### PR TITLE
Ensure `RID`, `Callable`, and `Signal` are stored as strings

### LINKED ISSUE #64442: RID as default value are empty in extension_api.json
### Godot version

4.0-rc13

### System information

n/a

### Issue description

RID as default value are not serialized properly, for instance `PhysicsServer2D::joint_make_pin`

```python
{
	"name": "joint_make_pin",
        [...]
	"arguments": [
		{
			"name": "joint",
			"type": "RID"
		},
		{
			"name": "anchor",
			"type": "Vector2"
		},
		{
			"name": "body_a",
			"type": "RID"
		},
		{
			"name": "body_b",
			"type": "RID",
			"default_value": ""  # <== ?????
		}
	]
},
```

This is because `Variant::get_construct_string` is use for the serialization which doesn't support serialization of `RID`:
https://github.com/godotengine/godot/blob/7c7ce7dcd7430d8503d6f74bb49c68892bc31dca/core/extension/extension_api_dump.cpp#L528

`Variant::get_construct_string` doesn't support serialization of `RID` and default to an empty string:
https://github.com/godotengine/godot/blob/7c7ce7dcd7430d8503d6f74bb49c68892bc31dca/core/variant/variant_parser.cpp#L1886-L1887

## The main issue

We represent the default value in ClassDB as an *instance* of `RID` which doesn't tell us we don't care about *this* instance (i.e. the default value is in fact "a new instance of `RID` is going to be created each time you call the function")

I think the easier solution would be to add a workaround in `extension_api_dump.cpp` (typically adding `"RID()"` as `default_value` if the argument type is `RID` and it has a default value set).

Of course this is not perfect given this way `extension_api.json` also don't provide the "this default value should be generated before each use". However we can fix this by adding a `reusable_default_value` boolean flag (that would only be true for RID).

## Bonus issue

I'm not sure why `Variant::get_construct_string` doesn't serialize `RID` :thinking:
It is also the case for `Callable` and `Signal`.

It means Dictionary/Array containing RID/Callable/Signal are not properly serialized as they will be displayed as `[, , ,]`

In the case this behavior is expected, shouldn't we add a warning when trying to serialize RID/Callable/Signal ?

### Steps to reproduce

n/a

### Minimal reproduction project

_No response_

### LINKED ISSUE #78380: Parse error when attempting to export var of Callable type in a resource
### Godot version

4.1.beta.a83eb16fb

### System information

Arch Linux

### Issue description

When attempting to have a scene load a resource that uses a script that exports a var of Callable type, a parse error will occur due to Callable not being serializable.

### Steps to reproduce

Create new project.
create a resource script that exports a Callable type:

```
class_name BreakStuff
extends Resource
@export var something: Callable
```

create a .tres file that uses the script.

create a scene that uses that resource, such as with a script like

```
extends Node
@export var stuff: Resource
```

set that resource to that .tres file.

close project and reopen.

Be greeted with error message about a parse error and be unable to open that scene.

Within plain text of .tscn file you can see a line that reads
something =

which causes a parse error as something has nothing to be set to.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Prevents parser errors in `.tscn` and `.tres` files where the assignment would otherwise be empty.

Using just `RID()` instead of storing the value, might do so only for the empty `RID`, it is required for default values to work in `GDExtension` as `RID`s cannot be created from integers just like in `GDScript`, but since we weren't serializing them at all anyway I went for a simple solution. This also fixes that serializing an array containing any of these types is broken with `var_to_str`, currently `var_to_str([Callable(), Signal(), RID()])`, results in `[, , ]`, now it will instead give `[Callable(), Signal(), RID()]`, though it does so regardless of the value, not attempting to serialize, but `var_to_str` doesn't handle references anyway as it is.

This also fixes hints in the editor, where before hints for these types for functions with defaults would not print anything.

We should probably not serialize these types on default in `GDScript` exports, but I don't know how to approach that so just fixing the immediate issue here to start with.

* Fixes: #78380 (Fixes the immediate issue)
* Fixes: #64442

### CODE REVIEW

File: core/variant/variant_parser.cpp [hunk 1]
```diff
@@ -865,13 +865,47 @@ Error VariantParser::parse_value(Token &token, Variant &value, Stream *p_stream,
 			}
 
 			get_token(p_stream, token, line, r_err_str);
-			if (token.type != TK_NUMBER) {
+			// Permit empty RID.
+			if (token.type == TK_PARENTHESIS_CLOSE) {
+				value = RID();
+				return OK;
+			} else if (token.type != TK_NUMBER) {
 				r_err_str = "Expected number as argument";
```
Comment (AThousandShips) [inline core/variant/variant_parser.cpp:873]:
```suggestion
				r_err_str = "Expected number as argument or ')'";
```
Or similar but unsure if required here

File: core/variant/variant_parser.cpp [hunk 2]
```diff
@@ -1832,6 +1866,17 @@ Error VariantWriter::write(const Variant &p_variant, StoreStringFunc p_store_str
 
 		} break;
 
+		// Do not really store these, but ensure that assignments are not empty.
+		case Variant::RID: {
+			p_store_string_func(p_store_string_ud, "RID()");
```
Comment (AThousandShips) [inline core/variant/variant_parser.cpp:1871]: Could  change this to only store `RID()` for the case where it is `RID(0)`, but unsure, elsewhere this parsing matches the general GDScript syntax, as mentioned in the main comment this simply avoids empty entries, as no serialization was done at all before, so I suggest approaching this separately later if desired

**Comment by AThousandShips** [comment]
Considering specifying this behavior on `var_to_str` like so:
```
[b]Note:[/b] This will return [code]RID()[/code], [code]Signal()[/code], and [code]Callable()[/code] for those types, regardless of the value, not storing any details about the actual value.
```

File: core/variant/variant_parser.cpp [hunk 3]
```diff
@@ -865,13 +865,47 @@ Error VariantParser::parse_value(Token &token, Variant &value, Stream *p_stream,
...
+			// Permit empty RID.
+			if (token.type == TK_PARENTHESIS_CLOSE) {
+				value = RID();
+				return OK;
+			} else if (token.type != TK_NUMBER) {
 				r_err_str = "Expected number as argument";
 				return ERR_PARSE_ERROR;
 			}
 
 			value = token.value;
```
Comment (AThousandShips) [inline core/variant/variant_parser.cpp:877]: Currently this *doesn't* load an `RID`, but an integer, unsure how to deal with that

**Comment by AThousandShips** [comment]
Added a fix to loading `RID` so it is typed as an `RID`, and also added support for storing them directly, storing `RID()` as such to ensure compatibility with `GDExtension`, also added documentation for the behavior, either of the second two commits are up for debate and will squash which ever are picked

File: core/variant/variant_parser.cpp (hunk 1 above)
Comment (KoBeWi) [reply core/variant/variant_parser.cpp:873]: Yes, the message needs to be updated.

File: doc/classes/@GlobalScope.xml [hunk 4]
```diff
@@ -1379,6 +1379,7 @@
 				    "b": 2
 				}
 				[/codeblock]
+				[b]Note:[/b] This will return [code]Signal()[/code] and [code]Callable()[/code] for those types, regardless of the value, not storing any details about the actual value.
```
Comment (KoBeWi) [inline doc/classes/@GlobalScope.xml:1382]: "for those types" is kind of unclear on what it refers to. Maybe something like
```suggestion
				[b]Note:[/b] Converting [Signal] or [Callable] is not supported and will result in empty value for these types, regardless of their data.
```
would be better.

**Review by KoBeWi — APPROVED** [review]

**Comment by AThousandShips** [comment]
Will squash if there's a consensus on the additional changes for storing `RID`s

**Review by akien-mga — APPROVED** [review]
Looks good to me. The RID parsing change seems OK, though we might want to add some more unit tests to validate this.

File: misc/extension_api_validation/4.0-stable.expected [hunk 5]
```diff
@@ -6,6 +6,34 @@ should instead be used to justify these changes and describe how users should wo
...
+Validate extension JSON: Error: Field 'classes/RenderingServer/methods/canvas_item_add_mesh/arguments/4': default_value changed value in new API, from "" to "RID()".
+Validate extension JSON: Error: Field 'classes/RenderingServer/methods/canvas_item_add_multimesh/arguments/2': default_value changed value in new API, from "" to "RID()".
+Validate extension JSON: Error: Field 'classes/RenderingServer/methods/canvas_item_add_polygon/arguments/4': default_value changed value in new API, from "" to "RID()".
+Validate extension JSON: Error: Field 'classes/RenderingServer/methods/canvas_item_add_triangle_array/arguments/7': default_value changed value in new API, from "" to "RID()".
+Validate extension JSON: Error: Field 'classes/RenderingServer/methods/instances_cull_aabb/arguments/1': default_value changed value in new API, from "" to "RID()".
+Validate extension JSON: Error: Field 'classes/RenderingServer/methods/instances_cull_convex/arguments/1': default_value changed value in new API, from "" to "RID()".
+Validate extension JSON: Error: Field 'classes/RenderingServer/methods/instances_cull_ray/arguments/2': default_value changed value in new API, from "" to "RID()".
+
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.0-stable.expected:36]: Haven't done any changes like this before, does this need to be clarified further? I have no experience with GDExtension here

**Comment by AThousandShips** [comment]
Will look at unit tests but at the moment I am lacking the energy most likely

File: misc/extension_api_validation/4.0-stable.expected (hunk 5 above)
Comment (AThousandShips) [reply misc/extension_api_validation/4.0-stable.expected:36]: Thank you! Was unsure how it was to be considered from a change/breaking perspective, will clarify
