### PR TITLE
glTF: Fix tangent generation for non-blend shapes

### LINKED ISSUE #32712: Navmesh not imported using glTF2 format in Godot 3.2 (regression from #30877)
**Godot version:**
Godot 3.2alpha1

**Issue description:**
Navmeshes are not correctly imported using the gltf2 format (from Blender 2.8 if it changes anything).
A NavigationMeshInstance is correctly created but the navmesh itself is not (ie blue polygons in the editor)
Using Godot 3.1 they are correctly imported so this is a regression bug. They seems to be correctly imported too using dae files.

**Steps to reproduce:**

Create a mesh in blender, add mesh with the -navmesh suffix, export to godot with gltf2 format.

**Minimal reproduction project**

[TestNavmesh3.2.zip](https://github.com/godotengine/godot/files/3712763/TestNavmesh3.2.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
PR #30877 was bogus as it made a blend shape-specific code block
apply to everything but blend shapes (as it seemed not to work
properly *for* blend shapes).

The proper fix should thus be to simply remove the problematic
block.

Fixes #32712.

### CODE REVIEW

File: editor/import/editor_scene_importer_gltf.cpp [hunk 1]
```diff
@@ -1083,13 +1083,6 @@ Error EditorSceneImporterGLTF::_parse_meshes(GLTFState &state) {
 				Ref<SurfaceTool> st;
 				st.instance();
 				st->create_from_triangle_arrays(array);
-				if (!p.has("targets")) {
```
Comment (akien-mga) [inline editor/import/editor_scene_importer_gltf.cpp]: For the reference, before #30877, this line was:
```
if (p.has("targets")) {
```
which makes sense with the following comment which mention morph targets explicitly.

File: editor/import/editor_scene_importer_gltf.cpp [hunk 2]
```diff
@@ -1075,24 +1075,15 @@ Error EditorSceneImporterGLTF::_parse_meshes(GLTFState &state) {
 				array[Mesh::ARRAY_INDEX] = indices;
 			}
 
-			bool generated_tangents = false;
-			Variant erased_indices;
+			bool generate_tangents = (primitive == Mesh::PRIMITIVE_TRIANGLES && !a.has("TANGENT") && a.has("TEXCOORD_0") && a.has("NORMAL"));
 
-			if (primitive == Mesh::PRIMITIVE_TRIANGLES && !a.has("TANGENT") && a.has("TEXCOORD_0") && a.has("NORMAL")) {
+			if (generate_tangents) {
```
Comment (akien-mga) [inline editor/import/editor_scene_importer_gltf.cpp]: This is just refactoring, no logic change.

**Comment by akien-mga** [comment]
If anyone has glTF test files that require tangent generation and with use or don't use blend shapes, that would be great to test this PR.

**Comment by akien-mga** [comment]
I'll merge and cherry-pick for 3.2.2 beta 2 to get wider testing.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
