### PR TITLE
[Autocomplete] Avoid prepending literals when the character has already been typed

### LINKED ISSUE #92538: Editing StringName argument adds extra `&`
### Tested versions

4.3 dev6

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

From #66481

https://github.com/godotengine/godot/assets/2223172/2f9de3bd-4632-4208-9587-bd03094dfa7c

Notice how quotes are correct, but the prefix is not.

### Steps to reproduce

1. Write some method with StringName argument and completion (e.g. `is_action_pressed()`) and use some argument
2. Move caret inside the string and autocomplete for different argument

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #107758: Extra caret/hat (^) added on completion inside quotes when add_node_path_literals is on
### Tested versions

Reproduced in
- v4.5.beta1.official [46c495ca2]
- v4.4.1.stable.fedora [49a5bc7b6]

### System information

Godot v4.4.1.stable (49a5bc7b6) - Fedora Linux 42 (Workstation Edition) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 threads)

### Issue description

It's a script editor bug. When editor setting _text_editor/completion/add_node_path_literals_ is on, code-completing a node path literal inside an existing one adds a redundant prefix `^` again.

Video demo:

https://github.com/user-attachments/assets/c1b5d915-2e8f-400d-8fd3-b4a0f63f9606

### Steps to reproduce

In script editor: 
1. Type: `get_node(^".")`
2. Remove content inside the quotes: `get_node(^"")`.
3. Place text cursor between the quotes and fire _ui_text_completion_query_ (usually [Ctrl]+[Space]).
4. Pick any option.
5. Get double-caret prefixed literal, e.g.: `get_node(^^".")`

### Minimal reproduction project (MRP)

n/a (the bug is visible in a brand new project or any project with a node)

### PR DESCRIPTION
**Pull request by Thought-Weaver**
When trying to autocomplete node paths and string literals in a script editor when the relevant editor settings were enabled, if you had already typed ^"" or &"", autocomplete would insert another character to make it ^^"..." or &&"...", causing a syntax error.

The autocomplete functions weren't previously checking the type of the literal that the user had entered, so there wasn't a way to validate whether the character was already prepended or not.

https://github.com/user-attachments/assets/64ea5257-62e4-4c22-b429-d7ba4e991d7f

Fixes: https://github.com/godotengine/godot/issues/107758

_Bugsquad edit:_
- _Supersedes https://github.com/godotengine/godot/pull/92586_
- _Fixes https://github.com/godotengine/godot/issues/92538_

### CODE REVIEW

**Comment by Thought-Weaver** [comment]
This is my first time working in Godot's codebase! Any and all feedback on this approach to refine it further is appreciated. Thank you in advance!

I'm especially wondering about the most appropriate type for the script language extension is, since default ints aren't supported, and if there are any other cases where it might benefit to have this context so the editor can be cleverer about autocompletion.

EDIT: Thanks for the feedback! Now we don't have to worry about the ints being passed around and will instead rely on a less brute-force method via the parsed literal type.

File: core/object/script_language.h [hunk 1]
```diff
@@ -336,7 +336,7 @@ class ScriptLanguage : public Object {
 		TypedArray<int> charac;
 	};
 
-	virtual Error complete_code(const String &p_code, const String &p_path, Object *p_owner, List<CodeCompletionOption> *r_options, bool &r_force, String &r_call_hint) { return ERR_UNAVAILABLE; }
+	virtual Error complete_code(const String &p_code, const int p_line, const int p_column, const String &p_path, Object *p_owner, List<CodeCompletionOption> *r_options, bool &r_force, String &r_call_hint) { return ERR_UNAVAILABLE; }
```
Comment (dalexeev) [inline core/object/script_language.h]: This breaks compatibility (`GDVIRTUAL_BIND` below) and if I remember correctly it is not needed, the cursor position is represented by the `U+FFFF` character.

Comment (Thought-Weaver) [reply core/object/script_language.h]: Is the cursor (0xFFFF) always included in p_code? I might have missed where it gets added, but that would clean up these changes substantially if that's true.

EDIT: I think I see what I missed! This should be easy to clean up.

File: editor/plugins/script_text_editor.cpp [hunk 2]
```diff
@@ -2349,7 +2349,9 @@ void ScriptTextEditor::drop_data_fw(const Point2 &p_point, const Variant &p_data
 
 	if (type == "obj_property") {
 		bool add_literal = EDITOR_GET("text_editor/completion/add_node_path_literals");
-		text_to_drop = add_literal ? "^" : "";
+		const String &line_to_caret = te->get_line(drop_at_line).substr(0, drop_at_column);
+		bool already_has_literal = line_to_caret.ends_with("^\"") || line_to_caret.ends_with("^'");
+		text_to_drop = add_literal && !already_has_literal ? "^" : "";
```
Comment (HolonProduction) [inline editor/plugins/script_text_editor.cpp]: This has nothing to do with the auto completion issue. And at least in 4.4.1 dropping a property in between quotes does still drop the additional quotes from the property so having this content aware is no feature at the moment. It should be tackled in a separate PR IMO

**Review by HolonProduction — COMMENTED** [review]
I don't think that doing additional checks on the code is a good idea. Autocompletion should work with the parse tree instead. In the cases were we do not want the additional path char there has to exist a literal node already so the check should just be based on `completion_context.current_node` being a node path or string literal.

Edit: Why is this better:
- the node gives us a view into the code that is far more stable than relying on own analysis of the line
- the node gives us positions of the literal, this is not important at the moment, but it will be in the future once we transition the LSP to calculate the insertion diff completely on the server side

File: editor/plugins/script_text_editor.cpp (hunk 2 above)
Comment (Thought-Weaver) [reply editor/plugins/script_text_editor.cpp]: Trying to use the parsed expression for the node path was the first thing I tried! But it seems the prepended symbol is being discarded -- it didn't appear as part of the string when converting the value of the node. It seemed much less risky to make a change to how autocomplete worked as part of the code editor than to make a change to GDScript's parser.

Comment (Thought-Weaver) [reply editor/plugins/script_text_editor.cpp]: Ah wait, this is probably because in my first attempt it looks like I used the reduced expression rather than guessing the expression type and using the value. If that works, I'll definitely switch over -- I'd much prefer to use the parser's context.

EDIT: No, that doesn't seem to have worked either -- it's still missing from the node's value when guessing the expression type of the argument passed to the call.

Comment (HolonProduction) [reply editor/plugins/script_text_editor.cpp]: You should have a `LiteralNode` which contains an arbitrary `Variant` value. You should be able to check the variant type of this value to get the required info.

If that does not work for some reason you can still use the location information of the node to check whether the source code contains the characters you are looking for.

Consider this case: (cursor is `|`) `^"a|"` now your spitted line does not begin with `^"` anymore. With your current approach you will end up writing a second string parser if you want to do it correctly. That's just not feasible since GDScript strings are complex. Take for example `""" ^"| """`.

Comment (Thought-Weaver) [reply editor/plugins/script_text_editor.cpp]: Perhaps I'm missing something, but in various attempts to evaluate the value of the argument in the call function, it hasn't included the character -- which I've found a bit odd because I agree that the literal should be the actual value of the string that the parser has parsed, unless there's a good reason to discard the prepended character:

```
if (_guess_expression_type(p_context, p_call->arguments[p_argidx], value)) {
	if (value.type.is_constant) {
		const String &literal_value = value.value; // Doesn't contain '^'
		if (literal_value[0] != '^') {
			opt = "^" + opt;
		}
	}
}
```

Is there another method I'm not seeing or a means of accessing the literal value directly? I fully agree with all your points, but like I said, I tried doing it that way initially and ran into these same issues.

String complexities could be avoided by using the current argument value for a more complex search, but that gets even deeper into the territory of relying on context from the code string itself.

Comment (HolonProduction) [reply editor/plugins/script_text_editor.cpp]: You don't have to guess any types here. String literals are already resolved to their runtime value by the tokenizer. So what you should be doing is something like (untested, actually location of the enums and such might be slightly different but the idea should be clear)
```c++
// GDSP = GDScriptParser for sake of brevity
if(p_call->arguments[p_argidx].type == GDSP::Node::LITERAL) {
    GDSP::LiteralNode *literal = static_cast<GDSP::LiteralNode *>(p_call->arguments[p_argidx]);
    Variant literal_value = literal->value;
    if(literal_value.type == Variant::STRING_NAME) {
        ...
    }
}
```

Although I'd recommend to skip the roundtrip through a call node and use `completion_context.current_node` directly, since this logic has nothing to do with calls, it just so happens that we only have string completion in calls at the moment.

Comment (Thought-Weaver) [reply editor/plugins/script_text_editor.cpp]: I tried this approach as well, and it yielded the same result: The argument is a `NodePath` and the character isn't part of the literal value. Also, wouldn't the `node` from the parser context in the reported bug case in `_find_call_arguments` be a `Call`? Maybe there's something about the parser I'm misunderstanding.

I'll keep digging and see if there's a way to get the right value or context from the parser, but I'm not currently sure it's available.

Comment (HolonProduction) [reply editor/plugins/script_text_editor.cpp]: > The argument is a NodePath and the character isn't part of the literal value.

Why is it important to have the `^` character as part of some value? The fact that the literal is a `NodePath` tells us that `^` is present in the source code. If the literal was a `StringName` the `&` character would be part of the source code and if it was a `String` none of those characters are present in the source code. Shouldn't that be enough information?



> Also, wouldn't the `node` from the parser context in the reported bug case in `_find_call_arguments` be a `Call`?

Yeah my bad, sorry. Usually completion_context.node contains the node under the cursor, but in some completion types it's used differently. Seems like for call arguments it just contains the call.

Comment (Thought-Weaver) [reply editor/plugins/script_text_editor.cpp]: Ah, I see! That's what I was misunderstanding: I thought the argument type would always be a `NodePath` not realizing that's the case iff the character exists. Let me give that a shot -- thanks for the clarification!

Comment (Thought-Weaver) [reply editor/plugins/script_text_editor.cpp]: https://github.com/user-attachments/assets/b8144ca3-5709-4aed-a2f6-2fa725124133

Alright! Updated and tested the latest fix -- thanks @HolonProduction for helping clarify that detail, it was exactly what I needed to use the parsed types. Let me know if there's anything else I should pare down!

File: modules/gdscript/tests/scripts/completion/argument_options/string_literals/add_node_path_tween.gd [hunk 3]
```diff
@@ -5,4 +5,4 @@ const A = preload("res://completion/class_a.notest.gd")
 func _ready() -> void:
     var a := A.new()
     var tween := get_tree().create_tween()
-    tween.tween_property(a, ➡)
+    tween.tween_property(a, "➡")
```
Comment (HolonProduction) [inline modules/gdscript/tests/scripts/completion/argument_options/string_literals/add_node_path_tween.gd]: Why change this test? In particular you are removing all instances of argument option completion without quotes from the tests. Especially for tween this would make this test identical to `argument_options_inside_string_literal.gd`

File: modules/gdscript/tests/scripts/completion/argument_options/string_literals/add_string_name_input_event.gd [hunk 4]
```diff
@@ -1,3 +1,3 @@
 func _input(event: InputEvent) -> void:
-    event.is_action_pressed(➡)
+    event.is_action_pressed("➡")
```
Comment (HolonProduction) [inline modules/gdscript/tests/scripts/completion/argument_options/string_literals/add_string_name_input_event.gd]: Same

File: modules/gdscript/gdscript_editor.cpp [hunk 5]
```diff
@@ -2954,11 +2961,11 @@ static void _find_call_arguments(GDScriptParser::CompletionContext &p_context, c
 
 				if (p_argidx == 1 && p_context.node && p_context.node->type == GDScriptParser::Node::CALL && ClassDB::is_parent_class(class_name, SNAME("Tween")) && p_method == SNAME("tween_property")) {
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_editor.cpp]: If you don't use `p_context.node` anymore, the check of `p_context.node->type` should be removed.

File: modules/gdscript/gdscript_editor.cpp [hunk 6]
```diff
@@ -2854,9 +2854,10 @@ static void _find_enumeration_candidates(GDScriptParser::CompletionContext &p_co
 	}
 }
 
-static void _find_call_arguments(GDScriptParser::CompletionContext &p_context, const GDScriptCompletionIdentifier &p_base, const StringName &p_method, int p_argidx, bool p_static, HashMap<String, ScriptLanguage::CodeCompletionOption> &r_result, String &r_arghint) {
+static void _find_call_arguments(GDScriptParser::CompletionContext &p_context, const GDScriptCompletionIdentifier &p_base, const GDScriptParser::CallNode *p_call, int p_argidx, bool p_static, HashMap<String, ScriptLanguage::CodeCompletionOption> &r_result, String &r_arghint) {
 	Variant base = p_base.value;
 	GDScriptParser::DataType base_type = p_base.type;
+	const StringName &p_method = p_call->function_name;
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_editor.cpp]: The `p_` prefix is for parameters. Should be renamed to just `method`.

File: modules/gdscript/gdscript_editor.cpp [hunk 7]
```diff
@@ -2978,7 +2985,10 @@ static void _find_call_arguments(GDScriptParser::CompletionContext &p_context, c
 									}
 									String name = E.name.quote(quote_style);
 									if (use_node_paths) {
-										name = "^" + name;
+										GDScriptParser::LiteralNode *literal = static_cast<GDScriptParser::LiteralNode *>(p_call->arguments[p_argidx]);
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_editor.cpp]: This part is missing validity checks and can crash. You need to ensure, that `p_argidx` is actually an index of `p_call->arguments`. e.g. `get_node(|)` will have 0 as argidx but no arguments stored with the node. Also before static casting AST nodes you need to check that they are of the correct type: `node->type == GDScriptParser::Node::LITERAL`.

File: modules/gdscript/tests/test_completion.h [hunk 8]
```diff
@@ -113,6 +113,7 @@ static void test_directory(const String &p_dir) {
 			code = code.replace_first(String::chr(0x27A1), String::chr(0xFFFF));
 			// Require pointer sentinel char in scripts.
 			int location = code.find_char(0xFFFF);
+
```
Comment (HolonProduction) [inline modules/gdscript/tests/test_completion.h]:
```suggestion
```

File: modules/gdscript/gdscript_editor.cpp [hunk 9]
```diff
@@ -2854,9 +2854,10 @@ static void _find_enumeration_candidates(GDScriptParser::CompletionContext &p_co
 	}
 }
 
-static void _find_call_arguments(GDScriptParser::CompletionContext &p_context, const GDScriptCompletionIdentifier &p_base, const StringName &p_method, int p_argidx, bool p_static, HashMap<String, ScriptLanguage::CodeCompletionOption> &r_result, String &r_arghint) {
+static void _find_call_arguments(GDScriptParser::CompletionContext &p_context, const GDScriptCompletionIdentifier &p_base, const GDScriptParser::CallNode *p_call, int p_argidx, bool p_static, HashMap<String, ScriptLanguage::CodeCompletionOption> &r_result, String &r_arghint) {
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_editor.cpp]: `_find_call_argument` has two overloads. The other one already takes a call node. The change makes sense, but we should probably rename this method to `_list_call_arguments` to prevent confusion with those two overloads (the other one guesses the base type and such and then calls to this one which actually adds all the options to the list).

**Review by HolonProduction — CHANGES_REQUESTED** [review]
The approach looks good now, but the implementation is still missing some essential checks to prevent edge case crashes.

File: modules/gdscript/tests/scripts/completion/argument_options/string_literals/add_node_path_tween.gd (hunk 3 above)
Comment (Thought-Weaver) [reply modules/gdscript/tests/scripts/completion/argument_options/string_literals/add_node_path_tween.gd]: Reverted!

File: modules/gdscript/gdscript_editor.cpp (hunk 6 above)
Comment (Thought-Weaver) [reply modules/gdscript/gdscript_editor.cpp]: Fixed! I thought that was the case, but hadn't renamed it after updating the argument to pass the Call node.

File: modules/gdscript/gdscript_editor.cpp (hunk 7 above)
Comment (Thought-Weaver) [reply modules/gdscript/gdscript_editor.cpp]: Gotcha, I've added in safety checks now, but let me know if I missed anything!

File: modules/gdscript/gdscript_editor.cpp (hunk 9 above)
Comment (Thought-Weaver) [reply modules/gdscript/gdscript_editor.cpp]: Updated! I did find that a bit confusing but thought there might be a good reason for it.

**Review by HolonProduction — APPROVED** [review]
Seems to work correctly based on my testing. Code looks good to me.

@Thought-Weaver you will need to squash your commits.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
