### PR TITLE
Ignore custom tooltip if its text is empty in signals tab

### LINKED ISSUE #99945: Hovering over the empty space of the signals dock shows an empty tooltip
### Tested versions

v4.4.dev.custom_build [0f20e67d8]

### System information

Godot v4.4.dev (0f20e67d8) - macOS 15.1.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

Image

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by hakro**
Fixes #99945

### CODE REVIEW

File: editor/connections_dialog.cpp [hunk 1]
```diff
@@ -907,7 +907,7 @@ ConnectDialog::~ConnectDialog() {
 
 Control *ConnectionsDockTree::make_custom_tooltip(const String &p_text) const {
 	// If it's not a doc tooltip, fallback to the default one.
-	if (p_text.contains("::")) {
+	if (p_text.contains("::") || p_text.is_empty()) {
```
Comment (AThousandShips) [inline editor/connections_dialog.cpp:910]:
```suggestion
	if (p_text.is_empty() || p_text.contains("::")) {
```

**Review by AThousandShips — APPROVED** [review]
Makes sense to me

**Review by jfmelo — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
