### PR TITLE
Fix inaccurate tree relationship lines

### LINKED ISSUE #116031: Right-to-Left trees' relationship lines are inaccurate.
### Tested versions

Reproducible in v4.6 stable, v4.7 dev.

### System information

Win11

### Issue description

When using Right-to-Left and setting `draw all relationship lines` to `All`, you will see trees' relationship lines are inaccurate. Some lines overlap.
LTR modern:

Image

LTR classic:

Image

RTL modern:

Image

RTL classic:

Image

### Steps to reproduce

Turn on Right-to-Left.
Set `draw all relationship lines` to `All`.
You will see inaccurate relationship lines.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by BrotherShort**
Fix #116031.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -2091,6 +2091,13 @@ Point2i Tree::convert_rtl_position(const Point2i &pos, int width) const {
 	return pos;
 }
 
+Point2 Tree::convert_rtl_position(const Point2 &pos, int width) const {
```
Comment (AThousandShips) [inline scene/gui/tree.cpp]:
```suggestion
Point2 Tree::convert_rtl_position(const Point2 &p_pos, int p_width) const {
```

**Review by bruvzg — APPROVED** [review]

File: scene/gui/tree.h [hunk 2]
```diff
@@ -569,6 +569,7 @@ class Tree : public Control {
 	int compute_item_height(TreeItem *p_item) const;
 	int get_item_height(TreeItem *p_item) const;
 	Point2i convert_rtl_position(const Point2i &pos, int width = 0) const;
+	Point2 convert_rtl_position(const Point2 &pos, int width = 0) const;
```
Comment (AThousandShips) [inline scene/gui/tree.h]:
```suggestion
	Point2 convert_rtl_position(const Point2 &p_pos, int p_width = 0) const;
```

File: scene/gui/tree.cpp (hunk 1 above)
Comment (AThousandShips) [inline scene/gui/tree.cpp]:
```suggestion
Point2 Tree::convert_rtl_position(const Point2 &p_pos, int p_width) const {
```

File: scene/gui/tree.h (hunk 2 above)
Comment (BrotherShort) [reply scene/gui/tree.h]: Done.

File: scene/gui/tree.cpp (hunk 1 above)
Comment (BrotherShort) [reply scene/gui/tree.cpp]: Done.
