### PR TITLE
[Web] Use actual `PThread` pool size for `get_default_thread_pool_size()`

### LINKED ISSUE #104004: Worker threads block the main thread if started from Area2D.body_entered/RigidBody2D.body_entered on Web
### Tested versions

- Reproducible in: v4.3.dev3.official [36e943b6b], v4.3.dev4.official [df78c0636], v4.3.beta2.official [b75f0485b], v4.3.stable.official [77dcf97d8], v4.4.stable.official [4c311cbee]
- Not reproducible in: v4.2.2.stable.official [15073afe3], v4.3.dev1.official [9d1cbab1c], v4.3.dev2.official [352434668]
- Likely introduced in v4.3.dev3.official [36e943b6b]

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21916.1002) - AMD Ryzen 7 5800H with Radeon Graphics (16 threads)

### Issue description

When a `RigidBody2D.body_entered` or `Area2D.body_entered` signal calls a function that contains a call to `WorkerThreadPool.start_task`, the worker thread will seemingly block the main thread until the task is completed. This only appears to happen when the game is exported to Web.

### Steps to reproduce

1. Have a `RigidBody2D` or `Area2D`, and connect the `body_entered` signal to the script
2. Have the function that is called by the signal start a worker thread task
3. Export the game to Web, start the game on Web, and try to trigger the `body_entered` signal
4. Observe that the game freezes when you do that

Example code:
```gdscript
extends Node

func _on_area_2d_body_entered(body):
	WorkerThreadPool.add_task(do_nothing_for_5_seconds)

func do_nothing_for_5_seconds():
	var t = Time.get_ticks_msec()
	while Time.get_ticks_msec() - t < 5000:
		pass
```

Also note that this still happens even if starting the worker thread task is in a deferred call, like so:
```gdscript
extends Node

func _on_area_2d_body_entered(body):
	call_deferred("start_task")

func start_task():
	WorkerThreadPool.add_task(do_nothing_for_5_seconds)

func do_nothing_for_5_seconds():
	var t = Time.get_ticks_msec()
	while Time.get_ticks_msec() - t < 5000:
		pass
```

**Instructions on how to use the MRP are included in the project itself as a help window.**

### Minimal reproduction project (MRP)

[Download mrp.zip](https://github.com/user-attachments/files/19199960/mrp.zip)

Image

Things to note:
- Whenever I move the green logo over the red logo, it freezes the game because a worker thread task was started when `Area2D.body_entered` emitted, and that worker thread (whose task lasts 5 seconds) ends up blocking the main thread for no reason.
- Whenever I move my mouse over the cyan logo, it also starts a worker thread task that lasts for 5 seconds, but it does not block the main thread because it was initiated by `CollisionBody2D.mouse_entered` rather than `Area2D.body_entered`/`RigidBody2D.body_entered`.

### LINKED ISSUE #104428: Crash on Web Export (Wasm) when using Physics Thread + CharacterBody3D + CollisionShape3D
### Tested versions

- Godot 4.4.stable.official.4c311cbee (Linux build)

### System information

Godot v4.4.stable - Ubuntu 24.04.2 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU - 13th Gen Intel(R) Core(TM) i9-13900H (20 threads)

### Issue description

When exporting to the Web (Wasm) with “Physics > 3D > Run on Separate Thread” enabled, the game freezes shortly after launch.

The issue occurs when a `CharacterBody3D` with a `CollisionShape3D` is present and interacts with a `StaticBody3D`. This only happens in Web Export (Wasm), while the same setup works correctly on native platforms.

There is no visible error or crash message — the browser tab simply freezes and becomes unresponsive, requiring manual closure.

Disabling “Run on Separate Thread” or removing the `CollisionShape3D` prevents the freeze.

### Steps to reproduce

1. Open the attached minimal reproduction project.  
2. Export the project for Web (Wasm).  
3. Run it in the browser:  `./serve.py`
5. Game crashes shortly after load

**No physics 3D thread**
Image

**With physics 3D thread enabled**
Image

### Minimal reproduction project (MRP)

[physics-thread-wasm-bug.zip](https://github.com/user-attachments/files/19386845/physics-thread-wasm-bug.zip)

### PR DESCRIPTION
**Pull request by marcosc90**
fixes #104428

This resolves a freeze in WebAssembly builds when `physics/3d/run_on_separate_thread=true` and threading is enabled.

Previously, `get_default_thread_pool_size()` in `OS_Web` was hardcoded to return 1, which caused physics step group tasks to stall. The only available worker was occupied by this long-lived task:

https://github.com/godotengine/godot/blob/2303ce843a362cf5497ca3336451de23793eb711/servers/physics_server_3d_wrap_mt.cpp#L42-L47

As a result, the following task 

https://github.com/godotengine/godot/blob/2303ce843a362cf5497ca3336451de23793eb711/modules/godot_physics_3d/godot_step_3d.cpp#L347

would never execute, leading to a deadlock. This patch replaces the hardcoded value with a dynamic call to a JS hook that reflects the available pthread pool size at runtime.

_bugsquad edit: fixes https://github.com/godotengine/godot/issues/104004_

### CODE REVIEW

File: platform/web/js/libs/library_godot_os.js [hunk 1]
```diff
@@ -346,6 +346,16 @@ const GodotOS = {
 		return concurrency < 2 ? concurrency : 2;
 	},
 
+	godot_js_os_pthread_pool_size_get__proxy: 'sync',
+	godot_js_os_pthread_pool_size_get__sig: 'i',
+	godot_js_os_pthread_pool_size_get: function () {
+		if (typeof PThread !== 'undefined' && PThread.runningWorkers && PThread.unusedWorkers) {
+			const total = PThread.runningWorkers.length + PThread.unusedWorkers.length;
+			return Math.max(1, total - 1);
```
Comment (marcosc90) [inline platform/web/js/libs/library_godot_os.js:354]: I'm being slightly defensive here by returning (total - 1) instead of the full thread count. While the sample in #104428 doesn't freeze with the full pool size, in my actual project it consistently hangs unless one thread is reserved.

**Comment by adamscott** [comment]
For reference, [here's the PR](https://github.com/godotengine/godot/pull/54499) that introduced the static `1` value.

File: platform/web/js/libs/library_godot_os.js [hunk 2]
```diff
@@ -346,6 +346,16 @@ const GodotOS = {
...
+		}
+		return 1;
+	},
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_os.js:357]:
```suggestion
	godot_js_os_pthread_pool_size_get: function () {
		if (typeof PThread === 'undefined') {
		    // Threads aren't supported, so default to `1`.
			return 1;
		}
		const total = PThread.runningWorkers.length + PThread.unusedWorkers.length;
		return Math.max(1, total - 1);
	},
```

- I think we should always prefer early exiting.
- `if (PThread == null)` could be valid too, but I'm not _that_ nitpicky.

It seems that you can trust that `Pthread.{runningWorkers,unusedWorkers}` exist. I didn't see anything [in the emscripten source code](https://github.com/emscripten-core/emscripten/) that suggests that these could be anything else than arrays.

File: platform/web/os_web.cpp [hunk 3]
```diff
@@ -148,6 +148,10 @@ String OS_Web::get_unique_id() const {
 	ERR_FAIL_V_MSG("", "OS::get_unique_id() is not available on the Web platform.");
 }
 
+int OS_Web::get_default_thread_pool_size() const {
+	return godot_js_os_pthread_pool_size_get();
+}
```
Comment (adamscott) [inline platform/web/os_web.cpp:153]: We don't even have to query JavaScript as we already know the answer.

```suggestion
int OS_Web::get_default_thread_pool_size() const {
#ifdef THREADS_ENABLED
	return godot_js_os_pthread_pool_size_get();
#else // Threads disabled.
	return 1;
#endif
}
```

**Review by adamscott — COMMENTED** [review]
I don't have an answer directly for https://github.com/godotengine/godot/pull/104458/files#r2008222268 though.

File: platform/web/js/libs/library_godot_os.js (hunk 1 above)
Comment (adamscott) [reply platform/web/js/libs/library_godot_os.js:354]: > in my actual project it consistently hangs unless one thread is reserved.
You mean without doing `Math.max(1, total - 1)`?

File: platform/web/js/libs/library_godot_os.js (hunk 2 above)
Comment (marcosc90) [reply platform/web/js/libs/library_godot_os.js:357]: I agree, I was being a bit more defensive than usual since wasn't sure in which emscripten version it was added.

Comment (adamscott) [reply platform/web/js/libs/library_godot_os.js]: Oh, didn't think about that. Mmmm. I'll investigate.

Comment (adamscott) [reply platform/web/js/libs/library_godot_os.js]: https://github.com/emscripten-core/emscripten/blame/62d4b1cc0b98d2a2ccdd59e0fc24d76703e1d866/src/lib/libpthread.js#L79-L81

I think we're OK! :)

File: platform/web/js/libs/library_godot_os.js (hunk 1 above)
Comment (marcosc90) [reply platform/web/js/libs/library_godot_os.js]: Correct, didn't investigate any further being honest.

**Comment by marcosc90** [comment]
Pushed again to fix lint issues from suggested changes in the review.

File: platform/web/js/libs/library_godot_os.js [hunk 4]
```diff
@@ -346,6 +346,17 @@ const GodotOS = {
...
 
+	godot_js_os_pthread_pool_size_get__proxy: 'sync',
+	godot_js_os_pthread_pool_size_get__sig: 'i',
+	godot_js_os_pthread_pool_size_get: function () {
+		if (typeof PThread === 'undefined') {
+			// Threads aren't supported, so default to `1`.
+			return 1;
+		}
+		const total = PThread.runningWorkers.length + PThread.unusedWorkers.length;
+		return Math.max(1, total - 1);
```
Comment (clayjohn) [inline platform/web/js/libs/library_godot_os.js:357]: cc @Faless. Can you confirm that this avoids the problem you identified in https://github.com/godotengine/godot/pull/54499 It seems like we are querying the number of web workers allocated by emscriptem rather than just querying the number of processors. That sounds like the right solution to me, but I am not well versed in Javascript/emscriptem.

Bottom line, we can't use only one thread in the WTP. We generally need at least 3 (in the case the separate rendering thread and separate physics thread are enabled.

Comment (marcosc90) [reply platform/web/js/libs/library_godot_os.js:357]: I comment about this [here](https://github.com/godotengine/godot/pull/104458#discussion_r2008222268), but I'm still unsure since the actual thread pool is hardcoded to 8 even if the user has less processors.

What we can do though is change `-sPTHREAD_POOL_SIZE=8` to

```
-sPTHREAD_POOL_SIZE=Math.max(3, Math.min(8, navigator.hardwareConcurrency))
```

See: https://github.com/emscripten-core/emscripten/blob/36423eb7efbecfb901300dd65d3f06967fafd984/src/settings.js#L1667-L1675

Comment (marcosc90) [reply platform/web/js/libs/library_godot_os.js:357]: @clayjohn pushed with

```
-sPTHREAD_POOL_SIZE=Math.min(8,navigator.hardwareConcurrency)
```
Which results in the following emscripten code:
```js
var pthreadPoolSize=Math.min(8,navigator.hardwareConcurrency)
```

I removed the `Math.max(3,...)`  because if the user does not have 3 cores, then it doesn't matter whether it's 3 or 1 the threadpool size. If the minimum required for multithreading is 3, the engine should fallback to single threaded, but I think that's outside of the scope of this PR (not sure whether that logic is implemented already)

**Comment by Faless** [comment]
Hi @marcosc90 , thank you for looking into this issue.

I will start with some context, but first, I didn't realize you could pass an expression as `PTHREAD_POOL_SIZE`, that is indeed much better than an hardcoded value. This also means we could expose it to the JS support code and make it configurable on export **which is great** :fireworks: .

Now for some context...

---

Most browsers have a hard cap on threads, historically, that cap has been quite low.
When hardware concurrency is capped the value of `navigator.hardwareConcurrency` [may be the cap](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency#value) (**may**, i.e. `hardwareConcurrency` may in fact be more than the cap).
This means we can't trust too much the value of `navigator.hardwareConcurrency`.

On the web, threads are spawned asynchronously, so code like:
```
thread.start(something)
// STUFF appends without returning the main loop
thread.join()
```
Will produce a deadlock.

This is why emscripten introduced the [PTHREAD_POOL_SIZE](https://emscripten.org/docs/tools_reference/settings_reference.html#pthread-pool-size) option.

But this means that any thread spawned in addition to the PTHREAD_POOL_SIZE, will still cause deadlocks when occurring in the above scenario.

The issue we historically had with the godot thread pool was it filling the emscripten thread pool size, causing deadlocks in other parts of the engine (where the aformentioned start/join was used, sometimes by third party libraries).
This was made worse by the fact that we were using multiple WorkerThreadPools in the past (I don't know if that's the case anymore).

So, in general, we need to find a good trade-off, and that's not easy to find.

---

With this in mind, I suggest we may just want to make both values customizable via JS via `platform/web/js/engine/config.js`.

We can set those value to a reasonable defeault (8 for the emscripten pool, 4 for the godot pool).

We can make the value customizable when exporting via the editor by adding the values to the config in EditorExportPlatformWeb

We can also optionally add more logic (in a follow up PR) to EditorExportPlatformWeb to throw an error/warning if values are set too small for the current project settings.

We could also explore building with [PTHREAD_POOL_SIZE_STRICT](https://emscripten.org/docs/tools_reference/settings_reference.html#pthread-pool-size-strict) but that probably deserves its own discussion.

Let me know what you think.

**Comment by marcosc90** [comment]
Hi @Faless, that sounds good to me since currently on my custom build I'm using some custom values, so making the customizable would be great.

I'm not yet familiar with how all the settings work in godot, to confirm, do you mean adding those configs to the export template settings?

image

Just below Thread Support, adding something like:
- Emscripten Pool Size: 8
- Godot Pool Size: 4

**Comment by Faless** [comment]
> I'm not yet familiar with how all the settings work in godot, to confirm, do you mean adding those configs to the export template settings?
>
> Just below Thread Support, adding something like:
> 
>     * Emscripten Pool Size: 8
> 
>     * Godot Pool Size: 4

Yes, that's indeed what I've been thinking

**Comment by marcosc90** [comment]
I've been quite busy, I'll try to get this done during the weekend.

**Comment by marcosc90** [comment]
Just pushed some changes. I'm not really sure if this is exactly how configs should be passed, it is working correctly in any case. 

image

I'm not good with public docs, so please feel free to add the description for both settings, I enabled "Allow edits"

**Comment by Faless** [comment]
Please apply the following patch so we don't pollute `window`.

[patch.diff.txt](https://github.com/user-attachments/files/20205586/patch.diff.txt)

**Comment by marcosc90** [comment]
Much better, thanks @Faless . I was looking for a better way, but was still figuring it out how all the code glues together.

File: platform/web/doc_classes/EditorExportPlatformWeb.xml [hunk 5]
```diff
@@ -86,6 +86,12 @@
 			If [code]true[/code], the exported game will support threads. It requires [url=https://web.dev/articles/coop-coep]a "cross-origin isolated" website[/url], which may be difficult to set up and is limited for security reasons (such as not being able to communicate with third-party websites).
 			If [code]false[/code], the exported game will not support threads. As a result, it is more prone to performance and audio issues, but will only require to be run on an HTTPS website.
 		</member>
+		<member name="variant/emscripten_pool_size" type="int" setter="" getter="">
+			TODO
+		</member>
+		<member name="variant/godot_pool_size" type="int" setter="" getter="">
+			TODO
```
Comment (clayjohn) [inline platform/web/doc_classes/EditorExportPlatformWeb.xml:93]: Something like "Override for the default size of the WorkerThreadPool. This setting is used when the WorkerThreadPool size is set to -1 (which it is by default). This size must be smaller than [member variant/emscripten_pool_size] otherwise deadlocks may occur. When using threads this size needs to be large enough to accommodate features that rely on having a dedicated thread like [member ProjectSettings.physics/2d/run_on_separate_thread] or [member ProjectSettings.rendering/driver/threads/thread_model]. In general, it is best to ensure that this is at least 4 and is at least at least 2 or three less than [member variant/emscripten_pool_size]."

@Faless How does that sound?

File: platform/web/doc_classes/EditorExportPlatformWeb.xml [hunk 6]
```diff
@@ -86,6 +86,12 @@
 			If [code]true[/code], the exported game will support threads. It requires [url=https://web.dev/articles/coop-coep]a "cross-origin isolated" website[/url], which may be difficult to set up and is limited for security reasons (such as not being able to communicate with third-party websites).
 			If [code]false[/code], the exported game will not support threads. As a result, it is more prone to performance and audio issues, but will only require to be run on an HTTPS website.
 		</member>
+		<member name="variant/emscripten_pool_size" type="int" setter="" getter="">
+			TODO
```
Comment (clayjohn) [inline platform/web/doc_classes/EditorExportPlatformWeb.xml:90]: Something like "Number of threads that emscripten will allocate at startup. A smaller value will allocate fewer threads and consume fewer system resources, but you may run the risk of running out of threads in the pool and needing to allocate more threads at run time which may cause a deadlock. [b]Note:[/b] some browsers have a hard cap on the number of threads that can be allocated, so it is best to be cautious and keep this number low."

CC @Faless

**Review by clayjohn — COMMENTED** [review]
For the docs, you will need to run Godot from the engine root with the `--doctool` argument. It will automatically generate the correct docs bindings in the correct place so you don't trigger the CI error. See: https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html#updating-class-reference-when-working-on-the-engine

I have made some rough suggestions, but this is outside my area of expertise, so the content may not be exactly accurate

File: platform/web/doc_classes/EditorExportPlatformWeb.xml (hunk 6 above)
Comment (Faless) [reply platform/web/doc_classes/EditorExportPlatformWeb.xml:90]: This sounds great

File: platform/web/doc_classes/EditorExportPlatformWeb.xml (hunk 5 above)
Comment (Faless) [reply platform/web/doc_classes/EditorExportPlatformWeb.xml:93]: This sounds good, the only it's not clear is what you mean by:
```
This setting is used when the WorkerThreadPool size is set to -1 (which it is by default).
```
Is that a setting? Or a method? We should probably reference it in case.

**Comment by marcosc90** [comment]
Thanks @clayjohn

image

image

File: platform/web/doc_classes/EditorExportPlatformWeb.xml [hunk 7]
```diff
@@ -79,9 +79,17 @@
...
 		</member>
+		<member name="variant/emscripten_pool_size" type="int" setter="" getter="">
+			Number of threads that emscripten will allocate at startup. A smaller value will allocate fewer threads and consume fewer system resources, but you may run the risk of running out of threads in the pool and needing to allocate more threads at run time which may cause a deadlock.
+			[b]Note:[/b] some browsers have a hard cap on the number of threads that can be allocated, so it is best to be cautious and keep this number low.
+		</member>
 		<member name="variant/extensions_support" type="bool" setter="" getter="">
 			If [code]true[/code] enables [GDExtension] support for this web build.
 		</member>
+		<member name="variant/godot_pool_size" type="int" setter="" getter="">
+			Override for the default size of the [WorkerThreadPool]. This setting is used when the [WorkerThreadPool] size is set to -1 (which it is by default). This size must be smaller than [member variant/emscripten_pool_size] otherwise deadlocks may occur.
```
Comment (clayjohn) [inline platform/web/doc_classes/EditorExportPlatformWeb.xml:90]:
```suggestion
			Override for the default size of the [WorkerThreadPool]. This setting is used when [member ProjectSettings.threading/worker_pool/max_threads] size is set to -1 (which it is by default). This size must be smaller than [member variant/emscripten_pool_size] otherwise deadlocks may occur.
```

Just to address @Faless' comment https://github.com/godotengine/godot/pull/104458#discussion_r2090746344

**Review by clayjohn — APPROVED** [review]
Looks good to me now. CC @Faless For final confirmation

**Review by Faless — APPROVED** [review]
LGTM!

File: platform/web/doc_classes/EditorExportPlatformWeb.xml [hunk 8]
```diff
@@ -79,9 +79,17 @@
 			- [b]Landscape:[/b] Forces a horizontal layout (wider than it is taller).
 			- [b]Portrait:[/b] Forces a vertical layout (taller than it is wider).
 		</member>
+		<member name="variant/emscripten_pool_size" type="int" setter="" getter="">
+			Number of threads that emscripten will allocate at startup. A smaller value will allocate fewer threads and consume fewer system resources, but you may run the risk of running out of threads in the pool and needing to allocate more threads at run time which may cause a deadlock.
```
Comment (AThousandShips) [inline platform/web/doc_classes/EditorExportPlatformWeb.xml:83]:
```suggestion
			The number of threads that emscripten will allocate at startup. A smaller value will allocate fewer threads and consume fewer system resources, but you may run the risk of running out of threads in the pool and needing to allocate more threads at run time which may cause a deadlock.
```

File: platform/web/doc_classes/EditorExportPlatformWeb.xml [hunk 9]
```diff
@@ -79,9 +79,17 @@
...
+			[b]Note:[/b] some browsers have a hard cap on the number of threads that can be allocated, so it is best to be cautious and keep this number low.
```
Comment (AThousandShips) [inline platform/web/doc_classes/EditorExportPlatformWeb.xml:84]:
```suggestion
			[b]Note:[/b] Some browsers have a hard cap on the number of threads that can be allocated, so it is best to be cautious and keep this number low.
```

File: platform/web/doc_classes/EditorExportPlatformWeb.xml (hunk 8 above)
Comment (marcosc90) [reply platform/web/doc_classes/EditorExportPlatformWeb.xml]: Changed!

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! Amazing work :1st_place_medal:

**Comment by adamscott** [comment]
FYI @marcosc90, [I suggested in the \#web channel of the Godot Developers Chat](https://chat.godotengine.org/channel/web?msg=xdGYZxuBLMPqPi9hw) that we revert this PR for the time being, at least for 4.5. Unfortunately, it seems that the current implementation makes the default Web editor build fail to actually run, because of a deadlock (see #108484).

It seems that by some miracle, the fact that the Godot thread pool was only running on a single thread, it made so that every thread spawned by the editor could in fact be spawned without creating a deadlock. By setting Godot thread pool count to 4 by default, well the deadlock happens.

I worry that games could suffer the same way, and there's not really another way than cranking up the number of Emscripten thread pool count, or setting the number to 1.

The other reason is that there's no way currently to determine these numbers like case by case. It could be nice to be able to set the Godot thread pool count to 1 or very low if `navigation.hardwareConcurrency` is very low, and high vice versa. And the ability to set a number of emscripten threads relative to the hardware concurrency reported by the browser.

> Most browsers have a hard cap on threads, historically, that cap has been quite low.
> When hardware concurrency is capped the value of `navigator.hardwareConcurrency` [may be the cap](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency#value) (**may**, i.e. `hardwareConcurrency` may in fact be more than the cap).
> This means we can't trust too much the value of `navigator.hardwareConcurrency`.

@Faless I did a little experiment, and from what I gathered so far, it doesn't seem that there's an hard cap (anymore?). We can spawn a number of threads times higher than `navigator.hardwareConcurrency`. So having a emscripten thread pool high count (just as a precaution) could be interesting. Here's my experiment: https://codepen.io/adamscott/pen/wBKavjN
