### PR TITLE
Fix crash in editor when setting `SubViewport.size` to zero

### LINKED ISSUE #70481: Editor crashes when SubViewport size is set to zero by sliding the values
### Godot version

v4.0.beta9.official [e780dc332]

### System information

macOS Ventura 13.0.1 (Intel), Radeon Pro 580 8 GB

### Issue description

When setting the size of a SubViewport (that is inside the corresponding SubViewportContainer) to zero, the editor crashes instantly.

**But it only happens when I set the size of the SubViewport by sliding the values.**

You can see what happens in this video:

https://user-images.githubusercontent.com/91340577/209363880-503d3dff-80e1-4e9e-bb57-d059fdbfeed0.mp4

At the end of the video you can see the crash message of macOS reading: _Godot quit unexpectedly._

If I write the number zero (or any negative) to the values of the SubViewport size, the crash doesn't happens.

### Steps to reproduce

1. Add a SubViewportContainer
2. Add a SubViewport as a child of the SubViewportContainer
3. Set the size of the SubViewport to zero **by sliding** the X or the Y value.

### Minimal reproduction project

1. Open the project
2. Go to the Control.tscn scene
3. Select the SubViewport node
4. Slide the X or Y values of the size to zero

[SubViewportCrash.zip](https://github.com/godotengine/godot/files/10296101/SubViewportCrash.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
`Viewport::_set_size` now verifies, that the minimum size is at least 2x2.
Also fix `RendererViewport::viewport_set_size` fail condition.

resolve #70481

### CODE REVIEW

**Comment by akien-mga** [comment]
> Extend `EditorPropertyVector2i::setup` with `p_allow_greater` and `p_allow_lesser`, keeping the previous behavior for default values.

That's a pretty specific solution, which makes the implementation inconsistent with other vector property editors.

Adding range support for vectors is maybe a good idea but this should be done consistently and probably independently of this PR.

For this one, can't we just force the size to be `>= 1` in the setter? What happens if the size is set from code to 0, which doesn't respect the editor hint?

**Comment by Sauermann** [comment]
Thanks for the comment. Adding range support for vectors would probably something to consider after 4.0, since it is more of a nice to have thing.

Initially my impression was that the linked issue is an editor problem, so I tried to solve it in this domain, but after digging deeper, it became a Viewport-Rendering problem.

File: servers/rendering/renderer_viewport.cpp [hunk 1]
```diff
@@ -844,7 +844,7 @@ void RendererViewport::viewport_set_scaling_3d_scale(RID p_viewport, float p_sca
 }
 
 void RendererViewport::viewport_set_size(RID p_viewport, int p_width, int p_height) {
-	ERR_FAIL_COND(p_width < 0 && p_height < 0);
+	ERR_FAIL_COND(p_width < 0 || p_height < 0);
```
Comment (akien-mga) [inline servers/rendering/renderer_viewport.cpp:847]: Shouldn't it be `< 2` to match the Viewport code?

**Review by akien-mga — APPROVED** [review]

File: servers/rendering/renderer_viewport.cpp (hunk 1 above)
Comment (Sauermann) [reply servers/rendering/renderer_viewport.cpp:847]: I tried that but noticed that some places in the code base use 0 as size. This resulted in multiple editor-error messages. The current variant simply fixes the wrong `&&`. These other places should probably be investigated separately, but that would be quite far away from the linked issue.
