### PR TITLE
Fix creating Nodes by DoubleClick from Recent list

### LINKED ISSUE #51632: [4.0] Creating a Node from "Recent" list in "Create New Node" dialogue creates Node2D instead of Node
### Godot version

v4.0.dev.custom_build [3a48474c4]

### System information

Windows 10, 1080 Ti

### Issue description

Creating a Node from "Recent" list with "Create New Node" dialogue returns Node2D instead of Node: 

https://user-images.githubusercontent.com/2698825/129388525-8d8a6e90-0b89-40e1-b7e8-af38644d05b1.mp4

### Steps to reproduce

1. Open "Create New Node" dialogue (Ctrl + A)
2. Select "Node" in Recent list

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Sauermann**
resolve #51632
related to #51808 and #59498
supersedes #66198

This bug stems from two problems.

1. `CreateDialog::_score_type` never scores the search string against `Node`, because `Node` is not in the list, that is used to make the comparison. This patch adds `Node` to the comparison list.

2. `CreateDialog::_score_type` gives a higher score to some preferred types, which interferes with search results. This patch gives search matching a higher weight than preferred types.

### CODE REVIEW

**Comment by akien-mga** [comment]
See also #51808 which aims at fixing the same issue (+ more), though with a different approach. (CC @hinlopen)

**Comment by Sauermann** [comment]
As far as I can tell this PR is compatible with #51808 in the sense that the other one will overwrite all changes. So this PR can be seen as a quick fix until there the other PR replaces the current system.

**Review by nathanfranke — APPROVED** [review]
I didn't test but the change looks good, well done.

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -351,13 +347,13 @@ float CreateDialog::_score_type(const String &p_type, const String &p_search) co
 	float score = (pos > -1) ? 1.0f - w * MIN(1, 3 * pos * inverse_length) : MAX(0.f, .9f - w);
```
Comment (nathanfranke) [inline editor/create_dialog.cpp:348]: Consider adding this to the top of `_score_type`, just in case there is an edge case where the bug described in #66198 is still reproducible. (Don't use GitHub to apply this change, it is on the wrong line.)

Am I correct in assuming it is impossible for a search to otherwise have a perfect `1.0f` score?

```suggestion
	if (p_type == p_search) {
		// Always favor an exact match (case-sensitive), since clicking a favorite will set the search text to the type.
		return 1.0f;
	}

```

Comment (Sauermann) [reply editor/create_dialog.cpp:348]: Sound like a good compromise between our two PRs - this addition makes the functionality very clear.
And yes, score is always supposed to be <= 1, as far as I can tell.

File: editor/create_dialog.cpp [hunk 2]
```diff
@@ -351,13 +347,13 @@ float CreateDialog::_score_type(const String &p_type, const String &p_search) co
...
 
 	// Favor shorter items: they resemble the search term more.
-	w = 0.1f;
+	w = 0.9f;
 	score *= (1 - w) + w * (p_search.length() * inverse_length);
```
Comment (Sauermann) [inline editor/create_dialog.cpp:351]: I need to restrict the product to be at most 1.

**Comment by Sauermann** [comment]
@nathanfranke it looks like your PR-approval got removed after my update. May I ask you to have another look at the changes?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by nathanfranke** [comment]
I'm not a maintainer, so my reviews are never blocking. Thanks for merging, though, akien!
