### PR TITLE
Fix spinbox decimal issues when `update_on_text_changed` = true

### LINKED ISSUE #100620: SpinBox `update_on_text_changed = true` regression: Can't input decimals.
### Tested versions

- Reproducible in: v4.3.stable, v4.4.dev6 [1f47e4c4e]
- Not reproducible in: v4.2.stable

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 32.0.15.6603) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

Setting `Update on Text Changed` to true prevents decimals from being input. It seems to be similar to what happened with #81989. You can copy and paste decimal numbers into the SpinBox just fine, but trying to type a decimal will do nothing. Changing `step` to a decimal value < 1 still doesn't allow a decimal to be typed. This is true for both GDscript and C# in 4.3 & 4.4-dev6, but not in 4.2 (as #81989 fixed it in that version)

### Steps to reproduce

1. Create a new scene
2. Add a SpinBox node
3. Set `Update on Text Changed` to true
4. Run the current scene
5. Type decimal (.) into the SpinBox

Image

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/100620

When using `update_on_text_changed`:

If `.` is entered as the first character, automatically change to `0.`
Text ending in `.` does not get submitted, unless "accepted". 
Round numbers do not automatically have a decimal appended to it, unless "accepted". 

https://github.com/user-attachments/assets/5328a735-9cd1-41ec-8ab4-52699fd8f1c6

### CODE REVIEW

File: scene/gui/spin_box.cpp [hunk 1]
```diff
@@ -288,12 +302,18 @@ void SpinBox::_line_edit_editing_toggled(bool p_toggled_on) {
...
+		accepted = true;
+
 		// Discontinue because the focus_exit was caused by canceling or the text is empty.
 		if (Input::get_singleton()->is_action_pressed("ui_cancel") || line_edit->get_text().is_empty()) {
 			_update_text();
 			return;
 		}
 
+		if (line_edit->get_text().ends_with(".")) {
+			line_edit->set_text(line_edit->get_text().trim_suffix("."));
```
Comment (ryevdokimov) [inline scene/gui/spin_box.cpp:314]: Text input ending in a decimal and submitted that way will assume just the whole number, even if update_on_text_changed is false.

File: scene/gui/spin_box.cpp [hunk 2]
```diff
@@ -68,7 +72,13 @@ void SpinBox::_update_text(bool p_keep_line_edit) {
 }
 
 void SpinBox::_text_submitted(const String &p_string) {
-	if (p_string.is_empty()) {
+	if (p_string.is_empty() || (update_on_text_changed && !p_string.begins_with(".") && p_string.ends_with("."))) {
+		return;
+	}
+
+	if (update_on_text_changed && p_string.begins_with(".")) {
+		line_edit->set_text("0.");
```
Comment (ryevdokimov) [inline scene/gui/spin_box.cpp:80]: Adding the `0.` automatically when `.` is the first character can be done with `update_on_text_changed` is false, if desired.

**Comment by KoBeWi** [comment]
`,` is also supported in SpinBox, so you should probably account for that too.

File: scene/gui/spin_box.cpp [hunk 3]
```diff
@@ -63,20 +63,39 @@ void SpinBox::_update_text(bool p_only_update_if_value_changed) {
...
+	if (!accepted && update_on_text_changed && !text.contains(".")) {
+		value = String::num(get_value(), 0);
+	}
+
 	line_edit->set_text_with_selection(value);
 }
 
 void SpinBox::_text_submitted(const String &p_string) {
-	if (p_string.is_empty()) {
-		_update_text();
```
Comment (ryevdokimov) [inline scene/gui/spin_box.cpp:71]: This line was added in https://github.com/godotengine/godot/pull/100860 and reintroduces: https://github.com/godotengine/godot/issues/99281

I'm not sure why it's necessary, since empty text is not a valid submission and there is other code that handles reverting from empty. 

@larspet, if you want to pitch in.

**Comment by ryevdokimov** [comment]
>, is also supported in SpinBox, so you should probably account for that too.

Done.

File: scene/gui/spin_box.cpp (hunk 3 above)
Comment (larspet) [reply scene/gui/spin_box.cpp:71]: It was meant to revert the text, which indeed does seem to work without that line. What might've happened is that the reverting stopped working while my PR was WIP, so I added that line to fix it. Then when my PR was functional I didn't try to remove it.

Comment (ryevdokimov) [reply scene/gui/spin_box.cpp:71]: Sounds good, thanks.

**Comment by KoBeWi** [comment]
When the number ends with period and you press Enter, the period will disappear resulting in wrong text. Pressing Enter again will update it correctly.

https://github.com/user-attachments/assets/e05a8259-001c-4ef8-9908-fd7c880b6e6c

**Comment by ryevdokimov** [comment]
> When the number ends with period and you press Enter, the period will disappear resulting in wrong text. Pressing Enter again will update it correctly.

Fixed.

**Comment by KoBeWi** [comment]
The initial value is missing trailing 0 for some reason.
image
Expected:
image

**Comment by ryevdokimov** [comment]
>The initial value is missing trailing 0 for some reason.

Fixed.

File: scene/gui/spin_box.cpp [hunk 4]
```diff
@@ -63,20 +63,33 @@ void SpinBox::_update_text(bool p_only_update_if_value_changed) {
 			value += " " + suffix;
 		}
 	}
+
+	String text = line_edit->get_text().replace(",", ".");
+
+	if (!accepted && update_on_text_changed && !text.contains(".")) {
```
Comment (KoBeWi) [inline scene/gui/spin_box.cpp:69]: It would be better if `text` was inside the condition. It's irrelevant unless `!accepted && update_on_text_changed` are true.

File: scene/gui/spin_box.cpp [hunk 5]
```diff
@@ -63,20 +63,33 @@ void SpinBox::_update_text(bool p_only_update_if_value_changed) {
...
 	line_edit->set_text_with_selection(value);
 }
 
 void SpinBox::_text_submitted(const String &p_string) {
-	if (p_string.is_empty()) {
-		_update_text();
+	// Convert commas ',' to dots '.' for French/German etc. keyboard layouts.
+	String text = p_string.replace(",", ".");
+
+	if (p_string.is_empty() || (update_on_text_changed && !text.begins_with(".") && text.ends_with("."))) {
```
Comment (KoBeWi) [inline scene/gui/spin_box.cpp:80]: Same here. You can run empty check first.

File: scene/gui/spin_box.cpp [hunk 6]
```diff
@@ -288,9 +307,16 @@ void SpinBox::_line_edit_editing_toggled(bool p_toggled_on) {
...
+		accepted = true;
+
 		if (Input::get_singleton()->is_action_pressed("ui_cancel") || line_edit->get_text().is_empty()) {
 			_update_text(); // Revert text if editing was canceled.
 		} else {
+			if (line_edit->get_text().ends_with(".")) {
+				line_edit->set_text(line_edit->get_text().trim_suffix("."));
+			} else if (line_edit->get_text().ends_with(",")) {
+				line_edit->set_text(line_edit->get_text().trim_suffix(","));
+			}
```
Comment (KoBeWi) [inline scene/gui/spin_box.cpp:319]:
```suggestion
			line_edit->set_text(line_edit->get_text().trim_suffix(".").trim_suffix(","));
```

**Review by KoBeWi — APPROVED** [review]
Works correctly now.

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
