### PR TITLE
[Core] Improve `CowData` and `Memory` metadata alignment.

### LINKED ISSUE #87442: Double precision build fails for linuxbsd x86_32 arch
### Tested versions

4.x at 0bcc0e92b3f0ac57d4c4650722f347593a258572
(to be more prices - my 4.x fork at https://github.com/roalyr/godot-for-3d-open-worlds/commit/647e40d9b7f1461ad1ac12dac1f2db23629b538e)

### System information

Linux mx-x230 5.10.0-27-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux

### Issue description

Compilation fails with this error only for x86_32 (other compile as intended):

```
In file included from ./core/os/memory.h:35,
                 from ./core/templates/local_vector.h:35,
                 from ./core/object/message_queue.h:36,
                 from ./core/object/object.h:35,
                 from ./core/variant/binder_common.h:35,
                 from ./core/object/method_bind.h:34,
                 from ./core/object/class_db.h:34,
                 from ./core/config/project_settings.h:34,
                 from platform/linuxbsd/crash_handler_linuxbsd.cpp:33:
./core/templates/safe_refcount.h:56:45: error: static assertion failed
   56 |  static_assert(alignof(SafeNumeric<m_type>) == alignof(m_type)); \
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
./core/templates/cowdata.h:49:1: note: in expansion of macro 'SAFE_NUMERIC_TYPE_PUN_GUARANTEES'
   49 | SAFE_NUMERIC_TYPE_PUN_GUARANTEES(uint64_t)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./core/os/memory.h:35,
                 from ./core/templates/local_vector.h:35,
                 from ./core/object/message_queue.h:36,
                 from ./core/object/object.h:35,
                 from ./core/variant/binder_common.h:35,
                 from ./core/object/method_bind.h:34,
                 from ./core/object/class_db.h:34,
                 from ./core/object/ref_counted.h:34,
                 from ./core/io/resource_uid.h:34,
                 from ./core/io/resource.h:34,
                 from ./core/input/input_event.h:35,
                 from ./core/input/input.h:34,
                 from platform/linuxbsd/joypad_linux.h:36,
                 from platform/linuxbsd/os_linuxbsd.h:35,
                 from platform/linuxbsd/godot_linuxbsd.cpp:31:
./core/templates/safe_refcount.h:56:45: error: static assertion failed
   56 |  static_assert(alignof(SafeNumeric<m_type>) == alignof(m_type)); \
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
./core/templates/cowdata.h:49:1: note: in expansion of macro 'SAFE_NUMERIC_TYPE_PUN_GUARANTEES'
   49 | SAFE_NUMERIC_TYPE_PUN_GUARANTEES(uint64_t)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [platform/linuxbsd/crash_handler_linuxbsd.linuxbsd.editor.double.x86_32.o] Error 1
scons: *** [platform/linuxbsd/godot_linuxbsd.linuxbsd.editor.double.x86_32.o] Error 1
scons: building terminated because of errors.
```

### Steps to reproduce

Compile source with these arguments:
```
scons -j2 platform=linuxbsd precision=double arch=x86_32
scons -j2 platform=linuxbsd precision=double target=template_debug arch=x86_32
```

### Minimal reproduction project (MRP)

Not a project-related issue.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/87442

This should not change real memory structure on any platform. But instead of hard-coded values, it is using actual sizes and alignments to allocate and access metadata.

### CODE REVIEW

**Comment by bruvzg** [comment]
Tested on:
- building and running on x86_32 Linux (fresh openSUSE VM).
- building and running on x86_64 (both 32-bit and 64-bit versions, and both MinGW and MSVC).
- building for x86_32 Android.
- building and running on ARM64 macOS.

On 32-bit Linux, I'm getting a few failed `FastNoiseLite` tests, but it seems to be an unrelated floating point precision issue (`0.8 != 0.7961`) otherwise it seems to be working fine.

Another unrelated note: 32-bit MinGW GCC crash when building with debug symbols on Windows (cross-building is fine), probably symbols are not too big (might be worth adding a note to the compiling page).

File: core/templates/cowdata.h [hunk 1]
```diff
@@ -260,26 +269,27 @@ typename CowData<T>::USize CowData<T>::_copy_on_write() {
...
-		USize *mem_new = (USize *)Memory::alloc_static(_get_alloc_size(current_size) + ALLOC_PAD, false);
-		mem_new += 2;
+		uint8_t *mem_new = (uint8_t *)Memory::alloc_static(_get_alloc_size(current_size) + _data_offset, false);
+		ERR_FAIL_NULL_V(mem_new, 0);
 
-		new (mem_new - 2) SafeNumeric<USize>(1); //refcount
-		*(mem_new - 1) = current_size; //size
+		SafeNumeric<USize> *_refc_ptr = (SafeNumeric<USize> *)(mem_new + _refc_offset);
+		USize *_size_ptr = (USize *)(mem_new + _size_offset);
+		T *_data_ptr = (T *)(mem_new + _data_offset);
```
Comment (AThousandShips) [inline core/templates/cowdata.h:277]: I'd suggest helper methods for these three calculations, just to avoid confusion and errors, as they're used a few times over

File: core/os/memory.h [hunk 2]
```diff
@@ -142,10 +142,12 @@ T *memnew_arr_template(size_t p_elements) {
 	same strategy used by std::vector, and the Vector class, so it should be safe.*/
 
 	size_t len = sizeof(T) * p_elements;
-	uint64_t *mem = (uint64_t *)Memory::alloc_static(len, true);
+	uint8_t *mem = (uint8_t *)Memory::alloc_static(len, true);
 	T *failptr = nullptr; //get rid of a warning
 	ERR_FAIL_NULL_V(mem, failptr);
-	*(mem - 1) = p_elements;
+
+	uint64_t *_size_ptr = (uint64_t *)(mem - Memory::_data_offset + Memory::_elem_offset);
```
Comment (AThousandShips) [inline core/os/memory.h:149]: Same here, maybe a `calculate_base`

**Review by AThousandShips — APPROVED** [review]
The changes here make a lot of sense to me

File: core/templates/cowdata.h (hunk 1 above)
Comment (bruvzg) [reply core/templates/cowdata.h]: Added helpers.

File: core/os/memory.cpp [hunk 3]
```diff
@@ -65,30 +65,37 @@ SafeNumeric<uint64_t> Memory::max_usage;
 
 SafeNumeric<uint64_t> Memory::alloc_count;
 
+// Alignment:  ↓ max_align_t        ↓ uint64_t          ↓ max_align_t
+//             ┌─────────────────┬──┬────────────────┬──┬───────────...
+//             │ uint64_t        │░░│ uint64_t       │░░│ T[]
+//             │ alloc size      │░░│ element count  │░░│ data
+//             └─────────────────┴──┴────────────────┴──┴───────────...
+// Offset:     ↑ _size_offset       ↑ _elem_offset      ↑ _data_offset
+
```
Comment (RandomShaper) [inline core/os/memory.cpp:74]: Good idea!

File: core/templates/cowdata.h [hunk 4]
```diff
@@ -46,7 +46,7 @@ class CharString;
 template <class T, class V>
 class VMap;
 
-SAFE_NUMERIC_TYPE_PUN_GUARANTEES(uint64_t)
+static_assert(std::is_trivially_destructible<std::atomic<uint64_t>>::value);
```
Comment (RandomShaper) [inline core/templates/cowdata.h:49]: If this because of the `SafeNumeric<uint64_t>` around, I'd suggest including this in the set of type-pun guarantees macro in `safe_refcount.h`.

Comment (bruvzg) [reply core/templates/cowdata.h:49]: It is part of `SAFE_NUMERIC_TYPE_PUN_GUARANTEES`:

```
#define SAFE_NUMERIC_TYPE_PUN_GUARANTEES(m_type)                    \
	static_assert(sizeof(SafeNumeric<m_type>) == sizeof(m_type));   \
	static_assert(alignof(SafeNumeric<m_type>) == alignof(m_type)); \
	static_assert(std::is_trivially_destructible<std::atomic<m_type>>::value);
```

We take case or sizes and alignment manually (since `alignof` part is not true on 32-bit platforms), and I have copy-pasted the remaining check here (but I'm not sure if there's any point for checking it for `uint64_t` at all).

**Comment by akien-mga** [comment]
Needs rebase after #87871.

File: core/templates/cowdata.h (hunk 4 above)
Comment (RandomShaper) [reply core/templates/cowdata.h]: Ah, makes sense.

**Review by RandomShaper — APPROVED** [review]

File: core/os/memory.h [hunk 5]
```diff
@@ -51,6 +47,10 @@ class Memory {
 	static SafeNumeric<uint64_t> alloc_count;
 
 public:
+	static constexpr size_t SIZE_OFFSET = 0;
```
Comment (AThousandShips) [inline core/os/memory.h:50]: Might want to add the explanation of the offsets here (like they are in CowData), maybe even instead of in the cpp file where they are defined, as the maths here is a bit dense without an explanation

**Review by AThousandShips — APPROVED** [review]
Re-confirming

File: core/os/memory.h (hunk 5 above)
Comment (bruvzg) [reply core/os/memory.h:57]: Moved comment to the header.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Would be good to get a Godot-cpp equivalent fix too

**Comment by bruvzg** [comment]
> Would be good to get a Godot-cpp equivalent fix too

Will do it soon.
