### PR TITLE
Transform mesh's AABB to skeleton's space when calculating mesh's bounds

### LINKED ISSUE #74132: Rearranging bones in the skeleton2d causes polygon2d to disappear
### Godot version

4 rc6

### System information

win 11

### Issue description

I made neck a check of torso instead of cervix and all the sprites for the neck and its children (head, etc) disappeared. I dunno how to get them back.

### Steps to reproduce

Make a polygon
make a skeleton with bones
assign the skeleton to the polygon and paint the weights
move the bones

### Minimal reproduction project

n/a

edit: okay i got them back by repainting the weights but now the uv thingy is off

image

### LINKED ISSUE #74656: Mismatch between AABB and mesh when mesh and skeleton don't have the same transform
### Godot version

Master (9b9bb418cb1137e69b5131ec9fa7b41c0396db28)

### System information

Irrelevant

### Issue description

Somewhat of a sequel to #71953. Sorry in advance for doing this report half-energy. I'm not sure if it counts as a bug, or is simply "You're not supposed to do that", i.e. undefined behavior.

Basically, if a mesh and a skeleton have mismatching transforms, in rendering, the mesh seems to attach to the skeleton based on the global position. For instance, if a skeleton's bone has rotation, and the mesh is moved in the direction that the bone's rest pose points at, the skeleton-transformed mesh would move in the direction that the bone's current pose points at. Basically, as if each of the mesh's vertices was moved.

Meanwhile, the AABB calculation seems to assume that the mesh and skeleton have the same transformation. That is, it attaches to the skeleton based on the positions of the vertices within the mesh, and not based on the global positions.

I've confirmed this in 2D, but it's likely present in 3D as well, since they use common code. At least for AABB.

### Steps to reproduce

1. Have a mesh (MeshInstance2D, MeshInstance3D, Polygon2D) with a skeleton (Skeleton2D, Skeleton3D) attached.
2. Move the skeleton to a non-rest pose
3. Move the the mesh's origin to being away from the skeleton.
4. Do some action that relies on AABB. e.g occlusion culling, canvas group, etc.

### Minimal reproduction project

Left as an exercise to the reader. I'm not even sure if this is unintended behavior, since skeleton and mesh with different transforms doesn't sound like something a user is normally supposed to do.

For the 2D case, it's possible to just take the project from #71953 and use the move tool to move the polygon.

### LINKED ISSUE #81983: Polygon2D/Skeleton2D rendering bug when the polygon's rest pose is outside the viewport
### Godot version

4.1.1.stable

### System information

Windows 10

### Issue description

Using Skeleton2D and Bone2D to animate Polygon2D can lead to the Polygon2D no longer being shown, probably being culled, when it is actually still supposed to be on the screen.

Minimum project, everything is shown:
image

Zooming in a little makes the lower leg and foot getting culled
image

Rotating the hips Bone node also makes all the leg nodes getting culled.
image

This was also an issue in Godot 3 that then luckily got fixed: https://github.com/godotengine/godot/issues/35726

It has the same behavior so a similar solution might solve the problem in 4 as well?

### Steps to reproduce

Add some Polygon2D nodes, attach a texture to them and use UV points to put it on screen. Add a Skeleton2D with some bone2Ds. Connect the UV of the Polygon2D to the bones 
image
This has been set up in minima project.

Now move the bones around a bit, move the root node around on the screen so it gets to the edge. You will see the Polygon2D's getting culled before they are off the screen. 

### Minimal reproduction project

[MinimumCulling.zip](https://github.com/godotengine/godot/files/12674037/MinimumCulling.zip)

### PR DESCRIPTION
**Pull request by ShirenY**
Fixes #74656 fixes #81983 fixes #74132, and there maybe more duplicated reports I havent found, since this bug is quite common.

This PR is following @clayjohn 's pr #76184. Thanks to guys working in this threads, they have actually identified the cause of this issue:
It's because when resolving animated meshes AABBs with skeleton. The AABBs is actually in mesh instance's space. But skeleton animation assumes differently: all the meshes are in skeleton's space.
That's why the PR tried to solve it by introduce the mesh item's xform to mesh_get_aabb. But we quickly found item's xform is not enough. As it's a local transform, it means it will still has the bug when the Polygon2d in a different hierarchy with the skeleton.

So I come up with a solution: 
Introduce a new transform stored in Mesh::Surface, which contains the transform differences between the Polygon2d and its skeleton. This transform is generated when polygon recreating the mesh. So that in run time, it can be used to transform the bones' AABBs back and forth.

I believe in 3d we have same issue, since the code is shared same logic. And I didn't address 3d part, because I believe this bug in 3d is quite rare, since people tends to have same root space for skinned meshes and skeletons in 3d. So I guess we can leave it for further PRs.

Plz NOTE that this PR is NOT tring to fix every edge cases, like if you move around polygon2d or skeleton's position in runtime, the AABBs will be incorrect until regenerating. And if people move around Polygon2ds in the editor when bones are not in their rest pos, there will be issues not just rect culling but also mesh rendering. I believe these cases are not really intentional usage. Since move mesh's transform after skinning in 3d is really weird practice.

This is my first PR to godot, so let me know if I messed up anything:)

### CODE REVIEW

**Comment by fire** [comment]
There's a notification for "move mesh's transform" on Node3D. NOTIFICATION_TRANSFORM_CHANGED NOTIFICATION_LOCAL_TRANSFORM_CHANGED

**Review by fire — COMMENTED** [review]
I have some comments on a paper review. Godot uses snake_case for variable names. It looks ok.

Now to run the Godot Engine pull request in a compile.

Tempted to run 500 avatars moving to see what happens -- with the aabb calculations performance wise.

File: drivers/gles3/storage/mesh_storage.cpp [hunk 1]
```diff
@@ -561,15 +563,16 @@ AABB MeshStorage::mesh_get_aabb(RID p_mesh, RID p_skeleton) {
...
+		if ((surface.format & RS::ARRAY_FORMAT_BONES) && surface.bone_aabbs.size()) {
+			int bs = surface.bone_aabbs.size();
+			const AABB *skbones = surface.bone_aabbs.ptr();
 
 			int sbs = skeleton->size;
 			ERR_CONTINUE(bs > sbs);
 			const float *baseptr = skeleton->data.ptr();
 
-			bool first = true;
+			bool foundBoundAABB = false;
```
Comment (fire) [inline drivers/gles3/storage/mesh_storage.cpp:575]:
```suggestion
			bool found_bound_aabb = false;
```

**Comment by ShirenY** [comment]
> There's a notification for "move mesh's transform" on Node3D. NOTIFICATION_TRANSFORM_CHANGED NOTIFICATION_LOCAL_TRANSFORM_CHANGED you can consider if it's a rare operation.

Pushed a new version to address this. I was intend to only do it in the editor, since I assumes the relative transform between mesh and skeleton won't change in runtime.

**Comment by ShirenY** [comment]
Also hope @clayjohn @SlugFiller @lawnjelly can check this out, as this PR follows their previous work.

**Comment by ShirenY** [comment]
Added Engine::get_singleton()->is_editor_hint() to make sure only recreat mesh for transform change event in Editor.

**Comment by ShirenY** [comment]
Oops, looks like swich-case fall through triggered some warnning in linux. Changed the way how it does the editor check.

**Comment by ShirenY** [comment]
As @fire suggested, I made a performance test project based on @Zoomulator's project at #74656 
[polygon2dcullbug.zip](https://github.com/godotengine/godot/files/13266917/polygon2dcullbug.zip)
It spawns 900 skeletons with meshes. 
This is what I got from engine at 4.1.3 without the fix. Frame time in range between 90ms - 110ms
Polygon2dOrigProfile

This is the profiler with this fix at 4.1.3. Frame time in range between 120ms - 140ms
Polygon2dCullingFixProfile

Looks like this fix do cause some frame time increase. But to be honest, I'm not sure which part causes this result. Because it costs more when culling working correctly: you got more drawcalls to cover. And godot's profiler looks quite rough to me, I can't see time in details. I'll try to do more test on this.

**Comment by ShirenY** [comment]
So I made second performance test, make a new animation, but everything won't get culled in origin code. So both version will have same amount of meshes draw to the viewport.
As I suspected, the performance shows no measurable differences this time.
This is the orign engine test result,
Polygon2dOrigProfile2

This is the fixed version test result,
Polygon2dCullingFixProfile2

And this is the second test project I used
[polygon2dcullbug.zip](https://github.com/godotengine/godot/files/13267365/polygon2dcullbug.zip)

**Comment by fire** [comment]
@lawnjelly If you have some spare time, can you review this?

File: scene/2d/polygon_2d.cpp [hunk 2]
```diff
@@ -364,7 +368,31 @@ void Polygon2D::_notification(int p_what) {
...
 
-				RS::get_singleton()->mesh_add_surface_from_arrays(mesh, RS::PRIMITIVE_TRIANGLES, arr, Array(), Dictionary(), RS::ARRAY_FLAG_USE_2D_VERTICES);
+				RS::SurfaceData sd;
+
+				if (skeleton_node) {
+					// Compute transform between mesh and skeleton for runtime AABB compute.
+
+					const Transform2D meshTransform = this->get_global_transform();
+					const Transform2D skeletonTransform = skeleton_node->get_global_transform();
+					const Transform2D mesh_to_sk2d = meshTransform * skeletonTransform.inverse();
```
Comment (lawnjelly) [inline scene/2d/polygon_2d.cpp:378]: It may be better to use `affine_inverse()` here (that's what I used in 3.x). `inverse()` just uses the transpose which is cheaper but doesn't work in some situations (I think transpose depends on being orthonormal but I forget).

File: servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp [hunk 3]
```diff
@@ -723,21 +728,29 @@ AABB MeshStorage::mesh_get_aabb(RID p_mesh, RID p_skeleton) {
...
+						found_bone_aabb = true;
 					} else {
 						laabb.merge_with(baabb);
 					}
 				}
 			}
 
+			if (found_bone_aabb) {
+				// Transform skeleton bounds back to mesh's space if any animated AABB applied.
+				laabb = surface.mesh_to_skeleton_xform.inverse().xform(laabb);
```
Comment (lawnjelly) [inline servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:746]: Consider pre-calculating affine inverse. Again `affine_inverse` preferred over inverse, and as it is a little more expensive to calculate, it can just be stored.

**Comment by lawnjelly** [comment]
This looks great!

It turns out to be simpler than #75612 in 3.x, maybe the bone AABBs were unavailable there so it had to jump through some extra hoops.

Re: performance, as the author says if you compare scenes that are culling differently you are not comparing like with like. It should be pretty ok from what I can see, but have mentioned pre-calculating affine inverse which might be a tad quicker / more accurate.

I don't know if @clayjohn might have opinions about storing the relative transform on each surface (even when not used), but maybe it can be reused for 3D skinning (no idea if the same problem exists there in 4.x). 

I haven't fully tested, but my old test project when I was looking at this seems to work ok and the debug bounds are correct.

**Review by lawnjelly — APPROVED** [review]
Approve in principle, see if author wants to make changes for affine inverse.

Also could do with a 4.x maintainer looking over to check they are happy with the housekeeping aspects (I'm not so familiar with rendering in 4.x).

**Comment by ShirenY** [comment]
Thanks @lawnjelly for the carefully review.

About affine inverse(I dont know this before) and storing inverse matrix. I'm totally fine with these two change. I didn't code these just because I want this change as small as possible, and I don't think a inverse matrix calculation can make any differences per instance in performance wise :) I mean, there at least will be dozens matrix operation in cpu when you do a skeleton animation. 
But I totally understand good programmers want every cpu cycle counts, I do that too. So I will definitely take the affine one. 
And for storing inverse matrix, there could be some concern on memory and software engineer aspect. I personally don't want store more data, because it usually means more bugs. But I'm totally open on this, you guys could made better choice on these changes than me who just get to the engine in two weeks.

Talking about performance, there actually is a more intense place than the inverse matrix. Like, is it correct and faster to mutliply the two matrix before apply to the bone AABB? I just haven't been very clear on the math correction with this. Feathuer more, can we just generate these AABBs in skeleton space, to save the matrix-aabb operation? Maybe, but there will be more related parts about these AABBs to be consider. 

And again, this PR is more focused on fixing this common issue than optimization as this is not usually the hotspot, I want to keep it as simple and small as possible.

**Comment by lawnjelly** [comment]
> Talking about performance, there actually is a more intense place than the inverse matrix. Like, is it correct and faster to mutliply the two matrix before apply to the bone AABB?

I didn't mention this, but in #75612 if I remember right I store the bone AABBs already in skeleton space so maybe this removes the need for:
`AABB baabb = surface.mesh_to_skeleton_xform.xform(skbones[j]);`

However, imo this kind of optimization can be left to a later PR. It is more important to get it working, and accurately, then look at performance improvements as required.

The pre-calculation and storage is more for the affine inverse - affine inverse is a bit more involved than regular inverse. And bear in mind my PR was profiled and highly optimized.

I suspect with regular inverse the bounds can be incorrect if there is skew in the basis. So it will be fine in most cases, but better to cover all bases, if it can be done effectively for free.

File: scene/2d/polygon_2d.cpp [hunk 4]
```diff
@@ -101,7 +101,11 @@ void Polygon2D::_skeleton_bone_setup_changed() {
 }
 
 void Polygon2D::_notification(int p_what) {
+	if (p_what == NOTIFICATION_TRANSFORM_CHANGED && !Engine::get_singleton()->is_editor_hint())
+		return; // Mesh recreation for NOTIFICATION_TRANSFORM_CHANGED is only needed in editor.
+
```
Comment (clayjohn) [inline scene/2d/polygon_2d.cpp:106]:
```suggestion
	if (p_what == NOTIFICATION_TRANSFORM_CHANGED && !Engine::get_singleton()->is_editor_hint()) {
		return; // Mesh recreation for NOTIFICATION_TRANSFORM_CHANGED is only needed in editor.
	}

```

This is just a style suggestion. We always use curly braces with if statements

File: scene/2d/polygon_2d.cpp (hunk 2 above)
Comment (clayjohn) [reply scene/2d/polygon_2d.cpp:378]: Ya, transpose is only valid if the matrix is orthonormal. I don't know if this transform is guaranteed to be orthonormal or not. So it's probably safest to use `affine_inverse()`

**Comment by lawnjelly** [comment]
Just as an aside (maybe for followup PR or investigation), I noticed this note in my original PR:

> The old code applied an unused bone AABB (0, 0, -1, -1) to the final result even if it was not used. This probably caused little problems due to other oversights, but is strictly speaking incorrect I think, so I did a check for this.

I don't know whether this technique is still used in master for unused bones. If so, these may cause the overall bound to be overestimated, and these may be worth rejecting. This won't cause visual errors, but could cause considerable lost performance (in cases of unused bones).

**Review by clayjohn — CHANGES_REQUESTED** [review]
This looks mostly good and it aligns with our approach in 3.x, so I trust this is the correct approach. Great work!

To be ready to merge, it just needs the one style change I recommended and to move to ``affine_inverse()`` as recommended by lawnjelly.

Please squash the changes into the original commit so that the PR only has one commit.

**Comment by ShirenY** [comment]
Looks good to me. I'm not free currently, so I will do these changes after a few hours.

File: drivers/gles3/storage/mesh_storage.cpp [hunk 5]
```diff
@@ -589,11 +592,13 @@ AABB MeshStorage::mesh_get_aabb(RID p_mesh, RID p_skeleton) {
 					mtx.basis.rows[1][1] = dataptr[5];
 					mtx.origin.y = dataptr[7];
 
-					AABB baabb = mtx.xform(skbones[j]);
+					// Transform bounds to skeleton's space before applying animation data
```
Comment (AThousandShips) [inline drivers/gles3/storage/mesh_storage.cpp:595]:
```suggestion
					// Transform bounds to skeleton's space before applying animation data.
```

File: drivers/gles3/storage/mesh_storage.cpp [hunk 6]
```diff
@@ -621,21 +626,29 @@ AABB MeshStorage::mesh_get_aabb(RID p_mesh, RID p_skeleton) {
 					mtx.basis.rows[2][2] = dataptr[10];
 					mtx.origin.z = dataptr[11];
 
-					AABB baabb = mtx.xform(skbones[j]);
-					if (first) {
+					// Transform bounds to skeleton's space before applying animation data
```
Comment (AThousandShips) [inline drivers/gles3/storage/mesh_storage.cpp:629]:
```suggestion
					// Transform bounds to skeleton's space before applying animation data.
```

File: servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp [hunk 7]
```diff
@@ -691,11 +694,13 @@ AABB MeshStorage::mesh_get_aabb(RID p_mesh, RID p_skeleton) {
 					mtx.basis.rows[1][1] = dataptr[5];
 					mtx.origin.y = dataptr[7];
 
-					AABB baabb = mtx.xform(skbones[j]);
+					// Transform bounds to skeleton's space before applying animation data
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:697]:
```suggestion
					// Transform bounds to skeleton's space before applying animation data.
```

File: servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp [hunk 8]
```diff
@@ -723,21 +728,29 @@ AABB MeshStorage::mesh_get_aabb(RID p_mesh, RID p_skeleton) {
 					mtx.basis.rows[2][2] = dataptr[10];
 					mtx.origin.z = dataptr[11];
 
-					AABB baabb = mtx.xform(skbones[j]);
-					if (first) {
+					// Transform bounds to skeleton's space before applying animation data
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:731]:
```suggestion
					// Transform bounds to skeleton's space before applying animation data.
```

File: scene/2d/polygon_2d.cpp [hunk 9]
```diff
@@ -364,7 +369,31 @@ void Polygon2D::_notification(int p_what) {
 
 				arr[RS::ARRAY_INDEX] = index_array;
 
-				RS::get_singleton()->mesh_add_surface_from_arrays(mesh, RS::PRIMITIVE_TRIANGLES, arr, Array(), Dictionary(), RS::ARRAY_FLAG_USE_2D_VERTICES);
+				RS::SurfaceData sd;
+
+				if (skeleton_node) {
+					// Compute transform between mesh and skeleton for runtime AABB compute.
+
+					const Transform2D meshTransform = this->get_global_transform();
```
Comment (AThousandShips) [inline scene/2d/polygon_2d.cpp:377]:
```suggestion
					const Transform2D meshTransform = get_global_transform();
```
Unnecessary use of `this`

**Comment by ShirenY** [comment]
Thanks guys. I've changed inverse() to affine_inverse() as @lawnjelly  and @clayjohn said. And all the code standard changes as @clayjohn @AThousandShips mentioned.

**Comment by AThousandShips** [comment]
Note that you can apply suggestions as a batch to make it easier to squash after

**Comment by ShirenY** [comment]
I used the commit changes option above, which generates two separte commits. Will same logs appears on main branch if merged? That does not look good to me XD 
Sorry, I'm new to github PR process.
image

**Comment by AThousandShips** [comment]
You will have to squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by ShirenY** [comment]
Oops, Did I meshup anything? The compare looks so wrong to me

**Comment by AThousandShips** [comment]
You did not, you just updated your branch at the same time

Now when applying the remaining changes you can do so with `git commit --amend` to not create a new commit

**Comment by ShirenY** [comment]
Looks good to me now. Thanks @AThousandShips 
Definitely learned something from this PR XD

**Comment by lawnjelly** [comment]
Looks fine now. :+1:

**Review by clayjohn — APPROVED** [review]
Looks good to me too. Great work! And thanks for your dedication in taking this the extra mile

**Review by AThousandShips — APPROVED** [review]

**Comment by ShirenY** [comment]
Hi devs, by no means to push, but is there anything need to be down for this PR to be merged? 
From my point of view, all the things need to be down in my side have been down. And all stake holders have approved. It's been quite a while, I've seen a lot of PRs later than this one is merged quickly.
@AThousandShips @clayjohn  @lawnjelly  @fire

**Comment by lawnjelly** [comment]
This needs production team to merge, no need to poke reviewers (we generally don't merge).
Delay may have been due to feature freeze.

I'm sure they list the approved PRs during merging sprees, but just in case pinging @akien-mga .

File: scene/2d/polygon_2d.cpp [hunk 10]
```diff
@@ -364,7 +369,31 @@ void Polygon2D::_notification(int p_what) {
...
 				arr[RS::ARRAY_INDEX] = index_array;
 
-				RS::get_singleton()->mesh_add_surface_from_arrays(mesh, RS::PRIMITIVE_TRIANGLES, arr, Array(), Dictionary(), RS::ARRAY_FLAG_USE_2D_VERTICES);
+				RS::SurfaceData sd;
+
+				if (skeleton_node) {
+					// Compute transform between mesh and skeleton for runtime AABB compute.
+
+					const Transform2D meshTransform = get_global_transform();
+					const Transform2D skeletonTransform = skeleton_node->get_global_transform();
```
[the remark this answers is not in the document]
Comment (ShirenY) [reply scene/2d/polygon_2d.cpp]: Of course. Down

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
