### PR TITLE
Fix ColorPicker always emitting color_changed on html submit

### LINKED ISSUE #66312: ColorPickerButton's color_changed is emitted when the color picker dialog is closed without a change
### Godot version

Tested with 3.5, 3.5.1rc2, 4.0b1

### System information

Windows 10, GLES2

### Issue description

A ColorPickerButton node's color_changed is emitted when the color picker dialog is closed without changing the color. Judging from the signal's name this is probably not intended.

https://user-images.githubusercontent.com/35151158/192012782-3f77a968-e301-4ed8-b853-6f9f9cddf3b9.mp4

### Steps to reproduce

1. Create a new ColorPickerButton scene and save it
2. Add a script to the scene
3. Connect the color_changed signal
4. Add a print function to it to see when the function is called
5. Start the game
6. Click the button and close the dialog without changing anything
7. The color_changed signal is emitted even if the color didn't change

### Minimal reproduction project

[color_picker_button_bug.zip](https://github.com/godotengine/godot/files/9635535/color_picker_button_bug.zip)

### PR DESCRIPTION
**Pull request by Mickeon**
Fixes https://github.com/godotengine/godot/issues/66312.

This is because the HTML TextEdit is set to always submit its text when the modal closes, but what wasn't good is that it still emitted the `color_change` signal even if the color was the same as before. In a way, this PR gets two birds with one stone.

Can probably be cherrypicked to 3.x?

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -427,8 +427,13 @@ void ColorPicker::_html_submitted(const String &p_html) {
 		return;
 	}
 
+	Color new_color = Color::html(p_html);
+	if (color == new_color) {
+		return;
+	}
+	color = new_color;
+
 	float last_alpha = color.a;
```
Comment (akien-mga) [inline scene/gui/color_picker.cpp:436]: You broke this logic.

Comment (Mickeon) [reply scene/gui/color_picker.cpp:436]: I do not understand, I checked again, it seems to work fine. Is it the alpha value?

Comment (akien-mga) [reply scene/gui/color_picker.cpp:436]: Well to me the code is relatively self explanatory:
- `last_alpha` saves the previous alpha value
- `color` gets assigned a new color, which may have a different alpha value
- if `is_editing_alpha()` is disabled (i.e. the user wants to keep the original alpha value), the original alpha value is restored

After your change, this code is this:
```cpp
float last_alpha = color.a;
if (!is_editor_alpha()) {
	color.a = last_alpha;
}
```

Tautological, isn't it?

Comment (Mickeon) [reply scene/gui/color_picker.cpp]: Thank you for your eye, I have addressed it fully.

**Review by akien-mga — APPROVED** [review]

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.
