### PR TITLE
Handle `RGB10_A2` storage format in octmap shaders.

### LINKED ISSUE #113909: Vulkan validation messages about mismatched image format related to radiance octmap
### Tested versions

- Godot 4.6-beta 14e840dd752884c4d98cb16f5f6f5fb1604c1e3d

### System information

Android - Samsung Galaxy XR - Qualcomm Adreno (TM) 740

### Issue description

Using the Vulkan mobile renderer on a Samsung Galaxy XR, I'm getting a bunch of vulkan validation messages that all look like this:

```
W 0:00:03:705   _debug_messenger_callback: VALIDATION - Message Id Number: 20145586 | Message Id Name: Undefined-Value-StorageImage-FormatMismatch-ImageView
	vkCmdDispatch(): the storage image descriptor [VkDescriptorSet 0x8630000000863, Set 1, Binding 0, Index 0] is accessed by a OpTypeImage that has a Format operand Rgba16f (equivalent to VK_FORMAT_R16G16B16A16_SFLOAT) which doesn't match the VkImageView 0x7fb00000007fb[Downsampled Radiance Octmap Mip 0  View] format (VK_FORMAT_A2B10G10R10_UNORM_PACK32). Any loads or stores with the variable will produce undefined values to the whole image (not just the texel being accessed).
Spec information at https://docs.vulkan.org/spec/latest/chapters/textures.html#textures-format-validation
	Objects - 3
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 1278732023104651
		Object[1] - VK_OBJECT_TYPE_DESCRIPTOR_SET, Handle 2360651464837219
		Object[2] - VK_OBJECT_TYPE_IMAGE_VIEW, Handle 2246302255548411, Name "Downsampled Radiance Octmap Mip 0  View"
  <C++ Source>  drivers/vulkan/rendering_context_driver_vulkan.cpp:639 @ _debug_messenger_callback()
W 0:00:03:706   _debug_messenger_callback: VALIDATION - Message Id Number: 20145586 | Message Id Name: Undefined-Value-
```

It goes through "Downsampled Radiance Octmap Mip 0" to "... Mip 5", and then has a series that don't specifically mention the radiance octmap like this:

```
W 0:00:03:706   _debug_messenger_callback: VALIDATION - Message Id Number: 20145586 | Message Id Name: Undefined-Value-StorageImage-FormatMismatch-ImageView
	vkCmdDispatch(): the storage image descriptor [VkDescriptorSet 0x86f000000086f, Set 1, Binding 0, Index 0] is accessed by a OpTypeImage that has a Format operand Rgba16f (equivalent to VK_FORMAT_R16G16B16A16_SFLOAT) which doesn't match the VkImageView 0x7f200000007f2 format (VK_FORMAT_A2B10G10R10_UNORM_PACK32). Any loads or stores with the variable will produce undefined values to the whole image (not just the texel being accessed).
Spec information at https://docs.vulkan.org/spec/latest/chapters/textures.html#textures-format-validation
	Objects - 3
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 1312816883565738
		Object[1] - VK_OBJECT_TYPE_DESCRIPTOR_SET, Handle 2373845604370543
		Object[2] - VK_OBJECT_TYPE_IMAGE_VIEW, Handle 2236406650898418
  <C++ Source>  drivers/vulkan/rendering_context_driver_vulkan.cpp:639 @ _debug_messenger_callback()
```

And then it gives up after 10 times.

I assume this originates from https://github.com/godotengine/godot/pull/107902

I'm using the Vulkan validation Android binaries version 1.4.335.0 from [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/releases/tag/vulkan-sdk-1.4.335.0).

### Steps to reproduce

- Make a new project using the Vulkan Mobile renderer
- Add a world environment that includes a procedural sky
- Setup your project to build with Gradle
- Install the Android build templates
- Copy the Vulkan Validation binaries into `android/build/libs/debug/arm64-v8a/`
- Deploy to your Android device with remote debug, and see the messages appear in the editor's errors tab

### Minimal reproduction project (MRP)

The MRP from https://github.com/godotengine/godot/issues/113778 also shows this issue - just add the Vulkan validation layers

### PR DESCRIPTION
**Pull request by blueskythlikesclouds**
Fixes #113909.
Fixes corrupted pixels on PowerVR GE8320.

### CODE REVIEW

**Review by clayjohn — CHANGES_REQUESTED** [review]
I think we should probably just go back to using the raster version always with the mobile renderer. 

This is adding too much complexity. We thought it would be nice to unify on a compute shader code path, but it's clear that it's not as simple as we thought.

File: servers/rendering/renderer_rd/effects/copy_effects.cpp [hunk 1]
```diff
@@ -164,6 +164,7 @@ CopyEffects::CopyEffects(BitField<RasterEffects> p_raster_effects) {
 		cube_to_octmap.pipeline.setup(shader, RD::RENDER_PRIMITIVE_TRIANGLES, RD::PipelineRasterizationState(), RD::PipelineMultisampleState(), RD::PipelineDepthStencilState(), RD::PipelineColorBlendState::create_disabled());
 	}
 
+	String octmap_format_defines = p_prefers_rgb10_a2 ? "\n#define OCTMAP_FORMAT rgb10_a2\n" : "\n#define OCTMAP_FORMAT rgba16f\n";
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/effects/copy_effects.cpp]: The shader baker won't like this. We need to generate both versions and then select between them at run time based on `_render_buffers_get_preferred_color_format()`

Comment (blueskythlikesclouds) [reply servers/rendering/renderer_rd/effects/copy_effects.cpp]: I changed it to a shader variant now. The modes were also getting out of hand, so I turned them into bit combinations, like how color pass flags are done.

File: servers/rendering/renderer_rd/effects/copy_effects.cpp [hunk 2]
```diff
@@ -1226,8 +1288,35 @@ void CopyEffects::octmap_filter(RID p_source_octmap, const Vector<RID> &p_dest_o
...
+		mode |= FILTER_MODE_FLAG_HIGH_QUALITY;
+	}
+	for (int i = 0; i < p_dest_octmap.size(); i++) {
+		RD::TextureFormat texture_format = RD::get_singleton()->texture_get_format(p_dest_octmap[i]);
+		switch (texture_format.format) {
+			case RD::DATA_FORMAT_A2B10G10R10_UNORM_PACK32: {
+				if (i == 0) {
+					mode |= FILTER_MODE_FLAG_RGB10_A2;
+				} else {
+					ERR_FAIL_COND_MSG((mode & FILTER_MODE_FLAG_RGB10_A2) == 0, "All destination octmaps must share the same format.");
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/effects/copy_effects.cpp]: I don't think this error checking is worth the cost `p_dest_octmap` is an array of views into the same texture. So the format will always be the same

**Review by clayjohn — COMMENTED** [review]
Looks mostly good. Now that we are making actual permutations of the shaders I hope you see what I mean about this adding complexity. But overall I think the changes are good and switching to using the bit flag approach will keep things a bit simpler long term if we end up adding more permutations (but I sincerely hope we don't need to add any more)

File: servers/rendering/renderer_rd/effects/copy_effects.cpp (hunk 2 above)
Comment (blueskythlikesclouds) [reply servers/rendering/renderer_rd/effects/copy_effects.cpp]: Made it take the format from the first texture in the list.

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!
