### PR TITLE
Fix `EditorScenePostImportPlugin::_get_internal_option_visibility()` having no effect

### LINKED ISSUE #118652: EditorScenePostImportPlugin _get_internal_option_visibility broken
### Tested versions

- Reproducible since at least 4.3.stable
- Not reproducible until at least 4.2.stable (feature works as expected since its inception in 4.0)

### System information

Godot v4.6.1.stable - Windows 11 (build 26200) - Multi-window, 2 monitors - Direct3D 12 (Forward+) - dedicated NVIDIA GeForce RTX 5080 (NVIDIA; 32.0.15.9186) - AMD Ryzen 9 9900X 12-Core Processor (24 threads) - 61.55 GiB memory

### Issue description

EditorScenePostImportPlugin's callback _get_internal_option_visibility does not work at all.
The function is not being called. (print statements don't show up.)
The return value is ignored. (properties show up as normal, even when return value is `false`.)

### Steps to reproduce

1. unzip the mrp
2. open godot. 
3. create new project in the unzipped folder
4. (godot 4.3 and later) toggle `create folder` off
5. confirm the warning to create project in non-empty folder
6. (open the project)
7. enable the `importer_test` plugin in project settings
8. open assets/cube.glb
9. click the mesh instance or the mesh node
10. (on versions 4.0 - 4.2) observe that the properties don't show up on the right and that print messages are logged  in the output (expected behavior)
11. (on versions 4.3 and above) observe that all the properties show up on the right, despite import_plugin.gd implementing _get_internal_option_visibility to return false
12. (on versions 4.3 and above) also observe that no log message is printed despite _get_internal_option_visibility implementing a print call

### Minimal reproduction project (MRP)

[importer_bug_mrp.zip](https://github.com/user-attachments/files/26794494/importer_bug_mrp.zip)

### PR DESCRIPTION
**Pull request by ArokhSlade**
post_import_plugin_skeleton_rest_fixer::_get_internal_option_visibility() gets called before user plugins. as it used to return true by default, it would always override/intercept any user implementation.

now it returns null for those cases it is not explicitly coded to handle, indicating "ignore". see also: https://github.com/godotengine/godot/issues/118652

EditorScenePostImportPlugin's _get_internal_option_visibility had no effect

*Bugsquad edit:*
- Fixes #118652

### CODE REVIEW

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 1]
```diff
@@ -81,7 +81,7 @@ Variant PostImportPluginSkeletonRestFixer::get_internal_option_visibility(Intern
 			return int(p_options["retarget/rest_fixer/retarget_method"]) == 2 && bool(p_options["retarget/bone_renamer/rename_bones"]) == false;
 		}
 	}
-	return true;
+	return Variant{};
```
Comment (AThousandShips) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp]:
```suggestion
	return Variant();
```
Minor nitpic, standard way

**Comment by ArokhSlade** [comment]
There is also this comment at https://github.com/godotengine/godot/blob/master/editor/import/3d/resource_importer_scene.cpp#L2547 which may be referring to this bug but I'm not sure.
> // TODO: If there are more than 2 or equal get_internal_option_visibility method, visibility state is broken.

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp (hunk 1 above)
Comment (ArokhSlade) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp]: Thanks, I had actually searched for that in the contributor guidelines but didn't find anything.

I commited your suggestion.

Now, I think I better ask, before i make a mess:
The [contributor guide](https://docs.godotengine.org/en/3.5/community/contributing/pr_workflow.html#the-interactive-rebase) tells me that I should squash the commits for neatness, using the interactive rebase workflow described there.

Can you give me reassurance that that would be the right thing do now?

**Review by aaronfranke — APPROVED** [review]
This fix is correct, I checked the code. If all calls return non-booleans it will still return true overall.

Should be squashed though. @ArokhSlade please do so, and see here for instructions: https://contributing.godotengine.org/en/latest/pull_requests/creating_pull_requests.html#the-interactive-rebase

**Comment by ArokhSlade** [comment]
squash complete

**Review by aaronfranke — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
