### PR TITLE
Fixes missing descriptions in Visual Script search window when adding nodes

### LINKED ISSUE #48699: Node descriptions don't appear in VisualScript editor's "Add Nodes"/Search window
**Godot version:**

3.3

**OS/device including version:**

macOS

**Issue description:**

When you extend another node, e.g. array variable - there you can see nodes descriptions, for example 
изображение

When you try to add node via search or "add nodes", you see this:
изображение

**Steps to reproduce:**
^^^
In description

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by theoway**
Fixes #48699

**Issue:** When the search window is opened to add nodes in visual script by "right-clicking" on the canvas, some of the functions(found in methods of `Vector2`, `String`, `Array` etc.) would not have their descriptions showing. But when the search window is opened by dragging connection out of the data port of a node, the functions that weren't showing descriptions previously, will have descriptions now. _Kindly see the issue mentioned above for more details_

This PR is for master branch, but the issue is presented in 3.x as well!

_Before the fix, these descriptions would not show_
Screenshot (251)

### CODE REVIEW

**Comment by pycbouh** [comment]
Your commit message needs to state what it would do if applied, not repeat the problem it solves. A simple change like “Fix missing descriptions ...” would be enough.

**Comment by theoway** [comment]
> Your commit message needs to state what it would do if applied, not repeat the problem it solves. A simple change like “Fix missing descriptions ...” would be enough.

Will take care next time! Thanks! Also, do I need to make any changes to the title or commit message. Lemme know :)

**Comment by pycbouh** [comment]
Title is not as important, but commit must be amended before this can be merged. This is because the commit history is, well, eternal, so as uniform and clear it is as easy it is to work with it.

Titles of PRs are not as important, though should generally align with the commit message.

This, and more, in our PR workflow guide https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

**Comment by theoway** [comment]
> Title is not as important, but commit must be amended before this can be merged. This is because the commit history is, well, eternal, so as uniform and clear it is as easy it is to work with it. You can check our commit history to get the idea.
> 
> Titles of PRs are not as important, though should generally align with the commit message.
> 
> This, and more, in our PR workflow guide https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

No problem! Thanks for the tips! I'll change the commit text right away!

File: modules/visual_script/visual_script_property_selector.cpp [hunk 1]
```diff
@@ -469,10 +469,11 @@ void VisualScriptPropertySelector::_item_selected() {
 
 		at_class = ClassDB::get_parent_class_nocheck(at_class);
 	}
-	Map<String, DocData::ClassDoc>::Element *T = dd->class_list.find(class_type);
+	Vector<String> functions = name.rsplit("/", false);
+	at_class = functions.size() > 3 ? (class_type == functions[functions.size() - 2] ? class_type : functions[functions.size() - 2]) : class_type;
```
Comment (akien-mga) [inline modules/visual_script/visual_script_property_selector.cpp:473]: That's a bit hard to read with two ternary operators... but also seems unnecessary? Whether `functions[functions.size() - 2] == class_type` or not you will get the value you need with `functions[functions.size() - 2]`.

```cpp
at_class = functions.size() > 3 ? functions[functions.size() - 2] : class_type;
```

Is it intended to check for `> 3` (i.e. min 4 items) and not `> 2`?

Comment (theoway) [reply modules/visual_script/visual_script_property_selector.cpp:473]: @akien-mga You're absolutely right. It's redundant, I just noticed. My bad! I'll fix it right away...

**Review by fire — APPROVED** [review]
Looks good

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
