### PR TITLE
Fix permission handling for write backup files (`FileAccessUnix`)

### LINKED ISSUE #110929: Saving a GDScript file removes its executable permission (chmod +x)
### Tested versions

Version: 4.5.stable [876b29033]

### System information

macOS Tahoe - M1 Mackbook Air

### Issue description

I followed the Command line tutorial in the Godot Docs.
https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html#running-a-script

I created a GDScript file and added executable permission to it using `chmod +x`.

After confirming that the script runs correctly from the CLI, I edited and saved the file in the Godot editor. 

When I tried to run the script again, I got a "permission denied" error.

It seems that saving the file in the editor removes the executable permission.

### Steps to reproduce

1. Create a GDScript and save it as `sayhello.gd`:
```gdscript
#!/usr/bin/env -S godot -s
extends SceneTree

func _init():
    print("Hello!")
    quit()
```

2. Make the file executable and run it:
```
$ chmod +x sayhello.gd
$ ./sayhello.gd
Hello!
```

3. Edit the file in the Godot editor and save it:
```gdscript
#!/usr/bin/env -S godot -s
extends SceneTree

func _init():
    print("Hello Again!")
    quit()
```

4. Try running it again:
```
$ ./sayhello.gd
zsh: permission denied: ./sayhello.gd
```

### Minimal reproduction project (MRP)

[Godot-permission-issue.zip](https://github.com/user-attachments/files/22561539/Godot-permission-issue.zip)

### PR DESCRIPTION
**Pull request by GlitchedCode922**
This PR adds a check for original file permissions to files written with the setting `Safe Save on Backup then Rename` enabled.

---

Closes #110929

### CODE REVIEW

File: drivers/unix/file_access_unix.cpp [hunk 1]
```diff
@@ -148,7 +148,15 @@ Error FileAccessUnix::open_internal(const String &p_path, int p_mode_flags) {
 			last_error = ERR_FILE_CANT_OPEN;
 			return last_error;
 		}
-		fchmod(fd, 0644);
+
+		struct stat file_stat = {};
+		int error = stat(save_path.utf8().get_data(), &file_stat);
+		if (!error) {
+			fchmod(fd, file_stat.st_mode & 0xFFF);
```
Comment (ajreckof) [inline drivers/unix/file_access_unix.cpp]: I'm assuming this is to seprate file mode from ffile type. if there is a mask defined it would be clearer but maybe there isn't one. If so maybe I think a comment explaining what is this value would be great

**Review by ajreckof — APPROVED** [review]
This looks good.

**Comment by GlitchedCode922** [comment]
Added a comment on the bitmask

**Review by Calinou — APPROVED** [review]
Tested locally on Linux with the MRP from #110929, it works as expected. Using **File > Save** in the script editor preserves the executable status from `sayhello_origin.gd`.

Code looks good to me.

**Comment by Repiteo** [comment]
Thanks!
