### PR TITLE
Expose `copy_effects` compute shader in Mobile backend

### LINKED ISSUE #55868: Vulkan Mobile backend: LightmapGI baking does not take environment lighting into account
### Godot version

4.0.dev (2a9dd654b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

Despite [lightmap rendering not working correctly when using the Vulkan Mobile backend](https://github.com/godotengine/godot/issues/55867), LightmapGI baking *does* work. However, it ignores environment lighting from the sky when it's enabled in the node properties.

**Note:** You need to switch back to the Vulkan Clustered backend and restart the editor to see the lightmap baked in the Vulkan Mobile backend in the editor/project.

### Steps to reproduce

- Import a glTF scene. Set the light bake mode to **Static Lightmaps** in the Import dock and click **Reimport**.
- Add a LightmapGI node.
- Bake lightmaps. Open the resulting EXR file in an image editor.
- Switch to Vulkan Mobile backend in the project settings (search for `back end`).
  - **Note:** The MRP linked below already uses the Vulkan Mobile backend by default.
- Restart the editor and bake lightmaps again. Open the resulting EXR file in an image editor for comparison. Notice the environment lighting is missing.

### Minimal reproduction project

[test_vulkan_clustered_vs_mobile_lightmap_sampling.zip](https://github.com/godotengine/godot/files/7699372/test_vulkan_clustered_vs_mobile_lightmap_sampling.zip)

### PR DESCRIPTION
**Pull request by Lasuch69**
This PR exposes compute version (the only one currently) of copy effects allowing for using some of the RenderingServer's functions on Mobile backend eg. [sky_bake_to_panorama](https://docs.godotengine.org/en/latest/classes/class_renderingserver.html#class-renderingserver-method-sky-bake-panorama).

Baking Lightmaps on development machine works (not considering other bugs).

Note: I encourage to test it on your phone. This is a quick change/hack, feedback necessary.

Fixes: https://github.com/godotengine/godot/issues/55868

image

### CODE REVIEW

File: servers/rendering/renderer_rd/effects/copy_effects.cpp [hunk 1]
```diff
@@ -310,7 +312,7 @@ CopyEffects::~CopyEffects() {
 		filter.raster_shader.version_free(filter.shader_version);
 		roughness.raster_shader.version_free(roughness.shader_version);
 	} else {
-		copy.shader.version_free(copy.shader_version);
+		//copy.shader.version_free(copy.shader_version);
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/effects/copy_effects.cpp:315]: This should still get freed. It just needs to move outside the if/else block

File: servers/rendering/renderer_rd/effects/copy_effects.cpp [hunk 2]
```diff
@@ -386,7 +388,7 @@ void CopyEffects::copy_to_rect(RID p_source_rd_texture, RID p_dest_texture, cons
 }
 
 void CopyEffects::copy_cubemap_to_panorama(RID p_source_cube, RID p_dest_panorama, const Size2i &p_panorama_size, float p_lod, bool p_is_array) {
-	ERR_FAIL_COND_MSG(prefer_raster_effects, "Can't use the compute version of the copy_cubemap_to_panorama shader with the mobile renderer.");
+	//ERR_FAIL_COND_MSG(prefer_raster_effects, "Can't use the compute version of the copy_cubemap_to_panorama shader with the mobile renderer.");
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/effects/copy_effects.cpp:391]: This line can be deleted entirely since this shader will always be available

**Comment by Lasuch69** [comment]
I forgot about other checks too.

**Comment by Lasuch69** [comment]
I can take a look at what functions (without raster version) can be exposed if not all of them need to be exposed.

**Comment by Lasuch69** [comment]
The way I see it is that only copy_cubemap_to_panorama would be of any use. Should I leave other 2 functions as is (with check that is)? 

Note: I haven't tested it on a phone yet, I need to build android template.

**Review by clayjohn — APPROVED** [review]
Looks good to me!

Tested locally to confirm that it works in the test project

**Comment by Calinou** [comment]
> Note: I haven't tested it on a phone yet, I need to build android template.

The lightmapper_rd module isn't built on Android, so it won't work there either way.

**Comment by YuriSizov** [comment]
Thanks!
