### PR TITLE
Fix internal `CONNECT_INHERITED` being saved in PackedScene & Make Local

### LINKED ISSUE #75801: Can't disconnect a connection after making an instance local
### Godot version

4.0.2

### System information

Windows 10 x64

### Issue description

Regression from #69661
The PR added a transient flag that makes instantiated connections uneditable. However when you make the instance local, the flag leaks to the local scene, making the connection impossible to remove other than by manually editing the tscn file.

### Steps to reproduce

1. Make scene A
2. Connect some signal from the root node
3. Make scene B
4. Instantiate A inside B
5. Right click A and use "Make Local"
6. You can no longer disconnect

### Minimal reproduction project

[BuggersDisconnectioners.zip](https://github.com/godotengine/godot/files/11181849/BuggersDisconnectioners.zip)

### PR DESCRIPTION
**Pull request by Mickeon**
Fixes https://github.com/godotengine/godot/issues/75801.

The title is pretty self-explanatory.
Tested with the attached project. The issue fixes itself after resaving the scene.

It would be nice to receive feedback from KoBeWi because judging by the cause, it seems like I have a tendency to overlooking things.

### CODE REVIEW

**Comment by Mickeon** [comment]
As a bit of a side note, there seems to be a regression from https://github.com/godotengine/godot/pull/81221 where the PopupMenu isn't updated properly, causing some options to be unclickable because of that early return.

https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/editor/connections_dialog.cpp#L1193-L1203

Worth keeping that in mind when testing.

**Comment by KoBeWi** [comment]
> As a bit of a side note, there seems to be a regression

I think it should be fixed first, because the popup is broken right now.
As for the PR, it only fixes saving the flag, but you can make new instance and make it local and run into the same issue (until you reload the scene).

**Comment by Mickeon** [comment]
Unsure how to handle this, then. "Sanitizing" the input when the scene is made local may make sense, but having it work seamlessly with UndoRedo looks to be overly verbose. Sanitizing it in `set_scene_file_path()` also seems to make sense to me, but it's a whole new step to an otherwise simple method. Perhaps the usage of a flag has been a mistake all along, if it needs to be discarded half the time...

**Comment by Mickeon** [comment]
I opened a PR about the aforementioned issue. https://github.com/godotengine/godot/pull/81750. Let's see. One thing at the time.

**Comment by Mickeon** [comment]
This PR has been updated with an (admittedly) shoddy solution to prevent **Local Scene** from ever keeping CONNECT_INHERITED. The problem now is that I'm unsure how to go about using UndoRedo here, as dealing with the Node dock like this feels like unexplored territory.

**Comment by Mickeon** [comment]
This PR has been updated with an (admittedly) shoddy solution to prevent Local Scene from ever keeping CONNECT_INHERITED. The problem now is that I'm unsure how to go about using UndoRedo here, as dealing with the Node dock like this feels like unexplored territory.

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1077,6 +1078,8 @@ void SceneTreeDock::_tool_selected(int p_tool, bool p_confirm_override) {
 					undo_redo->add_do_method(node, "set_scene_file_path", "");
 					undo_redo->add_undo_method(node, "set_scene_file_path", node->get_scene_file_path());
 					_node_replace_owner(node, node, root);
+					_node_strip_signal_inheritance(node);
+					NodeDock::get_singleton()->set_node(node); // Refresh.
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:1082]: I wonder if there is better way to refresh it.

**Comment by KoBeWi** [comment]
I think your new method should be recursive.

File: editor/scene_tree_dock.cpp (hunk 1 above)
Comment (Mickeon) [reply editor/scene_tree_dock.cpp:1082]: I wondered too, but it didn't seem like it because all of the "refreshing" logic is inside the `set_node` method. It would require moving it out...

Maybe `NodeDock::restore_last_valid_node` would work just the same?

Comment (KoBeWi) [reply editor/scene_tree_dock.cpp:1082]: It's probably fine for now, but if we ever decide to add early return to `set_node()` it will stop working.
Though my biggest concern would be that this method is not used outside editor node, so either the dock is not refreshed by anything else or there is a better way.

Comment (Mickeon) [reply editor/scene_tree_dock.cpp:1082]: I was about to go with the change, but I'll keep `set_node()` then. The lack of an early return is unexpected though, yeah.

The **NodeDock** has a pretty simple bunch of methods. None of them are like `restore_last_valid_node()` or `set_node()`, so they seem like the closest thing to a refresh?

**Comment by Mickeon** [comment]
Pushed to use make the connection stripping recursive.

**Review by KoBeWi — APPROVED** [review]
There are still some problems (like undo not restoring the flag), but at least it fixes the issue, which is more important.

**Comment by akien-mga** [comment]
Thanks!
