### PR TITLE
Prevent NARROWING_CONVERSION warning for `int(float)` function in GDScript

### LINKED ISSUE #59060: Type casting from `float` to `int` with constructor casting produce warning.
### Godot version

4.0 alpha 4

### System information

Windows 10

### Issue description

When casting the type from float to int with `int(number)` give `NARROWING_CONVERSION` warning in both editor and play mode debugger. It should not raise this warning.

Note: `number as int` is work as expect.

### Steps to reproduce

Write this code
```GDScript
var number: float = 3.2
print(int(number)) # NARROWING_CONVERSION
print(number as int) # ok
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #59060

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2294,7 +2294,7 @@ void GDScriptAnalyzer::reduce_call(GDScriptParser::CallNode *p_call, bool p_is_a
 							break;
 #ifdef DEBUG_ENABLED
 						} else {
-							if (par_type.builtin_type == Variant::INT && p_call->arguments[i]->get_datatype().builtin_type == Variant::FLOAT) {
+							if (par_type.builtin_type == Variant::INT && p_call->arguments[i]->get_datatype().builtin_type == Variant::FLOAT && p_call->function_name != SNAME("int")) {
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:2297]: I think it's better (and probably faster) to check the builtin type, since that was already solved before.
```suggestion
							if (par_type.builtin_type == Variant::INT && p_call->arguments[i]->get_datatype().builtin_type == Variant::FLOAT && builtin_type != Variant::INT) {
```

**Review by vnen — CHANGES_REQUESTED** [review]
I'm not fond of adding exceptions (as they might be forgotten when other things change), but in this case the proper solution would be quite complex, so doing this is be fine. Just the suggested change should be enough.

For reference, the actual problem is that the `int()` constructor has multiple signatures with the same number of parameters but different types. GDScript find the `int(int from)` constructor first, so it thinks the parameter has a narrowing conversion. GDScript should prefer the `int(float from)` constructor, but to do so it would require to know about the multiple types and choose the best match based on those.

It's not something trivial to add, and not really necessary, so for now it's okay to have the exception.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (Chaosus) [reply modules/gdscript/gdscript_analyzer.cpp]: Thanks! Done

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
