### PR TITLE
Fix iOS Crash on Application Exit

### LINKED ISSUE #34952: iOS 13.1+ Crash on Application Exit
**Godot version:**
3.2 beta 5

**OS/device including version:**
Tested on:
Apple iPhone 11 Pro - iOS 13.3
Apple iPad (7th Generation) - iOS 13.1.1
Apple iPhone 7 - iOS 13.1.2
Tested various android devices and none encounter this issue. This seems to be iOS specific.

**Issue description:**
On iOS devices running iOS 13.1.1+ (I have not personally tested this on lower versions of iOS), closing the app results in what appears to be some sort of crash/memory leak. Below is some of the reporting from XCode. There was [another issue reported fixed #7966 ](https://github.com/godotengine/godot/issues/7966) that is similar to this but I am not sure if it was intended to be in 3.2 beta 5. It seems iOS is dropping frames, performance is not great at all despite reporting 60 FPS in the debugger. Using `get_tree().quit()` does not work on iOS - not sure if this is related.

```
2020-01-08 21:06:38.710038-0500 Geocrash[3819:57474] Can't end BackgroundTask: no background task exists with identifier 5 (0x5), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
iphone_finish
2020-01-08 21:06:38.741265-0500 Geocrash[3819:57474] **WARNING**: ObjectDB Instances still exist!
2020-01-08 21:06:38.741331-0500 Geocrash[3819:57474]    At: core/object.cpp:2076:cleanup() - ObjectDB Instances still exist!
**WARNING**: ObjectDB Instances still exist!
   At: core/object.cpp:2076:cleanup() - ObjectDB Instances still exist!
2020-01-08 21:06:38.753357-0500 Geocrash[3819:57474] **ERROR**: BUG!
2020-01-08 21:06:38.753451-0500 Geocrash[3819:57474]    At: core/string_name.cpp:107:unref() - BUG!
**ERROR**: BUG!
   At: core/string_name.cpp:107:unref() - BUG!
Geocrash(3819,0x1020f9800) malloc: *** error for object 0x282c86d40: pointer being freed was not allocated
Geocrash(3819,0x1020f9800) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Steps to reproduce:**
AFAIK any minimal project exported and ran on iOS will experience this crash when closing the app on iOS.

### PR DESCRIPTION
**Pull request by zxcvdev**
Fixes #34952 

Some more testing is advised before merging.

### CODE REVIEW

File: platform/iphone/os_iphone.cpp [hunk 1]
```diff
@@ -356,14 +356,32 @@ void OSIPhone::delete_main_loop() {
 
 void OSIPhone::finalize() {
 
-	if (main_loop) // should not happen?
-		memdelete(main_loop);
+	delete_main_loop();
```
Comment (akien-mga) [inline platform/iphone/os_iphone.cpp]: `delete_main_loop()` is already called in `Main::cleanup()`, so it shouldn't be necessary here. That's also why the comment meant, though it points that maybe something is not working properly if `main_loop` is not `NULL` here.

Comment (zxcvdev) [reply platform/iphone/os_iphone.cpp]: I was confused why that snippet and comment were there so I compared the `OSIPhone::finalize()` function to the `OS_OSX::finalize()` function for the MacOSX platform and there its `delete_main_loop()` is called inside the  `OS_OSX::finalize()` function.

https://github.com/zxcvdev/godot/blob/9a90ea14259edc6596fa73e03d635ca822d9ac37/platform/osx/os_osx.mm#L1656-L1674

So inside `OSIPhone::finalize()` I replaced the mentioned snippet with `delete_main_loop()` to be uniform since the content of `delete_main_loop()` is functionally the same as the replaced code.

https://github.com/zxcvdev/godot/blob/9a90ea14259edc6596fa73e03d635ca822d9ac37/platform/iphone/os_iphone.cpp#L347-L355

But if you want me to leave it as it was, let me know.

Comment (akien-mga) [reply platform/iphone/os_iphone.cpp]: I think it's fine to use this as you did, especially if macOS also does it, which confirms that the `Main::cleanup()` is not sufficient (or is not called on those platforms maybe?).

Needs a good refactoring pass, but for the scope of fixing the crash for 3.2 that's definitely good as is.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by HEAVYPOLY** [comment]
I'm getting crash on app exit on 3.2 stable with iOS 13.3.1  Is this fix in 3.2 already?

**Comment by HEAVYPOLY** [comment]
Just tried with latest Xcode version, iPadOS 13.3.1, 3.2 stable.  When I swipe up and close app I get this during debug:
2020-02-02 13:57:17.417159-0800 HEAVYPAINT[4726:95868] Can't end BackgroundTask: no background task exists with identifier 2 (0x2), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
iphone_finish

Also tried with TestFlight version and get a crash on app exit

**Comment by zxcvdev** [comment]
@HEAVYPOLY  Are you actually getting a crash or just an error message?

This PR prevented a hard crash of the app when the app was closed (Xcode would show an malloc error, point to the location and the app process would be halted).

The error message

> 2020-02-02 13:57:17.417159-0800 HEAVYPAINT[4726:95868] Can't end BackgroundTask: no background task exists with identifier 2 (0x2), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

 is generated when the app is put to the background since 2 touch events are still unhandled, the app however should not crash (The fixed crash occurred when these unhandled touch events stayed unhandled when the app was closed). If you put the app to the background and foreground multiple times, you will get this error message every time, the app however should not crash. To get rid of this error message the way inputs are handled in Godot on iOS when the app is put to the background and brought back to the foreground, has to be further look at as I mentioned [here](https://github.com/godotengine/godot/issues/34952#issuecomment-575878989).

Note that iOS 13 has been notorious for closing/killing apps with above average memory usage when they are put to the background. So if your app closes automatically when put to the background, this might be the issue.

**Comment by HEAVYPOLY** [comment]
@zxcvdev  Thanks for the thorough explanation.  
I'm getting a crash popup message when I close the app on testflight, does that count?
File Feb 05, 9 28 24 AM

The strange thing is that an earlier version of the app exported from 3.2 RC4 has no crash on exit.  But on 3.2 stable, crash on exit (testflight version).  Both installed on the same iOS 13.3.1 iPad currently.
I'll check out the memory issue too..but wouldn't it affect the 3.2RC4 version too?

**Comment by zxcvdev** [comment]
This PR has been merged since Godot 3.2 RC 2 to prevent a crash on exit. If RC 4 was working something in Godot 3.2 has to have changed from RC 4 until stable or maybe something in your latest app version that causes the crash.

Or maybe TestFlight might report the above mentioned error message as a crash (which Xcode doesn't).

Do you get the crash on older iOS devices with a home button? Because the 2 unhandled touch events are generated by the swipe up motion on newer devices (I suspect).

**Comment by HEAVYPOLY** [comment]
Ok, I tried loading the older app version on Testflight, also getting the crash there (But not on App Store version of the same build). So I guess Testflight is treating that error message as a crash.  I will try publishing the new version to App Store and report back with results

**Comment by HEAVYPOLY** [comment]
The new upload does not crash on Testflight!  It must be something I've changed accidentally.  Publishing to App Store now.  Thanks for helping
