### PR TITLE
Don't use saved editor dialog size in single-window-mode.

### LINKED ISSUE #75084: Project/Editor settings dialog saved position in single window mode does not work well with resizing the editor
### Godot version

4.0

### System information

Linux

### Issue description

I'm using a tiling window manager (`dwm`) and running the editor in single window mode.
When `godot` is maximized, the project and editor settings dialogs are properly centered in Godot's window.
When `godot` is tiled to a half or quarter of the screen, these dialogs do not use space effectively

Other dialogs, like `Export`, seem better:

### Steps to reproduce

1. Open the project settings dialog
2. Tile `godot` to half or a quarter of the display.

### Minimal reproduction project

Can repro with an empty project.

### PR DESCRIPTION
**Pull request by rcorre**
Fixes #75084.

If single_window_mode is enabled, trying to place editor dialogs with a saved size
often looks wrong if the main editor window has been resized.
This can result in windows being partially (or mostly) off-screen,
or just off-centered.

### CODE REVIEW

**Comment by rcorre** [comment]
It might be nice to re-position the dialog if the parent window size changes, but I checked `godot3` and it doesn't do that either, so at least that part isn't a regression.

**Comment by YuriSizov** [comment]
I don't think this improves the situation meaningfully. If a dialog has a big enough size by default, it will still slide off of the screen. I think we should address this properly, instead of restoring a behavior to be similar to 3.x.

Dialogs need to respect the size of their parent window when embedded, and treat it as their max size. This should likely be an option, not a default behavior, as the opposite may still be useful in games and apps made with Godot.

**Comment by rcorre** [comment]
Thanks for the feedback @YuriSizov. I agree this isn't ideal, but I'm not quite following you. Are you saying that if `popup` is called with bounds that do not fit within the parent, it should adjust the bounds so they do? That is, we'd either (A) clamp the offending bounds or (B) shift the bounds?

example

**Comment by YuriSizov** [comment]
I think you follow me quite well :) IMO we should try both. If the size is within the parent's size, just slide it over. If it's bigger, then resize it to fit.

But again, this should probably be a flag on the Window node, and not the default behavior. We need it for the editor, but it may still be desirable for other projects to spawn windows out of frame.

**Comment by rcorre** [comment]
NVM. 8be16e0 was just about being able to drag windows outside the editor bounds. `clamp_to_embedder` only applies to drag events. Should `clamp_to_embedder` also work on `popup` and parent window resize events, or should that be a separate setting?

**Comment by YuriSizov** [comment]
I think it should apply here, yes. If you can't drag a window outside, then I think it's safe to assume you don't want to spawn it outside either.

**Comment by rcorre** [comment]
I updated it so windows that are clamped to their embedder are now automatically shifted/resized on popup, and when the parent is resized.

In the recording, there's a lag when I resize the parent. That only happens when I'm recording, so I'm guessing it's something weird with X11 and SSR? It seems reponsive when I'm not recording the screen.

https://user-images.githubusercontent.com/2496231/227674865-1c62f142-a829-4130-ae42-96b42193883a.mp4

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -875,6 +875,17 @@ void Viewport::_set_size(const Size2i &p_size, const Size2i &p_size_2d_override,
 	}
 
 	emit_signal(SNAME("size_changed"));
+
+	for (int i = 0; i < gui.sub_windows.size(); ++i) {
+		Window *sw = gui.sub_windows[i].window;
+		Rect2i rect = Rect2i(sw->position, sw->size);
+		Rect2i limit = get_visible_rect();
```
Comment (YuriSizov) [inline scene/main/viewport.cpp:882]: Can be moved out of loop.

**Review by YuriSizov — APPROVED** [review]
This looks great to me! Will wait a bit for another review, but this should be good to merge.

**Review by bruvzg — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
