### PR TITLE
Fix editing `ShaderInclude` causes a `Shader` to be edited

### LINKED ISSUE #103159: Editing ShaderInclude causes a Shader to be edited
### Tested versions

4.4 rc1

### System information

W10

### Issue description

https://github.com/user-attachments/assets/ea6404cb-81c1-4c7c-821c-f48ccf4eb3c9

There is a Shader unfolded in the inspector. Editing the include causes recompilation of the shader, which makes ShaderMaterial modifed and update the inspector, which re-opens the Shader resource and edits it in the editor.

Easiest fix would be not editing resource again when the inspector is refreshed.

### Steps to reproduce

1. Open the MRP
2. Open ShaderInclude in shader editor
3. Click the ColorRect and unfold material -> shader
4. Edit shader include in shader editor

### Minimal reproduction project (MRP)

[BottomPanelBug.zip](https://github.com/user-attachments/files/18922415/BottomPanelBug.zip)

### PR DESCRIPTION
**Pull request by beicause**
Fixes #103159

### CODE REVIEW

**Comment by KoBeWi** [comment]
I'm not sure it's a correct fix. Selecting shader will change the object at the top of the inspector, while still inspecting the previous object.

https://github.com/user-attachments/assets/0fe13f4b-334c-42c4-9c93-ba7914d2b249

While it does fix the issue, it seems rather hacky.
Then again, I think that top button is not always synced anyway, so maybe it's fine?

**Comment by beicause** [comment]
It should be fine. We also used  `push_item_no_inspector()` in `SceneTreeDock` and `CreateDialog` to open script.
IMO this is the easiest way to fix the issue.

File: editor/plugins/shader_editor_plugin.cpp [hunk 1]
```diff
@@ -382,6 +382,11 @@ void ShaderEditorPlugin::_shader_selected(int p_index) {
 
 	shader_tabs->set_current_tab(p_index);
 	shader_list->select(p_index);
+	if (edited_shaders[p_index].shader.is_valid()) {
+		EditorNode::get_singleton()->push_item_no_inspector(edited_shaders[p_index].shader.ptr());
```
Comment (KoBeWi) [inline editor/plugins/shader_editor_plugin.cpp:388]: You could add a comment explaining why is it needed.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
