### PR TITLE
Fix BlendShapeTrack insertion not working

### LINKED ISSUE #94737: BlendShapeTrack insertion is not working
### Tested versions

4.1, 4.2, 4.3

### System information

Any

### Issue description

Insertion of BlendshapeTrack in AnimationTrackEditor uses PropertySelector, but the path set is wrong.

image
image
image

BlendShapeTrack was implemented in 4.0. The correct path format is `Node3D:[BlendshapeName]`, not `Node3D:blendshapes/[BlendshapeName]`.

### Steps to reproduce

Insert BlendshapeTrack on AnimationTrackEditor

### Minimal reproduction project (MRP)

[blend_shape_test.zip](https://github.com/user-attachments/files/16377931/blend_shape_test.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/94737

> BlendShapeTrack was implemented in 4.0. The correct path format is Node3D:[BlendshapeName], not Node3D:blendshapes/[BlendshapeName].

image

The keying button on inspector also needs to be fixed, so I will follow up later.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/animation_track_editor.h [hunk 1]
```diff
@@ -34,6 +34,7 @@
 #include "editor/editor_data.h"
 #include "editor/editor_properties.h"
 #include "editor/property_selector.h"
+#include "scene/3d/mesh_instance_3d.h"
```
Comment (KoBeWi) [inline editor/animation_track_editor.h:37]: This should be in cpp file.
Or you can use `is_class()` to avoid including it at all.

**Review by fire — APPROVED** [review]
Can be cherry picked when we've tested more.

**Comment by akien-mga** [comment]
Thanks!
