### PR TITLE
Fix `split_floats` behavior when spaces are used as separators

### LINKED ISSUE #95609: String.split_floats() repeats numbers when extra spaces are present
### Tested versions

Godot 4.3-stable

### System information

macOS 14.5

### Issue description

The `split_floats` function on String repeats numbers when extra spaces are present. The same does not happen for all delimiters, if using `,` the extra fields are zero.

```gdscript
func _ready() -> void:
	print(" -2.0        5".split_floats(" "))
	print(",-2.0,,,,,,,,5".split_floats(","))
```

Output:

```
[-2, -2, 5, 5, 5, 5, 5, 5, 5, 5]
[0, -2, 0, 0, 0, 0, 0, 0, 0, 5]
```

### Steps to reproduce

Run the above GDScript code.

### Minimal reproduction project (MRP)

Paste the above lines of GDScript code into an empty project.

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #95609

`String::to_float()` parses a null terminated string but we only want it to parse a specific slice of the string.

I didn't choose to modify the implementation of `String::to_float()`. This is because it is a wrapper for `built_in_strtod()`, which in turn is a generically typed version of the standard library function `strtod()`.

Also adds a test case for this scenario. Adjusted how the original test case was written so it's easier to extend.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: tests/core/string/test_string.h [hunk 1]
```diff
@@ -638,64 +638,90 @@ TEST_CASE("[String] Ends with") {
...
+		for (int i = 0; i < d_arr.size(); i++) {
+			CHECK(ABS(d_arr[i] - slices[i]) <= 0.00001);
+		}
 
-	Vector<int> ii;
-	ii = s.split_ints(";");
-	CHECK(ii.size() == 2);
-	for (int i = 0; i < ii.size(); i++) {
-		CHECK(ii[i] == slices_i[i]);
+		const Vector<String> keys{ ";", " " };
```
Comment (akien-mga) [inline tests/core/string/test_string.h:683]: I believe it's equivalent but for consistency with how we usually do it:
```suggestion
		const Vector<String> keys = { ";", " " };
```

File: tests/core/string/test_string.h [hunk 2]
```diff
@@ -638,64 +638,90 @@ TEST_CASE("[String] Ends with") {
...
+		const String s = " -2.0        5";
+		const double slices[10] = { 0, -2, 0, 0, 0, 0, 0, 0, 0, 5 };
+
+		const Vector<double> arr = s.split_floats(" ");
+		CHECK(arr.size() == 10);
+		for (int i = 0; i < arr.size(); i++) {
+			CHECK(ABS(arr[i] - slices[i]) <= 0.00001);
+		}
+
+		const Vector<String> keys{ ";", " " };
```
Comment (akien-mga) [inline tests/core/string/test_string.h:701]:
```suggestion
		const Vector<String> keys = { ";", " " };
```

File: tests/core/string/test_string.h [hunk 3]
```diff
@@ -638,64 +638,90 @@ TEST_CASE("[String] Ends with") {
...
+		const String s = "1;2 4";
+		const int slices[3] = { 1, 2, 4 };
+
+		const Vector<int> arr = s.split_ints(";");
+		CHECK(arr.size() == 2);
+		for (int i = 0; i < arr.size(); i++) {
+			CHECK(arr[i] == slices[i]);
+		}
+
+		const Vector<String> keys{ ";", " " };
```
Comment (akien-mga) [inline tests/core/string/test_string.h:719]:
```suggestion
		const Vector<String> keys = { ";", " " };
```

**Comment by akien-mga** [comment]
Thanks!
