### PR TITLE
Fix TileMap selection pattern being needlessly reorganized

### LINKED ISSUE #53901: When changing layer with tile pattern active, the pattern gets messed up
### Godot version

c2a616f

### System information

W10

### Issue description

Z4gfSVEvPe
The blue and red icon are in different tile atlases.

### Steps to reproduce

1. Draw some tiles using multiple atlases as sources
2. Use Picker tool to select a pattern
3. Change layer

### Minimal reproduction project

[AtlasPatternMess.tscn.txt](https://github.com/godotengine/godot/files/7358390/AtlasPatternMess.tscn.txt)

EDIT:
This actually happens even if the tiles are from the same atlas:
6ypSCEmLaP

### PR DESCRIPTION
**Pull request by groud**
Fixes https://github.com/godotengine/godot/issues/53901

This PR removes some processing that aimed to fix the TileMap editor selection when switching layer, tabs, etc. But I believe it's probably too safe. So I replaced it by something that seems to make more sense to me.

Note that the editor will keep the pattern even if you change TileSet (so, like, the pattern will be the same but using another TileSet, if that's clear). That might be a bit weird but it does not cause any error, so I did not bother fixing that by keeping an reference of the edited TileSet in the editor.

I didn't spot any obvious regressions by this change, but there might be some situations where the removal of those "too safe" operations might lead to some small regressions.

### CODE REVIEW

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 1]
```diff
@@ -1640,12 +1640,15 @@ void TileMapLayerEditorTilesPlugin::_update_fix_selected_and_hovered() {
...
-	} else if (tiles_bottom_panel->is_visible_in_tree()) {
-		_update_selection_pattern_from_tileset_tiles_selection();
-	} else {
-		_update_selection_pattern_from_tileset_pattern_selection();
+	// Cleanup selection.
+	for (const KeyValue<Vector2i, TileMapCell> &E : selection_pattern->get_pattern()) {
+		const Vector2i key = E.key;
+		const TileMapCell &selected = E.value;
+		if (!tile_set->has_source(selected.source_id) ||
+				!tile_set->get_source(selected.source_id)->has_tile(selected.get_atlas_coords()) ||
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_map_layer_editor.cpp:1648]: This can be skipped, no? Unless an alternate tile can exist without tile?

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
