### PR TITLE
[3.x] Port Bullet's convex hull computer to replace QuickHull

### LINKED ISSUE #45946: QuickHull generates bad hull sometimes when multiple triangles share the same plane.
**Godot version:**
3.2.3
3.2.4.rc2

**OS/device including version:**
Windows 10

**Issue description:**
QuickHull fails to merge edges sometimes and results in generating multiple of the same plane and wrong geometry.  Errors printed to the log include things like:
 core\math\quick_hull.cpp:402 - Condition "O == 0" is true. Continuing.
 core\math\quick_hull.cpp:399 - Condition "!F" is true. Continuing.
 core\math\quick_hull.cpp:428 - Condition "!F2" is true. Continuing.

Example:
image
Edit: Just tried in 3.2.4.rc2, and the result was slightly different, but still broken:
image
(Should just be an octagon)

**Steps to reproduce:**
Generate a convex collision from something like a cylinder or another object that has many triangles on the same face, preferably at some odd angle.  Doesn't always reproduce.

**Notes:**
I've stepped through the QuickHull::build() function, and the problem seems to reside in the logic to merge faces and remove edges on a single plane.  It makes some assumptions about the structure/order of vertices.  If things overlap instead of being next to each other, the algorithm falls apart.  When the errors happen, extra planes are left in the hull that shouldn't be there.

It might be better to just generate the the planes, ignoring edges and verts, then generate the edges and verts at the end based on plane intersections.  It would also be nice if the edge generation was optional, because it's only necessary when displaying the hull, not when using it for collision purposes.

**Minimal reproduction project:**
[test_quickull.zip](https://github.com/godotengine/godot/files/5975048/test_quickull.zip)

### PR DESCRIPTION
**Pull request by mortarroad**
Supersedes #47307 and #47332.
Fixes #45946.

The code is based on the current version of thirdparty/vhacd and modified to use Godot's types.

Again, against 3.x first, since that's what I work with.
I can port it to master, once it is ready to be merged.

I still have some questions:
- What to do with the assertions? I think they may be too heavy to replace them with error macros, since that causes them to be left in for release builds, but I can't find how assertions are done in Godot.
- Is LocalVector the proper type to use here?
- Perhaps the custom classes PoolArray and Pool should be replaced with Godot's types (perhaps PagedAllocator) or even no pooling at all.

### CODE REVIEW

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Thanks for your work! I haven't tested yet, but I've left some comments about coding style.

Concerning your specific questions:

> What to do with the assertions? I think they may be too heavy to replace them with error macros, since that causes them to be left in for release builds, but I can't find how assertions are done in Godot.

What you can do is to wrap error calls with defines to avoid doing them in release, so they will show up only in the editor (it's configured in release_debug) and in game debug/release_debug.

Something like that:
```
#ifdef DEBUG_ENABLED
#define CHULL_ASSERT(m_cond) if (unlikely(!m_cond)) ERR_PRINT("Assertion \"" _STR(m_cond) "\" failed.")
#else
#define CHULL_ASSERT(m_cond)
#endif
```

> Is LocalVector the proper type to use here?

Yes, it's the proper type to avoid copy-on-write.

> Perhaps the custom classes PoolArray and Pool should be replaced with Godot's types (perhaps PagedAllocator) or even no pooling at all.

Yes, it looks like it would work well in this case! It should be fine to backport `paged_allocator.h` along with `spin_lock.h` (which you don't need in your case, but better keep things synchronized with master).

Since files are organized in a slightly different way on 3.x, `paged_allocator.h` should probably go to the core folder directly.

File: core/math/convex_hull.cpp [hunk 1]
```diff
@@ -0,0 +1,2335 @@
...
+		real_t toScalar() const {
+			return sign * ((m_denominator == 0) ? FLT_MAX : (real_t)m_numerator / m_denominator);
+		}
+	};
+
+	class Rational128 {
+	private:
+		Int128 numerator;
+		Int128 denominator;
+		int32_t sign;
```
[the remark this answers is not in the document]
Comment (mortarroad) [reply core/math/convex_hull.cpp:312]: I assume you mean they need to be at least initialized in every possible constructor.
Most other types in math/ don't initialize their members at the declaration site.

**Comment by mortarroad** [comment]
Considering PagedAllocator:
That won't work, since the implementation does not free all objects. I.e. the Pool takes care of freeing them in the end.

**Comment by mortarroad** [comment]
I think this should be ready for review again now.

File: core/math/convex_hull.cpp [hunk 2]
```diff
@@ -0,0 +1,2360 @@
...
+		edges.clear();
+		faces.clear();
+		return shift;
+	}
+
+	vertices.resize(0);
+	edges.resize(0);
+	faces.resize(0);
+
+	LocalVector<ConvexHullInternal::Vertex *> oldVertices;
```
Comment (pouleyKetchoupp) [inline core/math/convex_hull.cpp:2252]: Should be `old_vertices`

File: core/math/convex_hull.cpp [hunk 3]
```diff
@@ -0,0 +1,2360 @@
...
+	get_vertex_copy(hull.vertex_list, oldVertices);
+	int32_t copied = 0;
+	while (copied < (int32_t)oldVertices.size()) {
+		ConvexHullInternal::Vertex *v = oldVertices[copied];
+		vertices.push_back(hull.get_coordinates(v));
+		ConvexHullInternal::Edge *firstEdge = v->edges;
```
Comment (pouleyKetchoupp) [inline core/math/convex_hull.cpp:2258]: Should be `first_edge`

File: core/math/convex_hull.cpp [hunk 4]
```diff
@@ -0,0 +1,2360 @@
...
+		if (firstEdge) {
+			int32_t firstCopy = -1;
+			int32_t prevCopy = -1;
```
Comment (pouleyKetchoupp) [inline core/math/convex_hull.cpp:2261]: Should be `first_copy`and `prev_copy`

File: core/math/convex_hull.cpp [hunk 5]
```diff
@@ -0,0 +1,2360 @@
...
+	if (sign != b.sign) {
+		return sign - b.sign;
+	} else if (sign == 0) {
+		return 0;
+	}
+	if (is_int_64) {
+		return -b.compare(sign * (int64_t)numerator.low);
+	}
+
+	Int128 nbdLow, nbdHigh, dbnLow, dbnHigh;
```
Comment (pouleyKetchoupp) [inline core/math/convex_hull.cpp:852]: These need to be snake case too.

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Concerning PagedAllocator:
Unless I'm missing something specific, it has a method `reset()` to deallocate everything, and it's called in the destructor so it should be fine.

Concerning my comments:
It's just more things about code style. I didn't comment all of them, but I've seen more local variables in different methods of `ConvexHullInternal` that don't use snake case.

**Comment by pouleyKetchoupp** [comment]
I've just made some tests and it seems to work well!
This PR also fixes #44090.

I've made a quick test using `PagedAllocator` and it doesn't seem as straightforward, it's causing crashes for me, so it's something that can be revisited later (unless you'd like to try and make it work).

**Comment by mortarroad** [comment]
That's very confusing.
Apparently, the addresses returned by the pool are expected to be contiguous somehow.
PagedAllocator does not do that (in fact, it returns the addresses in the opposite order).
I'm not sure where this property is used, or whether it is maybe a bug in the convex hull implementation (because it is still allocated in blocks, so it is not contiguous everywhere).
It also crashes, if all new_object() calls are replaced with a simple memnew, and the memory is never freed. (Leaking should not cause a crash.)

File: core/math/convex_hull.cpp [hunk 6]
```diff
@@ -0,0 +1,2360 @@
...
+	switch (n) {
+		case 0:
+			r_result.min_xy = nullptr;
+			r_result.max_xy = nullptr;
+			r_result.min_yx = nullptr;
+			r_result.max_yx = nullptr;
+			return;
+		case 2: {
+			Vertex *v = original_vertices[p_start];
+			Vertex *w = v + 1;
```
Comment (mortarroad) [inline core/math/convex_hull.cpp:1067]: This right here assumes contiguous memory.
Should be safe to replace with original_vertices[p_start+1]

**Comment by mortarroad** [comment]
PagedAllocator seems to have the same performance as Pool.
Both take around 75% of the time of memnew.

**Comment by mortarroad** [comment]
I also added an `allow_leak` flag to PagedAllocator, which does not error if not everything has been freed. This is not a problem if the type has no destructor, since all the memory is freed anyway.

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Good job on finding the issue with `PagedAllocator` and fixing it!

Could you make it a separate function `reset_no_check()` (or an argument in `reset()` with a default value) to skip the error, instead of an extra template parameter? It would make things a bit more flexible for other use cases.

This way the error can stay in the destructor, and it would be up to the convex hull process to call this reset function at the end. It can still throw an error if the condition `!_has_trivial_destructor(T)` is true.

File: core/paged_allocator.h [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+		}
+		p_mem->~T();
+		available_pool[allocs_available >> page_shift][allocs_available & page_mask] = p_mem;
+		if (thread_safe) {
+			spin_lock.unlock();
+		}
+		allocs_available++;
+	}
+
+	void reset(bool allow_unfreed = false) {
```
Comment (pouleyKetchoupp) [inline core/paged_allocator.h:94]: Missing `p_` prefix, apart from that it looks good! :)

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]

**Comment by pouleyKetchoupp** [comment]
Looks great! We just need a few last things to finalize this PR and finally merge it:

1. There's one recent patch from Bullet that would be interesting to apply to this implementation to avoid potential issues:
https://github.com/bulletphysics/bullet3/pull/3037
I've checked the git history and everything else seems to be mostly coding style and compilation fixes, so it should be ok with just this change.

2. Please add this extra bit to `COPYRIGHT.txt`:
```diff
diff --git a/COPYRIGHT.txt b/COPYRIGHT.txt
index f2e2a86c05..4a5baf756f 100644
--- a/COPYRIGHT.txt
+++ b/COPYRIGHT.txt
@@ -55,6 +55,14 @@ Comment: Godot Engine logo
 Copyright: 2017, Andrea Calabró
 License: CC-BY-4.0

+Files: ./core/math/convex_hull.cpp
+ ./core/math/convex_hull.h
+Comment: Bullet Continuous Collision Detection and Physics Library
+Copyright: 2011, Ole Kniemeyer, MAXON, www.maxon.net
+ 2007-2021, Juan Linietsky, Ariel Manzur.
+ 2014-2021, Godot Engine contributors.
+License: Expat and Zlib
+
 Files: ./modules/fbx/fbx_parser/
 Comment: Open Asset Import Library (FBX parser)
 Copyright: 2006-2020, assimp team
```

3. Then you can squash all your commits into one ([interactive rebase](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase)).

4. We need a separate PR for master to keep the two branches in sync. I can do it myself if needed, but porting the code should be straightforward.

**Comment by pouleyKetchoupp** [comment]
Also I realize I didn't add core team for review before, so adding just in case.

**Comment by mortarroad** [comment]
Squashed and rebased onto 3.x

File: core/math/convex_hull.cpp [hunk 8]
```diff
@@ -0,0 +1,2276 @@
...
+
+#include <string.h>
+
+#include "aabb.h"
+#include "convex_hull.h"
+
+#include "core/error_macros.h"
+#include "core/math/math_defs.h"
+#include "core/os/memory.h"
+#include "core/paged_allocator.h"
```
Comment (akien-mga) [inline core/math/convex_hull.cpp:53]: See https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html#header-includes
```suggestion
#include "convex_hull.h"

#include "core/error_macros.h"
#include "core/math/aabb.h"
#include "core/math/math_defs.h"
#include "core/os/memory.h"
#include "core/paged_allocator.h"

#include <string.h>
```

File: core/paged_allocator.h [hunk 9]
```diff
@@ -0,0 +1,133 @@
...
+/*************************************************************************/
+
+#ifndef PAGED_ALLOCATOR_H
+#define PAGED_ALLOCATOR_H
+
+#include <type_traits>
+
+#include "core/os/memory.h"
+#include "core/os/spin_lock.h"
+#include "core/typedefs.h"
```
Comment (akien-mga) [inline core/paged_allocator.h:38]:
```suggestion
#include "core/os/memory.h"
#include "core/os/spin_lock.h"
#include "core/typedefs.h"

#include <type_traits>
```

File: core/math/convex_hull.cpp [hunk 10]
```diff
@@ -0,0 +1,2276 @@
...
+/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,       */
+/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF    */
+/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.*/
+/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY  */
+/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  */
+/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE     */
+/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
+/*************************************************************************/
+
+/*
```
Comment (akien-mga) [inline core/math/convex_hull.cpp:31]: Maybe add a comment that links to the Bullet source used for this (ideally including the corresponding commit, so we can see if future upstream fixes need to be backported) and explaining how the implementation was adapted to Godot.

**Review by akien-mga — APPROVED** [review]
Looks good to me overall.

File: core/math/convex_hull.cpp [hunk 11]
```diff
@@ -0,0 +1,2288 @@
...
+ * Based on Godot's patched VHACD-version of Bullet's btConvexHullComputer.
+ * See /thirdparty/vhacd/btConvexHullComputer.cpp at 64403ddcab9f1dca2408f0a412a22d899708bbb1
+ * This does not correspond directly to any upstream bullet version, and must have branched off
+ * before 7e14e79da083b8f239a1e371d7db366387552646 in https://github.com/bulletphysics/bullet3
+ *
+ * Changes:
+ * - adapted to Godot's code style
+ * - replaced Bullet's types (e.g. vectors) with Godot's
+ * - replaced custom Pool implementation with PagedAllocator
+ */
```
Comment (pouleyKetchoupp) [inline core/math/convex_hull.cpp:41]: It looks like the VHACD version is not too different from the Bullet version (minor style changes, and `int` have been replaced to use `int32_t` consistently, from commit https://github.com/kmammou/v-hacd/commit/c53070fcec4e4df6bb09f1acb53f7af50f4458a3).

So to make it simple to track, an easy way could be to state that it's based on Bullet's `src/LinearMath/btConvexHullComputer.cpp` on commit 73b217fb07e7e3ce126caeb28ab3c9ddd0718467 and add two changes in the list:
```
- int32_t is consistently used instead of int in some cases
- Integrated patch db0d6c92927f5a1358b887f2645c11f3014f0e8a from Bullet (CWE-190 integer overflow in btConvexHullComputer)
```

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]

**Review by pouleyKetchoupp — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by lawnjelly** [comment]
I'm not sure if I've made a mistake in some tests I'm running, but the meshes generated by this seem to have windings in the opposite direction to the old Quickhull, i.e. facing towards the centre of the hull, instead of pointing outward (for backface culling). If so it would be easy enough to change. Can anyone confirm this?

**Comment by pouleyKetchoupp** [comment]
@lawnjelly Yes, I can confirm that generated faces have the same plane normals, but indices are inverted compared to the previous version. Good catch, thanks!
