### PR TITLE
TextEdit: Ensure caret is visible after paste

### LINKED ISSUE #115956: Script Editor not scrolling down on copy/paste
### Tested versions

- Reproducible in: 4.6.stable, 4.5.1.stable

### System information

Godot v4.6.stable - Ubuntu 24.04.3 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon 760M Graphics (radeonsi, phoenix, LLVM 20.1.2, DRM 3.57, 6.8.0-100-generic) - AMD Ryzen 5 7640U w/ Radeon 760M Graphics (12 threads) - 13.45 GiB memory

### Issue description

In the script editor, if you are on the bottom line, if you copy and paste the line, it does not scroll down to the new line.

I guess if possible, the cursor should always be forced on-screen.

### Steps to reproduce

- go to the bottom line of the script editor
- copy and paste the entire line (Ctrl + C, then Ctrl + V)
- cursor is now off-screen

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by nevido2042**
Ensure the viewport scrolls correctly after paste so the caret remains visible.

Repro: In the script editor, paste repeatedly near the end of the file and the caret can move out of view.

The adjustment is deferred to make sure scrollbars and layout are updated before repositioning the viewport.

Fixes #115956.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4501,10 +4501,18 @@ void TextEdit::copy(int p_caret) {
 }
 
 void TextEdit::paste(int p_caret) {
+	const int caret_to_adjust = (p_caret >= 0) ? p_caret : 0;
+
 	if (GDVIRTUAL_CALL(_paste, p_caret)) {
+		// Even if a script overrides paste, keep caret visible.
+		call_deferred(SNAME("adjust_viewport_to_caret"), caret_to_adjust);
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp]:
```suggestion
		callable_mp(this, &TextEdit::adjust_viewport_to_caret).call_deferred(caret_to_adjust);
```

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -4501,10 +4501,18 @@ void TextEdit::copy(int p_caret) {
...
 		return;
 	}
+
 	_paste_internal(p_caret);
+
+	// Defer to ensure scrollbars/layout are updated after the paste.
+	call_deferred(SNAME("adjust_viewport_to_caret"), caret_to_adjust);
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp]:
```suggestion
	callable_mp(this, &TextEdit::adjust_viewport_to_caret).call_deferred(caret_to_adjust);
```

File: scene/gui/text_edit.cpp (hunk 1 above)
Comment (AThousandShips) [reply scene/gui/text_edit.cpp]: You only applied one

File: scene/gui/text_edit.cpp [hunk 3]
```diff
@@ -4501,10 +4501,18 @@ void TextEdit::copy(int p_caret) {
...
 	if (GDVIRTUAL_CALL(_paste, p_caret)) {
+		// Even if a script overrides paste, keep caret visible.
+		callable_mp(this, &TextEdit::adjust_viewport_to_caret).call_deferred(caret_to_adjust);
 		return;
 	}
+
 	_paste_internal(p_caret);
+
+	// Defer to ensure scrollbars/layout are updated after the paste.
+	callable_mp(this, &TextEdit::adjust_viewport_to_caret).call_deferred(caret_to_adjust);
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: Instead of deferring, `_update_scrollbars` can just be called before it if needed.

Also this is only needed in the case of copy-pasting an entire line, and shouldn't be called in all cases after pasting. It can be moved inside the relevant condition in `_paste_internal`.

File: scene/gui/text_edit.cpp [hunk 4]
```diff
@@ -4501,10 +4501,18 @@ void TextEdit::copy(int p_caret) {
 }
 
 void TextEdit::paste(int p_caret) {
+	const int caret_to_adjust = (p_caret >= 0) ? p_caret : 0;
+
 	if (GDVIRTUAL_CALL(_paste, p_caret)) {
+		// Even if a script overrides paste, keep caret visible.
+		callable_mp(this, &TextEdit::adjust_viewport_to_caret).call_deferred(caret_to_adjust);
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: If a script overrides it, then it is responsible for adjusting the viewport to the caret . We shouldn't force it to adjust.

**Review by kitbdev — COMMENTED** [review]
Someone else claimed the issue, but it has been a week, so I guess its fine.

File: scene/gui/text_edit.cpp (hunk 4 above)
Comment (nevido2042) [reply scene/gui/text_edit.cpp]: thank you

File: scene/gui/text_edit.cpp (hunk 3 above)
Comment (nevido2042) [reply scene/gui/text_edit.cpp]: thank you

**Review by nevido2042 — COMMENTED** [review]
thank you

**Review by nevido2042 — COMMENTED** [review]
fix text

**Review by nevido2042 — COMMENTED** [review]
Fix formatting in text paste logic

File: scene/gui/text_edit.cpp [hunk 5]
```diff
@@ -4501,10 +4501,12 @@ void TextEdit::copy(int p_caret) {
 }
 
 void TextEdit::paste(int p_caret) {
+	const int caret_to_adjust = (p_caret >= 0) ? p_caret : 0;
+
 	if (GDVIRTUAL_CALL(_paste, p_caret)) {
+		_paste_internal(p_caret);
 		return;
 	}
-	_paste_internal(p_caret);
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp]: This change makes no sense, it now only performs internal paste processing when the method is overridden, have you tested this code and confirmed this works correctly?

**Review by kitbdev — APPROVED** [review]
Tested, fixes the issue.

File: scene/gui/text_edit.cpp [hunk 6]
```diff
@@ -4504,6 +4504,7 @@ void TextEdit::paste(int p_caret) {
 	if (GDVIRTUAL_CALL(_paste, p_caret)) {
 		return;
 	}
+
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp]:
```suggestion
```
Unrelated noise now that those changes were removed

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
