### PR TITLE
Fix Subviewport keeps using removed Camera3D child.

### LINKED ISSUE #92869: Subviewport keeps using Camera3D when the Camera3D is no longer its child
### Tested versions

4.3-beta1

### System information

Windows 10, Ryzen 3 3300x, 16gb RAM 2666mhz, GTX 1660 6gb.

### Issue description

My setup is:

- Main Scene
   - Subviewport
       - Camera3D

Moving the Camera3D to outside the Subviewport, still makes the Subviewport render the content of the Camera3D. 

Creating a new Camera3D in the MainScene doesn't change the Subvieport's Camera Target. The only way I found to change what the subviewport renders, is by creating a new Camera3D inside the Subviewport, so it finally updates. 

I don't know if this is intended, but it's confusing.

### Steps to reproduce

As explained in the description.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by EAinsley**
Fix #92869 

`_camera_3d_remove()` changed `camera_3d` directly instead of calling `_camera_3d_set()`, which failed to change the `camera` in `RendererViewport`. Now use `_camera_3d_set()` instead.

https://github.com/godotengine/godot/assets/63407648/9ec33f83-dd50-4229-a77f-40dce2ca323d

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -4252,7 +4252,7 @@ void Viewport::_camera_3d_remove(Camera3D *p_camera) {
 	camera_3d_set.erase(p_camera);
 	if (camera_3d == p_camera) {
 		camera_3d->notification(Camera3D::NOTIFICATION_LOST_CURRENT);
```
Comment (kleonc) [inline scene/main/viewport.cpp:4254]: `_camera_3d_set(nullptr);` also triggers such notification, remove this one to notify only once.
```suggestion
```

**Review by kleonc — CHANGES_REQUESTED** [review]

File: scene/main/viewport.cpp (hunk 1 above)
Comment (EAinsley) [reply scene/main/viewport.cpp]: Thank you for reviewing. Updated.

**Review by kleonc — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
