### PR TITLE
Try other resolved IPs if one fails to connect

### LINKED ISSUE #36418: Asset library doesn't load when using a dual stack IPv4/IPv6 network
**Godot version:**
3.2
**OS/device including version:**
Linux Mint Cinnamon 19.3
**Issue description:**
Get the message "Can't connect to host: https://godotengine.org/asset-library/api" 
**Steps to reproduce:**
Top middle choice "AssetLib"
**Minimal reproduction project:**
assetlib

### LINKED ISSUE #46972: Godot editor build doesn't connect to WebSocket server (client in HTML5 works)
**Godot version:**
3.2.3 stable

**OS/device including version:**
Windows GLES2

**Issue description:**
When I run godot project via editor it doesnt do anything related to websocket but when I export it to HTML5 and run it then same code can connect to websocket. What might the reason be?
PS: I am trying everything in same PC

**Steps to reproduce:**
Start a websocket server, code websocket client on godot, run in editor it does nothing

### PR DESCRIPTION
**Pull request by timothyqiu**
When `HTTPClient` and `WebSocketClient` are connecting to server, save all resolved IPs, and try other candidates if one failed to connect. Not [Happy Eyeballs](https://tools.ietf.org/html/rfc8305), but at least it's happy I think :)

Fixes #46972, and hopefully fixes #36418, I don't have IPv6 connection to the AssetLib, so I only tested on my `localhost` which resolved to IPv6 first.

It's the same for 3.x, but `core/io/http_client_tcp.{h,cpp}` → `core/io/http_client.{h,cpp}` and `container.is_empty()` → `container.empty()`.

### CODE REVIEW

File: core/io/http_client_tcp.cpp [hunk 1]
```diff
@@ -256,10 +259,17 @@ Error HTTPClientTCP::poll() {
 					return OK; // Still resolving
 
 				case IP::RESOLVER_STATUS_DONE: {
-					IPAddress host = IP::get_singleton()->get_resolve_item_address(resolving);
-					Error err = tcp_connection->connect_to_host(host, conn_port);
+					ip_candidates = IP::get_singleton()->get_resolve_item_addresses(resolving);
```
Comment (Faless) [inline core/io/http_client_tcp.cpp:262]: `ip_candidates` should also be cleared when reaching `STATUS_CONNECTED` (i.e. fully connected, including SSL handshake).

**Review by Faless — CHANGES_REQUESTED** [review]
See my comments about `ip_candidates` cleanup. Looks great otherwise :+1: :trophy:

**Review by Faless — APPROVED** [review]
Looks good, great job :trophy:

**Comment by Faless** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.4.
