### PR TITLE
Fix "Go to definition" for GDScript type hints

### LINKED ISSUE #68475: GDScript "Go to definition" doesn't work in certain cases within type hints
### Godot version

Godot 4.0 beta 4

### System information

Windows 10

### Issue description

Script editor allows you to "Go to definition" by simply using Ctrl + Left Click while hovering code. This works seamlessly throughout the editor except for a few cases, one of those cases is when wanting to do so for type hints of on a enum or inner class of a custom class.

As seen below, we're able to prompt a underline of a enum and inner class, and use "Go to definition", when hovering over it's usage within the value declaration:
image
image

However, when wanting to "Go to definition" for the same enum or inner class defined in the type hint it won't even prompt a underline much less work:
image
image
image
image

Clip demonstrating "Go to definition" working fine in various cases, but not working within the scope of type hint:

https://user-images.githubusercontent.com/17155529/201033836-9e2079b0-166b-43dc-a6c8-1fa6823aba0b.mp4

### Steps to reproduce

1. Open example project
2. Open custom_class_b.gd
3. Hover over ".CustomEnum" at the end of line 5
4. Press `Ctrl + Left Click`
5. No highlight and no going to definition will occur
6. Hover over ".CustomEnum" in the type hint of line 7
7. Press `Ctrl + Left Click`
8. No highlight and no going to definition will occur
9. Hover over ".CustomEnum" in the value declaration of line 7
10. Press `Ctrl + Left Click`
11. Highlighting and going to definition will occur
12. Hover over ".CustomInnerClass" at the end of line 10
13. Press `Ctrl + Left Click`
14. No highlight and no going to definition will occur
15. Hover over ".CustomInnerClass" in the type hint of line 12
16. Press `Ctrl + Left Click`
17. No highlight and no going to definition will occur
18. Hover over ".CustomInnerClass" in the value declaration of line 12
19. Press `Ctrl + Left Click`
20. Highlighting and going to definition will occur

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/9978631/example.zip)

### PR DESCRIPTION
**Pull request by BBBenG23**
This change is intended to fix issue #68475

Here is the project that I used to test my changes

[example.zip](https://github.com/godotengine/godot/files/10206109/example.zip)

_Production edit: Fixes https://github.com/godotengine/godot/issues/68475_

### CODE REVIEW

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -3456,6 +3456,30 @@ ::Error GDScriptLanguage::lookup_code(const String &p_code, const String &p_symb
 				return OK;
 			}
 		} break;
+		case GDScriptParser::COMPLETION_TYPE_ATTRIBUTE: {
+			const GDScriptParser::TypeNode *type = static_cast<const GDScriptParser::TypeNode *>(context.node);
+
+			const GDScriptParser::IdentifierNode *prev;
```
Comment (Chaosus) [inline modules/gdscript/gdscript_editor.cpp:3462]:
```suggestion
			const GDScriptParser::IdentifierNode *prev = nullptr;
```

Should be initialized to pass the CI tests.

**Comment by BBBenG23** [comment]
Building issue should be fixed

File: modules/gdscript/gdscript_editor.cpp [hunk 2]
```diff
@@ -3456,6 +3456,30 @@ ::Error GDScriptLanguage::lookup_code(const String &p_code, const String &p_symb
 				return OK;
 			}
 		} break;
+		case GDScriptParser::COMPLETION_TYPE_ATTRIBUTE: {
+			const GDScriptParser::TypeNode *type = static_cast<const GDScriptParser::TypeNode *>(context.node);
```
Comment (kleonc) [inline modules/gdscript/gdscript_editor.cpp:3460]: Is `type` guaranteed to be not null in here? If not, it needs to be ensured right after.

File: modules/gdscript/gdscript_editor.cpp [hunk 3]
```diff
@@ -3456,6 +3456,30 @@ ::Error GDScriptLanguage::lookup_code(const String &p_code, const String &p_symb
...
+
+			const GDScriptParser::IdentifierNode *prev = nullptr;
+			GDScriptParser::DataType base_type;
+			for (const GDScriptParser::IdentifierNode *E : type->type_chain) {
+				if (E->name == p_symbol) {
+					base_type = prev->get_datatype();
```
Comment (kleonc) [inline modules/gdscript/gdscript_editor.cpp:3466]: If this condition would be true on the first iteration then it would crash as `prev` would still be `nullptr`. Is it guaranteed to not happen? If not, needs to be handled properly.

File: modules/gdscript/gdscript_editor.cpp (hunk 2 above)
Comment (BBBenG23) [reply modules/gdscript/gdscript_editor.cpp:3463]: I added a check to be safe

File: modules/gdscript/gdscript_editor.cpp (hunk 3 above)
Comment (BBBenG23) [reply modules/gdscript/gdscript_editor.cpp]: I added a check to be safe

**Comment by adamscott** [comment]
@vnen What do you think of that PR? It seems fine to me.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
I pushed a rebase to get it to re-run CI checks, as the last build was more than 6 months ago. Also tweaked the commit message for clarity.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
