### PR TITLE
Fix EditorFileDialog icon scale in list mode

### LINKED ISSUE #115068: FileDialog file icons half size on highDPI monitor (4.6 regression)
### Tested versions

4.6rc1 issue not present in 4.5.1

### System information

macOS 15.7.3

### Issue description

The icons in the editor FileDialog files panel are not sized correctly for me in 4.6rc1:

Image

Looks like they're half size, which could indicate they're a fixed px size and not resized correctly on my 4k highDPI monitor (retina 2x scale). Note that in the recent list on the left however, the icons are the right size.

Comparison of file dialog in 4.5.1:
Image

### Steps to reproduce

Launch editor and open a FileDialog to select a file or save location

### Minimal reproduction project (MRP)

Just editor needed

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #115068

Although not sure why `theme_cache.file->get_size()` would return wrong size. The favorites/recent lists, that don't have the bug, don't have any scaling applied either, so I think the editor icons are pre-scaled based on editor scale, no?

### CODE REVIEW

File: editor/gui/editor_file_dialog.h [hunk 1]
```diff
@@ -46,6 +46,7 @@ class EditorFileDialog : public FileDialog {
 	virtual bool _should_use_native_popup() const override;
 	virtual bool _should_hide_file(const String &p_file) const override;
 	virtual Color _get_folder_color(const String &p_path) const override;
+	virtual Vector2i _get_list_mode_icon_size() const;
```
Comment (akien-mga) [inline editor/gui/editor_file_dialog.h]:
```suggestion
	virtual Vector2i _get_list_mode_icon_size() const override;
```

**Review by akien-mga — APPROVED** [review]
