### PR TITLE
Fix voxel GI issues

### LINKED ISSUE #69565: Vulkan: Volumetric Fog breaks when number of visible VoxelGI nodes changes
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Manjaro Linux, Forward+, RX 570 (Mesa 22.3.0-devel)

### Issue description

When the number of visible VoxelGI nodes changes (through occlusion culling, changing visibility, or baking a fresh VoxelGI), Volumetric Fog breaks, with the froxel buffer appearing to freeze.
Toggling Volumetric Fog off and back on again will fix it until the aforementioned case breaks it again.

<details>
<summary>The outputs gets flooded with a massive error while the bug is occurring. Click to expand.</summary>

```
Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
drivers/vulkan/rendering_device_vulkan.cpp:8292 - Condition "!uniform_set" is true.
Uniforms supplied for set (0):
Set: 0 Binding: 1 Type: Texture Writable: N Length: 1
Set: 0 Binding: 2 Type: Texture Writable: N Length: 1
Set: 0 Binding: 3 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 4 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 5 Type: UniformBuffer Writable: N Length: 3712
Set: 0 Binding: 6 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 7 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 8 Type: Image Writable: Y Length: 1
Set: 0 Binding: 9 Type: Image Writable: Y Length: 1
Set: 0 Binding: 10 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 11 Type: UniformBuffer Writable: N Length: 896
Set: 0 Binding: 12 Type: Texture Writable: N Length: 8
Set: 0 Binding: 13 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 14 Type: UniformBuffer Writable: N Length: 304
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 1 Type: Texture Writable: N Length: 1
Set: 0 Binding: 2 Type: Texture Writable: N Length: 1
Set: 0 Binding: 3 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 4 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 5 Type: UniformBuffer Writable: N Length: 3712
Set: 0 Binding: 6 Type: StorageBuffer Writable: N Length: 0
Set: 0 Binding: 7 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 8 Type: Image Writable: Y Length: 1
Set: 0 Binding: 9 Type: Image Writable: Y Length: 1
Set: 0 Binding: 10 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 11 Type: UniformBuffer Writable: N Length: 896
Set: 0 Binding: 12 Type: Texture Writable: N Length: 8
Set: 0 Binding: 13 Type: Sampler Writable: N Length: 1
Set: 0 Binding: 14 Type: UniformBuffer Writable: N Length: 304
Set: 0 Binding: 15 Type: Texture Writable: N Length: 1
Set: 0 Binding: 16 Type: Image Writable: Y Length: 1
Set: 0 Binding: 17 Type: Image Writable: Y Length: 1
Set: 0 Binding: 18 Type: Image Writable: Y Length: 1
Set: 0 Binding: 19 Type: Texture Writable: N Length: 1
drivers/vulkan/rendering_device_vulkan.cpp:8292 - Condition "!uniform_set" is true.
Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
drivers/vulkan/rendering_device_vulkan.cpp:8292 - Condition "!uniform_set" is true.
Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
```
</details>

Video of the MRP below -- the box to the right represents the VoxelGI node.

https://user-images.githubusercontent.com/71602778/205486666-c10b42a0-5849-4cf3-a863-426074dd1a99.mp4

### Steps to reproduce

MRP:
1. Download and run. Click drag to rotate the camera around, and hit Space/Right Click to toggle the fog.
2. Rotate camera such that the cube either goes out of view, or goes into view. Observe volumetric fog not working anymore.
3. Toggle the fog off and back on to fix it, and test again if desired.

Manual:
1. Create a new scene, add a WorldEnvironment node and enable Volumetric Fog.
2. Add a FogVolume, or an intense light source to get a clear point of reference.
4. Add a VoxelGI node to the scene. Bake it so that it becomes active.
5. The volumetric fog will immediately break. Repair it by toggling it off and back on in the Environment
6. Either toggle the VoxelGI's visibility, or move the camera around in-editor so that the VoxelGI volume either goes out of, or into view. Observe volumetric fog breaking in these cases. Repair it the same way as step 4 to test it again.

### Minimal reproduction project

[Volumetric Fog+VoxelGI Test.zip](https://github.com/godotengine/godot/files/10148294/Volumetric.Fog%2BVoxelGI.Test.zip)

### LINKED ISSUE #76243: Vulkan: Volumetric fog glitches out in builds that use `optimize=none`, but not other optimization levels
### Godot version

4.0.2.stable (compiled from source)

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 530.41.03)

### Issue description

Volumetric fog glitches out with NaN/INF values depending on the compiler optimization level:

Glow disabled | Glow enabled
-|-
Screenshot_20230419_040319 webp | Screenshot_20230419_040324 webp

This occurs regardless of whether SDFGI or VoxelGI or any other effects (glow, SSR, SSAO, SSIL) is used.

- `optimize=speed`, `optimize=speed_trace`, `optimize=debug` and `optimize=size` work as expected.
- `optimize=none` causes the glitch.

I'm using GCC 12.2.1 from the Fedora 37 repositories.

**Edit:** I've tried reproducing this again with `optimize=none` and can't reproduce this anymore, even if I clean all SCons files and rebuild. However, when I could reproduce the issue, I could always reproduce it with a binary using `optimize=none` and never with a binary using `optimize=speed`.

### Steps to reproduce

- Use a self-compiled build on Linux with `optimize=none` (GCC, not tested with Clang).
- Open the Reflection project linked below in the editor and move the 3D camera around. Fog will eventually glitch out.

### Minimal reproduction project

I haven't managed to reproduce this issue in a minimal project so far, only in https://github.com/Calinou/godot-reflection.

### PR DESCRIPTION
**Pull request by RandomShaper**
**UPDATE:** To avoid multiple 'update' notices throughout, just know that the full text has been revised after enhancing the fixes.

---

Changes kept in two commits because, even if related, they address different issues:

- Commit 1: _Fix breakages of volumetric fog on voxel GI changes_

   Fixes the book-keeping of related uniforms. Without this change, some of them could fail to be created when needed and some others could be pointing to outdated voxel GI buffers. For the uniform sets related to GI instances, a minor sets group idiom is introduced, that helps tracking validity and saves some checks, while also assisting developers in detecting bugs.

   Fixes #69565.
   Fixes #76243.

- Commit 2: _Fix unsupported sampler filter used for voxel GI_

   Fixes a validation error* about an R8G8 texture being sampled linearly when the driver reports no support for that.
   
*:
```
drivers\vulkan\vulkan_context.cpp:267 - VALIDATION - Message Id Number: 188609398 | Message Id Name: VUID-vkCmdDispatch-magFilter-04553
Validation Error: [ VUID-vkCmdDispatch-magFilter-04553 ] Object 0: handle = 0x8f7057000000562c, name = RID:505478996034037, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 1: handle = 0xa182620000000079, name = RID:163208757251, type = VK_OBJECT_TYPE_SAMPLER; Object 2: handle = 0xf325e500000055e3, name = RenderBuffer forward_clustered/voxel_gi View, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0xb3df376 | Descriptor set VkDescriptorSet 0x8f7057000000562c[RID:505478996034037] encountered the following validation error at vkCmdDispatch time: Sampler (VkSampler 0xa182620000000079[RID:163208757251]) is set to use VK_FILTER_LINEAR with compareEnable is set to VK_FALSE, but image view's (VkImageView 0xf325e500000055e3[RenderBuffer forward_clustered/voxel_gi View]) format (VK_FORMAT_R8G8_UINT) does not contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT in its format features. The Vulkan spec states: If a VkSampler created with magFilter or minFilter equal to VK_FILTER_LINEAR and compareEnable equal to VK_FALSE is used to sample a VkImageView as a result of this command, then the image view's format features must contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDispatch-magFilter-04553)
	Objects - 3
		Object[0] - VK_OBJECT_TYPE_DESCRIPTOR_SET, Handle -8110887271382624724, Name "RID:505478996034037"
		Object[1] - VK_OBJECT_TYPE_SAMPLER, Handle -6808771934491246471, Name "RID:163208757251"
		Object[2] - VK_OBJECT_TYPE_IMAGE_VIEW, Handle -926082360191986205, Name "RenderBuffer forward_clustered/voxel_gi View"
   ```

### CODE REVIEW

File: servers/rendering/renderer_rd/environment/gi.cpp [hunk 1]
```diff
@@ -3493,6 +3493,9 @@ void GI::init(SkyRD *p_sky) {
 		if (RendererSceneRenderRD::get_singleton()->is_vrs_supported()) {
 			defines += "\n#define USE_VRS\n";
 		}
+		if (!RD::get_singleton()->sampler_is_format_supported_for_filter(RD::DATA_FORMAT_R8G8_UINT, RD::SAMPLER_FILTER_LINEAR)) {
```
Comment (RandomShaper) [inline servers/rendering/renderer_rd/environment/gi.cpp:3496]: Specifying the format here feels too hard-coded to my taste, but I couldn't find a way of querying the format of the actual texture. This is not the end of the world, but has a risk of getting out of sync with the code that creates the texture.

File: servers/rendering/renderer_rd/shaders/environment/gi.glsl [hunk 2]
```diff
@@ -625,7 +626,11 @@ void process_gi(ivec2 pos, vec3 vertex, inout vec4 ambient_light, inout vec4 ref
 
 #ifdef USE_VOXEL_GI_INSTANCES
 		{
+#ifdef SAMPLE_VOXEL_GI_NEAREST
+			uvec2 voxel_gi_tex = texelFetch(usampler2D(voxel_gi_buffer, nearest_sampler), pos, 0).rg;
+#else
 			uvec2 voxel_gi_tex = texelFetch(usampler2D(voxel_gi_buffer, linear_sampler), pos, 0).rg;
```
Comment (sakrel) [inline servers/rendering/renderer_rd/shaders/environment/gi.glsl:632]: It's strange that this is causing validation errors. I was under the impression that `texelFetch` is supposed to ignore the sampler and the only reason you need to pass a sampler to `texelFetch` is that OpenGL only supported combined image samplers. 

Looking at the SPIR-V spec, `OpImageFetch` only requires an image of type `OpTypeImage` and not a sampled image of type `OpTypeSampledImage`.

**Comment by Calinou** [comment]
> Fixes a validation error about an R8G8 texture being sampled linearly when the drivers reports no support for that. Besides the validation error, without the appropriate fallback to nearest, when looking at the scene from certain angles, the volumetric fog starts flooding the whole viewport with white in a few frames and there's no way back other than resizing the viewport.

Does this fix https://github.com/godotengine/godot/issues/76243? I thought it was due to compiler optimization levels but that may have been a fluke.

**Comment by RandomShaper** [comment]
> Does this fix #76243? I thought it was due to compiler optimization levels but that may have been a fluke.

Oh, that's exactly what one of the commits addresses! Not completely sure if its the same root cause or it's instead a different bug that looks like the same. I'm being optimistic and choosing to believe it's the same, and so updating the PR description.

File: servers/rendering/renderer_rd/shaders/environment/gi.glsl (hunk 2 above)
Comment (sakrel) [reply servers/rendering/renderer_rd/shaders/environment/gi.glsl:632]: Looks like glslang generates really silly code for the `texelFetch` call:
```
         %13 = OpLoad %10 %voxel_gi_buffer
         %17 = OpLoad %14 %linear_sampler
         %19 = OpSampledImage %18 %13 %17
         %24 = OpImage %10 %19
         %26 = OpImageFetch %v4uint %24 %23 Lod %int_0
```
https://shader-playground.timjones.io/d63b2e6271a1ed699b18f59c3a995b01

Instead of passing the image directly to `OpImageFetch`, the code first creates a sampled image via `OpSampledImage` and then extracts the image from the sampled image via `OpImage` and then passes the result of `OpImage` to `OpImageFetch`

There appears to be a gslang extension that makes it possible to to use `texelFetch` without a sampler: [GL_EXT_samplerless_texture_functions](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_samplerless_texture_functions.txt)

Comment (RandomShaper) [reply servers/rendering/renderer_rd/shaders/environment/gi.glsl:632]: Very interesting.

I've updated the code to leverage that extension in the case where not linear filtering is supported. I'm kind of assuming it's always supported.

**Comment by RandomShaper** [comment]
I think I've found the glitched fog issue! Will finish updating the PR tomorrow. Tagging as _Needs work_.

File: servers/rendering/renderer_rd/environment/gi.cpp [hunk 3]
```diff
@@ -3695,14 +3698,16 @@ void GI::setup_voxel_gi_instances(RenderDataRD *p_render_data, Ref<RenderSceneBu
 		if (p_render_buffers->has_custom_data(RB_SCOPE_FOG)) {
```
Comment (RandomShaper) [inline servers/rendering/renderer_rd/environment/gi.cpp:3698]: I think these checks would belong better to just before using the uniform sets. They will be invalid by that time because of deletion of dependencies, so doing the check there is to me more correct. The idea would be being reactive to what actually happened instead of being proactive in guessing what may have happened. That, of course, without detriment of being proactive as an optimization in cases where that can save some checks (a bit like this PR does by assuming the whole group of sets is either valid or invalid).

In any case, this is a suggestion to the rendering maintainers. I didn't want to attempt something like that in this PR, which would broaden its scope needlessly.

[the remark this answers is not in the document]
Comment (clayjohn) [reply servers/rendering/renderer_rd/environment/gi.cpp:3698]: That makes sense. There isn't much of a reason to be caching this so early

**Comment by RandomShaper** [comment]
For the records, I've still seen the floody fog glitch once even with this changes, in the D3D12 renderer. But I believe this PR fixes it like 99% since without it I've been able to reproduce the issue consistently if I force `voxel_instances_changed = true` always.

File: doc/classes/RenderingDevice.xml [hunk 4]
```diff
@@ -452,6 +452,13 @@
 			<description>
 			</description>
 		</method>
+		<method name="sampler_is_format_supported_for_filter" qualifiers="const">
+			<return type="bool" />
+			<param index="0" name="format" type="int" enum="RenderingDevice.DataFormat" />
+			<param index="1" name="sampler_filter" type="int" enum="RenderingDevice.SamplerFilter" />
+			<description>
+			</description>
```
Comment (clayjohn) [inline doc/classes/RenderingDevice.xml:460]:
```suggestion
			<description>
				Returns [code]true[/code] if implementation supports using a texture of [param format] with the given [param sampler_filter].
			</description>
```

**Review by clayjohn — APPROVED** [review]
This looks good as a minimalistic approach to fixing the issues. Indeed clearing those uniform sets should be moved out of the gi_setup code as it creates a weird dependency between the two classes.

File: doc/classes/RenderingDevice.xml (hunk 4 above)
Comment (RandomShaper) [reply doc/classes/RenderingDevice.xml:460]: Applied!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.
