### PR TITLE
Enhance tree scrolling when dragging

### LINKED ISSUE #23375: File system dock scroll itself when I drag the file
**Godot version:**
3.1 aeddb30

**OS/device including version:**
Windows 10

**Issue description:**
When I try to drag and drop file to 2d viewport then  filesystem dock scroll itself when I with dragged object are above this panel. This is very frustrating because I must again and again scroll down 

**Steps to reproduce:**
https://streamable.com/1lqd3

### PR DESCRIPTION
**Pull request by groud**
Fixes #23375

This is a compatibility breaking change, since it modifies how the Tree node handles auto-scrolling.
The Tree will now auto scroll when dragging only if the mouse is close to the border of the Control node.

### CODE REVIEW

**Comment by thloh85** [comment]
+1

**Comment by Chaosus** [comment]
Its very irritating thing, I hope this will be merged soon to fix it

File: editor/editor_themes.cpp [hunk 1]
```diff
@@ -677,7 +677,7 @@ Ref<Theme> create_editor_theme(const Ref<Theme> p_theme) {
 	theme->set_constant("item_margin", "Tree", 3 * default_margin_size * EDSCALE);
 	theme->set_constant("button_margin", "Tree", default_margin_size * EDSCALE);
 	theme->set_constant("draw_relationship_lines", "Tree", 0);
-	theme->set_constant("scroll_border", "Tree", default_margin_size * EDSCALE);
+	theme->set_constant("scroll_border", "Tree", 40);
```
Comment (Calinou) [inline editor/editor_themes.cpp]: Is the removal of `EDSCALE` intentional here? The dragging margin should be independent of the editor scale.

Comment (groud) [reply editor/editor_themes.cpp]: Lol, I don't remember. I guess so but I might have made a mistake I am not sure.
I'll check when rebasing.

Comment (akien-mga) [reply editor/editor_themes.cpp]: Rebase still pending :)

Comment (groud) [reply editor/editor_themes.cpp]: Done

**Comment by akien-mga** [comment]
Thanks!

**Comment by Xrayez** [comment]
> This is a compatibility breaking change, since it modifies how the Tree node handles auto-scrolling.

Shouldn't be considered for cherrypicking then?

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.
