### PR TITLE
Fix TreeItem icon overflows column boundary

### LINKED ISSUE #112804: Treeitem icon overflows column boundary
### Tested versions

v4.5.stable.mono.official [876b29033]

### System information

Windows11

### Issue description

If the icon is big, and the column is narrow, the icon overflows column boundary.

Image

### Steps to reproduce

Open MRP and follow GIF. 

### Minimal reproduction project (MRP)

[tree_icon_test.zip](https://github.com/user-attachments/files/23559980/tree_icon_test.zip)

### PR DESCRIPTION
**Pull request by BrotherShort**
Fix #112804.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -2081,7 +2081,16 @@ void Tree::draw_item_rect(const TreeItem::Cell &p_cell, const Rect2i &p_rect, co
 
 	int displayed_width = 0;
 	if (p_cell.icon.is_valid()) {
-		displayed_width += icon_size.width + theme_cache.h_separation;
+		if (displayed_width + icon_size.width > rect.size.width) {
+			displayed_width = rect.size.width;
+		} else {
+			displayed_width += icon_size.width;
+		}
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: Can be simplified to

```suggestion
		displayed_width = MIN(displayed_width + icon_size.width , rect.size.width);
```

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/tree.cpp (hunk 1 above)
Comment (BrotherShort) [reply scene/gui/tree.cpp]: Have been simplified.

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -2081,11 +2081,9 @@ void Tree::draw_item_rect(const TreeItem::Cell &p_cell, const Rect2i &p_rect, co
 
 	int displayed_width = 0;
 	if (p_cell.icon.is_valid()) {
-		displayed_width += icon_size.width + theme_cache.h_separation;
-	}
-	if (displayed_width + ts.width > rect.size.width) {
-		ts.width = rect.size.width - displayed_width;
+		displayed_width = MIN(displayed_width + icon_size.width + theme_cache.h_separation, rect.size.width);
 	}
+	ts.width = MIN(ts.width, rect.size.width - displayed_width);
```
Comment (akien-mga) [inline scene/gui/tree.cpp]: This doesn't seem to be equivalent to the previous code.

Comment (BrotherShort) [reply scene/gui/tree.cpp]: Changed back.

**Comment by Repiteo** [comment]
Thanks!
