### PR TITLE
Use getter return type for the property type

### LINKED ISSUE #42280: GDScript: error when assigning Material to any property of type Material derived from GeometryInstance3D
**Godot version:**
4.0 master - 80399781100796ea62184a2a908fc7fe23b27303

**Issue description:**
When assigning a Material, such as Material, StandardMaterial3D, BaseMaterial3D, ShaderMaterial, to a property of type Material, such as GeometryInstance3D's 'material_override', GPUParticles3D's 'process_material', it will throw an error similar to:
Cannot assign a value of type "StandardMaterial3D" to a target of type  "ShaderMaterial,StandardMaterial3D"

The console will also output something like "Cannot get class 'ShaderMaterial,StandardMaterial3D'."

**Steps to reproduce:**
```
func test():
	var mat: StandardMaterial3D = StandardMaterial3D.new() # Material, BaseMaterial3D, ShaderMaterial - also error
	var mesh : MeshInstance3D = MeshInstance3D.new() # GeometryInstance3D, GPUParticles3D - also error
	mesh.material_override = mat # Error here
```

Pics:

### PR DESCRIPTION
**Pull request by vnen**
The PropertyInfo hints are more relevant for the inspector. The getter return type is more reliable and less likely to be incorrect and it is what's going to be called in the end.

Fix #42280

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2597,10 +2597,13 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
...
 	if (class_exists(native)) {
-		PropertyInfo prop_info;
 		MethodInfo method_info;
-		if (ClassDB::get_property_info(native, name, &prop_info)) {
-			p_identifier->set_datatype(type_from_property(prop_info));
+		if (ClassDB::has_property(native, name)) {
+			StringName getter_name = ClassDB::get_property_getter(native, name);
+			MethodBind *getter = ClassDB::get_method(native, getter_name);
+			if (getter != nullptr) {
+				p_identifier->set_datatype(type_from_property(getter->get_return_info()));
```
Comment (akien-mga) [inline modules/gdscript/gdscript_analyzer.cpp:2605]: `get_return_info()` is only enabled with `DEBUG_METHODS_ENABLED`, so this doesn't compile for all platforms/targets.

Comment (vnen) [reply modules/gdscript/gdscript_analyzer.cpp:2605]: It just occurred to me that we need to enable some of those things on release builds too. Otherwise typed GDScript won't be working correctly and will miss a bunch of optimizations.

**Review by akien-mga — APPROVED** [review]
