### PR TITLE
[macOS] Fix mouse position in captured mode.

### LINKED ISSUE #42321: Captured mouse mode fails to capture mouse if it's outside the window on OSX
**Godot version:**
3.2.3-stable

**OS/device including version:**

GPU:  **Intel Iris Pro OpenGL Engine**
MacBookPro11,4
Quad-Core Intel Core i7
Intel Iris Pro VENDOR=0x80867 DEVICE=0x0d26
Mac OS X 10.15.6

**Issue description:**

This doesn't seem to work if the mouse cursor is over the dock when the mode is switched.

This is the code that I'm using to switch mouse modes:

```Python
func _set_active(value):
	active = value
	if $PlayerHead/Camera and value:
		$PlayerHead/Camera.current = value
	if value:
		var w: Node = world_mgr
		if w && w.has_method('get_arg'):
			if !w.get_arg('no-capture-mouse'):
				Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	else:
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		velocity = Vector3()
```

**Steps to reproduce:**

Download https://github.com/godotengine/godot-demo-projects/tree/d4bf89d3647097443bc4f3f8625d7564a1e80a01/3d/voxel
(or the attached .zip)
Open the project and run.
Click `Start Game` > `Flat Grass` and then press `esc` to open the menu and uncapture the mouse.
move the mouse down to the dock, and press `esc` again to re-capture the mouse.
Moving the mouse around and pressing arrow keys will still interact with the game, but when you click, it will click on the dock, because _mouse button_ input is not captured?

See these video examples: https://streamable.com/y87gbv https://streamable.com/6i7fd9

**Minimal reproduction project:**

[voxel.zip](https://github.com/godotengine/godot/files/5279290/voxel.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Move mouse cursor to the center of main window when switching to captured mode (similar to Linux and Windows behavior).

Fixes: #42321

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: platform/osx/display_server_osx.mm [hunk 1]
```diff
@@ -2041,6 +2041,12 @@ - (BOOL)canBecomeMainWindow {
 			CGDisplayHideCursor(kCGDirectMainDisplay);
 		}
 		CGAssociateMouseAndMouseCursorPosition(false);
+		WindowData &wd = windows[MAIN_WINDOW_ID];
+		const NSRect contentRect = [wd.window_view frame];
+		NSRect pointInWindowRect = NSMakeRect(contentRect.size.width / 2, contentRect.size.height / 2, 0, 0);
+		NSPoint pointOnScreen = [[wd.window_view window] convertRectToScreen:pointInWindowRect].origin;
+		CGPoint lMouseWarpPos = { pointOnScreen.x, CGDisplayBounds(CGMainDisplayID()).size.height - pointOnScreen.y };
```
Comment (jamie-pate) [inline platform/osx/display_server_osx.mm:2048]: Is it not possible to stack displays vertically in Marcos?

Comment (jamie-pate) [reply platform/osx/display_server_osx.mm:2048]: Or am I misinterpreting the reason behind this code

Comment (bruvzg) [reply platform/osx/display_server_osx.mm:2048]: It's possible to arrange displays vertically, but it does not matter. This code is needed to convert coordinates to global space (which is relative to the upper-left corner of the main display).

Comment (bruvzg) [reply platform/osx/display_server_osx.mm:2048]: I have checked it with vertically aligned displays just to be sure, it works fine.

**Comment by aaronfranke** [comment]
What about the case of setting the mouse position when tabbing out and in?
