### PR TITLE
Avoid `FlowContainer` crash with `TextureRect` using `EXPAND_FIT_*` expand modes

### LINKED ISSUE #93767: Changing Label in FlowContainer with TextureRect will cause crash
### Tested versions

Reproducible in: v4.2.1stable[b09f793f5]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 31.0.101.2125) - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 Threads)

### Issue description

Using a Label in FlowContainer with changed constants will cause a crash in your Godot.

### Steps to reproduce

- Create new scene
- Add FlowContainer and set 'minimum size' to X100, Y0
- Add TextureRect and add any image, and set 'fit width proportional'
- Add Label (and write something)

- Go to 'constants' in FlowContainer editor
- Set Hseparation 15 and Vseparation 5

2 ways now:

- Back to Label and change 'custom minimum size' X in 'layout' to X75 
- Or, back to FlowContainer node and change 'custom minimum size' in 'layout' (both X, Y)

Wait and it will close (but if it doesn't close, change the FlowContainer or Label again)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aaronp64**
When a `FlowContainer` had a `TextureRect` child using any of the EXPAND_FIT_* expand modes, it could crash when changing the `FlowContainer`'s minimum size, or that of its children.  This was due to the `TextureRect` resizing in `FlowContainer::_resort`, updating its minimum size, and triggering another `_resort`.  If the `TextureRect`'s minimum size changed in a way that caused any of the `FlowContainer`'s children to be put on a different line, it could repeatedly cause `_resort` to be called again, moving the children back and forth between the old and new lines.

This change is for `FlowContainer::_resort` to give a warning for `TextureRect`s with EXPAND_FIT_* expand modes when multiple lines are used, and just keep the `TextureRect` size the same in that case.  This is similar to the check added to `AspectRatioContainer` in https://github.com/godotengine/godot/pull/73396, but attempting to still support it in `FlowContainer` when possible.  In the case where the `TextureRect` is forced to stay the same size, there may be some overlap between the `FlowContainer`'s children, but should no longer crash.

Fixes #93767

### CODE REVIEW

File: scene/gui/flow_container.cpp [hunk 1]
```diff
@@ -203,7 +204,21 @@ void FlowContainer::_resort() {
...
+		TextureRect *trect = Object::cast_to<TextureRect>(child);
+		if (trect) {
+			TextureRect::ExpandMode mode = trect->get_expand_mode();
+			if (mode == TextureRect::EXPAND_FIT_WIDTH || mode == TextureRect::EXPAND_FIT_WIDTH_PROPORTIONAL ||
+					mode == TextureRect::EXPAND_FIT_HEIGHT || mode == TextureRect::EXPAND_FIT_HEIGHT_PROPORTIONAL) {
+				is_unsupported_texture_rect = true;
+			}
+		}
+
+		if (is_unsupported_texture_rect && lines_data.size() > 1) {
```
Comment (KoBeWi) [inline scene/gui/flow_container.cpp:217]: `lines_data.size() > 1` can be done before checking TextureRect; there is no reason to check the class and expand mode if it's known to be irrelevant.

Comment (aaronp64) [reply scene/gui/flow_container.cpp]: Updated to do size check first

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
