### PR TITLE
[Windows] Override key codes with Unicode values for OEM keys only.

### LINKED ISSUE #101701: [4.4-beta.1] Editor reads keyboard inputs incorrectly when using uncommon Keyboard Layout BÉPO
### Tested versions

- Reproducible in : 4.4.beta1
- Not Reproducible in : 4.3.stable

### System information

Godot v4.4.beta1 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 32.0.15.6603) - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 threads)

### Issue description

I use a uncommon keyboard layout on Windows called BÉPO [bepo-1.1rc2-full-azerty.exe](https://cdn.bepo.fr/windows/1.1rc2/bepo-1.1rc2-full-azerty.exe) that emulates shortcuts from the AZERTY layout, like Ctrl+S, Ctrl+C, Ctrl+V, etc.
My shortcuts now don't work anymore, which means I can't copy, paste, or save in the script editor using the correct shortcuts I use everywhere else and those shortcuts aren't editable so I can't rebind them.

Godot seems to have changed the way it reads input from Physical position to the letter that would give this position.
If I try to record the Save shortcut (Ctrl+S) on Godot4.3, it reads : 
"Ctrl+S or Ctrl+S (Physical) or Ctrl+U (Unicode)"
If I try the same on Godot4.4, it reads :
"**Ctrl+U** or Ctrl+S (Physical) or Ctrl+U (Unicode)"

### Steps to reproduce

Install AZERTY layout
Install the BÉPO layout [bepo-1.1rc2-full-azerty.exe](https://cdn.bepo.fr/windows/1.1rc2/bepo-1.1rc2-full-azerty.exe) (the one using AZERTY shortcuts)
Open Godot4.4 and navigate towards Editor > Editor Settings > Shortcuts
Try to bind shortcuts that use the Ctrl key in both layouts
Notice it's not the same (when it's the same in Godot4.3)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Should fix https://github.com/godotengine/godot/issues/101701 and still correctly process OEM keys (https://github.com/godotengine/godot/pull/100960).

I was not able to fully test it since layouts from https://bepo.fr seems to be non-functional (crash explorer when you try to switch layout) and do not have physical JP106 keyboard.

### CODE REVIEW

**Comment by buresu** [comment]
@bruvzg Testing with  jp106 keyboard showed no issues.
With the BÉPO keyboard layout, since the 'U' key is located in the position of the physical 'S' key, it seems natural that the 'U' key would be input. However, I'm not familiar with French keyboards, so I support this PR.
https://en.wikipedia.org/wiki/B%C3%89PO

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -5851,7 +5853,7 @@ void DisplayServerWindows::_process_key_events() {
 						if (!keysym.is_empty()) {
 							char32_t unicode_value = keysym[0];
 							// For printable ASCII characters (0x20-0x7E), override the original keycode with the character value.
-							if (Key::SPACE <= (Key)unicode_value && (Key)unicode_value <= Key::ASCIITILDE) {
+							if (is_oem && Key::SPACE <= (Key)unicode_value && (Key)unicode_value <= Key::ASCIITILDE) {
```
Comment (buresu) [inline platform/windows/display_server_windows.cpp:5856]: Since it's already restricted to OEM keys, I think ASCII range restriction may not be necessary.

**Comment by bruvzg** [comment]
> With the BÉPO keyboard layout, since the 'U' key is located in the position of the physical 'S' key, it seems natural that the 'U' key would be input. However, I'm not familiar with French keyboards, so I support this PR.

This is not for regular BEPO, but for a special layout variant with physical 'S' key inputting `U` as text but `S` if `Ctrl` is pressed.

File: platform/windows/display_server_windows.cpp (hunk 1 above)
Comment (bruvzg) [reply platform/windows/display_server_windows.cpp:5856]: Unlikely it will be ever outside this range, but there's no exact list of the valid values OEM keys can produce, and `keycode` still expected to be limited to 102-key US QWERTY keyboard values.

**Comment by buresu** [comment]
@bruvzg Thank you. I understand now.
The user is using a BÉPO physical keyboard, where normal input produces a 'U' key, but when pressed with Ctrl, the OS reports it as an 'S' key.
The problem occurs when this is overwritten by the Unicode value 'U' that was reported.

File: platform/windows/display_server_windows.cpp (hunk 1 above)
Comment (buresu) [reply platform/windows/display_server_windows.cpp:5856]: Sure I think it would be better to keep the ASCII range restriction for safety.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by RedSPINE** [comment]
Thank you very much it saves my life !
