### PR TITLE
Set `icon_max_width` in the ConnectionsDock tree

### LINKED ISSUE #83405: [4.2.beta1] Registering custom signals on custom node displays icon of original size in the category tab
### Godot version

4.2.beta1.mono

### System information

Godot v4.2.beta1.mono - Nobara Linux 38 (Thirty Eight) - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 Ti (nvidia; 535.104.05) - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

Godot displays comically large icon (which seems to be original size) next to the category name when exposing custom signals:
image

This does not happen on exported properties.

### Steps to reproduce

Made a plugin that adds custom node like this:
image

### Minimal reproduction project

It seems trivial, but I can provide my current project if others fail to reproduce it

### PR DESCRIPTION
**Pull request by raulsntos**
- Follow-up to https://github.com/godotengine/godot/pull/75472.
- Fixes https://github.com/godotengine/godot/issues/83405.

### CODE REVIEW

File: editor/connections_dialog.cpp [hunk 1]
```diff
@@ -1279,6 +1279,8 @@ void ConnectionsDock::_notification(int p_what) {
 			slot_menu->set_item_icon(slot_menu->get_item_index(SLOT_MENU_EDIT), get_editor_theme_icon(SNAME("Edit")));
 			slot_menu->set_item_icon(slot_menu->get_item_index(SLOT_MENU_GO_TO_METHOD), get_editor_theme_icon(SNAME("ArrowRight")));
 			slot_menu->set_item_icon(slot_menu->get_item_index(SLOT_MENU_DISCONNECT), get_editor_theme_icon(SNAME("Unlinked")));
+
+			tree->add_theme_constant_override("icon_max_width", get_theme_constant(SNAME("class_icon_size"), SNAME("Editor")));
```
Comment (KoBeWi) [inline editor/connections_dialog.cpp:1283]:
```suggestion
			tree->add_theme_constant_override("icon_max_width", get_theme_constant(SNAME("class_icon_size"), EditorStringName(Editor)));
```

**Review by akien-mga — APPROVED** [review]
