### PR TITLE
Fix Vulkan Instance initialized twice in ProjectDialog

### LINKED ISSUE #96722: Crash in Project Dialog on Windows - Vulkan
### Tested versions

4.4 custom build at revision 5675c76

### System information

Windows 10 - Vulkan

### Issue description

Editor crashes when in the project dialog.

Crash callstack shows:
```
 	0000000000000000()	Unknown
>	godot.windows.editor.dev.x86_64.exe!RenderingContextDriverVulkanWindows::surface_create(const void * p_platform_data) Line 67	C++
 	godot.windows.editor.dev.x86_64.exe!RenderingContextDriver::window_create(int p_window, const void * p_platform_data) Line 46	C++
 	godot.windows.editor.dev.x86_64.exe!DisplayServerWindows::_create_window(DisplayServer::WindowMode p_mode, DisplayServer::VSyncMode p_vsync_mode, unsigned int p_flags, const Rect2i & p_rect, bool p_exclusive, int p_transient_parent) Line 5659	C++
 	godot.windows.editor.dev.x86_64.exe!DisplayServerWindows::create_sub_window(DisplayServer::WindowMode p_mode, DisplayServer::VSyncMode p_vsync_mode, unsigned int p_flags, const Rect2i & p_rect, bool p_exclusive, int p_transient_parent) Line 1472	C++
 	godot.windows.editor.dev.x86_64.exe!Window::_make_window() Line 634	C++
 	godot.windows.editor.dev.x86_64.exe!Window::set_visible(bool p_visible) Line 853	C++
 	godot.windows.editor.dev.x86_64.exe!Window::popup(const Rect2i & p_screen_rect) Line 1866	C++
 	godot.windows.editor.dev.x86_64.exe!Window::popup_centered(const Vector2i & p_minsize) Line 1796	C++
 	godot.windows.editor.dev.x86_64.exe!ProjectManager::_show_quick_settings() Line 390	C++
```
Where `vkCreateWin32SurfaceKHR` is nullptr.

But the issue comes much earlier.
The problem is that the vkInstance is created twice. Once for the windows platform by the `DisplayServerWindows` class as intended.
And a second time for a platform agnostic `DisplayServer` when calling `DisplayServer::can_create_rendering_device()`.

This is a major issue, since Godot is using Volk, we cannot instatiate multiple vkInstances. Even a dummy one. This is because Volk uses global pointers for storing vulkan functions. The functions are initialized when calling `volkLoadInstance`. If this function is called multiple times, pointers are overwritten.

I found the incriminating change causing the crash: 04d0e7f7.

Function pointers should only be initialized once.
Asserts should be added so we do not overwrite the function pointers in the future.

### Steps to reproduce

1. Open project dialog
2. Open settings

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Gaktan**
Fixes #96722

I refactored a bit to be able to share as much code as possible with other systems that create a local device,

I first wanted to replace the `create_local_rendering_device()`, but since it's apparently used in GDScript, I did not know if it was possible to pass pointer reference arguments.

Note: this does not fix the leak that still exists in `create_local_rendering_device()`: #71003

### CODE REVIEW

File: servers/display_server.cpp [hunk 1]
```diff
@@ -1222,49 +1222,6 @@ void DisplayServer::_input_set_custom_mouse_cursor_func(const Ref<Resource> &p_i
 	singleton->cursor_set_custom_image(p_image, (CursorShape)p_shape, p_hostspot);
 }
 
-bool DisplayServer::can_create_rendering_device() {
```
Comment (akien-mga) [inline servers/display_server.cpp:1225]: I believe you should be able to remove the `drivers/*` includes now.

File: servers/rendering_server.cpp [hunk 2]
```diff
@@ -31,6 +31,13 @@
 #include "rendering_server.h"
 #include "rendering_server.compat.inc"
 
+#if defined(VULKAN_ENABLED)
+#include "drivers/vulkan/rendering_context_driver_vulkan.h"
+#endif
+#if defined(METAL_ENABLED)
+#include "drivers/metal/rendering_context_driver_metal.h"
+#endif
```
Comment (akien-mga) [inline servers/rendering_server.cpp:39]: This is a pre-existing issue, so maybe not blocking, but these includes break code encapsulation. The generic / abstract `servers` code shouldn't need to access driver code, and instead have virtual methods that drivers can implement.

Comment (Gaktan) [reply servers/rendering_server.cpp:39]: I'm trying to think of the best way to do this. Does it make sense to have this in the DisplayServer class?
Since the RenderServer doesn't have API.
I don't know the subtlety between the two classes. Does it even make sense for the RenderServer to have `RenderingServer::create_local_rendering_device()` ?

**Comment by clayjohn** [comment]
I think this is too much complexity just to solve https://github.com/godotengine/godot/issues/96722.

The core issue in https://github.com/godotengine/godot/issues/96722 is that creating a _RenderingDevice_ (not a local rendering device) crashes on certain hardware when a RenderingDevice has already been created. The solution is to add a check at the top of `can_create_rendering_device()` that checks if we are already using the Compatibility renderer. If we are, then it continues and attempts to create a RenderingDevice, if not, it does an early out and returns `true`.

**Comment by Gaktan** [comment]
That's fair.
Although what `can_create_rendering_device()` is doing is essentially the same steps as creating a local rendering device (literally the same code). I just took the opportunity to cleanup a bit and unify code

**Comment by clayjohn** [comment]
> That's fair. Although what `can_create_rendering_device()` is doing is essentially the same steps as creating a local rendering device (literally the same code). I just took the opportunity to cleanup a bit and unify code

Not exactly. `can_create_rendering_device()` doesn't create a local rendering device so the flow is very different. The new function also makes the user responsible for cleaning up the RenderingDevice and Context which is a big problem for a function like this. 

Also, as a bonus, while looking at the code again, I realized that it can done very simply just by checking if the RenderingDevice singleton exists:

```
RenderingDevice *device = RenderingDevice::get_singleton();
if (device) {
	return true;
}
```

This is what `create_local_rendering_device()` does, which is why attempting to create one works for this PR.

**Comment by dhoverml** [comment]
@Gaktan can you please rebase?
I wanted to confirm that this fixes #96938, but I am getting a non-trivial merge conflict when I cherry pick.

**Comment by Gaktan** [comment]
@dhoverml Should be good now

**Comment by dhoverml** [comment]
Thanks @Gaktan .
It looks like the crash is fixed with this PR, however, creating new windows is very slow.  It takes about 1 second to create a new window (click on `+ Create` in the Project Manager, or open any menu in the editor when `Single Window Mode` is false).
I don't know if that is unrelated to this PR though.

**Comment by Gaktan** [comment]
@clayjohn I'll do the simple fix for now, and do the refactor in an other PR

**Review by clayjohn — APPROVED** [review]
Looks great, thank you!

**Comment by clayjohn** [comment]
> Thanks @Gaktan . It looks like the crash is fixed with this PR, however, creating new windows is very slow. It takes about 1 second to create a new window (click on `+ Create` in the Project Manager, or open any menu in the editor when `Single Window Mode` is false). I don't know if that is unrelated to this PR though.

That's unrelated to this PR. 

If you are on Windows you can improve the speed of opening new windows a lot by switching to D3D12 instead of Vulkan

**Comment by clayjohn** [comment]
> @clayjohn I'll do the simple fix for now, and do the refactor in an other PR

Sounds good!

**Comment by akien-mga** [comment]
Thanks!
