### PR TITLE
Fix checking unsaved changes only in current scene

### LINKED ISSUE #4504: Prompt for unsaved scene changes checks incorrect scene
**Operating system or device:**
Windows 10 Pro x64

**Issue description** (what happened, and what was expected):
The check to ask for closing the scene in case of unsaved changes checks the currently displayed scene, not the scene which tab is about to be closed.

This creates two issues:
- The current scene has unsaved changes; closing tabs of saved scenes creates a misleading prompt: "Please Confirm...: Close scene? (Unsaved changes will be lost)"
- Even worse: The current scene is saved; closing tabs with unsaved changes does not create a prompt at all and immediately discards the scene and changes.

**Steps to reproduce:**
Open multiple scenes, change something in one, try closing the unchanged scenes (or the other way round); you'll get a misleading prompt or none where should be one.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #4504

AFAIK, the only way to close a scene without making it the currently edited one is with the _"Always Show Close Button In Scene Tabs"_ option activated, right?

### CODE REVIEW

File: tools/editor/editor_node.cpp [hunk 1]
```diff
@@ -1,4 +1,4 @@
-/*************************************************************************/
+﻿/*************************************************************************/
```
Comment (neikeq) [inline tools/editor/editor_node.cpp]: I have no idea why this happens :|

Comment (akien-mga) [inline tools/editor/editor_node.cpp]: That's weird indeed. Even in the raw patch I don't see any difference: https://github.com/godotengine/godot/commit/4427833746b94f35d304afa7ea47bd4976a21229.patch
Could be a line ending character that changed (LF to CRLF for example), or an added BOM marker.

Comment (neikeq) [inline tools/editor/editor_node.cpp]: Ah, yeah... it's a BOM marker:
damnit

No idea why Qt Creator is adding it nor how to avoid it. I will remove it manually for now...

**Comment by RayKoopa** [comment]
Yeah, I had that option on since ever (not sure if it's default).

**Comment by RayKoopa** [comment]
Compiled and tested your change, works as it should now!
