### PR TITLE
Insert barriers between subpasses when using enhanced barriers on D3D12.

### LINKED ISSUE #110096: [4.3 - 4.5] DirectX12 AMD Radeon Broken When Using Enhanced Barriers
### Tested versions

4.5dev [d5ad0556a2c04c50694b5c04dc1b3bf03ecd7113]
4.3dev

### System information

Windows 10 4.5 D3D12 12_0 - Forward Mobile AMD Radeon RX 6500 XT

### Issue description

We had plenty of people describing with AMD Radeon GPUs telling us that rendering on their PC looked broken.
After acquiring an AMD Radeon of our own we could reproduce this issue:
Image

Further debugging and comparing of render doc traces brought to light, that enabling Enhanced Barriers in the rendering pipline leads to ResolveSubresource calls without the inserting the needed barriers beforehand.
That leads to random state, interestingly as in the picture above it mostly fails for shaders whose output depend on the screen texture. 

**Correct** (Working) RenderDoc Trace:
Image

Incorrect (Non-Working) RenderDoc Trace:

Image

One can find the respective render doc dumps here:
https://drive.google.com/drive/folders/1Ha1EATLuHDND0ba8ulvkwvtAmBWaxCVz?usp=sharing

these where made with a few days old master branch. 

We fixed this now for our branch by disabled the barriers. But this is especially bad since the only working backend on AMD then is Angle/OpenGL

### Steps to reproduce

Start any Godot game using sub viewports  using MSAA  and rendering the associated viewport texture.
Notice that the textures go into a corrupted state when running the game on a somewhat recent AMD GPU.

### Minimal reproduction project (MRP)

TODO

### PR DESCRIPTION
**Pull request by blueskythlikesclouds**
Fixes #110096.

When using render passes, Vulkan does the job of synchronizing it under the hood. On D3D12, this is normally handled properly when using legacy barriers, but enhanced barriers disable these code paths and rely on pipeline barriers emitted by the render graph instead. Since the render graph emits no barriers for this case, we run into hazards on D3D12.

These barriers might be a little inefficient, but I don't think there's a proper way to solve it without editing the render graph to separate subpasses into multiple draw lists, which would be too involving of a change to the code.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Makes sense to me

**Comment by blueskythlikesclouds** [comment]
I just realized that we need to add barriers for input attachments too, otherwise when MSAA is disabled, it's going to try to use the color attachment as the input texture without any barriers inbetween.

Should I fix that in a follow-up or this PR?

**Comment by clayjohn** [comment]
Might as well fix it here

**Comment by blueskythlikesclouds** [comment]
I've changed it to handle all the attachment types instead, so when a layout change needs to happen, it'll insert barriers between the subpasses as needed.

File: drivers/d3d12/rendering_device_driver_d3d12.cpp [hunk 1]
```diff
@@ -4857,6 +4866,102 @@ void RenderingDeviceDriverD3D12::command_begin_render_pass(CommandBufferID p_cmd
...
+	BitField<PipelineStageBits> dst_stages = {};
+
+	thread_local LocalVector<TextureBarrier> texture_barriers;
+	texture_barriers.clear();
+
+	CommandBufferInfo *cmd_buf_info = (CommandBufferInfo *)p_cmd_buffer.id;
+
+	// Subpass dependencies cannot be specified by the end user, and by default they are very aggressive.
+	// We can have a bit of leniency by just looking at the texture layout and specifying appropriate access and stage bits.
+	auto _layout_to_access_bits = [](TextureLayout p_layout) -> BitField<BarrierAccessBits> {
```
Comment (clayjohn) [inline drivers/d3d12/rendering_device_driver_d3d12.cpp]: This should use a static LUT instead of a lambda.

File: drivers/d3d12/rendering_device_driver_d3d12.cpp [hunk 2]
```diff
@@ -4857,6 +4866,102 @@ void RenderingDeviceDriverD3D12::command_begin_render_pass(CommandBufferID p_cmd
...
+				return BARRIER_ACCESS_RESOLVE_WRITE_BIT;
+			}
+			default: {
+				WARN_PRINT_ONCE("Unrecognized texture layout, forcing full memory access.");
+				return BARRIER_ACCESS_MEMORY_READ_BIT | BARRIER_ACCESS_MEMORY_WRITE_BIT;
+			}
+		}
+	};
+
+	auto _layout_to_stage_bits = [](TextureLayout p_layout) -> BitField<PipelineStageBits> {
```
Comment (clayjohn) [inline drivers/d3d12/rendering_device_driver_d3d12.cpp]: Same here, should be a static LUT

**Review by clayjohn — CHANGES_REQUESTED** [review]
Looks great overall! Just a small suggested change to use LUTs instead of lambdas. Best case scenario the compiler will optimize the lambdas into static LUTs, but it is better to just write LUTs from the beginning.

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by Repiteo** [comment]
Thanks!
