### PR TITLE
Fixes incorrect display of property labels with feature tags

### LINKED ISSUE #60352: 4.0 Custom Project Settings with feature tags are displayed incorrectly
### Godot version

4.0alpha6

### System information

Windows 10 Vulkan, Nvidia 1050TI (Reproduced on desktop 2080TI)

### Issue description

Expected:

Expected

Got:

Got

Names are only displayed incorrectly; the project.godot-file has correct names, the tooltips use correct paths and the settings can be referred from the expected paths from code. Based on a quick test it seems that all tags produce similar results depending on their length.

Also a relevant comment from @Calinou:
> This is likely a regression from [godotengine/godot#58706](https://github.com/godotengine/godot/pull/58706) ... I've been able to reproduce this too but I don't know exactly why it's broken.

Also also. When trying to reproduce this bug, I found out that the reset-icons next to the custom project settings don't reset the value to the default variable value but instead delete the setting altogether. (In 3.x there are no reset-icons). If not linked to this issue, then perhaps another bug.

### Steps to reproduce

Add a custom project setting that has a feature tag. (.windows, .android etc.)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Rindbee**
Closes #60352

|| Image |
| :-------: | :------: |
| Before |  |
| After |  |

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -2678,11 +2678,13 @@ void EditorInspector::update_tree() {
...
 		String name_override = (path.contains("/")) ? path.substr(path.rfind("/") + 1) : path;
+		String dot_char;
 		String feature_tag;
 		{
-			const int dot = name_override.find(".");
+			const int dot = name_override.rfind(".");
 			if (dot != -1) {
-				feature_tag = name_override.right(dot);
+				dot_char = ".";
+				feature_tag = name_override.substr(dot + 1, -1);
```
Comment (timothyqiu) [inline editor/editor_inspector.cpp:2687]: This should not be changed to `rfind`, as other places like ProjectSettings also use the _first_ dot as separator. It could be another PR if you want to change this behavior.

The `dot_char` is redundant here. Using `feature_tag = name_override.substr(dot);` is OK I think. `feature_tag` is here only to be concatenated back to the property path.

Comment (Rindbee) [reply editor/editor_inspector.cpp:2687]: Delimiters are still needed, spaces may be more appropriate, otherwise the two words may be merged into one word.

Comment (timothyqiu) [reply editor/editor_inspector.cpp:2687]: I mean, you stripped the dot from `feature_tag` by using `dot + 1` instead of `dot`, and used a dedicated `dot_char` to store it.

If you use `substr(dot)`, then `dot_char` won't be needed.

**Review by timothyqiu — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Thanks!
