### PR TITLE
Fix code completion override of home and end keys

### LINKED ISSUE #71471: Autocomplete hijacks home and end keys
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

Windows 10

### Issue description

Autocomplete hijacks home and end keys. This makes writing code very annoying as you need to speficically close the autocomplete popup before you can continue coding.

Autocomplete should use *only* strictly necessary keys it needs to work but not keys which are usually used when writing a line of code. Acceptable keys would be up/down arrow keys, page up/down, esc.

kuva

### Steps to reproduce

1. First write this
```gdscript
var idget_parent()
```
2. Then add `=` between `id` and `get_parent()` to open the autocomplete popup.
3. Try to move to the end of the code line by pressing end key

-> It doesn't work. Autocomplete popup has got the focus and selection moves to the end of the list.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by adamscott**
Changes the behaviour of the home and end keys when the autocomplete popup is open.

Rather than going to the top and the bottom of the list, home and end closes the autocomplete popup and work as usual.

Fixes #71471

### CODE REVIEW

**Comment by Paulb23** [comment]
Checked a few other editors, this seems to be the common behaviour. Couple of unit tests are failing on macOS otherwise looks good.

**Comment by adamscott** [comment]
I wonder if macOS has another behavior when using home and end keys.

**Review by groud — APPROVED** [review]
Approved in Input PR review

Edit: the failing check needs a fix first though.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` d31794c4a26e5e10fc30c34a1ae9722fd9f50123), it works as expected.

https://github.com/godotengine/godot/assets/180032/2fb3025a-40d9-44f2-a58a-9149088a04d7

TIL pressing <kbd>Home</kbd> several times cycles between the beginning of the line with and without leading whitespace (like in VS Code) :slightly_smiling_face: 

An unit test needs to be fixed before this can be merged.

**Comment by adamscott** [comment]
I installed a macOS virtual machine to test the issue (why-oh-why it doesn't pass the unit tests on macOS!?)

**Comment by adamscott** [comment]
> > why-oh-why it doesn't pass the unit tests on macOS!?
> 
> I suspect it's related to `SEND_GUI_ACTION("ui_end");`, this macro is sending a key combination for the action (`End` key on all platforms). On other platforms, `ui_text_caret_line_end` is the same, but not on macOS (`ui_text_caret_line_end` is `Command+Right` and `Ctrl+E`).

Yes. I just found out that by reading that [Reddit comment](https://www.reddit.com/r/MacOS/comments/pz9vnu/comment/hf0f0nk/?utm_source=reddit&utm_medium=web2x&context=3).

**Comment by adamscott** [comment]
I just added the same functionality for `ui_text_caret_line_start` and `ui_text_caret_line_end` and disabled the tests for `ui_home` and `ui_end` on macOS.

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -479,19 +479,10 @@ void CodeEdit::gui_input(const Ref<InputEvent> &p_gui_input) {
...
-		}
-		if (k->is_action("ui_end", true)) {
-			code_completion_current_selected = code_completion_options.size() - 1;
-			code_completion_force_item_center = -1;
-			queue_redraw();
-			accept_event();
-			return;
+		if (
+				k->is_action("ui_text_caret_line_start", true) ||
+				k->is_action("ui_text_caret_line_end", true)) {
```
Comment (akien-mga) [inline scene/gui/code_edit.cpp:484]: I think it's more readable on a single line than on three like this (I know it's clang-format doing it but it makes it not worth it).

Comment (adamscott) [reply scene/gui/code_edit.cpp:484]: That's a left over of these being 4 checks instead of 2. I'm correcting this.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
