### PR TITLE
Fix race in `RefCounted::unreference()`

### LINKED ISSUE #115173: Android crash report with error: `FORTIFY: pthread_mutex_lock called on a destroyed mutex` (analytics report)
### Tested versions

- Reproducible in 4.5.stable
- Reproducible in https://github.com/akien-mga/godot/releases/tag/4.5.1.stable%2Bvulkan_mobile_fixes which is 4.5.1.stable + cherry-picks of Vulkan Mobile fixes made by @blueskythlikesclouds recently (https://github.com/akien-mga/godot/compare/4.5.1-stable...4.5.1.stable+vulkan_mobile_fixes).
- Can't easily test 4.6.rc as this is from Google Play analytics on a game in production with thousands of users, will test 4.5.2.rc1 once it's out

### System information

Various Android devices with different SoCs/GPUs and versions (11, 13, 14, 16 Beta seen in reports)

### Issue description

This is a crash seen in the wild on a number of devices with @Draknek's [Spooky Express](https://play.google.com/store/apps/details?id=express.spooky) (10k+ install base).

The Google Play Console reports this overarching error:
```
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x<sanitized>)
```

And this crash stack trace:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 21238 >>> express.spooky <<<

backtrace:
  #00  pc 0x000000000008d974  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #01  pc 0x000000000008f7d4  /apex/com.android.runtime/lib64/bionic/libc.so (__fortify_fatal(char const*, ...)+128)
  #02  pc 0x00000000000f69c0  /apex/com.android.runtime/lib64/bionic/libc.so (HandleUsingDestroyedMutex(pthread_mutex_t*, char const*)+68)
  #03  pc 0x00000000000f6840  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+248)
  #04  pc 0x00000000000db574  /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk!libc++_shared.so (std::__ndk1::mutex::lock()+96) (BuildId: 725db191d65be59dc18ddb3238f9e749442844a4)
  #05  pc 0x0000000003efde20  /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk!libgodot_android.so (RefCounted::unreference()+41) (BuildId: a9b34d498052473c)
  #06  pc 0x000000000124678c  /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk!libgodot_android.so (MethodBindTR<bool>::ptrcall(Object*, void const**, void*) const+254) (BuildId: a9b34d498052473c)
  #07  pc 0x00000000000d2a64  /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk
```

<details>
<summary>Fully symbolicated stack trace with `ndk-stack`</summary>

```
********** Crash dump: **********
#00 0x000000000008d974 /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
#01 0x000000000008f7d4 /apex/com.android.runtime/lib64/bionic/libc.so (__fortify_fatal(char const*, ...)+128)
#02 0x00000000000f69c0 /apex/com.android.runtime/lib64/bionic/libc.so (HandleUsingDestroyedMutex(pthread_mutex_t*, char const*)+68)
#03 0x00000000000f6840 /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+248)
#04 0x00000000000db574 /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk!libc++_shared.so (std::__ndk1::mutex::lock()+96) (BuildId: 725db191d65be59dc18ddb3238f9e749442844a4)
    std::__ndk1::__libcpp_mutex_lock[abi:ne190000](pthread_mutex_t*)
    out/lib/device-libcxx-aarch64-ndk-cxx/out/lib/device-libcxx-aarch64-ndk-cxx/include/c++/v1/__thread/support/pthread.h:96:10
    std::__ndk1::mutex::lock()
    out/lib/device-libcxx-aarch64-ndk-cxx/out/llvm-project/libcxx/src/mutex.cpp:29:12
#05 0x0000000003efde20 /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk!libgodot_android.so (RefCounted::unreference()+41) (BuildId: a9b34d498052473c)
    std::__ndk1::unique_lock<std::__ndk1::mutex>::unique_lock[abi:nn190000](std::__ndk1::mutex&)
    /root/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__mutex/unique_lock.h:41:11
    MutexLock<MutexImpl<std::__ndk1::mutex>>::MutexLock(MutexImpl<std::__ndk1::mutex> const&)
    /root/godot/./core/os/mutex.h:77:4
    Object::_instance_binding_reference(bool)
    /root/godot/./core/object/object.h:689:14
    RefCounted::unreference()
    /root/godot/core/object/ref_counted.cpp:89:22
#06 0x000000000124678c /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk!libgodot_android.so (MethodBindTR<bool>::ptrcall(Object*, void const**, void*) const+254) (BuildId: a9b34d498052473c)
    void call_with_ptr_args_ret_helper<__UnexistingClass, bool>(__UnexistingClass*, bool (__UnexistingClass::*)(), void const**, void*, IndexSequence<...>)
    /root/godot/./core/variant/binder_common.h:254:22
    void call_with_ptr_args_ret<__UnexistingClass, bool>(__UnexistingClass*, bool (__UnexistingClass::*)(), void const**, void*)
    /root/godot/./core/variant/binder_common.h:502:2
    MethodBindTR<bool>::ptrcall(Object*, void const**, void*) const
    /root/godot/./core/object/method_bind.h:538:3
#07 0x00000000000d2a64 /data/app/~~Vhgpa6OywDhA90Sb-F_JJg==/express.spooky-Z_6yR7zxaAMJl1OtSLUdXQ==/split_config.arm64_v8a.apk
```

</details>

That's not much to go on, and I don't have an MRP.

Spooky Express uses GDScript, but also one GDExtension [fmod-gdextension](https://github.com/utopia-rise/fmod-gdextension), so it's possible that this bug is caused by the extension doing something illegal or a godot-cpp bug. But there's no _obvious_ indication of that in the stack trace.

I'm logging this so we're aware of the issue, and to see if others run into similar crashes and can provide information.

### Steps to reproduce

Unknown

### Minimal reproduction project (MRP)

TBD

### PR DESCRIPTION
**Pull request by hpvb**
When two threads unreference() a RefCounted Object at the same time there's a potential race.

Thread A sees rc_val == 1, enters the if() block.
Thread B sees rc_val == 0, enters the if() block.

Thread A gets scheduled out, or is simply scheduled on a slower core and Thread B finishes, returning die = true. Thread B then frees the Object.

Some time during or after ~Object() Thread A wakes up and tries to call methods on the Object, which is either destroyed or in the process of being destroyed, leading to a use-after-free.

We fix the problem by counting how many threads are currently inside the critical section, and blocking returning die = true as long as there are still other threads potentially alive.

Tested by running with --test and by opening and playing various public and private Godot projects.

This fixes #115173

### CODE REVIEW

File: core/object/ref_counted.cpp [hunk 1]
```diff
@@ -33,6 +33,9 @@
 #include "core/object/class_db.h"
 #include "core/object/script_instance.h"
 
+// for _cpu_pause()
+#include "core/os/spin_lock.h"
```
Comment (akien-mga) [inline core/object/ref_counted.cpp]: Nitpick, can be kept grouped with other includes, with the comment inline.

```suggestion
#include "core/object/class_db.h"
#include "core/object/script_instance.h"
#include "core/os/spin_lock.h" // for _cpu_pause()
```

**Comment by hpvb** [comment]
I would like to amend this a little bit in the sense that I believe this is the only way to resolve this problem *without changing semantics of `unreference()`* 

Right now both the `rc_val == 0` and `rc_val == 1` cases have observable effects outside of the class. In some cases GDExtension callbacks are called.

There's ways of achieving clean shutdown without this refcount, mostly by moving more of the cleanup code to `Object::~Object()` but this would have API observable changes.

I think we *should* do this for Godot 5. But I don't see a way of retaining the api contract otherwise.

**Review by RandomShaper — APPROVED** [review]
Looks good to me!

Just as a suggestion (for the future), we could maybe refactor our very polished `SpinLock` implementation so we can use it to also have a `SpinSempahore` we could leverage here. I acknowledge it's very unlikely that we ever need to spin here, but that won't hurt anyway.

**Review by Ivorforce — APPROVED** [review]
Makes sense crash wise, but note that this introduces a pretty significant cost to `RefCounted`, both size wise and performance wise.

I'm not sure what's prompting the current code to notify extensions and scripts to decrement also on one instead of just 0, but changing to notify on just 0 would also fix the issue.

**Comment by hpvb** [comment]
> Makes sense crash wise, but note that this introduces a pretty significant cost to `RefCounted`, both size wise and performance wise.
> 
> I'm not sure what's prompting the current code to notify extensions and scripts to decrement also on one instead of just 0, but changing to notify on just 0 would also fix the issue.

I totally agree, but that would change the API contract so I didn't want to do it. If we can figure out why we notify on both we should change it. But there very well might be GDExtensions that rely on this behavior.

**Comment by Repiteo** [comment]
Thanks!

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.3.
