### PR TITLE
Remove error messages caused by Save on Focus feature

### LINKED ISSUE #73765: "Parent node is busy setting up children" on focus loss when `save_on_focus_loss` option is enabled
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.rc (5f3dee5988391deffcc0de1039dd50e05e266913)

### System information

Mageia 9, Linux

### Issue description

When `interface/editor/save_on_focus_loss` is enabled in the Editor Settings, focus loss triggers a save as expected, but also these errors:
```
ERROR: Parent node is busy setting up children, `add_child()` failed. Consider using `add_child.call_deferred(child)` instead.
   at: add_child (scene/main/node.cpp:1136)
ERROR: Condition "!is_inside_tree()" is true.
   at: popup_centered (scene/main/window.cpp:1456)
```

### Steps to reproduce

- Enable `interface/editor/save_on_focus_loss`
- Alt tab to desktop and back

### Minimal reproduction project

Happens on an empty project.

*Production edit (keywords for easier searching): Task 'save' already exists.*

### PR DESCRIPTION
**Pull request by AlexanderFarkas**
Fixes #73765

To clarify: fixing it that way covers most of the problems caused by the underlying issue (showing dialogs on the root Window during notification processing). 

Another issue could be created to track the underlying problem.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -2689,6 +2689,15 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
...
 			[[fallthrough]];
 		}
+
+		case FILE_SAVE_SCENE_SILENTLY: {
+			Node *scene = editor_data.get_edited_scene_root();
+			if (scene && !scene->get_scene_file_path().is_empty() && DirAccess::exists(scene->get_scene_file_path().get_base_dir())) {
+				_save_scene(scene->get_scene_file_path());
+				save_editor_layout_delayed();
+			}
+		} break;
```
Comment (akien-mga) [inline editor/editor_node.cpp:2699]: This will break the save logic, see how the previous case has a `[[fallthrough]]` attribute and no `break;` - so it's meant to fall through to the `FILE_SAVE_AS_SCENE` case, which won't happen anymore here.

Comment (AlexanderFarkas) [reply editor/editor_node.cpp]: Missed it, thank you! 
I believe, it should be fixed now.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -2666,6 +2666,13 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 		case FILE_CLOSE: {
 			_scene_tab_closed(editor_data.get_edited_scene());
 		} break;
+		case FILE_SAVE_SCENE_SILENTLY: {
+			Node *scene = editor_data.get_edited_scene_root();
+			if (scene && !scene->get_scene_file_path().is_empty() && DirAccess::exists(scene->get_scene_file_path().get_base_dir())) {
+				_save_scene(scene->get_scene_file_path());
+				save_editor_layout_delayed();
+			}
+		} break;
```
Comment (Calinou) [inline editor/editor_node.cpp:2675]: Add a comment to explain why this is needed:

```suggestion
		case FILE_SAVE_SCENE_SILENTLY: {
			// Save scene without displaying progress dialog. Used to work around
			// errors when Save on Focus Loss kicks in.
			Node *scene = editor_data.get_edited_scene_root();
			if (scene && !scene->get_scene_file_path().is_empty() && DirAccess::exists(scene->get_scene_file_path().get_base_dir())) {
				_save_scene(scene->get_scene_file_path());
				save_editor_layout_delayed();
			}
		} break;
```

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected (Windows 11). I no longer get errors when **Save on Focus Loss** kicks in.

The downside of this approach is that if saving takes a long time (e.g. due to a huge binary resource being serialized as text in a scene file), the editor will appear to freeze for a few seconds if you alt-tab back in quickly. Still, I consider this is preferable to displaying an error every time the editor loses focus.

Eventually, the scene saving UX should be reworked to use a visually non-blocking method that doesn't need to spawn a dialog. This will alleviate the issue entirely while being less intrusive when you press <kbd>Ctrl + S</kbd> or when saving before running a scene.

**Comment by AlexanderFarkas** [comment]
> Tested locally, it works as expected (Windows 11). I no longer get errors when **Save on Focus Loss** kicks in.
> 
> The downside of this approach is that if saving takes a long time (e.g. due to a huge binary resource being serialized as text in a scene file), the editor will appear to freeze for a few seconds if you alt-tab back in quickly. Still, I consider this is preferable to displaying an error every time the editor loses focus.
> 
> Eventually, the scene saving UX should be reworked to use a visually non-blocking method that doesn't need to spawn a dialog. This will alleviate the issue entirely while being less intrusive when you press Ctrl + S or when saving before running a scene.

For me the editor freezes even without changes in this PR. It could be especially noticeable when you alt-tab between the editor and the running game.

**Comment by akien-mga** [comment]
Looks good. Could you amend the commit message (with `git commit --amend`, then `git push --force` to update the PR) to use a more explicit message?

E.g.:
```
Remove error messages caused by Save on Focus feature

Fixes #73765.
```

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
