### PR TITLE
Prevent HTTPRequest from polling invalid client

### LINKED ISSUE #60602: Error message for reaching maximum number of concurrent DNS queries is not explicit.
### Godot version

3.x

### System information

Windows 10

### Issue description

After https://github.com/godotengine/godot/pull/59445 upped the maximum concurrent DNS queries at any given time, it is much less likely to reach the limit, but not impossible. And should it occur, the console outputs:
```
Condition ' resolving == IP::RESOLVER_INVALID_ID ' is true. returned: ERR_BUG
```

This error message can potentially be very confusing. misleading and, compared to most other error messages in Godot, it looks quite cryptic. If the users doesn't know where to look, it's bound to cause a few headaches
Ideally, it should tell the user exactly what happened (the query limit has been reached), and potentially instruct the user on how to fix it (_tone down the requests, or increase the limit, the latter of which should probably not be encouraged_)

### Steps to reproduce

No need.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Mickeon**
Somewhat fixes https://github.com/godotengine/godot/issues/60602

The reason why the error mentioned in the issue typically shows up in the first place is because **HTTPRequest** keeps polling its associated client. However, as a result of exceeding the maximum DNS requests, the client's resolving id is INVALID, but nothing seems to be done on the **HTTPRequest**'s side to handle it, because the **HTTPRequest** doesn't know this happened.

Now, only this error show up (no edit on my part, this is appropriate):
image

**HTTPClientTCP**.`connect_to_host()` now returns **ERR_CANT_RESOLVE** if the maximum number of DNS queries has been reached, ~and so does **HTTPRequest**.`request()`.~

~Need to update documentation, but I know **ERR_BUSY** isn't the most ideal error code (it's already used, too). I need someone to suggest an alternative.~

### CODE REVIEW

**Comment by Mickeon** [comment]
Reworked this PR, somewhat. Now it returns early, and the HTTPRequest... request isn't even started if the ID is invalid.

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by Mickeon** [comment]
As I do that, what would the most appropriate error be for this?

File: scene/main/http_request.cpp [hunk 1]
```diff
@@ -154,6 +154,10 @@ Error HTTPRequest::request_raw(const String &p_url, const Vector<String> &p_cust
 		err = _request();
 		if (err != OK) {
 			call_deferred(SNAME("_request_done"), RESULT_CANT_CONNECT, 0, PackedStringArray(), PackedByteArray());
+			// Maximum number of DNS queries reached.
+			if (err == ERR_BUSY) {
+				return ERR_BUSY;
+			}
```
Comment (Faless) [inline scene/main/http_request.cpp:160]: I don't think this is needed.

File: core/io/http_client_tcp.cpp [hunk 2]
```diff
@@ -94,6 +94,9 @@ Error HTTPClientTCP::connect_to_host(const String &p_host, int p_port, bool p_ss
 	} else {
 		// Host contains hostname and needs to be resolved to IP.
 		resolving = IP::get_singleton()->resolve_hostname_queue_item(server_host);
+		if (resolving == IP::RESOLVER_INVALID_ID) {
+			return ERR_BUSY;
+		}
```
Comment (Faless) [inline core/io/http_client_tcp.cpp:99]:
```suggestion
		if (resolving == IP::RESOLVER_INVALID_ID) {
			status = STATUS_CANT_RESOLVE;
			return ERR_CANT_RESOLVE;
		}
```

**Review by Faless — CHANGES_REQUESTED** [review]
Thanks for looking into this issue, see my review comments for changes.

File: scene/main/http_request.cpp (hunk 1 above)
Comment (Mickeon) [reply scene/main/http_request.cpp:160]: I wanted to return a more unique error to notify that this was happening but it being more generic wouldn't hurt, I suppose?

File: core/io/http_client_tcp.cpp (hunk 2 above)
Comment (Mickeon) [reply core/io/http_client_tcp.cpp]: Done and done

**Review by Faless — APPROVED** [review]
Nice work, thanks! :trophy:

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.
