### PR TITLE
Alpha Hash and Alpha2Coverage Implementation

### LINKED ISSUE #1273: Add alpha-to-coverage support (MSAA for alpha-tested materials)
**Describe the project you are working on:**

A third person shooter.

**Describe the problem or limitation you are having in your project:**

Achieving a pleasant appearance for alpha transparent surfaces is very difficult due to limitations with Godot's rendering, due to the lack of antialiasing on alpha transparent surfaces with alpha scissor enabled, producing very harsh and noticeable visible aliasing on trees.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Alpha to Coverage, a technique for using MSAA on Alpha Scissor'd Surfaces to avoid hard aliasing artefacts around the edges of alpha scissor'd surfaces. When alpha scissor'd surfaces are drawn, individual MSAA samples are filled based on opacity, producing an antialiased edge along the alpha scissor surfaces with minimal performance overhead.

[See this article for more information on what problems this feature solves and how it's implemented.](https://medium.com/@bgolus/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I can't think of a reason why anyone with MSAA enabled would want to disable this feature once it is added, but if that is desired, then a simple tickbox under Godot's project settings would be sufficient, or it could be even a per-material or a shader option.

Beyond that, there would be no other differences in UX or functionality in Godot. The technical details on Alpha to Coverage are discussed in the article I previously linked.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I can foresee myself using this in every 3D project I create in Godot, and certainly any time I create any kind of surface that relies on alpha transparency and alpha scissor. It could visually improve the quality of many types of assets. Eg: Trees, metal grates, wire fences, nets, floating text, etc.

I consider this a general quality improvement for Godot.

I do not see how this could be easily implemented with a script or shader code. At the very least, doing so is beyond my ability to do so.

**Is there a reason why this should be core and not an add-on in the asset library?:**

A basic rendering feature like this should be part of Godot, not a workaround or an add-on.

It would be likely very difficult to make this kind of additional feature an addon, difficult to maintain that addon, and an unnecessary burden for users to install that addon for this kind of basic rendering feature. Likewise an unnecessary burden for users to come up with some kind of workaround to this problem, assuming there is one.

The only workaround I can imagine is using actual mesh shapes instead of alpha scissor transparency, so for eg: individual leaves instead of alpha transparent images of tree branches, which would likely impact performance for scenes with a lot of foliage and require substantially more work.

It's a fairly standard feature which is found in most other modern game engines. This feature would likely be useful to basically everyone making a 3D game, given how common alpha transparent surfaces are in 3D graphics. Given this kind of feature should be relatively simple to implement for someone familiar with C++ experience and knowledge of how MSAA sampling works, and the huge benefits in visual quality to a broad number of games, I think it would be exceptionally worthwhile for Godot to have this as part of it's core.

### PR DESCRIPTION
**Pull request by marstaik**
This commit adds the following features to the Vulkan rendering pipeline:
Alpha Hash, AlphaToCoverage + AlphaToOne, and "mipped" antialiased edges.

These techniques are very helpful for creating nice looking Hair and Foliage, where alpha channels are used the most.

## Preview Video:
https://youtu.be/zQKkUNvAAJ4

## Alpha Hashing
Alpha Hashing is a dithered alpha testing method from NVIDIA that you can find more documentation for [here](https://developer.download.nvidia.com/assets/gameworks/downloads/regular/GDC17/RealTimeRenderingAdvances_HashedAlphaTesting_GDC2017_FINAL.pdf?pXO7jOEIrzP_kUqTc2Hwz88svU8woWuXonDBKl_PaMl48YZvczzsPGfgu3kvxE1gAri9d-f9IoR5mjgr8thwG7V1kTAPs49DdnmiGdxaEz5OrSyawbhCp5EdC0aq7uckAuGpSXM6eWnKAHrd7nmFnPMv8tZQqhU-dwEUUeRpoe_86TFQI1Re6jngDwW2NnMprcJMinDzn0NFI4Z5erF3MrnrH65AeQ)

## AlphaToCoverage and AlphaToOne
AlphaToCoverage is a technique that takes the fragment shaders alpha channel and AND's it with the MSAA SampleMask to produce additional areas for Anti-aliasing.

AlphaToOne is an additional flag in which after the alpha channel is used for the MSAA SampleMask, the alpha value is *set* to the maximum alpha value.

It is the combination of these two techniques that allow for good-looking anti-aliased alpha testing.

### But why both? Why is AlphaToCoverage by itself not enough?
In the preview video above, you may notice that when switching from "Alpha Edge Blend" to "Alpha Edge Clip" *(the respective names in the UI for AlphaToCoverage and AlphaToCoverage + AlphaToOne)* that using AlphaToCoverage by itself still results is some bleed/halo effects around the textures. This is because AlphaToCoverage alone does not clamp the alpha value; that is - the resulting alpha of the fragment shader still has to be *blended* somehow. And in general this is an issue we have with alpha blending. All AlphaToCoverage does by itself is export the Alpha channel as an area for MSAA to act upon.

This is where AlphaToOne comes in - after adding the apha to the MSAA SampleMask, the alpha value is set to the maximum - so no *blending* occurs anymore.

The final result is fragment color output with no alpha channel, yet MSAA smooths the areas where the alpha channel *was*.

## Alpha Edge Sharpening
This [blog post](https://medium.com/@bgolus/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f) by Ben Golus goes through some techniques for sharpening the Anti-aliasing edge with some mipmapping techniques.

This technique has been implemented as a function called `compute_alpha_antialiasing_edge` in `scene_hight_end.glsl` and usage will be explained below.

The Material3D system uses this by default when AlphaAntialiasing is enabled.

### AlphaToCoverage, AlphaToCoverage + AlphaToOne
In the spatial shader, the render flags `alpha_to_coverage` OR `alpha_to_coverage_and_one` can be added to process the result of the shaders `ALPHA` with either AlphaToCoverage, or AlphaToCoverage + AlphaToOne.

When either of these are set, the blend_mode is overridden to BLEND_MODE_ALPHA_TO_COVERAGE, which is better suited for blending.

### Alpha Scissor
* If `ALPHA_SCISSOR_THRESHOLD` *float, [0,1]* is set in the shader, then alpha values less than the threshold will be discarded.

### Alpha Hash
* If `ALPHA_HASH_SCALE` *float, recommended (0,2]* is set in the shader, alpha hashing will be used and alpha values less than the hash are discarded. Alpha Hash Scale simply affects the dithering affect of the alpha hash

### Alpha Edge (Needs Texture)
Alpha Edge requires two variables:
* `ALPHA_ANTIALIASING_EDGE` *float [0,1]* - Affects the edge point of the Edge sharpening. If `ALPHA_SCISSOR_THRESHOLD` is set, it is *added* to `ALPHA_ANTIALIASING_EDGE` and clamped from [0,1].
* `ALPHA_TEXTURE_COORDINATE` *vec2* - The texture coordinate to use. Think `uv_coordinate * alpha_texture_size`.

Please feel free to ask question and test it out!
I am looking forward to your feedback.

Thanks,
Marios S.

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/1273.*

### CODE REVIEW

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -930,6 +943,8 @@ void BaseMaterial3D::_update_shader() {
 			case TEXTURE_CHANNEL_GRAYSCALE: {
 				code += "\tvec4 roughness_texture_channel = vec4(0.333333,0.333333,0.333333,0.0);\n";
 			} break;
+			case TEXTURE_CHANNEL_MAX:
+				breal; // Internal value, skip.
```
Comment (clayjohn) [inline scene/resources/material.cpp:947]: One more! "Breal"

Comment (marstaik) [reply scene/resources/material.cpp:947]: woops fixed

**Comment by s-ilent** [comment]
Regarding the hashing function, I had some questions. Why did you choose this technique? 
Is there a particular benefit in this use case to its guarantee of stability? The main benefit listed in this paper is that its stability works well for TAA, but Godot does not support TAA. 
This is just conjecture, but the hashing function seems like it is expensive.

Placing the stability aside, the true random nature of the hash function means that it looks visually noisy, which IMO is worse than using simpler, cheaper methods using a screen-space noise sample offset by a temporal factor. 
For example, sampling blue noise from a precomputed lookup texture (1), or R-sequence (2), or one of the other methods listed by Oculus in their article on dithering (3). 
The end results look smoother both in still and in motion, and temporal offsets (as in 3) hide the instability, even if it leads to some shimmering. 

1. <http://momentsingraphics.de/BlueNoise.html>
2. <http://extremelearning.com.au/unreasonable-effectiveness-of-quasirandom-sequences/>
3. <https://developer.oculus.com/blog/tech-note-shader-snippets-for-efficient-2d-dithering/>

**Comment by marstaik** [comment]
Hi @s-ilent , regarding the dithering functions I am not really an expert in the matter, nor have I greatly invested myself in comparing different dithering functions. But I can still give some of my input on the matter from what I have read from the papers.

I think first and foremost, I must apologize because the preview video does not really demonstrate *what* the hash dithering is for - and although I believe you already understand the intent behind it, I'll clarify for others here. 

The Alpha Hash function (or any dithering in general) really isn't useful for the hair case I showed in the video - as the hair was opaque and faded to transparency at the edges.

Dithering is a technique to fake some form of OIT transparency where *blending* is required. We can argue that in the hair example, blending isn't really required as much, we just want smoothing of the edges. The hair strands themselves aren't transparent. Where dithering does shine is in situations where we want to emulate some form of true transparency throughout the mesh/texture plane/etc.

Slide 8 of the NVIDIA slides show what were trying to solve:
2h9
*(notice how the entirety of the facial hair has alpha throughout, not just the edges)*

Many of those techniques do look nice - and it could be nice to experiment with a few of them. It's hard to grasp through the paper however how well they work for texture transparency though - the examples I see are all technical visualizations of the noise or seem to deal with shadows. I'd love to see some real case examples where alpha transparency is simulated outside of shadows.

As for the benefit of the hashing function:
> Is there a particular benefit in this use case to its guarantee of stability? The main benefit listed in this paper is that its stability works well for TAA, but Godot does not support TAA.

The temporal offsets can still lead to shimmering as you said - which to some people, or for some use cases, is visually worse than the noise generated by the hashing.

I don't believe that its only benefit is its stability for TAA, but it's stability in general - it looks consistent under camera movement.
The temporal offsets is still trying to calculate a 3d camera movement onto a 2d plane. For fast moving games/scenes, the shimmer can be extremely distracting.

Some ideas I got from reading those papers was perhaps pre-dithering transparency masks per texture instead of storing the smooth alpha values.

Some concerns I don't believe I saw addressed either - how does it behave when zooming out or looking from a distance?
Since the precomputed noise is essentially a noise texture, as the camera distance increases I would think that aliasing of some kind would start degrading the quality. Can the textures be mipped well? How do the transitions look?

I have a lot of questions for these techniques! I would love to see more research into them.

At the end of the day though, the dithering functions are actually one of the easier things to do custom implementations for!
If the hashing inst good enough, roll your own! - You can always pass the result afterwards to Alpha2Coverage to get it smoothed - It may even reduce temporal shimmer quite noticeably!

**Comment by reduz** [comment]
Being completely honest, I have the feeling there might be better alternatives to this problem that are not being explored. While for the most part I think this is good, I also adhere to the fact that AlphaHash is mostly a technique devised for TAA which does not make much sense in a forward renderer like the one in Godot.

One alternative I would like to investigate myself for this is alpha slicing and sorting, which should work quite well for hair and other transparent objects (specially two sided ones). On import, faces that intersect each other are cut/sliced and then, before drawing, the index buffer is sorted using a compute shader (this can be enabled when geometry is closer than a given threshold). Aided by depth prepass, results should be as good as the reference image.

File: scene/resources/material.h [hunk 2]
```diff
@@ -235,68 +248,82 @@ class BaseMaterial3D : public Material {
...
 		DISTANCE_FADE_OBJECT_DITHER,
+		DISTANCE_FADE_MAX
 	};
 
 private:
 	union MaterialKey {
+		// parameters values
 		struct {
+			// enums
+			uint64_t texture_filter : TEXTURE_FILTER_MAX;
```
Comment (reduz) [inline scene/resources/material.h:290]: This does not make sense, the idea is making sure the bits cover the amount of values in the enumeration, using max increases the amount of bits significantly.

**Review by reduz — CHANGES_REQUESTED** [review]
I think this can still be merged after rebased, even if we implement other alternatives for improving alpha draw order. Only problem I see is what I mentioned here.

**Comment by marstaik** [comment]
I can rebase this and fix it up, just give me a few days :)

File: scene/resources/material.h (hunk 2 above)
Comment (marstaik) [reply scene/resources/material.h]: It was still technically bounded by the two unit64_t's in the union, but I have updated them to be MAX - 1.

Also, I converted MaterialKey to a struct and used memsets and memcmp's so that its simpler.

**Comment by marstaik** [comment]
Yeah, I would not use Alpha Hash specifically for things like hair. However, it *can* be very good for simulating anti-aliasing for *far away* objects, so I don't think its useless.

File: scene/resources/material.h [hunk 3]
```diff
@@ -284,24 +284,26 @@ class BaseMaterial3D : public Material {
...
-		uint64_t blend_mode : BLEND_MODE_MAX - 1;
-		uint64_t depth_draw_mode : DEPTH_DRAW_MAX - 1;
-		uint64_t cull_mode : CULL_MAX - 1;
+		// enum values
+		uint64_t texture_filter : get_num_bits(TEXTURE_FILTER_MAX - 1);
+		uint64_t detail_uv : get_num_bits(DETAIL_UV_MAX - 1);
+		uint64_t transparency : get_num_bits(TRANSPARENCY_MAX - 1);
+		uint64_t alpha_antialiasing_mode : get_num_bits(ALPHA_ANTIALIASING_MAX - 1);
+		uint64_t shading_mode : get_num_bits(SHADING_MODE_MAX - 1);
+		uint64_t feature_mask : get_num_bits(FEATURE_MAX - 1);
```
Comment (reduz) [inline scene/resources/material.h:293]: this is ok as just FEATURE_MAX since its a bitmask, its how it was originally, the rest are fine

Comment (marstaik) [reply scene/resources/material.h]: fixed

File: servers/rendering/rasterizer_rd/shaders/scene_high_end.glsl [hunk 4]
```diff
@@ -361,6 +361,65 @@ layout(location = 0) out vec4 frag_color;
 
 #endif // RENDER DEPTH
 
+#ifdef ALPHA_HASH_USED
+
+float hash_2d(vec2 p) {
+	return fract(1.0e4 * sin(17.0 * p.x + 0.1 * p.y) *
```
Comment (clayjohn) [inline servers/rendering/rasterizer_rd/shaders/scene_high_end.glsl:367]: I have a feeling this hash function is only going to look nice on NVidia cards. NVidia uses much higher precision for ``sin`` than anyone else. So hashes based on ``sin`` typically have bad artifacts on other cards.

**Review by clayjohn — APPROVED** [review]
I'm accepting for now despite my comment about the hash function. If it turns out to be an issue we can easily drop in a new hash function at any time. Preferably one recommended from this recent paper. http://www.jcgt.org/published/0009/03/02/

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Could you squash commits into one (or more if relevant, but fixups should be melded into the original commit that requires a fixups).

File: servers/rendering/rasterizer_rd/shaders/scene_high_end.glsl (hunk 4 above)
Comment (clayjohn) [reply servers/rendering/rasterizer_rd/shaders/scene_high_end.glsl:367]: I checked this out and it looks fine on my AMD card. So we can forget about this until we see if it actually is an issue on any cards.

**Review by clayjohn — CHANGES_REQUESTED** [review]
Docs need to be added before this is merged. You can generate the shell by running the engine from command line from the root directory of the godot project using the argument ``--doctool .``

**Comment by marstaik** [comment]
Squashed and doc comments added.

**Review by clayjohn — APPROVED** [review]

File: doc/classes/BaseMaterial3D.xml [hunk 5]
```diff
@@ -555,6 +567,15 @@
 		<constant name="BLEND_MODE_MUL" value="3" enum="BlendMode">
 			The color of the object is multiplied by the background.
 		</constant>
+		<constant name="ALPHA_ANTIALIASING_OFF" value="0" enum="AlphaAntiAliasing">
+			Disables Alpha AltiAliasing for the material.
```
Comment (fire) [inline doc/classes/BaseMaterial3D.xml:571]: AltiAliasing > Antialiasing

File: doc/classes/BaseMaterial3D.xml [hunk 6]
```diff
@@ -486,10 +495,13 @@
 		<constant name="TRANSPARENCY_ALPHA_SCISSOR" value="2" enum="Transparency">
 			The material will cut off all values below a threshold, the rest will remain opaque.
 		</constant>
-		<constant name="TRANSPARENCY_ALPHA_DEPTH_PRE_PASS" value="3" enum="Transparency">
+		<constant name="TRANSPARENCY_ALPHA_HASH" value="3" enum="Transparency">
+			The material will cut off all values below a spatially-determinsitic threshold, the rest will remain opaque.
```
Comment (fire) [inline doc/classes/BaseMaterial3D.xml:499]: determinsitic -> deterministic

Comment (marstaik) [reply doc/classes/BaseMaterial3D.xml]: Fixed

File: doc/classes/BaseMaterial3D.xml (hunk 5 above)
Comment (marstaik) [reply doc/classes/BaseMaterial3D.xml]: Fixed

**Comment by marstaik** [comment]
Fixed typos in docs.

**Comment by akien-mga** [comment]
Thanks!

File: scene/resources/material.h [hunk 7]
```diff
@@ -482,6 +512,8 @@ class BaseMaterial3D : public Material {
 	TextureChannel ao_texture_channel;
 	TextureChannel refraction_texture_channel;
 
+	AlphaAntiAliasing alpha_antialiasing_mode;
```
Comment (bruvzg) [inline scene/resources/material.h:515]: Uninitialized variable:
```
scene/resources/material.cpp:1481:6: runtime error: load of value 3200171710, which is not a valid value for type 'BaseMaterial3D::AlphaAntiAliasing'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior scene/resources/material.cpp:1481:6 in
```

**Comment by Calinou** [comment]
@marstaik How does alpha hashing compare to [interleaved gradient noise](https://github.com/godotengine/godot/pull/45326)? Is it still relevant when we have interleaved gradient noise in `master` now?

**Comment by Calinou** [comment]
@marstaik If you're still around, could you give some example values to use for `alpha_antialiasing_edge`? It's not clear which value should be used depending on the use case. I've noticed that using a value lower than `alpha_scissor_threshold` will cause the effective threshold to vary depending on distance from the camera (likely due to texture mipmaps). I assume this is intended to prevent vegetation from becoming too transparent at a distance.

**Comment by marstaik** [comment]
@calinou I haven't touched this in a while, but you can think of the alpha edge value as the width of the transparency *band* around the object that is then marked for msaa. A higher value should give you better visuals, but it also marks more pixels in general for the msaa process, and thus costs more.

If you are familiar with a radial soft brush like in Photoshop, then think of the edge value as the the *band* from the solid center to the faded away edge that disappears. The best possible result would be to mark the entire range of faded pixels for msaa, so they all get blended, but then the area of the circle that needs msaa also goes up drastically, because it's an area (the circumference of the object * "the width" of the edge band).

The alpha scissor is a hard cutoff. If it's 0.5, then any pixels with less than 0.5 transparency are discarded. The alpha edge then starts working *offset* from that edge.

Back to the brush example, if I set the scissor to 0.5 then the the outer half of the blended radius of the brush would completely disappear, as we *scissor* them off. We are then left with pixels of 100 opaqueness to 50 opaqueness, or 0 transparency to 50 transparency, depending on your viewpoint. The alpha edge value then only has those values left to play with to determine the band.

It's incredibly difficult I would think to automatically determine. There are different quality areas to consider (such as wanting very high quality player hair vs random foliage), but there is also input texture issues to consider. The artist dictates how much "edge" there is to work with depending on how fast they decided to fade the values to zero. IE did they step the alpha down by 10 percent every pixel, meaning a gradient of 10 pixels from opaqueness to fully transparent, or by 1 percent, meaning 100 pixels of "edge". That in addition to personal preference then determines how much you need to blend your edge to look acceptable.

**Comment by marstaik** [comment]
Also, as comes with a few years down the line hindsight, it might be better to have a boolean toggle to make alpha edge relative to alpha scissor (and default it to on) so that it is *scaled* by the alpha scissor and much more intuitive.

IE if the scissor is 0.5 and there are only half as many pixels, then instead of being additive we can remap the alpha edge [0,1] range onto [0, .5]
