### PR TITLE
GDScript function definition and get_node shortcut syntax highlighting

### LINKED ISSUE #11554: Syntax highlight for the $ get node synatax.
Currently when using $ to get a node, the node's name is highlighted with the default syntax highlighting, which can make it inconsistent with default node names

The word after the $ should have its own color to differentiate it from other things in the code.

### LINKED ISSUE #16284: Syntax highlighting for paths using the $ get_node shortcut is wrong
**Godot version:** 3.0

**Issue description:** Using $ to get a node path where the node name is a variable, such as name, causes the syntax colouring to screw up.

**Steps to reproduce:** make a child called "name" and type $name.

image

I struggled to name the title appropriately, feel free to change it so that it makes more sense.

### PR DESCRIPTION
**Pull request by Paulb23**
This PR starts to add the initial GDScript use cases into the `GDScriptSyntaxHighlighter` separating it from the default.

Firstly function definitions which are mentioned in #17873

Secondly the `get_node` `$` shortcut: 
closes #16284
closes #11554

### CODE REVIEW

File: modules/gdscript/gdscript_highlighter.cpp [hunk 1]
```diff
@@ -294,6 +304,12 @@ void GDScriptSyntaxHighlighter::_update_cache() {
 	function_color = text_editor->get_color("function_color");
 	number_color = text_editor->get_color("number_color");
 	member_color = text_editor->get_color("member_variable_color");
+
+#ifdef TOOLS_ENABLED
```
Comment (akien-mga) [inline modules/gdscript/gdscript_highlighter.cpp]: Do we need to compile any SyntaxHighlighter when tools are disabled?

File: editor/editor_settings.cpp [hunk 2]
```diff
@@ -583,6 +583,9 @@ void EditorSettings::_load_default_text_editor_theme() {
 	_initial_set("text_editor/highlighting/word_highlighted_color", Color(0.8, 0.9, 0.9, 0.15));
 	_initial_set("text_editor/highlighting/search_result_color", Color(0.05, 0.25, 0.05, 1));
 	_initial_set("text_editor/highlighting/search_result_border_color", Color(0.1, 0.45, 0.1, 1));
+
+	// GDScript highlighter
+	_initial_set("text_editor/highlighting/GDScript/function_definition_color", Color::html("#01e1ff"));
```
Comment (akien-mga) [inline editor/editor_settings.cpp]: I'm not sure about using uppercase letters in parameter names, we haven't done it so far so it's maybe better to stick to snake_case.

File: editor/editor_settings.cpp [hunk 3]
```diff
@@ -619,6 +622,9 @@ bool EditorSettings::_save_text_editor_theme(String p_file) {
 	cf->set_value(theme_section, "search_result_color", ((Color)get("text_editor/highlighting/search_result_color")).to_html());
 	cf->set_value(theme_section, "search_result_border_color", ((Color)get("text_editor/highlighting/search_result_border_color")).to_html());
 
+	//GDScript highlighter
+	cf->set_value(theme_section, "GDScript/function_definition_color", ((Color)get("text_editor/highlighting/GDScript/function_definition_color")).to_html());
```
Comment (akien-mga) [inline editor/editor_settings.cpp]: Maybe it should be made possible for SyntaxHighlighters to register such options themselves, so that it can be done also for other languages which are added as GDNative modules.

Comment (Paulb23) [reply editor/editor_settings.cpp]: Yeah I've been thinking about this but can't arrive at a decent solution. It would need both adding here and under `editor_themes.cpp` for light / dark theme switching.

File: modules/gdscript/gdscript_highlighter.cpp (hunk 1 above)
Comment (Paulb23) [reply modules/gdscript/gdscript_highlighter.cpp]: I guess not. It's only created when tools are enabled. I'll update with it excluded from scons.

**Comment by Paulb23** [comment]
Moved `gdscript_highlighter` into a `editor` subdirectory and updated the `SCsub` to only include this folder on tool builds. 

Lower cased the settings path.

File: editor/editor_settings.cpp (hunk 3 above)
Comment (vnen) [reply editor/editor_settings.cpp]: While this would be a nice addition, I think it's out of scope of this PR. I believe it'll need a bit of a refactor for EditorSettings to allow modules registering settings in a timely manner.

**Comment by reduz** [comment]
What's the status on this?

**Comment by Paulb23** [comment]
It's complete.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by MarianoGnu** [comment]
do you mind an screenshot?
