### PR TITLE
Display an error message in autoload settings when autoload name is invalid

### LINKED ISSUE #52631: Autoload settings don't tell why an autoload can't be added when name is invalid
### Godot version

4.0-dev (c7455d9d4284958d3ffed716ae4c7e192fb1a573)

### System information

Any

### Issue description

The Autoload tab in the Project Settings disables the "Add" button when the autoload name is invalid (e.g. when it has invalid characters), but it does not tell **why** it is disabled.

autoload-disabled-feedback

It should have a tooltip or maybe an error message in the dialog itself telling the reason the name is incorrect. The messages already exist in the code but they are ignored in this case. While it might be obvious in some cases, like when invalid characters are added, it might be quite confusing when the name is invalid because it conflicts with an engine class.

### Steps to reproduce

1. Create an empty scene or script to use as autoload.
1. Open Project Settings dialog.
1. Select the Autoload tab.
1. In the "Path" field, select the scene or script create earlier.
1. In the "Node Name" field, type an invalid name (e.g. "Test+", invalid since "+" isn't allowed in identifier).
1. Note the "Add" button is disabled as soon as "+" is typed but there's no information why it's invalid.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jmb462**
Fixes #52631

### Issue

In autoload settings window, when autoload name was invalid, "Add" button was disabled without any further information about the reason.

### Fix Proposal

Add a label under the linedit.
The label is shown only if name is invalid (and not empty).
The label contains the reason of invalidity.

### What it looks like

error_messages

### CODE REVIEW

File: editor/editor_autoload_settings.cpp [hunk 1]
```diff
@@ -828,6 +836,12 @@ EditorAutoloadSettings::EditorAutoloadSettings() {
 	HBoxContainer *hbc = memnew(HBoxContainer);
 	add_child(hbc);
 
+	error_message = memnew(Label);
```
Comment (mhilbrunner) [inline editor/editor_autoload_settings.cpp:839]: Does that need a `memdelete`?

File: editor/editor_autoload_settings.cpp [hunk 2]
```diff
@@ -64,15 +64,20 @@ void EditorAutoloadSettings::_notification(int p_what) {
 bool EditorAutoloadSettings::_autoload_name_is_valid(const String &p_name, String *r_error) {
 	if (!p_name.is_valid_identifier()) {
 		if (r_error) {
-			*r_error = TTR("Invalid name.") + "\n" + TTR("Valid characters:") + " a-z, A-Z, 0-9 or _";
+			*r_error = TTR("Invalid name.") + " ";
+			if (p_name.size() > 0 && p_name.left(1).is_numeric()) {
+				*r_error += TTR("Can not begin with a digit.");
```
Comment (akien-mga) [inline editor/editor_autoload_settings.cpp:69]:
```suggestion
				*r_error += TTR("Cannot begin with a digit.");
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
