### PR TITLE
Check renderer type when setting 3D upscaling mode.

### LINKED ISSUE #109991: `EXC_BAD_ACCESS` when changing MetalFX scale with Compatibility
### Tested versions

- Reproducible in 4.4.1
- Reproducible in 4.5 beta 5

### System information

Godot v4.4.1.stable - macOS Sequoia (15.6.1) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Apple M4 Pro - Apple M4 Pro (14 threads)

### Issue description

I get a `EXC_BAD_ACCESS` crash when changing the `rendering/scaling_3d/scale` property in project settings when using Compatibility with MetalFX (Spatial):

``` C++
return driver->has_feature(p_feature);
```

I haven't worked with Xcode in over a decade, but I see this when I try and get info on `driver`... I think it's null?

```
Printing description of this->driver:
(RenderingDeviceDriver *) driver = <parent is NULL>
```

Here's the call stack:

```
#0	0x0000000105899d38 in RenderingDevice::has_feature at /Users/allen/godot-dev/godot-src/servers/rendering/rendering_device.cpp:7337
#1	0x000000010587bd04 in RendererViewport::_configure_3d_render_buffers at /Users/allen/godot-dev/godot-src/servers/rendering/renderer_viewport.cpp:161
#2	0x00000001058817f8 in RendererViewport::viewport_set_scaling_3d_scale at /Users/allen/godot-dev/godot-src/servers/rendering/renderer_viewport.cpp:1029
#3	0x00000001059b3ba0 in RenderingServerDefault::viewport_set_scaling_3d_scale at /Users/allen/godot-dev/godot-src/servers/rendering/rendering_server_default.h:708
#4	0x0000000103c6d710 in Viewport::set_scaling_3d_scale at /Users/allen/godot-dev/godot-src/scene/main/viewport.cpp:4870
#5	0x00000001036a2b68 in Node3DEditorViewport::_project_settings_changed at /Users/allen/godot-dev/godot-src/editor/scene/3d/node_3d_editor_plugin.cpp:3018
#6	0x00000001036eb51c in call_with_variant_args_helper<Node3DEditorViewport> at /Users/allen/godot-dev/godot-src/core/variant/binder_common.h:223
#7	0x00000001036eb474 in call_with_variant_args<Node3DEditorViewport> at /Users/allen/godot-dev/godot-src/core/variant/binder_common.h:337
#8	0x00000001036eb334 in CallableCustomMethodPointer<Node3DEditorViewport, void>::call at /Users/allen/godot-dev/godot-src/core/object/callable_method_pointer.h:103
#9	0x0000000106482780 in Callable::callp at /Users/allen/godot-dev/godot-src/core/variant/callable.cpp:57
#10	0x000000010686edf8 in Object::emit_signalp at /Users/allen/godot-dev/godot-src/core/object/object.cpp:1294
#11	0x00000001005a40a4 in Object::emit_signal<> at /Users/allen/godot-dev/godot-src/core/object/object.h:941
#12	0x000000010691928c in ProjectSettings::_emit_changed at /Users/allen/godot-dev/godot-src/core/config/project_settings.cpp:536
#13	0x000000010692d2f8 in call_with_variant_args_helper<ProjectSettings> at /Users/allen/godot-dev/godot-src/core/variant/binder_common.h:223
#14	0x000000010692d250 in call_with_variant_args<ProjectSettings> at /Users/allen/godot-dev/godot-src/core/variant/binder_common.h:337
#15	0x000000010692d110 in CallableCustomMethodPointer<ProjectSettings, void>::call at /Users/allen/godot-dev/godot-src/core/object/callable_method_pointer.h:103
#16	0x0000000106482780 in Callable::callp at /Users/allen/godot-dev/godot-src/core/variant/callable.cpp:57
#17	0x0000000106865198 in CallQueue::_call_function at /Users/allen/godot-dev/godot-src/core/object/message_queue.cpp:220
#18	0x000000010686559c in CallQueue::flush at /Users/allen/godot-dev/godot-src/core/object/message_queue.cpp:268
#19	0x0000000103c1b974 in SceneTree::process at /Users/allen/godot-dev/godot-src/scene/main/scene_tree.cpp:702
#20	0x00000001005cfc04 in Main::iteration at /Users/allen/godot-dev/godot-src/main/main.cpp:4802
#21	0x0000000100500530 in invocation function for block in OS_MacOS_NSApp::start_main() at /Users/allen/godot-dev/godot-src/platform/macos/os_macos.mm:1102
#22	0x0000000186a85ed8 in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#23	0x0000000186a85dc0 in __CFRunLoopDoObservers ()
#24	0x0000000186a854d0 in __CFRunLoopRun ()
#25	0x0000000186a84a98 in CFRunLoopRunSpecific ()
#26	0x000000019252727c in RunCurrentEventLoopInMode ()
#27	0x000000019252a4e8 in ReceiveNextEventCommon ()
#28	0x00000001926b5484 in _BlockUntilNextEventMatchingListInModeWithFilter ()
#29	0x000000018a9a9a34 in _DPSNextEvent ()
#30	0x000000018b348940 in -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] ()
#31	0x000000018a99cbe4 in -[NSApplication run] ()
#32	0x00000001005001e8 in OS_MacOS_NSApp::run at /Users/allen/godot-dev/godot-src/platform/macos/os_macos.mm:1056
#33	0x0000000100576674 in main at /Users/allen/godot-dev/godot-src/platform/macos/godot_main_macos.mm:126
#34	0x00000001865fab98 in start ()
```

### Steps to reproduce

- Create a project with Compatibility rendering method
- Set `rendering/scaling_3d/mode.macos` to MetalFX (Spatial)
- Adjust `rendering/scaling_3d/scale`
- Crash

### Minimal reproduction project (MRP)

[metal-fx-compatibility-crash.zip](https://github.com/user-attachments/files/21992683/metal-fx-compatibility-crash.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/109991

### CODE REVIEW

File: servers/rendering/renderer_viewport.cpp [hunk 1]
```diff
@@ -145,6 +145,11 @@ void RendererViewport::_configure_3d_render_buffers(Viewport *p_viewport) {
 				scaling_3d_mode = RS::VIEWPORT_SCALING_3D_MODE_OFF;
 			}
 
+			if (scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_OFF && OS::get_singleton()->get_current_rendering_method() == "gl_compatibility") {
```
Comment (clayjohn) [inline servers/rendering/renderer_viewport.cpp]: I think compatibility supports bilinear

Comment (bruvzg) [reply servers/rendering/renderer_viewport.cpp]: Seems like it is supported, changed it to fall back to bilinear.

**Review by clayjohn — APPROVED** [review]
Looks great to me!

File: servers/rendering/renderer_viewport.cpp [hunk 2]
```diff
@@ -145,6 +145,12 @@ void RendererViewport::_configure_3d_render_buffers(Viewport *p_viewport) {
 				scaling_3d_mode = RS::VIEWPORT_SCALING_3D_MODE_OFF;
 			}
 
+			if (scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_OFF && scaling_3d_mode != RS::VIEWPORT_SCALING_3D_MODE_BILINEAR && OS::get_singleton()->get_current_rendering_method() == "gl_compatibility") {
+				scaling_3d_mode = RS::VIEWPORT_SCALING_3D_MODE_BILINEAR;
+				scaling_type = RS::scaling_3d_mode_type(scaling_3d_mode);
+				WARN_PRINT_ONCE("MetalFX and FSR upscaling are not supported by compatibility renderer. Falling back to bilinear scaling.");
```
Comment (Calinou) [inline servers/rendering/renderer_viewport.cpp]:
```suggestion
				WARN_PRINT_ONCE("MetalFX and FSR upscaling are not supported in the Compatibility renderer. Falling back to bilinear scaling.");
```

**Comment by allenwp** [comment]
In my initial bug report I mentioned that this happens in 4.4.1 and the latest 4.5 beta. I see this has cherry pick to 4.4, but I have not tested if this happens on earlier versions. It's possible this bug also exists in 4.3 and earlier, if these versions also support MetalFX (Spatial) upscaling(?)

**Comment by bruvzg** [comment]
> It's possible this bug also exists in 4.3 and earlier, if these versions also support MetalFX (Spatial) upscaling(?)

No, Metal support was added in 4.4.

**Comment by Repiteo** [comment]
Thanks!
