### PR TITLE
[RTL] Add option to scroll follow visible characters.

### LINKED ISSUE #104722: RichText text scroll doesn't work properly when set to follow the text after shaping it
### Tested versions

This happened in version 4.4-stable.
I tested and replicated in:
- 4.1-stable
- 4.4.1-stable

### System information

Godot v4.4.1.stable.mono - Windows 11 (build 22631) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.6636) - 12th Gen Intel(R) Core(TM) i5-12600K (16 threads)

### Issue description

I’m trying to create a dialog box using a RichText label. The main reason is to be able to be sure that each line appears properly without jumping a word from one line to the next if it doesn’t fit. I do that by setting “Visible Characters Behavior” to “Characters After Shaping”. I want to use this in conjunction the “Visible Ratio”, starting it at 0 and then using a tween to show the message. To let the text scroll as the text starts appearing I also enable the “Scroll Following”.

The problem arises when I see that the text starts already scrolled to the bottom, making like the text is always hidden, until it reaches the last sentence.

Image

I tried setting the scroll value to 0 in GDScript, and also using the method scroll_to_line(). They do scroll to the start of the text, but making this somehow makes the auto scrolling not work. Notice how the scroll jumps back to the top here;

Image

Of couse, if I set the “Visible Characters Behaviour” back to "“Characters Before Shaping”, the scroll works correctly and starts from the beginning, but as I mentioned, the sentence’s words jump from one line to the next if they don’t fit.

Image

### Steps to reproduce

1) To recreate this behavior, first create a RichText node.
2) Add some text in the inspector or assign it in code. Long enough to have multiple lines.
3) Set the "Visible Characters Behavior" to "Characters After Shaping"
4) Set the "Visible Ratio" to 0
5) Enable "Scroll Following"
6) Set a tween to move the visible ratio to 1

```gdscript 
var read_text_animation = create_tween()
read_text_animation.set_parallel(true)
read_text_animation.tween_property(%RichText, "visible_ratio", 1, 4)
```

### Minimal reproduction project (MRP)

[RichText.zip](https://github.com/user-attachments/files/19504846/RichText.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/104722 (as a separate `scroll_follow_visible_characters` property).

https://github.com/user-attachments/assets/bde050ac-bd2c-4329-a41e-c45d06386038

Note: while it is a new property, it is implementing behavior (in a more consistent way) that was a side effect of old inconsistent before-shaping mode behavior that was relied on in some cases (fixed in https://github.com/godotengine/godot/pull/107373), so should be considered for 4.5,

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -5019,6 +5022,30 @@ bool RichTextLabel::is_scroll_following() const {
 	return scroll_follow;
 }
 
+void RichTextLabel::_update_follow_vc() {
+	if (scroll_follow_visible_characters) {
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp]: Can be early return instead.

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/rich_text_label.cpp [hunk 2]
```diff
@@ -5019,6 +5022,30 @@ bool RichTextLabel::is_scroll_following() const {
...
+		int vc = visible_characters < 0 ? get_total_character_count() - 1 : (MIN(visible_characters, get_total_character_count()) - 1);
```
Comment (AThousandShips) [inline scene/gui/rich_text_label.cpp]:
```suggestion
		int vc = visible_characters < 0 ? get_total_character_count() - 1 : MIN(visible_characters, get_total_character_count()) - 1;
```
or
```suggestion
		int vc = visible_characters < 0 ? (get_total_character_count() - 1) : (MIN(visible_characters, get_total_character_count()) - 1);
```
or
```suggestion
		int vc = (visible_characters < 0 ? get_total_character_count() : MIN(visible_characters, get_total_character_count())) - 1;
```
The current parentheses are confusing

**Review by AThousandShips — APPROVED** [review]

File: doc/classes/RichTextLabel.xml [hunk 3]
```diff
@@ -729,6 +729,9 @@
 		<member name="scroll_following" type="bool" setter="set_scroll_follow" getter="is_scroll_following" default="false">
 			If [code]true[/code], the window scrolls down to display new content automatically.
 		</member>
+		<member name="scroll_following_visible_characters" type="bool" setter="set_scroll_follow_visible_characters" getter="is_scroll_following_visible_characters" default="false">
+			If [code]true[/code], the window scrolls to display last visible line when [member visible_characters] or [member visible_ratio] is changed.
```
Comment (AThousandShips) [inline doc/classes/RichTextLabel.xml]:
```suggestion
			If [code]true[/code], the window scrolls to display the last visible line when [member visible_characters] or [member visible_ratio] is changed.
```

**Comment by Repiteo** [comment]
Thanks!
