### PR TITLE
[Web] Fix PWA callback assignment causing crash in sandboxed iframes

### LINKED ISSUE #98068: Service Worker Error in Sandboxed Iframe Prevents Game Execution in Web Build
### Tested versions
- v4.3.stable.official [77dcf97d8]
- Godot_v4.2.1-stable

### System information

Micorosft Edge, Google Chrome, Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6590) - Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 Threads)

### Issue description

This bug is reproducible in `Microsoft Edge`, `Google Chrome`, and `Brave`, however even though the error occurs in `Firefox` the game is still able to start

## Issue Description

When running a Godot project in a sandboxed iframe, the game fails to execute due to a service worker error. Specifically, the `navigator.serviceWorker` property is inaccessible because the iframe context lacks the allow-same-origin flag. This occurs in the `godot_js_pwa_cb` function within `os_web.cpp`, where serviceWorker is called regardless of sandbox restrictions.

## Expected Behavior

The project should be able to run in a sandboxed iframe without requiring service worker access when pwa is disabled. Ideally, the code should detect sandboxed environments and disable service worker registration accordingly, bypassing this check when the allow-same-origin flag is missing.

# Error information
```
SecurityError: Failed to read the 'serviceWorker' property from 'Navigator': Service worker is disabled because the context is sandboxed and lacks the 'allow-same-origin' flag.
    at _godot_js_pwa_cb (godot-game.js:22:16)
    at 086f3c36:0x9e8d7
    at 086f3c36:0xc94a5
    at godot-game.js:9:12428
    at Object.callMain (godot-game.js:519:3863)
    at godot-game.js:1311:27
    at new Promise (<anonymous>)
    at godot-game.js:1306:13
 ```
 
 ## Relevant Code
 
 In `platform/web/os_web.cpp:274`:
 ```cpp
 // ...
 OS_Web::OS_Web() {
    // ...
    godot_js_pwa_cb(&OS_Web::update_pwa_state_callback);
    // ...
}
```

In `platform/web/js/libs/library_godot_os.js:445`
```js
godot_js_pwa_cb: function (p_update_cb) {
		if ('serviceWorker' in navigator) {
			const cb = GodotRuntime.get_func(p_update_cb);
			navigator.serviceWorker.getRegistration().then(GodotPWA.updateState.bind(null, cb));
		}
	},
```

## Suggested Solutions

- ~~Update godot_js_pwa_cb to detect sandboxed iframes and bypass service worker registration. This would allow Godot projects to run in more restrictive iframe environments~~ (edit: You can't detect if it's in a sanboxed iframe because that throws another security error)
or
- Surround the problem code with a try catch

### Steps to reproduce

# Steps to Reproduce

- Build a Godot project targeting HTML5.

- Embed the generated HTML5 project in an iframe with the `sandbox` attribute set, without including `allow-same-origin`. For example:

```html
<iframe src="path/to/godot-project/index.html" sandbox="allow-scripts"></iframe>
```

- Attempt to load the page containing the iframe.

### Minimal reproduction project (MRP)

[godot-iframe-test-main.zip](https://github.com/user-attachments/files/17331751/godot-iframe-test-main.zip)

or

   ```bash
   git clone https://github.com/thedinosoar/godot-iframe-test.git
```

## Note ❗: 

This happens with ANY godot project exported for the web, and can be alternatively tested using this html:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>IFrame Testing</title>
    <meta charset="UTF-8" />
  </head>
  <body>
    <iframe
      title="Example"
      src="<path to your godot.html>"
      sandbox="allow-scripts"
    ></iframe>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by keegabit**
Pull Request: Fix Service Worker Error in Sandboxed Iframe (#98068)
# Summary

This PR addresses the issue where the service worker callback fails in a sandboxed iframe, preventing the execution of Godot web builds. The solution introduces error handling for the service worker registration process, ensuring that any SecurityError or other exceptions are caught and logged appropriately without breaking the application.
Changes Made

- Error Handling: Wrapped the service worker registration calls in try-catch blocks to gracefully handle potential errors.
  - In the `godot_js_pwa_cb` function:
            Implemented a try-catch to manage errors during the assignment of the PWA callback. This prevents the application from crashing and logs any failures to the console.
  - In the `godot_js_pwa_update` function:
            Added a try-catch block around the service worker update logic to catch any errors and log them appropriately.
            
### Testing

Tested using https://github.com/thedinosoar/godot-iframe-test.git

* *Bugsquad edit, fixes: #98068*

### CODE REVIEW

File: platform/web/js/libs/library_godot_os.js [hunk 1]
```diff
@@ -233,7 +233,7 @@ const GodotOS = {
 		'GodotOS._fs_sync_promise = Promise.resolve();',
 	].join(''),
 	$GodotOS: {
-		request_quit: function () {},
+		request_quit: function () { },
```
Comment (Faless) [inline platform/web/js/libs/library_godot_os.js:236]:
```suggestion
		request_quit: function () {},
```

File: platform/web/js/libs/library_godot_os.js [hunk 2]
```diff
@@ -441,21 +441,30 @@ const GodotPWA = {
 	godot_js_pwa_cb__sig: 'vi',
 	godot_js_pwa_cb: function (p_update_cb) {
 		if ('serviceWorker' in navigator) {
-			const cb = GodotRuntime.get_func(p_update_cb);
-			navigator.serviceWorker.getRegistration().then(GodotPWA.updateState.bind(null, cb));
+			try {
+				const cb = GodotRuntime.get_func(p_update_cb);
+				navigator.serviceWorker.getRegistration().then(GodotPWA.updateState.bind(null, cb));
+			} catch (e) {
+				console.error('Failed to assign PWA callback', e); // eslint-disable-line no-console
```
Comment (Faless) [inline platform/web/js/libs/library_godot_os.js:448]:
```suggestion
				GodotRuntime.error('Failed to assign PWA callback', e);
```

File: platform/web/js/libs/library_godot_os.js [hunk 3]
```diff
@@ -441,21 +441,30 @@ const GodotPWA = {
...
-			});
+			try {
+				navigator.serviceWorker.getRegistration().then(function (reg) {
+					if (!reg || !reg.waiting) {
+						return;
+					}
+					reg.waiting.postMessage('update');
+				});
+			} catch (e) {
+				console.error(e); // eslint-disable-line no-console
```
Comment (Faless) [inline platform/web/js/libs/library_godot_os.js:465]:
```suggestion
				GodotRuntime.error(e);
```

**Review by Faless — CHANGES_REQUESTED** [review]
We should also update the `installServiceWorker` function in `platform/web/js/engine/engine.js` and the `navigator.serviceWorker` access from `misc/dist/html/full-size.html` and `misc/dist/html/editor.html` to properly cover all cases where this error can occur.

**Comment by thedinosoar** [comment]
> We should also update the `installServiceWorker` function in `platform/web/js/engine/engine.js` and the `navigator.serviceWorker` access from `misc/dist/html/full-size.html` and `misc/dist/html/editor.html` to properly cover all cases where this error can occur.

I thought about updating those as well, but aren't those only called if the app is a pwa? Which would mean these functions I am updating would have needed to be successfully called before those do.

**Comment by Faless** [comment]
> Which would mean these functions I am updating would have needed to be successfully called before those do.

Those functions are only called if the export is a threaded build, and the relevant headers are missing, so you probably didn't notice them.



> Also inside full-size.html, navigator.serviceWorker is inside of a promise which already catches any errors that would be thrown

Not it isn't, it's inside an array constructor, which is evaluated before the promise gets created. You can easily test that with the following snippet (which you'll notice will throw the error even if the resulting promise has a catch):

```
var opt = null; Promise.race([opt.lol]).catch(e => {/* noop */})
```

**Comment by thedinosoar** [comment]
> Not it isn't, it's inside an array constructor, which is evaluated before the promise gets created. You can easily test that with the following snippet (which you'll notice will throw the error even if the resulting promise has a catch):
> 

Ahh I see that now, I will fix that. I appreciate the constructive feedback!

**Comment by adamscott** [comment]
I don't understand how it can be an issue when we explicitly test if `serviceWorker` is in `navigator`.

```js
if ('serviceWorker' in navigator) {
}
```

**Comment by thedinosoar** [comment]
> I don't understand how it can be an issue when we explicitly test if `serviceWorker` is in `navigator`.

The issue isn't that 'serviceWorker' is not in navigator, it's that you cannot access it outside of a secure context (like a sandboxed iframe). The issue #98068 details that

**Review by adamscott — APPROVED** [review]
Looks good!

**Review by Faless — APPROVED** [review]
LGTM

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
