### PR TITLE
Fixes a crash on linux regarding scene tabs

### LINKED ISSUE #13085: Latest master crashes on editor closing (Regression from f8e8b7d)
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 - 90e37d5

**Issue description:**

Expected: not this
Happened: this
```
ERROR: operator[]: FATAL: Indexp_index=-1 out of size (size()=0)
   At: core/vector.h:146.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x34920) [0x7f369d6a5920] (??:0)
[2] Vector<Tabs::Tab>::operator[](int) const (/home/noshyaar/git/godot/0/core/vector.h:146 (discriminator 7))
[3] Tabs::get_tab_rect(int) const (/home/noshyaar/git/godot/0/scene/gui/tabs.cpp:792)
[4] EditorNode::_update_scene_tabs() (/home/noshyaar/git/godot/0/editor/editor_node.cpp:160 (discriminator 1))
[5] EditorNode::_notification(int) (/home/noshyaar/git/godot/0/editor/editor_node.cpp:369)
[6] EditorNode::_notificationv(int, bool) (/home/noshyaar/git/godot/0/editor/editor_node.h:95 (discriminator 14))
[7] Object::notification(int, bool) (/home/noshyaar/git/godot/0/core/object.cpp:851)
[8] Node::_propagate_exit_tree() (/home/noshyaar/git/godot/0/scene/main/node.cpp:280)
[9] Node::_propagate_exit_tree() (/home/noshyaar/git/godot/0/scene/main/node.cpp:266 (discriminator 2))
[10] Node::_set_tree(SceneTree*) (/home/noshyaar/git/godot/0/scene/main/node.cpp:2566)
[11] SceneTree::finish() (/home/noshyaar/git/godot/0/scene/main/scene_tree.cpp:578)
[12] OS_X11::run() (/home/noshyaar/git/godot/0/platform/x11/os_x11.cpp:2140)
[13] godot(main+0xd5) [0xe4eccf] (/home/noshyaar/git/godot/0/platform/x11/godot_x11.cpp:55)
[14] /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f369d691f6a] (??:0)
[15] godot(_start+0x2a) [0xe4eb3a] (??:?)
-- END OF BACKTRACE --
zsh: abort (core dumped)  godot -e
```

Bisecting underway...

**Steps to reproduce:**
1. open editor
2. close editor

### PR DESCRIPTION
**Pull request by kitbdev**
This should fix #13085
I haven't tested it on Linux but it adds a check to catch the index error from _update_scene_tabs.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -157,7 +157,10 @@ void EditorNode::_update_scene_tabs() {
 			tabbar_container->remove_child(scene_tab_add);
 			scene_tabs->add_child(scene_tab_add);
 		}
-		Rect2 last_tab = scene_tabs->get_tab_rect(scene_tabs->get_tab_count() - 1);
+		Rect2 last_tab = Rect2(Point2(0,0), Size2(0,0));
```
Comment (Noshyaar) [inline editor/editor_node.cpp]: I think simply `Rect2()` works as well.

**Comment by akien-mga** [comment]
Would be nice if you could use a bit more verbose commit logs (doesn't have to be super verbose, but "Fix crash in _update_scene_tabs" would already be nicer to read in the changelog).

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -157,7 +157,10 @@ void EditorNode::_update_scene_tabs() {
 			tabbar_container->remove_child(scene_tab_add);
 			scene_tabs->add_child(scene_tab_add);
 		}
-		Rect2 last_tab = scene_tabs->get_tab_rect(scene_tabs->get_tab_count() - 1);
+		Rect2 last_tab = Rect2();
+		if (scene_tabs->get_tab_count() != 0)
+			last_tab = scene_tabs->get_tab_rect(scene_tabs->get_tab_count() - 1);
+
```
Comment (Noshyaar) [inline editor/editor_node.cpp]: Please remove whitespaces on this line

**Comment by akien-mga** [comment]
I don't see why it would be Linux specific btw :)

**Comment by ianb96** [comment]
me neither, but it wasn't happening on Windows. Something happened where there were 0 scene tabs open, not even an empty one on Linux when closing.
