### PR TITLE
Only update `EditorSceneTabs` tabs when necessary

### LINKED ISSUE #81513: Switching scene tabs with many tabs may hide tabs
### Godot version

4.2 dev4

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you have many tabs opened and they are overflowing with the < > buttons, when you switch scene tab it may hide some tabs in specific circumstances:

https://github.com/godotengine/godot/assets/2223172/e5904497-6e3f-48af-815a-3a156ca15018

I'd expect that simply switching to another tab has no effect on visibility.

### Steps to reproduce

1. Open many scene tabs
2. Repeat what I did on the video
May depend on tab names and window size.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by kitbdev**
Fixes resizing rebuilds all tabs
Fixes updating scene unsaved state (basically every action) rebuilds all tabs
Fixes #81513
Fixes this TODO in editor_scene_tabs
> // TODO: This REALLY should be done in a better way than replacing all tabs after almost EVERY action.

`update_scene_tabs` now resizes its tabs only if it needs to, instead of always clearing and adding one by one.
added `_update_tab_titles` - updates the titles and icons of tabs. If the tab already has those values, it will not redraw.
added `_scene_tabs_resized` - repositions the add button. Used when resizing.

This could be optimized further by updating only the affected tab.

Needs testing on Mac to make sure the global menu works as expected. Particularly that it updates its name based on saved/unsaved state and that reordering tabs doesn't break it.

### CODE REVIEW

File: editor/gui/editor_scene_tabs.cpp [hunk 1]
```diff
@@ -190,59 +190,87 @@ void EditorSceneTabs::_disable_menu_option_if(int p_option, bool p_condition) {
...
+		_update_tab_titles();
+		return;
+	}
 
 	if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_GLOBAL_MENU)) {
 		DisplayServer::get_singleton()->global_menu_clear("_dock");
 	}
 
+	// Workaround to ignore the tab_changed signal.
+	scene_tabs->disconnect("tab_changed", callable_mp(this, &EditorSceneTabs::_scene_tab_changed));
```
Comment (KoBeWi) [inline editor/gui/editor_scene_tabs.cpp:206]: Since you are moving this code anyway, it can be changed to use `set_block_signals()` instead of disconnecting.

**Review by KoBeWi — APPROVED** [review]
Did some quick testing and seems to work correctly

**Comment by kitbdev** [comment]
updated to use `set_block_signals` and moved an if statement out of a for loop.

**Review by YuriSizov — APPROVED** [review]
Looks pretty great! Some lines related to global menus could probably be spread across multiple lines for readability, but that's not important right now.

**Comment by YuriSizov** [comment]
Thanks!
