### PR TITLE
Process events during splash on macOS only.

### LINKED ISSUE #115246: Very long application launch delay on Wayland - Compatibility Renderer
### Tested versions

- Reproducible: v4.6.rc2.official [78c6632eb]
- Not reproducible: v4.6.rc1.official [481f36ed2], v4.6.dev6.official [dec5a373d], v4.5.stable.official [876b29033]

### System information

Godot v4.6.rc2 - Fedora Linux 43 (KDE Plasma Desktop Edition) on Wayland - X11 display driver, Multi-window, 3 monitors - OpenGL 3 (Compatibility) - Mesa Intel(R) Iris(R) Xe Graphics (TGL GT2) - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 threads) - 62.52 GiB memory

### Issue description

Launching the game with Wayland as the display server increases the start time of the application.

What happens is that the boot splash screen lingers for **over a few seconds**, before the game is shown. All game logic (`_process` and `_physics_process`) does run in the background while the splash screen is visible - so the game runs, just there is a long delay before the splash is cleared.

It even happens when trying to launch a project with a totally empty scene. It happens both in the editor and an exported game. It happens only on the Compatibility renderer, doesn't happen on Mobile or Forward+.

Disabling the splash image doesn't have an impact on this behaviour. Without the image just an empty window is shown for the same amount of time.

This started happening in 4.6 rc2. Previous version behave as expected, where the game shows immediately.

### Steps to reproduce

1. Create new project using the Compatibility renderer.
2. Set the project to use Wayland as Display Server.
3. Make sure to disable embedded window (to make sure the game launches in a Wayland Window).
4. Launch game.

### Minimal reproduction project (MRP)

[launch-test.zip](https://github.com/user-attachments/files/24789890/launch-test.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/115246

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -4725,6 +4725,7 @@ int Main::start() {
 
 	GDExtensionManager::get_singleton()->startup();
 
+#ifdef MACOS_ENABLED
```
Comment (akien-mga) [inline main/main.cpp:4728]: This warrants a comment to clarify why it's useful on macOS and (so far) not proven useful on other platforms.

Comment (bruvzg) [reply main/main.cpp:4728]: Added a note.

**Review by akien-mga — APPROVED** [review]
