### PR TITLE
Fix non-embedded tooltips, popups and dialogs resizing to match Viewport content scale factors != 1.0

### LINKED ISSUE #44942: PopupPanel doesn't resize properly
**Godot version:**
3.2.4.beta4

**Issue description:**
When having a label with autowrap inside of a PopupPanel and changing the content of the label the PopupPanel doesn't resize accordingly.
Creating a new label in the script and adding it as a child node resizes the PopupPanel as expected.

For example:
Peek 2021-01-05 17-00
The PanelContainer on the top left has the same content as the PopupPanel which is created by the custom tooltip for the button in the middle.

**Steps to reproduce:**
1. Create a PopupPanel
2. Create a VBoxContainer
3. Add a label inside the vbox, enable autowrap
4. Create a script to change the text of the label in the ready function 

**Minimal reproduction project:**
[testpopuppanel.zip](https://github.com/godotengine/godot/files/5771414/testpopuppanel.zip)

### LINKED ISSUE #89482: Vertical scrollbar is visible in all popup menus when using a custom display scale
### Tested versions

v4.3.dev.custom_build [da945ce62]

Wasn't happening in 4.2.1

### System information

Godot v4.3.dev (da945ce62) - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

It's like this in every popup menu:

image<br>

**_EDIT: Correction, this has nothing to do with a theme, this is with no theme:_**

image

### Steps to reproduce

~~Use [this theme](https://github.com/passivestar/godot-minimal-theme) with 4.3~~

~~This might be mac-specific because I asked another person and found out that it's not happening on windows~~

Open 4.3 and set custom display scale to 1.6

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Koyper**
Required for fixes to https://github.com/godotengine/godot/issues/69749, https://github.com/godotengine/godot/issues/69171, and for fixes to the issues in https://github.com/godotengine/godot/issues/54030 when `embed_subwindows` is _disabled_.
Probably fixes https://github.com/godotengine/godot/issues/44942.
*Bugsquad edit:* Fixes #89482.

This will not relate directly to a fix for the blurry subwindows issue, but might help with the eventual solution for that.

This fix causes the `PopupPanel` children to correctly resize to fit the popup when the containing `Viewport.content_scale_factor` is changed. Without this fix, the children would expand outside the popup bounds if the scale factor was greater than 1.0, or shrivel if less than 1.0.

This fix is required for several separate PR's I will post, the first of which is to make tooltips scale to match the main viewport scale factor when the project `embed_subwindows` is _disabled_.

Implementation is slightly different depending on whether the popup is embedded or not. If embedded, the popup will scale simply by changing the viewport content scale factor, if the popup is _not_ embedded, i.e., using a floating system window, the popup content scale factor should be set to match the containing viewport's content scale factor. If this is done, the rendering will be correct (non-blurry).

The fixes below show the properly scaled tooltip that will be in a separate PR.

BEFORE FIX:

https://github.com/godotengine/godot/assets/33969780/9fe32aea-61b7-406b-b244-d8d152ead21e

ALSO BEFORE FIX - Note the tooltip scale stuck at 1.0

https://github.com/godotengine/godot/assets/33969780/6dac280f-a519-4db4-b3cd-1852507fb054

AFTER FIX:

https://github.com/godotengine/godot/assets/33969780/b0a11615-84f1-4226-9283-b87cc8ada48f

https://github.com/godotengine/godot/assets/33969780/3c692787-618e-4614-9220-bcc816abc3ed

### CODE REVIEW

File: scene/gui/popup.cpp [hunk 1]
```diff
@@ -247,7 +247,9 @@ void PopupPanel::_update_child_rects() {
 
 		if (c == panel) {
 			c->set_position(Vector2());
-			c->set_size(get_size());
+			Vector2 panel_size = Vector2(get_size()) / this->get_content_scale_factor();
```
Comment (AThousandShips) [inline scene/gui/popup.cpp:250]:
```suggestion
			Vector2 panel_size = get_size() / this->get_content_scale_factor();
```
No need to cast `Vector2` to `Vector2`

Comment (Koyper) [reply scene/gui/popup.cpp:250]: `get_size()` on `Window` returns `Size2i`, so the divide winds up truncating the float into an int. Is there a more elegant way to handle this?

Comment (AThousandShips) [reply scene/gui/popup.cpp:250]: Oh yes my bad, thought it was a `Control`, this is the correct way 🙂

Comment (Koyper) [reply scene/gui/popup.cpp:250]: Okay, good.

File: scene/gui/popup.cpp [hunk 2]
```diff
@@ -233,7 +233,7 @@ Size2 PopupPanel::_get_contents_minimum_size() const {
 
 void PopupPanel::_update_child_rects() {
 	Vector2 cpos(theme_cache.panel_style->get_offset());
-	Vector2 csize(get_size() - theme_cache.panel_style->get_minimum_size());
+	Vector2 csize; // There must always be `panel`, so safe to set csize below.
```
Comment (Sauermann) [inline scene/gui/popup.cpp:236]: Is the assumption guaranteed, that "panel" is the first Control-child?
In cases, where "panel" is not the first child, the loop below can lead to unexpected results, since the size of Control nodes can be set, without the initialization of ´csize`.

The user can change the order of child nodes and can interfere with this assumption.
I believe, that it would be more robust, to initialize `csize` before the for-loop.

Comment (Koyper) [reply scene/gui/popup.cpp:236]: Well-reasoned. I made the assumption that "panel" would always remain as the first child, not considering that the user could change the order. Is it safe to assume "panel" cannot be removed altogether?

Comment (Sauermann) [reply scene/gui/popup.cpp:236]: Users removing internal nodes ... sounds like a recipe for disaster.
While these cases should not be expected, if a crash can be prevented with a simple `!= null` check, I believe, that it should be included.

Comment (KoBeWi) [reply scene/gui/popup.cpp:236]: `panel` is an internal child, so user has no access to it unless they want to purposefully break the node. It can't be done by accident.

Comment (Koyper) [reply scene/gui/popup.cpp]: I made the suggested change to set `csize` correctly, regardless of `panel` child index. Per KoBeWi and that I believe it is standard practice to not protect internal nodes, I did not add a `null` or `is_instance_valid` check. There are many warnings in the docs about bad consequences of deleting internal nodes, but those are usually exposed.

**Comment by Koyper** [comment]
I have a related question regarding PR best practices: I've finished modifications to the remaining classes that did not respond correctly to `content_scale_factor` values other than 1.0. Should I post a separate PR for each of these or do them as a group in a single PR? The files modified are tree.cpp, popup_menu.cpp and dialog.cpp. Thanks!

**Comment by akien-mga** [comment]
If it's the same bug in different related classes, I would suggest fixing all of them in the same PR (so they could be added to this one, expanding its scope a bit).

**Comment by Koyper** [comment]
> If it's the same bug in different related classes, I would suggest fixing all of them in the same PR (so they could be added to this one, expanding its scope a bit). I'd go as far as suggesting to make the changes in a single commit (so amend this PR's commit with the similar changes to other Control classes).

So what about https://github.com/godotengine/godot/pull/86556 that would otherwise be included in this new group? Should I amend this PR with those changes and then close that PR?

**Comment by akien-mga** [comment]
Yeah I think that would make sense. Fix all those related issues with one fell swoop.

**Comment by Koyper** [comment]
I've amended this commit to add all the related changes required to implement proper scaling of non-embedded windows when `Viewport.content_scale_factor` is not equal to 1.0.

This includes tooltips, `PopupPanel`, `PopupMenu`, `Tree`, `ConfirmationDialog` and `AcceptDialog`.

File: scene/main/viewport.cpp [hunk 3]
```diff
@@ -1527,17 +1529,22 @@ void Viewport::_gui_show_tooltip() {
 
 	tooltip_owner->add_child(gui.tooltip_popup);
 
+	Window *window = gui.tooltip_popup->get_parent_visible_window();
```
Comment (Sauermann) [inline scene/main/viewport.cpp:1532]: In the case that `gui.tooltip_popup` is embedded, it is possible, that its embedder is not the parent visible window.

Can you please try:
```suggestion
	Window *window = gui.tooltip_popup->get_embedder();
	if (window == null) {
		window = ui.tooltip_popup->get_parent_visible_window();
	}
```

Comment (Koyper) [reply scene/main/viewport.cpp]: Change made - thanks!

**Comment by scgm0** [comment]
How's the progress of this PR?The problem of blurry sub-windows is really annoying...

**Comment by Koyper** [comment]
I'll have to take care of the conflicts with a rebase, but other than that the PR is ready to merge, pending approvals, which I've been awaiting for a while.

I've tested it for MacOS and Windows and all is working correctly for me (I've been using it continuously since the PR was posted)

I should get to the rebase within a few days...

**Comment by Koyper** [comment]
Ok, ready for review after fixing some issues with `PopupMenu` created by the removal of the internal margin container by #87462.

File: scene/gui/dialogs.cpp [hunk 4]
```diff
@@ -202,7 +202,7 @@ void AcceptDialog::register_text_enter(LineEdit *p_line_edit) {
 }
 
 void AcceptDialog::_update_child_rects() {
-	Size2 dlg_size = get_size();
+	Size2 dlg_size = Vector2(get_size()) / this->get_content_scale_factor(); // get_size() is Size2i hence the cast to Vector2.
```
Comment (KoBeWi) [inline scene/gui/dialogs.cpp:205]:
```suggestion
	Size2 dlg_size = Vector2(get_size()) / get_content_scale_factor();
```
`this` is unnecessary and the comment is somewhat obvious.

File: scene/gui/popup.cpp [hunk 5]
```diff
@@ -232,7 +232,8 @@ Size2 PopupPanel::_get_contents_minimum_size() const {
 
 void PopupPanel::_update_child_rects() {
 	Vector2 cpos(theme_cache.panel_style->get_offset());
-	Vector2 csize(get_size() - theme_cache.panel_style->get_minimum_size());
+	Vector2 panel_size = Vector2(get_size()) / this->get_content_scale_factor();
```
Comment (KoBeWi) [inline scene/gui/popup.cpp:235]:
```suggestion
	Vector2 panel_size = Vector2(get_size()) / get_content_scale_factor();
```
Same.

File: scene/gui/tree.cpp [hunk 6]
```diff
@@ -3995,12 +3995,14 @@ bool Tree::edit_selected(bool p_force_edit) {
...
 	}
 
+	float popup_scale = popup_editor->is_embedded() ? 1.0 : popup_editor->get_parent_visible_window()->get_content_scale_factor();
 	Rect2 rect;
 	if (select_mode == SELECT_ROW) {
 		rect = s->get_meta("__focus_col_" + itos(selected_col));
 	} else {
 		rect = s->get_meta("__focus_rect");
 	}
+	rect.position = rect.position * popup_scale;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:4005]:
```suggestion
	rect.position *= popup_scale;
```

File: scene/main/viewport.cpp [hunk 7]
```diff
@@ -1469,17 +1471,25 @@ void Viewport::_gui_show_tooltip() {
 
 	tooltip_owner->add_child(gui.tooltip_popup);
 
+	Window *window = Object::cast_to<Window>(gui.tooltip_popup->get_embedder());
+	if (window == NULL) { // Is NULL if the Window is NOT embedded.
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:1475]:
```suggestion
	if (window == nullptr) { // Is NULL if the Window is NOT embedded.
```

File: scene/main/viewport.cpp [hunk 8]
```diff
@@ -1461,6 +1461,8 @@ void Viewport::_gui_show_tooltip() {
 	panel->set_flag(Window::FLAG_NO_FOCUS, true);
 	panel->set_flag(Window::FLAG_POPUP, false);
 	panel->set_flag(Window::FLAG_MOUSE_PASSTHROUGH, true);
+	panel->set_flag(Window::FLAG_TRANSPARENT, true);
+	// A non-embedded tooltip window will only be transparent if per_pixel_transparency is allowed in the main Viewport.
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:1465]: This comment should be above the flag change.
Is this related to what this PR fixes though?

File: scene/main/viewport.cpp [hunk 9]
```diff
@@ -1469,17 +1471,25 @@ void Viewport::_gui_show_tooltip() {
...
 	tooltip_owner->add_child(gui.tooltip_popup);
 
+	Window *window = Object::cast_to<Window>(gui.tooltip_popup->get_embedder());
+	if (window == NULL) { // Is NULL if the Window is NOT embedded.
+		window = gui.tooltip_popup->get_parent_visible_window();
+	}
+	float win_scale = window->content_scale_factor;
 	Point2 tooltip_offset = GLOBAL_GET("display/mouse_cursor/tooltip_position_offset");
+	if (!gui.tooltip_popup->is_embedded()) {
+		tooltip_offset = tooltip_offset * win_scale;
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:1481]:
```suggestion
		tooltip_offset *= win_scale;
```

File: scene/main/viewport.cpp [hunk 10]
```diff
@@ -1469,17 +1471,25 @@ void Viewport::_gui_show_tooltip() {
...
 	Rect2 r(gui.tooltip_pos + tooltip_offset, gui.tooltip_popup->get_contents_minimum_size());
-	r.size = r.size.min(panel->get_max_size());
-
-	Window *window = gui.tooltip_popup->get_parent_visible_window();
 	Rect2i vr;
 	if (gui.tooltip_popup->is_embedded()) {
 		vr = gui.tooltip_popup->get_embedder()->get_visible_rect();
 	} else {
+		panel->content_scale_factor = win_scale;
+		r.size = r.size * win_scale;
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:1489]:
```suggestion
		r.size *= win_scale;
```

**Review by KoBeWi — APPROVED** [review]
I did some testing and it appears to be working correctly.
The code looks fine (aside from the style comments I left), but someone could double-check the viewport changes.

File: scene/main/viewport.cpp (hunk 7 above)
Comment (akien-mga) [reply scene/main/viewport.cpp:1475]: Or just
```suggestion
	if (!window ) { // Not embedded.
```

File: scene/main/viewport.cpp (hunk 8 above)
Comment (Koyper) [reply scene/main/viewport.cpp:1465]: It's true that the PR would work fine without this, but you could not have transparent backgrounds in the non-embedded tooltips. Should I remove this and at some point do a separate PR as a bug-fix?

My sense is that because this PR makes non-embedded tooltips workable (because you couldn't use them previously for projects on HiDPI displays), no one would have come accross this bug.

**Comment by Koyper** [comment]
Thanks for the comments! I've made the suggested changes, and for now left in the transparency flag fix, but can remove if recommended.

**Comment by akien-mga** [comment]
Thanks!

File: scene/main/viewport.cpp (hunk 8 above)
Comment (akien-mga) [reply scene/main/viewport.cpp:1464]: This seems to have caused a regression where editor tooltips are transparent unexpectedly: https://github.com/godotengine/godot/issues/92712#issuecomment-2261752610

Comment (bruvzg) [reply scene/main/viewport.cpp:1464]: > A non-embedded tooltip window will only be transparent if per_pixel_transparency is allowed in the main Viewport.

It's allowed in the project settings not for a Viewport, and only affect requested surface format on window creation, but nothing prevents GPU driver from always using surface with alpha channel. And seems like Windows DisplayServer do not have any additional checks (unlike X11 and macOS) and will try to enable it regardless of project settings.
