### PR TITLE
[3.x] Add ability to mute AudioServer.

### LINKED ISSUE #28039: Godot prevents automatic sleeping due to the audio system
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:** 3.1

**OS/device including version:** Mac OSX 10.14

**Issue description:** 
The godot editor is preventing Mac's from automatically sleeping, according to the activity monitor.

Screen Shot 2019-04-14 at 7 45 14 PM

**Steps to reproduce:** Open any godot project.

### LINKED ISSUE #55608: Editor Idle Power Consumption and Sleep Prevention
### Godot version

3.4 Stable

### System information

Windows 11 / Surface Pro 8 / i7 x86_64

### Issue description

Having the editor open but minimised / unfocused eats up 1-2 hours of battery life. Cause seems to be continuous use of `Windows Audio Device Graph Isolation`. `Desktop Window Manager` usage is also much higher than when the editor is closed.

image

This can also be seen by running `powercfg /requests` in the terminal.

```
SYSTEM:
[DRIVER] Realtek High Definition Audio(SST) (INTELAUDIO\FUNC_01&VEN_10EC&DEV_0274&SUBSYS_10EC122E&REV_1000\5&1543d6b8&0&0001)
An audio stream is currently in use.
```

Sometimes, but not consistently this also prevents sleep when closing the keyboard cover.

Might be analogous to these issues affecting MacOS:
https://github.com/godotengine/godot/issues/28039
https://github.com/godotengine/godot/issues/38154

Maybe this is a minor issue in the grand scheme of things, but usability is impacted when you have to keep opening and closing a project when you don't expect to work on it for even a hour less you sacrifice some battery!

### Steps to reproduce

Open the editor

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by lawnjelly**
Adds the option to change the audio driver to the Dummy driver and back at runtime, with a set of `MuteState` flags - Disabled (user control), Silence (period of silence), Focus Loss (when app is not in focus), and Paused (when app is paused).

Control for the flags is added for the editor in EditorSettings, and for the project in ProjectSettings.

Editor defaults to muted (Dummy driver) when there is no audio output, and automatically switches to active on output. This significantly reduces CPU usage.

Fixes #28039
Fixes #55608
May help with #38154

## Summary
* Can disable audio processing + driver when running the editor unless sound is being played.
* Will disable audio processing + driver in the project manager.
* Can mute audio on losing focus, or on pause / resume.
* Doesn't load the audio driver unless required in project manager / editor, faster startup / shutdown.
* How the system responds to state flag changes can be changed independently for the Editor (`EditorSettings`) and the running project (in `ProjectSettings`)

mute_proj_settings

mute_editor_settings

## Notes
* I had noticed that with the `vital_updates_only` redraw option, the biggest CPU hog in the editor was now the audio, even when playing no audio it does a significant amount of processing.
* There have been various issues / PRs to reduce audio processing but they haven't amounted to much so far, so I had a first look through the audio today, and decided to have a wild stab at this. I'm not very versed in the audio, and am thus _far_ from expert in this area, so the audio maintainers will have to decide whether this type of approach makes any sense. There are probably potential race conditions etc to contend with. Even if this doesn't prove fruitful I hope to spur the audio maintainers to offer such an option.

* On my system there are two problems:

1) A driver thread which is constantly using CPU
2) This thread using Pulse audio which also sits at 5% usage.

Although we can optimize the audio processing code, ultimately it is in a thread which will keep running in a loop unless something stalls it, so we need to look at either sleeping (or increasing existing sleep, I noticed there is a 1ms sleep on some drivers) or pausing or removing threads if not necessary.

Here I have explored using the option to stop the thread, by allowing swapping the driver on the fly to and from the `DummyAudioDriver`.

* In order to control the muting of the audio, there are a set of `MuteFlags`, which can be toggled at runtime. It will only play the audio when all are unset. The flags are:
1) `Disabled` - A user flag.
2) `Focus Loss` - Set and cleared when the app gains or loses focus.
3) `Paused` - Set when app is paused and resumed.
4) `Silence` - To be set when the audio encounters a section of silence, and automatically restart when sound detected again.

The sensitivity to each of these flags is controlled by a mask and can be either be set in the `Editor` / `ProjectSettings`, or altered at runtime (current defaults: editor is sensitive to all flags, but running projects are only sensitive to the `disabled` and `paused` flag). The idea is that most users will use the default for games, but people making apps might want to override this sensitivity mask.

* In order to turn on and off audio processing, instead of initializing the audio driver once at startup, the `AudioDriverManager` can now be called at runtime to switch between audio drivers, and in this case, the `Dummy` driver (for muted) and the desired driver (for sound on).
* The code required for this so far has been pretty minimal. I don't know to what extent the current driver implementations are safe to use by `init` and `finalizing` multiple times. It seems to work fine so far with Pulse, and Dummy (I had to fix a `nullptr` issue in Dummy).

## Results
With the switch, and the `vital_updates_only` redraw option, my CPU usage (percentages of core, rather than whole CPU):

Audio on : Godot 7%, PulseAudio 5%
Audio off (dummy) : Godot 2%, PulseAudio 0%

This is 1/6 of the CPU usage. The dummy driver actually still creates a thread which does some processing, although this processing is minimized. I did try removing the dummy thread, but it prevented playbacks progressing, so I've avoided that for now.

## Discussion
It has also occurred to me, that given in most cases users might wish to reduce CPU usage in the editor in all areas, we could potentially combine such a setting with the `vital_updates_only` redraw option. This would give one less button. But on the other hand this could be confusing / non obvious.

I've also implemented the approach suggested in https://github.com/godotengine/godot/pull/45948#issuecomment-779236872 . There is a `Silence` flag, which is set when 10 seconds of silence is detected, and cleared when playing the next sound.

Now that the silence flag is implemented and is default in the editor, it no longer seems necessary to have a mute button in the editor. _(Although https://github.com/godotengine/godot-proposals/issues/1066 suggests having the mute button _also_ mute any projects that are run from the editor, so maybe we could have it do that, but could be a later PR.)_

@Calinou has also suggested allowing switching to the mute mode when the editor loses focus, so I've added this.

There is also the possibility to use the `is_audio_processing_allowed()` to throttle processing in `AudioStreamPlayer`s. I haven't done that here to keep the PR as minimal as possible. This would also be different in 4.x (a number of things are different in audio in 4.x I believe, so that would need an independent implementation).

An alternative instead of swapping driver might be to prevent heavy processing on the audio driver thread, and increase the sleep to a large value (say 100ms), while using the same logic from this PR.

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/1066 and partially addresses https://github.com/godotengine/godot/issues/54183.*

### CODE REVIEW

File: servers/audio_server.h [hunk 1]
```diff
@@ -126,19 +126,52 @@ class AudioDriverManager {
 		MAX_DRIVERS = 10
 	};
 
+public:
+	enum DriverMode {
+		// User enables or disables audio, e.g. via button in editor
+		DRIVER_MODE_DISABLED = 1 << 0,
+		// Whether app is in focus
+		DRIVER_MODE_UNFOCUSSED = 1 << 1,
```
Comment (AaronRecord) [inline servers/audio_server.h:134]:
```suggestion
		DRIVER_MODE_UNFOCUSED = 1 << 1,
```

Comment (lawnjelly) [reply servers/audio_server.h:134]: Ah yup indeed that is US (and more common) spelling it looks like! :grin:

**Comment by lawnjelly** [comment]
Marking as ready for review to get some eyes on this. I'm fully expecting a lot of bikeshedding / possible changes to the design, and this will require testing on all platforms.

But it seems well worth doing, as well as throttling CPU in the editor / project manager, it also allows running user apps to play nicely with the OS and turn off audio processing when paused, which may be particularly important on mobile and may be necessary to allow some platforms to suspend.

**Comment by ellenhp** [comment]
I like this approach. Just some background: In 4.x the audio server knows the playback state of almost all audio playback streams. The notable exception is that video players don't use the AudioStreamPlayback API yet, and are still stuck on the old way of registering a callback with the audio server. So if a video player is in the scene, the audio server does not directly know the state of that playback, and therefore doesn't have direct knowledge of whether it can sleep. If a video player is not in the scene, it would be able to choose to sleep whenever there are no playback streams currently playing, or after 10s of that being true, etc.

I like the idea of using an indirect way of determining whether sleeping is possible, though. A video player's audio callback may or may not choose to push samples to the AudioServer depending on its pause state, but if it _does_ want to push samples it will need to do so by requesting a pointer to that buffer via `thread_get_channel_mix_buffer`. It hadn't occurred to me to do this and I think it accounts for every way that audio playback can occur in Godot.

**Comment by Calinou** [comment]
> But it seems well worth doing, as well as throttling CPU in the editor / project manager, it also allows running user apps to play nicely with the OS and turn off audio processing when paused, which may be particularly important on mobile and may be necessary to allow some platforms to suspend.

Another upside of doing this is that the editor will no longer constantly display a "playing audio" icon in the KDE task bar:

image

**Comment by lawnjelly** [comment]
> Edit: this should also allow this to be backported potentially to 3.6+ which is kind of cool. I don't see anything in here that's specific to 4.0 after a brief review.

This is actually currently written on 3.x and I'm happy to forward port once we have tested out / bikeshedded a bit, as you say most of the code is shared.

The main question in my mind is whether the approach of hot swapping drivers is viable on all platforms. If not we could alternatively use more sleeps on some platforms, or an option to pause the audio driver if this exists on a platform, or simply turn off the functionality if problematic on a certain platform.

My instincts are that hot swapping the driver _should_ be okay, as it should be the same to the OS as just loading a new app using the audio driver. But I am no expert here. :grin:

**Comment by lawnjelly** [comment]
Just to note I'm happy to rebase this and port for 4.x.

We did discuss in a PR meeting last year but at the time @reduz wasn't convinced of the use case (or implementation, not sure which was the blocker). On the other hand it is especially relevant given the increased use of Godot editor on mobile where battery saving is important, and the needs of Mac users who want their machines to sleep.

**Comment by Calinou** [comment]
> We did discuss in a PR meeting last year but at the time @reduz wasn't convinced of the use case (or implementation, not sure which was the blocker). On the other hand it is especially relevant given the increased use of Godot editor on mobile where battery saving is important, and the needs of Mac users who want their machines to sleep.

This is definitely something we need in the long term, not only for Godot itself but also for non-game applications that only play sound occasionally. (Some games may also do this, such as idle/incremental games.)

**Comment by Koyper** [comment]
Can we add a milestone to this PR? Is there an outstanding concern that needs to be addressed that prevented merging previously?

**Comment by AThousandShips** [comment]
It has a milestone? It's on 3.x, which is where 3.x targeting PRs go when they're not ready or approved

**Comment by Koyper** [comment]
I should have been more precise: Can we target 4.x instead? @lawnjelly had generously offered to rebase this for 4.x.

**Comment by AThousandShips** [comment]
Not with this no, it's 3.x code, it needs a dedicated 4.x PR

**Comment by Koyper** [comment]
I've searched around quite a bit for solutions to sleep blocking and audio driver energy consumption, but have not found another PR like this one that provides a way to toggle the audio server during runtime. Is there another proposal somewhere that addresses these issues?

**Comment by lawnjelly** [comment]
@reduz I've long since forgotten the meeting, but I seem to remember you weren't sure about this at the time.. although I vaguely recall it was based on your original idea I believe of detecting sound output to determine when to throttle down.

Clearly there is some demand for this feature (it gets periodically bumped), both in terms of reducing CPU and not monopolizing audio outputs (which can affect other programs, sleeping on laptops etc), saving battery on mobile etc.

It would be super helpful if you were able to remind your primary concerns, were they e.g.: :thinking: 

* Whether drivers would handle this gracefully on other OSes
* Changes in latency (introduced by driver restart)
* Whether the use case was significant enough to warrant including
* Code complexity
* User friendliness / user facing design

**Comment by Koyper** [comment]
@lawnjelly Thank you for your response!

Has anyone discussed the idea of having a way to play simple system-type alert sounds without requiring the audio server? Talking a quick look for example with MacOS `AudioServicesPlayAlertSound(_:)` and `AudioServicesCreateSystemSoundID(_:_:)` that takes a CFURL as the audio file to play. Not sure about other platforms.

This would allow projects to emit sounds without requiring low-latency audio or even audio busses. Ideally, you could still restart the audio driver when needed per this PR, and pause/stop it otherwise.

I think the laptop sleep blocking is the most important issue to resolve.

**Comment by lawnjelly** [comment]
Rebased and updated comments to 2025 style standard.

File: doc/classes/AudioServer.xml [hunk 2]
```diff
@@ -276,6 +282,13 @@
 				Sets the volume of the bus at index [code]bus_idx[/code] to [code]volume_db[/code].
 			</description>
 		</method>
+		<method name="set_enabled">
+			<return type="void" />
+			<argument index="0" name="enabled" type="bool" />
+			<description>
+				Allows disabling / muting the audio server. As well as muting, this will minimize audio CPU usage.
```
Comment (Calinou) [inline doc/classes/AudioServer.xml]:
```suggestion
				If [code]true[/code], the audio server is enabled and can output or input audio. Setting this to [code]false[/code] will mute audio input/output and minimize audio CPU usage.
```

File: doc/classes/AudioServer.xml [hunk 3]
```diff
@@ -182,6 +182,12 @@
 				If [code]true[/code], the bus at index [code]bus_idx[/code] is in solo mode.
 			</description>
 		</method>
+		<method name="is_enabled" qualifiers="const">
+			<return type="bool" />
+			<description>
+				If [code]false[/code], the audio server is disabled / muted.
```
Comment (Calinou) [inline doc/classes/AudioServer.xml]:
```suggestion
				If [code]false[/code], the audio server is disabled/muted.
```

File: doc/classes/ProjectSettings.xml [hunk 4]
```diff
@@ -301,6 +301,19 @@
...
+			[b]Note:[/b] The driver can be enabled and disabled at runtime using the [method AudioServer.set_enabled] function.
+		</member>
+		<member name="audio/muting/mute_on_focus_loss" type="bool" setter="" getter="" default="false">
+			If [code]true[/code], the current audio driver will be automatically disabled when the application loses focus, and re-enabled when the application regains focus.
+		</member>
+		<member name="audio/muting/mute_on_pause" type="bool" setter="" getter="" default="true">
+			If [code]true[/code], the current audio driver will be automatically disabled when the application is paused by the OS, and re-enabled when the application is resumed.
+		</member>
+		<member name="audio/muting/mute_on_silence" type="bool" setter="" getter="" default="false">
+			If [code]true[/code], the current audio driver will be automatically disabled after a period of silence is detected, and re-enabled when audio attempts to play.
```
Comment (Calinou) [inline doc/classes/ProjectSettings.xml]:
```suggestion
			If [code]true[/code], the current audio driver will be automatically disabled after a period of silence is detected, and re-enabled when audio attempts to play. This may result in temporarily higher audio latency when audio restarts after being muted.
```

File: doc/classes/ProjectSettings.xml [hunk 5]
```diff
@@ -301,6 +301,19 @@
...
 		</member>
+		<member name="audio/muting/mute_driver" type="bool" setter="" getter="" default="false">
+			If [code]true[/code], the current audio driver will be disabled, minimizing CPU usage. This will affect both audio output and input.
+			[b]Note:[/b] The driver can be enabled and disabled at runtime using the [method AudioServer.set_enabled] function.
+		</member>
+		<member name="audio/muting/mute_on_focus_loss" type="bool" setter="" getter="" default="false">
+			If [code]true[/code], the current audio driver will be automatically disabled when the application loses focus, and re-enabled when the application regains focus.
+		</member>
+		<member name="audio/muting/mute_on_pause" type="bool" setter="" getter="" default="true">
+			If [code]true[/code], the current audio driver will be automatically disabled when the application is paused by the OS, and re-enabled when the application is resumed.
```
Comment (Calinou) [inline doc/classes/ProjectSettings.xml:312]:
```suggestion
			If [code]true[/code], the current audio driver will be automatically disabled when the application is paused by the OS, and re-enabled when the application is resumed.
			[b]Note:[/b] This only affects platforms where the OS can pause applications (typically Android and iOS). This does not refer to in-game pausing, where you can manually mute audio by calling [method AudioServer.set_enabled].
```

**Review by Calinou — APPROVED** [review]
Tested locally on Linux and macOS, it works as expected. Code looks good to me.

On Linux, I can't really spot a noticeable difference in CPU utilization on my 9950X3D with a debug build of 3.x. It's pretty low already (it oscillates between 0% and 1.9%, likely because of filesystem scanning).

On macOS 15.5 on a M4 Max, CPU utilization when the editor is on an empty Script tab (and unfocused) drops from 4.8% to 3.5% with this PR. I didn't have time to do extended battery drain tests yet.

I like the "mute on focus loss" ability, since it's pretty common to see in games. This makes this PR address https://github.com/godotengine/godot-proposals/issues/3693 for 3.x.

Some feedback:

- Since we have both `set_enabled()` and `is_enabled()` in AudioServer, we can expose an `enabled` property that would use those setter/getter methods.

**Comment by lawnjelly** [comment]
For others also be sure to check the CPU usage of your audio driver.
Also checking release mode is probably more apt, as other Godot stuff will change relative importance in release.
On my old machine Pulse audio goes from 6% to 0%, so the CPU usage may not appear under the Godot process.

On my new desktop:
Godot Engine v3.7.dev.custom_build [d164443cd] - X11 - 2 monitors - GLES3 - Mesa Intel(R) Graphics (RPL-S) - 13th Gen Intel(R) Core(TM) i7-13700T (24 threads)

In the editor in release...

_Before PR:_
Godot CPU 2.34% Pulse audio 5.68%
_After PR:_
Godot CPU 1.67% Pulse audio 0%

Bear in mind this effect is magnified significantly on low power PCs and laptops, and mobile.
That's a 5x reduction in overall CPU usage by Godot editor.

Granted there will be some other processes typically running (on mine Cinnamon desktop takes between 0.67 and 1.33% typically) but that's potentially a significant battery saving.

This will become more significant as we further reduce Godot editor CPU usage at idle.

**Comment by Calinou** [comment]
> For others also be sure to check the CPU usage of your audio driver. On my old machine Pulse audio goes from 6% to 0%, so the CPU usage may not appear under the Godot process.

I looked at PipeWire CPU utilization (I'm on Fedora 42), but couldn't really spot a difference before and after.

**Comment by lawnjelly** [comment]
Thanks!

Let's give this a shot in 3.7 dev 1.

This should give us plenty of time to identify any problems, and assess whether similar approach might be worth doing in 4.x at some point.

**Comment by Koyper** [comment]
@lawnjelly Greetings - is this on your radar for porting to 4.6? Have you had a chance to see how different the 4.6 implementation would be compared to this PR? I'm surprised there isn't more interest in muting core audio, since that blocks laptop sleep and an open game will brick your computer even with the laptop closed. Thanks!

See also #76987 and  #99555

**Comment by lawnjelly** [comment]
As I say earlier a couple of times at least this could be forward ported, but there is no point doing any work until it is agreed to be on the roadmap. In Godot we tend to go for agreement on a feature / roadmap _before_ implementation to avoid wasted work.

At the time we discussed it (2022) it was blocked for 4.x, so is outside my control. This is something you could open a proposal for (if there isn't one already), to get popular support, and could be brought up in the 4.x audio meetings.

Additionally given that this has just been merged in 3.7, it might be worth waiting until we get some beta testing in 3.7 dev 1 before making decisions, as we have to find in practice how it works on different platforms in the wild.

**Comment by Koyper** [comment]
Thanks. There is a similar proposal for muting audio that could be expanded to include swapping the audio driver to `DUMMY` per this PR [Godot Proposal #3693](https://github.com/godotengine/godot-proposals/issues/3693). I'll offer that suggestion there. If the interest isn't there, but I want to proceed with an implemention in 4.6, can you advise on what's different in the 4.x `AudioServer` compared to this PR?

**Comment by lawnjelly** [comment]
> If the interest isn't there, but I want to proceed with an implemention in 4.6, can you advise on what's different in the 4.x AudioServer compared to this PR?

The process is generally:
* make a proposal
* if the proposal has popular support, discuss in the relevant team meeting (arranged on rocketchat audio channel), see if the proposal will be accepted by the team
* if accepted make PR 

This is to avoid wasting time developing PRs that won't be merged. Even maintainers have to get green lighted by the relevant team for new features.

I can't really advise on 4.x as I mostly work on 3.x (and I'm not an audio specialist in Godot).

**Comment by Koyper** [comment]
Thanks. I'll see about getting on an audio channel team meeting. Also thanks for your efforts on this PR.
