### PR TITLE
Properly sort projects by name

### LINKED ISSUE #29841: Sorting by name doesn't sort by project names
**Godot version:** 3.1.1 and master

**OS/device including version:** Ubuntu 18.04

**Issue description:**

In the project manager, you can choose to sort projects by name or by last modified. However, sorting by name doesn't actually sort by name - it actually sorts by path. If you have projects A, B, and C, and they are in `x/A`, `y/B`, and `x/C`, then they will be sorted `A`, `C`, `B`.

I can see sorting by path as useful, but it would also be useful to sort by the actual project name. I propose calling the current behavior sorting by "Path" and include a new sorting option that is called "Name" that actually sorts by the project name.

**Steps to reproduce:**

Have multiple projects added and use the sort by name option. Notice it doesn't sort by name.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #29841

Sorting by name and by path are now separate options. Also made it easier to add more sorting options.

### CODE REVIEW

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -1326,26 +1336,21 @@ void ProjectManager::_load_recent_projects() {
...
-		Error cf_err = cf->load(conf);
+		if (filter_option == ProjectListFilter::FILTER_NAME && search_term != "" && item.project_name.findn(search_term) == -1)
+			continue;
 
-		String project_name = TTR("Unnamed Project");
-		if (cf_err == OK && cf->has_section_key("application", "config/name")) {
-			project_name = static_cast<String>(cf->get_value("application", "config/name")).xml_unescape();
+		if (item.config_version > ProjectSettings::CONFIG_VERSION) {
+			// Comes from an incompatible (more recent) Godot version, grey it out
+			item.grayed = true;
```
Comment (aaronfranke) [inline editor/project_manager.cpp]: Note: most of the code in this area looks to be re-organized, but this part seems new. Something to look over before merging.

**Review by aaronfranke — APPROVED** [review]
I can confirm that this is fully functional, and the implementation of passing the enum instead of converting to a boolean looks good. There has been some code re-organization that should be looked at.

File: editor/project_manager.cpp [hunk 2]
```diff
@@ -1280,10 +1278,22 @@ void ProjectManager::_load_recent_projects() {
 
 		String project = _name.get_slice("/", 1);
 		String conf = path.plus_file("project.godot");
-		int config_version = 0; // Assume 0 until we know better
```
Comment (akien-mga) [inline editor/project_manager.cpp]: Why remove the comment?

File: editor/project_manager.cpp [hunk 3]
```diff
@@ -919,28 +919,32 @@ class ProjectDialog : public ConfirmationDialog {
...
 		config_version = p_config_version;
 		last_modified = p_last_modified;
 		favorite = p_favorite;
 		grayed = p_grayed;
-		ordered_latest_modification = p_ordered_latest_modification;
+		filter_order_option = p_filter_order_option;
 	}
 	_FORCE_INLINE_ bool operator<(const ProjectItem &l) const {
-		if (ordered_latest_modification)
+		if (filter_order_option == ProjectListFilter::FILTER_MODIFIED)
```
Comment (akien-mga) [inline editor/project_manager.cpp]: Might be better with a `switch`.

File: editor/project_manager.cpp (hunk 2 above)
Comment (akien-mga) [reply editor/project_manager.cpp]: Well OK, now that it's closer to the code that overrides it, it's fine without comment indeed.

Comment (akien-mga) [reply editor/project_manager.cpp]: I don't see a reason to move this here though, it duplicates the number of file access calls for no real gain. We could also drop the `config_version` member since it's not used in the end (just to the check to grey out).

Comment (KoBeWi) [reply editor/project_manager.cpp]: The problem is that I need to read the project name to sort the projects. Maybe the config files could be stored in structs, so they're not loaded twice?

File: editor/project_manager.cpp (hunk 3 above)
Comment (KoBeWi) [reply editor/project_manager.cpp]: Changed.

File: editor/project_manager.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/project_manager.cpp]: Nevermind, I just removed the second load and added necessary fields to the struct for fetching them earlier.

**Comment by akien-mga** [comment]
Thanks!
