### PR TITLE
Pause audio when game is paused

### LINKED ISSUE #68880: Audio does not stop on pause running project
### Godot version

4.0 beta5

### System information

Windows10, AMD Ryzen 9 3900XT, RTX3070, Vulkan

### Issue description

When audio is being played from an AudioStreamPlayer and the game is started, upon pausing the game from the Editor, the audio keeps playing. This is especially problematic when the audio timing is critical for a game (i.e. Rythm games). The same happens when playing the audio from an Audio Playback Track of an animation player, even though the animation itself pauses and resumes properly, any audio just goes on.

### Steps to reproduce

- Create a new scene
- Add an AudioStreamPlayer and attach some long enough track to it
- Set Audio StreamPlayer to autoplay
- Run the project from the editor
- Pause the project from the editor

### Minimal reproduction project

-

### PR DESCRIPTION
**Pull request by pafuent**
Fixes #68880

Implementation based on #99555

### CODE REVIEW

File: editor/debugger/script_editor_debugger.cpp [hunk 1]
```diff
@@ -445,6 +449,9 @@ void ScriptEditorDebugger::_parse_message(const String &p_msg, uint64_t p_thread
 			EditorDebuggerRemoteObjects *objs = inspector->set_objects(p_data);
 			emit_signal(SNAME("remote_objects_updated"), objs);
 		}
+	} else if (p_msg == "scene:debug_mute_audio") {
+		ERR_FAIL_COND(p_data.is_empty());
+		// This is handled by SceneDebugger, we need to ignore here to not show a WARNING.
```
Comment (YeldhamDev) [inline editor/debugger/script_editor_debugger.cpp:454]: No need to have "WARNING" in all caps, it just draws unnecessary attention. Otherwise, LGTM.

**Review by YeldhamDev — CHANGES_REQUESTED** [review]

**Review by YeldhamDev — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. I've also tested using the mute button while the project is paused and it works correctly (audio isn't being restored after resuming when it shouldn't).

Code looks good to me.

**Comment by Repiteo** [comment]
Thanks!
