### PR TITLE
[4.0] Rename 'PluginConfig' struct to fix lto warnings

### LINKED ISSUE #45179: LTO build failure on master branch with GCC 9.3.0 (warnings in Android/iOS plugin API and ICU codegen)
**Godot version: 4**
**OS:** Ubuntu 20.04.1LTS
**Device:** Dell Inspiron 3580, 64 bits, Intel core i7-8565U 1.80GHz, graphic card AMD Hainan / Mesa Intel UHD Graphics 620 (WHL GT2)

**Issue description:**
Compiled using gcc 9.3.0, scons version 3.1.2.
Building Godot with command:
`$scons platform=linuxbsd -j7` 
produces a normal executable while 
`$scons platform=linuxbsd -j7 use_lto=yes`
causes these errors to appear at linking time:
```
./platform/android/plugin/godot_plugin_config.h:70: warning: type 'struct PluginConfig' violates the C++ One Definition Rule [-Wodr]
   70 | struct PluginConfig {
      | 
./platform/iphone/plugin/godot_plugin_config.h:71: note: a different type is defined in another translation unit
   71 | struct PluginConfig {
      | 
./platform/android/plugin/godot_plugin_config.h:74: note: the first difference of corresponding definitions is field 'last_updated'
   74 |  uint64_t last_updated = 0;
      | 
./platform/iphone/plugin/godot_plugin_config.h:74: note: a field with different name is defined in another translation unit
   74 |  bool supports_targets = false;
      | 
./core/templates/vector.h:218: warning: 'push_back' violates the C++ One Definition Rule [-Wodr]
  218 | bool Vector<T>::push_back(T p_elem) {
      | 
./core/templates/vector.h:218: note: type mismatch in parameter 1
  218 | bool Vector<T>::push_back(T p_elem) {
      | 
./platform/android/plugin/godot_plugin_config.h:70: note: type 'struct PluginConfig' itself violates the C++ One Definition Rule
   70 | struct PluginConfig {
      | 
./platform/iphone/plugin/godot_plugin_config.h:71: note: the incompatible type is defined here
   71 | struct PluginConfig {
      | 
./core/templates/vector.h:218: note: 'push_back' was previously declared here
  218 | bool Vector<T>::push_back(T p_elem) {
      | 
./core/templates/vector.h:218: note: code may be misoptimized unless '-fno-strict-aliasing' is used
thirdparty/icu4c/common/udata.cpp:646: warning: type of 'icudt68_dat' does not match original declaration [-Wlto-type-mismatch]
  646 | extern "C" const DataHeader U_DATA_API U_ICUDATA_ENTRY_POINT;
      | 
./thirdparty/icu4c/icudata.gen.h:10:41: note: 'icudt68_dat' was previously declared here
   10 | extern "C" U_EXPORT const unsigned char U_ICUDATA_ENTRY_POINT[] = {
      |                                         ^
{standard input}: Assembler messages:
{standard input}:16031542: Warning: end of file not at end of a line; newline inserted
{standard input}:16032897: Error: no such instruction: `_znk9sortarrayin23viewportrotationcontrol6axis2dens0_13axis2dcompar'
g++: fatal error: Killed signal terminated program lto1
compilation terminated.
make: *** [/tmp/cc1fV7GU.mk:2: /tmp/godot.linuxbsd.tools.64.DCky7S.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.linuxbsd.tools.64] Error 1
scons: building terminated because of errors.
```

136991559_4904246892979523_1739789317381814575_o

**Steps to reproduce:**
Cloning the current godot master branch and run `$scons platform=linuxbsd -j7 use_lto=yes`

### PR DESCRIPTION
**Pull request by naithar**
Should cover `C++ One Definition Rule` warning for `PluginConfig` struct from: https://github.com/godotengine/godot/issues/45179

Added a prefixes for platform's `PluginConfig` struct and plugin constants to remove possible name collisions.

This changes are already cherry-picked for https://github.com/godotengine/godot/pull/41340

### CODE REVIEW

File: platform/android/plugin/godot_plugin_config.h [hunk 1]
```diff
@@ -35,22 +35,22 @@
 #include "core/io/config_file.h"
 #include "core/string/ustring.h"
 
-static const char *PLUGIN_CONFIG_EXT = ".gdap";
+static const char *ANDROID_PLUGIN_CONFIG_EXT = ".gdap";
```
Comment (akien-mga) [inline platform/android/plugin/godot_plugin_config.h:38]: Maybe those should be class constants so that they're properly namespaced? Then we don't need the suffix.

File: platform/android/export/export.cpp [hunk 2]
```diff
@@ -261,7 +261,7 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 		EditorProgress *ep = nullptr;
 	};
 
-	Vector<PluginConfig> plugins;
+	Vector<AndroidPluginConfig> plugins;
```
Comment (akien-mga) [inline platform/android/export/export.cpp:264]: I think we'd typically use `PluginConfigAndroid` to further specify `PluginConfig` (see `EditorExportPlatformAndroid`).

Which raises the question of whether this shouldn't be made abstract as a `PlatformPluginConfig` interface that each platform can implement, when relevant? Though that's outside the scope of this PR.

**Comment by naithar** [comment]
@akien-mga fixed some of your comments, should be fine now. 
Not sure about shared `PlatformPluginConfig` interface. Maybe we can implement it once more platforms support plugins, but for now I don't think it would give any benefit.

File: platform/android/plugin/godot_plugin_config.h [hunk 3]
```diff
@@ -67,7 +50,24 @@ The `dependencies` section and fields are optional and defined as follow:
 
  See https://github.com/godotengine/godot/issues/38157#issuecomment-618773871
  */
-struct PluginConfig {
+struct PluginConfigAndroid {
+	static const char *PLUGIN_CONFIG_EXT;
```
Comment (akien-mga) [inline platform/android/plugin/godot_plugin_config.h:54]: You should be able to have the values declared inline with C++11 no?

Comment (naithar) [reply platform/android/plugin/godot_plugin_config.h:54]: No, got inline initializer error on compilation, so left it as it is now.

Comment (akien-mga) [reply platform/android/plugin/godot_plugin_config.h:54]: According to https://stackoverflow.com/a/1563906 this may work with `inline` in C++17 (which we use).

Comment (akien-mga) [reply platform/android/plugin/godot_plugin_config.h:54]: Confirmed that it builds fine (with GCC at least):
```diff
diff --git a/platform/android/plugin/godot_plugin_config.h b/platform/android/plugin/godot_plugin_config.h
index 04091b49f7..a2ea42d311 100644
--- a/platform/android/plugin/godot_plugin_config.h
+++ b/platform/android/plugin/godot_plugin_config.h
@@ -51,7 +51,7 @@ The `dependencies` section and fields are optional and defined as follow:
  See https://github.com/godotengine/godot/issues/38157#issuecomment-618773871
  */
 struct PluginConfigAndroid {
-       static const char *PLUGIN_CONFIG_EXT;
+       inline static const char *PLUGIN_CONFIG_EXT = ".gdap";
 
        static const char *CONFIG_SECTION;
        static const char *CONFIG_NAME_KEY;
@@ -84,8 +84,6 @@ struct PluginConfigAndroid {
        Vector<String> custom_maven_repos;
 };
 
-const char *PluginConfigAndroid::PLUGIN_CONFIG_EXT = ".gdap";
-
 const char *PluginConfigAndroid::CONFIG_SECTION = "config";
 const char *PluginConfigAndroid::CONFIG_NAME_KEY = "name";
 const char *PluginConfigAndroid::CONFIG_BINARY_TYPE_KEY = "binary_type";
```

**Review by akien-mga — APPROVED** [review]

**Comment by naithar** [comment]
Fixed. Not sure if `3.2` should get an `inline` change as it gives: `warning: inline variables are a C++17 extension [-Wc++17-extensions]`

**Comment by akien-mga** [comment]
Thanks!

> Not sure if 3.2 should get an inline change as it gives: warning: inline variables are a C++17 extension [-Wc++17-extensions]

Indeed the `3.2` codebase is compiled with C++14 (while the code is mostly C++03 with some C++11 features, but we don't make any extensive use of new features there). So you might have to keep the non-inline version there.
