### PR TITLE
Fix `Scene > Export As...` being incorrectly disabled

### LINKED ISSUE #112894: Scene "Export As..." menu item disabled in master
### Tested versions

Reproducible in commit f00cf63b42975e44c573b589037b45c40a5f84a9 (PR #107652)
Not reproducible in commit 359ef8fc2b771b8cde320a8eb443220fe635c89d (the previous commit)

### System information

macOS Sequoia 15.7

### Issue description

As of PR #107652, the "Export As..." button is grayed out:

Image

### Steps to reproduce

Have a Godot project open with a scene open, click "Scene" in the menu bar, and try to click "Export As..."

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by vaner-org**
Fixes #112894 regression, spotted due to incorrect placement of `SCENE_SET_MAIN_SCENE` among scene menu enums and not among non-menu options. Additionally, renames `SCENE_SET_MAIN_SCENE` to `SCENE_TAB_SET_AS_MAIN_SCENE`.

Actual underlying cause fixed by #112912.

### CODE REVIEW

File: editor/editor_node.h [hunk 1]
```diff
@@ -217,6 +216,7 @@ class EditorNode : public Node {
 		SCENE_TAB_CLOSE,
 		SAVE_AND_RUN,
 		SAVE_AND_RUN_MAIN_SCENE,
+		SCENE_SET_MAIN_SCENE,
```
Comment (KoBeWi) [inline editor/editor_node.h]:
```suggestion
		SCENE_TAB_SET_AS_MAIN_SCENE,
```
More consistent. Also put it below the other scene tab option.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
