### PR TITLE
Fix crash during drag if user queue_free'd the drag preview

### LINKED ISSUE #36724: Project crashes when set_drag_preview() control freed before data dropped
**Godot version:**
3.2 stable
**OS/device including version:**
Windows 10 x64
**Issue description:**
Project crashes without an error, after droping data, if set_drop_preview() Control freed before data dropped.
**Steps to reproduce:**
1. Make Control with implemented get_drag_data()
2. Assign another Control as drag preview using set_drag_preview() in get_drag_data()
3. Free Control using queue_free() before data dropped

**Minimal reproduction project:**
[MRP.zip](https://github.com/godotengine/godot/files/4274837/MRP.zip)

**Note:**
I suppose engine at least should throw an error with description.

### LINKED ISSUE #46335: Change drag preview property cause crash when exported in release mode only
**Godot version:**
3.2.3 official(steam version)

**OS/device including version:**
windows 10 professional

**Issue description:**
Change drag preview property will cause crash on build version( no crash on debug export or in game engine)

**Steps to reproduce:**
1. Add a itemlist and give it a preview
2. Change preview text in gui_input(check whether the preview is exist)
3. Run in godot or export debug version, run well
4. Export non-debug version. crash when drag

Use call_deferred cannot fix the crash
Maybe some relation with[#36724](https://github.com/godotengine/godot/issues/36724)

**Minimal reproduction project:**
[PreviewCrash.zip](https://github.com/godotengine/godot/files/6026612/PreviewCrash.zip)

### PR DESCRIPTION
**Pull request by nmrkr**
Fixes #36724.
*Bugsquad edit:* Resolves #46335

I'm not sure about this one. Maybe this should be considered more of a Request For Comments than a finished solution.

This feels like a band-aid solution to a structural problem. The user creates a control instance in GDScript and the C++ side then takes ownership of said instance, dereferencing and deleting it as it sees fit. The user on the other hand is free to retain a reference to the instance as well and even `queue_free`'ing it, as seen in #36724. This patch protects the C++ side against the latter, but it still potentially leaves the user with a dangling pointer (or whatever the equivalent is in GDScript terms). The effect of which can be seen in #46335.

A better solution would likely involve changes to the API that potentially break existing code. Maybe the control could be duplicated in the `set_drag_preview` call. Maybe `Viewport` shouldn't delete the Control instance. I don't know...

Also, viewport.cpp:1780 has now grown to a magnificent length of 237 columns from an already impressive 194. Is there any kind of general rule when to break the line up?

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1777,7 +1777,7 @@ Control *Viewport::_gui_find_control_at_pos(CanvasItem *p_node, const Point2 &p_
 	matrix.affine_invert();
 
 	//conditions for considering this as a valid control for return
-	if (c->data.mouse_filter != Control::MOUSE_FILTER_IGNORE && c->has_point(matrix.xform(p_global)) && (!gui.drag_preview || (c != gui.drag_preview && !gui.drag_preview->is_a_parent_of(c)))) {
+	if (c->data.mouse_filter != Control::MOUSE_FILTER_IGNORE && c->has_point(matrix.xform(p_global)) && (!gui.drag_preview_id.is_valid() || (c->get_instance_id() != gui.drag_preview_id && !_gui_get_drag_preview()->is_a_parent_of(c)))) {
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:1780]:
```
!_gui_get_drag_preview()->is_a_parent_of(c)
```
^ this looks like it might still crash when `_gui_get_drag_preview()` returns null.

Also I wonder if this condition could be simpler/better formatted, as it's very long.

File: doc/classes/Control.xml [hunk 2]
```diff
@@ -869,7 +869,7 @@
 			<argument index="0" name="control" type="Control">
 			</argument>
 			<description>
-				Shows the given control at the mouse pointer. A good time to call this method is in [method get_drag_data]. The control must not be in the scene tree.
+				Shows the given control at the mouse pointer. A good time to call this method is in [method get_drag_data]. The control must not be in the scene tree. You should not call [method Node.queue_free] on the control, and you should not keep a reference to the control beyond the duration of the drag. It will be deleted automatically after the drag has ended.
```
Comment (KoBeWi) [inline doc/classes/Control.xml:872]: I'd rather write "You should not free the control" or something similar. Besides `queue_free()` a user can use `free()` or `queue_delete()` (from SceneTree).

File: scene/main/viewport.cpp [hunk 3]
```diff
@@ -2453,15 +2457,29 @@ void Viewport::_gui_set_drag_preview(Control *p_base, Control *p_control) {
...
+	gui.drag_preview_id = p_control->get_instance_id();
+}
+
+Control *Viewport::_gui_get_drag_preview() {
+	if (gui.drag_preview_id.is_null()) {
+		return nullptr;
+	} else {
+		Control *drag_preview = Object::cast_to<Control>(ObjectDB::get_instance(gui.drag_preview_id));
+		if (!drag_preview) {
+			ERR_PRINT("Don't call queue_free() on a control set as drag preview.");
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:2478]: Same thing with `queue_free()` as I wrote above.

**Comment by KoBeWi** [comment]
IMO the change is fine. If we have it documented and add proper checks then it's ok as long as the engine won't crash.
Any changes to how the system works could be done in another PR (preceded by a proposal ofc).

File: scene/main/viewport.cpp (hunk 1 above)
Comment (nmrkr) [reply scene/main/viewport.cpp]: Yep, that was an oversight on my part. I have refactored that monstrosity into something more readable.

**Review by RandomShaper — APPROVED** [review]
Looks good. We may consider limiting the check to debug builds, but this is not the kind of check that will hinder performance, so let's go!

**Comment by akien-mga** [comment]
FYI your commit is authored by a different account (@byonoy-dne) and not @nmrkr. Most likely you own both and use different emails for each, but I figured I'd let you know. It's not a problem for Git but the credits will go to @byonoy-dne and not @nmrkr :)

**Comment by nmrkr** [comment]
> FYI your commit is authored by a different account (@byonoy-dne) and not @nmrkr. Most likely you own both and use different emails for each, but I figured I'd let you know. It's not a problem for Git but the credits will go to @byonoy-dne and not @nmrkr :)

That's what happens when you play around with unfamiliar tools and aren't careful -.-

File: scene/main/viewport.cpp [hunk 4]
```diff
@@ -2453,15 +2460,29 @@ void Viewport::_gui_set_drag_preview(Control *p_base, Control *p_control) {
...
+	gui.drag_preview_id = p_control->get_instance_id();
+}
+
+Control *Viewport::_gui_get_drag_preview() {
+	if (gui.drag_preview_id.is_null()) {
+		return nullptr;
+	} else {
+		Control *drag_preview = Object::cast_to<Control>(ObjectDB::get_instance(gui.drag_preview_id));
+		if (!drag_preview) {
+			ERR_PRINT("Don't free a control set as drag preview.");
```
Comment (KoBeWi) [inline scene/main/viewport.cpp:2481]:
```suggestion
			ERR_PRINT("Don't free the control set as drag preview.");
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
This doesn't seem trivial to cherry-pick to `3.2`, would you do a dedicated PR? (Conflicts are easy enough to solve but I'd like to make sure it's tested against `3.2` as fixing the issue too.)

**Comment by nmrkr** [comment]
> This doesn't seem trivial to cherry-pick to `3.2`, would you do a dedicated PR? (Conflicts are easy enough to solve but I'd like to make sure it's tested against `3.2` as fixing the issue too.)

#46471
