### PR TITLE
Corrected GLTFDocument::save_scene from processing a nullptr

### LINKED ISSUE #52816: Executing `GLTFDocument.save_scene` crashes Godot
### Godot version

4.0.dev.custom_build. 87de2e7c4

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
GLTFDocument.new().save_scene(null, ".", ".", 14, -17.5731897354126, null)
```

Godot crashes with backtrace
```
scene/main/node.cpp:887:14: runtime error: member access within null pointer of type 'const struct Node'
scene/main/node.cpp:887:14: runtime error: member access within null pointer of type 'const struct Node'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (87de2e7c4a38b1258d9a554c7f50cdbd8ac825fa)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s(+0x3203960e) [0x563cc1a4860e] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7fbc4b0fe040] (??:0)
[3] StringName::StringName(StringName const&) (??:0)
[4] Node::get_name() const (??:0)
[5] GLTFDocument::_convert_scene_node(Ref<GLTFState>, Node*, Node*, int, int) (??:0)
[6] GLTFDocument::serialize(Ref<GLTFState>, Node*, String const&) (??:0)
[7] GLTFDocument::save_scene(Node*, String const&, String const&, unsigned int, float, Ref<GLTFState>) (??:0)
[8] void call_with_variant_args_ret_helper<__UnexistingClass, Error, Node*, String const&, String const&, unsigned int, float, Ref<GLTFState>, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul>(__UnexistingClass*, Error (__UnexistingClass::*)(Node*, String const&, String const&, unsigned int, float, Ref<GLTFState>), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>) (??:0)
[9] void call_with_variant_args_ret_dv<__UnexistingClass, Error, Node*, String const&, String const&, unsigned int, float, Ref<GLTFState> >(__UnexistingClass*, Error (__UnexistingClass::*)(Node*, String const&, String const&, unsigned int, float, Ref<GLTFState>), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) (??:0)
[10] MethodBindTR<Error, Node*, String const&, String const&, unsigned int, float, Ref<GLTFState> >::call(Object*, Variant const**, int, Callable::CallError&) (??:0)
[11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (??:0)
[12] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (??:0)
[13] Node::_gdvirtual__ready_call() (??:0)
[14] Node::_notification(int) (??:0)
[15] Node::_notificationv(int, bool) (??:0)
[16] CanvasItem::_notificationv(int, bool) (??:0)
[17] Node2D::_notificationv(int, bool) (??:0)
[18] Object::notification(int, bool) (??:0)
[19] Node::_propagate_ready() (??:0)
[20] Node::_propagate_ready() (??:0)
[21] Node::_set_tree(SceneTree*) (??:0)
[22] SceneTree::initialize() (??:0)
[23] OS_LinuxBSD::run() (??:0)
[24] godot4s(main+0x40b) [0x563cc1a460d4] (??:0)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7fbc4b0e5565] (??:0)
[26] godot4s(_start+0x2e) [0x563cc1a45c0e] (??:0)
-- END OF BACKTRACE --
================================================================

```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

None

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by e8newallm**
Fixes #52816

Error was caused by dereferencing of p_node when it's a nullptr.

I have added a check to save_scene to return ERR_INVALID_PARAMETER if p_node is a nullptr.

I am questioning whether or not Node::get_name() should be setup to throw the same error.

### CODE REVIEW

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -6744,6 +6744,10 @@ Error GLTFDocument::_serialize_file(Ref<GLTFState> state, const String p_path) {
 Error GLTFDocument::save_scene(Node *p_node, const String &p_path,
 		const String &p_src_path, uint32_t p_flags,
 		float p_bake_fps, Ref<GLTFState> r_state) {
+	if (p_node == nullptr) {
+		return ERR_INVALID_PARAMETER;
+	}
```
Comment (akien-mga) [inline modules/gltf/gltf_document.cpp:6749]:
```suggestion
	ERR_FAIL_NULL_V(p_node, ERR_INVALID_PARAMETER);
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
