### PR TITLE
[3.x] Android: Update to target API 35, NDK r28, 16kb page size

### LINKED ISSUE #108161: Support for Android SDK 35 for Godot 3.X
### Tested versions

- Reproducible in 3.X branch

### System information

Android

### Issue description

Starting August 31 2025 new apps and app updates must target Android 15 (API level 35) or higher to be submitted to Google Play (source: https://developer.android.com/google/play/requirements/target-sdk).

Master branch already supports SDK 35 with all its perks (e.g., UI behavior changes, https://github.com/godotengine/godot/pull/107742), but the 3.X branch do not support SDK 35 yet. Is there a plan to back-port the master SDK 35 support to 3.X branch?

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by WolfgangSenff**
This simply bumps the required version numbers for the Android codebase for 3.x, so that users can avoid the policy change removals from the Play store slated for August 31.

Tested on only a Pixel 9 XL Pro (don't have any other devices). Should fix https://github.com/godotengine/godot/issues/108161.

### CODE REVIEW

**Comment by WolfgangSenff** [comment]
Note: I followed the changes found at: https://github.com/godotengine/godot/pull/106152/, eliding only the changes that do not seem to apply to the 3.x codebase afaict (XR version update, and the constraintLayout version update).

**Review by syntaxerror247 — CHANGES_REQUESTED** [review]
Needs to apply changes from https://github.com/godotengine/godot/pull/106604

**Comment by WolfgangSenff** [comment]
> Needs to apply changes from #106604

Ahh, good find, thanks! Updated and running, tested AAB export as well and it seems to work exactly as intended now.

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -224,10 +224,10 @@ static const int EXPORT_FORMAT_APK = 0;
 static const int EXPORT_FORMAT_AAB = 1;
 
 static const char *APK_ASSETS_DIRECTORY = "res://android/build/assets";
-static const char *AAB_ASSETS_DIRECTORY = "res://android/build/assetPacks/installTime/src/main/assets";
+static const char *AAB_ASSETS_DIRECTORY = "res://android/build/assetPackInstallTime/src/main/assets";
 
-static const int DEFAULT_MIN_SDK_VERSION = 19; // Should match the value in 'platform/android/java/app/config.gradle#minSdk'
-static const int DEFAULT_TARGET_SDK_VERSION = 34; // Should match the value in 'platform/android/java/app/config.gradle#targetSdk'
+static const int DEFAULT_MIN_SDK_VERSION = 21; // Should match the value in 'platform/android/java/app/config.gradle#minSdk'
```
Comment (syntaxerror247) [inline platform/android/export/export_plugin.cpp]: Why are you updating minsdk version?

Comment (WolfgangSenff) [reply platform/android/export/export_plugin.cpp]: Because there's a warning/error that requires it to be updated as well. I'm forgetting exactly what it was, but I definitely ran into it when attempting these changes.

Comment (WolfgangSenff) [reply platform/android/export/export_plugin.cpp]: I can attempt to swap it back and get the error again if you want. One of the other updates though required 21 as the minimum.

Comment (WolfgangSenff) [reply platform/android/export/export_plugin.cpp]: Okay, attempted to revert that specific change, and the updates to Gradle require a min update to 21. If this is an issue, I can probably try to down-grade the Gradle version to one that works with 19, though I'm not keen on that.

Here's the error when exporting:

```
uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [godot-lib.debug.aar] /my_path/.gradle/caches/8.11.1/transforms/34d71ad94855b735079927627f5ff64c/transformed/jetified-godot-lib.debug/AndroidManifest.xml as the library might be using APIs not available in 19
```

Comment (syntaxerror247) [reply platform/android/export/export_plugin.cpp]: I think it's fine. Devices running API 19 make up just 0.1% (https://composables.com/android-distribution-chart)

**Review by syntaxerror247 — APPROVED** [review]
Looks good! Thanks for the update.

File: platform/android/java/app/config.gradle [hunk 2]
```diff
@@ -1,11 +1,11 @@
...
+    androidGradlePlugin: '8.6.1',
+    compileSdk         : 35,
+    minSdk             : 21, // Also update 'platform/android/export/export_plugin.cpp#DEFAULT_MIN_SDK_VERSION'
+    targetSdk          : 35, // Also update 'platform/android/export/export_plugin.cpp#DEFAULT_TARGET_SDK_VERSION'
+    buildTools         : '35.0.0',
+    kotlinVersion      : '2.1.20',
+    fragmentVersion    : '1.8.6',
     nexusPublishVersion: '1.3.0',
     javaVersion        : JavaVersion.VERSION_17,
     ndkVersion         : '23.2.8568313' // Also update 'platform/android/detect.py#get_ndk_version' when this is updated.
```
Comment (m4gr3d) [inline platform/android/java/app/config.gradle]: The ndk also needs to be updated in order to add support for device with 16kb page.
See https://github.com/godotengine/godot/pull/105611, https://github.com/godotengine/godot/pull/106328, and https://github.com/godotengine/godot/pull/106358.

**Review by m4gr3d — CHANGES_REQUESTED** [review]
The changes in https://github.com/godotengine/godot/pull/108393 should also be picked up.

**Comment by WolfgangSenff** [comment]
I started making the changes for the ndk version and wanted to keep my notes here:

https://github.com/godotengine/godot/pull/105611/files#diff-bd7eca2c1bd3fef206b15a7db387521c06e08916209a8b4b5b607d245dc6c55bR116 leads to a very different file because all these lines are not in, nor are they replacing anything, in the 3.x branch. I don't know if they're necessary, or if these changes only exist because of the 4.x upgrades to the build system, and so aren't needed at all in 3.x, or if I have to update the entire 3.x file. Note I did not also add subprocess as an import because I think that came from 4.x changes only, and for the changes I made with the triple_target_dir, I left the names of the android_arches the same as they are for 3.x, since that isn't a change this should be making, I think, but I did try to properly match them to their relevant arches.

Similarly, some of these changes could not be made because something from 4.x crept in and doesn't exist in 3.x: https://github.com/godotengine/godot/pull/105611/files#diff-6c1cc3a2230de0e0f8d190e6eb907b7b77266df81602a1527c09480e3864fad3R98, but I did a best-guess effort to update for the previous changes in the same file.

I have kept this in two separate commits, one for the NDK/Maven/16KB size updates, one for the general version number bumps. Let me know if I should squash them before this is merged, happy to do so.

File: platform/android/java/app/config.gradle (hunk 2 above)
Comment (WolfgangSenff) [reply platform/android/java/app/config.gradle]: Okay, I believe I've gotten everything that needs to be done in there, but please check again with a harder look, because, per my notes below, there were some changes I wasn't sure on that appeared to be 4.x-only, and I wanted to keep the changes as minimal as possible.

I kept it in a separate commit so you could see these specific changes more easily. Also, I did test all forms of exports and running directly on my device and it seemed to work in all cases, but I have not gotten permission from my team yet to test it on an exported Android build in our internal testing track on Play. If I can get that permission, I will definitely try that as well.

**Review by m4gr3d — APPROVED** [review]
The NDK related changes look good! From my pov, it's fine keeping them in separate commits to make it easy to track the changes, but I'll let @lawnjelly decide whether they should be squashed or not.

Note that https://github.com/godotengine/godot/pull/107998 may also be of interest as it adds the ability to generate native debug symbols file for Android. Though we're still testing whether the generated debug symbols work as expected, so it may be worth to wait until we've confirmed they're working.

**Comment by syntaxerror247** [comment]
Note: Updating the target SDK to 35 enforces edge-to-edge mode by default. This leads to behavior differences between Android 15 and earlier versions. To address this, we should also backport the changes from https://github.com/godotengine/godot/pull/107742

That PR also introduces an export setting to toggle edge-to-edge mode, I'd recommend to not provide that option and keeping it always disabled for 3.x. Enabling it opened a whole can of worms and fixing this for Android 5 and 6 would be really challenging.

**Review by syntaxerror247 — APPROVED** [review]

**Comment by lawnjelly** [comment]
> The NDK related changes look good! From my pov, it's fine keeping them in separate commits to make it easy to track the changes, but I'll let @lawnjelly decide whether they should be squashed or not.

Yeah I'm fine with a couple of commits if they do separate things.

Fix for compile errors would be good to squash though, when you get it working. :+1:

**Comment by WolfgangSenff** [comment]
Okay. I think I've figured out what the issue was, but I'm not sure if I solved it the way you want. The issue seemed to be that the minimum API target was still 21 and the code for getting it in detect.py was never returning the value I was expecting, which was odd, and that was an issue because the NDK had two different sets of headers based on if it was 21 or 24+, with the current-most NDK version; I noticed some changes in 4.x that were similar to what I've made here, so I've resolved it by simply setting the min target to 24, but I also had to replace a value in detect.py to match 4.x. This loses Godot coverage on roughly 0.7% of the current Android marketplace, so I deemed it okay, but let me know if there's a better solution, or if you'd prefer something else. I'm letting it build now, but actually have one more potential commit that may or may not be necessary based on my local build, I'm just seeing if it'll work without it. And one last thing: I'm leaving this as draft for now, but only because I still have to attempt to upload this to the actual Play store and see what it does. I've run it fine on my device and everything looks good, but good to test everything.

**Comment by WolfgangSenff** [comment]
Okay. @m4gr3d and @syntaxerror247 - not crazy happy with the fix I implemented here, but it turns out basically the min SDK has to be at least 24, for the reasons mentioned above. How I solved that was a little bit lazy: I just hard-coded it into the detect.py file, based on something I found in the 4.x codebase, which is admittedly different, but required the least number of changes to other files. Let me know if that's okay. If so, I believe this is ready to go.

**Comment by syntaxerror247** [comment]
I don’t think bumping to 24 should be necessary. I’ll take a closer look at the issue soon.

File: platform/android/detect.py [hunk 3]
```diff
@@ -34,7 +34,7 @@ def get_env_android_sdk_root():
 
 
 def get_min_sdk_version(platform):
-    return int(platform.split("-")[1])
+    return 24
```
Comment (WolfgangSenff) [inline platform/android/detect.py]: @syntaxerror247 - sorry for the ping, but if you put this back to the int(platform.split("-")[1]) line from the previous codebase, it'll actually error out. I was struggling with the time I have available to figure out exactly what calls this and why it's calling it with the incorrect value, but in 4.x, the code looks pretty different, so I suspect that's where a different fix could be had.

**Comment by lawnjelly** [comment]
@syntaxerror247 just a little bump to remind you to try and take a look.

I'm conscious the clock is ticking on this as in #108161 the author says the Google Play requirements change to need API level 35 on August 31st 2025.

We also would have to make builds etc and ideally we don't want to end up in a situation where people can't submit to Google Play.

File: platform/android/detect.py (hunk 3 above)
Comment (syntaxerror247) [reply platform/android/detect.py]: I’ve fixed the error you were running into with that line.

**Comment by syntaxerror247** [comment]
I tried to get this working on API 21, but had no success. I'm stuck on this error:

```
thirdparty/opus/stream.c:102:10: error: call to undeclared function 'fseeko'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  102 |   return fseeko((FILE *)_stream,(off_t)_offset,_whence);
      |          ^
thirdparty/opus/stream.c:102:10: note: did you mean 'fseek'?
/usr/local/lib/android/sdk/ndk/27.3.13750724/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/stdio.h:207:5: note: 'fseek' declared here
  207 | int fseek(FILE* _Nonnull __fp, long __offset, int __whence);
      |     ^
thirdparty/opus/stream.c:117:10: error: call to undeclared function 'ftello'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  117 |   return ftello((FILE *)_stream);
      |          ^
thirdparty/opus/stream.c:117:10: note: did you mean 'ftell'?
/usr/local/lib/android/sdk/ndk/27.3.13750724/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/stdio.h:208:6: note: 'ftell' declared here
  208 | long ftell(FILE* _Nonnull __fp);
      |      ^
2 errors generated.
```

**Comment by syntaxerror247** [comment]
I was able to get this build by updating the `ndk-platform` to `24` while keeping min_sdk at 21. However, I'm not sure if that's the correct approach.

@m4gr3d @Alex2782 would like your input on whether it's okay to just bump the ndk-platform version.

**Comment by Alex2782** [comment]
> I was able to get this build by updating the `ndk-platform` to `24` while keeping min_sdk at 21. However, I'm not sure if that's the correct approach.

`fseeko / ftello`: I think these two functions support 64-bit (and > 2 GB file access?). 
If that solves the problem, then it's fine. 

I could test it on my Android 6, ARM32 tablet (and some more devices) to see if there are any side effects. 
Can you create it as a custom ARM32/ARM64 template?

**Comment by syntaxerror247** [comment]
> I could test it on my Android 6, ARM32 tablet (and some more devices) to see if there are any side effects. Can you create it as a custom ARM32/ARM64 template?

@Alex2782 https://github.com/syntaxerror247/godot/actions/runs/16811996983

**Review by Alex2782 — COMMENTED** [review]
### Crash on Android 6 (API 23)
I think we have to give up support for API < 24 here as well, like in Godot 4.x


`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "/data/app/org.godotengine.firstgodotproject-1/lib/arm/libgodot_android.so"...`

----------------
`v3.6.1.stable.official [b1ba98fce]`

```
with custom template: 
`Godot Engine v3.7.dev.custom_build.ecb6f7aa2`

1) Android 13,  arm64, OpenGL ES 2.0 Renderer: Adreno (TM) 650
2) Android 8.1, arm64, OpenGL ES 2.0 Renderer: Adreno (TM) 418
3) Android 8.1, arm32, OpenGL ES 2.0 Renderer: Mali-T830

4) Android 6,   arm32, Adreno 3xx (CRASH)

OK with '3.6.1' template:
Godot Engine v3.6.1.stable.official.b1ba98fce
OpenGL ES 2.0 Renderer: Adreno (TM) 320



```
<details><summary>crash log</summary>

```java
--------- beginning of crash
08-07 22:25:35.256  3011  3011 E AndroidRuntime: FATAL EXCEPTION: main
08-07 22:25:35.256  3011  3011 E AndroidRuntime: Process: org.godotengine.firstgodotproject, PID: 3011
08-07 22:25:35.256  3011  3011 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "/data/app/org.godotengine.firstgodotproject-1/lib/arm/libgodot_android.so"...
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:50)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:695)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at org.godotengine.godot.Godot.onCreate(Godot.java:844)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3099)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:524)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2214)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2109)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:2002)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
08-07 22:25:35.256  3011  3011 E AndroidRuntime: 	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:74)

```
</details>

https://github.com/godotengine/godot/blob/1f4dce03b2d51fcc0a49caf7f95cb3e188f0b962/drivers/unix/net_socket_posix.cpp#L98-L112

------------

maybe possible solution:

```cpp
#if __ANDROID_API__ < 24
const struct in6_addr my_in6addr_any = IN6ADDR_ANY_INIT;
#define in6addr_any my_in6addr_any
#endif
```
But it is very likely that more similar workarounds are necessary.

@m4gr3d what is your opinion on this?

**Comment by syntaxerror247** [comment]
Let's just move forward with this PR and bump the min_sdk to 24 and keep it in sync with 4.x

**Review by syntaxerror247 — APPROVED** [review]
Looks good!

**Review by m4gr3d — APPROVED** [review]
Looks good!

**Comment by lawnjelly** [comment]
Thanks!

BTW I may try and have a look at a later date whether it is possible to sort the compile errors to get to compile with min_sdk 21, do let me know which bits to change (if it is literally just the number then sorting compile errors) if this is viable, as supporting older versions is more relevant in 3.x than in 4.x.

**Comment by syntaxerror247** [comment]
@lawnjelly Check this branch: https://github.com/syntaxerror247/godot/tree/testing
It has two newer commits after this PR:
1. Revert min_sdk 24 update - This commit fails to build with the error I mentioned above (https://github.com/godotengine/godot/pull/108433#issuecomment-3164882813)

2. Update ndk_platform to 24 - This commit builds successfully but crashes, as tested by Alex.

So, basically, you need to apply the changes from the first commit to change the minsdk to 21 again.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.2.
