### PR TITLE
Fix CSG Visual Bug.

### LINKED ISSUE #39919: CSG - Visual Bug
**Godot version:**
3.2.2 stable

**OS/device including version:**
Windows 10, 64 Bit, GLES3

**Issue description:**
Visual Bugs

**Steps to reproduce:**
See Video. CSGCombiner and 2 CSGMesh's

**Minimal reproduction project:**
https://www.facebook.com/daniel.suter.96/videos/10223256216141733/

### PR DESCRIPTION
**Pull request by madmiraal**
Fixes #39919 issues in the provided test project.

### CODE REVIEW

File: modules/csg/csg.cpp [hunk 1]
```diff
@@ -523,7 +523,7 @@ void CSGBrushOperation::MeshMerge::_add_distance(List<real_t> &r_intersectionsA,
 
 	// Check if distance exists.
 	for (const List<real_t>::Element *E = intersections.front(); E; E = E->next()) {
-		if (Math::abs(**E - p_distance) < vertex_snap) {
+		if (Math::abs(**E - p_distance) < CMP_EPSILON) {
```
Comment (aaronfranke) [inline modules/csg/csg.cpp:526]: Could be `if (Math::is_equal_approx(**E, p_distance)) {`

Comment (madmiraal) [reply modules/csg/csg.cpp]: Updated to use is_equal_approx().

**Comment by akien-mga** [comment]
Thanks!
