### PR TITLE
NoiseTexture2D/3D: Don't use a thread to regenerate when the build doesn't support threads

### LINKED ISSUE #96098: NoiseTexture2D doesn't resize on the Web without threads
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+)

### Issue description

Resizing a `NoiseTexture2D` on a web export with default settings (which means threads are disabled) doesn't work.
The texture stays at the same size.

### Steps to reproduce

Create a main `Node2D` scene, add a `TextureRect` child with a `NoiseTexture2D` texture and `FastNoiseLite`.

Attach the following script to the main node:

```gdscript
extends Node2D

func _process(_delta: float) -> void:
	if Input.is_action_just_pressed('ui_up'):
		print('resizing up')
		$TextureRect.texture.width += 100
		$TextureRect.texture.height += 100

	if Input.is_action_just_pressed('ui_down'):
		print('resizing down')
		$TextureRect.texture.width -= 100
		$TextureRect.texture.height -= 100
```

On Windows it works as expected- when pressing `Up`/`Down` the noise texture resizes.

Export to the web with the default settings (which means threads are disabled) and observe that the texture does not resize.

### Minimal reproduction project (MRP)

See `Steps to reproduce`

### PR DESCRIPTION
**Pull request by SnirBroshi**
Fixes #96098.

Tested locally with `v4.3.stable.official [77dcf97d8]`, the texture resizes slowly but correctly.

### CODE REVIEW

File: modules/noise/noise_texture_2d.cpp [hunk 1]
```diff
@@ -194,6 +194,9 @@ Ref<Image> NoiseTexture2D::_modulate_with_gradient(Ref<Image> p_image, Ref<Gradi
 
 void NoiseTexture2D::_update_texture() {
 	bool use_thread = true;
+#ifndef THREADS_ENABLED
+	use_thread = false;
+#endif
```
Comment (Calinou) [inline modules/noise/noise_texture_2d.cpp:199]: This can be simplified to:

```suggestion
#ifdef THREADS_ENABLED
	bool use_thread = true;
#else
	bool use_thread = false;
#endif
```

This works because the C++ preprocessor makes it so you don't redefine the variable in this scenario.

Comment (NotWearingPants) [reply modules/noise/noise_texture_2d.cpp:199]: Yes but then why not go a step further and remove the `if (first_time)` and `if (use_thread)`?

I tried to use the `#ifdef` here like a normal `if`, and to let the compiler optimize away the rest.

It starts with `use_thread = true` and then has some checks that can disable threads, such as `if (first_time)` or `#ifdef THREADS_ENABLED`. The fact that one of these is a compile time check shouldn't change the flow IMO.

Comment (clayjohn) [reply modules/noise/noise_texture_2d.cpp:199]: I don't think redefining the variable is a problem. The compiler will definitely produce the same result. I find the current approach in the PR to be simpler. So my preference is to keep it the same

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
The same changes are needed for NoiseTexture3D, I'll amend the PR.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
