### PR TITLE
miniupnpc: Update to 2.2.8 (new major 18)

### LINKED ISSUE #93907: Error compiling against system miniupnpc after major bump to 18 (API breakage)
### Tested versions

- Reproducible in 4.3dev

### System information

Artic (Arch) Linux

### Issue description

Hi, I was trying to update and build Godot from Master but due to recent update in arch repositories of UPNP (libminiupnp.17 -> libminiupnp.18) cant finish the compilation step.

Complete building log:
```
scons: Reading SConscript files ...
Auto-detected 4 CPU cores available for build parallelism. Using 4 cores by default. You can override it with the -j argument.
Using linker program: mold
Building for platform "linuxbsd", architecture "x86_64", target "editor".
Using LTO: full
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 33%] Compiling modules/upnp/upnp.cpp ...
[ 34%] Compiling modules/webp/webp_common.cpp ...
[ 34%] Compiling modules/webrtc/register_types.cpp ...
[ 34%] Compiling modules/webrtc/webrtc_data_channel.cpp ...
modules/upnp/upnp.cpp:134:10: error: no matching function for call to 'UPNP_GetValidIGD'
  134 |         int i = UPNP_GetValidIGD(devlist, &urls, &data, (char *)&addr, 16);
      |                 ^~~~~~~~~~~~~~~~
/usr/include/miniupnpc/miniupnpc.h:122:1: note: candidate function not viable: requires 7 arguments, but 5 were provided
  122 | UPNP_GetValidIGD(struct UPNPDev * devlist,
      | ^                ~~~~~~~~~~~~~~~~~~~~~~~~~
  123 |                  struct UPNPUrls * urls,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~
  124 |                  struct IGDdatas * data,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~
  125 |                  char * lanaddr, int lanaddrlen,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  126 |                  char * wanaddr, int wanaddrlen);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [modules/upnp/upnp.linuxbsd.editor.x86_64.llvm.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:12.30]

```
What should I do? Downgrade the library or is planning to update it soon? 

### Steps to reproduce

1. Update libraries in arch repository
2. git pull latest Godot changes (master)
3. Start building Godot  

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
Keep support for major 17 by using a version check for the changed API.

Fixes #93907.

### CODE REVIEW

File: modules/upnp/upnp.cpp [hunk 1]
```diff
@@ -131,7 +131,11 @@ void UPNP::parse_igd(Ref<UPNPDevice> dev, UPNPDev *devlist) {
 	GetUPNPUrls(&urls, &data, dev->get_description_url().utf8().get_data(), 0);
 
 	char addr[16];
+#if MINIUPNPC_API_VERSION >= 18
+	int i = UPNP_GetValidIGD(devlist, &urls, &data, (char *)&addr, 16, nullptr, 0);
```
Comment (akien-mga) [inline modules/upnp/upnp.cpp:135]: The new prototype is:
```cpp
UPNP_GetValidIGD(struct UPNPDev * devlist,
                 struct UPNPUrls * urls,
                 struct IGDdatas * data,
                 char * lanaddr, int lanaddrlen,
                 char * wanaddr, int wanaddrlen);
```

We should evaluate whether we want to make use of the new `wanaddr` stuff @mhilbrunner

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
