### PR TITLE
Fix inconsistency in 3D editor navigation

### LINKED ISSUE #97103: Zooming in 3D editor does not work with trackpad
### Tested versions

v4.4.dev2.official [97ef3c837]

### System information

Godot v4.4.dev2 - macOS 14.6.1 - Metal (Forward+) - integrated Apple M2 (Apple8) - Apple M2 (8 Threads)

### Issue description

When using a trackpad to navigate in the 3D editor, zooming does not work. Orbitting and panning does work, though (with the default shortcuts).

### Steps to reproduce

- Use a trackpad
- Switch to the 3D editor
- Press Shift+Ctrl and try zooming by dragging up or down
- The pan gesture is used instead of zoom

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by detomon**
Fixes #97103. Maybe fixes other inconsistencies with other input methods.

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -2169,9 +2169,11 @@ void Node3DEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
 	if (pan_gesture.is_valid()) {
 		NavigationMode nav_mode = NAVIGATION_NONE;
 
-		NavigationMode change_nav_from_shortcut = _get_nav_mode_from_shortcut_check(NAVIGATION_LEFT_MOUSE, shortcut_check_sets, true);
-		if (change_nav_from_shortcut != NAVIGATION_NONE) {
-			nav_mode = change_nav_from_shortcut;
+		for (const ShortcutCheckSet &shortcut_check_set : shortcut_check_sets) {
```
Comment (detomon) [inline editor/plugins/node_3d_editor_plugin.cpp:2172]: Pan gesture has no mouse button and shortcuts can be empty (e.g., orbit), so `_get_nav_mode_from_shortcut_check` can't be used here.

**Review by adamscott — APPROVED** [review]
Seems ok!

**Comment by akien-mga** [comment]
Thanks!
