### PR TITLE
Do not change scene on save when debugging

### LINKED ISSUE #33409: Saving a script during debugging causes 2D editor to steal focus
Godot 3.2 alpha1, beta1
Godot 3.2.2 rc1

When I test my game (or debug), it happens that I leave the game running while I do some corrections to my code, and doing so I sometimes press Ctrl+S, which in my shortcut settings saves the current script.
However, when I do, Godot switches to the 2D editor. It does that also if I use the File->Save menu.

It doesn't always happen, but when following the same steps in my project it happens everytime. I'm not sure which specific step causes it.

My project has a main scene with instances of other scenes in it. What I do:
- Have main scene open
- Start debugging session
- In the main scene, click on an instance icon to open its scene (that one might be optional but I'm not sure)
- Click on a node from the scene tree
- Switch to the Script editor
- Write something
- Save script: boom, editor switches to 2D editor.

### LINKED ISSUE #47861: Godot sometimes switches to the 2D editor on play
**Godot version:**
3.3.rc8

**OS/device including version:**
Windows 10

**Issue description:**
Sometimes when certain nodes in the 2D editor are selected, the script editor swaps to the 2D editor when the project runs.

In some scenes over multiple projects:

* When the root Node2D is selected, the script editor switches to the 2D editor on play
* When a CanvasLayer is selected, the script editor **does not** switch to the 2D editor on play
* Trying to replicate this scene with a simpler one fails to reproduce the bug

This video shows me talking through the issue and I also discovered switching to the 2D editor stopped in one project possibly because another project was already running.

https://user-images.githubusercontent.com/3285214/114578885-3d63f600-9c75-11eb-8227-307aaa5593e4.mp4

**Steps to reproduce:**
Unsure how to.

**Minimal reproduction project:**
I couldn't replicate it with a clean project with a smaller scene.

### PR DESCRIPTION
**Pull request by nathanfranke**
Fix https://github.com/godotengine/godot/issues/33409
Fix https://github.com/godotengine/godot/issues/47861

Aka: Do not update scene tree dock when node edited outside of it

It would be **incredible** to get this in 3.3, but seeing as we're already in RC8 that is unlikely. Just saying this would save dozens of peoples' sanity when they're already in their most dangerous place: **debugging**

---

Reproduction (Thanks for suggesting, KoBeWi)
- Add this code to any node:
```py
  func _process(delta):
  	pass
  ```

- Start debugging scene
- Select any canvas item in the scene
- Switch back to script tab
- Save

### CODE REVIEW

**Comment by akien-mga** [comment]
> It would be incredible to get this in 3.3, but seeing as we're already in RC8 that is unlikely. Just saying this would save dozens of peoples' sanity when they're already in their most dangerous place: debugging

Yes for 3.3-stable it's too risky, but it can likely make its way into 3.4 and 3.3.1.

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -526,6 +526,10 @@ void SceneTreeEditor::_node_removed(Node *p_node) {
 }
 
 void SceneTreeEditor::_node_renamed(Node *p_node) {
+	if (!get_scene_node()->is_a_parent_of(p_node)) {
```
Comment (nathanfranke) [inline editor/scene_tree_editor.cpp:529]: > Yes for 3.3-stable it's too risky, but it can likely make its way into 3.4 and 3.3.1.

Very true, I think I still somehow managed to get one of these three lines wrong :stuck_out_tongue: 

---

Of course this is a very simple change but my main concern is whether to use `tree` here or `get_scene_node()`. If I'm correct, `tree` is the representation of the nodes and `get_scene_node()` contains the nodes themselves.

**Comment by KoBeWi** [comment]
Any chance this fixes #47861 too?

Also some steps to reproduce the issue reliably would be useful for testing the PR. I myself encountered this few times, but I don't know how to reproduce.

**Comment by nathanfranke** [comment]
> Any chance this fixes #47861 too?
> 
> Also some steps to reproduce the issue reliably would be useful for testing the PR. I myself encountered this few times, but I don't know how to reproduce, so difficult to say if the fix even works.

- Add this code to any node:
```py
  func _process(delta):
  	pass
  ```

- Start debugging scene
- Select any node in the scene
- Switch back to script tab
- Save

**Comment by KoBeWi** [comment]
The steps don't work for me :/

**Comment by nathanfranke** [comment]
> The steps don't work for me :/

I elaborated that the selected node must be a `CanvasItem`.

File: editor/scene_tree_editor.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/scene_tree_editor.cpp:529]: This would need a rebase and change to `is_ancestor_of()` (renamed).

I'm also unsure on whether that's the right API to do this bugfix, but it does seem sensible. I think we can merge and see if there's any regression :)

**Review by akien-mga — APPROVED** [review]
Can be merged once rebased.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
