### PR TITLE
OpenXR: Fix saving action map when UID is used in project settings

### LINKED ISSUE #105607: OpenXR Action map is trying to save UUID as file name
### Tested versions

- Reproducible in 4.4.1 stable

Haven't tried on other platforms yet.

### System information

Not sure, user reported

### Issue description

This was reported on Discord but thought it serious enough to raise an issue for this, need to investigate further but I think this is caused by us now saving UIDs in project settings instead of path names, with the result that the OpenXR action map gets the path wrong:

Image

### Steps to reproduce

Not sure what triggers the pathname in the project settings being replaced by it's UID but once that is triggered, simply editing the OpenXR action map will trigger this error.

### Minimal reproduction project (MRP)

It should be possible to reproduce this with any of the projects in https://github.com/godotengine/godot-demo-projects/tree/master/xr
Doesn't require XR hardware, just need to trigger the condition where the UID is stored in project settings instead of the filepath.

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/105607

I don't know if this is the right way to fix this (because I'm not sure the proper way to handle UIDs in editor code) but it does fix the issue in my testing

### CODE REVIEW

File: modules/openxr/editor/openxr_action_map_editor.cpp [hunk 1]
```diff
@@ -288,17 +290,17 @@ void OpenXRActionMapEditor::_load_action_map(const String p_path, bool p_create_
...
-		action_map->set_path(p_path);
+		action_map->set_path(path);
 
 		// Save it immediately
-		err = ResourceSaver::save(action_map, p_path);
+		err = ResourceSaver::save(action_map, path);
 		if (err != OK) {
 			// Show warning but continue.
-			EditorNode::get_singleton()->show_warning(vformat(TTR("Error saving file %s: %s"), edited_path, error_names[err]));
+			EditorNode::get_singleton()->show_warning(vformat(TTR("Error saving file %s: %s"), path, error_names[err]));
```
Comment (dsnopek) [inline modules/openxr/editor/openxr_action_map_editor.cpp:299]: This change isn't strictly related to fixing this bug, but the original code here was incorrect: it was using `edited_path` before we've set `edited_path`, so it would show either `""` or the previous path. We're saving to `path`, so that is what should be shown in the error dialog.

**Review by akien-mga — APPROVED** [review]
Looks correct to me, but I'll let KoBeWi double check.

**Comment by KoBeWi** [comment]
How to open OpenXR Action Map editor? I created OpenXRActionMap resource, but double-clicking it in the filesystem does not open the editor.

**Comment by dsnopek** [comment]
> How to open OpenXR Action Map editor?

If you enable OpenXR in Project Settings (XR -> OpenXR -> Enabled), it should be an option in the bottom area (by "Output", "Debugger", etc).

> I created OpenXRActionMap resource, but double-clicking it in the filesystem does not open the editor.

I don't know if you can edit a random OpenXRActionMap resource, the editor may only work on the one that's configured in Project Settings (XR -> OpenXR -> Default Action Map). At least, that's the only way I've ever personally used it.

**Comment by KoBeWi** [comment]
The problem lies here:
https://github.com/godotengine/godot/blob/9f03bbf9086a1164490cd7cb4e8dd056bf57eac2/modules/openxr/editor/openxr_action_map_editor.cpp#L498
The editor opens the default map at launch, without validating if it's path or UID. If you ensure path here, you won't need any more changes.

File: modules/openxr/editor/openxr_action_map_editor.cpp [hunk 2]
```diff
@@ -288,17 +290,17 @@ void OpenXRActionMapEditor::_load_action_map(const String p_path, bool p_create_
 	} else if (p_create_new_if_missing) {
 		action_map.instantiate();
 		action_map->create_default_action_sets();
-		action_map->set_path(p_path);
+		action_map->set_path(path);
```
Comment (KoBeWi) [inline modules/openxr/editor/openxr_action_map_editor.cpp:293]: This line shouldn't be needed. `ResourceSaver` already sets that when saving.

**Review by KoBeWi — APPROVED** [review]
The fix looks fine. You can simplify it like I suggested, or go with your current solution to be extra safe. But right now the call I linked is the only way to edit the action map with UID.

File: modules/openxr/editor/openxr_action_map_editor.cpp (hunk 2 above)
Comment (dsnopek) [reply modules/openxr/editor/openxr_action_map_editor.cpp]: Ok, I've removed this line. Now that I've switched to the simpler approach you recommended, this change is a little out of place, but hopefully still OK :-)

**Comment by Repiteo** [comment]
Thanks!
