### PR TITLE
Force disable Vulkan overlays in the editor and project manager

### LINKED ISSUE #57403: Vulkan: MangoHud breaks rendering unless single-window mode is enabled
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

EndeavourOS(Arch linux) KDE, AMD Ryzen 5 3400g Vega11, AMDVLK 2022.Q1.1-1 64bit on Vulkan API 1.2.203

### Issue description

After opening Godot' projects lists there is dialog box asking about downloading projects from asset library or creating on your own and it doesn't load properly making UI basically useless, doesn't happen on 32bit version of the editor.
logs from the terminal:
```
Godot Engine v4.0.alpha1.official.31a7ddbf8 - https://godotengine.org
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_scanned_icd_add: Driver /usr/lib/amdvlk64.so says it supports interface version 6 but still exports core entrypoints (Policy #LDP_DRIVER_6)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 128156400
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:157)
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/boomer/Download/MangoHud.conf' [ not found ]
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/boomer/.config/MangoHud/Godot_v4.0-alpha1_linux.64.conf' [ not found ]
[2022-01-29 15:10:24.472] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/boomer/.config/MangoHud/MangoHud.conf'
Vulkan API 1.2.203 - Using Vulkan Device #0: AMD - AMD Radeon Vega 11 Graphics
[2022-01-29 15:10:24.569] [MANGOHUD] [info] [overlay.cpp:678] Uploading is disabled (permit_upload = 0)
```
 
HAPPEN ON THE RADEON DRIVER TOO!

### Steps to reproduce

Run 64bit of Godot 4.0 and load empty projects list

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
MangoHud would be shown on every popup in multi-window mode, and seemed
to cause rendering issues for various users.

There are also issues with RTSS, and VkBasalt also doesn't seem
particularly good to use in the editor.

All these stay available to enable when running the project itself,
including running from the editor (so running the editor after e.g.
`export MANGOHUD=1` in the environment will ignore it for the editor,
but use it when playing the project).

Fixes #57403.
Fixes #57937.

---

Before:
image

After:
image

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -1677,10 +1677,17 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 	OS::get_singleton()->_allow_hidpi = GLOBAL_DEF("display/window/dpi/allow_hidpi", true);
 	OS::get_singleton()->_allow_layered = GLOBAL_DEF("display/window/per_pixel_transparency/allowed", false);
 
+#ifdef TOOLS_ENABLED
 	if (editor || project_manager) {
-		// The editor and project manager always detect and use hiDPI if needed
+		// The editor and project manager always detect and use hiDPI if needed.
 		OS::get_singleton()->_allow_hidpi = true;
+		// Disable MangoHud in editor, as it's applied to all windows.
+		OS::get_singleton()->set_environment("DISABLE_MANGOHUD", "1");
```
Comment (bruvzg) [inline main/main.cpp:1685]: If we are force disabling tools like this, I guess we should also add `DISABLE_RTSS_LAYER = 1` to fix https://github.com/godotengine/godot/issues/57937

Comment (bruvzg) [reply main/main.cpp]: RTSS is a part of afterburner.

**Comment by Calinou** [comment]
At the same time, we can also force `ENABLE_VKBASALT=0` on the editor/project manager. Yyou generally don't want injected SMAA/CAS from influencing the editor UI (it'll negatively impact font rendering quality).

**Comment by akien-mga** [comment]
> At the same time, we can also force [`ENABLE_VKBASALT=0`](https://github.com/DadSchoorse/vkBasalt) on the editor/project manager. You generally don't want injected SMAA/CAS from influencing the editor UI (it'll negatively impact font rendering quality).

Done. Like the others, it also supports a `DISABLE_VKBASALT` override to allow disabling it without overriding the user-defined `ENABLE_VKBASALT`.

File: main/main.cpp [hunk 2]
```diff
@@ -1677,10 +1677,21 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
 		OS::get_singleton()->_allow_hidpi = true;
+		// Disable Vulkan overlays in editor, they cause various issues.
+		OS::get_singleton()->set_environment("DISABLE_MANGOHUD", "1"); // GH-57403.
+		OS::get_singleton()->set_environment("DISABLE_RTSS_LAYER", "1"); // GH-57937.
+		OS::get_singleton()->set_environment("DISABLE_VKBASALT", "1");
+	} else {
+		// Re-allow using Vulkan overlays, disabled while using the editor.
+		OS::get_singleton()->unset_environment("DISABLE_MANGOHUD");
+		OS::get_singleton()->unset_environment("DISABLE_RTSS_LAYER");
+		OS::get_singleton()->unset_environment("DISABLE_VKBASALT");
```
Comment (akien-mga) [inline main/main.cpp:1692]: Worth noting that if the user defined e.g. `DISABLE_MANGOHUD` themselves before running a project with a `TOOLS_ENABLED` build of Godot (directly, not necessarily from the editor), this would also unset it and then re-enable MangoHud if they also have `MANGOHUD=1` set.

That use case would be someone enabling MangoHud system-wide, but disabling with the `DISABLE_MANGOHUD` option instead of `MANGOHUD=0` when running Godot specifically.

Seems far fetched so probably not worth addressing. If anyone ever runs into this, we could move the `unset` calls to EditorRun to make them specific to running the project from the editor/project manager.

File: main/main.cpp [hunk 3]
```diff
@@ -1677,10 +1677,21 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
 
+#ifdef TOOLS_ENABLED
 	if (editor || project_manager) {
-		// The editor and project manager always detect and use hiDPI if needed
+		// The editor and project manager always detect and use hiDPI if needed.
 		OS::get_singleton()->_allow_hidpi = true;
+		// Disable Vulkan overlays in editor, they cause various issues.
+		OS::get_singleton()->set_environment("DISABLE_MANGOHUD", "1"); // GH-57403.
+		OS::get_singleton()->set_environment("DISABLE_RTSS_LAYER", "1"); // GH-57937.
+		OS::get_singleton()->set_environment("DISABLE_VKBASALT", "1");
```
Comment (Calinou) [inline main/main.cpp:1687]: If anyone's curious, `DISABLE_VKBASALT=1` is actually valid (but not documented in vkBasalt's README): https://github.com/DadSchoorse/vkBasalt/blob/3920df927bcffcc0fd1535a35c88e0bb5952ad63/config/vkBasalt.json.in#L14-L19

**Comment by hakro** [comment]
Thanks!

**Comment by Calinou** [comment]
This approach doesn't appear to be working on Windows with RTSS, both on Vulkan and Direct3D 12 when using https://github.com/godotengine/godot/pull/70315. I've also tried setting `DISABLE_RTSS_LAYER` to `1` in the command line before running the editor to no avail.

Using Windows 11 and RTSS 7.3.4 Beta 3 (bundled with MSI Afterburner).

**Comment by akien-mga** [comment]
Can you check the RTSS JSON file to see if what defines it relies on to skip it?

As a example for MangoHud on Linux:
```
$ cat /usr/share/vulkan/implicit_layer.d/MangoHud.json 
{
    "file_format_version" : "1.0.0",
    "layer" : {
      "name": "VK_LAYER_MANGOHUD_overlay",
      "type": "GLOBAL",
      "api_version": "1.3.0",
      "library_path": "/usr/$LIB/mangohud/libMangoHud.so",
      "implementation_version": "1",
      "description": "Vulkan Hud Overlay",
      "functions": {
         "vkGetInstanceProcAddr": "overlay_GetInstanceProcAddr",
         "vkGetDeviceProcAddr": "overlay_GetDeviceProcAddr"
      },
      "enable_environment": {
        "MANGOHUD": "1"
      },
      "disable_environment": {
        "DISABLE_MANGOHUD": "1"
      }
    }
}
```

**Comment by akien-mga** [comment]
Should probably be discussed upstream then, if it doesn't work when you define `DISABLE_RTSS_LAYER` manually in the environment yourself. I assume you can reproduce it with other applications too.

**Comment by Calinou** [comment]
RTSS 7.3.4 has an interesting entry in its changelog ([ReadMe.pdf](https://github.com/godotengine/godot/files/11393028/ReadMe.pdf)):

> Improved compatibility with Vulkan applications, using multiple coexisting swapchains (e.g. Godot v4 editor)
