### PR TITLE
Set thorvg threads to be one to avoid SVG import crash.

### LINKED ISSUE #48243: SVG Import fails since adding multi-threaded import
**Godot version:**
https://github.com/godotengine/godot/commit/288f484d0a034d02fbca3db0a2f14f5a0084a36b

**OS/device including version:**
Nvidia RTX 3000 series - Vulkan - Win10

**Issue description:**
The editor hangs on load.

**Steps to reproduce:**
Open the fail case project.

**Minimal reproduction project:**

[svg_test_fail.zip](https://github.com/godotengine/godot/files/6386244/svg_test_fail.zip)
[svg_test_pass.zip](https://github.com/godotengine/godot/files/6386245/svg_test_pass.zip)

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/48243.

Test cases:
[icons.zip](https://github.com/godotengine/godot/files/8358086/icons.zip)

### CODE REVIEW

**Comment by akien-mga** [comment]
With this test case (before this PR) I get this crash:
```
0x00007ffff7ae2bec in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install lib64alsa2-1.2.6.1-2.mga9.x86_64 lib64asyncns0-0.8-13.mga9.x86_64 lib64bsd0-0.10.0-3.mga9.x86_64 lib64dbus1_3-1.14.0-2.mga9.x86_64 lib64drm2-2.4.110-3.mga9.x86_64 lib64drm_amdgpu1-2.4.110-3.mga9.x86_64 lib64edit0-3.1-0.20210910.2.mga9.x86_64 lib64elfutils1-0.186-2.mga9.x86_64 lib64expat1-2.4.7-2.mga9.x86_64 lib64ffi8-3.4.2-5.mga9.x86_64 lib64flac8-1.3.4-2.mga9.x86_64 lib64gcrypt20-1.9.4-2.mga9.x86_64 lib64gl1-1.4.0-2.mga9.x86_64 lib64gldispatch0-1.4.0-2.mga9.x86_64 lib64gpg-error0-1.43-2.mga9.x86_64 lib64llvm13.0-13.0.1-2.mga9.x86_64 lib64lz4_1-1.9.3-3.mga9.x86_64 lib64lzma5-5.2.5-4.mga9.x86_64 lib64mesavulkan-drivers-22.0.0-7.mga9.x86_64 lib64ncurses6-6.3-20211211.2.mga9.x86_64 lib64opus0-1.3.1-4.mga9.x86_64 lib64pulseaudio0-15.0-5.mga9.x86_64 lib64pulsecommon15.0-15.0-5.mga9.x86_64 lib64systemd0-250.4-2.mga9.x86_64 lib64udev1-250.4-2.mga9.x86_64 lib64vorbisenc2-1.3.7-2.mga9.x86_64 lib64vulkan-loader1-1.3.204.1-1.mga9.x86_64 lib64wayland-client0-1.20.0-1.mga9.x86_64 lib64x11-xcb1-1.7.3.1-2.mga9.x86_64 lib64x11_6-1.7.3.1-2.mga9.x86_64 lib64xau6-1.0.9-3.mga9.x86_64 lib64xcb-dri3_0-1.14-2.mga9.x86_64 lib64xcb-shm0-1.14-2.mga9.x86_64 lib64xcb-sync1-1.14-2.mga9.x86_64 lib64xcb1-1.14-2.mga9.x86_64 lib64xcursor1-1.2.0-3.mga9.x86_64 lib64xdmcp6-1.1.3-3.mga9.x86_64 lib64xext6-1.3.4-3.mga9.x86_64 lib64xfixes3-6.0.0-2.mga9.x86_64 lib64xi6-1.8-2.mga9.x86_64 lib64xinerama1-1.1.4-4.mga9.x86_64 lib64xrandr2-1.5.2-3.mga9.x86_64 lib64xrender1-0.9.10-4.mga9.x86_64 lib64zlib1-1.2.11-12.mga9.x86_64 lib64zstd1-1.5.2-2.mga9.x86_64 libgcc1-12.0.1-0.20220327.1.mga9.x86_64 libstdc++6-12.0.1-0.20220327.1.mga9.x86_64
(gdb) bt
#0  0x00007ffff7ae2bec in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff7a962f2 in raise () from /lib64/libc.so.6
#2  0x00007ffff7a82457 in abort () from /lib64/libc.so.6
#3  0x00007ffff7ad7788 in __libc_message () from /lib64/libc.so.6
#4  0x00007ffff7aeb98a in malloc_printerr () from /lib64/libc.so.6
#5  0x00007ffff7aef204 in _int_realloc () from /lib64/libc.so.6
#6  0x00007ffff7aefd35 in realloc () from /lib64/libc.so.6
#7  0x000000000526dfb3 in strokeExportOutline (stroke=0x7fff9800d4e0, mpool=0xc4a1930, tid=0) at thirdparty/thorvg/src/lib/sw_engine/tvgSwStroke.cpp:924
#8  0x000000000526b422 in shapeGenStrokeRle (shape=0x7fff98179928, sdata=0x7fff98018220, transform=0x7fff98003dd0, clipRegion=..., renderRegion=..., mpool=0xc4a1930, tid=0)
    at thirdparty/thorvg/src/lib/sw_engine/tvgSwShape.cpp:596
#9  0x0000000005266af7 in SwShapeTask::run (this=0x7fff98179860, tid=0) at thirdparty/thorvg/src/lib/sw_engine/tvgSwRenderer.cpp:135
#10 0x00000000052246ef in tvg::TaskSchedulerImpl::request (this=0xc4a19d0, task=0x7fff98179860) at thirdparty/thorvg/src/lib/tvgTaskScheduler.cpp:154
#11 0x0000000005223f06 in tvg::TaskScheduler::request (task=0x7fff98179860) at thirdparty/thorvg/src/lib/tvgTaskScheduler.cpp:184
#12 0x0000000005266186 in tvg::SwRenderer::prepareCommon (this=0x7fff980187b0, task=0x7fff98179860, transform=0x7fff8bffd1e0, opacity=255, clips=..., flags=tvg::All)
    at thirdparty/thorvg/src/lib/sw_engine/tvgSwRenderer.cpp:607
#13 0x00000000052662d1 in tvg::SwRenderer::prepare (this=0x7fff980187b0, sdata=..., data=0x0, transform=0x7fff8bffd1e0, opacity=255, clips=..., flags=tvg::All)
    at thirdparty/thorvg/src/lib/sw_engine/tvgSwRenderer.cpp:638
#14 0x0000000005222a86 in tvg::Shape::Impl::update (this=0x7fff980182e0, renderer=..., transform=0x7fff8bffd1e0, opacity=255, clips=..., pFlag=tvg::All) at thirdparty/thorvg/src/lib/tvgShapeImpl.h:239
#15 0x0000000005223924 in tvg::PaintMethod<tvg::Shape::Impl>::update (this=0x7fff98018340, renderer=..., transform=0x7fff8bffd1e0, opacity=255, clips=..., renderFlag=tvg::All)
    at thirdparty/thorvg/src/lib/tvgPaint.h:180
#16 0x000000000521b7d5 in tvg::Paint::Impl::update (this=0x7fff980182b0, renderer=..., pTransform=0x7fff8bffd1e0, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:242
#17 0x000000000521fbac in tvg::Scene::Impl::update (this=0x7fff98001f70, renderer=..., transform=0x7fff8bffd1e0, opacity=255, clips=..., flag=tvg::All) at thirdparty/thorvg/src/lib/tvgSceneImpl.h:101
#18 0x000000000522068a in tvg::PaintMethod<tvg::Scene::Impl>::update (this=0x7fff98006ab0, renderer=..., transform=0x7fff8bffd1e0, opacity=255, clips=..., renderFlag=tvg::All)
    at thirdparty/thorvg/src/lib/tvgPaint.h:180
#19 0x000000000521b7d5 in tvg::Paint::Impl::update (this=0x7fff980028b0, renderer=..., pTransform=0x7fff8bffd1e0, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:242
#20 0x000000000521fbac in tvg::Scene::Impl::update (this=0x7fff98002610, renderer=..., transform=0x7fff8bffd1e0, opacity=255, clips=..., flag=tvg::All) at thirdparty/thorvg/src/lib/tvgSceneImpl.h:101
#21 0x000000000522068a in tvg::PaintMethod<tvg::Scene::Impl>::update (this=0x7fff98005a10, renderer=..., transform=0x7fff8bffd1e0, opacity=255, clips=..., renderFlag=tvg::All)
    at thirdparty/thorvg/src/lib/tvgPaint.h:180
#22 0x000000000521b767 in tvg::Paint::Impl::update (this=0x7fff98002450, renderer=..., pTransform=0x7fff8bffd360, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:239
#23 0x000000000521fbac in tvg::Scene::Impl::update (this=0x7fff98002990, renderer=..., transform=0x7fff8bffd360, opacity=255, clips=..., flag=tvg::All) at thirdparty/thorvg/src/lib/tvgSceneImpl.h:101
#24 0x000000000522068a in tvg::PaintMethod<tvg::Scene::Impl>::update (this=0x7fff98002a70, renderer=..., transform=0x7fff8bffd360, opacity=255, clips=..., renderFlag=tvg::All)
    at thirdparty/thorvg/src/lib/tvgPaint.h:180
#25 0x000000000521b767 in tvg::Paint::Impl::update (this=0x7fff98002530, renderer=..., pTransform=0x7fff8bffd4e0, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:239
#26 0x000000000521fbac in tvg::Scene::Impl::update (this=0x7fff980040f0, renderer=..., transform=0x7fff8bffd4e0, opacity=255, clips=..., flag=tvg::All) at thirdparty/thorvg/src/lib/tvgSceneImpl.h:101
#27 0x000000000522068a in tvg::PaintMethod<tvg::Scene::Impl>::update (this=0x7fff980026f0, renderer=..., transform=0x7fff8bffd4e0, opacity=255, clips=..., renderFlag=tvg::All)
    at thirdparty/thorvg/src/lib/tvgPaint.h:180
--Type <RET> for more, q to quit, c to continue without paging--
#28 0x000000000521b767 in tvg::Paint::Impl::update (this=0x7fff98005710, renderer=..., pTransform=0x7fff98006d70, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:239
#29 0x000000000521fbac in tvg::Scene::Impl::update (this=0x7fff98018640, renderer=..., transform=0x7fff98006d70, opacity=255, clips=..., flag=tvg::All) at thirdparty/thorvg/src/lib/tvgSceneImpl.h:101
#30 0x000000000522068a in tvg::PaintMethod<tvg::Scene::Impl>::update (this=0x7fff98018670, renderer=..., transform=0x7fff98006d70, opacity=255, clips=..., renderFlag=tvg::All)
    at thirdparty/thorvg/src/lib/tvgPaint.h:180
#31 0x000000000521b7d5 in tvg::Paint::Impl::update (this=0x7fff98018610, renderer=..., pTransform=0x7fff98006d70, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:242
#32 0x000000000521fbac in tvg::Scene::Impl::update (this=0x7fff98018720, renderer=..., transform=0x7fff98006d70, opacity=255, clips=..., flag=tvg::All) at thirdparty/thorvg/src/lib/tvgSceneImpl.h:101
#33 0x000000000522068a in tvg::PaintMethod<tvg::Scene::Impl>::update (this=0x7fff98018750, renderer=..., transform=0x7fff98006d70, opacity=255, clips=..., renderFlag=tvg::All)
    at thirdparty/thorvg/src/lib/tvgPaint.h:180
#34 0x000000000521b7d5 in tvg::Paint::Impl::update (this=0x7fff980186f0, renderer=..., pTransform=0x0, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:242
#35 0x000000000521d231 in tvg::Picture::Impl::update (this=0x7fff980019f0, renderer=..., pTransform=0x0, opacity=255, clips=..., pFlag=tvg::All) at thirdparty/thorvg/src/lib/tvgPictureImpl.h:137
#36 0x000000000521e5d0 in tvg::PaintMethod<tvg::Picture::Impl>::update (this=0x7fff980021d0, renderer=..., transform=0x0, opacity=255, clips=..., renderFlag=tvg::All) at thirdparty/thorvg/src/lib/tvgPaint.h:180
#37 0x000000000521b7d5 in tvg::Paint::Impl::update (this=0x7fff98009e10, renderer=..., pTransform=0x0, opacity=255, clips=..., pFlag=255) at thirdparty/thorvg/src/lib/tvgPaint.cpp:242
#38 0x0000000005217498 in tvg::Canvas::Impl::update (this=0x7fff98018810, paint=0x7fff98004e70, force=true) at thirdparty/thorvg/src/lib/tvgCanvasImpl.h:96
#39 0x00000000052172e2 in tvg::Canvas::Impl::push (this=0x7fff98018810, paint=std::unique_ptr<tvg::Paint> = {...}) at thirdparty/thorvg/src/lib/tvgCanvasImpl.h:57
#40 0x00000000052170b8 in tvg::Canvas::push (this=0x7fff98018790, paint=std::unique_ptr<tvg::Paint> = {...}) at thirdparty/thorvg/src/lib/tvgCanvas.cpp:48
#41 0x000000000526eae0 in ImageLoaderSVG::create_image_from_string (this=0xc4a1a30, p_image=..., p_string=..., p_scale=1, p_upsample=false, p_convert_color=false) at modules/svg/image_loader_svg.cpp:97
#42 0x000000000526efd1 in ImageLoaderSVG::load_image (this=0xc4a1a30, p_image=..., p_fileaccess=0x7fff98008530, p_force_linear=false, p_scale=1) at modules/svg/image_loader_svg.cpp:141
#43 0x000000000897d6f6 in ImageLoader::load_image (p_file=..., p_image=..., p_custom=0x0, p_force_linear=false, p_scale=1) at core/io/image_loader.cpp:66
#44 0x00000000068f9a49 in ResourceImporterTexture::import (this=0xcbf21f0, p_source_file=..., p_save_path=..., p_options=..., r_platform_variants=0x7fff8bffe298, r_gen_files=0x7fff8bffe290, 
    r_metadata=0x7fff8bffe270) at editor/import/resource_importer_texture.cpp:440
#45 0x00000000063147f6 in EditorFileSystem::_reimport_file (this=0xd4ee130, p_file=..., p_custom_options=0x0, p_custom_importer=...) at editor/editor_file_system.cpp:1881
#46 0x000000000631734f in EditorFileSystem::_reimport_thread (this=0xd4ee130, p_index=0, p_import_data=0x7fffffffc960) at editor/editor_file_system.cpp:2042
#47 0x0000000006327f2a in ThreadWorkPool::Work<EditorFileSystem, void (EditorFileSystem::*)(unsigned int, EditorFileSystem::ImportThreadData*), EditorFileSystem::ImportThreadData*>::work (this=0x1ac3f890)
    at ./core/templates/thread_work_pool.h:61
#48 0x0000000008d645b7 in ThreadWorkPool::_thread_function (p_user=0xd4eec70) at core/templates/thread_work_pool.cpp:42
#49 0x000000000888736d in Thread::callback (p_self=0xd4eec70, p_settings=..., p_callback=0x8d644e2 <ThreadWorkPool::_thread_function(void*)>, p_userdata=0xd4eec70) at core/os/thread.cpp:75
#50 0x000000000888811b in std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __f=@0xd4b03e8: 0x88872e8 <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>) at /usr/include/c++/12/bits/invoke.h:61
#51 0x0000000008887fe4 in std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __fn=@0xd4b03e8: 0x88872e8 <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>) at /usr/include/c++/12/bits/invoke.h:96
#52 0x0000000008887e9f in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0xd4b03c8) at /usr/include/c++/12/bits/std_thread.h:252
#53 0x0000000008887e04 in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator() (this=0xd4b03c8)
    at /usr/include/c++/12/bits/std_thread.h:259
#54 0x0000000008887de8 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_run (this=0xd4b03c0) at /usr/include/c++/12/bits/std_thread.h:210
--Type <RET> for more, q to quit, c to continue without paging--
#55 0x00000000091a3f83 in std::execute_native_thread_routine (__p=0xd4b03c0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#56 0x00007ffff7ae0f3a in start_thread () from /lib64/libc.so.6
#57 0x00007ffff7b601ac in clone3 () from /lib64/libc.so.6
```

Seems to me like a thorvg bug that should be reported and fixed upstream.

We can also merge this PR to fix it downstream but I need to understand what this is doing exactly. Usually we get problems when we use multiple threads, not when we run on the main thread. The referenced issue also claims that the problem stems from multi-threading, but the solution seems to be to make it multi-threaded?

**Review by akien-mga — APPROVED** [review]
I'm giving a tentative approval because it fixes the bug, and it seems sensible to let thorvg use multiple threads.

But I still have concerns regarding how this interacts with Godot's how import thread pool and whether this could lead to spawning way too many threads for something that might not warrant it. There's an upstream issue with further discussion, we can wait to have some input before merging.

File: modules/svg/register_types.cpp [hunk 1]
```diff
@@ -38,7 +39,8 @@ static ImageLoaderSVG *image_loader_svg = nullptr;
 
 void register_svg_types() {
 	tvg::CanvasEngine tvgEngine = tvg::CanvasEngine::Sw;
-	if (tvg::Initializer::init(tvgEngine, 0) != tvg::Result::Success) {
+	int32_t processor_count = OS::get_singleton()->get_processor_count();
+	if (tvg::Initializer::init(tvgEngine, MAX(1, processor_count - 1)) != tvg::Result::Success) {
```
Comment (akien-mga) [inline modules/svg/register_types.cpp:43]: As we discussed in PR review meeting, it might be best to use `1` for now, if `0` doesn't work.
Since we already handle multi-threading import of files in parallel, we don't need the thorvg scheduler to also spawn lots of threads for each file. (the `core/os/os.h` include can also be removed then).

Comment (fire) [reply modules/svg/register_types.cpp]: Updated.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by hermet** [comment]
@fire  @akien-mga It looks like a thread-safety issue. tvg is designed to share internal data-resource among canvas instances in default, its mechanism of the thread-safety is only considered for internal threads. (basically tvg apis doesn't guarantee the thread-safety)

If godot calls tvg apis on multi-threads, could you please try the following api for each canvas instance?

```
canvas->mempool(tvg::MempoolPolicy::Individual);
```

Once that, the canvas instance would use its own instance-designated internal resource. This could resolve the multi-threading issue. Hopefully, if my guess is correct.

btw, zero number of threads is not allowed, it would be re-arranged to maximum number of threads. so... bad. 
Please use 1 or a specific number under the system threads count. 
```
auto threads = std::thread::hardware_concurrency();
```
