### PR TITLE
OpenXR: Fix building foveation extension without Vulkan

### LINKED ISSUE #105704: Compiler error for openxr module on MacOS when compiling without Vulkan
### Tested versions

Reproduced in 4.5 dev 931820d33cbc38328e4014d65dd62c359b5116fc (master branch as of submitting)

The code that errors is introduced by: https://github.com/godotengine/godot/pull/99768
But I suspect the actual cause may lie somewhere else.

### System information

Godot v4.5.dev (931820d33) - macOS Sequoia (15.4.1) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M4 (Apple9) - Apple M4 (10 threads)

### Issue description

Compiling the Godot editor without Vulkan causes a vulkan only if statement to be executed.

```
if (rendering_driver == "vulkan") {
		request_extensions[XR_FB_FOVEATION_VULKAN_EXTENSION_NAME] = &fb_foveation_vulkan_ext;
}
```
Causing this error:
```
modules/openxr/extensions/openxr_fb_foveation_extension.cpp:76:22: error: use of undeclared identifier 'XR_FB_FOVEATION_VULKAN_EXTENSION_NAME'
   76 |                 request_extensions[XR_FB_FOVEATION_VULKAN_EXTENSION_NAME] = &fb_foveation_vulkan_ext;
      |        
```

### Steps to reproduce

`scons vulkan=no platform=macos arch=arm64`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/105704

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
macOS builds without Vulkan still fails for unrelated reason (https://github.com/godotengine/godot/pull/105709)

File: modules/openxr/extensions/openxr_fb_foveation_extension.cpp [hunk 1]
```diff
@@ -56,9 +56,12 @@ OpenXRFBFoveationExtension::OpenXRFBFoveationExtension(const String &p_rendering
 
 	if (rendering_driver == "opengl3") {
 		swapchain_create_info_foveation_fb.flags = XR_SWAPCHAIN_CREATE_FOVEATION_SCALED_BIN_BIT_FB;
-	} else if (rendering_driver == "vulkan") {
+	}
```
Comment (akien-mga) [inline modules/openxr/extensions/openxr_fb_foveation_extension.cpp:59]: Shouldn't this also check `XR_USE_GRAPHICS_API_OPENGL`?

Comment (dsnopek) [reply modules/openxr/extensions/openxr_fb_foveation_extension.cpp:59]: It doesn't need it to compile, because the extension always has the `XR_SWAPCHAIN_CREATE_FOVEATION_SCALED_BIN_BIT_FB` constant regardless. But, yeah, we could avoid the string comparison if OpenGL isn't enabled at all using some `#ifdef`'s. Let me see how that looks..

Comment (dsnopek) [reply modules/openxr/extensions/openxr_fb_foveation_extension.cpp:59]: So, using `#ifdef`s for OpenGL here isn't a complete win, because without even more ugly `#ifdef`s, we end up losing the `else`, so when both OpenGL and Vulkan are enabled, it does two string comparisons instead of one. But this code only runs once at startup, so it's fine.

In fact, we could probably just not have `#ifdef`s on this code at all? These two constants are always available regardless of which graphics APIs are enabled. I think I'm going to go that way in my next push, but I'd be happy to switch to the other if that was preferred.

**Comment by Repiteo** [comment]
Thanks!
