### PR TITLE
Fix folder color not showing up in file dialogs

### LINKED ISSUE #83366: Folder color doesn't show up in file dialogs
### Godot version

v4.2.beta.custom_build [a574c0296]

### System information

linux

### Issue description

Folder colors don't show up in file dialogs: when saving a scene, etc.

### Steps to reproduce

1. color a folder
2. create and open the save scene dialog and navigate to the colored folder
3. notice it's not shown its color in the file dialog

### Minimal reproduction project

any

### PR DESCRIPTION
**Pull request by nikableh**
Fixes #83366.

Here is an example project with a bunch of colored folders to verify that my changes work: [preview_project.zip](https://github.com/godotengine/godot/files/13333793/preview_project.zip).

I can also provide a compiled Windows 10 executable of the editor if someone needs it.

Screenshots:
image

### CODE REVIEW

File: editor/filesystem_dock.h [hunk 1]
```diff
@@ -369,6 +369,9 @@ class FileSystemDock : public VBoxContainer {
 	static void _bind_methods();
 
 public:
+	HashMap<String, Color> get_folder_colors() const;
```
Comment (AThousandShips) [inline editor/filesystem_dock.h:372]:
```suggestion
	const HashMap<String, Color> &get_folder_colors() const;
```
I'd say this should be passed by reference, unless you absolutely need them to be copied

File: editor/gui/editor_file_dialog.cpp [hunk 2]
```diff
@@ -842,6 +843,9 @@ void EditorFileDialog::update_file_list() {
 	dirs.sort_custom<NaturalNoCaseComparator>();
 	files.sort_custom<NaturalNoCaseComparator>();
 
+	HashMap<String, Color> folder_colors = FileSystemDock::get_singleton()->get_folder_colors();
```
Comment (AThousandShips) [inline editor/gui/editor_file_dialog.cpp:846]:
```suggestion
	const HashMap<String, Color> &folder_colors = FileSystemDock::get_singleton()->get_folder_colors();
```
For these as well in that case

File: editor/filesystem_dock.h [hunk 3]
```diff
@@ -369,6 +369,9 @@ class FileSystemDock : public VBoxContainer {
 	static void _bind_methods();
 
 public:
+	const HashMap<String, Color> &get_folder_colors() const;
+	Dictionary get_assigned_folder_colors() const;
```
Comment (synalice) [inline editor/filesystem_dock.h:373]: Shouldn't I change this to be a const reference as well?
```suggestion
	const Dictionary &get_assigned_folder_colors() const;
```

Comment (AThousandShips) [reply editor/filesystem_dock.h:373]: No dictionary is shared

Comment (synalice) [reply editor/filesystem_dock.h:373]: > No dictionary is shared

Uh? What do you mean? Sorry, I'm not very familiar with the codebase yet.

Comment (AThousandShips) [reply editor/filesystem_dock.h:373]: Copying a dictionary just makes a reference, it doesn't copy the data, if you make a copy and change it the original changes too

File: editor/gui/editor_file_dialog.cpp [hunk 4]
```diff
@@ -1432,10 +1445,19 @@ void EditorFileDialog::_update_favorites() {
 
 	EditorNode::disambiguate_filenames(favorited_paths, favorited_names);
 
+	HashMap<String, Color> folder_colors = FileSystemDock::get_singleton()->get_folder_colors();
```
Comment (AThousandShips) [inline editor/gui/editor_file_dialog.cpp:1448]:
```suggestion
	const HashMap<String, Color> &folder_colors = FileSystemDock::get_singleton()->get_folder_colors();
```

File: editor/gui/editor_file_dialog.cpp [hunk 5]
```diff
@@ -1515,10 +1537,19 @@ void EditorFileDialog::_update_recent() {
 
 	EditorNode::disambiguate_filenames(recentd_paths, recentd_names);
 
+	HashMap<String, Color> folder_colors = FileSystemDock::get_singleton()->get_folder_colors();
```
Comment (AThousandShips) [inline editor/gui/editor_file_dialog.cpp:1540]:
```suggestion
	const HashMap<String, Color> &folder_colors = FileSystemDock::get_singleton()->get_folder_colors();
```

File: editor/filesystem_dock.cpp [hunk 6]
```diff
@@ -3477,6 +3477,15 @@ void FileSystemDock::_file_sort_popup(int p_id) {
 	set_file_sort((FileSortOption)p_id);
 }
 
+const HashMap<String, Color> &FileSystemDock::get_folder_colors() const {
+	return folder_colors;
+}
+
+
```
Comment (AThousandShips) [inline editor/filesystem_dock.cpp:3484]:
```suggestion
```

**Comment by synalice** [comment]
Btw, is _force-pushing_ an only option to add new changes to PR? You either squash or amend, but you'll always have to _force-push_ after that, is that right?

**Comment by AThousandShips** [comment]
Indeed, or it will force you to merge with the upstream commits, unless you just add new commits at the end

**Comment by AThousandShips** [comment]
Unless you're expecting to have to do a major rework there's no need, unless it's been approved, though if you just communicate you need to fix some things there should be no issue

**Comment by KoBeWi** [comment]
The colors still do not apply to sub-folders and recent folders:
image

**Comment by synalice** [comment]
> The colors still do not apply to sub-folders and recent folders:
> image
> 

Oh, yeah, I missed that with subfolders. I'll fix that.

And is there a way to make a folder appear in the recent tab? It's empty for me.

**Comment by KoBeWi** [comment]
When you open some file (e.g. a scene), its directory will appear in recent.

**Comment by synalice** [comment]
Should be it now o(\*￣︶￣\*)o

**Comment by synalice** [comment]
Is there any tutorial on how to set up this code style GitHub action locally?

**Comment by AThousandShips** [comment]
Yes see [here](https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html)

File: editor/gui/editor_file_dialog.cpp [hunk 7]
```diff
@@ -766,6 +767,38 @@ void EditorFileDialog::update_file_name() {
...
+	}
+
+	if (!dir_path.ends_with("/")) {
+		dir_path += "/";
+	}
+
+	if (assigned_folder_colors.has(dir_path)) {
+		// If current folder itself has a color we should use it instead of the inherited color.
+		folder_icon_color = folder_colors[assigned_folder_colors[dir_path]];
+	}
```
Comment (synalice) [inline editor/gui/editor_file_dialog.cpp:797]: I think this code might be unnecessary. Let me test.

File: editor/gui/editor_file_dialog.h [hunk 8]
```diff
@@ -239,6 +239,8 @@ class EditorFileDialog : public ConfirmationDialog {
 	static void _bind_methods();
 
 public:
+	Color get_dir_icon_color(String dir_path);
```
[the remark this answers is not in the document]
Comment (synalice) [reply editor/gui/editor_file_dialog.h:242]: Are you sure? It can't be `const` because I'm modifying it inside the method. The same goes for the `&` – I'm modifying it, should it really be a reference?

[the remark this answers is not in the document]
Comment (AThousandShips) [reply editor/gui/editor_file_dialog.h:242]: You're not modifying it? And you shouldn't

[the remark this answers is not in the document]
Comment (synalice) [reply editor/gui/editor_file_dialog.h:242]: Oh, yea, you are right. It was the previous piece of this function that I've eventually removed that did modify the argument.

[the remark this answers is not in the document]
Comment (AThousandShips) [reply editor/gui/editor_file_dialog.h:242]: Generally you should avoid modifying arguments 🙂

File: editor/filesystem_dock.h (hunk 3 above)
Comment (KoBeWi) [reply editor/filesystem_dock.h:373]: It could still be const reference, to avoid increasing reference counter. Though the gain is probably minimal.

File: editor/gui/editor_file_dialog.cpp [hunk 9]
```diff
@@ -766,6 +767,29 @@ void EditorFileDialog::update_file_name() {
 	}
 }
 
+// TODO: Could use a unit test.
+Color EditorFileDialog::get_dir_icon_color(const String &p_dir_path) {
+	// Creating these two variables every time might be unoptimized, although I don't think it's noticeable.
```
Comment (KoBeWi) [inline editor/gui/editor_file_dialog.cpp:772]: These variables already exist in FileSystemDock, you are just fetching a reference, so it's cheap.
I think the comment is unnecessary.

File: editor/gui/editor_file_dialog.cpp [hunk 10]
```diff
@@ -766,6 +767,29 @@ void EditorFileDialog::update_file_name() {
...
+	// Check for a folder color to inherit (if one is assigned).
+	String parent_dir = p_dir_path;
+	while (parent_dir != "res://" && folder_icon_color == theme_cache.folder_icon_color) {
+		if (!parent_dir.ends_with("/")) {
+			parent_dir += "/";
+		}
+		if (assigned_folder_colors.has(parent_dir)) {
+			folder_icon_color = folder_colors[assigned_folder_colors[parent_dir]];
+		}
+		parent_dir = parent_dir.rstrip("/").get_base_dir();
```
Comment (KoBeWi) [inline editor/gui/editor_file_dialog.cpp:787]:
```suggestion
		parent_dir = parent_dir.trim_suffix("/").get_base_dir();
```

File: editor/gui/editor_file_dialog.cpp [hunk 11]
```diff
@@ -858,8 +882,10 @@ void EditorFileDialog::update_file_list() {
 		d["path"] = cdir.path_join(dir_name);
 		d["dir"] = true;
 
+		Color folder_icon_color = get_dir_icon_color(String(d["path"]));
```
Comment (KoBeWi) [inline editor/gui/editor_file_dialog.cpp:885]: I think you could put it directly in the method call, as the variable is used only once.

File: editor/gui/editor_file_dialog.cpp [hunk 12]
```diff
@@ -1386,6 +1412,8 @@ void EditorFileDialog::_update_favorites() {
 
 	favorite->set_pressed(false);
 
+	// FIXME: `favorited` and `favorited_paths` seem to be the two same variables.
+	//        Not sure is this is intentional or not.
```
Comment (KoBeWi) [inline editor/gui/editor_file_dialog.cpp:1416]: They are not exactly the same, e.g. `favorited_names` uses `/` instead of `res://`.
Again, unnecessary comment 🙃

**Review by KoBeWi — APPROVED** [review]
Works correctly now. I was a bit worried about the performance impact of recursively checking folder colors, but I tested the PR in a big project and didn't see any issues (although it's not like I have thousands of deeply nested folders).

**Comment by AThousandShips** [comment]
> I was a bit worried about the performance impact of recursively checking folder colors

If it is a concern maybe there could be some caching or other lookups, unsure how though, but I think the nesting should be shallow enough, though not sure how often it is queried

**Comment by synalice** [comment]
I've compiled the source and verified that everything still works. I think this can be safely merged now! \\(￣︶￣*\\))

**Comment by YuriSizov** [comment]
> If it is a concern maybe there could be some caching

I think the entire implementation is a bit iffy. This information seems like a perfect fit for the EditorFileSystem data structure rather than being limited to the FileSystemDock. EFS would also act as a cache and should make iterations easier.

**Comment by YuriSizov** [comment]
Thanks! I've decided we can merge this as is to address the existing problem. But I still think we can look into refactoring the implementation and moving color information to the editor file system. So if you're interested, feel free to look into it 🙂

**Comment by nathanfranke** [comment]
This caused a crash for me on Linux, 6.6.3-arch1-1

Reproduction is simple: Project Manager -> New Project -> Browse project path

Good daddb2b46950f37503f0d033e1d9bdccab173449
Bad 6faa5c6dc479bebd4b92a5251fafe22b21ca9523

```
Godot Engine v4.3.dev.custom_build.6faa5c6dc - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 23.2.1-arch1.2 - Compatibility - Using Device: AMD - AMD Radeon RX 6800 XT (navi21, LLVM 16.0.6, DRM 3.54, 6.6.3-arch1-1)
 

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.3.dev.custom_build (6faa5c6dc479bebd4b92a5251fafe22b21ca9523)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3e710) [0x7ff742c32710] (??:0)
[2] Dictionary::_ref(Dictionary const&) const (/home/nathan/workspace/public/godot-4/core/variant/dictionary.cpp:222)
[3] Dictionary::Dictionary(Dictionary const&) (/home/nathan/workspace/public/godot-4/core/variant/dictionary.cpp:388)
[4] FileSystemDock::get_assigned_folder_colors() const (/home/nathan/workspace/public/godot-4/editor/filesystem_dock.cpp:3473)
[5] EditorFileDialog::get_dir_icon_color(String const&) (/home/nathan/workspace/public/godot-4/editor/gui/editor_file_dialog.cpp:775)
[6] EditorFileDialog::update_file_list() (/home/nathan/workspace/public/godot-4/editor/gui/editor_file_dialog.cpp:885 (discriminator 3))
[7] EditorFileDialog::_invalidate() (/home/nathan/workspace/public/godot-4/editor/gui/editor_file_dialog.cpp:1190)
[8] void call_with_variant_args_helper<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/nathan/workspace/public/godot-4/./core/variant/binder_common.h:308)
[9] void call_with_variant_args<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, int, Callable::CallError&) (/home/nathan/workspace/public/godot-4/./core/variant/binder_common.h:418)
[10] CallableCustomMethodPointer<EditorFileDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/nathan/workspace/public/godot-4/./core/object/callable_method_pointer.h:99)
[11] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/nathan/workspace/public/godot-4/core/variant/callable.cpp:57)
[12] CallQueue::_call_function(Callable const&, Variant const*, int, bool) (/home/nathan/workspace/public/godot-4/core/object/message_queue.cpp:222)
[13] CallQueue::flush() (/home/nathan/workspace/public/godot-4/core/object/message_queue.cpp:328)
[14] SceneTree::physics_process(double) (/home/nathan/workspace/public/godot-4/scene/main/scene_tree.cpp:473)
[15] Main::iteration() (/home/nathan/workspace/public/godot-4/main/main.cpp:3750 (discriminator 3))
[16] OS_LinuxBSD::run() (/home/nathan/workspace/public/godot-4/platform/linuxbsd/os_linuxbsd.cpp:933 (discriminator 1))
[17] ./bin/godot.linuxbsd.editor.dev.x86_64(main+0x19b) [0x563adc2e2ea4] (/home/nathan/workspace/public/godot-4/platform/linuxbsd/godot_linuxbsd.cpp:76)
[18] /usr/lib/libc.so.6(+0x27cd0) [0x7ff742c1bcd0] (??:0)
[19] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7ff742c1bd8a] (??:0)
[20] ./bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x563adc2e2c35] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

**Comment by YuriSizov** [comment]
> Edit: Is it because FileSystemDock doesn't exist in project manager?

No, your stack trace doesn't show it crashing on the singleton or even on the previous line where we access another member of the dock class. It probably crashes because of this assignment:

```
assigned_folder_colors = ProjectSettings::get_singleton()->get_setting("file_customization/folder_colors");
```

Project settings don't exist outside of a project, so this probably assigns some gibberish to the member.

**Comment by YuriSizov** [comment]
@synalice Are you working on a fix?

**Comment by adamscott** [comment]
For more context, the export directory is also broken with the merge of this PR.

image

**Comment by YuriSizov** [comment]
@adamscott Your problem is different, you get an infinite loop in this:

```
	String parent_dir = p_dir_path;
	while (parent_dir != "res://" && folder_icon_color == theme_cache.folder_icon_color) {
		if (!parent_dir.ends_with("/")) {
			parent_dir += "/";
		}
		if (assigned_folder_colors.has(parent_dir)) {
			folder_icon_color = folder_colors[assigned_folder_colors[parent_dir]];
		}
		parent_dir = parent_dir.trim_suffix("/").get_base_dir();
	}
```

Because `parent_dir` is already an empty string or `/`, and it never reaches the `res://` state.
