### PR TITLE
Fix incorrect completion popup size of `CodeEdit`

### LINKED ISSUE #50275: Completion options popup has incorrect width
### Godot version

bfc14a6359f6a466999af37f20c71269e9952328

### System information

Windows 10

### Issue description

Size looking incorrect and some options are overlapping the width limit.

image
image

It seems like a regression from one of the @bruvzg commits...

### Steps to reproduce

Call a completion option in GDScript or shader editors.

### Minimal reproduction project

Too easy to reproduce.

### PR DESCRIPTION
**Pull request by Chaosus**
After this PR it looks identical to 3.x without any cut-offs.

completion_test

Fix #50275

### CODE REVIEW

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -2691,11 +2691,16 @@ void CodeEdit::_filter_code_completion_candidates() {
 			option.icon = completion_options[i].get("icon");
 			option.default_value = completion_options[i].get("default_value");
 
-			max_width = MAX(max_width, font->get_string_size(option.display).width);
+			int offset = 0;
+			if (option.default_value.get_type() == Variant::COLOR) {
+				offset = get_line_height();
```
Comment (Paulb23) [inline scene/gui/code_edit.cpp:2696]: `get_line_height` is quite expense to run at the moment, would recommend calculating this outside the loop. Same for below.

Comment (Chaosus) [reply scene/gui/code_edit.cpp]: Thanks, fixed

**Review by Paulb23 — APPROVED** [review]
LGTM.
