### PR TITLE
Make InstancePlaceholders in charge of resolving node references in instances

### LINKED ISSUE #88662: Regression in InstancePlaceholder behavior, instanced scene missing Node property values
### Tested versions

- Reproducible in 4.3.dev3
- Works as expected in 4.2.1

### System information

Godot v4.3.dev3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.4633) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When instantiating a node using `InstancePlaceholder.create_instance()` the newly instantiated node is missing exported Node properties.

This is the expected result ( viewed in Remote tab)
image
this is what happens instead 
image
( number change is due to me changing it in between screenshots 😅)
Nested scenes are not affected and seem to instantiate with all properties set. Issue appears in both GDScript and C#. 
Everything works as expected on 4.2.1

### Steps to reproduce

Open the attached MRP, and run `main.tscn`
Check the Remote tab and see the properties missing.

For ease of comparison the `Main` node has a bool 
image
which will trigger loading the same scene manually using `InstancePlaceholder.get_instance_path()` instead. This approach works fine.

### Minimal reproduction project (MRP)

[PlaceholderInstanceRepro.zip](https://github.com/godotengine/godot/files/14373332/PlaceholderInstanceRepro.zip)

### PR DESCRIPTION
**Pull request by TheOrioli**
This is my attempt at resolving #88662 

From what I could figure out with my limited understanding of the codebase, the issue seems deeper than just the suspected PR https://github.com/godotengine/godot/pull/83343 

I have created an even bigger repro project that tries to really abuse node properties, arrays and their resolutions during the instantiation process.

[PlaceholderInstanceRepro.zip](https://github.com/godotengine/godot/files/14893922/PlaceholderInstanceRepro.zip)

This project not only fails in versions 4.3-dev.X, but also in 4.2.1, where arrays of external and mixed node references hit the error here https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/scene/resources/packed_scene.cpp#L493 

I am not nearly comfortable enough with the system to truly say that this is the correct solution, but I hope it can through reviews and discussion serve as a base of finding one.

*Bugsquad edit:*
- Fixes #88662

### CODE REVIEW

File: scene/main/instance_placeholder.cpp [hunk 1]
```diff
@@ -88,27 +88,114 @@ Node *InstancePlaceholder::create_instance(bool p_replace, const Ref<PackedScene
...
+			instance->set(E.name, E.value, &is_valid);
+			if (is_valid)
+				break;
+
+			instance->set(E.name, try_get_node(placeholder, instance, E.value), &is_valid);
+			break;
+		case Variant::Type::OBJECT:
+			if (placeholder_type != Variant::Type::NODE_PATH)
+				break;
+			// easiest case, we want a node, but we have a deferred nodepath
```
Comment (AThousandShips) [inline scene/main/instance_placeholder.cpp:155]:
```suggestion
			if (placeholder_type != Variant::Type::NODE_PATH) {
				break;
			}
			// Easiest case, we want a node, but we have a deferred NodePath.
```

File: scene/main/instance_placeholder.cpp [hunk 2]
```diff
@@ -88,27 +88,114 @@ Node *InstancePlaceholder::create_instance(bool p_replace, const Ref<PackedScene
...
+				}
+			}
+
+			instance->set(E.name, converted_array, &is_valid);
+			if (!is_valid)
+				WARN_PRINT(vformat("{Property '%s' with type %s could not be set when creating instance of '%s'}", E.name, Variant::get_type_name(current_type), placeholder->get_name()));
+			break;
+		}
+		default:
+			WARN_PRINT(vformat("{Property '%s' with type '%s' could not be set when creating instance of '%s'}", E.name, Variant::get_type_name(current_type), placeholder->get_name()));
```
Comment (AThousandShips) [inline scene/main/instance_placeholder.cpp:186]:
```suggestion
			WARN_PRINT(vformat("Property '%s' with type '%s' could not be set when creating instance of '%s'.", E.name, Variant::get_type_name(current_type), placeholder->get_name()));
```

File: scene/main/instance_placeholder.cpp [hunk 3]
```diff
@@ -88,27 +88,114 @@ Node *InstancePlaceholder::create_instance(bool p_replace, const Ref<PackedScene
...
+			break;
+	}
+}
+
+Node *InstancePlaceholder::try_get_node(InstancePlaceholder *placeholder, Node *instance, const NodePath &np) {
+	// first try to resolve internally
+	// if that fails try resolving externally
```
Comment (AThousandShips) [inline scene/main/instance_placeholder.cpp:193]:
```suggestion
	// First try to resolve internally,
	// if that fails try resolving externally.
```

File: scene/resources/packed_scene.cpp [hunk 4]
```diff
@@ -314,6 +314,16 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
 					ERR_FAIL_INDEX_V(nprops[j].value, prop_count, nullptr);
 
 					if (nprops[j].name & FLAG_PATH_PROPERTY_IS_NODE) {
+						if (node->get_scene_instance_load_placeholder()) {
+							// we cannot know if the referenced nodes exist yet, so instead of defering, we write the nodepaths directly
```
Comment (AThousandShips) [inline scene/resources/packed_scene.cpp:318]:
```suggestion
							// We cannot know if the referenced nodes exist yet, so instead of deferring, we write the NodePaths directly.
```

File: scene/main/instance_placeholder.cpp [hunk 5]
```diff
@@ -88,27 +88,114 @@ Node *InstancePlaceholder::create_instance(bool p_replace, const Ref<PackedScene
...
+
+// This method will attempt to set the correct values on the placeholder instance
+// for regular types this is trivial and unnecessary.
+// For nodes however this becomes a bit tricky because they might now have existed until the instantiation,
+// so this method will try to find the correct nodes and resolve them.
+void InstancePlaceholder::set_value_on_instance(InstancePlaceholder *placeholder, Node *instance, const InstancePlaceholder::PropSet &E) {
+	bool is_valid;
+
+	// if we don't have any info, we can't do anything
+	// so try setting the value directly
```
Comment (AThousandShips) [inline scene/main/instance_placeholder.cpp:122]:
```suggestion
	// If we don't have any info, we can't do anything
	// so try setting the value directly.
```

**Comment by TheOrioli** [comment]
@AThousandShips appreciate the review 🙌

I would just like to try and write some actual tests as well, seems there are no tests for instance placeholders and it might be cool to get some coverage on all this new code.

**Comment by AThousandShips** [comment]
Sounds great!

**Comment by TheOrioli** [comment]
@AThousandShips I've added some tests for the new behavior. There are still a couple of test cases that might be good to cover, specifically concerning properties that should contain Node's but their NodePath is overridden with the same value, so they reference an internal node after creation. This happens quite often now in the editor, since the editor  seems to like setting the same value on the properties which is then stored as override in the PackedScene resource, as seen here:
image

But it would be good to get some eyes with testing experience to tell me if my current approach is actually good or not 🙌

**Comment by AThousandShips** [comment]
I'll try take a look soon

**Comment by TheOrioli** [comment]
There we go 😁 https://github.com/godotengine/godot/pull/90306/commits/bda230efcb4bffb9f502953a6819bbe4a7dbadd6 is a test that will fail on the current `master` branch, while it works with this PR. I will add a few additional tests in the same vein later today 💪 

Is there an official/best practice way of creating and deleting temporary files created during tests?

**Comment by AThousandShips** [comment]
I'm not sure if there's any good practice for the creation or deletion, I'd suggest checking some of the other tests, like `core/io`, should be something in there

Code looks good I believe, wasn't able to do a functional evaluation at the moment though

**Comment by TheOrioli** [comment]
Seems like the `core/io` tests write into the OS cache directory. I've changed my tests to do the same. I am surprised there doesn't seem to be an `OS` singleton method to get the temporary directory of the filesystem, but that is outside the scope of this PR.

I don't know where more to take this, so I would say it's as ready as it will get until further reviews are done 👍

**Comment by TheOrioli** [comment]
Merged the latest master into the branch 👍

**Comment by AThousandShips** [comment]
In the future please use rebasing to update your branch, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

File: scene/resources/packed_scene.cpp [hunk 6]
```diff
@@ -314,6 +314,16 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
 					ERR_FAIL_INDEX_V(nprops[j].value, prop_count, nullptr);
 
 					if (nprops[j].name & FLAG_PATH_PROPERTY_IS_NODE) {
+						if (node->get_scene_instance_load_placeholder()) {
```
Comment (SaracenOne) [inline scene/resources/packed_scene.cpp:317]: I think you may need to change this to something like, since otherwise direct node references get lost upon reloading a scene in the editor:
`if (!Engine::get_singleton()->is_editor_hint() && node->get_scene_instance_load_placeholder()) {`

**Review by SaracenOne — CHANGES_REQUESTED** [review]
Thanks for this! This mostly looks good, but could you examine one issue I raised in regards to the editor losing direct node references. Also could you squash this PR into a single commit? This is generally the preferred way to merge PRs in Godot.

**Comment by TheOrioli** [comment]
@SaracenOne thank you for the review. Added the fix, squashed into one commit, rebased on master.

**Review by SaracenOne — APPROVED** [review]
LGTM 👍

**Review by AThousandShips — APPROVED** [review]

File: tests/scene/test_instance_placeholder.h [hunk 7]
```diff
@@ -0,0 +1,535 @@
...
+#define TEST_INSTANCE_PLACEHOLDER_H
+
+#include "scene/main/instance_placeholder.h"
+#include "scene/resources/packed_scene.h"
+
+#include "tests/test_macros.h"
+
+// Declared in global namespace because of GDCLASS macro warning (Windows):
+// "Unqualified friend declaration referring to type outside of the nearest enclosing namespace
+// is a Microsoft extension; add a nested name specifier".
```
Comment (KoBeWi) [inline tests/scene/test_instance_placeholder.h:41]: I think the comment is unnecessary. Some tests also create global classes, without any comment.

**Review by KoBeWi — APPROVED** [review]
I'm not that familiar with InstancePlaceholder, but the code seems fine.

> Is there an official/best practice way of creating and deleting temporary files created during tests?

The official practice seems to be polluting a "cache" directory 🙃
https://github.com/godotengine/godot/issues/92097

**Comment by TheOrioli** [comment]
> I'm not that familiar with InstancePlaceholder, but the code seems fine.
> 
> > Is there an official/best practice way of creating and deleting temporary files created during tests?
> 
> The official practice seems to be polluting a "cache" directory 🙃 #92097

Thank for the review, I'll remove the comment and push a new version.

Concerning #92097 I noticed OS seems to lack a temporary directory method, so I'm thinking about making a PR later adding support for it and seeing what happens to the tests if they use that instead.

**Comment by KoBeWi** [comment]
As I noted in the issue, it'd be fine if there was a test-specific helper method that returns a fixed sub-directory, so at least the files are in one place.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
