### PR TITLE
fix wrong encoding format in uri_encode

### LINKED ISSUE #47475: `HttpClient.query_string_from_dict("\n")` encodes the newline as `%A` instead of `%0A`
**Godot version:** 3.2.3

**OS/device including version:** Linux

**Issue description:** HttpClient.query_string_from_dict("\n") encodes the newline as "%A" instead of "%0A". Probably an error with not including a leading zero in String::url_encode() around here: https://github.com/godotengine/godot/blob/db31445b905d94f055ffd210aee6d93cc39b8c96/core/string/ustring.cpp#L3780

**Steps to reproduce:** print(HTTPClient.new().query_string_from_dict({"test": "line\nline"}))

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by DanielKriz**
This should fix the wrong encoding format mentioned in  #47475. It explicitly wants the hex number to be aligned to two digits, if it is too small, it just adds null. I tested it with reproduce function given in the issue, and it worked.

*Bugsquad edit:* fixes #47475.

### CODE REVIEW

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -3772,9 +3772,9 @@ String String::uri_encode() const {
 		} else {
 			char h_Val[3];
 #if defined(__GNUC__) || defined(_MSC_VER)
-			snprintf(h_Val, 3, "%hhX", ord);
+			snprintf(h_Val, 3, "%02X", ord);
 #else
-			sprintf(h_Val, "%hhX", ord);
+			sprintf(h_Val, "%02X", ord);
```
Comment (Faless) [inline core/string/ustring.cpp:3777]: This seems okay, but shouldn't we keep the `hh`? i.e.: `"%02hhX"`?
@RandomShaper opinions?

Comment (RandomShaper) [reply core/string/ustring.cpp:3777]: I think we should. Ohterwise, if `ord < 0`, the formatting would take more than two characters despite the `02`: https://onlinegdb.com/SJTQ1Bnru

**Review by Faless — CHANGES_REQUESTED** [review]
Should be: `%02hhX`

**Comment by DanielKriz** [comment]
Requared changes are commited.

**Review by Faless — APPROVED** [review]
Looks good :trophy: ! Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.
