### PR TITLE
C#: Improve `GD.PushError` and `GD.PushWarning`

### LINKED ISSUE #72662: [4.0.beta17] .net - double clicking (unnecessarily long) debug log entry doesn't jumpt to source but to source-generator code
### Godot version

4.0.beta17.mono.official

### System information

Windows 10

### Issue description

As the title says, the log output is needlessly deep into internals (screenshot here: https://github.com/godotengine/godot/pull/71943#issuecomment-1415809223), but the actual issue is that double clicking the log entry doesn't jump to the source file but attempts to open the source-generator generated file instead:
grafik

### Steps to reproduce

Print debug statements from a c# file, and try to double click the log entry in the editor.

### Minimal reproduction project

If required i can create one

### LINKED ISSUE #76415: C# Selecting an error makes a "Save Resource As" menu appears when running the project
### Godot version

4.0.2

### System information

Windows 10

### Issue description

If an error in the Debugger/Errors menu caused by a C# script is selected every time the project is executed a "Save Resource As" menu appears.
Erro1
Erro2

The only way to stop it for appearing is restarting Godot.

### Steps to reproduce

1. Execute a C# script with an error
2. Select the error in the Debugger/Errors menu
3. Click "run project"
4. A "Save Resource As" menu appears.

### Minimal reproduction project

Example code with error:

```csharp
using Godot;
using System;

public partial class ErrorTest : Node 
{
    public override void _Ready() 
    {
        Node nullNode = null;

        nullNode.ToString();
    }
}


```

### LINKED ISSUE #79449: In C#, Polling for InputMap action that does not exist produces a difficult to debug error.
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - macOS 13.4.1 - Vulkan (Mobile) - dedicated AMD Radeon Pro 5300M - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When polling for an InputAction that does not exist from C#, Godot produces the following error, which is so long that it is impossible to read on a normal display.
```
E 0:00:01:0823   Godot.NativeInterop.NativeFuncs.generated.cs:345 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* ): The InputMap action "Jump" doesn't exist.
```
The expected error in this case would be something along the lines of
```
Error: The InputMap action "Jump" doesn't exist.
```
But instead this is what the console ends up looking like:
image

### Steps to reproduce

Poll an Action that does not exist in C#:
```
Input.GetActionStrength(action_name);
```
The resulting error should be very difficult to parse.

### Minimal reproduction project

This is a very simple error to reproduce (simply poll for a nonexistent Action with C#) so I don't think a reproduction project is necessary.

### PR DESCRIPTION
**Pull request by raulsntos**
- Use the name, file path and line number of the caller that invokes `GD.PushError` and `GD.PushWarning` instead of the location in the C++ `runtime_interop.cpp` file.
	- See https://github.com/godotengine/godot/pull/71943#issuecomment-1415809223.
- ~Deprecate `GD.PushError` and `GD.PushWarning` overloads that take a `params` parameter, since those can't be used with [Caller] attributes and the reported error location will be the `GD.cs` file.~
- ~Remove `GD.PushError` and `GD.PushWarning` overloads that take a single string parameter. This breaks compatibility but otherwise overload resolution will prefer them over the new overloads, which defeats the purpose of this PR.~
	- ~Interestingly, I'm the one that added those overloads as performance optimization in https://github.com/godotengine/godot/pull/71946.~
	- ~This breaks binary compatibility but not source compatibility, meaning that it only breaks for users that are calling these methods from a library that was built for 4.0 - 4.1. Users calling these methods directly in their game code will be unaffected.~
- Improvements to getting the C# stack trace.
  - Use C# type keywords for built-in types in method declarations.
  - Remove extra space before each parameter in method declarations.
  - Skip one more frame to avoid `NativeInterop.NativeFuncs`.
	  - Fixes https://github.com/godotengine/godot/issues/79449.
  - Skip methods annotated with the `[StackTraceHidden]` attribute.
- Improvements to `ScriptEditorDebugger` when source is in project.
  - Avoid overriding error metadata when the source is inside the project file.
    - Fixes https://github.com/godotengine/godot/issues/72662.
    - May fix https://github.com/godotengine/godot/issues/76415.
  - Use the source function in the title when the source is inside the project file.

Users that use these methods would expect the reported location printed by these methods to correspond to a location in their project source files. Specifically, they'd expect to see the file path and line number at which they call these methods, and not the location of the C++ code (which is always the same). Now, these methods are a lot more useful since users can know which line in their source code printed the error/warning.

4.1.stable | This PR
-|-
error4.1 | error4.2

### CODE REVIEW

**Comment by raulsntos** [comment]
Removed the `breaks compat` label, since I changed this to avoid breaking compatibility.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs [hunk 1]
```diff
@@ -334,6 +335,21 @@ public static void PrintT(params object[] what)
             NativeFuncs.godotsharp_printt(godotStr);
         }
 
+        [StackTraceHidden]
+        private static void ErrPrintError(string message, godot_error_handler_type type = godot_error_handler_type.ERR_HANDLER_ERROR)
+        {
+            // Skip 1 frame to avoid current method.
```
Comment (RedworkDE) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:341]: I still get `GD.PushError` instead of its caller as the location of the error.

**Review by RedworkDE — COMMENTED** [review]
If the a stack from is from source generated code attempting to open its source will fail because the source doesn't exist:
```
ERROR: Cannot open file 'C:/dir/Net7/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/Test_Node_ScriptMethods.generated.cs'.
   at: (modules\mono\utils\string_utils.cpp:152)
ERROR: Failed to read file: 'C:/dir/Net7/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/Test_Node_ScriptMethods.generated.cs'.
   at: (modules\mono\csharp_script.cpp:2754)
ERROR: Cannot load C# script file 'C:/dir/Net7/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/Test_Node_ScriptMethods.generated.cs'.
   at: (modules\mono\csharp_script.cpp:2820)
ERROR: Failed loading resource: C:/dir/Net7/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/Test_Node_ScriptMethods.generated.cs. Make sure resources have been imported by opening the project in the editor at least once.
   at: (C:\dir\godot_4.0.1\core/io/resource_loader.cpp:274)
```
(Same probably happens for libraries where the sources are not available, but paths are embedded in the pdb)
Can we pretend that we don't know about the source file if it doesn't exist and avoid these errors?
Also If you open a frame from a file that does exist but is not part of the project, the editor tries to convince you to save it as part of the project, if you save any script.

Also about the formatting of method signatures: if we want to format them in C# style, reference parameters are formatted as `Type&` instead of `ref Type` and inner types as `Outer+Inner` instead of `Outer.Inner`

File: modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs (hunk 1 above)
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:341]: You mean in the root tree item? The `<C# Source>` item? Or the first item of `<Stack Trace>`? See the image attached to the PR description. The `GD.PushError` calls are still part of the stack trace, are you suggesting to remove them?

File: modules/mono/glue/GodotSharp/GodotSharp/Core/DebuggingUtils.cs [hunk 2]
```diff
@@ -70,13 +102,26 @@ public unsafe void Dispose()
             }
         }
 
+        internal static unsafe StackFrame? GetCurrentStackFrame(int skipFrames = 0)
+        {
+            // We skip 2 frames:
+            // The first skipped frame is the current method.
```
[the remark this answers is not in the document]
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/DebuggingUtils.cs:108]: That's a really good point, I don't know.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs (hunk 1 above)
Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:341]: It looks like this: image on my end (v4.2.dev.mono.custom_build [13ab2b6f4]) and I would expect it to look like in the PR description. Not sure if you broke something when updating this or if something is different on my system.

Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:341]: That's weird, I have checked again and I'm getting the same result as the screenshot in the PR description.

image

Judging from your screenshot, it seems it doesn't consider `Test_Node.cs` to be inside the project, since it's printing the absolute path.

The `ErrPrintError` method should be localizing that path, which makes it a `res://` path, then `ScriptEditorDebugger` checks if the path starts with `res://` to determine if it's inside the project.

Comment (RedworkDE) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:341]: I started over with a fresh project that doesn't have all kinds of crap in it and the issue still exists.

It's a windows only `localize_path` bug: `GetFileName()` returns a path with `\` as path separators, but while it will convert them to `/` it only does so after checking if the path is local, so you need to either replace `\` before or call localize_path twice.

Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:341]: If it's a bug in `localize_path` I'd rather have that fixed in a separate PR, since it seems like you have already fixed it can you open a PR?

Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs:341]: - Should be resolved by https://github.com/godotengine/godot/pull/79342.

**Comment by RedworkDE** [comment]
> There is a check to avoid the source function if it's not part of the project. It only checks the path, is that check not enough?

What check do you mean?

https://github.com/godotengine/godot/blob/202e4b2c1e7f8b25738b93d0e4d5066453d3edf3/core/io/resource_loader.cpp#L276-L279

Could only trigger if the previous errors didn't happen.

I would add a single error to this function: (tho I suppose we could do that in a different PR as well)
https://github.com/godotengine/godot/blob/202e4b2c1e7f8b25738b93d0e4d5066453d3edf3/editor/debugger/editor_debugger_node.cpp#L142-L145

**Comment by raulsntos** [comment]
> What check do you mean?

This one:

https://github.com/godotengine/godot/blob/13ab2b6f4f61dbfb4f90c6602f126c247d4c38c5/editor/debugger/script_editor_debugger.cpp#L495

https://github.com/godotengine/godot/blob/13ab2b6f4f61dbfb4f90c6602f126c247d4c38c5/editor/debugger/script_editor_debugger.cpp#L608-L611

The metadata is then used to determine which file to open:

https://github.com/godotengine/godot/blob/13ab2b6f4f61dbfb4f90c6602f126c247d4c38c5/editor/debugger/script_editor_debugger.cpp#L1486-L1491

> I would add a single error to this function: (tho I suppose we could do that in a different PR as well)

I'd prefer to do it in a different PR.

**Review by RedworkDE — APPROVED** [review]
Needs https://github.com/godotengine/godot/pull/79342 to work correctly on windows, but is still a significant improvement without.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/DebuggingUtils.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/DebuggingUtils.cs:108]: Is this still a concern or is this not a problem since it's only going to execute in Debug builds which hopefully disable inlining optimizations?

**Comment by akien-mga** [comment]
Thanks!
