### PR TITLE
Editor now shows error when debug port is in use

### LINKED ISSUE #9096: No output when debug port in use
**Operating system or device - Godot version:**

Ubuntu 14.04. Godot 2.1.3

**Issue description:**

No output when running (console).

**Steps to reproduce:**

This seems to happen when something is using the debug port. See reports https://godotengine.org/qa/9453/debugger-and-output-malfunction and https://godotengine.org/qa/630/output-debug-messages-suddenly-stop-working-possible-causes.

No message showing what happened. You just have to know that is the issue (and then change the debug port number in Debug settings).

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by Faless**
This PR fixes #9096 , well, actually it just notify the user that the editor cannot listen to the given host/port.

The cause for that could be more than just the port is in use, but I guess it's just the most common scenario.

The editor will still end up unable to catch output from the child process and the stop button will not work.
I don't know if there's a better fix to that second problem, but I'm pretty busy with work, and I don't have much time to fiddle around (I tried calling `stop()` immediately but it didn't work).

### CODE REVIEW

File: editor/script_editor_debugger.cpp [hunk 1]
```diff
@@ -1042,7 +1042,10 @@ void ScriptEditorDebugger::start() {
 		perf_max[i] = 0;
 	}
 
-	server->listen(port);
+	if (server->listen(port) != OK) {
+		EditorNode::get_log()->add_message("** Error listening to debug host/port **");
```
Comment (bojidar-bg) [inline editor/script_editor_debugger.cpp]: Shouldn't it be "Error listening **on** debug host/port"?

Comment (volzhs) [inline editor/script_editor_debugger.cpp]: it would be better to print host/port number too.

**Comment by Faless** [comment]
Yay, the editor now also displays the debug host address and port number where it was trying to listen **on** (:wink:) when failing.
Additionally, I think I fixed the `network/debug/remote_port` setting which was broken (always defaulting to 6007).
I tested it a bit, it seems to be working fine now, but I couldn't test the android deploy since I can't generate the android templates (I think the TinyEXR inclusion broke it).
I'm not sure why the option was defined as a value in GlobalConfig, since it should be taken care of by the export flags when not running from the editor (if I understood that part correctly).

**I think it needs some more testing before merging.**

File: main/main.cpp [hunk 2]
```diff
@@ -581,12 +581,11 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 	GLOBAL_DEF("memory/multithread/thread_rid_pool_prealloc", 60);
 
 	GLOBAL_DEF("network/debug/max_remote_stdout_chars_per_second", 2048);
-	GLOBAL_DEF("network/debug/remote_port", 6007);
```
Comment (akien-mga) [inline main/main.cpp]: I think you need to keep that one to get it registered in the project settings. Here's what I have with your PR:
spectacle j17470

Comment (Faless) [inline main/main.cpp]: Okay, what I don't understand than is why do we need it in the project setting instead of just the editor settings?

I think in the end there are 2 pairs or values:
1. Listen port, listen address (`*`,`0.0.0.0`,`::`, or a specific interface) (editor)
2. Connect port, connect address (specific interface) (project)

The connection address and port can be set passing the `-rdebug IP:PORT` command line option. On exported projects (i.e. android run) that argument is set as an export flag in the data pack from the editor address and port.
Of course, the ports and addresses must match or it won't work.

The editor does not have a button to just listen for connection, but I guess it could in the future.

Is there any case where we would want to set the connect address and port via the project settings? What would be the reason behind that?

In fact, I'm okay in separating the client and server options, I'm just afraid it might gets confusing.
Suggestions are welcome.

Comment (akien-mga) [inline main/main.cpp]: Oh my bad, I hadn't noticed there were both the project and editor settings involved here. I'm fine with having the setting only at the editor level; if a need arises to have it project-specific, it can likely be added at that time.

**Comment by reduz** [comment]
Wait, I think this is getting pretty complicated, here are some things I don't understand.

1)  Why would the port be in use?
2) Can't a workaround be simple like just simply increasing the port number until opening succeeds? Client won't be launched until after the port is opened anyway..

**Comment by vnen** [comment]
Answering for what I know:

1. The port might be in use by another application (I had this problem with Dropbox). Also, there are other problems that may fail the connection, like a firewall setting.
2. Increasing the port seems very hacky. If the problem is the firewall, it'll never succeed. And in my experience the game is launched just fine, it just fails to connect to the editor debugger.

**Comment by reduz** [comment]
Ah I see, maybe we should choose another port them? Is there a way to tell which port range is less crowded?

Also I never meant incrementing infinitely, but more like trying a few times and then throw an error

**Comment by akien-mga** [comment]
As discussed on IRC, the current PR is good already; another later improvement could be to add some logic to try unused ports as fallback if the configured one doesn't work.
