### PR TITLE
Right-clicking with copied tiles cancels it

### LINKED ISSUE #55425: Right-clicking with copied tiles will still place them
### Godot version

69a194f

### System information

W10

### Issue description

Technically this is not a bug, because it might be intended, but when you right-click with pasted tiles, the tiles will still be placed. This is not an expected behavior.
gGAUNTnuOC
Right click should instead cancel the operation without drawing tiles.

### Steps to reproduce

1. Draw some tiles on TileMap
2. Select them
3. Ctrl + C
4. Ctrl + V
5. Right-click

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by fazil47**
This PR cancels the TileMap copying operation on right mouse click (this fixes #55425)

### CODE REVIEW

File: editor/plugins/tiles/tile_map_editor.cpp [hunk 1]
```diff
@@ -598,7 +598,9 @@ bool TileMapEditorTilesPlugin::forward_canvas_gui_input(const Ref<InputEvent> &p
 				}
 
 				if (drag_type == DRAG_TYPE_CLIPBOARD_PASTE) {
-					// Do nothing.
+					if (mb->get_button_index() == MouseButton::RIGHT) {
```
Comment (groud) [inline editor/plugins/tiles/tile_map_editor.cpp:601]: Could you add a comment there? Something like "Cancel tile pasting on right-click"
This function is quite big, and such comment help to understand faster what each block of code is for.

Comment (fazil47) [reply editor/plugins/tiles/tile_map_editor.cpp:602]: Done.

**Comment by groud** [comment]
Looks good to me, but you should squash your commit together for the PR to be merged. See the [PR workflow](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase).

**Comment by fazil47** [comment]
I've squashed my commits, ready for merging hopefully :)

**Review by groud — APPROVED** [review]

**Comment by groud** [comment]
Perfect, thanks!
And congrats for your first merged contribution!
