### PR TITLE
Windows: Fix `window_get_size_with_decorations` returning an invalid size when restoring from minimize

### LINKED ISSUE #79754: Root window gets smaller after minimizing with much bigger max_size set.
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)

### Issue description

Setting max_size property on the root window causes it to resize after minimizing it to task bar and bringing back.
In the following example the set max size is the size of the whole recorded screen, so it shouldn't interfere with the size of the window.

https://github.com/godotengine/godot/assets/84321760/aedff4ef-fd71-4a14-bfcb-ba54f6047c04

### Steps to reproduce

0. Use the minimal reproduction project.
1. Run the project.
2. Minimize the window by manually clicking minimize on its menu bar.
3. Bring back the window by clicking it on the task bar.
4. Observe that the size of the window is smaller than before.

### Minimal reproduction project

[Window-Size-Changes-Test-4.1.1.zip](https://github.com/godotengine/godot/files/12131108/Window-Size-Changes-Test-4.1.1.zip)

### PR DESCRIPTION
**Pull request by Noojuno**
Fixes #79754.

In Windows (replicated in Windows 10 & 11), minimizing then restoring a window that has both a `size` and a `max_size` set will cause the window to shrink to the smallest size window possible.

This PR fixes it by storing the width and height from `GetWindowRect()` and reading from that if the window is minimized. This is the exact same way we already solve the issue when reading from `GetClientRect()` in `window_get_size`.

**Before**

https://github.com/user-attachments/assets/4c311a54-4379-4388-91c5-00ae9c0a9083

**After**

https://github.com/user-attachments/assets/d6f693ac-7ab3-48a1-8cd1-e530447bc3e8

**Minimum reproduction**

[min-rep-resize_2025-11-08_20-39-42.zip](https://github.com/user-attachments/files/23430597/min-rep-resize_2025-11-08_20-39-42.zip)

### CODE REVIEW

File: platform/windows/display_server_windows.h [hunk 1]
```diff
@@ -341,6 +341,7 @@ class DisplayServerWindows : public DisplayServer {
 		Size2 min_size;
 		Size2 max_size;
 		int width = 0, height = 0;
+		int window_width = 0, window_height = 0;
```
Comment (bruvzg) [inline platform/windows/display_server_windows.h]: Maybe `width_with_decorations` / `height_with_decorations`, `window_x` will be confusing.

**Review by bruvzg — APPROVED** [review]

File: platform/windows/display_server_windows.h (hunk 1 above)
Comment (Noojuno) [reply platform/windows/display_server_windows.h]: Yeah I wasn't super happy with the naming here. Updated to match your suggestion.

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
