### PR TITLE
Ensure KinematicBodies only interact with other Bodies with matching mask.

### LINKED ISSUE #15243: KinematicBody/2D uses any combination of layer-mask for move_* collision detection
**Godot version: 3.0 d6a1125, 2.1.4**

**Issue description:**
KinematicBody2D move methods collides against bodies if the other bodies have the kinematic layer on the collision mask, meaning KB is using the layer too, not the mask only for collision resolution.

The expected is for the body to ignore the others that are not in their masks, this issue makes some common setups more complicated than they should, and renders the `move_*` methods almost useless.

**Steps to reproduce:**
 - Create a KinematicBody2D on layer 2.
 - Create another body with mask 2.
 - `move_and_slide` or `move_and_collide` the KB against the other body.
 - Watch how collides when should not.

**Minimal reproduction project:**
[KBmaskbug.zip](https://github.com/godotengine/godot/files/1596156/KBmaskbug.zip)

Probably related to #7644

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, when a `KinematicBody` collides with another `CollisionObject` the `collision_layer`->`collision_mask` combination is checked both ways. This results in unintended and unwanted collisions. For example, you may want a bullet to be stopped by a shield, but not a shield to be stopped by a bullet.

This PR ensures that `KinematicBodies` only collide with `CollisionObjects` that have one of the `KinematicBody`'s `collision_layer` bits in the other `CollisionObject`'s `collision_mask`. It fixes both 2D and 3D (Godot and Bullet) physics.

This PR is the `KinematicBody` sister to #42268, which fixes `collision_layer`->`collision_mask` checks for `Area`s.

Fixes #15243.

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge of #43952.

**Comment by madmiraal** [comment]
Rebased following merge of #46917 and #46937.

**Comment by pouleyKetchoupp** [comment]
Now we have an approved proposal:
https://github.com/godotengine/godot-proposals/issues/2775

So this change is welcome for 4.0, the PR just needs a rebase.

**Review by pouleyKetchoupp — APPROVED** [review]
I haven't tested the changes in Bullet, but they look ok.
Works fine in Godot Physics.

**Comment by akien-mga** [comment]
Thanks!

File: servers/physics_3d/space_3d_sw.cpp [hunk 1]
```diff
@@ -549,7 +549,7 @@ int Space3DSW::_cull_aabb_for_body(Body3DSW *p_body, const AABB &p_aabb) {
 			keep = false;
 		} else if (intersection_query_results[i]->get_type() == CollisionObject3DSW::TYPE_SOFT_BODY) {
 			keep = false;
-		} else if ((static_cast<Body3DSW *>(intersection_query_results[i])->test_collision_mask(p_body)) == 0) {
+		} else if (!p_body->layer_in_mask(static_cast<Body3DSW *>(intersection_query_results[i]))) {
```
Comment (pouleyKetchoupp) [inline servers/physics_3d/space_3d_sw.cpp:552]: Actually after doing more tests I realized this layer check is inverted, a kinematic body should collide with objects it scans in its own mask, not objects which have its own layer in their mask. I'll make a fix in another PR.

Comment (madmiraal) [reply servers/physics_3d/space_3d_sw.cpp:552]: This is the correct way around. A `KinematicBody` should only interact with other `Bodies` that have a matching mask.

Comment (pouleyKetchoupp) [reply servers/physics_3d/space_3d_sw.cpp:552]: The way you implemented things, walls would define what they stop instead of moving bodies what they collide with. That would be a nightmare for users to setup.

Comment (madmiraal) [reply servers/physics_3d/space_3d_sw.cpp:552]: You're right. Its mask is the layers it sees. So it is the other way around.

Comment (madmiraal) [reply servers/physics_3d/space_3d_sw.cpp:552]: It probably makes more sense then to revert the logic (and the name) of `layer_in_mask` to `mask_has_layer`.
