### PR TITLE
Preserve emission ring shape properties during conversion from GPUParticles3D to CPUParticles3D and vice versa

### LINKED ISSUE #100946: Converting GPUParticles3D to CPUParticles3D (or vice versa) doesn't preserve ring emission shape properties
### Tested versions

- Reproducible in: 4.4.dev7

### System information

Godot v4.4.dev7 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6636) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Converting GPUParticles3D to CPUParticles3D (or vice versa) doesn't preserve ring emission shape properties. In comparison, most other emission shape properties (point, box, sphere, sphere surface) are preserved both ways.

This should be straightforward to resolve by modifying `gpu_particles_3d.cpp` and `cpu_particles3D.cpp`'s `convert_from_particles()` methods. Read the properties from the source node and apply them to the newly created node.

### Before converting to CPUParticles3D

Image

### After converting to CPUParticles3D

Image

### Before converting to GPUParticles3D

Image

### After converting to GPUParticles3D

Image

### Steps to reproduce

- Create a CPUParticles3D node with a ring emission shape and non-default values for the height, inner radius, outer radius and angle.
- Convert it to GPUParticles3D using the menu at the top of the 3D editor viewport.
- Notice how the ring reverts to its default cylinder-like appearance.
- Change the properties in ParticleProcessMaterial, then convert it back to CPUParticles3D.
- Notice how the shape reverts to its default cylinder-like appearance again.

### Minimal reproduction project (MRP)

[test_particles_ring_conversion.zip](https://github.com/user-attachments/files/18276894/test_particles_ring_conversion.zip)

### PR DESCRIPTION
**Pull request by zachseiss**
* Fixes: #100946

### CODE REVIEW

**Comment by AThousandShips** [comment]
This commit isn't by your account, are you the author of this?

**Comment by zachseiss** [comment]
> This commit isn't by your account, are you the author of this?

I am!  The global email property for my git was set to the email for my old account.

File: scene/3d/cpu_particles_3d.cpp [hunk 1]
```diff
@@ -1392,6 +1392,11 @@ void CPUParticles3D::convert_from_particles(Node *p_particles) {
 
 	set_color(material->get_color());
 
+	set_emission_ring_height(material->get_emission_ring_height());
+	set_emission_ring_radius(material->get_emission_ring_radius());
+	set_emission_ring_inner_radius(material->get_emission_ring_inner_radius());
+	set_emission_ring_cone_angle(material->get_emission_ring_cone_angle());
```
Comment (paddy-exe) [inline scene/3d/cpu_particles_3d.cpp:1398]: These changes belong further down with the other emission shape calls

File: scene/3d/gpu_particles_3d.cpp [hunk 2]
```diff
@@ -606,6 +606,11 @@ void GPUParticles3D::convert_from_particles(Node *p_particles) {
 	proc_mat->set_flatness(cpu_particles->get_flatness());
 	proc_mat->set_color(cpu_particles->get_color());
 
+	proc_mat->set_emission_ring_height(cpu_particles->get_emission_ring_height());
+	proc_mat->set_emission_ring_radius(cpu_particles->get_emission_ring_radius());
+	proc_mat->set_emission_ring_inner_radius(cpu_particles->get_emission_ring_inner_radius());
+	proc_mat->set_emission_ring_cone_angle(cpu_particles->get_emission_ring_cone_angle());
```
Comment (paddy-exe) [inline scene/3d/gpu_particles_3d.cpp:612]: Same as above

**Review by paddy-exe — CHANGES_REQUESTED** [review]

**Review by paddy-exe — APPROVED** [review]
LGTM. Should be squashed as well now so it can be merged👍🏻

File: scene/3d/cpu_particles_3d.cpp (hunk 1 above)
Comment (zachseiss) [reply scene/3d/cpu_particles_3d.cpp]: I made the recommended changes and pushed them to my fork

**Comment by zachseiss** [comment]
> LGTM. Should be squashed as well now so it can be merged👍🏻

haha ok will need to do some googling to figure out how to do that

**Comment by paddy-exe** [comment]
The commit message needs cleanup now. You merged them together but you can clean it up by amending your commit again
`git commit --amend`

File: scene/3d/cpu_particles_3d.cpp [hunk 3]
```diff
@@ -1409,6 +1409,11 @@ void CPUParticles3D::convert_from_particles(Node *p_particles) {
 	set_emission_shape(EmissionShape(material->get_emission_shape()));
 	set_emission_sphere_radius(material->get_emission_sphere_radius());
 	set_emission_box_extents(material->get_emission_box_extents());
+	set_emission_ring_height(material->get_emission_ring_height());
+	set_emission_ring_radius(material->get_emission_ring_radius());
+	set_emission_ring_inner_radius(material->get_emission_ring_inner_radius());
+	set_emission_ring_cone_angle(material->get_emission_ring_cone_angle());
+
```
Comment (akien-mga) [inline scene/3d/cpu_particles_3d.cpp:1416]: There seems to be a trailing tab on this line that should be removed to follow the style guide.

You can make sure to apply style changes automatically by setting up `pre-commit` locally with:
```
pip install pre-commit
pre-commit install
```
in the Godot repo.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by zachseiss** [comment]
> Thanks! And congrats for your first merged Godot contribution 🎉

Thank you!
