### PR TITLE
Autocompletion: Don't use `next` for `GET_NODE` inference

### LINKED ISSUE #107626: Code complete on $-derived variables doesn't work past the 2nd statement
### Tested versions

Reproduced in:
- v4.4.1.stable.fedora [49a5bc7b6] (latest stable build)
- v4.5.dev5.official [64b09905c] (latest dev build)

### System information

Godot v4.4.1.stable (49a5bc7b6) - Fedora Linux 42 (Workstation Edition) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 threads)

### Issue description

The `$Selector` syntax is sugar for **Node.get_node()** with a quality-of-life bonus in the script editor: it is aware of the actual node class and thus offers a complete list of members is the picklist. However, when assigned to a variable, it works only on the immediate statement, and not past the 2nd one. Let me demonstrate.

Assume a simple scene with a single child node **Label**. I `$`-select the child and store it in a var.

✅ On the next line in my script, I get a complete picklist of the **Label** members, **get_line_count()** is one of them.

❌ On lines not immediately followed by the var assignment, I get a picklist for **Node** class only. E.g. the aforementioned **Label**'s method **get_line_count()** is not offered anymore.

### Steps to reproduce

1. Make a new, blank project.
2. Create a 2D scene (Node2D).
3. Add a child node, say Label.
4. Attach a script to the root node Node2D.
5. Try:
```
extends Node2D
func _ready() -> void:
	var lbl := $Label
	# Try code complete "lbl.getlc" on this line: get all Label members
	var _foo := 42
	# ...and then try code complete "lbl.getlc" on this line: get Node members only
```

### Minimal reproduction project (MRP)

Added upon request: [complete-node-reference-bug.zip](https://github.com/user-attachments/files/20778157/complete-node-reference-bug.zip)

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/107626

`Node->next` is a parser detail and has no semantic meaning. Using it for completion or analyzing is highly unreliable.

### CODE REVIEW

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -3142,8 +3142,21 @@ static bool _get_subscript_type(GDScriptParser::CompletionContext &p_context, co
 					}
 				} break;
 				case GDScriptParser::IdentifierNode::Source::LOCAL_VARIABLE: {
-					if (identifier_node->next != nullptr && identifier_node->next->type == GDScriptParser::ClassNode::Node::GET_NODE) {
-						get_node = static_cast<GDScriptParser::GetNodeNode *>(identifier_node->next);
+					// TODO: Do basic assignment flow analysis like in `_guess_expression_type`.
```
Comment (Mickeon) [inline modules/gdscript/gdscript_editor.cpp:3145]: What do you mean by the comment?

Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp:3145]: The standard code path for type detection takes assignments into account when picking the expression from which to guess the type.
```gdscript
var a
a = "hello"
a. # suggests string methods
```

This special code path for GET_NODE does not do that right now and only works with the initializer of the variable.

But to support that without duplicating a lot of code, we'd probably need to remove `_get_subscript_type` and integrate GET_NODE into the standard `_guess_expression_type` code path. So it isn't a quick fix, which is why I just added a comment about it for now.

**Review by vnen — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
