### PR TITLE
Fix `get_rpm()` on wheel which has steering

### LINKED ISSUE #101646: get_rpm() on VehicleWheel3D is calculated incorrectly
### Tested versions

- Reproducible in: 4.2 stable, 4.3 stable, 4.4.dev7, 4.4 stable

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.26100 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (Intel Corporation; 31.0.101.2130) - Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 Threads)

### Issue description

When you call get_rpm on a VehicleWheel3D when the steering angle is not equal to 0, it returns the wrong RPM. The only workaround I have found is to use trigonometry:
```gdscript
var corrected_rpm = wheel.get_rpm() / cos(wheel.steering)
```

### Steps to reproduce

- Create a VehicleBody3D
- Create a VehicleWheel3D as a child
- Spin up the wheel (engine_force or with friction against the ground)
- Turn the wheel with steering on the VehicleBody3D
- Call get_rpm() on the VehicleWheel3D which now gives the wrong rpm

### Minimal reproduction project (MRP)

[vehicle-bug.zip](https://github.com/user-attachments/files/18447812/vehicle-bug.zip)

### PR DESCRIPTION
**Pull request by drakeerv**
This fixes #101646. There are still some issues with VehicleBody3D but this fixes the problem in the issue.

### CODE REVIEW

**Comment by fire** [comment]
# Test plan

Download https://github.com/user-attachments/files/18447812/vehicle-bug.zip

Test the bug recreation steps.

2. Create a VehicleBody3D
3. Create a VehicleWheel3D as a child
4. Spin up the wheel (engine_force or with friction against the ground)
5. Turn the wheel with steering on the VehicleBody3D
6. Call get_rpm() on the VehicleWheel3D which now gives the wrong rpm

File: scene/3d/physics/vehicle_body_3d.cpp [hunk 1]
```diff
@@ -852,18 +852,26 @@ void VehicleBody3D::_body_state_changed(PhysicsDirectBodyState3D *p_state) {
...
+			// Get forward vector
 			Vector3 fwd(
 					chassisWorldTransform.basis[0][Vector3::AXIS_Z],
 					chassisWorldTransform.basis[1][Vector3::AXIS_Z],
 					chassisWorldTransform.basis[2][Vector3::AXIS_Z]);
 
+			// Apply steering rotation to forward vector for steerable wheels
+			if (wheel.steers) {
+				Basis steeringMat(Vector3(0, 1, 0), wheel.m_steering);
+				fwd = steeringMat.xform(fwd);
```
Comment (Calinou) [inline scene/3d/physics/vehicle_body_3d.cpp:869]: Use snake_case and C-style initialization syntax:

```suggestion
				Basis steering_mat = Basis(Vector3(0, 1, 0), wheel.m_steering);
				fwd = steering_mat.xform(fwd);
```

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

I've also tested this on a modified Truck Town but don't notice much difference in the reported wheel RPM (likely because the steering range is more limited).

**Testing project:** [truck_town.zip](https://github.com/user-attachments/files/18493353/truck_town.zip)

**Comment by drakeerv** [comment]
I fixed the formatting issues.

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by drakeerv** [comment]
Done!

**Comment by akien-mga** [comment]
GitHub seemed to be stuck in a loop assessing the mergeability of this PR, so I pushed a rebase directly as it was ~1500 commits behind `master`.

**Comment by drakeerv** [comment]
> GitHub seemed to be stuck in a loop assessing the mergeability of this PR, so I pushed a rebase directly as it was ~1500 commits behind `master`.

Do you need me to do anything?

**Comment by akien-mga** [comment]
Nope, it's ready to merge in an upcoming batch.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged commit! 🎉
