### PR TITLE
Remove auto disabling of the split-view in the FileSystem dock

### LINKED ISSUE #21499: Filesystem bottom box should scale, not disappear
**Godot version:**

current tip
0565adb20ff01a758c5ae8e4534a2cb7f07952df

**OS/device including version:**

Linux

**Issue description:**

peek 2018-08-27 20-51

### LINKED ISSUE #22307: New "Toggle split mode" button sometimes stops working
**Godot version:**
8e4b18a

**OS/device including version:**
Win10

**Issue description:**
image

**Steps to reproduce:**
Click it several times or switch to internal folder, Im not found the pattern which causes it

### PR DESCRIPTION
**Pull request by groud**
Closes #21499
Closes #22307

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -223,11 +223,9 @@ void FileSystemDock::_update_tree(const Vector<String> p_uncollapsed_paths, bool
 }
 
 void FileSystemDock::_update_display_mode() {
-	bool compact_mode = get_size().height < int(EditorSettings::get_singleton()->get("docks/filesystem/split_mode_minimum_height"));
-
 	// Compute the new display mode
 	DisplayMode new_display_mode;
-	if ((display_mode_setting == DISPLAY_MODE_SETTING_TREE_ONLY) || compact_mode) {
+	if ((display_mode_setting == DISPLAY_MODE_SETTING_TREE_ONLY)) {
```
Comment (akien-mga) [inline editor/filesystem_dock.cpp]: You can remove the extra pair of parentheses now.

Comment (groud) [reply editor/filesystem_dock.cpp]: Done
