### PR TITLE
Working autocomplete for $" and $'

### LINKED ISSUE #20811: Autocomplete for $ syntax sugar does not see children if "" are used.
**Godot version:**
3.0.6

**OS/device including version:**

Windows 7 Pro SP1

**Issue description:**
Autocomplete does not recognize node's children if i use quotation after dollar. It does, however, if only dollar is used.

**Steps to reproduce:**
Open Node.gd script, put your cursor at the end of line with '$"' and trigger autocomplete.

**Minimal reproduction project:**
https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/DollarAutocomplete

### PR DESCRIPTION
**Pull request by hilfazer**
Fixes #20811.

Problem was caused by $ (no quotes) syntax. If dollar is detected quotation is stripped off node paths regardless of quotation being written after dollar or not. So "" / '' were removed in all following cases:
$
$'
$"

Quotes are still stripped ( in function GDScriptLanguage::complete_code(), file gdscript_editor.cpp) but now they are added back if $ is followed by " or '.

### CODE REVIEW

**Review by Paulb23 — APPROVED** [review]
Nice fix! LGTM.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -5718,13 +5718,19 @@ void TextEdit::_update_completion_candidates() {
 
 	bool inquote = false;
 	int first_quote = -1;
+	char restore_quotes = -1;
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: Is there any advantage in using a signed char here instead of a plain int?

Comment (hilfazer) [reply scene/gui/text_edit.cpp]: Not really. It can take less space, depending on compiler. But that's not a big advantage by any means so i can change it to something else, no problem.

Comment (akien-mga) [reply scene/gui/text_edit.cpp]: Given that char signedness can be toggled on/off by a compiler flag and is implementation specific, I think using `int` would be safer yes.

**Comment by akien-mga** [comment]
Please squash commits together.

**Comment by hilfazer** [comment]
Squashed.

**Comment by akien-mga** [comment]
Thanks!
