### PR TITLE
Avoid double editing when clicking AnimatedSprite

### LINKED ISSUE #83256: Output error when select a AnimatedSprite2D node in the editor
### Godot version

4.1.2, 4.2, WebEditor

### System information

Windows, WebEditor

### Issue description

The output print this error everytime a AnimatedSprite2D node is selected in editor:

editor/editor_node.cpp:8223 - Condition "plugins_list.has(p_plugin)" is true.

I've noticed the same error when select a TileMap node, it's seems to be related to the handling of nodes that uses plugins to menage graphics etc... (here: #83185)

### Steps to reproduce

Add an AnimatedSprite2D node and add some graphics in the default animation, then select the node in tree.

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #83256
Caused by sprite frames plugin handling AnimatedSprite and then the attached SpriteFrames.

### CODE REVIEW

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -2325,7 +2329,7 @@ bool SpriteFramesEditorPlugin::handles(Object *p_object) const {
 	if (animated_sprite_3d && *animated_sprite_3d->get_sprite_frames()) {
 		return true;
 	}
-	return p_object->is_class("SpriteFrames");
+	return !frames_editor->is_editing() && Object::cast_to<SpriteFrames>(p_object);
```
Comment (akien-mga) [inline editor/plugins/sprite_frames_editor_plugin.cpp:2332]: That pattern is a bit unconventional, what makes SpriteFrames special compared to other editor plugins which handle resources?

Comment (KoBeWi) [reply editor/plugins/sprite_frames_editor_plugin.cpp:2332]: It handles both AnimatedSprite nodes and SpriteFrames resource. (handling nodes allows opening the editor when the resource is folded)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: editor/plugins/sprite_frames_editor_plugin.cpp (hunk 1 above)
Comment (kleonc) [reply editor/plugins/sprite_frames_editor_plugin.cpp:2332]: This new logic is incorrect, e.g. if you have selected/edited an AnimatedSprite2D with a valid SpriteFrames and then try to edit another SpriteFrames (e.g. by double clicking in the FileSystem dock a different SpriteFrames resource file) then the SpriteFrames edited by the plugin wouldn't be changed, this new logic would refuse to edit another SpriteFrames object.

Shouldn't it be simply checking whether it's a SpriteFrames different then the currently edited one? :thinking:

Comment (KoBeWi) [reply editor/plugins/sprite_frames_editor_plugin.cpp:2332]: I tested that and the editor is clearing the frame before editing a new one.
Or at least does something that makes it work.
But yes, if it turns out broken, it should also check if the new SpriteFrames are different.

**Comment by Jiayibingping** [comment]
Hello, it seems it still hasn't been fixed...[https://github.com/godotengine/godot/issues/97577#issuecomment-2466052155](url)
