### PR TITLE
Fix process mode update when mode owner is set to Inherit

### LINKED ISSUE #49818: Setting node `process_mode` to `Disabled` then back to `Inherit` doesn't reset the mode properly
### Godot version

3.3.2.stable, 4.0.dev (92f20fd70e6957cd65ccb7837fdc28f9b1e4a315)

### System information

Windows 10

### Issue description

When changing the `process_mode` property on a node that is at least 2 levels deep in the tree (both parents are set to `Inherited`), setting the mode back to `Inherited` doesn't reset the current state properly.

Example in the editor: the node stays grayed out even after setting it back to `Inherited`. Its state is reset properly only after setting the parent node to any mode then back to `Inherited`:

### Steps to reproduce

Using the minimal reproduction project:
1. Open project in editor
2. Select `Node3` in the scene tree
3. Set `process_mode` to `Disabled`
4. Observe the node is grayed out (correct)
5. Set `process_mode` back to `Inherited`
6. Observe the node is still grayed out (incorrect)

### Minimal reproduction project

[disable-node-bug-4.0.zip](https://github.com/godotengine/godot/files/6690185/disable-node-bug-4.0.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
~When the process mode owner is the root and is set to `PROCESS_MODE_INHERIT`, the mode needs to be considered as the default (`PROCESS_MODE_PAUSABLE`) instead of making the node disabled.~

Fixes #49818

**Edit: refactored based on https://github.com/godotengine/godot/pull/49819#issuecomment-912971626**

Prevent the root node to be set to `PROCESS_MODE_INHERIT`, since it causes undefined behavior.

Fix a case where the process owner node is wrongly set to the directparent instead of the proper node.

Add errors for all unhandled cases.

### CODE REVIEW

**Comment by reduz** [comment]
Ah right, the root node. I think for simplicity it should be set to PAUSABLE by default, and if changing the mode to INHERIT should error if `is_inside_tree() && get_tree()->get_root() == this`. We could probably do a consistency check with `unlikely()` and throw an error in the `can_process` function if the owner is set to inherit, as this would be a bug.

File: scene/main/node.cpp [hunk 1]
```diff
@@ -437,18 +439,18 @@ void Node::set_process_mode(ProcessMode p_mode) {
 	bool prev_can_process = can_process();
 	bool prev_enabled = _is_enabled();
 
-	data.process_mode = p_mode;
-
-	if (data.process_mode == PROCESS_MODE_INHERIT) {
+	if (p_mode == PROCESS_MODE_INHERIT) {
 		if (data.parent) {
-			data.process_owner = data.parent->data.owner;
+			data.process_owner = data.parent->data.process_owner;
```
Comment (pouleyKetchoupp) [inline scene/main/node.cpp:444]: This was causing a bug when switching back to inherit for a node with at least depth 2 in the tree, it was always using the direct parent as process owner instead of the correct node.

**Comment by pouleyKetchoupp** [comment]
@reduz I've rebased and updated from your comment.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
