### PR TITLE
[3.x] Fix inner class parsing when statement after colon is on the same line (reverted)

### LINKED ISSUE #56703: GDScript: empty class definition leads to error somewhere else
### Godot version

3.4.2

### System information

Windows 10

### Issue description

**Implementing a script class including an inner class with "pass" as body in one line leads to error some place else.**

I created the inner class with a given name as a temporary placeholder - prior to full implementation - to use it as an argument in other functions.

The error message itself is just misleading as it refers to a place in code which has nothing to do with the error itself.
I know this is a minor thing. It cost me a bit to figure out what the real cause was.

### Steps to reproduce

Inner class definition in single line including pass as body.

class Whatever: pass

```gdscript
# bug_class_one_liner.gd
extends Node2D

# line 07 leads to
# 'error(16,1): The method "to_local" isn't declared in the current class.'
# (line 08 to 09 works - same code including line-break.)
class WorxNot: pass
#class Worx:
#	pass

var var1

var var2

func icon_at(pos: Vector2):
	pos = to_local(pos)
	# other statements
```

leads to error at line "pos = to_local(pos)" in function icon_at().

### Minimal reproduction project

[bug_class_one_liner.zip](https://github.com/godotengine/godot/files/7849833/bug_class_one_liner.zip)

### PR DESCRIPTION
**Pull request by kdiduk**
This commit fixes #56703 

The fix is to increase indent level when the statement after the colon token is on the same line. 

It looks like this issue is a regression introduced after some of the changes. Because in one of the earlier versions of that piece of code the intend level was increased ([see this](https://github.com/kdiduk/godot/blob/99736e63e45b323d06411926bd92210a08c717c2/modules/gdscript/gd_parser.cpp#L80), for example). 

<i>Bugsquad edit:</i>
- Fix #56703

### CODE REVIEW

**Comment by kdiduk** [comment]
If this PR is approved and merged, we need to update documentation for GDScript grammar (both in [3.x](https://docs.godotengine.org/en/stable/development/file_formats/gdscript_grammar.html) and [4.0](https://docs.godotengine.org/en/latest/development/file_formats/gdscript_grammar.html)), because it says that after the colon in the inner class declaration there is a newline:
```ebnf
innerClass = "class" IDENTIFIER [ inheritance ] ":" NEWLINE
    INDENT [ inheritance NEWLINE ] topLevelDecl { topLevelDecl } DEDENT ;
```

As I understand, the idea is to have it more Python'ic way, where this is allowed:
```python
class Foo: pass
```

At lease, in 4.0 it already works like that.

**Comment by akien-mga** [comment]
> It looks like this issue is a regression introduced after some of the changes. Because in one of the earlier versions of that piece of code the intend level was increased ([see this](https://github.com/kdiduk/godot/blob/99736e63e45b323d06411926bd92210a08c717c2/modules/gdscript/gd_parser.cpp#L80), for example).

For the record, the `+1` was removed in this PR: #8123.
And that code was further refactored in #32808.

Please make sure that this doesn't reintroduce the issues that those PRs fixed.

**Comment by kdiduk** [comment]
> Please make sure that this doesn't reintroduce the issues that those PRs fixed. 

@akien-mga Thank you for mentioning the original PR! Indeed my initial fix re-introduced some issues from them.

I've just pushed another implementation. I've implemented a special case for inner classes and it doesn't touch the cases mentioned in those PRs. 

Please, review it. I can also do some refactoring to clean up and eliminate duplicated code.

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -137,6 +137,68 @@ bool GDScriptParser::_enter_indent_block(BlockNode *p_block) {
 	}
 }
 
+bool GDScriptParser::_enter_inner_class_indent_block() {
+	if (tokenizer->get_token() != GDScriptTokenizer::TK_COLON) {
+		// report location at the previous token (on the previous line)
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:142]: Comments should start with a capital letter and end with a period (`.`).

```suggestion
		// Report location at the previous token (on the previous line).
```

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -137,6 +137,68 @@ bool GDScriptParser::_enter_indent_block(BlockNode *p_block) {
...
+	}
+	tokenizer->advance();
+
+	if (tokenizer->get_token() != GDScriptTokenizer::TK_NEWLINE) {
+		if (tokenizer->get_token() == GDScriptTokenizer::TK_EOF) {
+			return false;
+		}
+
+		// Check Python-like one-liner class declaration "class Foo: pass"
+		// (note: only "pass" is allowed on the same line after the colon)
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:156]: Same here, should end with a period.

File: modules/gdscript/gdscript_parser.cpp [hunk 3]
```diff
@@ -137,6 +137,68 @@ bool GDScriptParser::_enter_indent_block(BlockNode *p_block) {
...
+			message += "\".";
+			_set_error(message, line, col);
+			return false;
+		}
+		return true;
+	}
+
+	while (true) {
+		if (tokenizer->get_token() != GDScriptTokenizer::TK_NEWLINE) {
+			return false; //wtf
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:176]: I guess you copied from another place but I think you can remove this comment.

File: modules/gdscript/gdscript_parser.cpp [hunk 4]
```diff
@@ -137,6 +137,68 @@ bool GDScriptParser::_enter_indent_block(BlockNode *p_block) {
...
+			if (indent <= current_level.indent) {
+				return false;
+			}
+
+			indent_level.push_back(new_indent);
+			tokenizer->advance();
+			return true;
+		}
+
+		tokenizer->advance(); // go to next newline
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:198]: Same here, either remove the comment of format it.

**Review by vnen — CHANGES_REQUESTED** [review]

**Comment by vnen** [comment]
Looks good to me, my remarks are only about the comment formatting.

**Comment by kdiduk** [comment]
@vnen Thank you for your remarks. I've just pushed new changes with some refactoring. I have eliminated duplicated code blocks, extracting it into separate methods. Could you review it again?

File: modules/gdscript/gdscript_parser.cpp [hunk 5]
```diff
@@ -82,8 +82,53 @@ void GDScriptParser::_set_end_statement_error(String p_name) {
...
+		return false;
+	}
+
+	if (tokenizer->get_token() != GDScriptTokenizer::TK_NEWLINE) {
+		// be more python-like
+		IndentLevel current_level = indent_level.back()->get();
+		indent_level.push_back(current_level);
+		return true;
+		//_set_error("newline expected after ':'.");
+		//return false;
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:95]: Being nitpicky again, but you shouldn't add commented out code (again, I know you are copying from the other function but these things can be fixed in the copy).

**Review by vnen — CHANGES_REQUESTED** [review]
Looks good to me, just have one style remark.

**Review by vnen — APPROVED** [review]
Looks good to me

**Comment by akien-mga** [comment]
Thanks!
