### PR TITLE
Fix error message on startup when camera is busy

### LINKED ISSUE #97454: "ERROR: Cannot set format, error: 16." on Linux after merge of Camera implementation (#53666), when webcam is busy
### Tested versions

- Reproducible in 4.4.dev (2834dd6a2a4510901c70a98d587045b0f102c8e0) after merge of #53666 
- Not reproducible in 4.3.stable or 4.4.dev2

### System information

Godot v4.4.dev (2834dd6a2) - Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

The following is printed to the terminal output when opening any project on Linux:
```
ERROR: Cannot set format, error: 16.
```

### Steps to reproduce

- Have the webcam busy (e.g. from a Jitsi meeting)
- Open Godot from a terminal
- Open a project

### Minimal reproduction project (MRP)

Any project.

### PR DESCRIPTION
**Pull request by pkowal1982**
It fixes #97454 by delaying camera feed format setting to just before activating feed.
If user fails to set format before feed activation engine will give proper error message then.

### CODE REVIEW

File: modules/camera/camera_feed_linux.cpp [hunk 1]
```diff
@@ -232,6 +232,7 @@ String CameraFeedLinux::get_device_name() const {
 }
 
 bool CameraFeedLinux::activate_feed() {
+	ERR_FAIL_COND_V_MSG(selected_format == -1, false, "Set feed format first.");
```
Comment (akien-mga) [inline modules/camera/camera_feed_linux.cpp:235]:
```suggestion
	ERR_FAIL_COND_V_MSG(selected_format == -1, false, "CameraFeed format needs to be set before activating.");
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
