### PR TITLE
Fix gles texture uniform array binding

### LINKED ISSUE #76463: Godot crashes if creating uniform sampler2D array when using compatibility/GLES3 renderer
### Godot version

Godot Engine v4.1.dev.custom_build (56253c3897b99966ee9e7469fd01e6152f8552ef)

### System information

Fedora 37 KDE, RTX 3080

### Issue description

As soon as one defines an array of sampler2D the editor crashes.

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.dev.custom_build (56253c3897b99966ee9e7469fd01e6152f8552ef)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x3cb20) [0x7f4c0d2a5b20] (??:0)
[2] GLES3::SceneMaterialData::bind_uniforms() (/storage/Code/godot/drivers/gles3/storage/material_storage.cpp:3520)
[3] void RasterizerSceneGLES3::_render_list_template<(PassMode)4>(RasterizerSceneGLES3::RenderListParameters*, RenderDataGLES3 const*, unsigned int, unsigned int, bool) (/storage/Code/godot/drivers/gles3/rasterizer_scene_gles3.cpp:2273)
[4] RasterizerSceneGLES3::render_scene(Ref<RenderSceneBuffers> const&, RendererSceneRender::CameraData const*, RendererSceneRender::CameraData const*, PagedArray<RenderGeometryInstance*> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, PagedArray<RID> const&, RID, RID, RID, RID, RID, RID, int, float, RendererSceneRender::RenderShadowData const*, int, RendererSceneRender::RenderSDFGIData const*, int, RendererSceneRender::RenderSDFGIUpdateData const*, RenderingMethod::RenderInfo*) (/storage/Code/godot/drivers/gles3/rasterizer_scene_gles3.cpp:1928)
[5] RendererSceneCull::_render_scene(RendererSceneRender::CameraData const*, Ref<RenderSceneBuffers> const&, RID, RID, unsigned int, RID, RID, RID, RID, int, float, bool, RenderingMethod::RenderInfo*) (/storage/Code/godot/servers/rendering/renderer_scene_cull.cpp:3317 (discriminator 4))
[6] RendererSceneCull::render_camera(Ref<RenderSceneBuffers> const&, RID, RID, RID, Vector2, bool, float, RID, Ref<XRInterface>&, RenderingMethod::RenderInfo*) (/storage/Code/godot/servers/rendering/renderer_scene_cull.cpp:2590)
[7] RendererViewport::_draw_3d(RendererViewport::Viewport*) (/storage/Code/godot/servers/rendering/renderer_viewport.cpp:212 (discriminator 1))
[8] RendererViewport::_draw_viewport(RendererViewport::Viewport*) (/storage/Code/godot/servers/rendering/renderer_viewport.cpp:279)
[9] RendererViewport::draw_viewports() (/storage/Code/godot/servers/rendering/renderer_viewport.cpp:729)
[10] RenderingServerDefault::_draw(bool, double) (/storage/Code/godot/servers/rendering/rendering_server_default.cpp:92)
[11] RenderingServerDefault::draw(bool, double) (/storage/Code/godot/servers/rendering/rendering_server_default.cpp:397)
[12] Main::iteration() (/storage/Code/godot/main/main.cpp:3234)
[13] OS_LinuxBSD::run() (/storage/Code/godot/platform/linuxbsd/os_linuxbsd.cpp:889)
[14] ./bin/godot.linuxbsd.editor.dev.x86_64(main+0x15a) [0x4f6d540] (/storage/Code/godot/platform/linuxbsd/godot_linuxbsd.cpp:75)
[15] /lib64/libc.so.6(+0x27510) [0x7f4c0d290510] (??:0)
[16] /lib64/libc.so.6(__libc_start_main+0x89) [0x7f4c0d2905c9] (??:0)
[17] ./bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x4f6d325] (??:?)
-- END OF BACKTRACE --
================================================================
[1]    15524 IOT instruction (core dumped)  ./bin/godot.linuxbsd.editor.dev.x86_64 
```

### Steps to reproduce

1. Set renderer to "Compatibility"
2. Write the following line in a shader that is assigned to an object through a ShaderMaterial (I've tried it in Spatial and Sky shaders)
   `uniform sampler2D test[5];`

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ChibiDenDen**
Fix both texture uniform binding and texture object binding in gles (compatibility ) mode for godot 4

Before this change, the engine (editor / game) crashes whenever there is an array of sampler2D in compatibility mode

The following line in any shader crashes:
`uniform sampler2D[10] textures;`

_Production edit: Fixes https://github.com/godotengine/godot/issues/76463_

### CODE REVIEW

**Comment by YuriSizov** [comment]
Thanks for opening a pull request! Please [squash your commits](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) into a single one. Make sure that the commit message stays short but descriptive (your original message and the title of this PR are a good option).

**Comment by ChibiDenDen** [comment]
@YuriSizov thanks, I squashed the commits.
I tried to look at the open issues for keywords like "shader array" "shader crash" "sampler array" "sampler2d" and couldn't find anything similar, might have missed something though.

Should I open an issue describing the bugs fixed here?

**Comment by YuriSizov** [comment]
> Should I open an issue describing the bugs fixed here?

Not, it's not necessary at this point. I was mostly curious if this would reduce our backlog of existing issues :)

File: drivers/gles3/storage/material_storage.cpp [hunk 1]
```diff
@@ -2947,6 +2947,18 @@ void MaterialStorage::material_update_dependency(RID p_material, DependencyTrack
 	}
 }
 
+LocalVector<ShaderGLES3::TextureUniformData> get_texture_uniform_data(const Vector<ShaderCompiler::GeneratedCode::Texture> &texture_uniforms) {
+	LocalVector<ShaderGLES3::TextureUniformData> texture_uniform_data;
+	for (int i = 0; i < texture_uniforms.size(); i++) {
+		auto num_textures = texture_uniforms[i].array_size;
```
Comment (clayjohn) [inline drivers/gles3/storage/material_storage.cpp:2953]:
```suggestion
		int num_textures = texture_uniforms[i].array_size;
```

As a matter of style, we don't use ``auto`` in the godot codebase

**Review by clayjohn — COMMENTED** [review]
Looks really good! I just have one little requested change because we try to avoid using ``auto`` unless absolutely necessary.

**Comment by clayjohn** [comment]
This looks good to go, it just needs to be rebased to resolve conflicts

File: drivers/gles3/shader_gles3.cpp [hunk 2]
```diff
@@ -29,6 +29,7 @@
 /**************************************************************************/
 
 #include "shader_gles3.h"
+#include "core/variant/variant.h"
```
Comment (akien-mga) [inline drivers/gles3/shader_gles3.cpp:32]: The include should go further down where the other includes are. But why do you need Variant?

Comment (clayjohn) [reply drivers/gles3/shader_gles3.cpp:32]: Looks like it is to access PackedInt32Array

File: drivers/gles3/shader_gles3.cpp [hunk 3]
```diff
@@ -268,10 +269,17 @@ void ShaderGLES3::_get_uniform_locations(Version::Specialization &spec, Version
...
 	}
 	// textures
-	for (int i = 0; i < p_version->texture_uniforms.size(); i++) {
-		String native_uniform_name = _mkid(p_version->texture_uniforms[i]);
+	int texture_index = 0;
+	for (uint32_t i = 0; i < p_version->texture_uniforms.size(); i++) {
+		String native_uniform_name = _mkid(p_version->texture_uniforms[i].name);
 		GLint location = glGetUniformLocation(spec.id, (native_uniform_name).ascii().get_data());
-		glUniform1i(location, i + base_texture_index);
+		PackedInt32Array texture_uniform_bindings;
```
Comment (clayjohn) [inline drivers/gles3/shader_gles3.cpp:276]: This can use a ``Vector<int32_t>`` instead, then you don't need to include variant.h. ``PackedInt32Array`` is just a typedef ``Vector<int32_t>`` anyway

Comment (ChibiDenDen) [reply drivers/gles3/shader_gles3.cpp]: Thanks, updated the code according to your suggestions.

**Review by clayjohn — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
