### PR TITLE
[TextServer] Fix some emoji sequences and add missing ICU emoji property data.

### LINKED ISSUE #112510: Characters after emoji sometimes not displayed in label/richtextlabel
### Tested versions

- Reproducible on 4.6dev3

### System information

macOS 15.0

### Issue description

For some emojis (the snowflake one at least, not sure if there are others), characters printed immediately after the emoji (ie. no whitespace) don't get displayed.

In the MRP I've attacked this script to a Label node:

```
extends Label

func _ready() -> void:
	text = "❄️1234567890 why do the numbers between the emoji and this sentence not show up?\n🔥123 these work\n💦123 these too\n❄️123 but not these?"
```

And the result when you run the project is:

Image

### Steps to reproduce

Paste "❄️1234567890" in a label node. Notice that none of the numbers show up.

### Minimal reproduction project (MRP)

[label-test.zip](https://github.com/user-attachments/files/23419178/label-test.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Follow up to https://github.com/godotengine/godot/pull/110194
Fixes https://github.com/godotengine/godot/issues/112510

| Version | Screenshot 
|--|--|
| 4.5.1 | Screenshot 2025-11-11 at 12 04 21 |
| 4.6.dev3 | Screenshot 2025-11-11 at 12 03 38 |
| this PR | Screenshot 2025-11-11 at 12 03 24 |

### CODE REVIEW

File: modules/text_server_adv/script_iterator.cpp [hunk 1]
```diff
@@ -119,8 +119,7 @@ ScriptIterator::ScriptIterator(const String &p_string, int p_start, int p_length
 			}
 
 			if (script_code == USCRIPT_SYMBOLS_EMOJI && script_code != sc) {
-				UCharCategory cat = (UCharCategory)u_charType(ch);
-				if ((cat >= U_SPACE_SEPARATOR && cat <= U_CONTROL_CHAR) || (cat >= U_DASH_PUNCTUATION && cat <= U_OTHER_PUNCTUATION) || (cat >= U_INITIAL_PUNCTUATION && cat <= U_FINAL_PUNCTUATION)) {
+				if (ch == 0xFE0E || n == 0xFE0E || !(is_emoji(ch, n) || ch == 0x200D || ch == 0xFE0F || (u_hasBinaryProperty(ch, UCHAR_EXTENDED_PICTOGRAPHIC)))) {
```
Comment (AThousandShips) [inline modules/text_server_adv/script_iterator.cpp]:
```suggestion
				if (ch == 0xFE0E || n == 0xFE0E || !(is_emoji(ch, n) || ch == 0x200D || ch == 0xFE0F || u_hasBinaryProperty(ch, UCHAR_EXTENDED_PICTOGRAPHIC))) {
```

File: modules/text_server_adv/script_iterator.cpp
Comment (Repiteo) [inline modules/text_server_adv/script_iterator.cpp:34]:
```suggestion

inline constexpr UChar32 ZERO_WIDTH_JOINER = 0x200d;
inline constexpr UChar32 VARIATION_SELECTOR_15 = 0xfe0e;
inline constexpr UChar32 VARIATION_SELECTOR_16 = 0xfe0f;

```

File: modules/text_server_adv/script_iterator.cpp [hunk 2]
```diff
@@ -37,12 +37,12 @@ inline bool ScriptIterator::same_script(int32_t p_script_one, int32_t p_script_t
 }
 
 inline bool ScriptIterator::is_emoji(UChar32 p_c, UChar32 p_next) {
-	if (p_next == 0xFE0E) { // Variation Selector-15
+	if (p_next == 0xFE0E && (u_hasBinaryProperty(p_c, UCHAR_EMOJI) || u_hasBinaryProperty(p_c, UCHAR_EXTENDED_PICTOGRAPHIC))) { // Variation Selector-15
```
Comment (Repiteo) [inline modules/text_server_adv/script_iterator.cpp]:
```suggestion
	if (p_next == VARIATION_SELECTOR_15 && (u_hasBinaryProperty(p_c, UCHAR_EMOJI) || u_hasBinaryProperty(p_c, UCHAR_EXTENDED_PICTOGRAPHIC))) {
```

File: modules/text_server_adv/script_iterator.cpp [hunk 3]
```diff
@@ -37,12 +37,12 @@ inline bool ScriptIterator::same_script(int32_t p_script_one, int32_t p_script_t
...
 		return false;
-	} else if (p_next == 0xFE0F) { // Variation Selector-16
+	} else if (p_next == 0xFE0F && (u_hasBinaryProperty(p_c, UCHAR_EMOJI) || u_hasBinaryProperty(p_c, UCHAR_EXTENDED_PICTOGRAPHIC))) { // Variation Selector-16
```
Comment (Repiteo) [inline modules/text_server_adv/script_iterator.cpp]:
```suggestion
	} else if (p_next == VARIATION_SELECTOR_16 && (u_hasBinaryProperty(p_c, UCHAR_EMOJI) || u_hasBinaryProperty(p_c, UCHAR_EXTENDED_PICTOGRAPHIC))) {
```

File: modules/text_server_adv/script_iterator.cpp [hunk 4]
```diff
@@ -119,8 +119,7 @@ ScriptIterator::ScriptIterator(const String &p_string, int p_start, int p_length
 			}
 
 			if (script_code == USCRIPT_SYMBOLS_EMOJI && script_code != sc) {
-				UCharCategory cat = (UCharCategory)u_charType(ch);
-				if ((cat >= U_SPACE_SEPARATOR && cat <= U_CONTROL_CHAR) || (cat >= U_DASH_PUNCTUATION && cat <= U_OTHER_PUNCTUATION) || (cat >= U_INITIAL_PUNCTUATION && cat <= U_FINAL_PUNCTUATION)) {
+				if (ch == 0xFE0E || n == 0xFE0E || !(is_emoji(ch, n) || ch == 0x200D || ch == 0xFE0F || u_hasBinaryProperty(ch, UCHAR_EXTENDED_PICTOGRAPHIC))) {
```
Comment (Repiteo) [inline modules/text_server_adv/script_iterator.cpp]:
```suggestion
				if (ch == VARIATION_SELECTOR_15 || n == VARIATION_SELECTOR_15 || !(is_emoji(ch, n) || ch == ZERO_WIDTH_JOINER || ch == VARIATION_SELECTOR_16 || u_hasBinaryProperty(ch, UCHAR_EXTENDED_PICTOGRAPHIC))) {
```

**Review by Repiteo — CHANGES_REQUESTED** [review]
If we're gonna be identifying  the magic numbers in comments anyway, might as well make them explicit

File: modules/text_server_adv/script_iterator.cpp
Comment (bruvzg) [reply modules/text_server_adv/script_iterator.cpp:34]: Done.

**Review by Repiteo — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
