### PR TITLE
Fix custom Ctrl-Space shortcut in Script Editor adds a space

### LINKED ISSUE #94031: [Import] Child nodes get reparented when two objects have the same name without the import hint
### Tested versions

v4.3.beta.custom_build [f3af22b10] (master)

### System information

Godot v4.3.beta (f3af22b10) - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

https://github.com/godotengine/godot/assets/60579014/aaea9510-b8bb-4261-b2af-babd96fe2a9f

This happens because godot only keeps the hint in the name when there's a conflict (as opposed to always keeping it). This can probably be solved by just always keeping hints in the names

cc @Hilderin 

### Steps to reproduce

1. Create a cube in a blend file, call it `Cube-col` and export
2. Add some child node to it in Godot with editable children
3. Create another cube in blender, call it `Cube` and export
4. The new cube steals the child of the old cube

### Minimal reproduction project (MRP)

Can only be reproduced by following the steps

### LINKED ISSUE #94032: Custom shortcut Ctrl-Space in Script Editor add a space
### Tested versions

Godot v4.3.beta.mono (27e375920)

### System information

Godot v4.3.beta.mono (27e375920) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Issue description

I customized the shortcut "Completion Query" for Ctrl-Alt-Space and used Ctrl-Space for "Toggle Last Opened Bottom Panel".
When the Script Editor is focus and I press Ctrl-Space, the Bottom panel opens/closes but a space is added in the script.
What is strange is that Ctrl-J does not produce this error.

https://github.com/godotengine/godot/assets/81109165/15db1017-798e-4ddf-a685-2943c792f715

### Steps to reproduce

- Change the "Completion Query" shortcut for something else.
- Change the "Toggle Last Opened Bottom Panel" shortcut for "Ctrl-Space".
- Open a script.
- Press Ctrl-Space.

### Minimal reproduction project (MRP)

Any project will do.

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #94032

It seems that `get_tree()->get_root()->set_input_as_handled()` was not called in `EditorNode::shortcut_input` for some shortcuts.

It's not the most beautiful code, but I'm not sure how to make it better!!

Edit: was wrong issue.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -317,36 +317,39 @@ void EditorNode::shortcut_input(const Ref<InputEvent> &p_event) {
...
 			_open_command_palette();
+			get_tree()->get_root()->set_input_as_handled();
 		} else if (ED_IS_SHORTCUT("editor/toggle_last_opened_bottom_panel", p_event)) {
 			bottom_panel->toggle_last_opened_bottom_panel();
-		} else {
-		}
-
-		if (old_editor != editor_plugin_screen) {
 			get_tree()->get_root()->set_input_as_handled();
+		} else {
```
Comment (AThousandShips) [inline editor/editor_node.cpp:352]:
```suggestion
```

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -317,36 +317,39 @@ void EditorNode::shortcut_input(const Ref<InputEvent> &p_event) {
 
 	Ref<InputEventKey> k = p_event;
 	if ((k.is_valid() && k->is_pressed() && !k->is_echo()) || Object::cast_to<InputEventShortcut>(*p_event)) {
-		EditorPlugin *old_editor = editor_plugin_screen;
-
 		if (ED_IS_SHORTCUT("editor/filter_files", p_event)) {
 			FileSystemDock::get_singleton()->focus_on_filter();
 			get_tree()->get_root()->set_input_as_handled();
```
Comment (AThousandShips) [inline editor/editor_node.cpp:322]: This should probably be handled with a `bool`, so a `bool is_handled = false;`, a `is_handled = true;` in each placez, and a check at the end.

**Comment by AThousandShips** [comment]
Did you mean to link:
* https://github.com/godotengine/godot/issues/94032

This doesn't seem to be linked to the correct issue

File: editor/editor_node.cpp (hunk 2 above)
Comment (Hilderin) [reply editor/editor_node.cpp]: Done!

File: editor/editor_node.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_node.cpp]: Done!

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -317,35 +317,40 @@ void EditorNode::shortcut_input(const Ref<InputEvent> &p_event) {
 
 	Ref<InputEventKey> k = p_event;
 	if ((k.is_valid() && k->is_pressed() && !k->is_echo()) || Object::cast_to<InputEventShortcut>(*p_event)) {
-		EditorPlugin *old_editor = editor_plugin_screen;
-
+		bool is_handled = false;
```
Comment (akien-mga) [inline editor/editor_node.cpp:320]: How about defaulting to true and only setting it to false in a final `else`?
Should save a bunch of repetition.

Comment (Hilderin) [reply editor/editor_node.cpp]: Lol! So simple, really better! That's brilliant!! :)
Done!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
