### PR TITLE
[Windows] Add Windows version and Wine checks for Windows 10+ dark mode API.

### LINKED ISSUE #93123: Godot editor crashes under Linux with Wine
### Tested versions

- Reproducible: 4.3 dev4 ~ 4.3 beta1
- Not Reproducible: 4.3 dev3, 4.2.2

### System information

OS: Fedora 38, Kernel 6.8.9-100.fc38.x86_64, Wine 9.0/9.3

### Issue description

Godot editor crashes when trying to run it with Wine 9.0 under linux.

In 4.3 dev4, the editor crashed silently. In 4.3 beta1, the editor crashed with message:
```
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.beta1.official (a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(0): executable file is not COFF
[2] error(-1): failed to read executable information
[3] error(-1): failed to read executable information
[4] error(-1): failed to read executable information
[5] error(-1): failed to read executable information
[6] error(-1): failed to read executable information
[7] error(-1): failed to read executable information
[8] error(-1): failed to read executable information
[9] error(-1): failed to read executable information
[10] error(-1): failed to read executable information
[11] error(-1): failed to read executable information
[12] error(-1): failed to read executable information
[13] error(-1): failed to read executable information
[14] error(-1): failed to read executable information
[15] error(-1): failed to read executable information
[16] error(-1): failed to read executable information
[17] error(-1): failed to read executable information
[18] error(-1): failed to read executable information
[19] error(-1): failed to read executable information
[20] error(-1): failed to read executable information
[21] error(-1): failed to read executable information
-- END OF BACKTRACE --
```
 
Full Wine error message under 4.3 dev4:
<details>

```
Godot Engine v4.3.dev4.official.df78c0636 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 550.78 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1660 Ti

wine: Unhandled page fault on read access to 0000000080070116 at address 00006FFFF82DCDD0 (thread 00dc), starting debugger...
Unhandled exception: page fault on read access to 0x0000000080070116 in 64-bit code (0x006ffff82dcdd0).
Register dump:
 rip:00006ffff82dcdd0 rsp:00007ffffe8fed90 rbp:00000000000000d2 eflags:00010206 (  R- --  I   - -P- )
 rax:00000000ffffffff rbx:0000000000000000 rcx:0000000080070006 rdx:0000000080070006
 rsi:0000000000000000 rdi:00000000000000d2  r8:0000000000000000  r9:00000000000000d2 r10:00006fffffcc2b20
 r11:0000000000000202 r12:0000000080070006 r13:00006ffff82e5070 r14:00007f672062a0b0 r15:00007ffffe8ff040
Stack dump:
0x007ffffe8fed90:  00007ffffe8fee30 0000000080070057
0x007ffffe8feda0:  00000000000000d2 00007ffffe8feed0
0x007ffffe8fedb0:  00007f672062a0b0 00006ffff82dd6cd
0x007ffffe8fedc0:  00007ffffe8ff040 00006fffffcad237
0x007ffffe8fedd0:  00007ffffeee0000 0000000080070006
0x007ffffe8fede0:  0000000000000000 0000000000000000
0x007ffffe8fedf0:  0000000080070057 00000000000000d2
0x007ffffe8fee00:  00007ffffe8feed0 00006ffff82dda2e
0x007ffffe8fee10:  00007ffffe8feeb0 0000000000000000
0x007ffffe8fee20:  00007ffffe8ff020 00006ffff82e5040
0x007ffffe8fee30:  00007f67000000d2 00006fff00000000
0x007ffffe8fee40:  00007fff000000d2 00000001440e1091
Backtrace:
=>0 0x006ffff82dcdd0 MSSTYLES_FindPartState(tcNext=<has been optimized away by compiler>, iStateId=<has been optimized away by 
compiler>, iPartId=<has been optimized away by compiler>, tc=0000000080070006) [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxthe
me/msstyles.c:509] in uxtheme (0x000000000000d2)
  1 0x006ffff82dcdd0 MSSTYLES_FindProperty+0x40(tc=<register R12 not accessible in this frame>, iPartId=<register RBX not acces
sible in this frame>, iStateId=<is not available>, iPropertyPrimitive=<register RBP not accessible in this frame>, iPropertyId=
[<register RSP not accessible in this frame>) [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/msstyles.c:1164] in uxtheme (0
x000000000000d2)
  2 0x006ffff82dda2e GetThemeFont+0x4e(hTheme=<register RBX not accessible in this frame>, hdc=<register RBP not accessible in 
this frame>, iPartId=<register RSI not accessible in this frame>, iStateId=<register RDI not accessible in this frame>, iPropId
=[<register RSP not accessible in this frame>, pFont=[<register RSP not accessible in this frame>) [/home/abuild/rpmbuild/BUILD
/wine-9.0/dlls/uxtheme/property.c:126] in uxtheme (0x00000080070057)
  3 0x006ffff82d98ab GetThemeTextMetrics+0x5b(hTheme=<register RBX not accessible in this frame>, hdc=<register RSI not accessi
ble in this frame>, iPartId=<register RDI not accessible in this frame>, iStateId=<register RBP not accessible in this frame>, 
ptm=[<register RSP not accessible in this frame>) [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/draw.c:2185] in uxtheme (0
000000000000000)
  4 0x0000014000581d in godot_v4.3-dev4_win64 (+0x581d) (0x0000014740f148)
  5 0x00000141a28bf2 in godot_v4.3-dev4_win64 (+0x1a28bf2) (0x0000014740f148)
  6 0x00000141a335d8 in godot_v4.3-dev4_win64 (+0x1a335d8) (0x0000014740f318)
  7 0x0000014121d346 in godot_v4.3-dev4_win64 (+0x121d346) (0x007ffffe8ff5e0)
  8 0x00000140091d2a in godot_v4.3-dev4_win64 (+0x91d2a) (0x00000143c39d40)
  9 0x000001400963ea in godot_v4.3-dev4_win64 (+0x963ea) (0x006fffffa904b4)
  10 0x000001450652e3 in godot_v4.3-dev4_win64 (+0x50652e3) (0x007ffffeee34c0)
  11 0x000001400012ee in godot_v4.3-dev4_win64 (+0x12ee) (0x007ffffeee34c0)
  12 0x000001400013e6 in godot_v4.3-dev4_win64 (+0x13e6) (0000000000000000)
  13 0x006fffffaa8b29 BaseThreadInitThunk+0x9(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [/home/ab
uild/rpmbuild/BUILD/wine-9.0/dlls/kernel32/thread.c:61] in kernel32 (0000000000000000)
  14 0x006fffffca54fb in ntdll (+0x554fb) (0000000000000000)
0x006ffff82dcdd0 MSSTYLES_FindProperty+0x40 [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/msstyles.c:1164] in uxtheme: mov
 0x110(%rdx), %rax
Unable to access file '/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/msstyles.c'
Modules:
Module  Address                                 Debug info      Name (147 modules)
PE-Wine         79300000-        7988d000       Deferred        opengl32
PE             140000000-       1476a5000       Export          godot_v4.3-dev4_win64
PE-Wine     6ffff82d0000-    6ffff839a000       Dwarf-4-5       uxtheme
PE-Wine     6ffff83b0000-    6ffff83df000       Deferred        wsock32
PE-Wine     6ffff83f0000-    6ffff846c000       Deferred        msacm32
PE-Wine     6ffff8480000-    6ffff863a000       Deferred        winmm
PE-Wine     6ffff8650000-    6ffff8670000       Deferred        version
PE-Wine     6ffff8680000-    6ffff8998000       Deferred        dwrite
PE-Wine     6ffff89b0000-    6ffff89d5000       Deferred        dwmapi
PE-Wine     6ffff89f0000-    6ffff8a25000       Deferred        hid
PE-Wine     6ffff8a40000-    6ffff8fa3000       Deferred        comctl32
PE-Wine     6ffff8fc0000-    6ffff90ec000       Deferred        dinput8
PE-Wine     6ffff9100000-    6ffff93ed000       Deferred        dbghelp
PE-Wine     6ffff9400000-    6ffffaa07000       Deferred        wined3d
PE-Wine     6ffffaa20000-    6ffffab68000       Deferred        dxgi
PE-Wine     6ffffab80000-    6ffffabde000       Deferred        d3d12
PE-Wine     6ffffabf0000-    6ffffafb4000       Deferred        crypt32
PE-Wine     6ffffafd0000-    6ffffb02a000       Deferred        bcrypt
PE-Wine     6ffffb040000-    6ffffb05d000       Deferred        avrt
PE-Wine     6ffffb070000-    6ffffb094000       Deferred        nsi
PE-Wine     6ffffb0b0000-    6ffffb0fe000       Deferred        dnsapi
PE-Wine     6ffffb110000-    6ffffb19e000       Deferred        iphlpapi
PE-Wine     6ffffb260000-    6ffffb2b9000       Deferred        winex11
PE-Wine     6ffffb2d0000-    6ffffb34e000       Deferred        imm32
PE-Wine     6ffffb6d0000-    6ffffb8a9000       Deferred        setupapi
PE-Wine     6ffffb950000-    6ffffbe46000       Deferred        oleaut32
PE-Wine     6ffffc290000-    6ffffc2ae000       Deferred        winepulse
PE-Wine     6ffffc2c0000-    6ffffc3b1000       Deferred        mmdevapi
PE-Wine     6ffffc3d0000-    6ffffc40a000       Deferred        xinput1_4
PE-Wine     6ffffc420000-    6ffffc452000       Deferred        compstui
PE-Wine     6ffffc470000-    6ffffc539000       Deferred        winspool
PE-Wine     6ffffc550000-    6ffffc6bb000       Deferred        wbemprox
PE-Wine     6ffffc6d0000-    6ffffc70f000       Deferred        wintab32
PE-Wine     6ffffc720000-    6ffffc773000       Deferred        shcore
PE-Wine     6ffffc790000-    6ffffc8aa000       Deferred        shlwapi
PE-Wine     6ffffc8c0000-    6ffffd64a000       Deferred        shell32
PE-Wine     6ffffd660000-    6ffffd6ad000       Deferred        coml2
PE-Wine     6ffffd6c0000-    6ffffd950000       Deferred        rpcrt4
PE-Wine     6ffffd960000-    6ffffd99c000       Deferred        win32u
PE-Wine     6ffffd9b0000-    6ffffdf90000       Deferred        user32
PE-Wine     6ffffdfa0000-    6ffffe265000       Deferred        gdi32
PE-Wine     6ffffe280000-    6ffffe41b000       Deferred        combase
PE-Wine     6ffffe430000-    6ffffe9d9000       Deferred        ole32
PE-Wine     6ffffe9f0000-    6ffffea9d000       Deferred        ws2_32
PE-Wine     6ffffeab0000-    6ffffeeac000       Deferred        ucrtbase
PE-Wine     6ffffeec0000-    6ffffef82000       Deferred        sechost
PE-Wine     6ffffefa0000-    6fffff2ff000       Deferred        msvcrt
PE-Wine     6fffff310000-    6fffff43d000       Deferred        advapi32
PE-Wine     6fffff450000-    6fffffa67000       Deferred        kernelbase
PE-Wine     6fffffa80000-    6fffffc3b000       Dwarf-4-5       kernel32
PE-Wine     6fffffc50000-    6fffffff0000       Dwarf-4-5       ntdll
ELF         7f670d400000-    7f670fe06000       Deferred        libnvidia-gpucomp.so.550.78
ELF         7f671a000000-    7f671bf15000       Deferred        libnvidia-glcore.so.550.78
ELF         7f6728200000-    7f6728627000       Deferred        libcrypto.so.3
ELF         7f672af2b000-    7f672afa3000       Deferred        libmp3lame.so.0
ELF         7f672afa3000-    7f672b000000       Deferred        libmpg123.so.0
ELF         7f672b815000-    7f672b871000       Deferred        libopus.so.0
ELF         7f672b871000-    7f672b91c000       Deferred        libvorbisenc.so.2
ELF         7f672b91c000-    7f672b982000       Deferred        libflac.so.12
ELF         7f672b982000-    7f672ba00000       Deferred        libsndfile.so.1
ELF         7f672be2c000-    7f672be5b000       Deferred        libvorbis.so.0
ELF         7f672be5b000-    7f672bee0000       Deferred        libpulsecommon-16.1.so
ELF         7f6730008000-    7f6730012000       Deferred        libogg.so.0
ELF         7f6730012000-    7f6730021000       Deferred        libgsm.so.1
ELF         7f6730021000-    7f6730073000       Deferred        libpulse.so.0
ELF         7f6730298000-    7f67302ba000       Deferred        liblz4.so.1
ELF         7f67302ba000-    7f6730379000       Deferred        libzstd.so.1
ELF         7f6730379000-    7f6730460000       Deferred        libsystemd.so.0
ELF         7f6730460000-    7f673048d000       Deferred        libselinux.so.1
ELF         7f673048d000-    7f67304e2000       Deferred        libdbus-1.so.3
ELF         7f67304e2000-    7f67305bb000       Deferred        libkrb5.so.3
ELF         7f6731002000-    7f673100c000       Deferred        libcap.so.2
ELF         7f673100c000-    7f6731013000       Deferred        libkeyutils.so.1
ELF         7f6731013000-    7f6731023000       Deferred        libkrb5support.so.0
ELF         7f6731023000-    7f673103b000       Deferred        libk5crypto.so.3
ELF         7f673103b000-    7f673104f000       Deferred        libavahi-client.so.3
ELF         7f673104f000-    7f673105e000       Deferred        libavahi-common.so.3
ELF         7f673105e000-    7f6731100000       Deferred        libcups.so.2
ELF         7f6731a03000-    7f6731a0a000       Deferred        libcom_err.so.2
ELF         7f6731a0a000-    7f6731a60000       Deferred        libgssapi_krb5.so.2
ELF         7f6732440000-    7f67324d7000       Deferred        libnvidia-glsi.so.550.78
ELF         7f67324d7000-    7f6732600000       Deferred        libglx_nvidia.so.0
ELF         7f6732834000-    7f673284b000       Deferred        libdrm.so.2
ELF         7f6732853000-    7f673285b000       Deferred        libasyncns.so.0
ELF         7f673285b000-    7f6732870000       Deferred        winepulse.so
ELF         7f6732870000-    7f6732875000       Deferred        libx11-xcb.so.1
ELF         7f6732875000-    7f673287c000       Deferred        libxcb-dri3.so.0
ELF         7f673287c000-    7f673288e000       Deferred        libxcb-randr.so.0
ELF         7f673288e000-    7f6732946000       Deferred        libgldispatch.so.0
ELF         7f6732946000-    7f6732979000       Deferred        libglx.so.0
ELF         7f6732979000-    7f6732a00000       Deferred        libgl.so.1
ELF         7f6732c00000-    7f6732c1c000       Deferred        libxcb-glx.so.0
ELF         7f6732c1c000-    7f6732c21000       Deferred        librt.so.1
ELF         7f6732c21000-    7f6732c26000       Deferred        libpthread.so.0
ELF         7f6732c26000-    7f6732c2b000       Deferred        libdl.so.2
ELF         7f6732c30000-    7f6732c36000       Deferred        winspool.so
ELF         7f6732c55000-    7f6732c5b000       Deferred        libnvidia-tls.so.550.78
ELF         7f6732d6b000-    7f6732d72000       Deferred        ws2_32.so
ELF         7f6732d96000-    7f6732d9e000       Deferred        libxfixes.so.3
ELF         7f6732d9e000-    7f6732dab000       Deferred        libxcursor.so.1
ELF         7f6732dab000-    7f6732dbe000       Deferred        libxi.so.6
ELF         7f6732dbe000-    7f6732dc3000       Deferred        libxcomposite.so.1
ELF         7f6732dc3000-    7f6732dd0000       Deferred        libxrandr.so.2
ELF         7f6732dd0000-    7f6732ddc000       Deferred        libxrender.so.1
ELF         7f6732ddc000-    7f6732de3000       Deferred        libxxf86vm.so.1
ELF         7f6732de3000-    7f6732de8000       Deferred        libxinerama.so.1
ELF         7f6732de8000-    7f6732dee000       Deferred        libxau.so.6
ELF         7f6732dee000-    7f6732e19000       Deferred        libxcb.so.1
ELF         7f6732e19000-    7f6732f60000       Deferred        libx11.so.6
ELF         7f6732f60000-    7f6732f74000       Deferred        libxext.so.6
ELF         7f6732f78000-    7f6732f8a000       Deferred        libresolv.so.2
ELF         7f6732f8a000-    7f6732f8f000       Deferred        dnsapi.so
ELF         7f6732f8f000-    7f6732f95000       Deferred        dwrite.so
ELF         7f6732f99000-    7f673301e000       Deferred        winex11.so
ELF         7f673301e000-    7f6733157000       Deferred        opengl32.so
ELF         7f6733157000-    7f673315d000       Deferred        crypt32.so
ELF         7f6733294000-    7f67332c7000       Deferred        liblzma.so.5
ELF         7f67332c7000-    7f673343b000       Deferred        libxml2.so.2
ELF         7f673343b000-    7f673348a000       Deferred        libfontconfig.so.1
ELF         7f673348a000-    7f6733524000       Deferred        libpcre2-8.so.0
ELF         7f6733524000-    7f6733547000       Deferred        libbrotlicommon.so.1
ELF         7f6733547000-    7f6733568000       Deferred        libgraphite2.so.3
ELF         7f6733568000-    7f67336b1000       Deferred        libglib-2.0.so.0
ELF         7f67336b1000-    7f67337ad000       Deferred        libharfbuzz.so.0
ELF         7f67337ad000-    7f67337c7000       Deferred        libz.so.1
ELF         7f67337c7000-    7f6733897000       Deferred        libfreetype.so.6
ELF         7f6733897000-    7f6733978000       Deferred        libm.so.6
ELF         7f6733978000-    7f6733b16000       Deferred        win32u.so
ELF         7f6733b16000-    7f6733bbb000       Deferred        libgmp.so.10
ELF         7f6733bbb000-    7f6733bfe000       Deferred        libhogweed.so.6
ELF         7f6733bfe000-    7f6733c51000       Deferred        libnettle.so.8
ELF         7f6733c51000-    7f6733e00000       Deferred        libunistring.so.5
ELF         7f6733e00000-    7f6734032000       Deferred        libgnutls.so.30
ELF         7f6734036000-    7f673406f000       Deferred        libpng16.so.16
ELF         7f673406f000-    7f6734200000       Deferred        libp11-kit.so.0
ELF         7f6741c00000-    7f6741c0d000       Deferred        libbrotlidec.so.1
ELF         7f6741c0d000-    7f6741c21000       Deferred        libbz2.so.1
ELF         7f6741c21000-    7f6741c2d000       Deferred        libffi.so.8
ELF         7f6741c2d000-    7f6741c4f000       Deferred        libidn2.so.0
ELF         7f6741c74000-    7f6741c98000       Deferred        libgcc_s.so.1
ELF         7f6741c98000-    7f6741cb2000       Deferred        libunwind.so.8
ELF         7f6741cb2000-    7f6741d6d000       Export          ntdll.so
ELF         7f6741d6f000-    7f6741f4d000       Deferred        libc.so.6
ELF         7f6741f52000-    7f6741f68000       Deferred        libtasn1.so.6
ELF         7f6741f68000-    7f6741f74000       Deferred        bcrypt.so
ELF         7f6741f74000-    7f6741faa000       Deferred        ld-linux-x86-64.so.2
ELF         7f6741faa000-    7f6741faf000       Deferred        <wine-loader>
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
        00000024    0
00000038 services.exe
        0000003c    0
        00000040    0     wine_rpcrt4_server
        0000004c    0     wine_rpcrt4_io
        00000050    0     wine_threadpool_worker
        00000070    0     wine_rpcrt4_io
        000000a0    0     wine_rpcrt4_io
        000000b8    0     wine_rpcrt4_io
        000000cc    0
        000000fc    0     wine_rpcrt4_io
        00000100    0     wine_threadpool_worker
00000044 winedevice.exe
        00000048    0
        00000054    0
        00000058    0     wine_sechost_service
        0000005c    0
        00000060    0
        00000064    0
        000000c4    0
        000000c8    0
00000068 winedevice.exe
        0000006c    0
        00000074    0
        00000078    0     wine_sechost_service
        0000007c    0
        00000080    0
        00000084    0
        00000098    0
        0000009c    0
00000088 explorer.exe
        0000008c    0
        000000e8    0
        000000ec    0     wine_rpcrt4_server
00000090 plugplay.exe
        00000094    0
        000000a4    0
        000000a8    0     wine_sechost_service
        000000ac    0     wine_rpcrt4_server
        00000160    0     wine_rpcrt4_io
        00000164    0     wine_threadpool_worker
000000b0 svchost.exe
        000000b4    0
        000000bc    0
        000000c0    0     wine_sechost_service
000000d0 conhost.exe
        000000d4    0
000000d8 (D) Z:\home\lemtea\Download\Godot_v4.3-dev4_win64.exe\Godot_v4.3-dev4_win64.exe
        000000dc    0 <==
        00000124    0
        00000128    0
        0000012c    0
        00000130    0
        00000134    0
        00000138    0
        0000013c    0
        00000140    0
        00000144    0
        00000148    0
        0000014c    0
        00000150    0
        00000154    0
        00000158    0     wine_xinput_hid_update
        0000015c    0     wine_sechost_device_notify
        00000168    0     wine_mmdevapi_notification
        0000016c   15     audio_client_main
        00000170    0
        00000174   15     audio_client_timer
        00000178    0
        00000184    0
000000f4 rpcss.exe
        000000f8    0
        00000104    0
        00000108    0     wine_sechost_service
        0000010c    0     wine_rpcrt4_server
        00000110    0     wine_rpcrt4_server
        00000114    0     wine_rpcrt4_io
        00000118    0     wine_threadpool_worker
System information:
    Wine build: wine-9.0
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 6.8.9-100.fc38.x86_64
```

</details>

Full Wine error message under 4.3 beta1:
<details>

```
Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org
Failed to enable screen_keep_on.
OpenGL API 3.3.0 NVIDIA 550.78 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1660 Ti


================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.beta1.official (a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(0): executable file is not COFF
[2] error(-1): failed to read executable information
[3] error(-1): failed to read executable information
[4] error(-1): failed to read executable information
[5] error(-1): failed to read executable information
[6] error(-1): failed to read executable information
[7] error(-1): failed to read executable information
[8] error(-1): failed to read executable information
[9] error(-1): failed to read executable information
[10] error(-1): failed to read executable information
[11] error(-1): failed to read executable information
[12] error(-1): failed to read executable information
[13] error(-1): failed to read executable information
[14] error(-1): failed to read executable information
[15] error(-1): failed to read executable information
[16] error(-1): failed to read executable information
[17] error(-1): failed to read executable information
[18] error(-1): failed to read executable information
[19] error(-1): failed to read executable information
[20] error(-1): failed to read executable information
[21] error(-1): failed to read executable information
-- END OF BACKTRACE --
================================================================
wine: Unhandled page fault on read access to 0000000080070116 at address 00006FFFF834CDD0 (thread 00dc), starting debugger...
Unhandled exception: page fault on read access to 0x0000000080070116 in 64-bit code (0x006ffff834cdd0).
Register dump:
 rip:00006ffff834cdd0 rsp:00007ffffe8fed10 rbp:00000000000000d2 eflags:00010206 (  R- --  I   - -P- )
 rax:00000000ffffffff rbx:0000000000000000 rcx:0000000080070006 rdx:0000000080070006
 rsi:0000000000000000 rdi:00000000000000d2  r8:0000000000000000  r9:00000000000000d2 r10:00006fffffcc2b20
 r11:0000000000000202 r12:0000000080070006 r13:00006ffff8355070 r14:00007f1931a5e3c0 r15:00007ffffe8fefc0
Stack dump:
0x007ffffe8fed10:  00007ffffe8fedb0 0000000080070057
0x007ffffe8fed20:  00000000000000d2 00007ffffe8fee50
0x007ffffe8fed30:  00007f1931a5e3c0 00006ffff834d6cd
0x007ffffe8fed40:  00007ffffe8fefc0 00006fffffcad237
0x007ffffe8fed50:  00007ffffefe0000 0000000080070006
0x007ffffe8fed60:  0000000000000000 0000000000000000
0x007ffffe8fed70:  0000000080070057 00000000000000d2
0x007ffffe8fed80:  00007ffffe8fee50 00006ffff834da2e
0x007ffffe8fed90:  00007ffffe8fee30 0000000000000000
0x007ffffe8feda0:  00007ffffe8fefa0 00006ffff8355040
0x007ffffe8fedb0:  00007f19000000d2 00006fff00000000
0x007ffffe8fedc0:  00007f19000000d2 00000001442751f1
Backtrace:
me/msstyles.c:509] in uxtheme (0x000000000000d2)ompiler>, tc=0000000080070006) [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxthe
x000000000000d2)ot accessible in this frame>) [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/msstyles.c:1164] in uxtheme (0
/wine-9.0/dlls/uxtheme/property.c:126] in uxtheme (0x00000080070057)not accessible in this frame>) [/home/abuild/rpmbuild/BUILD
000000000000000)SP not accessible in this frame>) [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/draw.c:2185] in uxtheme (0
  4 0x0000014000688d in godot_v4.3-beta1_win64 (+0x688d) (0x00000147652f48)
  5 0x00000141afd6ec in godot_v4.3-beta1_win64 (+0x1afd6ec) (0x00000147652f48)
  6 0x00000141b06d08 in godot_v4.3-beta1_win64 (+0x1b06d08) (0x00000147653118)
  7 0x0000014129bb5d in godot_v4.3-beta1_win64 (+0x129bb5d) (0x007ffffe8ff580)
  8 0x00000140096b0c in godot_v4.3-beta1_win64 (+0x96b0c) (0x007ffffe8ff890)
  9 0x0000014009b4bc in godot_v4.3-beta1_win64 (+0x9b4bc) (0x007fffffb01db8)
  10 0x00000145231243 in godot_v4.3-beta1_win64 (+0x5231243) (0x007ffffefe34c0)
  11 0x000001400012ee in godot_v4.3-beta1_win64 (+0x12ee) (0x007ffffefe34c0)
  12 0x000001400013e6 in godot_v4.3-beta1_win64 (+0x13e6) (0000000000000000)
uild/rpmbuild/BUILD/wine-9.0/dlls/kernel32/thread.c:61] in kernel32 (0000000000000000)l error>, arg=<internal error>) [/home/ab
  14 0x006fffffca54fb in ntdll (+0x554fb) (0000000000000000)
 0x110(%rdx), %raxSSTYLES_FindProperty+0x40 [/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/msstyles.c:1164] in uxtheme: mov
Unable to access file '/home/abuild/rpmbuild/BUILD/wine-9.0/dlls/uxtheme/msstyles.c'
Modules:
Module  Address                                 Debug info      Name (146 modules)
PE-Wine         79300000-        7988d000       Deferred        opengl32
PE             140000000-       1478fb000       Export          godot_v4.3-beta1_win64
PE-Wine     6ffff8340000-    6ffff840a000       Dwarf-4-5       uxtheme
PE-Wine     6ffff8420000-    6ffff844f000       Deferred        wsock32
PE-Wine     6ffff8460000-    6ffff84dc000       Deferred        msacm32
PE-Wine     6ffff84f0000-    6ffff86aa000       Deferred        winmm
PE-Wine     6ffff86c0000-    6ffff86e0000       Deferred        version
PE-Wine     6ffff86f0000-    6ffff9cf7000       Deferred        wined3d
PE-Wine     6ffff9d10000-    6ffff9e58000       Deferred        dxgi
PE-Wine     6ffff9e70000-    6ffffa188000       Deferred        dwrite
PE-Wine     6ffffa1a0000-    6ffffa1c5000       Deferred        dwmapi
PE-Wine     6ffffa1e0000-    6ffffa215000       Deferred        hid
PE-Wine     6ffffa230000-    6ffffa793000       Deferred        comctl32
PE-Wine     6ffffa7b0000-    6ffffa8dc000       Deferred        dinput8
PE-Wine     6ffffa8f0000-    6ffffabdd000       Deferred        dbghelp
PE-Wine     6ffffabf0000-    6ffffafb4000       Deferred        crypt32
PE-Wine     6ffffafd0000-    6ffffb02a000       Deferred        bcrypt
PE-Wine     6ffffb040000-    6ffffb05d000       Deferred        avrt
PE-Wine     6ffffb070000-    6ffffb094000       Deferred        nsi
PE-Wine     6ffffb0b0000-    6ffffb0fe000       Deferred        dnsapi
PE-Wine     6ffffb110000-    6ffffb19e000       Deferred        iphlpapi
PE-Wine     6ffffb260000-    6ffffb2b9000       Deferred        winex11
PE-Wine     6ffffb360000-    6ffffb3de000       Deferred        imm32
PE-Wine     6ffffb6d0000-    6ffffb8a9000       Deferred        setupapi
PE-Wine     6ffffb950000-    6ffffbe46000       Deferred        oleaut32
PE-Wine     6ffffc290000-    6ffffc2ae000       Deferred        winepulse
PE-Wine     6ffffc2c0000-    6ffffc3b1000       Deferred        mmdevapi
PE-Wine     6ffffc3d0000-    6ffffc40a000       Deferred        xinput1_4
PE-Wine     6ffffc420000-    6ffffc452000       Deferred        compstui
PE-Wine     6ffffc470000-    6ffffc539000       Deferred        winspool
PE-Wine     6ffffc550000-    6ffffc6bb000       Deferred        wbemprox
PE-Wine     6ffffc6d0000-    6ffffc70f000       Deferred        wintab32
PE-Wine     6ffffc720000-    6ffffc773000       Deferred        shcore
PE-Wine     6ffffc790000-    6ffffc8aa000       Deferred        shlwapi
PE-Wine     6ffffc8c0000-    6ffffd64a000       Deferred        shell32
PE-Wine     6ffffd660000-    6ffffd6ad000       Deferred        coml2
PE-Wine     6ffffd6c0000-    6ffffd950000       Deferred        rpcrt4
PE-Wine     6ffffd960000-    6ffffd99c000       Deferred        win32u
PE-Wine     6ffffd9b0000-    6ffffdf90000       Deferred        user32
PE-Wine     6ffffdfa0000-    6ffffe265000       Deferred        gdi32
PE-Wine     6ffffe280000-    6ffffe41b000       Deferred        combase
PE-Wine     6ffffe430000-    6ffffe9d9000       Deferred        ole32
PE-Wine     6ffffe9f0000-    6ffffea9d000       Deferred        ws2_32
PE-Wine     6ffffeab0000-    6ffffeeac000       Deferred        ucrtbase
PE-Wine     6ffffeec0000-    6ffffef82000       Deferred        sechost
PE-Wine     6ffffefa0000-    6fffff2ff000       Deferred        msvcrt
PE-Wine     6fffff310000-    6fffff43d000       Deferred        advapi32
PE-Wine     6fffff450000-    6fffffa67000       Deferred        kernelbase
PE-Wine     6fffffa80000-    6fffffc3b000       Dwarf-4-5       kernel32
PE-Wine     6fffffc50000-    6fffffff0000       Dwarf-4-5       ntdll
ELF         7f1919400000-    7f191be06000       Deferred        libnvidia-gpucomp.so.550.78
ELF         7f1926000000-    7f1927f15000       Deferred        libnvidia-glcore.so.550.78
ELF         7f1931200000-    7f1931627000       Deferred        libcrypto.so.3
ELF         7f193aa80000-    7f193aaf8000       Deferred        libmp3lame.so.0
ELF         7f193aaf8000-    7f193ab55000       Deferred        libmpg123.so.0
ELF         7f193ab55000-    7f193ac00000       Deferred        libvorbisenc.so.2
ELF         7f193b40c000-    7f193b468000       Deferred        libopus.so.0
ELF         7f193b468000-    7f193b497000       Deferred        libvorbis.so.0
ELF         7f193b497000-    7f193b4fd000       Deferred        libflac.so.12
ELF         7f193b4fd000-    7f193b57b000       Deferred        libsndfile.so.1
ELF         7f193b57b000-    7f193b600000       Deferred        libpulsecommon-16.1.so
ELF         7f194001a000-    7f1940029000       Deferred        libgsm.so.1
ELF         7f1940029000-    7f194007b000       Deferred        libpulse.so.0
ELF         7f19401b4000-    7f19401be000       Deferred        libogg.so.0
ELF         7f19404b2000-    7f19404d4000       Deferred        liblz4.so.1
ELF         7f19404d4000-    7f19405bb000       Deferred        libsystemd.so.0
ELF         7f1941009000-    7f19410c8000       Deferred        libzstd.so.1
ELF         7f19410c8000-    7f19410d2000       Deferred        libcap.so.2
ELF         7f19410d2000-    7f1941127000       Deferred        libdbus-1.so.3
ELF         7f1941127000-    7f1941200000       Deferred        libkrb5.so.3
ELF         7f1941a09000-    7f1941a36000       Deferred        libselinux.so.1
ELF         7f1941a36000-    7f1941a46000       Deferred        libkrb5support.so.0
ELF         7f1941a46000-    7f1941a5e000       Deferred        libk5crypto.so.3
ELF         7f1941a5e000-    7f1941b00000       Deferred        libcups.so.2
ELF         7f1942407000-    7f194241b000       Deferred        libavahi-client.so.3
ELF         7f194241b000-    7f194242a000       Deferred        libavahi-common.so.3
ELF         7f194242a000-    7f1942480000       Deferred        libgssapi_krb5.so.2
ELF         7f1942a01000-    7f1942a08000       Deferred        libkeyutils.so.1
ELF         7f1942a9b000-    7f1942ab2000       Deferred        libdrm.so.2
ELF         7f1942ab8000-    7f1942ac0000       Deferred        libasyncns.so.0
ELF         7f1942ac2000-    7f1942ad7000       Deferred        winepulse.so
ELF         7f1942ad7000-    7f1942c00000       Deferred        libglx_nvidia.so.0
ELF         7f1943405000-    7f194340c000       Deferred        libcom_err.so.2
ELF         7f194340c000-    7f1943411000       Deferred        libx11-xcb.so.1
ELF         7f1943411000-    7f1943418000       Deferred        libxcb-dri3.so.0
ELF         7f1943418000-    7f194342a000       Deferred        libxcb-randr.so.0
ELF         7f194342a000-    7f19434c1000       Deferred        libnvidia-glsi.so.550.78
ELF         7f19434c1000-    7f1943579000       Deferred        libgldispatch.so.0
ELF         7f1943579000-    7f1943600000       Deferred        libgl.so.1
ELF         7f1943802000-    7f194381e000       Deferred        libxcb-glx.so.0
ELF         7f194381e000-    7f1943823000       Deferred        librt.so.1
ELF         7f1943823000-    7f1943828000       Deferred        libpthread.so.0
ELF         7f1943828000-    7f194385b000       Deferred        libglx.so.0
ELF         7f194385e000-    7f1943864000       Deferred        winspool.so
ELF         7f1943883000-    7f1943888000       Deferred        libdl.so.2
ELF         7f1943888000-    7f194388e000       Deferred        libnvidia-tls.so.550.78
ELF         7f194399e000-    7f19439a5000       Deferred        ws2_32.so
ELF         7f19439a5000-    7f1943ade000       Deferred        opengl32.so
ELF         7f1943b02000-    7f1943b0a000       Deferred        libxfixes.so.3
ELF         7f1943b0a000-    7f1943b17000       Deferred        libxcursor.so.1
ELF         7f1943b17000-    7f1943b2a000       Deferred        libxi.so.6
ELF         7f1943b2a000-    7f1943b2f000       Deferred        libxcomposite.so.1
ELF         7f1943b2f000-    7f1943b3c000       Deferred        libxrandr.so.2
ELF         7f1943b3c000-    7f1943b48000       Deferred        libxrender.so.1
ELF         7f1943b48000-    7f1943b4f000       Deferred        libxxf86vm.so.1
ELF         7f1943b4f000-    7f1943b54000       Deferred        libxinerama.so.1
ELF         7f1943b54000-    7f1943b5a000       Deferred        libxau.so.6
ELF         7f1943b5a000-    7f1943b85000       Deferred        libxcb.so.1
ELF         7f1943b85000-    7f1943ccc000       Deferred        libx11.so.6
ELF         7f1943ccc000-    7f1943ce0000       Deferred        libxext.so.6
ELF         7f1943ce4000-    7f1943cf6000       Deferred        libresolv.so.2
ELF         7f1943cf6000-    7f1943cfb000       Deferred        dnsapi.so
ELF         7f1943cfb000-    7f1943d01000       Deferred        dwrite.so
ELF         7f1943d05000-    7f1943d8a000       Deferred        winex11.so
ELF         7f1943d8a000-    7f1943d90000       Deferred        crypt32.so
ELF         7f1943ec8000-    7f1943efb000       Deferred        liblzma.so.5
ELF         7f1943efb000-    7f194406f000       Deferred        libxml2.so.2
ELF         7f194406f000-    7f19440be000       Deferred        libfontconfig.so.1
ELF         7f19440be000-    7f1944158000       Deferred        libpcre2-8.so.0
ELF         7f1944158000-    7f194417b000       Deferred        libbrotlicommon.so.1
ELF         7f194417b000-    7f194419c000       Deferred        libgraphite2.so.3
ELF         7f194419c000-    7f19442e5000       Deferred        libglib-2.0.so.0
ELF         7f19442e5000-    7f19443e1000       Deferred        libharfbuzz.so.0
ELF         7f19443e1000-    7f194441a000       Deferred        libpng16.so.16
ELF         7f194441a000-    7f19444ea000       Deferred        libfreetype.so.6
ELF         7f19444ea000-    7f19445cb000       Deferred        libm.so.6
ELF         7f19445cb000-    7f1944769000       Deferred        win32u.so
ELF         7f1944769000-    7f194480e000       Deferred        libgmp.so.10
ELF         7f194480e000-    7f1944851000       Deferred        libhogweed.so.6
ELF         7f1944851000-    7f1944a00000       Deferred        libunistring.so.5
ELF         7f1944a00000-    7f1944c32000       Deferred        libgnutls.so.30
ELF         7f1944c34000-    7f1944c41000       Deferred        libbrotlidec.so.1
ELF         7f1944c41000-    7f1944c5b000       Deferred        libz.so.1
ELF         7f1944c5b000-    7f1944c6f000       Deferred        libbz2.so.1
ELF         7f1944c6f000-    7f1944e00000       Deferred        libp11-kit.so.0
ELF         7f1952801000-    7f195280d000       Deferred        libffi.so.8
ELF         7f195280d000-    7f1952860000       Deferred        libnettle.so.8
ELF         7f1952860000-    7f1952882000       Deferred        libidn2.so.0
ELF         7f19528a7000-    7f19528cb000       Deferred        libgcc_s.so.1
ELF         7f19528cb000-    7f19528e5000       Deferred        libunwind.so.8
ELF         7f19528e5000-    7f19529a0000       Export          ntdll.so
ELF         7f19529a2000-    7f1952b80000       Deferred        libc.so.6
ELF         7f1952b85000-    7f1952b9b000       Deferred        libtasn1.so.6
ELF         7f1952b9b000-    7f1952ba7000       Deferred        bcrypt.so
ELF         7f1952ba7000-    7f1952bdd000       Deferred        ld-linux-x86-64.so.2
ELF         7f1952bdd000-    7f1952be2000       Deferred        <wine-loader>
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
        00000024    0
00000038 services.exe
        0000003c    0
        00000040    0     wine_rpcrt4_server
        0000004c    0     wine_rpcrt4_io
        00000050    0     wine_threadpool_worker
        00000070    0     wine_rpcrt4_io
        000000a0    0     wine_rpcrt4_io
        000000b8    0     wine_rpcrt4_io
        000000cc    0
        000000fc    0     wine_rpcrt4_io
        00000100    0     wine_threadpool_worker
00000044 winedevice.exe
        00000048    0
        00000054    0
        00000058    0     wine_sechost_service
        0000005c    0
        00000060    0
        00000064    0
        000000c4    0
        000000c8    0
00000068 winedevice.exe
        0000006c    0
        00000074    0
        00000078    0     wine_sechost_service
        0000007c    0
        00000080    0
        00000084    0
        00000098    0
        0000009c    0
00000088 explorer.exe
        0000008c    0
        000000e8    0
        000000ec    0     wine_rpcrt4_server
00000090 plugplay.exe
        00000094    0
        000000a4    0
        000000a8    0     wine_sechost_service
        000000ac    0     wine_rpcrt4_server
        00000160    0     wine_rpcrt4_io
        00000164    0     wine_threadpool_worker
000000b0 svchost.exe
        000000b4    0
        000000bc    0
        000000c0    0     wine_sechost_service
000000d0 conhost.exe
        000000d4    0
000000d8 (D) Z:\home\lemtea\Download\Godot_v4.3-beta1_win64.exe\Godot_v4.3-beta1_win64.exe
        000000dc    0 <==
        00000124    0
        00000128    0
        0000012c    0
        00000130    0
        00000134    0
        00000138    0
        0000013c    0
        00000140    0
        00000144    0
        00000148    0
        0000014c    0
        00000150    0
        00000154    0
        00000158    0     wine_xinput_hid_update
        0000015c    0     wine_sechost_device_notify
        00000168    0     wine_mmdevapi_notification
        0000016c   15     audio_client_main
        00000170    0
        00000174   15     audio_client_timer
        00000178    0
        00000184    0
000000f4 rpcss.exe
        000000f8    0
        00000104    0
        00000108    0     wine_sechost_service
        0000010c    0     wine_rpcrt4_server
        00000110    0     wine_rpcrt4_server
        00000114    0     wine_rpcrt4_io
        00000118    0     wine_threadpool_worker
System information:
    Wine build: wine-9.0
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 6.8.9-100.fc38.x86_64
```

</details>

### Steps to reproduce

1. Download godot editor after version 4.3 dev4
2. Run with wine 9.0
3. Crash

### Minimal reproduction project (MRP)

It's editor/core bug.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/93123

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -5595,52 +5595,57 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
...
-			}
-			RefreshImmersiveColorPolicyStatePtr RefreshImmersiveColorPolicyState = (RefreshImmersiveColorPolicyStatePtr)GetProcAddress(ux_theme_lib, MAKEINTRESOURCEA(104));
-			if (ShouldAppsUseDarkMode) {
-				bool dark_mode = ShouldAppsUseDarkMode();
-				if (SetPreferredAppMode) {
-					SetPreferredAppMode(dark_mode ? APPMODE_ALLOWDARK : APPMODE_DEFAULT);
-				} else if (AllowDarkModeForApp) {
-					AllowDarkModeForApp(dark_mode);
+	// Load UXTheme, available on Windows 10+ only.
+	if (os_ver.dwBuildNumber >= 10240) {
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:5609]: Note: This check should be sufficient for most cases, but under Wine you can override Windows build version with an arbitrary value, so I have added an extra Wine detection above as well.

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -5595,52 +5595,57 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
 
 	HMODULE nt_lib = LoadLibraryW(L"ntdll.dll");
 	if (nt_lib) {
-		RtlGetVersionPtr RtlGetVersion = (RtlGetVersionPtr)GetProcAddress(nt_lib, "RtlGetVersion");
-		if (RtlGetVersion) {
-			RtlGetVersion(&os_ver);
+		WineGetVersionPtr wine_get_version = (WineGetVersionPtr)GetProcAddress(nt_lib, "wine_get_version"); // Do not read Windows build number under Wine, it can be set to arbitrarty value.
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:5598]:
```suggestion
		WineGetVersionPtr wine_get_version = (WineGetVersionPtr)GetProcAddress(nt_lib, "wine_get_version"); // Do not read Windows build number under Wine, it can be set to arbitrary value.
```

**Review by akien-mga — APPROVED** [review]
