### PR TITLE
Pass viewport size to shadow pass instead of using Vector2i(1,1)

### LINKED ISSUE #82782: spatial shader: using VIEWPORT_SIZE in VERTEX calculation breaks shadows
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

I'm trying to implement a vertex jitter shader to emulate psx style graphics. 

See: https://github.com/AnalogFeelings/godot-psx for a public implementation I am using for reference.

The shader should support shadows but there appears to be a bug in Godot that is preventing shadows from appearing.

As far as I can tell, the issue relates to VIEWPORT_SIZE. The shader uses VIEWPORT_SIZE to scale the jitter based on screensize.

### Steps to reproduce

1. spatial shader
2. include render mode `render_mode skip_vertex_transform`
3. inside the `vertex()` function,
4. use `VIEWPORT_SIZE` in some part of the calculation of VERTEX.

### Minimal reproduction project

[no_shadows.zip](https://github.com/godotengine/godot/files/12802376/no_shadows.zip)

See screenshot below:

1. A cube with a default material; shadows are displayed correctly
2. A cube with a custom material `jitter-not-using-viewport.tres`; shadows are displayed correctly
            The custom material essentially just does `VERTEX = round(VERTEX * i) / i;`, where i is set by the user
3. A cube with a custom material `jitter-using-viewport`; shadows are not displayed correctly
            The custom material scales `i` by `VIEWPORT_SIZE.y`

cubes

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #82782

Two things to improve:
1. the argument order, I put `p_viewport_size` to the last but it may better be inserted somewhere front
2. If 1 is ok and in general this commit is ok, I will port it to compatibility mode.

### CODE REVIEW

**Comment by clayjohn** [comment]
> Two things to improve:
> 
> 1. the argument order, I put `p_viewport_size` to the last but it may better be inserted somewhere front
> 2. If 1 is ok and in general this commit is ok, I will port it to compatibility and mobile mode.

Putting it last is fine. This commit looks fine, please make the same change to the compatibility renderer and then it should be ready to merge!

**Review by clayjohn — APPROVED** [review]
Looks good to me!

Let's not cherrypick this one as it will introduce a behaviour change if someone was erroneously relying on VIEWPORT_SIZE being (1,1) (for example to modify the shader when in a shadow pass)

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h [hunk 1]
```diff
@@ -593,9 +593,9 @@ class RenderForwardClustered : public RendererSceneRenderRD {
...
+	void _render_shadow_append(RID p_framebuffer, const PagedArray<RenderGeometryInstance *> &p_instances, const Projection &p_projection, const Transform3D &p_transform, float p_zfar, float p_bias, float p_normal_bias, bool p_reverse_cull_face, bool p_use_dp, bool p_use_dp_flip, bool p_use_pancake, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0.0, float p_screen_mesh_lod_threshold = 0.0, const Rect2i &p_rect = Rect2i(), bool p_flip_y = false, bool p_clear_region = true, bool p_begin = true, bool p_end = true, RenderingMethod::RenderInfo *p_render_info = nullptr, Size2i p_viewport_size = Size2i(1, 1));
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:598]:
```suggestion
	void _render_shadow_append(RID p_framebuffer, const PagedArray<RenderGeometryInstance *> &p_instances, const Projection &p_projection, const Transform3D &p_transform, float p_zfar, float p_bias, float p_normal_bias, bool p_reverse_cull_face, bool p_use_dp, bool p_use_dp_flip, bool p_use_pancake, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0.0, float p_screen_mesh_lod_threshold = 0.0, const Rect2i &p_rect = Rect2i(), bool p_flip_y = false, bool p_clear_region = true, bool p_begin = true, bool p_end = true, RenderingMethod::RenderInfo *p_render_info = nullptr, const Size2i &p_viewport_size = Size2i(1, 1));
```

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 2]
```diff
@@ -2491,7 +2496,7 @@ void RenderForwardClustered::_render_shadow_begin() {
 	scene_state.instance_data[RENDER_LIST_SECONDARY].clear();
 }
 
-void RenderForwardClustered::_render_shadow_append(RID p_framebuffer, const PagedArray<RenderGeometryInstance *> &p_instances, const Projection &p_projection, const Transform3D &p_transform, float p_zfar, float p_bias, float p_normal_bias, bool p_reverse_cull_face, bool p_use_dp, bool p_use_dp_flip, bool p_use_pancake, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, const Rect2i &p_rect, bool p_flip_y, bool p_clear_region, bool p_begin, bool p_end, RenderingMethod::RenderInfo *p_render_info) {
+void RenderForwardClustered::_render_shadow_append(RID p_framebuffer, const PagedArray<RenderGeometryInstance *> &p_instances, const Projection &p_projection, const Transform3D &p_transform, float p_zfar, float p_bias, float p_normal_bias, bool p_reverse_cull_face, bool p_use_dp, bool p_use_dp_flip, bool p_use_pancake, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, const Rect2i &p_rect, bool p_flip_y, bool p_clear_region, bool p_begin, bool p_end, RenderingMethod::RenderInfo *p_render_info, Size2i p_viewport_size) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:2499]:
```suggestion
void RenderForwardClustered::_render_shadow_append(RID p_framebuffer, const PagedArray<RenderGeometryInstance *> &p_instances, const Projection &p_projection, const Transform3D &p_transform, float p_zfar, float p_bias, float p_normal_bias, bool p_reverse_cull_face, bool p_use_dp, bool p_use_dp_flip, bool p_use_pancake, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, const Rect2i &p_rect, bool p_flip_y, bool p_clear_region, bool p_begin, bool p_end, RenderingMethod::RenderInfo *p_render_info, const Size2i &p_viewport_size) {
```

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 3]
```diff
@@ -2305,7 +2310,7 @@ void RenderForwardClustered::_render_buffers_debug_draw(const RenderDataRD *p_re
 	}
 }
 
-void RenderForwardClustered::_render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, bool p_open_pass, bool p_close_pass, bool p_clear_region, RenderingMethod::RenderInfo *p_render_info) {
+void RenderForwardClustered::_render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, bool p_open_pass, bool p_close_pass, bool p_clear_region, RenderingMethod::RenderInfo *p_render_info, Size2i p_viewport_size) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:2313]:
```suggestion
void RenderForwardClustered::_render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, bool p_open_pass, bool p_close_pass, bool p_clear_region, RenderingMethod::RenderInfo *p_render_info, const Size2i &p_viewport_size) {
```

File: drivers/gles3/rasterizer_scene_gles3.h [hunk 4]
```diff
@@ -516,8 +516,8 @@ class RasterizerSceneGLES3 : public RendererSceneRender {
 	void _setup_lights(const RenderDataGLES3 *p_render_data, bool p_using_shadows, uint32_t &r_directional_light_count, uint32_t &r_omni_light_count, uint32_t &r_spot_light_count, uint32_t &r_directional_shadow_count);
 	void _setup_environment(const RenderDataGLES3 *p_render_data, bool p_no_fog, const Size2i &p_screen_size, bool p_flip_y, const Color &p_default_bg_color, bool p_pancake_shadows, float p_shadow_bias = 0.0);
 	void _fill_render_list(RenderListType p_render_list, const RenderDataGLES3 *p_render_data, PassMode p_pass_mode, bool p_append = false);
-	void _render_shadows(const RenderDataGLES3 *p_render_data);
-	void _render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0, float p_screen_mesh_lod_threshold = 0.0, RenderingMethod::RenderInfo *p_render_info = nullptr);
+	void _render_shadows(const RenderDataGLES3 *p_render_data, Size2i p_viewport_size = Size2i(1, 1));
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_scene_gles3.h:519]:
```suggestion
	void _render_shadows(const RenderDataGLES3 *p_render_data, const Size2i &p_viewport_size = Size2i(1, 1));
```

File: drivers/gles3/rasterizer_scene_gles3.h [hunk 5]
```diff
@@ -516,8 +516,8 @@ class RasterizerSceneGLES3 : public RendererSceneRender {
...
+	void _render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0, float p_screen_mesh_lod_threshold = 0.0, RenderingMethod::RenderInfo *p_render_info = nullptr, Size2i p_viewport_size = Size2i(1, 1));
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_scene_gles3.h:520]:
```suggestion
	void _render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0, float p_screen_mesh_lod_threshold = 0.0, RenderingMethod::RenderInfo *p_render_info = nullptr, const Size2i &p_viewport_size = Size2i(1, 1));
```

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 6]
```diff
@@ -1932,20 +1932,20 @@ void RasterizerSceneGLES3::_render_shadows(const RenderDataGLES3 *p_render_data)
...
+			_render_shadow_pass(p_render_data->render_shadows[shadows[i]].light, p_render_data->shadow_atlas, p_render_data->render_shadows[shadows[i]].pass, p_render_data->render_shadows[shadows[i]].instances, camera_plane, lod_distance_multiplier, p_render_data->screen_mesh_lod_threshold, p_render_data->render_info, p_viewport_size);
 		}
 	}
 }
 
-void RasterizerSceneGLES3::_render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, RenderingMethod::RenderInfo *p_render_info) {
+void RasterizerSceneGLES3::_render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, RenderingMethod::RenderInfo *p_render_info, Size2i p_viewport_size) {
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_scene_gles3.cpp:1948]:
```suggestion
void RasterizerSceneGLES3::_render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane, float p_lod_distance_multiplier, float p_screen_mesh_lod_threshold, RenderingMethod::RenderInfo *p_render_info, const Size2i &p_viewport_size) {
```

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 7]
```diff
@@ -1896,7 +1896,7 @@ void RasterizerSceneGLES3::_setup_lights(const RenderDataGLES3 *p_render_data, b
 }
 
 // Render shadows
-void RasterizerSceneGLES3::_render_shadows(const RenderDataGLES3 *p_render_data) {
+void RasterizerSceneGLES3::_render_shadows(const RenderDataGLES3 *p_render_data, Size2i p_viewport_size) {
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_scene_gles3.cpp:1899]:
```suggestion
void RasterizerSceneGLES3::_render_shadows(const RenderDataGLES3 *p_render_data, const Size2i &p_viewport_size) {
```

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h [hunk 8]
```diff
@@ -593,9 +593,9 @@ class RenderForwardClustered : public RendererSceneRenderRD {
 
 	/* Render shadows */
 
-	void _render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0, float p_screen_mesh_lod_threshold = 0.0, bool p_open_pass = true, bool p_close_pass = true, bool p_clear_region = true, RenderingMethod::RenderInfo *p_render_info = nullptr);
+	void _render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0, float p_screen_mesh_lod_threshold = 0.0, bool p_open_pass = true, bool p_close_pass = true, bool p_clear_region = true, RenderingMethod::RenderInfo *p_render_info = nullptr, Size2i p_viewport_size = Size2i(1, 1));
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:596]:
```suggestion
	void _render_shadow_pass(RID p_light, RID p_shadow_atlas, int p_pass, const PagedArray<RenderGeometryInstance *> &p_instances, const Plane &p_camera_plane = Plane(), float p_lod_distance_multiplier = 0, float p_screen_mesh_lod_threshold = 0.0, bool p_open_pass = true, bool p_close_pass = true, bool p_clear_region = true, RenderingMethod::RenderInfo *p_render_info = nullptr, const Size2i &p_viewport_size = Size2i(1, 1));
```

Comment (jsjtxietian) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:596]: copying two int is very cheap, no need to use const &

Comment (AThousandShips) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:596]: We do it pretty much everywhere, it's preferable generally

Comment (akien-mga) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:596]: Indeed see `const Plane &p_camera_plane` in this function, we try to do it for all vector types for consistency.

Comment (jsjtxietian) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:596]: No problem!

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
