### PR TITLE
Change Basis is_equal_approx to use instance method

### LINKED ISSUE #37390: Basis.is_equal_approx() not working
**Godot version:**
3.2 stable official

**OS/device including version:**
Windows 10

**Issue description:**

Basis.is_equal_approx() is failing even when the difference is less than Epsilon.

As an example, I am using: `transform.basis = transform.basis.slerp(_target_rotation, ROTATION_SPEED)` within _physics_process() to rotate a body.

When I try to check if the rotation is complete using `	if transform.basis.is_equal_approx(_target_rotation, 0.01):` the condition never equates to true. Note the ridiculously high epsilon. (Which would surely cause issues if it worked.)

If I print the current and target Basis after the comparison fails, I get:

Current:  `((0.000004, 0, 1), (0, 1, 0), (-1, 0, 0.000004))`

Target: `((-0, 0, 1), (0, 1, 0), (-1, 0, -0))`

Which are well within the Epsilon range.

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #37390. I placed TODOs on this code as part of #32477 since this change breaks compat, but now we can fix this for 4.0. Test code:

```
	var a = Basis(Vector3(0.000004, 0, 1), Vector3(0, 1, 0), Vector3(-1, 0, 0.000004))
	var b = Basis(Vector3(0, 0, 1), Vector3(0, 1, 0), Vector3(-1, 0, 0))
	print(a.is_equal_approx(b)) # True
```

Also, since `is_equal_approx_ratio` is no longer used in any exposed API and serves no purpose, we can remove it, so I did. Also, I added `#ifdef MATH_CHECKS` for some code that is only used when `MATH_CHECKS` is defined. These changes are in the 2nd commit.

### CODE REVIEW

File: core/math/basis.cpp [hunk 1]
```diff
@@ -123,17 +123,20 @@ bool Basis::is_rotation() const {
 	return Math::is_equal_approx(determinant(), 1, UNIT_EPSILON) && is_orthogonal();
 }
 
+#ifdef MATH_CHECKS
+// This method is only used once, in diagonalize. If it's desired elsewhere, feel free to remove the #ifdef.
 bool Basis::is_symmetric() const {
 
-	if (!Math::is_equal_approx_ratio(elements[0][1], elements[1][0], UNIT_EPSILON))
+	if (!Math::is_equal_approx(elements[0][1], elements[1][0]))
```
Comment (akien-mga) [inline core/math/basis.cpp:130]: The previous version using `UNIT_EPSILON` was a lot more lenient since it defaults to 0.001 *and* it was a ratio. This will likely bring back the "false positive" !symmetric errors that led @reduz to implement a lenient `UNIT_EPSILON` in the first place.

So you should discuss this with him.

Comment (aaronfranke) [reply core/math/basis.cpp:130]: Related discussion: https://github.com/godotengine/godot/issues/37241

**Comment by aaronfranke** [comment]
@akien-mga From IRC:

> aaronfranke
> > reduz: What about reviewing #37403 and the issue #37241 ? These are issues where akien wanted your input.

> reduz
> > aaronfranke: i guess they are ok, but let akien decide i guess

**Comment by akien-mga** [comment]
Thanks!
