### PR TITLE
Fix C# `operator *(Transform3D, Aabb)`

### LINKED ISSUE #97197: Transform3D Aabb operator * does not handle rotations properly  [C#]
### Tested versions

reproduced in 4.3.stable.mono
not attempted in other versions

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (NVIDIA; 32.0.15.6070) - AMD Ryzen 9 7900 12-Core Processor (24 Threads)

### Issue description

I think that the csharp code for `public static Aabb operator *(Transform3D transform, Aabb aabb)` does not handle rotated+offsetPosition AABB's correctly.     

The code, from Godot's `Transform3D.cs` is as follows:  https://github.com/godotengine/godot/blob/0a4aedb36065f66fc7e99cb2e6de3e55242f9dfb/modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs#L460 

When I change to use my own custom version, everything works properly:

```csharp
	public static Aabb _Transformed(this Aabb aabb, Transform3D transform)
	{
		////////////////////////////////////////////////////////
		//full corner method:  accurate
		/////////////////////////////////////////////////
		////
		//// Get the 8 corners of the AABB

		Vector3[] corners = new Vector3[8];
		corners[0] = new Vector3(aabb.Position.X, aabb.Position.Y, aabb.Position.Z);
		corners[1] = new Vector3(aabb.Position.X, aabb.Position.Y, aabb.End.Z);
		corners[2] = new Vector3(aabb.Position.X, aabb.End.Y, aabb.Position.Z);
		corners[3] = new Vector3(aabb.Position.X, aabb.End.Y, aabb.End.Z);
		corners[4] = new Vector3(aabb.End.X, aabb.Position.Y, aabb.Position.Z);
		corners[5] = new Vector3(aabb.End.X, aabb.Position.Y, aabb.End.Z);
		corners[6] = new Vector3(aabb.End.X, aabb.End.Y, aabb.Position.Z);
		corners[7] = new Vector3(aabb.End.X, aabb.End.Y, aabb.End.Z);

		// Transform each corner
		for (int i = 0; i < 8; i++)
		{
			corners[i] = transform * corners[i];
		}

		// Find the minimum and maximum points of the transformed box
		Vector3 min = corners[0];
		Vector3 max = corners[0];

		for (int i = 1; i < 8; i++)
		{
			min = min.Min(corners[i]);
			max = max.Max(corners[i]);
		}

		// Create a new AABB from the min and max points
		return new Aabb(min, max - min);
	}
```

I am not a math guy so all I can guess is that there is some order-of-operations issue going on here with the matrix calculations.

I discovered this because I wrote a kitbash importer that successfully imports complex multimesh composite "models" and I manually track the AABB's of these for use in my custom BVH.  For objects that are both rotated and positioned, I noted that transforming the `meshInstance3D.GetAabb()` had the wrong positioning.  It took me a while, but I noticed that my custom OBB's were getting calculated properly, so eventually I tracked it down to this transform `operator *`

### Steps to reproduce

I have a very complex project so it's hard for me to figure out an easy way to provide repo-steps, but it seems that this problem occurs when a model with assets not at the origin is rotated.  

I have attached an export of the model I noticed this problem with.
[quoin_detailed.glb.zip](https://github.com/user-attachments/files/17064653/quoin_detailed.glb.zip)

In the image below: I notice that when I put this model into a scene, godot shows a debug bounds for it that is off, similar to (but not the same) as the issue I have seen.  This leads me to think there's an issue with the godot native transform code also.   

image

### Minimal reproduction project (MRP)

as I'm not a math guy I don't really fully understand the issue, so maybe if you can glance over the current `operator *` implementation and consider my statement, you'll realize that either there's a problem or if I have some workflow issue.

### PR DESCRIPTION
**Pull request by kleonc**
The current C# implemention of `static Aabb operator *(Transform3D transform, Aabb aabb)` (added in #64729) is pretty-much a copy-paste of the core/C++ implementation of `AABB Transform3D::xform(const AABB &p_aabb)`. The issue is that such implemenation uses `Basis[int]` operator and:
- in core/C++ this operator returns Basis row,
- in GDscript/C# this operator returns Basis column (axis).

This discrepancy was not taken into account, hence incorrect calculations. This PR fixes that.

Fixes #97197.

### CODE REVIEW

File: core/math/basis.h [hunk 1]
```diff
@@ -41,11 +41,11 @@ struct [[nodiscard]] Basis {
...
 
-	_FORCE_INLINE_ const Vector3 &operator[](int p_axis) const {
-		return rows[p_axis];
+	_FORCE_INLINE_ const Vector3 &operator[](int p_row) const {
+		return rows[p_row];
 	}
-	_FORCE_INLINE_ Vector3 &operator[](int p_axis) {
-		return rows[p_axis];
+	_FORCE_INLINE_ Vector3 &operator[](int p_row) {
+		return rows[p_row];
```
Comment (kleonc) [inline core/math/basis.h:48]: `p_axis` is confusing in there, AFAICT everywhere else in there axis refers to column.

**Review by aaronfranke — APPROVED** [review]
This is correct. The confusing thing is that (as the PR description states) in Godot's C++ code, the `[]` operator uses rows, while in GDScript and C#, the `[]` operator uses columns. The rename of `p_axis` to `p_row` helps too.

**Comment by akien-mga** [comment]
Thanks!
