### PR TITLE
Fix wrong behavior of Action Map Editor with non QWERTY layouts (Fix #52169)

### LINKED ISSUE #52169: Wrong behavior of Action Editor with AZERTY keyboard
### Godot version

v4.0.dev.custom_build [8e3e9d121]

### System information

Windows 10, Physical AZERTY Keyboard

### Issue description

Something is really weird with key definition in Project Settings > Action Editor.

### Preamble

As far as I understand, there are two ways to define a key for an action : 
- default : if I press Q key, I want the action to be triggered by a Q key on all keyboard layouts.
- physical keycode : if I press Q key, I want the action to  triggered by a key at this position on all keyboard layouts (maybe it won't be an Q on other layouts but it will be the key at this position)

On my keyboard, either with default or physical keycode, it should always be my Q key that should trigger the action (because on my keyboard my Q key as a value of 'Q' and the position of physical key "Q" in my layout)

### Bug description

Let's set an action named "left". Often used key for left action is Q on an AZERTY keyboard (corresponding to the position of A on QWERTY).

I don't check "Use Physical Keycode" (so on all layouts, it should be triggered by the Q key wherever it is)
image
I press Q key the letter A is shown in the windows (so it shows the QWERTY equivalent value).
Showing the QWERTY equivalent here is misleading. We don't care of that here. We always want an Q key even on QWERTY.

Then I start the project and another problem comes :
The key that I have to press to trigger the action is... A ! (not Q)
I have to press a key that I didn't press when assigning key to action.

Maybe, rather than showing misleading QWERTY keys, it should print : 
"value of Q" (by default) or "position of Q" (if «use physical» is checked) 
and in game action should never be triggered by a key that we never pressed (on the same keyboard of course).

### Steps to reproduce

On an AZERTY keyboard, setup an action and assign the key Q without checking "use physical keycode".
You will have to press A during game.

### Minimal reproduction project

[inputs.zip](https://github.com/godotengine/godot/files/7069476/inputs.zip)

In this project, Q key on AZERTY keyboard as been pressed for assigning it to "left" action.

You can see that it's the A key of AZERTY keyboard that trigger the action at runtime.

### PR DESCRIPTION
**Pull request by jmb462**
This PR fixes #52169 issue.

### Issue description:
With non QWERTY keyboard layouts, action keys assigned with non physical checkbox unchecked were wrong (if key position wasn't the same as QWERTY layout).
In game, the key that trigger the action wasn't the pressed key during configuration.

### Identified cause:
Confusion in code between physical_keycode and keycode assignement in action map editor.

### How this PR fixes the issue: **outdated**
Instead of setting physical_keycode or keycode to KEY_NONE to determine if it's a physical key input or not, I've added a boolean in InputEventKey ``is_physical``. keycode variables are no more set to KEY_NONE after beeing assigned. It's more clear and should prevent confusion.
I also change the tests ``InputEventKey.get_keycode()==0`` by ``InputEventKey.is_physical_key()``
I've added an extra info in the checkbock label to inform that key shown in map editor when physical is checked is based on QWERTY layout to clarify the way it works.

### Result:
- Key defined in Action map Editor works correctly in both mode (physical and normal mode) even on non QWERTY layouts.
- Physical checkbox is more informative

input_map_editor

### CODE REVIEW

**Comment by fabriceci** [comment]
I tested it, as currently (#52169), the input system is broken for non-qwerty keyboard.

I can confirm that the PR solves the issue and works now in both mode (normal & physical). **However**, this is a breaking change that will delete registered input if you saved them as physical if you open an "old" project because of the new boolean introduced. As so, if the fix is validated, this should be merged before the alpha at least.

**Review by bruvzg — APPROVED** [review]

**Comment by groud** [comment]
As this PR is modifying InputEventKey which is quite core, we likely need a review from @reduz on it.

File: core/input/input_event.cpp [hunk 1]
```diff
@@ -325,6 +325,13 @@ Key InputEventKey::get_physical_keycode() const {
 	return physical_keycode;
 }
 
+void InputEventKey::set_physical_key(bool p_bool) {
+	physical_key = p_bool;
+}
+bool InputEventKey::is_physical_key() const {
+	return physical_key;
+}
```
Comment (akien-mga) [inline core/input/input_event.cpp:333]: Please keep method definitions separated by a line:
```suggestion
void InputEventKey::set_physical_key(bool p_bool) {
	physical_key = p_bool;
}

bool InputEventKey::is_physical_key() const {
	return physical_key;
}
```

File: editor/action_map_editor.cpp [hunk 2]
```diff
@@ -682,7 +665,7 @@ InputEventConfigurationDialog::InputEventConfigurationDialog() {
 	// Physical Key Checkbox
 
 	physical_key_checkbox = memnew(CheckBox);
-	physical_key_checkbox->set_text(TTR("Use Physical Keycode"));
+	physical_key_checkbox->set_text(TTR("Use Physical Keycode based on QWERTY layout"));
```
Comment (akien-mga) [inline editor/action_map_editor.cpp:668]:
```suggestion
	physical_key_checkbox->set_text(TTR("Use Physical Keycode (US QWERTY Layout"));
```

**Comment by jmb462** [comment]
Thanks for the review @akien-mga . I've applied your changes.

I've also break the tooltip in two lines because it was very long. Hope it's ok : 

https://github.com/jmb462/godot/blob/5264fa1213cfcc270f16b5a2ac6028909077c59f/editor/action_map_editor.cpp#L668-L669

File: editor/action_map_editor.cpp [hunk 3]
```diff
@@ -682,8 +665,8 @@ InputEventConfigurationDialog::InputEventConfigurationDialog() {
 	// Physical Key Checkbox
 
 	physical_key_checkbox = memnew(CheckBox);
-	physical_key_checkbox->set_text(TTR("Use Physical Keycode"));
-	physical_key_checkbox->set_tooltip(TTR("Stores the physical position of the key on the keyboard rather than the keys value. Used for compatibility with non-latin layouts."));
+	physical_key_checkbox->set_text(TTR("Use Physical Keycode (US QWERTY layout)"));
```
Comment (akien-mga) [inline editor/action_map_editor.cpp:668]:
```suggestion
	physical_key_checkbox->set_text(TTR("Use Physical Keycode (US QWERTY Layout)"));
```
This uses "Title Case".

Comment (jmb462) [reply editor/action_map_editor.cpp]: Sorry. I missed it. Done.

**Comment by reduz** [comment]
I don't really think this is more clear, specially because in our context "physical key" means something else (the non remapped key). Additionally, this API can lead to an inconsistent state where user can create an event that is set as a physical key but contains no scancode, which will lead to worse confusion when trying to use the API. Maybe adding `has_keycode()` and `has_unicode()` methods in InputEventKey may make this less confusing.

**Comment by jmb462** [comment]
> ~I don't really think this is more clear, specially because in our context "physical key" means something else (the non remapped key). Additionally, this API can lead to an inconsistent state where user can create an event that is set as a physical key but contains no scancode, which will lead to worse confusion when trying to use the API. Maybe adding `has_keycode()` and `has_unicode()` methods in InputEventKey may make this less confusing.~
> 
> Nevermind, I misunderstood the fix. I still do not understand the need for extra property, leaving aside clarity reasons I don't see how this issue could not be fixed without resorting to that.

Thanks for the review.
OK I can try a less impacting fix. I can fix the main issue whitout modifying the core input cpp files.

But, in that case, a less impacting issue remain. Without keeping both physical and normal keycode (and use one of the two in function of the boolean i've introduce) in the InputEventKey, we should reset action key when switching the "physical" checkbox in Event configuration windows because we loose one of the information. So the key become false (the action doesn't correspond to the key we pressed on keyboard).

Trying to explain it with screenshots : 

image

Then, I press the physical checkbox, it becomes A (Physical) which is wrong. Should be Q (Physical) (but we lost the real physical information)

image

When I pressed the A key and checkbox is already checked, I get Q (Physical) which is correct.

image

If I uncheck the checkbox, it turns to Q. That's wrong. Should be A but we lost the keycode information.

image

So, if we don't keep the 2 keycodes in InputEventKey, I suggest to reset the key when checkbox is checked to force the action to have the correct keycode (physical or not). 

Hope I'm clear. What do you think about that ?

**Comment by akien-mga** [comment]
I think the behavior you show in the screenshots can also be considered working as intended. It doesn't convert your past key press as the equivalent physical keycode, but it makes the registered keycode a physical one. This may or may not be what you want as a user, but it's a fairly niche situation anyway so IMO it's OK.

At least as a developer, I'm not surprised by the behavior - I'm adding the "physical" flag to a past keycode which was registered as the "A" key, so now it's the "physical" A which happens to be "Q" on my AZERTY keyboard.

**Comment by jmb462** [comment]
I don't really agree that setting a key that we never pressed is intended or intuitive.
But if it's ok for you, the fix of initial issue may become quite trivial. I will update the PR soon.

**Comment by Calinou** [comment]
> I think the behavior you show in the screenshots can also be considered working as intended. It doesn't convert your past key press as the equivalent physical keycode, but it makes the registered keycode a physical one. This may or may not be what you want as a user, but it's a fairly niche situation anyway so IMO it's OK.

I think a good compromise would be to display both the key pressed and the key stored. For instance:

"Q (QWERTY layout) - A (on your local keyboard layout)"

**Comment by jmb462** [comment]
@Calinou To do that, either we need to keep both keycode in InputEventKey (which seems to be excluded) or we need a function to convert physical_keycode to layout keycode.

@akien-mga So, to fix the original linked issue #52169, this PR turns in a 2 line deletion.
Seems that the logic of setting the keycode/physical_keycode was inverted (maybe a wrong copy/paste from the toggle checkbox callback).
Furthermore, we don't need to set keycode here at all. InputEventKey already contained it. So we just need to remove the keycode we don't want to use accordling to the physical checkbox state.

That doesn't fix some other strange behavior of this window and I will surely investigate more on this window. But it's out of scope of the initial issue.

**Review by akien-mga — APPROVED** [review]
Let's merge this as a fix for the issue, and see in follow up issues or PRs how to improve the experience further.

**Comment by akien-mga** [comment]
Thanks!
