### PR TITLE
Import scene options is now exposed to GDScript.

### LINKED ISSUE #55911: Import scene options broke
### Godot version

26510f4c90628261aec36ad4d1b40ec87b198d45

### System information

Win 11, Vulkan, Nvidia 3000

### Issue description

Needed to revert https://github.com/V-Sekai/godot/commit/cd2a4990844fac72ae624a51bb797716e69ce2c3 because it caused a regression in godot-vrm.

I tried to fix this in the blender io pr, but the bug fix for this should be separated because it is complicated.

### Steps to reproduce

Any use of the import_scene from gdscript is broken because the extra options map means it is not bound correctly.

### Minimal reproduction project

This isn't really minimal, but I think this bug affects https://github.com/V-Sekai/godot-blender/tree/blender-3.

### PR DESCRIPTION
**Pull request by lyuma**
Implements `options` (map from StringName to Variant) in `_import_scene`, and remove `import_scene_with_other_importer` in order to add a new method exposed to GDScript `do_import_scene`

And analogously for `_import_animation`

CC @fire 

Edited:

Fixes: https://github.com/godotengine/godot/issues/55911

### CODE REVIEW

**Review by fire — APPROVED** [review]
* Looks good to me
* Tested with godot-vrm
* Needed for https://github.com/godotengine/godot/pull/54886

Needs @reduz approval

File: editor/import/resource_importer_scene.cpp [hunk 1]
```diff
@@ -1886,7 +1849,7 @@ Node *ResourceImporterScene::pre_import(const String &p_source_file) {
 	ERR_FAIL_COND_V(!importer.is_valid(), nullptr);
 
 	Error err = OK;
-	Node *scene = importer->import_scene(p_source_file, EditorSceneFormatImporter::IMPORT_ANIMATION | EditorSceneFormatImporter::IMPORT_GENERATE_TANGENT_ARRAYS, 15, nullptr, &err);
+	Node *scene = importer->import_scene(p_source_file, EditorSceneFormatImporter::IMPORT_ANIMATION | EditorSceneFormatImporter::IMPORT_GENERATE_TANGENT_ARRAYS, Map<StringName, Variant>(), 15, nullptr, &err);
```
Comment (fire) [inline editor/import/resource_importer_scene.cpp:1852]: Didn't we change to 30fps?

**Comment by fire** [comment]
The branch needs to be rebased because a previous commit broke the build.

File: doc/classes/EditorSceneFormatImporter.xml [hunk 2]
```diff
@@ -37,31 +37,35 @@
...
 			<argument index="0" name="path" type="String" />
 			<argument index="1" name="flags" type="int" />
-			<argument index="2" name="bake_fps" type="int" />
+			<argument index="2" name="options" type="Dictionary" />
+			<argument index="3" name="bake_fps" type="int" />
 			<description>
 			</description>
 		</method>
-		<method name="import_animation_from_other_importer">
+		<method name="do_import_animation">
```
Comment (reduz) [inline doc/classes/EditorSceneFormatImporter.xml:54]: This method is no longer needed, should be removed

File: doc/classes/EditorSceneFormatImporter.xml [hunk 3]
```diff
@@ -37,31 +37,35 @@
...
 			<argument index="0" name="path" type="String" />
 			<argument index="1" name="flags" type="int" />
-			<argument index="2" name="bake_fps" type="int" />
+			<argument index="2" name="options" type="Dictionary" />
+			<argument index="3" name="bake_fps" type="int" />
 			<description>
 			</description>
 		</method>
-		<method name="import_scene_from_other_importer">
+		<method name="do_import_scene">
```
Comment (reduz) [inline doc/classes/EditorSceneFormatImporter.xml:63]: This method should be removed because its no longer needed.

**Review by reduz — DISMISSED** [review]

File: doc/classes/EditorSceneFormatImporter.xml (hunk 3 above)
Comment (lyuma) [reply doc/classes/EditorSceneFormatImporter.xml]: Done. Note that as a consequence of removing this, it would not be possible to manually invoke the FBX or COLLADA importers from GDScript.

For me, however, since I only ever use glTF, and GLTFDocument has its own `import_scene` (which takes a GLTFState), I don't need this general API.

Given that glTF is the best supported document format, it stands to reason that having GLTFDocument exposed will satisfy most use cases.

**Review by fire — APPROVED** [review]
As discussed in the PR meeting. 

Reduz requested two unused functions to be removed. We reviewed our usages and agreed.

The review comments are now addressed.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

As a note for a future PR idea, it would be useful to write documentation for `EditorSceneFormatImporter` before the 4.0 stable release (and maybe even providing a script template like #56480 does for `VisualShaderNodeCustom`).

**Comment by akien-mga** [comment]
Thanks!
