### PR TITLE
Separate underscore from grapheme punctuation to enable doubleclick and caret jump over snakecase variables in editor

### LINKED ISSUE #46380: Ctrl + Backspace and Ctrl + Left/Right arrows skip underscores for subword navigation in the script editor/TextEdit
**Godot version:** 4.0 e1e52b373

**OS/device including version:** Windows 10

**Issue description:**

Ctrl + backspace and ctrl + left/right arrow only consume alphabats and digits but skips underscores.

ctrl_back

**Steps to reproduce:**
**Minimal reproduction project:**
N/A

### LINKED ISSUE #46456: Regression with Contextual Help lookup
**Godot version:**

4.0 master (75d03f1fbd94efb5f8756e405de03cf271435336)

**OS/device including version:**

macOS 10.14.6

**Issue description:**

When the script editor cursor is on a word with a `_`, the lookup does not used the entire word.

**Steps to reproduce:**

Open the attached project, open *Main.gd*, place the cursor on the `node` part of `find_node` (without selecting anything), then bring up the contextual help.

The docs will be on `node` when it should be on `find_node`.

This works properly in 3.2.4rc. `TextEdit::get_word_under_cursor()` has been re-implemented on master which breaks this behaviour.

**Minimal reproduction project:**

[ContextHelpBug.zip](https://github.com/godotengine/godot/files/6052186/ContextHelpBug.zip)

### PR DESCRIPTION
**Pull request by christinoleo**
Separate underscore from grapheme punctuation to enable doubleclick and caret jump over snakecase variables in editor.

I noticed that due to commit 06ae77a the method "shaped_text_get_word_breaks" now breaks on underscores (aka _ ), which means that a doubleclick on the editor window on a snake_case variable with_underscores_like_this will only select part of it (word by word split by the underscores) instead of the whole variable. The same thing also happens on ctrl+arrows to move the caret right or left. This is different from how godot 3.2, VSCode and other IDEs handle snake_case doubleclick and caret movement.

I mentioned this in 46524 and also patched my fork of godot with this code to have it do what I expected: to select the entire snake_case variables with doubleclick and skip the entire variable on ctrl+arrow by splitting underscores from the GRAPHEME_IS_PUNCTUATION logic, and created a new enum entry GRAPHEME_IS_UNDERSCORE and added this as a parameter to shaped_text_get_word_breaks so that the method can be reused if someone wishes for a different logic.

Hopefully this is good enough for the master godot repository, but I am happy to know if a different solution is better. 

*Bugsquad edit:* Fixes #46456, fixes #46380.

### CODE REVIEW

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/pull/46721.

**Comment by christinoleo** [comment]
@Calinou then would you say that the desired solution is to have an exposed editor setting with a list of what chars should be considered for a word break (aka nonwordcharacter on atom), and replace the punctuation logic with a check from this list in a manner similar to #46721 ?

**Review by bruvzg — COMMENTED** [review]
Seems fine, and better solution than #46691.

#46721 might be useful as an extra feature for the code editor and some special cases, but probably is an overkill for general purpose use.

File: modules/gdnative/text/text_server_gdnative.cpp [hunk 1]
```diff
@@ -550,15 +550,15 @@ Vector<Vector2i> TextServerGDNative::shaped_text_get_line_breaks(RID p_shaped, f
 	}
 }
 
-Vector<Vector2i> TextServerGDNative::shaped_text_get_word_breaks(RID p_shaped) const {
+Vector<Vector2i> TextServerGDNative::shaped_text_get_word_breaks(RID p_shaped, int p_grapheme_flags) const {
 	ERR_FAIL_COND_V(interface == nullptr, Vector<Vector2i>());
 	if (interface->shaped_text_get_word_breaks != nullptr) {
 		godot_packed_vector2i_array result = interface->shaped_text_get_word_breaks(data, (godot_rid *)&p_shaped);
```
[the remark this answers is not in the document]
Comment (christinoleo) [reply modules/gdnative/text/text_server_gdnative.cpp]: Cool. I force pushed to update the commit. I wasn't sure before if I should change or not due to backwards compatibility, but it is Godot 4.0 so these changes are to be expected.

**Comment by BastiaanOlij** [comment]
owh yes please :)

File: modules/text_server_adv/text_server_adv.cpp [hunk 2]
```diff
@@ -1728,7 +1728,10 @@ bool TextServerAdvanced::shaped_text_update_breaks(RID p_shaped) {
 			if (is_whitespace(c)) {
 				sd_glyphs[i].flags |= GRAPHEME_IS_SPACE;
 			}
-			if (u_ispunct(c)) {
+			if (c == 0x005F) {
+				sd_glyphs[i].flags |= GRAPHEME_IS_UNDERSCORE;
```
Comment (BastiaanOlij) [inline modules/text_server_adv/text_server_adv.cpp:1732]: nitpicking but seeing the other checks, should we have an is_underscore(c) function here that checks this? Probably overkill but I can see there may be a reason alternatives to underscores are added at some point.

Comment (akien-mga) [reply modules/text_server_adv/text_server_adv.cpp:1732]: It seems there is one in `text_server_fb` so it should likely be added here too for consistency.

File: servers/text_server.h [hunk 3]
```diff
@@ -79,7 +79,8 @@ class TextServer : public Object {
 		GRAPHEME_IS_BREAK_SOFT = 1 << 5, // Is line break (optional break, e.g. space).
 		GRAPHEME_IS_TAB = 1 << 6, // Is tab or vertical tab.
 		GRAPHEME_IS_ELONGATION = 1 << 7, // Elongation (e.g. kashida), glyph can be duplicated or truncated to fit line to width.
-		GRAPHEME_IS_PUNCTUATION = 1 << 8 // Punctuation (can be used as word break, but not line break or justifiction).
+		GRAPHEME_IS_PUNCTUATION = 1 << 8, // Punctuation, except underscore (can be used as word break, but not line break or justifiction).
+		GRAPHEME_IS_UNDERSCORE = 1 << 9 // Underscore (can be used as word break).
```
Comment (akien-mga) [inline servers/text_server.h:83]: Nitpick, but I'd add a trailing comma so that future additions don't create additional diff on the previous last entry.

**Review by bruvzg — APPROVED** [review]

File: modules/text_server_adv/text_server_adv.cpp (hunk 2 above)
Comment (christinoleo) [reply modules/text_server_adv/text_server_adv.cpp:1732]: ah, thanks, I didn't see that there was a method for this check

**Comment by christinoleo** [comment]
Thanks for the reviews! I have updated the code to include them.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
