### PR TITLE
Expose PrimitiveMesh's `request_update` method

### LINKED ISSUE #89067: MeshInstance2D does not update mesh when using custom PrimitiveMesh
### Tested versions

Found in: v4.2.1.stable.official [b09f793f5]
Reproducible in:
- v4.3.dev4.official [df78c0636]
- v4.2.2.rc1.official [c7fb0645a]
- v4.1.3.stable.official [f06b6836a]
- v4.0.4.stable.official [fc0b241c9]

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4633) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 Threads)

### Issue description

When using a custom `PrimitiveMesh` type via GDScript, changing its parameters in the editor does not update the actual mesh until you update another built-in property.

Expected behaviour: Changing the parameters should update the mesh, as with the built-in `PrimitiveMesh` types.

Here is the custom PrimitiveMesh type, for reference:
```gdscript
@tool
class_name CircleMesh
extends PrimitiveMesh

@export var radius := 1.0:
	set(value):
		if radius != value:
			radius = value
			emit_changed()

@export var vertex_count := 32:
	set(value):
		if vertex_count != value:
			vertex_count = value
			emit_changed()

func _create_mesh_array() -> Array:
	var vertices := PackedVector3Array()
	vertices.append(Vector3.ZERO)
	
	var uvs := PackedVector2Array()
	uvs.append(Vector2.ONE * 0.5)
	
	for i in range(0, vertex_count):
		var theta = (2.0 * PI / vertex_count) * i
		var dir = Vector3(sin(theta), cos(theta), 0.0)
		vertices.append(dir * radius)
		uvs.append(Vector2(dir.x, dir.y))
	
	var indices := PackedInt32Array()
	for i in range(0, vertex_count):
		indices.append(i + 1)
		indices.append(i + 2)
		indices.append(0)
	
	indices.append(vertex_count)
	indices.append(1)
	indices.append(0)
	
	var arrays = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = vertices
	arrays[Mesh.ARRAY_TEX_UV] = uvs
	arrays[Mesh.ARRAY_INDEX] = indices
	return arrays
```

### Steps to reproduce

- Open the attached project
- Open `example.tscn`, and select the root node
- Change either "Radius" or "Vertex Count" in the inspector
- The mesh in the scene does not change until you change some other built-in property of the `PrimitiveMesh`

### Minimal reproduction project (MRP)

[PrimitiveMesh Demo.zip](https://github.com/godotengine/godot/files/14465575/PrimitiveMesh.Demo.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/89067

### CODE REVIEW

File: scene/resources/3d/primitive_meshes.cpp [hunk 1]
```diff
@@ -249,6 +249,8 @@ void PrimitiveMesh::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_uv2_padding", "uv2_padding"), &PrimitiveMesh::set_uv2_padding);
 	ClassDB::bind_method(D_METHOD("get_uv2_padding"), &PrimitiveMesh::get_uv2_padding);
 
+	ClassDB::bind_method(D_METHOD("_request_update"), &PrimitiveMesh::_request_update);
```
Comment (bruvzg) [inline scene/resources/3d/primitive_meshes.cpp:252]: If it's exposed to be user accessible, it probably should be `request_update` without underline. Also, it's already being exposed in the subclass `TextMesh` (should be removed, or it will cause conflict), but it was exposed only to allow `call_deffered` (this case can be replaced with `callable_mp`).

Comment (clayjohn) [reply scene/resources/3d/primitive_meshes.cpp:252]: If we un-expose `_request_update()` from TextMesh will it break binary compatibility for extensions?

Comment (akien-mga) [reply scene/resources/3d/primitive_meshes.cpp:252]: It doesn't seem to be exposed in https://raw.githubusercontent.com/godotengine/godot-cpp/master/gdextension/extension_api.json

I believe we explicitly skip non virtual methods prefixed with underscore.

Comment (jsjtxietian) [reply scene/resources/3d/primitive_meshes.cpp:252]: > but it was exposed only to allow `call_deffered` (this case can be replaced with `callable_mp`).

It looks like `callable_mp`  can not use parent class's protected method, should I make `_request_update` public?

Comment (bruvzg) [reply scene/resources/3d/primitive_meshes.cpp:252]: > It looks like callable_mp can not use parent class's protected method, should I make _request_update public?

Probably, it's also make sense to make it public, if it's exposed. Removing `_` should not break compatibility, since `_` methods are considered private and not fully exposed to GDExtension.

Comment (akien-mga) [reply scene/resources/3d/primitive_meshes.cpp:252]: For consistency, both the exposed method and the now public C++ one should be renamed `request_update` (no underscore).

**Comment by jsjtxietian** [comment]
Looks like the function under `callable_mp`, `create_custom_callable_function_pointer` uses template as instance type and function type, so it can't deduce the parent/child relation and I have to use `static_cast` to cast the type and make it compile.

**Review by akien-mga — APPROVED** [review]

File: doc/classes/PrimitiveMesh.xml [hunk 2]
```diff
@@ -33,6 +33,12 @@
 				[/codeblocks]
 			</description>
 		</method>
+		<method name="request_update">
+			<return type="void" />
+			<description>
+				Request this primitive mesh to update based on its properties.
```
Comment (AThousandShips) [inline doc/classes/PrimitiveMesh.xml:39]:
```suggestion
				Request an update of this primitive mesh based on its properties.
```

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by jsjtxietian** [comment]
I just found out this is my 100th commit to godot repo, thanks for all of your help along the way :)
