### PR TITLE
Add `NOTIFICATION_PREDELETE_CLEANUP` notification to fix C# `Dispose()`

### LINKED ISSUE #82279: C#: Script methods bound to `tree_exited` / `_ExitTree()` can't be found.
### Godot version

v4.2.dev5.mono.official [e3e2528ba]

### System information

Windows 11

### Issue description

After I upgraded my Godot version from 4.2dev3 to 4.2dev5 I encountered the issue that the `tree_exited` signal fires on nodes that have my custom C# script attached but it somehow already "forgot" that the Node actually had my script attached. So I get the error `emit_signalp: Error calling from signal 'tree_exited' to callable: 'Node2D::_on_tree_exited': Method not found.
  <C++ Source>   core/object/object.cpp:1125 @ emit_signalp()`

The same problem leads to the fact that my `public override void _ExitTree()` method in my script does not even run at all.

### Steps to reproduce

* Create a node with a C# script attached to it that implements either `_ExitTree()` or where the scene is connected to the `tree_exited` signal (calling a method on the same scene)
* Put debug prints into the signal-connected method or the `_ExitTree()` one
* Create a wrapper scene which contains the first scene
* Let the node of the first scene get removed by calling `QueueFree()` when clicking a button or pressing any key
* Get errors (in signal case) or no printing at all (in `_ExitTree()` case)

### Minimal reproduction project

Start the project and click the button. Notice that we don't get the log message from `_ExitTree()` and also an error from the `tree_exited` signal connection.
[tree-exit-bug.zip](https://github.com/godotengine/godot/files/12710513/tree-exit-bug.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
New notification sent after `NOTIFICATION_PREDELETE` to let Objects cleanup at the very end, it should be the last notification sent.

 - This is one of the options I suggested in https://github.com/godotengine/godot/pull/83262#issuecomment-1766722392. I think it's the easiest and safest thing to do and avoids having to revert https://github.com/godotengine/godot/pull/78634.

`NOTIFICATION_PREDELETE_CLEANUP` is used by C# scripts to cleanup (calls `Dispose()`), instead of `NOTIFICATION_PREDELETE`. This ensures that it's the last thing we do, after disposing we can't do anything else with the C# instances.

 - Fixes https://github.com/godotengine/godot/issues/82279.
 - Supersedes https://github.com/godotengine/godot/pull/83262.

### CODE REVIEW

File: core/object/object.h [hunk 1]
```diff
@@ -801,6 +801,8 @@ class Object {
 		NOTIFICATION_POSTINITIALIZE = 0,
 		NOTIFICATION_PREDELETE = 1,
 		NOTIFICATION_EXTENSION_RELOADED = 2,
+		// Internal notification to send after NOTIFICATION_PREDELETE, not bound to scripting.
+		NOTIFICATION_PREDELETE_CLEANUP = 3,
```
Comment (AThousandShips) [inline core/object/object.h:805]: This needs to be clearly reserved so future notifications don't use it, especially if we use a system based on registered values to track overlap

Comment (raulsntos) [reply core/object/object.h:805]: It seems we use different _magnitudes_[^1] to avoid overlap (e.g.: the Node notifications are 1X, CanvasItem notifications are 3X, Control/Node3D notifications are 4X, Window notifications are 10XX). But I agree it can be error prone.

[^1]: Not sure if _magnitude_ is the right word.

**Review by akien-mga — APPROVED** [review]
Discussed with @reduz, seems good as a stopgap measure for the C# predelete, until we can have a more robust system.

Then we would remove that new notification - so PR reviewers should be aware of not letting it be exposed/used more internally, unless there's a very clear use case validated by the core team.

**Comment by akien-mga** [comment]
Thanks!
