### PR TITLE
Fix mobile renderer RID leaks

### LINKED ISSUE #89182: Vulkan Mobile leaks RIDs on exit even in empty project (StorageBuffer, Framebuffer, Texture)
### Tested versions

- Reproducible in 4.3.dev (f9ebd84b5ace8d0e6a9c43c3403ecd9a4bcb132e), 4.3-dev1, 4.2.1-stable (didn't test earlier)

### System information

Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) () - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

When exiting the editor after editing a Vulkan Mobile project (empty new project included), the following leaks are reported:
```
WARNING: 1 RID of type "StorageBuffer" was leaked.
     at: _free_rids (./servers/rendering/rendering_device.cpp:5191)
 - RID:624587029086219
WARNING: 1 RID of type "Framebuffer" was leaked.
     at: _free_rids (./servers/rendering/rendering_device.cpp:5191)
 - RID:625025115750887
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (./servers/rendering/rendering_device.cpp:5344)
 - RID:625020820790930
 - RID:625033705692822
 - RID:625046590594712
 - RID:625059475496602
```

Running a 3D scene doesn't seem to trigger that leak, so it seems to be specific to the editor, possibly the default preview environment?

CC @godotengine/rendering 

### Steps to reproduce

- Create new project with Vulkan Mobile rendering method
- Open it from a terminal
- Close and see the leak report

### Minimal reproduction project (MRP)

Empty Vulkan Mobile project

### PR DESCRIPTION
**Pull request by sullyscience**
Update render_forward_mobile destructor to include instance buffers. 
Update render_scene_buffers_rd cleanup to include weight buffers / blur textures.

Fixes: #89182

### CODE REVIEW

File: servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp [hunk 1]
```diff
@@ -128,6 +128,13 @@ void RenderSceneBuffersRD::cleanup() {
 		free_named_texture(E.value);
 	}
 	named_textures.clear();
+
+	// Clear weight_buffer / blur textures
+	for (WeightBuffers weight_buffer : weight_buffers) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp:133]:
```suggestion
	for (const WeightBuffers &weight_buffer : weight_buffers) {
```

File: servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp [hunk 2]
```diff
@@ -128,6 +128,13 @@ void RenderSceneBuffersRD::cleanup() {
 		free_named_texture(E.value);
 	}
 	named_textures.clear();
+
+	// Clear weight_buffer / blur textures
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp:132]:
```suggestion
	// Clear weight_buffer / blur textures.
```

File: servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp [hunk 3]
```diff
@@ -128,6 +128,13 @@ void RenderSceneBuffersRD::cleanup() {
...
+	for (WeightBuffers weight_buffer : weight_buffers) {
+		if (weight_buffer.weight != RID()) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp:134]:
```suggestion
		if (weight_buffer.weight.is_valid()) {
```

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 4]
```diff
@@ -2835,6 +2835,11 @@ RenderForwardMobile::~RenderForwardMobile() {
 		for (const RID &rid : scene_state.uniform_buffers) {
 			RD::get_singleton()->free(rid);
 		}
+		for (uint32_t i = 0; i < RENDER_LIST_MAX; i++) {
+			if (scene_state.instance_buffer[i] != RID()) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:2839]:
```suggestion
			if (scene_state.instance_buffer[i].is_valid()) {
```

**Review by clayjohn — APPROVED** [review]
Great work! Thank you for fixing this

Code changes look good to me, given the nature of the changes, I trust that they are good given that they are passing CI

This should be an easy cherrypick too

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp (hunk 4 above)
Comment (BalmundSM) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Seeing as this part is from "render_forward_clustered.cpp", will you be changing that file also?

Comment (sullyscience) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Looks like there's about 90 instances where we could move to `is_valid` or `is_null`. I could take that on in a separate task if it'd be useful.

**Review by Geometror — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
