### PR TITLE
Fix all categories unfold when one key binding is changed

### LINKED ISSUE #15726: All categories unfold when one key binding is changed
Godot 3.0 master 109242c011255757c981f634a33f59268a113f67

I tried deleting one of the shortcuts, and to find it I decided to fold categories one by one until I find the one I want. Then I found the shortcut, and deleted it. Doing so caused the window to update and I lost the view on the shortcuts I was watching. Turns out my action unfolded every category.

It would be better if that didn't happen^^

https://www.youtube.com/watch?v=dFHHx-0rG3A

### PR DESCRIPTION
**Pull request by Essojadojef**
Fixes #15726.

This is my first pull request, so tell me if I did something wrong.

### CODE REVIEW

File: editor/settings_config_dialog.cpp [hunk 1]
```diff
@@ -199,6 +199,14 @@ void EditorSettingsDialog::_update_icons() {
 
 void EditorSettingsDialog::_update_shortcuts() {
 
+	Map<String, bool> collapsed;
+
+	if ( shortcuts->get_root() && shortcuts->get_root()->get_children() ) {
```
Comment (Noshyaar) [inline editor/settings_config_dialog.cpp]: There are extra space after `(` and before `)` of `if` which fail the clang-format check. Other than that, the change looks fine. Thanks! :)

**Comment by Noshyaar** [comment]
Could you please squash commits together? ([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request))

**Comment by hpvb** [comment]
Cherry picked into 3.0.3
