### PR TITLE
Fix audio name doesn't appear in exports of child classes of `AudioStream`

### LINKED ISSUE #12613: Few elements in @exported Array should have visible name
### Describe the project you are working on

Learning Godot

### Describe the problem or limitation you are having in your project

When I add couple of AudioStreams to Arrray there is only note icon and audio wave visible. It's hard to know which audio is which. Name is visible only after hovering over.

Godot:

Image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

We should show file name. For example Unity does this and it is very easy to know which audio files are used here.

Image

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add names. Maybe there are other similar resources with similar problem in array :)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think this should not be addon. It is basic functionality.

### Is there a reason why this should be core and not an add-on in the asset library?

It is basic UX improvement.

### PR DESCRIPTION
**Pull request by ydeltastar**
- Fixes: https://github.com/godotengine/godot-proposals/issues/12613

### CODE REVIEW

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -3380,7 +3380,7 @@ void EditorPropertyResource::setup(Object *p_object, const String &p_path, const
 		shader_picker->set_edited_material(Object::cast_to<ShaderMaterial>(p_object));
 		resource_picker = shader_picker;
 		connect(SceneStringName(ready), callable_mp(this, &EditorPropertyResource::_update_preferred_shader));
-	} else if (p_base_type == "AudioStream") {
+	} else if (ClassDB::is_parent_class(p_base_type, "AudioStream")) {
```
Comment (akien-mga) [inline editor/editor_properties.cpp:3383]: Is there a similar issue with Shader and Script derived types above?

Comment (ydeltastar) [reply editor/editor_properties.cpp:3383]: These refer to specific properties, the `script` property in every node and the `shader` in every `ShaderMaterial`, so the type is always correct. Meanwhile, the audio stream affects any property.

Not sure why the special case handling just for them, maybe something to do with another editor feature, so I changed just what is relevant for the issue.

Comment (KoBeWi) [reply editor/editor_properties.cpp:3383]: I don't see any reason why Scripts and Shaders should be restricted to specific property. They can be changed too.

Comment (ydeltastar) [reply editor/editor_properties.cpp:3383]: If this handles all properties, it will open the "Attach Node Script" dialogue when you have a second `script2` and select "New Script" or "Extend Script". This dialogue only makes sense for `script`, so the special resource picker.
It's probably something similar for `shader`.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
