### PR TITLE
Don't save project on startup in no window mode

### LINKED ISSUE #45958: 'The following files are newer on disk' dialog everytime project run
**Godot version:**
Godot_v3.2.4-rc2_mono_win64

**OS/device including version:**
Windows10 x64 Nvidia 1650

**Issue description:**
When running project a dialog appears saying:

please confirm.

The following files are newer on disk. Which action should be taken?

project.godot

Resave Reload Cancel

Here is an image link: https://pasteboard.co/JOb0ik2.png
Project.godot is the file listed (dosen't appear on screenshot for some reason)

This hasn't happened before. It only happens on one mono project. Even RC1 works as expected.

**Steps to reproduce:**
Load project, run

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by KoBeWi**
Resolves #45958 

For some reason I can't run the editor in no window mode, so I couldn't test it.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -606,8 +606,10 @@ void EditorNode::_notification(int p_what) {
 				_editor_select(EDITOR_3D);
 			}
 
-			// Save the project after opening to mark it as last modified.
-			ProjectSettings::get_singleton()->save();
+			// Save the project after opening to mark it as last modified, except in headless mode.
```
Comment (Calinou) [inline editor/editor_node.cpp:609]: It seems a bit weird that we're saving the project just to mark it as last modified in the project manager. I would prefer not saving the project for this reason, even if it means changing the project manager behavior to actually show the last *modified* project first instead of the last *opened*.

Comment (akien-mga) [reply editor/editor_node.cpp:609]: Yeah while I understand where user requests are coming from, IMO it was a pretty bad hack to save the project without any modification just for this purpose - and as we see it's not without drawbacks.

If we want a "last opened" sorting, this should be achieved through metadata in the editor settings dir, not by tweaking "last modified" to cover both.

Comment (KoBeWi) [reply editor/editor_node.cpp:609]: Well, we could store the opening time somewhere in the editor data, but IMO it's not really such a big problem

Comment (mhilbrunner) [reply editor/editor_node.cpp:609]: I'm in favor of removing this and just using *last modified*.

Comment (aaronfranke) [reply editor/editor_node.cpp:609]: IIRC the last time we removed the "save on open" behavior it resulted in a lot of things not working as expected, along with the obvious of the project not being marked as modified. I would prefer leaving this functionality in personally.

Comment (KoBeWi) [reply editor/editor_node.cpp:609]: Yep, there is a bunch of stuff that does some changes at startup (like removing invalid plugins etc.) and it doesn't save the project, it relies on the autosaving. So if we were to remove that, we have to make sure that all these startup modifications are saved.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -606,8 +606,10 @@ void EditorNode::_notification(int p_what) {
...
+			if (!OS::get_singleton()->is_no_window_mode_enabled()) {
```
Comment (akien-mga) [inline editor/editor_node.cpp:610]: I don't think this will be sufficient when running with the headless display server without the (now mostly redundant) `--no-window` flag.

Comment (akien-mga) [reply editor/editor_node.cpp:610]: Case in point, we removed the `--no-window` flag in #51216 :)

Checking `OS::get_singleton()->can_draw()` might be better. (CC @Faless)

Comment (akien-mga) [reply editor/editor_node.cpp]: > _Edit:_ That's for `3.x`, in `master` it would likely be `DisplayServer::get_singleton()->window_can_draw()`.

Pushed an amend with that.

**Review by akien-mga — APPROVED** [review]
Tested, it works fine.

File: editor/editor_node.cpp (hunk 2 above)
Comment (akien-mga) [reply editor/editor_node.cpp]: I tested on `3.x` and there the no window mode doesn't set `can_draw()` to false, so we need to check both:
```
OS::get_singleton()->can_draw() && !OS::get_singleton()->is_no_window_mode_enabled()
```
(to exclude both server and --no-window desktop builds)

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
