### PR TITLE
Check if scale/offset values are provided in gltf `KHR_texture_transform`

### LINKED ISSUE #112485: GLB import: "Bug: Dictionary::operator[] used when there was no value for the given key, please report."
### Tested versions

- Reproducible on Commit cb3af5afff15669a684ba4f04b9aa5c70dfd09ad, build with .Net & precision=double

### System information

Godot v4.6.dev.mono.double (cb3af5afff15669a684ba4f04b9aa5c70dfd09ad) - Ubuntu 25.10 25.10 on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 5070 Ti (nvidia; 580.95.05) - Intel(R) Core(TM) i9-14900KF (32 threads) - 62.57 GiB memory

### Issue description

When importing .glb files the Editor shows following error:
ERROR: Bug: Dictionary::operator[] used when there was no value for the given key, please report.
   at: operator[] (core/variant/dictionary.cpp:136)

The model is displayed correctly, but this message appears.

### Steps to reproduce

Simply import or re-import a .glb file. This also happens when exporting in --headless mode.

### Minimal reproduction project (MRP)

[Bug.zip](https://github.com/user-attachments/files/23403177/Bug.zip)

### PR DESCRIPTION
**Pull request by aaronp64**
Update `GLTFDocument` to check if scale/offset values exist when reading KHR_texture_transform extension

Fixes #112485

### CODE REVIEW

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -3209,16 +3209,22 @@ void GLTFDocument::_set_texture_transform_uv1(const Dictionary &p_dict, Ref<Base
 		if (extensions.has("KHR_texture_transform")) {
 			if (p_material.is_valid()) {
 				const Dictionary &texture_transform = extensions["KHR_texture_transform"];
-				const Array &offset_arr = texture_transform["offset"];
-				if (offset_arr.size() == 2) {
-					const Vector3 offset_vector3 = Vector3(offset_arr[0], offset_arr[1], 0.0f);
-					p_material->set_uv1_offset(offset_vector3);
+				const Variant *offset_value = texture_transform.getptr("offset");
```
Comment (aaronfranke) [inline modules/gltf/gltf_document.cpp]: I would prefer wrapping in `if (texture_transform.has("offset")) {` instead of doing this.

But also, we should remove the `&`. This is a converted value, it is misleading to call its storage a reference.

**Review by aaronfranke — APPROVED** [review]
This fix is correct.

**Review by fire — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
