### PR TITLE
Fix PopupMenu's which are not closed after a recent commit

### LINKED ISSUE #44953: Popup menus do not close when other is opened (DisplayServer regression)
**Godot version:**
4.0 master cdfcf68

**OS/device including version:**
Win 10

**Issue description:**
Popup menus do not close when other is opened.
popup_menu_bug_1
popup_menu_bug_2

This seems to affect all popup menus (not just those created by MenuButtons) since you can have multiple context menus open as well.
image

However I also get this weird issue where if I right click in FileStystem and then right clicking in the Scene Tree, the filesystem context menu goes blank:
image

**Steps to reproduce:**
Open menus

### PR DESCRIPTION
**Pull request by Chaosus**
Fix a regression after #44299 (while still preserve warning suppression)
Fix https://github.com/godotengine/godot/issues/44953

### CODE REVIEW

**Comment by akien-mga** [comment]
For review, here's the combined diff of #44299 and this PR:
```diff
diff --git a/platform/windows/display_server_windows.cpp b/platform/windows/display_server_windows.cpp
index db3d697e05..693e3f32d5 100644
--- a/platform/windows/display_server_windows.cpp
+++ b/platform/windows/display_server_windows.cpp
@@ -1876,27 +1876,34 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 
 			break;
 		}
-		case WM_ACTIVATE: // Watch For Window Activate Message
-		{
-			windows[window_id].minimized = HIWORD(wParam) != 0;
-
-			if (LOWORD(wParam) == WA_ACTIVE || LOWORD(wParam) == WA_CLICKACTIVE) {
-				_send_window_event(windows[window_id], WINDOW_EVENT_FOCUS_IN);
-				windows[window_id].window_focused = true;
-				alt_mem = false;
-				control_mem = false;
-				shift_mem = false;
-			} else { // WM_INACTIVE
-				Input::get_singleton()->release_pressed_events();
-				_send_window_event(windows[window_id], WINDOW_EVENT_FOCUS_OUT);
-				windows[window_id].window_focused = false;
-				alt_mem = false;
-			};
-
-			if ((OS::get_singleton()->get_current_tablet_driver() == "wintab") && wintab_available && windows[window_id].wtctx) {
-				wintab_WTEnable(windows[window_id].wtctx, GET_WM_ACTIVATE_STATE(wParam, lParam));
+		case WM_ACTIVATE: { // Watch For Window Activate Message
+
+			if (!windows[window_id].window_focused) {
+				windows[window_id].minimized = HIWORD(wParam) != 0;
+
+				if (LOWORD(wParam) == WA_ACTIVE || LOWORD(wParam) == WA_CLICKACTIVE) {
+					_send_window_event(windows[window_id], WINDOW_EVENT_FOCUS_IN);
+					windows[window_id].window_focused = true;
+					alt_mem = false;
+					control_mem = false;
+					shift_mem = false;
+				} else { // WM_INACTIVE
+					Input::get_singleton()->release_pressed_events();
+					_send_window_event(windows[window_id], WINDOW_EVENT_FOCUS_OUT);
+					windows[window_id].window_focused = false;
+					alt_mem = false;
+				};
+
+				if ((OS::get_singleton()->get_current_tablet_driver() == "wintab") && wintab_available && windows[window_id].wtctx) {
+					wintab_WTEnable(windows[window_id].wtctx, GET_WM_ACTIVATE_STATE(wParam, lParam));
+				}
+			} else {
+				saved_wparam = wParam;
+				saved_lparam = lParam;
+				saved_window_id = window_id;
+				// Run a timer to prevent event catching warning if the focused window is closing.
+				focus_timer_id = SetTimer(windows[window_id].hWnd, 2, USER_TIMER_MINIMUM, (TIMERPROC) nullptr);
 			}
-
 			return 0; // Return  To The Message Loop
 		}
 		case WM_GETMINMAXINFO: {
@@ -1937,6 +1944,9 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 
 		case WM_CLOSE: // Did We Receive A Close Message?
 		{
+			if (focus_timer_id != 0U) {
+				KillTimer(windows[window_id].hWnd, focus_timer_id);
+			}
 			_send_window_event(windows[window_id], WINDOW_EVENT_CLOSE_REQUEST);
 
 			return 0; // Jump Back
@@ -2630,6 +2640,28 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 				if (!Main::is_iterating()) {
 					Main::iteration();
 				}
+			} else if (wParam == focus_timer_id) {
+				windows[saved_window_id].minimized = HIWORD(saved_wparam) != 0;
+
+				if (LOWORD(saved_wparam) == WA_ACTIVE || LOWORD(saved_wparam) == WA_CLICKACTIVE) {
+					_send_window_event(windows[saved_window_id], WINDOW_EVENT_FOCUS_IN);
+					windows[saved_window_id].window_focused = true;
+					alt_mem = false;
+					control_mem = false;
+					shift_mem = false;
+				} else { // WM_INACTIVE
+					Input::get_singleton()->release_pressed_events();
+					_send_window_event(windows[saved_window_id], WINDOW_EVENT_FOCUS_OUT);
+					windows[saved_window_id].window_focused = false;
+					alt_mem = false;
+				};
+
+				if ((OS::get_singleton()->get_current_tablet_driver() == "wintab") && wintab_available && windows[saved_window_id].wtctx) {
+					wintab_WTEnable(windows[saved_window_id].wtctx, GET_WM_ACTIVATE_STATE(saved_wparam, saved_lparam));
+				}
+
+				KillTimer(windows[saved_window_id].hWnd, focus_timer_id);
+				focus_timer_id = 0U;
 			}
 		} break;
 
@@ -3213,8 +3245,6 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
 	}
 #endif
 
-	move_timer_id = 1;
-
 	//set_ime_active(false);
 
 	if (!OS::get_singleton()->is_in_low_processor_usage_mode()) {
diff --git a/platform/windows/display_server_windows.h b/platform/windows/display_server_windows.h
index 89dd927304..88ea1fbb5b 100644
--- a/platform/windows/display_server_windows.h
+++ b/platform/windows/display_server_windows.h
@@ -387,7 +387,8 @@ private:
 
 	WindowID last_focused_window = INVALID_WINDOW_ID;
 
-	uint32_t move_timer_id;
+	uint32_t move_timer_id = 0U;
+	uint32_t focus_timer_id = 0U;
 
 	HCURSOR hCursor;
 
@@ -408,6 +409,10 @@ private:
 	bool in_dispatch_input_event = false;
 	bool console_visible = false;
 
+	WPARAM saved_wparam;
+	LPARAM saved_lparam;
+	WindowID saved_window_id;
+
 	WNDCLASSEXW wc;
 
 	HCURSOR cursors[CURSOR_MAX] = { nullptr };
```

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -1877,11 +1877,33 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
 			break;
 		}
 		case WM_ACTIVATE: { // Watch For Window Activate Message
-			saved_wparam = wParam;
-			saved_lparam = lParam;
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:1880]: This adds an empty line at the start of the code block.

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -1877,11 +1877,16 @@ LRESULT DisplayServerWindows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARA
...
 
-			// Run a timer to prevent event catching warning if the window is closing.
-			focus_timer_id = SetTimer(windows[window_id].hWnd, 2, USER_TIMER_MINIMUM, (TIMERPROC) nullptr);
+			if (!windows[window_id].window_focused) {
+				_process_activate_event(window_id, wParam, lParam);
+			} else {
+				saved_wparam = wParam;
+				saved_lparam = lParam;
+				saved_window_id = window_id;
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:1885]: Why this is necessary? Time should be associated with the window and have valid `window_id`, or is it redirected to the parent window somehow?

Also, `save_xparam` and `timer_id` probably should be in the window data, instead of global (in case WM_ACTIVATE is received by multiple windows before WM_TIMER is call).

File: platform/windows/display_server_windows.cpp (hunk 1 above)
Comment (Chaosus) [reply platform/windows/display_server_windows.cpp]: Fixed

**Review by bruvzg — COMMENTED** [review]
I'm not sure how #44299 is preventing popups from closing, or why these changes should fix it.

File: platform/windows/display_server_windows.cpp (hunk 2 above)
Comment (Chaosus) [reply platform/windows/display_server_windows.cpp]: Done, I think. I preserve `saved_window_id` but renamed it to `last_activated_window` cuz popups still overlap each other without it. Added params and timers to window data as you said.

**Comment by Chaosus** [comment]
> I'm not sure how #44299 is preventing popups from closing, or why these changes should fix it.

@bruvzg Well, after this PR they behaves correctly:
fix

**Review by bruvzg — APPROVED** [review]
