### PR TITLE
Fix Wrong Shape Offsets in Tileset

### LINKED ISSUE #25610: Autotile ATLAS_TILE shape offset only applies to first tile
**Godot version:** Godot 3.1-beta11(64bit,Linux)
**OS/device including version:** Linux Mint 19.1(Ubuntu 18.04)
**Issue description:**
The shape_offset is only applied to the first Tile of an AUTO_TILE/ATLAS_TILE and none of the following tiles.

**Steps to reproduce:**
Create a TileMap with a TileSet in it that has an ATLAS_TILE with a shape_offset and multiple tiles(each with collision). Then place the different tiles and look at it with visible collisions.

**Minimal reproduction project:**
[autotile_shape_offset_bug.zip](https://github.com/godotengine/godot/files/2828980/autotile_shape_offset_bug.zip)

EDITED: I looked a bit deeper into it and my first assumption wasn't right. Corrected the issue above.

### LINKED ISSUE #30994: Shape offset (collision) misplaced
**Godot version:**
v3.2.dev.calinou.9da24f7e3 AND Godot 3.1 Stable

**OS/device including version:**
Windoes 10, issue persists on different computers

**Issue description:**
The collision shape is mislplaced when using texture offset, even when piared with shape offset to account for it. Not all of the texture's collision shapes are misplaced, just some, for whatever reason.

**Steps to reproduce:**

Here's a screenshot explaining the problem. As you see, the collision shapes are correctly placed, paired with the shape offset

Capture

### PR DESCRIPTION
**Pull request by codecustard**
Closes #30994 and closes #25610.

When modifying the properties of a tileset in the editor, some properties only apply to the first tile (such as the shape offset).

This change resolves that issue by traversing the changes to all of the shapes in the tileset instead of the first one.

### CODE REVIEW

File: scene/resources/tile_set.cpp [hunk 1]
```diff
@@ -149,15 +149,19 @@ bool TileSet::_set(const StringName &p_name, const Variant &p_value) {
 		}
 	} else if (what == "shape")
 		tile_set_shape(id, 0, p_value);
```
Comment (qarmin) [inline scene/resources/tile_set.cpp]: This else if should also have a brackets for consistence.

**Comment by Lodugh** [comment]
Thanks a lot! This also fixes #25610 , while #30994 was a duplicate of it.

File: scene/resources/tile_set.cpp (hunk 1 above)
Comment (sparkart) [reply scene/resources/tile_set.cpp]: Are you saying that the line should have the for loop as well, or are you just talking about the brackets? 
Throughout the Godot source code it seems to be convention to omit brackets for one-liners. Following this convention, I guess I probably should have just omitted the brackets, since the for loop is a one-liner as well, although I felt the nested one-liners could cause readability problems.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Note to release maintainers: if this is cherry-picked, #33452 should be included too to fix the #33395 regression.
