### PR TITLE
Fix `overwrite_dialog` size on Android

### LINKED ISSUE #117918: Confirmation windows too large for small screen on Android.
### Tested versions

Reproducible on 4.6.1 stable on Android 10 (galaxy note 9)

### System information

Godot v4.6.1.stable - Android  (SDK 29 build N960U1UEU9FVG2) - Single-window, 1 monitor - Vulkan (Mobile) - integrated Adreno (TM) 630 -  (8 threads)

### Issue description

Confirmation window is unnecessarily large making any buttons off screen and unclickable. 

Image

Image

### Steps to reproduce

Move one file to a different folder where another file of the same name exists. Intention is to replace/overwrite the file. 

### Minimal reproduction project (MRP)

N/a

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes https://github.com/godotengine/godot/issues/117918

Also, increases the `move_dialog` minimum size for better usability on Android.

| Before | After |
|--------|--------|
|  Screenshot_20260328_162355 | Screenshot_20260328_162832 |
| Screenshot_20260328_162412 | Screenshot_20260328_162846 |

### CODE REVIEW

File: editor/docks/filesystem_dock.cpp [hunk 1]
```diff
@@ -4533,7 +4533,7 @@ FileSystemDock::FileSystemDock() {
 
 	overwrite_dialog_scroll = memnew(ScrollContainer);
 	overwrite_dialog_vb->add_child(overwrite_dialog_scroll);
-	overwrite_dialog_scroll->set_custom_minimum_size(Vector2(400, 600) * EDSCALE);
+	overwrite_dialog_scroll->set_custom_minimum_size(Vector2(350, 350) * EDSCALE);
```
Comment (m4gr3d) [inline editor/docks/filesystem_dock.cpp]: Is there an option to make this relative to the size of the window?

Comment (syntaxerror247) [reply editor/docks/filesystem_dock.cpp]: There's no direct option to make `custom_minimum_size` relative but we can set it's popup window size ratio and set this scroll container to expand.

Comment (m4gr3d) [reply editor/docks/filesystem_dock.cpp]: Will the container expand to match the text within?

Comment (syntaxerror247) [reply editor/docks/filesystem_dock.cpp]: Yes

Edit:
to be clear, It won't expand for text inside the scroll container.

Comment (syntaxerror247) [reply editor/docks/filesystem_dock.cpp]: Default size on my laptop and mobile

| laptop | mobile |
|--------|--------|
| image | image |

**Review by m4gr3d — APPROVED** [review]
