### PR TITLE
FileSystemDock: Collapse folders by default, add context menu with "E…

### LINKED ISSUE #7488: Filesystem window - option to disable expanding all folders
**Operating system or device - Godot version:**
ubuntu 16.04
2.1

**Issue description** (what happened, and what was expected):
The file system folders under res:// should not be fully expanded. I have lots of folders in folders, and by default the folders are all in an expanded view. It makes the first thing to do after loading the editor is to always close them.
The only folder that should be expanded by default is res://. None of its subfolders should be expanded.

**Steps to reproduce:**
make folders in folders in folders
load editor
pull out hair :)

### PR DESCRIPTION
**Pull request by lonesurv1vor**
…xpand all" / "Collapse all" option.

Fixes #7488 and partly #796 (no remembering of the state when tree gets updatet yet).

One thing to discuss is if the subfolders should expand/collapse recursively or only within the selected folder (current behavior). I like it more without recursion, because you have more control.

### CODE REVIEW

File: tools/editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -38,14 +38,16 @@
...
 #include "scene/main/viewport.h"
 
-
 bool FileSystemDock::_create_tree(TreeItem *p_parent,EditorFileSystemDirectory *p_dir) {
 
 
 	TreeItem *item = tree->create_item(p_parent);
 	String dname=p_dir->get_name();
-	if (dname=="")
+	if (dname=="")
```
Comment (akien-mga) [inline tools/editor/filesystem_dock.cpp]: Trailing space! (OK, no big deal :P)

File: tools/editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -38,14 +38,16 @@
...
 
 
 	TreeItem *item = tree->create_item(p_parent);
 	String dname=p_dir->get_name();
-	if (dname=="")
+	if (dname=="") 
 		dname="res://";
+	else
+		// collapse every tree item but the root folder
+		item->set_collapsed(true);
```
Comment (akien-mga) [inline tools/editor/filesystem_dock.cpp]: Please use braces for this `else`, even if the comment is properly ignored by the compiler and the statement is indeed part of the `else` block, this looks quite confusing.

Comment (lonesurvivor) [inline tools/editor/filesystem_dock.cpp]: Ok, will do that.
