### PR TITLE
 Fix PoolVector resize and subarray.

### LINKED ISSUE #30007: Editor crash when using PoolByteArray_subarray
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f3346da7f60] (??:0)
[2] PoolVector<unsigned char>::subarray(int, int) (/home/rafal/Pulpit/godot/./core/pool_vector.h:414 (discriminator 7))
[3] _VariantCall::_call_PoolByteArray_subarray(Variant&, Variant&, Variant const**) (/home/rafal/Pulpit/godot/core/variant_call.cpp:619)
[4] _VariantCall::FuncData::call(Variant&, Variant&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:121)
[5] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1092)
[6] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1080)
[7] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[8] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[9] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[10] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[11] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[12] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[13] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[14] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[15] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[16] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[17] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f3346d8ab6b] (??:0)
[19] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)

```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit f721feb3a64f79bb04b83e084f01388e3aef4f4e
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/f721feb3a64f79bb04b83e084f01388e3aef4f4e.zip

### LINKED ISSUE #30020: Editor crash when using PoolByteArray.sha256_string()
**Godot version:**
3.2.dev.custom_build. 297e7efa0

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f9b6da31f60] (??:0)
[2] /usr/bin/godot(_memcp+0x1d) [0x362a294] (/home/rafal/Pulpit/godot/thirdparty/misc/sha256.c:86 (discriminator 2))
[3] /usr/bin/godot(sha256_hash+0x91) [0x362aad7] (/home/rafal/Pulpit/godot/thirdparty/misc/sha256.c:152 (discriminator 3))
[4] _VariantCall::_call_PoolByteArray_sha256_string(Variant&, Variant&, Variant const**) (/home/rafal/Pulpit/godot/core/variant_call.cpp:604)
[5] _VariantCall::FuncData::call(Variant&, Variant&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:121)
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1092)
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1080)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[12] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1927)
[17] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[18] /usr/bin/godot(main+0xdf) [0x139d6d1] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f9b6da14b6b] (??:0)
[20] /usr/bin/godot(_start+0x2a) [0x139d53a] (??:?)
```

**Steps to reproduce:**
1. Read informations about repository(https://github.com/qarmin/The-worst-Godot-test-project#informations)
2. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit e7bc06ded4b989ddf4b2008dac2542c852ba76a6
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/e7bc06ded4b989ddf4b2008dac2542c852ba76a6.zip

### LINKED ISSUE #30021: Editor crash when using PoolVector<String>::resize(int)
**Godot version:**
3.2.dev.custom_build. 297e7efa0

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f98a58b4f60] (??:0)
[2] CowData<wchar_t>::_unref(void*) (/home/rafal/Pulpit/godot/./core/safe_refcount.h:118)
[3] CowData<wchar_t>::~CowData() (/home/rafal/Pulpit/godot/./core/cowdata.h:370)
[4] String::~String() (/home/rafal/Pulpit/godot/./core/ustring.h:130)
[5] PoolVector<String>::resize(int) (/home/rafal/Pulpit/godot/./core/pool_vector.h:596 (discriminator 2))
[6] _VariantCall::_call_PoolStringArray_resize(Variant&, Variant&, Variant const**) (/home/rafal/Pulpit/godot/core/variant_call.cpp:647)
[7] _VariantCall::FuncData::call(Variant&, Variant&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:121)
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1092)
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1927)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x139d6d1] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f98a5897b6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x139d53a] (??:?)
```

**Steps to reproduce:**
1. Read informations about repository(https://github.com/qarmin/The-worst-Godot-test-project#informations)
2. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 20638b48bb0d738fd2c2d7dd0befd24e4bd0837a
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/20638b48bb0d738fd2c2d7dd0befd24e4bd0837a.zip

### LINKED ISSUE #30022: Editor crash when using PoolVector3Array_set
**Godot version:**
3.2.dev.custom_build. 297e7efa0

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f4b66c21f60] (??:0)
[2] PoolVector<Vector3>::set(int, Vector3 const&) (/home/rafal/Pulpit/godot/./core/pool_vector.h:492)
[3] _VariantCall::_call_PoolVector3Array_set(Variant&, Variant&, Variant const**) (/home/rafal/Pulpit/godot/core/variant_call.cpp:667)
[4] _VariantCall::FuncData::call(Variant&, Variant&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:121)
[5] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1092)
[6] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[7] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[8] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[9] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[10] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[11] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[12] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[13] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[14] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[15] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1927)
[16] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[17] /usr/bin/godot(main+0xdf) [0x139d6d1] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f4b66c04b6b] (??:0)
[19] /usr/bin/godot(_start+0x2a) [0x139d53a] (??:?)
```

**Steps to reproduce:**
1. Read informations about repository(https://github.com/qarmin/The-worst-Godot-test-project#informations)
2. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit ab6d8dcd334c59f3d8a2afd42f362bee62aac85f
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/ab6d8dcd334c59f3d8a2afd42f362bee62aac85f.zip

### PR DESCRIPTION
**Pull request by Faless**
The first used to accept negative values, the second would crash if out
of bound.

Subarray:
Fixes #30007

Resize:
Fixes #30020
Fixes #30021
Fixes #30022

### CODE REVIEW

File: core/pool_vector.h [hunk 1]
```diff
@@ -411,8 +411,8 @@ class PoolVector {
 			p_to = size() + p_to;
 		}
 
-		CRASH_BAD_INDEX(p_from, size());
-		CRASH_BAD_INDEX(p_to, size());
+		ERR_FAIL_INDEX_V(p_from, size(), PoolVector<T>());
+		ERR_FAIL_INDEX_V(p_to, size(), PoolVector<T>());
```
Comment (akien-mga) [inline core/pool_vector.h]: It seems those were made crashing on purpose by @RandomShaper in 211c4518903d82068c061943064824ac5595fd38. It would be good to know why, and assess the other `CRASH_BAD_INDEX` added back then.

Comment (RandomShaper) [reply core/pool_vector.h]: Before my commit, the error handling code was this:
```
PoolVector<T> &aux = *((PoolVector<T> *)0); // nullreturn
ERR_FAIL_COND_V(p_from < 0 || p_from >= size(), aux)
```
Seemingly, the intention was to make the engine crash at some point, but that way of doing it invokes undefined behavior. It might very well keep running on a weird state.

I made the crash explicit and happening for sure.

This new change modifies the behavior of the function so that it handles out-of-bounds indices gracefully, giving you back and empty vector instead of crashing. But I'm not sure if that would be losing a chance of catching a logic error early.

Comment (Faless) [reply core/pool_vector.h]: Thanks for the explanation, I was actually unsure about this change but forgot to check the log and just tagged hpvb since I knew he worked on that time ago.

> But I'm not sure if that would be losing a chance of catching a logic error early.

I think the idea in Godot is to always avoid crashing, and let the user take responsibility in not having errors in the debugger/console. So, in case of a logic error, the user would see the message and realize that something is wrong when calling `resize`. I think the editor also point you to the line in code that called if if you click on it. But maybe I'm missing the point.

Comment (Faless) [reply core/pool_vector.h]: But maybe we can handle this at a higher level in the exposed functions? Would that be better? I find it strange that passing a negative value to `resize` in gdscript crashes the engine.

Comment (akien-mga) [reply core/pool_vector.h]: Yeah I don't think it should crash if it is recoverable, it should just error out. Red errors printed to the stdout are still must fix for both game developers and engine devs, so it's sufficient IMO.

Comment (RandomShaper) [reply core/pool_vector.h]: I totally agree on your point about `resize`.
Other crashing functions can not be fixed so easily; i.e., those returning references to elements.
I find your idea about handling those situations more gracefully at the binding level interesting.
Some methods 
What if we undertake a full review of all the crashing behaviors for 4.0?
Not sure if a more conservative subset of that would have a point in 3.2 if we did that.

Comment (KoBeWi) [reply core/pool_vector.h]: > What if we undertake a full review of all the crashing behaviors for 4.0?

Then you might want to look at #24199. FAIL macros don't print the error line in script, only the line in the source, which in many cases isn't really useful. I wonder if it's possible to give macro an access to the script, so it tells you which line in YOUR code fails.

Comment (akien-mga) [reply core/pool_vector.h]: Comment from @reduz on IRC:
```
18:53 <reduz> Akien: since this can be used from gdscript, it may probably be better to throw an error and return an empty vector
18:53 <reduz> crashing is too much
18:53 <reduz> from gdscript all functions that can do out of bounds reads are prevalidated
18:53 <reduz> (and writes)
```

Comment (Faless) [reply core/pool_vector.h]: @KoBeWi don't the editor debugger bring you to the GDScript line that caused that error when you click on it? It should.

Comment (Faless) [reply core/pool_vector.h]: See the attached this [screencast](https://github.com/godotengine/godot/files/3321911/debugger_to_line2.zip) as an example

Comment (KoBeWi) [reply core/pool_vector.h]: I remember some errors that you couldn't trace, but maybe they weren't from GDScript, but from scene (in which case providing a failing node path would be helpful).

**Comment by akien-mga** [comment]
Thanks!
