### PR TITLE
Fix alignment and locking issues with CommandQueueMT

### LINKED ISSUE #21725: Multi-Threaded mode coredumps on Linux
Here is a simple multithreading test with my Favorite Testing Cube. Just create a scene based on Spatial with a camera at (0, -20, -40) and run this code inside the Spatial. (I've tried this on Godot 3.0 stable and Godot master.)
<details><summary>Test code</summary>

```
extends Spatial

var loader_thread = Thread.new()

var queue = [Vector3(0,0,-1),
			Vector3(-1,0,-1),
			Vector3(1,0,-1)]

func _process(delta): # Process input
	if Input.is_action_just_pressed("ui_cancel"): get_tree().quit() # Exit on Escape

func _ready():
	chunk_load(queue.pop_front())

func chunk_load(pos): # Called on "ready", manages starting a loader thread
	loader_thread.start(self, "initialize", pos) # Start a loader thread to generate a chunk

func initialize(pos): # Started in a thread, generates a chunk
	var chunk = Spatial.new()
	chunk.translate(pos * 16)
	
	# Build a tree of nodes for this chunk
	for x in range(16):
		for y in range(16):
			for z in range(16):
				var mi = MeshInstance.new()
				mi.mesh = CubeMesh.new()
				mi.mesh.size = Vector3(1, 1, 1)
				mi.translate(Vector3(x, y, z))
				chunk.add_child(mi)
	
	# Add this chunk to the scene tree, and reap the thread
	call_deferred("finalize_chunk", chunk)

func finalize_chunk(chunk): # Add the chunk to the scee tree and reap the loader thread
	add_child(chunk)
	loader_thread.wait_to_finish()
	
	# Load another chunk after this one, just for this test
	if queue != null: chunk_load(queue.pop_front())
```
</details>

With "Single-Safe" threading model, it works on all listed platforms. With "Multi-Threaded", it works on Windows, but coredumps on every Linux machine and distro and graphics card that I have:

- Debian Jessie (oldstable), GeForce GTX 260, nvidia driver
- Debian Stretch (stable), Radeon 5850, radeon driver
- Debian Stretch (stable), Radeon Mobility-something on r600, radeon driver
- Ubuntu Bionic (18.04), Radeon 5850, radeon driver

Additionally, on Debian Stretch with radeon driver, it fails to build shaders ("translation from TSGI failed"), but that's a separate issue. (Should I open it? Does Godot officially support radeon driver? According to glxinfo, radeon supports GLES3. On one hand, it's going to be replaced, so no sense putting effort into supporting it; on the other hand, people owning pre-GCN Radeon cards have no other choice...)

<details><summary>Debian Jessie backtrace</summary>

```
OpenGL ES 3.0 Renderer: GeForce GTX 260/PCIe/SSE2
WARNING: load: Loaded resource as image file, this will not work on export: 'res://icon.png'. Instead, import the image file as an Image resource and load it normally as a resource.
   At: core/image.cpp:1734.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x350e0) [0x7f05473ce0e0] (??:0)
[2] ./test_multithreading_GLES3.x86_64() [0x16ec2f0] (<artificial>:?)
[3] ./test_multithreading_GLES3.x86_64() [0x1188640] (??:?)
[4] ./test_multithreading_GLES3.x86_64() [0xab62d6] (<artificial>:?)
[5] ./test_multithreading_GLES3.x86_64() [0x72e1fa] (<artificial>:?)
[6] ./test_multithreading_GLES3.x86_64() [0x6c2864] (??:?)
[7] ./test_multithreading_GLES3.x86_64() [0x194a090] (??:?)
[8] ./test_multithreading_GLES3.x86_64() [0x19c6afc] (??:?)
[9] ./test_multithreading_GLES3.x86_64() [0x71e246] (<artificial>:?)
[10] ./test_multithreading_GLES3.x86_64() [0x72b6e8] (<artificial>:?)
[11] ./test_multithreading_GLES3.x86_64() [0x1949fcf] (??:?)
[12] ./test_multithreading_GLES3.x86_64() [0x179e30f] (<artificial>:?)
[13] ./test_multithreading_GLES3.x86_64() [0xb97a04] (<artificial>:?)
[14] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f0545b79064] (??:0)
[15] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f054748162d] (??:0)
-- END OF BACKTRACE --
Aborted
```
</details>

Edit: What's especially frustrating is that this dump does not even appear in the debugger, or even in the output console. When launched from the editor, the project window just closes. I was lucky enough to catch the problem because I just switched to multi-threaded mode, but others will think that the program cleanly finished for some reason...
Edit: Added an queue array to allow multiple chunks - one is not always enough

### PR DESCRIPTION
**Pull request by hpvb**
The allocations of commands in CommandQueueMT weren't aligned. This
commit aligns all accesses on 64bit boundaries regardless of target
platform. This ensures that all types are aligned.

Lock-wise the semaphores were maked as usable when the command had ran
but not when the synchronous stub had finished with it. This lead to a
race condition where sometimes the semaphore got reused before it was
waited on. We now mark the semaphore as free only once we're done
waiting on it.

This fixes #21725

### CODE REVIEW

File: core/command_queue_mt.cpp [hunk 1]
```diff
@@ -107,6 +107,7 @@ CommandQueueMT::CommandQueueMT(bool p_sync) {
 	write_ptr = 0;
 	dealloc_ptr = 0;
 	mutex = Mutex::create();
+	command_mem = (uint8_t *)malloc(COMMAND_MEM_SIZE);
```
Comment (hpvb) [inline core/command_queue_mt.cpp]: Before anyone complains, malloc() here guarantees that the array itself is 64bit aligned :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Skipping for the 3.0 branch, that's too big a change IMO.
