### PR TITLE
Fix `EditorExportPlugin::_export_file()` ignoring GDScripts (reverted)

### LINKED ISSUE #93487: `_export_file()` not called for GDScript files
### Tested versions

4.3 beta2

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Related to #67844
When I export my project `_export_file()` does not see GDScript files and they all get exported. It does not happen in a minimal project, I don't know what causes it.

### Steps to reproduce

1. Open my project ;_;
2. Export ZIP
3. My export plugin should filter out some .gd files, but all are included in the zip

### Minimal reproduction project (MRP)

I have maximal reproduction project.

### PR DESCRIPTION
**Pull request by Muller-Castro**
Fix `EditorExportPlugin::_export_file()` ignoring GDScript paths if `EditorExportPlugin::_get_name() > "GDScript"`, and not preventing them from being exported on `skip()` if `EditorExportPlugin::_get_name() < "GDScript"`

*Bugsquad edit:* Closes #93487

### CODE REVIEW

File: editor/export/editor_export_platform.cpp [hunk 1]
```diff
@@ -1345,6 +1345,8 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
 		}
 
 		bool do_export = true;
+		bool skip_all = false;
```
Comment (KoBeWi) [inline editor/export/editor_export_platform.cpp:1348]: Isn't `skip_all` always opposite of `do_export`? Why is it needed?

**Review by KoBeWi — APPROVED** [review]
The code feels a bit convoluted, but it works correctly.

File: editor/export/editor_export_platform.cpp [hunk 2]
```diff
@@ -1360,26 +1362,30 @@ Error EditorExportPlatform::export_project_files(const Ref<EditorExportPreset> &
...
+			if (!skip_all) {
+				for (int j = 0; j < export_plugins[i]->extra_files.size(); j++) {
+					err = save_proxy.save_file(p_udata, export_plugins[i]->extra_files[j].path, export_plugins[i]->extra_files[j].data, idx, total, enc_in_filters, enc_ex_filters, key, seed);
+					if (err != OK) {
+						return err;
+					}
+					if (export_plugins[i]->extra_files[j].remap) {
+						do_export = false; // If remap, do not.
+						path_remaps.push_back(path);
+						path_remaps.push_back(export_plugins[i]->extra_files[j].path);
```
Comment (AThousandShips) [inline editor/export/editor_export_platform.cpp]:
```suggestion
				for (const ExtraFile &extra_file : export_plugins[i]->extra_files) {
					err = save_proxy.save_file(p_udata, extra_file.path, extra_file.data, idx, total, enc_in_filters, enc_ex_filters, key, seed);
					if (err != OK) {
						return err;
					}
					if (extra_file.remap) {
						do_export = false; // If remap, do not.
						path_remaps.push_back(path);
						path_remaps.push_back(extra_file.path);
```

File: editor/export/editor_export_platform.cpp (hunk 1 above)
Comment (Muller-Castro) [reply editor/export/editor_export_platform.cpp:1348]: `do_export` may change for the next plugins at [1381](https://github.com/godotengine/godot/pull/109815/files#diff-a64507e1723f451757967d0bcb08c8e8999bc77b5d4863e9c71133432140b17fR1381)

**Comment by Repiteo** [comment]
Thanks!
