### PR TITLE
Precise size calculation of ScrollContainer

### LINKED ISSUE #21517: ScrollContainer's max scroll_vertical is larger than expected
**Godot version:**

3.0.6

**OS/device including version:**

Windows 8.1

**Issue description:**

I noticed that no matter what I do, the maximum value of a ScrollContainer's scroll_vertical is always 12 px more than expected.

With three Buttons each 20 px tall, inside a VBoxContainer with separation = 0, you'd expect a ScrollContainer 60 px tall to have no VScrollBar. But it does, and you can scroll down 12 px (that is, scroll_vertical can be increased to 12).

The result of this is that there is an ugly gap at the bottom of the VScrollBar, corresponding to the 12 extra pixels. 

**Steps to reproduce:**

- Create a ScrollContainer 60 px tall with scroll_vertical_enabled = true.
- Add a VBoxContainer with separation = 0.
- Add 3 buttons to the VBoxContainer, each 20 px tall.
- Observe the extra 12 px at the bottom of the VScrollBar.

**Minimal reproduction project:**
[ScrollContainerIssue.zip](https://github.com/godotengine/godot/files/2326383/ScrollContainerIssue.zip)

**Thoughts:**

Maybe these 12 extra pixels correspond to the height of an HScrollBar that isn't visible but is somehow figuring into the mix.

### PR DESCRIPTION
**Pull request by volzhs**
Fix #21517

I think this can be cherry-picked on 3.0 branch.

### CODE REVIEW

File: scene/gui/scroll_container.cpp [hunk 1]
```diff
@@ -371,6 +371,9 @@ void ScrollContainer::update_scrollbars() {
 	Size2 hmin = h_scroll->get_combined_minimum_size();
 	Size2 vmin = v_scroll->get_combined_minimum_size();
 
+	if (!scroll_h) hmin.height = 0;
+	if (!scroll_v) vmin.width = 0;
```
Comment (akien-mga) [inline scene/gui/scroll_container.cpp]: Maybe it would be cleaner to do this?
```cpp
Size2 hmin;
Size2 vmin;
if (scroll_h)
	hmin = h_scroll->get_combined_minimum_size();
if (scroll_v)
	vmin = v_scroll->get_combined_minimum_size();
```

**Comment by volzhs** [comment]
@akien-mga updated.

**Comment by reduz** [comment]
I don't think the original issue is a bug, unless I misunderstood something. Check my comment in there.

**Comment by akien-mga** [comment]
Closing then (feel free to reopen if @reduz's analysis is incorrect).

**Comment by volzhs** [comment]
@akien-mga @reduz 

https://github.com/godotengine/godot/blob/69761816381f11536980441265345ba055ad1c26/scene/gui/scroll_container.cpp#L371-L372

getting h/v scrollbar size at here

https://github.com/godotengine/godot/blob/69761816381f11536980441265345ba055ad1c26/scene/gui/scroll_container.cpp#L376-L387

and here,
`v_scroll->set_page(size.height - hmin.height);`
page is set with considering h scrollbar's height even though it's not visible.

the another way to fix it is `get_combined_minimum_size()` returns (0,0) when it's not visible.
but it would break things.

**Comment by volzhs** [comment]
I'd like to request a review to @groud for this too.

**Comment by groud** [comment]
I think this PR is ok. There is indeed a problem. 
With something as simple as this:
2019-03-07-135542_486x164_scrot
I end up with this:
2019-03-07-135709_88x41_scrot
(There is some space after the ScrollContainer's content.)
Note that all styleboxes were overridden by the default empty style box, so the problem was not here.

If this PR solves this problem, I think it should be merged.

**Comment by volzhs** [comment]
I'd like to reopen it and hope it's merged for 3.1 :smile: 
I would not break things.

**Comment by akien-mga** [comment]
Thanks!
