### PR TITLE
Fix invalid 3-to-4 renames of `add_animation` to `add_animation_library`

### LINKED ISSUE #86646: Upgrading from 3 to 4 changes functions to invalid functions
### Tested versions

Reproducible when upgrading from 3.5 to 4.2 (and possibly other versions, I was only upgrading from 3.5 to 4.2).

### System information

Windows 10, Godot 4.2

### Issue description

Upgrading the project with the `--convert-3to4` flag changes functions to invalid functions. For example, the SpriteFrame's `AddAnimation` method was supposedly updated to `AddAnimationLibrary`, however this results in a compile error saying:
> 'SpriteFrames' does not contain a definition for 'AddAnimationLibrary' and no accessible extension method 'AddAnimationLibrary' accepting a first argument of type 'SpriteFrames' could be found (are you missing a using directive or an assembly reference?)

When I look in the assembly for SpriteFrames (Assembly GodotSharp, Version=4.2.0.0), I see that it contains a definition for `AddAnimation` but not `AddAnimationLibrary`. There are several other upgraded methods that result in this same error.

Am I missing something? This [cheat sheet](https://godot-3to4.vercel.app/) seems to indicate that the upgrade was supposed to change that method to `AddAnimationLibrary`, but why does the assembly define the old method name and not the new one?

**URL to the documentation page:**
https://docs.godotengine.org/en/4.0/tutorials/migrating/upgrading_to_godot_4.html

### Steps to reproduce

Have a Godot 3.5 project and upgrade to 4.2

### Minimal reproduction project (MRP)

This is more a general question. The project in question is private, and I suspect this applies to any project upgrading from 3 to 4.

### PR DESCRIPTION
**Pull request by AThousandShips**
This rename breaks `SpriteFrames` and also isn't valid as the new method takes an `AnimationLibrary`, not an `Animation`

This change needs a more elaborate fix and should be mentioned in the migration page, see:
* https://github.com/godotengine/godot/issues/86611

* Fixes: https://github.com/godotengine/godot/issues/86646

### CODE REVIEW

File: editor/renames_map_3_to_4.cpp [hunk 1]
```diff
@@ -644,7 +644,6 @@ const char *RenamesMap3To4::csharp_function_renames[][2] = {
 	{ "_SetPlaying", "SetPlaying" }, // AnimatedSprite3D
 	{ "_ToplevelRaiseSelf", "_TopLevelRaiseSelf" }, // CanvasItem
 	{ "_UpdateWrapAt", "_UpdateWrapAtColumn" }, // TextEdit
-	{ "AddAnimation", "AddAnimationLibrary" }, // AnimationPlayer
```
Comment (AThousandShips) [inline editor/renames_map_3_to_4.cpp:647]: As none of the commented out conversions are mentioned in the same way in the C# part I just removed it, can add it as a commented out part if desired

File: editor/renames_map_3_to_4.cpp [hunk 2]
```diff
@@ -163,6 +163,7 @@ const char *RenamesMap3To4::gdscript_function_renames[][2] = {
 
 	// { "_set_name", "get_tracker_name" }, // XRPositionalTracker -- CameraFeed uses this.
 	// { "_unhandled_input", "_unhandled_key_input" }, // BaseButton, ViewportContainer -- Breaks Node, FileDialog, SubViewportContainer.
+	// { "add_animation", "add_animation_library" }, // AnimationPlayer -- Breaks SpriteFrames (and isn't a correct conversion).
```
Comment (AThousandShips) [inline editor/renames_map_3_to_4.cpp:166]: Technically this now applies to `AnimationMixer`, but wanting to allow cherry picking of this so not changing this

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2. (Included the removal from https://github.com/godotengine/godot/pull/86301 since it was conflicting with it. Also removed the C# variant during the cherry-pick for simplicity, but here's the PR for `master` https://github.com/godotengine/godot/pull/87533)

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4. (Same caveat.)
