### PR TITLE
Set some dialogs in the VisualShader editor to be exclusive

### LINKED ISSUE #83805: Some times can't add node in visualshader editor
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Windows 10, 64bit

### Issue description

Some times can't add node in visualshader editor

### Steps to reproduce

1. Open a VisualShader file for edit.
2. Click the `Add Node...` button, it will popup menu, it is OK.
3. Direct close the menu.
4. Clikd the `Add Node...` again, the menu can't popup.
GIF

### Minimal reproduction project

/

### PR DESCRIPTION
**Pull request by jsjtxietian**
Should fix #83805

### CODE REVIEW

**Comment by akien-mga** [comment]
That should work, but I'm not sure it's the best solution.

I would expect either of those behaviors:
- Either the popup should be exclusive so it can't lose focus until you close it,
- Or clicking outside the popup should close it, not just lose focus.

**Comment by jsjtxietian** [comment]
I think either is ok really, I sightly perfer the first solution where it grabs focus (more intuitive) , the second one may cause some confusion.

**Comment by jsjtxietian** [comment]
I have updated the code, along with some other popup window with the same problem in visual shader editor. Tested on my windows it works fine.

**Comment by Chaosus** [comment]
Seems to be a good replacement for https://github.com/godotengine/godot/pull/84488.

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 1]
```diff
@@ -4080,6 +4080,12 @@ void VisualShaderEditor::_show_members_dialog(bool at_mouse_pos, VisualShaderNod
 		saved_node_pos_dirty = false;
 		members_dialog->set_position(graph->get_screen_position() + Point2(5 * EDSCALE, 65 * EDSCALE));
 	}
+
+	if (members_dialog->is_visible()) {
+		members_dialog->grab_focus();
+		return;
+	}
+
```
Comment (akien-mga) [inline editor/plugins/visual_shader_editor_plugin.cpp:4088]: Since this dialog is now exclusive, I guess this situation should no longer happen?

May not hurt to keep it for safety.

**Review by akien-mga — APPROVED** [review]
Looks good to me overall.

File: editor/plugins/visual_shader_editor_plugin.cpp (hunk 1 above)
Comment (jsjtxietian) [reply editor/plugins/visual_shader_editor_plugin.cpp:4088]: Yes this should be removed, if there is any related bug in the future I will fix it.
