### PR TITLE
Ignore trailing slashes in new project’s path when disabling Create Folder

### LINKED ISSUE #93973: Create new project with default "Create folder" selected, not working in Godot 4.3.*
### Tested versions

- Reproducible in: v4.3.dev5.official [c9c17d6ca], v4.3.dev6.official [64520fe67], v4.3.beta1.official [a4f2ea91a], v4.3.beta2.official [b75f0485b]
- Not reproducible in: previously versions (is a new attribute)

### System information

Ubuntu 22.04.4 LTS - Godot v4.3.beta2.official [b75f0485b]

### Issue description

When creating a new project, the "Create Folder" option is selected by default, but it is not working.
New proyect

If I leave the option checked (as it comes) and press the CREATE AND EDIT button, it creates the project without creating a new folder with the project's name. However, if before pressing the CREATE AND EDIT button I uncheck and recheck the "Create Folder" option, in that case, it does create the folder.
[Video for new proyect](https://github.com/godotengine/godot/assets/576414/12f40372-074a-4cfc-8d95-fe1c4f9f4af1)

### Steps to reproduce

Test 1

1. Start Godot
2. Press the button to create a new project
3. If necessary, change the project's name (if a project with the default name already exists)
4. Press the Create and Edit button
5. Verify that the project was created in the "Project Path" folder and not within the "Project Name" folder.

Test 2
1. Start Godot
2. Press the button to create a new project
3. If necessary, change the project's name (if a project with the default name already exists)
4. Uncheck the "Create Folder" option
5. Recheck the "Create Folder" option
6. Press the Create and Edit button
7. Verify that the project was created in the "Project Name" folder within the "Project Path" folder (Expected behavior)

Possible fixes:

1. Have the "Create Folder" option appear unchecked by default.
2. Ensure the internal value used by the editor is set to TRUE when the screen starts.

### Minimal reproduction project (MRP)

no MRP, only video to see bug
[Grabación de pantalla desde 05-07-24 11:27:01.webm](https://github.com/godotengine/godot/assets/576414/bb286a6b-30e3-4490-ae88-d19013f53717)

### PR DESCRIPTION
**Pull request by Grublady**
In the “Create New Project” dialog, disabling the “Create Folder” slider with a trailing slash in the project path would cause it to incorrectly identify the last path component as the substring following the slash, in other words, an empty string.

By first discarding any trailing slashes when disabling the slider, the project dialog will now identify and pop the last path component as usual even when a trailing slash is present.

Fixes #93973

### CODE REVIEW

**Comment by AThousandShips** [comment]
Your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by Grublady** [comment]
Apologies! I have added the commit header email address to my GitHub account, please let me know if there are any other issues

File: editor/project_manager/project_dialog.cpp [hunk 1]
```diff
@@ -315,6 +315,10 @@ void ProjectDialog::_create_dir_toggled(bool p_pressed) {
 			target_path = target_path.path_join(last_custom_target_dir);
 		}
 	} else {
+		// Strip any trailing slash.
+		while (target_path.ends_with("/") || target_path.ends_with("\\")) {
+			target_path = target_path.substr(0, target_path.length() - 1);
+		}
```
Comment (akien-mga) [inline editor/project_manager/project_dialog.cpp:321]:
```suggestion
		target_path = target_path.rstrip("/");
```

Comment (Grublady) [reply editor/project_manager/project_dialog.cpp:321]: Ah, much nicer! Any reason not to include backslash?
```suggestion
		target_path = target_path.rstrip("/\\");
```

Comment (akien-mga) [reply editor/project_manager/project_dialog.cpp:321]: `rstrip` replaces all occurrences of a pattern from the right side, so it would only replace it if it ends with `/\` with the proposed change.
If you want to strip both, you have to do them separately: `target_path.rstrip("/").rstrip("\\")`

Godot shouldn't be using backslashes in paths though, but I guess users might input them manually / copy from the Windows explorer, so that makes sense.

File: editor/project_manager/project_dialog.cpp [hunk 2]
```diff
@@ -315,6 +315,8 @@ void ProjectDialog::_create_dir_toggled(bool p_pressed) {
 			target_path = target_path.path_join(last_custom_target_dir);
 		}
 	} else {
+		// Strip any trailing slash.
+		target_path = target_path.rstrip("/").rstrip("\\")
```
Comment (adamscott) [inline editor/project_manager/project_dialog.cpp:319]: Isn't a semi-colon `;` needed at the end of the line?
```suggestion
		target_path = target_path.rstrip("/").rstrip("\\");
```

Comment (Grublady) [reply editor/project_manager/project_dialog.cpp]: Absolutely 😅 I can't believe I missed that

**Comment by Grublady** [comment]
Amended with the suggested change, however I'm still uncertain whether it requires one or two calls to `rstrip`—

On my machine it seems to successfully strip any combination of forward & back slashes with just `target_path = target_path.rstrip("/\\");`, but since two calls was suggested I would like to confirm this behavior.

If this is not intended it may be another issue and/or documentation discrepancy.

**Comment by akien-mga** [comment]
> Amended with the suggested change, however I'm still uncertain whether it requires one or two calls to `rstrip`—
> 
> On my machine it seems to successfully strip any combination of forward & back slashes with just `target_path = target_path.rstrip("/\\");`, but since two calls was suggested I would like to confirm this behavior.
> 
> If this is not intended it may be another issue and/or documentation discrepancy.

Hm you are right, I commented from memory but indeed `rstrip` replaces any of the chars found in the string, so your suggestion was correct (and more efficient).

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Creating a project when the project path has a trailing slash also works (it's in the correct newly created folder).

### Before

https://github.com/godotengine/godot/assets/180032/49555e61-9436-4243-9463-10a6da744cc8

### After

https://github.com/godotengine/godot/assets/180032/053b5a54-dd52-4bf3-a665-3fa9053dccb4

**Comment by akien-mga** [comment]
Thanks!
