### PR TITLE
Use one-based line numbers for external text editors

### LINKED ISSUE #100832: External Editor line flag differs in behavior from internal editor
### Tested versions

- Tested in Godot v4.3.stable.official [77dcf97d8]
- Reproducible in both VSCode and SublimeText
- Unsure if it applies to any other editor

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD Ryzen 3 3200G with Radeon Vega Graphics (4 Threads)

### Issue description

When using a external editor, files open 1 line before the expected line while debugging. Compare:

Image

Image

This happens with the official VSCode settings as well, which is why I tried a different one here.

I'm unfamiliar with how this works internally, but this seems to be the line that replaces the flag for the external editor:

https://github.com/godotengine/godot/blob/99a8ab795d65e816ea7c452aa0fb55d02385c048/editor/plugins/script_editor_plugin.cpp#L2508

And I found this case where it is being modified:

https://github.com/godotengine/godot/blob/99a8ab795d65e816ea7c452aa0fb55d02385c048/editor/plugins/script_editor_plugin.cpp#L617

It didn't seem like it was possible to modify the line flag directly in the editor settings in way (like adding a +1)

### Steps to reproduce

- Configure a project with an external editor, like VSCode
- Use External Editor for Debugging
- insert a breakpoint at any line
- see the wrong line being open

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #107809: VS Code opens to line before error on selecting stack trace/error/warning
### Tested versions

Reproducible in v4.5.beta.custom_build [4e6ac9bcc]

### System information

Godot v4.5.beta (4e6ac9bcc) - macOS Sequoia (15.5.0) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - Apple M4 Pro - Apple M4 Pro (14 threads) - 24.00 GiB memory

### Issue description

I'm using VS Code and the following `exec_flags`:
```
{project} --goto {file}:{line}:{col}
```
When an error occurs in the game, the stack frame line number is correct:

Image

However, VS Code opens to the line *before* the one with the error:

Image

### Steps to reproduce

- Create a project with a GDScript that will throw a runtime error, such as attempting to access a member of an object that is guaranteed to be `null`.
- In Editor Settings, set up Visual Studio Code as the external code editor.
   - Exec Flags should be `{project} --goto {file}:{line}:{col}`.
   - Use External Editor should be enabled.
- In the Script tab, check "Debug with External Editor" under the Debug menu.
- Run the scene in the editor so that the error is thrown. VS Code should pop up with the script file, but the cursor will be on the line *before* the error.

### Minimal reproduction project (MRP)

[test-vscode-debug-line_2025-06-21_09-25-19.zip](https://github.com/user-attachments/files/20847446/test-vscode-debug-line_2025-06-21_09-25-19.zip)

For this MRP, run the scene and press the Enter key to crash it.

### PR DESCRIPTION
**Pull request by Meorge**
Closes #107809 . Closes #100832 . Supercedes #107812 .

The table in #107809 notes that all of the external editors mentioned by the Godot Docs expect line numbers to start at 1. Internally, Godot considers line numbers to start at 0. This PR simply adds 1 to an existing line number before passing it to an external editor, so that the editor highlights the correct line.

As noted in the PR's comment, a better long-term solution may be to have Godot adopt one-based line numbering internally. I chose to take a more conservative approach for now, to avoid breaking other parts of the engine or editor while fixing the problem at hand.

### CODE REVIEW

File: editor/plugins/script_editor_plugin.cpp [hunk 1]
```diff
@@ -2480,6 +2480,13 @@ bool ScriptEditor::edit(const Ref<Resource> &p_resource, int p_line, int p_col,
 
 	const bool should_open = (open_dominant && !use_external_editor) || !EditorNode::get_singleton()->is_changing_scene();
 
+	// External editors expect line numbers to start from 1, but Godot starts them from 0.
+	// In the long run, we may want to make Godot work with this standard, but for now
+	// this will send external editors to the correct line.
+	if (use_external_editor) {
```
Comment (kitbdev) [inline editor/plugins/script_editor_plugin.cpp]: This will fail in the fallback case and with `scr->get_language()->overrides_external_editor()`.
It looks like `scr->get_language()->overrides_external_editor()` should be 0 indexed, it is handled in `OpenInExternalEditor`.

**Review by kitbdev — COMMENTED** [review]
The column should also be 1 indexed.

We can't completely change to a 1 index system internally in the future, it would just cause lots of issues. The lines are stored in a vector which is always going to be 0 indexed, and it would cause compatibility issues if we change TextEdit and CodeEdit methods to be 1 indexed as well. I also doubt those editors all actually use 1 indexed internally, its just the interface.
So there is always going to be conversion between them, we just need to better define where it happens.
We already display line numbers in the editor as starting from 1, and `EditorInterface::edit_script` looks like it is already 1 indexed.

File: editor/plugins/script_editor_plugin.cpp (hunk 1 above)
Comment (Meorge) [reply editor/plugins/script_editor_plugin.cpp]: Thanks for catching that! Do you think it'd be better/sufficient, then, to add 1 to `p_line` and `p_col` to the flag generation code here?
https://github.com/godotengine/godot/blob/3162399ec5b0f200052b794d49ae097135f333f2/editor/plugins/script_editor_plugin.cpp#L2513-L2515

Looking over the function, it seems like that would work for only passing the one-based values to external editors using the exec flags, but I just want to double-check that it'd be an appropriate place before I push through a commit for it 😅

Comment (kitbdev) [reply editor/plugins/script_editor_plugin.cpp]: That should be good, yes.

Comment (Meorge) [reply editor/plugins/script_editor_plugin.cpp]: Great, thanks! I'll get that updated and pushed shortly, then! 😄

**Review by kitbdev — APPROVED** [review]
Tested on multiple different editors, works as expected.

**Comment by Repiteo** [comment]
Thanks!
