### PR TITLE
Show last added action on Input Map

### LINKED ISSUE #6121: Auto scroll Input Map when adding new actions
**Operating system or device - Godot version:**
Windows 10 Godot 2.1 Stable

**Issue description** (what happened, and what was expected):
I would like the Input Map screen to auto scroll to the bottom whenever a new action is added. It would make the workflow more efficient.

**Steps to reproduce:**

1. Open Scene -> Project Settings
2. Select Input Map
3. Add a new action
4. Scroll to the bottom and click + on the action to map it to a key/button etc

I guess this would be low priority but it would be nice.

### PR DESCRIPTION
**Pull request by volzhs**
Fix #6121

input_map

### CODE REVIEW

File: core/os/input_event.cpp [hunk 1]
```diff
@@ -34,8 +34,52 @@
  */
 
 bool InputEvent::operator==(const InputEvent &p_event) const {
+	if (type != p_event.type){
+		return false;
+	}
```
Comment (neikeq) [inline core/os/input_event.cpp]: What's the of the above condition?

Comment (volzhs) [inline core/os/input_event.cpp]: not check further if type is not same, like `InputEventKey` != `InputEventMouseButton`.
rest `case` didn't check type is same.

Comment (neikeq) [inline core/os/input_event.cpp]: Oh, my bad. I don't know what I thought you were comparing structs there :D

File: core/os/input_event.cpp [hunk 2]
```diff
@@ -34,8 +34,52 @@
...
 
-	return true;
+	switch(type) {
```
Comment (akien-mga) [inline core/os/input_event.cpp]: It would have been good to mention in the commit log that you're doing more than "showing the last added action on InputMap", since this code chunk effectively fixes broken InputEvent comparison, which is relevant beyond this usability enhancement :)

Comment (volzhs) [inline core/os/input_event.cpp]: @akien-mga I now know that how to merge two commits to one, but I don't know how to separate one commit in tow. :(

Comment (akien-mga) [inline core/os/input_event.cpp]: I think it's okay to keep it in one commit, but maybe you can amend the log to mention the two changes? `git commit --amend`.

Comment (neikeq) [inline core/os/input_event.cpp]: If you want to split the last commit you can do:

`git reset --soft HEAD^` (`--soft` to keep the changes)

Then commit the changes separately and force-push. I would recommend doing it in a cloned branch in case you screw up, and specify the branch like this:

`git push -f origin issue-6121-cloned:issue-6121`

Comment (volzhs) [inline core/os/input_event.cpp]: @akien-mga I updated commit log.

**Comment by vnen** [comment]
This broke some of [my code](https://github.com/vnen/godot-rpg2d) but only on the 2.1 branch, on master I have no problem. Still not sure what is the actual problem.

**Comment by akien-mga** [comment]
@vnen That's #6376 for which I haven't cherry-picked the fix to 2.1 yet.

**Comment by vnen** [comment]
@akien-mga oh, I see. Sorry for the disturbance then.
