### PR TITLE
Defer `ActionMapEditor::_action_edited` signal to prevent tree updates when tree is blocked.

### LINKED ISSUE #86612: Input System - Changing Value and pressing outside the field crashing Godot Engine
### Tested versions

- Reproducible in 4.2.1 stable.
- minimum project requirement, empty project will do.

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.3758) - AMD Ryzen 3 3100 4-Core Processor (8 Threads)

### Issue description

Input Map - Changing Value and pressing outside the field crashing Godot Engine

### Steps to reproduce

open input map, add a few fields, 
try renaming, don't press enter, instead click outside the field.
then engine will crash.

### Minimal reproduction project (MRP)

- minimum project requirement, empty project will do.

### PR DESCRIPTION
**Pull request by bruvzg**
Should fix https://github.com/godotengine/godot/issues/86612, by preventing tree update inside `propagate_mouse_event`, but I'm not sure if this is the best fix (tree internal login probably should be changed to be more robust).

### CODE REVIEW

File: editor/action_map_editor.cpp [hunk 1]
```diff
@@ -429,6 +429,7 @@ void ActionMapEditor::update_action_list(const Vector<ActionInfo> &p_action_info
 		// Update Tree...
 
 		TreeItem *action_item = action_tree->create_item(root);
+		ERR_FAIL_NULL(action_item);
```
Comment (bruvzg) [inline editor/action_map_editor.cpp:432]: This should never trigger, added just in case.

Comment (KoBeWi) [reply editor/action_map_editor.cpp:432]: I know this comes from the issue, but there are more potentially crashing spots like that. Kinda odd to handle only this one specifically.

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -4439,6 +4439,14 @@ void Tree::item_edited(int p_column, TreeItem *p_item, MouseButton p_custom_mous
 	if (p_item != nullptr && p_column >= 0 && p_column < p_item->cells.size()) {
 		edited_item->cells.write[p_column].dirty = true;
 	}
+	if (blocked > 0) {
+		callable_mp(this, &Tree::emit_item_edited).call_deferred(p_custom_mouse_index);
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:4443]: This either needs a comment, because being blocked does not prevent firing signal, or it should be solved in the problematic code by connecting with `CONNECT_DEFERRED`.

Comment (akien-mga) [reply scene/gui/tree.cpp:4443]: Poke.

Comment (akien-mga) [reply scene/gui/tree.cpp:4443]: Ping @bruvzg :)

Comment (bruvzg) [reply scene/gui/tree.cpp:4443]: `CONNECT_DEFERRED` might be enough, will check it a moment.

**Comment by bruvzg** [comment]
Updated to defer `ActionMapEditor::_action_edited` instead of changing tree.

**Review by KoBeWi — APPROVED** [review]
For some reason I can't reproduce the crash on master 🤔
The fix looks fine, assuming it's still relevant.

**Comment by akien-mga** [comment]
Thanks!
