### PR TITLE
Disable lock and group buttons when selected item is not CanvasItem

### LINKED ISSUE #88939: Cannot lock or group child nodes of ParallaxBackground
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - KDE neon 5.27 22.04 - X11 - GLES3 (Compatibility)

### Issue description

Normally one can click on a node with children in the Scene panel of the editor and then click the Lock or Group buttons to prevent selecting or moving those children independently:

image

However this isn't the case for the ParallaxBackground node... Clicking those buttons (which aren't disabled, so should be usable) doesn't do anything - child nodes (e.g. Sprite2D's) are still selectable and movable. I do notice however that the buttons are instead labelled Unlock and Ungroup...

image

If this is by design, I suggest making these buttons disabled for ParallaxBackground nodes to avoid confusion.

### Steps to reproduce

1. Open the 'parallax_test.zip' MRP below
2. Click and drag one of the icons in the editor to show they're not locked/grouped
3. Select the ParallaxBackground node in the Scene panel, then click on the Lock/Unlock and Group/Ungroup buttons
4. Notice the button icons don't change
5. Click and drag one of the icons in the editor to show they're still not locked/grouped

### Minimal reproduction project (MRP)

[parallax_test.zip](https://github.com/godotengine/godot/files/14426879/parallax_test.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
An idea of fix https://github.com/godotengine/godot/issues/88939 , should be merged after https://github.com/godotengine/godot/pull/89132 is merged.

The origin problem lies in the fact that ParallaxBackground is not a CanvasItem so the code did not do anything special to it, I guess if this need to be fixed, we can either hide the button or make it disable. 

This pr disables lock and group buttons when there's not any selected CanvasItem.

### CODE REVIEW

**Comment by Mickeon** [comment]
So what about Node3Ds?

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -3817,12 +3818,16 @@ void CanvasItemEditor::_draw_viewport() {
 		}
 	}
 
+	force_disable_lock_group = selection.size() == 1 && Object::cast_to<CanvasItem>(selection[0]) == nullptr;
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:3821]: The button will be always enabled when you select more nodes. You should check whether there is any CanvasItem in the selection.

Comment (jsjtxietian) [reply editor/plugins/canvas_item_editor_plugin.cpp:3821]: > when you select more nodes

Sorry I don't quite understand your suggestion. In this case `force_disable_lock_group` will be false and all buttons will act like before (before this pr is introduced).

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp:3821]: Yep, which means that you can select e.g. 2 plain Nodes and the button will be enabled and do nothing. So right now the PR only fixes a case for single selected node.

Comment (jsjtxietian) [reply editor/plugins/canvas_item_editor_plugin.cpp:3821]: I see, thanks!

**Comment by jsjtxietian** [comment]
I've rebased the code onto master, and added back `_update_lock_and_group_button` in `_draw_viewport`, to support update the lock button immediately after click it instead of next `selection_changed`.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -3827,6 +3831,8 @@ void CanvasItemEditor::_draw_viewport() {
 	transform.columns[2] = -view_offset * zoom;
 	EditorNode::get_singleton()->get_scene_root()->set_global_canvas_transform(transform);
 
+	_update_lock_and_group_button();
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:3834]: You could instead update when the button was pressed.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 3]
```diff
@@ -2665,11 +2667,13 @@ void CanvasItemEditor::_update_lock_and_group_button() {
 	}
 
 	lock_button->set_visible(!all_locked);
-	lock_button->set_disabled(selection.is_empty());
+	lock_button->set_disabled(!has_canvas_item || selection.is_empty());
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:2670]:
```suggestion
	lock_button->set_disabled(!has_canvas_item);
```
If selection is empty, `has_canvas_item` will always be false.

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 4]
```diff
@@ -7365,26 +7366,31 @@ void Node3DEditor::_refresh_menu_icons() {
...
-				all_grouped = false;
+			if (!all_locked && !all_grouped) {
 				break;
 			}
 		}
 	}
 
 	tool_button[TOOL_LOCK_SELECTED]->set_visible(!all_locked);
-	tool_button[TOOL_LOCK_SELECTED]->set_disabled(selection.is_empty());
+	tool_button[TOOL_LOCK_SELECTED]->set_disabled(!has_node3d_item || selection.is_empty());
```
Comment (KoBeWi) [inline editor/plugins/node_3d_editor_plugin.cpp:7386]: Same here.

**Comment by KoBeWi** [comment]
When you click non-CanvasItem node, the lock button opens:

https://github.com/godotengine/godot/assets/2223172/6e8f495a-b66e-446b-a2fb-8a9769258ee3

It's inconsistent with empty selection, which is closed, and also suggests that non-CanvasItems are "locked". Probably worth fixing.

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 3 above)
Comment (jsjtxietian) [reply editor/plugins/canvas_item_editor_plugin.cpp:2670]: Thanks！

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 2 above)
Comment (jsjtxietian) [reply editor/plugins/canvas_item_editor_plugin.cpp:3834]: But that means add update to four different places (lock, unlock, group, ungroup), and deal with UndoRedo carefully, IMHO it doesn't seem very neat

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp:3836]: And the alternative is updating the buttons every time the viewport redraws, for no reason, because most actions don't affect selection.

There are signals `item_lock_status_changed` and `item_group_status_changed`. You can just connect them to update buttons.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 5]
```diff
@@ -2657,19 +2658,24 @@ void CanvasItemEditor::_update_lock_and_group_button() {
...
 				}
+				has_canvas_item = true;
 			}
 			if (!all_locked && !all_group) {
 				break;
 			}
 		}
 	}
 
+	all_locked = all_locked && has_canvas_item;
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:2669]: `all_group` needs the same treatment.

Comment (jsjtxietian) [reply editor/plugins/canvas_item_editor_plugin.cpp:2669]: Done.

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 2 above)
Comment (jsjtxietian) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Done

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
