### PR TITLE
Overhaul and optimize Glow in the mobile renderer

### LINKED ISSUE #98531: Glow extremely Slow with Mobile on Android
### Tested versions

4.4.dev3, (Probably also 4.3)

### System information

Android 14, Samsung Galaxy A35

### Issue description

With Mobile Renderer enabled, I created an empty scene without a sky or anything, and just put a MeshInstance with a Cube Mesh and a Standard Emissive Material. It renders with smooth 120 FPS on my Galaxy A35. 

Then I enable Glow to actually see some glowing. It works on my PC, but on my phone:

1. The glow is not visible, as if it is turned off somehow.
2. FPS drops from 120 to 37...

Then I switched to Compatibility Renderer:
1. Glow is visible now
2. FPS is back to 120

If I do the same in Unreal Engine, no matter if I use GLES3 or Vulkan renderer there, it is always at 60 FPS and Glow is always working.

So there must be a huge performance issue with turning on Glow/Postprocessing with Mobile Renderer. 

I read an official article that SSGI and other effects are not optimized in Godot yet and will improved with upcoming releases, so hopefully Glow will be part of that upcoming optimizations? 

Anyway, thanks for your hard work on the engine, just wanted to report this and hope it gets fixed soon. (Still kinda hope there is just a setting I did wrong).

### Steps to reproduce

I attached MRP. Basically just make an emissive cube, run on low/mid-range android device with Mobile compared to Compatibility renderer.

### Minimal reproduction project (MRP)

[slowglowmrp.zip](https://github.com/user-attachments/files/17526220/slowglowmrp.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Depends on https://github.com/godotengine/godot/pull/109971

Fixes: https://github.com/godotengine/godot/issues/98531

### TLDR

This PR overhauls our approach to glow to use something that is both higher quality and more suitable for mobile devices. On the tested devices the performance improvement is upwards of 2X on all tested devices and reaches over 7X on one device. 

### Notes

The way glow works in master is first, we downsample and blur the screen using a two pass guassian blur. Using 2 passes allows us to take `kernel_size * 2` samples instead of `kernel_size * kernal_size`. Then, in the tonemap shader, we gather all the glow levels (each mip level of the texture), multiply them by their level amount and add them together.

There are three bad things about this approach:
1. The number of render passes is 2 * the number of levels (this comes with a huge performance penalty on Mali devices and Apple devices)
2. The tonemap shader does up to 7 texture fetches for each pixel in the screen
3. Despite glow being a relatively low frequency effect, and the first couple of levels are so sharp you can't really even notice them, yet they are by far the most expensive. 

Profiling showed that texture reads were the biggest problem for glow. Most of those texture reads come from the tonemap pass. When using all 7 levels we do 7 texture reads per pixel in the tonemap pass and 6.6 texture reads per pixel during downsampling. If we eliminate the first level and skip to level 2, then we can bring that down to 1.6 texture reads per pixel during downsampling. That's a nice improvement, but it still leaves 8.6 samples per pixel because of the gather. Accordingly, we need to somehow move the gather into a lower resolution pass so we reduce the number of samples taken at full res. 

In the end, I prioritized reducing texture reads over reducing passes. I use the technique described in https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-20-66/siggraph2015_2D00_mmg_2D00_marius_2D00_notes.pdf with a few key optimizations. 

Broadly, the technique downsamples in a single pass using an optimized blur that is somewhere between a box blur and a gaussian blur. It relies on the fact that repeated applications of a box blur add up to a guassian blur. What we do is downsample with the blur to our target level, then we upsample back up to full res, adding our original blurred textures in as we go. This takes `2 * levels -1` number of render passes, but allows us to do the gather as we upsample. So all the gather texture reads are done at low res. This massively reduces the sample count per pixel. With 7 levels using this technique we do only one sample in the tonemap shader and we do 3.0 samples per pixel during the downsample and upsample passes combined for a total of 4 samples per pixel. 

I then also did a few other optimizations:
1. Split the tonemap shader into one for Forward+ and one for Mobile. The one for Mobile is simplified and uses specialization constants to removed unused features. This significantly improved the speed of the tonemap pass. Even when not using Glow
2. We use quarter-res for level 1 instead of half res. This cuts the number of samples per pixel down to 1.75. Moving level 1 to quarter res also had the side-effect of making the blur radius consistent with the Forward+ renderer despite using a smaller radius blur.
3. We can skip sampling the original texture when the glow level for that level is 0. We still need to do the upsample and downsample passes to keep the size and quality of the blur consistent. 
4. Use the super optimized blur kernels from https://www.shadertoy.com/view/mdsyDf. This minimizes the number of texture samples we use. As a follow up, we could consider using less-optimized kernels to get better quality on desktop devices. That shadertoy includes a few options including the ones from https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-20-66/siggraph2015_2D00_mmg_2D00_marius_2D00_notes.pdf and [Call of Duty](https://www.iryoku.com/next-generation-post-processing-in-call-of-duty-advanced-warfare/)

## Quality

_Forward+_
Screenshot from 2025-09-01 14-30-07

_Mobile: Before_
Screenshot from 2025-09-01 14-32-25

_Mobile: After_
Screenshot from 2025-09-01 18-50-59

## Performance

The performance of each depends in part on the screen resolution

**Adreno 640 (1080 x 2280)**

| Glow        | default | level 3 only | all levels |
|--------|---------|--------------|------------|
| Before |  2.6ms       | 2.6ms             |  3.2ms         |
| After  | 1.35ms     |1.3ms            | 1.4ms |
| Tonemap       |  |  |  |
| Before | 7.4ms        |  6.7ms            | 8.8ms           |
| After  | 1.5ms        | 1.5ms     | 1.5ms  |
| Total  | 3.5X       | 3.3X     | 4.1X |

**Mali G710 (1080 x 2400)**

Weirdly the Mali G710 is a much more powerful device (Pixel 7 vs Pixel 4). But the Adreno 640 wins here because Adreno devices can basically turn off TBDR rendering and go fully immediate mode for workloads like this. 

| Glow        | default | level 3 only | all levels |
|--------|---------|--------------|------------|
| Before | 3.8ms        | 3.2ms             | 4.2ms           |
| After  | 1.75ms      |  1.3ms          |2.25ms   |
| Tonemap       |  |  | |
| Before | 3.5ms        | 3.2ms             |  4.4ms          |
| After  | 1.6ms        |    1.3ms           |1.9ms |
| Total  | 2.2X        | 2.46X     | 2.1X  |

As you can see, performance on Mali devices scales very closely with the number of render passes used. 

**Adreno 530 (1080 x 1920)**

| Glow        | default | level 3 only | all levels |
|--------|---------|--------------|------------|
| Before |  3.5ms       |  3.45ms            |  3.6ms          |
| After  |  1.15ms     |  1.1ms          | 1.23ms  |
| Tonemap       |  |  |  |
| Before |6.0ms      |  5.7ms          | 9.25ms           |
| After  | 2.3ms     | 2.25ms              | 2.2ms |
| Total  | 2.75X       |  2.73X    | 3.75X |

**Intel Xe graphics (1152 x 648)**

Before (all levels, glow): 0.24 ms
Before (all levels, tonemap): 0.5 ms
Before (glow off, tonemap only): 0.19 ms

After (all levels, glow): 0.13 ms
After (all levels, tonemap: 0.14 ms
After (glow off, tonemap only): 0.12 ms

Forward+ (all levels, glow): 0.4 ms
Forward+ (all levels, tonemap): 0.45 ms

I'm surprised to see such a big win here!

**M2 MBP (2400 x 1366 + 2.0x scale_3d)** 

| Glow        | default | level 3 only | all levels |
|--------|---------|--------------|------------|
| Before | 4.0ms        | 2.4ms             | 4.1ms           |
| After  | 0.49ms      |  0.42ms          | 0.55ms   |
| Tonemap       |  |  |  |
| Before | 1.58ms        | 1.26ms             |  3.15ms          |
| After  | 0.47ms        |    0.41ms           |0.44ms |
| Total  | 5.8X       | 4.4X     | 7.32X  |

Note, the timings for glow were pretty variable and could swing by about 50% between runs. I tried to take the worst runs from the after and the best runs from before to keep things fair. In any case, the new code is consistently an order of magnitude faster while the tonemapping code is more like 3x faster. 

### TODO

- [x] Clean up some code (Mip1 downsample is no longer used)
- [x] Further test the MIP2 downsampling
- [x] Do one final hail mary test to see if I can drop the cost on Mali
- [x] Test on more devices (iphone, macos especially since they are TBDR + high end GPU)

### Notes

Using the sampling functions from https://www.shadertoy.com/view/mdsyDf
Using the technique from  https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-20-66/siggraph2015_2D00_mmg_2D00_marius_2D00_notes.pdf

### Next Steps

In another PR, we can copy this approach for both the compatibility renderer and the Forward+ renderer. The compatibility renderer approach is already based on https://community.arm.com/cfs-file/__key/communityserver-blogs-components-weblogfiles/00-00-00-20-66/siggraph2015_2D00_mmg_2D00_marius_2D00_notes.pdf, but we can optimize it a lot more

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 1]
```diff
@@ -709,19 +755,16 @@ void RendererSceneRenderRD::_render_buffers_post_process_and_tonemap(const Rende
 		}
 
 		if (rb->get_use_debanding()) {
-			if (dest_fb_format >= RD::DATA_FORMAT_R8_UNORM && dest_fb_format <= RD::DATA_FORMAT_A8B8G8R8_SRGB_PACK32) {
-				tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_8_BIT;
-			} else if (dest_fb_format >= RD::DATA_FORMAT_A2R10G10B10_UNORM_PACK32 && dest_fb_format <= RD::DATA_FORMAT_A2B10G10R10_SINT_PACK32) {
-				tonemap.debanding_mode = RendererRD::ToneMapper::TonemapSettings::DebandingMode::DEBANDING_MODE_10_BIT;
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:740]: I'm very sad to delete this right after Allen added it, but with https://github.com/godotengine/godot/pull/109971 we no longer need to consider the 10 bit case, so its best for us to remove the code path to simplify things

File: servers/rendering/renderer_rd/effects/copy_effects.cpp [hunk 2]
```diff
@@ -53,8 +53,10 @@ CopyEffects::CopyEffects(bool p_prefer_raster_effects) {
 		Vector<String> blur_modes;
 		blur_modes.push_back("\n#define MODE_MIPMAP\n"); // BLUR_MIPMAP
 		blur_modes.push_back("\n#define MODE_GAUSSIAN_BLUR\n"); // BLUR_MODE_GAUSSIAN_BLUR
-		blur_modes.push_back("\n#define MODE_GAUSSIAN_GLOW\n"); // BLUR_MODE_GAUSSIAN_GLOW
-		blur_modes.push_back("\n#define MODE_GAUSSIAN_GLOW\n#define GLOW_USE_AUTO_EXPOSURE\n"); // BLUR_MODE_GAUSSIAN_GLOW_AUTO_EXPOSURE
+		blur_modes.push_back("\n#define MODE_GLOW_DOWNSAMPLE\n"); // BLUR_MODE_GAUSSIAN_GLOW_DOWNSAMPLE
+		blur_modes.push_back("\n#define MODE_GLOW_DOWNSAMPLE\n#define MODE_GLOW_GATHER\n"); // BLUR_MODE_GAUSSIAN_GLOW_MIP1
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/effects/copy_effects.cpp]: `BLUR_MODE_GAUSSIAN_GLOW_MIP1` can be deleted outright

**Review by beicause — COMMENTED** [review]
`tonemap.glsl` and `tonemap_mobile.glsl` seem to have many duplicate code. Should there be a `tonemap_inc.glsl`? which can make it easier for other PRs (like #106940) to rebase.

**Comment by clayjohn** [comment]
> `tonemap.glsl` and `tonemap_mobile.glsl` seem to have many duplicate code. Should there be a `tonemap_inc.glsl`? which can make it easier for other PRs (like #106940) to rebase.

No, I intentionally duplicated the code since I expect these shaders to diverge even more as time goes on. Trying to share code between them is what led us to leaving a huge amount of performance on the table. This is a case where having optimized code for each platform is worthwhile and saves us literally milliseconds per frame.

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp (hunk 1 above)
Comment (allenwp) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:740]: Hah! Don't be very sad -- less code is great!

But I think this code path still happens in mobile when HDR 2D is disabled and SMAA is enabled?

**Comment by allenwp** [comment]
> > `tonemap.glsl` and `tonemap_mobile.glsl` seem to have many duplicate code. Should there be a `tonemap_inc.glsl`? which can make it easier for other PRs (like #106940) to rebase.
> 
> No, I intentionally duplicated the code since I expect these shaders to diverge even more as time goes on. Trying to share code between them is what led us to leaving a huge amount of performance on the table. This is a case where having optimized code for each platform is worthwhile and saves us literally milliseconds per frame.

Why aren't specialization constants an option for this case? I suspect that specialization constants will be added at some point in the near future anyway to address performance issues from branching, even if we are using two entirely separate shaders. (In the past, I've seen a measurable performance gain when using the Linear tonemapper from simply turning:

```
	if (params.tonemapper == TONEMAPPER_LINEAR) {
		return color;
	} else if (params.tonemapper == TONEMAPPER_REINHARD) {
		return tonemap_reinhard(max(vec3(0.0f), color), white);
	} else if (params.tonemapper == TONEMAPPER_FILMIC) {
		return tonemap_filmic(max(vec3(0.0f), color), white);
	} else if (params.tonemapper == TONEMAPPER_ACES) {
		return tonemap_aces(max(vec3(0.0f), color), white);
	} else { // TONEMAPPER_AGX
		return tonemap_agx(color);
	}
```
into:
```
		return color;
```
(which is exactly how this would compile with specialization constants, if I understand correctly)

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:740]: I hope not! But I'll have to check. I need to rebase to get the SMAA changes

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

I noticed an issue with 3D resolution scaling on macOS + Metal (or MoltenVK) though. The glow buffer doesn't appear to be scaled, so it will appear at the wrong position if the resolution scale isn't `1.0`. Note that this issue does not occur if using MetalFX Spatial, only with Bilinear (FSR 1.0 isn't supported on Mobile).

**Testing project:** [test_glow_mobile.zip](https://github.com/user-attachments/files/22152576/test_glow_mobile.zip)

Scale 0.25 | Scale 1.0 | Scale 2.0
-|-|-
 |  | 

Scale 0.25 with MetalFX Spatial (looks correct):

**Comment by allenwp** [comment]
> > > `tonemap.glsl` and `tonemap_mobile.glsl` seem to have many duplicate code. Should there be a `tonemap_inc.glsl`? which can make it easier for other PRs (like #106940) to rebase.
> > 
> > 
> > No, I intentionally duplicated the code since I expect these shaders to diverge even more as time goes on. Trying to share code between them is what led us to leaving a huge amount of performance on the table. This is a case where having optimized code for each platform is worthwhile and saves us literally milliseconds per frame.
> 
> Why aren't specialization constants an option for this case?

Whoops, I hadn't looked into this PR thoroughly enough: I see now that specialization constants were added **AND** `tonemap.glsl` was split into two.

I presume there's a substantial reason that specialization constants weren't an option for optimizations that prompted splitting `tonemap.glsl` into two files?

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp (hunk 1 above)
Comment (allenwp) [reply servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:740]: I've posted an MRP for this issue in the HDR 2D PR: https://github.com/godotengine/godot/pull/109971#issuecomment-3316018457

**Comment by allenwp** [comment]
With the Mobile renderer, the first level seems to add a lot of jaggies. This is especially the case with HDR 2D enabled:

Settings | Image
-|-
image|image

MRP: [glow-test.zip](https://github.com/user-attachments/files/22605357/glow-test.zip)

File: servers/rendering/renderer_rd/shaders/effects/tonemap_mobile.glsl [hunk 3]
```diff
@@ -0,0 +1,779 @@
...
+#ifndef SUBPASS
+	// Glow
+	if (use_glow && !glow_mode_mix) {
+		vec3 glow = gather_glow() * params.glow_intensity * params.luminance_multiplier;
+		if (use_glow_map) {
+			glow = mix(glow, texture(glow_map, uv_interp).rgb * glow, params.glow_map_strength);
+		}
+
+		// Left in on the understanding that glow would be moved to be before tonemapping
+		// If that doesn't happen, this should be moved to the final glow upsample stage so it is done at a lower resolution.
```
Comment (allenwp) [inline servers/rendering/renderer_rd/shaders/effects/tonemap_mobile.glsl]: As described in #13181 (section 3), soft light must be applied after tonemapping. Additionally, my proposed "legacy mode" requires glow to be applied after tonemapping to match existing behaviour in Godot 4.5 and earlier.

**Comment by allenwp** [comment]
I'm struggling to review the code changes of this PR because I'm unfamiliar with both the existing and new glow gathering code. This is a "me" problem and not a problem with this PR.

...But I mention it, because it leads me to some thoughts that I figure are worth mentioning just in case it's helpful:

This PR seems to be a combination of:

- Swapping out the Mobile glow gather implementation and changing how the rendering passes work in relation to this
- Separating `tonemap.glsl` into two files
- Adding specialization constants

This is pie-in-the-sky thinking, but an alternative approach may be to add specialization constants to the tonemap process in a separate PR. This PR could explore specialization constants for both Forward+ and Mobile on different mobile and desktop hardware.

There is also a part of the Godot PR process that I struggle with in general: although a single commit is best for merging, it makes things harder to review for a person not very familiar with the code when a PR combines multiple changes, like this one.

Anyway, not sure if my thoughts are helpful. I understand people only have so much time to work on these things and there is some efficiency to be gained in the development process by bulking multiple changes into one commit. I'm not sure if the extra complexity during the review process balances that or if there is risk introduced by bugs that couldn't be caught during review due to the extra complexity of the single commit during the review process. (This is likely a discussion that is beyond this PR?)

**Comment by allenwp** [comment]
Oh! I've been so focused on finding any outstanding issues that I failed to voice my positive thoughts about this PR:

- Changes the way that glow is gathered and passes are handled on Mobile to minimize texture reads and greatly improve performance on devices that can't read these textures quickly: 👍👍😄😄
- Adds specialization constants to resolve issues with insane amounts of branching that saturates ALUs: 👍👍😄😄

These changes in this PR are extremely valuable and I'm really looking forward to having these merged in! It will be a game changer in performance on mobile!

**Comment by allenwp** [comment]
> With the Mobile renderer, the first level seems to add a lot of jaggies. This is especially the case with HDR 2D enabled
> 
> MRP: [glow-test.zip](https://github.com/user-attachments/files/22605357/glow-test.zip)

What do people think of getting rid of Level 1 for Mobile and Forward+ altogether? Even if it's not as expensive on desktop GPUs, I suspect it still has a cost that almost nobody benefits from?

Just spit-balling ideas here. Other than this, I'm not sure how this issue can be addressed...

**Comment by allenwp** [comment]
[Here's a quick comparison](https://github.com/allenwp/godot-glow-comparison) of this PR with Godot 4.5 for all levels, 1 through 7:

| Mobile HDR 2D (this PR) | Mobile HDR 2D (4.5) | Forward+ HDR 2D (4.5)
| --- | --- | ---
 | mobile-hdr2d | 4.5_mobile-hdr2d | 4.5_forward-hdr2d
 | mobile-hdr2d | 4.5_mobile-hdr2d | 4.5_forward-hdr2d
 | mobile-hdr2d | 4.5_mobile-hdr2d | 4.5_forward-hdr2d
 | mobile-hdr2d | 4.5_mobile-hdr2d | 4.5_forward-hdr2d
 | mobile-hdr2d | 4.5_mobile-hdr2d | 4.5_forward-hdr2d
 | mobile-hdr2d | 4.5_mobile-hdr2d | 4.5_forward-hdr2d
 | mobile-hdr2d | 4.5_mobile-hdr2d | 4.5_forward-hdr2d

| Mobile (this PR) | Mobile (4.5) | Forward+ (4.5)
| --- | --- | ---
 | mobile | 4.5_mobile | 4.5_forward
 | mobile | 4.5_mobile | 4.5_forward
 | mobile | 4.5_mobile | 4.5_forward
 | mobile | 4.5_mobile | 4.5_forward
 | mobile | 4.5_mobile | 4.5_forward
 | mobile | 4.5_mobile | 4.5_forward
 | mobile | 4.5_mobile | 4.5_forward

`*` Note: #110671 will help fix some of the issues shown when HDR 2D is disabled.

The tool is fully automated, so it's easy to generate more images. Takes no time at all to try other configurations, just ask if you want to see.

This test does highlight that level 1 is the only regression in this PR...

**Comment by clayjohn** [comment]
>This test does highlight that level 1 is the only regression in this PR...

I don't intend to make any improvements to glow level 1. I searched Godot projects on Github and couldn't find any that relied on level 1. In practice it is kind of useless because the kernel is so narrow that it doesn't look like anything. Ironically level 1 is the most expensive to compute because it is reading from the highest res source, and writing out the highest number of pixels. 

What this PR does to avoid that cost is simply downsample instead of blur level 1. So what you are comparing is a raw downsampled image to one that has already had an expensive layer of blur applied. They are not intended to match at all

**Comment by allenwp** [comment]
> What this PR does to avoid that cost is simply downsample instead of blur level 1. So what you are comparing is a raw downsampled image to one that has already had an expensive layer of blur applied. They are not intended to match at all

This makes sense and matches my understanding.

This is why I suggested we maybe remove level 1 entirely, since it adds jaggies and doesn't work as expected. To do this, I guess we could hide level 1 in the editor and force its intensity to always `0.0`, even if a script tries to set it to something else?

My thought is that if level 1 is left in this state, it will both appear as a bug and also introduce risk of games being made to look worse if upgraded from a previous version that uses level 1 in the blur effect.

There is also a possibility that in some scenes it looks acceptable, but other scenes show the jaggies... So glow is made more difficult to use because jaggies might appear in scenes other than the one the glow was initially configured for. An example is when you have rectangular, axis-aligned objects in your setup scene that only rotate off axis in other scenes.

(Said differently, I'm concerned that this level 1 behaviour produces a bad user experience.)

**Comment by clayjohn** [comment]
> This is why I suggested we maybe remove level 1 entirely, since it adds jaggies and doesn't work as expected. To do this, I guess we could hide level 1 in the editor and force its intensity to always `0.0`, even if a script tries to set it to something else?

I have no problem doing that!

**Comment by allenwp** [comment]
> > This is why I suggested we maybe remove level 1 entirely, since it adds jaggies and doesn't work as expected. To do this, I guess we could hide level 1 in the editor and force its intensity to always `0.0`, even if a script tries to set it to something else?
> 
> I have no problem doing that!

Let's go with that approach then! One other wrinkle is how the "normalize" function works: level 1 should not contribute to the calculation of normalized levels, in case it's been set through script or by a resource that was saved with an earlier version of Godot. I think that should handle all the edge cases to make this a good user experience...

**Comment by mrjustaguy** [comment]
I'm Strongly against the opinion of removing level 1 glow as it does Have uses (at least in Forward+)

Some very tiny very bright objects for example get a glow only using level 1 glow and that can be very much desired (again F+ only, I don't know about other renderers)

If anything I'd just document the fact that it's the most expensive level and that it should be avoided if you're working on/for weaker hardware.

**Comment by clayjohn** [comment]
> I'm Strongly against the opinion of removing level 1 glow as it does Have uses (at least in Forward+)
> 
> Some very tiny very bright objects for example get a glow only using level 1 glow and that can be very much desired (again F+ only, I don't know about other renderers)
> 
> If anything I'd just document the fact that it's the most expensive level and that it should be avoided if you're working on/for weaker hardware.

I think you are misunderstanding what Allen is suggesting. Level 1 will still be calculated. Allen is suggesting removing the slider so level one can't be added to the final visual output, but it is still used in the _intermediate_ blur. So very tiny bright objects will still be picked up by glow, but you won't be able to add the jaggie infested single pixel width layer on top of the rest of the glow. 

Take a look at his screenshots above to see what he is talking about. 

Also this PR is for the mobile renderer, so your concern about the Forward+ renderer is totally off topic

**Comment by mrjustaguy** [comment]
if the removal of L1 is only for mobile I'm fine, but idk how that'd go from a UI stand point, it'd be a little odd starting from L2, but i suppose no biggie.

**Comment by clayjohn** [comment]
@allenwp Rebased and pushed changes to implement the changes you made recently to the tonemapper. 

I ended up catching a bug in the sampling I used that was responsible for making the jaggies extra bad at level 1. They are now a lot less bad (still noticeable on single pixel features and thin diagonal lines), but probably tolerable for a lot of games. So I opted to change the default amount for level 1 to 0, but I did not remove it altogether. I think we should leave it in now and see if people complain. 

~Other than that, I think this PR is ready to go! _edit: not quite yet, somehow I missed Calinou's review comment this whole time_~

_edit edit: This should be ready to merge now!_

**Comment by allenwp** [comment]
In the latest update, not only were the glow level defaults changed, but `glow_hdr_bleed_threshold` was also changed from `1.0` to `0.0`. This changes glow from being something that is is designed to only take effect when values are becoming brighter than the display can reproduce to being something that is more like a bloom effect. HDR Scale does have an impact on this, but this is a substantial default change and I'm curious to know why this change was introduced. Maybe the HDR threshold default change would be better for a different PR?

**Comment by clayjohn** [comment]
> In the latest update, not only were the glow level defaults changed, but `glow_hdr_bleed_threshold` was also changed from `1.0` to `0.0`. This changes glow from being something that is is designed to only take effect when values are becoming brighter than the display can reproduce to being something that is more like a bloom effect. HDR Scale does have an impact on this, but this is a substantial default change and I'm curious to know why this change was introduced. Maybe the HDR threshold default change would be better for a different PR?

2 reasons:
1. Its more "correct", the method of thresholding before blurring and accumulating blur is really dated and never had any physical basis. Setting the threshold to 0.0 looks better in almost every situation. So this is a nice change to go along with our shift to accumulating in linear space and defaulting to screen mode instead of softlight. 
2. The threshold was creating a lot of unnecessary aliasing

I'd prefer to make the change now while we are changing other defaults.

**Comment by clayjohn** [comment]
Pushed another update after a discussion with Allen on Rocketchat. I brought back 10 bit debanding in the mobile tonemap shader when SMAA is in use. In that case the output of the tonemap shader goes into an intermediate RGB10A2 buffer, so debanding needs to be 10 bit. 

I also introduced debanding to the upscale/gather pass for glow. An unfortunate side effect of this approach is that accumulating glow in multiple 10 bit passes is prone to banding. Previously we accumulated glow in the tonemap shader, so the accumulation was done with full 32 bit floating point values, so banding wasn't as prevalent. Any banding that was created was dealt with by the normal debanding pass in the tonemap shader. The impact of debanding can be noticeable when the intensity of glow is very high since glow intensity is a straight multiplier to the final result of the glow. IMO this is an acceptable tradeoff for people who need glow and also need to use RGB10A2 buffers. The only other alternative is to switch to full RGBA16 for glow.

**Comment by allenwp** [comment]
> I ended up catching a bug in the sampling I used that was responsible for making the jaggies extra bad at level 1. They are now a lot less bad (still noticeable on single pixel features and thin diagonal lines), but probably tolerable for a lot of games.

I'm having a hard time seeing how they're better. This is what I see with HDR 2D disabled, HDR Threshold `1.0` for stable comparison with Oct 10 screenshot.

| Mobile (this PR Oct 10) | Mobile (this PR Oct 24) | Mobile (master) 
| --- | --- | ---
 | mobile | image | image

I've tripple checked and I still get the same result from the windows build artifact from the checks page of this PR. If it's not possible to further improve, it's still probably best to hide and disable level one for Mobile for the reasons previously discussed.

(Also, I found that the screenshots weren't saving correctly for my automated tests above, but I think it's specific to HDR 2D. Maybe there's something wrong with the image saver(???) Regardless, I don't have time to fix that, so I've saved these two new comparisons manually with good 'ol print-screen instead.)

And I've got to head off for vacation and won't be around to do any testing for a few weeks. Good luck!

**Edit:** Oh, one last thing: Feel free to include #111333 in this PR if you'd like. Might be better than making a change later that is nothing more than a variable rename.

👋

**Comment by clayjohn** [comment]
> I'm having a hard time seeing how they're better. This is what I see with HDR 2D disabled, HDR Threshold 1.0 for stable comparison with Oct 10 screenshot.

If you swap between your images you can see a huge difference! But more importantly, if you look at it overlaid on actual game content with multiple layers the difference is much more apparent. The jaggies line up better with the underlying geometry and blend into the other layers better. On larger geometry its not even noticeable at reasonable settings. 

Now, if you stretch things to their limits only use level one, then ya, it looks bad. But I'm not really worried about people doing that. The important thing is that it is no longer something that is guaranteed to look bad no matter what. With the earlier draft of this PR it was always worse to use level 1 than to not use it. That isn't true anymore, so I think it is fine to keep. 

If you can't tell, I want to avoid breaking compatibility more than I already have. That change is a compat breakage bigger than everything else in this PR combined, so it should only be done with extreme caution. Since it is no longer absolutely necessary, we shouldn't do it. If users complain a lot during the beta phase we can re-evaluate removing it.

File: servers/rendering/renderer_rd/effects/tone_mapper.cpp [hunk 4]
```diff
@@ -182,43 +213,141 @@ void ToneMapper::tonemapper(RID p_source_color, RID p_dst_framebuffer, const Ton
...
+	tonemap_mobile.push_constant.src_pixel_size[0] = 1.0 / p_settings.texture_size.x;
+	tonemap_mobile.push_constant.src_pixel_size[1] = 1.0 / p_settings.texture_size.y;
+	tonemap_mobile.push_constant.glow_intensity = p_settings.glow_intensity;
+	tonemap_mobile.push_constant.glow_map_strength = p_settings.glow_map_strength;
+
+	tonemap_mobile.push_constant.exposure = p_settings.exposure;
+	tonemap_mobile.push_constant.white = p_settings.white;
+	tonemap_mobile.push_constant.luminance_multiplier = p_settings.luminance_multiplier;
+
+	uint32_t spec_constant = 0;
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/effects/tone_mapper.cpp:327]: Nitpick, but as discussed on RC, I think we should comment out or disable these seeing they are not supported when a subpass is used. They are hardcoded to false in `RendererSceneRenderRD::_post_process_subpass` but for future people looking at this, it may be clearer to see here that these settings are only supported with a full pass.

**Review by BastiaanOlij — APPROVED** [review]
This result looks amazing! Defo a huge improvement for the mobile renderer.

File: servers/rendering/renderer_rd/effects/tone_mapper.cpp (hunk 4 above)
Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/effects/tone_mapper.cpp:327]: (well comment out the lines from the code block starting at line 328, dang preview positioning :P

Comment (clayjohn) [reply servers/rendering/renderer_rd/effects/tone_mapper.cpp:327]: Done!

**Comment by Repiteo** [comment]
Thanks!

**Comment by dsnopek** [comment]
I just finished bisecting and it looks like this PR broke foveated rendering with OpenXR and the Vulkan Mobile renderer. The project I'm testing doesn't have glow enabled, so it's probably some random collateral damage, although, from looking at the diff I'm not entirely sure the cause yet

**Comment by clayjohn** [comment]
@dsnopek Could it be a hardcoded framebuffer format somewhere?

**Comment by mmMarzban** [comment]
No difference for me. Still a poor performance on mobile.

**Comment by allenwp** [comment]
> But more importantly, if you look at it overlaid on actual game content with multiple layers the difference is much more apparent. The jaggies line up better with the underlying geometry and blend into the other layers better. On larger geometry its not even noticeable at reasonable settings.

Ah, I think I might have misunderstood the change that happened between the Oct 10 and Oct 24 versions of this PR. The change that was made was to do with how level 1 was blended with the rest and not to do with the generation of the level 1 texture?

> If you swap between your images you can see a huge difference!

This is the part where I think the misunderstanding presented itself, as there is only a minor difference between the two versions of the PR:

| Mobile (this PR Oct 10) | Mobile (this PR Oct 24)
| --- | ---
 | mobile | image

**Comment by allenwp** [comment]
> > But more importantly, if you look at it overlaid on actual game content with multiple layers the difference is much more apparent. The jaggies line up better with the underlying geometry and blend into the other layers better. On larger geometry its not even noticeable at reasonable settings.
> 
> Ah, I think I might have misunderstood the change that happened between the Oct 10 and Oct 24 versions of this PR. The change that was made was to do with how level 1 was blended with the rest and not to do with the generation of the level 1 texture?

Cleared this up in the rendering meeting: it was the change of threshold default that was supposed to help with some scenes' jaggies, but this change of default has been reverted so we're back where we started with jaggies generated from level 1.

clayjohn and I both don't have strong feelings regarding the behaviour of level 0 after this PR, so we're leaving it as-is and see if people report it as a serious usability issue.

File: servers/rendering/renderer_rd/effects/tone_mapper.cpp [hunk 5]
```diff
@@ -35,34 +35,62 @@
...
+		if (!RendererCompositorRD::get_singleton()->is_xr_enabled()) {
+			tonemap_mobile.shader.set_variant_enabled(TONEMAP_MOBILE_MODE_NORMAL_MULTIVIEW, false);
+			tonemap_mobile.shader.set_variant_enabled(TONEMAP_MOBILE_MODE_1D_LUT_MULTIVIEW, false);
+			tonemap_mobile.shader.set_variant_enabled(TONEMAP_MOBILE_MODE_SUBPASS_MULTIVIEW, false);
+			tonemap_mobile.shader.set_variant_enabled(TONEMAP_MOBILE_MODE_SUBPASS_1D_LUT_MULTIVIEW, false);
+		}
+
+		tonemap_mobile.shader_version = tonemap_mobile.shader.version_create();
+
+		for (int i = 0; i < TONEMAP_MODE_MAX; i++) {
```
Comment (Alex2782) [inline servers/rendering/renderer_rd/effects/tone_mapper.cpp:65]:
```suggestion
		for (int i = 0; i < TONEMAP_MOBILE_MODE_MAX; i++) {
```

Currently not critical, but should be adjusted at some point (`enum TonemapMode` and `enum TonemapModeMobile` currently have 8 values)

Comment (clayjohn) [reply servers/rendering/renderer_rd/effects/tone_mapper.cpp:65]: Good catch. Indeed this works fine, but only by chance. If either enum changes it might break

Comment (DarioSamo) [reply servers/rendering/renderer_rd/effects/tone_mapper.cpp:65]: That was actually corrected in https://github.com/godotengine/godot/pull/114149
