### PR TITLE
Fixed the auto-completion bug in gdscript_editor

### LINKED ISSUE #37119: Properties don't appear in autocompletion outside functions
**Godot version:**
3.2

**Issue description:**
Ok
image
Not ok
image

(script extends Node2D-derived class)

### PR DESCRIPTION
**Pull request by theoway**
Issue referenced #37119 
**Bug:-**  `properties` wouldn't appear in auto-complete list when typing was done outside a function.
The reason was `bool _static` in `gdscript_editor` was calculated by checking if the `parser` node was inside a `function` . But this condition failed when the `parser` was outside a `function` , leading to wrong `bool` value in `_static`.
**Fix:-** Now the value for `_static` is calculated considering if the `parser` is inside a `function` or not.
**Result:-** `properties` are now listed in auto-complete list when typing outside a function.

*Bugsquad edit:* Fixes #37119.

### CODE REVIEW

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -2148,7 +2148,7 @@ static void _find_identifiers(const GDScriptCompletionContext &p_context, bool p
 	}
 
 	const GDScriptParser::ClassNode *clss = p_context._class;
-	bool _static = !p_context.function || p_context.function->_static;
+	bool _static = !p_context.function ? false : p_context.function->_static;
```
Comment (bojidar-bg) [inline modules/gdscript/gdscript_editor.cpp]: This is equivalent to `p_context.function && p_context.function->_static`, no?

Comment (theoway) [reply modules/gdscript/gdscript_editor.cpp]: The problem arises when p_context.function is a nullptr. In that case, p_context.function->_static will give erroneous/incorrect values. That's why, in the expression, it first checks if p_context.function is a nullptr

Comment (bojidar-bg) [reply modules/gdscript/gdscript_editor.cpp]: `&&` short-circuits: if `p_context.function` evaluates to false, `p_context.function->_static` will not be evaluated.

Comment (theoway) [reply modules/gdscript/gdscript_editor.cpp]: Oh yeah! How could I miss it, the short-circuiting thing. Thanks, I'll update it.

**Review by vnen — APPROVED** [review]
Usually you don't access properties outside functions, since you shouldn't rely on initialization order, but I guess it makes sense for `onready`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
