### PR TITLE
Fix using signals in lambda functions

### LINKED ISSUE #68907: Can't access node `Signal`s in lambda
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Fedora 37

### Issue description

Lambda functions cannot access the `Signal` objects declared in the current object script.

It is possible that this is intended behavior but it seems surprising to me, so I am assuming it is a bug.

### Steps to reproduce

```gdscript
extends Control

signal my_signal

func _ready():
	my_signal.connect(func(): print("Hello!"))
	
	# Works
	var test1 = func(): emit_signal("my_signal")
	test1.call()
	
	# Doesn't work
	var test2 = func(): my_signal.emit()
	test2.call()
```

Prints "Hello!" once and crashes on `my_signal.emit()` with "Invalid get index 'my_signal' (on base: 'Nil')."

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/68907

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Seems fine to me!

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -3009,6 +3012,8 @@ void GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode *p_ident
 			p_identifier->reduced_value = p_identifier->constant_source->initializer->reduced_value;
 			found_source = true;
 			break;
+		case GDScriptParser::IdentifierNode::MEMBER_SIGNAL:
+			[[fallthrough]];
 		case GDScriptParser::IdentifierNode::INHERITED_VARIABLE:
```
Comment (akien-mga) [inline modules/gdscript/gdscript_analyzer.cpp:3017]: Fallthrough doesn't need to be explicit if there's no specific code to run before the fallthrough.
```suggestion
		case GDScriptParser::IdentifierNode::MEMBER_SIGNAL:
		case GDScriptParser::IdentifierNode::INHERITED_VARIABLE:
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
