### PR TITLE
Fix orthogonal camera auto LOD calculation

### LINKED ISSUE #57404: Broken mesh in Orthogonal view
### Godot version

4.0.dev (2f57a11ed9b383706b72783c0d9b1e869774e08a)

### System information

MacOS 11.6

### Issue description

Meshes are broken in Orhtogonal view. Is it because of Auto LOD?

スクリーンショット 2022-01-30 0 41 46

### Steps to reproduce

Put on glb model in 3D scene, use orthogonal view.

### Minimal reproduction project

[broken_mesh.zip](https://github.com/godotengine/godot/files/7964026/broken_mesh.zip)

### PR DESCRIPTION
**Pull request by orosmatthew**
Resolves #57404

- Orthogonal camera used to take into account its distance from a mesh for auto LOD. 
- This should not be done as the distance does not affect how the mesh visually appears. 
- This was most obvious when using the "Preview Orthogonal" camera as it was placed ~2000m away and most meshes near the origin would then only show their lowest LOD.

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 1]
```diff
@@ -1081,6 +1081,9 @@ void RenderForwardClustered::_fill_render_list(RenderListType p_render_list, con
 					distance = -distance_max;
 				}
 
+				if (p_render_data->cam_ortogonal)
+					distance = 1.0;
```
Comment (Calinou) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1085]: Braces are required around one-line `if` statements:

```suggestion
				if (p_render_data->cam_ortogonal) {
					distance = 1.0;
				}
```

(Note for other reviewers: `cam_ortogonal` is the correct spelling for the variable; we should probably fix the typo in a separate PR.)

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 2]
```diff
@@ -1429,6 +1429,9 @@ void RenderForwardMobile::_fill_render_list(RenderListType p_render_list, const
 					distance = -distance_max;
 				}
 
+				if (p_render_data->cam_ortogonal)
+					distance = 1.0;
```
Comment (Calinou) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:1433]: Same as above:

```suggestion
				if (p_render_data->cam_ortogonal) {
					distance = 1.0;
				}
```

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp (hunk 1 above)
Comment (orosmatthew) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp]: Thanks for linking the guidelines, will take into account in the future, first time contributing

**Comment by JFonS** [comment]
Changes look good but the 3 commits should be squashed into a single one. Here's the PR workflow docs for more info: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

**Comment by orosmatthew** [comment]
Understood, should all be in one commit now

**Comment by fire** [comment]
Approved the cicd check.

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 3]
```diff
@@ -1081,6 +1081,10 @@ void RenderForwardClustered::_fill_render_list(RenderListType p_render_list, con
 					distance = -distance_max;
 				}
 
+				if (p_render_data->cam_ortogonal) {
+					distance = 1.0;
```
Comment (TokageItLab) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1085]: `1.0` seems like a magic number, but is it really reasonable? Shouldn't it be `0.0` or `distance_min`?

Comment (orosmatthew) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1085]: A couple of lines down, a call to mesh_surface_get_lod() is called which accepts distance * lod_distance_multiplier which then divides some values by this to get effective screen size. 0.0 would cause the highest LOD to always be shown and distance_min would still take into account the distance between the camera and the mesh which shouldn't happen in an orthogonal camera. 1.0 would then just effectively pass in the lod_distance_multiplier itself which is the size of an orthogonal camera or the fov of a perspective camera.

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
