### PR TITLE
ScriptEditor: Fix line number gutter drag select

### LINKED ISSUE #1247: Clicking the line number gutter in the script editor should select that line of code
**Describe the project you are working on:**
Very new to Godot, just starting on some simple tutorial projects.

**Describe the problem or limitation you are having in your project:**
No shortcut to select line of code in text editor.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
In most code editors, you can click on the line number to select that line. Godot's built-in editor lacks this feature, unless I am doing something incorrect.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Left click line number in text editor --> Line becomes highlighted and selected

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
N/A

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a very basic feature common to most editors that I am aware of. 

Thanks 🤠

### LINKED ISSUE #42722: 4.0 ScriptEditor Gutter Drag Selection Always Acts Like You're Holding Shift
**Godot version:**
4.0 / ca2c0b8937d287e608448a9a5ba553a8deaf46d9

**OS/device including version:**
Windows 10

**Issue description:**
When you click and drag on the line numbers gutter in the ScriptEditor in Godot 4.0, it adds to the selection from your previous cursor point instead of starting a new selection from the drag line's start.

Here is the current 4.0 behavior acting strange: 
4 0_bad

Here is the Godot 3.2 behavior working as expected:
3 2_good

This is related to the refactor from #31739

**Steps to reproduce:**

1. Open the Script Editor in any 4.0 project.
2. Click in the middle of any line to place the cursor there.
3. Click and drag the line number gutter of a different line. (See gifs above)
4. Notice the selection starts from the previous cursor point instead of starting from the dragged line number.

### PR DESCRIPTION
**Pull request by Devination**
Exposes TextEdit's selection as a protected variable so that CodeEdit can correctly set the selected lines when dragging on the line number gutter.

Fixes #42722
Also closes https://github.com/godotengine/godot-proposals/issues/1247

### CODE REVIEW

**Review by Paulb23 — CHANGES_REQUESTED** [review]
As you mentioned in the issue, the selection shouldn't really be exposed.`TextEdit` should have a API for this. I'm sure there's was a separate issue about this somewhere, but I can't seem to find it.

**Comment by Devination** [comment]
Just to be clear: you're thinking of dedicated public functions for set_selecting_line/column? That would match up nicely with the existing cursor_set_line/column functions.

**Comment by Devination** [comment]
I pushed updates using the --amend method as suggested in the documentation. In this update, I exposed the `Selection` struct for use with the new `set_selection_mode` function but kept TextEdit's `selection` variable private.

File: scene/gui/text_edit.h [hunk 1]
```diff
@@ -636,6 +638,15 @@ class TextEdit : public Control {
 	void set_right_click_moves_caret(bool p_enable);
 	bool is_right_click_moving_caret() const;
 
+	Selection::Mode get_selection_mode() { return selection.selecting_mode; };
+	void set_selection_mode(Selection::Mode p_mode, int p_line = -1, int p_column = -1);
+
+	int get_selection_line() { return selection.selecting_line; };
+	void set_selection_line(int p_line) { selection.selecting_line = p_line; };
```
Comment (Paulb23) [inline scene/gui/text_edit.h:645]: I can't see a use case for wanting to set `selection_line` or `selection_column` separately, without the mode, as `TextEdit` also changes these values, so would suggest removing these setters?

File: scene/gui/text_edit.h [hunk 2]
```diff
@@ -47,6 +47,44 @@ class TextEdit : public Control {
 		GUTTER_TPYE_CUSTOM
 	};
 
+	struct Selection {
+		enum Mode {
```
Comment (Paulb23) [inline scene/gui/text_edit.h:51]: Might be worth moving this out so we don't have to expose the entire struct, renaming it to `SelectionMode`

File: scene/gui/text_edit.cpp [hunk 3]
```diff
@@ -4333,6 +4333,16 @@ bool TextEdit::is_right_click_moving_caret() const {
 	return right_click_moves_caret;
 }
 
+void TextEdit::set_selection_mode(Selection::Mode p_mode, int p_line, int p_column) {
+	selection.selecting_mode = p_mode;
+	if (p_line >= 0) {
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:4338]: Should check it's not greater then the text size with `ERR_FAIL_INDEX(p_line, text.size());`

File: scene/gui/text_edit.cpp [hunk 4]
```diff
@@ -4333,6 +4333,16 @@ bool TextEdit::is_right_click_moving_caret() const {
...
+		selection.selecting_line = p_line;
+	}
+	if (p_column >= 0) {
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:4341]: Same here should check it's not longer then `selection.selecting_line.length()`

File: scene/gui/text_edit.h [hunk 5]
```diff
@@ -636,6 +638,15 @@ class TextEdit : public Control {
 	void set_right_click_moves_caret(bool p_enable);
 	bool is_right_click_moving_caret() const;
 
+	Selection::Mode get_selection_mode() { return selection.selecting_mode; };
```
Comment (Paulb23) [inline scene/gui/text_edit.h:641]: Need `const` on the getters. eg `Selection::Mode get_selection_mode() const;` Would also move them to the cpp file rather then keeping them here in the header.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Overall looks good, left a couple small notes inline, would also add bindings to GDScript.

**Comment by Devination** [comment]
Thank you for your suggestions, I updated the code based on them. Sorry for the slow turnaround time, I wasn't able to work on this until the weekend.

File: scene/gui/text_edit.cpp [hunk 6]
```diff
@@ -6642,6 +6672,11 @@ void TextEdit::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_right_click_moves_caret", "enable"), &TextEdit::set_right_click_moves_caret);
 	ClassDB::bind_method(D_METHOD("is_right_click_moving_caret"), &TextEdit::is_right_click_moving_caret);
 
+	ClassDB::bind_method(D_METHOD("get_selection_mode"), &TextEdit::get_selection_mode);
+	ClassDB::bind_method(D_METHOD("set_selection_mode", "mode", "line", "column"), &TextEdit::set_selection_mode, DEFVAL(0), DEFVAL(-1), DEFVAL(-1));
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp:6676]:
```suggestion
	ClassDB::bind_method(D_METHOD("set_selection_mode", "mode", "line", "column"), &TextEdit::set_selection_mode, DEFVAL(-1), DEFVAL(-1));
```

`DEFVAL(0)` should be safe to remove.

**Review by Paulb23 — COMMENTED** [review]
No worries, one more small issue to fix then it should be good to approve.

**Review by Paulb23 — APPROVED** [review]
Thanks for the contribution, LGTM!

**Comment by akien-mga** [comment]
Thanks!
