### PR TITLE
Fix Jolt Physics soft body vertex normal calculation

### LINKED ISSUE #107831: Jolt Physics - soft body normals are computed incorrectly
### Tested versions

- Reproducible in 4.5-beta1 as well as earlier versions

### System information

Windows 11

### Issue description

`JoltSoftBody3D::update_rendering_server()` computes vertex normals incorrectly: it iterates through all faces, and sets the normal for each vertex to the face normal.  This results in each vertex getting the normal value from one of its attached faces (the last one in the face list).  This results in weird and broken shading.

The code should instead be computing the vertex normal by averaging the normal from all associated faces, similar to how `GodotSoftBody3D::update_normals_and_centroids()` behaves.

### Steps to reproduce

Run the default scene in the attached MRP.

Example of output with Jolt's current normal calculation: 
Image

Output with fixed normal calculation, similar to the Godot physics engine behavior:
Image

### Minimal reproduction project (MRP)

[soft_body_shading.zip](https://github.com/user-attachments/files/20850532/soft_body_shading.zip)

### PR DESCRIPTION
**Pull request by simpkins**
The code previously iterated through each face and set all vertices to that face's normal.  This resulted in each vertex getting the normal from just one face that it belonged to (whichever face was last in this array).  This caused weird shading artifacts.

This fixes the code so that the vertex normal is now the average normal of all faces that it belongs to.  This results in "smooth shading" behavior for soft body meshes.  This is still somewhat undesirable if the input mesh was using flat shading, but it looks less bad than the previous behavior of picking a normal at random from one attached face.

This matches the behavior of GodotPhysicsServer3D.

Fixes #107831.

### CODE REVIEW

**Review by jrouwe — APPROVED** [review]
The only nitpick I have is that if someone ever decides that `LocalVector::clear` should free memory, that this will cause a memory allocation on every update. Personally, I would make the 'reset normal to zero' an explicit loop.

**Comment by mihe** [comment]
> The only nitpick I have is that if someone ever decides that `LocalVector::clear` should free memory, that this will cause a memory allocation on every update

FWIW, there's already `LocalVector::reset`, which serves the purpose of clear-and-deallocate.

**Review by Calinou — APPROVED** [review]
Tested locally with the MRP from https://github.com/godotengine/godot/pull/106697, it works as expected.

File: modules/jolt_physics/objects/jolt_soft_body_3d.cpp [hunk 1]
```diff
@@ -643,9 +646,15 @@ void JoltSoftBody3D::update_rendering_server(PhysicsServer3DRenderingServerHandl
...
-		normals[i2] = normal;
+		normals[i0] += normal;
+		normals[i1] += normal;
+		normals[i2] += normal;
+	}
+	for (Vector3 &n : normals) {
+		real_t len = n.length();
+		if (len > CMP_EPSILON) {
+			n /= len;
+		}
```
Comment (Calinou) [inline modules/jolt_physics/objects/jolt_soft_body_3d.cpp]: Maybe this should have a comment to explain the intended goal (smooth shading), as it's not immediately obvious.

File: modules/jolt_physics/objects/jolt_soft_body_3d.cpp [hunk 2]
```diff
@@ -629,6 +629,9 @@ void JoltSoftBody3D::update_rendering_server(PhysicsServer3DRenderingServerHandl
 	const int physics_vertex_count = (int)physics_vertices.size();
 
 	normals.resize(physics_vertex_count);
+	for (Vector3 &n : normals) {
+		n.zero();
+	}
```
Comment (mihe) [inline modules/jolt_physics/objects/jolt_soft_body_3d.cpp]: If we're changing things anyway, then I would either change this to use `resize_uninitialized`, or just restore `normals.clear()` again. Either one is fine with me.

```suggestion
	normals.resize_uninitialized(physics_vertex_count);
	for (Vector3 &n : normals) {
		n.zero();
	}
```
```suggestion
	normals.clear();
	normals.resize(physics_vertex_count);
```

Looks good otherwise.

**Review by mihe — APPROVED** [review]

File: modules/jolt_physics/objects/jolt_soft_body_3d.cpp (hunk 1 above)
Comment (simpkins) [reply modules/jolt_physics/objects/jolt_soft_body_3d.cpp]: Sure, I'll add a comment.

Note that this code is basically just copied from the Godot physics implementation here:
https://github.com/godotengine/godot/blob/ebc36a722593a131f0b1d88aa85f9e24d82b0766/modules/godot_physics_3d/godot_soft_body_3d.cpp#L185-L190

I ultimately think that we should move this code out of the physics server implementation, and into SoftBody3D.  It doesn't seem like rendering shading logic belongs in the physics server, and it seems unfortunate that all physics server implementations have to re-implement this.  I have some discussions of this (and other issues) in this proposal:
https://github.com/godotengine/godot-proposals/issues/12670

File: modules/jolt_physics/objects/jolt_soft_body_3d.cpp (hunk 2 above)
Comment (simpkins) [reply modules/jolt_physics/objects/jolt_soft_body_3d.cpp]: I'll update it back to using `clear()` again.

I believe using `resize_uninitialized()` is not allowed here, and would technically be undefined behavior.  Even though `Vector3` is a standard-layout class, it has a non-trivial constructor, and I believe the standard says it's undefined behavior to access the data without running the constructor.
(See section 11.9.5 of n4917.pdf: https://github.com/cplusplus/draft/releases/tag/n4917)

**Comment by akien-mga** [comment]
Thanks!
