### PR TITLE
Fix PathFollow rotations.

### LINKED ISSUE #12258: PathFollow abnormal rotation
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, 0e8db63009fdbc586829565d86f0974b95b1cd9e

**Issue description:**
Rotations are very strong for path follow in 3.0, `PathFollow` will very often make multiple 360 degree rotations in points where it should do slight 20 degree rotation.

Godot 2.1.3 (how it should look):
godot2_path_follow

Godot 3.0 (how it looks now):
godot3_path_follow

This issue is a regression in relation to 2.x (tested in 2.1.3). 
Not sure but it reminds me a little like how it could look if rotation is applied in degrees to the method that uses radians. 

**Steps to reproduce:**
1. Add Path node to the scene.
2. Add PathFollow node as a PathNode child
3. Create some path with curves in Path node
4. Add mesh instance to PathFollow, to visualise it
5. Animate PathFollow 'Unit offset' property to see how it behaves.

**Link to minimal example project:**
[PathFollowRotation.zip](https://github.com/godotengine/godot/files/1402000/PathFollowRotation.zip) (run PathFollowRotation.tscn)

### PR DESCRIPTION
**Pull request by ghost**
Replaced the lookahead (which is problematic) with exact delta in offset. Also made some other minor fixes and improvements.

Fixes #12258.

### CODE REVIEW

File: scene/3d/path.cpp [hunk 1]
```diff
@@ -145,6 +157,7 @@ void PathFollow::_update_transform() {
 	}
 
 	set_transform(t);
+	//delta_offset = 0;
```
Comment (akien-mga) [inline scene/3d/path.cpp]: I guess that was for debugging purposes? If so could you remove it?

**Review by akien-mga — APPROVED** [review]
