### PR TITLE
Optimize classnames enumeration

### LINKED ISSUE #101194: Excessive error spam when a global script is not valid
### Tested versions

4.4 dev7

### System information

W10

### Issue description

If you have a global script (with `class_name`) and it has an error, the error will be spammed occasionally when using editor. I observed it e.g. when opening CreateDialog to add a node (happens once), or every time you try to autocomplete something.
https://github.com/user-attachments/assets/97e7b7f2-e148-42ee-a481-025a07a2d38f
What's relevant though is that the error appears at all. It means the script is loaded and/or parsed needlessly *very often* and it probably applies to all global scripts. We should find a way to avoid that. The scripts should be parsed only after they change and use some cache whenever the editor needs something script-related.

### Steps to reproduce

1. Add a script with class name
2. Introduce some parsing error, e.g. a random word wherever
3. In another script, try autocompleting something

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by RandomShaper**
Hereby, a number of items involved in presenting icons of global classes are rewired to leverage the global class cache much better. As a consequence, the time it takes for the node create dialog and autocomplete popup to show up (especially in cold, just after opening the editor) is reduced considerably. This is especially impactful in big projects. I've been a witness of a moderately big project taking about 10 seconds for the node create dialog to be shown for it.

This PR also makes an initial commit that simplifies file system cache parsing, something one of the other commits leverages when it comes to including more attributes in the global class cache.

Benchmarking on a test project with thousands of trivial globally named GDScript and C# classes, some of them with icons, these are the results:
- Without this PR
	- Create node dialog
		Cold: 4692 ms (icon loads: 10, script loads: 2268)
		Hot: 1810 ms (icon loads: 0, script loads: 0)
	- Autocomplete popup
		Cold: 3079 ms (icon loads: 10, script loads: 756)
		Hot: 698 ms (icon loads: 0, script loads: 0)
- With this PR
	- Create node dialog
		Cold: 182 ms (icon loads: 10, script loads: 0
		Hot: 172 ms (icon loads: 0, script loads: 0)
	- Autocomplete popup
		Cold: 91 ms (icon loads: 10, script loads: 0)
		Hot: 83 ms (icon loads: 0, script loads: 0)

As the data above shows, one of the reasons for the speedup is that the new implementation doesn't need to load (potentially multiple times) all the scripts involved. The number of icon loads was measures as well to ensure no regressions in that area were caused by this PR. That is, the editor script icon cache is still used as most as possible.

Besides everything explained above, this PR removes part of the extra work the involved code was doing (such as checking the deprecated custom types' icons), to behave more consistently with what the file system dock does. Given the extent of the changes, there's some risk of regressions in picking up icons for classes.

Version of this PR for 4.3 submitted as #101490.

**UPDATE:** I forgot to add that another potential regression is that the create node dialog won't be able to show the global classes before they have been parsed and cached, which is especially true in the cold case. If that's true and a concern, we could still fall back to parsing the script files or let the create dialog wait until the global classes cache is ready.

- *Production edit: See https://github.com/godotengine/godot/issues/27333.*

Fixes #101194

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -383,33 +383,23 @@ void EditorFileSystem::_scan_filesystem() {
...
-							fc.deps.push_back(path);
-						}
+					{
+						const Vector<String> &slices = split[7].split("<>");
+						ERR_CONTINUE(slices.size() < 5);
+						fc.script_class_name = slices[0];
+						fc.script_class_extends = slices[1];
+						fc.script_class_icon_path = slices[2];
+						fc.import_md5 = slices[3];
+						fc.import_dest_paths = slices[4].split("<*>");
```
Comment (akien-mga) [inline editor/editor_file_system.cpp]: This rang a bell... for context: https://github.com/godotengine/godot/pull/95678#discussion_r1768615235

File: core/object/script_language.cpp [hunk 2]
```diff
@@ -390,7 +390,7 @@ void ScriptServer::global_classes_clear() {
 	inheriters_cache.clear();
 }
 
-void ScriptServer::add_global_class(const StringName &p_class, const StringName &p_base, const StringName &p_language, const String &p_path) {
+void ScriptServer::add_global_class(const StringName &p_class, const StringName &p_base, const StringName &p_language, const String &p_path, bool p_is_abstract, bool p_is_tool) {
```
Comment (akien-mga) [inline core/object/script_language.cpp:393]: I don't have a particular suggestion for improvement, but I can't help wonder if there won't be other types of qualifiers we need to keep track on in the future, leading to further boolean parameters. It's probably fine, though the GDExtension compatibility might need some care.

File: core/object/script_language_extension.h [hunk 3]
```diff
@@ -672,7 +672,7 @@ class ScriptLanguageExtension : public ScriptLanguage {
 
 	GDVIRTUAL1RC_REQUIRED(Dictionary, _get_global_class_name, const String &)
 
-	virtual String get_global_class_name(const String &p_path, String *r_base_type = nullptr, String *r_icon_path = nullptr) const override {
+	virtual String get_global_class_name(const String &p_path, String *r_base_type = nullptr, String *r_icon_path = nullptr, bool *r_is_abstract = nullptr, bool *r_is_tool = nullptr) const override {
```
Comment (akien-mga) [inline core/object/script_language_extension.h:675]: These should likely be added to the `GDVIRTUAL_CALL`, otherwise GDExtension scripting languages won't be able to pass this information.

@dsnopek just added a system for virtual methods compatibility bindings which should work here: #100674.

File: editor/editor_file_system.cpp [hunk 4]
```diff
@@ -49,7 +49,7 @@
 
 EditorFileSystem *EditorFileSystem::singleton = nullptr;
 //the name is the version, to keep compatibility with different versions of Godot
-#define CACHE_FILE_NAME "filesystem_cache8"
+#define CACHE_FILE_NAME "filesystem_cache10"
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply editor/editor_file_system.cpp:52]: In the version for 4.3, I raised to `filesystem_cache9`. In case someone switches between 4.3 and 4.4 for some reason to edit a single project, that'd ensure compatibility. Or that was my reasoning at least.

**Review by akien-mga — COMMENTED** [review]
Looks pretty good to me overall from reading the code. Haven't tested.

**Comment by akien-mga** [comment]
CC @YYF233333 who has been working on #101435 recently, which seems partially related (both are probably relevant to merge but good to cross-review).

File: core/object/script_language.cpp (hunk 2 above)
Comment (RandomShaper) [reply core/object/script_language.cpp:393]: Since I've added just two, I've kept them as separate args here and as separate fields in the classnames cache. For future extensions, I'd say moving to some kind of bitset or similar would be advisable. I'll check the GDExtension compat.

**Comment by YYF233333** [comment]
This one change the sign of `EditorNode::get_object_icon` as well as some change I don't come up with. It probably won't resolve RemoteTree performance issue though, because we are still doing `ResourceLoader::exists()` for every icon, so mine is still relevant. I think I can rebase on top of this once it is settled.

File: core/object/script_language_extension.h (hunk 3 above)
Comment (RandomShaper) [reply core/object/script_language_extension.h:675]: I'm always—inexplicably—fuzzy about this GDExtension compatibility topic, like I used to be with GDNative... So, let's see if I'm getting this straight. This is the only related binding I'm being able to find: `GDVIRTUAL_BIND(_get_global_class_name, "path");`

Given it only cares about the first parameter, looks like we are lucky that second parameter onwards don't have an impact. Is that right?

File: editor/editor_file_system.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (RandomShaper) [reply editor/editor_file_system.cpp:52]: Maybe we could just fork both forever in a way that they can't clash. More detailedly, we'd use something like `filesystem_cache0001` for _master_  and `filesystem_cache1001` for 4.3.

Alternatively, we can backport #100729, which is the one adding a need for checking 'is tool` so we can keep both file system cache formats the same for now...

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

**Testing project:** [test_class_names.zip](https://github.com/user-attachments/files/18497508/test_class_names.zip)
This project includes a `generate.sh` script that can be used to create projects with lots of `class_name`s with custom icons.[^1]

[^1]: Same project without the pregenerated classes in case you have trouble extracting it: [test_class_names.zip](https://github.com/user-attachments/files/18497515/test_class_names.zip)

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 41)
</details>

Using an optimized (LTO) editor build.

In a project with 10,000 named classes that have their own icon each, this is the delay before the Create New Node dialog shows up after clicking the button:

Cold:

Before | After
-|-
4.1 seconds | 1.6 seconds

Warm:

Before | After
-|-
0.9 seconds | 0.3 seconds

File: editor/editor_file_system.cpp [hunk 5]
```diff
@@ -2349,16 +2325,16 @@ void EditorFileSystem::update_files(const Vector<String> &p_script_paths) {
...
 			fi->type = type;
 			fi->resource_script_class = script_class;
 			fi->uid = uid;
-			fi->script_class_name = _get_global_script_class(type, file, &fi->script_class_extends, &fi->script_class_icon_path);
+			fi->class_info = _get_global_script_class(type, file);
 			fi->import_group_file = ResourceLoader::get_import_group_file(file);
 			fi->modified_time = FileAccess::get_modified_time(file);
 			fi->deps = _get_dependencies(file);
-			fi->import_valid = type == "TextFile" || type == "OtherFile" || ResourceLoader::is_import_valid(file);
+			fi->import_valid = (type == "TextFile" || type == "OtherFile") ? true : ResourceLoader::is_import_valid(file);
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:2337]:
```suggestion
			fi->import_valid = type == "TextFile" || type == "OtherFile" || ResourceLoader::is_import_valid(file);
```

**Comment by KoBeWi** [comment]
Unfortunately this breaks custom icons for scripts that aren't global classes. `@icon` is supposed to work in any script, even built-in ones. It affects Scene dock.

File: core/object/script_language.cpp [hunk 6]
```diff
@@ -480,6 +484,16 @@ StringName ScriptServer::get_global_class_native_base(const String &p_class) {
 	return base;
 }
 
+bool ScriptServer::is_global_class_abstract(const String &p_class) {
+	ERR_FAIL_COND_V(!global_classes.has(p_class), false);
+	return global_classes[p_class].is_abstract;
```
Comment (KoBeWi) [inline core/object/script_language.cpp:489]:
```suggestion
	GlobalScriptClass *global_class = global_classes.getptr(p_class);
	ERR_FAIL_COND_V(!global_class, false);
	return global_class->is_abstract;
```
Same below.

File: core/object/script_language.cpp [hunk 7]
```diff
@@ -513,6 +527,8 @@ void ScriptServer::save_global_classes() {
 		d["path"] = global_classes[E].path;
 		d["base"] = global_classes[E].base;
 		d["icon"] = class_icons.get(E, "");
+		d["is_abstract"] = global_classes[E].is_abstract;
```
Comment (KoBeWi) [inline core/object/script_language.cpp:530]: It would be better if `global_classes[E]` was performed only once.
```C++
const GlobalScriptClass &global_class = global_classes[E];
```

File: editor/editor_file_system.h [hunk 8]
```diff
@@ -312,7 +326,7 @@ class EditorFileSystem : public Node {
 	void _update_pending_scene_groups();
 	void _get_all_scenes(EditorFileSystemDirectory *p_dir, HashSet<String> &r_list);
 
-	String _get_global_script_class(const String &p_type, const String &p_path, String *r_extends, String *r_icon_path) const;
+	EditorFileSystem::ScriptClassInfo _get_global_script_class(const String &p_type, const String &p_path) const;
```
Comment (KoBeWi) [inline editor/editor_file_system.h:329]:
```suggestion
	ScriptClassInfo _get_global_script_class(const String &p_type, const String &p_path) const;
```

File: editor/editor_data.h [hunk 9]
```diff
@@ -255,9 +254,9 @@ class EditorData {
 	void script_class_save_icon_paths();
 	void script_class_load_icon_paths();
 
-	Ref<Texture2D> extension_class_get_icon(const String &p_class) const;
+	String extension_class_get_icon_path(const String &p_class) const;
```
Comment (KoBeWi) [inline editor/editor_data.h:257]: What's this change for? How is returning path better if you load it anyway?

File: core/object/script_language.cpp (hunk 7 above)
Comment (RandomShaper) [reply core/object/script_language.cpp:530]: I generally keep such optimizations out of the scope of PRs, unless it's something as pressing as the case of file system. However, it's enough that you have brought this up for me to fix it.

File: editor/editor_file_system.h (hunk 8 above)
Comment (RandomShaper) [reply editor/editor_file_system.h:329]: Including in the next push.

File: editor/editor_data.h (hunk 9 above)
Comment (RandomShaper) [reply editor/editor_data.h:257]: In a previous iteration this made sense, and I forgot to leave it unchanged after I discarded the old idea. Fix coming in the next push.

File: editor/editor_file_system.cpp [hunk 10]
```diff
@@ -1186,7 +1176,7 @@ void EditorFileSystem::_process_file_system(const ScannedDirectory *p_scan_dir,
 					scan_actions.push_back(ia);
 				}
 
-				if (fc->type.is_empty()) {
+				if (fc->type == StringName()) {
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply editor/editor_file_system.cpp:1179]: I'll change it in the next push.

**Comment by RandomShaper** [comment]
@KoBeWi, thanks for your detailed review. I'm glad you caught some issues and now I have a chance to fix them. I'll include fixes in my next push, including counterparts for the 4.3 version of the PR.

**Comment by RandomShaper** [comment]
OK. Pushed after addressing @KoBeWi's comments. I've kept most of the key function so the former algorithm can kick in unless the new fast path is able to fully leverage the class names cache.

File: editor/editor_file_system.cpp [hunk 11]
```diff
@@ -1186,7 +1176,7 @@ void EditorFileSystem::_process_file_system(const ScannedDirectory *p_scan_dir,
 					scan_actions.push_back(ia);
 				}
 
-				if (fc->type.is_empty()) {
+				if (!fc->type.is_empty()) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1179]: Is this really correct?
In your previous iteration you did `fc->type == StringName()`, now the effect is opposite.

File: core/object/script_language.cpp (hunk 6 above)
Comment (KoBeWi) [reply core/object/script_language.cpp:489]: Unresolved.

Comment (RandomShaper) [reply core/object/script_language.cpp:489]: Oh, I forgot.

However, on this new inspection, I realize why I did it like that: for consistency, to match how all the other `ScriptServer::get_global_class_*()` getters are made. A change like the one you're suggesting would be ideal for a subsequent PR that addresses them all at once.

**Review by KoBeWi — APPROVED** [review]

**Comment by RandomShaper** [comment]
After rechecking the code with a fresher mind, I don't really think my concern was justified. What I'm changing in this PR is, in short, how the icon to a certain class name is obtained, once the class name is already known. In other words, if it's possible that you can get an incomplete type set in the create node dialog because the file system hasn't ended parsing the classes yet, that's without this PR as well.

However, given the first file system scan, which includes populating the inventory or global classes, happens synchronously on the main thread, and very early, so, unless I'm missing something, the user has no chance of interacting with the editor early enough for the issue to exist.

**Comment by akien-mga** [comment]
Tested the PR with Calinou's project and a dev build. It's extremely slow in `master`, and just pretty slow (5s) in this PR, but that's with an unoptimized build and 10000 classes, so that's expected. Calinou's test results show what an optimized production build yields.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

File: editor/editor_data.cpp [hunk 12]
```diff
@@ -1026,22 +1012,25 @@ void EditorData::script_class_set_icon_path(const String &p_class, const String
...
+			// If the classnames chain has a native class ancestor, we're done with success.
+			if (r_valid) {
+				*r_valid = ClassDB::class_exists(current);
+			}
 			return String();
 		}
-		ret = _script_class_icon_paths.has(current) ? _script_class_icon_paths[current] : String();
+		HashMap<StringName, String>::ConstIterator E = _script_class_icon_paths.find(current);
+		if ((bool)E) {
+			if (r_valid) {
```
Comment (PhairZ) [inline editor/editor_data.cpp:1027]: This sets `r_valid` to true even if no path was found.

**Review by PhairZ — COMMENTED** [review]
I'll submit a PR addressing an issue on line 1027.

File: editor/editor_data.cpp (hunk 12 above)
Comment (akien-mga) [reply editor/editor_data.cpp:1027]: How so? If the path is not found, `find` would return an Iterator for a nullptr element, and casting it to boil should be false, so it wouldn't enter this branch.
https://github.com/godotengine/godot/blob/394508d26dcf1b7a9362453f9009c07d969f1a7e/core/templates/hash_map.h#L542

Comment (PhairZ) [reply editor/editor_data.cpp:1027]: Yes, but for plugins `find` returns an address with no value, which causes plugin icons not to show. For more details check #102997 and my PR #103143 

I think My wording was slightly off, Sorry about that.
