### PR TITLE
Fix minimap capturing events and improve its theme and editor settings

### LINKED ISSUE #45439: 3.2.4.beta6 graph minimap reacts to clicks even when disabled
**Godot version:**

3.2.4.beta6.mono.official

**OS/device including version:**

Win10

**Issue description:**

The new minimap in graph editors (animation blendtree in my example) still reacts to clicks even when it's disabled (the clickable area seems to stay):

jumkNKF2I3

Also, i'd like to request a small outline around it, so it doesn't blend into the background when using the light editor theme

### PR DESCRIPTION
**Pull request by YuriSizov**
Fixes #45439. This also applies the suggestion about the border around the minimap. I've also adjusted the default value of the minimap opacity to make it stand out even further.

There was also an issue with the resizer icon, it wasn't created properly and it wasn't colored properly to make it visible in a light theme.

image

This also exposes an editor setting for the minimap opacity in all visual editors. (This doesn't work in `master` due to #43394, but it works in `3.2`, #45448).

image

### CODE REVIEW

File: editor/editor_themes.cpp [hunk 1]
```diff
@@ -1115,9 +1120,15 @@ Ref<Theme> create_editor_theme(const Ref<Theme> p_theme) {
...
-	theme->set_color("resizer_color", "GraphEditMinimap", Color(1, 1, 1, 0.65));
+	Ref<Texture2D> minimap_resizer_icon = theme->get_icon("GuiResizer", "EditorIcons");
+	Color minimap_resizer_color;
+	if (dark_theme) {
+		minimap_resizer_color = Color(1, 1, 1, 0.65);
+	} else {
+		minimap_resizer_color = Color(0, 0, 0, 0.65);
+	}
+	theme->set_icon("resizer", "GraphEditMinimap", flip_icon(minimap_resizer_icon, true, true));
+	theme->set_color("resizer_color", "GraphEditMinimap", minimap_resizer_color);
```
Comment (Chaosus) [inline editor/editor_themes.cpp:1131]: I would suggest pushing theme element overriding into `notification`/`NOTIFICATION_THEME_CHANGED`. Because currently, it remains light on the light theme if the user changes the theme:
image

**Review by Chaosus — CHANGES_REQUESTED** [review]

File: editor/editor_themes.cpp (hunk 1 above)
Comment (pycbouh) [reply editor/editor_themes.cpp:1131]: It updates correctly for me. This is similar to how we handle all other color properties in the theme.


https://user-images.githubusercontent.com/11782833/105743131-65349f00-5f4d-11eb-8703-202baa47f7fd.mp4

Comment (Chaosus) [reply editor/editor_themes.cpp:1131]: Ah, sorry, I mixed up the Godot windows :/ Tested, seems ok.

**Review by Chaosus — APPROVED** [review]

File: scene/resources/default_theme/default_theme.cpp [hunk 2]
```diff
@@ -114,7 +114,8 @@ static Ref<Texture2D> flip_icon(Ref<Texture2D> p_texture, bool p_flip_y = false,
 	}
 
 	Ref<ImageTexture> texture(memnew(ImageTexture));
-	Ref<Image> img = p_texture->get_data();
+	Ref<Image> orig_img = p_texture->get_data();
+	Ref<Image> img = memnew(Image(orig_img->get_width(), orig_img->get_height(), orig_img->has_mipmaps(), orig_img->get_format(), orig_img->get_data()));
```
Comment (akien-mga) [inline scene/resources/default_theme/default_theme.cpp:118]: Can't it be duplicated in a simpler way (like `img->duplicate()`)?

Comment (pycbouh) [reply scene/resources/default_theme/default_theme.cpp:118]: I guess it can, yes. Was looking for examples of handling this case in other places, and never checked for the obvious.

Comment (pycbouh) [reply scene/resources/default_theme/default_theme.cpp]: Fixed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
