### PR TITLE
Fix `Camera3D` gizmo representation to accurately reflect FOV

### LINKED ISSUE #101516: Camera wireframe widget gizmo doesn't match FOV.
### Tested versions

4.2-4.4 dev 7

### System information

Godot v4.4.dev7 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6603) - AMD Ryzen 7 3700X 8-Core Processor (16 threads)

### Issue description

If you try to place items in the world so that they line up a certain way with the camera using the wireframe shape of the gizmo for a guide, they don't show up where expected.  For example, if I want something in the lower left corner of the view and line it up like this:

Image

I would expect this to be in the lower left corner, but when viewed from the camera, it looks like this:

Image

Quite far away from the corner.  I have to position the mesh outside of what it looks like the camera to see in order to get it in the corner.

### Steps to reproduce

Make a simple 3D scene with a camera.  Place an object where it looks like it will be in the corner of the camera.  Run the scene or preview the camera and note that the object is inset quite a bit from the corner.

### Minimal reproduction project (MRP)

[test_camera_fov.zip](https://github.com/user-attachments/files/18403949/test_camera_fov.zip)

### PR DESCRIPTION
**Pull request by aaronp64**
Updated gizmo drawing to keep depth proportional to width or height based on whether FOV is horizontal or vertical.

Fixes #101516

### CODE REVIEW

**Review by Chubercik — APPROVED** [review]

**Comment by jitspoe** [comment]
From a quick test, this seems to work properly with the "keep aspect" on the camera set to "keep height" (the default), but not "keep width".

File: editor/plugins/gizmos/camera_3d_gizmo_plugin.cpp [hunk 1]
```diff
@@ -180,7 +180,7 @@ void Camera3DGizmoPlugin::redraw(EditorNode3DGizmo *p_gizmo) {
 
 			const float hsize = Math::sin(Math::deg_to_rad(fov));
 			const float depth = -Math::cos(Math::deg_to_rad(fov));
-			Vector3 side = Vector3(hsize * size_factor.x, 0, depth);
+			Vector3 side = Vector3(hsize * size_factor.x, 0, depth * size_factor.y);
```
Comment (jitspoe) [inline editor/plugins/gizmos/camera_3d_gizmo_plugin.cpp:183]: I think in order to account for both vertical and horizontal FOV, this is the correct solution:
```C++
			Vector3 side;
			if (camera->get_keep_aspect_mode() == Camera3D::KEEP_HEIGHT) {
				side = Vector3(hsize * size_factor.x, 0, depth * size_factor.y);
			} else {
				side = Vector3(hsize * size_factor.x, 0, depth);
			}
```

Comment (aaronp64) [reply editor/plugins/gizmos/camera_3d_gizmo_plugin.cpp]: Updated to multiply depth by `size_factor.x` in the KEEP_WIDTH case - I think `size_factor.x` is needed for the tall aspect ratio/KEEP_WIDTH case, and is 1.0 for wide aspect ratios.  Each combination of tall/wide aspect ratio and KEEP_WIDTH/KEEP_HEIGHT seems to work ok now.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

### Keep Height

image

### Keep Width

image

**Comment by Repiteo** [comment]
Thanks!
