### PR TITLE
Corrected ordering of Left/Top/Right/Bottom properties

### LINKED ISSUE #52577: "Border Width" properties for StyleBoxFlat are in the wrong order
### Godot version

3.4.beta4

### System information

Windows 10

### Issue description

"Border Width" properties are in the order left, top, right, and bottom. "Expand Margin" and "Content Margin" properties are in the order left, right, top, and bottom.

### Steps to reproduce

1. Make a new StyleBoxFlat.
2. Expand the Border Width, Expand Margin, and Content Margin properties.
3. Observe.
image

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by e8newallm**
Fix #52577
 
Orders of all Left/Right/Up/Down properties of the StyleBox resource are now ordered Top -> Right -> Bottom -> Left.

*Part of https://github.com/godotengine/godot-proposals/issues/2141*

### CODE REVIEW

**Comment by pycbouh** [comment]
It fails the CI because empty lines should not be indented.

**Comment by e8newallm** [comment]
Sorted it now. 
`clang-format *.cpp *.h -i` is not recursive I have learnt.

**Comment by pycbouh** [comment]
We have pre-commit hooks that are already setup to properly run clang-format: https://github.com/godotengine/godot/tree/master/misc/hooks

**Comment by e8newallm** [comment]
> We have pre-commit hooks that are already setup to properly run clang-format: https://github.com/godotengine/godot/tree/master/misc/hooks

Just tried it, that makes things a lot easier. Thanks for the help!

File: scene/resources/style_box.cpp [hunk 1]
```diff
@@ -96,10 +96,11 @@ void StyleBox::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("draw", "canvas_item", "rect"), &StyleBox::draw);
 
 	ADD_GROUP("Content Margin", "content_margin_");
-	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "content_margin_left", PROPERTY_HINT_RANGE, "-1,2048,1"), "set_default_margin", "get_default_margin", SIDE_LEFT);
-	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "content_margin_right", PROPERTY_HINT_RANGE, "-1,2048,1"), "set_default_margin", "get_default_margin", SIDE_RIGHT);
+
```
Comment (aaronfranke) [inline scene/resources/style_box.cpp:99]: I think it's better without this blank line. The group and the properties in that group are very related, so they should be together.

Comment (e8newallm) [reply scene/resources/style_box.cpp:99]: Ah apologies, didn't realise I'd put a blank space in there!

**Comment by e8newallm** [comment]
Tidied it up, and grouped things a bit better now.

**Review by mhilbrunner — APPROVED** [review]
Not the maintainer for this one, but the change looks good.

**Review by YuriSizov — DISMISSED** [review]

**Comment by pycbouh** [comment]
After thinking about it and looking at the APIs that we have, I think I agree with @kleonc that Left-Top-Right-Bottom makes more sense.

Their reasoning is [here](https://github.com/godotengine/godot-proposals/issues/2141#issuecomment-918093655). I just want to add that it does make more sense from the control rect POV to go from "left-top" to "right-bottom". It matches that position-size/start-end configuration and it makes sense to have an X value before a Y value.

And we already have some related methods, inside of the edited file even, that follow that order.

**Comment by groud** [comment]
> After thinking about it and looking at the APIs that we have, I think I agree with @kleonc that Left-Top-Right-Bottom makes more sense.

I can't tell what's better, but I wanted to mention that on my TileMap / TileSet rework I had to deal with directions too. 
There I used a "rotation" ordering too but started from the right. So it goes Right / Bottom / Left / Top. This makes it starts for the positive directions, and is also consistent with how you deal with an increasing angle that you would have with polar coordinates. 

I believe this is a more "mathematically correct" way of handling this, but I guess it might be less intuitive than when you are dealing with UI and texts in general, as you would probably favor the reading direction (from left to right in English at least) for that. In such case, I agree left / top / right / bottom would make more sense.

**Comment by Calinou** [comment]
I'm not sure if left-top-right-bottom is better than top-right-left-bottom (we lose on the muscle memory from CSS), but it's better than the current inconsistency we have.

**Comment by Xrayez** [comment]
> I believe this is a more "mathematically correct" way of handling this

If we talk about *unit circle*, mathematically correct way would be "right-top-left-bottom" (`0` radians point at `Vector2.RIGHT`).

In relation to Godot, a more correct way would be "right-bottom-left-top" (when positive Y axis points down). 😛

**Comment by groud** [comment]
> In relation to Godot, a more correct way would be "right-bottom-left-top" (when positive Y axis points down). 😛

Well yes, that's what I said. I am not sure what you mean. 🙃

**Comment by Xrayez** [comment]
> Well yes, that's what I said. I am not sure what you mean. 🙃

I just wanted to show that even when we talk about it from the math standpoint, we'd get potential inconsistency and ambiguity, therefore even when using mathematical approach is not always the appropriate way to look at this (depending on left or right "handedness" in 2D).

I basically confirmed what you've said, but you got concerned that mathematical approach might be superior or more correct.

**Comment by KoBeWi** [comment]
There are more Left/Right/Up/Down properties though:

- margin in MarginContainer
- patch_margin in NinePatchRect
- stretch_margin in TextureProgressBar
- limit in Camera2D
- offset in Control
- anchor in Control
- focus_neighbor in Control

They seem to mostly use Left/Up/Right/Down order. Is this PR only about StyleBoxes or maybe it should make all of it consistent?

**Comment by e8newallm** [comment]
> There are more Left/Right/Up/Down properties though:
> 
> * margin in MarginContainer
> * patch_margin in NinePatchRect
> * stretch_margin in TextureProgressBar
> * limit in Camera2D
> * offset in Control
> * anchor in Control
> * focus_neighbor in Control
> 
> They seem to mostly use Left/Up/Right/Down order. Is this PR only about StyleBoxes or maybe it should make all of it consistent?

I can make it consistent across every set as soon as we decide on the orientation of them first.

**Comment by KoBeWi** [comment]
The CSS order feels more natural to me, even though I never used CSS.

On the other hand, e.g. Camera2D limits are better in their current order. So if we were to make all of them the same, I'd go with Left-Top-Right-Bottom.

**Comment by e8newallm** [comment]
I have changed the order of everything I can find to Left Up Right Down.

**Review by YuriSizov — APPROVED** [review]
Change in the PopupMenu wasn't really necessary, but it's okay for consistency. 🙃

**Review by aaronfranke — DISMISSED** [review]
Looks good to me (haven't tested). I fixed the title to match the current state of this PR.

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

**Comment by akien-mga** [comment]
Thanks!
