### PR TITLE
Fix retrieving command line flags in Android.

### LINKED ISSUE #80574: Immersive mode no longer works on android, both the notification bar and the navigation bar are still visible.
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.2.dev2.official [da81ca62a]

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

Immersive mode seems to no longer works on android, both the notification bar and the navigation bar are still visible. The pinhole cutout is has also gained a black bar.

Tried creating a completely blank project and the problem still arises.

Godot 4.2 dev 2:
Screenshot_20230813-015546

Godot 4.1:
Screenshot_20230813-015227

I am using a Pixel 7 with Android 13

### Steps to reproduce

Export to android

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by MTareqAzim**
Fixes #80574 

This fix stemmed from immersive mode not working in Godot 4.2. It was caused by the command line flags not properly being retrieved.

In this case, the strings retrieved were not properly added to the ArrayList. I do not know Kotlin, so it took time for me to find this fix, but that also means there might be a better fix than this one.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected on a Samsung Galaxy Z Fold4 (Android 13).

**Testing project:** [test_android_immersive_mode.zip](https://github.com/godotengine/godot/files/13194953/test_android_immersive_mode.zip)

Before[^1] | After *(this PR)*
-|-
Screenshot_20231028_102954_Test Android Immersive Mode | Screenshot_20231028_103510_Test Android Immersive Mode

[^1]: Showing notification bar is disabled on screenshots in my system settings, but notice how the image is less tall due to some space being taken by the notification bar.

APKs for testing:

- `master`: [UnnamedProject_master.zip](https://github.com/godotengine/godot/files/13194948/UnnamedProject_master.zip)
- This PR: [UnnamedProject_pr_84102.zip](https://github.com/godotengine/godot/files/13194949/UnnamedProject_pr_84102.zip)

**Comment by akien-mga** [comment]
The fix seems correct, but to make it cleaner, I would suggest removing the `argc` argument from `var cmdline = ArrayList<String>(argc)`.

This seems to be a misinterpretation of the API, this argument is called `initialCapacity` but it doesn't actually resize the ArrayList. It's not clear what it does, but it might be that it doesn't do anything actually: https://stackoverflow.com/a/45661667

I confirm that this program prints an empty array:
```kotlin
fun main() {
    var argc = 4
    val cmdline = ArrayList<String>(argc)
    println(cmdline)
}
```

I checked and that's the only occurrence of using the optional `initialCapacity` parameter in our Kotlin codebase.

**Review by akien-mga — APPROVED** [review]

**Comment by m4gr3d** [comment]
@MTareqAzim Thanks for the fix! 
The original type of `cmdLine` was `Array<String>` for which the addition as previously done worked.
The switch to `ArrayList<>` changed the semantics, introducing the bug.

**Comment by m4gr3d** [comment]
> The fix seems correct, but to make it cleaner, I would suggest removing the `argc` argument from `var cmdline = ArrayList<String>(argc)`.
> 
> This seems to be a misinterpretation of the API, this argument is called `initialCapacity` but it doesn't actually resize the ArrayList. It's not clear what it does, but it might be that it doesn't do anything actually: https://stackoverflow.com/a/45661667
> 
> I confirm that this program prints an empty array:
> 
> ```kotlin
> fun main() {
>     var argc = 4
>     val cmdline = ArrayList<String>(argc)
>     println(cmdline)
> }
> ```
> 
> I checked and that's the only occurrence of using the optional `initialCapacity` parameter in our Kotlin codebase.
> 
> _Note:_ Please make modifications by _amending_ the commit, and _force pushing_ the changes, so that it stays as a single commit (see [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request)).

The `ArrayList` data structure has an internal array it uses to store data that is dynamically resized. The `initialCapacity` argument is used to [pre-allocate the size of that array](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/ArrayList.java#L155), which is useful if you know how big it can grow to, avoiding re-allocation, [which involves resizing and copying the original array](https://github.com/openjdk/jdk/blob/1ec0d02717b6be4faeb13cd0596d80eea90e81ed/src/java.base/share/classes/java/util/ArrayList.java#L232).

As such, let's leave the original allocation as it was. For most operation it won't make a difference since the default initial capacity is 10, and the argument count is likely to be smaller or equal to that, but in occasional situation, it may be useful.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.kt [hunk 1]
```diff
@@ -892,7 +892,7 @@ class Godot(private val context: Context) : SensorEventListener {
 			}
 			val argc =
 				(len[3].toInt() and 0xFF) shl 24 or ((len[2].toInt() and 0xFF) shl 16) or ((len[1].toInt() and 0xFF) shl 8) or (len[0].toInt() and 0xFF)
-			val cmdline = ArrayList<String>(argc)
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.kt:895]: Let's revert this change. I've added a description what it's used for.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Review by m4gr3d — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
