### PR TITLE
GDScript: Fix `MIN_INT` not representable as numeric literal

### LINKED ISSUE #42289: Bitwise operators OR and AND are not working with `-(2^63 - 1)` in 3.2.3 [regression]
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10, 2004

**Issue description:**

Bitwise operators OR and AND aren't working 100% correctly in version 3.2.3, but were working in 3.2.2.

I didn't test XOR.

**Steps to reproduce:**

If I want to set bit 63 on a 64-bit int using:
var value:int = 0 | -9223372036854775808
I get -9223372036854775807 which is wrong
Godot just set bit 63 and bit 0!

Likewise, if I want to test for bit 63:
var value:int = -1 & -9223372036854775808
I get again -9223372036854775807 which is wrong
Godot tested bit 63 and bit 0!

(I also tested with Python, just to be sure)

Possibly related, I repeatedly see on the console while editing:

_ERROR: Cannot represent 9223372036854775808 as 64-bit integer, provided value is too big.
   At: core/ustring.cpp:1821_

Which is actually correct. However, I don't have that number anywhere in code. Well, I do have that number, but negative. The parser seems to be ignoring the minus sign.

My hunch is that "-9223372036854775808" is being incorrectly parsed, leading to incorrect bitwise operations.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by dalexeev**
This PR fixes the inability to write the minimum `int` value as `-9223372036854775808` literal (in master this causes an error, but you can write `1 << 63` instead). This is now a literal, not a "unary minus and a number" expression.

Closes #42289.

Related: #48745.

### CODE REVIEW

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 1]
```diff
@@ -643,6 +663,11 @@ GDScriptTokenizer::Token GDScriptTokenizer::number() {
 	bool has_error = false;
 	bool (*digit_check_func)(char32_t) = is_digit;
 
+	// Sign before hexadecimal or binary.
+	if ((_peek(-1) == '+' || _peek(-1) == '-') && _peek() == '0') {
+		_advance();
+	}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_tokenizer.cpp:669]: This is not obvious due to the fact that the first character of the number literal is consumed before the `number()`. I would prefer `number()` to be called when the current character is the first character of the numeric literal, whatever it is (`+`, `-`, `.`, `0` or some other digit).

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 2]
```diff
@@ -162,6 +162,24 @@ const char *GDScriptTokenizer::Token::get_name() const {
...
+		case CONST_PI:
+		case CONST_TAU:
+		case CONST_INF:
+		case CONST_NAN:
+			return true;
+		default:
+			return false;
+	}
+}
+
```
Comment (MewPurPur) [inline modules/gdscript/gdscript_tokenizer.cpp:182]: I encountered the same problem in the highlighter, and the line of code for it winded up being

```gdscript
if (word == "true" || word == "false" || word == "null" || word == "PI" || word == "TAU" || word == "INF" || word == "NAN" || word == "self" || word == "super" || !reserved_keywords.has(word)
```
not so much in terms of correctness of syntax, but with the rule that if the previous word represents a value, it should be followed by a binary OP. For `super` it was more so because I decided to treat `.` like an operator too as it was helpful to determine when to highlight it like a number.

Maybe there's something to learn from this implementation, and maybe this function in the tokenizer can eventually be used in the highlighter instead of that long condition?

Comment (dalexeev) [reply modules/gdscript/gdscript_tokenizer.cpp:182]: I've also noticed that the highlighter doesn't properly handle newlines and line continuations (for example, the `&&` operator doesn't always highlight correctly). Note that after the `NEWLINE` token, `+` must be treated as unary operator or the start of a numeric literal. But if it is a line continuation or multiline mode is enabled, then `+` can be binary operator.

I think for highlighter you can just keep a parentheses stack and flag if the current line is a continuation. Although with lambdas it can be difficult.

Comment (MewPurPur) [reply modules/gdscript/gdscript_tokenizer.cpp:182]: The highlighter works line by line rn and idk how to fix it. This also messes with the highlighting of much more than just operators that can be unary or binary.

What I'm saying, maybe in the future we can use the tokenizer's info for this too. And also, some of the checks aren't consistent between our implementations, so I wanted to explain my motivation for them.

**Review by adamscott — APPROVED** [review]
This PR introduces `last_token` in the `GDScriptTokenizer`. I don't know if we should maybe expand to a better system of cache/seeking, but for now it works and it helps to fix an issue. It will be possible to upgrade the system afterwards.

Great PR. And great unit tests too, @dalexeev.

It's good for 4.1

**Comment by dalexeev** [comment]
`Expression` also has this issue (https://github.com/godotengine/godot/issues/42289#issuecomment-698565791). Should I fix it in this PR?

**Comment by adamscott** [comment]
> `Expression` also has this issue ([#42289 (comment)](https://github.com/godotengine/godot/issues/42289#issuecomment-698565791)). Should I fix it in this PR?

No, AFAIK, `Expression` is found in `core/math/expression.h`. You should create a new PR. Ping me in the chat with the PR, I'll set the 4.1 milestone to it.

**Comment by akien-mga** [comment]
Thanks!
