### PR TITLE
Fix jumping to function definition using `Ctrl+LMB` or the "Lookup Symbol" button

### LINKED ISSUE #72353: self.function syntax won't trigger Ctirl+Click -> jump to definition.
### Godot version

4.0.beta.16

### System information

N/A

### Issue description

```gdscript
func _run() -> void:
	click_this_function_doesnt_jump_to_its_line() # this works
	self.click_this_function_doesnt_jump_to_its_line() # add self breaks click-jump























































func click_this_function_doesnt_jump_to_its_line():
	pass
```

Ctrl + Click on self.click_this_function_doesnt_jump_to_its_line(), it won't jump to its definition.

### Steps to reproduce

N/A

### Minimal reproduction project

[godot.4.0.beta15.bugs.0.zip](https://github.com/godotengine/godot/files/10532051/godot.4.0.beta15.bugs.0.zip)

### LINKED ISSUE #73167: Lookup Symbol does not always work (regression in 4.0 RC 1)
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 11 Pro 64Bit

### Issue description

Hi,

Found a rather annoying bug in 4.0 RC1 official on Windows 11:
When right clicking on a function in code and selecting "Lookup Symbol" - it does not always work?
Sometimes it works, sometimes it does not work?

Any ideas?

Jesse

### Steps to reproduce

Right click on a function in code and select "Lookup Symbol".
(it does not work always?)

### Minimal reproduction project

N.A.

### LINKED ISSUE #73480: The "Lookup Symbol" button don't appears for custom class names.
### Godot version

4.0 dev_build

### System information

Ubuntu 22.04.1

### Issue description

The "Lookup Symbol" button don't appears for custorm class names.
Related issues: #68475,  #73167.
I tried apply #68311, #69473 and #73196. It don't helps.
The `Ctrl+LMB` works right for all cases.

### Steps to reproduce

Right click to the `CustomClassA` symbol in the `custom_class_b.gd` anywhere. The `Lookup Symbol` button don't appears in the context menu.

### Minimal reproduction project

Example from  #68475.

### PR DESCRIPTION
**Pull request by Vilcrow**
Fixes #72353.
Fixes #73167.
Fixes #73480.

I found the cause of bug #73167. The problem is that when we click on the `Lookup Symbol` button in the context menu, the method `String CodeEdit::get_text_for_symbol_lookup()` returns position of cursor which is located on the `Lookup Symbol` and wrong for code parsing.

bug

Such a bug found in the `3.5.1.stable` too.

### CODE REVIEW

**Comment by akien-mga** [comment]
Since we're at RC stage, and #72789 fixed the relatively minor #72353, I'm thinking the safest path might be to revert #72789 for now (and reopen #72353), and then keep this new PR to redo the relevant changes and make sure they're regression free for 4.1. WDYT?

**Comment by Vilcrow** [comment]
@akien-mga ok.

**Comment by akien-mga** [comment]
Done, you can rebase and redo the relevant changes to fix #72353 + the regressions.

**Comment by Vilcrow** [comment]
It seems to me that this is not a solution for #73167.

**Comment by akien-mga** [comment]
Some other related PRs: #68311 #69473

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -1401,11 +1401,19 @@ static bool _guess_expression_type(GDScriptParser::CompletionContext &p_context,
 			} break;
 			case GDScriptParser::Node::SELF: {
 				if (p_context.current_class) {
+					if (p_context.type != GDScriptParser::COMPLETION_SUPER_METHOD) {
+						r_type.type = p_context.current_class->get_datatype();
+					} else {
+						r_type.type = p_context.current_class->base_type;
+					}
+					// Should it be deleted?
```
Comment (KoBeWi) [inline modules/gdscript/gdscript_editor.cpp:1409]: Yes, no reason to keep commented-out code.

File: scene/gui/code_edit.cpp [hunk 2]
```diff
@@ -2116,25 +2115,32 @@ String CodeEdit::get_text_for_symbol_lookup() {
 		return String();
 	}
 
-	StringBuilder lookup_text;
+	return get_text_with_cursor_char(line, col);
+}
+
+String CodeEdit::get_text_with_cursor_char(int p_line, int p_column) const {
+	int line = p_line;
+	int col = p_column;
```
Comment (KoBeWi) [inline scene/gui/code_edit.cpp:2123]: What are these for?

**Review by KoBeWi — APPROVED** [review]
I can confirm this fixes the issues, but can't tell if the implementation is correct.

File: scene/gui/code_edit.cpp (hunk 2 above)
Comment (AThousandShips) [reply scene/gui/code_edit.cpp:2123]: They're never changed so should just use the arguments instead

Comment (KoBeWi) [reply scene/gui/code_edit.cpp:2123]: Even if they were changed it's pointless, unless you want to use original value after modifying.

**Comment by YuriSizov** [comment]
cc @Paulb23

File: doc/classes/CodeEdit.xml [hunk 3]
```diff
@@ -237,12 +237,20 @@
...
 			<description>
 				Returns the full text with char [code]0xFFFF[/code] at the cursor location.
 			</description>
 		</method>
+		<method name="get_text_with_cursor_char" qualifiers="const">
+			<return type="String" />
+			<param index="0" name="line" type="int" />
+			<param index="1" name="column" type="int" />
+			<description>
+				If the location is not over the text, returns the full text with char [code]0xFFFF[/code] at the specified location, else returns a source text.
```
Comment (Paulb23) [inline doc/classes/CodeEdit.xml:251]: This is independent to `get_text_for_symbol_lookup`, can leave it to this:

Returns the full text with char [code]0xFFFF[/code] at the specified location.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
ScriptEditor changes look good, agree with KoBeWi comments. 
We could probably convert `get_text_for_code_completion` to use the new method as well.

Given it touches `CodeEdit` unit tests would also be nice to add.

**Review by Paulb23 — APPROVED** [review]
ScriptEditor side looks good.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by nagidev** [comment]
I'm facing an issue regarding lookup symbol and autocomplete suggestions not working on referenced children nodes.
Could this be caused by this PR?
https://github.com/godotengine/godot/issues/82258

**Comment by Vilcrow** [comment]
@nagidev No. I checked this for the previous commit, the result is the same. The reason is not in this PR.
