### PR TITLE
Fix particles not properly updated by their lifetime

### LINKED ISSUE #43485: Particles don't adjust curves to fit a randomized lifetime
**Godot version:** 3.2.2
**OS/device including version:** Arch Linux x64, GTX 1660, GLEX3

The documentation [says](https://docs.godotengine.org/en/stable/classes/class_particlesmaterial.html) that properties "can have a CurveTexture applied to vary values over the lifetime of the particle."  But they appear to vary values over the _base_ lifetime, not the individual particle's _actual_ lifetime.  Consider this particle system, with a linear scale curve from 1 to 0, a lifetime of 2, and a lifetime randomness of 1:

Peek 2020-11-12 14-37

I'd expect the particles to always shrink to nothing, but they clearly shrink at the same rate regardless of their individual lifetimes.

Same behavior occurs with other properties (at least color and tangential acceleration), and with both GPU and CPU particles.  I'm not sure if it's intentional, but it makes "fade out" or "shrink away" effects infeasible to combine with randomized lifetimes.

### PR DESCRIPTION
**Pull request by Chaosus**
Fixed several properties which gather from the texture in default Particles material that is not properly handled by `lifetime_randomness`. Also fixed in `CPUParticles`/`CPUParticles2D`.

Before:

particles_before

After:

particles_after

Fix #43485

Test Project:
[Particles_3.2_CurveTest.zip](https://github.com/godotengine/godot/files/5879830/Particles_3.2_CurveTest.zip)

### CODE REVIEW

File: scene/2d/cpu_particles_2d.cpp [hunk 1]
```diff
@@ -671,12 +671,15 @@ void CPUParticles2D::_particles_process(float p_delta) {
 			restart = true;
 		}
 
+		float tv;
```
Comment (akien-mga) [inline scene/2d/cpu_particles_2d.cpp:674]: Should be initialized to `0` in case there's any branch which doesn't assign it a value below (currently there's none, but it's better to do it now than to get bitten by uninitialized memory in the future).

Comment (Chaosus) [reply scene/2d/cpu_particles_2d.cpp]: Fixed (in all files)

File: scene/2d/cpu_particles_2d.cpp [hunk 2]
```diff
@@ -765,59 +767,61 @@ void CPUParticles2D::_particles_process(float p_delta) {
 			continue;
 		} else if (p.time > p.lifetime) {
 			p.active = false;
+			tv = 1.0;
 		} else {
 			uint32_t alt_seed = p.seed;
 
 			p.time += local_delta;
 			p.custom[1] = p.time / lifetime;
+			tv = p.time / p.lifetime;
```
Comment (lawnjelly) [inline scene/2d/cpu_particles_2d.cpp:777]: Should `p.custom[1]` be set as the same as tv too? Or is there something that assumes tv is part of the unadjusted lifetime?

Comment (Chaosus) [reply scene/2d/cpu_particles_2d.cpp:777]: Its used in this code:

```
float base_angle = (parameters[PARAM_ANGLE] + tex_angle) * Math::lerp(1.0f, p.angle_rand, randomness[PARAM_ANGLE]);
			base_angle += p.custom[1] * lifetime * (parameters[PARAM_ANGULAR_VELOCITY] + tex_angular_velocity) * Math::lerp(1.0f, rand_from_seed(alt_seed) * 2.0f - 1.0f, randomness[PARAM_ANGULAR_VELOCITY]);
			p.rotation = Math::deg2rad(base_angle); //angle
			float animation_phase = (parameters[PARAM_ANIM_OFFSET] + tex_anim_offset) * Math::lerp(1.0f, p.anim_offset_rand, randomness[PARAM_ANIM_OFFSET]) + p.custom[1] * (parameters[PARAM_ANIM_SPEED] + tex_anim_speed) * Math::lerp(1.0f, rand_from_seed(alt_seed), randomness[PARAM_ANIM_SPEED]);
			p.custom[2] = animation_phase;
```
and in shader:
```
code += "		float base_angle = (initial_angle + tex_angle) * mix(1.0, angle_rand, initial_angle_random);\n";
	code += "		base_angle += CUSTOM.y * LIFETIME * (angular_velocity + tex_angular_velocity) * mix(1.0, rand_from_seed(alt_seed) * 2.0 - 1.0, angular_velocity_random);\n";
	code += "		CUSTOM.x = base_angle * degree_to_rad;\n"; // angle
	code += "		CUSTOM.z = (anim_offset + tex_anim_offset) * mix(1.0, anim_offset_rand, anim_offset_random) + CUSTOM.y * (anim_speed + tex_anim_speed) * mix(1.0, rand_from_seed(alt_seed), anim_speed_random);\n"; // angle
```
I'm not sure whether it's can be changed here so I used a temporary variable to avoid this.

Comment (lawnjelly) [reply scene/2d/cpu_particles_2d.cpp:777]: I've no idea either not that familiar with the particles, we'll see if anyone else chimes in.. Worst case though it wouldn't be bad to merge as is and this could be fixed in a separate PR if necessary.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
