### PR TITLE
Fix sub-resource IDs resetting when preloaded

### LINKED ISSUE #62258: Some resources will randomly reset their UID
### Godot version

0aa85f4

### System information

Windows 10 x64

### Issue description

Example diff:
```diff
diff --git a/default_bus_layout.tres b/default_bus_layout.tres
index 8cf0b3a7..f306fb8d 100644
--- a/default_bus_layout.tres
+++ b/default_bus_layout.tres
@@ -1,4 +1,4 @@
-[gd_resource type="AudioBusLayout" load_steps=2 format=3 uid="uid://mebhjwywmmgu"]
+[gd_resource type="AudioBusLayout" load_steps=2 format=3 uid="uid://bn3ouxpvseinh"]
```
There is new UID every time I load the project. No idea what causes this, as I wasn't able to reproduce in minimal project.

### Steps to reproduce

1. Create `default_bus_layout.tres`
2. Restart the project
3. The bus layout now has a different UID if your project is unlucky to trigger this :/

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
*Probably* fixes #62258, idk what the issue is about at this point

I had a case in my project where I had a scene A preloading scene B. If I opened A first and then opened B, all B's sub-resource IDs would reset and the built-in script would show as `[unsaved][*]`. It *might* be the clue of all sub-resource issues reported in the issue.

The fix I did is not probably correct (the code seems to have been like this for a very long time, so changing it might have some unwanted side-effects), but it fixes the issue.

EDIT:
I came upon this comment
https://github.com/godotengine/godot/pull/71171#issue-1527805339
which basically confirms that it isn't the right fix. But if the cache is ignored, loading the same resource again should replace the resource from ignored load (to make sure it has a path this time).

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs rebase to pass CI, I fixed the GDScript test error.

**Review by akien-mga — APPROVED** [review]
Tentatively approving to keep track of it as high priority :) But still needs @reduz to check it.

**Comment by reduz** [comment]
The problem is that, in many cases, we use CACHE_IGNORE to convert resources on background (on the exporter, as an example) and this change will break the ones currently loaded and edited.

I think the right fix is a bit simpler here, just change this code:
```C++
if (do_assign && cache_mode != ResourceFormatLoader::CACHE_MODE_IGNORE) {
	res->set_path(path, cache_mode == ResourceFormatLoader::CACHE_MODE_REPLACE);
	res->set_scene_unique_id(id);
}
```
by
```C++
if (do_assign && cache_mode != ResourceFormatLoader::CACHE_MODE_IGNORE) {
	res->set_path(path, cache_mode == ResourceFormatLoader::CACHE_MODE_REPLACE);
}
res->set_scene_unique_id(id);
```

This way, when the resource is re-saved it will keep the unique ID, but you don't necessarily kill the existing resource when using the CACHE_IGNORE mode.

**Comment by reduz** [comment]
After further discussion, it appears that what we need here is to separate the resource cache and the subresource cache modes in the ResourceLoader::load function. I will work on a PR for this soon.

**Comment by KoBeWi** [comment]
After some investigation, the original issue is caused by this line:
https://github.com/godotengine/godot/blob/0a9e6e478e3183d7bf3c5cb895c706bc6275d3ea/modules/gdscript/gdscript_cache.cpp#L367
Resource loaded with CACHE_MODE_IGNORE takes over a path and causes id reset. The solution mentioned in the above comment would fix it, but I think this is not really a correct behavior, idk.

**Comment by KoBeWi** [comment]
Reopening, as fixing the internal ids is high-priority matter and this works as a temporary fix.

File: scene/resources/resource_format_text.cpp [hunk 1]
```diff
@@ -602,9 +602,11 @@ Error ResourceLoaderText::load() {
...
 
 		int_resources[id] = res; //always assign int resources
-		if (do_assign && cache_mode != ResourceFormatLoader::CACHE_MODE_IGNORE) {
-			res->set_path(path, cache_mode == ResourceFormatLoader::CACHE_MODE_REPLACE);
-			res->set_scene_unique_id(id);
+		if (do_assign) {
+			if (cache_mode != ResourceFormatLoader::CACHE_MODE_IGNORE) {
+				res->set_path(path, cache_mode == ResourceFormatLoader::CACHE_MODE_REPLACE);
+			}
+			res->set_scene_unique_id(id); // FIXME: Temporary fix for resetting internals ids. Revert this block after proper fix.
```
Comment (reduz) [inline scene/resources/resource_format_text.cpp:609]: I think this is still correct, even if a temporary fix, likely does not need the comment

**Review by reduz — APPROVED** [review]

File: scene/resources/resource_format_text.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/resources/resource_format_text.cpp:609]: It won't be necessary after the issue is fixed though.

**Comment by ashelleyPurdue** [comment]
You mentioned that this was probably not a "correct" fix because it breaks something else.  What is this other thing that it breaks, out of curiosity?

**Comment by ashelleyPurdue** [comment]
You mentioned that this was probably not a "correct" fix because it breaks something else.  What is this other thing that it breaks, out of curiosity?

**Comment by KoBeWi** [comment]
That was before I updated the PR. It used to set path for resources that ignore cache (i.e. they are supposed to be temporary). Now it only sets ID, which *shouldn't* break anything.
