### PR TITLE
Fix usage req. in Viewport so that ViewportTexture can be sampled as HDR

### LINKED ISSUE #38702: HDR ViewportTexture requires at least USAGE_3D_NO_EFFECTS
**Godot version:**
3.2.2 beta2 win64

**OS/device including version:**
Windows 10 1903

**Issue description:**
In order for a ViewportTexture to be sampled as HDR I must not only have `HDR = true` in the viewport but also have at least `usage = USAGE_3D_NO_EFFECTS`. Sampling the ViewportTexture in another shader with 2D usage results in [0.0,1.0] ranges.
The `disable 3d` flag has no influence (though its intent is not clear to me anyway).

**Steps to reproduce:**
Create a Viewport with a shader outputting a HDR value. 
Use the resulting ViewportTexture in another shader and sample the value.
Change the producing viewports modes.

**Minimal reproduction project:**
Try switching the `Viewport` Node in the project between 2D and 3D usage modes.
[HDR_Viewport_Bug.zip](https://github.com/godotengine/godot/files/4618167/HDR_Viewport_Bug.zip)

Godot_HDR_Bug

### PR DESCRIPTION
**Pull request by mrushyendra**
Previously, setting 'hdr' to `true` in the Viewport was not sufficient
to allow a ViewportTexture to be sampled as HDR, using gles3. Instead,
it was also dependent on whether usage was set to `USAGE_3D` or
`USAGE_3D_NO_EFFECTS`. The cause can be traced to the following line:

` if (!hdr || rt->flags[RENDER_TARGET_NO_3D]) { `

Instead, we want to use the 16bit format when hdr is set to `true`.

Fixes #38702

### CODE REVIEW

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 1]
```diff
@@ -7115,7 +7115,7 @@ void RasterizerStorageGLES3::_render_target_allocate(RenderTarget *rt) {
 	bool hdr = rt->flags[RENDER_TARGET_HDR] && config.framebuffer_half_float_supported;
 	//hdr = false;
 
-	if (!hdr || rt->flags[RENDER_TARGET_NO_3D]) {
+	if (!hdr && rt->flags[RENDER_TARGET_NO_3D]) {
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_storage_gles3.cpp:7118]: This logic is slightly incorrect. 

Right now, this forces HDR for every texture using ``3D`` or ``3D no effects``.

**Comment by clayjohn** [comment]
#38702 is labelled as a documentation issue because the issue the user posted about is not a bug, but  improperly documented behaviour. 

The 2D renderer isnt made to work with HDR. So we don't want to allocate HDR textures when the usage mode is set to ``Usage_2D**``. 

The intention is for HDR images to only be usable in 3D, so the description of ``hdr`` in the docs should be updated https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-property-hdr

**Comment by mrushyendra** [comment]
Gotcha, made the changes to the documentation instead. Thanks!

**Review by clayjohn — APPROVED** [review]

File: doc/classes/Viewport.xml [hunk 2]
```diff
@@ -248,6 +248,7 @@
 		</member>
 		<member name="hdr" type="bool" setter="set_hdr" getter="get_hdr" default="true">
 			If [code]true[/code], the viewport rendering will receive benefits from High Dynamic Range algorithm. High Dynamic Range allows the viewport to receive values that are outside the 0-1 range. In Godot HDR uses 16 bits, meaning it does not store the full range of a floating point number.
+			[b]Note:[/b] Requires [member usage] to be set to [code]USAGE_3D[/code] or [code]USAGE_3D_NO_EFFECTS[/code], since HDR is not supported for 2D.
```
Comment (akien-mga) [inline doc/classes/Viewport.xml:251]: You should be able to reference the constants directly with `[constant Viewport.USAGE_3D]`.

Comment (mrushyendra) [reply doc/classes/Viewport.xml]: Made the required changes. Guess I could update the relevant section in [Updating The Class Reference](https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html#improve-formatting-with-bbcode-style-tags) as well.

Comment (akien-mga) [reply doc/classes/Viewport.xml]: Ah indeed, it needs to be updated to add `[constant CONSTANTNAME]`, `[constant Class.CONSTANTNAME]`, `[enum EnumName]` and `[enum Class.EnumName]`.

**Comment by akien-mga** [comment]
Thanks!
