### PR TITLE
Ensure that SceneTree is initialized and finalized at correct time

### LINKED ISSUE #71695: Mainloop is being created and initialized after main scene and singletons
### Godot version

4.0.dev (14fdd28de9f1f9979cb6cffa4b715a16d406439d)

### System information

Windows 11

### Issue description

Experimenting with nodes initialization order, I have found something strange.

I have sample hierarchy like this:
```
Mainloop # custom
    Singleton
    Singleton2
    Node2D # main scene root node
        Node2D_2
```
Every node prints its status upon construction, being ready, and entering and exiting tree. For Mainloop it's construction, initialization and finalization

I have expected order like this:

```
# init
Mainloop constructed and initialized
    Singleton constructed, entered tree, ready
    Singleton2 constructed, entered tree, ready
    Node2D constructed, entered tree
         Node2D constructed, entered tree, ready
    Node2D ready

# and then deinit in reverse order

    Node2D_2 exited tree
    Node2D exited tree
    Singleton2 exited tree
    Singleton exited tree
MainLoop finalized
```

Real order imho is broken (output from my test project attached to ticket):

```
singleton _init obj: (name: null, id: 26658997261)
singleton _init obj: (name: null, id: 26709329027)
node _init obj: (name: null, id: 27279754254)
    scenetree is  obj: null                     <------- 0.
node _init obj: (name: null, id: 27296531439)
    scenetree is  obj: null
singleton _enter_tree obj: (name: Singleton, id: 26658997261)
singleton _enter_tree obj: (name: Singleton2, id: 26709329027)
node _enter_tree obj: (name: Node2D, id: 27279754254)
node _enter_tree obj: (name: Node2D_2, id: 27296531439)
singleton _ready obj: (name: Singleton, id: 26658997261)    <--------- 1.
singleton _ready obj: (name: Singleton2, id: 26709329027)
node _ready obj: (name: Node2D_2, id: 27296531439)
node _ready obj: (name: Node2D, id: 27279754254)
mainloop _init obj: (name: <null>, id: 25954354228)  <------- 2.
mainloop _initialize obj: (name: <null>, id: 25954354228)
mainloop _finalize obj: (name: <null>, id: 25954354228)
node _exit_tree obj: (name: Node2D_2, id: 27296531439)
    scenetree is  obj: (name: <null>, id: 25954354228)
node _exit_tree obj: (name: Node2D, id: 27279754254)
    scenetree is  obj: (name: <null>, id: 25954354228)
singleton _exit_tree obj: (name: Singleton2, id: 26709329027)
singleton _exit_tree obj: (name: Singleton, id: 26658997261)
```

(0.) during init of first frame custom mainloop is not initialized yet (related problem is fixed here https://github.com/godotengine/godot/pull/70771, and discussion in ticket led to this experiment) 

(1.) Singletons while being slightly glorified nodes break tree initialization order : they enter tree before root scene node and are expected to be ready before it (because they are siblings), but in reality "singleton enters tree, node enters tree, singleton becomes ready, node becomes ready".

(2.). And mainloop is only created and becomes initialized after _all nodes_, and also is destroyed before final destruction of tree, while nominally being a container for all nodes. Such behavior diminishes it's usefulness, because user can't count on custom mainloop for early initialization checks (cli arguments, hardware, etc) or final cleanups. (Ok they can be set in very first singleton in list, but it's too easy to break their order).

More to this: Nodes of very first scene expect to have tree available at any moment.  I have tried accessing mainloop from `Node2D._ready`. This leads to **change in initialization order**!

Like this

```
mainloop _init obj: (name: <null>, id: 25954353607)
singleton _init obj: (name: null, id: 26692551073)
singleton _init obj: (name: null, id: 26742882840)
node _init obj: (name: null, id: 27346862499)
    scenetree is  obj: null
node _init obj: (name: null, id: 27363639707)
    scenetree is  obj: null
singleton _enter_tree obj: (name: Singleton, id: 26692551073)
singleton _enter_tree obj: (name: Singleton2, id: 26742882840)
node _enter_tree obj: (name: Node2D, id: 27346862499)
node _enter_tree obj: (name: Node2D_2, id: 27363639707)
singleton _ready obj: (name: Singleton, id: 26692551073)
    scenetree is  obj: (name: <null>, id: 25954353607)
singleton _ready obj: (name: Singleton2, id: 26742882840)
    scenetree is  obj: (name: <null>, id: 25954353607)
node _ready obj: (name: Node2D_2, id: 27363639707)
node _ready obj: (name: Node2D, id: 27346862499)
mainloop _initialize obj: (name: <null>, id: 25954353607)
mainloop _finalize obj: (name: <null>, id: 25954353607)
node _exit_tree obj: (name: Node2D_2, id: 27363639707)
    scenetree is  obj: (name: <null>, id: 25954353607)
node _exit_tree obj: (name: Node2D, id: 27346862499)
    scenetree is  obj: (name: <null>, id: 25954353607)
singleton _exit_tree obj: (name: Singleton2, id: 26742882840)
singleton _exit_tree obj: (name: Singleton, id: 26692551073)
```

Mainloop becomes constructed before everything else, and during first scene initialization nodes get access to half-baked  mainloop, while it's init completion  and finalization stay where they very.

My question is are (1.) and (2.) bugs or such behavior has some purpose? 

### Steps to reproduce

1. Run reproduction project from console. Running from editor skips deinit steps.
2. See init order
3. Go to Node2D.gd _ready (or Singleton.gd _ready) and uncomment print
4. Run reproduction project again
5. See another init order

### Minimal reproduction project

[test_init_order.zip](https://github.com/godotengine/godot/files/10461192/test_init_order.zip)

### PR DESCRIPTION
**Pull request by RedwanFox**
SceneTree should be fully initialized before any tree operation with any node and finalized only after all nodes exited tree.

Accounts only for in-tree operations, not constructors. After fix init-deinit order will be:

1. constructors (_init) in unspecified order
2. SceneTree native _initialize
3. SceneTree script _initialize
4. All nodes in-tree lifecycle (_enter_tree ->_ready -> ...-> _exit_tree)
5. SceneTree script _finalize
6. SceneTree native _finalize

Partially fixes https://github.com/godotengine/godot/issues/71695

### CODE REVIEW

**Comment by akien-mga** [comment]
Possibly related to #70771 ? CC @kleonc

**Comment by RedwanFox** [comment]
Added one more pull request as follow up to this https://github.com/godotengine/godot/pull/72266
It's experimental and is meant for discussion.

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -407,8 +407,8 @@ void SceneTree::set_group(const StringName &p_group, const String &p_name, const
 void SceneTree::initialize() {
 	ERR_FAIL_COND(!root);
 	initialized = true;
```
Comment (kleonc) [inline scene/main/scene_tree.cpp:409]: Seems like this `initialized` member isn't used for anything (it's being assigned `true`/`false` in `initialize`/`finalize` and that's all). Probably it could be just removed? :thinking:

If not removed then it's strange that `initialized = true` is set at the beginning of the initialization instead of at the end.

File: scene/main/scene_tree.cpp [hunk 2]
```diff
@@ -576,14 +576,13 @@ void SceneTree::finalize() {
...
 
-	MainLoop::finalize();
-
 	if (root) {
 		root->_set_tree(nullptr);
 		root->_propagate_after_exit_tree();
 		memdelete(root); //delete root
 		root = nullptr;
 	}
+	MainLoop::finalize();
```
Comment (kleonc) [inline scene/main/scene_tree.cpp:585]: I'd move it even at the end of this method as I think it should be done after finalizing all `SceneTree`-related stuff (and timers/tweens are `SceneTree`-specific).

Also while you're at it, you could move that `_flush_delete_queue();` from below (with the comment) at the end of the `if (root)` block above. As the comment states it's relevant only after destructing the `root` (for reference I'm the one who added it in #53571).

**Review by kleonc — COMMENTED** [review]
I agree with the changes, it's logical to:
- in `SceneTree::initialize` firstly initialize the base class (call `MainLoop::initialize`), then do `SceneTree`-specific initialization (set tree for the `root`),
- in `SceneTree::finalize` firstly finalize the `SceneTree`-related stuff, then finalize the base class (call `MainLoop::finalize`).

It's the same ordering as for constructors/destructors.

File: scene/main/scene_tree.cpp (hunk 1 above)
Comment (RedwanFox) [reply scene/main/scene_tree.cpp:409]: Yeah, looks like `initialized` is legacy param and can be safely deleted.

**Comment by kleonc** [comment]
> Possibly related to #70771 ? CC @kleonc

@akien-mga Kinda related as both are fixing some aspects of likely not-so-logical initialization order for `MainLoop`/`SceneTree`. But I do think both PRs are fine on their own / independent.

File: scene/main/scene_tree.cpp (hunk 2 above)
Comment (RedwanFox) [reply scene/main/scene_tree.cpp:585]: > I'd move it even at the end of this method as I think it should be done after finalizing all SceneTree-related stuff (and timers/tweens are SceneTree-specific).

At first I did it like this, but it breaks construction-destruction order. because `MainLoop::finalize` calls gdscript method and SceneTree init-deinit order becomes:
1. SceneTree native init
2. SceneTree gdscript init (called from MainLoop::initialize)
3. SceneTree native finalize 
4. SceneTree gdscript finalize (called from MainLoop::finalize)

So I have decided to move it to this place, and not to redo script attaching for this class hierarchy. 

>Also while you're at it, you could move that _flush_delete_queue(); from below (with the comment) at the end of the if (root) block above

Ok.

Comment (kleonc) [reply scene/main/scene_tree.cpp]: I guess it makes sense to leave it in here. In case someone would create timer/tween in script's `_finalize` then there will be no leak (contrary to if moved `MainLoop::finalize()` to the end of `SceneTree::finalize() like I've suggested`).

Comment (RedwanFox) [reply scene/main/scene_tree.cpp]: Let's merge then?:)

Comment (kleonc) [reply scene/main/scene_tree.cpp]: > Let's merge then?:)

Won't happen without approval from **reduz**, he's the maintainer of this area. I can tell you that it's already added to his personal project with PRs to review. But when he'll look at this I have no idea. :slightly_smiling_face:

**Review by RandomShaper — APPROVED** [review]
Looks good for early testing in 4.2.

**Comment by YuriSizov** [comment]
Needs a rebase though :)

**Comment by RedwanFox** [comment]
@RandomShaper Could you also look into this https://github.com/godotengine/godot/pull/70771 ? It would be nice to have both fixes in upstream
@YuriSizov  done

**Review by kleonc — APPROVED** [review]
As already mentioned in https://github.com/godotengine/godot/pull/72248#pullrequestreview-1273990787 this initialization/finalization order makes more sense to me.

Can't think of anything this change could break besides the cases where user implements custom `MainLoop` extending `SceneTree`, and somehow relies on the previous ordering of these callbacks. I find this unlikely though.

>Looks good for early testing in 4.2.

:point_up:

**Comment by YuriSizov** [comment]
Thanks! Yeah, we're aiming to merge this for 4.2 dev1.

**Comment by YuriSizov** [comment]
Thanks!
