### PR TITLE
Fix selection being deleted and indentation not being accounted for. Fixes #55855

### LINKED ISSUE #55855: Ctrl + Enter replaces selected text with a newline in the script editor (should move to the next line instead)
### Godot version

v3.4.stable.official [206ba70f4] and the online editor: https://editor.godotengine.org/releases/3.4.1.rc2/

### System information

Windows 10 21H1, Geforce GTX 550 Ti, GLES2 and GLES3

### Issue description

In the script editor.
Selecting text and pressing `ctrl enter` or `shift ctrl enter`,
replaces the selection with a newline.

Expected:
Cancel the selection and move the cursor to a:
- new empty line below (`ctrl enter`)
- new empty line above (`shift ctrl enter`)

This would make `ctrl (shift) enter` behave the same with or without selected text.

If the intention is to replace the selected text with a new line,
then `enter` can be pressed without holding down a modifier key.

### Steps to reproduce

- create a new or open an existing script
- type some text, for example:
```
var test = 3
```
- select `test`

>Explanation of symbols:
cursor = `|` (vertical bar)
selection start = `[`
selection end = `]`

```
var [test]| = 3
```
- press `ctrl enter`

### observed
```
var 
| = 3
```
Result: A newline replaced the selected text.

### expected:
After `ctrl enter`:
```
var test = 3
|
```
Result: The cursor is on a new empty line below, and the selected text stays unmodified.

Or after pressing `shift ctrl enter`:
```
|
var test = 3
```
Result:  The cursor is on a new empty line above, and the selected text stays unmodified.

### notes:
An application that shows the expected behavior is Visual Studio Code.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by preslavnpetrov**
This fixes the editor deleting the selected text when creating a new line below or above the current one with Ctrl + Enter. I've also made a small edit that will make sure that the indentation is properly accounted for, as if you were creating a new line from the end of the line (i.e, the ':' will be properly accounted for).

Here is a demonstration of how this works after the commit:

4FYN5OA91Q

Fixes #55855

### CODE REVIEW

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -927,8 +927,10 @@ void CodeEdit::_new_line(bool p_split_current_line, bool p_above) {
 		return;
 	}
 
-	const int cc = get_caret_column();
+	/* When not splitting the line, we need to factor in indentation from the end of the current line. */
```
Comment (Calinou) [inline scene/gui/code_edit.cpp:930]: Use single-line comment syntax for single-line comments:

```suggestion
	// When not splitting the line, we need to factor in indentation from the end of the current line.
```

Remember to squash commits together after applying the suggestion (we don't use GitHub's *Squash and merge* feature because we want to keep the merge commit).

Comment (preslavnpetrov) [reply scene/gui/code_edit.cpp:930]: Ah yeah that was a confusing one. The code_edit.cpp file has all of the single-line comments written in /* comment */ form. Would you still like me to change this one to use // single-line comment syntax? It might look a bit inconsistent with the rest of the file.

Comment (Calinou) [reply scene/gui/code_edit.cpp:930]: > Would you still like me to change this one to use // single-line comment syntax? It might look a bit inconsistent with the rest of the file.

I guess it's not so important then; we can change it later in the whole fire in a single commit.

**Comment by Paulb23** [comment]
Any chance you could write some unit tests for the `CodeEdit` changes?

**Comment by preslavnpetrov** [comment]
> Any chance you could write some unit tests for the `CodeEdit` changes?

Sure, I'll just need to go through the docs to see what the workflow for that is.

**Comment by preslavnpetrov** [comment]
Hmmm from what I gather there aren't really any editor tests in the test suite. It seems to be more focused on the actual engine internals, so I don't know if this would really be fitting with the rest of the test suite. Let me know if I'm missing something though.

**Comment by Paulb23** [comment]
> Sure, I'll just need to go through the docs to see what the workflow for that is.

The unit test docs can be found [here.](https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html)

> Hmmm from what I gather there aren't really any editor tests in the test suite. It seems to be more focused on the actual engine internals, so I don't know if this would really be fitting with the rest of the test suite. Let me know if I'm missing something though.

Yeah no editor tests so far, however, `CodeEdit` and `TextEdit` are the engine not the editor. There's already are some `CodeEdit` tests [here.](https://github.com/godotengine/godot/blob/master/tests/scene/test_code_edit.h) These will probably fit under the `auto indent` section. `TextEdit` tests don't exist yet.

**Comment by preslavnpetrov** [comment]
Sorry for the long break between submits. I was taking an extended break for the holidays. I've submitted a version of the code with the unit tests included.

**Review by Paulb23 — APPROVED** [review]
No worries, thanks for the contribution! 

LGTM.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
