### PR TITLE
Fix unintended SpinBox mouse capture

### LINKED ISSUE #43608: FileDialog, Spinbox, and ScrollContainer mouse capture bug
**Godot version:**

v3.2.3.stable.official

**OS/device including version:**

Windows 10, GLES3

**Issue description:**

When double clicking a file in the FileDialog menu while still having left click hold then trying to drag the arrows on a spinbox inside a ScrollContainer will cause the mouse to get stuck in the mouse captured mode. A temporary fix is to check every frame to see if you released your mouse click. What was expected was for the SpinBox in the ScrollContainer not to cause the mouse to be stuck in captured mode.

**Steps to reproduce:**
1. Make a scene with a FileDialog, Spinbox, and a ScrollContainer.
2. Make sure the SpinBox is inside the ScrollContainer under the FileDialog.
3. Double click on a file but make sure your mouse is positioned and your still holding down left click above the SpinBox which is under the FileDialog.
4. Then while still having left click hold down, move your mouse up and down on the arrows.
5. Your mouse will then be stuck in captured mode.

**Minimal reproduction project:**

[FileDialogSpinboxScrollContainerIssue.zip](https://github.com/godotengine/godot/files/5552083/FileDialogSpinboxScrollContainerIssue.zip)

### PR DESCRIPTION
**Pull request by volkathemartian**
Initializes SpinBox drag variables to prevent the mouse from being captured if pressed outside the SpinBox and dragged inside.

Fixes #43608

### CODE REVIEW

File: scene/gui/spin_box.h [hunk 1]
```diff
@@ -52,11 +52,11 @@ class SpinBox : public Range {
 	void _line_edit_input(const Ref<InputEvent> &p_event);
 
 	struct Drag {
-		float base_val;
-		bool allowed;
-		bool enabled;
+		float base_val = 0;
+		bool allowed = false;
+		bool enabled = false;
```
Comment (akien-mga) [inline scene/gui/spin_box.h:57]: There's `enabled = true;` in the constructor which will override this.
I guess this should maybe be initialized to `true` and the constructor initialization removed, to keep the same behavior.

Comment (volkathemartian) [reply scene/gui/spin_box.h]: I moved the fix to the constructor for consistency. Otherwise identical behavior to what I had before.

Comment (akien-mga) [reply scene/gui/spin_box.h]: Actually I must have misread, the constructor has `drag.enabled = false;`, not `true`.

It is indeed better to do it here than in the constructor, so I suggest reverting back to the previous version but removing the re-initialization in the constructor.

Comment (volkathemartian) [reply scene/gui/spin_box.h:57]: Alright, I moved the initialization back to the struct.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
