### PR TITLE
Fix unable to change directory in user access mode

### LINKED ISSUE #58605: FileDialog with User Data access is unusable
### Godot version

3fab862

### System information

W10

### Issue description

When you set `access` of FileDialog to User Data, the current dir and path are filed with `user://<path_to_project>` (effectively `user://res://`). You can select files, but you can't change the current directory at all.

### Steps to reproduce

1. Add FileDialog
2. Change `access` to User Data
3. Add a script that shows the dialog and run the project
4. Notice that the dialog shows project files instead of user data
5. Try to change directory

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by keptsecret**
Fix #58605  
Set it to use the user directory specified  
~~Noticed that it currently ignores custom user data directory set in project settings, needs testing, might be a separate issue that affects more than Windows builds~~

### CODE REVIEW

**Comment by KoBeWi** [comment]
The fact that other modes don't require explicit `change_dir()` suggests that the fix should be done somewhere else.

**Comment by keptsecret** [comment]
Yeah I think so but `dir_access` defaults to the current directory the game is started in, which works on Linux because that's what the user directory defaults to, but on Windows, it defaults to a folder in AppData for some reason. So without adding a case somewhere else, this is what I thought would be fine, unless we change the default folder on Windows.

File: core/io/dir_access.cpp [hunk 1]
```diff
@@ -250,6 +250,11 @@ DirAccess *DirAccess::create(AccessType p_access) {
 	DirAccess *da = create_func[p_access] ? create_func[p_access]() : nullptr;
 	if (da) {
 		da->_access_type = p_access;
+
+		// for ACCESS_RESOURCES and ACCESS_FILESYSTEM, current_dir already defaults to where game was started
+		if (p_access == ACCESS_USERDATA) {
+			da->change_dir("user://");
+		}
```
Comment (bruvzg) [inline core/io/dir_access.cpp:257]: It's probably worth doing the same for the `ACCESS_RESOURCES` as well.

By default, `DirAccess` uses process current directory, it's fine for `ACCESS_FILESYSTEM`. But current directory can be changed by calling `OS::set_cwd` or by third party code. If it's changed to be outside PCK location, `ACCESS_RESOURCES` will have the same issue.

Comment (keptsecret) [reply core/io/dir_access.cpp:257]: Ah okay, that's a good point

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by atngames** [comment]
Hi, I have this same bug in 3.5 beta3 !

**Comment by Calinou** [comment]
> Hi, I have this same bug in 3.5 beta3 !

Please open a new issue with a minimal reproduction project attached.
