### PR TITLE
typedefs: Cleanup unused macros and unnecessary checks

### LINKED ISSUE #36986: Should OFFSET_OF macro be removed?
This code dates from the first commit when godot was open sourced. It's actually unused.
Should we remove it? The language has [offsetof](https://en.cppreference.com/w/cpp/types/offsetof), what's wrong with it?
https://github.com/godotengine/godot/blob/98cdf50a5591e7629bde7688ceda82b15bd9e858/core/typedefs.h#L73-L81

### PR DESCRIPTION
**Pull request by akien-mga**
We now require a compiler with C++17 support, so we don't need to
check for features added to GCC 5 or Clang 3.2.

Clang builtin availability checks were unused anyway as Clang defines
`__GNUC__` as it's also a GNU C implementation.

Fixes #36986.

---

@punto- I checked the codebase for usage (or lack thereof) of the macros I removed, can you check if you actually rely on some of them in console ports?

### CODE REVIEW

File: core/typedefs.h [hunk 1]
```diff
@@ -37,60 +37,41 @@
...
-
-#define OFFSET_OF(st, m) \
-	((size_t)((char *)&(_nullptr<st>()->m) - (char *)0))
-/**
- * Some platforms (devices) don't define NULL
- */
-
-#ifndef NULL
-#define NULL 0
-#endif
```
Comment (akien-mga) [inline core/typedefs.h]: I haven't actually double checked if this is still necessary nowadays. But I think any compiler that supports C11 should define `NULL` in `typedefs.h` which we include above?

Comment (lupoDharkael) [reply core/typedefs.h]: I plan to make a PR migrating from NULL to nullptr so I guess it will be removed anyway. I'm waiting for the display-server branch to be merged so my PR doesn't cause a lot of conflicts.

Comment (akien-mga) [reply core/typedefs.h]: I was waiting similarly before doing this change, but if you want to work on it, I'll leave it to you for after the merge of the `display-server` branch.
Note that `clang-tidy` has a tool for that: https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html
