### PR TITLE
XR: When an sRGB target is used, check hardware sRGB conversion

### LINKED ISSUE #74857: OpenXR/OpenGL(ES) rendering has washed out colors on some android devices
### Godot version

4.0.stable

### System information

Android

### Issue description

Using OpenXR with the OpenGL (`gl_compatibility`) renderer often results in washed out colors. There are differences between different devices and XR runtimes but this is mainly due to us attempting to work around this problem.

These issues also existed in Godot 3 and were worked around, they have returned in Godot 4 as most of this information was lost as it was poorly documented. I'll attempt to sketch the full issue here for prosperity.

Godot has always handled linear to sRGB internally as much as possible as the 2D rendering pipeline is fully sRGB oriented and doesn't require any conversions (one of the reasons Godot has a leg up on the competition), and 3D rendering in Godot 3 was performed in linear color space with a conversion to sRGB in the tone-mapping stage. I believe for Godot 4 we've decided to do all 3D rendering in OpenGL in sRGB color space.

OpenGL(ES) has build in functionality to perform linear to sRGB conversion (and back)
As Godot handles all conversions for it's own buffers normal variants of `GL_RGBA8` buffers are used ensuring no hardware conversions are applied.

This proved to be an issue for OpenXR as we are now sending our rendering result to a 3rd party system. The OpenXR specification clearly states that:
- `GL_RGBA8` and similar image formats are assumed to contain linear color data
- `GL_SRGB_ALPHA8` and similar image formats are assumed to contain sRGB color data.

The footnote here is that some XR runtimes ignore the above and always assume data is in sRGB color space when 8bit color data is used, this is important because it explains why our current workaround sometimes works.

This is why our OpenXR implementation overrides Godots default logic and uses `GL_SRGB_ALPHA8` as the color format for our render target. This ensures OpenXR handles the images correctly.

But on Android devices it broke.

In OpenGL the problem they had when adding sRGB image format support was that many solutions out there already output sRGB color data from the fragment shader. From the documentation on the Khronos website:

> When the output buffer is linear RGB, the answer is assumed to be linear. But if we are writing to an sRGB image, it is entirely reasonable for a shader to want to write linear values which will be automatically converted to sRGB for storage. However, at other times, it is entirely reasonable for a shader to want to write sRGB values directly, and therefore want to store the written provided without any conversion. 

A decision was thus made to make this a setting that by default is off. This setting is called `GL_FRAMEBUFFER_SRGB`.

When off, whatever the fragment shader outputs is written into the buffer
When on, the output of the fragment shader is assumed linear, and if a sRGB image format is used, OpenGL will convert the color to sRGB before writing it into the buffer.

Even though Godot is an OpenGLES renderer, we're still using OpenGL on desktop machines and without ever enabling `GL_FRAMEBUFFER_SRGB` we're good.

In OpenGLES however we have no such setting. OpenGLES always assumes fragment shader output is linear. No problem when the `GL_RGBA8` image format is used as OpenGLES assumes that is a linear buffer, but when a `GL_SRGB_ALPHA8` is used, it will apply the conversion. However as we've already converted the data to sRGB, this doubles up, and we get washed out colors.

The workaround that was implemented a few months ago was to change the logic around choosing the image format. In OpenXR, the XR runtime supplies us with a list of formats it supports. On most desktop system this only returns `GL_SRGB_ALPHA8` while on most Android devices it uses both `GL_RGBA8` and `GL_SRGB_ALPHA8`. So we changed the order around and use `GL_RGBA8` on Android if available. As I mentioned up above, certain runtimes ignore the rule and will treat a `GL_RGBA8` buffer as containing sRGB data. However as we found out, Quest is not one of them, and we're running into trouble with other devices also handling this wrong.

We need to undo this work around and return the logic to what it was and always use `GL_SRGB_ALPHA8` when available.

As 2D rendering to XR viewports isn't supported, we can detect in the rendering pipeline if an sRGB image format is used and if we're either using GLES or if  `GL_FRAMEBUFFER_SRGB` is enabled, we have to ensure our fragment shaders are outputting linear color space even if this means doing an sRGB to linear conversion, only for the hardware to convert it back.

For more understanding of linear v.s. sRGB color space as implemented in OpenGL/OpenGLES, please see:
https://learnopengl.com/Advanced-Lighting/Gamma-Correction
https://www.khronos.org/opengl/wiki/Framebuffer

Note, this issue is not relevant for Vulkan due to Vulkan implementing this much better and giving us the needed control.

### Steps to reproduce

Undo the workaround and thus change this code back the way it was:
```
void OpenXROpenGLExtension::get_usable_swapchain_formats(Vector<int64_t> &p_usable_swap_chains) {
	p_usable_swap_chains.push_back(GL_SRGB8_ALPHA8);
	p_usable_swap_chains.push_back(GL_RGBA8);
}
```

Run any XR project on a Quest or other mobile device

### Minimal reproduction project

The demo project for XR Tools can be used for this:
https://github.com/GodotVR/godot-xr-tools

### PR DESCRIPTION
**Pull request by BastiaanOlij**
In XR situations such as with OpenXR we are overriding our render target as we need to use proper sRGB textures to submit to the XR compositor.

There turns out to be a problem when using OpenGL ES that OpenGL ES **always** expects the output of fragment shaders to be in linear color space, while on OpenGL this is optional but globally turned on. We thus need to suppress our linear to sRGB conversion when applicable.

This PR adds a check to see if an sRGB render target is used, and whether HW sRGB conversion is active and if so, disables our own conversion. There is a slight mismatch at this point where color correction is now done before sRGB conversion.

Note that these changes **only** effect the 3D render pipeline. The use cases where this is needed don't render 2D elements to the viewport that is effected by this.

Fixes #74857

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
I have tested this on PICO and on my Index and got correct output both to the headsets and on screen.

The test project attached should show a row of boxes with incremental shades of black/gray/white:
image

It becomes clear pretty quickly when sRGB is doubled up (2nd box will be visibly gray and middle box will be much loser to white) or when sRGB conversion is not applied (first 5 boxes become nearly black). 

Note for the test project, to run on android install gradle template and install OpenXR loader project from the asset library!

[test xr project.zip](https://github.com/godotengine/godot/files/10963858/test.xr.project.zip)

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -1960,8 +1965,28 @@ void RasterizerSceneGLES3::render_scene(const Ref<RenderSceneBuffers> &p_render_
...
 	RENDER_TIMESTAMP("Render Opaque Pass");
 	uint64_t spec_constant_base_flags = 0;
+	bool disable_linear_to_srgb = false;
 
 	{
+		// Check if our target is an SRGB target, if we're on OpenGL ES or if sRGB conversion is enabled,
+		// the hardware expects our fragment shader to output in linear color space
+		// and will perform the conversion for us.
+		GLint encoding = GL_LINEAR;
+		glGetFramebufferAttachmentParameteriv(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING, &encoding);
```
Comment (BastiaanOlij) [inline drivers/gles3/rasterizer_scene_gles3.cpp:1975]: We may want to store this on the framebuffer we're using and may need to check if there are devices that don't support this check. As far as I can tell this was made core in OpenGL 3.0 and GLES3.

**Comment by Malcolmnixon** [comment]
I tested this on the quest and the brightness looks fine in all the configurations I could test:
 - Quest Link using Oculus = Fine on PC and Headset
 - Quest Link using Steam VR = Fine on PC and Headset
 - Quest Native = Fine on Headset

Additionally I was able to get 120Hz on the Quest Native.

**Comment by BastiaanOlij** [comment]
@rsjtdrjgfuzkfg I've tested it on my PICO and it looks fine, you might want to test too

**Comment by BastiaanOlij** [comment]
After talking with @clayjohn I'm still looking into ways to do this without having to making changes to the renderer as this may hinder us later on as we implement post processing which will assume the data is handled in sRGB.

So far it looks like the extension I found that would potentially allow us to configure OpenGLES to disable the linear to sRGB conversion on fragment shaders but it looks like its poorly supported. OpenGL is a bit vague here.

**Comment by rsjtdrjgfuzkfg** [comment]
@BastiaanOlij tested; works for me as well :)

**Comment by BastiaanOlij** [comment]
Ok @Malcolmnixon @rsjtdrjgfuzkfg new approach that doesn't change the internals of the rendering engine but relies on the `GL_EXT_sRGB_write_control` extension.

This solution is fully contained within the OpenGL extension for OpenXR and I've added some info on how it works at the top.

There are basically two separate extensions for OpenGL and OpenGLES, the OpenGL one is now core functionality (and has been for awhile), but I haven't found good info on the GLES version.
It's not in the core, or at least the defines are not there in the headers on our Android SDK, so I cheated a little there by adding the define into the extension (and naming it the same as in OpenGL, it's actually the same constant).

@clayjohn I'm not sure how we check if this extension is available and ensure how its enabled. It seems to be there by default on the PICO.

So far tested on desktop and tested on PICO.

**Comment by BastiaanOlij** [comment]
Ok, works on Quest too.

**Comment by Malcolmnixon** [comment]
I also confirm it's operational on all Quest modes (PC-Link and Native) and on the Oculus and Steam runtimes.

**Comment by dsnopek** [comment]
This is looking awesome! Great work @BastiaanOlij!!

**Review by clayjohn — APPROVED** [review]
Looks good to me! Great work

**Comment by BastiaanOlij** [comment]
@m4gr3d it might be worth backporting this fix into the Godot 3 plugin

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.
