### PR TITLE
Android: Fix JavaClassWrapper test crashes on API 26 and lower

### LINKED ISSUE #115764: Android JavaClassWrapper test crashes on API 26
### Tested versions

- Reproducible in master

### System information

Medium Phone, 6.4in/16cm (Arm), Virtual, API Level 26

### Issue description

I'm running instrumemted tests via Firebase Test Labs on 4 devices:
- Medium Phone, 6.4in/16cm (Arm), Virtual, API Level 26 - Failed
- Medium Phone, 6.4in/16cm (Arm), Virtual, API Level 30 - Pass
- Motorola G20, API Level 30 - Pass
- Galaxy S25 Ultra, API Level 35 - Pass

On API 26, app crashes when running https://github.com/godotengine/godot/blob/f4f0679a2d4a2b8e6da8700412b387fc1ccad951/platform/android/java/app/src/instrumented/assets/test/javaclasswrapper/java_class_wrapper_tests.gd#L144-L151

```
     *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_arm64/generic_arm64:8.0.0/OSR1.180418.028.A3/10734686:userdebug/dev-keys'
Revision: '0'
ABI: 'arm64'
pid: 6843, tid: 6868, name: GLThread 355  >>> com.godot.game.instrumented <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: JNI NewStringUTF called with pending exception java.lang.OutOfMemoryError: PushLocalFrame'
    x0   0000000000000000  x1   0000000000001ad4  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   7f7f7f7f7f7f7f7f
    x8   0000000000000083  x9   b04b12a3c8fcef79  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  ffffffffffffffff  x14  ff00000000000000  x15  ffffffffffffffff
    x16  00000077d4b532f8  x17  00000077d4af55d0  x18  0000000000000020  x19  0000000000001abb
    x20  0000000000001ad4  x21  00000077b1d92740  x22  0000000000000002  x23  00000000000027d1
    x24  00000000000000e1  x25  00000077b198a000  x26  00000000000027d0  x27  00000077b80fe7a0
    x28  0000000000000043  x29  00000077b80fe640  x30  00000077d4aa9994
    sp   00000077b80fe600  pc   00000077d4af55d8  pstate 0000000060000000
```

### Steps to reproduce

Run Godot instrumented tests on Android API 26

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by m4gr3d**
Fixes https://github.com/godotengine/godot/issues/115764

### CODE REVIEW

File: platform/android/jni_utils.cpp [hunk 1]
```diff
@@ -93,12 +93,18 @@ String charsequence_to_string(JNIEnv *p_env, jobject p_charsequence) {
 jobject _variant_to_jobject(JNIEnv *env, Variant::Type p_type, const Variant *p_arg, int p_depth) {
 	jobject ret = nullptr;
 
-	if (p_depth > Variant::MAX_RECURSION_DEPTH) {
+	if (p_depth > 64) {
```
Comment (syntaxerror247) [inline platform/android/jni_utils.cpp]: Could you please explain this change?

Comment (m4gr3d) [reply platform/android/jni_utils.cpp]: The test that's failing is a stack overflow test; it uses a dictionary that contains an array that nest that same dictionary, so when the logic attempts to convert the data structure, it keeps looping over the nested elements until the stack is exhausted.

On older devices, the stack limit is much less than the previous depth limit (1024), so this update reduces that limit to a value that won't cause a stack overflow on older versions.

Comment (syntaxerror247) [reply platform/android/jni_utils.cpp]: Thanks!

**Review by syntaxerror247 — APPROVED** [review]

File: platform/android/jni_utils.cpp (hunk 1 above)
Comment (dsnopek) [reply platform/android/jni_utils.cpp]: Should we have a comment or constant for this magic number?

File: platform/android/java_class_wrapper.cpp [hunk 2]
```diff
@@ -44,6 +44,11 @@ bool JavaClass::_call_method(JavaObject *p_instance, const StringName &p_method,
 	ERR_FAIL_NULL_V(env, false);
 
 	env->PushLocalFrame(p_argcount);
+	if (env->ExceptionCheck()) {
+		env->ExceptionDescribe();
+		env->ExceptionClear();
```
Comment (dsnopek) [inline platform/android/java_class_wrapper.cpp:49]: Should we log this anywhere? I guess we really don't expect this call to generate an exception, but if it does, I think we'd really want to know about it

Comment (m4gr3d) [reply platform/android/java_class_wrapper.cpp:49]: [`ExceptionDescribe()`](https://docs.oracle.com/en/java/javase/17/docs/specs/jni/functions.html#exceptiondescribe) prints the exception to the log (without crashing the app).

**Review by Repiteo — APPROVED** [review]

File: platform/android/java_class_wrapper.cpp (hunk 2 above)
Comment (dsnopek) [reply platform/android/java_class_wrapper.cpp:49]: Oh, great, thanks!
