### PR TITLE
Fix perform_node_renames handling of AnimationMixers track paths

### LINKED ISSUE #83936: Error when reparenting AnimationPlayer, can break animation tracks
### Godot version

4.2 beta3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you reparent AnimationPlayer, this error is written in the output:
```
Node not found: "../Node2D" (relative to "/root/@EditorNode@17151/@Panel@13/@VBoxContainer@14/@HSplitContainer@17/@HSplitContainer@25/@HSplitContainer@33/@VBoxContainer@34/@VSplitContainer@36/@VSplitContainer@62/@VBoxContainer@63/@PanelContainer@110/MainScreen/@CanvasItemEditor@9493/@VSplitContainer@9312/@HSplitContainer@9314/@HSplitContainer@9316/@Control@9317/@SubViewportContainer@9318/@SubViewport@9319/2D/Node2D/AnimationPlayer")
```
It comes from https://github.com/godotengine/godot/blob/06d51891678e3abf360d6fcd2e8bd1ba96704fcc/editor/scene_tree_dock.cpp#L1584
Seems like the code is called at a wrong time. The paths are updated correctly though.

EDIT:
No the paths are not updated correctly. If you move root node, every animation tracks for nodes that aren't is children will be broken.

### Steps to reproduce

1. Create a new scene with a Node2D root;
2. Add a child Node2D to the **root**;
3. Add a child AnimationPlayer to the **child Node2D**;
4. Create a new animation in the AnimationPlayer node with any name;
5. Add a property track, pick the child Node2D and select any property (example: the modulate property);
6. Create a key in the newly created property track;
7. Reparent AnimationPlayer to the root Node2D;

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes https://github.com/godotengine/godot/issues/83936

This modifies the handling of AnimationPlayers in the perform_node_renames method by moving it before the properties are modified which allows it still retain the correct path to its root. Additionally, since AnimationPlayers and AnimationTrees have been refactored in to the base AnimationMixer class, it now provides handling for AnimationTrees too, but will only run it for AnimationTrees which don't point to an AnimationPlayer.

Additionally, I have restricted path renaming from read-only animations and modifications to tracks marked as imported. This feels like it makes sense since any modifications to these would not be preserved anyway.

There are still other issues discovered around AnimationMixer root nodes in respect to how they're meant to behave, but those issues are out of scope of the reported bug.

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1810,95 +1811,92 @@ void SceneTreeDock::perform_node_renames(Node *p_base, HashMap<Node *, NodePath>
...
-		Node *root = ap->get_node(ap->get_root_node());
+	AnimationMixer *mixer = Object::cast_to<AnimationMixer>(p_base);
+	if (autorename_animation_tracks && mixer) {
+		// Don't rename if we're an AnimationTree pointing to an AnimationPlayer
+		bool points_to_other_animation_player = false;
+		AnimationTree *at = Object::cast_to<AnimationTree>(mixer);
+		if (at) {
+			AnimationPlayer *ap = Object::cast_to<AnimationPlayer>(at->get_node_or_null(at->get_animation_player()));
+			if (ap) {
+				points_to_other_animation_player = false;
```
Comment (YuriSizov) [inline editor/scene_tree_dock.cpp:1824]:
```suggestion
				points_to_other_animation_player = true;
```

Otherwise nothing happens :)

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -1810,95 +1811,92 @@ void SceneTreeDock::perform_node_renames(Node *p_base, HashMap<Node *, NodePath>
...
-								undo_redo->add_undo_method(anim.ptr(), "track_set_path", idx, track_np);
-								undo_redo->add_undo_method(anim.ptr(), "track_set_interpolation_type", idx, anim->track_get_interpolation_type(i));
-								for (int j = 0; j < anim->track_get_key_count(i); j++) {
-									undo_redo->add_undo_method(anim.ptr(), "track_insert_key", idx, anim->track_get_key_time(i, j), anim->track_get_key_value(i, j), anim->track_get_key_transition(i, j));
-								}
+						for (int i = 0; i < anim->get_track_count(); i++) {
+							NodePath track_np = anim->track_get_path(i);
+							if (anim->track_is_imported(i)) {
+								continue;
+							}
```
Comment (YuriSizov) [inline editor/scene_tree_dock.cpp:1859]: Can check this before getting the path.

**Review by YuriSizov — APPROVED** [review]
One issue and one nit, but otherwise changes look good to me.

**Comment by SaracenOne** [comment]
Fixed now, don't know how that one slipped past me.

**Comment by YuriSizov** [comment]
Thanks!
