### PR TITLE
Stop drawing of MarginContainer margins if not in tree

### LINKED ISSUE #112684: Harmless error when MarginContainer is selected then a new scene is opened
### Tested versions

Reproduced in:
 - v4.6.dev.mono.custom_build [bad1287b6]
 - v4.6.dev2.official [7864ac801]

### System information

Godot v4.6.dev.mono (bad1287b6) - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.5599) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads) - 15.76 GiB memory

### Issue description

Error of  `ERROR: scene\main\canvas_item.cpp:177 - Condition "!is_inside_tree()" is true. Returning: Transform2D()` and `INTERNAL ERROR: Condition "!is_inside_tree()" is true. Returning: Transform2D()` get raised when switching scenes with a `MarginContainer` selected. I was able to breakpoint and it looks related to https://github.com/godotengine/godot/pull/111095 at this line 

https://github.com/godotengine/godot/blob/bad1287b62ea09d993fb178bb6b1a61c17ae725e/editor/scene/gui/margin_container_editor_plugin.cpp#L58

Seemed harmless since nothing looked broken in the editor, but still annoying.

### Steps to reproduce

1. Add a `MarginContainer` to the current scene and select it
2. Press the + on the scene tab bar to make a new scene and switch to it
3. See  `ERROR: scene\main\canvas_item.cpp:177 - Condition "!is_inside_tree()" is true. Returning: Transform2D()` and `INTERNAL ERROR: Condition "!is_inside_tree()" is true. Returning: Transform2D()`

### Minimal reproduction project (MRP)

[margin-error.zip](https://github.com/user-attachments/files/23506826/margin-error.zip)
though, the steps are simple enough to do from an empty project

### PR DESCRIPTION
**Pull request by Meorge**
Closes https://github.com/godotengine/godot/issues/112684 .

The error itself didn't seem to cause any problems, but it cluttered the output and made it look like something had gone wrong. This PR just adds a check that stops unnecessary code from running, and that error from being emitted as a result.

### CODE REVIEW

File: editor/scene/gui/margin_container_editor_plugin.cpp [hunk 1]
```diff
@@ -51,7 +51,7 @@ bool MarginContainerEditorPlugin::handles(Object *p_object) const {
 }
 
 void MarginContainerEditorPlugin::forward_canvas_draw_over_viewport(Control *p_viewport_control) {
-	if (!margin_container) {
+	if (!margin_container || !margin_container->is_inside_tree()) {
```
Comment (KoBeWi) [inline editor/scene/gui/margin_container_editor_plugin.cpp]: You can replace it with `is_visible_in_tree()`, because currently the margins draw when the node is invisible.

Comment (Meorge) [reply editor/scene/gui/margin_container_editor_plugin.cpp]: Thanks, will do that! :)

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
