### PR TITLE
[Net] Implement String::parse_url for parsing URLs.

### LINKED ISSUE #39331: WebSocketServer doesn't accept connections over ipv6
**Godot version:**

3.2.1

**OS/device including version:**

Microsoft Windows 10 Home Version	10.0.18362 Build 18362

**Issue description:**

WebSocketServer and WebSocketClient fail to connect when attempting to use an ipv6 address, but connect correctly when using ipv4 addresses.

Documentation on how ipv6 interacts with Websockets in Godot is spotty, but based on PRs #26189 and #26688, I take it that ipv6 compatibility with websockets is mostly automatic.

If it is not automatic, I don't see any mention on the [doc page](https://docs.godotengine.org/en/stable/classes/class_websocketserver.html) wrt. configuring the server for this.

**Steps to reproduce:**

Server.cs

'
using Godot;
using System;

public class Server : Node
{

    WebSocketServer server = new WebSocketServer();
    int PORT = 3476;

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        // server.Connect("data_received", this, "_OnData");
        server.Connect("client_connected", this, "_PeerConnected");
        // server.Connect("client_disconnected", this, "_PeerDisconnected");
        server.Listen(PORT);
        GD.Print("Server Listening");
    }

    public void _PeerConnected(int id, String protocol = "")
    {
        GD.Print("_PeerConnected: ", id);
    }
    public override void _Process(float delta)
    {
        server.Poll();
    }
}
'
[ipv6Test.zip](https://github.com/godotengine/godot/files/4738910/ipv6Test.zip)

Client.cs:

'
    using Godot;
    using System;

    public class Client : Node
    {

        WebSocketClient client = new WebSocketClient();
        string ipv4 = "ws://192.168.1.143:3476";
        string ipv6 = "ws://1234:1234:123:1234:1234:1234:1234:1234:3476";
        // Called when the node enters the scene tree for the first time.
        public override void _Ready()
        {
            client.Connect("connection_established",this, "_Connected");
            client.ConnectToUrl(ipv4);
            GD.Print("Client trying to connect");
        }

        private void _Connected(string protocol)
        {
            GD.Print("Connected");
        }

    // Called every frame. 'delta' is the elapsed time since the previous frame.
        public override void _Process(float delta)
        {
            client.Poll();
        }
    }

'

**Minimal reproduction project:**

[ipv6Test.zip](https://github.com/godotengine/godot/files/4738926/ipv6Test.zip)

### LINKED ISSUE #43365: Cannot connect to websocket using an IPv6 address
Probably related with https://github.com/godotengine/godot/issues/39331 but on the client side

**Godot version:**
3.2.3 stable

**OS/device including version:**
macOS 10.15

**Issue description:**
When connecting to a server exposing a websocket, the connection does not work if I specify `ws://[:.1]:4000` and run the game as a native app. If I export to HTML5 and run in the browser, the connection is established without issues.

If I use `127.0.0.1` the connection can be created both in HTML5 and in the native app, while with `localhost` only the HTML5 version works.

**Steps to reproduce:**

You can use the demo for Godot Phoenix channels [here](https://github.com/alfredbaudisch/GodotPhoenixChannels), accidentally it already implements this behavior and allows to try different hostnames from its UI

### PR DESCRIPTION
**Pull request by Faless**
Splits the URL into (scheme, host, port, path).
Supports both literal IPv4 and IPv6.
Strip credentials when present (e.g. http://user:pass@example.com/).

Use that function in both HTTPRequest and WebSocketClient.

Fixes #39331
Fixes #43365

### CODE REVIEW

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -240,6 +240,70 @@ String String::word_wrap(int p_chars_per_line) const {
 	return ret;
 }
 
+Error String::parse_url(String &r_scheme, String &r_host, int &r_port, String &r_path) const {
```
Comment (akien-mga) [inline core/string/ustring.cpp:243]: Might be worth adding a short description similar to what you put in the PR, since it's not exposed and thus documented in the classref.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
