### PR TITLE
Fixes #15416 - "The deleted nodes are hanging in the inspector."

### LINKED ISSUE #15416: The deleted nodes are hanging in the inspector.
**Godot version:**

**OS/device including version:**

**Issue description:**
inspector doesn't refresh when delete a node. 

**Steps to reproduce:**
1. delete a node
2. click another scene tab
3. back to scene

rf2

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by bfloch**
Problem was the history in #15416 
Exposed the cleanup and also called  a slightly modified _prepare_history which solves an issue where the history would not be correct after cleanup.

I am curious to know if there is a better way do determine if a node was deleted.

I am using is_inside_tree because from the look of it delete nodes never get freed in the editor. Possibly another issue, I thought it is the reference inside the history but it seems to hold references elsewhere.

### CODE REVIEW

File: editor/editor_data.cpp [hunk 1]
```diff
@@ -48,8 +48,16 @@ void EditorHistory::_cleanup_history() {
 			if (!history[i].path[j].ref.is_null())
 				continue;
 
-			if (ObjectDB::get_instance(history[i].path[j].object))
-				continue; //has isntance, try next
+
+			Object* obj = ObjectDB::get_instance(history[i].path[j].object);
+			if(obj)
```
Comment (akien-mga) [inline editor/editor_data.cpp]: Style issues, it should be `if (obj) {`. See https://travis-ci.org/godotengine/godot/jobs/326249268 and http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

While you amend the commit, might be worth also editing the commit log to describe what actual engine bug is being fixed (editor history not being cleaned up properly) instead of the symptom (deleted nodes are "hanging"). So something like:
```
Clean the EditorHistory on SceneTree node deletion

Fixes #15416.
```

Comment (akien-mga) [reply editor/editor_data.cpp]: This said, congrats on your first PR, it looks fine overall code-wise :)
You may be interested in reading (or skimming through, depending on your experience) http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html too.

**Comment by icnikerazah** [comment]
if nodes still are in memory. why 'delete with confirm' option exist

**Comment by bfloch** [comment]
Did I do something wrong? The test failed due to missing apt-get clang-5.0.

**Comment by bfloch** [comment]
@icnikerazah Not too hasty with conclusions :-) There could be various reasons why the objects are not freed like e.g. undo/redo. The problem really is that the history depends on checking if an node is valid if it is still in ObjectDB.
That's what I try to fix here.

As to the memory I've opened another ticket that people familiar with the engine can answer:
https://github.com/godotengine/godot/issues/15481

I hope this pull request fixes at least your problem.

**Comment by volzhs** [comment]
history
is this still possible with this PR?

**Comment by bfloch** [comment]
@volzhs yes. I did not change anything related to undo. All I did is mess with the "EditorHistory".

This is the right side of the "Inspector" where you can go back and forth between recently active nodes.
It relied on ObjectDB::get_instance to cleanup the entries, but it will (by design or not) always be available, even when deleted.

So I replaced this with is_inside_tree checks for nodes.
