### PR TITLE
Fix snapping lines don't disappearing after drag anchors

### LINKED ISSUE #92393: Axis Red lines don't get removed and persist in every scene
### Tested versions

4.2.2.stable

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5222) - Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 Threads)

### Issue description

So I came across a bug where if you try to move the anchors it creates red lines that don't go away and persist in every scene. This can be very frustrating as I have not encountered a way to fix this. 
image_2024-05-26_132726718
image_2024-05-26_132741052

### Steps to reproduce

- Move anchor to center of button, image, any kind of gui
- Red lines show up and don't disappear

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by matheusmdx**
Fix #92393

Before: 

https://github.com/godotengine/godot/assets/44306054/d73b4bc5-56f4-4f34-a50a-053b4a0d785d

<br>

After:

https://github.com/godotengine/godot/assets/44306054/b0460759-ccf6-473c-a5ac-82b8cb24a920

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -1687,13 +1687,18 @@ bool CanvasItemEditor::_gui_input_anchors(const Ref<InputEvent> &p_event) {
 			_commit_canvas_item_state(
 					drag_selection,
 					vformat(TTR("Move CanvasItem \"%s\" Anchor"), drag_selection.front()->get()->get_name()));
+			snap_target[0] = SNAP_TARGET_NONE;
+			snap_target[1] = SNAP_TARGET_NONE;
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:1691]: This looks like something that should be a part of `_reset_drag()` method.

**Review by KoBeWi — APPROVED** [review]

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (matheusmdx) [reply editor/plugins/canvas_item_editor_plugin.cpp:1691]: > This looks like something that should be a part of `_reset_drag()` method.

If desired i can update my pr to do that

Comment (KoBeWi) [reply editor/plugins/canvas_item_editor_plugin.cpp:1691]: It's better to do it in a separate PR.

**Comment by akien-mga** [comment]
Thanks!
