### PR TITLE
Enhancements and fixes for the editor feature profile

### LINKED ISSUE #27841: "Editor Feature Profiles" doesn't show info about restart
**Godot version:**
3.2 def6655964d0ae3a3c9f2d668efef58777ac62e6

**OS/device including version:**
Ubuntu 18.04.2

**Issue description:**
When I set current profile, then Godot doesn't show info about restart. I was a little confused why Godot doesn't change  interface immediately, so info like in editor settings about restart should be provided.

### PR DESCRIPTION
**Pull request by YeldhamDev**
- Update editor when (un)setting profiles (fixes #27841).
- Properly update some editors on change.
- Don't change editor if not the disabled one.
- Enable folding in class tree.
- Minor touch-up in strings.

### CODE REVIEW

File: editor/editor_feature_profile.cpp [hunk 1]
```diff
@@ -12,7 +12,7 @@ const char *EditorFeatureProfile::feature_names[FEATURE_MAX] = {
 	TTRC("Scene Tree Editing"),
 	TTRC("Import Dock"),
 	TTRC("Node Dock"),
-	TTRC("Filesystem Dock")
+	TTRC("Filesystem/Import Dock")
```
Comment (akien-mga) [inline editor/editor_feature_profile.cpp]: Does disabling the FileSystem dock (BTW, capital S) also force disabling the Import dock?
If so, it should likely be "FileSystem and Import Dock**s**".

Comment (YeldhamDev) [reply editor/editor_feature_profile.cpp]: Done.

**Comment by akien-mga** [comment]
Thanks!

File: editor/editor_feature_profile.cpp [hunk 2]
```diff
@@ -42,7 +42,7 @@ const char *EditorFeatureProfile::feature_names[FEATURE_MAX] = {
 	TTRC("Scene Tree Editing"),
 	TTRC("Import Dock"),
 	TTRC("Node Dock"),
-	TTRC("Filesystem Dock")
+	TTRC("FileSystem and Import Docks")
```
Comment (aaronfranke) [inline editor/editor_feature_profile.cpp:45]: You changed the name, but this checkbox doesn't actually control the existence of the Import dock. I fixed this in #38580.
