### PR TITLE
Fix some dragging operations in the editor breaking when tabbing out

### LINKED ISSUE #110359: Some editors don't properly handle focus loss
### Tested versions

4.5 and earlier

### System information

W10

### Issue description

When you Alt+Tab while doing some operations, not all editors will properly release them. I tested with collision shape editors (2D and 3D), but there might be more.

### Steps to reproduce

1. Add a CollisionShape2D or 3D and create shape resource
2. Select the node and drag its size gizmo in the editor
3. While dragging, Alt+Tab so the editor loses focus
4. While the window is not focused, you can see that the dragging operation continues
5. If you click on another scene tab, the editor may crash

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
- Fix dragging operations on 2D and 3D nodes breaking when tabbing out of the window.
- Allow to cancel dragging operations on `CollisionShape2D` nodes with right mouse click.

Fixes #110359.

**ATTENTION:** If this is cherry-picked, #112249 should be too.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Shouldn't focus out stop dragging? I see it's not getting stuck now, and while it's cool that it works while window is unfocused, I think it should just end the operation.

**Comment by YeldhamDev** [comment]
@KoBeWi You think it should confirm the operation or completely cancel it?

**Comment by KoBeWi** [comment]
Confirm. You can undo it anyway.

**Comment by YeldhamDev** [comment]
Changes made.

File: editor/scene/2d/physics/collision_shape_2d_editor_plugin.cpp [hunk 1]
```diff
@@ -35,6 +35,7 @@
 #include "editor/editor_undo_redo_manager.h"
 #include "editor/scene/canvas_item_editor_plugin.h"
 #include "editor/settings/editor_settings.h"
+#include "scene/main/node.h"
```
Comment (AThousandShips) [inline editor/scene/2d/physics/collision_shape_2d_editor_plugin.cpp]:
```suggestion
```

File: editor/scene/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -2804,6 +2676,183 @@ void CanvasItemEditor::_gui_input_viewport(const Ref<InputEvent> &p_event) {
 	}
 }
 
+void CanvasItemEditor::_commit_drag() {
+	if (drag_selection.size() == 0) {
```
Comment (KoBeWi) [inline editor/scene/canvas_item_editor_plugin.cpp]:
```suggestion
	if (drag_selection.is_empty()) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
