### PR TITLE
Fix: Make `get_space_left` on Windows use `current_dir` instead of process CWD

### LINKED ISSUE #108966: DirAccess.get_space_left() always returns free space of executable's directory, regardless of instance path
### Tested versions

Reproducible in Godot 4.4.1.stable

### System information

Godot v4.4.1.stable.mono - Windows 11 (build 26100) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.7216) - 12th Gen Intel(R) Core(TM) i5-12600KF (16 threads)

### Issue description

The `DirAccess.get_space_left()` method appears to always return the free space of the disk where the *project executable* resides, rather than the disk space of the directory referenced by the `DirAccess` instance.

According to the documentation:

> "Returns the available space on the current directory's disk, in bytes."

I interpreted "current directory" as the one the `DirAccess` instance points to, which seems more intuitive. However, the return value seems unrelated to the instance path.

```gdscript
var dir := DirAccess.open("D:\\")		
print("current drive:", DirAccess.get_drive_name(dir.get_current_drive()))
print("space left: %.2f GB" % (dir.get_space_left() / 1024.0 / 1024.0 / 1024.0)) # returns project executable drive's free space

dir.change_dir("C:\\")
print("current drive:", DirAccess.get_drive_name(dir.get_current_drive()))
print("space left: %.2f GB" % (dir.get_space_left() / 1024.0 / 1024.0 / 1024.0)) # still returns project executable drive's free space
```

### Expected behavior

I expected the method to return the free space of the disk corresponding to the path set on the `DirAccess` instance.

### Suggestions

If the current behavior is intended, it may be worth:

- Clarifying the documentation more explicitly.

- Considering making this a static method, as the result doesn't depend on the instance's state.

### Steps to reproduce

1. Create a `DirAccess` instance pointing to a different drive or directory.

2. Call get_space_left() on the instance.

3. Observe that it still returns the free space of the directory containing the executable.

### Minimal reproduction project (MRP)

`N/A`

### PR DESCRIPTION
**Pull request by moluopro**
This PR fixes a behavioral inconsistency in `DirAccessWindows::get_space_left()`, where the method incorrectly queries the available disk space of the process's current working directory (CWD) instead of the directory tracked by the DirAccess instance via current_dir, as is correctly done on Unix platforms.

## Problem

The original Windows implementation uses:

```cpp
GetDiskFreeSpaceEx(nullptr, ...)
```

Passing `nullptr` causes the API to use the **current process directory**, not the directory path that the `DirAccess` object is logically operating on.

This leads to incorrect results in the following cases:

- When the process is running on drive `D:` but the `DirAccess` object has opened a path on drive `C:`.
- When calling `change_dir()` on a `DirAccess` object, which updates `current_dir`, but `get_space_left()` continues to use the wrong drive.

This results in behavioral inconsistency between platforms.

Fixes https://github.com/godotengine/godot/issues/108966

### CODE REVIEW

**Comment by moluopro** [comment]
Test code：
```python
func _on_ready() -> void:
	var BYTES_IN_GB := 1024.0 * 1024.0 * 1024.0

	var dir : DirAccess = DirAccess.open("D:\\")
	print("Space left: %.2f GB" % (dir.get_space_left() / BYTES_IN_GB))

	print(dir.change_dir("C:\\"))
	print("Space left: %.2f GB" % (dir.get_space_left() / BYTES_IN_GB))
```

Before: 

image

After: 

image

File: drivers/windows/dir_access_windows.cpp [hunk 1]
```diff
@@ -329,7 +329,14 @@ Error DirAccessWindows::remove(String p_path) {
 
 uint64_t DirAccessWindows::get_space_left() {
 	uint64_t bytes = 0;
-	if (!GetDiskFreeSpaceEx(nullptr, (PULARGE_INTEGER)&bytes, nullptr, nullptr)) {
+
+	String path = fix_path(current_dir).trim_prefix(R"(\\?\)");
+	// Remove trailing slashes that can break GetDiskFreeSpaceExW
+	if (path.ends_with("\\") && path.length() > 3) { // Don't strip root like "C:\"
```
Comment (bruvzg) [inline drivers/windows/dir_access_windows.cpp]: According to the docs, it should work with the UNC prefix and trailing slash, since only UNC support long paths, it should be better to keep prefix and add missing trailing slash (I have not tested it).

> If this parameter is a UNC name, it must include a trailing backslash, for example, "\\MyServer\MyShare\".

Comment (moluopro) [reply drivers/windows/dir_access_windows.cpp]: Do you think it's appropriate if I change it like this?
```python
	String path = fix_path(current_dir);
	if (!path.ends_with("\\")) {
		path += "\\";
	}
```

Comment (bruvzg) [reply drivers/windows/dir_access_windows.cpp]: Yes, this should be fine, assuming it works like it is described in [docs](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdiskfreespaceexw#parameters).

Comment (moluopro) [reply drivers/windows/dir_access_windows.cpp]: I’ve tested it and didn’t encounter issues. I’ll commit this change. Thanks!

**Review by bruvzg — APPROVED** [review]
Tested it on Windows 11, and it seems to be working fine.

Please squash the commits, see [Pull request workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

**Comment by moluopro** [comment]
> Tested it on Windows 11, and it seems to be working fine.
> 
> Please squash the commits, see [Pull request workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

Done.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
