### PR TITLE
SCons: Disable C++ exception handling

### LINKED ISSUE #80513: Extremely slow build times for `gdscript_vm.cpp` with MSVC and optimizations enabled
### Godot version

4.2.dev (4714e95896c8db02616ea6ec7f9aff92dec1cae4)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX Vega (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

MSVC (tested with VS 2022, but I believe VS 2019 behaves the same) takes an inordinate amount of time to compile two files in the current codebase, when optimizations are enabled:
- `core/variant/variant_call.cpp`
- `modules/gdscript/gdscript_vm.cpp`

This issue is about `gdscript_vm.cpp`, I'll open another one to track `variant_call.cpp` as the resolution for each may not be the same.

On my system, with VS 2022 17.6.5 (MSVC 14.36.32532), compiling `gdscript_vm.cpp` with the default `/O2` optimization level (used when compiling without specifying a different `optimization` or `dev_build` value) takes more than 25 min (!). This is more than half of the total build time for the whole Godot codebase.

We need to figure out why MSVC struggles so much with that file, and how to improve this. It's very likely that we can at least gain an order of magnitude here - at least that should be the goal, because those build times are not acceptable (I'm on Linux 99% of the time, I don't know how MSVC users deal with this on a daily basis...).

The GDScript VM is known to be a pretty heavy file with a massive switch for all opcodes. GCC/Clang do a good job at optimizing it, so good that it's one of the reasons why our official Windows builds are made with MinGW-GCC - it makes the GDScript VM 20% faster. I believe @RandomShaper has been looking into ways to get a similar performance gain with MSVC, using some undocumented MSVC builtins. This is about runtime performance, but if we're lucky this _may_ also help with build time.

This can be debugged by compiling only the `gdscript_vm.cpp` file on the command line with `cl.exe`. You can do a build with `scons p=windows target=editor verbose=yes` to see what the command line would be, abort the build, remove the `gdscript_vm.*.obj` file, and run the command manually. Here's what I have:
```
"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe" /Fomodules\gdscript\gdscript_vm.windows.editor.x86_64.obj /c modules\gdscript\gdscript_vm.cpp /TP /std:c++17 /nologo /MT /Gd /GR /utf-8 /bigobj /O2 /W4 /wd4100 /wd4127 /wd4201 /wd4244 /wd4245 /wd4267 /wd4305 /wd4514 /wd4714 /wd4820 /EHsc /WX /DTOOLS_ENABLED /DDEBUG_ENABLED /DNDEBUG /DNO_EDITOR_SPLASH /DWINDOWS_ENABLED /DWASAPI_ENABLED /DWINMIDI_ENABLED /DTYPED_METHOD_BIND /DWIN32 /DMSVC /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /DNOMINMAX /D_WIN64 /DVULKAN_ENABLED /DGLES3_ENABLED /DMINIZIP_ENABLED /DBROTLI_ENABLED /DZSTD_STATIC_LINKING_ONLY /DUSE_VOLK /DVK_USE_PLATFORM_WIN32_KHR /DGLAD_ENABLED /DGLES_OVER_GL /DTESTS_ENABLED /Ithirdparty\libpng /Ithirdparty\glad /Ithirdparty\volk /Ithirdparty\vulkan /Ithirdparty\vulkan\include /Ithirdparty\zstd /Ithirdparty\zlib /Ithirdparty\brotli\include /Iplatform\windows /I.
```

(Actually I used `dev_mode=yes` instead of `verbose=yes`, so it also enabled warnings. This may negatively impact build time, I'll do another round of tests with just `scons p=windows target=editor verbose=yes`.)

The optimization flag is `/O2`, and can be replaced with other values for testing.

I did some comparisons with different optimization levels:

```
# `O2` (`optimize=speed` or `optimize=speed_trace`)
25m19.63s

# `O1` (`optimize=size`)
29m45.63s

# `Od` (`optimize=none` or `optimize=debug`)
2.93s
```

### Steps to reproduce

Compile `gdscript_vm.cpp` with `/O2` using MSVC, either with:

- `scons p=windows target=editor` (full engine build)
- `cl.exe /Fomodules\gdscript\gdscript_vm.windows.editor.x86_64.obj /c modules\gdscript\gdscript_vm.cpp /TP /std:c++17 /nologo /MT /Gd /GR /utf-8 /bigobj /O2 /DTOOLS_ENABLED /DDEBUG_ENABLED /DNDEBUG /DNO_EDITOR_SPLASH /DWINDOWS_ENABLED /DWASAPI_ENABLED /DWINMIDI_ENABLED /DTYPED_METHOD_BIND /DWIN32 /DMSVC /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /DNOMINMAX /D_WIN64 /DVULKAN_ENABLED /DGLES3_ENABLED /DMINIZIP_ENABLED /DBROTLI_ENABLED /DZSTD_STATIC_LINKING_ONLY /DUSE_VOLK /DVK_USE_PLATFORM_WIN32_KHR /DGLAD_ENABLED /DGLES_OVER_GL /DTESTS_ENABLED /Ithirdparty\libpng /Ithirdparty\glad /Ithirdparty\volk /Ithirdparty\vulkan /Ithirdparty\vulkan\include /Ithirdparty\zstd /Ithirdparty\zlib /Ithirdparty\brotli\include /Iplatform\windows /I.`
  * This compiles only `gdscript_vm.cpp` so it's faster / more focused, won't have you mislead thinking it's the linking step taking forever. You can change `/O2` for `/Od` to compare what it would be like with optimization off, and add/remove any flag which may have an impact on this build step.

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by akien-mga**
Upon investigating the extremely slow MSVC build times in #80513, I noticed that while Godot policy is to never use exceptions, we weren't enforcing it with compiler flags, and thus still included exception handling code and stack unwinding.

This is wasteful on multiple aspects:

- Binary size: Around 20% binary size reduction with exceptions disabled for both MSVC and GCC binaries.
- Compile time:
  * More than 50% build time reduction with MSVC.
  * 10% to 25% build time reduction with GCC + LTO.
- Performance: Possibly, needs to be benchmarked.

Since users may want to re-enable exceptions in their own thirdparty code or the libraries they compile with Godot, this behavior can be toggled with the `disable_exceptions` SCons option, which defaults to true.

Alternative to #80516.
Fixes #80513.

Could be considered for a `4.1` cherry-pick, but this will require significant testing to make sure it behaves as expected, and it may be a welcome but surprising change for existing 4.1.x users, so we might opt for not including it.

----

## Test builds

**Edit:** New test builds for all platforms made with the official buildsystem: https://downloads.tuxfamily.org/godotengine/testing/4.2-dev-pr80612/

To help validate this PR, I've done some builds of the before and after states (from this PR, so on top of 0308422f461dce11339896249e23ff02d978bfa0), for Linux (GCC on our official buildsystem) and Windows (VS 2022 on my laptop, unsigned).

You'll find zips here:
https://downloads.tuxfamily.org/godotengine/testing/4.2.dev.no-exceptions/

#### Linux builds

```
-rwxr-xr-x. 1 akien akien 116M Aug 14 13:11 godot.linuxbsd.editor.x86_64.exceptions-with-oidn
-rwxr-xr-x. 1 akien akien 110M Aug 14 11:02 godot.linuxbsd.editor.x86_64.exceptions-without-oidn
-rwxr-xr-x. 1 akien akien  97M Aug 14 13:11 godot.linuxbsd.editor.x86_64.no-exceptions-with-oidn
-rwxr-xr-x. 1 akien akien  90M Aug 14 11:02 godot.linuxbsd.editor.x86_64.no-exceptions-without-oidn
-rwxr-xr-x. 1 akien akien  68M Aug 14 13:11 godot.linuxbsd.template_release.x86_64.exceptions
-rwxr-xr-x. 1 akien akien  57M Aug 14 13:11 godot.linuxbsd.template_release.x86_64.no-exceptions
```

`exceptions` are the same as we currently use for official builds, and `no-exceptions` use the new option to disable exception handling.

OIDN is special cased as I couldn't disable exception handling for it yet, so the `with-oidn` builds actually still have exceptions enabled for OIDN's build environment only. `without-oidn` builds were made with `module_denoise_enabled=no`. It's an editor-only dependency so it doesn't affect the template build.

I didn't include the `without-oidn` builds in the above ZIPs to save your bandwidth, I mostly build them to see the impact on size and build time.

These builds were made on the official buildsystem with the same options as official releases, so with full optimizations and LTO enabled (`scons p=linuxbsd target=editor warnings=no production=yes`)

#### Windows builds

```
-rwxr-xr-x 1 Remi 197121 118M Aug 14 11:17 godot.windows.editor.x86_64.exceptions.exe*
-rwxr-xr-x 1 Remi 197121 101M Aug 14 13:50 godot.windows.editor.x86_64.no-exceptions.exe*
-rwxr-xr-x 1 Remi 197121  54M Aug 14 12:17 godot.windows.template_release.x86_64.exceptions.exe*
-rwxr-xr-x 1 Remi 197121  51M Aug 14 11:52 godot.windows.template_release.x86_64.no-exceptions.exe*
```

## Impact on size

As seen above, for Linux builds with GCC 10, we get a 16% size reduction for the editor build (or said otherwise, enabling exceptions added 20% size), and a similar ratio for the release template.

With LTO disabled, both build types are around 3M bigger, so the ratio doesn't change much.

Dev build: 758M to 736M on Linux, so 3% size reduction. Less than I expected.

On Windows, there's a similar 15% size reduction for the editor build, and only 5% size reduction for the release template (but it was already significantly smaller than the Linux one, now they have a comparable size).

#### Linux with GCC 10

**Production builds with LTO enabled.**

`scons p=linuxbsd target=editor warnings=no production=yes`

```
==> ../logs/godot-editor-exceptions-with-oidn.log <==
[Time elapsed: 00:09:19.461]

==> ../logs/godot-editor-exceptions-without-oidn.log <==
[Time elapsed: 00:09:09.282]

==> ../logs/godot-editor-no-exceptions-with-oidn.log <==
[Time elapsed: 00:08:51.862]

==> ../logs/godot-editor-no-exceptions-without-oidn.log <==
[Time elapsed: 00:07:55.473]

==> ../logs/godot-template_release-exceptions.log <==
[Time elapsed: 00:06:10.944]

==> ../logs/godot-template_release-no-exceptions.log <==
[Time elapsed: 00:04:34.993]
```

The differences aren't huge, because LTO still takes a while, and it seems like having to compile OIDN with exceptions enabled adds a whole minute to the build time.

If we compare the builds without OIDN, there's a 13% build time reduction for the editor, and a 26% build time reduction for the release template.

**Builds without LTO enabled.**

`no-lto` is `scons p=linuxbsd target=editor warnings=no`, while `dev-build` is `scons p=linuxbsd target=editor dev_build=yes`.

```
==> ../ext/logs/godot-editor-dev-build-exceptions.log <==
[Time elapsed: 00:05:47.942]

==> ../ext/logs/godot-editor-dev-build-exceptions.log <==
[Time elapsed: 00:06:00.398]

==> ../ext/logs/godot-editor-no-lto-exceptions.log <==
[Time elapsed: 00:10:02.207]

==> ../ext/logs/godot-editor-no-lto-no-exceptions.log <==
[Time elapsed: 00:07:35.507]
```

For an optimized build without LTO (so not paying a disproportionate amount of time for linking), there's a significant 25% build time speedup.

For the dev builds, I actually got a 2% build time increase, though I don't know if it's representative, I ran the test only once.

Sizes for these builds for those interested:
```
-rwxr-xr-x. 1 root root 758M Aug 14 11:45 godot.linuxbsd.editor.dev.x86_64.exceptions-dev-build
-rwxr-xr-x. 1 root root 736M Aug 14 12:01 godot.linuxbsd.editor.dev.x86_64.no-exceptions-dev-build
-rwxr-xr-x. 1 root root 119M Aug 14 11:34 godot.linuxbsd.editor.x86_64.exceptions-no-lto
-rwxr-xr-x. 1 root root 100M Aug 14 11:19 godot.linuxbsd.editor.x86_64.no-exceptions-no-lto
```

#### Windows with MSVC from VS 2022

```
scons p=windows target=editor scu_build=yes verbose=yes

- exceptions
[Time elapsed: 00:34:24.411]

- no-exceptions
[Time elapsed: 00:12:18.504]


scons p=windows target=template_release scu_build=yes verbose=yes

- exceptions
[Time elapsed: 00:19:28.350]

- no-exceptions
[Time elapsed: 00:09:20.439]
```

I used `scu_build` to speed things up, so this exacerbates issues like #80513 since the parallel build goes faster, but we'll still get stuck a long time on `gdscript_vm.cpp` for the `exceptions` build.

The results are pretty impressive though, with the build time divided by 3 for the editor (34m to 12m) and divided by 2 for the template (19m to 9m).

## Impact on performance

Help welcome to run some benchmarks! You can use the builds linked above.

## Impact on tests

I had to disable exceptions in doctest, which downgrades our `REQUIRE`/`FAIL` macros to the `CHECK` level (which marks the test as failed but doesn't rage quit). We need to see if that impacts our test suites negatively, and if we should clarify this behavior by changing our existing `REQUIRE`/`FAIL` uses to `CHECK`.

This is work for a follow-up PR where I'd welcome a volunteer - for this PR we should just ensure that the tests still work properly.

## Further work

`godot-cpp` could likely reuse the same logic to build without extensions by default, with a command line option to override that behavior for users who want to compile with a library that needs exceptions (or their own code).

`3.x` backport: #80622

### CODE REVIEW

File: platform/linuxbsd/x11/gl_manager_x11.h [hunk 1]
```diff
@@ -74,17 +74,17 @@ class GLManager_X11 {
...
 
 	struct GLDisplay {
-		GLDisplay() { context = nullptr; }
+		GLDisplay();
 		~GLDisplay();
 		GLManager_X11_Private *context = nullptr;
-		::Display *x11_display;
-		XVisualInfo x_vi;
+		::Display *x11_display = nullptr;
+		XVisualInfo x_vi = {};
```
Comment (akien-mga) [inline platform/linuxbsd/x11/gl_manager_x11.h:81]: That's unrelated to the changes in this PR, but since it triggered rebuilding the engine from scratch, it caught new warnings which were not emitted when reusing the cached objects. If this works to fix the warnings, I'll split it off to a separate PR.

Comment (akien-mga) [reply platform/linuxbsd/x11/gl_manager_x11.h:81]: Moved to #80615, I'm including this commit in this PR for now until it's merged.

**Comment by akien-mga** [comment]
> I had to disable exceptions in doctest, which downgrades our `REQUIRE`/`FAIL` macros to the `CHECK` level (which marks the test as failed but doesn't rage quit). We need to see if that impacts our test suites negatively, and if we should clarify this behavior by changing our existing `REQUIRE`/`FAIL` uses to `CHECK`.

We seem to have one failing test suite after these changes:

```
$ ./bin/godot.linuxbsd.editor.dev.x86_64 --test
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
ERROR: Condition "singleton != nullptr" is true.
   at: NavigationServer3D (./servers/navigation_server_3d.cpp:189)
===============================================================================
./tests/core/io/test_image.h:221:
TEST CASE:  [Image] Modifying pixels of an image

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

./tests/core/io/test_image.h:271: ERROR: CHECK( img->get_pixel(x, y).is_equal_approx(Color(1, 1, 1, 1)) ) is NOT correct!
  values: CHECK( false )
  logged: fill_rect() should colorize all image pixels within rect bounds.

ERROR: Resource was not pre cached for the resource section, bug?
   at: _write_resource (./scene/resources/resource_format_text.cpp:1848)
WARNING: Couldn't load resource (no cache): local://Resource_7urp5
     at: parse_variant (./core/io/resource_format_binary.cpp:411)
ERROR: The object does not have any 'meta' values with the key 'next'.
   at: get_meta (./core/object/object.cpp:926)
ERROR: The object does not have any 'meta' values with the key 'next'.
   at: get_meta (./core/object/object.cpp:926)
```

**Comment by akien-mga** [comment]
We were already defining `-fno-exceptions` for Android, iOS and Web, so I removed those since it's now done in `SConstruct` directly.

Also removed the `ios_exceptions` option since it's redundant with `disable_exceptions` (as long as `-fexceptions` is the default behavior with Apple Clang, to be confirmed @bruvzg).

**Comment by Jordyfel** [comment]
Ran the production builds on my machine (6 core CPU), with MSVC, same scons options.

Editor build time goes from 12:52 to 7:36, a reduction of 41%.

Release template build time goes from 7:46 to 5:45, a reduction of 26%.

**Comment by akien-mga** [comment]
I made an "official" build (same build containers and options as official releases) from this PR for all platforms, so we can easily test the change and compare with 4.2-dev3 from a few days ago.

https://downloads.tuxfamily.org/godotengine/testing/4.2-dev-pr80612/
4.2-dev3 for comparison: https://downloads.tuxfamily.org/godotengine/4.2/dev3/

Size comparison:

```
    4.2-dev3     PR 80612     Diff.    Binary
    
   228.3 MiB    191.1 MiB    -16.3%    Godot.app
   105.4 MiB     91.4 MiB    -13.3%    Godot_v4.2-dev_linux.x86_32
   115.6 MiB     96.3 MiB    -16.7%    Godot_v4.2-dev_linux.x86_64
   112.7 MiB    100.6 MiB    -10.7%    Godot_v4.2-dev_win32.exe
   114.8 MiB     97.3 MiB    -15.2%    Godot_v4.2-dev_win64.exe
    66.8 MiB     56.8 MiB    -15.0%    templates/linux_debug.x86_32
    69.8 MiB     56.7 MiB    -18.8%    templates/linux_debug.x86_64
    66.2 MiB     57.1 MiB    -13.7%    templates/linux_release.x86_32
    67.6 MiB     56.0 MiB    -17.2%    templates/linux_release.x86_64
   281.1 MiB    232.9 MiB    -17.1%    templates/macos_template.app
    71.4 MiB     62.8 MiB    -12.0%    templates/windows_debug_x86_32.exe
    68.5 MiB     56.7 MiB    -17.2%    templates/windows_debug_x86_64.exe
    71.1 MiB     61.9 MiB    -12.9%    templates/windows_release_x86_32.exe
    66.0 MiB     56.1 MiB    -15.0%    templates/windows_release_x86_64.exe
```

**Comment by Calinou** [comment]
**OS:** Fedora 38
**CPU:** Intel Core i9-13900K
**SSD:** Solidigm P44 Pro 2 TB
**Compiler:** GCC 13.2.1

<details>
<summary>Build options</summary>

Editor build options: `scons -j32 platform=linuxbsd linker=mold optimize=none fast_unsafe=yes progress=no debug_symbols=yes builtin_embree=no builtin_enet=no builtin_freetype=no builtin_graphite=no builtin_harfbuzz=no builtin_libogg=no builtin_libpng=no builtin_libtheora=no builtin_libvorbis=no builtin_libwebp=no builtin_mbedtls=no builtin_miniupnpc=no builtin_pcre2=no builtin_zlib=no builtin_zstd=no scu_build=all tests=no`

Release export template build options: `scons -j32 platform=linuxbsd target=template_release debug_symbols=yes lto=full progress=no scu_build=all`
</details>
I ran each build twice with `ccache -C` first to fully empty ccache.
```bash
# Before
vstask "Build (editor)"  1387.70s user 115.27s system 2425% cpu 1:01.96 total
Stripped binary size: 170,679,344 bytes

# After
vstask "Build (editor)"  1278.58s user 112.49s system 2425% cpu 57.361 total
Stripped binary size: 150,215,728 bytes
```

```bash
# Before
vstask "Build (release export template)"  2962.39s user 139.11s system 1888% cpu 2:44.21 total
Striped binary size: 70,403,424 bytes

# After
vstask "Build (release export template)"  2351.15s user 132.09s system 1904% cpu 2:10.37 total
Stripped binary size: 58,283,360 bytes
```

**Comment by mastermarkus** [comment]
### Editor

Compile Time: [Time elapsed: 00:27:55.373] (disable_exceptions= **false**)
After: [Time elapsed: 00:12:49.400] (disable_exceptions= **true**)

As for binary size, reduction is about 15MB

**Comment by mihe** [comment]
Some issues I'm noticing:

- There are a lot of warnings being emitted for MSVC about missing unwind semantics. It seems like you forgot to carry over `/wd4530` from [#80516](https://github.com/godotengine/godot/pull/80516).
- You seem to have forgot to actually re-enable exception-handling (by appending `/EHsc`) in the denoise module when using MSVC.

**Comment by mihe** [comment]
I guess this is borderline off-topic, but I was curious about what further binary size reductions could be had with disabling RTTI as well, so I compiled with `/GR-` on MSVC (which breaks `dynamic_cast`, but still lets you compile) and saw a ~2% reduction. So not exactly a world of difference (when using MSVC).

Figured you might be interested.

**Comment by santouits** [comment]
In release builds you can also try ["-fno-unwind-tables", "-fno-asynchronous-unwind-tables"] .

**Review by bruvzg — APPROVED** [review]
Still needs a `/wd4530` to suppress warnings from the headers, but seems to work fine.

**Comment by Calinou** [comment]
> I guess this is borderline off-topic, but I was curious about what further binary size reductions could be had with disabling RTTI as well, so I compiled with `/GR-` on MSVC (which breaks `dynamic_cast`, but still lets you compile) and saw a ~2% reduction. So not exactly a world of difference (when using MSVC).
> 
> Figured you might be interested.

We rely on RTTI on all platforms since 4.0, as it's needed for `Object::cast_to()` to work reliably.

**Comment by dsnopek** [comment]
> We rely on RTTI on all platforms since 4.0, as it's needed for `Object::cast_to()` to work reliably. This means we can't disable it anymore, unlike 3.x where it was disabled for Android and web exports.

This veering even further off-topic, but we _could_ implement a custom replacement for RTTI to support `Object::cast_to<>()` that could maybe be somewhat more performant than `dynamic_cast<>()` because we wouldn't need to support things like multiple inheritance and non-public inheritance and all the other wacky edge cases that `dynamic_cast<>()` does. That said, I have no idea how much "somewhat more performant" would be, and it may not (in fact, it's probably not?) worth it, especially considering cross-platform considerations.

**Comment by bruvzg** [comment]
> This veering even further off-topic

RTTI is also used by some third party libraries (icu, msdfgen, embree, oidn), so it's not just for `cast_to`.

**Comment by akien-mga** [comment]
Re-added `/EHsc` when compiling OIDN, it should compile fine without warnings now.

**Comment by akien-mga** [comment]
> In release builds you can also try ["-fno-unwind-tables", "-fno-asynchronous-unwind-tables"] .

Tested this:

Editor:

```
# production build with `-fno-exceptions`
[Time elapsed: 00:08:51.862]
-rwxr-xr-x. 1 akien akien  97M Aug 14 13:11 godot.linuxbsd.editor.x86_64.no-exceptions

# production build with `-fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables`
[Time elapsed: 00:10:25.825]
-rwxr-xr-x. 1 akien akien  91M Aug 16 14:09 godot.linuxbsd.editor.x86_64.no-exceptions-no-unwind-tables
```

Release template:

```
# production build with `-fno-exceptions`
[Time elapsed: 00:04:34.993]
-rwxr-xr-x. 1 akien akien  57M Aug 14 13:11 godot.linuxbsd.template_release.x86_64.no-exceptions

# production build with `-fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables`
[Time elapsed: 00:06:53.694]
-rwxr-xr-x. 1 akien akien  52M Aug 16 14:20 godot.linuxbsd.template_release.x86_64.no-exceptions-no-unwind-tables
```

So these options seem to have a significant impact to further decrease the binary size, at the cost of (somewhat surprisingly?) increasing build times.

Might be an interesting tradeoff to explore for official production builds, though I'll leave that for a separate issue/PR.

**Comment by mihe** [comment]
I'm seeing [mentions](https://stackoverflow.com/a/39456731) of these "unwind tables" potentially affect stacktrace generation as well, so might be worth checking to see that any such things in Godot are still working as expected, if applicable.

**Comment by akien-mga** [comment]
> I'm seeing [mentions](https://stackoverflow.com/a/39456731) of these "unwind tables" potentially affecting stacktrace generation as well, so might be worth checking to see that any such things in Godot are still working as expected, if applicable.

Indeed, I would enable this only when using `debug_symbols=no`, since the stacktraces are useless anyway without debug symbols.

Currently we build everything with `debug_symbols=no` for official builds, but we should move towards actually building with debug symbols, extracting them, and providing them for download on-demand to make sense of stacktraces. When we do that, this may indeed remove the possibility to disable unwind tables fully. But we could consider doing that for `target=template_release` only.

**Comment by akien-mga** [comment]
Note to self, or Yuri: Worth cherrypicking IMO, but we might want to make `disable_exceptions` false by default to preserve the existing behavior. Otherwise this could be seen as breaking compat for users with C++ modules using exceptions. Official builds could turn on the option.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2. Disabled by default, as suggested.
