### PR TITLE
Show valid types in SceneTreeDialog

### LINKED ISSUE #62483: Can't tell expected node type without looking into the script
### Godot version

5ab59ee

### System information

Windows 10 x64

### Issue description

When you export Node (after #62470), you can't tell what type it expects from looking at the inspector:
image
Moreover, when you click Assign, you see list of nodes and the wrong types are disabled. But if there is no expected type in the list, you don't know what type it wants. You need to look into the script.

In the inspector, we could have an icon of the expected node type.
In the scene picker dialog, the type could be in the title.

### Steps to reproduce

1. Export some Node type variable
2. Forget the type
3. Try to assign it

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
When picking node for Node/NodePath property, allowed type is now displayed at the top:
image

Multiple types:
image

Closes #62483

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` e8aa8c17d289097e24734a28f3bf9e806fd8a944), it works as expected.

image

Code looks good to me at a glance.

File: editor/gui/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1486,8 +1487,48 @@ void SceneTreeDialog::popup_scenetree_dialog() {
...
+		hflow->add_child(trect);
+		trect->set_expand_mode(TextureRect::EXPAND_IGNORE_SIZE);
+		trect->set_stretch_mode(TextureRect::STRETCH_KEEP_ASPECT_CENTERED);
+		trect->set_meta("type", type);
+		valid_type_icons.push_back(trect);
+
+		Label *label = memnew(Label);
+		hflow->add_child(label);
+		label->set_text(type);
+		label->set_auto_translate(false);
```
Comment (YuriSizov) [inline editor/gui/scene_tree_editor.cpp:1522]: We should group them in hbox, otherwise the label and the icon can end up on separate lines.

image

**Review by YuriSizov — APPROVED** [review]
One thing needs addressing, otherwise should be good.

I'm a bit concerned about the usability if you have many different types listed, but I guess we can assume this to be a rare/edge case.

**Comment by YuriSizov** [comment]
You have shadowing issues 🙃

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
