### PR TITLE
Fix crash when rearranging filtered animation tracks

### LINKED ISSUE #99713: Godot crashes when re-arranging nodes in the list of AnimationPlayer with some timeline options active.
### Tested versions

- v3.6.stable.official [de2f0f147] (Official latest release)
- v4.3.stable.official [77dcf97d8]
- v3.6.stable.custom_build [de2f0f147] (custom latest build from Spine - Esoteric Software)

Crash happen in these three releases, traversing major Godot revisions.

### System information

Windows 10, Godot v3.6/v4.3 stable official, Nvidia 1070.

### Issue description

Re-arranging entries in ActionPlayers is usually required to sort the list in a convenient way mostly when there is a lot of nodes involved. I use it combined with the Funnel filter (**Only show tracks from  nodes selected in the tree**) and the List filter (**Group tracks by node or display them as plain list**).

Those filters helps to have a compact view of the ActionPlayer and manage nodes selectively since I have projects sometimes with a hundred entries in ActionPlayers,

I am experiencing crashes when the re-arrangement is made to certain locations in the ActionPlayer tree.

### Steps to reproduce

For testing I have included a Minimal reproduction project below or you can follow all these steps:

- Create a 2D scene. Create four Node2D nodes under the root node (name those as 1, 2, 3 and 4).
- Create an ActionPlayer and into it a new animation.
- In the animation create a Visibility property keyframe in frame 0 for the nodes 1, 2, 3 and 4.

- Activate the Funnel and List icon filters (**Only show tracks from nodes selected in the tree** and **Group tracks by node or display them as plain list**)

- In the scene node tree select nodes 1, 2 and 4 (not 3). Then you will see only three entries in the ActionPlayer.
- In the ActionPlayer, drag the first node track right under the last track. The crash must happen.

This also occur in different ways to re-arrange tracks, not only when moving a track to the bottom location.

Thank you for your time.

### Minimal reproduction project (MRP)
```
[gd_scene load_steps=2 format=2]

[sub_resource type="Animation" id=1]
resource_name = "New Anim"
tracks/0/type = "value"
tracks/0/path = NodePath("1:visible")
tracks/0/interp = 1
tracks/0/loop_wrap = true
tracks/0/imported = false
tracks/0/enabled = true
tracks/0/keys = {
"times": PoolRealArray( 0 ),
"transitions": PoolRealArray( 1 ),
"update": 1,
"values": [ true ]
}
tracks/1/type = "value"
tracks/1/path = NodePath("2:visible")
tracks/1/interp = 1
tracks/1/loop_wrap = true
tracks/1/imported = false
tracks/1/enabled = true
tracks/1/keys = {
"times": PoolRealArray( 0 ),
"transitions": PoolRealArray( 1 ),
"update": 1,
"values": [ true ]
}
tracks/2/type = "value"
tracks/2/path = NodePath("3:visible")
tracks/2/interp = 1
tracks/2/loop_wrap = true
tracks/2/imported = false
tracks/2/enabled = true
tracks/2/keys = {
"times": PoolRealArray( 0 ),
"transitions": PoolRealArray( 1 ),
"update": 1,
"values": [ true ]
}
tracks/3/type = "value"
tracks/3/path = NodePath("4:visible")
tracks/3/interp = 1
tracks/3/loop_wrap = true
tracks/3/imported = false
tracks/3/enabled = true
tracks/3/keys = {
"times": PoolRealArray( 0 ),
"transitions": PoolRealArray( 1 ),
"update": 1,
"values": [ true ]
}

[node name="node_2d" type="Node2D"]

[node name="1" type="Node2D" parent="."]
modulate = Color( 1, 1, 1, 0 )

[node name="2" type="Node2D" parent="."]
modulate = Color( 1, 1, 1, 0 )

[node name="3" type="Node2D" parent="."]
modulate = Color( 1, 1, 1, 0 )

[node name="4" type="Node2D" parent="."]
modulate = Color( 1, 1, 1, 0 )

[node name="animation_player" type="AnimationPlayer" parent="."]
"anims/New Anim" = SubResource( 1 )
```

### PR DESCRIPTION
**Pull request by Nallebeorn**
Fixes https://github.com/godotengine/godot/issues/99713.

The root cause was using the real track index (unaffected by filtering) to index into a list of track edit controls (potentially smaller when filtered). Curiously, other than the crash when dropping a track at the bottom the correct control still somehow received focus. This is because there was another opposite index mixup cancelling it out: `_update_tracks()` fetched the index of the selected edit control but treated it as a real track index.

I found at least one other edge case bug fixed by this PR, that I found no open issue for: Pasting a key via the Edit menu with a track selected and node filtering enabled would paste the key into the wrong track.

For convenience, pre-packaged MRP (original issue provided it as a .tscn code block): 
[animation-player-crash_2025-10-08_21-27-00.zip](https://github.com/user-attachments/files/22784760/animation-player-crash_2025-10-08_21-27-00.zip)

### CODE REVIEW

**Review by TokageItLab — CHANGES_REQUESTED** [review]
It is good that you identified the cause.

However, having two retrievable values to manage should be avoided from a maintainability perspective. So I believe the issue should be resolved by changing the update timing or adding resetting the state.

**Comment by Nallebeorn** [comment]
> It is good that you identified the cause.
> 
> However, having two retrievable values to manage should be avoided from a maintainability perspective. So I believe the issue should be resolved by changing the update timing or adding resetting the state.

I'm with you that having two retrievable indices could get confusing. I don't think I understand what you mean with your alternatives though, can you elaborate a little?

In the end there are two different vectors involved (`track_edits` and  `Animation.tracks`) which sneakily can be access with the same index _most_ of the time, until you happen to have a filter. As long as that's the case I think it's very easy to use the wrong index by mistake. The problem could be avoided by always keeping `track_edits` the size of `Animation.get_track_count()`, adding null or hidden controls for the filtered-out tracks, but that seems bad for other reasons.

I could probably also drop `get_track_edit_selected` and instead do the loop inline in `set_animation` when finding the control to release focus from (it's not really needed elsewhere). But I kinda feel like for maintainability, leaving just one retrievable index (without any other refactoring) just leaves the door wide open to accidentally use that to index into `track_edits` again?

**Comment by TokageItLab** [comment]
> I could probably also drop get_track_edit_selected and instead do the loop inline in set_animation when finding the control to release focus from (it's not really needed elsewhere).

So in other words, I assume you can remove the focus immediately before filtering.

**Comment by Nallebeorn** [comment]
> So in other words, I assume you can remove the focus immediately before filtering.

Mmm, do you just mean you'd prefer it like https://github.com/godotengine/godot/pull/111427/commits/fa81a0afaa51e3fe11baef765d37283814daf4bb (temp commit for discussion purposes)? I feel like you have something more different in mind 😅

**Comment by TokageItLab** [comment]
I think that's a similar way. So if there's something that keeps fetching the index, I believe the simplest approach to solve the issue is to abort that fetching by initialize the state.

**Comment by Nallebeorn** [comment]
Okay. So the actual error locations before were
1. Passing a animation track index into the `_track_grab_focus` signal callback, while the callback treated it as a `track_edits` index
2. `_update_tracks` fetching the currently selected `track_edits` index, but then comparing it against animation track indices (it does this to focus the correct control after reinitializing `track_edits`.)
3. `_anim_duplicate_keys` and `_anim_paste_keys` fetching the selected `track_edits` index, but then using it to manipulate the actual `animation` tracks

As seen in the last commit, it's easy enough to get rid of the need to fetch the selected `track_edit` index, but the places that are (or should be) fetching the real animation track index I think are not so easy. Currently the only way to know which track is selected is to derive it by finding the focused control, like `_get_real_track_selected` does. I'm not sure what state I can initialize to simplify the logic in these places?

**Comment by TokageItLab** [comment]
I assume you just need to process sequence to remove all filtering in TrackEditor, perform the sort, and then reapply the filtering.

If maintaining an index for sorting is necessary, creating a temporary local array within the function should be fine.

The main thing to consider here is that the state of the filtered list after sorting and then removing the filter is undefined. For example, if changes like the following occur, the final result could be one of several possibilities:

User's operation:
```
1234 -[enable filtering]-> 124 -> 241 -[disable filtering]-> ????
```

then

`3241` or `2341` or `2431` or `2413`

If we want consistent results, I think you can ensure that filtered items always appear at the top like `2413`.

Actual behavior on sort filtered `124` to `241`:
```
1234 -[enable filtering]-> 124 -[disable filtering for sorting]-> 1234 -[Sorting]-> 2413 -[re-enable filtering]-> 241
```

**Comment by Nallebeorn** [comment]
Currently it's actually dependent on where exactly you drop the dragged track. It's always placed next to the track you drop it onto, either directly before or after it depending on which half it's dropped at:

https://github.com/user-attachments/assets/6eca5e5b-897c-4efc-bc7e-170c0b86f903

I believe this is working about as well as it can, so I don't think this behaviour should change. It's not really affected by this bug, since even before this PR the operation of rearranging the animation tracks itself was always dealing only with unfiltered indices (and then it got things mixed up when trying to manage the UI focus).

**Comment by TokageItLab** [comment]
Yeah, that should be fine for the reordering.
So if the steps described above are processed correctly internally, crashes should not occur.

> remove all filtering in TrackEditor, perform the sort, and then reapply the filtering.

File: editor/animation/animation_track_editor.h [hunk 1]
```diff
@@ -639,7 +639,7 @@ class AnimationTrackEditor : public VBoxContainer {
 
 	bool animation_changing_awaiting_update = false;
 	void _animation_update(); // Updated by AnimationTrackEditor(this)
-	int _get_track_selected();
+	int _get_real_track_selected();
```
Comment (TokageItLab) [inline editor/animation/animation_track_editor.h]:
```suggestion
	int _get_track_selected();
```

There should be no need to distinguish anymore.

**Comment by Nallebeorn** [comment]
Cleaned up, squashed and rebased. Thanks for the review, diff is a bit smaller now.

**Review by TokageItLab — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
