### PR TITLE
Typed GDScript

### LINKED ISSUE #1039: Code Completion Not Working for Sub-classes or Other Files
OK, so it seems like code completion only works for built-in classes and types. If you define a sub-class in a GDScript file, you can't access that class's members or functions. Also, if you define anything in a GDScript file itself (using the file itself as the "class"), you won't be able to get any completion on its attributes. An example would be

```
const STATE_RELEASED = 3
```

in `input.gd`, and trying to use

```
var input = preload("res://input.gd").new()
```

to refer to the file. Printing out `input.STATE_RELEASED` works, but the completion displays nothing from the `input.gd` file.

### LINKED ISSUE #10630: Optional typing in GDScript
I don't know if this would be needed or interesting to any developer, but I think it might be useful to have optional typing in GDScript and was hoping to have a discussion about it here.

I've been learning the programming language called "Nim" because it has a pretty friendly module for GDNative and I'm interesting in learning to contribute there (since C++ is difficult for me visually BUT unrelated to this, just some background). Nim is statically typed which I know GDSCript is dynamic but I came across a situation in which I might want to specify type to make things easier.

Mainly when writing a function, it'd be nice if I could specify the type of a variable that is allowed to be passed in so the code completion could know what I'm talking about, but I'm sure there are other advantages to this.

Something like
```gdscript
func myfunction(a, b : int, c : InputEvent , d : String = "Default Value"):
    (...)
```
Where a is dynamic, b-d are static but show what I think the syntax could look like.

I know you can specify type hint for the editor when using the export keyword, but you don't have to keep the variable at that type once the script executes. This idea could be against what GDScript is meant to be, or too much work for very little gain, but lets talk.

### LINKED ISSUE #13951: Code completion problem when accessing AutoLoads
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot Version: 3.0 Beta 1, 2.1.4 Stable
OS: Windows 8.1
Language: GDScript

**Issue description:**
So, there are 2 things that you can add to Autoload: Script and Scene
In my case as example, I have:
Autoload named Functions that is a script
Autoload named UISound that is a scene
autoload
And also there are 2 way to access AutoLoad:
1. Direct, example: `Functions.method_or_variable`
2. get_node(), example: `get_node("/root/UISound").method_or_variable`

So, here is the problem, I try to access the autoload Functions (that is a GDScript), I type `Functions.`
then press Ctrl + Space, the code completion / method and variable list appear.
scriptok
But, when I try to access the Autoload UISound (that is a Scene), 
then press Ctrl + Space, the code completion / method and variable list NOT appear.
scenenot

This is the more detail about this issue, also using Godot 2.1.4 and using Direct and get_node():

Godot 2.1.4:
1. Direct:
a. Scene (`UISound.`):
Not Appear.
b. Script (`Functions.`):
Appear
2. get_node("/root/..."):
a. Scene (`get_node("/root/UISound").`):
Appear, but not custom function from attached script
b. Script (`get_node("/root/Functions").`):
Appear, but not custom function from attached script

3.0 Beta 1:
1. Direct:
a. Scene (`UISound.`):
Not Appear.
b. Script (`Functions.`):
Appear
2. get_node("/root/..."):
a. Scene (`get_node("/root/UISound").`):
Not Appear
b. Script (`get_node("/root/Functions").`):
Not Appear

**Steps to reproduce:**
1. Make a scene, attach script, and add it to Autoload
2. Make a script, add it to Autoload.
3. Try accessing the Autoload from another script

**Link to minimal example project:**

### LINKED ISSUE #15088: Symbol completion problem in built-in code/script editor
**Godot version:**
Godot 3 beta 2

**OS/device including version:**
Dev OS: Windows 8.1

**Issue description:**
Symbol completion (Ctrl + space) not showing in some case.
Example:
Completion for variables with values, as example I use string
symbolcompletion3b2
In previous version (2.1.4) it works:
symbolcompletion214
Also happen with other variable type like Array, Vector2, etc

Note:
Completion work when accessing node member.
Tho completion not showing, but the script work when you type it yourself (manually)

**Steps to reproduce:**
Just type script in build-in script editor

**Minimal reproduction project:**

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+script+completion) for potential duplicates.

### LINKED ISSUE #16257: No code completion on obvious case
Godot 3.0 stable

With the following code:
```gdscript
extends Panel

func _ready():
	var f = File.new()
	f.
```

When I type the final dot, nothing comes out.
In 2.1.4 I get auto-complete straight away.

Note 1:
If I write `open("test.txt")` and attempt to Ctrl+Click on `open`, nothing happens.

Note 2:
it seems to happen in more places where completion used to work, like `onready` vars assigned with `get_node`.

### PR DESCRIPTION
**Pull request by vnen**
**Alright, big change coming! Let me add a bit of documentation in here.**

## FAQ

Things people asked me during the development.

- **Is it optional?**

Yes. You can use GDScript dynamically as it is now. Type hints can be used only in parts of the code.

- **Will this affect my existing code?**

It shouldn't. If it does then it's a bug. Whenever a type check is possible it will make one, but this won't affect duck-typing. Lines that are fully type-checked are indicated by a highlight in the line number. However, GDScript was very lenient about some behaviors that can be considered an error, so your script might break if it relied on those behaviors.

- **Does it improve performance?**

As it is now: no. However, this enables the possibility of future improvements in performance. A set of benchmarks are needed before we go this path.

- **Can the syntax change to be like \<my favorite language\>?**

No, this was discussed at length before. The syntax is similar to Python. It's made to be easy to parse without changing the GDScript syntax in itself, considering the types are optional.

## Syntax

- Variable hint: `var my_int : int`
  - Optional inline initialization: `var my_int : int = 42`
  - Type can be omitted to be inferred from value: `var my_int : = 42`
- Also for constants (but not strictly needed): `const my_const : String = "Something"`
- Function declaration: `func (arg1 : int, arg2 : String = "") -> float:`
- Casting: `event as InputEventKey`
  - It returns `null` if the cast is not possible.
  - It errors out if trying impossible conversion between built-in types.

### Possible types

- **Built-in variant types** (`int`, `float`, `Vector2`, `Basis`, etc.).
- **Native classes from the ClassDB** (Node, Resource, Sprite, AnimationPlayer.
- **Scripts of any kind**, they can be preloaded into a constant, then the constant can be used as a type. includes inner classes in other scripts.
- **Named classes in the script server**, as added in GDScript with the `class_name` keyword. Includes their inner classes too.
- **Other classes in the current script** (the ones made using the `class` statement).

## Static checks

As long as there any type can be fully determined, the parser will try to detect mismatches. This will be shown as an error in the editor.

- Type mismatch when assigning to a variable.
- Type mismatch in function arguments when making a call.
- Missing or exceeding arguments for a function call.
- Operation in an expression.
  - Whether the operand types are valid for the operator (e.g. can't multiply `int` and `String`).
  - What is the resulting type of operation (e.g. `2 * 2` is an `int`, but `2 * 2.0` is a `float`).
- Whether the declared function matches the parent signature.
- Member variable shadowing one in the same or the parent class.
- Type mismatch between member variables and setter/getter.
- Constants and inner classes are in the same scope: if one shadows another they error out.
- Whether an inner class name shadows a native class from the ClassDB.
- Non-existing identifier/function.

Note that since this is meant to be fully optional and still compatible with duck-typing, it won't mark as an error if the member variable/method could be available in a subtype. Instead, **type-safe lines** will be marked with a subtle green tint in the number line. Non-safe lines will just not be marked:

## Completion

The code completion was rewritten to make use of the type hints, and also fixed many long-standing bugs. The code is now somewhat cleaner and easier to add new features. Some improvements:

- Better guessing based on assigned values (Fix #16257, Fix #15088).
- Guess type of function based on the returned value.
- Look inner classes too when guessing the type or finding candidates (Fix #1039).
- Look into other scripts/singletons. (Fix #13951)
- Use type-hints when they're available.
- Better definition/documentation lookup 

## Wanted feedback

Any feedback is welcome but there's some things in particular that I want to know. In any case it's great to have sample scripts for me to test.

- **It breaks the current code of your project.** This includes parser and compiler errors in general.
- **It doesn't detect a problem when it should.**
- **It does detect a problem when it shouldn't.**
- **It gives an error in the console saying "Parser bug".**
- **It is too slow in a big file or file with lots of dependencies.**

## Future

Before anyone asks, here's a bit of ideas for the future.

- Add types in signals, including type checks for `emit_signal` and `connect` calls.
- Improve completion inference and better use of type hints.
- Add warnings (#18271).
- Homogeneous collections (like `var int_array : int[]` as an array of integers).
- Optimizations for better performance.

----

Closes #10630.

### CODE REVIEW

**Comment by blurymind** [comment]
Fantastic addition! Thank you very much for working on this!

**Comment by Xrayez** [comment]
Some weird stuff when using `emit_signal`:
```gdscript
extends Node2D

var my_int : int = 10

signal my_signal(param1, param2)

func _ready() -> void:
	var p1 : int = 0
	var p2 : int = 1
	emit_signal("my_signal", p1, p2)
	
```
```
SCRIPT ERROR: GDScript::reload: Parse Error: Too many arguments for 'emit_signal()' call. Expected at most 1.
          At: res://Node2D.gd:10
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:579
```
```
ERROR: debug_get_stack_level_instance: Condition ' _debug_parse_err_line >= 0 ' is true. returned: __null
   At: modules/gdscript/gdscript_editor.cpp:288
```

**Comment by vnen** [comment]
@Xrayez seems I missed a check for varargs. Thanks for pointing it out.

**Comment by coppolaemilio** [comment]
I really want to like this because it seems like a lot of work but I don't think this is a good addition to gdscript. It will add more segmentation, a harder entry barrier and distance itself further more from Python. Imagine the confusion of new comers when they start watching tutorials of people who prefer typed and others that don't. Maybe it would be a good idea to separate this with a different extension? something like .gdt not sure. Maybe I'm just too much into Python.

**Comment by OvermindDL1** [comment]
> I really want to like this because it seems like a lot of work but I don't think this is a good addition to gdscript. It will add more segmentation, a harder entry barrier and distance itself further more from Python.

Considering it is both backwards compatible *and* it follow Python's Typed Syntax spec, how would it segment or distanct itself further from python?

Typing code is not a hard thing (though I would prefer if it were enforced, preferably with ML unification abilities ala OCaml or so would fit perfectly, hmm, maybe I should make an OCaml'ish native language interface...).

**Comment by vnen** [comment]
@coppolaemilio Python has the same syntax for optional typing, if anything this will bring GDScript *closer* to Python.

I don't think there should be that much confusion. Newcomers will probably just ask about it and learn while doing so. Since this is optional, both kind of tutorials and can even be mixed without (much) problem. There's a problem of mixing type hints and duck-typing, which may bring errors, but I still think people will just ask and learn. It doesn't sound like a big of a deal to me.

Also, I'm not sure if we should nuke a wanted feature because of potential newcomer confusion. There's a lot of positive reactions not only to this PR but also to the related issue and my posts on Twitter. We *know* those people like this feature, should we not add it because the confusion it *might* cause (which we don't know)?

If this were to be made into a separate file type then it would be better to make a new language altogether. But that would be a great effort in itself and really increase the fragmentation.

Of course, I have a bit of passion for a feature I wrote myself, but I'm still open to feedback. If for the greater good this is decided to be a bad thing I won't push it further.

**Comment by OvermindDL1** [comment]
For note, Python Typing:  https://www.python.org/dev/peps/pep-0484/
Near identical to how gdscript does it (in fact it does look identical from the bits I've seen so far), and yes that is in the Python standard and is supported by the cpython system (although cpython doesn't do much with the typing information, static analyzers do).

```zsh
╰─➤  python3 -i 
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def greeting(name: str) -> str:
...     return 'Hello ' + name
... 
>>> greeting("world")
'Hello world'
>>> 
```

**Comment by coppolaemilio** [comment]
Sorry guys, my bad! I wasn't aware that it was already implemented in Python.

**Comment by vnen** [comment]
Solved the issue with vararg functions. Hopefully fixed compilation/style issues as well.

**Comment by akien-mga** [comment]
The last build issue seems to be on Android, is there a missing `#ifdef TOOLS_ENABLED`?
```
modules/gdscript/gdscript_editor.cpp:57: error: undefined reference to '_EDITOR_DEF(String const&, Variant const&)'
```

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -54,16 +54,17 @@ void GDScriptLanguage::get_string_delimiters(List<String> *p_delimiters) const {
 }
 Ref<Script> GDScriptLanguage::get_template(const String &p_class_name, const String &p_base_class_name) const {
 
+	bool th = EDITOR_DEF("text_editor/completion/add_type_hints", true);
```
Comment (akien-mga) [inline modules/gdscript/gdscript_editor.cpp]: Android build fails here, but I guess the whole file should be in `#ifdef TOOLS_ENABLED`, and not just a handful of duplicate includes as done currently?

**Comment by volzhs** [comment]
[Typed GDscript autoload.zip](https://github.com/godotengine/godot/files/2055895/Typed.GDscript.autoload.zip)

@vnen This is crash sample project at starting editor.
It has simply 2 autoloads and the first one tries to access the second one.

**Comment by neikeq** [comment]
> - **It is too cumbersome to have static type check in a particular statement.** For instance, I removed it from `get_node()` to avoid having to cast every time you use it (specially with the `$` shorthand).

I think there is a design problem here. This is what you would expect in an statically type language. You get an instance up-casted to a base type. If you want to use the methods from the derived type, you have to down-cast it first. This is common in C#:

``` C#
var sprite = GetNode("/root/Sprite") as Sprite;
sprite.Centered = true;
```

This would be totally fine if the new GDScript were to be only statically typed. The problem is the intention is to be backwards compatible with dynamically typed GDScript. The above is [unacceptable](). This means `get_node("/root/sprite").centered = true` should be possible, so we have to treat return types as Variant until they are explicitly or implicitly cast. This means we don't truly have full optional typing.

Did you remove the need for the cast only from `get_node()` or from other methods as well?

**Comment by vnen** [comment]
@neikeq I'm still not entirely sure about that. Full static typing means that you can't do something simple like:

```gdscript
$AnimationPlay.play("animation")
```

This would give an error because Node does not have a `play()` function. Which is expected in a typed context. For this to work you would need an explicit downcast:

```gdscript
($AnimationPlayer as AnimationPlayer).play("animation")
```

I have a feeling that most of the time this would be cumbersome, especially if you are used to GDScript already. Maybe it's better if I remove this exceptional case and if people complain during usage I really change it.

> Did you remove the need for the cast only from get_node() or from other methods as well?

Only for `get_node()`, because it's a method used very often.

> [...] so we have to treat return types as Variant until they are explicitly or implicitly cast. This means we don't truly have full optional typing.

That's the catch: should type hints imply that GDScript is fully statically typed or should just be a convenience when assigned? The former sounds more sane but latter is more backwards compatible (and makes types truly optional).

The thing is that if you add a type hint your code is subject to static checks, which might raise a parse-time error somewhere even if the code worked flawlessly with dynamic typing. If that's what we want, I'm fine with it.

**Comment by magyar123** [comment]
My two cents is, that static type checks would be more fitting for GDscript with parse time errors only. Maybe we could use some of the type guessing in the auto complete, to handle specific cases, like get_node, better.

**Comment by eon-s** [comment]
`($AnimationPlayer as AnimationPlayer).play("animation")` is like putting salt and pepper over the syntax sugar...

**Comment by toger5** [comment]
O think if you want your script to be typed u would probably use onready vars which are of the correct type.
So i think it would be okay to have full static typing.
But since i can still do the cast although godot allows me to not do it, i would allow to use it without the cast.

**Comment by vnen** [comment]
@volzhs thanks for the repro, I fixed the issue.

File: modules/gdscript/gdscript_editor.cpp (hunk 1 above)
Comment (vnen) [reply modules/gdscript/gdscript_editor.cpp]: This really needs I cleanup, but since I intend to refactor the completion code anyway, I'll fix it then.

**Comment by volzhs** [comment]
@vnen 

```gdscript
const INDEX = ["index1", "index2", "index3"]
var dic = {}

func _ready():
	dic["index1"] = 1  # fine
	dic[INDEX[0]] = 1  # Parse Error: Only strings can be used as index in the base type 'Array'.

```

**Comment by vnen** [comment]
@volzhs oops, that was my mistake in a later change. Will fix right away.

**Comment by neikeq** [comment]
@vnen If type checks are only removed from `get_node()` and not other engine methods (not user defined), then the following is not true:

>- **Is it optional?**
>
> Yes. You can use GDScript dynamically as it is now. Type hints can be used only in parts of the code.
>
>- **Will this affect my existing code?**
>
>It shouldn't. If it does then it's a bug. Static type checks will only apply if you use type hints in your code. Note that if there's *any* type hint in the file, it'll assume to use static checks and might detect errors when you try to duck-type somewhere else.

I think we could mark a script as `typed` like we mark tool scripts to enable type checking for cases where it would break compatibility, like this situation with the return type of engine methods.

**Comment by swarnimarun** [comment]
Probably we can have Typed GDScript by default and then have a keyword to disable it.
Obviously only if it's the popular demand. And not just mine.

**Comment by cbscribe** [comment]
I definitely don't like it as the default. For beginners, GDScript's strength is its readability and low barrier to entry.

I really like the `typed` declaration idea. We can even have a toggle in the new script dialog to enable it, which would then be remembered for all your subsequent scripts, as with the templates.

**Comment by swarnimarun** [comment]
So the majority is against it. I thought as much. But it was worth a try, I like my code to be more readable by know what is what.
If the variable is an int I would prefer to know it by declaration rather than guessing from what value I assigned.
`var somevariable = 10`
`var anothervariable = 10.0`
One is int and the other float, I don't like it. And I don't thing that beginners will understand this at the start, I had experience with python so it was easier but I don't like duck typing always. But that's just me.

Anyways anything is fine by me.

**Comment by blurymind** [comment]
I am for it. 
It is more readable yes- especially when initializing functions..

It's just a drastic change of syntax to what is now a standard established by many tutorials online.
After release- when many people pick it up and tutorials are made on it- maybe then it might be pitched to become a default

**Comment by OvermindDL1** [comment]
Instead of doing Python style typing, keep the python style syntax but use full hindley-milner typing.  It is both really easy to implement and let's you leave out most of the syntax typing declarations in most of the cases anyway (I can help if needed, I've implemented hindley-milner typing about a dozen times over the years).

A prime example of a language with HM typing is OCaml, where you can leave out almost all typing declarations and the whole thing is still type-safe and sound (though many still like to type things as it is great documentation).  Could even swipe a few HM-extensions that OCaml uses as they are all crazy-fast to use in their design and very short both.  Something like the Polymorphic Variants or the Functors would be fun things to swipe (though if you take much more then you may as well embed OCaml 'as' the scripting language at that point, which could be done, except it can already compile to either bytecode or native assembly already).

**Comment by mrcdk** [comment]
To solve the `get_node()` issue we can add a special type that behaves like dynamic typing but let you specify a base type. Something similar like a constrained type parameter for that special type.

So `get_node()` returns a `Dynamic<Node>` which by default it's a `Node` (the autocompletion will give you all the Node stuff) but it still let you use duck typing. It'll let you do something like `$AnimationPlayer.play("anim")` With this, it's up to the developer if they want to correctly type it or not. We could even use `Variant<Node>` or something like that.

**Comment by vnen** [comment]
@neikeq 

> I think we could mark a script as `typed` like we mark tool scripts to enable type checking for cases where it would break compatibility, like this situation with the return type of engine methods.

The way it is now is that it's fully typed if you use any type hints, fully dynamic otherwise. So it is true that current code would work without any change. While "Type hints can be used only in parts of the code" is true, you might need some casting in the non-typed part.

If people prefer a `typed` keyword, then we might as well go with full inference and everything is statically typed unless told otherwise. But it also becomes like another language, you can't partially apply type hints.

The thing about `get_node()` (which is temporarily disabled BTW), is that it's a very Godot-specific construct. It depends on the scene where the script is attached, rather than the script itself. You know it's a Node, but which specific type is only known at runtime. Maybe we could guarantee some tree restrictions so `get_node()` knows beforehand the expected type, but it would be more troublesome than anything I believe.

The other methods where dynamic types might play a role are much less of a hassle to explicit downcast (like `_input()` callback or physics collision signals), since you usually do some checks anyway.

Also note that this is only a thing if you are *directly* accessing a member from the result of a function call (or a given callback argument). Something like this wouldn't be a problem even in a typed context:

```gdscript
var anim = $AnimationPlayer
anim.play("animation")
```

Because `anim` is declared without types so it's considered a Variant.

**Comment by vnen** [comment]
So up for discussion, which is the preferred:

1. Static checks apply fully if any type hint is used, otherwise it's fully dynamic like good ol' GDScript. This is how it is now in this PR.
2. Same as 1, but with a few exceptions (like for `get_node()`).
3. Use a `typed` keyword to mark the script, then variables types are inferred (`var a = 2` will force `a` to be `int`; `return 0` will force the function to always return `int`). Hints can be specified if needed. Hints in a non-typed script raise an error. (This won't be the default because it would break every existing project).

**Comment by letheed** [comment]
I'm not sure I understand very well. What's the difference between 1 and 3, aside from static analysis being triggered by type hints for 1 and `typed` for 3?

Either way I'd rather not have to cast when using `get_node` or `$Node`. I'd use C# or another language if I wanted strong typing, not GDScript.

**Comment by vnen** [comment]
> I'm not sure I understand very well. What's the difference between 1 and 3, aside from static analysis being triggered by type hints for 1 and typed for 3?

For 3 I would do full inference. With 1, if you don't add hint to particular variable it will be a Variant (i.e. can have any type). With 3 the variable type would be assumed to be the same type of the value assigned on initialization (i.e. `var a = 1` is equivalent to `var a : int = 1`).

> Either way I'd rather not have to cast when using get_node or $Node. I'd use C# or another language if I wanted strong typing, not GDScript.

Well, in any case you can still use GDScript like you do now, nothing needs to change. The point is only important if *do want* static typing.

**Comment by mrcdk** [comment]
Is a constrained `Variant` to a base type (`Variant<Node>` or `Variant[Node]` python-like) out of the question then? If it is then I choose 3.

**Comment by letheed** [comment]
> For 3 I would do full inference. With 1, if you don't add hint to particular variable it will be a Variant (i.e. can have any type). With 3 the variable type would be assumed to be the same type of the value assigned on initialization (i.e. var a = 1 is equivalent to var a : int = 1).

Thank you for clarifying, that's what I thought, but I wasn't sure. So I don't really see how 1 and 3 are contradictory. Are they incompatible? Type hints trigger typing of some items, `typed` just forces it for everything.

> Well, in any case you can still use GDScript like you do now, nothing needs to change. The point is only important if do want static typing.

Yeah, I do very much! :) I was very happy to find out when it was the first voted items by patrons last year. I find dynamic code bases hard to maintain beyond a few thousand lines, especially refactoring. And GDScript makes it a bit harder still since it's not really possible to do TDD like in other languages. I love it though, so I'm looking forward to this very much.

The way I see it, 2. is the closest to the original spirit of the request, and the language. Maybe that decision warrants a bit more exposition and feedback on SNs.

**Comment by vnen** [comment]
@mrcdk 
> Is a constrained Variant to a base type (Variant<Node> or Variant[Node] python-like) out of the question then? If it is then I choose 3.

TBH I don't see how that can be helpful (apart from `get_node()` itself). It adds complexity and removes the power of the static checks, since it can no longer detect when you access a member that does not exist.

**Comment by YeldhamDev** [comment]
I think **2** would be the most useful, as it allows to use typing in specific places that it would be useful, while leaving other alone.

**Comment by vnen** [comment]
Forgot to mention, but there's possibility number 4: use a new construct to allow type inference, like `let a = 1` or `var a := 1`.

**Comment by vnen** [comment]
> So I don't really see how 1 and 3 are contradictory. Are they incompatible? Type hints trigger typing of some items, typed just forces it for everything.

They are not mutually exclusive, but I don't see much of a point of maintaining both. I think it could lead to confusion by having multiple ways to do the same thing.

**Comment by swarnimarun** [comment]
I go for 4.
It's just better to not have worries of var becoming something else.

**Comment by swarnimarun** [comment]
@petkovsc I am sorry but C++ is in no way easier to read for me, however it makes more sense at times but python is much better for readability. Probably I started out with Java.

If you don't think so then you must be a genius.
`for x in my_list: = gdscript/python`
C++,
`for (List<Node *>::Element *E = my_list.front(); E; E->next()) = C++ from the engine code`

**Other than that I absolutely agree that GDScript has duck typing** which makes **lots of things more difficult**. I would prefer static typing any day, and I concur with all of your points other than the C++ one.
I don't want any C++ syntax or typing specifically but more clear and direct typing will be awesome.
Like `int someNumber`

But I can live with Python-like static typing, too. I just want this feature.

**Comment by chanon** [comment]
I'd prefer having a project setting to set whether the scripts in the project are to be considered typed or not by default. 

If typed, I'd prefer all variable types to be inferred. There would be a `variant` type hint for variables that the developer wants to be `variant`. This is similar to TypeScript's `any` type with noImplicitAny which helps catches a lot of bugs.

There should be some way so that `get_node` when used as `self.get_node("/static/path/to/node")` or $NodeName should know the type of the actual node in the scene. Problem is the scene file knows what .gd file it uses, but the .gd file doesn't know what scene file it is being used with. Maybe a line at the top to declare the scene file to use? This would be automatically added by the editor.

Otherwise get_node will have to be of return type `variant` so you don't need to cast it all the time if you don't want to.

**Comment by chanon** [comment]
Actually TypeScript has many options so people can set how strict they want it to be. While it is additional code, it might be the best way so people can choose.

**Comment by letheed** [comment]
@chanon 

> There should be some way so that get_node when used as self.get_node("/static/path/to/node") or $NodeName should know the type of the actual node in the scene

Nodes can be instanciated/added/removed dynamically. There's no way to know about the type of those ahead of time.

**Comment by chanon** [comment]
@letheed I know. But the most common use case is as I stated where you are getting a node with a static path as self.get_node("/static/path/to/node") or using $ syntax as $NodeName. In those cases (which is the most common case) it can be known the actual node type by looking it up from the scene file.

**Comment by samdze** [comment]
@chanon Intellisense does this referring to the currently open scene. The scene_file declaration sounds not like a good idea to me as multiple scenes can have the same script attached.

I don't like the `typed` keyword option. I'd go with 2, the editor could also suggest already casted auto-completions based on the type of the assigning variabile (if declared with a type).
Also the keyword `let`, or maybe `auto` (sounds better to me), for type inference seems good.

**Comment by chanon** [comment]
Again, yes, multiple scenes can have the same script attached, but the most common case is that each script is paired with one scene file.

However I understand if people say it may not sound like a good idea.

**Comment by reduz** [comment]
Here is my take on the typed GDScript approach. I think we should first focus on the use cases for it to understand what the best solution for this might be. The goals for having typed GDScript is:

* Be optional, to keep GDScript ease of use as priority, specially for simple scripts
* Help on more complex scripts, specially to catch bugs beforehand
* Provide an improvement to code completion
* Eventually allow typed parts of the code to be optimized (typed code can have custom bytecode to make it much, much faster).

I still think GDScript should always be non-typed first as a priority, so when accessing properties or calling functions of objects, it should not fail compilation (for properties or functions of built-in types, it's fine it does since there is no chance it may appear later).

get_node("anim").play() should _never_ be an error, even if the type is known, else GDScript would not be dynamic first and typed second. Of course, if you are writing typed code, this can be an annoyance.. so this is clearly a design contradiction.

When I was thinking about doing typed GDScript, the solution to this problem to me was more about thinking out of the box. Please read the following proposal, as I think it will make sense once you reason it:

### Introducing "Safe" code

Godot editor should, instead should include the concept of "safe" code. This means, it should mark in the text editor somehow which lines are _safe_. 

If a line of code uses typed code and all types, functions, etc. are known then it's considered safe, it may have a slight highlight of the background color in the editor, something like this:

image

The concept of _"safety"_ solves many problems at the same time:

* Users can tell the code they are writing is actually safe. Of course type errors that _can be catched_ (like assigning a string to a float) will still be just errors, as that has nothing to do with safety.
* Eventually, when we add custom bytecode support for typed instructions, users will feel relieved that the code market safe will _always execute much faster_, by using those typed instructions, so it will be very useful for optimization too.

So, in the case of get node or similar situations, if you don't get an error and the code is not market safe, then it should be pretty obvious why.

**Comment by samdze** [comment]
@reduz I really like this "Safe" code approach, we could make use of the empty space left to the line number in the script tab editor to show a line indicating which lines are safe together with the breakpoint points:
safe_lines_mockup
Maybe it's a little too much visually invasive with this tickness and color, but you get the point.

**Comment by chanon** [comment]
I think this "Safe" code idea can be a great middle ground between 
- those who want to keep the dynamic freedom of normal GDScript and to be sure all old code will run fine
- and those who want full strict type safety

As @reduz said, typed GDScript should be optional. So having code that is not type safe just marked as such is enough. It doesn't have to fail and not run. Actually, even if there is a type error (string used for int), the code can still run (no need for type check failures to cause the game to be un-runnable). For example TypeScript will generate all JavaScript code even if it finds type errors. In this way the type checks are truly optional.

Now, what I wish would be added in this case for those who really want full type safety is maybe to have a project setting / option to tell the type checker to output 'warnings' to the output for all lines that are not "Safe".

This way instead of having to scan every line of every file in the editor, you can just see if there are any "Unsafe" warnings.

**Comment by reduz** [comment]
@chanon I think having unsafe warnings is more troublesome because GDScript _is_ unsafe by default.  Marking safe code IMO is the best approach. Many users will probably not care so much about safety for most code or only use it to get better code completion, unless writing optimizing code for a more critical function.. then I think marking safe is a better bet. 

I was thinking of a very subtle highlight as probably the best solution, as otherwise something on the left  side of the screen may easily go ignored.

**Comment by chanon** [comment]
@reduz, as I said, having it output unsafe warnings would be an option. By default it would be disabled.

**Comment by reduz** [comment]
@chanon but you will never be able to have full type safety on GDScript due to how it works (like, arrays and dictionaries are unsafe.. we may add typing for them in the future but many APIs just return unsafe).

Again, if this is a very slight hilight, it should be fine IMO.

**Comment by chanon** [comment]
@reduz for Arrays and Dictionaries, they would be the same as get_node() where to make it type safe you would have to cast it. That would be a crazy amount of casting though so I see your point. If the Type checking system allows to define typed Arrays and Dictionaries (and objects .. like in TypeScript) then it would make more sense.

**Comment by chanon** [comment]
Regarding type inference, in this case I think we can be aggressive since the game will always run anyways. So going back to @vnen 's options I would choose 3.

But I would still prefer the option to enable type checking for all .gd files via a project setting rather than putting typed at the the top.

**Comment by vnen** [comment]
I'm gonna implement @reduz's idea. It's probably the best of both worlds without having to resort in a hard choice between typed and dynamic for each file.

My intention is to eventually add a system for warnings, which will make you easily find unsafe code (among other things).

**Comment by samdze** [comment]
Another way to point out safe lines is to highlight the line number, which makes sense, is not invasive. it's easy to notice if you want to, and the line number is embedded in the information you are looking for:
safe_lines_mockup_2
Highlighting the entire line can result in multiple highlight types one over the other, error highlight, selection highlight, safe line highlight, and may be confusing.

**Comment by eon-s** [comment]
I like the safe indicators but need to differentiate from breakpoints and errors (not red and not on the same position).

**Comment by petkovsc** [comment]
I have class files that do not define any member variables, local variables, nor function declarations (e.g. singletons, input handlers). Yet I definitely want type checking in case I write an invalid function call into these classes. 

It would be nice to have an explicit way to turn on type checking. A preprocessor directive on every file is ok. But a project setting is ideal, as others have mentioned. Defining a variable to turn on type checking seems pretty hacky.

Thanks @vnen for implementing type checking!

**Comment by vnen** [comment]
> I have class files that do not define any member variables, local variables, nor function declarations (e.g. singletons, input handlers). Yet I definitely want type checking in case I write an invalid function call in these classes.

Well if you don't have any member variables nor functions, how come the class is calling anything?

In any case, the problem is: how can GDScript know if a function call is invalid if it doesn't know the types? As long as it *can* figure out the types, it'll raise an error, otherwise it can't really do anything.

What will happen is the following: if you do `$Sprite.get_child("string")`, it'll raise an error since `get_child()` from Node accepts an integer. But if you do `$Sprite.rotate("string")` it won't be able to find the `rotate()` function in Node (since it's defined on Node2D), so it won't raise any error.

Again, the idea is to implement a system to display warnings, which will let you know about those unsafe lines so you can potentially fix them.

**Comment by chanon** [comment]
I think what petkovsc means is what if $Sprite.get_child("string") was done in a file that had no type hints.

**Comment by chanon** [comment]
BTW I think this supports option 3 (aggressive type inference for vars) as for files that have no type hints such as old GDScript code nothing bad will happen to them (unless project setting is turned on to enable type checking on all files)

**Comment by petkovsc** [comment]
@chanon interpreted me correctly.

@vnen  
> Well if you don't have any member variables nor functions, how come the class is calling anything?

My input handler references only global objects or inherited functions. It does override _input, so perhaps we'll now have to specify the full type to override functions now, and that could trigger typing. 

> But if you do $Sprite.rotate("string") it won't be able to find the rotate() function in Node (since it's defined on Node2D), so it won't raise any error. Again, the idea is to implement a system to display warnings, which will let you know about those unsafe lines so you can potentially fix them.

I don't know if the safe code highlighting will help me on my projects or not. You guys know more about it than I do, so if you think it's good, then great. Here's what I do know:

The biggest frustration for me is that I can type $Sprite.invalid_func() in function X, press F5 and it runs. At least until function X is called, then it crashes mid game because of an error that should have been caught right away by the parser. 

I'd prefer it work like a compiler and not run until the function call is fixed. This behavior already exists in godot for some cases. For instance, in function X above, I can type "m = Vector(3,4)" and it does not give me any code highlights. But F5 errors with "Parser error: identifier m not found". Great! The highlighter should have caught it too, but at least the parser caught it. If I add "var" to the front, now it runs until function X is called, then dies because there is no Vector. Not great.  :(

That's really all I'm hoping to see fixed: typing errors that would cause the game to crash mid-game are instead flagged at parse time. And the option for a project wide setting would be preferable, so it forces me to define types on all files.

All the other topics like safe code highlighting, duck-typed arrays and dictionaries, etc I don't know much about, so trust you guys will make the right decision.

**Comment by neikeq** [comment]
I think `instance as Type` should be changed to `instance.cast(Type)` (or `instance.as(Type)`, but I prefer "cast"). This way you avoid the annoying parenthesis:

``` GDScript
# Can be annoying to write. You usually don't think about casting at first, so you end up going back to add the first parenthesis
# This is why we are going to add genetic GetNode to the C# API
(instance as Type).Property = value

### vs

# One less char and easier to write. Not the best naming IMO
instance.as(Type).Property = value
# One more char but easier to write. Better naming than 'as'
instance.cast(Type).Property = value

### A bit longer when no parenthesis are needed
var sprite : Sprite = instance as Sprite
var sprite : Sprite = instance.as(Sprite)
var sprite : Sprite = instance.cast(Sprite)
```

There does not seem to be type inference right now. I think this would improve code a lot:

``` GDScript
var str : String = "something"
var str = "something"

var sprite : Sprite = get_node("s") as Sprite
var sprite = get_node("s") as Sprite
```

I think `var` would refer to Variant (dynamically typed), not variable, so maybe:
`let sprite = get_node("s") as Sprite`.

**Comment by AndreaCatania** [comment]
I think that we should use the shortest possible solution, and I think "as" as keyword is not bad.
Also `instance.as(Type).Property = value` seems a bit weird to me (it seems like a function call..)

> I think var would refer to Variant (dynamically typed), not variable, so maybe:
let sprite = get_node("s") as Sprite.

This could be a good idea, but we have to introduce another keyword... way easier if you use `Type variable_name` at this point

**Comment by chanon** [comment]
Casting with `as` I think makes sense since we already have `is` keyword and their syntax would be similar.
`$NodeName as Sprite` and `$NodeName is Sprite`

`Sprite sprite = get_node("s")` looks like C++ code and I don't think it communicates visually that `get_node("s")` was casted. Also it is a syntax that would only be used for initialization.

If you want to call a method on the sprite then you can't use that syntax anyways, you would still need to do `(get_node("s") as Sprite).texture = new_texture`

**Comment by neikeq** [comment]
@AndreaCatania I don't think `let` as a new keyword would be a problem. I don't think the cast using a function call syntax is a problem either, it's the same in the C++ API.
What about the following syntax for casting return types? `get_node!Sprite("note/path")`. Not to be confused with generics, it's just a a syntax sugar for `get_node("node/path") as Sprite`:

``` GDScript
(get_node("path") as Sprite).Property = value
# vs
get_node!Sprite("path").Property = value
```

**Comment by chanon** [comment]
I still wish for the `scene_file` idea to be implemented though. 

If it was worth it and useful enough to implement the ability for intellisense to automatically look up node types when using $NodeName and get_node("/static/path/to/node"), then it is surely worth it to make the Type system be able to get the same info. And the reason it was worth it for intellisense because using $NodeName and get_node("/static/path") is the most common case.

It will cut away on so many (get_node(...) as TypeName) casts and help a lot code to be "Safe" automatically.

Yes, there are cases where the the node may not exist in the scene yet (to be dynamically created later) or the get_node parameter is a dynamic variable. In those cases the code would just be marked "Unsafe" and then you can do a cast to make it safe.

**Comment by neikeq** [comment]
> Also this kind of `as` syntax is used in other languages (including C# and TypeScript) so I think will be easy for people to understand.

The problem with the `as` keyword is that it's cumbersome when you want to cast the return type of a method and reference a member directly on it.

**Comment by chanon** [comment]
@neikeq as long as it is just syntax sugar and people like it, then that is good. Actually even function call style is ok with me as long as normal `as` syntax is available.

Also `let` keyword is good. Though as I said, in JavaScript it has a different meaning.

**Comment by neikeq** [comment]
@chanon It has another different meaning in Swift too. Its meaning in GDScript would be similar to Rust. It's a good thing we get used to it, since we are going to re-write Godot in Rust for the 25.0 release.

**Comment by chanon** [comment]
If Rust uses it in a similar way, then that's great! I would go for `let` then.

**Comment by AndreaCatania** [comment]
@neikeq hmm I don't know.. it seems completely different thing from a cast
of course if you know what it is, you are fine, but I think that for new users it has no sense.. I prefer a lot more this form `(get_node("path") as Sprite).Property = value` even if I prefer c++ style (but I know that it should be more similar possible to python so it's ok for me).

Also "let" could be a good idea, but I've few concern,
E.G. what if I want pass a "let" to a "var"? (this could be a possible question by a new user)
The other is that if I've to apply it to an old script it require me to write more...

In other Godot features I remember that we went for the solution where name of variable/function was simple, and we written the full description of it in the docs, so we don't need to focus a lot to make it so explicit that it's "safe code"

**Comment by chanon** [comment]
> Also "let" could be a good idea, but I've few concern,
> E.G. what if I want pass a "let" to a "var"?

Not sure if I understand the question clearly, but a `let` would be a typed variable, a `var` would be variant. So all `lets` would be able to be passed to all `vars` without any type errors.

Example:
```
# from line below, count will be a typed variable of type int
let count = 2

# from line below, somevar will be an untyped variable, or you could say the type is variant
var somevar = "string"

# line below is valid since something is variant, it can accept any type
somevar = count

# line below is not valid (I think?) because count can only accept ints and somevar is not of type int
count = somevar
```

**Comment by neikeq** [comment]
@chanon Correct. Last line (assign var to let variable) would require an explicit cast:
`count = somevar as int`.

**Comment by AndreaCatania** [comment]
@chanon what I mean is that introducing "let" could introduce more understanding difficulties, because the user need to choose between var or let so he need to know the difference between "var" and "let" to write a script... 

Without "let" he don't need to know and understsand safe code, while the coder that know how safe code works don't need neither a variable type nor a color that explictly say "hey I'm safe code".

(N.B. I'm not against an highlight that differentiate the safe code)

**Comment by neikeq** [comment]
I missed the `:=` proposal above. It actually looks good to me. It may not be obvious that it's a typed variable being inferred and not a variant, but it's the best option if `let` is discarded.

**Comment by RandomShaper** [comment]
Following TypeScript once more, I find `as` better than `cast`. They call it type *coercion* instead of casting.

Aside from the fact it's less typing.

**Comment by chanon** [comment]
@AndreaCatania without `let`, do you mean have type inference work on `var`? I like that too (actually more than `let`). But in that case user if enabling typed code *must* understand safe code.

For type inference on `var` (vnen's option 3) it would be
```
# assuming type checking have been enabled for this file

# here count would be inferred to be type int
var count = 2

# here somevar would be inferred to be type string
var somevar = "string"

# both lines below would not be valid, the type checker will say assignment of incompatible type to the vars
count = somevar
somevar = count
```

Which as you can see, this is valid normal GDScript would become invalid in Typed GDScript if `vars` are automatically type inferred (no `let` or other separate keyword/syntax).

While some say this is unacceptable because it is not backwards compatible, I would say that
- If type checking is not enabled (there are no type hints or explicit enabling of type checker), then the above will not cause any errors. Meaning old GDScript .gd files will be totally unaffected.
- Only when you begin to use type hints in a file (or explicitly enable type checking some other way) would the above cause an error. Which if you are using type hints / type checking then that means you want to be type safe and so catching possible errors like this is preferrable.
- And if type errors are treated more like warnings rather than showstoppers, then you can come back and fix it later.

**Comment by letheed** [comment]
I don't like `let` much personally.

First it kinda creates two classes of variables instead of adding optional typing that can be sprinkled in your regular code.

Second, aside from Javascript, most languages use `let` to define immutable or constant bindings, not variables. Swift has `var` for variables, Rust has `let mut` and F# `let mutable`.

I think there are interests expanding optional typing (inference, forcing type checking everywhere) and adding some syntax sugar for casting, but maybe those should be discussed in separate issues each?

I don't think we should block this from landing, without type inference and with casting required for now.

**Comment by neikeq** [comment]
@chanon No, I mean with var and `:=`:

``` GDScript
var count := 10
# inferred as int, therefore same as
var count : int = 10
```

**Comment by chanon** [comment]
@neikeq not what I said that you are responding to, but yup, `:=` is another option.

**Comment by letheed** [comment]
`var a := 5` makes me think a bit of `var a: _ = 5` which is pretty much what it would mean here.

**Comment by chanon** [comment]
I would like to be able to write it as
`var a: = 5` as it kind of shows clearly that the type is left blank compared to 
`var a: int = 5`

**Comment by vnen** [comment]
I have to say that I don't like the idea of fully-static in some files and fully-dynamic in others. I think this increases the complexity of GDScript beyond needed. Also makes it hard for making a gradual transition between dynamic and typed.

Though not everything will be done in this PR, my idea is:

* Implement the safe code highlight. This allows you to freely mix dynamic and typed code. This also means that the possible static checks will happen in *all* files, no matter if you are using types or not.
* Create a construct for type-inferred variables, so you don't need to repeat the type too many times (such as `var : Sprite  = $Sprite as Sprite`).
* Add a panel in the editor to show warnings. Then you can easily see the unsafe code lines and fix them if you want.

**Comment by vnen** [comment]
Addressing some points:

> I think instance as Type should be changed to instance.cast(Type) (or instance.as(Type), but I prefer "cast"). This way you avoid the annoying parenthesis

The problem is that this breaks if the user has a function with the same name. I also dislike using the function syntax, it's quite confusing (both for the parser and the user). I already have my problems with `.new()`. 

> I don't think the cast using a function call syntax is a problem either, it's the same in the C++ API.

The C++ API actually defines such function, it's not like there's a C++ construct to do so that looks like a function. Unless you mean we should do `dynamic_cast<Sprire>($Sprite)` as well.

Also, I don't see much of a difference between `$Sprite.cast(Sprite).texture` and `($Sprite as Sprite).texture`. Both are equally cumbersome IMO. Not to mention that it might return `null` if the node is not a Sprite, so if you are already sure it's a Sprite, you don't really need the cast.

----

> This could be a good idea, but we have to introduce another keyword... way easier if you use Type variable_name at this point

The problem is not being able to omit the type hint, so this won't solve it. Still, I agree that using a new keyword can be confusing, it's probably better to use `var : = 0` (i.e. add the colon but omit the type hint).

----

> I still wish for the scene_file idea to be implemented though.

I understand why you like it but in practice it's not easy to pull this off. First, the same script could be applied to more than one scene that vary only slightly. I would have to instance the scene while parsing, which can be slow depending on the scene. Then would have to call `get_node` whenever it happens on script, which is also not a fast operation. Even then it won't be 100% safe, because you can add/move/delete nodes at runtime, so the runtime checks will still need to be applied to guarantee the type safety.

Also, if you load a scene that contains the current script (which is the base case for this), it'll try to load the script that is already being loaded again, raising an error. It probably would need some exception for this particular case.

**Comment by vnen** [comment]
I know many people want something fully static that can detect every possible error beforehand. I would want something like that as well. However, GDScript files are compiled each one by themselves, they do not have much awareness of their surroundings, so it's quite a work to make structural checks in a per-file basis.

What I would do is to create another tool that scrapes the whole project and observe the interaction between scenes and between scripts, detecting *potential* problems where it can. This would include using nodes with wrong types and whatnot. Effectively a static analyzer tool. It is a different process than compilation and you wouldn't do it all the time, so it can be a bit slow.

**Comment by petkovsc** [comment]
> It is a different process than compilation and you wouldn't do it all the time, so it can be a bit slow.

Perhaps we press F5 to run and CTRL+F5 to "Build" which does full cross file type checking. Also "slow" may be subjective. VS/gcc builds complex C++ quickly, PHP checks complex libraries quickly. I'm sure it can be optimized over time.

**Comment by neikeq** [comment]
> The problem is that this breaks if the user has a function with the same name. I also dislike using the function syntax, it's quite confusing (both for the parser and the user). I already have my problems with `.new()`.

If the name to be used is `as` then the new `as` operator also breaks compatibility, since reserved keywords cannot be used as function names.

------

> The C++ API actually defines such function, it's not like there's a C++ construct to do so that looks like a function. Unless you mean we should do `dynamic_cast<Sprire>($Sprite)` as well.

I was referring to `Object::cast_to<T>(instance)`, previously `instance->cast_to<T>()`.

------

> Also, I don't see much of a difference between `$Sprite.cast(Sprite).texture` and `($Sprite as Sprite).texture`. Both are equally cumbersome IMO.

Quoting myself:
> Can be annoying to write. You usually don't think about casting at first, so you end up going back to add the first parenthesis
    
In other words, you are not forced to go back when you suddenly realize, as you type, that you need to use a cast.

------

> Not to mention that it might return `null` if the node is not a Sprite, so if you are already sure it's a Sprite, you don't really need the cast.

Except for type safety...

**Comment by chanon** [comment]
> In other words, you are not forced to go back when you suddenly realize, as you type, that you need to use a cast.

One idea, if possible, maybe if you type
`something as SomeType)`
when you type in the closing parenthesis ( the `)` ), the editor will automatically put in the opening `(` for you.

**Comment by chanon** [comment]
> The C++ API actually defines such function, it's not like there's a C++ construct to do so that looks like a function. Unless you mean we should do dynamic_cast<Sprire>($Sprite) as well.

> I was referring to Object::cast_to<T>(instance), previously instance->cast_to<T>().

Here vnen was pointing out that the Object::cast_to<T>(instance) is an API that was added, so it isn't really a standard C++ syntax / standard C++ doesn't cast that way. But C++ does have dynamic_cast<Type>(variable) which does look like a function though.

**Comment by vnen** [comment]
> If the name to be used is `as` then the new as operator also breaks compatibility, since reserved keywords cannot be used as function names.

They can actually. `sync` is a keyword and `func sync()` is valid.

But I don't find that bat to put parenthesis around it. I have to shuffle parenthesis all the time when I'm doing complex expressions/conditions. If you get used to always cast the nodes, it'll become a habit to do, if not then you'll probably forget and add it afterwards, so you'll have to move the cursor anyway.

I'm not convinced that any would be inherently better than the other.

----

> Here I think vnen was pointing out that the Object::cast_to<T>(instance) function is an API that was added, so it isn't really a standard C++ construct for casting and standard C++ doesn't cast that way. But C++ does have dynamic_cast<Type>(variable) which does look like a function though.

Yes, that was what I was talking about.

----

> Perhaps we press F5 to run and CTRL+F5 to "Build" which does full cross file type checking. Also "slow" may be subjective. VS/gcc builds complex C++ quickly, PHP checks complex libraries quickly. I'm sure it can be optimized over time.

Maybe, but this discussion is in another castle. We can open an issue to talk about this.

**Comment by Zireael07** [comment]
> this discussion is in another castle

:laughing:

**Comment by vnen** [comment]
Implemented the highlights but put them in the line number (as suggested by @samdze):

screenshot from 2018-06-06 10-50-01

When it's known for sure, type errors are detected even when not using type hints:

screenshot from 2018-06-06 10-54-08
screenshot from 2018-06-06 11-09-12
screenshot from 2018-06-06 11-07-49
screenshot from 2018-06-06 11-20-14
screenshot from 2018-06-06 11-15-23

**Comment by swarnimarun** [comment]
@vnen I think a little more obvious highlight would be better.
The one you currently implemented can easily be missed, especially if one for some reason is working for odd reason in lighting conditions one should not on ones old laptop that was gifted to him/her by his/her parents.

But I am not complaining just suggesting something a little more obvious will be better, 
As a suggestion you can make the color for the line number if that's all that you want to edit a little more bright or just change/shift the hue or you can just give some settings to change it, in text-editor themes.
If there is already some settings for it then just ignore.....

**Comment by vnen** [comment]
@swarnimarun Is it really that bad to differentiate?
screenshot from 2018-06-06 12-06-44

I think that doing a full line highlight is too obnoxious when you're working for a great amount of time. The idea is to make a clear difference but not to get in the way. Because for the people that don't really care about the safety (like when you're just prototyping) having the highlights might be an inconvenience.

I can still increase the contrast a bit if it's not enough.

**Comment by swarnimarun** [comment]
@LeonardMeagher2 Won't export automatically define if it's a float or int. 
i.e. No need for that extra `: float`

@vnen I think it's fine but some settings to change it when needed or when getting used to will be nice. More contrast might annoy some people.

**Comment by LeonardMeagher2** [comment]
@swarnimarun That's my question, I would hope to not have to add the `: float` to get type checking on that variable.

**Comment by vnen** [comment]
> Does this modify or take advantage of the export hint?

> Won't export automatically define if it's a float or int.

No, because the export hint doesn't guarantee that you won't set the variable with another type later on (i.e. it's still a variant). What happens is that if the export hint and explicit type doesn't match it will give an error. You can also omit the export hint if don't need the range:

```gdscript
export var scale : float # Works fine
```

----

@swarnimarun 
> I think it's fine but some settings to change it when needed or when getting used to will be nice. More contrast might annoy some people.

The color can be set by the theme and also customized in Editor Settings, like every other color.

**Comment by vnen** [comment]
I did some test. Is this better or worse:

screenshot from 2018-06-06 15-18-47

Compared to just the line numbers:

screenshot from 2018-06-06 15-23-07

Honestly I find the full line highlight distracting. Also hard to tell if the current line is type-safe or not.

**Comment by OvermindDL1** [comment]
> I did some test. Is this better or worse:

Hmm, I like both options, although I'd prefer if lines without useful code (including newlines) were marked as typesafe (since they technically are) that way I can better focus on the lines that are 'not'.

Overall I'd pick the fullline/first image, especially if the noise of empty lines and so forth were marked as fully typed, thus questionable lines are more noticeable instead of lost in the noise.

**Comment by chanon** [comment]
I like both options, meaning I'd prefer having both at the same time.
With the line number highlight it will allow to see if the current line is safe.

Also agree that empty lines should be highlighted.

**Comment by mrcdk** [comment]
Definitely line numbers. Having full line hightlight is too distracting and hightlighting empty lines would make non-typed scripts look really weird and add to the distraction.

**Comment by vnen** [comment]
This actually doesn't look so bad:

screenshot from 2018-06-06 16-29-56

Here with line numbers as well:

screenshot from 2018-06-06 16-34-14

Still might be a nuisance for people who don't care about the typing.

**Comment by OvermindDL1** [comment]
> Still might be a nuisance for people who don't care about the typing.

If it encourages them to properly type things, then the better, it in general makes the code more reliable (and perhaps faster once JIT).

**Comment by letheed** [comment]
What about putting the highlight in the margin/line numbers instead of the code?

**Comment by chanon** [comment]
I guess there needs to be an editor setting (or settings) for it since the empty lines will annoy at least one group. 

Don't highlight empty lines -> people who do mostly typed will be annoyed.
Highlight empty lines -> people who do mostly non-typed will be annoyed.

There should be settings for colors for 
- empty lines
- typed lines
- untyped lines

Or the option to choose between highlighting just the typed lines (for people who do mostly non-typed) or highlighting non-typed lines (for people who do mostly typed)

**Comment by AndreaCatania** [comment]
I really dislike highlight the line of code depending on the type of variable... Please add the possibility to disable it. I prefer to have the same background for the entire page...

**Comment by vnen** [comment]
@chanon 
> I guess there needs to be an editor setting (or settings) for it since the empty lines will annoy at least one group.

Not counting the color selector, there should be only one setting: enable/disable the highlight entirely.

If you use the highlight to see the possible problems, maybe the ideal is to highlight the *unsafe* lines instead. It would be like my previous screenshot but with colors reversed.

**Comment by vnen** [comment]
@letheed 
> What about putting the highlight in the margin/line numbers instead of the code?

That might be viable as well, I'll see if it's easy to test. But I think I'll settle in marking the unsafe parts, however the marking would be like.

**Comment by vnen** [comment]
@AndreaCatania 
> I really dislike highlight the line of code depending on the type of variable... Please add the possibility to disable it. I prefer to have the same background for the entire page...

It's not depending on the type of the variable, it's whether the member/function you're accessing is guaranteed to exist based on the type information available. In any case, there'll be an option to disable it.

**Comment by AndreaCatania** [comment]
@vnen oh, ok thanks you

**Comment by petkovsc** [comment]
Great work so far @vnen !

Definitely just line numbers. I even hate those indent icons and have them turned off. I prefer a clean background when coding. If the whole line was highlighted, I might have to switch to editing gdscript in VS! :(

The red highlight for invalid functions and code that just won't run is good. Although the intellisense red squigly that someone mentioned is ideal: non intrusive and wide spread already (e.g. spell check).

**Comment by vnen** [comment]
I appreciate the feedback but there's been a lot of noise in this discussion already. It became more of bike-shedding at this point.

What I'm gonna do is add highlight to the number lines in type-safe lines (much like my first example but I'll fix it to mark the empty space/comments between safe lines as well). There'll be an option to disable it as well as changing the color.

If usage proves this is bad or there's a better solution, we can solve it in another PR.

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -2413,7 +2579,20 @@ void GDScriptParser::_parse_block(BlockNode *p_block, bool p_static) {
...
-
+			case GDScriptTokenizer::TK_EOF:
+			case GDScriptTokenizer::TK_ERROR:
+			case GDScriptTokenizer::TK_NEWLINE:
+			case GDScriptTokenizer::TK_CF_PASS: {
+				// will check later
+			} break;
+			default: {
+				if (p_block->has_return) {
+					_set_error("Unreacheable code.");
```
Comment (Faless) [inline modules/gdscript/gdscript_parser.cpp]: Is this really necessary? Unreachable code might not be an error, I use it a lot when debugging, it can be very annoying that I cannot run the script for that reason. It also has the potential of breaking many projects (though I admit, having a check is nice)

Comment (vnen) [reply modules/gdscript/gdscript_parser.cpp]: Yeah, I was going to remove this (and eventually make a warning) but I forgot. It shouldn't really stop the code from running.

**Comment by vnen** [comment]
Update the code. Now it has a setting to disable the highlighting. For the time being it will be only a subtle greenish highlight in the line number. After people start using it we can better assess what changes are needed.

Here's code from the platformer demo to see how it behaves with current code:

screenshot from 2018-06-07 01-14-37

**Comment by OvermindDL1** [comment]
> Here's code from the platformer demo to see how it behaves with current code:

That little green highlight is entirely ignorable and I missed it entirely until i read the text before the picture, it really should be more visible (or make it less visible but non-typechecked lines should be obvious).

**Comment by swarnimarun** [comment]
@vnen How do we use the class in the same script with auto-complete.
I simply can't get it to auto-complete.

image

And the highlight is quite light. But I got the hang of it in about a few minutes of coding.

**Comment by karroffel** [comment]
As said before, I wish there was a way to "force" static type everywhere. I would be fine if it was a project setting that's disabled by default, but having a way to make sure that there is no unchecked code would be really useful!

**Comment by neikeq** [comment]
> As said before, I wish there was a way to "force" static type everywhere. I would be fine if it was a project setting that's disabled by default, but having a way to make sure that there is no unchecked code would be really useful!

A "Enforce static typing"-like project setting sounds good to me. You can see similar flags in other languages, like allowing `unsafe` code in C#.

**Comment by chanon** [comment]
I'm not sure if it is something on my side, but with this pull request whenever I do
```
var myFile = File.new()
```
I get an error saying `Cannot call 'new()' on an instance.`

**Comment by vnen** [comment]
@chanon oh, I think I broke this. Will fix it soon.

**Comment by vnen** [comment]
@karroffel 
> As said before, I wish there was a way to "force" static type everywhere. I would be fine if it was a project setting that's disabled by default, but having a way to make sure that there is no unchecked code would be really useful!

I feel that adding warnings will solve this. Then we can also add options to consider warnings as errors.

@swarnimarun 
> How do we use the class in the same script with auto-complete.
I simply can't get it to auto-complete.

That's one of the reasons I will refactor the completion code. The current implementation completely ignores the inner classes.

@OvermindDL1 
> That little green highlight is entirely ignorable and I missed it entirely until i read the text before the picture, it really should be more visible (or make it less visible but non-typechecked lines should be obvious).

That's part of the point. It shouldn't be a burden for people who don't use typing. If a beginner looks at it they will think it's no big deal (which is the idea). Also, if you're looking only at the thumbnail in the post (and not at the full-size image) it is much less noticeable.

**Comment by chanon** [comment]
The pull request also crashes my project. I've prepared a minimal example project of a crash here:
[typeCrash.zip](https://github.com/godotengine/godot/files/2081187/typeCrash.zip)

It seems to be related to parse errors in autoloading singletons (I think).
The project above is empty except for 2 autoload singletons that I set.

I agree the line number / line highlighting is something that can adjust later as people get to use it more.

**Comment by OvermindDL1** [comment]
> That's part of the point. It shouldn't be a burden for people who don't use typing. If a beginner looks at it they will think it's no big deal (which is the idea). Also, if you're looking only at the thumbnail in the post (and not at the full-size image) it is much less noticeable.

I saw the full image, I think the thing is that the line numbers just kind of become invisible in my vision due to their ubiquity...  >.>

Shouldn't the default mode be something that strongly encourages strong typing though, for quite a variety of reasons?

**Comment by chanon** [comment]
I have the same preference @OvermindDL1, but I think this can be adjusted later / options added later as different people will have different opinions on this. 

At this point I think we should help test out the current pull request so it can get merged and then we will have a more solid foundation to build in more features.

**Comment by vnen** [comment]
@OvermindDL1 
> Shouldn't the default mode be something that strongly encourages strong typing though, for quite a variety of reasons?

No, it should not encourage strong typing (nor discourage either). It defeats the point of the language being easy to use.

But yeah, the details of the highlighting can be discussed in another issue/PR.

**Comment by swarnimarun** [comment]
@vnen Now things left are likely refactoring and including InnerClasses and Merging.
Is there more incomplete, I am testing the PR so if there is I would like to know.
Hope it's merged soon.

**Comment by vnen** [comment]
@swarnimarun to clarify, inner classes are missing **from the code completion**. The code completion is the one that needs a refactor and I'll do it in another PR. So anything related to completion itself is out of scope for this one.

**Comment by vnen** [comment]
I believe this is ready to be merged.

**Comment by chanon** [comment]
This still crashes my project.
Here is example minimal reproduction:
[typeCrash2.zip](https://github.com/godotengine/godot/files/2082958/typeCrash2.zip)

Result when opening project:
image

**Comment by vnen** [comment]
@chanon thanks for the report. Should be fixed now.

**Comment by chanon** [comment]
@vnen that's great!

If no one else finds any other issues then merge!

I'm on vacation for a week now, so won't be able to do any testing until after.

**Comment by Mr-Slurpy** [comment]
About whether the blank line numbers should be highlighted or not, could they inherit the highlight of the lines above/below? That way blank lines between safe code match with their surroundings and vice versa. Blank lines between safe/unsafe code can be either.

**Comment by vnen** [comment]
> About whether the blank line numbers should be highlighted or not, could they inherit the highlight of the lines above/below? 

That's what happens now. If a line is marked safe it will mark all the following empty lines and comments as safe.

**Comment by megasoft78** [comment]
Hi,
I'm very interested on having gdscript typed.
I built Godot from this repository:
https://github.com/vnen/godot/tree/typed-gdscript-final

When I declare a variable as Sprite it's not detecting if the function exists.

image

Is it expected?

**Comment by vnen** [comment]
@megasoft78 you might have missed the long discussion before, but this case won't error out. Instead, the checked lines are marked with subtle green tint on the line number. I can see in the screenshot that the given line is (correctly) not marked as safe.

The rationale is that GDScript is still duck-typed and should remain compatible. While the variable is a Sprite, it can also be set with a subtype that might have the function defined, so it can't simply tell it's an error. It just add a soft warning by not marking the line as safe. Eventually we will add proper warnings to manage this better.

**Comment by vnen** [comment]
@megasoft78 
> Would it be possible to setup a strict mode? Maybe a setting in Godot editor or a keyword at the begin of the script like in Visual Basic?

Once warnings are in place, we could add an option to treat warning as errors.

**Comment by OvermindDL1** [comment]
> Once warnings are in place, we could add an option to treat warning as errors.

Oh I hope so, maybe even a project-wide setting.  Even if I'm forced to add the occasional type declarations around I do *not* want anything untyped.

**Comment by megasoft78** [comment]
@vnen thank you. Would it be in 3.1 Alpha?
It seem the plan is for July 1st, am I right?

**Comment by vnen** [comment]
> Would it be in 3.1 Alpha?

I don't think I'll made it in time for 3.1. But it can be added in the 3.1.x release cycle.

**Comment by megasoft78** [comment]
Don't worry. I'll wait. Thank you. ;)

**Comment by chanon** [comment]
Another one
`MyBaseCanvasLayer.gd`
```
extends CanvasLayer

onready var something = "whatever"

func dummy():
	pass
```

`MyCanvasLayer.gd`
```
extends "res://MyBaseCanvasLayer.gd"

func _ready():
	print("Hello World")
```

Result:
image

Example project:
[ReadyInheritProblem.zip](https://github.com/godotengine/godot/files/2108958/ReadyInheritProblem.zip)

Funny thing is, it doesn't happen all the time (if you run it again, sometimes it doesn't error).

**Comment by chanon** [comment]
Next one:
image
It is not possible to assign anything to the Control.material property (I don't know how).

Example project:
[ControlCantAssignMaterial.zip](https://github.com/godotengine/godot/files/2108974/ControlCantAssignMaterial.zip)

**Comment by chanon** [comment]
Next one, I think this is too picky, will break old code:
image

Example Project:
[ControlCantSetIntSize.zip](https://github.com/godotengine/godot/files/2109005/ControlCantSetIntSize.zip)

**Comment by chanon** [comment]
Next one, so is having arguments in _init going to be no longer supported?

```
extends Node2D

class MyPosition:
	var x
	var y
	
	func _init(p_x, p_y):
		x = p_x
		y = p_y
	
	func show():
		print( "position: %f, %f" % [x, y] )

func _ready():
	var myPos = MyPosition.new(100, 50)
	myPos.show()
```

In non Typed GDScript build outputs 
```
position: 100.000000, 50.000000
```

In Typed GDScript build:
image

I can't remember where I found out about this ability, but the documentation still kind of talks about _init being able to have arguments, and I am using it in some of my custom classes.
http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#class-constructor

**Comment by megasoft78** [comment]
I'm not sure but your last one can't be done. You need to define the type in the declaration. :)

**Comment by chanon** [comment]
@megasoft78 not sure what you mean, but all these example projects run fine in Godot master (without the Typed GDScript). If they are supposed to no longer work, then that is a breaking change.

**Comment by megasoft78** [comment]
@chanon I'm sorry. I was thinking you expect that Godot detect the type of x and y from your code. You are right. That should work.

**Comment by chanon** [comment]
I don't think I can go any further at this point as there is too much code to write workarounds for.

**Comment by chanon** [comment]
BTW, after testing the Typed Build it seems that the typed parsing is being done at runtime. I understand/I guess that is how GDScript works and is the fastest way to get this actually working in Godot, but this and the fact that errors it finds are considered parse errors causes some issues. I know you intend to address some of these issues, but just to summarize again after actually using it:
- Instead of finding all the parse errors before running the game, it finds errors when the game is running when each of the scripts are loaded at runtime. So in the end, you still have to run the game and go to different parts of the game before you see/catch all the errors. The 'static analyzer' tool suggested *could* be the solution.
- Any of the new errors found causes the game to stop running. The first problem from this is it will break existing projects if they had some previously unknown errors in them (but still ran fine). This may be OK/acceptable, except when the Type system itself has bugs. The second problem is that instead of being able to see all the Type errors and fix them at once like with a normal compiler, you have to fix the errors one by one and run the game again each time, which is inconvenient / takes more time.
- I am not sure if there is a performance impact of the additional type parsing/checking at runtime which could impact scene loading speed. If so, this is something that would impact all GDScript projects even if they don't use any Type hints.

What I'd originally imagined when I heard about Typed GDScript is basically what TypeScript does. That is Typed GDScript would be compiled into normal GDScript at 'compile' time and all parsed errors are found and listed. The 'compiler' would just strip out all type syntax. Then the game would be run using the normal GDScript.

Later when the VM can support using type info for performance optimization, the compiler could compile into bytecode with type info embedded instead.

I guess integrating it into the normal parser also has advantages and is probably better for tighter integration, but due to how the normal GDScript parser works at runtime and how it handles parse errors (stop everything) it causes the issues above.

**Comment by vnen** [comment]
@chanon Thanks a lot for testing this. Almost all of the things you found there are actually bugs. Apparently there are some issues when looking up the inheritance tree (which causes the errors for non-declared identifiers and mismatching signatures).

The only one that is not a "bug" is the integer assignment to float variables. I was already considering changing to allow this specific case, since it gets in the way when you're initializing variables.

> Instead of finding all the parse errors before running the game, it finds errors when the game is running when each of the scripts are loaded at runtime. So in the end, you still have to run the game and go to different parts of the game before you see/catch all the errors. 

Well, this was already the case. Many problems were found in the compiler (like non-declared identifiers) which would only happen if you run the game. Now it shows up in the editor since they are caught by the parser. Of course, there are some tweaks I need to make in this PR to not incorrectly identify those errors nor raise problems with things that were valid before.

> Any of the new errors found causes the game to stop running. The first problem from this is it will break existing projects if they had some previously unknown errors in them (but still ran fine). This may be OK/acceptable, except when the Type system itself has bugs.

The typed system can be tweaked, bugs should be fixed. This is not the final version, it *shouldn't* raise errors in things that were valid before. But it may catch errors that are only seem at runtime and the old code just ran fine because it never reached such code.

I want this to be merged to have more people testing and I can start fixing the problems I didn't reach with my projects. I don't really have a big project to test issues.

> The second problem is that instead of being able to see all the Type errors in a script file and fix them at once like with a normal compiler, you have to fix the errors one by one and run the game again each time to get the next error, which is inconvenient / takes more time.

Again, this is a problem with the current dynamic GDScript as well. Once it finds an error it just stops. And again this PR makes it better because more errors are caught in the editor, so you don't have to run the script to find them. This is only a problem for people fixing issues in current projects, won't be a problem in new scripts.

>  It is a new frustrating experience of writing a statically typed language but only being able to get the errors one by one at runtime like a dynamic language.

I think it's already clear that they are not "caught at runtime". They are caught when loaded. It's a nuisance when you're updating an old project, but it's not when you are *writing* the code because the error will appear right on the editor after you wrote the line. This will help you catch bugs as well that before only was caught really when running such code (and that's my main intention with this).

> I am not sure if there is a performance impact of the additional type parsing/checking at runtime which could impact scene loading speed. If so, this is something that would impact all GDScript projects even if they don't use any Type hints.

It likely does impact the loading time for scripts. I don't think the increase is significant though. If you aren't sure, it's because it's not affecting that much. If it becomes a problem we can see how to optimize it. I really don't like that GDScripts are parsed and compiled at runtime, but that's out of the scope for this change in particular. Some people are discussing about adding AOT compilation (see #5049).

> What I'd originally imagined when I heard about Typed GDScript is basically what TypeScript does. That is Typed GDScript would be compiled into normal GDScript at 'compile' time and all parsed errors are found and listed. The 'compiler' would just strip out all type syntax. Then the game would be run using the normal GDScript. 

The problem is that GDScript files are compiled on demand and they are not dependent on each other. TypeScript adds a new compilation step to the process that runs through all the files. It *sounds* easy to do, but it's not, TypeScript is very efficient at detecting what changed and compile only what's needed. I seriously don't want to worry about that.

> This would not cause any performance impact as all static type checking / type parsing is done at compile time.

It's not like this PR affects runtime performance (it might if you are doing typed assign and casting, but not if you aren't using types).

> Later when the VM can support using type info for performance optimization, the compiler could compile into bytecode with type info embedded instead.

Which means maintaining two parsers and two compilers. It defeats the purpose of GDScript of being easy to maintain.

> Actually, I know this is a late suggestion/idea, but again, taking from TypeScript, maybe Typed GDScript should even have a different extension eg. `.tgd`. That wouldn't let old projects get any advantage like the current implementation does, but it would guarantee compatibility. (Like TypeScript though, you could either rename old `.gd` files to `.tgd`, or enable type checking in `.gd` files with a project setting. Type hints would still only be correct syntax in `.tgd` files.) Implementation of this could even use the current resource system where `.tgd` files are 'compiled' into `.gd` files in the `.import` folder. This would complicate a few things, but would also make a few things cleaner.

This also means maintaining two parsers, and also a transpiler. The other problems with this is that it has to support a new file format, add hooks to the editor to transpile everything before running and also on export, make the transpiler smart enough to not redo unchanged files but at the same time detect if the dependencies were changed (extends and preload), and probably a few more things that I might have forgotten.

> I guess integrating the Typed parser it into the normal parser also has advantages and is probably better for tighter integration, but due to how the normal GDScript parser works at runtime and how it handles parse errors (stop everything) it causes the issues above.

Parse errors are not recoverable, it makes sense to stop everything. The difference with GDScript is that it is parsed on load, so if you missed the errors in editor, it won't stop you from running until you try to load it.

This PR only adds a few more things to what can be an error. Of course I might have overshoot somethings and still might left some bugs, but in the end the errors would be caught in compilation or run time.

**Comment by vnen** [comment]
I'll work on the reported bugs, naturally (and I appreciate the reports). But I want this merged to have a broader testing and be able to fix more bugs.

It after some alphas there are still uncertainty if this can break projects, I can change the type errors to be non-blocking and show just as a warning in-editor so people can report issues with false-positives.

**Comment by chanon** [comment]
@vnen Thank you very much for the extended response. I completely understand your points, and yes I agree that this should get merged for broader testing.

Most of my wishes could probably be answered by the static analyzer or maybe the AOT compiler.

**Comment by mhilbrunner** [comment]
Thanks for the in-depth testing @chanon :)

Agree about getting this merged soon to get more eyeballs on it.

>I can change the type errors to be non-blocking and show just as a warning in-editor so people can report issues with false-positives.

Could *maybe* be an option: treat type errors as warnings/errors.

**Comment by vnen** [comment]
BTW, the mismatch with the `_ready()` signature is something I bumped into as well, and I think it's related to #19548. I'll investigate this today.

**Comment by vnen** [comment]
Rebased to fix the reported issues.

@chanon if you want you can send your project to me (privately) so I can look into more issues. Anyway, thanks for the reports. They all should be fixed now.

**Comment by chanon** [comment]
The latest version opens and runs my project fine!
I will begin to clean up some of my own errors and then start putting in type hints.

**Comment by vnen** [comment]
I figured it would be easy to add the type inference syntax too, so I threw that in. If you add the colon but omit the type, it will be inferred from the assigned value:

```gdscript
var x : = 42 # Inferred to be an integer
```

This can make a few things less redundant like:

```gdscript
var key := event as InputEventKey
var my_sprite := $MySprite as Sprite
```

**Comment by chanon** [comment]
After beginning to input type hints, one thing I found is that some types can't have null assigned to them.

Main ones which I'd expect to be allowed are String, Dictionary and Array
```
# all of these give error: Assigned value type (null) doesn't match the variable's type
var myArray: Array = null # 
var myDic: Dictionary = null
var myString: String = null
```
For these I think null should be allowed as many times I use null value for them in function parameters as default value.

**Comment by vnen** [comment]
@chanon 
> After beginning to input type hints, one thing I found is that some types can't have null assigned to them.

`null` is not compatible with the built-in Variant types (apart from `Object`). You can see that if try to assign `null` to a member variable that is a `String` or a `Vector2`, you'll get a runtime error.

If you want it to be empty it's simpler to not assign anything. GDScript always assign a base value by default.

**Comment by vnen** [comment]
> [...] it would be nice to be able to specify the type of the temporary variable inside for loops.

It's something that crossed my mind, but I'll have to take a closer look. It would generate errors if one of the values weren't compatible with the hint.

**Comment by vnen** [comment]
About sum/union types, while I like them too I'm not planning to add them anytime soon. I prefer to work on tooling first which I believe is severely lacking features (warnings, static analysis, refactor tools, etc.).

Also, GDScript is still supposed to be simple and easy to maintain (otherwise it's better to just bind some third-party scripting language and be done with it). Should probably give some time to solve #18698 and decide more clearly what will and won't be added to the language.

**Comment by chanon** [comment]
With this code, there are no errors in the editor, however when it runs, there is an error:
```
extends Node2D

class TestClass:
	var timeLeft: float = 5.0
	
	# if change to this line, it works
	# var timeLeft: int = 5
	
func _ready():
	callIt(10)
	
func callIt(value: float):
	var test: = TestClass.new()
	test.timeLeft = value
	print(test.timeLeft)
```
Result:
image

It is a bug, but it also seems like it is doing a type check at runtime? I thought type checks were only done 
at script load?

Project file:
[RuntimeAssignError.zip](https://github.com/godotengine/godot/files/2115911/RuntimeAssignError.zip)

**Comment by vnen** [comment]
Oh, I forgot about this. The problem is how function calls are being applied.

> It is a bug, but it also seems like it is doing a type check at runtime? I thought type checks were only done
at script load?

There are runtime type checks on assignment, to guarantee the types are correct when it can't be detected by the parser. This will be optimized later.

**Comment by chanon** [comment]
I wonder if those are really needed. I feel as though that could impact performance, ie. by adding type hints I'm making my game slower because it has to do type checks on every assignment. I'd rather that it is let to run like normal GDScript .. unless there is optimization in the VM that actually uses the type information for optimization.

**Comment by OvermindDL1** [comment]
Technically it could end up faster because the storage for the given assignment could be known and optimized both on creation and on access later without needing to perform dispatch on every-single-access.

Better question though, why was line 10 typechecking when an integer is being passed to a float?

**Comment by vnen** [comment]
It could be disabled in release. But I don't like to work with assumptions. I'll try to make some time to find/develop benchmarks for GDScript and test the actual performance impact, then decide if there's something to be fixed.

**Comment by vnen** [comment]
> Technically it could end up faster because the storage for the given assignment could be known and optimized both on creation and on access later without needing to perform dispatch on every-single-access.

That's kind of what I intend to do eventually. Though I'll work on benchmarks first.

> Better question though, why was line 10 typechecking when an integer is being passed to a float?

There are a few cases where implicit type coercion happens, this is one of them. Otherwise doing `Vector2(0, 0)` would be invalid, while the engine itself doesn't care. This is on the list for the warnings feature. An infamous case is NodePath to String: `get_node("Sprite")` is technically invalid type-wise, you'd have to do `get_node(@"Sprite")` to use a NodePath instead.

**Comment by chanon** [comment]
Just as an example, here s is another (I guess expected) case of a type error happening not at compile time, but at runtime:
image
This is probably the kind of error that the type check on assignment is meant to catch.

I still feel this is kind of of a strange mix of a (not-really) statically typed language having its types forced not at compile time, but at runtime. And instead of getting your type errors when you compile, you get them when you run the game up to where the error would happen.

It is another vector to creating runtime error bugs when coding. If you type a variable and in some case down the road it gets assigned a different type you didn't think of, then you get a runtime error. Whereas if you didn't type it, your code would likely have worked fine. So you have to be careful when typing and using variables, or you may introduce new runtime errors where there would have been none.

At least I think these types of errors should be treated as warnings instead of 'stop the game / can't continue running the method' errors.

**Comment by vnen** [comment]
But that kind of error occurs in runtime already anyway, for example if you are setting a property in an engine class. It's not anything new, the novelty is only applying that to scripts as well.

**Comment by chanon** [comment]
I guess if the game code is tested well enough, then it would be ok .. and in that way it will help catch bugs. 

I guess it just feels different for me coming from TypeScript where after compilation it doesn't care about types anymore.

**Comment by OvermindDL1** [comment]
> I guess it just feels different for me coming from TypeScript where after compilation it doesn't care about types anymore.

That's just because the underlying language it compiles to, Javascript, is untyped.  GDScript on the other hand both has a typed engine base and it itself is likely to end up compiling to typed assembly anyway.

**Comment by chanon** [comment]
>But that kind of error occurs in runtime already anyway, for example if you are setting a property in an engine class. It's not anything new, the novelty is only applying that to scripts as well.

Yes that kind of error already can occur. But now, there is possibility to have more of them due to type definitions in scripts too. So there is possibility for more to occur.

As a game developer using the engine, the engine class properties already have types. But variables in scripts will have types only if the game developer adds them to his scripts. So by adding types he may be able to prevent some runtime error bugs, but he may also be adding new runtime type error bugs.

When you use TypeScript you are only catching bugs at compile time that would have occurred at runtime. You can't add new runtime bugs when using TypeScript compared to using just JavaScript.
However when you use Typed GDScript, you may be adding new runtime bugs compared to just normal GDScript. 

At this point, the language doesn't let you type everything - Dictionaries and Arrays are used all the time and can't be typed - so there is possibility of runtime type errors everytime you use them with typed variables. And then, while adding that risk, the type info isn't used for optimizing anything. Yes, the runtime type checking can help catch bugs, but it (and adding types) can also be the source of bugs if you are not careful. 

So I kind of am not sure if it is worth it as I was mostly fine with GDScript but wanted extra safety from Typed GDScript. Now this makes me feel that I am introducing more unsafety with Typed GDScript.
I want to add types for compile time type safety. Not to increase runtime type unsafety.

Again, I am expressing some opinions from using it, but I'd like if more people use it and see what they think from actually using it.

**Comment by mhilbrunner** [comment]
If we look to Python, you should be able to declare the dictionary like:
`var dic := Dictionary()[string, float]` at which point line 6 would fail at compile time.

**Comment by chanon** [comment]
> If we look to Python, you should be able to declare the dictionary like:
> `var dic := Dictionary()[string, float]` at which point line 6 would fail at compile time.

Yes, stuff like that is what is needed in order to increase the type safetyness and make things fail at compile time instead of runtime.

If I could type everything, then I would, and then I wouldn't be afraid of runtime type errors.

But since right now it is not available, I think with all the 'forced untypedness' it is creating more risk to mix typed variables with the untyped stuff.

I know right now it is just the start and features to let you type Dictionaries/Arrays would come later, so right now I think it makes more sense not to make runtime type checking cause stop the game errors.

**Comment by chanon** [comment]
Some more examples:

This is a parse error, as it should be:
image

This parses fine, but becomes a runtime error:
image

**Comment by OvermindDL1** [comment]
> In TypeScript actually the same thing is allowed. You can assign untyped (any) vars to typed vars without any special syntax. However since there is no runtime type checking, there are no runtime type errors. It kind of 'trusts' (it has to) that you are doing what you want to do.

And then random runtime errors.  ^.^

But really, storing a string into an integer, what would you expect that to do?  Let's say it's a 32-bit integer, thus it has 4 bytes of storage, what would you expect to happen by storing a longer string into that 4 bytes of storage considering that variable is typed and such an optimization is quite likely 'soon'.

Honestly though, that should not compile.  That little missing easily-ignored green line number is a bad bad design, that line should be red, it's a failure.  Not just a dynamic type cast, it is an out-right type failure since both the left-side and right-side are known types.

**Comment by vnen** [comment]
GDScript is strictly typed (always was) while JavaScript is much more lenient with that. In JS you can do `"1" + 2` just fine, while in GDS you get a type error. Even without hints, there are many situations this could lead to an error.

Also, those errors do not stop the game in a release build. They'll fail and ignore the rest of the function, but keep processing. It breaks in-editor to let you know this is an error. In the C++ engine it could lead to crashes.

Eventually we will add optimizations, which will make those runtime errors unavoidable. So I'm adding the errors now to not be considered a compatibility breakage when they're in.

**Comment by mhilbrunner** [comment]
@vnen Are there plans for type-constrained versions of the core collection types (Dictionaries, Arrays) like in the example above? E.g. via `var dic := Dictionary()[string, float]` or some other syntax.

**Comment by vnen** [comment]
> Honestly though, that should not compile. That little missing easily-ignored green line number is a bad bad design, that line should be red, it's a failure. Not just a dynamic type cast, it is an out-right type failure since both the left-side and right-side are known types.

They are not known types, since it's not inferred from assignment. Seems obvious in this example, but if I start with this, there will be many other intricate examples to cater for, which I'm not willing to put effort at this particular time (especially in a feature that was not even merged yet...)

But really, people seem to be projecting their favorite language into GDScript (especially this PR). Which is one of the reasons I opened #18698. You need to realize also that this is a new feature and in the spirit of Godot it will be polished over time. I find pointless to add everything now and then in general use people don't use it or even don't like it. And GDScript is meant to be simple both from users and from developers perspectives (some language-buffs, as I am myself, love their algebraic data types, but for the general GDScript audience it's not important and may be hard to grasp).

I appreciate the feedback, but we need more of that to make the next decisions.

----

@mhilbrunner 
> Are there plans for type-constrained versions of the core collection types (Dictionaries, Arrays) like in the example above? E.g. via `var dic := Dictionary()[string, float]` or some other syntax.

Yes, as stated in the "Future" section of the first post. Not sure about the syntax yet though.

**Comment by chanon** [comment]
> Honestly though, that should not compile. That little missing easily-ignored green line number is a bad bad design, that line should be red, it's a failure. Not just a dynamic type cast, it is an out-right type failure since both the left-side and right-side are known types.

Right, I actually agree with this. The language enforces types at runtime, but it _doesn't_ enforce types at compile time. 

I am not only projecting my favorite language onto GDScript, but I can't think of any other language that has this behavior.

Languages that I know of are usually either somewhat fully dynamically typed (JavaScript) or fully statically typed (C++). And for TypeScript you have the 'option' to type things, and they aren't enforced at runtime.

**Comment by chanon** [comment]
C++
```
int main()
{
  std::string text = "some text";
  float myVar = 10.0f;
  myVar = text;
}

result:
error: cannot convert 'std::string {aka std::basic_string<char>}' to 'float' in assignment
```

JavaScript
```
var text = "some text"
var myVar = 10.0
myVar = text

result
no errors, runs fine
```

TypeScript
```
var text = "some text"
var myVar: number = 10.0
myVar = text

result
no errors, runs fine
```

TypeScript with noImplicitAny enabled
```
var text = "some text"
var myVar: number = 10.0
myVar = text

result
Type 'string' is not assignable to type 'number'
```

Typed GDScript
```
func _ready():
  var text = "some text"
  var myVar: float = 10.0
  myVar = text

result
No compile errors but fails at runtime
```

**Comment by vnen** [comment]
> Typed GDScript right now enforces types at runtime, but it doesn't enforce types at compile time.

It's not *Typed GDScript* that does it, as I said a few times, GDScript _always_ did it.

The thing is that you'll get an error eventually when you are actually *using* the variable and not only assigning it. For instance, try running this (even without this PR):

```gdscript
func _ready():
	var text = "text"
	var number = 30.2
	print(text + number)
```

It will fail at runtime.

With this PR you can specify the types so this:

```gdscript
func _ready():
	var text := "text"
	var number := 30.2
	print(text + number)
```

Will now give an error at **parse** time so you can catch the error while still editing the file.

If are _actually_ using that float for a calculation or assigning it to a property on an engine-defined class (or as an argument to an engine-defined function), you _will_ get a runtime error _anyway_. And when that happens, people will complain that it let a float variable contain a string...

This is not introducing *more* errors, it's only catching them sooner. 

If you are not confident that you are always passing a float, then simply don't type-hint it and let it be a variant.

>  I can't think of any other language that has this behavior.

There's at least one: Ruby. It's an interpreted language, with duck-typing, strong-typing, and dynamic-typing, just like GDScript.

You can't really compare to TypeScript, because it transpiles to JavaScript, which is a language that will never complain about typing. GDScript *does* care about it, many type errors can happen in operations. You can't compare with the other languages either because GDScript does not have implicit type inference.

**Comment by chanon** [comment]
Ruby, same simple example
```
text = "sometext"
myVar = 20.5
myVar = text

result
no errors, runs fine
```

I completely understand what you said in the previous post. I just disagree that the current language design is a good one.

Coming from C++/Java/JavaScript/TypeScript background, the way the type system is lax at compile time but strict at runtime is opposite of what I'd want to work with.

**Comment by chanon** [comment]
I mean, the tradeoff is .. if you have a var, do you add a type specification to it?

If you do, you have to be absolutely sure that at runtime, it is never going to be assigned a value of another incompatible type. Because different from any other statically typed language, Typed GDScript is not going to help you at compile time, because if at any part of your code if you assign an untyped var to it, then it can blow up at runtime with no warning at compile time. And in current Typed GDScript you can't get away from untyped vars because they come at you from everywhere (for loops, Arrays, Dictionaries). 

Now, maybe it does help you catch bugs where the value is set wrongly at runtime that you didn't want. But it is also possible that something that would have been harmless if you wrote it in normal GDScript would cause runtime errors. 

This is from experience of actually trying putting type hints it in my current project. Instead of catching bugs, I made new ones. I know, I was careless .. but Typed GDScript (at least to me) was supposed to help me catch bugs, not make them.

**Comment by OvermindDL1** [comment]
@chanon It seems to me that Typed GDScript is more of a Positive Typer (like, say, Erlang/Dialyzer) rather than an HM typer, and though I would prefer HM typing, adding Positive Typing to a dynamic language is easier than adding HM typing.

**Comment by vnen** [comment]
> Ruby, same simple example

But Ruby, just like GDScript, does not have type inference. My point was to try to make an operation with it, not just assignment. It's the same as GDScript if you have no type hints.

> I mean, the tradeoff is .. if you have a var, do you add a type specification to it?
> If you do, you have to be absolutely sure that at runtime, it is never going to be assigned a value of another incompatible type. 

Again, if you *need* it to be a float (because you're making operations with it or something), then do type-hint it, since you'll catch the error early on. Otherwise it is pointless to add the type-hint, because the parser is relying that this variable is *always* a float to know what is safe or not. If you're not using the variable for anything, it does not require a type-hint.

In a dynamic scenario, you could try to forcibly cast it to float so you can use in operations:

```gdscript
var text = "something"
var number = float(text)
```

Which _still_ would cause a runtime error if `text` is not a String but an object, for instance.

If the type is not detectable at parse-time, the line is marked as unsafe, so you know it *might* give you a runtime error. If you remove the hints you'll see those lines in the example are marked as safe.

**Comment by OvermindDL1** [comment]
I am curious though @vnen, why does his picture show that the untyped assignment is typed (green line number, which is still so dreadfully easy to miss...) if it is not actually typed?

**Comment by chanon** [comment]
> But Ruby, just like GDScript, does not have type inference. My point was to try to make an operation with it, not just assignment. It's the same as GDScript if you have no type hints.

I was comparing Ruby to Typed GDScript. The fact that you can't create a runtime error with Ruby but you can with Typed GDScript with a simple non scary looking assignment.

As for an operation, many 'operations' can take multiple types.
For example in normal GDScript, this works
```
  var text = "some text"
  var myVar = 10.0
  print(myVar) # print takes floats
  myVar = text
  print(myVar) # print takes strings
```
If I add a float type to myVar, then the above does not work at runtime anymore. It will compile but it will error at runtime. Again, some may say that is good, but for me the fact that it allows it to compile but then not work at runtime is error-prone. Other languages would fail at compile-time.

> You can't compare with the other languages either because GDScript does not have implicit type inference.

At this point I wish it did.

> If the type is not detectable at parse-time, the line is marked as unsafe

Yes, this is what I try to do ... make sure all lines are green. However, since there is so much untyped stuff that you can't type, it isn't really possible to make all lines green. And those lines are where you are exposed to possible runtime errors. 

If you code with no type hints at all, just regular GDScript, then you only have to worry when you interface with engine class properties and methods. But with typing your own scripts, you have to worry about every typed<->untyped interaction.

**Comment by vnen** [comment]
@OvermindDL1 
> why does his picture show that the untyped assignment is typed (green line number, which is still so dreadfully easy to miss...) if it is not actually typed?

Because the green number does not mean it's "typed" but simply "type-safe". If a variable is a variant you can assign anything to it and it's still type-safe.

Also, it is supposed to be invisible unless you are looking for it. Beginners should not think there's something wrong with their code just because they're not using type hints.

**Comment by chanon** [comment]
I guess right now for me
- Everything statically typed => best (eg. C++)
- Everything (or almost everything) dynamically typed => good (eg. GDScript, which I am completely fine with)
- A lot of stuff statically typed and a lot of stuff untyped mixed together with no compile time protection = bad. (GDScript with Type hints)

**Comment by chanon** [comment]
> Erlang/Dialyzer

Elixir Dialyzer will only help you find existing runtime errors by adding types and running Dialyzer. It will not create new runtime errors by adding its types. If I understand correctly, I am new to it.

**Comment by OvermindDL1** [comment]
@vnen A variant is not terrible great at catching bugs however.  As well as a lack of proper typing significantly increases the chance that there is a bug there regardless so they _should_ think something is wrong with their code as it is likely that something is.

@chanon C++ I would definitely not ranked as strongly typed, maybe something like OCaml sure, but not C++...

GDScript's typing doesn't seem to add new runtime errors either, it only seems to catch them 'sooner' in anticipation of a possible AOT path, which needs to be done anyway, typing or not.

**Comment by chanon** [comment]
@OvermindDL1 I didn't say C++ was strongly typed, I said it was statically typed

**Comment by vnen** [comment]
The thing is that the safe lines and type hints are many times a trade-off. Consider this:

```
func _process(delta : float) -> void:
	var factor_dict : = { "level1": 1.2, "level2": 3.4 }
	var speed : = Vector2(100, 0)

	var factor : float = factor_dict.level1
	var movement = speed * factor * delta
```

In this case, the next to last line (where `factor` is defined), won't be type-safe because it can't get the type from the dictionary contents.

If you don't type it, then it'll be safe since the variable is Variant. But then the last line can't be sure to be a valid operation, so it won't be safe.

Note that if the value from the dictionary is not a number, it will fail either way. If you type the `factor` variable it'll fail on assignment, otherwise the operation in the last line will fail.

It really boils down to how confident you are about your code, and what kind of errors do you prefer to happen.

And this will be improved in the future when we add typed collections (which will also be applied to the `for` loop variable), and other editor tools like warnings panel and static analyzer.

**Comment by bojidar-bg** [comment]
<details>
<summary>
Long, complicated example about runtime type checks, click to expand (2¢)
</summary>
Consider a piece of untyped modular code where you have a player script creating a projectile object, setting it to apply a debuff, which later happens to  enemies hit by the projectile.

```gdscript
# player.gd
func shoot():
    var proj = projectile_scene.instance()
    proj.debuff = true
# projectile.gd
var debuff = false
func hit(object):
    if debuff: object.apply_debuff()
# enemy.gd
func apply_debuff():
    debuffed = true
```

Now, this was written by some sloppy programmer, whose colleague realizes that debuffs must have different types. So the colleague changes some scripts:

```gdscript
# projectile.gd
var debuff = null
func hit(object):
        if debuff: object.apply_debuff(debuff)
# enemy.gd
func apply_debuff(debuff):
    debuffs.push_back(debuff)
# ...
        for debuff in debuffs: debuff.apply(self)
```
Unfortunately, the colleague, running late for dinner, forgets to change the player script. And everything works, up until some enemy tries to apply the debuff a frame after it received it. At this point the call stack shows only `enemy.gd::_fixed_process` and shows nothing of the real culprit, the player script.

If instead, the GDScript was typed, then a runtime error at the line assigning `proj.debuff=true` would have been much more useful than the error a frame later in another, unrelated script. A compile-time error would be even better, but there are enough complicated cases in which compile-time checks are hard.
</details>

---

IMO, runtime errors complaining of invalid type saved in an object or in a method call are way more useful than runtime errors when the corrupted data is accessed. Compile time errors are better, but with Godot's dynamic node structure and multiple scripting languages, it would be hard-or-impossible to check all usecases and workflows.

**Comment by chanon** [comment]
The latest version fixes the bug with method calls I reported.

Also, I see the latest version now displays the error
```
Parser Error: Assigned value does not have a set type, variable type cannot be inferred.
```
when appropriate, which is nice. 

From my own testing, I think this is ready to merge.

I've decided that I will add a project settings option to disable runtime type checking in my own custom build after this gets merged. Then I can have it the way I want without impacting others. Since Godot is open source, it is no problem 😄

**Comment by chanon** [comment]
Wait, um another bug ... it is converting types to `String` where it shouldn't

```
extends Node2D

func _ready():
	var input = {"testing": "ok"}
	print(typeof(input))
	typedMethod(input)
	partiallyTypedMethod("something", input)

func typedMethod(dic: Dictionary):
	print(typeof(dic))

func partiallyTypedMethod(something: String, dic):
	print(typeof(dic))
```

Output:
```
18
18
4
```
18 -> Dictionary
4 -> String

Amazingly, the input dic gets converted into a String when going through a partially typed method.

**Comment by chanon** [comment]
Oh, there is another, almost forgot.

When using 'self', it doesn't seem to realize that the type of 'self' fits with what the method wants.

Global.gd autoload singleton:
```
extends Node

const MyNode2D = preload("res://MyNode2D.gd")

func show_energy(node: MyNode2D):
	print("Energy level is %d" % node.get_energy())
```

MyNode2d.gd
```
extends Node2D

func _ready():
	Global.show_energy(self)

func get_energy():
	return 100
```

Result:
image

**Comment by vnen** [comment]
@chanon 
> Looks like I'm the QA for this pull request :)

It seems you are indeed xD

> Wait, um another bug ... it is converting parameters to String where it shouldn't

I'll investigate, this shouldn't happen.

> Also, during development, I sometimes get 'cyclic preload error' that I can't get out of other than by closing the whole engine and opening it back up.

I guess the message needs to be more clear. This can happen in a cyclic preload but also if you try to preload a script that is failing to compile. In this case you need to fix the issues in the preloaded script and resave it, then force the parse of the current script by editing (like adding and deleting a space).

Maybe we could add a button to trigger the re-validation when needed. Or it could always re-validate when changing scripts.

> When using 'self', it doesn't seem to realize that the type of 'self' fits with what the method wants.

This is an interesting case. I'll have to see what can be done about it.

> In this example, if you try to workaround by removing the type on the show_energy function in Global.gd, the parse error in MyNode2D.gd won't disappear.

It's the same "cyclic preload error", like I said above.

----

Thanks for the tests. I don't have enough time to actually use this extensively yet, so I'm glad there's another pair of eyes on it.

**Comment by chanon** [comment]
I haven't had time to create a minimal reproduction yet, but it seems something strange is happening when the Typed version is built on macOS. My project just doesn't work with it. Events in gui_input come in as null.

**Comment by vnen** [comment]
> I haven't had time to create a minimal reproduction yet, but it seems something strange is happening when the Typed version is built on macOS. My project just doesn't work with it. Events in gui_input come in as null.

You mean the project doesn't work on macOS but works in other platforms? That's really odd, I didn't any platform-specific code path.

**Comment by chanon** [comment]
> You mean the project doesn't work on macOS but works in other platforms? That's really odd, I didn't any platform-specific code path.

Correct. I have prepared a minimal test project:
[TestTypedMacOS2.zip](https://github.com/godotengine/godot/files/2136894/TestTypedMacOS2.zip)

Result when run in Windows 10 normal build:
Blue window, when clicked on outputs `OK!` to output.

Result when run in Windows 10 Typed build:
Blue window, when clicked on outputs `OK!` to output.

Result when run in macOS High Sierra Version 10.13.5 normal build:
Blue window, when clicked on outputs `OK!` to output.

Result when run in macOS High Sierra Version 10.13.5 typed-gdscript-final branch build:
image
and this strange error:
image

**Comment by vnen** [comment]
I wonder if this is an issue with macOS input handling that's only surfaced by my changes.

**Comment by vnen** [comment]
Fixed the issue with types in function calls. Might have fixed this macOS problem as well.

**Comment by chanon** [comment]
I have tested the latest version and all 3 issues I reported have been fixed including the macOS problem.

However, there are two new issues that I found.

First one is with this code:
```
extends Node2D

class Test:
	var value1: String = "hello1"
	var value2: String = "hello2"

func _ready():
	var test: Test = Test.new()
	if ("value1" in test):
		print("ok")
```
it results in this:
image

**Comment by chanon** [comment]
Second one is a bit scary as it can cause corrupted scene files on save. Was a bit hard to track down the cause, but once I saw it, it was obvious.

The cause is, if you have a `tool` script that has export vars, it will cause Script Variables to be listed as [null]

For example with this code:
```
tool
extends Control

# actually, I don't think it has to be a setget export
# but this is just to illustrate 
export var mytext = "hello" setget set_mytext, get_mytext

func _ready():
	pass

func set_mytext(input):
	$Label.text = input
	mytext = input

func get_mytext():
	return mytext
```
If you select an instance of it, in the inspector you would expect to see:
image
However, in Typed GDScript version you will see:
image
If you have a scene that contains an instance of this tool scene and you make any edits to it and save it, your scene will be corrupted. When you close and reopen it, you will see two instances of the tool scene. If the tool script has more export vars, then there will be more duplicates.


Example project:
[GetSetCorrupt.zip](https://github.com/godotengine/godot/files/2142851/GetSetCorrupt.zip)

**Comment by vnen** [comment]
Exports and tools never worked well in my experience. I'm not sure if I'm breaking something or just surfacing something else. I'll see what's going on.

**Comment by vnen** [comment]
Also, I'll try to take some time to make a suite of thorough tests to check for more regressions.

**Comment by vnen** [comment]
Actually, I did something wrong. What baffles me is that export was working fine, it only broke when `tool` was added.

**Comment by chanon** [comment]
After testing, can confirm that both reported issues have been fixed. Will continue adding type hints to my project and see if any other issues come up.

Again, it is _probably_ ready to merge. Not sure if July 1st target for 3.1 Alpha is still on, but I think it should be in the Alpha so it can get wider testing. Just hope there are no more scene file corrupting bugs.

**Comment by aaronfranke** [comment]
July 1st is no longer the target. [Akien said](https://github.com/godotengine/godot/issues/19101#issuecomment-401528882) it would be at least a few weeks, so I'd expect the alpha to be out in a month. However, we should try to get this feature finished up and merged soon so that we have plenty of time for testing it.

**Comment by vnen** [comment]
The code completion is now redone. I was planning to do in another PR but since this is not merged yet and the rewrite depends on this, I'll bundle it together.

**Comment by RandomShaper** [comment]
Sorry for adding some noise to this thread, but I couldn't help congratulating you for your amazing work on this.

**Comment by chanon** [comment]
Have been developing my game project with Typed GDScript for a few days now and haven't found any new major bugs. Sometimes I get some unexpected errors, but I'm not sure if it is just my code.

Once this gets merged I will open a few issues for minor stuff and related feature requests.

**Comment by jahd2602** [comment]
@reduz Should this be merged? or is there anything stopping the merge?

**Comment by MarianoGnu** [comment]
i just oppened an existing project "as is" and found out the following messages on console, everithing in tool scritps (wich makes sense since it's just runing on editor)

imagen

**Comment by MarianoGnu** [comment]
it loops on this piece of code, base_script never changes it's value, so makes sense produce a CRC
```

	while (base_script.is_valid()) {
		native = base_script->get_instance_base_type();
		MethodInfo mi = base_script->get_method_info(p_function);

		if (!(mi == MethodInfo())) {
			r_return_type = _type_from_property(mi.return_val, false);
			r_default_arg_count = mi.default_arguments.size();
			for (List<PropertyInfo>::Element *E = mi.arguments.front(); E; E = E->next()) {
				r_arg_types.push_back(_type_from_property(E->get()));
			}
			return true;
		}
	}
```

changed the "while" for an "if" statement and now project starts, but have not idea if this is the right fix...

**Comment by MarianoGnu** [comment]
i compiled to test this PR along with optional class names on GdScript, looks like it's not working yet, but could not be related to the PR in particular, instead could be that gdScript class names are not exposed or being checked when  the Editor or parser looks for simbols

imagen
imagen
imagen

**Comment by vnen** [comment]
@MarianoGnu
> i compiled to test this PR along with optional class names on GdScript, looks like it's not working yet

Reduz added this yesterday, I haven't had time to update this PR yet. It won't work as is because the checks I added don't know about the existence of these new classes (it's a new case I need to add).

> i just oppened an existing project "as is" and found out the following messages on console, everithing in tool scritps (wich makes sense since it's just runing on editor)
The project never finishes loading, it just hangs on the splash screen

> it loops on this piece of code, base_script never changes it's value, so makes sense produce a CRC

Yeah, that might be it. I really need this code in the wild to catch stuff like that. The issue is I forgot to get the base type of the script (it should keep getting the base while it's valid).

About the particular error (function signature doesn't match parent) it is something that GDScript allowed but I find it a bug, since it breaks the expectation of inheritance. This can be considered compatibility breaking, I'm not sure if there's any way around it.

**Comment by vnen** [comment]
Updated to make use of the new named classes.

**Comment by vnen** [comment]
Fixed some issues in release builds. Should be good to merge.

**Comment by akien-mga** [comment]
Alright, this seems pretty ripe for merging and wider testing in the *master* branch!

**Note:** Regressions are fully possible at this stage, even though @vnen and @chanon did a great job testing the PR and fixing many issues. Please report any issue you stumble upon, and give @vnen a few days to have a look at fixing them :)

If you're adventurous and use dev builds in "production", you may want to stick to 2b9902db for a bit while we're ironing out the main issues (if any).

**Comment by YeldhamDev** [comment]
@vnen Just a quick question, is there a way to set the type in a `for` loop? For example:
`for i in stuff`, where I want to define the type of `i`.

**Comment by vnen** [comment]
> Just a quick question, is there a way to set the type in a for loop? For example:
for i in stuff, where I want to define the type of i.

No, it's not possible in the current state.

**Comment by aaronfranke** [comment]
As /u/Cheekydood asked on Reddit, does this allow overloading of functions with different typed args?

**Comment by vnen** [comment]
@aaronfranke no, that is not possible to do in a performant way, considering typing is optional.

**Comment by jahd2602** [comment]
Running a project on Android with Godot, 1 commit before this PR, works fine. After compiling master and testing on Android, I get this error:

```
07-24 11:47:34.419 15303-15337/org.godotengine.jumpingdown E/godot: **SCRIPT ERROR**: Parse Error: Too many arguments for '()' call. Expected at most 0 but called with 3.
       At: res://Scripts/jumpingPlayer.gdc:12:GDScript::load_byte_code() - Parse Error: Too many arguments for '()' call. Expected at most 0 but called with 3.
    **ERROR**: Method/Function Failed, returning: ERR_PARSE_ERROR
       At: modules\gdscript\gdscript.cpp:760:load_byte_code() - Method/Function Failed, returning: ERR_PARSE_ERROR
    **ERROR**: Condition ' err != OK ' is true. returned: RES()
       At: modules\gdscript\gdscript.cpp:1939:load() - Condition ' err != OK ' is true. returned: RES()
    **ERROR**: Failed loading resource: res://Scripts/jumpingPlayer.gdc
       At: core\io\resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
    **ERROR**: res://Objects/jumping_down.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Scripts/jumpingPlayer.gd
       At: scene\resources\scene_format_text.cpp:439:poll() - res://Objects/jumping_down.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Scripts/jumpingPlayer.gd
    **ERROR**: Condition ' err != OK ' is true. returned: RES()
       At: core\io\resource_loader.cpp:149:load() - Condition ' err != OK ' is true. returned: RES()
07-24 11:47:34.427 15303-15337/org.godotengine.jumpingdown E/godot: **ERROR**: Failed loading resource: res://Objects/jumping_down.tscn
       At: core\io\resource_loader.cpp:186:_load() - Method/Function Failed, returning: RES()
07-24 11:47:34.442 15303-15337/org.godotengine.jumpingdown E/godot: **ERROR**: Failed loading scene: res://Objects/jumping_down.tscn
       At: main\main.cpp:1678:start() - Condition ' !scene ' is true. returned: false
```

BTW it is working fine in Windows and Linux.

**Comment by akien-mga** [comment]
@jahd2602 Please open a separate bug report, it's hard to keep track of issues in a merged PR.

**Comment by jahd2602** [comment]
@akien-mga I just found the issue: https://github.com/godotengine/godot/issues/20346

**Comment by girng** [comment]
i tried 3.1  and this typed gdscript feels very similar to a statically typed and very strict language. for example, getting errors because i forgot to use a variable in a block. which was not intended at all it was just leftover code ( i'm also getting a lot of red warnings for really weird stuff that wasn't prevalent in 3.0.6, _this makes the developer feel less and less confident_). this is not the gdscript i fell in love with because it was more layed back (less intrusive), and made the developer feel more free. now, it seems like there is a "strict" guideline we have to follow. in my honest opinion, I think it's striving away from the simplicity and ease of use that the original gdscript offered.

with regards to the slim arrows (`->`), and `:=`, i think new syntax is ok. but personally not a fond of how restrictive the new language feels now, it feels like something totally new. i apologize if this is an unpopular opinion, but i feel like it's important to let admins/lead devs know

**Comment by aaronfranke** [comment]
> for example, getting errors because i forgot to use a variable in a block.

@girng That's not Typed GDScript, that's the new warning system: https://github.com/godotengine/godot/issues/18271

**Comment by vnen** [comment]
@girng you can disable warnings in the project settings if you want.

I'm closing this thread because bugs and suggestions about Typed GDScript should be made in a new clean issue. This thread is already too long.
