### PR TITLE
Reimport bone attachment fixes

### LINKED ISSUE #82466: 3D Armature with BoneAttachment Glitches on Reimport
### Godot version

4.1.1

### System information

Windows 10 - Godot v4.1.1 - Vulkan(Forward+) - dedicated

### Issue description

If a model with an **armature** AND with **direct object-to-bone parenting** (imported as **BoneAttachment3D** in Godot) is changed in blender and reimported, it can break instances of the model's armature under specific circumstances.

Use Cases: A character is rigged with an armature using vertex weights, except for a weapon parented to the hand bone, or a hat parented to the head bone.

Of Note: 
- Dragging in a new instance of the model into the scene does not exhibit the bug. Only model instances which exist within scenes are affected.

**Before:**
image

**After another BoneAttachement3D is added over head:**
image

### Steps to reproduce

**Step 1**: Import model to Godot. The model is then dragged into a scene **AND** "Editable Children" is toggled. If a model is turned into a "new inherited scene", the bug will occur without needing to toggle "Editable Children".

**Step 2**: In Blender, add another object that is parented directly to a bone. Export to Godot, overwriting the previous version.
image
image

**Step 3**: Upon importing, instances of the armature within scenes will bug out. Some bones will now be oriented in erroneous directions, and some previously existing BoneAttachement3Ds may no longer have the correct "Bone Idx" (1 value off if the new object precedes it in the hierarchy).

For simple reproduction, a project zip has been included which contains a README with instructions and models already setup to reproduce the bug. You will need Blender 3.6 to reproduce the bug. This bug has been reproduced with the following file types: .fbx, .gltf, .blend. For the sake of unified export options, this reproduction uses .blend

### Minimal reproduction project

[Bug Report Bone Attachement 3d.zip](https://github.com/godotengine/godot/files/12744689/Bug.Report.Bone.Attachement.3d.zip)

### LINKED ISSUE #82680: Model reimport causes TextureRect to throw NOTIFICATION_DRAW error
### Godot version

v4.1.2.rc1.official [58f0cae4a]

### System information

Windows 11, Forward+, All versions of Godot 4

### Issue description

Reimporting a 3D model can cause this error to appear once or multiple times:
`Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.`

### Steps to reproduce

Open main.tscn in the included reproduction project.
Reimport the included test.glb model by either double-clicking it and reimporting it from the Advanced Settings window, or by clicking the "Reimport" button in the Import tab.
Notice the error messages in the console.

In general, the following conditions need to be met for the error to appear:
- A scene containing a node that inherits from the reimported model must be open.
- The open scene needs to also contain one or more TextureRect nodes with a texture of any kind assigned.

### Minimal reproduction project

[DrawErrorTest.zip](https://github.com/godotengine/godot/files/12782724/DrawErrorTest.zip)

### PR DESCRIPTION
**Pull request by SaracenOne**
~~Fixes an oversight of accidentally giving NOTIFICATION_NODE_RECACHE_REQUESTED the same ID as NOTIFICATION_DRAW, and adds the notification to BoneAttachment3D and Skeleton3D~~

Fixes some bugs in GLTF importing which would lead to issues when reimporting the scene. An earlier version of this PR also made use of the NOTIFICATION_NODE_RECACHE_REQUESTED notification, but discussions in RocketChat indicated that usage of this notification may not have been desirable, so for now, I've included a bespoke recursive function with special-case handling for Skeleton3Ds and BoneAttachment3Ds and removed dependency on NOTIFICATION_NODE_RECACHE_REQUESTED.

Closes [#82466](https://github.com/godotengine/godot/issues/82466)
Closes [#82680](https://github.com/godotengine/godot/issues/82680)

### CODE REVIEW

**Comment by SaracenOne** [comment]
I've updated this fix a bit more throughly to also have the GLTF importer assign the correct bone_idx at this. This needs to be done because otherwise, it doesn't get saved and we cannot derive the correct reset value from any scene which derive from it. I've also forced the bone_idx to -1 during the RECACHE notification to ensure that the idx will get properly updated.

An issue remaining is that with changing the enum values, the build system warns of compat breakage with GDExtension. Since this is an enum which I imagine nobody used it was only designed to deal with bugs like this, would request information on how to proceed.

**Comment by Sauermann** [comment]
part of #75839

**Comment by slumberface** [comment]
Tested this with a build using 8ef1cd5. The main issue in ticket https://github.com/godotengine/godot/issues/82466 seems to be fixed! The armature itself no longer appears to glitch visually. But by adding a total of **6** bone attachments, and then removing **2**, the lowest bone attachment in the hierarchy stays at idx 16 (incorrectly pointing to a idx associated with the armature), instead the new correct idx which appears to be 14.
**Incorrect:**
image
**Correct after manually adjusting:**
image

**Comment by SaracenOne** [comment]
Hmm, would it be possible to do another reproduction project for this specific instance too @slumberface? I just want to make sure I'm not making a mistake and am actually reproducing the situation as accurately as possible.

**Comment by slumberface** [comment]
@SaracenOne I can definitely make another reproduction that demonstrates this last situation. Do you want it made on 4.1.1 or https://github.com/godotengine/godot/commit/8ef1cd51b21ef4ecfbe2df2ec769b449a95dd8c4?

**Comment by SaracenOne** [comment]
Thanks! @slumberface 
https://github.com/godotengine/godot/commit/8ef1cd51b21ef4ecfbe2df2ec769b449a95dd8c4 Would probably be easier for me

**Comment by slumberface** [comment]
@SaracenOne I'm experiencing an issue where the Godot editor/engine itself won't compress in windows (file names that are too long??). Here is the asset folder you can drag into a 4.1.1 project. Same instructions for reproduction but this test has:
- 6 BoneAttachments to begin with
- Instead of adding BoneAttachments, 2 are removed when Model_A is overwritten with Model_B (the first test was only adding bone attachments and I believe your branch seems to fix that scenario)

[Assets for BoneAttachment Bug.zip](https://github.com/godotengine/godot/files/12785062/Assets.for.BoneAttachment.Bug.zip)

**Comment by slumberface** [comment]
@SaracenOne no worries on the delay and good work circling back to this!

**Comment by Bromeon** [comment]
This partly fixes https://github.com/godotengine/godot/issues/75839, too.

I'm not sure if any other conflicts should be addressed as well, or only this critical one.

**Comment by AThousandShips** [comment]
This notification collision also causes this:
* https://github.com/godotengine/godot/issues/82680

**Comment by AThousandShips** [comment]
Do we want to just remove calling the notification for 4.2 and do an overhaul in 4.3, we have issues arising from it and close to release

**Comment by SaracenOne** [comment]
PR's been updated with a more ad-hoc fix for this bug and removed dependency on the notificiation which was discussed to potentially be undesirable.

File: scene/3d/skeleton_3d.cpp [hunk 1]
```diff
@@ -318,6 +318,9 @@ void Skeleton3D::_notification(int p_what) {
 				set_physics_process_internal(true);
 			}
 		} break;
+		case NOTIFICATION_NODE_RECACHE_REQUESTED: {
```
Comment (YuriSizov) [inline scene/3d/skeleton_3d.cpp:321]: This should be removed now. And the notification itself can be removed completely (don't forget to run the doctool).

**Review by YuriSizov — APPROVED** [review]
Approving for the overall consensus and for the editor side of changes. Should be okay for now, but we will need to rework it later, of course.

Needs some clean up, and an approval from the animation team would be appreciated.

File: scene/3d/skeleton_3d.cpp (hunk 1 above)
Comment (SaracenOne) [reply scene/3d/skeleton_3d.cpp]: Ah, missed this. Removed it now.

**Review by AThousandShips — APPROVED** [review]
LGTM

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!
