### PR TITLE
Fix crash related to #region/#endregion caused by trailing spaces

### LINKED ISSUE #103797: Editor crashes when entering simple if statement
### Tested versions

Master since ba3f4a4b24fe93a77dfd1390f1b0ea4352c664ab

### System information

Godot v4.5.dev (b5bdb8806) - Fedora Linux 41 (Workstation Edition) on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) - 13th Gen Intel(R) Core(TM) i7-13700K (24 threads)

### Issue description

Since commit ba3f4a4b24fe93a77dfd1390f1b0ea4352c664ab, I am seeing an editor crash if you enter the following text into a script:
```
extends Node3D

var count = 0
func _process(delta):
    if count>0:
```

When pressing enter after the colon, the editor crashes.

Following backtrace is generate:
```
(gdb)  bt
#0  0x0000000003442597 in CowData<char32_t>::get (this=<optimized out>, p_index=<optimized out>) at ./core/templates/cowdata.h:217
#1  String::operator[] (this=<optimized out>, p_index=<optimized out>) at ./core/string/ustring.h:342
#2  GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl (this=0x2c436940, p_line=<optimized out>) at modules/gdscript/editor/gdscript_highlighter.cpp:606
#3  0x00000000060b796b in SyntaxHighlighter::get_line_syntax_highlighting (this=this@entry=0x2c436940, p_line=<optimized out>, p_line@entry=5)
    at scene/resources/syntax_highlighter.cpp:46
#4  0x000000000564681b in TextEdit::_get_line_syntax_highlighting (this=this@entry=0x2c13c7e0, p_line=<optimized out>, p_line@entry=5) at scene/gui/text_edit.cpp:8432
#5  0x0000000005685314 in TextEdit::_notification (this=<optimized out>, p_what=<optimized out>) at scene/gui/text_edit.cpp:883
#6  0x000000000539a5a7 in TextEdit::_notificationv (this=0x2c13c7e0, p_notification=30, p_reversed=false) at ./scene/gui/text_edit.h:41
#7  CodeEdit::_notificationv (this=0x2c13c7e0, p_notification=30, p_reversed=<optimized out>) at scene/gui/code_edit.h:37
#8  0x000000000761c6f8 in Object::notification (this=0x2c13c7e0, p_notification=30, p_reversed=false) at core/object/object.cpp:911
#9  0x00000000051a5d61 in CanvasItem::_redraw_callback (this=0x2c13c7e0) at scene/main/canvas_item.cpp:144
#10 CanvasItem::_redraw_callback (this=0x2c13c7e0) at scene/main/canvas_item.cpp:133
#11 0x00000000076171b8 in CallQueue::_call_function (this=this@entry=0x7de1580, p_callable=..., p_args=p_args@entry=0x995cc58, p_argcount=0, p_show_error=true)
    at core/object/message_queue.cpp:220
#12 0x0000000007617472 in CallQueue::flush (this=0x7de1580) at core/object/message_queue.cpp:268
#13 0x00000000052744ad in SceneTree::physics_process (this=0xa5de390, p_time=0.016666666666666666) at scene/main/scene_tree.cpp:535
#14 0x0000000002b8db72 in Main::iteration () at main/main.cpp:4462
#15 0x0000000002b1b861 in OS_LinuxBSD::run (this=this@entry=0x7fffffffd150) at platform/linuxbsd/os_linuxbsd.cpp:980
#16 0x0000000002b190f5 in main (argc=<optimized out>, argv=0x7fffffffd7a8) at platform/linuxbsd/godot_linuxbsd.cpp:85
```

### Steps to reproduce

1. Create project.
2. Attach script to node.
3. Add an if statement as listed above.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by JulianHeuser**
Fixes #103797 
Issue introduced in #101319

(Also is mildly more efficient since it isn't redundantly splitting twice)

### CODE REVIEW

**Comment by tdaven** [comment]
I can confirm that this fixes https://github.com/godotengine/godot/issues/103797 for me.

File: modules/gdscript/editor/gdscript_highlighter.cpp [hunk 1]
```diff
@@ -151,10 +151,13 @@ Dictionary GDScriptSyntaxHighlighter::_get_line_syntax_highlighting_impl(int p_l
...
-								str.strip_edges().split_spaces()[0] != "#region" &&
-								str.strip_edges().split_spaces()[0] != "#endregion") {
-							match = false;
+						if (color_regions[c].type == ColorRegion::TYPE_CODE_REGION) {
+							Vector<String> str_stripped_split = str.strip_edges().split_spaces();
+							if (!str_stripped_split.is_empty() &&
+									str_stripped_split[0] != "#region" &&
+									str_stripped_split[0] != "#endregion") {
+								match = false;
+							}
```
Comment (dalexeev) [inline modules/gdscript/editor/gdscript_highlighter.cpp:160]:
```suggestion
							String stripped_str = str.strip_edges();
							if (!stripped_str.begins_with("#region") && !stripped_str.begins_with("#endregion")) {
								match = false;
							}
```

Comment (JulianHeuser) [reply modules/gdscript/editor/gdscript_highlighter.cpp:160]: This works but undoes the original fix where this bug was introduced.
For example, "#region" and "#endregion" here are highlighted, but don't actually create a region you can collapse or expand.
image
We need to check for whitespace after region/endregion to fix this.

Comment (dalexeev) [reply modules/gdscript/editor/gdscript_highlighter.cpp:160]: Yes, we can use the `maxsplit` parameter since we are only checking the 0th substring.

Or alternatively we could extract the alphanumeric identifier after the `#`. Since the current version does not take into account cases like `#region:Name`. I think we should add methods like `String.get_{ascii,unicode}_identifier(from: int = 0) -> String`.

Comment (JulianHeuser) [reply modules/gdscript/editor/gdscript_highlighter.cpp:160]: Is there a source for what characters should be after `#region` or is that up in the air? The only examples the docs show are with whitespace.

**Review by SaracenOne — APPROVED** [review]
LGTM 👍

**Comment by Repiteo** [comment]
Thanks!
