### PR TITLE
Fix VoxelGI saving VoxelGIData as a built-in file, despite being prompted to save it to an external file

### LINKED ISSUE #50029: Saving the scene after baking lightmaps or VoxelGI will save the lightmap/VoxelGI data as a built-in file, despite being prompted to save it to an external file beforehand
### Godot version

3.3.2.stable, 4.0.dev (659178e85)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

When you bake lightmaps with a BakedLightmap node for the first time, you're prompted to save a `.lmbake` file that will contain the BakedLightmapData. This file is correctly generated once, but once you save the scene, the BakedLightmapData will be saved built-in to the scene file, which makes it huge and slow to load/save (since binary data is converted to Base64).

This also happens with GIProbe/VoxelGI in my experieence.

### Steps to reproduce

- Create a BakedLightmap node.
- Create a [lightmapping setup](https://docs.godotengine.org/en/stable/tutorials/3d/baked_lightmaps.html).
- Save your scene to a `.tscn` file.
- Select the BakedLightmap node and click **Bake**. Accept the default save location for the `.lmbake` file.
- Press <kbd>Ctrl + S</kbd> to save the scene.
- Notice how the `.tscn` file becomes huge on disk (several megabytes or more). This is not as noticeable with a binary `.scn` file, but it'll still be pretty large.

### Minimal reproduction project

https://github.com/Calinou/godot-demo-projects/tree/add-global-illumination-demo-2/3d/global_illumination

### PR DESCRIPTION
**Pull request by MineBill**
This fixes #50029.

It seems like the resource saver will change the VoxelGIData resource path to the external file, save the resource and the revert it to what it was previously (an empty string), essentially creating two resources, one built-in to the scene (which has the actual data) and the external file. I do not know why the resource saver works this way, but the `ScriptCreateDialog` does the same thing:
```cpp
String lpath = ProjectSettings::get_singleton()->localize_path(file_path->get_text());
scr->set_path(lpath);
Error err = ResourceSaver::save(scr, lpath, ResourceSaver::FLAG_CHANGE_PATH);
if (err != OK) {
	alert->set_text(TTR("Error - Could not create script in filesystem."));
	alert->popup_centered();
	return;
}
``` 
so I copied that.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works.

image

File: editor/plugins/voxel_gi_editor_plugin.cpp [hunk 1]
```diff
@@ -166,8 +166,10 @@ void VoxelGIEditorPlugin::_voxel_gi_save_path_and_bake(const String &p_path) {
 	probe_file->hide();
 	if (voxel_gi) {
 		voxel_gi->bake();
-		ERR_FAIL_COND(voxel_gi->get_probe_data().is_null());
-		ResourceSaver::save(voxel_gi->get_probe_data(), p_path, ResourceSaver::FLAG_CHANGE_PATH);
+		Ref<VoxelGIData> voxel_gi_data = voxel_gi->get_probe_data();
```
Comment (Calinou) [inline editor/plugins/voxel_gi_editor_plugin.cpp:169]: Add a comment to explain why this is done:

```suggestion
		// Ensure the file is always saved to an external resource.
		// This avoids bloating the scene file with large binary data,
		// which would be serialized as Base64 if the scene is a `.tscn` file.
		Ref<VoxelGIData> voxel_gi_data = voxel_gi->get_probe_data();
```

Comment (MineBill) [reply editor/plugins/voxel_gi_editor_plugin.cpp:172]: Done!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
