### PR TITLE
Set an appropriate minimum size for labels in windows that display incorrectly

### LINKED ISSUE #85551: [4.2] Export Window Sized outside of screen, cannot be resized when export template is selected
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

{73902E40-48C8-4573-A9D8-F4075EDDB875}
{4337DBCF-2184-445A-9A41-D82DE05FB55E}
{D6BE09FD-C644-49CB-894F-71F550415ABD}

### Steps to reproduce

Just converted my 4.1 project to 4.2, wanted to export immediately as the given project is just a gateway for my server.

### Minimal reproduction project

n/a

### LINKED ISSUE #86136: Export dialog becomes extremely tall if using dedicated server export mode
### Tested versions

- Reproducible in: 4.2.stable, 4.2.1.stable
- Not reproducible in: 4.1.3.stable

### System information

Godot v4.3.dev (aa5b6ed13) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

When you open the Export dialog, it initially looks correct:

Screenshot_20231214_004727

As soon as you select an export preset that uses dedicated server export mode (configured on the **Resources** tab), the window becomes extremely tall:

Screenshot_20231214_004738

This makes it impossible to reach the buttons at the bottom of the Export dialog, even on a large display.

This is presumably due to the Tree node used within the Resources tab. I bisected the regression to e5bebbc9ffda8b4fa5a786842ea24f0a3ea0763a. cc @Rindbee 

### Steps to reproduce

- Create a project with many folders and files.
- Open the Export dialog and create an export preset.
- Switch to the Resources tab and set the export mode to **Export as dedicated server**.
- Notice the window becoming extremely tall.

### Minimal reproduction project (MRP)

[test_dedicated_server_export_window_height.zip](https://github.com/godotengine/godot/files/13666766/test_dedicated_server_export_window_height.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
When the label's `autowrap_mode` is `AUTOWRAP_WORD_SMART` and the initial `text` is set at the same time, it may have a higher height than expected. See https://github.com/godotengine/godot/issues/80218#issuecomment-1669527304 for more details.

Set an appropriate minimum size for labels in windows that display incorrectly so that these windows display properly.

As a workaround for display issues in the editor caused by #77280.

Close #86136.
Closes https://github.com/godotengine/godot/issues/85551.

### CODE REVIEW

**Review by YuriSizov — DISMISSED** [review]

File: editor/export/project_export.cpp [hunk 1]
```diff
@@ -1276,6 +1276,7 @@ ProjectExportDialog::ProjectExportDialog() {
 	server_strip_message = memnew(Label);
 	server_strip_message->set_visible(false);
 	server_strip_message->set_autowrap_mode(TextServer::AUTOWRAP_WORD_SMART);
+	server_strip_message->set_size(Size2(500, 1) * EDSCALE);
```
Comment (YuriSizov) [inline editor/export/project_export.cpp:1279]: We should use `set_custom_minimum_size` and force the minimum size, not set the default size, this is unreliable.

File: editor/import/dynamic_font_import_settings.cpp [hunk 2]
```diff
@@ -1345,6 +1345,7 @@ DynamicFontImportSettingsDialog::DynamicFontImportSettingsDialog() {
 	page2_description->set_text(TTR("Add font size, and variation coordinates, and select glyphs to pre-render:"));
 	page2_description->set_h_size_flags(Control::SIZE_EXPAND_FILL);
 	page2_description->set_autowrap_mode(TextServer::AUTOWRAP_WORD_SMART);
+	page2_description->set_size(Size2(500, 1) * EDSCALE);
```
Comment (YuriSizov) [inline editor/import/dynamic_font_import_settings.cpp:1348]: I don't see any fixed size for this dialog, so it's worth to double-check if 500 is not too much, This value should be rather conservative (applies to all 3 labels).

**Review by YuriSizov — CHANGES_REQUESTED** [review]
See above.

File: editor/export/project_export.cpp (hunk 1 above)
Comment (Rindbee) [reply editor/export/project_export.cpp:1279]: One characteristic of this series of issues is that during first `Label::_shape()`, the size assigned to the label by the container has not been updated, causing the label's initial width to be 0, so a relatively large minimum height is calculated. 

https://github.com/godotengine/godot/blob/26b1fd0d842fa3c2f090ead47e8ea7cd2d6515e1/scene/gui/label.cpp#L104-L106

If the initial width is large enough, this won't happen. The minimum size is calculated as a single line height.

Comment (YuriSizov) [reply editor/export/project_export.cpp:1279]: Enforcing a minimum size is still more reliable because it doesn't depend on the order of events. You just need to pick a size which will be within the dialog's own minimum size, so there is no visible difference for the end user.

**Review by YuriSizov — APPROVED** [review]

File: editor/export/project_export.cpp [hunk 3]
```diff
@@ -1277,6 +1277,7 @@ ProjectExportDialog::ProjectExportDialog() {
 	server_strip_message = memnew(Label);
 	server_strip_message->set_visible(false);
 	server_strip_message->set_autowrap_mode(TextServer::AUTOWRAP_WORD_SMART);
+	server_strip_message->set_custom_minimum_size(Size2(300, 1) * EDSCALE);
```
Comment (AThousandShips) [inline editor/export/project_export.cpp:1280]:
```suggestion
	server_strip_message->set_custom_minimum_size(Size2(300 * EDSCALE, 1));
```
Same for all, IMO it doesn't make sense to scale `1`, and might cause weirdness

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
