### PR TITLE
Windows: Fix compilation warnings with GCC 11.2.1

### LINKED ISSUE #35194: -Wnon-virtual-dtor warning with MinGW/GCC in AudioDriverWasapi
**Godot version:**
3.2 master (a2c90fe2f)

**OS/device including version:**
Linux, cross-compiling for Windows with MinGW 5.0.4 and GCC 8.3.0

**Issue description:**
With the above compiler, this warning is raised in `scons p=windows tools=yes target=debug`:
```
drivers/wasapi/audio_driver_wasapi.cpp:71:7: warning: base class 'struct IMMNotificationClient' has accessible non-virtual destructor [-Wnon-virtual-dtor]
 class CMMNotificationClient : public IMMNotificationClient {
       ^~~~~~~~~~~~~~~~~~~~~
```

Our implementation seems directly taken from https://docs.microsoft.com/en-us/windows/win32/coreaudio/device-events, and this warning would normally be fixed by changing `IMMNotificationClient`'s destructor to `virtual`, but it's a Windows SDK struct and we have no control over it.

**Steps to reproduce:**
See above.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #35194.

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -42,6 +42,11 @@
 #include "drivers/gles3/rasterizer_gles3.h"
 #endif
 
+#if defined(__GNUC__)
+// Workaround GCC warning from -Wcast-function-type.
+#define GetProcAddress (void *)GetProcAddress
+#endif
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:48]: We had the same in other Windows-specific files, it was just missing here.
