### PR TITLE
[Unix] Fix `execute_with_pipe` closing wrong pipe handle.

### LINKED ISSUE #109652: OS.execute_with_pipe causes SIGPIPE crash on writing to a restarted process
### Tested versions

- Reproducible in 4.5.beta.custom_build.45509c284

### System information

Ubuntu - 4.5.beta.custom_build.45509c284 - x86_64

### Issue description

Upon restarting a process, a call to pipe() in the OS_Unix driver provides `0` as the read file descriptor to `pipe_in`:
 ```cpp
// OS_Unix::execute_with_pipe, lines 737-741
int pipe_in[2] = { -1, -1 };
int pipe_out[2] = { -1, -1 };
int pipe_err[2] = { -1, -1 };

ERR_FAIL_COND_V(pipe(pipe_in) != 0, ret); // upon restart pipe_in[0] = 0

// ...
// lines 772-773,  inside forked process
::close(STDIN_FILENO);
::dup2(pipe_in[0], STDIN_FILENO); //  bad file descriptor error.

```

The editor crashes on any write operation with the bad pipe, in reference to the MRP's main.gd
```gdscript
func _on_write_pressed() -> void:
	pipe_process.stdio.store_line(%TextEdit.text) # <--- SIGPIPE happens here, applies to any write method
```

### Steps to reproduce

1. Run project
2. Enter text in text edit and press the button to write to stdin
3. Restart the process with either the regular restart button or restart with time button
4. Try to write to stdin again, the game will crash

### Minimal reproduction project (MRP)

[sigpipe_crash_project.zip](https://github.com/user-attachments/files/21803380/sigpipe_crash_project.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
`0` can be a valid handle in use (see https://github.com/godotengine/godot/pull/108737#pullrequestreview-3097448794 for example, it was closing pipe handle used by `popen` and breaking it).

Fixes https://github.com/godotengine/godot/issues/109652

### CODE REVIEW

File: drivers/unix/os_unix.cpp [hunk 1]
```diff
@@ -795,7 +795,7 @@ Dictionary OS_Unix::execute_with_pipe(const String &p_path, const List<String> &
 
 	Ref<FileAccessUnixPipe> err_pipe;
 	err_pipe.instantiate();
-	err_pipe->open_existing(pipe_err[0], 0, p_blocking);
+	err_pipe->open_existing(pipe_err[0], -1, p_blocking);
```
Comment (m4gr3d) [inline drivers/unix/os_unix.cpp:798]: Does this need include the additional changes in https://github.com/godotengine/godot/pull/108737:
```
	if (pid == 0) {
		// The new process
		// Create a new session-ID so parent won't wait for it.
		// This ensures the process won't go zombie at the end.
		setsid();
```

Comment (bruvzg) [reply drivers/unix/os_unix.cpp:798]: It's not directly related to the bug. Probably make sense to set it, but it's not critical to have in 4.5. I'll test this part of it later.

**Review by Repiteo — APPROVED** [review]
Simple change and the issue's OP claims this fixes things, so I say we run with it

**Comment by Repiteo** [comment]
Thanks!
