### PR TITLE
The inspector will show the custom resources added via plugin

### LINKED ISSUE #17395: Plugin custom resource types are not appearing in property resource menu
Godot 3.0.2

I have a plugin that registers a custom resource type, but I have no idea how to make a property `export`ing it. So I tried `export(Resource)` instead, which gave me a huuuuuge menu which is too big to fit on screen (it scrolls though).
But more importantly, my custom resource type **doesn't appear on that list**.

image

It does appear only if I click "New resource" in the inspector, which opens a different window.

Repro steps:
1) Have a plugin register a custom resource type
2) Have a script with a property `export(Resource)` on a node
3) Click on that property, see the huge menu and absence of custom type

Turns out https://github.com/godotengine/godot/pull/16995 would fix this

### PR DESCRIPTION
**Pull request by mrcdk**
Before this, the custom resources added via a plugin weren't being shown in the inspector dropdown with hint `PROPERTY_HINT_RESOURCE_TYPE`. This PR fixes this.

If you filter them with `hint_string` in the `_get_property_list()` function:

If you export a var with `export (Resource) var test`:

*Bugsquad edit:* fixes #17395.

### CODE REVIEW

**Comment by mrcdk** [comment]
This is probably get superseded by https://github.com/godotengine/godot/issues/6067#issuecomment-368918761 if what @willnationsdev says ends in a PR because if the custom type ends inside `ClassDB` we won't need to check for custom types anymore.

**Comment by willnationsdev** [comment]
Well, not so fast with the way this is going. We may be tracking the information elsewhere than the ClassDB.

File: editor/property_editor.cpp [hunk 1]
```diff
@@ -877,6 +882,7 @@ bool CustomPropertyEditor::edit(Object *p_owner, const String &p_name, Variant::
 			} else if (hint_text != "") {
 				int idx = 0;
 
+				const Vector<EditorData::CustomType> custom_resources = EditorNode::get_editor_data().get_custom_types()["Resource"];
```
Comment (Noshyaar) [inline editor/property_editor.cpp]: This line causes #18058
