### PR TITLE
[macOS] Remove unnecessary debug prints.

### LINKED ISSUE #74906: `godot --version` outputs extra cruft to stdout on MacOS
### Godot version

master (79454bfd3b21)

### System information

MacOS

### Issue description

On MacOS, `godot --version` outputs more than just the version number to stdout. This is a problem for tools that parse the Godot version number.

The responsible code is here:
https://github.com/godotengine/godot/blob/79454bfd3b218f5d2b2bb1da2013a3f359615d63/platform/macos/godot_main_macos.mm#L54-L69

I think this debug output should just go to stderr instead, i.e. `fprintf(stderr, ...)` instead of `printf(...)`.

### Steps to reproduce

```
$ godot --version
arguments
0: /Users/runner/work/_temp/godot_bin/godot.macos.editor.dev.x86_64
1: --version
Current path: /Users/runner/work/gdext/gdext/godot-core
4.1.dev.custom_build.79454bfd3
```

(I don't have a Mac, this output is synthesized.)

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/74906

### CODE REVIEW

File: platform/macos/godot_main_macos.mm [hunk 1]
```diff
@@ -53,19 +53,16 @@ int main(int argc, char **argv) {
...
 		}
-		printf("%i: %s\n", i, argv[i]);
 	}
 
 #ifdef DEBUG_ENABLED
 	// Lets report the path we made current after all that.
 	char cwd[4096];
 	getcwd(cwd, 4096);
-	printf("Current path: %s\n", cwd);
 #endif
```
Comment (ttencate) [inline platform/macos/godot_main_macos.mm:66]: This entire block can be removed now.

**Review by clayjohn — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
