### PR TITLE
Load assets before enabling editor plugins

### LINKED ISSUE #36713: Assets should be imported before running plugins and tool scripts
**Godot version:** 3.2 stable

**OS/device including version:** Ubuntu, but likely applies elsewhere.

**Issue description:**

If I delete `.import` and load the [2.5D demo projects](https://github.com/godotengine/godot-demo-projects/pull/315), I get this error:

    Unable to load addon script from path: 'res://addons/node25d/node25d_plugin.gd' There seems to be an error in the code, please check the syntax.

However, if I then restart Godot, it works fine.

I think the root of the problem is that the assets are currently imported after (or at the same time as) the plugins are ran. This causes the scripts to fail the first time, so it's really annoying.

To fix this issue, Godot should import all assets before attempting to run plugins or other scripts.

### PR DESCRIPTION
**Pull request by TechnoPorg**
Closes #36713 by moving the code for enabling plugins in `EditorNode` from `NOTIFICATION_READY` to after the first scan of the filesystem has been completed.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -970,6 +957,18 @@ void EditorNode::_sources_changed(bool p_exist) {
...
+		_initializing_addons = true;
+		Vector<String> addons;
+		if (ProjectSettings::get_singleton()->has_setting("editor_plugins/enabled")) {
+			addons = ProjectSettings::get_singleton()->get("editor_plugins/enabled");
+		}
+
+		for (int i = 0; i < addons.size(); i++) {
+			set_addon_plugin_enabled(addons[i], true);
+		}
+		_initializing_addons = false;
```
Comment (akien-mga) [inline editor/editor_node.cpp:971]: Won't this mean that it will re-initialize addons every time sources change, instead of only once at startup?

Comment (TechnoPorg) [reply editor/editor_node.cpp:971]: I don't think so, because this code will only run when `waiting_for_first_scan` is true.

Comment (akien-mga) [reply editor/editor_node.cpp:971]: Ah right, I misread as GH messes tab width for me between near and extended diff.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.4.

**Comment by akien-mga** [comment]
In the end I also reverted this in `master` since we did not find a fix yet for the regressions.

**Comment by TechnoPorg** [comment]
I'm really sorry about this. I started high school in the fall and the workload has been harder to adjust to than I expected that it would be. Also I had an issue to do with outdated graphics drivers that I only fixed yesterday, which was causing Godot to crash on launch. Neither of those excuses are preventing me from working on Godot now, though, so I will try and be more helpful in the future.

**Comment by akien-mga** [comment]
No worries, I wasn't trying to blame you or put pressure on you to fix the regression. But indeed when a known regression couldn't be fixed fast, it's usually best to rollback the change, and re-attempt it at a later time to solve both the original issue and the regressions.
