### PR TITLE
Verify that GLES3 cached shader load is successful

### LINKED ISSUE #77136: OpenGL backend (e.g. in Project Manager) shows blank screen / corrupted visuals due to invalid shader cache (e.g. after driver upgrade)
### Godot version

v4.1.dev.custom_build.1c7a62d2c

### System information

Windows 10, OpenGL API 3.3.0 NVIDIA 531.79 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce GTX 1070

### Issue description

I build Godot from the `master` branch nightly on Windows. For a while the Project Manager has been displaying corrupted visuals as below:

image

I went back through the commits from the past month and determined that it first appears when compiling PR #76092 with the commit ID of 1c7a62d2c0.

For now I can work around the issue by starting Godot with my project directly. In doing this I've not noticed any other issues beyond the Project Manager.

### Steps to reproduce

No, sample code. Just building Godot on Windows 10.

### Minimal reproduction project

No project needed.

### PR DESCRIPTION
**Pull request by ChibiDenDen**
Fixes #77136

Verified by corrupting the shader data using 
variant_bytes.ptrw()[5] = 0;
right before loading.
Shader cache loading fails but the shader compilation kicks in and everything still works

### CODE REVIEW

File: drivers/gles3/shader_gles3.cpp [hunk 1]
```diff
@@ -564,6 +564,13 @@ bool ShaderGLES3::_load_from_cache(Version *p_version) {
 			specialization.id = glCreateProgram();
 			glProgramBinary(specialization.id, variant_format, variant_bytes.ptr(), variant_bytes.size());
 
+			GLint link_status = 0;
+			glGetProgramiv(specialization.id, GL_LINK_STATUS, &link_status);
+			if (link_status != GL_TRUE) {
+				ERR_PRINT("Failed to load cached shader.");
```
Comment (akien-mga) [inline drivers/gles3/shader_gles3.cpp:570]: Since it's a "normal" error that will happen anytime users use a different GPU (integrated vs discrete), maybe this should only be a warning (or even a `print_verbose`?).
```suggestion
				WARN_PRINT("Couldn't load cached shader, recompiling.");
```

File: drivers/gles3/shader_gles3.cpp [hunk 2]
```diff
@@ -564,6 +564,13 @@ bool ShaderGLES3::_load_from_cache(Version *p_version) {
 			specialization.id = glCreateProgram();
 			glProgramBinary(specialization.id, variant_format, variant_bytes.ptr(), variant_bytes.size());
 
+			GLint link_status = 0;
+			glGetProgramiv(specialization.id, GL_LINK_STATUS, &link_status);
+			if (link_status != GL_TRUE) {
+				WARN_PRINT("Couldn't load cached shader, recompiling.");
```
Comment (akien-mga) [inline drivers/gles3/shader_gles3.cpp:570]: Just tested (with the previous commit where it was still an error), I'd make it a `WARN_PRINT_ONCE` actually, as it's a bit spammy otherwise:
```
$ DRI_PRIME=0 godot-git
Godot Engine v4.1.dev.custom_build.4917101ae - https://godotengine.org
ERROR: Failed to load cached shader.
   at: _load_from_cache (drivers/gles3/shader_gles3.cpp:570)
ERROR: Failed to load cached shader.
   at: _load_from_cache (drivers/gles3/shader_gles3.cpp:570)
OpenGL API 4.6 (Core Profile) Mesa 23.1.0 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 630 (KBL GT2)
 
ERROR: Failed to load cached shader.
   at: _load_from_cache (drivers/gles3/shader_gles3.cpp:570)
```

Comment (ChibiDenDen) [reply drivers/gles3/shader_gles3.cpp]: done :)

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]
Looks great! This is exactly what I had in mind. Tested locally by switching between GPUs and can confirm this fixes the issue

**Comment by akien-mga** [comment]
Thanks!
