### PR TITLE
Range: Fix cases where max was set to or below min value

### LINKED ISSUE #33907: "Cannot get ratio when minimum and maximum value are equal" error at run time
**Godot version:**
3.2 Beta 2 Mono
**OS/device including version:**
Manjaro/XPS 15 9560
**Issue description:**
When I run the project it throws the following error:
```
Godot_v3.2-beta2_mono_x11_64]$ Mono: Logfile is: /home/user/mono_logs/2019_11_25 19.51.24 (6867).txt
ERROR: get_as_ratio: Cannot get ratio when minimum and maximum value are equal.
   At: scene/gui/range.cpp:176.
```
**Steps to reproduce:**

1. Create a (mono) Project
2. Create a scene with Node2D root and add an icon (drag the Godot logo into the scene)
3. Attach a C# Script to the Node2D
4. Save; Build and run the project

**Minimal reproduction project:**
[project.zip](https://github.com/godotengine/godot/files/3890770/project.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
It will now raise an error whenever this happens so that we can fix
these situations. `max == min` is not allowed as it could lead to
divisions by zero in ratios, and `max < min` doesn't make much sense.

Fixes #33907.

### CODE REVIEW

File: scene/gui/range.cpp [hunk 1]
```diff
@@ -100,6 +100,7 @@ void Range::set_value(double p_val) {
 	shared->emit_value_changed();
 }
 void Range::set_min(double p_min) {
+	ERR_FAIL_COND_MSG(p_min >= shared->max, "Range cannot have min value higher or equal to its max value.");
```
Comment (akien-mga) [inline scene/gui/range.cpp]: This wasn't a very good idea as it puts too strict requirements on how to set min and max values. For example, since the default min and max are 0 and 100, this triggers an error:
```
set_min(256)
set_max(16384)
```
Since `min` will be higher than `max` temporarily. It can be worked around by setting max first, but it's not really intuitive. I'll relax the requirement as it's only a problem in `get_as_ratio`, which already has a check.

Comment (akien-mga) [reply scene/gui/range.cpp]: Fixed with 966c68bad.
