### PR TITLE
Android: Fix UnsupportedOperationException remove from non-ArrayList

### LINKED ISSUE #89696: godot 4.3 dev5 on android is crashing when i try to start it
### Tested versions

- reproducible in godot 4.3 dev5 on android

### System information

Android 14 One Ui 6.0

### Issue description

I try to open the godot 4.3 dev5 that I installed in my phone and it just crashes and dont open

### Steps to reproduce

the process i do is: i go to the godot org site and go to see the newest dev, i go install the apk file then i go and i install the apk on my phone, after this when i try to open it just crashes

### Minimal reproduction project (MRP)

its not an in editor bug

### PR DESCRIPTION
**Pull request by lyuma**
`getManifestPermissions` on some versions of android seem to return some other implementation of List<> which does not implement `remove()`

I workaround this crash by converting the generic List<> to an ArrayList<> which is known to support `remove()`

Tested crash fix on `Pixel Tablet` Android 14:
Godot v4.3.dev - Android - Vulkan (Mobile) - integrated Mali-G710 -  (8 Threads)

Fixes #89696

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java [hunk 1]
```diff
@@ -213,7 +213,7 @@ public static boolean requestManifestPermissions(Activity activity, @Nullable Se
 
 		List<String> manifestPermissions;
 		try {
-			manifestPermissions = getManifestPermissions(activity);
+			manifestPermissions = new ArrayList<String>(getManifestPermissions(activity));
```
Comment (Maran23) [inline platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java:216]: This is not the correct fix actually.
`getManifestPermissions` should not return `Collections.emptyList()` because it is immutable (and therefore, `remove` will throw an exception).

So in the `getManifestPermissions`, you should change the `return Collections.emptyList()` with `new ArrayList<>()`

Comment (lyuma) [reply platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java:216]: The empty list is not an issue here due to the check 
```
if (manifestPermissions.isEmpty()) {
			return true;
		}
```

I disagree about the fix being incorrect: wrapping Arrays.asList() in the implementation of getManifestPermissions instead of where it is called should behave equivalently.

I also do not understand the distinction between new ArrayList<>(Collections.emptyList()) which is what this code is effectively doing, and new ArrayList<>()

But anyway, changing the return type of getManifestPermissions to ArrayList, rather than abstract List could better illustrate that it is a mutable type. I would still be open to making this proposed change stylistically

Comment (Maran23) [reply platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java:216]: Yes, but the method is public. So other developers may call this method and do not expect it to be unmodifiable.

So we can decide between: 
1. `getManifestPermissions(..)` is always returning an unmodifiable list (like now) and we need to wrap it inside an `ArrayList` in order to remove permissions later
2. Make `getManifestPermissions` always return a mutable list

It probably does not matter which route we pick.
If it is the first, we should probably document this at `getManifestPermissions(..)`.
E.g. change `manifest permissions list` to `unmodifiable manifest permissions list`
and then we are good for the future :)

Comment (m4gr3d) [reply platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java:216]: @lyuma That's an interesting bug, thanks for finding it!

We're making modifications to the list returned by `getManifestPermissions(...)` within our own code, so I'd say let's be consistent and make `getManifestPermissions(...)` always return a mutable list as @Maran23 mentioned.

**Review by m4gr3d — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
