### PR TITLE
[3.x] AnimatedSprite Fix updating inspector when SpriteFrames is modified

### LINKED ISSUE #28658: Deleting a SpriteFrames Animation does not update owning AnimatedSprite's Animation property to an existing Animation
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Home
Version: 1803
Build: 17134.706

**Issue description:**
When I delete a SpriteFrame Animation, the Inspector shows that the Animation is still selected and testing through gdscript reveals that the owning AnimatedSprite's Animation property continues to hold the string name of the deleted Animation until it is manually changed. When changed, the name of the deleted Animation vanishes.

Expected: when I delete a SpriteFrame Animation, the program should update the Inspector to an existing Animation and set the owning AnimatedSprite's Animation property to that Animation's name.

**Steps to reproduce:**
1. Open Godot (see version at top)
2. Create a new project.
3. Create an AnimatedSprite node.
4. Select the AnimatedSprite node.
5. In the Inspector tab, go to Frames and create a new SpriteFrames asset.
6. If the SpriteFrames asset is not already selected, select the SpriteFrames asset in the Inspector.
7. If the Animation window is not already open, select the SpriteFrames option on the bottom of the Godot viewport.
8. Create 2 new animations. Note that when you create a new animation, the inspector will update to select that animation by name.
9. Delete the currently assigned animation. Note that when the currently assigned animation is deleted, *the inspector does not update the Animation property to an existing animation*.

**Additional Steps:**
10. Attach a new empty script to the AnimatedSprite node and insert the following code.
```gdscript
var animation_names = PoolStringArray() # holds string names of frame sequences
var animation_dictionary = Dictionary() # maps animation names to booleans

func _ready():
	animation_names = self.frames.get_animation_names() # get the current animation names
	for animation_name in animation_names: # for each name
		animation_dictionary[animation_name] = false # map false to it
	test()

func test(): # testing block to execute error method
	if is_locked():
		print("locked")
	else:
		print("unlocked")

func is_locked(): # method that will cause error
	return animation_dictionary[self.animation] # get current boolean for a given animation name
```
11. Save the script.
12. Run the scene.

**Result:** the debugger will inform you that you have provided an invalid index to the dictionary, whose string name matches the name of the Animation you deleted.

**Cause:** when you create a new Animation, it is automatically switched to in the Inspector for the AnimationSprite node; however, if you delete that same Animation, the AnimatedSprite node continues to hold the string name of the deleted Animation until you manually select a new one in the Inspector.

**Minimal reproduction project:**
[AnimatedSpriteTest.zip](https://github.com/godotengine/godot/files/3143250/AnimatedSpriteTest.zip)

### LINKED ISSUE #40263: Removed animation still used in Animated Sprite object. (set_animation: There is no animation with name 'New Anim'.)
(hello)

**Godot version:**
3.2.2.stable.official

**OS/device including version:**
Ubuntu bionic (probably not related to device...)

**Steps to reproduce:**
The issue is related to the IDE.

I followed the tutorial  [Your first game](https://docs.godotengine.org/fr/stable/getting_started/step_by_step/your_first_game.html), while adding an animation, i added an extra one that i removed (trash icon in left panel "Animation :" of animated sprite) and got the error :
```
set_animation: There is no animation with name 'New Anim'.
```

(To workaround the issue i edited the scene file in Vim and guess the animation reference was wrong.)

At the moment i added the animation 'New Anim' (not nammed), it replaced the existing setting (in right pane : Animated Sprite > Animation  e.g. 'walking').
And when i removed the animation, the setting stay at 'New Anim'.

For a more coherent gui (given a dialog already exists), the setting (if used) shall be replaced by the next/previous existing one; or at least the setting shall be highlighted to see the error.

### LINKED ISSUE #44438: The editor does not update when adding frames to an AnimatedSprite using SpriteFrames editor
**Godot version:**

3.2.4 beta 4 mono

**OS/device including version:**

win10 64

**Issue description:**

In an animated sprite node with the "Playing" property activated, it works correctly with two frames, the "Frame" property indicates each frame correctly, however, if you add one more frame (it would be number 2), then the "Frame" property does not show this frame and keep oscillating between frame number 0 and frame number 1.

In the gif, notice that when I add frame number 2, the "Frame" property doesn't show it and you can only see 0 and 1.
gif

**Steps to reproduce:**
Add an "AnimatedSprite" node
Add two frames
activate the "Playing" property
notice the "Frame" property
Add a third frame
Note that the "Frame" property does not display frame number 2 even though the animation looks correct.

**Minimal reproduction project:**

### LINKED ISSUE #46741: Opening/Closing scenes with Animated Sprite causes the SpriteFrames editor panel to display wrong Animations and Animation Frames
**Godot version:**

3.2.3 stable (mono)

**OS/device including version:**

Windows 7 x64

**Issue description:**

Viewing an Animated Sprite's SpriteFrames, closing a scene and re-opening another scene with an Animated Sprite shows the incorrect scene's animations in the SpriteFrames' Animation and Animation Frames panel, and causes loss of functionality until corrected.

**Steps to reproduce:**
**Prep:**
1. Create a Node2D Scene, attach an AnimatedSprite as child. Create SpriteFrames, and add a new animation, call it something distinguishable, ie. "ANIMATION_A". _Optional, but helps to demo: add any random graphic to this animation._ Save this scene as "abc123". Make sure the AnimatedSprite node is selected.
2. Repeat the above step, but use "ANIMATION_B" instead of "ANIMATION_A", and add a different graphic (or use none). Save this scene as "def234". Make sure the AnimatedSprite node is selected.
3. Your scene tabs should be as follows: [abc123, def234 (current)], both with their AnimatedSprite node selected to make the SpriteFrame Animation/Animation Frames panel in the editor visible.

**Reproduction**
Close def234, then close abc123. Re-open def234, then select the AnimatedSprite node. The displayed animation in the Animation and AnimationFrames panel will be of abc123, not def234. Also, all buttons in the Animation and Animation Frame panels do not respond, except for "New Animation" and "Add Frames from a Sprite Sheet" respectively.

**Current workarounds**
There are two ways I've found to "correct" this behavior in the editor. One such way is to open abc123 again, select its AnimatedSprite node, then switching back to def234. Another is to use the aforementioned buttons and either create a new animation, or the spritesheet button and add a frame to the animation (no frame is actually added?). The editor then correctly displays the correct animations.

https://user-images.githubusercontent.com/67756278/110222308-22d47b00-7e86-11eb-99a6-1f7875e950b1.mp4

### PR DESCRIPTION
**Pull request by kleonc**
(needs a separate `master` version due to #45879; for the same reason some issues fixed here might already be non-existent in the `master`; haven't checked none of these)

Makes creating / renaming / deleting animations in the `SpriteFramesEditorPlugin` properly update properties of the `AnimatedSprite` in the inspector (mainly options in the animation dropdown). Removing current animation of the `AnimatedSprite` will make the first (after removal) animation left be selected as the new current animation (if no animation would be left then nothing will be done from the inspector point of view). 

Reverts #27254 but keeps #26381 being fixed.
Fixes #44438.
Fixes #46741.
Fixes #28658, fixes #40263 (these look like duplicates).

Removes unused `SpriteFrames::_get_animation_list()` method.

~~After reverting #27254 newly created animation is no longer automatically set as the current animation of the `AnimatedSprite`/`AnimatedSprite3D` being edited. Should the current behavior be preserved (assigning it automatically)?~~
I've changed it so currently the newly created animation is automatically set as the current animation of the anim sprite being edited (same as before), and the same for all other anim sprites having currently invalid animation set (same as before). But valid animations of other anim sprites will no longer be automatically changed (as they used to be).

### CODE REVIEW

**Comment by KoBeWi** [comment]
I checked the issues. One is valid on both branches and one only in 3.x

> newly created animation is no longer automatically set as the current animation of the AnimatedSprite/AnimatedSprite3D being edited.

I think the reason for this was that when you create new animation and put some sprites, you can preview it immediately.

**Comment by kleonc** [comment]
> I checked the issues. One is valid on both branches and one only in 3.x

Hmm, I think I've listed 3 issues (4 if counting the duplicated one): 

> Reverts #27254 but keeps #26381 being fixed.
> Fixes #44438.
> Fixes #46741.
> Fixes #28658, fixes #40263 (these look like duplicates).

so it's kinda hard to tell what have you found out. :smile: So please try being more specific. Also thanks for checking it out!
Oh, and if by any chance you'd like to do `master` version feel free to do so (or anyone else).
 
---


> > newly created animation is no longer automatically set as the current animation of the AnimatedSprite/AnimatedSprite3D being edited.
> 
> I think the reason for this was that when you create new animation and put some sprites, you can preview it immediately.


For me it looks like it was just an unintended side effect of #27254. But yeah, I can see how it might be a desired behavior for some people and that's why I've asked which behavior is the desired one / should current behavior be preserved.

**Comment by KoBeWi** [comment]
> so it's kinda hard to tell what have you found out. 

I meant #28658 and #46741 (the other ones are closed now).

File: scene/2d/animated_sprite.cpp [hunk 1]
```diff
@@ -144,20 +144,24 @@ void SpriteFrames::clear(const StringName &p_anim) {
 void SpriteFrames::clear_all() {
 	animations.clear();
 	add_animation("default");
+	// emit_changed(); will be triggered by the previous line, no need to do it twice
```
Comment (akien-mga) [inline scene/2d/animated_sprite.cpp:147]: Makes it look less like dead code to remove.
```suggestion
	add_animation("default"); // Also emits changed.
```

**Comment by kleonc** [comment]
@akien-mga Rebased, applied suggestion. Added some more comments and changed this (part of the PR description):

> ~After reverting #27254 newly created animation is no longer automatically set as the current animation of the `AnimatedSprite`/`AnimatedSprite3D` being edited. Should the current behavior be preserved (assigning it automatically)?~
> I've changed it so currently the newly created animation is automatically set as the current animation of the anim sprite being edited (same as before), and the same for all other anim sprites having currently invalid animation set (same as before). But valid animations of other anim sprites will no longer be automatically changed (as they used to be).

**Review by akien-mga — APPROVED** [review]
Should be good to merge after 3.5 is released.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.
