### PR TITLE
Fix native FileDialogs popping up when `use_native_dialog` is modified

### LINKED ISSUE #113745: FileDialog appears when `use_native_dialog` is assigned `true`
### Tested versions

- Reproducible in master [dec5a373d9] on KDE Plasma

### System information

Godot v4.6.dev (dec5a373d) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (nvidia; 580.105.08) - 12th Gen Intel(R) Core(TM) i9-12900K (24 threads) - 46.80 GiB memory

### Issue description

Whenever the `use_native_dialog` is assigned `true` the dialog is shown.

### Steps to reproduce

Create a script:
```gdscript
extends Control


func _ready() -> void:
	var fd := FileDialog.new()
	fd.hide()
	add_child(fd)
	fd.use_native_dialog = true
```
It doesn't appear when the last line is commented out.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by sockeye-d**
As the title says, this fixes a regression where native FileDialogs would popup any time `use_native_dialog` changes by adding back in a check erroneously removed in #111212.

Fixes #113745

### CODE REVIEW

File: scene/gui/file_dialog.cpp [hunk 1]
```diff
@@ -2210,7 +2210,7 @@ void FileDialog::set_use_native_dialog(bool p_native) {
 #endif
 
 	// Replace the built-in dialog with the native one if it's currently visible.
-	if (is_inside_tree() && _should_use_native_popup()) {
+	if (is_inside_tree() && _should_use_native_popup() && is_visible()) {
```
Comment (AThousandShips) [inline scene/gui/file_dialog.cpp]:
```suggestion
	if (is_inside_tree() && is_visible() && _should_use_native_popup()) {
```
Cheaper check first

Comment (sockeye-d) [reply scene/gui/file_dialog.cpp]: Fixed

**Review by AThousandShips — APPROVED** [review]
Simply restores a check, LGTM, don't think it should be moved into the helper function

**Review by KoBeWi — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
