### PR TITLE
Fix signal duplication bug when duplicating node with instanced children

### LINKED ISSUE #39119: node.duplicate(7) fails to duplicate signals for specific ownership configuration
There were some issues with duplicating signals before:
https://github.com/godotengine/godot/issues/1888
https://github.com/godotengine/godot/issues/5405

**Godot version:** 3.2.1.stable

**OS/device including version:** Arch Linux

**Issue description:**
Duplicated node loses signal-connections of children. This happens only in the case that the duplicated node is not a scene and it has a descendant that is a scene with descendants that have signal-connections.

**Steps to reproduce:**
Open the minimal reproduction project. Click on button "node.duplicate(7)", then click on button "workaround duplicate(7)", then click on button "node.duplicate(15)". Each click duplicates the node `$DuplicateMe` in a different way and adds it to the main scene. The duplicated node contains a descendant whose "ready" signal is connected to a printout. The first button with the code `node.duplicate(7)` misses the printout. The output is:

```

--- Debugging process started ---
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)

received ready signal!

┌─ $DuplicateMe.duplicate(7) ────────────
│ Original Scene2.owner: SceneMain
│ Original Scene2/Receive.owner: Scene2
│ Duplicate Scene2.owner: Null
│ Duplicate Scene2/Receive.owner: Null
│ incoming connections: []
└─────────────────────────────────────
┌─ workaround ────────────
│ Original Scene2.owner: DuplicateMe
│ Original Scene2/Receive.owner: DuplicateMe
│ Duplicate Scene2.owner: Null
│ Duplicate Scene2/Receive.owner: Null
│ incoming connections: [{method_name:_on_IDoEmit_ready, signal_name:ready, source:[Node:1340]}]
└─────────────────────────────────────
received ready signal!

┌─ $DuplicateMe.duplicate(15) ────────────
│ Original Scene2.owner: SceneMain
│ Original Scene2/Receive.owner: Scene2
│ Duplicate Scene2.owner: Null
│ Duplicate Scene2/Receive.owner: Scene2
│ incoming connections: [{method_name:_on_IDoEmit_ready, signal_name:ready, source:[Node:1403]}]
└─────────────────────────────────────
received ready signal!
```

The workaround precedes the `duplicate(7)` with a recursive own on the duplicated node `$DuplicateMe`:

```gd
  var nodes = $DuplicateMe.get_children()
  while len(nodes) > 0:
    var node = nodes.pop_front()
    node.owner = $DuplicateMe
    nodes += node.get_children()
  var duplicate = $DuplicateMe.duplicate(7)
```

I didn't compile godot yet, but a possible solution might add some mechanism to `Node::_duplicate_signals(const Node *p_original, Node *p_copy)` that changes p_original to any encountered scene-instance with the same owner as the node the duplicate call was made on before it calls `get_child(i)->_duplicate_signals(p_original, p_copy);` or something similar.

**Minimal reproduction project:**
[Signal Duplication.zip](https://github.com/godotengine/godot/files/4695183/Signal.Duplication.zip)

### PR DESCRIPTION
**Pull request by mrushyendra**
`node::duplicate()` recreates all descendants of `node`. However, it does not necessarily duplicate all signals between members of the subtree rooted at that `node`, even if the `DUPLICATE_SIGNALS` flag is passed.

The issue occurs due to the error check in `duplicate_signals()`, because it only checks for common ownership 1 or 2 levels up, which need not always be the case. To fix, for any given node, the code now checks if it belongs to the subtree rooted at the `node` on which `duplicate()` is initially called. This more closely matches how `duplicate()` itself works.

If this seems alright, I can make a separate PR for 3.2.

Closes #39119

### CODE REVIEW

File: scene/main/node.cpp [hunk 1]
```diff
@@ -2238,46 +2238,53 @@ void Node::_duplicate_and_reown(Node *p_new_parent, const Map<Node *, Node *> &p
...
 
-			// Attempt to find a path to the duplicate target, if it seems it's not part
-			// of the duplicated and not yet parented hierarchy then at least try to connect
-			// to the same target as the original
+				Node *copytarget = target;
 
-			if (p_copy->has_node(ptarget)) {
-				copytarget = p_copy->get_node(ptarget);
-			}
+				// Atempt to find a path to the duplicate target, if it seems it's not part
```
Comment (akien-mga) [inline scene/main/node.cpp:2268]: You added a typo :) "Attempt" was correct.

Comment (mrushyendra) [reply scene/main/node.cpp]: Done, thanks!

**Comment by akien-mga** [comment]
Thanks!
