### PR TITLE
Fix fullscreen on X11.

### LINKED ISSUE #54065: Fullscreen not working in Godot 4 when passed to DisplayServer create function
### Godot version

4.0.dev

### System information

Issue verified on:
- Manjaro Linux 5.13, Ryzen 5 3600, Radeon RX 580 with Vulkan 1.2
- Windows 11, Intel i5-8250U, Nvidia MX 110 also with Vulkan 1.2

### Issue description

I am trying to port my game from Godot 3 to Godot 4. Somehow, even fullscreen isn't working, even though it is turned on in the settings:
image
image
I know the resolution is 1024x600, the Godot default, but on Godot 3 that isn't a problem and the window simply gets scaled to completely fill my 1080p screen. From an answer I received on reddit, from a user also having this issue, it seems to happen regardless of GPU brand and regardless of how Godot 4 is "acquired" (manual build or download from the pre-alpha releases) and of whether the project is run from the editor or as an executable.

### Steps to reproduce

1. Make a new Godot 4 project
2. Setup any kind of sample scene
3. Check "Fullscreen" in the project's Window settings

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by MatthewZelriche**
Should fix #54065

It appears to be the case that if an attempt is made to use the `_NET_WM_STATE_FULLSCREEN` EWMH hint on a window that is not mapped, applying the hint will silently fail. Whether this is a EWMH specification requirement, or it's left up to the window manager's discretion, I am not sure. Regardless, `DisplayServerX11::_create_window` attempts to do just this, and this leaves Godot in an internal state where it believes the window is in fullscreen, but in reality it is not. What this pull request does is whenever a window receives a `MapNotify` request, we test to see if Godot believes the window is fullscreen, and also test to see if `_NET_WM_STATE_FULLSCREEN` genuinely was set. If there is a discrepancy, we re-attempt setting the window to fullscreen now that we know for sure that the window has been mapped. 

This PR was tested on i3wm, as its the only window manager i have installed. It's probably a good idea to test it on other window managers.

### CODE REVIEW

File: platform/linuxbsd/display_server_x11.cpp [hunk 1]
```diff
@@ -1865,6 +1865,16 @@ bool DisplayServerX11::_window_fullscreen_check(WindowID p_window) const {
 	return retval;
 }
 
+void DisplayServerX11::_validate_fullscreen_on_map(WindowID p_window) {
+	const WindowData &wd = windows[p_window];
+	if (wd.fullscreen && !_window_fullscreen_check(p_window)) {
+		// Undo the failed fullscreen mode.
+		window_set_mode(WINDOW_MODE_WINDOWED, p_window);
+		// Try again now that we are mapped.
+		window_set_mode(WINDOW_MODE_FULLSCREEN, p_window);
```
Comment (bruvzg) [inline platform/linuxbsd/display_server_x11.cpp:1874]: Not sure about toggling it back and forth, maybe it's better to directly set the flag to avoid any intermediate window size changes, like (not tested):
```c++
_set_wm_fullscreen(p_window, true);
```

**Review by bruvzg — COMMENTED** [review]
Seems logical, the same is might be relevant for initial maximized and minimized modes and some of the window flags, if they are set before window is mapped.

File: platform/linuxbsd/display_server_x11.cpp (hunk 1 above)
Comment (MatthewZelriche) [reply platform/linuxbsd/display_server_x11.cpp]: I have amended the PR with the requested changes. Testing suggests the change works fine. I also looked into your suggestion that `WINDOW_MODE_MINIMIZED` and `WINDOW_MODE_MAXIMIZED` will be affected by this bug; I can confirm that this is the case. Should this PR be amended to deal with those cases as well?

**Comment by MatthewZelriche** [comment]
Resolved a merge conflict

File: platform/linuxbsd/display_server_x11.cpp (hunk 1 above)
Comment (akien-mga) [reply platform/linuxbsd/display_server_x11.cpp]: Let's merge this one as is since it's ready (and I'm about to build 4.0 alpha 15), but feel free to open a PR with the other fixes.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Tested on KWin/X11 and it works as expected :+1:
