### PR TITLE
Fix DistractionFreeMode and BottomPanel

### LINKED ISSUE #113314: Distraction free mode makes the editor blank
### Tested versions

v4.6.dev.custom_build [7ed0b6167]

### System information

Arch Linux

### Issue description

Image

This is not a bug technically, because an empty interface indeed presents no distractions.

### Steps to reproduce

- Open any bottom panel.
- Click "Expand Bottom Panel".
- Click "Distraction Free Mode".

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #113520: In distraction free mode, the output panel does not appear when running the game
### Tested versions

v4.6.dev5.official [f5918a9d3]

### System information

linux

### Issue description

Today I switched to dev5, and since I frequently use the console while debugging code and the side panels get in the way, I use distraction free mode, which expands the script editor while still showing the console. In dev4 and earlier it always worked this way, but in dev5 the output panel simply isn’t there. I believe this is a bug because I couldn’t find any flags or changes related to it. Looking through the changelog, there are modifications that could have caused this issue, but nothing that suggests it was an intentional change.

### Steps to reproduce

https://github.com/user-attachments/assets/f8d61398-59be-4585-b37c-d11e79c5c1a6

### Minimal reproduction project (MRP)

This is GUI

### PR DESCRIPTION
**Pull request by arkology**
- Fix https://github.com/godotengine/godot/issues/113314
- Fix https://github.com/godotengine/godot/issues/113520

Also fix DistractionFreeMode button visibility between scene tabs and bottom panel.

https://github.com/user-attachments/assets/bdba7b62-8b69-42dd-b1cd-02a05cbad1be

### CODE REVIEW

File: editor/docks/editor_dock_manager.cpp [hunk 1]
```diff
@@ -913,6 +913,9 @@ void EditorDockManager::set_docks_visible(bool p_show) {
 	}
 	docks_visible = p_show;
 	for (int i = 0; i < DockConstants::DOCK_SLOT_MAX; i++) {
+		if (i == DockConstants::DOCK_SLOT_BOTTOM) {
+			continue;
+		}
```
Comment (KoBeWi) [inline editor/docks/editor_dock_manager.cpp]:
```suggestion
for (int i = 0; i < DockConstants::DOCK_SLOT_BOTTOM; i++) {
```

Comment (AThousandShips) [reply editor/docks/editor_dock_manager.cpp]: This would assume the bottom slot is always the last, and that only should be ignored, might work but fragile (also indentation is wrong)

Comment (KoBeWi) [reply editor/docks/editor_dock_manager.cpp]: Well, it's not like we are going to add more side docks and a similar loop is already used in a few places.

**Review by KoBeWi — DISMISSED** [review]

File: editor/docks/editor_dock_manager.cpp (hunk 1 above)
Comment (arkology) [reply editor/docks/editor_dock_manager.cpp]: Right now, the code obviously makes it clear that we are processing _all_ options _except_ DOCK_SLOT_BOTTOM (without having to look at the DockConstants values, which is not very convenient to do when viewing the code on Github, for example). Yes, the current variant may be not optimal in terms of performance, but it's not a hot path either.

Comment (AThousandShips) [reply editor/docks/editor_dock_manager.cpp]: If it's an established pattern then I think it's fine, just a note of caution

File: editor/gui/editor_bottom_panel.cpp [hunk 2]
```diff
@@ -115,7 +115,7 @@ void EditorBottomPanel::_repaint() {
 	pin_button->set_visible(!panel_collapsed);
 	expand_button->set_visible(!panel_collapsed);
 	if (expand_button->is_pressed()) {
-		EditorNode::get_top_split()->set_visible(panel_collapsed);
+		_expand_button_toggled(!panel_collapsed);
```
Comment (KoBeWi) [inline editor/gui/editor_bottom_panel.cpp:118]: `_repaint()` is a generic update method called when tabs are changed etc. `_expand_button_toggled()` does too much unnecessary stuff to be called every time, e.g. it will call `_theme_changed()` which is already done below.

Comment (arkology) [reply editor/gui/editor_bottom_panel.cpp:118]: There is a situation: we expand bottom panel, then enter distraction free mode, then hide selected tab by clicking on it (i.e. tab has changed). Right now in this situation distraction free mode button will stay in bottom panel, which is wrong, it should be moved to scenes tab bar again.
I'll think how it could be done differently. I suppose it will stay inside `_repaint()`, but with some additional checks to prevent excessive calls.

Comment (arkology) [reply editor/gui/editor_bottom_panel.cpp:118]: Actually there is no need to prevent calls, because these lines exist:
```cpp
	if (!panel_collapsed && (previous_tab != -1)) {
		return;
	}
```
And `_expand_button_toggled()` calls happen only when opening/closing tab. So it is called in right place.

https://github.com/user-attachments/assets/cf41a11d-efb2-41fe-b4ca-bafeeaf8bd2d

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by SeleDreams** [comment]
I was having this issue when trying to maximize my editor plugin. nice to see it got fixed. Do you know around when it should be integrated in a new update ? 4.6 dev 6 / beta ?
