### PR TITLE
Fix canvas background mode not clearing correctly in Compatibility renderer

### LINKED ISSUE #100203: Glow effect on transparent background isn't cleared in compatibility mode
### Tested versions

Reproducible in
- v4.3.dev4.official [df78c0636]
- v4.3.stable.official [77dcf97d8]
- v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 30.0.13044.14002) - AMD Ryzen 5 5500U with Radeon Graphics (12 Threads)

### Issue description

I tried to create a simple glow effect on some particles, and noticed that the particles started to leave a trail behind them.

How it looks in the editor:
Image

How it looks in play mode:
Image

### Steps to reproduce

- Create a project in Compatibility mode
- Create a 2D scene with a WorldEnvironment and a CPUParticles2D node
- Set the WorldEnvironments background mode to Canvas and enable Glow
- Set the CPUParticles RAW color to (10, 10, 10, 1)
- Enable Rendering > Viewport > Transparent Background
- Enable Rendering > Viewport > HDR 2D

### Minimal reproduction project (MRP)

https://github.com/Rocka06/Godot-Background_MRP

### PR DESCRIPTION
**Pull request by Namey5**
There was an inconsistency in framebuffer clear behaviour between Compatibility and the other renderers when using the 'Canvas' background mode.

More specifically, when using an intermediate framebuffer in the GLES3 backend (eg. when `Glow` post-processing effect was enabled), the framebuffer was not being cleared before having the current `rt` copied over, resulting in a feedback loop equivalent to setting `Environment::background` to `RS::ENV_BG_KEEP`.

In the other backends this doesn't appear to be the case, so I have modified the GLES3 backend to clear the framebuffer before copying when `Environment::background` is set to `RS::ENV_BG_CANVAS`.

| Background Mode | Compatibility | Compatibility (w/ Glow) | Forward+ |
|--------|--------|--------|--------|
| Clear Color | compat_color | compat_glow_color | forward_color |
| Sky | compat_sky | compat_glow_sky | forward_sky |
| Canvas | compat_canvas | compat_glow_canvas | forward_canvas |
| Keep | compat_keep | compat_glow_keep | forward_keep |
| Camera Feed | compat_feed | compat_glow_feed | forward_feed |

[Looks like the other backends have had issues with this in the past too](https://github.com/godotengine/godot/pull/68805), but would certainly like some extra testing on this as I am not too familiar with this setup.

Fixes https://github.com/godotengine/godot/issues/100203

### CODE REVIEW

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -2380,6 +2380,7 @@ void RasterizerSceneGLES3::render_scene(const Ref<RenderSceneBuffers> &p_render_
 	bool draw_sky = false;
 	bool draw_sky_fog_only = false;
 	bool keep_color = false;
+	bool draw_canvas = false;
```
Comment (Namey5) [inline drivers/gles3/rasterizer_scene_gles3.cpp:2383]: Would it make sense to instead have a more generic flag for `copy_framebuffer` giving the combinations of:
```
bg_mode: keep
 - keep_color: true
 - copy_framebuffer: false

bg_mode: canvas
 - keep_color: false
 - copy_framebuffer: true

bg_mode: camera_feed
 - keep_color: true
 - copy_framebuffer: true
```

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 2]
```diff
@@ -2540,10 +2542,11 @@ void RasterizerSceneGLES3::render_scene(const Ref<RenderSceneBuffers> &p_render_
 		glClear(GL_DEPTH_BUFFER_BIT);
 	}
 
-	if (!keep_color && !draw_feed) {
+	if (!keep_color) {
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_scene_gles3.cpp:2545]: This clear should happen _only_ when using an intermediate framebuffer. By default 2D and 3D rendering use the same texture. Therefore, this change will clear out the results of 2D rendering before 3D rendering happens. 

This PR works when using glow because the bound framebuffer uses a separate texture.

Comment (Namey5) [reply drivers/gles3/rasterizer_scene_gles3.cpp:2545]: Ah ok, so something more along the lines of:
```suggestion
	if (fbo != rt->fbo) {
		if (!keep_color) {
			clear_color.a = render_data.transparent_bg ? 0.0f : 1.0f;
			glClearBufferfv(GL_COLOR, 0, clear_color.components);
		}
		if (copy_framebuffer) {
			// Need to copy our current contents to our intermediate/MSAA buffer
			GLES3::CopyEffects *copy_effects = GLES3::CopyEffects::get_singleton();
			...
		}
	}
```

Comment (Namey5) [reply drivers/gles3/rasterizer_scene_gles3.cpp]: Nice catch - updated.

I've also added a comparison matrix to the original PR description to show the different paths - it looks like `ENV_BG_KEEP` clears the 2D framebuffer in Forward+, do we know what the intended behaviour should be there?

**Comment by Rocka06** [comment]
I've found an issue(#98958) similar to the one I reported(#100203), so I tested that MRP with the changes of this PR, and it fixed that as well.

**Review by clayjohn — APPROVED** [review]
Looks good to me now!

**Comment by akien-mga** [comment]
Thanks!
