### PR TITLE
Fix code formatting issues and VS compilation

### LINKED ISSUE #33356: vulkan - 4.0 dev - cant compile in windows VS 2017, previous version did compile
**Godot version:**
vulkan branch 8b1d5dd from  20191105

**OS/device including version:**
Windows 10 64 bits
VS 2017
python 3.8.0
scons 3.1.1
Intel i7 8750H 16G RAM
Nvidia GTX 1060

**Issue description:**
vulkan branch compiled on windows with previous commit, this one fails almost at the end in math_funcs.h and rasterizer.h

**Steps to reproduce:**
clone vulkan branch from git and compile:

```
git clone https://github.com/godotengine/godot/ --branch vulkan
cd godot
scons platform=windows -j 10 tools=yes target=release_debug
```

Error at the end:

```
[Initial build] Compiling ==> servers\visual\rasterizer_rd\shader_rd.cpp
shader_rd.cpp
servers\visual\rasterizer_rd\rasterizer_scene_forward_rd.cpp(1559): error C2666: 'Math::pow': sobrecargas 2 tienen conversiones similares
[Initial build] C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\core/math/math_funcs.h(101): note: puede ser 'float Math::pow(float,float)'
C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\core/math/math_funcs.h(100): note: o       'double Math::pow(double,double)'Compiling ==> servers\audio\audio_driver_dummy.cpp

servers\visual\rasterizer_rd\rasterizer_scene_forward_rd.cpp(1559): note: al hacer coincidir la lista de argumentos '(float, double)'
audio_driver_dummy.cpp
scons: *** [servers\visual\rasterizer_rd\rasterizer_scene_forward_rd.windows.opt.tools.64.obj] Error 2
C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\servers/visual/rasterizer.h(108): warning C4099: 'RasterizerScene::InstanceBase': nombre de tipo visto anteriormente usando 'struct' ahora se ve usando 'class'
C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\servers/visual/rasterizer.h(98): note: vea la declaración de 'RasterizerScene::InstanceBase'
C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\servers/visual/rasterizer.h(108): warning C4099: 'RasterizerScene::InstanceBase': nombre de tipo visto anteriormente usando 'struct' ahora se ve usando 'class'
C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\servers/visual/rasterizer.h(98): note: vea la declaración de 'RasterizerScene::InstanceBase'
servers\visual\rasterizer_rd\rasterizer_storage_rd.cpp(2619): warning C4804: '>=': uso no seguro del tipo 'bool' en la operación
servers\visual\rasterizer_rd\rasterizer_storage_rd.cpp(2640): warning C4804: '>=': uso no seguro del tipo 'bool' en la operación
servers\visual\rasterizer_rd\rasterizer_storage_rd.cpp(2727): warning C4804: '>=': uso no seguro del tipo 'bool' en la operación
servers\visual\rasterizer_rd\rasterizer_storage_rd.cpp(2750): warning C4804: '>=': uso no seguro del tipo 'bool' en la operación
C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\servers/visual/rasterizer.h(108): warning C4099: 'RasterizerScene::InstanceBase': nombre de tipo visto anteriormente usando 'struct' ahora se ve usando 'class'
C:\Users\Sistemas\Documents\Godot\build\vulkan\godot\servers/visual/rasterizer.h(98): note: vea la declaración de 'RasterizerScene::InstanceBase'
scons: building terminated because of errors.
```

### PR DESCRIPTION
**Pull request by akien-mga**
Also temporarily disable multistage build so that we get a full build
even when there are style issues on Vulkan.

Thanks @javawag for documenting the fix for #33356.

Fixes #33356.

### CODE REVIEW

File: servers/visual/rasterizer_rd/rasterizer_scene_forward_rd.cpp [hunk 1]
```diff
@@ -1556,7 +1556,7 @@ void RasterizerSceneForwardRD::_setup_gi_probes(RID *p_gi_probe_probe_cull_resul
 		gi_probe_ubo.texture_slot = gi_probe_instance_get_slot(rpi);
 		gi_probe_ubo.anisotropy_strength = storage->gi_probe_get_anisotropy_strength(base_probe);
 		gi_probe_ubo.ao = storage->gi_probe_get_ao(base_probe);
-		gi_probe_ubo.ao_size = Math::pow(storage->gi_probe_get_ao_size(base_probe),4.0);
+		gi_probe_ubo.ao_size = Math::pow(storage->gi_probe_get_ao_size(base_probe), 4.0f);
```
Comment (akien-mga) [inline servers/visual/rasterizer_rd/rasterizer_scene_forward_rd.cpp]: For the record, this is the VS compilation bugfix.

File: servers/visual/rasterizer_rd/shaders/scene_forward.glsl [hunk 2]
```diff
@@ -757,45 +737,44 @@ void light_process_omni(uint idx, vec3 vertex, vec3 eye_vec, vec3 normal, vec3 a
...
-		clearcoat, clearcoat_gloss,
+			clearcoat, clearcoat_gloss,
 #endif
 #ifdef LIGHT_ANISOTROPY_USED
-		binormal, tangent, anisotropy,
+			binormal, tangent, anisotropy,
 #endif
 #ifdef USE_SHADOW_TO_OPACITY
-		alpha
+			alpha,
```
Comment (akien-mga) [inline servers/visual/rasterizer_rd/shaders/scene_forward.glsl]: The missing comma was a bug here, toggling `USE_SHADOW_TO_OPACITY` would likely cause shader compilation failure.

File: servers/visual/rasterizer_rd/shaders/scene_forward.glsl [hunk 3]
```diff
@@ -757,45 +737,44 @@ void light_process_omni(uint idx, vec3 vertex, vec3 eye_vec, vec3 normal, vec3 a
...
-	float clearcoat, float clearcoat_gloss,
+		float clearcoat, float clearcoat_gloss,
 #endif
 #ifdef LIGHT_ANISOTROPY_USED
-	vec3 binormal, vec3 tangent, float anisotropy,
+		vec3 binormal, vec3 tangent, float anisotropy,
 #endif
 #ifdef USE_SHADOW_TO_OPACITY
-	inout float alpha
+		inout float alpha,
```
Comment (akien-mga) [inline servers/visual/rasterizer_rd/shaders/scene_forward.glsl]: Same here, bugfix.

File: servers/visual/rasterizer_rd/shaders/scene_forward.glsl [hunk 4]
```diff
@@ -1544,120 +1494,114 @@ FRAGMENT_SHADER_CODE
...
-				clearcoat, clearcoat_gloss,
+					clearcoat, clearcoat_gloss,
 #endif
 #ifdef LIGHT_ANISOTROPY_USED
-				binormal, tangent, anisotropy,
+					binormal, tangent, anisotropy,
 #endif
 #ifdef USE_SHADOW_TO_OPACITY
-				alpha
+					alpha,
```
Comment (akien-mga) [inline servers/visual/rasterizer_rd/shaders/scene_forward.glsl]: Bugfix.
