### PR TITLE
Fixed Make 3D viewport locked nodes unselectable as in 2D viewport

### LINKED ISSUE #29903: Make 3D viewport locked nodes unselectable as in 2D viewport
**Godot version:**
3.2 master (43a9b8c76)

**OS/device including version:**
Any

**Issue description:**
Follow-up to discussion in #26944.

> So there has been some confusion here as the feature partly exists already for children of a locked nodes, which are not selectable.
>
> What should be changed is to make things behave like in 2D, where locking also makes the locked node unselectable. The code should be kept as similar as possible as the features and behaviour should be the same for the 2D and 3D viewports. The tooltips in 2D and 3D should be adjusted to mention that they lock the position and prevent selection in the viewport.
> 
> In a later PR, it could be interesting to implement a picking mode for 2D and 3D which bypasses the selection restriction, so e.g. Ctrl+Click would let you select locked nodes (to ease finding them in the scene tree/viewing their properties/unlocking them).

**Steps to reproduce:**
- Create 2D scene with a node and a child
- Lock the parent node, see that neither parent nor child can be selected by picking in the viewport
- Create 3D scene with a node and a child
- Lock the parent node, see that the child cannot be selected by picking in the viewport, but the parent can still be

### PR DESCRIPTION
**Pull request by iamnkc**
Fixes #29903  . 3D viewport nodes cannot be selected when they are locked.

### CODE REVIEW

File: editor/plugins/spatial_editor_plugin.cpp [hunk 1]
```diff
@@ -833,7 +836,9 @@ void SpatialEditorViewport::_surface_focus_exit() {
 
 	view_menu->set_disable_shortcuts(true);
 }
-
+bool SpatialEditorViewport ::_is_node_locked(const Node *pnode) {
```
Comment (akien-mga) [inline editor/plugins/spatial_editor_plugin.cpp]: This should be `p_node` (same in the header). We use the `p_` prefix for parameters, and `r_` for those passed as referenced and modified within the method.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks and congrats for your first contribution! :)

**Comment by n-k-chilagani** [comment]
Thank you for your support and for giving me this opportunity.
