### PR TITLE
Fixes #15470 "Crash on drag and drop scene file on empty scene"

### LINKED ISSUE #15470: (2D) Crash on drag and drop scene file on empty scene
**Godot version:**
3.0B 37ca542d2bfd9aac296e82e30a76117090dea08e
Compiler VS2017
SCons 2.5.1
Python 2.7

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
When I drag a scene (not empty and previously saved) to a completely empty new scene (2D) a dialog box appears with some options, when I choose one and click on "Ok" godot crash.
Could the same thing be done when a scene is instantiated as a Node? as a suggestion (when the scene is empty in 2d and 3d)
godotcrash

**Steps to reproduce:**
Create a project
Create a new scene, add a node and save file
Create a empty scene (no add nothing)
Drag from file system the scene created (with node) and drop to a empty scene (In 2D)
select any option from the menu and crash >:D !

**Minimal reproduction project:**
just create a empty scene and drag an drop the scene file in 2d mode
[GodotBeta.zip](https://github.com/godotengine/godot/files/1610325/GodotBeta.zip)

### PR DESCRIPTION
**Pull request by bfloch**
Fixes #15470

- New: Allows for multiple files to be dragged over
- Added error when multiple nodes are dropped in scene **without** scene root
  - Removed TTR: "This operation requires a single selected node.", "I see.."
  - Introduces TTR: "Can not instaniate multiple nodes without root."
- Fixes "Can't add_child, already got a parent" error
- Reduced multiple resource loading by casting
- Make sure to not _show_resource_type_selector if only PackedScenes are being dropped

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -4603,6 +4607,14 @@ bool CanvasItemEditorViewport::_create_instance(Node *parent, String &path, cons
 void CanvasItemEditorViewport::_perform_drop_data() {
 	_remove_preview();
 
+	// Without root dropping multiple files is not allowed
+	if (!target_node && selected_files.size() > 1) {
+		accept->get_ok()->set_text(TTR("Ok"));
+		accept->set_text(TTR("Can not instaniate multiple nodes without root."));
```
Comment (akien-mga) [inline editor/plugins/canvas_item_editor_plugin.cpp]: *instantiate

Comment (akien-mga) [reply editor/plugins/canvas_item_editor_plugin.cpp]: And I would use "Cannot".

**Comment by bfloch** [comment]
Typo fixed.
