### PR TITLE
Fix GDScript preload fails in standalone build unless files are present in directory

### LINKED ISSUE #56343: Godot 4.0 GDScript preload fails in standalone build unless files are present in directory
### Godot version

4.0.dev (28174d531) built with Visual Studio 2019

### System information

OS: Windows 10 (64-bit)
Renderer: Vulkan

### Issue description

The current dev build of Godot 4.0 fails to load GDScript files which use `preload` with some assets in exported builds, citing a "file does not exist" error, unless there is another file with the same name in the executable's directory.

For instance, trying to preload an asset using the path `res://square.png` fails unless there is a file named square.png next to the exported executable, but the content of that file does not matter, as Godot will still (correctly) load it from the PCK. It just bails early if the path doesn't exist in the filesystem.

This issue only affects the built-in `preload` in GDScript, and it does not affect the latest stable build (3.4.2). It's also picky about assets it fails to load (in the reproduction project, square.png is affected but icon.png isn't, and in another project, image files fail, but custom scripted resources don't).

In addition, because it causes a script parse error, affected scripts will not be attached to nodes when running in standalone mode, so this is a blocker.

### Steps to reproduce

Using the minimal reproduction project:

- Run main scene in editor: both images are loaded from filesystem
- Export project (important: it must be outside of the project directory!) and run it: only icon.png is loaded from the PCK, and an error is shown in the console:
    - `SCRIPT ERROR: Parse Error: Preload file "res://square.png" does not exist.`
- Create a placeholder file called square.png (the content does not matter, even a 0 byte empty file will work), place it in the directory where the exported project is, and run it again: both images are loaded from the PCK
- (Workaround) Delete the placeholder square.png file, replace the `preload` call in the script of the Square node (in main.tscn) with a `load` call, re-export, and run again: both images are loaded from the PCK

### Minimal reproduction project

[PreloadIssue_4.0.zip](https://github.com/godotengine/godot/files/7793325/PreloadIssue_4.0.zip)

### PR DESCRIPTION
**Pull request by s77rt**
**Intro:**
When exporting files into a pck format
files that are imported (those that have .import file) are replaced by whatever path is in the .import file + the .import file itself [[ref]](https://github.com/godotengine/godot/blob/736632ee7ed00a3474448cfd227f696f82905ac7/editor/export/editor_export_platform.cpp#L635-L707).

Example:
adding `audio.ogg` will add instead `audio.ogg.import` and `.godot/imported/audio.ogg-{hash}.oggvorbisstr`

With the exception of files that are meant to be kept (see previous ref) + the icon and the splash files [[ref]](https://github.com/godotengine/godot/blob/736632ee7ed00a3474448cfd227f696f82905ac7/editor/export/editor_export_platform.cpp#L802-L811)

**Problem:**
The problem is when checking for file existence, namely for `preload` where the gdscript analyser call `FileAccess::exists(p_preload->resolved_path)` it fails for every imported file (except the exceptions listed above), since `audio.ogg` does not exist (as per the example).

**Solution:**
Since for every imported file, the .import file is also added [[ref]](https://github.com/godotengine/godot/blob/736632ee7ed00a3474448cfd227f696f82905ac7/editor/export/editor_export_platform.cpp#L699-L705), we can make a second check to check for that .import file instead.

Fixes #56343

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -3189,7 +3189,7 @@ void GDScriptAnalyzer::reduce_preload(GDScriptParser::PreloadNode *p_preload) {
 			p_preload->resolved_path = parser->script_path.get_base_dir().path_join(p_preload->resolved_path);
 		}
 		p_preload->resolved_path = p_preload->resolved_path.simplify_path();
-		if (!FileAccess::exists(p_preload->resolved_path)) {
+		if (!FileAccess::exists(p_preload->resolved_path) && !FileAccess::exists(p_preload->resolved_path + ".import")) {
```
Comment (reduz) [inline modules/gdscript/gdscript_analyzer.cpp:3192]: Just use `ResourceLoader::exists` instead of all this.

**Review by reduz — DISMISSED** [review]

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/gdscript/gdscript_analyzer.cpp:3192]: I tested and confirmed that this fixes the issue. I'll push an update directly to this PR to do that change and squash the commits / make the commit message clearer.

**Review by akien-mga — APPROVED** [review]
Looks good.

**Comment by akien-mga** [comment]
Thanks!
