### PR TITLE
Fix Ignore External Changes Bug

### LINKED ISSUE #106410: Ignore External Changes no longer re-saves scenes
### Tested versions

Regression from #90034

### System information

W10

### Issue description

When a scene is edited externally and in the dialog you select "Ignore External Changes", it's supposed to re-save all scenes. It doesn't anymore, if the scenes are currently unmodified.

I think it should be changed to actually re-save only scenes that were changed, instead of all of them.

### Steps to reproduce

1. Open a scene
2. Modify the tscn file externally
3. Focus on the editor and click the aforementioned button

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jorgekorgut**
Fix Issue #106410 : Add a check for external modified scene files (_is_scene_externally_modified()) before handling the logic of ignoring external changes.

ignore-external-changes-test

* *Bugsquad edit, fixes: #106410*

### CODE REVIEW

**Comment by KoBeWi** [comment]
As I suggested in the issue, it would be better to save only the scenes in the list, instead of using `_save_all_scenes()`.

**Comment by jorgekorgut** [comment]
@KoBeWi Thanks for your feedback.

I have been reading the code for a while and I found just one reference containing the information of external unsaved files. This tree, called```disk_changed_list```, keeps reference of the string of the scenes names ? (not so sure about it) and I think it is only used for the UI.

Just to be sure you have spotted, calling the ```_save_all_scenes()``` does actually the saving scene logic only for the lists that are not saved in the editor ```_is_scene_unsaved()``` AND with this pull request scenes that were externally modified ```_is_scene_externally_modified()```.

Do you still would prefer a new function like ```_save_scene(i)``` that is called somewhere ? (dont know where or how do you want this function to be called)

**Comment by KoBeWi** [comment]
`_save_scene()` already exists and takes a scene path (index is optional), so you can use that.

The reason I think it's better to save only modified scenes is that this information is already available. `_save_all_scenes()` is used in other places too (e.g. when running project), and with your current code it will perform unnecessary check.

I'd go with your suggestion 1. You can add a `LocalVector<String>` with paths of the scenes (the same ones as added to `disk_changed_list`).
Alternatively you can reuse `disk_changed_list`, since it already has all the scene paths. However it may contain not only scenes, so you'd have to mark items whether they are a scene or not. While it would work, the above solution sounds cleaner.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -1304,21 +1304,28 @@ void EditorNode::_scan_external_changes() {
...
 		uint64_t last_date = editor_data.get_scene_modified_time(i);
-		uint64_t date = FileAccess::get_modified_time(editor_data.get_scene_path(i));
+		uint64_t date = FileAccess::get_modified_time(scene_path);
 
 		if (date > last_date) {
 			TreeItem *ti = disk_changed_list->create_item(r);
-			ti->set_text(0, editor_data.get_scene_path(i).get_file());
+			ti->set_text(0, scene_path.get_file());
 			need_reload = true;
+
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1327]:
```suggestion
```
Unnecessary blank line. Same below.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -1304,21 +1304,28 @@ void EditorNode::_scan_external_changes() {
...
+	disk_changed_scenes.clear();
+	disk_changed_project = false;
 
+	// Check if any edited scene has changed.
 	for (int i = 0; i < editor_data.get_edited_scene_count(); i++) {
 		Ref<DirAccess> da = DirAccess::create(DirAccess::ACCESS_RESOURCES);
-		if (editor_data.get_scene_path(i) == "" || !da->file_exists(editor_data.get_scene_path(i))) {
+
+		String scene_path = editor_data.get_scene_path(i);
+
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1315]:
```suggestion
		const String scene_path = editor_data.get_scene_path(i);
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
