### PR TITLE
Fix `PROPERTY_HINT_GROUP_ENABLE` display on hover

### LINKED ISSUE #108257: Editor inspector section displays hover feedback even if non-actionable due to not containing any visible properties (unchecked checkbox)
### Tested versions

- Reproducible in: 4.5.beta1
- Not reproducible in: 4.4.1.stable (checkbox-on-section feature is not present there)

### System information

Godot v4.5.beta (efb40c152) - Fedora Linux 42 (KDE Plasma Desktop Edition) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 5090 (nvidia; 575.64) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 62.33 GiB memory

### Issue description

When hovering a section in the inspector, the section background and text will brighten, which is good. However, this also happens when hovering a section that has an unchecked checkbox on it. These sections can't be unfolded by design, as they do not contain any visible properties until you tick the checkbox.

https://github.com/user-attachments/assets/b7621e56-71ab-4dff-95e6-de9495f4c0d9

We should do one of these two things:

1. Remove hover feedback on the section if it has an unchecked checkbox, but keep it for checked checkboxes as you can still (un)fold the section.
2. Make clicking the section tick the checkbox if it's currently unchecked.

I'm neutral on which one is the best solution here. Solution 2 is more seamless to the user, but is prone to accidentally activating some features, which can have a performance impact in some cases (e.g. shadows in Light3D).

cc @cier and @lodetrick, as they implemented the feature in https://github.com/godotengine/godot/pull/81630 and https://github.com/godotengine/godot/pull/105272.

### Steps to reproduce

- Add an OmniLight3D node.
- Hover the mouse over the **Shadow** section in the inspector, then try to click it. See that nothing happens unless you tick the **On** checkbox next to it, but the section has visible hover feedback regardless.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by lodetrick**
Fixes #108257

This PR fixes a regression by making it so unchecked sections do not show the hovered highlight. This PR syncs the `gui_input()`'s understanding of the hover with the `NOTIFICATION_DRAW`, as there were issues with the hover hint becoming out of sync.

### CODE REVIEW

File: editor/inspector/editor_inspector.cpp [hunk 1]
```diff
@@ -2166,11 +2168,11 @@ void EditorInspectorSection::setup(const String &p_section, const String &p_labe
 
 void EditorInspectorSection::gui_input(const Ref<InputEvent> &p_event) {
 	ERR_FAIL_COND(p_event.is_null());
-	bool has_children_to_show = vbox->get_child_count(false) != 0;
+	bool can_click_unfold = vbox->get_child_count(false) != 0 && !(!checkbox_only && checkable && !checked);
```
Comment (KoBeWi) [inline editor/inspector/editor_inspector.cpp:2173]: Uh, double negation. I think the condition can be something like
```suggestion
	bool can_click_unfold = vbox->get_child_count(false) != 0 && (checkbox_only || !checkable || checked);
```
Though it's arguable which one is more readable.

File: editor/inspector/editor_inspector.cpp [hunk 2]
```diff
@@ -2059,11 +2059,13 @@ void EditorInspectorSection::_notification(int p_what) {
...
+		case NOTIFICATION_MOUSE_EXIT_SELF:
 		case NOTIFICATION_MOUSE_EXIT: {
 			if (dropping_for_unfold) {
 				dropping_unfold_timer->stop();
 			}
 
+			header_hover = false;
 			check_hover = false;
 			keying_hover = false;
 			queue_redraw();
```
Comment (KoBeWi) [inline editor/inspector/editor_inspector.cpp]: Shouldn't this only redraw if `header_hover` was previously true?

**Review by KoBeWi — APPROVED** [review]

File: editor/inspector/editor_inspector.cpp (hunk 1 above)
Comment (lodetrick) [reply editor/inspector/editor_inspector.cpp:2173]: In my opinion the double negation is more readable because it is checking against a single case (is how I thought about it), I reorganized it which made the double negation more apparent, I could change it back to:
```suggestion
	bool can_click_unfold = vbox->get_child_count(false) != 0 && !(checkable && !checked && !checkbox_only);
```

**Comment by Repiteo** [comment]
Thanks!
