### PR TITLE
Fix crash when division by zero/modulo by zero happen on vectors

### LINKED ISSUE #95168: `Vector*i` divide by zero crash
### Tested versions

v4.3.rc.custom_build [3978628c6]

### System information

Windows 10

### Issue description

Dividing by zero with any of the `Vector*i` types in gdscript will cause a crash when running from editor (only the game crashes, editor continues running fine but does not show any errors).  Dividing by zero with `int` gives the error "Division by zero error in operator '/'.", and shows the line where the error occurred - not sure how different the `Vector*i` handling is, but seems like it could be helpful to show a similar error.  Running from console gives the stack trace below:

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.rc.custom_build (3978628c6cc1227250fc6ed45c8d854d24c30c30)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] Vector2i::operator/ (C:\dev\godot\core\math\vector2i.cpp:100)
[1] Vector2i::operator/ (C:\dev\godot\core\math\vector2i.cpp:100)
[2] OperatorEvaluatorDivNZ<Vector2i,Vector2i,Vector2i>::validated_evaluate (C:\dev\godot\core\variant\variant_op.h:205)
[3] GDScriptFunction::call (C:\dev\godot\modules\gdscript\gdscript_vm.cpp:789)
[4] GDScriptInstance::callp (C:\dev\godot\modules\gdscript\gdscript.cpp:2032)
[5] Object::callp (C:\dev\godot\core\object\object.cpp:786)
[6] Variant::callp (C:\dev\godot\core\variant\variant_call.cpp:1211)
[7] GDScriptFunction::call (C:\dev\godot\modules\gdscript\gdscript_vm.cpp:1781)
[8] GDScriptInstance::callp (C:\dev\godot\modules\gdscript\gdscript.cpp:2032)
[9] Node::_notification (C:\dev\godot\scene\main\node.cpp:217)
[10] CanvasItem::_notificationv (C:\dev\godot\scene\main\canvas_item.h:45)
[11] Node2D::_notificationv (C:\dev\godot\scene\2d\node_2d.h:37)
[12] Object::notification (C:\dev\godot\core\object\object.cpp:873)
[13] Node::_propagate_ready (C:\dev\godot\scene\main\node.cpp:273)
[14] Node::_propagate_ready (C:\dev\godot\scene\main\node.cpp:262)
[15] Node::_set_tree (C:\dev\godot\scene\main\node.cpp:3174)
[16] OS_Windows::run (C:\dev\godot\platform\windows\os_windows.cpp:1662)
[17] widechar_main (C:\dev\godot\platform\windows\godot_windows.cpp:181)
[18] _main (C:\dev\godot\platform\windows\godot_windows.cpp:208)
[19] main (C:\dev\godot\platform\windows\godot_windows.cpp:220)
[20] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[21] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

### Steps to reproduce

In a new project, add the below code to the main scene and run:

```gdscript
func _ready() -> void:
	test_vector()
	
func test_int():
	var i1 := 1
	var i2 := 0
	print(i1 / i2)

func test_vector():
	var v1 := Vector2i(1, 1)
	var v2 := Vector2i(0, 0)
	print(v1 / v2)

```

### Minimal reproduction project (MRP)

N/A, can be reproduced in a new project with sample code above

### PR DESCRIPTION
**Pull request by Chaosus**
- Fix https://github.com/godotengine/godot/issues/95168

```gdscript
func test_vector():
	var v1 := Vector2i(1, 1)
	var v2 := Vector2i(0, 0)
	print(v1 / v2)

# or

func test_vector2():
	var v1 := Vector2i(1, 1)
	var v2 := 0
	print(v1 / v2)
```

Will now correctly finish with error, instead of silent crash.

### CODE REVIEW

File: modules/gdscript/gdscript_byte_codegen.cpp [hunk 1]
```diff
@@ -585,8 +585,8 @@ void GDScriptByteCodeGenerator::write_unary_operator(const Address &p_target, Va
...
-	if (HAS_BUILTIN_TYPE(p_left_operand) && HAS_BUILTIN_TYPE(p_right_operand) && ((p_operator != Variant::OP_DIVIDE && p_operator != Variant::OP_MODULE) || p_left_operand.type.builtin_type != Variant::INT || p_right_operand.type.builtin_type != Variant::INT)) {
+	// Avoid validated evaluator for modulo and division when operands are int or integer vector, since there's no check for division by zero.
+	if (HAS_BUILTIN_TYPE(p_left_operand) && HAS_BUILTIN_TYPE(p_right_operand) && ((p_operator != Variant::OP_DIVIDE && p_operator != Variant::OP_MODULE) || (!(p_left_operand.type.builtin_type == Variant::INT && p_right_operand.type.builtin_type == Variant::INT) && !(p_left_operand.type.builtin_type == Variant::VECTOR2I && (p_right_operand.type.builtin_type == Variant::VECTOR2I || p_right_operand.type.builtin_type == Variant::INT)) && !(p_left_operand.type.builtin_type == Variant::VECTOR3I && (p_right_operand.type.builtin_type == Variant::VECTOR3I || p_right_operand.type.builtin_type == Variant::INT)) && !(p_left_operand.type.builtin_type == Variant::VECTOR4I && (p_right_operand.type.builtin_type == Variant::VECTOR4I || p_right_operand.type.builtin_type == Variant::INT))))) {
```
Comment (dalexeev) [inline modules/gdscript/gdscript_byte_codegen.cpp:589]: 1. Could you please add tests for this?
2. Could you turn this into a `switch` for better readability?

Comment (Chaosus) [reply modules/gdscript/gdscript_byte_codegen.cpp]: 1. Not sure if I did the test right, can you check?
2. Fixed

File: modules/gdscript/gdscript_byte_codegen.cpp [hunk 2]
```diff
@@ -585,8 +585,61 @@ void GDScriptByteCodeGenerator::write_unary_operator(const Address &p_target, Va
...
+				}
+				break;
+			case Variant::VECTOR2I:
+				switch (p_right_operand.type.builtin_type) {
+					case Variant::INT:
+						valid = false;
+						break;
+					case Variant::VECTOR2I:
+						valid = false;
+						break;
```
Comment (Calinou) [inline modules/gdscript/gdscript_byte_codegen.cpp:608]: This can be simplified to:

```suggestion
					case Variant::INT:
					case Variant::VECTOR2I:
						valid = false;
						break;
```

Same for the other cases below.

**Review by Calinou — COMMENTED** [review]
The logic behind this makes sense to me, but I'm not well-versed in the GDScript codegen implementation.

File: modules/gdscript/gdscript_byte_codegen.cpp [hunk 3]
```diff
@@ -585,8 +585,55 @@ void GDScriptByteCodeGenerator::write_unary_operator(const Address &p_target, Va
...
+					case Variant::VECTOR4I:
+						valid = false;
+						break;
+					default:
+						break;
+				}
+				break;
+			default:
+				break;
+		}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_byte_codegen.cpp:633]:
```suggestion
		switch (p_left_operand.type.builtin_type) {
			case Variant::INT:
				valid = p_right_operand.type.builtin_type != Variant::INT;
				break;
			case Variant::VECTOR2I:
			case Variant::VECTOR3I:
			case Variant::VECTOR4I:
				valid = p_right_operand.type.builtin_type != Variant::INT && p_right_operand.type.builtin_type != p_left_operand.type.builtin_type;
				break;
			default:
				break;
		}
```

File: modules/gdscript/gdscript_byte_codegen.cpp [hunk 4]
```diff
@@ -585,8 +585,55 @@ void GDScriptByteCodeGenerator::write_unary_operator(const Address &p_target, Va
 }
 
 void GDScriptByteCodeGenerator::write_binary_operator(const Address &p_target, Variant::Operator p_operator, const Address &p_left_operand, const Address &p_right_operand) {
-	// Avoid validated evaluator for modulo and division when operands are int, since there's no check for division by zero.
-	if (HAS_BUILTIN_TYPE(p_left_operand) && HAS_BUILTIN_TYPE(p_right_operand) && ((p_operator != Variant::OP_DIVIDE && p_operator != Variant::OP_MODULE) || p_left_operand.type.builtin_type != Variant::INT || p_right_operand.type.builtin_type != Variant::INT)) {
+	// Avoid validated evaluator for modulo and division when operands are int or integer vector, since there's no check for division by zero.
+	bool valid = HAS_BUILTIN_TYPE(p_left_operand) && HAS_BUILTIN_TYPE(p_right_operand);
+	if (valid && (p_operator == Variant::OP_DIVIDE || p_operator == Variant::OP_MODULE)) {
```
Comment (dalexeev) [inline modules/gdscript/gdscript_byte_codegen.cpp:590]:
```suggestion
	bool valid = HAS_BUILTIN_TYPE(p_left_operand) && HAS_BUILTIN_TYPE(p_right_operand);

	// Avoid validated evaluator for modulo and division when operands are int or integer vector, since there's no check for division by zero.
	if (valid && (p_operator == Variant::OP_DIVIDE || p_operator == Variant::OP_MODULE)) {
```

File: modules/gdscript/tests/scripts/runtime/errors/op_by_zero/division_by_zero_int.gd [hunk 5]
```diff
@@ -0,0 +1,3 @@
+func test():
+	var integer = 1
+	integer /= 0
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/runtime/errors/op_by_zero/division_by_zero_int.gd:3]: I'm not sure if validated evaluator is used in this case or not. Maybe yes, since it's a local variable and the inferred weak type doesn't change. But if not, we can't tell from the positive test result, since validated evaluators are not used for untyped variables. So I'd prefer to explicitly use typed variables.

```suggestion
	var integer := 1
	integer /= 0
```

or

```suggestion
	var integer: int = 1
	integer /= 0
```

File: modules/gdscript/tests/scripts/runtime/errors/op_by_zero/division_by_zero_int.gd
Comment (dalexeev) [inline modules/gdscript/tests/scripts/runtime/errors/op_by_zero/division_by_zero_int.gd:1]: * I'm not sure testing every data type, vector component, and left/right operand combination (if we add negative tests) is worth it. Even with a separate folder, it still clutters up the filesystem. See also #99490.

**Review by dalexeev — COMMENTED** [review]
Sorry for the long delay! Added some comments, mostly about tests.

File: modules/gdscript/tests/scripts/runtime/errors/op_by_zero/division_by_zero_int.gd
Comment (Chaosus) [reply modules/gdscript/tests/scripts/runtime/errors/op_by_zero/division_by_zero_int.gd:1]: Ok, I removed them for now, added only two tests (after your PR we can add more to them)

**Review by dalexeev — APPROVED** [review]
Looks good to me.

**Comment by Repiteo** [comment]
Thanks!
