### PR TITLE
Fix save dialog clearing filename when navigating folders

### LINKED ISSUE #114030: Scene name clears when you open a folder
### Tested versions

- NOT Present in 4.4.1 stable
- Present in 4.6beta1

### System information

Godot v4.6.beta1 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.8157) - AMD Ryzen 9 3900X 12-Core Processor (24 threads) - 47.92 GiB memory

### Issue description

If you want to save a node as a scene and open a folder along the way, the name disappears

### Steps to reproduce

https://github.com/user-attachments/assets/3db7194b-3c97-4010-a692-774a9e96689d

1. Select a node branch to save as a scene
2. Select a folder in your project

### Minimal reproduction project (MRP)

Any project will do

### PR DESCRIPTION
**Pull request by ayanchavand**
Fixes #114030 

**Solution**
In` FileDialog::_file_list_selected()`, the filename is no longer cleared when a directory is selected if the dialog is in `FILE_MODE_SAVE_FILE`.
In` FileDialog::_dir_submitted(`), the filename is only cleared for non-SAVE modes.

### CODE REVIEW

File: scene/gui/file_dialog.cpp [hunk 1]
```diff
@@ -628,7 +630,7 @@ void FileDialog::_file_list_selected(int p_item) {
 		} else {
 			set_default_ok_text(ETR("Open"));
 		}
-	} else if (mode == FILE_MODE_OPEN_DIR || mode == FILE_MODE_OPEN_ANY || !dir_access->file_exists(filename_edit->get_text())) {
+	} else if (mode != FILE_MODE_SAVE_FILE) {
```
Comment (KoBeWi) [inline scene/gui/file_dialog.cpp:633]:
```suggestion
	} else if (mode != FILE_MODE_SAVE_FILE && mode != FILE_MODE_OPEN_DIR) {
```
EDIT:
Actually seems like it doesn't change anything 🤔

Comment (AThousandShips) [reply scene/gui/file_dialog.cpp:633]: In that case the check on line 635 should be changed as it's now impossible to have the first condition

**Comment by AThousandShips** [comment]
Please make sure you have added any changes before pushing, please don't push unnecessarily without any changes (in this case it ended up not being relevant, so good actually lol)

File: scene/gui/file_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/gui/file_dialog.cpp:633]: The filename is not visible in dir mode, so this is irrelevant.

Comment (AThousandShips) [reply scene/gui/file_dialog.cpp:633]: What? I'm talking about this:
```cpp
if (mode == FILE_MODE_OPEN_DIR || mode == FILE_MODE_OPEN_ANY) {
```

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/file_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/gui/file_dialog.cpp:633]: Either way my original suggestion was wrong, so no further changes are needed.

**Comment by Repiteo** [comment]
Thanks!
