### PR TITLE
fixed holding alt while zooming zooms in by 2 increments.

### LINKED ISSUE #67221: Godot 4B2: Alt+scroll integer zooming is broken a little, moves by 2 zoom increments instead of 1
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10

### Issue description

It looks like something slightly broke with
https://github.com/godotengine/godot/pull/50490

In godot 3, this moves by steps of 1 zoom increment.  So you zoom

25%/33%/50%/100%/200%/300%, et cetera

In godot 4 this appears to now move by steps of 2 zoom increments.  
So the zoom levels are now
25%/50%/200%/400%
or
33%/100%/300%/500%

### Steps to reproduce

Hold down alt, use the scroll wheel to zoom in or out.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by MladoniSzabi**
When scrolling, Godot is generating two events:
`InputEventMouseButton: button_index=4, mods=Alt, pressed=true, position=((807, 754)), button_mask=8, double_click=false`
`InputEventMouseButton: button_index=4, mods=Alt, pressed=false, position=((807, 754)), button_mask=0, double_click=false`

Added an if statement to check if the mouse button is pressed so that only one of the events is processed.
Not sure if Godot generating two scroll events is intended but regardless this should solve the issue. (also not sure how to fix that)

Resolves #67221

### CODE REVIEW

File: scene/gui/view_panner.cpp [hunk 1]
```diff
@@ -39,39 +39,43 @@ bool ViewPanner::gui_input(const Ref<InputEvent> &p_event, Rect2 p_canvas_rect)
 	if (mb.is_valid()) {
 		Vector2 scroll_vec = Vector2((mb->get_button_index() == MouseButton::WHEEL_RIGHT) - (mb->get_button_index() == MouseButton::WHEEL_LEFT), (mb->get_button_index() == MouseButton::WHEEL_DOWN) - (mb->get_button_index() == MouseButton::WHEEL_UP));
 		if (scroll_vec != Vector2()) {
```
Comment (KoBeWi) [inline scene/gui/view_panner.cpp:41]:
```suggestion
		if (scroll_vec != Vector2() && mb->is_pressed()) {
```
You could just do this instead of indenting everything.

Comment (MladoniSzabi) [reply scene/gui/view_panner.cpp]: Merged the two if statements.

File: scene/gui/view_panner.cpp [hunk 2]
```diff
@@ -38,7 +38,9 @@ bool ViewPanner::gui_input(const Ref<InputEvent> &p_event, Rect2 p_canvas_rect)
 	Ref<InputEventMouseButton> mb = p_event;
 	if (mb.is_valid()) {
 		Vector2 scroll_vec = Vector2((mb->get_button_index() == MouseButton::WHEEL_RIGHT) - (mb->get_button_index() == MouseButton::WHEEL_LEFT), (mb->get_button_index() == MouseButton::WHEEL_DOWN) - (mb->get_button_index() == MouseButton::WHEEL_UP));
-		if (scroll_vec != Vector2()) {
+		// moving the scroll wheel sends two events: one with pressed as true,
+		// and one with pressed as false. Make sure we only process one of them
```
Comment (KoBeWi) [inline scene/gui/view_panner.cpp:42]:
```suggestion
		// Moving the scroll wheel sends two events: one with pressed as true,
		// and one with pressed as false. Make sure we only process one of them.
```

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/view_panner.cpp (hunk 2 above)
Comment (KoBeWi) [reply scene/gui/view_panner.cpp]: You forgot `.`

Comment (MladoniSzabi) [reply scene/gui/view_panner.cpp]: Fixed moving not being capitalised

Comment (MladoniSzabi) [reply scene/gui/view_panner.cpp]: Sorry, fixed it now.

**Comment by akien-mga** [comment]
Thanks!
