### PR TITLE
Fix polygon generation in BitMap

### LINKED ISSUE #31675: BitMap `opaque_to_polygons()` polygon generation problem
**Godot version:**
Godot_v3.1.1-stable_win64

**OS/device including version:**
Windows10

**Issue description:**

In my project I'm using a lot of BitMaps to generate polygons through GDScript.

Sometimes the polygon generated by opaque_to_polygon has unexpected behavior.

I did some troubleshooting and it seems that if there is a single true pixel near a larger true area, the opaque_to_polygon function only generates a "single pixle" polygon and the larger area is ignored.

**Steps to reproduce:**

See the example project.

In the attached image, the first png used for BitMap Generation has an angular pixel near a larger area and generates a polygon around the single pixel by skipping the larger area, in the second png it works as it should.

BitMap_Polygon_Bug

**Minimal reproduction project:**
[BitMap_Bug_Example.zip](https://github.com/godotengine/godot/files/3540946/BitMap_Bug_Example.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
While working on #68380 some issues with the way BitMap does polygon generation showed up, I have tried to solve them here

There are a few things that have been changed:
* An oversight in `fill_bits` that caused connected pixels to not be filled, causing duplicate polygons being generated
* The procedure for traversing the bits and generating the polygon in `_march_squares`

For the `fill_bits` you could have a the following, starting at x and the red square would not be filled, causing in some cases overlapping polygons as the function would start over in the red square and create a polygon overlapping with the white area:
image

There were some issues with the traversing the squares to generate the polygon as well, causing entire areas to be ignored:
image

There were also cases where the polygon would get self intersections, like this:
image
Which break the triangulation

When the number of points is greater than the pixels in the BitMap it now returns an empty result rather than the points so far, I don't see how a result in that case is valid and shouldn't be returned

So my solution is this:
* Fix the popping in the `fill_bits`, it seems to have been an oversight as the code says "The next loop over j must start normally." which I take to mean subtracting one, and from what I can see it doesn't cause any problems
* Fix the behavior in diagonal cases:
image
Where traversal didn't take into account the direction we are coming from, as the direction to go is (as far as I can figure out) based on the direction as we traverse it counter-clockwise
* Fix cases of self-overlap caused by my fix as well as other cases original to the code, this splits polygons at points where it reaches the same point again, which in some cases breaks triangulation (as it uses ear-clipping)

I had a few other approaches but this approach avoids filling in any bits that weren't filled, making assumptions or decisions on where should be included to solve the degenerate cases, at the cost of splitting polygons at these self overlap points

There might still be some issues in the `reduce` function that I haven't identified but it seems that it now generates valid polygons for general cases

For testing purposes here is a project where you can play around with a bitmap and see the different results:
[BitPR.zip](https://github.com/godotengine/godot/files/10022270/BitPR.zip)
Instructions:
* Left mouse fills square
* Right mouse clears square
* Space gets polygons
* Tab inverts bits
* Escape clears

Fixes #31675

### CODE REVIEW

**Comment by AThousandShips** [comment]
For cases when you might want polygons that are touching to be grouped I'm considering adding a "element" argument to the `clip_opaque_to_polygons` function to return what connected component a resulting polygon belongs to, but I'm not sure how much use that would get

**Comment by AThousandShips** [comment]
Nested polygons are generated, which might be an issue in some cases, i.e. when a polygon has a hole that contains another polygon, the fix for that could be relatively straight forward but as it doesn't generate any directly broken behavior I haven't touched it here, and would probably require options or a discussion over how to exactly navigate that

**Comment by AThousandShips** [comment]
To explain the stack and the processing of "crossing points" a bit more in detail:
In the case of the diagonals we can get a result where the polygon reaches the same point twice, which can cause cases that are not triangulatable, and that are always generating broken triangulations, in this case we track a stack of ranges between these points, and when we reach such a point a single time we roll up the range since the last case of such a point and the current point so that it becomes a new polygon

**Comment by Geometror** [comment]
Looks great! Do you think you can provide some unit tests which check the edge cases you fixed?

**Comment by AThousandShips** [comment]
@Geometror never written any before but I can take a stab at it!

**Comment by Geometror** [comment]
You can orient yourself on the existing test cases in `test_bit_map.h` (starting from line 398, test case "[BitMap] Clip to polygon").

**Comment by AThousandShips** [comment]
There added three tests, one for each diagonal, to ensure it catches everything, and splits correctly, and one for this shape to ensure it doesn't split that even though there is a crossing point in it:
image

**Comment by AThousandShips** [comment]
Merged the diagonal test cases and added a test case to verify the fill fix (the y shape in the description)

File: scene/resources/bit_map.cpp [hunk 1]
```diff
@@ -505,17 +593,18 @@ Vector<Vector<Vector2>> BitMap::clip_opaque_to_polygons(const Rect2i &p_rect, fl
 			if (!fill->get_bit(j, i) && get_bit(j, i)) {
 				fill_bits(this, fill, Point2i(j, i), r);
 
-				Vector<Vector2> polygon = _march_square(r, Point2i(j, i));
-				print_verbose("BitMap: Pre reduce: " + itos(polygon.size()));
-				polygon = reduce(polygon, r, p_epsilon);
-				print_verbose("BitMap: Post reduce: " + itos(polygon.size()));
+				for (Vector<Vector2> polygon : _march_square(r, Point2i(j, i))) {
+					print_verbose("BitMap: Pre reduce: " + itos(polygon.size()));
```
Comment (Geometror) [inline scene/resources/bit_map.cpp:597]: I wouldn't keep those print_verbose statements here. Print verbose should be used to provide more detailed info about some process, but this will just result in console spam without much value for the user.

**Review by Geometror — CHANGES_REQUESTED** [review]
Thanks for updating this so quickly! Nice work, there's just a small issue which needs to be addressed.

File: scene/resources/bit_map.cpp (hunk 1 above)
Comment (AThousandShips) [reply scene/resources/bit_map.cpp]: Done! Removed the one for `fill_bits` too for the same reason

**Comment by AThousandShips** [comment]
Also I'm pretty sure adding the y position of the rectangle to the result is incorrect, so fixed that, correct me if that's an incorrect assumption

**Comment by AThousandShips** [comment]
(Sorry didn't realize that removed the previous reviewers)

**Review by Geometror — APPROVED** [review]
Implementation looks good and after testing I can confirm that this PR fixes the current issues with polygon generation.

**Comment by akien-mga** [comment]
Thanks!
