### PR TITLE
Fix "Import Defaults" selector not being initialized incorrectly

### LINKED ISSUE #80867: Project -> Project Settings -> Import Defaults -> The selection list 'Importer' is initialized incorrectly
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Godot v4.2.dev3 - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

The content is empty. In the list `<Select Importer> `should be preselected, if possible. 
Or directly show the settings for "Animation Library" (check first selection).

Bildschirmfoto 2023-08-22 um 01 29 44

### Steps to reproduce

1. Project
2. Project Settings
3. Import Defaults 

https://github.com/godotengine/godot/assets/41921395/cb263c7d-27f0-4053-a555-0ed03ac7ef2a

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
In ImportDefaultsEditor, when first call the function, last_selected can be the first one(`Animation Library`) and directly show the settings for "Animation Library", fix #80867

However, there is another option: show the `<Select Importer>` option, I decided to go with the first option but this one is ok too. Can change my code to impl this one.

### CODE REVIEW

**Comment by dalexeev** [comment]
> However, there is another option: show the `<Select Importer>` option

In my opinion, `<Select Importer>` doesn't serve any purpose, we can remove it:

```diff
diff --git a/editor/import_defaults_editor.cpp b/editor/import_defaults_editor.cpp
index 98a9bfe9dc..a0ee2c2b66 100644
--- a/editor/import_defaults_editor.cpp
+++ b/editor/import_defaults_editor.cpp
@@ -169,17 +169,15 @@ void ImportDefaultsEditor::_importer_selected(int p_index) {
 
 void ImportDefaultsEditor::clear() {
 	String last_selected;
-	if (importers->get_selected() > 0) {
+	if (importers->get_selected() >= 0) {
 		last_selected = importers->get_item_text(importers->get_selected());
 	}
 
 	importers->clear();
 
-	importers->add_item("<" + TTR("Select Importer") + ">");
-	importers->set_item_disabled(0, true);
-
 	List<Ref<ResourceImporter>> importer_list;
 	ResourceFormatImporter::get_singleton()->get_importers(&importer_list);
+
 	Vector<String> names;
 	for (const Ref<ResourceImporter> &E : importer_list) {
 		String vn = E->get_visible_name();
@@ -190,8 +188,9 @@ void ImportDefaultsEditor::clear() {
 	for (int i = 0; i < names.size(); i++) {
 		importers->add_item(names[i]);
 
-		if (names[i] == last_selected) {
-			importers->select(i + 1);
+		if (names[i] == last_selected || (i == 0 && last_selected.is_empty())) {
+			importers->select(i);
+			_update_importer();
 		}
 	}
 }
```

**Comment by jsjtxietian** [comment]
> In my opinion, `<Select Importer>` doesn't serve any purpose, we can remove it:

Agreed. The OptionButton itself is quite clear, thus maybe we don't need a placeholder there to tell the user to tselect one importer.

File: editor/import_defaults_editor.cpp [hunk 1]
```diff
@@ -187,11 +188,15 @@ void ImportDefaultsEditor::clear() {
 	}
 	names.sort();
 
+	if (is_first && names.size() > 0)
+		last_selected = names[0];
+
```
Comment (dalexeev) [inline editor/import_defaults_editor.cpp:193]: `is_first` is not needed.

```suggestion
	if (last_selected.is_empty() && !names.is_empty()) {
		last_selected = names[0];
	}
```

Comment (jsjtxietian) [reply editor/import_defaults_editor.cpp:193]: Here's what I thought at first, have a bool here can make code more understandable. But you are right, I will add a comment to the code.

File: editor/import_defaults_editor.cpp [hunk 2]
```diff
@@ -187,11 +185,17 @@ void ImportDefaultsEditor::clear() {
 	}
 	names.sort();
 
+	// last_selected.is_empty means it's the first time being called.
```
Comment (dalexeev) [inline editor/import_defaults_editor.cpp:188]:
```suggestion
	// `last_selected.is_empty()` means it's the first time being called.
```

**Review by dalexeev — APPROVED** [review]
Looks good to me.

**Comment by YuriSizov** [comment]
The solution makes sense to me, but could you please amend your commit message to follow the preferred style of the project? Your first line needs concisely describe the change, so you can use the title of the PR for this purpose. You can keep the rest, just put it into commit's description instead.

**Comment by jsjtxietian** [comment]
Thank you for your help, I missed the commit message requirement mentioned in CONTRIBUTING.md, sorry for that!

**Comment by YuriSizov** [comment]
Thanks!
