### PR TITLE
ResourceLoader: Report appropriate error code when no suitable loader is found

### LINKED ISSUE #95490: ResourceLoader.load_threaded_get_status returns THREAD_LOAD_LOADED after ResourceLoader.load_threaded_request with invalid path
### Tested versions

- Reproducible in v4.3.rc3.official [03afb92ef], latest master [9f6336b46], v4.0.4.stable.official [fc0b241c9]

### System information

Godot v4.3.rc3 - Ubuntu 24.04 LTS 24.04 - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

`ResourceLoader.load_threaded_get_status` with invalid path returns `3`, which is `THREAD_LOAD_LOADED`, after `ResourceLoader.load_threaded_request` with that same invalid path. Interestingly, `ResourceLoader.load_threaded_request` returns `0`, which is `OK`, while printing an error. After call to `ResourceLoader.load_threaded_get` with that invalid path, `ResourceLoader.load_threaded_get_status` starts to give normal result: `0`, which is `THREAD_LOAD_INVALID_RESOURCE`.
By invalid path, i mean something like `res://node.tsc` or invalid UID, NOT like `res://node.gd`, which results in "File not found" and `THREAD_LOAD_FAILED` status.

### Steps to reproduce

1. Call `ResourceLoader.load_threaded_request` with some invalid path.
2. Call `ResourceLoader.load_threaded_get_status` with that same path. Notice status equaling to 3.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/16601878/mrp.zip)
 1. Start project.
 2. Notice output.
 3. Click "get" to call `ResourceLoader.load_threaded_get`.

### PR DESCRIPTION
**Pull request by RandomShaper**
New version of the reverted #97370.

One difference worth mentioning compared to the reverted PR is that, in order to make a simpler diff, reporting the file doesn't 
exist is more prioritary than telling the extension is unknown. I don't think we have reasons to prefer one over the other.

E.g., loading `thing.aaa`, which doesn't exist:
- Old PR: `ERR_FILE_UNRECOGNIZED`.
- This PR: `ERR_FILE_NOT_FOUND`.

If the file exists, then this PR will then do report `ERR_FILE_UNRECOGNIZED`.

Fixes #95490.

### CODE REVIEW

File: core/io/resource_loader.cpp [hunk 1]
```diff
@@ -316,14 +316,34 @@ Ref<Resource> ResourceLoader::_load(const String &p_path, const String &p_origin
 		return res;
 	}
 
+#ifdef TOOLS_ENABLED
+	if (Engine::get_singleton()->is_editor_hint()) {
```
Comment (RandomShaper) [inline core/io/resource_loader.cpp:320]: Restricting this to editor sessions (and not just editor builds) because at runtime many types are not registered with the importer and therefore the check below would be less reliable. That way, we have two behaviors only: editor and runtime, and not an in-between third one, that would make things unnecessarily complex.

**Review by akien-mga — APPROVED** [review]
Let's give this a spin for beta2, so we have some time to get it tested in `master` first (beta1 is imminent so I wouldn't risk potentially introducing a regression).

**Comment by Repiteo** [comment]
Thanks!
