### PR TITLE
GDScript: range function type check bug fixed

### LINKED ISSUE #43586: Issues with range() when not using static typed variables
**Godot version:**
Current 4.0 master

**OS/device including version:**
Win10

**Issue description:**
When using a non static typed variable, the range function will throw an error if the variable is altered before using the range function.

**Steps to reproduce:**

eg. 

```
var t = 10

func _ready():
    t = 20
    for i in range(t):
        print(str(i))

```

will give the error "Invalid argument for "range()" call. Argument 1 should be int or float but "variant" was given

If I declare t as an int, I no longer get the error. Likewise if I don't alter the variable with t = 20, then the code runs.
As you would imagine, this type of code runs fine in 3.2.
Seems that the combination of no type hinting and altering a variable before using range, is where the bug lies.

Also having the same issue when doing something like this:

```
var pool = get_tree().get_nodes_in_group("enemy").get_children()
for i in range(pool.size()):
   # do stuff
```

Once again, I can get around this by changing this to:
```
var pool = get_tree().get_nodes_in_group("enemy").get_children()
var pool_size: int = pool.size()
for i in range(pool_size):
   # do stuff
```

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #43586

### CODE REVIEW

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -983,12 +983,14 @@ void GDScriptAnalyzer::resolve_for(GDScriptParser::ForNode *p_for) {
...
-							all_is_constant = false;
-							push_error(vformat(R"*(Invalid argument for "range()" call. Argument %d should be int or float but "%s" was given.)*", i + 1, arg_type.to_string()), call->arguments[i]);
-						} else if (arg_type.builtin_type != Variant::INT && arg_type.builtin_type != Variant::FLOAT) {
-							all_is_constant = false;
-							push_error(vformat(R"*(Invalid argument for "range()" call. Argument %d should be int or float but "%s" was given.)*", i + 1, arg_type.to_string()), call->arguments[i]);
+						if (!arg_type.is_variant()) {
+							if (arg_type.kind != GDScriptParser::DataType::BUILTIN) {
+								all_is_constant = false;
+								push_error(vformat(R"*(Invalid argument for "range()" call. Argument %d should be int or float but "%s" was given.)*", i + 1, arg_type.to_string()), call->arguments[i]);
+							} else if (arg_type.builtin_type != Variant::INT && arg_type.builtin_type != Variant::FLOAT) {
```
Comment (Anutrix) [inline modules/gdscript/gdscript_analyzer.cpp:990]: Both if and else blocks do the exact same thing.
