### PR TITLE
Disable the OK button until a node is selected.

### LINKED ISSUE #62893: Add Method Track can be accepted immediately and will just do nothing
### Godot version

d26442e

### System information

Windows 10 x64

### Issue description

godot_Ta4CY1X5bO
The OK button should be disabled until a node is selected.

### Steps to reproduce

1. Add AnimationPlayer and Animation
2. Click Add Track -> Add Method Track
3. Just press OK without touching anything else

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by garychia**
Fixes #62893.
The OK button of SceneTreeDialog is disabled until a node is selected
OK_Disabled
OK_Enabled
.

### CODE REVIEW

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1359,6 +1359,10 @@ void SceneTreeDialog::_select() {
 	}
 }
 
+void SceneTreeDialog::_selected_changed() {
+	get_ok_button()->set_disabled(tree->get_selected() == nullptr);
```
Comment (KoBeWi) [inline editor/scene_tree_editor.cpp:1363]:
```suggestion
	get_ok_button()->set_disabled(!tree->get_selected());
```
I'd write it like that, but whichever style is ok.

**Review by KoBeWi — APPROVED** [review]

**Comment by KoBeWi** [comment]
You need to squash the commits.
Also you accepted my suggestion, which automatically added me as co-author; you should remove that.
Also also, if you are changing the style, the other condition needs a change too.

**Comment by garychia** [comment]
I tried to fix the issues you mentioned. But I'm not sure if this is the right thing to do with the commits. Thanks for your suggestion.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.
