### PR TITLE
Fix unsent WINDOW_EVENT_MOUSE_ENTER event on mouse_mode-change

### LINKED ISSUE #64438: mouse_entered signal is not working if mouse mode has been set to MOUSE_MODE_CAPTURED when mouse is outside the window
### Godot version

4.0.dev 49ac05550e4ce3b3489fad0a2addd907af1f5898

### System information

Ubuntu 22.04, 6700xt

### Issue description

When mouse is outside the window when `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)` is called, then after calling Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE) GUI is not behaving properly (it has no idea that mouse is hovering over them) and some signals like `mouse_entered`/`mouse_exited` are not called. 

https://user-images.githubusercontent.com/6129594/184652538-00145e90-497b-45bb-b7db-d221ba1b1517.mp4

### Steps to reproduce

1. Create new project
2. In ready add 
```
    await(get_tree().create_timer(5).timeout)
    Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
```
3. Add also
```
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
```
4. Add two buttons to the main scene of the project
5. Start the project, move your mouse outside the window
6. When mouse gets captured click 'escape'
7. Ensure to not move mouse outside the window at any point from now on
8. Click one of the buttons, note that they are not highlighting when mouse is hovering over them

Alternative is to get reproduction project and follow steps from video attached above

### Minimal reproduction project

[MouseOverIssue.zip](https://github.com/godotengine/godot/files/9337775/MouseOverIssue.zip)

This investigation was kindly sponsored by The Mirror

### PR DESCRIPTION
**Pull request by Sauermann**
On linuxbsd and macOS the `WINDOW_EVENT_MOUSE_ENTER` was not sent, when the mouse became visible again after a `mouse_mode`-change.

coauthor: @bruvzg

This change make the linuxbsd&macOS-display-server consistent with the windows-display-server, which does send `WINDOW_EVENT_MOUSE_ENTER`.

fix #64438
supersedes #64492

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
It's not sent on macOS as well (so needs the same fix in the `mouse_set_mode`).

**Comment by Sauermann** [comment]
I am a bit reluctant to change macOS-platform-code, since I can't test it.

**Comment by bruvzg** [comment]
The same code seems to be working fine on macOS:

```diff
diff --git a/platform/macos/display_server_macos.mm b/platform/macos/display_server_macos.mm
index 33d8a8dd14..8b596379a0 100644
--- a/platform/macos/display_server_macos.mm
+++ b/platform/macos/display_server_macos.mm
@@ -1843,11 +1843,22 @@ void DisplayServerMacOS::mouse_set_mode(MouseMode p_mode) {
 		window_id = MAIN_WINDOW_ID;
 	}
 	WindowData &wd = windows[window_id];
+
+	bool show_cursor = (p_mode == MOUSE_MODE_VISIBLE || p_mode == MOUSE_MODE_CONFINED);
+	bool previously_shown = (mouse_mode == MOUSE_MODE_VISIBLE || mouse_mode == MOUSE_MODE_CONFINED);
+
+	if (show_cursor && !previously_shown) {
+		WindowID window_id = get_window_at_screen_position(mouse_get_position());
+		if (window_id != INVALID_WINDOW_ID) {
+			send_window_event(windows[window_id], WINDOW_EVENT_MOUSE_ENTER);
+		}
+	}
+
 	if (p_mode == MOUSE_MODE_CAPTURED) {
 		// Apple Docs state that the display parameter is not used.
 		// "This parameter is not used. By default, you may pass kCGDirectMainDisplay."
 		// https://developer.apple.com/library/mac/documentation/graphicsimaging/reference/Quartz_Services_Ref/Reference/reference.html
-		if (mouse_mode == MOUSE_MODE_VISIBLE || mouse_mode == MOUSE_MODE_CONFINED) {
+		if (previously_shown) {
 			CGDisplayHideCursor(kCGDirectMainDisplay);
 		}
 		CGAssociateMouseAndMouseCursorPosition(false);
@@ -1858,7 +1869,7 @@ void DisplayServerMacOS::mouse_set_mode(MouseMode p_mode) {
 		CGPoint lMouseWarpPos = { pointOnScreen.x, CGDisplayBounds(CGMainDisplayID()).size.height - pointOnScreen.y };
 		CGWarpMouseCursorPosition(lMouseWarpPos);
 	} else if (p_mode == MOUSE_MODE_HIDDEN) {
-		if (mouse_mode == MOUSE_MODE_VISIBLE || mouse_mode == MOUSE_MODE_CONFINED) {
+		if (previously_shown) {
 			CGDisplayHideCursor(kCGDirectMainDisplay);
 		}
 		[wd.window_object setMovable:YES];
@@ -1868,7 +1879,7 @@ void DisplayServerMacOS::mouse_set_mode(MouseMode p_mode) {
 		[wd.window_object setMovable:NO];
 		CGAssociateMouseAndMouseCursorPosition(false);
 	} else if (p_mode == MOUSE_MODE_CONFINED_HIDDEN) {
-		if (mouse_mode == MOUSE_MODE_VISIBLE || mouse_mode == MOUSE_MODE_CONFINED) {
+		if (previously_shown) {
 			CGDisplayHideCursor(kCGDirectMainDisplay);
 		}
 		[wd.window_object setMovable:NO];
@@ -1884,7 +1895,7 @@ void DisplayServerMacOS::mouse_set_mode(MouseMode p_mode) {
 	warp_events.clear();
 	mouse_mode = p_mode;
 
-	if (mouse_mode == MOUSE_MODE_VISIBLE || mouse_mode == MOUSE_MODE_CONFINED) {
+	if (show_cursor) {
 		cursor_update_shape();
 	}
 }
```

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 1]
```diff
@@ -377,6 +377,14 @@ void DisplayServerX11::mouse_set_mode(MouseMode p_mode) {
 
 	// The only modes that show a cursor are VISIBLE and CONFINED
 	bool showCursor = (p_mode == MOUSE_MODE_VISIBLE || p_mode == MOUSE_MODE_CONFINED);
```
Comment (bruvzg) [inline platform/linuxbsd/x11/display_server_x11.cpp:379]:
```suggestion
	bool show_cursor = (p_mode == MOUSE_MODE_VISIBLE || p_mode == MOUSE_MODE_CONFINED);
```

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 2]
```diff
@@ -377,6 +377,14 @@ void DisplayServerX11::mouse_set_mode(MouseMode p_mode) {
...
+	bool previously_shown = (mouse_mode == MOUSE_MODE_VISIBLE || mouse_mode == MOUSE_MODE_CONFINED);
+
+	if (showCursor && !previously_shown) {
```
Comment (bruvzg) [inline platform/linuxbsd/x11/display_server_x11.cpp:382]:
```suggestion
	if (show_cursor && !previously_shown) {
```

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 3]
```diff
@@ -377,6 +377,14 @@ void DisplayServerX11::mouse_set_mode(MouseMode p_mode) {
...
+		WindowID window_id = get_window_at_screen_position(mouse_get_position());
+		if (window_id != INVALID_WINDOW_ID) {
+			_send_window_event(windows[window_id], WINDOW_EVENT_MOUSE_ENTER);
+		}
+	}
 
 	for (const KeyValue<WindowID, WindowData> &E : windows) {
 		if (showCursor) {
```
Comment (bruvzg) [inline platform/linuxbsd/x11/display_server_x11.cpp:390]:
```suggestion
		if (show_cursor) {
```

**Comment by Sauermann** [comment]
@bruvzg thanks, I have included your patch in the PR.

**Review by bruvzg — APPROVED** [review]

File: platform/linuxbsd/x11/display_server_x11.cpp (hunk 1 above)
Comment (Sauermann) [reply platform/linuxbsd/x11/display_server_x11.cpp]: From the time before the variable-naming-convention. I have changed it. Thanks!

**Comment by akien-mga** [comment]
Thanks!
