### PR TITLE
Fix VECTOR/LOCAL transitions in Node3D

### LINKED ISSUE #62225: Rotation is not applied on scene load, if rotation_edit_mode is set to Quaternion.
### Godot version

4.0 Alpha 10

### System information

Archlinux, KDE X11

### Issue description

If a node has rotation_edit_mode set to Quaternion, then its rotation is either not loaded when loading its parent scene, or saved incorrectly. When set to Euler angles it works correctly.

### Steps to reproduce

- Create a new 3D scene, add to it any rotatable 3D node
- Rotate the node in some way
- Save the scene, and then reload it
    - Rotation is loaded correctly
- Set Rotation Edit Mode to Quaternion on the node
- Save the scene and reload it
    - Rotation is reset to the default value.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by reduz**
The update logic for both vector and local when the other is dirty was broken, this should fix it. Additionally, Basis had broken functions interacting with this code which was corrected.

Additionally, the behavior is better documented in the header file.

Fixes #62225, supersedes #62227

### CODE REVIEW

File: scene/3d/node_3d.h [hunk 1]
```diff
@@ -68,20 +71,36 @@ class Node3D : public Node {
 	};
 
 private:
+	// For the sake of ease of use, Node3D can operate with Transforms (Basis+Origin), Quaterinon/Scale and Euler Rotation/Scale
+	// Transform and Quaterinon are stored in data.local_transform Basis (so quaternion is not really stored, but converted back/fortm from 3x3 matrix on demand).
```
Comment (Logharaa) [inline scene/3d/node_3d.h:75]: Typo on "back/forth"

Comment (reduz) [reply scene/3d/node_3d.h:75]: Thanks!

File: scene/3d/node_3d.cpp [hunk 2]
```diff
@@ -333,52 +343,51 @@ Node3D::RotationEditMode Node3D::get_rotation_edit_mode() const {
...
 		notification(NOTIFICATION_LOCAL_TRANSFORM_CHANGED);
 	}
 }
 
 void Node3D::set_scale(const Vector3 &p_scale) {
-	if (data.dirty & DIRTY_VECTORS) {
-		data.rotation = data.local_transform.basis.get_euler_normalized(data.rotation_order);
-		data.dirty &= ~DIRTY_VECTORS;
+	if (data.dirty & DIRTY_EULER_ROTATION_AND_SCALE) {
+		// Update rotation only if vectors are dirty, as scale will be override.
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:384]:
```suggestion
		// Update rotation only if vectors are dirty, as scale will be overridden.
```

File: scene/3d/node_3d.cpp [hunk 3]
```diff
@@ -85,12 +85,20 @@ void Node3D::_notify_dirty() {
 }
 
 void Node3D::_update_local_transform() const {
-	if (this->get_rotation_edit_mode() != ROTATION_EDIT_MODE_BASIS) {
-		data.local_transform = data.local_transform.orthogonalized();
-	}
-	data.local_transform.basis.set_euler_scale(data.rotation, data.scale);
+	// This function is called when the local transform (data.local_transform) is dirty and the right value is contained in the euler vector
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:88]: Nitpicks but while at it, let's get comment style right/consistent:
```suggestion
	// This function is called when the local transform (data.local_transform) is dirty and the right value is contained in the Euler vector.
```

File: scene/3d/node_3d.cpp [hunk 4]
```diff
@@ -85,12 +85,20 @@ void Node3D::_notify_dirty() {
...
+
+	data.local_transform.basis.set_euler_scale(data.euler_rotation, data.scale, data.euler_rotation_order);
 
-	data.dirty &= ~DIRTY_LOCAL;
+	data.dirty &= ~DIRTY_LOCAL_TRANSFORM;
+}
+
+void Node3D::_update_rotation_and_scale() const {
+	// This function is called when the euler rotation (data.euler_rotation) is dirty and the right value is contained in the local transform
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:96]:
```suggestion
	// This function is called when the Euler rotation (data.euler_rotation) is dirty and the right value is contained in the local transform.
```

File: scene/3d/node_3d.cpp [hunk 5]
```diff
@@ -137,12 +145,12 @@ void Node3D::_notification(int p_what) {
 			if (data.top_level && !Engine::get_singleton()->is_editor_hint()) {
 				if (data.parent) {
 					data.local_transform = data.parent->get_global_transform() * get_transform();
-					data.dirty = DIRTY_VECTORS; //global is always dirty upon entering a scene
+					data.dirty = DIRTY_EULER_ROTATION_AND_SCALE; // As local transform was updated, vectors should be dirty
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:148]:
```suggestion
					data.dirty = DIRTY_EULER_ROTATION_AND_SCALE; // As local transform was updated, vectors should be dirty.
```

File: scene/3d/node_3d.cpp [hunk 6]
```diff
@@ -137,12 +145,12 @@ void Node3D::_notification(int p_what) {
...
 				}
 				data.top_level_active = true;
 			}
 
-			data.dirty |= DIRTY_GLOBAL; //global is always dirty upon entering a scene
+			data.dirty |= DIRTY_GLOBAL_TRANSFORM; //global is always dirty upon entering a scene
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:153]:
```suggestion
			data.dirty |= DIRTY_GLOBAL_TRANSFORM; // Global is always dirty upon entering a scene.
```

File: scene/3d/node_3d.cpp [hunk 7]
```diff
@@ -217,7 +225,8 @@ void Node3D::set_quaternion(const Quaternion &p_quaternion) {
 
 void Node3D::set_transform(const Transform3D &p_transform) {
 	data.local_transform = p_transform;
-	data.dirty |= DIRTY_VECTORS;
+	data.dirty = DIRTY_EULER_ROTATION_AND_SCALE; // Make vectors dirty
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:228]:
```suggestion
	data.dirty = DIRTY_EULER_ROTATION_AND_SCALE; // Make vectors dirty.
```

File: scene/3d/node_3d.cpp [hunk 8]
```diff
@@ -333,52 +343,51 @@ Node3D::RotationEditMode Node3D::get_rotation_edit_mode() const {
...
 
 Node3D::RotationOrder Node3D::get_rotation_order() const {
-	return RotationOrder(data.rotation_order);
+	return RotationOrder(data.euler_rotation_order);
 }
 
 void Node3D::set_rotation(const Vector3 &p_euler_rad) {
-	if (data.dirty & DIRTY_VECTORS) {
+	if (data.dirty & DIRTY_EULER_ROTATION_AND_SCALE) {
+		// Update scale only if vectors are dirty, as rotation will be overriden.
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:369]: FYI, that's a typo you always seem to make, your other kryptonite together with "threshold" :P
`overridden` takes two d's, even though `override` is a single d.
```suggestion
		// Update scale only if vectors are dirty, as rotation will be overridden.
```

File: scene/3d/node_3d.h [hunk 9]
```diff
@@ -52,6 +52,9 @@ class Node3D : public Node {
 	GDCLASS(Node3D, Node);
 
 public:
+	// Edit mode for the rotation
+	// THIS MODE ONLY AFFECTS HOW DATA IS EDITED AND SAVED
+	// IT DOES _NOT_ AFFECT THE TRANSFORM LOGIC (see comment in TransformDirty).
```
Comment (akien-mga) [inline scene/3d/node_3d.h:57]:
```suggestion
	// Edit mode for the rotation.
	// THIS MODE ONLY AFFECTS HOW DATA IS EDITED AND SAVED.
	// IT DOES _NOT_ AFFECT THE TRANSFORM LOGIC (see comment in TransformDirty).
```

File: scene/3d/node_3d.h [hunk 10]
```diff
@@ -68,20 +71,36 @@ class Node3D : public Node {
 	};
 
 private:
+	// For the sake of ease of use, Node3D can operate with Transforms (Basis+Origin), Quaterinon/Scale and Euler Rotation/Scale
```
Comment (akien-mga) [inline scene/3d/node_3d.h:74]:
```suggestion
	// For the sake of ease of use, Node3D can operate with Transforms (Basis+Origin), Quaterinon/Scale and Euler Rotation/Scale.
```

File: scene/3d/node_3d.h [hunk 11]
```diff
@@ -68,20 +71,36 @@ class Node3D : public Node {
...
+	// Transform and Quaterinon are stored in data.local_transform Basis (so quaternion is not really stored, but converted back/fortm from 3x3 matrix on demand).
+	// Euler needs to be kept separate because converting to Basis and back may result in a different vector (which is troublesome for users
+	// editing in the inspector, not only because of the numerical precision loss but because they expects these rotations to be consistent, or support
```
Comment (akien-mga) [inline scene/3d/node_3d.h:77]:
```suggestion
	// editing in the inspector, not only because of the numerical precision loss but because they expect these rotations to be consistent, or support
```

File: scene/3d/node_3d.h [hunk 12]
```diff
@@ -68,20 +71,36 @@ class Node3D : public Node {
...
+	// "redundant" rotations for animation interpolation, like going from 0 to 720 degrees).
+	//
+	// As such, the system works in a way where if the local transform is set (via transform/basis/quaternion), the EULER rotation and scale becomes dirty.
+	// It will remain dirty until reading back is attempted (for performance reasons). Likewise, if the euler rotation scale are set, the local transform
```
Comment (akien-mga) [inline scene/3d/node_3d.h:81]:
```suggestion
	// It will remain dirty until reading back is attempted (for performance reasons). Likewise, if the Euler rotation scale are set, the local transform
```

File: scene/3d/node_3d.h [hunk 13]
```diff
@@ -68,20 +71,36 @@ class Node3D : public Node {
...
+	// will become dirty (and again, will not become valid again until read).
+	//
+	// All this is transparent from outside the Node3D API, which allows everything to works by calling these functions in exchange.
+	//
+	// Additionally, setting either transform, quaternion, euler rotation or scale makes the global transform dirty, which will be updated when read again.
```
Comment (akien-mga) [inline scene/3d/node_3d.h:86]:
```suggestion
	// Additionally, setting either transform, quaternion, Euler rotation or scale makes the global transform dirty, which will be updated when read again.
```

File: scene/3d/node_3d.h [hunk 14]
```diff
@@ -68,20 +71,36 @@ class Node3D : public Node {
...
+	//
+	// NOTE: Again, RotationEditMode is _independent_ of this mechanism, it is only meant to expose the right set of properties for editing (editor) and saving (to scene,
+	// in order to keep the same values and avoid data loss on conversions). It has zero injerence on the logic described above.
```
Comment (akien-mga) [inline scene/3d/node_3d.h:89]:
```suggestion
	// NOTE: Again, RotationEditMode is _independent_ of this mechanism, it is only meant to expose the right set of properties for editing (editor) and saving
	// (to scene, in order to keep the same values and avoid data loss on conversions). It has zero interference on the logic described above.
```

**Review by akien-mga — COMMENTED** [review]
Comments review.

File: scene/3d/node_3d.cpp (hunk 2 above)
Comment (reduz) [reply scene/3d/node_3d.cpp:384]: thanks!

**Comment by TokageItLab** [comment]
After a shear is caused by BasisMode, if RotationEditMode is changed to Quaternion or Euler, the shear remains. Orthogonalization is required when changing the mode.

In addition, errors frequently occur in Quaternion mode.
```
ERROR: Basis must be normalized in order to be casted to a Quaternion. Use get_rotation_quaternion() or call orthonormalized() if the Basis contains linearly independent vectors.
   at: (core\math\basis.cpp:718)
```

**Comment by reduz** [comment]
@TokageItLab Not sure what you mean by shear, but did some further fixes so make sure to try again.

**Comment by TokageItLab** [comment]
The problem of the frequent Quaternion errors has been resolved.

In Basis mode, local shearing is allowed. However, in Quaternion and Euler modes, shear is forced to be orthogonalized during transformation and should be orthogonalized when changing modes, since currently the following implicit and abrupt orthogonalization is done, which is uncomfortable:

https://user-images.githubusercontent.com/61938263/175789345-a2392088-f5ab-4a3a-bffd-0e2e557eb4c8.mp4

One way to do this would be to call `_update_local_transform()` when changing modes.

However, `data.euler_rotation` and `data.scale` are not recorded in the `.tscn` file when the scene is saved. This causes `data.euler_rotation` and `data.scale` to have initial values when the scene is loaded, which causes problem #62225 which is a mistake I have made in #53684.

File: scene/3d/node_3d.cpp [hunk 15]
```diff
@@ -314,13 +342,14 @@ void Node3D::set_rotation_edit_mode(RotationEditMode p_mode) {
...
-	data.dirty |= DIRTY_LOCAL;
-	_propagate_transform_changed(this);
-	if (data.notify_local_transform) {
-		notification(NOTIFICATION_LOCAL_TRANSFORM_CHANGED);
+	if (p_mode == ROTATION_EDIT_MODE_EULER && (data.dirty & DIRTY_EULER_ROTATION_AND_SCALE)) {
+		// If going to Euler mode, ensure that vectors are _not_ dirty, else the retrieved value may be wrong.
+		// Otherwise keep what is there, so switching back and forth between modes does not break the vectors.
+
+		_update_rotation_and_scale();
 	}
```
Comment (TokageItLab) [inline scene/3d/node_3d.cpp:354]:
```suggestion
	if (p_mode != ROTATION_EDIT_MODE_BASIS) {
		data.local_transform.orthogonalize();
		_propagate_transform_changed(this);
		if (data.notify_local_transform) {
			notification(NOTIFICATION_LOCAL_TRANSFORM_CHANGED);
		}
	}
```
So, at a minimum, I suggest that such an implementation is required.

File: scene/3d/node_3d.cpp [hunk 16]
```diff
@@ -314,13 +342,14 @@ void Node3D::set_rotation_edit_mode(RotationEditMode p_mode) {
 	if (data.rotation_edit_mode == p_mode) {
 		return;
 	}
+
 	data.rotation_edit_mode = p_mode;
```
Comment (TokageItLab) [inline scene/3d/node_3d.cpp:347]:
```suggestion
	if (p_mode != ROTATION_EDIT_MODE_BASIS) {
		data.local_transform.orthogonalize();
		_propagate_transform_changed(this);
		if (data.notify_local_transform) {
			notification(NOTIFICATION_LOCAL_TRANSFORM_CHANGED);
		}
	}
```
So, at a minimum, I think that an implementation like this is needed.

Comment (TokageItLab) [inline scene/3d/node_3d.cpp:347]:
```suggestion
	if (p_mode != ROTATION_EDIT_MODE_BASIS) {
		data.local_transform.orthogonalize();
		_propagate_transform_changed(this);
		if (data.notify_local_transform) {
			notification(NOTIFICATION_LOCAL_TRANSFORM_CHANGED);
		}
	}
```
So, at a minimum, I think that an implementation like this is needed.

**Comment by TokageItLab** [comment]
Is it okay to save something with Euler 720 degree and when you load the scene it becomes Euler 0 degree? .tscn does not save the euler value directly, so when you load the scene it is forced to convert from Basis.
Otherwise it looks good.

**Comment by reduz** [comment]
@TokageItLab Hmm you are right, let me see if I can do this a bit different, otherwise the order of properties becomes the problem.

**Comment by reduz** [comment]
@TokageItLab okay I guess it should be ok now.

**Review by TokageItLab — APPROVED** [review]
As a result, 720-degree objects are loaded as 0 degrees, but that may not be much of a problem for now, since it is a special case that requires out-of-range angles. At least for animation, just set those angles for initial frames, idle animation or etc.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
