### PR TITLE
[Android export] Added validation of the project name when using $genname in the 'Unique Name' field.

### LINKED ISSUE #71645: [Android] Implicit conversion of the package name when exporting for Android with using "$genname" for project name starting with invalid characters.
### Godot version

3.5.1.stable, v4.0.beta.custom_build [0a87ead64]

### System information

Ubuntu 22.04.1

### Issue description

For example, if project has name "300spartans", we can't enter the "org.godotengine.300spartans" to "Unique Name" field. We get the error "Invalid package name: A digit cannot be the first character in a package segment". But , if we enter "org.godotengine.$genname", there will be no error message. When exporting, the name will be set as "org.godotengine.spartans" without "300" in beginning, but user will not be informed about it. I think, it is not very good. It may not be worth making changes to the source code, but mention it in the documentation.

### Steps to reproduce

See issue description.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Vilcrow**
Fixes #71645.

### CODE REVIEW

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2382,6 +2387,16 @@ bool EditorExportPlatformAndroid::has_valid_project_configuration(const Ref<Edit
...
+	//Check package name when used $genname in the "Unique Name" field
+	String basename = GLOBAL_GET("application/config/name");
+	String name = get_valid_basename();
+	if (valid && pn.find("$genname") >= 0 && name != basename) {
+		String p_name = p_preset->get("package/unique_name");
+		String fn = get_package_name(p_name);  //The final package name
+		err += vformat(TTR("Invalid package name. Will be replaced with \"%s\" when exporting."), fn);
+		err += "\n";
+	}
+
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:2399]: There is a check above that already validates the package name, can this logic be added to it.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

File: platform/android/export/export_plugin.cpp (hunk 1 above)
Comment (Vilcrow) [reply platform/android/export/export_plugin.cpp:2399]: @m4gr3d if I do the check above, then the variable `valid` may then change to the `false`. Then this warning will be displayed in red font, which will be wrong. If the export is not possible, then this warning is not necessary.
Here I need to delete line number 2394 and replace `p_name` with `pn`.
This is my first pull request and I don't now how to do it yet, because I messed up something with the branches. I will try to figure it out.

Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp]: I think the warning should be turned into an error, in which case it's fine to merge the added logic with `is_package_name_valid`.

The reason for being an error is that a warning that doesn't block the user from progressing can easily be overlooked leading to confusion when the package name doesn't match with the unique name.
I'd rather the export dialog to be explicit to the user that the selected name is invalid.

Comment (m4gr3d) [reply platform/android/export/export_plugin.cpp]: As part of the error, we can suggest the user to manually overwrite the package name with a suitable replacement if they would like to keep the unique name.

**Comment by Vilcrow** [comment]
Fixed the commit history in this branch. It doesn't seem to have broken anything.

File: platform/android/export/export_plugin.cpp [hunk 2]
```diff
@@ -525,6 +530,22 @@ bool EditorExportPlatformAndroid::is_package_name_valid(const String &p_package,
...
+	return true;
+}
+
+bool EditorExportPlatformAndroid::is_project_name_valid(const String &p_package) const {
+	String basename = GLOBAL_GET("application/config/name");
+	basename = basename.to_lower();
+	if (basename != get_valid_basename()) {
+		return false;
+	}
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:548]: Looks good! Can you add a comment describing this logic.  Otherwise it could be easy for a contributor to not realize that `basename` may not be equal to `get_valid_basename()` and mistakenly remove this method.

File: platform/android/export/export_plugin.cpp [hunk 3]
```diff
@@ -525,6 +530,22 @@ bool EditorExportPlatformAndroid::is_package_name_valid(const String &p_package,
...
+		if (r_error) {
+			*r_error = TTR("The end result may be unexpected. Try to explicitly specify the project name instead of the '$genname'.");
+		}
+		return false;
+	}
+
+	return true;
+}
+
+bool EditorExportPlatformAndroid::is_project_name_valid(const String &p_package) const {
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:543]: The `p_package` parameter doesn't seem to be needed.

File: platform/android/export/export_plugin.cpp [hunk 4]
```diff
@@ -525,6 +530,22 @@ bool EditorExportPlatformAndroid::is_package_name_valid(const String &p_package,
 		return false;
 	}
 
+	if (p_package.find("$genname") >= 0 && !is_project_name_valid(p_package)) {
+		if (r_error) {
+			*r_error = TTR("The end result may be unexpected. Try to explicitly specify the project name instead of the '$genname'.");
```
Comment (m4gr3d) [inline platform/android/export/export_plugin.cpp:535]: Can you update the error message to:
`The project name does not meet the requirement for the package name format. Please explicitly specify the package name.`

**Review by m4gr3d — CHANGES_REQUESTED** [review]
Looks good! 

Added some comments to address before it's ready to merge.

File: platform/android/export/export_plugin.cpp (hunk 4 above)
Comment (Vilcrow) [reply platform/android/export/export_plugin.cpp]: Done.

**Review by m4gr3d — APPROVED** [review]
Looks great!

**Comment by Vilcrow** [comment]
@m4gr3d thanks.

File: platform/android/export/export_plugin.cpp [hunk 5]
```diff
@@ -437,6 +437,14 @@ String EditorExportPlatformAndroid::get_project_name(const String &p_name) const
 
 String EditorExportPlatformAndroid::get_package_name(const String &p_package) const {
 	String pname = p_package;
+	String name = get_valid_basename();
+	pname = pname.replace("$genname", name);
+	return pname;
+}
+
+//returns the project name without invalid characters
+//or the "noname" string if all characters are invalid
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:446]: Our comment style is full sentences (with capital letter and period), and space after `//`.
```suggestion
// Returns the project name without invalid characters
// or the "noname" string if all characters are invalid.
```
Applies to the other comments below.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
