### PR TITLE
Fix icons for custom types in the recent & favorites lists in the create dialog

### LINKED ISSUE #10917: Custom types added via EditorPlugin do not have their imported image listed under "Recent" when selecting a node
Godot 3.0, Windows x64

The actual list will show it properly and the node hierarchy in Scene dock does, but in the Create New Node window, the bottom-left section labeled "Recent" does not use the imported image and defaults to a white box.

Check out the icons for "HoverContainer" as a comparison in the below screenshot:
this screenshot

### PR DESCRIPTION
**Pull request by ghost**
The imported image for custom types now shows for the recent and favourites lists in the create node dialog. Fixes #10917

Currently this is done by iterating over all the custom types for each icon which isn't found with has_icon. It may be better to do a lookup directly from custom type name to the custom type data, but i couldn't find a way to do this without introducing another map and doing a bit more book keeping.

### CODE REVIEW

**Comment by akien-mga** [comment]
cc @djrm @toger5.

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -122,6 +117,29 @@ void CreateDialog::_sbox_input(const Ref<InputEvent> &p_ie) {
 	}
 }
 
+Ref<Texture> CreateDialog::_get_editor_icon(const String &p_type) const {
+
+	if (has_icon(p_type, "EditorIcons")) {
+		return get_icon(p_type, "EditorIcons");
+	}
+
+	const Map<String, Vector<EditorData::CustomType> > &p_map = EditorNode::get_editor_data().get_custom_types();
```
Comment (djrm) [inline editor/create_dialog.cpp]: maybe just to avoid iterating over the map, you can also do:
```
String parent = ClassDB::get_parent_class(p_type);
const Vector<EditorData::CustomType> &ct = EditorNode::get_editor_data().get_custom_types()[parent];
// and then iterate

```

**Comment by djrm** [comment]
looks good, there is an optimization but this gets the job done.

**Comment by MillionOstrich** [comment]
@djrm I tried to get the ClassDB::get_parent_class call to work but it is only returning an empty string. I think this is because the ClassDB only holds information about native types (though i am not sure). I think i would need to access to the script to call get_instance_base_type() which is held in the same place as the icon.

After looking at the code further i could have a go at re-factoring how custom types are stored and registered a bit. In Particular i am considering the following:
- removing the p_inherits field from the EditorData::add_custom_type and determining it from the script
- associating the custom types by name to the custom type data (rather than by parent), which would make the icon lookup a easier.

But perhaps these changes would be best made a separate pull request?
