### PR TITLE
Fix `GDScript::reload` leaving `reloading` as `true` on failure

### LINKED ISSUE #107869: `GDScript::reload` leaves `reloading` as `true` when `ERR_FAIL_COND_V` macro exits early
### Tested versions

- Reproducible in: 4.5-beta1, 4.4.1-stable, 4.3-stable, 4.2-stable

### System information

Tested OS: Ubuntu (headless server), Linux Mint

### Issue description

The function `GDScript::reload` performs the check `ERR_FAIL_COND_V(!p_keep_state && has_instances, ERR_ALREADY_IN_USE);` after setting `reloading = true;` which can exit the function early without resetting `reloading = false;` which leaves the `GDScript` object in an unreloadable state.

### Steps to reproduce

1. Create a `GDScript` object "`script`".
2. Provide valid source code "A" to `script.source_code` and call `script.reload()`.
3. Instantiate an object "`custom_a`" with `script.new()`.
4. While `custom_a` is still valid, provide valid source code "B" to `script.source_code` and call `script.reload()`.
5. As `script`'s previously created object `custom_a` is still valid, it cannot reload and returns `ERR_ALREADY_IN_USE`, but erroneously leaves `script.reloading` as `true`.
6. `script` is now in a state where it can never be reloaded. Calling `script.reload()` again, it now returns `OK`, but does not reload the script.
  - Calling `script.new()` from this point on will still create instances from source code "A", despite `script.reload()` appearing successful.

### Minimal reproduction project (MRP)

[Minimal reproduction script in browser](https://gdscript.live/?script=Y29uc3QgU0NSSVBUX1NPVVJDRV9BIDo9IFwKCSAgImNsYXNzX25hbWUgQ3VzdG9tQSBleHRlbmRzIE5vZGVcbiIgXAoJKyAidmFyIGkgOj0gNDJcbiIKCmNvbnN0IFNDUklQVF9TT1VSQ0VfQiA6PSBcCgkgICJjbGFzc19uYW1lIEN1c3RvbUIgZXh0ZW5kcyBOb2RlXG4iIFwKCSsgInZhciBmIDo9IDMuMTRcbiIKCmZ1bmMgbWFpbigpIC0%2BIHZvaWQ6Cgl2YXIgY3VzdG9tX3NjcmlwdCA6PSBHRFNjcmlwdC5uZXcoKQoKCWN1c3RvbV9zY3JpcHQuc291cmNlX2NvZGUgPSBTQ1JJUFRfU09VUkNFX0EKCXByaW50KCJSZWxvYWRpbmcgU0NSSVBUX1NPVVJDRV9BIikKCXByaW50KGVycm9yX3N0cmluZyhjdXN0b21fc2NyaXB0LnJlbG9hZCgpKSkgIyBPSwoKCXZhciBjdXN0b21fYSA9IGN1c3RvbV9zY3JpcHQubmV3KCkKCXByaW50KGN1c3RvbV9hLmkpICMgNDIKCWN1c3RvbV9hLmkgPSAzMDAKCXByaW50KGN1c3RvbV9hLmkpICMgMzAwCgoJY3VzdG9tX3NjcmlwdC5zb3VyY2VfY29kZSA9IFNDUklQVF9TT1VSQ0VfQgoJcHJpbnQoIlxuUmVsb2FkaW5nIFNDUklQVF9TT1VSQ0VfQiIpCgkjIEZhaWxzIGJlY2F1c2UgYGN1c3RvbV9hYCBzdGlsbCBsaXZlcwoJcHJpbnQoZXJyb3Jfc3RyaW5nKGN1c3RvbV9zY3JpcHQucmVsb2FkKCkpKSAjIEFscmVhZHkgaW4gdXNlCgoJIyBDYWxsaW5nIGEgc2Vjb25kIHRpbWUsIGByZWxvYWRpbmdgIGlzIHN0aWxsIGB0cnVlYCwKCSMgc28gYEdEU2NyaXB0OjpyZWxvYWQoKWAgZXhpdHMgZWFybHkgd2l0aCBhbiBgT0tgCglwcmludCgiXG5SZWxvYWRpbmcgU0NSSVBUX1NPVVJDRV9CIGEgc2Vjb25kIHRpbWUiKQoJcHJpbnQoZXJyb3Jfc3RyaW5nKGN1c3RvbV9zY3JpcHQucmVsb2FkKCkpKSAjIE9LCgkjIE9uZSB3b3VsZCBhc3N1bWUgaGVyZSBgY3VzdG9tX3NjcmlwdGAgY29udGFpbnMgYSB2YWxpZCBzY3JpcHQKCSMgd2l0aCBgU0NSSVBUX1NPVVJDRV9CYCwgYnV0IGl0IGFjdHVhbGx5IGlzIHN0aWxsIG9wZXJhdGluZwoJIyB3aXRoIGBTQ1JJUFRfU09VUkNFX0FgCglwcmludCgiY3VzdG9tX3NjcmlwdC5jYW5faW5zdGFudGlhdGUoKTogIiwgY3VzdG9tX3NjcmlwdC5jYW5faW5zdGFudGlhdGUoKSkgIyB0cnVlCgl2YXIgY3VzdG9tX2IgPSBjdXN0b21fc2NyaXB0Lm5ldygpCglwcmludCgiY3VzdG9tX2IuZiA9ICIsIGN1c3RvbV9iLmdldCgmImYiKSkgIyA8bnVsbD4KCXByaW50KCJjdXN0b21fYi5pID0gIiwgY3VzdG9tX2IuZ2V0KCYiaSIpKSAjIDQyCgoJY3VzdG9tX2EuZnJlZSgpCgljdXN0b21fYi5mcmVlKCkK&godot_version=4.5-beta1)

```gdscript
const SCRIPT_SOURCE_A := \
	  "class_name CustomA extends Node\n" \
	+ "var i := 42\n"

const SCRIPT_SOURCE_B := \
	  "class_name CustomB extends Node\n" \
	+ "var f := 3.14\n"

func main() -> void:
	var custom_script := GDScript.new()

	custom_script.source_code = SCRIPT_SOURCE_A
	print("Reloading SCRIPT_SOURCE_A")
	print(error_string(custom_script.reload())) # OK

	var custom_a = custom_script.new()
	print(custom_a.i) # 42
	custom_a.i = 300
	print(custom_a.i) # 300

	custom_script.source_code = SCRIPT_SOURCE_B
	print("\nReloading SCRIPT_SOURCE_B")
	# Fails because `custom_a` still lives
	print(error_string(custom_script.reload())) # Already in use

	# Calling a second time, `reloading` is still `true`,
	# so `GDScript::reload()` exits early with an `OK`
	print("\nReloading SCRIPT_SOURCE_B a second time")
	print(error_string(custom_script.reload())) # OK
	# One would assume here `custom_script` contains a valid script
	# with `SCRIPT_SOURCE_B`, but it actually is still operating
	# with `SCRIPT_SOURCE_A`
	print("custom_script.can_instantiate(): ", custom_script.can_instantiate()) # true
	var custom_b = custom_script.new()
	print("custom_b.f = ", custom_b.get(&"f")) # <null>
	print("custom_b.i = ", custom_b.get(&"i")) # 42

	custom_a.free()
	custom_b.free()

```

### PR DESCRIPTION
**Pull request by archhabra**
Added the fix for https://github.com/godotengine/godot/issues/107869

### CODE REVIEW

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -755,7 +755,11 @@ Error GDScript::reload(bool p_keep_state) {
 		has_instances = instances.size();
 	}
 
-	ERR_FAIL_COND_V(!p_keep_state && has_instances, ERR_ALREADY_IN_USE);
+	// Check condition but reset flag before early return
+    if (!p_keep_state && has_instances) {
+        reloading = false;  // Reset flag before returning
+        return ERR_ALREADY_IN_USE;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp]: This change removes an informative error print, there should be an `ERR_FAIL_V_MSG` here instead with a good message

Comment (archhabra) [reply modules/gdscript/gdscript.cpp]: Updated the code

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -755,7 +755,12 @@ Error GDScript::reload(bool p_keep_state) {
 		has_instances = instances.size();
 	}
 
-	ERR_FAIL_COND_V(!p_keep_state && has_instances, ERR_ALREADY_IN_USE);
+	// Check condition but reset flag before early return
+	if (!p_keep_state && has_instances) {
+		reloading = false; // Reset flag before returning
+
+		ERR_FAIL_V_MSG(ERR_ALREADY_IN_USE, "Cannot reload script while instances exist");
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp]:
```suggestion
		ERR_FAIL_V_MSG(ERR_ALREADY_IN_USE, "Cannot reload script while instances exist.");
```

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -755,7 +755,12 @@ Error GDScript::reload(bool p_keep_state) {
...
+	}
```
Comment (dalexeev) [inline modules/gdscript/gdscript.cpp]:
```suggestion
	// Check condition but reset flag before early return.
	if (!p_keep_state && has_instances) {
		reloading = false; // Reset flag before returning.

		ERR_FAIL_V_MSG(ERR_ALREADY_IN_USE, "Cannot reload script while instances exist.");
	}
```

**Review by dalexeev — APPROVED** [review]
Looks good to me.

**Comment by Repiteo** [comment]
Could you squash the commits? See our PR workflow documentation for details: https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase

**Comment by archhabra** [comment]
> Could you squash the commits? See our PR workflow documentation for details: https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase

Done

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
