### PR TITLE
Increase precision of RAW mode in ColorPicker

### LINKED ISSUE #82514: Color value changes on update of alpha values in color Editor
### Godot version

4.2.dev.5

### System information

Windows 11

### Issue description

After entering the color value if you update the alpha value in raw section of color editor as shown in the video. the color value changes in the RGB text field.

### Steps to reproduce

https://github.com/godotengine/godot/assets/84369217/52ea6bec-b2ec-47ee-a9be-852236eeeada

Notice in the video after entering the alpha as 0.8 the color value changed from #484848 to #474747 

Apologies for tumbling in entering the value in the video as it is another issue https://github.com/godotengine/godot/issues/73926

### Minimal reproduction project

N.A

### PR DESCRIPTION
**Pull request by Calinou**
This sets the slider step to `0.001` but keeps SpinBox arrow increments at `0.01`.

Thanks @axu-ap for the suggested fix :slightly_smiling_face: 

- This closes https://github.com/godotengine/godot/issues/82514.

## Preview

https://github.com/godotengine/godot/assets/180032/e7d9c875-b929-4e0c-a6e3-493b19800ef5

### CODE REVIEW

**Review by fire — APPROVED** [review]
Preserving the precision is a good goal.

**Comment by aXu-AP** [comment]
Just as I imagined it 👍

File: scene/gui/color_mode.h [hunk 1]
```diff
@@ -43,6 +43,7 @@ class ColorMode {
 
 	virtual int get_slider_count() const { return 3; };
 	virtual float get_slider_step() const = 0;
+	virtual float get_spinbox_arrow_step() const { return get_slider_step(); };
```
Comment (aXu-AP) [inline scene/gui/color_mode.h:46]: Could also be `const = 0;`

Comment (Calinou) [reply scene/gui/color_mode.h:46]: I was thinking it should have a default value so that individual color modes aren't required to implement this method.

Comment (aXu-AP) [reply scene/gui/color_mode.h:46]: 0 is the default value for SpinBox.custom_arrow_step, it will be ignored. From [docs](https://docs.godotengine.org/en/stable/classes/class_spinbox.html#class-spinbox-property-custom-arrow-step):
> `float custom_arrow_step = 0.0`
> If not 0, value will always be rounded to a multiple of custom_arrow_step when interacting with the arrow buttons of the SpinBox.

**Comment by akien-mga** [comment]
Thanks!
