### PR TITLE
Core: Natively convert `enum`/`BitField` with `Variant`

### LINKED ISSUE #101002: Cannot declare virtual method with enum from own class
### Tested versions

v4.4.dev7
v4.3.stable
v4.2.2.stable
v4.1.stable

### System information

Windows 11 24H2

### Issue description

Attempting to setup a class which defines a virtual method for an enum setup in that class. That is, before `VARIANT_ENUM_CAST` gets setup. Because the logic in the virtual method is declared immediately, any generic calls are established before this crucial step. In this case, it's `PtrToArg` that's setup too early.

### Steps to reproduce

Script excerpt:
```cpp
class Logger : public RefCounted {
	GDCLASS(Logger, RefCounted);

protected:
	static void _bind_methods();

public:
	enum class LogLevel {
		DEBUG,
		INFO,
		WARN,
		ERROR,
		FATAL,
		MAX,
	};

	virtual void log(const String &p_content, LogLevel p_level, const TypedDictionary<String, Variant> &p_context = {}) = 0;

#define _COMMA ,
	GDVIRTUAL3(_log, String, LogLevel, TypedDictionary<String _COMMA Variant>);
#undef _COMMA
};

VARIANT_ENUM_CAST(Logger::LogLevel);
```

Error output:
```
Use of undeclared identifier 'argval2'; did you mean 'argval1'? clang(undeclared_var_use_suggest)
Expected ';' after expression clang(expected_semi_after_expr)
No member named 'EncodeT' in 'PtrToArg<Logger::LogLevel>' clang(no_member)
Use of undeclared identifier 'argval2' clang(undeclared_var_use)
Implicit instantiation of undefined template 'GetTypeInfo<Logger::LogLevel>' clang(template_instantiate_undefined)
type_info.h(62, 8): Template is declared here
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Repiteo**
A big reason the above issue happened in the first place is because SO MUCH of the enum binding logic happens after the fact, when the overwhelming majority could be determined via `<type_traits>` magic. The only exception seems to be the qualified name, which this PR keeps as an explicitly provided variable; absolutely *everything* else is now handled natively. While this could probably be implemented more cleanly via C++20 concepts, the **entire bindsystem** would benefit from them; so for now, SFINAE[^1] gets the job done.

EDIT: No longer a fix for #101002, as the option I tried exploring here increased binary size to a non-insignificant degree

[^1]: https://en.cppreference.com/w/cpp/language/sfinae

### CODE REVIEW

File: core/variant/variant_internal.h [hunk 1]
```diff
@@ -528,66 +528,23 @@ class VariantInternal {
...
-template <>
-struct VariantGetInternalPtr<int64_t> {
-	static int64_t *get_ptr(Variant *v) { return VariantInternal::get_int(v); }
-	static const int64_t *get_ptr(const Variant *v) { return VariantInternal::get_int(v); }
-};
-
-template <>
-struct VariantGetInternalPtr<uint64_t> {
+template <typename T>
+struct VariantGetInternalPtr<T, std::enable_if_t<std::is_integral_v<T> || std::is_enum_v<T>>> {
```
Comment (Ivorforce) [inline core/variant/variant_internal.h:541]: `is_integral_v` matches bools too. The explicit `<bool>` declaration will probably always trump it, but just in case, you could probably add an explicit != bool check too.

File: core/variant/type_info.h [hunk 2]
```diff
@@ -265,77 +266,33 @@ class BitField {
...
 template <typename T>
 inline StringName __constant_get_bitfield_name(T param, const String &p_constant) {
-	if (GetTypeInfo<T>::VARIANT_TYPE == Variant::NIL) {
-		ERR_PRINT("Missing VARIANT_ENUM_CAST for constant's bitfield: " + p_constant);
-	}
 	return GetTypeInfo<BitField<T>>::get_class_info().class_name;
 }
 #define CLASS_INFO(m_type) (GetTypeInfo<m_type *>::get_class_info())
 
+// No initialization by default, expect for scalar types.
```
Comment (Ivorforce) [inline core/variant/type_info.h:288]: What about pointer types?

Comment (Repiteo) [reply core/variant/type_info.h:288]: They're also scalar types!

https://en.cppreference.com/w/cpp/named_req/ScalarType

File: core/variant/variant_internal.h (hunk 1 above)
Comment (Repiteo) [reply core/variant/variant_internal.h:541]: Explicit declaration should always take priority, but I'm not 100% sure if that will also capture edgecases like `cvref` equivalents. Granted, if it doesn't, then that's a hole that exists for basically all the other templates too. Either way, I'll prooobably include that in a future rebase, even if I'm not sold on it being necessary

**Comment by Repiteo** [comment]
Figured out how to handle qualified names! Now `VARIANT_ENUM_CAST` & `VARIANT_BITFIELD_CAST` are **completely deprecated** macros; everything about enums can be detected automatically!

File: core/variant/binder_common.h [hunk 3]
```diff
@@ -82,112 +82,10 @@ struct VariantCaster<const T &> {
...
-VARIANT_ENUM_CAST(Variant::Type);
-VARIANT_ENUM_CAST(Variant::Operator);
-
-// Key
-
-VARIANT_ENUM_CAST(Key);
-VARIANT_BITFIELD_CAST(KeyModifierMask);
-VARIANT_ENUM_CAST(KeyLocation);
+#ifndef DISABLE_DEPRECATED
+#define VARIANT_ENUM_CAST(m_enum) // Does nothing.
```
Comment (Ivorforce) [inline core/variant/binder_common.h:86]: Are these stubs still needed? If they are not used in the codebase (you seem to have removed a lot of them), maybe an [explicit deprecation](https://stackoverflow.com/a/29297970/730797) would be good?

File: core/variant/type_info.h [hunk 4]
```diff
@@ -220,31 +226,47 @@ inline String enum_qualified_name_to_class_info_name(const String &p_qualified_n
...
+inline String demangle_enum_name() {
+#ifdef __GNUC__
+	int status;
+	char *buffer = abi::__cxa_demangle(typeid(T).name(), nullptr, nullptr, &status);
+	DEV_ASSERT(status == 0);
+	String name = String::utf8(const_cast<const char *>(buffer));
+	free(buffer);
+	return name;
+#else
+	return String::utf8(typeid(T).name()).trim_prefix("enum ");
```
Comment (Ivorforce) [inline core/variant/type_info.h:240]: I guess this case is valid for both MSVC and emscripten? Do they not mangle names? Do we have any guarantees that this works for _potential_ other compilers?

File: core/variant/type_info.h [hunk 5]
```diff
@@ -220,31 +226,47 @@ inline String enum_qualified_name_to_class_info_name(const String &p_qualified_n
 	// Contains namespace. We only want the class and enum names.
 	return parts[parts.size() - 2] + "." + parts[parts.size() - 1];
 }
+
+template <typename T>
+inline String demangle_enum_name() {
+#ifdef __GNUC__
+	int status;
+	char *buffer = abi::__cxa_demangle(typeid(T).name(), nullptr, nullptr, &status);
```
Comment (Ivorforce) [inline core/variant/type_info.h:234]: Is there a guarantee that this works even if the binary is obfuscated? I guess obfuscation may introduce other problems too, but just a thought.

File: core/variant/variant.h [hunk 6]
```diff
@@ -441,12 +443,13 @@ class Variant {
...
 	operator Vector<StringName>() const;
 
-	// some core type enums to convert to
-	operator Side() const;
-	operator Orientation() const;
-
 	operator IPAddress() const;
 
+	template <typename T, std::enable_if_t<std::is_enum_v<T>, int> = 0>
+	_FORCE_INLINE_ operator T() const { return static_cast<T>(operator int64_t()); }
```
Comment (Ivorforce) [inline core/variant/variant.h:449]: Interesting generalized approach! Two comments:

1) While the source code doesn't currently differentiate anyway, we may want to use the appropriate `operator()` based on the actual enum type (`std::underlying_type_t<FooEnum>`).
2) This is opening a new can of worms for implicit conversions, where previously only `Side` and `Orientation` were allowed. Perhaps we can make this explicit, and re-add `Side` and `Orientation` back as implicit for backwards compat (for now)?

File: core/variant/variant.h [hunk 7]
```diff
@@ -509,22 +512,12 @@ class Variant {
...
-	VARIANT_ENUM_CLASS_CONSTRUCTOR(JoyAxis)
-	VARIANT_ENUM_CLASS_CONSTRUCTOR(JoyButton)
-	VARIANT_ENUM_CLASS_CONSTRUCTOR(Key)
-	VARIANT_ENUM_CLASS_CONSTRUCTOR(KeyLocation)
-	VARIANT_ENUM_CLASS_CONSTRUCTOR(MIDIMessage)
-	VARIANT_ENUM_CLASS_CONSTRUCTOR(MouseButton)
-
-#undef VARIANT_ENUM_CLASS_CONSTRUCTOR
+	template <typename T, std::enable_if_t<std::is_enum_v<T>, int> = 0>
+	_FORCE_INLINE_ Variant(T p_enum) :
```
Comment (Ivorforce) [inline core/variant/variant.h:516]: I have implicitness concerns here too.

File: core/variant/variant_internal.h [hunk 8]
```diff
@@ -821,36 +772,26 @@ struct VariantGetInternalPtr<PackedVector4Array> {
...
-VARIANT_ACCESSOR_NUMBER(uint8_t)
-VARIANT_ACCESSOR_NUMBER(int16_t)
-VARIANT_ACCESSOR_NUMBER(uint16_t)
-VARIANT_ACCESSOR_NUMBER(int32_t)
-VARIANT_ACCESSOR_NUMBER(uint32_t)
-VARIANT_ACCESSOR_NUMBER(int64_t)
-VARIANT_ACCESSOR_NUMBER(uint64_t)
-VARIANT_ACCESSOR_NUMBER(char32_t)
+template <typename T>
+struct VariantInternalAccessor<T, std::enable_if_t<std::is_integral_v<T> || std::is_enum_v<T>>> {
```
Comment (Ivorforce) [inline core/variant/variant_internal.h:785]: We have the same (probably unimportant) bool concerns here as with `VariantGetInternalPtr` before :)

File: core/variant/variant_internal.h [hunk 9]
```diff
@@ -1125,40 +1066,23 @@ struct VariantInternalAccessor<Vector<Variant>> {
...
+};
+
+template <typename T>
+struct VariantInitializer<BitField<T>, std::enable_if_t<std::is_enum_v<T>>> {
+	static _FORCE_INLINE_ void init(Variant *v) { VariantInternal::init_generic<BitField<T>>(v); }
+};
+
+template <>
+struct VariantInitializer<ObjectID> {
+	static _FORCE_INLINE_ void init(Variant *v) { VariantInternal::init_generic<ObjectID>(v); }
```
Comment (Ivorforce) [inline core/variant/variant_internal.h:1084]: Do these 3 cases have to be separate? I don't really see a difference.

**Review by Ivorforce — COMMENTED** [review]
This is looking great! I think the LOC change alone shows the reduction in complexity this PR brings. Looking forward to when this gets merged 😁

File: core/variant/type_info.h (hunk 4 above)
Comment (Repiteo) [reply core/variant/type_info.h:240]: GCC and Clang are the main two compilers that return mangled names from `typeid`[^1]. I *believe* emscription falls into the same camp as clang, but I'm not 100% positive.

[^1]: https://en.cppreference.com/w/cpp/types/type_info/name#Notes

File: core/variant/binder_common.h (hunk 3 above)
Comment (Repiteo) [reply core/variant/binder_common.h:86]: I suppose not. I kept them for compatibility with third-party modules, but their removal isn't technically "breaking" unless you do a deliberate rescope like `RenderingDevice`. Will likely remove next rebase.

File: core/variant/type_info.h (hunk 5 above)
Comment (Repiteo) [reply core/variant/type_info.h:234]: No clue. I'll dig for alternative ways of grabbing typenames natively just in case

File: core/variant/variant.h (hunk 6 above)
Comment (Repiteo) [reply core/variant/variant.h:449]: 1. All int-likes are cast to/from `int64_t` with Variant as-is, so that being the baseline should be fine (or, at least, working-as-expected).
2. For better or for worse, Variant is built upon implicit casts. Those two were specified before for convenience, in a manner camp to the non-packed `Vector<>` overloads; I wouldn't consider that *excluding* other enums, so much as not wanting to deal with extra verbosity. In other words: this won't break compat, as it's not changing any behavior for the existing code.

File: core/variant/variant.h (hunk 7 above)
Comment (Repiteo) [reply core/variant/variant.h:516]: By design, same as above.

File: core/variant/variant_internal.h (hunk 9 above)
Comment (Repiteo) [reply core/variant/variant_internal.h:1084]: Now that you mention it, this whole section simplified drastically. The default case can just be `init_generic`!

File: core/variant/variant.h (hunk 6 above)
Comment (Ivorforce) [reply core/variant/variant.h:449]: 1. If we accept this at the baseline, i think I should rewrite #101055 with the same logic (call `operator int64_t`, `cast`). Agree? I'd be fine with that too.

Comment (Repiteo) [reply core/variant/variant.h:449]: You aren't dealing with generics in that PR, so it's probably not *as* necessary. If anything, I'd consider leaning *more* into the generics with that PR. Lemme setup a diff real quick; I'll post it on the PR itself to not derail this

**Comment by Repiteo** [comment]
Gave it some more thought, and I'm gonna walk back on trying to handle qualified names automatically. While I'm still *largely* confident of that implementation, it wasn't air-tight; I'd rather not have the rest of the PR be potentially bogged down by it. I'll revisit that idea in the future, once I have an unambiguously universal solution.

**Comment by Ivorforce** [comment]
Looks like this PR massively increases the size of the resulting binary (going by the action's artifacts).

**Comment by Repiteo** [comment]
> Looks like this PR massively increases the size of the resulting binary (going by the action's artifacts).

Hmm, so it does. Wish I could more easily pin down where that size change comes from at a glance, but we don't have something setup in SCons for that atm (might look into that later today).

**Comment by Ivorforce** [comment]
I quickly checked with `bloaty`, seems like it's all text:

```
 ❯ bloaty /Users/lukas/Downloads/godot.macos.editor.universal -- /Users/lukas/Downloads/godot.macos.editor.universal\ 2
    FILE SIZE        VM SIZE
 --------------  --------------
   +48% +88.4Mi   +46% +44.1Mi    __TEXT,__text
 +53e2% +1.84Mi  [ = ]       0    __DATA_CONST,__mod_init_func
 +53e2% +1.84Mi +53e2% +1.84Mi    __DATA,__mod_init_func
```

**Comment by Repiteo** [comment]
Ahhh, I might know whats up then. I'm still using a similar setup to the version that would've automatically grabbed a name but utilize a fallback otherwise; it's now technically *all* fallback, so that's almost certainly the bloat. Still have no clue *how* that would happen so excessively, but now I have something to dig into at least.

**Comment by Repiteo** [comment]
Alright, looks like the solution I've got up is working. I simplified several of the template layouts originally called to for enums/bitfields, meaning they automatically convert the passed types to a simple equivalent. So while I did have to return to the old formatting, there only has to be a single type specified per-layout!

**Review by Ivorforce — APPROVED** [review]
I like this a lot! All these templates were way overdue for a simplification. I think you did a great job on this PR.

It's difficult to be _completely_ sure that everything works as expected - but the biggest hurdle with templates is getting it to compile. I've spotted no mistakes with the logic beyond that.

The biggest risk I see with more templating vs explicit declaratinos is that you can accidentally overgeneralize and match types you don't want to match. I've raised the boolean problem before, and there may be others like it (although I didn't immediately spot any). Before merging, please make doubly sure that each declaration is as airtight as it can be.

File: core/variant/variant_internal.h [hunk 10]
```diff
@@ -527,66 +529,26 @@ class VariantInternal {
...
-template <>
-struct VariantGetInternalPtr<int64_t> {
-	static int64_t *get_ptr(Variant *v) { return VariantInternal::get_int(v); }
-	static const int64_t *get_ptr(const Variant *v) { return VariantInternal::get_int(v); }
-};
-
-template <>
-struct VariantGetInternalPtr<uint64_t> {
+template <typename T>
+struct VariantGetInternalPtr<T, std::enable_if_t<std::is_integral_v<T> || std::is_enum_v<T>>> {
```
[the remark this answers is not in the document]
Comment (Repiteo) [reply core/variant/variant_internal.h:545]: I've since removed it because that edge-case scenario is no longer applicable; any non-simple `bool` will be simplified to `bool`, which already has its template explicitly created

[the remark this answers is not in the document]
Comment (Ivorforce) [reply core/variant/variant_internal.h:545]: Ok, explicit will definitely trump int selectors!

**Comment by Repiteo** [comment]
The only issue now is that this is no longer a fix for #101002, but I think that's unavoidable at this stage. The only way to truly work around this in a portable manner will rely on C++20 via `std::source_location`. This PR still stands on its own merits for laying the groundwork for internal template cleanup
