### PR TITLE
Clarify C# Color opacity comment

### LINKED ISSUE #88882: Change wording from "transparency" to "opacity"
### Tested versions

- `v4.2.2.rc1.mono.official` [c7fb0645a]
- `v4.2.1.stable.mono.official` [b09f793f5]

### System information

Godot v4.2.2.rc1.mono - Windows 10.0.22621 - Vulkan (Forward+)

### Issue description

According to the (.NET) doc comments for `Color`, `color.a` (alpha) is:
> "The color's alpha (transparency) component, typically on the range of 0 to 1."

This is misleading because it implies 1 is fully transparent (like in [Roblox](https://create.roblox.com/docs/reference/engine/classes/BasePart#Transparency)) but in fact 1 is fully opaque.

Relevant comments:
image
image
image

Interestingly, the [web docs](https://docs.godotengine.org/en/stable/classes/class_color.html#property-descriptions) are clearer:
> The color's alpha component, typically on the range of 0 to 1. A value of 0 means that the color is fully transparent. A value of 1 means that the color is fully opaque.

But this could also be resolved with something shorter like:
> The opacity of the color from 0 to 1.

### Steps to reproduce

- GodotSharp + VSCode

### Minimal reproduction project (MRP)

[GodotOpacityColourTest.zip](https://github.com/godotengine/godot/files/14409416/GodotOpacityColourTest.zip)

### PR DESCRIPTION
**Pull request by emre0altan**
Comments are updated for clarity.

* Fixes: #88882

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs [hunk 1]
```diff
@@ -38,7 +38,9 @@ public struct Color : IEquatable<Color>
         public float B;
 
         /// <summary>
-        /// The color's alpha (transparency) component, typically on the range of 0 to 1.
+        /// The color's alpha (opacity) component, typically on the range of 0 to 1.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs:41]: Core documentation doesn't include the parenthesized word.

```suggestion
        /// The color's alpha component, typically on the range of 0 to 1.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs [hunk 2]
```diff
@@ -534,7 +536,11 @@ readonly get
         /// <param name="r">The color's red component, typically on the range of 0 to 1.</param>
         /// <param name="g">The color's green component, typically on the range of 0 to 1.</param>
         /// <param name="b">The color's blue component, typically on the range of 0 to 1.</param>
-        /// <param name="a">The color's alpha (transparency) value, typically on the range of 0 to 1. Default: 1.</param>
+        /// <param name="a">
+		/// The color's alpha (opacity) value, typically on the range of 0 to 1.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs:540]:
```suggestion
		/// The color's alpha value, typically on the range of 0 to 1.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs [hunk 3]
```diff
@@ -547,7 +553,11 @@ public Color(float r, float g, float b, float a = 1.0f)
         /// Constructs a <see cref="Color"/> from an existing color and an alpha value.
         /// </summary>
         /// <param name="c">The color to construct from. Only its RGB values are used.</param>
-        /// <param name="a">The color's alpha (transparency) value, typically on the range of 0 to 1. Default: 1.</param>
+        /// <param name="a">
+		/// The color's alpha (opacity) value, typically on the range of 0 to 1.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs:557]:
```suggestion
		/// The color's alpha value, typically on the range of 0 to 1.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs [hunk 4]
```diff
@@ -534,7 +536,11 @@ readonly get
         /// <param name="r">The color's red component, typically on the range of 0 to 1.</param>
         /// <param name="g">The color's green component, typically on the range of 0 to 1.</param>
         /// <param name="b">The color's blue component, typically on the range of 0 to 1.</param>
-        /// <param name="a">The color's alpha (transparency) value, typically on the range of 0 to 1. Default: 1.</param>
+        /// <param name="a">
+		/// The color's alpha (opacity) value, typically on the range of 0 to 1.
+		/// A value of 0 means that the color is fully transparent.
+		/// A value of 1 means that the color is fully opaque. Default: 1.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs:542]: The default value is unnecessary, IntelliSense will already surface the default value of a parameter. Since we're making changes to this documentation we could take the opportunity to remove it.

```suggestion
		/// A value of 1 means that the color is fully opaque.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs [hunk 5]
```diff
@@ -547,7 +553,11 @@ public Color(float r, float g, float b, float a = 1.0f)
         /// Constructs a <see cref="Color"/> from an existing color and an alpha value.
         /// </summary>
         /// <param name="c">The color to construct from. Only its RGB values are used.</param>
-        /// <param name="a">The color's alpha (transparency) value, typically on the range of 0 to 1. Default: 1.</param>
+        /// <param name="a">
+		/// The color's alpha (opacity) value, typically on the range of 0 to 1.
+		/// A value of 0 means that the color is fully transparent.
+		/// A value of 1 means that the color is fully opaque. Default: 1.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs:559]:
```suggestion
		/// A value of 1 means that the color is fully opaque.
```

**Review by raulsntos — COMMENTED** [review]
Thanks for contributing to the .NET documentation.

We usually try to match the Core documentation, so I took a look at the documentation for [Color](https://github.com/godotengine/godot/blob/a586e860e5fc382dec4ad9a0bec72f7c6684f020/doc/classes/Color.xml) and it looks like these changes mostly match the documentation for the [`a` member](https://github.com/godotengine/godot/blob/a586e860e5fc382dec4ad9a0bec72f7c6684f020/doc/classes/Color.xml#L475-L477). I made comments on the parts that are different.

**Review by raulsntos — APPROVED** [review]
LGTM. Thanks!

**Comment by emre0altan** [comment]
Thanks, updated the changes now 🙂

**Comment by akien-mga** [comment]
Thanks!
