### PR TITLE
Fix inconsistent behavior of Bezier editor undo operations upon selection of different animation

### LINKED ISSUE #93859: Inconsistent behavior when undoing animation bezier movements upon selection of different animations
### Tested versions

- Reproducible in 4.2.1 and master (9425535)

### System information

Windows 10

### Issue description

When manipulating bezier keys and then selecting a different Animation, or a different AnimationPlayer, bad things are bound to happen on undo and redo, due to the animation_bezier_editor referencing the currently selected animation in the undo methods.

### Steps to reproduce

1. Select AnimationPlayer, go into bezier view and move a key
2. Select a different AnimationPlayer
3. Undo (observe an index out of bounds error in the output)
4. Redo (observe that the key is now transferred to the currently selected animation)

### Minimal reproduction project (MRP)

[AnimationTestProject2.zip](https://github.com/user-attachments/files/16066763/AnimationTestProject2.zip)

### PR DESCRIPTION
**Pull request by CookieBadger**
Fixes #93859.

~This PR removes the method `_bezier_track_insert_key` in the `AnimationBezierEditor` and adds a method `bezier_track_insert_key_with_handle_mode` in `Animation`. This new method is then called in the undo/redo operations, such that the correct animation is always tracked.~

This PR adds the animation as a parameter to a method `_bezier_track_insert_key_at_anim` (before `_bezier_track_insert_key`) in the `AnimationBezierEditor`, such that it is tracked when used in UndoRedo operations.

### CODE REVIEW

File: scene/resources/animation.h [hunk 1]
```diff
@@ -455,6 +455,7 @@ class Animation : public Resource {
 	void track_set_interpolation_type(int p_track, InterpolationType p_interp);
 	InterpolationType track_get_interpolation_type(int p_track) const;
 
+	void bezier_track_insert_key_with_handle_mode(int p_track, double p_time, real_t p_value, const Vector2 &p_in_handle, const Vector2 &p_out_handle, const Animation::HandleMode p_handle_mode);
```
Comment (AThousandShips) [inline scene/resources/animation.h:458]:
```suggestion
	void bezier_track_insert_key_with_handle_mode(int p_track, double p_time, real_t p_value, const Vector2 &p_in_handle, const Vector2 &p_out_handle, HandleMode p_handle_mode);
```

File: scene/resources/animation.cpp [hunk 2]
```diff
@@ -3189,6 +3189,14 @@ StringName Animation::method_track_get_name(int p_track, int p_key_idx) const {
 	return pm->methods[p_key_idx].method;
 }
 
+void Animation::bezier_track_insert_key_with_handle_mode(int p_track, double p_time, real_t p_value, const Vector2 &p_in_handle, const Vector2 &p_out_handle, const Animation::HandleMode p_handle_mode) {
```
Comment (AThousandShips) [inline scene/resources/animation.cpp:3192]:
```suggestion
void Animation::bezier_track_insert_key_with_handle_mode(int p_track, double p_time, real_t p_value, const Vector2 &p_in_handle, const Vector2 &p_out_handle, HandleMode p_handle_mode) {
```

File: scene/resources/animation.h [hunk 3]
```diff
@@ -455,6 +455,7 @@ class Animation : public Resource {
 	void track_set_interpolation_type(int p_track, InterpolationType p_interp);
 	InterpolationType track_get_interpolation_type(int p_track) const;
 
+	void bezier_track_insert_key_with_handle_mode(int p_track, double p_time, real_t p_value, const Vector2 &p_in_handle, const Vector2 &p_out_handle, HandleMode p_handle_mode);
```
Comment (akien-mga) [inline scene/resources/animation.h:458]: `HandleMode` is `TOOLS_ENABLED` (editor) only, so this doesn't compile in export templates.

If this is only needed for the editor, it should also be enclosed in `#ifdef TOOLS_ENABLED`, but then it can't be exposed in `_bind_methods` as the scripting API shouldn't differ between tools and non-tools.

**Comment by CookieBadger** [comment]
Does the method using HandleMode have to be defined in #ifdef TOOLS_ENABLED, for Android, Linux, etc. to compile successfully? I'm unfamiliar with those flags

File: scene/resources/animation.h (hunk 3 above)
Comment (CookieBadger) [reply scene/resources/animation.h:458]: oh I see. Well, it should not be exposed in the editor, but I figured it would have to be bound, such that it can be called from a signal, right?

Comment (akien-mga) [reply scene/resources/animation.h:458]: To use as a signal callback it doesn't need to be bound, you can use `callable_mp`.
But in this PR you're using it for UndoRedo and that one currently still requires method bindings, it doesn't support `callable_mp`.

So ideally if there's a way to achieve what you're doing while keeping the method within the AnimationBezierEditor, that might be best. Otherwise it might need some creative API rethinking (possibly exposing HandleMode to non-tools if there's no good alternative).

Comment (CookieBadger) [reply scene/resources/animation.h:458]: Ok, makes sense. The easiest is to move it back to the bezier editor then. Thank you, akien! :)

**Review by TokageItLab — APPROVED** [review]
Working fine on testing.
