### PR TITLE
Fix a gap with scrolling down in Tree with arrow keys (#57636)

### LINKED ISSUE #57636: Scrolling down in Tree with arrow keys leaves a small gap
### Godot version

3db1d689ce11507d9597bb434891da95168f2c69

### System information

W10

### Issue description

When scrolling down with arrow keys, there is a small space between the highlighted result and the bottom of the tree rect. This is not the case when scrolling up. It probably has something to do with the horizontal slider, even when it's not visible.

Scrolling up works correctly:
tree2

Scrolling down leaves a gap:
tree

With horizontal scrollbar visible:
image

Video:

https://user-images.githubusercontent.com/25907608/152580566-3981fba7-4623-4ac1-86b7-4c9c94bb089a.mp4

### Steps to reproduce

Focus tree node with vertical scrollbar
Scroll down with arrow keys

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by marzecdawid**
Fixes #57636
As it is my first PR and also I don't have to much experience with programming and C++ please check if everything is for sure correct. To help with that I will try to explain what I changed and why.

Right now if you use the arrow keys to scroll through the tree then the position of the scrollbar will be calculated and set in the function `Tree::scroll_to_item` because:
- the event `CreateDialog::_item_selected()` executes a function `CreateDialog::select_type()` 
- the function `CreateDialog::select_type()` executes `Tree::scroll_to_item()`

But after that the position of the scrollbar will be again calculated but in the function `Tree::ensure_cursor_is_visible()` because:
- `Tree::gui_input()` executes `_go_down()`
- `_go_down()` executes `Tree::ensure_cursor_is_visible()`

In the issue #57636 the problem is inside the `Tree::ensure_cursor_is_visible()` as the `Tree::scroll_to_item` also calculates the position for scrollbar wrong and the selected item is slighly outside of the tree window so it is then corrected in the `Tree::ensure_cursor_is_visible()`.
The `Tree::ensure_cursor_is_visible()` ignores the fact that the h_scroll is not visible so I fixed that:

`const int screen_h = area_size.height - h_scroll->get_combined_minimum_size().height - tbh;` to:
`const int screen_h = area_size.height - h_scroll->is_visible() * h_scroll->get_combined_minimum_size().height - tbh;`

And it basically fixes the issue #57636, however while testing I also found that the `Tree::scroll_to_item` calculates the scrollbar value wrong (which is used for example when you select an item by mouse click) so I also copied the fixed calculations from `Tree::ensure_cursor_is_visible()` to `Tree::scroll_to_item` to fix that:
obraz
... and corrected the code when the parameter `p_center_on_item` it set to true as it was not perfectly centered.

At first I wanted to fix this by removing the calculations for scrollbar from `Tree::scroll_to_item` and add the `Tree::ensure_cursor_is_visible()` here but `Tree::ensure_cursor_is_visible()` need to have an item in the tree selected where `Tree::scroll_to_item` does not need it. So that's why I left same calculations in both places.

Other less important things I noticed:
1. (Editor problem) If you use the searchbar to find a node it will then first execute:
- `CreateDialog::_item_selected()` -> `select_type(name, false)` -> `search_options->scroll_to_item(to_select, p_center_on_item)` where p_center_on_item is false
- and then `CreateDialog::_update_search()` -> `select_type(_top_result(candidates, search_text))` -> `search_options->scroll_to_item(to_select, p_center_on_item);` where the p_center_on_item is true as it is the default value in .h file
2. (Gui->Tree problem) If you use the right arrow key to select the node in the tree list then it will execute from Editor code:
- `CreateDialog::_item_selected()` -> `CreateDialog::select_type()` -> `Tree::scroll_to_item`, and then from the Gui->Tree code:
- `Tree::_go_right()` -> `_go_down()` -> `ensure_cursor_is_visible()`
- `Tree::_go_right()` -> `ensure_cursor_is_visible()`

So in this case it will calculate the scrollbar value 3 times, where 2 times are from the Gui->Tree code. I don't know if something like this is acceptable and if this should be corrected but I just wanted to share what I found.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -4555,7 +4555,7 @@ void Tree::ensure_cursor_is_visible() {
 		y_offset -= tbh;
 
 		const int cell_h = compute_item_height(selected_item) + theme_cache.vseparation;
-		const int screen_h = area_size.height - h_scroll->get_combined_minimum_size().height - tbh;
+		const int screen_h = area_size.height - h_scroll->is_visible() * h_scroll->get_combined_minimum_size().height - tbh;
```
Comment (groud) [inline scene/gui/tree.cpp:4558]: This it a bit of a weird trick. I think it would be a bit cleaner to avoid multiplying a bool by an int here.
If you want to keep things in line, a ternary operator would be better IMO: 
`const int screen_h = area_size.height - (h_scroll->is_visible() ? h_scroll->get_combined_minimum_size().height : 0) - tbh;

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -4706,26 +4706,28 @@ Point2 Tree::get_scroll() const {
...
-	} else {
-		if (item_y < v_scroll->get_value()) {
-			v_scroll->set_value(item_y);
+	int y_offset = get_item_offset(p_item);
+	if (y_offset != -1) {
+		const int tbh = _get_title_button_height();
+		y_offset -= tbh;
+
+		const int cell_h = compute_item_height(p_item) + theme_cache.vseparation;
+		const int screen_h = area_size.height - h_scroll->is_visible() * h_scroll->get_combined_minimum_size().height - tbh;
```
Comment (groud) [inline scene/gui/tree.cpp:4720]: Same here.

**Review by groud — CHANGES_REQUESTED** [review]
Other than the weird `bool * int` multiplication, it looks fine to me.

File: scene/gui/tree.cpp (hunk 1 above)
Comment (marzecdawid) [reply scene/gui/tree.cpp:4558]: I always see bool as very small int :)
I will correct this.

Comment (KoBeWi) [reply scene/gui/tree.cpp:4558]: IMO explicit `int(h_scroll->is_visible())` is ok too.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
