### PR TITLE
Fix transform for transposed tiles in compatibility mode (from 3.x)

### LINKED ISSUE #73517: TileSet Alternative transposed tile incorrectly offsets collision shape (and representative tile orange box)
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

While working on Demo Platformer 2D, I noticed that the collision shapes for slope ceiling tiles, which are transposed variants, were completely offset from their definition in red. Below, the blue collision shapes are not matching the red ones at all.

image

Either the preview for red shape editing is wrong, or the blue collision shape is wrong. When testing in game, the physics seems to correspond to the blue shape, so it's possible that the preview for red shape editing is incorrectly offset.

In addition, the orange box, representing the place in the tilemap where the tile is actually set (only meaningful for tile collection whose Texture Region Size does not match TileMap Tile Size, generally bigger), is also offset from the actual box used for placement.

In the alternative tile view, the representative box (in blue this time) is also oddly represented:
- when moved by at least 1 px horizontally, it disappears (I suspect transposed tiles think it's moving vertically and therefore leaving the expected area, as the bad orange box in the red shape editing area). We can still see the center blue cross though
- when moved to the right edge, it's coonsidered completely out of area so the coords (16, 0) are shown instead (again due to transpose thinking we are moving on Y)

image

Compare with a non-transposed tile correctly showing the blue box:

image

### Steps to reproduce

1. Open a tileset with transposed tiles (the demo Platformer 2D is good)
2. Click on Select tab and click on some of the variants, esp. transposed ones (ceiling slopes)
3. Check the Transpose flag, the Texture Origin, and most importantly Physics > Physics Layer 0 > Red collision shape editing area
4. Observe discrepancy between red area and blue area in the preview on the right
5. Repeat with Texture Origin, testing different values to move the orange/blue box near the edges of the big tile
6. Observe discrepancy between orange box and blue box in the preview on the right

### Minimal reproduction project

The Demo Platformer 2D is good, but I can provide minimal project extracting just the tileset if required

### PR DESCRIPTION
**Pull request by kleonc**
When converting a TileSet from 3.x. the Transform2D used for transforming collision shapes etc. was incorrectly calculated for transposed tiles.

`xform.rotated(Math_PI).scaled(Size2(-1, -1))` previously used is a no-op, as that's a rotation by 180 degrees followed by flipping both axes.

If anything, e.g. a rotation by 90 degrees followed by the x-axis (post rotation) flip could be used as transposition (`xform.rotated(Math_PI * 0.5).scaled(Size2(-1, 1))`). But the rotation would result in slight inaccurancy (y-axis could become something like `(1.00000000000000000000, -0.00000004371138828674)`) and hence it should be avoided. This PR makes the axes be actually swapped, without additional calculations.

Probably fixes #73517 (not fully sure if that's what reported in there).

### CODE REVIEW

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -3086,7 +3086,7 @@ void TileMap::_build_runtime_update_tile_data(SelfList<TileMapQuadrant>::List &r
 
 							// Create the runtime TileData.
 							TileData *tile_data_runtime_use = tile_data->duplicate();
-							tile_data->set_allow_transform(true);
+							tile_data_runtime_use->set_allow_transform(true);
```
Comment (kleonc) [inline scene/2d/tile_map.cpp:3089]: @groud That's unrelated changed, but I think it's the duplicated TileData which were supposed to be allowed to be transformed? :thinking:

Comment (groud) [reply scene/2d/tile_map.cpp:3089]: Yes, that sounds good.

Comment (groud) [reply scene/2d/tile_map.cpp:3089]: I added the change to https://github.com/godotengine/godot/pull/78328 too. I don't know if we want to keep it in this PR. I guess it depends on the first merged. ^_^"

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
