### PR TITLE
Clear intermediate buffers when not in use in Compatibility

### LINKED ISSUE #100391: Compatibility Renderer: Environment Color Changed after Turn off Glow
### Tested versions

v4.3.stable.official [77dcf97d8] and all the version of 4.0 (probably)

### System information

Godot v4.3.stable - Android - GLES3 (Compatibility) - Adreno (TM) 610 -  (8 Threads)

### Issue description

I had a environment with colorful objects. When I turn on the glow in Compatibility Renderer everything was normal. But when I just turn off the glow my colorful environment turn into dry environment. Here is the preview.
Glow Off:
Image
Glow On:
Image
Glow off after On:
Image

above preview has minimal things. But still difference between screenshot 1 and screenshot 3 is notice able. 

### Steps to reproduce

- created colorful environment
- turn on glow
- turn off glow

### Minimal reproduction project (MRP)

[big-problem.zip](https://github.com/user-attachments/files/18134356/big-problem.zip)

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
After setting up the intermediate buffers for the first time, they don't get cleared after disabling glow / adjustments. When the buffers are present,
https://github.com/godotengine/godot/blob/1f7630f1bfd9a7c65a5c144f85be38b4b64e3717/drivers/gles3/rasterizer_scene_gles3.cpp#L2778 will not be 0.

Some post processing logic is dependent on if it is 0:
https://github.com/godotengine/godot/blob/1f7630f1bfd9a7c65a5c144f85be38b4b64e3717/drivers/gles3/rasterizer_scene_gles3.cpp#L2845 https://github.com/godotengine/godot/blob/1f7630f1bfd9a7c65a5c144f85be38b4b64e3717/drivers/gles3/rasterizer_scene_gles3.cpp#L2864

Fixes https://github.com/godotengine/godot/issues/100391

### CODE REVIEW

File: drivers/gles3/storage/render_scene_buffers_gles3.cpp [hunk 1]
```diff
@@ -202,6 +202,10 @@ void RenderSceneBuffersGLES3::_check_render_buffers() {
 
 	if ((!use_internal_buffer || internal3d.color != 0) && (msaa3d.mode == RS::VIEWPORT_MSAA_DISABLED || msaa3d.color != 0)) {
 		// already setup!
+		if (!use_internal_buffer && msaa3d.mode == RS::VIEWPORT_MSAA_DISABLED && (internal3d.color != 0 || msaa3d.color != 0)) {
```
Comment (clayjohn) [inline drivers/gles3/storage/render_scene_buffers_gles3.cpp]: I don't think you need to check msaa3d.mode here. MSAA follows its own branch after the internal texture is allocated. The parent if check here checks both MSAA and internal buffer only because it can only early return if neither of them need to be allocated.

Comment (Kaleb-Reid) [reply drivers/gles3/storage/render_scene_buffers_gles3.cpp]: I see that now, changes made.

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by Repiteo** [comment]
Thanks!
