### PR TITLE
LSP: Optimize `find_usages_in_file`

### LINKED ISSUE #114729: LSP command Goto References causes a segfault on 4.6 Beta 3 (with NeoVim)
### Tested versions

Crashes on:
v4.6.beta.custom_build [5d9722e83]
v4.6.beta3.official [76dda5c6c]

Not tested on v4.6.beta2.official [551ce8d47], see https://github.com/godotengine/godot/pull/114401

Might not crash, but at least hangs the editor.
v4.6.beta1.official [d743736f8]
v4.5.1.stable.official [f62fdbde1]

### System information

Godot v4.6.beta3 - Bazzite 43.20260101.0 (Kinoite) on Wayland - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 590.44.01) - 13th Gen Intel(R) Core(TM) i9-13900K (32 threads) - 125.5 GiB memory

### Issue description

Goto References works ok with just a blank project and AClass and BClass (see below). If I add GDUnit4 and do the same I get a segmentation fault.

```
Thread 111 "godot.linuxbsd." received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffed2ffe6c0 (LWP 15473)]
0x0000555558d4f018 in CowData<String>::size (this=0x7ffeb0fe3090)
    at ./core/templates/cowdata.h:170
170             _FORCE_INLINE_ Size size() const { return !_ptr ? 0 : *_get_size(); }


(gdb) bt
#0  0x0000555558d4f018 in CowData<String>::size (this=0x7ffeb0fe3090)
    at ./core/templates/cowdata.h:170
#1  0x0000555558d59462 in Vector<String>::size (this=0x7ffeb0fe3088)
    at ./core/templates/vector.h:92
#2  0x00005555596c5dd8 in GDScriptWorkspace::find_usages_in_file (
    this=0x55557b1960c0, p_symbol=..., p_file_path=...)
    at modules/gdscript/language_server/gdscript_workspace.cpp:440
#3  0x00005555596c5f11 in GDScriptWorkspace::find_all_usages (
    this=0x55557b1960c0, p_symbol=...)
    at modules/gdscript/language_server/gdscript_workspace.cpp:484
#4  0x00005555596b528c in GDScriptTextDocument::references (
    this=0x55557b1962f0, p_params=...)
    at modules/gdscript/language_server/gdscript_text_document.cpp:260
#5  0x00005555596ad83c in call_with_variant_args_ret_helper<GDScriptTextDocument, Array, Dictionary const&, 0ul> (p_instance=0x55557b1962f0,
    p_method=(Array (GDScriptTextDocument::*)(GDScriptTextDocument * const, const Dictionary &)) 0x5555596b516e <GDScriptTextDocument::references(Dictionary const&)>, p_args=0x7ffed2ffc670, r_ret=..., r_error=...)
    at ./core/variant/binder_common.h:673
#6  0x00005555596ac0e1 in call_with_variant_args_ret<GDScriptTextDocument, Array, Dictionary const&> (p_instance=0x55557b1962f0,
    p_method=(Array (GDScriptTextDocument::*)(GDScriptTextDocument * const, const Dictionary &)) 0x5555596b516e <GDScriptTextDocument::references(Dict--Type <RET> for more, q to quit, c to continue without paging--c
ionary const&)>, p_args=0x7ffed2ffc670, p_argcount=1, r_ret=...,
    r_error=...) at ./core/variant/binder_common.h:716
#7  0x00005555596aa39a in CallableCustomMethodPointer<GDScriptTextDocument, Array, Dictionary const&>::call (this=0x55557b1971d0,
    p_arguments=0x7ffed2ffc670, p_argcount=1, r_return_value=...,
    r_call_error=...) at ./core/object/callable_method_pointer.h:105
#8  0x000055555e539206 in Callable::callp (this=0x55557b1972e8,
    p_arguments=0x7ffed2ffc670, p_argcount=1, r_return_value=...,
    r_call_error=...) at core/variant/callable.cpp:57
#9  0x000055555e539548 in Callable::callv (this=0x55557b1972e8,
    p_arguments=...) at core/variant/callable.cpp:84
#10 0x0000555559fe54c3 in JSONRPC::process_action (this=0x55557b195cc0,
    p_action=..., p_process_arr_elements=true)
    at modules/jsonrpc/jsonrpc.cpp:128
#11 0x0000555559fe5a50 in JSONRPC::process_string (this=0x55557b195cc0,
    p_input=...) at modules/jsonrpc/jsonrpc.cpp:172
#12 0x0000555559694094 in GDScriptLanguageProtocol::process_message (
    this=0x55557b195cc0, p_text=...)
    at modules/gdscript/language_server/gdscript_language_protocol.cpp:154
#13 0x0000555559693bb4 in GDScriptLanguageProtocol::LSPeer::handle_data (
    this=0x7ffeb8a6f6e0)
    at modules/gdscript/language_server/gdscript_language_protocol.cpp:109
#14 0x0000555559695338 in GDScriptLanguageProtocol::poll (
    this=0x55557b195cc0, p_limit_usec=100000)
    at modules/gdscript/language_server/gdscript_language_protocol.cpp:285
#15 0x00005555596b01ad in GDScriptLanguageServer::thread_main (
    p_userdata=0x55557b1958d0)
    at modules/gdscript/language_server/gdscript_language_server.cpp:91
#16 0x000055555e267e7a in Thread::callback (p_caller_id=90,
    p_settings=...,
    p_callback=0x5555596b016e <GDScriptLanguageServer::thread_main(void*)>, p_userdata=0x55557b1958d0) at core/os/thread.cpp:64
#17 0x000055555e268b21 in std::__invoke_impl<void, void (*)(unsigned long, Thread::Settings const&, void (*)(void*), void*), unsigned long, Thread::Settings, void (*)(void*), void*> (
    __f=@0x555572725708: 0x55555e267dec <Thread::callback(unsigned long, Thread::Settings const&, void (*)(void*), void*)>)
    at /usr/include/c++/15.2.1/bits/invoke.h:63
#18 0x000055555e268a32 in std::__invoke<void (*)(unsigned long, Thread::Settings const&, void (*)(void*), void*), unsigned long, Thread::Settings, void (*)(void*), void*> (
    __fn=@0x555572725708: 0x55555e267dec <Thread::callback(unsigned long, Thread::Settings const&, void (*)(void*), void*)>)
    at /usr/include/c++/15.2.1/bits/invoke.h:98
#19 0x000055555e268917 in std::thread::_Invoker<std::tuple<void (*)(unsigned long, Thread::Settings const&, void (*)(void*), void*), unsigned long, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0x5555727256e8) at /usr/include/c++/15.2.1/bits/std_thread.h:303
#20 0x000055555e26887c in std::thread::_Invoker<std::tuple<void (*)(unsigned long, Thread::Settings const&, void (*)(void*), void*), unsigned long, Thread::Settings, void (*)(void*), void*> >::operator() (
    this=0x5555727256e8) at /usr/include/c++/15.2.1/bits/std_thread.h:310
#21 0x000055555e268860 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(unsigned long, Thread::Settings const&, void (*)(void*), void*), unsigned long, Thread::Settings, void (*)(void*), void*> > >::_M_run (this=0x5555727256e0) at /usr/include/c++/15.2.1/bits/std_thread.h:255
#22 0x000055555eefd674 in execute_native_thread_routine ()
#23 0x00007ffff7d2198b in ?? () from /usr/lib/libc.so.6
#24 0x00007ffff7da59cc in ?? () from /usr/lib/libc.so.6


(gdb) frame 2
#2  0x00005555596c5dd8 in GDScriptWorkspace::find_usages_in_file (
    this=0x55557b1960c0, p_symbol=..., p_file_path=...)
    at modules/gdscript/language_server/gdscript_workspace.cpp:440
440                     for (int i = 0; i < content.size(); ++i) {
(gdb) info locals
i = 5
content = @0x7ffeb0fe3088: {write = {<No data fields>}, _cowdata = {
    static MAX_INT = <optimized out>,
    static REF_COUNT_OFFSET = <optimized out>,
    static CAPACITY_OFFSET = <optimized out>,
    static SIZE_OFFSET = <optimized out>,
    static DATA_OFFSET = <optimized out>, _ptr = 0x1}}
usages = {write = {<No data fields>}, _cowdata = {
    static MAX_INT = <optimized out>,
    static REF_COUNT_OFFSET = <optimized out>,
    static CAPACITY_OFFSET = <optimized out>,
    static SIZE_OFFSET = <optimized out>,
    static DATA_OFFSET = <optimized out>, _ptr = 0x0}}
identifier = {_cowdata = {static MAX_INT = <optimized out>,
    static REF_COUNT_OFFSET = <optimized out>,
    static CAPACITY_OFFSET = <optimized out>,
    static SIZE_OFFSET = <optimized out>,
    static DATA_OFFSET = <optimized out>, _ptr = 0x5555637402f0 U"a"},
  static _null = 0 U'\000', static _replacement_char = 65533 U'�'}
parser = 0x7ffeb0fe2650


frame 3
#3  0x00005555596c5f11 in GDScriptWorkspace::find_all_usages (
    this=0x55557b1960c0, p_symbol=...)
    at modules/gdscript/language_server/gdscript_workspace.cpp:484
484                     usages.append_array(find_usages_in_file(p_symbol, path));
(gdb) print p_symbol
$1 = (const LSP::DocumentSymbol &) @0x7ffeb0ff9dc0: {name = {_cowdata = {
      static MAX_INT = <optimized out>,
      static REF_COUNT_OFFSET = <optimized out>,
      static CAPACITY_OFFSET = <optimized out>,
      static SIZE_OFFSET = <optimized out>,
      static DATA_OFFSET = <optimized out>, _ptr = 0x5555637402f0 U"a"},
    static _null = 0 U'\000', static _replacement_char = 65533 U'�'},
  detail = {_cowdata = {static MAX_INT = <optimized out>,
      static REF_COUNT_OFFSET = <optimized out>,
      static CAPACITY_OFFSET = <optimized out>,
      static SIZE_OFFSET = <optimized out>,
      static DATA_OFFSET = <optimized out>,
      _ptr = 0x7ffeb93de300 U"var a: AClass"}, static _null = 0 U'\000',
    static _replacement_char = 65533 U'�'}, documentation = {
    _cowdata = {static MAX_INT = <optimized out>,
      static REF_COUNT_OFFSET = <optimized out>,
      static CAPACITY_OFFSET = <optimized out>,
      static SIZE_OFFSET = <optimized out>,
      static DATA_OFFSET = <optimized out>, _ptr = 0x0},
    static _null = 0 U'\000', static _replacement_char = 65533 U'�'},
  native_class = {_cowdata = {static MAX_INT = <optimized out>,
      static REF_COUNT_OFFSET = <optimized out>,
      static CAPACITY_OFFSET = <optimized out>,
      static SIZE_OFFSET = <optimized out>,
      static DATA_OFFSET = <optimized out>, _ptr = 0x0},
    static _null = 0 U'\000', static _replacement_char = 65533 U'�'},
  kind = 13, deprecated = false, local = false, range = {start = {
      line = 2, character = 0}, end = {line = 2, character = 13}},
  selectionRange = {start = {line = 2, character = 4}, end = {line = 2,
      character = 5}}, uri = {_cowdata = {
      static MAX_INT = <optimized out>,
      static REF_COUNT_OFFSET = <optimized out>,
      static CAPACITY_OFFSET = <optimized out>,
      static SIZE_OFFSET = <optimized out>,
      static DATA_OFFSET = <optimized out>,
      _ptr = 0x7ffea994c990 U"file:///<snip repository location>lsp_test/b.gd"}, static _null = 0 U'\000',
    static _replacement_char = 65533 U'�'}, script_path = {_cowdata = {
      static MAX_INT = <optimized out>,
      static REF_COUNT_OFFSET = <optimized out>,
      static CAPACITY_OFFSET = <optimized out>,
      static SIZE_OFFSET = <optimized out>,
      static DATA_OFFSET = <optimized out>,
      _ptr = 0x7ffeb9699210 U"res://b.gd"}, static _null = 0 U'\000',
    static _replacement_char = 65533 U'�'}, children = {
    write = {<No data fields>}, _cowdata = {
      static MAX_INT = <optimized out>,
      static REF_COUNT_OFFSET = <optimized out>,
      static CAPACITY_OFFSET = <optimized out>,
      static SIZE_OFFSET = <optimized out>,
      static DATA_OFFSET = <optimized out>, _ptr = 0x0}}}
(gdb)
```

### Steps to reproduce

Test files:
```
class_name AClass extends Node

func test() -> void:
    print("test")
```

```
class_name BClass extends Node

var a: AClass # Put cursor on a and invoke Goto References

func _ready() -> void:
    a.test()


func _process(delta: float) -> void:
    a.test()

```

Add GDUnit as addon https://github.com/godot-gdunit-labs/gdUnit4/commit/c8d63a903b8be964b1564112abc18b95723bbb16.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes https://github.com/godotengine/godot/issues/114729 
It's closed since we used it to track a 4.6 regression. However the issue also mentions a hang which was present before and still is. This PR addresses this slowdown.

---

`resolve_symbol` is very expensive since it parses and analyzes the script, without any caching. For very short variable names this becomes a bottleneck, since a single char identifier like `a` can occur hundreds of times in a script.

This PR adds a cheaper intermediate check, which just tokenizes the identifier at that pos to filter false positives:

Example: Find references to `a` in `var my_variable = a`

Before this PR:
Four occurrences of `a` -> four calls to `resolve_symbol`

With this PR:
identifier for first occurrence is `var`, no call to `resolve_symbol`
identifier for second occurrence is `my_variable`,  no call to `resolve_symbol`
third occurrence is skipped since search is continued after `my_variable`
identifier for fourth occurrence is `a` -> call `resolve_symbol`

This significantly cuts down the time it takes to find references to such short identifiers in projects. (Can't give accurate times, since I did not fully wait for the search to finish before this PR.)

---

In theory this PR might have a negative impact for long identifier names because they are not prone to false positives from the fulltext search. However I think that's negligible because `get_identifier_under_position` is faster then `resolve_symbol` by a very large margin (in reasonably complex projects).

### CODE REVIEW

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 1]
```diff
@@ -451,18 +451,23 @@ Vector<LSP::Location> GDScriptWorkspace::find_usages_in_file(const LSP::Document
...
+						loc.uri = text_doc.uri;
+						loc.range.start = params.position;
+						loc.range.end.line = params.position.line;
+						loc.range.end.character = params.position.character + identifier.length();
+						usages.append(loc);
+					}
 				}
 
-				character = line.find(identifier, character + 1);
+				character = line.find(identifier, range.end.character);
```
Comment (HolonProduction) [inline modules/gdscript/language_server/gdscript_workspace.cpp]: The end of LSP ranges is exclusive. So the `+1` can be omitted.

**Review by akien-mga — APPROVED** [review]
LGTM.
