### PR TITLE
Batch GLES2 draw calls

### LINKED ISSUE #19917: Text rendering performance low due to missing batching
**Godot version:**

Godot 3.1 compiled with 54988df9ce0227d9f933f6f82e2f9f1d35df28c0

**OS/device including version:**

Android 7.1.2
Qualcomm® Adreno™ 430 GPU  OpenGL ES 3.1

**Issue description:**

Text rendering harms the FPS on Android with GLES3.
In the screenshots below the same scene rendered with diffrent text content.
More text rendered less FPS.

screenshot-1530551860525

screenshot-1530551712802

**Steps to reproduce:**
* Create a RichTextLabel and fill a long text as its text
* Export and run it on Android with GLES3

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by dragmz**
Fixes #19917

Adds GLES2 draw calls batching for the same render list item that uses
multiple rasterizer commands (e.g. Label node; a node with multiple
GDScript draw_* calls).

This does not cover glBufferSubData calls batching that I've tried to fix in #20077.

Some stats for the number of draw calls -

Before:

image

After:

image

### CODE REVIEW

File: drivers/gles2/shader_gles2.cpp [hunk 1]
```diff
@@ -1109,3 +1107,11 @@ ShaderGLES2::ShaderGLES2() {
...
 	finish();
 }
+
+bool ShaderGLES2::is_dirty() const {
+	if (active != this || !version || new_conditional_version.key != conditional_version.key) {
+		return true;
+	}
+
+	return false;
+}
```
Comment (oisincar) [inline drivers/gles2/shader_gles2.cpp]: Maybe you could just have:
```
return (active != this || !version || new_conditional_version.key != conditional_version.key);
```
(Just a very little thing in what looks like a really great PR, can't wait to see the speedup)

Comment (dragmz) [reply drivers/gles2/shader_gles2.cpp]: Thanks for catching this code smell, I'll clean it up.

**Comment by reduz** [comment]
Looks good to me, @karroffel ?

**Review by karroffel — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Just mentioning here for clarity that this was reverted in #21204.
