### PR TITLE
Fix editor crash when expanding/collapsing empty scene tree

### LINKED ISSUE #55523: Crash when clicking "Expand/Collapse All" button in the Scene tree dock if the scene has no nodes created
### Godot version

4.0.dev (89a4ab6c1)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

Clicking the following menu option will crash the editor:

image

(This button is only available in `master`, not `3.x`.)

Backtrace:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (b9d877e55fc469e7441cb00856359946b91d00ff)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3d320) [0x7ff428bcc320] (??:0)
[2] TreeItem::get_first_child() const (/home/hugo/Documents/Git/godotengine/godot/scene/gui/tree.cpp:586)
[3] SceneTreeDock::_is_collapsed_recursive(TreeItem*) const (/home/hugo/Documents/Git/godotengine/godot/editor/scene_tree_dock.cpp:1900)
[4] SceneTreeDock::_tool_selected(int, bool) (/home/hugo/Documents/Git/godotengine/godot/editor/scene_tree_dock.cpp:424)
[5] void call_with_variant_args_helper<SceneTreeDock, int, bool, 0ul, 1ul>(SceneTreeDock*, void (SceneTreeDock::*)(int, bool), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:228)
[6] void call_with_variant_args<SceneTreeDock, int, bool>(SceneTreeDock*, void (SceneTreeDock::*)(int, bool), Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:338)
[7] CallableCustomMethodPointer<SceneTreeDock, int, bool>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/./core/object/callable_method_pointer.h:97)
[8] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:51)
[9] Object::emit_signal(StringName const&, Variant const**, int) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1104)
[10] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1159)
[11] PopupMenu::activate_item(int) (/home/hugo/Documents/Git/godotengine/godot/scene/gui/popup_menu.cpp:1391)
[12] PopupMenu::gui_input(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/gui/popup_menu.cpp:394)
[13] void call_with_variant_args_helper<PopupMenu, Ref<InputEvent> const&, 0ul>(PopupMenu*, void (PopupMenu::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:223)
[14] void call_with_variant_args<PopupMenu, Ref<InputEvent> const&>(PopupMenu*, void (PopupMenu::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:338)
[15] CallableCustomMethodPointer<PopupMenu, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/./core/object/callable_method_pointer.h:97)
[16] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:51)
[17] Object::emit_signal(StringName const&, Variant const**, int) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1104)
[18] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1159)
[19] Window::_window_input(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/main/window.cpp:921)
[20] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:223)
[21] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:338)
[22] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/./core/object/callable_method_pointer.h:97)
[23] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:51)
[24] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/display_server_x11.cpp:2970)
[25] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/display_server_x11.cpp:2954)
[26] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/hugo/Documents/Git/godotengine/godot/core/input/input.cpp:638)
[27] Input::flush_buffered_events() (/home/hugo/Documents/Git/godotengine/godot/core/input/input.cpp:857)
[28] DisplayServerX11::process_events() (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/display_server_x11.cpp:3818)
[29] OS_LinuxBSD::run() (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/os_linuxbsd.cpp:338)
[30] bin/godot.linuxbsd.tools.64.llvm(main+0x1c6) [0x462d2f6] (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/godot_linuxbsd.cpp:58)
[31] /lib64/libc.so.6(__libc_start_main+0xd5) [0x7ff428bb6b75] (??:0)
[32] bin/godot.linuxbsd.tools.64.llvm(_start+0x2e) [0x462d06e] (??:?)
-- END OF BACKTRACE --
================================================================
[1]    44424 IOT instruction (core dumped)  bin/godot.linuxbsd.tools.64.llvm /tmp/4/project.godot
```

### Steps to reproduce

- Create a new scene.
- Click the 3 vertical dots icon on the right of the Scene tree dock and choose **Expand/Collapse All**.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by and-rad**
Fixes #55523

The scene tree dock performs an additional check to see if the tree contains any children. If not, it just stops.

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -419,6 +419,9 @@ void SceneTreeDock::_tool_selected(int p_tool, bool p_confirm_override) {
 
 			if (!selected_item) {
 				selected_item = tree->get_root();
+				if (!selected_item) {
+					break;
```
Comment (Calinou) [inline editor/scene_tree_dock.cpp:423]: `return;` might be a better choice here, I'm not sure.

Comment (and-rad) [reply editor/scene_tree_dock.cpp:423]: I can do that. The reason I used `break` was for consistency with how it's done in other `case` blocks in that function.

Comment (KoBeWi) [reply editor/scene_tree_dock.cpp:423]: `break` is used everywhere in this function, so it's ok to leave it.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
