### PR TITLE
Core: Fix `Basis::get_euler` incorrectly simplifying rotations in some cases.

### LINKED ISSUE #49839: Potential problem in look_at()
### Godot version

3.3.2.stable.official

### System information

macOS 11.3.1 GLES3

### Issue description

When using the `look_at()` function in a script attached to a camera, there seems to be some sort of discretization effect occurring in my tests; for a camera positioned at e.g. `(0,90,0)` looking towards `(0,0,0)`, I see rendering artifacts. These artifacts persist for a small region around `(0,0,0)` on the `x,z` plane (approx. +/- 0.1 units).

This effect is particularly jarring when it manifests as part of an animated movement, producing an effect almost like a magnet snapping the camera view direction onto the target location at `(0,0,0)`.

I've attached an example project to demonstrate this effect; a camera is located at `(0,90,0)` above a simple plane, and the `look_at()` method is invoked in the camera's `_process()` method. The target position is slowly moved left and right via a `sin()` function, and the effect is visible when the camera looks in the vicinity of `(0,0,0)`.

Am I missing something important, here?

### Steps to reproduce

See issue description, and attached project file.

### Minimal reproduction project

[Weird.zip](https://github.com/godotengine/godot/files/6697007/Weird.zip)

### PR DESCRIPTION
**Pull request by Cwazywierdo**
Fixes #49839 

A large testing threshold would sometimes cause `Basis::get_euler` to incorrectly assume a rotation could simplified. This would cause certain rotations with a range of +-0.26° to be effectively truncated, depending on the rotation order and axis. Using the MRP from #49839 for testing, I determined  that `0.00000025` was the largest threshold where the truncation was visually unnoticeable (Range of +-0.04°).

| Master | PR |
|--------|--------|
| master | pr |
| Threshold: 0.00001 (CMP_EPSILON) | Threshold: 0.00000025 |
| Error Range: +-0.26° | Error Range: +-0.04° |

### CODE REVIEW

File: core/math/basis.cpp [hunk 1]
```diff
@@ -455,6 +455,8 @@ void Basis::get_rotation_axis_angle_local(Vector3 &p_axis, real_t &p_angle) cons
 }
 
 Vector3 Basis::get_euler(EulerOrder p_order) const {
+	const real_t epsilon = 0.00000025;
```
Comment (RedMser) [inline core/math/basis.cpp:458]: A code comment should explain how this value came to be, so future devs won't have to look up this PR for context.

**Review by TokageItLab — APPROVED** [review]

**Comment by TokageItLab** [comment]
BTW, this is not related to this PR, but I remember that Quaternion's `is_normalized()` has a similar accuracy problem, so this might be a good opportunity to rethink the epsilon values.

**Review by fire — APPROVED** [review]

**Comment by lawnjelly** [comment]
My first thoughts are, why is this epsilon needed at all?

If it is for `asin` (which errors outside -1 to 1), the `Math::asin()` is a safe version which won't error. I do however notice that for YXZ at line 540 it doesn't seem to be using the `Math` versions, that should be corrected, as we should prefer the Math versions especially for asin / acos because they are safe.

I don't know if `atan2` has any strange out of range behaviour that the epsilons helped with, but from memory `atan2` is fairly robust (unless x and y are zero).

**Review by aaronfranke — APPROVED** [review]
With this code, in single-precision, this means that the value is allowed to be up to 3 ULPs away in order to pass the check and run the simpler code (the expression `1.0f - epsilon` is 4 ULPs away from `1.0f`). This is a fairly narrow margin of error if we expect to be working with values calculated from other things.

However, in this particular case, the point of these checks is to handle the common cases where Euler angle rotation happens in only one direction / around one axis with better accuracy. In those cases, we expect the values to be exact, because they shouldn't be altered (if you rotate in the XY plane around Z, then Z shouldn't be changed). This purpose is actually already evident by the `== 0` checks under the `// is this a pure Y rotation?` comments.

I wrote similar code last year for my 4D module for decomposing a Basis4D into 4D Euler angles (6 numbers), though it's simpler in that it only handles one Euler order. Suffice to say, the purpose of this code is pretty clear to me.

Anyway, this means that a more strict check should be absolutely fine with the expected use case. Even exact equality should still do the trick (as @lawnjelly mentions above). As the OP shows, the current check is too broad since it produces visual errors. Besides, the general code path still works even for the special cases. Therefore I think this is a good change, I don't think there are any downsides.

The only notes I have is that I would add to the comment to mention that 1.0 minus this value is 4 ULPs away from 1.0 in single precision, to give a 3 ULPs margin (maybe this can be worded more concisely / simply), and that @lawnjelly's comment above about potentially not needing an epsilon here at all is very valid too.

**Comment by Cwazywierdo** [comment]
While I was trying to determine the ideal epsilon value, I actually did consider getting rid of it entirely. When I looked at the PR that introduced it though (#39483), the author claimed that it solved a nondescript "floating point issue." Without any other information on the actual issue, I figured it would be better to keep it and avoid a possible regression. I will change this if it's considered unnecessary.

I will definitely go ahead and change those function calls to the Math versions though.

**Comment by lawnjelly** [comment]
Worth tagging @AndreaCatania and @RevoluPowered , I don't know if they are still contributing but they might remember why the epsilon was introduced.

**Review by Repiteo — APPROVED** [review]
We'll send it as-is for the time being. If we want global consistency in the future, there's always `CMP_EPSILON2`; though that might be better suited for a PR focused on the math constants as a whole

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
