### PR TITLE
Fix redraw timing in `AnimationBlendTreeEditor`

### LINKED ISSUE #45437: AnimationNodeTransition does not visually update upon changing input count or input names
**Godot version:**

v3.2.3-stable

**OS/device including version:**

Manjaro Linux, running kernel `5.9.1-1-rt19-MANJARO` (64-bit), using KDE with Plasma version `5.20.4` in X11.

Using an Nvidia GeForce GTX 1060 6GB with driver version 455.45.01.

Performed in 2D mode, using GLES3.

**Issue description:**

Upon updating an Transition node's "Input Count" property or any input of the Transition node's "Name" property within an AnimationNodeBlendTree will not visually update the number of inputs or the names of the inputs until another node is added to the AnimationNodeBlendTree. 

Closing the editor (that is, quitting to the project list or closing the program entirely) and reopening the project also visually updates the Transition node. Closing the scene and reopening it does not update the Transition node.

Deleting the node and then undoing the action will also update the Transition node.

Deleting the parent AnimationTree and then undoing the action does not update the Transition node.

**Steps to reproduce:**
1. Within an AnimationNodeBlendTree, place a Transition node.
2. Update the "Input Count" parameter and/or the "Name" parameter of any input of the Transition node.
3. Place any other node within the AnimationNodeBlendTree to update the Transition node, OR close and reopen the project in its entirety, OR delete the Transition node and undo the action.

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/5864192/example.zip)

### LINKED ISSUE #49375: Animation Transition node wont update until conected.
**Godot version:**
Godot 3.3

**OS/device including version:**
MX Linux

**Issue description:**
Updating the inputs for the Transition Node wont reflect any change until reconected

**Steps to reproduce:**
Create a Animation Tree
Add AnimationNodeBlendTree as the RootNode
Add Transition Node
Add inputs
You wont see any updates in the node until reconected to something

AnimTree

**Minimal reproduction project:**
New project is fine

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #49375. Fixes #45437.
Supersedes #52296.

- Made `NodeTransition` to redraw when the number or name of input port is changed
- Made `NodeAnimation`'s animation list to redraw when the `AnimationTree`'s `AnimationPlayer` is changed
  - Made `AnimationNodeBlendTreeEditor::update_graph()` to public

There is a bug that doesn't undo disconnect correctly when the number of NodeTransition's ports is reduced, but it requires a large implementation to undo correctly, so I put that in the comments.

Before:

https://user-images.githubusercontent.com/61938263/187948275-1829605d-b412-46e4-a9b3-d3753de9e658.mp4

After:

https://user-images.githubusercontent.com/61938263/187948292-4a8e822b-a41d-4740-8dca-0fd19788668b.mp4

### CODE REVIEW

File: scene/animation/animation_tree.cpp [hunk 1]
```diff
@@ -1771,6 +1776,18 @@ void AnimationTree::_notification(int p_what) {
 }
 
 void AnimationTree::set_animation_player(const NodePath &p_player) {
+	AnimationPlayer *new_player = Object::cast_to<AnimationPlayer>(get_node(p_player));
```
Comment (reduz) [inline scene/animation/animation_tree.cpp:1779]: The problem I see with this is that, if you load the scene, it is unlikely at load time you will be able to resolve this path because the node is not even added to the parent yet. 

I would move this to a separate function `_setup_animation_player`. You can call it from here only if `is_inside_tree()` returns `true`, otherwise you will have to call it from `NOTIFICATION_ENTER_TREE`.

**Review by reduz — CHANGES_REQUESTED** [review]

**Comment by TokageItLab** [comment]
@reduz Implemented the method you pointed out as `_setup_animation_player()`.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
