### PR TITLE
Fix light related crashes

### LINKED ISSUE #33007: Godot crashes when using OmniLight and CSGSphere
**Godot version:**
3.2.alpha.custom_build. 8c3a5057c

**OS/device including version:**
Ubuntu 19.04, GTX 970
**Issue description:**
Backtrace GLES 2
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fb1a277af60] (??:0)
[2] RasterizerSceneGLES2::_add_geometry_with_material(RasterizerStorageGLES2::Geometry*, RasterizerScene::InstanceBase*, RasterizerStorageGLES2::GeometryOwner*, RasterizerStorageGLES2::Material*, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:1172)
[3] RasterizerSceneGLES2::_add_geometry(RasterizerStorageGLES2::Geometry*, RasterizerScene::InstanceBase*, RasterizerStorageGLES2::GeometryOwner*, int, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:1006 (discriminator 2))
[4] RasterizerSceneGLES2::_fill_render_list(RasterizerScene::InstanceBase**, int, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:1261 (discriminator 4))
[5] RasterizerSceneGLES2::render_scene(Transform const&, CameraMatrix const&, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:3313)
[6] VisualServerScene::_render_scene(Transform, CameraMatrix const&, bool, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:2187)
[7] VisualServerScene::render_camera(RID, RID, Vector2, RID) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:1757 (discriminator 2))
[8] VisualServerViewport::_draw_3d(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:66)
[9] VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:109)
[10] VisualServerViewport::draw_viewports() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:345)
[11] VisualServerRaster::draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_raster.cpp:109 (discriminator 2))
[12] VisualServerWrapMT::thread_draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:46)
[13] CommandQueueMT::Command2<VisualServerWrapMT, void (VisualServerWrapMT::*)(bool, double), bool, double>::call() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:301 (discriminator 4))
[14] CommandQueueMT::flush_one(bool) (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:427)
[15] CommandQueueMT::wait_and_flush_one() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:460)
[16] VisualServerWrapMT::thread_loop() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:70)
[17] VisualServerWrapMT::_thread_callback(void*) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:58)
[18] ThreadPosix::thread_callback(void*) (/mnt/KubuntuWolne/godot/drivers/unix/thread_posix.cpp:76)
[19] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7fb1a2c7d182] (??:0)
[20] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fb1a2854b1f] (??:0)
```
Backtrace GLES 3
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7ff8d288cf60] (??:0)
[2] RasterizerSceneGLES3::_setup_light(RasterizerSceneGLES3::RenderList::Element*, Transform const&) (/mnt/KubuntuWolne/godot/drivers/gles3/rasterizer_scene_gles3.cpp:1894)
[3] RasterizerSceneGLES3::_render_list(RasterizerSceneGLES3::RenderList::Element**, int, Transform const&, CameraMatrix const&, unsigned int, bool, bool, bool, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles3/rasterizer_scene_gles3.cpp:2255)
[4] RasterizerSceneGLES3::render_scene(Transform const&, CameraMatrix const&, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/drivers/gles3/rasterizer_scene_gles3.cpp:4535 (discriminator 9))
[5] VisualServerScene::_render_scene(Transform, CameraMatrix const&, bool, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:2187)
[6] VisualServerScene::render_camera(RID, RID, Vector2, RID) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:1757 (discriminator 2))
[7] VisualServerViewport::_draw_3d(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:66)
[8] VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:109)
[9] VisualServerViewport::draw_viewports() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:345)
[10] VisualServerRaster::draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_raster.cpp:109 (discriminator 2))
[11] VisualServerWrapMT::thread_draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:46)
[12] CommandQueueMT::Command2<VisualServerWrapMT, void (VisualServerWrapMT::*)(bool, double), bool, double>::call() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:301 (discriminator 4))
[13] CommandQueueMT::flush_one(bool) (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:427)
[14] CommandQueueMT::wait_and_flush_one() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:460)
[15] VisualServerWrapMT::thread_loop() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:70)
[16] VisualServerWrapMT::_thread_callback(void*) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:58)
[17] ThreadPosix::thread_callback(void*) (/mnt/KubuntuWolne/godot/drivers/unix/thread_posix.cpp:76)
[18] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7ff8d2d8f182] (??:0)
[19] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7ff8d2966b1f] (??:0)

```
**Steps to reproduce:**

1. Read Project README - https://github.com/qarmin/The-worst-Godot-test-project#the-worst-godot-test-project
2. Run Project

**Minimal reproduction project:**
[The-worst-Godot-test-project.tar.gz](https://github.com/godotengine/godot/files/3762357/The-worst-Godot-test-project.tar.gz)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/33007

@qarmin Can you test this out? I wasn't able to reproduce the GLES3 crash, but this should fix it.

### CODE REVIEW

**Comment by qarmin** [comment]
Yes, this fixes issue on my machine with GLES 2 crash, but with GLES 3 `if` should look a little different to prevent crash

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -1887,8 +1887,8 @@ void RasterizerSceneGLES3::_setup_light(RenderList::Element *e, const Transform
 		const RID *lights = e->instance->light_instances.ptr();
 
 		for (int i = 0; i < lc; i++) {
-			LightInstance *li = light_instance_owner.getptr(lights[i]);
-			if (li->last_pass != render_pass) //not visible
+			LightInstance *li = light_instance_owner.getornull(lights[i]);
+			if (li && li->last_pass != render_pass) //not visible
```
Comment (qarmin) [inline drivers/gles3/rasterizer_scene_gles3.cpp]: Should be `if ( !li || li->last_pass` like in GLES 2

**Review by qarmin — CHANGES_REQUESTED** [review]

File: drivers/gles3/rasterizer_scene_gles3.cpp (hunk 1 above)
Comment (clayjohn) [reply drivers/gles3/rasterizer_scene_gles3.cpp]: Good idea. I was using ``li`` to avoid a null pointer read, but ``!li ||`` is much better to avoid issues further down.

**Comment by clayjohn** [comment]
@qarmin Thanks for the feedback!

**Comment by akien-mga** [comment]
Thanks!
