### PR TITLE
Tweak the GradientTexture property hint to follow CurveTexture

### LINKED ISSUE #50249: Setting a GradientTexture's width to 999999999 crashes the editor.
### Godot version

3.3.2.stable.official

### System information

Windows 10, Intel HD Graphics

### Issue description

Setting a _GradientTexture_'s _width_ to _999999999_ crashes the editor.

### Steps to reproduce

This is the setup I had:

A _Sprite_ with a _GradientTexture_ as its _Texture_, and its _width_ set to _999999999_.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Calinou**
This prevents setting too large values and crashing the editor.

This closes https://github.com/godotengine/godot/issues/50249.

### CODE REVIEW

File: scene/resources/texture.cpp [hunk 1]
```diff
@@ -1762,7 +1762,7 @@ void GradientTexture::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("_update"), &GradientTexture::_update);
 
 	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "gradient", PROPERTY_HINT_RESOURCE_TYPE, "Gradient"), "set_gradient", "get_gradient");
-	ADD_PROPERTY(PropertyInfo(Variant::INT, "width", PROPERTY_HINT_RANGE, "1,2048,1,or_greater"), "set_width", "get_width");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "width", PROPERTY_HINT_RANGE, "32,4096"), "set_width", "get_width");
```
Comment (akien-mga) [inline scene/resources/texture.cpp:1765]: Shouldn't there be a min value?

Comment (akien-mga) [reply scene/resources/texture.cpp:1765]: Ah nevermind, I guess the step is optional.
I don't think we should restrict min value to 32, it can be an artistic choice to use a gradient with e.g. 4 steps.

Comment (Calinou) [reply scene/resources/texture.cpp]: Changed to allow widths as low as 1. I also applied the same change to CurveTexture and Curve3Texture for consistency.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
