### PR TITLE
Fix incorrect rendering of vcs dialogs

### LINKED ISSUE #69509: "Create Version Control Metadata" pop up window is glitching
### Godot version

Godot 4.0 Beta 7

### System information

Ubuntu 22.04 LTS, AMD RX570 8GB

### Issue description

When pressing "Create Version Control Metadata" a glitching window pops up, tested on both Standard and .NET 6.0 versions of Godot. 
Godot Create VC Metadata

### Steps to reproduce

At the top left menu, click on Project > Version Control > Create Version Control Metadata

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Chaosus**
I found that's glitched because window added as a child of `PopupMenu`.

Before the fix:

image

After the fix:

image

- Fix https://github.com/godotengine/godot/issues/69509

### CODE REVIEW

File: editor/plugins/version_control_editor_plugin.cpp [hunk 1]
```diff
@@ -1574,6 +1574,8 @@ VersionControlEditorPlugin::VersionControlEditorPlugin() {
 
 VersionControlEditorPlugin::~VersionControlEditorPlugin() {
 	shut_down();
+	memdelete(metadata_dialog);
+	memdelete(set_up_dialog);
```
Comment (akien-mga) [inline editor/plugins/version_control_editor_plugin.cpp:1578]: Seems fine for now, but this should likely be refactored at some point to be like other editor plugins. Normally `*EditorPlugin` classes have a dedicated root node which owns everything, and whose lifecycle is handled by EditorNode (I think).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
