### PR TITLE
[TextEdit / LineEdit] Add support for OEM Alt codes input.

### LINKED ISSUE #9981: Add alt code input feature
### Describe the project you are working on

An incremental game (this is not really project specific, although I work with a lot of text strings like flavor text in it, so those small inconeniences might slowly accumulate over time)

### Describe the problem or limitation you are having in your project

Using "alt codes" for entering special characters does not seem to work in the editor, including code editor, inspector input fields and other input fields in the editor. So, holding down Alt, then entering a valid numerical code on the numpad while Num Lock is active results in no special symbol being inserted. That includes the code editor and the editor input fields; and, since the editor is said to use the Godot UI system itself, it also extends to nodes like LineEdit in games as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the alt code input functionality to the text editors.
I feel like I probably don't need to describe how it should work since it's base functionality in a lot of regular desktop programs such as text editors and web browsers.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Just like in most other text input fields in other programs, when the user holds Alt and types a combination of numbers on the numeric keypad while having Num Lock on and then releases Alt, the required symbol will be entered.

For example, Alt + 0151 corresponds to  — (the em dash symbol)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around by just opening any text editor or any program with a text input field (such as a web browser), entering a combination in here and copying the resulting symbol.

### Is there a reason why this should be core and not an add-on in the asset library?

I feel like it doesn't make sense for this feature to be a separate add-on or a library, considering how it's usually just supported out-of-the-box, so might either just add it as core functionality or not (and reject this proposal in the latter case).

### LINKED ISSUE #83294: Implement support for Alt code text input on Windows
### Godot version

4.1

### System information

win10

### Issue description

it's quite rare to find editors that don't support Alt-codes (after all, they are part of the native OS).

This unfortunately makes Godot much less useful for making internationally supported applications and games involving lots of text entry.

Indeed, I agree on this. At least, for me this has been a major draw back that ultimately kept me away from Godot. It's not just because it makes coding a slow and painful process (which does matter), but also due to the fact that it makes Godot a rather US-centric app — i.e., assumes users are working on a US keyboard.

### Steps to reproduce

alt+62 alt+60 
It doesn't work

### Minimal reproduction project

f

### PR DESCRIPTION
**Pull request by bruvzg**
In addition to existing Unicode Alt codes (`Alt` + `Num+` + hex code):
- Adds support for OEM (CP437) Alt codes (`Alt` + dec code without leading zero).
- Adds support for Windows (CP1252) Alt codes (`Alt` + dec code with leading zero).
- Codes greater than `255` produces Unicode characters.

Fixes https://github.com/godotengine/godot-proposals/issues/9981
Fixes https://github.com/godotengine/godot/issues/83294

### CODE REVIEW

**Comment by Mickeon** [comment]
How come it's a draft?

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -446,10 +446,65 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
...
+						};
+						char32_t ucodestr[2] = { oem437[alt_code], 0 };
+						insert_text_at_caret(ucodestr);
+					} else if (alt_code > 0xFF) {
+						char32_t ucodestr[2] = { (char32_t)alt_code, 0 };
+						insert_text_at_caret(ucodestr);
+					}
+				} else if (alt_mode == ALT_INPUT_WIN) {
+					if (alt_code > 0x00 && alt_code <= 0xFF) {
+						static char32_t cp1252[256] = {
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp:482]: These too

Comment (bruvzg) [reply scene/gui/line_edit.cpp]: Moved to `char_range.inc`.

**Comment by Calinou** [comment]
@bruvzg Could you look into rebasing this so I can review it?

**Comment by bruvzg** [comment]
Unicode Alt input was previously changed to display input code as `uXXXX`, so I have updated this to do the same for OEM/Win codes as well for consistency (displayed as `oXXX` and `wXXX`).

**Review by Calinou — COMMENTED** [review]
Tested locally on LineEdit and TextEdit (Linux), it works as expected.

Code looks good to me.

https://github.com/user-attachments/assets/aadc87f9-cf4a-4f33-8eb0-819acce823b6

I suggest adding these notes to `TextEdit.xml` and `LineEdit.xml` at the end of their class description (before other notes):

```
		While entering text, it is possible to insert special characters using Unicode, OEM or Windows alt codes:
		- To enter Unicode codepoints, hold [kbd]Alt[/kbd] and type the codepoint on the numpad. For example, to enter the character [code]á[/code] (U+00E1), hold [kbd]Alt[/kbd] and type [kbd]+E1[/kbd] on the numpad (the leading zeroes can be omitted).
		- To enter OEM codepoints, hold [kbd]Alt[/kbd] and type the code on the numpad. For example, to enter the character [code]á[/code] (OEM 160), hold [kbd]Alt[/kbd] and type [code]160[/code] on the numpad.
		- To enter Windows codepoints, hold [kbd]Alt[/kbd] and type the code on the numpad. For example, to enter the character [code]á[/code] (Windows 0225), hold [kbd]Alt[/kbd] and type [kbd]0[/kbd], [kbd]2[/kbd], [kbd]2[/kbd], [kbd]5[/kbd] on the numpad. The leading zero here must [b]not[/b] be ommitted, as this is how Windows codepoints are distinguished from OEM codepoints.
```

**Comment by bruvzg** [comment]
> I suggest adding these notes to TextEdit.xml and LineEdit.xml at the end of their class description (before other notes)

Added.

**Review by Calinou — APPROVED** [review]

**Comment by CsloudX** [comment]
I'm make a app with code scanner, this feature was very useful. need this.

**Review by Repiteo — APPROVED** [review]
Looks great!

**Comment by Repiteo** [comment]
Thanks!
