### PR TITLE
Fix some issues found by clang sanitizers.

### LINKED ISSUE #59741: `call on address which does not point to an object` crash when opening editor compiled with address sanitizer.
### Godot version

`4.0`, b0df742cbe

### System information

macOS 12.3 (21E230) on M1 Mac.

### Issue description

```
core/object/method_bind.h:217:51: runtime error: member call on address 0x00013ba35d90 which does not point to an object of type 'MethodBindVarArgTR<Object, Error>'
AddressSanitizer: nested bug in the same thread, aborting.
```

Probably related to https://github.com/godotengine/godot/pull/58436

### Steps to reproduce

Run an editor compiled with `use_asan=yes`.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #59741
Fixes crash of the `--test` run, due to dereferencing of unset `EditorSettings::get_singleton()`.

```
modules/gdscript/gdscript.cpp:827:59: runtime error: member call on null pointer of type 'EditorSettings'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior modules/gdscript/gdscript.cpp:827:59 in
editor/editor_settings.cpp:1115:24: runtime error: member call on null pointer of type 'const EditorSettings *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior editor/editor_settings.cpp:1115:24 in
```

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @piiertho

**Comment by piiertho** [comment]
I don't think there will be a non static implem of this CRTP in future, so should be ok :)

File: core/object/method_bind.h [hunk 1]
```diff
@@ -214,7 +214,7 @@ class MethodBindVarArgBase : public MethodBind {
 
 private:
 	PropertyInfo _gen_return_type_info() const {
```
Comment (piiertho) [inline core/object/method_bind.h:216]: Can't it be static too now ?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
