### PR TITLE
Fix `Input.is_action_just_pressed` flicker on joypad axes

### LINKED ISSUE #81975: `Input.is_action_just_pressed` flickers when action is tied to an input axis (joystick direction)
### Godot version

4.2.dev5

### System information

linux, wired switch pro controller

### Issue description

may be related to https://github.com/godotengine/godot/pull/81170 (as before that, my axes were getting stuck, but since then I get this bug). (although I didn't bisect or anything, I just remember that)

I have an action tied to an input axis (a joystick direction).
This happens as I move my joystick in the direction of the action:

[simplescreenrecorder-2023-09-20_13.57.30.webm](https://github.com/godotengine/godot/assets/71937306/a0cb18dd-f66b-44f7-af75-6f20ba4cf877)

(red circle is deadzone)

### Steps to reproduce

1. assign a controller axis to an action
2. print `Input.is_action_just_pressed("your_action")` in `_process`
3. wiggle your stick

### Minimal reproduction project

[axis_jittering.zip](https://github.com/godotengine/godot/files/12672834/axis_jittering.zip)

### PR DESCRIPTION
**Pull request by ErezShahaf**
Fixes #81975
Pressed tick assignments were in the wrong scope, ended up updating pressed_frame even when it shouldn't and therefore the just_press would return true every time that the strength changes and not only when there's a new press.

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -706,16 +706,16 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
 						if (!action.axis_pressed) {
 							action.pressed++;
 							action.axis_pressed = true;
+							if (action.pressed == 1) {
+								action.pressed_physics_frame = Engine::get_singleton()->get_physics_frames();
+								action.pressed_process_frame = Engine::get_singleton()->get_process_frames();
+							}
 						}
 					} else {
 						action.pressed++;
```
Comment (Sauermann) [inline core/input/input.cpp:715]: With these changes, in this else-branch the pressed-frame is now no longer set. This would lead to missing pressed-frame info's for Actions that are caused by keyboard events.

**Review by Sauermann — CHANGES_REQUESTED** [review]

File: core/input/input.cpp (hunk 1 above)
Comment (ErezShahaf) [reply core/input/input.cpp:712]: Woops, my bad.
I fixed it with new flag is_new_press and returned the pressed frame assignments the original scope.

Tested for both axis, and keyboard input. Both presses and "just_pressed" functionality work well now.

**Comment by ErezShahaf** [comment]
Uhmm, not sure why the automated tests did not run for the last commit but my latest commit should fix the failed tests.

File: core/input/input.cpp [hunk 2]
```diff
@@ -697,29 +697,28 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
 	for (const KeyValue<StringName, InputMap::Action> &E : InputMap::get_singleton()->get_action_map()) {
 		if (InputMap::get_singleton()->event_is_action(p_event, E.key)) {
 			Action &action = action_state[E.key];
+			bool is_joystick = jm.is_valid();
 			bool is_pressed = false;
-
+			bool is_joystick_valid_zone_enter = false;
 			if (!p_event->is_echo()) {
 				if (p_event->is_action_pressed(E.key)) {
```
Comment (Sauermann) [inline core/input/input.cpp:704]: The variables scope can be reduced.
```suggestion
			if (!p_event->is_echo()) {
				if (p_event->is_action_pressed(E.key)) {
					bool is_joystick_valid_zone_enter = false;
```

**Review by Sauermann — APPROVED** [review]

**Comment by Sauermann** [comment]
With the exception of the comments, the changes are looking good. Only reviewed code, but didn't test it.

**Comment by Calinou** [comment]
This is how the MRP linked in https://github.com/godotengine/godot/pull/81170#issuecomment-1699867615 behaves:

### master 42425baa5

https://github.com/godotengine/godot/assets/180032/936468ef-bd7c-4f8b-892c-6116278d1891

### This PR

https://github.com/godotengine/godot/assets/180032/893b224a-8c8d-4653-b88c-c9a58ca6bee7

I still notice two issues:

- On both `master` and this PR, the strength of the "Both" action (an action that is activated by both keyboard and gamepad events) remains on 100% when the keyboard is released if the gamepad is held still above 0%.
- Controller strength sometimes flickers wildly, but I don't know exactly why. This may be related to mouse movement (I'm using a DualSense which has a touchpad that moves the mouse when you touch it).

**Review by Eoin-ONeill-Yokai — APPROVED** [review]
Once @Sauermann 's issues are resolved, I think this is good to go.

I've tested it with a few devices on my end and the axis "just_pressed" flag triggers appropriately only when entering the deadzone. Additionally, "just_released" works as expected as well. 

I didn't observe any flickering inputs on my end compared to @Calinou 's observations. Having said that, I'm using mostly DS4, 8BitDo and Xbox Series X Controllers. The Series X controller on linux seems to register inputs twice still (looking into a solution to this still, if possible) but otherwise it seemed to behave akin to how master behaves.

**Comment by akien-mga** [comment]
Please remember to squash the commits while addressing the code review comments. See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

File: core/input/input.cpp [hunk 3]
```diff
@@ -697,29 +697,28 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
 	for (const KeyValue<StringName, InputMap::Action> &E : InputMap::get_singleton()->get_action_map()) {
 		if (InputMap::get_singleton()->event_is_action(p_event, E.key)) {
 			Action &action = action_state[E.key];
+			bool is_joystick = jm.is_valid();
```
[the remark this answers is not in the document]
Comment (KoBeWi) [reply core/input/input.cpp:700]: While it doesn't matter that much performance-wise, it makes the code a bit more readable. Though I'd call this variable `is_joypad_axis` to be more clear.

**Comment by akien-mga** [comment]
I squashed the commits and addressed the review comments myself.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
