### PR TITLE
Fix missing dependency warning popup

### LINKED ISSUE #82243: Dependency warning popup no longer works.
### Godot version

fb4c0cf4624b1e3e738cf391e20cf2c08d76be9c

### System information

Windows 11

### Issue description

The window that warns and gives the user the oppertunity to fix and broken resource dependencies in scenes no longer pops up. Instead, the scene will attempt to load regardless, potentially corrupting the scene.

### Steps to reproduce

- Create a scene
- Create a Sprite2D object
- Assign the icon texture to the sprite
- Close the scene
- Delete the icon texture
- Attempt to reopen the scene

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes #82243

In older versions of Godot, a popup would appear when a scene was loaded which contained broken dependencies and would give the user an oppertunity to either cancel loading the scene or attempt to fix the dependencies. This seems may have been broken for a while due to changes the ResourceLoader. Since the ResourceLoader is now multithreaded, the callback for broken dependencies now uses a deferred call, but the load_scene function used by the EditorNode only ever requests that loading be done from the main thread. Immediately after the loading is performed, it would check for any dependency_errors list. However, since the callback is now deferred, the updates to the dependency_errors list would not be performed until the end of the frame, skipping the check entirely.

This PR attempts to fix this bug by making it so that if a broken dependency is detected, but the loading is being done on the main thread, it will do a direct callback rather than a deferred call. This fixes the bug and allows the warning popup to be seen again in the event of a broken scene.

godot windows editor dev x86_64_UWiLWOV8SJ

### CODE REVIEW

File: core/io/resource_loader.h [hunk 1]
```diff
@@ -230,7 +230,13 @@ class ResourceLoader {
...
 	static void notify_dependency_error(const String &p_path, const String &p_dependency, const String &p_type) {
 		if (dep_err_notify) {
-			callable_mp_static(dep_err_notify).bind(p_path, p_dependency, p_type).call_deferred();
+			if (Thread::get_caller_id() == Thread::get_main_id()) {
+				Callable::CallError ce;
+				Variant ret;
+				callable_mp_static(dep_err_notify).bind(p_path, p_dependency, p_type).callp(nullptr, 0, ret, ce);
+			} else {
+				callable_mp_static(dep_err_notify).bind(p_path, p_dependency, p_type).call_deferred();
+			}
```
Comment (RandomShaper) [inline core/io/resource_loader.h:239]: The main-thread case can just be "natural":

```suggestion
			if (Thread::get_caller_id() == Thread::get_main_id()) {
				dep_err_notify(p_path, p_dependency, p_type);
			} else {
				callable_mp_static(dep_err_notify).bind(p_path, p_dependency, p_type).call_deferred();
			}
```

**Comment by RandomShaper** [comment]
This PR makes sense, especially given how important a regresion it fixes. I'd like to bring a few points up, though:

- The load error notification and dependency error notification mechanisms would no longer have the same thread-wise semantics. Maybe this PR can just apply the same change to the othre one.
- I'd swear that I did something similar in one of my related PRs and someone raised concerns about the fact that some callbacks happening deferredly whilt some others don't would lead to problems in the order of errors in the dialog. However, I'm not able to find that discussion and this rationale I remember doesn't seem to be right. Just for the records.
- Since this is not exposed (it's editor-only), we can afford to apply this patch and down the road aim for a more robust design. The current idea is that those `ResourceLoader` static functions are the ones in charge of dealing with cross-thread boundaries to the editor API is still main-thread aware only. That part of the machinery may be still good. However, a different mechanism could be added in the future for the notification part (e.g., collect the errors in a callback with a mutex so they are ready by the end of the load regardless which thread issued them).

**Comment by SaracenOne** [comment]
I agree with your assessments here. I do get the feeling that a lot of the editor code feels like a legacy system awkwardly wrapping itself around more modern subsystems, a pretty common scenario. A broader overhaul which could make use of callback mechanisms would certainly make would certainly make a lot of sense.

**Review by RandomShaper — APPROVED** [review]
Let's merge (remembering the caveats). I guess this warrants cherry-picking into 4.1, but I'm not sure.

**Comment by SaracenOne** [comment]
It might be worth it. My reason for investigating this was a friend mentioning how Godot can easily corrupt your scenes when resources are moved around, and I think any issue related to data corruption is important

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Note: If we cherry-pick this, we should likely include #83024 with it.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
