### PR TITLE
Fix: export var type reduce() implemented

### LINKED ISSUE #36899: Dictionary of References export breaks compilation
**Godot version:**
Godot 3.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
An export of a dictionary of References (or Resources) breaks compilation and the scene itself: it can't be opened again. This happens when both 1) and 2) are true: 1) the dictionary is modified in any way that makes it different from the initialization specified for it in the script 2) the dictionary holds more than 1 key-value pair.

**Steps to reproduce:**
- Create a node
- Add script to it
- Script content: `export var dictionary = {
	0: Reference,
	1: Reference
}`
- From the inspector, replace one of the values of the dictionary with any resource.
- Play scene (crash at compilation, no log)
- Also, save scene, close it and try to re-open: "Error while parsing 'scene_name.tscn'."

**Minimal reproduction project:**
[dictionary test.zip](https://github.com/godotengine/godot/files/4303022/dictionary.test.zip)

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #36899

when exporting a var the parser checks if the type is supported and for array and dictionary, they are supported but if they contain any variant which doesn't supported -> BUG!!
setting an unsupported type value and saving the scene will also write invalid text to `*.tscn` file which will leads to an error `Error while parsing *.tscn`
```gdscript
## *.tscn file
dictionary = {
0: SubResource( 1 ), ## some value assigned from inspector
1: Object(GDScriptNativeClass,"script":null) ## no value assigned -> writing invalid text
}
```

fix: validate type recursively (for array and dictionary) to ensure that all types inside are supported.

export var type reduce

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -2022,6 +2022,38 @@ GDScriptParser::Node *GDScriptParser::_parse_and_reduce_expression(Node *p_paren
...
+		for (int i = 0; i < dict.size(); i++) {
+			Variant value = dict.get_value_at_index(i);
+			if (!_reduce_export_var_type(value, p_line)) return false;
+		}
+	}
+
+	// validate type
+	DataType type = _type_from_variant(p_value);
+	if (type.kind == DataType::BUILTIN || type.kind == DataType::NATIVE) {
+		if (!ClassDB::is_parent_class(type.native_type, "Resource")) {
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:2045]: If `type.kind == DataType::BUILTIN` then it won't have a `native_type`, so this will fail.

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (ThakeeNathees) [reply modules/gdscript/gdscript_parser.cpp]: @vnen I've changed that 👍

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
