### PR TITLE
Fix `heap-use-after-free` error in `TileMap::~TileMap()`

### LINKED ISSUE #69918: Crash due to heap corruption after `change_scene_to_file`
### Godot version

v4.0.beta8

### System information

Linux, Vulkan as well as OpenGL

### Issue description

Intermittently the engine crashes during `change_scene_to_file` from GDscript. A litany of different error messages appears before aborting, relating this to heap corruption:

- `malloc(): mismatching next->prev_size (unsorted)`
- `corrupted size vs. prev_size`
- `corrupted double-linked list (not small)`

It seems to be triggered by having a `TileMap` with assigned `TileSet` in the origin scene. It also seems to help to have an empty `_process`. But I'm not sure.

### Steps to reproduce

- Load the minimal reproduction project.
- Start it. It will switch scenes every half-second and (here at least) reliably crash in less than a minute.

### Minimal reproduction project

In the attached project I've reduced my game to the important essentials: bouncing between the interlude and gameplay (two nearly empty scenes) every half a second. It does nothing otherwise. You can exit with `esc` at any time if it happens to not crash for you.
[repro4.tar.gz](https://github.com/godotengine/godot/files/10202797/repro4.tar.gz)

### PR DESCRIPTION
**Pull request by adamscott**
Makes sure that `TileMap::tile_set` is disposed first when `TileMap::~TileMap()` is called, otherwise [it can lead to a `heap-use-after-free` error.
](https://github.com/godotengine/godot/issues/69918#issuecomment-1345620226)
Fixes #69918 - Crash due to heap corruption after `change_scene_to_file`

### CODE REVIEW

**Comment by adamscott** [comment]
Tested the MRP of #69918 with this PR with ASAN, and this effectively fixes the `heap-use-after-free` error.

**Comment by vmedea** [comment]
Thank you! I built from source and can confirm this solves the crash issue (both in the repro project as in my actual game).

**Comment by adamscott** [comment]
@groud This seems more legit than my solution. It passed the ASAN test, you got it.

I added you as a co-author, seems the logical thing to do. :smile:

**Comment by akien-mga** [comment]
Seems like you didn't commit the changes :)

**Comment by adamscott** [comment]
> Seems like you didn't commit the changes :)

Oopsie. :sweat_smile:

File: scene/2d/tile_map.cpp [hunk 1]
```diff
@@ -4072,5 +4072,9 @@ TileMap::TileMap() {
 }
 
 TileMap::~TileMap() {
+	if (tile_set.is_valid()) {
+		tile_set->disconnect("changed", callable_mp(this, &TileMap::_tile_set_changed));
+	}
+
```
Comment (adamscott) [inline scene/2d/tile_map.cpp:4078]: I changed it!

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
