### PR TITLE
Fix resource loader not resolving shallow loaded scripts through dependencies (reverted)

### LINKED ISSUE #95909: Validation error using Resource sub-classes and sub-resources with specific combination of preload/@onready/instantiation
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]
- Reproducible behavior, with different error messages, in: v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

With a _very_ specific set of Resource subclasses and sub-resources, use of preload, use of `@onready`, and instantiation in script, the following error occurs:

```
E 0:00:00:0708   validate_object: Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
  <C++ Error>    Condition "!other_script->inherits_script(script)" is true. Returning: false
  <C++ Source>   core/variant/container_type_validate.h:140 @ validate_object()
```
```
E 0:00:00:0708   assign: Unable to convert array index 0 from "Object" to "Object".
  <C++ Error>    Method/function failed.
  <C++ Source>   core/variant/array.cpp:238 @ assign()
```

This occurs when attempting to run the project. The data in the sub-resource will not be loaded, and will be removed from disk when saved. Additionally, validation performed by the editor when loading the project will similarly remove the 'offending' data and give a similar error.

However, it seems that if you _don't_ have a call to instantiate the sub-resource in code (or preload, or `@onready` in this specific way), then this configuration of resources/subresources is fine to load, use, and save. This may suggest that the class structure is supported but there is some issue arising in the validation process.

### Error and automatic deletion of sub-resource at startup
When you open the included minimal reproduction project, you will see the following error in the output window:

```  
Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
Unable to convert array index 0 from "Object" to "Object". 
```

At this point, the included resource `.tres` file will be automatically modified to remove the problematic data. You should see its contents go from something like this:

```
[gd_resource type="Resource" script_class="MyResourceContainer" load_steps=5 format=3 uid="uid://6qhpq8xclwhy"]

[ext_resource type="Script" path="res://my_resource_a.gd" id="1_huj0e"]
[ext_resource type="Script" path="res://my_resource_container.gd" id="2_88hls"]
[ext_resource type="Script" path="res://my_resource_b.gd" id="2_tfgcd"]

[sub_resource type="Resource" id="Resource_aiw63"]
script = ExtResource("2_tfgcd")

[resource]
script = ExtResource("2_88hls")
data = Array[ExtResource("1_huj0e")]([SubResource("Resource_aiw63")])
```

to this (where the sub_resource has been removed)

```
[gd_resource type="Resource" script_class="MyResourceContainer" load_steps=3 format=3 uid="uid://6qhpq8xclwhy"]

[ext_resource type="Script" path="res://my_resource_a.gd" id="1_huj0e"]
[ext_resource type="Script" path="res://my_resource_container.gd" id="2_88hls"]

[resource]
script = ExtResource("2_88hls")
data = Array[ExtResource("1_huj0e")]([])
```

### Automatic deletion at runtime if you attempt to add it back
At this point, you _could_ run the project without errors, but that's because the sub-resource has been automatically removed. If you add it back in:
1. Select `test_resource.tres`
2. In the inspector, click `Add Element` for MyResourceContainer -> Data
3. Set the new element to `New MyResourceB`

Now when you run the project, you will see the two errors:
```
validate_object: Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
assign: Unable to convert array index 0 from "Object" to "Object".
```

Additionally, the data will not be available if you load the resource. It will also be removed from disk if you save the project.

### Interactions with preload, `@onready`, and more
This is a _very_ specific set of scripts! If you remove the `@onready` references, the type hints, the function call to instantiate `MyResourceB.new()`, or the preload call, the issue appears to go away.

I have tried to simplify the project further but this eliminates the issue. For example, simply having "a resource class that contains a sub-resource of a type that itself is a subclass of Resource" is not enough to trigger this error.

### Godot 4.2.2:
In v4.2.2.stable.mono.official [15073afe3], the startup error is a little different:
```
 Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
  unsupported format character
  core/variant/array.cpp:222 - Method/function failed.
```

The result is the same however, as the sub-resource data is removed from the `.tres` file.

And at runtime (if you replace the automatically removed sub-resource as described above):
```
E 0:00:00:0691   validate_object: Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
  <C++ Error>    Condition "!other_script->inherits_script(script)" is true. Returning: false
  <C++ Source>   core/variant/container_type_validate.h:140 @ validate_object()
```
```
E 0:00:00:0691   vformat: unsupported format character
  <C++ Error>    Condition "error" is true. Returning: String()
  <C++ Source>   ./core/variant/variant.h:835 @ vformat()
```
```
E 0:00:00:0691   assign: Method/function failed.
  <C++ Source>   core/variant/array.cpp:222 @ assign()
```

### Minimal reproduction project (MRP)

[resource-bug.zip](https://github.com/user-attachments/files/16695302/resource-bug.zip)

### PR DESCRIPTION
**Pull request by beev1s**
When a script first gets shallow loaded through a dependency and and then requested by the resource loader, that script is already registered in `ResourceCache` and will therefore not be properly reloaded, which is necessary in order to resolve any Script inheritance. This can lead to errors when assigning objects with that script to a reference of its parent.

`GDScript` now overwrites `set_path_cache` which does not register it in the `RessourceCache`. `set_path_cache` replaces a call to `set_path` in `get_shallow_script`. `get_full_script` now calls `set_path` to register the script.

- Fixes https://github.com/godotengine/godot/issues/95909

### CODE REVIEW

File: core/io/resource.h [hunk 1]
```diff
@@ -125,6 +125,8 @@ class Resource : public RefCounted {
 
 	Node *get_local_scene() const;
 
+	virtual bool is_fully_loaded() const { return true; }
```
Comment (dalexeev) [inline core/io/resource.h:128]: Not sure about this approach, in my opinion it has confusing semantics which could potentially lead to introducing bugs. CC @RandomShaper

Note that we would like to do a major refactoring of `GDScriptCache`. Maybe we can simplify it, given that `ResourceLoader` now supports "shallow" references.

Comment (beev1s) [reply core/io/resource.h:128]: Could you elaborate on this a bit more? Are there other resources that can be "shallow" loaded?
Would you like for me to rename the function to something more contextual?

Otherwise, as far as I understand the `ResourceLoader` is resource agnostic and has to decide whether it wants to use a cached resource or load it from scratch. So the only 2 points where a possible fix can be made are: 1. When the `ResourceLoader` decides to use or not use a cached resource or 2. When it is critically important for a resource to be fully loaded. Through 2. would mean that this has to be decided for a bunch of different points in the engine one by one.

Comment (RandomShaper) [reply core/io/resource.h:128]: I'm with @dalexeev. If the GDScript cache is going to be overhauled, it's better to think how the new implementation can accommodate the need. That may collaborate with the shallow resource support in `ResourceLoader` or maybe allow to make it a `ResourceCache` feature somehow. And that also goes for `GDScriptCache`: it may also be subsumed in `ResourceCache` in the new approach.

However, we'd stil benefit form a short term solution. I was wondering, if the various calls to `Resource::set_path()` in the GDScript module could be the basis of the solution. The idea would involve using `set_path_cache()` instead in some cases (full logic to be determined by the contributor). That one won't register the resource in the `ResourceCache` and so the `ResourceLoader` won't consider it for returning that one. At some later point, when the script is known to be fully loaded, `set_cache()` would be used.

Comment (beev1s) [reply core/io/resource.h]: I updated the commit. Could you look over it again?

Comment (RandomShaper) [reply core/io/resource.h]: It looks reasonable now, but I can't trust I understand all the implications to GDScript. I'd still like @dalexeev to take another look.

**Review by dalexeev — APPROVED** [review]
Looks reasonable to me. I tested it, this PR fixes the linked issue.

@beev1s Note that GitHub will **not** count this as your contribution. See [GitHub Docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile) for details.

**Review by RandomShaper — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks, and congratulations on your first contribution! 🎉

**Comment by akien-mga** [comment]
Reverting with #102429 as this introduced complex regressions which are worse than the bug this was addressing.
