### PR TITLE
Triple click in text editor now uses last mouse position for validity

### LINKED ISSUE #51312: Triple click doesn't take mouse position into account
### Godot version

3.3.3.rc1

### System information

Windows 10

### Issue description

When double clicking to select a word, the mouse position is taken into account correctly, but when doing a third click elsewhere, the line is suddenly selected. The following gif demonstrates the problem:

tripleclick

### Steps to reproduce

1. Double click a word.
2. Quickly, single-click another word.
3. The entire line is now selected.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by codecat**
Previously, you would be able to double click a word, followed by single-clicking another word on the same line, which would select the entire line. Now, it will only select the whole line if the mouse position has remained the same after the double click. This mimics the behavior in most third party text editors.

This fixes #51312.

### CODE REVIEW

**Comment by akien-mga** [comment]
Shouldn't there be a tolerance of a few pixels for unintentional mouse movement?

I checked on Firefox/GTK3 on Linux and it triple select seems to work if I'm moving very slightly while still triple clicking fast.

**Comment by codecat** [comment]
You're correct, I've never noticed this!

**Review by KoBeWi — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks good! Could you squash the commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -2246,7 +2246,7 @@ void TextEdit::_gui_input(const Ref<InputEvent> &p_gui_input) {
 					selection.selecting_column = col;
 				}
 
-				if (!mb->is_double_click() && (OS::get_singleton()->get_ticks_msec() - last_dblclk) < 600 && cursor.line == prev_line) {
+				if (!mb->is_double_click() && (OS::get_singleton()->get_ticks_msec() - last_dblclk) < 600 && mb->get_position().distance_to(last_dblclk_pos) < 5) {
```
Comment (Calinou) [inline scene/gui/text_edit.cpp:2249]: I would probably move the tolerance into some kind of constant (local `const int` is fine for this). This would avoid using a "magic number" of sorts.

Comment (KoBeWi) [reply scene/gui/text_edit.cpp:2249]: 600 is a magic number too.

Comment (codecat) [reply scene/gui/text_edit.cpp:2249]: I actually had it as a constant like this:
```c++
const int triple_click_tolerance = 5;
```
But I changed it because there's other constants like that too. Should I make constants for both the numbers then? eg:
```c++
const int triple_click_timeout = 600;
const int triple_click_tolerance = 5;
```

Comment (Calinou) [reply scene/gui/text_edit.cpp:2249]: > Should I make constants for both the numbers then?

Sure :slightly_smiling_face:

**Review by Ansraer — APPROVED** [review]
Damn it, you beat me to it by a day...
I am just gonna blame my slow internet and the good weather.

**Comment by codecat** [comment]
Is the Linux CI failure something I should concern myself with?

**Comment by Calinou** [comment]
> Is the Linux CI failure something I should concern myself with?

The log says:

```
Run echo "Running --doctool to see if this changes the public API without updating the documentation."
Running --doctool to see if this changes the public API without updating the documentation.
If a diff is shown, it means that your code/doc changes are incomplete and you should update the class reference with --doctool.


diff --git a/doc/classes/@GlobalScope.xml b/doc/classes/@GlobalScope.xml
index 3dfb0f4..7c954df 100644
--- a/doc/classes/@GlobalScope.xml
+++ b/doc/classes/@GlobalScope.xml
@@ -213,10 +213,8 @@
 			</description>
 		</method>
 		<method name="error_string">
-			<return type="String">
-			</return>
-			<argument index="0" name="error" type="int">
-			</argument>
+			<return type="String" />
+			<argument index="0" name="error" type="int" />
 			<description>
 				Returns a human-readable name for the given error code.
 			</description>
Error: Process completed with exit code 1.
```

You need to [update the class reference](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) to resolve this.

**Comment by akien-mga** [comment]
Thanks!
