### PR TITLE
[Web] Gracefully handle non-finite audio volumes

### LINKED ISSUE #94806: Uncaught TypeError: AudioParam.value setter error in Web build.
### Tested versions

Error occurs in v4.3.beta3.official [82cedc83c]
Error did not occur in 4.3.beta2

### System information

Godot v4.3.beta3 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3623) - 12th Gen Intel(R) Core(TM) i9-12900KF (24 Threads)

### Issue description

When playing the game on a web browser (such as itch.io), sometimes playing different audio causes this error. I don't really have a reliable way to reproduce this and I know this is super vague, but I wanted to bring it up regardless as this did not happen in 4.3beta2, but does happen in 4.3beta3.

The error in full is as thus:

Blocking on the main thread is very dangerous, see <url>
Uncaught TypeError: AudioParam.value setter: Value being assigned is not a finite floating-point value.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
These values aren't valid but they should be handled gracefully, ~could handle with a `isFinite()` instead (though that would involve checking after converting, so bit more complex code), with or without a message, but I think this is the most straight forward way to handle it~

This shouldn't happen with properly handled input, but in case of user error entering invalid values we should handle this gracefully instead of failing to load

* Closes: https://github.com/godotengine/godot/issues/94806

### CODE REVIEW

**Review by adamscott — COMMENTED** [review]
I think we can handle this case more gracefully than a try/catch. I'll try something in the following hour.

**Comment by AThousandShips** [comment]
I'll switch to a `isFinite` instead as an alternative, will push momentarily

**Comment by AThousandShips** [comment]
Now just ignores the value if non-finite after converting

File: platform/web/js/libs/library_godot_audio.js [hunk 1]
```diff
@@ -858,7 +858,10 @@ class Bus {
 	 * @returns {void}
 	 */
 	setVolumeDb(val) {
-		this._gainNode.gain.value = GodotAudio.db_to_linear(val);
+		const linear = GodotAudio.db_to_linear(val);
+		if (isFinite(linear)) {
+			this._gainNode.gain.value = linear;
+		}
```
Comment (AThousandShips) [inline platform/web/js/libs/library_godot_audio.js:864]:
```suggestion
		} else {
			this._gainNode.gain.value = 0;
		}
```
If we want uniformity between platforms, probably unnecessary though but would silence when fed invalid input as is the case otherwise

Comment (adamscott) [reply platform/web/js/libs/library_godot_audio.js:864]: I would rather test directly with `isNaN()` rather than `isFinite()`, because `-Infinity` is a valid dB value.

Comment (AThousandShips) [reply platform/web/js/libs/library_godot_audio.js:864]: But this isn't a dB value, it's a linear value

Comment (adamscott) [reply platform/web/js/libs/library_godot_audio.js:864]: I don't understand your edit, as I tested locally and `db_to_linear(Infinity)` returns `Infinity`.

What I suggest is that we return early if `isNaN(val)` returns `true`.

Comment (AThousandShips) [reply platform/web/js/libs/library_godot_audio.js:864]: Yes but please check the issue, it will error out, the issue is that you can't assign a non-finite value, your suggested fix isn't valid

This is a potential mini suggestion but isn't really relevant, the issue is that we can't assign a non-finite value to the gain

**Comment by AThousandShips** [comment]
To confirm this just try running:
```gdscript
AudioServer.set_bus_volume_db(0, +INF)
AudioServer.set_bus_volume_db(0, NAN)
```

This will error out and fail to run

**Comment by AThousandShips** [comment]
Here's an MRP to test with, won't always freeze but if you check the log it will throw the uncaught exception:
[WebMRP.zip](https://github.com/user-attachments/files/16417418/WebMRP.zip)

**Comment by adamscott** [comment]
> Here's an MRP to test with, check the script for instructions: [WebMRP.zip](https://github.com/user-attachments/files/16417437/WebMRP.zip)

@AThousandShips Are you sure you joined the right MRP? There's no script at all.

**Comment by AThousandShips** [comment]
It's built-in

**Review by adamscott — APPROVED** [review]
Great work @AThousandShips. I didn't know that it was the WebAudio gain node that was complaining about `Infinity`.

So, everything's good, I'll add a warning later, that I must implement in the JS stack.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!
