### PR TITLE
[Image Font Importer] Adds support for `\uXXXX` in the kerning config strings.

### LINKED ISSUE #93066: Kerning Pairs property for Monospace Image Font Data does not support spaces
### Tested versions

- Reproducible in: Godot v4.3.beta1.official [a4f2ea91a]

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5176) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When creating monospace image fonts, the new `kerning_pairs` property allows character combo kerning settings to be applied, which is awesome. From the tooltip, though, these settings are made using two strings and an integer with [space] as the delimiter. 

This seems to preclude the use of kerning settings for the [space] character itself, which causes problems with text layout (large gaps in my case). 

The current "latest" docs do not seem to have information, so it's very possible I am missing something in the intended usage.

As an aside, a way to define a wildcard so that a character has the same kerning for all subsequent characters would be handy.

image

Image of the settings window for quick reference.

### Steps to reproduce

1) Import a text PNG as monospace font data as seen with example here: https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html#doc-gui-using-fonts
2) Add a label node to a scene and set the font data in its LabelSettings.
3) Add text and try to modify the kerning of the [space] character in the scene.

### Minimal reproduction project (MRP)

[kerning_issue.zip](https://github.com/user-attachments/files/15796602/kerning_issue.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Partially fixes https://github.com/godotengine/godot/issues/93066

Spaces can be now added to kerning pairs with `\u0020`, not the most elegant solution, but not much can be changed without breaking existing imports.

I'll probably make a separate PR adding the advanced import dialog for bitmap fonts, since entering it via standard property editor is not convenient.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: editor/import/resource_importer_imagefont.cpp [hunk 1]
```diff
@@ -291,10 +291,29 @@ Error ResourceImporterImageFont::import(const String &p_source_file, const Strin
 			WARN_PRINT(vformat("Invalid kerning pairs string: \"%s\"", kp));
 			continue;
 		}
+		String from_tokens;
+		for (int i = 0; i < kp_tokens[0].length(); i++) {
+			if (i <= kp_tokens[0].length() - 6 && kp_tokens[0][i] == '\\' && kp_tokens[0][i + 1] == 'u') {
+				char32_t charcode = kp_tokens[0].substr(i + 2, 4).hex_to_int();
+				from_tokens += charcode;
```
Comment (DarkMarmot) [inline editor/import/resource_importer_imagefont.cpp:298]: @bruvzg This bit of code is missing a part to advance past the hex characters and thus includes `u` and whatever 4 hex characters are included after it. I think it just needs `i += 5` here and in the next loop set to fix it. Do I need a demo project for it?
