### PR TITLE
Make `RID_Owner<Texture>` threadsafe in `TextureStorage` for GLES3

### LINKED ISSUE #88195: `RID_Alloc::get_or_null` randomly fails leading to crashes down the line in `RID_Alloc::owns`
### Tested versions

v4.2.1.stable

### System information

Windows 10, Godot 4.2.1, Gles3 compatibility

### Issue description

It seems that `RID_Alloc::get_or_null` randomly fails sometimes (if a lot of RIDs are allocated?). So far I can only get this to trigger once every 100 or so map loads which makes it hard to debug. Especially since all of this is marked as force inline which means my breakpoints don't trigger. So far I had it fail with "Attempting to initialize the wrong RID" and "Attempting to use an uninitialized RID".

This then later leads to a crash in `RID_Alloc::owns`  with an access violation in this line:
```
bool owned = (validator != 0x7FFFFFFF) && (validator_chunks[idx_chunk][idx_element] & 0x7FFFFFFF) == validator;
```
with trying to access address 0xFFFFFFFFFFFFFFFF. So far I was able to extract the following values:
```
id 0x000043f500000368
elements_in_chunk 0x0000012f
idx_chunk 2
idx_element 0x10A
validator 0x43f5
```

My assumption so far is that there is an off by one error in `_allocate_rid` somewhere but I wasn't able to determine that yet. The only other similarity between all crashes I could find is that it was always related to a texture. My game is not really using that many textures though so no idea why that would cause issues.

### Steps to reproduce

Didn't find a consistent way to reproduce this yet

### Minimal reproduction project (MRP)

-

### PR DESCRIPTION
**Pull request by 0x0ACB**
This seems to fix https://github.com/godotengine/godot/issues/88195. In the Vulkan driver the `RID_Owner<Texture>` is already thread safe and indeed, textures might be created from threads. Also the `RID_Owner<CanvasTexture>` for gles3 is thread safe as well. I think this was just forgotten to add for the `Texture` one in a refactor.

### CODE REVIEW

File: drivers/gles3/storage/texture_storage.h [hunk 1]
```diff
@@ -404,8 +404,8 @@ class TextureStorage : public RendererTextureStorage {
 	RID_Owner<CanvasTexture, true> canvas_texture_owner;
 
 	/* Texture API */
-
-	mutable RID_Owner<Texture> texture_owner;
+	//textures can be created from threads, so this RID_Owner is thread safe
```
Comment (akien-mga) [inline drivers/gles3/storage/texture_storage.h:407]:
```suggestion
	// Textures can be created from threads, so this RID_Owner is thread safe.
```

Comment (0x0ACB) [reply drivers/gles3/storage/texture_storage.h:407]: should I change this in the vulkan driver as well then? I just copied this from there ^^

**Comment by RandomShaper** [comment]
I'm not sure you can create textures from threads in the OpenGL ES backend. Also, there's some ongoing work (#77004) that may need to be aware of this change to potentially revert it if it turns out in the end to be possible to funnel all the renderer calls via a unique thread in the case of GL.

**Comment by 0x0ACB** [comment]
It is (currently) possible to create textures from threads, atleast that is what I found while debugging my issue.

**Comment by RandomShaper** [comment]
Oh, right. Allocating a `RID` would need sync indeed.

PS: I'm wondering if `RID_Owner` could be enhanced with a locking pattern that makes that more optimal, given most of the time it will be read-written from the renderer thread. I'll add this to my TODO list.

**Comment by AThousandShips** [comment]
Like:
* https://github.com/godotengine/godot/pull/86333

Perhaps?

**Review by RandomShaper — APPROVED** [review]
I think this makes sense, but I don't have time to repro and debug, and I'm not very familiar with the GL implementation. I'm approving, but TIWAGOS.

**Comment by RandomShaper** [comment]
> Like:
> 
> * [Make `RID_Owner` lock-free for fetching. #86333](https://github.com/godotengine/godot/pull/86333)
> 
> Perhaps?

Not quite... The requirements here would be: 1) any thread can allocate uninitialized RIDs, 2) only the "owner" thread can do everything else. So, both usages involve writing, but with different constraints.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by Nicholas3413** [comment]
Please also cherry pick this for Godot 4.1.5 next. thankyou!
