### PR TITLE
Mention display driver and window mode in Copy System Info text

### LINKED ISSUE #10787: Clarify in "Copy System Info" whether the Godot client is running the X11 or Wayland DisplayServer
### Describe the project you are working on

Godot itself

### Describe the problem or limitation you are having in your project

Bug reports from Linux users which relate to windowing issues are pretty difficult to diagnose initially, because we need to know whether the user is running the X11 or Wayland version of the editor. See e.g. https://github.com/godotengine/godot/issues/97211#issuecomment-2363479718

The current line looks like this on my system:
```
Godot v4.4.dev (0a4aedb36) - Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)
```

So it says "Wayland", but I'm actually using the X11 version of the editor, on a Wayland session of KDE Plasma (i.e. through XWayland).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would tweak the report to make things more explicit, e.g. from:

> Godot v4.4.dev (0a4aedb36) - Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

to (changes in **bold**):

> Godot v4.4.dev (0a4aedb36) - Fedora Linux 40 (KDE Plasma **on Wayland**) - **X11 client (multi-window)** - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

I suggest adding "(single-window)" and "(multi-window)" too as it's often important information for GUI/input related issues.

CC @Riteo @Calinou

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Could be, but it would defeat the purpose of having better bug reports from the get go, and I think the current "Wayland" / "X11" mention of the OS session type is misleading at best.

### Is there a reason why this should be core and not an add-on in the asset library?

n/a, editor improvement for issue triage purposes

### PR DESCRIPTION
**Pull request by Calinou**
This is useful information to know, as the X11 display driver can be used both on X11 natively and on Wayland through XWayland.

Certain editor issues only occur in multi-window mode (or only in single-window mode). Some issues also only occur on multi-monitor setups, so the monitor count is now listed.

**Not tested on a Wayland session yet.**

- This closes https://github.com/godotengine/godot-proposals/issues/10787.

### Before

```
Godot v4.4.dev (39f8e69f1) - Fedora Linux 40 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 560.35.03) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)
```

### After

```
Godot v4.4.dev (39f8e69f1) - Fedora Linux 40 (KDE Plasma) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 560.35.03) - 13th Gen Intel(R) Core(TM) i9-13900K (32 threads)
```

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -5018,16 +5020,33 @@ String EditorNode::_get_system_info() const {
...
-#ifdef LINUXBSD_ENABLED
 	if (!display_server.is_empty()) {
-		info.push_back(display_server);
+		distribution_display_server += " on " + display_server;
 	}
+	info.push_back(distribution_display_server);
+
+	String display_driver_window_mode;
+#ifdef LINUXBSD_ENABLED
+	// `replace` is necessary, because `capitalize` introduces a whitespace between "x" and "11".;
```
Comment (AThousandShips) [inline editor/editor_node.cpp:5034]:
```suggestion
	// `replace` is necessary, because `capitalize` introduces a whitespace between "x" and "11".
```

**Review by adamscott — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -4956,8 +4956,10 @@ String EditorNode::_get_system_info() const {
 		godot_version += " " + hash;
 	}
 
+	String display_server;
 #ifdef LINUXBSD_ENABLED
-	const String display_server = OS::get_singleton()->get_environment("XDG_SESSION_TYPE").capitalize().replace(" ", ""); // `replace` is necessary, because `capitalize` introduces a whitespace between "x" and "11".
+	// `replace` is necessary, because `capitalize` introduces a whitespace between "x" and "11".
+	display_server = OS::get_singleton()->get_environment("XDG_SESSION_TYPE").capitalize().replace(" ", "");
```
Comment (akien-mga) [inline editor/editor_node.cpp:4962]: I would avoid the name `display_server` for this and `distribution_display_server` to avoid furthering the ambiguity between the OS display server protocol and Godot's DisplayServer implementation.

Maybe `display_session_type`?

**Review by akien-mga — APPROVED** [review]
Works well on Fedora 40 KDE Wayland:

```
Godot v4.4.dev (9e2df27ed) - Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)
```

**Comment by akien-mga** [comment]
Thanks!
