### PR TITLE
[3.x] Fix custom build export

### LINKED ISSUE #50926: Android export fails on custom build because of undefined boolean parameter in can_export()
### Godot version

3.x

### System information

Windows 10

### Issue description

Because of an undefined boolean the android export fails, a fix is to set the r_missing_templates to false here:

in platform/android/export/export.cpp

```
@@ -2127,10 +2127,12 @@ public:
 		} else {
 			bool installed_android_build_template = FileAccess::exists("res://android/build/build.gradle");
 			if (!installed_android_build_template) {
 				r_missing_templates = !exists_export_template("android_source.zip", &err);
 				err += TTR("Android build template not installed in the project. Install it from the Project menu.") + "\n";
+			} else {
+				r_missing_templates = false;
 			}
 
 			valid = installed_android_build_template && !r_missing_templates;
 		}
```

### Steps to reproduce

Use custom android build, on release_debug builds.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by m4gr3d**
Fix #50926

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/android/export/export.cpp [hunk 1]
```diff
@@ -2129,6 +2129,8 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 			if (!installed_android_build_template) {
 				r_missing_templates = !exists_export_template("android_source.zip", &err);
 				err += TTR("Android build template not installed in the project. Install it from the Project menu.") + "\n";
+			} else {
+			  r_missing_templates = false;
```
Comment (akien-mga) [inline platform/android/export/export.cpp:2133]: Indentation bug (spaces).

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.
