### PR TITLE
Handle RID validator overflow

### LINKED ISSUE #74728: Servers may rarely return an invalid RID
### Godot version

4.0.stable

### System information

Linux 5.10.167-1-MANJARO

### Issue description

After roughly 2-billion calls to `rid_allocate_id()`, if you then make a call to a server that creates and returns a new RID, and no other calls have been made to that function. The server will then return an invalid RID.

Attempting to free this RID will make godot crash without errors, unlike what normally happens when you try to free an invalid RID.

This happens because the function that generates the RID only uses the lower 31 bits of the generated id from `rid_allocate_id`. In combination with an index into the array of elements of that `RID_Owner`. So if you generate `2^31` total ids, it will overflow (without any actual integer overflow happening, as the id is 64 bits long) and become 0. then if the array is empty, the index is 0 as well, so it will generate an rid = 0.

### Steps to reproduce

Call `rid_allocate_id()` until the returned value is `0x7FFFFFFF`. Then make a call (such as `PhysicsServer3D.area_create()`) which will print an error in the console and return an invalid RID.

### Minimal reproduction project

Let the project run, eventually (takes a couple of minutes on my machine) the error will show up and a print message indicating that an invalid RID has been returned.
[repro.zip](https://github.com/godotengine/godot/files/10943606/repro.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
If the RID validator index reaches the maximum value of a 31 bit integer it will register as an invalid entry and break the RID, this crashes the engine on reaching that.

My reasoning is that the likelihood of reaching this in normal usage of the engine is extremely low and it's safe to just crash on the exception, as in, it shouldn't disrupt normal usage but crash on exceptional one

I can instead have it generate a new validator by calling the increment again, possibly skipping over 0 to avoid an RID of 0, but I don't think it's safe to reuse validators. If someone can confirm it is safe to do so I will change to that approach.

* Fixes: #74728

### CODE REVIEW

**Comment by AThousandShips** [comment]
Realized there was a missing check in `free`, will add

**Comment by AThousandShips** [comment]
Added a condition to the validity of RIDs as no valid RID should have an invalid validator

**Comment by AThousandShips** [comment]
Added a test for invalid RIDs given the new test

**Comment by AThousandShips** [comment]
But it makes it crash on overflow, but can word it like that if it's better

**Comment by Chaosus** [comment]
NVM, I've just misreading, but adding a crash rather than fix this or at least adding a proper error emitting sounds a bit weird.

**Comment by AThousandShips** [comment]
The description elaborates why a "fix" is difficult and I don't feel confident adding it unless someone can confirm it's safe to reuse validators

File: core/templates/rid.h [hunk 1]
```diff
@@ -58,7 +58,7 @@ class RID {
 	_ALWAYS_INLINE_ bool operator!=(const RID &p_rid) const {
 		return _id != p_rid._id;
 	}
-	_ALWAYS_INLINE_ bool is_valid() const { return _id != 0; }
+	_ALWAYS_INLINE_ bool is_valid() const { return _id != 0 && _id < 0x7FFFFFFF00000000L; }
```
[the remark this answers is not in the document]
Comment (AThousandShips) [reply core/templates/rid.h:61]: That makes sense to me

File: core/templates/rid_owner.h [hunk 2]
```diff
@@ -266,7 +271,7 @@ class RID_Alloc : public RID_AllocBase {
 		uint32_t idx_element = idx % elements_in_chunk;
 
 		uint32_t validator = uint32_t(id >> 32);
-		if (unlikely(validator_chunks[idx_chunk][idx_element] & 0x80000000)) {
+		if (unlikely(validator >= 0x7FFFFFFF || validator_chunks[idx_chunk][idx_element] & 0x80000000)) {
```
Comment (lawnjelly) [inline core/templates/rid_owner.h:274]: `>= 0x7FFFFFFF` is the same as `& 0x80000000` I think (in release it will probably check the bit rather than do a comparison, as I'm assuming this is cheaper). Not that using the former is bad, just noting this is the same thing.

File: core/templates/rid_owner.h [hunk 3]
```diff
@@ -239,7 +244,7 @@ class RID_Alloc : public RID_AllocBase {
 
 		uint32_t validator = uint32_t(id >> 32);
 
-		bool owned = (validator_chunks[idx_chunk][idx_element] & 0x7FFFFFFF) == validator;
+		bool owned = (validator < 0x7FFFFFFF) && (validator_chunks[idx_chunk][idx_element] & 0x7FFFFFFF) == validator;
```
Comment (lawnjelly) [inline core/templates/rid_owner.h:248]: By definition if the validator is `0x8000000` or more it cannot pass the second check, so the first check is effectively just for the value `0x7FFFFFFF` I think. It's debatable whether this is worth doing, as it's just adding a comparison to test for a super rare corrupted value I think.

And actually come to think of it, the `validator_chunks` should never get set to this (`0x7FFFFFF`) in the first place (due to the `CRASH_NOW`) so this check is redundant I suspect?

File: core/templates/rid_owner.h [hunk 4]
```diff
@@ -173,7 +174,12 @@ class RID_Alloc : public RID_AllocBase {
 
 		uint32_t validator = uint32_t(id >> 32);
 
-		if (unlikely(p_initialize)) {
+		if (unlikely(validator >= 0x7FFFFFFF)) {
+			if (THREAD_SAFE) {
```
Comment (lawnjelly) [inline core/templates/rid_owner.h:178]: Again, I suspect this check is redundant because if the `validator_chunks` is checked before being set, it shouldn't be `0x80000000` or above?

File: core/templates/rid_owner.h (hunk 3 above)
Comment (AThousandShips) [reply core/templates/rid_owner.h:248]: Added to catch user input, but can remove

Comment (lawnjelly) [reply core/templates/rid_owner.h:248]: But regardless of user input, if the `validator_chunks` are always correct, bad input will always be caught (as it won't equal the stored validator I think?).

**Comment by lawnjelly** [comment]
I suspect only the `CRASH_COND` is needed (and removing the superfluous `return`).

Although in the long run, I don't think it would be *that* bad just to let the validators rollover (if this bug happens in the wild).

File: core/templates/rid_owner.h (hunk 3 above)
Comment (AThousandShips) [reply core/templates/rid_owner.h:248]: Will take a deeper look soon! Thank you

File: core/templates/rid_owner.h (hunk 2 above)
Comment (lawnjelly) [reply core/templates/rid_owner.h:274]: Ah true, but I'm still not sure this is required, same thing as the other cases, it compares the `validator_chunks` with the `validator` so this should be caught in the existing code.

Comment (AThousandShips) [reply core/templates/rid_owner.h:274]: True this case checks against the full validator so will catch, thank you

**Comment by AThousandShips** [comment]
Thank you that is a good idea, will see what to update that part with, if someone greenlights reusing RIDs I'm all for it but I don't feel confident allowing it without someone else guaranteeing it's considered safe

**Comment by lawnjelly** [comment]
> if someone greenlights reusing RIDs I'm all for it but I don't feel confident allowing it without someone else guaranteeing it's considered safe

Yeah it's fine to leave for now I think. We can discuss it if we get reports of it hitting the limit in the wild. :+1:

**Comment by RandomShaper** [comment]
> I don't think it's safe to reuse validators

I'm a bit late to the party, but stepping in to confirm that's true. If you have an `RID` that has been released, maybe somewhere else, you still want to be able to query the relevant `RID_Owner` for validity. If `RID` was re-assignable, we'd run into a situation of potential dangling `RID`s.

**Comment by AThousandShips** [comment]
Removed the other checks, unsure how to go with `owns` giving false positives but if any specific checks are desired I'll add them

**Comment by AThousandShips** [comment]
There, sorry for the confusion, it now handles the edge case where the RID has a validator of `0x7FFFFFFF` and accesses an index that points to an unallocated RID, in this case `owns` will return true, and in cases when this value is trusted absolutely, like in the physics servers, it will then go on to trust that `get_or_null` will return a valid value, this specific case is the only case that it will happen for as if it is greater than that validator value it won't match the masked value and nothing bad will happen

**Comment by lawnjelly** [comment]
> There, sorry for the confusion, it now handles the edge case where the RID has a validator of `0x7FFFFFFF` and accesses an index that points to an unallocated RID, in this case `owns` will return true

Ah I think I get the case you are trying to deal with, as unallocated validator is currently set to `0xFFFFFFFF`, so it will indeed pass the second check. I have a feeling there might be some cunning way around this, but it's not too bad as is. :+1:

**Review by lawnjelly — APPROVED** [review]
This looks fine, we may be able to think of an even more sneaky way to avoid one of the checks, but this will do for now. :smile:

**Comment by AThousandShips** [comment]
This at least handles the case when interacting with the servers, as far as I can tell, which is the primary risk and the case that caused the original crash, granted that was only caused by the now not occurring error with overflow, but should protect against more general inappropriate use with servers

Haven't done deep testing for breaking it when directly interacting with `RidOwner`

**Comment by AThousandShips** [comment]
Thank you!
