### PR TITLE
Fix ownership bugs in node copy and pasting.

### LINKED ISSUE #83594: Copy/Pasting foreign node behaviour is incorrect
### Godot version

f8818f85e6c43cdf1277e8ae85eba19ca0a003b0

### System information

Windows 11

### Issue description

Currently, the behaviour of the node copy-pasting with respect to certain foreign nodes is incorrect. Given certain scene composition, you can copy paste and node and the ownership of that node will be corrupted; top-level nodes should ALWAYS be assigned as owned by the edited scene, but it is currently possible to copy-paste a foreign node and end up with another foreign node.

### Steps to reproduce

Open the example project
Copy one of the lowest level nodes called BaseNode
Paste it onto another BaseNode
The new node should appear yellow, which is incorrect.

### Minimal reproduction project

[scene_composition.zip](https://github.com/godotengine/godot/files/13035829/scene_composition.zip)

### PR DESCRIPTION
**Pull request by SaracenOne**
The implementation of this is a little bit clunky, but it seems to work. The reason to maintain an extra list of nodes is because it currently it seems there's no way to distinguish between either nodes owned by the selected nodes and nodes we actually want to reassign to the new edited scene. I tried initially setting them to *just* nullptr owners instead, but this led to it including *actual* ownerless nodes being included in the copy/paste. Maintaining an extra list seems to solve this ambiguity.

Closes https://github.com/godotengine/godot/issues/83594

While an independent enhancement, would also recommend merging this PR too which provides complimentary functionality and fixes to re-enable duplication of foreign nodes https://github.com/godotengine/godot/pull/83597

### CODE REVIEW

File: editor/scene_tree_dock.h [hunk 1]
```diff
@@ -143,6 +143,7 @@ class SceneTreeDock : public VBoxContainer {
 	EditorSelection *editor_selection = nullptr;
 
 	List<Node *> node_clipboard;
+	List<Node *> node_clipboard_edited_scene_owned;
```
Comment (KoBeWi) [inline editor/scene_tree_dock.h:146]: This should be a HashSet.

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -493,16 +493,25 @@ void SceneTreeDock::_tool_selected(int p_tool, bool p_confirm_override) {
...
+					for (Node *F : cur_owned) {
+						owned.push_back(F);
+					}
+				}
 
 				for (Node *F : owned) {
 					if (!duplimap.has(F) || F == node) {
 						continue;
 					}
 					Node *d = duplimap[F];
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:510]:
```suggestion
					if (F == node) {
						continue;
					}

					HashMap<const Node *, Node *>::Iterator G = duplimap.find(F);
					if (!G) {
						continue;
					}
					Node *d = G->value;
```
Unrelated to this PR, but this code can be improved.

**Review by KoBeWi — APPROVED** [review]
Probably makes sense.
It works and the code looks ok.

**Comment by SaracenOne** [comment]
Converted to HashSet now.

**Comment by YuriSizov** [comment]
Thanks!
