### PR TITLE
Object::script may not be a valid Ref<Script>

### LINKED ISSUE #28134: 3.1 editor crash on Play/Play Scene/Opening project
**Godot version:**

3.1.Stable.official

**OS/device including version:**

Mac Mini Late 2012
2.5ghz intel core i5
16 gb 1600 ddr3 Ram
Intel HD graphics 4000 1536mb

**Issue description:**

Hello! am a Godot newbie, I build games in Blender, Max/msp and some in Unreal.
Have a new (very simple) project I am building based on this video:
https://www.youtube.com/watch?v=dSUMCUsOeyU

I get to various stages of completion, and then the project will crash on Play or Play Scene (godot saves project, then I get crash)

From then on if I reload said project it will crash on Play or Play Scene, or whenever I select or touch the little Godot Icon in the 2d layout view. (sometimes simply on project load)

Have had to rebuild project from scratch several times (is actually helping me solidify how Godot works in my brain)

I tried the steps mentioned here, but same results
https://github.com/godotengine/godot/issues/21551

Thanks very much for any help/pointers you can provide me.
Godot is a VERY interesting project. Thank you for all your work.
jd

**Steps to reproduce:**
This happens at various stages of rebuild. see attached projects

**Minimal reproduction project:**

This project crashes out on Play/Play Scene or touching the Godot icon in 2d Layout
[Test Movement 5.zip](https://github.com/godotengine/godot/files/3091065/Test.Movement.5.zip)

This project simply crashes upon load
[Test Movement 2 2.zip](https://github.com/godotengine/godot/files/3091081/Test.Movement.2.2.zip)

### PR DESCRIPTION
**Pull request by hpvb**
It appears that Object::script may be a valid ScriptInstance but not be
castable to Ref<Script>. There were only 5 places in the code that made
this assumption. This commit fixes that.

This fixes #28134

### CODE REVIEW

File: core/object.cpp [hunk 1]
```diff
@@ -1366,7 +1366,10 @@ Array Object::_get_incoming_connections() const {
 void Object::get_signal_list(List<MethodInfo> *p_signals) const {
 
 	if (!script.is_null()) {
-		Ref<Script>(script)->get_script_signal_list(p_signals);
+		Ref<Script> scr = script;
+		if (scr.is_valid()) {
+			Ref<Script>(script)->get_script_signal_list(p_signals);
```
Comment (akien-mga) [inline core/object.cpp]: I think you could dereference `scr` here directly?

Comment (hpvb) [reply core/object.cpp]: Yes I could! I'll update the PR.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
