### PR TITLE
Usability improvements to the Zoom Widget

### LINKED ISSUE #69093: CanvasEditor's zoom widget has janky click areas
### Godot version

4.0.beta6

### System information

Ubuntu 22

### Issue description

Clipboard - November 22, 2022 6_07 PM

This cursor position here should get the Zoom Minus' focus, not the Zoom Reset's.

The bug is caused by the HBoxContainer using a negative amount of separation. So Zoom Plus overlaps a bit of Zoom Reset, and Zoom Reset overlaps a little bit of Zoom Minus.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by MewPurPur**
Fix #69093

While at it, I also added two decimal digits for numbers under 10%. Reasons:
- The numbers are small enough that the extra digit doesn't clutter much
- It helps recognize key zoom levels like 6.25%
- At the smallest zoom levels, sometimes adjusting an increment had no visual indication (for example one increment might bring you from 1.24% to 1.17%, which rounds to 1.2% either way)

And I tweaked the numbers' outline width to look nicer.

image

### CODE REVIEW

**Review by Calinou — APPROVED** [review]

File: editor/editor_zoom_widget.cpp [hunk 1]
```diff
@@ -201,5 +205,5 @@ EditorZoomWidget::EditorZoomWidget() {
 
 	_update_zoom_label();
 
-	add_theme_constant_override("separation", Math::round(-8 * EDSCALE));
+	add_theme_constant_override("separation", -1);
```
Comment (Calinou) [inline editor/editor_zoom_widget.cpp:208]: Shouldn't this be scaled with `EDSCALE` too?

Comment (MewPurPur) [reply editor/editor_zoom_widget.cpp:208]: Nah. It actually should be 0, but that didn't work for some reason when I tried it at first. I'll test it again.

Comment (MewPurPur) [reply editor/editor_zoom_widget.cpp:208]: Changed to 0.

**Comment by akien-mga** [comment]
Thanks!
