### PR TITLE
Limit scale of `Node2D` to EPSILON (0.00001) to prevent `det==0` error

### LINKED ISSUE #25986: Light2D scale - scalar multiplication tending to zero || det == 0
**Godot Version:**
- 3.1 Beta 5

**OS/device including version:**
- Windows 10
- RTX 2080
- I7 8700

**Issue description:**
With the switch from Beta 4 to Beta 5 the following error occured (100+ same errors per second).
_"E 0:00:23:0627 Condition ' det == 0 ' is true. <C Source> core/math/transform_2d.cpp:51 @ affine_invert()"_

**Steps to reproduce:**
Modify the Light2D scale within the physics_process with 0.x multiplication.
I assume this is also valid for process, but haven't tested it.

_**Hint:** tried a few other node types, it seems that only Light2D is causing errors with the above mentioned multiplication_

**Minimal reproduction project:**
- Create new project
- add Node2D as root (main scene)
- add Light2D (just add Godot Icon as texture)
- add script to Light2D 
`func _physics_process(var delta : float):
	scale *= 0.5`

### PR DESCRIPTION
**Pull request by JestemStefan**
Fix for issue #25986 for `master` since it was still reproducible.

It seems that due to floating point errors value of `scale` reach almost `0`, but not exactly `0` and this "safety trigger" failed.
This issue is more severe in `3.x` since there scale NEVER reach 0, but in `master` it does eventually.

Replaced with `Math::is_zero_approx()` instead. It should also fix this issue for any Node2D

Attached test file. There is no error anymore and minimum value for scale is 0.00001
[25986_issue_godot4_MRP.zip](https://github.com/godotengine/godot/files/6796428/25986_issue_godot4_MRP.zip)

<i>Bugsquad edit</i>: Fix #25986

### CODE REVIEW

File: scene/2d/node_2d.cpp [hunk 1]
```diff
@@ -169,11 +169,11 @@ void Node2D::set_scale(const Size2 &p_scale) {
 		((Node2D *)this)->_update_xform_values();
 	}
 	_scale = p_scale;
-	// Avoid having 0 scale values, can lead to errors in physics and rendering.
-	if (_scale.x == 0) {
+	// Avoid having 0 scale values, can lead to errors in physics and rendering. Limit scale to (+-)0.00001.
```
Comment (aaronfranke) [inline scene/2d/node_2d.cpp:172]: The `CMP_EPSILON` constant is already used below. The change to the comment is not necessary and can be worse in the event that the constant is changed. I will give this a :heavy_check_mark: if it's just the code changes.

Comment (JestemStefan) [reply scene/2d/node_2d.cpp]: I removed unnecessary addition to comment 👍

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
