### PR TITLE
Ensure that threads only process one pump task

### LINKED ISSUE #105074: 4.4.1 stable gets stuck on load on my laptop NVIDIA GeForce 920M
### Tested versions

4.4.1 stable

### System information

win 10, NVIDIA GeForce 920M

### Issue description

4.3 was working fine.
Updated to 4.4.1 and now loading hangs up on reimporting assets window. But message and percentage not always the same.

last message in console:
WARNING: The requested V-Sync mode Disabled is not available. Falling back to V-Sync mode Enabled.
     at: swap_chain_resize (drivers/vulkan/rendering_device_driver_vulkan.cpp:3101)

### Steps to reproduce

use old laptop?

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/105074

I was not able to reproduce the issue in https://github.com/godotengine/godot/issues/105074, but I think I understand why it happens in theory and have confirmed that this will catch that situation and fix it. 

Basically, what this does is two things:
1. If a thread recieves a pump task when it already has one, it instead returns and waits until it is signaled again. 
2. If more pump tasks are added than threads, crash the engine. There is no way to safely process multiple pump tasks on one thread (it will always deadlock) and there is no way to recover if a pump task cannot obtain a thread.

### CODE REVIEW

File: core/object/worker_thread_pool.cpp [hunk 1]
```diff
@@ -351,15 +352,23 @@ WorkerThreadPool::TaskID WorkerThreadPool::_add_task(const Callable &p_callable,
 	task->native_func_userdata = p_userdata;
 	task->description = p_description;
 	task->template_userdata = p_template_userdata;
+	task->is_pump_task = p_pump_task;
 	tasks.insert(id, task);
 
-	_post_tasks(&task, 1, p_high_priority, lock);
+	if (p_pump_task) {
+		pump_task_count++;
+		if (pump_task_count > get_thread_count()) {
```
Comment (bruvzg) [inline core/object/worker_thread_pool.cpp]: Seems like we have max 4 pump threads in the editor, so this might be an issue for Web and low-end hardware. Maybe we can spawn an extra thread instead of crashing (at least if total number of threads is low), it's not efficient, but should work.

File: core/object/worker_thread_pool.cpp [hunk 2]
```diff
@@ -218,11 +219,11 @@ void WorkerThreadPool::_thread_function(void *p_user) {
 	}
 }
 
-void WorkerThreadPool::_post_tasks(Task **p_tasks, uint32_t p_count, bool p_high_priority, MutexLock<BinaryMutex> &p_lock) {
+void WorkerThreadPool::_post_tasks(Task **p_tasks, uint32_t p_count, bool p_high_priority, MutexLock<BinaryMutex> &p_lock, bool p_pump_task) {
 	// Fall back to processing on the calling thread if there are no worker threads.
 	// Separated into its own variable to make it easier to extend this logic
 	// in custom builds.
-	bool process_on_calling_thread = threads.is_empty();
+	bool process_on_calling_thread = threads.is_empty() && p_high_priority && !p_pump_task; // Pump tasks can never run on the main thread.
```
Comment (clayjohn) [inline core/object/worker_thread_pool.cpp]: This logic is wrong. Calling thread isn't necessarily the main thread. I'll just remove it since it isn't needed for the fix. 

But I do think we should improve this logic.

File: core/object/worker_thread_pool.cpp (hunk 1 above)
Comment (clayjohn) [reply core/object/worker_thread_pool.cpp]: That's a good idea. We could just warn the user that the setting is too long and then spawn a new thread. 

I'll check and see if there are any issues with adding threads to the WTP at run time. Right now we only ever create threads when it is initialized as far as I can tell

File: core/object/worker_thread_pool.cpp (hunk 2 above)
Comment (clayjohn) [reply core/object/worker_thread_pool.cpp]: Nevermind, this is needed. We will deadlock if we call a pump task from the calling thread since it means the calling thread will never finish the task that lead to the creation of the pump task

File: core/object/worker_thread_pool.cpp [hunk 3]
```diff
@@ -351,15 +354,42 @@ WorkerThreadPool::TaskID WorkerThreadPool::_add_task(const Callable &p_callable,
...
 	task->template_userdata = p_template_userdata;
+	task->is_pump_task = p_pump_task;
 	tasks.insert(id, task);
 
-	_post_tasks(&task, 1, p_high_priority, lock);
+	if (p_pump_task) {
+		pump_task_count++;
+		int thread_count = get_thread_count();
+		if (pump_task_count > thread_count) {
+			print_verbose(vformat("A greater number of dedicated threads were requested (%i) than threads available (%i). Please increase the number of available worker task threads", pump_task_count, thread_count));
```
Comment (Ivorforce) [inline core/object/worker_thread_pool.cpp]: Might be useful to communicate how we're dealing with the situation:

```suggestion
			print_verbose(vformat("A greater number of dedicated threads were requested (%i) than threads available (%i). Please increase the number of available worker task threads. Recovering this session by spawning more worker task threads.", pump_task_count, thread_count));
```

Comment (clayjohn) [reply core/object/worker_thread_pool.cpp]: Nice suggestion!

**Comment by clayjohn** [comment]
I am testing this in more situations and it seems that dynamically spawning a new thread isn't possible right now and causes a deadlock. We access both the `threads` vector and the `thread_id` hashmap without locking. So already we have potential for a race condition, but it seems like somehow the task_mutex is being held and not released for some reason. Debugging further now

**Comment by clayjohn** [comment]
Just a brief update. The code is working correctly as far as I can tell and we are never allocating two pump tasks on a single thread. This should remove one case of deadlocks. 

However, one of my test cases is the situation where we have more pump tasks than threads. In that case, I am getting a deadlock with the current code (which adds a new thread). The previous version of this PR worked "correctly", but the correct behaviour in that case was to crash with a warning to the user. 

With this version of the PR, when there are more pump tasks than threads, we correctly allocate additional threads, but then the engine deadlocks. I can't figure out exactly why it is deadlocking though. 

For those interested, here is a simple thread dump exhibiting the problem:

The main thread is stuck waiting to synchronize with the PhysicsServer3D while the PhysicsServer3D is stuck yielding to the WTP. In theory, as soon as the main thread requests a sync, the worker thread running the PhysicsServer3D should unlock and stop yielding. But for some reason that isn't happening.

```
2495 Thread_18215694   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2495 start  (in dyld) + 2476  [0x187d1b154]
    +   2495 main  (in godot) + 696  [0x1003f5064]
    +     2495 -[NSApplication run]  (in AppKit) + 476  [0x18b9d5ffc]
    +       2495 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]  (in AppKit) + 700  [0x18c1d94d0]
    +         2495 _DPSNextEvent  (in AppKit) + 660  [0x18b9e2cc8]
    +           2495 _BlockUntilNextEventMatchingListInModeWithFilter  (in HIToolbox) + 76  [0x19292cd30]
    +             2495 ReceiveNextEventCommon  (in HIToolbox) + 648  [0x19292cfd8]
    +               2495 RunCurrentEventLoopInMode  (in HIToolbox) + 292  [0x19292d19c]
    +                 2495 CFRunLoopRunSpecific  (in CoreFoundation) + 608  [0x188183434]
    +                   2495 __CFRunLoopRun  (in CoreFoundation) + 1028  [0x188183e90]
    +                     2495 __CFRunLoopDoObservers  (in CoreFoundation) + 536  [0x188184768]
    +                       2495 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__  (in CoreFoundation) + 36  [0x18818487c]
    +                         2495 invocation function for block in OS_MacOS_NSApp::start_main()  (in godot) + 92  [0x1003b9104]
    +                           2495 Main::iteration()  (in godot) + 484  [0x100445964]
    +                             2495 PhysicsServer3DWrapMT::sync()  (in godot) + 48  [0x104575ee4]
    +                               2495 CommandQueueMT::push_and_sync<CommandQueueMT, void (CommandQueueMT::*)()>(CommandQueueMT*, void (CommandQueueMT::*)())  (in godot) + 224  [0x10420ae48]
    +                                 2495 std::condition_variable::wait(std::unique_lock<std::mutex>&)  (in libc++.1.dylib) + 28  [0x187fcbb14]
    +                                   2495 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1228  [0x10aa19c00]
    +                                     2495 __psynch_cvwait  (in libsystem_kernel.dylib) + 8  [0x1880685ec]
    2495 Thread_18216052
    + 2495 start_wqthread  (in libsystem_pthread.dylib) + 0  [0x10aa1fa8c]
    2495 Thread_18216056
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 Thread::thread_callback(void*)  (in godot) + 80  [0x1015d2ae4]
    +       2495 _IP_ResolverPrivate::_thread_function(void*)  (in godot) + 132  [0x104888e6c]
    +         2495 std::condition_variable::wait(std::unique_lock<std::mutex>&)  (in libc++.1.dylib) + 28  [0x187fcbb14]
    +           2495 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1228  [0x10aa19c00]
    +             2495 __psynch_cvwait  (in libsystem_kernel.dylib) + 8  [0x1880685ec]
    2495 Thread_18216057: WorkerThread 0
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 Thread::thread_callback(void*)  (in godot) + 80  [0x1015d2ae4]
    +       2495 WorkerThreadPool::_thread_function(void*)  (in godot) + 364  [0x104dc569c]
    +         2495 std::condition_variable::wait(std::unique_lock<std::mutex>&)  (in libc++.1.dylib) + 28  [0x187fcbb14]
    +           2495 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1228  [0x10aa19c00]
    +             2495 __psynch_cvwait  (in libsystem_kernel.dylib) + 8  [0x1880685ec]
    2495 Thread_18216060: com.apple.NSEventThread
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 _NSEventThread  (in AppKit) + 144  [0x18bb0d280]
    +       2495 CFRunLoopRunSpecific  (in CoreFoundation) + 608  [0x188183434]
    +         2495 __CFRunLoopRun  (in CoreFoundation) + 1208  [0x188183f44]
    +           2495 __CFRunLoopServiceMachPort  (in CoreFoundation) + 160  [0x188185680]
    +             2495 mach_msg  (in libsystem_kernel.dylib) + 24  [0x188065178]
    +               2495 mach_msg_overwrite  (in libsystem_kernel.dylib) + 476  [0x18806d9c4]
    +                 2495 mach_msg2_internal  (in libsystem_kernel.dylib) + 80  [0x1880775e4]
    +                   2495 mach_msg2_trap  (in libsystem_kernel.dylib) + 8  [0x188064df4]
    2495 Thread_18216061
    + 2495 start_wqthread  (in libsystem_pthread.dylib) + 0  [0x10aa1fa8c]
    2495 Thread_18216064: caulk.messenger.shared:17
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 caulk::thread_proxy<std::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::tuple<caulk::concurrent::details::worker_thread*>>>(void*)  (in caulk) + 96  [0x1926241d8]
    +       2495 caulk::concurrent::details::worker_thread::run()  (in caulk) + 36  [0x1926244d8]
    +         2495 caulk::semaphore::timed_wait(double)  (in caulk) + 212  [0x192624624]
    +           2495 semaphore_wait_trap  (in libsystem_kernel.dylib) + 8  [0x188064d70]
    2495 Thread_18216065: caulk.messenger.shared:high
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 caulk::thread_proxy<std::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::tuple<caulk::concurrent::details::worker_thread*>>>(void*)  (in caulk) + 96  [0x1926241d8]
    +       2495 caulk::concurrent::details::worker_thread::run()  (in caulk) + 36  [0x1926244d8]
    +         2495 caulk::semaphore::timed_wait(double)  (in caulk) + 212  [0x192624624]
    +           2495 semaphore_wait_trap  (in libsystem_kernel.dylib) + 8  [0x188064d70]
    2495 Thread_18216073: caulk::deferred_logger
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 caulk::thread_proxy<std::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::tuple<caulk::concurrent::details::worker_thread*>>>(void*)  (in caulk) + 96  [0x1926241d8]
    +       2495 caulk::concurrent::details::worker_thread::run()  (in caulk) + 36  [0x1926244d8]
    +         2495 caulk::semaphore::timed_wait(double)  (in caulk) + 212  [0x192624624]
    +           2495 semaphore_wait_trap  (in libsystem_kernel.dylib) + 8  [0x188064d70]
    2495 Thread_18216074: com.apple.audio.IOThread.client
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 HALC_IOThread::Entry(void*)  (in CoreAudio) + 88  [0x18aa9b850]
    +       2495 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)  (in CoreAudio) + 108  [0x18a915a8c]
    +         2495 HALC_ProxyIOContext::IOWorkLoop()  (in CoreAudio) + 4272  [0x18a917274]
    +           2495 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)  (in CoreAudio) + 96  [0x18aa42c84]
    +             2495 mach_msg  (in libsystem_kernel.dylib) + 24  [0x188065178]
    +               2495 mach_msg_overwrite  (in libsystem_kernel.dylib) + 476  [0x18806d9c4]
    +                 2495 mach_msg2_internal  (in libsystem_kernel.dylib) + 80  [0x1880775e4]
    +                   2495 mach_msg2_trap  (in libsystem_kernel.dylib) + 8  [0x188064df4]
    2495 Thread_18216095
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 std::__thread_proxy[abi:nn180100]<std::tuple<std::unique_ptr<std::__thread_struct>, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::'lambda'()>>(void*)  (in godot) + 48  [0x10068de20]
    +       2495 tvg::TaskSchedulerImpl::run(unsigned int)  (in godot) + 288  [0x10068df6c]
    +         2495 std::condition_variable::wait(std::unique_lock<std::mutex>&)  (in libc++.1.dylib) + 28  [0x187fcbb14]
    +           2495 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1228  [0x10aa19c00]
    +             2495 __psynch_cvwait  (in libsystem_kernel.dylib) + 8  [0x1880685ec]
    2495 Thread_18216096: WorkerThread 1
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 Thread::thread_callback(void*)  (in godot) + 80  [0x1015d2ae4]
    +       2495 WorkerThreadPool::_thread_function(void*)  (in godot) + 512  [0x104dc5730]
    +         2495 WorkerThreadPool::_process_task(WorkerThreadPool::Task*)  (in godot) + 1008  [0x104dc4f7c]
    +           2495 PhysicsServer3DWrapMT::_thread_loop()  (in godot) + 48  [0x104575d50]
    +             2495 WorkerThreadPool::yield()  (in godot) + 556  [0x104dc70bc]
    +               2495 std::condition_variable::wait(std::unique_lock<std::mutex>&)  (in libc++.1.dylib) + 28  [0x187fcbb14]
    +                 2495 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1228  [0x10aa19c00]
    +                   2495 __psynch_cvwait  (in libsystem_kernel.dylib) + 8  [0x1880685ec]
    2495 Thread_18216097: WorkerThread 2
    + 2495 thread_start  (in libsystem_pthread.dylib) + 8  [0x10aa1faa0]
    +   2495 _pthread_start  (in libsystem_pthread.dylib) + 136  [0x10aa155c0]
    +     2495 Thread::thread_callback(void*)  (in godot) + 80  [0x1015d2ae4]
    +       2495 WorkerThreadPool::_thread_function(void*)  (in godot) + 512  [0x104dc5730]
    +         2495 WorkerThreadPool::_process_task(WorkerThreadPool::Task*)  (in godot) + 1008  [0x104dc4f7c]
    +           2495 PhysicsServer2DWrapMT::_thread_loop()  (in godot) + 48  [0x1045229b4]
    +             2495 WorkerThreadPool::yield()  (in godot) + 556  [0x104dc70bc]
    +               2495 std::condition_variable::wait(std::unique_lock<std::mutex>&)  (in libc++.1.dylib) + 28  [0x187fcbb14]
    +                 2495 _pthread_cond_wait  (in libsystem_pthread.dylib) + 1228  [0x10aa19c00]
    +                   2495 __psynch_cvwait  (in libsystem_kernel.dylib) + 8  [0x1880685ec]
    2495 Thread_18216115
      2495 start_wqthread  (in libsystem_pthread.dylib) + 0  [0x10aa1fa8c]
      ```

File: core/object/worker_thread_pool.cpp (hunk 1 above)
Comment (clayjohn) [reply core/object/worker_thread_pool.cpp]: I'm having trouble tracking down why allocating a new thread at run time is causing a deadlock. I am tempted to instead just check the project settings when initializing the WTP and allocate enough for one thread per system. I.e.:

```
int minimum_threads = 1;
minimum_threads += bool(GLOBAL_GET("physics/3d/run_on_separate_thread"))? 1:0;
minimum_threads += bool(GLOBAL_GET("physics/2d/run_on_separate_thread"))? 1:0;
minimum_threads += OS::get_singleton()->is_separate_thread_rendering_enabled()? 1:0;
minimum_threads += bool(GLOBAL_GET("rendering/textures/vram_compression/compress_with_gpu"))? 1:0; // No guarantee that Betsy is used, but this is the best we can do
```

What do you think?

**Comment by clayjohn** [comment]
I figured out the issue. The new code is breaking because ThreadData/thread cannot be safely relocated. When the LocalVector `threads` is resized, the pointers to the elements are moved, but we store the pointer to the ThreadData when launching each thread, so we cannot move them at run time. 

The problem goes away if I resize to a larger size up front or reserve enough.

File: core/object/worker_thread_pool.cpp [hunk 4]
```diff
@@ -788,6 +827,9 @@ void WorkerThreadPool::init(int p_thread_count, float p_low_priority_task_ratio)
 
 	print_verbose(vformat("WorkerThreadPool: %d threads, %d max low-priority.", p_thread_count, max_low_priority_threads));
 
+	// Reserve 5 threads in case we need separate threads for 1) 2D physics 2) 3D physics 3) rendering 4) GPU texture compression, 5) all other tasks.
+	// We cannot safely increase the Vector size at runtime, so reserve enough up front, but only launch those needed.
+	threads.reserve(5);
```
Comment (clayjohn) [inline core/object/worker_thread_pool.cpp:837]: @bruvzg @Ivorforce This is my hack to ensure that the LocalVector is never resized at run time. Personally, I think this is a bit brittle, but I'm not sure what else to do. Reading from the project settings like I suggested above seems equally brittle to me. 

One option that may be a bit safer would be to do this change, but use a FixedVector instead of a LocalVector, then if we ever try to allocate more threads than those reserved, we will get a very clear error and it will be easy to trace back the issue to the number of threads reserved. 

What do you think?

Comment (Ivorforce) [reply core/object/worker_thread_pool.cpp:837]: I don't think `FixedVector` can work, because `threads` needs to have a dynamic size according to `WorkerThreadPool::init`.

The regular 'safe' resize option would be to change `threads` to hold `ThreadData *` instead of `ThreadData`. On indexed access, this would mean an additional dereference. I don't think it will lead to noticeable regressions, but I can't' guarantee it.

The `reserve` trick also seems OK for me. It would hold until we get more pump threads, which kinda seems like a ticking time bomb, but I'm also not sure we'll have this system forever anyway. I don't fully understand pump tasks yet but my impression so far has been sceptical.

**Review by Ivorforce — COMMENTED** [review]
Isn't this whole situation something that can be foreseen from a specific combination of settings? Perhaps we can just predict when too many pump tasks will be needed for too little threads, and compensate by printing an error like "Too many dedicated threads were set up in the project settings for the amount of available dedicated threads. Please adjust the settings accordingly. Compensating by spawning as many threads as necessary for the given dedicated thread settings."
If properly predicted, we also wouldn't have to reserve / resize `threads` at all.

**Comment by clayjohn** [comment]
> Isn't this whole situation something that can be foreseen from a specific combination of settings? Perhaps we can just predict when too many pump tasks will be needed for too little threads, and compensate by printing an error like "Too many dedicated threads were set up in the project settings for the amount of available dedicated threads. Please adjust the settings accordingly. Compensating by spawning as many threads as necessary for the given dedicated thread settings." If properly predicted, we also wouldn't have to reserve / resize `threads` at all.

Almost. In 3 out of 4 cases we can predict the needed number of threads in advance. See my comment above https://github.com/godotengine/godot/pull/108697#discussion_r2222483493

I don't love this solution as it requires us to basically hard code the project settings in WTP::init() . But in that regard it isn't all that different from the reserve hack since both require an idea of how many potential pump tasks there are. 


Pump tasks are command queues that are associated with a specific thread in the WTP. Basically they are systems that have been assigned a dedicated thread. The thread is yielded to the WTP when the command queues is empty. But as soon as something is added to the queue, the thread returns to processing that queue.

File: core/object/worker_thread_pool.cpp [hunk 5]
```diff
@@ -351,15 +354,46 @@ WorkerThreadPool::TaskID WorkerThreadPool::_add_task(const Callable &p_callable,
...
+			// This is insufficient when using a library like SPIRV-Cross,
+			// which can generate deep stacks and result in a stack overflow.
+#ifdef DEV_ENABLED
+			// Debug builds need an even larger stack size.
+			settings.stack_size = 2 * 1024 * 1024; // 2 MiB
+#else
+			settings.stack_size = 1 * 1024 * 1024; // 1 MiB
+#endif
+#endif
+			threads.resize_initialized(thread_count + 1);
```
Comment (Ivorforce) [inline core/object/worker_thread_pool.cpp:381]: Let's add a sanity check here:


```suggestion
			 // Re-sizing implies relocation, which is not supported for this array.
			CRASH_COND_MSG(thread_count + 1 > threads.get_capacity(), "Reserve trick for worker thread pool failed. Crashing.");
			threads.resize_initialized(thread_count + 1);
```

**Review by Ivorforce — COMMENTED** [review]
Thanks for explaining!

How does this whole 'pump task' thing work out in non-threaded builds? If it just runs the leftover command queues on the main thread, could we imitate that for 'leftover' command queues that didn't get a dedicated thread in the WTP?

Otherwise, while I'm still a bit sceptical about pump tasks in general, I see no reason not to merge this if it solves a release blocker. It seems like a fitting solution for the problem at hand.

**Comment by clayjohn** [comment]
> Thanks for explaining!
> 
> How does this whole 'pump task' thing work out in non-threaded builds? If it just runs the leftover command queues on the main thread, could we imitate that for 'leftover' command queues that didn't get a dedicated thread in the WTP?
> 
> Otherwise, while I'm still a bit sceptical about pump tasks in general, I see no reason not to merge this if it solves a release blocker. It seems like a fitting solution for the problem at hand.

I believe if you use one of the separate thread options in non threaded builds the engine will just deadlock. That's a good reminder though. All of this added code should be behind an `#ifdef THREADS_ENABLED` check

**Review by Ivorforce — APPROVED** [review]
Let's go ahead with this. The PR solves the problem, and is relatively simple at that.
We can continue discussing WTP and pump tasks in 4.6 forwards, but for 4.5 this seems like an appropriate fix.

**Comment by clayjohn** [comment]
> How does this whole 'pump task' thing work out in non-threaded builds? If it just runs the leftover command queues on the main thread, could we imitate that for 'leftover' command queues that didn't get a dedicated thread in the WTP?

Just finished checking on Master. It just livelocks and spams this error endlessly:

https://github.com/godotengine/godot/blob/2d113cc224cb9be07866d003819fcef2226a52ea/core/object/worker_thread_pool.cpp#L585

**Comment by Repiteo** [comment]
Thanks!
