### PR TITLE
Fix freeze after building C# project with a lot of files

### LINKED ISSUE #92485: 1 minute freeze after building C# project consisting of only empty txt files and empty scripts (since 4.1.dev4)
### Tested versions

- Not reproductible in :
v4.0.4.stable.mono.official [fc0b241c9]
v4.1.dev1.mono.official [db1302637]
v4.1.dev3.mono.official [a67d37f7c]

- Reproductible in :
v4.1.dev4.mono.official [5c2295ff5]
v4.1.beta3.mono.official [ada712e06]
v4.1.2.stable.mono.official [399c9dc39]
v4.2.1.stable.mono.official [b09f793f5]
v4.3.dev6.mono.official [89850d553]
v4.3.beta.mono.custom_build [be56cab58]

### System information

Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 Threads)

### Issue description

As the number of `txt files/C# scripts` grows, the project freezes longer and longer when you re-build, i.e.:
- Click `Build` from the toolbar after source changes
- Click `Play `from the toolbar after source changes
- Launch in debug mode from VisualStudio
- Click `Rebuild Project` from the `MSBuild dock`

For `128 scripts / 8192 txt files`, the freeze lasts `56s` on my computer.

As you can see from the "Tested versions" section, the problem seems to have been introduced with v4.1.dev4.mono.official [5c2295f]

### Steps to reproduce

- 1 - download / extract the MRP

- 2 - open it with a .NET version of godot (double-click the godot exe then import the project https://docs.godotengine.org/en/stable/tutorials/editor/project_manager.html#opening-and-importing-projects)

- 3 - wait until the project is completely loaded. i.e. the FileSystem dock should contain something. (This may take a while)
wait

- 4 - create the C# solution (`Project` => `Tools` => `C#` =>` Create C# solution`)
solution

- 5 - rebuild the C# project form the MSBuild dock
build

- 6 - spam-click the editor until it freezes

### Minimal reproduction project (MRP)

[editor-freeze-issue.zip](https://github.com/godotengine/godot/files/15474558/editor-freeze-issue.zip)

### PR DESCRIPTION
**Pull request by Hilderin**
Fixes #92485 

With the MRP project, on Godot 4.2, it took 1 min after rebuild.

With this modification, it now takes less then 1 sec.

I added the method `update_files` in `editor_file_system` that can take a list of files in parameter. Instead of calling `updates_file` from `ScriptManagerBridge` for each file, I call this new method only once.

I was the first time that I tried to modify the native functions between C++ and C# but I think I figured it out!!

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 1]
```diff
@@ -427,10 +427,18 @@ static void LookupScriptForClass(Type type)
...
-                    NativeFuncs.godotsharp_internal_editor_file_system_update_file(nativeScriptPath);
+                    godot_packed_string_array script_paths_packed_array = Marshaling.ConvertSystemArrayToNativePackedStringArray(script_paths);
+                    try
+                    {
+                        NativeFuncs.godotsharp_internal_editor_file_system_update_files(ref script_paths_packed_array);
+                    }
+                    finally
+                    {
+                        script_paths_packed_array.Dispose();
+                    }
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:441]: Just use an `using` statement.

```suggestion
                    using godot_packed_string_array scriptPaths = Marshaling.ConvertSystemArrayToNativePackedStringArray(script_paths);
                    NativeFuncs.godotsharp_internal_editor_file_system_update_files(ref scriptPaths);
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/NativeFuncs.cs [hunk 2]
```diff
@@ -60,6 +60,7 @@ private partial struct UnmanagedCallbacks
             ref DebuggingUtils.godot_stack_info_vector p_stack_info_vector);
 
         internal static partial void godotsharp_internal_editor_file_system_update_file(in godot_string p_script_path);
+        internal static partial void godotsharp_internal_editor_file_system_update_files(ref godot_packed_string_array p_script_paths);
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/NativeFuncs.cs:63]: We usually use `in` when the parameter is not going to be modified, although in practice this doesn't make a difference.

```suggestion
        internal static partial void godotsharp_internal_editor_file_system_update_files(in godot_packed_string_array p_script_paths);
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 3]
```diff
@@ -427,10 +427,18 @@ static void LookupScriptForClass(Type type)
             // This method may be called before initialization.
             if (NativeFuncs.godotsharp_dotnet_module_is_initialized().ToBool() && Engine.IsEditorHint())
             {
-                foreach (var scriptPath in _pathTypeBiMap.Paths)
+                string[] script_paths = _pathTypeBiMap.Paths.ToArray();
+                if (script_paths.Length > 0)
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:431]: Instead of converting to array here, change the type of the [`Paths`](https://github.com/godotengine/godot/blob/1ce6df7087113a61491567f3ac55561d5688e2a8/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs#L67) property to `IReadOnlyCollection<string>`. That way you can use the `Count` property to check how many script paths there are without allocating.

```suggestion
                IReadOnlyCollection<string> scriptPaths = _pathTypeBiMap.Paths;
                if (scriptPaths.Count > 0)
```

File: modules/mono/glue/runtime_interop.cpp [hunk 4]
```diff
@@ -1451,6 +1465,7 @@ static const void *unmanaged_callbacks[]{
 	(void *)godotsharp_stack_info_vector_resize,
 	(void *)godotsharp_stack_info_vector_destroy,
 	(void *)godotsharp_internal_editor_file_system_update_file,
```
Comment (raulsntos) [inline modules/mono/glue/runtime_interop.cpp:1467]: Seems like the `godotsharp_internal_editor_file_system_update_file` method is now unused, so we can probably remove it.

**Review by raulsntos — CHANGES_REQUESTED** [review]
Thanks for contributing to the .NET module. In general, the change makes sense to me but I'd like to confirm with the Editor team that they are OK with this.

I have also left some comments about the .NET changes.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs (hunk 1 above)
Comment (Hilderin) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:441]: I cannot because the variable is passed as ref.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/NativeFuncs.cs (hunk 2 above)
Comment (Hilderin) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/NativeFuncs.cs:63]: Oh nice, I was not able to use using because of the ref!

**Comment by Hilderin** [comment]
All the changes should be done. Thanks for your comments.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 5]
```diff
@@ -427,10 +427,14 @@ static void LookupScriptForClass(Type type)
             // This method may be called before initialization.
             if (NativeFuncs.godotsharp_dotnet_module_is_initialized().ToBool() && Engine.IsEditorHint())
             {
-                foreach (var scriptPath in _pathTypeBiMap.Paths)
+
+                if (_pathTypeBiMap.Paths.Count > 0)
                 {
-                    using godot_string nativeScriptPath = Marshaling.ConvertStringToNative(scriptPath);
-                    NativeFuncs.godotsharp_internal_editor_file_system_update_file(nativeScriptPath);
+                    string[] script_paths = _pathTypeBiMap.Paths.ToArray();
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:433]: The naming convention for local variables in C# is `camelCase`.

```suggestion
                    string[] scriptPaths = _pathTypeBiMap.Paths.ToArray();
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 6]
```diff
@@ -427,10 +427,14 @@ static void LookupScriptForClass(Type type)
...
+                    using (godot_packed_string_array script_paths_packed_array = Marshaling.ConvertSystemArrayToNativePackedStringArray(script_paths))
+                    {
+                        NativeFuncs.godotsharp_internal_editor_file_system_update_files(script_paths_packed_array);
+                    }
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:437]: No need to use braces here since the scope is already delimited by the if.

We also use the `Native` suffix to refer to variables of an interop type. So in this case, the managed variable `scriptsPath` is converted to an unmanaged type and stored in a variable named `scriptsPathNative` that can be used with the NativeFuncs.

```suggestion
                    using godot_packed_string_array scriptPathsNative = Marshaling.ConvertSystemArrayToNativePackedStringArray(scriptPaths);
                    NativeFuncs.godotsharp_internal_editor_file_system_update_files(scriptPathsNative);
```

File: editor/editor_file_system.h [hunk 7]
```diff
@@ -310,6 +310,7 @@ class EditorFileSystem : public Node {
 	void scan();
 	void scan_changes();
 	void update_file(const String &p_file);
+	void update_files(const Vector<String> *p_script_paths);
```
Comment (AThousandShips) [inline editor/editor_file_system.h:313]: Any reason to pass by pointer? It's never modified, should probably be passed like so instead:
```suggestion
	void update_files(const Vector<String> &p_script_paths);
```

File: editor/editor_file_system.cpp [hunk 8]
```diff
@@ -1714,105 +1714,115 @@ HashSet<StringName> EditorFileSystem::_get_scene_groups(const String &p_path) {
...
+	scripts.push_back(p_file);
+	update_files(&scripts);
+}
 
-	if (!_find_file(p_file, &fs, cpos)) {
-		if (!fs) {
-			return;
+void EditorFileSystem::update_files(const Vector<String> *p_script_paths) {
+	for (int idx_file = 0; idx_file < p_script_paths->size(); idx_file++) {
+		String file = (*p_script_paths)[idx_file];
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:1724]:
```suggestion
void EditorFileSystem::update_files(const Vector<String> &p_script_paths) {
	for (const String &file : p_script_paths) {
```
Prefer for-each syntax when appropriate

File: editor/editor_file_system.h (hunk 7 above)
Comment (Hilderin) [reply editor/editor_file_system.h]: You are right, this is a vestige of some other tests.

File: editor/editor_file_system.cpp [hunk 9]
```diff
@@ -1714,105 +1714,114 @@ HashSet<StringName> EditorFileSystem::_get_scene_groups(const String &p_path) {
...
+	Vector<String> scripts;
+	scripts.push_back(p_file);
+	update_files(scripts);
+}
 
-	if (!_find_file(p_file, &fs, cpos)) {
-		if (!fs) {
-			return;
+void EditorFileSystem::update_files(const Vector<String> &p_script_paths) {
+	for (String file : p_script_paths) {
```
Comment (AThousandShips) [inline editor/editor_file_system.cpp:1723]:
```suggestion
	for (const String &file : p_script_paths) {
```
Or is there a specific reason you didn't apply that part? This saves copying and the values aren't (and shouldn't) be modified

Comment (Hilderin) [reply editor/editor_file_system.cpp]: My bad! done!

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 10]
```diff
@@ -427,10 +427,11 @@ static void LookupScriptForClass(Type type)
...
             if (NativeFuncs.godotsharp_dotnet_module_is_initialized().ToBool() && Engine.IsEditorHint())
             {
-                foreach (var scriptPath in _pathTypeBiMap.Paths)
+                if (_pathTypeBiMap.Paths.Count > 0)
                 {
-                    using godot_string nativeScriptPath = Marshaling.ConvertStringToNative(scriptPath);
-                    NativeFuncs.godotsharp_internal_editor_file_system_update_file(nativeScriptPath);
+                    string[] scriptPaths = _pathTypeBiMap.Paths.ToArray();
+                    using (godot_packed_string_array scriptPathsNative = Marshaling.ConvertSystemArrayToNativePackedStringArray(scriptPaths))
+                        NativeFuncs.godotsharp_internal_editor_file_system_update_files(scriptPathsNative);
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:434]: I meant like this:

```suggestion
                    using godot_packed_string_array scriptPathsNative = Marshaling.ConvertSystemArrayToNativePackedStringArray(scriptPaths);
                    NativeFuncs.godotsharp_internal_editor_file_system_update_files(scriptPathsNative);
```

Comment (Hilderin) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs]: I see! done!

**Review by raulsntos — APPROVED** [review]
Works as expected and the changes to the mono module look good to me.

File: editor/editor_file_system.cpp [hunk 11]
```diff
@@ -1714,105 +1714,114 @@ HashSet<StringName> EditorFileSystem::_get_scene_groups(const String &p_path) {
 
 void EditorFileSystem::update_file(const String &p_file) {
 	ERR_FAIL_COND(p_file.is_empty());
-	EditorFileSystemDirectory *fs = nullptr;
-	int cpos = -1;
+	Vector<String> scripts;
+	scripts.push_back(p_file);
+	update_files(scripts);
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1719]:
```suggestion
	update_files({ p_file });
```

**Review by KoBeWi — APPROVED** [review]
Editor changes look ok.

**Comment by akien-mga** [comment]
Thanks!
