### PR TITLE
Ensure `joy_connection_changed` is emitted on the main thread

### LINKED ISSUE #78531: Engine freezes when calling Sprite.new() from joy_connection_changed callback
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Debian 11 - Intel Ivybridge Mobile - GLES3

### Issue description

Pretty much what the title says, the engine freezes when I call Sprite.new() from a method that I previously connected to `joy_connection_changed` signal. No errors are shown.

### Steps to reproduce

1. Run the minimal reproduction project, you will see the Godot icon moving around.
2. Connect or disconnect a gamepad and you will see the icon stops moving due to engine freeze.

### Minimal reproduction project

[minimal-reproduction-project.zip](https://github.com/godotengine/godot/files/11821885/minimal-reproduction-project.zip)

### PR DESCRIPTION
**Pull request by rsubtil**
Closes #78531 (once cherry-picked for `3.x`)

On Linux, the code for querying joypad status runs in a thread (`JoypadLinux::joypad_events_thread_run`). Therefore, the `joy_connection_changed` signal is not emitted on the main thread, which depending on user code, can lead do a deadlock due to thread-unsafe API.

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -475,7 +475,7 @@ void Input::joy_connection_changed(int p_idx, bool p_connected, String p_name, S
 	}
 	joy_names[p_idx] = js;
 
-	emit_signal(SNAME("joy_connection_changed"), p_idx, p_connected);
+	call_deferred("emit_signal", SNAME("joy_connection_changed"), p_idx, p_connected);
```
Comment (akien-mga) [inline core/input/input.cpp:478]: I'd add a comment to clarify, like "Defer to emit on the main thread." (IIUC).

Comment (akien-mga) [reply core/input/input.cpp:479]: BTW I'm not good with multithreading, but would deferring the call to `joy_connection_changed` in the Linux input code solve the issue similarly?

If only some platforms do this in a thread, maybe they should be responsible for deferring to the main thread where needed?

Though this one claims to be thread-safe so I guess this helps provide this guarantee?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
