### PR TITLE
Fix light and multimesh crashes

### LINKED ISSUE #29778: Editor crash in RasterizerStorageGLES3::multimesh_instance_get_color
**Godot version:**
3.2.dev.custom_build. bd937ea39

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fa01151ff60] (??:0)
[2] VectorWriteProxy<float>::operator[](int) (/home/rafal/Pulpit/godot/./core/vector.h:49 (discriminator 7))
[3] RasterizerStorageGLES3::multimesh_instance_get_color(RID, int) const (/home/rafal/Pulpit/godot/drivers/gles3/rasterizer_storage_gles3.cpp:4645 (discriminator 2))
[4] VisualServerRaster::multimesh_instance_get_color(RID, int) const (/home/rafal/Pulpit/godot/servers/visual/visual_server_raster.h:266)
[5] CommandQueueMT::CommandRet2<VisualServer, Color (VisualServer::*)(RID, int) const, RID, int, Color>::call() (/home/rafal/Pulpit/godot/./core/command_queue_mt.h:309 (discriminator 4))
[6] CommandQueueMT::flush_one(bool) (/home/rafal/Pulpit/godot/./core/command_queue_mt.h:431)
[7] CommandQueueMT::wait_and_flush_one() (/home/rafal/Pulpit/godot/./core/command_queue_mt.h:464)
[8] VisualServerWrapMT::thread_loop() (/home/rafal/Pulpit/godot/servers/visual/visual_server_wrap_mt.cpp:70)
[9] VisualServerWrapMT::_thread_callback(void*) (/home/rafal/Pulpit/godot/servers/visual/visual_server_wrap_mt.cpp:58)
[10] ThreadPosix::thread_callback(void*) (/home/rafal/Pulpit/godot/drivers/unix/thread_posix.cpp:76)
[11] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7fa011a20182] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fa0115f9b1f] (??:0)
```
```
valgrind: Unrecognised instruction at address 0x13e53cc.
   at 0x13E53CC: VectorWriteProxy<float>::operator[](int) (vector.h:49)
   by 0x1E73CF1: RasterizerStorageGLES3::multimesh_instance_get_color(RID, int) const (rasterizer_storage_gles3.cpp:4645)
   by 0x34399BA: VisualServerRaster::multimesh_instance_get_color(RID, int) const (visual_server_raster.h:266)
   by 0x34A6508: CommandQueueMT::CommandRet2<VisualServer, Color (VisualServer::*)(RID, int) const, RID, int, Color>::call() (command_queue_mt.h:309)
   by 0x33E6546: CommandQueueMT::flush_one(bool) (command_queue_mt.h:430)
   by 0x33E6646: CommandQueueMT::wait_and_flush_one() (command_queue_mt.h:463)
   by 0x346C4A0: VisualServerWrapMT::thread_loop() (visual_server_wrap_mt.cpp:72)
   by 0x346C405: VisualServerWrapMT::_thread_callback(void*) (visual_server_wrap_mt.cpp:57)
   by 0x1E2D1FE: ThreadPosix::thread_callback(void*) (thread_posix.cpp:74)
   by 0x62E8181: start_thread (pthread_create.c:486)
   by 0x676FB1E: clone (clone.S:95)
Your program just tried to execute an instruction that Valgrind
did not recognise.  There are two possible reasons for this.
1. Your program has a bug and erroneously jumped to a non-code
   location.  If you are running Memcheck and you just saw a
   warning about a bad jump, it's probably your program's fault.
2. The instruction is legitimate but Valgrind doesn't handle it,
   i.e. it's Valgrind's fault.  If you think this is the case or
   you are not sure, please let us know and we'll try to fix it.
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 03c0fb5a7e53ccecdcf0f482bb8c12b155c8ab45
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/03c0fb5a7e53ccecdcf0f482bb8c12b155c8ab45.zip

### LINKED ISSUE #33007: Godot crashes when using OmniLight and CSGSphere
**Godot version:**
3.2.alpha.custom_build. 8c3a5057c

**OS/device including version:**
Ubuntu 19.04, GTX 970
**Issue description:**
Backtrace GLES 2
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fb1a277af60] (??:0)
[2] RasterizerSceneGLES2::_add_geometry_with_material(RasterizerStorageGLES2::Geometry*, RasterizerScene::InstanceBase*, RasterizerStorageGLES2::GeometryOwner*, RasterizerStorageGLES2::Material*, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:1172)
[3] RasterizerSceneGLES2::_add_geometry(RasterizerStorageGLES2::Geometry*, RasterizerScene::InstanceBase*, RasterizerStorageGLES2::GeometryOwner*, int, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:1006 (discriminator 2))
[4] RasterizerSceneGLES2::_fill_render_list(RasterizerScene::InstanceBase**, int, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:1261 (discriminator 4))
[5] RasterizerSceneGLES2::render_scene(Transform const&, CameraMatrix const&, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/drivers/gles2/rasterizer_scene_gles2.cpp:3313)
[6] VisualServerScene::_render_scene(Transform, CameraMatrix const&, bool, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:2187)
[7] VisualServerScene::render_camera(RID, RID, Vector2, RID) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:1757 (discriminator 2))
[8] VisualServerViewport::_draw_3d(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:66)
[9] VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:109)
[10] VisualServerViewport::draw_viewports() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:345)
[11] VisualServerRaster::draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_raster.cpp:109 (discriminator 2))
[12] VisualServerWrapMT::thread_draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:46)
[13] CommandQueueMT::Command2<VisualServerWrapMT, void (VisualServerWrapMT::*)(bool, double), bool, double>::call() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:301 (discriminator 4))
[14] CommandQueueMT::flush_one(bool) (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:427)
[15] CommandQueueMT::wait_and_flush_one() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:460)
[16] VisualServerWrapMT::thread_loop() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:70)
[17] VisualServerWrapMT::_thread_callback(void*) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:58)
[18] ThreadPosix::thread_callback(void*) (/mnt/KubuntuWolne/godot/drivers/unix/thread_posix.cpp:76)
[19] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7fb1a2c7d182] (??:0)
[20] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fb1a2854b1f] (??:0)
```
Backtrace GLES 3
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7ff8d288cf60] (??:0)
[2] RasterizerSceneGLES3::_setup_light(RasterizerSceneGLES3::RenderList::Element*, Transform const&) (/mnt/KubuntuWolne/godot/drivers/gles3/rasterizer_scene_gles3.cpp:1894)
[3] RasterizerSceneGLES3::_render_list(RasterizerSceneGLES3::RenderList::Element**, int, Transform const&, CameraMatrix const&, unsigned int, bool, bool, bool, bool, bool) (/mnt/KubuntuWolne/godot/drivers/gles3/rasterizer_scene_gles3.cpp:2255)
[4] RasterizerSceneGLES3::render_scene(Transform const&, CameraMatrix const&, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/drivers/gles3/rasterizer_scene_gles3.cpp:4535 (discriminator 9))
[5] VisualServerScene::_render_scene(Transform, CameraMatrix const&, bool, RID, RID, RID, RID, int) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:2187)
[6] VisualServerScene::render_camera(RID, RID, Vector2, RID) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_scene.cpp:1757 (discriminator 2))
[7] VisualServerViewport::_draw_3d(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:66)
[8] VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:109)
[9] VisualServerViewport::draw_viewports() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_viewport.cpp:345)
[10] VisualServerRaster::draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_raster.cpp:109 (discriminator 2))
[11] VisualServerWrapMT::thread_draw(bool, double) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:46)
[12] CommandQueueMT::Command2<VisualServerWrapMT, void (VisualServerWrapMT::*)(bool, double), bool, double>::call() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:301 (discriminator 4))
[13] CommandQueueMT::flush_one(bool) (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:427)
[14] CommandQueueMT::wait_and_flush_one() (/mnt/KubuntuWolne/godot/./core/command_queue_mt.h:460)
[15] VisualServerWrapMT::thread_loop() (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:70)
[16] VisualServerWrapMT::_thread_callback(void*) (/mnt/KubuntuWolne/godot/servers/visual/visual_server_wrap_mt.cpp:58)
[17] ThreadPosix::thread_callback(void*) (/mnt/KubuntuWolne/godot/drivers/unix/thread_posix.cpp:76)
[18] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9182) [0x7ff8d2d8f182] (??:0)
[19] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7ff8d2966b1f] (??:0)

```
**Steps to reproduce:**

1. Read Project README - https://github.com/qarmin/The-worst-Godot-test-project#the-worst-godot-test-project
2. Run Project

**Minimal reproduction project:**
[The-worst-Godot-test-project.tar.gz](https://github.com/godotengine/godot/files/3762357/The-worst-Godot-test-project.tar.gz)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/29778
Fixes: https://github.com/godotengine/godot/issues/33007

#29778 results from passing in values outside of the possible values for the ``MultiMeshColorFormat`` and ``MultiMeshCustomDataFormat`` enums. Now the engine will treat values outside that range as if ``*NONE`` had been selected.

#33007 Results from not checking for the existence of a pointer before accessing it.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -3051,6 +3051,7 @@ void RasterizerStorageGLES2::multimesh_instance_set_color(RID p_multimesh, int p
 	ERR_FAIL_COND(!multimesh);
 	ERR_FAIL_INDEX(p_index, multimesh->size);
 	ERR_FAIL_COND(multimesh->color_format == VS::MULTIMESH_COLOR_NONE);
+	ERR_FAIL_INDEX(multimesh->color_format, VS::MULTIMESH_COLOR_FLOAT);
```
Comment (qarmin) [inline drivers/gles2/rasterizer_storage_gles2.cpp]: Now I have this errors 
``` drivers/gles2/rasterizer_storage_gles2.cpp:3087 - Index multimesh->custom_data_format=2 out of size (VisualServer::MULTIMESH_CUSTOM_DATA_FLOAT=2)```

Shouldn't this line look like 
```ERR_FAIL_INDEX(multimesh->color_format, VS::MULTIMESH_COLOR_FLOAT);``` 
or after adding new enum value 
```ERR_FAIL_INDEX(multimesh->color_format, VS::MULTIMESH_COLOR_MAX);``` ?

Comment (clayjohn) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: Your error is for line 3087 (below) which is for ``multimesh_set_custom_data()``. 

However, I see where the issue may be. I may have misunderstood when FAIL_INDEX will fail. 

Indeed: It fails when ``index >= size`` I though it failed when ``index > size``. Looks like we do need to add a new enum.
https://github.com/godotengine/godot/blob/f2aa99a8e2d33e534fa3adbff2981a9c902bbf32/core/error_macros.h#L123-L129
