### PR TITLE
Store `_custom_type_script` meta as String

### LINKED ISSUE #102551: Deserializing custom resource created through inspector results in parser error
### Tested versions

- Reproducible in: 4.4.beta3
- Not reproducible in: 4.3.stable

### System information

Godot v4.4.beta3 - Windows 11 (build 26100) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6636) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 threads)

### Issue description

When doing `bytes_to_var_with_objects(var_to_bytes_with_objects(some_custom_resource))` where `some_custom_resource` was specifically created through the editor inspector, and not through something like `MyResource.new()`, you end up with a debugger break saying:

```
Parser Error: Class "MyResource" hides a global script class.
```

The exact same setup seemingly worked in 4.3-stable.

### Steps to reproduce

1. Open the MRP.
2. Run the main scene.
3. Note error.

### Minimal reproduction project (MRP)

[resource-serialization-error.zip](https://github.com/user-attachments/files/18710656/resource-serialization-error.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #102551

Makes custom type script stored as Script's UID instead of reference. This avoids all issues with accidental saving of script (like #100154,  so #101001 is no longer needed for this particular case).

### CODE REVIEW

File: scene/property_utils.cpp [hunk 1]
```diff
@@ -282,3 +282,29 @@ Vector<SceneState::PackState> PropertyUtils::get_node_states_stack(const Node *p
...
+
+Ref<Script> PropertyUtils::get_custom_type_script(const Object *p_object) {
+	Variant custom_script = p_object->get_meta(SceneStringName(_custom_type_script));
+#ifndef DISABLE_DEPRECATED
+	if (custom_script.get_type() == Variant::OBJECT) {
+		// Convert old script meta.
+		Ref<Script> script_object(custom_script);
+		assign_custom_type_script(const_cast<Object *>(p_object), script_object);
+		return script_object;
+	}
```
Comment (KoBeWi) [inline scene/property_utils.cpp:307]: Bonus conversion code, only relevant for Resources/Nodes created in 4.4.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
Since the type of this metadata item is more generic now and allows any string, this should be renamed to `_custom_type_script_uid` to make it clear that this is a UID (as opposed to a class name).

**Comment by KoBeWi** [comment]
At this point it's not worth to change it anymore.
