### PR TITLE
Change to new PICO interaction profiles

### LINKED ISSUE #79019: Pico Neo 3: The Pico Interaction Profile is not used
### Godot version

v4.0.2.stable.official [7a0977ce2] and v4.0.3.stable.official [5222a99f5]

### System information

Pico Neo 3 Pro Eye; PUI Version 4.8.19; Android 10

### Issue description

When trying to use the controllers, only the menu button and trigger works because the Simple controller profile is used. The system refuses to use the Pico profile (or any other profile). Also creating a custom map and/or deleting the Simple Controller profile did not work.

I expected the Pico Profile to work on a Pico Neo 3.

For clarification, this is the controller I am using: https://sdk.picovr.com/docs/NativeSDK/en/chapter_five.html#id4

### Steps to reproduce

- Just create a Project as shown here: https://www.youtube.com/watch?v=ZckQ-6ocHrI 
- Add a script to the XRController3D node that outputs the signals. Export and start the project.

### Minimal reproduction project

[pico_.zip](https://github.com/godotengine/godot/files/11949055/pico_.zip)

Note: I have also deleted the Android folder.

### PR DESCRIPTION
**Pull request by BastiaanOlij**
We added the Pico interaction we're using before they had officially passed the OpenXR conformance test. The profiles were changed and separate profiles introduced for the neo3 and Pico 4.

While Pico has kept the unofficial interaction profile for backwards compatibility, the correct profiles should be used.

Users with existing applications may need to update their action maps, though I've added a rename for the main profile.

Fixes: #79019

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Just ran through testing this on my PICO now that some unrelated build issues have been resolved. This looks to work properly for me.

**Review by akien-mga — APPROVED** [review]

File: modules/openxr/action_map/openxr_action_map.cpp [hunk 1]
```diff
@@ -308,14 +308,14 @@ void OpenXRActionMap::create_default_action_sets() {
 	profile->add_new_binding(haptic, "/user/hand/left/output/haptic,/user/hand/right/output/haptic");
 	add_interaction_profile(profile);
 
-	// Create our Pico 4 / Neo 3 controller profile
-	profile = OpenXRInteractionProfile::new_profile("/interaction_profiles/pico/neo3_controller");
+	// Create our Pico 4 controller profile
```
Comment (AThousandShips) [inline modules/openxr/action_map/openxr_action_map.cpp:311]:
```suggestion
	// Create our Pico 4 controller profile.
```

File: modules/openxr/extensions/openxr_pico_controller_extension.cpp [hunk 2]
```diff
@@ -56,44 +52,88 @@ void OpenXRPicoControllerExtension::on_register_metadata() {
...
-	metadata->register_io_path("/interaction_profiles/pico/neo3_controller", "Thumbstick touch", "/user/hand/left", "/user/hand/left/input/thumbstick/touch", "", OpenXRAction::OPENXR_ACTION_BOOL);
-	metadata->register_io_path("/interaction_profiles/pico/neo3_controller", "Thumbstick", "/user/hand/right", "/user/hand/right/input/thumbstick", "", OpenXRAction::OPENXR_ACTION_VECTOR2);
-	metadata->register_io_path("/interaction_profiles/pico/neo3_controller", "Thumbstick click", "/user/hand/right", "/user/hand/right/input/thumbstick/click", "", OpenXRAction::OPENXR_ACTION_BOOL);
-	metadata->register_io_path("/interaction_profiles/pico/neo3_controller", "Thumbstick touch", "/user/hand/right", "/user/hand/right/input/thumbstick/touch", "", OpenXRAction::OPENXR_ACTION_BOOL);
-
-	metadata->register_io_path("/interaction_profiles/pico/neo3_controller", "Haptic output", "/user/hand/left", "/user/hand/left/output/haptic", "", OpenXRAction::OPENXR_ACTION_HAPTIC);
-	metadata->register_io_path("/interaction_profiles/pico/neo3_controller", "Haptic output", "/user/hand/right", "/user/hand/right/output/haptic", "", OpenXRAction::OPENXR_ACTION_HAPTIC);
+	// Make sure we switch to our new name
```
Comment (AThousandShips) [inline modules/openxr/extensions/openxr_pico_controller_extension.cpp:55]:
```suggestion
	// Make sure we switch to our new name.
```

File: modules/openxr/extensions/openxr_pico_controller_extension.cpp [hunk 3]
```diff
@@ -56,44 +52,88 @@ void OpenXRPicoControllerExtension::on_register_metadata() {
...
+	metadata->register_profile_rename("/interaction_profiles/pico/neo3_controller", "/interaction_profiles/bytedance/pico_neo3_controller");
+
+	// Pico neo 3 controller
```
Comment (AThousandShips) [inline modules/openxr/extensions/openxr_pico_controller_extension.cpp:58]:
```suggestion
	// Pico neo 3 controller.
```

File: modules/openxr/extensions/openxr_pico_controller_extension.cpp [hunk 4]
```diff
@@ -56,44 +52,88 @@ void OpenXRPicoControllerExtension::on_register_metadata() {
...
+	metadata->register_io_path("/interaction_profiles/bytedance/pico_neo3_controller", "Thumbstick", "/user/hand/right", "/user/hand/right/input/thumbstick", "", OpenXRAction::OPENXR_ACTION_VECTOR2);
+	metadata->register_io_path("/interaction_profiles/bytedance/pico_neo3_controller", "Thumbstick click", "/user/hand/right", "/user/hand/right/input/thumbstick/click", "", OpenXRAction::OPENXR_ACTION_BOOL);
+	metadata->register_io_path("/interaction_profiles/bytedance/pico_neo3_controller", "Thumbstick touch", "/user/hand/right", "/user/hand/right/input/thumbstick/touch", "", OpenXRAction::OPENXR_ACTION_BOOL);
+
+	metadata->register_io_path("/interaction_profiles/bytedance/pico_neo3_controller", "Haptic output", "/user/hand/left", "/user/hand/left/output/haptic", "", OpenXRAction::OPENXR_ACTION_HAPTIC);
+	metadata->register_io_path("/interaction_profiles/bytedance/pico_neo3_controller", "Haptic output", "/user/hand/right", "/user/hand/right/output/haptic", "", OpenXRAction::OPENXR_ACTION_HAPTIC);
+
+	// Pico 4 controller
```
Comment (AThousandShips) [inline modules/openxr/extensions/openxr_pico_controller_extension.cpp:99]:
```suggestion
	// Pico 4 controller.
```

**Review by AThousandShips — COMMENTED** [review]
Just some comment style nitpicks

**Comment by BastiaanOlij** [comment]
Thanks @AThousandShips !

**Comment by akien-mga** [comment]
Needs rebase after `OpenXRInteractionProfileMetadata` was renamed.

**Comment by BastiaanOlij** [comment]
@akien-mga all done :)

**Comment by akien-mga** [comment]
Thanks!
