### PR TITLE
[RTL] Fix custom effects not updating.

### LINKED ISSUE #103630: RichTextLabel only renders first installed custom effect when using multiple install_effect() in a row
### Tested versions

- Reproducible in 4.4 stable
- Not reproducible in 4.3 stable

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.7196) - AMD Ryzen 7 9800X3D 8-Core Processor (16 threads)

### Issue description

When adding multiple custom bbcode RichTextEffect using install_effect(effect) at _ready time, only the effect of the first installed effect is rendered and any following still show their unmodified text including tags. This does not happen when instead assigning a new Array to custom_effects which already contains all new effects. When instead appending to the array, no effect gets shown.

I would expect for install_effect() to behave like assigning a new array.

Image

Altering the text in the running project does update everything correctly for all three methods shown.

### Steps to reproduce

Create a custom script for RichTextLabel with something like this:

```
func _ready() -> void:
	custom_effects.clear()
	install_effect(load("uid://c2vp3pnlokpg2")) # Only this effect works
	install_effect(load("uid://3ke1uaie6igq"))
	install_effect(load("uid://dsfc7ow5qjeet"))
```

### Minimal reproduction project (MRP)

[texteffecttest.zip](https://github.com/user-attachments/files/19089575/texteffecttest.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/103630

- Fixes `install_effect` not updating label text (`INSTALL_EFFECT` case).
- There's no reliable way to track external `Array` changes, so I have added `reload_effects` method to use after such changes (`APPEND_ARRAY` case).
```gdscript
	custom_effects.append(load("uid://c2vp3pnlokpg2"))
	custom_effects.append(load("uid://3ke1uaie6igq"))
	custom_effects.append(load("uid://dsfc7ow5qjeet"))
	reload_effects()
```

### CODE REVIEW

**Comment by Mickeon** [comment]
If **RichTextLabel** relied on auxiliary methods to interface with the array instead of exposing it as is, `reload_effects()` wouldn't be necessary. I guess it's too late for that

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -6357,7 +6357,9 @@ float RichTextLabel::get_visible_ratio() const {
 void RichTextLabel::set_effects(Array p_effects) {
 	custom_effects = p_effects;
 	if (!stack_externally_modified && use_bbcode) {
+		internal_stack_editing = true;
 		parse_bbcode(atr(text));
+		internal_stack_editing = false;
 	}
```
Comment (KoBeWi) [inline scene/gui/rich_text_label.cpp:6363]: You could replace this with `reload_effects()`. Same below.

File: doc/classes/RichTextLabel.xml [hunk 2]
```diff
@@ -525,6 +525,12 @@
 				Adds a [code skip-lint][u][/code] tag to the tag stack.
 			</description>
 		</method>
+		<method name="reload_effects">
+			<return type="void" />
+			<description>
+				Reloads externally modified custom effects.
```
Comment (KoBeWi) [inline doc/classes/RichTextLabel.xml:531]:
```suggestion
				Reloads custom effects. Useful when [member custom_effects] is modified manually.
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
