### PR TITLE
Fix closest edge and face check in `NavigationServer3D.map_get_closest_point_to_segment`

### LINKED ISSUE #93138: `NavigationServer3D.map_get_closest_point_to_segment` only returns correct result if segment intersects nav mesh
### Tested versions

Reproducible in 4.3.beta1

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

`NavigationServer3D.map_get_closest_point_to_segment` only returns correct result if segment intersects the nav mesh. If both endpoints of the segment are above or below the nav mesh, then it will return the *closest point on an edge*. The expected result would be to return the closest point on the nav mesh, period.

In the GIF below, you can see the two blue points representing the endpoints of the segment. The red represents the output of `NavigationServer3D.map_get_closest_point_to_segment`. As you can see, it lands directly on an edge:

closest_point_to_segment_edge

The expected result is for it to land right beneath the lower of the two blue points, like this:

closest_point_to_segment_edge_correct

When the two blue points are on opposite sides of the nav mesh (the segment intersects the nav mesh), the function produces the correct result, with the red point being on the surface of the nav mesh, at a position where the segment crosses it.

closest_point_to_segment_edge_intersects

### Steps to reproduce

- Open the attached project.
- Turn on `Debug > Visible Navigation` in the menu.
- Run the project or scene.
- Observe the results.
- Rearrange `endpoint_A` and `endpoint_B` and repeat, and note that the error only happens when the segment does not intersect the nav mesh.

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/15827967/bug-report.zip)

### PR DESCRIPTION
**Pull request by oshman99**
If the line segment was not intersecting a face, Geometry3D::get_closest_points_between_segments was used. It calculated distance between the line segment and face's edges, instead of the distance between the line segment and face itself. 
Since If the line segment is not itersecting a face, closest point to this face will be either beggining or end of this line segment, Face3::get_closest_point_to was used.

- Fixes https://github.com/godotengine/godot/issues/93138
ezgif-7-15f81872d7

### CODE REVIEW

**Review by smix8 — APPROVED** [review]
Thanks.

On a different note the NavigationServer3D documentation of that function should be improved to clarify what the collision parameter does.

**Review by AThousandShips — APPROVED** [review]

File: modules/navigation/nav_map.cpp [hunk 1]
```diff
@@ -627,24 +627,20 @@ Vector3 NavMap::get_closest_point_to_segment(const Vector3 &p_from, const Vector
...
-				Vector3 a, b;
-
-				Geometry3D::get_closest_points_between_segments(
-						p_from,
-						p_to,
-						p.points[point_id].pos,
-						p.points[(point_id + 1) % p.points.size()].pos,
-						a,
-						b);
+			// If segment does not itersect face, check the distance from segment's endpoints
```
Comment (AThousandShips) [inline modules/navigation/nav_map.cpp:630]:
```suggestion
			// If segment does not itersect face, check the distance from segment's endpoints.
```

**Comment by AThousandShips** [comment]
When you've fixed the comment please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) 

And please also update the commit message to match the PR title to make it a bit clearer

**Comment by oshman99** [comment]
Sorry, my bad. Will follow pull-request guidelines properly next time.

**Comment by kleonc** [comment]
> Since If the line segment is not itersecting a face, closest point to this face will be either beggining or end of this line segment,

This is incorrect statement (and hence this PR is incorrect as well). Counterexample: consider a face `[(0, 0, 0), (1, 0, 0), (0, 1, 0)]` and a segment `[(0, 0, 1), (1, 2, 0)]`. Then:
- Segment's endpoint `(0, 0, 1)` distance to the face is `1.0`, closest on-face point is `(0, 0, 0)`.
- Segment's endpoint `(1, 2, 0)` distance to the face is `sqrt(2)` (approx `1.414`), closest on-face point is `(0, 1, 0)`.
- Distance of on-segment point `(5 / 11, 10 / 11, 6 / 11)` to on-face point `(3 / 11, 8 / 11, 0)` (it's on face's edge) is `2 / sqrt(11)` (approx `0.603`).

**Comment by oshman99** [comment]
@kleonc you're right, completely missed this, thanks! I still would like to try to implement a proper fix with your correction in mind.
@AThousandShips what would be the correct way of handeling this? Should a bug be reopened and a new PR created?

**Comment by akien-mga** [comment]
A bug report could be good so we make sure to track this for the 4.3 release, and ensure that we can either merge a fix up PR, or revert this one if it's incorrect, to revisit later.

**Comment by kleonc** [comment]
> I still would like to try to implement a proper fix with your correction in mind.

@oshman99 So any update on this / are you planning to open a PR? If you are not able to then please say so (in such case I'll address this myself). :slightly_smiling_face:

**Comment by oshman99** [comment]
@kleonc yeah you can go ahead and address this. Wanted to tackle it today, but life got in the way. If you don't mind, can you tag me in your PR, when you create one?

**Comment by kleonc** [comment]
> @kleonc yeah you can go ahead and address this. Wanted to tackle it today, but life got in the way. If you don't mind, can you tag me in your PR, when you create one?

@oshman99 Oh, I've asked kinda preemptively (seeing no update and just wanting to ensure it will be fixed for 4.3.stable). Aka haven't looked into this myself yet, maybe I'll do so tomorrow/Tuesday. So if you still want to open PR yourself feel free to do so (sorry if I made you not open a PR today etc.!); a simple fix ensuring correctness of the result would be fine for now (there's very likely a more optimal way to do the calculations as we're dealing with convex polygons / triangle fans and currently we're considering/checking each triangle separately).
And sure I'll tag you if I'll end up opening a PR for this.

**Comment by oshman99** [comment]
> @oshman99 Oh, I've asked kinda preemptively (seeing no update and just wanting to ensure it will be fixed for 4.3.stable). Aka haven't looked into this myself yet, maybe I'll do so tomorrow/Tuesday. So if you still want to open PR yourself feel free to do so (sorry if I made you not open a PR today etc.!); a simple fix ensuring correctness of the result would be fine for now (there's very likely a more optimal way to do the calculations as we're dealing with convex polygons / triangle fans and currently we're considering/checking each triangle separately). And sure I'll tag you if I'll end up opening a PR for this.

@kleonc oh, hahaha, sorry for causing confusion then. There is MOST DEFINITELY a more optimal way of doing things. My first instinct was to basically add a third shortest distance check, that would compare the current shortest distance with the distance to the edge (basically, a copy-paste of the previous implementation). It works fine, but that's a pretty naive solution. I'll create a PR today and ping you and @smix8 . Feel free to comment on any issues or suggest better ways of doing this :)
