### PR TITLE
Fix `RandomPCG::random(int, int)` overflow bug

### LINKED ISSUE #94578: GD.RandRange is broken at integer limits, always returning the same number.
### Tested versions

requires C# version as the the issue is related to C#
Godot v4.3.dev5.mono - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.5176) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 Threads)

### System information

Godot v4.3.dev5.mono - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.5176) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 Threads)

### Issue description

C# GD.RandRange is broken when using the minimum and maximum value of the int type
it returns the same number always, which is some big negative number

### Steps to reproduce

get the specified version.

in ready function use the following code line, run the scene a few times. you will get the same number after the first run
use GD.Print(GD.RandRange(int.MinValue, int.MaxValue));

### Minimal reproduction project (MRP)

requires C# version of godot! create a new project and simply use GD.Print(GD.RandRange(int.MinValue, int.MaxValue));
in ready or anywhere.

### PR DESCRIPTION
**Pull request by aaronp64**
- Use int64_t for subtraction before converting to uint32_t
- Don't add one to uint32_t max value for rand() bounds

Fixes #94578

Tested with gdscript below (and similar C# code).  Results will vary from run to run, but old code seemed to consistently use very narrow ranges:

```gdscript
extends Node

func _ready() -> void:
	test_rand_range(-2147483648, 2147483647)
	print("-----")
	test_rand_range(-2147483640, 2147483640)
	print("-----")
	test_rand_range(0, 1)

func test_rand_range(min : int, max : int):
	for i in 5:
		print(randi_range(min, max))

```

old:
```
-2147483647
-2147483647
-2147483647
-2147483647
-2147483647
-----
-2147483629
-2147483639
-2147483639
-2147483632
-2147483631
-----
0
0
1
0
1
```

new:
```
-293104615
-1349897285
51334271
1668222099
762702258
-----
415601630
-584587391
62246720
-877669916
287709698
-----
1
1
1
0
0

```

### CODE REVIEW

File: core/math/random_pcg.cpp [hunk 1]
```diff
@@ -80,5 +80,15 @@ int RandomPCG::random(int p_from, int p_to) {
 	if (p_from == p_to) {
 		return p_from;
 	}
-	return rand(abs(p_from - p_to) + 1) + MIN(p_from, p_to);
+
+	int64_t min = MIN(p_from, p_to);
+	int64_t max = MAX(p_from, p_to);
+	uint32_t diff = static_cast<uint32_t>(max - min);
+
+	if (diff == 4'294'967'295) {
```
Comment (akien-mga) [inline core/math/random_pcg.cpp:88]:
```suggestion
	if (diff == UINT32_MAX) {
```

Comment (aaronp64) [reply core/math/random_pcg.cpp]: Updated to use UINT32_MAX

**Review by Ivorforce — APPROVED** [review]
Looks good!
Needs a rebase to account for UBSan fixes though.

**Comment by aaronp64** [comment]
Rebased.  I saw the UBSAN PR mentioned avoiding implicit sign changing casts - I tried to add static_casts around those cases, but I'm not sure how to test that any UBSAN errors that showed up before for this method haven't been reintroduced.  Is that checked automatically by the `Linux / Editor with clang sanitizers (target=editor, tests=yes, dev_build=yes, use_asan=yes, use_ubsan=yes, use_llvm=yes, linker=lld)` check?  Let me know if there's any other changes needed for that.

**Review by Ivorforce — APPROVED** [review]
I think this should be fine, going along with the UBSan fixes 👍
Edit: Oh, looks like this also needs another rebase for the vulkan fixes.

**Comment by Repiteo** [comment]
Thanks!
