### PR TITLE
Editor: Show actual class name in resource picker tooltips

### LINKED ISSUE #113310: Confusing message in linked resource indicator
### Tested versions

4.6.dev [7ed0b6167618f9c8c5df87c7e83da6003c081368]

### System information

Arch Linux

### Issue description

Image

- Enclosing the quantity in parentheses is inexplicable. It's also using `TTR` instead of `TTRN`.
- `Resource` is used to refer to the `CircleShape2D`. It should either be `resource` or `CircleShape2D`.
- A space is hardcoded before `Left-click to make it unique` for translation. It's better to be on a new line for localization.

https://github.com/godotengine/godot/blob/7ed0b6167618f9c8c5df87c7e83da6003c081368/editor/inspector/editor_resource_picker.cpp#L110-L128

### Steps to reproduce

Inspect resource owning properties in various conditions.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MattiaZir**
- Replaced generic "Resource" with the actual class name (e.g. "Texture2D").
- Used TTRN for correct pluralization 
- Removed unnecessary parentheses around the count.

This fixes #113310.

### CODE REVIEW

File: editor/inspector/editor_resource_picker.cpp [hunk 1]
```diff
@@ -107,19 +108,34 @@ void EditorResourcePicker::_update_resource() {
 
 			String tooltip;
 
+			String resource_name = "resource";
+			if (edited_resource.is_valid()) {
+				resource_name = edited_resource->get_class();
+
+				if (edited_resource->has_meta(SceneStringNames::get_singleton()->_custom_type_script)) {
```
Comment (KoBeWi) [inline editor/inspector/editor_resource_picker.cpp]:
```suggestion
				if (edited_resource->has_meta(SceneStringName(_custom_type_script))) {
```

File: editor/inspector/editor_resource_picker.cpp [hunk 2]
```diff
@@ -107,19 +108,34 @@ void EditorResourcePicker::_update_resource() {
...
+					if (const Ref<Script> custom_script = PropertyUtils::get_custom_type_script(edited_resource.ptr()); custom_script.is_valid()) {
+						if (const String global_name = custom_script->get_global_name(); !global_name.is_empty()) {
```
Comment (KoBeWi) [inline editor/inspector/editor_resource_picker.cpp]: Assignment inside conditions is not allowed (per code style).

**Review by KoBeWi — APPROVED** [review]

File: editor/inspector/editor_resource_picker.cpp (hunk 1 above)
Comment (MattiaZir) [reply editor/inspector/editor_resource_picker.cpp]: Done, thank you!

File: editor/inspector/editor_resource_picker.cpp (hunk 2 above)
Comment (MattiaZir) [reply editor/inspector/editor_resource_picker.cpp]: Thank you for the help, done.

**Comment by Repiteo** [comment]
Thanks!
