### PR TITLE
Fix indentation in script templates

### LINKED ISSUE #78657: Groups of spaces in scripts automatically changing into tabs/indentation
### Godot version

4.0.3.stable

### System information

Windows 11, ask for more info if needed, I'm not sure what else would be needed here.

### Issue description

Issue also asked about on Godot Q&A (currently unresolved): https://ask.godotengine.org/155740/godot-automatically-creating-tabs-script-template-how-that

I have a script template that I use for all my scripts. In this template, I have an instance of a long line of spaces leading to a comment (this is my commenting method of choice, putting all comments on the right). Looks like (without underscores, would be spaces):
my code  _    _    _    _    _    _    _    _    _    _    _    # my comment

It worked perfectly in prior versions, though after switching to Godot 4 it has started converting my groups of spaces into tabs. It now looks like this (with the indent carrots), despite me only including spaces there in my .gd file:
my code  >    >    >    >    >    >    >    >    >       # my comment

I cannot find a way to disable this "feature" and believe it to truly be a bug. Mr. J. Godfrey (a Godot contributor/Q&A admin I think?) believes so as well. I have taken a look at the indentation section of the editor settings but this is a different feature. I like tabs for indents, and am not trying to change that. I just don't want Godot to auto-change my spaces into indents when it sees a group of them. I understand others may, so I'm proposing there is an option created for that (or please inform me of which one it is if it exists). When I create/edit this template in Notepad, I'm able to verify that it is indeed just normal spaces.

### Steps to reproduce

1) Go to this link and download the script template I created (this program won't let me attach a .gd for some reason):
https://drive.google.com/file/d/1oXPKAn_3DulkF2oIFNYTFV3QKuNKdGz-/view?usp=sharing

2) Load it into a folder called "Objects" within your script templates folder (you may need to create this folder, found at *Godot master folder location*...Godot Engine\editor_data\script_templates\

3) Create a new script in Godot 4.0.3.stable and select this file as the template. You may need to create it on a node, type shouldn't matter.

4) Open the new script and see that the "extends" line has a bunch of tab indents when it should just be spaces.

### Minimal reproduction project

N/A, this is trivial

### PR DESCRIPTION
**Pull request by AThousandShips**
Uses a variation on the code from `CodeEdit`, works well in my testing, also fixes the parsing of `meta-space-indent` which was not updated and used the wrong spacing and error message

Would be useful to be able to unify the code but the code for `CodeEdit` turns one type of indentation into another instead of turning two types of indentation into one special sequence

* Fixes: #78657

### CODE REVIEW

**Comment by capnm** [comment]
If possible, you could add some unit tests.

**Comment by AThousandShips** [comment]
I'm not sure that's possible this is specific to the editor interface

**Comment by capnm** [comment]
Purely theoretical: Copy test-template to Project/script_templates/Node/.
Call godot --script create_script.gd  (??) and compare the generated new_script.gd with the expected result.

**Comment by AThousandShips** [comment]
You can't do that from CLI, this is specific to the editor UI, the `ScriptCreateDialog`

File: editor/script_create_dialog.cpp [hunk 1]
```diff
@@ -892,22 +892,41 @@ ScriptLanguage::ScriptTemplate ScriptCreateDialog::_parse_template(const ScriptL
...
+					}
+
+					line = line.left(i - (space_indent_size - 1)) + "_TS_" + line.substr(i + 1);
+
+					space_count = 0;
+					i += -(space_indent_size - 1) + 4;
 				}
-				script_template.content += line.replace("\t", "_TS_") + "\n";
+
+				script_template.content += line + "\n";
```
Comment (dalexeev) [inline editor/script_create_dialog.cpp:929]: Can this be simplified to something like:

```c++
int space_count = 0;
for (int i = 0; i < line.length(); i++) {
    if (line[i] == '\t') {
        script_template.content += "_TS_";
    } else if (line[i] == ' ') {
        space_count++;
        if (space_count == space_indent_size) {
            script_template.content += "_TS_";
            space_count = 0;
        }
    } else {
        script_template.content += line.substr(i) + "\n";
        break;
    }
}
```

File: editor/script_create_dialog.cpp [hunk 2]
```diff
@@ -892,22 +892,41 @@ ScriptLanguage::ScriptTemplate ScriptCreateDialog::_parse_template(const ScriptL
 					script_template.description = line.substr(12, -1).strip_edges();
 				}
 				if (line.begins_with("space-indent")) {
-					String indent_value = line.substr(17, -1).strip_edges();
+					String indent_value = line.substr(13, -1).strip_edges();
```
Comment (dalexeev) [inline editor/script_create_dialog.cpp:895]: The length of the "space-indent" string is 12, but we take the substring from position 13 because the colon is at 12. The condition should be `line.begins_with("space-indent:")`.

Nitpick: The second argument of `substr()` is -1 by default and can be omitted.

File: editor/script_create_dialog.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/script_create_dialog.cpp:929]: Not completely matching but will see about adding a variation of this simplification, thank you!

File: editor/script_create_dialog.cpp (hunk 2 above)
Comment (AThousandShips) [reply editor/script_create_dialog.cpp:895]: True, was written to match the other cases though, but will modify

File: editor/script_create_dialog.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/script_create_dialog.cpp:929]: Which all in all is why I chose to use the method from `CodeEdit` with modifications to keep it more simple while still ensuring the behavior, but will see if I can do something similar while still maintaining that aspect of the original behavior (the part ahead of the first non-space character)

Comment (AThousandShips) [reply editor/script_create_dialog.cpp:929]: Will test the following when I'm back and able to test the code:
```cpp
int space_count = 0;
for (int i = 0; i < line.length(); i++) {
    if (line[i] == '\t') {
        if (space_count) {
            script_template.content += String(" ").repeat(space_count);
            space_count = 0;
        }
        script_template.content += "_TS_";
    } else if (line[i] == ' ') {
        space_count++;
        if (space_count == space_indent_size) {
            script_template.content += "_TS_";
            space_count = 0;
        }
    } else {
        if (space_count) {
            script_template.content += String(" ").repeat(space_count);
            space_count = 0;
        }
        script_template.content += line.substr(i) + "\n";
        break;
    }
}
```

This will deal with the spaces case

File: editor/script_create_dialog.cpp [hunk 3]
```diff
@@ -884,30 +884,49 @@ ScriptLanguage::ScriptTemplate ScriptCreateDialog::_parse_template(const ScriptL
...
+						}
+					} else {
+						break;
+					}
+				}
+				if (space_count) {
+					script_template.content += String(" ").repeat(space_count);
 				}
-				script_template.content += line.replace("\t", "_TS_") + "\n";
+				script_template.content += line.substr(i) + "\n";
```
Comment (AThousandShips) [inline editor/script_create_dialog.cpp:929]: To deal with empty lines or lines that are just whitespace, this matches the pre-first non-whitespace character behavior of the old code, and also matches generally the behavior of converting indentation on save

File: editor/script_create_dialog.cpp [hunk 4]
```diff
@@ -884,30 +884,49 @@ ScriptLanguage::ScriptTemplate ScriptCreateDialog::_parse_template(const ScriptL
...
+				if (line.begins_with("description:")) {
+					script_template.description = line.substr(12).strip_edges();
 				}
-				if (line.begins_with("space-indent")) {
-					String indent_value = line.substr(17, -1).strip_edges();
+				if (line.begins_with("space-indent:")) {
+					String indent_value = line.substr(13).strip_edges();
 					if (indent_value.is_valid_int()) {
 						int indent_size = indent_value.to_int();
 						if (indent_size >= 0) {
```
Comment (dalexeev) [inline editor/script_create_dialog.cpp:898]:
```suggestion
						if (indent_size > 0) {
```

**Review by dalexeev — APPROVED** [review]
I haven't tested this but it looks good to me.

File: editor/script_create_dialog.cpp (hunk 4 above)
Comment (AThousandShips) [reply editor/script_create_dialog.cpp:898]: Is there any reason to change the original support for not converting spaces to indentation?

Comment (dalexeev) [reply editor/script_create_dialog.cpp:898]: I'm not sure about this, just suggested as it looks like a mistake.

Comment (AThousandShips) [reply editor/script_create_dialog.cpp:898]: If it is a mistake it should have an error, but I think it's intentional to simply prevent spaces to be used as indentation

Comment (AThousandShips) [reply editor/script_create_dialog.cpp:898]: That's true, will see, thank you for your feedback!

Will add an error though as it doesn't error out if you have a negative number

**Review by akien-mga — APPROVED** [review]
Seems good to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
