### PR TITLE
Fix errors on file rename or move in the Filesystem Dock

### LINKED ISSUE #82652: Crash on file rename or move
### Godot version

4.2-rc5

### System information

MacOS 12.3

### Issue description

When renaming or moving a file in-editor, Godot crashes. Happens 99.9% of the time.

Video of the issue [here](https://youtu.be/gjQlb6y6ysU).

### Steps to reproduce

1. Load a project
2. Move a directory containing files that are used by other scenes
3. Wait for the crash

### Minimal reproduction project

I don't think an MRP is necessary, but if you can't replicate I'll give it a go.

### PR DESCRIPTION
**Pull request by Jordyfel**
Fix for https://github.com/godotengine/godot/issues/82652#issuecomment-1745963117 (the errors, the crash is still in question)

This happens when at least 2 scenes which depend on a .glb are open, one is the currently edited scene, and another gets reloaded before it in `FilesystemDock::_update_dependencies_after_move()`. This is the reason scene tab order matters.

When attempting to reload another scene which depends on the same glb as the currently edited scene, `scene_tabs->set_current_tab(current_tab);`, gets called in `EditorNode::reload_scene()`. This triggers a code path introduced in [this commit](https://github.com/godotengine/godot/commit/7f96f0603e16a970c7b0ea1fba936e56baf80d4a), which tries to pack the currently edited scene, but it has an invalid dependency path as it has not been reloaded yet.

This results in several errors related to dependencies failing to load.

A simple enough workaround seems to be to always reload the currently edited scene first.

Test project: 
[test_proj.zip](https://github.com/godotengine/godot/files/13266196/test_proj.zip)

Uploaded with `.godot` so the open scenes and scene tab order are preserved.

Test by moving the .glb in and out of the additional dir multiple times. Worth mentioning that on my PC this resulted in a crash only rarely, other times it's error spam.

Note that there is another issue present - after moving the glb, the scene tab is correct, but the edited scene is wrong, and there is a related error in the console, that should be fixed separately.

### CODE REVIEW

**Comment by fire** [comment]
@SaracenOne if you're interested, here's another scene reloading bug.

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1595,6 +1595,11 @@ void FileSystemDock::_update_dependencies_after_move(const HashMap<String, Strin
 	// The following code assumes that the following holds:
 	// 1) EditorFileSystem contains the old paths/folder structure from before the rename/move.
 	// 2) ResourceLoader can use the new paths without needing to call rescan.
+
+	// The currently edited scene should be reloaded first, so get it's path (GH82652).
+	const EditorData &ed = EditorNode::get_singleton()->get_editor_data();
+	const uint64_t edited_scene_path_hash = ed.get_scene_path(ed.get_edited_scene()).hash64();
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1601]: This can be simplified to
```suggestion
	const uint64_t edited_scene_path_hash = EditorNode::get_editor_data().get_scene_path(ed.get_edited_scene()).hash64();
```

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -1604,7 +1609,11 @@ void FileSystemDock::_update_dependencies_after_move(const HashMap<String, Strin
 		const Error err = ResourceLoader::rename_dependencies(file, p_renames);
 		if (err == OK) {
 			if (ResourceLoader::get_resource_type(file) == "PackedScene") {
-				scenes_to_reload.push_back(file);
+				if (file.hash64() == edited_scene_path_hash) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1612]: Not sure if it's worth it to use hash here. Usually we just compare the strings directly. Even with 100 opened scenes there won't be visible difference. (also not even sure if hashing every path is faster)

Comment (AThousandShips) [reply editor/filesystem_dock.cpp:1612]: Hashing here shouldn't be any faster if it's done on each path, hashing a string should take `O(n)` time, where `n` is the length of `file` string *always*, but comparing strings takes `O(n)` only when the strings match length, and exists early if they don't match, so hashing should be slower

File: editor/filesystem_dock.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/filesystem_dock.cpp:1601]: There's two uses of `ed` in that line so not that trivial

Comment (KoBeWi) [reply editor/filesystem_dock.cpp:1601]: Ah ok then. Still, the `get_singleton()` part is not needed, because `get_editor_data()` is static.

**Comment by YuriSizov** [comment]
Could you please amend your commit message to be a bit more descriptive? The current title of the PR is a good option.

**Review by KoBeWi — APPROVED** [review]
The code looks fine, assuming it does fix the issue. I can't reproduce the crash unfortunately.

**Comment by Jordyfel** [comment]
Took a look at the original issue, and it's probably not the crash OP reported. The video he uploaded crashed at reimport, which means that the fs scan was already reached, which is past this code in the function.

I originally thought i had fixed it because I was reaching the same error in Rindbee's comment, even though it did not crash for me (except rarely but I couldn't reproduce). Thought it was a difference between win and linux.

I still think this should go in because it fixes that problem (are linux users experiencing it as a crash?) but the issue should probably be unlinked

**Comment by KoBeWi** [comment]
I tried moving various files and folders and I don't even get any errors. This should've been fixed by some recent PRs, so the issue is odd.

**Comment by YuriSizov** [comment]
> but the issue should probably be unlinked

Feel free to edit your OP to remove the link!

**Comment by Jordyfel** [comment]
Done, left a reference to the comment so it's still clear where the issue came up

**Comment by Jordyfel** [comment]
I tried investigating the crash again, with little luck. It only happens around 5% of the time when moving the glb in and out of the dir, seemingly only in debug (though that might be related to whatever is causing the variance behaving differently in prod build, maybe it can still crash there) and has a very cryptic stack trace (the same one as in the linked comment). It seems to not occur after the change, but that by itself doesn't mean there isn't a deeper root cause.

Will update the PR to reflect that this conclusively fixes only the error spam.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.1.
