### PR TITLE
Fixes TileSet set as local to scene

### LINKED ISSUE #77045: Tile Custom Data cleared when selecting "Local to Scene"
### Godot version

4.01

### System information

Windows 10

### Issue description

It seems a tiles Custom Data is cleared/not set when "Local to Scene" is enabled for the TileMap in the Resource section. At least the custom data isn't set by the time of the _ready function in the script attached to the TileMap.

### Steps to reproduce

create TileMap and tileset with custom data and attached script. in _ready method attempt to read custom data from a used cell. 

In Attached project run it. It will print_debug if it found custom data or not. "Local to Scene" is enabled so it will not find the custom data.

### Minimal reproduction project

[TileMapCustomDataLocalBugReproduce.zip](https://github.com/godotengine/godot/files/11470771/TileMapCustomDataLocalBugReproduce.zip)

### PR DESCRIPTION
**Pull request by groud**
Fixes #77045

Also clarifies the docs about it, explaining that a source cannot belong to two TileSets at once.

### CODE REVIEW

File: scene/resources/tile_set.cpp [hunk 1]
```diff
@@ -504,6 +509,16 @@ void TileSet::remove_source(int p_source_id) {
...
 }
 
+void TileSet::remove_source_ptr(TileSetSource *p_tile_set_source) {
+	for (const KeyValue<int, Ref<TileSetSource>> &kv : sources) {
+		if (kv.value.ptr() == p_tile_set_source) {
+			remove_source(kv.key);
+			return;
+		}
+	}
+	ERR_FAIL_MSG(vformat("Could not remove source: %s", p_tile_set_source));
```
Comment (YuriSizov) [inline scene/resources/tile_set.cpp:519]:
```suggestion
	ERR_FAIL_MSG(vformat("Attempting to remove source from a tileset, but the tileset doesn't have it: %s", p_tile_set_source));
```

**Review by YuriSizov — APPROVED** [review]
