### PR TITLE
EditorHelpBit: Fix content height fit and RTL theme propagation

### LINKED ISSUE #57174: Tooltip boxes not expanding correctly to show multiple lines in editor.
### Godot version

4.0.alpha1.official

### System information

Windows 10

### Issue description

Property tooltip boxes often cut through a line of text:

image

image

The tooltip's size is not consitent, nor is the 'cut hieght':

image

It looks like only single-line tooltips display properly:

image

Altering Windows' app scaling (this settings option:
image) didn't change the behaviour.

### Steps to reproduce

Open the editor and mouseover a property in the inspector.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
This reverts #51619 and fixes the issue properly, as well as enabling
`fit_content_height` which is necessary following #57304.

- Fixes #57174.

Also adds placeholder for property and signal tooltips with no description,
factoring the code while at it.

Thanks @bruvzg for the hints.

---

Before:
image

image

After:
image

image
(Was meant to be italics but we don't set an italics font for the `EditorHelp` it seems.)

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Actually that's not enough, I _also_ need to revert #51619 for it to work.

**Comment by bruvzg** [comment]
I guess with #51619 popup window is checking for RTL size before text is set (so it's size of an empty label), and I do not think there's any code that's recalculating window size after its creation.

**Comment by bruvzg** [comment]
Reverting #51619 and adding this changes to `editor/editor_help.cpp` should fix both color and size issues:

```diff
void EditorHelpBit::_notification(int p_what) {
 		case NOTIFICATION_ENTER_TREE:
 		case NOTIFICATION_THEME_CHANGED: {
 			rich_text->add_theme_color_override("selection_color", get_theme_color(SNAME("selection_color"), SNAME("EditorHelp")));
-		} break;
-
-		case NOTIFICATION_READY: {
 			rich_text->clear();
 			_add_text_to_rt(text, rich_text);

 		} break;
 	}
 }
 
EditorHelpBit::EditorHelpBit() {
 	add_child(rich_text);
 	rich_text->connect("meta_clicked", callable_mp(this, &EditorHelpBit::_meta_clicked));
 	rich_text->set_override_selected_font_color(false);
+	rich_text->set_fit_content_height(true);
 	set_custom_minimum_size(Size2(0, 70 * EDSCALE));
 }
 
```

**Comment by akien-mga** [comment]
Thanks, it seems to work well!

While at it I did some cleanup and tweaks to the `EditorInspector` code that creates the tooltips.

**Comment by akien-mga** [comment]
BTW I noticed another unexpected behavior with property tooltips:
image
image

For `rect_size` there seems to be an extra line / the tooltip height doesn't fit the content exactly. I thought it might be a stray `\n` but it doesn't seem to be the case:
```
(gdb) print property_name
$1 = {_cowdata = {_ptr = 0x184977b0 U"rect_size"}}
(gdb) print property_doc
$2 = {_cowdata = {_ptr = 0x1992b180 U"The size of the node's bounding rectangle, in pixels. [Container] nodes update this property automatically."}}
```

Might be because it's so close to wrapping that the calculations somehow make the height bigger than needed?

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -833,30 +833,41 @@ void EditorProperty::_update_pin_flags() {
...
 }
 
-Control *EditorProperty::make_custom_tooltip(const String &p_text) const {
-	tooltip_text = p_text;
+static Control *make_help_bit(const String &p_text, bool p_property) {
+	PackedStringArray slices = p_text.split("::", false);
+	if (slices.is_empty()) {
+		// Not a valid EditorHelpBit text, use default tooltip.
+		return nullptr;
+	}
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:841]: That's an unverified assumption, but the previous behavior was to return an `EditorHelpBit` with an empty `RichTextLabel`, which is probably never useful. Now the `nullptr` return is handled by `Viewport::_gui_show_tooltip` to create a default tooltip using the same `p_text` as here.

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -1094,25 +1105,7 @@ void EditorInspectorCategory::_notification(int p_what) {
 
 Control *EditorInspectorCategory::make_custom_tooltip(const String &p_text) const {
 	tooltip_text = p_text;
-	EditorHelpBit *help_bit = memnew(EditorHelpBit);
-	help_bit->add_theme_style_override("panel", get_theme_stylebox(SNAME("panel"), SNAME("TooltipPanel")));
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:1098]: This was commented out in `EditorProperty`'s implementation, and I couldn't notice a difference between category (Node names) and property tooltips, so I removed it.

File: editor/editor_inspector.cpp [hunk 3]
```diff
@@ -833,30 +833,41 @@ void EditorProperty::_update_pin_flags() {
...
-				text += "\n" + property_doc;
-			}
+	if (slices.size() > 1) {
+		String property_doc = slices[1].strip_edges();
+		if (property_name != property_doc) {
+			text += "\n" + property_doc;
 		}
-		help_bit->call_deferred(SNAME("set_text"), text); //hack so it uses proper theme once inside scene
+	} else {
+		text += "\n[i]No description.[/i]";
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:859]: As mentioned in the OP, the italics actually don't work because we don't set a font for it in the `EditorHelp` RTL.

**Comment by Chaosus** [comment]
Also, notice that the same pattern from https://github.com/godotengine/godot/pull/51619 used at:
https://github.com/godotengine/godot/blob/c8ee8082f49f4051d7143e24961c45c56910997a/editor/connections_dialog.cpp#L549

**Comment by akien-mga** [comment]
> Also, notice that the same pattern from #51619 used at:
> 
> https://github.com/godotengine/godot/blob/c8ee8082f49f4051d7143e24961c45c56910997a/editor/connections_dialog.cpp#L549

Ah good call, this was indeed buggy too:
image

I'll fix it up.

File: editor/editor_help.cpp [hunk 4]
```diff
@@ -1971,9 +1969,11 @@ EditorHelpBit::EditorHelpBit() {
 	add_child(rich_text);
 	rich_text->connect("meta_clicked", callable_mp(this, &EditorHelpBit::_meta_clicked));
 	rich_text->set_override_selected_font_color(false);
-	set_custom_minimum_size(Size2(0, 70 * EDSCALE));
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply editor/editor_help.cpp:1974]: I changed my mind and added it back, since it would cause this on wrongly initialized entries:
https://github.com/godotengine/godot/pull/57547#issuecomment-1028078230

**Comment by akien-mga** [comment]
Fixed up the `ConnectionsDialog` which indeed had the same problem for the same reason.

I checked other uses of `EditorHelpBit` and then didn't seem to defer updates.

**Comment by bruvzg** [comment]
> BTW I noticed another unexpected behavior with property tooltips

Screenshot 2022-02-02 at 22 42 25

At least final RTL min. size and content size seems to be correct, so it's not related to line breaks, not sure why window is bigger. Probably some intermediate state during `_add_text_to_rt` which has an unclosed tag is bigger, and it did not shrink back.

Adding `rich_text->set_size(Size2(0, 0));` after `_add_text_to_rt` in the notifications should shrink it to min. size and fix the issue.

Screenshot 2022-02-02 at 22 57 49

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
> At least final RTL min. size and content size seems to be correct, so it's not related to line breaks, not sure why window is bigger. Probably some intermediate state during `_add_text_to_rt` which has an unclosed tag is bigger, and it did not shrink back.

That makes sense, the size might be calculated based on that string with `[Container]` instead of `Container` (and thus possibly not properly taking into account the different font? Might be something to keep in mind if we see future issues around this).

> Adding `rich_text->set_size(Size2(0, 0));` after `_add_text_to_rt` in the notifications should shrink it to min. size and fix the issue.

I've added this for now (using the new `reset_size()` which is nicer :)) as it doesn't cost much.

**Comment by bruvzg** [comment]
> Might be something to keep in mind if we see future issues around this).

Might be font, or it's `p_rt->add_text("[");` which is displayed as a visible `[` char until tag is finished.
I guess adding some sort of bulk update mode to prevent recalculation after every single portion of text added might be worth it.
