### PR TITLE
GDScript: Add tests for calling with wrong arguments in Callable.callv() when passing a readonly (const) Array

### LINKED ISSUE #93600: Callable.callv() will make call with wrong arguments if a const Array is passed
### Tested versions

- Reproducible in 4.3.beta2.official [b75f0485b]

### System information

Windows 10 - Godot 4.3.beta2.official [b75f0485b]

### Issue description

Using Callable().callv() will result in a call using the wrong arguments, if the Array being passed is a const.
The bug does not occur if the Array being passed is a var.
The bug does not occur if we use Callable().bindv().call() instead.

### Steps to reproduce

The following code can demonstrate the bug. The debugger does not show any errors or warnings.
```extends Node2D

const arr_const = ['one','two','three','four']
var arr_var = ['one','two','three','four']

func _ready() -> void:
	# non-const works
	somefunc.callv(arr_var)
	# const fails
	somefunc.callv(arr_const)
	# temporary workaround
	somefunc.bindv(arr_const).call()
	
func somefunc(v1,v2,v3,v4):
	print('%s,%s,%s,%s'% [v1,v2,v3,v4])
```
will print:
```
one,two,three,four
four,four,four,four
one,two,three,four
```
The first and third calls work as expected, with the four arguments in the arrays.
Only the second call, which used a const Array and .callv(), made a call with all arguments replaced by the last argument.

In this example, I use a function directly, but this can be reproduced with any Callable().

This seems like a similar issue as #69237, with a similar workaround, but in this case the correct number of arguments was passed.

### Minimal reproduction project (MRP)

[callablecheck.zip](https://github.com/user-attachments/files/15974691/callablecheck.zip)

### PR DESCRIPTION
**Pull request by Nolkaloid**
Use a duplicate of the passed array when it is read-only.

Prior to this fix, when the array was marked as read-only, the temporary address of `p_arguments->read_only` was used for all parameters. Consequently, this caused all parameters to reference the last element of the array.

Fixes #93600.

### CODE REVIEW

**Comment by AThousandShips** [comment]
This would really benefit from having a test added under `modules/gdscript/tests/scripts/runtime/features` to make sure it actually fixes the bug and makes sure it remains fixed

**Comment by Nolkaloid** [comment]
As this is not GDScript specific, shouldn't it be a unit test in `tests/core/variant/test_callable.h` ?

**Comment by AThousandShips** [comment]
We do many of these tests there

Also how did you confirm this was not script specific? I at least suspect it's specific to arguments in script methods being called, due to how the bindings and data passing works

**Comment by AThousandShips** [comment]
Given some of the details here I think I have a potential alternative solution that might be better, I'll look at it along with my other changes in:
* #88905

**Comment by AThousandShips** [comment]
> I'm not sure that the call to duplicate has that much overhead since the underlying Vector uses CoW if I recall correctly. But I might be wrong.

I'm not sure, that's a good point and it might not matter, but i don't think the code is significantly less readable and it avoids potential weirdness

**Comment by Nolkaloid** [comment]
I did a quick check, and indeed the duplication is done using CoW. If it were up to me I'd keep the `duplicate` as it's simpler IMO, but I don't have strong opinions about it. You tell me. I'll add the test in` modules/gdscript/tests/scripts/runtime/features` in the meantime.

**Comment by AThousandShips** [comment]
You decide, both are fine by me, and let's see what the core team says

**Comment by RandomShaper** [comment]
A few thoughts:
- CoW involves dealing with the atomic refcount, with performance implications.
- This looks like an _ad hoc_ fix for an issue due to how read-only arrays are implemented. It may be better to assess solutions to the root issue.

**Comment by AThousandShips** [comment]
I think it might be difficult to handle the issue with read access on the array itself, given the nature of the reference, but I'd say those points reinforce the use of my suggestion above, it avoids the COW issues, and avoids any issues with the data access

I can't think of a reliable way to handle the read only status of array without breaking compatibility, or allocating more data somehow, but regardless I think this situation warrants at least a temporary local solution

**Comment by AThousandShips** [comment]
This also needs to be done for `Object::callv`

File: core/object/object.cpp [hunk 1]
```diff
@@ -733,12 +733,24 @@ void Object::setvar(const Variant &p_key, const Variant &p_value, bool *r_valid)
...
+	Variant *args = nullptr;
 
-	if (p_args.size() > 0) {
-		argptrs = (const Variant **)alloca(sizeof(Variant *) * p_args.size());
-		for (int i = 0; i < p_args.size(); i++) {
-			argptrs[i] = &p_args[i];
+	if (argcount > 0) {
+		argptrs = (const Variant **)alloca(sizeof(Variant *) * argcount);
+
+		// Make copies of the arguments if the array is read-only, otherwise the address of p_arguments->read_only will be copied for each
```
Comment (AThousandShips) [inline core/object/object.cpp:743]:
```suggestion
		// Make copies of the arguments if the array is read-only, otherwise the address of p_arguments->read_only will be copied for each.
```

File: core/object/object.cpp [hunk 2]
```diff
@@ -747,6 +759,14 @@ Variant Object::callv(const StringName &p_method, const Array &p_args) {
 	if (ce.error != Callable::CallError::CALL_OK) {
 		ERR_FAIL_V_MSG(Variant(), "Error calling method from 'callv': " + Variant::get_call_error_text(this, p_method, argptrs, p_args.size(), ce) + ".");
 	}
+
+	// Destroy the copies of the arguments if any
```
Comment (AThousandShips) [inline core/object/object.cpp:763]:
```suggestion
	// Destroy the copies of the arguments if any.
```

File: core/variant/callable.cpp [hunk 3]
```diff
@@ -73,15 +73,36 @@ void Callable::callp(const Variant **p_arguments, int p_argcount, Variant &r_ret
...
 	const Variant **argptrs = nullptr;
-	if (argcount) {
+	Variant *args = nullptr;
+
+	if (argcount > 0) {
 		argptrs = (const Variant **)alloca(sizeof(Variant *) * argcount);
-		for (int i = 0; i < argcount; i++) {
-			argptrs[i] = &p_arguments[i];
+
+		// Make copies of the arguments if the array is read-only, otherwise the address of p_arguments->read_only will be copied for each
```
Comment (AThousandShips) [inline core/variant/callable.cpp:81]:
```suggestion
		// Make copies of the arguments if the array is read-only, otherwise the address of p_arguments->read_only will be copied for each.
```

File: core/variant/callable.cpp [hunk 4]
```diff
@@ -73,15 +73,36 @@ void Callable::callp(const Variant **p_arguments, int p_argcount, Variant &r_ret
...
+				argptrs[i] = &p_arguments[i];
+			}
 		}
 	}
+
 	CallError ce;
 	Variant ret;
 	callp(argptrs, argcount, ret, ce);
+
+	// Destroy the copies of the arguments if any
```
Comment (AThousandShips) [inline core/variant/callable.cpp:99]:
```suggestion
	// Destroy the copies of the arguments if any.
```

File: core/object/object.cpp [hunk 5]
```diff
@@ -747,6 +759,14 @@ Variant Object::callv(const StringName &p_method, const Array &p_args) {
...
+	if (args) {
```
Comment (AThousandShips) [inline core/object/object.cpp:764]: Needs to be moved up above the error check or you'll have leaks

Comment (Nolkaloid) [reply core/object/object.cpp:764]: Perhaps I should use another macro then. If I destroy the arguments before the, the `argptrs` will be pointing to pointers of destroyed Variants.

Comment (AThousandShips) [reply core/object/object.cpp:764]: That would be necessary yes, you'd have to make it `ERR_PRINT` and then have the return under

File: core/object/object.cpp [hunk 6]
```diff
@@ -733,20 +733,42 @@ void Object::setvar(const Variant &p_key, const Variant &p_value, bool *r_valid)
...
+		for (int i = 0; i < argcount; i++) {
+			args[i].~Variant();
+		}
+	}
+
 	if (ce.error != Callable::CallError::CALL_OK) {
-		ERR_FAIL_V_MSG(Variant(), "Error calling method from 'callv': " + Variant::get_call_error_text(this, p_method, argptrs, p_args.size(), ce) + ".");
+		ERR_PRINT("Error calling method from 'callv': " + Variant::get_call_error_text(this, p_method, argptrs, p_args.size(), ce) + ".");
+		return Variant();
```
Comment (AThousandShips) [inline core/object/object.cpp:769]: Not needed if you move it, either erase before error or split

Comment (Nolkaloid) [reply core/object/object.cpp:769]: Nah I'm just stupid and forgot to move it back.

Comment (AThousandShips) [reply core/object/object.cpp:763]:
```suggestion
		// Destroy the copies of the arguments if any.
		if (args) {
			for (int i = 0; i < argcount; i++) {
				args[i].~Variant();
			}
		}
		return Variant();
```

File: core/object/object.cpp [hunk 7]
```diff
@@ -733,21 +733,43 @@ void Object::setvar(const Variant &p_key, const Variant &p_value, bool *r_valid)
...
+			for (int i = 0; i < argcount; i++) {
+				argptrs[i] = &p_args[i];
+			}
 		}
 	}
 
 	Callable::CallError ce;
 	Variant ret = callp(p_method, argptrs, p_args.size(), ce);
+	
+
```
Comment (AThousandShips) [inline core/object/object.cpp:760]:
```suggestion
```

File: core/object/object.cpp [hunk 8]
```diff
@@ -733,21 +733,43 @@ void Object::setvar(const Variant &p_key, const Variant &p_value, bool *r_valid)
...
+		} else {
+			for (int i = 0; i < argcount; i++) {
+				argptrs[i] = &p_args[i];
+			}
 		}
 	}
 
 	Callable::CallError ce;
 	Variant ret = callp(p_method, argptrs, p_args.size(), ce);
+
```
Comment (AThousandShips) [inline core/object/object.cpp:759]:
```suggestion

```

Comment (Nolkaloid) [reply core/object/object.cpp]: White space my nemesis

**Comment by Nolkaloid** [comment]
Indeed this solution is not perfect, and we should consider modifying how read-only arrays are implemented. I will try to think of a nice solution when I have more time.

**Comment by AThousandShips** [comment]
Made an issue tracking the broader issues of the read-only state:
* https://github.com/godotengine/godot/issues/93702

**Review by Ivorforce — CHANGES_REQUESTED** [review]
There's actually been a change since this PR has been opened: `const Array` subscripts no longer use `read_only` semantics! This change has been implemented by https://github.com/godotengine/godot/pull/103999.

In practice, this means https://github.com/godotengine/godot/issues/93600 is already fixed (I just tested the reproducer on `master`). The `object.cpp` and `variant.cpp` changes from this PR are no longer needed.

I'd like to propose removing the logical changes from this PR, but keeping the unit tests, so we can assert this problem doesn't reappear in the future :)

**Comment by Nolkaloid** [comment]
Agreed, I removed the changes.

**Review by Ivorforce — APPROVED** [review]
Awesome, thanks! I think this would have caught the bug happening.

File: modules/gdscript/tests/scripts/runtime/features/callv_readonly_array.gd [hunk 9]
```diff
@@ -0,0 +1,26 @@
+var array_var: Array = ["one", "two", "three", "four"]
+const array_const: Array = ["one", "two", "three", "four"]
+
+var array_nested_var: Array = [["one"], ["two"], ["three"], ["four"]]
+const array_nested_const: Array = [["one"], ["two"], ["three"], ["four"]]
+
+
+func test():
+    assert(array_const.is_read_only() == true)
+    assert(array_nested_const.is_read_only() == true)
```
Comment (AThousandShips) [inline modules/gdscript/tests/scripts/runtime/features/callv_readonly_array.gd:10]:
```suggestion
    Utils.check(array_const.is_read_only() == true)
    Utils.check(array_nested_const.is_read_only() == true)
```
As per:
* https://github.com/godotengine/godot/pull/96229

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
