### PR TITLE
Narrow FileAccess scope to prevent deadlocks.

### LINKED ISSUE #60148: Godot freezes permanently when saving any file
### Godot version

v4.0.alpha.custom_build [f62f36cd9]

### System information

Windows 11,  Vulkan Clustered, Geforce 1660 (512.15)

### Issue description

When saving any file, scene or script, Godot freezes permanently.

https://user-images.githubusercontent.com/10379487/162800968-489af082-6349-4ec9-af56-987cae4cafde.mp4

If you reopen the same project, Godot immediately freezes.

### Steps to reproduce

* create empty project;
* add script;
* change it;
* save it.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #60148

### CODE REVIEW

File: editor/editor_export.cpp [hunk 1]
```diff
@@ -1301,6 +1305,8 @@ Error EditorExportPlatform::save_pack(const Ref<EditorExportPreset> &p_preset, b
 		f->store_buffer(buf, got);
 	}
 
+	ftmp = Ref<FileAccess>(); // Close temp file.
```
Comment (akien-mga) [inline editor/editor_export.cpp:1308]: Wouldn't it be clearer to use `close()` for this?

Comment (akien-mga) [reply editor/editor_export.cpp:1308]: Right, that makes sense. It just looks a bit weird to have to assign a new empty ref to force closing and destroying an existing FileAccess.

I guess another is memdelete but that's not really better.

Comment (akien-mga) [reply editor/editor_export.cpp:1308]: Yes that sounds good!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
