### PR TITLE
Fix look_at with non uniform scaling

### LINKED ISSUE #23247: look_at oscillates between 2 angles with non-uniform scale
**Godot version:**
ee858d0

**OS/device including version:**
Windows 7

**Issue description:**
Using `look_at` on a node with a non-uniform scale causes it to oscillate between 2 angles.

**Steps to reproduce:**
Set a sprite's scale to (x, y) where x != y. Call `look_at` in `_process`.

**Minimal reproduction project:**
[look_at_repro.zip](https://github.com/godotengine/godot/files/2508306/look_at_repro.zip)

### PR DESCRIPTION
**Pull request by ptrojahn**
The angle function doesn't consider the scaling of the local coordinates,
so it needs to be removed first. Fixes #23247

### CODE REVIEW

File: scene/2d/node_2d.cpp [hunk 1]
```diff
@@ -376,7 +376,10 @@ void Node2D::look_at(const Vector2 &p_pos) {
 
 float Node2D::get_angle_to(const Vector2 &p_pos) const {
 
-	return (get_global_transform().affine_inverse().xform(p_pos)).angle();
+	Vector2 local_pos = to_local(p_pos);
+	local_pos.x *= get_scale().x;
+	local_pos.y *= get_scale().y;
+	return local_pos.angle();
```
Comment (akien-mga) [inline scene/2d/node_2d.cpp]: You should be able to use `return (to_local(p_pos) * get_scale()).angle();`, vectors can be multiplied term-by-term.

**Comment by akien-mga** [comment]
Thanks!
