### PR TITLE
Include animation frames in tile atlas merge.

### LINKED ISSUE #58342: The new TileSet Atlas Merging Tool does not include Animations
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

When I try to use the merge tool on a TileSet that uses animations, it only brings the first tile over and gives a bunch of messages and then the animation does not work:

`  Cannot create tile. The tile is outside the texture or tiles are already present in the space the tile would cover.
`

### Steps to reproduce

- use the merge tool
- errors (as soon as select  two atlas to merge) and just the first frame from each animation in merged atlas

### Minimal reproduction project

https://github.com/rakkarage/NewTileMapTest

### PR DESCRIPTION
**Pull request by rakkarage**
`dst_rect_wide` was the same for each frame so kept getting overwritten in the output image I think?
This adjusts `dst_rect_wide` based on separation and columns and frames.
Closes: https://github.com/godotengine/godot/issues/58342
Thanks.

Before:
Screenshot (89)

After:
Screenshot (88)

### CODE REVIEW

**Comment by rakkarage** [comment]
Sorry, I am doing something wrong obviously...
the previous atlas has only 9 and a half tiles (instead of 10) in the second screenshot.
I think I fixed it by only using new frame_coords on subsequent frames `(frame > 0 ? frame_coords : Vector2i(0, 0))`
Thanks.

**Review by Calinou — COMMENTED** [review]
Tested locally (rebased on top of `master` b6ba664830d9ff1bd7eeb72294fa1e7a3827e42e), I see something completely different when testing with the MRP you linked in the issue. I'm using the atlas merging tool in `TileMapAnimation.tscn`'s TileMap node in the TileSet bottom panel.

### `master`

Screenshot_20230622_042048-1

### This PR

image

File: editor/plugins/tiles/atlas_merging_dialog.cpp [hunk 1]
```diff
@@ -68,20 +68,23 @@ void AtlasMergingDialog::_generate_merged(Vector<Ref<TileSetAtlasSource>> p_atla
...
-				Rect2i new_tile_rect_in_altas = Rect2i(atlas_offset + tile_id, atlas_source->get_tile_size_in_atlas(tile_id));
+				Rect2i new_tile_rect_in_atlas = Rect2i(atlas_offset + tile_id, atlas_source->get_tile_size_in_atlas(tile_id));
 
 				// Copy the texture.
+				int animation_columns = atlas_source->get_tile_animation_columns(tile_id);
+				Vector2i animation_separation = atlas_source->get_tile_animation_separation(tile_id);
 				for (int frame = 0; frame < atlas_source->get_tile_animation_frames_count(tile_id); frame++) {
 					Rect2i src_rect = atlas_source->get_tile_texture_region(tile_id, frame);
-					Rect2 dst_rect_wide = Rect2i(new_tile_rect_in_altas.position * new_texture_region_size, new_tile_rect_in_altas.size * new_texture_region_size);
+					Vector2i frame_coords = tile_id + (src_rect.size + animation_separation) * ((animation_columns > 0) ? Vector2i(frame % animation_columns, frame / animation_columns) : Vector2i(frame, 0));
```
Comment (groud) [inline editor/plugins/tiles/atlas_merging_dialog.cpp:78]: This looks kind of too complex for what it needs to be. Maybe something like this ?:
```
animation_columns =  animation_columns < 0 ? atlas_source->get_tile_animation_frames_count(tile_id) : animation_column;
Vector2i pos = new_tile_rect_in_atlas.position + Vector2i(frame % animation_columns, frame/animation_columns) * animation_separation;
Rect2 dst_rect_wide = Rect2i(pos * new_texture_region_size, new_tile_rect_in_atlas.size * new_texture_region_size);
```

**Comment by rakkarage** [comment]
again

it only seems to work if animation in dst... i guess it needs the same kinda fixes for when animation in src

File: editor/plugins/tiles/atlas_merging_dialog.cpp [hunk 2]
```diff
@@ -69,20 +69,26 @@ void AtlasMergingDialog::_generate_merged(Vector<Ref<TileSetAtlasSource>> p_atla
...
+					Vector2i extra = (frame > 0 ? frame_coords : Vector2i(0, 0));
+					atlas_size.x += extra.x;
+					Vector2i newPosition = new_tile_rect_in_atlas.position * new_texture_region_size + extra;
```
Comment (AThousandShips) [inline editor/plugins/tiles/atlas_merging_dialog.cpp:82]:
```suggestion
					Vector2i new_position = new_tile_rect_in_atlas.position * new_texture_region_size + extra;
```
Style requires snake case

**Comment by rakkarage** [comment]
ya sorry it is taking all the frames at least, but new atlas after merge not have animation setup... will try to get that working too

**Comment by KoBeWi** [comment]
Editor crashes if the animation has more rows:
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.2.dev.custom_build (c495eb5102278a110c14bbffbf833ed436d1594d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] Object::set (C:\godot_source\core\object\object.cpp:224)
[1] AtlasMergingDialog::_generate_merged (C:\godot_source\editor\plugins\tiles\atlas_merging_dialog.cpp:145)
[2] AtlasMergingDialog::_update_texture (C:\godot_source\editor\plugins\tiles\atlas_merging_dialog.cpp:162)
[3] call_with_variant_args_helper<AtlasMergingDialog> (C:\godot_source\core\variant\binder_common.h:308)
[4] call_with_variant_args<AtlasMergingDialog> (C:\godot_source\core\variant\binder_common.h:418)
[5] CallableCustomMethodPointer<AtlasMergingDialog>::call (C:\godot_source\core\object\callable_method_pointer.h:105)
[6] Callable::callp (C:\godot_source\core\variant\callable.cpp:51)
[7] CallableCustomUnbind::call (C:\godot_source\core\variant\callable_bind.cpp:255)
[8] Callable::callp (C:\godot_source\core\variant\callable.cpp:51)
[9] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1073)
[10] Node::emit_signalp (C:\godot_source\scene\main\node.cpp:3577)
[11] Object::emit_signal<int,bool> (C:\godot_source\core\object\object.h:891)
[12] ItemList::gui_input (C:\godot_source\scene\gui\item_list.cpp:697)
[13] Control::_call_gui_input (C:\godot_source\scene\gui\control.cpp:1806)
[14] Viewport::_gui_call_input (C:\godot_source\scene\main\viewport.cpp:1576)
[15] Viewport::_gui_input_event (C:\godot_source\scene\main\viewport.cpp:1805)
[16] Viewport::push_input (C:\godot_source\scene\main\viewport.cpp:3152)
[17] Window::_window_input (C:\godot_source\scene\main\window.cpp:1525)
[18] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\godot_source\core\variant\binder_common.h:303)
[19] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\godot_source\core\variant\binder_common.h:418)
[20] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\godot_source\core\object\callable_method_pointer.h:105)
[21] Callable::callp (C:\godot_source\core\variant\callable.cpp:51)
[22] DisplayServerWindows::_dispatch_input_event (C:\godot_source\platform\windows\display_server_windows.cpp:2617)
[23] DisplayServerWindows::_dispatch_input_events (C:\godot_source\platform\windows\display_server_windows.cpp:2582)
[24] Input::_parse_input_event_impl (C:\godot_source\core\input\input.cpp:723)
[25] Input::flush_buffered_events (C:\godot_source\core\input\input.cpp:980)
[26] DisplayServerWindows::process_events (C:\godot_source\platform\windows\display_server_windows.cpp:2301)
[27] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:1479)
[28] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:182)
[29] _main (C:\godot_source\platform\windows\godot_windows.cpp:204)
[30] main (C:\godot_source\platform\windows\godot_windows.cpp:218)
[31] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:232)
[32] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[33] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```
In the issue's MRP change columns of the lower animation to 3 and try to merge it.

File: editor/plugins/tiles/atlas_merging_dialog.cpp [hunk 3]
```diff
@@ -109,6 +115,13 @@ void AtlasMergingDialog::_generate_merged(Vector<Ref<TileSetAtlasSource>> p_atla
 					int changed_id = -1;
 					if (alternative_id == 0) {
 						merged->create_tile(tile_mapping.value, atlas_source->get_tile_size_in_atlas(tile_mapping.key));
+						merged->set_tile_animation_columns(tile_mapping.value, atlas_source->get_tile_animation_columns(tile_mapping.key));
+						int count = atlas_source->get_tile_animation_frames_count(tile_mapping.key);
+						merged->set_tile_animation_frames_count(tile_mapping.value, count);
+						for (int i = 0; i < count; i++)
+							merged->set_tile_animation_frame_duration(tile_mapping.value, i, atlas_source->get_tile_animation_frame_duration(tile_mapping.key, i));
```
Comment (AThousandShips) [inline editor/plugins/tiles/atlas_merging_dialog.cpp:122]:
```suggestion
						for (int i = 0; i < count; i++) {
							merged->set_tile_animation_frame_duration(tile_mapping.value, i, atlas_source->get_tile_animation_frame_duration(tile_mapping.key, i));
						}
```
Code style, always use brackets

**Comment by rakkarage** [comment]
Thanks for feedback.

Another issue I just noticed. Even with no columns some animation frames are a pixel or two offset in output.
Untitled

I cannot replicate the crash, testing with the 4.1.x that I was using at the time? I set the columns of the second animation to 3 and it works but I still get the offset bug. Maybe I should merge / rebase it all up to latest version or idk...
Untitled333

Looking into fixing this...

**Comment by rakkarage** [comment]
fixed the brackets and pixel offset...

`atlas_size.x += extra.x;`
this code is wrong too... tile coords + pixel coords = gibberish
will fix, sorry should not have pushed/spam when not 100%

**Review by KoBeWi — APPROVED** [review]

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
