### PR TITLE
Add `modf` function and fix animation editor snap behavior

### LINKED ISSUE #96159: Animation editor breaks if snapping is set to more than 1 second
### Tested versions

- Reproducible in: 4.3.stable, 4.4.dev1
- Not reproducible in: 4.2.1.stable, 4.2.2.stable

### System information

Windows 11 - Godot v4.3.stable - Vulcan (Forward+)

### Issue description

When snap value is set to more than 1 second animation editor just breaks.
- If snap value is higher than 1 second and equal or less than 2 seconds, then animation keys continue to snap to 1 second, ignoring that value is actually higher
- If snap value is higher than 2 seconds, then animation editor just refuses to create new keys when you try to make them by right clicking on animation track and selecting "Insert key..." option. 
- And you're no longer able to move any animation keys if snapping is set to more than 2 seconds.

### Steps to reproduce

- 1.) Create AnimationPlayer node and some Sprite or ColorRect node inside scene
- 2.) Add new animation and make some simple animation with created Sprite/ColorRect
- 3.) Set snap value to higher than 2 seconds
- 4.) Try to move existing animation keys or create new key via "Insert key..." right-click option

### Minimal reproduction project (MRP)

[animation_test.zip](https://github.com/user-attachments/files/16760572/animation_test.zip)

### PR DESCRIPTION
**Pull request by object71**
Fixes #96159

### CODE REVIEW

File: core/math/math_funcs.h [hunk 1]
```diff
@@ -105,6 +105,9 @@ class Math {
 	static _ALWAYS_INLINE_ double fmod(double p_x, double p_y) { return ::fmod(p_x, p_y); }
 	static _ALWAYS_INLINE_ float fmod(float p_x, float p_y) { return ::fmodf(p_x, p_y); }
 
+	static _ALWAYS_INLINE_ double modf(double p_x, double &p_int) { return ::modf(p_x, &p_int); }
+	static _ALWAYS_INLINE_ float modf(float p_x, float &p_int) { return ::modff(p_x, &p_int); }
+
```
Comment (TokageItLab) [inline core/math/math_funcs.h:110]:
```suggestion
	static _ALWAYS_INLINE_ double modf(double p_x, double *p_int) { return ::modf(p_x, p_int); }
	static _ALWAYS_INLINE_ float modf(float p_x, float *p_int) { return ::modff(p_x, p_int); }

```
Wouldn't this be more natural given cpp's modf format?

File: editor/animation_track_editor.cpp [hunk 2]
```diff
@@ -7079,7 +7079,10 @@ void AnimationTrackEditor::_update_snap_unit() {
 	if (timeline->is_using_fps()) {
 		snap_unit = 1.0 / step->get_value();
 	} else {
-		snap_unit = 1.0 / Math::round(1.0 / step->get_value()); // Follow the snap behavior of the timeline editor.
+		double integer;
+		double fraction = Math::modf(step->get_value(), integer);
```
Comment (TokageItLab) [inline editor/animation_track_editor.cpp:7083]:
```suggestion
		double fraction = Math::modf(step->get_value(), &integer);
```

File: core/math/math_funcs.h (hunk 1 above)
Comment (object71) [reply core/math/math_funcs.h:110]: I wrote it in a more C++ form of way since the std library is C compatible. But I am fine with the proposed changes if you insist? Having it as a pointer indicates better that it is an "out" value.

**Review by TokageItLab — APPROVED** [review]
We may be able to add `modf()` to GlobalScope as a follow up later. But for now, we would like to merge this PR separately to fix the regression.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
