### PR TITLE
Fix static object destructors being called on gpu selection with X11

### LINKED ISSUE #68322: Error "Unreferenced static string to 0: interface_added" on editor startup
### Godot version

9580769e9a8e9542e651859d61452a13cf1eb398

### System information

Archlinux 6.0.6-arch1-1 kernal, X11

### Issue description

Hello
When starting the editor on the latest dev build I get these errors
```
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
```

I spent some time investigating this and I think this happens when the app tries to select the best GPU to use for rendering. Here is where I think the issue is:
In the `detect_prime()` in the `detect_prime_x11.cpp` file. There is a call to `fork()` on line 152.
As far as I understand, this call is supposed to make the sub processes try and make an X11 session then relay the best selected gpu back to the main process. I think the issue comes when these processes finish and `exit()` gets called. They try to free global memory(call global destructors) and thats where they run into this error and output it to console.

The reason I suspect this is because I ran the editor with gdb with `-gdb-set follow-fork-mode child` and the error only happens on the call to `exit()` on line 211 in `detect_prime_x11.cpp` in the sub process.

Removing the call to `emit_signal()` in `text_server.cpp` causes the error to not show up. I suspect that doing this causes the static string to not be allocated and thus does not show in the sub processes so no error because there is no call static object destructors.

I don't know why freeing the static object causes this error. If anyone could have a look at this to confirm that I am on the right track or if this is completely unrelated.
Thanks 

### Steps to reproduce

Start the editor on the latest commit with a dev build and observe terminal output.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Abdul-AZ**
Resolves #68322 

There is no need to call static object destructors on a child process that is used purely for determining the best GPU to use.

### CODE REVIEW

File: platform/linuxbsd/x11/detect_prime_x11.cpp [hunk 1]
```diff
@@ -208,7 +208,10 @@ int detect_prime() {
 				print_verbose("Couldn't write vendor/renderer string.");
 			}
 			close(fdset[1]);
-			exit(0);
+
+			//quick_exit() is used because exit() will call destructors on static objects copied by fork()
```
Comment (akien-mga) [inline platform/linuxbsd/x11/detect_prime_x11.cpp:212]: Please amend the comment to use the same style as surrounding code (capitalized sentences ending with a period, space after `//`).

**Comment by akien-mga** [comment]
You seem to have typoed your email in your Git identity, so it's not attributed to your GitHub account: https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/68345.patch

File: platform/linuxbsd/x11/detect_prime_x11.cpp [hunk 2]
```diff
@@ -208,7 +208,10 @@ int detect_prime() {
 				print_verbose("Couldn't write vendor/renderer string.");
 			}
 			close(fdset[1]);
-			exit(0);
+
+			//The function quick_exit() is used because exit() will call destructors on static objects copied by fork().
+			//These objects will be freed anyway when the process finishes execution.
```
Comment (akien-mga) [inline platform/linuxbsd/x11/detect_prime_x11.cpp:213]: This too :)
```suggestion
			// The function quick_exit() is used because exit() will call destructors on static objects copied by fork().
			// These objects will be freed anyway when the process finishes execution.
```

Comment (Abdul-AZ) [reply platform/linuxbsd/x11/detect_prime_x11.cpp]: Yea sorry will pay more attention next time

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.
