### PR TITLE
Fix a crash in the wild with drag and drop in the Skeleton3D editor.

### LINKED ISSUE #116669: Skeleton3D Editor: Crash in the wild.
### Tested versions

This is happening in a Godot-4.5.1 based engine with Xogot, but from reading the crash, this appears to continue to exist in Godot/master

### System information

iPadOS

### Issue description

This is the stack trace that we are getting in the wild: 

```
0  Xogot                          0x73efbb0 TreeItem::get_metadata(int) const + 83 (cowdata.h:83)
1  Xogot                          0x5cdf960 Skeleton3DEditor::drop_data_fw(Vector2 const&, Variant const&, Control*) + 766 (skeleton_3d_editor_plugin.cpp:766)
2  Xogot                          0x5cdf960 Skeleton3DEditor::drop_data_fw(Vector2 const&, Variant const&, Control*) + 766 (skeleton_3d_editor_plugin.cpp:766)
3  Xogot                          0x2a48018 <deduplicated_symbol> + 4388585496
4  Xogot                          0xa59c430 CallableCustomBind::call(Variant const**, int, Variant&, Callable::CallError&) const + 150 (callable_bind.cpp:150)
5  Xogot                          0x6dbdb0c Control::drop_data(Vector2 const&, Variant const&) + 2075 (control.cpp:2075)
6  Xogot                          0x6b55538 Viewport::_gui_drop(Control*, Vector2, bool) + 1874 (viewport.cpp:1874)
7  Xogot                          0x6b5870c Viewport::gui_perform_drop_at(Vector2 const&, Control*) + 2392 (viewport.cpp:2392)
8  Xogot                          0x6b55820 Viewport::_gui_input_event(Ref<InputEvent>) + 121 (ref_counted.h:121)
9  Xogot                          0x6b5ca10 Viewport::push_input(Ref<InputEvent> const&, bool) + 203 (ref_counted.h:203)
10 Xogot                          0x6bc3968 Window::_window_input(Ref<InputEvent> const&) + 1937 (window.cpp:1937)
11 Xogot                          0x24cb0c8 <deduplicated_symbol> + 4382830792
12 Xogot                          0x2246324 Variant Callable::call<Variant>(Variant) const + 887 (variant.h:887)
13 Xogot                          0x90e3ed8 DisplayServerEmbedded::send_input_event(Ref<InputEvent> const&, int) const + 887 (variant.h:887)
14 Xogot                          0x90e2e80 DisplayServerEmbedded::_dispatch_input_events(Ref<InputEvent> const&) + 203 (ref_counted.h:203)
15 Xogot                          0xa504b3c Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) + 59 (mutex.h:59)
16 Xogot                          0xa50441c Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) + 203 (ref_counted.h:203)
17 Xogot                          0xa501938 Input::flush_buffered_events() + 203 (ref_counted.h:203)
18 Xogot                          0xa9f42fc GodotInstance::iteration() + 121 (godot_instance.cpp:121)
19 Xogot                          0x15b9310 MethodBindTR<bool>::ptrcall(Object*, void const**, void*) const + 58 (method_ptrcall.h:58)
20 Xogot                          0xa9b032c gdextension_object_method_bind_ptrcall(void const*, void*, void const* const*, void*) + 1435 (gdextension_interface.cpp:1435)
21 SwiftGodot                     0x324ed4 __swift_memcpy48_4 + 2315004
22 Xogot                          0x2bc7a4 closure #1 in GodotApp.iterate() + 914 (GodotAppView.swift:914)
23 Xogot                          0x282618 GodotInstance.scopedAttach<A>(callback:) + 432 (SwiftGodotKit.swift:432)
24 SwiftGodot                     0x3cf04 __swift_memcpy49_8 + 19532
25 Xogot                          0xa9b335c CallableCustomExtension::call(Variant const**, int, Variant&, Callable::CallError&) const + 172 (gdextension_interface.cpp:172)
26 Xogot                          0xa9f5920 std::__1::__function::__func<GodotInstance::execute(Callable, bool)::$_0, std::__1::allocator<GodotInstance::execute(Callable, bool)::$_0>, void ()>::operator()() + 887 (variant.h:887)
27 Xogot                          0xa9f3500 TaskExecutor::invokeCallback(void*) + 395 (function.h:395)
28 Xogot                          0xa9f458c GodotInstance::execute(Callable, bool) + 4522460556 (function.h:4522460556)
29 Xogot                          0xa9f5414 MethodBindT<Callable, bool>::ptrcall(Object*, void const**, void*) const + 244 (binder_common.h:244)
30 Xogot                          0xa9b032c gdextension_object_method_bind_ptrcall(void const*, void*, void const* const*, void*) + 1435 (gdextension_interface.cpp:1435)
31 SwiftGodot                     0x32513c __swift_memcpy48_4 + 2315620
32 Xogot                          0x2bc5d4 GodotApp.iterate() + 438 (SwiftGodotKit.swift:438)
33 Xogot                          0x2bcbe0 @objc GodotApp.iterate() + 4347120608 (<compiler-generated>:4347120608)
34 QuartzCore                     0x101d0 CA::Display::DisplayLinkItem::dispatch_(CA::SignPost::Interval<(CA::SignPost::CAEventCode)835322056>&) + 48
35 QuartzCore                     0xfdc8 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 876
36 QuartzCore                     0x10364 CA::Display::DisplayLink::dispatch_deferred_display_links(unsigned int) + 360
37 UIKitCore                      0x9404 _UIUpdateSequenceRun + 84
38 UIKitCore                      0x8ab4 schedulerStepScheduledMainSection + 208
39 UIKitCore                      0x41e4 runloopSourceCallback + 92
40 CoreFoundation                 0xfa8c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
41 CoreFoundation                 0xf8a4 __CFRunLoopDoSource0 + 172
42 CoreFoundation                 0xf700 __CFRunLoopDoSources0 + 232
43 CoreFoundation                 0x10080 __CFRunLoopRun + 840
44 CoreFoundation                 0x11c3c CFRunLoopRunSpecific + 572
45 GraphicsServices               0x1454 GSEventRunModal + 168
46 UIKitCore                      0x135274 -[UIApplication _run] + 816
47 UIKitCore                      0x100a28 UIApplicationMain + 336
48 SwiftUI                        0x3037a4 closure #1 in KitRendererCommon(_:) + 168
49 SwiftUI                        0x901c runApp<A>(_:) + 112
50 SwiftUI                        0x8ed0 static App.main() + 180
51 Xogot                          0x29e1c4 main + 4346995140 (XogotApp.swift:4346995140)
52 ???                            0x1b0aa3f08 (Missing)
```

### Steps to reproduce

No idea, but I have a theory.

In skeleton_3d_editor_plugin.cpp, drag-and-drop is implemented only for the bone tree UI (joint_tree), not for scene nodes in general.   While there is some validation in place, there are two scenarios that do not seem to be covered and could explain the crash:

1. p_data["type"] is not validated
2. that the dragged source is a valid bone type.

Given that Godot has type annotations for the DnD sources, rather than the ad-hoc validation done with the metadata containing `bones/`, wouldn't it be better to use a dedicated DnD type, instead of `nodes`?   Say, we could use `skeleton_bone` as the source

### Minimal reproduction project (MRP)

none, happens in the wild, no further data is available

### PR DESCRIPTION
**Pull request by migueldeicaza**
This patch, rather than stating that it can drag nodes, it uses a dedicated type for the drag operation, and validates the arguments before attempting to perform the operation.

This is a fix for #116669

Additionally, it uses the safer idiom to pass the selected node, as seen in other places in the codebase, where we pass the instance_id rather than the object, and then extract that out.

Looking for comments on the approach and whether I missed something important.

_Bugsquad edited:_
Fixes https://github.com/godotengine/godot/issues/116669

### CODE REVIEW

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -782,11 +787,22 @@ void Skeleton3DEditor::drop_data_fw(const Point2 &p_point, const Variant &p_data
 		return;
 	}
 
+	Dictionary drag_data = p_data;
+
 	TreeItem *target = (p_point == Vector2(Math::INF, Math::INF)) ? joint_tree->get_selected() : joint_tree->get_item_at_position(p_point);
-	TreeItem *selected = Object::cast_to<TreeItem>(Dictionary(p_data)["node"]);
+	TreeItem *selected = Object::cast_to<TreeItem>(ObjectDB::get_instance(drag_data["source"]));
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
	TreeItem *selected = ObjectDB::get_instance<TreeItem>(drag_data["source"]);
```

File: editor/scene/3d/skeleton_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -764,13 +769,13 @@ bool Skeleton3DEditor::can_drop_data_fw(const Point2 &p_point, const Variant &p_
 		return false;
 	}
 
-	TreeItem *selected = Object::cast_to<TreeItem>(Dictionary(p_data)["node"]);
-	if (target == selected) {
+	TreeItem *selected = Object::cast_to<TreeItem>(ObjectDB::get_instance(drag_data["source"]));
```
Comment (AThousandShips) [inline editor/scene/3d/skeleton_3d_editor_plugin.cpp]:
```suggestion
	TreeItem *selected = ObjectDB::get_instance<TreeItem>(drag_data["source"]);
```

**Review by TokageItLab — APPROVED** [review]
I confirmed it fixes bug, need to squash into one commit.

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.3.
