### PR TITLE
Android: Implement Storage Access Framework (SAF) support

### LINKED ISSUE #12669: Android: Implement full Storage Access Framework (SAF) support
### Describe the project you are working on

Godot Android Port Improvements

### Describe the problem or limitation you are having in your project

Currently, without the MANAGE_EXTERNAL_STORAGE permission, the user cannot select or save files outside the Documents and Download directories, and the app can only access files it has created itself.

There are more scoped permissions available for accessing media files, such as READ_MEDIA_IMAGES, READ_MEDIA_AUDIO, and READ_MEDIA_VIDEO. However, to read non-media files (like .txt or .json) from external storage, the app still requires the special MANAGE_EXTERNAL_STORAGE permission.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

By adding support for SAF, users will be able to open and save files from any directory using the system file picker. This approach eliminates the need for any storage-related permissions, as access is granted directly by the system through user interaction.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user opens the system file picker (native FileDialog) on Android, it will behave as it does now i.e showing the picker UI and allowing the user to choose a file or location.

Currently, the file picker returns a file path string for consistency with other platforms. However, to fully support SAF (Storage Access Framework), this needs to change. Instead of returning a file path, the picker will now return a `content URI` directly.

Users can then pass this URI to `FileAccess.open()` just like they would with a normal file path. Internally, Godot will detect whether the `path` parameter is a file path or a content URI, and handle the file access accordingly.

```gdscript
func _on_file_selected(path: String):
    # On Android, if the native file picker is used, the given path will be a content URI (e.g., content://...).
    var file := FileAccess.open(path, FileAccess.READ)
    if file:
        var content := file.get_as_text()
        print(content)
    else:
        push_error("Failed to open file: %s" % path)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, this can't be easily worked around. SAF requires platform-specific handling that are not accessible from GDScript alone without writing a custom Android plugin.

### Is there a reason why this should be core and not an add-on in the asset library?

While this could be implemented as a plugin, it should ideally be part of the core engine. Accessing external `.txt`, `.json`, or other non-media files is a common need for many Android apps and games.

Adding SAF support directly in core would significantly improve Android file access, especially that use of MANAGE_EXTERNAL_STORAGE is discouraged by Google.

### LINKED ISSUE #112136: FileAccess completely broken on android when using DisplayServer.file_dialog_show and not using MANAGE_EXTERNAL_STORAGE
### Tested versions

master 2cb2c1fb5bbeb2afbac7255841f9c66d9611bf55

### System information

Android

### Issue description

I'm trying to use file_dialog_show to let the user pick a directory to read modded data from.

Unfortunately, it seems like when calling FileAccess godot's kotlin code expects a file URI (when not using MANAGE_EXTERNAL_STORAGE), which we do not have as the file_dialog_show callback returns the disk path and not the internal android URI.

Android apps on the play store are not allowed to use MANAGE_EXTERNAL_STORAGE unless they are file managers.

### Steps to reproduce

- Call file_dialog_show
- Observe the returned path is a full path and not an android URI
- Try to run FileAccess.file_exists in a file that you know for a fact exists in the picked directory
- Observe it returns false
- ?????
- profit

### Minimal reproduction project (MRP)

Will include one tomorrow

### PR DESCRIPTION
**Pull request by syntaxerror247**
Closes https://github.com/godotengine/godot-proposals/issues/12669
Resolves https://github.com/godotengine/godot/issues/112136

This PR implements full SAF support:

- The Android file picker now returns a URI.
- This URI can be used with `FileAccess` to perform standard read/write operations.
- You can also request full access to a directory using `FILE_DIALOG_MODE_OPEN_DIR`.
- This would return a `tree URI`, giving you full access to that directory. You can open/create files inside it directly with paths, without reopening the file picker.
- This tree URI should be saved to avoid asking for access to that directory every time. It can be reused across device restarts, as long as the directory isn't renamed, moved, or deleted.
- To work with files inside this directory, use `FileAccess` as usual, but the path should follow the format `treeUri#relative/path/to/file`.
- Finally, you do not need to ask for any file permissions when using this uri method.

<details><summary>Sample code for testing</summary>
<p>

```gdscript
func _pick_file() -> void:
	var filters = PackedStringArray(["*/*"])
	var current_directory = OS.get_system_dir(OS.SYSTEM_DIR_DESKTOP)
	DisplayServer.file_dialog_show("title", current_directory, "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_FILE, filters, _picker_callback)
	

func _picker_callback(status: bool, selected_uris: PackedStringArray, _selected_filter_index: int):
	$Label.text += str("Status: ",status,"\n")
	$Label.text += str("Selected Uris: ",selected_uris,"\n\n")
	
	var path = selected_uris[0]
	print(FileAccess.file_exists(path))
	print(FileAccess.get_size(path))
	print(FileAccess.get_modified_time(path))
	print(FileAccess.get_file_as_bytes(path))
	print(FileAccess.get_file_as_string(path))
	print(FileAccess.get_md5(path))
	print(FileAccess.get_sha256(path))
	
	print("---Saving file normally---")
	var f4 = FileAccess.open(path, FileAccess.WRITE)
	print(f4.store_string("It seems to be working!"))
	f4.close()
	
	print("---Opening file normally---")
	var f1 = FileAccess.open(path, FileAccess.READ)
	print(f1.get_as_text())
	print(f1.get_buffer(30))
	print(f1.get_path())
	print(f1.get_path_absolute())
	f1.seek(5)
	print(f1.get_position())
	f1.close()
	
	print("---Saving file with password---")
	var f2 = FileAccess.open_encrypted_with_pass(path, FileAccess.WRITE, "password")
	print(f2.store_string("Password is \"password\".\n"))
	print(f2.store_line("This is a new line"))
	f2.close()
	
	print("---Opening file with password---")
	var f3 = FileAccess.open_encrypted_with_pass(path, FileAccess.READ, "password")
	print(f3.get_as_text())
	print(f3.get_buffer(5))
	print(f3.get_path())
	print(f3.get_path_absolute())
	f3.seek(5)
	print(f3.get_position())
	f3.close()


func _get_document_tree_uri() -> void:
	var filters = PackedStringArray(["*/*"])
	var current_directory = OS.get_system_dir(OS.SYSTEM_DIR_DESKTOP)
	DisplayServer.file_dialog_show("title", current_directory, "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_DIR, filters, _picker_callback_directory_tree)

func _picker_callback_directory_tree(_status: bool, selected_uris: PackedStringArray, _selected_filter_index: int):
	var directory_tree_uri = selected_uris[0]
	_picker_callback(true, [str(directory_tree_uri+"#"+"testing_saf.txt")], 0)
```

</p>
</details> 

Edit: To be able to reuse the URI across app restarts, you need to request persistable permission. See https://github.com/godotengine/godot/pull/113367

### CODE REVIEW

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+			} catch (e: Exception) {
+				Log.d(TAG, "Error deleting file: $uri", e)
+				false
+			}
+		}
+
+		fun rename(context: Context, uri: Uri, to: String): Boolean {
+			TODO()
+		}
+
```
Comment (syntaxerror247) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: This isn’t implemented yet because the API expects a boolean return, but in SAF case we’d need to return the new file’s URI instead. Without it, the app loses access after renaming, and the user would have to pick the file again. I’m still unsure how to handle this.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/StorageScope.kt [hunk 2]
```diff
@@ -93,6 +95,11 @@ internal enum class StorageScope {
 				return ASSETS
 			}
 
+			val uri = path.toUri()
+			if (uri.scheme == ContentResolver.SCHEME_CONTENT) {
+				return APP
+			}
+
```
Comment (syntaxerror247) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/StorageScope.kt]: Here, I’m setting the scope to APP and later checking if the path is a content uri, then calling methods from SAFData instead of FileData (as shown below). However, I was thinking, maybe we can just create a SAF scope to simplify the logic?

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt [hunk 3]
```diff
@@ -136,23 +150,35 @@ internal abstract class DataAccess {
 			return when(storageScope) {
 				StorageScope.APP -> FileData.fileLastAccessed(path)
 				StorageScope.ASSETS -> AssetData.fileLastAccessed(path)
-				StorageScope.SHARED -> MediaStoreData.fileLastAccessed(context, path)
-				StorageScope.UNKNOWN -> 0L
+				StorageScope.SHARED, StorageScope.UNKNOWN -> 0L
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: Is the `MediaStoreData` value not accurate in this scenario?

Comment (m4gr3d) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]: nvm, I saw the implementation just returned `0L`, so your update looks good.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt (hunk 1 above)
Comment (EIREXE) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: Maybe we shouldn't support renaming at all for SAF accessed files, instead requiring the user to do the move themselves?

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: Removed the support for renaming.
Will try to add support for it future a PR.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/StorageScope.kt (hunk 2 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/StorageScope.kt]: Umm... current logic seems fine to me.

**Comment by syntaxerror247** [comment]
Added support for DocumentTree to allow full access to a directory and do file operations using file paths in this selected directory. For example, when a directory is selected using FILE_DIALOG_MODE_OPEN_DIR, you receive a `treeUri` for eg `content://com.android.externalstorage.documents/tree/primary%3Atestdir`. To perform i/o in this directory, you can use FileAccess as usual, but the path must be relative to the selected directory in the format `treeUri#relative/path/to/file`.

This is now almost ready, only the documentation is left. So, please start reviewing it in the meantime. The sample code is included in the PR description.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/StorageScope.kt (hunk 2 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/StorageScope.kt]: Well... ended up creating a seperate SAF scope, for cleaner code.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt [hunk 4]
```diff
@@ -136,29 +142,35 @@ internal abstract class DataAccess {
...
+				StorageScope.SAF -> SAFData.fileSize(context, path)
+
 				StorageScope.UNKNOWN -> -1L
 			}
 		}
 
 		fun removeFile(storageScope: StorageScope, context: Context, path: String): Boolean {
 			return when(storageScope) {
-				StorageScope.APP -> FileData.delete(path)
+				StorageScope.APP ->FileData.delete(path)
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/DataAccess.kt]:
```suggestion
				StorageScope.APP -> FileData.delete(path)
```

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 5]
```diff
@@ -0,0 +1,155 @@
+package org.godotengine.godot.io.file
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt:31]: You forgot to include the license header.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 6]
```diff
@@ -0,0 +1,155 @@
...
+import android.net.Uri
+import android.provider.DocumentsContract
+import android.util.Log
+import androidx.core.net.toUri
+import androidx.documentfile.provider.DocumentFile
+import java.io.FileInputStream
+import java.io.FileOutputStream
+import java.nio.channels.FileChannel
+
+internal class SAFData(context: Context, path: String, accessFlag: FileAccessFlags) :
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt:47]: Can you add javadocs describing the class purpose.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 7]
```diff
@@ -0,0 +1,155 @@
...
+	DataAccess.FileChannelDataAccess(path) {
+
+	companion object {
+		private val TAG = FileData::class.java.simpleName
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]:
```suggestion
		private val TAG = SAFData::class.java.simpleName
```

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 8]
```diff
@@ -0,0 +1,155 @@
...
+			val treeUri = uri.buildUpon().fragment(null).build()
+			val relativePath = uri.fragment!!
+
+			val rootDir = DocumentFile.fromTreeUri(context, treeUri)
+				?: throw IllegalStateException("Unable to resolve tree URI: $treeUri")
+
+			val parts = relativePath.split('/')
+			val filename = parts.last()
+			val folderParts = parts.dropLast(1)
+			rootDir.exists()
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: What is this used for?

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: Ah, good catch. This isn't used, I was testing something locally and it got pushed by mistake.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 9]
```diff
@@ -0,0 +1,188 @@
...
+		private fun resolvePath(context: Context, path: String, accessFlag: FileAccessFlags): Uri {
+			val uri = path.toUri()
+
+			if (uri.fragment == null) {
+				return uri
+			}
+
+			// For directory format: content://treeUri#relative/path/to/file
+			val treeUri = uri.buildUpon().fragment(null).build()
+			val relativePath = uri.fragment!!
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: Let's be explicit and throw an exception if we're expecting the `fragment` to be non-null.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 10]
```diff
@@ -0,0 +1,188 @@
...
+			val filename = parts.last()
+			val folderParts = parts.dropLast(1)
+
+			var current: DocumentFile? = rootDir
+
+			for (folder in folderParts) {
+				var next = current?.findFile(folder)
+
+				if (next == null) {
+					if (isWriteMode(accessFlag)) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: Let's store `isWriteMode(accessFlag)` in a variable outside of the loop, and just reference it.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 11]
```diff
@@ -0,0 +1,188 @@
...
+						next = current!!.createDirectory(folder)
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]:
```suggestion
						next = current?.createDirectory(folder)
```

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt [hunk 12]
```diff
@@ -0,0 +1,188 @@
...
+				}
+
+				current = next
+			}
+
+			var file = current?.findFile(filename)
+
+			if (file == null) {
+				if (isWriteMode(accessFlag)) {
+					file = current!!.createFile("*/*", filename)
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]:
```suggestion
					file = current?.createFile("*/*", filename)
```

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/FilePicker.kt [hunk 13]
```diff
@@ -69,48 +69,49 @@ internal class FilePicker {
...
-									Log.d(TAG, "null filepath URI: $it")
+								try {
+									context.contentResolver.takePersistableUriPermission(
+										it,
+										Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION
+									)
+								} catch (e: SecurityException) {
+									Log.d(TAG, "Unable to persist URI: $it", e)
 								}
+								selectedFiles.add(it.toString())
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/FilePicker.kt:96]: Does not being able to persist the uri create an issue? Should the uri be added to the `selectedFiles` if that error occurs?

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/FilePicker.kt:96]: Yes, uri should be added to selectedFiles even if persistence fails. Users won't have the long term access but it still allows the temporary access.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt (hunk 9 above)
Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/file/SAFData.kt]: This cannot be null here, the method returns early when fragment is null. See the check above where we return the uri if `fragment == null`.

File: platform/android/java/lib/src/main/java/org/godotengine/godot/io/FilePicker.kt [hunk 14]
```diff
@@ -201,5 +197,37 @@ internal class FilePicker {
...
 			return "application/octet-stream"
 		}
+
+		private fun getUriFromDirectoryPath(context: Context, directoryPath: String): Uri? {
+			if (directoryPath.startsWith("content://")) {
+				return directoryPath.toUri()
+			}
+			if (!directoryExists(directoryPath)) {
+				return null
+			}
```
Comment (m4gr3d) [inline platform/android/java/lib/src/main/java/org/godotengine/godot/io/FilePicker.kt:207]: Shouldn't this check be first?

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/FilePicker.kt:207]: We do early return if it's a uri because this method can only handle paths. We could update `directoryExists` to handle uri as well, but there's no need. We can pass the uri directly and let SAF handle the existence check.

Comment (syntaxerror247) [reply platform/android/java/lib/src/main/java/org/godotengine/godot/io/FilePicker.kt:207]: Actually, this doesn't even needs to be a directory. I haven't tried it but documentation mentions (https://developer.android.com/reference/android/provider/DocumentsContract#EXTRA_INITIAL_URI)
> Location should specify a document URI or a tree URI with document ID. If this URI identifies a non-directory, document navigator will attempt to use the parent of the document as the initial location.

**Review by m4gr3d — APPROVED** [review]
The code looks good!

Do you think you can turn the sample gdscript code into instrumented tests the way we did for `javaclasswrapper`?

**Comment by m4gr3d** [comment]
@syntaxerror247 Once the feature is stable, we should look into updating the Android editor to make use of it (potentially for 4.7).

**Comment by syntaxerror247** [comment]
> Do you think you can turn the sample gdscript code into instrumented tests the way we did for javaclasswrapper?

Yes, I can try.
But there's one limitation: testing this properly would require interacting with the file picker UI, and we can't automate that in instrumented tests. So instead of actually opening the picker, we'd have to fake the SAF responses.

**Comment by m4gr3d** [comment]
> > Do you think you can turn the sample gdscript code into instrumented tests the way we did for javaclasswrapper?
> 
> Yes, I can try. But there's one limitation: testing this properly would require interacting with the file picker UI, and we can't automate that in instrumented tests. So instead of actually opening the picker, we'd have to fake the SAF responses.

From a google search, it seems to be possible to use espresso to interact with the SAF file picker UI.

**Comment by syntaxerror247** [comment]
> From a google search, it seems to be possible to use espresso to interact with the SAF file picker UI.

Hmm, I thought Espresso was only for app UI testing, it can’t interact with system UI. But I might be wrong since I haven't looked into it much.
I'll check it out. UI Automator's doc mention that it test can interact with system apps.

**Comment by akien-mga** [comment]
Thanks!
