### PR TITLE
Fix crash when removing child during focus exit.

### LINKED ISSUE #78578: Modifying certain Array type through Inspector will cause Editor crash
### Godot version

e74bf831

### System information

Windows 11, Godot v4.1.beta

### Issue description

There's nasty bug going on with the latest master branch build of Godot. If you have an exported variable of type PackedVector2Array, and then proceed to modify its value through the Inspector, it will crash the IDE for no reason. 

I reopened the same project on 4.0.3 stable version on Steam, and the bug did not happen and I was able to modify my PackedVector2Array freely through the Inspector.

### Steps to reproduce

- Make a new scene, call it 'main.tscn'
- Attach a script to it, call it 'main.gd'
- Create an export variable, something like this will do 
```
extends Node2D
@export var mypacked : PackedVector2Array
```
- Go to that scene, click "Add Elements" on that exported variable several times. Then try to modify some of its value to something like [1,2] [2,3] [3,3]

image

- The IDE will crash

### Minimal reproduction project

[empty.zip](https://github.com/godotengine/godot/files/11837624/empty.zip)

### LINKED ISSUE #78590: Removing child on focus exit can cause a crash in certain cases
### Godot version

v4.1.beta.custom_build [f23a12007]

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

This was discovered through inspection of https://github.com/godotengine/godot/issues/78578#issuecomment-1603236210. This is happening when focus is requested by one node that ask for the previous focused node to release focus. But during focus release it remove the new focused node from the scene tree. This means the new focused node will first exit scene tree and then be focused. This means it will not be unfocused because release focus happens during exit of the tree. 

### Steps to reproduce

1. run the MRP
2. click on one of the LineEdit
3. click on the other one 
4. See Godot Crash

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11841284/Test.zip)

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #78590 
Fixes https://github.com/godotengine/godot/issues/78578#issuecomment-1603236210 ( but I think the main issue is already fixed so I think issue i itself can be closed now)

This just check at the last moment if the control is still inside the scene tree just before setting it as focused.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @Sauermann

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -2427,10 +2427,12 @@ void Viewport::_gui_control_grab_focus(Control *p_control) {
 		return;
 	}
 	get_tree()->call_group("_viewports", "_gui_remove_focus_for_window", (Node *)get_base_window());
-	gui.key_focus = p_control;
-	emit_signal(SNAME("gui_focus_changed"), p_control);
-	p_control->notification(Control::NOTIFICATION_FOCUS_ENTER);
-	p_control->queue_redraw();
+	if (p_control->is_inside_tree()) {
```
Comment (Sauermann) [inline scene/main/viewport.cpp:2430]: As the MRP of #78590 shows, this crash can be caused by user-code. So the fix is necessary.
I suggest to make the condition even more robust by:
``` c++
if (p_control->is_inside_tree() && p_control->get_viewport() == this) {
```
Without this addition, user-code can bring the viewport into an inconsistent state, where a viewport has focus of a `Control`-node, that is not inside the viewport.

Here is a MRP, that demonstrates the necessary gdscript: [Test.zip](https://github.com/godotengine/godot/files/11851093/Test.zip)
In the MRP, follow the steps of #78590 and the label shows the path of the currently focused node in the SubViewport.

Comment (ajreckof) [reply scene/main/viewport.cpp:2430]: You are right I didn't think about multiviewport I think only doing the second check should be enough as in case the node is out of the tree the viewport is a null object and should therefore never pass the second one.

Comment (Sauermann) [reply scene/main/viewport.cpp:2430]: In a detached scene tree, `get_viewport()` still returns the (also detached) viewport.
I am not sure, if in this case the focus-change is desirable or not. I would tend to leave the `is_inside_tree` check in the code.

Comment (ajreckof) [reply scene/main/viewport.cpp:2430]: I think this might cause the same type of bug where it can't find the viewport to unfocus himself if it is detached and reattached later. In fact if it does come early as we are treating it here but happening "normaly" it is detached so we should prevent from attaching if it happened before.

Comment (ajreckof) [reply scene/main/viewport.cpp]: I understand what you mean like if the viewport is removed from the scene tree it would unfocus the node so if the viewport has already been removed from scene tree `get_viewport` still return something but it should still prevent it to keep it consistent.

**Review by Sauermann — APPROVED** [review]
I have tested the PR with the MRPs of both linked issues and it fixes the crashes for me.
The implementation looks good to me.

**Review by YuriSizov — APPROVED** [review]
On behalf of @Sauermann

**Comment by akien-mga** [comment]
Thanks!
