### PR TITLE
Improved Bullet Physics flush algorithm, Lazy collision filter reload, Shape reload regression fix.

### LINKED ISSUE #40311: Crash in Bullet when changing a CollisionShape
**Godot version:**
Master 9678a41b19e142bbc4c00f761a3a5a0cf2d4458e

**OS/device including version:**
Windows 10

**Issue description:**
Issue reproduced on master while testing the use case from #40283 (see https://github.com/godotengine/godot/issues/40283#issuecomment-657099590)

Callstack:
```
 godot.windows.tools.64.exe!abort() Line 77	C++
 	[External Code]	
 godot.windows.tools.64.exe!btCollisionWorld::updateSingleAabb(btCollisionObject * colObj) Line 158	C++
 godot.windows.tools.64.exe!btCollisionWorld::updateAabbs() Line 212	C++
 godot.windows.tools.64.exe!btCollisionWorld::performDiscreteCollisionDetection() Line 229	C++
 godot.windows.tools.64.exe!btDiscreteDynamicsWorld::internalSingleStepSimulation(float timeStep) Line 475	C++
 godot.windows.tools.64.exe!btSoftRigidDynamicsWorld::internalSingleStepSimulation(float timeStep) Line 91	C++
 godot.windows.tools.64.exe!btDiscreteDynamicsWorld::stepSimulation(float timeStep, int maxSubSteps, float fixedTimeStep) Line 435	C++
 godot.windows.tools.64.exe!SpaceBullet::step(float p_delta_time) Line 363	C++
 godot.windows.tools.64.exe!BulletPhysicsServer3D::step(float p_deltaTime) Line 1553	C++
 godot.windows.tools.64.exe!Main::iteration() Line 2178	C++
 godot.windows.tools.64.exe!OS_Windows::run() Line 627	C++
 godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 161	C++
 godot.windows.tools.64.exe!_main() Line 183	C++
 godot.windows.tools.64.exe!main(int _argc, char * * _argv) Line 195	C++
```

**Steps to reproduce:**
Start the reproduction project and wait for the collision to happen.

Repro steps from the original issue:
1. Get two rigid bodies to collide, and detect each other colliding with the _body_entered signal.
2. Upon collision, get one of them to change it's collision shape, then remove itself from the scene

**Minimal reproduction project:**
[RigidBodyBugMinimal-4.0.zip](https://github.com/godotengine/godot/files/4908202/RigidBodyBugMinimal-4.0.zip)

### LINKED ISSUE #40506: Project crashes when using CSGBox and calculating tangents
**Godot version:**
4.0.dev.custom_build. 9e34ba485

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
Two backtraces - one when running code in _physics() function and one inside _physics_process()
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f4c997ad210] (??:0)
[2] btCollisionWorld::updateSingleAabb(btCollisionObject*) (/mnt/Miecz/mojgodot/thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:156)
[3] btCollisionWorld::updateAabbs() (/mnt/Miecz/mojgodot/thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:202 (discriminator 2))
[4] btCollisionWorld::performDiscreteCollisionDetection() (/mnt/Miecz/mojgodot/thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:229)
[5] btDiscreteDynamicsWorld::internalSingleStepSimulation(float) (/mnt/Miecz/mojgodot/thirdparty/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:475)
[6] btSoftRigidDynamicsWorld::internalSingleStepSimulation(float) (/mnt/Miecz/mojgodot/thirdparty/bullet/BulletSoftBody/btSoftRigidDynamicsWorld.cpp:91)
[7] btDiscreteDynamicsWorld::stepSimulation(float, int, float) (/mnt/Miecz/mojgodot/thirdparty/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:435 (discriminator 2))
[8] SpaceBullet::step(float) (/mnt/Miecz/mojgodot/modules/bullet/space_bullet.cpp:363)
[9] BulletPhysicsServer3D::step(float) (/mnt/Miecz/mojgodot/modules/bullet/bullet_physics_server.cpp:1551 (discriminator 2))
[10] Main::iteration() (/mnt/Miecz/mojgodot/main/main.cpp:2180)
[11] OS_LinuxBSD::run() (/mnt/Miecz/mojgodot/platform/linuxbsd/os_linuxbsd.cpp:238)
[12] /usr/bin/godot4(main+0x125) [0x19d6f2b] (/mnt/Miecz/mojgodot/platform/linuxbsd/godot_linuxbsd.cpp:57)
[13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f4c9978e0b3] (??:0)
[14] /usr/bin/godot4(_start+0x2e) [0x19d6d4e] (??:?)
```
and
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f6f824c2210] (??:0)
[2] btCollisionWorld::refreshBroadphaseProxy(btCollisionObject*) (/mnt/Miecz/mojgodot/thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:110)
[3] SpaceBullet::reload_collision_filters(RigidBodyBullet*) (/mnt/Miecz/mojgodot/modules/bullet/space_bullet.cpp:532)
[4] RigidBodyBullet::on_collision_filters_change() (/mnt/Miecz/mojgodot/modules/bullet/rigid_body_bullet.cpp:400)
[5] CollisionObjectBullet::set_collision_layer(unsigned int) (/mnt/Miecz/mojgodot/modules/bullet/collision_object_bullet.h:176)
[6] BulletPhysicsServer3D::body_set_collision_layer(RID, unsigned int) (/mnt/Miecz/mojgodot/modules/bullet/bullet_physics_server.cpp:596)
[7] CSGShape3D::set_collision_layer(unsigned int) (/mnt/Miecz/mojgodot/modules/csg/csg_shape.cpp:73)
[8] MethodBind1<unsigned int>::call(Object*, Variant const**, int, Callable::CallError&) (/mnt/Miecz/mojgodot/./core/method_bind.gen.inc:775 (discriminator 12))
[9] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/mojgodot/core/object.cpp:890 (discriminator 1))
[10] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Callable::CallError&) (/mnt/Miecz/mojgodot/core/variant_call.cpp:1255 (discriminator 1))
[11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript_function.cpp:1047)
[12] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/mnt/Miecz/mojgodot/modules/gdscript/gdscript.cpp:1306)
[13] Node::_notification(int) (/mnt/Miecz/mojgodot/scene/main/node.cpp:57)
[14] Node::_notificationv(int, bool) (/mnt/Miecz/mojgodot/./scene/main/node.h:46 (discriminator 14))
[15] Node3D::_notificationv(int, bool) (/mnt/Miecz/mojgodot/./scene/3d/node_3d.h:52 (discriminator 3))
[16] VisualInstance3D::_notificationv(int, bool) (/mnt/Miecz/mojgodot/./scene/3d/visual_instance_3d.h:40 (discriminator 3))
[17] GeometryInstance3D::_notificationv(int, bool) (/mnt/Miecz/mojgodot/./scene/3d/visual_instance_3d.h:83 (discriminator 3))
[18] CSGShape3D::_notificationv(int, bool) (/mnt/Miecz/mojgodot/modules/csg/csg_shape.h:42 (discriminator 3))
[19] CSGPrimitive3D::_notificationv(int, bool) (/mnt/Miecz/mojgodot/modules/csg/csg_shape.h:169 (discriminator 3))
[20] CSGBox3D::_notificationv(int, bool) (/mnt/Miecz/mojgodot/modules/csg/csg_shape.h:239 (discriminator 3))
[21] Object::notification(int, bool) (/mnt/Miecz/mojgodot/core/object.cpp:901)
[22] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/mojgodot/scene/main/scene_tree.cpp:826)
[23] SceneTree::idle(float) (/mnt/Miecz/mojgodot/scene/main/scene_tree.cpp:455 (discriminator 2))
[24] Main::iteration() (/mnt/Miecz/mojgodot/main/main.cpp:2194)
[25] OS_LinuxBSD::run() (/mnt/Miecz/mojgodot/platform/linuxbsd/os_linuxbsd.cpp:238)
[26] /usr/bin/godot4(main+0x125) [0x19d6f2b] (/mnt/Miecz/mojgodot/platform/linuxbsd/godot_linuxbsd.cpp:57)
[27] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f6f824a30b3] (??:0)
[28] /usr/bin/godot4(_start+0x2e) [0x19d6d4e] (??:?)
```

**Steps to reproduce:**
1. Run project

**Minimal reproduction project:**
[TheWorstGodotTestProject.zip](https://github.com/godotengine/godot/files/4943575/TheWorstGodotTestProject.zip)

**Code**
```
extends CSGBox3D

# First crash
func _physics_process(delta):
	if randi() % 2 == 1:
		set_calculate_tangents(get_bool())
	if randi() % 2 == 1:
		set_use_collision(get_bool())
	if randi() % 2 == 1:
		set_collision_layer(get_int())

# Second Crash
func _process(delta) -> void:
	if randi() % 2 == 1:
		set_calculate_tangents(get_bool())
	if randi() % 2 == 1:
		set_use_collision(get_bool())
	if randi() % 2 == 1:
		set_collision_layer(get_int())
		
const RANGE : int = 100

func get_bool() -> bool:
	return bool(randi()%2)
	
func get_int() -> int:
	return randi() % RANGE - RANGE / 2
```

### LINKED ISSUE #40508: [Bullet] Gravity is applied to RigidBody even with custom_integrator turned on
**Godot version:**
3.2 custom build, issue bisected to commit e7d8464f

**OS/device including version:**
Linux Mint 20

**Issue description:**
The custom_integrator property of rigid bodies is ignored, which causes gravity to be applied when it should not.

**Steps to reproduce:**
Add a RigidBody to a scene, turn custom_integrator on/off, the RigidBody will fall regardless.
Building Godot from a commit prior to e7d8464f (or the latest stable 3.2 release) does not cause this issue.

**Minimal reproduction project:**
[CustomIntegrator.zip](https://github.com/godotengine/godot/files/4943606/CustomIntegrator.zip)
The custom_integrator property is turned on in this project, yet the box still falls due to gravity. I have to actively subtract gravity in `_integrate_forces()` to prevent the box from falling, but even then it will move downward slowly. In previous versions, the box stays perfectly still, or falls upward if I subtract gravity, as is expected.

### PR DESCRIPTION
**Pull request by AndreaCatania**
- Improved flush algorithm, so now when a RigidBody goes into sleeping mode, it's flush is not executed (as should have be).
- Added pre flush list, used by areas, so their notifications arrives to RigidBody before those get flushed.
- Make sure to correctly fetch gravity when the integrate_forces function is used
- Lazy reload body when layer and mask changes
- Shapes are reloaded just before the physics step starts.
- Improved some other parts of the code.
- Removed `std::vector` and `Vector` in favour of the recently added `LocalVector`.

Check this PR: https://github.com/godotengine/godot/pull/40186
Improves this: https://github.com/godotengine/godot/issues/40127

Fixes #40508
Fixes #40311
Fixes #40506

### CODE REVIEW

File: modules/bullet/rigid_body_bullet.h [hunk 1]
```diff
@@ -202,11 +202,11 @@ class RigidBodyBullet : public RigidCollisionObjectBullet {
...
-	Vector<CollisionData> collisions;
-	Vector<RigidBodyBullet *> collision_traces_1;
-	Vector<RigidBodyBullet *> collision_traces_2;
-	Vector<RigidBodyBullet *> *prev_collision_traces;
-	Vector<RigidBodyBullet *> *curr_collision_traces;
+	std::vector<CollisionData> collisions;
+	std::vector<RigidBodyBullet *> collision_traces_1;
+	std::vector<RigidBodyBullet *> collision_traces_2;
+	std::vector<RigidBodyBullet *> *prev_collision_traces;
+	std::vector<RigidBodyBullet *> *curr_collision_traces;
```
Comment (madmiraal) [inline modules/bullet/rigid_body_bullet.h:210]: I thought we weren't supposed to use `std::vector`.

File: modules/bullet/space_bullet.cpp [hunk 2]
```diff
@@ -41,6 +41,7 @@
 #include "rigid_body_bullet.h"
 #include "servers/physics_server_3d.h"
 #include "soft_body_bullet.h"
+#include <algorithm>
```
Comment (madmiraal) [inline modules/bullet/space_bullet.cpp:45]: Again, I thought we weren't supposed to use the Standard Template Library; except for a few specified exceptions.

File: modules/bullet/space_bullet.h [hunk 3]
```diff
@@ -36,6 +36,7 @@
 #include "godot_result_callbacks.h"
 #include "rid_bullet.h"
 #include "servers/physics_server_3d.h"
+#include <vector>
```
Comment (madmiraal) [inline modules/bullet/space_bullet.h:39]: And again.

**Review by madmiraal — CHANGES_REQUESTED** [review]
I don't think trying to control the order that the flush happens is the right approach; especially not by creating multiple queues, which significantly increases the complexity of the flush system without the flexibility of varying the number of priorities.

Also, as highlighted below, your solution appears to require the Standard Template Library's `std::vector`, which I thought we shouldn't be using.

**Comment by AndreaCatania** [comment]
The old solution was really bad because all the rigid bodies are processed, even the one that are not needed. Instead, the queue allows to only process the `body`s that need to. Exactly like the Godot nodes are processed.

The solution of single queue, has the big disadvantage that before its use it must be sorted. This is acceptable when each element can have N priorities. For this use case, we have just 2 priorities (and this is unlikely to change), so use two separate queues is much more convenient.

Regarding the `std::vector`: Back when I've implemented it, the `Vector` was not using COW and it was perfect for this use case. However, later COW got implemented and that added a significant overhead for this use case.
Since avoid the `Vector` copy on write makes the code more complex, and since as far as I know is fine use `std::vector` into modules, I preferred use the std version.

**Comment by AndreaCatania** [comment]
Update: Rebased and fixed few bugs.

File: modules/bullet/space_bullet.h (hunk 3 above)
Comment (reduz) [reply modules/bullet/space_bullet.h:39]: Master branch has LocalVector, which is more similar to std::vector, you could backport to to 3.2 if you want.

File: modules/bullet/rigid_body_bullet.h (hunk 1 above)
Comment (AndreaCatania) [reply modules/bullet/rigid_body_bullet.h]: Removed `std::vector` in favour of the recently added `LocalVector`.

File: modules/bullet/space_bullet.cpp (hunk 2 above)
Comment (AndreaCatania) [reply modules/bullet/space_bullet.cpp]: Removed `std::vector` in favour of the recently added `LocalVector`.

File: modules/bullet/space_bullet.h (hunk 3 above)
Comment (AndreaCatania) [reply modules/bullet/space_bullet.h]: Removed `std::vector` in favour of the recently added `LocalVector`.

**Comment by AndreaCatania** [comment]
Removed `std::vector` and `Vector` in favour of the recently added `LocalVector`.

File: modules/bullet/collision_object_bullet.h [hunk 4]
```diff
@@ -35,6 +35,7 @@
 #include "core/math/vector3.h"
 #include "core/object.h"
 #include "core/vset.h"
+#include "core/local_vector.h"
```
Comment (akien-mga) [inline modules/bullet/collision_object_bullet.h:38]: Should be further up (alphabetical ordering).

**Comment by AndreaCatania** [comment]
Force push: Removed invalid comment, It was no more valid since `std::vector` is gone.

File: modules/bullet/area_bullet.cpp [hunk 5]
```diff
@@ -187,10 +183,11 @@ void AreaBullet::set_space(SpaceBullet *p_space) {
 	if (space) {
 		space->register_collision_object(this);
 		reload_body();
+		scratch();
 	}
 }
 
-void AreaBullet::on_collision_filters_change() {
+void AreaBullet::do_reload_collision_fm() {
 	if (space) {
```
Comment (madmiraal) [inline modules/bullet/area_bullet.cpp:191]: Nitpicking, but all these `*collision_fm` variables and functions would be better named `*collision_filters`.

File: modules/bullet/area_bullet.h [hunk 6]
```diff
@@ -152,9 +150,9 @@ class AreaBullet : public RigidCollisionObjectBullet {
 	// Dispatch the callbacks and removes from overlapping list
 	void remove_overlap(CollisionObjectBullet *p_object, bool p_notify);
 
-	virtual void on_collision_filters_change();
-	virtual void on_collision_checker_start() {}
-	virtual void on_collision_checker_end() { isTransformChanged = false; }
+	virtual void do_reload_collision_fm() override;
+	virtual void on_collision_checker_start() override {}
```
Comment (madmiraal) [inline modules/bullet/area_bullet.h:154]: As above: `do_reload_collision_filters()`.

File: modules/bullet/collision_object_bullet.cpp [hunk 7]
```diff
@@ -165,11 +165,20 @@ bool CollisionObjectBullet::has_collision_exception(const CollisionObjectBullet
...
+
+void CollisionObjectBullet::dispatch_callbacks() {}
+
+void CollisionObjectBullet::pre_process() {
 	if (need_body_reload) {
 		do_reload_body();
-		need_body_reload = false;
+	} else if (need_collision_fm_reload) {
+		do_reload_collision_fm();
 	}
```
Comment (madmiraal) [inline modules/bullet/collision_object_bullet.cpp:179]: As above: `needs_collision_filters_reload` (and I'd put an "s" after "need") and `do_reload_collision_filters()`.

File: modules/bullet/collision_object_bullet.h [hunk 8]
```diff
@@ -127,15 +128,18 @@ class CollisionObjectBullet : public RIDBullet {
...
 	/// New area is added when overlap with new area (AreaBullet::addOverlap), then is removed when it exit (CollisionObjectBullet::onExitArea)
 	/// This array is used mainly to know which area hold the pointer of this object
-	Vector<AreaBullet *> areasOverlapped;
+	LocalVector<AreaBullet *> areasOverlapped;
 	bool isTransformChanged = false;
 
 public:
 	bool is_in_world = false;
+	bool into_flush = false;
+	bool into_process = false;
```
Comment (madmiraal) [inline modules/bullet/collision_object_bullet.h:143]: `in_process` doesn't appear to be used. It can be removed.

`into_flush` appears to be used for marking whether the `CollisionObject` has been added to the either the queue to be flushed or the pre-flush queue. Is this intended, or should there be separate markers for each queue?

Finally, nitpicking, I think `into_flush` would be better named `is_in_queue`. And if there should be two separate markers then `is_in_pre_flush_queue` and `is_in_flush_queue`.

File: modules/bullet/collision_object_bullet.h [hunk 9]
```diff
@@ -171,20 +175,20 @@ class CollisionObjectBullet : public RIDBullet {
 	_FORCE_INLINE_ void set_collision_layer(uint32_t p_layer) {
 		if (collisionLayer != p_layer) {
 			collisionLayer = p_layer;
-			on_collision_filters_change();
+			need_collision_fm_reload = true;
 		}
```
Comment (madmiraal) [inline modules/bullet/collision_object_bullet.h:179]: As above: `needs_collision_filters_reload`.

File: modules/bullet/collision_object_bullet.h [hunk 10]
```diff
@@ -127,15 +128,18 @@ class CollisionObjectBullet : public RIDBullet {
 	VSet<RID> exceptions;
 
 	bool need_body_reload = true;
+	bool need_collision_fm_reload = true;
```
Comment (madmiraal) [inline modules/bullet/collision_object_bullet.h:132]: More nitpicking, but I think "need" needs an "s": `needs_body_reload` and `needs_collision_filters_reload`.

File: modules/bullet/rigid_body_bullet.cpp [hunk 11]
```diff
@@ -392,7 +395,7 @@ void RigidBodyBullet::scratch_space_override_modificator() {
 	isScratchedSpaceOverrideModificator = true;
 }
 
-void RigidBodyBullet::on_collision_filters_change() {
+void RigidBodyBullet::do_reload_collision_fm() {
 	if (space) {
```
Comment (madmiraal) [inline modules/bullet/rigid_body_bullet.cpp:399]: As above, `do_reload_collision_filters()`.

File: modules/bullet/rigid_body_bullet.h [hunk 12]
```diff
@@ -235,21 +236,20 @@ class RigidBodyBullet : public RigidCollisionObjectBullet {
...
 	void scratch_space_override_modificator();
 
-	virtual void on_collision_filters_change();
-	virtual void on_collision_checker_start();
-	virtual void on_collision_checker_end();
-
-	void set_max_collisions_detection(int p_maxCollisionsDetection) {
-		ERR_FAIL_COND(0 > p_maxCollisionsDetection);
+	virtual void do_reload_collision_fm() override;
+	virtual void on_collision_checker_start() override;
```
Comment (madmiraal) [inline modules/bullet/rigid_body_bullet.h:249]: As above, `do_reload_collision_filters()`

File: modules/bullet/space_bullet.cpp [hunk 13]
```diff
@@ -348,16 +348,46 @@ SpaceBullet::~SpaceBullet() {
...
+	}
+}
+
+void SpaceBullet::add_to_flush_queue(CollisionObjectBullet *p_co) {
+	if (p_co->into_flush == false) {
+		p_co->into_flush = true;
+		queue_flush.push_back(p_co);
+	}
+}
+
```
Comment (madmiraal) [inline modules/bullet/space_bullet.cpp:364]: As mentioned above, should `into_flush` be used to indicated whether or not an item is already in either queue, or should there be separate indicators?

**Review by madmiraal — COMMENTED** [review]
I haven't tested whether or not this PR solves the issues indicated, but aside from the few minor points below I think the changes look good. :+1:

File: modules/bullet/area_bullet.cpp (hunk 5 above)
Comment (AndreaCatania) [reply modules/bullet/area_bullet.cpp:191]: I agree, changed

File: modules/bullet/area_bullet.h (hunk 6 above)
Comment (AndreaCatania) [reply modules/bullet/area_bullet.h:154]: changed

File: modules/bullet/collision_object_bullet.cpp (hunk 7 above)
Comment (AndreaCatania) [reply modules/bullet/collision_object_bullet.cpp:179]: Changed

File: modules/bullet/collision_object_bullet.h (hunk 9 above)
Comment (AndreaCatania) [reply modules/bullet/collision_object_bullet.h:179]: Changed

File: modules/bullet/collision_object_bullet.h (hunk 8 above)
Comment (AndreaCatania) [reply modules/bullet/collision_object_bullet.h:143]: Woups, `into_process` should not be there, and `into_flush` got renamed to `is_in_flush_queue`. Yes, is intended that we have only `is_in_flush_queue` because a `CollisionObject` can be an `Area` or a `RigidBody` - so can be in one or the other queue but never in both.

File: modules/bullet/rigid_body_bullet.cpp (hunk 11 above)
Comment (AndreaCatania) [reply modules/bullet/rigid_body_bullet.cpp:399]: Changed

File: modules/bullet/rigid_body_bullet.h (hunk 12 above)
Comment (AndreaCatania) [reply modules/bullet/rigid_body_bullet.h:249]: Changed

File: modules/bullet/space_bullet.cpp (hunk 13 above)
Comment (AndreaCatania) [reply modules/bullet/space_bullet.cpp:364]: More details above, but yes, same indicator is enough.

File: modules/bullet/collision_object_bullet.h (hunk 10 above)
Comment (AndreaCatania) [reply modules/bullet/collision_object_bullet.h:132]: Changed

**Comment by AndreaCatania** [comment]
All fixed

**Review by madmiraal — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Two apparent regressions from this PR: #40840 #40848.

File: modules/bullet/space_bullet.h [hunk 14]
```diff
@@ -110,17 +110,23 @@ class SpaceBullet : public RIDBullet {
...
-	Vector<AreaBullet *> areas;
+	LocalVector<CollisionObjectBullet *> queue_pre_flush;
+	LocalVector<CollisionObjectBullet *> queue_flush;
+	LocalVector<CollisionObjectBullet *> collision_objects;
+	LocalVector<AreaBullet *> areas;
 
-	Vector<Vector3> contactDebug;
-	int contactDebugCount = 0;
+	LocalVector<Vector3> contactDebug;
+	uint32_t contactDebugCount = 0;
```
Comment (aaronfranke) [inline modules/bullet/space_bullet.h:119]: Shouldn't these be `snake_case`?

Comment (AndreaCatania) [reply modules/bullet/space_bullet.h:119]: Yep, it should be. Also I would check if make sense remove it (now that we have `LocalVector`)
