### PR TITLE
Fix clipboard history not updating on subsequent copies in Wayland

### LINKED ISSUE #116522: Clipboard history only logs the first copy attempt from Godot in Wayland
### Tested versions

- Reproducible in 4.6 and 833889aec024b792b1c5ce5089eaebc5eb45692f

### System information

Godot v4.6.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 09 Feb 2026 17:16:33 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - KDE Plasma Version: 6.5.5, KDE Frameworks Version: 6.23.0, Qt Version: 6.10.2, Graphics Platform: Wayland

### Issue description

When using native Wayland with KDE (Klipper as clipboard manager), copying text from the editor or in-game works for the first attempt; however, subsequent copies are not logged in the clipboard history until you copy text from another application and then copy text in Godot again.

Example scenario :
1. Copy text "A" inside the Godot editor
2. Check the clipboard history, initially showing "A" in the list
3. Copy text "B" inside the Godot editor
4. Check the clipboard history, still shows "A" in the list
5. Copy text "C" outside Godot
6. Check the clipboard history, now shows "C", "A" in the list (ordered chronologically)
7. Copy text "D" inside the Godot editor
8. Check the clipboard history, now shows "D", "C", "A" in the list
9. Copy text "E" inside the Godot editor
10. Check the clipboard history, shows "D", "C", "A" in the list

Despite not being logged, pasting still works properly (according to the example scenario, it will paste "E")

Using X11 (set `run/platforms/linuxbsd/prefer_wayland` to false) does not seem to have this issue.

Not sure if this is reproducible in other clipboard managers or DEs

### Steps to reproduce

1. Launch the editor with native Wayland
2. Copy any text in the editor
3. Open the clipboard history and observe that the copied text is logged
4. Copy different text in the editor again
5. Open the clipboard history again, and observe that the second copy is not logged.

### Minimal reproduction project (MRP)

Not needed

### PR DESCRIPTION
**Pull request by gongpha**
Fixes #116522 

When setting the clipboard, the data source was reused after the first copy and only the in-memory buffer was updated, so the compositor was never notified of subsequent clipboard changes.

The change makes it destroy and recreate the `wl_data_source` when setting the clipboard selection, so that `wl_data_device_set_selection` is called each time. Clipboard managers (e.g. KDE Klipper) detect new entries by receiving a new selection event from the compositor, which only fires when set_selection is called with a new data source.

This PR also applies the same fix to the primary clipboard.

### CODE REVIEW

**Review by YeldhamDev — APPROVED** [review]
Fixes the issue, but someone needs to review the Wayland code itself.

Really hope this get merged though, such an annoying issue.

**Review by deralmas — APPROVED** [review]
Code looks good!

Could not see any obvious regressions on my usual test harness (KDE 6.5.4, GNOME 49.2.2, COSMIC 1.0.1), and my laptop (sway 1.11).

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 1]
```diff
@@ -5334,16 +5337,19 @@ void WaylandThread::primary_set_text(const String &p_text) {
...
-		// TODO: Implement a good way of getting the latest serial from the user.
-		zwp_primary_selection_device_v1_set_selection(ss->wp_primary_selection_device, ss->wp_primary_selection_source, MAX(ss->pointer_data.button_serial, ss->last_key_pressed_serial));
+	if (ss->wp_primary_selection_source != nullptr) {
+		zwp_primary_selection_source_v1_destroy(ss->wp_primary_selection_source);
+		ss->wp_primary_selection_source = nullptr;
 	}
 
+	ss->wp_primary_selection_source = zwp_primary_selection_device_manager_v1_create_source(registry.wp_primary_selection_device_manager);
+	zwp_primary_selection_source_v1_add_listener(ss->wp_primary_selection_source, &wp_primary_selection_source_listener, ss);
+	zwp_primary_selection_source_v1_offer(ss->wp_primary_selection_source, "text/plain;charset=utf-8");
```
Comment (Rindbee) [inline platform/linuxbsd/wayland/wayland_thread.cpp:5347]: The `_wp_primary_selection_source_on_send()` function lacks handling for this MIME type.

https://github.com/godotengine/godot/blob/60fff00a660a2aeb03f88c07fb7baed353bcb72f/platform/linuxbsd/wayland/wayland_thread.cpp#L2944-L2946

Perhaps it should be added there.

Comment (akien-mga) [reply platform/linuxbsd/wayland/wayland_thread.cpp:5347]: Oops I wanted to wait for this review comment to be resolved but I forgot to remove the PR from my upcoming batch.

CC @deralmas

Comment (deralmas) [reply platform/linuxbsd/wayland/wayland_thread.cpp:5347]: Oh that's tricky! Took me a minute to figure out.

Yea, that's an usual case of the primary selection code being out of sync with the main one. You can simply copy paste the logic from the regular clipboard handler:

https://github.com/godotengine/godot/blob/60fff00a660a2aeb03f88c07fb7baed353bcb72f/platform/linuxbsd/wayland/wayland_thread.cpp#L2610-L2620

We could perhaps wrap this part in a method but I'm somewhat skeptic that it would stop cases like these in the future.

Comment (deralmas) [reply platform/linuxbsd/wayland/wayland_thread.cpp:5347]: (Yea right this got merged, making a PR rn xD)

Comment (Rindbee) [reply platform/linuxbsd/wayland/wayland_thread.cpp:5347]: https://github.com/godotengine/godot/blob/e3dc665263bba9d76977ee6aa4d0c2a5758c6f4c/platform/linuxbsd/wayland/wayland_thread.cpp#L5586

`primary_get_mime()` also returned incorrect data. It should be `ss->primary_data`.

Comment (deralmas) [reply platform/linuxbsd/wayland/wayland_thread.cpp:5347]: Done! Please check #117873 out.

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.3.
