### PR TITLE
Color Pickers Respect Default Editor Settings

### LINKED ISSUE #57154: Sun/Environment Preview and Label toolbar color pickers doesn't respect color picker shape and mode editor settings
### Godot version

v4.0.dev.custom_build [e09881de9]

### System information

Windows 10, Vulkan

### Issue description

The color picker in the sun preview menu doesn't respect the Default Color Picker Mode and Default Color Picker Shape editor settings. This applies to all 3 color pickers in this menu (Sun, Sky, and Ground Color).

image

image

EDIT: This also applies to the Label toolbar:
image

### Steps to reproduce

* Change the Default Color Picker Mode and Default Color Picker Shape editor settings to something other than the default
* Open a color picker in the 3D Sun/Environment Preview menu

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Guh-Feng**
Updated editor_node with set_color_picker function called by color pickers throughout Godot to respect the editor's settings.
Another attempt to fix #57154.
Implemented changes noted in #57402 and rewrote certain color pickers to match the function call and keep everything consistent.

### CODE REVIEW

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -1854,23 +1854,13 @@ void ScriptTextEditor::_enable_code_editor() {
 
 	add_child(color_panel);
 
-	color_picker = memnew(ColorPicker);
-	color_picker->set_deferred_mode(true);
+	color_picker = memnew(ColorPickerButton);
+	color_picker->get_picker()->set_deferred_mode(true);
 	color_picker->connect("color_changed", callable_mp(this, &ScriptTextEditor::_color_changed));
```
Comment (KoBeWi) [inline editor/plugins/script_text_editor.cpp:1859]: This picker appears when you right-click a Color in the script editor.
godot windows tools 64_EzFengNOeV
It must be ColorPicker to appear correctly. Not sure why you changed the type if the method expects ColorPicker.

**Comment by KoBeWi** [comment]
Looks good overall, but you shouldn't change ColorPicker nodes to ColorPickerButtons as they won't work correctly.

Instead you can manually setup the picker, e.g. here
https://github.com/godotengine/godot/blob/03765b298554dcbad40f45372d6c59b358d4a845/editor/plugins/script_text_editor.cpp#L1177-L1179
here
https://github.com/godotengine/godot/blob/03765b298554dcbad40f45372d6c59b358d4a845/scene/gui/gradient_edit.cpp#L75-L80
etc.
(you can also connect to the custom popups there)

File: scene/gui/gradient_edit.h [hunk 2]
```diff
@@ -34,6 +34,7 @@
 #include "scene/gui/color_picker.h"
 #include "scene/gui/popup.h"
 #include "scene/resources/gradient.h"
+#include "editor/editor_node.h"
```
Comment (KoBeWi) [inline scene/gui/gradient_edit.h:37]: Includes should be in cpp file when possible (this file has some wrong includes that shouldn't be there; let's not add more).

**Comment by Guh-Feng** [comment]
Made changes from the recommendations. Things to note that I forgot to mention initially, I looked into fire-forge's suggestion for making everything use the same color picker. It seems just a little out of the scope of what I can do but I might consider working on it in the future. I also had a different perspective in consolidating the script used to sync the color picker settings into a single method. It might be a bandage solution but it could be an easier way to achieve the same goal. I'd like some feedback on the idea.

File: editor/property_editor.cpp [hunk 3]
```diff
@@ -828,19 +828,9 @@ bool CustomPropertyEditor::edit(Object *p_owner, const String &p_name, Variant::
...
-					color_picker->set_hsv_mode(true);
-				} else if (default_color_mode == 2) {
-					color_picker->set_raw_mode(true);
-				}
-
-				int picker_shape = EDITOR_GET("interface/inspector/default_color_picker_shape");
-				color_picker->set_picker_shape((ColorPicker::PickerShapeType)picker_shape);
 			}
 
+			color_picker->connect("show", callable_mp(EditorNode::get_singleton(), &EditorNode::setup_color_picker), varray(color_picker));
```
Comment (KoBeWi) [inline editor/property_editor.cpp:833]: This should be higher up, in the initialization code.
Not sure when this one appears though.

Comment (Guh-Feng) [reply editor/property_editor.cpp]: I moved it up. I think this one appears in the settings, in the themes tab.

File: scene/gui/gradient_edit.h (hunk 2 above)
Comment (Guh-Feng) [reply scene/gui/gradient_edit.h]: I moved the include to the cpp file.

**Review by KoBeWi — APPROVED** [review]
Looks good now. You need to squash the commits.

**Comment by KoBeWi** [comment]
Ah now I noticed that GradientEdit isn't editor class, so it can't include editor-related code. You need to add a public method that returns the popup and then setup it in gradient editor plugin.

Also style checks failed, so you need to run `clang-format`.

**Comment by akien-mga** [comment]
Needs a rebase/rework after #62075.

File: editor/plugins/gradient_editor_plugin.cpp [hunk 4]
```diff
@@ -85,6 +85,7 @@ void GradientEditor::reverse_gradient() {
 }
 
 GradientEditor::GradientEditor() {
+	GradientEdit::get_popup()->connect("about_to_popup", callable_mp(EditorNode::get_singleton(), &EditorNode::setup_color_picker), varray(GradientEdit::get_picker()));
```
Comment (KoBeWi) [inline editor/plugins/gradient_editor_plugin.cpp:88]:
```suggestion
	GradientEdit::get_popup()->connect("about_to_popup", callable_mp(EditorNode::get_singleton(), &EditorNode::setup_color_picker), varray(GradientEdit::get_picker()));
```
Not necessary.

**Comment by KoBeWi** [comment]
The rebase should be easy, just initialization code has changed from
https://github.com/godotengine/godot/blob/31745a8b15443a28b8d8c90d408ebb47913342a1/editor/editor_properties.cpp#L3012-L3020
to
https://github.com/godotengine/godot/blob/ca18a02e00f7009d084c55b7e9de17df634f3d47/editor/editor_properties.cpp#L3012-L3015

**Comment by Guh-Feng** [comment]
> The rebase should be easy, just initialization code has changed from...

Do I add back the _picker_created function with these suggested changes?

**Comment by Guh-Feng** [comment]
Sorry that it got a little messy, but I cleaned everything up and I think all the changes appropriately accommodate the rebase.

File: editor/editor_node.cpp [hunk 5]
```diff
@@ -3588,6 +3588,13 @@ void EditorNode::set_current_scene(int p_idx) {
 	call_deferred(SNAME("_set_main_scene_state"), state, get_edited_scene()); // Do after everything else is done setting up.
 }
 
+void EditorNode::setup_color_picker(ColorPicker *picker) {
+	int default_color_mode = EDITOR_GET("interface/inspector/default_color_picker_mode");
+	int picker_shape = EDITOR_GET("interface/inspector/default_color_picker_shape");
+picker->set_color_mode((ColorPicker::ColorModeType)default_color_mode);
+	picker->set_picker_shape((ColorPicker::PickerShapeType)picker_shape);
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3595]:
```suggestion
	int default_color_mode = EDITOR_GET("interface/inspector/default_color_picker_mode");
	int picker_shape = EDITOR_GET("interface/inspector/default_color_picker_shape");
	picker->set_color_mode((ColorPicker::ColorModeType)default_color_mode);
	picker->set_picker_shape((ColorPicker::PickerShapeType)picker_shape);
```

Comment (Guh-Feng) [reply editor/editor_node.cpp:3595]: For some reason clang failed that original line, so I tried the suggested change just to see what would happen.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
