### PR TITLE
Fix InputEvent actions.

### LINKED ISSUE #8914: InputEvent's is_action{,_pressed,_released} don't work
**Godot version: 3.0 master**

**Issue description:**
`Input.is_action_pressed("action")` is not working :)

### PR DESCRIPTION
**Pull request by 27thLiz**
The `InputEvent::is_action(pressed|released)` methods weren't implemented yet.
Also fixed a typo in `InputDefault` that prevented `Input.is_action(pressed|released)` from working.

Fixes #8914

### CODE REVIEW

**Review by bojidar-bg — APPROVED** [review]
LGTM

File: core/os/input_event.cpp [hunk 1]
```diff
@@ -62,10 +62,16 @@ bool InputEvent::is_action(const StringName &p_action) const {
...
-	return false; // InputMap::get_singleton()->event_is_action(Ref<InputEvent>(this),p_action);
+	if (is_action(p_action)) {
+		return is_pressed();
+	}
+	return false;
 }
 bool InputEvent::is_action_released(const StringName &p_action) const {
 
+	if (is_action(p_action)) {
+		return !is_pressed();
```
Comment (nunodonato) [inline core/os/input_event.cpp]: Sorry if I'm being clueless on this matter but.... Why is !is_pressed() used for action_released? 
Shouldn't release be when pressed was true and then pressed becomes false? Otherwise as long as I'm not pressing the key, action_released() will always return true... which seems wrong

Comment (Hinsbart) [inline core/os/input_event.cpp]: No, you're calling this on individual `InputEvents`. That would be the case if it was implemented this way for `Input.is_action_released(action)`, yes.
But since this is for events, there's just no way `is_action_released` will return true if the event is something other than specified in the action.

Comment (bojidar-bg) [inline core/os/input_event.cpp]: Well, no, there is only one `pressed=false` event when the key is released. So, this is going to catch just that one

File: core/os/input_event.cpp [hunk 2]
```diff
@@ -62,10 +62,16 @@ bool InputEvent::is_action(const StringName &p_action) const {
 
 bool InputEvent::is_action_pressed(const StringName &p_action) const {
 
-	return false; // InputMap::get_singleton()->event_is_action(Ref<InputEvent>(this),p_action);
+	if (is_action(p_action)) {
+		return is_pressed();
```
Comment (bojidar-bg) [inline core/os/input_event.cpp]: Actually, just thought about it, I guess you might want to add `&& !is_echo()` here, but I'm not completely sure about that.

Comment (Hinsbart) [inline core/os/input_event.cpp]: Mhh, I'll check how 2.1 handled this.

File: core/os/input_event.cpp (hunk 1 above)
Comment (nunodonato) [inline core/os/input_event.cpp]: oh ok, thanks for the explanation :)

File: core/os/input_event.cpp (hunk 2 above)
Comment (Hinsbart) [inline core/os/input_event.cpp]: Yeah, definitely should be ignoring echo events. ^^
