### PR TITLE
[Editor] Fix `AnimationTrackEditor::timeline_changed` signal

### LINKED ISSUE #95479: AnimationPlayer timeline error
### Tested versions

Reproducible in 4.3 after commit [29a0e51]

### System information

Godot v4.3.rc.mono (f7f202345) - Ubuntu 22.04.4 LTS 22.04 - Wayland - Vulkan (Forward+) - integrated AMD Unknown (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

Trying to do anything with the animation players timeline since #95400 results in  

```
core/object/object.cpp:1200 - Error calling from signal 'timeline_changed' to callable: 'AnimationPlayerEditor::AnimationPlayerEditor::_animation_key_editor_seek': Method expected 3 arguments, but called with 4.
```

### Steps to reproduce

Create a AnimationPlayer node, an animation and click anywhere in the timeline.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Signal was declared with two arguments, emitted with both two and three

The signal emitted by `AnimationTimelineEdit` has two arguments and left as is, as is the signal from `AnimationTrackEdit` which is connected via a helper method in `AnimationTrackEditor`, unsure what the intention might have been there but that signal is never emitted by `AnimationTrackEdit`, but leaving that for a future cleanup and assessment

Confirmed properly that this fixes the issue, should have confirmed more properly in last attempted fix

* Fixes: https://github.com/godotengine/godot/issues/95479

### CODE REVIEW

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -7101,7 +7101,7 @@ void AnimationTrackEditor::_bind_methods() {
 
 	ClassDB::bind_method(D_METHOD("_bezier_track_set_key_handle_mode", "animation", "track_idx", "key_idx", "key_handle_mode", "key_handle_set_mode"), &AnimationTrackEditor::_bezier_track_set_key_handle_mode, DEFVAL(Animation::HANDLE_SET_MODE_NONE));
 
-	ADD_SIGNAL(MethodInfo("timeline_changed", PropertyInfo(Variant::FLOAT, "position"), PropertyInfo(Variant::BOOL, "timeline_only")));
+	ADD_SIGNAL(MethodInfo("timeline_changed", PropertyInfo(Variant::FLOAT, "position"), PropertyInfo(Variant::BOOL, "timeline_only"), PropertyInfo(Variant::BOOL, "update_position_only")));
```
Comment (TokageItLab) [inline editor/animation_track_editor.cpp:7104]: No additional arguments should really be needed.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
I think the two signals should have different names to avoid confusion, and after then fix the incorrect bindings.

File: editor/animation_track_editor.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/animation_track_editor.cpp:7104]: What do you mean? The signal is emitted with that, half the time

**Comment by AThousandShips** [comment]
The signal for `AnimationTimelineEdit` and `AnimationTrackEdit` you mean?

**Review by TokageItLab — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
