### PR TITLE
Fix typed array export

### LINKED ISSUE #62916: Can't assign nodes to exported array
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

Godot 4.0 alpha 11

### System information

Solus OS and Windows

### Issue description

Can't assign nodes to an exported array of node pointers

https://user-images.githubusercontent.com/61121689/178321358-fe05eec9-17ab-4d94-ac87-f87b1e059b97.mp4

### Steps to reproduce

1) Export an array of node pointers (`@export var node_pointer_array: Array[Node2D]`)
2) Try to assign an element to the array on the editor
3) Element will not be assigned

Or: check out the minimal reproduction project below

### Minimal reproduction project

[export array of node pointers.zip](https://github.com/godotengine/godot/files/9086249/export.array.of.node.pointers.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
*Borrowed* from #67454
Fixes #62916

The issue has multiple duplicates, so I think it's better to have it fixed sooner than later. I rebased the PR and applied my comments. I also removed references to `_editor_prop_ptr_indices`, because it doesn't seem to be used anywhere (leftover from some old code?).

The code overall needs checking probably, I mostly copied the PR and made it work (it just needed a fix in array assigning).

### CODE REVIEW

**Comment by YuriSizov** [comment]
> The issue has multiple duplicates, so I think it's better to have it fixed sooner than later.

Yes, but for all intents and purposes, this is a missing feature, not a bug. So it won't be too bad if we address this in 4.1.

> The code overall needs checking probably, I mostly copied the PR and made it work (it just needed a fix in array assigning).

Reduz gave it a cursory look before, and said

> that looks pretty good, but I think I would fix this after 4.0, at this point I think its too risky to touch PackedScene
> any issue and you can get corrupted files

**Comment by KoBeWi** [comment]
I wouldn't call it a missing feature. We do support node export and array export, they are just broken when used together.
But yeah, the changes seem a bit risky.

**Comment by GuilhermeGSousa** [comment]
Thanks for doing this, I didn't have time to work on my PR but I'll be testing you branch today!

File: scene/resources/packed_scene.cpp [hunk 1]
```diff
@@ -238,16 +238,38 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
-						if (Engine::get_singleton()->is_editor_hint()) {
-							// If editor, just set the metadata and be it
-							node->set(META_POINTER_PROPERTY_BASE + String(snames[name_idx]), props[nprops[j].value]);
+
+						if (prop_variant.get_type() == Variant::ARRAY) {
+							if (Engine::get_singleton()->is_editor_hint()) {
+								// If editor, just set the metadata and be it
+								node->set(prop_name, prop_variant);
+								continue;
+							}
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:251]: Why does it need to be special cased here? The only difference seems to be not using the `META_POINTER_PROPERTY_BASE` prefix, does it break Node arrays?

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -416,7 +438,21 @@ Node *SceneState::instantiate(GenEditState p_edit_state) const {
...
+		const String string_property = dnp.property;
+		if (string_property.contains("/indices/")) {
+			const Vector<String> properties = string_property.split("/");
+			Array array = dnp.base->get(properties[0]);
+
+			if (array.size() >= properties[2].to_int()) {
+				array.push_back(other);
+			} else {
+				array.set(properties[2].to_int(), other);
+			}
```
Comment (akien-mga) [inline scene/resources/packed_scene.cpp:450]: Is it possible for a non-Array property path to include `/indices/` too, and possibly trigger this logic in an unexpected way and crash?

Or can an Array property include `/` in the first place, leading to the `"/indices/`" + itos(k)` suffix being at different indices when splitting by `/`?

**Review by akien-mga — COMMENTED** [review]
Just left some comments for things which may warrant more eyes on them. I didn't check the existing code to see if what I point out are valid potential problems, I'm just trying to make sure we don't cut corners as PackedScene is very sensitive.

**Comment by akien-mga** [comment]
Given the current timetable and the risks from this PR, let's keep it for 4.1 and consider for a 4.0.x cherry-pick once merged and well tested.

In the meantime, it would be good to add a note in the relevant documentation to point to the missing feature.

**Comment by reduz** [comment]
I would appreciate the code is commented a bit more because given its hacky, its hard to understand exactly what is going on. Additionally there are some unanswered comments in the review.

**Comment by YuriSizov** [comment]
@KoBeWi Bump :)

File: scene/resources/packed_scene.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/resources/packed_scene.cpp:251]: This will assign the raw array of NodePaths. `META_POINTER_PROPERTY_BASE` doesn't seem to work here. The condition can't be moved elsewhere and removing it crashes, so it's likely the only way.

File: scene/resources/packed_scene.cpp (hunk 2 above)
Comment (KoBeWi) [reply scene/resources/packed_scene.cpp:450]: > Is it possible for a non-Array property path to include /indices/ too, and possibly trigger this logic in an unexpected way and crash?

Yes and no. This code only runs for "deferred NodePath properties", i.e. properties stored as NodePath that are assigned a node after the scene is complete. This limits severely what properties are affected by this code. Users can't use `/` in their properties without using `_get_property_list()`, so it's extremely unlikely that this logic is triggered when it shouldn't. And even if it does, assigning non-Array Variant will result in empty array, I think. So it shouldn't crash.

> Or can an Array property include / in the first place, leading to the "/indices/" + itos(k)suffix being at different indices when splitting by/`?

The `/indicies/` properties are created further above, near your first comment. Extra `/` are only possible if someone uses it wrongly.

**Comment by KoBeWi** [comment]
> I would appreciate the code is commented a bit more because given its hacky, its hard to understand exactly what is going on.

I checked the code in detail and Node properties were already hacky. This PR just extends the hack to support arrays.

The changes are pretty safe, as they only affect the "deferred NodePath" properties. I rebased/fixed the PR and added some comments.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by MaxIsJoe** [comment]
Does this also fix it for C#?

**Comment by romifauzi** [comment]
Tested 4.1 Dev snapshot, upon assigning sprite2d node onto an Array of type Sprite2D, got this error:

```
 Attempted to set a variable of type 'NodePath' into a TypedArray of type 'Object'.
  core/variant/array.cpp:413 - Condition "!_p->typed.validate(value, "set")" is true.
```

**Comment by Zireael07** [comment]
IIRC NodePath is a separate issue

**Comment by romifauzi** [comment]
Okay, I was under the assumption this PR fixed issue with dragging nodes into an exported typed array variable @Zireael07. So what does it fixed actually?

**Comment by KoBeWi** [comment]
This IS what the PR fixed, but somehow it's broken again on master.

**Comment by KoBeWi** [comment]
I opened #76378
It should be included when cherry-picking, because it fixes another issue.

**Comment by YuriSizov** [comment]
Skipping this from being cherry-picked for now, as there seem to be problems uncovered by this PR. Once those are addressed, we can cherry-pick in a 4.0.x release. For now, this should be available for testing in 4.1 dev snapshots, if you want to provide feedback and help catch all the bugs.

**Comment by KoBeWi** [comment]
The uncovered bugs are corner-case, while this PR fixes a very requested feature. Also the only so far discovered regression is fixed by #76378
Maaybe we can merge it for rc and revert if it causes too many problems? (which i doubt)

**Comment by YuriSizov** [comment]
We would prefer to test the changes with 4.1 builds before picking it for a patch release that doesn't get much testing before publishing.

**Comment by thornySoap** [comment]
It seems like it's still not working on (at least my) Android export. If I `OS.alert()` the same Array on desktop debug and Android export, on desktop I get an Array with my Nodes, on Android just an empty one.

**Comment by KoBeWi** [comment]
@thornySoap Open a new issue, with a minimal reproduction project.
This isn't something that would have platform-specific issues 🤔

**Comment by YuriSizov** [comment]
Regarding the cherry-pick, see my comment here: https://github.com/godotengine/godot/pull/76378#issuecomment-1594812425
