### PR TITLE
Cancel/OK swap on HTML5 platform, small fixes.

### LINKED ISSUE #30653: Confirm/Cancel buttons of FileDialog are swapped on Web Export
**Godot version:**
3.1 Official

**OS/device including version:**
Windows 10 vs. HTML5 Web Export

**Issue description:**
Confirm and Cancel buttons are swapped on the HTML5 web export for some reason.
(Confirm can be Save/Open/etc... depending on FileDialog.mode)

Windows exported build (debug):
windows
vs.
HTML5 vs. Web Export:
web

**Steps to reproduce:**
Add a FileDialog to your Godot Project, make it popup and export for both Windows and HTML5. Compare the position of the buttons.

### PR DESCRIPTION
**Pull request by Faless**
In this PR:

- Two small fixes to address DisplayServer init, and `javascript_main.cpp` compilation and syncing with `3.2` (see #40432).
- Implement Cancel/OK UI button swap for HTML5 platform when Windows is detected. Fixes #30653 .

You can test it by checking the result of `DisplayServer.get_cancel_ok_swap()` (given there is no rendering yet).
For testing, you can override the platform value in firefox via `about:config` by setting a new property `general.platform.override` with the desired `string` value.

For a `3.2` version (where you can see the actual swap happening, and for easy cherry-pick) [see this branch](https://github.com/godotengine/godot/compare/3.2...Faless:js/swap_ok_cancel_3.2)

### CODE REVIEW

File: platform/javascript/display_server_javascript.cpp [hunk 1]
```diff
@@ -829,6 +829,8 @@ DisplayServer *DisplayServerJavaScript::create_func(const String &p_rendering_dr
 }
 
 DisplayServerJavaScript::DisplayServerJavaScript(const String &p_rendering_driver, WindowMode p_mode, uint32_t p_flags, const Vector2i &p_resolution, Error &r_error) {
+	r_error = OK; // Always succeedes for now.
```
Comment (akien-mga) [inline platform/javascript/display_server_javascript.cpp:832]:
```suggestion
	r_error = OK; // Always succeeds for now.
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
