### PR TITLE
Fix conflicted indeterminate state in asset importer

### LINKED ISSUE #84021: When importing an asset, you can't deselect a partially selected folder.
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3141) - 11th Gen Intel(R) Core(TM) i7-11375H @ 3.30GHz (8 Threads)

### Issue description

When importing an asset, a file selection window line this appears: 
image  
You can select individual files or whole folders, and when a folder has some of its items selected but not all, it appears like this:
image
Clicking on this checkbox will select all of the items in the folder, then clicking it again will deselect all of the items in the folder. This is working as intended. *However,* if some of the files can't be imported, due to file type, conflict, being gdignored, whatever, clicking this button does nothing.  It feels like a good idea to me that instead it should deselect all files, if the only files not selected *can't* be selected.
image

### Steps to reproduce

1. Open a project  
2. Go to AssetLib and hit import  
3. Select a zip file  
4. Find a folder with some unselectable files
5. Try to deselect the parent folder

### Minimal reproduction project

Open an empty godot project and attempt to import this zip:
[SignalUtilities.zip](https://github.com/godotengine/godot/files/13182622/SignalUtilities.zip)
then try to deselect the .godot folder or the `editor` folder inside of `.godot`.

### PR DESCRIPTION
**Pull request by rakkarage**
This pull request fixes an issue in the asset importer where the indeterminate state of conflicted items was not being properly resolved. It adds a new signal `propagate_check_finished` to the `Tree` class and a new method `_fix_conflicted_indeterminate_state` to the `EditorAssetInstaller` class to handle this.

Closes: https://github.com/godotengine/godot/issues/84021

Currently in Godot, in the asset import dialog (editor_asset_installer) it deals with indeterminate like this.

	void EditorAssetInstaller::_check_propagated_to_item(Object *p_obj, int p_column) {
		TreeItem *affected_item = Object::cast_to<TreeItem>(p_obj);
		if (!affected_item) {
			return;
		}
	
		Dictionary item_meta = affected_item->get_metadata(0);
		bool is_conflict = item_meta.get("is_conflict", false);
		if (is_conflict) {
			affected_item->set_checked(0, false);
			affected_item->propagate_check(0, false);
		}
	}

This is a problem because normally a indeterminate parent when clicked will become checked, but because some of the children are is_conflict they are unchecked again? which causes parent to go indeterminate again and repeat. So it prevents toggling from folder.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Why is the new signal needed? Can't you just
```C++
tree->propagate_check();
_fix_conflicted_indeterminate_state()
```
?

**Comment by rakkarage** [comment]
I tried it like that first but `_check_propagated_to_item` is already being called multiple times during a:

```
void TreeItem::propagate_check(int p_column, bool p_emit_signal) {
	bool ch = cells[p_column].checked;

	if (p_emit_signal) {
		tree->emit_signal(SNAME("check_propagated_to_item"), this, p_column);
	}
	_propagate_check_through_children(p_column, ch, p_emit_signal);
	_propagate_check_through_parents(p_column, p_emit_signal);
}
```

Which is how it gets to `_check_propagated_to_item` so modifying the tree while it was in the process of propagating a check did not seem to work even when limiting it to only calling when `affected_item == root`.

Much easier to let it finish propagating then fix.

**Comment by KoBeWi** [comment]
I mean you can fix the conflicts after calling `propagate_check()` in EditorAssetInstaller. The function is not async, so right after the call is when it has already finished. The signal is redundant.

**Comment by rakkarage** [comment]
I (dialog) don't call `proagate_check` tree does when something gets checked or unchecked or added or...
The existing code just uses this handler to uncheck conflict when checked...
I need a new handler to know when tree has finished propagating checks and dialog has finished flipping them back off again. propagate_check_finished idk

```
void EditorAssetInstaller::_check_propagated_to_item(Object *p_obj, int p_column) {
	TreeItem *affected_item = Object::cast_to<TreeItem>(p_obj);
	if (!affected_item) {
		return;
	}

	Dictionary item_meta = affected_item->get_metadata(0);
	bool is_conflict = item_meta.get("is_conflict", false);
	if (is_conflict) {
		affected_item->set_checked(0, false);
		affected_item->propagate_check(0, false);
	}
}
```

**Comment by KoBeWi** [comment]
But I do see `propagate_check()` calls in EditorAssetInstaller. It's in item checked callback, but it's the installer calling it, not the Tree itself. And your new signals is emitted right at the end of this method, which is the same as if the method's caller did something after the call.

**Comment by rakkarage** [comment]
I apologize for the confusion. :)
I was focused (tunnel vision) on the one `propagate_check` call inside `_check_propagated_to_item` which is signaled/called from `TreeItem::propagate_check`, but ya adding fix after all **other** `propagate_check` calls works.
Thanks.

**Comment by KoBeWi** [comment]
Shouldn't the conflict check in `_check_propagated_to_item()` be removed now?

Also the branch with conflicts appears as checked, while I think it should be indeterminate
image

File: editor/editor_asset_installer.cpp [hunk 1]
```diff
@@ -54,23 +54,56 @@ void EditorAssetInstaller::_item_checked_cbk() {
...
-	}
-
-	Dictionary item_meta = affected_item->get_metadata(0);
-	bool is_conflict = item_meta.get("is_conflict", false);
-	if (is_conflict) {
-		affected_item->set_checked(0, false);
-		affected_item->propagate_check(0, false);
+bool EditorAssetInstaller::_fix_conflicted_indeterminate_state(TreeItem *p_item, int p_column) {
+	// If the item is a parent, determine its state based on its non-conflict children.
+	if (p_item->get_child_count() > 0) {
```
Comment (KoBeWi) [inline editor/editor_asset_installer.cpp:65]:
```suggestion
	if (p_item->get_child_count() == 0) {
		return false;
	}
```
Prefer early returns.

File: editor/editor_asset_installer.cpp [hunk 2]
```diff
@@ -54,23 +54,56 @@ void EditorAssetInstaller::_item_checked_cbk() {
...
+				bool child_checked = child_item->is_checked(p_column);
+				bool child_indeterminate = child_item->is_indeterminate(p_column);
+				all_non_conflict_checked &= (child_checked || child_indeterminate);
+				all_non_conflict_unchecked &= !child_checked;
+				has_indeterminate_child |= child_indeterminate;
+			}
+			child_item = child_item->get_next();
+		}
+		if (has_indeterminate_child) {
+			p_item->set_checked(p_column, false);
```
Comment (KoBeWi) [inline editor/editor_asset_installer.cpp:89]:
```suggestion
```
Setting indeterminate does this automatically.

File: editor/editor_asset_installer.cpp [hunk 3]
```diff
@@ -54,23 +54,56 @@ void EditorAssetInstaller::_item_checked_cbk() {
...
+			p_item->set_indeterminate(p_column, true);
+		} else if (all_non_conflict_checked) {
+			p_item->set_checked(p_column, true);
+			p_item->set_indeterminate(p_column, false);
```
Comment (KoBeWi) [inline editor/editor_asset_installer.cpp:93]:
```suggestion
```
Same.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
