### PR TITLE
Fix emit_signal timing for GraphEdit's begin/end node move

### LINKED ISSUE #42854: GraphEdit's _begin_node_move signal is fired upon movement completion, not movement start
**Godot version:**
3.2.3, presumably `master` as well

**OS/device including version:**
Windows 10 PC

**Issue description:**
`GraphEdit` has two exposed signals for node movement, `_begin_node_move` and `_end_node_move`. [In the docs](https://docs.godotengine.org/en/stable/classes/class_graphedit.html?highlight=_begin_node_move#signals) they are described as 
> Emitted at the beginning of a GraphNode movement.

and 

> Emitted at the end of a GraphNode movement.

In practice, however, both signals are emitted at the movement completion. It is evident from the source:
https://github.com/godotengine/godot/blob/88a3db5bff3c5d62aec7e7ade4f6c62bf2d0ec3e/scene/gui/graph_edit.cpp#L883-L894

Now, signals are named with a preceding underscore, so maybe they are not supposed to be exposed. They do seem to be used internally. Visual Script editor uses those signals for the action history and `UndoRedo`, for example. Then again, I don't see any reason for such signals not to be exposed to the scripting API. But this behavior is either erroneous or wrongly documented. Relevant parts of the codebase look unchanged for at least 5 years, so this behavior is ancient.

This issue effectively prevent accurate tracking of `GraphNode` movement, specifically for cases where it can be important to be able to undo such movement. So I guess this intended functionality is broken in the Visual Script editor then.

**Steps to reproduce:**
I was provided with a repro project using this code:
```gdscript
extends GraphEdit

var _selected_node: Node

func _ready() -> void:
	set_selected($GraphNode)
	assert(connect("node_selected", self, "_on_node_selected") == OK)
	assert(connect("_begin_node_move", self, "_on_node_begin_move") == OK)
	assert(connect("_end_node_move", self, "_on_node_end_move") == OK)

func _on_node_selected(node: Node) -> void:
	_selected_node = node

func _on_node_begin_move() -> void:
	print("You begin to move me, but triggered only if your end move, i'm a bug")
	print(_selected_node.name, " begin -> ", _selected_node.offset)

func _on_node_end_move() -> void:
	print(_selected_node.name, " end -> ", _selected_node.offset)
```

If you run a scene with this script attached and try to move the only child `GraphNode`, you can see all `print`s firing only upon the movement has ended.

**Minimal reproduction project:**
Project provided by a third party:
[GraphEditBug.zip](https://github.com/godotengine/godot/files/5392388/GraphEditBug.zip)

### PR DESCRIPTION
**Pull request by gvaneyck**
Fixes #42854 
Can be cherry-picked to 3.0+

Tested using the attached project.  I also tested AnimationNodeBlendTreeEditor which uses GraphEdit, however it was unaffected by the bug because it uses the `dragged` signal for undo tracking.

Start signal is now emitted on the first drag movement.  End signal is only emitted when the drag ends (mouse up) and if the start signal was sent.

Test project: [GraphEditBug.zip](https://github.com/godotengine/godot/files/5398167/GraphEditBug.zip)

### CODE REVIEW

File: scene/gui/graph_edit.cpp [hunk 1]
```diff
@@ -775,6 +775,11 @@ void GraphEdit::_gui_input(const Ref<InputEvent> &p_ev) {
 	}
 
 	if (mm.is_valid() && dragging) {
+		if (!move_signal_sent) {
+			emit_signal("_begin_node_move");
+			move_signal_sent = true;
+		}
```
Comment (HaSa1002) [inline scene/gui/graph_edit.cpp:781]: Why are you introducing a new variable, if you have dragging available? Can't you check for `!dragging`?

Comment (gvaneyck) [reply scene/gui/graph_edit.cpp:781]: - `dragging` is always true in this block.
- Checking for `!dragging` in the `if (b->get_button_index() == BUTTON_LEFT && b->is_pressed()) {` if statement before `dragging` is set to true also doesn't work because that block is triggered by Ctrl+Clicking nodes
- `just_selected` and `!just_selected` also don't work because it can be either state depending on previous actions (e.g. if you ctrl+click a node, then drag it, `just_selected` will be false.  If you drag an unselected node, `just_selected` will be true)

File: scene/gui/graph_edit.h [hunk 2]
```diff
@@ -98,6 +98,7 @@ class GraphEdit : public Control {
 
 	bool dragging;
 	bool just_selected;
+	bool move_signal_sent;
```
Comment (Chaosus) [inline scene/gui/graph_edit.h:101]: I think this should be renamed to `moving_selection` similar to the boolean from animation_bezier_editor/track editor.

**Review by Chaosus — CHANGES_REQUESTED** [review]

File: scene/gui/graph_edit.h (hunk 2 above)
Comment (gvaneyck) [reply scene/gui/graph_edit.h]: Updated

**Review by Chaosus — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
