### PR TITLE
Fix opaque stencil rendering

### LINKED ISSUE #107935: Stencil X-Ray inconsistencies using mobile and compatibility renderers
### Tested versions

- Reproducible in v4.5.beta.mono.custom_build [88b9932ce]

### System information

Godot v4.5.beta.mono (88b9932ce) - macOS Sonoma (14.7.3) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated AMD Radeon Pro 5500M - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 threads) - 32.00 GiB memory

### Issue description

Forward+ renderer:
Image

Mobile renderer:
Image

Compatibility renderer:
Image

X-rays are not rendered in some cases using the mobile and compatibility renderers on an Intel Mac. In the screenshots above the two capsules are in the background, and the three boxes are in the foreground.

The materials are as follows:
- left capsule: standard material with stencil x-ray option enabled + custom color
- right capsule: the above material converted to a shader material, by first converting the next pass material to a shader material, then re-assigning it after converting the main material to a shader material.
- top box: no material override
- middle box: standard material converted to a shader material
- bottom box: standard material

All materials are set as surface overrides. The screenshots are from an Intel Mac and I'm not able to compare it to other machines at the moment, but the project is attached.

### Steps to reproduce

Open and run the attached project

### Minimal reproduction project (MRP)

[xray-test.zip](https://github.com/user-attachments/files/20884221/xray-test.zip)

### PR DESCRIPTION
**Pull request by apples**
Resolves #107935.

The problem was that stencil writes were occurring during depth pre-pass in Compatibility and Forward+, which resulted in improper sorting. For Mobile, a very similar problem was caused due to the lack of depth pre-pass.

The reason this issue wasn't caught earlier is because it mainly applies to objects which cannot use the shared shadow material, which was resulting in accidentally correct stencil values in the depth pre-pass.

Overview of code changes:
- GLES3
  - Disable stencil writes during depth pre-pass. Easy.
- Forward+
  - Disable stencil writes in depth pre-pass.
  - Disable shared shadow material for shaders using stencil.
- Mobile
  - (Updated) Simply sort opaque stencil objects to the end of the render list. This doesn't *fully* fix the issue, but it's a good compromise that will fix the vast majority of use cases.
  - Disable shared shadow material for shaders using stencil.

### CODE REVIEW

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 1]
```diff
@@ -2092,6 +2092,12 @@ void RenderForwardClustered::_render_scene(RenderDataRD *p_render_data, const Co
 			}
 			RD::get_singleton()->draw_command_end_label();
 		}
+
+		// Reset stencil.
+		if (scene_state.used_opaque_stencil) {
+			RD::get_singleton()->draw_list_begin(depth_framebuffer, RD::DRAW_CLEAR_STENCIL, depth_pass_clear, 0.0f);
+			RD::get_singleton()->draw_list_end();
+		}
```
Comment (Ansraer) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp]: I am really not happy with this approach. imo stencil shouldn't be written in the first place if we are in a shadow/depth-pre pass.
Yeah, doing so might increase the number of pipelines, but imo that is still far preferable over writing unnecessary data to a buffer only to then having to reset that entire buffer.

**Review by Ansraer — CHANGES_REQUESTED** [review]

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp (hunk 1 above)
Comment (apples) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp]: @Ansraer Thanks for this. Yeah I was a bit too laser-focused on avoiding pipeline changes. I've reworked it to just use a modified pipeline for the initial pass.

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 2]
```diff
@@ -1209,6 +1209,18 @@ void RenderForwardMobile::_render_scene(RenderDataRD *p_render_data, const Color
 
 		RD::get_singleton()->draw_command_end_label(); //Render Opaque
 
+		if (scene_state.used_opaque_stencil) {
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Stencil should be written during the opaque pass for mobile. Adding a new pass like this will be totally prohibitive performance wise on mobile devices.

File: servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp [hunk 3]
```diff
@@ -582,13 +598,15 @@ void SceneShaderForwardMobile::init(const String p_defines) {
 
 				bool default_enabled = (uint32_t(use_fp16) == fp16);
 				shader_versions.push_back(ShaderRD::VariantDefine(shader_group, base_define + "", default_enabled)); // SHADER_VERSION_COLOR_PASS
+				shader_versions.push_back(ShaderRD::VariantDefine(shader_group, base_define + "", default_enabled)); // SHADER_VERSION_COLOR_PASS_NOCOLOR
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp]: This is a copy of the above shader version. If you don't make any changes to the shader you shouldn't make an entirely new shader variant. This is going to increase load time for no reason

File: servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp [hunk 4]
```diff
@@ -582,13 +598,15 @@ void SceneShaderForwardMobile::init(const String p_defines) {
...
 				shader_versions.push_back(ShaderRD::VariantDefine(shader_group, base_define + "\n#define MODE_RENDER_DEPTH\n#define SHADOW_PASS\n", default_enabled)); // SHADER_VERSION_SHADOW_PASS, should probably change this to MODE_RENDER_SHADOW because we don't have a depth pass here...
 				shader_versions.push_back(ShaderRD::VariantDefine(shader_group, base_define + "\n#define MODE_RENDER_DEPTH\n#define MODE_DUAL_PARABOLOID\n#define SHADOW_PASS\n", default_enabled)); // SHADER_VERSION_SHADOW_PASS_DP
 				shader_versions.push_back(ShaderRD::VariantDefine(shader_group, base_define + "\n#define MODE_RENDER_DEPTH\n#define MODE_RENDER_MATERIAL\n", default_enabled)); // SHADER_VERSION_DEPTH_PASS_WITH_MATERIAL
 
 				// Multiview versions of our shaders.
 				shader_versions.push_back(ShaderRD::VariantDefine(shader_group_multiview, base_define + "\n#define USE_MULTIVIEW\n", false)); // SHADER_VERSION_COLOR_PASS_MULTIVIEW
+				shader_versions.push_back(ShaderRD::VariantDefine(shader_group, base_define + "\n#define USE_MULTIVIEW\n", false)); // SHADER_VERSION_COLOR_PASS_NOCOLOR_MULTIVIEW
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp]: This is using the wrong shader group. But likely shouldn't be used at all since it doesn't add a new combination of defines.

**Review by clayjohn — CHANGES_REQUESTED** [review]

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp (hunk 2 above)
Comment (apples) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: @clayjohn I realize I called it a "pass" but it doesn't actually start a new render pass, it's just re-drawing elements while still in the opaque pass. First draw is depth-only, second draw is color+stencil.

image

File: servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp (hunk 3 above)
Comment (apples) [reply servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp]: Would adding a new ~`stencil`~ `depth_only` field to the `PipelineKey` struct be acceptable?

Comment (apples) [reply servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp]: I've updated it to use a `depth_only` field on the `PipelineKey`.

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp (hunk 2 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Oh nice. That's not so bad then. I still don't understand the need for this "pass" though. In the description you say that it is needed because you clear the stencil after doing opaque, but I don't see where you actually clear the stencil. It looks more like you are now just rendering stencil objects twice, once during the main opaque pass, and then a second time immediately after.

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: I really don't think we should be drawing stencil objects twice. Depth + color + stencil writes should all happen at once during the opaque pass. Then objects with a stencil read should happen in the alpha pass. It should be that simple.

Comment (apples) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: @clayjohn Sorry the description was slightly outdated, the stencil buffer is *not* cleared anymore with this current PR. I've updated the description to be more accurate. This PR introduces a separate pipeline for the first draw of stencil materials which disables stencil writes, so no clear is necessary.

The screenshot in the linked issue shows what happens when stencil writes occur at the same time as depth writes, and I don't think it's possible to resolve this without doing a second draw.
Without complete depth information, "depth pass" stencil writes might occur and write incorrect stencil values, before another mesh is drawn which occludes the stencil object.

It's the same reason we force depth pre-pass on when using stencil in forward+.

If you're interested, I can share RenderDoc captures of both scenarios.

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: But why draw the object twice? Shouldn't you just draw it a single time in the stencil pass in that case? Or better yet, use the sort key so stencil objects always draw last in the normal opaque pass?

Comment (apples) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Stencil objects might occlude each other though. If we sort stencil objects last, they'll render correctly *most* of the time, but still render incorrectly when multiple stencil objects overlap.

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Right. Okay. This really sucks. I guess this is why we need fine tune control over render order. 

But it seems like we don't have any other choice

Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: I haven't dived into this deep enough so I could very much be barking up the wrong tree here.

It looks like all objects are passed a second time, wouldn't only the objects that require stencil checks need to be in this stencil pass? It wouldn't be too hard to create a `RENDER_LIST_STENCIL` that has only the objects that need to be rendered a second time, or maybe even only render the stencil objects here and remove them from RENDER_LIST_OPAQUE all together, and then apply a sort algorithm there similar to how we do with transparent object?

Comment (QbieShay) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: >Stencil objects might occlude each other though. If we sort stencil objects last, they'll render correctly most of the time, but still render incorrectly when multiple stencil objects overlap.

This is an acceptable trade-off. It;s okay. Stencil are experimental, some stuff won't work.

I'd much rather we get a proper solution later down the line than adding a "mini multipass rendering". It can be in the documentation. The Xray option can either be axed entirely, or show a warning that will work only on forward+

Comment (apples) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp]: Personally I don't deal with Mobile very often, so I'm willing to go with whatever y'all decide on.

I think @BastiaanOlij suggestion of sorting the stencil objects in the same way as the transparent pass, is the best compromise for performance.

**Comment by apples** [comment]
There is no longer a depth-only pass for stencil in Mobile. Opaque stencil objects are simply sorted after all non-stencil elements.

image

**Comment by Repiteo** [comment]
@clayjohn Could you give this another review? Seems like your comments have been addressed

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by Repiteo** [comment]
Thanks!
