### PR TITLE
Fix integer value for `GL_MAX_UNIFORM_BLOCK_SIZE` overflowing

### LINKED ISSUE #68180: Exported Web Project does not work on Linux with Mesa 22.2+
### Godot version

v4.0.beta4.official [e6751549c]

### System information

- Chromium Version 107.0.5304.87 (Official Build) Arch Linux (64-bit)
- Firefox 107.0b8

- OS: Arch Linux
- ~KERNEL: 6.0.6-arch1-1~
- ~KERNEL: 6.0.7-arch1-1~
- ~KERNEL: 6.0.8-arch1-1~
- KERNEL: 6.0.9-arch1-1
- CPU: AMD Ryzen 7 3700X 8-Core
- GPU: AMD Radeon RX 6900 XT (navi21, LLVM 14.0.6, DRM 3.48, 6.0.6-arch1-1)
- GPU DRIVER: 4.6 Mesa 22.2.1

### Issue description

When I try to start the provided minimal project as a web project, the mesh in the scene is not visible and the browser console is showing this error right after the site loaded:
Screenshot from 2022-11-02 20-01-35

After that, the console is flooded with these error messages:
Screenshot from 2022-11-02 19-49-14

### Steps to reproduce

Use the [official beta4](https://downloads.tuxfamily.org/godotengine/4.0/beta4/) with the provided templates and try to start the provided project as a web application

### Minimal reproduction project
[beta4_webtest.zip](https://github.com/godotengine/godot/files/9923528/beta4_webtest.zip)

### PR DESCRIPTION
**Pull request by adamscott**
This PR fixes the issue of shader compilation on the web platform.
Capture d’écran du 2023-08-22 11-36-25

It happens that the following line (on my PC, at least) makes the `int Config::max_uniform_buffer_size` to overflow to `-2147483648`, which is exactly `INT_MIN` (or `INT_MAX + 1`).
https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/drivers/gles3/storage/config.cpp#L94

Then, `int Config::max_renderable_lights` (defaults to `32`) is set to the minimum value of itself or our `Config::max_uniform_buffer_size`, which we remember is `-2147483648`. Then the same thing happens for `int Config::max_lights_per_object` (defaults to `8`).
https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/drivers/gles3/rasterizer_scene_gles3.cpp#L2626-L2627

This makes two [scene.glsl](https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/drivers/gles3/shaders/scene.glsl) "#defines" with `INT_MIN` value. It's pretty easy to understand then why the shader can't compile.

https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/drivers/gles3/rasterizer_scene_gles3.cpp#L2664-L2673

~My PR is quite simple. If the value of `Config::max_uniform_buffer_size` is negative, it means that it overflowed. So `INT_MAX` is set as the value.~

Edit: used `glGetInteger64v()` and `int64_t` for `Config` instead.

Fixes #68180

### CODE REVIEW

**Comment by bitsawer** [comment]
Interesting bug. I found possibly related MESA PR's and issues as at least original the bug report happens when on web and Linux MESA. https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/18512 and https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/922

**Comment by adamscott** [comment]
> Interesting bug. I found possibly related MESA PR's and issues as at least the original bug report happens when on web and Linux MESA. https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/18512 and https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests/922

I confirm that my workstation use Linux MESA.

**Comment by bruvzg** [comment]
Since this is an issue on Web platform, it's probably using ANGLE. And ANGLE specify use 64-bit for this value (and some other "size" values):

https://github.com/google/angle/blob/4723a32df4e48c946dc7aabe024fb80badc63bdf/src/libANGLE/queryutils.cpp#L3866-L3875

There's also the following comment in the code (actual clamping is done only when using Vulkan as backend, when using desktop GL is seems to be used as it):
```
 // Clamp the maxUniformBlockSize to 64KB (majority of devices support up to this size
 // currently), on AMD the maxUniformBufferRange is near uint32_t max.
```

**Comment by adamscott** [comment]
@bruvzg I'm actually using an AMD card. (AMD Radeon™ RX Vega 64)

**Comment by adamscott** [comment]
For the record, I changed my code to make the config use `int64_t` ints instead of `int`. And effectively use `glGetInteger64v()` instead of the regular one.

**Comment by lawnjelly** [comment]
> For the record, I changed my code to make the config use int64_t ints instead of int. And effectively use glGetInteger64v() instead of the regular one.

What value does it return as `int64_t`? :thinking:

File: drivers/gles3/storage/config.cpp [hunk 1]
```diff
@@ -88,11 +88,11 @@ Config::Config() {
 	rgtc_supported = extensions.has("GL_EXT_texture_compression_rgtc") || extensions.has("GL_ARB_texture_compression_rgtc") || extensions.has("EXT_texture_compression_rgtc");
 #endif
 
-	glGetIntegerv(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, &max_vertex_texture_image_units);
-	glGetIntegerv(GL_MAX_TEXTURE_IMAGE_UNITS, &max_texture_image_units);
-	glGetIntegerv(GL_MAX_TEXTURE_SIZE, &max_texture_size);
-	glGetIntegerv(GL_MAX_UNIFORM_BLOCK_SIZE, &max_uniform_buffer_size);
-	glGetIntegerv(GL_MAX_VIEWPORT_DIMS, max_viewport_size);
+	glGetInteger64v(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS, &max_vertex_texture_image_units);
+	glGetInteger64v(GL_MAX_TEXTURE_IMAGE_UNITS, &max_texture_image_units);
```
Comment (bruvzg) [inline drivers/gles3/storage/config.cpp:92]: There's another one `glGetIntegerv(GL_MAX_TEXTURE_IMAGE_UNITS, ...)` in the `shader_gles3.cpp`, not related to the issue, but probably should be changed to 64-bit version as well for consistency.

https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/drivers/gles3/shader_gles3.cpp#L774

Comment (adamscott) [reply drivers/gles3/storage/config.cpp:92]: Done!

**Review by clayjohn — APPROVED** [review]
Looks great! Good work

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
