### PR TITLE
Fix tileset image and background sometimes disappearing

### LINKED ISSUE #61470: tileset editor blank in a certain scale
### Godot version

Godot_v4.0-alpha8_win64

### System information

Windows 10, i5-8250U, mx150, Vulkan

### Issue description

When zooming to get a better view of the tileset in the editor, the tiles sunddenly disappear at 252%
Here's a gif showing it:
example1
.
I used a tile set from [https://jamiebrownhill.itch.io/solaria-demo](url)
This is not a big issue, but it bothers me a bit.

### Steps to reproduce

1. create a tilemap
2. create a tileset
3. in the tileset editor, scroll your mouse to zoom, until the tiles shown suddenly disappear

### Minimal reproduction project

[godot4 testing.zip](https://github.com/godotengine/godot/files/8787777/godot4.testing.zip)

### LINKED ISSUE #63070: TileMap image sometimes disappear
### Godot version

4.0 a12

### System information

win10 vulkan desktop

### Issue description

Moving or scaling is a chance to cause the image to disappear in TileMap, and by the way this issue has not been found in TileSet yet.

tilemapb

### Steps to reproduce

add tilemap node set tileset add tile image

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by MinusKube**
Fixes #63070 and fixes #61470 (which are duplicates, I believe)

This fixes the bug causing the tileset image and background from disappearing in some cases.

Actually, there were two issues occurring:
- The image disappeared because the `*_tiles_drawing_root` children were clipped because they were not set to the correct size (they were not using the zoom), I fixed it by not setting their size at all, now their size is inferred correctly using their parent.
- The background disappeared because it had some kind of weird size dependency with its parent, causing it to shrink multiple times when zooming out once, I fixed it by changing its anchor from `PRESET_FULL_RECT` to `PRESET_TOP_LEFT`, and setting their size in the `_update_zoom_and_panning` method instead of the draw method.

### CODE REVIEW

File: editor/plugins/tiles/tile_map_editor.cpp [hunk 1]
```diff
@@ -2214,12 +2214,14 @@ TileMapEditorTilesPlugin::TileMapEditorTilesPlugin() {
 	atlas_sources_split_container->add_child(tile_atlas_view);
 
 	tile_atlas_control = memnew(Control);
+	tile_atlas_control->set_anchors_and_offsets_preset(Control::PRESET_FULL_RECT);
```
Comment (groud) [inline editor/plugins/tiles/tile_map_editor.cpp:2217]: I believe this should instead be done inside the `add_control_over_alternative_tiles` and `add_control_over_alternative_tiles` functions. As it's kind of a requirement for any control to work there.

**Review by groud — DISMISSED** [review]
Aside from my small nitpick, looks like a correct fix. Good job!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
