### PR TITLE
Error handling functions for GdScript

### LINKED ISSUE #211: Improve error handling/messages for users
**Describe the project you are working on:**

Working on plugins

**Describe the problem or limitation you are having in your project:**

When something I do in GDScript that results in an error, and I am checking for errors and printing them to the screen, they come out as integers. Because I do not have @GlobalScope's err enums memorized, I must then break my flow of thought from looking at my code to now looking up this enum in documentation to figure out what it means.

It would be more convenient for debugging if error values could be printed directly as a string based on the name of their identifier.

Add a `@GDScript.err2str(Error value) -> String` method that handles the conversion of integer value to String identifier name for us. 

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

It is purely a convenience factor since a lot of the information people want can already be acquired through manual work. But if we want to improve UX by absolving users of the need to do that, then that would be great.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

    if error != OK:
        print("Error: %d" % error) # shows as int, must look up in docs!
        print("Error: %s" % err2str(error)) # shows as string, now meaning immediately

**Describe implementation detail for your proposal (in code), if possible:**

You just need to add a Map<int, String> into the core somewhere and then make it accessible to scripting languages that each implement a global function for accessing the data.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

You could, conceivably, just write your own Dictionary for handling this, but that would be even *more* work and the whole reason to do this in the first place is to improve the UX, not make it worse.

**Is there a reason why this should be core and not an add-on in the asset library?:**

See above.

### PR DESCRIPTION
**Pull request by yvie-k**
Many functions in GdScript can fail. But there are no functions to display the error to users or give a meaningful message in the console.

Therefore this Pull Request adds two functions:
 - `error_string(code: int)`:
    Returns a human readable string for the given error code.
    E.g. `error_string(ERR_UNAVAILABLE) == "Requested operation is unsupported/unavailable"`
 - `push_error_formatted(message: String, code: int)`:
    Convenience function.
    Inspired by the `perror` function from C.
    Actually just a shorthand for `push_error(message + ": " + error_string(code))`.

Some error codes were not clear to me from the comments in the source code or the documentation. I've added some comments to mark those strings and (hopefully) replace them with better messages during review

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/211.*

### CODE REVIEW

File: core/variant/variant_utility.cpp [hunk 1]
```diff
@@ -484,6 +484,14 @@ struct VariantUtilityFunctions {
 		return str;
 	}
 
+	static inline String error_string(int error) {
+		if (error < 0 || error >= ERR_MAX) {
+			return String("Invalid error code");
```
Comment (Calinou) [inline core/variant/variant_utility.cpp:489]: Make it clear that "Invalid error code" is not an error code message, but an internal error:

```suggestion
			return String("(invalid error code)");
```

File: doc/classes/@GlobalScope.xml [hunk 2]
```diff
@@ -276,6 +276,15 @@
 				Easing function, based on exponent. The curve values are: 0 is constant, 1 is linear, 0 to 1 is ease-in, 1+ is ease out. Negative values are in-out/out in.
 			</description>
 		</method>
+		<method name="error_string">
+			<return type="String">
+			</return>
+			<argument index="0" name="error" type="int">
+			</argument>
+			<description>
+				Returns a human readable name of the given error code.
```
Comment (Calinou) [inline doc/classes/@GlobalScope.xml:285]:
```suggestion
				Returns a human-readable name for the given [code]error[/code] code.
```

File: core/variant/variant_utility.cpp [hunk 3]
```diff
@@ -484,6 +484,14 @@ struct VariantUtilityFunctions {
 		return str;
 	}
 
+	static inline String error_string(int error) {
```
Comment (Calinou) [inline core/variant/variant_utility.cpp:487]: I wonder if we can use `Error` instead of `int` as the parameter type for `error`. We should also check if this appears in the generated documentation.

File: doc/classes/@GlobalScope.xml [hunk 4]
```diff
@@ -720,6 +729,23 @@
...
+			<argument index="1" name="error" type="int">
+			</argument>
+			<description>
+				Pushes an error message along with a human readable name of the error code to Godot's built-in debugger and to the OS terminal.
+				[codeblock]
+				var file = File.new()
+				var err = file.open("res://file.txt", File.READ)
+				if err:
+				    push_error_formatted("failed to open file", err) # Prints, e.g. "failed to open file: File not found", to debugger and terminal as error call
+				[/codeblock]
```
Comment (Calinou) [inline doc/classes/@GlobalScope.xml:746]: Add the same note as `push_error` as it also applies here:

```suggestion
				[/codeblock]
				[b]Note:[/b] Errors printed this way will not pause project execution. To print an error message and pause project execution in debug builds, use [code]assert(false, "test error")[/code] instead.
```

File: doc/classes/@GlobalScope.xml [hunk 5]
```diff
@@ -720,6 +729,23 @@
...
+			</argument>
+			<argument index="1" name="error" type="int">
+			</argument>
+			<description>
+				Pushes an error message along with a human readable name of the error code to Godot's built-in debugger and to the OS terminal.
+				[codeblock]
+				var file = File.new()
+				var err = file.open("res://file.txt", File.READ)
+				if err:
+				    push_error_formatted("failed to open file", err) # Prints, e.g. "failed to open file: File not found", to debugger and terminal as error call
```
Comment (Calinou) [inline doc/classes/@GlobalScope.xml:745]: The line is pretty long. It's better to split the comment to put it on the line above. Also, error messages should preferably start with a capital letter:

```suggestion
					# Prints, e.g. "Failed to open file: File not found", to debugger and terminal as error call
				    push_error_formatted("Failed to open file", err)
```

**Review by Calinou — DISMISSED** [review]
Feature looks good to me, but there are some documentation changes to make. It's also worth checking whether the error conversion method can accept an `Error` instead of an `int`.

File: core/variant/variant_utility.cpp (hunk 3 above)
Comment (Dragoncraft89) [reply core/variant/variant_utility.cpp]: Seems to work. But using Error as argument type in `@GlobalScope.xml` still only displays `int` in the documentation

Comment (Dragoncraft89) [reply core/variant/variant_utility.cpp]: Static Checks error out, because Error is an undefined type in `@GlobaScope.xml`? Locally this worked fine. Reverting that for now

**Comment by akien-mga** [comment]
It would be good to squash the commits into one, as the second and third commits are fixups of the first.
I'll try to review the proposed error names more in-depth soon.

**Comment by akien-mga** [comment]
Actually no commits 1 and 2 are good to keep separate, but it's the third fixup commit which should be melded into the first and second commits so that they're correct "from the start". Once merged, we want the commit history to reflect what changes in the engine and not what changed during PR review.

**Comment by Dragoncraft89** [comment]
@akien-mga Done.
I saw in the linked proposal, that `err2str` was proposed as a name. This is probably a better name, as it's more in line with other names such as `var2str`. If you have a preference on the name, just ping me

File: core/variant/variant_utility.cpp [hunk 6]
```diff
@@ -1234,12 +1250,14 @@ void Variant::_register_variant_utility_functions() {
...
 	FUNCBINDR(_typeof, sarray("variable"), Variant::UTILITY_FUNC_TYPE_GENERAL);
 	FUNCBINDVARARGS(str, sarray(), Variant::UTILITY_FUNC_TYPE_GENERAL);
+	FUNCBINDR(error_string, sarray("error"), Variant::UTILITY_FUNC_TYPE_GENERAL);
 	FUNCBINDVARARGV(print, sarray(), Variant::UTILITY_FUNC_TYPE_GENERAL);
 	FUNCBINDVARARGV(printerr, sarray(), Variant::UTILITY_FUNC_TYPE_GENERAL);
 	FUNCBINDVARARGV(printt, sarray(), Variant::UTILITY_FUNC_TYPE_GENERAL);
 	FUNCBINDVARARGV(prints, sarray(), Variant::UTILITY_FUNC_TYPE_GENERAL);
 	FUNCBINDVARARGV(printraw, sarray(), Variant::UTILITY_FUNC_TYPE_GENERAL);
 	FUNCBINDVARARGV(push_error, sarray(), Variant::UTILITY_FUNC_TYPE_GENERAL);
+	FUNCBIND(push_error_formatted, sarray("message", "error"), Variant::UTILITY_FUNC_TYPE_GENERAL);
```
Comment (Rubonnek) [inline core/variant/variant_utility.cpp:1260]: I think this `push_error_formatted` function is unnecessary -- concatenating the provided error string and using `push_error` suffices

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And sorry for the delay getting this merged.
