### PR TITLE
Fix Parallax2D physics interpolation

### LINKED ISSUE #91625: Physics 2D Interpolation does not work on Parallax2D.
### Tested versions

Godot v4.3.dev6.mono - macOS 14.4.1 - GLES3 (Compatibility) - Apple M2 Max - Apple M2 Max (12 Threads)

### System information

Godot v4.3.dev6.mono - macOS 14.4.1 - GLES3 (Compatibility) - Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

Spawned from https://github.com/godotengine/godot-proposals/issues/2753#issuecomment-2094912482.

Parallax2D object does not seem to support physics interpolation. ParallaxBackground and ParallaxLayers do work. With a small physics rate (like 15hz), Parallax 2D is visibly choppy and is not interpolation.

### Steps to reproduce

1) Set Physics Step to a low value like 15hz
2) Add a Parallax2D and Sprite2D node to the root scene node.
3) Add a 2D Camera which follows an object.
4) Observe that the Parallax2D is not smooth.

Minimal repro here: https://github.com/TrieBr/GodotParallax2DInterpolation

Observe the differences between Parallax2D and ParallaxBackground/ParallaxLayer by toggling visibility on both and testing.

### Minimal reproduction project (MRP)

Minimal repro here: https://github.com/TrieBr/GodotParallax2DInterpolation

### PR DESCRIPTION
**Pull request by rburing**
The `camera_screen_center` value was stale in case of interpolation, so in that case we compute it using the affine inverse of the interpolated camera transform.

- Fixes https://github.com/godotengine/godot/issues/91625

### CODE REVIEW

**Comment by rburing** [comment]
For ease of reviewing: `xform` is interpolating between the return value of `get_camera_transform()` in the previous physics tick and in the current physics tick. The end of the `get_camera_transform` method is:

https://github.com/godotengine/godot/blob/281fe39929303a8ef12e72ff7999b849bbe0678d/scene/2d/camera_2d.cpp#L244-L246

Hence instead of

https://github.com/godotengine/godot/blob/281fe39929303a8ef12e72ff7999b849bbe0678d/scene/2d/camera_2d.cpp#L68

we can do `adj_screen_pos = xform.affine_inverse().get_origin()`, and this PR does an optimized version of that.

**Comment by akien-mga** [comment]
CC @markdibarry

**Review by markdibarry — APPROVED** [review]
I did some quick tests, and checked the screen center values while using camera drag with and without physics interpolation. LGTM.

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -54,19 +54,22 @@ void Camera2D::_update_scroll() {
...
+		Point2 adj_screen_pos;
+
 		Transform2D xform;
 		if (is_physics_interpolated_and_enabled()) {
 			xform = _interpolation_data.xform_prev.interpolate_with(_interpolation_data.xform_curr, Engine::get_singleton()->get_physics_interpolation_fraction());
+			// The following alternative to xform.affine_inverse().get_origin() is more efficient.
+			adj_screen_pos = xform.basis_xform(-xform.get_origin());
 		} else {
 			xform = get_camera_transform();
+			adj_screen_pos = camera_screen_center - (screen_size * 0.5);
```
Comment (lawnjelly) [inline scene/2d/camera_2d.cpp:68]: Pardon my ignorance, but does this even work if the camera is rotated?

File: scene/2d/camera_2d.cpp [hunk 2]
```diff
@@ -54,19 +54,22 @@ void Camera2D::_update_scroll() {
...
 
+		Size2 screen_size = _get_camera_screen_size();
+		Point2 screen_offset = (anchor_mode == ANCHOR_MODE_DRAG_CENTER ? (screen_size * 0.5) : Point2());
+		Point2 adj_screen_pos;
+
 		Transform2D xform;
 		if (is_physics_interpolated_and_enabled()) {
 			xform = _interpolation_data.xform_prev.interpolate_with(_interpolation_data.xform_curr, Engine::get_singleton()->get_physics_interpolation_fraction());
+			// The following alternative to xform.affine_inverse().get_origin() is more efficient.
+			adj_screen_pos = xform.basis_xform(-xform.get_origin());
```
Comment (lawnjelly) [inline scene/2d/camera_2d.cpp:65]: Should we be calculating interpolated `camera_screen_center` here? It looks like this function is just bound for users, but it could have been something I missed originally. Then the code for the adjusted center could be the same.

But maybe this interpolation is calculated after the user `_process()` in which case it wouldn't be so useful (I can't remember the order of operations here off hand).

**Comment by lawnjelly** [comment]
I'm not clear on what `adj_screen_pos` should be in the case of camera rotation. Should it be the top left of the rotated screen, or should it be the centre minus half the screen size?

I suspect they can both just derive the `adj_screen_pos` from the `xform`, this would make the code a bit simpler and less bug prone in future. The cost of a single `xform` for each camera doesn't seem worth worrying about if it makes a single path for all cases.

**Comment by markdibarry** [comment]
@lawnjelly Oh good catch. I didn't test with rotation and totally should have. The original behavior is still correct, but the interpolated version now has different behavior. I used a camera with position and rotation smoothing to show the difference.

Without interpolation:

https://github.com/godotengine/godot/assets/21325943/7183d814-84c9-42eb-a194-f7166fe6ae19

With interpolation:

https://github.com/godotengine/godot/assets/21325943/39a45191-d51b-4631-84d0-32e39ab11e42

**Comment by rburing** [comment]
@markdibarry Could you share your test scene as a ZIP file?

**Comment by markdibarry** [comment]
Here you go!
[parallaxmrp.zip](https://github.com/godotengine/godot/files/15263795/parallaxmrp.zip)

**Comment by markdibarry** [comment]
We're getting close! The only problems I found was when I zoomed a camera in or out.

When zoomed out I noticed it was scrolling differently with interpolation on, and eventually broke when it got to the the loop point:
A

Just to preempt the question of why the first image has the looping looking weird too, that's outside the normal bounds of the viewport if the zoom was set to 1. If you were to increase the repeat_times it works correctly, but still doesn't with interpolation:
B

**Comment by rburing** [comment]
@markdibarry I don't understand how you got to the situation in the screenshot, please upload the new MRP.

**Comment by markdibarry** [comment]
@rburing I just set the zoom on the camera to 0.5.

**Comment by rburing** [comment]
@markdibarry I made a silly mistake, the PR should be good to go now.

**Review by markdibarry — APPROVED** [review]
Ran through tests for most things I think would be affected. LGTM. Great job!

**Review by lawnjelly — APPROVED** [review]
I think this looks as correct as possible, and I guess testing will reveal any problems here.

(It's been a while since I looked at `Camera2D`, and the whole logic of doing processing in `get_camera_transform()` has long needed refactoring.)
