### PR TITLE
Make mouse enter/exit notifications match mouse events

### LINKED ISSUE #81909: MouseEnter/Exit events not correctly passed on from children to parent script since Godot 4.2 dev3
### Godot version

4.2 dev3 and 4.2 dev4

### System information

Windows 10

### Issue description

With the following Control Node hierarchy:
image
the `TextureRect` Node (godot icon) blocks the `mouse_entered / mouse_exited` signals in the script of the `ParentWithScript` Node (the white area). The `TextureRect` uses its default `mouse_filter` of `Pass`. When using the `mouse_filter` `Ignore`, the signals are triggered correctly on the parent.

I went back the official versions to see when the behavior started and it seems to have started with 4.2 dev3.

In 4.2 dev2 the behavior is still a bit weird, but it has been like that for a long time (tested with 4.1.1) : when moving the mouse from "over the parent" (the white area in the MRP) directly to "over the child" (the godot icon), the `mouse_exited` signal gets triggered first and then directly the `mouse_entered` again. But at least the last signal that gets triggered is `mouse_entered` (important for custom tooltips!).

Another quick observation (that is not in the MRP): I added a tooltip to the `ParentWithScript` node and that gets correctly shown when hovering over the `TextureRect` child node! So it seems to only affect the signals.

### Steps to reproduce

- Open the minimal reproduction project in Godot 4.2 dev3 or dev4
- Run it
- Observe that `entered` gets printed when hovering over the white area (the parent), but `exited` gets called as soon as the mouse moves over the godot icon (the child)

### Minimal reproduction project

[MouseEnterExitTest.zip](https://github.com/godotengine/godot/files/12657936/MouseEnterExitTest.zip)

### LINKED ISSUE #82530: Problems with new `mouse_entered` and `mouse_exited` signals
### Godot version

master, 4.2 dev3+, since 1c3c17

### System information

Windows 10

### Issue description

#81909 is caused by the same root cause, #67791
#82182 does not solve the issues.

### Mouse enter and exit are not in sync with _gui_input InputEventMouseButton and other mouse events.
This leads to issues where a button can be clicked on without being hovered:
godot_mouse_event_issue
InputEventMouseMotion should be called only between mouse enter and exit events, currently this is not the case.
The existing mouse events (InputEventMouse*) are fine and work as expected, the mouse enter and exit signals need to match it.

### Mouse enter and exit do not respect `MOUSE_FILTER_PASS`.
Only `MOUSE_FILTER_IGNORE` and `MOUSE_FILTER_STOP` are respected. This means there is not a good way to get the event in a parent while the child needs mouse events.
Workarounds include: 
- Manually set all child Controls to `MOUSE_FILTER_IGNORE`. This does not scale and doesn't work if the children also need mouse input. (Doesn't `MOUSE_FILTER_PASS` exist for this reason?)
- Manually track the proper state by listening to InputEventMouseMotion. This can tell you when the mouse has entered, but not exited.
- Continuously check `Rect2.has_point()`. This is only axis-aligned and doesn't include children.

These workarounds are cumbersome and not performant.
All Nodes that use `NOTIFICATION_MOUSE_ENTER` like `BaseButton` would also need to do be changed.

The current implementation of mouse enter and exit is useful in its own way, but should not be the default used for most events.

### No other UI system I could find does mouse enter and exit events like this. 
For the ones that provide multiple ways, this way isn't the default.
- [Unity has both mouse enter/leave and mouse over/out](https://docs.unity3d.com/Manual/UIE-Mouse-Events.html)
- [HTML has both onmouseenter/onmouseleave (doesn't bubble up, excludes overlaps, includes children) and onmouseover/onmouseout (bubbles up, excludes overlaps, includes children)](https://www.w3schools.com/jsref/event_onmouseenter.asp)
- [Windows has both IsMouseOver (includes child elements)](https://learn.microsoft.com/en-us/dotnet/api/system.windows.uielement.ismouseover) [and IsMouseDirectlyOver (does not)](https://learn.microsoft.com/en-us/dotnet/api/system.windows.uielement.ismousedirectlyover?view=windowsdesktop-7.0#system-windows-uielement-ismousedirectlyover)
- [Phaser and has a toponly input flag to ignore overlaps](https://newdocs.phaser.io/docs/3.60.0/Phaser.Input.InputPlugin#topOnly)
- [Haxeflixel has mouseChildren flag that allows children to receive mouse events](https://api.haxeflixel.com/flixel/input/mouse/FlxMouseEventManager.html)
- [Gamemaker does bounding box test, no overlaps](https://manual.yoyogames.com/#t=The_Asset_Editors%2FObject_Properties%2FObject_Events.htm&rhsearch=mouse%20enter&rhhlterm=mouse%20enter)

### Proposed Solution
Change the current `mouse_enter` and `mouse_exited` signals to `mouse_over` and `mouse_out`. Add a `NOTIFICATION_MOUSE_OVER`  and `NOTIFICATION_MOUSE_OUT` for it.
`mouse_entered` signal: Emitted when the mouse enters the control's Rect area or any of its descendants, provided its [mouse_filter](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-property-mouse-filter) lets the event reach it.
`mouse_exited` signal: Emitted when the mouse exits the control's Rect area and all of its descendants, provided its [mouse_filter](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-property-mouse-filter) lets the event reach it.
The signals should not propagate up if the parent already received that signal.
Implementation details for this:
- The mouse entered signal would propagate up until the last gui.mouse_over,
- The mouse exited signal would propagate up until where the new gui.mouse_over is a parent of the old gui.mouse_over.
- otherwise they do propagate like the mouse events do.

This ensures that a Control first receives `mouse_enter` then mouse move events then `mouse_exit`.

### Steps to reproduce

Add a button
Add a visible control to it with `MOUSE_FILTER_PASS` set, like an image.
Hover over the button and the image. 
The button does not get hovered, even though it will accept a mouse click.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by kitbdev**
I created this based on #83276 to fix some logic and edgecases and to add some tests, since this is important for 4.2.
- based on and supersedes https://github.com/godotengine/godot/pull/83276
- resolve #81909
- resolve #82530
- regression from #67791
- supersedes #82182

Changes:
Mouse Enter/Exit notifications go through non-Control CanvasItems to match mouse event behavior in `gui_input`.
Handles Mouse Filters.
Handles changing Mouse Filters while hovering a descendant.
Handles changing Top Level in CanvasItems while hovering a descendant.
Handles removing or hiding a Control when hovering a descendant.
Simplified some logic.
Added tests.
Clarified some documentation.

Updated test case "[Viewport][GuiInputEvent] Mouse Motion changes the Control that it is over." to check both mouse enter and mouse enter self notifications.
Added test cases:
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification propagation."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification propagation when moving into child."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification propagation with top level."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification propagation with mouse filter stop."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification propagation with mouse filter ignore."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification when changing top level."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification when changing the mouse filter to stop."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification when removing the hovered Control."
- "[Viewport][GuiInputEvent] Mouse Enter/Exit notification when hiding the hovered Control."

The notification propagation test doesn't check for notification order, I'm not sure if it's possible to check that in a test or if it really needs to be tested.

These tests don't cover all edgecases, so I could add more if it is wanted. Such as changing mouse filter ignore when hovering on and off, moving mouse between siblings, or moving the mouse up and down the node hierarchy when mouse filter is stop or is set to top level.

### CODE REVIEW

**Review by Sauermann — COMMENTED** [review]
Thanks for your great effort! The changes are looking good so far.

> The notification propagation test doesn't check for notification order, I'm not sure if it's possible to check that in a test or if it really needs to be tested.

It is possible to check the notification order. You can see a method for how to do that in the updated #83276.
However I wouldn't consider testing the notification order strictly necessary for this PR.

> These tests don't cover all edgecases [...]

I believe, that the implemented set of unit-tests covers the most important cases. I will try to test the implementation before Thursday.

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1834,6 +1834,10 @@ void Control::set_mouse_filter(MouseFilter p_filter) {
 	data.mouse_filter = p_filter;
 	notify_property_list_changed();
 	update_configuration_warnings();
+
+	if (get_viewport()) {
```
[the remark this answers is not in the document]
Comment (kitbdev) [reply scene/gui/control.cpp:1838]: It does make sense to have a guard here. 
It should probably be put before the filter is set and the other calls, right? Before `data.mouse_filter = p_filter`.

[the remark this answers is not in the document]
Comment (Sauermann) [reply scene/gui/control.cpp:1838]: Yes, that is the intention.

**Comment by Sauermann** [comment]
I have created a testing project for mouse notifications: [HierarchicalMouseNotifications.zip](https://github.com/godotengine/godot/files/13288996/HierarchicalMouseNotifications.zip)

In most cases this PR works as expected. Only when switching from/to `MOUSE_FILTER_IGNORE` and when hiding Controls, I found, that there could be some stale mouse-over states.

In the following video I show these.

https://github.com/godotengine/godot/assets/6299227/737aa9b7-cc56-40e1-916f-7533f5c29ea5

The first one (top right corner):
0. start with the middle Control set to pass
1. move mouse cursor over bottom Control
2. press SPACE to set the middle (right) Control from pass to ignore
3. Now the middle Control has as state, that the mouse is over the Control, which is not expected.

The second one (bottom left corner):
0. start with the middle Control visible
1. move mouse cursor over bottom Control
2. press SPACE to hide the middle (right) Control
3. now the topmost Control has as state, that the mouse is over the Control, which is not expected

The third one (bottom right corner) A:
0. start with the middle Control set to stop
1. move mouse cursor over bottom Control
2. press SPACE to set the middle (right) Control from pass to ignore
3. Now the middle Control has as state, that the mouse is over the Control, which is not expected.

The third one (bottom right corner) B (not in the video):
0. start with the middle Control set to ignore
1. move mouse cursor over bottom Control
2. press SPACE to set the middle (right) Control from ignore to stop
3. Now the middle Control doesn't receive a mouse-enter notification, but that would be expected.
4. move the mouse from the bottom Control to the background
5. Now the middle Control receives a mouse-exit notification (currently without having received a mouse-enter notification before)

I noticed that in contrast to #83276, in this PR a Control with `MOUSE_FILTER_IGNORE` doesn't break the notification chain. Is there a specific reason for choosing this interpretation?

**Comment by kitbdev** [comment]
> a Control with MOUSE_FILTER_IGNORE doesn't break the notification chain. Is there a specific reason for choosing this interpretation?

Yes, since this is how it works with `_gui_input`. 
From the [mouse filter ignore documentation](https://docs.godotengine.org/en/latest/classes/class_control.html#enum-control-mousefilter): `This will not block other controls from receiving these events or firing the signals`

For changing mouse filter to/from ignore while the mouse is over it or a descendant (your 1st, 3rd, and 4th cases):

I consider this intended, since setting the mouse filter to ignore means it should not receive any notifications or signals. 
If the user is tracking the mouse over state and changing the mouse filter to/from ignore, they should expect this behavior or manually set their over state to false when changing to ignore.
Also from the [mouse filter ignore documentation](https://docs.godotengine.org/en/latest/classes/class_control.html#enum-control-mousefilter): `The control will not receive mouse movement input events...` `The control will also not receive the mouse_entered nor mouse_exited signals.`
So if the user changes the filter to ignore, we can't immediately send a mouse signal.

**Comment by kitbdev** [comment]
For your 2nd case, when a Control is hidden (or removed) and the mouse is over it or a descendant:
Currently, the mouse exit notification is sent the next time the mouse over is updated and not null, so the next time a control is hovered.
I was trying to keep it the same as when a Control is added, moved, or shown. In those cases, the mouse over only updates when a mouse event occurs.
However, when the mouse is not over another Control when the one it was over is hidden, then the situation you showed happens. 
So I think I will just update the mouse over when a hovered Control is hidden or removed.
Alternatively, I could make the Control above the one hidden/removed receive mouse enter self, even if the mouse isn't over it if we want to update only on mouse event.

This will need to be updated in some of my test cases (`Mouse Enter/Exit notification when hiding the hovered Control` and `Mouse Enter/Exit notification when removing the hovered Control`) where I check that no Controls received mouse enter self after hiding/removing.

**Comment by kitbdev** [comment]
Updated to handle hiding/removing Controls when the mouse was over a descendant where the mouse was no longer over a Control now updating properly.

The mouse over updates the next time a mouse event occurs.
If we do want to update the mouse over immediately when a Control is hidden or removed it should also update when it is shown, added, and maybe when it is moved. This could be done in a separate PR.

**Comment by Sauermann** [comment]
> Yes, since this is how it works with mouse events in `_gui_input`.

That is good. Also it is consistent with previous behavior.

> For changing mouse filter to/from ignore while the mouse is over it or a descendant (your 1st, 3rd, and 4th cases):
> 
> I consider this intended, since setting the mouse filter to ignore means it should not receive any notifications or signals. If the user is tracking the mouse over state and changing the mouse filter to/from ignore, they should expect this behavior or manually set their over state to false when changing to ignore.

I see the following problems with this approach:
1. It requires the user to take care of the mouse-over-state, while it could be done automatically by listening to the signals from the engine. That makes it less user-friendly.
2. With the PR in its current form, the following behavior is introduced: It is possible (4th case) that a Control node receives a mouse-exited signal, without having received a mouse-entered signal previously. I would consider it a bug, that a mouse-exited signal can happen before a mouse-entered signal.

> Also from the [mouse filter ignore documentation](https://docs.godotengine.org/en/latest/classes/class_control.html#enum-control-mousefilter): `The control will not receive mouse movement input events...` `The control will also not receive the mouse_entered nor mouse_exited signals.`
> So if the user changes the filter to ignore, we can't immediately send a mouse signal.

In my opinion, the description leaves room for interpretation. The description can be interpreted as: "after the successful change of the mouse-filter to ignore, the control will not receive entered/exited signals." But during the process of changing the filter from pass to ignore, the signals can be received.

> I was trying to keep it the same as when a Control is added, moved, or shown. In those cases, the mouse over only updates when a mouse event occurs, such as a mouse movement.

The current behavior is not very robust, and considered a bug (see #40012). See also #78017, which fixed this behavior for Node2D physics nodes. The Control node case is more complex (as seen in #66625) and needs some additional changes before that can be implemented.

> Updated to handle hiding/removing Controls when the mouse was over a descendant not updating until the mouse was over a Control. This fixes the 2nd case in the testing project (bottom left corner).

I can confirm this improvement. Now, just like in the Control-movement case, an additional mouse-move is necessary to cause the mouse-exited signal.

> If do we update on hide/remove then some test cases will need to be updated (`Mouse Enter/Exit notification when hiding the hovered Control` and `Mouse Enter/Exit notification when removing the hovered Control`) where I check that no Controls received mouse enter self after hiding/removing.

Thanks for the info, I will keep it in mind for this situation.

> If we do want to update the mouse over immediately when a Control is hidden or removed it should probably also update when it is shown, added, and maybe when it is moved. This could be done in a separate PR.

That change should be postponed until after #40012 gets fixed, so the current handling of hiding nodes is fine.

**Comment by kitbdev** [comment]
I was thinking `MOUSE_FILTER_IGNORE` could be used as a way to have more control over mouse enter/exit notifications, but I'm not sure there is any use case for having exit called before enter or getting enter called multiple times in a row. In the editor, `set_mouse_filter` is only ever called when a Control is created and mouse enter/exit is mostly used for keeping track of mouse over state.

I noticed Mouse Enter/Exit Self handles `MOUSE_FILTER_IGNORE` like you are suggesting and keeping track of the mouse over state seems more important, so I will update to handle mouse filter ignore differently. 

I will also add a note to clarify on the Control  `MOUSE_FILTER_IGNORE` docs:
`[b]Note:[/b] If the Control has received [signal mouse_enter] but not [signal mouse_exit], changing the [member mouse_filter] to [constant MOUSE_FILTER_IGNORE] will cause [signal mouse_exit] to be emitted.`

**Comment by kitbdev** [comment]
Changed to send `MOUSE_EXIT` when changing a Control to `MOUSE_FILTER_IGNORE`, and send  `MOUSE_ENTER` when changing a Control to not be `MOUSE_FILTER_IGNORE` while the mouse is over it or a descendant.
This fixes the remaining cases (1,3,4) from the testing project.

Added test case "[Viewport][GuiInputEvent] Mouse Enter/Exit notification when changing the mouse filter to ignore."

Changing the `MOUSE_FILTER_IGNORE` behavior made handling each possible case individually in `_gui_update_mouse_over` more complex, so instead I revamped it to just rebuild the mouse over hierarchy. This should be easier to maintain than having separate cases, and can be used if anything else needs to change the mouse_over_hierarchy structure.

When hovering a control and changing it to `MOUSE_FILTER_IGNORE`, it will receive `MOUSE_EXIT_SELF` immediately. Its parent won't receive `MOUSE_ENTER_SELF` until the next mouse event. If changing a control from `MOUSE_FILTER_IGNORE` and the mouse would be directly over it, `MOUSE_ENTER_SELF` won't be received until the next mouse event. Changing these can also be postponed until after #40012.

**Comment by Sauermann** [comment]
Great work on that, thanks!

I have tested the latest changes and I found only one strange case:

https://github.com/godotengine/godot/assets/6299227/f5183387-4fa6-4e30-b252-8ecd1a898d6e

Testing project: "Switch between Stop and Ignore"
1. Have the middle Control set to Stop
2. Move the mouse cursor over the middle Control, so that it isn't over the top-Control
3. press SPACE to switch from Stop to Ignore
4. Now the top Control receives a mouse-entered notification, even though the mouse is not over the top-Control

**Comment by akien-mga** [comment]
CC @mrTag if you could help test that it solves your issues too.

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -2442,6 +2442,94 @@ void Viewport::_gui_remove_control(Control *p_control) {
...
+
+void Viewport::_gui_update_mouse_over() {
+	if (gui.mouse_over == nullptr || gui.mouse_over_hierarchy.is_empty()) {
+		return;
+	}
+
+	// Rebuild the mouse over hierarchy.
+	LocalVector<Control *> new_mouse_over_hierarchy;
+	LocalVector<Control *> needs_enter;
+	LocalVector<int> needs_exit;
```
Comment (RandomShaper) [inline scene/main/viewport.cpp:2457]: We may want to avoid allocations in such a hot function. @Sauermann has an idea on maybe using just references to nodes at the ends of the chain. Maybe the other vector needs something else. This is just an idea about optimization, not meant as a blocker for this PR in any case.

File: doc/classes/Control.xml [hunk 3]
```diff
@@ -1150,12 +1150,24 @@
...
+			Sent when the mouse cursor leaves the control's (and all child control's) visible area, that is not occluded behind other Controls or Windows, provided its [member mouse_filter] lets the event reach it and regardless if it's currently focused or not.
+			[b]Note:[/b] [member CanvasItem.z_index] doesn't affect, which Control receives the notification.
+			See also [constant NOTIFICATION_MOUSE_EXIT_SELF].
+		</constant>
+		<constant name="NOTIFICATION_MOUSE_ENTER_SELF" value="60">
+			Sent when the mouse cursor enters the control's visible area, that is not occluded behind other Controls or Windows, provided its [member mouse_filter] lets the event reach it and regardless if it's currently focused or not.
+			[b]Note:[/b] [member CanvasItem.z_index] doesn't affect, which Control receives the notification.
+			See also [constant NOTIFICATION_MOUSE_ENTER].
+		</constant>
+		<constant name="NOTIFICATION_MOUSE_EXIT_SELF" value="61">
```
Comment (akien-mga) [inline doc/classes/Control.xml:1167]: We discussed with the Input team that these could be documented as experimental for the time being - in case we figure out later that this isn't a good addition to the API, so it could be removed / refactored further.
```suggestion
		<constant name="NOTIFICATION_MOUSE_ENTER_SELF" value="60" is_experimental="true">
			Sent when the mouse cursor enters the control's visible area, that is not occluded behind other Controls or Windows, provided its [member mouse_filter] lets the event reach it and regardless if it's currently focused or not.
			[b]Note:[/b] [member CanvasItem.z_index] doesn't affect, which Control receives the notification.
			See also [constant NOTIFICATION_MOUSE_ENTER].
		</constant>
		<constant name="NOTIFICATION_MOUSE_EXIT_SELF" value="61" is_experimental="true">
```

**Comment by mrTag** [comment]
I just tested this PR with our game and can confirm: mouse_enter/exit works as expected and our tooltips are not broken anymore.
Great work! Thank you!

File: scene/main/viewport.cpp (hunk 2 above)
Comment (kitbdev) [reply scene/main/viewport.cpp:2457]: I'm not sure this function is very hot. It is only called when `set_top_level()` or `set_mouse_filter()` is called, and only executed if the mouse is over something.
If we want I can add a guard before the allocations that is similar to the loop below it but smaller.

**Comment by kitbdev** [comment]
Updated to add `is_experimental` to the *_self notifications, and fix a comma.

Unrelated: The Control documentation seems to use `control` `Control` `[Control]` `the node` and `this node` interchangeably.

File: scene/main/viewport.cpp (hunk 2 above)
Comment (kitbdev) [reply scene/main/viewport.cpp:2457]: Also the `mouse_over_hierarchy` contains a list of all nodes that have gotten `mouse_entered` but still need a `mouse_exited`. If we change this to only store the ends, we wouldn't be able to update properly when the mouse filter ignore is set.

**Review by akien-mga — APPROVED** [review]
We reviewed this early today with the input team and approved it for merging. It seems to be a pretty thorough solution with extensive unit testing.

We had some doubts on whether the `ENTER_SELF` and `EXIT_SELF` notifications are needed, which is why they're now marked as experimental. The engine itself doesn't use them, so we can see if users start making good use of the additional functionality or if they find it too confusing.

**Comment by akien-mga** [comment]
Thanks @kitbdev and @Sauermann!

Amazing work fixing a critical regression so fast during the beta stage :)

**Comment by Sauermann** [comment]
Thanks @kitbdev for putting so much effort into this!

**Comment by dobin** [comment]
Is this already in 4.2, or later?

**Comment by KoBeWi** [comment]
It's in 4.2.
