### PR TITLE
Only update inspector if configuration warning change was relevant (reverted)

### LINKED ISSUE #88176: Can't write Label text
### Tested versions

Regression from #68420

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/a4a50655-3777-495f-894a-1c21fb9e704d

This is caused by Label calling `update_configuration_warnings()` in `set_text()`:
https://github.com/godotengine/godot/blob/4e990cd7e51d17cf24f854cc33b2715eaa27200f/scene/gui/label.cpp#L909
Which since #68420 will cause inspector update.

I somehow overlooked it while reviewing, I think there should be a separate warning signal that causes inspector update.
CC @RedMser 

### Steps to reproduce

1. Add Label
2. Change `text` property

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #88294: `SpinSlider`s can't be dragged on some nodes
### Tested versions

Reproducible in master: v4.3.dev.custom_build [e92d55bbf]
**Not** reproducible in v4.2.1.stable.official [b09f793f5]

### System information

macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

For some reason sliders are undraggable on some nodes because they immediately stop being dragged after one frame:

https://github.com/godotengine/godot/assets/60579014/8d3eb35f-fc9e-4bd3-8b82-e108e13c8509

This doesn't happen in 4.2:

https://github.com/godotengine/godot/assets/60579014/2b3cb29f-c723-414f-8894-7bec79fdbc5c

### Steps to reproduce

Create a DirectionalLight3D node and drag any of its transform properties

What's interesting is that it doesn't happen for any node, for example there's no issue when trying to do this with `MeshInstance3D`, but there's an issue with `DirectionalLight3D`. And I saw that in some other nodes too

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by RedMser**
1. Keeps track of the node's property configuration warnings. If one got added, changed or removed by the latest `update_configuration_warnings()` call, only then will the inspector be forced to update.
2. Ignores config warnings that don't have a property associated, so these will never update the inspector.

This currently does another call to `Node::get_configuration_warnings()`. As a possible optimization, we could propagate this cached information from the EditorInspector to the EditorProperty as well. Not necessary for the fix though, and usually config warnings should be fast to evaluate.

Fixes #88176

* *Bugsquad edit, fixes: #88294*

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -4050,8 +4053,48 @@ void EditorInspector::_node_removed(Node *p_node) {
...
+		if (found_warning_index < 0) {
+			found_warning_index = property_configuration_warnings.size();
+			property_configuration_warnings.push_back(warning);
+			changed = true;
+		}
+		found_warning_indices.push_back(found_warning_index);
+	}
+
+	// Removed warnings.
+	for (uint32_t i = 0; i < property_configuration_warnings.size(); i++) {
```
Comment (Mickeon) [inline editor/editor_inspector.cpp:4089]: Why is this specifically `uint32_t`?

Comment (RedMser) [reply editor/editor_inspector.cpp:4089]: It was `int` at the beginning but I got a compiler warning which caused the CI pipeline to fail. I think it's because of using LocalVector, not sure if I should just switch it out to Vector instead...

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
