### PR TITLE
Prevent creating any type of file with a leading dot

### LINKED ISSUE #62497: A scene name can be empty (`.tscn`), leading to confusion in the list of open scenes and sometimes disappearing from the FileSystem dock
### Godot version

4.0.alpha10 (likely applies to 3.x too)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

Godot editor allows you to save a file with no name but an extension, such as `.tscn` or `.scn`. The result is that the scene will appear to have no name in the list of open scenes, which can look confusing. On top of that, the scene file will sometimes disappear and reappear in the FileSystem dock.

image

I suggest not allowing empty names for saved scenes in the editor – the lefthand side (without the extension) should be at least 1 character long.

### Steps to reproduce

- Create a new scene and add any node.
- Press <kbd>Ctrl + S</kbd> to save the scene, and change its name to `.tscn` or `.scn`.
- Notice how the scene will not have any name (as the file extension is trimmed), and it will intermittently disappear from the FileSystem dock.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by SekoiaTree**
Fixes https://github.com/godotengine/godot/issues/62497, ports https://github.com/godotengine/godot/pull/62940 to master. Tested with every filesystem dock option, as well as saving resources and scenes from other docks.

Co-authored-by: gotnospirit <gotnospirit@gmail.com>

### CODE REVIEW

**Comment by AThousandShips** [comment]
Since this is a port I'd say adding the original author as co-author is appropriate

**Comment by SekoiaTree** [comment]
Sure! How do I do that?

**Comment by AThousandShips** [comment]
Add
```
Co-authored-by: Name <Email>
```
Get the details from the original PR commit

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1760,6 +1760,9 @@ void FileSystemDock::_duplicate_operation_confirm() {
 	} else if (new_name.contains("/") || new_name.contains("\\") || new_name.contains(":")) {
 		EditorNode::get_singleton()->show_warning(TTR("Name contains invalid characters."));
 		return;
+	} else if (new_name.begins_with(".")) {
```
Comment (AThousandShips) [inline editor/filesystem_dock.cpp:1763]: Here too

File: editor/scene_create_dialog.cpp [hunk 2]
```diff
@@ -103,6 +103,8 @@ void SceneCreateDialog::update_dialog() {
 
 	if (validation_panel->is_valid() && !scene_name.is_valid_filename()) {
 		validation_panel->set_message(MSG_ID_PATH, TTR("File name invalid."), EditorValidationPanel::MSG_ERROR);
+	} else if (validation_panel->is_valid() && scene_name.begins_with(".")) {
```
Comment (AThousandShips) [inline editor/scene_create_dialog.cpp:106]: And here

File: editor/filesystem_dock.cpp (hunk 1 above)
Comment (AThousandShips) [reply editor/filesystem_dock.cpp]: That one isn't guaranteed so I'd leave it alone

**Comment by AThousandShips** [comment]
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

And also add the co-author

File: editor/filesystem_dock.cpp [hunk 3]
```diff
@@ -1688,7 +1688,7 @@ void FileSystemDock::_rename_operation_confirm() {
 	} else if (new_name.contains("/") || new_name.contains("\\") || new_name.contains(":")) {
 		EditorNode::get_singleton()->show_warning(TTR("Name contains invalid characters."));
 		rename_error = true;
-	} else if (new_name.begins_with(".")) {
+	} else if (new_name[0] == '.')) {
```
Comment (AThousandShips) [inline editor/filesystem_dock.cpp:1691]:
```suggestion
	} else if (new_name[0] == '.') {
```

**Comment by SekoiaTree** [comment]
@gotnospirit I need your email to add you as coauthor, but I can't find it anywhere :/

**Comment by SekoiaTree** [comment]
Squashed commits. For co-author, I can't find the email anywhere. There's a noreply address from github somewhere, but idk what it is either.

**Comment by KoBeWi** [comment]
You can get the author's email from commit's patch
https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/62940.patch

**Comment by SekoiaTree** [comment]
Yep, found that immediately after... Sorry!

File: editor/directory_create_dialog.cpp [hunk 4]
```diff
@@ -51,13 +51,17 @@ String DirectoryCreateDialog::_validate_path(const String &p_path) const {
 		return TTR("Folder name cannot be empty.");
 	}
 
+	if (p_path.contains("\\") || p_path.contains(":") || p_path.contains("*") ||
+			p_path.contains("|") || p_path.contains(">") || p_path.ends_with(".") || p_path.ends_with(" ")) {
```
Comment (KoBeWi) [inline editor/directory_create_dialog.cpp:55]: Why the name can't end with `.`?
Also `" "` is irrelevant, because the dialog does `strip_edges()` before creating the folder.

Comment (SekoiaTree) [reply editor/directory_create_dialog.cpp:55]: This isn't my code afaik, it's because it hasn't been rebased in a bit.

I'll rebase and edit in an hour or two.

Comment (KoBeWi) [reply editor/directory_create_dialog.cpp:55]: Inside the loop it checks parts separated with `/`, e.g. `path/to/directory/somewhere`. It makes sense that the middle elements shouldn't have dots/spaces.

Comment (SekoiaTree) [reply editor/directory_create_dialog.cpp:55]: It doesn't do anything different though, because inside the loop it still used p_path. Unless there's some weird in-place stuff I'm unaware of, seems to me it does the exact same thing (it doesn't use part)

Comment (KoBeWi) [reply editor/directory_create_dialog.cpp:55]: Well, that looks like a bug 🙃

Comment (SekoiaTree) [reply editor/directory_create_dialog.cpp:55]: I'll fix it so that each part can't end with a dot or a space?

Comment (KoBeWi) [reply editor/directory_create_dialog.cpp:55]: Not sure about dot tbh, as it's valid to use, but space shouldn't be allowed.

Comment (KoBeWi) [reply editor/directory_create_dialog.cpp]: Might be worth checking for a space at the beginning too.

**Review by KoBeWi — APPROVED** [review]

File: editor/directory_create_dialog.cpp (hunk 4 above)
Comment (SekoiaTree) [reply editor/directory_create_dialog.cpp]: It now does that too

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Can't be cherry-picked, unfortunately, as it depends on https://github.com/godotengine/godot/pull/78744. Can likely be redone for 4.1, but it's not extremely important.
