### PR TITLE
[.NET] Add caching for dotnet TFM validation result

### LINKED ISSUE #104285: [.Net] Long freeze when clicking the `Android` export template with projects that have lots of gdignored files
### Tested versions

Reproducible: v4.4.stable.mono.official [4c311cbee]
Not reproducible: v4.4.stable.official [4c311cbee]

### System information

Godot v4.4.stable.mono - Windows 10 (build 19044) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.7270) - AMD Ryzen 9 5900HS with Radeon Graphics (16 threads)

### Issue description

If a project has many `gdignore`d files, the editor will freeze for a long time when clicking the `Android` export template button.

https://github.com/user-attachments/assets/dd8ff601-0711-4c5e-8a80-6c84085453f9

### Steps to reproduce

1. Download the MRP
2. Open the project with godot 4.4 mono version
3. Build the C# project
4. Restart the project
5. Open the export menu
6. Click the Android export template
7. Observe the issue

### Minimal reproduction project (MRP)

> **Note**
> Since GitHub has a size limit, I have to lower the count of the gdignored files to 30,000; the actual MRP contains 1,000,000 random binary files, each with a Guid as the file content.

[mrp_slowloadtime.zip](https://github.com/user-attachments/files/19296449/mrp_slowloadtime.zip)

You may procedurally generate these files by the following code:

```csharp
const int files = 1_000_000;

var task = new List<Task>(files);

for (var i = 0; i < files; i++)
{
    var localI = i;
    task.Add(
        Task.Run(
            async () =>
            {
                var randomPayload = Guid.NewGuid().ToByteArray();
                var fileStream = File.Create($@"PATH-TO-THE-MRP\IgnoredDir\RandomFile-{localI:00000}", randomPayload.Length);
                await fileStream.WriteAsync(randomPayload);
                await fileStream.DisposeAsync();
            }
        )
    );
}

await Task.WhenAll(task);
```

### PR DESCRIPTION
**Pull request by zaevi**
- Close: #104285

After #102627, exporting Android runs `dotnet build <project.csproj> --getProperty:TargetFramework` to check the TFM. However, in export dialog, **EVERY INPUT** do trigger `has_valid_export_configuration`, which makes the interface very sticky.

This PR adds caching for TFM checks, only using command line when export dialog is first opened and when `project.csproj` is modified.

| Before   | After  |
|---------|---------|
| fix_before | fix_after |

### CODE REVIEW

**Review by raulsntos — APPROVED** [review]
Tested and works as expected. Code looks good to me too.

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2540,6 +2540,9 @@ bool EditorExportPlatformAndroid::has_valid_username_and_password(const Ref<Edit
 }
 
 #ifdef MODULE_MONO_ENABLED
+uint64_t _last_validate_tfm_time = 0;
+String _last_validate_tfm = "";
```
Comment (beicause) [inline platform/android/export/export_plugin.cpp:2544]:
```suggestion
static uint64_t _last_validate_tfm_time = 0;
static String _last_validate_tfm = "";
```
Could be `static`

Comment (zaevi) [reply platform/android/export/export_plugin.cpp]: Accepted. `static` can avoid unexpected external linkage (although this name is hard to conflict).

**Review by m4gr3d — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
