### PR TITLE
Display `BitField[Enum]` in docs to distinguish from `Enum`

### LINKED ISSUE #74593: GDScript 2.0: `ResourceSaver.save()` with using combined `SaverFlags` shows an invalid warning `INT_AS_ENUM_WITHOUT_CAST`
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, MacOS

### Issue description

I actually fixing all the warnings that popup in my plugin after remove the default exclude script checks for the addons folder.

Using `ResourceSaver.save` says:
`The flags bitmask can be specified to customize the save behavior using SaverFlags flags.`

But let the compiler do report incorrect warnings
using the flags as bitmask (`ResourceSaver.FLAG_BUNDLE_RESOURCES|ResourceSaver.FLAG_REPLACE_SUBRESOURCE_PATHS`) is popup warnings.

```
[Ignorieren]Zeile 10 (INT_AS_ENUM_WITHOUT_CAST):Integer used when an enum value is expected. If this is intended cast the integer to the enum type.
[Ignorieren]Zeile 10 (INT_AS_ENUM_WITHOUT_MATCH):Cannot pass 66 as Enum "ResourceSaver.SaverFlags": no enum member has matching value.
```

### Steps to reproduce

```gdscript
ResourceSaver.save(GDScript.new(), "res://test.gd", ResourceSaver.FLAG_BUNDLE_RESOURCES|ResourceSaver.FLAG_REPLACE_SUBRESOURCE_PATHS)
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* ~~Treat `BitField<T>` as an `int` rather than an enum `T` in GDScript.~~ Fixed by #75691.
* Change display of bitfields in Editor Help as `BitField[T]`.

I highlighted the `BitField` with a different color and added a hint, since `BitField` is not a type in GDScript.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks fairly good to me, though I'm a bit concerned about introducing the `BitField[Enum]` syntax which might be confusing, especially since it's not supported in GDScript.

For example, how would users know which type is actually returned by `button_mask` in GDScript? Is it `MouseButtonMask`, is it some `BitField[]` that would raise a syntax error if they try to use it as type hint, or is it a plain `int`?

**Comment by dalexeev** [comment]
> For example, how would users know which type is actually returned by `button_mask` in GDScript? Is it `MouseButtonMask`, is it some `BitField[]` that would raise a syntax error if they try to use it as type hint, or is it a plain `int`?

Now it is plain `int`, not `SomeEnum`.

> I'm a bit concerned about introducing the `BitField[Enum]` syntax which might be confusing

Yes, I'm a little worried about this too, so I used a different color (same as `void`) and added a tooltip. A little confusion is unavoidable, but the current state is already confusing. `ENUM_VALUE_A | ENUM_VALUE_B` is `int` in GDScript. And the `SomeEnum` type hint raises a warning when an `int` is passed to it.

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -245,6 +246,13 @@ void EditorHelp::_add_type(const String &p_type, const String &p_enum) {
 			class_desc->add_text("Array");
 			class_desc->pop();
 			class_desc->add_text("[");
+		} else if (is_bitfield) {
+			class_desc->push_color(Color(theme_cache.type_color, 0.5));
+			class_desc->push_hint(TTR("This value is a bitmask of the following flags."));
```
Comment (akien-mga) [inline editor/editor_help.cpp:251]:
```suggestion
			class_desc->push_hint(TTR("This value is integer composed as a bitmask of the following flags."));
```
Not sure that's the best phrasing, but I think we should make it explicit it's an `int`.

File: editor/editor_help.cpp [hunk 2]
```diff
@@ -245,6 +246,13 @@ void EditorHelp::_add_type(const String &p_type, const String &p_enum) {
 			class_desc->add_text("Array");
 			class_desc->pop();
 			class_desc->add_text("[");
+		} else if (is_bitfield) {
+			class_desc->push_color(Color(theme_cache.type_color, 0.5));
+			class_desc->push_hint(TTR("This value is integer composed as a bitmask of the following flags."));
```
Comment (akien-mga) [inline editor/editor_help.cpp:251]:
```suggestion
			class_desc->push_hint(TTR("This value is an integer composed as a bitmask of the following flags."));
```

**Comment by dalexeev** [comment]
Online docs uses C++ style:

<details>
<summary>Images</summary>






</details>

File: modules/gdscript/gdscript_analyzer.cpp [hunk 3]
```diff
@@ -4557,6 +4557,9 @@ GDScriptParser::DataType GDScriptAnalyzer::type_from_property(const PropertyInfo
 						result.is_constant = false;
 					}
 				}
+			} else if ((p_property.usage & PROPERTY_USAGE_CLASS_IS_BITFIELD) && p_property.class_name != StringName()) {
+				// BitField isn't supported (yet?).
+				result.is_constant = false;
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:4562]: This `else` is not needed. The only reason it sets `result.is_constant = false` here is because `make_enum_type()` makes it `true`, but in the `else` branch it is not called.

**Review by Calinou — APPROVED** [review]
Code looks good to me. I think the current style isn't too bad – we may have to iterate on it later, but it needs testing in real world conditions first :slightly_smiling_face:

**Comment by dalexeev** [comment]
Rebased. Fixed bug with using `BIND_ENUM_CONSTANT` instead of `BIND_BITFIELD_FLAG` (now the error can be found by `make_rst.py`).

https://github.com/godotengine/godot/blob/28cca66d2cfe25d6d7bf5a2a26ab7bd366029669/scene/main/node.h#L709

https://github.com/godotengine/godot/blob/28cca66d2cfe25d6d7bf5a2a26ab7bd366029669/scene/main/node.cpp#L49-L52

Is there any reason why some `VARIANT_*_CAST` are in `*.cpp` while most are in `*.h`?

`VARIANT_(ENUM|BITFIELD)_CAST` in `*.cpp` - 11 matches

```
core/io/ip.cpp: 1
 38:  1: VARIANT_ENUM_CAST(IP::ResolverStatus);
core/io/xml_parser.cpp: 1
 37:  1: VARIANT_ENUM_CAST(XMLParser::NodeType);
core/os/time.cpp: 2
 55:  1: VARIANT_ENUM_CAST(Month);
 56:  1: VARIANT_ENUM_CAST(Weekday);
scene/2d/line_2d.cpp: 3
 38:  1: VARIANT_ENUM_CAST(Line2D::LineJointMode)
 39:  1: VARIANT_ENUM_CAST(Line2D::LineCapMode)
 40:  1: VARIANT_ENUM_CAST(Line2D::LineTextureMode)
scene/main/node.cpp: 4
 49:  1: VARIANT_ENUM_CAST(Node::ProcessMode);
 50:  1: VARIANT_ENUM_CAST(Node::ProcessThreadGroup);
 51:  1: VARIANT_BITFIELD_CAST(Node::ProcessThreadMessages);
 52:  1: VARIANT_ENUM_CAST(Node::InternalMode);
```

`VARIANT_(ENUM|BITFIELD)_CAST` in `*.h` - 625 matches

**Review by akien-mga — APPROVED** [review]
Looks good to me. Needs a rebase.

**Comment by akien-mga** [comment]
Thanks!
