### PR TITLE
Fix usage of String.left()

### LINKED ISSUE #48951: Editor settings window doesn't display last letter of entry headers
**Godot version:**
Commit 3b3a55ca04331e85cc24ac315b60e7ad4aeb17df

**OS/device including version:**
Fedora 34 Workstation, Vega 64

**Issue description:**
Built the editor with LLVM/LLD following the instructions [here](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html#using-clang-and-lld-for-faster-development) and when I opened a new empty project and went to the editor settings I noticed that the settings headers are all missing the last letter of their entries.
See "Editor Languag", "Display Scal", etc. :
image

**Steps to reproduce:**

1. Open the editor
2. Open the "Editor Settings" window

### PR DESCRIPTION
**Pull request by KoBeWi**
#36180 changed behavior of negative arguments in `left()`. Previously it would return empty string. Some code relied on that behavior, so this PR fixes it.

*Bugsquad edit: This closes https://github.com/godotengine/godot/issues/48951.

### CODE REVIEW

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -939,6 +939,7 @@ const char32_t *String::get_data() const {
 }
 
 void String::erase(int p_pos, int p_chars) {
+	p_pos = MAX(p_pos, 0);
```
Comment (akien-mga) [inline core/string/ustring.cpp:942]: Should it fail on negative indices instead?

File: core/string/ustring.cpp [hunk 2]
```diff
@@ -939,6 +939,7 @@ const char32_t *String::get_data() const {
...
 	*this = left(p_pos) + substr(p_pos + p_chars, length() - ((p_pos + p_chars)));
```
Comment (kleonc) [inline core/string/ustring.cpp:943]:
```suggestion
	*this = left(MAX(p_pos, 0)) + substr(p_pos + p_chars, length() - ((p_pos + p_chars)));
```
Since only `left()` was changed shouldn't it be like this to restore previous behavior?

File: core/string/ustring.cpp (hunk 1 above)
Comment (KoBeWi) [reply core/string/ustring.cpp:942]: I could change it to fail, I just wanted to preserve the previous behavior.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
