### PR TITLE
Fix opening found lines in built-in scripts

### LINKED ISSUE #75600: Opening built-in script line can fail sometimes
### Godot version

4.0.2 rc

### System information

Windows 10 x64

### Issue description

#74401 introduced a great feature, but I found a case where it fails in less than a minute of using it 🙃
I didn't investigate why exactly it fails. I attached MRP.

CC @stms

### Steps to reproduce

1. Put the MRP scene into any project
2. Do "Search in Files" for `on_dead`
3. Click the result
4. Wrong script is opened
5. `scene\gui\code_edit.cpp:1586 - Index p_line = -63 is out of bounds (get_line_count() = 10).` is printed

### Minimal reproduction project

[CrystalAccess.tscn.txt](https://github.com/godotengine/godot/files/11133234/CrystalAccess.tscn.txt)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #75600

The fix was actually very easy. When a line is found in a built-in script, it will be a specific line in the scene file. That line will always be preceded by a script header from the script it's part of. So I just made the editor crawl upwards until the header, which allows to determine the correct script. Previously the scanning was done from the top and it only found the first script or whatever.

For some reason, clicking the line if script editor is not visible, will not jump to that line. You have to click again. Not sure how to fix that, as using deferred call does not help. It's not that important though, code search is usually done from within script editor anyway.

### CODE REVIEW

File: editor/script/script_editor_plugin.cpp [hunk 1]
```diff
@@ -4020,69 +4020,43 @@ void ScriptEditor::_on_find_in_files_result_selected(const String &fpath, int li
...
 				if (scr.is_valid()) {
 					edit(scr);
 					ScriptTextEditor *ste = Object::cast_to<ScriptTextEditor>(_get_current_editor());
 
 					if (ste) {
-						EditorInterface::get_singleton()->set_main_screen_editor("Script");
-						ste->goto_line_selection(line_number, begin, end);
+						callable_mp(EditorInterface::get_singleton(), &EditorInterface::set_main_screen_editor).call_deferred("Script");
+						if (line_number == 0) {
+							const int source_len = String(source_header).length();
```
Comment (AThousandShips) [inline editor/script/script_editor_plugin.cpp]:
```suggestion
							const int source_len = strlen(source_header);
```

File: editor/script/script_editor_plugin.cpp [hunk 2]
```diff
@@ -4020,69 +4020,43 @@ void ScriptEditor::_on_find_in_files_result_selected(const String &fpath, int li
...
+			const char *scr_header = "[sub_resource type=\"GDScript\" id=\"";
+			const char *source_header = "script/source = \"";
+			String script_id;
+
+			// Search the scene backwards from the found line.
+			int scan_line = line_number - 1;
+			while (scan_line >= 0) {
+				const String &line = lines[scan_line];
+				if (line.begins_with(source_header)) {
+					line_number -= scan_line + 1;
```
Comment (HolonProduction) [inline editor/script/script_editor_plugin.cpp:4052]:
```suggestion
                    // Adjust line relative to the script beginning.
					line_number -= scan_line + 1;
```

File: editor/script/script_editor_plugin.cpp [hunk 3]
```diff
@@ -4020,69 +4020,43 @@ void ScriptEditor::_on_find_in_files_result_selected(const String &fpath, int li
...
 					if (ste) {
-						EditorInterface::get_singleton()->set_main_screen_editor("Script");
-						ste->goto_line_selection(line_number, begin, end);
+						callable_mp(EditorInterface::get_singleton(), &EditorInterface::set_main_screen_editor).call_deferred("Script");
+						if (line_number == 0) {
+							const int source_len = strlen(source_header);
+							ste->goto_line_selection(line_number, begin - source_len, end - source_len);
+						} else {
+							ste->goto_line_selection(line_number, begin, end);
+						}
```
Comment (HolonProduction) [inline editor/script/script_editor_plugin.cpp:4074]: This looks pretty fragile to me in terms of history management because it could trigger another history entry on top of the one introduced by `edit`.

I can't exactly prove it without https://github.com/godotengine/godot/pull/113619 though. And given that it was done like this before it should be fine for this PR.

File: editor/script/script_editor_plugin.cpp [hunk 4]
```diff
@@ -4020,69 +4020,43 @@ void ScriptEditor::_on_find_in_files_result_selected(const String &fpath, int li
...
-				} while (!f->eof_reached());
+			const PackedStringArray lines = FileAccess::get_file_as_string(fpath).split("\n");
+			if (line_number > lines.size()) {
+				return;
+			}
 
-				if (line_number > scr_start_line + scr_line_count) {
-					// Find in another built-in GDScript.
-					continue;
+			const char *scr_header = "[sub_resource type=\"GDScript\" id=\"";
```
Comment (HolonProduction) [inline editor/script/script_editor_plugin.cpp:4042]: Not a c++ expert but shouldn't this stuff be `constexpr`?

**Review by HolonProduction — APPROVED** [review]
Fixes the linked issue in my testing.

Approach of the fix makes sense to me.

File: editor/script/script_editor_plugin.cpp (hunk 4 above)
Comment (KoBeWi) [reply editor/script/script_editor_plugin.cpp:4042]: It doesn't compile with `constexpr`.

**Comment by Repiteo** [comment]
Thanks!
