### PR TITLE
Fix uint's suffix is not highlighted in text shader editor

### LINKED ISSUE #75161: Unsigned int suffix not highlighted in shader editor
### Godot version

4.0.1

### System information

Windows 10 x64

### Issue description

image

### Steps to reproduce

1. Create shader
2. Add `uint`, e.g. `4u`

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #75161

`GDShaderSyntaxHighlighter` uses `CodeHighlighter` which doesn't recognize this suffix syntax, there are other ways to fix this, IMHO add a bool in the base class to distinguish the behaviour is the one introduces least change.

### CODE REVIEW

**Review by Chaosus — APPROVED** [review]
Seems fine and should work.

File: scene/resources/syntax_highlighter.cpp [hunk 1]
```diff
@@ -617,6 +617,10 @@ void CodeHighlighter::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::DICTIONARY, "color_regions"), "set_color_regions", "get_color_regions");
 }
 
+void CodeHighlighter::set_use_uint_suffix(bool p_use) {
+	use_uint_suffix = p_use;
+}
```
Comment (Chaosus) [inline scene/resources/syntax_highlighter.cpp:622]:
```suggestion
void CodeHighlighter::set_uint_suffix_enabled(bool p_enabled) {
	uint_suffix_enabled = p_enabled;
}
```

File: scene/resources/syntax_highlighter.h [hunk 2]
```diff
@@ -93,6 +93,8 @@ class CodeHighlighter : public SyntaxHighlighter {
 	Color symbol_color;
 	Color number_color;
 
+	bool use_uint_suffix = false;
```
Comment (Chaosus) [inline scene/resources/syntax_highlighter.h:96]:
```suggestion
	bool uint_suffix_enabled = false;
```

File: scene/resources/syntax_highlighter.h [hunk 3]
```diff
@@ -139,6 +141,8 @@ class CodeHighlighter : public SyntaxHighlighter {
 
 	void set_member_variable_color(Color p_color);
 	Color get_member_variable_color() const;
+
+	void set_use_uint_suffix(bool p_use);
```
Comment (Chaosus) [inline scene/resources/syntax_highlighter.h:145]:
```suggestion
	void set_uint_suffix_enabled(bool p_enabled);
```

File: scene/resources/syntax_highlighter.cpp [hunk 4]
```diff
@@ -303,7 +303,7 @@ Dictionary CodeHighlighter::_get_line_syntax_highlighting_impl(int p_line) {
 		}
 
 		// Check for dot or underscore or 'x' for hex notation in floating point number or 'e' for scientific notation.
-		if ((str[j] == '.' || str[j] == 'x' || str[j] == '_' || str[j] == 'f' || str[j] == 'e') && !in_word && prev_is_number && !is_number) {
+		if ((str[j] == '.' || str[j] == 'x' || str[j] == '_' || str[j] == 'f' || str[j] == 'e' || (use_uint_suffix && str[j] == 'u')) && !in_word && prev_is_number && !is_number) {
```
Comment (Chaosus) [inline scene/resources/syntax_highlighter.cpp:306]:
```suggestion
		if ((str[j] == '.' || str[j] == 'x' || str[j] == '_' || str[j] == 'f' || str[j] == 'e' || (uint_suffix_enabled && str[j] == 'u')) && !in_word && prev_is_number && !is_number) {
```

File: editor/plugins/text_shader_editor.cpp [hunk 5]
```diff
@@ -330,6 +330,8 @@ void ShaderTextEditor::_load_theme_settings() {
 		warnings_panel->add_theme_font_override("normal_font", EditorNode::get_singleton()->get_editor_theme()->get_font(SNAME("main"), EditorStringName(EditorFonts)));
 		warnings_panel->add_theme_font_size_override("normal_font_size", EditorNode::get_singleton()->get_editor_theme()->get_font_size(SNAME("main_size"), EditorStringName(EditorFonts)));
 	}
+
+	syntax_highlighter->set_use_uint_suffix(true);
```
Comment (Chaosus) [inline editor/plugins/text_shader_editor.cpp:334]:
```suggestion
	syntax_highlighter->set_uint_suffix_enabled(true);
```

**Review by Chaosus — CHANGES_REQUESTED** [review]
Added several suggestions, also `set_uint_suffix_enabled` might be an open method, but this can be fixed in another PR.

File: scene/resources/syntax_highlighter.cpp (hunk 1 above)
Comment (jsjtxietian) [reply scene/resources/syntax_highlighter.cpp:622]: Thanks!

**Review by Chaosus — APPROVED** [review]
LGTM

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: scene/resources/syntax_highlighter.h [hunk 6]
```diff
@@ -139,6 +141,8 @@ class CodeHighlighter : public SyntaxHighlighter {
 
 	void set_member_variable_color(Color p_color);
 	Color get_member_variable_color() const;
+
+	void set_uint_suffix_enabled(bool p_enabled = true);
```
Comment (Calinou) [inline scene/resources/syntax_highlighter.h:145]: I'm curious as to why this setter has a default parameter. We generally don't use default parameters for setter methods by convention.

Comment (jsjtxietian) [reply scene/resources/syntax_highlighter.h:145]: I just followed @Chaosus 's suggestion for this, in this case looks like explicit is better
