### PR TITLE
Fix error when dragging non-resource file

### LINKED ISSUE #89996: Moving text-files results in "No loader found for resource"
### Tested versions

- Reproducible in: v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When moving .txt files (or any other text file), the following log prints on *begin drag* `No loader found for resource: res://folder_a/file.txt (expected type: )`.

Note: Although this can be reproduced in a blank project, it's also possible to reproduce by creating a custom control which implementing the related drag functions, and returning your own synthetic move order: `{"type": "files", "files":[...]}`. If this contains a text file, the log ALSO prints when the drag *begins*.

### Steps to reproduce

Create a .txt file in any folder. Drag+drop the file from one place to another. View console log.

The MRP contains two folders, and a txt file for your convenience.

### Minimal reproduction project (MRP)

[no_loader_found.zip](https://github.com/godotengine/godot/files/14795966/no_loader_found.zip)

### LINKED ISSUE #101461: Drag text files in filesystem makes the engine throw the error `No loader found for resource: "file_path" (expected type: )`
### Tested versions

- Reproducible: Between v4.0.beta2.official [f8745f2f7] ~ v4.0.beta8.official [45cac42c0] and from v4.0.beta11.official [91713ced8] upwards

- Not reproducible: v4.0.beta1.official [20d667284] and lower and between v4.0.beta9.official [e780dc332] ~ v4.0.beta10.official [d0398f62f]

### System information

Godot v4.4.dev (abf8e1e6f) - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21921.1000) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

As the title says, dragging a text file in the editor raises the pointed error, json files seems to be the exception. Also, open the text file stops the error for the file opened until you restart the editor, the others will keep raising the error until you open them.

https://github.com/user-attachments/assets/de2c1e94-f6c4-4d90-8d87-97e499d6ea55

<br>

Bisecting points the pr #62413 (in 4.0 beta 2) as the one that introduced this issue. Pr #68498 (in 4.0 beta 9) made the error stop but had to be reverted in 4.0 beta 11 because introduced other regressions:

Image

<br>

CC @willnationsdev

### Steps to reproduce

Drag a txt file in the filesystem.

### Minimal reproduction project (MRP)

Not necessary, any project with a txt file can reproduce.

### PR DESCRIPTION
**Pull request by Changryy**
Fixes #89996
Fixes #101461

When dragging a file the editor now checks if the file can be loaded as a resource before trying to load it.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

I've tested drag-and-drop of resources with automatic conversion (e.g. dropping a `.jpg` onto a property that expects a BaseMaterial3D) and it still works.

File: editor/inspector/editor_resource_picker.cpp [hunk 1]
```diff
@@ -737,9 +737,10 @@ bool EditorResourcePicker::_is_drop_valid(const Dictionary &p_drag_data) const {
 	} else if (drag_data.has("type") && String(drag_data["type"]) == "files") {
 		Vector<String> files = drag_data["files"];
 
-		// TODO: Extract the typename of the dropped filepath's resource in a more performant way, without fully loading it.
```
Comment (KoBeWi) [inline editor/inspector/editor_resource_picker.cpp:740]: The TODO doesn't seem resolved? Why remove it?

Comment (Changryy) [reply editor/inspector/editor_resource_picker.cpp:740]: My bad. I misinterpreted it as wanting to check if the file is a resource before loading it, which is what the code now does. But I see now that what the TODO actually meant is to avoid loading the resource altogether in favour of finding out the resource type and using that instead

Comment (Changryy) [reply editor/inspector/editor_resource_picker.cpp:740]: Thank you for pointing it out. I have added the TODO back

**Comment by Repiteo** [comment]
Thanks!

**Comment by Goury** [comment]
Doesn't fix the problem on exporting
