### PR TITLE
[Core] Fix sharing of typed arrays from constructor

### LINKED ISSUE #89191: C++ A deep copy (COW) of TypedArray is sometimes incorrectly made
### Tested versions

Reproducible on 7d2ca2d8ac49cde9767e00b70f9eaf1920eb266d and also on 4.2-stable 46dc277917a93cbf601bbcf0d27d00f6feeec0d5

### System information

Godot v4.3.dev (7d2ca2d8a) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When casting from `TypedArray` to `Array` and back again, a deep copy (COW) will be performed. This seems to also affect nested `Array` occurrences, thus making it impossible(?) to extract a reference to a `TypedArray` as a `TypedArray` from an `Array` or `TypedArray`.

### Steps to reproduce

A simple example is the following. Even though `untypedArray` in this example knows that it is, internally, a typed array, it will still perform a COW deep copy.

```C++
TypedArray<int> typedArray;
typedArray.push_back(1);

Array untypedArray = typedArray;
TypedArray<int> typedArrayCopy = untypedArray; // COW

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

WARN_PRINT(typedArray[0]); // Prints 2
WARN_PRINT(untypedArray[0]); // Prints 2
WARN_PRINT(typedArrayCopy[0]); // Prints 3
```

This behaviour arguably becomes more problematic when dealing with nested `Array` scenarios:

```C++
TypedArray<int> typedArray;
typedArray.push_back(1);

Array parentArray;
parentArray.push_back(typedArray);

Array untypedArray = parentArray[0];
TypedArray<int> typedArrayCopy = parentArray[0];

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

WARN_PRINT(typedArray[0]); // Prints 2
WARN_PRINT(untypedArray[0]); // Prints 2
WARN_PRINT(typedArrayCopy[0]); // Prints 3
```

This second example demonstrates that it is difficult (and maybe impossible?) to extract a `TypedArray` from an `Array` (or `TypedArray`) and put it back into a `TypedArray` container without doing a COW that may not be desirable.

### GDScript
This behaviour does **not** affect GDScript. In GDScript, I can do the following and a COW deep copy will never occur:
```GDScript
var typedArray: Array[int];
typedArray.push_back(1);

var untypedArray: Array = typedArray;
var typedArrayCopy: Array[int] = untypedArray;

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

print(typedArray[0]); # Prints 3
print(untypedArray[0]); # Prints 3
print(typedArrayCopy[0]); # Prints 3
```

```GDScript
var typedArray: Array[int];
typedArray.push_back(1);

var parentArray: Array;
parentArray.push_back(typedArray);

var untypedArray: Array = parentArray[0];
var typedArrayCopy: Array[int] = parentArray[0];

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

print(typedArray[0]); # Prints 3
print(untypedArray[0]); # Prints 3
print(typedArrayCopy[0]); # Prints 3
```

### Minimal reproduction project (MRP)

(See above code snippets. Put them in something that you know will be called in the engine like `register_core_singletons()` of `register_core_types.cpp`)

### PR DESCRIPTION
**Pull request by AThousandShips**
This matches the copy constructor of `Array` when same typed, which I'd say is expected behavior

* Closes: https://github.com/godotengine/godot/issues/89191

### CODE REVIEW

File: core/variant/typed_array.h [hunk 1]
```diff
@@ -46,10 +46,15 @@ class TypedArray : public Array {
 		_ref(p_array);
 	}
 	_FORCE_INLINE_ TypedArray(const Variant &p_variant) :
-			Array(Array(p_variant), Variant::OBJECT, T::get_class_static(), Variant()) {
+			TypedArray(Array(p_variant)) {
```
Comment (AThousandShips) [inline core/variant/typed_array.h:49]: Simplified this by delegating to avoid copying code

File: core/variant/typed_array.h [hunk 2]
```diff
@@ -46,10 +46,15 @@ class TypedArray : public Array {
...
 	}
-	_FORCE_INLINE_ TypedArray(const Array &p_array) :
-			Array(p_array, Variant::OBJECT, T::get_class_static(), Variant()) {
+	_FORCE_INLINE_ TypedArray(const Array &p_array) {
+		set_typed(Variant::OBJECT, T::get_class_static(), Variant());
```
Comment (AThousandShips) [inline core/variant/typed_array.h:52]:
```suggestion
	_FORCE_INLINE_ TypedArray(const Array &p_array) :
			TypedArray() {
```
Alternatively, to reduce duplication even further

File: core/variant/typed_array.h [hunk 3]
```diff
@@ -46,10 +46,15 @@ class TypedArray : public Array {
...
+		if (is_same_typed(p_array)) {
+			_ref(p_array);
+		} else {
+			assign(p_array);
+		}
```
Comment (AThousandShips) [inline core/variant/typed_array.h:57]: Alternatively this block can be replaced by:
```cpp
		if (p_array.get_typed_builtin() == Variant::OBJECT && p_array.get_typed_class_name() == T::get_class_static() && p_array.get_typed_script() == Variant()) {
			_ref(p_array);
		} else {
			set_typed(Variant::OBJECT, T::get_class_static(), Variant());
			assign(p_array);
		}
```
To avoid doing the typing part, though in either case it will allocate private data possibly unnecessarily

File: core/variant/typed_array.h (hunk 1 above)
Comment (adamscott) [reply core/variant/typed_array.h:49]: I'm all in to simplify the code.

File: core/variant/typed_array.h (hunk 3 above)
Comment (adamscott) [reply core/variant/typed_array.h:57]: > though in either case it will allocate private data possibly unnecessarily

Then, I would keep the simplest version.

Comment (AThousandShips) [reply core/variant/typed_array.h:57]: Then I will and a future cleanup or improvement can hand that

**Comment by allenwp** [comment]
I just tried this PR and it fixes the issue using the minimum reproduction code that I shared in  #89191.

**Review by dsnopek — APPROVED** [review]
This looks good to me!

After this change, is the `Array(const Array &p_base, uint32_t p_type, const StringName &p_class_name, const Variant &p_script)` constructor even used anywhere? If not, I wonder if it should be removed? Anyway, not important questions for now, things could be cleaned up more later :-)

**Comment by AThousandShips** [comment]
I think it's used in scripting, as the template can't be used in dynamic code, only static code, so in GDScript etc. the explicit constructor is relevant

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!
