### PR TITLE
Consolidate remembering window settings into single config

### LINKED ISSUE #97051: `interface/editor/editor_screen` setting has no effect once window position is remembered
### Tested versions

4.4 dev2

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

There is `interface/editor/editor_screen` editor setting, which defines where the editor should appear at startup. After #76085, the editor will use the last window position (including screen), making the setting effectively useless. It has effect only when a project is opened for the first time.

Maybe we should just remove this setting now.

### Steps to reproduce

1. Change `interface/editor/editor_screen` to Screen 1
2. Restart the editor while it is on screen 2
3. It starts on screen 2

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bits-by-brandon**
Fixes https://github.com/godotengine/godot/issues/97051 by consolidating the `remember_window_size_and_position` editor config into a new `Auto` option in `interface/editor/editor_screen`.

Screenshot 2024-09-23 at 11 14 46 AM

Tested locally on MacOS build

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -4051,7 +4056,7 @@ int Main::start() {
 				sml->get_root()->set_embedding_subwindows(true);
 			}
 			restore_editor_window_layout = EditorSettings::get_singleton()->get_setting(
-					"interface/editor/remember_window_size_and_position");
+												   "interface/editor/editor_screen") == -5;
```
Comment (bits-by-brandon) [inline main/main.cpp:4059]: How do I compare this variant to this signed int?

Comment (AThousandShips) [reply main/main.cpp:4059]: You cast it to an int, like `int(EditorSettings::get_singleton()->get_setting("interface/editor/editor_screen"))` or `EditorSettings::get_singleton()->get_setting("interface/editor/editor_screen").operator int()`

File: doc/classes/EditorSettings.xml [hunk 2]
```diff
@@ -772,7 +773,7 @@
 			Translations are provided by the community. If you spot a mistake, [url=$DOCS_URL/contributing/documentation/editor_and_docs_localization.html]contribute to editor translations on Weblate![/url]
 		</member>
 		<member name="interface/editor/editor_screen" type="int" setter="" getter="">
-			The preferred monitor to display the editor.
+			The preferred monitor to display the editor. If set to [code]Auto[/code], the editor will remember the last screen it was displayed on across restarts.
```
Comment (Mickeon) [inline doc/classes/EditorSettings.xml:776]: The actual value of the setting is `-5`, so "Auto" shouldn't be in code tags.
```suggestion
			The preferred monitor to display the editor. If set to [b]Auto[/b], the editor will remember the last screen it was displayed on across restarts.
```
We could also note down the `-5` , but there's no precedent of this _just yet_ so I'd avoid it for consistency.

File: doc/classes/EditorSettings.xml [hunk 3]
```diff
@@ -824,10 +825,7 @@
 			If [code]true[/code], the mouse's additional side buttons will be usable to navigate in the script editor's file history. Set this to [code]false[/code] if you're using the side buttons for other purposes (such as a push-to-talk button in a VoIP program).
 		</member>
 		<member name="interface/editor/project_manager_screen" type="int" setter="" getter="">
-			The preferred monitor to display the project manager.
-		</member>
-		<member name="interface/editor/remember_window_size_and_position" type="bool" setter="" getter="">
-			If [code]true[/code], the editor window will remember its size, position, and which screen it was displayed on across restarts.
+			The preferred monitor to display the project manager. If set to [code]Auto[/code], the editor will remember the last screen it was displayed on across restarts.
```
Comment (Mickeon) [inline doc/classes/EditorSettings.xml:828]: Ditto

File: doc/classes/EditorSettings.xml (hunk 2 above)
Comment (bits-by-brandon) [reply doc/classes/EditorSettings.xml:776]: Changing the description! 
> We could also note down the -5 , but there's no precedent of this just yet so I'd avoid it for consistency.
What do you mean? Noting the -5 value in the docs here, or somewhere else?

Comment (Mickeon) [reply doc/classes/EditorSettings.xml]: I mean not doing it at all, because this kind of thing is not done almost anywhere else in the class reference.

File: main/main.cpp (hunk 1 above)
Comment (bits-by-brandon) [reply main/main.cpp]: I'm a total beginner with c++, is there a convention of using the raw values over something like an enum here?

**Comment by bits-by-brandon** [comment]
I'm not sure what's causing the build fail `GHA / 🐧 Linux / Editor w/ Mono (target=editor)`

File: doc/classes/EditorSettings.xml [hunk 4]
```diff
@@ -1,5 +1,6 @@
 <?xml version="1.0" encoding="UTF-8" ?>
-<class name="EditorSettings" inherits="Resource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
+<class name="EditorSettings" inherits="Resource"
+	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
```
Comment (AThousandShips) [inline doc/classes/EditorSettings.xml:3]: This should be restored, check the CI check it corrects this

File: main/main.cpp (hunk 1 above)
Comment (AThousandShips) [reply main/main.cpp]: You should use the enum to make it safer

File: doc/classes/EditorSettings.xml (hunk 4 above)
Comment (bits-by-brandon) [reply doc/classes/EditorSettings.xml:3]: Sorry for the total beginner questions. It keeps auto formatting like this on save. Is this my editor, or a project configured formatter doing this?

Comment (AThousandShips) [reply doc/classes/EditorSettings.xml:3]: It must be your editor enforcing a line limit, it should be just one line

Comment (bits-by-brandon) [reply doc/classes/EditorSettings.xml]: Fixed

File: main/main.cpp (hunk 1 above)
Comment (bits-by-brandon) [reply main/main.cpp]: Okay, I found the enums! lmk if i'm doing this right

**Comment by KoBeWi** [comment]
The project manager's Auto option does not work. The window spawns at 0, 0 and moves to screen center, always on screen 1.

File: servers/display_server.h [hunk 5]
```diff
@@ -293,6 +293,7 @@ class DisplayServer : public Object {
 	virtual Rect2i get_display_safe_area() const { return screen_get_usable_rect(); }
 
 	enum {
+		SCREEN_AUTO = -5, // Remembers last screen position.
```
Comment (KoBeWi) [inline servers/display_server.h:296]: This enum if for usage with `_get_screen_index()`. The new value makes no sense in this context.

File: main/main.cpp [hunk 6]
```diff
@@ -4051,7 +4056,8 @@ int Main::start() {
 				sml->get_root()->set_embedding_subwindows(true);
 			}
 			restore_editor_window_layout = EditorSettings::get_singleton()->get_setting(
-					"interface/editor/remember_window_size_and_position");
+																				  "interface/editor/editor_screen")
+												   .operator int() == DisplayServer::SCREEN_AUTO;
```
Comment (KoBeWi) [inline main/main.cpp:4060]: This formatting looks terrible.
It would be more readable as a single line.

File: main/main.cpp [hunk 7]
```diff
@@ -2757,9 +2757,14 @@ Error Main::setup2(bool p_show_boot_logo) {
 								prefer_wayland_found = true;
 							}
 
-							if (!remember_window_size_and_position_found && assign == "interface/editor/remember_window_size_and_position") {
+							if (editor && !remember_window_size_and_position_found && assign == "interface/editor/editor_screen") {
```
Comment (KoBeWi) [inline main/main.cpp:2760]: You could probably use the `screen_property` above.

File: servers/display_server.h (hunk 5 above)
Comment (bits-by-brandon) [reply servers/display_server.h:296]: should I make a new enum that essentially copies these values?
I'm trying to follow the values from this, which seem to be the same
https://github.com/godotengine/godot/pull/97333/files#diff-985565fb1f983acb2d87dbe8931c929d0f46fdecb1d99a31e495b151c0f52186R429

Comment (KoBeWi) [reply servers/display_server.h:296]: No idea tbh, you could use `-10` (to make sure there are no conflicts in the future, as it's a fake value anyway) and just hard-code it without any enum. I mean, it used `-2` previously (near the code you linked).

File: main/main.cpp (hunk 7 above)
Comment (bits-by-brandon) [reply main/main.cpp:2760]: Refactored this a bit, realized that saving the position of the project manager was never implemented

**Comment by bits-by-brandon** [comment]
Refactored to only apply settings in the editor and not to project manager, which was never implemented. 
Also creates a separate enum to capture valid values of the editor config, which mirrors screens but also has the new possible "Auto" value

File: main/main.cpp (hunk 6 above)
Comment (bits-by-brandon) [reply main/main.cpp]: 😅  Battling with auto formatting on this one

**Comment by bits-by-brandon** [comment]
Any other considerations for this PR?

**Comment by adamscott** [comment]
> Any other considerations for this PR?

cc. @KoBeWi

File: servers/display_server.h [hunk 8]
```diff
@@ -292,6 +292,14 @@ class DisplayServer : public Object {
 	virtual TypedArray<Rect2> get_display_cutouts() const { return TypedArray<Rect2>(); }
 	virtual Rect2i get_display_safe_area() const { return screen_get_usable_rect(); }
 
+	enum InitialScreen {
+		INITIAL_SCREEN_AUTO = -5, // Remembers last screen position.
+		INITIAL_SCREEN_WITH_MOUSE_FOCUS = -4,
+		INITIAL_SCREEN_WITH_KEYBOARD_FOCUS = -3,
+		INITIAL_SCREEN_PRIMARY = -2,
+		INITIAL_SCREEN_OF_MAIN_WINDOW = -1,
```
Comment (KoBeWi) [inline servers/display_server.h:300]: You can use the other enum to copy values, e.g.
```suggestion
		INITIAL_SCREEN_OF_MAIN_WINDOW = SCREEN_OF_MAIN_WINDOW,
```

File: doc/classes/EditorSettings.xml [hunk 9]
```diff
@@ -772,7 +772,7 @@
 			Translations are provided by the community. If you spot a mistake, [url=$DOCS_URL/contributing/documentation/editor_and_docs_localization.html]contribute to editor translations on Weblate![/url]
 		</member>
 		<member name="interface/editor/editor_screen" type="int" setter="" getter="">
-			The preferred monitor to display the editor.
+			The preferred monitor to display the editor. If set to [b]Auto[/b], the editor will remember the last screen it was displayed on across restarts.
```
Comment (KoBeWi) [inline doc/classes/EditorSettings.xml:775]:
```suggestion
			The preferred monitor to display the editor. If [b]Auto[/b], the editor will remember the last screen it was displayed on across restarts.
```

**Review by KoBeWi — APPROVED** [review]
Looks good, though I think the new enum shouldn't be in DisplayServer, or at least be wrapped in TOOLS_ENABLED. It's editor-only.

File: main/main.cpp [hunk 10]
```diff
@@ -4050,8 +4048,7 @@ int Main::start() {
 			if (editor_embed_subwindows) {
 				sml->get_root()->set_embedding_subwindows(true);
 			}
-			restore_editor_window_layout = EditorSettings::get_singleton()->get_setting(
-					"interface/editor/remember_window_size_and_position");
+			restore_editor_window_layout = EditorSettings::get_singleton()->get_setting("interface/editor/editor_screen").operator int() == DisplayServer::InitialScreen::INITIAL_SCREEN_AUTO;
```
Comment (AThousandShips) [inline main/main.cpp:4051]: You're not adjusting this here, the enum has `-4` but the option has `-5`

File: editor/editor_settings.h [hunk 11]
```diff
@@ -62,6 +62,13 @@ class EditorSettings : public Resource {
 		NETWORK_ONLINE,
 	};
 
+	enum InitialScreen {
```
Comment (AThousandShips) [inline editor/editor_settings.h:65]: What is this used for? Mixed it up with the one in `DisplayServer` below, is this one that was meant in those cases? In that case the value is off by one

Comment (bits-by-brandon) [reply editor/editor_settings.h:65]: Ah yes whoops. Let me fix

File: editor/editor_settings.cpp [hunk 12]
```diff
@@ -426,12 +426,17 @@ void EditorSettings::_load_defaults(Ref<ConfigFile> p_extra_config) {
 	EDITOR_SETTING_USAGE(Variant::INT, PROPERTY_HINT_ENUM, "interface/editor/display_scale", 0, display_scale_hint_string, PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_RESTART_IF_CHANGED | PROPERTY_USAGE_EDITOR_BASIC_SETTING)
 	EDITOR_SETTING_USAGE(Variant::FLOAT, PROPERTY_HINT_RANGE, "interface/editor/custom_display_scale", 1.0, "0.5,3,0.01", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_RESTART_IF_CHANGED | PROPERTY_USAGE_EDITOR_BASIC_SETTING)
 
-	String ed_screen_hints = "Screen With Mouse Pointer:-4,Screen With Keyboard Focus:-3,Primary Screen:-2"; // Note: Main Window Screen:-1 is not used for the main window.
+	String ed_screen_hints = "Auto (Remembers last position):-4,Screen With Mouse Pointer:-3,Screen With Keyboard Focus:-2,Primary Screen:-1";
```
Comment (AThousandShips) [inline editor/editor_settings.cpp:429]: This will make existing settings break as if people picked `Screen With Keyboard Focus` they'll now have picked `Screen With Mouse Pointer`, any reason you can't keep those?

Comment (bits-by-brandon) [reply editor/editor_settings.cpp:429]: Oh good point

**Comment by bits-by-brandon** [comment]
@AThousandShips  @KoBeWi Made changes!

**Review by AThousandShips — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
I pushed an update to squash the commits together, as per our preferred PR workflow.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
