### PR TITLE
Fixed Image.save_jpg() does not write any file

### LINKED ISSUE #66650: `Image.save_jpg()` does not write any file
### Godot version

v4.0.beta2.official.f8745f2f7

### System information

Windows 10

### Issue description

Calling `Image.save_png(...)` writes the image data to a png file as expected, but `Image.save_jpg(...)` does not result in any file. It returns error code 0 to indicate that no errors occured.

### Steps to reproduce

Run the example project and check the "user://" directory. There is an `icon.png` file but no `icon.jpg`.

Alternatively run this code in a fresh project:

    var icon_path := "res://icon.svg"
    
    var image = Image.load_from_file(icon_path)

    var error = image.save_jpg("user://icon.jpg")
    print("Error: %s" % error)
    print(FileAccess.file_exists("user://icon.jpg"))
    error = image.save_png("user://icon.png")
    print("Error: %s" % error)
    print(FileAccess.file_exists("user://icon.png"))

Output:

    Error: 0
    false
    Error: 0
    true

### Minimal reproduction project

[imageTest.zip](https://github.com/godotengine/godot/files/9682231/imageTest.zip)

### PR DESCRIPTION
**Pull request by MladoniSzabi**
The function that was supposed to implement the saving in image_loader_jpegd was returning OK without doing anything. Copied the code from _jpgd_buffer_save_func to _jpgd_save_func but changed the ImageLoaderJPGOSBufferto a ImageLoaderJPGOSFile to save to a file instead of memory. Changed the image format from FORMAT_ETC2_RGB8 to FORMAT_RGB8 since the first one was creating a weird greyscale interlaced image.

I am not sure how to merge the two functions or make the code more dry

Resolves  #66650

### CODE REVIEW

File: modules/jpg/image_loader_jpegd.cpp [hunk 1]
```diff
@@ -183,6 +180,36 @@ static Vector<uint8_t> _jpgd_buffer_save_func(const Ref<Image> &p_img, float p_q
 	return output;
 }
 
+static Error _jpgd_save_func(const String &p_path, const Ref<Image> &p_img, float p_quality) {
+	ERR_FAIL_COND_V(p_img.is_null() || p_img->is_empty(), ERR_INVALID_PARAMETER);
+	Ref<Image> image = p_img;
+	if (image->get_format() != Image::FORMAT_RGB8) {
+		image->convert(Image::FORMAT_RGB8);
```
Comment (akien-mga) [inline modules/jpg/image_loader_jpegd.cpp:187]: I see that `_jpgd_buffer_save_func` above does this check instead:
```
	if (image->get_format() != Image::FORMAT_RGB8) {
		image->convert(Image::FORMAT_ETC2_RGB8);
	}
```
Sounds like it's wrong and yours is better? If so should be fixed above too.

I don't know if the intention from #62122 was to do the implementation using `ImageLoaderJPGOSFile` as done here, or just getting a buffer from the file and calling the buffer version.

CC @reduz @Faless

**Comment by akien-mga** [comment]
It's not directly related to your fix but it's also a wrong change from #62122, so maybe you can include this in your commit if it ever requires an amend (otherwise I can include it in a future cleanup if I remember):
```diff
diff --git a/modules/jpg/image_loader_jpegd.cpp b/modules/jpg/image_loader_jpegd.cpp
index ce20ac9060..8446e063a5 100644
--- a/modules/jpg/image_loader_jpegd.cpp
+++ b/modules/jpg/image_loader_jpegd.cpp
@@ -33,8 +33,8 @@
 #include "core/os/os.h"
 #include "core/string/print_string.h"
 
-#include "thirdparty/jpeg-compressor/jpgd.h"
-#include "thirdparty/jpeg-compressor/jpge.h"
+#include <jpgd.h>
+#include <jpge.h>
 #include <string.h>
 
 Error jpeg_load_image_from_buffer(Image *p_image, const uint8_t *p_buffer, int p_buffer_len) {
```

`thirdparty/jpeg-compressor` is in the `CPPPATH` so there's no reason to hardcode it. This would theoretically make it possible to link against a system packaged jpeg-compressor (even though realistically I don't think anyone will care for this tiny lib).

File: modules/jpg/image_loader_jpegd.cpp (hunk 1 above)
Comment (MladoniSzabi) [reply modules/jpg/image_loader_jpegd.cpp:187]: I added a `printf` before and inside the if and it seems the image is already RGB8 and the conversion doesn't happen.
If i change the if to 
`
if (image->get_format() != Image::FORMAT_ETC2_RGB8) {
		image->convert(Image::FORMAT_ETC2_RGB8);
	}
`
it gives an error
ERROR: Cannot convert to <-> from compressed formats. Use compress() and decompress() instead.

Comment (MladoniSzabi) [reply modules/jpg/image_loader_jpegd.cpp]: Changed the `_jpgd_buffer_save_func` to use `FORMAT_RGB8`.
Changed the include path to `jpgd.h` and `jpge.h`.
Merged duplicate code into one function.

Can still change the `_jpgd_save_func` to use the buffer from the `_jpgd_buffer_save_func` if need be

**Comment by MladoniSzabi** [comment]
Is there something else I need to do on this PR?

**Comment by Calinou** [comment]
> Is there something else I need to do on this PR?

Code looks good from a quick glance, but I'll let someone else review just to make sure. Akien is currently not available for PR reviews.

**Review by Calinou — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
