### PR TITLE
Fix object icon in the resource picker not being visible when it should

### LINKED ISSUE #114041: Type icon does not appear for texture in resource picker
### Tested versions

Reproducible 4.6 beta1
Not reproducible 4.5.1

### System information

W10

### Issue description

https://github.com/user-attachments/assets/c10d895b-312f-4d94-a46f-4f9d800c376e

### Steps to reproduce

1. Create Sprite2D
2. Assign new GradientTexture2D to `texture` (has icon)
3. Re-select the sprite (no icon)
4. Click the gradient texture to open it (icon appears)
5. Click again to close it (still icon)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #114041.

### CODE REVIEW

File: editor/inspector/editor_resource_picker.cpp [hunk 1]
```diff
@@ -1076,7 +1076,7 @@ void EditorResourcePicker::_notification(int p_what) {
 			draw_style_box(get_theme_stylebox(SceneStringName(panel), SNAME("Tree")), Rect2(Point2(), get_size()));
 		} break;
 
-		case NOTIFICATION_RESIZED: {
```
Comment (KoBeWi) [inline editor/inspector/editor_resource_picker.cpp:1079]: This case was _added_ in #109458
I wonder how it was working before 🤔

**Review by KoBeWi — APPROVED** [review]
Fixes the bug, but there might be a better fix.

File: editor/inspector/editor_resource_picker.cpp (hunk 1 above)
Comment (YeldhamDev) [reply editor/inspector/editor_resource_picker.cpp:1079]: The bug itself is caused by `preview_rect` having a width of `0` by the time it's called, which is lower than `thumbnail_size`, triggering the hide behavior. Said code happens inside `_update_resource_preview()`.

As to how it was working before? I'm honestly not quite sure. :shrug:

**Comment by Repiteo** [comment]
Thanks!
