### PR TITLE
[TextEdit] Make `wrap_right_offset` adjustable theme constant.

### LINKED ISSUE #111739: TextEdit wraps differently from Label
### Tested versions

Reproducible in: 4.5.stable

### System information

Godot v4.5.stable.mono - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.8115) - AMD Ryzen 7 2700X Eight-Core Processor (16 threads) - 31.91 GiB memory

### Issue description

The TextEdit node contains right padding which is not part of the StyleBox and cannot be customized in any way. This causes a TextEdit node of the same minimum size as a Label to autowrap its text differently, and prevents a dev from doing anything to change this behavior. This makes TextEdit unusable for multi-line input in situations where a player expects the text they enter to look the same when it is displayed.

### Steps to reproduce

1. Create a TextEdit node
2. Create a Label node
3. Give them the same custom minimum width and autowrap at boundary
4. Script the Label to use the text entered into the TextEdit

### Minimal reproduction project (MRP)

[text-edit-padding.zip](https://github.com/user-attachments/files/22956960/text-edit-padding.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/111739

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -8806,7 +8807,7 @@ void TextEdit::_adjust_viewport_to_caret_horizontally(int p_caret, bool p_maximi
 	if (v_scroll->is_visible_in_tree()) {
 		visible_width -= v_scroll->get_combined_minimum_size().width;
 	}
-	visible_width -= 20; // Give it a little more space.
+	visible_width -= theme_cache.wrap_right_offset * 2; // Give it a little more space.
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: This isn't related to wrapping, this code only runs when wrapping is disabled.

File: doc/classes/TextEdit.xml [hunk 2]
```diff
@@ -1676,6 +1676,9 @@
 			The size of the text outline.
 			[b]Note:[/b] If using a font with [member FontFile.multichannel_signed_distance_field] enabled, its [member FontFile.msdf_pixel_range] must be set to at least [i]twice[/i] the value of [theme_item outline_size] for outline rendering to look correct. Otherwise, the outline may appear to be cut off earlier than intended.
 		</theme_item>
+		<theme_item name="wrap_right_offset" data_type="constant" type="int" default="10">
+			Sets an additional right margin for line wrapping width.
```
Comment (kitbdev) [inline doc/classes/TextEdit.xml]: The name probably shouldn't use "right" since it is on the left if the layout is set to rtl.

**Review by kitbdev — COMMENTED** [review]
Makes sense to have this customizable.

File: doc/classes/TextEdit.xml (hunk 2 above)
Comment (bruvzg) [reply doc/classes/TextEdit.xml]: Removed "right", directions are mixed for a lot of RTL related stuff, but in this case "right" doesn't add anything useful.

**Review by kitbdev — APPROVED** [review]
Looks good.

**Comment by Repiteo** [comment]
Thanks!
