### PR TITLE
Hash function improvements

### LINKED ISSUE #61645: Tilemap really slow with few tiles
### Godot version

4.0 alpha 9

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1060

### Issue description

The tilemap editor becomes very slow when a certain number of tiles are added (only on alpha 9) someone suggested it could be changes to the HashMap.

Videos to show the difference between the alpha 8 and 9 version:

Alpha 9 ( Slow ) 

https://user-images.githubusercontent.com/16109919/171746421-452c019b-95cf-4757-8dec-7998d736c775.mp4

Alpha 8

https://user-images.githubusercontent.com/16109919/171746493-125f8b91-b4d9-4fcf-bf6b-0a1dab73f6a4.mp4

### Steps to reproduce

Just fill a Tilemap node with a certain number of tiles

### Minimal reproduction project

[BugTilemapAlpha9.zip](https://github.com/godotengine/godot/files/8828085/BugTilemapAlpha9.zip)

### PR DESCRIPTION
**Pull request by Geometror**
This PR aims to improve the performance of data structures which rely on hashing functions (such as HashMap and HashSet). For some types (most noticeably Vector2i) the currently used hash function provides a seemingly bad distribution, resulting in lots of collisions and therefore severely degraded lookup performance of the affected data structures.

For Vector2i, the currently used DBJ2 function performs bad with numbers that are close together, making the tilemap editor unusable if you have more than a few hundred tiles.

Detailed changes:
- Use the murmur3 hash function for all basic numeric types as it provides a better distribution (murmur3 should be a little bit slower than DBJ2, but provides a much better random distribution, resulting in an overall better lookup performance)
- Use Thomas Wang's 64-bit to 32-bit hash functions for RID and OBJECT in VariantHasher (this was already done in HashMapHasherDefault)
- Removed VariantHasher template argument in text_server_adv/fb as it seems like it is not needed anymore (however I am not sure)

Supercedes #61833, as this makes the tilemap editor at least as fast as with #61833 and fixes the underlying issue.

~~Marked as draft, since I came across some strange issues with string hashing when I tried to switch from DBJ2 to any other hash function (murmur2/3 or meiyan): The engine crashes on startup because ClassDB completely breaks (as I conclude based on the message "Request for nonexistent class 'Object'."). Just changing the string hash functions of HashMapHasherDefault (in hashfuncs.h) works, but I think we should have one common hash function for strings.
I left the murmur2 and meiyan hash functions in hashfuncs.h in case someone wants to do some further experiments. (can be stripped when this PR is fully tested and ready to merge)~~

HashMaps with Vector2i are also used in some places of TextServer so we should check performance there. Benchmarking/testing is very appreciated :)

The editor's startup time seems to be unchanged [project manager/release_debug]: 
```
hyperfine -iw1 "godot_before.exe --quit" "godot.windows.opt.tools.64.exe --quit"
Benchmark 1: godot_before.exe --quit
  Time (mean ± σ):      1.793 s ±  0.024 s    [User: 0.000 s, System: 0.008 s]
  Range (min … max):    1.770 s …  1.851 s    10 runs

  Warning: Ignoring non-zero exit code.

Benchmark 2: godot.windows.opt.tools.64.exe --quit
  Time (mean ± σ):      1.797 s ±  0.021 s    [User: 0.003 s, System: 0.008 s]
  Range (min … max):    1.778 s …  1.846 s    10 runs

  Warning: Ignoring non-zero exit code.

Summary
  'godot_before.exe --quit' ran
    1.00 ± 0.02 times faster than 'godot.windows.opt.tools.64.exe --quit'
```

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/61645

### CODE REVIEW

**Comment by bruvzg** [comment]
> Removed VariantHasher template argument in text_server_adv/fb as it seems like it is not needed anymore (however I am not sure)

It was added since default hasher did not have a hash function for `Vector2i` at all, and is not necessary anymore.

**Comment by KoBeWi** [comment]
Tested with my project and indeed TileMap issues are gone.

File: core/templates/hashfuncs.h [hunk 1]
```diff
@@ -100,7 +100,160 @@ static inline uint32_t hash_one_uint64(const uint64_t p_int) {
 	return uint32_t(v);
 }
 
-static inline uint32_t hash_djb2_one_float(double p_in, uint32_t p_prev = 5381) {
+// Murmurhash2 32-bit version from https://github.com/aappleby/smhasher/blob/master/src/MurmurHash2.cpp.
```
Comment (akien-mga) [inline core/templates/hashfuncs.h:103]: Seems all three thirdparty hashes you added are public domain, but this would be good to document properly with a quote of their license/public domain dedication, as the links can go 404.

File: core/templates/hashfuncs.h [hunk 2]
```diff
@@ -186,7 +341,9 @@ struct HashMapHasherDefault {
 	static _FORCE_INLINE_ uint32_t hash(const char32_t p_uchar) { return (uint32_t)p_uchar; }
 	static _FORCE_INLINE_ uint32_t hash(const RID &p_rid) { return hash_one_uint64(p_rid.get_id()); }
 
-	static _FORCE_INLINE_ uint32_t hash(const StringName &p_string_name) { return p_string_name.hash(); }
+	static _FORCE_INLINE_ uint32_t hash(const StringName &p_string_name) {
+		return p_string_name.hash();
+	}
```
Comment (akien-mga) [inline core/templates/hashfuncs.h:346]: I guess this and the one above were wrongly changed by buggy clang-format 14.0.0?  https://github.com/llvm/llvm-project/issues/54901

Comment (Geometror) [reply core/templates/hashfuncs.h]: This was a leftover from testing some other hash functions which required several lines of code. Just cleaned it up.

**Comment by Geometror** [comment]
Did a cleanup and removed meiyan + murmurhash2 since they didn't have any clear benefit over murmurhash3.

File: core/templates/hashfuncs.h (hunk 1 above)
Comment (Geometror) [reply core/templates/hashfuncs.h]: I replaced it with the sentence I found in the smhasher repo: "All MurmurHash versions are public domain software, and the author disclaims all copyright to their code."

File: core/templates/hashfuncs.h [hunk 3]
```diff
@@ -167,11 +233,24 @@ template <class T>
...
+	template <class T>
+	static _FORCE_INLINE_ uint32_t hash(const T *p_pointer) { return hash_one_uint64((uint64_t)p_pointer); }
+
+	template <class T>
+	static _FORCE_INLINE_ uint32_t hash(const Ref<T> &p_ref) { return hash_one_uint64((uint64_t)p_ref.operator->()); }
+
 	static _FORCE_INLINE_ uint32_t hash(const String &p_string) { return p_string.hash(); }
 	static _FORCE_INLINE_ uint32_t hash(const char *p_cstr) { return hash_djb2(p_cstr); }
-	static _FORCE_INLINE_ uint32_t hash(const uint64_t p_int) { return hash_one_uint64(p_int); }
+	static _FORCE_INLINE_ uint32_t hash(const wchar_t p_wchar) { return (uint32_t)p_wchar; }
```
Comment (reduz) [inline core/templates/hashfuncs.h:245]: I think this and the ones below likely should be hashed too.

File: core/templates/hashfuncs.h [hunk 4]
```diff
@@ -100,7 +100,73 @@ static inline uint32_t hash_one_uint64(const uint64_t p_int) {
...
+	h ^= h >> 16;
+	h *= 0x85ebca6b;
+	h ^= h >> 13;
+	h *= 0xc2b2ae35;
+	h ^= h >> 16;
+
+	return h;
+}
+
+static _FORCE_INLINE_ uint32_t hash_murmur3_32(const void *key, int len) {
```
Comment (reduz) [inline core/templates/hashfuncs.h:120]: I would probably make this compatible with the djb2 call style, where you can call the function multiple times and if you dont pass a second argument, the seed is used.

The reason is that, many times, things that need to be hashed do not appear in the form of buffers.

**Review by reduz — CHANGES_REQUESTED** [review]

File: core/templates/hashfuncs.h [hunk 5]
```diff
@@ -100,7 +100,73 @@ static inline uint32_t hash_one_uint64(const uint64_t p_int) {
...
+		h1 ^= k1;
+		h1 = rotl32(h1, 13);
+		h1 = h1 * 5 + 0xe6546b64;
+	}
+
+	const uint8_t *tail = (const uint8_t *)(data + nblocks * 4);
+
+	uint32_t k1 = 0;
+
+	switch (len & 3) {
```
Comment (reduz) [inline core/templates/hashfuncs.h:149]: We don't really hash anything not aligned to words, so i think this is not needed and the code can be simplified, or this version can be kept separate for buffers if needed, but not used by default.

**Review by reduz — CHANGES_REQUESTED** [review]

**Comment by bruvzg** [comment]
> HashMaps with Vector2i are also used in some places of TextServer so we should check performance there. Benchmarking/testing is very appreciated :)

Done some pref. testing: with the new harsher `TextServer` processing of the large help pages seems to be `0.7%` faster on average. `TextServer` use `Vector2i` maps for font sizes and for bitmap font kerning, in both cases number of items are small and probability of hash collision is low, so there are no reasons to expect any significant performance improvement. But it should not cause any issues.

File: core/templates/hashfuncs.h (hunk 4 above)
Comment (Geometror) [reply core/templates/hashfuncs.h]: The beauty of this hash function is that it is a general purpose hash function that just works on any form of data. As it is already done with several types in this PR, you can pass any type together with its size in bytes to it. For example Vector2i: `hash_murmur3_32_buffer(&p_vec, sizeof(Vector2i));`
I had dedicated versions for primitive types, but they didn't provide any performance benefit compared to this general variant. Nearly all places where dbj2 is used can be easily replaced with this buffer version. (However, at one point, I had replaced the dbj2 string hash functions (in ustring.cpp) with murmur3 but that broke ClassDB for some reason and I have no clue why).

Besides that, I am not sure if the quality of murmur3 will still be the same if I modify it to work like the dbj2 hash functions (because that is not how it was intended to be used and hash functions are quite fragile). I could do some tests, but that might take some time.
For now I added a seed parameter which defaults to the same random prime number as before.

File: core/templates/hashfuncs.h (hunk 3 above)
Comment (akien-mga) [reply core/templates/hashfuncs.h:244]: For the record they were not hashed before, they were just moved here. They could likely be hashed somehow but since they're ints that fit in `uint32_t` that might not be needed?

Comment (reduz) [reply core/templates/hashfuncs.h:244]: Yeah but this is actually the issue that we are trying to fix. For sequential indices, if not hashed, robin hood will not work properly because it relies on random gaps on the hash table.

**Review by reduz — APPROVED** [review]

File: core/templates/hashfuncs.h (hunk 3 above)
Comment (Geometror) [reply core/templates/hashfuncs.h]: I replaced it with the murmurhash3 finalizer function `fmix32()` which does bitmixing pretty well for hashing (although just for the char types, should I use this approach on the other integer types too?)

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
I will probably do a subsequent PR cleaning up a bit of the djb2 use cases and moving it to murmur3.
