### PR TITLE
Fix duplicated string on RichTextLabel if starts with '\n'

### LINKED ISSUE #3773: RichTextLabel append text problem
Arch Linux x64

When I try to append text in any possible way to a rich text label, the first line will be a duplicate of all contents with no escape characters and other lines will be the new content.
To reproduce, try to append text to a rich text label!

I'm using [this commit](https://github.com/godotengine/godot/commit/f88d7a0df7d28ff5572173ba3e496907de79bb04)
Screenshot

### LINKED ISSUE #6212: Multi-line String creates duplicate string
**Operating system or device - Godot version:** 2.1

**Issue description** (what happened, and what was expected):
Alright folks, this is a pretty fascinating bug: 

```
    get_node("RichTextLabel").set_bbcode("""
    hello
    """)
```

This is valid `GDScript` syntax, but, it will actually insert 2x `hello` strings instead of just one.

If you do it without a initial line break:

```
    get_node("RichTextLabel").set_bbcode("""hello
    """)
```

It works fine.  I am making some extensive tooltips and need the line breaks but it literally duplicated my text, lol pretty funny tbh. I am not sure if this intended :P

### PR DESCRIPTION
**Pull request by volzhs**
Fix #6212, fix #3773

Test result

image

dug for several hours...

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -1179,7 +1179,8 @@ void RichTextLabel::add_text(const String& p_text) {
 			item->line=current_frame->lines.size();
 			_add_item(item,false);
 			current_frame->lines.resize(current_frame->lines.size()+1);
```
Comment (bojidar-bg) [inline scene/gui/rich_text_label.cpp]: Shouldn't this line be inside the if as well?

Comment (volzhs) [inline scene/gui/rich_text_label.cpp]: `rich_text_label.cpp` is really complicated for me, but I guess this line should be outside of `if` to increase position of line.
