### PR TITLE
Fix black bars appearing when using `background_color` on a TextEdit/CodeEdit.

### LINKED ISSUE #102844: When using a background colour on a TextEdit, the Minimap has ugly black bars.
### Tested versions

- Reproducible in Godot 4.3 stable, 4.2 stable, 4.1 stable

### System information

Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 08 Feb 2025 18:54:55 +0000 - X11 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 620 (KBL GT2) - Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 Threads)

### Issue description

Hi. 
I'm making a sort of detective game and I'm using a TextEdit node to store notes. I am using my own custom theme to make the TextEdit look consistent with the rest of the game. I asked for help in the [godot forums](https://godotforums.org/d/41932-ugly-black-bars-when-using-minimap-in-text-edit) and even on [reddit](https://www.reddit.com/r/godot/comments/1ihcbro/how_can_i_change_the_colour_of_the_lines_in_the/) but seeing as no one came for help, I assumed that it must be a bug and started to do some testing.

Without a theme, the Minimap looks okay and doesn't show these black bars. 

Image
Image

I noticed that when turning on the Minimap setting in the TextEdit, black bars are seen in the editor, and even in the game. I have attached a screenshot.
Image
This isn't horrible in dark mode, just an annoyance, but since I'm also designing a white version of my theme, these black bars make the Minimap unusable.
Image

I did some testing and figured out that the problem lies in the `background_color` setting of the TextEdit. If it is set to anything but `#00000000` (Even changing the alpha triggers this) the black bars appear. See the reproduction steps.

### Steps to reproduce

This bug can be seen in a blank project.
- Create a new blank project with nothing in it.
- Make a TextEdit Node
- Enable the Minimap
- Add a new theme to it, preferably a blank one
- Override the TextEdit theme 
- Go to the colours tab in the Theme
- Change the background colour
- Note how the black bars appear for every line in the Minimap if the background colour is set to anything but `#00000000`
Video attached as a demonstration in an completely empty project.

https://github.com/user-attachments/assets/611596db-fc24-446c-b977-cf42a5bf4a13

### Minimal reproduction project (MRP)

[Broken Text Edit Demo.zip](https://github.com/user-attachments/files/18793715/Broken.Text.Edit.Demo.zip)
Not required but attached anyway. The bug can be demonstrated in any project.

### PR DESCRIPTION
**Pull request by WinnerWind**
Fixes #102844  by equating the line_background_color in a slightly different way before applying alpha. 
This preserves editor error highlighting and fixes the above mentioned bug in a simple way. 
Editor error highlighting preserved. (See Minimap)
image
Bug is eradicated.
image
image
image

_In theory this is not the best way to solve it._ Ideally, the user should be using the Stylebox in the theme settings to change the background colour of the Text Edit, but since this option exists, and removing it might break existing projects, I decided to fix it this way instead. **This issue may not fix other issues with regards to setting the `background_color`** property in a theme, this is only intended as a fix for #102844. 

The previous solution was checking if the `line_background_color` was not equal to the theme's `background_color` property. `line_background_color` is usually `#00000000`, with the notable exception of errors. I am not sure where else this property is used. However, on setting the `background_color` in the theme, it becomes something other than `#00000000` which makes the resulting if statement return `true` instead, and it's alpha gets set to `1`, giving the resultant `#000000ff` and hence, the signature black bars. By checking it against `#00000000` directly, the if statement will return `false` unless `line_background_color` is being set.

P.S. This is my first commit to Godot. Please let me know how I can improve future commits (if any) and what I should be doing differently.

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -884,7 +884,14 @@ void TextEdit::_notification(int p_what) {
...
 					Color line_background_color = text.get_line_background_color(minimap_line);
 
-					if (line_background_color != theme_cache.background_color) {
+					// HACK: line_background_color is always #00000000
+					//       which causes the below check to always return false. Causes issues when
+					//       the user sets a background_color in the theme, at which point the below check would have
+					//       equated to true instead.
+					// By checking it against #00000000, we can ensure that the check only
+					// returns true only if a line_background_color is being set (Eg. error markers)
+					// irrespective of the theme background color.
```
Comment (KoBeWi) [inline scene/gui/text_edit.cpp:893]: Why the long comment, and calling it a hack?

This seems to be consistent with the documentation:
> If set to [code]Color(0, 0, 0, 0)[/code], no additional color is applied.

Comment (kleonc) [reply scene/gui/text_edit.cpp:893]: > Ok I'm not sure what the condition should be. If you simply write it like now, the `else` has no effect.

I've looked into this and:
- `theme_cache.background_color` is a single color for the whole TextEdit.
- `line_background_color` is a per-line custom color. If a line has no custom color, then the default `Color(0, 0, 0, 0)` is stored in its per-line data.

So:
- `if (line_background_color != theme_cache.background_color)` check makes no sense, as these are completely unrelated values.
- `if (line_background_color != Color(0, 0, 0, 0))` means "if the line has a custom background color" which is an absolutely valid / not hacky check.

This if/else was added in #85054. The original intention was to make the error etc. more visible, as previously `line_background_color.a *= 0.6` was always done.

So I think the correct code would be something like:
```cpp
const bool line_has_custom_background_color = line_background_color != Color(0, 0, 0, 0);
if (line_has_custom_background_color) {
	// Make non-default background colors more visible, such as error markers.
	line_background_color.a = 1.0;
}
```
The `else` indeed makes no sense here, "hack comment" too.

Comment (WinnerWind) [reply scene/gui/text_edit.cpp:893]: Hey there. Good morning.

I wrote the long comment calling it a hack because I wasn't sure about the purpose of the previous implementation. I looked through the commit history and spent a lot of time looking through the previous code and where this property was used and I couldn't figure out why it was being matched against the Theme Cache.

Because of this I decided to keep my changes as minimalist as possible and change the erroring line. I'm not sure if the else statement triggers at all either, because if it did, we would get semi translucent black lines. I'm not sure what it is doing, but to be on the safe side I decided to keep it.

Anyway, I have an exam to write in a few hours, but once I'm free, here are the changes I will make:
- Remove redundant else statement 
- Remove long comment.

Comment (WinnerWind) [reply scene/gui/text_edit.cpp]: Here's the code for the branchless solution. It works as intended.
image

image
image

Considering the nature of this code, it could give really small performance benefits to lower end systems. Not a whole lot, but every bit counts right?

**Review by KoBeWi — APPROVED** [review]
Needs to be squashed into one commit.

File: scene/gui/text_edit.cpp (hunk 1 above)
Comment (WinnerWind) [reply scene/gui/text_edit.cpp]: I'll add a comment too.

**Comment by WinnerWind** [comment]
Commits have been squashed. Do let me know if any more changes need to be made.

**Comment by WinnerWind** [comment]
I am so sorry for the recent changes. Please ignore them, they were a mistake on my part. The changes already appear squashed.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by WinnerWind** [comment]
Hey there. 
Thanks for merging my PR!
Hoping I can contribute more like this in the future.

Good luck with other issues and PRs!
