### PR TITLE
Fixed uinitialized variable in srgb_to_linear table

### LINKED ISSUE #33133: srgb_to_linear turns rgb 255 values into 0
**Godot version:**
3.2 alpha 2
EDIT: Same issue in 3.2 alpha 3

**OS/device including version:**
Windoze 10

**Issue description:**
It appears any Color value that uses maximum 255 becomes 0. 

So for example if red is 255 after conversion red becomes 0. Same issue with green and blue.

I do not think this is intended behavior. Possibly an upper boundary check  issue?

**Steps to reproduce:**

In my test below pixel at location 21,21 is black alpha 0.0 then I place a white alpha 1.0 and after conversion it becomes black alpha 1.0

image

**Minimal reproduction project:**

Sorry I do not have a test project.

### PR DESCRIPTION
**Pull request by hbina**
Old array's size was actually 255.

Fixes #33133

### CODE REVIEW

File: core/image.cpp [hunk 1]
```diff
@@ -2934,7 +2934,7 @@ void Image::srgb_to_linear() {
...
+	static const uint8_t srgb2lin[256] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 13, 13, 13, 14, 14, 15, 15, 16, 16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 21, 22, 22, 23, 23, 24, 24, 25, 26, 26, 27, 27, 28, 29, 29, 30, 31, 31, 32, 33, 33, 34, 35, 36, 36, 37, 38, 38, 39, 40, 41, 42, 42, 43, 44, 45, 46, 47, 47, 48, 49, 50, 51, 52, 53, 54, 55, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 92, 93, 94, 95, 97, 98, 99, 101, 102, 103, 105, 106, 107, 109, 110, 112, 113, 114, 116, 117, 119, 120, 122, 123, 125, 126, 128, 129, 131, 132, 134, 135, 137, 139, 140, 142, 144, 145, 147, 148, 150, 152, 153, 155, 157, 159, 160, 162, 164, 166, 167, 169, 171, 173, 175, 176, 178, 180, 182, 184, 186, 188, 190, 192, 193, 195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 218, 220, 222, 224, 226, 228, 230, 232, 235, 237, 239, 241, 243, 245, 248, 250, 252, 256 };
```
Comment (akien-mga) [inline core/image.cpp]: Are you sure about using `256`? Max value is `255` no?

**Comment by akien-mga** [comment]
It fails building on any compiler:
```
core/image.cpp: In member function 'void Image::srgb_to_linear()':
core/image.cpp:2937:1095: error: narrowing conversion of '256' from 'int' to 'uint8_t' {aka 'unsigned char'} [-Wnarrowing]
 2937 | , 230, 232, 235, 237, 239, 241, 243, 245, 248, 250, 252, 256 };
      | 
```

It's OK to do a non-tested PR, but if so please label it as such so that we can test it and confirm that it builds and fixes the bug.

File: core/image.cpp (hunk 1 above)
Comment (hbina) [reply core/image.cpp]: Sorry about that, fixed in latest commit.

**Review by akien-mga — APPROVED** [review]
