### PR TITLE
Enhancement for tileset sorting

### LINKED ISSUE #34783: Tileset sorting wrong after 9th tile
**Godot version:** 3.2.beta4
**Godot version:** 3.2.rc4.official

**OS/device including version:** (Probably Any) (Found On: GNU\Linux\Manjaro KDE x86_64)

**Issue description:** Godot sorts tiles correct to the 9th tile. After you add 10th tile Godot puts it after 1st tile. For example: 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9.

**Steps to reproduce:** Create a TileMap node. From Inspector menu, select "New TileSet" as Tile Set. Then select an image that includes at least 10 tiles. Add at least 10 tiles using "New Single Tile" button.

**Minimal reproduction project:**
[Sorting.zip](https://github.com/godotengine/godot/files/4019413/Sorting.zip)

**Screenshot.**
Screenshot_20200103_171242

### PR DESCRIPTION
**Pull request by Pleto**
Simple fix for issue #34783. "Natural no case" comparison should be used to sort the tiles.

*Bugsquad edit:* Fixes #34783.

### CODE REVIEW

File: editor/plugins/tile_map_editor_plugin.cpp [hunk 1]
```diff
@@ -413,7 +413,10 @@ struct _PaletteEntry {
 	String name;
 
 	bool operator<(const _PaletteEntry &p_rhs) const {
-		return name < p_rhs.name;
+
```
Comment (akien-mga) [inline editor/plugins/tile_map_editor_plugin.cpp:416]: This line should be removed to match our current code style:
https://github.com/godotengine/godot/pull/43050/checks?check_run_id=1302112226

Could you do it by amending the commit? (`git commit --amend` and `git push --force` to update the remote branch).

File: editor/plugins/tile_map_editor_plugin.cpp [hunk 2]
```diff
@@ -413,7 +413,10 @@ struct _PaletteEntry {
 	String name;
 
 	bool operator<(const _PaletteEntry &p_rhs) const {
-		return name < p_rhs.name;
+		
+		// Natural no case comparison will compare strings based on CharType
+		// order (except digits) and on numbers that start on the same position
```
Comment (akien-mga) [inline editor/plugins/tile_map_editor_plugin.cpp:418]: While amending the commit, you can also add a dot at the end of this sentence.

**Review by akien-mga — APPROVED** [review]
Style nitpicks but otherwise should be good to merge.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
