### PR TITLE
Clamp bezier handle length to half the length of animation

### LINKED ISSUE #93807: Bezier handles are too long on short animations
### Tested versions

4.3.beta2

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.4633) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

Handles on Bezier keys are always 0.25 seconds long. This causes problems when working with short animations where the bezier curve will end up with an unwanted shape and you won't be able to get at the handles since they might be outside the view.

https://github.com/godotengine/godot/assets/4955051/415fa752-b176-42ed-869d-e56e1543c6e7

New key Handle length should at least be clamp to animation length, but something like half or quarter of animation length might be better. This would also be somewhat improved if the default handle type of new keys could be specified. It might make sense to have a default bezier handle type in editor settings.

### Steps to reproduce

See video above
OR
1. Create an animation and set the length to 0.2 seconds.
2. Create a bezier anaimation with a key at the beginning and end of the animation and observe the curve and handles.

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by Arnklit**
Fixes https://github.com/godotengine/godot/issues/93807 by clamping the new handle length to half the length of the animation.

image

### CODE REVIEW

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -4459,9 +4459,9 @@ AnimationTrackEditor::TrackIndices AnimationTrackEditor::_confirm_insert(InsertD
 			Array array;
 			array.resize(5);
 			array[0] = p_id.value;
-			array[1] = -0.25;
+			array[1] = MAX(-0.25, -animation->get_length() / 2.0);
```
Comment (akien-mga) [inline editor/animation_track_editor.cpp:4462]: Not critical but I'd factor this out as:
```cpp
const float max_width = animation->get_length() / 2.0;
```
to avoid computing it twice.

Comment (Arnklit) [reply editor/animation_track_editor.cpp]: Good point. Done/

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by Arnklit** [comment]
@mihe pointed out to me that there was another code path that this didn't cover. Setting to draft while I fix that and refactor the code.

**Comment by Arnklit** [comment]
Moved `make_default_bezier_key` into animation on @mihe 's suggestion, which meant we can now call the same code from all three spots and remove the repeated code. @mihe if you have time to give it another look that would be great.

File: editor/animation_track_editor.cpp [hunk 2]
```diff
@@ -4458,14 +4458,9 @@ AnimationTrackEditor::TrackIndices AnimationTrackEditor::_confirm_insert(InsertD
 		case Animation::TYPE_BEZIER: {
 			Array array;
 			array.resize(5);
-			array[0] = p_id.value;
-			array[1] = -0.25;
-			array[2] = 0;
-			array[3] = 0.25;
-			array[4] = 0;
+			array = animation->make_default_bezier_key(p_id.value);
```
Comment (mihe) [inline editor/animation_track_editor.cpp:4461]: Skip the intermediate `array` here and just assign straight to `value`.

**Review by mihe — CHANGES_REQUESTED** [review]

File: editor/animation_track_editor.cpp [hunk 3]
```diff
@@ -5269,12 +5264,7 @@ void AnimationTrackEditor::_insert_key_from_track(float p_ofs, int p_track) {
 			_find_hint_for_track(p_track, bp, &value);
 			Array arr;
 			arr.resize(5);
-			arr[0] = value;
-			arr[1] = -0.25;
-			arr[2] = 0;
-			arr[3] = 0.25;
-			arr[4] = 0;
-
+			arr = animation->make_default_bezier_key(value);
```
[the remark this answers is not in the document]
Comment (Arnklit) [reply editor/animation_track_editor.cpp]: done

File: scene/resources/animation.cpp [hunk 4]
```diff
@@ -3189,6 +3189,20 @@ StringName Animation::method_track_get_name(int p_track, int p_key_idx) const {
 	return pm->methods[p_key_idx].method;
 }
 
+Array Animation::make_default_bezier_key(float p_value) {
+	const float max_width = length / 2.0;
```
[the remark this answers is not in the document]
Comment (Arnklit) [reply scene/resources/animation.cpp]: done

**Review by TokageItLab — COMMENTED** [review]
The best approach is to share the calculation with the handle setting method in `bezier_track_set_key_handle_mode()`, which calculates a value that depends on the key interval. The default value is not defined for `HANDLE_SET_MODE_AUTO` when keying a newly created key, but in that case, I think the `HANDLE_MODE_BALANCED` or `HANDLE_MODE_MIRRORED` calculation should be applied. `HANDLE_MODE_MIRRORED` should be a concept closer to the current default in that it adopts a length that is x0.25 the interval-dependent length.

**Comment by Arnklit** [comment]
> The best approach is to share the calculation with the handle setting method in `bezier_track_set_key_handle_mode()`, which calculates a value that depends on the key interval. The default value is not defined for `HANDLE_SET_MODE_AUTO` when keying a newly created key, but in that case, I think the `HANDLE_MODE_BALANCED` or `HANDLE_MODE_MIRRORED` calculation should be applied. `HANDLE_MODE_MIRRORED` should be a concept closer to the current default in that it adopts a length that is x0.25 the interval-dependent length.

Happy to add that in. I had thought it would make more sense as a editor setting where you could change the default behavior. But if it can work for everything by default that is easier.

**Review by TokageItLab — APPROVED** [review]
Well, since follow up is possible later, I think it is enough as a stop gap for this inconvenient situation for now.

**Review by mihe — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
