### PR TITLE
Don't append standard ports to the request header.

### LINKED ISSUE #9146: HTTPRequest doesn't work with some https servers.
**Operating system or device - Godot version:**
linux 4.8, godot 2.1.3, godot tip

**Issue description:**

I made a simple test page, that demonstrates the effect:
https://www.capitanio.org/tests/godot/
A curl, wget, firefox, chromium, … doesn't have any problem,
so I think it's a godot issue. 

The URL https://www.capitanio.org/tests/godot/ok.html (apache server)
works fine, but the providers apache+php7 server for some reason doesn't
recognizes the godot's (ssl) request:  
```
extends HTTPRequest
request("https://www.capitanio.org/tests/godot/")
```
gives a response:
```
CERT STR: /CN=www.capitanio.org
VALID: 1
CONNECTION RESULT: 1
cert_ok: 1
result: 0
response_code: 400
headers: [Date: Tue, 13 Jun 2017 06:42:29 GMT, Server: Apache/2.4.25 (Unix), Content-Length: 362, Content-Type: text/html; charset=iso-8859-1, Vary: Accept-Encoding, Connection: close]
body.length: 362
body:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
</body></html>
```

This looks IMO correct:
```
diff --git a/thirdparty/openssl/ssl/ssl_lib.c b/thirdparty/openssl/ssl/ssl_lib.c
index 24be376..9e45af7 100644
--- a/thirdparty/openssl/ssl/ssl_lib.c
+++ b/thirdparty/openssl/ssl/ssl_lib.c
@@ -1052,6 +1052,14 @@ int SSL_write(SSL *s, const void *buf, int num)
         SSLerr(SSL_F_SSL_WRITE, SSL_R_PROTOCOL_IS_SHUTDOWN);
         return (-1);
     }
+
+    printf("XXXX SSL_write\n-=-");
+       for (int i = 0; i < num; i++) {
+               printf("%c", ((char *)buf)[i]);
+       }
+       printf("-=-\n");
+
+
     return (s->method->ssl_write(s, buf, num));
 }
```
prints out
```
XXXX SSL_write
-=-GET /tests/godot/ HTTP/1.1
Host: www.capitanio.org:443
User-Agent: GodotEngine/3.0.alpha.custom_build (X11)
Accept: */*

-=-
```

**Link to minimal example project:**

[network-test-gv3-02.zip](https://github.com/godotengine/godot/files/1070590/network-test-gv3-02.zip)

### PR DESCRIPTION
**Pull request by capnm**
Breaks the SSL communication with some servers,
follow the curl, wget, firefox & co

Fixes #9146

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@capnm Just to make sure, did you check if it runs fine with this change?

File: core/io/http_client.cpp [hunk 1]
```diff
@@ -96,7 +96,12 @@ Error HTTPClient::request_raw(Method p_method, const String &p_url, const Vector
 	};
 
 	String request = String(_methods[p_method]) + " " + p_url + " HTTP/1.1\r\n";
-	request += "Host: " + conn_host + ":" + itos(conn_port) + "\r\n";
+	if (ssl && conn_port == 443) {
```
Comment (bojidar-bg) [inline core/io/http_client.cpp]: I think you should also not add port 80 in case it is non-ssl.
Something like: (untested)
```c++
if ((ssl && conn_port == 443) || (!ssl && conn_port == 80)) {
	…
```
(applies to other if below as well)

**Comment by capnm** [comment]
> @capnm Just to make sure, did you check if it runs fine with this change?

Sure, the SSL connection works now  :sunglasses:
 
```
request: 'https://www.capitanio.org/tests/godot/' = 0
CERT STR: /CN=www.capitanio.org
VALID: 1
CONNECTION RESULT: 1
cert_ok: 1
XXXX SSL_write [122]
-=>GET /tests/godot/ HTTP/1.1
Host: www.capitanio.org
User-Agent: GodotEngine/3.0.alpha.custom_build (X11)
Accept: */*

<=-
result: 0
response_code: 200
headers: [Date: Tue, 13 Jun 2017 17:16:53 GMT, Server: Apache/2.2.31 (Unix), X-Powered-By: PHP/7.0.17, Cache-Control: max-age=60, Expires: Tue, 13 Jun 2017 17:17:53 GMT, Vary: Accept-Encoding, Content-Type: text/html, Transfer-Encoding: chunked]
body.length: 150
body:
<!DOCTYPE html>
<html>
<head>
<title>gogot https test</title>
<meta charset="utf-8" />
</head>
<body>
	<h1>Waiting for godot 3.1</h1>
</body>
</html>
```

**Comment by capnm** [comment]
> I think you should also not add port 80 in case it is non-ssl.

Ok, looks like it's also not appended by the other clients:

```
curl -vv http://capitanio.de:80/tests/godot/
*   Trying 81.169.145.149...
* Connected to capitanio.de (81.169.145.149) port 80 (#0)
> GET /tests/godot/ HTTP/1.1
> Host: capitanio.de
> User-Agent: curl/7.47.0
> Accept: */*
```

**Comment by capnm** [comment]
@bojidar-bg The godot http implementation has IMO generally a many subtle bugs, but it is ok, if you can control the server content. I've tested some random urls and everything seems to work atl least better as before :-)

Everything bellow ended with response_code: 200 + body:
```
request: 'http://www.capitanio.de:80/tests/godot/' = 0
GET /tests/godot/ HTTP/1.1
Host: www.capitanio.de

request: 'http://www.capitanio.de/tests/godot/' = 0
GET /tests/godot/ HTTP/1.1
Host: www.capitanio.de

request: 'http://www.capitanio.de:21/tests/godot/' = 0
GET /tests/godot/ HTTP/1.1
Host: www.capitanio.de:21

request: 'http://rpi.local:8888/doku.php' = 0
GET /doku.php HTTP/1.1
Host: rpi.local:8888

-----
request: 'http://google.com' = 0
GET / HTTP/1.1
Host: google.com

request: 'https://google.com' = 0
Host: google.com
XXXX SSL_write
-=-GET / HTTP/1.1
Host: google.com

----

request: 'https://github.com' = 0
Host: github.com
XXXX SSL_write
-=-GET / HTTP/1.1
Host: github.com

request: 'http://github.com:80' = 0
Host: github.com
````

**Comment by capnm** [comment]
@bojidar-bg This should be also cherry-picked to the 2.x  branch.

**Review by bojidar-bg — APPROVED** [review]
LGTM

**Comment by capnm** [comment]
@akien-mga could you cherrypick it to the 2.x branch as well?

**Comment by bojidar-bg** [comment]
@capnm I think he would do it when he starts getting 2.1.4 ready anyway.
