### PR TITLE
Attempt at fixing size mismatch in _compress_etc

### LINKED ISSUE #12710: _compress_etc - Expected data size of 16 in Image::create()
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 master (9437db7bc59a33b134306e8fa46eede2fb4ffde6)

**Issue description:**
While looking at the project in issue #10232 the following error was encountered when clicking on the "Particles" particle emitter in the DirectedParticles scene:
`ERROR: Expected data size of 16 in Image::create()
   At: core\image.cpp:1180`

I believe this is caused by image_etc.cpp Line 131 having a less strict test for mipmaps than Line 184 which leads to the size mismatch. See: https://github.com/godotengine/godot/blob/master/modules/etc/image_etc.cpp#L131

One fix could be to adjust the calculation of target_size as following to match L184:
`int target_size = Image::get_image_data_size(imgw, imgh, etc_format, mmc > 1 ? -1 : 0);`

However, should L184 and therefore L131 be `mmc > 0` instead of  `mmc > 1`? 
Also not sure if it would be better for line 184 to be changed to match 131 instead, or if this is the right fix in the first place really.

**Steps to reproduce:**

- Open project included in #10232
- Notice that assests are re-imported as there is no .imports folder
- Open DirectedParticles.tscn
- Click the "Particles" particle emitter

**Link to minimal example project:**
See #10232

### PR DESCRIPTION
**Pull request by ghost**
Fixes #12710 

This fixes the target_size being larger than the size calculated in `Image::create` caused when mmc is 1. 
I added the crash check because using the `mmc > 1 ` test rather than `mmc > 0` would memcpy out of bounds into `dst_data` if `mmc = 1` (which is the case in the test case described in that issue).

This does need another set of eyes though, as whilst this does stop the error I am not sure if this is the best or correct way to do so (e.g. do we actually want the mipmap if mmc is 1 or do we want to discard it?).

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @reduz and maybe @tagcup for review?

**Comment by tagcup** [comment]
mmc == 1 when there are no mipmaps if memory serves, so mmc > 1 should be OK

File: modules/etc/image_etc.cpp [hunk 1]
```diff
@@ -173,15 +174,17 @@ static void _compress_etc(Image *p_img, float p_lossy_quality, bool force_etc1_f
...
 		wofs += etc_data_len;
 
 		delete[] etc_data;
 		delete[] src_rgba_f;
 	}
+
 	print_line("time encoding: " + rtos(OS::get_singleton()->get_ticks_msec() - t));
 
-	p_img->create(imgw, imgh, mmc > 1 ? true : false, etc_format, dst_data);
+	p_img->create(imgw, imgh, uses_mipmaps, etc_format, dst_data);
```
Comment (tagcup) [inline modules/etc/image_etc.cpp]: Changing only this line to
```cpp
p_img->create(imgw, imgh, p_img->has_mipmaps(), etc_format, dst_data);
```
should work, no?

File: modules/etc/image_etc.cpp [hunk 2]
```diff
@@ -128,8 +128,9 @@ static void _compress_etc(Image *p_img, float p_lossy_quality, bool force_etc1_f
 
 	PoolVector<uint8_t>::Read r = img->get_data().read();
 
-	int target_size = Image::get_image_data_size(imgw, imgh, etc_format, p_img->has_mipmaps() ? -1 : 0);
 	int mmc = p_img->has_mipmaps() ? Image::get_image_required_mipmaps(imgw, imgh, etc_format) : 0;
```
Comment (tagcup) [inline modules/etc/image_etc.cpp]: Ah wait, this should probably be replaced with
```cpp
int mmc = (p_img->has_mipmaps() ? Image::get_image_required_mipmaps(imgw, imgh, etc_format) : 0) + 1;
```

Comment (akien-mga) [reply modules/etc/image_etc.cpp]: Does `mmc` stand for "mipmaps count"? If so I guess it should just be this, no?
```cpp
int mmc = p_img->has_mipmaps() ? Image::get_image_required_mipmaps(imgw, imgh, etc_format) : 1;
```

Comment (tagcup) [reply modules/etc/image_etc.cpp]: No there was little bit of inconsistency about the mipmap count, which is the source of confusion. Check it but if memory serves, get_image_required_mipmaps probably returns the number of mipmaps without counting the image with original size.

Comment (tagcup) [reply modules/etc/image_etc.cpp]: If only the cpp code had some bit of documentation

Comment (tagcup) [reply modules/etc/image_etc.cpp]: like at least what does this non-trivial function do

Comment (tagcup) [reply modules/etc/image_etc.cpp]: BTW I wanted to check this with a recent build but my console is being flooded with

```
WARNING: not found: display/window/size/width
WARNING: not found: display/window/size/height
```

Is it just me or is this a known issue?

Comment (akien-mga) [reply modules/etc/image_etc.cpp]: Likely a regression from d09160a8b67fdc60e8108962c4e9bd4c0bc7f13e

Comment (MillionOstrich) [reply modules/etc/image_etc.cpp]: on second look would calling `int mmc = p_img->get_mipmap_count() + 1;` be ok here?

Comment (tagcup) [reply modules/etc/image_etc.cpp]: Just checked, get_image_required_mipmaps does count the original size image as well, so it should indeed be
```cpp
int mmc = p_img->has_mipmaps() ? Image::get_image_required_mipmaps(imgw, imgh, etc_format) : 1;
```

or simply

```cpp
int mmc = Image::get_image_required_mipmaps(imgw, imgh, etc_format);
```

(given the work etc needs to do, that "optimization" isn't worth it anyway)

Comment (tagcup) [reply modules/etc/image_etc.cpp]: @MillionOstrich there shouldn't be a +1 because get_mipmap_count already counts the original image.
Also, the required # of mipmaps depends on the format, so the # of mipmaps of the original and etc may not match

Comment (tagcup) [reply modules/etc/image_etc.cpp]: 5cb1d06 fixed the "display/window/size/width" warning BTW

Comment (MillionOstrich) [reply modules/etc/image_etc.cpp]: @tagcup does that mean we want to remove the +1 from the for loop condition too?
`for (int i = 0; i < mmc + 1; i++) {`

Comment (tagcup) [reply modules/etc/image_etc.cpp]: looks that way
btw can you change the loop variable to j in the inner loop?

Comment (tagcup) [reply modules/etc/image_etc.cpp]: can you also check `modules/squish/image_compress_squish.cpp`? the code there should be more or less the same there so if there is a problem here, squish code would also need to be fixed

Comment (MillionOstrich) [reply modules/etc/image_etc.cpp]: I had a search around the codebase, `image_compress_squish` is using <= in the for loop for both compress and decompress. 

I also had a search for get_mipmap_count() as that calls the same method underneath -
 everything seems to be using +1:
```core\image.cpp(309): ERR_FAIL_INDEX_V(p_mipmap, get_mipmap_count() + 1, -1);
drivers\gles3\rasterizer_storage_gles3.cpp(772): int mipmaps = ((texture->flags & VS::TEXTURE_FLAG_MIPMAPS) && img->has_mipmaps()) ? img->get_mipmap_count() + 1 : 1;
editor\import\resource_importer_texture.cpp(245): int mmc = image->get_mipmap_count() + 1;
editor\import\resource_importer_texture.cpp(274): int mmc = image->get_mipmap_count() + 1;
modules\pvr\texture_loader_pvr.cpp(214): for (int i = 0; i <= new_img->get_mipmap_count(); i++) {
modules\squish\image_compress_squish.cpp(49): int mm_count = p_image->get_mipmap_count();
//^ uses <= in the loop later on
```

Results for `get_image_required_mipmaps`:
```modules\etc\image_etc.cpp(132): int mmc = p_img->has_mipmaps() ? Image::get_image_required_mipmaps(imgw, imgh, etc_format) : 1;
modules\squish\image_compress_squish.cpp(151): int mm_count = p_image->has_mipmaps() ? Image::get_image_required_mipmaps(w, h, target_format) : 0;
scene\resources\texture.cpp(591): int mipmaps = Image::get_image_required_mipmaps(tw, th, format);
```

The only case i can't see a +1 is in `texture.cpp:  StreamTexture::_load_data`, and that also has a >1 check too - but i don't understand what is happening in that method.

Comment (tagcup) [reply modules/etc/image_etc.cpp]: If you can confirm that it is indeed the case, the only change that is necessary would be

```cpp
p_img->create(imgw, imgh, p_img->has_mipmaps(), etc_format, dst_data);
```

Comment (tagcup) [reply modules/etc/image_etc.cpp]: or if you'd like to wait, I can give a proper check during weekend

**Comment by akien-mga** [comment]
So what's the status, do we still want to make changes or is it good as is?

**Comment by tagcup** [comment]
Sorry been a little busy recently
Based on the way other code is using the mipmap count, only changing mmc > 1 to mmc > 0 ir img->has_mipmaps should work, no? Or we can add 1 to where mmc is defined and adjust the rest accordingly

**Comment by akien-mga** [comment]
@reduz Can you have a look at the proposed change and discussion?

**Comment by MillionOstrich** [comment]
Updated this PR based on feedback.

- added 1 to mmc and changed loop condition to match
- use Image::has_mipmaps() to fix the call into Image::create() rather than inspecting mmc
- changed inner loop variable from i to j
