### PR TITLE
Avoid resetting the code completion popup excessively

### LINKED ISSUE #57027: Code completion popup interrupts itself even if contents are the same
### Godot version

3.4

### System information

Windows 7

### Issue description

When the idle autocomplete timer fires, it fully refreshes the autocomplete list, even if the contents are the same. This moves the cursor back up to the top of the list without a change in contents. The user might already be navigating the autocomplete list because there are many cases where it updates immediately upon input, so this is a usability problem.

IIRC this happens on master (4.x) as well.

### Steps to reproduce

Type something that autocompletes, but where typing a little more will keep the same autocomplete list, e.g. `Spatial.tra`. Navigate the autocomplete list immediately. Wait for the code complete timer to fire. The cursor will move back up to the top. Add a character to the text, e.g. `Spatial.tran`, do the same thing, observe the same thing.

Video for clarity:

https://user-images.githubusercontent.com/585488/150461716-74044e4c-55af-4ed4-a5f5-7d21ad519724.mp4

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by matorin57**
Fixes #57027. The issue was that `_filter_code_completion_candidates_impl` always resets the selected item. While up/down won't cause an update, there is a race condition where updating the list and then quickly changing selection will cause the selection to move and then reset. This can also happen even when the update doesn't actually change the list of options. 

The fix here was to have `_filter_code_completion_candidates_impl` check to see if the new options list is the same up to the currently selected item. Then we only reset the selection if the list differs before the selection. That way if the list only changes after the selection we won't reset. If the list changes before our selection, then we still want to reset as the selected item may no longer be meaningful.

This is done by building a new list and then comparing. There is an increased memory footprint in that we must hold two lists while doing the update, but once we are done we discard the old list. There is also a time increase in that we need to perform the list comparison (copying over the new list should be the same as clearing the old list and building the new one like we did originally). Considering that this lists will typically be small the time and memory hit should be unnoticeable from a UX standpoint. 

I also implemented it for the overridden version but I wasn't sure how to test that directly. But the tests for the non-overridden version should check the base logic. I am not 100% sure how this override system works so any notes and explanation would be appreciated.

I haven't squashed yet, but figured I was going to have to make some updates in the review anyway so will squash after the notes.

### CODE REVIEW

**Comment by Chaosus** [comment]
Thanks for your contribution. Please squash the commits as required by our pipeline (https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request)

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -3139,11 +3139,34 @@ void CodeEdit::_update_scroll_selected_line(float p_mouse_y) {
 	code_completion_force_item_center = -1;
 }
 
+/* Assumes both the new_options and the code_completion_options are sorted. */
```
Comment (YuriSizov) [inline scene/gui/code_edit.cpp:3142]: We don't use block comments, even if the comment itself is multiline. So please change all comments to use `//` (and in case of very long comments please wrap them manually at a reasonable breakpoint (the wrapping point is usually around 80 characters).

File: scene/gui/code_edit.cpp [hunk 2]
```diff
@@ -3139,11 +3139,34 @@ void CodeEdit::_update_scroll_selected_line(float p_mouse_y) {
...
+bool CodeEdit::_should_reset_selected_option_for_new_options(const Vector<ScriptLanguage::CodeCompletionOption> &new_options) {
```
Comment (YuriSizov) [inline scene/gui/code_edit.cpp:3143]: Method arguments must be prefixed with `p_` (same in the header).

```suggestion
bool CodeEdit::_should_reset_selected_option_for_new_options(const Vector<ScriptLanguage::CodeCompletionOption> &p_new_options) {
```

File: scene/gui/code_edit.cpp [hunk 3]
```diff
@@ -3139,11 +3139,34 @@ void CodeEdit::_update_scroll_selected_line(float p_mouse_y) {
...
+		/* If we are unequal at an element before the currently selected item we should reset as the elements before the currently selected item have changed. */
+		else if (code_completion_options[i].display != new_options[i].display) {
+			return true;
+		}
+	}
+	/*
+	 * If we are here, then we either exhuasted the smaller of the two lists or checked every option until the currently selected option in both.
+	 * The currently selected option must be inside the new list by here.
+	 * Therefore we should not reset, since the currently selected element is contained in the updated list and nothing up to it has changed.
+	 */
```
Comment (YuriSizov) [inline scene/gui/code_edit.cpp:3161]: I feel like this doesn't require such verbose and heavy commenting. The logic is pretty straightforward, and the amount of comments currently rivals the amount of lines of code.

**Comment by YuriSizov** [comment]
> I haven't squashed yet, but figured I was going to have to make some updates in the review anyway so will squash after the notes.

Yeah, that's fine. But when you do, please make sure to use a commit message that follows the project's style. The current title of this PR is a good option.

**Comment by matorin57** [comment]
Squashed commits and addressed feedback

File: scene/gui/code_edit.cpp [hunk 4]
```diff
@@ -3139,11 +3139,26 @@ void CodeEdit::_update_scroll_selected_line(float p_mouse_y) {
 	code_completion_force_item_center = -1;
 }
 
+// Assumes both the new_options and the code_completion_options are sorted.
+bool CodeEdit::_should_reset_selected_option_for_new_options(const Vector<ScriptLanguage::CodeCompletionOption> &p_new_options) {
+	if (code_completion_current_selected >= p_new_options.size())
+		return true;
```
Comment (AThousandShips) [inline scene/gui/code_edit.cpp:3145]:
```suggestion
	if (code_completion_current_selected >= p_new_options.size()) {
		return true;
	}
```
Always use brackets

File: tests/scene/test_code_edit.h [hunk 5]
```diff
@@ -3725,6 +3725,67 @@ TEST_CASE("[SceneTree][CodeEdit] completion") {
...
+		code_edit->set_caret_column(2);
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te1", "te1");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3");
+		code_edit->update_code_completion_options();
+		CHECK_MESSAGE(code_edit->get_code_completion_selected_index() == 0, "Initially selected item should be 0.");
+
+		// After adding later options shouldn't update selection.
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te1", "te1");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te4", "te4"); // Added te4
```
Comment (AThousandShips) [inline tests/scene/test_code_edit.h:3743]:
```suggestion
		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te4", "te4"); // Added te4.
```

File: tests/scene/test_code_edit.h [hunk 6]
```diff
@@ -3725,6 +3725,67 @@ TEST_CASE("[SceneTree][CodeEdit] completion") {
...
+		code_edit->update_code_completion_options();
+		CHECK_MESSAGE(code_edit->get_code_completion_selected_index() == 0, "Adding later options shouldn't update selection.");
+
+		code_edit->set_code_completion_selected_index(2);
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te1", "te1");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te4", "te4");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te5", "te5"); // Added te5
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te6", "te6"); // Added te6
```
Comment (AThousandShips) [inline tests/scene/test_code_edit.h:3752]:
```suggestion
		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te5", "te5"); // Added te5.
		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te6", "te6"); // Added te6.
```

File: tests/scene/test_code_edit.h [hunk 7]
```diff
@@ -3725,6 +3725,67 @@ TEST_CASE("[SceneTree][CodeEdit] completion") {
...
+		code_edit->update_code_completion_options();
+		CHECK_MESSAGE(code_edit->get_code_completion_selected_index() == 2, "Adding later options shouldn't update selection.");
+
+		// Removing elements after selected element shouldn't update selection.
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te1", "te1");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te4", "te4");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te5", "te5"); // Removed te6
```
Comment (AThousandShips) [inline tests/scene/test_code_edit.h:3760]:
```suggestion
		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te5", "te5"); // Removed te6.
```

File: tests/scene/test_code_edit.h [hunk 8]
```diff
@@ -3725,6 +3725,67 @@ TEST_CASE("[SceneTree][CodeEdit] completion") {
...
+		code_edit->update_code_completion_options();
+		CHECK_MESSAGE(code_edit->get_code_completion_selected_index() == 2, "Removing elements after selected element shouldn't update selection.");
+
+		// Changing elements after selected element shouldn't update selection.
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te1", "te1");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te4", "te4");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te6", "te6"); // Changed te5->te6
```
Comment (AThousandShips) [inline tests/scene/test_code_edit.h:3768]:
```suggestion
		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te6", "te6"); // Changed te5->te6.
```

File: tests/scene/test_code_edit.h [hunk 9]
```diff
@@ -3725,6 +3725,67 @@ TEST_CASE("[SceneTree][CodeEdit] completion") {
...
+		code_edit->update_code_completion_options();
+		CHECK_MESSAGE(code_edit->get_code_completion_selected_index() == 2, "Changing elements after selected element shouldn't update selection.");
+
+		// Changing elements before selected element should reset selection.
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te2", "te2"); // Changed te1->te2
```
Comment (AThousandShips) [inline tests/scene/test_code_edit.h:3773]:
```suggestion
		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te2", "te2"); // Changed te1->te2.
```

File: tests/scene/test_code_edit.h [hunk 10]
```diff
@@ -3725,6 +3725,67 @@ TEST_CASE("[SceneTree][CodeEdit] completion") {
...
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te4", "te4");
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te6", "te6");
+		code_edit->update_code_completion_options();
+		CHECK_MESSAGE(code_edit->get_code_completion_selected_index() == 0, "Changing elements before selected element should reset selection.");
+
+		// Removing elements before selected element should reset selection.
+		code_edit->set_code_completion_selected_index(2);
+		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3"); // Removed te2
```
Comment (AThousandShips) [inline tests/scene/test_code_edit.h:3782]:
```suggestion
		code_edit->add_code_completion_option(CodeEdit::CodeCompletionKind::KIND_VARIABLE, "te3", "te3"); // Removed te2.
```

File: scene/gui/code_edit.cpp [hunk 11]
```diff
@@ -3193,11 +3208,16 @@ void CodeEdit::_filter_code_completion_candidates_impl() {
 			if (theme_cache.font.is_valid()) {
 				max_width = MAX(max_width, theme_cache.font->get_string_size(option.display, HORIZONTAL_ALIGNMENT_LEFT, -1, theme_cache.font_size).width + offset);
 			}
-			code_completion_options.push_back(option);
+			code_completion_options_new.push_back(option);
 		}
 
+		code_completion_options_new.sort_custom<CodeCompletionOptionCompare>();
```
Comment (Paulb23) [inline scene/gui/code_edit.cpp:3214]: No need to sort here, as it's overridden allowing the user set it as they see fit

File: scene/gui/code_edit.cpp [hunk 12]
```diff
@@ -3139,11 +3139,26 @@ void CodeEdit::_update_scroll_selected_line(float p_mouse_y) {
 	code_completion_force_item_center = -1;
 }
 
+// Assumes both the new_options and the code_completion_options are sorted.
+bool CodeEdit::_should_reset_selected_option_for_new_options(const Vector<ScriptLanguage::CodeCompletionOption> &p_new_options) {
```
Comment (Paulb23) [inline scene/gui/code_edit.cpp:3143]: `.cpp` should follow the header ordering so this should be placed after `_filter_code_completion_candidates_impl`

File: scene/gui/code_edit.cpp [hunk 13]
```diff
@@ -3139,11 +3139,26 @@ void CodeEdit::_update_scroll_selected_line(float p_mouse_y) {
...
+	if (code_completion_current_selected >= p_new_options.size())
+		return true;
+
+	for (int i = 0; i < code_completion_options.size() && i < p_new_options.size(); i++) {
+		if (i > code_completion_current_selected) {
+			return false;
+		} else if (code_completion_options[i].display != p_new_options[i].display) {
```
Comment (Paulb23) [inline scene/gui/code_edit.cpp:3150]: `Nit`: Can remove the `else` here

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Thanks for the contribution!

Looks great with test as well, couple small comments left inline

**Comment by matorin57** [comment]
Addressed Feedback

**Review by Paulb23 — APPROVED** [review]
LGTM
