### PR TITLE
`AudioStreamWAV`: Check for `eof_reached` when reading LIST INFO tags

### LINKED ISSUE #116099: Loading a certain WAV file makes the editor hang
### Tested versions

- Reproducible in 4.6, 4.5

### System information

Godot v4.6.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 24 Jan 2026 00:47:39 +0000 on Wayland - Wayland display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon Graphics (radeonsi, renoir, ACO, DRM 3.64, 6.18.7-arch1-1) - AMD Ryzen 7 5800H with Radeon Graphics (16 threads) - 14.97 GiB memory

### Issue description

Importing or loading (`AudioStreamWAV.load_from_buffer`/`AudioStreamWAV.load_from_buffer`) the WAV file in the MRP (SFX from Quake 1) causes the editor hang forever.

As far as I investigated, this section causes the issue :

https://github.com/godotengine/godot/blob/377b5a31752ad5e9c53733639ba0d263e1158645/scene/resources/audio_stream_wav.cpp#L880-L890

### Steps to reproduce

Launch or just open the MRP

### Minimal reproduction project (MRP)

[69.02.09-wav.zip](https://github.com/user-attachments/files/25185382/69.02.09-wav.zip)

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Fixes #116099. Supersedes #116112 which touches code beyond the issue.

By analyzing the file, it seems to have a `LIST` chunk that not only is placed after `data` (which is usually the last), but also informs a size of 3,225,026,560 bytes, which is far beyond the end of the file.

This is an unusual case, but it can be solved by simply adding an `eof_reached` check that breaks the `INFO` loop (which honestly, should have been there long ago).

It will print an error in the editor, but it's reasonable for a file with invalid chunks.

### CODE REVIEW

File: scene/resources/audio_stream_wav.cpp [hunk 1]
```diff
@@ -906,6 +906,7 @@ Ref<AudioStreamWAV> AudioStreamWAV::load_from_buffer(const Vector<uint8_t> &p_st
 					tag_value.append_utf8(&text[0], text_size);
 
 					tag_map[tag] = tag_value;
+					ERR_BREAK_MSG(file->eof_reached(), "EOF reached while reading INFO chunk.");
```
Comment (Ivorforce) [inline scene/resources/audio_stream_wav.cpp]: I'd say it's fair to regard the whole file as corrupt in this case. Not sure how likely it is that the rest of the file will work.

```suggestion
					ERR_FAIL_COND_V_MSG(file->eof_reached(), Ref<AudioStreamWAV>(), "EOF reached while reading INFO chunk.");
```

**Review by Ivorforce — APPROVED** [review]
Thanks for taking care of this!

File: scene/resources/audio_stream_wav.cpp (hunk 1 above)
Comment (Ivorforce) [reply scene/resources/audio_stream_wav.cpp]: One more reason to just return from the whole function. If it's EOF there's nothing more in the file to read, so any further attempts will error anyway.

Comment (DeeJayLSP) [reply scene/resources/audio_stream_wav.cpp]: The file I tested still worked both in the editor and external players. In case some the LIST chunk is before the `data` chunk, the worst that can happen is an AudioStreamWAV resource with zero audio, as EOF in general is already handled.

Comment (Ivorforce) [reply scene/resources/audio_stream_wav.cpp]: Right. I guess maybe the better solution would be to reject reading audio files that don't have a data chunk, which we _could_ consider as corrupt.
We can consider this out of scope though, since you tested and say it works with a break I think it's fine to keep it as you have it.

**Review by gongpha — APPROVED** [review]
Tested with several ancient wav files. All of them were loaded fine !

**Review by Ivorforce — APPROVED** [review]

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.2.
