### PR TITLE
Fix current line highlight not extending into gutter

### LINKED ISSUE #115622: [4.6] CodeEdit - Highlight current line no longer extends into gutter
### Tested versions

Correct behaviour: 4.5.1
Incorrect behaviour: 4.6

### System information

Godot v4.6.stable.mono - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.8088) - Intel(R) Core(TM) i7-14700K (28 threads) - 47.72 GiB memory

### Issue description

CodeEdit - Highlight current line no longer extends into gutter. This can be seen in the godot editor itself.
The 4.5.1 behaviour seems more correct and ideal to me.

Godot 4.5.1:
Image

Godot 4.6:
Image

### Steps to reproduce

Open a script in Godot, observe.

### Minimal reproduction project (MRP)

N/A - observable in the godot code editor.

### PR DESCRIPTION
**Pull request by Manik2607**
Fixes regression where current line highlight no longer extends into the gutter area. The highlight now starts from left_margin instead of xmargin_beg, which includes the gutter width.

This restores the 4.5.1 behavior where the current line highlight spans the entire line including the gutter area.

- *Bugsquad edit:* Closes https://github.com/godotengine/godot/issues/115622

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -1403,9 +1403,9 @@ void TextEdit::_notification(int p_what) {
 					// Draw current line highlight.
 					if (highlight_current_line && highlighted_lines.has(Pair<int, int>(line, line_wrap_index))) {
 						if (rtl) {
-							RS::get_singleton()->canvas_item_add_rect(text_ci, Rect2(size.width - xmargin_end, ofs_y, xmargin_end - xmargin_beg, row_height), theme_cache.current_line_color);
+							RS::get_singleton()->canvas_item_add_rect(text_ci, Rect2(size.width - xmargin_end, ofs_y, xmargin_end - left_margin, row_height), theme_cache.current_line_color);
 						} else {
-							RS::get_singleton()->canvas_item_add_rect(text_ci, Rect2(xmargin_beg, ofs_y, xmargin_end - xmargin_beg, row_height), theme_cache.current_line_color);
+							RS::get_singleton()->canvas_item_add_rect(text_ci, Rect2(left_margin, ofs_y, xmargin_end - left_margin, row_height), theme_cache.current_line_color);
```
Comment (kitbdev) [inline scene/gui/text_edit.cpp]: To be more accurate to the 4.5.1 behavior, this should go all the way to the edge instead of to the left margin.
So it looks like this should use `0` instead of `left_margin`.

**Review by kitbdev — APPROVED** [review]
Looks good. Fixes the issue.
