### PR TITLE
Fix singleton scene cyclic loading

### LINKED ISSUE #69073: Editor deletes Autoloaded node's children
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows 10

### Issue description

When using a global auto-loaded node, the editor will delete the children of the node if they are referenced via a script.

This occurred in my project that is stable in Godot 4 beta 4 and I noticed right away that my one global node had most of the children deleted when I opened the project in Godot 4 beta 6.

I was able to recreate a minimum project with ease by setting up an auto-loaded node that has children and scripts that reference the global name.

I build the autoloaded node like this with two children:

Here is the raw text of the node:

After reloading the project, the editor has deleted my child nodes:

This is a major regression from Godot 4 beta 1, 2, 3, and 4.

### Steps to reproduce

1. Create a scene with a corresponding script and add it to as an auto-loaded global.
2. Create two child nodes with corresponding scripts and add them as children to the auto-loaded node. Create onready references to them in the auto-loaded node's script.
    
3. In one of the child node scripts, reference the other child of the auto-loaded node from the global reference.
    
5. Click Project > Reload Current Project
6. Open the auto-loaded node and observe that the editor has deleted it's child nodes.
    

### Minimal reproduction project

[editor-deletes-nodes.zip](https://github.com/godotengine/godot/files/10079156/editor-deletes-nodes.zip)

Attached is my minimum reproduction project. When you open the project, the editor will delete the child nodes before you can observe in the scene hierarchy. To prove that it is opening, I recommend opening the `singleton.tscn` node in an external editor, then opening in editor to observe that the nodes have been deleted. You can also re-add the child nodes, `map.tscn` and `ui.tscn`, and all appears well until you do the step I describe above to Reload the project, and you can observe that once again the children have been deleted.

### PR DESCRIPTION
**Pull request by adamscott**
This PR makes sure that any scene that is loaded through autoload is initialized and cached first, then it loads the scene.

This makes it so that `GDScriptCache::get_packed_scene()` can retreive that scene even if it's in the middle of its parsing.

Fixes #69073 where children nodes would try to load a new instance of the singleton, where chaos ensued.

### CODE REVIEW

**Comment by adamscott** [comment]
This fixes the MRP, but I don't know if it fixes every problem with singleton scenes. I'm having trouble with @KoBeWi's project.

**Comment by adamscott** [comment]
Using `GDScriptCache::get_packed_scene()` fixes every thing, even @KoBeWi's huge personal project issues. The problem is that we don't want to load necessarily `GDScriptCache` into `main.cpp` or other non-module files.

**Comment by akien-mga** [comment]
Maybe the PackedScene cache should be extracted from `GDScriptCache` into a core `PackedSceneCache`?

I remember there was something along those lines in one of the earlier attempts at solving this, not sure what the end result was.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -3125,14 +3125,19 @@ void GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode *p_ident
...
-						err = singl_parser->raise_status(GDScriptParserRef::INTERFACE_SOLVED);
-						if (err == OK) {
-							result = type_from_metatype(singl_parser->get_parser()->head->get_datatype());
+				if (GDScriptLanguage::get_singleton()->get_named_globals_map().has(name)) {
+					Variant constant = GDScriptLanguage::get_singleton()->get_named_globals_map()[name];
+					Node *node = Object::cast_to<Node>(constant);
+					if (node != nullptr) {
+						Ref<Script> scr = node->get_script();
+						if (scr.is_valid()) {
+							Ref<GDScriptParserRef> singl_parser = get_parser_for(scr->get_path());
```
Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:3134]: No need to meddle with `PackedScene` cache finally. Instead of loading the `PackedScene` to get the script, I forgot that I could get the instance of script through the node created with the `PackedScene` (which is accessible through global constants).

File: modules/gdscript/gdscript_cache.cpp [hunk 2]
```diff
@@ -365,31 +365,6 @@ Ref<PackedScene> GDScriptCache::get_packed_scene(const String &p_path, Error &r_
 	return scene;
 }
 
-Ref<GDScript> GDScriptCache::get_packed_scene_script(const String &p_path, Error &r_error) {
-	r_error = OK;
```
Comment (adamscott) [inline modules/gdscript/gdscript_cache.cpp:369]: I removed `GDScriptCache::get_packed_scene_script()` as it is not used anymore.

**Comment by jeffgamedev** [comment]
The artifacts built from this PR resolve all of my issues. Thank you!

**Review by akien-mga — APPROVED** [review]
Seems good to me.

I just notice a slight awkwardness with instantiating a scene, to then assign it to a `Ref<Resource>`, and then right after cast again to `Ref<PackedScene>` to check if it's a scene. This could maybe be refactored a bit, but that's not blocking for this PR.

**Comment by adamscott** [comment]
@akien-mga I can take the time to refactor it.

**Comment by adamscott** [comment]
Refactored it! If it's a scene, it will instantiate the scene after caching it. Took the time too to convert the error logs to use `vformat()` instead of string concatenation.

**Review by akien-mga — APPROVED** [review]
That's nice, the logic is easier to read now IMO with two clear branches.

**Comment by akien-mga** [comment]
Thanks!

File: modules/gdscript/tests/gdscript_test_runner.cpp [hunk 3]
```diff
@@ -71,27 +71,38 @@ void init_autoloads() {
...
-			StringName ibt = script->get_instance_base_type();
-			bool valid_type = ClassDB::is_parent_class(ibt, "Node");
-			ERR_CONTINUE_MSG(!valid_type, "Script does not inherit from Node: " + info.path);
+		if (ResourceLoader::get_resource_type(info.path) == "PackedScene") {
+			// Cache the scene reference before loading it (for cyclic references)
+			Ref<PackedScene> scn;
+			scn.instantiate();
+			scn->set_path(info.path);
+			scn->reload_from_file();
+			ERR_CONTINUE_MSG(!scn.is_valid(), vformat("Can't autoload: %s.", info.path));
```
Comment (rune-scape) [inline modules/gdscript/tests/gdscript_test_runner.cpp:81]: how would the scn `Ref` not be valid here if it was just instantiated? the next line uses the same check, did you mean `->is_valid()`
