### PR TITLE
Fix some bugs in the advanced scene import

### LINKED ISSUE #54807: Crash when selecting empty/placeholder material in Advanced Import Settings dialog
### Godot version

4.0

### System information

Arch Linux

### Issue description

When importing a model (ex: cube.gltf), if exported with placeholder materials, when you import it in Godot, and click on the material, the whole engine crashes.

image

### Steps to reproduce

1. Open Blender and create cube
2. Export as glTF and under Geometry->Materials, select Placeholder
3. Import in Godot and double click the file
4. Open Materials tab or Meshes tab
5. Click on the material icon
6. Crash

### Minimal reproduction project

[MaterialCrash.zip](https://github.com/godotengine/godot/files/7506192/MaterialCrash.zip)

### PR DESCRIPTION
**Pull request by trollodel**
Fix the following bugs:

- Start with the scene item selected, instead of showing an invalid view.
- Don't crash when selecting an unnamed material.
- Show `<Unnamed Material>` instead of no text for unnamed materials.

Fixes #54807

### CODE REVIEW

File: editor/import/scene_import_settings.cpp [hunk 1]
```diff
@@ -119,14 +125,12 @@ void SceneImportSettings::_fill_material(Tree *p_tree, const Ref<Material> &p_ma
...
 	TreeItem *item = p_tree->create_item(p_parent);
-	item->set_text(0, p_material->get_name());
-	item->set_icon(0, icon);
-
-	bool created = false;
-	if (!material_set.has(p_material)) {
-		material_set.insert(p_material);
-		created = true;
+	if (p_material->get_name().is_empty()) {
+		item->set_text(0, TTR("<Unnamed Material>"));
```
Comment (fire) [inline editor/import/scene_import_settings.cpp:129]: @Calinou Reviews welcome.

I would use the classname of the p_material with deduplication.

**Review by fire — COMMENTED** [review]
The rest of the changes aside from the naming of the empty material look ok on a cursory review.

File: editor/import/scene_import_settings.cpp (hunk 1 above)
Comment (Calinou) [reply editor/import/scene_import_settings.cpp:129]: I agree displaying a material ID somehow would be useful. I'd suggest using the form `[Unnamed Material 1234]`). Is there a prefereably deterministic material ID coming from the import system?

Comment (trollodel) [reply editor/import/scene_import_settings.cpp:129]: For what I understand from the import UI, the scene importer can provide a material ID.
But, if the ID is not provider, an autogenerated ID with a progressive number is created [here](https://github.com/godotengine/godot/pull/59834/files#diff-26e1bde2ef7dbe454265bd0a7abc7fea36035cc84786acfd3bce9ee40edc8228R110).
I can display that (or a formatted version), but it's not deterministic.

Comment (fire) [reply editor/import/scene_import_settings.cpp:129]: Having a non deterministic name is worse than an empty string.

**Comment by fire** [comment]
I recommend this pr be split into two prs. The unamed material has problems, but the other bug is good.

**Review by fire — DISMISSED** [review]
Requires a deteministic name or it will cause randomly changing version control commits and other problems like material overrides changing.

**Review by mhilbrunner — APPROVED** [review]
Approved in today's editor meeting.

Exploring adding a material ID to the default name would be worthwhile to explore (should be deterministic though) as per the comments/discussion, but that can be a followup PR.
We should fix these bugs and merge this in the mean time :)

File: editor/import/scene_import_settings.cpp (hunk 1 above)
Comment (Rindbee) [reply editor/import/scene_import_settings.cpp:170]: Different icons can be used here to distinguish whether the name is a deterministic material ID coming from the import system.

**Comment by akien-mga** [comment]
Thanks!
