### PR TITLE
Fix a rounding error in ColorPicker

### LINKED ISSUE #25063: Color encoding inconsistancy
**Godot version:**
master, commit 96899b7ee1cb442ce9625232d558670fe7011c2c

**OS/device including version:**
linux mint 18, 64bits

**Issue description:**
When encoding **127** on the any RGB channel in the color picker, the value saved in the tscn is _0.498039_. When scene is reloaded, the color picker displays **126**. This is particularly unpleasant when trying to have precise control over shader via textures.

**Steps to reproduce:**
Encode **127** in a Gradient via color picker, close the scene and reopen it.

**Solution proposal:**
Propose an option in the editor to encode colors in float [0,1] instead of int [0,255]. just like it is in opengl and in tscn... Might be tricky for non-coders, but much more precise for devs :)

Thanks in advance,

françois z.

### PR DESCRIPTION
**Pull request by Calinou**
This closes #25063. This also makes the spinboxes' "up" arrow work as expected (which was apparently broken before this change).

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -176,14 +176,15 @@ void ColorPicker::_update_color() {
...
-		scroll[i]->set_step(0.01);
 		if (raw_mode_enabled) {
+			scroll[i]->set_step(0.01);
 			scroll[i]->set_max(100);
 			if (i == 3)
 				scroll[i]->set_max(1);
 			scroll[i]->set_value(color.components[i]);
 		} else {
-			const int byte_value = color.components[i] * 255;
+			scroll[i]->set_step(1);
```
Comment (akien-mga) [inline scene/gui/color_picker.cpp]: For the reference, this had been changed in #18981 and then reverted in #18988, but I think the problematic change back then was forcing a max of `1` for the raw mode. Changing the step as done here should be fine.

Comment (akien-mga) [reply scene/gui/color_picker.cpp]: BTW we could likely set the raw mode max to `1.0` and enable `set_allow_greater(true)` now that the feature is available. But that's probably more stuff for after 3.1.

**Comment by akien-mga** [comment]
Thanks!
