### PR TITLE
Fix GDScript autocompletion with "as" or typed variables

### LINKED ISSUE #31818: Explicit types break contextual autocompletion
**Godot version:**
4f6eb36

**Issue description:**
...at least for AnimationPlayer. Here's a typed AnimationPlayer node variable:
image
Works as expected. But when we enforce the type to make sure it's AnimationPlayer:
image
The animations don't show.

### LINKED ISSUE #33434: Autocompletion may use wrong type if "as" is not used
**Godot version:**
3.2 beta1

**Issue description:**
Consider this code
```
export var target_path: NodePath
onready var target: Node2D = get_node(target_path)
onready var hinge = get_parent()
```
Now see this
image
Autocompletion doesn't suggest `position`. Looking at the list, looks like it assumes that `target` is of type Node. Using "as" like this
```
onready var target: Node2D = get_node(target_path) as Node2D
```
or this
```
onready var target := get_node(target_path) as Node2D
```
will fix the completion.
image
So looks like the variable has wrong type in the first case. The casting should be automatic.

(btw, notice how on the second image there's no suggestion for `get_postion_in_parent()`, but it's suggested if `position` is absent. Another case of #33425)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #31818, fixes #33434.

### CODE REVIEW

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -744,6 +744,14 @@ static bool _guess_expression_type(GDScriptCompletionContext &p_context, const G
 			r_type.type.kind = GDScriptParser::DataType::BUILTIN;
 			r_type.type.builtin_type = Variant::ARRAY;
 		} break;
+		case GDScriptParser::Node::TYPE_CAST: {
+			const GDScriptParser::CastNode *cn = static_cast<const GDScriptParser::CastNode *>(p_expression);
+			GDScriptCompletionIdentifier value;
+			if (_guess_expression_type(p_context, cn->source_node, r_type)) {
```
Comment (vnen) [inline modules/gdscript/gdscript_editor.cpp]: Do we really need to check the source node? We already have a resulting type from the cast as `cn->cast_type`, we should be able to just use that. Unless we use the actual type of `source_node` in this case.

Comment (bojidar-bg) [reply modules/gdscript/gdscript_editor.cpp]: We need the value from the source node, so that `($x as AnimationPlayer).play(..` autocompletes with animation names from `$x`.

Comment (vnen) [reply modules/gdscript/gdscript_editor.cpp]: Okay, that makes sense.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
