### PR TITLE
Validate supported architectures when exporting to Android

### LINKED ISSUE #36727: Android export: Validate .apk contents before exporting
**Godot version:**
3.2-stable, master (e2b66ca)

**OS/device including version:**
Export to Android from any OS.

**Issue description:**
When exporting to Android with custom-built templates, I often fall into the trap of having a custom template with only an armv7 or arm64v8 library, while my export preset has the other one enabled. (Or, on an arm64v8 capable device, having both armv7 and arm64v8 enabled but only armv7 provided will also reproduce the issue.)

In such case, the game will crash on the device and one has to dig through `adb logcat` to figure out that `libgodot_android.so` is missing.

We should perform a basic validation of the contents of the APK (at least checking that the libs are present for the enabled architectures in the preset) before allowing export. (Or, if we can't do that easily, the export should fail if the libs are found missing while creating the new APK.)

**Steps to reproduce:**
- Build custom APK with only `armv7`
- Export to arm64v8 device with `arm64-v8a` enabled.

CC @godotengine/android

### PR DESCRIPTION
**Pull request by SkyLucilfer**
Fix #36727 
androidCrashTestFull

### CODE REVIEW

File: platform/android/export/export.cpp [hunk 1]
```diff
@@ -1978,6 +1978,7 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 				for (int i = 0; i < enabled_abis.size(); ++i) {
 					if (file.begins_with("lib/" + enabled_abis[i] + "/")) {
 						enabled = true;
+						enabled_abis.remove(i);
```
Comment (SkyLucilfer) [inline platform/android/export/export.cpp]: Looking back I think modifying enabled_abis directly can be quite dangerous. As enabled_abis will be empty afterwards and this will cause errors if future code contributors use it.
I could create a copy of enabled_abis in a local scope and use it to do the check. After the scope the copy will be destroyed. What do you (Godot devs) think?

Comment (m4gr3d) [reply platform/android/export/export.cpp]: @SkyLucilfer using a local scope copy would be safer and would also help with clarifying the intent of the logic since given the current variable name, I had to double check to make sure I understood why you were doing.

File: platform/android/export/export.cpp [hunk 2]
```diff
@@ -2016,6 +2017,15 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 			ret = unzGoToNextFile(pkg);
 		}
 
+		if (!enabled_abis.empty()) {
+			String unsupported_arch = "";
+			for (int i = 0; i < enabled_abis.size(); i++)
+				unsupported_arch += enabled_abis[i] + ", ";
```
Comment (m4gr3d) [inline platform/android/export/export.cpp]: You can use the `String::join` method instead:
```
String unsupported_arch = ", ".join(enabled_abis);
```

File: platform/android/export/export.cpp [hunk 3]
```diff
@@ -2016,6 +2017,15 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
...
+			EditorNode::add_io_error("lib for the selected architectures : " + unsupported_arch + "is not found in the export template.\
```
Comment (m4gr3d) [inline platform/android/export/export.cpp]: I'd drop the `:` character from the error message.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Comment by SkyLucilfer** [comment]
@m4gr3d Thanks for the review! It helps me to improve. If there's still some flaws I could force push another commit.

File: platform/android/export/export.cpp [hunk 4]
```diff
@@ -1975,8 +1976,9 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 
 			if (file.ends_with(".so")) {
 				bool enabled = false;
-				for (int i = 0; i < enabled_abis.size(); ++i) {
-					if (file.begins_with("lib/" + enabled_abis[i] + "/")) {
+				for (int i = 0; i < invalid_abis.size(); ++i) {
+					if (file.begins_with("lib/" + invalid_abis[i] + "/")) {
```
Comment (m4gr3d) [inline platform/android/export/export.cpp]: While they are semantically the same, for clarity I'd use `enabled_abis` for the `for` loop size and for the file check:
```
for (int i = 0; i < enabled_abis.size(); ++i) {
    if (file.begins_with("lib/" + enabled_abis[i] + "/")) {
        invalid_abis.remove(i);
        ...
    }
}
```

This conveys that the logic is going through all the enabled abis and removing the valid ones from the invalid abis list.
It's also safer since the `invalid_abis.remove(i)` call can modify the value returned by `invalid_abis.size()`.

File: platform/android/export/export.cpp [hunk 5]
```diff
@@ -2016,6 +2018,13 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 			ret = unzGoToNextFile(pkg);
 		}
 
+		if (!invalid_abis.empty()) {
+			String unsupported_arch = String(", ").join(invalid_abis);
+			EditorNode::add_io_error("lib for the selected architectures" + unsupported_arch + "is not found in the export template.\
```
Comment (m4gr3d) [inline platform/android/export/export.cpp]: Seems you may need a space before `"is not found..."`.

**Review by m4gr3d — APPROVED** [review]

File: platform/android/export/export.cpp (hunk 4 above)
Comment (SkyLucilfer) [reply platform/android/export/export.cpp:1980]: In this case we should use `invalid_abis.erase(enabled_abis[i])`? 
```
for (int i = 0; i < enabled_abis.size(); ++i) {
    if (file.begins_with("lib/" + enabled_abis[i] + "/")) {
        invalid_abis.erase(enabled_abis[i]);
        ...
    }
}
```
With `invalid_abis.remove(i)` I'm afraid the index might not match afterwards because the invalid_abis vector will resize.

Alternatively I could use a bool array or bit array to mark the valid abis but when it comes to outputting the error string it becomes quite messy. Something like this 
```
//Checking valid abis
{
	String unsupported_arch = "";
	for (int i = 0; i < enabled_abis.size(); i++) {
		if (!valid_abis[i]) 
			unsupported_arch += enabled_abis[i] + ", ";
	}
	if (unsupported_arch != "") {
		EditorNode::add_io_error("lib for the selected architectures " + unsupported_arch + "is not found in the export template.\
		\nPlease uncheck the unsupported architectures in the export settings or add the required libs in the export template.");
		return ERR_FILE_NOT_FOUND;
	}
}
```

File: platform/android/export/export.cpp (hunk 5 above)
Comment (SkyLucilfer) [reply platform/android/export/export.cpp:2023]: Yea my bad I was having trouble compiling for Android on master branch so I didn't test it. 
This time I changed the line and tested it on 3.2
androidExportValidation

File: platform/android/export/export.cpp (hunk 4 above)
Comment (m4gr3d) [reply platform/android/export/export.cpp:1980]: Good point! Yes that should be `invalid_abis.erase(enabled_abis[i])`.

File: platform/android/export/export.cpp [hunk 6]
```diff
@@ -2016,6 +2018,13 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 			ret = unzGoToNextFile(pkg);
 		}
 
+		if (!invalid_abis.empty()) {
+			String unsupported_arch = String(", ").join(invalid_abis);
+			EditorNode::add_io_error("lib for the selected architectures " + unsupported_arch + " is not found in the export template.\
+				\nPlease uncheck the unsupported architectures in the export settings or add the required libs in the export template.");
```
Comment (akien-mga) [inline platform/android/export/export.cpp:2024]:
```suggestion
			EditorNode::add_io_error("Missing libraries in the export template for the selected architectures: " + unsupported_arch + ".\n"
				"Please build a template with all required libraries, or uncheck the missing architectures in the export preset.");
```

File: platform/android/export/export.cpp [hunk 7]
```diff
@@ -2016,6 +2018,13 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
...
+			return ERR_FILE_NOT_FOUND;
```
Comment (akien-mga) [inline platform/android/export/export.cpp:2025]: This should use `CLEANUP_AND_RETURN(ERR_FILE_NOT_FOUND);`, otherwise you'll leave a stray temporary APK in the cache.

File: platform/android/export/export.cpp [hunk 8]
```diff
@@ -2016,6 +2018,13 @@ class EditorExportPlatformAndroid : public EditorExportPlatform {
 			ret = unzGoToNextFile(pkg);
 		}
 
+		if (!invalid_abis.empty()) {
+			String unsupported_arch = String(", ").join(invalid_abis);
+			EditorNode::add_io_error("Missing libraries in the export template for the selected architectures: " + unsupported_arch + ".\n"
+				"Please build a template with all required libraries, or uncheck the missing architectures in the export preset.");
```
Comment (akien-mga) [inline platform/android/export/export.cpp:2024]: My bad, my previous suggestion doesn't pass the `clang-format` style guidelines. This works:
```suggestion
			EditorNode::add_io_error(
					"Missing libraries in the export template for the selected architectures: " + unsupported_arch + ".\n" +
					"Please build a template with all required libraries, or uncheck the missing architectures in the export preset.");
```

Comment (SkyLucilfer) [reply platform/android/export/export.cpp]: I think it worked with the previous suggestion, but it needed a lot of white spaces before the line "Please build a template..."
I tried deleting those white spaces and push without clang formatting. Then it failed.

Anyway, thanks a lot for the review and code suggestions !

**Comment by SkyLucilfer** [comment]
@akien-mga Is the last commit good?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
