### PR TITLE
GDScript: Fix and improve doc comment parsing

### LINKED ISSUE #78934: GDScript documentation comments: description tooltips are omitted when applied to @export variables with multiline arguments, as well as @export_category
### Godot version

4.1.rc2.mono.official

### System information

Godot v4.1.rc2.mono - EndeavourOS #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4400 (HSW GT2) () - Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 Threads)

### Issue description

When using [GDScript documentation comments](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html) to create description tooltips for [@export variables](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_exports.html), they do not show up in the editor if:

- The export variable requires arguments (eg. [@export_enum](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_exports.html#exporting-enums)), and the arguments are declared across more than 2 lines. [(recommended by GDScript style guide)](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#format-multiline-statements-for-readability)
- A description is applied to an [@export_category](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-export-category). 
  - This error also applies to all variables within the category

To illustrate, here are some screenshots from the included minimal reproduction project.

working

nonworking_multiline

nonworking_category

### Steps to reproduce

Copy-paste this code into a new node's script. A minimal reproduction project with all this prepared is included below for convenience.

```
extends Node


## This shows up in the editor.
@export_enum("example1", "example2",) var good_enum


## [i]This shows up in the editor, but goes against recommended practices.[/i]
@export_enum(
	"example1", "example2",) var poor_practice_multiline


## THIS DOES NOT SHOW UP IN THE EDITOR.
@export_enum(
	"example1",
	"example2",
) var bad_enum

## THIS DOES NOT SHOW UP IN THE EDITOR.
@export_category("Categories truncate comments")

## THIS DOES NOT SHOW UP IN THE EDITOR.
@export var bad: int
```

### Minimal reproduction project

[tooltip-bug.zip](https://github.com/godotengine/godot/files/11928865/tooltip-bug.zip)

### LINKED ISSUE #81578: Generated documentation for single line enum duplicates the same documentation for each enumeration
### Godot version

v4.2.master.custom_build [98b50eb30]

### System information

Ubuntu 20.04 LTS

### Issue description

Reproducible on 4.2dev3, 4.2dev4, and master.
This is not reproducible on 4.1.1-stable and 4.2dev1 (4.2dev2 crashed).

By `single line enum` I mean:
```
## My documentation
enum MyEnum { A, B, C }
```
The generated documentation looks like this:
enumdocumentationbug

The generated documentation for an enum formatted like this
```
## My documentation
enum MyEnum {
  A,
  B,
  C
}
```
looks correct
enumdocumentationbug_good

### Steps to reproduce

1. Attach a script to a node
2. Add this:
```
## My documentation
enum MyEnum { A, B, C }
```
3. Open the documentation for that node

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #78934.
* Closes #81578.

1\. Handle annotations correctly.

2\. Handle inline doc comments on multiline declarations. Now this works:

```gdscript
func my_func(): ## Doc.
    pass

class MyClass: ## Doc.
    pass
```

3\. Handle the case of multiple declarations on the same line.

4\. Add `@tag` support for inline doc comments.

<details>
<summary>Test script</summary>

```gdscript
## desc 1
var a1; var a2; var a3 ## desc 2

var b1; var b2; var b3 ## desc 3

## desc 4
var c1; var c2; var c3

enum E1 { A, B, C } ## desc 5

## desc 6
enum E2 { A, B, C }

enum E3 { ## desc 7
    A, B, C
}

enum E4 {
    ## desc 8
    A, B, C
}

enum E5 {
    A, B, C ## desc 9
}

enum E6 {
    A,
    B, ## desc 10
    C,
}

enum E7 { ## desc 11
    A, ## desc 12
    B, ## desc 13
    C, ## desc 14
}
```

</details>

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -1263,6 +1264,9 @@ GDScriptParser::EnumNode *GDScriptParser::parse_enum(bool p_is_static) {
 
 	push_multiline(true);
 	consume(GDScriptTokenizer::Token::BRACE_OPEN, vformat(R"(Expected "{" after %s.)", named ? "enum name" : R"("enum")"));
+#ifdef DEBUG_ENABLED
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp:1267]:
```suggestion
#ifdef TOOLS_ENABLED
```

**Review by adamscott — APPROVED** [review]
Approved by the GDScript team. It even reduces the number of lines! That's awesome, thanks @dalexeev

**Comment by akien-mga** [comment]
Thanks!
