### PR TITLE
Windows: Always double-quote path when launching explorer.exe to browse

### LINKED ISSUE #78949: Project Manager, comma in project name, breaks open project folder button
### Godot version

v4.1.rc2.official [46424488e]

### System information

Godot v4.1.rc2 - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GTX 550 Ti () - Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 Threads)

### Issue description

In the Project Manager.
With a project that has a comma in the name, for example: `one, two`

When the open project folder button is pressed, then two issues can occur:
- If there is no other project with the name before the comma: `one`
Then the default Godot project folder opens: `C:/Users/username/Documents`
- If there is another project with the name: `one`
Then the `one` project folder opens.
(the project `one` doesn't need to be listed in the Project Manager, 
it just has to exist in the same folder as the `one, two` folder)

Expected:
The `one, two` project folder should open.

Notes:
The open project folder button works when there isn't a comma in the project name.
For example: `three`, or `three four`

### Steps to reproduce

- Download the attached zip file: [two projects.zip](https://github.com/godotengine/godot/files/11929652/two.projects.zip)
- Extract the zip file into an empty folder.
- Open the Godot Project Manager.
- Scan the extracted folder.
There should now be two projects with the names: `one` and `one, two`.
- Click on the `one, two` projects, open project button, to the left of the project path.

### Observed

The project `one` folder opens.

### Expected

The project `one, two` folder should have opened.

### Continued reproduction steps
- Now remove the `one` folder from the extracted folder.
It doesn't matter that it's still listed in the Project manager.
- Click on the `one, two` projects, open project button.

### Observed 2

Now the default Godot project folder opens: `C:/Users/username/Documents`

### Expected 2

Same as above, the `one, two` project folder should have opened.

### Minimal reproduction project

[two projects.zip](https://github.com/godotengine/godot/files/11929652/two.projects.zip)

### PR DESCRIPTION
**Pull request by bgie**
Fixes #78949

Code now always double quotes the filename to use as command line argument when calling 'explorer.exe'. In particular, commas in a filename would be interpreted by 'explorer.exe' as separators for commands.

Fixed the logic logic where existing leading or trailing double quotes in the filename were duplicated, instead of adding them when they were missing.

Similarly a `trim_suffix` for "file://" is assumed to be a mistake, this could potentially be a _pre_fix that we want to strip, but never a suffix. 

Judging from [the commit](https://github.com/godotengine/godot/pull/69698) that first introduced the `OS_Windows::shell_show_in_file_manager` function I would guess that stripping "file://" was some intermediate decision that might not be needed in the end, and never even worked. The old code would prefix "file://" at several locations, but this was all moved to the base implementation of shell_show_in_file_manager, and the new windows implementation never prefixes, so there is no need for trimming.

Maybe trimming the prefix could be dropped altogether, but I'm playing safe. I do not know if there are usages of this method that I am unaware of. If this method is exposed to GDScript or plugins use it, that code could still be prefixing "file://", hence we need to strip it for the windows version.

### CODE REVIEW

**Comment by bgie** [comment]
Tested this myself on Windows 11 Pro

- tested bug #78949 which opens a project folder from the project manager
- tested the 'show in file manager' action which opens a folder and highlights the selected file.

**Review by akien-mga — APPROVED** [review]
Looks like 3 straightforward typo fixes.

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -1356,17 +1356,17 @@ Error OS_Windows::shell_open(String p_uri) {
 }
 
 Error OS_Windows::shell_show_in_file_manager(String p_path, bool p_open_folder) {
-	p_path = p_path.trim_suffix("file://");
+	p_path = p_path.trim_prefix("file://");
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp:1359]: Given that this would never have worked, it might indeed be unnecessary and could be removed I think.

I expect `explorer.exe` would handle a path with `file://` just fine, no?

**Comment by akien-mga** [comment]
I pushed my suggested changes, but didn't test (I'm on Linux). CC @bruvzg

**Review by bruvzg — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.
