### PR TITLE
Fix equal operation for typed enums

### LINKED ISSUE #49278: Incorrect invalid operands when using enums
**Godot version:**
Godot master af3ebc96ed07810e001824743fbce1e01f565079

**OS/device including version:**
any

**Issue description:**
When using enums comparisons give a bogus invalid operands error

**Steps to reproduce:**
Use the following code:
```
extends Node

enum Test { ONE, TWO }
var test : Test = Test.ONE

func testing():
	if test == Test.TWO:
		# this is a test
		pass
```

We now get the error ` "Invalid operands "Test (enum)" and "TWO (enum value)" for "==" operator.` on the if statement

### PR DESCRIPTION
**Pull request by SpectralDragon**
# Summary

Fix #49278

Screen proof: 
image

## How I Fix it

`op_binary` can't compare two `builtin_type`. **ENUM_VALUE** returns `Variant::NIL` and **ENUM** returns `Variant::DICTIONARY`. Problem was in default value for `builtin_type`, because for **ENUM_VALUE** we don't set builtin_type and using default `Variant::NIL`
image

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1779,10 +1779,10 @@ void GDScriptAnalyzer::reduce_binary_op(GDScriptParser::BinaryOpNode *p_binary_o
 	} else {
 		if (p_binary_op->variant_op < Variant::OP_MAX) {
 			bool valid = false;
-			result = get_operation_type(p_binary_op->variant_op, p_binary_op->left_operand->get_datatype(), right_type, valid, p_binary_op);
+			result = get_operation_type(p_binary_op->variant_op, left_type, right_type, valid, p_binary_op);
```
Comment (SpectralDragon) [inline modules/gdscript/gdscript_analyzer.cpp:1782]: Just for readability, because `left_type` was assigned above

**Review by phocodes — APPROVED** [review]
yes. This looks good!

**Comment by akien-mga** [comment]
For the reference, the email used to author your commit (see header of https://github.com/godotengine/godot/commit/6449c5f2464076ab51d4955bf5b8e627beefb8ce.patch) is not linked to your GitHub account, which is why the commit doesn't appear authored by your @SpectralDragon account. It's not a problem for Git or GitHub, but if you want to have your GitHub account credited for the contribution, you can add this email as secondary email in your settings.

**Comment by SpectralDragon** [comment]
I’ll update it a couple of hours

**Comment by SpectralDragon** [comment]
@akien-mga I added my email as secondary to Github. Thanks for suggestion!

**Review by akien-mga — APPROVED** [review]
PR looks good to me, but I'll let @vnen confirm the fix as he's more familiar with GDScript.

**Comment by SpectralDragon** [comment]
@vnen can you look at this PR?

**Review by vnen — APPROVED** [review]
I feel like there's something wrong elsewhere, but this fix is correct in any case. Sorry for the delay in reviewing it.

**Comment by vnen** [comment]
Thanks!
