### PR TITLE
2D: Fix clip children and rendering artefacts

### LINKED ISSUE #102147: `CanvasItem.clip_children` has no effect
### Tested versions

- Reproducible in: 4.4.beta [a013481b0911e59cc3f3dea7ebb732450c3e1460]
- Not reproducible in: 4.4.beta1 [d33da79d3f8fe84be2521d25b9ba8e440cf25a88]

### System information

Godot v4.4.beta (a013481b0) - Windows 11 (build 26100) - Multi-window, 3 monitors - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 32.0.11029.1008) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 threads)

### Issue description

The `CanvasItem` property `clip_children`, which is meant to allow the parent to act as a mask for any of its `CanvasItem` children, seemingly has no effect in current `master` (a013481b0911e59cc3f3dea7ebb732450c3e1460).

Here's what it looked like in 4.4-beta1:

Image

Here's what it looks like now:

Image

### Steps to reproduce

- Open the MRP in latest `master`.
- Observe the issue.

### Minimal reproduction project (MRP)

[clip-children-bug-4.4.zip](https://github.com/user-attachments/files/18585252/clip-children-bug-4.4.zip)

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #102147

Fixes both GLES3 and RendererRD implementations

> [!NOTE]
>
> This fix also addresses the root cause of #101998, which was that instance buffers were reused in the same draw call, causing rendering artefacts.

<details>
<summary>Both issues resolved</summary>

| clip children | rendering artefact |
| :---- | :---- |
|  |  |

</details>

### CODE REVIEW

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 1]
```diff
@@ -1567,7 +1567,9 @@ void RasterizerCanvasGLES3::_add_to_batch(uint32_t &r_index, bool &r_batch_broke
 
 void RasterizerCanvasGLES3::_new_batch(bool &r_batch_broken) {
 	if (state.canvas_instance_batches.size() == 0) {
-		state.canvas_instance_batches.push_back(Batch());
+		Batch new_batch;
+		new_batch.instance_buffer_index = state.current_instance_buffer_index;
```
Comment (stuartcarnie) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:1571]: We need to start at the last instance buffer, even when starting the first batch. This is 0 when starting a new canvas draw, but will be non-zero if there are multiple draws in a single canvas draw.

**Review by clayjohn — APPROVED** [review]
Makes sense

**Comment by Repiteo** [comment]
Thanks!
