### PR TITLE
Make TileMapLayer editor match layer's filter

### LINKED ISSUE #52332: Non-matching texture filtering mode for cursor preview in new tilemap editor
### Godot version

4.0.dev.custom_build [a160a95ea]

### System information

W10, Vulkan, NVIDIA GeForce GTX 1080

### Issue description

When drawing on tilemaps using the new tilemap feature, the transparent preview of the tile under the drawing cursor always uses linear filtering.

It looks like this when the TileMap's filter mode is set to Nearest:

image

It should probably match whichever filter mode the TileMap is assigned to use, rather than assuming Linear.

### Steps to reproduce

1. Create a tileset with a tile.
2. Create a tilemap node and use the tileset to paint that tile.
3. Compare the tile preview to the painted tiles.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #52332

https://github.com/user-attachments/assets/e5ed35d8-ca8f-4d1f-90ad-63572e2550fb

### CODE REVIEW

**Comment by groud** [comment]
Ah, you add a new control on the top of the other overlay one. I guess that's a good approach. The only texture drawn there is indeed the preview, so I am not worried the filter would apply wrongly to some other texture.

So well, LGTM.

**Review by groud — APPROVED** [review]

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 1]
```diff
@@ -4280,8 +4264,21 @@ bool TileMapLayerEditor::forward_canvas_gui_input(const Ref<InputEvent> &p_event
...
 
 void TileMapLayerEditor::forward_canvas_draw_over_viewport(Control *p_overlay) {
+	if (!custom_overlay) {
+		custom_overlay = memnew(Control);
+		custom_overlay->set_anchors_and_offsets_preset(Control::PRESET_FULL_RECT);
+		custom_overlay->set_mouse_filter(Control::MOUSE_FILTER_IGNORE);
+		custom_overlay->set_clip_contents(true);
+		custom_overlay->set_draw_behind_parent(true);
+		p_overlay->add_child(custom_overlay);
+		custom_overlay->connect("draw", callable_mp(this, &TileMapLayerEditor::_draw_overlay));
```
Comment (AThousandShips) [inline editor/plugins/tiles/tile_map_layer_editor.cpp]:
```suggestion
		custom_overlay->connect(SceneStringName(draw), callable_mp(this, &TileMapLayerEditor::_draw_overlay));
```

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
