### PR TITLE
Prevent error message when try to get blend point name at first time

### LINKED ISSUE #118943: BlendSpace1D throws a "get_blend_point_name: Index p_point = -1 is out of bounds" error when used
### Tested versions

Reproducible in:
v4.7.beta1.official [1c8cc9e7e]

Not reproducible in:
v4.7.dev3.official [60fff00a6]

### System information

Godot v4.7.dev3 - Windows 10 (build 19045) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1060 3GB (NVIDIA; 32.0.15.8180) - Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 threads) - 15.95 GiB memory

### Issue description

Godot seems to throw a (harmless?) error when you use BlendSpace1D with any setup.
BlendSpace2D Doesn't seem to have this issue. At least I couldn't cause it.

Image

### Steps to reproduce

https://github.com/user-attachments/assets/33523a44-2ec5-406d-8023-2c41559e3048

1. Create an animation tree. Assign it an animation player with animations and give it a blendtree
2. Make a BlendSpace1D. Give it any 2 animations
3. Launch the project. Godot will throw an error

Or just open the MRP and launch it (the editor will throw an error too when you load the project)

### Minimal reproduction project (MRP)

[blendspaceerror_2026-04-25_09-09-58.zip](https://github.com/user-attachments/files/27079020/blendspaceerror_2026-04-25_09-09-58.zip)

### PR DESCRIPTION
**Pull request by xuhuisheng**
- Fixes https://github.com/godotengine/godot/issues/118943

## Issue Description

When we try get blend point name at first time, the `cur_closest` is `-1`. So the assertion will report an error message.

https://github.com/godotengine/godot/blob/6d6e822c689acb54bf86e19cc2bbbe3fa567b123/scene/animation/animation_blend_space_1d.cpp#L231-L235

It won't break the flow, as `get_child_instance_by_path_or_null()` can handle the `null` situation.

https://github.com/godotengine/godot/blob/6d6e822c689acb54bf86e19cc2bbbe3fa567b123/scene/animation/animation_blend_space_1d.cpp#L559

## Solution

Checking `cur_closest` to consider whether calling `get_blend_point_name()`, then we can prevent the error message.

### CODE REVIEW

File: scene/animation/animation_blend_space_1d.cpp [hunk 1]
```diff
@@ -556,7 +556,7 @@ AnimationNode::NodeTimeInfo AnimationNodeBlendSpace1D::_process(ProcessState &p_
 	}
 
 	// Special case for discrete carry.
-	AnimationNodeInstance *instance_current_closest = p_instance.get_child_instance_by_path_or_null(get_blend_point_name(cur_closest));
+	AnimationNodeInstance *instance_current_closest = p_instance.get_child_instance_by_path_or_null(cur_closest > 0 ? get_blend_point_name(cur_closest) : StringName());
```
Comment (TokageItLab) [inline scene/animation/animation_blend_space_1d.cpp]:
```suggestion
```
This is an unused variable and appears to be a mistake made during the rebase. Simply deleting it should suffice.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: scene/animation/animation_blend_space_1d.cpp (hunk 1 above)
Comment (xuhuisheng) [reply scene/animation/animation_blend_space_1d.cpp]: But 'instance_current_assest' is used in the following line. I'm afraid it won't compile.

https://github.com/godotengine/godot/blob/6d6e822c689acb54bf86e19cc2bbbe3fa567b123/scene/animation/animation_blend_space_1d.cpp#L566

Comment (TokageItLab) [reply scene/animation/animation_blend_space_1d.cpp]: So it should be

```cpp

	// Special case for discrete carry.
	if (new_closest != cur_closest && new_closest != -1 && cur_closest != -1 && blend_mode == BLEND_MODE_DISCRETE_CARRY && sync_mode < SYNC_MODE_CYCLIC_MUTABLE) {
		AnimationNodeInstance *instance_current_closest = p_instance.get_child_instance_by_path_or_null(get_blend_point_name(cur_closest));
		AnimationNodeInstance *instance_new_closest = p_instance.get_child_instance_by_path_or_null(get_blend_point_name(new_closest));
```

as same with BlendSpace2D.

Comment (xuhuisheng) [reply scene/animation/animation_blend_space_1d.cpp]: Yes, it should be handled like 'BlendSpace2D'.

**Review by TokageItLab — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
