### PR TITLE
Prevent axis-based actions from getting stuck

### LINKED ISSUE #81164: Axis-based actions can get stuck as pressed
### Godot version

4.2 bc88dca

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

After #80859 if you have an action that uses joypad axis, it can get stuck very easily and don't get released until more input. The `pressed` counter can go above 1, because multiple pressed events are received in a row, without equivalent release events that would release the action.

### Steps to reproduce

1. Create an action that uses joypad axis event
2. Start the project and press the action a few times
3. Eventually it will not release

### Minimal reproduction project

[BrokenAxis.zip](https://github.com/godotengine/godot/files/12476218/BrokenAxis.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #81164

Not sure how much correct is that. This assumes that only InputEventJoypadMotion has this problem and that you have only single axis event assigned to an action (which is true in 99.9% cases). Also a special handler for one event type feels hacky.

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -701,6 +701,16 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
...
+					if (iejm.is_valid()) {
+						if (action.axis_pressed) {
+							// If axis is already pressed, don't increase the pressed counter.
+							action.pressed--;
+						} else {
+							action.axis_pressed = true;
+						}
+					}
+
 					action.pressed++;
```
Comment (Sauermann) [inline core/input/input.cpp:714]: Decreasing and afterwards increasing `action.pressed` seems to be more difficult to understand.
What do you think about the following?
```suggestion
					Ref<InputEventJoypadMotion> iejm = p_event;
					if (iejm.is_valid()) {
						if (!action.axis_pressed) {
							action.pressed++;
							action.axis_pressed = true;
						}
					} else {
						action.pressed++;
					}
```

File: core/input/input.cpp [hunk 2]
```diff
@@ -701,7 +701,17 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
 
 			if (!p_event->is_echo()) {
 				if (p_event->is_action_pressed(E.key)) {
-					action.pressed++;
+					Ref<InputEventJoypadMotion> iejm = p_event;
+					if (iejm.is_valid()) {
```
[the remark this answers is not in the document]
Comment (Sauermann) [reply core/input/input.cpp]: @KoBeWi I believe, that my intention got lost. `jm` is already set a few lines above:

https://github.com/godotengine/godot/blob/bc88dca176cef6b8943ded58c68a60f7c127baea/core/input/input.cpp#L681

**Review by Sauermann — APPROVED** [review]
This is difficult to review, because I cant test the PR.
I'm not sure if there is a better way to fix the bug, but I can follow the argumentation of the shortcomings in the OP and understand the changes.

So this is a "it will not worsen the situation" review approval.

**Comment by Calinou** [comment]
This doesn't appear to work great on my end (using keyboard and DualSense at the same time):

https://github.com/godotengine/godot/assets/180032/c3283894-fe4f-4e4f-a8c1-761a65332f97

CheckBox indicates state of `is_action_pressed()`, left ProgressBar is the action strength, right Progressbar is the action raw strength.

**Testing project:** [test_analog_and_digital_input_2.zip](https://github.com/godotengine/godot/files/12480268/test_analog_and_digital_input_2.zip)

File: core/input/input.cpp [hunk 3]
```diff
@@ -713,6 +722,7 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
 						action.released_process_frame = Engine::get_singleton()->get_process_frames();
 					}
 					action.pressed = MAX(action.pressed - 1, 0);
+					action.axis_pressed = false;
```
Comment (Sauermann) [inline core/input/input.cpp:725]: I believe, that it is possible to fix comment https://github.com/godotengine/godot/pull/81170#issuecomment-1699867615 with:
``` c++
					if (jm.is_valid()) {
						if (action.axis_pressed) {
							if (action.pressed == 1) {
								action.released_physics_frame = Engine::get_singleton()->get_physics_frames();
								action.released_process_frame = Engine::get_singleton()->get_process_frames();
							}
							action.pressed = MAX(action.pressed - 1, 0);
							print_line("p3=", action.pressed);
							action.axis_pressed = false;
						}
					} else {
						action.pressed--;
					}
```

Comment (KoBeWi) [reply core/input/input.cpp:725]: Found a simpler solution.

**Comment by KoBeWi** [comment]
Fixed. It was the same issue - the action was released multiple times in a row.
Thinking again, the issue makes sense. Axis actions are pressed based on the deadzone, so if you receive multiple events above or below deadzone, the action state will change abnormally.

File: core/input/input.cpp [hunk 4]
```diff
@@ -701,18 +701,33 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
...
+
 					is_pressed = true;
 					if (action.pressed == 1) {
 						action.pressed_physics_frame = Engine::get_singleton()->get_physics_frames();
 						action.pressed_process_frame = Engine::get_singleton()->get_process_frames();
 					}
 				} else {
+					if (jm.is_valid() && !action.axis_pressed) {
+						// Same as above. Don't release axis when not pressed.
+						continue;
```
Comment (Sauermann) [inline core/input/input.cpp:722]: The `continue;` will skip over the line

``` c++
action.exact = InputMap::get_singleton()->event_is_action(p_event, E.key, true);
```
and will skip over the section
```c++
if (is_pressed || action.pressed == 0) {
	action.strength = p_event->get_action_strength(E.key);
	action.raw_strength = p_event->get_action_raw_strength(E.key);
}
```

That means, that for such InputEvents, the attributes `exact`, `strength` and `raw_strength` no longer get updated. This doesn't seem like expected behavior.

Comment (KoBeWi) [reply core/input/input.cpp:722]: Not sure about exact, but the second condition will be false (the event is not pressed).

Comment (Sauermann) [reply core/input/input.cpp:722]: `exact` could be solved by moving the assignment above the if-else-clause.

> Action strength for released events is irrelevant.

Before #80859, strength was set set even for released InputEvents, so it was accessible to users. At the moment I don't see any reason for changing this behavior.

**Review by Sauermann — APPROVED** [review]
Origin for this PR is #80859, which originally intended to fix #45628. Since I can't replicate that issue, I can't verify that.

#80859 introduced #81164 which this PR intends to fix. I can confirm #81164 in v4.2.dev4.official [549fcce5f] 
With this PR applied to v4.2.dev.custom_build [fb4edf50d], I tried for over a minute to cause, #81164 but was unsuccessful to do that. So I am confident, that this PR fixes that issue.

Comment https://github.com/godotengine/godot/pull/81170#issuecomment-1699867615 mentioned a problem, that a previous version of this PR introduced and I have tested and can confirm, that this has been fixed in the latest update.

The concerns of my comments regarding the implementation also have been solved.

**Review by akien-mga — APPROVED** [review]
Seems to work fine, and I don't see any regression on the joypads demo.

**Comment by akien-mga** [comment]
Thanks!
