### PR TITLE
GDScript compiler inner class bugfixes

### LINKED ISSUE #61268: GDScript 2.0: Subclass member with type of another script's subclass does not get assigned correctly
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

Windows 10

### Issue description

(I tried my best with the title, I swear.)

In GDScript 2.0, attempting to assign to a subclass member variable with a type of another script's subclass quietly fails, resulting in a `null` value instead.

### Steps to reproduce

A minimal example project is provided. In addition, here are the steps used to manually reproduce the issue:
- Create a project in the latest alpha build of Godot 4.0. 
- Create two scripts, `AScript.gd` and `BScript.gd`, with these contents, respectively:

```gdscript
# AScript.gd

class_name AScript

class ASubClass:
	var data := 4.0
```

```gdscript
# BScript.gd

extends Node # Assign this script to the main scene to reproduce

class BSubClass:
	# The type annotation here is what triggers the bug - without it, no problem
	var a := AScript.ASubClass.new()
	
func _ready():
	# Lone ASubClass, works as expected.
	
	var lone_a := AScript.ASubClass.new()
	print(lone_a.data)
	
	# BSubClass.new() initializes correctly, `a` is valid, as is `data`
	
	var b := BSubClass.new()
	print(b.a.data)
	
	# Here's where it gets weird - despite being functionally identical 
	# to line 10, `a` is `null` after this statement
	
	b.a = AScript.ASubClass.new()
	print(b.a)
	# print(b.a.data) 	Error, `a` is null
```

The console output of this project is:
```
4
4
null
```

(Given that removing the type annotation from `BSubClass` resolves this, it seems like a type checking issue. I've used this to work around the bug in my own project.)

### Minimal reproduction project

[GDScriptBugTest.zip](https://github.com/godotengine/godot/files/8748665/GDScriptBugTest.zip)

### LINKED ISSUE #61848: Subclass cannot be inherited from other subclass in autoload using its naming alias
### Godot version

a2c016e997fbff4c1af6f3c7220de7bfe1e59105

### System information

Windows 11

### Issue description

Nested class from autoload cannot be accessed in the other script file using autoload name (only full path):

image

while this is ok:

image

### Steps to reproduce

Create autoload GDScript file like :

```
extends Node

class A:
	pass
```
(call it `Global.gd`)

Create a GDScript and fill it like:
```
extends Node

class B extends Global.A:
	pass
```

<i>EDIT: Actually is not even for 2nd case - it inherits autoload itself instead of nested class</i>

### Minimal reproduction project

[class_test.zip](https://github.com/godotengine/godot/files/8870597/class_test.zip)

### LINKED ISSUE #62982: GDScript 2.0: "Cannot convert argument 1 from Object to Object" when signal parameter is typed with an inner class.
### Godot version

v4.0.alpha.custom_build [8b059d47f]

### System information

Arch on 5.18.10-arch1-1

### Issue description

Looks similar to https://github.com/godotengine/godot/issues/26047

I think `game: Global.Game` is the problem. Maybe it thinks the type is Global?

```
E 0:00:04:0641   _ready: Error calling from signal 'game_changed' to callable: 'Node(scene.gd)::_on_game_changed': Cannot convert argument 1 from Object to Object..
  <C++ Source>   core/object/object.cpp:1025 @ emit_signalp()
  <Stack Trace>  global.gd:10 @ _ready()
```

### Steps to reproduce

`global.gd` in autoload `Global`

```gdscript
extends Node

signal game_changed(game)

class Game:
	extends Node

func _ready() -> void:
	await get_tree().process_frame
	game_changed.emit(Game.new())

```

`scene.gd`

```gdscript
extends Node

func _ready() -> void:
	Global.game_changed.connect(_on_game_changed)

func _on_game_changed(game: Global.Game) -> void:
	print(game)

```

Cannot reproduce if everything is in one file

### Minimal reproduction project

[test10.zip](https://github.com/godotengine/godot/files/9104420/test10.zip)

### LINKED ISSUE #64915: Typehints on inner classes do not recognize function argument types
### Godot version

9c9b8fcd34f21fb8a754621c5a6ae21cddaca9d9

### System information

Windows 10

### Issue description

I use a lot of inner classes in my project to structure my data better and in Godot 3.5+ I was able to instantiate an inner class and use it as a function argument type. Attempting this in Godot 4 results in a compilation error:

```
Invalid type in function '_print_string_value' in base 'Node2D ()'. The Object-derived class of argument 1 (RefCounted (ChildClassA)) is not a subclass of the expected argument class.
```
This line comes from https://github.com/godotengine/godot/blob/7199314eb39408da4f9f7286452c980a3d3da1c9/modules/gdscript/gdscript_vm.cpp#L166 and when debugging the project it looks like there is not a real type created but just a `RefCounted`:
Capture

This might relate to #61567 and #61635 however, they mention very specific use-cases while I am just trying to use the type itself.

### Steps to reproduce

Create some inner classes with inheritance and then register that namespace class as a autoload singleton:
Capture2

Attempt to use the inner classes as types:
Capture

### Minimal reproduction project

[gdscript-inner-classes.zip](https://github.com/godotengine/godot/files/9430575/gdscript-inner-classes.zip)

### LINKED ISSUE #65953: GDScript 2.0: Incorrect base class when using `extends Class.Subclass`
### Godot version

20d6672846

### System information

Windows 10 x64

### Issue description

When using 'extends BaseClass.Subclass' the class extended is 'BaseClass'. Kinda.
All super calls will go to A, not B, but Analyzer still knows B is the intended super class.

The `GDScriptDataType::script_type` for the identifier is set wrong in i think 'resolve_inheritance' or 'reduce_identifier_from_base' in GDScriptAnalyser. Or left unset?
Something to do with the subclass class member not getting its script type resolved.
`GDScriptDataType::script_type` is not set right by the time it gets to GDScriptCompiler when it sets the 'base' ptr in GDScript, where all super calls go.
Tested on Beta 1

### Steps to reproduce

Use the dot notation in an extends clause, like (extends A.B).
All super calls will go to A, not B, but Analyzer still knows B is the intended super class

### Minimal reproduction project

[GodotInheritanceBugProject.zip](https://github.com/godotengine/godot/files/9590571/GodotInheritanceBugProject.zip)
Running the project will print:
```
TestClass._init
BaseClass.test
```
When it should print:
```
TestClass._init
SubClass.test
```

### LINKED ISSUE #67163: Random errors related to inner classes
### Godot version

4.0 ca25c6e

### System information

Windows 10 x64

### Issue description

When you open a scene that has a script with an inner class, you will sometimes get this error:
```
Attempt to open script '' resulted in error 'Can't open file'.
```
It's triggered in specific circumstances, but prints every time the scene is opened.

Seems like the script has to be built-in and the class has to be used as an array type. Not sure if it's the only case that triggers the error.

### Steps to reproduce

1. Create a new scene
2. Add any node and attach a new built-in script
3. Put this in the script
```GDScript
var arr: Array[Inner]

class Inner:
	pass
```
4. Save and reload the scene

### Minimal reproduction project

_No response_

### LINKED ISSUE #67547: GDScript 2.0: Typed assigning an inner class leads to a runtime error
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I have a function `auto_free(<instance>) : Object` to register instances to be get auto freed after test execution on my plugin GdUnit3.

The function signature is
`func auto_free(obj) -> Object:`
and returns the same obj

When going back to the original class, an error occurs at runtime
`var instance :AdvancedTestClass.AtmosphereData = auto_free(AdvancedTestClass.AtmosphereData.new())`
**```Trying to assign value of type '' to a variable of type 'AdvancedTestClass.gd'.```**

### Steps to reproduce

Copy this code and run it.
```
class_name TestScene
extends Node

class Custom:
	pass

func _ready():
	test_wrapper()

func test_wrapper():
	# with this inner class it works
	var original: = TestScene.Custom.new()
	var as_object :TestScene.Custom = auto_free(original)
	prints(as_object)
	
	# with this inner class defined in ExampleClass it breaks
	var original_: = ExampleClass.Data.new()
	# this line fails at runtime
	var as_object_ :ExampleClass.Data = auto_free(original_)

# just return same value 
func auto_free(value :Object) -> Object:
	return value
```

The external script/class
```
class_name ExampleClass
extends Resource

class Data:
	pass
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #67753: GDScript 2.0: Extending an inner class results in invalid constructor resolution at runtime
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I run into this issue during my plugin migration form Godot3 to Godot4
My mocker implementation allows to mock inner classes and used default arguemts to construct it.

With Godot 4 it is broken and the construction fails by an error:
**`Invalid call to function '_init'. Expected 0 arguments.`**
But the construcor is correct called with all needed arguments

### Steps to reproduce

create a simple scene and add this code

```
class_name TestScene
extends Node

class SmokyAtmosphereData extends ExampleClass.AtmosphereData:
	
	func _init():
		super._init(SMOKY, 1.1)

func _ready():
	ExampleClass.AtmosphereData.new()
	SmokyAtmosphereData.new()
``` 

The `ExampleClass` code
```
class_name ExampleClass
extends Resource

class AtmosphereData:
	enum {
		WATER,
		AIR,
		SMOKY,
	}
	
	func _init(type := AIR, toxigen := 0.0):
		prints("AtmosphereData", type, toxigen)

func _init():
	pass
```

Run it
image

**Apparently the constructor of the 'ExampleClass' class is used instead of the constructor of the inner class.**
If you comment the construcor of the 'ExampleClass' out, the code is running

This is a critical bug in my eyes.

### Minimal reproduction project

_No response_

### LINKED ISSUE #67977: GDScript 2.0: Calling an overwritten function of an external inner class results in a runtime error
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I have a mocker that stubs classes
On Godot 4 it is broken when calling an  overwritten function of an external inner class.

image

### Steps to reproduce

run the example code
external.gd
```
class_name External

class A:
	func foo() -> void:
		prints("External.A:foo")
	
	func bar() -> void:
		pass
```

testscene.gd
```
class_name TestScene
extends Node

class A:
	func foo() -> void:
		prints("A:foo")

class B extends A:
	func foo() -> void:
		super.foo()
		prints("B:foo")
	
	func bar() -> void:
		pass

class C extends External.A:
	func foo() -> void:
		super.foo()
		prints("C:foo")
	
	func bar() -> void:
		pass

func _ready():
	prints("External.A")
	var a := External.A.new()
	a.bar()
	a.foo()
	
	prints("B")
	var b := B.new()
	b.bar()
	b.foo()
	prints("C")
	var c := C.new()
	c.bar()
	# fails by a runtime error
	c.foo()
```
The output
```
External.A
External.A:foo
B
A:foo
B:foo
C
  editor/debugger/debug_adapter/debug_adapter_types.h:70 - Condition "path.is_empty()" is true.

```
image

### Minimal reproduction project

_No response_

### LINKED ISSUE #68291: GDScript: Subclass overwrites rpc info
### Godot version

https://github.com/godotengine/godot/commit/6882890a34528e056f13020798f4a473046990bb

### System information

Windows 10 x64

### Issue description

Functions in a subclass with the same name as a func in its outer class will overwrite its rpc info, also i think rpc info for subclasses dont get made at all?

### Steps to reproduce

Run the project, it spits out 0 instead of printing an error.
Here the rpc info are being overwritten by subclasses info, and subclass info is not getting populated as far as i can tell.
https://github.com/godotengine/godot/blob/6882890a34528e056f13020798f4a473046990bb/modules/gdscript/gdscript.cpp#L1234-L1262

### Minimal reproduction project

[godot-phantom-rpc-call.zip](https://github.com/godotengine/godot/files/9943850/godot-phantom-rpc-call.zip)

### PR DESCRIPTION
**Pull request by rune-scape**
Replaces some important outdated code about subclasses.
rpc properties correctly apply to subclasses.
subclasses of subclasses now have docs populated.
shallow scripts have their subclass scripts populated and name and id set.
various other fixes.

- Fixes #65953
- Fixes #68291
- Fixes #68561
- Fixes #64915
- Fixes #61848
- Fixes #61268
- Fixes #67977
- Fixes #62982
- Fixes #67753
- Fixes #67547
- Fixes #67163

### CODE REVIEW

**Comment by Chaosus** [comment]
Don't forget to squash the commits.

**Comment by rune-scape** [comment]
collapsed them into nothing lol oops

**Comment by adamscott** [comment]
As discussed in #67714, I think this PR should be merged before or after #67714 in order to fix #65953. This PR fix is way more deep that the solution I used in my PR.

**Review by adamscott — APPROVED** [review]
At first glance, it seems fine to me. Can't wait to integrate those changes in my PR.

**Comment by rune-scape** [comment]
@adamscott sorry for changing it last minute, i added tests and found a bug

**Review by akien-mga — APPROVED** [review]
I'm not competent to do an in-depth review, but generally speaking this look solid. vnen is not available right now but I put this on his backlog to possibly review post-merge when he has time.

Let's get this merged and tested more broadly to see if any regressions creep up.

**Comment by MikeSchulze** [comment]
Thanks for you all hard work!

File: modules/gdscript/gdscript_cache.cpp [hunk 1]
```diff
@@ -173,11 +174,16 @@ Ref<GDScript> GDScriptCache::get_shallow_script(const String &p_path, const Stri
 		return singleton->shallow_gdscript_cache[p_path];
 	}
 
+	Ref<GDScriptParserRef> parser_ref = get_parser(p_path, GDScriptParserRef::PARSED, r_error);
+	if (r_error != OK) {
+		return Ref<GDScript>();
+	}
```
Comment (Rindbee) [inline modules/gdscript/gdscript_cache.cpp:180]: This is not equivalent to the previous logic. Now it seems that if the parsing fails, the script will not be cached by `shallow_gdscript_cache` (the previous logic is only an invalid script will report an error, this will hardly appear, may it appear in multi-threading?)

File: modules/gdscript/gdscript_cache.cpp [hunk 2]
```diff
@@ -200,17 +206,21 @@ Ref<GDScript> GDScriptCache::get_full_script(const String &p_path, Error &r_erro
 	}
 
 	if (script.is_null()) {
-		script = get_shallow_script(p_path);
-		ERR_FAIL_COND_V(script.is_null(), Ref<GDScript>());
+		script = get_shallow_script(p_path, r_error);
+		if (r_error) {
+			return script;
+		}
```
Comment (Rindbee) [inline modules/gdscript/gdscript_cache.cpp:212]: This is not equivalent to the previous logic. Now it seems that if the parsing fails, the script will not be cached by `shallow_gdscript_cache` (the previous logic is only an invalid script will report an error, this will hardly appear, may it appear in multi-threading?)

Comment (rune-scape) [reply modules/gdscript/gdscript_cache.cpp:212]: you're right, i completely missed that, and just after #68914 was merged too

Comment (rune-scape) [reply modules/gdscript/gdscript_cache.cpp:212]: ok I made #68927 to fix this
