### PR TITLE
HTML5: Explain why export templates are missing

### LINKED ISSUE #59476: Clarify why HTML5 export templates are missing in 4.0 alpha builds
### Godot version

4.0.alpha3

### System information

MacOS 10.15.7

### Issue description

I cannot export project to webassembly. It seems that the webassembly export templates are missing. I can download export templates for 4.0.alpha3, but 'webassembly_release.zip' and 'webassembly_debug.zip' are missing:
Screenshot 2022-03-24 at 17 43 58
Screenshot 2022-03-24 at 17 44 17
Screenshot 2022-03-24 at 17 44 29

### Steps to reproduce

Project -> Export...

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
Same for UWP.

This is skipped in DEV_ENABLED builds so contributors can still test
the export pipeline (and CI still compiles it on debug builds).

- Closes #59476.

### CODE REVIEW

**Comment by akien-mga** [comment]
Preview:
image

We could do more, but I think that's good enough as a short term solution until we can actually provide HTML5 templates again.

File: platform/javascript/export/export_plugin.cpp [hunk 1]
```diff
@@ -360,6 +360,15 @@ Ref<Texture2D> EditorExportPlatformJavaScript::get_logo() const {
 }
 
 bool EditorExportPlatformJavaScript::can_export(const Ref<EditorExportPreset> &p_preset, String &r_error, bool &r_missing_templates) const {
+#ifndef DEV_ENABLED
+	// We don't provide export templates for the HTML5 platform currently as there
+	// is no suitable renderer to use with them. So we forbid exporting and tell
+	// users why. This is skipped in DEV_ENABLED so that contributors can still test
+	// the pipeline once we start having WebGL or WebGPU support.
+	r_error = "The HTML5 platform is currently not supported in Godot 4.0, as there is no suitable renderer for it.\n";
```
Comment (akien-mga) [inline platform/javascript/export/export_plugin.cpp:368]: I didn't bother making this translatable with `TTR()` as I envision this as a temporary solution, and current translations track the `3.x` branch anyway.
