### PR TITLE
Warn that navigation mesh baking from Meshes is bad for runtime performance

### LINKED ISSUE #90607: Navigation mesh baking needs to warn that visual Meshes are bad for runtime performance
### Tested versions

4.3dev

### System information

Windows 10

### Issue description

Parsing source geometry from rendering meshes for the navigation mesh baking is a significant performance hazard.

What is ok for easy setup and performs ok inside the Editor makes runtime (re)baking of navigation meshes basically impossible without frame rate issues.

The issue with visual meshes is that their geometry data needs to be received from the GPU which blocks the rendering every time the parsing needs to read the mesh arrays.

Most users are not aware that the majority of their runtime (re)bake performance issues are caused by this (and nodes) and expect just the entire navigation mesh baking process to be the issue.

The navigation mesh baking should print a performance warning when at runtime a MeshInstance2D/3D, MultiMeshInstance2D/3D, GridMap mesh or CSG mesh, or any Mesh really, ... gets parsed by the navigation mesh baking process or added to a NavigationSourceGeometryData object.

The warning also should inform users to switch the parsing to use collision shapes as they do not have the same issues as rendering meshes and are far better optimized for their role as source geometry.

Ideally the default geometry parsing would also be switched to collision instead of parsing visual meshes but since Godot does not store defaults this would break existing projects.

### Steps to reproduce

Bake navigation meshes with visual meshes as source geometry at runtime. Expect significant performance issues.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by smix8**
Adds a one-time warning when a visual Mesh is added to the source geometry at runtime to make users more aware about this problem.

Resolves https://github.com/godotengine/godot/issues/90607

At runtime this poses a significant performance issues as visual meshes store geometry data on the GPU and transferring this data back to the CPU blocks the rendering.

So baking navigation mesh when parsing from e.g. MeshInstance3D or MultiMeshInstance3D  nodes is really only viable inside the Editor where frame rate is less of an issue.

For runtime (re)baking navigation meshes use and parse collision shapes as source geometry or create geometry data procedural in scripts.

### CODE REVIEW

File: scene/resources/3d/navigation_mesh_source_geometry_data_3d.cpp [hunk 1]
```diff
@@ -30,6 +30,17 @@
 
 #include "navigation_mesh_source_geometry_data_3d.h"
 
+#ifdef DEBUG_ENABLED
+#define NAVMESH_SOURCE_GEOMETRY_PARSE_RENDERING_MESHES_WARN_MSG()                                                                                    \
+	if (!Engine::get_singleton()->is_editor_hint()) {                                                                                                \
+		WARN_PRINT_ONCE("Source geometry parsing for navigation mesh baking had to parse RenderingServer meshes at runtime.\n\
+		This poses a significant performance issues as visual meshes store geometry data on the GPU and transferring this data back to the CPU blocks the rendering.\n\
+		For runtime (re)baking navigation meshes use and parse collision shapes as source geometry or create geometry data procedural in scripts."); \
```
Comment (Scony) [inline scene/resources/3d/navigation_mesh_source_geometry_data_3d.cpp:38]: procedurally

**Review by Scony — APPROVED** [review]

File: scene/resources/3d/navigation_mesh_source_geometry_data_3d.cpp [hunk 2]
```diff
@@ -30,6 +30,17 @@
...
+#ifdef DEBUG_ENABLED
+#define NAVMESH_SOURCE_GEOMETRY_PARSE_RENDERING_MESHES_WARN_MSG()                                                                                    \
+	if (!Engine::get_singleton()->is_editor_hint()) {                                                                                                \
+		WARN_PRINT_ONCE("Source geometry parsing for navigation mesh baking had to parse RenderingServer meshes at runtime.\n\
+		This poses a significant performance issues as visual meshes store geometry data on the GPU and transferring this data back to the CPU blocks the rendering.\n\
+		For runtime (re)baking navigation meshes use and parse collision shapes as source geometry or create geometry data procedurally in scripts."); \
+	};
+#else
+#define NAVMESH_SOURCE_GEOMETRY_PARSE_RENDERING_MESHES_WARN_MSG()
+#endif
```
Comment (akien-mga) [inline scene/resources/3d/navigation_mesh_source_geometry_data_3d.cpp:42]: Seems to have some trailing `\` alignment issues (with the tab size clang-format uses):
https://github.com/godotengine/godot/actions/runs/8766104374/job/24057840243?pr=90921

It's only used in one place though, so does this needs to be a macro? It could just be inline enclosed in `DEBUG_ENABLED`.

Comment (smix8) [reply scene/resources/3d/navigation_mesh_source_geometry_data_3d.cpp]: True, originally I had multiple places in mind where this needs to be added but then I realized late that all those other functions use the add_mesh() function internally so I switch it over here without replacing the macro.

File: scene/resources/3d/navigation_mesh_source_geometry_data_3d.cpp [hunk 3]
```diff
@@ -158,6 +158,15 @@ void NavigationMeshSourceGeometryData3D::_add_faces(const PackedVector3Array &p_
 
 void NavigationMeshSourceGeometryData3D::add_mesh(const Ref<Mesh> &p_mesh, const Transform3D &p_xform) {
 	ERR_FAIL_COND(!p_mesh.is_valid());
+
+#ifdef DEBUG_ENABLED
+	if (!Engine::get_singleton()->is_editor_hint()) {
+		WARN_PRINT_ONCE("Source geometry parsing for navigation mesh baking had to parse RenderingServer meshes at runtime.\n\
+		This poses a significant performance issues as visual meshes store geometry data on the GPU and transferring this data back to the CPU blocks the rendering.\n\
+		For runtime (re)baking navigation meshes use and parse collision shapes as source geometry or create geometry data procedurally in scripts.");
+	};
```
Comment (akien-mga) [inline scene/resources/3d/navigation_mesh_source_geometry_data_3d.cpp:167]: Unnecessary semicolon.

**Comment by akien-mga** [comment]
Thanks!
