### PR TITLE
[macOS] Disable window embedding code in export templates.

### LINKED ISSUE #113953: Godot 4.5.1 App fails macOS App Review
### Tested versions

4.5.1 stable

### System information

macOS

### Issue description

When putting an app for macOS review, I get:

```
Guideline 2.5.1 - Performance - Software Requirements


Your app uses or references the following non-public or deprecated APIs:


Contents/MacOS/PolyglotPirates

Classes:

• CAContext

Symbols:

• _kCAContextCIFilterBehavior


The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.
```

Along with a failure of review (Unable to publish on App store).

### Steps to reproduce

Build/sign/publish to test flight and add for review a macOS app.

### Minimal reproduction project (MRP)

-

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/113953

### CODE REVIEW

File: platform/macos/display_server_macos.mm [hunk 1]
```diff
@@ -42,7 +42,9 @@
 #import "godot_window.h"
 #import "godot_window_delegate.h"
 #import "key_mapping_macos.h"
+#ifdef TOOLS_ENABLED
 #import "macos_quartz_core_spi.h"
+#endif
 #import "os_macos.h"
 
 #include "core/config/project_settings.h"
```
Comment (akien-mga) [inline platform/macos/display_server_macos.mm:51]:
```suggestion
#import "os_macos.h"

#ifdef TOOLS_ENABLED
#import "macos_quartz_core_spi.h"
#endif

#include "core/config/project_settings.h"
```

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.2.
