### PR TITLE
Fix mipmap bias behavior by refactoring how samplers are created by Material Storage.

### LINKED ISSUE #81214: Mipmap bias slider in the project settings no longer has any effect
### Godot version

v4.2.dev.custom_build [549fcce5f]

### System information

Windows 10, Vulkan, GTX 960 537.13

### Issue description

https://github.com/godotengine/godot/assets/48926464/2be7d140-97c9-4b6d-9c82-0d741401393a

### Steps to reproduce

I think the video shows enough.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by DarioSamo**
Introduces a new structure to store samplers created with certain parameters instead of storing a 'custom' set of samplers. Allows viewports to correctly configure the mipmap bias and use it when rendering the scene.

This effectively fixes [#81214](https://github.com/godotengine/godot/issues/81214) and also introduces rendering improvements for the FSR 2 PR https://github.com/godotengine/godot/pull/81197, which will be adapted to account for this behavior properly when this is merged.

The most obvious way to test this is that changing the mipmap bias setting at the project level or per viewport effectively did nothing before. This also fixes the issue where it was not possible to use different mipmap biases across different viewports.

The fix should work for both RenderingDevice-based renderers Forward+ and Mobile.

### CODE REVIEW

File: servers/rendering/renderer_rd/storage_rd/material_storage.cpp [hunk 1]
```diff
@@ -1088,6 +1088,37 @@ void MaterialStorage::MaterialData::set_as_used() {
 	}
 }
 
+///////////////////////////////////////////////////////////////////////////
+// MaterialStorage::Samplers
+
+Vector<RD::Uniform> MaterialStorage::Samplers::get_uniforms(int first_index) const {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/material_storage.cpp:1094]:
```suggestion
Vector<RD::Uniform> MaterialStorage::Samplers::get_uniforms(int p_first_index) const {
```

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h [hunk 2]
```diff
@@ -155,8 +155,7 @@ class RenderForwardClustered : public RendererSceneRenderRD {
 
 	uint64_t lightmap_texture_array_version = 0xFFFFFFFF;
 
-	bool base_uniform_set_updated = false;
-	void _update_render_base_uniform_set();
+	void _update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &samplers);
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h:158]:
```suggestion
	void _update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &p_samplers);
```
Prefix arguments with `p_`

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 3]
```diff
@@ -2694,13 +2697,11 @@ void RenderForwardClustered::base_uniforms_changed() {
 	render_base_uniform_set = RID();
 }
 
-void RenderForwardClustered::_update_render_base_uniform_set() {
+void RenderForwardClustered::_update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &samplers) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:2700]:
```suggestion
void RenderForwardClustered::_update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &p_samplers) {
```

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 4]
```diff
@@ -1517,7 +1520,7 @@ void RenderForwardMobile::base_uniforms_changed() {
 	render_base_uniform_set = RID();
 }
 
-void RenderForwardMobile::_update_render_base_uniform_set() {
+void RenderForwardMobile::_update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &samplers) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:1523]:
```suggestion
void RenderForwardMobile::_update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &p_samplers) {
```

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.h [hunk 5]
```diff
@@ -200,7 +200,7 @@ class RenderForwardMobile : public RendererSceneRenderRD {
 
 	uint64_t lightmap_texture_array_version = 0xFFFFFFFF;
 
-	void _update_render_base_uniform_set();
+	void _update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &samplers);
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.h:203]:
```suggestion
	void _update_render_base_uniform_set(const RendererRD::MaterialStorage::Samplers &p_samplers);
```

File: servers/rendering/renderer_rd/storage_rd/material_storage.cpp [hunk 6]
```diff
@@ -2400,24 +2237,98 @@ void MaterialStorage::material_update_dependency(RID p_material, DependencyTrack
...
+			}
+
+			samplers.rids[i][j] = RD::get_singleton()->sampler_create(sampler_state);
+		}
+	}
+
+	return samplers;
+}
+
+void MaterialStorage::samplers_rd_free(const Samplers &samplers) const {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2324]:
```suggestion
void MaterialStorage::samplers_rd_free(const Samplers &p_samplers) const {
```

File: servers/rendering/renderer_rd/storage_rd/material_storage.h [hunk 7]
```diff
@@ -105,13 +105,23 @@ class MaterialStorage : public RendererMaterialStorage {
 		Vector<RID> texture_cache;
 	};
 
+	struct Samplers {
+		RID rids[RS::CANVAS_ITEM_TEXTURE_FILTER_MAX][RS::CANVAS_ITEM_TEXTURE_REPEAT_MAX];
+		float mipmap_bias = 0.0f;
+		bool use_nearest_mipmap_filter = false;
+		int anisotropic_filtering_level = 2;
+
+		Vector<RD::Uniform> get_uniforms(int first_index) const;
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/material_storage.h:114]:
```suggestion
		Vector<RD::Uniform> get_uniforms(int p_first_index) const;
```

File: servers/rendering/renderer_rd/storage_rd/material_storage.h [hunk 8]
```diff
@@ -335,18 +345,16 @@ class MaterialStorage : public RendererMaterialStorage {
 
 	/* Samplers */
 
+	Samplers samplers_rd_allocate(float p_mipmap_bias = 0, bool p_use_nearest_mipmap_filter = false, int p_anisotropic_filtering_level = 2) const;
+	void samplers_rd_free(const Samplers &samplers) const;
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/material_storage.h:349]:
```suggestion
	void samplers_rd_free(const Samplers &p_samplers) const;
```

**Comment by DarioSamo** [comment]
Thanks @AThousandShips for the suggestions, I forgot about the parameter rules for a bit there.

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 9]
```diff
@@ -2724,22 +2725,22 @@ void RenderForwardClustered::_update_render_base_uniform_set() {
 			RID sampler;
 			switch (decals_get_filter()) {
 				case RS::DECAL_FILTER_NEAREST: {
-					sampler = material_storage->sampler_rd_get_custom(RS::CANVAS_ITEM_TEXTURE_FILTER_NEAREST, RS::CANVAS_ITEM_TEXTURE_REPEAT_DISABLED);
+					sampler = material_storage->sampler_rd_get_default(RS::CANVAS_ITEM_TEXTURE_FILTER_NEAREST, RS::CANVAS_ITEM_TEXTURE_REPEAT_DISABLED);
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:2728]: This is a change in behaviour that is worth discussing. I have a feeling that it makes sense for decals and projectors to have the per-viewport mipmap bias applied.

File: servers/rendering/renderer_rd/storage_rd/material_storage.cpp [hunk 10]
```diff
@@ -1101,92 +1132,7 @@ MaterialStorage::MaterialStorage() {
...
-				}
-			}
-
-			default_rd_samplers[i][j] = RD::get_singleton()->sampler_create(sampler_state);
-		}
-	}
-
-	//custom sampler
-	sampler_rd_configure_custom(0.0f);
+	default_samplers = samplers_rd_allocate();
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/storage_rd/material_storage.cpp:1135]: We need to include the project settings for ``rendering/textures/default_filters/use_nearest_mipmap_filter`` and ``rendering/textures/default_filters/anisotropic_filtering_level`` here so that they continue to apply to the default samplers

**Review by clayjohn — COMMENTED** [review]
Great work! I left a few comments for your consideration

File: servers/rendering/renderer_rd/storage_rd/material_storage.cpp (hunk 10 above)
Comment (DarioSamo) [reply servers/rendering/renderer_rd/storage_rd/material_storage.cpp:1135]: Should we query the global settings inside the allocate function then so we don't have to query the global where I moved it as well?

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp (hunk 9 above)
Comment (DarioSamo) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:2728]: I was unaware how these samplers are used to be honest to be sure. This should be a matter of just pulling from the other samplers below.

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:2728]: You'll have to make the same change in the mobile renderer too.

File: servers/rendering/renderer_rd/storage_rd/material_storage.cpp (hunk 10 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/storage_rd/material_storage.cpp:1135]: I think thats a good idea. There's no point in making them parameters if we always pull from the global settings

**Comment by DarioSamo** [comment]
Added the change to mobile renderer as well.

**Comment by Calinou** [comment]
> This also fixes the issue where it was not possible to use different mipmap biases across different viewports.

Would this make it possible to use a different mipmap bias for 2D and 3D rendering in the future? Right now, changing mipmap bias in a viewport affects both 2D and 3D. (Note that mipmaps are disabled by default in 2D; you need to enable them in the 2D filter property of Viewport, **and** enable the Mipmaps import option on the texture.)

**Comment by DarioSamo** [comment]
> Would this make it possible to use a different mipmap bias for 2D and 3D rendering in a single viewport in the future? Right now, changing mipmap bias in a viewport affects both 2D and 3D. (Note that mipmaps are disabled by default in 2D; you need to enable them in the 2D filter property of Viewport, **and** enable the Mipmaps import option on the texture.)
> 
> This should be achievable using two viewports thanks to your PR now, but using a single viewport should reduce the performance overhead.

Should be easily doable. Basically the PR allows any class with access to MaterialStorage to create a set of samplers configured however they need it. My implementation chose to do it for each set of RenderBuffers as the mipmap bias required for rendering the scene differs depending on settings that affect the buffers, but even the same renderer pulls from different set of samplers depending on the content.

**Review by clayjohn — APPROVED** [review]
Looks good to me. I haven't tested locally, but I trust that Dario tested adequately. This isn't a very risky change.

This PR introduces a slight change in behaviour as Decals and projectors in the mobile renderer now properly use the custom samplers with mipmap bias applied (whereas before they ignored mipmap bias). Since the mipmap bias was broken anyway, users should only notice an improvement

This PR is technically fixing a regression that occurred sometime after 4.1 (I think) so it shouldn't be cherrypicked unless we find out that the regression happened before 4.1

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` fe5b1c8d49313d63fbe91cb7cdf463e10fb86afa), it works as expected.

Note that this PR does not fix https://github.com/godotengine/godot/issues/65690, which still occurs when adjusting mipmap bias manually, enabling antialiasing properties or decreasing 3D resolution scaling (as these automatically adjust mipmap bias). Either way, that can be looked into separately.

**Comment by akien-mga** [comment]
Thanks!
