### PR TITLE
[Code Editor] Fix "Pick Color" menu option replacing multiple color items.

### LINKED ISSUE #108428: Pick Color changes values for multiple colors
### Tested versions

- present in 4.4.2 stable
- present in 4.5 beta2

### System information

Godot v4.5.beta2 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6614) - AMD Ryzen 9 3900X 12-Core Processor (24 threads) - 47.92 GiB memory

### Issue description

https://github.com/user-attachments/assets/cdea739e-abe7-4ed6-ab5d-53aa5a0939fb

If you duplicate a color in an Array and try to change the first one, it changes them all (they are linked somehow)
Happens quite a lot to me

### Steps to reproduce

1. Create an Array
2. Add a color to it (const cols = [Color(1.0, 0.222, 0.86), ])
3. Duplicate the color (CTRL+D)
4. Change the first color with Pick Color

### Minimal reproduction project (MRP)

[bugreport.zip](https://github.com/user-attachments/files/21138035/bugreport.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
It was replacing every instance of the same `Color` constructor to the end of the line, instead of a selected one.

Fixes https://github.com/godotengine/godot/issues/108428

### CODE REVIEW

**Review by kitbdev — APPROVED** [review]
Fixes the issue.
This should be changed to use the same methods as the inline colors in the future, but this is fine for now.

- supersedes https://github.com/godotengine/godot/pull/91016
- fixes https://github.com/godotengine/godot/issues/91008

File: editor/script/script_text_editor.h [hunk 1]
```diff
@@ -112,7 +112,7 @@ class ScriptTextEditor : public ScriptEditorBase {
 
 	PopupPanel *color_panel = nullptr;
 	ColorPicker *color_picker = nullptr;
-	Vector2 color_position;
+	Vector3 color_position;
```
Comment (kleonc) [inline editor/script/script_text_editor.h]: AFAICT it's used to store ints only.
```suggestion
	Vector3i color_position;
```

File: editor/script/script_text_editor.cpp [hunk 2]
```diff
@@ -2544,7 +2545,7 @@ void ScriptTextEditor::_color_changed(const Color &p_color) {
 	}
 
 	String line = code_editor->get_text_editor()->get_line(color_position.x);
-	String line_with_replaced_args = line.replace(color_args, new_args);
+	String line_with_replaced_args = line.substr(0, color_position.y) + line.substr(color_position.y, color_position.z - color_position.y).replace(color_args, new_args) + line.substr(color_position.z, -1);
```
Comment (AThousandShips) [inline editor/script/script_text_editor.cpp]:
```suggestion
	String line_with_replaced_args = line.substr(0, color_position.y) + line.substr(color_position.y, color_position.z - color_position.y).replace(color_args, new_args) + line.substr(color_position.z);
```

**Comment by Repiteo** [comment]
Thanks!
