### PR TITLE
Fixed editor inspector ranges capping values at 65535.

### LINKED ISSUE #22528: Incorrect display of Vector2,3 in the debugger
**Godot version:**
3.1.alpha a2b6be2

**OS/device including version:**
Windows 10

**Issue description:**
When debugger is showing contents of `Vector2`, the values are capped to [-65535,65535]. Also affects `Vector3`.

**Steps to reproduce:**
Run code with brakpoint:
```
	var v = Vector2(0,1000000)
	var vy = v.y
	print("%s %f %f" % [ v, v.x, v.y ])
```
godot-vector-truncated-3
Console output is as expected:
```
(0, 1000000) 0.000000 1000000.000000
```

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed editor inspector ranges capping values at 65535.

Fixes #22528 and #5867

### CODE REVIEW

File: editor/editor_properties.cpp [hunk 1]
```diff
@@ -825,6 +825,8 @@ void EditorPropertyInteger::setup(int p_min, int p_max, bool p_allow_greater, bo
 	spin->set_step(1);
 	spin->set_allow_greater(p_allow_greater);
 	spin->set_allow_lesser(p_allow_lesser);
+	spin->set_allow_greater(true);
```
Comment (groud) [inline editor/editor_properties.cpp]: I'm not sure this is needed, you're overriding what the two lines above do.

Comment (DualMatrix) [reply editor/editor_properties.cpp]: Eeh... yeah that was an accident...

**Comment by DualMatrix** [comment]
Removed those two unneeded lines.

**Comment by akien-mga** [comment]
Thanks!
