### PR TITLE
Prompt to restart when project data (.godot) is missing

### LINKED ISSUE #81199: Getting `cannot open/create file` error if `.godot` folder is removed when project is already open
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Godot v4.2.dev3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

If project is open in Godot when the `.godot` folder is removed, you get some errors:

kuva

```
editor/import/resource_importer_texture.cpp:334 - Condition "f.is_null()" is true.
Cannot open MD5 file 'res://.godot/imported/icon.svg-218a8f2b3041327d8a5756f3a245f83b.md5'.
Cannot create file 'res://.godot/editor/filesystem_cache8'. Check user write permissions.
Cannot create file 'res://.godot/editor/filesystem_update4'. Check user write permissions.
```

This happened to me when I constructed a reproduction project for an issue. The project was still opened when I removed `.godot` folder before zipping the project folder.

It seems that Godot recreates the `.godot` folder structure only when a project is opened. Maybe it could be done also when it is detected that saving files to `.godot` folder fails because the whole folder is missing? If this error happens, error messages ("Check user write permissions") do not help very much as this is not write permission problem. Or if the recreation of `.godot` folder is too complicated at this stage, maybe an error message could instruct reloading the project.

The problem can be solved by reloading the project.

### Steps to reproduce

1. Open any project 
2. Remove project's `.godot` folder 
-> get some errors immediately 
3. Save any *.gd file 
-> get some more errors

### Minimal reproduction project

N/A

### LINKED ISSUE #104225: Godot Editor fails to reimport if `.godot` folder is deleted
### Tested versions

4.4.stable, 4.5.dev

### System information

Godot v4.5.dev.mono  - EndeavourOS  SMP PREEMPT_DYNAMIC Fri, 07 Mar 2025 20:19:00 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Mobile) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 4800U with Radeon Graphics (16 threads)

### Issue description

Godot editor fails to reimport if `.godot` folder is deleted and the `.godot` folder can't re-gengerated, unless reload the project.

https://github.com/user-attachments/assets/f9ccda48-9cc5-478b-8341-8fec6a063535

### Steps to reproduce

Open a project, delete the `.godot` folder, then godot fails to reimport assets.

### Minimal reproduction project (MRP)

[editor-import-bug.zip](https://github.com/user-attachments/files/19270335/editor-import-bug.zip)

### PR DESCRIPTION
**Pull request by beicause**
Closes #104225, closes #81199

When editor gets focus: 
- check if `.godot`, `.godot/editor`, `.godot/imported` are missing 
- recreate `.gdignore`, `uid_cache.bin` if them don't exist
- skip scanning and reimporting resource
- popup a dialog to prompt to restart

Although this doesn't check detailly if individual files are missing, It‘s sufficient to deal with some situations.

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -7937,6 +7978,13 @@ EditorNode::EditorNode() {
 
 	gui_base->add_child(disk_changed);
 
+	project_data_missing = memnew(ConfirmationDialog);
+	project_data_missing->set_text(TTR("Project data (.godot) is missing. Please restart editor."));
+	project_data_missing->connect(SceneStringName(confirmed), callable_mp(this, &EditorNode::_restart_editor).bind(false));
```
Comment (KoBeWi) [inline editor/editor_node.cpp:7983]: You should use `restart_editor()` instead, otherwise this will discard all unsaved changes.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -7937,6 +7978,13 @@ EditorNode::EditorNode() {
...
+	project_data_missing->set_ok_button_text(TTR("Restart"));
```
Comment (KoBeWi) [inline editor/editor_node.cpp:7984]:
```suggestion
	project_data_missing->set_ok_button_text(TTRC("Restart"));
```

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -600,6 +600,43 @@ void EditorNode::update_preview_themes(int p_mode) {
 	}
 }
 
+bool EditorNode::_is_project_data_missing() {
+	Ref<DirAccess> da = DirAccess::create(DirAccess::ACCESS_RESOURCES);
+	const String project_data_dir = EditorPaths::get_singleton()->get_project_data_dir();
+	const String dirs[] = {
+		EditorPaths::get_singleton()->get_project_settings_dir(),
+		ProjectSettings::get_singleton()->get_imported_files_path()
+	};
```
Comment (KoBeWi) [inline editor/editor_node.cpp:609]: This can be just before the loop.

File: editor/editor_node.cpp (hunk 1 above)
Comment (beicause) [reply editor/editor_node.cpp:7983]: This won't work. If the `imported` folder is deleted, saving will fail. 
屏幕截图_20250317_225746

File: editor/editor_node.cpp (hunk 2 above)
Comment (beicause) [reply editor/editor_node.cpp]: I found this dialog uses `TTR()`:
https://github.com/godotengine/godot/blob/ef4ed69674895e98108ca7a24dc7cafe71db5aad/editor/editor_node.cpp#L7747

Comment (KoBeWi) [reply editor/editor_node.cpp]: TTRC is preferred for new strings. The plan is to eventually replace old usages of TTR. See #102562

**Comment by beicause** [comment]
```diff
diff --git a/servers/rendering/renderer_rd/shader_rd.cpp b/servers/rendering/renderer_rd/shader_rd.cpp
index fde0616a0ea928471436f74b7cf176f9bff56dc7..ef4ed69674895e98108ca7a24dc7cafe71db5aad 100644
--- a/servers/rendering/renderer_rd/shader_rd.cpp
+++ b/servers/rendering/renderer_rd/shader_rd.cpp
@@ -508,7 +508,7 @@
 	ERR_FAIL_COND(!shader_cache_dir_valid);
 	const String &path = _get_cache_file_path(p_version, p_group);
 	Ref<FileAccess> f = FileAccess::open(path, FileAccess::WRITE);
-	ERR_FAIL_COND(f.is_null());
+	ERR_FAIL_COND_MSG(f.is_null(), "Failed to open shader cache, please restart the editor/game.");
 	f->store_buffer((const uint8_t *)shader_file_header, 4);
 	f->store_32(cache_file_version); // File version.
 	uint32_t variant_count = group_to_variant_map[p_group].size();
```
I revert this change in `shader_rd.cpp`, although deleting `.godot/shader_cache` will cause an error here and the `.godot/shader_cache` won't be regenerated, perhaps this is not the only reason and there may be a better solution.

File: editor/editor_node.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/editor_node.cpp]: Ok, it should actually say "Restart" 🙃
"Save & Restart" is for when the option saves all scenes, but here it just exits and save dialog is separate.
Alternatively you can implement it as save and restart. See `_set_renderer_name_save_and_restart()` for example.

**Review by KoBeWi — APPROVED** [review]
Works fine.

I realized Save & Restart (as mentioned in https://github.com/godotengine/godot/pull/104252#discussion_r2004289687) would be better, but this can be changed in a follow-up too.

**Comment by beicause** [comment]
This is the project  [mrp_nested_gltf_scene.zip](https://github.com/user-attachments/files/19477350/mrp_nested_gltf_scene.zip) I previously tested in https://github.com/godotengine/godot/pull/104252#discussion_r1998957503

In this project, after deleting .godot, setting the renderer, saving and restarting, the "Couldn't save scene" and confirm dialog will pop up. Then, after you select "Cancel", the editor will be no response if you try to restart or quit. It seems to be a bug in `_set_render_method_save_and_restart` or `restart_editor`

For now I prefer to keep using `restart_editor`.

**Comment by akien-mga** [comment]
Thanks!
