### PR TITLE
Fix ShaderInclude selected in ShaderCreateDialog due to previous selection even if invalid

### LINKED ISSUE #114618: ShaderInclude can be created in ShaderMaterial
### Tested versions

4.6 beta2

### System information

W10

### Issue description

When creating a shader for a ShaderMaterial, the ShaderInclude option is normally disabled.

Image

However, if you create a ShaderInclude in FileSystem dock, the shader dialog will remember this option, so it can be selected while disabled

Image

This creates a ShaderInclude file normally, but it's not being assigned to the material (which is expected at least).

### Steps to reproduce

1. In FileSystem dock, use New Resource > ShaderInclude and create the file
2. Make a Node2D, in `material` property create ShaderMaterial
3. Add a shader to the material, it will show the shader creation dialog
4. The ShaderInclude will be selected despite disabled

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by LucaTuerk**
Fix ShaderInclude automatically selected when creating adding a Shader f.e in ShaderMaterial due to previous selection when creating a ShaderInclude from the FileSystemDock.

This fixes uses the existing load_enabled parameter to determine if the ShaderInclude type is valid and does not accept it from the last selected type if invalid.

Fixes #114618

### CODE REVIEW

**Comment by mxtherfxcker** [comment]
There are a lot of unnecessary code actions here. The problem can be solved more simply and universally. It is enough to add a check to the cycle - `!type_menu->is_item_disabled(i)`.

File: editor/shader/shader_create_dialog.cpp [hunk 1]
```diff
@@ -330,27 +330,21 @@ void ShaderCreateDialog::config(const String &p_base_path, bool p_built_in_enabl
...
 			break;
 		}
 	}
-	if (preferred_type < 0 || preferred_type >= type_menu->get_item_count()) {
-		preferred_type = 0;
-		// Select the last selected language if possible, otherwise default to the first language.
-		String last_lang = EditorSettings::get_singleton()->get_project_metadata("shader_setup", "last_selected_language", "");
-		if (!last_lang.is_empty()) {
-			for (int i = 0; i < type_menu->get_item_count(); i++) {
-				if (type_menu->get_item_text(i) == last_lang) {
```
Comment (mxtherfxcker) [inline editor/shader/shader_create_dialog.cpp]: Delete your changes and add an additional check here - `!type_menu->is_item_disabled(i)`.
The final change (one single one) is `if (type_menu->get_item_text(i) == last_lang && !type_menu->is_item_disabled(i))`

Comment (LucaTuerk) [reply editor/shader/shader_create_dialog.cpp]: Thank you for the review! 

I tried this solution but it does not fix the issue, as the items disabled state is set only later when _type_changed(...) is called at the end of the config(...) method.

Comment (mxtherfxcker) [reply editor/shader/shader_create_dialog.cpp]: > Thank you for the review!
> 
> I tried this solution but it does not fix the issue, as the items disabled state is set only later when _type_changed(...) is called at the end of the config(...) method.

That's right, my flaw. But I still advise you to optimize everything you can, because I'm sure the fix can be made shorter.

**Review by YeldhamDev — APPROVED** [review]
LGTM.

**Comment by Repiteo** [comment]
Thanks!
