### PR TITLE
Fix double `text_changed` signal when overwriting selection in LineEdit

### LINKED ISSUE #86451: `LineEdit` `text_changed` emitted twice when replacing selected text
### Tested versions

Reproducable in Godot 4.2.1
Reproducable in master 13a0d6e

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6900 XT (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

`LineEdit` `text_changed` is emitted twice when a selected range of text is replaced.

### Steps to reproduce

1. Select a text range, e.g. 'AAA'
2. Press a key, e.g. 'B'
3. Text is now 'B'
4. `text_changed` is emitted twice

Observe the count in the following video when replacing the text:
https://github.com/godotengine/godot/assets/66004280/04323f99-23a8-4c02-a4e4-cea3e5301c8b

### Minimal reproduction project (MRP)

[LineEditTest.zip](https://github.com/godotengine/godot/files/13755150/LineEditTest.zip)

### PR DESCRIPTION
**Pull request by reach-satori**
The part of gui_input that handles unicode wasn't checking text_changed_dirty before emitting the signal, unlike the rest of the text editing functions in LineEdit.

This brings it in line with the other code in the same file and fixes #86451

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
This looks like something that should be a method 🤔 (e.g. `emit_changed()`)

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -624,7 +624,12 @@ void LineEdit::gui_input(const Ref<InputEvent> &p_event) {
 			int prev_len = text.length();
 			insert_text_at_caret(ucodestr);
 			if (text.length() != prev_len) {
-				_text_changed();
+				if (!text_changed_dirty) {
+					if (is_inside_tree()) {
+						MessageQueue::get_singleton()->push_call(this, "_text_changed");
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp:629]:
```suggestion
						callable_mp(this, &LineEdit::_text_changed).call_deferred();
```
Would be best to use Callable here, see https://github.com/godotengine/godot/pull/86301, better to not risk conflicts between these PRs and just use this here

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
