### PR TITLE
Fixed parser error when indexing a dictionary.

### LINKED ISSUE #41707: GDScript parse error on Dictionary indexing with member syntax
**Godot version:**
358e209fa049887fd4212c52c9faba0ca9d6e111

**OS/device including version:**
Linux, but should affect any OS.

**Issue description:**
Given this script:
```gdscript
func _ready():
        var a = {
                test: "Hello"
        }
        a.test += " World"
```
The new GDScript in the `master` branch would throw an error:
```
SCRIPT ERROR: Parse Error: Identifier "test" not declared in the current scope.
          at: GDScript::reload (res://Node2D.gd:6)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:633)
```

**Steps to reproduce:**
- Use `my_dict.my_var` syntax to index a Dictionary.

**Minimal reproduction project:**
Not necessary.

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #41707
similar fix in 3.2 [here](https://github.com/godotengine/godot/blob/d773de6d244116c3ad26f0506a10038cc11019ff/modules/gdscript/gdscript_parser.cpp#L6688)

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2073,18 +2073,29 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
...
-			Callable::CallError temp;
-			Variant dummy = Variant::construct(base.builtin_type, nullptr, 0, temp);
-			List<PropertyInfo> properties;
-			dummy.get_property_list(&properties);
-			for (const List<PropertyInfo>::Element *E = properties.front(); E != nullptr; E = E->next()) {
-				const PropertyInfo &prop = E->get();
-				if (prop.name == name) {
-					p_identifier->set_datatype(type_from_property(prop));
+			switch (base.builtin_type) {
+				case Variant::NIL: // May not needed since it'll be GDScriptParser::DataType::VARIANT now.
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:2077]: You cannot use indexing on `null` so this case should raise an error I think. Though it should still return as a Variant type so the analyzer can keep checking the rest of the code.

Comment (vnen) [reply modules/gdscript/gdscript_analyzer.cpp:2077]: I just noticed it is the same 3.2. Still, I think if we inferred the type as `null` we can just raise an error to inform the user.

Comment (ThakeeNathees) [reply modules/gdscript/gdscript_analyzer.cpp]: @vnen done! only if a variable is explicitly assigned to `null` the inferred type is `null` and it raise an error otherwise it's a variant.

```gdscript
func _ready():
    var v1 = null
    v1.name ## <-- error
    var v2
    v2.name ## <-- not error
```

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
