### PR TITLE
Fix color picker MacOS permission request box always being visible

### LINKED ISSUE #118829: Color Picker Node requests users to enable Screen Recording even if Sampler Visible is turned off
### Tested versions

Found in Godot 4.5.1, although I don't think much has changed with the Color Picker node since then.

### System information

Godot v4.5.1.stable.mono - macOS Tahoe (26.4.1) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M4 Pro (Apple9) - Apple M4 Pro (14 threads) - 48.00 GiB memory

### Issue description

I received a complaint from a player asking why my game "requires" screen recording and was confused because it most certainly does not.

This issue concerns the Color Picker control node, I'm using the Color Picker to allow players to customize their color. The built-in color picker node provides a nicer user experience than separate RGB/HSL sliders so I thought I'd use it.

On macOS, the color picker emits this message saying that screen recording is not enabled, clicking the message takes them to their security settings to turn it on.

I think this message appears because the Eye Dropper can't work without screen recording permission. However, there is no Eye Dropper in this color picker, so I don't know what the user gets for enabling this permission.

Image

In short: if **Sampler Visible** is turned off, this message should not show up because there is no sampler to require screen recording.

### Steps to reproduce

- (from a macOS device)
- Ensure you do NOT have Screen Recording granted to Godot.
- Create a Color Picker control node
- You will see the `Screen Recording permission missing!` message, even in editor.
- Uncheck all the boxes in the inspector, no matter how minimal you make the color picker, you cannot make this message go away.

### Minimal reproduction project (MRP)

I can upload an MRP if you really need one but this is trivial to reproduce.

### PR DESCRIPTION
**Pull request by SorkoPiko**
Ensures the sampler is visible before showing the permission request box.

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/118829*

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Please squash the commits, see [The interactive rebase](https://contributing.godotengine.org/en/latest/organization/pull_requests/creating_pull_requests.html#the-interactive-rebase).

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -2330,7 +2333,6 @@ ColorPicker::ColorPicker() {
 	perm_link->connect(SceneStringName(pressed), callable_mp(this, &ColorPicker::_req_permission));
 	perm_hb->add_child(perm_link);
 	real_vbox->add_child(perm_hb);
-	perm_hb->set_visible(false);
```
Comment (LiveTrower) [inline scene/gui/color_picker.cpp:2333]: Why was this line deleted? It seems to have introduced a regression on non-macOS platforms. They are now showing the 'Screen Recording permission missing!' alert, which should be specific to macOS.

Comment (SorkoPiko) [reply scene/gui/color_picker.cpp:2333]: 😬 oops, i thought that would be caught when the node received the visibility notification but i forgot about it being mac-exclusive.

Comment (LiveTrower) [reply scene/gui/color_picker.cpp:2333]: Will you open a PR to fix this?

Comment (SorkoPiko) [reply scene/gui/color_picker.cpp:2333]: yep, working on it

Comment (SorkoPiko) [reply scene/gui/color_picker.cpp:2333]: fixed in #119251
