### PR TITLE
Fixes to CSG robustness

### LINKED ISSUE #58637: Holes in CSG meshes with coplanar faces and engine freeze when moving them
### Godot version

4.0.alpha3

### System information

Windows 11

### Issue description

I am generating a number of `CSGMesh3D` objects and putting them in a `CSGCombiner3D`. All meshes are set to be a union. Sometimes, this generates random holes:

image

And, potentially related, when moving the mesh with the hole on the Z axis, the engine freezes.

### Steps to reproduce

1. Open `csg_bug.tscn` in the editor
2. Look at the red CSG mesh
3. Optionally, try to move the red CSG mesh on the Z axis

### Minimal reproduction project

[CSGBug.zip](https://github.com/godotengine/godot/files/8155020/CSGBug.zip)

### PR DESCRIPTION
**Pull request by fire**
…iangles

Collaboration with OldBelge

Previously, the code assumed that if the intersection line hit the common edge of 2 triangles, it meant that the intersection entered or exited a shape. However, there is also a case where the intersection just "skirts" the other shape on the outside. To handle this case, we added a check for the direction of the normals of the faces. If the inner product of the normals and the intersection is greater than 0, then the intersection is inside the shape.

Fixes: https://github.com/godotengine/godot/issues/58637

Still happens: https://github.com/godotengine/godot/issues/41140

### CODE REVIEW

**Comment by fire** [comment]
OldBelge posted a test case. 
[Uploading prototype003.zip…]()

**Comment by fire** [comment]
Investigating fixes for the perpendicular cases.

**Comment by fire** [comment]
Before:

image

After:

image

**Comment by fire** [comment]
Some debugging diagrams.

image

**Comment by fire** [comment]
We've decided that fixing two cases is good enough for this pr. Waiting for review.

**Comment by fire** [comment]
Before:

image

After:

image

**Comment by fire** [comment]
image

Missed an edge case.

**Comment by fire** [comment]
[CSGBug_2023-03-11.zip](https://github.com/godotengine/godot/files/10949662/CSGBug_2023-03-11.zip)

**Comment by fire** [comment]
Original:

https://user-images.githubusercontent.com/32321/224521654-62c7efd2-2f71-4c61-a041-05ff5d71fc81.mp4

Fixed:

https://user-images.githubusercontent.com/32321/224521645-1fc062d5-0521-4843-b2b7-3d24d0e76b25.mp4

**Comment by akien-mga** [comment]
I started testing this PR, as I have a project using CSG which suffers from glitches. This PR seems to fix a lot of the problems!

It's a fairly pathological case, we stitched 40 Path3Ds together, generating CSGPolygon3D from each Path3D and using them to subtract from a big CSGBox3D.

Here's how it looks like in 4.0.2-stable:
image
(same in 4.1 `master` as of 6bf94cfd7acf747f1b4fd0b0762cb878f8f08198)
The glitches can move around, forcing a regeneration of the CSGCombiner can typically make things better or worse, so it's clearly a problem of precision issues.

And here's how it looks like with this PR (rebased on latest `master`):
image

So... it's definitely better :D

I'll soon make that project open source so it can be used by others for testing too. It's this game: https://akien.itch.io/godog

The above screenshots is from a level we didn't use in the end due to those glitches. But even the playable build on itch has CSG glitches (weird hard lines going through the level where it's supposed to be subtracting geometry), and I confirmed that this PR fixes them.

File: modules/csg/csg.h [hunk 1]
```diff
@@ -135,6 +135,17 @@ struct CSGBrushOperation {
 				return h;
 			}
 		};
+		struct Intersection {
+			bool found = false;
+			real_t conormal = 9999999.0f; // Should be MAX, but probably is never larger than 1.
+			real_t distance_squared = 9999999.0f; // Should be MAX.
+			real_t origin_angle = 9999999.0f; // Should be MAX, but probably is never larger than 1.
```
Comment (akien-mga) [inline modules/csg/csg.h:142]: Would it make sense to use `FLOAT_MAX`, or is it overkill?

File: modules/csg/csg_shape.cpp [hunk 2]
```diff
@@ -141,11 +141,11 @@ bool CSGShape3D::is_root_shape() const {
 }
 
 void CSGShape3D::set_snap(float p_snap) {
-	snap = p_snap;
+	snap = p_snap / 100;
```
Comment (akien-mga) [inline modules/csg/csg_shape.cpp:144]: This breaks compatibility, is it really needed?

It's not change the way `snap` is used internally, only breaking compat for on the user side, which seems unnecessary.

If the problem was not being able to input small enough numbers, you can change the step in the range hint.

File: modules/csg/csg_shape.cpp [hunk 3]
```diff
@@ -653,7 +653,7 @@ void CSGShape3D::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("get_meshes"), &CSGShape3D::get_meshes);
 
 	ADD_PROPERTY(PropertyInfo(Variant::INT, "operation", PROPERTY_HINT_ENUM, "Union,Intersection,Subtraction"), "set_operation", "get_operation");
-	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "snap", PROPERTY_HINT_RANGE, "0.0001,1,0.001,suffix:m"), "set_snap", "get_snap");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "snap", PROPERTY_HINT_RANGE, "0.001,1,0.001,suffix:mm"), "set_snap", "get_snap");
```
Comment (akien-mga) [inline modules/csg/csg_shape.cpp:656]: You add a factor 100 so that wouldn't go from meter to millimeter. Was the previous value in decimeters?

**Review by akien-mga — APPROVED** [review]

File: modules/csg/csg_shape.cpp (hunk 3 above)
Comment (fire) [reply modules/csg/csg_shape.cpp:656]: This is the bugfix for the very small box sample someone made. It increases the precision range. Not sure if this is the best way but it has an effect on that test case.

File: modules/csg/csg.h (hunk 1 above)
Comment (fire) [reply modules/csg/csg.h:142]: I wondered too. This number is not a constant, but I am in the middle of something. The test plan is to check your sample and the zip for the change to float max and the precision of snapping.

File: modules/csg/csg.cpp [hunk 4]
```diff
@@ -587,17 +592,61 @@ bool CSGBrushOperation::MeshMerge::_bvh_inside(FaceBVH *facebvhptr, int p_max_de
...
-									_add_distance(intersectionsA, intersectionsB, current_face.from_b, 0);
+									_add_distance(intersectionsA, intersectionsB, current_face.from_b, 0, true);
 								}
 							} else if (ray_intersects_triangle(face_center, face_normal, current_points, CMP_EPSILON, intersection_point)) {
-								real_t distance = face_center.distance_to(intersection_point);
-								_add_distance(intersectionsA, intersectionsB, current_face.from_b, distance);
+								real_t distance_squared = face_center.distance_squared_to(intersection_point);
+								real_t inner = current_normal.dot(face_normal);
+								// If the faces are perpendicular, ignore this face.
+								// The triangles on the side should be intersected and result in the correct behaviour
```
[the remark this answers is not in the document]
Comment (fire) [reply modules/csg/csg.cpp:606]: Oops I’m using Canadian English. Good catch

File: modules/csg/csg_shape.cpp (hunk 3 above)
Comment (fire) [reply modules/csg/csg_shape.cpp:656]: https://github.com/godotengine/godot/files/10949662/CSGBug_2023-03-11.zip I am not able check immediately. Sorry

Comment (fire) [reply modules/csg/csg_shape.cpp:656]: to be clear a 10 cm hole is too much

Comment (akien-mga) [reply modules/csg/csg_shape.cpp:656]: The default snap is `0.001` (m), which is 1 mm. That shouldn't be 10 cm, which would be `0.1`.

File: modules/csg/csg.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (akien-mga) [reply modules/csg/csg.cpp]: Fixed.

File: modules/csg/csg.h (hunk 1 above)
Comment (akien-mga) [reply modules/csg/csg.h]: I changed it to `FLT_MAX`, seems to work.

File: modules/csg/csg_shape.cpp (hunk 3 above)
Comment (akien-mga) [reply modules/csg/csg_shape.cpp]: I removed the `snap * 100` change so we don't break compatibility.

I changed the min value and step to `1e-6` so users can adjust the snap value further down if they need.

Changing the snap to `0.0001` fixes both MRPs from #41140 in my tests. I don't know if that's a good enough resolution for that issue, CC @goatchurchprime.

**Comment by akien-mga** [comment]
I pushed some changes to avoid breaking compatibility. It's still possible to reduce the `snap` value down to 1e-6 m, i.e. 1 µm, which should help solve situations with missing triangles on small CSG meshes as seen by @goatchurchprime in #41140.

It's not perfect, but hopefully that makes things more usable.

**Comment by akien-mga** [comment]
Tested some more projects from previously reported issues / duplicates.

This PR does fix the MRPs from those issues:
- #41140, when changing the `snap` value to 0.0001 to match the size of the geometry
- https://github.com/team-godog/NGJ2023_Godog
  * `main` branch, which had a few holes and most importantly missing triangles in the subtraction which would end up as hard lines on top of the track.
  * `pathageddon` branch, which a much more complex network of Path3Ds which used to be full of holes in the lower part, as shown in https://github.com/godotengine/godot/pull/74771#issuecomment-1523377936 (this branch is iffy when loading in Godot 4.0 or 4.1.dev, be sure to delete `.godot` to force a reimport, possibly re-edit the project twice, and you might still need to manually trigger a reimport of the shiba.gltf mesh to be able to open the Game scene).

But doesn't fix the MRPs from those issues:
- #43755
- #75862

File: modules/csg/csg_shape.cpp (hunk 3 above)
Comment (fire) [reply modules/csg/csg_shape.cpp]: The reasoning makes sense.

**Comment by akien-mga** [comment]
Thanks!

**Comment by justinwash** [comment]
> Does this also fix #73927? (Which may be a duplicate of the linked issue.)

Testing with the repro project here from #74343 it does not appear so. I have a branch on my fork that fixes this issue by keeping track of which edges have already been processed by the loop. Will post over on issue #73927 to continue the conversation there.

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.
