### PR TITLE
Tweak property order in the inspector for OptionButton

### LINKED ISSUE #88141: `OptionButton` has a foldable `Items` section above properties that do not belong to it
### Tested versions

v4.3.dev.custom_build [94dbf69f5]

### System information

linux

### Issue description

image

notice the upper section that folds but doesn't contain the other properties. This section should be moved below the sectionless properties.

It used to be the same in `AudioStreamRandomiser`, but it [was fixed](https://github.com/godotengine/godot/pull/82411).

### Steps to reproduce

add an OptionButton

### Minimal reproduction project (MRP)

any

### PR DESCRIPTION
**Pull request by Ratamacue9112**
Fixes #88141. Moves the `items` property to below other properties.

### CODE REVIEW

**Comment by Ratamacue9112** [comment]
There was a comment that said:
`// "selected" property must come after "item_count", otherwise GH-10213 occurs.`
However when I reordered it, no errors were thrown. I'm guessing this was fixed at some point and the comment was never removed.

**Comment by AThousandShips** [comment]
There isn't an `item_count` any more so it's irrelevant

**Comment by AThousandShips** [comment]
But it's not in the declarations here so it can't be reordered before or after

**Comment by KoBeWi** [comment]
I think `ADD_ARRAY_COUNT` does the declaration.

**Comment by AThousandShips** [comment]
That's true!

Note though @Ratamacue9112 that this isn't an error being thrown, so make sure to check the issue report to make sure it doesn't reappear:
* https://github.com/godotengine/godot/issues/10213

**Review by AThousandShips — CHANGES_REQUESTED** [review]
This does indeed break the class, and `selected` breaks with this change, it works fine without this change

**Comment by Ratamacue9112** [comment]
Ah sorry, didn't notice that. I'm trying to work out a fix now, any suggestions?

**Comment by AThousandShips** [comment]
No, it'd require quite a bit of reorganization I think, you can't change any of the names of the properties, and we can't delay initializing this property, so I'm not sure how it would be possible to fix this without reworking quite a bit

**Comment by KoBeWi** [comment]
The initializing *can* be delayed. You can add a new boolean e.g. `initialized` and if `selected` is out of index and `initialized` is false, store it into e.g. a new `queued_selected` variable. Then in `NOTIFICATION_POSTINTIALIZE` check if `queued_selected` was changed and if it was, assign it to `selected`. Also set `initialized` to `true`.

**Comment by AThousandShips** [comment]
It's true we can delay the rest of the processing, what I meant was that we can't directly delay it with some property flag

**Comment by Ratamacue9112** [comment]
Where should I put the check for `selected` being out of index? I've tried it in a few places, which don't seem to work, but I might just be doing it wrong.

**Comment by KoBeWi** [comment]
It should be in the setter.

**Comment by Ratamacue9112** [comment]
I've fixed it now. It only worked when I put check if `queued_current` was changed in the `set_item_count` method, instead of in `NOTIFICATION_POSTINITIALIZE`. I don't know if that affects anything else.

File: scene/gui/option_button.cpp [hunk 1]
```diff
@@ -339,6 +339,13 @@ void OptionButton::set_item_count(int p_count) {
 		}
 	}
 
+	if (!initialized) {
+		if (queued_current != current) {
+			current = queued_current;
+		}
+		initialized = true;
```
Comment (AThousandShips) [inline scene/gui/option_button.cpp:346]: This should be set in `_select_int` IMO

File: scene/gui/option_button.cpp [hunk 2]
```diff
@@ -435,9 +442,17 @@ void OptionButton::_select(int p_which, bool p_emit) {
 }
 
 void OptionButton::_select_int(int p_which) {
-	if (p_which < NONE_SELECTED || p_which >= popup->get_item_count()) {
+	if (p_which < NONE_SELECTED) {
 		return;
 	}
+	if (p_which >= popup->get_item_count()) {
+		if (initialized) {
+			ERR_FAIL_INDEX(current, popup->get_item_count());
```
Comment (AThousandShips) [inline scene/gui/option_button.cpp:450]: Why this addition? It checks the previously selected value?

File: scene/gui/option_button.cpp [hunk 3]
```diff
@@ -435,9 +435,26 @@ void OptionButton::_select(int p_which, bool p_emit) {
...
+			queued_current = p_which;
+		}
+	}
+
+	if (!initialized) {
+		if (queued_current != current) {
+			current = queued_current;
+		}
+		initialized = true;
+	}
```
Comment (AThousandShips) [inline scene/gui/option_button.cpp:456]: My bad I deleted that suggestion as I got confused about the order, sorry to confuse there didn't realize you saw it and responded

Comment (Ratamacue9112) [reply scene/gui/option_button.cpp:456]: It does still work so should I just keep it like that?

Comment (AThousandShips) [reply scene/gui/option_button.cpp:456]: Restore it to how it was, it was correct as far as I could tell

**Comment by AThousandShips** [comment]
I will test this out later today :)

**Review by AThousandShips — APPROVED** [review]
Tested and works correctly, thank you!

**Comment by akien-mga** [comment]
Thanks!
