### PR TITLE
Vulkan: Force disable broken `VK_LAYER_bandicam_helper` layer in editor

### LINKED ISSUE #101480: Crash on opening Vulkan project with Bandicam installed
### Tested versions

4.3

### System information

win11 pro - nvidia geforce rtx 3080

### Issue description

Crash on new/open project in version 4.3, but can run normally when using --rendering-driver opengl3

### Steps to reproduce
· run Godot_v4.3-stable_win64.exe
· new project or open existed project.

### Minimal reproduction project (MRP)

Crash on new/open project in version 4.3, but can run normally when using --rendering-driver opengl3

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #101480.

For now we're only disabling it in the editor, like we've done for various other overlays which played badly with Godot's multi-window support. Not clear whether that's the problem with the Bandicam layer too, but for now I'm assuming it is.

If users report that exported games crash because of Bandicam, we can reconsider.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

File: main/main.cpp [hunk 1]
```diff
@@ -2551,12 +2551,14 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 		OS::get_singleton()->set_environment("DISABLE_RTSS_LAYER", "1"); // GH-57937.
 		OS::get_singleton()->set_environment("DISABLE_VKBASALT", "1");
 		OS::get_singleton()->set_environment("DISABLE_VK_LAYER_reshade_1", "1"); // GH-70849.
+		OS::get_singleton()->set_environment("DISABLE_VK_LAYER_bandicam_helper_DEBUG_1", "1"); // GH-101480.
```
Comment (bruvzg) [inline main/main.cpp:2554]: Unlike other layers, there's no `DISABLE_` in the bandicam variable name.

**Review by bruvzg — CHANGES_REQUESTED** [review]

File: main/main.cpp (hunk 1 above)
Comment (bruvzg) [reply main/main.cpp:2554]: For the reference, variables are defined by `disable_environment` in layer `.json` file, and can have any name:

```json
{
	"file_format_version" : "1.0.0",
	"layer": {
		"name": "VK_LAYER_bandicam_helper",
		"type": "GLOBAL",
		"library_path": ".\\bdcamvk64.dll",
		"api_version": "1.2.141",
		"implementation_version": "1",
		"description": "Vulkan Bandicam Helper",
		"disable_environment": { "VK_LAYER_bandicam_helper_DEBUG_1": "1" }
	}
}
```

```json
{
	"file_format_version" : "1.0.0",
	"layer" : {
		"name": "VK_LAYER_reshade",
		"type": "GLOBAL",
		"library_path": ".\\ReShade64.dll",
		"api_version": "1.1.73",
		"implementation_version": "1",
		"description": "crosire's ReShade post-processing injector for 64-bit",
		"disable_environment": {
			"DISABLE_VK_LAYER_reshade_1": "1"
		}
	}
}
```

Comment (akien-mga) [reply main/main.cpp]: Thanks! Fixed.

**Review by bruvzg — APPROVED** [review]

**Comment by bruvzg** [comment]
This completely ludicrous mess, I have installed it in a sandbox and 32-bit and 64-bit have different variable names:

Screenshot 2025-01-14 214120

Disabling all implicit layers, and keeping allowed layer list might actually be a better way to handle it.

**Comment by akien-mga** [comment]
I update this to set both environment variables.

> Disabling all implicit layers, and keeping allowed layer list might actually be a better way to handle it.

I agree, though there's a bit more risk (we'll have to figure out what's the list of layers we want to allow - e.g. someone mentioned Valve's `gamescope` uses implicit layers), so probably something to iterate on during the 4.5 dev cycle.

**Comment by Repiteo** [comment]
Thanks!
