### PR TITLE
Bugfixes for Tree node

### LINKED ISSUE #3549: Signal "item_selected" in class Tree not working correctly
tree = get_node("Tree")
tree.connect("item_selected",self,"item_selected")

When select mode SELECT_SINGLE is set, the signal will never fire.
When select mode SELECT_ROW is set, the signal will fire as often as columns are set in tree (sic :D).

As a side note: the "item_activated" and "cell_selected" signals are working comprehensible in this combinatons.

### PR DESCRIPTION
**Pull request by bruno-ortiz**
This PR fixes 2 bugs: 

-  Deselecting a TreeItem when select_mode is SELECT_SINGLE now works;
- Fixes #3549, now when select_mode is SELECT_SINGLE, the signal item_selected is emitted.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -2923,8 +2923,7 @@ void Tree::item_selected(int p_column,TreeItem *p_item) {
 
 void Tree::item_deselected(int p_column,TreeItem *p_item) {
 
-	if (select_mode==SELECT_MULTI) {
-
+    if (select_mode==SELECT_MULTI || select_mode == SELECT_SINGLE) {
```
Comment (akien-mga) [inline scene/gui/tree.cpp]: Indentation issue, you should be using tabs like in the rest of the code, but your editor is likely enforcing 4 spaces. (same thing in the other commit). Could you rebase to fix them?

**Review by akien-mga — CHANGES_REQUESTED** [review]

File: scene/gui/tree.cpp (hunk 1 above)
Comment (bruno-ortiz) [inline scene/gui/tree.cpp]: fixed! :+1:

**Comment by bruno-ortiz** [comment]
I noticed now that i merged my edit_resource branch in the master branch. I shouldn't have done that. How can i fix this?

**Comment by akien-mga** [comment]
`git rebase -i HEAD~6` and remove the unwanted commits. You could also take the opportunity to squash the remaining commits together so that the commit is merge ready.

**Comment by bruno-ortiz** [comment]
Thanks, I think that now everything is correct.

**Review by akien-mga — APPROVED** [review]
