### PR TITLE
Fix crash when writing $. in the editor

### LINKED ISSUE #49764: GDScript with "$." crashes the editor
### Godot version

v4.0.dev.custom_build.7aebb8f81

### System information

Windows 10

### Issue description

When you start typing `$.` in the script editor, it throws unhandled exception:
`read access violation. p_subscript->base was nullptr.` in `modules\gdscript\gdscript_analyzer.cpp` line 2731

### Steps to reproduce

Start the script editor, define any function and try to type `$.` in function body.

### Minimal reproduction project

_No response_

### LINKED ISSUE #50259: Editor crashes when editing string value
### Godot version

v4.0.dev.custom_build [56d712686]

### System information

Windows 10, Nvidia GTX 1080 Ti

### Issue description

Editor simply freezes up and crashes when a string is being edited in a particular location.

### Steps to reproduce

1. Open the project attached
2. Open Node3D.gd
3. Type the character: " (double quote) at either of the locations shown in the image
4. Observe the editor crash

Issue

NOTE: This issue does not seem to happen when editing a normal string assigned to a variable.

### Minimal reproduction project

[ScriptCrashIssue.zip](https://github.com/godotengine/godot/files/6779033/ScriptCrashIssue.zip)

### PR DESCRIPTION
**Pull request by Blackiris**
Fixes #49764 and fixes #50259

When writing $. in the editor, the analyzer expect an expression like object.attribute, but in this case, object is $, which is a get_node on nothing, so converted to nullptr, making the base null.
This PR only adds a check on nullptr to avoid the crash.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2728,10 +2728,12 @@ void GDScriptAnalyzer::reduce_self(GDScriptParser::SelfNode *p_self) {
 }
 
 void GDScriptAnalyzer::reduce_subscript(GDScriptParser::SubscriptNode *p_subscript) {
-	if (p_subscript->base->type == GDScriptParser::Node::IDENTIFIER) {
-		reduce_identifier(static_cast<GDScriptParser::IdentifierNode *>(p_subscript->base), true);
-	} else {
-		reduce_expression(p_subscript->base);
+	if (p_subscript->base != nullptr) {
```
Comment (akien-mga) [inline modules/gdscript/gdscript_analyzer.cpp:2731]: There's some other code dereferencing `p_subscript->base` later on, maybe it's also risky?

Comment (Blackiris) [reply modules/gdscript/gdscript_analyzer.cpp:2731]: Indeed, you're right, typing `$.aaa` makes it crash too... I will make some changes

Comment (Blackiris) [reply modules/gdscript/gdscript_analyzer.cpp]: Made the change to stop reducing if the base is null. Just wondering is a valid null base could happen...

**Comment by lyuma** [comment]
There's another PR open from last year which may also fix this, but it seems to have been limboed

https://github.com/godotengine/godot/pull/44667

**Comment by Blackiris** [comment]
> There's another PR open from last year which may also fix this, but it seems to have been limboed
> 
> #44667

This PR fixed the issue in the parser, before the analyzer, which maybe makes it better than the current one.

**Review by vnen — APPROVED** [review]
This seems good to me since the parser already checks for `nullptr` in this case.

**Comment by vnen** [comment]
Thanks!
