### PR TITLE
Fix error when break scriptless scene

### LINKED ISSUE #113621: ObjectDB Profiler: Error when generating snapshot for a scriptless scene
### Tested versions

- Reproducible: v4.6.dev2.official [7864ac801], v4.6.dev.custom_build [0156b2bcd]

### System information

Godot v4.6.dev (0156b2bcd) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.105.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

When making a snapshot, the ObjectDB Profiler stuck in "Generating Snapshot" state if none of nodes in the current scene have script attached.

https://github.com/user-attachments/assets/e11bec27-82d1-4d03-9914-cd042c693608

An error is also printed:

> ERROR: Parameter "script_lang" is null.
>   at: debug (core/debugger/remote_debugger.cpp:416)

### Steps to reproduce

1. Make sure that nodes in the current scene does not have any script attached. e.g., Create an empty scene.
2. Run this scene
3. In the ObjectDB Profiler, click Take ObjectDB Snapshot
4. It's stuck in Generating Snapshot state with an error

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by voylin**
Fixes #113621

When running a scene without a script and breaking or using the ObjectDB Profiler you get following error and crash:
image

This PR checks if the scene is scriptless, removes the error, and allows for correctly pausing and breaking so the scene can be inspected. It's just a couple of extra if statements so let me know if anything else needs to change, from my testing I get a working empty project without errors and scene inspection working.

### CODE REVIEW

File: core/debugger/remote_debugger.cpp [hunk 1]
```diff
@@ -408,12 +408,10 @@ void RemoteDebugger::debug(bool p_can_continue, bool p_is_error_breakpoint) {
...
 
 	ScriptLanguage *script_lang = script_debugger->get_break_language();
-	ERR_FAIL_NULL(script_lang);
-
 	Array msg = {
 		p_can_continue,
-		script_lang->debug_get_error(),
-		script_lang->debug_get_stack_level_count() > 0,
+		script_lang ? script_lang->debug_get_error() : String(),
+		script_lang ? script_lang->debug_get_stack_level_count() > 0 : false,
```
Comment (AThousandShips) [inline core/debugger/remote_debugger.cpp]:
```suggestion
		script_lang && (script_lang->debug_get_stack_level_count() > 0),
```
No need for a ternary for booleans

File: core/debugger/remote_debugger.cpp [hunk 2]
```diff
@@ -529,6 +532,9 @@ void RemoteDebugger::debug(bool p_can_continue, bool p_is_error_breakpoint) {
 				ERR_FAIL_COND(data.is_empty());
 				script_debugger->set_ignore_error_breaks(data[0]);
 			} else if (command == "evaluate") {
+				if (!script_lang) {
```
Comment (AThousandShips) [inline core/debugger/remote_debugger.cpp]: Where in this block is `script_lang` used? Why does this get skipped in this case but the two above don't?

File: core/debugger/remote_debugger.cpp (hunk 1 above)
Comment (voylin) [reply core/debugger/remote_debugger.cpp]: Thanks for the tip! Still learning CPP.

File: core/debugger/remote_debugger.cpp (hunk 2 above)
Comment (voylin) [reply core/debugger/remote_debugger.cpp]: Was from me testing around, removing that part made things work as expected so was a bad left-over which I missed when cleaning up. Sorry about that!

**Review by YeldhamDev — APPROVED** [review]
Functionality-wise it fixes the bug, and I didn't notice any regressions with the normal breakpoint behavior.
