### PR TITLE
Fix "File must be opened" error with File.open()

### LINKED ISSUE #60188: File.open reports file not open (GDScript)
### Godot version

895f2a21f4beea6f4c89d33666bdf3b0925d6db7

### System information

Void Linux, Ryzen 1700/RTX 3060

### Issue description

It seems when using File to open something, it complains that the file is not open... when running the open() function? I assume this is some oversight left over from #60169 / #60166

This does not seem to affect functionality, the code still works as expected. For example my test script:

```	
testfile.open("./test_file.txt", File.READ)
var file_text := testfile.get_line()
read_speed = file_text.to_float()
prints("Read speed from file:", read_speed)
```

Which spits out the following (yet still functions):

### Steps to reproduce

See above and below

### Minimal reproduction project

[BasicTest_1.zip](https://github.com/godotengine/godot/files/8477946/BasicTest_1.zip)

### PR DESCRIPTION
**Pull request by novaplusplus**
Fixes #60188 
Simplest fix I could think of, I don't think it would have any side effects. But unsure if this is the best way to do it, feedback welcome.

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -1072,7 +1072,9 @@ Error File::open_compressed(const String &p_path, ModeFlags p_mode_flags, Compre
 }
 
 Error File::open(const String &p_path, ModeFlags p_mode_flags) {
-	close();
+	if (f.is_valid()) {
+		close();
+	}
```
Comment (bruvzg) [inline core/core_bind.cpp:1077]: This can be removed at all, since setting `f` will unref and close a previously open file automatically.

Comment (novaplusplus) [reply core/core_bind.cpp]: Done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
