### PR TITLE
[Windows] Improve build environment detection, add support for Windows on ARM.

### LINKED ISSUE #64904: MSVC builds are broken
### Godot version

f03ac21ea8bf04b5ac0243706facdbde45ba7385

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

Bisected issue to this #55778. Seems to consistently break with the error 'Arch argument should not be used when using VCINSTALLDIR' when compiling with the Visual Studio toolchain regardless whether the arch argument is absent or any other are seemingly used. Seems to compile fine though if this block of code is outright removed:
```    """Set up env to use MSVC manually, using VCINSTALLDIR"""
    print(env["arch"])
    if env["arch"] != "auto":
        print(
            """
            Arch argument is not supported for MSVC manual configuration (VCINSTALLDIR configured).
            Architecture depends on the Native/Cross Compile Tools Prompt/Developer Console (or Visual Studio settings) that is being used to run SCons.
            As a consequence, the arch argument is disabled. Run scons again without arch argument (example: scons p=windows)
            and SCons will attempt to detect what MSVC compiler will be executed and inform you.
            """
        )
        raise SCons.Errors.UserError("Arch argument should not be used when using VCINSTALLDIR")```
```
### Steps to reproduce

Simply attempt to run SCons with the MSVC toolchain. This is the command I'm using
`"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && scons platform=windows`

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
- Adds support for Windows on ARM builds (MSVC and MinGW).
- 32-bit ARM is also supported by the build system, but not tested (are there any 32-bit ARM Windows devices at all?).
- Improves build environment detection.

Supported build option:

- Running from MSVC environment: architecture is detected automatically, mismatching `arch` flag cause error.
- Running from MSYS2 target specific environment: architecture is detected automatically, mismatching `arch` flag cause error.
- Running for generic terminal: any `arch` can be set.
   - Installed MSVC is detected automatically.
   - MinGW compilers should be in `PATH` or `MINGW_PREFIX` should be set (points to the MinGW installation root, replaces `MINGW_PREFIX32` and `MINGW_PREFIX64`).

Known limitation:
- It's impossible to build from base `MSYS` environment, target specific environment should be used instead (`MINGW32`, `MINGW64`, `CLANG32` and, `CLANG64`). Seems like there is some issue with MSYS2 path translation and compilers can't access temporary folder, unlikely fixable.
- If VS is installed, it's still necessary to use `use_mingw`, even if running from MSYS environment, SCons seems to be doing compilers detection before calling anything from `detect.py`.

TODO:

- [x] Cleanup.
- [x] Use readable error messages.
- [x] Mark changes in the third-party libraries.
- [x] Automatically detect `use_llvm` values based on MSYS2 environment type and available compiles in the path/prefix.

Fixes #64904

### CODE REVIEW

File: core/config/engine.cpp [hunk 1]
```diff
@@ -191,11 +191,11 @@ String Engine::get_architecture_name() const {
...
 	return "x86_32";
 
-#elif defined(__aarch64__) || defined(_M_ARM64)
+#elif defined(__aarch64__) || defined(_M_ARM64) || defined(_M_ARM64EC)
 	return "arm64";
 
-#elif defined(__ARM_ARCH_7A__) || defined(__ARM_ARCH_7S__)
-	return "armv7";
+#elif defined(__ARM_ARCH_7A__) || defined(__ARM_ARCH_7S__) || defined(_M_ARM)
+	return "arm32";
```
Comment (akien-mga) [inline core/config/engine.cpp:198]: This is likely also needed in `core/os/os.cpp`'s `OS::has_feature()`.

And the missed arch change is another confirmation that these two methods should really be unified as I advocated for #63258.

File: platform/windows/detect.py [hunk 2]
```diff
@@ -383,36 +490,39 @@ def configure_mingw(env):
...
             env.Append(LINKFLAGS=["-static"])
             env.Append(LINKFLAGS=["-static-libgcc"])
             env.Append(LINKFLAGS=["-static-libstdc++"])
-        mingw_prefix = env["mingw_prefix_32"]
+            env["x86_libtheora_opt_gcc"] = True
     else:
+        if env["arch"] == "x86_64":
+            env["x86_libtheora_opt_gcc"] = True
         if env["use_static_cpp"]:
             env.Append(LINKFLAGS=["-static"])
```
Comment (akien-mga) [inline platform/windows/detect.py:503]: Might be a bit clearer to do it separately IMO:
```python
if env["use_static_cpp"]:
    env.Append(LINKFLAGS=["-static"])
    if env["arch"] == "x86_32":
        env.Append(LINKFLAGS=["-static-libgcc"])
        env.Append(LINKFLAGS=["-static-libstdc++"])

if env["arch"] in ["x86_32", "x86_64"]:
     env["x86_libtheora_opt_gcc"] = True
```
Though the latter could be refactored to be done in `modules/theora/SCsub`.

File: platform/windows/detect.py [hunk 3]
```diff
@@ -29,39 +29,141 @@ def can_build():
...
+        test_gcc = "gcc --version > /dev/null 2>&1"
+        test_clang = "clang --version > /dev/null 2>&1"
 
-        if os.getenv("MINGW32_PREFIX"):
-            mingw32 = os.getenv("MINGW32_PREFIX")
-        if os.getenv("MINGW64_PREFIX"):
-            mingw64 = os.getenv("MINGW64_PREFIX")
+        prefix = ""
+        if os.getenv("MINGW_PREFIX"):
+            prefix = os.getenv("MINGW_PREFIX")
```
Comment (yedpodtrzitko) [inline platform/windows/detect.py:37]:
```suggestion
        prefix = os.getenv("MINGW_PREFIX", "")
```

File: platform/windows/detect.py [hunk 4]
```diff
@@ -29,39 +29,141 @@ def can_build():
...
+                return "a86_64"
+            host_path_index = os.getenv("PATH").upper().find(os.getenv("VCINSTALLDIR").upper() + "BIN\\amd64;")
+            if (host_path_index > -1):
+                return "x86_64"
+            host_path_index = os.getenv("PATH").upper().find(os.getenv("VCINSTALLDIR").upper() + "BIN\\amd64_x86;")
+            if (host_path_index > -1):
+                return "x86_32"
+            host_path_index = os.getenv("PATH").upper().find(os.getenv("VCINSTALLDIR").upper() + "BIN;")
+            if (host_path_index > -1):
+                return "x86_32"
```
Comment (yedpodtrzitko) [inline platform/windows/detect.py:134]:
```suggestion
            PATH = os.getenv("PATH").upper()
            VCINSTALLDIR = os.getenv("VCINSTALLDIR").upper()
            path_arch = {
                "BIN\\x86_ARM;": "arm32",
                "BIN\\amd64_ARM;": "arm32",
                "BIN\\x86_ARM64;": "arm64",
                "BIN\\amd64_ARM64;": "arm64",
                "BIN\\x86_amd64;": "a86_64",
                "BIN\\amd64;": "x86_64",
                "BIN\\amd64_x86;": "x86_32",
                "BIN;": "x86_32",
            }
            for path, arch in path_arch.items():
                final_path = VCINSTALLDIR + path
                if final_path in PATH:
                    return arch
```

File: platform/windows/detect.py [hunk 5]
```diff
@@ -29,39 +29,141 @@ def can_build():
...
+
+        if os.system(get_mingw_bin_prefix(prefix, "arm64", True) + test_clang) == 0:
+            return True
+       
+        if os.system(get_mingw_bin_prefix(prefix, "arm32", True) + test_clang) == 0:
             return True
 
     return False
 
+def get_mingw_bin_prefix(prefix, arch, llvm):
```
Comment (yedpodtrzitko) [inline platform/windows/detect.py:65]: `llvm` parameter is unused

File: platform/windows/detect.py [hunk 6]
```diff
@@ -29,39 +29,141 @@ def can_build():
...
-        mingw32 = "i686-w64-mingw32-"
-        mingw64 = "x86_64-w64-mingw32-"
-
-    if os.getenv("MINGW32_PREFIX"):
-        mingw32 = os.getenv("MINGW32_PREFIX")
-    if os.getenv("MINGW64_PREFIX"):
-        mingw64 = os.getenv("MINGW64_PREFIX")
+    mingw = ""
+    if os.getenv("MINGW_PREFIX"):
+        mingw = os.getenv("MINGW_PREFIX")
```
Comment (yedpodtrzitko) [inline platform/windows/detect.py:163]:
```suggestion
    mingw =  os.getenv("MINGW_PREFIX", "")
```

File: platform/windows/detect.py [hunk 7]
```diff
@@ -79,73 +181,59 @@ def get_opts():
 
 
 def get_flags():
+    arch = detect_build_env_arch()
+    if arch == "":
+        arch = detect_arch()
```
Comment (yedpodtrzitko) [inline platform/windows/detect.py:186]:
```suggestion
    arch = detect_build_env_arch() or detect_arch()
```

File: platform/windows/detect.py [hunk 8]
```diff
@@ -179,19 +267,35 @@ def setup_msvc_auto(env):
...
-    if env["arch"] == "x86_32":
-        env["x86_libtheora_opt_vc"] = False
 
 
 def setup_mingw(env):
     """Set up env for use with mingw"""
-    # Nothing to do here
-    print("Using MinGW")
+
+    if os.getenv("MSYSTEM") and os.getenv("MSYSTEM") == "MSYS":
```
Comment (yedpodtrzitko) [inline platform/windows/detect.py:278]:
```suggestion
    if os.getenv("MSYSTEM") == "MSYS":
```

**Comment by Bromeon** [comment]
This fix seems to work in my CI job which builds nightly Godot for MSVC: 
https://github.com/Bromeon/godot4-nightly/actions/runs/2936360587

File: modules/raycast/config.py [hunk 9]
```diff
@@ -1,5 +1,8 @@
 def can_build(env, platform):
     # Depends on Embree library, which only supports x86_64 and arm64.
+    if platform == "windows" and env["arch"] != "x86_64":
+        return False #TODO build for Windows on ARM
```
Comment (aaronfranke) [inline modules/raycast/config.py:4]:
```suggestion
    if platform == "windows":
        return env["arch"] == "x86_64" #TODO build for Windows on ARM
```

File: core/config/engine.cpp (hunk 1 above)
Comment (bruvzg) [reply core/config/engine.cpp:198]: `OS::has_feature()` already handle `arm32` feature and have `_M_ARM` define.

Comment (akien-mga) [reply core/config/engine.cpp:198]: I was confused because it uses seemingly different logic: https://github.com/godotengine/godot/blob/master/core/os/os.cpp#L441

This one here doesn't seem to handle `__arm__`?

Comment (bruvzg) [reply core/config/engine.cpp:198]: > This one here doesn't seem to handle __arm__?

I'm not sure which compiler/platform is using this define, Windows seems to be using `_M_ARM`.

Comment (akien-mga) [reply core/config/engine.cpp:198]: It's defined by GCC/Clang and other `__GNUC__` compatible compilers. But it's not directly related to this PR, just a reminder for myself / anyone interested to handle when unifying `OS::has_feature` and `Engine::get_architecture_name`.

**Review by akien-mga — APPROVED** [review]
Looks good.

Could you PR the necessary thirdparty changes upstream?

**Comment by akien-mga** [comment]
Thanks!

**Comment by DoubleF3lix** [comment]
Sorry to necro an old thread, but I saw the original post has support for 32-bit ARM on Windows. How could I actually do this? 32-bit ARM windows devices do exist (Surface RT), and I'd like to build a game for it.

**Comment by bruvzg** [comment]
> How could I actually do this? 

You can try building Godot with MSVC (ARM tool chains need to be selected in the VS installer) or [LLVM-MinGW](
https://github.com/mstorsjo/llvm-mingw) by adding `arch=arm32` to the build command. See [Compiling for Windows](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_windows.html). But it regularly tested, so it might be broken. Also, ARM Widows do not have Vulkan support and OpenGL is only available via software emulation (look for OpenCL and OpenGL Compatibility Pack in the app. store), so it probably will have terrible performance.

**Comment by DoubleF3lix** [comment]
So how does the OS render anything?

**Comment by aaronfranke** [comment]
> So how does the OS render anything, or does it have its own software rendering?

You don't need a graphics API in many situations such as rendering a simple UI. But when a graphics API is needed, Windows devices have DirectX.

**Comment by DoubleF3lix** [comment]
Ah. Unfortunately, I don't think my ARM32 Windows device have DirectX, it's just OpenGL 2 IIRC.
