### PR TITLE
Fix Collada material roughness import function

### LINKED ISSUE #17822: Incorrect (NaN) Roughness after importing DAE's from Blender
Not sure if the problem is in this specific line, but it may as well be.

https://github.com/godotengine/godot/blob/9f479f096cb50fa8d1215e68c262f110116114ef/editor/import/editor_import_collada.cpp#L483

     Blender has Hardness value ranging from 1 to 511. In Godot 3.0 it's 0 to 1. (I noticed, that Godot 2.1 has a different structure for this, as there is no numerical value to input for material roughness, and may or may not be because of this, it imports the same .dae file absolutely correct).
     So, the problem is that for bigger values of Hardness in Blender, Godot can't calculate Roughness to import. Material with Hardness 45 is imported all right. But the next one, with Hardness 325 returns "-nan".

     Which makes the model all black.
     (If you are experiencing the same problem, for now this may be corrected by manually imputing Roughness value in Godot. (Below Roughness is changed from "-nan(ind)" to "1"))

### PR DESCRIPTION
**Pull request by Dimonasdf**
Fixes NaN roughness in Godot when importing .dae with material hardness more than 255 (set in Blender, for example).
Also corrects dependency: more hardness = more roughness (it says shininess, but it actually is hardness).

This Fixes #17822, please look inside the issue for details.

### CODE REVIEW

File: editor/import/editor_import_collada.cpp [hunk 1]
```diff
@@ -480,7 +480,7 @@ Error ColladaImport::_create_material(const String &p_target) {
 		}
 	}
 
-	float roughness = Math::sqrt(1.0 - ((Math::log(effect.shininess) / Math::log(2.0)) / 8.0)); //not very right..
+	float roughness = -Math::sqrt(1.0 - ((Math::log(effect.shininess) / Math::log(2.0)) / 9.0)) + 1;
```
Comment (tagcup) [inline editor/import/editor_import_collada.cpp]: I'd either keep the "not very right" or multiply `effect.shininess` with 512.0/511.0 because that's what it refers to. Also you'd probably want to do

```cpp
float roughness = Math::sqrt(((Math::log(effect.shininess * (512.0/511.0)) / Math::log(2.0)) / 9.0))
```

rather than doing a nonlinear double negation (one under square root and one outside)

**Comment by tagcup** [comment]
That just wrong and arbitrarily, I already gave you the correct answer

**Comment by tagcup** [comment]
Also you're trying to map something called shininess in Blemder's Blinn Phong shader to roughness in Disney BRDF, but you really can't, those are two different shading models

**Comment by tagcup** [comment]
I realized that this PR is also wrong in ways other than I initially realized.

1. In specular, roughness essentially controls the size of the specular blob. The larger roughness gets, the larger the blob becomes. In Blender, the opposite happens: as you increase hardness, the specular blob *shrinks*.

2. Roughness and hardness (shininess) are the exponent of N.H in both Blender and Godot specular BRDFs, meaning they are related to to each other *linearly*, not logarithmically.

**Comment by Dimonasdf** [comment]
Now that is some information to think about. Although I believe, that the light models are out of the scope of this problem, as we are only talking about exporting one specific value, which simply serves as a quantitative input for whatever is happening inside of them. That is, if you will check the thread, exactly why I've put a quick question midst my investigation as to why this value is not exported linearly. So, I strongly agree with you on this latter point.

**Comment by tagcup** [comment]
BRDF is the only place roughness is used so I don't understand how it's out of scope.

And no, I'm not talking about one specific value. I'm talking about how the *entire range* of hardness maps to roughness (which is what is is important at the end of the day, and sure, it will also cover one same point as well if that's what you want to focus), and the only way you can do such a mapping between Blender and Godot faithfully is to look at how hardness and roughness enter into the BRDF.

How else do you think you can say hardness and roughness must be linearly related?

**Comment by akien-mga** [comment]
@reduz Argh, don't merge 4 commits all changes the exact same line :'(

**Comment by Dimonasdf** [comment]
I know, I'm sorry :(
I was just using the web version, and "more correct" ideas came one after another, so the pr is not all fancy. I hope it is useful, though.

**Comment by akien-mga** [comment]
It's ok, but please see [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for future contributions. We usually prefer to have a single commit if there's only one change from a working state A to a working state B.
