### PR TITLE
`Vector4`, `Vector4i` and `Projection` for Csharp

### LINKED ISSUE #63445: Mono build fails with invalid literal suffix 'i' (C3688)
### Godot version

4.0.dev (3bd74cd)

### System information

Windows 10

### System
MSVC version 14.3
arch: amd64
bits: 64

### Problem

    >scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
does not compile

### Cause
```cpp
// modules\mono\mono_gd\gd_mono_marshal.h 265
MATCHES_Vector4i = (MATCHES_int && (sizeof(Vector4i) == (sizeof(int32_t) * 4i)) &&
```
throws error C3688 because `4i` has an unknown suffix

### Solution
use `4` instead of `4i` (see `Vector3i`)

```cpp
// modules\mono\mono_gd\gd_mono_marshal.h 271
MATCHES_Vector3i = (MATCHES_int && (sizeof(Vector3i) == (sizeof(int32_t) * 3)) &&
```

### Steps to reproduce

    >scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
with a fresh clone

### Minimal reproduction project

      -

### PR DESCRIPTION
**Pull request by antonWetzel**
## Csharp `Vector4`, `Vector4i` and `Projection` to enable mono to work again.

- `Vector4` and `Vector4i` copied and modified from `Vector3(cs)` and `Vector3i(cs)`
- `Projection` modified from `Projection(c++)` (only what gdscript can see)
- No other class or function uses the structures

## todo
- comments for `Projection` (non trivial functions) -> add while Projection is documented
- add more function to``Vector4(i)` -> add with changes to GDScript

## done
- Vector4 (code and comments)
- Vecto4i (code and comments)
- Projection (code and trivial comments)

*Bugsquad edit:*
- Fixes #63445

### CODE REVIEW

**Comment by antonWetzel** [comment]
## questions
- `GD: Projection.new()` return `Identity` and `CSharp: new Projection()` returns `Zero` (can't be changed) 
    - what is the prefered solution?
- `MinAxisIndex`: `Vector3(i)` (cs) return the last axis and `Vector4` (c++) return the first axis if equal
     - what should the function return?
- c++ returns `Zero` if an init fails
     - should Csharp return `Zero` or throw an exception?
- c++ uses float for `Determinant` and `GetLodMultiplier`
     - should Csharp use `real_t` or `float`?
- c++ uses `ERR_FAIL_COND`
     - should csharp throw an exception?

**Comment by raulsntos** [comment]
> `Projection` uses a lot of code copied from c++, I would prefer to bind the c++ implementations but I don't know if possible

I think it's preferred to reimplement the struct in C# to avoid marshaling since these core types are very commonly used.

> * `GD: Projection.new()` return `Identity` and `CSharp: new Projection()` returns `Zero` (can't be changed)
>   * what is the prefered solution?

What we do in `Transform{2D,3D}` is we have an `Identity` property:

https://github.com/godotengine/godot/blob/edb503cd00614391d14759777c38d8be6d0f20aa/modules/mono/glue/GodotSharp/GodotSharp/Core/Transform2D.cs#L387-L393

> * `MinAxisIndex`: `Vector3(i)` (cs) return the last axis and `Vector4` (c++) return the first axis if equal
>   * what should the function return?

The documentation for `Vector4.min_axis_index` claims if all components are equal it returns the last axis (`W`) so if the C++ is not doing that it's likely a bug.

https://github.com/godotengine/godot/blob/edb503cd00614391d14759777c38d8be6d0f20aa/doc/classes/Vector4.xml#L124-L128

>  * c++ returns `Zero` if an init fails
>    * should Csharp return `Zero` or throw an exception?

I'm not sure, can you give me an example of where this happens?

> * c++ uses float for `Determinant` and `GetLodMultiplier`
>   * should Csharp use `real_t` or `float`?

Looks to me like it should be using `real_t` in C++, not sure why it returns float, probably an oversight.

> * c++ uses `ERR_FAIL_COND`
>   * should csharp throw an exception?

I think we tend not to use exceptions much but I guess it depends on the context. For example, in `Projection.SetFrustum` it sounds like those should be `ArgumentException`.

> Todo: why init v?

Answering your question here:

https://github.com/antonWetzel/godot/blob/9823050c0f2149d0ea249a6fc8817868b628f7a0/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs#L232-L233

That line copies the `Vector4` to avoid mutating the instance, it could also have been implemented like this:

```csharp
    return new Vector4
    (
        Mathf.Sign(x),
        Mathf.Sign(y),
        Mathf.Sign(z),
        Mathf.Sign(w)
    );
```

We use both ways in Vector3 (see `PosMod` and `Clamp`).

> Don't know what changes with dotnet6 (or when)

I don't think the structs need to be different for `dotnet6`.

**Comment by antonWetzel** [comment]
> > * c++ returns `Zero` if an init fails
> >   
> >   * should Csharp return `Zero` or throw an exception?
> 
> I'm not sure, can you give me an example of where this happens?

1. `create_for_hmd` creates empty `Projection`and calls `set_for_hmd`
1. `set_for_hmd` only calls `set_frustrum` for `eye == 1` or `eye == 2`
1. for all other values `set_for_hmd` returns without changing the projection

**Comment by raulsntos** [comment]
I'm not sure if that is considered a failure since it doesn't push an error, maybe it's intended, in which case C# should behave the same way.

**Comment by aaronfranke** [comment]
Please compare your implementation of Vector4 with the existing implementations:

https://github.com/Geometror/godot/blob/add-vector4/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs

https://github.com/aaronfranke/GodotExtraMath/blob/master/addons/extra_math_cs/ExtraMath/Vector4.cs

**Comment by antonWetzel** [comment]
> Please compare your implementation of Vector4 with the existing implementations:
> 
> https://github.com/Geometror/godot/blob/add-vector4/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs
> 
> https://github.com/aaronfranke/GodotExtraMath/blob/master/addons/extra_math_cs/ExtraMath/Vector4.cs

@aaronfranke I only implemented the same function as exposed to GDScript, but external implementations implement more function. Should the same as GDScript or all maybe usefull functions be implemented?

**Comment by aaronfranke** [comment]
@antonWetzel It would be good to get a list of what's different so that it can be decided more concretely. But in general, I would say that any method that exists on Vector3i should also be in Vector4/4i, because the methods on Vector3i are a subset of the ones in Vector3 and are very useful for vectors to have.

**Comment by akien-mga** [comment]
For this PR I'd say it's fine to keep it strictly to readding C# support by implementing what's currently needed.

Adding more APIs can be done in another PR for both C++/bindings and C#.

**Comment by antonWetzel** [comment]
The good news, I finally managed to clean the branch.
The bad news, I marked everyone as Reviewer; sorry.

I think everything might be done, but write if something needs change.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 1]
```diff
@@ -0,0 +1,817 @@
...
+            f3 /= aspect;
+
+            switch (eye)
+            {
+                case 1:
+                    return CreateFrustum(-f2 * zNear, f1 * zNear, -f3 * zNear, f3 * zNear, zNear, zFar);
+                case 2:
+                    return CreateFrustum(-f1 * zNear, f2 * zNear, -f3 * zNear, f3 * zNear, zNear, zFar);
+                default:
+                    GD.PushError("eye is not 1 or 2");
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:168]: Since the C++ equivalent doesn't push an error here, I don't think C# should either.

https://github.com/godotengine/godot/blob/8cb51a642e7c34a73e7ed877ab46c041521205e5/core/math/projection.cpp#L339-L340

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 2]
```diff
@@ -0,0 +1,817 @@
...
+            {
+                fovyDegrees = GetFovy(fovyDegrees, (real_t)1.0 / aspect);
+            }
+            real_t radians = Mathf.Deg2Rad(fovyDegrees / (real_t)2.0);
+            real_t deltaZ = zFar - zNear;
+            real_t sine = Mathf.Sin(radians);
+
+            if (deltaZ == 0) { GD.PushError("far is equal to near"); return Zero; }
+            if (sine == 0) { GD.PushError("sin of fov is zero"); return Zero; }
+            if (aspect == 0) { GD.PushError("aspect is zero"); return Zero; }
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:248]: Since the C++ equivalent doesn't push an error here, I don't think C# should either.

https://github.com/godotengine/godot/blob/8cb51a642e7c34a73e7ed877ab46c041521205e5/core/math/projection.cpp#L263-L265

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 3]
```diff
@@ -0,0 +1,817 @@
...
+                        }
+                    }
+                }
+
+                /* Product of pivots, gives determinant when finished */
+                determinant *= pvt_val;
+                if (Mathf.IsZeroApprox(determinant))
+                {
+                    GD.PushError("determinant is zero");
+                    return Zero;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:442]: Since the C++ equivalent doesn't push an error here, I don't think C# should either.

https://github.com/godotengine/godot/blob/8cb51a642e7c34a73e7ed877ab46c041521205e5/core/math/projection.cpp#L619-L621

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 4]
```diff
@@ -0,0 +1,817 @@
...
+                    GD.PushError("eye is not 1 or 2");
+                    return Zero;
+            }
+        }
+
+        public static Projection CreateFrustum(real_t left, real_t right, real_t bottom, real_t top, real_t near, real_t far)
+        {
+            if (right <= left) { GD.PushError("right is less or equal to left"); return Zero; }
+            if (top <= bottom) { GD.PushError("top is less or equal to bottom"); return Zero; }
+            if (far <= near) { GD.PushError("far is less or equal to near"); return Zero; }
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:177]: To me this looks like these should be `ArgumentException`.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 5]
```diff
@@ -0,0 +1,817 @@
...
+#endif
+using System;
+using System.Runtime.InteropServices;
+
+
+namespace Godot
+{
+    /// <summary>
+    /// The parameterless constructor returns <see cref="Projection.Zero"/>, not <see cref="Projection.Identity"/> like GDScript.
+    /// </summary>
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:14]: I don't think this comment is necessary, we don't have it for `Transform{2D,3D}`, instead we document it in the `Identity` property and I think that's enough.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 6]
```diff
@@ -0,0 +1,814 @@
...
+                    return Zero;
+            }
+        }
+
+        public static Projection CreateFrustum(real_t left, real_t right, real_t bottom, real_t top, real_t near, real_t far)
+        {
+            if ((right <= left) || (top <= bottom) || (far <= near))
+            {
+                throw new ArgumentException();
+            }
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:174]: Something like this would be more descriptive:

```suggestion
            if (right <= left)
            {
                throw new ArgumentException("right is less or equal to left.");
            }
            if  (top <= bottom)
            {
                throw new ArgumentException("top is less or equal to bottom.");
            }
            if  (far <= near)
            {
                throw new ArgumentException("far is less or equal to near.");
            }
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs [hunk 7]
```diff
@@ -0,0 +1,730 @@
...
+        {
+            return !left.Equals(right);
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is less than
+        /// the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:555]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs [hunk 8]
```diff
@@ -0,0 +1,730 @@
...
+            }
+            return left.x < right.x;
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is greater than
+        /// the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:583]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs [hunk 9]
```diff
@@ -0,0 +1,730 @@
...
+            }
+            return left.x > right.x;
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is less than
+        /// or equal to the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:611]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs [hunk 10]
```diff
@@ -0,0 +1,730 @@
...
+        {
+            if (left.x == right.x)
+            {
+                if (left.y == right.y)
+                {
+                    if (left.z == right.z)
+                    {
+                        return left.w <= right.w;
+                    }
+                    return left.z <= right.z;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:627]:
```suggestion
                    return left.z < right.z;
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs [hunk 11]
```diff
@@ -0,0 +1,730 @@
...
+            }
+            return left.x < right.x;
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is greater than
+        /// or equal to the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:639]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs [hunk 12]
```diff
@@ -0,0 +1,730 @@
...
+        {
+            if (left.x == right.x)
+            {
+                if (left.y == right.y)
+                {
+                    if (left.z == right.z)
+                    {
+                        return left.w >= right.w;
+                    }
+                    return left.z >= right.z;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:655]:
```suggestion
                    return left.z > right.z;
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs [hunk 13]
```diff
@@ -0,0 +1,702 @@
...
+        {
+            return !left.Equals(right);
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4i"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is less than
+        /// the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs:524]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs [hunk 14]
```diff
@@ -0,0 +1,702 @@
...
+            }
+            return left.x < right.x;
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4i"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is greater than
+        /// the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs:552]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs [hunk 15]
```diff
@@ -0,0 +1,702 @@
...
+            }
+            return left.x > right.x;
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4i"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is less than
+        /// or equal to the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs:580]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs [hunk 16]
```diff
@@ -0,0 +1,702 @@
...
+        {
+            if (left.x == right.x)
+            {
+                if (left.y == right.y)
+                {
+                    if (left.z == right.z)
+                    {
+                        return left.w <= right.w;
+                    }
+                    return left.z <= right.z;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs:596]:
```suggestion
                    return left.z < right.z;
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs [hunk 17]
```diff
@@ -0,0 +1,702 @@
...
+            }
+            return left.x < right.x;
+        }
+
+        /// <summary>
+        /// Compares two <see cref="Vector4i"/> vectors by first checking if
+        /// the X value of the <paramref name="left"/> vector is greater than
+        /// or equal to the X value of the <paramref name="right"/> vector.
+        /// If the X values are exactly equal, then it repeats this check
+        /// with the Y values of the two vectors, and then with the Z values.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs:608]:
```suggestion
        /// with the Y values of the two vectors, then with the Z values, and then with the W values.
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs [hunk 18]
```diff
@@ -0,0 +1,702 @@
...
+        {
+            if (left.x == right.x)
+            {
+                if (left.y == right.y)
+                {
+                    if (left.z == right.z)
+                    {
+                        return left.w >= right.w;
+                    }
+                    return left.z >= right.z;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs:624]:
```suggestion
                    return left.z > right.z;
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs (hunk 7 above)
Comment (aaronfranke) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:555]: With the longer text, we should also give it another line.

Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4.cs:555]: I think adding W is pretty long,
I would prefer a shorter version
- If the X values are exactly equal, then it repeats this check with the Y, Z and W values in order.
- If the X values are exactly equal, then it repeats this check with the Y, Z and finally W values of the two vectors.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 19]
```diff
@@ -0,0 +1,822 @@
...
+
+        /// <summary>
+        /// Returns <see langword="true"/> if the projections are exactly equal.
+        /// </summary>
+        /// <param name="left">The left projection.</param>
+        /// <param name="right">The right projection.</param>
+        /// <returns>Whether or not the projections are exactly equal.</returns>
+        public static bool operator ==(Projection left, Projection right)
+        {
+            return (left.x == right.x) && (left.y == right.y) && (left.z == right.z) && (left.w == right.w);
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:621]: Should we use `left.Equals(right)` here like in the other structs?

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 20]
```diff
@@ -0,0 +1,822 @@
...
+
+        /// <summary>
+        /// Returns <see langword="true"/> if the projections are not exactly equal.
+        /// </summary>
+        /// <param name="left">The left projection.</param>
+        /// <param name="right">The right projection.</param>
+        /// <returns>Whether or not the projections are not exactly equal.</returns>
+        public static bool operator !=(Projection left, Projection right)
+        {
+            return !(left == right);
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:632]: Should we use `!left.Equals(right)` here like in the other structs?

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 21]
```diff
@@ -0,0 +1,822 @@
...
+                }
+            }
+        }
+
+        /// <summary>
+        /// Access single values.
+        /// </summary>
+        /// <param name="column">Which column vector.</param>
+        /// <param name="row">Which row of the column.</param>
+        internal real_t this[int column, int row]
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:684]: This operator is public in `Basis`, we may want to consider doing the same here but it shouldn't block this PR.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 22]
```diff
@@ -0,0 +1,822 @@
...
+                }
+            }
+        }
+
+        /// <summary>
+        /// Returns a vector transformed (multiplied) by this projection.
+        /// </summary>
+        /// <param name="v">A vector to transform.</param>
+        /// <returns>The transformed vector.</returns>
+        internal Vector3 Xform(Vector3 v)
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:729]: I would make this method private.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs [hunk 23]
```diff
@@ -0,0 +1,702 @@
...
+#else
+using real_t = System.Single;
+#endif
+using System;
+using System.Runtime.InteropServices;
+
+namespace Godot
+{
+    /// <summary>
+    /// 3-element structure that can be used to represent 3D grid coordinates or sets of integers.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Vector4i.cs:12]: Seems you accidentally left the documentation of Vector3i here.

**Review by raulsntos — CHANGES_REQUESTED** [review]
Thank you very much for working on this, I've finally taken the time to review the entire thing.

The `Projection` type has been difficult to review because it can be hard to read but I think I found some typos, please double check as I might've made a mistake.

Also, the order of the methods is a bit odd, for example in `Vector4` the `Length` and `LengthSquared` methods should be together. I think methods that are strongly related should be kept close to each other, you can look at `Vector3` for reference and maybe try to follow the same order but this is a very minor nit-pick and I don't think it should block the PR.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 24]
```diff
@@ -0,0 +1,822 @@
...
+                Planes.Near => new Plane(x.w + x.z, y.w + y.z, z.z + z.y, w.w + w.z),
+                Planes.Far => new Plane(x.w - x.z, y.w - y.z, z.z - z.y, w.w - w.z),
+                Planes.Left => new Plane(x.w + x.x, y.w + y.x, z.w + z.x, w.w + w.x),
+                Planes.Top => new Plane(x.w - x.y, y.w - y.y, z.w - z.y, w.w - w.y),
+                Planes.Right => new Plane(x.w - x.x, y.w - y.x, z.w - z.x, w.w - w.x),
+                Planes.Bottom => new Plane(x.w + x.y, y.w + y.y, z.w + z.y, w.w + w.y),
+            };
+            newPlane.Normal = -newPlane.Normal;
+            return newPlane.Normalized();
+        }
```
[the remark this answers is not in the document]
Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:394]: added `_ => new Plane()`

1. normal is `Zero`
1. normal negated is `-zero` 
1. `normalized` checks if the normal is zero and returns `Plane` with all zero

The function does more work, but the result is the same. I think the cleaner look is better as the performance for the unusal case.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 25]
```diff
@@ -0,0 +1,822 @@
...
+
+        public real_t GetAspect()
+        {
+            Vector2 vpHe = GetViewportHalfExtends();
+            return vpHe.x / vpHe.y;
+        }
+
+        public Vector2 GetFarPlaneHalfExtends()
+        {
+            var res = GetProjectionPlane(Planes.Far).Intersect3(GetProjectionPlane(Planes.Right), GetProjectionPlane(Planes.Top));
```
[the remark this answers is not in the document]
Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:337]: The results are the same (compared to GDScript with random parameters). 
The c-code planes have the same position, but flipped normals.
(I think the c code should use `get_projection_plane` or define `__inline__ Plane get_..._plane()` x 6 and use the functions in `get_projection_plane` but this is not the scope of this merge)

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 26]
```diff
@@ -0,0 +1,822 @@
...
+                Planes.Right => new Plane(x.w - x.x, y.w - y.x, z.w - z.x, w.w - w.x),
+                Planes.Bottom => new Plane(x.w + x.y, y.w + y.y, z.w + z.y, w.w + w.y),
+            };
+            newPlane.Normal = -newPlane.Normal;
+            return newPlane.Normalized();
+        }
+
+        public Vector2 GetViewportHalfExtends()
+        {
+            var res = GetProjectionPlane(Planes.Near).Intersect3(GetProjectionPlane(Planes.Right), GetProjectionPlane(Planes.Top));
```
[the remark this answers is not in the document]
Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:398]: [same as above](https://github.com/godotengine/godot/pull/63537#discussion_r933960323)

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 27]
```diff
@@ -0,0 +1,822 @@
...
+            return new Vector2(res.Value.x, res.Value.y);
+        }
+
+        public real_t GetZFar()
+        {
+            Plane newPlane = new Plane(x.w + x.z, y.w + y.z, z.z + z.y, w.w + w.z);
```
[the remark this answers is not in the document]
Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:404]: changed to `return GetProjectionPlane(Planes.Far).Normalized().D;`
and `return -GetProjectionPlane(Planes.Near).Normalized().D;`

Same result but different code, I would prefer this version to avoid copy-paste mistakes.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 28]
```diff
@@ -0,0 +1,822 @@
...
+            newPlane.Normal = -newPlane.Normal;
+            return newPlane.D;
```
[the remark this answers is not in the document]
Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:406]: [see](https://github.com/godotengine/godot/pull/63537#discussion_r933963492)

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs (hunk 24 above)
[the remark this answers is not in the document]
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs]: I agree with the cleaner look, not sure if `_ => new Plane()` is necessary since structs get default initialized anyway. I originally missed that `normalized` would return a `Plane` with all zero, I was worried we'd be returning negative zeroes.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs (hunk 27 above)
[the remark this answers is not in the document]
Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs]: If you are using `GetProjectionPlane` isn't `.Normalized` unnecessary? Since `GetProjectionPlane` already normalizes the result.

[the remark this answers is not in the document]
Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs]: yep

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs [hunk 29]
```diff
@@ -0,0 +1,820 @@
...
+                        hold = proj[i][k];
+                        proj[i, k] = -proj[i][j];
+                        proj[i, j] = hold;
+                    }
+                }
+            }
+            return proj;
+        }
+
+        public bool IsOrthorgonal()
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs:555]: There's a typo in the name:

```suggestion
        public bool IsOrthogonal()
```

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs (hunk 24 above)
[the remark this answers is not in the document]
Comment (antonWetzel) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Projection.cs]: This type of switch throws a `SwitchExpressionException` if a case is not handled. The `_ => new Plane()` is required to match the c implementation.

**Review by raulsntos — APPROVED** [review]
This looks good to me.

For future work we may want to look into making the C++ `Projection` implementation less repetitive by reusing `get_projection_plane` instead of manually creating the planes from scratch since it can be error-prone, and it'd be nice to have unit tests for this.
Also, we may want to consider if we need to add/expose more methods in `Vector4{i}` as mentioned earlier.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by antonWetzel** [comment]
@raulsntos Thanks for the help
