### PR TITLE
Editor debugger now always handle connections.

### LINKED ISSUE #28168: Networking disconnects after some time
From Discord:
>Does anyone else have issues where their client just gets disconnected no matter what after a few minutes?
It's happening FAR less when I don't use a rpc() call back to the client after receiving one. I can reproduce it pretty much every time when just doing that. Make rpc to server, that method makes rpc back to the client. Is there any reason why it's bad to do that?

User `ex` on Discord provided a server and client project reproducing this behaviour reliably for them. (Thanks for the effort, by the way!)

Info:
>Think I have it so it's reproduced every time. I'm not even sure if it's that the client is disconnecting. The client freezes first, it seems (not sure if that's due to a dc).
>Here's a zip of the client/server project. Don't feel like messing with github right now. Might be able to later.
>1. Start server
>2. Start client
>3. Wait. Without fail, client crashes/dcs after a few minutes (often times happens when the counter hits around 8,000 for me)
>
>(Godot 3.1 stable)
>windows 10 pro, ryzen 2700x, Intel(R) I211 Gigabit Network Connection.
over localhost (client/server on same comp)

[dc-crash-bug.zip](https://github.com/godotengine/godot/files/3096602/dc-crash-bug.zip)

### PR DESCRIPTION
**Pull request by Faless**
The editor debugger used to only take the first client connection,
leaving potential new connections hanging until TCP timeout.
This caused a lock after some time when running multiple game/editor
instances, as the client will fill the write buffer, and then lock until
timeout (as the editor server would never read from that socket).

The editor now drops new connections immediately if it is already
connected to a client.

Fixes #28168

### CODE REVIEW

File: editor/script_editor_debugger.cpp [hunk 1]
```diff
@@ -1132,10 +1132,15 @@ void ScriptEditorDebugger::_notification(int p_what) {
...
 
-			if (connection.is_null()) {
-
-				if (server->is_connection_available()) {
-
+			if (server->is_connection_available()) {
+				if (connection.is_valid()) {
+					// We already have a valid connection.
+					// Disconnecting any new connecting client to prevent it from hanging.
+					Ref<StreamPeerTCP> conn = server->take_connection();
```
Comment (Faless) [inline editor/script_editor_debugger.cpp]: This could just be `server->take_connection();` (going out of scope will cause the TCP stream to close), but I prefer the explicit code (while less performant). Let me know if I should change it.

Comment (Faless) [reply editor/script_editor_debugger.cpp]: Maybe I should actually just do that and add it in the comment...

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
