### PR TITLE
Prevent AnimationPlayer from being added on GLTF import if the option is unckecked

### LINKED ISSUE #63954: Animation(s) Imported Despite Import Settings Unchecked
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Ubuntu 22.04, NVIDIA GeForce GTX 765M 

### Issue description

GLTF animations get imported despite setting unchecked:

import_no-anim

The created scene contains an `AnimationPlayer` node:

scene_anim-player

Which contains the animation resource:

anim_clip-res

I would expect neither the animation player node to be present nor the animation data to be generated.

### Steps to reproduce

1. Disable the animation import settings check-box for an GLTF file which contains at least one animation
2. Open the imported scene and observe an `AnimationPlayer` node present with the imported animation data (both unexpected)

For your convenience I added a sample project with a simple rotating cube gltf (`cube_rot.glb`). The import settings have animation unchecked but it is ignored.

### Minimal reproduction project

[import-no-anim-bug.zip](https://github.com/godotengine/godot/files/9267838/import-no-anim-bug.zip)

### PR DESCRIPTION
**Pull request by hakro**
Fixes #63954

### CODE REVIEW

**Review by fire — APPROVED** [review]
The paper code review looks good.

My understanding of the pull request is that when we import, we set the state of `state->set_create_animations(bool(p_options["animation/import"]));`

then we don't parse or create the animation.

File: modules/gltf/editor/editor_scene_importer_gltf.cpp [hunk 1]
```diff
@@ -60,6 +60,7 @@ Node *EditorSceneFormatImporterGLTF::import_scene(const String &p_path, uint32_t
 		}
 		return nullptr;
 	}
+	state->set_create_animations(bool(p_options["animation/import"]));
```
Comment (fire) [inline modules/gltf/editor/editor_scene_importer_gltf.cpp:63]: Sometimes options can be empty.

Try doing a p_options.has("animation/import") check before accessing the dictionary.

Comment (hakro) [reply modules/gltf/editor/editor_scene_importer_gltf.cpp]: Right, I removed at some point because I saw p_options used elsewhere without checking.
But you're absolutely correct, better check anyway.
I just pushed a check

**Comment by fire** [comment]
Please check the pr guide https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html.

You're missing documentation.

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Cherry-picked for 3.6
