### PR TITLE
Fix Image CowData crash when baking large lightmaps

### LINKED ISSUE #54679: Vulkan: Crash when baking lightmaps with LightmapGI if the resulting image is too large (due to CowData using 32-bit ints)
### Godot version

4.0.dev (4651b2ae5)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The editor crashes when baking lightmaps with LightmapGI in a specific scene (see the MRP included).

Backtrace:

```
[1] /lib64/libc.so.6(+0x3d320) [0x7fdb5cf60320] (??:0)
[2] /lib64/libc.so.6(+0x163b81) [0x7fdb5d086b81] (??:0)
[3] Image::create(int, int, bool, Image::Format) (/home/hugo/Documents/Git/godotengine/godot/core/io/image.cpp:1996)
[4] LightmapperRD::_blit_meshes_into_atlas(int, Vector<Ref<Image> >&, Vector<Ref<Image> >&, AABB&, Vector2i&, int&, bool (*)(float, String const&, void*, bool), void*) (/home/hugo/Documents/Git/godotengine/godot/modules/lightmapper_rd/lightmapper_rd.cpp:258)
[5] LightmapperRD::bake(Lightmapper::BakeQuality, bool, int, float, int, bool, Lightmapper::GenerateProbes, Ref<Image> const&, Basis const&, bool (*)(float, String const&, void*, bool), void*) (/home/hugo/Documents/Git/godotengine/godot/modules/lightmapper_rd/lightmapper_rd.cpp:684)
[6] LightmapGI::bake(Node*, String, bool (*)(float, String const&, void*, bool), void*) (/home/hugo/Documents/Git/godotengine/godot/scene/3d/lightmap_gi.cpp:954)
[7] LightmapGIEditorPlugin::_bake_select_file(String const&) (/home/hugo/Documents/Git/godotengine/godot/editor/plugins/lightmap_gi_editor_plugin.cpp:39)
[8] void call_with_variant_args_helper<LightmapGIEditorPlugin, String const&, 0ul>(LightmapGIEditorPlugin*, void (LightmapGIEditorPlugin::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:223)
[9] void call_with_variant_args<LightmapGIEditorPlugin, String const&>(LightmapGIEditorPlugin*, void (LightmapGIEditorPlugin::*)(String const&), Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:338)
[10] CallableCustomMethodPointer<LightmapGIEditorPlugin, String const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/./core/object/callable_method_pointer.h:97)
[11] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:51)
[12] Object::emit_signal(StringName const&, Variant const**, int) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1099)
[13] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1154)
[14] EditorFileDialog::_action_pressed() (/home/hugo/Documents/Git/godotengine/godot/editor/editor_file_dialog.cpp:477)
[15] void call_with_variant_args_helper<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:228)
[16] void call_with_variant_args<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:338)
[17] CallableCustomMethodPointer<EditorFileDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/./core/object/callable_method_pointer.h:97)
[18] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:51)
[19] Object::emit_signal(StringName const&, Variant const**, int) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1099)
[20] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1154)
[21] AcceptDialog::_ok_pressed() (/home/hugo/Documents/Git/godotengine/godot/scene/gui/dialogs.cpp:105)
[22] void call_with_variant_args_helper<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:228)
[23] void call_with_variant_args<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:338)
[24] CallableCustomMethodPointer<AcceptDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/./core/object/callable_method_pointer.h:97)
[25] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:51)
[26] Object::emit_signal(StringName const&, Variant const**, int) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1099)
[27] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/hugo/Documents/Git/godotengine/godot/core/object/object.cpp:1154)
[28] BaseButton::_pressed() (/home/hugo/Documents/Git/godotengine/godot/scene/gui/base_button.cpp:126)
[29] BaseButton::on_action_event(Ref<InputEvent>) (/home/hugo/Documents/Git/godotengine/godot/scene/gui/base_button.cpp:?)
[30] BaseButton::gui_input(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/gui/base_button.cpp:67)
[31] Control::_call_gui_input(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/gui/control.cpp:823)
[32] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:1276)
[33] Viewport::_gui_input_event(Ref<InputEvent>) (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:1579)
[34] Viewport::push_input(Ref<InputEvent> const&, bool) (/home/hugo/Documents/Git/godotengine/godot/scene/main/viewport.cpp:2691)
[35] Window::_window_input(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/scene/main/window.cpp:919)
[36] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:223)
[37] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/home/hugo/Documents/Git/godotengine/godot/./core/variant/binder_common.h:338)
[38] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/./core/object/callable_method_pointer.h:97)
[39] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/hugo/Documents/Git/godotengine/godot/core/variant/callable.cpp:51)
[40] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/display_server_x11.cpp:2970)
[41] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/display_server_x11.cpp:2954)
[42] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/hugo/Documents/Git/godotengine/godot/core/input/input.cpp:621)
[43] Input::flush_buffered_events() (/home/hugo/Documents/Git/godotengine/godot/core/input/input.cpp:840)
[44] DisplayServerX11::process_events() (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/display_server_x11.cpp:3811)
[45] OS_LinuxBSD::run() (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/os_linuxbsd.cpp:338)
[46] bin/godot.linuxbsd.tools.64.llvm(main+0x1c6) [0x45c8756] (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/godot_linuxbsd.cpp:58)
[47] /lib64/libc.so.6(__libc_start_main+0xd5) [0x7fdb5cf4ab75] (??:0)
[48] bin/godot.linuxbsd.tools.64.llvm(_start+0x2e) [0x45c84ce] (??:?)
-- END OF BACKTRACE --
```

### Steps to reproduce

- Open the MRP below in the editor.
- Select the LightmapGI node and click **Bake** at the top of the 3D viewport.
- Wait 10-50 seconds for the editor to crash.

### Minimal reproduction project

[global_illumination.zip](https://github.com/godotengine/godot/files/7491081/global_illumination.zip)

### PR DESCRIPTION
**Pull request by Calinou**
This switches to 64-bit integers in select locations of the Image class, so that image resolutions of 16384×16384 (used by lightmap texture arrays) can be used properly. Values that are larger should also work (the Image class' `MAX_PIXELS` constant is `2^28` pixels, and `2^24` pixels on each axis).

VRAM compression is also supported, although most VRAM-compressed formats are limited to individual slices of 16384×16384. WebP is limited to 16383×16383 due to format limitations.

Note that very large lightmaps will cause the scene to load significant slower – this would be addressed by using VRAM compression, but it's currently very slow on lightmaps this large. https://github.com/godotengine/godot/pull/91535 should make compression times more reasonable, but I haven't tested it together with this PR yet. https://github.com/godotengine/godot/pull/50574 can also help bring down file sizes and memory usage (and could be coupled with VRAM compression for further gains).

Please test this on your own projects :slightly_smiling_face: 

cc @jcostello @BlueCube3310 @SpockBauru @jitspoe @TokisanGames @DarioSamo

PS: How do we handle GDExtension compatibility on this one? Is it possible to add a compatibility method in this case?

```
Error: Validate extension JSON: Error: Field 'classes/Image/methods/get_mipmap_offset/return_value': meta changed value in new API, from "int32" to "int64".
```

- This closes https://github.com/godotengine/godot/issues/54679.

**Testing project:** [global_illumination_updated.zip](https://github.com/user-attachments/files/16184863/global_illumination_updated.zip)
*Previously, this project would crash upon baking lightmaps. It works now.*

## Preview

Lightmap editor

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]

File: core/io/image.cpp [hunk 1]
```diff
@@ -329,37 +329,41 @@ void Image::_get_mipmap_offset_and_size(int p_mipmap, int &r_offset, int &r_widt
...
 	ERR_FAIL_INDEX_V(p_mipmap, get_mipmap_count() + 1, -1);
 
-	int ofs, w, h;
+	int64_t ofs;
+	int w, h;
 	_get_mipmap_offset_and_size(p_mipmap, ofs, w, h);
 	return ofs;
 }
 
 int Image::get_mipmap_byte_size(int p_mipmap) const {
```
Comment (akien-mga) [inline core/io/image.cpp:341]: Shouldn't this one return `int64_t` too? Since it's a difference between two offsets.

**Comment by reduz** [comment]
@RandomShaper Since you are here, I think these have to be fixed too:
https://github.com/godotengine/godot/blob/97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b/servers/rendering/rendering_device_commons.h#L856

I think some return size or offset in uint32_t (my fault).

**Review by akien-mga — COMMENTED** [review]
Looks great!

There are some tests that need adjustments too (see diff view) and a compat method needs to be registered for `get_mipmap_offset`.

**Comment by passivestar** [comment]
@Calinou the provided test project has glb with the default texel size of `0.1` and LightmapGI texel scale is also the default value `1`. Not knowing what large value to change it to for testing I set it to `30` and it immediately crashed the editor when I clicked bake :D
```
MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion Texture Descriptor Validation
MTLTextureDescriptor has width (210870) greater than the maximum allowed size of 16384.
MTLTextureDescriptor has height (278700) greater than the maximum allowed size of 16384.
```

**Comment by Saul2022** [comment]
> what large value to change it to for testing I set it to `30` and it immediately crashed the editor when I clicked bake :D

It might be the file size and the fact it still really slpw for the m1 max to handle. 


> MTLTextureDescriptor has height (278700) greater than the maximum allowed size of 16384.


Why is it so big  lol...

**Comment by jcostello** [comment]
Im getting this error baking sponza with texel density set to `3`

```
 Too many pixels for Image. Maximum is 16777216x16777216 = 268435456pixels.
  core/io/image.cpp:2798 - Condition "dsize == 0" is true.
```

**Comment by SpockBauru** [comment]
Built @Calinou's repo locally and made a test with my LightmapProbeGrid plugin demo scene. I enabled lightmap only for the terrain (disabled for the tunnel, trees, etc.).

Here the test project, you may have to restart on the first launch because the probes plugin:

[LightmapProbeGrid.zip](https://github.com/user-attachments/files/16195658/LightmapProbeGrid.zip)

There are 2 modified scenes on this test: the Demo Scene (main scene) and the Terrain scene (GLTF inherited scene).

On the Terrain scene, unwrapping the terrain's UV2 in Godot generates a Lightmap Size Hint of 12034x12238 (the terrain is not perfectly squared) which is bellow the 16384 max size from this PR.

Back to the demo scene if I bake the LightmapGI it results in a wall or errors with a pitch-black terrain and the lightmap .exr file is also full black. The same happen lowering the resolution all way down to 8192 (2^13):

image

image


By reducing the Lightmap Size Hint to 8053x8190, it freezes the editor on `Determining optimal atlas size`:
image

image

With the resolution of 8023x8139, it bakes normally without errors. The resulting EXR file has a resolution of 8192x8192
image

image

In a short: Any attempt on creating a Lightmap file with resolution above 8192 didn't work on this demo :'(

**Comment by BlueCube3310** [comment]
> By reducing the Lightmap Size Hint to 8053x8190, it freezes the editor on `Determining optimal atlas size

Could you try rebasing this on top of #94237?

**Comment by SpockBauru** [comment]
> > By reducing the Lightmap Size Hint to 8053x8190, it freezes the editor on `Determining optimal atlas size
> 
> Could you try rebasing this on top of #94237?

Sorry, I can't... I don't have enough knowledge to do that :'(

**Comment by BlueCube3310** [comment]
After adding the patches from that PR 16k lightmaps bake correctly. The first case seems to happen when the generated atlas is rounded to 32k, though I'm not certain about that yet.

**Comment by Calinou** [comment]
Very few GPUs support 32768x32768 textures and their memory usage is obscene, so the lightmapper should clamp the size down in that case (and print a warning advising the user to reduce their texel scale property).

**Comment by lyuma** [comment]
> the lightmapper should clamp the size down in that case (and print a warning advising the user to reduce their texel scale property).

The entire underlying issue here is a UX problem and lack of communication with the user.

i doubt I have ever *wanted* godot to create even a 16k lightmap texture. It is still better to not crash, but we certainly shouldn't make it possible to go higher.

> Textures should already not exceed 4096x4096 in the first place if you want them to show up reliably on mobile/web platforms 

Indeed, this is the real problem. I think Godot needs better UX here to show the user what size texture would be generated, explain the consequences with mobile and web support, diagnose which meshes are responsible for the bloated size, and give the user various options to keep the lightmap within the size budget the user asks for.

It might be nice to have a max lightmap size option and perhaps options like "downscale" or "error" if it goes over that size budget. (The problem is usually one mesh is taking way more space in the lightmap, and it might be a relatively unimportant object or have very little detail, so if I knew which it is then I could adjust the settings)

**Comment by jcostello** [comment]
@lyuma sorry my ignorance, but is there a limit of how big a scene can be (because of the texture size) or the problem is the texel density?

**Comment by Saul2022** [comment]
> > the lightmapper should clamp the size down in that case (and print a warning advising the user to reduce their texel scale property).


Agreeed, even ue5 being  pretty high end  might just support 8k texture at  maximum here.

Screenshot_20240714_053655_Chrome

**Comment by lyuma** [comment]
We tend to discourage posting AI responses because of its tendency to be verbose or inaccurate: the AI generated response is wrong. UE4's resolution limit of 8192 is likely no longer present at least in UE 5.1, (and UE 5.x in particular may be able to make use of virtual texturing in some cases to go beyond conventional resolution limits)

That said, UE5 docs contain this warning:
> "Some GPUs have hardware limits in the maximum size texture they can support. For example, some GPUs may not support texture sizes larger than 8192 pixels (8k)."

my guess is most desktop GPUs support 16k (supposedly GPUs without support for 16k will be DX10 only). Still, relying on 16k textures might make your content inaccessible to mobile users or old/low-end desktop hardware.

That said, while an uncompressed 16k HDR lightmap texture will take 2 Gigabytes of contiguous memory which would be impractical on most GPUs, BPTC should be able to cut that down to 8bpp, only 256MB of memory, which should be acceptable.

**Comment by SpockBauru** [comment]
I believe the main issue is not the lightmap size, but the lack of automatic lightmap tiling where lightmaps are splitted in chunks.

In Unity you can set the max size of each tile and several are automatically generated according the need. The engine bakes one by one so gpus with low amount of memory can bake big scenes without issues. Tiles have not a fixed size, but rather vary according the region.

For Godot we can take a step further and after baking make the game load/unload each tile as needed, but how to make it must be a topic of careful discussion since is far from trivial.

Since Godot aims to include low end platforms and also simplify the development as much as possible, I believe that a fully automatic tiling system without the need for user interaction would be the best approach for developing games with relative big maps, not only full open worlds but also things like a racing game with 10km tracks, or something like the Gran Pulse level on Final Fantasy XIII.

**Comment by Calinou** [comment]
> For Godot we can take a step further and after baking make the game load/unload each tile as needed, but how to make it must be a topic of careful discussion since is far from trivial.

Mesh splitting is needed to get decent culling (and already has its own proposal), but it's difficult to do right in a way that preserves materials and both UV layers.

**Comment by SpockBauru** [comment]
> Mesh splitting is needed to get decent culling (and already has its own [proposal](https://github.com/godotengine/godot-proposals/issues/3673)), but it's difficult to do right in a way that preserves materials and both UV layers.

As far as I remember, Unity does not perform mesh splitting on the lightmaps, it only groups whole meshes.

 Instead, the user defines the max size of the lightmap tile and if a mesh exceeds that, the lightmap resolution of the mesh is automatically shrunk to fit the max size. After baking a warning is print in the console.


Example:

If a terrain with 1km² have defined 4 samples per meter, it would not fit an 1024x1024 lightmap tile. In this case the engine automatically shrinks the terrain lightmap resolution to fit the max tile size. 

After that, the bake is done normally and give a console warning telling the user what objects had their lightmap resolution reduced.

**Comment by Saul2022** [comment]
Prob or we could do what unreal does as making the lightmap a texture atlas( idk if it’s done already, but it’s an idea for file sizes). As for resolution  i agree with lyuma  about limit prob being 15k since with this and bluecibe performance it does seem to improve the situatuon, though i would say an resolution limit option  should be brought in.

**Comment by BlueCube3310** [comment]
The other compression modes (ASTC, CVTT, etcpak) should probably be adjusted for this as well, even though compressed images technically shouldn't require 64-bit offsets/sizes.

**Comment by akien-mga** [comment]
Rebased and updated the PR to fix the image unit tests.

I also removed `int Image::get_mipmap_byte_size(int p_mipmap) const` which wasn't used anywhere (its only used was in 4 years old `#if 0`'d code, which I removed too).

> The other compression modes (ASTC, CVTT, etcpak) should probably be adjusted for this as well, even though compressed images technically shouldn't require 64-bit offsets/sizes.

I guess we can merge this PR first and either @BlueCube3310 or @Calinou can do this as a follow-up?

File: core/io/image.compat.inc [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+#ifndef DISABLE_DEPRECATED
+
+int32_t Image::_get_mipmap_offset_bind_compat_94243(int p_mipmap) const {
+	return get_mipmap_offset(p_mipmap);
+}
+
+void Image::_bind_compatibility_methods() {
+	ClassDB::bind_compatibility_method(D_METHOD("get_mipmap_offset", "mipmap"), &Image::_get_mipmap_offset_bind_compat_94243);
+}
```
Comment (akien-mga) [inline core/io/image.compat.inc:39]: @raulsntos @dsnopek Not sure how to deal with this compat method, it seems GDExtension and C# have conflicting needs.

- GDExtension (at least our CI checks) want a compat method as the return type changed from `int32_t` to `int64_t`.
- C# doesn't like it and complains:
```
/home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Image.cs(1207,17): error CS0111: Type 'Image' already defines a member called 'GetMipmapOffset' with the same parameter types [/home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
```

Comment (dsnopek) [reply core/io/image.compat.inc:39]: Hm. Having a compatibility method for the change in return type is the right thing to do for GDExtension. Perhaps the C# code generation hasn't yet had to take into account a compatibility method where the only change is the return type?

Comment (akien-mga) [reply core/io/image.compat.inc:39]: The glue generation seems to have logic to skip methods with conflicting signature:

https://github.com/godotengine/godot/blob/293c0f76463a4e1c2c2e86d8fbfc3e04f491b347/modules/mono/editor/bindings_generator.cpp#L3928-L3935

But the implementation seems to ignore the return type, and I don't really understand the comment justifying it.

https://github.com/godotengine/godot/blob/293c0f76463a4e1c2c2e86d8fbfc3e04f491b347/modules/mono/editor/bindings_generator.cpp#L4762-L4765

Comment (raulsntos) [reply core/io/image.compat.inc]: C# can't have overloads where the only thing that changes is the return type, so these kinds of changes break compat for C#.

The bindings generator avoids generating these compat methods, to avoid generating invalid C# that won't compile. That's what the comment is trying to say, we don't compare the return type because we don't care if they are different it should still return `true` in this case (the method is still considered conflicting even if the return type is different).

I'm pretty sure we already have cases of compat methods where the only thing that changes is the return type, so this should already be handled. Not sure why it would generate invalid C# in this case, it may have something to do with the type, `int32_t` and `int64_t` are really both `INT` with different metadata, so maybe ClassDB gets confused about this and it's not properly registering the compat method.

The bindings generator only checks conflicting methods of compat methods, so if it's not registered as a _compat method_ it won't check. We assume there are no conflicts in the non-compat methods because ClassDB doesn't support method overloading.

Comment (akien-mga) [reply core/io/image.compat.inc]: > The bindings generator only checks conflicting methods of compat methods, so if it's not registered as a _compat method_ it won't check. We assume there are no conflicts in the non-compat methods because ClassDB doesn't support method overloading.

Can't there be conflicts between a compat method and a non-compat method though, like we have here apparently?

Comment (raulsntos) [reply core/io/image.compat.inc]: So I've built locally to check the generated C# and I see 2 `GetMipmapOffset` methods with identical signatures:

```csharp
public long GetMipmapOffset(int mipmap)
```

Note how both methods are returning `long` (`int64_t`). So it looks like the method that returns a 64-bit integer is registered twice. Also, neither of the 2 methods is generated with the EB never attribute, this attribute is always added to compat methods:

https://github.com/godotengine/godot/blob/9508a52e2edd2aca59806e8bbba20408c36c354a/modules/mono/editor/bindings_generator.cpp#L3908-L3909

This looks like the method is registered twice as a non-compat method. So I suspect registering the compat method in ClassDB is getting confused because the method signature is the same, since the only difference in the return type is metadata.

Comment (akien-mga) [reply core/io/image.compat.inc]: > I'm pretty sure we already have cases of compat methods where the only thing that changes is the return type, so this should already be handled. Not sure why it would generate invalid C# in this case, it may have something to do with the type, `int32_t` and `int64_t` are really both `INT` with different metadata, so maybe ClassDB gets confused about this and it's not properly registering the compat method.

At least for the GDExtension API, it seems to handle `int32` and `int64` properly via some metadata:
```
				{
					"name": "get_mipmap_offset",
					"is_const": true,
					"is_vararg": false,
					"is_static": false,
					"is_virtual": false,
					"hash": 923996154,
					"hash_compatibility": [
						923996154
					],
					"return_value": {
						"type": "int",
						"meta": "int64"
					},
					"arguments": [
						{
							"name": "mipmap",
							"type": "int",
							"meta": "int32"
						}
					]
				},
```

We're maybe missing handling the `meta` when the type is `Variant::INT` to handle this and recognize that it's two different signatures?

Comment (raulsntos) [reply core/io/image.compat.inc]: The `hash` and the `hash_compatibility` are the same (`923996154`). @dsnopek Are you sure registering a compat method in this case is correct? I think I remember something about not adding compat methods when the only thing that changes is the types metadata.

Comment (dsnopek) [reply core/io/image.compat.inc]: > The `hash` and the `hash_compatibility` are the same (`923996154`). @dsnopek Are you sure registering a compat method in this case is correct?

Ah, no, actually I think you're right. GDExtension always uses `int64_t` in its encoding anyway, so the metadata change only affects the data type that bindings generate. So, if the hash doesn't change, then we don't need the compatibility method. Sorry for the incorrect info earlier!

Comment (akien-mga) [reply core/io/image.compat.inc]: So it's our CI script that needs fixing I guess?

Or should I just include the line in the `.expected` file and write that it doesn't require a compat binding?

Comment (dsnopek) [reply core/io/image.compat.inc]: What is the error line? Is it actually complaining about a missing hash?

This close to 4.3, I'd say adding the line to `.expected` is probably fine for now - we can work on CI more later.

Comment (akien-mga) [reply core/io/image.compat.inc]: Hm no it didn't actually complain about the hash, only:
```
Validate extension JSON: Error: Field 'classes/Image/methods/get_mipmap_offset/return_value': meta changed value in new API, from "int32" to "int64".
```

I'll silence it.

After 4.3 we could review the CI script, maybe it shouldn't report changes to `meta` at all?

**Review by akien-mga — APPROVED** [review]
Changes look good to me, and I confirmed it fixes the linked issue.

File: core/io/image.compat.inc (hunk 2 above)
Comment (dsnopek) [reply core/io/image.compat.inc]: Only the errors about missing hashes really affect GDExtension binary compatibility, and call out the need for a compatibility method.

The rest are good to consider for source compatibility, like, we don't want to completely change an API signature, better to add new arguments at the end with defaults. And these errors help to call out API changes, that we might otherwise miss.

But we could certainly make the CI more clear that the hash change ones that require compatibility methods, and should only very, very rarely be ignored.

**Comment by akien-mga** [comment]
Thanks!

**Comment by SpockBauru** [comment]
Downloaded the windows artifact and simplified the terrain scene to include only the needed parts. Now we can simply set the lightmap_size_hint on the Terrain Mesh node to get the desired lightmap file size after baking.

Terrain test scene:

[TerrainLightmapTest.zip](https://github.com/user-attachments/files/16314203/TerrainLightmapTest.zip)


I agree that this PR can be merged as it is, and a follow up will be needed.

The artifact can correctly generate Lightmap files up to 8192, which is better than we had, but between this value and the proposed 16384 it still generates a black lightmap file with a wall of errors.

May I be tagged on the follow up PR to test this issue? ^-^
