### PR TITLE
Fix RayShape collision when used with a KinematicBody (Bullet Physics)

### LINKED ISSUE #25227: RayShape collision on KinematicBody stopped workin in 3.1 beta 2
**Godot version:**
Godot_v3.1-beta2_x11.64

**Issue description:**
I have a KinematicBody 3D with a box and a ray collision shape.
It works perfect in 3.1 beta 1, but the same project in beta 2 ignores the RayShape.

**Steps to reproduce:**
Use a RayShape collision on a kinematic body. It is ignored. Change to box shape. It works.

**Minimal reproduction project:**
I attached a sample project.
In Beta 2:
- The red sphere has a box collision shape and stops on the static body floor
- the green sphere has a RayShape and falls through the floor.

in beta 1: the project is working.

[RayShapeBug.zip](https://github.com/godotengine/godot/files/2783002/RayShapeBug.zip)

### PR DESCRIPTION
**Pull request by aqnuep**
- Added code handling non-compound collision to recover_from_penetration_ray()
  which is now needed due to the optimization avoiding the use of compound
  collisions when only a single collision shape is used.
- Removed arbitrary margin applied in the collision algorithm of RayShapes
  which causes jittered movement. For lack of a better replacement and for
  lack of any explanation on why it has been introduced, it's now using the
  shape's margin property instead which is small enough to not show visible
  jitter.
- Removed hack from GodotDeepPenetrationContactResultCallback::addContactPoint
  for RayShape collision as it's no longer needed as the collision algorithm
  of RayShapes correctly calculates the contact normal for a while now.

Fixes #25227.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @AndreaCatania

File: modules/bullet/godot_ray_world_algorithm.cpp [hunk 1]
```diff
@@ -102,7 +100,7 @@ void GodotRayWorldAlgorithm::processCollision(const btCollisionObjectWrapper *bo
 
 		btScalar depth(ray_shape->getScaledLength() * (btResult.m_closestHitFraction - 1));
 
-		if (depth >= -RAY_STABILITY_MARGIN)
+		if (depth >= -ray_shape->getMargin())
```
Comment (AndreaCatania) [inline modules/bullet/godot_ray_world_algorithm.cpp]: This seems good, but you should remove the margin here:
/godot/modules/bullet/btRayShape.cpp:100

File: modules/bullet/godot_result_callbacks.cpp [hunk 2]
```diff
@@ -333,14 +333,6 @@ void GodotDeepPenetrationContactResultCallback::addContactPoint(const btVector3
 		m_other_compound_shape_index = isSwapped ? m_index0 : m_index1;
 		m_pointWorld = isSwapped ? (pointInWorldOnB + (normalOnBInWorld * depth)) : pointInWorldOnB;
 
-		const btCollisionObjectWrapper *bw0 = m_body0Wrap;
-		if (isSwapped)
-			bw0 = m_body1Wrap;
-
-		if (bw0->getCollisionShape()->getShapeType() == CUSTOM_CONVEX_SHAPE_TYPE) {
-			m_pointNormalWorld = bw0->m_worldTransform.getBasis().transpose() * btVector3(0, 0, 1);
```
[the remark this answers is not in the document]
Comment (aqnuep) [reply modules/bullet/godot_result_callbacks.cpp]: Have you actually tested this? Because the sample project in the issue works for me identically in both GodotPhysics and Bullet, with both "Slips On Slope" set to on and off.

IIRC this code I removed practically breaks "Slips On Slope" set to on, so that's why I removed it.

File: modules/bullet/godot_ray_world_algorithm.cpp (hunk 1 above)
Comment (aqnuep) [reply modules/bullet/godot_ray_world_algorithm.cpp]: That makes sense. I'll do so.

File: modules/bullet/godot_result_callbacks.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (AndreaCatania) [reply modules/bullet/godot_result_callbacks.cpp]: Yes I did, and the idea is that when slips on slope is true this condition should fail. I can give it a try later

[the remark this answers is not in the document]
Comment (AndreaCatania) [reply modules/bullet/godot_result_callbacks.cpp]: Ok so this one is correct and you can leave this as is now

File: modules/bullet/space_bullet.cpp [hunk 3]
```diff
@@ -1275,22 +1290,26 @@ int SpaceBullet::recover_from_penetration_ray(RigidBodyBullet *p_body, const btT
...
-						B_TO_G(r_recover_result.normal, r_results[ray_index].collision_normal);
-						B_TO_G(btRigid->getVelocityInLocalPoint(r_recover_result.pointWorld - btRigid->getWorldTransform().getOrigin()), r_results[ray_index].collider_velocity);
-						r_results[ray_index].collision_local_shape = kinIndex;
-						r_results[ray_index].collider_id = collisionObject->get_instance_id();
-						r_results[ray_index].collider = collisionObject->get_self();
-						r_results[ray_index].collider_shape = r_recover_result.other_compound_shape_index;
+						convert_to_separation_result(&r_results[ray_index], recover_result, kinIndex, otherObject);
 					}
 				}
+			} else if (otherObject->getCollisionShape()->isConvex()) {
```
Comment (AndreaCatania) [inline modules/bullet/space_bullet.cpp]: Here is necessary to remove this if statment, because the correct ray algorithm is executed when this function `RFP_convex_world_test` is called.

So the function `RFP_convex_convex_test` must not be called

**Review by AndreaCatania — CHANGES_REQUESTED** [review]

File: modules/bullet/godot_ray_world_algorithm.cpp [hunk 4]
```diff
@@ -102,7 +100,7 @@ void GodotRayWorldAlgorithm::processCollision(const btCollisionObjectWrapper *bo
...
 			depth = 0;
```
Comment (AndreaCatania) [inline modules/bullet/godot_ray_world_algorithm.cpp]: can you please change this with: `depth *= 0.5;`

File: modules/bullet/btRayShape.cpp [hunk 5]
```diff
@@ -97,7 +97,7 @@ void btRayShape::getPreferredPenetrationDirection(int index, btVector3 &penetrat
 
 void btRayShape::reload_cache() {
 
-	m_cacheScaledLength = m_length * m_localScaling[2] + m_collisionMargin;
+	m_cacheScaledLength = m_length * m_localScaling[2];
```
Comment (AndreaCatania) [inline modules/bullet/btRayShape.cpp]: Can you please revert this one, we need it I was wrong.

**Review by AndreaCatania — CHANGES_REQUESTED** [review]

**Comment by AndreaCatania** [comment]
Can you please change this function
```
void btRayShape::getAabb(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const {
#define MARGIN_BROADPHASE 0.1
	btVector3 localAabbMin(0, 0, 0);
	btVector3 localAabbMax(m_shapeAxis * m_length);
	btTransformAabb(localAabbMin, localAabbMax, MARGIN_BROADPHASE, t, aabbMin, aabbMax);
}
```

To this one:
```
void btRayShape::getAabb(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const {
#define MARGIN_BROADPHASE 0.1
	btVector3 localAabbMin(0, 0, 0);
	btVector3 localAabbMax(m_shapeAxis * (m_length * m_localScaling[2] + m_collisionMargin));
	btTransformAabb(localAabbMin, localAabbMax, MARGIN_BROADPHASE, t, aabbMin, aabbMax);
}
```

File: modules/bullet/btRayShape.cpp (hunk 5 above)
Comment (aqnuep) [reply modules/bullet/btRayShape.cpp]: Sure, can you explain?

**Comment by AndreaCatania** [comment]
[RayShapeBug.zip](https://github.com/godotengine/godot/files/2879276/RayShapeBug.zip)

This is a modified version of your project, I've added a rigidbody with a ray.
The two right spheres must stay in this slope when the slide on slope is off and slide down when it is on.

By doing everything I told you in the comments the kinematic body should not vibrate anymore. Please let me know

File: modules/bullet/godot_ray_world_algorithm.cpp (hunk 4 above)
Comment (aqnuep) [reply modules/bullet/godot_ray_world_algorithm.cpp]: What would be the rationale for that?

File: modules/bullet/space_bullet.cpp (hunk 3 above)
Comment (aqnuep) [reply modules/bullet/space_bullet.cpp]: Is that because `RFP_convex_convex_test` always uses GJK?

File: modules/bullet/btRayShape.cpp (hunk 5 above)
Comment (AndreaCatania) [reply modules/bullet/btRayShape.cpp]: Basically in the processCollision function we have this: 

```
if (depth >= -ray_shape->getMargin())
depth = 0;
```
This mean that the margin will be subtracted by the ray size, so if our ray is 1m and the margin is 0.5m the object will penetrate of 0.5 that make the ray half longer.
Instead I'm expecting that the ray stay around 1 and 1.5 so is necessary to tell to the process function that my ray is 1.5 long and allow a penetration of 0.5 (the margin)

Comment (aqnuep) [reply modules/bullet/btRayShape.cpp]: Yeah, just realized now, testing some of the changes. Sure, if your margin is large this allows convergence. Makes sense.

**Comment by aqnuep** [comment]
With your proposed changes there's still a problem that the rigid body stops higher than the kinematic one, even though they have the same margin.

**Comment by AndreaCatania** [comment]
Yes the problem is on the move_and_slide function that allow this penetration.

Can I test it again?

**Comment by aqnuep** [comment]
Yeah, the move_and_slide function...

That works so terribly on Bullet (consuming potentially a second to depenetrate due to some seemingly arbitrary looping) that I ended up stop using kinematic bodies all together.

Honestly, I can keep updating this pull request but if you're only experimenting around which values lead to acceptable behavior then please do it yourself, as, with all due respect, I can't sit around changing values back and forth until everything happens to work.

File: modules/bullet/btRayShape.cpp [hunk 6]
```diff
@@ -97,8 +97,8 @@ void btRayShape::getPreferredPenetrationDirection(int index, btVector3 &penetrat
...
```
Comment (AndreaCatania) [inline modules/bullet/btRayShape.cpp]: Please don't forget to revert this one.

I need that you put this:
`m_cacheScaledLength = m_length * m_localScaling[2] + m_collisionMargin;`

File: modules/bullet/btRayShape.cpp [hunk 7]
```diff
@@ -79,7 +79,7 @@ void btRayShape::batchedUnitVectorGetSupportingVertexWithoutMargin(const btVecto
 void btRayShape::getAabb(const btTransform &t, btVector3 &aabbMin, btVector3 &aabbMax) const {
 #define MARGIN_BROADPHASE 0.1
 	btVector3 localAabbMin(0, 0, 0);
-	btVector3 localAabbMax(m_shapeAxis * m_length);
+	btVector3 localAabbMax(m_shapeAxis * (m_cacheScaledLength + m_collisionMargin));
```
Comment (AndreaCatania) [inline modules/bullet/btRayShape.cpp]: you can remove this `+ m_collisionMargin` because the scaled length already has it

**Review by AndreaCatania — CHANGES_REQUESTED** [review]
You forget to change a thing

File: modules/bullet/btRayShape.cpp (hunk 6 above)
Comment (aqnuep) [reply modules/bullet/btRayShape.cpp]: If you look at the code more carefully, I moved things a bit around to not have to apply the collision margin in`m_cacheScaledLength`, as that was incorrect.

Why? Because `localGetSupportingVertexWithoutMargin()` would otherwise return the supporting vertex *with* margin and `localGetSupportingVertex()` would return the supporting vertex with the margin applied *twice*.

So AFAICT the margin is applied in all the right places, except maybe `getScaledLength()` which now does not contain the margin. Should it? If yes, why?

Comment (AndreaCatania) [reply modules/bullet/btRayShape.cpp]: You true

**Review by AndreaCatania — APPROVED** [review]

**Comment by AndreaCatania** [comment]
@akien-mga You can merge this

**Comment by akien-mga** [comment]
Thanks!

**Comment by aqnuep** [comment]
I'm sorry to burst the bubble, but the jittering is back on after the changes suggested, which I just observed with my project today.

Note that it's happening in case of rigid bodies this time (sigh).

Apparently one of the changes compared to the original PR is causing this. Will follow up with another PR...

**Comment by aqnuep** [comment]
Created PR #26090 to solve the issue.
