### PR TITLE
Optimize AnimationTree, Improve internals & Editor & `Node::process_thread_group` safety

### LINKED ISSUE #112053: Errors when switching animations while in `Capture` blend mode in `BlendSpace1D` and `BlendSpace2D`
### Tested versions

Reproducible in:
v4.5.1.stable.mono.official [f62fdbde1]
v4.6.dev.mono.custom_build [f50d7fa]

### System information

Godot v4.6.dev.mono (f50d7fa) - Windows 11 (build 22621) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 32.0.15.8129) - Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz (20 threads) - 127.6 GiB memory

### Issue description

`Capture` blend mode used in `BlendSpace1D` and `BlendSpace2D` produces errors when animation is switched for the first time:
```
E 0:00:03:470   AnimationNode::set_parameter: Condition "!process_state->tree->property_parent_map.has(node_state.base_path)" is true.
  <C++ Source>  scene\animation\animation_tree.cpp:91 @ AnimationNode::set_parameter()
```

### Steps to reproduce

You can use the attached MRP. This project implements animations for four directions. You can switch between animations using arrow keys. If `Capture` blend mode is used, errors occur when switching animations.

[2025-10-21.22-58-49.mp4](https://private-user-images.githubusercontent.com/9061796/503867489-55611ef2-b43d-4139-9619-fa2d78c00969.mp4?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE0OTA2MzIsIm5iZiI6MTc2MTQ5MDMzMiwicGF0aCI6Ii85MDYxNzk2LzUwMzg2NzQ4OS01NTYxMWVmMi1iNDNkLTQxMzktOTYxOS1mYTJkNzhjMDA5NjkubXA0P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMjZUMTQ1MjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVhNTNlMzJlMzI3ZThhNDgwMjhlMWFkNjlmZThmM2MzNDdjZTlmZjNmMTFhYTkxNmE3MWFjYTI3NDYxZWM4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v_914XbUxp14lp1eNnVJDPy0d1BwC84EibuFygcS710)

### Minimal reproduction project (MRP)

[BlendSpace2D.zip](https://github.com/user-attachments/files/23031731/BlendSpace2d.zip)

### PR DESCRIPTION
**Pull request by Ryan-000**
Supersedes https://github.com/godotengine/godot/pull/113444

Related https://github.com/godotengine/godot/pull/116394 https://github.com/godotengine/godot/pull/112308 https://github.com/godotengine/godot/pull/110474

# Benchmark

Compiled with `scons production=yes debug_symbols=yes target=editor` 
Ran with `./engine_binary --headless --print-fps --path /path/to/project res://path_to_world.tscn`
Project: [optimize.zip](https://github.com/user-attachments/files/23435265/optimize.zip)

---

Scene: `res://World.tscn`

Before: (a1eaac8171a53e5a74cd511bc144bd28afc4c7ff)

FPS: high 227, low 223, median 224.5
MSPF: high 4.48, low 4.40, median 4.45

After: (ac1c551294f64f60dda5b2b7fc95335666189e2c)

FPS: high 342, low 333, median 338
MSPF: high 3.00, low 2.92, median 2.95

median FPS change: +113.5 (+50.56%)
median MSPF change: -1.50 (-33.71%)

---

Scene: `res://World_StressTest.tscn`

Before: (a1eaac8171a53e5a74cd511bc144bd28afc4c7ff)

FPS: high 110, low 103, median 105
MSPF: high 9.70, low 9.09, median 9.52

After: (ac1c551294f64f60dda5b2b7fc95335666189e2c)

FPS: high 127, low 118, median 126
MSPF: high 8.47, low 7.87, median 7.93

median FPS change: +21 (+20.00%)
median MSPF change: -1.59 (-16.70%)

_Bugsquad edited:_
- Closes https://github.com/godotengine/godot/issues/112053
- Closes https://github.com/godotengine/godot/pull/112050

### CODE REVIEW

File: scene/animation/animation_node_extension.cpp [hunk 1]
```diff
@@ -29,10 +29,9 @@
 /**************************************************************************/
 
 #include "animation_node_extension.h"
-
 #include "core/object/class_db.h"
```
Comment (AThousandShips) [inline scene/animation/animation_node_extension.cpp:33]:
```suggestion

#include "core/object/class_db.h"
```
Invalid please restore

File: scene/animation/animation_blend_tree.h [hunk 2]
```diff
@@ -439,18 +444,19 @@ class AnimationNodeBlendTree : public AnimationRootNode {
 		//no need to check for cycles due to tree topology
 	};
 
-	void add_node(const StringName &p_name, Ref<AnimationNode> p_node, const Vector2 &p_position = Vector2());
+	void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```
Comment (AThousandShips) [inline scene/animation/animation_blend_tree.h]:
```suggestion
	virtual void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```

File: scene/animation/animation_blend_tree.h [hunk 3]
```diff
@@ -54,25 +55,27 @@ class AnimationNodeAnimation : public AnimationRootNode {
 		PLAY_MODE_BACKWARD
 	};
 
-	void get_parameter_list(List<PropertyInfo> *r_list) const override;
-	virtual Variant get_parameter_default_value(const StringName &p_parameter) const override;
+	void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```
Comment (AThousandShips) [inline scene/animation/animation_blend_tree.h]:
```suggestion
	virtual void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```

File: scene/animation/animation_blend_space_2d.h [hunk 4]
```diff
@@ -93,10 +93,12 @@ class AnimationNodeBlendSpace2D : public AnimationRootNode {
 	virtual void _animation_node_removed(const ObjectID &p_oid, const StringName &p_node) override;
 
 public:
-	virtual void get_parameter_list(List<PropertyInfo> *r_list) const override;
+	void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```
Comment (AThousandShips) [inline scene/animation/animation_blend_space_2d.h]:
```suggestion
	virtual void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```

File: scene/animation/animation_blend_space_1d.h [hunk 5]
```diff
@@ -80,10 +80,12 @@ class AnimationNodeBlendSpace1D : public AnimationRootNode {
 	virtual void _animation_node_removed(const ObjectID &p_oid, const StringName &p_node) override;
 
 public:
-	virtual void get_parameter_list(List<PropertyInfo> *r_list) const override;
+	void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```
Comment (AThousandShips) [inline scene/animation/animation_blend_space_1d.h]:
```suggestion
	virtual void validate_node(const AnimationTree *p_tree, const StringName &p_path) const override;
```

**Comment by Ryan-000** [comment]
> This looks very impressive. Is it something I could cherrypick into 4.6.1 to solve some animation performance problems I have been having?


The PR is based off this commit a1eaac8171a53e5a74cd511bc144bd28afc4c7ff, so I think you would need a 4.7 build to get it to work. 

If you get a chance to test it there, it would be helpful if you could let us know whether you run into any issues.

**Comment by Mike-Litton** [comment]
> > This looks very impressive. Is it something I could cherrypick into 4.6.1 to solve some animation performance problems I have been having?
> 
> The PR is based off this commit [a1eaac8](https://github.com/godotengine/godot/commit/a1eaac8171a53e5a74cd511bc144bd28afc4c7ff), so I think you would need a 4.7 build to get it to work.
> 
> If you get a chance to test it there, it would be helpful if you could let us know whether you run into any issues.

Which are the commits I should get so that it is applicable to 4.6? I want this into my production game that releases soon.

File: scene/gui/graph_edit.h [hunk 6]
```diff
@@ -526,6 +526,7 @@ class GraphEdit : public Control {
 	bool is_connection_lines_antialiased() const;
 
 	HBoxContainer *get_menu_hbox();
+	void pan_to(const Vector2 &p_scroll_vec);
```
Comment (TokageItLab) [inline scene/gui/graph_edit.h]: I think this `pan_to` modification should be separated as follow up PR.

**Review by TokageItLab — APPROVED** [review]
Although there are many lines of changes, most of them are actually changes to arguments. Since consensus on these changes was already reached in https://github.com/godotengine/godot/pull/112308#pullrequestreview-3519746932 before this PR was split off, this should not be a problem.

I encountered an issue where results were broken when filters were complex (for example, this [MRP](https://github.com/user-attachments/files/25992782/nested_tree.zip) state shouldn't be processed but it is not so), but since this behavior is unchanged from before, I consider that it is no problem as an optimization PR. See also https://github.com/godotengine/godot/issues/89726.

BTW, regarding filtering, there was already a proposal to turn it into a resource like https://github.com/godotengine/godot/pull/76788, so I believe that not only will fixes for complex cases be needed, but a large-scale rework will also be necessary at some point.

I also found a bug where the read-only state in BlendTreeEditor is broken, but this PR is unrelated to that as well.

I recommend merging this PR at early stage of dev so that many people can test them to ensure there are no issues.

**Comment by akien-mga** [comment]
Thanks!
