### PR TITLE
Autocompletion: Improve autocompletion for indices

### LINKED ISSUE #76955: Autocompletion in array indices in 4.x is worse than in 3.x
### Godot version

4.0.2.stable

### System information

windows10，gtx1050ti

### Issue description

The bracket code prompt is not as good as it used to be.

### Steps to reproduce

It was OK in 3.5.1, but not after 4.0.

### Minimal reproduction project

none

### LINKED ISSUE #83074: Autocomplete in Array and Dictionary Index Operator does not work correctly
### Godot version

4.2.dev6

### System information

Windows 11

### Issue description

When using autocomplete to index an array or dictionary it does not list variable names for autocomplete, instead it lists the available methods as if I had typed a `.`
image

### Steps to reproduce

1. Create a variable containing an index: `var index = 0`
2. Create an array or a dictionary, `var test = [1,2,3]`
3. Attempt to use autocomplete to index the array using the index variable. `test[in]`
4. Note that the autocomplete results have the same methods as putting a `.` instead of providing relevant autocomplete variables.
image
image

### Minimal reproduction project

N/A

### LINKED ISSUE #93062: Dictionary suggests its methods in `[]` autocompletion
### Tested versions

4.3 beta1
I don't remember it happening before.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

image
The `[]` operator can be used on Object to access its properties and methods (as Callables), and apparently Dictionary is treated the same way.

### Steps to reproduce

1.
```GDScript
var d: Dictionary
d["
```
2. Put caret after `"` and press Ctrl+Space

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #76955
Fixes #83074
Fixes #93062

Todo:
- ~include dictionary keys for const dictionaries in the auto completion (see https://github.com/godotengine/godot/issues/83074#issuecomment-1786989398)~ Done

### CODE REVIEW

**Comment by dalexeev** [comment]
@HolonProduction The 4.2 release is coming very soon, so I'm postponing this and your other autocomplete PRs to 4.3. At the moment we want to focus on critical bugs. Thanks for your patience!

**Comment by akien-mga** [comment]
Will need another rebase.

**Comment by HolonProduction** [comment]
Rebased again and also did some changes to the behavior:

- When using `[]` on an identifier whose type is unknown, identifiers from the current context are suggested. I made this change, since I think array lookups are the most common use case, which should also work well without static typing.
- When using `[]` on an not builtin type, the properties of this object are now quoted. Otherwise auto-completion would complete invalid code.

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -3178,11 +3178,36 @@ ::Error GDScriptLanguage::complete_code(const String &p_code, const String &p_pa
 		case GDScriptParser::COMPLETION_SUBSCRIPT: {
 			const GDScriptParser::SubscriptNode *subscript = static_cast<const GDScriptParser::SubscriptNode *>(completion_context.node);
 			GDScriptCompletionIdentifier base;
-			if (!_guess_expression_type(completion_context, subscript->base, base)) {
-				break;
-			}
+			const bool res = _guess_expression_type(completion_context, subscript->base, base);
+
+			// If the type is not known, we assume it is BUILTIN, since indices on arrays the most common use case.
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_editor.cpp:3183]:
```suggestion
			// If the type is not known, we assume it is BUILTIN, since indices on arrays is the most common use case.
```

**Review by Mickeon — COMMENTED** [review]
Code looks great to me, needs a few moments of testing though. Especially for the "Dictionary key quoting" part.

... I haven no idea why that Linux build check did not pass.

**Review by Mickeon — APPROVED** [review]
Tested. This actually works as intended, even the Dictionary part, which is interesting.
Suggestions for keys appear as normal and are quoted.
image

A happy accident! When typing two quotes, due of the way the suggestions work **only** keys are shown, which is super convenient.
image

-------------------------

There are actually issues with Dictionary suggestions that is **not** related to this PR.
For example, because the suggestions are sorted alphabetically, the Dictionary's keys appear shuffled all over the place along with the Dictionary's methods.
image
I just thought this may be worth mentioning for the foreseeable future.

**Comment by HolonProduction** [comment]
Also dictionary keys with spaces in it (e.g. `"Little guy"`) can't be accessed using `.`. Filtering such options out might make sense.

**Comment by Mickeon** [comment]
Yeah but you can keep that in mind for another time.

**Comment by akien-mga** [comment]
I checked the linked issues and tested this briefly, but I'm not convinced about what the desired completion should be.

I understand users want to be able to use local or member variables as indices, and this PR adds them back. But the rest still doesn't seem to make much sense to me:
image

IMO we should aim to limit the completion suggestions to only the things which actually make sense. Functions shouldn't be shown when using the `[]` operator. And random class properties like `owner` or class names like `Object` or whatever `or` is seem hardly relevant for array indexing.

Overall I find it hard to review autocompletion changes as it seems like what should be a _good_ output is not that well defined.

**Comment by HolonProduction** [comment]
The autocompletion uses `_find_identifiers` which adds all this stuff. This is in line with how function parameters work.

We could replace it with `_find_identifiers_in_class` but we would also need `_find_identifiers_in_suite` and we'd need to add things like `true` or `false` again, so basically we would need to reimplement large parts of `_find_identifiers`. If we did that for all places it would hurt maintainability quite a bit.

Furthermore I don't think it is that easy to say which identifiers are needed in which place. 

> Functions shouldn't be shown when using the `[]` operator.

Why not? Take the following example:
```
const enemy_scenes = {
    EnemyType.FIRE: preload("..."),
    EnemyType.WATER: preload("..."),
    EnemyType.PLANT: preload("..."),
}

func summon_enemy():
    var enemy = enemy_scenes[pick_fair_enemy()].instantiate()
```

`pick_fair_enemy` picks an enemy type at random, but also does rejection sampling to prevent unfair situations.

What I'm trying to say with this, is that there are a lot of things that someone could want to put in there. Instead of limiting suggestions on a case by case basis for every context, which could miss use cases, we suggest a lot of stuff and rely on the sorting. It ensures, that users still get suggested the stuff they want. E.g all the native types would never end up above a variable from the current script so they won't be a problem for users that don't want them, while they are still there in the rare case that they are needed.

At least that's how I understand the design philosophy of the autocompletion we currently have.

**Comment by hsandt** [comment]
Cool, does it also fix class name / enum access?

Ex when trying to access an enum stored in a pure class:

```gd
# HeroEnums.gd
class_name HeroEnums

enum HeroType {
	SPEED,
	FLY,
	POWER,
}

# example.gd
func _ready():
	var hero_levels: Array[int]
	print(hero_levels[HeroEnums.HeroType.FLY])  # typing HeroEn... will NOT autocomplete, but HeroEnums.HeroTy... will autocomplete

	# another issue
	var hero_types: Array[HeroEnums.HeroType]  # reverse: typing HeroEn... will autocomplete, but HeroEnums.HeroTy... will not
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by HolonProduction** [comment]
Turns out I didn't fully test after the rebase, the dictionary key part does not work due to #94082 right now. I will fix it in a followup and add some test cases as well.
