### PR TITLE
Flip cull mode when rendering flipped Light2D and LightOccluder2D

### LINKED ISSUE #32993: Tile set tile rotation doesn't affect LightOccluder2D
**Godot version:** 3.1.1

**OS/device including version:** Windows 10, Manjaro Linux 18

**Issue description:** Rotation of tiles in tileset has no effect on LightOccluder2D, resulting in incorrect shadowing of parented sprite in top-down environment.

**Steps to reproduce:**
1. Create the new scene
2. Add sprite and then add LightOccluder2D, StaticBody2D and CollisionShape2D (for StaticBody)
3. Set up occluder and collision shape. Occluder should have ClockWise or CounterClockWise Cull Mode, Closed set to On. You can try setting Closed to Off and issue still will be relevant, though you will also get a hole in occlusion or additional setup will be required
4. Convert scene to tileset
5. Create game level scene, add tiles to the scene, optionally add CanvasModulate to darken the scene
6. Add light source focused on assets
7. Place assets in different directions using tile rotate, only one will have correct shadowing.

**Screenshot:**
2019-10-22 20_12_51-Godot Engine - Heist_Meisters - Test_Level tscn

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #32993.

Discussion on IRC about the proper fix: [2019-12-10 22:33:57](http://godot.eska.me/irc-logs/devel/2019-12-10.log).
Not sure about the performance implications, but I tried to keep them to a minimum.

### CODE REVIEW

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 1]
```diff
@@ -1898,9 +1898,19 @@ void RasterizerCanvasGLES2::canvas_light_shadow_buffer_update(RID p_buffer, cons
 			}
 
 			state.canvas_shadow_shader.set_uniform(CanvasShadowShaderGLES2::WORLD_MATRIX, instance->xform_cache);
-			if (cull != instance->cull_cache) {
 
-				cull = instance->cull_cache;
+			VS::CanvasOccluderPolygonCullMode transformed_cull_cache = instance->cull_cache;
+
+			if (transformed_cull_cache != VS::CANVAS_OCCLUDER_POLYGON_CULL_DISABLED && p_light_xform.basis_determinant() * instance->xform_cache.basis_determinant() < 0) {
```
Comment (reduz) [inline drivers/gles2/rasterizer_canvas_gles2.cpp]: Seems good, I would add parethesis () on the right of && for a bit more of clarity

**Review by reduz — DISMISSED** [review]

File: drivers/gles2/rasterizer_canvas_gles2.cpp (hunk 1 above)
Comment (bojidar-bg) [reply drivers/gles2/rasterizer_canvas_gles2.cpp]: Done, threw in a newline as well for a good measure.

**Comment by akien-mga** [comment]
Thanks!
