### PR TITLE
Fix custom tracks causing issues on reimport

### LINKED ISSUE #39959: Duplicate tracks on animation reimport - GLTF
**Godot version:** 3.2.2

**OS/device including version:** Windows

**Issue description:** On presssing reimportfor a .glb file, my animation tracks that I created in blender (not custom ones that I created in godot, those are fine) for every single animation that I have, get duplicted. This didnt happen in 3.2.1, because I tested it, and had to revert to that version because of this issue. This happens for both .tres as well as .anim.

Note: turning off 'keep custom tracks' will 'fix' this bug, however I need custom tracks for my game, hence this is not a valid solution for myself

**Steps to reproduce:** Please refer to this video: https://youtu.be/rvnMbUBGHAI (notice how the tracks for bone1-3 got duplicated for every reimport I did). I also attached an image of the errors that come with the bug

**Minimal reproduction project:** You can test it out using this project: [AnimationImportingBugTest.zip](https://github.com/godotengine/godot/files/4847293/AnimationImportingBugTest.zip)

Capture

### PR DESCRIPTION
**Pull request by lordkettune**
Upon importing a scene with custom tracks enabled, the importer was treating _all_ of the tracks as custom tracks, meaning that when reimported it would overwrite the tracks with the previously imported ones. I just deleted the bit of code that did that.

Also fixed an issue with copy_track in which it would try to copy a value track's update mode even if it wasn't a value track, which led to it printing a ton of error messages each time you reimported a scene.

(This is my first time contributing here by the way, let me know if I'm doing anything wrong)

*Bugsquad edit:* Fixes #39959.

### CODE REVIEW

**Comment by aaronfranke** [comment]
See also #39657, cc @Sl3dge78 @reduz.

**Comment by lordkettune** [comment]
That PR must've been what broke it. I think they were calling `anim->set_imported_track(i, false)` to fix the warning on the animation editor displaying when it shouldn't be, which is also annoying, but it broke the importer as a result. It should be doing the exact opposite if anything, which it looks like it was before that PR.

**Comment by Sl3dge78** [comment]
Hey thank you for cc ing me and sorry if my PR cause any issues...


Just to understand your issue, you imported a scene with animation to external files, modified existing tracks and/or added new ones, and finally saved said animation. Then when pressing reimport what happened?

Here's what I just tested on my side and what happens in both cases :
- Import a .dae file with animation and store the animation outside the dae
- Edit an animation (by changing tracks or adding new ones) and save it
- Reimport the .dae with the Keep Custom Tracks enabled.

old behaviour (before my pr):
- Edited tracks are reverted
- Created tracks are kept

new behaviour (with my pr):
- It duplicates all tracks (that's a big issue!)

This is where the merge happens : 
https://github.com/godotengine/godot/blob/73262c0f609d2b865ae1af721c167600d120342a/editor/import/resource_importer_scene.cpp#L959-L971

The snippet above adds any track that isn't marked as imported from the old file to the new file, so that's why.

Maybe the operation shouldn't be a copy but a replace? If the track exists, replace it if its not imported.
If the user wants to reverts the changes he has made he can untick "keep custom tracks"

Can you confirm that this is the behaviour you were having?

**Comment by lordkettune** [comment]
Yes, that's the issue I was having; it doesn't duplicate the tracks though, it overwrites the new files with the old ones.

I don't think it should replace the tracks either, if it did you would have you lose your custom tracks every time you want to change your animations, which defeats the purpose.

I believe that calling `anim->set_imported_track(i, true)` on all of the tracks that came from the source file was the correct solution. I'm going to add that back in once I'm at home and I can update this PR.

**Comment by lordkettune** [comment]
Fixes #39959

**Comment by Sl3dge78** [comment]
Thank you for the change and sorry again for the trouble.
Edited tracks will be reverted on reimport, but to fix that we'd need to be able to compare tracks maybe via their paths. That's probably too big of an edge case.

**Comment by lordkettune** [comment]
Don't be sorry, it's no trouble!
I think that's the expected behavior - edited tracks _should_ be reverted on reimport, the user should be able to edit their animations, then reimport the file, and it should update the imported tracks with the changes they made but not delete the custom tracks they added.

**Comment by CowKeyMan** [comment]
> Don't be sorry, it's no trouble!
> I think that's the expected behavior - edited tracks _should_ be reverted on reimport, the user should be able to edit their animations, then reimport the file, and it should update the imported tracks with the changes they made but not delete the custom tracks they added.

As someone doing a lot of reiterating and reimporting of 3D models with animations, I agree with this 100%. Thank you to the both of you. Hope this gets merged soon ^-^

I'm still a bit new here, should I close this issue: #39959 ? Or should I wait until it gets merged into master?

**Comment by lordkettune** [comment]
I tweaked this a little and it should be ready now.

@CowKeyMan I think wait until it gets merged into master.

I'm also wondering if there's a good way to hide the imported tracks warning when keep_custom_tracks is enabled. It's a little misleading when it displays and the user already has that enabled. Does anyone know if there's a way to check a resource's import settings through the editor?

If not the only way I can think of is storing that flag from the importer in each animation, but I don't think that's a very elegant way to handle it.

**Comment by CowKeyMan** [comment]
> I tweaked this a little and it should be ready now.
> 
> @CowKeyMan I think wait until it gets merged into master.
> 
> I'm also wondering if there's a good way to hide the imported tracks warning when keep_custom_tracks is enabled. It's a little misleading when it displays and the user already has that enabled. Does anyone know if there's a way to check a resource's import settings through the editor?
> 
> If not the only way I can think of is storing that flag from the importer in each animation, but I don't think that's a very elegant way to handle it.

There's also sometimes another weird bug that appears, where if you reimport while godot is open, you either need restart godot or else double click the .glb/.gltf file (havent tried it with others yet) and open 'new inherited scene' before the new glb/gltf file actually takes effect. During this state, if you try to create new custom animation tracks or edit previous one, the changes end up getting lost. I'll put a more detailed description of this in an issue soon, gonna check if it still happens in 3.2.2 after this merge. That said, thank you very much once again for the fix!

**Comment by lordkettune** [comment]
@CowKeyMan No problem. I'm hoping this can be backported, the issue is the same on 3.2.

File: editor/import/resource_importer_scene.cpp [hunk 1]
```diff
@@ -943,9 +943,9 @@ void ResourceImporterScene::_make_external_resources(Node *p_node, const String
 				ERR_CONTINUE(anim.is_null());
 
 				if (!p_animations.has(anim)) {
-					// We are making external files so they are modifiable
+					//tracks from source file should be set as imported, anything else is a custom track
```
Comment (akien-mga) [inline editor/import/resource_importer_scene.cpp:946]:
```suggestion
					// Tracks from source file should be set as imported, anything else is a custom track.
```

**Review by akien-mga — APPROVED** [review]

File: editor/import/resource_importer_scene.cpp [hunk 2]
```diff
@@ -943,9 +943,9 @@ void ResourceImporterScene::_make_external_resources(Node *p_node, const String
 				ERR_CONTINUE(anim.is_null());
 
 				if (!p_animations.has(anim)) {
-					// We are making external files so they are modifiable
```
Comment (aaronfranke) [inline editor/import/resource_importer_scene.cpp:946]: Could you also add periods while you're at it?

**Review by aaronfranke — COMMENTED** [review]
Since these changes are small, this could probably be squashed down to 1 commit.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged PR :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.
