### PR TITLE
Fix prompt for empty project files when loaded

### LINKED ISSUE #25541: Warning "... project ... was generated by older engine" even if project.godot is empty
**Godot version:**
3.1 beta 3

**OS/device including version:**
Windows 10

**Issue description:**
When I create an empty project.godot and try to open it via project manager, then popup about converting project to new version is shown.

**Steps to reproduce:**
Create empty project.godot and try to import it

### PR DESCRIPTION
**Pull request by twaritwaikar**
Fixes #25541

### CODE REVIEW

**Comment by qarmin** [comment]
I think it would be a better solution not to display any pop-ups because the empty project.godot is often created with some reasons and does not cause any irreversible changes.

**Comment by IronicallySerious** [comment]
@qarmin Yes this is another point we can consider. But I was trying to cater to people who may expect something to be in the project file but don't find anything to their surprise

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -1471,6 +1471,13 @@ void ProjectManager::_open_selected_projects_ask() {
 	}
 
 	int config_version = (int)cf->get_value("", "config_version", 0);
+
+	// Check if the project file was empty
+	if (config_version == 0) {
+		ask_update_settings->set_text(vformat(TTR("The following project settings file is empty. Do you want to proceed with it?")));
```
Comment (akien-mga) [inline editor/project_manager.cpp]: That's not true though, no `config_version` doesn't necessarily mean that the project is empty. You can have a fully functional `project.godot` file with no `config_version` defined.

In such case it *might* be a 3.0.x project, or a later version. I guess it makes sense to show a specific message in such situation, but it should be something like:
```
ask_update_settings->set_text(vformat(TTR("The following project settings file does not include a `config_version` property:\n\n%s\n\nIf you proceed with opening it, it will be converted to Godot's current configuration file format.\nWarning: You will not be able to open the project with previous versions of the engine anymore."), conf));
```

Comment (IronicallySerious) [reply editor/project_manager.cpp]: This makes sense 😅 . The property could just not be there with everything else.

Also, should the prompt reveal the `config_version` identifier to the user who normally won't have anything to do with the contents of `project.godot` most of the time? After your review, I was thinking of something like:
```
The following project settings file does not mention the version of Godot through which it was created.\n\n%s\n\nIf you proceed with opening it, it will be converted to Godot's current configuration file format.\nWarning: You will not be able to open the project with previous versions of the engine anymore.
```

Comment (IronicallySerious) [reply editor/project_manager.cpp]: I will look out for how I can detect the file being empty in the meanwhile

Comment (groud) [reply editor/project_manager.cpp]: > I will look out for how I can detect the file being empty in the meanwhile

I think there is no need to make specific distinction for this use case. It is going to need a bunch of lines of code for little gain IMHO.

Comment (IronicallySerious) [reply editor/project_manager.cpp]: @groud Actually in my understanding this is the only way to fix #25541 . Without checking the file content size, it might be cumbersome to detect the existence of all possible Godot project settings properties in the project settings file.

Comment (groud) [reply editor/project_manager.cpp]: @IronicallySerious, in #25541, the problem is that it displays a wrong warning, not that it displays a warning. We simply need to change the warning when there is no `config_version` to notify that to the user. Getting more into the file details is not needed.

Comment (IronicallySerious) [reply editor/project_manager.cpp]: Okay, so we just need to handle this specific case of not having `config_version`. I will do this at once. Do we require a prompt for opening empty project files though?

Comment (groud) [reply editor/project_manager.cpp]: > Do we require a prompt for opening empty project files though?

it is not really needed in that case, so in that situation the popup might not be displayed, but it should not require a huge bunch of lines of code to check the file's content. 
If you can check this in one line or two, it's ok to not display the popup in that situation, else it is better to keep the "config_file not found" message for both situation.

**Comment by IronicallySerious** [comment]
@akien-mga I have made the changes.

**Comment by akien-mga** [comment]
Thanks!
