### PR TITLE
Fix unnecessarily quantizing current color in color picker

### LINKED ISSUE #85743: Color changes when opening color picker
### Godot version

v4.3.dev.custom_build [d76c1d0e5]

### System information

Linux

### Issue description

When opening the color picker by clicking on a color property the color changes slightly.

### Steps to reproduce

* Click on a property with value `Color(.5, .5, .5) ` in the inspector
* Click away
* Open the color picker again
* See the color change to Color(0.502, 0.502, 0.502) in the "RAW" tab

### Minimal reproduction project

[ColorChangeBug.zip](https://github.com/godotengine/godot/files/13545089/ColorChangeBug.zip)

### PR DESCRIPTION
**Pull request by bs-mwoerner**
Fixes #85743.

The color picker would update the current color to match the HTML string whenever the parsed value did not match the current color. Since Godot Colors have a 16 bit resolution, this would quantize the current value to the nearest HTML color even when no change was made. And since this happened whenever the HTML input lost focus, just opening and closing the color picker was enough to change a 16-bit value to the nearest 8-bit value.

With this PR, the HTML input only updates the current color when the HTML representation is different from the current color's HTML representation (and not whenever the HTML representation represents a different color than the current one).

### CODE REVIEW

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by KoBeWi** [comment]
#83786 seems to be also addressing this problem, in a simpler way.
CC @aXu-AP

**Comment by bs-mwoerner** [comment]
> #83786 seems to be also addressing this problem, in a simpler way. CC @aXu-AP

Ah, yes, I missed that PR. `to_abgr32()` is probably the better way, although I think that other solution still requires a slight modification to actually work. I'll add my comments there.

**Comment by aXu-AP** [comment]
Good work catching the error in my pr. I think this pr could be better fit to be modified, and I don't currently have time to work on it, so feel free to borrow from my solution.

**Comment by bs-mwoerner** [comment]
> Good work catching the error in my pr. I think this pr could be better fit to be modified, and I don't currently have time to work on it, so feel free to borrow from my solution.

I will, thanks! And I only caught that error because I spent quite some time pulling my hair out when I was working on my own PR wondering how on Earth it still managed to get the wrong color value through to the caller despite me having breakpoints everywhere. 😅

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -556,16 +556,16 @@ void ColorPicker::_html_submitted(const String &p_html) {
...
-		color.a = previous_color.a;
+		new_color.a = color.a;
 	}
 
-	if (color == previous_color) {
+	if (new_color.to_argb32() == color.to_argb32()) {
 		return;
 	}
+	color = new_color;
 	if (!is_inside_tree()) {
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:569]:
```suggestion
	color = new_color;

	if (!is_inside_tree()) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
