### PR TITLE
Make `script_class_get_icon_path()` return any value when `r_valid` is passed.

### LINKED ISSUE #105194: @icon not inheriting on Resource type
### Tested versions

- Reproducible: v4.4.beta3, v4.4.rc2, v4.4.rc3, **v4.4.1**
- Non-reproducible: v4.4.beta2, v4.4.beta4, v4.4.rc1

### System information

Godot v4.4.stable - Windows 11 (build 26100) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3734) - 12th Gen Intel(R) Core(TM) i5-12400 (12 threads)

### Issue description

A similar issue to https://github.com/godotengine/godot/issues/102565, except this is for Resource type.
Basically, if you have a resource extended from a custom class with a custom icon, the extended resource does not display the custom icon in the File System.

Expected:
Image

Reality:
Image

_Note that if you try to "Add Resource" in the File System and look for the custom resource class in the dialog, the icons there display perfectly well._
Image

### Steps to reproduce

1. Create a script with a custom class & icon.
2. Create another script and extend from the class made above.
3. Create resources each from both of the scripts made above.
4. Note that the resource with extended class does not display the custom icon in the File System.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by PhairZ**
Closes #105194 by making it so when passing something to `r_value` in `script_class_get_icon_path()`, the function returns `E->value`, even if `value` is empty.
This is needed due to [this (IMO useless optimization)](https://github.com/godotengine/godot/blob/ce94b26de74a0a0f2463c5dc61b9b683a1e3676b/editor/editor_data.cpp#L1125-L1135). Removing these 11 lines also fixes the problem, and to which I just think this overcomplication isn't worth saving a couple of instruction. But maybe I'm just missing something.

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_data.cpp [hunk 1]
```diff
@@ -1024,10 +1024,12 @@ String EditorData::script_class_get_icon_path(const String &p_class, bool *r_val
 		}
 		HashMap<StringName, String>::ConstIterator E = _script_class_icon_paths.find(current);
 		if ((bool)E) {
-			if (r_valid && !E->value.is_empty()) {
-				*r_valid = true;
+			if (r_valid) {
+				*r_valid = !E->value.is_empty();
+				return E->value;
+			} else if (!E->value.is_empty()) {
```
Comment (akien-mga) [inline editor/editor_data.cpp:1030]: This new condition changes the behavior, as now if `!r_valid && E->value.is_empty()`, it won't return an empty value anymore. Is that intentional?

Otherwise if you just want to make `r_valid` always be handled (as it should indeed), this can just be:
```cpp
if (r_valid) {
    *r_valid = !E->value.is_empty();
}
return E->value;
```

Comment (PhairZ) [reply editor/editor_data.cpp:1030]: Yes, this is intentional because you want to check the base class for an icon if `E->is_empty()` returns true

**Comment by Repiteo** [comment]
Thanks!
