### PR TITLE
Fix highlighted word style being overwritten by hover/pressed styles in find in files

### LINKED ISSUE #115497: `Search Results` dock, modern theme hides the text highlight when the mouse cursor hovers over the result
### Tested versions

v4.6.stable.official [89cea1439]

### System information

Godot v4.6.stable - Windows 11 (build 26100) - Single-window, 2 monitors - OpenGL ES 3/ANGLE (Compatibility) - ANGLE (Intel, Intel(R) HD Graphics 620 (0x00005916) Direct3D11 vs_5_0 ps_5_0, D3D11-31.0.101.2115) - Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz (4 threads) - 7.86 GiB memory

### Issue description

Classic theme:

Image

Modern theme:

Image

### Steps to reproduce

Search something using FindInFiles, hover results with mouse.

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #116013: TreeItem.set_custom_draw_callback draw stuff below selected box since 4.6
### Tested versions

- Reproductible in 4.6.0, 4.6.1-rc1, v4.7.dev.custom_build [56f3e2611] (latest commit at the time I am writting this issue)
- Not reproductible in 4.5.1

### System information

Godot v4.6.stable - Windows 11 (build 26200) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.9174) - 12th Gen Intel(R) Core(TM) i9-12900K (24 threads) - 63.78 GiB memory

### Issue description

When using the method [TreeItem.set_custom_draw_callback()](https://docs.godotengine.org/en/4.6/classes/class_treeitem.html#class-treeitem-method-set-custom-draw-callback) the drawn things are display below the "selection box" or the "hover bow" since version 4.6

Note that ingame the selected is a little bit transparent so we can see behind but not ingame.

It's maybe a side effect of #114572

Maybe we should draw using the RenderServer and the `content_ci` RID if we can access it somehow.

Current result :
Image

Expected result :
Image

### Steps to reproduce

Create a tree with the following attached script:

```gdscript
@tool
extends Tree

const ICON = preload("uid://bov1efxly4x0s") # Godot default project icon


func _ready() -> void:
	var root: TreeItem = create_item()

	for color: Color in [Color.RED, Color.GREEN, Color.BLUE]:
		var child: TreeItem = root.create_child()
		child.set_metadata(0, color)
		child.set_cell_mode(0, TreeItem.CELL_MODE_CUSTOM)
		child.set_custom_draw_callback(0, _custom_draw)

func _custom_draw(tree_item: TreeItem, rect: Rect2) -> void:
	var icon_color: Color = tree_item.get_metadata(0)
	draw_texture_rect(ICON, rect, true, icon_color)
```

### Minimal reproduction project (MRP)

[mrp_tree_draw_2026-02-07_18-22-59.zip](https://github.com/user-attachments/files/25153782/mrp_tree_draw_2026-02-07_18-22-59.zip)

### PR DESCRIPTION
**Pull request by jinyangcruise**
- Close #115497
- Close #116013

Fix highlighted word style being overwritten by hover/pressed styles in find in files.

image

v4.6.stable.official [89cea1439]:

https://github.com/user-attachments/assets/02e63c2c-e340-4fec-82b9-0582e8353a20

This PR:

https://github.com/user-attachments/assets/5a52953b-bafc-43a8-b412-a93cbaab9706

### CODE REVIEW

**Comment by arkology** [comment]
- Reported in https://github.com/godotengine/godot/issues/115497

Please add close keyword into OP.

File: editor/script/find_in_files.cpp [hunk 1]
```diff
@@ -1037,8 +1037,18 @@ void FindInFilesPanel::draw_result_text(Object *item_obj, Rect2 rect) {
...
+
+	Vector<Vector2> points;
+	points.resize(5);
+	points.write[0] = match_rect.position;
+	points.write[1] = match_rect.position + Vector2(match_rect.size.x, 0);
+	points.write[2] = match_rect.position + match_rect.size;
+	points.write[3] = match_rect.position + Vector2(0, match_rect.size.y);
+	points.write[4] = match_rect.position;
+	Vector<Color> colors = { get_theme_color(SNAME("accent_color"), EditorStringName(Editor)) * Color(1, 1, 1, 0.33) };
+	RenderingServer::get_singleton()->canvas_item_add_polyline(ci, points, colors, 2.0);
```
Comment (Zehir) [inline editor/script/find_in_files.cpp:920]: The RenderingServer reference was removed in #116454
You will need to add it back;

```C
#include "servers/rendering/rendering_server.h"
```

Except that I am using the feature in my test build of Godot and it's working correctly

**Review by Zehir — CHANGES_REQUESTED** [review]

File: editor/script/find_in_files.cpp (hunk 1 above)
Comment (jinyangcruise) [reply editor/script/find_in_files.cpp:920]: Maybe I need a rebase.

Comment (jinyangcruise) [reply editor/script/find_in_files.cpp:920]: Rebased.

**Review by Zehir — APPROVED** [review]

File: doc/classes/Tree.xml [hunk 2]
```diff
@@ -140,6 +140,13 @@
 				Returns the column's width in pixels.
 			</description>
 		</method>
+		<method name="get_custom_canvas_item" qualifiers="const">
+			<return type="RID" />
+			<description>
+				Returns the internal custom canvas item [RID] used by the [RenderingServer] for this node. Useful for custom drawing. See [method TreeItem.set_custom_draw_callback].
```
Comment (KoBeWi) [inline doc/classes/Tree.xml]:
```suggestion
				Returns the internal canvas item designated for custom drawing. See [method TreeItem.set_custom_draw_callback].
```
Or something like that. It's more precise IMO.

File: scene/gui/tree.cpp [hunk 3]
```diff
@@ -7172,6 +7176,8 @@ void Tree::_bind_methods() {
 
 	ClassDB::bind_method(D_METHOD("get_column_width", "column"), &Tree::get_column_width);
 
+	ClassDB::bind_method(D_METHOD("get_custom_canvas_item"), &Tree::get_custom_canvas_item);
```
Comment (KoBeWi) [inline scene/gui/tree.cpp]: Maybe something like this would be better (more clear).
```suggestion
	ClassDB::bind_method(D_METHOD("get_custom_drawing_canvas_item"), &Tree::get_custom_canvas_item);
```

**Review by kitbdev — APPROVED** [review]
Tested, fixes the issue.
Code looks good. Tree has multiple canvas items, so exposing a new one on top of them is probably the best way to allow custom drawing.
Probably closes https://github.com/godotengine/godot/issues/116013, it does require user to make code changes but now they can draw on top of selections again.

File: editor/script/find_in_files.cpp [hunk 4]
```diff
@@ -1040,8 +1041,18 @@ void FindInFilesPanel::draw_result_text(Object *item_obj, Rect2 rect) {
...
```
Comment (KoBeWi) [inline editor/script/find_in_files.cpp:920]: Why not `canvas_item_add_rect`?

Comment (kitbdev) [reply editor/script/find_in_files.cpp:920]: It doesn't have a non-filled outline mode.
Related, TextEdit has a its own `TextEdit::_draw_rect_unfilled` for this.

File: doc/classes/Tree.xml (hunk 2 above)
Comment (jinyangcruise) [reply doc/classes/Tree.xml]: Fixed.

File: scene/gui/tree.cpp (hunk 3 above)
Comment (jinyangcruise) [reply scene/gui/tree.cpp]: Fixed.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Needs rebase

**Comment by jinyangcruise** [comment]
Rebased.

**Comment by Repiteo** [comment]
Thanks!

**Comment by KoBeWi** [comment]
I tried applying it in the new template dialog and something is wrong.

https://github.com/user-attachments/assets/6e028039-2d53-4c4b-9d27-eeefbc14eb7a

For whatever reason the sub-items are darker (they draw the same color) and still covered by hover style?

**Comment by jinyangcruise** [comment]
- @KoBeWi Can you check whether #118733 fixes this? I wanted to check this but the install button is disabled.

**Comment by KoBeWi** [comment]
You can test it by changing `status` in `version.py` to `dev5`. Be sure to also use my PR: #118725
It does not fix the problem so far.

**Comment by jinyangcruise** [comment]
- #118733 fix the "darker" problem.

And the "covered by hover style" problem is caused by using `owning_tree->draw_rect`, which should be replaced by using `custom_ci`.
