### PR TITLE
Move mixing out of the AudioStreamPlayer* nodes

### LINKED ISSUE #21312: Audible click/pop when audio bus changes
When an Area2D is used to divert audio to a different bus than the currently active one, occasionally there's an audible click.

I haven't tried other ways of changing the bus (other than the automatic Area2D-based diversion), but I'm guessing this issue is likely present in all of them. I have tried both .ogg and .wav files for the audio, with the same results.

Here's my guess of what the issue might be:
Any unnaturally large change in the amplitude of audio samples over a single sample period is bound to cause clicks/pops due to the extreme frequencies that will be introduced during such sudden change. So I'm guessing Godot may currently be using a naive (easy to implement) approach that changes busses suddenly, over a single sample period. This would almost always produce a click unless the output of the two busses match both in time and in amplitude; however the audibility of the click would depend on the amplitude of the change, which we can consider to be random for all practical purposes (so it would sometimes be audible and sometimes not, and it would occasionally fit in with the audio being played and not be noticeable). Assuming my guess about Godot's current implementation is correct, an obvious solution would be to apply a low-pass filter during the transition, i.e. smooth out the transition. Even a simple smoothing operation over a few sample periods should work wonders (e.g. a simple solution that overlaps the new and old busses for a few samples, during which it fades out the old bus and fades in the new one).

To test/reproduce this issue, make sure the busses you use apply different effects, and make sure your audio is not silent. To almost guarantee a click most of the time, simply lower the volume of one of the busses significantly or use any effect that causes a time-delay.

Last test on Godot version 3.0.6, but the issue was there in the first 3.0 release as well.
OS: macOS 10.13.6

### LINKED ISSUE #25087: static is emitted when stopping an AudioStreamPlayer
**Godot version:** 
ce36351065c3a21d6582a7bce7d2c7cbdb5fe045

**OS/device including version:**
Windows 10, 64-bit. Default High Definition Microsoft Audio Driver (last update 9/7/2018)

**Issue description:**
When calling `stop()` or setting the `stream = null` with an AudioStreamPlayer, there is a small static  at the end

**Steps to reproduce:**
- Turn up your volume a bit
- Run the attached demo
- Listen for about 2-4 seconds to get the stream warmed up
- Click the Button to stop the stream
- You'll hear a small static.  

**Minimal reproduction project:**
[audiostreamstopbug.zip](https://github.com/godotengine/godot/files/2771876/audiostreamstopbug.zip)

i'm am not sure if this is only with .ogg files, will test some more. at the moment, i don't think i can replicate this with .wav

### PR DESCRIPTION
**Pull request by ellenhp**
Fixes #25087
Fixes #21312

Implements https://github.com/godotengine/godot-proposals/issues/2299

My focus here is parity with current `master`, not to add features, but it's still an enormous change. I can probably split off the individual commits into their own PRs if people would prefer that.

More detail is in the proposal above, but this basically moves all mixing into the audio server. Audio streams register their playback objects with the audio server and then update the volume during their panning or spatialization steps. This eliminates an entire class of bugs in which the player node's state is updated and it can't continue a volume ramp or fade out.

This also opens the door to lots of really exciting things! Now that we can crossfade across audio buses, we can have Area2D/Area3D based bus overrides that smoothly transition to the new bus. Imagine the mouth of a cave that slowly fades reverb in, or an area of a 2d platformer level that adds a distortion to audio. Before these things would cause pops and abrupt transitions, but with this change the pops are gone and it'll be fairly easy to add smooth transitions.

Another thing we can add back is polyphony, which I think users will appreciate. An audio stream player node can simply instance multiple playbacks for a stream and send them all to the audio server which will mix them independently. That's also not included in this change but should be simple to add.

A few notes:
* I changed the mix buffer size to 512, which I think is fine. It should probably be a project setting or at least influenced by the audio driver's buffer size, i.e. based on the latency project setting. It doesn't make sense for the audio server to have a bigger buffer than the audio driver.
* ~The NO_THREADS implementation of my SafeList data structure is probably broken, but I don't really know how to test it given that web exports aren't working in 4.0 right now, unless I'm mistaken on that.~
* This PR contains a mediocre workaround for #50958 that I put in for testing purposes only. I'm basically including the current viewport in the list of viewports to iterate through while looking for the active listener. It works for simple scenes but we should still address #50958 somehow.

### CODE REVIEW

**Comment by ellenhp** [comment]
This is the project I've been using to test: [audioservertest.zip](https://github.com/godotengine/godot/files/6950996/audioservertest.zip)

It's probably good to test this on other more complex projects too.

**Review by reduz — APPROVED** [review]

File: scene/2d/audio_stream_player_2d.cpp [hunk 1]
```diff
@@ -169,116 +64,124 @@ void AudioStreamPlayer2D::_notification(int p_what) {
...
+		if (active.is_set() && !AudioServer::get_singleton()->get_is_playback_active(stream_playback)) {
+			active.clear();
+			set_physics_process_internal(false);
+			emit_signal(SNAME("finished"));
+		}
+	}
+}
+StringName AudioStreamPlayer2D::_get_actual_bus() {
+	if (!stream_playback.is_valid()) {
+		return "Master";
```
Comment (akien-mga) [inline scene/2d/audio_stream_player_2d.cpp:89]:
```suggestion
		return SNAME("Master");
```
maybe? Also for other occurrences. `SNAME()` creates and caches the StringName so we always use the same one.

File: scene/2d/audio_stream_player_2d.cpp [hunk 2]
```diff
@@ -169,116 +64,124 @@ void AudioStreamPlayer2D::_notification(int p_what) {
...
-				if (vp->is_audio_listener_2d()) {
-					//compute matrix to convert to screen
-					Transform2D to_screen = vp->get_global_canvas_transform() * vp->get_canvas_transform();
-					Vector2 screen_size = vp->get_visible_rect().size;
+	Vector2 global_pos = get_global_position();
 
-					//screen in global is used for attenuation
-					Vector2 screen_in_global = to_screen.affine_inverse().xform(screen_size * 0.5);
+	Set<Viewport *> viewports = world_2d->get_viewports();
+	viewports.insert(get_viewport()); // Not sure why this is necessary.
```
Comment (akien-mga) [inline scene/2d/audio_stream_player_2d.cpp:131]: No idea :P
Is this something that was already done previously, or that you found that was needed for things to work?

File: scene/2d/audio_stream_player_2d.cpp [hunk 3]
```diff
@@ -385,7 +283,11 @@ void AudioStreamPlayer2D::_set_playing(bool p_enable) {
 }
 
 bool AudioStreamPlayer2D::_is_active() const {
-	return active.is_set();
+	if (stream_playback.is_valid()) {
+		// TODO make sure this doesn't change any behavior w.r.t. pauses. Is a paused stream active?
```
Comment (akien-mga) [inline scene/2d/audio_stream_player_2d.cpp:287]: Just putting a comment so that we remember to evaluate this (either in this PR or as a follow-up, if so might warrant opening an issue so we don't forget).

File: scene/2d/audio_stream_player_2d.cpp [hunk 4]
```diff
@@ -433,15 +335,17 @@ uint32_t AudioStreamPlayer2D::get_area_mask() const {
...
+		AudioServer::get_singleton()->set_playback_paused(stream_playback, p_pause);
 	}
 }
 
 bool AudioStreamPlayer2D::get_stream_paused() const {
-	return stream_paused;
+	if (stream_playback.is_valid()) {
+		return AudioServer::get_singleton()->get_is_playback_paused(stream_playback);
+	}
+	return false; // TODO is this the right default?
```
Comment (akien-mga) [inline scene/2d/audio_stream_player_2d.cpp:348]: I think so, at least that was the default previously.

File: scene/2d/audio_stream_player_2d.cpp [hunk 5]
```diff
@@ -433,15 +335,17 @@ uint32_t AudioStreamPlayer2D::get_area_mask() const {
 }
 
 void AudioStreamPlayer2D::set_stream_paused(bool p_pause) {
-	if (p_pause != stream_paused) {
-		stream_paused = p_pause;
-		stream_paused_fade_in = !p_pause;
-		stream_paused_fade_out = p_pause;
+	// TODO this does not have perfect recall, fix that maybe? If the stream isn't set, we can't persist this bool.
```
Comment (akien-mga) [inline scene/2d/audio_stream_player_2d.cpp:338]: Commenting as reminder for the TODO.

File: scene/2d/audio_stream_player_2d.h [hunk 6]
```diff
@@ -35,6 +35,7 @@
 #include "scene/2d/node_2d.h"
 #include "servers/audio/audio_stream.h"
 #include "servers/audio_server.h"
+#include <cstdint>
```
Comment (akien-mga) [inline scene/2d/audio_stream_player_2d.h:38]:
```suggestion
#include "scene/2d/node_2d.h"
#include "servers/audio/audio_stream.h"
#include "servers/audio_server.h"

#include <cstdint>
```

See https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html#header-includes

I don't know if the explicit `<cstdint>` include is needed though, technically it's correct but we use `uint*_t` types throughout the codebase without explicit includes, so I guess it's already included via typedefs which are included basically everywhere.

File: scene/3d/audio_stream_player_3d.cpp [hunk 7]
```diff
@@ -360,277 +278,228 @@ void AudioStreamPlayer3D::_notification(int p_what) {
...
-				}
+		float multiplier = Math::db2linear(_get_attenuation_db(dist));
+		if (max_distance > 0) {
+			multiplier *= MAX(0, 1.0 - (dist / max_distance));
+		}
+
+		// Output output;
+		// output.bus_index = bus_index;
+		// output.reverb_bus_index = -1; //no reverb by default
+		// output.viewport = vp;
```
Comment (akien-mga) [inline scene/3d/audio_stream_player_3d.cpp:423]: Can be removed?

File: scene/3d/audio_stream_player_3d.h [hunk 8]
```diff
@@ -31,12 +31,15 @@
...
 
+#include "core/math/audio_frame.h"
 #include "core/templates/safe_refcount.h"
+#include "scene/3d/area_3d.h"
 #include "scene/3d/node_3d.h"
 #include "scene/3d/velocity_tracker_3d.h"
 #include "servers/audio/audio_filter_sw.h"
 #include "servers/audio/audio_stream.h"
 #include "servers/audio_server.h"
+#include <cstdint>
```
Comment (akien-mga) [inline scene/3d/audio_stream_player_3d.h:42]:
```suggestion
#include "servers/audio/audio_stream.h"
#include "servers/audio_server.h"

#include <cstdint>
```

File: servers/audio/audio_stream.cpp [hunk 9]
```diff
@@ -345,13 +367,15 @@ void AudioStreamPlaybackRandomPitch::seek(float p_time) {
...
-void AudioStreamPlaybackRandomPitch::mix(AudioFrame *p_buffer, float p_rate_scale, int p_frames) {
+int AudioStreamPlaybackRandomPitch::mix(AudioFrame *p_buffer, float p_rate_scale, int p_frames) {
 	if (playing.is_valid()) {
-		playing->mix(p_buffer, p_rate_scale * pitch_scale, p_frames);
+		return playing->mix(p_buffer, p_rate_scale * pitch_scale, p_frames);
 	} else {
 		for (int i = 0; i < p_frames; i++) {
 			p_buffer[i] = AudioFrame(0, 0);
 		}
+		// TODO does this make sense?
```
Comment (akien-mga) [inline servers/audio/audio_stream.cpp:377]: To assess.

File: servers/audio_server.h [hunk 10]
```diff
@@ -155,7 +160,10 @@ class AudioServer : public Object {
 	};
 
 	enum {
-		AUDIO_DATA_INVALID_ID = -1
+		AUDIO_DATA_INVALID_ID = -1,
+		MAX_CHANNELS_PER_BUS = 4,
+		MAX_BUSES_PER_PLAYBACK = 6,
+		LOOKAHEAD_BUFFER_SIZE = 32
```
Comment (akien-mga) [inline servers/audio_server.h:166]:
```suggestion
		LOOKAHEAD_BUFFER_SIZE = 32,
```
Trailing comma can ensure that future additions won't generate unnecessary line diff.

File: servers/audio_server.h [hunk 11]
```diff
@@ -219,7 +227,43 @@ class AudioServer : public Object {
...
+			PLAYING = 1, // Playing. Fading may still be necessary if volume changes!
+			FADE_OUT_TO_PAUSE = 2, // About to pause.
+			FADE_OUT_TO_DELETION = 3, // About to stop.
+			AWAITING_DELETION = 4,
+		};
+		// If zero or positive, a place in the stream to seek to during the next mix.
+		std::atomic<float> setseek = -1;
+		std::atomic<float> pitch_scale = 1;
+		std::atomic<float> highshelf_gain = 0;
+		std::atomic<float> attenuation_filter_cutoff_hz = 0; // This isn't used unless highshelf_gain is nonzero.
```
Comment (akien-mga) [inline servers/audio_server.h:248]: I know we tend to use our own `SafeNumeric` instead of `std::atomic` (which wraps `std::atomic`), but I'm not familiar with its semantics and whether it would actually make sense here. CC @RandomShaper

File: servers/audio_server.h [hunk 12]
```diff
@@ -319,6 +371,25 @@ class AudioServer : public Object {
...
+	void set_playback_bus_exclusive(Ref<AudioStreamPlayback> p_playback, StringName p_bus, Vector<AudioFrame> p_volumes);
+	void set_playback_bus_volumes_linear(Ref<AudioStreamPlayback> p_playback, Map<StringName, Vector<AudioFrame>> p_bus_volumes);
+	void set_playback_all_bus_volumes_linear(Ref<AudioStreamPlayback> p_playback, Vector<AudioFrame> p_volumes);
+	void set_playback_pitch_scale(Ref<AudioStreamPlayback> p_playback, float p_pitch_scale);
+	void set_playback_paused(Ref<AudioStreamPlayback> p_playback, bool p_paused);
+	void set_playback_highshelf_params(Ref<AudioStreamPlayback> p_playback, float p_gain, float p_attenuation_cutoff_hz);
+
+	bool get_is_playback_active(Ref<AudioStreamPlayback> p_playback);
+	float get_playback_position(Ref<AudioStreamPlayback> p_playback);
+	bool get_is_playback_paused(Ref<AudioStreamPlayback> p_playback);
```
Comment (akien-mga) [inline servers/audio_server.h:387]: For boolean getters, we usually start directly with `is_` and not with `get_is_`.

**Review by akien-mga — COMMENTED** [review]
Great work!

I left some style nitpicks and only skimmed through the detailed code changes, but it looks pretty solid!

File: servers/audio/audio_stream.cpp (hunk 9 above)
Comment (ellenhp) [reply servers/audio/audio_stream.cpp]: I thought about it for a while, and I think it does make sense :) Removed as a todo.

**Comment by ellenhp** [comment]
Made the changes Akien pointed out and rebased. I also added a preprocessor warning in the NO_THREADS implementation of SafeList because it occurred to me that this could cause some frustrating bugs in the future if nobody is aware of it. I used a pattern that I've seen elsewhere in the codebase to avoid throwing an error on MSVC toolchains. I just want it documented in the code that NO_THREADS SafeLists are untested so someone debugging can identify issues quickly. Hopefully that's fine.

I also wanted to ask about whether my silly workaround in AudioStreamPlayer2D is appropriate to keep in this PR. I left it in for ease of testing but I don't think it's the correct solution for #50958.

File: servers/audio_server.h (hunk 11 above)
Comment (RandomShaper) [reply servers/audio_server.h:248]: That's right. `SafeNumeric<T>` is intended to be the Godot "STL" counterpart of `std::atomic`. It should fit most cases, where acquire-release semantics is the right choice.

Comment (RandomShaper) [reply servers/audio_server.h:248]: Elaborating on that, I see atomic are being used throughout this PR will the default memory ordering semantics (sequential). Even if we didn't have `SafeNumeric`, it'd be good to check if acquire-release is enough, because, AFAIK, that is more performant on certain architectures.

File: servers/audio_server.h [hunk 13]
```diff
@@ -219,7 +227,43 @@ class AudioServer : public Object {
...
+		// If zero or positive, a place in the stream to seek to during the next mix.
+		std::atomic<float> setseek = -1;
+		std::atomic<float> pitch_scale = 1;
+		std::atomic<float> highshelf_gain = 0;
+		std::atomic<float> attenuation_filter_cutoff_hz = 0; // This isn't used unless highshelf_gain is nonzero.
+		AudioFilterSW::Processor filter_process[8];
+		// Updating this ref after the list node is created breaks consistency guarantees, don't do it!
+		Ref<AudioStreamPlayback> stream_playback;
+		// Playback state determines the fate of a particular AudioStreamListNode during the mix step. Must be atomically replaced.
+		std::atomic<PlaybackState> state = AWAITING_DELETION;
```
Comment (RandomShaper) [inline servers/audio_server.h:253]: I guess this one can become a `SafeNumeric`, too, with the same provision about checking that acquire-release is fine.

File: servers/audio_server.h [hunk 14]
```diff
@@ -230,8 +274,15 @@ class AudioServer : public Object {
 	void init_channels_and_buffers();
 
 	void _mix_step();
+	void _mix_step_for_channel(AudioFrame *p_out_buf, AudioFrame *p_source_buf, AudioFrame p_vol_start, AudioFrame p_vol_final, float p_attenuation_filter_cutoff_hz, float p_highshelf_gain, AudioFilterSW::Processor *p_processor_l, AudioFilterSW::Processor *p_processor_r);
+
+	// Should only be called on the main thread.
+	AudioStreamPlaybackListNode *_find_playback_list_node(Ref<AudioStreamPlayback> p_playback);
 
 	struct CallbackItem {
+		std::atomic<CallbackItem *> next;
```
Comment (RandomShaper) [inline servers/audio_server.h:283]: In this case, since we don't have a `SafePointer<T>`, using `std::atomic` directly is fine. If we find many cases of atomic pointers sometime in the future, we can always introduce it.

In any case, again, it'd be good to check if acquire-release (or even something weaker) can be used intead of sequential in the operations.

File: core/templates/safe_list.h [hunk 15]
```diff
@@ -0,0 +1,365 @@
...
+#include <functional>
+#include <type_traits>
+
+// Design goals for these classes:
+// - Accessing this list with an iterator will never result in a use-after free,
+//   even if the element being accessed has been logically removed from the list on
+//   another thread.
+// - Logical deletion from the list will not result in deallocation at that time,
+//   instead the node will be deallocated at a later time when it is safe to do so.
+// - No blocking synchronization primitives will be used.
```
[the remark this answers is not in the document]
Comment (RandomShaper) [reply core/templates/safe_list.h:49]: I almost skipped this. I don't think I'll be able to check it today, so please let me check it tomorrow.

File: servers/audio_server.h (hunk 11 above)
Comment (ellenhp) [reply servers/audio_server.h:248]: I think acquire-release is probably fine everywhere except in SafeList but I find it very difficult to reason about these things so I'm not sure. I do think a system-wide barrier of some sort is appropriate during insertions or removals to SafeList because they tend to be fairly rare and the penalty if something goes wrong could be a double free or a use after free. These scalar values can absolutely have weaker guarantees.

The main thing we're attempting to avoid here is a sleeping on mutex contention, right? A memory barrier is not in the same league performance-wise as sleeping the audio thread.

Comment (ellenhp) [reply servers/audio_server.h:248]: Apparently a compare-swap operation is [about as expensive as a cache miss](https://en.wikipedia.org/wiki/Compare-and-swap#Costs_and_benefits) on x86 server platforms. I'm curious about other architectures but even if it were 100x more expensive than a cache miss I don't think I'd consider moving to another memory model for SafeList given how rarely insertions and deletions happen. I'm also hesitant to optimize without profiling results.

Side-note, thank you so much for reviewing this @RandomShaper. I know it's a difficult PR to review and I appreciate it. :)

Comment (RandomShaper) [reply servers/audio_server.h:248]: No worries! It's also hard for me to reason about every possible case. I just have the mindset of use acq-rel by default, which is already stronger than certain cases would need, but it still allows for more perfomant load/stores on some architectures than sequential would cause. When it's about compare-exchange, to be honest, I still haven't studied much about the performane consequences of using one memory ordering or the other.

In the case of `SafeList`, I can't but agree that the wisest thing is to leave sequential ordering.

This said, the only thing I'd ask you to do is switch to `SafeNumeric` in the other cases.

Comment (ellenhp) [reply servers/audio_server.h:248]: Makes sense! I'll do that later today. I think I also want to get my NO_THREADS implementation of the SafeList structure to a better state than it is right now. I haven't tested it so it might be broken and I don't want to check in broken code. I can ping you when everything is done if you'd like?

I'm glad I'm not the only one who finds this sort of thing difficult. Writing the SafeList class nearly broke my brain. Lock-free programming is hard. 🤣

Comment (RandomShaper) [reply servers/audio_server.h:248]: Sure, feel free to ping me.

Yeah, lockless is hell. I wouldn't dare myself to write a lockless data structure unless there's no other option, like basing it on some third party one known to be good.

Comment (ellenhp) [reply servers/audio_server.h]: @RandomShaper Ready for another review. I've had lots of trouble thinking about whether or not the remaining atomic usages are okay for acquire-release. The scalar values are definitely okay to be SafeNumerics, but other than those, all remaining usages of the default atomic behavior impact control flow in non-trivial ways. If you'd like, I can switch the playback state enum over to be acquire-release, but I'd prefer to keep the bus details pointer as-is. I should be honest though, it's fear of double-frees or other weird behavior that's making me say this, not any sort of logic or reason. :)

**Comment by ellenhp** [comment]
Rebased. This PR has become quite a mess of commits! Let me know when it's ready to merge and I'll squash them. If possible I'd like approval from @RandomShaper before merging and @reduz might be interested in double-checking that the way I rebased my AudioStream::mix return type change from void to int is correct. I kind of just guessed. :) Other than rebasing and adjusting to the new GDVIRTUAL stuff, I also made a bunch of fixes with the NO_THREADS implementation of SafeList. I'm now pretty sure it's correct. I tested it for functionality and it seems to work fine.

File: servers/audio_server.h (hunk 14 above)
Comment (ellenhp) [reply servers/audio_server.h:283]: Mentioned above, but I'm not entirely comfortable switching over to acquire release here. I'm not convinced it would be a problem, but I can't convince myself it's safe either.

Comment (ellenhp) [reply servers/audio_server.h:283]: Wow nevermind! These atomics can be removed. They're dead code leftover from before I factored out SafeList into its own file.

**Comment by AndreaCatania** [comment]
Hello, when I play the game I've a segmentation fault at this line: https://github.com/ellenhp/godot/blob/3598d300cb43797a4f18b34d921875d060ce7de7/servers/audio_server.cpp#L1237 which was added by this PR. Any idea how to fix it?

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (e6e5502a165d34762e29203658dbfd624a5bb9bd)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3d320) [0x7ffff7a87320] (??:0)
[2] AudioServer::set_playback_all_bus_volumes_linear(Ref<AudioStreamPlayback>, Vector<AudioFrame>) (/home/andrea/Workspace/momento/wander/source/engine/godot/servers/audio_server.cpp:1237)
[3] AudioStreamPlayer::set_volume_db(float) (/home/andrea/Workspace/momento/wander/source/engine/godot/scene/audio/audio_stream_player.cpp:98 (discriminator 4))
[4] void call_with_variant_args_helper<__UnexistingClass, float, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(float), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/andrea/Workspace/momento/wander/source/engine/godot/./core/variant/binder_common.h:227 (discriminator 4))
[5] void call_with_variant_args_dv<__UnexistingClass, float>(__UnexistingClass*, void (__UnexistingClass::*)(float), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/andrea/Workspace/momento/wander/source/engine/godot/./core/variant/binder_common.h:370)
[6] MethodBindT<float>::call(Object*, Variant const**, int, Callable::CallError&) (/home/andrea/Workspace/momento/wander/source/engine/godot/./core/object/method_bind.h:286)
[7] ClassDB::set_property(Object*, StringName const&, Variant const&, bool*) (/home/andrea/Workspace/momento/wander/source/engine/godot/core/object/class_db.cpp:1189)
[8] Object::set(StringName const&, Variant const&, bool*) (/home/andrea/Workspace/momento/wander/source/engine/godot/core/object/object.cpp:407)
[9] Variant::set_named(StringName const&, Variant const&, bool&) (/home/andrea/Workspace/momento/wander/source/engine/godot/core/variant/variant_setget.cpp:234)
[10] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/andrea/Workspace/momento/wander/source/engine/godot/modules/gdscript/gdscript_vm.cpp:947)
[11] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/home/andrea/Workspace/momento/wander/source/engine/godot/./modules/gdscript/gdscript.cpp:1486)
[12] Node::_gdvirtual__process_call(double) (/home/andrea/Workspace/momento/wander/source/engine/godot/scene/main/node.h:221 (discriminator 5))
[13] Node::_notification(int) (/home/andrea/Workspace/momento/wander/source/engine/godot/scene/main/node.cpp:59)
[14] Node::_notificationv(int, bool) (/home/andrea/Workspace/momento/wander/source/engine/godot/./scene/main/node.h:48 (discriminator 14))
[15] Object::notification(int, bool) (/home/andrea/Workspace/momento/wander/source/engine/godot/core/object/object.cpp:843)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/andrea/Workspace/momento/wander/source/engine/godot/scene/main/scene_tree.cpp:851)
[17] SceneTree::process(double) (/home/andrea/Workspace/momento/wander/source/engine/godot/scene/main/scene_tree.cpp:455 (discriminator 2))
[18] Main::iteration() (/home/andrea/Workspace/momento/wander/source/engine/godot/main/main.cpp:2554)
[19] OS_LinuxBSD::run() (/home/andrea/Workspace/momento/wander/source/engine/godot/platform/linuxbsd/os_linuxbsd.cpp:342)
[20] /home/andrea/Workspace/momento/wander/source/engine/godot/bin/godot.linuxbsd.tools.64(main+0x144) [0x24ad95a] (/home/andrea/Workspace/momento/wander/source/engine/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[21] /lib64/libc.so.6(__libc_start_main+0xd5) [0x7ffff7a71b75] (??:0)
[22] /home/andrea/Workspace/momento/wander/source/engine/godot/bin/godot.linuxbsd.tools.64(_start+0x2e) [0x24ad75e] (??:?)
-- END OF BACKTRACE --
================================================================
```

**Comment by AndreaCatania** [comment]
I spot the issue, on the following code `playback_node->bus_details.load()` is returning a `nullptr`:
```c++
		if (playback_node->bus_details.load()->bus_active[bus_idx]) {
			map[playback_node->bus_details.load()->bus[bus_idx]] = p_volumes;
		}
```
so it crashes. To fix it we should check it in this way:
```c++
	if (playback_node->bus_details.load()) {
		if (playback_node->bus_details.load()->bus_active[bus_idx]) {
			map[playback_node->bus_details.load()->bus[bus_idx]] = p_volumes;
		}
	}
```
Even if this code fix the issue **momentarily on my project**, it still unsafe. Atomic pointers, if not under some well documented and strict conditions, are unsafe since the check is guaranteed only the moment of the first `if`; any subsequent call may cause a segmentation fault, since the pointer can suddenly change.
To fix this issue, we need to use a mutex, or make sure that by design the pointer can't ever change at that point.

Please let me know if you need that I open an issue, I'm also available to test an eventual fix.

**Comment by ellenhp** [comment]
Good catch. This can be easily made to be safe, it was just an oversight on my part.

**Comment by ellenhp** [comment]
Maybe not as easily as I had hoped. Would you mind making an issue because this might need further discussion and I'd like to be able to point to something other than an enormous PR when I submit a fix.

**Comment by ellenhp** [comment]
@AndreaCatania would you mind testing #52187?
