### PR TITLE
[Input] Handle invalid `input/` settings correctly

### LINKED ISSUE #115624: [4.6] After migrating from 4.5 to 4.6 - ERROR: Bug: Dictionary::operator[] used when there was no value
### Tested versions

- Reproducible in v4.6.stable.official [89cea1439]
- Not reproducible in v4.5.1.stable.official [f62fdbde1]
- Not reproducible in an empty project in v4.6

### System information

Windows 10 - Godot 4.6 - Vulkan 1.4.325 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 4070 Ti SUPER

### Project information
- 3D Project 
- Using Forward Plus
- 14k lines across 176 .tscn files.
- 27k lines of gdscript code in 280 files
- Using externally created 3d models, imported via glb files (maybe relevant due to the linked issue)
- Using different addons, but it happens also when removing all addons completely from the project

### Issue description

After migrating my project from 4.5.1 to 4.6 this morning, i get these logs in the output every time i load the project:

Godot Engine v4.6.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "events". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "deadzone". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "events". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "deadzone". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "events". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "deadzone". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "events". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "deadzone". Please report.
--- Debug adapter server started on port 6006 ---
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "events". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "deadzone". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "events". Please report.
  ERROR: Bug: Dictionary::operator[] used when there was no value for the given key "deadzone". Please report.

### Additional information
Maybe noteworthy:
- My game doesnt start anymore
- All shader code was deleted from some of my shader files (gonna file another bug for that)

### Steps to reproduce

Unfortunatelly i cant provide repro steps, because my project is very big already and i cannot say where it comes from. 

### Minimal reproduction project (MRP)

Unfortunatelly i cant provide repro steps, because my project is very big already and i cannot say where it comes from.

### PR DESCRIPTION
**Pull request by AThousandShips**
This prefix is reserved for events

Could fully filter out invalid entries in the project settings, but keeping this as small scale as possible, I think these invalid settings also show up in autocompletion, which would be annoying

Only a noisy issue when manually adding invalid settings to the `input/`, the bug doesn't seem to have any practical impact (though the invalid entries do show up in the action map editor)

* Fixes: https://github.com/godotengine/godot/issues/115624

Edit: Added an optional commit to error in the editor, see the review comment below for some context

### CODE REVIEW

File: editor/settings/project_settings_editor.cpp [hunk 1]
```diff
@@ -613,6 +613,10 @@ void ProjectSettingsEditor::_update_action_map_editor() {
 		String display_name = property_name.substr(String("input/").size() - 1);
 		Dictionary action = GLOBAL_GET(property_name);
 
+		if (!action.has("events")) {
+			continue;
+		}
```
Comment (akien-mga) [inline editor/settings/project_settings_editor.cpp:619]: At least for the editor, should this report an error so users can fix their settings?

```suggestion
  
  		ERR_CONTINUE_EDMSG(!action.has("events"), vformat("Invalid input action in project settings: %s.", property_name));
```

Comment (AThousandShips) [reply editor/settings/project_settings_editor.cpp:619]: Good point, depends on if we consider the fact that `input/` is a hidden prefix as it being properly reserved, can absolutely add that to point people in the right direction

The problem is they'd have to manually remove it from the `project.godot` file as it can't be edited in the project settings editor, so it might be unhelpful to warn about it

Adding it for consideration for review

Comment (KoBeWi) [reply editor/settings/project_settings_editor.cpp:619]: > depends on if we consider the fact that input/ is a hidden prefix as it being properly reserved

The `input/` is such a generic name that not sure if we should forbid using it. Maybe it can be one-time warning saying "`input/` should be used for input actions, consider changing the category" or something.

Comment (AThousandShips) [reply editor/settings/project_settings_editor.cpp:619]: I'll tweak and make it a warning clarifying the setting will be hidden

We'd have to look at how incorrect entries here affect other areas as they might turn up in and mess up autocomplete etc., haven't dug into that

**Review by KoBeWi — APPROVED** [review]

**Comment by AThousandShips** [comment]
Thank *you*!
