### PR TITLE
Scale quickhull tolerance with mesh size

### LINKED ISSUE #21141: "Create convex static body/collision sibling" freezes the editor if used on sphere mesh (regression)
**Godot version:**
c93888a

**OS/device including version:**
Windows 10

**Issue description:**
If you use these options when MeshInstance with sphere geometry is selected

image

the editor will freeze for a long time(or maybe crash) with the following error spam in console

image

Update: It also have same behavior if you use it on Capsule mesh

### PR DESCRIPTION
**Pull request by hpvb**
Taken from three.js's implementation. Tested with a wide variety of
meshes.

This fixes #21141

### CODE REVIEW

File: core/math/quick_hull.cpp [hunk 1]
```diff
@@ -36,7 +36,7 @@ uint32_t QuickHull::debug_stop_after = 0xFFFFFFFF;
 
 Error QuickHull::build(const Vector<Vector3> &p_points, Geometry::MeshData &r_mesh) {
 
-	static const real_t over_tolerance = 0.0001;
+	real_t over_tolerance = 0.0001;
```
Comment (akien-mga) [inline core/math/quick_hull.cpp]: Does it make sense to define it here? It looks like the `0.0001` is never used.

I'd remove this one and put `real_t over_tolerance = 3 * UNIT_EPSILON * (aabb.size.x + aabb.size.y + aabb.size.z);` directly under `/* COMPUTE AVAILABLE VERTICES */`.

Comment (hpvb) [reply core/math/quick_hull.cpp]: Yeah, that's a good point. I was a bit too happy I found a solution :P

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
