### PR TITLE
Use double when setting the default step size

### LINKED ISSUE #47390: ProgressBar with max value 10 can't reach 100%
**Godot version:**

166a6d0 / 3.3rc6

**Steps to reproduce:**
1. Add ProgressBar node
2. Set max value to 10
3.
image
image
Also the percents are not accurate at all, e.g. 1/10 is 9%. Could be another float precision issue, but it looks really bad in this case.

### PR DESCRIPTION
**Pull request by megalobyte**
Fixes #47390

Confirmed this bug is present in 3.2 and current master branch. 

Prior to change:
Godot3 2_example
precision_error

After change:
godot_fix
fixed_100

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1472,7 +1472,7 @@ void Node3DEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
 
 				Vector3 ray_pos = _get_ray_pos(m->get_position());
 				Vector3 ray = _get_ray(m->get_position());
-				float snap = EDITOR_GET("interface/inspector/default_float_step");
+				float snap = EDITOR_GET("interface/inspector/default_step_size");
```
Comment (aaronfranke) [inline editor/plugins/node_3d_editor_plugin.cpp:1475]: This line should be `double snap`.

**Review by aaronfranke — COMMENTED** [review]
On using `double`: Good idea.

On renaming to `default_step_size`: Seems OK, but should be discussed, cc @akien-mga.

File: editor/plugins/node_3d_editor_plugin.cpp (hunk 1 above)
Comment (megalobyte) [reply editor/plugins/node_3d_editor_plugin.cpp]: Updated `snap` to double. Also had to update `angle` further down to fix a compile warning. 

Regarding the name change, in hindsight I'm not to keen on the new name. I think `default_precision` or `default_resolution` would be more descriptive for how the variable is meant to be used. At the very least, I think having float in the name is misleading, but I'll implement whatever you guys think is best.

Comment (akien-mga) [reply editor/plugins/node_3d_editor_plugin.cpp]: In Godot's API, `float` is a 64-bit float point type, so the name was fine IMO.

But if we want to change it, it could be `default_decimal_resolution` yes.

**Comment by akien-mga** [comment]
Note that the email used to author your commit doesn't appear to be linked to your GitHub account (see email in header: https://github.com/godotengine/godot/commit/c59da0e181da5688a80baf086522746524ccfa1f.patch ). It's not a problem for Git but that's why the commit is not being shown as authored by "@megalobyte".
If you wish to reclaim it, you can either add this email address to your GitHub account, or re-author the commit with a different identity.

**Comment by megalobyte** [comment]
@akien-mga Thanks for the heads up

**Review by aaronfranke — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Comment by kerryann89** [comment]
I am new to Github and also coding. Can someone please explain this to me as I am  a beginner please.

**Comment by kerryann89** [comment]
> I am new to Github and also coding. Can someone please explain this to me as I am a beginner please.
what is the difference between the before and after screenshot that was done?

**Comment by Calinou** [comment]
@kerryann89 This pull request has been merged already, so there is no more work remaining to do on this subject. If you want to contribute to Godot, see [Ways to contribute](https://docs.godotengine.org/en/stable/community/contributing/ways_to_contribute.html) in the documentation :slightly_smiling_face:

**Comment by megalobyte** [comment]
@kerryann89 Sorry for the late reply, I don't check github often. The first screen shot showed 49% when showing the progress of 5 steps out of 10. That should obviously be 50%. The first screen shot also shows a max value of 100.00005, but I entered 100. Also not good. 

This occurred because of a floating point precision error. If you're new to programming and plan to work in C++ in the future, precision errors a good thing to keep in mind because they're not a syntax or logic error, so they can be hard to debug. Hope this helps
