### PR TITLE
Fix MOUSE_FILTER_STOP not affecting emulated mouse events

### LINKED ISSUE #71099: Input event passes through Control-nodes with emulating touch from mouse enabled.
### Godot version

v4.0.beta.custom_build [bb08997b8]

### System information

Ubuntu 22.10 LTS, GTX1060, Vulkan

### Issue description

If you toggle emulate_touch_from_mouse option in ProjectSettings `InputEventMouseMotion`, `InputEventScreenDrag`, `InputEventScreenTouch` passes through `Panel`, afaik this doesn't happen in **`3.x branch`**

how tree looks:
```
- Node
  - Panel(half screen size, to stop input events)
  - Node(captures unhandled inputs)

```
screen separated into 2 sides, left side is Panel, right is empty space, so if you click on Panel you can't get any output from _unhandled_input on Node.

### Steps to reproduce

1. run attachment
2. click and/or scroll with mouse on left side and right side (check output)
3. go to project settings and toggle `emulate touch from mouse`
4. go to step 2 (check output)

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/10371324/New.Game.Project.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Touch and drag events are now also stopped by `MOUSE_FILTER_STOP`

resolve #71099

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @boruok

**Comment by groud** [comment]
Looks like a good solution to me.

**Comment by boruok** [comment]
tested. works!

**Review by akien-mga — APPROVED** [review]

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1338,8 +1338,8 @@ bool Viewport::_gui_call_input(Control *p_control, const Ref<InputEvent> &p_inpu
 				stopped = true;
 				break;
 			}
-			if (control->data.mouse_filter == Control::MOUSE_FILTER_STOP && is_mouse_event && !(is_scroll_event && control->data.force_pass_scroll_events)) {
-				// Mouse events are stopped by default with MOUSE_FILTER_STOP, unless we have a scroll event and force_pass_scroll_events set to true
+			if (control->data.mouse_filter == Control::MOUSE_FILTER_STOP && (is_mouse_event || p_input->get_device() == InputEvent::DEVICE_ID_TOUCH_MOUSE) && !(is_scroll_event && control->data.force_pass_scroll_events)) {
+				// Mouse events and emulated events from Mouse events are stopped by default with MOUSE_FILTER_STOP, unless we have a scroll event and force_pass_scroll_events set to true
```
Comment (m4gr3d) [inline scene/main/viewport.cpp:1342]: Can you update the logic to set `is_mouse_event` instead to include `p_input->get_device() == InputEvent::DEVICE_ID_TOUCH_MOUSE`.

That'll ensure that other uses of `is_mouse_event` also reflect the change.

**Review by m4gr3d — DISMISSED** [review]

**Comment by Sauermann** [comment]
Before I update the PR with the requested change, I would like to discuss the question, when an InputEvent should be considered a mouse event.

In the context of emulating mouse from touch and emulating touch from mouse, they are a bit ambiguous and the question becomes, which of the combinations should be considered a mouse event.

The following graphic shows an overview of the current state in master, the version of this PR and a suggestion, 

EmulatedMouseEventStatus drawio

I have the feeling, that in its current form this PR is inconsistent, because a touch event gets sent to a different set of Nodes than the mouse event, that it causes, if touch-to-mouse is activated.

My question is, if it would be better to treat an `InputEventMouse` that was created as an emulation from Screen-Touch not as a mouse event.

**Comment by Sauermann** [comment]
As discussed in the PR-review meeting, Drag and Touch events are now also stopped by `MOUSE_FILTER_STOP`.

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -1314,7 +1314,7 @@ bool Viewport::_gui_call_input(Control *p_control, const Ref<InputEvent> &p_inpu
 	Ref<InputEvent> ev = p_input;
 
 	// Returns true if an event should be impacted by a control's mouse filter.
-	bool is_mouse_event = Ref<InputEventMouse>(p_input).is_valid();
+	bool is_mouse_event = Ref<InputEventMouse>(p_input).is_valid() || Ref<InputEventScreenDrag>(p_input).is_valid() || Ref<InputEventScreenTouch>(p_input).is_valid();
```
Comment (RandomShaper) [inline scene/main/viewport.cpp:1317]: Let me suggest either renaming the variable (e.g., `is_pointer_event`) or adding a new one and checking both.

Comment (Sauermann) [reply scene/main/viewport.cpp]: Since the variable is only used in a single place, splitting it up into two variables seems like a bit of overkill.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
