### PR TITLE
Basis constructor: row vectors -> column vectors 

### LINKED ISSUE #5295: Change the constructor of Basis
Currently Basis constructor takes row vectors as parameters, because it is how Basis stores the matrix.
However this is very unintuitive as , as these row vectors have no physical meaning.
Users natually have basis vectors to offer which are the columns of the matrix.

(Note: current doc describes the parameters as column vectors but this is wrong. This is fixed by https://github.com/godotengine/godot/pull/65124 .)

This is the current implementation of the constructor:
```
Basis(const Vector3 &row0, const Vector3 &row1, const Vector3 &row2) {
	rows[0] = row0;
	rows[1] = row1;
	rows[2] = row2;
}
```

In addition, Transform3D already takes column vectors as parameters, and use `set_column` to set the basis.
It is better to be consistent.
```
Transform3D::Transform3D(const Vector3 &p_x, const Vector3 &p_y, const Vector3 &p_z, const Vector3 &p_origin) :
		                             origin(p_origin) {
	basis.set_column(0, p_x);
	basis.set_column(1, p_y);
	basis.set_column(2, p_z);
}
```

Interestingly the Mono glue also uses column and does the conversion internally.
```cs
/// <summary>
/// Constructs a basis matrix from 3 axis vectors (matrix columns).
/// </summary>
/// <param name="column0">The X vector, or Column0.</param>
/// <param name="column1">The Y vector, or Column1.</param>
/// <param name="column2">The Z vector, or Column2.</param>
public Basis(Vector3 column0, Vector3 column1, Vector3 column2)
{
    Row0 = new Vector3(column0.x, column1.x, column2.x);
    Row1 = new Vector3(column0.y, column1.y, column2.y);
    Row2 = new Vector3(column0.z, column1.z, column2.z);
    // Same as:
    // Column0 = column0;
    // Column1 = column1;
    // Column2 = column2;
    // We need to assign the struct fields here first so we can't do it that way...
}
```

So I propose that we should change

```
Basis(const Vector3 &row0, const Vector3 &row1, const Vector3 &row2) {
	rows[0] = row0;
	rows[1] = row1;
	rows[2] = row2;
}
```

to something like

```
Basis(const Vector3 &p_basis_x, const Vector3 &p_basis_y, const Vector3 &p_basis_z) {
	set_column(0, p_basis_x);
	set_column(1, p_basis_y);
	set_column(2, p_basis_z);
}
```

One practical trouble is that this entirely changes the usage of this function but it does not change the function signature.
It is hard for existing users upgrading the engine to realize this change when it silently screws up their games.
A notification or warning should be posted somewhere.

### LINKED ISSUE #59806: Basis(Vector3, Vector3, Vector3) in GDScript in Godot 4 appears to take the arguments as rows, rather than columns (axes)
### Godot version

4.0-alpha5

### System information

Linux, Vulkan, 1070M

### Issue description

This started because I was having a chat on Discord with a user that was convinced that `Basis(Vector3, Vector3, Vector3)` in Godot 3 actually took in matrix rows, rather than the columns (the axes). Part of the reason he thought this, is that printing out the `Basis` will show the matrix as rows:

Godot 3

So, I was going to make a PR to fix the printing of `Basis`.

However, when I went to go try the same code in Godot 4 (where I would have to make a PR first) the results were even more surprising -  `Basis(Vector3, Vector3, Vector3)` _does_ appear to take the rows as arguments in Godot 4:

Godot 4

Is this a purposeful change that needs a docs fix? Or, is this a bug?

### Steps to reproduce

Here's the code from my screenshot above:

```
	var x = Vector3(0.707107, -0.707107, 0)
	var y = Vector3(0.707107, 0.707107, 0)
	var z = Vector3(0, 0, 1)
	
	var basis = Basis(x, y, z)
	
	print ("x: ", x)
	print ("y: ", y)
	print ("z: ", z)
	
	print ("Basis as string: ", basis)
	
	print ("basis.x: ", basis.x)
	print ("basis.y: ", basis.y)
	print ("basis.z: ", basis.z)
```

We are passing in an x axis of `Vector3(0.707107, -0.707107, 0)` but the `basis.x` is `(0.707107, 0.707107, 0)`. I would have expected them to be the same (and on Godot 3, they are the same)!

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by zhehangd**
The Basis constructor takes row vectors but the doc says column.
```cpp
_FORCE_INLINE_ Basis(const Vector3 &row0, const Vector3 &row1, const Vector3 &row2) {
    rows[0] = row0;
    rows[1] = row1;
    rows[2] = row2;
}
```

> Constructs a basis matrix from 3 axis vectors (matrix columns).

*Bugsquad edit:*
- Closes https://github.com/godotengine/godot-proposals/issues/5295
- Fixes #59806

### CODE REVIEW

**Comment by zhehangd** [comment]
In addition, I think using row vectors as paramters are very confusing. Using column vectors makes a lot of sense.
This is not directly related to this PR so I opened another proposal for discussion
https://github.com/godotengine/godot-proposals/issues/5295

**Comment by akien-mga** [comment]
It's using rows internally as it's better for performance IIUC. But the user facing API should be with columns, I think it's just bound to the wrong constructor here.

Needs discussion with @reduz and @aaronfranke.

**Comment by zhehangd** [comment]
Right. Though this PR is just dealing with doc inconsitentcy, we can finish this and discuss the parameter issue in the proposal.

**Comment by aaronfranke** [comment]
@akien-mga is correct, the bug is that the wrong constructor is bound. It works as expected in Godot 3, but it's bugged in the master branch. I wouldn't change the documentation, only to have the documentation changed back later.

**Comment by dsnopek** [comment]
This is the issue tracking this bug: https://github.com/godotengine/godot/issues/59806

**Comment by zhehangd** [comment]
Ok I updated the commit so now the constructor directly takes basis vectors instead of rows.
So merging it will complete https://github.com/godotengine/godot-proposals/issues/5295 and fix https://github.com/godotengine/godot/issues/59806.

File: core/math/basis.h [hunk 1]
```diff
@@ -238,10 +238,8 @@ struct _NO_DISCARD_ Basis {
 	Basis(const Vector3 &p_axis, real_t p_angle, const Vector3 &p_scale) { set_axis_angle_scale(p_axis, p_angle, p_scale); }
 	static Basis from_scale(const Vector3 &p_scale);
 
-	_FORCE_INLINE_ Basis(const Vector3 &row0, const Vector3 &row1, const Vector3 &row2) {
-		rows[0] = row0;
-		rows[1] = row1;
-		rows[2] = row2;
+	_FORCE_INLINE_ Basis(const Vector3 &p_basis_x, const Vector3 &p_basis_y, const Vector3 &p_basis_z) {
+		set_columns(p_basis_x, p_basis_y, p_basis_z);
```
Comment (aaronfranke) [inline core/math/basis.h:242]:
```suggestion
	_FORCE_INLINE_ Basis(const Vector3 &p_x_axis, const Vector3 &p_y_axis, const Vector3 &p_z_axis) {
		set_columns(p_x_axis, p_y_axis, p_z_axis);
```

**Review by aaronfranke — APPROVED** [review]
I can confirm that this works as expected. Now the Variant constructor is the only usage of this constructor.

Note that this is different from Godot 3, which has a constructor in C++ accepting rows and then the bound one is different. Also, it makes sense to have the C++ constructor match the GDScript one (what this PR does).

One rename suggestion though, since "basis" isn't a helpful distinction inside of Basis:

File: core/math/basis.h (hunk 1 above)
Comment (zhehangd) [reply core/math/basis.h]: Done. "basis vector" is a stricter term in this context than "axis vector" which is a little bit ambiguous. But I suppose it isn't a big deal and "axis" has already been used everywhere in the codebase.

**Review by akien-mga — APPROVED** [review]
Looks good to me. Also confirmed with @reduz that it's fine.

reduz actually mentioned that we might want to reconsider whether there's really a significant gain in storing things by rows internally. Transform3D and Projection use columns.

**Comment by akien-mga** [comment]
Thanks!
