### PR TITLE
Fix a nested ysort invalid memory read again

### LINKED ISSUE #24755: Deleting specific branch of nodes from nested YSort tree causes viewport bug
**Godot version:** v3.1-alpha 65a86ae
**OS:** Windows 10.0.17134
**GPU:** NVIDIA GeForce GTX 980 Ti
**NVIDIA driver version:** 23.21.13.8813

**Issue description:**
Create a node tree that looks like this:
image

Delete the "Node2D" node, which should delete its "YSort" child node. The viewport will then be filled with infinitely-stacking copies of the whole editor:
image

Trying to run the project in this state causes the editor to crash. This happens under both GLES2 and GLES3.

**Minimal reproduction project:**
This comes with the full tree in place. Just delete the "Node2D" node and you should see the bug.
[ysort graphics bug.zip](https://github.com/godotengine/godot/files/2725745/ysort.graphics.bug.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #24755.
What is more fun than making a bunch of PRs fixing the same issue over and over :confused:.

### CODE REVIEW

File: servers/visual/visual_server_canvas.cpp [hunk 1]
```diff
@@ -126,6 +133,8 @@ void VisualServerCanvas::_render_canvas_item(Item *p_canvas_item, const Transfor
 		int i = 0;
 		_collect_ysort_children(ci, Transform2D(), child_items, i);
 
+		// ERR_FAIL_COND(child_item_count != i);
```
Comment (akien-mga) [inline servers/visual/visual_server_canvas.cpp]: Debug statement?

**Comment by akien-mga** [comment]
Thanks!
