### PR TITLE
Fixed popup_menu buttons getting activated on press instead of release

### LINKED ISSUE #51778: Clicking Scene menu's Undo/Redo always fail
### Godot version

4.0.dev (84b11fbaa)

### System information

macOS 11.5.1

### Issue description

Clicking Undo/Redo in editor's Scene menu does nothing and prints something like this in the output:

```
Can't undo while mouse buttons are pressed.
```

Undo/Redo works if I hover that menu item by mouse and then press enter on the keyboard.

* This happens no matter if Single Window Mode is enabled.
* This does not happen in 3.x. The message will only appear when pressing CTRL-Z with mouse button pressed in the editor.

### Steps to reproduce

Click Undo/Redo in editor's Scene menu.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ThreeRhinosInAnElephantCostume**
Fixes #51778

The real issue is that popup_menu buttons activate on _pressing_ the LMB whereas in 3.x they activated on _releasing_ it.

This is (presumably) unintended, so I modified it to work the way it did in 3.x.

The behaviour described by the comment directly below my change is still present, though I am not sure why it's a thing.

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -358,7 +358,7 @@ void PopupMenu::_gui_input(const Ref<InputEvent> &p_event) {
 		}
 
 		int button_idx = b->get_button_index();
-		if (b->is_pressed() || (!b->is_pressed() && during_grabbed_click)) {
+		if (!b->is_pressed()) {
 			// Allow activating item by releasing the LMB or any that was down when the popup appeared.
 			// However, if button was not held when opening menu, do not allow release to activate item.
```
Comment (EricEzaM) [inline scene/gui/popup_menu.cpp:363]:
```suggestion
		// Activate item when the left mouse button is released.
		if (!b->is_pressed()) {
```

The comment documenting the functionality should change if you are changing a part of how it works.

**Review by EricEzaM — COMMENTED** [review]
> though I am not sure why it's a thing.

It allows for people to open a popup menu and activate an item in one mouse click. Press down -> hover to item -> release. Not a workflow that I use but I guess someone does.

File: scene/gui/popup_menu.cpp (hunk 1 above)
Comment (ThreeRhinosInAnElephantCostume) [reply scene/gui/popup_menu.cpp:363]: > The comment documenting the functionality should change if you are changing a part of how it works.

The functionality stays the same, so the comment is still up to date, it's just working as intended now.

Comment (EricEzaM) [reply scene/gui/popup_menu.cpp:363]: No, the bold part of comment below is a complete contradiction to what the functionality now is:

"// However, if button was not held when opening menu, **do not allow release to activate item**."

**Review by EricEzaM — APPROVED** [review]
Wicked!

File: scene/gui/popup_menu.cpp [hunk 2]
```diff
@@ -358,9 +358,10 @@ void PopupMenu::_gui_input(const Ref<InputEvent> &p_event) {
 		}
 
 		int button_idx = b->get_button_index();
-		if (b->is_pressed() || (!b->is_pressed() && during_grabbed_click)) {
-			// Allow activating item by releasing the LMB or any that was down when the popup appeared.
-			// However, if button was not held when opening menu, do not allow release to activate item.
+		if (!b->is_pressed()) {
+			// Activate the item on release of either the left mouse button or
```
Comment (akien-mga) [inline scene/gui/popup_menu.cpp:362]: Trailing space on this line.

File: scene/gui/popup_menu.cpp (hunk 1 above)
Comment (ThreeRhinosInAnElephantCostume) [reply scene/gui/popup_menu.cpp]: Oh, I get it now

**Comment by akien-mga** [comment]
Thanks!
