### PR TITLE
[Web] Refactor `mouse_mode` setters in display server

### LINKED ISSUE #102209: [Web] `Input.mouse_mode` can't capture mouse after user presses escape key in browser
### Tested versions

- Reproducible in Godot 4.4.beta2
- Not Reproducible in 4.3

### System information

Godot v4.4.beta2 - Linux Mint 22 (Wilma) on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4060 Ti (nvidia; 550.120) - AMD Ryzen 9 3900X 12-Core Processor (24 threads)

### Issue description

I have discovered an edge case that likely happens often. When the mouse is captured browsers tend to tell the user that they can press escape to free there mouse. If we capture the users mouse and then they press escape we can not again capture it with the current behavior. Even though the engine knows that the mouse has been released. To capture the mouse again after the user has pressed escape we must first tell the engine to release the mouse and then capture it again. So that they engine executes the correct sequence.

Note: https://github.com/godotengine/godot/issues/100758#issuecomment-2624679816

### Steps to reproduce

1. Extract MRP
2. Open MRP in Godot 4.4.beta2
3. Ensure exports are managed for Godot 4.4.beta2
4. Run the MRP in the browser.
5. Capture the mouse using the button provided.
6. Press the escape key "esc".
7. Observe that your mouse is released and visible.
8. Attempt to capture the mouse using the button provided that says "Capture Mouse".
9. Observe this does not work.
10. Press the button that says "Capture Mouse After Release".
11. Observe this works.

Alternatively for step 10. You can also press space bar or press the "Release Mouse" button. and then you can press the "Capture Mouse" button and it will work.

### Minimal reproduction project (MRP)

[web-mouse-capture-part-2.zip](https://github.com/user-attachments/files/18608637/web-mouse-capture-part-2.zip)

### PR DESCRIPTION
**Pull request by adamscott**
This PR refactors the `mouse_mode` ~~setters in display servers of various platforms in order to update the mouse_mode only when actually needed.~~ setter in the Web platform display server.

It also fixes an issue on the Web platform where the mouse mode would refuse to capture the mouse twice.

Fixes #102209.

Edit: reverted to a Web-only fix.

### CODE REVIEW

File: platform/web/display_server_web.cpp [hunk 1]
```diff
@@ -576,9 +576,17 @@ void DisplayServerWeb::_mouse_update_mode() {
...
 void DisplayServerWeb::mouse_set_mode(MouseMode p_mode) {
 	ERR_FAIL_INDEX(p_mode, MouseMode::MOUSE_MODE_MAX);
-	if (p_mode == mouse_mode_base) {
+
+	if (mouse_mode_override_enabled) {
+		mouse_mode_base = p_mode;
+		// No need to update, as override is enabled.
+		return;
+	}
+	if (p_mode == mouse_mode_base && p_mode == mouse_get_mode()) {
```
Comment (adamscott) [inline platform/web/display_server_web.cpp:585]: `mouse_get_mode()` is specific to the Web platform, as we don't store a cached version of the state. We query the browser directly.

Comment (bruvzg) [reply platform/web/display_server_web.cpp:585]: > It also fixes an issue on the Web platform where the mouse mode would refuse to capture the mouse twice.

Other platform seems to automatically recapture mouse if you refocus the app. For example, Windows call mode update from window activation handlers to restore it, maybe Web should store it and auto-recapture mouse instead of requiring to set in the second time?

Comment (adamscott) [reply platform/web/display_server_web.cpp:585]: @bruvzg Not possible. Because the browser is letting you a way to escape from websites, by pressing escape. And capturing the mouse is only possible from a direct action from the user: i.e. a click. So it's not possible to capture the mouse without intent from the user. If the user escaped, we cannot capture until a new click.

See https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock#security for more info.

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -815,9 +815,17 @@ void DisplayServerWindows::_mouse_update_mode() {
...
+		// No need to update, as override is enabled.
+		return;
+	}
+	if (p_mode == mouse_mode_base && p_mode == mouse_mode) {
+		// No need to update, as it is currently set as the correct mode.
 		return;
 	}
+
 	mouse_mode_base = p_mode;
 	_mouse_update_mode();
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:830]: `_mouse_update_mode` already have the following check:

```c++
	MouseMode wanted_mouse_mode = mouse_mode_override_enabled
			? mouse_mode_override
			: mouse_mode_base;

	if (mouse_mode == wanted_mouse_mode) {
		return;
	}
```

And `mouse_mode` is only and always updated in `_mouse_update_mode`, so these checks seems redundant (on desktop platforms).

**Review by bruvzg — COMMENTED** [review]
Web part make sense, but the rest of the changes seems redundant.

File: platform/windows/display_server_windows.cpp (hunk 2 above)
Comment (adamscott) [reply platform/windows/display_server_windows.cpp:830]: You're right, forgot about the check in update. Will revert the desktop files.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Chubercik** [comment]
Possibly fixes #102403, needs testing.

**Comment by AThousandShips** [comment]
It probably doesn't as this was a regression in 4.4, so unless this also changed other areas it wouldn't be the same bug, but someone should test, this is in `beta4`

**Comment by Chubercik** [comment]
> It probably doesn't as this was a regression in 4.4, so unless this also changed other areas it wouldn't be the same bug, but someone should test, this is in `beta4`

Yeah, I saw changes being made to the mouse's behaviour on the web and got excited too quickly 😅

Checked the issue out using `beta4`, unfortunately, it still persists 😪
