### PR TITLE
Ensure PopupMenu item is shaped when the shortcut is set.

### LINKED ISSUE #66453: Shortcut text in PopupMenu of MenuButton cut off the first time menu is opened
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

If you set a shortcut on an item in a `PopupMenu`, the shortcut is shown next to the item.  The first time the menu is opened, the menu is not positioned correctly to accommodate this text.  Opening the menu a second time properly positions it.

This is a regression from 3.5.

popup_menu_shortcut_bug

### Steps to reproduce

1. Create a `MenuButton`
2. Add a `Shortcut` to one of the items
3. Run the project and click on the menu button

### Minimal reproduction project

[menu_button_shortcut_display_bug.zip](https://github.com/godotengine/godot/files/9647902/menu_button_shortcut_display_bug.zip)

### PR DESCRIPTION
**Pull request by EricEzaM**
Closes #66453

https://user-images.githubusercontent.com/41730826/193438665-479d08ff-97c6-4cc5-a843-f618f605dd1b.mp4

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -1457,6 +1457,7 @@ void PopupMenu::set_item_shortcut(int p_idx, const Ref<Shortcut> &p_shortcut, bo
 	items.write[p_idx].shortcut = p_shortcut;
 	items.write[p_idx].shortcut_is_global = p_global;
 	items.write[p_idx].dirty = true;
+	_shape_item(p_idx);
```
Comment (bruvzg) [inline scene/gui/popup_menu.cpp:1460]: Strange, this should not be necessary, setting `dirty` should be enough, since it's will reshape it on redraw.

Comment (bruvzg) [reply scene/gui/popup_menu.cpp:1460]: Oh, I see the issue was about menu position not drawing, so I guess a more universal solution would be adding shape to the size calculation, shortcut is likely not the only property that can cause size changes.

```diff
diff --git a/scene/gui/popup_menu.cpp b/scene/gui/popup_menu.cpp
index 10e13042a7..ca3bd8070f 100644
--- a/scene/gui/popup_menu.cpp
+++ b/scene/gui/popup_menu.cpp
@@ -60,6 +60,8 @@ Size2 PopupMenu::_get_contents_minimum_size() const {
 	for (int i = 0; i < items.size(); i++) {
 		Size2 size;
 
+		const_cast<PopupMenu *>(this)->_shape_item(i);
+
 		Size2 icon_size = items[i].get_icon_size();
 		size.height = _get_item_height(i);
 		icon_w = MAX(icon_size.width, icon_w);
```

Comment (EricEzaM) [reply scene/gui/popup_menu.cpp:1460]: Yes I did originally do that as the fix, but the cost cast I wanted to avoid. If you think that is better I am happy to do that.

**Comment by KoBeWi** [comment]
This also fixes an issue where changing a shortcut does not update the shortcut listed in popup (tested in the editor). Not sure if it was reported.

**Comment by EricEzaM** [comment]
#66442?

**Comment by KoBeWi** [comment]
Looks like it's still not fixed (but this PR does it)

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
