### PR TITLE
RegEx: Fix handling of unset/unknown capture groups

### LINKED ISSUE #6114: Add option to allow RegEx substitution empty replacement groups
### Describe the project you are working on

Currently, improving project 3 to 4 converter, but I suppose this is something that expected from regex to support.

### Describe the problem or limitation you are having in your project

Currently, it is impossible to do regex replacement for patterns with optional replacement groups.

Simple example: (a)|(b) - to replace with $1$2. In this case either $1 or $2 will be empty. Expected result will be "a" for "a" and "b" for "b". Actual result is empty string in both cases because for "a" entry, we have $1 = "a" but $2 is not found (and vice versa).

Real life example:

\bOS\.set_window_resizable\s*\((.*)\)|\bOS\.window_resizable\s*=\s*([^#]+)

This pattern allows to capture as $1$2 both setter argument or assignment to replace:

get_window().resizable = $1$2

There are also many other cases where I used such replacement approach.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Introduce new RegEx option (disabled by default) that will enable PCRE2 to treat not found groups as an empty strings.
This will allow regex replacements which otherwise require multiple separate patterns. Please see example above.

This is also how online regex matchers works, for example https://regex101.com and some software like Notepad++.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If I understand PCRE2 docs correctly, this option should just set both PCRE2_SUBSTITUTE_UNKNOWN_UNSET and PCRE2_SUBSTITUTE_UNSET_EMPTY when RegEx.sub(...) is preparing flags.

https://www.pcre.org/current/doc/html/pcre2api.html#SEC36

Currently it looks like this:

```c++
uint32_t flags = PCRE2_SUBSTITUTE_OVERFLOW_LENGTH;
if (p_all) {
  flags |= PCRE2_SUBSTITUTE_GLOBAL;
}
````

I haven't tested if this will actually gives desired effect yet but I believe it should.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I suppose only way to workaround this is using separate regex for each group and apply them sequentially which increase complexity and code size.

I also found #3487 and #2927 where pattern options workaround was suggested, but after reading PCRE2 documentation I didn't found any of such options for this replace options (_UNKNOWN_UNSET and _UNSET_EMPTY).

### Is there a reason why this should be core and not an add-on in the asset library?

RegEx class is already part of core.

### PR DESCRIPTION
**Pull request by dalexeev**
Add the `PCRE2_SUBSTITUTE_UNSET_EMPTY` flag so that unset capture groups do not clear the line.

* Closes godotengine/godot-proposals#6114.
* See also #73954.

https://www.pcre.org/current/doc/html/pcre2api.html

> PCRE2_SUBSTITUTE_UNKNOWN_UNSET causes references to capture groups that do not appear in the pattern to be treated as unset groups. This option should be used with care, because it means that a typo in a group name or number no longer causes the PCRE2_ERROR_NOSUBSTRING error.
>
> PCRE2_SUBSTITUTE_UNSET_EMPTY causes unset capture groups (including unknown groups when PCRE2_SUBSTITUTE_UNKNOWN_UNSET is set) to be treated as empty strings when inserted as described above. If this option is not set, an attempt to insert an unset group causes the PCRE2_ERROR_UNSET error. This option does not influence the extended substitution syntax described below. 

* Add error message output.

Example:

```gdscript
var line := "property get_property set_property"

var re1 := RegEx.new()
re1.compile("((get_|set_)?)property")

var re2 := RegEx.new()
re2.compile("(get_|set_)?property")

print("|", re1.sub(line, "$1new_property", true), "|")
print("|", re2.sub(line, "$1new_property", true), "|")
print("|", re2.sub(line, "$5new_property", true), "|")
```

Before:

```
|new_property get_new_property set_new_property|
||
||
```

After:

```
|new_property get_new_property set_new_property|
|new_property get_new_property set_new_property|
  modules/regex/regex.cpp:332 - PCRE2 Error: unknown substring
|new_property new_property new_property|
```

### CODE REVIEW

File: modules/regex/regex.cpp [hunk 1]
```diff
@@ -326,6 +326,10 @@ String RegEx::sub(const String &p_subject, const String &p_replacement, bool p_a
 	pcre2_match_context_free_32(mctx);
 
 	if (res < 0) {
+		PCRE2_UCHAR32 buf[256];
+		pcre2_get_error_message_32(res, buf, 256);
+		String message = "PCRE2 Error: " + String((const char32_t *)buf);
+		ERR_PRINT(message.utf8());
 		return String();
```
Comment (dalexeev) [inline modules/regex/regex.cpp:333]: Perhaps in case of an error we should return the original string, and not an empty one?

**Comment by akien-mga** [comment]
This makes sense to me. It makes the behavior consistent with Python 3's `re.sub()`.

```
$ python3
Python 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> line = "property get_property set_property"
>>> res1 = re.sub(r"((get_|set_)?)property", r"\1new_property", line)
>>> res1
'new_property get_new_property set_new_property'
>>> res2 = re.sub(r"(get_|set_)?property", r"\1new_property", line)
>>> res2
'new_property get_new_property set_new_property'
>>> res3 = re.sub(r"(get_|set_)?property", r"\5new_property", line)
Traceback (most recent call last):
  File "<python-input-8>", line 1, in <module>
    res3 = re.sub(r"(get_|set_)?property", r"\5new_property", line)
  File "/usr/lib64/python3.13/re/__init__.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/re/__init__.py", line 377, in _compile_template
    return _sre.template(pattern, _parser.parse_template(repl, pattern))
                                  ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/re/_parser.py", line 1070, in parse_template
    addgroup(int(this[1:]), len(this) - 1)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/re/_parser.py", line 1015, in addgroup
    raise s.error("invalid group reference %d" % index, pos)
re.PatternError: invalid group reference 5 at position 1
>>> res3
Traceback (most recent call last):
  File "<python-input-9>", line 1, in <module>
    res3
NameError: name 'res3' is not defined. Did you mean: 'res1'?
```

File: modules/regex/regex.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/regex/regex.cpp:333]: Good question. We could, but that should then also be changed for the early failure checks at the start of the function.

`sed` and Python `re` both raise exceptions so they don't have a fallback behavior to take inspiration from.

Interesting, `perl` doesn't error and instead returns the _replacement string_ with the unmatched group being an empty string:
```
$ perl -pe 's/((get_|set_)?)property/\5new_property/g' <<< "property get_property set_property"
new_property new_property new_property
```

That kind of makes sense?

Comment (akien-mga) [reply modules/regex/regex.cpp:333]: Also with a case that doesn't involve actual capture groups:
```
$ perl -pe 's/property/\5new_property/g' <<< "property get_property set_property"
new_property get_new_property set_new_property
```

If the pattern to replace is a match, and the replacement pattern can be made sense of by treating the invalid reference as empty, then I'd indeed expect it to do what perl does. (Though unlike perl, I'd still print an error that the replacement string references a non-existing capture group.)

**Review by akien-mga — APPROVED** [review]
I think this could be merged as is, but indeed there's a case to be made about what the return value should be in case of failure.

File: modules/regex/regex.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/regex/regex.cpp:333]: This makes sense to me logically, but since an unknown capture group throws an error anyway, I think we could just return an empty string. A fallback would require calling PCRE2 again with `PCRE2_SUBSTITUTE_UNKNOWN_UNSET`, so I'm not sure it's worth it.

Comment (dalexeev) [reply modules/regex/regex.cpp]: However, I tried to do it. Looks correct.

**Comment by akien-mga** [comment]
I've just been thinking that it would be good to add a unit test for those changes.

**Review by akien-mga — APPROVED** [review]
