### PR TITLE
Ignore class's property array when generating extension_api.json (not…

### LINKED ISSUE #63066: Incorrect property types in extension_api.json
### Godot version

4.0.alpha12

### System information

Windows 10

### Issue description

Information about properties of classes in `extension_api.json` appears to be incorrect in some cases.

There are cases where int turns into list of two elements:
* SkeletonModificationStack2D and SkeletonModificationStack3D
    - Property: modification_count
    - Expected value (as in docs): int
    - Actual value (as in json): Modifications,modifications/
* Curve, Curve2D and Curve3D
    - Property: point_count
    - Expected value (as in docs): int
    - Actual value (as in json): Points,point_
* ItemList and PopupMenu
    - Property: item_count
    - Expected value (as in docs): int
    - Actual value (as in json): Items,item_
* MenuButton and OptionButton
    - Property: item_count
    - Expected value (as in docs): int
    - Actual value (as in json): Items,popup/item_
* SkeletonProfile
    - Property: group_size
    - Expected value (as in docs): int
    - Actual value (as in json): Groups,group/
    - Property: bone_size
    - Expected value (as in docs): int
    - Actual value (as in json): Bones,bone/
* TabBar
    - Property: tab_count
    - Expected value (as in docs): int
    - Actual value (as in json): Tabs,tab_    

And there are also a few of a different type. This ones are not documented, but can be accessed through GDScript.   
Getters and setters are also empty strings for them.
* AudioStreamRandomizer
    - Property: streams
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): stream_
* TileMap
    - Property: layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): layer_
* TileSet
    - Property: occlusion_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): occlusion_layer_
    - Property: physics_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): physics_layer_
    - Property: terrain_sets
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): terrain_set_
    - Property: navigation_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): navigation_layer_
    - Property: custom_data_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): custom_data_layer_

### Steps to reproduce

1. Get `extension_api.json`
2. Check for yourself

### Minimal reproduction project

_No response_

### LINKED ISSUE #64426: Class property array incorrectly displayed in extension_api.json
### Godot version

4.0-rc13

### System information

n/a

### Issue description

Currently, class's property array are rendered in `extension_api.json` as regular properties:
```python
{
    "name": "AudioStreamRandomizer",
    [...]
    "properties": [
        {
            "type": "stream_",
            "name": "streams",
            "setter": "",
            "getter": "",
            "index": -1
        },
    [...]
}
```

However this is misleading:
- the value in type field is not a valid type (the `stream_` value comes from an "array element prefix" set when registering the property array)
- this property cannot be directly accessed (at least as far as I know: it is not present in the documentation and I couldn't find a way to access them from GDScript). Instead this property seems to be only used by the node editor.

So I guess this array property is not a real property and should be [added to the list of ignored ones](https://github.com/godotengine/godot/blob/eda6800f5dc01981f3626580d91a619b496acb5f/core/extension/extension_api_dump.cpp#L843-L848) when dumping the json

### Steps to reproduce

n/a

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by touilleMan**
fix #64426
fix #63066

I've copied the code from the [mono's bindings_generator.cpp](https://github.com/godotengine/godot/blob/eda6800f5dc01981f3626580d91a619b496acb5f/modules/mono/editor/bindings_generator.cpp#L2768) (I'm not sure why the `F.type == Variant::NIL` part is needed given `PropertyInfo::add_property_array` always set the type to `Variant::NIL`)

In the long run, we should probably replace this by a proper factorization (for instance adding a `PropertyInfo::is_fake_property` method) as there is multiple places where this `E.usage & PROPERTY_USAGE_CATEGORY ||  ...` pattern is used (sometime without the check to `PROPERTY_USAGE_ARRAY` and no comment to easily understand if it is a desired behavior ^^)

EDIT: I've also included a commit that filter out the properties with `/` in there name (this also comes from [mono's bindings_generator.cpp](https://github.com/godotengine/godot/blob/eda6800f5dc01981f3626580d91a619b496acb5f/modules/mono/editor/bindings_generator.cpp#L2772-L2775) ) as they are also not real properties (if you ask me, in the long run we should have a dedicated `PROPERTY_...` for this kind of "editor only" property). Tell me you'd rather have it as a separate PR ;-)

### CODE REVIEW

**Comment by raulsntos** [comment]
> I'm not sure why the `F.type == Variant::NIL` part is needed given `PropertyInfo::add_property_array` always set the type to `Variant::NIL`

Probably because it can be `Variant::INT` when using `add_property_array_count` which adds the same `PROPERTY_USAGE_ARRAY` flag so we need to disambiguate. This way the array count is exposed, although it may not be very useful by itself.

By the way, when I added that check to mono I copied it from `test_class_db` (this was added in the original PR that implements the array property feature):

https://github.com/godotengine/godot/blob/4bd7700e89f4476a3b2c76e7bed4263a111b3c09/tests/test_class_db.h#L530

**Comment by touilleMan** [comment]
> This way the array count is exposed, although it may not be very useful by itself.

According to #63066 `PROPERTY_USAGE_ARRAY` on `Variant::INT` also cause issues in `extension_api.json`

@raulsntos  I'd rather updated this PR to ignore all `PROPERTY_USAGE_ARRAY` (As you say it is not very useful and this array flag seems pretty fragile). But if you prefer I can implement instead the [fix you proposed](https://github.com/godotengine/godot/issues/63066#issuecomment-1186206860)

**Comment by raulsntos** [comment]
One example of something that would break if we remove/unexpose the count properties: in C# we use the `ItemList.ItemCount` property in `BuildOutputView`.

**Comment by touilleMan** [comment]
@raulsntos Thanks for the feedback ! I've updated my PR with your fix then ;-)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Since the changes seem related to each other it might be best to squash them, and use the commit description to clarify what the changes do instead of separate commits.

BTW it seems like you opened this PR by creating a branch on the upstream Godot repo instead of your fork. That means double the amount of CI runs (when pushing to the branch, and in the PR). To note for future PRs :)

File: core/extension/extension_api_dump.cpp [hunk 1]
```diff
@@ -846,6 +846,10 @@ Dictionary NativeExtensionAPIDump::generate_extension_api() {
 					if (F.name.begins_with("_")) {
 						continue; //hidden property
 					}
+					if (F.name.find("/") >= 0) {
+						// Ignore properties with '/' (slash) in the name. These are only meant for use in the inspector.
+						continue;
+					}
```
Comment (akien-mga) [inline core/extension/extension_api_dump.cpp:855]: I'm not sure if that's always true.

At least some of them seem to be real but badly named properties:
```
doc/classes/AudioEffectDelay.xml:               <member name="feedback/active" type="bool" setter="set_feedback_active" getter="is_feedback_active" default="false">
doc/classes/AudioEffectDelay.xml:               <member name="feedback/delay_ms" type="float" setter="set_feedback_delay_ms" getter="get_feedback_delay_ms" default="340.0">
doc/classes/AudioEffectDelay.xml:               <member name="feedback/level_db" type="float" setter="set_feedback_level_db" getter="get_feedback_level_db" default="-6.0">
doc/classes/AudioEffectDelay.xml:               <member name="feedback/lowpass" type="float" setter="set_feedback_lowpass" getter="get_feedback_lowpass" default="16000.0">
doc/classes/AudioEffectDelay.xml:               <member name="tap1/active" type="bool" setter="set_tap1_active" getter="is_tap1_active" default="true">
doc/classes/AudioEffectDelay.xml:               <member name="tap1/delay_ms" type="float" setter="set_tap1_delay_ms" getter="get_tap1_delay_ms" default="250.0">
doc/classes/AudioEffectDelay.xml:               <member name="tap1/level_db" type="float" setter="set_tap1_level_db" getter="get_tap1_level_db" default="-6.0">
doc/classes/AudioEffectDelay.xml:               <member name="tap1/pan" type="float" setter="set_tap1_pan" getter="get_tap1_pan" default="0.2">
doc/classes/AudioEffectDelay.xml:               <member name="tap2/active" type="bool" setter="set_tap2_active" getter="is_tap2_active" default="true">
doc/classes/AudioEffectDelay.xml:               <member name="tap2/delay_ms" type="float" setter="set_tap2_delay_ms" getter="get_tap2_delay_ms" default="500.0">
doc/classes/AudioEffectDelay.xml:               <member name="tap2/level_db" type="float" setter="set_tap2_level_db" getter="get_tap2_level_db" default="-12.0">
doc/classes/AudioEffectDelay.xml:               <member name="tap2/pan" type="float" setter="set_tap2_pan" getter="get_tap2_pan" default="-0.4">
doc/classes/CharacterBody2D.xml:                <member name="collision/safe_margin" type="float" setter="set_safe_margin" getter="get_safe_margin" default="0.08">
doc/classes/CharacterBody3D.xml:                <member name="collision/safe_margin" type="float" setter="set_safe_margin" getter="get_safe_margin" default="0.001">
doc/classes/Joint3D.xml:                <member name="collision/exclude_nodes" type="bool" setter="set_exclude_nodes_from_collision" getter="get_exclude_nodes_from_collision" default="true">
doc/classes/Joint3D.xml:                <member name="nodes/node_a" type="NodePath" setter="set_node_a" getter="get_node_a" default="NodePath(&quot;&quot;)">
doc/classes/Joint3D.xml:                <member name="nodes/node_b" type="NodePath" setter="set_node_b" getter="get_node_b" default="NodePath(&quot;&quot;)">
doc/classes/Joint3D.xml:                <member name="solver/priority" type="int" setter="set_solver_priority" getter="get_solver_priority" default="1">
```

Comment (akien-mga) [reply core/extension/extension_api_dump.cpp:855]: I'm fixing those in #44876.

**Comment by touilleMan** [comment]
@akien-mga thanks for the review !

I've squashed and rebase the commits and improved the commit message as you asked

> BTW it seems like you opened this PR by creating a branch on the upstream Godot repo

Sorry for this (I can't even say it's the first time, shame on me !), I'll try to be more careful next time ;-)

> I'm fixing those in https://github.com/godotengine/godot/pull/44876.

So do you want me to remove the check on `/` properties now ?

**Comment by akien-mga** [comment]
> > I'm fixing those in #44876.
> 
> So do you want me to remove the check on `/` properties now ?

No I think it's ok. Those properties with `/` are not actually usable in GDScript so it makes sense to ignore them in GDExtension too. After #44876, the remaining ones should all be stuff that is indeed not meant to be accessed as properties.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
