### PR TITLE
[Windows] Add support for handling network share paths.

### LINKED ISSUE #54863: Windows network paths do not work properly with Godot's file dialog
### Godot version

3.4-stable

### System information

Windows 11 for ARM VM on an M1 Mac (I think it should be reproducible with any Windows device with a network share)

### Issue description

Windows network paths do not work properly with Godot's file dialog.

What works:

* Browsing files
* Displaying the path in the path box

What doesn't work:

* Creating files or folders
* Hiding the drive letter when the path is a network path

Here is what it looks like:

GodotWindowsNetworkShare

### Steps to reproduce

Open the file dialog in the project manager on a Windows machine with a network share and observe that Godot doesn't hide the drive letter or allow creating files or folders.

### Minimal reproduction project

N/A - can be reproduced in the project manager.

### LINKED ISSUE #55314: Can't create config directory on Windows DFS roaming profiles
### Godot version

v4.0.dev.custom_build [1e99eea06]

### System information

Windows 10, AD-managed roaming user profiles

### Issue description

When Godot is used on a Windows PC, it fails to create the user's config directory **%AppData%/Godot** if the user profile is a roaming profile managed by [Active Directory](https://en.wikipedia.org/wiki/Active_Directory) and mounted on a [DFS](https://en.wikipedia.org/wiki/Distributed_File_System_(Microsoft)) path.

## Some More Details
It is common that user profiles in large companies and universities are not bound to local machines and instead live on a server and are loaded onto any machine when a user logs in. These are called **roaming profiles**. Windows uses Active Directory to manage users and groups. When a roaming profile is mounted, it's often done on a DFS path, which takes the form `\\ServerName\RootName\path\to\wherever\`. See [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dfsc/3109f4be-2dbb-42c9-9b8e-0b34f7a2135e) for the full DFS specification.

Godot does not recognize that path. It fails to correctly parse it as a DFS path and subsequently errors out of creating the user config. This means no shader cache, no editor settings, no user-specific settings are ever created or saved.

The code that causes the failure is `DirAccess::make_dir_recursive` in `dir_access.cpp`, specifically this part:
```c++
full_dir = full_dir.replace("\\", "/");

String base;

if (full_dir.begins_with("res://")) {
	base = "res://";
} else if (full_dir.begins_with("user://")) {
	base = "user://";
} else if (full_dir.begins_with("/")) {
	base = "/";
} else if (full_dir.find(":/") != -1) {
	base = full_dir.substr(0, full_dir.find(":/") + 2);
} else {
	ERR_FAIL_V(ERR_INVALID_PARAMETER);
}

full_dir = full_dir.replace_first(base, "").simplify_path();

Vector<String> subdirs = full_dir.split("/");

String curpath = base;
for (int i = 0; i < subdirs.size(); i++) {
	curpath = curpath.plus_file(subdirs[i]);
	Error err = make_dir(curpath);
	if (err != OK && err != ERR_ALREADY_EXISTS) {
		ERR_FAIL_V_MSG(err, "Could not create directory: " + curpath);
	}
}
```

Running through these instructions, the DFS path 
`\\dfs\mycorp\home\myusername\AppData\Godot` turns into
`//dfs/mycorp/home/myusername/AppData/Godot` (this is expected) and from there into
`/dfs/mycorp/home/myusername/AppData/Godot`.

Because there is no Windows-type drive letter (like C:\) in the path, it effectively turns it into a unix file path. It then tries to recursively create this directory, starting at the root `/`, which fails, but not for the reasons the engine would expect. It returns with an error message and the directory is never created.

Console output:
```
USER ERROR: Could not create directory: /
   at: DirAccess::make_dir_recursive (core\io\dir_access.cpp:173) - Method/function failed. Returning: err
USER ERROR: Can't create shader cache folder, no shader caching will happen: //dfs/mycorp/home/myusername/AppData/Godot
USER ERROR: Cannot save EditorSettings config, no valid path
   at: EditorSettings::save (editor\editor_settings.cpp:1012) - Cannot save EditorSettings config, no valid path
```

### Steps to reproduce

- Sit down on a Windows machine that mounts roaming user profiles on a DFS path
- Install Godot and launch the project manager
- Create a project, change the UI language, close the manager
- Launch the manager again, observe how none of the settings have been saved and the list of projects is empty

### Minimal reproduction project

Any will do, even just starting the project manager. Observe the console output.

### PR DESCRIPTION
**Pull request by bruvzg**
Adds support for handling Windows `//Server/Share/` style network share paths.

Screenshot 2022-01-24 162747

- Fixes #54863, adds temporary, unselectable `Network` item to the drive list, which is removed as soon as any other drive is selected.
- Fixes #55314

### CODE REVIEW

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -4288,7 +4291,22 @@ String String::get_base_dir() const {
 		}
 	}
 
-	// unix root directory base
+	// Windows UNC netwrok share path.
```
Comment (mhilbrunner) [inline core/string/ustring.cpp:4294]:
```suggestion
	// Windows UNC network share path.
```

File: drivers/windows/dir_access_windows.cpp [hunk 2]
```diff
@@ -165,8 +165,11 @@ Error DirAccessWindows::make_dir(String p_dir) {
 	bool success;
 	int err;
 
-	p_dir = "\\\\?\\" + p_dir; //done according to
-	// https://msdn.microsoft.com/en-us/library/windows/desktop/aa363855(v=vs.85).aspx
+	if (!p_dir.begins_with("\\\\")) {
```
Comment (mhilbrunner) [inline drivers/windows/dir_access_windows.cpp:168]: Maybe having a `is_network_share_path()` would be clearer than putting `p_dir.begins_with("\\\\")` in multiple places?

**Review by mhilbrunner — COMMENTED** [review]
Looks good. Some comments below.

File: drivers/windows/dir_access_windows.cpp (hunk 2 above)
Comment (bruvzg) [reply drivers/windows/dir_access_windows.cpp:168]: This makes sense, and also can be used by the file dialog UI in some way.

**Review by mhilbrunner — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
