### PR TITLE
Disable viewports inputs when dragging and dropping into the viewport

### LINKED ISSUE #90112: Alt key conflict between scene drag and drop and 3D navigation scheme
### Tested versions

v4.3.dev5.mono.official [89f70e98d]

### System information

Godot v4.3.dev5.mono - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

Since https://github.com/godotengine/godot/pull/87623 has been merged the alt key is used as a drag-and-drop modifier to instantiate scenes as a child of root instead of a child of a selected node. However, this now conflicts with none default navigation schemes. 

https://github.com/godotengine/godot/assets/105675984/d69f9cd0-921b-4226-8f18-adeb77bdb0e8

### Steps to reproduce

Change navigation scheme to Maya or Modo.

image

Hold Alt while doing drag-and-drop to instantiate scene as a child of root 

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: https://github.com/godotengine/godot/issues/90112 and this comment https://github.com/godotengine/godot/issues/90112#issuecomment-2105974359

Having viewport inputs enabled while performing a drag and drop leads to issues especially in different navigation modes as mentioned in the linked issue. In theory the existing behavior sounds good, but in practice I believe it leads to more issues than it's worth. Usually, users put the target location in their viewport before dragging to it.

### CODE REVIEW

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1668,6 +1668,10 @@ void Node3DEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
 				}
 			} break;
 			case MouseButton::RIGHT: {
+				if (preview_node->is_inside_tree() || spatial_editor->get_preview_material().is_valid()) {
+					break;
```
Comment (ryevdokimov) [inline editor/plugins/node_3d_editor_plugin.cpp:1672]: I actually don't see the need for right-click to do anything in the viewport when drag-and-dropping.

**Comment by ryevdokimov** [comment]
Just realized I haven't actually solved the problem, and it's a little bit more complex. Might have to look into disabling all input on the viewport before the data has even entered. I think this is more of an "input" problem, than simply not allowing certain functions depending on the drop data.

**Review by akien-mga — DISMISSED** [review]
Makes sense to me.

*Edit:* Not sure actually. I don't have a lot of hands on experience with 3D but it seems useful to me to be able to navigate the scene while dragging something to instantiate at a specific place. Sometimes the target is just a little bit off the current viewport, or zooming is needed to position things precisely, etc.

**Comment by KoBeWi** [comment]
> it seems useful to me to be able to navigate the scene while dragging something to instantiate at a specific place

What are the options to navigate the scene though? Holding Alt rotates the camera, but only if you use non-Godot navigation scheme. I think most people use the default, which doesn't allow navigating while dragging (unless I'm missing some shortcut).

**Review by akien-mga — APPROVED** [review]
Alright, let's go with this approach and see if anyone complains their [workflow](https://xkcd.com/1172/) broke.

**Comment by akien-mga** [comment]
Thanks!
