### PR TITLE
Fix ambiguous AnimationNode's parameter type in default value and make `validate_type_match()` static function

### LINKED ISSUE #105275: Tween on AnimationTree Blend Amount is not working
### Tested versions

4.4.1

### System information

Godot v4.4.1.stable - Windows 11 (build 22631) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6119) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads)

### Issue description
Seems to be similar to this issue: https://www.reddit.com/r/godot/comments/1cfdjhp/how_to_tween_blend_amount_in_animationtree_smooth/

When I use a tween on `blend_amount` to smoothly transition between aiming and not aiming, the `blend_amount` just goes from 0 to 1.

Code:
Image
Results:

https://github.com/user-attachments/assets/a790551a-26ee-47c0-88de-6415c98fc78d

Expected:

https://github.com/user-attachments/assets/b7768aa7-1b67-44b9-8c04-8ffcb1a43a6c

### Steps to reproduce

Not able to replicate

### Minimal reproduction project (MRP)

I provide a MRP but I wasn't able to replicate. Needs more investigation.

[replicate-tweening-blend-amount.zip](https://github.com/user-attachments/files/19724401/replicate-tweening-blend-amount.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/105275
- Supersedes/Closes https://github.com/godotengine/godot/pull/106440

The cause of this problem is the following implicit cast:

```cpp
Variant val = 0.0;
WARN_PRINT(stringify_variant(val)); // 0.0
val = 0;
WARN_PRINT(stringify_variant(val)); // 0
```

Considering the behavior of the Variant type, unless fundamental changes are made to the Variant type, it seems that the only solution is the approach suggested by @KoBeWi .

There are two places where problems occur:

- `AnimationTree::_set()`
- `AnimationNode::set_parameter()`

However, even with these validations, the `property_map` may initially be set to the wrong type due to incorrect default parameter types.

In the former case `AnimationTree::_set()`, I assume that the type may have been saved incorrectly in past projects when the parameter was not changed after placing the AnimationNode. Below is an MRP that intentionally reproduces that situation.

[replicate-tweening-blend-amount_issue.zip](https://github.com/user-attachments/files/20536567/replicate-tweening-blend-amount_issue.zip)

If you save that MRP after applying this PR, the stored type should be fixed in `cube.tscn`.

This PR fixes the type of the parameter's default value, adds validation, and makes the validation function static. Since the utilities related to Variant conversion are already collected in the Animation class, so I will integrate them there.

### CODE REVIEW

**Review by lyuma — APPROVED** [review]
Seems like a good correctness fix. Every case seems to be fixing code that was returning the wrong type, and the change to set ensures that every subsequent attempt to assign the property assigns the matching type. I think this fixes the issue.

File: scene/animation/animation_blend_space_1d.cpp [hunk 1]
```diff
@@ -47,7 +47,7 @@ Variant AnimationNodeBlendSpace1D::get_parameter_default_value(const StringName
 	if (p_parameter == closest) {
 		return -1;
```
Comment (akien-mga) [inline scene/animation/animation_blend_space_1d.cpp]: Shouldn't this one also be `-1.0`?

File: scene/animation/animation_tree.cpp [hunk 2]
```diff
@@ -77,7 +77,11 @@ void AnimationNode::set_parameter(const StringName &p_name, const Variant &p_val
 
 	const AHashMap<StringName, int>::Iterator it = property_cache.find(p_name);
 	if (it) {
-		process_state->tree->property_map.get_by_index(it->value).value.first = p_value;
+		Pair<Variant, bool> &parameter = process_state->tree->property_map.get_by_index(it->value).value;
```
Comment (akien-mga) [inline scene/animation/animation_tree.cpp]: (Very) nitpicky, but for the same code repeated at line 924 you're using `prop`, and `parameter` here, as the variable name. Could make sense to use the same name for consistency.

File: scene/animation/animation_blend_space_1d.cpp (hunk 1 above)
Comment (lyuma) [reply scene/animation/animation_blend_space_1d.cpp]: closest is Variant::INT, so I think -1 is correct. See above:
```
void AnimationNodeBlendSpace1D::get_parameter_list(List<PropertyInfo> *r_list) const {
	AnimationNode::get_parameter_list(r_list);
	r_list->push_back(PropertyInfo(Variant::FLOAT, blend_position));
	r_list->push_back(PropertyInfo(Variant::INT, closest, PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NONE));
}
```

Comment (akien-mga) [reply scene/animation/animation_blend_space_1d.cpp]: Makes sense.

I would suggest to maybe use explicit casts (`(int)-1`, `(double)0.0`) so that the intention is clear, and not leave it to chance whether we have a `.0` or not.

**Review by KoBeWi — APPROVED** [review]

File: scene/animation/animation_tree.cpp (hunk 2 above)
Comment (TokageItLab) [reply scene/animation/animation_tree.cpp]: Unified into `prop`.

File: scene/animation/animation_blend_space_1d.cpp (hunk 1 above)
Comment (TokageItLab) [reply scene/animation/animation_blend_space_1d.cpp]: Added (int) for some parameters.

**Comment by akien-mga** [comment]
Thanks!

**Comment by DarioSamo** [comment]
I'm getting a lot of error spam originating from this PR in the following demo from [here](https://github.com/godotengine/godot/pull/90284).

https://drive.google.com/file/d/1wg1PLTlc6pZs-HzFzQEGAkN3Oo7sqAfB/view?usp=sharing

Can I get a sanity check on whether this is a content issue that needs to be fixed or a false positive?

**Comment by sinewavey** [comment]
> I'm getting a lot of error spam originating from this PR in the following demo from [here](https://github.com/godotengine/godot/pull/90284).
> 
> https://drive.google.com/file/d/1wg1PLTlc6pZs-HzFzQEGAkN3Oo7sqAfB/view?usp=sharing
> 
> Can I get a sanity check on whether this is a content issue that needs to be fixed or a false positive?

I am also getting a huge amount of errors as well here after merging this commit into my own project and local build, though I have not been able to pinpoint exactly which objects are problematic yet either (beyond the fact it's in one (or more) of my Skeleton3D/animation player import from glb.

**Comment by TokageItLab** [comment]
@DarioSamo @sinewavey After investigating, it seems that there is a problem with the bool value of StateMachine and the state immediately after adding BlendSpace. It is probably a conflict with the parent class parameters, so the addition of else if is missing in some places. I will send an additional PR later.

**Comment by TokageItLab** [comment]
@DarioSamo @sinewavey I sent https://github.com/godotengine/godot/pull/107171, please check it.

**Comment by sinewavey** [comment]
@TokageItLab  The patch has cleared up errors on my end so far. Thank you!
