### PR TITLE
Mono: Fixes annotated signal loading in exported binaries

### LINKED ISSUE #19563: C# 3.0.3-stable signals not always triggering with exported binaries
**Godot version:**
3.0.3 Stable

**OS/device including version:**
Windows 10, Linux (Ubuntu 18) and OSX (macOS Sierra 10.12.6 - friend tested)

**Issue description:**
Problem is when you export a C# project, signals sometimes will not trigger. When I say sometimes I mean the debug version locally works flawlessly. On other pc's the debug has issue where my WeaponDischarged signal doesn't trigger. Release version on other pc's it'll work once or twice then fail to trigger the signals after trying to restart the game again.

I could've sworn this issue was fixed, but it seems like it's back

```
ERROR: emit_signal: Can't emit non-existing signal "WeaponDischarged".
    At: core/object.cpp:1139.
```

**Steps to reproduce:**
1. Create a game with signal usage. 
2. Export game
3. Watch console spit out errors about signal

**Minimal reproduction project:**
[SpaceShooter.zip](https://github.com/godotengine/godot/files/2102785/SpaceShooter.zip)
https://github.com/exts/godotsharp-shooter

Binaries: https://g4mr.itch.io/testing-godot

(Controls: WASD and SPACE, space to shoot)

### PR DESCRIPTION
**Pull request by exts**
Fixes #19563 can you review this @hpvb. I've tested on windows 10 so far so good.

### CODE REVIEW

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -1579,37 +1577,33 @@ bool CSharpScript::_update_exports() {
...
-		return false;
-
-	bool changed = false;
-
-	if (signals_invalidated) {
-		signals_invalidated = false;
+void CSharpScript::load_script_signals(GDMonoClass *scrp_class) {
 
-		GDMonoClass *top = script_class;
+	// no need to load the script's signals more than once
```
Comment (paulloz) [inline modules/mono/csharp_script.cpp]: Correct me if I'm wrong but this will prevent signal list to be updated in the editor when building after some code changes, as `signals_invalidated` is never reverted to `true`.  

Otherwise thanks for getting on this issue when I can't :+1: :+1: :+1:

**Comment by akien-mga** [comment]
Please squash the commits together, see http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

File: modules/mono/csharp_script.h [hunk 2]
```diff
@@ -111,7 +111,7 @@ class CSharpScript : public Script {
 
 	void _clear();
 
-	bool _update_signals();
+	void load_script_signals(GDMonoClass *scrp_class);
```
Comment (akien-mga) [inline modules/mono/csharp_script.h]: What does `scrp` mean? Script? Read-only parameters should start with `p_`, and I think `p_class` is good enough. If it needs to be more explicit, it would have to be `p_script_class`, not a mangled `scrp`.

File: modules/mono/csharp_script.cpp (hunk 1 above)
Comment (exts) [reply modules/mono/csharp_script.cpp]: Thanks for the suggestion, I re-added that check in the `reload_assemblies_if_needed` method before `reload` gets called now.

**Comment by exts** [comment]
@akien-mga I have no idea how to rebase this when git forced that merge with master as it won't show all changes. Should I just create a new branch with the changes based off master?

**Comment by akien-mga** [comment]
If you squash and rebase `exts:export_signals` on top of `godotengine:master`, it should have all changes included in the squash commit, which you can force push to `exts:export_signals`.

**Comment by exts** [comment]
Man I screwed something up because like I said when I rebased HEAD~10 it did not show anything after https://github.com/godotengine/godot/pull/19872/commits/54eb4a38b4bfb5dbce6e2e7e5614b1dc2e6e18cc this commit. So I aborted, tried HEAD~3 and it showed those commits now my local repo is all screwed up. I'm just going to create a new PR this is frustrating.

**Comment by hpvb** [comment]
LGTM

File: modules/mono/csharp_script.cpp [hunk 3]
```diff
@@ -2108,6 +2100,8 @@ Error CSharpScript::reload(bool p_keep_state) {
 
 			script_class->fetch_methods_with_godot_api_checks(native);
 
+			load_script_signals(script_class);
+
```
Comment (neikeq) [inline modules/mono/csharp_script.cpp]: This needs to be added to `CSharpScript::create_for_managed_type(GDMonoClass *)` as well. Also I would prefer it before the previous statement or after the while loop, since those two are related.

**Review by neikeq — CHANGES_REQUESTED** [review]

File: modules/mono/csharp_script.cpp (hunk 3 above)
Comment (exts) [reply modules/mono/csharp_script.cpp]: @neikeq alright I'm updating load_script_signals to accept another parameter to handle the `script->native`. Also moving load script below the while loop in both functions. compiling/testing now to make sure it works then ill push and rebase

**Comment by exts** [comment]
Alright I believe I made the necessary changes you requested @neikeq

**Comment by neikeq** [comment]
Thanks!
