### PR TITLE
Use multiple children in dock SplitContainers to make resizing consistent

### LINKED ISSUE #83348: Resizing Editor Docks is not consistent.
### Godot version

4.0, 4.1, 4.2.beta, all versions

### System information

Godot v4.2.beta (a574c0296) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3598) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

Adjusting the split between docks works differently depending on the one dragged. It is not symmetric, all docks to the right are scaled, the left ones aren't affected. 
This also applies anytime there is a hierarchy of `SplitContainer`s intended to work together.
Example:

godot_dock_resizing_issue1

The current behavior is not intuitive to the user and should be fixed.

related https://github.com/godotengine/godot-proposals/issues/7233#issuecomment-1625898356 
related https://github.com/godotengine/godot-proposals/issues/4033 

Also, I'm already working on a PR for this.

### Steps to reproduce

Adjust docks in the editor.
Or create multiple nested `SplitContainers` and see how resizing and dragging works between them.

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by kitbdev**
- supersedes #83359
- fixes #83348
- requires https://github.com/godotengine/godot/pull/90411

Affects Editor docks and the Debugger Stack Trace (ScriptEditorDebugger).
TileSet with TileSetAtlasSourceEditor can't take advantage of this since it is too nested

The CanvasItemEditor and Node3DEditor side panels are more niche and needs a plugin to test, so I can do it in another PR.

Editor dock layouts *should* work the same but I'm not sure if it will be in all scenarios.

godot multisplit

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -8756,9 +8741,10 @@ EditorNode::EditorNode() {
 	history_dock = memnew(HistoryDock);
 	editor_dock_manager->add_dock(history_dock);
 
-	// Add some offsets to left_r and main hsplits to make LEFT_R and RIGHT_L docks wider than minsize.
-	left_r_hsplit->set_split_offset(270 * EDSCALE);
-	main_hsplit->set_split_offset(-360 * EDSCALE);
```
Comment (kitbdev) [inline editor/editor_node.cpp]: This value -360 seems like an accidental leftover from https://github.com/godotengine/godot/pull/101787, since the default layout wasn't updated, so I just use the value it was before.

**Comment by Mickeon** [comment]
What happens to https://github.com/godotengine/godot/pull/83359? I suppose that with the SplitContainer change, this PR is much more favourable

**Comment by kitbdev** [comment]
> What happens to https://github.com/godotengine/godot/pull/83359? I suppose that with the SplitContainer change, this PR is much more favourable

The approach of allowing nested SplitContainers to work still has value in some cases, but it is currently rare in the Editor. It can be reconsidered in the future if we want to add that functionality.
However that PR needs a big rework even before multiple children were added, so it would need to be completely redone.
So I'll close that one for now.

File: editor/docks/editor_dock_manager.cpp [hunk 2]
```diff
@@ -232,6 +232,45 @@ void DockSplitContainer::remove_child_notify(Node *p_child) {
...
+	for (int i = 0; i < get_child_count(false); i++) {
+		Control *c = Object::cast_to<Control>(get_child(i, false));
+		if (!c || c->is_set_as_top_level()) {
+			continue;
+		}
+		// Count even if it is not visible.
+		if (c->is_visible() && p_layout->has_section_key(p_section, "dock_hsplit_" + itos(index + 1))) {
+			offsets.push_back(p_layout->get_value(p_section, "dock_hsplit_" + itos(index + 1)));
+		}
+		index++;
```
Comment (Mickeon) [inline editor/docks/editor_dock_manager.cpp]: Are we sure it's counting for invisible controls? The name `is_visible()` tells another story.

**Review by Mickeon — APPROVED** [review]
I approve of this myself, but I have not tested it. It does showcase how useful multiple children are in SplitContainer, as the overall code is less... split. Plus it matches our goal of making the editor increasingly more modular.

File: editor/docks/editor_dock_manager.cpp (hunk 2 above)
Comment (kitbdev) [reply editor/docks/editor_dock_manager.cpp]: The count is outside of the if statement. Maybe I should move the comment.

File: editor/docks/editor_dock_manager.h [hunk 3]
```diff
@@ -101,7 +104,7 @@ class EditorDockManager : public Object {
 
 	// To access splits easily by index.
 	Vector<DockSplitContainer *> vsplits;
-	Vector<DockSplitContainer *> hsplits;
+	DockSplitContainer *main_hsplit;
```
Comment (AThousandShips) [inline editor/docks/editor_dock_manager.h]:
```suggestion
	DockSplitContainer *main_hsplit = nullptr;
```

File: editor/docks/editor_dock_manager.cpp [hunk 4]
```diff
@@ -232,6 +232,46 @@ void DockSplitContainer::remove_child_notify(Node *p_child) {
...
+	PackedInt32Array so = get_split_offsets();
+	PackedInt32Array offsets;
+	int index = 0;
+	for (int i = 0; i < get_child_count(false); i++) {
+		Control *c = Object::cast_to<Control>(get_child(i, false));
+		if (!c || c->is_set_as_top_level()) {
+			continue;
+		}
+		if (c->is_visible() && so.size() > index) {
+			offsets.push_back(so[index]);
```
Comment (passivestar) [inline editor/docks/editor_dock_manager.cpp]:
```suggestion
			offsets.push_back(so[index] / EDSCALE);
```

They need to be stored unscaled because they are multiplied by scale on load.

Tested, works well besides that bug

File: editor/docks/editor_dock_manager.cpp [hunk 5]
```diff
@@ -232,6 +232,46 @@ void DockSplitContainer::remove_child_notify(Node *p_child) {
 	_update_visibility();
 }
 
+void DockSplitContainer::set_split_offsets_from_config(Ref<ConfigFile> p_layout, const String &p_section) {
+	PackedInt32Array offsets;
+	int index = 0;
+	for (int i = 0; i < get_child_count(false); i++) {
+		Control *c = Object::cast_to<Control>(get_child(i, false));
+		if (!c || c->is_set_as_top_level()) {
```
Comment (KoBeWi) [inline editor/docks/editor_dock_manager.cpp]:
```suggestion
		Control *c = as_sortable_control(get_child(i, false), SortableVisibilityMode::IGNORE);
		if (!c) {
```
Same below.

File: editor/docks/editor_dock_manager.cpp [hunk 6]
```diff
@@ -232,6 +232,46 @@ void DockSplitContainer::remove_child_notify(Node *p_child) {
...
+			continue;
+		}
+		if (c->is_visible() && so.size() > index) {
+			offsets.push_back(so[index] / EDSCALE);
+			index++;
+		} else {
+			offsets.push_back(0);
+		}
+		if (offsets.size() >= 4) {
```
Comment (KoBeWi) [inline editor/docks/editor_dock_manager.cpp]: Is there any way to avoid hard-coding `4`? Why is it even checked? It's not like more children will pass the first condition, no?

**Review by KoBeWi — APPROVED** [review]
Looks good, needs rebase.

File: editor/docks/editor_dock_manager.cpp (hunk 6 above)
Comment (kitbdev) [reply editor/docks/editor_dock_manager.cpp]: Its needed this because there are 5 children, so it was saving 5 entries. But this made me realize it is checking the center main screen container for visibility which isn't right. I'll switch to a different approach completely.

**Comment by akien-mga** [comment]
Thanks!
