### PR TITLE
FIX: Prevent crashing if `max_threads` is zero. (reverted)

### LINKED ISSUE #107733: WorkerThreadPool max thread count set to 0 produces index error and crash at start
### Tested versions

Godot 4.5beta1

### System information

Windows 10

### Issue description

If WorkerThreadPool  max thread count is set to `0` in the ProjectSettings it causes index errors at game start followed by a crash.

Expected would be that it would set itself to at least 1 thread as default as it does with all platforms that do not support threads.

### Steps to reproduce

Set WorkerThreadPool max thread count to 0 in the ProjectSettings.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by WinnerWind**
Prevents user from setting zero thread counts via GUI, and the worker thread pool will auto detect thread count if it is set to zero.

Fixes #107733 .

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -343,6 +343,10 @@ bool ProjectSettings::_set(const StringName &p_name, const Variant &p_value) {
 		}
 	}
 
+	if (p_name == StringName("threading/worker_pool/max_threads") && int(p_value) == 0) {
```
Comment (KoBeWi) [inline core/config/project_settings.cpp]: What's this check for? The change below should already handle this.

Comment (WinnerWind) [reply core/config/project_settings.cpp]: That check is to ensure that the value in the UI of the project manager, if it is set to `0`, will automatically set it to `-1`

In a way it is not needed and I could remove it, but it ensures that the user knows that `0` threads makes no sense and automatically set it to `-1`, which I feel is good UX

Comment (KoBeWi) [reply core/config/project_settings.cpp]: It can be mentioned in the property's description. Checking a hard-coded name every time a property is set isn't very efficient...

Comment (WinnerWind) [reply core/config/project_settings.cpp]: Alright, i'll make that change and edit the docs about it

Comment (WinnerWind) [reply core/config/project_settings.cpp]: Made the change, just compiling everything and testing the change before squashing & committing.

File: doc/classes/ProjectSettings.xml [hunk 2]
```diff
@@ -3404,7 +3404,7 @@
 			The ratio of [WorkerThreadPool]'s threads that will be reserved for low-priority tasks. For example, if 10 threads are available and this value is set to [code]0.3[/code], 3 of the worker threads will be reserved for low-priority tasks. The actual value won't exceed the number of CPU cores minus one, and if possible, at least one worker thread will be dedicated to low-priority tasks.
 		</member>
 		<member name="threading/worker_pool/max_threads" type="int" setter="" getter="" default="-1">
-			Maximum number of threads to be used by [WorkerThreadPool]. Value of [code]-1[/code] means [code]1[/code] on Web, or a number of [i]logical[/i] CPU cores available on other platforms (see [method OS.get_processor_count]).
+			Maximum number of threads to be used by [WorkerThreadPool]. Value of [code]-1[/code] or [code]0[/code] means [code]1[/code] on Web, or a number of [i]logical[/i] CPU cores available on other platforms (see [method OS.get_processor_count]).
```
Comment (KoBeWi) [inline doc/classes/ProjectSettings.xml]:
```suggestion
			Maximum number of threads to be used by [WorkerThreadPool]. Value of [code]0[/code] or less means [code]1[/code] on Web, or a number of [i]logical[/i] CPU cores available on other platforms (see [method OS.get_processor_count]).
```

**Review by KoBeWi — APPROVED** [review]

**Comment by WinnerWind** [comment]
Will squash changes when I'm back home

**Review by Repiteo — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by WinnerWind** [comment]
Glad to have helped!

**Comment by AThousandShips** [comment]
This broke physics (and possibly other things) on non-threaded Web builds, will make an issue report on Monday with further details but this is has triggered a regression

**Comment by WinnerWind** [comment]
Oh dear! I'm sorry that I didn't notice that.

**Comment by AThousandShips** [comment]
Seems to be caused by the way it handles threads and count, where it calls from `main.cpp` with `0` for argument in thread-less builds:
https://github.com/godotengine/godot/blob/73da0d20207f751cb8d1ec7922613b39dfc46b12/main/main.cpp#L1950-L1962

Which checks with this:
https://github.com/godotengine/godot/blob/73da0d20207f751cb8d1ec7922613b39dfc46b12/core/object/worker_thread_pool.cpp#L826-L828

Using this:
https://github.com/godotengine/godot/blob/73da0d20207f751cb8d1ec7922613b39dfc46b12/platform/web/os_web.cpp#L151-L157

So it went from taking `0` to `1`, so this probably just exposed a bug elsewhere, but this changes the behavior with no threads in `main.cpp`, unsure what the specific issues might be, but this is the specific trigger for it

I will look into it more tomorrow and make a report

**Comment by clayjohn** [comment]
@AThousandShips maybe this is the cause of https://github.com/godotengine/godot/issues/109914 too

**Comment by AThousandShips** [comment]
It seems that this is the result of some weird interactions with:
* https://github.com/godotengine/godot/pull/104458

I think this might be a bit tricky to fix without creating unexpected effects elsewhere, so I'd suggest reverting this and coordinating with @marcosc90 for a proper fix we can test during 4.6

It *could* be enough to change:
https://github.com/godotengine/godot/blob/73da0d20207f751cb8d1ec7922613b39dfc46b12/platform/web/os_web.cpp#L151-L157

Into:
```cpp
int OS_Web::get_default_thread_pool_size() const { 
#ifdef THREADS_ENABLED 
	return godot_js_os_thread_pool_size_get(); 
#else // No threads. 
	return 0; 
#endif 
}
```

But can't speak to possible other impacts of that

**Comment by WinnerWind** [comment]
I'll make a new PR to revert this tomorrow morning, first thing.

I didn't realize that such a small change created such a big chain reaction.
