### PR TITLE
Core: Fix built-in enum constant bindings

### LINKED ISSUE #99309: set_axis() expects a non-existing Enum Vector3.Axis
### Tested versions

Reproducible in: Godot 4.3

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.2799) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

[According to the docs](https://docs.godotengine.org/en/stable/classes/class_spritebase3d.html#class-spritebase3d-property-axis), the set_axis() function of the SpriteBase3D node expects a "Vector3.Axis" enum. The link to that enum is active in the in-engine docs, but not in the web docs. If you navigate [to the Vector3 docs](https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3), you'll see that an Axis enum doesn't exist, only three separate constants.

This would be just a documentation issue, but the result is that there is no valid enum that set_axis() would accept, and I believe having to use an int there would be bad practice. Moreover, the editor's behavior here depends on how the Sprite in question is referenced, which is the most confusing part for me:

`$Sprite3D.set_axis(Vector3.AXIS_Y) # This works`

```
@onready var sprite : Sprite3D = $Sprite3D # Explicit casting as Sprite3D is what seems to be causing the error
# in any function, i.e. _ready():
sprite.set_axis(Vector3.AXIS_Y) # This triggers warnings
```

The warnings this latter example triggers are as follows:

```
W 0:00:04:0562   Integer used when an enum value is expected. If this is intended cast the integer to the enum type.
  <GDScript Error>INT_AS_ENUM_WITHOUT_CAST
  <GDScript Source>node_3d.gd:7
W 0:00:04:0563   Cannot pass 1 as Enum "Axis": no enum member has matching value.
  <GDScript Error>INT_AS_ENUM_WITHOUT_MATCH
  <GDScript Source>node_3d.gd:7
```

I believe that at the very least the Sprite3D docs should be modified to reflect the intended use, but ideally set_axis() should accept existing enums (whether it means reimplementing Vector3.Axis or making it understand the AXIS constants) without warnings.

### Steps to reproduce

See the MRP. To reproduce it yourself:
- Set up a 3D scene.
- Create a Sprite3D and cast it as Sprite3D in the script.
- Address the resulting variable in the script with set_axis(). The prompt will suggest using the Vector3.Axis enum. Type "Vector3" and choose any AXIS const (AXIS_X, AXIS_Y, AXIS_Z) from the prompt.
- Run the scene and see the warnings. 

### Minimal reproduction project (MRP)

[axis-test.zip](https://github.com/user-attachments/files/17783891/axis-test.zip)

### LINKED ISSUE #99531: Godot4.4-dev5: Breaks my mock implementation, `get_method_list` provides invalid method info for `get_primary_rotation_axis`
### Tested versions

v4.4.dev5.mono.official [9e6098432]

### System information

All

### Issue description

I'm providing a mocking util for testing in my plugin GdUnit4 and the test are broken now.
My tests try to mock all Godot classes, and it fails now on `LookAtModifier3D#get_primary_rotation_axis`
The method is documented as
Image

But the `Vector3` has no enum `Axis` defined.

### Steps to reproduce

Run the script to check the provided method info.

```gd
extends Node


func _ready() -> void:
	get_method_info()
	get_tree().quit()


func get_method_info() -> void:
	var modifier := LookAtModifier3D.new()


	var axis := modifier.get_primary_rotation_axis()
	prints("get_primary_rotation_axis value:", axis, "return type:", typeof(axis))

	var methods := modifier.get_method_list()
	var mi_get_primary_rotation_axis := methods.filter(func(m :Dictionary) -> bool:
		return m["name"] == "get_primary_rotation_axis"
	)
	prints(mi_get_primary_rotation_axis[0]["return"])

```
The output is:
```
get_primary_rotation_axis value: 1 return type: 2
{ "name": "", "class_name": &"Vector3.Axis", "type": 2, "hint": 0, "hint_string": "", "usage": 65542 }
```

I use the provided method info to build the mocking class, and it will not be compiling about missing enum `Vector3.Axis`

e.g. use a valid script code will show the compile error
`var axis_typed :Vector3.Axis = modifier.get_primary_rotation_axis()`

**Parse Error: Built-in types don't contain nested types.**
Same issues for all classes inherits from `SpriteBase3D`

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #99309.
* Fixes #99531.
* Supersedes #99341.

### CODE REVIEW

**Comment by dalexeev** [comment]
Note: I have not checked the GDExtension and C# binding generators, `tests/core/object/test_class_db.h`.

**Comment by Bromeon** [comment]
[Here](https://gist.github.com/Bromeon/9ec46ef2b3a8251a3c5300ab82ec0135) is the diff of `extension_api.json` from the previous commit. The `AXIS_*` and `PLANE_*` constants are removed as expected. I added some context, so the `enums` are visible -- which already contain the same identifiers.


> Also let me know if this change is breaking (I don't know if enum members falling into outer scope is supported in C# and GDExtension).

A GDExtension binding may technically need an update in the code generator (or an API dependent on it), if constants are missing -- but since the values are still there as enum variants, migration should be straightforward. And since both are passed as numbers to the actual GDExtension C API, binary compatibility shouldn't be broken. Which is the important part, because it means existing plugins will keep working with Godot 4.4 without recompilation.

So from my side this is a welcome improvement! :+1:

**Review by Mickeon — COMMENTED** [review]
On the documentation side this is a big plus too

File: modules/mono/editor/bindings_generator.cpp [hunk 1]
```diff
@@ -5039,24 +5039,6 @@ void BindingsGenerator::_populate_global_constants() {
...
-		// These enums are not generated and must be written manually (e.g.: Vector3.Axis)
-		// Here, we assume core types do not begin with underscore
-		TypeInterface enum_itype;
-		enum_itype.is_enum = true;
-		enum_itype.name = enum_cname.operator String();
-		enum_itype.cname = enum_cname;
-		enum_itype.proxy_name = pascal_to_pascal_case(enum_itype.name);
-		TypeInterface::postsetup_enum_type(enum_itype);
-		enum_types.insert(enum_itype.cname, enum_itype);
-	}
```
Comment (raulsntos) [inline modules/mono/editor/bindings_generator.cpp:5059]: The Vector types are intentionally declared manually in C#, so these enums should still be hardcoded. Otherwise, generated API will use `int` instead of the enum types which is worse and also breaks compat.

Comment (dalexeev) [reply modules/mono/editor/bindings_generator.cpp:5059]: Could the binding generator use the following API to generate this without hardcoding?

https://github.com/godotengine/godot/blob/6206fd5764d99bfbec4e73377428560d3caa0d20/core/variant/variant.h#L800-L804

Also note that `Projection.Planes`, `Vector4.Axis`, and `Vector4i.Axis` are missing.

**Review by dsnopek — APPROVED** [review]
Approval for the impact on GDExtension only

File: modules/mono/editor/bindings_generator.cpp (hunk 1 above)
Comment (raulsntos) [reply modules/mono/editor/bindings_generator.cpp:5059]: It should be possible yeah, we can just iterate all the Variant types here and then get all their enums and add them to `enum_types`. Something like this (I haven't tested it):

```C++
for (int i = 0; i < Variant::VARIANT_MAX; i++) {
	if (i == Variant::OBJECT) {
		continue;
	}

	Variant::Type type = Variant::Type(i);

	List<StringName> enum_names;
	Variant::get_enums_for_type(type, &enum_names);

	for (const StringName &enum_name : enum_names) {
		TypeInterface enum_itype;
		enum_itype.is_enum = true;
		enum_itype.name = Variant::get_type_name(type) + "." + enum_name;
		enum_itype.cname = enum_itype.name;
		enum_itype.proxy_name = pascal_to_pascal_case(enum_itype.name);
		TypeInterface::postsetup_enum_type(enum_itype);
		enum_types.insert(enum_itype.cname, enum_itype);
	}
}
```

> Also note that `Projection.Planes`, `Vector4.Axis`, and `Vector4i.Axis` are missing.

That's true, these types were added later so it looks like we missed them. That said, it looks like only `Vector3.Axis` is used in Godot APIs, so it's the only one that really matters right now. It would be nice to add the others for future-proofing though.

**Review by raulsntos — APPROVED** [review]
The C# changes look good to me. I tested it and the generated bindings look as expected.

**Review by akien-mga — APPROVED** [review]
Looks great to me!

**Comment by Repiteo** [comment]
Thanks!
