### PR TITLE
Fixed node not renaming when clicking elsewhere on the scene tree

### LINKED ISSUE #51725: Node's renaming does not applied when clicking outside of the context field of the Scene Tree
### Godot version

3e7a545ecf9194891ef0fd774159ddfa4cebf5f6

### System information

Windows 10

### Issue description

Attempting to rename node in the Scene Tree and clicking outside of context does not apply this rename:

renaming_bug

This is a regression because 3.x allows doing this.

### Steps to reproduce

GIF above ^^

### Minimal reproduction project

No need.

### PR DESCRIPTION
**Pull request by ThreeRhinosInAnElephantCostume**
Fixes #51725

To be more exact, this issue only occurs when clicking the scene tree, clicking anywhere else renames the node just fine.

The issue seems to be caused by a kind of "race condition" where the scene tree updates, removing the textbox containing the new name,  before `_renamed` can be called.

I fixed it by making `_renamed` non-deferred. There might be a deeper issue at play here, but diagnosing it is beyond my current understanding of the engine and my fix seems to be working just fine.

### CODE REVIEW

File: editor/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1206,11 +1206,10 @@ SceneTreeEditor::SceneTreeEditor(bool p_label, bool p_can_rename, bool p_can_ope
 	}
 
 	tree->connect("cell_selected", callable_mp(this, &SceneTreeEditor::_selected_changed));
-	tree->connect("item_edited", callable_mp(this, &SceneTreeEditor::_renamed), varray(), CONNECT_DEFERRED);
```
Comment (Chaosus) [inline editor/scene_tree_editor.cpp:1209]: You can omit `varray()` parameter too if it's empty.

File: editor/scene_tree_editor.cpp [hunk 2]
```diff
@@ -1206,11 +1206,10 @@ SceneTreeEditor::SceneTreeEditor(bool p_label, bool p_can_rename, bool p_can_ope
...
+	tree->connect("item_edited", callable_mp(this, &SceneTreeEditor::_renamed), varray());
```
Comment (Chaosus) [inline editor/scene_tree_editor.cpp:1209]: You can omit varray() parameter too if it's empty.

Comment (ThreeRhinosInAnElephantCostume) [reply editor/scene_tree_editor.cpp:1209]: Done. Seems to work just fine. 
As a side-note, should I have pushed this as a separate commit instead of squashing it?

Comment (Chaosus) [reply editor/scene_tree_editor.cpp]: No, you need to squash it. The practice of non-squashing is only for an advanced contribution where it's important to differentiate between the commits (and even then it can be avoided).

**Review by Chaosus — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
