### PR TITLE
Don't expose AnimationNodeStartState and AnimationNodeEndState as internal, this triggers a ClassDB bug

### LINKED ISSUE #99534: Godot4.4-dev5: `ClassDB` provides classes where not exists/accessible
### Tested versions

v4.4.dev5.mono.official [9e6098432]

### System information

all

### Issue description

I iterate over all classes provided by `ClassDB` for testing. Using `ClassDB:get_class_list()`
With Godot4.4.dev5 there is now “AnimationNodeStartState”, “AnimationNodeEndState” there are not documented and cannot be instantiated.

### Steps to reproduce

Can be verified by
```
extends Node

func _ready() -> void:
	prints("AnimationNodeStartState class_exists:", ClassDB.class_exists("AnimationNodeStartState"))
	prints("AnimationNodeStartState can_instantiate:", ClassDB.can_instantiate("AnimationNodeStartState"))

        # compile error
	AnimationNodeStartState.new()
```
output:
```
AnimationNodeStartState class_exists: true
AnimationNodeStartState can_instantiate: true
````
errors:
```
 res://test.gd:7 - Parse Error: Native class GDScriptNativeClass used in script doesn't exist or isn't exposed.
  res://test.gd:7 - Parse Error: Static function "new()" not found in base "GDScriptNativeClass".
```

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #99534.

Please test to confirm the functionality still works, I don't know how to use of it.

### CODE REVIEW

File: scene/animation/animation_node_state_machine.cpp [hunk 1]
```diff
@@ -1322,7 +1322,8 @@ bool AnimationNodeStateMachine::are_ends_reset() const {
 
 bool AnimationNodeStateMachine::can_edit_node(const StringName &p_name) const {
 	if (states.has(p_name)) {
-		return !(states[p_name].node->is_class("AnimationNodeStartState") || states[p_name].node->is_class("AnimationNodeEndState"));
+		const Ref<AnimationNode> &anode = states[p_name].node;
+		return !(Ref<AnimationNodeStartState>(anode).is_valid() || Ref<AnimationNodeEndState>(anode).is_valid());
```
Comment (akien-mga) [inline scene/animation/animation_node_state_machine.cpp:1326]: Note that I didn't actually check whether this needed to change to work. But in general relying on casting pointers seems better than a string check through ClassDB.

**Comment by fire** [comment]
@TokageItLab Can you take a look?

**Review by TokageItLab — APPROVED** [review]
Tested and confirmed that delete and other operations are prevented correctly for them.
