### PR TITLE
Fix 2D viewport texture drop issue with global history registration

### LINKED ISSUE #86826: Dropping a texture in empty scene creates a global action that can erase other scenes
### Tested versions

4.3 dev, but probably exists since 4.0

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you drop a texture to 2D viewport and the scene has no root, the newly created node will be set as root, but the action is registered in global history. If you undo it and redo *on another scene*, the newly created node will replace the root of current scene:

https://github.com/godotengine/godot/assets/2223172/c4676c44-6e50-4a4f-945a-1c1127ac7f97

Trying to undo this operation will result in empty scene. You need to revert it to restore the original content.

### Steps to reproduce

1. Open a non-empty scene
2. Create new scene
3. In the new scene, drop a texture file into 2D view
4. Undo
5. Go back to the first scene
6. Redo

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by alessandrofama**
This fix addresses an issue where dropping a texture onto the 2D viewport in a scene without a root node incorrectly registers the action in the global history. Subsequently undoing and redoing this action in another scene results in the newly created node replacing the root of the current scene. Fixes #86826.

Fix video:

https://github.com/godotengine/godot/assets/26153311/886dbb96-3017-4702-bf8d-fee70b668b72

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -5842,7 +5842,7 @@ void CanvasItemEditorViewport::_perform_drop_data() {
 	Vector<String> error_files;
 
 	EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
-	undo_redo->create_action(TTR("Create Node"));
+	undo_redo->create_action_for_history(TTR("Create Node"), EditorNode::get_singleton()->get_editor_data().get_current_edited_scene_history_id());
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:5845]:
```suggestion
	undo_redo->create_action_for_history(TTR("Create Node"), EditorNode::get_editor_data().get_current_edited_scene_history_id());
```
This method is static.

**Review by KoBeWi — APPROVED** [review]

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (alessandrofama) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Fixed 👍
