### PR TITLE
Check if the required texture format is imported in the export dialog

### LINKED ISSUE #78395: Incorrect (?) warning about enabling S3TC BPTC texture compression on macOS export
### Godot version

4.1.beta2

### System information

macOS 13.3.1 mobile renderer

### Issue description

When setting up an export preset for macOS in a project where the Import S3TC BPTC setting is not enabled you get a warning that this platform requires this to be enabled. 

Screenshot 2023-06-18 at 11 37 03

However, if you check the documentation for this project setting, it seems that this is not required at all, and it's actually very unclear (to me) what enabling it will actually change.

Screenshot 2023-06-18 at 12 47 11

As I understand this description the platform will use the format if it requires it even if the setting is disabled (so it doesn't matter). In this case the macOS export warning should be removed. If however this is required the description text also seems to note that just enabling this will do nothing, you also need to re-import all your textures for this to take effect. So just enabling the setting wouldn't be enough?

The setting is for the full project, so if you have a project with exports for both mobile and desktop I guess you need to have it turned off since it's not supported on mobile? So if it is indeed required on some desktop systems perhaps there's need for a mobile version of this setting to have it disabled there? Or just get rid of the setting entirely if this is handled automatically anyway to avoid this confusion?

### Steps to reproduce

- Have a project where the Import S3TC BPTC setting is not enabled in the project settings
- Set up a macOS export preset
- Observe warning (and read setting documentation)

### Minimal reproduction project

[Simple macOS export project](https://www.lostminds.com/godot/MacExportPermissionsTest.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
Before, the export dialog only cared about if the *setting* is enabled.

Now, it cares whether the format is actually imported. Fixes #78395.

I created 2 new files `resource_importer_texture_settings.{h,cpp}` for this, since I did not know if there was any better place for this to exist. Before reviewing you should also look at #78457 to see how it will be used in the near future.

### CODE REVIEW

File: editor/import/resource_importer_texture.cpp [hunk 1]
```diff
@@ -38,6 +38,7 @@
 #include "editor/editor_node.h"
 #include "editor/editor_scale.h"
 #include "editor/editor_settings.h"
+#include "resource_importer_texture_settings.h"
```
Comment (akien-mga) [inline editor/import/resource_importer_texture.cpp:41]: Use absolute paths for editor includes (`editor/import/resource_importer_texture-settings.h`).

File: editor/import/resource_importer_layered_texture.cpp [hunk 2]
```diff
@@ -38,6 +38,7 @@
 #include "editor/editor_file_system.h"
 #include "editor/editor_node.h"
 #include "resource_importer_texture.h"
+#include "resource_importer_texture_settings.h"
```
Comment (akien-mga) [inline editor/import/resource_importer_layered_texture.cpp:41]:
```suggestion
#include "editor/import/resource_importer_texture.h"
#include "editor/import/resource_importer_texture_settings.h"
```

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]
Looks good to me! The changes are simple and have a very low risk of breaking something else. Let's go ahead and merge this for 4.1

**Comment by YuriSizov** [comment]
Thanks!
