### PR TITLE
Restructure and reimplement v-sync options

### LINKED ISSUE #1283: Add support for adaptive V-Sync
**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

Traditional V-Sync is able to eliminate tearing, but will introduce stuttering if the device can't keep up with the monitor's refresh rate. For instance, with a 60 Hz monitor, getting 50 FPS will display 40 frames at full speed, but 10 frames in that second will be displayed for twice as long. This makes the game look like it's effectively running at 30 FPS during those stuttering periods. The default V-Sync behavior can also lead to [confusion](https://github.com/godotengine/godot/issues/40909).

Variable refresh rate monitors can solve this issue. While they've been on the rise lately, not everyone has access to such a monitor, especially in laptops where the display typically can't be upgraded.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

*Note that adaptive V-Sync can be used on any monitor and has no relation to G-Sync or FreeSync. [This video from Digital Foundry](https://www.youtube.com/watch?v=seyAzw9zEoY) should be helpful to clear confusion about the various V-Sync modes available out there.*

Compared to variable refresh rate monitors, adaptive V-Sync is a slightly older technique, being popularized in the early 2010s. It works by automatically disabling V-Sync if the FPS goes below the monitor refresh rate. This introduces tearing, but avoids stuttering and decreases input lag in periods where the game doesn't run as smoothly. This is usually a better compromise in those situations.

V-Sync will enable itself again automatically once the FPS goes back above the monitor refresh rate.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

The V-Sync project setting and associated RenderingServer property should be converted from a boolean to an enum with the following values: "Disabled", "Enabled (Traditional)", "Enabled (Adaptive)".

We should also evaluate making adaptive V-Sync the default as it can significantly improve the player's experience. Likewise, it should also make the editor feel smoother and more reactive in heavier scenes.

See also this pull request: https://github.com/godotengine/godot/pull/36862

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, as implementing adaptive V-Sync requires changes to the core rendering code. The user may be able to force adaptive V-Sync in their graphics driver control panel, but this relies on OS- and hardware-specific features not always available on macOS or Linux.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Implementing adaptive V-Sync requires changes to the core rendering code.

### LINKED ISSUE #36467: Vulkan: disabling V-Sync not reimplemented yet
**Godot version:** Git https://github.com/godotengine/godot/commit/bf7d6de55662d7f4f9e82e69920582cf8ec55375

**OS/device including version:** Fedora 31, NVIDIA 440.44, GeForce GTX 1080

**Issue description:** V-Sync is always enabled, even if you disable it in the Project Settings then restart the editor.

**Steps to reproduce:** Try disabling **Display > Window > Vsync > Use Vsync** in the Project Settings.

### PR DESCRIPTION
**Pull request by Geometror**
This PR is a complete reorginization of the v-sync related code for DisplayServers with the changes discussed here and on IRC. So it's no longer a reimplementation of PR #36862, altough @giarve's work was very helpful.

- Adds a v-sync mode setting which allows to choose between DISABLED, ON, ADAPTIVE and MAILBOX (fixes #36467, fixes godotengine/godot-proposals#1283)
	-> can be modified via project settings or via code at runtime [for Windows, Linux and OSX]
	-> fallback to VK_PRESENT_MODE_FIFO_KHR if the desired mode is not supported
	-> No engine restart is required for a change of the vsync-mode setting
- Removed the v-sync via compositor option as it was problematic (as suggested by @Calinou)

### CODE REVIEW

**Comment by Geometror** [comment]
Rebased and partly restructured, 
vsync setting is now read in Main::setup2 + removed dead code in OS

What is the plan for vsync_via_compositor in 4.0? The code regarding vsync_via_compositor is currently dead in master.

**Comment by Calinou** [comment]
> What is the plan for vsync_via_compositor in 4.0? The code regarding vsync_via_compositor is currently dead in master.

I think it would be better to remove it, as it doesn't work correctly for everyone. It causes the framerate to halve unexpectedly on some setups.

**Comment by Geometror** [comment]
Ok, I removed the V-Sync via Compositor option entirely, now its ready for review :)

**Comment by clayjohn** [comment]
Looks interesting, but is this not just a reimplementation of https://github.com/godotengine/godot/pull/36862? See this comment https://github.com/godotengine/godot/pull/36862#issuecomment-765469169 for reduz' response to that PR. 

I echo reduz' concern and I am not certain that just grabbing the first available V-sync format is the proper way to expose vsync to users. 

Can you elaborate why this is the best approach for exposing v-sync? Please pardon my ignorance if it is something obvious.

**Comment by Geometror** [comment]
It is a reimplementation of #36862, but moved to DisplayServer as requested by reduz. In addition I removed the broken vsync via compositor option.
Managing v-sync that way(choosing the first available v-sync present mode) could keep it simple and uniform between Vulkan and the upcoming GL ES renderer. As giarve mentioned VK_PRESENT_MODE_FIFO_KHR in #36862 is the only mode required to be supported, so it makes sense to prefer it over the others as the driver may support it the best. However, I think providing the user with an option to choose the prefered mode would be a good idea. (mainly between MAILBOX[could reduce input lag] and FIFO[guaranteed supported], FIFO_RELAXED isn't that useful imo) 
Do you think that would be a better way to expose vsync to users?

**Comment by clayjohn** [comment]
I'm not certain what the best way to expose the vsync settings to the user is. 

I don't think falling back to ``VK_PRESENT_MODE_FIFO_RELAXED_KHR`` makes sense when a user disables v-sync but does not support ``VK_PRESENT_MODE_IMMEDIATE_KHR``.

I think one option may be to have a toggle (between on and off, if ``VK_PRESENT_MODE_IMMEDIATE_KHR`` is not available then try the selected v-sync mode) and a dropdown menu (for v-sync mode, defaulting to ``VK_PRESENT_MODE_FIFO_KHR`` and falling back to ``VK_PRESENT_MODE_FIFO_KHR`` if selected mode is unavailable). 

That being said, I'm not sure that it makes sense to do it like that, for android it looks like ``VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR`` or ``VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR`` may be more suitable when v-sync is disabled (because ``VK_PRESENT_MODE_IMMEDIATE_KHR`` is [never available](https://vulkan.gpuinfo.org/listsurfacepresentmodes.php?platform=android))

**Comment by Geometror** [comment]
Ok, I will look into that. By digging through the codebase I found out that it is more work than I initially thought, so I should change this PR to a draft as there are still some things to decide, restructure and implement. Maybe I should ask reduz if he has concrete plans for v-sync atm.

**Comment by clayjohn** [comment]
@Geometror that is a good idea. Reduz typically has some ideas for this kind of stuff, and it is important to work on soon as we are approaching alpha.

**Comment by Geometror** [comment]
Reimplemented after discussion on IRC with @Calinou, @reduz and @lawnjelly 
The v-sync option is now represented as an enum and implemented on all available platforms, for a summary of all final changes see my edited initial comment (https://github.com/godotengine/godot/pull/48622#issue-638265155)

Could someone test it on Linux and OSX?

**Comment by Calinou** [comment]
Testing again on Linux + NVIDIA:

### Disabled

image

### On

image

The reported FPS is pretty much always 143-144 FPS.

### Adaptive

image

Interestingly, the FPS reported is slightly higher than my monitor's refresh rate (144 Hz). It can go up to 148 FPS.

### Mailbox (Triple Buffering)

image

**Note:** When changing the project setting, press <kbd>Ctrl + S</kbd> *twice* to make sure the setting is saved. This is an editor bug unrelated to this PR.

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -1114,8 +1114,8 @@ ProjectSettings::ProjectSettings() {
 
 	_add_builtin_input_map();
 
-	// Keep the enum values in sync with the `DisplayServer::ScreenOrientation` enum.
 	custom_prop_info["display/window/handheld/orientation"] = PropertyInfo(Variant::INT, "display/window/handheld/orientation", PROPERTY_HINT_ENUM, "Landscape,Portrait,Reverse Landscape,Reverse Portrait,Sensor Landscape,Sensor Portrait,Sensor");
+	custom_prop_info["display/window/vsync/vsync_mode"] = PropertyInfo(Variant::STRING, "display/window/vsync/vsync_mode", PROPERTY_HINT_ENUM, "disabled,on,adaptive,mailbox/triple buffering");
```
Comment (Calinou) [inline core/config/project_settings.cpp:1118]: Capitalize every value for consistency with other property hints, and rename "On" to "Enabled" to put it in contrast with "Disabled":

```suggestion
	custom_prop_info["display/window/vsync/vsync_mode"] = PropertyInfo(Variant::STRING, "display/window/vsync/vsync_mode", PROPERTY_HINT_ENUM, "Disabled,Enabled,Adaptive,Mailbox (Triple Buffering)");
```

**Review by Calinou — CHANGES_REQUESTED** [review]

**Comment by bruvzg** [comment]
Tested it on macOS 11.4 with AMD FirePro D300:
* Disabled - runs with unlimited FPS (300-340 FPS).
* All other options - runs at constant FPS equal to double display refresh rate, 120 FPS if display is set to 60 Hz, 60 FPS if it's set to 30 Hz (tested with two different hiDPI and loDPI displays).

File: core/config/project_settings.cpp (hunk 1 above)
Comment (Geometror) [reply core/config/project_settings.cpp]: Ok, changed and replaced "Mailbox(Tripple Buffering)" with just "Mailbox" like @lawnjelly suggested as true triple buffering in Vulkan is only achieved with three images in the swapchain, although it has a similar effect. (I forgot to rename that property earlier)

**Comment by Geometror** [comment]
@bruvzg By looking at the code again it seems like the fallback to the guaranteed supported FIFO present mode works correctly, so your graphics card/driver might not support FIFO_RELAXED or MAILBOX. However, the framerate which is double of the display's refresh rate is weird, likely a driver issue. 

@Calinou With the first 3 modes I got the same results. But in Mailbox mode a basic scene like yours runs close to the framerate with v-sync disabled (around 3000 FPS) on my machine(Windows 10/NVIDIA). That is a little weird, but it could be also a driver issue...

File: servers/display_server.cpp [hunk 2]
```diff
@@ -305,29 +304,13 @@ void DisplayServer::set_icon(const Ref<Image> &p_icon) {
 	WARN_PRINT("Icon not supported by this display server.");
 }
 
-void DisplayServer::_set_use_vsync(bool p_enable) {
-	WARN_PRINT("VSync not supported by this display server.");
+void DisplayServer::window_set_vsync_mode(DisplayServer::VSyncMode p_vsync_mode, WindowID p_window) {
+	WARN_PRINT("Changing the VSync mod is not supported by this display server.");
```
Comment (bruvzg) [inline servers/display_server.cpp:308]:
```suggestion
	WARN_PRINT("Changing the VSync mode is not supported by this display server.");
```

File: servers/display_server.cpp [hunk 3]
```diff
@@ -305,29 +304,13 @@ void DisplayServer::set_icon(const Ref<Image> &p_icon) {
...
-}
-
-void DisplayServer::vsync_set_use_via_compositor(bool p_enable) {
-	WARN_PRINT("VSync via compositor not supported by this display server.");
-}
-
-bool DisplayServer::vsync_is_using_via_compositor() const {
-	return false;
+DisplayServer::VSyncMode DisplayServer::window_get_vsync_mode(WindowID p_window) const {
+	WARN_PRINT("Changing the VSync mod is not supported by this display server.");
```
Comment (bruvzg) [inline servers/display_server.cpp:312]:
```suggestion
	WARN_PRINT("Changing the VSync mode is not supported by this display server.");
```

**Comment by lawnjelly** [comment]
Just out of interest, and as someone who isn't really familiar with this area :smile: .. is 'adaptive' a better name in some way that just using the vulkan name RELAXED or FIFO_RELAXED?

With a quick google search it seems the name adaptive (apart from being a non-specific term, and seeming to describe anything that isn't on or off) seems as though it could be confusing as it is used for at least 2 different methods:
https://en.wikipedia.org/wiki/FreeSync
https://www.asus.com/support/FAQ/1009271/

> ASUS FreeSync product is certified by both AMD and VESA standard, so it can be called as VESA Adaptive-Sync as well.

FreeSync / VESA Adaptive-Sync seems to be designed to avoid tearing on suitable monitors.

Here nvidia use the word 'adaptive' to describe something closer to FIFO_RELAXED:
https://www.nvidia.com/en-gb/geforce/technologies/adaptive-vsync/

> VK_PRESENT_MODE_FIFO_RELAXED_KHR:
This mode only differs from the previous one if the application is late and the queue was empty at the last vertical blank. Instead of waiting for the next vertical blank, the image is transferred right away when it finally arrives. This may result in visible tearing.

https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain#page_Presentation-mode

File: main/main.cpp [hunk 4]
```diff
@@ -1329,7 +1306,26 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
+		} else if (vsync_mode == "Adaptive") {
+			print_line("<<Adaptive");
+			window_vsync_mode = DisplayServer::VSYNC_ADAPTIVE;
+		} else if (vsync_mode == "Mailbox") {
+			print_line("<<Mailbox");
+			window_vsync_mode = DisplayServer::VSYNC_MAILBOX;
+		} else {
+			print_line("v-sync mode unknown.");
+			window_vsync_mode = DisplayServer::VSYNC_ENABLED;
+		}
```
Comment (bruvzg) [inline main/main.cpp:1327]: It's probably better to use `print_verbose` (need some code rearrangement, since `verbose` flag is set on the line 1344).

Comment (Geometror) [reply main/main.cpp]: Oh, forgot to remove those print_line statements. They were just for debugging, so i removed the first four and replaced the last one with WARN_PRINT.

**Comment by Geometror** [comment]
@lawnjelly I understand your point with all these branded synchronization techniques, but I think Adaptive VSync is more clear than FIFO_RELAXED since it behaves similar across rendering APIs (so it would be the same for a possible GLES fallback renderer) and is widely known as "VSync off when framerate falls below screens refresh rate, VSync on if it stays above". However, I updated the documentation so that the user gets a simple summary on how it behaves.

**Comment by Geometror** [comment]
Rebased and fixed to compile again after the DisplayServerHeadless addition.

File: doc/classes/DisplayServer.xml [hunk 5]
```diff
@@ -1143,5 +1137,13 @@
...
 		<constant name="WINDOW_EVENT_DPI_CHANGE" value="6" enum="WindowEvent">
 		</constant>
+		<constant name="VSYNC_DISABLED" value="0" enum="VSyncMode">
+		</constant>
+		<constant name="VSYNC_ENABLED" value="1" enum="VSyncMode">
+		</constant>
+		<constant name="VSYNC_ADAPTIVE" value="2" enum="VSyncMode">
+		</constant>
+		<constant name="VSYNC_MAILBOX" value="3" enum="VSyncMode">
+		</constant>
```
Comment (clayjohn) [inline doc/classes/DisplayServer.xml:1147]: These should be filled out

File: doc/classes/ProjectSettings.xml [hunk 6]
```diff
@@ -443,7 +443,7 @@
 		</member>
 		<member name="debug/settings/fps/force_fps" type="int" setter="" getter="" default="0">
 			Maximum number of frames per second allowed. The actual number of frames per second may still be below this value if the game is lagging.
-			If [member display/window/vsync/use_vsync] is enabled, it takes precedence and the forced FPS number cannot exceed the monitor's refresh rate.
+			If [member display/window/vsync/vsync_mode] is set to ENABLED or ADAPTIVE, it takes precedence and the forced FPS number cannot exceed the monitor's refresh rate.
```
Comment (clayjohn) [inline doc/classes/ProjectSettings.xml:446]:
```suggestion
			If [member display/window/vsync/vsync_mode] is set to [code]ENABLED[/code] or [code]ADAPTIVE[\code], it takes precedence and the forced FPS number cannot exceed the monitor's refresh rate.
```

File: doc/classes/ProjectSettings.xml [hunk 7]
```diff
@@ -530,12 +530,11 @@
...
-		</member>
-		<member name="display/window/vsync/vsync_via_compositor" type="bool" setter="" getter="" default="false">
-			If [code]Use Vsync[/code] is enabled and this setting is [code]true[/code], enables vertical synchronization via the operating system's window compositor when in windowed mode and the compositor is enabled. This will prevent stutter in certain situations. (Windows only.)
-			[b]Note:[/b] This option is experimental and meant to alleviate stutter experienced by some users. However, some users have experienced a Vsync framerate halving (e.g. from 60 FPS to 30 FPS) when using it.
+		<member name="display/window/vsync/vsync_mode" type="String" setter="" getter="" default="&quot;Enabled&quot;">
+			Sets the VSync mode for the main game window.
+			With [code]Enabled[/code] and [code]Mailbox[/code] the image is displayed only on vertical blanking periods, so no tearing is visible.
+			[code]Adaptive[/code] behaves like disabled VSync when the framerate drops below the screen's refresh rate to reduce stuttering(although tearing may be visible), otherwise VSync is enabled to avoid tearing.
```
Comment (clayjohn) [inline doc/classes/ProjectSettings.xml:536]:
```suggestion
			[code]Adaptive[/code] behaves like [code]DISABLED[/code] VSync when the framerate drops below the screen's refresh rate to reduce stuttering(although tearing may be visible), otherwise VSync is enabled to avoid tearing.
```

File: drivers/vulkan/vulkan_context.cpp [hunk 8]
```diff
@@ -1304,16 +1304,41 @@ Error VulkanContext::_update_swap_chain(Window *window) {
...
+
+	//Set the windows present mode if it is available, otherwise FIFO is used(guaranteed supported)
+	if (present_mode_available) {
+		window->presentMode = requested_present_mode;
+	} else {
+		WARN_PRINT("Requested VSync mode is not available!");
+		window->vsync_mode = DisplayServer::VSYNC_ENABLED; //Set to default
+	}
+
+	print_verbose("Choosen present mode:" + String(string_VkPresentModeKHR(window->presentMode)));
```
Comment (clayjohn) [inline drivers/vulkan/vulkan_context.cpp:1339]:
```suggestion
	print_verbose("Using present mode: " + String(string_VkPresentModeKHR(window->presentMode)));
```

File: platform/windows/display_server_windows.cpp [hunk 9]
```diff
@@ -1119,7 +1119,7 @@ bool DisplayServerWindows::window_can_draw(WindowID p_window) const {
 
 	ERR_FAIL_COND_V(!windows.has(p_window), false);
 	const WindowData &wd = windows[p_window];
-	return wd.minimized;
+	return !wd.minimized;
```
Comment (clayjohn) [inline platform/windows/display_server_windows.cpp:1122]: This seems unrelated to the rest of the PR. Although the original does look wrong, was this connected to a bug you noticed?

Comment (Geometror) [reply platform/windows/display_server_windows.cpp:1122]: Yes, this is a typo and prevented rendering the frames as fast as possible when disabling v-sync on Windows.

File: doc/classes/DisplayServer.xml (hunk 5 above)
Comment (Geometror) [reply doc/classes/DisplayServer.xml]: Done.

File: doc/classes/ProjectSettings.xml (hunk 6 above)
Comment (Geometror) [reply doc/classes/ProjectSettings.xml]: Done, but changed to "[code]Enabled[/code] or [code]Adaptive[/code]" to match with the actual text in the dropdown menu.

File: platform/windows/display_server_windows.cpp (hunk 9 above)
Comment (akien-mga) [reply platform/windows/display_server_windows.cpp:1122]: This should probably go in its own PR then to be reviewed and merged independently of this one.

File: doc/classes/ProjectSettings.xml (hunk 7 above)
Comment (Geometror) [reply doc/classes/ProjectSettings.xml]: Linked the enum destription instead of describing the different modes directly, so that they are at one place.

File: drivers/vulkan/vulkan_context.cpp (hunk 8 above)
Comment (Geometror) [reply drivers/vulkan/vulkan_context.cpp]: Done.

File: platform/windows/display_server_windows.cpp (hunk 9 above)
Comment (Geometror) [reply platform/windows/display_server_windows.cpp:1122]: I could do that, but is that really necessary for this tiny change since it is a bug that prevented the v-sync setting to work properly on Windows?

Comment (akien-mga) [reply platform/windows/display_server_windows.cpp:1122]: It looks to me like a bug that would also affect Godot on Windows regardless of this PR, no? 
This method is used in `Window::can_draw()` and in `main.cpp`:
```
OS::get_singleton()->add_frame_delay(DisplayServer::get_singleton()->window_can_draw());
```
So it has potential for changing behavior for Windows users significantly (hopefully for the better), and thus it's better if it's merged independently so that its effect can be assessed independently of this PR for VSync.

Of course you need the fix here so you can also keep the change here and rebase once the other PR is merged (which is likely to come sooner than this here PR given the difference in complexity of the changes).

Comment (Geometror) [reply platform/windows/display_server_windows.cpp:1122]: Ok, then I will split this up.

Comment (Geometror) [reply platform/windows/display_server_windows.cpp:1122]: Opened  #49253

**Comment by Geometror** [comment]
I'm sorry, I have no idea how this got accidently closed... could someone reopen it?

**Comment by bruvzg** [comment]
> could someone reopen it?

No, there's `0` commits in PR, that's why it was closed, and it's impossible to reopen it until there are commits. Seems like something gone wrong with the rebase.

File: core/config/project_settings.cpp [hunk 10]
```diff
@@ -1114,8 +1114,8 @@ ProjectSettings::ProjectSettings() {
 
 	_add_builtin_input_map();
 
-	// Keep the enum values in sync with the `DisplayServer::ScreenOrientation` enum.
```
Comment (clayjohn) [inline core/config/project_settings.cpp:1117]: Should this comment be deleted? Seems unrelated to this PR

File: doc/classes/DisplayServer.xml [hunk 11]
```diff
@@ -1143,5 +1139,18 @@
...
+		<constant name="VSYNC_ENABLED" value="1" enum="VSyncMode">
+			Default vertical synchronization mode, the image is displayed only on vertical blanking intervals (no tearing is visible).
+		</constant>
+		<constant name="VSYNC_ADAPTIVE" value="2" enum="VSyncMode">
+			Behaves like [code]VSYNC_DISABLED[/code] when the framerate drops below the screen's refresh rate to reduce stuttering (tearing may be visible), otherwise vertical synchronization is enabled to avoid tearing.
+		</constant>
+		<constant name="VSYNC_MAILBOX" value="3" enum="VSyncMode">
+			Displays the most recent image in the queue on vertical blanking intervals, while rendering to the other images (no tearing is visible).
+			Altough not guaranteed, the images can be rendered as fast as possible, which may reduce input lag.
```
Comment (clayjohn) [inline doc/classes/DisplayServer.xml:1153]:
```suggestion
			Although not guaranteed, the images can be rendered as fast as possible, which may reduce input lag.
```

Comment (Geometror) [reply doc/classes/DisplayServer.xml]: Oops, fixed.

File: core/config/project_settings.cpp (hunk 10 above)
Comment (Geometror) [reply core/config/project_settings.cpp:1117]: No, sorry, I deleted that comment accidently.

File: core/config/project_settings.cpp (hunk 1 above)
Comment (Geometror) [reply core/config/project_settings.cpp]: Is it fine like this?

**Review by clayjohn — APPROVED** [review]

File: doc/classes/DisplayServer.xml [hunk 12]
```diff
@@ -995,6 +978,19 @@
...
+			<return type="void">
+			</return>
+			<argument index="0" name="vsync_mode" type="int" enum="DisplayServer.VSyncMode">
+			</argument>
+			<argument index="1" name="window_id" type="int" default="0">
+			</argument>
+			<description>
+				Sets the VSync mode of the given window.
+				See [enum DisplayServer.VSyncMode] for possible values and how they affect the behavior of your application.
+				Depending on the platform and used renderer, the engine will fall back to [code]Enabled[/code], if the desired mode is not supported.
```
Comment (akien-mga) [inline doc/classes/DisplayServer.xml:991]: I know there was some back and forth on this but it seems @clayjohn wasn't familiar with this convention: you can refer to constants directly with `[constant VSYNC_ENABLED]` to create a hyperlink.

File: doc/classes/DisplayServer.xml [hunk 13]
```diff
@@ -1143,5 +1139,18 @@
...
 		<constant name="WINDOW_EVENT_DPI_CHANGE" value="6" enum="WindowEvent">
 		</constant>
+		<constant name="VSYNC_DISABLED" value="0" enum="VSyncMode">
+			No vertical synchronization, which means the engine will display frames as fast as possible (tearing may be visible).
+		</constant>
+		<constant name="VSYNC_ENABLED" value="1" enum="VSyncMode">
+			Default vertical synchronization mode, the image is displayed only on vertical blanking intervals (no tearing is visible).
+		</constant>
+		<constant name="VSYNC_ADAPTIVE" value="2" enum="VSyncMode">
+			Behaves like [code]VSYNC_DISABLED[/code] when the framerate drops below the screen's refresh rate to reduce stuttering (tearing may be visible), otherwise vertical synchronization is enabled to avoid tearing.
```
Comment (akien-mga) [inline doc/classes/DisplayServer.xml:1149]: This should be `[constant VSYNC_DISABLED]`.

File: doc/classes/ProjectSettings.xml [hunk 14]
```diff
@@ -530,12 +530,10 @@
...
-		</member>
-		<member name="display/window/vsync/vsync_via_compositor" type="bool" setter="" getter="" default="false">
-			If [code]Use Vsync[/code] is enabled and this setting is [code]true[/code], enables vertical synchronization via the operating system's window compositor when in windowed mode and the compositor is enabled. This will prevent stutter in certain situations. (Windows only.)
-			[b]Note:[/b] This option is experimental and meant to alleviate stutter experienced by some users. However, some users have experienced a Vsync framerate halving (e.g. from 60 FPS to 30 FPS) when using it.
+		<member name="display/window/vsync/vsync_mode" type="String" setter="" getter="" default="&quot;Enabled&quot;">
+			Sets the VSync mode for the main game window.
+			See [enum DisplayServer.VSyncMode] for possible values and how they affect the behavior of your application.
+			Depending on the platform and used renderer, the engine will fall back to [code]Enabled[/code], if the desired mode is not supported.
```
Comment (akien-mga) [inline doc/classes/ProjectSettings.xml:536]: Here we could also use `[constant DisplayServer.VSYNC_ENABLED]`, though I think for the project settings there's merit in giving the name of the actual user-facing value in the drop-down list, so it's good as is.

File: drivers/vulkan/vulkan_context.cpp [hunk 15]
```diff
@@ -1304,16 +1304,41 @@ Error VulkanContext::_update_swap_chain(Window *window) {
...
+			break;
+		case DisplayServer::VSYNC_ENABLED:
+			requested_present_mode = VkPresentModeKHR::VK_PRESENT_MODE_FIFO_KHR;
+			break;
+		case DisplayServer::VSYNC_DISABLED:
+			requested_present_mode = VkPresentModeKHR::VK_PRESENT_MODE_IMMEDIATE_KHR;
+			break;
+	}
+
+	//Check if the requested mode is available
```
Comment (akien-mga) [inline drivers/vulkan/vulkan_context.cpp:1323]: Not super important, but we usually style comments this way (initial space, final dot):
```
// Check if the requested mode is available.
```
Same for other comments.

File: drivers/vulkan/vulkan_context.cpp [hunk 16]
```diff
@@ -2062,6 +2087,15 @@ String VulkanContext::get_device_pipeline_cache_uuid() const {
 	return pipeline_cache_id;
 }
 
+DisplayServer::VSyncMode VulkanContext::get_vsync_mode(DisplayServer::WindowID p_window) const {
+	return windows[p_window].vsync_mode;
```
Comment (akien-mga) [inline drivers/vulkan/vulkan_context.cpp:2091]: Are we sure that `p_window` will always be a valid index? Otherwise this could crash and would need an `ERR_FAIL_COND` or `ERR_FAIL_INDEX` check to guard it.

**Review by akien-mga — COMMENTED** [review]
Looks pretty good!

File: drivers/vulkan/vulkan_context.cpp (hunk 16 above)
Comment (Geometror) [reply drivers/vulkan/vulkan_context.cpp:2092]: Done, it throws an error and prints out a message when trying to set/get the VSync mode of a non-existent window.

File: doc/classes/DisplayServer.xml (hunk 12 above)
Comment (Geometror) [reply doc/classes/DisplayServer.xml]: Changed.

File: doc/classes/DisplayServer.xml (hunk 13 above)
Comment (Geometror) [reply doc/classes/DisplayServer.xml]: Changed.

File: doc/classes/ProjectSettings.xml (hunk 14 above)
Comment (Geometror) [reply doc/classes/ProjectSettings.xml:536]: I would leave it as is because of the reason you already mentioned.

File: drivers/vulkan/vulkan_context.cpp (hunk 15 above)
Comment (Geometror) [reply drivers/vulkan/vulkan_context.cpp]: Done.

**Comment by Geometror** [comment]
Rebased.
@Calinou Do you think I should include the editor VSync option from your 4.0 PR (#48364) as part of the whole VSync options reimplementation? Because when/if this is merged, that PR must be redone anyway, so I could save you some work.

**Comment by clayjohn** [comment]
@Geometror I think it is best for each PR to do one thing. My preference is to merge this PR first and then look at Calinou's PR after.

File: core/config/project_settings.cpp (hunk 1 above)
Comment (Calinou) [reply core/config/project_settings.cpp]: Looks good to me now.

**Review by Calinou — APPROVED** [review]
Tested locally with this PR rebased against the latest `master` branch. All options seem to work as expected on Linux + NVIDIA.

**Edit:** Tested on a Windows 10 + Intel IGP setup, it works as expected there too.

**Review by reduz — APPROVED** [review]

**Comment by Calinou** [comment]
Thanks!

File: core/config/project_settings.cpp [hunk 17]
```diff
@@ -1114,6 +1114,7 @@ ProjectSettings::ProjectSettings() {
 
 	// Keep the enum values in sync with the `DisplayServer::ScreenOrientation` enum.
 	custom_prop_info["display/window/handheld/orientation"] = PropertyInfo(Variant::INT, "display/window/handheld/orientation", PROPERTY_HINT_ENUM, "Landscape,Portrait,Reverse Landscape,Reverse Portrait,Sensor Landscape,Sensor Portrait,Sensor");
+	custom_prop_info["display/window/vsync/vsync_mode"] = PropertyInfo(Variant::STRING, "display/window/vsync/vsync_mode", PROPERTY_HINT_ENUM, "Disabled,Enabled,Adaptive,Mailbox");
```
Comment (Calinou) [inline core/config/project_settings.cpp:1117]: I just noticed this is a *string* enum rather than an integer enum. I think using an integer enum would be better as it's more Godot-y overall. (We're trying to move away from string usage when possible in 4.0 onwards.)

Comment (Geometror) [reply core/config/project_settings.cpp:1117]: I presume I just copied how it was done for the screen orientation (which was before you changed it to an integer enum). But you are right, an integer enum is cleaner as it wouldn't need that ugly if-elseif construct in main.cpp. I will open a PR soon to change that.

File: platform/linuxbsd/display_server_x11.h [hunk 18]
```diff
@@ -362,6 +362,9 @@ class DisplayServerX11 : public DisplayServer {
 	virtual void window_set_ime_active(const bool p_active, WindowID p_window = MAIN_WINDOW_ID);
 	virtual void window_set_ime_position(const Point2i &p_pos, WindowID p_window = MAIN_WINDOW_ID);
 
+	virtual void window_set_vsync_mode(DisplayServer::VSyncMode p_vsync_mode, WindowID p_window = MAIN_WINDOW_ID) override;
+	virtual DisplayServer::VSyncMode window_get_vsync_mode(WindowID p_vsync_mode) const override;
```
Comment (vnen) [inline platform/linuxbsd/display_server_x11.h:366]: This class didn't have `override` before this, so now Clang complain about the others that are missing.

Comment (Geometror) [reply platform/linuxbsd/display_server_x11.h:366]: Is the use of `override` desired? If so, I could add it where it should be (only display_server_iphone and display_server_osx use it currently), otherwise I could open a PR to remove the keyword from all display_server classes except osx and iphone.

Comment (vnen) [reply platform/linuxbsd/display_server_x11.h:366]: > Is the use of `override` desired?

Yes, it is. I'm not sure why it wasn't used in those classes before.

Comment (Geometror) [reply platform/linuxbsd/display_server_x11.h:366]: I opened a PR for this: #50513
