### PR TITLE
TabContainer's signal changes (v3)

### LINKED ISSUE #7752: TabContainer's tab_changed signal runs every time you click tab
**Operating system or device - Godot version:** 
v2.1.2 (on Steam)

**Issue description:**
The tab_changed( int tab ) does not only run when you change tab, it also runs when you select a tab regardless if you are changing it. ([Video example at 6:06'ish](https://youtu.be/00569Osm-OM?t=6m4s))

**Steps to reproduce:**
- Create a TabContainer with a few tabs.
- Setup the "tab_changed( int tab ) signal from TabContainer
- Make it print some text when the signal runs
- Play the scene and click the same tab over and over again

**Link to minimal example project:**
https://mega.nz/#!oQNxCZTJ!k2o2y6I5do4fqKFkaE9abWSRIRY91VD4z1VJxXHQMaw (Project used in the video example)

### PR DESCRIPTION
**Pull request by RebelliousX**
- `tab_changed` signal emits only by selecting a different tab.
- Added `tab_selected` signal. Which emits a signal by selecting any tab, even if current tab is being selected again.
- Added `get_previous_tab()`. Which returns the previous shown tab index. **Note:** only `tab_changed` can modify previous tab index.
- Add documentation for the added function and signals. Fix a typo too.
- Fix #7752

### CODE REVIEW

**Comment by RebelliousX** [comment]
Here is a [tiny project](https://www.dropbox.com/s/z2h1ozrju2zf3t3/tabcontainer_v3.rar?dl=0) showing how it works

**Comment by akien-mga** [comment]
My proposal was actually:
- Emit `tab_changed` when the tab is changed
- Emit `tab_selected` when a tab is selected
Which happens to match their names pretty well :)

I don't think that `tab_current_reselected` is useful, people who need it should just check if the tab ID is the current one when they receive `tab_selected`, which should be emitted when *any* tab is selected.

So yes, that means that when you change tabs, you would emit both `tab_selected` (first, upon tab selection) and `tab_changed` (second, after the tab has been changed).

**Comment by RebelliousX** [comment]
@akien-mga Sorry, I misunderstood your point, I thought you were just complaining about the names of the signals.

**Comment by RebelliousX** [comment]
Please test and review with the new changes, I reuploaded the project that shows the changes above.

**Comment by Tybobobo** [comment]
Nice. Good job

File: scene/gui/tab_container.cpp [hunk 1]
```diff
@@ -417,7 +419,13 @@ void TabContainer::set_current_tab(int p_current) {
 	}
 
 	_change_notify("current_tab");
-	emit_signal("tab_changed", current);
+	if (pending_previous == current)
+		emit_signal("tab_selected", current);
```
Comment (akien-mga) [inline scene/gui/tab_container.cpp]: This should be outside the `if` ;)

**Review by akien-mga — APPROVED** [review]

File: scene/gui/tab_container.cpp (hunk 1 above)
Comment (RebelliousX) [inline scene/gui/tab_container.cpp]: Yes, I didn't pay much attention to it, since I wanted minimal changes to previous commit. But functionality wise, it would be the same. I will change this now :)

Comment (akien-mga) [inline scene/gui/tab_container.cpp]: I don't understand. What I mean is that:
```
	if (pending_previous == current)
		emit_signal("tab_selected", current);
	else {
		previous = pending_previous;
		emit_signal("tab_selected", current);
		emit_signal("tab_changed", current);
	}
```
should be the same as
```
	emit_signal("tab_selected", current);
	if (pending_previous != current) {
		previous = pending_previous;
		emit_signal("tab_changed", current);
	}
```
which is IMO much cleaner. Or does the emission of `tab_selected` change the value of either `pending_previous` or `current`?

Comment (RebelliousX) [inline scene/gui/tab_container.cpp]: It does change,  I tested exactly what you suggested, on all subsequent calls before the emission occurs, `pending_previous` changes to `current` at the start of the function. Which ruins the comparison later on. Note that I don't compare previous with current; but pending previous with current.

I find the current code comprehendible and neat.

Comment (RebelliousX) [inline scene/gui/tab_container.cpp]: @akien-mga please wait, don't merge.

Comment (RebelliousX) [inline scene/gui/tab_container.cpp]: The output for the new code is:
**Code**
```
	emit_signal("tab_selected", current);
	if (pending_previous != current) {
		previous = pending_previous;
		emit_signal("tab_changed", current);
	}
```
**Output** 
```
on_tab_selected: current tab index 1, previous tab index: 0
on_tab_changed: current tab index 1, previous tab index: 0

on_tab_selected: current tab index 0, previous tab index: 0
on_tab_changed: current tab index 0, previous tab index: 1

on_tab_selected: current tab index 1, previous tab index: 1
on_tab_changed: current tab index 1, previous tab index: 0

on_tab_selected: current tab index 2, previous tab index: 0
on_tab_changed: current tab index 2, previous tab index: 1

on_tab_selected: current tab index 3, previous tab index: 1
on_tab_changed: current tab index 3, previous tab index: 2

on_tab_selected: current tab index 4, previous tab index: 2
on_tab_changed: current tab index 4, previous tab index: 3
```

It should be like this:
**Code**
```
	if (pending_previous == current)
		emit_signal("tab_selected", current);
	else {
		previous = pending_previous;
		emit_signal("tab_selected", current);
		emit_signal("tab_changed", current);
	}
```

**Output**
```
on_tab_selected: current tab index 1, previous tab index: 0
on_tab_changed: current tab index 1, previous tab index: 0

on_tab_selected: current tab index 0, previous tab index: 1
on_tab_changed: current tab index 0, previous tab index: 1

on_tab_selected: current tab index 1, previous tab index: 0
on_tab_changed: current tab index 1, previous tab index: 0

on_tab_selected: current tab index 2, previous tab index: 1
on_tab_changed: current tab index 2, previous tab index: 1

on_tab_selected: current tab index 3, previous tab index: 2
on_tab_changed: current tab index 3, previous tab index: 2

on_tab_selected: current tab index 4, previous tab index: 3
on_tab_changed: current tab index 4, previous tab index: 3
```

Did you notice the difference? `previous` tab index is not updated. That is what drove me crazy, it seems the putting the emission outside the if statement is a benign thing. But there is a very subtle difference. Look carefully when `previous` gets updated by `pending_previous`. Not necessarily every time `set_current_tab()` is called. 

But I am not crazy, lol, I've been programming since the days of Atari ST, MSX and Commodore 64, even assembly of Z80 processor when I was 9. This is the first time a silly fragment of code gave such headache.

I am reverting to previous code.

Comment (akien-mga) [inline scene/gui/tab_container.cpp]: Alright, I've done enough nit-picking for this one ;)
