### PR TITLE
GDScript: Allow mixed indentation on blank lines

### LINKED ISSUE #52834: Error when mixing tabs and spaces in comment line
### Godot version

b1063a7

### System information

W10

### Issue description

idk I had this error in my code:
```
[TAB][SPACE]#something
```
It complains that tabs and spaces are mixed, even though it's irrelevant, because it's just a comment. Reporting this only because it was valid in 3.x

### Steps to reproduce

See snippet above.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dalexeev**
* Allow mixed indentation on non-code lines (empty or only comment).
* In 3.x this is allowed.
* Closes #52834.
* See also #80360. After #44557, commenting out such code results in a parser error.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 1]
```diff
@@ -1214,6 +1205,15 @@ void GDScriptTokenizer::check_indent() {
 			continue;
 		}
 
+		if (mixed && !(line_continuation || multiline_mode)) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_tokenizer.cpp:1208]:
```suggestion
		if (mixed && !line_continuation && !multiline_mode) {
```
Looks cleaner IMO

**Comment by akien-mga** [comment]
Thanks!
