### PR TITLE
Fix can't set AudioStreamPlayer stream to null

### LINKED ISSUE #16846: AudioStreamPlayer3D and AudioStreamPlayer2D setting Stream issue.
**Godot version:**
Godot 3.0 stable

**OS/device including version:**
OS: Windows 8.1

**Issue description:**
I'm not sure it should be written as different issue or not. But I think that this 2 bug about AudioStreamPlayer3D and AudioStreamPlayer2D is related so I reported it under the same issue.
1. Error: !p_stream.is_valid() always shown when running a scene that have an AudioStreamPlayer2D Node or AudioStreamPlayer3D Node with null/unset Stream property. (Not happen with AudioStreamPlayer Node)
image

2. If you set a Stream property in AudioStreamPlayer2D Node or AudioStreamPlayer3D Node you cannot unset it. (Click clear like in my screenshot below, nothing happen)
(Also Not happen with AudioStreamPlayer Node)
image

**Steps to reproduce:**
1. Create new scene
2. Add AudioStreamPlayer2D Node or AudioStreamPlayer3D Node.
3. Save Scene.
4. Do the same thing I did in Issue Description

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by chanon**
Fixes #16846 and #18012.

I looked at how all 3 `set_stream` methods were implemented, and fixed them so that they would allow setting the stream to null (empty) without erroring.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
I guess you should also clear the stream in this case, not just silence the error.

**Comment by chanon** [comment]
I thought it does that with the `stream.unref()` call.
Following the logic, from what I understand if `p_stream` is null, then `stream_playback` will be null and so  `stream.unref()` would be called.

**Comment by bojidar-bg** [comment]
Oh right, seems like I wasn't attentive enough before dinner. Sorry :smiley:

File: scene/2d/audio_stream_player_2d.cpp [hunk 1]
```diff
@@ -254,14 +253,15 @@ void AudioStreamPlayer2D::set_stream(Ref<AudioStream> p_stream) {
...
-	stream_playback = p_stream->instance_playback();
+	if (p_stream.is_valid()) {
+		stream = p_stream;
+		stream_playback = p_stream->instance_playback();
+	}
 
 	AudioServer::get_singleton()->unlock();
 
 	if (stream_playback.is_null()) {
 		stream.unref();
```
Comment (vnen) [inline scene/2d/audio_stream_player_2d.cpp]: Isn't this `unref`ing the stream twice if the new stream is null?

Comment (chanon) [reply scene/2d/audio_stream_player_2d.cpp]: Hmm so do you think
```
if (stream_playback.is_null()) {
 		stream.unref();
```
can be removed?

It was there in the old code in all versions (AudioStreamPlayer and AudioStreamPlayer2D/3D had similar but different `set_stream` methods) so I didn't think to remove it.

Comment (chanon) [reply scene/2d/audio_stream_player_2d.cpp]: I see, I will test it and update the pull request

**Comment by chanon** [comment]
Updated according to review comments
