### PR TITLE
Fix Tree minimum size calculation

### LINKED ISSUE #91047: Empty Tree ignores column title for minimum size
### Tested versions

v4.3.dev.custom_build [7abe0c601]

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/2edf2bbd-e28d-46e4-912a-0cd642f47707

This is with vertical scroll disabled.

### Steps to reproduce

1. Create Tree
2. Enable `column_titles_visible`
3. Disable `scroll_vertical_enabled`
4. Resize the Tree to minimum size

### Minimal reproduction project (MRP)

Quick script for setting column title:
```GDScript
@tool
extends Tree

func _ready() -> void:
	set_column_title(0, "Title")
```

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #91047

- Takes scrollbar space and column title buttons into account
- Fixes first column min size sometimes missing one level of indent
- Fixes cell min size ignoring text overrun behavior and item inner margin
- Updates min size when `hide_root` or `column_title_visible` changes

Also fixed wrong description of `item_inner_margin_*` constants. They are actually applied to cells instead of items (rows) in the [PR](https://github.com/godotengine/godot/pull/75460) that introduced them. The naming is unfortunate, but I don't think it's worth breaking compat for.

---

This PR accidentially fixed the problem that Scene dock uses both text ellipsis and horizontal scrollbar (and the scrollbar did not allow you to see the whole text) :rofl: 

| Before | After |
|---|---|
| Peek 2024-04-24 10-06 | Peek 2024-04-24 10-03 |

If the horizontal scrollbar is preferred, all we need to do is setting the text overrun behavior to "no trimming".

### CODE REVIEW

**Comment by AdriaandeJongh** [comment]
As long as there is a tooltip that displays the full title of a node with a title longer than can be displayed, I think this fix is the preferred one. Horizontal scrolling is simply always cumbersome IMO.

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -4394,17 +4395,25 @@ void Tree::_update_all() {
...
-		return Size2();
-	} else {
-		Vector2 min_size = get_internal_min_size();
-		Ref<StyleBox> bg = theme_cache.panel_style;
-		if (bg.is_valid()) {
-			min_size.x += bg->get_margin(SIDE_LEFT) + bg->get_margin(SIDE_RIGHT);
-			min_size.y += bg->get_margin(SIDE_TOP) + bg->get_margin(SIDE_BOTTOM);
-		}
-		return Vector2(h_scroll_enabled ? 0 : min_size.x, v_scroll_enabled ? 0 : min_size.y);
+	Vector2 min_size = Vector2(0, _get_title_button_height());
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:4398]: Shouldn't this be ignored when vertical scroll is enabled?

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -4394,17 +4395,25 @@ void Tree::_update_all() {
...
+
+	Ref<StyleBox> bg = theme_cache.panel_style;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:4400]: tbh this new variable is unnecessary.

**Review by KoBeWi — APPROVED** [review]
Left some comments, but otherwise looks ok.
(I didn't test extensively though)

File: scene/gui/tree.cpp (hunk 1 above)
Comment (timothyqiu) [reply scene/gui/tree.cpp:4398]: Vertical scrollbar does not scroll the title.

**Comment by akien-mga** [comment]
Needs rebase to fix CI.

**Comment by akien-mga** [comment]
Thanks!
