### PR TITLE
Mono: Show custom error explaining that UWP is not supported

### LINKED ISSUE #64490: Disable UWP export in Mono build
### Godot version

3.5 stable mono

### System information

Windows 11

### Issue description

When exporting a Mono project, UWP is an option in the list. However, UWP exports are not supported for Mono projects and no UWP export templates exist for the Mono build. So the result is confusion when after installing the export templates, the export window still says it can't find the template for UWP. So it would make sense to disable the UWP option in Mono builds.

I think it would also be helpful to mention the lack of Mono support on the UWP export page in the docs. Right now this is only mentioned as an aside on the C# scripting overview page.

After searching the issues I found that there is *some* chatter around Mono UWP support in #20271 (among others), but it seems that there's a lot of complexity and it doesn't look like proper C#/Mono UWP exports will make it into Godot any time soon. So I think disabling the UWP option in the UI to prevent confusion would be a good solution for the time being.

### Steps to reproduce

1. Create a project in a Mono build
2. Install export templates
3. Create UWP export configuration
4. See the error at the bottom of the export window saying that it can't find the UWP export templates

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #64490.

It's slightly hacky because I left the door open for people potentially providing their own Mono-enabled UWP templates. I'm not aware of anyone actually having implemented such support, but who knows (I guess if someone really cares they could figure out how to use IL2CPP to compile the C# code to C++ in the template, and thus be able to use a non-Mono UWP template to export their game).

Initially I was thinking that this might be needed for Pineapple's Mono support on Xbox, but [reading again](https://mobile.twitter.com/pineapple_works/status/1557452890326933506) I see they're using GDKX so it shouldn't matter. CC @wkubiak anyway FYI.

My first implementation was skipping the whole `export.cpp` logic, which fully hides the "UWP" entry from the list, but then you get an error if you e.g. have a GDScript project with a configured UWP preset and you then load it in a Mono build (e.g. to start using C# additionally). And this error can't be removed until you edit `export_presets.cfg` manually to remove the section about UWP, since it doesn't show in the UI to do so.

### CODE REVIEW

File: platform/uwp/export/export.cpp [hunk 1]
```diff
@@ -1110,11 +1117,20 @@ class EditorExportPlatformUWP : public EditorExportPlatform {
 		}
 
 		valid = dvalid || rvalid;
+
+#ifdef MODULE_MONO_ENABLED
+		// If this is a Mono build, provide a custom error so that users are not confused.
+		// We don't bypass the whole logic to check templates because third-parties might have
+		// Mono-enabled UWP builds using this path.
+		r_missing_templates = false; // Don't warn about those.
+		r_error = TTR("Godot's Mono version does not support the UWP platform. Use the standard build (no C# support) if you wish to target UWP.");
```
Comment (bruvzg) [inline platform/uwp/export/export.cpp:1126]: Probably `valid` should forced to `false` here, in case some template files were placed into the mono template folder manually.

Comment (akien-mga) [reply platform/uwp/export/export.cpp:1126]: No that's intentional as I mentioned in the comment:
```
// We don't bypass the whole logic to check templates because third-parties might have
// Mono-enabled UWP builds using this path.
```

The idea is that if you do provide templates which you got from a third-party and which would work, then you can use them. But if you don't, then it will just inform that the official Godot Mono doesn't support UWP.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.
