### PR TITLE
[TLS] Disable TLSv1.3 support by default

### LINKED ISSUE #101910: [4.4 beta 1] TLS Handshake Error with Godot HTTPRequest
### Tested versions

4.4 beta 1 

### System information

Windows 11 - Godot 4.4 beta 1 - Vulkan (Mobile)

### Issue description

I’m encountering a TLS handshake error when trying to make a request to https://graph.oculus.com/ using Godot's HTTPRequest.

* Requests to https://www.google.com/ work without any issues.
* Python's requests library can access the URL without any problems.
* The same https://graph.oculus.com/ URL works correctly in Postman.
* I attempted to create a certificate bundle as well, but it was unsuccessful.
* This issue appears to be specific to Godot.

CPP ERROR:

E 0:00:01:0639   StreamPeerMbedTLS::_do_handshake: TLS handshake error: -28800
  <C++ Source>   modules\mbedtls\stream_peer_mbedtls.cpp:88 @ StreamPeerMbedTLS::_do_handshake()

### Steps to reproduce

* Create simple project
* Add a HTTPRequest node
* Add script:
```
extends Node3D

@onready var http: HTTPRequest = $HTTPRequest

func _ready() -> void:
	http.request("https://graph.oculus.com/")
	print(await http.request_completed)
```
* Run

### Minimal reproduction project (MRP)

[teste-vr.zip](https://github.com/user-attachments/files/18505403/teste-vr.zip)

### PR DESCRIPTION
**Pull request by Faless**
mbedTLS does not support TLS Handshake record layer fragmentation which seems enabled on some sites (notably, Meta's sites).

This PR makes TLSv1.3 optional (and disabled by default).

We should decide if we want to proceed with #102770 (which incorporates an upstream, yet unmerged, PR adding support for the aforementioned feature in mbedTLS -> https://github.com/Mbed-TLS/mbedtls/pull/9949) or merge this instead.

I also had another branch making the TLS min and max versions configurable via TLSOptions but I honestly think that's an overkill and adds a lot of API complexity for something that should just work out of the box.

Fixes #101910 .

### CODE REVIEW

File: modules/mbedtls/register_types.cpp [hunk 1]
```diff
@@ -30,6 +30,7 @@
 
 #include "register_types.h"
 
+#include "core/config/project_settings.h"
 #include "crypto_mbedtls.h"
 #include "dtls_server_mbedtls.h"
 #include "packet_peer_mbed_dtls.h"
```
Comment (akien-mga) [inline modules/mbedtls/register_types.cpp:36]: We normalize group includes like this in modules: module files first, then core Godot files, then thirdparty. (Suggestion not complete as I couldn't include line 37 in it, it's outside the changed diff.)
```suggestion
#include "crypto_mbedtls.h"
#include "dtls_server_mbedtls.h"
#include "packet_peer_mbed_dtls.h"

#include "core/config/project_settings.h"
```

**Review by akien-mga — APPROVED** [review]

File: doc/classes/ProjectSettings.xml [hunk 2]
```diff
@@ -2195,6 +2195,10 @@
 		<member name="network/limits/webrtc/max_channel_in_buffer_kb" type="int" setter="" getter="" default="64">
 			Maximum size (in kiB) for the [WebRTCDataChannel] input buffer.
 		</member>
+		<member name="network/tls/enable_tls_v1.3" type="bool" setter="" getter="" default="false">
+			If [code]true[/code], enable TLSv1.3 negotiation.
+			[b]Note:[/b] This is experimental, and may cause connections to fail in some cases (notably, if the remote server uses TLS handshake fragmentation).
+		</member>
```
Comment (akien-mga) [inline doc/classes/ProjectSettings.xml:2201]: This needs to be a bit further down, members are sorted alphabetically.

**Review by Calinou — COMMENTED** [review]
Tested locally on Linux, it works as expected. See also https://github.com/godotengine/godot/pull/102770#pullrequestreview-2612613417.

Considering TLS 1.3 isn't a hard requirement for most services (most still support TLS 1.2 due to legacy clients) and that TLS 1.2 doesn't have known exploitable flaws yet, it's probably fine. However, I'm also concerned about the default setting changes we'd potentially have to make in a patch release.

It may be worth pointing out the project setting in the HTTPClient and HTTPRequest class documentation still, in case someone is testing against a TLS 1.3-only service.

**Comment by akien-mga** [comment]
As discussed on RC, and given concerns expressed on #102770 being a bit too cutting edge, let's go with this approach for 4.4.

**Comment by akien-mga** [comment]
Tested this, I get this warning spammed when I open the Asset Library in the project manager:
```
WARNING: Property not found: 'network/tls/allow_tls_v1.3'.
     at: get_setting_with_override (core/config/project_settings.cpp:379)
```

File: modules/mbedtls/register_types.cpp [hunk 3]
```diff
@@ -50,6 +52,8 @@ void initialize_mbedtls_module(ModuleInitializationLevel p_level) {
 		return;
 	}
 
+	GLOBAL_DEF("network/tls/enable_tls_v1.3", false);
```
Comment (akien-mga) [inline modules/mbedtls/register_types.cpp:55]: I think the `.` might be confusing the logic as that's what we use for overrides normally.

I'd suggest
```suggestion
	GLOBAL_DEF("network/tls/enable_tls_v1_3", false);
```
as a workaround.

Comment (akien-mga) [reply modules/mbedtls/register_types.cpp:55]: Ah wait, the bug I found was `allow_` vs `enable_`, it's maybe not the `.`.

File: modules/mbedtls/tls_context_mbedtls.cpp [hunk 4]
```diff
@@ -187,6 +194,10 @@ Error TLSContextMbedTLS::init_client(int p_transport, const String &p_hostname,
 		}
 	}
 
+	if (Engine::get_singleton()->is_editor_hint() || !(bool)GLOBAL_GET("network/tls/allow_tls_v1.3")) {
```
[the remark this answers is not in the document]
Comment (Faless) [reply modules/mbedtls/tls_context_mbedtls.cpp]: Thanks for double checking, I renamed the property after testing, and forgot to update all references :/

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
