### PR TITLE
Fix EditorSettings saving on draw calls

### LINKED ISSUE #22097: Editor settings are being constantly re-saved
**Godot version:**
4547e22

**OS/device including version:**
Windows 10

**Issue description:**
Editor settings are being re-saved every UI update in the editor.

Possibly regression from https://github.com/godotengine/godot/pull/21717

Partial callstack:
`ResourceSaver::save(const String & p_path, const Ref<Resource> & p_resource, unsigned int p_flags) Line 46`
`EditorSettings::save() Line 964`
`SceneTreeDock::_update_create_root_dialog() Line 2247`
`Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1308`
`CreateDialog::_update_favorite_list() Line 583`
`Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1308`
`EditorFileSystem::update_script_classes() Line 1380`

**Steps to reproduce:**
Find editor-settings-3.tres file
Note file changed time stamp
When system clock changes, do anything that triggers a UI update
Editor settings file timestamp will change

Alternately, set a breakpoint in `ResourceSaver::save` and notice that it's firing on every UI update.

### PR DESCRIPTION
**Pull request by willnationsdev**
Closes #22097.

This, combined with #22234 should ensure that everything in the CreateDialog is working fine regardless of whether it is receiving the signal.

I am a little confused though as to why `EditorFileSystem::update_script_classes` is being called every draw call though. Someone who's more familiar with how the file caching system works will need to determine whether that's really necessary (since presumably it should only need to be called any time a script file has actually been modified).

### CODE REVIEW

File: editor/editor_file_system.cpp [hunk 1]
```diff
@@ -1378,7 +1378,6 @@ void EditorFileSystem::update_script_classes() {
 
 	ScriptServer::save_global_classes();
 	EditorNode::get_editor_data().script_class_save_icon_paths();
-	emit_signal("script_classes_updated");
```
Comment (LikeLakers2) [inline editor/editor_file_system.cpp]: Wait, why is this signal emit being removed from here?

Comment (willnationsdev) [reply editor/editor_file_system.cpp]: 2 reasons.

1. If the `update_script_classes` method is SUPPOSED to be called every draw call (which is what's currently happening), then we *probably* shouldn't be emitting a signal every frame unnecessarily...?
2. The only reason this signal was added in the first place (by me) was so that the CreateDialog would know the names had been updated and would remove no-longer-existing records from the serialized recent/favorites lists. The change in the PR mentioned in the description, however, removes any need for the signal connection in the first place, therefore the signal emission is no longer necessary either.

Comment (willnationsdev) [reply editor/editor_file_system.cpp]: Oh, which also means I can remove the signal itself! Forgot that bit.

Comment (LikeLakers2) [reply editor/editor_file_system.cpp]: Hmm. That's fair, at least by that second reason. I'll put the rest of my response in comment on the PR itself.

**Comment by LikeLakers2** [comment]
I do question how this fixes EditorSettings being saved every draw call, like the title claims. More or less it's just removing a signal from `update_script_classes` that's no longer needed. I haven't looked at the code in-depth like you have, but isn't `update_script_classes` (which is still being called every draw) what's causing the settings to be saved?

Personally, I don't see a reason why updating script classes needs to happen every draw, and I get the feeling it was more a hack for the sake of caching, if it's for caching reasons. Maybe we could remove the call to `update_script_classes` from the draw code?

**Comment by willnationsdev** [comment]
@LikeLakers2 I'm not opposed to doing that as well (cause it doesn't make sense to me for it to be happening every draw call), but in the particular Issue that this closes, the call stack supplied in the OP shows that the save is occurring from the [_update_create_root_dialog()](https://github.com/godotengine/godot/blob/master/editor/scene_tree_dock.cpp#L2202) call, triggered by the ["favorites_updated"](https://github.com/godotengine/godot/blob/master/editor/create_dialog.cpp#L551) signal emission that is only happening every draw call in the first place *because* of the "update_script_classes" signal emission.

I'm not even sure if it's happening every draw call anyway. In `editor_file_system.cpp`, the `_queue_update_script_classes()` method gets called in several places, pretty much any time it's NOT actively scanning changed files (so basically, if we are not scanning and updating script files, then immediately re-scan and update script files, or something like that). This may have been confused with draw calls, but I also don't know exactly how to make it only trigger when it's really necessary.

**Comment by LikeLakers2** [comment]
That's... very confusing. I don't think there's any reason to *always* be re-scanning, not even for the sake of caching (the whole point of caching is to avoid re-scanning every time you need a piece of information). 

That being said, I would personally leave fixing that for another PR, to avoid causing any sort of regression with this PR. Unless, of course, someone else says you should try to fix that in this PR too.

**Comment by willnationsdev** [comment]
@LikeLakers2 ikr. I'll just leave that to someone who better understands how the heck that system works. XD

**Comment by akien-mga** [comment]
Thanks!
