### PR TITLE
 Fix FindReplaceBar focus problems

### LINKED ISSUE #83303: Pressing ESC from code search should give focus to the code editor
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

When editing code in Godot, and searching with Ctrl+F we get a search bar at the bottom of the text editor. When pressing ESC it loses focus... But then - apparently - nothing has focus.

Pressing ESC should return focus to the code editor, as it did until v4.2.dev6.official [57a6813bb]

### Steps to reproduce

While editing code in any project, press CTRL+F to bring up the search bar, then press ESC, and try to write, observe you are no longer writing in the code editor because it does not have focus.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
After #81128 and then #82914 the `_unhandled_input` in FindReplaceBar did not work correctly when it was focused.

Fixes #83303

### CODE REVIEW

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -732,6 +740,7 @@ FindReplaceBar::FindReplaceBar() {
 	vbc_lineedit->add_child(replace_text);
 	replace_text->set_custom_minimum_size(Size2(100 * EDSCALE, 0));
 	replace_text->connect("text_submitted", callable_mp(this, &FindReplaceBar::_replace_text_submitted));
+	search_text->connect("focus_exited", callable_mp(this, &FindReplaceBar::_focus_lost));
```
Comment (SaracenOne) [inline editor/code_editor.cpp:743]: Shouldn't this be ```replace_text->connect("focus_exited", callable_mp(this, &FindReplaceBar::_focus_lost));```?

**Review by SaracenOne — CHANGES_REQUESTED** [review]

**Review by SaracenOne — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!
