### PR TITLE
Cancels the code complete timer when the caret moves to another line

### LINKED ISSUE #68961: Moving caret does not cancel autocompletion timer
### Godot version

4.0 11e1c83 / 3.5

### System information

Windows 10 x64

### Issue description

godot windows editor dev x86_64_Vr9mH4j7QG
The popup shouldn't appear here, because I stopped typing and moved to another line. It makes navigation annoying, because I have to constantly mash Escape :/

### Steps to reproduce

1. Type some text in script editor
2. Make sure autocompletion is closed
3. Type some more on the same line
4. Immediately move to another line
5. Autocompletion will appear of the new line

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by alfredbaudisch**
Fixes and closes #68961

### CODE REVIEW

File: editor/code_editor.h [hunk 1]
```diff
@@ -158,6 +158,7 @@ class CodeTextEditor : public VBoxContainer {
 	Label *info = nullptr;
 	Timer *idle = nullptr;
 	Timer *code_complete_timer = nullptr;
+	int code_complete_timer_line;
```
Comment (akien-mga) [inline editor/code_editor.h:161]: This should likely be initialized to prevent undefined behavior if it's accessed before being set.
(The same would be true for other scalar values below, seems like this class still needs some refactoring.)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
