### PR TITLE
Checks in analyzer and compiler for GDScript naming conflicts

### LINKED ISSUE #47885: GDScript crash when instantiating subclass which overrides parent class member
**Godot version:**
4.0.dev 6b39980ea

**OS/device including version:**
Windows 10.

**Issue description:**
Instantiating a class which extends another class seems to crash.
The issue occurred sometime between 9ca0d66a3b and b4b7c97d38 (Previously, I was one month out of date)

I tried making a subclass by hand but I was not able to replicate the crash. I call this the "simple test" and it seems to work.
I was able to copy the structure which triggers it and it still crashes. I call this the "complex test".

See the source code, either in the attached project or here:
https://gist.github.com/lyuma/782adbebcaed0dceb2124dcc807a852c

Here is the output from the latest Godot version.
```
Begin simple test.
test1A
test3A
test1A
test2B
test3B
Done with simple test.
Begin complex test.
About to instantiate
ERROR: FATAL: Index p_index = 9 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 9).
   at: VectorWriteProxy<class Variant>::operator [] (S:\repo\godot-pr-pr\core/templates/vector.h:50)
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] VectorWriteProxy<Variant>::operator[] (S:\repo\godot-pr-pr\core\templates\vector.h:50)
[1] VectorWriteProxy<Variant>::operator[] (S:\repo\godot-pr-pr\core\templates\vector.h:50)
[2] GDScriptFunction::_get_variant (S:\repo\godot-pr-pr\modules\gdscript\gdscript_vm.cpp:62)
[3] GDScriptFunction::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript_vm.cpp:519)
[4] GDScript::_super_implicit_constructor (S:\repo\godot-pr-pr\modules\gdscript\gdscript.cpp:94)
[5] GDScript::_create_instance (S:\repo\godot-pr-pr\modules\gdscript\gdscript.cpp:121)
[6] GDScript::_new (S:\repo\godot-pr-pr\modules\gdscript\gdscript.cpp:180)
[7] MethodBindVarArg<GDScript>::call (S:\repo\godot-pr-pr\core\object\method_bind.h:180)
[8] Object::call (S:\repo\godot-pr-pr\core\object\object.cpp:784)
[9] GDScript::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript.cpp:972)
[10] Variant::call (S:\repo\godot-pr-pr\core\variant\variant_call.cpp:938)
[11] GDScriptFunction::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript_vm.cpp:1394)
[12] GDScriptInstance::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript.cpp:1552)
[13] Object::call (S:\repo\godot-pr-pr\core\object\object.cpp:765)
[14] Variant::call (S:\repo\godot-pr-pr\core\variant\variant_call.cpp:938)
[15] GDScriptFunction::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript_vm.cpp:1394)
[16] GDScriptInstance::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript.cpp:1552)
[17] Object::call (S:\repo\godot-pr-pr\core\object\object.cpp:765)
[18] Variant::call (S:\repo\godot-pr-pr\core\variant\variant_call.cpp:938)
[19] GDScriptFunction::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript_vm.cpp:1394)
[20] GDScriptInstance::call (S:\repo\godot-pr-pr\modules\gdscript\gdscript.cpp:1552)
[21] ScriptInstance::call (S:\repo\godot-pr-pr\core\object\script_language.cpp:322)
[22] Node::_notification (S:\repo\godot-pr-pr\scene\main\node.cpp:147)
[23] Node::_notificationv (S:\repo\godot-pr-pr\scene\main\node.h:45)
[24] Node3D::_notificationv (S:\repo\godot-pr-pr\scene\3d\node_3d.h:52)
[25] VisualInstance3D::_notificationv (S:\repo\godot-pr-pr\scene\3d\visual_instance_3d.h:40)
[26] GeometryInstance3D::_notificationv (S:\repo\godot-pr-pr\scene\3d\visual_instance_3d.h:83)
[27] MeshInstance3D::_notificationv (S:\repo\godot-pr-pr\scene\3d\mesh_instance_3d.h:40)
[28] Object::notification (S:\repo\godot-pr-pr\core\object\object.cpp:795)
[29] Node::_propagate_ready (S:\repo\godot-pr-pr\scene\main\node.cpp:189)
[30] Node::_propagate_ready (S:\repo\godot-pr-pr\scene\main\node.cpp:181)
[31] Node::_propagate_ready (S:\repo\godot-pr-pr\scene\main\node.cpp:181)
[32] Node::_set_tree (S:\repo\godot-pr-pr\scene\main\node.cpp:2525)
[33] SceneTree::initialize (S:\repo\godot-pr-pr\scene\main\scene_tree.cpp:395)
[34] OS_Windows::run (S:\repo\godot-pr-pr\platform\windows\os_windows.cpp:620)
[35] widechar_main (S:\repo\godot-pr-pr\platform\windows\godot_windows.cpp:163)
[36] _main (S:\repo\godot-pr-pr\platform\windows\godot_windows.cpp:185)
[37] main (S:\repo\godot-pr-pr\platform\windows\godot_windows.cpp:199)
[38] __scrt_common_main_seh (D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[39] BaseThreadInitThunk
-- END OF BACKTRACE --
Segmentation fault
```

From the one month old build, I see the correct output:
```
Begin simple test.
test1A
test3A
test1A
test2B
test3B
Done with simple test.
Begin complex test.
About to instantiate
Did instantiate [DefaultImporter 0:::0]
Done with complex test.
```

**Steps to reproduce:**
Run the attached project. It will crash.

**Minimal reproduction project:**
[ExtendsCrash.zip](https://github.com/godotengine/godot/files/6310726/ExtendsCrash.zip)

### PR DESCRIPTION
**Pull request by SaracenOne**
This PR includes a variety of checks naming conflicts in variables, constants, enums, enum values, and inner classes from scripts that extend other scripts scripts, native types, and class names. Signal naming conflicts are also checked, but currently only check for naming conflicts with other signals. Some things such as checks against custom class_names and duplicate class_names are still yet to be implemented.

_Bugsquad edit:_ Fix #47885

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -313,6 +313,136 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
 	class_type.native_type = result.native_type;
 	p_class->set_datatype(class_type);
 
+	#define CHECK_MEMBER_AGAINST_INHERITANCE(name, node) \
```
Comment (LightningAA) [inline modules/gdscript/gdscript_analyzer.cpp:316]: Is there a reason these are macros and not inline functions? Inline functions are generally preferred, see https://github.com/godotengine/godot-proposals/issues/2093#issuecomment-757352474

Comment (vnen) [reply modules/gdscript/gdscript_analyzer.cpp:316]: Yeah, I would ask the same.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -313,6 +313,136 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
...
+					break;
+			}
+		}
+		current_data_type = &current_class_node->base_type;
+	}
+
+	#define CHECK_MEMBER_AGAINST_NATIVE(name, native_type_string, node, is_signal) \
+	if (is_signal) { \
+		if (ClassDB::has_signal(native_type_string, name)) { \
+			push_error("Member '" + name + "' redefined (original in native class '" + String(native_type_string) + "')", node); \
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:370]: You should use the `vformat` style and use double quotes (`"`) to surround names so it follows the standard (using raw strings makes it easier).

File: modules/gdscript/gdscript_analyzer.cpp [hunk 3]
```diff
@@ -313,6 +313,136 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
...
+					CHECK_MEMBER_AGAINST_INHERITANCE(p_class->members[i].signal->identifier->name, p_class->members[i].signal)
+					break;
+				default:
+					break;
+			}
+		}
+		current_data_type = &current_class_node->base_type;
+	}
+
+	#define CHECK_MEMBER_AGAINST_NATIVE(name, native_type_string, node, is_signal) \
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:367]: This probably could be a function too.

File: modules/gdscript/gdscript_compiler.cpp [hunk 4]
```diff
@@ -2186,8 +2186,47 @@ Error GDScriptCompiler::_parse_class_level(GDScript *p_script, const GDScriptPar
...
+	if (p_script->name != "") {
+		if (ClassDB::class_exists(p_script->name) && ClassDB::is_class_exposed(p_script->name)) {
+			_set_error("The class '" + p_script->name + "' shadows a native class", p_class);
+			return ERR_ALREADY_EXISTS;
+		}
+	}
+
 	Ref<GDScriptNativeClass> native;
 
+#define CHECK_SCRIPT_MEMBER_INHERITANCE(name, member_type) GDScript *c = p_script; \
```
Comment (vnen) [inline modules/gdscript/gdscript_compiler.cpp:2198]: Any reason you do this check on the compiler? I think it can be done on the analyzer itself (in particular in the `resolve_class_interface` method as it's already looping through members and checking stuff, inheritance is already known at that point). It has better usability since the compiler only runs when you save the script so it won't report errors as you're typing and the compiler still reports a single error while the analyzer can report all at once.

Comment (vnen) [reply modules/gdscript/gdscript_compiler.cpp:2198]: Also, probably can be a function too.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 5]
```diff
@@ -313,6 +313,136 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
...
+				base_member->type == GDScriptParser::ClassNode::Member::CONSTANT || \
+				base_member->type == GDScriptParser::ClassNode::Member::ENUM || \
+				base_member->type == GDScriptParser::ClassNode::Member::ENUM_VALUE || \
+				base_member->type == GDScriptParser::ClassNode::Member::CLASS) { \
+					push_error(vformat(R"(The member "%s" already exists in a parent class.)", name), node); \
+					return ERR_PARSE_ERROR; \
+			} else if (base_member->type == GDScriptParser::ClassNode::Member::SIGNAL && p_class->members[i].type == GDScriptParser::ClassNode::Member::SIGNAL) { \
+				push_error(vformat(R"(The signal "%s" already exists in a parent class.)", name), node); \
+				return ERR_PARSE_ERROR; \
+			} \
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:332]: I think signal should not clash with any of the others, since it's first class now. If a signal clashes with a method or variable it can have unintended effects.

**Review by vnen — CHANGES_REQUESTED** [review]
I do have some nitpicks, but the general idea is okay to me.

**Comment by SaracenOne** [comment]
Okay, this feedback all sounds good. I'll try and make these changes tomorrow.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 6]
```diff
@@ -313,6 +359,117 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
 	class_type.native_type = result.native_type;
 	p_class->set_datatype(class_type);
 
+	// Check for invalid naming in members
+	GDScriptParser::DataType *current_data_type = &p_class->base_type;
+	while (current_data_type && current_data_type->kind == GDScriptParser::DataType::Kind::CLASS) {
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:364]: I just realized you're doing this loop in `resolve_inheritance()`, this check should not be done here (technically this should not fail the inheritance check itself, as long as the base class is valid). In `resolve_class_interface()` there's already a loop for the members and these checks can just be added there in the existing switch cases.

It also also allows for reporting multiple issues at once since it doesn't have to return at the first error.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 7]
```diff
@@ -313,6 +359,117 @@ Error GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode *p_class,
...
+	}
+
+	// Check for name collisions in native types
+	StringName native_name = "";
+	if (current_data_type && current_data_type->kind == GDScriptParser::DataType::Kind::NATIVE) {
+		native_name = current_data_type->native_type;
+	}
+
+	if (String(native_name) != "") {
+		for (int i = 0; i < p_class->members.size(); i++) {
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:424]: Same about this, it can be done on the same loop in `resolve_class_interface()`. There's not really a need for an extra loop just for this check.

**Review by vnen — CHANGES_REQUESTED** [review]
The checks are correct now, but I noticed the location isn't ideal.

**Comment by SaracenOne** [comment]
@vnen Updated the PR to follow your feedback

**Review by vnen — APPROVED** [review]

File: modules/gdscript/gdscript_analyzer.h [hunk 8]
```diff
@@ -44,6 +44,12 @@ class GDScriptAnalyzer {
 	const GDScriptParser::EnumNode *current_enum = nullptr;
 	List<const GDScriptParser::LambdaNode *> lambda_stack;
 
+	// Tests for detecting invalid overloading of script members
+	static _FORCE_INLINE_ bool has_member_name_conflict_in_script_class(const StringName &p_name, const GDScriptParser::ClassNode *p_current_class_node);
+	static _FORCE_INLINE_ bool has_member_name_conflict_in_native_type(const StringName &p_name, const StringName &p_native_type_string);
```
Comment (Shatur) [inline modules/gdscript/gdscript_analyzer.h:49]: Why are you putting `_FORCE_INLINE_` in non-inline methods?
