### PR TITLE
Fix multiple issues with CSG module.

### LINKED ISSUE #21125: CSG: co-planar faces break algorithm
**Godot version:**
3.1.dev

**OS/device including version:**
Win10 64 / GTX 980 Ti

**Issue description:**

Using union, subtraction or intersection on CSG nodes with co-planar / overlapping faces breaks the CSG algorithm and results in either missing faces or clipping.

image

Adding a small jitter (e.g. translating by 0.01) resolves the issue as it makes the affected faces not co-planar, but this creates significant workflow strain that adds up.

**Steps to reproduce:**

- Add 2 CSGBox (or other CSG node) in the same CSGCombiner
- Place them such that 2 of their faces are co-planar, e.g. try making a staircase with `union`

*Bugsquad edit (keywords for easier searching):* coplanar

### LINKED ISSUE #33117: CSG geometry bug
**Godot version:**
Godot 3.2 alpha3

**OS/device including version:**
Win7 Nvidia

**Issue description:**
Geometry (or rendering?) bug showing visible faces with two CSG boxes, the second child one in subtraction operation. There should be no diagonal faces visible, since this area is "subtracted" by the second child CSG box.

**Steps to reproduce:**
Add CSG box node, change height, width and depth to your liking,
Add another CSG box as child of the first, set Operation to "Subtraction", change height, width and depth to see the bug (visible diagonal faces).

csg_renderbug01

### LINKED ISSUE #33121: CSG flicker rendering bug with all union, one subtraction box
**Godot version:**
Godot 3.2 alpha3

**OS/device including version:**
Win7 Nvidia

**Issue description:**
Stable visual positional flicker on the mesh with almost overlapping CSG boxes with one subtraction box covering the area (outerbox)

csg_renderbug03

**Steps to reproduce:**
Move the CSG boxes on the z-axis until they almost overlapp in the minimal project:

**Minimal reproduction project:**
[csg_flicker_bug.zip](https://github.com/godotengine/godot/files/3776561/csg_flicker_bug.zip)

### LINKED ISSUE #33665: CSG Subtraction Bug
**Godot version:**
3.1.2 RC 1

**OS/device including version:**
Windows 10 x64
GTX 1080

**Issue description:**
CSGBox does not calculate subtraction at certain depths if the node that is subtracting is at certain coordinate

Might be related to https://github.com/godotengine/godot/issues/33117

**Steps to reproduce:**
- Create a Spatial scene
- Add a CSGCombiner
- Add a CSGBox as child to the combiner
- Set the box's size to width to 40, height to 0.051, depth to 16
- Add CSGCylinder as child to the combiner and set operation to Subtraction
- Set cylinder size radius to 3
- Set cylinder X translation to -7.51
- Observe the top and bottom face of the CSGBox if subtraction is working on both sides.
At this point, the face facing up should be subtracted, but the bottom face should not. If you then change the cylinders X translation to -7.5, you will observe that now both faces are being subtracted. Similarly, increasing the CSGBox's depth will require a smaller X translation for the subtraction to work

[Changing cylinder translation](https://gyazo.com/8b60851db82d4a2f91d277abdeaed63a)
[Changing Box depth](https://gyazo.com/e3710376cec8f823c44625f557aecf36)

You will also find some other strange issues on the bottom face of the CSGBox if you:
- Set the CSGBox height to 1 and the depth to 15
- Move the CSGCylinder's X translation to -9.63
- Increase CGSCylinder's height. Set to 5 or more for immediate results.

**Minimal reproduction project:**
Included a project with 3 scenes. Two scenes have a controllable rigidbody with WSAD movmenet and the R key to reload the scene. This is to show that although there is evidently a hole, the rigidboy cannot fall through the hole due to the bottom of the CSGBox not being subtracted.
[CSGTest.zip](https://github.com/godotengine/godot/files/3854829/CSGTest.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Replaces BuildPoly with Build2DFaces, which creates faces as each pair of face intersections are processed, instead of trying to create them after all the intersections are processed. Ensures that faces are merged when possible, and removes degenerate triangles.

Treats the child as inside the parent when faces are coplanar.

Includes a general clean up of csg.h and csg.cpp.

Fixes #21125
Fixes #33117
Fixes #33121
Fixes #33665

### CODE REVIEW

File: modules/csg/csg.h [hunk 1]
```diff
@@ -138,99 +140,59 @@ struct CSGBrushOperation {
...
 
-	void _add_poly_points(const BuildPoly &p_poly, int p_edge, int p_from_point, int p_to_point, const Vector<Vector<int> > &vertex_process, Vector<bool> &edge_process, Vector<PolyPoints> &r_poly);
-	void _add_poly_outline(const BuildPoly &p_poly, int p_from_point, int p_to_point, const Vector<Vector<int> > &vertex_process, Vector<int> &r_outline);
-	void _merge_poly(MeshMerge &mesh, int p_face_idx, const BuildPoly &p_poly, bool p_from_b);
-
-	void _collision_callback(const CSGBrush *A, int p_face_a, Map<int, BuildPoly> &build_polys_a, const CSGBrush *B, int p_face_b, Map<int, BuildPoly> &build_polys_b, MeshMerge &mesh_merge);
-
-	static void _collision_callbacks(void *ud, int p_face_b);
-	void merge_brushes(Operation p_operation, const CSGBrush &p_A, const CSGBrush &p_B, CSGBrush &result, float p_snap = 0.001);
+	void update2DFaces(const CSGBrush &p_brush_a, const int p_face_idx_a, const CSGBrush &p_brush_b, const int p_face_idx_b, Build2DFaceCollection &p_collection, float p_vertex_snap);
```
Comment (akien-mga) [inline modules/csg/csg.h]: Shouldn't this be `update_2d_faces` to match our naming convention for methods?

**Comment by reduz** [comment]
that is impressive

File: modules/csg/csg.h (hunk 1 above)
Comment (madmiraal) [reply modules/csg/csg.h]: Old habits die hard. :-)
Looking at it, I think a better name is update_faces.

**Comment by Calinou** [comment]
Correctness is important to have, but is performance as good or better than the current implementation?

**Comment by madmiraal** [comment]
@Calinou Do you have a benchmark we can test it against?

**Comment by Calinou** [comment]
@madmiraal I made one: [test_csg.zip](https://github.com/godotengine/godot/files/4237385/test_csg.zip)

It may not be representative of a real-world use case, but it's a start. Try moving the CSGSphere called "MoveMe" and see how fast the editor remains (compare the current `master` branch and your PR).

**Comment by madmiraal** [comment]
@Calinou I've tested it against your scene (and many of my own scenes during debugging) and the subjective experience is the same.

**Comment by madmiraal** [comment]
In the absence of an existing benchmark, I've created the attached scene to push the CSG calculations beyond what they're designed for:
[CSG Benchmark.zip](https://github.com/godotengine/godot/files/4239485/CSG.Benchmark.zip)

It consists of a `CSGTorus`, which I've increased to 16 sides and 16 ring sides and a script that creates 5 (but this is configurable) default `CSGSpheres` (12 segments and 6 rings) in subtraction mode, which are positioned evenly around the torus and configured to revolve along the torus every frame creating around 350,000 triangle intersections per frame.

On my laptop I get the following frame times:
Current CSG: 127ms ±3ms
Fixed CSG: 141ms ±3ms

So the fixed version is marginally slower, but I wouldn't say significantly so.

**Comment by Calinou** [comment]
@madmiraal Sounds good to me :slightly_smiling_face: 

In the future, we could add a debouncing delay to CSG recomputations to make the editor more responsive.

**Comment by akien-mga** [comment]
Thanks!
