### PR TITLE
Never duplicate Scripts when duplicating resources recursively

### LINKED ISSUE #108220: `duplicate_deep(DEEP_DUPLICATE_ALL)` throws an assert when duplicating a resource cointaining an exported PackedScene with a class_named script
### Tested versions

- Reproduced in Godot 4.5.beta2

### System information

Windows 11 - Vulkan 1.3.271 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Laptop GPU

### Issue description

After upgrading my project to 4.5 i noticed `Resource.duplicate(true)` was not working as before. I already expected this, but turns out none of the 3 option worked as i expected, and in particular `DEEP_DUPLICATE_ALL` caused this assert because duplicating a PackedScene seems to attempt to create a duplicate of the Script, which is usually impossible because of the `PROPERTY_USAGE_NEVER_DUPLICATE` flag

### Steps to reproduce

- Create a new resource script like the following:
```
class_name MyResource extends Resource
@export var my_scene: PackedScene
```
- Create a scene script like the following:
```
class_name MyScene extends Node
```
- Create a new scene, assign the **MyScene** script and save it
- Create a new MyResource, assign the just created scene to the my_scene proeprty in the inspector and save it
- In the main scene of the project run the following code:
```
func _ready() -> void:
	preload("res://my_resource.tres").duplicate_deep(Resource.DEEP_DUPLICATE_ALL)
```

**Expected result**
- deep duplicate works, script is not duplicated

**Actual Result**
- The following error prompts
```
Parser Error: Class "MyScene" hides a global script class.
```

My understanding is the Script subresource of PackedScene is being duplicated and because of that is errors because of the repeated class_name

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/21025246/mrp.zip)

### PR DESCRIPTION
**Pull request by MarianoGnu**
This allows to duplicate PackedScenes safely
Fixes #108220

### CODE REVIEW

**Comment by RedMser** [comment]
Wouldn't a proper fix be to instead add `PROPERTY_USAGE_NEVER_DUPLICATE` to the script property? Or also adding a check for `property.name == "script"` or so.

Duplicating a script resource is fine, but it's largely undesired when done automatically in context of a scene. So just adding the type check seems too aggressive of a solution to me.

**Comment by MarianoGnu** [comment]
> Wouldn't a proper fix be to instead add `PROPERTY_USAGE_NEVER_DUPLICATE` to the script property? Or also adding a check for `property.name == "script"` or so.
> 
> Duplicating a script resource is fine, but it's largely undesired when done automatically in context of a scene. So just adding the type check seems too aggressive of a solution to me.

I can think of several arguments against that check
- there's no PropertyInfo variable here to peek the name, so is not even possible, at least from this call, i should check a level upper
- Someone could call their script variable "script" and not be an script
- Someone could make a custom variable in a script and not name it "script", but be an script
- That check is a string comparison that should need to be done before, and for each variable, i picked strategically the place to put this check to make sure the order of the checks is done from cheaper to more expensive, to have an early escape as soon as possible (to be fair this ended up being an StringName comparison i guess, but started as a fair concern)

About adding `PROPERTY_USAGE_NEVER_DUPLICATE` to all script properties, i considered that, i also considered adding it to all properties with type PackedScene too as mentioned in #108220
For now this is the less invasive solution that i came with that can solve the problem before 4.5 is released

**Comment by RedMser** [comment]
OK I looked a bit deeper, there's two sides to this.

On one side, a similar error #101001 was fixed the same way (filtering out the `Script` class as a whole). So there's precedent for fixing this error the "extreme" way. I personally don't agree with how this was solved either, but so be it...

On the other side, I already see logic that's *supposed* to filter out *specifically* `"script"` property on duplicate:

https://github.com/godotengine/godot/blob/1123d7fd9cf447e259cbb8fe16de5cf7bb810c39/core/io/resource.cpp#L394-L396

So it might be worth investigating how we even reach this point where it tries duplicating the script, since it seems like a safeguard was already added.

Anyway, for fixing the error for 4.5, it's probably fine to keep your solution as-is, since the parts I'm having problems with are entering niche territory (I'll argue for it below, but I don't want to die on this hill either).

Overall I'm worried that `script.duplicate()` works but `res.duplicate_deep(DEEP_DUPLICATE_ALL)` refuses to duplicate variables containing `Script`s. Sure it avoids a common user mistake, but also is inconsistent behavior of the engine.
As such, it should probably be documented that `Resource.duplicate_deep` never duplicates sub-resources of type `Script`.

---

> there's no PropertyInfo variable here to peek the name

Fair point.

> Someone could call their script variable "script" and not be an script

No, you can't:

image

> Someone could make a custom variable in a script and not name it "script", but be an script

As I mentioned, my stance is that duplicating a `Script` in and of itself *isn't a problem*. E.g. imagine having a GDScript that gets dynamically modified at runtime, I could see it make sense to duplicate variables containing `Script`s in this situation.

User can still add the never duplicate flag to the property manually to revert behavior, so it'd be fine.

> cheaper to more expensive

Yeah I assumed it would be `StringName` equality check, so comparison would likely not be too costly.

**Comment by MarianoGnu** [comment]
The `script` property is a member of Object, and as such is safe to believe it cannot be overriden, that being said, this case is different, because PackedScene does not have a property specifically for scripts, it has a collection of dependencies embeded in a dictionary with the metadatas of nodes to reconstruct the tree, we cannot just filter the scripts with a property name, there's potentially several scripts in the same PackedScene.

For reference, PackedScene has a unique proeprty called "_bundle" of type Dictionary:
`PropertyInfo(Variant::DICTIONARY, "_bundled", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_STORAGE | PROPERTY_USAGE_INTERNAL)` (this is the reason why the resource is being duplicated, is part of a dictionary, not a property in itself)
The property hints and usages of subresources included in this _bundle dictionary are the default for the Type of each resource

**Comment by MarianoGnu** [comment]
> Overall I'm worried that script.duplicate() works but res.duplicate_deep(DEEP_DUPLICATE_ALL) refuses to duplicate variables containing Scripts. Sure it avoids a common user mistake, but also is inconsistent behavior of the engine.
> As such, it should probably be documented that Resource.duplicate_deep never duplicates sub-resources of type Script.

This was in part the reason why i proposed #108299 to give users more control over what is duplicated and what not, but from internal disscussion on the gdscript chat, it seems the PR will be rejected in favor of implementing custom annotations (i am totally fine with that)
In any case, my PR was not fully working as intended, since the NEVER and ALWAYS flags seems to be less inportant than the DEEP_DUPLICATE_XXX argument

> As I mentioned, my stance is that duplicating a Script in and of itself isn't a problem. E.g. imagine having a GDScript that gets dynamically modified at runtime, I could see it make sense to duplicate variables containing Scripts in this situation.

This is a fair point, but having scripts accidentally duplicated because of a duplicate_deep is also a fair point. Users will mostly not know this is happening because they are indeed not meant to know this happens, if we wanted to support this behaviour, it should be an extra argument in deep_duplicate, and an extra parameter in `DuplicateParams`

> User can still add the never duplicate flag to the property manually to revert behavior, so it'd be fine.

They can, but this somewhat painful to do (hence #108299) you have to use get_property_list to peek what godot is creating, and then replicate the same but attaching the NEVER_DUPLICATE flag, is not something i would imagine a novice developper doing

>Yeah I assumed it would be StringName equality check, so comparison would likely not be too costly.

Sadly equiality is not enough, is_parent_class is used to ensure both GDScript as CSharp as any other script language is considered

File: core/io/resource.cpp [hunk 1]
```diff
@@ -298,6 +298,9 @@ Variant Resource::_duplicate_recursive(const Variant &p_variant, const Duplicate
 							DEV_ASSERT(false);
 						}
 					}
+					if (should_duplicate && ClassDB::is_parent_class(sr->get_class_name(), SNAME("Script"))) {
```
Comment (KoBeWi) [inline core/io/resource.cpp]:
```suggestion
					if (should_duplicate) {
						Ref<Script> scr = sr;
						if (scr.is_valid()) {
```

**Review by KoBeWi — APPROVED** [review]
This is the alternative I mentioned in #109425 (I didn't know someone already made it)
It's more hacky, but less invasive. I'm fine with either solution.

**Comment by MarianoGnu** [comment]
I like it is cheaper, but wonder which one is more readable 🤔 duplicating resources is not somethign you do every single frame, we can live with any of both.

What is the concensus? should i change the check?

**Comment by KoBeWi** [comment]
The check I suggested is somewhat a preferred style for checking RefCounted types, though in this case is a bit awkward. Could be changed to single line like `if (should_duplicate && Ref<Script>(sr).is_valid())`, but it's readability is even more arguable and I think we don't use such syntax anywhere else.

**Comment by clayjohn** [comment]
Discussed in the core meeting. This can be merged after the suggestion from Kobewi is applied!

**Comment by MarianoGnu** [comment]
Done

**Comment by Repiteo** [comment]
Thanks!
