### PR TITLE
C#: Add platform name to the exported data directory

### LINKED ISSUE #78385: Linux + C# : "Failed to initialize context for app" on exported project
### Godot version

Godot Engine v4.0.3.stable.mono.official.5222a99f5

### System information

Ubuntu 22.04.2 LTS

### Issue description

when exported project is launch it crash :

```
Godot Engine v4.0.3.stable.mono.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1650
 
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
Failed to initialize context for app: /mnt/nova/secure/workspace/wip/godot4/empty/build/data_empty_x86_64/empty.dll. Error code: 0x80008087
ERROR: hostfxr_initialize_for_dotnet_command_line failed with code: -2147450745
   at: initialize_hostfxr_self_contained (modules/mono/mono_gd/gd_mono.cpp:239)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: initialize_hostfxr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:316)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:411)
Erreur de segmentation (core dumped)
```

### Steps to reproduce

Linux export a simple project and run the .x86_64 binary

### Minimal reproduction project

Only one scene with one node with just one empty C# script

### PR DESCRIPTION
**Pull request by raulsntos**
- Since we publish self-contained assemblies, the contents of the data directory are platform specific so adding the platform name to the data directory.
- Fixes https://github.com/godotengine/godot/issues/78385.

### CODE REVIEW

File: modules/mono/godotsharp_dirs.cpp [hunk 1]
```diff
@@ -139,18 +171,37 @@ class _GodotSharpDirs {
...
 		api_assemblies_dir = api_assemblies_base_dir.path_join(GDMono::get_expected_api_build_config());
 #else // TOOLS_ENABLED
+		String platform = _get_platform_name();
 		String arch = Engine::get_singleton()->get_architecture_name();
 		String appname_safe = path::get_csharp_project_name();
-		String data_dir_root = exe_dir.path_join("data_" + appname_safe + "_" + arch);
+		String data_dir_root = exe_dir.path_join("data_" + appname_safe + "_" + platform + "_" + arch);
 		if (!DirAccess::exists(data_dir_root)) {
-			data_dir_root = exe_dir.path_join("data_Godot_" + arch);
+			data_dir_root = exe_dir.path_join("data_Godot_" + platform + "_" + arch);
```
Comment (raulsntos) [inline modules/mono/godotsharp_dirs.cpp:179]: Can we get rid of the fallback to `data_Godot`? It doesn't seem like our exporter ever generates a directory with that name.

File: modules/mono/godotsharp_dirs.cpp [hunk 2]
```diff
@@ -139,18 +171,37 @@ class _GodotSharpDirs {
...
+		}
+		// Fallback to directory name without the platform which was used in previous versions of Godot.
+		{
+			if (!DirAccess::exists(data_dir_root)) {
+				data_dir_root = exe_dir.path_join("data_" + appname_safe + "_" + arch);
+			}
+			if (!DirAccess::exists(data_dir_root)) {
+				data_dir_root = exe_dir.path_join("data_Godot_" + arch);
+			}
 		}
```
Comment (raulsntos) [inline modules/mono/godotsharp_dirs.cpp:189]: Do we really need this fallback? I think this is only useful when using a newer Godot executable than the one the game was exported with, which seems pretty rare to me.

Comment (RedworkDE) [reply modules/mono/godotsharp_dirs.cpp:189]: Also this is unlikely to work anyways as the size of the managed callbacks has most likely changed since whenever such an export format was used and the export cannot be loaded anyways.

File: modules/mono/godotsharp_dirs.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/mono/godotsharp_dirs.cpp:179]: Yeah I think we can remove it.

BTW, do we warn users well enough if the data dir is missing?

Comment (raulsntos) [reply modules/mono/godotsharp_dirs.cpp:179]: Not really, it seems we just crash when we inevitably fail to load hostfxr. In the terminal you'll at least get to see `ERROR: .NET: Failed to load hostfxr` but it's not very user-friendly since it doesn't explain why it couldn't find it.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

Would be good to improve the handling of a missing data dir, e.g. by showing an `OS.alert()` or at least a clear error message in the terminal, but that can be done in a follow-up.

**Review by RedworkDE — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
