### PR TITLE
[RichTextLabel] Fix `remove_paragraph` crash by popping current

### LINKED ISSUE #84202: Executing `RichTextLabel.remove_paragraph` function crashes Godot
### Godot version

4.2.beta.custom_build. 914445748

### System information

Ubuntu 22.04 CI

### Issue description

When executing (this code was automatically minimized, so it is possible, that an even more "minimal" project can be created)
```
extends Node
func _process(delta):
	var temp_variable239 = InputEventMagnifyGesture.new()
	var temp_variable421 = RichTextLabel.new()
	add_child(temp_variable421)
	temp_variable421.get_character_line(-62)
	temp_variable421.deselect()
	temp_variable421.set_hint_underline(true)
	temp_variable421.clear()
	temp_variable421.push_language("3802509553")
	temp_variable421.push_dropcap("", SystemFont.new(), -14, Rect2(Vector2(-7.0141019821167, 0), Vector2(0.69551467895508, -0.71851193904877)), Color(41.8949584960938, -41.9348487854004, -66.3293304443359, 1), -70, Color(-68.9253845214844, 67.6798553466797, 97.9244613647461, 1))
	temp_variable421.remove_paragraph(0)
```
Godot crashes:
```
Godot Engine v4.2.beta.custom_build.914445748 - https://godotengine.org
Vulkan API 1.2.0 - Forward Mobile - Using Vulkan Device #0: Unknown - SwiftShader Device (LLVM 10.0.0)

ERROR: Condition "p_string.is_empty()" is true.
   at: push_dropcap (scene/gui/rich_text_label.cpp:3365)
=================================================================
==20064==ERROR: AddressSanitizer: heap-use-after-free on address 0x607000fe8140 at pc 0x562145ea62a2 bp 0x7fff92543090 sp 0x7fff92543080
READ of size 8 at 0x607000fe8140 thread T0
    #0 0x562145ea62a1 in List<RichTextLabel::Item*, DefaultAllocator>::size() const core/templates/list.h:467
    #1 0x562145dd08bf in RichTextLabel::remove_paragraph(int) scene/gui/rich_text_label.cpp:3348
    #2 0x56213ce75e68 in void call_with_variant_args_ret_helper<__UnexistingClass, bool, int, 0ul>(__UnexistingClass*, bool (__UnexistingClass::*)(int), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:755
    #3 0x56213ce71dcf in void call_with_variant_args_ret_dv<__UnexistingClass, bool, int>(__UnexistingClass*, bool (__UnexistingClass::*)(int), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:534
    #4 0x56213ce6edbf in MethodBindTR<bool, int>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:496
    #5 0x562150c2f858 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:774
    #6 0x56214ffdf9aa in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #7 0x56213795988b in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #8 0x5621372534e2 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #9 0x562144a021ec in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #10 0x562144940798 in Node::_notification(int) scene/main/node.cpp:57
    #11 0x562136d644c3 in Node::_notificationv(int, bool) scene/main/node.h:49
    #12 0x562150c313e2 in Object::notification(int, bool) core/object/object.cpp:836
    #13 0x562144b00438 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #14 0x562144b036dc in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #15 0x562144af17d2 in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #16 0x5621363a2003 in Main::iteration() main/main.cpp:3613
    #17 0x5621360bcbe5 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #18 0x56213609b117 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #19 0x7f60fb429d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #20 0x7f60fb429e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #21 0x56213609aac4 in _start (/home/runner/work/Qarminer/Qarminer/godot.linuxbsd.editor.dev.x86_64.san+0x3a201ac4)
0x607000fe8140 is located 48 bytes inside of 80-byte region [0x607000fe8110,0x607000fe8160)
freed by thread T0 here:
    #0 0x7f60fc0b4537 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
    #1 0x56214f2dbd15 in Memory::free_static(void*, bool) core/os/memory.cpp:168
    #2 0x562145ea6692 in void memdelete<RichTextLabel::Item>(RichTextLabel::Item*) core/os/memory.h:112
    #3 0x562145dc73d8 in RichTextLabel::_remove_item(RichTextLabel::Item*, int, int) scene/gui/rich_text_label.cpp:3143
    #4 0x562145dd006e in RichTextLabel::remove_paragraph(int) scene/gui/rich_text_label.cpp:3337
    #5 0x56213ce75e68 in void call_with_variant_args_ret_helper<__UnexistingClass, bool, int, 0ul>(__UnexistingClass*, bool (__UnexistingClass::*)(int), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:755
    #6 0x56213ce71dcf in void call_with_variant_args_ret_dv<__UnexistingClass, bool, int>(__UnexistingClass*, bool (__UnexistingClass::*)(int), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:534
    #7 0x56213ce6edbf in MethodBindTR<bool, int>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:496
    #8 0x562150c2f858 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:774
    #9 0x56214ffdf9aa in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #10 0x56213795988b in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #11 0x5621372534e2 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #12 0x562144a021ec in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #13 0x562144940798 in Node::_notification(int) scene/main/node.cpp:57
    #14 0x562136d644c3 in Node::_notificationv(int, bool) scene/main/node.h:49
    #15 0x562150c313e2 in Object::notification(int, bool) core/object/object.cpp:836
    #16 0x562144b00438 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #17 0x562144b036dc in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #18 0x562144af17d2 in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #19 0x5621363a2003 in Main::iteration() main/main.cpp:3613
    #20 0x5621360bcbe5 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #21 0x56213609b117 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #22 0x7f60fb429d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
previously allocated by thread T0 here:
    #0 0x7f60fc0b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x56214f2dac67 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x56214f2dab78 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x562145ddd259 in RichTextLabel::push_language(String const&) scene/gui/rich_text_label.cpp:3577
    #4 0x562137b41011 in void call_with_variant_args_helper<__UnexistingClass, String const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:303
    #5 0x562137b3f446 in void call_with_variant_args_dv<__UnexistingClass, String const&>(__UnexistingClass*, void (__UnexistingClass::*)(String const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:450
    #6 0x562137b3d7b4 in MethodBindT<String const&>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:335
    #7 0x562150c2f858 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:774
    #8 0x56214ffdf9aa in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #9 0x56213795988b in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #10 0x5621372534e2 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #11 0x562144a021ec in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #12 0x562144940798 in Node::_notification(int) scene/main/node.cpp:57
    #13 0x562136d644c3 in Node::_notificationv(int, bool) scene/main/node.h:49
    #14 0x562150c313e2 in Object::notification(int, bool) core/object/object.cpp:836
    #15 0x562144b00438 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #16 0x562144b036dc in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #17 0x562144af17d2 in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #18 0x5621363a2003 in Main::iteration() main/main.cpp:3613
    #19 0x5621360bcbe5 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #20 0x56213609b117 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #21 0x7f60fb429d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
SUMMARY: AddressSanitizer: heap-use-after-free core/templates/list.h:467 in List<RichTextLabel::Item*, DefaultAllocator>::size() const
Shadow bytes around the buggy address:
  0x0c0e801f4fd0: 00 00 00 00 00 00 00 00 fa fa fa fa 00 00 00 00
  0x0c0e801f4fe0: 00 00 00 00 00 00 fa fa fa fa 00 00 00 00 00 00
  0x0c0e801f4ff0: 00 00 00 fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0e801f5000: 00 00 fa fa fa fa fd fd fd fd fd fd fd fd fd fd
  0x0c0e801f5010: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fa fa
=>0x0c0e801f5020: fa fa fd fd fd fd fd fd[fd]fd fd fd fa fa fa fa
  0x0c0e801f5030: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fd fd
  0x0c0e801f5040: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c0e801f5050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e801f5060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0e801f5070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==20064==ABORTING
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visible when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

   

### Steps to reproduce

Above

### Minimal reproduction project

Above

### PR DESCRIPTION
**Pull request by nickyfoo**
Fixes #84202 
In my investigation of the issue, it appears to be caused when `current` is pushed into `subitem_to_remove` in `RichTextLabel::remove_paragraph`. This calls memdelete on the pointer in `RichTextLabel::_remove_item`, and we get a dangling pointer.

My solution was to pop `current` up if it's being added as a sub item to be removed, which should be okay since we're removing them in reverse order.

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -3355,7 +3355,10 @@ bool RichTextLabel::remove_paragraph(const int p_paragraph) {
 	for (int i = subitem_to_remove.size() - 1; i >= 0; i--) {
 		List<Item *>::Element *subitem = subitem_to_remove[i];
 		had_newline = had_newline || subitem->get()->type == ITEM_NEWLINE;
-		_remove_item(subitem->get(), subitem->get()->line, p_paragraph);
+		if (subitem->get() == current) {
+			pop();
+		}
+		_remove_item(subitem->get(), p_paragraph, subitem->get()->line);
```
Comment (nickyfoo) [inline scene/gui/rich_text_label.cpp:3361]: Reordered the arguments because the signature is `RichTextLabel::_remove_item(Item *p_item, const int p_line, const int p_subitem_line)`

**Comment by nickyfoo** [comment]
Heya @bruvzg , bumping for review in case this slipped through the net!

(Sorry in advance, not familiar with the bumping rules here and it might've been bad to bump)

File: scene/gui/rich_text_label.cpp (hunk 1 above)
Comment (bruvzg) [reply scene/gui/rich_text_label.cpp:3361]: These arguments actually are always the same value, so it can be simplified:
```diff
diff --git a/scene/gui/rich_text_label.cpp b/scene/gui/rich_text_label.cpp
index 0b65daf712..6d5d7fa98a 100644
--- a/scene/gui/rich_text_label.cpp
+++ b/scene/gui/rich_text_label.cpp
@@ -3151,7 +3151,7 @@ void RichTextLabel::_add_item(Item *p_item, bool p_enter, bool p_ensure_newline)
 	queue_redraw();
 }
 
-void RichTextLabel::_remove_item(Item *p_item, const int p_line, const int p_subitem_line) {
+void RichTextLabel::_remove_item(Item *p_item, const int p_line) {
 	int size = p_item->subitems.size();
 	if (size == 0) {
 		p_item->parent->subitems.erase(p_item);
@@ -3160,7 +3160,7 @@ void RichTextLabel::_remove_item(Item *p_item, const int p_line, const int p_sub
 			current_frame->lines.remove_at(p_line);
 			if (p_line < (int)current_frame->lines.size() && current_frame->lines[p_line].from) {
 				for (List<Item *>::Element *E = current_frame->lines[p_line].from->E; E; E = E->next()) {
-					if (E->get()->line > p_subitem_line) {
+					if (E->get()->line > p_line) {
 						E->get()->line--;
 					}
 				}
@@ -3169,7 +3169,7 @@ void RichTextLabel::_remove_item(Item *p_item, const int p_line, const int p_sub
 	} else {
 		// First, remove all child items for the provided item.
 		while (p_item->subitems.size()) {
-			_remove_item(p_item->subitems.front()->get(), p_line, p_subitem_line);
+			_remove_item(p_item->subitems.front()->get(), p_line);
 		}
 		// Then remove the provided item itself.
 		p_item->parent->subitems.erase(p_item);
@@ -3377,7 +3377,7 @@ bool RichTextLabel::remove_paragraph(const int p_paragraph) {
 	for (int i = subitem_to_remove.size() - 1; i >= 0; i--) {
 		List<Item *>::Element *subitem = subitem_to_remove[i];
 		had_newline = had_newline || subitem->get()->type == ITEM_NEWLINE;
-		_remove_item(subitem->get(), subitem->get()->line, p_paragraph);
+		_remove_item(subitem->get(), p_paragraph);
 	}
 
 	if (!had_newline) {
diff --git a/scene/gui/rich_text_label.h b/scene/gui/rich_text_label.h
index 2f48600583..5c8585565d 100644
--- a/scene/gui/rich_text_label.h
+++ b/scene/gui/rich_text_label.h
@@ -461,7 +461,7 @@ private:
 	_FORCE_INLINE_ float _update_scroll_exceeds(float p_total_height, float p_ctrl_height, float p_width, int p_idx, float p_old_scroll, float p_text_rect_height);
 
 	void _add_item(Item *p_item, bool p_enter = false, bool p_ensure_newline = false);
-	void _remove_item(Item *p_item, const int p_line, const int p_subitem_line);
+	void _remove_item(Item *p_item, const int p_line);
 
 	String language;
 	TextDirection text_direction = TEXT_DIRECTION_AUTO;
```

**Review by bruvzg — APPROVED** [review]

**Comment by bruvzg** [comment]
Rebased and pushed my suggested change.

**Comment by akien-mga** [comment]
Thanks both!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
