### PR TITLE
Highlight warning lines in Script editor

### LINKED ISSUE #11706: Display a yellow background highlight for warnings like errors
### Describe the project you are working on

I was writing a function to find the intersections between a circle and spline

### Describe the problem or limitation you are having in your project

I had a hard-to-find bug where I was accidentally assigning a float to an int, resulting in the binary search not working as intended. It does generate a warning, but it is hard to find as it isn't highlighted anywhere

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Mark lines that have warnings in a visual way

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Draw a yellow line background behind lines that have warnings, prompting the user to look at the warning list, or inlay hints like Visual Studio

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

This improves the script editing experience out of the box

### PR DESCRIPTION
**Pull request by sockeye-d**
Adds a yellow highlight (customizable through the theme editor) to the script editor
image

Resolves godotengine/godot-proposals#11706

### CODE REVIEW

**Comment by arkology** [comment]
I think it should have transparency check to skip code if alpha is zero.

**Comment by sockeye-d** [comment]
> I think it should have transparency check to skip code if alpha is zero.

If the alpha is set to zero, warnings are added, then changed in the editor settings to something visible, it won't change until the next time warnings are updated. This is because it won't make the lines a color other than `Color(0.0, 0.0, 0.0, 0.0)` and so when it updates the line colors it won't find any that match. Also since errors don't do it and it's probably a negligible performance hit I don't think it's worth it

**Comment by arkology** [comment]
I understand you point.
But at the same time:
> Also since errors don't do it

Because users have errors if something is going wrong and usualy errors should be fixed. But there could by many warnings and they could be freely ignored.

This is just a suggestion (I'll rephrase previous comment) and not critical at the first glance.

**Comment by KoBeWi** [comment]
Checking for alpha would allow skipping double for loop. If setting the background color would have no effect, no reason to run this loop. Same could be done for errors.
Unless I'm misunderstanding something.

**Comment by sockeye-d** [comment]
Done, I also added the missing documentation that was causing the Linux mono build to fail I think

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

However, I think the default warning mark is too prominent by default and draws attention away from errors.

Default | Black (OLED) | Light
-|-|-
image | image | image

With opacity reduced by half on the warning mark color:

Default | Black (OLED) | Light
-|-|-
image | image | image

We should remember that many projects out there have dozens of warnings (if not hundreds) that were never noticed by users (and therefore not fixed), so we should ensure we don't highlight warnings too prominentl by default.

File: editor/editor_settings.cpp [hunk 1]
```diff
@@ -1075,6 +1075,7 @@ void EditorSettings::_load_godot2_text_editor_theme() {
 	_initial_set("text_editor/theme/highlighting/function_color", Color(0.4, 0.64, 0.81), true);
 	_initial_set("text_editor/theme/highlighting/member_variable_color", Color(0.9, 0.31, 0.35), true);
 	_initial_set("text_editor/theme/highlighting/mark_color", Color(1.0, 0.4, 0.4, 0.4), true);
+	_initial_set("text_editor/theme/highlighting/warning_color", Color(1.0, 0.8, 0.4, 0.2), true);
```
Comment (Calinou) [inline editor/editor_settings.cpp:1078]: Reduce opacity as mentioned in my review:

```suggestion
	_initial_set("text_editor/theme/highlighting/warning_color", Color(1.0, 0.8, 0.4, 0.1), true);
```

File: editor/themes/editor_theme_manager.cpp [hunk 2]
```diff
@@ -2608,6 +2608,7 @@ void EditorThemeManager::_generate_text_editor_defaults(ThemeConfiguration &p_co
 	const Color function_color =                  p_config.dark_theme ? Color(0.34, 0.7, 1.0) : Color(0, 0.225, 0.9, 1);
 	const Color member_variable_color =           p_config.dark_theme ? Color(0.34, 0.7, 1.0).lerp(p_config.mono_color, 0.6) : Color(0, 0.4, 0.68, 1);
 	const Color mark_color =                      Color(p_config.error_color.r, p_config.error_color.g, p_config.error_color.b, 0.3);
+	const Color warning_color =                   Color(p_config.warning_color.r, p_config.warning_color.g, p_config.warning_color.b, 0.3);
```
Comment (Calinou) [inline editor/themes/editor_theme_manager.cpp:2611]: Reduce opacity as mentioned in my review:

```suggestion
	const Color warning_color =                   Color(p_config.warning_color.r, p_config.warning_color.g, p_config.warning_color.b, 0.15);
```

Comment (sockeye-d) [reply editor/themes/editor_theme_manager.cpp]: I reduced the opacity in the latest commit

**Review by Calinou — APPROVED** [review]

**Comment by Calinou** [comment]
Looks good to me, please squash the commits together. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

**Comment by sockeye-d** [comment]
Commits are now squashed together

File: editor/plugins/script_text_editor.cpp [hunk 3]
```diff
@@ -1807,8 +1828,8 @@ void ScriptTextEditor::_notification(int p_what) {
 				break;
 			}
 			if (is_visible_in_tree()) {
-				_update_warnings();
 				_update_errors();
+				_update_warnings();
```
Comment (KoBeWi) [inline editor/plugins/script_text_editor.cpp:1832]: Does it make any difference?

File: editor/plugins/script_text_editor.cpp [hunk 4]
```diff
@@ -707,11 +726,13 @@ void ScriptTextEditor::_update_errors() {
 			bool is_folded_code_region = te->is_line_code_region_start(i) && te->is_line_folded(i);
 			te->set_line_background_color(i, is_folded_code_region ? folded_code_region_color : Color(0, 0, 0, 0));
 		} else {
-			for (const ScriptLanguage::ScriptError &E : errors) {
-				bool error_line = i == E.line - 1;
-				te->set_line_background_color(i, error_line ? marked_line_color : Color(0, 0, 0, 0));
-				if (error_line) {
-					break;
+			if (marked_line_color.a != 0) {
```
Comment (KoBeWi) [inline editor/plugins/script_text_editor.cpp:729]: You could do `else if` instead.

File: editor/plugins/script_text_editor.cpp [hunk 5]
```diff
@@ -637,6 +644,18 @@ void ScriptTextEditor::_update_warnings() {
 		warnings_panel->pop(); // Cell.
 	}
 	warnings_panel->pop(); // Table.
+	if (warning_line_color.a != 0.0) {
+		CodeEdit *te = code_editor->get_text_editor();
+		for (int i = 0; i < te->get_line_count(); i++) {
+			for (const ScriptLanguage::Warning &W : warnings) {
+				// maybe this should also include W.end_line
```
Comment (KoBeWi) [inline editor/plugins/script_text_editor.cpp:651]: If warnings can be multiline then yes, you could check if `i` is within the range. Looks like it's different from errors?

**Review by KoBeWi — APPROVED** [review]

File: editor/plugins/script_text_editor.cpp (hunk 5 above)
Comment (sockeye-d) [reply editor/plugins/script_text_editor.cpp:651]: Implemented both suggestions

Comment (KoBeWi) [reply editor/plugins/script_text_editor.cpp:651]: Then remove the comment.
And print_line 🙃

Comment (sockeye-d) [reply editor/plugins/script_text_editor.cpp]: Done

File: editor/plugins/script_text_editor.cpp [hunk 6]
```diff
@@ -637,6 +644,17 @@ void ScriptTextEditor::_update_warnings() {
 		warnings_panel->pop(); // Cell.
 	}
 	warnings_panel->pop(); // Table.
+	if (warning_line_color.a != 0.0) {
+		CodeEdit *te = code_editor->get_text_editor();
+		for (int i = 0; i < te->get_line_count(); i++) {
+			for (const ScriptLanguage::Warning &W : warnings) {
```
Comment (a-johnston) [inline editor/plugins/script_text_editor.cpp:650]: [saw this was already approved, definitely not a blocker]

I feel like it most cases it would be better to loop over the warnings and only mark the ranges indicated by each one. technically the same big O but in general I would expect several 1 line warnings and potentially 100s or 1000s of lines of code. The current code would be better as there were more warnings and also many overlapping the same lines.
```suggestion
		for (const ScriptLanguage::Warning &W : warnings) {
			for (int i = W.start_line - 1; i < W.end_line; i++) {
```

**Review by a-johnston — COMMENTED** [review]
In a future pr it could be cool to extend this by adding warning and error gutter indicators (or the classic jagged underline) as a place to provide the the message as a tooltip

**Comment by sockeye-d** [comment]
> In a future pr it could be cool to extend this by adding warning and error gutter indicators (or the classic jagged underline) as a place to provide the the message as a tooltip

I was planning on doing something like that too but that's way more difficult since I will need to add extra code to TextEdit to do inlayed hints or warning squiggles

**Comment by a-johnston** [comment]
I only glanced through the code but maybe it could be a part of the syntax highlighter. Either way definitely a thing for later

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by WinnerWind** [comment]
Congrats on this nice PR! Hoping it doesn't cause any issues with my highlighting PR.
