### PR TITLE
Fixed executing Viewport.notification() crashes Godot

### LINKED ISSUE #54100: Executing `Viewport.notification()` crashes Godot
### Godot version

3.4.beta.custom_build. 01ae4888e

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
	var temp_variable2716 = Viewport.new()
	temp_variable2716.notification(91, true)
	temp_variable2716.notification(26, true)
```

Godot crashes with this backtrace
```
ERROR: Condition "!data.tree" is true. Returned: nullptr
   at: get_tree (./scene/main/node.h:269)
scene/main/viewport.cpp:376:48: runtime error: member call on null pointer of type 'struct SceneTree'
scene/main/viewport.cpp:376:48: runtime error: member access within null pointer of type 'struct SceneTree'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v3.4.rc.custom_build (11d1b0387e51bf1582ba6e87c37e3e721d702339)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x17d976c] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:56)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46520) [0x7f21cd837520] (??:0)
[3] Viewport::_notification(int) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:376)
[4] Viewport::_notificationv(int, bool) (/mnt/Miecz/godot3.2/scene/main/viewport.h:90 (discriminator 14))
[5] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:929)
[6] MethodBind2<int, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:1523 (discriminator 19))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:918 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1175 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1049)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1184)
[11] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:57)
[12] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:45 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:163 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:37 (discriminator 3))
[15] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:929)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:977)
[17] SceneTree::idle(float) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:528 (discriminator 3))
[18] Main::iteration() (/mnt/Miecz/godot3.2/main/main.cpp:2186)
[19] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3641)
[20] godots(main+0x33e) [0x17cfd54] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[21] /lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0) [0x7f21cd81efd0] (??:0)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f21cd81f07d] (??:0)
[23] godots(_start+0x25) [0x17cf955] (??:?)
-- END OF BACKTRACE --
================================================================

```

This example was found by fuzzer, so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by vitika9**
Fixes #54100

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -462,6 +462,10 @@ void Viewport::_notification(int p_what) {
 			RenderingServer::get_singleton()->viewport_set_parent_viewport(viewport, RID());
 		} break;
 		case NOTIFICATION_INTERNAL_PHYSICS_PROCESS: {
+			if (!get_tree()) {
+				return;
+			}
+
```
Comment (akien-mga) [inline scene/main/viewport.cpp:468]: There's trailing whitespace on this line that should be removed (you should do it by editing this commit with `git commit --amend`, and then force push to update the PR, see [rebase docs](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase)).

Comment (Vitika9) [reply scene/main/viewport.cpp]: done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
