### PR TITLE
MultiNodeEdit Fix setting NodePath

### LINKED ISSUE #51963: Can't set exported NodePath on multiple selected nodes simultaneously
### Godot version

3.3.3 stable

### System information

Windows 10

### Issue description

See title.  Attempting to set a NodePath from the inspector for a field that was created in-script with the `export` keyword will pop up a special dialog rather than allowing a path to be specified as a string.  This unique behavior may be responsible for the missing functionality to set the NodePath on multiple nodes at once from this dialog.  The nodes can be on the same branch, using the same script, of the same class, but will not set any value if multiple nodes are selected.  This also occurs on instances which are their own scene.

### Steps to reproduce

1.  Create new project, add a main node and a child node.
2. Add script to child node with a line like `export (NodePath) var path`
3. Duplicate the node a few times in the editor. 
4. Select all instances of the child.
5. Attempt to set a NodePath (prefarably to the owner, which shouldn't have any particular conflict).

### Minimal reproduction project

_No response_

*Bugsquad edit (keywords for easier searching): MultiNodeEdit*

### PR DESCRIPTION
**Pull request by kleonc**
`NodePath` passed in is relative to the root `Node` of the edited scene which means that the target `Node` for the `NodePath`s being set were obtained incorrectly. This PR should fix this.

Fixes #51963.

Cherry-pickable `3.x`, `3.3`.

### CODE REVIEW

File: editor/multi_node_edit.cpp [hunk 1]
```diff
@@ -49,6 +49,11 @@ bool MultiNodeEdit::_set_impl(const StringName &p_name, const Variant &p_value,
 		name = "script";
 	}
 
+	Node *node_path_target = nullptr;
+	if (p_value.get_type() == Variant::NODE_PATH) {
+		node_path_target = es->get_node(p_value);
+	}
+
```
Comment (fire) [inline editor/multi_node_edit.cpp:56]: What happens when node_path_target is accessed when null?

Comment (kleonc) [reply editor/multi_node_edit.cpp:56]: It spams errors when used later in `get_path_to(node_path_target)`.
Actually I've realized it myself before reading your comment that `p_value` can be a `NodePath()` (it happens when clearing the path) which would lead to an error itself (in `es->get_node(p_value)`) and to `node_path_target` being null resulting in even more errors. Just pushed a fix.

File: editor/multi_node_edit.cpp [hunk 2]
```diff
@@ -63,9 +68,11 @@ bool MultiNodeEdit::_set_impl(const StringName &p_name, const Variant &p_value,
 		}
 
 		if (p_value.get_type() == Variant::NODE_PATH) {
-			Node *tonode = n->get_node(p_value);
-			NodePath p_path = n->get_path_to(tonode);
-			ur->add_do_property(n, name, p_path);
+			NodePath path;
```
Comment (fire) [inline editor/multi_node_edit.cpp:71]: I wonder if it's possible to move the above code here.

```c++
Node *node_path_target = nullptr;
if (p_value.get_type() == Variant::NODE_PATH && p_value != NodePath()) {
node_path_target = es->get_node(p_value);
}
```

Comment (kleonc) [reply editor/multi_node_edit.cpp:71]: Sure it's possible. I moved that part outside of the loop just because there's no need to keep calling `es->get_node(p_value)` on each iteration. But yeah, I guess performancewise it wouldn't be a problem (unless dealing with enormous number of selected nodes and/or complicated path). So yeah, I can move everything into the loop if that's preferred stylewise.

Comment (fire) [reply editor/multi_node_edit.cpp:71]: If you wanted to optimize, you would cache the `es->get_node(p_value)` as an object id.

Comment (kleonc) [reply editor/multi_node_edit.cpp:71]: I don't understand what you're suggesting / don't see benefit from using object id, can you elaborate?

Comment (KoBeWi) [reply editor/multi_node_edit.cpp:71]: If that code can be outside the loop then it's better outside. Also object id has no benefit, rather the opposite.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.4.
