### PR TITLE
[3.2] Add interpolation parameter to resize_to_po2()

### LINKED ISSUE #44379: [GLES2] Repeated textures look blurry in HTML5 builds
**Godot version:**
`3.2.3.stable.official`

**OS/device including version:**

The issue happens on HTML5 with GLES2 backend. Tested on Arch Linux with Firefox 83 and Chromium 87.0.4280.88.

Tested on two different computers, one has Intel i5-3320M and the other has NVIDIA GTX 1650 SUPER.

**Issue description:**

If you set "Repeat" to enabled in texture import settings, the texture will look blurry in HTML5 build, like it has been scaled with aliasing. This causes semitransparent edges and generally blurry look for pixel art.

The issue happens with GLES2 backend, it's not present on GLES3.

How it's supposed to look:

How it looks instead:

**Steps to reproduce:**

1. Add any pixel art texture to you project and make sure that you can see it up close.
2. Disable filtering and enable repeat in import settings and click "Reimport".
image
3. Export the project using HTML5 preset.
4. Run it in your browser. You will likely need to start a local HTTP server like this: `python -m http.server --bind 127.0.0.1`

**Minimal reproduction project:** [blurred_repeated_pixels.zip](https://github.com/godotengine/godot/files/5691552/blurred_repeated_pixels.zip)

There's already an HTML5 build in the `build/` directory.

### PR DESCRIPTION
**Pull request by theoratkin**
Add an optional `p_interpolation` parameter to `Image::resize_to_po2()` and call it in GLES2 rasterizer storage with either `INTERPOLATE_BILINEAR` or `INTERPOLATE_NEAREST` depending on `TEXTURE_FLAG_FILTER`.

This is equivalent of #44445 that closes #44379 in 3.2.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
I'm sure the commits that add the function and the doc update respectively could be unified.

And thanks for your first contribution to Godot!

**Comment by theogen-ratkin** [comment]
@YeldhamDev Done! And it's my pleasure. :smiley:

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -682,7 +682,7 @@ void RasterizerStorageGLES2::texture_set_data(RID p_texture, const Ref<Image> &p
 		if (img == p_image) {
 			img = img->duplicate();
 		}
-		img->resize_to_po2(false);
+		img->resize_to_po2(false, Image::INTERPOLATE_NEAREST);
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_storage_gles2.cpp:685]: Sorry for flip flopping. I changed my mind again. This should switch between nearest and linear based on the texture filter flag. 

```suggestion
		img->resize_to_po2(false, texture->flags & VS::TEXTURE_FLAG_FILTER ? Image::INTERPOLATE_BILINEAR : Image::INTERPOLATE_NEAREST);
```

**Review by clayjohn — DISMISSED** [review]

File: drivers/gles2/rasterizer_storage_gles2.cpp (hunk 1 above)
Comment (theogen-ratkin) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: Done!

**Comment by clayjohn** [comment]
Should be good to go once you squash the commits together. For simple changes like this we prefer one commit.

**Comment by theogen-ratkin** [comment]
@clayjohn Squashed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
