### PR TITLE
Prevent node rename shortcut from stealing focus from controls

### LINKED ISSUE #88102: Scene tree steals focus from Inspector when pressing Enter on a focused SpinSlider
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

So basically when you press Enter on a focused Inspector element, you get value popups for both Inspector element and whatever is the selected node in the Scene dock. And the latter gets the input:

https://github.com/godotengine/godot/assets/60579014/e8075793-0ac8-4c23-924d-35800c56c70f

### Steps to reproduce

1. Click on an input in the Inspector

2. Press Escape to hide the input popup.
The SpinSlider control itself still has the focus. You can use arrow buttons to navigate to other SpinSliders

3. Press Enter to edit
You'll get 2 different input popups in 2 different parts of the editor UI, both of which look visually focused, and the input goes into Scene tree's one

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by passivestar**
Adds a check for controls that may react to `Enter` to prevent a conflict on macOS. Fixes #88102

### CODE REVIEW

**Review by ajreckof — APPROVED** [review]
This is something that has been a huge pain for quite some time. I haven't tested it but code looks good.

**Comment by KoBeWi** [comment]
The bug only occurs, because the default shortcut uses Enter. You can reproduce it on other systems if you manually assign Enter shortcut for renaming or other action. I wonder if other docks are affected too (considering non-default shortcuts).

I think instead of checking for Range you could add ``is_text_field()` EditorSpinSlider.

**Comment by passivestar** [comment]
> I wonder if other docks are affected too

Nope, no other dock reacts to enter like this

> I think instead of checking for Range you could add is_text_field() to EditorSpinSlider

Seems reasonable

**Review by KoBeWi — APPROVED** [review]
This makes SceneTree shortcuts unusable when a Button is focused. Not sure if it's a problem though, as editor viewports can steal focus very easily so it shouldn't be noticeable.

**Comment by passivestar** [comment]
Now only the rename shortcut is prevented if a button is focused

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -157,7 +158,11 @@ void SceneTreeDock::shortcut_input(const Ref<InputEvent> &p_event) {
 	}
 
 	if (ED_IS_SHORTCUT("scene_tree/rename", p_event)) {
-		_tool_selected(TOOL_RENAME);
+		// Prevent renaming if a button is focused
+		// to avoid conflict with Enter shortcut on macOS
+		if (!focus_owner || !Object::cast_to<BaseButton>(focus_owner)) {
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:163]: That's... very specific 🙃
The issue only exists because of a default shortcut. Shortcuts are rebindable, so it doesn't solve all problems.
But eh, technically it fixes the linked issue.

Comment (passivestar) [reply editor/scene_tree_dock.cpp:163]: It is very specific and the code is not as pretty :). But previous code didn't make sense though... Blocking all shortcuts seems excessive, even if it's a rare encounter it doesn't feel good if nothing happens when you press a shortcut. If user rebinds to conflicting shortcuts it's a different story I think

**Comment by akien-mga** [comment]
Thanks!
