### PR TITLE
Several improvements to GridMap.

### LINKED ISSUE #10697: Freelook mode does not play well with Gridmap editor
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 26 - Godot master HEAD

**Issue description:**

The RMB shortcut for freelook is conflicting with the delete action in the Gridmap editor.
More importantly, I sometimes get stuck in freelook mode which makes the WASD keys both move me around as well as rotate the object. One time I couldn't get into freelook at all so there's variation in the bug.

**Steps to reproduce:**
Use freelook in gridmap editor.

**Link to minimal example project:**

3D platformer demo

### PR DESCRIPTION
**Pull request by djrm**
closes  #10697

also changed the appearance of the editor:

screenshot from 2017-10-29 14-36-56,

of course thats up for discussion, but i think the change makes more sense, and should be also implemented in tilemap.

### CODE REVIEW

File: modules/gridmap/grid_map_editor_plugin.cpp [hunk 1]
```diff
@@ -54,8 +56,18 @@ void GridMapEditor::_configure() {
 
 void GridMapEditor::_menu_option(int p_option) {
 
+	bool using_freelook = Input::get_singleton()->is_mouse_button_pressed(BUTTON_RIGHT);
```
Comment (akien-mga) [inline modules/gridmap/grid_map_editor_plugin.cpp]: Isn't there a way to know that without hardcoding an input check? @Zylann is about to add support for toggling freelook with a hotkey.

Comment (Zylann) [reply modules/gridmap/grid_map_editor_plugin.cpp]: I agree that you shouldn't imply RMB means freelook

Comment (djrm) [reply modules/gridmap/grid_map_editor_plugin.cpp]: yes thats why i added the flag, its true, that freelook mode could be toggled in different ways.

Comment (Zylann) [reply modules/gridmap/grid_map_editor_plugin.cpp]: That means we would need to change Gridmap if freelook changes... which isn't good design (not DRY and no SoC). Currently the only true way to access this info is with `SpatialEditorViewport::is_freelook_active()` though...

Comment (djrm) [reply modules/gridmap/grid_map_editor_plugin.cpp]: @Zylann that flag is only used to avoid rotation of tiles, if frelook, or any other shortcut / mode, changes grid map and other stuff will need to change (that flag might even be irrelevant on such cases), because of the possible conflicts, so this is not about design, godot works this way, maybe later we could have a better input handling mechanism.

Comment (Zylann) [reply modules/gridmap/grid_map_editor_plugin.cpp]: Note that when I say "consume events", Godot already supports this. If using that feature isn't enough then I don't know... but I can say your check will fail as soon as I PR the feature proposed in https://github.com/godotengine/godot/issues/10463#issuecomment-340283571

Comment (djrm) [reply modules/gridmap/grid_map_editor_plugin.cpp]: @Zylann also consider that such navigation mode, will make grid map editing almost unusable, or very hard at least (it will also override QWER keys for spatial gizmos), but yeah, im not sure how people will use it, also im not sure how to fix that in a smarter way, i mean there will be something here that requires knowledge of the general viewport shortcuts.

**Comment by reduz** [comment]
Some questions:
1)  would this not affect Maya style keybindings?
2) why not something like ctrl-mouse button to erase or optionally adding a brush selection icon menu? (paint, erase, select)?

**Comment by reduz** [comment]
any hopes of fixing this before the beta?

**Comment by djrm** [comment]
@reduz im a bit lost, i cant figure out a way to capture the events produced by spatial editor so they dont propagate to the gridmap shortcuts or input events, thats the only thing im missing here.

**Comment by reduz** [comment]
it's the opposite, you have to allow the events that go to gridmap editor
to continue to spatial editor by returning false instead of true

**Comment by djrm** [comment]
i updated this to consider when freelook is active.
