### PR TITLE
Fix ruler tool sticks after right click

### LINKED ISSUE #93043: Ruler tool stuck after right click
### Tested versions

4.3 beta1 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/85199fc5-ee42-434d-9797-84aa957efd4d

### Steps to reproduce

1. Go to 2D editor and enable ruler tool (R)
2. Start measuring by holding LMB
3. While still holding the button, right-click to open context menu
4. Left click to close the menu
5. The ruler is still visible despite no buttons pressed

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MannyFluss**
ruler tool prevents new nodes from being added while ruler is active.

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/issues/93043*

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please make the PR title more descriptive, describing what you have done instead of what issue number you have fixed

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -2525,6 +2525,11 @@ bool CanvasItemEditor::_gui_input_ruler_tool(const Ref<InputEvent> &p_event) {
 		ruler_tool_origin = snap_point(viewport->get_local_mouse_position() / zoom + view_offset);
 	}
 
+	if (b.is_valid() && b->get_button_index() == MouseButton::RIGHT && ruler_tool_active == true) {
```
Comment (AThousandShips) [inline editor/plugins/canvas_item_editor_plugin.cpp:2528]:
```suggestion
	if (b.is_valid() && b->get_button_index() == MouseButton::RIGHT && ruler_tool_active) {
```

**Comment by Chaosus** [comment]
@AThousandShips Hm, fox? Maybe fix?

**Comment by AThousandShips** [comment]
Autocorrect strikes again!

**Comment by KoBeWi** [comment]
I think right click should cancel the operation instead of doing nothing.

**Comment by MannyFluss** [comment]
should it allow the add child popup menu to appear or just cancel the ruler

**Comment by KoBeWi** [comment]
Just cancel.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 2]
```diff
@@ -2525,6 +2525,12 @@ bool CanvasItemEditor::_gui_input_ruler_tool(const Ref<InputEvent> &p_event) {
 		ruler_tool_origin = snap_point(viewport->get_local_mouse_position() / zoom + view_offset);
 	}
 
+	if (b.is_valid() && b->get_button_index() == MouseButton::RIGHT && ruler_tool_active) {
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp:2528]:
```suggestion
	if (ruler_tool_active && b.is_valid() && b->get_button_index() == MouseButton::RIGHT) {
```
Cheaper checks first.

**Review by KoBeWi — APPROVED** [review]
Remember to squash the commits into 1.

**Comment by MannyFluss** [comment]
how do I squash the commits into one? or is that for someone else to do.

**Comment by KoBeWi** [comment]
See https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase

**Comment by MannyFluss** [comment]
for future reference, I should be using amends for small changes like this?

**Comment by KoBeWi** [comment]
Having multiple commits make it easier to follow changes, but more difficult to resolve conflicts. At the end you are expected to squash into single commit anyway, so use what works better for you.
Also it's better to avoid accepting changes or rebasing using the GitHub buttons, because they make the PR more difficult to squash.

**Review by AThousandShips — APPROVED** [review]

**Comment by MannyFluss** [comment]
I have learned a lot from this, hopefully next pr I do goes a bit smoother!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
