### PR TITLE
[TextEdit] Update syntax highlighting when IME composition string is updated.

### LINKED ISSUE #102430: IME in progress syntax highlight color is wrong in some cases
### Tested versions

Godot v4.4.beta2 and v4.3.stable
Didn't test other versions

### System information

Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 32.0.15.6614) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads)

### Issue description

When typing in the IME, syntax highlighting uses the wrong color if there is a different colored section after it.
This can affect the color of the text after the IME.

See:

https://github.com/user-attachments/assets/ccf2927c-738e-436d-b946-67706244f53e

After the IME is accepted, it gets updated so it is not a big issue.

### Steps to reproduce

1. Have multiple colored regions next to each other, like `("") #`
2. Type using the IME

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/102430

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -186,7 +186,15 @@ _FORCE_INLINE_ String TextEdit::Text::operator[](int p_line) const {
 	return text[p_line].data;
 }
 
-void TextEdit::Text::invalidate_cache(int p_line, int p_column, bool p_text_changed, const String &p_ime_text, const Array &p_bidi_override) {
+_FORCE_INLINE_ const String &TextEdit::Text::get_text_with_ime(int p_line) const {
+	if (text[p_line].ime_data.length() > 0) {
```
Comment (KoBeWi) [inline scene/gui/text_edit.cpp:190]:
```suggestion
	if (!text[p_line].ime_data.is_empty()) {
```

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -209,20 +217,14 @@ void TextEdit::Text::invalidate_cache(int p_line, int p_column, bool p_text_chan
...
-			TS->shaped_text_set_bidi_override(text_line.data_buf->get_rid(), p_bidi_override);
-		}
-	} else {
-		if (p_text_changed) {
-			text_line.data_buf->add_string(text_line.data, font, font_size, language);
-		}
-		if (!text_line.bidi_override.is_empty()) {
-			TS->shaped_text_set_bidi_override(text_line.data_buf->get_rid(), text_line.bidi_override);
-		}
+	const String &t = (text_line.ime_data.length() > 0) ? text_line.ime_data : text_line.data;
```
Comment (KoBeWi) [inline scene/gui/text_edit.cpp:220]: Something more descriptive than `t` would be nice.

**Review by KoBeWi — APPROVED** [review]
Fixes the bug.

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
