### PR TITLE
GDScript: Solve `_populate_class_members()` cyclic dependency problem 

### LINKED ISSUE #78146: Unexpected "Parser Error : Identifier not found" when using parent class member
### Godot version

4.0.2

### System information

Linux Mint 21

### Issue description

On the minimal reproduction project, with a 3 level hierarchy and 2 autoloads, when running the game we get a parse error in daughter.gd where we use a parent member.

**Additional remarks :** 
- We have a circular dependency involving one of the autoloads : Autoload2 references Daughter which references Mother which references GrandMother which references Autoload2
- Autoload1 references Mother which references GrandMother which references Autoload2
- We don't have any error if we switch the 2 autoloads order in Project Settings
- We get the same error if _member is put in GrandMother class instead of Mother class
- We still get the issue if we disable Autoload1 in Project Settings

**A quick look in Godot source code :**
- GDScriptCache::full_gdscript_cache contains invalid scripts (ie script->is_valid() is false)
- I think the engine tries to compile GrandMother, then Daughter (but it fails), then Mother

(This issue might be related to https://github.com/godotengine/godot/issues/75388.)

### Steps to reproduce

To get the parse error :
- Open the minimal reproduction project
- Run the game
You'll get `Parser Error: Identifier not found: _member`.

### Minimal reproduction project

[ParseError_Project.zip](https://github.com/godotengine/godot/files/11725756/ParseError_Project.zip)

### LINKED ISSUE #79153: Project broken following upgrade from 4.0.3 - "Parser Error: Identifier not found: (x)" error on all child classes from a global script class
### Godot version

4.1 Stable

### System information

Linux Mint 21.1 - Godot 4.1 Stable - Vulkan (Forward+) - i7-12700K - RTX 2060

### Issue description

Hi folks!

My project worked back on Godot 4.0.3 but since upgrading to 4.1 the project instantly crashes when testing, with the parser reporting that it was unable to find pretty much all inherited members with the following error:

Parser Error: Identifier not found: [variable name here]

My characters are currently made up of three classes, starting with Actor_Base inheriting from CharacterBody3D, then two child classes named Actor_Simple and Actor_Player_NPC inheriting from Actor_Base, which can be found in the project’s Scripts/Actors folder. 

To explain the problem, two members inherited from Actor_Base that first manifested this problem in my child classes after upgrading were “ActorActive” and “ActorAlive”, both of which appear to be correctly recognised as inherited members from Actor_Base in child scripts by the editor’s script parser, but no longer seem to be detected as inherited members by the in-game script parser, instantly causing a crash.

Commenting out each now-offending variable call revealed it appears to have a problem with pretty much every member inherited from my custom parent class. Putting “self.” at the start of each call appeared to work around the issue, but this meant that another script/node that instances these actors broke as it was unable to access and set the inherited “ActorDefinition” resource member.

As even the editor’s script parser can’t find any issues with these scripts, I am at a loss for what’s happened here.

_Unfortunately as I can’t guarantee that I can reproduce the same symptoms for the same reasons on a minimal project, I have included the entire project as the Minimal Reproduction Project._ 

To reiterate, the project worked just fine back on 4.0.3, but has completely broken since the upgrade, with this issue backporting to 4.0.3 and thus leaving me stranded. I have also tried to start a new project and copy the original files in, which produced the same results.

Any help is greatly appreciated!

-CFR

### Steps to reproduce

Run test on included project

### Minimal reproduction project

[TPAction_Broken_GH.zip](https://github.com/godotengine/godot/files/11981632/TPAction_Broken_GH.zip)

### PR DESCRIPTION
**Pull request by anvilfolk**
Fixes #78146 and fixes #79153 (which is pretty much a duplicate). The issue occurs because `_populate_class_members(descendant_class)` is getting called during a call for `_populate_class_members(ancestor_class)`. Thus class members of ancestors are _not_ available for the descendant class when it is populating its own, resulting the `identifier not found` error of the linked issue when the descendant class gets compiled.

### Issue 🔥 
`GDScriptCompiler::_populate_class_members()` sets up the datastructures so that the compiler knows the addresses of member variables of the class being compiled. For this, it needs to know members its base class, so that those are also addressable. In order to obtain those members, it asks for the fully compiled script of the base class using `GDScriptCache::get_full_script()`.

However in certain configurations of dependencies, the base class of the current class may depend on a descendant class. Let's say `Daughter(D) extends Mother(M) extends Grandmother(GM)`, as in the linked issue. If you start by _compiling_ (not just analyzing) M, that requires GM's class members, so you `get_full_script(GM)`, but if `GM` somehow references `D` in a way that asks for its `get_full_script(D)`, then `D` will run its `_populate_class_members()` without `M` having hers populated from `GM`.

Oof, that's a mouthful.

I don't believe it is possible to replicate the issue within the test framework, as it relies on global class names that exist in different files. Instead, I am attaching 🐛 [MRP.zip](https://github.com/godotengine/godot/files/11992352/MRP.zip) 🐞, which causes the issue when running the scene, before this PR, but works properly after this PR.

The dependency is as follows: `Daughter extends Mother extends Grandmother`, with `Grandmother` referring to (but not extending `Daughter`), and `Mother` being the first file loaded, in this case by being attached to the main scene node.

### Solution ⚕️ 

The solution here was to make it so that `_populate_class_members()` did not require `get_full_script()`, but instead only requires the shallow script (which does resolve any necessary inheritance dependencies), followed by calling its `_populate_class_members()`. This no longer triggers `get_full_script()`, and so descendant classes don't get compiled before their base classes are done populating their members.

### Concerns 😨 
I'm not super well versed in the meta-organization of the GDScript infrastructure, so I wonder whether this is the best solution. This doesn't so much solve cyclic dependencies as it sidesteps them insofar as `_populate_class_members` is concerned. Maybe that's not so bad, since it's such a specific case?

Either way, I'd love to see a refactor of the way scripts are loaded, maybe doing away with `get_shallow/full_script` and using `GDScriptCache/raise_status()` to give us more fine-grained control over what is needed at each point in time, and making `GDScript::reload()`, which `get_full_script()` relies on, a little less monolithic.

### CODE REVIEW

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -787,11 +787,11 @@ Error GDScript::reload(bool p_keep_state) {
 	err = compiler.compile(&parser, this, p_keep_state);
 
 	if (err) {
+		_err_print_error("GDScript::reload", path.is_empty() ? "built-in" : (const char *)path.utf8().get_data(), compiler.get_error_line(), ("Compile Error: " + compiler.get_error()).utf8().get_data(), false, ERR_HANDLER_SCRIPT);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript.cpp:790]: Right now we don't get compilation-related warnings in the editor. This line enables them. This does not mean analyzer errors, which presumably there are none of.

Compilation errors, if the analyzer passes, are _our_ problem, not a game developer's, so I understand the desire to hide them. But if the error only occurs when game devs run the game, that just puts a barrier towards bug reporting/fixing.

Comment (adamscott) [inline modules/gdscript/gdscript.cpp:790]: It's a good idea to move the error to display it, whether it can run or not.

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -2698,8 +2698,9 @@ Ref<GDScript> GDScriptLanguage::get_script_by_fully_qualified_name(const String
 
 Ref<Resource> ResourceFormatLoaderGDScript::load(const String &p_path, const String &p_original_path, Error *r_error, bool p_use_sub_threads, float *r_progress, CacheMode p_cache_mode) {
 	Error err;
+	ERR_PRINT(vformat("ResourceFormatLoaderGDScript::load(%s)", p_path));
 	Ref<GDScript> scr = GDScriptCache::get_full_script(p_path, err, "", p_cache_mode == CACHE_MODE_IGNORE);
-
+
```
Comment (adamscott) [inline modules/gdscript/gdscript.cpp:2703]: I think the formater will not like this added tab.

File: modules/gdscript/gdscript_cache.cpp [hunk 3]
```diff
@@ -251,6 +251,8 @@ Ref<GDScript> GDScriptCache::get_shallow_script(const String &p_path, Error &r_e
 		return singleton->shallow_gdscript_cache[p_path];
 	}
 
+	ERR_PRINT(vformat("GDScriptCache::get_shallow_script(%s)", p_path));
```
Comment (adamscott) [inline modules/gdscript/gdscript_cache.cpp:254]: Is this a debug print?

Comment (anvilfolk) [reply modules/gdscript/gdscript_cache.cpp:254]: Yes, there are still quite a few debug prints in several places so that I can see what gets called when. Order of these different calls was really important, and it still is as we're working on other regressions this "fix" apparently introduces 😅

**Comment by anvilfolk** [comment]
Currently running into failure of the `out_of_order_external.gd` test, but only when running the tests. It works both in-editor and when directly running the scene 🤔 Will keep investigating.

**Comment by anvilfolk** [comment]
> Currently running into failure of the `out_of_order_external.gd` test, but only when running the tests. It works both in-editor and when directly running the scene 🤔 Will keep investigating.

This appears to have been caused by the fact that the test runner doesn't use `ResourceLoader::load()` to load a `GDScript`, it creates it itself. This meant that `GDScript::path` was being set but `Resource::path` was empty, which meant that `GDScriptCache::finish_compiling(main_script->get_path())`, which grabs the Resource's path, was passing it the empty string, and thus `finish_compiling` was doing a no-op.

File: modules/gdscript/gdscript_compiler.cpp [hunk 4]
```diff
@@ -2968,7 +2973,7 @@ Error GDScriptCompiler::compile(const GDScriptParser *p_parser, GDScript *p_scri
 		GDScriptCache::add_static_script(p_script);
 	}
 
-	return GDScriptCache::finish_compiling(main_script->get_path());
+	return GDScriptCache::finish_compiling(main_script->path);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_compiler.cpp:2976]: This was the issue with testing, which doesn't use `ResourceLoader::load()` to load scripts, meaning that `Resource::path`, which you get using `main_script->get_path()` was empty, so that `GDScriptCache::finish_compiling()` was getting an empty string and being a no-op :)

**Review by adamscott — APPROVED** [review]
Great work, ocean!

File: modules/gdscript/gdscript_compiler.cpp [hunk 5]
```diff
@@ -2591,7 +2591,12 @@ Error GDScriptCompiler::_populate_class_members(GDScript *p_script, const GDScri
 					_set_error(vformat(R"(Could not find class "%s" in "%s".)", base->fully_qualified_name, base->path), nullptr);
 					return ERR_COMPILATION_FAILED;
 				}
-				ERR_FAIL_COND_V(!base->is_valid() && !base->reloading, ERR_BUG);
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_compiler.cpp:2594]: This is what I'm worried about! I haven't noticed the absence of this causing problems in the small tests I have done, but I'd love to see this merged so we can fix any regressions this might lead to.

Comment (anvilfolk) [reply modules/gdscript/gdscript_compiler.cpp:2594]: I believe that the checks above should cause the function to return early in the case of errors so that this isn't necessary. But you never know when things are this subtle :)

**Comment by YuriSizov** [comment]
Sure, let's go ahead with this. Thanks!

**Comment by anvilfolk** [comment]
Nice, thank you! Let's keep an eye out for potential regressions :)

**Comment by YuriSizov** [comment]
Given the regressions I'd err on the side of caution and skip this from cherry-picking. If there is still desire to bring this to 4.1.x, I'd appreciate a summary of the PRs that need to be picked and the stability of this change. But given that some of the fixes are pretty recent, I'd at least give it more time.

**Comment by anvilfolk** [comment]
The bug this fixes can be pretty project-stopping with unclear or impossible workarounds, but it only affects with cyclic dependencies and specific load orders. Unless we see a lot of folks complaining about class members that aren't recognized in 4.1, I think you're right in letting this + the recent fixes stew a little longer in 4.2 :)

The current other PRs that continue this effort to fix cyclic dependencies in compilation are #81577 and #81201. If
