### PR TITLE
Fix incorrect `KEY_MODIFIER_MASK` value

### LINKED ISSUE #89775: Incorrect enum value of KeyModifierMask.MODIFIER_MASK
### Tested versions

- Reproducible in: master branch

### System information

All

### Issue description

File core/os/keyboard.h, line 252 contains incorrect value assignment:
`MODIFIER_MASK = (0x7F << 22), ///< Apply this mask to isolate modifiers.`

Correct value assignment is:
`MODIFIER_MASK = (0x7E << 22)`

### Explanation
22nd bit is part of Key enum in form of Key.SPECIAL value and not KeyModifierMask enum, as no value in KeyModifierMask enum contains 22nd bit set.

In other words `KeyModifierMask.CODE_MASK & KeyModifierMask.MODIFIER_MASK` must evaluate to zero.

### Minimal reproduction project (MRP)

None

### PR DESCRIPTION
**Pull request by yelloweennnn**
This pull request fixes an incorrect value assignment for `MODIFIER_MASK` in keyboard.h and @GlobalScope.xml.

- Updated the `MODIFIER_MASK` to `0x7E << 22` to isolate modifier keys correctly, ensuring that it does not interfere with the `Key.SPECIAL` value.

I tested the solution by checking that the result of the `AND` operation between `MODIFIER_MASK` and `CODE_MASK` returned `0`, confirming that the modifier mask is now correctly configured.

(Sorry for the confusion with the previous PR; I'm new to this and accidentally included others' changes, so I created this new one for clarity.)

Fixes https://github.com/godotengine/godot/issues/89775

### CODE REVIEW

**Review by Sauermann — DISMISSED** [review]
This PR changes the API which requires additional steps. You can find relevant information in the docs:
https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html

File: core/os/keyboard.h [hunk 1]
```diff
@@ -249,7 +249,7 @@ enum class Key {
 
 enum class KeyModifierMask {
 	CODE_MASK = ((1 << 23) - 1), ///< Apply this mask to any keycode to remove modifiers.
-	MODIFIER_MASK = (0x7F << 22), ///< Apply this mask to isolate modifiers.
+	MODIFIER_MASK = (0x7E << 22), ///< Apply this mask to isolate modifiers.
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply core/os/keyboard.h:252]: > Currently the upper 9 bits are reserved for modifiers

Not sure if `KPAD` and `GROUP_SWITCH` should be considered modifiers.

But both seems to be unused:
- `GROUP_SWITCH` flag seems to be completely unused (I have no idea what it was intended for).
- `KPAD` flag is parsed by macOS native menu code, but it must an oversight, since it's never set by any code.

I would probably mask it like this:

```
0-20  Unicode value       |1|
21    Reserved            |1| CODE_MASK
22    Special key flag    |1|
23    Reserved                 |2| Keep reserved in case we want to add some other special flag.
24    CTRL or CMD flag              |3|
25    SHIFT flag                    |3|
26    ALT flag                      |3|
27    META flag                     |3| MODIFIER_MASK
28    CTRL flag                     |3|
29    (KPAD) Reserved               |3|
30    (GROUP_SWITCH) Reserved       |3|
31    Reserved                           |4| Sign bit, keep clean to avoid negative values if it's used with int32_t API.
```

[the remark this answers is not in the document]
Comment (Sauermann) [reply core/os/keyboard.h:252]: Sounds good, so that would boil down to:
```suggestion
	MODIFIER_MASK = (0x7F << 24), ///< Apply this mask to isolate modifiers.
```

**Comment by Yelloween10** [comment]
> This PR changes the API which requires additional steps. You can find relevant information in the docs: https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html

I read the docs and I'm confused about how I should continue in this situation. How should I approach this?

**Comment by DarkyMago** [comment]
> > This PR changes the API which requires additional steps. You can find relevant information in the docs: https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html
> 
> I read the docs and I'm confused about how I should continue in this situation. How should I approach this?

you need to add expected changes to API in the correct `.expected` file in `misc/extension_api_validation/`

basically you add
```
GH-%pull-requestID%
----------------------------
%expected validation error%
```

you should find the expected validation error in the failed check that has been run on your PR ([this one](https://github.com/godotengine/godot/actions/runs/11470067485/job/31918891198?pr=98441)),
or by running the `misc/scripts/validation_extension_api.sh`.

File: core/os/keyboard.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (akien-mga) [reply core/os/keyboard.h:252]: @Yelloween10 Please see the above suggestion.

[the remark this answers is not in the document]
Comment (Yelloween10) [reply core/os/keyboard.h:252]: > @Yelloween10 Please see the above suggestion.

I was just working on it at the moment. I was busy for a few weeks, I have time to do it now.

**Comment by Yelloween10** [comment]
Is there anything I should do?

**Comment by AThousandShips** [comment]
You've added unrelated changes to the api-validation files, you need to resolve that conflict

**Comment by Yelloween10** [comment]
I noticed that the changes I made eventually ended up getting conflicts because of the new changes. I tried adding my original change at the end again, but it still says that there are conflicts.

File: misc/extension_api_validation/4.3-stable.expected [hunk 2]
```diff
@@ -122,3 +122,93 @@ GH-98918
 Validate extension JSON: Error: Field 'classes/FileAccess/methods/open_encrypted/arguments': size changed value in new API, from 3 to 4.
 
 Optional argument added to allow setting initialization vector. Compatibility method registered.
+
+
+GH-98972
+--------
+Validate extension JSON: Error: Field 'classes/TranslationServer/methods/standardize_locale/arguments': size changed value in new API, from 1 to 2.
+
+Optional argument added. Compatibility method registered.
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.3-stable.expected:131]: You've added a lot here that I'm not sure where it comes from, did you copy these over from the 4.2 file?

Comment (Yelloween10) [reply misc/extension_api_validation/4.3-stable.expected:131]: I copied the lines from `4.3-stable.expected` and put my changes at the end. I thought that it would fix the message "This branch has conflicts that must be resolved". I did that because my changes got outdated from the new lines inside of the `4.3-stable.expected` file.

Comment (AThousandShips) [reply misc/extension_api_validation/4.3-stable.expected:131]: You need to rebase your branch as you are behind and you are making these changes on top of older code, you shouldn't copy what's in these files right now but rebase instead and just add your content

Comment (Yelloween10) [reply misc/extension_api_validation/4.3-stable.expected:131]: How can I do that exactly? The last time I tried it, I ended up accidentally ruining the entire PR. Sorry about the questions, I'm nervous about it that.

Comment (AThousandShips) [reply misc/extension_api_validation/4.3-stable.expected:131]: See [the interactive rebase](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for details

Comment (Yelloween10) [reply misc/extension_api_validation/4.3-stable.expected:131]: Oh, so I need to update my branch with a rebase?
I have another question, should I squash my commits after I'm done?

Comment (AThousandShips) [reply misc/extension_api_validation/4.3-stable.expected:131]: Yes you need to rebase your branch on the up-to-date branch, squashing would be good too but not necessary until this is approved

**Comment by Yelloween10** [comment]
Is this good?

**Comment by AThousandShips** [comment]
Compatibility code is correct now!

**Comment by Yelloween10** [comment]
Should I squash it now?

**Comment by AThousandShips** [comment]
You can do it now if you like, but you don't have to untill it's approved

**Comment by Yelloween10** [comment]
Alright, thank you.

**Comment by Yelloween10** [comment]
When would it be available to review?

**Review by Sauermann — APPROVED** [review]
The changes make sense as discussed here: https://github.com/godotengine/godot/pull/98441#discussion_r1812143234
I can't predict how many problems this breaking change causes for projects. But since the previous implementation is simply wrong, i'm in favor of merging.

**Comment by Repiteo** [comment]
Thanks!
