### PR TITLE
Pass current value to `EditorInterface` node/property popups

### LINKED ISSUE #94322: EditorInterface `popup_node_selector` and `popup_property_selector` should include passing a current selected value
### Tested versions

Godot 4.3.beta3

### System information

Windows 11

### Issue description

While the two new popup methods introduced on `EditorInterface` in Godot 4.3 are nice to expose these dialogs to external plugins and editor tools, they lack the ability for the external plugin/tool to pass a "currently selected" value.  

For example, if a plugin presents the node selector followed by the property selector, similar to how the Animation editor works when animating a node property, its very unfriendly if the node isn't changing and only the property changes that the user must search and select the node again.  

Ideally the `popup_node_selector` should take a `NodePath` or a `Node*` pointer to represent the current selected value as an optional value, set to an empty NodePath or a nullptr in the case of a pointer.  The `popup_property_selector` should take a property name that is optional, defaulting to empty string.  

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Naros**
Fixes #94322 

As outlined in the issue, while these new methods are nice in Godot 4.3, they don't seem to hit the mark in terms of being fully user friendly without being able to specify a current value, should these be used in cases where the addon already has an existing value and would prefer to highlight that in the dialog when its shown.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You need to bind compatibility methods, see [here](https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html)

**Comment by Naros** [comment]
> You need to bind compatibility methods, see [here](https://docs.godotengine.org/en/latest/contributing/development/handling_compatibility_breakages.html)

Even if these methods were introduced in an alpha/beta build of Godot 4.3?

**Comment by AThousandShips** [comment]
Oh my bad didn't know they were current, then it's unnecessary

File: editor/editor_interface.cpp [hunk 1]
```diff
@@ -272,7 +272,7 @@ void EditorInterface::set_current_feature_profile(const String &p_profile_name)
 
 // Editor dialogs.
 
-void EditorInterface::popup_node_selector(const Callable &p_callback, const TypedArray<StringName> &p_valid_types) {
+void EditorInterface::popup_node_selector(const Callable &p_callback, const TypedArray<StringName> &p_valid_types, Node *current_value) {
```
Comment (AThousandShips) [inline editor/editor_interface.cpp:275]:
```suggestion
void EditorInterface::popup_node_selector(const Callable &p_callback, const TypedArray<StringName> &p_valid_types, Node *p_current_value) {
```

File: editor/editor_interface.cpp [hunk 2]
```diff
@@ -301,7 +301,7 @@ void EditorInterface::popup_node_selector(const Callable &p_callback, const Type
 	node_selector->connect(SNAME("canceled"), canceled_callback, CONNECT_DEFERRED);
 }
 
-void EditorInterface::popup_property_selector(Object *p_object, const Callable &p_callback, const PackedInt32Array &p_type_filter) {
+void EditorInterface::popup_property_selector(Object *p_object, const Callable &p_callback, const PackedInt32Array &p_type_filter, const String &current_value) {
```
Comment (AThousandShips) [inline editor/editor_interface.cpp:304]:
```suggestion
void EditorInterface::popup_property_selector(Object *p_object, const Callable &p_callback, const PackedInt32Array &p_type_filter, const String &p_current_value) {
```

Comment (Naros) [reply editor/editor_interface.cpp]: Fixed.

File: editor/editor_interface.cpp (hunk 1 above)
Comment (Naros) [reply editor/editor_interface.cpp]: Fixed.

**Review by AThousandShips — DISMISSED** [review]
Not familiar with the internals so a second eye on this would be good but the code looks good to me and the existing interface is just employed

File: doc/classes/EditorInterface.xml [hunk 3]
```diff
@@ -299,8 +299,9 @@
 			<return type="void" />
 			<param index="0" name="callback" type="Callable" />
 			<param index="1" name="valid_types" type="StringName[]" default="[]" />
+			<param index="2" name="current_value" type="Node" default="null" />
 			<description>
-				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types.
+				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types. If [param current_value] if provided, the Node will be automatically selected in the tree, if it exists.
```
Comment (akien-mga) [inline doc/classes/EditorInterface.xml:304]:
```suggestion
				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types. If [param current_value] is provided, the Node will be automatically selected in the tree, if it exists.
```

Comment (Naros) [reply doc/classes/EditorInterface.xml]: Fixed @akien-mga

**Comment by KoBeWi** [comment]
The `current_value` in `popup_property_selector()` seems to do nothing. Nothing is selected no matter what I tried to use.

**Comment by Naros** [comment]
Hi @KoBeWi so I checked the code in the `property_selector.h` and `property_selector.cpp` files and it does seem that while one can pass the current "selected" value into the dialog, the logic within `PropertySelector::_update_search` does not actually do anything with the member variable `selected`.

Looking more closely at the uses of `PropertySelector`, there are 8 public methods that pass the current value and store that in the `selected` member variable; however, while the member variable's value is set by those 8 methods, it's not used internally in any of the presentation logic sadly.

So I think for completeness, we should at the very least keep the ability to pass this value on the `EditorInterface`.  This minimizes the need to introduce any compatibility method after-the-fact.  I think the question is really how do we want to address this bug, as a part of this PR or a follow-up.  

I'm of the opinion that give where we are with 4.3, we should likely take care of addressing the `PropertySelector` implementation bug separately at the outset of 4.4 and then consider backporting that fix.  What do others think?  @akien-mga ?

**Comment by KoBeWi** [comment]
Well, you added a new argument and it didn't require any compatibility code, so looks like adding arguments in the future is not a problem.
I think this can be pushed to 4.4 and let you can finish it properly.

**Comment by akien-mga** [comment]
> Well, you added a new argument and it didn't require any compatibility code, so looks like adding arguments in the future is not a problem. I think this can be pushed to 4.4 and let you can finish it properly.

It doesn't require compatibility code now because this is a new API in 4.3.

If a new argument is added in 4.4, it will indeed require a compat binding. But that's no big deal so if the added API doesn't work, I think it's better to take the time to do it right (otherwise we'd add something in 4.3 where the docs are actually wrong about what the new argument does).

**Comment by KoBeWi** [comment]
We could say in the docs to say that the argument is unused 🤔
And then change it once it's fixed.

**Comment by Naros** [comment]
As I see Remi has moved this to 4.4, what's the final verdict then here?

**Comment by akien-mga** [comment]
To me there's not much gain adding an argument that does nothing in 4.3, to fix it later. It still means that people who want to make EditorPlugins using this API will have to special case 4.3.0 because while they can use the API, it won't work.

And making it work in 4.3.x would be confusing IMO, documentation typically doesn't state in which version an API was made operative, and the docs will be updated once the bug is fixed to remove mention of it not working.

So I'd say this should wait for 4.4. We're in RC stage, it's no longer the time to

**Comment by Naros** [comment]
Can someone point me to an example of compatibility methods, I plan to update this PR with the fix & I'd like to get this in merge shape asap.  Thanks!

**Comment by KoBeWi** [comment]
Check `.compat.inc` files and the PRs that added them.

**Comment by Naros** [comment]
@KoBeWi added logic for the "current_value" matching for properties/methods & added compatibility methods.  Would you mind giving this another pass from your PoV?  Thanks!

**Comment by KoBeWi** [comment]
Selecting now works, but it would be nice if the dialog scrolled to the selected item.

**Comment by KoBeWi** [comment]
Almost. The view is not centered on the property, but awkwardly cut at the top:
image

**Comment by Naros** [comment]
Thanks @KoBeWi, fixed.  It appears I needed to delay the `scroll_to_item` until the end of the frame since building of the list was still in-flight and the offset would obviously change due to additional items added.

**Comment by AThousandShips** [comment]
You've added your own compatibility file, this isn't correct, it should be added to the existing `4.3-stable.expected`

**Comment by Naros** [comment]
> You've added your own compatibility file, this isn't correct, it should be added to the existing `4.3-stable.expected` (creation of these files is handled by maintainers, you don't need to do it yourself)

Well, as you can see that file doesn't exist based on the HEAD of this PR, and so I based those changes on what I saw in other PRs.  I'll rebase and amend the existing file.  Is this documented somewhere ?

**Comment by AThousandShips** [comment]
Don't think it's documented but it's a general maintenance thing, good to rebase after a release to make sure things are up to date

File: doc/classes/EditorInterface.xml [hunk 4]
```diff
@@ -305,8 +305,9 @@
 			<return type="void" />
 			<param index="0" name="callback" type="Callable" />
 			<param index="1" name="valid_types" type="StringName[]" default="[]" />
+			<param index="2" name="current_value" type="Node" default="null" />
 			<description>
-				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types.
+				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types.  If [param current_value] is provided, the Node will be automatically selected in the tree, if it exists.
```
Comment (KoBeWi) [inline doc/classes/EditorInterface.xml:310]:
```suggestion
				Pops up an editor dialog for selecting a [Node] from the edited scene. The [param callback] must take a single argument of type [NodePath]. It is called on the selected [NodePath] or the empty path [code]^""[/code] if the dialog is canceled. If [param valid_types] is provided, the dialog will only show Nodes that match one of the listed Node types. If [param current_value] is provided, the Node will be automatically selected in the tree, if it exists.
```

File: editor/editor_interface.compat.inc [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+/**************************************************************************/
+
+#include "editor_interface.h"
+
+#include "editor/gui/scene_tree_editor.h"
+#include "editor/property_selector.h"
+
+#ifndef DISABLE_DEPRECATED
+
+void EditorInterface::popup_node_selector_compat_94322(const Callable &p_callback, const TypedArray<StringName> &p_valid_types) {
```
Comment (KoBeWi) [inline editor/editor_interface.compat.inc:38]: The old method should just call the new one. The behavior is the same when you pass empty string for current value.

File: editor/property_selector.cpp [hunk 6]
```diff
@@ -173,6 +176,12 @@ void PropertySelector::_update_search() {
 		if (category && category->get_first_child() == nullptr) {
 			memdelete(category); //old category was unused
 		}
+
+		if (found) {
+			// As we call this while adding items, defer until list is completely populated
+			callable_mp(search_options, &Tree::scroll_to_item).bind(search_options->get_selected(), true).call_deferred();
```
Comment (KoBeWi) [inline editor/property_selector.cpp:182]:
```suggestion
			callable_mp(search_options, &Tree::scroll_to_item).call_deferred(search_options->get_selected(), true);
```

File: editor/property_selector.cpp [hunk 7]
```diff
@@ -173,6 +176,12 @@ void PropertySelector::_update_search() {
 		if (category && category->get_first_child() == nullptr) {
 			memdelete(category); //old category was unused
 		}
+
+		if (found) {
+			// As we call this while adding items, defer until list is completely populated
```
Comment (KoBeWi) [inline editor/property_selector.cpp:181]:
```suggestion
			// As we call this while adding items, defer until list is completely populated.
```

**Review by KoBeWi — APPROVED** [review]

File: misc/extension_api_validation/4.3-stable.expected [hunk 8]
```diff
@@ -65,3 +65,10 @@ Validate extension JSON: Error: Field 'classes/AudioStreamPlayer2D/properties/pl
 Validate extension JSON: Error: Field 'classes/AudioStreamPlayer3D/properties/playing': setter changed value in new API, from "_set_playing" to &"set_playing".
 
 These setters have been renamed to expose them. GDExtension language bindings couldn't have exposed these properties before.
+
+GH-94322
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.3-stable.expected:69]:
```suggestion

GH-94322
```
Two lines

File: misc/extension_api_validation/4.3-stable_4.4-stable.expected
Comment (AThousandShips) [inline misc/extension_api_validation/4.3-stable_4.4-stable.expected:1]: This file shouldn't exist

**Review by AThousandShips — CHANGES_REQUESTED** [review]

File: editor/editor_interface.compat.inc [hunk 9]
```diff
@@ -0,0 +1,51 @@
...
+
+#include "editor_interface.h"
+
+#include "editor/gui/scene_tree_editor.h"
+#include "editor/property_selector.h"
+
+#ifndef DISABLE_DEPRECATED
+
+void EditorInterface::_popup_node_selector_bind_compat_94323(const Callable &p_callback, const TypedArray<StringName> &p_valid_types) {
+	popup_node_selector(p_callback, p_valid_types);
```
Comment (AThousandShips) [inline editor/editor_interface.compat.inc:39]:
```suggestion
	popup_node_selector(p_callback, p_valid_types, nullptr);
```
Pass the default explicitly

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
