### PR TITLE
Fix `Node` selection when navigating `Tree` with Arrow keys

### LINKED ISSUE #12544: Arrow keys doesn't select objects on the scene hierarchy
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 Alpha 2, Windows 10 64 bit

**Issue description:**
Arrow keys doesn't select objects on the scene hierarchy, please see this video as reference:
https://youtu.be/lRbefcsYDi4?t=99

Notice how by using the arrow keys doesn't really select the items, only changes the property window information but doesn't have any effect on the viewport.

### PR DESCRIPTION
**Pull request by TheSofox**
Fixes  #12544

Arrow keys change actual selection (not just cursor) when navigating `Tree` and `SceneTreeDock`.

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -3233,7 +3233,8 @@ void Tree::_go_up() {
 		if (!prev) {
 			return;
 		}
-		selected_item = prev;
+
+		select_single_item(prev, get_root(), selected_col);
 		emit_signal(SNAME("cell_selected"));
```
Comment (AThousandShips) [inline scene/gui/tree.cpp:3238]: This will now be emitted twice

Comment (TheSofox) [reply scene/gui/tree.cpp]: Removed `emit_signal` in the two places it appeared under `select_single_item`

**Review by KoBeWi — APPROVED** [review]
`select_single_item()` looks more expensive than what was done previously, but I tested with a very big scene and it's not noticeable.

Also using that method might change what signals are emitted in different selection modes, but this could be desirable (and maybe fix other existing issues).

**Comment by YuriSizov** [comment]
Thanks!

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -3233,8 +3233,8 @@ void Tree::_go_up() {
 		if (!prev) {
 			return;
 		}
-		selected_item = prev;
-		emit_signal(SNAME("cell_selected"));
+
+		select_single_item(prev, get_root(), selected_col);
```
Comment (aaronfranke) [inline scene/gui/tree.cpp:3237]: Why is `select_single_item` used for `SELECT_MULTI`?

Comment (TheSofox) [reply scene/gui/tree.cpp:3237]: Arrow key overrides it. It's exactly what happens in other systems, such as in Windows file explorer.

Comment (aaronfranke) [reply scene/gui/tree.cpp:3237]: Can you take a look at #92959? The code currently crashes, and when I fixed the crash, @KoBeWi reported incorrect behavior, that it selects items which are not visible.
