### PR TITLE
Core: Do not generate `*.uid` files for JSON, certificates, and translations

### LINKED ISSUE #99514: JSON files produce `*.uid` files
### Tested versions

Godot 4.4 dev 5.

### System information

Godot v4.4.dev5 - Windows 10.0.22631 - Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6614) - 13th Gen Intel(R) Core(TM) i7-13700K (24 threads)

### Issue description

I use JSON files for mod support and these get imported when starting up the game. However, it's creating uid's for all of these files and will not load due to errors.

eg:
`Expected 'true','false' or 'null', got 'uid'. in res://Scenarios/Scenario_1.json.uid at line 0.
`

I'm not entirely sure if this is a bug but it seems to be an oversight. As now i will need to write extra code to handle this and all my mod files will be cluttered.

I did go through and remove them all and whilst the game will actually load, it takes several minutes longer than it should.

### Steps to reproduce

Have JSON files within your game files and they will all be given a uid.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #99514.

### CODE REVIEW

File: core/io/json.h [hunk 1]
```diff
@@ -105,6 +105,9 @@ class ResourceFormatLoaderJSON : public ResourceFormatLoader {
 	virtual void get_recognized_extensions(List<String> *p_extensions) const override;
 	virtual bool handles_type(const String &p_type) const override;
 	virtual String get_resource_type(const String &p_path) const override;
+	// Treat JSON as a text file, do not generate a `*.json.uid` file.
+	virtual ResourceUID::ID get_resource_uid(const String &p_path) const override { return ResourceUID::INVALID_ID; }
+	virtual bool has_custom_uid_support() const override { return true; }
```
Comment (dalexeev) [inline core/io/json.h:110]: Note that **both** overrides are required. This may seem odd, since in fact JSON does not have a UID. But we define "support" for custom UID... which is invalid. It might make sense to separate these three lines with a blank line for better readability.

https://github.com/godotengine/godot/blob/f952bfe9985ad8f507cc29b2c7601bbba18b8039/core/io/resource_loader.cpp#L115-L126

https://github.com/godotengine/godot/blob/f952bfe9985ad8f507cc29b2c7601bbba18b8039/editor/editor_node.cpp#L1457-L1465

https://github.com/godotengine/godot/blob/f952bfe9985ad8f507cc29b2c7601bbba18b8039/editor/editor_file_system.cpp#L1263-L1270

**Comment by akien-mga** [comment]
> * `ResourceFormatLoaderCrypto` (`*.crt`, `*.key`, `*.pub`);
> * `TranslationLoaderPO` (`*.po`, `*.mo`).

Yeah I think disabling `.uid` files for those would make sense.

We can always re-assess if some users report issues due to not having UIDs for those or `.json`, but I think it's better to start conservative (less intrusive to user projects) and adjust later.

**Review by akien-mga — APPROVED** [review]
Makes sense to me.

File: core/io/json.h (hunk 1 above)
Comment (KoBeWi) [reply core/io/json.h:110]: We could make it into a macro called `DISABLE_UID` or something. These 2 lines will be the same for every class.

**Review by KoBeWi — APPROVED** [review]

File: core/io/json.h (hunk 1 above)
Comment (dalexeev) [reply core/io/json.h:111]: I think this is redundant for now. But we may reconsider this in the future if more exceptions are added.

**Comment by Repiteo** [comment]
Thanks!
