### PR TITLE
Fix Navigation agent callback wild pointer crash

### LINKED ISSUE #68013: Executing `Navigation2DServer.agent_set_callback` crashes Godot
### Godot version

3.6.beta.custom_build. 4d4c6c187

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
extends Node
func _process(delta):


	var temp_variable_f2845871 = RID()
	var temp_variable_f2845872 = null
	var temp_variable_f2845873 = "127.0.0.1"
	var temp_variable_f2845874 = {"roman" : 22, 22 : 25, BoxShape.new() : BoxShape.new()}
	Navigation2DServer.agent_set_callback(temp_variable_f2845871,temp_variable_f2845872,temp_variable_f2845873,temp_variable_f2845874)

```
Godot crashes with this backtrace

```
scene/resources/shape.cpp:121:38: runtime error: member call on null pointer of type 'struct PhysicsServer'
scene/resources/shape.cpp:121:38: runtime error: member access within null pointer of type 'struct PhysicsServer'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v3.6.beta.custom_build (71f5bb391626b5d541a21885c846dca2b44dbb9a)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] godots() [0x1897926] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/x11/crash_handler_x11.cpp:56)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f1a4dff5520] (??:0)
[3] Shape::~Shape() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/resources/shape.cpp:121)
[4] BoxShape::~BoxShape() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/resources/box_shape.h:36)
[5] void memdelete<Reference>(Reference*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/os/memory.h:118)
[6] Ref<Reference>::unref() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/reference.h:260)
[7] RefPtr::unref() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/ref_ptr.cpp:86)
[8] Variant::clear() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant.cpp:1054)
[9] Variant::~Variant() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant.h:437)
[10] HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::Pair::~Pair() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/hash_map.h:61)
[11] HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::Element::~Element() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/hash_map.h:74)
[12] void memdelete<HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::Element>(HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::Element*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/os/memory.h:118)
[13] HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::clear() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/hash_map.h:512)
[14] HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::~HashMap() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/hash_map.h:574)
[15] OrderedHashMap<Variant, Variant, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::~OrderedHashMap() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/ordered_hash_map.h:47)
[16] DictionaryPrivate::~DictionaryPrivate() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/dictionary.cpp:37)
[17] void memdelete<DictionaryPrivate>(DictionaryPrivate*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/os/memory.h:118)
[18] Dictionary::_unref() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/dictionary.cpp:222)
[19] Dictionary::~Dictionary() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/dictionary.cpp:312)
[20] Variant::clear() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant.cpp:1061)
[21] Variant::~Variant() (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant.h:437)
[22] agent_set_callback_command::~agent_set_callback_command() (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/navigation/godot_navigation_server.cpp:540)
[23] void memdelete<SetCommand>(SetCommand*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/os/memory.h:118)
[24] GodotNavigationServer::flush_queries() (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/navigation/godot_navigation_server.cpp:623 (discriminator 2))
[25] GodotNavigationServer::~GodotNavigationServer() (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/navigation/godot_navigation_server.cpp:114)
[26] void memdelete<NavigationServer>(NavigationServer*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/os/memory.h:118)
[27] finalize_navigation_server() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:238)
[28] Main::cleanup(bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2531)
[29] godots(main+0x361) [0x188d137] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/x11/godot_x11.cpp:63)
[30] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f1a4dfdcd90] (??:0)
[31] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f1a4dfdce40] (??:0)
[32] godots(_start+0x2e) [0x188cd1e] (??:?)

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### LINKED ISSUE #68022: Executing `NavigationAgent.set_avoidance_enabled` crashes Godot
### Godot version

3.6.beta.custom_build. 4d4c6c187

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
extends Node
func _process(delta):

	var temp_variable226 = NavigationAgent.new()
	temp_variable226.set_avoidance_enabled(true)
	temp_variable226.queue_free()
```
Godot crashes with this backtrace

```
==7110==ERROR: AddressSanitizer: heap-use-after-free on address 0x61700002ff10 at pc 0x000003a29096 bp 0x7ffd6274c060 sp 0x7ffd6274c050
READ of size 8 at 0x61700002ff10 thread T0
    #0 0x3a29095 in GodotNavigationServer::_cmd_agent_set_callback(RID, Object*, StringName, Variant) modules/navigation/godot_navigation_server.cpp:544
    #1 0x3a40d37 in agent_set_callback_command::exec(GodotNavigationServer*) modules/navigation/godot_navigation_server.cpp:540
    #2 0x3a2c7a3 in GodotNavigationServer::flush_queries() modules/navigation/godot_navigation_server.cpp:624
    #3 0x3a2d527 in GodotNavigationServer::process(float) modules/navigation/godot_navigation_server.cpp:640
    #4 0x1a685fd in Main::iteration() main/main.cpp:2312
    #5 0x1931c57 in OS_X11::run() platform/x11/os_x11.cpp:4035
    #6 0x188d12c in main platform/x11/godot_x11.cpp:59
    #7 0x7f5f2dae6d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #8 0x7f5f2dae6e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #9 0x188cd1d in _start (/usr/bin/godots+0x188cd1d)

0x61700002ff10 is located 16 bytes inside of 680-byte region [0x61700002ff00,0x6170000301a8)
freed by thread T0 here:
    #0 0x7f5f2e73740f in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x13523bb2 in Memory::free_static(void*, bool) core/os/memory.cpp:168
    #2 0x1a75f80 in void memdelete<Object>(Object*) core/os/memory.h:118
    #3 0xd23d34d in SceneTree::_flush_delete_queue() scene/main/scene_tree.cpp:1251
    #4 0xd22a0fb in SceneTree::idle(float) scene/main/scene_tree.cpp:653
    #5 0x1a6a159 in Main::iteration() main/main.cpp:2337
    #6 0x1931c57 in OS_X11::run() platform/x11/os_x11.cpp:4035
    #7 0x188d12c in main platform/x11/godot_x11.cpp:59
    #8 0x7f5f2dae6d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

previously allocated by thread T0 here:
    #0 0x7f5f2e737808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x13522b6f in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x13522a80 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0xd03cfe1 in Object* ClassDB::creator<NavigationAgent>() (/usr/bin/godots+0xd03cfe1)
    #4 0x12cadd23 in ClassDB::instance(StringName const&) core/class_db.cpp:520
    #5 0x1d89d02 in GDScriptNativeClass::instance() modules/gdscript/gdscript.cpp:77
    #6 0x1d896eb in GDScriptNativeClass::_new() modules/gdscript/gdscript.cpp:65
    #7 0x1e673dd in MethodBind0R<Variant>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:233
    #8 0x12f39650 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #9 0x131f2ce4 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1237
    #10 0x1f819f1 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1048
    #11 0x1db094b in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1211
    #12 0xd0e098f in Node::_notification(int) scene/main/node.cpp:58
    #13 0x1c5731d in Node::_notificationv(int, bool) scene/main/node.h:47
    #14 0x12f39aec in Object::notification(int, bool) core/object.cpp:927
    #15 0xd23a2f5 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:1133
    #16 0xd228942 in SceneTree::idle(float) scene/main/scene_tree.cpp:636
    #17 0x1a6a159 in Main::iteration() main/main.cpp:2337
    #18 0x1931c57 in OS_X11::run() platform/x11/os_x11.cpp:4035
    #19 0x188d12c in main platform/x11/godot_x11.cpp:59
    #20 0x7f5f2dae6d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: heap-use-after-free modules/navigation/godot_navigation_server.cpp:544 in GodotNavigationServer::_cmd_agent_set_callback(RID, Object*, StringName, Variant)

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by smix8**
Sanitizer builds crashed when callback agent or receiver object were already freed when the NavigationServer command queue was executed.

Fixes #68013
Fixes #68022

Same in Godot 3.5+ for cherry-picked.

### CODE REVIEW

File: modules/navigation/godot_navigation_server.cpp [hunk 1]
```diff
@@ -680,14 +680,22 @@ COMMAND_4(agent_set_callback, RID, p_agent, Object *, p_receiver, StringName, p_
 	RvoAgent *agent = agent_owner.get_or_null(p_agent);
 	ERR_FAIL_COND(agent == nullptr);
 
-	agent->set_callback(p_receiver == nullptr ? ObjectID() : p_receiver->get_instance_id(), p_method, p_udata);
+	if (agent == nullptr) {
+		return;
+	}
```
Comment (kleonc) [inline modules/navigation/godot_navigation_server.cpp:685]: I don't get it. The guard above should already handle this?
(also it could be changed to `ERR_FAIL_NULL(agent)`)

**Review by kleonc — COMMENTED** [review]
Honestly I don't see how this PR changes anything. The code before/after seems to be doing exactly the same thing.

File: modules/navigation/godot_navigation_server.cpp [hunk 2]
```diff
@@ -680,14 +680,22 @@ COMMAND_4(agent_set_callback, RID, p_agent, Object *, p_receiver, StringName, p_
...
+		agent->set_callback(ObjectID(), p_method, p_udata);
+		if (agent->get_map()) {
 			agent->get_map()->remove_agent_as_controlled(agent);
-		} else {
-			agent->get_map()->set_agent_as_controlled(agent);
 		}
+		return;
+	}
+
+	agent->set_callback(p_receiver->get_instance_id(), p_method, p_udata);
```
Comment (timothyqiu) [inline modules/navigation/godot_navigation_server.cpp:695]: `p_receiver` won't match the null check since it's a wild pointer. So the problem still exists.

Probably it should be passed as an `ObjectID` instead of `Object *`, or just use `Callable` as the parameter.

Comment (smix8) [reply modules/navigation/godot_navigation_server.cpp:695]: ObjectID sounds fine.

File: modules/navigation/godot_navigation_server.cpp (hunk 1 above)
Comment (smix8) [reply modules/navigation/godot_navigation_server.cpp]: well yes that was a redundant goof.

File: modules/navigation/godot_navigation_server.cpp [hunk 3]
```diff
@@ -676,18 +676,24 @@ bool GodotNavigationServer::agent_is_map_changed(RID p_agent) const {
...
-			agent->get_map()->set_agent_as_controlled(agent);
 		}
+		return;
+	}
+
+	agent->set_callback(p_object_id, p_method, p_udata);
+
+	if (agent->get_map()) {
+		agent->get_map()->set_agent_as_controlled(agent);
 	}
```
Comment (timothyqiu) [inline modules/navigation/godot_navigation_server.cpp:697]: Nitpicks:

I think the old structure can be reused. The early return makes it harder to figure out what this code block does.

There is also a validation of the object ID before passing it to `set_callback()`. I think it's redundant since `RvoAgent` still needs to validate the object ID before using it. The validation also makes the behavior inconsistent under certain circumstances (i.e. when the callback object becomes invalid before `set_callback()`, the agent is not registered as controlled in navmap; when the callback object becomes invalid after `set_callback()`, the agent won't un-register itself as controlled in navmap). But it's okay if you think this is an optimization :)

**Review by timothyqiu — APPROVED** [review]
Looks good.

Also note that since the signature of `agent_set_callback()` is changed, this PR might break some existing projects that uses the function directly (argument type mismatch).

**Comment by akien-mga** [comment]
> Also note that since the signature of `agent_set_callback()` is changed, this PR might break some existing projects that uses the function directly (argument type mismatch).

Good point, so it's probably not suitable for `3.5`, despite being a clear bugfix. For `3.6` I think the compat breakage is OK, it's easily justified.

File: modules/navigation/godot_navigation_server.cpp (hunk 3 above)
Comment (smix8) [reply modules/navigation/godot_navigation_server.cpp]: returned old structure

**Comment by smix8** [comment]
Returned old structure as suggested by timo.

**Comment by timothyqiu** [comment]
Cherry-picked for 3.6
