### PR TITLE
[3.x] Use hash table for GDScript parsing

### LINKED ISSUE #74733: Very long scripts tend to slow writing down
### Godot version

3.5.2 and previous versions

### System information

MX Linux, SSD, i5-6500

### Issue description

Hey,

I tend to work on large scripts. When a script gets very long, 10k+ lines scrolling can be laggy (if you use the scrollbar and drag it) and writing new stuff can take considerable amount of time, the inputs are taken but until it shows on screen it can take a second (just write something very fast, especially at the end of the script). It does not happen always but in more than 50% of tries.

I could use an external editor but I would really like to avoid using one.

Edit: Sorry for Closing and Reopening that was not my intention. I wanted to add: I just tested it on Godot 4.0 - the problem is not there, not when using the Forward nor the Compatibility renderer if that helps.

### Steps to reproduce

Work with a large script

### Minimal reproduction project

[Minimal_Project.zip](https://github.com/godotengine/godot/files/10944253/Minimal_Project.zip)

I don't know how to not include the .godot folder but couldn't find one with ls -a. This is a project with 40k lines to test it properly.

Just write something very fast, especially at the end of the script.

### PR DESCRIPTION
**Pull request by lawnjelly**
GDScript now uses hash table for lookup of type lists / functions / keywords, instead of linear String comparisons.

Helps fix #74733

HashTable lookup during parsing seems approx 20x faster than linear search.

## Notes
* Profiling reveals after the other fixes, looking up keywords / functions using a linear search with lots of `String ==` comparisons is very slow, this is better suited to a hash table.
* I'm not super familiar with the parser so this could do with double checking by GDScript guy.
* Using an `OAHashMap` here, welcome suggestions if there is a better container, can be slow insertion but needs fast lookup.
* Using dynamic allocation just to be super safe - reduz mentioned previously that some of the Variant / possibly String stuff might not be safe to store as globals due to order of construction / destruction.
I couldn't immediately see a good place to put them as member variables (`GDScriptTokenizer` gets reconstructed often so not a good candidate, as we want to set up the hash table only once), but would welcome any suggestions.

### CODE REVIEW

**Review by vnen — APPROVED** [review]
I haven't really worked with this code in quite a long time. For what I can assess it looks good.

**Comment by vnen** [comment]
BTW the tokenizer in 4.0 is still doing string comparisons but it has optimizations of its own. It only cares about keywords (built-in types and functions are seen as regular identifiers), it checks for length first (ids shorter or longer than any existing keyword skips the checks), and it's grouped by first character (only if the first matches it checks for keywords in the group, which has at most 4 items currently).

I haven't profiled it so I'm not sure if a hash table would be faster or worth the extra memory.

**Comment by lawnjelly** [comment]
> BTW the tokenizer in 4.0 is still doing string comparisons but it has optimizations of its own. It only cares about keywords (built-in types and functions are seen as regular identifiers), it checks for length first (ids shorter or longer than any existing keyword skips the checks), and it's grouped by first character (only if the first matches it checks for keywords in the group, which has at most 4 items currently).
> 
> I haven't profiled it so I'm not sure if a hash table would be faster or worth the extra memory.

That sounds pretty good for 4.0. :+1: :slightly_smiling_face: 
The main win I think is having *something* better than a linear search, but it might be interesting to compare at some point.

File: modules/gdscript/gdscript_tokenizer.cpp [hunk 1]
```diff
@@ -235,6 +237,96 @@ static const _kws _keyword_list[] = {
...
+
+void GDScriptTokenizer::terminate() {
+	if (token_hashtable) {
+		memdelete(token_hashtable);
+		token_hashtable = nullptr;
+	}
+}
+
+// return whether found
+bool GDScriptTokenizerText::_parse_identifier(String p_str) {
```
Comment (akien-mga) [inline modules/gdscript/gdscript_tokenizer.cpp:279]: I don't know if this would make a difference but we usually try to pass `const String &` where applicable.

Comment (lawnjelly) [reply modules/gdscript/gdscript_tokenizer.cpp:279]: Good point, I'll do this. :+1:

**Comment by akien-mga** [comment]
Thanks!
