### PR TITLE
Corrected text selection in color picker

### LINKED ISSUE #35603: Copying hex code from exported Color variable does not copy anything to clipboard
**Godot version:**
~~3.2 RC 3~~
3.2 Stable

**OS/device including version:**
Windows 7 Home Premium Service Pack 1
Windows 10 Home

**Issue description:**
When user tries to copy hex code of color he picked using exported Color variable, he gets ~~"color" string when pasted instead~~ nothing copied to clipboard.

**Steps to reproduce:**
1. Export Color variable so it becomes visible in Inspector
2. Change that variable value in Inspector
3. Try to copy Hex Code visible in bottom right corner of dialog
4. Paste copied value

**Minimal reproduction project:**
[ExportColorIssueProject.zip](https://github.com/godotengine/godot/files/4114741/ExportColorIssueProject.zip)

### PR DESCRIPTION
**Pull request by Janglee123**
Fixes two issues. 
1. Fixes #35603 
2. Two text selection at the same time

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -624,26 +624,34 @@ void ColorPicker::_screen_pick_pressed() {
 }
 
 void ColorPicker::_focus_enter() {
+	bool has_ctext_focus = false;
```
Comment (akien-mga) [inline scene/gui/color_picker.cpp]: This can be simplified a bit with:
```
bool has_ctext_focus = c_text->has_focus();
if (has_ctext_focus) {
	c_text->select_all();
} else {
...
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.
