### PR TITLE
Use correct ndc for proximity fade in Compatibility

### LINKED ISSUE #89942: Proximity Fade broken in Compatibility (OpenGL)
### Tested versions

- v4.3.dev5.official [89f70e98d]

### System information

Godot v4.3.dev5 - macOS 13.6.0 - GLES3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

The Proximity Fade in StandardMaterial3D does not work with Compatibility renderer. The produced code assumes Vulkan Z range 0.0 to 1.0 instead of OpenGL -1.0 to 1.0. The fix is to remap the depth_tex as follows:

```glsl
// Proximity Fade: Enabled
	float depth_tex = textureLod(depth_texture, SCREEN_UV, 0.0).r;
        depth_tex = depth_tex * 2.0 - 1.0; // <-- For OpenGL
	vec4 world_pos = INV_PROJECTION_MATRIX * vec4(SCREEN_UV * 2.0 - 1.0, depth_tex, 1.0);
	world_pos.xyz /= world_pos.w;
	ALPHA *= clamp(1.0 - smoothstep(world_pos.z + proximity_fade_distance, world_pos.z, VERTEX.z), 0.0, 1.0);
```

### Steps to reproduce

- Use Compatibility renderer.
- Add a cube on a plane, or two intersecting cubes, etc. 
- Apply a new standardMaterial3D and enable Proximity Fade.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
I believe this is the only other place in BaseMaterial where the depth texture is used aside from refraction, which requires different math between the RD renderers and Compatibility. The other prs either fail shader compilation or output sub-optimal shader code when converting to ShaderMaterial in the editor.

Fixes https://github.com/godotengine/godot/issues/89942

Supersedes https://github.com/godotengine/godot/pull/100220

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

File: scene/resources/material.cpp [hunk 1]
```diff
@@ -1842,7 +1842,8 @@ void fragment() {)";
 		code += R"(
 	// Proximity Fade: Enabled
 	float proximity_depth_tex = textureLod(depth_texture, SCREEN_UV, 0.0).r;
-	vec4 proximity_view_pos = INV_PROJECTION_MATRIX * vec4(SCREEN_UV * 2.0 - 1.0, proximity_depth_tex, 1.0);
+	vec4 ndc = OUTPUT_IS_SRGB ? vec4(vec3(SCREEN_UV, proximity_depth_tex) * 2.0 - 1.0, 1.0) : vec4(SCREEN_UV * 2.0 - 1.0, proximity_depth_tex, 1.0);
+	vec4 proximity_view_pos = INV_PROJECTION_MATRIX * ndc;
```
Comment (Calinou) [inline scene/resources/material.cpp:1846]: Add a comment to explain why this is done:

```suggestion
	// Use correct normalized device coordinates on Compatibility.
	vec4 ndc = OUTPUT_IS_SRGB ? vec4(vec3(SCREEN_UV, proximity_depth_tex) * 2.0 - 1.0, 1.0) : vec4(SCREEN_UV * 2.0 - 1.0, proximity_depth_tex, 1.0);
	vec4 proximity_view_pos = INV_PROJECTION_MATRIX * ndc;
```

**Review by Calinou — APPROVED** [review]
Looks good to me.

Ideally, we'd use the shader preprocessor to avoid (static) branching, but this is better than the status quo.

**Comment by clayjohn** [comment]
> Looks good to me.
> 
> Ideally, we'd use the shader preprocessor to avoid (static) branching, but this is better than the status quo.

This code will get optimized at compile time since `OUTPUT_IS_SRGB` is a compile time constant. The run time performance will be the same as using the shader preprocessor

**Comment by Repiteo** [comment]
Thanks!
