### PR TITLE
Fix incorrect anchor preset when custom offset is set (reverted)

### LINKED ISSUE #101694: Custom anchor Container Sizing switching to Full Rect
### Tested versions

4.4 beta 1

### System information

Windows 11

### Issue description

First, If you set any node to Anchor Mode, and then set Preset to "Full Rect", it will change a default of:
Anchor Points: 0,0,1,1 and 
Anchor Offsets: 0,0,0,0.

thus, Full Rect is:
Anchor Points: 0,0,1,1 and 
Anchor Offsets: 0,0,0,0.

You must choose "Custom" if you want to change these settings.

However, if you close the scene and then reopen it, Godot will only look at whether the Anchor Points are 0,0,1,1 and not the Anchor Offsets
If you change the offsets, Godot needs to keep the Preset to "Custom", however, Godot keeps reassigning the Preset to "Full Rect", which is incorrect.

Godot needs to also check if the Anchor Offsets are 0,0,0,0 before automatically selecting "Full Rect" on reopening. The user has to reselect "Custom" just to get to the Anchor Offset settings. As well, if an aware of the bug, they will not know why the margins are offset when it states "Full Rect" 

### Steps to reproduce

Create a scene with a control and parent.
Add a child control.
Set child Layout mode to Anchors.
Set the Anchors Preset to Custom.
Set Anchor Points to 0,0,1,1
Set Anchors Offset to 25,25,-25,-25

Save the scene and close it. 
Upon reopening, the Anchors Preset has switched from "Custom" to "Full Rect", now hiding the Anchor Offset settings.

### Minimal reproduction project (MRP)

[project.zip](https://github.com/user-attachments/files/18456092/project.zip)

### LINKED ISSUE #105854: When a previously saved scene is opened in the editor, when child of a CanvasLayer, control nodes with "Custom" Anchors Preset and nonzero anchor offsets show the incorrect value when the anchor points values match a preset
### Tested versions

- Reproducible in v4.4.1.stable.mono.official [49a5bc7b6]

### System information

Godot v4.4.1.stable.mono - Windows 11 (build 26100) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4070 Ti SUPER (NVIDIA; 32.0.15.6636) - AMD Ryzen 7 7800X3D 8-Core Processor (16 threads)

### Issue description

When a previously saved scene is opened in the editor, when child of a CanvasLayer, control nodes with "Custom" Anchors Preset and nonzero anchor offsets show the incorrect value when the anchor points values match a preset. Since the anchor offsets are nonzero, it should not be considered to match a an anchors preset value, and should be considered "Custom".

Note that this does not occur if the Anchor Points are different from an Anchors Preset's anchor points, in that case it correctly shows "Custom" as the Anchors Preset value when the saved scene is opened in the editor.

This bug does not seem to affect the actual positioning of the control node, though it does affect the value of `anchors_preset` in the `.tscn` file.

### Steps to reproduce

1. Create a new scene with CanvasLayer as the root node.
2. Add a Button as a child of the Canvas Layer
3. Choose "Custom" for Anchors Preset.
4. Set Anchor Point (Left 0.5, Top, 0.0, Right 0.5, Bottom 0.0), set Anchor Offsets (Top 100px).
5. Save the scene
6. Select the "Button" node in the inspector, if not already selected.
    - It should look like this screenshot, with "Custom" for Anchors Preset.
Image
7. Close the scene
8. Open the scene again
9. Click the "Button" node.
11. Check the Anchors Preset. Note that Anchors Preset incorrectly says "Center Top" (instead of Custom)
    - It will (incorrectly) look like this screenshot
Image
12. Also note that the node will be in the correct place (100px below the actual center top location)
13. Also note that if you choose "Custom" for Anchors Preset again, the Anchor Offsets will be displayed and will be correct.

You may use the MRP below, however due to the nature of the bug, when loaded it will be as if starting from step 8 above. You may use the editor to change the "Button" node Anchors Preset value to "Custom" and save, then close and reopen the scene to reproduce the bug from the MRP.

### Minimal reproduction project (MRP)

[anchors_preset_test_project.zip](https://github.com/user-attachments/files/19933950/anchors_preset_test_project.zip)

### PR DESCRIPTION
**Pull request by limuy2022**
Fix #105854 Fix #101694

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1043,6 +1043,14 @@ int Control::_get_anchors_layout_preset() const {
 	float top = get_anchor(SIDE_TOP);
 	float bottom = get_anchor(SIDE_BOTTOM);
 
+	float left_offset = get_offset(SIDE_LEFT);
+	float right_offset = get_offset(SIDE_RIGHT);
+	float top_offset = get_offset(SIDE_TOP);
+	float bottom_offset = get_offset(SIDE_BOTTOM);
```
Comment (KoBeWi) [inline scene/gui/control.cpp]: These variables are unnecessary. You can compare the method results directly.

**Review by KoBeWi — APPROVED** [review]
The commits need to be squashed.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by Summersay415** [comment]
This PR is broken - now trying to apply preset to Control with non-zero size will always result in Custom preset

**Comment by KoBeWi** [comment]
Looks like anchors offset shouldn't be used to determine layout 🙃

**Comment by KoBeWi** [comment]
So it turns out that the bug boils down to the values not being initialized properly. #109282 makes the default values wrong, making it impossible to properly set the default state of Control and Control-derived nodes.

If not the aforementioned issue, changing this to `true` would be sufficient to fix the bug:
https://github.com/godotengine/godot/blob/45509c284cc8779f7e791b0d7dc3d639b3cc2fcc/scene/gui/control.h#L201
I think this PR should be reverted, because it made things worse than before.
