### PR TITLE
Fix GraphEdit::arrange_nodes causing a freeze when cycle in Graph

### LINKED ISSUE #63501: Arranging GraphNodes when a self-connection exists crashes scene.
### Godot version

4.0alpha12 (2c11e6d9efc42370a8d7537eaff8b1ea78a283e5)

### System information

Windows 10

### Issue description

When working with GraphEdit and GraphNodes, if we have a node self-connecting -- where the connection goes from one of its output ports into its own input ports -- then selecting and arranging the nodes crashes the scene/editor.

This happens both when launching a scene or using an in-editor plugin. 
It also happens if the arranging is being called by pressing the button or by calling the function arrange_nodes().

Behaviour expected: Self-connections should be ignored in the rearrangement.

### Steps to reproduce

1. Create a scene with a GraphEdit node.
2. Add a child GraphNode and a child label to said GraphNode
3. Enable both right and left slots of GraphNode.
4. Add a script to GraphEdit and on_ready connect the GraphNode to itself.
5. Launch scene, select node and try arranging them by clicking the button. 
6. Scene crashes.

### Minimal reproduction project

[BugArrangeNodes.zip](https://github.com/godotengine/godot/files/9192028/BugArrangeNodes.zip)

### PR DESCRIPTION
**Pull request by tefusion**
When a Graph contains cycle(s), e.g. GraphNode->GraphNode _layering would end up in an infinite loop since IS_SUBSET would never be true. By keeping check of the size of z, which contains the already layered nodes, one can detect a freeze (since it should change after current_layer increases). If it doesn't "u" didn't change and q and u will  never be equal resulting  in a freeze/infinite while loop).
If a freeze happens warn the user and put all the nodes part of the cycle (leftover in p) to the  first layer which will then just list them top to bottom at the end.

This is the more complete version of #63765. While not optimal (see video, everything part of cycle just gets listed randomly) it still sorts the non cyclic graphs part of the selected nodes, breaks the freeze and doesn't really impact performance of the more common non cyclic graphs (ShaderEditor, etc.). 

https://user-images.githubusercontent.com/69000267/182458611-138a1197-993b-483b-80b4-b177c81a35fd.mp4

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/63501

### CODE REVIEW

**Comment by fire** [comment]
@theoway Can you review?

File: scene/gui/graph_edit.cpp [hunk 1]
```diff
@@ -1823,7 +1823,20 @@ HashMap<int, Vector<StringName>> GraphEdit::_layering(const HashSet<StringName>
 		}
 		if (!selected) {
 			current_layer++;
+			uint32_t previous_size_z = z.size();
 			_set_operations(GraphEdit::UNION, z, u);
+			if (z.size() == previous_size_z) {
+				WARN_PRINT("Graph contains cycle(s) so arranged one may be faulty.");
```
Comment (theoway) [inline scene/gui/graph_edit.cpp:1829]: We can change the warning to: `"Graph contains cycle(s). The cycle(s) will not be rearranged accurately."`

**Review by theoway — CHANGES_REQUESTED** [review]
Great catch! The code is designed only for DAGs. As it is very rare for someone to code recursions in visualscripts, cycles rarely occur. This approach handles them well. 
It is not possible to layer a cyclic graph so we cannot expect any decent rearrangement. 
For time being, a warning to user is sufficient.

**Review by fire — APPROVED** [review]
Approvable after revisions are made.

**Comment by akien-mga** [comment]
Thanks!
