### PR TITLE
.NET: Prevent generating mono glue in project folder

### LINKED ISSUE #83128: Godot crashes when generating mono glue if PWD is godot project
### Godot version

commit hash: d80ce0c52a097c35bb4d441e7a9c0a76e6342ba4

### System information

Pop OS 22.04

### Issue description

I'm putting this issue in for tracking purposes.  I also have a PR incoming with a fix.

When generating glue following these docs: 

https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_dotnet.html#generate-the-glue

Godot crashes if it is generated while the PWD is a godot project.

Here is the stacktrace:

```log
Godot Engine v4.2.dev.mono.custom_build.d80ce0c52 - https://godotengine.org
 

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev.mono.custom_build (d80ce0c52a097c35bb4d441e7a9c0a76e6342ba4)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f6cfa642520] (??:0)
[2] submodules/godot/bin/godot.linuxbsd.editor.x86_64.llvm.mono(+0x33302a7) [0x55f5f45ee2a7] (/home/tcroc/dev/BlockyBallOT/submodules/godot/./core/templates/cowdata.h:397)
[3] submodules/godot/bin/godot.linuxbsd.editor.x86_64.llvm.mono(+0x31fd9a3) [0x55f5f44bb9a3] (/home/tcroc/dev/BlockyBallOT/submodules/godot/editor/editor_help.cpp:2365)
[4] submodules/godot/bin/godot.linuxbsd.editor.x86_64.llvm.mono(+0x31fe3a4) [0x55f5f44bc3a4] (??:?)
[5] submodules/godot/bin/godot.linuxbsd.editor.x86_64.llvm.mono(+0x58843d2) [0x55f5f6b423d2] (/home/tcroc/dev/BlockyBallOT/submodules/godot/core/os/thread.cpp:63)
[6] submodules/godot/bin/godot.linuxbsd.editor.x86_64.llvm.mono(+0x60aa763) [0x55f5f7368763] (msdf-error-correction.cpp:?)
[7] /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f6cfa694ac3] (??:0)
[8] /lib/x86_64-linux-gnu/libc.so.6(+0x126a40) [0x7f6cfa726a40] (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

### Steps to reproduce

1. Create a godot project
2. Make sure your PWD is in the godot project
3. Generate the mono glue
4. Watch the world burn

### Minimal reproduction project

The steps to reproduce above

### PR DESCRIPTION
**Pull request by akien-mga**
- Fixes #83128.
- Supersedes #83129.

```
$ cd ~/some/project
$ /Godot/godot/bin/godot.linuxbsd.editor.dev.x86_64.mono --generate-mono-glue .
ERROR: --generate-mono-glue: Cannot generate Mono glue while running a game project. Change current directory or enable --editor.
   at: handle_cmdline_args (modules/mono/editor/bindings_generator.cpp:4977)
$ /Godot/godot/bin/godot.linuxbsd.editor.dev.x86_64.mono --generate-mono-glue . -e
// works
```

### CODE REVIEW

File: modules/mono/editor/bindings_generator.cpp [hunk 1]
```diff
@@ -4889,8 +4889,14 @@ void BindingsGenerator::handle_cmdline_args(const List<String> &p_cmdline_args)
 	}
 
 	if (glue_dir_path.length()) {
-		handle_cmdline_options(glue_dir_path);
-		// Exit once done
+		if (Engine::get_singleton()->is_editor_hint() ||
+				Engine::get_singleton()->is_project_manager_hint()) {
```
Comment (AThousandShips) [inline modules/mono/editor/bindings_generator.cpp:4893]: Makes me wonder if we should add complementary cases, either a `is_editor_or_project_manager_hint` or a `is_game/running_hint` or something like it, though I'm not sure how often this particular check is used, or the complement

**Review by AThousandShips — APPROVED** [review]
Makes sense to me, haven't tried but the logic is valid

File: modules/mono/editor/bindings_generator.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/mono/editor/bindings_generator.cpp:4893]: This is something I'd like to refactor one day, `main.cpp` and the whole logic to infer what mode to run based on context is very hacky.

We should change it so there's a lot more _intent_ on what to run (can still be implicit for the user but the code flow needs to be explicit), and then we can store which run mode we're using in an enum instead of these custom bools.

**Review by raulsntos — APPROVED** [review]
Works as expected, thanks!
