### PR TITLE
Fix third and fourth level (AltGr / ⌥ modifier) keys input in LineEdit.

### LINKED ISSUE #21440: Unable to enter some characters to LineEdit boxes (macOS non-US keyboard layout)
**Godot version:**
3.0.6

**OS/device including version:**
macOS High Sierra 10.13.6

**Issue description:**
In Finnish (Swedish, and other) keyboard layout several characters such as `@£$|\{[]}` require the use of `alt/option` key to type, for example `@` is `alt/option`+`2` and `{` is `shift`+`alt/option`+`8`.

These characters can not be typed into LineEdit boxes, seemingly nothing happens. OTOH TextEdit does not have that problem.

**Steps to reproduce:**

0. select Finnish keyboard layout in macOS System Preferences
1. attempt to type `@` to Godot text boxes – that is `alt/option`+`2`

**Minimal reproduction project:**
N/A

### LINKED ISSUE #29509: [OSX] Curly brackets { } and @ symbol not working in the inspector
**Godot version:**
3.2 build #197b65f32

**OS/device including version:**
MacOSX Mojave

**Issue description:**
Upon exporting a String to the inspector if you try to enter a `{`  `}` or a `@` you can't, my guess is that it happens due to keyboard layout. I'm from Portugal and to input those symbols I need to press `option + shift + 8` `option + shift + 9` and `option + shift + 2` respectively so the key combination must be being considered as a short-cut instead.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #21440, fixes #29509

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -539,7 +539,7 @@ void LineEdit::_gui_input(Ref<InputEvent> p_event) {
 
 			if (handled) {
 				accept_event();
-			} else if (!k->get_alt() && !k->get_command()) {
+			} else if (!k->get_command()) {
```
Comment (akien-mga) [inline scene/gui/line_edit.cpp]: It would be good to check why `!k->get_alt()` was used previously and if this change would introduce issues on non-macOS. From a quick look I see above that in some cases `handled` is set to `false` for `k->get_alt()` on non-Apple, so this would now fall into this branch.

Comment (bruvzg) [reply scene/gui/line_edit.cpp]: This check was added in #5271, not sure what was it supposed to fix.

On Windows all `Alt+?` seems to have `unicode` set to `0` and `AltGr` combinations with set `unicode` have `set_alt` flag removed. I have not found any difference in input behaviour.

On Linux (Debian, Xfce) `Alt+?` have `unicode` values set, and act as text input (without this PR Alt+? input was not accepted by LineEdit, but was by TextEdit, behaviour of other apps seems to be inconsistent). `AltGr` combinations doesn't have `set_alt` flag set.

Just in case I'm missing something I have added extra check for the cases setting `handled` to `false`.

Comment (akien-mga) [reply scene/gui/line_edit.cpp]: I trust your research and tests, I don't think we should add extra checks which are not particularly obvious to the reader. Either we know that they are really needed and we should put a comment explaining why, or it's better to leave them out and we can reconsider if anyone reports a regression when using Alt + one of those keys on a given platform.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.
