### PR TITLE
[Linux] Process TTS callback on the main thread to avoid speech-dispatcher deadlock.

### LINKED ISSUE #73605: tts_stop freezes Godot under Godot 4 on Linux
### Godot version

- 4.0 RC2 (.NET) x64 official binaries 
- 4.0 RC1 (.NET) x64 official binaries

### System information

Manjaro (Arch) with KDE Plasma.

### Issue description

Calling `DisplayServer.tts_stop` freezes Godot. None of the subsequent actions (e.g. `print` or `tts_speak`) execute.

TTS works. I have installed `spd-say`, `festival`, and `espeakup`. Running `spd-say Hello, world!` on the console speaks the intended output.

It doesn't look like a regression per-se; RC1 and RC2 both behave the same.

On the other hand, it seems to work on Windows 10. I suspect that it's system-specific; perhaps I'm missing some pre-requisites or other libraries related to TTS?

### Steps to reproduce

- Get a voice for TTS
- Call `DisplayServer.tts_speak(long_ramble, _voice["id")`
- Call `DisplayServer.tts_stop()` while the speech is still in progress

Expected: speech stops and the game continues
Actual: speech stops and the game freezes

### Minimal reproduction project

[tts-stop-bug.zip](https://github.com/godotengine/godot/files/10778085/tts-stop-bug.zip)

- Click the first button
- Click the second button

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/73605

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: platform/linuxbsd/tts_linux.cpp [hunk 1]
```diff
@@ -76,76 +81,84 @@ void TTS_Linux::speech_init_thread_func(void *p_userdata) {
 
 void TTS_Linux::speech_event_index_mark(size_t p_msg_id, size_t p_client_id, SPDNotificationType p_type, char *p_index_mark) {
 	TTS_Linux *tts = TTS_Linux::get_singleton();
-	if (tts && tts->ids.has(p_msg_id)) {
-		MutexLock thread_safe_method(tts->_thread_safe_);
-		// Get word offset from the index mark injected to the text stream.
-		String mark = String::utf8(p_index_mark);
-		DisplayServer::get_singleton()->tts_post_utterance_event(DisplayServer::TTS_UTTERANCE_BOUNDARY, tts->ids[p_msg_id], mark.to_int());
+	if (tts) {
+		tts->call_deferred(SNAME("_speech_index_mark"), p_msg_id, p_client_id, (int)p_type, String::utf8(p_index_mark));
```
Comment (akien-mga) [inline platform/linuxbsd/tts_linux.cpp:85]: Would this work with `callable_mp(...).call_deferred()` instead of binding the methods?

Registering this with `GDCLASS` has made it show up in the GDExtension API: https://github.com/godotengine/godot-cpp/commit/c1ff169bf3ad5f13457eda7cd5a424b894adbb05#diff-fc336699721277f071b492b7c4006667e3073bb75cef6ddf75721ba8a61d12daR217376-R217382

Comment (bruvzg) [reply platform/linuxbsd/tts_linux.cpp:85]: Yes, this will work as well - https://github.com/godotengine/godot/pull/73764
