### PR TITLE
Select relevant 3D lights per mesh on GLES3 and Mobile renderers

### LINKED ISSUE #107070: Irrelevant 3D lights are chosen per mesh in Mobile and Compatibility renderers
### Tested versions

- Reproducible in 4.4.1 and 4.5-dev4

### System information

Windows 10 (build 19045), NVIDIA GeForce GTX 1650 Ti, Core(TM) i5-10300H CPU @ 2.50GHz (8 threads)

### Issue description

When using the Compatibility (and also the Mobile) renderer I was expecting to have up to 8-Omni and 8-Spot lights render on each mesh.  Designing the scene to have more small meshes, and respecting the total light limit, I still had meshes that looked unlit.  In the following procedural office scene there are 28 Omnilights (close to the floor so it's easy to see where they are) and one Spotlight and 1 directional light.  Each room is its own mesh and has at least 1 light, and the yellow rooms have 3x2 and 2x2 lights.  You can see where lights were not rendering as you might expect:

Image

Digging into the code, I found that the Compatibility and Mobile renderers both have a function named **pair_light_instances**, and in that function only the first N lights that pass the culling stage are linked.  I changed the code to keep only the closest N lights and it rendered as expected.  Then I tried changing the project settings to allow 256 lights total, with 16 per mesh and tried minimal test project, but still some meshes picked weird lights:

Image

I then found that **RendererSceneCull::_scene_cull** has a fixed upper limit of **MAX_INSTANCE_PAIRS = 32**, so the culling code will never consider more than 32 lights total.  I can easily change the limit up to 256, yielding this:

Image

That isn't super efficient, however...it might be best to move the "keep the best N lights" into the culling code, and directly link them there as well.

Note that a fix for this might also fix [Issue 67508](https://github.com/godotengine/godot/issues/67508)

### Steps to reproduce

Open the MRP attached below.  Go to the 3D preview.  You should see something like the following:

Image

### Minimal reproduction project (MRP)

[incorrect_lights_per_mesh.zip](https://github.com/user-attachments/files/20560152/incorrect_lights_per_mesh.zip)

### PR DESCRIPTION
**Pull request by jon1solution**
This PR changes the behavior of the `RendererSceneCull::_scene_cull` function to select the most relevant 3D lights per mesh in the Compatibility and Mobile renderers.  It is a fix for [Issue 107070](https://github.com/godotengine/godot/issues/107070).

Previously, if the scene had many more lights in range than could be rendered per-mesh (so > 8 for Mobile, or > `Max Lights per Object` for Compatibility), Godot would simply pick the first N lights and assign them to the mesh.  Even increasing the limits (on Compatibility) failed to illuminate the scene as you would expect.  I am sure most users who need complex 3D lighting can use the Forward+ renderer, but I am hoping to get a decent approximation running on the more limited renderers (I ran into the issue trying to fake GI in a procedural building with lots of lights).

Here is the behavior of 4.4.1 in a scene with 256 meshes and 256 omni-lights.  For testing purposes, the range of each light was extended so that all meshes were in range of all lights.  The result looked the same on both Mobile and Compatibility (with limits set to 256 lights per scene, 8 per-mesh to match Mobile):
image

With the code modifications in this PR, it now looks like this:
image

The original code ran through each mesh, and then each light relative to each mesh.  The new code follows the same pattern but now assigns a score to each light, relative to each mesh, factoring in the distance from the light's AABB center to the mesh's AABB center, the light range, and the light energy.

The code then keeps track of the top N lights, by keeping the top N scores in a SortArray, which uses a heap internally to keep the scores sorted enough to find the worst score directly (it is always in slot [0]).  If a new light is found to score better than the worst in the collection, slot 0 is replaced with the new light and the heap is updated.  

In theory this is the fastest way to run through *all* M lights while keeping the top N, however many spatial hashing schemes could accelerate this by not having to run through all M lights for every mesh.  So there is room to optimize further if this turns out to be too slow for extreme cases, however 256 3D lights in a scene might be excessive for mobile and web targets.  [8^)

- _Bugsquad edit,_ fixes https://github.com/godotengine/godot/issues/107070

### CODE REVIEW

**Comment by Calinou** [comment]
> Here is the behavior of 4.4.1 in a scene with 256 meshes and 256 omni-lights.

Can you upload this test project somewhere? This will make it easier to test the PR.

File: servers/rendering/renderer_scene_cull.cpp [hunk 1]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
-
-							if ((RSG::light_storage->light_get_bake_mode(E->base) == RS::LIGHT_BAKE_STATIC) && idata.instance->lightmap) {
-								continue;
-							}
-
-							instance_pair_buffer[idx++] = light->instance;
-							if (idx == MAX_INSTANCE_PAIRS) {
-								break;
+						ERR_FAIL_NULL(geom->geometry_instance);
+						//	clear any existing light instances for this mesh and return the max count per-mesh, and total (per-scene).
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]: Use a space instead of a tab between `//` and the first character of the comment (this applies to other comments in this PR too):

```suggestion
						// Clear any existing light instances for this mesh and return the max count per-mesh, and total (per-scene).
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 2]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+						Pair<uint32_t, uint32_t> max_per_mesh_total = geom->geometry_instance->clear_light_instances();
+						if ((max_per_mesh_total.first > 0) && (max_per_mesh_total.second > 0)) {
+							//	Run through all M lights, but use a heap to keep track of the best N
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
							// Run through all M lights, but use a heap to keep track of the best N
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 3]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+							uint32_t omni_count = 0, spot_count = 0;
+							LocalVector<Pair<float, uint32_t>> omni_score_idx, spot_score_idx; //	score, index into the light array
+							SortArray<Pair<float, uint32_t>> heapify; //	SortArray has heap functionality in it
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]: Avoid inline comments on lines that are already long. Prefer writing comments on their own line:

```suggestion
							// Score, index into the light array.
							LocalVector<Pair<float, uint32_t>> omni_score_idx, spot_score_idx;
							// SortArray has heap functionality in it.
							SortArray<Pair<float, uint32_t>> heapify;
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 4]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+							bool omni_needs_heap = true, spot_needs_heap = true;
+							Vector3 mesh_center = idata.instance->transformed_aabb.get_center();
+							//	Run through all lights in the scene (there might be more than max_renderable_lights)
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
							// Run through all lights in the scene (there might be more than max_renderable_lights).
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 5]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+							uint32_t total_omni_count = 0, total_spot_count = 0;
+							for (const Instance *E : geom->lights) {
+								RS::LightType light_type = RSG::light_storage->light_get_type(E->base);
+								if (((RS::LIGHT_OMNI == light_type) && (total_omni_count++ < max_per_mesh_total.second)) ||
+										((RS::LIGHT_SPOT == light_type) && (total_spot_count++ < max_per_mesh_total.second))) {
+									//	Cull
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
									// Perform culling.
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 6]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+									if (!(RSG::light_storage->light_get_cull_mask(E->base) & idata.layer_mask)) {
+										continue;
+									}
+									if ((RSG::light_storage->light_get_bake_mode(E->base) == RS::LIGHT_BAKE_STATIC) && idata.instance->lightmap) {
+										continue;
+									}
+
+									InstanceLightData *light = static_cast<InstanceLightData *>(E->base_data);
+									//	Large scores are worse, so linear with distance, inverse with energy and range
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
									// Large scores are worse, so linear with distance, inverse with energy and range.
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 7]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+									Vector3 light_center = E->transformed_aabb.get_center();
+									float light_range_energy =
+											RSG::light_storage->light_get_param(E->base, RS::LightParam::LIGHT_PARAM_RANGE) *
+											RSG::light_storage->light_get_param(E->base, RS::LightParam::LIGHT_PARAM_ENERGY);
+									float light_inst_score = mesh_center.distance_to(light_center) / MAX(0.01f, light_range_energy);
+									//	Keep the best per-light-type
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
									// Keep the "best" lights on a per-light-type basis.
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 8]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+									switch (light_type) {
+										case RS::LIGHT_OMNI: {
+											if (omni_count < max_per_mesh_total.first) {
+												//	We have room to just add it, and track the score and where it goes
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
												// We have room to just add it, and track the score and where it goes.
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 9]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+												omni_score_idx.push_back(Pair(light_inst_score, omni_count));
+												geom->geometry_instance->pair_light_instance(light->instance, light_type, omni_count++);
+											} else {
+												if (omni_needs_heap) {
+													//	We need to make this a heap one time
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
													// We need to make this a heap one time.
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 10]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+												if (light_inst_score < omni_score_idx[0].first) {
+													uint32_t replace_index = omni_score_idx[0].second;
+													geom->geometry_instance->pair_light_instance(light->instance, light_type, replace_index);
+													heapify.adjust_heap(0, 0, omni_count, Pair(light_inst_score, replace_index), &omni_score_idx[0]);
+												}
+											}
+										} break;
+										case RS::LIGHT_SPOT: {
+											if (spot_count < max_per_mesh_total.first) {
+												//	We have room to just add it, and track the score and where it goes
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
												// We have room to just add it, and track the score and where it goes.
```

File: servers/rendering/renderer_scene_cull.cpp [hunk 11]
```diff
@@ -2932,26 +2932,81 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+												spot_score_idx.push_back(Pair(light_inst_score, spot_count));
+												geom->geometry_instance->pair_light_instance(light->instance, light_type, spot_count++);
+											} else {
+												if (spot_needs_heap) {
+													//	We need to make this a heap one time
```
Comment (Calinou) [inline servers/rendering/renderer_scene_cull.cpp]:
```suggestion
													// We need to make this a heap one time.
```

**Review by Calinou — COMMENTED** [review]
Tested locally with the MRP from https://github.com/godotengine/godot/issues/107070, it works as expected. (It doesn't have as many meshes/lights as shown on the screenshots, but it still shows that the situation compared to `master` is improved by rendering small lights on top of all the meshes.)

Code looks good to me.

**Comment by jon1solution** [comment]
Thank you for the feedback! I forgot to mention, in the original MRP, if you change the Grid Size export var up to 16, you should have the 256 meshes and lights test case displayed.

**Comment by mrjustaguy** [comment]
This probably also resolves https://github.com/godotengine/godot/issues/102230

**Comment by BastiaanOlij** [comment]
Looks like a nice first contribution. Great talking it all through in the rendering meeting. Few tidbits and this should be a nice improvement.

**Comment by jon1solution** [comment]
> Looks like a nice first contribution. Great talking it all through in the rendering meeting. Few tidbits and this should be a nice improvement.

Thank you!  I think it is ready for another look.

**Comment by Calinou** [comment]
I've tested this PR again on the MRP included in https://github.com/godotengine/godot/issues/110085, and noticed that it *reverses* the issue in both Mobile and Compatibility. It no longer occurs near the origin, but it starts occurring far from the origin (where it looked correct previously).

https://github.com/user-attachments/assets/9ce9316e-5426-4205-a51c-c828118907f0

https://github.com/user-attachments/assets/71f49ac0-9104-4b7e-b844-e64a7d467571

**Comment by jon1solution** [comment]
> I've tested this PR again on the MRP included in #110085, and noticed that it _reverses_ the issue in both Mobile and Compatibility. It no longer occurs near the origin, but it starts occurring far from the origin (where it looked correct previously).

Thanks for testing!  Could you please zip that tiny test project and drop it here?  I should have some time early next week to look at this.

**Comment by Calinou** [comment]
> Thanks for testing! Could you please zip that tiny test project and drop it here? I should have some time early next week to look at this.

[lights.zip](https://github.com/user-attachments/files/22044861/lights.zip) (it's linked under "Minimal reproduction project" in the linked issue)

**Comment by jon1solution** [comment]
> [lights.zip](https://github.com/user-attachments/files/22044861/lights.zip) (it's linked under "Minimal reproduction project" in the linked issue)

Thanks.  It seems the lights aren't getting culled when they are outside the view frustum prior to being linked to mesh instances (quite possibly by design, since this linking does not take camera position into account?).  So in the test case, all 9 lights attempt to link, the 8 of the 9 (basically) closest to the center of the mesh are kept...same problem as in the original, only it's a different light that loses the toss.

File: servers/rendering/renderer_scene_cull.cpp [hunk 12]
```diff
@@ -2932,26 +2940,82 @@ void RendererSceneCull::_scene_cull(CullData &cull_data, InstanceCullResult &cul
...
+												// We have room to just add it, and track the score and where it goes.
+												omni_score_idx.push_back(Pair(light_inst_score, omni_count));
+												geom->geometry_instance->pair_light_instance(light->instance, light_type, omni_count++);
+											} else {
+												if (omni_needs_heap) {
+													// We need to make this a heap one time.
+													heapify.make_heap(0, omni_count, &omni_score_idx[0]);
+													omni_needs_heap = false;
+												}
+												if (light_inst_score < omni_score_idx[0].first) {
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_scene_cull.cpp:3001]: Finally got around to doing a bunch of testing @jon1solution. Played around a bit with the test projects.

First there does seem to be a bug. `heapify.adjust_heap` nicely inserts the new entry but it doesn't actually end up sorting the `LocalVector`, so the more lights it evaluates, the more likely you get the wrong lights.

Actually testing more, even after `make_heap` is called the sorting can be off:
Image
So it might even be a bug in the sort logic itself, or we're making an assumption here on what 'make_heap' and 'adjust_heap' supposedly do.

Testing in OpenGL with only 2 lights, it masks the issue, but testing in the mobile renderer with 8 lights you do end up with the wrong lights.

Second, and I can't put my finger on it completely, `geom->lights` seems to always contain all lights that are in range of the mesh regardless of whether the light itself is being culled. Or maybe there is some other criteria for what gets added here. As a result, this code path is skipped with the previous results reused until `FLAG_GEOM_LIGHTING_DIRTY` gets set. I can pass several lights and have them out of range behind the camera before the light pairing is updated and even then it seems to still process all lights.

Third, we're sorting by distance to the mesh. This solution is perfect for your use case (in which the second point is also mute), with many objects potentially being effected by many lights, sorting the lights and having those closest to the object win is perfect.

But the other sample from @Calinou 's comment, here all 3 points mentioned effect the outcome.
The sorting would mean that only the lights closest to the center of the mesh would be applied, regardless of the camera position. This use case would work better if we'd prioritise lights based on distance to the camera, but that would break your use case. 

I don't think the distance fade is taken into account here either, you'd expect it to adjust the content of `geom->lights` but it didn't seem to do so for me.

--

Anyway, to make a long story short. My recommendation is to figure out what is going on with the sorting and fix that issue. Then this PR solves your use case, which IMHO is all we can fix with this optimisation.

For the issues with the test project @Calinou was referring too, I think that requires an entirely different approach. We'd need to look into why `geom->lights` includes lights that should be culled because they shouldn't effect anything on screen.

Neither fixes the issue where there are more then 8 lights (2 for GLES3) that effect one mesh and where we'd like them sorted based on distance to camera instead of distance to mesh.
I think those requirements are mutually exclusive. Personally I believe distance wins out because you can solve the other use case by simply breaking your mesh up into smaller meshes.

**Review by BastiaanOlij — APPROVED** [review]
Looks good with the latest feedback.

It solves the issue as described at the top, choosing the closest lights to the mesh being lit.

It doesn't solve the issue referenced later but also isn't intended to fix that. I don't think that issue can be fixed in a meaningful way and should simply be worked around by breaking a large mesh up into smaller chunks, in which case this PR does its job really nicely.

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.3.
