### PR TITLE
Hide only PluginScript in dialog box

### LINKED ISSUE #15884: Missing NativeScript entry in inspector->new ressource
Following #15099 and #15863, all Ressource inheriting from `Script` has been removed from the `Inspector` -> `New resource` dialog box.
As @vnen [mentioned](https://github.com/godotengine/godot/pull/15863#issuecomment-359137026), this is wrong because using this dialog box is the way to create new `NativeScript` according to the [GDNative tutorial](http://docs.godotengine.org/en/latest/community/tutorials/gdnative/gdnative-c-example.html#creating-our-gdns-filel)

The solutions I see to solve the trouble:
- blacklist style: only hide the `PluginScript` node in the dialog box (given it's the one which cause the segfault)
- whitelist style: only show `NativeScript`. Obviously we should also check all the `Script` children to make sure no other class needs to be exposed to the user.

I would be more willing to go whitelist style given it seems creating a Script this way [is more the exception than the rule](https://github.com/godotengine/godot/issues/15099#issuecomment-358696103)

### PR DESCRIPTION
**Pull request by touilleMan**
close #15884

### CODE REVIEW

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -255,8 +255,9 @@ void CreateDialog::_update_search() {
 		if (base_type == "Node" && type.begins_with("Editor"))
 			continue; // do not show editor nodes
 
-		if (base_type == "Resource" && ClassDB::is_parent_class(type, "Script"))
-			continue; // do not show script nodes
+		if (base_type == "Resource" && ClassDB::is_parent_class(type, "PluginScript"))
```
Comment (MarianoGnu) [inline editor/create_dialog.cpp]: This is not gonna work, this prevent PluginScript children to be displayer but not PluginScript, which is the one who causes the crash, proper sentence would be:
> if (base_type == "Resource" && type == "PluginScript")

**Review by MarianoGnu — CHANGES_REQUESTED** [review]
statement change needed

File: editor/create_dialog.cpp (hunk 1 above)
Comment (touilleMan) [reply editor/create_dialog.cpp]: @MarianoGnu `is_parent_class` goes recursive on the provided class, starting by itself.
I've tested this code and it works as expected (just like previous version with `ClassDB::is_parent_class(type, "Script")` were hiding `Script` along with `PluginScript`, `GDScript` etc.)

Comment (MarianoGnu) [reply editor/create_dialog.cpp]: and is this ok? won't it hide phython script and nim script?

Comment (touilleMan) [reply editor/create_dialog.cpp]: Python script (and nim script, provided it is implemented using pluginscript) won't appear in this list in the first place because it is not a C++ class inheriting from `PluginScript`.

The idea is that a `PluginScript` instance is connected to a `PluginScriptLanguage` which describe the language and it C callback functions to interact with.

That's precisely the reason `PluginScript` is hidden in the first place: if you instantiate it from this dialog box, you cannot configure what language this script is in, so it will crash as soon as you start using it.

Comment (MarianoGnu) [reply editor/create_dialog.cpp]: Well then, i'm probably misunderstanding the use of PluginScript, and it's used to create Languages instead of actual scripts.

**Review by MarianoGnu — APPROVED** [review]
