### PR TITLE
Skip `Object::to_string` when Jolt Physics is on separate thread

### LINKED ISSUE #102638: Jolt Physics warnings for PhysicalBone3D fail to report bone names when running physics on separate thread
### Tested versions

- Reproducible in 4.4-beta2, 4.4-beta3
- Not reproducible in 4.3 (no Jolt implementation)

### System information

Godot v4.4.beta3 - Fedora Linux 41 (KDE Plasma) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 SUPER (nvidia; 565.77) - AMD Ryzen 7 8700F 8-Core Processor (16 threads)

### Issue description

I am using the native Jolt Physics engine on a separate thread via project settings (`physics/3d/run_on_separate_thread`). I have an armature that needs updating, so Jolt is emitting warnings. However, the warning is attempting to fetch the names of the problem bones, which is not thread-safe, so the warning text is malformed and is passed with multiple errors (as seen below).

```
ERROR: Caller thread can't call this function in this node (/root/@EditorNode@21257/@Panel@14/@VBoxContainer@15/DockHSplitLeftL/DockHSplitLeftR/DockHSplitMain/@VBoxContainer@26/DockVSplitCenter/@VSplitContainer@54/@VBoxContainer@55/@EditorMainScreen@102/MainScreen/@CanvasItemEditor@11479/@VSplitContainer@11131/@HSplitContainer@11133/@HSplitContainer@11135/@Control@11136/@SubViewportContainer@11137/@SubViewport@11138/RDMOutpost/world/renegade/visual/renegade/Skeleton3D/Physical Bone DEF-spine_001). Use call_deferred() or call_thread_group() instead.
   at: to_string (scene/main/node.cpp:2697)
ERROR: Caller thread can't call this function in this node (/root/@EditorNode@21257/@Panel@14/@VBoxContainer@15/DockHSplitLeftL/DockHSplitLeftR/DockHSplitMain/@VBoxContainer@26/DockVSplitCenter/@VSplitContainer@54/@VBoxContainer@55/@EditorMainScreen@102/MainScreen/@CanvasItemEditor@11479/@VSplitContainer@11131/@HSplitContainer@11133/@HSplitContainer@11135/@Control@11136/@SubViewportContainer@11137/@SubViewport@11138/RDMOutpost/world/renegade/visual/renegade/Skeleton3D/Physical Bone DEF-spine). Use call_deferred() or call_thread_group() instead.
   at: to_string (scene/main/node.cpp:2697)
WARNING: Hinge joint bias limit is not supported when using Jolt Physics. Any such value will be ignored. This joint connects '' and ''.
     at: set_param (modules/jolt_physics/joints/jolt_hinge_joint_3d.cpp:221)
```

When physics is set to run on the main thread, the problem resolves, showing the warnings as normal, including the bone names (expected behavior).
```
WARNING: Hinge joint bias limit is not supported when using Jolt Physics. Any such value will be ignored. This joint connects 'Physical Bone DEF-spine:<PhysicalBone3D#3027113173784>' and 'Physical Bone DEF-spine_001:<PhysicalBone3D#3027146728218>'.
     at: set_param (modules/jolt_physics/joints/jolt_hinge_joint_3d.cpp:221)
WARNING: Hinge joint bias limit is not supported when using Jolt Physics. Any such value will be ignored. This joint connects 'Physical Bone DEF-spine:<PhysicalBone3D#3102627426828>' and 'Physical Bone DEF-spine_001:<PhysicalBone3D#3102660981262>'.
     at: set_param (modules/jolt_physics/joints/jolt_hinge_joint_3d.cpp:221)
```

Should the warning itself be deferred to the main thread?

### Steps to reproduce

1. Set physics to run on a separate thread `physics/3d/run_on_separate_thread`
2. Switch Physics Engine to Jolt Physics
3. Set up a Skeleton3D with PhysicalBone3D bones that have joint properties unsupported in Jolt (i.e. a Pinjoint configured with impulse clamping)
4. Restart editor to see errors in console, or launch game to see them in debugger

### Minimal reproduction project (MRP)

Warnings should appear as soon as this project is opened and imported.

[physicalbone3d_report_2025-02-09_17-35-51.zip](https://github.com/user-attachments/files/18726415/physicalbone3d_report_2025-02-09_17-35-51.zip)

### PR DESCRIPTION
**Pull request by mihe**
Fixes #102638.
Supersedes #102717.

This PR changes the error reporting happening in `modules/jolt_physics` so as to not fetch the actual object/node name when using `physics/3d/run_on_separate_thread`, but instead just fall back to using `<unknown>` as the name, as `Object::to_string` is not thread-safe.

(I also removed `JoltSoftBody3D::to_string`, which seemed to be entirely redundant.)

### CODE REVIEW

File: modules/jolt_physics/objects/jolt_object_3d.cpp [hunk 1]
```diff
@@ -137,6 +138,12 @@ bool JoltObject3D::can_interact_with(const JoltObject3D &p_other) const {
 }
 
 String JoltObject3D::to_string() const {
+	constexpr char fallback_name[] = "<unknown>";
```
Comment (akien-mga) [inline modules/jolt_physics/objects/jolt_object_3d.cpp:141]: I'm not opposed to it per se, but it's a syntax I haven't seen before in the codebase. What's the advantage of doing this vs `const String fallback_name = "<unknown>";`?

Comment (mihe) [reply modules/jolt_physics/objects/jolt_object_3d.cpp]: I mostly wanted to avoid the heap allocation for the "happy path", and somehow got it into my head that this was closer to a duplicated literal than `const char* fallback_name = "<unknown>"`, which does not seem to be the case.

All very silly in this context either way.

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by adamscott** [comment]
It seems to have caused a regression (see #102812), as the TPS demo is crashing on macOS ever since the merge.

**Comment by adamscott** [comment]
> It seems to have caused a regression (see #102812), as the TPS demo is crashing on macOS ever since the merge.

Weird. I just compiled back the project on master and the demo works now. It may be a false flag.
