### PR TITLE
Fix `line_separation` working incorrectly in `RichTextLabel`

### LINKED ISSUE #49455: RichTextLabel ignores Line Separation custom constant
### Godot version

master (0cbb19a246)

### System information

macOS 11.4

### Issue description

Setting `RichTextLabel`'s  Line Separation custom constant does not change line spacing.

The custom constant works fine in 3.x.

### Steps to reproduce

1. Create a RichTextLabel and type in some text
2. Adjust the control's width so the text wraps (or just type in texts that have multiple lines)
3. In the Inspector, change "Custom Constants" -> "Line Separation"

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by requizm**
Fixed #49455

Also, I set `line_separation` to 0 by default. Because every time we open and close the `line_separation` checkbox, there was a visual change. 

line_separation_test

### CODE REVIEW

**Comment by requizm** [comment]
Any reviewers?

**Comment by Calinou** [comment]
Thanks for opening a pull request!

Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) (`git commit --amend`). This way, people reading the Git log can easily figure out what's going on :slightly_smiling_face:

**Comment by requizm** [comment]
@Calinou 
Updated commit message.

**Review by Calinou — APPROVED** [review]
Thanks!

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -1435,7 +1435,7 @@ void RichTextLabel::_notification(int p_what) {
 			while (ofs.y < size.height && from_line < main->lines.size()) {
 				visible_paragraph_count++;
 				visible_line_count += _draw_line(main, from_line, ofs, text_rect.size.x, base_color, outline_size, outline_color, font_shadow_color, use_outline, shadow_ofs);
-				ofs.y += main->lines[from_line].text_buf->get_size().y;
+				ofs.y += main->lines[from_line].text_buf->get_size().y + get_theme_constant(SNAME("line_separation"));
```
Comment (bruvzg) [inline scene/gui/rich_text_label.cpp:1438]: The same change should be done in the `RichTextLabel::_find_click`, (on line 1130) or clicks and selection won't take line separation into account.

Comment (requizm) [reply scene/gui/rich_text_label.cpp:1438]: If your okay with that, i can open a issue and pr.

Comment (KoBeWi) [reply scene/gui/rich_text_label.cpp:1438]: You don't need to open issue, just make a PR directly and link to this comment.

Comment (Calinou) [reply scene/gui/rich_text_label.cpp:1438]: https://github.com/godotengine/godot/pull/51933
