### PR TITLE
Avoid error spamming in animation_tree when path is not found

### LINKED ISSUE #65608: AnimationTree infinite loop, ERROR: Condition "!track_cache.has(path)" is true. Continuing.
### Godot version

4.0-alpha16

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

The whole application started to lag and I noticed this output over and over in the terminal:
```
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
...
```

I ended up closing the application because it would not resolve.

### Steps to reproduce

I was updating the AnimationTree, with the graph open, and changing the referenced tracks from the AnimationPlayer. I ended up saving the scene with the AnimationTree graph open. 

Now, when ever I launch the scene, it throws this infinite loop and makes my machine come to a crawl.

The first output I notice when opening the scene is the following:

```
ERROR: Node not found: "Root/Skeleton3D:root.x" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:root.x'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:root.x" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:root.x'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:foot.l" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:foot.l'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:foot.l" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:foot.l'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:toes_01.l" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:toes_01.l'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:thigh_twist.l" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:thigh_twist.l'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:thigh_twist.l" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:thigh_twist.l'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:foot.r" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:foot.r'
   at: _update_caches (scene/animation/animation_tree.cpp:587)
ERROR: Node not found: "Root/Skeleton3D:foot.r" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
...
```

The above output, goes through all the bones on the skeleton...

Which then goes into the mentioned error output of:

```
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
ERROR: Condition "!track_cache.has(path)" is true. Continuing.
   at: _process_graph (scene/animation/animation_tree.cpp:990)
...
```

This happens until I close the application, which takes a long time because my machine is locked up.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by hackenshaw**
For this issue: https://github.com/godotengine/godot/issues/65608

Error spamming was bringing Godot (and eventually the whole system) to a crawl by spamming an error message when there was an error finding a path.

I fixed this by skipping the error message (the error is also logged somewhere else outside of the loop)

<i>Bugsquad edit:</i>
- Fix #65608

### CODE REVIEW

**Comment by Chaosus** [comment]
Use the clang-format tool to fix the static check failure. Squash the resulted commits after that.

**Comment by TokageItLab** [comment]
Should not hide errors. The cause of the error should be resolved.

**Comment by Chaosus** [comment]
Yeah, placing a check for the path before calling that function instead.

**Comment by LabFortySeven** [comment]
> Should not _**hide**_ errors. Instead, the cause of the error should be resolved.

The cause is if an animation is broken (missing nodes). User error. It is still logged before the loop

**Comment by TokageItLab** [comment]
"Cache failure" and "node not found" are not equivalent, and they should output separate errors. If you want to avoid spamming, for example, you should consider using `ERR_PRINT_ONCE`. However, even in that case, the output should be for all broken casts. E.g. if the first and fifth caches are corrupt, but you only output an error for the first cache, this is the wrong implementation.

**Comment by LabFortySeven** [comment]
I might be missing something... but you first get a "node not found" error and then a "track not found" error for each missing node/track. 

`ERROR: Node not found: "Root/Skeleton3D:root.x" (relative to "/root/@@16122/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@721/MainScreen/@@9499/@@9328/@@9329/@@9330/@@9331/@@9332/@@9333/Player/Root").
   at: get_node (scene/main/node.cpp:1356)
ERROR: AnimationTree: 'Player/Idle', couldn't resolve track:  'Root/Skeleton3D:root.x'
   at: _update_caches (scene/animation/animation_tree.cpp:587)`

Then you get a check in process_graph() to check if the track has an assigned path (which it isn't) and so you get this error (again) every time process_graph() is called. A better solution might be to not add that track to the graph at all.

File: scene/animation/animation_tree.cpp [hunk 1]
```diff
@@ -1018,7 +1018,9 @@ void AnimationTree::_process_graph(double p_delta) {
 				}
 
 				NodePath path = a->track_get_path(i);
-				ERR_CONTINUE(!track_cache.has(path));
+				if (!track_cache.has(path)) {
+					continue; //no path, but avoid error spamming
```
Comment (Chaosus) [inline scene/animation/animation_tree.cpp:1022]:
```suggestion
					continue; // No path, but avoid error spamming.
```

**Comment by TokageItLab** [comment]
The timing of update_cache is very limited. Therefore, considering the possibility that the cache may break for some reason, this error should not be removed.

There have already been report (#39926) of problems with too few occurrences of update_cache apart from #65608. So we should give priority to fixing those first.

**Comment by TokageItLab** [comment]
I looked into AnimationPlayer, and it seems to be implemented similarly to this workaround. So avoiding this error may not be a problem. Very sorry. However, this fix alone does not completely solve the problem, so I have sent an alternative PR as #69480.

**Review by TokageItLab — APPROVED** [review]
As I described #69480, even if this error is avoided, spamming of one frame path errors may occur immediately after playback.

However, it is better than having an error every frame, and since avoiding this error provides the same behavior as the AnimationPlayer, I reconsidered this as not a problem. I am sorry if my above comment scared you.

However, there is basically always some reason for the error output and it needed a very careful decision to remove it. Don't be afraid of this and I would be happy if you send another PR in the future :)

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by hackenshaw** [comment]
> As I described #69480, even if this error is avoided, spamming of one frame path errors may occur immediately after playback.
> 
> However, it is better than having an error every frame, and since avoiding this error provides the same behavior as the AnimationPlayer, I reconsidered this as not a problem. I am sorry if my above comment scared you.
> 
> However, there is basically always some reason for the error output and it needed a very careful decision to remove it. Don't be afraid of this and I would be happy to send you another PR in the future :)

Great! I was just looking at your solution from the other PR. Definitely way beyond my current knowledge! I could fix it in my own project by deleting the references to the missing armatures. But that doesn't solve the underlying problem. I will keep an eye out for other PRs... I think I need some time to look more into the codebase. But I'm still sticking around

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
