### PR TITLE
Tree: Fix de-select when selection mode set to SELECT_ROW (3.x)

### LINKED ISSUE #36047: Tree SELECT_ROW allows de-selecting rows, not emitting _tree_selected (compared to SELECT_SINGLE)
**Godot version:**
3.2 Stable

**OS/device including version:**
Ubuntu 18.4.4 LTS

**Issue description:**
When creating Tree with TreeItems and setting the tree's select mode to SELECT_ROW it doesn't actually trigger _tree_select function, even though emit_signal("item_selected"); is called.

(It omits inside function `tree.cpp::select_single_item()`)

When the mode is SELECT_SINGLE it does omit emit_signal("item_selected"); and _tree_select is called.

Moreover when the select mode is SELECT_ROW you can also de-select items in the tree 

**GIF**
Peek 2020-02-11 00-49

I think I found the problem:
Signal "item_select" is not connected inside file_dialog , only cell_selected is binded, which in turn calls _tree_select
"item_select" needs some use

I fixed the signal problem but now I can deselect the row...
I also get :

> ERROR: deselect_all: Condition "item == prev_item" is true.
   At: scene/gui/tree.cpp:3217.

errors when I go up / inside a folder

**Steps to reproduce:**
In godot engine inside file_dialog.cpp in function set_mode(Mode p_mode) you change the line:
`tree->set_select_mode(Tree::SELECT_SINGLE);`
to:
`tree->set_select_mode(Tree::SELECT_ROW);`

**Minimal reproduction project:**
[minimal.zip](https://github.com/godotengine/godot/files/4183400/minimal.zip)

### PR DESCRIPTION
**Pull request by eazrael**
It no longer de-selects an already selected row if the SELECT_MODE is
set to SELECT_ROW. Fixes #36047

### CODE REVIEW

**Comment by KoBeWi** [comment]
The code seems to be the same as in #56408, so a dedicated 3.x PR wasn't really necessary. It could've been easily cherry-picked.

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -1526,7 +1526,10 @@ void Tree::select_single_item(TreeItem *p_selected, TreeItem *p_current, int p_c
 					*/
 
 			} else if (c.selected) {
-				c.selected = false;
+				if (p_selected != p_current) {
+					//Deselect other rows
+					c.selected = false;
+				}
 				//p_current->deselected_signal.call(p_col);
```
Comment (YeldhamDev) [inline scene/gui/tree.cpp:1533]:
```suggestion
					// Deselect other rows.
					c.selected = false;
				}
```

**Review by YeldhamDev — CHANGES_REQUESTED** [review]

**Comment by YeldhamDev** [comment]
Simple PRs should be squashed into a single commit. Here are the instructions on how do to so: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
