### PR TITLE
Fix for WebGL2 and HTML5 export

### LINKED ISSUE #10256: Editor can't Play the project on Linux if built with release_debug target
**Operating system or device - Godot version:**
Arch linux x86_64; Godot 3.0-alpha from master branch, commit 81dde2687f2f80f5f365a02d68913322d35e9be1

**Issue description:**
If I build engine with target=release_debug, than when I open my project and try to run it (F5 or F6), it starts and immediately stops. And there are no errors.

But if I build engine with target=debug, all works fine. So I think that problem can be in some compilers optimizations. I have a clang 4.0.1

It can be reproduced on new empty project.

On windows with MSVC all fine.

### PR DESCRIPTION
**Pull request by Faless**
This PR is mainly about fixing shaders to work properly in a WebGL2 context:

- Add padding to UBO data to be multiple of 16 bytes [see here](https://khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf#page=159)
- Add precision definition for samplers
- Replace texture2D (deprecated) with texture in shaders

Additionally, I attached to this PR 2 other small fixes:

1 - Application icon loading was broken due to NULL pointer (*bugsquad*: fixes #10256)
2 - `getaddrinfo` was failing due to `AI_NUMERICHOST` flag being set by default on HTML5 platform (see #9624 ).
      (I really hope this won't break other platforms, as it shouldn't, but networking sucks)

I'm really a noob at OpenGL so don't hesitate to question this work.
Let me know also if you prefer to have a separate PR for the 2 small fixes

EDIT: Adding some screenshots

**PBR Materials look cool**
3dmat

**3D Platformer is still somewhat broken**
3d-plat

**2D Effects seems to be working just fine**
2deffects

**Same as 2D lights**
2dlights

**2D Platformer seems to be working too, but keyboards controls are broken everywhere**
2dplat

### CODE REVIEW

File: drivers/gles3/rasterizer_scene_gles3.h [hunk 1]
```diff
@@ -328,6 +330,7 @@ class RasterizerSceneGLES3 : public RasterizerScene {
 		float atlas_clamp[4];
 		float local_matrix[16]; //up to here for spot and omni, rest is for directional
 		//notes: for ambientblend, use distance to edge to blend between already existing global environment
+		uint8_t padding[10];
```
Comment (reduz) [inline drivers/gles3/rasterizer_scene_gles3.h]: Reflection probes are not passed directly but as an array, so in practice the padding is not needed here

**Review by reduz — DISMISSED** [review]
just one change for reflection probes, which goes to an array

File: drivers/gles3/rasterizer_scene_gles3.h (hunk 1 above)
Comment (Faless) [inline drivers/gles3/rasterizer_scene_gles3.h]: > padding is not needed here

I thought that would screw up our offset calculation in the array. Are they tightly packed when defined as array in the uniform block object?

Comment (reduz) [inline drivers/gles3/rasterizer_scene_gles3.h]: it seems like it, at least it works on every platform I tested, including mobile. If padded, it will most likely break

**Comment by Faless** [comment]
PR updated, removed padding from `ReflectionProbeDataUBO`
