### PR TITLE
Core: Fix `RefCounted` handling in `marshalls.cpp`

### LINKED ISSUE #68666: Class "XXX" hides global script class on FileAccess.get_var()
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.beta4.official.e6751549c

### System information

Ubuntu 22.04

### Issue description

GDscript produces an error with no backtrace: "Class 'XXX' hides global script class'. 

I've narrowed down an error I started getting when loading saved objects from a file down to the call to `FileAccess.get_var()`. This occurs when I have a class instance written out with `FileAccess.store_var(true)` (which works), and doesn't appear to occur for any other reason. 

I can just serialise the object myself (and probably should) but this error is definitely harder to track down with no backtrace.

### Steps to reproduce

Just run the attached minimum project.

### Minimal reproduction project

[storavar_bug.zip](https://github.com/godotengine/godot/files/10007026/storavar_bug.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes https://github.com/godotengine/godot/issues/68666#issuecomment-2056346084.

### CODE REVIEW

File: core/io/marshalls.cpp [hunk 1]
```diff
@@ -656,10 +656,17 @@ Error decode_variant(Variant &r_variant, const uint8_t *p_buffer, int p_len, int
...
 					ERR_FAIL_NULL_V(obj, ERR_UNAVAILABLE);
-					ERR_FAIL_COND_V(len < 4, ERR_INVALID_DATA);
 
+					Variant variant;
+					if (Object::cast_to<RefCounted>(obj)) {
+						Ref<RefCounted> ref = Ref<RefCounted>(Object::cast_to<RefCounted>(obj));
+						variant = ref;
+					} else {
+						variant = obj;
+					}
```
Comment (akien-mga) [inline core/io/marshalls.cpp:667]: I'd suggest adding a comment to explain why this is done (and why here), as it's not obvious to me, since the code afterwards still uses the raw `obj` anyway, and `variant` is only used at the end.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
