### PR TITLE
Fix UID support in MultiplayerSpawner

### LINKED ISSUE #99706: Godot v4.4.dev5 breaks MultiplayerSpawner: Condition "!ResourceLoader::exists(p_path)" is true.
### Tested versions

Reproducible in: Godot v4.4.dev5.mono
Not reproducible in: Godot v4.3.stable.mono

Only tested with C#.

### System information

Godot v4.4.dev5.mono - Freedesktop SDK 24.08 (Flatpak runtime) on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) - AMD Ryzen 7 5800X3D 8-Core Processor (16 threads)

### Issue description

A MultiplayerSpawner where the Auto Spawn List is assigned in Godot 4.4 will not replicate nodes to clients. The Auto Spawn List is reset every time the editor reopens with the following error message:

```
modules/multiplayer/multiplayer_spawner.cpp:108 - Condition "!ResourceLoader::exists(p_path)" is true.
```

In addition any MultiplayerSynchronizer errors out on the client with:

```
ERROR: Node not found: "Game/Network/Player/MultiplayerSynchronizer" (relative to "/root").
   at: get_node (scene/main/node.cpp:1873)
ERROR: Parameter "node" is null.
   at: process_simplify_path (modules/multiplayer/scene_cache_interface.cpp:118)
```

View in Godot 4.4 (left is host, right is client):
Image

View in Godot 4.3:
Image

(Pill in the back is already present in scene to show that peers are connected)

dev5 should contain https://github.com/godotengine/godot/pull/99137, so that didn't seem to fix it.

### Steps to reproduce

1. Open a Godot 4.3 project containing a `MultiplayerSpawner` in Godot 4.4
2. Start two instances and observe that everything is working
3. Clear the `Auto Spawn List` of the `MultiplayerSpawner` and assign it again
4. Start two instances and observe that scenes are not spawned on the client

This works in both directions. An `Auto Spawn List` assigned in Godot 4.4 will not load correctly in Godot 4.3 until the `Auto Spawn List` is reassigned.

### Minimal reproduction project (MRP)

In the MRP, everything is working as expected since it was edited in Godot 4.3.

To break it: Open the `Game.tscn` scene and reassign the `Auto Spawn List` on the `MultiplayerSpawner`. Add `res://Player.tscn`.

[MultiplayerSpawnerTest.zip](https://github.com/user-attachments/files/17917858/MultiplayerSpawnerTest.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #99706

The bug occurred because setting a path will use `_set()` on path index, instead of `_set_spawnable_scenes()`. idk how I missed it previously.

The main problem is that MultiplayerSpawner *must* operate on paths, but the editor wants it to store the paths as UID. I removed the uid field added in #99137. Now all paths are stored as paths internally, but saved as UID, with the conversion happening inside setters/getters. This might affect scene loading, but shouldn't impact performance of the spawner's operation.

### CODE REVIEW

File: modules/multiplayer/multiplayer_spawner.cpp [hunk 1]
```diff
@@ -97,13 +97,7 @@ PackedStringArray MultiplayerSpawner::get_configuration_warnings() const {
...
-	if (p_path.begins_with("uid://")) {
-		sc.uid = p_path;
-		sc.path = ResourceUID::uid_to_path(p_path);
-	} else {
-		sc.uid = ResourceUID::path_to_uid(p_path);
-		sc.path = p_path;
-	}
+	sc.path = ResourceUID::ensure_path(p_path);
 	if (Engine::get_singleton()->is_editor_hint()) {
 		ERR_FAIL_COND(!ResourceLoader::exists(p_path));
```
Comment (Faless) [inline modules/multiplayer/multiplayer_spawner.cpp:102]:
```suggestion
	sc.path = ResourceUID::ensure_path(p_path);
	if (Engine::get_singleton()->is_editor_hint()) {
		ERR_FAIL_COND(!ResourceLoader::exists(sc.path));
```

Although the check doesn't seem to ever be executed...

**Review by Faless — COMMENTED** [review]
Pressing the "Add Element" button in the inspector now spams:

```
ERROR: Condition "!unique_ids.has(p_id)" is true. Returning: String()
   at: get_id_path (core/io/resource_uid.cpp:133)
```

File: modules/multiplayer/multiplayer_spawner.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/multiplayer/multiplayer_spawner.cpp:102]: Poke @KoBeWi, this doesn't seem to be included in your later amend.

**Review by akien-mga — APPROVED** [review]
Core changes look good to me.

**Review by Faless — APPROVED** [review]
LGTM, thanks!

**Comment by Repiteo** [comment]
Thanks!
