### PR TITLE
Fix spinbox scrolling for advanced importer controls.

### LINKED ISSUE #98015: Editor SpinBox properties in Advanced Importer are broken.
### Tested versions

4c4e67334412f73c9deba5e5d29afa8651418af2

### System information

Windows 11

### Issue description

Certain properties which use the EditorSpinBox in the Advanced Importer such as primitive/size, primitive/position and primitive/rotation will break if you attempt to mouse-click and drag to change them. This appears to be due to them using PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED flag which causes the entire inspector to be reset anytime they are changed, breaking the spin action.

### Steps to reproduce

* Import a model
* Set one of the meshes to use the physics with a box collider.
* Attempt to spin the size parameter.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes https://github.com/godotengine/godot/issues/98015
Attempts to do this by removing the PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED flag on a bunch of parameters where it doesn't seem nessecary. If anyone can explain why these are here, please let me know, otherwise, this should fix the UX problem outlined in the issue.

### CODE REVIEW

File: editor/import/3d/resource_importer_scene.cpp [hunk 1]
```diff
@@ -2013,26 +2013,26 @@ void ResourceImporterScene::get_internal_import_options(InternalImportCategory p
...
+			r_options->push_back(ImportOption(PropertyInfo(Variant::VECTOR3, "primitive/size", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT), Vector3(2.0, 2.0, 2.0)));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "primitive/height", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT), 1.0));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "primitive/radius", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT), 1.0));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::VECTOR3, "primitive/position", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT), Vector3()));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::VECTOR3, "primitive/rotation", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT), Vector3()));
 
 			r_options->push_back(ImportOption(PropertyInfo(Variant::INT, "generate/occluder", PROPERTY_HINT_ENUM, "Disabled,Mesh + Occluder,Occluder Only", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), 0));
 			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "occluder/simplification_distance", PROPERTY_HINT_RANGE, "0.0,2.0,0.01", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), 0.1f));
```
Comment (kitbdev) [inline editor/import/3d/resource_importer_scene.cpp:2038]:
```suggestion
			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "occluder/simplification_distance", PROPERTY_HINT_RANGE, "0.0,2.0,0.01", PROPERTY_USAGE_DEFAULT), 0.1f));
```
It can be removed here as well, I believe this is the only other one.

**Review by kitbdev — APPROVED** [review]
According to https://github.com/godotengine/godot/pull/52266#discussion_r702978255, these should have all been removed but only the `precision` one was.
Tested and it looks good.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
