### PR TITLE
Preview the color animation in the animation editor

### LINKED ISSUE #289: AnimationPlayer track: track visualisation should also visualize Update Mode, Interpolation Mode or Easing
**Describe the project you are working on:** Projects that use AnimationPlayer node a lot.

**Describe the problem or limitation you are having in your project:**
I was on the fence submitting the track visualization as bug, because it leads to false judgement and shows stuff that is not actually happening:
When you change alpha or color between two keys, the track accurately visualizes the change (see alpha -> white -> alpha -> red transition below). However, when you change Update Mode, Interpolation Mode or Easing, the track visualization dos not reflect the setting, which makes it **very** easy to oversee a mistake, or simply confuse people. This makes the track visualization imho more harmful than helpful:
animation_track_previs

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Make the track reflect the Update Mode, Interpolation Mode or Easing setting as well, or remove the track visualization all together.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
See above how it currently works. If the track visualization would also reflect Update Mode, Interpolation Mode or Easing setting, we would not see a gradient between keys on the track once I changed the setting from "linear" to "Nearest" (Interpolation Mode), or "Linear" to "Zero" (Easing)

**Describe implementation detail for your proposal (in code), if possible:**
Impossible.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Not that I would know.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It would lead to less confusion and potential error for all users of the AnimationPlayer. Don't download anti-confusion medicine in the library, people!

### PR DESCRIPTION
**Pull request by trollodel**
Fixes godotengine/godot-proposals#289 for color tracks (not sure if it is enough to close the proposal)

image

It is done by splitting the link between the 2 keys in chunks.

### CODE REVIEW

File: editor/animation_track_editor_plugins.cpp [hunk 1]
```diff
@@ -101,47 +101,59 @@ void AnimationTrackEditColor::draw_key_link(int p_index, float p_pixels_sec, int
...
 
-	if (x_to > p_clip_right) {
-		float c = float(p_clip_right - x_from) / (x_to - x_from);
-		color_next = color.lerp(color_next, c);
-		x_to = p_clip_right;
-	}
-
-	int y_from = (get_size().height - fh) / 2;
+		if (!color_samples[0].is_equal_approx(color_next)) {
+			color_samples.resize(1 + (x_to - x_from) / 64);
```
Comment (trollodel) [inline editor/animation_track_editor_plugins.cpp:126]: The 64 is arbitrary

**Comment by timothyqiu** [comment]
When I set update mode to discrete, the color still interpolates in the second section.
Snapshot

**Comment by trollodel** [comment]
@timothyqiu should be fixed now.

File: editor/animation_track_editor_plugins.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/animation_track_editor_plugins.cpp]: Then maybe add a comment about it.

File: editor/animation_track_editor_plugins.cpp [hunk 2]
```diff
@@ -101,47 +101,67 @@ void AnimationTrackEditColor::draw_key_link(int p_index, float p_pixels_sec, int
...
-	Color color_next = get_animation()->track_get_key_value(get_track(), p_index + 1);
+	Vector<Color> color_samples;
+	color_samples.append(get_animation()->track_get_key_value(get_track(), p_index));
 
-	if (x_from < p_clip_left) {
-		float c = float(p_clip_left - x_from) / (x_to - x_from);
-		color = color.lerp(color_next, c);
-		x_from = p_clip_left;
-	}
+	if (get_animation()->track_get_type(get_track()) == Animation::TYPE_VALUE) {
```
Comment (KoBeWi) [inline editor/animation_track_editor_plugins.cpp:120]: Is this condition necessary? Can color track be a different track than TYPE_VALUE?

File: editor/animation_track_editor_plugins.cpp [hunk 3]
```diff
@@ -101,47 +101,67 @@ void AnimationTrackEditColor::draw_key_link(int p_index, float p_pixels_sec, int
...
+		colors.push_back(color_samples[i + 1]);
 
-	points.push_back(Vector2(x_from, y_from + fh));
-	colors.push_back(color);
+		points.push_back(Vector2(Math::lerp(x_from, x_to, float(i) / (color_samples.size() - 1)), y_from + fh));
+		colors.push_back(color_samples[i]);
 
-	draw_primitive(points, colors, Vector<Vector2>());
+		draw_primitive(points, colors, Vector<Vector2>());
+	}
```
Comment (KoBeWi) [inline editor/animation_track_editor_plugins.cpp:164]: I'm pretty sure it's possible to build one primitive and draw it outside the loop.

File: editor/animation_track_editor_plugins.cpp (hunk 2 above)
Comment (trollodel) [reply editor/animation_track_editor_plugins.cpp:120]: The condition is necessary because there are `value` specific calls  (e.g. `value_track_interpolate`).
Ideally, it should work for every animation type where interpolation at specific time makes sense (currently, only the `value` and `bezier` type). But since Animation doesn't expose a generic equivalent of  `value_track_interpolate` and colors in `bezier` are split in their component, I decided to support only `value`.

Comment (KoBeWi) [reply editor/animation_track_editor_plugins.cpp:120]: I mean, it should be impossible to create a color track of other type, so this condition would never evaluate to false anyways. But maybe safety check just in case is ok 🤔

Comment (trollodel) [reply editor/animation_track_editor_plugins.cpp:120]: Honestly, I'd keep it because it has a good fallback. But I agree that it's probably useless currently.

File: editor/animation_track_editor_plugins.cpp (hunk 3 above)
Comment (trollodel) [reply editor/animation_track_editor_plugins.cpp:164]: `draw_primitive` accepts at most 4 points and (unless I'm missing something) there aren't other possibilities to draw a gradient in `CanvasItem`.

Comment (KoBeWi) [reply editor/animation_track_editor_plugins.cpp]: Ah right. It would need to be `draw_polygon`. It's the same, but without the limit.

File: editor/animation_track_editor_plugins.cpp [hunk 4]
```diff
@@ -101,47 +101,63 @@ void AnimationTrackEditColor::draw_key_link(int p_index, float p_pixels_sec, int
...
-	colors.push_back(color_next);
-
-	points.push_back(Vector2(x_from, y_from + fh));
-	colors.push_back(color);
-
-	draw_primitive(points, colors, Vector<Vector2>());
+		points.write[i] = Vector2(x_pos, y_from);
+		colors.write[i] = color_samples[i];
+		points.write[points.size() - i] = Vector2(x_pos, y_from + fh);
+		colors.write[points.size() - i] = color_samples[i];
```
Comment (KoBeWi) [inline editor/animation_track_editor_plugins.cpp:158]:
```suggestion
		points.write[points.size() - i - 1] = Vector2(x_pos, y_from + fh);
		colors.write[points.size() - i - 1] = color_samples[i];
```

**Review by KoBeWi — CHANGES_REQUESTED** [review]

File: editor/animation_track_editor_plugins.cpp (hunk 4 above)
Comment (KoBeWi) [reply editor/animation_track_editor_plugins.cpp]: Actually something is wrong when setting easing to high value:
image
Not sure why.

File: editor/animation_track_editor_plugins.cpp [hunk 5]
```diff
@@ -101,47 +101,63 @@ void AnimationTrackEditColor::draw_key_link(int p_index, float p_pixels_sec, int
...
-	points.push_back(Vector2(x_from, y_from + fh));
-	colors.push_back(color);
-
-	draw_primitive(points, colors, Vector<Vector2>());
+		points.write[i] = Vector2(x_pos, y_from);
+		colors.write[i] = color_samples[i];
+		points.write[points.size() - i - 1] = Vector2(x_pos, y_from + fh);
+		colors.write[points.size() - i - 1] = color_samples[i];
+	}
+	draw_polygon(points, colors, Vector<Vector2>());
```
Comment (KoBeWi) [inline editor/animation_track_editor_plugins.cpp:160]: The third argument is the same as default, so it's not necessary.

File: editor/animation_track_editor_plugins.cpp (hunk 4 above)
Comment (trollodel) [reply editor/animation_track_editor_plugins.cpp]: Here's a bigger version for reference.
image

Comment (trollodel) [reply editor/animation_track_editor_plugins.cpp]: After debugging a bit, it seems a bug in the renderer as it appears only when there are 8 or more points.
I fix it by splitting the polygon in chunks of 6 points.

Comment (KoBeWi) [reply editor/animation_track_editor_plugins.cpp]: Uh, the code looks too complicated now .-.
But that maybe it should be fine if you add a comment saying that this is a workaround for a bug. Or alternatively you could return to the first approach...

Comment (trollodel) [reply editor/animation_track_editor_plugins.cpp]: The same issue happens in 3.x, so I think it is better to return to the `draw_primitive` approach.

<details>
  <summary>chunked draw_polygon approach</summary>
  
  ```c++
    const int polygon_points = 3;

	Vector<Vector2> points;
	Vector<Color> colors;
	points.resize(polygon_points * 2);
	colors.resize(polygon_points * 2);

	int j = 0;
	for (int i = 0; i < color_samples.size() || j == polygon_points; i++) {
		if (j == polygon_points) {
			j = 0;
			i -= 2;
			draw_polygon(points.duplicate(), colors.duplicate());
		} else {
			int x_pos = Math::lerp(x_from, x_to, float(i) / (color_samples.size() - 1));
			points.write[j] = Vector2(x_pos, y_from);
			colors.write[j] = color_samples[i];
			points.write[points.size() - j - 1] = Vector2(x_pos, y_from + fh);
			colors.write[points.size() - j - 1] = color_samples[i];
			j++;
		}
	}

	if (j > 1) {
		Vector<Vector2> points_aux = points.subarray(points.size() - j, points.size() - 1);
		Vector<Color> colors_aux = colors.subarray(points.size() - j, points.size() - 1);
		points.resize(j);
		colors.resize(j);
		points.append_array(points_aux);
		colors.append_array(colors_aux);
		draw_polygon(points, colors);
	}
```
</details>

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
