### PR TITLE
JavaClassWrapper: Give additional error when trying to call non-static method directly on the class

### LINKED ISSUE #102019: Error when calling exisiting function using JavaClassWrapper
### Tested versions

- Tested in 4.4-beta1 and dev7

### System information

Godot v4.4.beta1 - Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6636) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

Issue:
When using the new JavaClassWrapper and calling some functions from the JavaClass it sometimes crashes the Application and returns "Attempt to call function 'xyz' in base 'JavaClass' on a null instance."
This is weird, as in my example I even return all the Java Methods and therefore the JavaClass can't be a null instance

How do I expect it to work:
Proper Error Handling and / or not crashing the whole app :D

### Steps to reproduce

For the MRP:
- Open the Project in the latest Version (4.4-beta1)
- Install Export Templates
- Remote Deploy to Android Device

### Minimal reproduction project (MRP)

[orientation_and_gps.zip](https://github.com/user-attachments/files/18546234/orientation_and_gps.zip)

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/102019

I'm not sure this is the right fix.

`JavaClass` is still returning `CALL_ERROR_INSTANCE_IS_NULL` when a developer tries to call a non-static method directly on the class, which means the GDScript VM will still show its not-very-helpful message. But this adds an additional error giving more helpful information.

I went this way because the other `CALL_ERROR_*` values aren't any more appropriate to this situation. We could do `CALL_ERROR_INVALID_METHOD`, but that has the same confusion as on the issue, where the developer listed the methods, and saw that this one exists, but they can't call it on the class. And looking at other places where Godot uses `CALL_ERROR_INSTANCE_IS_NULL`, it really seems like the most appropriate error.

Another option would be to modify the GDScript VM's message to say something about non-static methods, but that would be kinda weird because GDScript itself can detect that you're calling a non-static method in the parser, before it even gets to the VM, so this can't come up with pure GDScript or native classes. So, I don't know that it makes sense to change that?

I'd love feedback on if doing it this way makes sense, or if we should do one of the alternatives.

### CODE REVIEW

File: platform/android/java_class_wrapper.cpp [hunk 1]
```diff
@@ -156,6 +156,9 @@ bool JavaClass::_call_method(JavaObject *p_instance, const StringName &p_method,
 	}
 
 	if (!method) {
+		if (r_error.error == Callable::CallError::CALL_ERROR_INSTANCE_IS_NULL) {
+			ERR_PRINT(vformat("Cannot call static function \"%s\" on Java class \"%s\" directly. Make an instance instead.", p_method, java_class_name));
```
Comment (AThousandShips) [inline platform/android/java_class_wrapper.cpp:160]:
```suggestion
			ERR_PRINT(vformat(R"(Cannot call static function "%s" on Java class "%s" directly. Make an instance instead.)", p_method, java_class_name));
```

Comment (dsnopek) [reply platform/android/java_class_wrapper.cpp]: Thanks! Updated in my latest push

File: platform/android/java_class_wrapper.cpp [hunk 2]
```diff
@@ -156,6 +156,9 @@ bool JavaClass::_call_method(JavaObject *p_instance, const StringName &p_method,
 	}
 
 	if (!method) {
+		if (r_error.error == Callable::CallError::CALL_ERROR_INSTANCE_IS_NULL) {
```
Comment (m4gr3d) [inline platform/android/java_class_wrapper.cpp:159]: Do we get a similar error when a call is made on an actual `null` instance?

Comment (dsnopek) [reply platform/android/java_class_wrapper.cpp:159]: Do you mean with a `null` value in GDScript?

If so, no, `null` in GDScript is `Variant::NIL` and doesn't have an object type. So, for example:

```gdscript
class B:
	func some_method():
		print("hi")

func _ready() -> void:
	var b: B
	b.some_method()
```

... will lead to this error:

```
Invalid call. Nonexistent function 'some_method' in base 'Nil'.
```

But this GDScript snippet isn't the best equivalent to this situation.

A closer equivalent would be:

```gdscript
func _ready() -> void:
	B.some_method()
```

However, that won't even get to runtime, because it gets caught by the GDScript parser, with the very nice error of:

```
Parser Error: Cannot call non-static function "some_method" on the class "B" directly. Make an instance instead.
```

This error is what I modeled the error in this PR on. But, like I said, we can't make GDScript give that error itself in our case, because that's a parser error, and `JavaClassWrapper` only knows what methods each class has at runtime.

The closest equivalent to this in GDScript at runtime would be:

```gdscript
func _ready() -> void:
	var c = Callable(B, "some_method")
	c.call()
```

... which leads to the slightly less nice, but still nice message of:

```
Can't call non-static function 'some_method' in script.
```

Strangely, in this last case, GDScript considers this `CALL_OK` even though it's not actually calling anything.

Anyway, I guess that's all to say, it's a pretty mixed bag, and Godot does a wide variety of different things in similar situations, but I tried to match the one that seemed the nicest :-)

Comment (syntaxerror247) [reply platform/android/java_class_wrapper.cpp:159]: @dsnopek, I believe @m4gr3d is asking whether calling a method on a null instance results in a similar error. For example, would calling `location_manager.hasProvider("gps")` trigger the same error if `location_manager` is actually null?

Comment (dsnopek) [reply platform/android/java_class_wrapper.cpp:159]: > For example, would calling `location_manager.hasProvider("gps")` trigger the same error if `location_manager` is actually null?

Oh! No, it won't. In that case `location_manager` would be `Variant::NIL` and you'd get the error:

```
Invalid call. Nonexistant function 'hasProvider' in base 'Nil'.
```

The error added by this PR wouldn't trigger.

I'm like 99% sure that the error added in this PR can only happen if you're trying to call a non-static method on a class. You _can_ end up with a `JavaObject` that holds a null instance, but it would also have a null class, and so you'd never end up in `JavaClass::_call_method()`.

**Review by syntaxerror247 — APPROVED** [review]

**Review by m4gr3d — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
