### PR TITLE
Disable save button when Inspector is not editing anything

### LINKED ISSUE #50799: Save button not disabled when Inspector is not editing any resource
### Godot version

3.3.2, 3.4.beta1, 3.x (6d58ea6ce7), 4.0.dev (9ac27b58c5)

### System information

macOS 11.4

### Issue description

The "Save the currently edited resource" button is not disabled when I end the edit of a resource in Inspector.

### Steps to reproduce

1. Click the "Create resource in memory" button in Inspector and select a Resource type, say `ImageTexture`.
    * Now the Inspector is editing the image texture.
2. Click in the main editor to end editing
    * The Inspector now shows nothing.
    * But the "Save the currently edited resource" button is still functional, clicking Save even shows the corresponding default filename "new_imagetexture.tres".

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #50799

When Inspector is not editing anything:

* Disable the save button.
* Disable related menu items in the extra options menu.

Did a small refactoring so that the disable-on-nothing logic is not so repetitive.

### CODE REVIEW

File: editor/inspector_dock.cpp [hunk 1]
```diff
@@ -408,29 +408,27 @@ void InspectorDock::update(Object *p_object) {
...
-		return;
-	}
-
-	bool is_resource = p_object->is_class("Resource");
-	bool is_node = p_object->is_class("Node");
-
-	object_menu->set_disabled(false);
-	search->set_editable(true);
-	editor_path->enable_path();
+	const bool is_object = p_object;
```
Comment (akien-mga) [inline editor/inspector_dock.cpp:411]: This works but I'd prefer to make the cast obvious here so that it doesn't look like a wrong assignment.
```suggestion
	const bool is_object = p_object != nullptr;
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
