### PR TITLE
Fix `SoftBody3D` pinned points breaking when reloading scene

### LINKED ISSUE #82434: Error during export of the project with Softbody, also errors in exported project.
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 22.04.3 LTS 22.04 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

Softbody attached to Rigidbody.
Errors during export. "scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D())"
Softbody works correct in editor (follows Rigidbody), does not work correctly in Linux and Web exports (haven't tested other export profiles).

### Steps to reproduce

1. Project with one Rigidbody3D box and SoftBody attached to it by 4 points. No scripts. 
Project attached.

2. In editor it works ok (i.e. SoftBody follows falling RigidBody like a parachute)

3. During export I get 
 scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()
  scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()
  scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()
  scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()
  scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()
  scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()
  scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()
  scene/3d/node_3d.cpp:324 - Condition "!is_inside_tree()" is true. Returning: Transform3D()

4. On execution of exported project (both Linux and WASM): Softbody deforms correctly by gravity, but stays in one place (does not follow Rigidbody box). In console there are messages:

ERROR: Node3D node not defined in the pinned point, this is undefined behavior for SoftBody3D!
   at: _update_cache_pin_points_datas (scene/3d/soft_body_3d.cpp:719)
ERROR: Node3D node not defined in the pinned point, this is undefined behavior for SoftBody3D!
   at: _update_cache_pin_points_datas (scene/3d/soft_body_3d.cpp:719)
ERROR: Node3D node not defined in the pinned point, this is undefined behavior for SoftBody3D!
   at: _update_cache_pin_points_datas (scene/3d/soft_body_3d.cpp:719)
ERROR: Node3D node not defined in the pinned point, this is undefined behavior for SoftBody3D!

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12736993/test.zip)

### LINKED ISSUE #86308: SoftBody3D pinned points get displaced when reloading current scene
### Tested versions

Reproducible in: 4.3.dev [2d0ee20], 4.2.1.stable, 4.1.3.stable, 4.0.4.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - RX 7800 XT - i5-13600K

### Issue description

When you have a SoftBody3D node with pinned points in your scene and you reload the scene using `get_tree().reload_current_scene()` or by loading a different scene and then loading back to the first scene, the pinned points become displaced in the reloaded scene and the following error is printed twice for each pinned point:

```
E 0:00:01:0421   get_global_transform: Condition "!is_inside_tree()" is true. Returning: Transform3D()
  <C++ Source>   scene/3d/node_3d.cpp:343 @ get_global_transform()
```

softbody_issue

This issue is similar to the problem reported in #54780, but the reproduction project in that issue is more complex and throws more errors, plus it's originally from Godot 3.4, so I'm creating this issue for the more straightforward case of simply having a SoftBody3D with pinned points and reloading current scene.

### Steps to reproduce

1. Open MRP and run the game
2. Use A / D to rotate the cube and verify that the soft body has pinned points working properly
3. Press Space to trigger `get_tree().reload_current_scene()`
4. See that now the pinned points are clearly displaced and above mentioned errors were thrown

### Minimal reproduction project (MRP)

MRP for 4.2: [softbody_issue_4.2.zip](https://github.com/godotengine/godot/files/13707034/softbody_issue_4.2.zip)
MRP for 4.0 and 4.1: [softbody_issue_4.1.zip](https://github.com/godotengine/godot/files/13707037/softbody_issue_4.1.zip)

### PR DESCRIPTION
**Pull request by jirisvd**
Fixes #86308.

The issue is that `SoftBody3D::_add_pinned_point()` uses `pinned_point->spatial_attachment->get_global_transform()` to calculate the offset of the pinned point, but getting the global transform of the spatial attachment fails when it's not inside the tree. When calling `get_tree().reload_current_scene()`, the spatial attachment was not inside the tree when `_add_pinned_point()` was called, causing the bug described in #86308, as the offset calculation failed and the pinned points became displaced as a result.

I found that disabling the deferred call to `SoftBody3D::pin_point()` implemented in #71824 and instead calling `pin_point()` immediately in `SoftBody3D::_set_property_pinned_points_attachment()` got rid of this issue, but that broke the reparenting issue that motivated the deferred call in the first place.

By adding an `is_inside_tree()` condition and using the deferred call to `pin_point()` when inside the tree and calling `pin_point()` directly when outside of the tree, I managed to get it into a state where both the offset calculation issue (#86308) and the reparenting issue (#71785) are prevented.

*Physics squad edit*:

- Fixes https://github.com/godotengine/godot/issues/82434

### CODE REVIEW

**Review by rburing — APPROVED** [review]
Tested and confirmed this fixes the issues.

The direct code path is used when (re)loading/exporting the scene, and the deferred code path is used in the editor e.g. when reparenting.

File: scene/3d/soft_body_3d.cpp [hunk 1]
```diff
@@ -215,7 +215,13 @@ bool SoftBody3D::_set_property_pinned_points_attachment(int p_item, const String
 
 	if ("spatial_attachment_path" == p_what) {
 		PinnedPoint *w = pinned_points.ptrw();
-		callable_mp(this, &SoftBody3D::_pin_point_deferred).call_deferred(Variant(w[p_item].point_index), true, p_value);
+
+		if (is_inside_tree()) {
+			callable_mp(this, &SoftBody3D::_pin_point_deferred).call_deferred(Variant(w[p_item].point_index), true, p_value);
+		} else {
+			pin_point(Variant(w[p_item].point_index), true, p_value);
```
Comment (rburing) [inline scene/3d/soft_body_3d.cpp:222]: Adding `Variant(...)` is unnecessary, it can be just `w[p_item].point_index`.

Comment (jirisvd) [reply scene/3d/soft_body_3d.cpp]: I amended the commit to use just `w[p_item].point_index`.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
