### PR TITLE
[Button] Fix theme elements size rounding errors not keeping sufficient space for the text.

### LINKED ISSUE #90745: Text clipping on buttons when using a custom display scale
### Tested versions

Current master v4.3.dev.custom_build [4728ff30c]

### System information

Godot v4.3.dev (4728ff30c) - macOS 14.4.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

I thought it was fixed but apparently it's back?

image<br>

Audi makes nice cars but the tab isn't about them unfortunately

### Steps to reproduce

Just set the display scale to 1.6. No custom theme

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/90745

### CODE REVIEW

File: scene/gui/button.cpp [hunk 1]
```diff
@@ -358,7 +358,7 @@ void Button::_notification(int p_what) {
 			if (!xl_text.is_empty()) {
 				text_buf->set_alignment(align_rtl_checked);
 
-				float text_buf_width = MAX(1.0f, drawable_size_remained.width); // The space's width filled by the text_buf.
+				float text_buf_width = Math::ceil(MAX(1.0f, drawable_size_remained.width)); // The space's width filled by the text_buf.
```
Comment (akien-mga) [inline scene/gui/button.cpp:361]: Should it be `round()` to avoid errors on the other end where `62.000000047` would become `63`?
Or is it better to err on the side of caution and have one too many pixels instead of one too few?

Comment (bruvzg) [reply scene/gui/button.cpp:361]: An extra pixel in the text buffer should not be an issue (it's setting max. width available for the string), so always ceiling is probably safer (I'm not sure how big the error can get since a lot of code is involved in control size calculations).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
