### PR TITLE
Make LineEdit secret character easier to change and enter

### LINKED ISSUE #81681: LineEdit secret character hard to change/enter
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 27.20.100.9621) - Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 Threads)

### Issue description

LineEdits secret character property is hard to edit in the inspector. It won't let me input more or less than one character so when I try and delete the default `.` to input my own character it gives me an error in the Output panel and does not change the `.`. You can change it by highlighting the `.` and typing the new character but that feels unintuitive to me so it took me a while to work out how to change it. 

### Steps to reproduce

1. Create a `LineEdit` node
2. Try and edit its Secret Character property in the Inspector without highlighting the `.`.

### Minimal reproduction project

Not really required but I'll add one if anyone asks.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #81681.
1. Allow values longer than 1 character in the property, but trim characters after the first one.
2. Allow empty strings, this acts like if a space was used as a secret character, so that an error isn't printed when you erase all characters in the property.

About the implementation, we can add another field for displaying the char and so `secret_character` can only store the result of the above rule or vice versa. But that requires more change, so I decided to change the drawing part, calculate the right `secret_character` based on the rule above.

### CODE REVIEW

File: scene/gui/line_edit.cpp [hunk 1]
```diff
@@ -2280,7 +2276,13 @@ void LineEdit::_shape() {
 	if (text.length() == 0 && ime_text.length() == 0) {
 		t = placeholder_translated;
 	} else if (pass) {
-		t = secret_character.repeat(text.length() + ime_text.length());
+		// Allow secret_character as empty strings, act like if a space was used as a secret character.
+		String secret = " ";
+		// Allow values longer than 1 character in the property, but trim characters after the first one.
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp:2281]: One question for evaluation is the usability of multi codepoint entries for non-latin scripts, but would require some integration with the text server, so out of scope for this, but something to consider

Comment (jsjtxietian) [reply scene/gui/line_edit.cpp:2281]: Yes, the origin code will assert if `p_string.length() != 1` so it assumes it must be lation scripts like English. I think maybe add support for non-latin secret character should be a standalone proposal.

Comment (AThousandShips) [reply scene/gui/line_edit.cpp:2281]: Agreed, might be worth adding a `TODO` there for it

File: scene/gui/line_edit.cpp [hunk 2]
```diff
@@ -2280,7 +2276,14 @@ void LineEdit::_shape() {
 	if (text.length() == 0 && ime_text.length() == 0) {
 		t = placeholder_translated;
 	} else if (pass) {
-		t = secret_character.repeat(text.length() + ime_text.length());
+		// Todo: Integrate with text server to add support for non-latin scripts.
```
Comment (AThousandShips) [inline scene/gui/line_edit.cpp:2279]:
```suggestion
		// TODO: Integrate with text server to add support for non-latin scripts.
```
Will pop in IDEs and easier to spot

File: doc/classes/LineEdit.xml [hunk 3]
```diff
@@ -269,7 +269,7 @@
 			If [code]true[/code], every character is replaced with the secret character (see [member secret_character]).
 		</member>
 		<member name="secret_character" type="String" setter="set_secret_character" getter="get_secret_character" default="&quot;•&quot;">
-			The character to use to mask secret input (defaults to "•"). Only a single character can be used as the secret character.
+			The character to use to mask secret input (defaults to "•"). Only a single character can be used as the secret character, if it is longer than one character, only use the first one. If it is empty, use a space instead.
```
Comment (AThousandShips) [inline doc/classes/LineEdit.xml:272]:
```suggestion
			The character to use to mask secret input (defaults to "•"). Only a single character can be used as the secret character, if it is longer than one character, only the first one will be used. If it is empty, use a space instead.
```

File: doc/classes/LineEdit.xml [hunk 4]
```diff
@@ -269,7 +269,7 @@
 			If [code]true[/code], every character is replaced with the secret character (see [member secret_character]).
 		</member>
 		<member name="secret_character" type="String" setter="set_secret_character" getter="get_secret_character" default="&quot;•&quot;">
-			The character to use to mask secret input (defaults to "•"). Only a single character can be used as the secret character.
+			The character to use to mask secret input (defaults to "•"). Only a single character can be used as the secret character, if it is longer than one character, only the first one will be used. If it is empty, use a space instead.
```
Comment (KoBeWi) [inline doc/classes/LineEdit.xml:272]:
```suggestion
			The character to use to mask secret input. Only a single character can be used as the secret character. If it is longer than one character, only the first one will be used. If it is empty, a space will be used instead.
```

**Comment by KoBeWi** [comment]
If extra characters are ignored, maybe we should have a configuration warning saying that.

File: doc/classes/LineEdit.xml (hunk 4 above)
Comment (jsjtxietian) [reply doc/classes/LineEdit.xml:272]: Thanks!

**Comment by KoBeWi** [comment]
By "configuration warning" I mean `get_configuration_warning()`. With your current implementation the warning will be spammed in the output.

File: scene/gui/line_edit.cpp [hunk 5]
```diff
@@ -2266,6 +2262,13 @@ void LineEdit::_emit_text_change() {
 	emit_signal(SNAME("text_changed"), text);
 	text_changed_dirty = false;
 }
+PackedStringArray LineEdit::get_configuration_warnings() const {
+	PackedStringArray warnings = Control::get_configuration_warnings();
+	if (secret_character.length() > 1) {
+		warnings.push_back("Only the first secret character is used, others are ignored.");
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:2268]:
```suggestion
		warnings.push_back("Secret Character property supports only one character. Extra characters will be ignored.");
```

**Comment by KoBeWi** [comment]
You need to call `update_configuration_warnings()` in `set_secret_character()`.

File: scene/gui/line_edit.cpp [hunk 6]
```diff
@@ -2281,7 +2284,15 @@ void LineEdit::_shape() {
...
 		t = placeholder_translated;
 	} else if (pass) {
-		t = secret_character.repeat(text.length() + ime_text.length());
+		// TODO: Integrate with text server to add support for non-latin scripts.
+		// Allow secret_character as empty strings, act like if a space was used as a secret character.
+		String secret = " ";
+		// Allow values longer than 1 character in the property, but trim characters after the first one.
+		if (!secret_character.is_empty()) {
+			secret = secret_character.left(1);
+			update_configuration_warnings();
```
Comment (KoBeWi) [inline scene/gui/line_edit.cpp:2293]: This call should be in `set_secret_character()`, it shouldn't be called excessively.

Comment (jsjtxietian) [reply scene/gui/line_edit.cpp:2293]: Agreed, thanks.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
