### PR TITLE
[macOS] Implement seamless display scaling.

### LINKED ISSUE #5688: MacOS: Moving Godot Editor Window from Retina Display to non Retina display does not resize the content appropriately
**Operating system or device - Godot version:**
2.1 beta 20160712 osx

_**Not reproducible with 2.0 stable version**_ 

**Issue description** (what happened, and what was expected):
When moving the window from a 'zoomed' monitor (Retina Display) to a non zoomed (Full HD) monitor the window content is too big

Retina before:
image

After moving to Non Retina Monitor:
image

**Steps to reproduce:**
(Using a MacBook Pro MBP)
- 1 External DVI monitor via Lightning Cable attached to MBP
- Start Godot on the Retina screen (Builtin screen) and open a project
- Move the window over to non retina screen

### LINKED ISSUE #13017: "Window Placement Centered" causes game window to appear offscreen on hi-DPI laptop
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

OS: Windows 10
Device: Dell XPS 15 9560
GPU: Nvidia GTX 1050
GPU Driver: 388.00
Screen Resolution:  3840 x 2160 px
Godot version: 3.0 alpha 2 

**Issue description:**

- Actual behaviour:

If Window Placement - Centred is selected in Editor Settings, when running a project using the 'Play Project' button, the game window opens outside the visible screen area (to the bottom-right). I have to move the window back onscreen to see it.

(However, Window Placement - Top Left works fine.)

- Expected behaviour:

The game window should be centred if Window Placement - Centred is selected in Editor Settings.

**Steps to reproduce:**

Load any project which runs windowed and ensure that Window Placement - Centred is selected in Editor Settings. Press 'Play Project'. 

**Link to minimal example project:**

*Bugsquad edit:* Keywords for searching: Windows, window, placement, location, position, screen, scaling, incorrect, offscreen, bottom, right, corner, bottom-right, center, centered, 125%, 150%, 175%, 200%, expected, unexpected, resolution.

### PR DESCRIPTION
**Pull request by bruvzg**
Use the highest display scale to calculate window/screen coordinates and for rendering, ~downscale~ (we do not need to do it ourselves, just let OS to do the job) on lower scale displays. Also, should fix popup positions.

Before (moving from hiDPI to lowDPI display):
mmove2

After:
mmove1

Fixes #5688 (no scale changes when moving from screen to screen)
Fixes #13017 (incorrect project window position when started from editor and project have different DPI settings).

*Update:*
- Added missing `No Focus` flag implementation.
- And tested all `window_...` and `screen_...` functions in the DS, except `window_set_input_text_callback` (callback is not used on any desktop platform) and `window_set_transient` (I have no idea what it is really supposed to do), everything seems to work.

### CODE REVIEW

File: scene/main/window.cpp [hunk 1]
```diff
@@ -647,6 +648,12 @@ void Window::_update_viewport_size() {
 	_set_size(final_size, final_size_override, attach_to_screen_rect, stretch_transform, allocate);
 
 	if (window_id != DisplayServer::INVALID_WINDOW_ID) {
+#ifdef OSX_ENABLED
```
Comment (bruvzg) [inline scene/main/window.cpp:651]: Not sure this is the right way and place to downscale it. Font oversampling probably should be changed too.

**Comment by akien-mga** [comment]
Fixes #5688 I presume?

**Comment by bruvzg** [comment]
> Fixes #5688 I presume?

Yes

File: servers/display_server.cpp [hunk 2]
```diff
@@ -392,6 +392,7 @@ void DisplayServer::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("screen_get_dpi", "screen"), &DisplayServer::screen_get_dpi, DEFVAL(SCREEN_OF_MAIN_WINDOW));
 	ClassDB::bind_method(D_METHOD("screen_get_scale", "screen"), &DisplayServer::screen_get_scale, DEFVAL(SCREEN_OF_MAIN_WINDOW));
 	ClassDB::bind_method(D_METHOD("screen_is_touchscreen", "screen"), &DisplayServer::screen_is_touchscreen, DEFVAL(SCREEN_OF_MAIN_WINDOW));
+	ClassDB::bind_method(D_METHOD("screen_get_max_scale"), &DisplayServer::screen_get_max_scale);
```
Comment (Calinou) [inline servers/display_server.cpp:395]: Documentation should be added for this method by running `--doctool .` and updating the class reference XML.

**Comment by akien-mga** [comment]
Thanks hugely!

**Comment by bruvzg** [comment]
It should be possible to do similar change for 3.2, but this will involve fully rewriting macOS OpenGL context from View backed to Layer backed (eventually should be done for 4.0 GL support anyway).
