### PR TITLE
Editor: Ignore CapsLock when pressed alone

### LINKED ISSUE #73073: Editor: Pressing CapsLock hides code completion
### Godot version

4.0-rc1

### System information

Windows 10; Ubuntu VM

### Issue description

In Godot's GDScript Editor and Shader Editor, when pressing CapsLock, the code completion closes.
I'm using AutoHotkey to have arrows on ijkl, when CapsLock is pressed. Works fine in VS and VS Code.

### Steps to reproduce

- Edit a GDScript file with Godot
- Bring up code completion (by typing `self.` in any function or `Ctrl+Space`)
- Press CapsLock.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by M4rYu5**
**Now:** CapsLock will behave like other modifier keys: does nothing when pressed alone.

Fixes #73073

### CODE REVIEW

**Review by Paulb23 — APPROVED** [review]

File: scene/gui/code_edit.cpp [hunk 1]
```diff
@@ -436,12 +436,12 @@ void CodeEdit::gui_input(const Ref<InputEvent> &p_gui_input) {
...
 	/* If a modifier has been pressed, and nothing else, return. */
-	if (!k->is_pressed() || k->get_keycode() == Key::CTRL || k->get_keycode() == Key::ALT || k->get_keycode() == Key::SHIFT || k->get_keycode() == Key::META) {
+	if (!k->is_pressed() || k->get_keycode() == Key::CTRL || k->get_keycode() == Key::ALT || k->get_keycode() == Key::SHIFT || k->get_keycode() == Key::META || k->get_keycode() == Key::CAPSLOCK) {
 		return;
 	}
 
-	/* Allow unicode handling if:              */
-	/* No Modifiers are pressed (except shift) */
+	/* Allow unicode handling if:							*/
+	/* No Modifiers are pressed (except shift and CapsLock)	*/
```
Comment (KoBeWi) [inline scene/gui/code_edit.cpp:444]:
```suggestion
	// Allow unicode handling if:\
	// * No Modifiers are pressed (except shift and CapsLock)
```

Comment (YuriSizov) [reply scene/gui/code_edit.cpp:444]: The fact that Shift is not capitalized, but CapsLock is... is annoying. 👀

Comment (M4rYu5) [reply scene/gui/code_edit.cpp:444]: now I have to modify -> commit --amend -> push --force ?

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
