### PR TITLE
Move project-specific editor data into res://.godot/editor

### LINKED ISSUE #282: Editor project data should be stored in project folder, not in \Godot Engine\editor_data\projects
**Describe the project you are working on:**
Not applicable.

**Describe the problem or limitation you are having in your project:**
Moving around project folder and renaming it resets everything about project's editor state, as a new `editor_data\projects` is generated based on path and name. This also makes it impossible to store that folder in VCS, which can be useful for personal projects.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It is a common practice among programming software to store state for each project inside the project folder, in a file, like `.editorconfig`, or under a subfolder, like `.idea`, `.vs`, `.git`, `.hg`, etc. This makes project folder a fully contained environment to start working on the project.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Not applicable.

**Describe implementation detail for your proposal (in code), if possible:**
There are two ways this can be implemented:

* As a default behavior
  1. When creating a new project, setup a `.godot` folder inside the project folder immediately
  2. When opening an existing project, look for `.godot` folder inside the project folder
  3. If none is present, check the old path `editor_data\projects` for a pre-existent folder in old form

* As a project setting
  1. When creating a new project, allow user to check whether to store editor data locally or in `editor_data\projects`, and create the corresponding folder (I suggest setting the checkbox to TRUE by default)
  2. When opening an existing project, check `project.godot` for setting and then look for the corresponding folder
  3. If the folder does not exist, create it
  4. If the setting does not exist, assume default behavior, save setting and create the corresponding folder
  5. When changing the setting from within the editor, move current folder's content into the new folder, save setting, then ask the user to restart the editor (I assume, this is required)

I understand, there might be a problem when opening the same project with different versions of Godot, as currently each Godot folder stores its own settings for each project. If this is important, some sanity checks must be implemented, when working with local editor folder. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it's not a part of user space.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a part of internal editor logic.

### LINKED ISSUE #42578: Favorites from a deleted project in a new one with the same name
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
macOS Catalina 10.15.5

**Issue description:**
When you delete a project and create a new one with the same name in the same folder, Godot uses favorites from the deleted project. The same might be true for some of the cache files stored in " /Users/marcin/Library/Application\ Support/Godot/projects". 

**Steps to reproduce:**
1. Create a new project
2. Create a new folder
3. Create a new scene and save it in the folder
4. Add scene to favorites
5. Save the project and close Godot
6. Delete the project folder
7. Open Godot and remove the missing project
8. Create a new project with the same name in the same folder

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes https://github.com/godotengine/godot-proposals/issues/282, follow up to #38607, fixes #42578. This PR moves the project-specific editor data files into a subfolder of `res://.godot` called `res://.godot/editor` (defined as a constant: `EditorSettings::EDITOR_FILES_PATH`). 

One advantage of this change is that it's easy to delete a project without leaving any files behind. Another advantage is that if you screw up the editor settings for your project, it's very easy to reset them by deleting `res://.godot` (or just `res://.godot/editor`). A third advantage is that if you move a project to a different location, your editor settings are still there (previously the editor settings were stored in a location with the MD5 sum of the project path, so if the path changes then you lose the settings).

A change that people may or may not see as an advantage is that if you ZIP up a project without deleting the `res://.godot/editor` folder, you will share the project-specific editor settings with the recipient of that ZIP file, so they should see exactly what you see (in terms of editor layout, but not non-project-specific settings like the theme or font size).

A question remains about whether or not this should be configurable. It makes the code a lot simpler to just make it always inside the project, but maybe some people wouldn't like this behavior.

### CODE REVIEW

**Comment by Xrayez** [comment]
> A question remains about whether or not this should be configurable. It makes the code a lot simpler to just make it always inside the project, but maybe some people wouldn't like this behavior.

I have/know of at least two plugins which store their editor settings per project ([Plugin Refresher](https://github.com/godot-extended-libraries/godot-plugin-refresher/blob/e2b12f448b9fc112fd0f4acdc6de8df6180b464e/addons/godot-plugin-refresher/plugin_refresher_plugin.gd#L81-L86)), and those rely on `get_project_settings_dir` which is in fact exposed through the editor interface in 3.2 to scripting.

I know that we're breaking compatibility but it doesn't have to be a justification for breaking it completely. What I mean is that, returning the constant `res://.godot/editor` by `get_project_settings_dir` would also suffice (it doesn't have to be configurable). This would likely create less changes on the diff in this PR. 😉

If performance is a concern, then making the method `inline` would also be a solution.

Retaining `get_project_settings_dir` would also be good for documentation purposes, as it can be documented just like any other `Object` method, hence improves discoverability within the built-in documentation as well.

**Comment by aaronfranke** [comment]
@Xrayez Alternatively, we could either expose the constant itself, or we could encourage users to pick their own folder inside of `.godot` like `.godot/myplugin`.

**Comment by pycbouh** [comment]
I guess a method like this (but probably not called `get_project_settings_dir`) can return the root of `res://.godot` instead. Though, arguably, at this point there is not a lot of use in a function for looking up a folder which is discoverable as `res://.godot`.

**Comment by Xrayez** [comment]
> Alternatively, we could either expose the constant itself, or we could encourage users to pick their own folder inside of `.godot` like `.godot/myplugin`.

I just think there are many similar methods currently accessible via the `EditorInterface` in the same manner, which have the pattern of `get_*_path`, so I'd think twice before removing *editor interface* methods which are exposed specifically for convenience purpose, like improving the editor traversal.

For instance, it's possible to access the `EditorNode` root and do `get_child()` to get the base, other plugins etc:
```gdscript
var base = get_tree().get_root().get_child(0) # This might not be the base, but you get the point.
```

Plugins like https://github.com/Zylann/godot_editor_debugger_plugin take advantage of this ability, in fact.

But doing so via `EditorInterface` simplifies this task currently:
```gdscript
var base = get_editor_interface().get_base_control()
```
So the main purpose of those methods is exactly convenience, in my opinion. If adding a constant helps to avoid quite verbose `EditorSettings->get_singleton()->get_project_settings_dir()` in C++, then should be ok, as long as `get_project_settings_dir` is retained.

The pros and cons for this are also described in godotengine/godot-proposals#70.

---

Plugins themselves could also have their respective folder, like `.godot/plugins/myplugin` or `.godot/editor/plugins/myplugin`. Building upon pycbouch's idea, `get_plugin_settings_dir` could also be added, although it may be that not every plugin would need to store plugin-related settings. Plugin names can be uniquely inferred from `addons/` currently.

> Also, AFAIK, the method can't be explicitly inlined if it's also exposed, because of how inlining works.

Making method calls inline would only work at compile-time for C++ usage, I think it shouldn't affect GDScript calls, but it's likely not performance-critical anyways.

**Comment by Xrayez** [comment]
> I guess a method like this (but probably not called `get_project_settings_dir`) can return the root of `res://.godot` instead. Though, arguably, at this point there is not a lot of use in a function for looking up a folder which is discoverable as `res://.godot`.

`get_project_settings_dir` can also be renamed to `get_project_editor_settings_dir` if we aim at breaking compatibility completely, then again my main concern is retaining the method to be usable in scripts.

**Comment by aaronfranke** [comment]
@Xrayez What do you think of this PR in its current state?

**Review by Xrayez — APPROVED** [review]

File: editor/editor_settings.cpp [hunk 1]
```diff
@@ -1247,7 +1239,7 @@ String EditorSettings::get_settings_dir() const {
 }
 
 String EditorSettings::get_project_settings_dir() const {
-	return get_settings_dir().plus_file("projects").plus_file(project_config_dir);
+	return EditorSettings::PROJECT_EDITOR_SETTINGS_PATH;
```
Comment (akien-mga) [inline editor/editor_settings.cpp:1242]: Since there's a getter for it specifically, maybe it doesn't need to be a separate constant? You could just use `get_project_settings_dir()` in `create()`.

**Comment by akien-mga** [comment]
Just noting that I like the idea, I'll test the PR and review the above discussion more in-depth before approving.

File: editor/editor_settings.cpp (hunk 1 above)
Comment (aaronfranke) [reply editor/editor_settings.cpp:1242]: The original idea was to remove the methods and only have the constant, but the method is still needed if we want to expose this (we can't bind string constants AFAIK, just numeric ones).

File: editor/editor_settings.h [hunk 2]
```diff
@@ -46,6 +46,7 @@ class EditorSettings : public Resource {
 	_THREAD_SAFE_CLASS_
 
 public:
+	static const String PROJECT_EDITOR_SETTINGS_PATH;
```
Comment (akien-mga) [inline editor/editor_settings.h:49]: I think you can make this `inline static const` and move the initialization here.

Comment (aaronfranke) [reply editor/editor_settings.h]: Good idea, I didn't know this was possible.

File: editor/editor_settings.cpp [hunk 3]
```diff
@@ -959,27 +959,18 @@ void EditorSettings::create() {
...
-		}
-		project_config_dir = project_config_dir.get_file() + "-" + project_config_dir.md5_text();
-
-		if (dir->change_dir(project_config_dir) != OK) {
-			dir->make_dir(project_config_dir);
-		} else {
-			dir->change_dir("..");
+		{
+			// Validate/create project-specific editor settings dir.
+			DirAccess *da = DirAccess::open("res://");
```
Comment (akien-mga) [inline editor/editor_settings.cpp:964]: You can use `DirAccessRef da`, so you don't need to `memdelete()` it (done automatically when it goes out of scope).

Comment (akien-mga) [reply editor/editor_settings.cpp:964]: Also, I *think* we tend to use `DirAccess::create(DirAccess::ACCESS_RESOURCES);` which should be equivalent (didn't check though).

**Review by akien-mga — APPROVED** [review]
Looks good to me overall, I think it's a good idea.
I was growing tired of having to go to `~/.config/godot/project/<name>-<hash>/` to clear editor metadata or debug issues with it.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
