### PR TITLE
Prevent renaming to an unkown extension from FileSystem dock.

### LINKED ISSUE #56805: Renaming a script without a supported file extension, hides the script without a warning
### Godot version

v3.4.1.stable.official [aa1b95889]

### System information

Windows 10 21H1

### Issue description

Renaming a script in the FileSystem panel, by removing the file extension `.gd`

Hides the file from the FileSystem panel, without showing a warning message.

This might seem like it was deleted.
But it's still available in the project directory.

### Steps to reproduce

In the FileSystem panel
- Create a new script file
- Rename it by removing the extension `.gd`

### Observed
The file disappears from the FileSystem panel.

### Expected
A warning message should probably be shown.

Stating that renaming a file without a supported extension, will hide the file in Godot.

It will not be deleted, it's still available in the project directory.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by jmb462**
Fixes #56805

### Issue description

Renaming a file in FileSystem dock to an unrecognized extension hides the file in editor.
No warning. Just a file that disapears. Can't be undone from editor FileSystem dock.

### Fix proposal

Prevent doing such a thing because it is probably a mistake and it can't be undone from the editor which may be quite misleading.
Instead of renaming, show a warning explaining the situation.
Invite user to use system file explorer to do such a rename on purpose.

image

As english is not my native language, you are invited to provide me a better message if you think it's needed.

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1472,12 +1472,22 @@ void FileSystemDock::_folder_removed(String p_folder) {
...
 		return;
 	} else if (new_name.find("/") != -1 || new_name.find("\\") != -1 || new_name.find(":") != -1) {
 		EditorNode::get_singleton()->show_warning(TTR("Name contains invalid characters."));
 		return;
+	} else if (old_name.get_extension() != new_name.get_extension()) {
+		List<String> extensions;
+		ResourceLoader::get_recognized_extensions_for_type("", &extensions);
+		const Vector<String> textfile_ext = ((String)(EditorSettings::get_singleton()->get("docks/filesystem/textfile_extensions"))).split(",", false);
+		bool extension_unkown = !extensions.find(new_name.get_extension()) && textfile_ext.find(new_name.get_extension()) == -1;
+		if (to_rename.is_file && extension_unkown) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1487]: `to_rename.is_file` could be moved to the condition above, to avoid checking extension when it's not necessary.
Then the `extension_unkown` variable is not needed.

**Comment by KoBeWi** [comment]
I noticed that EditorFileSystem has a list of valid extensions. Maybe we could add a method to retrieve it, so it can be reused?

File: editor/filesystem_dock.cpp (hunk 1 above)
Comment (jmb462) [reply editor/filesystem_dock.cpp]: Done.

**Comment by jmb462** [comment]
> I noticed that EditorFileSystem has a list of valid extensions. Maybe we could add a method to retrieve it, so it can be reused?

I've added a method : ``Set<String> EditorFileSystem::get_valid_extensions() const``
It's just returning ``valid_extensions``. As the list is updated in scan(), I'm not sure if we need to check if valid_extension is not empty and if empty, call _update_extensions().

The function is not exposed to GDScript. Don't know if it will be very usefull (plugins ?)

**Review by KoBeWi — APPROVED** [review]
Looks good. The message might need tweaking though, CC @Calinou 

> As the list is updated in scan(), I'm not sure if we need to check if valid_extension is not empty and if empty, call _update_extensions().

AFAIK editor automatically scans on startup, so this is not a problem.

> The function is not exposed to GDScript. Don't know if it will be very usefull (plugins ?)

No need to expose it for now.

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -1472,12 +1472,18 @@ void FileSystemDock::_folder_removed(String p_folder) {
...
+	String old_name = tree->get_selected()->get_text(0);
 	if (new_name.length() == 0) {
 		EditorNode::get_singleton()->show_warning(TTR("No name provided."));
 		return;
 	} else if (new_name.find("/") != -1 || new_name.find("\\") != -1 || new_name.find(":") != -1) {
 		EditorNode::get_singleton()->show_warning(TTR("Name contains invalid characters."));
 		return;
+	} else if (to_rename.is_file && old_name.get_extension() != new_name.get_extension()) {
+		if (!EditorFileSystem::get_singleton()->get_valid_extensions().find(new_name.get_extension())) {
+			EditorNode::get_singleton()->show_warning(TTR("This extension is not recognized by editor.\nIf you want to rename it anyway, please use your system file explorer.\nThen, the file won't be shown anymore in Godot editor."));
```
Comment (Calinou) [inline editor/filesystem_dock.cpp:1484]:
```suggestion
			EditorNode::get_singleton()->show_warning(TTR("This extension is not recognized by the editor.\nIf you want to rename it anyway, use your operating system's file manager.\nAfter renaming to an unknown extension, the file won't be shown in the editor anymore."));
```

Comment (jmb462) [reply editor/filesystem_dock.cpp]: Thanks. Updated.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.
