### PR TITLE
Fix clear color on mobile renderer

### LINKED ISSUE #79931: Clear color is lighter on mobile renderer
### Godot version

4.1.1

### System information

windows 11, mobile renderer

### Issue description

On Mobile Vulkan renderer, the clear color is 50% lighter than expected

See steps to reproduce and Minimal reproduction project below.

The box and background have the same color on Forward+ and compatibility, but not on Mobile
happens also in runtime on exported project, not only in editor preview

Images of the same scene from
compatibility:
compatibility
Forward+:
forward
Mobile:
mobile

### Steps to reproduce

 - add a CSGBox3D with "unshaded" shading, and albedo of #545454
 - add environment with Background = Custom color and color of #545454

Box and background are not the same color

### Minimal reproduction project

[bg_color.zip](https://github.com/godotengine/godot/files/12174822/bg_color.zip)

### PR DESCRIPTION
**Pull request by ChibiDenDen**
Fix for #79931

* *Bugsquad edit, fixes: #79931*
* *Bugsquad edit, alternative to: #80663*

### CODE REVIEW

**Comment by AThousandShips** [comment]
There's already a fix for this:
* #80663

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 1]
```diff
@@ -899,14 +900,14 @@ void RenderForwardMobile::_render_scene(RenderDataRD *p_render_data, const Color
 			// regular forward for now
 			Vector<Color> c;
 			{
-				Color cc = clear_color.srgb_to_linear();
+				Color cc = clear_color.srgb_to_linear().darkened(inverse_luminance_multiplier);
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:903]: This should just be a multiply operation instead of using the `darkened` operation

**Review by clayjohn — COMMENTED** [review]
Thanks! Looks mostly good, but see my comment

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp (hunk 1 above)
Comment (akien-mga) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:903]: Does this apply to both lines using `darkened`, or just this one?

Comment (clayjohn) [reply servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:903]: Both

**Review by clayjohn — APPROVED** [review]
Looks great! Thanks

**Comment by clayjohn** [comment]
Actually just cherrypick for 4.1 I think. As this is a pretty clear visual change

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
> Actually just cherrypick for 4.1 I think.

@clayjohn Changes here kind of build upon https://github.com/godotengine/godot/pull/79876. Should we also pick that one? Or I can fix the conflicts manually. Or we can forgo picking completely at this point.

**Comment by clayjohn** [comment]
Let's just cherrypick https://github.com/godotengine/godot/pull/79876 as well.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
