### PR TITLE
Simplify DisplayServerWindows pos/size message handling

### LINKED ISSUE #45740: Wrong popups/tooltips offset in the editor (DisplayServer regression)
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
image

**OS/device including version:**
Windows 10 x64
Using Vulkan Device #0: AMD - AMD Radeon R7 200 Series

**Issue description:**
When you click any tab (Project,Scene,Debug) or even right click to add node the popup appears far away form mouse:
image

**Steps to reproduce:**
Just interact with engine itself

**Workaround**
minimize window and maximize again!

### PR DESCRIPTION
**Pull request by rxlecky**
Replace WM_MOVE and WM_SIZE message handling with WM_POSCHANGED instead.
This is for multiple reasons:
1) Microsoft suggest using WM_POSCHANGED for efficiency reasons
2) RectChanged callback is only called once for most window operations
3) It's less code

This _should_ also close #45740 but it would be good to test on other machines as I was struggling to reproduce the bug on master today.

### CODE REVIEW

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -1766,15 +1766,15 @@ void DisplayServerWindows::window_set_vsync_mode(DisplayServer::VSyncMode p_vsyn
 	_THREAD_SAFE_METHOD_
 #if defined(VULKAN_ENABLED)
 	// TODO disabling for now
-	//context_vulkan->set_vsync_mode(p_window, p_vsync_mode);
+	// context_vulkan->set_vsync_mode(p_window, p_vsync_mode);
```
Comment (akien-mga) [inline platform/windows/display_server_windows.cpp:1769]: That's weird, `clang-format` is configured specifically not to do that. Did you author this on an old branch (pre #54133) before rebasing on `master` maybe?

Comment (rxlecky) [reply platform/windows/display_server_windows.cpp:1769]: Oh no, sorry, that's my fault. I had to comment out `SpacesInLineCommentPrefix` from .clang-format because that's a new Clang 13 option and LLVM haven't yet updated Windows clang-format binary to the new version. I thought it was okay to add a leading space, though, since vast majority of comments in those files already use a leading space and it was just more consistent. I can undo those changes, though, if that would be better.

**Comment by jmb462** [comment]
I confirm that #45740 seems to be fixed by your PR.

Can't reproduce anymore with your PR.  (I can reproduce it everytime with current master branch)

**Comment by akien-mga** [comment]
Would need a rebase.

**Comment by rxlecky** [comment]
Rebased now. I also got rid of the wrong `clang-format` changes adding space in comments.

**Comment by Logharaa** [comment]
Could not reproduce #45740 with this PR either (on Windows 10)

**Review by bruvzg — APPROVED** [review]
