### PR TITLE
Use `angle_rand` to calculate `base_angle` in particles process material

### LINKED ISSUE #49767: Vulkan: GPUParticles3D angular velocity has jumps
### Godot version

v4.0.dev.custom_build [1acc76fec]

### System information

Linux Arch, Radeon RX 590

### Issue description

Enabling angular velocity  results in the particle angle to abruptly jump during the particle lifetime

https://gfycat.com/difficultweebrontosaurus

### Steps to reproduce

- Create a 3D scene with a particle node
- Assign quad material with particle billboard
- Enable angular velocity

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/49767

Using ``angle_rand`` for the random value ensures that the returned ``base_angle`` is the same in the ``start()`` function and in the ``process()`` function.

I also changed the base ``tex_angle`` to 1.0 to match the ``process()`` function. Without this change the base_angle was always 0 in the ``start()`` function which could lead to a different kind of snapping on the first frame.

### CODE REVIEW

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -419,7 +419,7 @@ void ParticleProcessMaterial::_update_shader() {
 	if (tex_parameters[PARAM_ANGLE].is_valid()) {
 		code += "	float tex_angle = textureLod(angle_texture, vec2(0.0, 0.0), 0.0).r;\n";
 	} else {
-		code += "	float tex_angle = 0.0;\n";
+		code += "	float tex_angle = 1.0;\n";
```
Comment (akien-mga) [inline scene/resources/particle_process_material.cpp:422]: I notice that CPUParticles also used in turns `0.0` and `1.0` like ParticlesProcessMaterial, should they be changed too?
```
$ rg 'tex_angle ='
scene/3d/cpu_particles_3d.cpp
745:                    real_t tex_angle = 0.0;
747:                            tex_angle = curve_parameters[PARAM_ANGLE]->sample(tv);
945:                    real_t tex_angle = 1.0;
947:                            tex_angle = curve_parameters[PARAM_ANGLE]->sample(tv);

scene/2d/cpu_particles_2d.cpp
725:                    real_t tex_angle = 0.0;
727:                            tex_angle = curve_parameters[PARAM_ANGLE]->sample(tv);
861:                    real_t tex_angle = 1.0;
863:                            tex_angle = curve_parameters[PARAM_ANGLE]->sample(tv);

scene/resources/particle_process_material.cpp
420:            code += "       float tex_angle = textureLod(angle_texture, vec2(0.0, 0.0), 0.0).r;\n";
422:            code += "       float tex_angle = 0.0;\n";
638:            code += "       float tex_angle = textureLod(angle_texture, vec2(tv, 0.0), 0.0).r;\n";
640:            code += "       float tex_angle = 1.0;\n";
```

**Comment by clayjohn** [comment]
Updated to fix the base ``tex_angle`` in CPUParticles as well

**Review by akien-mga — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by unfa** [comment]
Sweet! I gotta test this in 4.0.3 :)
