### PR TITLE
Apply `fix_alpha_edges` for both theme icons and font glyphs.

### LINKED ISSUE #102839: SVG glyphs in TTF fonts show artifacts when not at 100% scale
### Tested versions

4.4.beta3

Same in 4.3 so doesn't look like a regression.

### System information

Godot v4.4.beta3 - Windows 11 (build 26100) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 32.0.15.6636) - 13th Gen Intel(R) Core(TM) i7-13700KF (24 threads)

### Issue description

When zoomed in or out in either editor preview or app the edges of the SVG glyphs show artifacts. 

Image

### Steps to reproduce

Open MRP, zoom in/out in 2D preview. Or launch app and resize window.
At 100% glyphs look ok.

The testFont.ttf contains only 2 glyphs (at codepoints '#' and 'H'). Font was generated from SVGs in MRP using https://github.com/googlefonts/nanoemoji using `--color_format picosvgz` i.e. using SVG table

### Minimal reproduction project (MRP)

[svgfonttest1.zip](https://github.com/user-attachments/files/18793066/svgfonttest1.zip)

### PR DESCRIPTION
**Pull request by mooflu**
Fixes https://github.com/godotengine/godot/issues/102839

Updated, so _font_draw_glyph only calls fix_alpha_edges when it's a SVG glyph.

### CODE REVIEW

File: modules/text_server_adv/text_server_adv.cpp [hunk 1]
```diff
@@ -1319,10 +1319,15 @@ _FORCE_INLINE_ bool TextServerAdvanced::_ensure_glyph(FontAdvanced *p_font_data,
 		}
 
 		if (!outline) {
+			FT_GlyphSlot slot = fd->face->glyph;
+			bool from_svg = false;
+			if (slot->format == FT_GLYPH_FORMAT_SVG) {
+				// Need to check before FT_Render_Glyph as it will change format to bitmap
+				from_svg = true;
+			}
```
Comment (bruvzg) [inline modules/text_server_adv/text_server_adv.cpp:1327]:
```suggestion
			bool from_svg = (slot->format == FT_GLYPH_FORMAT_SVG); // Need to check before FT_Render_Glyph as it will change format to bitmap.
```

File: modules/text_server_adv/text_server_adv.cpp [hunk 2]
```diff
@@ -3806,6 +3812,10 @@ void TextServerAdvanced::_font_draw_glyph(const RID &p_font_rid, const RID &p_ca
 				if (ffsd->textures[fgl.texture_idx].dirty) {
 					ShelfPackTexture &tex = ffsd->textures.write[fgl.texture_idx];
 					Ref<Image> img = tex.image;
+					if (fgl.from_svg) {
+						// same as the "fix alpha border" process option when importing SVGs
```
Comment (bruvzg) [inline modules/text_server_adv/text_server_adv.cpp:3816]:
```suggestion
						// Same as the "fix alpha border" process option when importing SVGs.
```

Dirty textures can be updated in multiple functions, so `fix_alpha_edges` should be applied there as well.
```
_font_get_glyph_texture_rid
_font_get_glyph_texture_size
_font_draw_glyph
_font_draw_glyph_outline
```

**Review by bruvzg — COMMENTED** [review]
Seems to be working fine.

There's the same code in the fallback text server (`modules/text_server_fb`), the same changes should be added to it as well.

**Comment by mooflu** [comment]
Thanks for review. Updated code. If it looks good I can squash.

While testing I noticed drop shadow (keeps color) and outline (none) for svg glyphs look like this (regular 't' for comparison):
image

**Comment by mooflu** [comment]
Changed back to draft. I'd like to understand this better. 

I don't think outline makes sense for SVGs. Outline uses FT_LOAD_NO_BITMAP which results in a format of FT_GLYPH_FORMAT_OUTLINE and not FT_GLYPH_FORMAT_SVG so fix_alpha_edges won't run.

font_get_glyph_texture_rid and font_get_glyph_texture_size seem to used in 3d (Label3D) and I've only tested 2d so far.

**Comment by bruvzg** [comment]
> I don't think outline makes sense for SVGs.

Indeed, outline should be irrelevant for SVG fonts.

**Comment by mooflu** [comment]
with these changes before (beta3) and after:
before
after

**Comment by mooflu** [comment]
Also tested and fixed text fallback server. Squashed.

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
