### PR TITLE
Unified GLES3 / GLES2 Batching

### LINKED ISSUE #19943: Polygon2D is extremely slow compared to Sprite rendering
**Godot version:**
3.04

**OS/device including version:**
Windows 10 / Surface Pro 4

**Issue description:**
Polygon2D seems alarmingly slow when compared to Sprite or draw_rect().

Here are some results from a small test scene I made:
godot3_poly2d_performance

I've had the same results in a game project where I've attempted to create levels from Polygon2D objects. Usually optimized meshes would be very useful for optimizing fillrate, but this performance seems to make it impossible to utilize. I feel like this is going to hurt many graphically demanding 2D-projects.

**Steps to reproduce:**
Comparing between Sprite / Polygon2D and draw_rect() / draw_polygon() seems to give similiar results.

**Minimal reproduction project:**
[polygon2d_performance.zip](https://github.com/godotengine/godot/files/2160787/polygon2d_performance.zip)

### LINKED ISSUE #33225: NinePatch changes texture scale when resized
Godot version:
Godot 3.2 Alpha 3 (from your website)

OS/device including version:
Windows 10

Issue description:
When doing pixelated texture, resizing the Ninepatch changes its scale.

Steps to reproduce:
1. Add a pixelated nine patch frame
2. Set up the patch margins
3. resize the nine patch in the editor.

Minimal reproduction project:
https://i.imgur.com/VeQeuhQ.gifv

Notes: Godot 3.2 alpha 1 doesn't have this issue. Anything past alpha 1 has this issue.

### LINKED ISSUE #35772: Render "GLES2" does not draw Polygon2D on Android
godot 3.1.2-stable

Android 6.0 (BF166_BOOST3-SE_L010)

If you use the "GLES2" render, then the Polygon2D is not drawn!
If you use the "GLES3" render, then everything works
Textures imported as Loss

GLES2:
image of GLES2

GLES3:
image of GLES3

PS:
I need [it for beautiful animations](https://www.youtube.com/watch?v=4YfzkH1RHsg)

### LINKED ISSUE #36749: Polygon2D with Skeleton2D assigned does not render in the browser with GLES2
**Godot version:** 3.2

**OS/device including version:** HTML5 (multiple browsers tested on both Windows and Linux)

**Issue description:**
Any Polygon2D with a Skeleton2D assigned to it does not render in the browser with the GLES2 backend enabled. WebGL does not recognize `GL_UNSIGNED_INT` as a valid enum variant for the 3rd argument to `glVertexAttribPointer` in https://github.com/godotengine/godot/blob/416cd715a3f51b7d74676fa7d4c8e34c3c2823c9/drivers/gles2/rasterizer_canvas_gles2.cpp#L337

Changing it to `GL_UNSIGNED_SHORT` or `GL_UNSIGNED_BYTE` causes the polygons to render, but of course transformations of the bones result in mangled textures when they overflow the type.

Switching to GLES3 fixes the issue, but of course this is generally not recommended for HTML5 games, which caused me to dig into the Godot source before even trying this.

**Steps to reproduce:**
In a GLES2 project, create a Polygon2D and Skeleton2D node. The Skeleton2D can have bones in it or not; it will not work either way. Assign the Skeleton2D to the Polygon2D, and export the project to HTML5. The polygon will not render, but If you switch the project to GLES3, it will render properly.

### LINKED ISSUE #37077: Are there errors in the NinePatchRect algorithm?
**Godot version:3.2.1:**

I have to talk about NinePatchRect again. I wonder if there is an error in the NinePatchRect algorithm in the control?
Below is an example of the NinePatchtexture plugin I wrote. You can see the obvious differences by comparing the effects.

[NinePatchTexture-Demo](https://codeload.github.com/qq715152910/Godot-Bug/zip/master)
-5e8aa7331e9a8573

OK, this is normal, then you look at the second picture, I have updated the demo, you can download a new demo to see a new demo example.
In Jiugong's standard algorithm:
1.The four corners should be kept (tiled) to their original size
2. The four sides should keep one-way scaling
3. The middle area should maintain two-way scaling

But I think NinePatchRect's current algorithm has lost its practical significance.

test2

### LINKED ISSUE #41324: 2D normal mapping rotations incorrect
**Godot version:**
3.2.2

**OS/device including version:**
All (GLES2 and GLES3)

**Issue description:**
_Note this is a stub issue for reference, to illustrate the problem which is now hopefully fixed with 2 PRs._

When using normal mapping in 2D, flips and rotations only produce correct results in the old TEXTURE_RECT (uniform draw) method. The results are incorrect with GLES2 and GLES3 nvidia workarounds, and with GLES2 batching.

i.e. If you rotate a sprite, or flip, the normal mapping will not adjust according to the new orientation with the light.

In GLES2 and GLES3 nvidia workaround, rotations work but flips do not.
In GLES2 batching, both flips and rotations do not work.

**Steps to reproduce:**
Add a normal mapped sprite using GLES2 or GLES3 using `nvidia_workaround` project setting, or GLES2 batching.
Add a 2D light so you can see the normal map lighting.

Flip and rotate the sprite. Note that the normal maps do not rotate correctly to match the lighting.

### LINKED ISSUE #42576: Linking polygon2D points to bone2D goes wrong
**Godot version:**
Godot Engine v3.2.3.stable.official
OpenGL ES 2.0 Renderer: Intel(R) HD Graphics
OpenGL ES 2.0 Batching: ON

**OS/device including version:**
Processor: Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 CPUs), ~2.1GHz
Memory: 4096MB RAM
Card name: Intel(R) HD Graphics
Chip type: Intel(R) HD Graphics (Core i3)
DAC type: Internal
System: Windows 7 Professional x64

**Issue description:**
When I try to link a few polygon2D points to a bone2D the sprite gets distorted. If I link all the points, the image disappears
Video: https://youtu.be/oqmed2EWGog

**Steps to reproduce:**
Open "Player.tscn, Select LegR object and click over UV. On UV editor, select Bones and select the bLegR bone. Select a few points and click "OK". 

**Minimal reproduction project:**
[GodotTest.zip](https://github.com/godotengine/godot/files/5328458/GodotTest.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
Very much a WIP, the new unified batching both provides acceleration for GLES3 and will be adding new features which will also improve GLES2 batching.

There will probably be issues with custom shaders to sort out, but it seems to run the platformer demo fine and a few test games and the editor.

Uses the curiously recurring template pattern to share code between the 2 backends.

Fixes #19943.
Fixes #37077.
Fixes #33225.
Fixes #42576.
Fixes #35772.
Fixes #36749.
Fixes #41324.
Mitigates #40905.

Benchmarking with the text benchmark I used for GLES2, I get 45x increase in fps, versus ~78x for GLES2. That is to be expected as the bottlenecks are slightly different in GLES3. This benchmark is specifically designed to look at drawcalls, real life increases are likely to be far less dramatic.

## Expectations
* As with GLES2 batching, any increases in performance will depend on how much your project is bottlenecked by drawcalls. Projects using tilemaps / lots of text will typically benefit the most. Custom shaders may or may not be able to be batched.
* Normal mapping angles are now hopefully fixed, although regressions are expected. I have merged PR #41323 into the batching.
* Projects with lights, you may get a slowdown due to fill rate. Be sure to try the `batching/light_scissoring` option.
* Batching settings are the same as for GLES2.
* Speed may not be optimal yet, at first I will be trying to fix any visual regressions.
* If you get decreased speed with batching, this is highly likely to be because batching defaults to `single_rect_fallback` to false. This is the old method of drawing quads which is about 2x as fast, but causes flicker on nvidia drivers. To directly compare the performance of both you would need to turn this back on.

## New features
This isn't just a straight port of the feature set of GLES2 batching, I am now adding new features, which will be available in GLES2 and GLES3.

* Light angles - for correct normal mapping angles and flips - DONE
* Large vertex format - for accelerating more custom shaders - DONE - needs testing - build 0.13
* More primitives - Ninepatch rects, lines, polys DONE
* Software skinning path for 2d polys - DONE
_(software skinning is switchable in projectsettings->rendering->quality->2d)_
* Switchable ninepatch margin scaling method - DONE (except GLES3 legacy)
_(switchable in projectsettings->rendering->quality->2d)_

## Please read for more info
https://docs.godotengine.org/en/3.2/tutorials/optimization/batching.html#doc-batching
https://docs.godotengine.org/en/3.2/tutorials/optimization/batching.html#frequently-asked-questions

## Builds
In progress builds for linux / windows. I'll try and update these as I go.
Please post any feedback regarding regressions, performance gains (or not) etc, with the build version you tried.

To find regressions, run while turning on `flash_batching` in project settings. The batching settings are exactly the same as GLES2. To test performance, turn off vsync, and choose to `debug/settings/stdout/print_fps` and run with batching switched off, then on.

* 0.16 Fixed software skinning, ninepatch options
* 0.15 Batching polys and software skinning path for polys
* 0.14 Batching ninepatch rects and lines (single pixel width only)
* 0.13 New vertex formats for accelerating custom shaders - highly likely to have bugs
* 0.12 Light angles for normal mapping
* 0.11 batching with items as well as commands - more likely to have regressions
* 0.10 First version - batching with commands only

https://github.com/lawnjelly/Misc/releases

### CODE REVIEW

**Comment by lawnjelly** [comment]
@clayjohn I've changed this from draft to ready for review.

There's probably quite a few things I've missed as far as naming etc but I'm keen for us to get this in as soon as possible, even if more work is expected. This is partly so we can get testing asap (as Akien said he is building 3.2.4 betas soon) but also because this is such a major change that it involves substantial work to manually rebase every time any other PR is added to the rendering.

Some things of note:
* The common template to do the batching is quite large. For this reason and to prevent it becoming unwieldy I have split it into several `inc` files which are included from the main header. This is a trade off. It makes it super easy to navigate and find areas of the template concerned with different topics. On the other hand it breaks a lot of intellisense which is a pain.

I am open to moving them all into the same header, or a single hander and single inc, and separating the implementations and definitions if that is preferable. Or alternatively we could do such changes later if we thought it would work better in the long run.

* There's a really tricky bug in the joining I haven't figured out yet which is meaning the first in a series of items often isn't getting joined. This doesn't result in visual errors, but it would be nice to fix because it could potentially lead to better performance.
* I finally got around to solving the 'dummy' batches at the start of runs. This probably doesn't make that much difference but makes debugging and diagnostics easier.

**Comment by clayjohn** [comment]
I've quickly reviewed the easy stuff, but Im gonna need a few more days to get through the difficult parts. So far it looks pretty good. Personally, I really like have things split across many files (even though some of those files are only 20 lines long). However, I know reduz really prefers long files that include all the needed functionality, so he will have to weigh in here. Either way it won't be too bad as most of those ``.inc`` files could be joined together without harming readability too much.

I'll let you know when I have a chance to do a more substantive review. The overall structure looks pretty similar to GLES2 batching, but I haven't really dug into how you are batching the other primitive types. So we'll see.

**Comment by lawnjelly** [comment]
For batching the other types, the main conceptual change is that for the buffers, the start vertex and number of vertices (or commands) is stored in terms of vertex rather than quad (group of 4 verts) in the old version. This is because lines use 2 verts each, and polys can use a variable number of verts per poly.

What simplifies it considerably is that only similar primitives can be joined together at the moment. E.g. a group of rects are joined, and rendered as a group of rects. Poly group all polys etc.

This is something I'm meaning to improve later (probably after 3.2.4) so multiple types can be included in the same vertex buffer before a flush, it requires an extra layer of logic on top, but should result in a lot less VB uploads and probably better performance.

## Ninepatches
Ninepatches are very simple, in that they are just translated into 9 rects and drawn as rects. In the version you have it only supports the GLES2 method, stretch mode, but I've been starting to look into whether it is possible to support the tiling modes as in GLES3. This seems to be a whole can o' worms, not in terms of technical difficulty, but in terms of agreement about how ninepatches should work.

I've opened up a new proposal to discuss this, so this PR doesn't become too off topic with what is really a side issue:
https://github.com/godotengine/godot-proposals/issues/1618

**Comment by lawnjelly** [comment]
As mentioned in the linked proposal, in unified batching path, ninepatch scaling mode is now selectable between a default old style (pixel perfect) and puthre's scaling version. These only support the stretch mode.

In GLES3 if the tile mode is switched on, or batching is off, it uses the shader path. To keep the shader simple, based on agreement it is reverted to the old style (it is kind of messy to support both in the shader). This does have the consequence that if you are using tiling in GLES3, only old style pixel perfect scaling is available. Based on feedback this seems the more popular version.

**Comment by avencherus** [comment]
Ran some quick tests this morning comparing results using the benchmark project from:  https://github.com/godotengine/godot/issues/19943

[polygon2d_performance.zip](https://github.com/godotengine/godot/files/5362925/polygon2d_performance.zip)

Mostly gains for the Poly2D, but there was some regression in performance for Sprites in GLES3.

image


**Source screenshots of the project tests:**

### Old Version

**GLES2 Sprite Tests**
GLES2-s1-a
GLES2-s2-a
GLES2-s3-a

**GLES3 Sprite Tests**
GLES3-s1-a
GLES3-s2-a
GLES3-s3-a

**GLES2 Poly Tests**
GLES2-p1-a
GLES2-p2-a
GLES2-p3-a

**GLES3 Poly Tests**
GLES3-p1-a
GLES3-p2-a
GLES3-p3-a


### New Version

**GLES2 Sprite Tests**
GLES2-s1-b
GLES2-s2-b
GLES2-s3-b

**GLES3 Sprite Tests**
GLES3-s1-b
GLES3-s2-b
GLES3-s3-b

**GLES2 Poly Tests**
GLES2-p1-b
GLES2-p2-b
GLES2-p3-b

**GLES3 Poly Tests**
GLES3-p1-b
GLES3-p2-b
GLES3-p3-b

**Comment by lawnjelly** [comment]
That all looks good. The drop in sprite performance depending on your test is expected .. as with the GLES2 batching the default single rect draw method is now equivalent to nvidia workaround, which is slower, but free of flicker artifacts.

If you want to directly compare sprite performance, you should set `project_settings->rendering->batching->options->single_rect_fallback` to true.

This has been a source of confusion in the past. I did actually change this default temporarily for some of the test builds, but when we integrate in 3.2 the default will be the same as in GLES2 (as it uses the same setting).

We really are trying to discourage people from using the old faster single rect method. The reason is, that while it may look great on your machine, a significant portion of your users may see flicker, and uninstall your game / give bad reviews.

**Comment by lawnjelly** [comment]
Now rebased with the buffer orphaning.

I've also tidied up `canvas_batcher` a little bit, moved the implementations of most of the functions outside the template class so the declarations are easier to navigate. It is still a bit unwieldy to my eyes having so much in a monolithic class, but the templated nature makes it a little more difficult to split apart unless we use multiple templates, and the boiler plate could get excessive.

On boiler plate I've used macros to reduce this.

I've also changed a couple of the function names to slightly more sensible versions, let me know any more suggestions for renaming.

**Comment by clayjohn** [comment]
Thanks for keeping it updated! I swear I will find time to review it soon. I've already read through all the code bits at a time, I just need to dedicate a chunk of time to do a more careful review of the substance.

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 1]
```diff
@@ -45,304 +45,160 @@ static const GLenum gl_primitive[] = {
...
+	storage->info.render._2d_draw_call_count++;
 
-	// VERY IMPORTANT to return where we got to, because this func may be called multiple
-	// times per item.
-	// Don't miss out on this step by calling return earlier in the function without setting r_command_start.
-	r_command_start = command_num;
+	// could these have ifs?
+	glDisableVertexAttribArray(VS::ARRAY_TEX_UV);
+	glDisableVertexAttribArray(VS::ARRAY_COLOR);
+	//	glDisableVertexAttribArray(VS::ARRAY_TANGENT);
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_canvas_gles2.cpp:194]: cleanup

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 2]
```diff
@@ -45,304 +45,160 @@ static const GLenum gl_primitive[] = {
...
+	glVertexAttribPointer(VS::ARRAY_TEX_UV, 2, GL_FLOAT, GL_FALSE, sizeof_vert, CAST_INT_TO_UCHAR_PTR(pointer + (2 * 4)));
 
-				Item::CommandRect *rect = static_cast<Item::CommandRect *>(command);
+	//	glDisableVertexAttribArray(VS::ARRAY_COLOR);
+	//	glVertexAttrib4fv(VS::ARRAY_COLOR, (float *) &p_batch.color);
 
-				// unoptimized - could this be done once per batch / batch texture?
-				bool send_light_angles = rect->normal_map != RID();
+	// color
+	//	if (!colored_verts) {
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_canvas_gles2.cpp:174]: cleanup

File: drivers/gles3/rasterizer_canvas_gles3.h [hunk 3]
```diff
@@ -28,136 +28,50 @@
 /* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                */
 /*************************************************************************/
 
-#ifndef RASTERIZERCANVASGLES3_H
-#define RASTERIZERCANVASGLES3_H
+#pragma once
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_canvas_gles3.h:31]: @akien-mga are we starting to use #pragma once now?

**Review by clayjohn — CHANGES_REQUESTED** [review]
I've gone through he whole thing, given the length of the PR, I can't say I spent a significant amount of time on each line of code. So I will mostly make general comments here:

1. I like the overall structure of the implementation. It is a nice logical step up from the previous batching implementation. 

2. The ``PREAMBLE`` macro was a great way to simplify the templates.

3. There is a lot of commented out code that has been left in throughout, I stopped commenting on them part way through. Before merging we will have to do a full read-through and make sure that we get read of the dead code.

Overall, great work! I am amazed at the size and complexity of this PR.

With just a little bit of code cleanup I think this will be ready for a testing build, we should do something similar to when we first added batching. @akien-mga can we get you to help put together another test batching build so we can get this into the hands of as many users as possible?

File: drivers/gles2/rasterizer_canvas_gles2.cpp [hunk 4]
```diff
@@ -45,304 +45,160 @@ static const GLenum gl_primitive[] = {
...
+	if (!bdata.vertices.size())
+		return;
 
-RasterizerStorageGLES2::Texture *RasterizerCanvasGLES2::_get_canvas_texture(const RID &p_texture) const {
-	if (p_texture.is_valid()) {
+	glBindBuffer(GL_ARRAY_BUFFER, bdata.gl_vertex_buffer);
 
-		RasterizerStorageGLES2::Texture *texture = storage->texture_owner.getornull(p_texture);
+	// orphan the old (for now)
+	//glBufferData(GL_ARRAY_BUFFER, 0, 0, GL_DYNAMIC_DRAW);
```
[the remark this answers is not in the document]
Comment (lawnjelly) [reply drivers/gles2/rasterizer_canvas_gles2.cpp:57]: I actually changed this just yesterday, commenting out the glBufferCall. I didn't think it was necessary, and the test versions should reveal any problems (I think I had initially put it in the first batching for safety).

Every upload uses a glBufferData call rather than glSubBufferData, so will be requesting a new buffer each time. The buffer sizes are usually quite small, so at the moment this seems more appropriate than trying to maintain a large number of larger fixed sized buffers per frame. (This is same mechanism as GLES2 batching).

File: drivers/gles3/rasterizer_canvas_gles3.h (hunk 3 above)
Comment (lawnjelly) [reply drivers/gles3/rasterizer_canvas_gles3.h:31]: Ah that's probably me from initial implementation, I'll remove the #pragma once. :+1:

**Comment by lawnjelly** [comment]
I've cleaned up a number of the comments... :+1: 

Some I did miss but part of the reason for leaving others in is that we are expecting to have to tweak things as a result of the betas, and the commented code may help for changing these areas (and some are placeholders). Bear in mind we can also do a separate cleanup PR after the betas.

**Comment by lawnjelly** [comment]
Added a second commit, doing some experiments to try and lower the amount of glBufferSubData calls in the legacy renderer in the hope of helping performance on devices with poor drivers.

**Review by clayjohn — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Amazing work as usual!

Let's get this merged and tested in 3.2.4 beta 1 (hopefully sometime this week).

**Comment by akien-mga** [comment]
Thanks!

@lawnjelly Do you want to prepare an issue with some testing instructions like we had for GLES2 batching, to collect user feedback?

**Comment by lawnjelly** [comment]
Yup sure will do. :+1:

**Comment by Valeryn4** [comment]
The problem is still relevant.
The error pops up on some devices.

Version 3.3
image
image

**Comment by Calinou** [comment]
@Valeryn4 Please continue the discussion about this in https://github.com/godotengine/godot/issues/35772.

**Comment by oeleo1** [comment]
@lawnjelly Not sure where to write this quick note, so here :-) The `RasterizerCanvasGLES2/3::try_join_item()` function seems to have a useless `reclip` var and a dead code test on it later on which is probably a leftover from previous versions of the code that you may want to cleanup.
