### PR TITLE
fix crash on iOS 13 

### LINKED ISSUE #7966: Crash on exit iOS application when using iOS 13
**iPhone 5( 32bit) - Godot version: 2.1.2**

Crash on **exit application** in godot/servers/audio/audio_server_sw.cpp on line 774:

```
void AudioServerSW::_thread_func(void *self) {

	Thread::set_name("AudioServerSW");

	AudioServerSW *as=(AudioServerSW *)self;

	while (!as->exit_update_thread) {
		as->_update_streams(true);
		OS::get_singleton()->delay_usec(5000); <<--  Crash here
	}

}
```

Resume: OS::get_singleton() -- not thread save (maybe do "delay_usec" as static) and not correct finalize class.
 In my case  OS::get_singleton() === NULL.

### PR DESCRIPTION
**Pull request by ealataur**
Fix crash on iOS 13 when app go to background and back it from

*Bugsquad edit:* Fixes #7966.

### CODE REVIEW

File: platform/iphone/gl_view.mm [hunk 1]
```diff
@@ -340,6 +340,8 @@ - (void)layoutSubviews {
 	[EAGLContext setCurrentContext:context];
 	[self destroyFramebuffer];
 	[self createFramebuffer];
+	[self drawView];
+	// [self drawView];
```
Comment (akien-mga) [inline platform/iphone/gl_view.mm]: The commented out duplicate can be removed.

**Comment by akien-mga** [comment]
Could you rebase the branch to remove the unnecessary merge commit? (just `git pull --rebase upstream master` should be sufficient if you have `upstream` pointing to `godotengine/godot`). See https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by akien-mga** [comment]
Still needs a rebase to squash commits, otherwise changes seem OK if others can confirm that it fixes the bug without introducing performance regressions.

**Comment by gerald1248** [comment]
@akien-mga which benchmark should we use? I have built iphone.zip with and without the change. I'm happy to run a comparison.

I'm not 100% confident performance is the same (I get weird dropped frames sometimes, but perhaps they were an issue before and I didn't notice?) but the thing is that this addresses a bug that's pretty serious. *Every* Godot app on iOS13 crashes every time it is closed.

**Comment by akien-mga** [comment]
Pushed a rebased commit that should be fine to merge.

> which benchmark should we use? I have built iphone.zip with and without the change. I'm happy to run a comparison.

I'm not sure, but I guess the changes should be fine. The only performance-impacting change now is the reintroduction of the `[drawView]` call, which was removed in #32194 but this was likely not the right fix for the bug it tried to address (this PR looks like it might be).

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Comment by dylantmarsh** [comment]
I am experiencing this crash with 3.2 beta 5 on iOS 13.1.1

**Comment by akien-mga** [comment]
Please open a new bug report.

**Comment by pchasco** [comment]
This commit appears to correct the same issue for the 2.1.X branch.

**Comment by akien-mga** [comment]
Cherry-picked for 2.1.7.
