### PR TITLE
[Window] Fix mouse hover state of the main window when mouse enter event was sent before setting callbacks.

### LINKED ISSUE #91589: Editor window doesn't receive some mouse events when it's first launched
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When the editor is first launched:

- None of the buttons show their hover state (left clicking them works though)
- Right clicking dock tabs does nothing (but right clicking some other things, like a folder in the FileSystem dock works)

To fix this I have to alt tab into another app and alt tab back, then it goes back to normal

https://github.com/godotengine/godot/assets/60579014/e8a3a1d0-34c5-4482-9476-daccfeddd3a7

There's issue https://github.com/godotengine/godot/issues/86904 that sounds similar to this, except:

- This only happens on the first editor launch for me before the first alt tab. When I alt tab and go back the issue is gone
- Unlike that issue, the editor doesn't require an extra click for buttons to become clickable. Only their hover states don't work. And a click doesn't fix the hover situation, only alt tabbing does

### Steps to reproduce

Run the editor and see that moving cursor over buttons doesn't have any effect

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Main window is shown before event callbacks for `Window` are set, and OS mouse-enter event might arrive before it and get lost.

Fixes https://github.com/godotengine/godot/issues/91589

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: scene/main/window.cpp [hunk 1]
```diff
@@ -1354,6 +1354,10 @@ void Window::_notification(int p_what) {
 					_update_window_size(); // Inform DisplayServer of minimum and maximum size.
 					_update_viewport_size(); // Then feed back to the viewport.
 					_update_window_callbacks();
+					// Simulate mouse-enter event when mouse is over the window, since OS event might arrive before setting callbacks.
+					if (Rect2(position, size).has_point(DisplayServer::get_singleton()->mouse_get_position()) && !mouse_in_window) {
```
Comment (AThousandShips) [inline scene/main/window.cpp:1358]:
```suggestion
					if (!mouse_in_window && Rect2(position, size).has_point(DisplayServer::get_singleton()->mouse_get_position())) {
```
Cheaper check first

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
