### PR TITLE
Close shader in Shader Editor tab when deleting shader file in FileSystem panel

### LINKED ISSUE #72595: Deleting Shader file in FileSystem panel leaves shader file open for editing in Shader Editor tab
### Godot version

4.0b17

### System information

macOS 13.2

### Issue description

If you have a shader resource open in the Shader Editor (Visual shader like below or regular code-based Shader) and then delete this shader file from the FileSystem panel, the Shader editor is not updated. I would expect the shader editor to close the file (perhaps with a warning) and update the file list. 

If you then save the project the name of the file in the Shader Editor changes to [unsaved]. However, it does not prompt you if you wish to save this open unsaved file if you close it or the project, so it feels like a ghost file of sorts instead of reverting the file to an unsaved new file state (as perhaps intended?). 
If you try to save again you instead get an error in the output `Can't save resource to empty path. Provide non-empty path or a Resource with non-empty resource_path.`

https://user-images.githubusercontent.com/17763524/216334632-84fd19da-cd13-442f-98a8-d96a07386f30.mov

There also seems to be a similar issue with the Theme editor tab. Where it will stay open even if the resource you're editing has been deleted. 

### Steps to reproduce

- Open a shader resource in the Shader Editor tab
- Delete the Shader file from the FileSystem panel
- Observe that nothings seems to have happened in the Shader Editor
- Save the project and see the Shader editor filename change to [unsaved] but not prompting to be saved on close

### Minimal reproduction project

This is an editor UI issue so I think any project will be the same.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #72595

It works as the same with built-in script editor, when you delete the file in the filesystem panel, the editor should close the relating tab.

### CODE REVIEW

**Review by SaracenOne — APPROVED** [review]
LGTM

File: editor/plugins/shader_editor_plugin.h [hunk 1]
```diff
@@ -87,6 +87,7 @@ class ShaderEditorPlugin : public EditorPlugin {
 	void _resource_saved(Object *obj);
 	void _close_shader(int p_index);
 	void _close_builtin_shaders_from_scene(const String &p_scene);
+	void _file_removed(const String &p_file);
```
[the remark this answers is not in the document]
Comment (jsjtxietian) [reply editor/plugins/shader_editor_plugin.h:90]: Thanks!

File: editor/plugins/shader_editor_plugin.cpp [hunk 2]
```diff
@@ -571,10 +576,20 @@ void ShaderEditorPlugin::_window_changed(bool p_visible) {
 	make_floating->set_visible(!p_visible);
 }
 
+void ShaderEditorPlugin::_file_removed(const String &p_removed_file) {
+	for (uint32_t i = 0; i < edited_shaders.size(); i++) {
+		Ref<Shader> &shader = edited_shaders[i].shader;
+		if (shader->get_meta("_edit_res_path") == p_removed_file) {
```
Comment (KoBeWi) [inline editor/plugins/shader_editor_plugin.cpp:582]:
```suggestion
		if (shader->get_path() == p_removed_file) {
```
Resources already know their path.

File: editor/plugins/shader_editor_plugin.cpp [hunk 3]
```diff
@@ -571,10 +576,20 @@ void ShaderEditorPlugin::_window_changed(bool p_visible) {
 	make_floating->set_visible(!p_visible);
 }
 
+void ShaderEditorPlugin::_file_removed(const String &p_removed_file) {
+	for (uint32_t i = 0; i < edited_shaders.size(); i++) {
+		Ref<Shader> &shader = edited_shaders[i].shader;
```
Comment (KoBeWi) [inline editor/plugins/shader_editor_plugin.cpp:581]:
```suggestion
		const Ref<Shader> &shader = edited_shaders[i].shader;
```

File: editor/plugins/shader_editor_plugin.cpp (hunk 2 above)
Comment (jsjtxietian) [reply editor/plugins/shader_editor_plugin.cpp:582]: That path is empty because it's already cleared when delete the file in filesystem panel. 
Thus I have to set the meta in `_update_shader_list`, and use the meta to decide which file to close.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
I just discovered that `set_meta()` is used wrongly here. It gets attached to shaders and saved in the file, which shouldn't be happening.
