### PR TITLE
Fix crash when parsing invalid datetime string

### LINKED ISSUE #60189: Crash when parsing invalid datetime string
### Godot version

3.x (8f4f384) master (788f355)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

Godot crashes if invalid datetime strings like `2022-01T03:04` is given to `Time.get_unix_time_from_datetime_string()`.

<details><summary>Backtrace</summary>

```
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v3.5.beta.custom_build (7efe2380691bdba3a55188b91671eb1f3fa08458)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] bin/godot.x11.tools.64s() [0x187511a] (/home/timothy/repos/godot-3.x/platform/x11/crash_handler_x11.cpp:55)
[2] /usr/lib/libc.so.6(+0x42560) [0x7f5dad222560] (??:0)
[3] CowData<int>::get(int) const (/home/timothy/repos/godot-3.x/./core/cowdata.h:156 (discriminator 7))
[4] Vector<int>::operator[](int) const (/home/timothy/repos/godot-3.x/./core/vector.h:87)
[5] Time::get_unix_time_from_datetime_string(String) const (/home/timothy/repos/godot-3.x/core/os/time.cpp:295 (discriminator 53))
[6] MethodBind1RC<long, String>::call(Object*, Variant const**, int, Variant::CallError&) (/home/timothy/repos/godot-3.x/./core/method_bind.gen.inc:1305 (discriminator 8))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/timothy/repos/godot-3.x/core/object.cpp:918 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/timothy/repos/godot-3.x/core/variant_call.cpp:1185 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/timothy/repos/godot-3.x/modules/gdscript/gdscript_function.cpp:1053)
[10] GDScript::_create_instance(Variant const**, int, Object*, bool, Variant::CallError&) (/home/timothy/repos/godot-3.x/modules/gdscript/gdscript.cpp:113)
[11] GDScript::instance_create(Object*) (/home/timothy/repos/godot-3.x/modules/gdscript/gdscript.cpp:317)
[12] Object::set_script(RefPtr const&) (/home/timothy/repos/godot-3.x/core/object.cpp:1018)
[13] MainLoop::init() (/home/timothy/repos/godot-3.x/core/os/main_loop.cpp:95 (discriminator 2))
[14] SceneTree::init() (/home/timothy/repos/godot-3.x/scene/main/scene_tree.cpp:497)
[15] OS_X11::run() (/home/timothy/repos/godot-3.x/platform/x11/os_x11.cpp:3837)
[16] bin/godot.x11.tools.64s(main+0x1f6) [0x1870b1c] (/home/timothy/repos/godot-3.x/platform/x11/godot_x11.cpp:57)
[17] /usr/lib/libc.so.6(+0x2d310) [0x7f5dad20d310] (??:0)
[18] /usr/lib/libc.so.6(__libc_start_main+0x81) [0x7f5dad20d3c1] (??:0)
[19] bin/godot.x11.tools.64s(_start+0x25) [0x1870865] (??:?)
-- END OF BACKTRACE --

```
</details>

And `Time.get_datetime_dict_from_string()` overruns the global buffer when the month is invalid (e.g. 99).

<details><summary>Backtrace</summary>

```
==330188==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00000b2cc3f8 at pc 0x000009062565 bp 0x7ffcb893e5e0 sp 0x7ffcb893e5d0
READ of size 1 at 0x00000b2cc3f8 thread T0
    #0 0x9062564 in Time::get_datetime_dict_from_string(String, bool) const core/os/time.cpp:262
    #1 0x907ff8b in MethodBind2RC<Dictionary, String, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/timothy/repos/godot-3.x/bin/godot.x11.tools.64s+0x907ff8b)
    #2 0x8d39c64 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #3 0x8ea59f1 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #4 0x1b7d6d6 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1050
    #5 0x1a9773d in GDScript::_create_instance(Variant const**, int, Object*, bool, Variant::CallError&) modules/gdscript/gdscript.cpp:113
    #6 0x1a9a9d3 in GDScript::instance_create(Object*) modules/gdscript/gdscript.cpp:317
    #7 0x8d3b22b in Object::set_script(RefPtr const&) core/object.cpp:1018
    #8 0x904a8eb in MainLoop::init() core/os/main_loop.cpp:95
    #9 0x6669763 in SceneTree::init() scene/main/scene_tree.cpp:496
    #10 0x18a6fca in OS_X11::run() platform/x11/os_x11.cpp:3830
    #11 0x1870b1b in main platform/x11/godot_x11.cpp:55
    #12 0x7f74ae88430f in __libc_start_call_main (/usr/lib/libc.so.6+0x2d30f)
    #13 0x7f74ae8843c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0)
    #14 0x1870864 in _start (/home/timothy/repos/godot-3.x/bin/godot.x11.tools.64s+0x1870864)

0x00000b2cc3f8 is located 0 bytes to the right of global variable 'MONTH_DAYS_TABLE' defined in 'core/os/time.cpp:50:22' (0xb2cc3e0) of size 24
SUMMARY: AddressSanitizer: global-buffer-overflow core/os/time.cpp:262 in Time::get_datetime_dict_from_string(String, bool) const
Shadow bytes around the buggy address:
  0x000081651820: f9 f9 f9 f9 00 00 00 00 07 f9 f9 f9 f9 f9 f9 f9
  0x000081651830: 00 00 00 00 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
  0x000081651840: 00 00 00 00 00 00 00 00 00 00 00 03 f9 f9 f9 f9
  0x000081651850: 00 00 05 f9 f9 f9 f9 f9 00 00 02 f9 f9 f9 f9 f9
  0x000081651860: 05 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
=>0x000081651870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00[f9]
  0x000081651880: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x000081651890: 00 04 f9 f9 f9 f9 f9 f9 02 f9 f9 f9 f9 f9 f9 f9
  0x0000816518a0: 03 f9 f9 f9 f9 f9 f9 f9 00 06 f9 f9 f9 f9 f9 f9
  0x0000816518b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000816518c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==330188==ABORTING
```

</details>

### Steps to reproduce

Run the script below with `-s`.

### Minimal reproduction project

```gdscript
extends SceneTree

func _init():
	print("===== Start =====")

	Time.get_unix_time_from_datetime_string("2022-01T03:04")
	Time.get_datetime_dict_from_string("2022-99-02T03:04:05", true)

	print("====== End ======")
	quit()
```

### PR DESCRIPTION
**Pull request by rohanrhu**
Fixes #60189

Meow.. this quick fix works and avoids crashes.

### CODE REVIEW

File: core/os/time.cpp [hunk 1]
```diff
@@ -137,11 +137,15 @@ VARIANT_ENUM_CAST(Time::Weekday);
 		if (p_datetime.find_char('T') > 0) {                      \
 			has_date = has_time = true;                           \
 			PackedStringArray array = p_datetime.split("T");      \
+			if (array.size() < 2)                                 \
+				return iso8601_fmt_err_val;                       \
```
Comment (bruvzg) [inline core/os/time.cpp:141]: I guess it should print at error message, like other functions do:

```suggestion
			ERR_FAIL_COND_V_MSG(array.size() < 2, err_val, "Invalid ISO-8601 date/time string"); \
```

I would also move the error return value to the macro argument, see #60203 changes for example.

**Comment by rohanrhu** [comment]
Hiiii @bruvzg changed checks to `ERR_FAIL_COND_V_MSG()` and passed `err_val` as macro parameter.

**Review by bruvzg — APPROVED** [review]

File: core/os/time.cpp [hunk 2]
```diff
@@ -124,50 +124,54 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
-				year *= -1;                                       \
-			}                                                     \
-		}                                                         \
-		if (has_time) {                                           \
-			PackedInt32Array array = time.split_ints(":", false); \
-			hour = array[0];                                      \
-			minute = array[1];                                    \
-			second = array[2];                                    \
-		}                                                         \
+#define PARSE_ISO8601_STRING(err_val)                                                            \
```
Comment (aaronfranke) [inline core/os/time.cpp:127]: A bit of an inconsistent style with #60203 which uses `ret` as the argument name.

File: core/os/time.cpp [hunk 3]
```diff
@@ -124,50 +124,54 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
+		if (p_datetime.find_char('T') > 0) {                                                     \
+			has_date = has_time = true;                                                          \
+			PackedStringArray array = p_datetime.split("T");                                     \
+			ERR_FAIL_COND_V_MSG(array.size() < 2, err_val, "Invalid ISO-8601 date/time string"); \
+			date = array[0];                                                                     \
+			time = array[1];                                                                     \
+		} else if (p_datetime.find_char(' ') > 0) {                                              \
+			has_date = has_time = true;                                                          \
+			PackedStringArray array = p_datetime.split(" ");                                     \
+			ERR_FAIL_COND_V_MSG(array.size() < 2, err_val, "Invalid ISO-8601 date/time string"); \
```
Comment (aaronfranke) [inline core/os/time.cpp:146]:
```suggestion
			ERR_FAIL_COND_V_MSG(array.size() < 2, err_val, "Invalid ISO 8601 date/time string"); \
```

**Review by aaronfranke — CHANGES_REQUESTED** [review]
This will conflict with #60201.

File: core/os/time.cpp (hunk 3 above)
Comment (rohanrhu) [reply core/os/time.cpp]: Oh.. I thought you mean they should be all with `-` or not. I set them to `ISO 8601`.

File: core/os/time.cpp [hunk 4]
```diff
@@ -293,7 +297,7 @@ int64_t Time::get_unix_time_from_datetime_dict(const Dictionary p_datetime) cons
 }
 
 int64_t Time::get_unix_time_from_datetime_string(String p_datetime) const {
-	PARSE_ISO8601_STRING
+	PARSE_ISO8601_STRING(-1)
 	VALIDATE_YMDHMS(0)
```
Comment (aaronfranke) [inline core/os/time.cpp:301]: With this code:
* If the string parsing fails due to an incorrect number of elements, it will return -1
* If one of the values in each element is invalid, it will return 0

It may be useful to have different return values for these cases. I'm not sure which behavior is desired, but I think this is good.

**Review by aaronfranke — APPROVED** [review]
For easy reviewing, here's a commit with only the non-whitespace changes: https://github.com/aaronfranke/godot/commit/32a7226bf1506d798ae63f55dbbea1a706f1f9ae

(don't change your PR, it's good as it is, this is just to help reviewers review quickly)

File: core/os/time.cpp [hunk 5]
```diff
@@ -124,50 +124,54 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
+			has_date = true;                                                                 \
+			date = p_datetime;                                                               \
+		} else if (p_datetime.find_char(':') > 0) {                                          \
+			has_time = true;                                                                 \
+			time = p_datetime;                                                               \
+		}                                                                                    \
+		/* Set the variables from the contents of the string. */                             \
+		if (has_date) {                                                                      \
+			PackedInt32Array array = date.split_ints("-", false);                            \
+			ERR_FAIL_COND_V_MSG(array.size() < 3, ret, "Invalid ISO 8601 date/time string"); \
```
Comment (aaronfranke) [inline core/os/time.cpp:159]:
```suggestion
			ERR_FAIL_COND_V_MSG(array.size() < 3, ret, "Invalid ISO 8601 date string."); \
```

File: core/os/time.cpp [hunk 6]
```diff
@@ -124,50 +124,54 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
+			month = (Month)array[1];                                                         \
+			day = array[2];                                                                  \
+			/* Handle negative years. */                                                     \
+			if (p_datetime.find_char('-') == 0) {                                            \
+				year *= -1;                                                                  \
+			}                                                                                \
+		}                                                                                    \
+		if (has_time) {                                                                      \
+			PackedInt32Array array = time.split_ints(":", false);                            \
+			ERR_FAIL_COND_V_MSG(array.size() < 3, ret, "Invalid ISO 8601 date/time string"); \
```
Comment (aaronfranke) [inline core/os/time.cpp:170]:
```suggestion
			ERR_FAIL_COND_V_MSG(array.size() < 3, ret, "Invalid ISO 8601 time string."); \
```

**Review by aaronfranke — COMMENTED** [review]
Actually, these messages can be improved a bit more (and add periods to the other two):

**Comment by akien-mga** [comment]
> For easy reviewing, here's a commit with only the non-whitespace changes: [aaronfranke@32a7226](https://github.com/aaronfranke/godot/commit/32a7226bf1506d798ae63f55dbbea1a706f1f9ae)

FYI, you didn't need to do this manually, GitHub has an option to ignore whitespace changes in the diff view:
https://github.com/godotengine/godot/pull/60215/files?w=1

File: core/os/time.cpp [hunk 7]
```diff
@@ -124,50 +124,54 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
+		if (p_datetime.find_char('T') > 0) {                                                 \
+			has_date = has_time = true;                                                      \
+			PackedStringArray array = p_datetime.split("T");                                 \
+			ERR_FAIL_COND_V_MSG(array.size() < 2, ret, "Invalid ISO 8601 date/time string"); \
+			date = array[0];                                                                 \
+			time = array[1];                                                                 \
+		} else if (p_datetime.find_char(' ') > 0) {                                          \
+			has_date = has_time = true;                                                      \
+			PackedStringArray array = p_datetime.split(" ");                                 \
+			ERR_FAIL_COND_V_MSG(array.size() < 2, ret, "Invalid ISO 8601 date/time string"); \
```
Comment (aaronfranke) [inline core/os/time.cpp:146]:
```suggestion
			ERR_FAIL_COND_V_MSG(array.size() < 2, ret, "Invalid ISO 8601 date/time string."); \
```

File: core/os/time.cpp [hunk 8]
```diff
@@ -124,50 +124,54 @@ VARIANT_ENUM_CAST(Time::Weekday);
...
+	uint8_t hour = 0;                                                                        \
+	uint8_t minute = 0;                                                                      \
+	uint8_t second = 0;                                                                      \
+	{                                                                                        \
+		bool has_date = false, has_time = false;                                             \
+		String date, time;                                                                   \
+		if (p_datetime.find_char('T') > 0) {                                                 \
+			has_date = has_time = true;                                                      \
+			PackedStringArray array = p_datetime.split("T");                                 \
+			ERR_FAIL_COND_V_MSG(array.size() < 2, ret, "Invalid ISO 8601 date/time string"); \
```
Comment (aaronfranke) [inline core/os/time.cpp:140]:
```suggestion
			ERR_FAIL_COND_V_MSG(array.size() < 2, ret, "Invalid ISO 8601 date/time string."); \
```

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
