### PR TITLE
Fix `Camera2D` right and bottom limit to depend on bottom right corner

### LINKED ISSUE #105775: Camera2D ignores rotation pivot on small limits, even if there's enough room for it to rotate.
### Tested versions

- Reproducible in Godot v4.4.1.stable.official [49a5bc7b6]

### System information

Windows 10, Godot v4.4.1.stable.official [49a5bc7b6]

### Issue description

Issue is pretty self descriptive, setting any camera's limits to values that totals a size too close to the window size messes up the rotation

https://github.com/user-attachments/assets/23a02e71-b163-475e-99bb-4f611c96c280

### Steps to reproduce

- Works on any project but it happens on brand new ones as well
- Also happens independently of the parent or children of the camera
- Add a Camera2D node to the node tree
- In the inspector, set "Ignore Rotation" to false
- Set the camera limits to a value that totals around 200-500 more than the widest dimension of your window size in the Project Settings (example: if your window size is 1152x648, set the camera limits to around 600 pixels towards all directions)
- Inside the "Editor" tab of the camera in the inspector, turn on "Draw Limits"
- on "Transform", rotate either the camera itself or any node higher in the hierarchy and watch as the camera completely ignores the rotation pivot, even if it has enough room to rotate normally

### Minimal reproduction project (MRP)

[is_this_a_bug_2025-04-25_22-05-39.zip](https://github.com/user-attachments/files/19918460/is_this_a_bug_2025-04-25_22-05-39.zip)

### PR DESCRIPTION
**Pull request by Alex-Onceanu**
Fixed #105775 

Before : "Right" and "Bottom" limits for Camera2D clamped camera's position based on top-left corner of screen rect plus a certain constant. This meant that when the camera was rotated, the limits weren't computed properly since the offset was constant, which meant the limits used to behave weird.

Now : for "Right" and "Bottom" limits, clamp the position of camera based on the bottom-right corner of the camera, just as it is with "Top" and "Left" limits with the top-left corner. Now, even when the camera is rotated the limits behave properly.

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -270,18 +270,20 @@ Transform2D Camera2D::get_camera_transform() {
 	}
 
 	Rect2 screen_rect(-screen_offset + ret_camera_pos, screen_size * zoom_scale);
-
+	
 	if (limit_enabled && (!position_smoothing_enabled || !limit_smoothing_enabled)) {
+		Point2 bottomRightCorner = Point2(screen_rect.position + 2.0 * (camera_pos - screen_rect.position));
```
Comment (KoBeWi) [inline scene/2d/camera_2d.cpp:275]:
```suggestion
		const Point2 bottom_right_corner = Point2(screen_rect.position + 2.0 * (camera_pos - screen_rect.position));
```

**Review by KoBeWi — APPROVED** [review]
Fixes the issue, no obvious regressions.

File: scene/2d/camera_2d.cpp [hunk 2]
```diff
@@ -270,18 +270,20 @@ Transform2D Camera2D::get_camera_transform() {
 	}
 
 	Rect2 screen_rect(-screen_offset + ret_camera_pos, screen_size * zoom_scale);
-
+
```
Comment (akien-mga) [inline scene/2d/camera_2d.cpp:273]: There's an unnecessary tab here to remove.

**Comment by akien-mga** [comment]
I squashed the commits and addressed the style issues.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by Alex-Onceanu** [comment]
Thank you! 😊

**Comment by ogapo** [comment]
I think this commit may have missed the case on line 221. 
`if (limit_enabled && limit_smoothing_enabled) {`

It seems like the limits are implemented twice (once when smoothing is enabled and once when it isn't) but this commit only touches one of them. Pardon me if I'm off base, I don't really understand this change fully.
