### PR TITLE
Fix clamping logic in `EditorSpinSlider`

### LINKED ISSUE #81272: Bug? EditorSpinSlider: Change input via ´down´ or ´up´ arrow key
### Godot version

v4.1.1.stable.official [bd6af8e0e] and v4.2.dev4.official [549fcce5f]

### System information

macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

If the input is set to -1 and you want to change the value back to 0 by pressing the arrow key up, the value is increased by 0.001 only. This looks like a rounding error (see video below).  In version 3.5.2 it was still ok.

### Steps to reproduce

1. create `Node2D`
2. Inspector -> Transform -> x - Position
3. enter `-1`
4. press the arrow keys `up` several times, then `down` again.

https://github.com/godotengine/godot/assets/41921395/2ff82b7f-b24d-4039-88b3-30328258791d

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Alex2782**
... when arrow keys are pressed `up` or `down`.

Fixes #81272

I have only tried `Inspertor`, I am not sure if the old changes are necessary for something else.
The old version changed the values by 0.001 from time to time.

https://github.com/godotengine/godot/assets/41921395/65962971-c3b8-4374-b03b-9dc596c4bcf3

### CODE REVIEW

File: editor/gui/editor_spin_slider.cpp [hunk 1]
```diff
@@ -221,30 +220,23 @@ void EditorSpinSlider::_value_input_gui_input(const Ref<InputEvent> &p_event) {
 		}
 
 		Key code = k->get_keycode();
+
 		switch (code) {
-			case Key::UP: {
+			case Key::UP:
+			case Key::DOWN:
+			{
```
Comment (AThousandShips) [inline editor/gui/editor_spin_slider.cpp:227]:
```suggestion
			case Key::DOWN: {
```

File: editor/gui/editor_spin_slider.cpp [hunk 2]
```diff
@@ -221,30 +220,23 @@ void EditorSpinSlider::_value_input_gui_input(const Ref<InputEvent> &p_event) {
...
-				_evaluate_input_text();
-
-				double last_value = get_value();
-				set_value(last_value - step);
+				set_value(last_value + step);
 				double new_value = get_value();
-
-				if (new_value > CLAMP(last_value - step, get_min(), get_max())) {
-					set_value(last_value - real_step);
+
```
Comment (AThousandShips) [inline editor/gui/editor_spin_slider.cpp:236]:
```suggestion

```

File: editor/gui/editor_spin_slider.cpp [hunk 3]
```diff
@@ -221,30 +220,23 @@ void EditorSpinSlider::_value_input_gui_input(const Ref<InputEvent> &p_event) {
...
-
-				double last_value = get_value();
-				set_value(last_value - step);
+				set_value(last_value + step);
 				double new_value = get_value();
-
-				if (new_value > CLAMP(last_value - step, get_min(), get_max())) {
-					set_value(last_value - real_step);
+				
+				double clamp_value = CLAMP(new_value, get_min(), get_max());
```
Comment (AThousandShips) [inline editor/gui/editor_spin_slider.cpp:237]:
```suggestion

				double clamp_value = CLAMP(new_value, get_min(), get_max());
```

File: editor/gui/editor_spin_slider.cpp [hunk 4]
```diff
@@ -221,30 +220,23 @@ void EditorSpinSlider::_value_input_gui_input(const Ref<InputEvent> &p_event) {
...
+				if (new_value < clamp_value || new_value > clamp_value) {
```
Comment (AThousandShips) [inline editor/gui/editor_spin_slider.cpp:238]: This is just `new_value != clamp_value` isn't it?

Comment (Alex2782) [reply editor/gui/editor_spin_slider.cpp]: yes that's better, I checked, `set_value` is only executed when limits are reached.

**Comment by MewPurPur** [comment]
I already did this in #80551.

**Comment by Alex2782** [comment]
ok, I would also like to catch `mouse wheel` events. e.g. `Ctrl + up/down` does not work under MacOS, already assigned with the system function `Show all windows of the front app`. But mainly to increase the usability, if it is possible directly when the mouse is over the input field, without 'input focus'.

Should I wait until 'merge' has been executed? #80551

**Comment by MewPurPur** [comment]
Would suggest against it. Would lead to a lot of accidental value changes when I try to adjust my inspector view.

**Comment by MewPurPur** [comment]
Nevermind, this PR works well in all situations, I think it's better than mine actually. So my PR can be closed, though I think my comments can be carried over to improve the clarity of the code.

`// Modifiers based on web browsers' DevTools.` before the Ctrl/Alt/Shift modifier code.

`// If the step is smaller than 1 but can be expressed as a 1/int fraction, then set the change to 1.`
`// For example, 0.001 is 1/1000, so then the change will be 1.`
`// Otherwise, for example if the step is 0.4, use that step directly.` before the step declaration.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
