### PR TITLE
Increase directional light energy in sky for fog sun scatter

### LINKED ISSUE #107098: Sun scatter sky energy lower than foreground in Forward+
### Tested versions

Reproducible in 4.4.1-stable.

### System information

Steam Runtime 2 (soldier) 2 on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia) - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 threads)

### Issue description

I'm not sure if this is the same issue as https://github.com/godotengine/godot/issues/44466 but I really do not think that this is desirable behaviour. Somehow it seems that the light energy in the sky is off from the energy in the foreground by a factor of PI?

```DirectionalLight3D``` in light and sky mode with 1.0 energy:
Image

You can remove these ugly silhouettes by using two ```DirectionalLight3D```s, one in sky only mode and one in light only mode, and then setting the sky only light's energy to the energy of the light only lights's multiplied by PI.

```DirectionalLight3D``` in light only mode with 1.0 energy + ```DirectionalLight3D``` in sky only mode with PI energy:
Image

### Steps to reproduce

- Add ```WorldEnvironment``` with a sky and non-volumetric fog which uses sun scatter.
- Add ```DirectionalLight3D``` in light and sky mode.
- Add mesh.
- Position camera so that mesh is partially / fully covered by fog and in front of sun scatter in sky.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
The current behaviour of sun scatter in fog creates ugly silhouettes, which appears to be fixed by increasing the directional light energy by a factor of PI in the sky shader.

master:
image

this pr:
image

Maybe someone can comment as to whether the actual issue is the energy value in the sky or foreground fog shader, but I thought that modifying the sky would be more compatible than modifying the foreground light energy in terms of existing projects.

Fixes https://github.com/godotengine/godot/issues/107098

### CODE REVIEW

**Comment by jcostello** [comment]
Quality improves a lot

**Comment by clayjohn** [comment]
In the scene shader we premultiply the light energy by PI to avoid the multiplication in the shader. Basically when everyone moved to PBR, they started multiplying the light energy by PI since the energy-conserving BRDF includes a division by PI. In sky shaders we exposed the light energy directly because we aren't doing a proper PBR BRDF. So we kept what the user gets in the shader in the same units as what they specify on the scene-side. As you have noticed, we use the energy directly in the calculation of sun-scatter. Therefore, I think this is the correct fix. We shouldn't premultiply on the scene side as that would be compatibility breaking. 

Directional lights in sky:

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/servers/rendering/renderer_rd/environment/sky.cpp#L1094-L1096

Directional Lights in scene:

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/servers/rendering/renderer_rd/storage_rd/light_storage.cpp#L643-L647

**Review by clayjohn — CHANGES_REQUESTED** [review]
This looks great, we just need the same change in the compatibility renderer as well

https://github.com/godotengine/godot/blob/1b37dacc1842779fb0d03a5b09026f59c13744fc/drivers/gles3/shaders/sky.glsl#L144-L146

**Comment by Kaleb-Reid** [comment]
@clayjohn I pushed the change but I've now tested it and it doesn't fix the problem. I'm going to look into it more but currently the compatibility renderer still has an issue with the silhouettes except the sky seems far too bright now.

master on compatibility:
image

this pr as of now on compatibility:
image

**Comment by Kaleb-Reid** [comment]
I think I fixed the compatibility implementation, the color for the sky lights was also missing a conversion from sRGB color space to linear.

this pr now on compatibility:
image

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -700,7 +700,7 @@ void RasterizerSceneGLES3::_setup_sky(const RenderDataGLES3 *p_render_data, cons
 					sky_light_data.energy *= RSG::camera_attributes->camera_attributes_get_exposure_normalization_factor(p_render_data->camera_attributes);
 				}
 
-				Color linear_col = light_storage->light_get_color(base);
+				Color linear_col = light_storage->light_get_color(base).srgb_to_linear();
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_scene_gles3.cpp]: Great catch!

However, this is slightly the wrong approach. It affects the appearance of the sun in the sky shader. 

_With this PR, compatibility_
Screenshot 2025-06-04 at 8 17 43 AM

_Forward+_
Screenshot 2025-06-04 at 8 20 13 AM

The problem comes from how we handle sRGB space in sky shaders. In general the compatibility renderer uses sRGB space for everything except for direct lighting. I.e. all the inputs to the shader are sRGB, inside the shader they get converted to linear for direct lighting then back to sRGB. 

Therefore in the scene shader, we can just pass the light colors in linear. 

In sky shaders, fog is calculated in linear space, but the rest of the sky is in sRGB space. Since we expose the light_color value directly to users, we need to either convert the light color to linear manually in the shader when calculating fog, or we need to pass in linear color separately.

Comment (Kaleb-Reid) [reply drivers/gles3/rasterizer_scene_gles3.cpp]: @clayjohn I tested master, this pr before changing it as you suggested, as well as after and they all have this problem with the sun colour being different in Compatibility than in Forward+. Changing this value actually didn't seem to affect the sun from my testing. I changed it though to do the sRGB -> linear conversion in the shader because as you noted, the light_color value is exposed in users' shaders.

**Review by clayjohn — APPROVED** [review]
Looks great!

File: drivers/gles3/rasterizer_scene_gles3.cpp (hunk 1 above)
Comment (clayjohn) [reply drivers/gles3/rasterizer_scene_gles3.cpp]: The sun colour will always be different because it is blended in sRGB space. So you're right to point out that this PR won't fix that

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
