### PR TITLE
Fix directional shadow bias

### LINKED ISSUE #45115: Vulkan: Directional light shadow rendering is broken on some splits after culling changes
**Godot version:** Git

**OS/device including version:** Fedora 33, GeForce GTX 1080

**Issue description:** Directional light shadow rendering is broken on some splits after the recent culling changes.

**Steps to reproduce:**

- Add a DirectionalLight node.
- Enable shadows on the DirectionalLight.
- Play around with the DirectionalLight shadow's **Max Distance** property if you want to better see the effect.

https://user-images.githubusercontent.com/180032/104247440-1de7e200-5468-11eb-9aa8-0ff1e048290a.mp4

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by reduz**
* Simplified code a lot, bias based on normalized cascade size.
* Lets scale cascades, max distance, etc. without creating acne.
* Fixed normal biasing in directional shadows.

I removed normal biasing in both omni and spot shadows, since the technique can't be easily implemented there.
Will need to be replaced by something else.

*Bugsquad edit: This closes https://github.com/godotengine/godot/issues/45115.*

### CODE REVIEW

File: servers/rendering/renderer_rd/renderer_scene_render_rd.cpp [hunk 1]
```diff
@@ -2701,7 +2701,7 @@ void RendererSceneRenderRD::_setup_lights(const PagedArray<RID> &p_lights, const
 						CameraMatrix shadow_mtx = rectm * bias * matrix * modelview;
 						light_data.shadow_split_offsets[j] = split;
 						float bias_scale = li->shadow_transform[j].bias_scale;
-						light_data.shadow_bias[j] = storage->light_get_param(base, RS::LIGHT_PARAM_SHADOW_BIAS) * bias_scale;
+						light_data.shadow_bias[j] = storage->light_get_param(base, RS::LIGHT_PARAM_SHADOW_BIAS) / 100.0 * bias_scale;
```
Comment (reduz) [inline servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:2704]: I used 100 to avoid integer units for the normalized bias. Could be 1000 I don know.

**Review by JFonS — APPROVED** [review]
Looks good, tested during my work on #51335.

**Comment by akien-mga** [comment]
Thanks!
