### PR TITLE
Expose AnimationNodeOneShot::mix_mode as a property

### LINKED ISSUE #23458: AnimationTree -> OneShot node don't have the UI to change parameters
**Godot version:**
72db3000a56a6f85d348c218437d1a1dfc0953bf

**OS/device including version:**
Ubuntu 18.04, GTX 1060, 64bit

**Issue description:**
'One shot' graph node in the new Animation Tree (not the depreciated AnimationTreePlayer), don't have any UI to change:
- mix mode
- fade in time
- fade out time

one_shot

From the API I can see that those functionalities are implemented but they are not exposed to the graph (there are functions `set_mix_mode`, `set_fadein_time`, `set_fadeout_time` inside `AnimationNodeOneShot`. 

For comparison old version looked like that:
one_shot_old

**Steps to reproduce:**
1. Add `OneShot` node to the animation graph of the `AnimationTree` node.
2. Try to find any way to change the mix mode of this node.

### PR DESCRIPTION
**Pull request by IllusiveS**
fixes #23458

### CODE REVIEW

**Review by TokageItLab — APPROVED** [review]

File: scene/animation/animation_blend_tree.cpp [hunk 1]
```diff
@@ -339,6 +339,8 @@ void AnimationNodeOneShot::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_use_sync", "enable"), &AnimationNodeOneShot::set_use_sync);
 	ClassDB::bind_method(D_METHOD("is_using_sync"), &AnimationNodeOneShot::is_using_sync);
 
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "mix mode", PROPERTY_HINT_ENUM, "Blend, Add"), "set_mix_mode", "get_mix_mode");
```
Comment (theraot) [inline scene/animation/animation_blend_tree.cpp:342]: I suggest using "mix_mode" instead of "mix mode" (which is the pattern for properties everywhere).

To be clear, the change as it is fixes the bug (makes the property available on the Inspector Panel when the node is selected). I'm thinking about not adding extra hassle for scripting.

Comment (TokageItLab) [reply scene/animation/animation_blend_tree.cpp:342]: Indeed, the fixed part is right, but the formatting is not right. I did not test it properly, so overlooked it.

**Review by akien-mga — APPROVED** [review]

File: scene/animation/animation_blend_tree.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/animation/animation_blend_tree.cpp]: Thanks for the review, I force pushed an update to fix this.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.
