### PR TITLE
Prevent crash when passing empty array to MeshEmitter

### LINKED ISSUE #55266: Executing `VisualShaderNodeParticleMeshEmitter.set_mesh` crashes Godot
### Godot version

4.0.dev.custom_build. ed02b8af5

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

When executing
```
func _process(delta):
	var temp_variable16995 = VisualShaderNodeParticleMeshEmitter.new()
	temp_variable16995.set_use_all_surfaces(false)
	temp_variable16995.set_mesh(ArrayMesh.new())
```
Godot crashes with this backtrace
```
ERROR: Index p_surface = 0 is out of bounds (surfaces.size() = 0).
   at: surface_get_arrays (scene/resources/mesh.cpp:1365)
ERROR: Index p_index = 0 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 0).
   at: operator[] (./core/templates/vector.h:50)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.dev.custom_build (ed02b8af59fceb48798c857306335fe0f7ff6a8a)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x22712ac] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:56)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46520) [0x7f54df06d520] (??:0)
[3] VectorWriteProxy<Variant>::operator[](int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/vector.h:50 (discriminator 7))
[4] Array::operator[](int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/array.cpp:81)
[5] VisualShaderNodeParticleMeshEmitter::_update_textures() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/resources/visual_shader_particle_nodes.cpp:540 (discriminator 1))
[6] void call_with_variant_args_helper<VisualShaderNodeParticleMeshEmitter>(VisualShaderNodeParticleMeshEmitter*, void (VisualShaderNodeParticleMeshEmitter::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:228 (discriminator 4))
[7] void call_with_variant_args<VisualShaderNodeParticleMeshEmitter>(VisualShaderNodeParticleMeshEmitter*, void (VisualShaderNodeParticleMeshEmitter::*)(), Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:323)
[8] CallableCustomMethodPointer<VisualShaderNodeParticleMeshEmitter>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/callable_method_pointer.h:96)
[9] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/callable.cpp:50)
[10] Object::emit_signal(StringName const&, Variant const**, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:1105)
[11] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:1159)
[12] Resource::emit_changed() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/io/resource.cpp:44)
[13] VisualShaderNodeParticleMeshEmitter::set_mesh(Ref<Mesh>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/resources/visual_shader_particle_nodes.cpp:606)
[14] void call_with_variant_args_helper<__UnexistingClass, Ref<Mesh>, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Ref<Mesh>), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:223 (discriminator 6))
[15] void call_with_variant_args_dv<__UnexistingClass, Ref<Mesh> >(__UnexistingClass*, void (__UnexistingClass::*)(Ref<Mesh>), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:341)
[16] MethodBindT<Ref<Mesh> >::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:280)
[17] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:837 (discriminator 1))
[18] Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/variant_call.cpp:1021)
[19] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1505)
[20] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1511)
[21] Node::_gdvirtual__process_call(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:232 (discriminator 5))
[22] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:56)
[23] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:48 (discriminator 14))
[24] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:848)
[25] SceneTree::_notify_group_pause(StringName const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:855)
[26] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:453 (discriminator 4))
[27] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2648)
[28] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:342)
[29] godot4s(main+0x414) [0x226ebba] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[30] /lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0) [0x7f54df054fd0] (??:0)
[31] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f54df05507d] (??:0)
[32] godot4s(_start+0x2e) [0x226e6ee] (??:?)
-- END OF BACKTRACE --
================================================================
```
### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/55266

### CODE REVIEW

File: scene/resources/visual_shader_particle_nodes.cpp [hunk 1]
```diff
@@ -504,66 +502,88 @@ void VisualShaderNodeParticleMeshEmitter::_update_textures() {
...
 
 	if (use_all_surfaces) {
-		for (int i = 0; i < max_surface_index; i++) {
+		for (int i = 0; i < mesh->get_surface_count(); i++) {
 			// position
-			Array vertex_array = mesh->surface_get_arrays(i)[Mesh::ARRAY_VERTEX];
-			for (int j = 0; j < vertex_array.size(); j++) {
-				vertices.push_back((Vector3)vertex_array[j]);
+			if (mesh->surface_get_arrays(i).size() > Mesh::ARRAY_VERTEX) {
+				Array vertex_array = mesh->surface_get_arrays(i)[Mesh::ARRAY_VERTEX];
```
Comment (akien-mga) [inline scene/resources/visual_shader_particle_nodes.cpp:508]: Sounds like both `mesh->surface_get_arrays(i)` and `mesh->surface_get_arrays(i).size()` could be saved to local variables to avoid calling the getters for every check:
```
const Array surface_arrays = mesh->surface_get_arrays(i);
const int surface_arrays_size = surface_arrays.size();
```

Comment (Chaosus) [reply scene/resources/visual_shader_particle_nodes.cpp]: Done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
