### PR TITLE
Fix multiple issues with 'add alternative tile' tileset editor button

### LINKED ISSUE #99764: In tileset editor, attempting to paint terrain over alternative tile instead creates a new alternative tile
### Tested versions

- Reproducible for v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - AMD Radeon RX 6600M (Advanced Micro Devices, Inc.; 30.0.13024.5001) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

Attempting to paint terrain over an alternative tile instead results with the terrain editor creating a new alternative tile. Which shouldn't happen, as the alternative tile creation is done via "Select" tab of the tileset editor.

### Steps to reproduce

1. Load attached project
2. Open `player.tscn`
3. Open `TileMapLayer` node
4. Switch to tileset editing, `Paint` mode
5. Select property `Terrains` -> `Terrain Set 0` -> `Dots Biome`
6. Attempt to paint this point:
Image
7. Be greeted with this sight:
Image

### Minimal reproduction project (MRP)

[TerrainPainterBug.zip](https://github.com/user-attachments/files/17937477/TerrainPainterBug.zip)

### PR DESCRIPTION
**Pull request by olanti-p**
Fix multiple issues with 'add alternative tile' tileset editor button in "Alternative tiles" section:
1. Fix button being oversized and not rendered properly on small (texture region size < 12px) tilesets (fixes #99764)
2. Stop button from interfering with MMB panning
3. Fix undo not working on tiles created with this button
4. Stop the button from appearing while painting tile properties

The undo doesn't undo increments in `next_alternative_id` counter within TileSetAtlasSource, but that's an existing issue that also happens when creating alternative tiles via RMB.

Before/after:
image

### CODE REVIEW

**Comment by groud** [comment]
The commits should likely be squashed, but aside from that, looks good to me.

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 1]
```diff
@@ -2009,6 +2011,17 @@ void TileSetAtlasSourceEditor::_tile_alternatives_control_mouse_exited() {
 	alternative_tiles_control_unscaled->queue_redraw();
 }
 
+void TileSetAtlasSourceEditor::_tile_alternatives_create_button_pressed(const Vector2i p_atlas_coords) {
+	EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
+
+	// FIXME: doesn't undo changes to `next_alternative_id` counter
```
Comment (KoBeWi) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2017]:
```suggestion
	// FIXME: Doesn't undo changes to `next_alternative_id` counter.
```
It just means that some alternative IDs will be skipped when you undo and make them again, no?

**Review by KoBeWi — APPROVED** [review]

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp (hunk 1 above)
Comment (olanti-p) [reply editor/plugins/tiles/tile_set_atlas_source_editor.cpp:2017]: Correct. I mention it because the counter is saved, so a sequence of user actions "create tile"->"undo"->"save" produces an unexpected change in the resource file. Intuitive behavior would be to leave no evidence of undone change.

**Comment by KoBeWi** [comment]
@groud ^

**Comment by groud** [comment]
> I'm not sure how to fix these errors, but I could make it so the button is disabled while "Paint" tab is active, and user can't create alternative tiles while painting properties. Would such solution be fine?

Well, in theory, the create alternative button should only be visible in the "setup" tab. That's where you define tiles and their alternatives.

**Comment by olanti-p** [comment]
Applied suggested changes, and also stopped the button from appearing in "paint" tab.

> Well, in theory, the create alternative button should only be visible in the "setup" tab. That's where you define tiles and their alternatives.

At this moment the UI already allows creating and deleting tiles (both base and alternative) in both "setup" and "select" tabs with RMB, and entire alternative tile config has to be done in "select" tab anyway, so stopping the button from appearing in "select" tab feels unnecessarily restrictive. Although if that's something still wanted, I'll change it.

**Comment by groud** [comment]
> At this moment the UI already allows creating and deleting tiles (both base and alternative) in both "setup" and "select" tabs with RMB, and entire alternative tile config has to be done in "select" tab anyway, so stopping the button from appearing in "select" tab feels unnecessarily restrictive. Although if that's something still wanted, I'll change it.

Well, in the "select" mode I think it kind of make sense to make it a bit more difficult to create tiles, as a missclick could easily happen and would maybe be a bit annoying. You can create alternatives there with right click too (though I think the option to create a new alternative should be available in the dropdown menu of alternative tiles too).

In any case, I don't really have a strong opinion on that, so if others want the button, I guess it makes sense to add it there.

**Comment by KoBeWi** [comment]
I tested the updated version and it works in both Setup and Select modes without errors, so it's fine.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
