### PR TITLE
Move Vulkan includes to a central `godot_vulkan.h` header

### LINKED ISSUE #96918: Build problem with recent Clang releases
### Tested versions

- Reproducible with Godot master (4.4 - 83d54ab2ad476ae265b323c2b88f4623b922f4c6)

### System information

MacOS 14.6.1 - Xcode Version 16.0 (16A242 - Release Candidate)

### Issue description

It seems that a stricter Clang is triggering a problem in Godot.

The issue seems to be that Objective-C++ code includes vulkan.h, which uses an `extern 'C'` block and then includes the C `stdint.h`, but for some reason recent Clang++ map '#include stdint.h' into importing the C++ module 'std_stdint_h', which is not allowed to be done from C.

The build error is like this:

```
In file included from platform/ios/keyboard_input_view.mm:33:
In file included from platform/ios/display_server_ios.h:42:
In file included from platform/ios/rendering_context_driver_vulkan_ios.h:36:
In file included from ./drivers/vulkan/rendering_context_driver_vulkan.h:46:
In file included from thirdparty/vulkan/include/vulkan/vulkan.h:11:
In file included from thirdparty/vulkan/include/vulkan/vulkan_core.h:8325:
In file included from thirdparty/vulkan/include/vk_video/vulkan_video_codec_h264std.h:24:
thirdparty/vulkan/include/vk_video/vulkan_video_codecs_common.h:25:5: error: import of C++ module 'std_stdint_h' appears within extern "C" language linkage specification [-Wmodule-import-in-extern-c,15]
   25 |      #include <stdint.h>
      |      ^
thirdparty/vulkan/include/vk_video/vulkan_video_codecs_common.h:17:1: note: extern "C" language linkage specification begins here [2]
   17 |  extern "C" {
      |  ^

```

I am using this workaround, which seems a bit like brute force, hence why this is not a PR:

```
diff --git a/platform/ios/SCsub b/platform/ios/SCsub
index cf565db049..1ee114e59e 100644
--- a/platform/ios/SCsub
+++ b/platform/ios/SCsub
@@ -95,6 +95,8 @@ else:
 # (iOS) Enable module support
 env_ios.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])
 
+env_ios.Append(CCFLAGS=["-Wno-module-import-in-extern-c"])
+
 
 def combine_libs(target=None, source=None, env=None):
     lib_path = target[0].srcnode().abspath
```

### Steps to reproduce

To reproduce this issue you need a recent clang, like the one that was just released for Xcode 16.0.

Build Godot on MacOS, like this:

```
scons p=ios
```

### Minimal reproduction project (MRP)

None is needed, just upgrading Xcode 16.0

### PR DESCRIPTION
**Pull request by kisg**
Also fixes Vulkan build problem with recent Clang.

Developed by [Migeran](https://migeran.com/), sponsored by [Xibbon Inc.](https://xibbon.com/)

Fixes #96918.

### CODE REVIEW

File: thirdparty/vulkan/vk_enum_string_helper.h [hunk 1]
```diff
@@ -13,11 +13,7 @@
 #ifdef __cplusplus
 #include <string>
 #endif
-#ifdef USE_VOLK
-    #include <volk.h>
-#else
-    #include <vulkan/vulkan.h>
-#endif
+#include "drivers/vulkan/godot_vulkan.h"
```
Comment (bruvzg) [inline thirdparty/vulkan/vk_enum_string_helper.h:16]: Changes in third party files should be marked by `/* GODOT start */`, `/* GODOT end */` comments and/or have patches included (usually in the `patches` subfolder), and mentioned in the `thirdparty/README.md` (this includes seems to be part of existing patches, which should be updated).

Comment (kisg) [reply thirdparty/vulkan/vk_enum_string_helper.h:16]: Done.

File: thirdparty/vulkan/vk_mem_alloc.h [hunk 2]
```diff
@@ -122,16 +122,13 @@ for user-defined purpose without allocating any real GPU memory.
...
 #ifdef __cplusplus
 extern "C" {
 #endif
 
-#ifdef USE_VOLK
-    #include <volk.h>
-#else
-    #include <vulkan/vulkan.h>
-#endif
+
```
Comment (akien-mga) [inline thirdparty/vulkan/vk_mem_alloc.h:131]: We're unintentionally adding a stray line here, would be good to remove it (also in the .patch) to keep our changes minimal.

What's the rationale from moving the include outside the `extern "C"` scope though? Does it only work for C++ code?

**Review by akien-mga — APPROVED** [review]
Looks good to me, just left a minor nitpick.

File: thirdparty/vulkan/vk_mem_alloc.h (hunk 2 above)
Comment (kisg) [reply thirdparty/vulkan/vk_mem_alloc.h:131]: The original error from Clang was that it was no longer allowed to include stdint.h in an extern "C" {} block. That is why the include was moved.

Comment (kisg) [reply thirdparty/vulkan/vk_mem_alloc.h:131]: Pushed the update with the removal of the extra line.

**Comment by akien-mga** [comment]
Thanks!

**Comment by zaddok** [comment]
What is the best way for 4.3 users to use this as of today?  scons fails to build on my Mac at the moment due to this error. 4.3 doesnt have an updated release, and 4.4 is not yet out.

**Comment by zaddok** [comment]
With an up to date 4.3 checkout to my local up to date Mac, I am encountering this problem. 

Are there plants to allow scons to be used on Mac with 4.3? It seems, as it stands, it's not possible to use scons on Mac with stable godot.   Does anyone have a workaround for building on Mac for godot 4.3?

**Comment by zaddok** [comment]
I have manually applied this patch to my checkout of the 4.3 branch and I can confirm for people on 4.3, that this patch does allow building on MacOS 15.1 using Xcode 16.1.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1, 4.2.3, and 4.1.5.

**Comment by aaronfranke** [comment]
The cherry-pick to the 4.2 branch missed a spot (but the 4.1 and 4.3 branches are good). I opened PR #110036 to fix this.
