### PR TITLE
Fix headless import always emits errors

### LINKED ISSUE #103398: Headless import always emits errors about `!tasks.has(p_task)`
### Tested versions

- Reproducible in: 4.4.rc2
- Reproducible in: 4.4.dev2
- Not reproducible in: 4.4.dev1

### System information

Godot v4.4.rc2 - Windows 11 (build 26100) - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6636) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 threads)

### Issue description

(This is a formal issue for what's mentioned [here](https://github.com/godotengine/godot/issues/100900#issuecomment-2567712127), and potentially a duplicate of #100900 itself, but since that one mentions errors at startup I figured it's possibly a different issue.)

When running Godot with `--headless --import` on any project, you're currently met with the following output:

```
ERROR: Do not use progress dialog (task) while flushing the message queue or using call_deferred()!
   at: add_task (editor/progress_dialog.cpp:183)
ERROR: Condition "!tasks.has(p_task)" is true. Returning: canceled
   at: task_step (editor/progress_dialog.cpp:217)
ERROR: Condition "!tasks.has(p_task)" is true. Returning: canceled
   at: task_step (editor/progress_dialog.cpp:217)
ERROR: Condition "!tasks.has(p_task)" is true. Returning: canceled
   at: task_step (editor/progress_dialog.cpp:217)
ERROR: Condition "!tasks.has(p_task)" is true. Returning: canceled
   at: task_step (editor/progress_dialog.cpp:217)
ERROR: Condition "!tasks.has(p_task)" is true. Returning: canceled
   at: task_step (editor/progress_dialog.cpp:217)
ERROR: Condition "!tasks.has(p_task)" is true. Returning: canceled
   at: task_step (editor/progress_dialog.cpp:217)
ERROR: Condition "!tasks.has(p_task)" is true.
   at: end_task (editor/progress_dialog.cpp:240)
```

The import seems to complete successfully despite that, I think.

When bisecting it seems that this is a regression stemming from #93064.

### Steps to reproduce

- Create a new project.
- Run `/path/to/godot --headless --import` in the project folder.
- Note the errors.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #103398  

There's a condition in `EditorNode::_begin_first_scan` to execute the editor filesystem scan during the message queue flush. With the addition of progress dialogs during the import process in #93064, `ProgressDialog::add_task` is now always called during a message queue flush when using `--headless --import`.  

Progress dialogs are not useful when nothing is displayed, so I skipped the `ProgressDialog` code when using `--headless` by checking `DisplayServer::get_singleton()->window_can_draw()`.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good, but wouldn't it make sense to go once step above and avoid registering ProgressDialog steps in headless mode? Or would that add significant complexity to the implementation?

**Comment by Hilderin** [comment]
I'm not sure I understand exactly what you mean by `avoid registering ProgressDialog steps`. Do you mean not creating the `ProgressDialog` instance in EditorNode, moving the condition in `EditorProgress::EditorProgress` or avoiding all the calls to `EditorProgress` in `EditorNode`?? Or something else??

**Comment by Calinou** [comment]
> Progress dialogs are not useful when nothing is displayed, so I skipped the ProgressDialog code when using --headless by checking DisplayServer::get_singleton()->window_can_draw().

Note that we could technically support displaying progress dialogs in headless mode, but it would likely involve something like [ncurses](https://invisible-island.net/ncurses/announce.html) which would bring a lot of added complexity for limited benefit.

**Comment by akien-mga** [comment]
> > Progress dialogs are not useful when nothing is displayed, so I skipped the ProgressDialog code when using `--headless` by checking `DisplayServer::get_singleton()->window_can_draw()`.
> 
> Note that we could technically support displaying progress dialogs in headless mode, but it would likely involve something like [ncurses](https://invisible-island.net/ncurses/announce.html) which would bring a lot of added complexity for limited benefit. Not to mention it wouldn't play well with CI where progress reporting should be purely non-interactive.

Yeah I wouldn't add that, `--headless` is first and foremost meant for CI / server use, so non-interactive.

**Comment by akien-mga** [comment]
> That sounds interesting, but I'm not sure I understand exactly what you mean by `avoid registering ProgressDialog steps`. Do you mean not creating the `ProgressDialog` instance in EditorNode, moving the condition in `EditorProgress::EditorProgress` or avoiding all the calls to `EditorProgress` in `EditorNode`?? Or something else??

I meant not creating any `EditorProgress` in `EditorNode` when headless mode is enabled. But checking https://github.com/godotengine/godot/pull/93064 I see that it would add a lot of boilerplate. The way you did it is probably the simplest.

**Review by akien-mga — DISMISSED** [review]

**Comment by akien-mga** [comment]
Actually, I was confusing `EditorProgress` and `ProgressDialog`. Looking at the code of `EditorProgress`, it seems already designed to not use `ProgressDialog` on command line:
```
bool EditorNode::progress_task_step(const String &p_task, const String &p_state, int p_step, bool p_force_refresh) {
	if (!singleton) {
		return false;
	} else if (singleton->cmdline_export_mode) {
		print_line("\t" + p_task + ": step " + itos(p_step) + ": " + p_state);
		return false;
	} else if (singleton->progress_dialog) {
		return singleton->progress_dialog->task_step(p_task, p_state, p_step, p_force_refresh);
	} else {
		return false;
	}
}
```

We might just need to change the condition there.

**Comment by Hilderin** [comment]
I updated the PR with a new suggestion renaming `cmdline_export_mode` for `cmdline_mode` and reusing it in headless mode.

I looked to place the condition directly into `EditorProgress` but I saw that `EditorNode::progress_add_task` is called directly from `godot_icall_EditorProgress_Create` in `editor_internal_calls`.

This proposed version has the advantage of displaying the progress in the output console, exactly how it was done when exporting from command line:
image

And we can also see that there's a couple of useless steps in headless mode, but there's already an issue for that: https://github.com/godotengine/godot/issues/103305

**Comment by mihe** [comment]
It sounds like this would supersede my old PR to some degree: #90806

**Comment by Hilderin** [comment]
Just fixed merge conflict.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -6848,6 +6848,11 @@ EditorNode::EditorNode() {
 	DEV_ASSERT(!singleton);
 	singleton = this;
 
+	// Detecting headless mode, that means the editor is running in command line.
+	if (!DisplayServer::get_singleton()->window_can_draw()) {
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply editor/editor_node.cpp:6852]: That's a good point yes. We should probably review usage of `window_can_draw()` to mean "headless", which there are a few other occurrences of in EditorNode.

That can be done in a separate PR though, for this one I think it makes sense to stay consistent with other pre-existing usage.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -6848,6 +6848,13 @@ EditorNode::EditorNode() {
...
+		cmdline_mode = true;
+	}
+
+	set_translation_domain("godot.editor");
+
```
Comment (akien-mga) [inline editor/editor_node.cpp:6857]: Just curious, why is this now needed?

Comment (Hilderin) [reply editor/editor_node.cpp]: That's an error from the merge conflict on my part. This line was removed in master. I removed it in this PR also.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by mihe** [comment]
@Hilderin I haven't looked into this too deeply, but the exact error that this issue fixes for headless can also be seen when minimizing the editor while it's starting up, as mentioned by another user [here](https://github.com/godotengine/godot/issues/100900#issuecomment-2705248413), even when using the fix from this PR.

Given that the user has narrowed down the regression to have been introduced between 4.4-dev1 and 4.4-dev2 I assume it's largely the same issue, but I haven't bisected the exact commit.

I'm guessing `DisplayServer::window_can_draw` isn't sufficient to capture the case where the `DisplayServer` can actually draw but isn't able to? Would we even want `cmdline_mode` in those cases?

**Comment by akien-mga** [comment]
> I'm guessing `DisplayServer::window_can_draw` isn't sufficient to capture the case where the `DisplayServer` can actually draw but isn't able to (if that's even a thing)? Would we even want `cmdline_mode` in those cases?

Then maybe @Riteo is right in https://github.com/godotengine/godot/pull/103403/files#diff-b88f0bde58b731e8dd353707c8011fb7a1e452f0db2c9f15f4b7905d60e5e52e and we should switch all those to explicitly check for `headless`.

**Comment by mihe** [comment]
To clarify, I'm saying that this fix is missing a case of this regression, since it doesn't seem to fix the case where we're not headless, but the window is instead just minimized. So the fix introduced by this PR likely needs to be altered or supplemented to encompass that.

Switching to what @Riteo suggested (which might still be warranted) would not resolve this.

**Comment by mihe** [comment]
> That's why I think that checking for the DS name instead of `window_can_draw` should fix the issue for the minimized case.

I'm confused. I was under the impression that this PR fixed the issue of headless imports because it was made to piggyback on what was previously called `cmdline_export_mode`, but is now just called `cmdline_mode`, which lets us skip all the progress dialog stuff that causes the errors to be emitted, as seen here:

https://github.com/godotengine/godot/blob/b5bdb88062a31a982c8f3bf4b820188edd53c6c5/editor/editor_node.cpp#L4995-L5003

So switching out the `DisplayServer::window_can_draw()` check that this PR introduced would presumably result in _less_ cases being encompassed by this change (which, again, might be warranted for other reasons). The issue with errors being emitted when minimizing the editor on startup (as reported [here](https://github.com/godotengine/godot/issues/100900#issuecomment-2705248413)) is not a regression from this PR, it's a yet-to-be-fixed regression from #93064.

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
