### PR TITLE
More Crypto, SSL server, crt/key as Resource, HashingContext

### LINKED ISSUE #27045: Can't connect to asset-library if custom certificate is set in Project Settings
**Godot version:**

3.1 stable

**OS/device including version:**

**Issue description:**

A custom certificate might impact the ability to access the asset library.

`Can't connect to host: https://godotengine.org/asset-library/api`

```
thirdparty/mbedtls/library/ssl_tls.c:5757: x509_verify_cert() returned -9984 (-0x2700)
ERROR: _do_handshake: TLS handshake error: -9984
   At: modules/mbedtls/stream_peer_mbed_tls.cpp:105.
mbedtls error: returned -0x2700
```

**Steps to reproduce:**

- Set a custom certificate in Project Settings -> SSL
- Restart the editor
- Try and access the Asset Library

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by Faless**
This PR includes:

- New `hex_encode` function for `PoolByteArray` that convert the bytes to an hex string.
- New **`Crypto`** class that can **generate random bytes, rsa keys,  self signed certificates**.
- Certificates (**crt**) and Keys (**key**) are considered **`Resource`**. You can `load` and save them.
- Implemented `StreamPeerSSL.accept_stream` (**SSL server**) and allow selecting specific valid CAs when calling `conntect_to_stream`.
- ~**AES encryption** via the `AESContext` class~ (will be done in a separate PR).
- **MD5/SHA1/SHA256 hashing** via the `HashingContext` class.

This is also some ground work towards implementing DTLS, and internal HTTP(S) server for HTML5 debug.

Some interesting points:
- Certs and keys gets "locked" when in use by a stream, and can't be changed when in use.
  This is so you can have a single instance of key/cert, and use it across multiple peers, without holding.
- Should we have a default "Crypto" singleton (right now it's an object you instance)? I like having the possibility of them having different seeds, but having a default one would be nice.
- Should we use the same random number generator across all SSL sessions (could that be a weakness?), right now it uses one rng per session as before.

A small example that uses this PR (SSL server with self-signed certificate, visit https://localhost:4343 after opening):
```gdscript
extends Node

class Client:
	var ssl = StreamPeerSSL.new()
	var recv = ""

	func set_stream(stream, key, cert):
		ssl.blocking_handshake = false
		ssl.accept_stream(stream, key, cert)

	func process():
		if ssl.get_status() != StreamPeerSSL.STATUS_CONNECTED:
			return
		ssl.poll()
		if ssl.get_available_bytes() > 0:
			recv += ssl.get_data(ssl.get_available_bytes())[1].get_string_from_utf8()
		if recv.ends_with("\r\n\r\n"):
			ssl.put_data(("HTTP/1.0 200 OK\r\nContent-Type: text/html\r\n\r\n" + \
						"<h2>Godot TLS Test Server</h2>\r\n"  + \
						"<p>Successful connection using SSL</p>\r\n").to_utf8())
			ssl.disconnect_from_stream()

var _server = TCP_Server.new()
var _clients = []
var _cert = null
var _key = null

func _ready():
	var crypto = Crypto.new()
	_key = crypto.generate_rsa(4096)
	_cert = crypto.generate_self_signed_certificate(_key, "CN=aserver,O=A Game Company,C=IT")
	_key.save("res://generated.key")
	_cert.save("res://generated.crt")
	_server.listen(4343)

func _process(delta):
	if _server.is_connection_available():
		var c = Client.new()
		c.set_stream(_server.take_connection(), _key, _cert)
		_clients.append(c)

	for c in _clients:
		c.process()
```

Another example showing hahsing:
```gdscript
extends Node

func _ready():
	var ctx = HashingContext.new()
	ctx.start(HashingContext.HASH_MD5) # Or HASH_SHA1 or HASH_SHA256
	print("a".to_utf8().size())
	ctx.update("a".to_ascii())
	var fin = ctx.finish()
	print(Array(fin))
	print(fin.hex_encode())
```

Fixes #27045 .

References (possibly close after some more work): #29871 #25928 #1969

### CODE REVIEW

**Comment by nate066** [comment]
This looks really cool, I hope AES support will happen along with a hashing algorithm like argon2. :)

**Comment by fire** [comment]
How do you want this reviewed? Is there anything in particular you want to look for? Did you make basic demos that use these and do they run as expected?

**Comment by fire** [comment]
Also, can you improve the quality of the commity messages and reduce the number of commits?

**Comment by Faless** [comment]
> How do you want this reviewed?

It's still WIP, so mainly in terms of structure (see interesting points), 

>  Did you make basic demos that use these and do they run as expected?

Just the attached script.

> Also, can you improve the quality of the commit messages and reduce the number of commits?

Yes, I will, before removing the WIP tag, but it's likely going to be 2 commits in the end.
- Adding crypto
  (`modules/mbdetls/crypto_mbedtls.*` and `core/math/crypto.*`)
- Porting StreamPeerSSL to crypto
  (`core/io/stream_peer_ssl.*`, `modules/mbdetls/ssl_context_mbed_tls.*`, `modules/mbdetls/stream_peer_mbedtls.*`)

**Comment by aspenforest** [comment]
Please consider adding SHA-3 and BLAKE hash functions. :)

**Comment by akien-mga** [comment]
FYI, the javascript platform currently disables the mbedTLS module with this comment:
```python
        # Disabling the mbedtls module reduces file size.
        # The module has little use due to the limited networking functionality
        # in this platform. For the available networking methods, the browser
        # manages TLS.
        ('module_mbedtls_enabled', False),
```
I guess we might want to enable it again for this module?

**Comment by Faless** [comment]
> I guess we might want to enable it again for this module?

Yeah, an alternative is for Javascript to have its own implementation via the [CryptoAPI](https://developer.mozilla.org/en-US/docs/Web/API/Crypto).

But I would prefer having only one implementation for ease of maintenance, it should pretty much work out of the box, the only difference might be in the entropy function.

I'll do a size comparison with and without the module to see how much bigger we get in the HTML5 export.

**Comment by fire** [comment]
Are you blocked on anything? Is there anything we can do to help you?

**Comment by Faless** [comment]
> Are you blocked on anything? Is there anything we can do to help you?

I've been busy on the WebSocket library switch and some other fixes.
I'm finally back to this, so you can expect an update soon, I'm thinking of adding AES and support to streamed hashing before marking this as ready for review :)

**Comment by fire** [comment]
Can you split those changes to another PR, or do they require code stubs for them? 

I wish to try this in master without custom merging this branch.

**Comment by nate066** [comment]
Is there any chance you add CBC or GCM to AES. Since ECB is considered less secure/ insecure. https://datalocker.com/what-is-the-difference-between-ecb-mode-versus-cbc-mode-aes-encryption/

**Comment by Faless** [comment]
> Is there any chance you add CBC or GCM to AES.

Of course, but likely in a separate PR, this one is already pretty big.

**Comment by nate066** [comment]
That would be awesome

**Comment by Faless** [comment]
I've removed the AES part, since it was incomplete and it was taking too long for me to get it right.
AES will be added in a separate PR, this one should be ready now.

File: editor/editor_settings.cpp [hunk 1]
```diff
@@ -1022,7 +1022,8 @@ void EditorSettings::setup_network() {
 	add_property_hint(PropertyInfo(Variant::INT, "network/debug/remote_port", PROPERTY_HINT_RANGE, "1,65535,1"));
 
 	// Editor SSL certificates override
-	_initial_set("network/ssl/editor_ssl_certificates", _SYSTEM_CERTS_PATH);
+	String certs = has_setting("network/ssl/editor_ssl_certificates") ? get("network/ssl/editor_ssl_certificates") : _SYSTEM_CERTS_PATH;
```
Comment (akien-mga) [inline editor/editor_settings.cpp]: Why is it done this way? Doesn't it mean that the "initial" (revert) value will always be the currently set one, so it's not revertable?

File: core/crypto/crypto.cpp [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+}
+
+void Crypto::_bind_methods() {
+	ClassDB::bind_method(D_METHOD("generate_random_bytes", "size"), &Crypto::generate_random_bytes);
+	ClassDB::bind_method(D_METHOD("generate_rsa", "size"), &Crypto::generate_rsa);
+	ClassDB::bind_method(D_METHOD("generate_self_signed_certificate", "key", "issuer_name", "not_before", "not_after"), &Crypto::generate_self_signed_certificate, DEFVAL("CN=myserver,O=myorganisation,C=IT"), DEFVAL("20140101000000"), DEFVAL("20340101000000"));
+}
+
+PoolByteArray Crypto::generate_random_bytes(int p_bytes) {
+	ERR_EXPLAIN("generate_random_bytes is not available when mbetls module is disabled");
```
Comment (akien-mga) [inline core/crypto/crypto.cpp]: See #31207, this should be changed to `ERR_FAIL_V_MSG`.

There's also a typo in "mbe**d**tls" (in all occurrences), and it would be nice to add a dot at the end of the error messages.

File: editor/editor_settings.cpp (hunk 1 above)
Comment (Faless) [reply editor/editor_settings.cpp]: No, it means that the value shown in the editor settings will be the last configured value if available, otherwise `_SYSTEM_CERTS_PATH` (which is an empty string).
The same is done above for debug address and port.

Comment (akien-mga) [reply editor/editor_settings.cpp]: But isn't it what `_initial_set` did already? It's designed so that it defines the default value, but doesn't override any custom value.

File: core/crypto/crypto.cpp (hunk 2 above)
Comment (Faless) [reply core/crypto/crypto.cpp]: Thanks, fixed!

**Review by akien-mga — APPROVED** [review]

File: editor/editor_settings.cpp (hunk 1 above)
Comment (Faless) [reply editor/editor_settings.cpp]: I see, I'll fix that, probably `network/debug/remote_port` should use the same behaviour then. (`network/debug/remote_host` is a bit special instead)

Comment (Faless) [reply editor/editor_settings.cpp]: Well, `_initial_set` always calls `set` :( . I guess `setup_network` needs to be modified a bit.

Comment (akien-mga) [reply editor/editor_settings.cpp]: I guess `setup_network()` simply happens too late? `_initial_set` works fine for dozens of settings, but it's meant to be called before loading the editor settings. It sets the default value, and then it can be overridden by user values from `editor_settings-3.tres`.

Comment (akien-mga) [reply editor/editor_settings.cpp]: See `_load_defaults()`, which is called by the constructor.

Comment (Faless) [reply editor/editor_settings.cpp]: See added commit https://github.com/godotengine/godot/pull/29871/commits/fc411115f5ddb214c19b23499400f10266095e5f as a potential fix

Comment (akien-mga) [reply editor/editor_settings.cpp]: Looks good!

**Comment by akien-mga** [comment]
Thanks!
