### PR TITLE
Disable multi-window buttons instead of hiding them when support is unavailable

### LINKED ISSUE #84435: Floating script editor button is hidden when Single Window Mode is enabled
### Godot version

4.2 beta4

### System information

Godot v4.2.beta4 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.2647) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

The button to make the script editor floating is no longer present in 4.2 beta 4

4.2:
image

4.1:
image

Also using the ctrl shift P shorting and selecting "make floating" under the script editor section does nothing

### Steps to reproduce

Open a script, notice there is no floating button. 

Try to use "make floating" option using ctrl shift P, notice it does nothing

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Calinou**
This is more explicit as for why this functionality isn't available depending on editor settings and current platform.

This also exposes a `EditorInterface.is_multi_window_enabled()` method so that editor plugins can easily query whether the editor is able and expected to create multiple windows.

- This closes https://github.com/godotengine/godot/issues/84435.

## Preview

Screenshot_20231106_123931

Screenshot_20231106_124049

### CODE REVIEW

**Review by deralmas — COMMENTED** [review]
I tested it on top of #57025 (which will sadly be singlewin for the foreseeable future) and it works fine! This will definitely help at avoiding confusion.

One last thing before I approve though: the tooltips talk about "this platform", but the concept of a platform will be further differentiated when the second Linux/BSD DS will come out (Wayland). I propose using a more specific term like, well, "display server".

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -7171,16 +7171,25 @@ EditorNode::EditorNode() {
...
-		dock_float->set_focus_mode(Control::FOCUS_NONE);
-		dock_float->set_h_size_flags(Control::SIZE_SHRINK_CENTER);
-		dock_float->connect("pressed", callable_mp(this, &EditorNode::_dock_make_selected_float));
-
-		dock_vb->add_child(dock_float);
-	}
+	dock_float = memnew(Button);
+	dock_float->set_icon(theme->get_icon("MakeFloating", EditorStringName(EditorIcons)));
+	dock_float->set_text(TTR("Make Floating"));
+	const bool multi_window_enabled = !SceneTree::get_singleton()->get_root()->is_embedding_subwindows() && !EDITOR_GET("interface/editor/single_window_mode") && EDITOR_GET("interface/multi_window/enable");
```
Comment (YeldhamDev) [inline editor/editor_node.cpp:7177]: This PR adds 2 more instances that uses this to confirm multi-window is enabled, with the total now being 4[^1]. We really should add a centralized way to ask this that checks those conditions by itself.

[^1]: The other two instances being in https://github.com/godotengine/godot/blob/b7449a3d1aebd34026c7a2279a1b18ff0f02ccfa/editor/editor_node.cpp#L7174 and https://github.com/godotengine/godot/blob/b7449a3d1aebd34026c7a2279a1b18ff0f02ccfa/editor/window_wrapper.cpp#L317.

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected.

**Comment by KoBeWi** [comment]
> I've tried to read OS.get_cmdline_args() to check whether --single-window was used, but it's not present in the list of arguments when you pass it to the editor.

Instead you should check if `FEATURE_SUBWINDOWS` is supported by DisplayServer. Right now when you use `--single-window`, the button will say that multiwindow is not supported by the current platform.

File: editor/editor_dock_manager.cpp [hunk 2]
```diff
@@ -702,15 +702,22 @@ EditorDockManager::EditorDockManager() {
...
+	dock_float->set_text(TTR("Make Floating"));
+	if (!EditorNode::get_singleton()->is_multi_window_enabled()) {
+		dock_float->set_disabled(true);
+		if (SceneTree::get_singleton()->get_root()->is_embedding_subwindows()) {
+			dock_float->set_tooltip_text(TTR("Multi-window support is not available because the current platform doesn't support multiple windows."));
+		} else if (EDITOR_GET("interface/editor/single_window_mode")) {
+			dock_float->set_tooltip_text(TTR("Multi-window support is not available because Interface > Editor > Single Window Mode is enabled in the editor settings."));
+		} else if (EDITOR_GET("interface/multi_window/enable")) {
+			dock_float->set_tooltip_text(TTR("Multi-window support is not available because Interface > Multi Window > Enable is disabled in the editor settings."));
+		}
```
Comment (KoBeWi) [inline editor/editor_dock_manager.cpp:715]: This code should be moved to a method somewhere, like `get_multliwindow_support_tooltip()`.

File: editor/plugins/shader_editor_plugin.cpp [hunk 3]
```diff
@@ -655,6 +655,10 @@ ShaderEditorPlugin::ShaderEditorPlugin() {
 
 		menu_hb->add_child(make_floating);
 		window_wrapper->connect("window_visibility_changed", callable_mp(this, &ShaderEditorPlugin::_window_changed));
+	} else {
+		// Add placeholder button that displays tooltip about multi-window support being unavailable.
+		make_floating = memnew(ScreenSelect);
+		menu_hb->add_child(make_floating);
```
Comment (KoBeWi) [inline editor/plugins/shader_editor_plugin.cpp:661]: Wouldn't it be better if you adjusted the above code instead? (like in the dock manager)
Right now the disabled button looks differently from non-disabled one.

Same in shader editor, where the button even changes position.

File: editor/plugins/script_editor_plugin.cpp [hunk 4]
```diff
@@ -4074,17 +4074,14 @@ ScriptEditor::ScriptEditor(WindowWrapper *p_wrapper) {
 	script_forward->set_disabled(true);
 	script_forward->set_tooltip_text(TTR("Go to next edited document."));
 
-	if (p_wrapper->is_window_available()) {
-		menu_hb->add_child(memnew(VSeparator));
+	menu_hb->add_child(memnew(VSeparator));
 
-		make_floating = memnew(ScreenSelect);
-		make_floating->set_flat(true);
-		make_floating->set_tooltip_text(TTR("Make the script editor floating."));
```
Comment (KoBeWi) [inline editor/plugins/script_editor_plugin.cpp:4082]: Seems like this tooltip is lost and now it refers to script/shader editor as "this panel". Since the disabled logic runs in the constructor, you could check if the button is not disabled and ovewrite the tooltip.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
