### PR TITLE
Button shortcuts no longer "press" the Button.

### LINKED ISSUE #40464: The "Add Child Node" button remains pressed after adding a node via shortcut
**Godot versions:**
4.0.dev 9e34ba48556b71f1f672b5be47d12b0e3f679b86
3.2.3.beta
3.2.2.stable
*Cannot* reproduce in 3.1.1.stable, regression?

**OS/device including version:**
Windows 10, GLES3

**Issue description:**
The "Add Child Node" button remains visually pressed after adding a node with <kbd>Ctrl</kbd> + <kbd>A</kbd>.

Annotation 2020-07-17 130200

Using a [custom theme](https://github.com/Xrayez/godot-editor-settings), but I think that shouldn't affect the behavior. If it does, that's still a bug which might happen under some theme conditions.

Stumbled upon this one while testing workarounds suggested in godotengine/godot-proposals#1206.

**Steps to reproduce:**
1. Create empty scene.
2. <kbd>Ctrl</kbd> + <kbd>A</kbd>, might need to do this several times.

### LINKED ISSUE #45033: Add child node shortcut (CTRL + A) is not working while the scene dock has been clicked or selected
**Godot version:** 4.0

**OS/device including version:** Windows/ HP Omen 15

**Issue description:** Add child node shortcut (CTRL + A) is pressed while the scene dock has been selected, the add child node button i.e. the '+' button is holding the pressed state and not being released, so it can generate the 'add child node' window.  

**Steps to reproduce:** 1. Click anywhere in the scene dock. Then press (CTRL+A) 

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by reduz**
* Button shortcuts were treated as generic input events on buttons. This means that to activate a button shortcut you had to press and release.
* This logic is removed and now shortcuts always activate on press.
* This makes the editor feel more responsive and solves problems related to this behavior.
* Shortcut feedback is kept, but it is now a timed event after press.

Fixes #45033 and possibly others.
Fixes https://github.com/godotengine/godot/issues/40464.

### CODE REVIEW

**Comment by KoBeWi** [comment]
This basically reverts (or more like supersedes) #71328
You forgot to update the docs btw.

**Comment by EricEzaM** [comment]
Also fixes #40464

**Comment by reduz** [comment]
@KoBeWi I restored shortcut feedback (works a little different now).

File: scene/gui/base_button.cpp [hunk 1]
```diff
@@ -348,13 +353,45 @@ Ref<Shortcut> BaseButton::get_shortcut() const {
...
+			_pressed();
+		}
+		queue_redraw();
 		accept_event();
+
+		if (shortcut_feedback) {
+			if (shortcut_feedback_timer == nullptr) {
+				shortcut_feedback_timer = memnew(Timer);
+				add_child(shortcut_feedback_timer);
+				shortcut_feedback_timer->set_wait_time(0.5);
```
Comment (akien-mga) [inline scene/gui/base_button.cpp:388]: Sounds like this might be a bit long, but we can start with this and see what the user feedback is. I'm sure @Calinou will be happy to tweak this :P

Comment (akien-mga) [reply scene/gui/base_button.cpp:388]: BTW, could also use `SceneTreeTimer` in theory?
Seems like the only place we use it currently in core is for Viewport tooltips.

**Comment by akien-mga** [comment]
Seems good to me.

> Shortcut feedback is kept, but it is now a timed event after press.

I foresee potential requests to make the timer configurable... but we can see first if we can get away with a reasonable default. I guess we can also add a project setting for it eventually if there's demand.

**Comment by reduz** [comment]
@akien-mga made the timer configurable as a project setting

File: scene/gui/base_button.cpp (hunk 1 above)
Comment (reduz) [reply scene/gui/base_button.cpp]: I prefer the `Timer` node for this myself because you can restart it more easily, so you "push it back" instead of creating another one.

File: scene/gui/base_button.cpp [hunk 2]
```diff
@@ -466,6 +495,9 @@ void BaseButton::_bind_methods() {
 
 	BIND_ENUM_CONSTANT(ACTION_MODE_BUTTON_PRESS);
 	BIND_ENUM_CONSTANT(ACTION_MODE_BUTTON_RELEASE);
+
+	GLOBAL_DEF("gui/button/shortcut_feedback_highlight_time", 0.5);
+	ProjectSettings::get_singleton()->set_custom_property_info(PropertyInfo(Variant::FLOAT, "gui/button/shortcut_feedback_highlight_time", PROPERTY_HINT_RANGE, "0.01,10,0.01,suffix:s"));
```
Comment (akien-mga) [inline scene/gui/base_button.cpp:500]: We now have
```
Variant _GLOBAL_DEF(const PropertyInfo &p_info, const Variant &p_default, bool p_restart_if_changed = false, bool p_ignore_value_in_docs = false, bool p_basic = false, bool p_internal = false);
```
so you can group both and avoid the redundant name (merged last week #68429).

```suggestion
	GLOBAL_DEF(PropertyInfo(Variant::FLOAT, "gui/button/shortcut_feedback_highlight_time", PROPERTY_HINT_RANGE, "0.01,10,0.01,suffix:s"), 0.5);
```

Comment (akien-mga) [reply scene/gui/base_button.cpp:500]: And remember to sync the classref / add documentation.

**Comment by KoBeWi** [comment]
I think the default value 0.5 is too long and doesn't look good. Something like 0.2 is better. The button is highlighted for similar time as the shortcut is normally pressed.

File: scene/gui/base_button.cpp (hunk 2 above)
Comment (reduz) [reply scene/gui/base_button.cpp:500]: oooh nice

File: scene/gui/base_button.cpp [hunk 3]
```diff
@@ -348,13 +354,45 @@ Ref<Shortcut> BaseButton::get_shortcut() const {
...
+			_pressed();
+		}
+		queue_redraw();
 		accept_event();
+
+		if (shortcut_feedback) {
+			if (shortcut_feedback_timer == nullptr) {
+				shortcut_feedback_timer = memnew(Timer);
+				add_child(shortcut_feedback_timer);
+				shortcut_feedback_timer->set_wait_time(GLOBAL_GET("gui/button/shortcut_feedback_highlight_time"));
```
[the remark this answers is not in the document]
Comment (reduz) [reply scene/gui/base_button.cpp:389]: It could be done the same as SNAME if needed, I guess. But of course, may be better for another PR.

**Comment by reduz** [comment]
@KoBeWi changed!

**Comment by akien-mga** [comment]
CC @Spartan322 as you had interest in disabling the shortcut feedback (which this still preserves but refactors).

The last question for me is this one:

> Which BTW raises the question of whether folks really want to configure this on a per-button basis, or if a global toggle for shortcut feedback and duration wouldn't be better.

**Comment by KoBeWi** [comment]
Ah yes, another one-element section lol
image

> a global toggle for shortcut feedback and duration wouldn't be better.

It can be easily achieved by setting the highlight time to 0.

File: scene/gui/base_button.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (KoBeWi) [reply scene/gui/base_button.cpp:389]: Or it could be cached in the constructor and updated when project settings change (with #62038).

**Comment by akien-mga** [comment]
> Ah yes, another one-element section lol

Maybe we can move to `gui/timers/`.

**Comment by reduz** [comment]
@KoBeWi done changes!

File: doc/classes/ProjectSettings.xml [hunk 4]
```diff
@@ -699,6 +699,9 @@
 		<member name="filesystem/import/fbx/enabled.web" type="bool" setter="" getter="" default="false">
 			Override for [member filesystem/import/fbx/enabled] on the Web where FBX2glTF can't easily be accessed from Godot.
 		</member>
+		<member name="gui/timers/button_shortcut_feedback_highlight_time" type="float" setter="" getter="" default="0.2">
```
Comment (akien-mga) [inline doc/classes/ProjectSettings.xml:702]: Will fail CI, should be ordered alphabetically.

File: scene/gui/base_button.cpp [hunk 5]
```diff
@@ -267,6 +261,10 @@ BaseButton::DrawMode BaseButton::get_draw_mode() const {
 		return DRAW_DISABLED;
 	}
 
+	if (in_shortcut_feedback) {
```
Comment (KoBeWi) [inline scene/gui/base_button.cpp:264]: This could be replaced by
```suggestion
	if (shortcut_feedback_timer && !shortcut_feedback_timer->is_stopped()) {
```
to avoid extra bool flag, but it's not important I guess.

**Review by KoBeWi — APPROVED** [review]

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
