### PR TITLE
Use distance to AABB surface to calculate Mesh LOD instead of using supports

### LINKED ISSUE #76436: Godot automatic LOD changing (incorrectly) based on the angle of the camera when using MultiMesh
### Godot version

4.0 Mono

### System information

Windows 11

### Issue description

Godot 4 seems to be doing some kind of LOD performance improvement incorrectly.

Here are some screenshots:

image
image
image

Of note but maybe hard to tell from the screenshot alone, this tiny model is roughly at the same distance from the camera for all 3 screenshots - but as the camera rotates the LOD changes as well.

### Steps to reproduce

It is not feasible to provide the entire project, and I am not sure if this will be easily replicable elsewhere. If it is not replicable, I will try to provide further info.
You can have the beautiful flower model, free of charge. I know it's surprising to offer these high quality assets for free, but I feel like it is for a good cause.

### Minimal reproduction project

[flower1.zip](https://github.com/godotengine/godot/files/11322380/flower1.zip)

### LINKED ISSUE #81995: LOD selection implementation is wrong
### Godot version

4.2.dev

### System information

n/a

## Issue

I've just come back to work on a project and I'm certain the LOD selection code is wrong after #67307
I've witnessed LOD selection artifacts even after #79590, and looking at the code changes from #67307 the implementation doesn't make sense.

Example of broken LOD selection viewing a MultiMeshInstance3D:
Viewed from one angle:
image
And with camera rotated just barely, clearly the wrong LOD is used:
image

The problematic code:
https://github.com/godotengine/godot/blame/26c4644b388afb775c0563e7f8d70a3215c1216b/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L947-L967

```cpp
if (!inst->transformed_aabb.has_point(p_render_data->scene_data->cam_transform.origin)) {
	// Get the LOD support points on the mesh AABB.
	Vector3 lod_support_min = inst->transformed_aabb.get_support(p_render_data->scene_data->cam_transform.basis.get_column(Vector3::AXIS_Z));
	Vector3 lod_support_max = inst->transformed_aabb.get_support(-p_render_data->scene_data->cam_transform.basis.get_column(Vector3::AXIS_Z));

	// Get the distances to those points on the AABB from the camera origin.
	float distance_min = (float)p_render_data->scene_data->cam_transform.origin.distance_to(lod_support_min);
	float distance_max = (float)p_render_data->scene_data->cam_transform.origin.distance_to(lod_support_max);

	if (distance_min * distance_max < 0.0) {
		//crossing plane
		distance = 0.0;
	} else if (distance_min >= 0.0) {
		distance = distance_min;
	} else if (distance_max <= 0.0) {
		distance = -distance_max;
	}
}
```

### Implementation flaws

First of all, plainly using vector distance to support points will not work.

There are illogical situations where `distance_min` is greater than `distance_max`:
image

Additionally, `distance_min/max` will *never* be negative when calculated by `Vector3::distance_to`. Therefore the final `distance` will always be equal to `distance_min`, which can be arbitrarily far from the camera for long AABBs despite the mesh being so close to the camera.

**I recommend reverting this code** (I have a branch prepared) before trying to implement a better solution. A better solution may be harder to attain than you would expect (or prove me wrong).

### The purpose of LOD level selection

An ideal LOD selection should maintain optimal visual quality for all parts of the mesh (enforcing `projected triangle size * lod_bias < 1 pixel`). Therefore, you should locate the worst-case geometry on the mesh (the position closest to the camera view plane) and calculate the LOD based on the distance.
(This tracks with the orthogonal case which assigns `distance = 1.0` where the projected size is constant with respect to distance.)

### Identifying the actual problems
The discussion of whether LOD levels should be determined by radial distance or view-normal scalar projection #54885 is motivated by two core problems:
1. a need for frustum culling (if not already implemented)
2. LOD popping in/out with camera rotation

Solving problem 1 involves a different system than LODs, and problem 2 only exists if you decide to change `lod_bias`. The [documentation](https://docs.godotengine.org/en/stable/tutorials/3d/mesh_lod.html) suggests modifying the bias for performance, but I believe other approaches should take priority (mesh optimization, base model quality, etc.), otherwise LOD popping is completely unavoidable without implementing an independent solution. Even if rotational consistency is achieved, LODs will still pop in/out as the camera translates. This is the wrong place to solve the problem.

### Possible approach for rotationally-consistent LOD level selection

If we _need_ the marginal quality improvements from achieving rotational consistency, some notes:

1. Calculate shortest distance between AABB surface and the camera near plane (this is possibly non-trivial)
2. `distance *= 1.0 / cos(camera FOV angle from screen center to corner)` to make sure that LOD is high enough to ensure `projected triangle size * lod_bias < 1 pixel` is enforced in the corners of the screen

### Steps to reproduce

-

### Minimal reproduction project

-

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/81995
Fixes: https://github.com/godotengine/godot/issues/76436

Supersedes https://github.com/godotengine/godot/pull/82000

Builds on https://github.com/godotengine/godot/pull/92287 but introduces riskier changes. 

This PR simplifies and improves the LOD selection logic by calculating the depth as the distance to the closest point on the surface of the AABB.

The old logic used the camera z direction to calculate the min and max supports. This was flawed as it meant that rotating the camera could drastically change which supports were chosen and (as pointed out in https://github.com/godotengine/godot/issues/81995) if the camera looked slightly past an AABB, it could cause the supports to change and then jump LOD levels.

The new code automatically handles being inside the AABB (distance will always be 0 inside the AABB) and gradually increases from 0 at the surface of the AABB so there is no snapping like with the first draft of this PR.

I also moved the entire calculation outside the loop since everything depends on the instance. It doesn't need to be recalculated for each surface.

### CODE REVIEW

**Comment by huwpascoe** [comment]
Linking the MRP I created for testing LOD since it's quite useful:

[multimesh_lod_mrp.zip](https://github.com/user-attachments/files/16710877/multimesh_lod_mrp.zip)

image

**Review by Calinou — COMMENTED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/568589c9d8c763bfb3a4348174d53b42d7c59f21), it doesn't seem to work as expected with @huwpascoe's MRP. I still get sudden unexpected LOD level changes when the camera moves at certain positions (e.g. going from a low LOD level to full resolution LOD instantly).

Also, in general, the LOD level regularly decreases even though my camera is getting *closer* to the MultiMeshInstance3D's center, which doesn't make sense to me.

### `master`

https://github.com/user-attachments/assets/c2222cee-22a8-485a-bae5-5f57bd524111

### This PR

https://github.com/user-attachments/assets/5766c7bb-cc4e-4d21-81ab-cb5c3a500e9f

This makes me wonder if the full resolution LOD should always be used if the camera's AABB is inside the MultiMeshInstance's AABB. This will be slower, but it ensures one instance from the MultiMeshInstance3D will never look bad if it's right in front of you, no matter how isolated it is from the rest (or whether it's near the edges or at the center of the MultiMeshInstance3D).

A less extreme approach could be to clamp the LOD selection for MultiMeshInstance3Ds when the camera is inside its bounds (e.g. use only the two most detailed LOD levels to avoid too much discrepancy).

**Comment by clayjohn** [comment]
> This makes me wonder if the full resolution LOD should always be used if the camera's AABB is inside the MultiMeshInstance's AABB. This will be slower, but it ensures one instance from the MultiMeshInstance3D will never look bad if it's right in front of you, no matter how isolated it is from the rest (or whether it's near the edges or at the center of the MultiMeshInstance3D).

That's how the PR currently works. If the camera is inside the AABB then the most detailed LOD is always used. 

Do you know if the AABB in this MRP actually covers all the instances? Depending on how it was created it might not fit the instances very well

**Comment by huwpascoe** [comment]
> Do you know if the AABB in this MRP actually covers all the instances? Depending on how it was created it might not fit the instances very well

Well it's just the automatic AABB that's generated with the multimesh?
image

**Comment by huwpascoe** [comment]
Found an algorithm:
```glsl
float aabb_dist(vec3 p_point, vec3 p_min, vec3 p_max) {
    float dist_sq = 0.0;

    for (int i = 0; i < 3; ++i) {
        if (p_point[i] < p_min[i]) {
            float d = p_point[i] - p_min[i];
            dist_sq += d * d;
        }
        else if (p_point[i] > p_max[i]) {
            float d = p_point[i] - p_max[i];
            dist_sq += d * d;
        }
    }

    return sqrt(dist_sq);
}
```
Can probably replace that entire section, certainly reduces the number of conditionals. Could go one further and store LOD keys as distance squared and avoid the sqrt.

**Comment by huwpascoe** [comment]
Regarding comments in the meeting:

- AABB does in fact store coordinates in a min max format. Only it's called position and size respectively.
- The sqrt is correct because of how vector3.length is calculated `length = sqrt(x*x+y*y+z*z)`, the sqrt can be deferred to the sum of all the lengths
- The sqrt can be avoided entirely if the LOD keys are also stored in squared form, but that's at @clayjohn's discretion.

Yes the algorithm seems to work as advertised.
https://gist.github.com/huwpascoe/6d8beba40cec02f4967a2aac33eef92a
image

**Comment by clayjohn** [comment]
Pushed an update with calculation to surface of the AABB instead of using the support. 

I didn't use the formula from [huwpascoe](https://github.com/huwpascoe), but instead used one that does the same thing mathematically but is branchless. 

Overall, the number of calculations are significantly **reduced** from the previous state and the results are much more accurate. 

I think this is ready for merging now. I have tested it with a few MRPs from previous issues and it appears to work the same or better in all cases.

**Comment by huwpascoe** [comment]
Can confirm it works, entirely consistent with distance to the AABB!

image
<sub>Moved the control to the corner of the multimesh AABB for the distances to match</sub>

**Review by akien-mga — APPROVED** [review]

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 1]
```diff
@@ -1363,38 +1363,25 @@ void RasterizerSceneGLES3::_fill_render_list(RenderListType p_render_list, const
...
 
+		float lod_distance = 0.0;
+
+		if (p_render_data->cam_orthogonal) {
+			lod_distance = 1.0;
+		} else {
+			Vector3 aabb_min = inst->transformed_aabb.position;
+			Vector3 aabb_max = inst->transformed_aabb.position + inst->transformed_aabb.size;
+			Vector3 camera_position = p_render_data->main_cam_transform.origin;
+			Vector3 surface_distance = Vector3(0.0, 0.0, 0.0).max(aabb_min - camera_position).max(camera_position - aabb_max);
```
Comment (AThousandShips) [inline drivers/gles3/rasterizer_scene_gles3.cpp:1374]:
```suggestion
			Vector3 surface_distance = (aabb_min - camera_position).max(camera_position - aabb_max).maxf(0.0);
```
Equivalent

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 2]
```diff
@@ -962,40 +962,27 @@ void RenderForwardClustered::_fill_render_list(RenderListType p_render_list, con
...
 
+		float lod_distance = 0.0;
+
+		if (p_render_data->scene_data->cam_orthogonal) {
+			lod_distance = 1.0;
+		} else {
+			Vector3 aabb_min = inst->transformed_aabb.position;
+			Vector3 aabb_max = inst->transformed_aabb.position + inst->transformed_aabb.size;
+			Vector3 camera_position = p_render_data->scene_data->main_cam_transform.origin;
+			Vector3 surface_distance = Vector3(0.0, 0.0, 0.0).max(aabb_min - camera_position).max(camera_position - aabb_max);
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:973]:
```suggestion
			Vector3 surface_distance = (aabb_min - camera_position).max(camera_position - aabb_max).maxf(0.0);
```

File: servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp [hunk 3]
```diff
@@ -1884,39 +1884,27 @@ void RenderForwardMobile::_fill_render_list(RenderListType p_render_list, const
...
 
+		float lod_distance = 0.0;
+
+		if (p_render_data->scene_data->cam_orthogonal) {
+			lod_distance = 1.0;
+		} else {
+			Vector3 aabb_min = inst->transformed_aabb.position;
+			Vector3 aabb_max = inst->transformed_aabb.position + inst->transformed_aabb.size;
+			Vector3 camera_position = p_render_data->scene_data->main_cam_transform.origin;
+			Vector3 surface_distance = Vector3(0.0, 0.0, 0.0).max(aabb_min - camera_position).max(camera_position - aabb_max);
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:1895]:
```suggestion
			Vector3 surface_distance = (aabb_min - camera_position).max(camera_position - aabb_max).maxf(0.0);
```

File: drivers/gles3/rasterizer_scene_gles3.cpp (hunk 1 above)
Comment (clayjohn) [reply drivers/gles3/rasterizer_scene_gles3.cpp:1374]: I prefer it the way it was. The code is much clearer that way

**Comment by akien-mga** [comment]
Thanks!
