### PR TITLE
Fix wrong size on `Container` nodes due to late cache update

### LINKED ISSUE #109497: HBoxContainer child not positioned correctly due to container visibility
### Tested versions

Reproducible in v4.4.1.stable.mono.official [49a5bc7b6] and v4.5.beta5.mono.official [c81fd6c51]

### System information

Godot v4.4.1.stable.mono - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.7680) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 threads)

### Issue description

When a child of an HBoxContainer is removed while the container is hidden and then re-added after showing the container it is positioned incorrectly. It should be noted that the container is anchored to the bottom center.

### Steps to reproduce

- Run the minimal reproduction project
- Press ui_right to show the container and add a button child. This looks correct
- Press ui_left to hide the container and remove the child
- Press ui_right again to show the container and add a button again. It now looks incorrect

### Minimal reproduction project (MRP)

[h-box-test.zip](https://github.com/user-attachments/files/21706633/h-box-test.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #109497.

Partially reverses #115041, as this was also the root cause.

### CODE REVIEW

**Comment by kitbdev** [comment]
It looks like the issue is when Controls are not visible, their minimum sizes are not updated, not that it updates too late. Specifically the `data.last_minimum_size` isn't updated, which makes the check in `Control::_update_minimum_size()` fail when it is called when visible with children.

Rather than putting it in `Control::get_combined_minimum_size()` which is exposed and could be called from anywhere with side effects, it could just be where it is called in `Control::_update_minimum_size()`, and then there isn't a need for an `updating_size` flag. Like:
```c++
void Control::_update_minimum_size() {
	if (!is_inside_tree()) {
		data.updating_last_minimum_size = false;
		return;
	}

	bool was_invalid = !data.minimum_size_valid;
	Size2 minsize = get_combined_minimum_size();
	data.updating_last_minimum_size = false;

	if (was_invalid || minsize != data.last_minimum_size) {
```

Or we could remove the `is_visible_in_tree` check from `Control::update_minimum_size()`. This would also make the `minimum_size_changed` able to emit when not visible.

Also looks related to https://github.com/godotengine/godot/pull/78009#issuecomment-1584477539

File: scene/gui/control.h [hunk 1]
```diff
@@ -216,6 +216,7 @@ class Control : public CanvasItem {
 
 		Point2 pos_cache;
 		Size2 size_cache;
+		bool updating_size = false;
```
Comment (kitbdev) [inline scene/gui/control.h]: No longer checked, can be removed.

**Review by kitbdev — APPROVED** [review]
Fixes the issue, looks good to me.
I also confirmed that it does not bring back https://github.com/godotengine/godot/issues/114757

**Comment by KoBeWi** [comment]
The `!is_visible_in_tree()` check dates back to 005b69cf6e276209464cc8c36ebc7376679925b6. While I don't know its original purpose, it prevents Controls from updating their size while invisible (which is nice, because their size is irrelevant until they appear). The size is updated when they become visible:
https://github.com/godotengine/godot/blob/3c5e561024b2aeee7494e675fbed4724dd216fe2/scene/gui/control.cpp#L3974-L3976
So I guess the problem is that the order of updates is wrong when visibility is propagated. Is there no other way to fix it? If no, or it's not feasible right now, then removing this check is fine. However it might make things a bit slower due to extraneous updates (not sure how much significant impact it may have).

**Review by KoBeWi — APPROVED** [review]
