### PR TITLE
Fix script backtrace reporting wrong line numbers in release exports

### LINKED ISSUE #106484: Script backtraces report incorrect line numbers in release exports
### Tested versions

- Reproducible in c3ae6aa10b1c0c5488cf5b5e82dd34d265c1567c (4.5-dev4+)

### System information

Windows 10.0.20348, macOS 15.4.1

### Issue description

In release exports, capturing script backtraces reports incorrect line numbers for GDScript, always pointing to the function signature. Backtraces in release builds can be enabled with `always_track_call_stacks` in the project setting.

Related PR:
- https://github.com/godotengine/godot/pull/91006

### Detailed explanation

Consider this code:

Image

Using `editor` build:
```
debug build: true
entering f1()
entering f2()
entering f3()
GDScript backtrace (most recent call first):
    [0] f3 (res://main.gd:21)
    [1] f2 (res://main.gd:16)
    [2] f1 (res://main.gd:11)
    [3] _ready (res://main.gd:6)
```

Using `tempate_release` build:
```
debug build: false
entering f1()
entering f2()
entering f3()
GDScript backtrace (most recent call first):
    [0] f3 (res://main.gd:19)
    [1] f2 (res://main.gd:14)
    [2] f1 (res://main.gd:9)
    [3] _ready (res://main.gd:4)
```

Note how frame line numbers are pointing to the function signatures when running with a release template build.

#### The problem manifesting in `sentry-godot` GDExtension:

Script stack trace produced using `editor` build:
script-stack-trace-editor

Script stack trace produced using `template_release` build:
script-stack-trace-release

### Steps to reproduce

Run MRP using `editor` build and then using `template_release` build. Compare the console outputs.

### Minimal reproduction project (MRP)

[reproduce-release-backtrace-issue.zip](https://github.com/user-attachments/files/20241955/reproduce-release-backtrace-issue.zip)

### PR DESCRIPTION
**Pull request by limbonaut**
In release exports, capturing script backtraces reports incorrect line numbers in GDScript, always pointing to the function signature. This PR fixes it by enabling adding line opcodes for projects with `always_track_call_stacks` enabled in the project setting.

Resolves #106484

Related PR:
- https://github.com/godotengine/godot/pull/91006

cc @mihe

### CODE REVIEW

**Comment by mihe** [comment]
Does this happen to resolve the [weird line numbers](https://github.com/godotengine/godot/pull/91006#pullrequestreview-2788548486) you were seeing with coroutines as well?

**Comment by limbonaut** [comment]
@mihe I forgot about that one. Just checked -- it doesn't. I think it's different issues. I'll make a reproduction project and open a separate issue.

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -1903,10 +1903,11 @@ Error GDScriptCompiler::_parse_block(CodeGen &codegen, const GDScriptParser::Sui
...
 		const GDScriptParser::Node *s = p_block->statements[i];
 
-#ifdef DEBUG_ENABLED
-		// Add a newline before each statement, since the debugger needs those.
-		gen->write_newline(s->start_line);
-#endif
+		if (enable_newline) {
+			// Add a newline before each statement, since the debugger needs those.
+			// Also needed when tracking call stacks is enabled in the project settings.
+			gen->write_newline(s->start_line);
```
Comment (dalexeev) [inline modules/gdscript/gdscript_compiler.cpp:1909]: This isn't the only call to `write_newline()`, so I'd recommend moving the condition inside the `write_newline()` and removing the `#ifdef`s at the call sites. You should also move `enable_newline` to `GDScriptByteCodeGenerator`, near [`debug_stack`](https://github.com/godotengine/godot/blob/a12e9d5c3180a57364f419beb6a1b411bc28161d/modules/gdscript/gdscript_byte_codegen.h#L77), since it serves a similar purpose.

```
10 matches
modules/gdscript/gdscript_byte_codegen.cpp: 1
1764: 33: void GDScriptByteCodeGenerator::write_newline(int p_line) {
modules/gdscript/gdscript_byte_codegen.h: 1
548: 15: 	virtual void write_newline(int p_line) override;
modules/gdscript/gdscript_codegen.h: 1
161: 15: 	virtual void write_newline(int p_line) = 0;
modules/gdscript/gdscript_compiler.cpp: 7
1908:  8: 		gen->write_newline(s->start_line);
1960: 11: 					gen->write_newline(branch->start_line);
2341: 24: 				codegen.generator->write_newline(field->start_line);
2376: 24: 				codegen.generator->write_newline(field->initializer->start_line);
2536: 23: 			codegen.generator->write_newline(field->start_line);
2571: 23: 			codegen.generator->write_newline(field->initializer->start_line);
2597: 22: 		codegen.generator->write_newline(p_class->start_line);
```

Comment (limbonaut) [reply modules/gdscript/gdscript_compiler.cpp]: Good points -- updated accordingly.

File: modules/gdscript/gdscript_compiler.cpp [hunk 2]
```diff
@@ -1955,10 +1954,9 @@ Error GDScriptCompiler::_parse_block(CodeGen &codegen, const GDScriptParser::Sui
 					// Add locals in block before patterns, so temporaries don't use the stack address for binds.
 					List<GDScriptCodeGenerator::Address> branch_locals = _add_block_locals(codegen, branch->block);
 
-#ifdef DEBUG_ENABLED
 					// Add a newline before each branch, since the debugger needs those.
```
Comment (dalexeev) [inline modules/gdscript/gdscript_compiler.cpp:1957]:
```suggestion
					// Add a newline before each branch, since the debugger needs those.
					// Also needed when tracking call stacks is enabled in the project settings.
```

Or remove both comments since we don't add them to every `write_newline()` call.

File: modules/gdscript/gdscript_byte_codegen.cpp [hunk 3]
```diff
@@ -162,6 +162,7 @@ void GDScriptByteCodeGenerator::end_parameters() {
 void GDScriptByteCodeGenerator::write_start(GDScript *p_script, const StringName &p_function_name, bool p_static, Variant p_rpc_config, const GDScriptDataType &p_return_type) {
 	function = memnew(GDScriptFunction);
 	debug_stack = GDScriptLanguage::get_singleton()->should_track_locals();
+	enable_newline = GDScriptLanguage::get_singleton()->should_track_call_stack();
```
Comment (dalexeev) [inline modules/gdscript/gdscript_byte_codegen.cpp:165]: I'd rename `enable_newline` and `debug_stack` to `track_call_stack` and `track_locals` for consistency, like in `GDScriptLanguage` (or we could call these methods directly in the code generator). Especially given the potential confusion that `should_track_call_stack()` corresponds to `enable_newline` rather than `debug_stack`.

**Review by dalexeev — COMMENTED** [review]
Looks good to me, just a few nitpicks on the code style.

**Comment by limbonaut** [comment]
I removed both `debug_stack` and `enable_newline` variables in favor of direct function calls and shortened the comments to one-liners, adding them to all call sites. If that's excessive, I can move the comment to `write_newline()` function and remove it from the call sites.

**Review by dalexeev — APPROVED** [review]
> I can move the comment to `write_newline()` function and remove it from the call sites.

I think it would be better, no need to repeat the same phrase.

**Comment by Repiteo** [comment]
Thanks!
