### PR TITLE
Fix error on attaching script

### LINKED ISSUE #37583: Attempt to connect nonexistent signal 'popup_hide' to 'SceneTreeDock::_script_creation_closed'.
**Godot version:**
4.0.dev.custom_build. 1957c99ab
**OS/device including version:**
Ubuntu 19.10
**Issue description:**

```
ERROR: Signal 'script_created' is already connected to given callable 'SceneTreeDock::_script_created' in that object.
   at: connect (core/object.cpp:1462)
ERROR: In Object of type 'ScriptCreateDialog': Attempt to connect nonexistent signal 'popup_hide' to callable 'SceneTreeDock::_script_creation_closed'.
   at: connect (core/object.cpp:1449)

```
**Steps to reproduce:**
jfile

### PR DESCRIPTION
**Pull request by groud**
Closes #37583

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -2628,9 +2624,6 @@ void SceneTreeDock::attach_script_to_selected(bool p_extend) {
 		}
 	}
 
-	script_create_dialog->connect("script_created", callable_mp(this, &SceneTreeDock::_script_created));
-	script_create_dialog->connect("popup_hide", callable_mp(this, &SceneTreeDock::_script_creation_closed), varray(), CONNECT_ONESHOT);
-	script_create_dialog->set_inheritance_base_type("Node");
```
Comment (akien-mga) [inline editor/scene_tree_dock.cpp:2633]: Are you sure that this one is unnecessary? I assume it was put here to reset things which might have been modified in the Create New Script variant of this dialog.

**Comment by akien-mga** [comment]
Make sure to test thoroughly as IIRC this convoluted connect/disconnect logic was to enable reusing the same dialog for both the "Create New Script" and "Attach Script" functions.

If both seem to work fine, that's all good.

File: editor/scene_tree_dock.cpp (hunk 1 above)
Comment (groud) [reply editor/scene_tree_dock.cpp:2633]: This only thing it did was to disconnect the "script_created" signal. I believe this was added originally only to avoid the "signal already connected" message, because I see no other reason to disconnect this signal otherwise.

Since now the signal connection is done once and not every time the attach_script_to_selected function is ran, I see no reason to keep this.

Comment (akien-mga) [reply editor/scene_tree_dock.cpp:2633]: I meant the `set_inheritance_base_type` specifically.

**Comment by groud** [comment]
Ah damn, you are right, this requires more testing. It seems that I did not see the getter used to retrieve the script_create_dialog variable. So I assumed it could not be used elsewhere... I don't see why we need to reuse the same dialog though, maybe another one might be created I guess.

That being said, it also looks like this vairiable is expose via get_script_create_dialog() into EditorPlugin. I don't really see the point there, maybe it's used somewhere to add something? That's really weird...

**Comment by groud** [comment]
Alright, I updated the PR with a simpler fix. It would be good to someday refactor all of this but it needs more work.
I believe that if the ScriptEditorDialog has to be shared, it should likely be moved into EditorNode, instead of the scene tree dock.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
