### PR TITLE
Fix auto-complete not suggesting custom class names on identifiers

### LINKED ISSUE #69941: Autocomplete does not suggest custom class names
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10

### Issue description

Autocomplete will no longer complete custom class names defined with `class_name`.

Godot 3.5.1
image

Godot 4.0 beta8
image

### Steps to reproduce

1. Create `custom_class.gd`
```gdscript
class_name CustomClass extends Node
```

2. Create `main.gd`
```gdscript
extends Node

func _ready():
	Custo
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by poohcom1**
Fixes #69941

In 4.x, auto-complete will suggest custom classes only when completing types, not identifiers. This makes it auto-complete for identifiers as well, as this was the behavior in 3.x.

image

image

### CODE REVIEW

**Comment by adamscott** [comment]
CC @anvilfolk

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -1271,6 +1271,14 @@ static void _find_identifiers(const GDScriptParser::CompletionContext &p_context
 		}
 		r_result.insert(option.display, option);
 	}
+
+	// Global scripts
```
Comment (adamscott) [inline modules/gdscript/gdscript_editor.cpp:1275]: I would change this comment to `// Global classes`, but it's a small nitpick.

**Review by adamscott — APPROVED** [review]
LGTM.

File: modules/gdscript/gdscript_editor.cpp (hunk 1 above)
Comment (poohcom1) [reply modules/gdscript/gdscript_editor.cpp:1275]: Yeah I agree; I'll update it now

**Review by vnen — APPROVED** [review]

**Comment by vnen** [comment]
Thanks!
