### PR TITLE
Apply additional fixes to servers' threading

### LINKED ISSUE #87382: Memory leaks with multithreading
### Tested versions

4.3.dev.custom_build. 7827c8e37

### System information

Ubuntu 22.04 CI Lavapipe

### Issue description

Headless
```
extends Node
func _process(delta):
	var temp_variable40299 = RandomNumberGenerator.new()
	temp_variable40299.get_class()
```
cause leak
```
Godot Engine v4.3.dev.custom_build.7827c8e37 - https://godotengine.org
WARNING: The Multi-Threaded rendering thread model is experimental, and has known issues which can lead to project crashes. Use the Single-Safe option in the project settings instead.
     at: setup2 (main/main.cpp:2498)
WARNING: Rendering thread not supported by this display server.
     at: release_rendering_thread (servers/display_server.cpp:566)
WARNING: Rendering thread not supported by this display server.
     at: make_rendering_thread (servers/display_server.cpp:570)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2204)
=================================================================
==18483==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 65552 byte(s) in 1 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x558202a5128a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x55820300f6b5 in String::resize(int) core/string/ustring.h:218
    #4 0x558212c086ac in ShaderPreprocessor::vector_to_string(LocalVector<char32_t, unsigned int, false, false> const&, int, int) servers/rendering/shader_preprocessor.cpp:361
    #5 0x558212c1e766 in ShaderPreprocessor::preprocess(ShaderPreprocessor::State*, String const&, String&) servers/rendering/shader_preprocessor.cpp:1299
    #6 0x558212c1ec23 in ShaderPreprocessor::preprocess(String const&, String const&, String&, String*, List<ShaderPreprocessor::FilePosition, DefaultAllocator>*, List<ShaderPreprocessor::Region, DefaultAllocator>*, HashSet<Ref<ShaderInclude>, HashMapHasherDefault, HashMapComparatorDefault<Ref<ShaderInclude> > >*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, void (*)(List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*)) servers/rendering/shader_preprocessor.cpp:1310
    #7 0x55820ff04600 in Shader::set_code(String const&) scene/resources/shader.cpp:82
    #8 0x55820bb85879 in ColorPicker::init_shaders() scene/gui/color_picker.cpp:191
    #9 0x55820adc1eb5 in register_scene_types() scene/register_scene_types.cpp:1188
    #10 0x5581fcc38749 in Main::setup2() main/main.cpp:2810
    #11 0x5581fcc258dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #12 0x5581fc93baac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #13 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Direct leak of 40848 byte(s) in 74 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x558216005a92 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x558211024af4 in generate_icon scene/theme/default_theme.cpp:83
    #4 0x55821102be80 in fill_default_theme(Ref<Theme>&, Ref<Font> const&, Ref<Font> const&, Ref<Font> const&, Ref<Font> const&, Ref<Texture2D>&, Ref<StyleBox>&, float) scene/theme/default_theme.cpp:145
    #5 0x5582110a9741 in make_default_theme(float, Ref<Font>, TextServer::SubpixelPositioning, TextServer::Hinting, TextServer::FontAntialiasing, bool, bool) scene/theme/default_theme.cpp:1236
    #6 0x558210fb75af in ThemeDB::initialize_theme() scene/theme/theme_db.cpp:89
    #7 0x5581fcc3b1a9 in Main::setup2() main/main.cpp:2881
    #8 0x5581fcc258dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #9 0x5581fc93baac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #10 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Direct leak of 4112 byte(s) in 1 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x558202a5128a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x55820300f6b5 in String::resize(int) core/string/ustring.h:218
    #4 0x558212c086ac in ShaderPreprocessor::vector_to_string(LocalVector<char32_t, unsigned int, false, false> const&, int, int) servers/rendering/shader_preprocessor.cpp:361
    #5 0x558212c1e766 in ShaderPreprocessor::preprocess(ShaderPreprocessor::State*, String const&, String&) servers/rendering/shader_preprocessor.cpp:1299
    #6 0x558212c1ec23 in ShaderPreprocessor::preprocess(String const&, String const&, String&, String*, List<ShaderPreprocessor::FilePosition, DefaultAllocator>*, List<ShaderPreprocessor::Region, DefaultAllocator>*, HashSet<Ref<ShaderInclude>, HashMapHasherDefault, HashMapComparatorDefault<Ref<ShaderInclude> > >*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, void (*)(List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*)) servers/rendering/shader_preprocessor.cpp:1310
    #7 0x55820ff04600 in Shader::set_code(String const&) scene/resources/shader.cpp:82
    #8 0x55820bb85678 in ColorPicker::init_shaders() scene/gui/color_picker.cpp:166
    #9 0x55820adc1eb5 in register_scene_types() scene/register_scene_types.cpp:1188
    #10 0x5581fcc38749 in Main::setup2() main/main.cpp:2810
    #11 0x5581fcc258dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #12 0x5581fc93baac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #13 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Direct leak of 4112 byte(s) in 1 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x558202a5128a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x55820300f6b5 in String::resize(int) core/string/ustring.h:218
    #4 0x558212c086ac in ShaderPreprocessor::vector_to_string(LocalVector<char32_t, unsigned int, false, false> const&, int, int) servers/rendering/shader_preprocessor.cpp:361
    #5 0x558212c1e766 in ShaderPreprocessor::preprocess(ShaderPreprocessor::State*, String const&, String&) servers/rendering/shader_preprocessor.cpp:1299
    #6 0x558212c1ec23 in ShaderPreprocessor::preprocess(String const&, String const&, String&, String*, List<ShaderPreprocessor::FilePosition, DefaultAllocator>*, List<ShaderPreprocessor::Region, DefaultAllocator>*, HashSet<Ref<ShaderInclude>, HashMapHasherDefault, HashMapComparatorDefault<Ref<ShaderInclude> > >*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, void (*)(List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*)) servers/rendering/shader_preprocessor.cpp:1310
    #7 0x55820ff04600 in Shader::set_code(String const&) scene/resources/shader.cpp:82
    #8 0x55820bb854e5 in ColorPicker::init_shaders() scene/gui/color_picker.cpp:142
    #9 0x55820adc1eb5 in register_scene_types() scene/register_scene_types.cpp:1188
    #10 0x5581fcc38749 in Main::setup2() main/main.cpp:2810
    #11 0x5581fcc258dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #12 0x5581fc93baac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #13 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Direct leak of 2064 byte(s) in 1 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x558202a5128a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x55820300f6b5 in String::resize(int) core/string/ustring.h:218
    #4 0x558212c086ac in ShaderPreprocessor::vector_to_string(LocalVector<char32_t, unsigned int, false, false> const&, int, int) servers/rendering/shader_preprocessor.cpp:361
    #5 0x558212c1e766 in ShaderPreprocessor::preprocess(ShaderPreprocessor::State*, String const&, String&) servers/rendering/shader_preprocessor.cpp:1299
    #6 0x558212c1ec23 in ShaderPreprocessor::preprocess(String const&, String const&, String&, String*, List<ShaderPreprocessor::FilePosition, DefaultAllocator>*, List<ShaderPreprocessor::Region, DefaultAllocator>*, HashSet<Ref<ShaderInclude>, HashMapHasherDefault, HashMapComparatorDefault<Ref<ShaderInclude> > >*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, void (*)(List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*)) servers/rendering/shader_preprocessor.cpp:1310
    #7 0x55820ff04600 in Shader::set_code(String const&) scene/resources/shader.cpp:82
    #8 0x55820bf65e8f in GraphEdit::init_shaders() scene/gui/graph_edit.cpp:220
    #9 0x55820adc1eba in register_scene_types() scene/register_scene_types.cpp:1189
    #10 0x5581fcc38749 in Main::setup2() main/main.cpp:2810
    #11 0x5581fcc258dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #12 0x5581fc93baac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #13 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Direct leak of 1104 byte(s) in 2 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x558216005a92 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x5581fcabff63 in Ref<Image>::instantiate() core/object/ref_counted.h:216
    #4 0x55820f624a36 in GradientTexture2D::_update() scene/resources/gradient_texture.cpp:235
    #5 0x55820f62ff13 in GradientTexture2D::update_now() scene/resources/gradient_texture.cpp:416
    #6 0x55820f658ba2 in void call_with_variant_args_helper<GradientTexture2D>(GradientTexture2D*, void (GradientTexture2D::*)(), Variant const**, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:303
    #7 0x55820f653302 in void call_with_variant_args<GradientTexture2D>(GradientTexture2D*, void (GradientTexture2D::*)(), Variant const**, int, Callable::CallError&) core/variant/binder_common.h:417
    #8 0x55820f64d260 in CallableCustomMethodPointer<GradientTexture2D>::call(Variant const**, int, Variant&, Callable::CallError&) const core/object/callable_method_pointer.h:98
    #9 0x558216ca3718 in Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const core/variant/callable.cpp:56
    #10 0x55821798bde5 in CallQueue::_call_function(Callable const&, Variant const*, int, bool) core/object/message_queue.cpp:221
    #11 0x55821798fdbe in CallQueue::flush() core/object/message_queue.cpp:326
    #12 0x55820b4426a3 in SceneTree::physics_process(double) scene/main/scene_tree.cpp:471
    #13 0x5581fcc57ca0 in Main::iteration() main/main.cpp:3752
    #14 0x5581fc95d6e9 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #15 0x5581fc93bc8b in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #16 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Indirect leak of 83104 byte(s) in 74 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x5581fcae4bfe in Error CowData<unsigned char>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x5581fcac07b1 in Vector<unsigned char>::resize(int) core/templates/vector.h:94
    #4 0x558202cf677c in ImageLoaderSVG::create_image_from_utf8_buffer(Ref<Image>, unsigned char const*, int, float, bool) modules/svg/image_loader_svg.cpp:135
    #5 0x558202cf6fa1 in ImageLoaderSVG::create_image_from_utf8_buffer(Ref<Image>, Vector<unsigned char> const&, float, bool) modules/svg/image_loader_svg.cpp:156
    #6 0x558202cf737b in ImageLoaderSVG::create_image_from_string(Ref<Image>, String, float, bool, HashMap<Color, Color, HashMapHasherDefault, HashMapComparatorDefault<Color>, DefaultTypedAllocator<HashMapElement<Color, Color> > > const&) modules/svg/image_loader_svg.cpp:168
    #7 0x558211024e71 in generate_icon scene/theme/default_theme.cpp:91
    #8 0x55821102be80 in fill_default_theme(Ref<Theme>&, Ref<Font> const&, Ref<Font> const&, Ref<Font> const&, Ref<Font> const&, Ref<Texture2D>&, Ref<StyleBox>&, float) scene/theme/default_theme.cpp:145
    #9 0x5582110a9741 in make_default_theme(float, Ref<Font>, TextServer::SubpixelPositioning, TextServer::Hinting, TextServer::FontAntialiasing, bool, bool) scene/theme/default_theme.cpp:1236
    #10 0x558210fb75af in ThemeDB::initialize_theme() scene/theme/theme_db.cpp:89
    #11 0x5581fcc3b1a9 in Main::setup2() main/main.cpp:2881
    #12 0x5581fcc258dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #13 0x5581fc93baac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #14 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Indirect leak of 65568 byte(s) in 2 object(s) allocated from:
    #0 0x7f98738b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x558216005b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x5581fcae4bfe in Error CowData<unsigned char>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x5581fcac07b1 in Vector<unsigned char>::resize(int) core/templates/vector.h:94
    #4 0x55820f626822 in GradientTexture2D::_update() scene/resources/gradient_texture.cpp:253
    #5 0x55820f62ff13 in GradientTexture2D::update_now() scene/resources/gradient_texture.cpp:416
    #6 0x55820f658ba2 in void call_with_variant_args_helper<GradientTexture2D>(GradientTexture2D*, void (GradientTexture2D::*)(), Variant const**, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:303
    #7 0x55820f653302 in void call_with_variant_args<GradientTexture2D>(GradientTexture2D*, void (GradientTexture2D::*)(), Variant const**, int, Callable::CallError&) core/variant/binder_common.h:417
    #8 0x55820f64d260 in CallableCustomMethodPointer<GradientTexture2D>::call(Variant const**, int, Variant&, Callable::CallError&) const core/object/callable_method_pointer.h:98
    #9 0x558216ca3718 in Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const core/variant/callable.cpp:56
    #10 0x55821798bde5 in CallQueue::_call_function(Callable const&, Variant const*, int, bool) core/object/message_queue.cpp:221
    #11 0x55821798fdbe in CallQueue::flush() core/object/message_queue.cpp:326
    #12 0x55820b4426a3 in SceneTree::physics_process(double) scene/main/scene_tree.cpp:471
    #13 0x5581fcc57ca0 in Main::iteration() main/main.cpp:3752
    #14 0x5581fc95d6e9 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #15 0x5581fc93bc8b in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #16 0x7f9872c29d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
SUMMARY: AddressSanitizer: 266464 byte(s) leaked in 156 allocation(s).
```

Vulkan
```
Godot Engine v4.3.dev.custom_build.7827c8e37 - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 108370614997504
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	terminator_CreateInstance: Failed to CreateInstance in ICD 4.  Skipping ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 108370614997504
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
Vulkan API 1.3.255 - Forward Mobile - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.7, 256 bits)
WARNING: Invalid/corrupt pipelines cache.
     at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:2209)
WARNING: The Multi-Threaded rendering thread model is experimental, and has known issues which can lead to project crashes. Use the Single-Safe option in the project settings instead.
     at: setup2 (main/main.cpp:2498)
=================================================================
==20704==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 65552 byte(s) in 1 object(s) allocated from:
    #0 0x7f52afcb4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55cf50a6fb81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x55cf3d4bb28a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x55cf3da796b5 in String::resize(int) core/string/ustring.h:218
    #4 0x55cf4d6726ac in ShaderPreprocessor::vector_to_string(LocalVector<char32_t, unsigned int, false, false> const&, int, int) servers/rendering/shader_preprocessor.cpp:361
    #5 0x55cf4d688766 in ShaderPreprocessor::preprocess(ShaderPreprocessor::State*, String const&, String&) servers/rendering/shader_preprocessor.cpp:1299
    #6 0x55cf4d688c23 in ShaderPreprocessor::preprocess(String const&, String const&, String&, String*, List<ShaderPreprocessor::FilePosition, DefaultAllocator>*, List<ShaderPreprocessor::Region, DefaultAllocator>*, HashSet<Ref<ShaderInclude>, HashMapHasherDefault, HashMapComparatorDefault<Ref<ShaderInclude> > >*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, void (*)(List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*)) servers/rendering/shader_preprocessor.cpp:1310
    #7 0x55cf4a96e600 in Shader::set_code(String const&) scene/resources/shader.cpp:82
    #8 0x55cf465ef879 in ColorPicker::init_shaders() scene/gui/color_picker.cpp:191
    #9 0x55cf4582beb5 in register_scene_types() scene/register_scene_types.cpp:1188
    #10 0x55cf376a2749 in Main::setup2() main/main.cpp:2810
    #11 0x55cf3768f8dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #12 0x55cf373a5aac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #13 0x7f52af029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Direct leak of 4112 byte(s) in 1 object(s) allocated from:
    #0 0x7f52afcb4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55cf50a6fb81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x55cf3d4bb28a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x55cf3da796b5 in String::resize(int) core/string/ustring.h:218
    #4 0x55cf4d6726ac in ShaderPreprocessor::vector_to_string(LocalVector<char32_t, unsigned int, false, false> const&, int, int) servers/rendering/shader_preprocessor.cpp:361
    #5 0x55cf4d688766 in ShaderPreprocessor::preprocess(ShaderPreprocessor::State*, String const&, String&) servers/rendering/shader_preprocessor.cpp:1299
    #6 0x55cf4d688c23 in ShaderPreprocessor::preprocess(String const&, String const&, String&, String*, List<ShaderPreprocessor::FilePosition, DefaultAllocator>*, List<ShaderPreprocessor::Region, DefaultAllocator>*, HashSet<Ref<ShaderInclude>, HashMapHasherDefault, HashMapComparatorDefault<Ref<ShaderInclude> > >*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, void (*)(List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*)) servers/rendering/shader_preprocessor.cpp:1310
    #7 0x55cf4a96e600 in Shader::set_code(String const&) scene/resources/shader.cpp:82
    #8 0x55cf465ef678 in ColorPicker::init_shaders() scene/gui/color_picker.cpp:166
    #9 0x55cf4582beb5 in register_scene_types() scene/register_scene_types.cpp:1188
    #10 0x55cf376a2749 in Main::setup2() main/main.cpp:2810
    #11 0x55cf3768f8dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #12 0x55cf373a5aac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #13 0x7f52af029d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```
GLES3
```
Godot Engine v4.3.dev.custom_build.7827c8e37 - https://godotengine.org
WARNING: Could not set V-Sync mode. V-Sync is not supported.
     at: set_use_vsync (platform/linuxbsd/x11/gl_manager_x11.cpp:374)
WARNING: The Multi-Threaded rendering thread model is experimental, and has known issues which can lead to project crashes. Use the Single-Safe option in the project settings instead.
     at: setup2 (main/main.cpp:2498)
servers/rendering/shader_compiler.h:89:9: runtime error: load of value 1380403859, which is not a valid value for type 'TextureFilter'
servers/rendering/shader_compiler.h:89:9: runtime error: load of value 22044, which is not a valid value for type 'TextureRepeat'
servers/rendering/shader_compiler.h:89:9: runtime error: load of value 1380403859, which is not a valid value for type 'TextureFilter'
servers/rendering/shader_compiler.h:89:9: runtime error: load of value 22044, which is not a valid value for type 'TextureRepeat'
OpenGL API  - Compatibility - Using Device:  - 
ERROR: trying to allocate texture with name Texture 2D but ID already used by Texture 2D: 0
   at: texture_allocated_data (drivers/gles3/storage/utilities.h:117)
ERROR: trying to allocate texture with name Texture 2D but ID already used by Texture 2D: 0
   at: texture_allocated_data (drivers/gles3/storage/utilities.h:117)
   ERROR: Texture cache is not empty. There may be an additional texture leak of 5356884 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:84)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2204)
Direct leak of 65552 byte(s) in 1 object(s) allocated from:
    #0 0x7fd1b2eb4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x561c52474b81 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x561c3eec028a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:291
    #3 0x561c3f47e6b5 in String::resize(int) core/string/ustring.h:218
    #4 0x561c4f0776ac in ShaderPreprocessor::vector_to_string(LocalVector<char32_t, unsigned int, false, false> const&, int, int) servers/rendering/shader_preprocessor.cpp:361
    #5 0x561c4f08d766 in ShaderPreprocessor::preprocess(ShaderPreprocessor::State*, String const&, String&) servers/rendering/shader_preprocessor.cpp:1299
    #6 0x561c4f08dc23 in ShaderPreprocessor::preprocess(String const&, String const&, String&, String*, List<ShaderPreprocessor::FilePosition, DefaultAllocator>*, List<ShaderPreprocessor::Region, DefaultAllocator>*, HashSet<Ref<ShaderInclude>, HashMapHasherDefault, HashMapComparatorDefault<Ref<ShaderInclude> > >*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*, void (*)(List<ScriptLanguage::CodeCompletionOption, DefaultAllocator>*)) servers/rendering/shader_preprocessor.cpp:1310
    #7 0x561c4c373600 in Shader::set_code(String const&) scene/resources/shader.cpp:82
    #8 0x561c47ff4879 in ColorPicker::init_shaders() scene/gui/color_picker.cpp:191
    #9 0x561c47230eb5 in register_scene_types() scene/register_scene_types.cpp:1188
    #10 0x561c390a7749 in Main::setup2() main/main.cpp:2810
    #11 0x561c390948dd in Main::setup(char const*, int, char**, bool) main/main.cpp:2238
    #12 0x561c38daaaac in main platform/linuxbsd/godot_linuxbsd.cpp:62
    #13 0x7fd1b2229d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```

### Steps to reproduce

Run minimal project - contains inside project.godot
```
[rendering]
threads/thread_model=2
driver/threads/thread_model=2
```

### Minimal reproduction project (MRP)

[Untitled Folder 2.zip](https://github.com/godotengine/godot/files/13997392/Untitled.Folder.2.zip) - empty project with only one node and set multithread settings

### LINKED ISSUE #89585: `ResourceLoader` threaded loading causes memory leak
### Tested versions

- Reproducible in: 4.3.dev3, 4.3.dev5
- Not reproducible in: 4.2.1.stable, 4.2.2.rc1

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - GLES3 (Compatibility) - Radeon RX 560X Series (Advanced Micro Devices, Inc.; 31.0.21910.5) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Using `ResourceLoader`'s threaded loading mechanism causes memory leaks.

Here is a short script which demonstrates it. It just loads a white texture repeatedly. Note how it doesn't hold any references to the loaded texture by the end of `_physics_process`.

```gdscript
extends Node2D

const PATH = 'res://white_1024.png' # a white 1024x1024 texture, can be any resource
const MAX_LOAD_COUNT = 500 # total of ~2GB RAM usage

var is_loading := false
var load_count := 0

func _physics_process(__):
	if not is_loading:
		is_loading = true
		ResourceLoader.load_threaded_request(PATH)
	else:
		if ResourceLoader.load_threaded_get_status(PATH) == ResourceLoader.THREAD_LOAD_LOADED:
			print('Load count = %s' % load_count)
			var test := ResourceLoader.load_threaded_get(PATH)
			assert(ResourceLoader.has_cached(PATH) == true)
			test = null
			assert(ResourceLoader.has_cached(PATH) == false)

			load_count += 1
			if load_count < MAX_LOAD_COUNT:
				is_loading = false # load again
```

### Steps to reproduce

1. Run the MRP.
2. In the Debugger > Monitors tab, observe how the RAM usage and Objects counter keeps increasing.
3. Observe how the RAM usage and Objects counter doesn't go down even after all the loading is done (after `MAX_LOAD_COUNT` is reached).

Not sure if related, but notice how the texture memory usage didn't really change throughout.

Sample Run:
sample_run

### Minimal reproduction project (MRP)

[resource_threaded_mem_leak_MRP.zip](https://github.com/godotengine/godot/files/14625218/resource_threaded_mem_leak_MRP.zip)

### LINKED ISSUE #90725: Multithreaded memory leak (4.3 only)
### Tested versions

 - Reproducible in 4.3
 - Not reproducible in 4.2

### System information

Godot v4.3.dev5.mono - Windows 10.0.22000 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.12027.9001) - Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 Threads)

### Issue description

Found a memory leak when setting shape data, but only if physics multithreading is turned on.  Doesn't happen in 4.2.

### Steps to reproduce

Run attached, memory use increases.
Turn off multithreading & run, no increase.

### Minimal reproduction project (MRP)

[MemTest-cs_gdscript.zip](https://github.com/godotengine/godot/files/14985017/MemTest-cs_gdscript.zip)
[MemTest-gdscript_only.zip](https://github.com/godotengine/godot/files/14985019/MemTest-gdscript_only.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
This is a follow-up of #90268 that ties up a few loose ends of it; namely:
- Startup and teardown of physics and rendering servers is know much more consistent among them and is better integrated with the new `WorkerThreadPool`-`CommandQueueMT` collaboration infrastructure.
- The `DisplayServer` stays unlocked in more conditions, which avoids ceratin cases of deadlock when input events are delivered.
- Post-draw callbacks and signals from the `RenderingServer` are now sent from the main thread. Otherwise, you'd for sure find dragons if using separate thread.

Not directly related, and so kept in separate commits, but their need found while working on this:
- OpenGL: Avoid error due to the assumption of the lifetime of the backbuffer texture being perfectly bond to that of the backbuffer FBO.
- `ObjectDB`: Properly lock the object database for cleanup.
- `CommandQueueMT`: Fix certain leaks when using separate thread for physics or rendering (thanks to @Zylann for the investigation). Also, properly handle resize of the command buffer!

Known issues (will fix the critical ones before changing from draft to ready-for-review):
- ~Windows, OpenGL: resizing windows using separate render thread deadlocks.~ **FIXED**
- Windows, Vulkan: resizing windows seems to apply some offset to the system surface. (Present in `master`. Will have its own PR.)
- MacOS: ~Can't test anymore since there's a crash.~ Resizing with Vulkan deadlocks. Possibly a MoltenVK issue. Reported (https://github.com/KhronosGroup/MoltenVK/issues/2213). ThIs PR can be merged despite it. If it turns out to be fixable in Godot, a separate PR can address it. **UPDATE:** Seems solvable at MoltenVK; in fact, I've submitted a PR there. **UPDATE:* Fix merged upstream.

Fixed issues:
- Fixes #89585.
- Fixes #90725.
- Fixes #87382.

PS: A bit of testing on Linux with all the combos for rendering would be appreciated.
- `--render-thread safe`, `--render-thread separate`
- `--rendering-method gl_compatibility`, `--rendering-method forward_plus`

### CODE REVIEW

File: servers/rendering/rendering_server_default.cpp [hunk 1]
```diff
@@ -194,6 +184,23 @@ void RenderingServerDefault::_draw(bool p_swap_buffers, double frame_step) {
 	RSG::utilities->update_memory_info();
 }
 
+void RenderingServerDefault::_run_post_draw_steps() {
```
Comment (reduz) [inline servers/rendering/rendering_server_default.cpp:187]: I am not sure I understand this, the idea is that this runs in the same thread as the render code, is it not?
I think this should be deprecated though to instead rely on call_on_render_thread()

Comment (RandomShaper) [reply servers/rendering/rendering_server_default.cpp:187]: The lines I moved to this function will only work on the main thread, because they are emitting a signal and calling some callbacks. Both mechanisms are only safe on the main thread.

Comment (RandomShaper) [reply servers/rendering/rendering_server_default.cpp:187]: That said, I can't see why we have two mechanisms for quite the same. The signal should be enough. But, still, it's only safe to emit it from the main thread. In separate thread mode that's the best point I found to emit it, but there may be better options.

So, deprecating frame drawn callbacks is certainly something we can do, but they still need to be called from the main thread.

**Review by akien-mga — APPROVED** [review]
Looks good to me. Needs a rebase.

**Comment by akien-mga** [comment]
Tested on Linux (rebased on latest `master`), and confirmed that this fixes the MRPs for these issues which I could reproduce in 4.3-dev6:
- #89585 
- #90725 

For the third one, it's not a recent regression like the other two, and requires LSAN to reproduce the issue. I couldn't reproduce the issue in `master` so maybe it's already fixed.

**Comment by akien-mga** [comment]
> PS: A bit of testing on Linux with all the combos for rendering would be appreciated.
> 
> * `--render-thread safe`, `--render-thread separate`
> * `--rendering-method gl_compatibility`, `--rendering-method forward_plus`

Did some basic testing on Fedora 40 with these two projects:
- https://github.com/gdquest-demos/godot-4-3d-third-person-controller
- https://github.com/johncoffee/ngj-2024

Didn't notice any particular difference in either combination, so it seems to work.

**Comment by akien-mga** [comment]
Thanks! Great work :tada:
