### PR TITLE
Standardize dialog input validation as a new class

### LINKED ISSUE #80218: Script Create Dialog is enormous
### Godot version

4.2 0606ba7

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you create a new script, the dialog has a height of a few screens. Likely caused by autowrapped Labels. The bug happens even when a new Label appears in already shrunk dialog:

https://github.com/godotengine/godot/assets/2223172/f25fb153-9e24-4aaa-beef-6e7c8554cb39

### Steps to reproduce

1. Create script

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Since some time we have an established way to validate input in various dialogs. We use a panel with error messages, like this one:

However every dialog implemented it separately, with led to duplicate code and even some inconsistencies (like missing panel style or using wrong listing character).

This PR adds EditorValidationPanel. It serves 2 purposes:
- displays provided messages, styling them depending on message type (ok/warning/error/info)
- reduces boilerplate code by doing some error management automatically

EditorValidationPanel's constructor expects a vector of strings. They will serve as default "valid" messages (i.e. no errors); size of the vector determines number of labels. After panel is created, use `EditorValidationPanel.update()` to *queue* an update method. This method will first setup labels to their default state (so the status is "valid" by default and you don't need to set it each time), then a designated update callback is called. In this callback the user is supposed to use `set_message()` method to set the texts of the labels. The `set_message()` takes label index, message text and message type (ok/warning/error/info). EditorValidationPanel will automatically prefix the messages with •, assign them colors based on type and disable or enable the dialog's OK button if it was registered.

I replaced all custom validations with EditorValidationPanel, in some cases making them more consistent (although I tried to preserve the previous appearance, notably the notes without bullet points in script create dialog). This also exposed some messages that previously weren't previously used due to faulty logic. I noticed that AnimationBlendSpaceEditor also uses some similar panel with errors, but it behaves a bit differently and is not a dialog, so I left it for now (although the validation panel is capable of handling it).

EDIT:
After latest changes the messages are no longer part of the constructor. Instead you need to define them with explicit ID.

EDIT2:
Fixes #80218

### CODE REVIEW

File: editor/scene_create_dialog.cpp [hunk 1]
```diff
@@ -82,40 +81,35 @@ void SceneCreateDialog::browse_types() {
...
 
 void SceneCreateDialog::update_dialog() {
 	scene_name = scene_name_edit->get_text().strip_edges();
-	update_error(file_error_label, MSG_OK, TTR("Scene name is valid."));
 
-	bool is_valid = true;
 	if (scene_name.is_empty()) {
-		update_error(file_error_label, MSG_ERROR, TTR("Scene name is empty."));
-		is_valid = false;
+		validation_panel->set_message(0, TTR("Scene name is empty."), EditorValidationPanel::MSG_ERROR);
```
Comment (YuriSizov) [inline editor/scene_create_dialog.cpp:94]: So I have a question about the overall design of the new component.

It's expected that you, as a user, would update all messages in one go, within one call of the update callback, whatever triggers it. This makes me question whether it makes sense to rigidly set a predetermined list of possible status messages and create labels for them. Why not just clear everything and create the necessary lines, whether OK or WARN or ERROR on the fly, as we call the update callback? We can still evaluate if messages contain any errors and update the accept button, disable or enable it.

This seems a bit on the overengineered side of things.

----

That said, if you have a good argument for this approach, I would still suggest an adjustment. There is currently no clear connection between the messages that we update. We pass some collection to the constructor, and then here we set the message for some index 0. I would rework this so that instead of indices we use an enum/constants, so instead of some mysterious 0 we have a clear pointer to the message that we update, e.g. `SCENE_NAME_VALIDITY` or something.

And instead of passing an array to the constructor I would add a method for adding messages and use these constants there as well. So both when setting and updating it is clear which validation message we are touching. So it'd be like

```cpp

validation_panel->add_message(TTR("Some valid message"), SCENE_NAME_VALIDITY);
```

This would mean that instead of indices we use ids, but that's a fairly common pattern in our codebase.

Again, this is if you insist on doing it this way to begin with. But I think the whole scaffolding with labels is unnecessary and the update callback can set both good and bad message, or no message at all.

**Review by YuriSizov — CHANGES_REQUESTED** [review]

File: editor/scene_create_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/scene_create_dialog.cpp:94]: > This makes me question whether it makes sense to rigidly set a predetermined list of possible status messages and create labels for them. Why not just clear everything and create the necessary lines, whether OK or WARN or ERROR on the fly, as we call the update callback?

If they are predetermined, the order is guaranteed, so it doesn't matter what message you set and when.
Also there is no reason to re-create and setup them every time, not to mention it can be costly (validation is called with every text change).

Comment (YuriSizov) [reply editor/scene_create_dialog.cpp:94]: The order is guaranteed anyway, since the update callback is the only source of state changes. So the order is determined by it as well (or was, before this PR).

I don't get what you mean by it being costly. We have the update callback; before calling it we set the state to false, during it we set it to true if an error is added, after it we do the necessary updates.

Comment (KoBeWi) [reply editor/scene_create_dialog.cpp:94]: > The order is guaranteed anyway, since the update callback is the only source of state changes.

Yeah, and then there is ScriptCreateDialog with its tangled update logic. Appending messages would be super error-prone.

I only added enum in one case, because there were many different messages; for simple dialogs it's not that important. But I could add it everywhere I guess; IDs make sense too. Main reason why I designed this system like this is that I wanted to minimize the code required to add validation to a dialog; lots of stuff happens automatically behind the scenes.

> I don't get what you mean by it being costly.

The update callback is called with LineEdit's `text_changed`, which means every time you type or remove a letter. It wouldn't have noticeable impact probably, but destroying and creating nodes this often is not very efficient.

**Review by YuriSizov — APPROVED** [review]
Implementation looks sensible now. I understand your arguments and they make sense to me. I've tested all 4 dialogs a bit, and it seems to work as expected, though admittedly I didn't test every error message.

One thing that caught my eye, which isn't related to this PR, but can be addressed by it, is that the template message is colored like a successful check, when it should probably be an info message:

image

(Also apparently this is a valid filename, who knew!)

-----

There are some small suggestions (and a typo), but LGTM otherwise.

File: editor/gui/editor_validation_panel.h [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+	void _notification(int p_what);
+
+public:
+	void add_line(int p_id, const String &p_valid_message = "");
+	void set_accept_button(Button *p_button);
+	void set_update_callback(const Callable &p_callback);
+
+	void update();
+	void set_message(int p_id, const String &p_text, MessageType p_type, bool p_auto_prefix = true);
+	bool is_valid() const;
```
[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/gui/editor_validation_panel.h:83]: They are already grouped.
`add_line()`, `set_accept_button()` and `set_update_callback()` are for initialization.
`update()`, `set_message()` and `is_valid()` are used for/during update.
Also, except `set_accept_button()` and `set_update_callback()`, they are called in the same order in code.

`update()` and `_update()` can't be together due to different access specifiers.

Not sure how to improve it.

[the remark this answers is not in the document]
Comment (YuriSizov) [reply editor/gui/editor_validation_panel.h:83]: That grouping in the header makes sense, but I think it's not the same in the cpp file.

[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/gui/editor_validation_panel.h:83]: Right, for some reason the order is different...

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
