### PR TITLE
Change some image error messages to output the file path

### LINKED ISSUE #94946: Error messages for failed image imports do not print the affected file path
### Tested versions

- Reproducible in: v4.3.rc1.official

### System information

Windows 11 Pro - Godot v4.3.rc1.official - Vulkan (Compatibility)

### Issue description

When the editor fails to import images the error messages printed in the console might look like this:
```
● Expected Image data size of 1010x277x1 (DXT5 RGBA8 with 9 mipmaps) = 378896 bytes, got 379184 bytes instead.
● drivers\gles3\storage\texture_storage.cpp:1043 - Condition "image->is_empty()" is true. Returning: Ref<Image>()
```
These messages should print the path of the affected image file so that users have an easier time to find them. The size might be a hint but in larger projects that might be useless too.

### Steps to reproduce

Open the referenced project and check the console output.

### Minimal reproduction project (MRP)

https://github.com/godotengine/godot/files/13494040/Nov2023.zip

### PR DESCRIPTION
**Pull request by ChrisBase**
* Fixes: #94946

## Test environment
Godot Engine v4.3.rc1.official
Windows 11 Pro, Version 23H2, Build 22631.3880

## Issue
```TextureStorage::texture_2d_get()``` and ```TextureStorage::texture_2d_layer_get()``` do not print the path of the affected texture image when they fail. This is how an example output currently looks like:
```
● Expected Image data size of 1010x277x1 (DXT5 RGBA8 with 9 mipmaps) = 378896 bytes, got 379184 bytes instead.
● drivers\gles3\storage\texture_storage.cpp:1043 - Condition "image->is_empty()" is true. Returning: Ref<Image>()
```
This makes it hard to find and fix the affected image file.

## Fix
The fix replaces some ```ERR_FAIL_COND_V()``` with ```ERR_FAIL_COND_V_MSG()``` to also output the file path. The output then looks like this:
```
● Expected Image data size of 1010x277x1 (DXT5 RGBA8 with 9 mipmaps) = 378896 bytes, got 379184 bytes instead.
● Texture with path 'res://assets/images/placeholder.png' has no data.
```

### CODE REVIEW

**Comment by Calinou** [comment]
I suggest applying the same change in RenderingDevice, so this also impacts the Forward+ and Mobile rendering methods. Otherwise, the improved error messages will only be visible when using the Compatibility rendering method.

**Comment by RandomShaper** [comment]
Also, bear in mind that (I think)b not all textures will have a path (programatically created).

Also, the wording of the message feels a bit werid to me.

I'd suggest something like this:
```c++
if (image->is_empty()) {
    const String& path_str = texture->path.is_empty() ? "with no path" : vformat("with path '%s'", texture->path));
    ERR_FAIL_V_MSG(Ref<Image>(), vformat("Texture (%s) has no data.
}
```

**Comment by ChrisBase** [comment]
@Calinou  @RandomShaper 

Thank you both for your feedback. I updated the PR accordingly.

File: drivers/gles3/storage/texture_storage.cpp [hunk 1]
```diff
@@ -1040,7 +1040,11 @@ Ref<Image> TextureStorage::texture_2d_get(RID p_texture) const {
 
 		ERR_FAIL_COND_V(data.is_empty(), Ref<Image>());
 		image = Image::create_from_data(texture->width, texture->height, texture->mipmaps > 1, texture->real_format, data);
-		ERR_FAIL_COND_V(image->is_empty(), Ref<Image>());
+		if (image->is_empty()) {
+			const String& path_str = texture->path.is_empty() ? "with no path" : vformat("with path '%s'", texture->path);
```
Comment (Calinou) [inline drivers/gles3/storage/texture_storage.cpp:1044]:
```suggestion
			const String &path_str = texture->path.is_empty() ? "with no path" : vformat("with path '%s'", texture->path);
```

**Comment by RandomShaper** [comment]
I think this is good enough for now, but if may be good to refactor these blocks into something more compact, such as a (maybe templated) utility function in `RendererTextureStorage`. For the time being, I'll give my approval, but other contributors may think it's better to do the refactor now.

**Comment by Mickeon** [comment]
This could use a rebase and perhaps someone else from the rendering team could take a look at it, too.

**Review by Calinou — APPROVED** [review]
Should be good to merge after squashing commits together (see [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) for details).

**Comment by ChrisBase** [comment]
> Should be good to merge after squashing commits together (see [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) for details).

Thank you for the pointer. Hope everything is correct now. The ** GHA / 🏁 Windows / Template w/ GCC...** action seems to have an issue, but that doesn't seem related to my commit. Otherwise let me know.

**Comment by Repiteo** [comment]
Thanks!
