### PR TITLE
Make GridMap shortcuts editable and not conflict with other plugins

### LINKED ISSUE #3839: Make more GridMap keyboard bindings configurable
### Describe the project you are working on

A project which uses GridMap

### Describe the problem or limitation you are having in your project

I use a non standard keyboard layout (Colemak)

The current default keys to rotate or move up and down layers are fairly difficult to work with.

My Mac does not have a `delete` key so if I want to delete a selection I must do it by clicking two times, there is no shortcut.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add Editor level InputMappings which can be configured, this should solve the issue

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Please see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This is frustrating because a workaround is an everyday procedure

### Is there a reason why this should be core and not an add-on in the asset library?

Core GridMap

### LINKED ISSUE #67497: Grid Map Hotkeys for "changing floors" in editor no longer work
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 Beta 3

### System information

Windows 10

### Issue description

# Expected Behaviour
When editing a Grid Map, the E and Q keys are used to change the "floor" that the user is currently working on. (Marked in green in the image below)

## Actual behaviour
E and Q changes the transform mode of the 3D Editor. I believe it changes from Rotation, translation or scale. (marked in Red in the image below)

image

### Steps to reproduce

1. Create a scene, add a 3D mesh to the scene.
2. Save the scene as a Mesh Library through File>Export>MeshLibrary somewhere in your project.
3. Create a new Scene, add a GridMap Node.
4. Drag and drop the MeshLibrary from step 2 into the "MeshLibrary" slot in the GridMap inspector. 
5. Select the GridMap in the Scene Hierarchy. A Window should appear showing all the meshes in the MeshLibrary.
6. Select the mesh and start drawing the mesh in the scene. 
7. Try to Change the floor you are drawing on with Q and E. Instead of changing floors, it will switch between Transform/Rotation/Scale

### Minimal reproduction project
[GridMap Project_v2.zip](https://github.com/godotengine/godot/files/9841145/GridMap.Project_v2.zip)

### PR DESCRIPTION
**Pull request by geowarin**
This allows users to change shortcuts for the gridmap and also makes them more discoverable.

It now uses physical keycodes, where appropriate, to make the tool more accessible to non-qwerty keyboard users.

This also prevents shortcut events to be forwarded to the 3D editor plugin, avoiding conflicts.

image

fixes: #67497.
supersedes: #79377
supersedes: #75243
Closes: https://github.com/godotengine/godot-proposals/issues/3839

### CODE REVIEW

**Comment by geowarin** [comment]
I was looking for a way to use physical keycodes for editor shortcuts but I did not find any way.... 

This would be convenient for example the grid map "Rotate Cursor X" or the "Fly cam move left" could be mapped to A in qwerty and Q in azerty.

This would be a good way to provide good defaults for users using a non qwerty keyboard

**Comment by geowarin** [comment]
Ok thought I tested this more thoroughly but now, most of the shortcuts of the gridmap are inaccessible because they are conflicting with the 3D Editor shortcuts:

`Previous floor` (Q) is the same as `Select Mode`
`Next floor` is the same as `Rotate Mode`, ...

Is there a way for the GridMapPlugin to take precedence over the node_3d_editor_plugin?

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 1]
```diff
@@ -743,6 +743,16 @@ EditorPlugin::AfterGUIInput GridMapEditor::forward_spatial_input_event(Camera3D
 				}
 			}
 
+			// Swallow input to avoid conflicts with other plugins
```
Comment (KoBeWi) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:746]:
```suggestion
			// Swallow input to avoid conflicts with other plugins.
```

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 2]
```diff
@@ -743,6 +743,16 @@ EditorPlugin::AfterGUIInput GridMapEditor::forward_spatial_input_event(Camera3D
...
+			for (int itemIdx = 0; itemIdx < options->get_popup()->get_item_count(); ++itemIdx) {
+				const Ref<Shortcut> &shortcut = options->get_popup()->get_item_shortcut(itemIdx);
+				if (shortcut.is_valid() && shortcut->matches_event(p_event)) {
+					accept_event();
```
Comment (KoBeWi) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:750]:
```suggestion
```
`accept_event()` doesn't seem to be used here. The return value is sufficient.

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 3]
```diff
@@ -743,6 +743,16 @@ EditorPlugin::AfterGUIInput GridMapEditor::forward_spatial_input_event(Camera3D
 				}
 			}
 
+			// Swallow input to avoid conflicts with other plugins
+			for (int itemIdx = 0; itemIdx < options->get_popup()->get_item_count(); ++itemIdx) {
```
Comment (KoBeWi) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:747]:
```suggestion
			for (int item_idx = 0; item_idx < options->get_popup()->get_item_count(); ++item_idx) {
```
Use `snake_case` only for variable names.
(it could be simply `i`)

**Comment by KoBeWi** [comment]
The implementation looks alright, but the physical shortcuts are questionable. We don't use physical keys for shortcuts (see https://github.com/godotengine/godot-proposals/issues/7303). Also your choice of physical keys is rather arbitrary; at best it only helps users with a specific layout (I assume AZERTY or similar).

> However, I found a way to prevent forwarding the shortcuts events to the node_3d_editor_plugin by iterating on all the menu item shortcuts in forward_spatial_input_event and accepting the events when appropriate.

I don't remember seeing menu shortcuts iterated like this before, but it looks correct.

**Comment by geowarin** [comment]
Physicals are used because I'm assuming theses keys are meant to be in close physical proximity.

QWE (floors and clear rotation)
ASD (rotation x/y/z)
ZXC (edit axis x/y/z)

Are clearly meant to be grouped together. I agree that making all of them (rather than cherry-picked ones) physical would make more sense.

You're right I'm using azerty :smile: 
For me it makes the tool way more usable out of the box. 
Anyway, this is just a personal opinion since they become configurable, I can remove that part of the code if you wish :smile:

File: modules/gridmap/editor/grid_map_editor_plugin.cpp [hunk 4]
```diff
@@ -743,6 +743,15 @@ EditorPlugin::AfterGUIInput GridMapEditor::forward_spatial_input_event(Camera3D
 				}
 			}
 
+			// Swallow input to avoid conflicts with other plugins.
```
Comment (AThousandShips) [inline modules/gridmap/editor/grid_map_editor_plugin.cpp:746]:
```suggestion
			// Consume input to avoid conflicts with other plugins.
```

**Review by KoBeWi — APPROVED** [review]
The implementation looks alright.

I still think that physical keys shouldn't be used. CC @Calinou

**Comment by geowarin** [comment]
@KoBeWi 
I'm willing to remove the physical keys but I want to defend my case one last time with pictures.
And if you're not convinced, I will remove them :smile: 

Here is what the keyboard shortcuts look like on a QWERTY keyboard:

image

Notice how they are nicely laid out.

`Red` keys control floor and clear rotation.
`Green` control the rotation of the mesh.
`Blue` control the rotation of the grid.

Here it what it looks in azerty:

image

It's super confusing!

I agree with you that physical keycodes should be avoided most of the time but I think this feature, just like the FreeCam justify their use.

What do you think?

**Comment by KoBeWi** [comment]
I borrowed your implementation to open another PR (#80317) and actually discovered a bug that also exists in your code.

You can use `matches_event()` directly on the InputEvent, because it will also match released and echo events. So e.g. Cursor Rotate shortcut will rotate the mesh by 180° instead of 90, because it will also use both the press and release events. I solved it by using a condition before the `for` loop:
```C++
Ref<InputEventKey> k = p_event;
if (k.is_valid() && k->is_pressed() && !k->is_echo()) {
```
You should do the same.

**Comment by akien-mga** [comment]
I think physical keys make sense here.

The criterion is simple:
- Is the shortcut meant to be linked to a letter/symbol, regardless of its position on the keyboard? If yes, then use "normal" key that follows the keyboard layout. E.g. "M" for toggling **M**inimap. Or Ctrl+Z for Undo because that's well established after decades of use on different keyboard layouts.
- Is the shortcut meant to be located in a specific position, such as WASD for first-person movement? If yes, it should use physical keys. There's no link between "W" and "Up", aside from it being positioned on top of "ASD" on a QWERTY keyboard.

So here the shortcuts seem to be positioned as an equivalent to the NumPad and they should stay there, not move around arbitrarily based on the keyboard layout (AZERTY is a common issue, but test DVORAK...).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by clemrod** [comment]
Hi, I’m experiencing a similar issue with the GridMap editor in Godot 4.4.1 using a French AZERTY keyboard. The **Z** key activates the Eraser Tool even after setting it to "None" in **Editor > Editor Settings > Shortcuts > TileMap Editor**. Switching to a QWERTY layout (FR US) fixes the problem, suggesting a bug in AZERTY key mapping.

Steps to reproduce:
1. Use a French AZERTY keyboard.
2. Open a project with a GridMap node.
3. Set the Eraser Tool shortcut to "None" in TileMap Editor settings.
4. Press **Z** in the GridMap editor: it still activates the Eraser Tool.

Environment:
- Godot Version: 4.4.1 stable, vérifie dans Aide > À propos de Godot]
- OS: [ex. Windows 11]
- Keyboard: French AZERTY
- Project: C# with GridMap node

Workaround:
- Switch to QWERTY layout.
- Use toolbar buttons instead of shortcuts.

Does this PR fix the issue of shortcuts not disabling correctly on AZERTY keyboards? If not, should I open a separate issue? Thanks for the work on improving GridMap shortcuts!

**Comment by Zireael07** [comment]
Make a separate issue or ask around in other community channels. People are unlikely to see a comment on a long-ago merged PR
