### PR TITLE
Fix crash on old glTF scene reimport 

### LINKED ISSUE #69604: GLB's crashing Godot 4.0 beta 7 if from previous version
### Godot version

4.0.beta.7.mono

### System information

Endeavour OS Zen Kernel 6.1 Ryzen 5900x Nvidia GTX 1060 6GB (proprietary drivers)

### Issue description

Curtain models in my game which were exported as GLTF2's and imported in the previous Godot 3.5 crash the engine when importing with godot 4. Moving the location of the file so the engine auto-reimports it fixes the issue. This is the error given when the crash happens 

```
ERROR: FATAL: Condition "!exists" is true.
   at: operator[] (./core/templates/hash_map.h:504)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.beta7.mono.official (0bb1e89fb7046209f64d46ccedc6b42645c96573)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.11/libcoreclr.so(+0x4b37de) [0x7f55734b37de] (??:0)
[2] /usr/lib/libc.so.6(+0x38a00) [0x7f55ad8faa00] (??:0)
[3] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x13d40d6] (??:0)
[4] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x207bc8a] (??:0)
[5] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x1d89d70] (??:0)
[6] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x1d8a489] (??:0)
[7] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x43d19ba] (??:0)
[8] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x14e0f50] (??:0)
[9] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x2d0bfc4] (??:0)
[10] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x2a5be65] (??:0)
[11] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x2aaac3e] (??:0)
[12] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x2aacd51] (??:0)
[13] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x2aad323] (??:0)
[14] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x2acd4d7] (??:0)
[15] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0xe28444] (??:0)
[16] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x4145937] (??:0)
[17] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0x41467b5] (??:0)
[18] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0xe2a3e8] (??:0)
[19] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0xda8302] (??:0)
[20] /usr/lib/libc.so.6(+0x23290) [0x7f55ad8e5290] (??:0)
[21] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f55ad8e534a] (??:0)
[22] /home/zach/Godot Projects/Godot 4/Godot builds/Godot_v4.0-beta7_mono_linux_x86_64/Godot_v4.0-beta7_mono_linux.x86_64() [0xdc9e5e] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

Transfer a project from Godot 3 to 4 containing GLTF 2 models and attempt to open them

### Minimal reproduction project

N/A as is subjective and likely wouldn't happen without the conversion and non-re importation bug which happens locally

### PR DESCRIPTION
**Pull request by RumblingTurtle**
Fix for #69625. modules/gltf/editor/editor_scene_importer_gltf.cpp:66 tries to access nonexistent "animation/trimming" parameter from cube.glb.import. Not sure if this flag is added by default but it seems like it breaks compatibility. @TokageItLab 

*Bugsquad edit:*
- Fixes #69604

### CODE REVIEW

**Review by fire — APPROVED** [review]
I think this is good, but would like someone else to look at it @lyuma

**Comment by lyuma** [comment]
Why does it need an explicit check for "animation/trimming" but not for "animation/fps"?

I'm concerned that this bug will pop up again and again in different places if we don't understand why checks are needed for some but not others.

**Comment by lyuma** [comment]
I would prefer it do `p_options.get("animation/trimming", false)` to avoid an if statement and duplicate code.

But I'm still wondering why the same issue isn't happening with fps

**Comment by RumblingTurtle** [comment]
> I would prefer it do `p_options.get("animation/trimming", false)` to avoid an if statement and duplicate code.
> 
> But I'm still wondering why the same issue isn't happening with fps

I don't see any get(key,bool) implementations in core/templates/hash_map.h but it would be nice to have one

**Comment by akien-mga** [comment]
> But I'm still wondering why the same issue isn't happening with fps

I assume `fps` is present in older imports so it works fine. But anything new can't be assumed to be defined.

**Comment by TokageItLab** [comment]
I do not like the idea of adding checks for compatibility every time a new parameter is implemented in importer. I feel those are the role of the project converter. Shouldn't we make it so that when an old project is detected, reimport is enforced?

**Comment by akien-mga** [comment]
Whatever we do, we should aim to have a merged fix today so that users don't get a crash in beta8 (ETA tomorrow-ish).

So I think a short term fix is fine, and we can take time to figure out a long term solution, e.g. properly identifying when an import format changes so that reimports *are* forced.

**Comment by TokageItLab** [comment]
@akien-mga Apart from this, I know there is a problem with AnimationPlayer with Capture mode crashing (by #69357), do we need to take care of that as well? More to the point, the Bezier tracks created in early Alpha are corrupted and the 3.x TransformTrack is not compatible at all.

I think the problem is that it crashes without the error that "the scene is corrupted and cannot be opened".

File: modules/gltf/editor/editor_scene_importer_gltf.cpp [hunk 1]
```diff
@@ -63,7 +63,12 @@ Node *EditorSceneFormatImporterGLTF::import_scene(const String &p_path, uint32_t
 	if (p_options.has("animation/import")) {
 		state->set_create_animations(bool(p_options["animation/import"]));
 	}
-	return doc->generate_scene(state, (float)p_options["animation/fps"], (bool)p_options["animation/trimming"]);
+
+	if ((bool)p_options.has("animation/trimming")) {
```
Comment (aaronfranke) [inline modules/gltf/editor/editor_scene_importer_gltf.cpp:67]: `.has()` should already return a bool.

**Review by akien-mga — APPROVED** [review]
Let's go with this for now to solve the crash.
