### PR TITLE
Fix parameters that are considered as constants

### LINKED ISSUE #68977: GDScript 2.0: Argument of a function marked as constant if it is of a custom type
### Godot version

4.0.beta5 and currently last build of 11e1c83

### System information

MacOS 10.15.7

### Issue description

Last line of code in **Steps to reproduce** produces a parser error on last line with "Cannot assign a new value to a constant."

Maybe that is some intended behavior, but if `baz` is of type `Object` the restriction is lifted and no error is produced.

### Steps to reproduce

```gd
class Foo extends Object:
  pass

func bar( baz: Foo ) -> void:
  baz = Foo.new()
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by adamscott**
Force the datatype of function parameters to not be a constant.

Fixes #68977

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1745,6 +1745,7 @@ void GDScriptAnalyzer::resolve_parameter(GDScriptParser::ParameterNode *p_parame
 		push_error(vformat(R"(Could not infer the type of the variable "%s" because the initial value is "null".)", p_parameter->identifier->name), p_parameter->default_value);
 	}
 
+	result.is_constant = false;
```
Comment (akien-mga) [inline modules/gdscript/gdscript_analyzer.cpp:1748]: There's code above setting this to `false` already, which is now redundant.

If this can never be constant, I'd move this up to where `result` is initialized.

Comment (adamscott) [reply modules/gdscript/gdscript_analyzer.cpp:1747]: You're right about the redundancy, I removed the code above that is setting `result.is_constant = false`.

But if you take a look at lines [1722](https://github.com/godotengine/godot/pull/68985/files#diff-e01550d654cd3b28e2c1abaa393c95a08008ea22c5860cbd034b515b84635237R1722) and [1731](https://github.com/godotengine/godot/pull/68985/files#diff-e01550d654cd3b28e2c1abaa393c95a08008ea22c5860cbd034b515b84635237R1731), you'll see that `result` is assigned there, which makes moving `is_constant = false` up impossible.

**Review by akien-mga — APPROVED** [review]

**Comment by adamscott** [comment]
Wait before merging this PR. I'm wondering if there's something else that I can do, because setting `is_constant` to `false` may impact performance and memory (as being a constant skips multiple checks).

**Comment by akien-mga** [comment]
Thanks!
