### PR TITLE
[DisplayServer] Add method to check if native window is focused.

### LINKED ISSUE #77824: Initial window focus state is incorrect, `has_focus()` returns `false` when it should return `true`
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  The "focus" of a window through get_window ().has_focus () reports false for a window initially even though it is obviously true.  It doesn't get corrected until something else gets the "focus" and it receives a WM_SETFOCUS again.  This is the case for the Editor window when running a plug-in aswell.

  It looks like the internal "focus" state flag is being reset after the initial WM_SETFOCUS has occurred for a window.

### Steps to reproduce

  Run the MRP and you'll see that "false" is printed in the title-bar of the window when it should be "true".

### Minimal reproduction project

[MRP_Focus.zip](https://github.com/godotengine/godot/files/11644644/MRP_Focus.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/77824

In some cases `Window` object callbacks are set after it's shown, and focus event arrived, therefore it's necessary to check current window status.

### CODE REVIEW

File: scene/main/window.cpp [hunk 1]
```diff
@@ -616,6 +616,8 @@ void Window::_update_from_window() {
 void Window::_clear_window() {
 	ERR_FAIL_COND(window_id == DisplayServer::INVALID_WINDOW_ID);
 
+	bool had_focus = has_focus();
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply scene/main/window.cpp:619]: Not it's saving the state to restore it later. If it _had_ focus, it will be restored.

File: .github/workflows/static_checks.yml [hunk 2]
```diff
@@ -106,5 +106,5 @@ jobs:
         uses: codespell-project/actions-codespell@v1
         with:
           skip: "./bin,./thirdparty,*.desktop,*.gen.*,*.po,*.pot,*.rc,./AUTHORS.md,./COPYRIGHT.txt,./DONORS.md,./core/input/gamecontrollerdb.txt,./core/string/locales.h,./editor/project_converter_3_to_4.cpp,./misc/scripts/codespell.sh,./platform/android/java/lib/src/com,./platform/web/node_modules,./platform/web/package-lock.json"
-          ignore_words_list: "curvelinear,doubleclick,expct,findn,gird,hel,inout,lod,nd,numer,ot,te,vai"
+          ignore_words_list: "curvelinear,doubleclick,expct,findn,gird,hel,inout,lod,nd,numer,ot,te,vai,requestor"
```
Comment (akien-mga) [inline .github/workflows/static_checks.yml:109]: Seems unrelated to this PR?
This list should also be kept in sync with `misc/scripts/codespell.sh`.

Comment (bruvzg) [reply .github/workflows/static_checks.yml:109]: Unrelated, but it's in the same file that was edited. Updated the script.

File: scene/main/window.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (bruvzg) [reply scene/main/window.cpp:619]: It's a state saved before removing native windows, which is checked after deletion.

File: .github/workflows/static_checks.yml (hunk 2 above)
Comment (bruvzg) [reply .github/workflows/static_checks.yml]: Done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
