### PR TITLE
Fix reset_state() in TileSet

### LINKED ISSUE #70847: Doesn't reset default values when reloading tilemap files
### Godot version

4.0 beta 10

### System information

Windows 10

### Issue description

Another bug found when working on the [Godot 4 exporter for Tiled](https://github.com/mapeditor/tiled/pull/3550).

When you change a tilemap file and remove a setting, Godot reloads the tilemap, but doesn't reset the removed setting to its default. Closing and reopening the project does.

### Steps to reproduce

1. Open the reproduction project. Note the isometric tilemap.
2. Edit tile_map.tscn
3. Remove line 73: `tile_shape = 1`
4. Re-focus Godot, and allow it to reload tile_map.tscn. Note the isometric tilemap.
5. Close the project and reopen it, without saving. Note the orthographic tilemap.

### Minimal reproduction project

[godotdefaultvalues.zip](https://github.com/godotengine/godot/files/10333210/godotdefaultvalues.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #70847
Apparently every Resource is supposed to implement `reset_state()` like this.

Although as I mentioned in the comment, the issue wouldn't have happened if the reference to TileSet was released properly.

### CODE REVIEW

File: scene/resources/tile_set.h [hunk 1]
```diff
@@ -308,7 +308,6 @@ class TileSet : public Resource {
 	TileLayout tile_layout = TILE_LAYOUT_STACKED;
 	TileOffsetAxis tile_offset_axis = TILE_OFFSET_AXIS_HORIZONTAL;
 	Size2i tile_size = Size2i(16, 16); //Size2(64, 64);
-	Vector2 tile_skew = Vector2(0, 0);
```
Comment (KoBeWi) [inline scene/resources/tile_set.h:311]: Unrelated, but this property is unused.

**Review by groud — APPROVED** [review]
