### PR TITLE
Fix crash when trying to set as Bitmap Font fallback one of his parent

### LINKED ISSUE #26939: Editor crash in EditorResourcePreview when assigned as fallback bitmap font
**Godot version:**
Godot 3.1 RC 2

**OS/device including version:**
Linux Mint 19

**Issue description:**
When assigning fallback of fallback to root BitmapFont, then editor crash.

**Steps to reproduce:**
1. Create new resource Bitmap font
2. Save it 
3. Open this Bitmap font
4. Assign to fallback new Bitmap font
5. To newly created Bitmap font assign previously saved font(root one)

### PR DESCRIPTION
**Pull request by qarmin**
Prevent assign to Bitmap Font fallback one of his parent to avoid crash by recurrence.
EDIT: It also fixed crash with materials
Fix first point of #26939

### CODE REVIEW

**Comment by reduz** [comment]
if it works, fine

File: scene/resources/font.cpp [hunk 1]
```diff
@@ -498,6 +498,11 @@ Size2 Font::get_string_size(const String &p_string) const {
 void BitmapFont::set_fallback(const Ref<BitmapFont> &p_fallback) {
 
 	ERR_FAIL_COND(p_fallback == this);
+
+	for (Ref<BitmapFont> p_fallback_child = p_fallback; p_fallback_child != NULL; p_fallback_child = p_fallback_child->get_fallback()) {
```
Comment (akien-mga) [inline scene/resources/font.cpp]: Two things:
- `p_` is for method parameters, not local variables, so it should be `fallback_child`.
- Might need an `ERR_EXPLAIN` to give a more descriptive error mentioning the recursion in the fallback chain.

Comment (akien-mga) [reply scene/resources/font.cpp]: Bump.

**Comment by akien-mga** [comment]
Thanks!
