### PR TITLE
Retargeting option to use a template for silhouette.

### LINKED ISSUE #65656: "Fix Silhouette" in Retargeting does not work well on models other than A-pose or T-pose
### Godot version

https://github.com/godotengine/godot/commit/200b9cde88da485659a6376266af8e9bf7be186f

### System information

Windows 11, GLES3, RTX 3000

### Issue description

https://sketchfab.com/3d-models/valora-twitch-prime-emote-c430ff2028744abfa132774b0771f25d 

> トカゲ — Today at 01:50
If you load it into blender, you can see that the model is a titan...

> トカゲ — Today at 02:02
Since the rest is neither T-pose nor A-pose, the T-poser does not seem to work very well for the fingertips

> トカゲ — Today at 02:11
> Whether or not the T-poser works depends on the rest that is loaded. So I think this PR is important:
> https://github.com/godotengine/godot/pull/40274

>トカゲ — Today at 02:19
> So, the problem is that there are gltfs which have neither A-pose nor T-pose as a bound pose, > but only a pose for the first frame of the animation for about the issue of missing conversions 
maybe

### Steps to reproduce

1. Load godot
2. Setup glb to for retargeting
3. The retargeting doesn't match

### Minimal reproduction project

[valora__twitch_prime_emote.zip](https://github.com/godotengine/godot/files/9542870/valora__twitch_prime_emote.zip)

### LINKED ISSUE #89244: Animation retargeting leads to weird looking animations
### Tested versions

- Reproducable in v4.3-dev

### System information

Godot v4.3.dev.mono (28d895f32) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.14043.7000) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

I'm currently trying to set up a 3D character with 8-directional idle/walk/jog/run animations.
For this, I bought a model from cgtrader as a placeholder model and several locomotion animation packs:

 - [Mocap Online](https://[mocaponline.com/products/mobility?variant=31536237772871](https://mocaponline.com/products/mobility?variant=31536237772871))
 - [Synty Studios](https://syntystore.com/products/animation-base-locomotion)
 - [Movement_MocapAnimPack_2.0](https://assetstore.unity.com/packages/3d/animations/movement-mocapanimpack-2-0-223764)
 - [Mixamo](https://www.mixamo.com/)

And all of them except the Mixamo one are being animated really weird, like the animations are added to their rest pose somehow:
godot windows editor x86_64 mono_qudoBIHLk6

I've also tried to go down the path of importing them into blender, combining all the animations into one file and then reexport as GLTF but that also proved to be error prone because blenders skeleton system isn't compatible with the one from FBX so most of the animations are working but I got all sort of problems with it like twisted foot / hand, crossed arms or even still the same output sometimes.

The thing is - I and many of us game devs are simply no blender / animation pros, neither do we own a license for expensive Autodesk software so we have to rely on assets from third parties which mostly target Unity and Unreal.
So while I fully understand that the Godot way is to provide already animated characters with correct rest poses to the engine, in practise that's causing a lot of trouble (and wasted money) for the developers.

From what I've seen when importing several animations and fiddling around with them, most if not all of the animation files won't have their rest pose set to "T" or "A", they just use the same pose as the first animation frame.
However, the Mixamo character has all it's bones properly set up, nothing twisted after import and also all separate animation files have their rest pose set to "T" so that's why I'm guessing that the rest pose is the root cause here.

In Unity there is this avatar which will be reused across all the imported animations which is usually set up for the base character model.
This might roughly be the same as setting up a BoneMap in Godot and reusing that one for all animation files so maybe there should be an option to use the rest pose of a reference model to calculate the relative poses when retargeting animations.

### Steps to reproduce

- Create a blank 3D project
- Grab some locomotion animations from one of the many asset creators that mostly target Unity/Unreal
- Import the base model into Godot
  - Import Mode: Scene
  - Trimming: Yes (Some animations don't start at "0" so they have little jumps in them when looping)
  - Skeleton3D: Setup bone map with humanoid profile and save to disk
- Import animation like "run forward"
  - Import Mode: Animation Library
  - Trimming: Yes
  - Skeleton3D: Use bone map from base model
  - Animation: Set loop mode to "Linear"
- Drag base model into scene
- Right click on the node and enable "Editable Children"
- Select animation player
  - Add one if none was imported - for me, the Synty Robot did not have any animations so the animation player was not added
- Click "Animation -> Manage animations"
- Click "Load Library" and select the desired animation
- Select the animation
- Press "Play"

### Minimal reproduction project (MRP)

Unfurtunately I can't provide an MVP since all of the assets are locked behind commercial licenses.
However, Mocap Online offers a free demo pack which can be downloaded for testing purposes so I've set up a small test project but excluded all the FBX files.

One can just download the demo package from Mocap Online [here](https://[mocaponline.com/collections/demo-packs/products/free-mocap-animation-pack](https://mocaponline.com/collections/demo-packs/products/free-mocap-animation-pack)). extract and copy `MCO_Demo_Pack_v2/FBX` to `MocapOnlineDemo/MCO_Demo_Pack_v2/FBX` before opening the project and it should work.

[MocapOnlineDemo.zip](https://github.com/godotengine/godot/files/14523304/MocapOnlineDemo.zip)

### PR DESCRIPTION
**Pull request by lyuma**
Option to create and use SkeletonProfile as silhouette template.

Adds a few Skeleton3D options:
* For a reference model, adds `export_skeleton_profile_to_file/enabled` and `/path` to export the Skeleton3D node as a SkeletonProfile before retargeting.
* For retargeting, `retarget/rest_fixer/silhouette_template` option to replace bone rest with an exported SkeletonProfile before retargeting.

-------
With the latest version of the PR, I now use animations to transfer the pose from one model to another.
I tested the workflow. Here are some ways the new Rest Pose feature can be activated:
image

And for an example of it in action, here is of jog animation from issue #89244, showing the problem:
<details>
model in a wacky pose with limbs flailing
</details>

From this model, I now open up the good t-pose version and export the t-pose animation to a file:
image
This is best done using the "Export Skeleton Rest Pose" field on the skeleton, which works in case the model does not contain an explicit t-pose animation and avoids several pitfalls when referencing an AnimationLibrary or other extracted animation.

After reimporting the t-pose model, I can now use the extracted rest-pose animation in another model:
image

And tada! We now have the correct jogging animation, in Godot's humanoid format:
image

I will re-post this in the PR as well to show the workflow.

Fixes #65656
Fixes #89244

### CODE REVIEW

**Comment by fire** [comment]
Thoughts on a boolean that hides the bonemap. Like a switch between bone map or `retarget/rest_fixer/silhouette_template` where we control visibility.

**Comment by fire** [comment]
We discussed a read-only multiline string property for displaying correction instructions.

**Comment by TokageItLab** [comment]
Wasn't the real problem with this that all the other animations have T or A poses other than the top of the animation list?
I don't think this workflow requiring a separate model is a good idea. So the right way is to add a GUI to select the reference animation such as adding processing steps in the importer IMO.

**Comment by lyuma** [comment]
There is no list of animations on Maya exports. It is very common for an animation export from Maya to be a single animation named "Take 001", which is why animation authors in Unity typically include a separate fbx file in the reference pose.

I do not know if there are different workflows common in other engines such as Unreal, but the suggestion to add additional animations in each file for t-pose or a-pose is impractical at least for FBX and Maya exports.

Can you explain why it is not a good idea?

**Comment by TokageItLab** [comment]
There are several problems

Importing another model as an actual object increases the size of the project folder by the amount of the imported model.

It is difficult to detect the possibility that a profile has incorrect rests. This may have to be left to the user's file management practices, but at least it is a hassle to output a profile from the model each time and save it as a separate resource.

If managed as another model, it would be better to use a name suffix or special extension so that the collider uses `_col` and the external fbx can be specified directly from the importer as a file to be used only at import time.

**Comment by lyuma** [comment]
> Importing another model as an actual object increases the size of the project folder by the amount of the imported model.
Usually these models don't need the mesh, so they are just a skeleton posed in t-pose. So it may take on the order of one extra megabyte. For character models with separate animations, usually the character itself *is* the reference pose, so there is often no need to add additional files.

This is a critique of the workflow, but not a reason why it is wrong to do this, just that it is not as efficient. Also, there is no requirement to retain the original t-posed model in the project after extracting a skeleton profile. This is one of the reasons I decided to take this approach, since it creates an asset that can be reused for subsequent imports of a particular character.

> It is difficult to detect the possibility that a profile has incorrect rests. This may have to be left to the user's file management practices, but at least it is a hassle to output a profile from the model each time and save it as a separate resource.

I warn if a SkeletonProfile is used which does not match up with the chosen BoneMap. If two models have the same sets of bones, my assumption is that they likely have the same rests, but of course it is no guarantee. This feature is designed to work when two files refer to precisely the same skeleton, but the burden is on the user to make sure not to mix up files. This is indeed a workflow challenge but not a reason why this cannot be used as a workflow.

> If managed as another model, it would be better to use a name suffix or special extension so that the collider uses _col

I strongly dislike the collider suffix convention, and I would be unhappy creating a new workflow which depends on name suffixes, as other parts of the system may need to become aware of such rules..

> and the external fbx can be specified directly from the importer as a file to be used only at import time.

This certainly could be done as an alternative to specifying a SkeletonProfile. It adds complexity because the external model would have to be loaded which creates an import dependency. If you insist that we implement the feature this way, I can try to work on it.

I have some concerns about referencing another scene file from the import. Godot might not have a guarantee that models are imported in a particular order, or it could create a cyclic import if the user by mistake sets two gltf files as each other's silhouette.

**Comment by lyuma** [comment]
> after fbx changes the rest, this steps is required again

It should not be required, because the model uses the same skeleton either way (For example, if I have Alicia in t-pose and Alicia doing a walk animation, the skeleton is the same, so it does not matter which version of Alicia's bone rest I use.

Overwriting the bone rest is merely adjusting the model into a known pose, Also, this known pose can be combined with silhouette fixer to account for any offset between the reference t-pose and the desired t-pose.

> allow external fbxes to be specified IMO.

I'll have to figure out how to do this, but I assume it would be a scene file. We just need to make sure that the imports happen in the correct order if I lose my `.godot` directory. Perhaps it would be sufficient to call `reimport_append` if the dependency scene cannot be loaded.

We'd still have the problem that the target scene is not allowed to use BoneMap (since we lose the original bone rolls if the user has set a BoneMap, but it would be easy to detect this because the node names will not match (GeneralSkeleton vs Skeleton3D) as well as the bone names.

Anyway, I will work on this version of the change. From the user's perspective it should not be much different.

Technically I fear we are opening a can of worms that has not been tested. Do I use a PackedScene resource picker? a little scared to serialize a .glb or .fbx reference from a .import file
... or a `PROPERTY_HINT_FILE` file picker with `*.fbx,*.glb,*.gltf,*.scn,*.tscn,*.dae` ... but it can't target a .vrm if I do that: the user would have to inherit scene and reference the inherited .scn

**Comment by Illauriel** [comment]
> Importing another model as an actual object increases the size of the project folder by the amount of the imported model.

But if you export the Skeleton Profile, and remove the model afterwards, it shouldn't be that big of an impact, right? And this approach would fit with a kind of workflow where source model files themselves are not version-controlled and are split into their respective resources. So the FBX (or GLTF or whatever) from which the correct pose was borrowed only bloats the project folder of the team member responsible for setting the models up.

Overall, I see merit in both approaches, and if it would be possible to reference either a scene file _or_ a Skeleton Profile in the Silhouette Template field, that might be the best way to do it. Exporting a Skeleton Profile would be an extra step you have to do for each model, but it looks like a 'cleaner' workflow. Correct me if I'm wrong.^^'

> If managed as another model, it would be better to use a name suffix or special extension so that the collider uses `_col` and the external fbx can be specified directly from the importer as a file to be used only at import time.

It might be an option, but I don't use suffixes in my workflow so I don't think it would necessarily be 'better' to do it this way.

**Comment by TokageItLab** [comment]
It is true that SkeletonProfile is not referenced with the source model. It is focused to work in cases where changes to the source model are not important.

For example, SkeletonProfile is designed to be independently sharable for sharing among workers to allow retargeting of monster models with specific Rest, etc.

However, this is not the case in this PR case. If only one silhouette of one specific model is to be targeted, the Profile must have an reference with the source model. This is the same as the AnimationLibrary continuing to have an reference with the source file. In other words, if the referenced Profile is a tres, it must be generated with the .import through ImportedAs in Godot.

**Comment by Illauriel** [comment]
> This is the same as the AnimationLibrary continuing to have an reference with the source file.

I think I get your point, but we have also independent Animation Libraries that are not "models imported as AnimationLibrary", but "A grouping of externally stored animations" so this analogy is not entirely correct.

> In other words, if the referenced Profile is a tres, it must be generated with the .import through ImportedAs in Godot. 

But wat if I don't want to import the file as this kind of resource, because it also holds a ton of other useful data, like meshes, materials, etc. Say we have one big blend file with character, animations and all the stuff. It's like 150Mb. I never ever plan to edit it under any circumstances. (because I'm not an artist) I want to export all of this useful data as separate resources and discard the source .blend file for good. Should I instead create multiple copies of this .blend file to import one as an AnimationLibrary, another as SkeletonProfileForBetterSilhouetteFix and save meshes and materials from the third one?

> I think it would be suitable to have something like SilhouetteData

If it's a standalone file and it can safely lose reference to the imported model file that it got created from, it might be okay, but also as you've said, making a separate class just for this specific purpose seems wasteful. 

Here's how I see my specific workflow with this in my imagination:
- I bought a pack of animations from some store and want to retarget them to my character that has vastly different proportions to Unreal Mannequin or whatever the animation creators used as their base model.
- I drop the folder with animation FBX files in the project hierarchy, open the file that says T-pose, set BoneMapHumanoid, reimport open it as a scene and export a SkeletonProfile or whatever it will be called from it. 
- I open each of the other animation files' advanced import dialogues, set BoneMapHumanoid, set the exported SkeletonProfile, set a destination to export the animations, reimport.
- Then I delete the FBX source files and forget about their existence. I don't include them in the version control, I don't bloat my project folder, and feel happy about it.

TL;DR: all of the "ImportAs" and resource inheritance discussed previously is very good when you have a project where assets are in constant state of iteration and need updating, but it's not the only use case.

**Comment by TokageItLab** [comment]
> I think I get your point, but we have also independent Animation Libraries that are not "models imported as AnimationLibrary", but "A grouping of externally stored animations" so this analogy is not entirely correct.

Conversely, if the SkeletonProfile can also have a reference to the original model, it should do so.

Finally, it would be best if the split fbx could be imported as an AnimationLibrary and specified as per my comment above.

If that is possible, then we can share a method with the ability to specify animations other than the top of the animation list to address the two problem cases:

1. if the reference pose is in a separate file, we can load it as an external animation library and specify the reference  animation
2. if the reference pose is in the same file, but not at the beginning of the animation list, we can specify that reference animation

**Comment by lyuma** [comment]
Revision 442bbced8512cb3e13c1f704d6cb7dff3fd1c10f adds a better warning to the SkeletonProfile template.
image

I have spent several hours prototyping a workflow for animations or AnimationLibrary or PackedScene references, but they all seemed so clunky, and animations in particular are highly error prone either due to mixing up post-retargeting animations from pre-retargeting animations, as well as the default setting of "Remove Immutable Tracks" being on (BoneMap forces immutable tracks to be written, but we can't use a BoneMap'ed animation)

> If only one silhouette of one specific model is to be targeted, the Profile must have an reference with the source model. This is the same as the AnimationLibrary continuing to have an reference with the source file. In other words, if the referenced Profile is a tres, it must be generated with the .import through ImportedAs in Godot. Also, many fields are unnecessary for SkeletonProfile for this purpose.

Anyway, I was chatting with @Illauriel and thinking about your comment, and it occurred to me: I can make the SkeletonProfile generated by the .import.
image
This also adds a new workflow to easily create new workflow-specific profiles without having to open the scene and manually select "Export Skeleton Profile"

Further, since it is generated before the BoneMap is applied, it no longer requires an additional file for "retargeted" and "not retargeted" versions: you can enable the new Export Skeleton Profile to file and still perform the retarget, and the exported profile will be pre-retarget and hence suitable for use as a "Silhouette Template":
image

File: scene/resources/skeleton_profile.cpp [hunk 1]
```diff
@@ -390,6 +390,52 @@ bool SkeletonProfile::has_bone(const StringName &p_bone_name) {
 	return is_found;
 }
 
+void SkeletonProfile::init_from_skeleton(Skeleton3D *skeleton) {
```
Comment (fire) [inline scene/resources/skeleton_profile.cpp:393]:
```suggestion
void SkeletonProfile::initialize_from_skeleton(Skeleton3D *skeleton) {
```

We typically spell out abbreviations.

File: scene/resources/skeleton_profile.h [hunk 2]
```diff
@@ -123,6 +124,8 @@ class SkeletonProfile : public Resource {
 
 	bool has_bone(const StringName &p_bone_name);
 
+	void init_from_skeleton(Skeleton3D *skeleton);
```
Comment (AThousandShips) [inline scene/resources/skeleton_profile.h:127]:
```suggestion
#ifndef _3D_DISABLED
	void init_from_skeleton(Skeleton3D *p_skeleton);
#endif
```

File: scene/resources/skeleton_profile.h [hunk 3]
```diff
@@ -31,6 +31,7 @@
 #ifndef SKELETON_PROFILE_H
 #define SKELETON_PROFILE_H
 
+#include "scene/3d/skeleton_3d.h"
```
Comment (AThousandShips) [inline scene/resources/skeleton_profile.h:34]:
```suggestion
#ifndef _3D_DISABLED
#include "scene/3d/skeleton_3d.h"
#endif
```

File: scene/resources/skeleton_profile.h [hunk 4]
```diff
@@ -123,6 +126,10 @@ class SkeletonProfile : public Resource {
 
 	bool has_bone(const StringName &p_bone_name);
 
+#ifndef _3D_DISABLED
+	void initialize_from_skeleton(Skeleton3D *skeleton);
```
Comment (AThousandShips) [inline scene/resources/skeleton_profile.h:130]:
```suggestion
	void initialize_from_skeleton(Skeleton3D *p_skeleton);
```
Prefix arguments with `p_`

File: scene/resources/skeleton_profile.cpp [hunk 5]
```diff
@@ -390,6 +390,52 @@ bool SkeletonProfile::has_bone(const StringName &p_bone_name) {
 	return is_found;
 }
 
+#ifndef _3D_DISABLED
+void SkeletonProfile::initialize_from_skeleton(Skeleton3D *skeleton) {
```
Comment (AThousandShips) [inline scene/resources/skeleton_profile.cpp:394]:
```suggestion
void SkeletonProfile::initialize_from_skeleton(Skeleton3D *p_skeleton) {
```

**Comment by lyuma** [comment]
> There at least two different type of animation in FBX Maya, one is one single clip and the other is a series of animations.

Thank you, fire. I appreciate that you have identified that there are multiple cases here. That's exactly right.

I am solving the FBX split case.

However, I would also be happy to solve the multiple animation case. I believe this is best solved using a different approach:

> The current approach using SkeletonProfile does not look good as it is too specialized for the split fbx special case. The feature to select reference animation from AnimationLibrary would be a comprehensive solution to the problems with the order of blender's animation list in glTF as well as split fbx.

Rather than build one complexx comprehensive solution, we should take specific problems and solve both with specific solutions. That is the godot way.
The solution I built works extremely well for split FBX. It is difficult to improve on the workflow in terms of number of clicks or steps.

That leaves solving the gltf case.
I believe that can be done with a checkbox on the individual animation in the import settings for a given model. We can also make a dropdown if people prefer that.

Basically, it would be choosing an animation from the same model (not using an external AnimationLibrary) to use as the reference pose. I think this would be easy to do and I would be happy to implement this.

I am not going to compromise this design on the basis of forcing AnimationLibrary to be a suitable workflow. It simply is not a clean workflow
1. exported animations by default are missing immutable tracks
2. exported animations are subject to retargeting by default, so we need to remind the user to disable BoneMap from the reference model.
3. it is extremely difficult to include both an animation library reference as well as a dropdown for which animation wihtin the library. I don't even know where to start on building such a feature with godot's default inspector
4. Import As -> Animation library requires dedicating a whole model file just for the rest pose (since you then can't use as scene). exporting an individual animation would be simpler but we still have the first few issues.

Anyway I know I am not using SkeletonProfile the way you designed, but there was inspiration to do things this way, and I think it makes some sense to use the same datatype even if not 100% of the functionality of that data type is being used.

**Comment by TokageItLab** [comment]
> exported animations by default are missing immutable tracks
> exported animations are subject to retargeting by default, so we need to remind the user to disable BoneMap from the reference model.
> it is extremely difficult to include both an animation library reference as well as a dropdown for which animation wihtin the library. I don't even know where to start on building such a feature with godot's default inspector
> Import As -> Animation library requires dedicating a whole model file just for the rest pose (since you then can't use as scene). exporting an individual animation would be simpler but we still have the first few issues.

So I mean that it is the role of the AnimationLibrary importer to solve these, not the post importer.

**Comment by lyuma** [comment]
We talked in the meeting about it, there was a lot of pushback to using SkeletonProfile. I think we agreed that an Animation represents a skeleton pose.

There was some discussion that Animation is difficult to import currently, so we talked about adding Import As Animation (or animation pose?)
However, AnimationLibrary is difficult to reference because i would need a picker in the adv import dialog.
Furthermore, with sub-resource references, animation will become much easier to reference in 4.4+. Hence, I think we should reference Animation in anticipation of this change.

File: editor/import/3d/scene_import_settings.cpp [hunk 6]
```diff
@@ -109,29 +111,68 @@ class SceneImportSettingsData : public Object {
...
+					break;
+				case 2:
+					if (anim.is_valid()) {
+						hint_string = anim->get_name() + "," + anim->get_name();
+					}
+					if (library.is_valid()) {
+						List<StringName> anim_names;
+						library->get_animation_list(&anim_names);
+						for (StringName anim_name : anim_names) {
+							hint_string += "," + anim_name; // Include preceeding , for as catch-all
```
Comment (fire) [inline editor/import/3d/scene_import_settings.cpp:137]:
```suggestion
							hint_string += "," + anim_name; // Include preceding, for as catch-all
```

**Comment by lyuma** [comment]
Updated the PR to accept animation libraries, either externally or animations from the same file's AnimationPlayer.

There are now a few different cases here, and I have some warnings to detect the common pitfalls, (these pitfalls are why I originally shied away from using animations). For example, using a BoneMap converted animation; or using an animation with (almost) no tracks -- both of these are easy to create by mistake due the remove immutable tracks.
image

File: editor/import/3d/resource_importer_scene.cpp [hunk 7]
```diff
@@ -1745,7 +1849,39 @@ void ResourceImporterScene::get_internal_import_options(InternalImportCategory p
...
+			r_options->push_back(ImportOption(PropertyInfo(Variant::OBJECT, "rest_pose/external_animation_library", PROPERTY_HINT_RESOURCE_TYPE, "Animation,AnimationLibrary", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), Variant()));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::STRING, "rest_pose/selected_animation", PROPERTY_HINT_ENUM, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), ""));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "rest_pose/selected_timestamp", PROPERTY_HINT_RANGE, "0,1,0.001,allow_greater,suffix:s", PROPERTY_USAGE_DEFAULT), 0.0f));
+			String mismatched_or_empty_profile_warning = String(
+					"The external rest animation is missing some bones. "
+					"Use \"Export skeleton rest\" on the Skeleton3D advanced import, or "
+					"disable Remove Immutable Tracks."); // TODO: translate.
+			r_options->push_back(ImportOption(
+					PropertyInfo(
+							Variant::STRING, U"rest_pose/\u26A0_warnings/mismatched_or_empty_profile",
```
Comment (fire) [inline editor/import/3d/resource_importer_scene.cpp:1862]:
```suggestion
							Variant::STRING, U"rest_pose/\u26A0_validation/mismatched_or_empty_profile",
```

I wonder if validation or something like is better than warnings.

**Comment by Invertex** [comment]
Oh, glad to see this PR haha. I actually implemented this a couple months ago: 
https://github.com/Invertex/godot/tree/fix-silhouette-using-other-source



But I never submitted a PR because I assumed it probably wouldn't get approved... Was waiting to see if I could think of some other solutions. This has been a pretty big issue for more as it has severly restricted what third party animations we can use as a smaller studio. Many of the animation packs people may buy will come in this "bad workflow" format.


I took a similar approach as here, but instead of storing the Resource as an externally referenced file, I embed it in the **.import** of the model it belongs to. My thought here is that it ensures there's no mistake of ownership or possibility of another asset instance overwriting the Resource.

Other models can choose the target source model and read the BindPose resource from its .import if it exists.

I also update the pose at the very start before any of the regular importing fixes happen, so that the file is basically utilized by the import system as though it actually contained the proper rest pose. Don't need to mess with any of the actual import code.
BoneMap can do its thing, working with a proper matching bindpose then.

--------------------------------------
A possibility for triggering dependency could be having a list in the source file of other assets that rely on this profile. When this source model reimports, it could trigger those list of files for reimport after the source file is done (and any paths that don't exist anymore can be culled and warned about).

**Comment by fire** [comment]
@lyuma https://github.com/Invertex/godot/commit/62a98c4f4cbb8095b615c30f3f889ddbaa2cf16c#diff-d524f1765c15505d971875ccbf5ea13733989c77101db63a2f84fb09eb1b5ca3R57-R66

**Review by TokageItLab — CHANGES_REQUESTED** [review]
The UI seems much improved. However, I feel that the `Export Skeleton Rest Pose` features need more discussion.

I understand where you are coming from with the desire to extract individual Animations, but from a consistency standpoint, an option to 'include rests as "REST" animation in the AnimationPlayer of imported tres', and separate the animation from the imported scene and save it as new animation would seem more appropriate, IMO. Then, other models should be able to refer that AnimationPlayer to specify the "REST" animation for `Rest Pose`.

Even if it is extracted separately, at least it should be a folded option like `Use External`, similar to Mesh and Material since this option should be not necessary in many cases.

image

@lyuma So, I believe that the `Export Skeleton Rest Pose` functionality can be separated from this PR for now, can you remove/separate that option once from this PR? Other than that, it seems to make sense and we can be Approved.

**Comment by lyuma** [comment]
Before I update this PR, I would like to first understand the intended direction so that I can prepare both PRs: there is no point merging one feature without the other feature: a user cannot select a rest pose animation when there is no way to create a rest pose animation.

Sure, I would be fine without "Export Skeleton Rest Pose" since I am using Unidot to import fbx files, and Unidot now creates the rest pose animation automatically on 4.3. But losing this feature would interfere with ordinary users who are not using a third party tool script to create this animation automatically. While it does not need to be implemented in exactly this way, a way to create a "rest pose animation" does need to exist in some form in 4.3 for FBX animation import to be functional.

Therefore, I would like to understand the intended user-facing **workflow** / steps for FBX. 

To be clear, here is the problem that is being solved with "Export Skeleton Rest Pose":
The user has two FBX files. One is in t-pose, call it "TPose.fbx". The other is an animation FBX, maybe "Walking.fbx" posed on the first frame (incorrect rest pose) and no mesh, so no bind pose.

Here is my understanding of the workflow you are proposing:

1. Open the advanced importer of TPose.fbx
2. Select "Include rests as "RESET" animation" checkbox on the Skeleton3D
3. The advanced importer will refresh and the RESET animation is now listed as an animation
4. The user selects to extract animations to a file or import as library
5. Open "Walking.fbx" in the advanced importer
6. Now select the extracted RESET animation in "Load pose"

Clearly, this "RESET" animation would always include all keys (ignore the immutable track policy), since all tracks are immutable when only one keyframe exists.

(also, is "REST" this the same thing as "RESET"? I think the similar names in all caps may be confusing me.)

**Comment by TokageItLab** [comment]
I understand that REST animation and RESET animation are different things.

RESET was supposed to define a pause at load time, but as we discussed on RocketChat, if that is not currently working and AutoPlay is working as an alternative, then I think it is acceptable to include it in RESET.

Also, it would be ideal to include that setting in the normal importer settings rather than the advanced importer.

image

Because the rest extraction itself is done outside of the Retartget process and has no direct impact on Retartget.

**Comment by lyuma** [comment]
I think I understand: if it's in the normal import settings, then it can be generated before `_pre_import` completes, so it will enforce the creation of an AnimationPlayer and a rest animation, which can then be extracted using Godot's standard animation flow (AnimationLibrary or extract animations)

Ok, so adjusting my above workflow, it would be:

1. Select TPose.fbx in the Import Dock
2. (Optional) Enable "Import as skeleton bones"
3. Enable "Generate Rest Pose Animation"
4. Do not enable humanoid import. Instead:
    1. either: Switch "Import As" to AnimationLibrary and Reimport
    2. or: Open advanced importer and selects Extract Animations and Reimport.
5. Select animation (e.g. Walking.FBX)
6. Enable "Import as skeleton bones"
7. Open advanced importer:
8. Enable BoneMap
9. Set "Rest Pose" to "External Animation"
10. Select the animation exported in step 4.
11. Click Reimport

Does this flow look correct?

**Comment by TokageItLab** [comment]
> Enable "Import as skeleton bones"

Does this mean that you implement something new? Does this mean that it uses the Skeleton as its root, unlike the import as Scene which uses the Node3D as its root?

I think it is sufficient to add the option "Import Rest as RESET" under "Remove Immutable Tracks".

**Comment by lyuma** [comment]
> Does this mean that you implement something new

No, since "Import as skeleton bones" is the feature implemented in #88819 and was already merged,

I am merely recommending to use this feature in conjunction: It should be documented as part of the recommended flow for animation import, since it will guarantee that the animation FBX contains a skeleton (otherwise, a FBX with no meshes might only contain nodes and no bones)

> Does this mean that it uses the Skeleton as its root

No, that feature does not change the root of the scene to skeleton: this created too many compatibility problems, so the root is Node3D but the children are always Skeleton3D and AnimationPlayer if animations are present.

> "Import Rest as RESET"

Sounds like a good name. I would be happy to implement this and name the resulting animation "RESET" by default.

> Is the problem when there are more than one Skeletons?

It could be confusing when there are multiple skeletons.

However, the "Import as skeleton bones" feature above will guarantee that exactly one skeleton is present, since all nodes in the scene are now bones in that single skeleton.

Generally speaking, our workflow is not well suited to scenes with multiple skeletons, so this should be discussed separately with a specific example file (I have a few but they are not designed to be retargeted). The limitation of one logical skeleton per animation file seems fairly common across several engines / file formats, so I don't think we should try to solve this right now.

**Comment by TokageItLab** [comment]
> No, since "Import as skeleton bones" is the feature implemented in https://github.com/godotengine/godot/pull/88819 and was already merged,

Okay, so it is no problem. However, please keep in mind that ""Import Rest as RESET" option may be enabled even for Import as Scene. I think we now agree.

**Comment by lyuma** [comment]
Updated this PR to remove the "Export Skeleton Rest Pose" option.

Opened #89629 to add a "Import Rest as Reset" option in the top-level import dock, which can be used to generate a compatible rest pose (t-pose) animation from fbx or similar files which did not come with one.

**Review by TokageItLab — APPROVED** [review]
LGTM

File: editor/import/3d/resource_importer_scene.cpp [hunk 8]
```diff
@@ -1157,6 +1158,74 @@ Node *ResourceImporterScene::_post_fix_node(Node *p_node, Node *p_root, HashMap<
...
+					}
+					rest_animation = anim_player->get_animation(selected_animation_name);
+					if (rest_animation.is_valid()) {
+						break;
+					}
+				}
+			} else if (int(node_settings["rest_pose/load_pose"]) == 2) {
+				Object *external_object = node_settings.get("rest_pose/external_animation_library", Variant());
+				rest_animation = external_object;
+				if (!rest_animation.is_valid()) {
```
Comment (AThousandShips) [inline editor/import/3d/resource_importer_scene.cpp:1184]:
```suggestion
				if (rest_animation.is_null()) {
```

File: editor/import/3d/resource_importer_scene.cpp [hunk 9]
```diff
@@ -1157,6 +1158,74 @@ Node *ResourceImporterScene::_post_fix_node(Node *p_node, Node *p_root, HashMap<
...
+			rest_animation_timestamp = double(node_settings.get("rest_pose/selected_timestamp", 0.0));
+			if (rest_animation.is_valid()) {
+				for (int track_i = 0; track_i < rest_animation->get_track_count(); track_i++) {
+					NodePath path = rest_animation->track_get_path(track_i);
+					StringName node_path = path.get_concatenated_names();
+					if (String(node_path).begins_with("%")) {
+						continue; // Unique node names are commonly used with retargeted animations, which we do not want to use.
+					}
+					StringName skeleton_bone = path.get_concatenated_subnames();
+					if (!skeleton_bone) {
```
Comment (AThousandShips) [inline editor/import/3d/resource_importer_scene.cpp:1205]:
```suggestion
					if (skeleton_bone == StringName()) {
```

File: editor/import/3d/resource_importer_scene.cpp [hunk 10]
```diff
@@ -1745,6 +1814,34 @@ void ResourceImporterScene::get_internal_import_options(InternalImportCategory p
 		} break;
 		case INTERNAL_IMPORT_CATEGORY_SKELETON_3D_NODE: {
 			r_options->push_back(ImportOption(PropertyInfo(Variant::BOOL, "import/skip_import", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), false));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::INT, "rest_pose/load_pose", PROPERTY_HINT_ENUM, "Default Pose,Use AnimationPlayer,Load External Animation", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), 0));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::OBJECT, "rest_pose/external_animation_library", PROPERTY_HINT_RESOURCE_TYPE, "Animation,AnimationLibrary", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), Variant()));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::STRING, "rest_pose/selected_animation", PROPERTY_HINT_ENUM, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), ""));
+			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "rest_pose/selected_timestamp", PROPERTY_HINT_RANGE, "0,1,0.001,allow_greater,suffix:s", PROPERTY_USAGE_DEFAULT), 0.0f));
```
Comment (AThousandShips) [inline editor/import/3d/resource_importer_scene.cpp:1820]:
```suggestion
			r_options->push_back(ImportOption(PropertyInfo(Variant::FLOAT, "rest_pose/selected_timestamp", PROPERTY_HINT_RANGE, "0,1,0.001,or_greater,suffix:s", PROPERTY_USAGE_DEFAULT), 0.0f));
```

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
There seems to be a build issue for the editor:
```
Error: editor/import/3d/scene_import_settings.cpp:116:7: error: 'option' was not declared in this scope; did you mean 'options'?
  116 |   if (option.name == "rest_pose/load_pose") {
      |       ^~~~~~
      |       options
Error: editor/import/3d/scene_import_settings.cpp:121:7: error: 'option' was not declared in this scope; did you mean 'options'?
  121 |   if (option.name == "rest_pose/selected_animation") {
      |       ^~~~~~
      |       options
```

**Comment by akien-mga** [comment]
Thanks!
