### PR TITLE
Use selected node type for choosing editor tab

### LINKED ISSUE #71655: Some 3D nodes will incorrectly force 3D editor when switching scene tab
### Godot version

4.0 d93b66a

### System information

Windows 10 x64

### Issue description

I have a 2D scene with some 3D nodes. The root is node 2D, most nodes are 2D, I have 2D node selected. When I switch scene tab and back, the editor switches to 3D view, even though the 2D node is still selected.

I managed to strip the scene to bare minimum. You need a Node3D with Camera3D and DirectionalLight3D children.

https://user-images.githubusercontent.com/2223172/213327465-ba07760e-6dab-43c0-96e8-5109fcc0a576.mp4

### Steps to reproduce

1. Make 2D scene
2. Add some 3D
3. This bug has a chance to happen
4. Check the repro for setup that reproduces the issue

### Minimal reproduction project

[3DBug.tscn.txt](https://github.com/godotengine/godot/files/10452297/3DBug.tscn.txt)

### PR DESCRIPTION
**Pull request by PrecisionRender**
Fixes https://github.com/godotengine/godot/issues/71655

When switching an open scene, the editor now selects a tab based on what type of node (2D/Control or 3D) the scene's last selected node is. If no node is selected, it uses the root node's type.

### CODE REVIEW

**Comment by KoBeWi** [comment]
The old heuristic could still be useful when scene has Node root.

**Comment by PrecisionRender** [comment]
@KoBeWi Right now, it simply doesn't change the editor when the scene has a Node root, or any other non-"tangible" node.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -3626,12 +3626,12 @@ void EditorNode::_set_main_scene_state(Dictionary p_state, Node *p_for_scene) {
...
-			int n2d = 0, n3d = 0;
-			_find_node_types(get_edited_scene(), n2d, n3d);
-			if (n2d > n3d) {
+			Node *editor_node = SceneTreeDock::get_singleton()->get_tree_editor()->get_selected();
+			editor_node = editor_node == nullptr ? get_edited_scene() : editor_node;
+
+			if (editor_node->is_class("Node2D") || editor_node->is_class("Control")) {
 				editor_select(EDITOR_2D);
-			} else if (n3d > n2d) {
+			} else if (editor_node->is_class("Node3D")) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3634]:
```suggestion
			} else if (Object::cast_to<Node3D>(editor_node)) {
```
Checking types this way is faster and safer. Same above.

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_node.cpp (hunk 1 above)
Comment (PrecisionRender) [reply editor/editor_node.cpp:3634]: It appears to have access to those classes. I was just using that function to stay consistent with the other similar methods in this class.

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
> Right now, it simply doesn't change the editor when the scene has a Node root, or any other non-"tangible" node.

It can affect what you see on startup. I have a scene with Node root and only 2D nodes and it opens in 3D view when I open the project. It's a test project though, so I don't really care; just saying there is a potentially unwanted effect.
