### PR TITLE
C#: Update Basis Euler angle code to match core

### LINKED ISSUE #66268: Basis' GetEuler function returns wrong angles under certain conditions
### Godot version

4.0-beta1_mono_win64

### System information

Windows 10

### Issue description

While lerping a basis and getting its euler angle I got results that visually were wrong and also seemed wrong in numbers.

Basis : [X: (0, 0,040403813, 0,9991835), Y: (1, 1,1920929E-07, 0), Z: (-1,1920929E-07, 0,9991835, -0,040403843)]
Euler: (-1,5303826,    -3,1415896,    1,5707934)

Next frame:

Basis:  [X: (0, 0, 1), Y: (1, 0, 0), Z: (0, 1, 0)]
Euler: (-1,5707964,    1,5707964,     0)

The basis are very close, but by getting the euler of the second one I expect a value more like (-1.57, 0, 1.57...).

Out of the 24 rotations I'm working with only 4 to 8 seem to be affected by this issue.

## Code:

```C#
Basis basis1 = new Basis( new Vector3(0, 0.040403813f, 0.9991835f),  new Vector3(1, 0, 0), new Vector3(0, 0.9991835f, -0.040403843f));
Basis basis2 = new Basis(  new Vector3(0, 0, 1),  new Vector3(1, 0, 0),  new Vector3(0, 1, 0) );
GD.Print("basis1:");
GD.Print( basis1 );
GD.Print("basis1.GetEuler():");
GD.Print(basis1.GetEuler());
GD.Print("basis2:");
GD.Print( basis2 );
GD.Print("basis2.GetEuler():");
GD.Print(basis2.GetEuler());
```

## Prints:

basis1:
[X: (0, 0,040403813, 0,9991835), Y: (1, 0, 0), Z: (0, 0,9991835, -0,040403843)]

basis1.GetEuler():
(-1,5303826, 3,1415927, 1,5707964)

basis2:
[X: (0, 0, 1), Y: (1, 0, 0), Z: (0, 1, 0)]

basis2.GetEuler():
(-1,5707964, 1,5707964, 0)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR brings the changes in #54084 to C#. It also solves #66268. I did some testing with these changes applied to 3.x using the test code in the OP and the output is correct.

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs [hunk 1]
```diff
@@ -799,6 +993,46 @@ internal Basis(real_t xx, real_t yx, real_t zx, real_t xy, real_t yy, real_t zy,
...
+        /// Constructs a Basis matrix from Euler angles in the specified rotation order. By default, use YXZ order (most common).
+        /// </summary>
+        /// <param name="euler">The Euler angles to use.</param>
+        /// <param name="order">The order to compose the Euler angles.</param>
+        public static Basis FromEuler(Vector3 euler, EulerOrder order = EulerOrder.YXZ)
+        {
+            real_t c, s;
+
+            c = Mathf.Cos(euler.x);
+            s = Mathf.Sin(euler.x);
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs:1006]: In .NET 6 we can use the `System.Math.SinCos`/`System.MathF.SinCos` method to calculate sin and cos together which would be faster. Note that we don't expose these methods in `Godot.Mathf`.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs [hunk 2]
```diff
@@ -244,50 +259,258 @@ public real_t Determinant()
...
+                            {
+                                euler.x = Mathf.Atan2(-Row1[2], Row2[2]);
+                                euler.y = Mathf.Asin(sy);
+                                euler.z = Mathf.Atan2(-Row0[1], Row0[0]);
+                            }
+                        }
+                        else
+                        {
+                            euler.x = Mathf.Atan2(Row2[1], Row1[1]);
+                            euler.y = -Mathf.Tau / 4.0f;
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs:309]: Note that the core implementation uses PI instead of TAU, I don't have a preference just wanted to note the inconsistency.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs (hunk 1 above)
Comment (aaronfranke) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs:1006]: This is a good idea to optimize later down the line, but I think it's worth looking over the whole C# codebase for instances like this, and also using it now would hinder cherry-picking to 3.x.

Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs:1006]: I'm not sure it would be a problem for cherry-picking since you have a dedicated PR for 3.x, but yeah optimizations can be done in a future PR.

Comment (aaronfranke) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs:1006]: Sorry, I should've clarified, I meant that if we added `Godot.Mathf.SinCos` and used it in more places, then any place we use it becomes slightly harder to cherry-pick.

**Review by neikeq — APPROVED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs [hunk 3]
```diff
@@ -3,6 +3,21 @@
...
+    /// </summary>
+    public enum EulerOrder
+    {
+        XYZ,
+        XZY,
+        YXZ,
+        YZX,
+        ZXY,
+        ZYX
+    };
```
Comment (neikeq) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs:19]: Is this used anywhere outside Basis? If not, we may want to move it inside the Basis struct, like `Vector3.Axis`.

Comment (aaronfranke) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs:19]: The same values are used in Node3D already, but I don't think it's typed as the enum (just int). Also, the plan is to use it in Quaternion soon, see https://github.com/godotengine/godot/pull/66747 and https://github.com/aaronfranke/godot/tree/quat-euler-order

**Comment by akien-mga** [comment]
Thanks!
