### PR TITLE
Fix editor inspector refresh not working

### LINKED ISSUE #41675: Editor Inspector does not auto-refresh
**Godot version:**
4.0 64e0a1290

**OS/device including version:**
WIN 10

**Issue description:**
Editor Inspector does not auto refresh.

**Steps to reproduce:**
The below script, also found in MRP zip is a tool script that auto increments and exported variable. As you can see in the console `prints`, the count is incrementing but the inspector does not show it.

```gdscript
@tool
extends Node2D

@export
var count = 0

var accum: float = 0;
func _process(delta):
	accum += delta

	if accum > 1:
		count += 1
		print("Upped counter to %s" % count)
		accum = 0
```

**Minimal reproduction project:**
[EditorInspRefresh.zip](https://github.com/godotengine/godot/files/5156394/EditorInspRefresh.zip)

I already have fixed this quickly as I needed it for a PR I am working on but will look at it again and submit a proper PR. The issue is that the timer counter for the refresh in `EditorInspector` never actually starts...

### PR DESCRIPTION
**Pull request by EricEzaM**
Closes #41675

Inspector will cache refresh interval value so it does not need to `EDITOR_GET` after every interval.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -1969,7 +1969,7 @@ void EditorInspector::refresh() {
 	if (refresh_countdown > 0 || changing) {
 		return;
 	}
-	refresh_countdown = EditorSettings::get_singleton()->get("docks/property_editor/auto_refresh_interval");
+	refresh_countdown = refresh_interval_cache;
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:1972]: That means that a restart is needed to take changes into account. Is the setting defined with `EDITOR_DEF_RST`?

Comment (EricEzaM) [reply editor/editor_inspector.cpp:1972]: No, it's just set with `_initial_set("docks/property_editor/auto_refresh_interval", 0.3);` in `editor_settings.cpp`. But I don't follow what you mean here..

> That means that a restart

What means it needs a restart?

In my testing, I changed the refresh interval value in the editor settings window to 5 seconds and it was immediately applied, and the value in my test scene (see linked issue) was only refreshing every 5 seconds. I then changed it back to 0.3 and the value started refreshing every 0.3 seconds, as expected.

Comment (EricEzaM) [reply editor/editor_inspector.cpp:1972]: No, it's just set with `_initial_set("docks/property_editor/auto_refresh_interval", 0.3);` in `editor_settings.cpp`. But I don't follow what you mean here..

> That means that a restart

What means it needs a restart?

In my testing, I changed the refresh interval value in the editor settings window to 5 seconds and it was immediately applied, and the value in my test scene (see linked issue) was only refreshing every 5 seconds. I then changed it back to 0.3 and the value started refreshing every 0.3 seconds, as expected.

Comment (akien-mga) [reply editor/editor_inspector.cpp:1972]: Well this is set in `NOTIFICATION_READY`, so it would run only once normally. Or is the EditorInspector recreated when settings change?

Comment (EricEzaM) [reply editor/editor_inspector.cpp:1972]: It gets set both in `NOTIFICATION_READY` and `NOTIFICATION_EDITOR_SETTINGS_CHANGED`

Comment (akien-mga) [reply editor/editor_inspector.cpp:1972]: Ah indeed, I missed it while reviewing on phone. All good then.

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
This needs to be reverted, as it misunderstood what refresh is for. Its causing the editor to redraw all the time and this is extremely inefficient.

**Comment by reduz** [comment]
The correct solution is a smart refresh, checking if properties changed and only then update them, but this is a much bigger undertaking

**Comment by reduz** [comment]
I think you need different logic here. There is a refresh() call which sets the refresh countdown. As you will be refreshing all the time, you can change that to a bool force_update_property_editors; to true instead of setting the refresh countdown.

Then in the refresh logic, you want something like this:

for (Map<StringName, List<EditorProperty *>>::Element *F = editor_property_map.front(); F; F = F->next()) {
	for (List<EditorProperty *>::Element *E = F->get().front(); E; E = E->next()) {
		if (E->get()->has_changed() || force_update_property_editors) {
			E->get()->update_property();
			E->get()->update_reload_status();
		}
	}
}

force_update_property_editors = false;
```

For the has_changed() method, I think EditorProperty need to be able to figure out when the value inside the object differs from what was edited. One way could be caching the value in EditorProperty::emit_changed, another is doing this manually in every editor which may be too much.

**Comment by akien-mga** [comment]
Removing cherry-pick label as this was reverted.
