### PR TITLE
Fix bitwise-and eval not updating return type

### LINKED ISSUE #44411: GDScript bitwise AND evaluating to Nil when using variables
**Godot version:**

4.0.dev 94b15bfb89

**OS/device including version:**

Windows 10

**Issue description:**

I'm trying to use bitwise AND in a project to check flags. However, this operator does not seem to work unless using integer literals.

Edit: From my comment below, using this operator can also cause a crash if an Array or Dictionary is declared earlier. Probably can use other types that use refs.

**Steps to reproduce:**

Using the code:
```gdscript
var one: int = 1
var also_one: int = 1

print(1 & 1)
print(one & 1)
print(1 & one)
print(one & also_one)
```
prints the following:

> 1
> Null
> Null
> Null

**Minimal reproduction project:**

[GDSBitAndMinRep.zip](https://github.com/godotengine/godot/files/5699285/GDSBitAndMinRep.zip)

### PR DESCRIPTION
**Pull request by briansemrau**
Fixes https://github.com/godotengine/godot/issues/44411.
This was just a missing line of code in `OperatorEvaluatorBitAnd::validated_evaluate`. It's present in all other operator implementations of `validated_evaluate`.

Without this line of code, the bitwise-and operator tries to assign the return value as an int even if the `r_ret` variant isn't an int type. If `r_ret` happens to be an int it just works. But it is possible the variant is sometimes an array or other ref type which may crash the engine by modifying a freed ref.

### CODE REVIEW

**Comment by briansemrau** [comment]
@reduz is the author of the original changes, so maybe he can review

File: core/variant/variant_op.cpp [hunk 1]
```diff
@@ -318,6 +318,7 @@ class OperatorEvaluatorBitAnd {
 		r_valid = true;
 	}
 	static void validated_evaluate(const Variant *left, const Variant *right, Variant *r_ret) {
+		VariantTypeChanger<R>::change(r_ret);
```
Comment (Calinou) [inline core/variant/variant_op.cpp:321]: It would be good to add a comment to explain why this was added, as this isn't 100% obvious at a glance.

Comment (briansemrau) [reply core/variant/variant_op.cpp:321]: I modified the comment to hopefully make it more clear.

Comment (Calinou) [reply core/variant/variant_op.cpp:321]: I still think it'd be better to have a code comment, as not everyone will jump to `git blame` instinctively if they reach a line of code they don't understand.

Comment (briansemrau) [reply core/variant/variant_op.cpp:321]: I don't necessarily disagree and I did just update the description to make this next point clear, but this line is present for every operator and isn't unique to bit-and. I'd be willing to add a comment to make the importance of this line more clear, but I don't see where it would make sense to add unless copied in-place for every operator.

Comment (Calinou) [reply core/variant/variant_op.cpp:321]: Alright, makes sense then.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!
