### PR TITLE
Fixed colour region calculation for the first line, issue 18104

### LINKED ISSUE #18104: Shader editor no longer does syntax highlighting (Regression)
**Godot version:**

ca1312d

**OS/device including version:**

Antergos x86_64

**Issue description:**

image

**Steps to reproduce:**
1. Open existing shader, or create a new one.

**Minimal reproduction project:**

Try with this basic shader:
```
shader_type canvas_item;
void fragment(){
COLOR=vec4(1.0);
}
```

### PR DESCRIPTION
**Pull request by Paulb23**
Fixed colour region cache not calculating the first line correctly.

closes #18104

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -4023,6 +4023,9 @@ int TextEdit::_is_line_in_region(int p_line) {
 
 	// calculate up to line we need and update the cache along the way.
 	int in_region = color_region_cache[previous_line];
+	if (previous_line = -1) {
```
Comment (akien-mga) [inline scene/gui/text_edit.cpp]: Don't you mean `==`?

Comment (Paulb23) [reply scene/gui/text_edit.cpp]: whoops! Fixed!
