### PR TITLE
Fix Editor/Debugger connection problems.

### LINKED ISSUE #7544: Remote debugger not working on Windows
**Operating system or device - Godot version:**

Godot.64bit  2.1 branch (9c8ecb45f8516a2)
compiled on Windows 7 with MinGW-w64, 4.8.3

**Issue description**:

gdscript remote debugger cannot connect to editor:

```
Remote Debugger: Connection failed with status: 3'', retrying in 1 sec.
Remote Debugger: Connection failed with status: 3'', retrying in 1 sec.
Remote Debugger: Connection failed with status: 3'', retrying in 1 sec.
Remote Debugger: Unable to connect
```

Reverting IPv6 commits enables the debugger connection again.
Local debugger is working.
I have nothing configured for IPv6 support and never used it with Windows 7.

**Related issue**
#7545

### PR DESCRIPTION
**Pull request by Faless**
In this PR:

- `_socket_create` now falls back to IPv4 when requesting type IP_ANY and the current machine does not allow IPv6 sockets
- Fix local interface address detection (we where recognizing non-INET addresses as local IP addresses)
- The editor now respects the `debug_host` option pushing it as the `rdebug` argument host.
- The `network/debug_host` option is now renamed to `network/debug/remote_host` for consistency with `network/debug/remote_port`. (do you like this location? Do you want to move it to `run/debug`?)

Fixes #7544 #8563 #5828
Possibly also #2604 (but I think that the `gethostbyname` error is actually unrelated to the real problem).

### CODE REVIEW

File: drivers/unix/socket_helpers.h [hunk 1]
```diff
@@ -100,13 +100,21 @@ static size_t _set_listen_sockaddr(struct sockaddr_storage *p_addr, int p_port,
...
 
 	ERR_FAIL_COND_V(p_type > IP::TYPE_ANY || p_type < IP::TYPE_NONE, ERR_INVALID_PARAMETER);
 
 	int family = p_type == IP::TYPE_IPV4 ? AF_INET : AF_INET6;
 	int sockfd = socket(family, type, protocol);
 
+	if (sockfd == -1 && p_type == IP::TYPE_ANY) {
+		// Careful here, changing the referenced parameter so the caller knows that we are using an IPv4 socket
+		// in place of a dual stack one, and further calls to _set_sock_addr will work as expected.
+		p_type = IP::TYPE_IPV4;
```
Comment (Faless) [inline drivers/unix/socket_helpers.h]: I don't really like doing this since it makes the code a bit more obscure, but it saves us a lot of code in the various networking classes since they already use a sock_type instance variable which is passed to `_socket_create`.

If you can think of a better solution I'll offer you (whomever you might be) a :beer:  at the next Godot event :wink:
