### PR TITLE
Toggle control expand flag directly via top bar

### LINKED ISSUE #81726: Control toolbar, "align with expand" checkbox does not set/unset the flag for container sizing
### Godot version

4.2.dev.4

### System information

Windows 11

### Issue description

In the control toolbar when you toggle the checkbox "align with expand", it does not set/unset the expand flag in the container sizing

### Steps to reproduce

https://github.com/godotengine/godot/assets/84369217/18a3cf33-c0b9-436d-bb48-7d3890a539eb

### Minimal reproduction project

If required I will provide it

### PR DESCRIPTION
**Pull request by RedMser**
Fixes #81726

- Change the label from "Align with Expand" to just "Expand".
- Turns "Expand" checkbox to a check buton, to make UX clearer.
- Opening the container sizing popup loads the current value for the "Expand" check button, based on user's selection.
- Clicking on the check button immediately toggles the flag for the selected controls.
- Fix (unreported) bug that redo does nothing when changing shrink flags.

24-05-09_14-28-15_godot windows editor x86_64_Aldabratortoise

### CODE REVIEW

**Comment by RedMser** [comment]
CC @YuriSizov since you created #63358 which this PR expands (hah) upon.

**Comment by YuriSizov** [comment]
The current system was made this way on purpose, so I'm not sure if this is a good change. No other button in this or anchors' popup behaves like that and updates to match the state of the selected nodes.

**Comment by RedMser** [comment]
I tried working with the current system (I'm working mainly on applications, so very UI-heavy stuff). The new top bar felt very cumbersome to use without my change in place.

While from a programming standpoint I totally understand why it was created this way, for actual users creating UIs I don't think this is a good design. Users like to get instant feedback on their changes, see what each option does and how it affects the layout.

An alternative that does not involve updating based on selection state would be to have a "Toggle Expand" button, which does not show the state, but only requires a single click to toggle the flag instead of two.

If you want, I can open a proposal for this change first and get some more opinions in.

**Comment by YuriSizov** [comment]
@RedMser Yes, those are the options that we have, and the same ones I had to consider before arriving to the current state. I also work primarily with UI in Godot and understand the workflows. But none of these options are good in my opinion, including the current state. I just found it to be more consistent than others, but ultimately I don't like any of them.

So I'm all for a better option, I'm just not sure that this is better (because it's inconsistent with the rest).

File: editor/plugins/control_editor_plugin.cpp [hunk 1]
```diff
@@ -650,6 +650,10 @@ void SizeFlagPresetPicker::_preset_button_pressed(const int p_preset) {
 	emit_signal("size_flags_selected", flags);
 }
 
+void SizeFlagPresetPicker::_expand_button_pressed() {
+	emit_signal("expand_toggled", expand_button->is_pressed());
```
Comment (YuriSizov) [inline editor/plugins/control_editor_plugin.cpp:654]: I'd call it `expand_flag...` instead of `expand...` in signals and methods, so it's consistent with `size_flags...`.

**Comment by RedMser** [comment]
To address the issue of consistency, it might help to make the presets/size flags buttons also reflect the selected nodes' current values (by making them toggle buttons, part of a button group)?

And in case of differing values between selected nodes, or when one isn't using a preset, none of the options would be highlighted.

> And to be clear, if this is otherwise approved, I'm not going to die on that hill. 🙃 If this feels better, then it's better.

I'll gladly help working towards a solution everyone's happy with! So far, every change to the UI system was an improvement to the previous iteration, so I'm confident we'll get there, hopefully before 4.0 releases. 🙂

**Comment by YuriSizov** [comment]
> To address the issue of consistency, it might help to make the presets/size flags buttons also reflect the selected nodes' current values (by making them toggle buttons, part of a button group)?

We can give it a try.

Would also be nice to somehow indicate that "expand" is not a standalone flag and is changing the main flag's behavior. Maybe with a highlight like I did for the movie writer button (though that may be too much).

**Comment by KoBeWi** [comment]
Consistency aside, IMO the main problem with this change is that the state of the button is kind of undetermined. It's obvious when you select one Control, but if you have multiple selected controls or non-Control nodes mixed in it becomes messy.

Another option to consider, not mentioned here, is making the expand flag use a modifier key. So the checkbox could be replaced with a label "Hold Shift to set with Expand" (though it's long).

If not, at least the checkbox could be changed to CheckButton, to better convey immediate action.

**Comment by ajreckof** [comment]
> Consistency aside, IMO the main problem with this change is that the state of the button is kind of undetermined. It's obvious when you select one Control, but if you have multiple selected controls or non-Control nodes mixed in it becomes messy.

This is not a real problem as this is already the case in the Inspector and I'm assuming this is just doing the same as the Inspector which just chooses a value. I feel like this is okay as this how most things work in those case.
Capture d’écran 2024-04-26 à 03 30 49

> If not, at least the checkbox could be changed to CheckButton, to better convey immediate action.

I agree check button would be better here

File: editor/plugins/control_editor_plugin.cpp [hunk 2]
```diff
@@ -959,6 +1006,33 @@ void ControlEditorToolbar::_selection_changed() {
...
+		int nb_h_expand = 0;
+		int nb_v_expand = 0;
+
+		List<Node *> selection = editor_selection->get_selected_node_list();
+		for (Node *E : selection) {
+			Control *control = Object::cast_to<Control>(E);
+			if (!control) {
+				continue;
+			}
+			if (!Object::cast_to<Container>(control->get_parent())) {
```
Comment (KoBeWi) [inline editor/plugins/control_editor_plugin.cpp:1021]: Expand flag can be set outside containers (mostly for scene root that's going to be inside container later), so this check shouldn't be here I think.

**Comment by RedMser** [comment]
Sorry it took me a while. Updated to use a check button, since I think this UX is clearer.

**Comment by KoBeWi** [comment]
Something is wrong with undo:

https://github.com/godotengine/godot/assets/2223172/6f1012db-9672-4dba-8003-bddf636aa8a3

File: editor/plugins/control_editor_plugin.h [hunk 3]
```diff
@@ -36,6 +36,7 @@
 #include "scene/gui/box_container.h"
 #include "scene/gui/button.h"
 #include "scene/gui/check_box.h"
+#include "scene/gui/check_button.h"
```
Comment (KoBeWi) [inline editor/plugins/control_editor_plugin.h:39]: This should be forward declared.

Comment (RedMser) [reply editor/plugins/control_editor_plugin.h:39]: I assume you mean removing the include and inserting `class CheckButton;` into the header? It does not seem to work:

```
editor\plugins\control_editor_plugin.cpp(656): error C2027: use of undefined type 'CheckButton'
B:\Godot\editor\plugins\control_editor_plugin.h(48): note: see declaration of 'CheckButton'
editor\plugins\control_editor_plugin.cpp(664): error C2027: use of undefined type 'CheckButton'
B:\Godot\editor\plugins\control_editor_plugin.h(48): note: see declaration of 'CheckButton'
editor\plugins\control_editor_plugin.cpp(673): error C2027: use of undefined type 'CheckButton'
B:\Godot\editor\plugins\control_editor_plugin.h(48): note: see declaration of 'CheckButton'
editor\plugins\control_editor_plugin.cpp(675): error C2027: use of undefined type 'CheckButton'
B:\Godot\editor\plugins\control_editor_plugin.h(48): note: see declaration of 'CheckButton'
...
```

Comment (akien-mga) [reply editor/plugins/control_editor_plugin.h:39]: You also need to add the include in the `.cpp`.

The idea with forward-declaring in the header is to reduce bringing dependencies around in places that include that header just for the class definition. If a dependency is only needed in the implementation, it can be forward-declared and included in the .cpp.

Comment (RedMser) [reply editor/plugins/control_editor_plugin.h]: Ahh okay, thank you for explaining! :pray:

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
