### PR TITLE
[Debugger] Fix scene debugger crash when editor shortcuts are invalid

### LINKED ISSUE #100182: Project crashes when pressing any key in v4.4-dev6 and when rolling back to v4.4-dev5
### Tested versions

- v4.4.dev.custom_build.0c45ace15
  - Build made to revert the CPU consumption from 4.4-dev5.
- v4.4-dev6

### System information

windows 10, Forward+, GTX 1660, Ryzen 3300x, 16GB RAM

### Issue description

If I execute the project and press any keys in the keyboard, the project crashes. Leaving the following dump:

```
Godot Engine v4.4.dev6.official.1f47e4c4e - https://godotengine.org
Vulkan 1.3.289 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1660

(Virtual Joystick) The Project Setting 'emulate_mouse_from_touch' should be set to False
(Virtual Joystick) The Project Setting 'emulate_touch_from_mouse' should be set to True

================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.4.dev6.official (1f47e4c4e3a09a422e96880a7918d986dd575a63)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
[7] error(-1): no debug info in PE/COFF executable
[8] error(-1): no debug info in PE/COFF executable
[9] error(-1): no debug info in PE/COFF executable
[10] error(-1): no debug info in PE/COFF executable
[11] error(-1): no debug info in PE/COFF executable
[12] error(-1): no debug info in PE/COFF executable
[13] error(-1): no debug info in PE/COFF executable
[14] error(-1): no debug info in PE/COFF executable
[15] error(-1): no debug info in PE/COFF executable
[16] error(-1): no debug info in PE/COFF executable
[17] error(-1): no debug info in PE/COFF executable
[18] error(-1): no debug info in PE/COFF executable
[19] error(-1): no debug info in PE/COFF executable
[20] error(-1): no debug info in PE/COFF executable
[21] error(-1): no debug info in PE/COFF executable
[22] error(-1): no debug info in PE/COFF executable
[23] error(-1): no debug info in PE/COFF executable
[24] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================
```

```
Godot Engine v4.4.dev.custom_build.0c45ace15 (2024-11-22 20:54:49 UTC) - https://godotengine.org
Vulkan 1.3.289 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1660

(Virtual Joystick) The Project Setting 'emulate_mouse_from_touch' should be set to False
(Virtual Joystick) The Project Setting 'emulate_touch_from_mouse' should be set to True
ERROR: 1 RID allocations of type 'class RendererRD::TextureStorage::Texture' were leaked at exit.
ERROR: Parameter "RenderingServer::get_singleton()" is null.
   at: CompressedTexture2D::~CompressedTexture2D (scene\resources\compressed_texture.cpp:464)
ing the bug to the project developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
Godot Engine v4.4.dev.custom_build.0c45ace15 (2024-11-22 20:54:49 UTC) - https://godotengine.org
Vulkan 1.3.289 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1660

(Virtual Joystick) The Project Setting 'emulate_mouse_from_touch' should be set to False
(Virtual Joystick) The Project Setting 'emulate_touch_from_mouse' should be set to True
ERROR: 1 RID allocations of type 'class RendererRD::TextureStorage::Texture' were leaked at exit.
ERROR: Parameter "RenderingServer::get_singleton()" is null.
   at: CompressedTexture2D::~CompressedTexture2D (scene\resources\compressed_texture.cpp:464)
ing the bug to the project developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

I was using 4.4-dev5 as I needed a new feature regarding RPCs. I had to go to v4.4.dev.custom_build.0c45ace15 to revert the Clock Syncing changes that were making impossible to work in my project. I then upgraded to 4.4-dev6.

Now, the project crashes even if I go back to v4.4.dev.custom_build.0c45ace15.

I've tried deleting the `.godot` , `appdata/local/godot` and the `appdata/roaming/godot/app_userdata/_project_name_/`folder after rolling back to v4.4.dev.custom_build.0c45ace15, but still crashes.

### Steps to reproduce

:/

### Minimal reproduction project (MRP)

This is happening in my main project.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #100182.

### CODE REVIEW

**Review by Faless — APPROVED** [review]
LGTM

File: scene/debugger/scene_debugger.cpp [hunk 1]
```diff
@@ -96,7 +96,7 @@ void SceneDebugger::deinitialize() {
 #ifdef DEBUG_ENABLED
 void SceneDebugger::_handle_input(const Ref<InputEvent> &p_event, const Ref<Shortcut> &p_shortcut) {
 	Ref<InputEventKey> k = p_event;
-	if (k.is_valid() && k->is_pressed() && !k->is_echo() && p_shortcut->matches_event(k)) {
+	if (k.is_valid() && k->is_pressed() && !k->is_echo() && p_shortcut.is_valid() && p_shortcut->matches_event(k)) {
```
Comment (AThousandShips) [inline scene/debugger/scene_debugger.cpp:99]:
```suggestion
	if (k.is_valid() && p_shortcut.is_valid() && k->is_pressed() && !k->is_echo() && p_shortcut->matches_event(k)) {
```
Minor but might be best to get the null checks out of the way immediately

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
