### PR TITLE
[4.0] Add readable export errors.

### LINKED ISSUE #61392: Godot 3.5 rc2 export template error for Win Desktop builds
### Godot version

3.5 rc2

### System information

Windows 10

### Issue description

On Godot 3.5 rc2, when trying to build for Windows Desktop, it throws the following error:

GodotExportBug

I've tried redownloading the export templates multiple times, but the problem persists on multiple projects.

Happens with 3.5 rc1 as well.

### Steps to reproduce

Build any project using Godot 3.5 rc2 export templates.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
`master` version of #61624

Adds readable errors to the export dialog and log, instead of the misleading `missing/corrupted templates` or `configuration error` error that's currently displayed.

export_all

Fixes https://github.com/godotengine/godot/issues/61392

### CODE REVIEW

File: editor/editor_export.cpp [hunk 1]
```diff
@@ -252,6 +253,83 @@ String EditorExportPreset::get_script_encryption_key() const {
...
+bool EditorExportPlatform::fill_log_messages(RichTextLabel *p_log, Error p_err) {
+	bool has_messages = false;
+
+	int msg_count = get_message_count();
+
+	p_log->add_text(TTR("Project export for the platform") + " \"");
+	p_log->add_image(get_logo(), 16 * EDSCALE, 16 * EDSCALE, Color(1.0, 1.0, 1.0), INLINE_ALIGNMENT_CENTER);
+	p_log->add_text(" ");
+	p_log->add_text(get_name());
+	p_log->add_text("\" - ");
```
Comment (akien-mga) [inline editor/editor_export.cpp:265]: It's a bit tricky for translation with the platform name added later as some languages might need to place it somewhere else to respect the natural flow of e.g. "Project export for platform Windows". It could use `vformat` but then you can't easily add the logo, which was a nice touch.

Maybe adding a colon to force a syntactic break in the sentence would work better, and the quotes can then be removed:

```suggestion
	p_log->add_text(TTR("Project export for platform:") + " ");
	p_log->add_image(get_logo(), 16 * EDSCALE, 16 * EDSCALE, Color(1.0, 1.0, 1.0), INLINE_ALIGNMENT_CENTER);
	p_log->add_text(" ");
	p_log->add_text(get_name());
	p_log->add_text(" - ");
```

File: editor/editor_export.cpp [hunk 2]
```diff
@@ -1162,14 +1243,16 @@ Error EditorExportPlatform::save_pack(const Ref<EditorExportPreset> &p_preset, b
 		f = FileAccess::open(p_path, FileAccess::WRITE);
 		if (f.is_null()) {
 			DirAccess::remove_file_or_error(tmppath);
-			ERR_FAIL_V(ERR_CANT_CREATE);
+			add_message(EXPORT_MESSAGE_ERROR, TTR("Save PCK"), vformat(TTR("Can't open file to read from path `%s`."), tmppath));
```
Comment (akien-mga) [inline editor/editor_export.cpp:1246]:
```suggestion
			add_message(EXPORT_MESSAGE_ERROR, TTR("Save PCK"), vformat(TTR("Can't open file to read from path \"%s\"."), tmppath));
```

Comment (akien-mga) [reply editor/editor_export.cpp:1246]: And same for the other occurrences.

File: editor/project_export.h [hunk 3]
```diff
@@ -73,7 +73,8 @@ class ProjectExportDialog : public ConfirmationDialog {
 	Button *button_export = nullptr;
 	bool updating = false;
 
-	AcceptDialog *error_dialog = nullptr;
+	RichTextLabel *result_dialog_log;
+	AcceptDialog *result_dialog;
```
Comment (akien-mga) [inline editor/project_export.h:77]:
```suggestion
	RichTextLabel *result_dialog_log = nullptr;
	AcceptDialog *result_dialog = nullptr;
```

File: editor/editor_run_native.h [hunk 4]
```diff
@@ -32,11 +32,16 @@
...
 #include "scene/gui/box_container.h"
+#include "scene/gui/dialogs.h"
 #include "scene/gui/menu_button.h"
+#include "scene/gui/rich_text_label.h"
 
 class EditorRunNative : public HBoxContainer {
 	GDCLASS(EditorRunNative, HBoxContainer);
 
+	RichTextLabel *result_dialog_log;
+	AcceptDialog *result_dialog;
```
Comment (akien-mga) [inline editor/editor_run_native.h:43]:
```suggestion
	RichTextLabel *result_dialog_log = nullptr;
	AcceptDialog *result_dialog = nullptr;
```

File: platform/android/export/export_plugin.cpp [hunk 5]
```diff
@@ -2335,7 +2335,7 @@ Error EditorExportPlatformAndroid::sign_apk(const Ref<EditorExportPreset> &p_pre
 	String apksigner = get_apksigner_path();
 	print_verbose("Starting signing of the " + export_label + " binary using " + apksigner);
 	if (!FileAccess::exists(apksigner)) {
-		EditorNode::add_io_error(vformat(TTR("'apksigner' could not be found.\nPlease check the command is available in the Android SDK build-tools directory.\nThe resulting %s is unsigned."), export_label));
+		add_message(EXPORT_MESSAGE_WARNING, TTR("Code Signing"), vformat(TTR("'apksigner' could not be found. Please check the command is available in the Android SDK build-tools directory. The resulting %s is unsigned."), export_label));
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:2338]: Reads better to me with:
```suggestion
		add_message(EXPORT_MESSAGE_WARNING, TTR("Code Signing"), vformat(TTR("'apksigner' could not be found. Please check that the command is available in the Android SDK build-tools directory. The resulting %s is unsigned."), export_label));
```

File: platform/android/export/export_plugin.cpp [hunk 6]
```diff
@@ -2545,13 +2552,13 @@ Error EditorExportPlatformAndroid::export_project_helper(const Ref<EditorExportP
...
 			if (f.is_null()) {
-				EditorNode::get_singleton()->show_warning(TTR("Trying to build from a custom built template, but no version info for it exists. Please reinstall from the 'Project' menu."));
+				add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), TTR("Trying to build from a custom built template, but no version info for it exists. Please reinstall from the 'Project' menu."));
 				return ERR_UNCONFIGURED;
 			}
 			String version = f->get_line().strip_edges();
 			print_verbose("- build version: " + version);
 			if (version != VERSION_FULL_CONFIG) {
-				EditorNode::get_singleton()->show_warning(vformat(TTR("Android build version mismatch:\n   Template installed: %s\n   Godot Version: %s\nPlease reinstall Android build template from 'Project' menu."), version, VERSION_FULL_CONFIG));
+				add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Android build version mismatch: Template installed: %s Godot Version: %s. Please reinstall Android build template from 'Project' menu."), version, VERSION_FULL_CONFIG));
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:2561]:
```suggestion
				add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Android build version mismatch: Template installed: %s, Godot version: %s. Please reinstall Android build template from 'Project' menu."), version, VERSION_FULL_CONFIG));
```

File: platform/android/export/export_plugin.cpp [hunk 7]
```diff
@@ -2706,7 +2713,7 @@ Error EditorExportPlatformAndroid::export_project_helper(const Ref<EditorExportP
 
 		int result = EditorNode::get_singleton()->execute_and_show_output(TTR("Building Android Project (gradle)"), build_command, cmdline);
 		if (result != 0) {
-			EditorNode::get_singleton()->show_warning(TTR("Building of Android project failed, check output for the error.\nAlternatively visit docs.godotengine.org for Android build documentation."));
+			add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), TTR("Building of Android project failed, check output for the error.\nAlternatively visit docs.godotengine.org for Android build documentation."));
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:2716]: You did not remove `\n` here, I don't know if it's a requirement of the new system or not.

File: platform/android/export/export_plugin.cpp [hunk 8]
```diff
@@ -2758,7 +2765,7 @@ Error EditorExportPlatformAndroid::export_project_helper(const Ref<EditorExportP
 			src_apk = find_export_template("android_release.apk");
 		}
 		if (src_apk.is_empty()) {
-			EditorNode::add_io_error(vformat(TTR("Package not found: %s"), src_apk));
+			add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Package not found: `%s`."), src_apk));
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:2768]:
```suggestion
			add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Package not found: \"%s\"."), src_apk));
```

File: platform/android/export/export_plugin.cpp [hunk 9]
```diff
@@ -2776,7 +2783,7 @@ Error EditorExportPlatformAndroid::export_project_helper(const Ref<EditorExportP
 
 	unzFile pkg = unzOpen2(src_apk.utf8().get_data(), &io);
 	if (!pkg) {
-		EditorNode::add_io_error(vformat(TTR("Could not find template APK to export:\n%s"), src_apk));
+		add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Could not find template APK to export: `%s`."), src_apk));
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:2786]:
```suggestion
		add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Could not find template APK to export: \"%s\"."), src_apk));
```

File: platform/android/export/export_plugin.cpp [hunk 10]
```diff
@@ -2925,7 +2932,7 @@ Error EditorExportPlatformAndroid::export_project_helper(const Ref<EditorExportP
 		if (apk_expansion) {
 			err = save_apk_expansion_file(p_preset, p_debug, p_path);
 			if (err != OK) {
-				EditorNode::add_io_error(TTR("Could not write expansion package file!"));
+				add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Could not write expansion package file!")));
```
Comment (akien-mga) [inline platform/android/export/export_plugin.cpp:2935]: Doesn't need `vformat`. Nor the other ones below.

File: platform/javascript/export/export_plugin.cpp [hunk 11]
```diff
@@ -38,12 +38,12 @@ Error EditorExportPlatformJavaScript::_extract_template(const String &p_template
 	unzFile pkg = unzOpen2(p_template.utf8().get_data(), &io);
 
 	if (!pkg) {
-		EditorNode::get_singleton()->show_warning(TTR("Could not open template for export:") + "\n" + p_template);
+		add_message(EXPORT_MESSAGE_ERROR, TTR("Prepare Templates"), vformat(TTR("Could not open template for export: `%s`."), p_template));
```
Comment (akien-mga) [inline platform/javascript/export/export_plugin.cpp:41]:
```suggestion
		add_message(EXPORT_MESSAGE_ERROR, TTR("Prepare Templates"), vformat(TTR("Could not open template for export: \"%s\"."), p_template));
```

Comment (akien-mga) [reply platform/javascript/export/export_plugin.cpp:41]: And more below.

File: platform/linuxbsd/export/export_plugin.cpp [hunk 12]
```diff
@@ -35,7 +35,10 @@
 
 Error EditorExportPlatformLinuxBSD::_export_debug_script(const Ref<EditorExportPreset> &p_preset, const String &p_app_name, const String &p_pkg_name, const String &p_path) {
 	Ref<FileAccess> f = FileAccess::open(p_path, FileAccess::WRITE);
-	ERR_FAIL_COND_V(f.is_null(), ERR_CANT_CREATE);
+	if (f.is_null()) {
+		add_message(EXPORT_MESSAGE_ERROR, TTR("Debug Script Export"), vformat(TTR("Could not open file `%s`."), p_path));
```
Comment (akien-mga) [inline platform/linuxbsd/export/export_plugin.cpp:39]:
```suggestion
		add_message(EXPORT_MESSAGE_ERROR, TTR("Debug Script Export"), vformat(TTR("Could not open file \"%s\"."), p_path));
```
And some more in that file.

File: platform/linuxbsd/export/export_plugin.cpp [hunk 13]
```diff
@@ -196,5 +204,9 @@ Error EditorExportPlatformLinuxBSD::fixup_embedded_pck(const String &p_path, int
 
 	memfree(strings);
 
-	return found ? OK : ERR_FILE_CORRUPT;
+	if (!found) {
+		add_message(EXPORT_MESSAGE_ERROR, TTR("PCK Embeding"), TTR("`pck` section not found."));
```
Comment (akien-mga) [inline platform/linuxbsd/export/export_plugin.cpp:208]:
```suggestion
		add_message(EXPORT_MESSAGE_ERROR, TTR("PCK Embeding"), TTR("Executable \"pck\" section not found."));
```

File: platform/osx/export/export_plugin.cpp [hunk 14]
```diff
@@ -261,7 +261,8 @@ void EditorExportPlatformOSX::_make_icon(const Ref<Image> &p_icon, Vector<uint8_
 				if (f.is_null()) {
 					// Clean up generated file.
 					DirAccess::remove_file_or_error(path);
-					ERR_FAIL();
+					add_message(EXPORT_MESSAGE_ERROR, TTR("Icon Creation"), vformat(TTR("Could not open icon file `%s`."), path));
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.cpp:264]: Quotes in that file too.

File: platform/osx/export/export_plugin.cpp [hunk 15]
```diff
@@ -441,18 +442,25 @@ Error EditorExportPlatformOSX::_notarize(const Ref<EditorExportPreset> &p_preset
...
-		print_line("          \"xcrun stapler staple <app path>\"");
+		int next_nl = str.find("\n", rq_offset);
+		String request_uuid = (next_nl == -1) ? str.substr(rq_offset + 14, -1) : str.substr(rq_offset + 14, next_nl - rq_offset - 14);
+		add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), vformat(TTR("Notarization request UUID: `%s`"), request_uuid));
+		add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), TTR("The notarization process generally takes less than an hour. When the process is completed, you'll receive an email."));
+		add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t" + TTR("You can check progress manually by opening a Terminal and running the following command:"));
+		add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t\t\"xcrun altool --notarization-history 0 -u <your email> -p <app-specific pwd>\"");
+		add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t" + TTR("Run the following command to staple the notarization ticket to the exported application (optional):"));
+		add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t\t\"xcrun stapler staple <app path>\"");
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.cpp:463]: Feels like it would be nice to properly support multiline messages. I guess the table formatting in the RTL makes it a bit tricky?

File: platform/osx/export/export_plugin.cpp [hunk 16]
```diff
@@ -797,21 +818,33 @@ Error EditorExportPlatformOSX::export_project(const Ref<EditorExportPreset> &p_p
 	if (err == OK) {
 		print_verbose("Creating " + tmp_app_path_name + "/Contents/MacOS");
 		err = tmp_app_dir->make_dir_recursive(tmp_app_path_name + "/Contents/MacOS");
+		if (err != OK) {
+			add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Counld not created directory `%s`."), tmp_app_path_name + "/Contents/MacOS"));
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.cpp:822]:
```suggestion
			add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Could not create directory \"%s\"."), tmp_app_path_name + "/Contents/MacOS"));
```
Same below.

File: platform/osx/export/export_plugin.cpp [hunk 17]
```diff
@@ -955,16 +988,22 @@ Error EditorExportPlatformOSX::export_project(const Ref<EditorExportPreset> &p_p
...
 				err = tmp_app_dir->make_dir_recursive(file.get_base_dir());
+				if (err != OK) {
+					add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Counld not created directory `%s`."), file.get_base_dir()));
+				}
 			}
 			if (err == OK) {
 				String lnk_data = String::utf8((const char *)data.ptr(), data.size());
 				err = tmp_app_dir->create_link(lnk_data, file);
+				if (err != OK) {
+					add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Counld not created symlink `%s` -> `%s`."), lnk_data, file));
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.cpp:1005]: Note also this one with symlink, same typos.

File: platform/osx/export/export_plugin.cpp [hunk 18]
```diff
@@ -1049,6 +1091,7 @@ Error EditorExportPlatformOSX::export_project(const Ref<EditorExportPreset> &p_p
 						FileAccess::set_unix_permissions(file, 0755);
 					}
 				} else {
+					add_message(EXPORT_MESSAGE_ERROR, TTR("Export"), vformat(TTR("Counld not open `%s`."), file));
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.cpp:1094]: Typo.

File: platform/osx/export/export_plugin.cpp [hunk 19]
```diff
@@ -1061,7 +1104,7 @@ Error EditorExportPlatformOSX::export_project(const Ref<EditorExportPreset> &p_p
 	unzClose(src_pkg_zip);
 
 	if (!found_binary) {
-		ERR_PRINT(vformat("Requested template binary '%s' not found. It might be missing from your template archive.", binary_to_use));
+		add_message(EXPORT_MESSAGE_ERROR, TTR("Code Signing"), vformat(TTR("Requested template binary '%s' not found. It might be missing from your template archive."), binary_to_use));
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.cpp:1107]: Isn't that more of an "Export" error?

File: platform/windows/export/export_plugin.cpp [hunk 20]
```diff
@@ -433,15 +454,17 @@ bool EditorExportPlatformWindows::can_export(const Ref<EditorExportPreset> &p_pr
 	return valid;
 }
 
-Error EditorExportPlatformWindows::fixup_embedded_pck(const String &p_path, int64_t p_embedded_start, int64_t p_embedded_size) const {
+Error EditorExportPlatformWindows::fixup_embedded_pck(const String &p_path, int64_t p_embedded_start, int64_t p_embedded_size) {
 	// Patch the header of the "pck" section in the PE file so that it corresponds to the embedded data
 
 	if (p_embedded_size + p_embedded_start >= 0x100000000) { // Check for total executable size
-		ERR_FAIL_V_MSG(ERR_INVALID_DATA, "Windows executables cannot be >= 4 GiB.");
+		add_message(EXPORT_MESSAGE_ERROR, TTR("PCK Embeding"), TTR("Windows executables cannot be >= 4 GiB."));
```
Comment (akien-mga) [inline platform/windows/export/export_plugin.cpp:461]:
```suggestion
		add_message(EXPORT_MESSAGE_ERROR, TTR("PCK Embedding"), TTR("Windows executables cannot be >= 4 GiB."));
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
