### PR TITLE
Fix PanoramaSky artifacts on Android/GLES2

### LINKED ISSUE #43667: Artifacts on Android GLES2 with PanoramaSky
**Godot version:**
3.2.3

**OS/device including version:**
Android, Pixel 2, GLES2

**Issue description:**
On Editor:
image

On Android:
screen

Artifacts on objects when WorldEnvironment has a PanoramaSky. If WorldEnvironment is set to color only, this does not happen. There is a ticket related to this (https://github.com/godotengine/godot/issues/33633) which says it is fixed by enabling High Precision Float in GLES2 for Android, however it does not seem to fix it. This issues is not present on Desktop or iOS (or any other platform I am aware of)

**Steps to reproduce:**
1) Create scene and add a sphere and camera
2) Add SpatialMaterial to sphere
3) Add WorldEnvironment to scene and add Environment
4) Select Background->Mode = Sky
5) Add new ProceduralSky or add a PanoramaSky
6) Run project on Android device

**Minimal reproduction project:**
[Repro Project (Includes .apk)](https://github.com/godotengine/godot/files/5563905/GodotBug.zip)
[Repro Project (No .apk)](https://github.com/godotengine/godot/files/5563976/GodotBug-NoAPK.zip)

### PR DESCRIPTION
**Pull request by ForestKatsch**
The root cause of the issue is that OpenGL ES 2 does not support the `textureCubeLod` function.
There are (optional) extensions to support this, but they don't appear to be exposed with the ES2 renderer (even though the hardware needed to support LOD features are certainly available.)
The existing shim in `drivers/gles2/shaders/cubemap_filter.glsl` just creates a macro:

```
#define textureCubeLod(img, coord, lod) textureCube(img, coord)
```

But the third parameter of `textureCube` is actually a mip bias, not an absolute mip level.
(And it doesn't seem to work regardless.)
In this specific case, the `cubemap_filter` should only sample from the first level of the "source" panorama cubemap.
In lieu of a method to force a lod level of zero, I've chosen to comment out the switchover from a 2D equirectangular panorama to the cubemap version of the same image, therefore always sampling roughness values from the 2D equirectangular panorama.
This may cause additional artifacts or issues across the seam, but at least it prevents the glaringly obvious black areas.

---

This same issue (no fragment texture LOD support) has rather large repercussions elsewhere too; it means materials with larger cubemap density (i.e. planar or distant objects) will be far rougher than expected.
Since GLES 3 appears to properly support fragment `texture*Lod` functions, switching to the GLES 3 backend would solve this problem.

---

Root cause discovered with help from @KaadmY.

<I>Bugsquad edit</i>: Fix #43667

### CODE REVIEW

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 1]
```diff
@@ -1280,7 +1280,7 @@ void RasterizerStorageGLES2::sky_set_texture(RID p_sky, RID p_panorama, int p_ra
 
 			glActiveTexture(GL_TEXTURE0);
 			glBindTexture(GL_TEXTURE_CUBE_MAP, sky->radiance);
-			shaders.cubemap_filter.set_conditional(CubemapFilterShaderGLES2::USE_SOURCE_PANORAMA, false);
+			//shaders.cubemap_filter.set_conditional(CubemapFilterShaderGLES2::USE_SOURCE_PANORAMA, false);
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_storage_gles2.cpp:1283]: This will cause issues on hardware that is strictly compliant with OpenGL spec. By commenting out this conditional, the shader will expect to be given a ``sampler2D`` panorama texture. But you are still binding a cubemap to texture slot 0. I'm surprised this worked on your sample hardware at all.

File: drivers/gles2/shaders/cubemap_filter.glsl [hunk 2]
```diff
@@ -40,8 +40,8 @@ void main() {
 #endif
 
 #if !defined(GL_EXT_shader_texture_lod) && !defined(GL_ARB_shader_texture_lod)
-#define texture2DLod(img, coord, lod) texture2D(img, coord, lod)
-#define textureCubeLod(img, coord, lod) textureCube(img, coord, lod)
+#define texture2DLod(img, coord, lod) texture2D(img, coord)
+#define textureCubeLod(img, coord, lod) textureCube(img, coord)
```
Comment (clayjohn) [inline drivers/gles2/shaders/cubemap_filter.glsl:44]: Im surprised that this makes a difference as any call to texture2DLod or textureCubeLod has 0.0 as the lod offset.

**Review by clayjohn — COMMENTED** [review]
Thanks for making a pull request! This certainly is a troubling bug. 

As you'll see my comments, I'm a little skeptical that these are the proper fixes. I will take a closer look tonight and try running this on an android device. In the meantime, do you mind uploading an image of a radiance cubemap generated from this PR. you can capture it in RenderDoc and save to a png fairly easily.

File: drivers/gles2/shaders/cubemap_filter.glsl (hunk 2 above)
Comment (ForestKatsch) [reply drivers/gles2/shaders/cubemap_filter.glsl:44]: It doesn't make a difference in this case (even setting it to a large negative number didn't change anything, but if I understand it correctly, it should force sampling from mip 0.)

In this specific shader, we always want to sample from mip 0, as the other mips of the cubemap source texture aren't set (and are just black.)

File: drivers/gles2/rasterizer_storage_gles2.cpp (hunk 1 above)
Comment (ForestKatsch) [reply drivers/gles2/rasterizer_storage_gles2.cpp:1283]: Oh oops, looks like I shouldn't create PRs when tired. Working on a fix...

**Comment by ForestKatsch** [comment]
A better fix would be to check for the existence of the `GL_ARB_shader_texture_lod` or `GL_EXT_shader_texture_lod` extensions, and only enable `USE_SOURCE_PANORAMA` (i.e. read from the cubemap instead of the source equirectangular map) only if `textureCubeLod` is available. I'm not sure how Godot handles OpenGL extension detection though, and I'd like to reuse that existing code if possible. Any pointers are welcome!

**Comment by clayjohn** [comment]
@ForestKatsch GLSL extension checking is handled within each shader with preprocessor directives as below:

https://github.com/godotengine/godot/blob/68013d23932688e57b489600f4517dd280edc464/drivers/gles2/shaders/cubemap_filter.glsl#L30-L45

**Comment by ForestKatsch** [comment]
This is definitely not a long-term proper fix. Without support for fragment shader texture LOD sampling, I don't know if there *can be* a proper fix for this bug. But an incorrect result is arguably an improvement over the black artifacts.

I don't have a native Android device, only an Oculus Quest 2. I'll look into getting RenderDoc captures.

> GLSL extension checking is handled within each shader with preprocessor directives

Without checking for the extension on the C++ side, I don't think there's a clean workaround for devices that don't support the `textureCubeLod` function, because the C++ side would need to know to not set `USE_SOURCE_PANORAMA` and the source cubemap texture.

**Comment by clayjohn** [comment]
@ForestKatsch Well, we can just do a different codepath for all android devices. While it won't be as smooth, we could just force android devices to read from the source panorama. You would do so by putting an ``#ifdef GLES_OVER_GL`` check around the ``if (lod == 1)`` block

**Comment by akien-mga** [comment]
> @ForestKatsch Well, we can just do a different codepath for all android devices. While it won't be as smooth, we could just force android devices to read from the source panorama. You would do so by putting an `#ifdef GLES_OVER_GL` check around the `if (lod == 1)` block

Note that this would apply to iOS too (and WebGL I think).

**Comment by ForestKatsch** [comment]
I don't know all of the tradeoffs between sampling from the source equirectangular panorama (with `USE_SOURCE_PANORAMA` set) and from the transformed cubemap. If they're functionally identical, I don't think there would be an issue with always sampling from the source equirectangular panorama on all platforms.

**Comment by ForestKatsch** [comment]
Here is a comparison between the two methods on a desktop with the GLES2 backend:

```
#if 1
      glActiveTexture(GL_TEXTURE0);
      glBindTexture(GL_TEXTURE_CUBE_MAP, sky->radiance);
      shaders.cubemap_filter.set_conditional(CubemapFilterShaderGLES2::USE_SOURCE_PANORAMA, false);
#endif
```

Sampling from panorama for level 0 and cubemap for all other levels (`#if 1`, existing behavior)

Sampling from panorama (`#if 0`, new behavior)

**Comment by clayjohn** [comment]
@ForestKatsch The difference is quality. A huge difference in quality when using high frequency environment maps. Try the same comparison with the environment map from https://github.com/godotengine/godot/issues/33616. 

Although, thinking about it, GLES2 may not use an HDR panorama, so the impact may not be so severe. Please test with the environment map from https://github.com/godotengine/godot/issues/33616 and if it looks fine in both cases I am happy to remove the hack altogether.

**Comment by ForestKatsch** [comment]
> Try the same comparison with the environment map from #33616.

> Although, thinking about it, GLES2 may not use an HDR panorama, so the impact may not be so severe.

I think you're correct:

```
```

> **Edit:**_ to be clear, in your above example, you tested once with `#if 1` and once with `if 0` right?

**Comment by clayjohn** [comment]
Well that settles it. Looks like our little hack isn't needed in GLES2. 

I'll test tonight when I get home from work before approving. 

In the meantime, you can remove the ``#if 0`` block. We prefer to remove all dead code and just use the git history to keep things for posterity.

**Comment by ForestKatsch** [comment]
It's worth noting that this exact problem (no texture LOD support in GLES2) **will** cause issues elsewhere; notably, the wrong roughness will be used on planar or distant metallic surfaces (which should normally have a uniform roughness). This is visually very apparent.

As this issue probably isn't easily solved (given the strict GLES2/GLES3 separation), isn't immediately apparent as a visual defect, and with Godot moving to Vulkan in the future, I don't plan on opening an issue for that. But it is a problem on any device that doesn't support texture LOD extensions.

File: drivers/gles2/rasterizer_storage_gles2.cpp [hunk 3]
```diff
@@ -1278,9 +1278,8 @@ void RasterizerStorageGLES2::sky_set_texture(RID p_sky, RID p_panorama, int p_ra
 		if (lod == 1) {
 			//bind panorama for smaller lods
 
-			glActiveTexture(GL_TEXTURE0);
-			glBindTexture(GL_TEXTURE_CUBE_MAP, sky->radiance);
-			shaders.cubemap_filter.set_conditional(CubemapFilterShaderGLES2::USE_SOURCE_PANORAMA, false);
+			// USE_DIRECT_WRITE should be false as we want to properly filter roughness at all LODs other than 0,
+			// even if we're sampling from the panorama instead of the cubemap.
```
Comment (clayjohn) [inline drivers/gles2/rasterizer_storage_gles2.cpp:1282]: I would remove all 3 lines of comments and replace with a more descriptive comment about the new process

e.g. "Turn off direct write after first LOD is copied over"

**Comment by clayjohn** [comment]
> It's worth noting that this exact problem (no texture LOD support in GLES2) will cause issues elsewhere; notably, the wrong roughness will be used on planar or distant metallic surfaces (which should normally have a uniform roughness). This is visually very apparent.

Yep. Could be useful to document in https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html which is becoming a catch all for GLES2 specific limitations.

File: drivers/gles2/rasterizer_storage_gles2.cpp (hunk 3 above)
Comment (ForestKatsch) [reply drivers/gles2/rasterizer_storage_gles2.cpp]: Resolved in 763fe84.

File: drivers/gles2/shaders/cubemap_filter.glsl (hunk 2 above)
Comment (clayjohn) [inline drivers/gles2/shaders/cubemap_filter.glsl:44]: These changes are unnecessary, so it is best not to make them.

**Review by clayjohn — CHANGES_REQUESTED** [review]
Tested out on my hardware and removing the cubemap hack works great. Since GLES2 always uses LDR, we don't need the extra smoothness that comes from resampling from lower radiance levels. 

I also tested out without your changes to the texture2DLod, and I was correct before that those changes are unnecessary. So just remove those changes and this PR will be good to go!

Thanks for your hard work and your great sleuthing. It will be really nice to have this fixed.

File: drivers/gles2/shaders/cubemap_filter.glsl (hunk 2 above)
Comment (ForestKatsch) [reply drivers/gles2/shaders/cubemap_filter.glsl]: Reverted in 4b95b18.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Could you squash the commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by ForestKatsch** [comment]
> Could you squash the commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

Done!

**Comment by akien-mga** [comment]
Thanks!
