### PR TITLE
Remove use of `std::string` in test

### LINKED ISSUE #80421: Incomplete type error when compiling unit tests
### Godot version

master [f7bc653cbe81018fe362472a0143b7153a52f929]

### System information

Arch Linux (GCC 13.2.1)

### Issue description

Output:

```
In file included from tests/test_main.cpp:118:
./tests/servers/rendering/test_shader_preprocessor.h: In function 'bool TestShaderPreprocessor::is_operator_char(unsigned char)':
./tests/servers/rendering/test_shader_preprocessor.h:55:34: error: variable 'const std::string operators' has initializer but incomplete type
   55 |         static const std::string operators = "<>=+-*/";
      |                                  ^~~~~~~~~
./tests/servers/rendering/test_shader_preprocessor.h:56:50: error: incomplete type 'std::string' {aka 'std::__cxx11::basic_string<char>'} used in nested name specifier
   56 |         return operators.find(c) != std::string::npos;
      |                                                  ^~~~
scons: *** [tests/test_main.linuxbsd.editor.dev.x86_64.san.o] Error 1
scons: building terminated because of errors.
```

### Steps to reproduce

Compile the project. Probably needs GCC 13.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Can alternatively include `<string>` but since this would be the only place in the source using `std::string` save for the glsl module and the windows platform I'll lean to this

The only other places `std::string` is used are (excluding `thirdparty/`):
* `modules/glslang/register_types.cpp`
* `platform/windows/crash_handler_windows.cpp`

Fixes: #80421

### CODE REVIEW

File: tests/servers/rendering/test_shader_preprocessor.h [hunk 1]
```diff
@@ -52,8 +52,8 @@ bool is_variable_char(unsigned char c) {
 }
 
 bool is_operator_char(unsigned char c) {
-	static const std::string operators = "<>=+-*/";
-	return operators.find(c) != std::string::npos;
+	static const String operators = "<>=+-*/";
+	return operators.find_char(c) != -1;
```
Comment (AThousandShips) [inline tests/servers/rendering/test_shader_preprocessor.h:56]: Optionally:
```suggestion
	static const Vector<unsigned char> operators = {'<', '>', '=', '+', '-', '*', '/' };
	return operators.find(c) != -1;
```

File: tests/servers/rendering/test_shader_preprocessor.h [hunk 2]
```diff
@@ -52,8 +52,8 @@ bool is_variable_char(unsigned char c) {
 }
 
 bool is_operator_char(unsigned char c) {
-	static const std::string operators = "<>=+-*/";
-	return operators.find(c) != std::string::npos;
+	static const Vector<unsigned char> operators({ '<', '>', '=', '+', '-', '*', '/' });
+	return operators.find(c) != -1;
```
Comment (bruvzg) [inline tests/servers/rendering/test_shader_preprocessor.h:56]: It's only a few options, so does not need a vector of function calls at all, probably should be implemented similarly to the methods in the https://github.com/godotengine/godot/blob/master/core/string/char_utils.h.

**Comment by akien-mga** [comment]
> Fixes:
>
> - https://github.com/godotengine/godot/issues/80421

FYI, "Fixes" should come directly before the issue number to work as a closing keyword (edited the OP).

File: tests/servers/rendering/test_shader_preprocessor.h (hunk 2 above)
Comment (AThousandShips) [reply tests/servers/rendering/test_shader_preprocessor.h:56]: Very true will change soon, thank you!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
