### PR TITLE
Draw materials in tile atlas view

### LINKED ISSUE #77672: Tiles in the tile picker aren't rendered with their material
### Godot version

4.1.dev

### System information

Linux Vulkan mobile renderer

### Issue description

In my game I'm using alternatives to create variations of tiles. Because these can't be achieved by changing built-in properties, I'm doing this by attaching a shader with different parameters that will change something in the tile's rendering. However, these differences don't show up in the selection pane at the bottom. Neither in the TileMap editor nor the TileSet editor. This makes it difficult to pick the right one :smile: 

image

They do show up in the TileMap editor in the scene view itself, as well as in the game, just not in this preview pane.

### Steps to reproduce

- Create a 2D scene with a TileMap
- Create a TileSet resource and add it
- Add a texture, define a tile
- Create alternatives of this tile, have them use a material with different shaders, or the same shader with different parameters

"Tiles" picker will show them all the same.

### Minimal reproduction project

I am not sure this is necessary as this issue is not specific to any project. If it's desirable I'm happy to create one, though.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #77672

https://github.com/godotengine/godot/assets/2223172/a480886c-9860-4551-a5c4-9c168c9b5477

Test TileSet:
[Shaderset.tres.txt](https://github.com/godotengine/godot/files/11664753/Shaderset.tres.txt)
(requires icon.png)

There is also a separate (and unreported?) issue where the "ghost" tiles (i.e. when drawing on TileMap) are not using their material.

### CODE REVIEW

File: editor/plugins/tiles/tile_atlas_view.cpp [hunk 1]
```diff
@@ -405,6 +417,16 @@ void TileAtlasView::set_atlas_source(TileSet *p_tile_set, TileSetAtlasSource *p_
 	tile_set = p_tile_set;
 	tile_set_atlas_source = p_tile_set_atlas_source;
 
+	// Clear material canvas items.
```
[the remark this answers is not in the document]
Comment (KoBeWi) [reply editor/plugins/tiles/tile_atlas_view.cpp:420]: Ah, right...

File: editor/plugins/tiles/tile_atlas_view.cpp [hunk 2]
```diff
@@ -286,6 +298,16 @@ void TileAtlasView::_draw_base_tiles() {
 	}
 }
 
+void TileAtlasView::_clear_material_canvas_items() {
+	for (KeyValue<Ref<Material>, RID> kv : material_tiles_draw) {
+		if (kv.value == base_tiles_draw->get_canvas_item()) {
```
Comment (groud) [inline editor/plugins/tiles/tile_atlas_view.cpp:303]: I guess this cannot happen, I don't think you add `base_tiles_draw->get_canvas_item()` to the list

**Review by groud — CHANGES_REQUESTED** [review]
Soooo. I've been thinking about it a bit and I am a bit worried this cached materials pool could become big as it is only cleaned when changing sources. While most of the edits only trigger queue_redraw.

I would be more confident if the cache was cleaned dynamically in the drawing functions. The idea would be, when drawing, to keep track of the materials in the cache that were not used by any tile, then free the corresponding CanvasItems at the end of the drawing function.

Also, this needs to be implemented for `_draw_alternatives`, which means you probably need two HashMaps to store the CanvasItems.

File: editor/plugins/tiles/tile_atlas_view.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/plugins/tiles/tile_atlas_view.cpp:303]: I do, for the empty material.

**Comment by KoBeWi** [comment]
> Soooo. I've been thinking about it a bit and I am a bit worried this cached materials pool could become big as it is only cleaned when changing sources. While most of the edits only trigger queue_redraw.

I implemented what you said and then discovered that material change *always* results in `set_atlas_source()`, so it's useless 🙄

**Comment by KoBeWi** [comment]
Ok pushed fix for alternate tiles. I did not add removing unused materials for the reason described above.

**Comment by groud** [comment]
> I implemented what you said and then discovered that material change always results in set_atlas_source(), so removing unused materials is useless roll_eyes

hmm, that sounds like a bug though. I don't really understand why that would be triggered.
I guess it can be merged as is anyway, it's not a big deal.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by vmedea** [comment]
Can confirm this solves #77672. This is so much better thank u!!!

image

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.
