### PR TITLE
[Windows] Offload `RenderingDevice` creation test to subprocess.

### LINKED ISSUE #101659: Compatibility renderer crash with Nvidia GPU and 566.36 drivers on Windows
### Tested versions

Reproducible in every version of 4.4 including Dev 1

### System information

Windows 11 - Godot 4.4 (any version) - OpenGL API - Nvidia 3070 or 970(happens with both)  - AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz - 

### Issue description

Image
everytime I try to open Godot, it just closes before it even finished opening
this happens with both my 3070 and 970 gpus

### Steps to reproduce

all I do is open the application

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Might fix https://github.com/godotengine/godot/issues/101659

### CODE REVIEW

File: servers/display_server.cpp [hunk 1]
```diff
@@ -1334,6 +1334,24 @@ bool DisplayServer::can_create_rendering_device() {
...
+	int exitcode = 0;
+	err = OS::get_singleton()->execute(OS::get_singleton()->get_executable_path(), arguments, &pipe, &exitcode);
+	if (err == OK && exitcode == 0) {
+		created_rendering_device = RenderingDeviceCreationStatus::SUCCESS;
+		return true;
+	} else {
+		created_rendering_device = RenderingDeviceCreationStatus::FAILURE;
+		return false;
+	}
+#endif
```
Comment (akien-mga) [inline servers/display_server.cpp:1353]: I'd suggest making it a static bool so we only test this once per session, to avoid redoing such test all the time.

Actually, the whole function should likely be called only once and saved in a static bool. It's called in `LightmapGI::get_configuration_warnings` so any time a scene with a LightmapGI is refreshed, it would call this.

Comment (bruvzg) [reply servers/display_server.cpp:1353]: `created_rendering_device` is static variable (3 state), it's already checking it once.

File: servers/display_server.cpp [hunk 2]
```diff
@@ -1317,7 +1317,7 @@ void DisplayServer::_input_set_custom_mouse_cursor_func(const Ref<Resource> &p_i
 }
 
 bool DisplayServer::can_create_rendering_device() {
-	if (get_singleton()->get_name() == "headless") {
+	if (get_singleton() && get_singleton()->get_name() == "headless") {
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply servers/display_server.cpp:1320]: This is already saving the results in `created_rendering_device`, so nevermind.

**Comment by akien-mga** [comment]
I get this build error with mingw-gcc from Fedora 41:
```
platform/windows/crash_handler_windows_signal.cpp: In function 'void CrashHandlerException(int)':
platform/windows/crash_handler_windows_signal.cpp:137:17: error: 'quick_exit' was not declared in this scope; did you mean '_c_exit'?
  137 |                 quick_exit(1);
      |                 ^~~~~~~~~~
      |                 _c_exit
```

**Comment by bruvzg** [comment]
> I get this build error with mingw-gcc from Fedora 41

Replaced it with `std::_Exit`, we do not care about `at_quick_exit`, just need a "normal" termination to avoid any system error popups.

**Comment by akien-mga** [comment]
I'm now getting this linking error:
```
/usr/lib/gcc/x86_64-w64-mingw32/14.2.1/../../../../x86_64-w64-mingw32/bin/ld: main/main.windows.editor.x86_64.o:main.cpp:(.text+0x17e37): undefined reference to `test_create_rendering_device_and_gl()'
```

**Comment by bruvzg** [comment]
> I'm now getting this linking error

I can reproduce it on Fedora 41, but not macOS or Windows, probably LTO / GCC linking order related. Added `__attribute__((used))` to prevent function removal. Moving the file to the `main`, to be in the same library should also fix it, but it Windows specific, so not sure what's better.

**Comment by akien-mga** [comment]
I made a test build with the official buildsystem for Windows x86_64 and x86_32, both standard and mono:

https://editor.godotengine.org/testing/4.4-rc1-pr103245/

I'll ask in the issue for testers.

**Comment by clayjohn** [comment]
This will block users from creating new projects using the Forward+ and Mobile renderers on the affected drivers. 

We will need to use a different check for project creation because there we only care if RD is supported, we don't care if RD can run at the same time as OpenGL

**Comment by bruvzg** [comment]
> This will block users from creating new projects using the Forward+ and Mobile renderers on the affected drivers.

Added second RD only check version.

File: platform/windows/os_windows.cpp [hunk 3]
```diff
@@ -2346,6 +2364,126 @@ void OS_Windows::add_frame_delay(bool p_can_draw) {
...
+				rd = nullptr;
+				if (err == OK) {
+					ok = true;
+				}
+			}
+			memdelete(rcd);
+			rcd = nullptr;
+		}
+#endif
+	}
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp:2474]: I guess you could leverage the new `_test_create_rendering_device` here to reduce code duplication?
```suggestion
	if (ok) {
		ok = _test_create_rendering_device();
	}
```

Comment (bruvzg) [reply platform/windows/os_windows.cpp]: Done.

**Review by akien-mga — APPROVED** [review]
We have two confirmations that it fixes the crash for affected users on Windows, so let's go!

Some more testing will be needed to validate whether VRAM compression and lightmap baking works, but this will be easier to do once this is included in 4.4.rc2 (and worst case, this can be fixed after the 4.4 release if it doesn't work, as long as it's not crashing).
