### PR TITLE
[3.x] Core: Add recursion level check for `Array` and `Dictionary` hashing

### LINKED ISSUE #44195: [3.x] Using `Dictionary` as own key crashes Godot
**Godot version:**
3.2.3

**OS/device including version:**
MacOS Catalina 10.15.5

**Issue description:**
Write this code:

```
func _ready():
  var test = {}
  test[test] = test
```

The game crashes immediately when it hits this code.

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #44195.
* Copies the minimum part of #35816 needed to fix the bug (with minor style changes). The `recursive_equal()` and other things are not copied as it would break compatibility.

It also prevents crashes in cases like:

```gdscript
var a = []
a.append(a)
print(a.hash())
```

### CODE REVIEW

File: core/array.cpp [hunk 1]
```diff
@@ -118,16 +118,25 @@ bool Array::operator==(const Array &p_array) const {
 }
 
 uint32_t Array::hash() const {
+	return recursive_hash(0);
+}
+
+uint32_t Array::recursive_hash(int p_recursion_count) const {
```
Comment (RandomShaper) [inline core/array.cpp:124]: Let me suggest declaring these as (private) `uint32_t T::_hash(int p_recursion_count = 0) const`.

**Review by RandomShaper — APPROVED** [review]

File: core/array.cpp (hunk 1 above)
Comment (dalexeev) [reply core/array.cpp:124]: Makes sense. I just copied it from 4.x though.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.
