### PR TITLE
Fix ScriptEditor inline colors float handling

### LINKED ISSUE #107725: Inline color picker doesn't work well with non-constant colors
### Tested versions

- Reproducible in v4.5.beta1.mono.official [46c495ca2]

### System information

Godot v4.5.beta1.mono - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 threads) - 15.95 GiB memory

### Issue description

I have constant colors `c1`, `c2` and a non-constant color `c3`:

Image

`c2` and `c3` are shown to have the same color, green. But `c3` is a non-constant color, it is not green. In this exact case the `c3`'s color would be yellow, but for example in the following code the actual color would change in every while loop.

```gdscript
var red := 0.0
while red < 1.0:
	var color = Color(red, 1, 0)
	red += 0.1
	...
```

If I click the `c3`'s color rectangle I can choose a new color. That will overwrite the variable `red` and replace it with a constant number:

Image

I would expect that non-constant colors would not display the color rectangle and they would not be editable at all with the inline color picker.

### Steps to reproduce

```gdscript
	var red = 1
	var c1 = Color(1, 1, 0)
	var c2 = Color(0, 1, 0)
	var c3 = Color(red, 1, 0)
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by kitbdev**
- Fixes https://github.com/godotengine/godot/issues/107725

Mostly whitespace changes since I tried to make the function easier to read.

`split_floats` just gives `0.0` when it encounters non-numbers, so I removed it and now check `is_valid_float` for each parameter, with a maximum of 4.
It must be a float literal, variables and expressions are not allowed here. It may be possible to use Expression to handle them, but it would still need to be readonly.

Also added checks when typing a string parameter to only show the color if it is valid and to prevent some invalid color errors (not all, see https://github.com/godotengine/godot/issues/89357).

This function will need to be moved to be language independent in the future, then it can be parsed better with GDScript.

### CODE REVIEW

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -411,76 +411,91 @@ Array ScriptTextEditor::_inline_object_parse(const String &p_text, int p_line) {
...
+		const String fn_name = p_text.substr(i_start + 5, i_par_start - i_start - 5);
+		const String s_params = p_text.substr(i_par_start + 1, i_par_end - i_par_start - 1);
+		bool has_added_color = false;
+
+		if (fn_name.is_empty()) {
+			String stripped = s_params.strip_edges(true, true);
+			if (stripped.length() > 0 && (stripped[0] == '\"')) {
+				// String constructor.
+				const String color_string = stripped.substr(1, stripped.length() - 2);
+				if (Color::html_is_valid(color_string) || Color::find_named_color(color_string) != -1) {
```
Comment (KoBeWi) [inline editor/plugins/script_text_editor.cpp]: Checking for valid color causes the marker to get toggled repeatedly while writing.

https://github.com/user-attachments/assets/e0818780-5f0b-482a-8fda-a5e66d879140

I think if it's inside string, it doesn't matter if the color code is valid, because it can't mean anything else, right? 🤔 (as opposed to the original issue, where a variable is treated as a number)

**Comment by kitbdev** [comment]
Updated to show default color if the string isn't valid so it doesn't keep dissapearing and reappearing while typing.
Also now works with single quote strings. Though it will be changed to double quote when changing color.
Added more checks to prevent these cases being considered valid:
```gdscript
Color(")
Color("aaa)
Color(0xawaaaaaa)
Color(0x0 + aaaa)
Color("ff"+red)
```

There are still some colors that should be considered valid (like hex without alpha and more static methods) but those can be done later.

**Review by KoBeWi — APPROVED** [review]
Works fine now.
Needs rebase.

File: editor/script/script_text_editor.cpp [hunk 2]
```diff
@@ -411,76 +411,97 @@ Array ScriptTextEditor::_inline_object_parse(const String &p_text, int p_line) {
...
+				const char32_t string_delimiter = stripped[0];
+				if (stripped[stripped.length() - 1] == string_delimiter) {
+					const String color_string = stripped.substr(1, stripped.length() - 2);
+					if (!color_string.contains_char(string_delimiter)) {
+						color_info["color"] = Color::from_string(color_string, Color());
+						color_info["color_mode"] = MODE_STRING;
+						has_added_color = true;
 					}
 				}
+			} else if (stripped.length() == 10 && stripped.substr(0, 2) == "0x") {
```
Comment (AThousandShips) [inline editor/script/script_text_editor.cpp]:
```suggestion
			} else if (stripped.length() == 10 && stripped.begins_with("0x")) {
```
Avoids creating a temporary string copy

File: editor/script/script_text_editor.cpp [hunk 3]
```diff
@@ -411,76 +411,97 @@ Array ScriptTextEditor::_inline_object_parse(const String &p_text, int p_line) {
...
+				// Hex constructor.
+				const String color_string = stripped.substr(2, stripped.length() - 2);
```
Comment (AThousandShips) [inline editor/script/script_text_editor.cpp]:
```suggestion
				const String color_string = stripped.substr(2);
```

File: editor/script/script_text_editor.cpp [hunk 4]
```diff
@@ -411,76 +411,97 @@ Array ScriptTextEditor::_inline_object_parse(const String &p_text, int p_line) {
...
-								color_info["color_mode"] = MODE_RGB8;
-							} else if (fn_name.is_empty()) {
-								color_info["color"] = Color(params[0], params[1], params[2], params[3]);
-								color_info["color_mode"] = MODE_RGB;
-							} else {
-								has_added_color = false;
-							}
-						}
-					}
+		if (i_start != 0 && ("_" + p_text.substr(i_start - 1, 1)).is_valid_ascii_identifier()) {
```
Comment (AThousandShips) [inline editor/script/script_text_editor.cpp]:
```suggestion
		if (i_start != 0 && ('_' + p_text.substr(i_start - 1, 1)).is_valid_ascii_identifier()) {
```

File: editor/script/script_text_editor.cpp [hunk 5]
```diff
@@ -411,76 +411,97 @@ Array ScriptTextEditor::_inline_object_parse(const String &p_text, int p_line) {
...
+		color_info["width_ratio"] = 1.0;
+		color_info["color_end"] = i_par_end;
+
+		const String fn_name = p_text.substr(i_start + 5, i_par_start - i_start - 5);
+		const String s_params = p_text.substr(i_par_start + 1, i_par_end - i_par_start - 1);
+		bool has_added_color = false;
+
+		if (fn_name.is_empty()) {
+			String stripped = s_params.strip_edges(true, true);
+			if (stripped.length() > 1 && (stripped[0] == '\"' || stripped[0] == '\'')) {
```
Comment (AThousandShips) [inline editor/script/script_text_editor.cpp]:
```suggestion
			if (stripped.length() > 1 && (stripped[0] == '"' || stripped[0] == '\'')) {
```

**Comment by Repiteo** [comment]
Thanks!
