### PR TITLE
Editor: Fix display of objects in the Remote Inspector

### LINKED ISSUE #116820: Remote inspector view does not show node values
### Tested versions

reproducible on v4.7.dev.custom_build [ebc126193]
not reproducible in v4.6.1.stable.arch_linux [14d19694e]

### System information

Godot v4.7.dev (ebc126193) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 09 Feb 2026 17:16:33 +0000 on Wayland - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon 780M Graphics (radeonsi, phoenix, LLVM 21.1.6, DRM 3.64, 6.18.9-arch1-2) - AMD Ryzen 7 8745HS w/ Radeon 780M Graphics (16 threads) - 28.18 GiB memory

### Issue description

Image

The variable `node reference` is not null, but doesn't show in the inspector when viewing the remote tree. The `@exported` variable shows fine though

### Steps to reproduce

Set a variable value with `get_child` during runtime, and try to view it in the remote inspector. The variable value doesn't show, even if it can be printed just fine.

```swift
var node_reference
func _ready():
    node_reference = get_child(0)
    print(node_reference)
```

### Minimal reproduction project (MRP)

(project started from a project linked in this similar issue https://github.com/godotengine/godot/issues/77580)

[treeexpander_2026-02-26_13-50-06.zip](https://github.com/user-attachments/files/25585158/treeexpander_2026-02-26_13-50-06.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #116820.

Test script:

```gdscript
extends Node2D

@export var node_manual_set: Node
@export var res_manual_set: Resource

var node_reference
var res_reference

var node_reference_typed: Node
var res_reference_typed: Resource

var arr: Array
var arr_untyped

func _ready():
    node_reference = get_child(0)
    node_reference_typed = node_reference

    res_reference = res_manual_set
    res_reference_typed = res_reference

    arr = [node_reference, res_reference]
    arr_untyped = arr
```

### CODE REVIEW

File: editor/inspector/editor_properties.cpp [hunk 1]
```diff
@@ -97,6 +98,10 @@ void EditorPropertyVariant::_popup_edit_menu() {
 	change_type->popup();
 }
 
+void EditorPropertyVariant::_object_id_selected(const StringName &p_property, ObjectID p_id) {
+	emit_signal(SNAME("object_id_selected"), p_property, p_id);
+}
+
```
Comment (YeldhamDev) [inline editor/inspector/editor_properties.cpp:104]: I wonder if there's a way to connect to `emit_signal` directly, without the need to create a function just for it. Oh well...

File: editor/inspector/editor_properties.cpp [hunk 2]
```diff
@@ -125,7 +130,14 @@ void EditorPropertyVariant::update_property() {
...
 		if (current_type == Variant::OBJECT) {
-			sub_property = EditorInspector::instantiate_property_editor(nullptr, current_type, "", PROPERTY_HINT_RESOURCE_TYPE, Resource::get_class_static(), PROPERTY_USAGE_NONE);
+			Object *obj = value.get_validated_object();
+			if (Object::cast_to<EncodedObjectAsID>(obj)) {
+				EditorPropertyObjectID *editor = memnew(EditorPropertyObjectID);
+				editor->setup("Object");
+				sub_property = editor;
+			} else {
+				sub_property = EditorInspector::instantiate_property_editor(nullptr, current_type, "", PROPERTY_HINT_RESOURCE_TYPE, Resource::get_class_static(), PROPERTY_USAGE_NONE);
+			}
```
Comment (YeldhamDev) [inline editor/inspector/editor_properties.cpp:140]: What is the reason why `instantiate_property_editor()` can't handle this on its own?

Comment (dalexeev) [reply editor/inspector/editor_properties.cpp:140]: I did this in a similar way to `EditorPropertyArray` and `EditorPropertyDictionary`. `EditorPropertyVariant` is similar in that it's designed to edit values ​​of different types (but only a single instance, unlike elements in an array or keys/values ​​in a dictionary).

https://github.com/godotengine/godot/blob/54c6cfee0d4ae12d49fb79c18a37f1139dce09b2/editor/inspector/editor_properties_array_dict.cpp#L514-L520

https://github.com/godotengine/godot/blob/54c6cfee0d4ae12d49fb79c18a37f1139dce09b2/editor/inspector/editor_properties_array_dict.cpp#L1431-L1439

I looked at the implementation of `instantiate_property_editor()` and it didn't seem like a more appropriate place to make this change.

File: editor/inspector/editor_properties.cpp (hunk 1 above)
Comment (dalexeev) [reply editor/inspector/editor_properties.cpp:104]: This isn't the only instance. If you want to do anything about it, I think it's beyond the scope of this PR.

<details>
<summary>List</summary>

```c++
void EditorInspector::_object_id_selected(const String &p_path, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_id);
}

void EditorPropertyVariant::_object_id_selected(const StringName &p_property, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_property, p_id);
}

void EditorPropertyObjectID::_edit_pressed() {
    emit_signal(SNAME("object_id_selected"), get_edited_property(), _get_object_id());
}

void EditorPropertySignal::_edit_pressed() {
    Signal signal = get_edited_property_value();
    emit_signal(SNAME("object_id_selected"), get_edited_property(), signal.get_object_id());
}

void EditorPropertyResource::_sub_inspector_object_id_selected(int p_id) {
    emit_signal(SNAME("object_id_selected"), get_edited_property(), p_id);
}

void EditorPropertyArray::_object_id_selected(const StringName &p_property, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_property, p_id);
}

void EditorPropertyDictionary::_object_id_selected(const StringName &p_property, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_property, p_id);
}

void EditorPropertyLocalizableString::_object_id_selected(const StringName &p_property, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_property, p_id);
}

void EditorPropertyFontMetaOverride::_object_id_selected(const StringName &p_property, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_property, p_id);
}

void EditorPropertyOTVariation::_object_id_selected(const StringName &p_property, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_property, p_id);
}

void EditorPropertyOTFeatures::_object_id_selected(const StringName &p_property, ObjectID p_id) {
    emit_signal(SNAME("object_id_selected"), p_property, p_id);
}
```

</details>

Comment (YeldhamDev) [reply editor/inspector/editor_properties.cpp:104]: I'm aware. Just highlighting the issue, not asking you to be the one to fix it.

**Review by YeldhamDev — APPROVED** [review]
