### PR TITLE
Fix- using cut in first line of a script file does not remove the line

### LINKED ISSUE #34289: Using cut in first line of a script file does not remove the line
**Godot version:**
9abc0ad8a5cf400d848fd25a33bd562db08d1046

**Issue description:**
When using `Cut` in the first line of a script file (without any selection) the cut operation is executed, but an empty line remains.

**Steps to reproduce:**
1. Place cursor anywhere in the first line
2. Press `Ctrl + X` or use the context menu to execute `Cut`
3. See that the content of the line is cut, but the line still remains

### PR DESCRIPTION
**Pull request by mikkac**
Fix #34289 
**TextEdit::cut** needs to handle cuting first line of the file due to the fact that **TextEdit::backspace_at_cursor** does not perform it's functionality, when _cursor.line == 0_

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @timothyqiu @KoBeWi as this seems quite close to #34217 / #34212.

**Comment by timothyqiu** [comment]
* This creates two undo entries when cutting the first line
* Cutting on other lines moves the cursor one extra line below

**Comment by mikkac** [comment]
> * This creates two undo entries when cutting the first line
> * Cutting on other lines moves the cursor one extra line below

Good point! Thanks, I didn't notice that
I will also take a look at #34217 and will try to incorporate similar solution in _TextEdit::cut_ method.

**Comment by mikkac** [comment]
Ok, I managed to avoid issues mentioned by @timothyqiu. Please take look at this in free moment. Thanks!

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -5173,15 +5173,21 @@ void TextEdit::cut() {
 
 	if (!selection.active) {
 
+		auto initial_cursor_line = cursor.line;
```
Comment (Paulb23) [inline scene/gui/text_edit.cpp]: FYI `auto` is banned in Godot.

In any case it should be possible to use `cursor.line` in the below if.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
One note inline, otherwise looks okay to me.

File: scene/gui/text_edit.cpp (hunk 1 above)
Comment (mikkac) [reply scene/gui/text_edit.cpp]: ok, thanks! Where can I find more rules (like _forbidden auto_) related to Godot?

Comment (Paulb23) [reply scene/gui/text_edit.cpp]: Currently Godot is still C++03. But, for 4.0 the C++11 guidelines are still being written up. 

If you're keen though, there was an overview given at GodotCon Brussels 2019 that should be on YouTube.

**Review by Paulb23 — APPROVED** [review]
LGTM.

**Comment by akien-mga** [comment]
Thanks!
