### PR TITLE
[TextServer] Save advances rounding remainders to prevent rounding error accumulation.

### LINKED ISSUE #93199: Kerning Pairs (monospace image font) can affect the kerning of subsequent characters, off by one pixel
### Tested versions

- Reproducible in: Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5176) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5176) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When using kerning pairs, the space between two characters can be affected by the character that came before them. It appears there is some kind of rounding layout issue, not sure if this is a bug in kerning or in the rendering pipeline.

image

In the example, A and B have different kerning offsets when followed by p. The space between u and p then differs between them.

### Steps to reproduce

Open the project and the layout issue is visible in the main scene for preview and run.

Note that this affect can be achieved by changing things like character margins as well to generate inconsistent layouts.

### Minimal reproduction project (MRP)

[kerning_layout_issue.zip](https://github.com/user-attachments/files/15848756/kerning_layout_issue.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/93199

### CODE REVIEW

File: modules/text_server_adv/text_server_adv.cpp [hunk 1]
```diff
@@ -6097,21 +6098,33 @@ void TextServerAdvanced::_shape_run(ShapedTextDataAdvanced *p_sd, int64_t p_star
 			gl.index = glyph_info[i].codepoint;
 			if (gl.index != 0) {
 				_ensure_glyph(fd, fss, gl.index | mod);
+				if (subpos) {
+					gl.x_off = (double)glyph_pos[i].x_offset / (64.0 / scale);
+				} else {
+					if (p_sd->orientation == ORIENTATION_HORIZONTAL) {
```
Comment (AThousandShips) [inline modules/text_server_adv/text_server_adv.cpp:6104]: I'd merge this else block into an `if else` as it's just nested, it would be more readable

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
