### PR TITLE
Prevent double input events on gamepad when running through steam input

### LINKED ISSUE #75480: Controller events detected as InputEventKey when Steam is open (due to Steam Input event injection)
### Godot version

4.0, 4.0.1

### System information

Windows 10

### Issue description

If Steam is open on your computer, input from a controller can be incorrectly detected as an InputEventKey. Closing Steam corrects this error.

Controller inputs should never be detected as an InputEventKey: According to the current documentation an InputEventKey is [only for keyboard events.](https://docs.godotengine.org/en/4.0/classes/class_inputeventkey.html)

**Video demonstration:** https://youtu.be/9krmPx9vYoc
**Controller used:** Dualshock 4

### Steps to reproduce

1. Run minimal reproduction project (or a script with the following code):
```
func _input(event : InputEvent) -> void:
	if event is InputEventKey:
		print ("Keyboard Event Detected")
```
2. Test if "Keyboard Event Detected" prints on Controller input with Steam open vs. with Steam closed. 

### Minimal reproduction project

[InputEventKey Controller Test.zip](https://github.com/godotengine/godot/files/11106151/InputEventKey.Controller.Test.zip)

### PR DESCRIPTION
**Pull request by Eoin-ONeill-Yokai**
Fixes #75480 

# The Problem
During GDC2023 and when generally testing on Steam Deck units, we found that a single gamepad would often register inputs twice under certain circumstances. This was caused by SteamInput creating a new virtual device, which Godot registers as a second gamepad. This resulted in two gamepad devices reporting the same button presses, often leading to buggy input response on games with no multi-device logic or otherwise could cause Steam controller rebindings to not work as intended (for example, swapping `o` and `x` on a PlayStation pad if that feature isn't supported by the game.)

SDL2 gets around this by taking in a list of devices that are to be ignored via system environment. When valve sees a controller that wants to be routed through SteamInput, they push a new `VID/PID` entry onto the environment variable `SDL_GAMECONTROLLER_IGNORE_DEVICES` matching the source gamepad so that the SDL based games will only read inputs from the virtual device remappings.

## Proposed Solution
This PR fixes this issue by leveraging the same logic that SDL uses. As we are already using SDL gamepad related HID mappings, there shouldn't be much harm in leveraging another environment variable for usb device ignoring capabilities.

This feature is currently only being used on LinuxBSD platform, but can be applied to other platforms that need it due to the implementation in the Input class. 

## Considerations

- This environment variable parsing and `should_ignore_device` api could be moved to another class. For example, they could be stored in `JoypadLinux/JoypadOSX/JoypadXXX` if we determine that we only really need this functionality for a few select platforms.
- It's very likely that this logic will also be needed on OSX as SDL2 does so on that platform as well. I don't have a computer to test this so I left it unimplemented. In theory, JoypadOSX would also simply call `should_ignore_device` before registering controller connection to determine whether or not the device should be ignored.
- Windows *supposedly* **doesn't** need to take this into account, as Valve is doing their own thing on that platform with regards to virtual game inputs. Having said that, if it is determined that Windows does need this, it should also use a pretty similar solution to what's provided here.

## Testing Procedure

<details>
   <summary> Collapsed for ease-of-reading </summary>

### Reproduction, Verification

- Download the attached testing project
- Get vanilla Godot 4.0 template_debug export target
- Verify that only 1 `A Button` press occurs when running the testing project standalone (no steam)
- Export the testing project as a game via vanilla 4.0
- Load the game via Steam, make sure that Steam Input is enabled for your device (on Xbox/Nintendo controllers, this often needs to be done manually.)
- Observe when you press the A button (or X Button on PS layout, or the B Button on Nintendo controller layout) that there's two button presses registered on a single frame for the single gamepad.

### Testing

- Compile this branch, both editor and template_debug export target.
- Verify that only 1 button press occurs when running the testing project standalone (no steam)
- Load the testing project in the editor and export.
- Reload the game via Steam, making sure to use the same Steam Input settings as the reproduction.
- Observe when you press the A button (or X button PS layout, B button Nintendo layout) there's now only one button press registered for the single gamepad. 

- [x] Controller input should work when running Godot without steam input
- [x] Controller input should work when running Godot through steam input, with only one button press registered per button.
- [x] Controllers should be rebindable via SteamInput when the user wants to take advantage of system-level customization features (for example, swapping buttons or axis.) 
</details>

[bug75480.zip](https://github.com/godotengine/godot/files/11229184/bug75480.zip)

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -1505,6 +1510,29 @@ Input::Input() {
...
+			if (vid_pid.size() < 2) {
+				continue;
+			}
+
+			print_verbose(vformat("Device Ignored -- Vendor: %s Product: %s", vid_pid[0], vid_pid[1]));
+			const uint16_t vid_unswapped = vid_pid[0].hex_to_int();
+			const uint16_t pid_unswapped = vid_pid[1].hex_to_int();
+
+			const uint16_t vid = BSWAP16(vid_unswapped);
+			if (ignored_vid_pid_devices.has(vid)) {
```
Comment (RandomShaper) [inline core/input/input.cpp:1529]: You can use the first branch of the `if` directly, since `HashMap::operator[]` will add the entry if not already present.

File: doc/classes/Input.xml [hunk 2]
```diff
@@ -120,6 +120,20 @@
 				Returns a SDL2-compatible device GUID on platforms that use gamepad remapping. Returns [code]"Default Gamepad"[/code] otherwise.
 			</description>
 		</method>
+		<method name="should_ignore_device" qualifiers="const">
```
Comment (RandomShaper) [inline doc/classes/Input.xml:123]: As CI has shown, this has to be more to the bottom.

**Review by RandomShaper — CHANGES_REQUESTED** [review]
Looks fine, beside the little things. If no one can confirm about Mac in the short term, we can just merge and iterate if news finally come on that later.

File: core/input/input.h [hunk 3]
```diff
@@ -151,6 +151,9 @@ class Input : public Object {
 	VelocityTrack mouse_velocity_track;
 	HashMap<int, VelocityTrack> touch_velocity_track;
 	HashMap<int, Joypad> joy_names;
+
+	HashMap<uint16_t, Vector<uint16_t>> ignored_vid_pid_devices;
```
Comment (RandomShaper) [inline core/input/input.h:155]:
```suggestion
	union DeviceId {
		struct {
			uint16_t vid;
			uint16_t pid;
		} parts;
		uint32_t full;
	};
	HashSet<DeviceId> ignored_device_ids;
```

File: core/input/input.cpp [hunk 4]
```diff
@@ -1462,6 +1463,10 @@ String Input::get_joy_guid(int p_device) const {
 	return joy_names[p_device].uid;
 }
 
+bool Input::should_ignore_device(int vendor_id, int product_id) const {
+	return ignored_vid_pid_devices.has(vendor_id) && (ignored_vid_pid_devices[vendor_id].find(product_id) != -1);
+}
```
Comment (RandomShaper) [inline core/input/input.cpp:1468]:
```suggestion
bool Input::should_ignore_device(int p_vendor_id, int p_product_id) const {
	DeviceId id = {};
	id.parts.vid = (uint16_t)p_vendor_id;
	id.parts.pid = (uint16_t)p_product_id;
	return ignored_device_ids.has(id.full);
}
```

**Review by RandomShaper — CHANGES_REQUESTED** [review]
Regarding the suggested changes, TIWAGOS, but I believe they're good in spirit.

**Comment by Eoin-ONeill-Yokai** [comment]
I've gone ahead and made the suggested changes as they all seem to be a good idea. I haven't tested it yet but I'll find some time to test it on Monday.  I presume it will all work, but I think one of the changes suggested that I cast to a 16bit int and then shift 16 bits, which I think wouldn't work due to bit limitation so instead I'm casting the `vid` to 32bit int and shifting that left 16bits. I think that seems correct to me at least.

File: core/input/input.cpp [hunk 5]
```diff
@@ -1498,6 +1499,11 @@ String Input::get_joy_guid(int p_device) const {
 	return joy_names[p_device].uid;
 }
 
+bool Input::should_ignore_device(int vendor_id, int product_id) const {
```
Comment (RandomShaper) [inline core/input/input.cpp:1502]:
```suggestion
bool Input::should_ignore_device(int p_vendor_id, int p_product_id) const {
```

**Comment by Eoin-ONeill-Yokai** [comment]
Ok I've made all the necessary changes.

I've also relocated the conditional branch within the `joypad_linux.cpp` which was arguably in the wrong place. This seems to work more consistently than the previous iteration (which would have to double-check with godot whether or not the controller is properly "connected" or not, which is unnecessary.) Now devices should be ignored and never registered as a joystick if that's what steam wants.

**Review by RandomShaper — APPROVED** [review]

File: doc/classes/Input.xml [hunk 6]
```diff
@@ -343,6 +343,20 @@
...
+			<param index="0" name="vendor_id" type="int" />
+			<param index="1" name="product_id" type="int" />
+			<description>
+				Returns whether the device is requested to be ignored or not.
+
+				There are certain scenarios where game devices should be ignored; The most common scenario being that a 3rd party api (for example, [i]SteamInput[/i]) is already using an existing
+				device to add a new virtual device which should be watched instead. In such a case, we should respect the virtual device and ignore the original device that is being translated.
+				This allows for full gamepad rebinding features without resulting in multiple input events being registered from the same device.
+
+				Devices can be ignored by setting the environment variable [code]SDL_GAMECONTROLLER_IGNORE_DEVICES[/code] before booting the Godot Engine or Project. Read SDL documentation for more details.
```
Comment (YuriSizov) [inline doc/classes/Input.xml:357]: There shouldn't be any empty lines in the description, or line breaks mid-sentence. Each new line creates a new paragraph.

```suggestion
				Returns whether the device is requested to be ignored or not. Devices can be ignored by setting the [code]SDL_GAMECONTROLLER_IGNORE_DEVICES[/code] environment variable before booting Godot or your project. Read SDL documentation for more details.
				[b]Note:[/b] Some 3rd party tools can contribute to the list of ignored devices. For example, [i]SteamInput[/i] creates virtual devices to allow free key and input remapping. To avoid handling the same input device twice, the original device is added to the ignore list.
```

`Read SDL documentation for more details.` should also link to the said documentation.

**Review by YuriSizov — CHANGES_REQUESTED** [review]

File: doc/classes/Input.xml (hunk 6 above)
Comment (Eoin-ONeill-Yokai) [reply doc/classes/Input.xml]: Thanks for the review. 

I've gone ahead and fixed the formatting. Additionally, I did some rewording to make it easer to read and be a bit more concise. Let me know if there's any other changes you'd like!

File: doc/classes/Input.xml [hunk 7]
```diff
@@ -343,6 +343,15 @@
 				[b]Note:[/b] This value can be immediately overwritten by the hardware sensor value on Android and iOS.
 			</description>
 		</method>
+		<method name="should_ignore_device" qualifiers="const">
+			<return type="bool" />
+			<param index="0" name="vendor_id" type="int" />
+			<param index="1" name="product_id" type="int" />
+			<description>
+				Queries whether an input device should be ignored or not. Devices can be ignored by setting the environment variable [code]SDL_GAMECONTROLLER_IGNORE_DEVICES[/code]. Read the [url="https://wiki.libsdl.org/SDL2"]SDL documentation[/url] for more information.
```
Comment (YuriSizov) [inline doc/classes/Input.xml:351]:
```suggestion
				Queries whether an input device should be ignored or not. Devices can be ignored by setting the environment variable [code]SDL_GAMECONTROLLER_IGNORE_DEVICES[/code]. Read the [url=https://wiki.libsdl.org/SDL2]SDL documentation[/url] for more information.
```

Though I think quotation marks are handled fine now, they are also unnecessary and we don't use them anywhere else in the docs. So for consistency they should be removed.

File: doc/classes/Input.xml [hunk 8]
```diff
@@ -343,6 +343,15 @@
...
+				[b]Note:[/b] Some 3rd party tools can contribute to the list of ignored devices. For example, [i]SteamInput[/i] creates virtual devices from physical devices for rebinding purposes. To avoid handling the same input device twice, the original device is added to the ignore list.
```
Comment (YuriSizov) [inline doc/classes/Input.xml:352]:
```suggestion
				[b]Note:[/b] Some 3rd party tools can contribute to the list of ignored devices. For example, [i]SteamInput[/i] creates virtual devices from physical devices for remapping purposes. To avoid handling the same input device twice, the original device is added to the ignore list.
```

I think "remapping" would be more appropriate here, but it's not critical.

**Review by YuriSizov — APPROVED** [review]
Docs look good now. Just a couple of nitpicks.

**Comment by Eoin-ONeill-Yokai** [comment]
@YuriSizov Thanks again, went ahead and fixed the last remaining problems.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
