### PR TITLE
Fix incorrect Rect2i calculations: intersects and encloses

### LINKED ISSUE #57468: Some Integer Rect2i calculations are incorrect
### Godot version

v4.0.alpha.custom_build [78e3e65e7]

### System information

Debian 11, Vulkan

### Issue description

Rect2i makes some calculation based on floating arithmetic, which do not correctly apply to the integer case.

1. During the calculation of the intersection of the blue (0,0)-(1,1) and red (2,2)-(3,3) rectangle according to the following diagram with Rect2i (integer version) there are inconsistencies.

rect2i

I would expect that the two rectangles do not intersect.

2. A Rect2i should enclose itself

3. Expanding to the positive side does not work

The following code tests this:
```
func _ready():
	var a1 = Rect2i(0, 0, 2, 2)
	var a2 = Rect2i(2, 2, 2, 2)
	print(a1.intersects(a2))
	print(a1.expand(Vector2i(2,2)).has_point(Vector2i(2,2)))
	print(a1.encloses(a1))
```
The code outputs the following result:
```
true
false
false
```

I would expect the following output:
```
false
true
true
```

### Steps to reproduce

Load and run the Minimal reproduction project

### Minimal reproduction project

[Rect2iCalculations.zip](https://github.com/godotengine/godot/files/7968949/Rect2iCalculations.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Correction of some border cases for Rect2i calculations.
Clarify expand documentation.
Added Unit tests for these cases.

resolves #57468

### CODE REVIEW

**Review by lawnjelly — APPROVED** [review]
Looks good to me.

**Comment by lawnjelly** [comment]
Just to note that this exclusive definition is the usual way of handling integer bounds in my experience. It is a matter of definition of course, but it's the same as an integer range in a for loop being:
```
for (int x=0; x<10; x++)
```
includes 0 to 9, but not 10.

One fun thing to mention with the plus one in the `expand_to` function, is that if you are doing this in any tight loops with thousands of points, it is possible to optimize by using the non plus one version, then adding one to the size at the end as a one off, rather than for every point.

File: core/math/rect2.h [hunk 1]
```diff
@@ -531,11 +531,11 @@ struct _NO_DISCARD_ Rect2i {
 			begin.y = p_vector.y;
 		}
 
-		if (p_vector.x > end.x) {
-			end.x = p_vector.x;
+		if (p_vector.x >= end.x) {
+			end.x = p_vector.x + 1;
```
Comment (akien-mga) [inline core/math/rect2.h:535]: That seems very weird to me. IMO the current behavior was correct, and if the documentation makes it sound like it should be different, then the documentation should be changed.

I would definitely be confused if `Rect2i(0, 0, 10, 10).expand(Vector2i(20, 10))` returns `Rect2i(0, 0, 21, 11)`.

**Comment by Sauermann** [comment]
> One fun thing to mention with the plus one in the `expand_to` function, is that if you are doing this in any tight loops with thousands of points, it is possible to optimize by using the non plus one version, then adding one to the size at the end as a one off, rather than for every point.

In order to optimize this, iterate over all points while setting minx, miny, maxx, maxy and afterwards call `expand_to` twice. That way you don't calculate begin, end, position and size multiple times.

File: core/math/rect2.h [hunk 2]
```diff
@@ -382,16 +382,16 @@ struct _NO_DISCARD_ Rect2i {
 			ERR_PRINT("Rect2i size is negative, this is not supported. Use Rect2i.abs() to get a Rect2i with a positive size.");
 		}
 #endif
-		if (position.x > (p_rect.position.x + p_rect.size.width)) {
+		if (position.x >= (p_rect.position.x + p_rect.size.width)) {
```
Comment (bruvzg) [inline core/math/rect2.h:385]: Might be better to add an extra argument instead, like it was done for `Rect2` in https://github.com/godotengine/godot/pull/36021, and have both options.

File: core/math/rect2.h [hunk 3]
```diff
@@ -405,8 +405,8 @@ struct _NO_DISCARD_ Rect2i {
 		}
 #endif
 		return (p_rect.position.x >= position.x) && (p_rect.position.y >= position.y) &&
-				((p_rect.position.x + p_rect.size.x) < (position.x + size.x)) &&
-				((p_rect.position.y + p_rect.size.y) < (position.y + size.y));
+				((p_rect.position.x + p_rect.size.x) <= (position.x + size.x)) &&
+				((p_rect.position.y + p_rect.size.y) <= (position.y + size.y));
```
Comment (bruvzg) [inline core/math/rect2.h:409]: For the reference, same change was done for `Rect2` in https://github.com/godotengine/godot/pull/32478

File: core/math/rect2.h (hunk 2 above)
Comment (Sauermann) [reply core/math/rect2.h:385]: This would probably be better suited as a separate pull request.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by lawnjelly** [comment]
Just to note that my review approval was based on the PR having the `expand_to()` being the "+1" definition, rather than Groud's version.

`expand_to()` is normally taken to mean "expand_to_include", that is the usual use of the function, to enlarge a bound to include a series of points. If you have a look at other libraries which use integer bounds you should see this (providing they use the exclusive definition of a bound).

Thus in this common usage, by definition, `expand_to(foo)` should now include the point "foo" and return `has_point(foo)` as true.

### Problems with the non +1 version
The non +1 version of expand is sometimes used, particularly for optimization, but will not work well in the general case, there are a number of situations it can't deal with well.

### Some examples
For instance, if you have an existing bound say in 1 dimension, (0 position, 10 size) and you want to expand that bound to include a point:

* If you want to expand the bound to include the point 15, in this existing version you would have to call:
```
expand_to(15);
size += 1;
```
* Whereas if you want to expand the bound to include the point 5, you would have to call:
```
expand_to(5);
```
You immediately have a problem, because the user needs to add code to deal with these two different situations.

* Thus you might start with a check at runtime something like the following:
```
old_bound = bound;
bound.expand_to(new_point);
if (bound.size > old_bound.size)
{
bound.size +=1;
}
```
_However_, there is a bigger problem.
* Consider if you wanted to add the point 10 to the existing bound:
```
old_bound = bound;
bound.expand_to(10);
// bound now includes numbers 0 to 9 inclusive
if (bound.size > old_bound.size)
{
// this if check fails, and the bound is now incorrect
bound.size += 1;
} 
```
* If you wanted this to work, your _simple_ code would now become something like
```
old_bound = bound;
bound.expand_to(10);
if ((bound.size > old_bound.size) || ((bound.position + bound.size) == 10))
{
bound.size += 1;
}
```
This is one of a number of cases where this non +1 definition of `expand_to` breaks down.

### +1 definition "just works"
With the standard definition of `expand_to_include(foo)`, with +1, the code in all cases becomes:
```
bound.expand_to_include(10);
```
And it works in all situations.

### Why the confusion?
I have a feeling there may be a confusion because using inclusive bounds (i.e. position 0, size 1, includes 0 and 1) which _we do not use_, then you don't need to apply the +1. But with exclusive, you do.

**Comment by Sauermann** [comment]
For reference, here are the locations in the code base, that use `Rect2i.expand_to`:

https://github.com/godotengine/godot/blob/2aee84c755ccb5674b257d7b281bbfb7a3769f44/editor/editor_atlas_packer.cpp#L103

Here point+(1,1) is explicitly included (and would benefit from the +1 version):
https://github.com/godotengine/godot/blob/2aee84c755ccb5674b257d7b281bbfb7a3769f44/editor/plugins/tiles/tile_map_editor.cpp#L1559-L1560

https://github.com/godotengine/godot/blob/2aee84c755ccb5674b257d7b281bbfb7a3769f44/editor/plugins/tiles/tile_map_editor.cpp#L2979

Here`screen_rect.grow(1)` is used to enlarge the Rect2i after the expansions (and would benefit from the +1 version):
https://github.com/godotengine/godot/blob/2aee84c755ccb5674b257d7b281bbfb7a3769f44/editor/plugins/tiles/tile_map_editor.cpp#L3855-L3858

https://github.com/godotengine/godot/blob/2aee84c755ccb5674b257d7b281bbfb7a3769f44/scene/2d/tile_map.cpp#L3377
