### PR TITLE
Pushes visual shader code preview to separate window

### LINKED ISSUE #42612: Visual Shader Editor - Can't close code preview on low-mid res display
No dupes of this issue were found with search. Or i can't search things. Either of these.

**Godot version:**
v3.2.2.stable.official from godot website.
Win10 x64
Screen resolution 1366 x 768 (laptop Dell Inspiron 5558)

**Issue description:**
Can't close code preview because it overlays the button that opens/closes it.
Also there is no "X" button to close code preview.
image
image

Only solution to close the code preview is to stretch inspector and sceene-manager side windows as much as possible, BUT IT WON'T HELP with much smaller screen resolutions:
image

**Steps to reproduce:**
Open blank project, enter visual shader editor on 1366 x 768 or narrower resolution. Open code preview.

### PR DESCRIPTION
**Pull request by Chaosus**
vs_preview_window3

Fix #42612

### CODE REVIEW

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 1]
```diff
@@ -2971,24 +2996,30 @@ VisualShaderEditor::VisualShaderEditor() {
 	preview_shader->connect("pressed", callable_mp(this, &VisualShaderEditor::_show_preview_text));
 
 	///////////////////////////////////////
-	// PREVIEW PANEL
+	// PREVIEW WINDOW
 	///////////////////////////////////////
 
+	preview_window = memnew(Window);
+	preview_window->set_title(TTR("Resulted shader code"));
```
Comment (akien-mga) [inline editor/plugins/visual_shader_editor_plugin.cpp:3003]: I don't know if "Resulted" is correct, I think it might be better with "Resulting" or "Generated" ("Generated" is likely the clearest, provided that it's an accurate description of what this is).

Comment (Chaosus) [reply editor/plugins/visual_shader_editor_plugin.cpp:3003]: Then a button tooltip should also be changed to "Show generated shader code"?

Comment (Chaosus) [reply editor/plugins/visual_shader_editor_plugin.cpp]: Alright, changed both of them..

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Does it work fine in single window mode too? I guess it would become an embedded popup?

**Comment by Chaosus** [comment]
> Does it work fine in single window mode too? I guess it would become an embedded popup?

Yes, it works.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YeldhamDev** [comment]
It's a little weird that the button still works as a toggle. I don't think any other editor window works like this.

**Comment by Chaosus** [comment]
I don't see a problem - this window should have only one instance and the toggle button does indicate that window is opened and controls its visibility. Yes, it a bit unusual across engine, but why not?
