### PR TITLE
Restore script class cache if removed

### LINKED ISSUE #72154: Script classes are not regenerated project-wide after first import
### Godot version

4.0.dev.d1e5903c67956707948b1de370b807e3aad395b7

### System information

macOS 13.1

### Issue description

Script classes are not regenerated project-wide after first import. See the reproduction steps below.

This is a huge problem for large games since a class may not have all of its dependencies ready by the time it comes to parsing the script, so it doesn't get registered on the first pass, and there are no other passes. The only solution is to manually open every single script and save it (potentially multiple times if there are long dependency chains).

The symptom is happening as of #70557, but the root cause was still present before that PR. If I revert that PR, open the reproduction project, and then instead of deleting the below file I empty out the `_global_script_class*` members, A and B do not regenerate (but they do if you open and save them). This has become a serious regression because the class list is no longer saved to version control, so you can end up in a situation where deleting `.godot/` results in a broken project until you manually open and save every script (for every developer, every time they delete `.godot/`).

### Steps to reproduce

1. Download an open the below minimal reproduction project.
2. Look at the generated `.godot/global_script_class_cache.cfg` file. Both A and B will be in there (good).
3. Close Godot and delete this file.
4. Open Godot again.
5. Look at the lack of a `.godot/global_script_class_cache.cfg` file. It is not regenerated (bad).
6. Open the `a.gd` script and save it.
7. Look at the generated `.godot/global_script_class_cache.cfg` file. Only A will be in there, but B will not (bad).

### Minimal reproduction project

[GlobalClassMissing.zip](https://github.com/godotengine/godot/files/10515105/GlobalClassMissing.zip)

### PR DESCRIPTION
**Pull request by reduz**
I have no idea why anyone would do this, but this fixes it.

Fixes #72154. Depends on #72444 being merged to function properly.

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -1132,12 +1132,14 @@ Variant ProjectSettings::get_setting(const String &p_setting, const Variant &p_d
...
 
+#define GLOBAL_CLASS_LIST_CACHE_FILE "global_script_class_cache.cfg"
+
 Array ProjectSettings::get_global_class_list() {
 	Array script_classes;
 
 	Ref<ConfigFile> cf;
 	cf.instantiate();
-	if (cf->load(get_project_data_path().path_join("global_script_class_cache.cfg")) == OK) {
+	if (cf->load(get_project_data_path().path_join(GLOBAL_CLASS_LIST_CACHE_FILE)) == OK) {
```
Comment (akien-mga) [inline core/config/project_settings.cpp:1142]: I would use `get_global_class_list_path()` here, and in `store_global_class_list()` too.

Then there's maybe not need for the define anymore as it will be hardcoded only once.

**Review by akien-mga — APPROVED** [review]

**Comment by Lippanon** [comment]
> I have no idea why anyone would do this, but this fixes it.
I've seen it be recommended to delete the .godot folder between engine updates. Indeed when one doesn't, one often encounters errors and bugs that go away if .godot is deleted and the projected reopened.

**Comment by akien-mga** [comment]
Thanks!
