### PR TITLE
Fix combatibility with older .scn files

### LINKED ISSUE #13162: *.scn file support is broken (regression from 0cf959775)
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/f8fd9a4a62e32a34dc6ae888884eea115dcd75b4

**Issue description:**

Opening any project with an *.scn will greet you with the following errors:

and when you try to open it anyway:

Full error log:

```
ERROR: add_register_func: Condition ' register_funcs.has(p_name) ' is true.
   At: modules\visual_script\visual_script.cpp:2643
erasing C:\Users\mrcdk\AppData\Roaming/Godot/projects/platformer-b26b16aecf77a9f6596f3e73766553c3/filesystem_update3
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://coin.scn
   At: core\io\resource_loader.cpp:184
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://enemy.scn
   At: core\io\resource_loader.cpp:184
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://player.scn
   At: core\io\resource_loader.cpp:184
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://coin.scn
   At: core\io\resource_loader.cpp:184
WARNING: parse_variant: Couldn't load resource: res://coin.scn
     At: core\io\resource_format_binary.cpp:354
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://enemy.scn
   At: core\io\resource_loader.cpp:184
WARNING: parse_variant: Couldn't load resource: res://enemy.scn
     At: core\io\resource_format_binary.cpp:354
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://player.scn
   At: core\io\resource_loader.cpp:184
WARNING: parse_variant: Couldn't load resource: res://player.scn
     At: core\io\resource_format_binary.cpp:354
ERROR: remove_scene: Indexp_idx=1 out of size (edited_scene.size()=1)
   At: editor\editor_data.cpp:491
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://coin.scn
   At: core\io\resource_loader.cpp:184
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://enemy.scn
   At: core\io\resource_loader.cpp:184
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://player.scn
   At: core\io\resource_loader.cpp:184
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://coin.scn
   At: core\io\resource_loader.cpp:184
WARNING: parse_variant: Couldn't load resource: res://coin.scn
     At: core\io\resource_format_binary.cpp:354
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://enemy.scn
   At: core\io\resource_loader.cpp:184
WARNING: parse_variant: Couldn't load resource: res://enemy.scn
     At: core\io\resource_format_binary.cpp:354
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://bullet.scn
   At: core\io\resource_loader.cpp:184
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://bullet.scn
          At: res://player.gd:170
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules\gdscript\gdscript.cpp:582
ERROR: parse_variant: Method/Function Failed, returning: ERR_FILE_CORRUPT
   At: core\io\resource_format_binary.cpp:613
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core\io\resource_loader.cpp:147
ERROR: Failed loading resource: res://player.scn
   At: core\io\resource_loader.cpp:184
WARNING: parse_variant: Couldn't load resource: res://player.scn
     At: core\io\resource_format_binary.cpp:354
ERROR: instance: Condition ' !sdata.is_valid() ' is true. returned: __null
   At: scene\resources\packed_scene.cpp:136
ERROR: remove_scene: Indexp_idx=1 out of size (edited_scene.size()=1)
   At: editor\editor_data.cpp:491
```

**Steps to reproduce:**
1. Open the Platformer 3D demo

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #13162. There might be some problems opening .scn files created after 613d374bc571929d601af1eab17079a639fe576f, because the format was changed without changing the version number.

### CODE REVIEW

File: core/io/resource_format_binary.cpp [hunk 1]
```diff
@@ -84,8 +84,10 @@ enum {
 	OBJECT_INTERNAL_RESOURCE = 2,
 	OBJECT_EXTERNAL_RESOURCE_INDEX = 3,
 	//version 2: added 64 bits support for float and int
-	FORMAT_VERSION = 2,
-	FORMAT_VERSION_CAN_RENAME_DEPS = 1
+	//version 3: changed nodepath encoding
```
Comment (akien-mga) [inline core/io/resource_format_binary.cpp]: Good, now we're in sync with 3.0 :P
