### PR TITLE
GDScript: Fix setter being called in chains for shared types

### LINKED ISSUE #28720: Assigning a value to a getter's variable results in calling its setter function
**Godot version:**

3.1.1

**OS/device including version:**

Windows 10/Nvidia GeForce GTX 1070

**Issue description:**

What happened:
Assigning setter's variable results in calling getter and setter function 
What was expected:
To not to call the setter function.

**Steps to reproduce:**

Just assign value to a variable, declared inside the class that is used as setter/getter (or download minimal reproduction project), e.g.:
```
# engine is a setter/getter in Car script
# engine's getter will be called, that is OK, 
# engine's setter will be callled, that is NOT OK
$Car.engine.speed = 60 
```
**Minimal reproduction project:**
[MinimalReproductionProject.zip](https://github.com/godotengine/godot/files/3147374/MinimalReproductionProject.zip)

### LINKED ISSUE #31245: GDScript error when using `get_tree().root.foo = bar` (setter called on property with read-only property)
**Godot version:**
Tested on nightly build and 3.1.1

**OS/device including version:**
GNU/Linux x64

**Issue description:**
The engine seems to only throw an error when using get_tree().root.foo = bar, I tried with another object and the script ran fine.
image

**Steps to reproduce:**
use get_tree().root.foo = bar in a script

**Minimal reproduction project:**
[GDScriptBug.zip](https://github.com/godotengine/godot/files/3487608/GDScriptBug.zip)

### LINKED ISSUE #57793: [Godot4 Alpha1] setter called twice
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

aaa
I only call 'editor=<sth>', but it's setter called twice.

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[GetSetTest.zip](https://github.com/godotengine/godot/files/8022196/GetSetTest.zip)

### LINKED ISSUE #60796: GD Script variable setter is called when a variable behind a variable behind the reference is modified.
### Godot version

4.0 alpha 7

### System information

Archlinux, KDE x11

### Issue description

I'm unsure if this is normal behavior but it felt odd, and someone on discord confirmed it was weird:

In a gdscript attached to a node, when a variable which is a reference to a node has a setter, if you edit a variable behind that reference, it calls the variables setter function. This should be reproducible in the attached project.

In other words, the setter isn't just being called when the variable is set, it's being called whenever any of its properties are set, too, making it kind of useless.

### Steps to reproduce

In a Node-A's attached script:
- Declare a variable with a setter, to hold Node-B (it may reproduce for things other than nodes, but I didn't test this)
- In the setter, set the variable and print it out at the same time
- In Node-A's _process function, set any property on Node-B (can also be a custom property declared in a script attached to Node-B)

You should see that every time Node-A's process method is called, so is Node-B's setter, even though node B hasn't directly changed.

### Minimal reproduction project

[TestProjectForSetterBug.zip](https://github.com/godotengine/godot/files/8632700/TestProjectForSetterBug.zip)

### PR DESCRIPTION
**Pull request by vnen**
When a type is shared (i.e. passed by reference) it doesn't need to be called in a setter chain (e.g. `a.b.c = 0`) since it will be updated in place.

This PR adds an instruction that jumps when the value is shared so it can be used to skip those cases and avoid redundant calls of setters. It also solves issues when assigning to sub-properties of read-only properties.

There are some duplicate issues for this that I could find:
Fixes #28720
Fixes #31245
Fixes #57793
Fixes #60796

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Code looks good, as far as I'm able to assess (not much :D).

**Comment by AThousandShips** [comment]
Unfortunately this seems to break access to types that are returned by value:
```gdscript
var dict : Dictionary = { "A":Transform2D() }
dict["A"].origin = Vector2(1.0, 2.0)
```
Has no effect

Same goes for:
```gdscript
var tr = Transform3D()
tr.basis.x = Vector3(2.0, 0.0, 0.0)
```

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -1056,33 +1056,61 @@ GDScriptCodeGenerator::Address GDScriptCompiler::_parse_expression(CodeGen &code
...
+							}
+						} else {
+							gen->write_set_named(info.base, info.name, assigned);
 						}
-					} else {
-						gen->write_set_named(info.base, info.name, assigned);
+					}
+					if (!known_type) {
+						gen->write_end_jump_if_shared();
 					}
```
Comment (cdemirer) [inline modules/gdscript/gdscript_compiler.cpp:1078]: The above probably needs a similar logic to the part outside the loop (`if (!known_type || !is_shared)`) because currently `jump_if_shared` only jumps to the very next instruction :slightly_smiling_face: 

```gdscript
extends Node3D

func _ready():
    var dict : Dictionary = {}
    dict["A"]["B"].origin = Vector2()
```
```
Disassembling _ready()
 0: line 4:     var dict : Dictionary = {}
 2: make_dict stack(4) = {}
 5: assign stack(3) = stack(4)
 8: line 5:     dict["A"]["B"].origin = Vector2()
 10: get keyed validated stack(5) = stack(3)[const("A")]
 15: get keyed stack(6) = stack(5)[const("B")]
 19: set_named stack(6)["origin"] = const((0, 0))
 23: jump-if-shared stack(6) to 26
 26: jump-if-shared stack(5) to 29
 29: == END ==
```
