### PR TITLE
Search terms are now highlighted when the bar opens with a selection.

### LINKED ISSUE #82706: Search matches are not highlighted when opening search with a selection
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.12027.9001) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

In the code editor, when the search bar is up, search matches in the current document are normally highlighted. However, if the bar is opened by pressing Ctrl+F with a selection, the search bar is populated with the selection, but no highlighting occurs until the user goes to the next result or changes the search query.

### Steps to reproduce

1. Create a script file and paste the follow in it:
```
extends Node

func _ready() -> void:
	var arr : Array = [1, 2, 3, 4]
	print(arr)
	print(arr)
```
2. Double-click any occurrence of `arr` to select it.
3. Press Ctrl+F

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by BrianMacIntosh**
Previously, the code editor only updated the text highlights when a search was made, but opening the search bar with a selection does not go through that code path because the first result is already selected.

This is a fix for #82706.

*Bugsquad edit:*
- Fixes #82706.

### CODE REVIEW

**Review by MewPurPur — APPROVED** [review]
Nitpick: `dir` makes me think of a directory rather than direction. Otherwise, looks excellent!

**Comment by BrianMacIntosh** [comment]
> Nitpick: `dir` makes me think of a directory rather than direction. Otherwise, looks excellent!

Thanks for the feedback - I went ahead and amended it.

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -536,6 +528,10 @@ void FindReplaceBar::_show_search(bool p_focus_replace, bool p_show_only) {
 			search_text->set_caret_column(search_text->get_text().length());
 		}
 
+		_update_flags(false);
```
Comment (jsjtxietian) [inline editor/code_editor.cpp:531]: Can we just add a `_search_text_changed(get_search_text())` call after `search_text->set_text(text_editor->get_selected_text(0))` ? Force doing a search when the search bar is shown.

Comment (BrianMacIntosh) [reply editor/code_editor.cpp:531]: That would clean the code up but it triggers a search_current unnecessarily, since the the first search match is already selected in this case. I figured that's why the stuff that was already here was inlined in the first place, so I stuck with that.

If you guys think that slight inefficiency is worth the cleaner code I can change it.

Comment (BrianMacIntosh) [reply editor/code_editor.cpp:531]: @jsjtxietian what do you think about my post above?

Comment (jsjtxietian) [reply editor/code_editor.cpp:531]: Ah sorry for the late reply. IMHO both are fine, it's a choice between a little readability and performance. I slightly perfer my suggestion because it introduces less change which could potentially introduce less bug.

Comment (BrianMacIntosh) [reply editor/code_editor.cpp]: I made that change, with the exception that I left the `_search_text_changed` where the existing result-updating code was in the not-empty check, to avoid doing it unnecessarily and minimize the change.

**Comment by AThousandShips** [comment]
You've rebased your branch incorrectly and taken over other people's commits

**Comment by BrianMacIntosh** [comment]
> Please reset your branch by doing: `git reset --hard 40118f1707c5077a6de3576abc6e20f30fa7c0d8` and then try again

Thanks, I didn't realize I needed to force push after a rebase.

File: editor/code_editor.cpp [hunk 2]
```diff
@@ -546,11 +538,7 @@ void FindReplaceBar::_show_search(bool p_focus_replace, bool p_show_only) {
 			search_text->set_caret_column(search_text->get_text().length());
 		}
 
-		results_count = -1;
-		results_count_to_current = -1;
-		needs_to_count_results = true;
-		_update_results_count();
-		_update_matches_label();
+		_search_text_changed(get_search_text());
```
Comment (Paulb23) [inline editor/code_editor.cpp:541]: Should probably set `preserve_cursor=true` before this to prevent the jumping around the text when simply opening the searchbar, with whatever was in there previously.

Comment (BrianMacIntosh) [reply editor/code_editor.cpp:542]: Reproduced and changed, thanks.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
