### PR TITLE
Clear current path when deselecting files

### LINKED ISSUE #92867: Saving a scene re-selects a file
### Tested versions

4.3 beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/1c6b8abd-0407-4339-a3d8-6912fdf25b1c

### Steps to reproduce

1. Select a file in FileSystem dock
2. Deselect it by clicking empty space
3. Press Ctrl+S (make sure you are in 2D or 3D editor)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #92867

https://github.com/user-attachments/assets/33d9f034-ec49-444d-9492-c7e0e1e24956

This also fixes a problem where you may end up with a random file selected after project restart, which can result in many uncollapsed folders.

### CODE REVIEW

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -3581,6 +3581,11 @@ void FileSystemDock::_tree_empty_click(const Vector2 &p_pos, MouseButton p_butto
 
 void FileSystemDock::_tree_empty_selected() {
 	tree->deselect_all();
+	current_path = "";
+	current_path_line_edit->set_text(current_path);
```
Comment (Mickeon) [inline editor/filesystem_dock.cpp:3585]: This feels like it should be associated to its own method that sets both at once, but I don't know about the internals of this

Comment (KoBeWi) [reply editor/filesystem_dock.cpp:3585]: I counted 2 other places that could use the method. In other cases the path and text are assigned separately, like
https://github.com/godotengine/godot/blob/46c495ca21f40f57a7fb9c7cde6143738f1652d4/editor/filesystem_dock.cpp#L1742-L1748
so the method would be not very useful.

**Review by Mickeon — APPROVED** [review]
This should've always been the case even if it didn't fix anything

**Comment by Repiteo** [comment]
Thanks!
