### PR TITLE
[GraphEdit] Do not scale popup menus in the graph elements when zoomed.

### LINKED ISSUE #108609: Inconsistant Visual Shader Dropdown Size
### Tested versions

4.5 beta3. I first noticed it in one of 4.5 dev versions.

### System information

Godot v4.5.beta (c6d130abd) - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21923.1000) - Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 threads) - 15.96 GiB memory

### Issue description

Zoom level 207%

Image

Zoom level 60%
Image

The difference in size of the dropdown menu is distracting.

### Steps to reproduce

Open texture2d's dropdown menu

### Minimal reproduction project (MRP)

No need

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/108609

https://github.com/user-attachments/assets/a6a695c3-e53f-4d1f-bedd-5db2e739ea7d

### CODE REVIEW

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -3221,12 +3224,27 @@ void PopupMenu::popup(const Rect2i &p_bounds) {
...
+#endif
+	if (scale_with_parent) {
+		Size2 scale = get_force_native() ? get_parent_viewport()->get_popup_base_transform_native().get_scale() : get_parent_viewport()->get_popup_base_transform().get_scale();
+		CanvasItem *c = Object::cast_to<CanvasItem>(get_parent());
+		if (c) {
+			scale *= c->get_global_transform_with_canvas().get_scale();
+		}
+		popup_scale = MIN(scale.x, scale.y);
 	}
-	real_t popup_scale = MIN(scale.x, scale.y);
```
Comment (YeldhamDev) [inline scene/gui/popup_menu.cpp:3380]: A comment would be nice, since it's about a feature from a different node.
I would also add some some blank lines here and there, so it becomes less of a blob and easier to read at a glance.

File: scene/gui/popup_menu.cpp [hunk 2]
```diff
@@ -3223,12 +3226,31 @@ void PopupMenu::popup(const Rect2i &p_bounds) {
...
 
 void PopupMenu::_pre_popup() {
-	Size2 scale = get_force_native() ? get_parent_viewport()->get_popup_base_transform_native().get_scale() : get_parent_viewport()->get_popup_base_transform().get_scale();
-	CanvasItem *c = Object::cast_to<CanvasItem>(get_parent());
-	if (c) {
-		scale *= c->get_global_transform_with_canvas().get_scale();
+	real_t popup_scale = 1.0;
+	bool scale_with_parent = true;
+
+#ifndef ADVANCED_GUI_DISABLED
```
Comment (AThousandShips) [inline scene/gui/popup_menu.cpp]: `PopupMenu` is itself advanced GUI so this is unnecessary I'd say

File: scene/gui/popup_menu.cpp [hunk 3]
```diff
@@ -35,6 +35,9 @@
 #include "core/input/input.h"
 #include "core/os/keyboard.h"
 #include "core/os/os.h"
+#ifndef ADVANCED_GUI_DISABLED
```
Comment (AThousandShips) [inline scene/gui/popup_menu.cpp]: Same here

File: scene/gui/graph_element.cpp [hunk 4]
```diff
@@ -226,6 +234,9 @@ void GraphElement::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_selected", "selected"), &GraphElement::set_selected);
 	ClassDB::bind_method(D_METHOD("is_selected"), &GraphElement::is_selected);
 
+	ClassDB::bind_method(D_METHOD("set_scaling_menus", "selected"), &GraphElement::set_scaling_menus);
```
Comment (AThousandShips) [inline scene/gui/graph_element.cpp]:
```suggestion
	ClassDB::bind_method(D_METHOD("set_scaling_menus", "scaling_menus"), &GraphElement::set_scaling_menus);
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
