### PR TITLE
Automatically create folder in project manager create and import

### LINKED ISSUE #2754: Add create folder button to project imports
### Describe the project you are working on
Various projects downloaded from Git.

### Describe the problem or limitation you are having in your project
Importing projects from a zip or project file in the import menu of the project manager requires users to create an empty folder outside of the godot editor. This adds extra time that can build up while checking out many different projects.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a "Create Folder" button to the import existing project menu that will parse the name of the file to import and create a folder for it in the same way as creating a new project gives you the option to create a folder.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

These are screenshots from a branch I have where this feature is implemented.

Screenshot from 2021-05-21 17-23-24
Screenshot from 2021-05-21 17-23-52

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It requires engine changes.

### Is there a reason why this should be core and not an add-on in the asset library?

It's an editor-specific function.

### LINKED ISSUE #4749: Automatically create directory when creating a new project
### Describe the project you are working on

Haven't made it yet

### Describe the problem or limitation you are having in your project

When creating a new project, there are many steps to create a typical directory structure.

- Type the directory name you want (e.g. `my-new-project`)
- Click "Create Folder"
- Re-type the project name you want (e.g. `My New Project`)

Since I make so many projects for testing, this can get tedious.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- Replace the "Create Folder" button with a `CheckButton`, enabled by default.

When "Create Folder" is active:
- The project name will be converted to the project directory using some algorithm. I propose: `My Project Name`->`my-project-name`, `Test1`->`test1`.
- Changing the project name will modify the project path (only if the path wasn't previously changed).
- The user is allowed to change the project path and it will not be automatically changed unless the user reverts their changes and changes the project name.
- Browsing to a path will create a new folder under that path.

When "Create Folder" is inactive:
- The project path is never changed by the engine.
- The project path must exist before the project can be created.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://user-images.githubusercontent.com/14253836/175791862-c7a608b4-ec3d-49dd-9d95-d57981304303.mp4

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Cannot be worked around without modifying the project manager

### Is there a reason why this should be core and not an add-on in the asset library?

The project manager is already part of the editor

### LINKED ISSUE #60332: Prevent creating projects in folders that can "brick" the editor until moved
### Godot version

3.3.4 flathub

### System information

Chromebook 32bit ran on linux

### Issue description

As soon as I open up Godot it has a tab (and this is the only tab) stating that Error: Can't run project: no main scene defined in the project.
It's just a white box that states that message and no matter what I do I cannot get past this stage, any help?

### Steps to reproduce

To reproduce these circumstances you need to on a Chromebook open a new project once recently download it, leave it empty and leave (I was checking out the software and then left) after that this error message will pop up. 

### Minimal reproduction project

[https://docs.google.com/presentation/d/1LyO5Yk52BFnr1MXw4soUyyKtkWC20i3Dj7SF7u_hLps/edit#slide=id.p](url for the error message)

### LINKED ISSUE #74678: Option to delete project contents when removing from Project Manager is too dangerous
### Godot version

4

### System information

Windows 10

### Issue description

I created a project to try the new version of Godot but I couldn't run it for more than 15 seconds.

Godot crashed after a short time so I wanted to delete the project in order to create another one and that's when the magic happened, 
it deleted not only the Godot project folder but also the folder before it i.e. my user folder ("C:\Users\\{user}\document") and of course nothing that was deleted was found in the recycle bin.

### Steps to reproduce

Create and delete a project via the launcher

### Minimal reproduction project

empty

### PR DESCRIPTION
**Pull request by nathanfranke**
### Edit:

~~2023-09-07 - I am busy, but once I have time this will be my top priority PR.~~
~~2023-10-17 - I am working on this slowly :slightly_smiling_face:~~
2023-10-18 - Rebased and happy, but should wait for 4.3 :smiley: 

---

Supersedes https://github.com/godotengine/godot/pull/49602
Fixes https://github.com/godotengine/godot/issues/60332
Fixes https://github.com/godotengine/godot/issues/74678
Resolves https://github.com/godotengine/godot-proposals/issues/4749
Resolves https://github.com/godotengine/godot-proposals/issues/2754
Partly r3solves https://github.com/godotengine/godot-proposals/issues/7978

### Behavior:

- When create_dir is enabled, browse selects the containing/parent directory, project name is appended.
- When create_dir is disabled, whether before or after browsing, browse selects the exact project folder.
- Directory naming convention is configurable. `kebab-case` (default), `snake_case`, etc.

### Potential improvements:

- ~~Behavior of `capitalize()` means `test5` turns into `test-5/`.~~ Fixed, now `test5` --> `test5/`
- Persist/remember if `create_dir` is pressed. Would we need an editor setting?
- Maybe bug: horizontal scroll position of target path resets on change

Video:

https://user-images.githubusercontent.com/14253836/219931962-029b1d8f-21aa-4a68-91ba-320601b0f499.mp4

Creation:
image

Import:
image

### CODE REVIEW

**Comment by timothyqiu** [comment]
When the project name is "Test" and "Create Folder" is on, project path is "/path/to/dir/Test". If I then change the path to "/path/do/dir/DoesNotExist" and click "Create & Edit". It creates and uses the "DoesNotExist" folder for me.

I'm not sure if this is expected. If yes, would it be better to place the button somewhere else because it's now not "that" related to the project name as before.

Also, should "Create Folder" use a CheckBox instead of a CheckButton? Because the control does not have immediate effect (the folder is not immediately created).

**Comment by nathanfranke** [comment]
> When the project name is "Test" and "Create Folder" is on, project path is `/path/to/dir/Test`. If I then change the path to `/path/to/dir/DoesNotExist` and click "Create & Edit". It creates and uses the "DoesNotExist" folder for me.

This is the behavior I intended. Some users might want to make the directory name different from the project name (e.g. `Card Game` project name and `card-game` directory)

> It be better to place the button somewhere else because it's now not "that" related to the project name as before.

I agree that moving the button somewhere else would make sense, but the only other place I can think of would be below the name/path fields, taking more vertical space.

> Also, should "Create Folder" use a CheckBox instead of a CheckButton? Because the control does not have immediate effect (the folder is not immediately created).

I think a `CheckButton` works better because the button immediately changes the path field.

>     * What the "Create Folder" button does was clear: Create a folder with the project name at the current project path, and use that folder as the new project path.
> 
>     * The "Create Folder" toggle is confusing:
>       
>       * When toggled off: It strips the last component from project path no matter if it's the same as project name.
>         
>         1. Turn on
>         2. Set the project path to `/path/to/something/you/typed/later`
>         3. Turn off
>         4. And it strips `/later`
>       * When toggled on: It appends the project name to the project path, even when the current path does not exist.
>         
>         1. Set the project path to `/path/that/does/not/exist`
>         2. Turn on
>         3. The project path becomes `/path/that/does/not/exist/ProjectName`
>         4. It still reports error because the parent directory does not exist (and won't be created).
>       * When "Create & Edit" is pressed: create the project folder if missing when the toggle is on.

I tried my best to make it intuitive and straightforward for most use-cases. Although if you have any improvement suggestions I would greatly appreciate it!

I've already considered changing the text on the button, but I couldn't decide on what to change it to.

**Comment by LightningAA** [comment]
> I agree that moving the button somewhere else would make sense, but the only other place I can think of would be below the name/path fields, taking more vertical space.

It could go on the right side of an hbox with the "Project Path:" label.

**Comment by nathanfranke** [comment]
:tada: 
image

**Comment by Calinou** [comment]
@nathanfranke Thanks for adding this :slightly_smiling_face: 

Does it prevent creating the project? It should, as users should never be able to brick Godot entirely.

**Comment by nathanfranke** [comment]
> Does it prevent creating the project?

Yes

How do I get the home directory?

**Comment by Calinou** [comment]
> How do I get the home directory?

Probably like this:

```cpp
#ifdef WINDOWS_ENABLED
	const String home_dir = OS::get_singleton()->get_environment("USERPROFILE")
#else
	const String home_dir = OS::get_singleton()->get_environment("HOME")
#endif
```

See also https://github.com/godotengine/godot/blob/1e553e34fbc74e16fbecc59406c97e3a0f4a5698/editor/editor_settings.cpp#L472.

**Comment by nathanfranke** [comment]
This is working great on my end and ready for review. Behavior is intuitive for me for every edge case, with the exception of one: Typing the project name as `..` will put that same text `..` in the path, which will almost definitely cause oddities. I traced the issue back to `OS.get_safe_dir_name` and made a PR to fix that behavior: https://github.com/godotengine/godot/pull/65755

**To rephrase**, this PR is complete, but PR https://github.com/godotengine/godot/pull/65755 should be merged first, and this PR retested, **before** this PR should be merged!

**Comment by nathanfranke** [comment]
This is ready for 4.1 if desired

File: editor/project_manager.cpp [hunk 1]
```diff
@@ -111,237 +112,247 @@ class ProjectDialog : public ConfirmationDialog {
 	AcceptDialog *dialog_error;
 	String fav_dir;
 
-	String created_folder_path;
-
-	void set_message(const String &p_msg, MessageType p_type = MESSAGE_SUCCESS, InputType input_type = PROJECT_PATH) {
+	void set_message(const String &p_msg, MessageType p_type, InputType input_type = PROJECT_PATH) {
```
Comment (KoBeWi) [inline editor/project_manager.cpp:115]:
```suggestion
	void set_message(const String &p_msg, MessageType p_type, InputType p_input_type = PROJECT_PATH) {
```

**Comment by KoBeWi** [comment]
Ok I found another bug xd
When you clear the project path completely, the Create button does not get disabled and there is no error/warning. I created the project out of curiosity and the project manager crashed and my Godot got "bricked". I managed to find the project in the executable folder, but it's not very intuitive. I think relative paths should not be allowed.

File: editor/project_manager.cpp [hunk 2]
```diff
@@ -494,6 +510,11 @@ class ProjectDialog : public ConfirmationDialog {
 
 			} else {
 				if (mode == MODE_NEW) {
+					if (create_dir->is_pressed()) {
+						Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+						d->make_dir(project_path->get_text());
```
Comment (KoBeWi) [inline editor/project_manager.cpp:515]: So this is what I mentioned in my first comment. The folder shouldn't be created here, because the function may return later.

File: editor/project_manager.cpp [hunk 3]
```diff
@@ -550,7 +572,12 @@ class ProjectDialog : public ConfirmationDialog {
 						EditorVCSInterface::create_vcs_metadata_files(EditorVCSInterface::VCSMetadata(vcs_metadata_selection->get_selected()), dir);
 					}
 				} else if (mode == MODE_INSTALL) {
-					if (project_path->get_text().ends_with(".zip")) {
+					if (create_dir->is_pressed()) {
+						Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
+						d->make_dir(install_path->get_text());
```
Comment (KoBeWi) [inline editor/project_manager.cpp:577]: Same here.

File: editor/project_manager.cpp [hunk 4]
```diff
@@ -659,39 +686,10 @@ class ProjectDialog : public ConfirmationDialog {
...
-		if (!created_folder_path.is_empty()) {
-			Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
-			d->remove(created_folder_path);
-
-			create_dir->set_disabled(false);
-			created_folder_path = "";
-		}
-	}
-
 	void cancel_pressed() override {
```
Comment (KoBeWi) [inline editor/project_manager.cpp:689]: This function doesn't seem to be called anywhere 🤔
Also it's probably redundant, because simply closing the dialog seems to achieve the same.

Comment (nathanfranke) [reply editor/project_manager.cpp]: It's an override and it does get called, but I removed it anyways

File: editor/editor_settings.cpp [hunk 5]
```diff
@@ -747,14 +747,16 @@ void EditorSettings::_load_defaults(Ref<ConfigFile> p_extra_config) {
...
 	// Web platform only supports `gl_compatibility`.
-	EDITOR_SETTING(Variant::STRING, PROPERTY_HINT_NONE, "project_manager/default_renderer", "gl_compatibility", "forward_plus,mobile,gl_compatibility")
+	EDITOR_SETTING(Variant::STRING, PROPERTY_HINT_ENUM, "project_manager/default_renderer", "gl_compatibility", "forward_plus,mobile,gl_compatibility")
 #elif defined(ANDROID_ENABLED)
 	// Use more suitable rendering method by default.
-	EDITOR_SETTING(Variant::STRING, PROPERTY_HINT_NONE, "project_manager/default_renderer", "mobile", "forward_plus,mobile,gl_compatibility")
+	EDITOR_SETTING(Variant::STRING, PROPERTY_HINT_ENUM, "project_manager/default_renderer", "mobile", "forward_plus,mobile,gl_compatibility")
 #else
-	EDITOR_SETTING(Variant::STRING, PROPERTY_HINT_NONE, "project_manager/default_renderer", "forward_plus", "forward_plus,mobile,gl_compatibility")
+	EDITOR_SETTING(Variant::STRING, PROPERTY_HINT_ENUM, "project_manager/default_renderer", "forward_plus", "forward_plus,mobile,gl_compatibility")
```
Comment (nathanfranke) [inline editor/editor_settings.cpp:759]: renderer setting changes are unrelated but works as intended now

File: editor/project_manager.cpp [hunk 6]
```diff
@@ -109,245 +110,283 @@ class ProjectDialog : public ConfirmationDialog {
...
+#ifdef WINDOWS_ENABLED
+			const String home_dir = OS::get_singleton()->get_environment("USERPROFILE");
+#else
+			const String home_dir = OS::get_singleton()->get_environment("HOME");
+#endif
+
+			if (target_path == home_dir || target_path == OS::get_singleton()->get_system_dir(OS::SYSTEM_DIR_DOCUMENTS)) {
+				set_message(TTR("You cannot save a project in the selected path. Please make a new folder or choose a new path."), MESSAGE_ERROR, target_path_type);
+				return "";
+			}
```
Comment (nathanfranke) [inline editor/project_manager.cpp:247]: First check: Disallow working directory and executable directory
Second check: Disallow home dir (env USERPROFILE or HOME) and documents dir

File: editor/project_manager.cpp [hunk 7]
```diff
@@ -109,245 +110,283 @@ class ProjectDialog : public ConfirmationDialog {
...
+			case 4: // PascalCase
+				name = name.to_pascal_case();
+				break;
+			case 5: // Title Case
+				name = name.capitalize();
+				break;
+			default:
+				ERR_FAIL_V_MSG("", "Invalid directory naming convention.");
+				break;
+		}
```
Comment (nathanfranke) [inline editor/project_manager.cpp:344]: Open to better ideas

Also, right now project name `test3` has path `test-3` which I don't really like

**Comment by nathanfranke** [comment]
Rebased and working :) Should be moved to 4.3 milestone.

`test5` still suggests `test-5`.

File: editor/project_manager.cpp (hunk 7 above)
Comment (nathanfranke) [reply editor/project_manager.cpp]: Still not totally satisfied with this. `kebab-case` as a default makes sense though, e.g. `godot-proposals`.

File: doc/classes/EditorSettings.xml [hunk 8]
```diff
@@ -714,6 +714,9 @@
 		<member name="project_manager/default_renderer" type="String" setter="" getter="">
 			The renderer type that will be checked off by default when creating a new project. Accepted strings are "forward_plus", "mobile" or "gl_compatibility".
 		</member>
+		<member name="project_manager/directory_naming_convention" type="int" setter="" getter="">
+			Directory naming convention for project manager. Options are "None", "kebab-case", "snake_case", "camelCase", "PascalCase", or "Title Case".
```
Comment (KoBeWi) [inline doc/classes/EditorSettings.xml:718]: I think None should be explained, as it's less obvious.

File: editor/project_manager.cpp [hunk 9]
```diff
@@ -51,7 +51,8 @@
 #include "editor/plugins/asset_library_editor_plugin.h"
 #include "main/main.h"
 #include "scene/gui/center_container.h"
-#include "scene/gui/check_box.h"
+//#include "scene/gui/check_box.h"
```
Comment (KoBeWi) [inline editor/project_manager.cpp:54]:
```suggestion
```

**Comment by KoBeWi** [comment]
I think the validation code should use EditorValidationPanel.

File: editor/project_manager.h [hunk 10]
```diff
@@ -37,7 +37,8 @@
 #include "scene/gui/file_dialog.h"
 #include "scene/gui/scroll_container.h"
 
-class CheckBox;
+//class CheckBox;
```
Comment (KoBeWi) [inline editor/project_manager.h:40]:
```suggestion
```

File: editor/project_manager.h [hunk 11]
```diff
@@ -93,42 +94,41 @@ class ProjectDialog : public ConfirmationDialog {
...
+	void _install_path_changed(const String &p_text);
 	void _path_selected(const String &p_path);
 	void _file_selected(const String &p_path);
 	void _install_path_selected(const String &p_path);
 
-	void _browse_path();
+	void _browse_project_path();
 	void _browse_install_path();
-	void _create_folder();
+	void _create_folder_toggled(const bool p_pressed);
```
Comment (KoBeWi) [inline editor/project_manager.h:117]:
```suggestion
	void _create_folder_toggled(bool p_pressed);
```
Don't use `const` for primitive-type arguments.

File: editor/editor_settings.cpp [hunk 12]
```diff
@@ -784,6 +784,8 @@ void EditorSettings::_load_defaults(Ref<ConfigFile> p_extra_config) {
 	// TRANSLATORS: Project Manager here refers to the tool used to create/manage Godot projects.
 	EDITOR_SETTING(Variant::INT, PROPERTY_HINT_ENUM, "project_manager/sorting_order", 0, "Last Edited,Name,Path")
```
Comment (KoBeWi) [inline editor/editor_settings.cpp:786]:
```suggestion
```
No reason for separating it.

File: doc/classes/EditorSettings.xml (hunk 8 above)
Comment (zolrath) [reply doc/classes/EditorSettings.xml:718]: Does "None" imply that the project title becomes the directory, spaces and all?

"Unchanged" or "Literal" or something describing the behavior may be more immediately apparent.

Comment (KoBeWi) [reply doc/classes/EditorSettings.xml:718]: > Does "None" imply that the project title becomes the directory, spaces and all?

Yes, although it also replaces invalid characters.

File: editor/project_manager.cpp [hunk 13]
```diff
@@ -69,270 +70,302 @@ constexpr int GODOT4_CONFIG_VERSION = 5;
...
-				install_path_container->hide();
-				get_ok_button()->set_disabled(true);
+	String working_dir = d->get_current_dir();
+	String executable_dir = OS::get_singleton()->get_executable_path().get_base_dir();
+	if (target_path == working_dir || target_path == executable_dir) {
+		_set_message(TTR("Creating a project in the engine's working directory or executable directory is not allowed, as it would prevent the project manager from starting."), MESSAGE_ERROR, target_path_input_type);
+		return "";
+	}
+
+	// Get home dir proposal: https://github.com/godotengine/godot-proposals/issues/4851
```
Comment (KoBeWi) [inline editor/project_manager.cpp:183]: Why is this comment here?

**Comment by nathanfranke** [comment]
> I think the validation code should use EditorValidationPanel.

I agree, but I would want confirmation before implementing this.

File: editor/project_manager.cpp (hunk 13 above)
Comment (nathanfranke) [reply editor/project_manager.cpp:183]: It's a proposal that if completed would simplify the ~5 lines below.

Comment (KoBeWi) [reply editor/project_manager.cpp:183]: Right, but it's out of place. It can say "FIXME: This can be simplified if OS.get_home_dir() is implemented()." or something.

**Comment by KoBeWi** [comment]
I tried to make a PR for the validation rework but the code is too tangled 😬
Hopefully this PR will make it easier to modify.

File: doc/classes/EditorSettings.xml (hunk 8 above)
Comment (nathanfranke) [reply doc/classes/EditorSettings.xml:718]: Changed to

> "None" (project name is directory name), "kebab-case" (default), ...

File: editor/project_manager.cpp [hunk 14]
```diff
@@ -669,77 +646,57 @@ void ProjectDialog::set_mode(Mode p_mode) {
...
 	// Workaround: for the file selection dialog content to be rendered we need to show its parent dialog.
 	show_dialog();
-	_set_message("");
-
-	_browse_path();
+	_browse_project_path();
 }
 
 void ProjectDialog::show_dialog() {
+	msg->hide(); // TODO: Workaround for https://github.com/godotengine/godot/issues/83546. Also check msg->show() at end of this function.
```
Comment (nathanfranke) [inline editor/project_manager.cpp:664]: https://github.com/godotengine/godot/issues/83546

File: editor/project_manager.cpp [hunk 15]
```diff
@@ -69,270 +70,303 @@ constexpr int GODOT4_CONFIG_VERSION = 5;
...
+		return "";
+	}
+
+	// TODO: The following 5 lines could be simplified if OS.get_user_home_dir() or SYSTEM_DIR_HOME is implemented.
+	// Proposal: https://github.com/godotengine/godot-proposals/issues/4851
+#ifdef WINDOWS_ENABLED
+	String home_dir = OS::get_singleton()->get_environment("USERPROFILE");
+#else
+	String home_dir = OS::get_singleton()->get_environment("HOME");
+#endif
```
Comment (nathanfranke) [inline editor/project_manager.cpp:189]: https://github.com/godotengine/godot-proposals/issues/4851

**Review by nathanfranke — COMMENTED** [review]
Two TODOs

File: editor/project_manager.cpp [hunk 16]
```diff
@@ -69,270 +70,303 @@ constexpr int GODOT4_CONFIG_VERSION = 5;
...
-				get_ok_button()->set_disabled(true);
+	String working_dir = d->get_current_dir();
+	String executable_dir = OS::get_singleton()->get_executable_path().get_base_dir();
+	if (target_path == working_dir || target_path == executable_dir) {
+		_set_message(TTR("Creating a project in the engine's working directory or executable directory is not allowed, as it would prevent the project manager from starting."), MESSAGE_ERROR, target_path_input_type);
+		return "";
+	}
+
+	// TODO: The following 5 lines could be simplified if OS.get_user_home_dir() or SYSTEM_DIR_HOME is implemented.
+	// Proposal: https://github.com/godotengine/godot-proposals/issues/4851
```
Comment (KoBeWi) [inline editor/project_manager.cpp:184]: TODO comment is ok, proposal link is out of place IMO.

File: editor/project_manager.h [hunk 17]
```diff
@@ -38,6 +38,7 @@
 #include "scene/gui/scroll_container.h"
 
 class CheckBox;
```
Comment (KoBeWi) [inline editor/project_manager.h:40]:
```suggestion
```
Unused (can be re-added after the CheckBox is uncommented).

File: editor/project_manager.cpp (hunk 14 above)
Comment (KoBeWi) [reply editor/project_manager.cpp:664]:
```suggestion
	msg->hide(); // TODO: Workaround for GH-83546. Also check msg->show() at end of this function.
```
This style is used more commonly. Also the comment should be FIXME probably.

**Review by KoBeWi — APPROVED** [review]
The code is somewhat difficult to review due to amount of changes, but I did some testing and overall it works correctly.

File: editor/project_manager.cpp [hunk 18]
```diff
@@ -69,270 +70,303 @@ constexpr int GODOT4_CONFIG_VERSION = 5;
...
+			// The path is not necessarily empty here, but we will update the message later if it isn't.
+			_set_message(TTR("The project folder exists and is empty."), MESSAGE_SUCCESS, target_path_input_type);
+		}
+
+		if (d->change_dir(target_path) == OK) {
+			// Check if the directory is empty. Not an error, but we want to warn the user.
+			d->list_dir_begin();
+			String n = d->get_next();
+			while (!n.is_empty()) {
+				if (!n.begins_with(".")) {
```
Comment (AThousandShips) [inline editor/project_manager.cpp:236]:
```suggestion
				if (n[0] != '.') {
```
Known to be non-empty so can use faster check

File: editor/project_manager.cpp [hunk 19]
```diff
@@ -427,233 +446,191 @@ void ProjectDialog::_renderer_selected() {
...
-					}
+		unzFile pkg = unzOpen2(zip_path.utf8().get_data(), &io);
+		if (!pkg) {
+			_set_message(TTR("Error opening package file, not in ZIP format."), MESSAGE_ERROR);
+			return;
+		}
 
-					ret = unzGoToNextFile(pkg);
-				}
+		// Find the zip_root
```
Comment (AThousandShips) [inline editor/project_manager.cpp:541]:
```suggestion
		// Find the zip_root.
```
Per the [comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide).

File: editor/project_manager.cpp [hunk 20]
```diff
@@ -427,233 +446,191 @@ void ProjectDialog::_renderer_selected() {
...
-						Ref<FileAccess> f = FileAccess::open(dir.path_join(rel_path), FileAccess::WRITE);
-						if (f.is_valid()) {
-							f->store_buffer(uncomp_data.ptr(), uncomp_data.size());
-						} else {
-							failed_files.push_back(rel_path);
-						}
-					}
+		Vector<String> failed_files;
+		while (ret == UNZ_OK) {
+			//get filename
```
Comment (AThousandShips) [inline editor/project_manager.cpp:562]:
```suggestion
			// Get filename.
```

**Review by AThousandShips — APPROVED** [review]
Looks good otherwise

File: editor/project_manager.cpp (hunk 14 above)
Comment (nathanfranke) [reply editor/project_manager.cpp:664]: Changed to:
```cpp
msg->set_custom_minimum_size(Size2(500, 0) * EDSCALE); // HACK: This fixes window size with autowrap label. See: https://github.com/godotengine/godot/issues/80218#issuecomment-1669527304
```

File: editor/project_manager.cpp (hunk 16 above)
Comment (nathanfranke) [reply editor/project_manager.cpp:184]: Changed to:
```cpp
// TODO: The following 5 lines could be simplified if OS.get_user_home_dir() or SYSTEM_DIR_HOME is implemented. See: https://github.com/godotengine/godot-proposals/issues/4851.
```

File: editor/project_manager.cpp [hunk 21]
```diff
@@ -663,123 +645,102 @@ void ProjectDialog::set_mode(Mode p_mode) {
...
 		} else {
 			Ref<DirAccess> d = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
 			project_path->set_text(d->get_current_dir());
-			fdialog->set_current_dir(d->get_current_dir());
-		}
-
-		if (project_name->get_text().is_empty()) {
-			String proj = TTR("New Game Project");
-			project_name->set_text(proj);
-			_text_changed(proj);
```
Comment (nathanfranke) [inline editor/project_manager.cpp:728]: Cannot reproduce https://github.com/godotengine/godot/issues/83605

File: editor/project_manager.cpp [hunk 22]
```diff
@@ -69,264 +70,302 @@ constexpr int GODOT4_CONFIG_VERSION = 5;
...
+		install_path->grab_focus();
 	} else {
-		get_ok_button()->call_deferred(SNAME("grab_focus"));
+		get_ok_button()->grab_focus();
 	}
 }
 
 void ProjectDialog::_path_selected(const String &p_path) {
-	// If not already shown.
-	show_dialog();
```
Comment (nathanfranke) [inline editor/project_manager.cpp:313]: Did this instead, and everything still works.

**Review by nathanfranke — COMMENTED** [review]
Rebased to 4.2.1

File: editor/project_manager.cpp (hunk 14 above)
Comment (nathanfranke) [reply editor/project_manager.cpp]: Now it is:

```gdscript
msg->set_anchors_and_offsets_preset(Control::LayoutPreset::PRESET_TOP_WIDE); // TODO: Work around enormous popup height. See: https://github.com/godotengine/godot/issues/83546
```

File: doc/classes/EditorSettings.xml (hunk 8 above)
Comment (nathanfranke) [reply doc/classes/EditorSettings.xml]: I also changed "None" to "No convention"

File: editor/project_manager.cpp [hunk 23]
```diff
@@ -663,123 +645,102 @@ void ProjectDialog::set_mode(Mode p_mode) {
...
 
 void ProjectDialog::show_dialog() {
+	// Set minimum sizes based on max autowrap line count. Label must be inside tree first.
 	if (mode == MODE_RENAME) {
+		msg->set_text("\n"); // One line
+	} else {
+		msg->set_text("\n\n"); // Two lines
+	}
+	msg->set_custom_minimum_size(msg->get_minimum_size());
+
```
Comment (nathanfranke) [inline editor/project_manager.cpp:670]: This ensures label never expands the window, but is hard coded...

image

Comment (YuriSizov) [reply editor/project_manager.cpp:670]: The message already has a minimum size limit to prevent the dialog from misbehaving. This should not be done, it only introduces instability.

File: editor/project_manager.h [hunk 24]
```diff
@@ -93,42 +93,41 @@ class ProjectDialog : public ConfirmationDialog {
...
 	String zip_title;
-	String fav_dir;
 
-	String created_folder_path;
+	void _set_message(const String &p_msg, MessageType p_type = MESSAGE_SUCCESS, InputType p_input_type = PROJECT_PATH);
+
+	String _validate_path();
 
-	void _set_message(const String &p_msg, MessageType p_type = MESSAGE_SUCCESS, InputType input_type = PROJECT_PATH);
+	String _last_target_auto_dir;
```
Comment (AThousandShips) [inline editor/project_manager.h:104]: I'd keep this along with the other variables, also let's keep the naming consistent and remove the `_`, this file doesn't use that for member variables (even though some files do)

**Review by AThousandShips — COMMENTED** [review]
Just a minor nit

File: editor/project_manager.cpp [hunk 25]
```diff
@@ -862,7 +828,8 @@ ProjectDialog::ProjectDialog() {
 
 	msg = memnew(Label);
 	msg->set_horizontal_alignment(HORIZONTAL_ALIGNMENT_CENTER);
-	msg->set_custom_minimum_size(Size2(200, 0) * EDSCALE);
+	msg->set_autowrap_mode(TextServer::AUTOWRAP_WORD_SMART);
+	msg->set_anchors_and_offsets_preset(Control::LayoutPreset::PRESET_TOP_WIDE); // TODO: Work around enormous popup height. See: https://github.com/godotengine/godot/issues/83546
```
Comment (YuriSizov) [inline editor/project_manager.cpp:832]: And this should not be done either.

File: editor/project_manager.cpp (hunk 23 above)
Comment (nathanfranke) [reply editor/project_manager.cpp:670]: Is it okay that window is forced to resize when the initial 1 line turns into 2 lines.

Comment (YuriSizov) [reply editor/project_manager.cpp:670]: Why would we not want it to resize is the label now takes more space?

**Comment by YuriSizov** [comment]
> The code is somewhat difficult to review due to amount of changes, but I did some testing and overall it works correctly.

I second KoBeWi's concerns here, by the way. I have yet to look into this PR in detail, but why exactly the changes are so extensive for such an isolated feature? Can the changeset be reduced somehow?

Full disclosure, I need to work on the project manager, and this PR is going to get in the way. So I either have to accept it or ignore it. Making sure this PR doesn't exceed its own scope would be a great help.

**Comment by nathanfranke** [comment]
I am reworking this to reduce the changes, will take a few days.

**Comment by YuriSizov** [comment]
> I am reworking this to reduce the changes, will take a few days.

Thanks, I appreciate it! I took a look over the weekend and I think it all pretty much makes sense and at least changes are isolated to one class, for the most part. Renames for clarity are also very nice to have. So at a glance I'm not sure what specifically can be simplified, but an attempt at that is very much welcome.

KoBeWi mentioned that perhaps the folder naming scheme feature can be cut, and I agree that it is probably not very necessary, but since it's already implemented then it makes sense to keep it.

File: doc/classes/EditorSettings.xml [hunk 26]
```diff
@@ -714,6 +714,9 @@
 		<member name="project_manager/default_renderer" type="String" setter="" getter="">
 			The renderer type that will be checked off by default when creating a new project. Accepted strings are "forward_plus", "mobile" or "gl_compatibility".
 		</member>
+		<member name="project_manager/directory_naming_convention" type="int" setter="" getter="">
+			Directory naming convention for project manager. Options are "No convention" (project name is directory name), "kebab-case" (default), "snake_case", "camelCase", "PascalCase", or "Title Case".
```
Comment (YuriSizov) [inline doc/classes/EditorSettings.xml:718]:
```suggestion
			Directory naming convention for the project manager. Options are "No convention" (project name is directory name), "kebab-case" (default), "snake_case", "camelCase", "PascalCase", or "Title Case".
```

File: editor/project_manager.cpp (hunk 6 above)
Comment (Zachary-Rude) [reply editor/project_manager.cpp]: why are you disallowing the documents folder?!

**Comment by akien-mga** [comment]
This can be rebased / redone after #87266.

File: doc/classes/EditorSettings.xml [hunk 27]
```diff
@@ -880,6 +880,9 @@
 		<member name="project_manager/default_renderer" type="String" setter="" getter="">
 			The renderer type that will be checked off by default when creating a new project. Accepted strings are "forward_plus", "mobile" or "gl_compatibility".
 		</member>
+		<member name="project_manager/directory_naming_convention" type="int" setter="" getter="">
+			Directory naming convention for the project manager. Options are "No convention" (project name is directory name), "kebab-case" (default), "snake_case", "camelCase", "PascalCase", or "Title Case".
```
[the remark this answers is not in the document]
Comment (nathanfranke) [reply doc/classes/EditorSettings.xml:884]: Right now, the default is kebab-case and it replaces underscores: **`t e_s-t` → `t-e-s-t`**
It would probably be better to keep underscores instead: **`t e_s-t` → `t-e_s-t`**

Could be implemented like this: `dir_name = project_name.to_lower().replace(" ", "-")`

**Comment by nathanfranke** [comment]
Thanks for the patience, rebased and ready.

File: doc/classes/EditorSettings.xml (hunk 27 above)
[the remark this answers is not in the document]
Comment (nathanfranke) [reply doc/classes/EditorSettings.xml:887]: The default (kebab-case) is now implemented as `to_lower().replace(" ", "-")`. So underscores are preserved: **`t e_s-t` → `t-e_s-t`**

File: editor/project_manager/project_dialog.h [hunk 28]
```diff
@@ -65,67 +66,76 @@ class ProjectDialog : public ConfirmationDialog {
...
-	Button *create_dir = nullptr;
-	VBoxContainer *name_container = nullptr;
-	VBoxContainer *path_container = nullptr;
-	VBoxContainer *install_path_container = nullptr;
+	Container *name_container = nullptr;
+	Container *project_path_container = nullptr;
+	Container *install_path_container = nullptr;
 
-	VBoxContainer *renderer_container = nullptr;
+	Container *renderer_container = nullptr;
```
Comment (akien-mga) [inline editor/project_manager/project_dialog.h:76]: Why were those changes to non-specific container types? They still seem to have only either `HBoxContainer` or `VBoxContainer` assigned.

**Review by akien-mga — APPROVED** [review]
Tested locally, looks pretty good! It's a great usability improvement, I really disliked how this worked until now.

The code changes are pretty hard to review in depth, for future PRs please try to keep refactoring separate from feature work. There's a lot of changes here which are just moving things around or slightly improving code quality which make the functional changes challenging to review. But overall it seems ok to me.

File: editor/project_manager/project_dialog.cpp [hunk 29]
```diff
@@ -957,20 +956,20 @@ ProjectDialog::ProjectDialog() {
...
 	add_child(fdialog_install);
 
-	project_name->connect("text_changed", callable_mp(this, &ProjectDialog::_text_changed));
-	project_path->connect("text_changed", callable_mp(this, &ProjectDialog::_path_text_changed));
-	install_path->connect("text_changed", callable_mp(this, &ProjectDialog::_update_path));
-	fdialog->connect("dir_selected", callable_mp(this, &ProjectDialog::_path_selected));
-	fdialog->connect("file_selected", callable_mp(this, &ProjectDialog::_file_selected));
+	project_name->connect("text_changed", callable_mp(this, &ProjectDialog::_project_name_changed));
+	project_path->connect("text_changed", callable_mp(this, &ProjectDialog::_project_path_changed));
+	install_path->connect("text_changed", callable_mp(this, &ProjectDialog::_install_path_changed));
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.cpp:970]:
```suggestion
	install_path->connect("text_changed", callable_mp(this, &ProjectDialog::_install_path_changed).unbind(1));
```

File: editor/project_manager/project_dialog.h [hunk 30]
```diff
@@ -65,67 +66,76 @@ class ProjectDialog : public ConfirmationDialog {
...
+	void _update_target_auto_dir();
 
-	void _browse_path();
+	// While `create_dir` is disabled, stores the last target path dir name, or an empty string if equal to `auto_dir`.
+	String last_custom_target_dir;
+	void _create_dir_toggled(bool p_pressed);
+
+	void _project_name_changed(const String &p_text);
+	void _project_path_changed(const String &p_text);
+	void _install_path_changed(const String &p_text);
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.h:117]:
```suggestion
	void _install_path_changed();
```

File: editor/project_manager/project_dialog.cpp [hunk 31]
```diff
@@ -41,349 +41,382 @@
...
-	callable_mp((Control *)get_ok_button(), &Control::grab_focus).call_deferred();
+	_validate_path();
 }
 
-void ProjectDialog::_install_path_selected(const String &p_path) {
-	String sp = p_path.simplify_path();
-	install_path->set_text(sp);
-	_update_path(sp);
-	callable_mp((Control *)get_ok_button(), &Control::grab_focus).call_deferred();
+void ProjectDialog::_install_path_changed(const String &p_text) {
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.cpp:347]:
```suggestion
void ProjectDialog::_install_path_changed() {
```

File: editor/project_manager/project_dialog.cpp [hunk 32]
```diff
@@ -957,20 +956,20 @@ ProjectDialog::ProjectDialog() {
...
-	add_child(fdialog);
+	add_child(fdialog_project);
 	add_child(fdialog_install);
 
-	project_name->connect("text_changed", callable_mp(this, &ProjectDialog::_text_changed));
-	project_path->connect("text_changed", callable_mp(this, &ProjectDialog::_path_text_changed));
-	install_path->connect("text_changed", callable_mp(this, &ProjectDialog::_update_path));
-	fdialog->connect("dir_selected", callable_mp(this, &ProjectDialog::_path_selected));
-	fdialog->connect("file_selected", callable_mp(this, &ProjectDialog::_file_selected));
+	project_name->connect("text_changed", callable_mp(this, &ProjectDialog::_project_name_changed));
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.cpp:968]:
```suggestion
	project_name->connect("text_changed", callable_mp(this, &ProjectDialog::_project_name_changed).unbind(1));
```

File: editor/project_manager/project_dialog.h [hunk 33]
```diff
@@ -65,67 +66,76 @@ class ProjectDialog : public ConfirmationDialog {
...
+
+	// Updates `auto_dir`. If the target path dir name is equal to `auto_dir` (the default state), the target path is also updated.
+	void _update_target_auto_dir();
 
-	void _browse_path();
+	// While `create_dir` is disabled, stores the last target path dir name, or an empty string if equal to `auto_dir`.
+	String last_custom_target_dir;
+	void _create_dir_toggled(bool p_pressed);
+
+	void _project_name_changed(const String &p_text);
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.h:115]:
```suggestion
	void _project_name_changed();
```

File: editor/project_manager/project_dialog.cpp [hunk 34]
```diff
@@ -41,349 +41,382 @@
...
-	_update_path(sp);
-	if (p.ends_with(".zip")) {
-		callable_mp((Control *)install_path, &Control::grab_focus).call_deferred();
-	} else {
-		callable_mp((Control *)get_ok_button(), &Control::grab_focus).call_deferred();
+	_set_target_path(target_path);
+	_validate_path();
+}
+
+void ProjectDialog::_project_name_changed(const String &p_text) {
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.cpp:331]:
```suggestion
void ProjectDialog::_project_name_changed(
) {
```

File: editor/project_manager/project_dialog.cpp [hunk 35]
```diff
@@ -957,20 +956,20 @@ ProjectDialog::ProjectDialog() {
...
+	add_child(fdialog_project);
 	add_child(fdialog_install);
 
-	project_name->connect("text_changed", callable_mp(this, &ProjectDialog::_text_changed));
-	project_path->connect("text_changed", callable_mp(this, &ProjectDialog::_path_text_changed));
-	install_path->connect("text_changed", callable_mp(this, &ProjectDialog::_update_path));
-	fdialog->connect("dir_selected", callable_mp(this, &ProjectDialog::_path_selected));
-	fdialog->connect("file_selected", callable_mp(this, &ProjectDialog::_file_selected));
+	project_name->connect("text_changed", callable_mp(this, &ProjectDialog::_project_name_changed));
+	project_path->connect("text_changed", callable_mp(this, &ProjectDialog::_project_path_changed));
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.cpp:969]:
```suggestion
	project_path->connect("text_changed", callable_mp(this, &ProjectDialog::_project_path_changed).unbind(1));
```

File: editor/project_manager/project_dialog.h [hunk 36]
```diff
@@ -65,67 +66,76 @@ class ProjectDialog : public ConfirmationDialog {
...
+	void _project_path_changed(const String &p_text);
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.h:116]:
```suggestion
	void _project_path_changed();
```

File: editor/project_manager/project_dialog.cpp [hunk 37]
```diff
@@ -41,349 +41,382 @@
...
+		_update_target_auto_dir();
 	}
+
+	_validate_path();
 }
 
-void ProjectDialog::_path_selected(const String &p_path) {
-	// If not already shown.
-	show_dialog();
+void ProjectDialog::_project_path_changed(const String &p_text) {
```
Comment (AThousandShips) [inline editor/project_manager/project_dialog.cpp:339]:
```suggestion
void ProjectDialog::_project_path_changed() {
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by allenwp** [comment]
It seems that this PR introduced a usability issue described in #94081.
