### PR TITLE
Fix for documentation not appearing in preview in editor inspector

### LINKED ISSUE #69004: Documentation not appearing in preview in editor inspector
### Godot version

4.0 (e3a51e5)

### System information

Fedora 37 x86_64

### Issue description

If you have documentation of subresources that extended the resource class from your script, they would not be shown in the preview mode of the editor inspector.

See image:
image

### Steps to reproduce

1- Add docstrings to a property or method  in a custom resource you create.
2- On a different node, `NodeB`, add an exported property with the type of the custom resource you created
3- Instantiate `NodeB` anywhere
4- Select the instance just instantiated
5- Hover on the exported property which you added the docstring.
Expected behavior: docstring should appear
Actual behavior: The default "no description" is displayed.

### Minimal reproduction project

[minimum_repro_doc_not_showing.zip](https://github.com/godotengine/godot/files/10068302/minimum_repro_doc_not_showing.zip)

### PR DESCRIPTION
**Pull request by brunosxs**
Fixes #69004 .
If you had documentation of subresources that extended the resource class from your script, they would not be shown.
See video:
[without_fix.webm](https://user-images.githubusercontent.com/1557903/202931873-00804daf-23a3-49a9-ba69-789b793a0e59.webm)

Fix:
[with_fix.webm](https://user-images.githubusercontent.com/1557903/202931930-b2778eec-2a5e-47bb-9561-3ffdca2db58f.webm)

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -3114,7 +3114,24 @@ void EditorInspector::update_tree() {
 			// Build the doc hint, to use as tooltip.
 
 			// Get the class name.
-			StringName classname = doc_name == "" ? object->get_class_name() : doc_name;
+			StringName classname = doc_name;
+			if (classname == "") {
+				if (Object::cast_to<Resource>(object) && object->get_script()) {
+					Resource *res = cast_to<Resource>(object);
```
Comment (anvilfolk) [inline editor/editor_inspector.cpp:3120]: If `cast_to<>()` is the same as `Object::cast_to<>()`, you can pull `Resource *res = cast_to<Resource>(object);` outside the `if`, right?

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -3114,7 +3114,24 @@ void EditorInspector::update_tree() {
...
+					if (res) {
```
Comment (anvilfolk) [inline editor/editor_inspector.cpp:3121]: Can this ever be false? To get inside `if (Object::cast_to<Resource>(object) && object->get_script()) {`, there had to have been a successful cast into `Resource`, so `res` can never be `nullptr`.

Looks like the ifs should be reorganized a little bit?

```
if (classname == "") {
  Resource *res = cast_to<Resource>(object);
  if (res) {
    Script *src = cast_to<Script>(res->get_script());
    if (src) { ... } else { ... }
```

Something like this?

File: editor/editor_inspector.cpp [hunk 3]
```diff
@@ -3114,7 +3114,24 @@ void EditorInspector::update_tree() {
...
+						Script *src = cast_to<Script>(res->get_script());
+						if (src) {
+							// If it is a resource and has a script, grab its script to get the script class.
+							classname = EditorNode::get_editor_data().script_class_get_name(src->get_path());
+						} else {
+							classname = object->get_class_name();
```
Comment (anvilfolk) [inline editor/editor_inspector.cpp:3127]: Also, `classname = object->get_class_name();` can probably show up just after `if (classname == "")`, right? This way it defaults to that, unless `if (res)` and `if (scr)` are true, and you don't need any of the `else` clauses!

**Comment by anvilfolk** [comment]
Not very well versed in this part of the code, but the solution seems to work & make sense!

I think with a little cleanup it will be great! :)

File: editor/editor_inspector.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/editor_inspector.cpp:3120]: Btw it's a static method and should always be used as `Object::cast_to`. Relying on the fact that `this` happens to be an object to do a method call isn't a good practice here.

File: editor/editor_inspector.cpp (hunk 3 above)
Comment (brunosxs) [reply editor/editor_inspector.cpp:3127]: Indeed!

File: editor/editor_inspector.cpp (hunk 2 above)
Comment (brunosxs) [reply editor/editor_inspector.cpp]: After defaulting class_name to the object's class name, as you suggested, there is no more need for else conditions. Thanks.

**Comment by brunosxs** [comment]
Updated the PR based on the feedback given.

File: editor/editor_inspector.cpp [hunk 4]
```diff
@@ -3114,7 +3114,18 @@ void EditorInspector::update_tree() {
 			// Build the doc hint, to use as tooltip.
 
 			// Get the class name.
-			StringName classname = doc_name == "" ? object->get_class_name() : doc_name;
+			StringName classname = doc_name;
+			if (classname == "") {
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:3118]: This should be a `else if` after the two checks below. There's no point doing all this `classname` computation before two cases which may overwrite it anyway.

File: editor/editor_inspector.cpp [hunk 5]
```diff
@@ -3114,7 +3114,18 @@ void EditorInspector::update_tree() {
...
+				classname = object->get_class_name();
+				Resource *res = Object::cast_to<Resource>(object);
+				if (res && object->get_script()) {
+					Script *src = Object::cast_to<Script>(res->get_script());
+					if (src) {
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:3123]:
```suggestion
				if (res && res->get_script().is_valid()) {
```

Comment (brunosxs) [reply editor/editor_inspector.cpp:3123]: `res->get_script()`evaluates to a Variant, as such there is no `is_valid()`.
I looked at the sources and saw that variant has `Variant::is_null()` and it seems to me to apply to this particular situation.

**Comment by anvilfolk** [comment]
Looks wonderful to me :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by anvilfolk** [comment]
Wohoooo, congraaaaaaaaats!!! 🥇
