### PR TITLE
`CONNECT_APPEND_SOURCE_OBJECT` on signal emission

### LINKED ISSUE #13974: Make CONNECT_APPEND_SOURCE_OBJECT work with any signal
### Describe the project you are working on

-

### Describe the problem or limitation you are having in your project

There is a specific Connect Flag `CONNECT_APPEND_SOURCE_OBJECT`.
It's docs say the following:

> The source object is automatically bound when a [PackedScene](https://docs.godotengine.org/en/stable/classes/class_packedscene.html#class-packedscene) is instantiated. If this flag bit is enabled, the source object will be appended right after the original arguments of the signal.

I actually do not know what that first sentence means.

When I do the following:

`
area.Connect(Node.SignalName.TreeEntered, new Callable(this,OnAreaEnteredTree), (uint)ConnectFlags.AppendSourceObject)`, I receive an error when the signal is emitted that the Method `OnAreaEnteredTree` is not found, since it expects a no-argument method. Despite having `ConnectFlags.AppendSourceObject` supplied.

To "append the source object", we need to manually bind the object in a callable or in the case of C#, use a lambda and use the captured source object:  

```cs
public void OnAreaEnteredTree(Area3D arg) {
	activeAttacks.Add(arg);
}
public void OnAreaExitingTree(Area3D arg) {
	activeAttacks.Remove(arg);
}
[...]
area.TreeEntered += () => { OnAreaEnteredTree(area); }; // capture area and pass to the actual method
area.TreeExiting += () => { OnAreaExitingTree(area); };
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I would expect `ConnectFlags.AppendSourceObject` / `CONNECT_APPEND_SOURCE_OBJECT` to work in any context.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
func _ready() -> void:
    var node = Node.new()
    node.connect(
        "tree_entered",
        Callable(self,"_on_tree_entered"),
        Object.CONNECT_APPEND_SOURCE_OBJECT
    )


func _on_tree_entered(emitter: Object) -> void: #note the emitter arg, which is not part of original tree_entered signature
    print("tree_entered emitted by:", emitter)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

We can bind or capture the object in a lambda, but having an "official" way to do it would be great.

### Is there a reason why this should be core and not an add-on in the asset library?

The flag exists, but seems to have only one specific use case.

### LINKED ISSUE #114326: Duplicating a node adds an extra empty argument to signal.
### Tested versions

reproduceable in v4.5.1.stable.official[f62fdbde1], v4.6.beta2.official[551ce8d47]

### System information

Godot v4.6.beta2 - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 14 Nov 2025 06:54:20 +0000 on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7800 XT (RADV NAVI32) - AMD Ryzen 7 9700X 8-Core Processor (16 threads) - 30.45 GiB memory

### Issue description

Duplicating a node with a append source signal adds an extra empty argument to signal to its child, if the editor is closed before duplicating. 

This causes the signal to be called with 2 arguments where 1 is expected.

### Steps to reproduce

create control node as root
add control node named "Parent"
attach new empty script to "Parent"
add control node named "Child" as child to "Parent"
connect resize signal of "Child" to "Parent" using Advanced > Append Source
save project and close editor (without closing, the bug did not appear)
open project and duplicate "Parent"
rmb edit the resize signal for the duplicated "Child" (so child of Parent2)

### Minimal reproduction project (MRP)

[duplicate-signal-extra-arg.zip](https://github.com/user-attachments/files/24333638/duplicate-signal-extra-arg.zip)

### LINKED ISSUE #114660: Connecting to signal crashes the editor when `unbinds > 0` and `Append Source` is enabled
### Tested versions

v4.6.beta2.official [551ce8d47]

Not relevant for pre-4.6 versions as before #108741 it was not possible to at once:
- unbind some args,
- append source

using the Signals dock connection dialog.

### System information

Godot v4.6.beta2 - Windows 10 (build 19045) - Multi-window, 1 monitor - Direct3D 12 (Forward+) - dedicated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21923.11000) - AMD Ryzen 5 5600G with Radeon Graphics (12 threads) - 31.29 GiB memory

### Issue description

Connecting to a signal using the `Signals` dock dialog crashes the editor when at once:
- `unbinds > 0` (the signal needs to have at least one parameter to be able to set it),
- `Append Source` is checked.

Image

### Steps to reproduce

1. Add a Node, attach a script.
2. Using Signals dock try to connect to a non-parameterless signal (e.g. `child_entered_tree`).
3. In the connection dialog enable `Advanced` toggle, set `unbinds > 0`, enable `Append Source`.
4. Click `Connect`.

### Minimal reproduction project (MRP)

N/A, trivial to reproduce in any project.

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #114326.
Fixes #114660.

Resolves https://github.com/godotengine/godot-proposals/issues/13974.

Changes `CONNECT_APPEND_SOURCE_OBJECT` to append the source object on signal emission. Previously it was done only on PackedScene instantiation, which led to bugs/inconsistencies.

- `CONNECT_APPEND_SOURCE_OBJECT` did not work on runtime connections.
- On runtime, duplicating a Node with the source object/Node binded during the scene instantiation would not replace the binded source object with the newly duplicated one.
- The source object/Node binded during the scene instantiation might be tried to be saved in the scene file.
- etc.

---

`CONNECT_APPEND_SOURCE_OBJECT` originally was added/needed specifically only for the editor's signal connection dialog (#60143), was never implemented for using on runtime. Was added as `Object`'s connection flag for ease of storage. AFAICT it would make more sense back then to implement it internally in the connections dialog, and store as some kind of meta data for connections. 🤔 But since it was added to Object as an exposed connection flag, I think it should work consistently, even on runtime. This PR aims to make it work consistently, so no special handling is needed on scene instantiation, node duplication, etc. As long as the flag is stored/duplicated things should work as expected.

The implementation is inspired by pre-#63595 state, when binds from `Object.connect` were appended on signal emission as well.

---

Modified MRP from #114326 with the examples below: [duplicate-signal-extra-arg_v2.zip](https://github.com/user-attachments/files/24346447/duplicate-signal-extra-arg_v2.zip)

Before (v4.6.beta2.official [551ce8d47])|After (this PR)
-|-
Godot_v4 6-beta2_win64_wQKInKJUeV|Sw5Z8VevPJ
Godot_v4 6-beta2_win64_DhLwm8jbzi|2cM7n4ITyY
Godot_v4 6-beta2_win64_XJHynYXQjd<br>gB2eqbazlf|MeJntvXswE<br>NczvKU27Bc

Relevant part of `control.tscn` from #114326 MRP:

- Before (v4.6.beta2.official [551ce8d47]):
```
[connection signal="resized" from="Parent/Child" to="Parent" method="_on_child_resized" flags=18]
[connection signal="resized" from="Parent2/Child" to="Parent2" method="_on_child_resized" flags=18 binds= [Object(Control,"unique_name_in_owner":false,"process_mode":0,"process_priority":0,"process_physics_priority":0,"process_thread_group":0,"physics_interpolation_mode":2,"auto_translate_mode":0,"editor_description":"","visible":true,"modulate":Color(1, 1, 1, 1),"self_modulate":Color(1, 1, 1, 1),"show_behind_parent":false,"top_level":false,"clip_children":0,"light_mask":1,"visibility_layer":1,"z_index":0,"z_as_relative":true,"y_sort_enabled":false,"texture_filter":0,"texture_repeat":0,"material":null,"use_parent_material":false,"clip_contents":false,"custom_minimum_size":Vector2(0, 0),"layout_direction":0,"layout_mode":0,"anchors_preset":0,"anchor_left":0.0,"anchor_top":0.0,"anchor_right":0.0,"anchor_bottom":0.0,"offset_left":0.0,"offset_top":0.0,"offset_right":40.0,"offset_bottom":40.0,"grow_horizontal":1,"grow_vertical":1,"rotation":0.0,"scale":Vector2(1, 1),"pivot_offset":Vector2(0, 0),"pivot_offset_ratio":Vector2(0, 0),"size_flags_horizontal":1,"size_flags_vertical":1,"size_flags_stretch_ratio":1.0,"localize_numeral_system":true,"tooltip_text":"","tooltip_auto_translate_mode":0,"focus_neighbor_left":NodePath(""),"focus_neighbor_top":NodePath(""),"focus_neighbor_right":NodePath(""),"focus_neighbor_bottom":NodePath(""),"focus_next":NodePath(""),"focus_previous":NodePath(""),"focus_mode":0,"focus_behavior_recursive":0,"mouse_filter":0,"mouse_behavior_recursive":0,"mouse_force_pass_scroll_events":true,"mouse_default_cursor_shape":0,"shortcut_context":null,"accessibility_name":"","accessibility_description":"","accessibility_live":0,"accessibility_controls_nodes":Array[NodePath]([]),"accessibility_described_by_nodes":Array[NodePath]([]),"accessibility_labeled_by_nodes":Array[NodePath]([]),"accessibility_flow_to_nodes":Array[NodePath]([]),"theme":null,"theme_type_variation":&"","script":null)
]]
```
- After (this PR):
```
[connection signal="resized" from="Parent/Child" to="Parent" method="_on_child_resized" flags=18]
[connection signal="resized" from="Parent2/Child" to="Parent2" method="_on_child_resized" flags=18]
```

### CODE REVIEW

**Comment by kleonc** [comment]
cc @Rindbee (#60143)

**Review by Rindbee — APPROVED** [review]
Looks good to me!

**Comment by kleonc** [comment]
> `CONNECT_APPEND_SOURCE_OBJECT` is currently a flag primarily used for `PackedScene` and is somewhat redundant ~now~. It was originally intended to enhance the functionality of the connection dialog, ~but the ability to add extra parameters of type `NodePath` (`^"."`) now effectively replaces this functionality.~

I've moved handling `CONNECT_APPEND_SOURCE_OBJECT` to Object / removed special handling from PackedScene. PR description updated.

File: core/object/object.cpp [hunk 1]
```diff
@@ -1340,15 +1340,25 @@ Error Object::emit_signalp(const StringName &p_name, const Variant **p_args, int
...
 		const uint32_t &flags = slot_flags[i];
 
-		if (!callable.is_valid()) {
+		if (!callable_ptr->is_valid()) {
 			// Target might have been deleted during signal callback, this is expected and OK.
 			continue;
 		}
 
+		if (flags & CONNECT_APPEND_SOURCE_OBJECT) {
+			callable_with_source_object_binded = callable_ptr->bind(this);
```
Comment (Rindbee) [inline core/object/object.cpp]: Using `bind()` again (like a Russian nesting doll) will cancel the `source`'s emission (not the original arguments) if unbinding is enabled (`unbind > 0`).

Comment (kleonc) [reply core/object/object.cpp]: Indeed, I've even added tests with unbinding confirming such behavior:
```cpp
		object.connect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback0).unbind(1), Object::CONNECT_APPEND_SOURCE_OBJECT);
		object.emit_signal("my_custom_signal");
		CHECK_EQ(target.received_args, Vector<Variant>{});
		object.disconnect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback0));

		object.connect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback1).unbind(1), Object::CONNECT_APPEND_SOURCE_OBJECT);
		object.emit_signal("my_custom_signal", "emit_arg");
		CHECK_EQ(target.received_args, Vector<Variant>{ "emit_arg" });
		object.disconnect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback1));

		object.connect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback1).bind("bind_arg").unbind(1), Object::CONNECT_APPEND_SOURCE_OBJECT);
		object.emit_signal("my_custom_signal");
		CHECK_EQ(target.received_args, Vector<Variant>{ "bind_arg" });
		object.disconnect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback1));

		object.connect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback2).bind("bind_arg").unbind(1), Object::CONNECT_APPEND_SOURCE_OBJECT);
		object.emit_signal("my_custom_signal", "emit_arg");
		CHECK_EQ(target.received_args, Vector<Variant>{ "emit_arg", "bind_arg" });
		object.disconnect("my_custom_signal", callable_mp(&target, &SignalReceiver::callback2));
```

But you're right, it makes pretty much no sense for it to behave like that. For such behavior you can already use `object.signal.emit(callable.bind(object))`, the `CONNECT_APPEND_SOURCE_OBJECT` flag would be not needed for that.

So it makes sense for the `CONNECT_APPEND_SOURCE_OBJECT` to be appending regardless of the callable's unbinds, on the Object-level (not just hacked-in in the PackedScene etc.).
The docs will need to be clarified though, as you can see it wasn't obvious to me that's the expected behavior (even given it wasn't actually implemented in the Object).

---

Now I'm not sure about the implementation. cc @dalexeev in case you have some thoughts/sugestions regarding that.

- How to "skip the unbinds"? Could be done e.g. by injecting the source-binding past the last chain on unbinds, something like:
```gdscript
callable{.any_bind_unbind_combination()}{.last_bind(arg)}.unbind(last1).unbind(last2)
# to:
callable{.any_bind_unbind_combination()}{.last_bind(arg)}.bind(source).unbind(last1).unbind(last2)
```
Is there a simpler/better way? 🤔

- Performance-wise it makes more sense to append the source once in `connect`, not in `emit_signal` like currently done in this PR. But doing so in `connect` means the source would be somehow already included (e.g. binded) in the connected Callable, which would then require special handling in PackedScene (reverting the source-appending to not store such appended source) or `Node.duplicate` (retarget the source to new duplicated node) etc. Doing so in `emit_signal` means no special handling needed elsewhere as the correct source will be appended as long as the `CONNECT_APPEND_SOURCE_OBJECT` flag was stored/copied.

Comment (Rindbee) [reply core/object/object.cpp]: Because `bind()` and `unbind()` are like Russian nesting dolls. The parameters used in the signal definition are the outermost layer. 

So the initial implementation of #60143 involved appending the source object to the beginning of the receiving function's parameter list. The order in which the Russian nesting dolls are opened:

> [source] [signal parameters] [unbind] [bind arguments]

However, @reduz disagreed at the time. So the current order is...

> [signal parameters] [unbind] [source] [bind arguments]

Initially, it was also implemented in `Object`. However, if implemented in `Object`, it would be necessary to determine and undo the nested layer of `unbind()`, then `bind(source)` ~~(if considering user scripts, there are many levels of nesting, this doesn't seem sufficient to guarantee the position of the source)~~, and then wrap it back to `unbind()`. And it seems that `CONNECT_APPEND_SOURCE_OBJECT` is primarily used for connecting dialogs. That's why it is the way it is now.

The current order in this PR is...

> [signal parameters] [source] [unbind] [bind arguments]

This also seems to be the reason that prevented #60143 from being merged for a long time. 

Currently, the first order seems to be the easiest to implement.

Comment (kleonc) [reply core/object/object.cpp]: OK, should be fixed. I've also moved the `(source)` indicator between the unbinds/binds to better indicate the final arg order:
godot windows editor dev x86_64_RhC45l8YkV

File: core/object/object.cpp [hunk 2]
```diff
@@ -1352,6 +1355,31 @@ Error Object::emit_signalp(const StringName &p_name, const Variant **p_args, int
...
+					args_mem[j + 1] = p_args[j];
+				}
+
+				args = args_mem;
+				argc = p_argcount + 1;
+			} else {
+				// More args unbound than provided, call will fail.
+				// Since appended source is non-unbindable, the error
+				// about too many unbinds should be correct as is.
+			}
```
Comment (KoBeWi) [inline core/object/object.cpp:1380]: Is this branch only for the comment? 🙃

**Review by KoBeWi — APPROVED** [review]

File: core/object/object.cpp (hunk 2 above)
Comment (kleonc) [reply core/object/object.cpp:1380]: Yep. 🙂 I guess it could be moved before the `if` if that's preferred over an empty `else` block (the explanation itself why there's no error etc. in case `source_index < 0` I think is needed/helpful).

File: doc/classes/Object.xml [hunk 3]
```diff
@@ -1051,7 +1051,17 @@
...
+			[codeblock]
+				extends Object
+
+				signal test_signal
+
+				func test():
+					print(self) # Prints e.g. &lt;Object#35332818393&gt;
+					test_signal.connect(prints.unbind(1), CONNECT_APPEND_SOURCE_OBJECT)
+					test_signal.emit("emit_arg_1", "emit_arg_2") # Prints emit_arg_1 &lt;Object#35332818393&gt;
+			[/codeblock]
```
Comment (akien-mga) [inline doc/classes/Object.xml:1064]:
```suggestion
			[codeblock]
			extends Object

			signal test_signal

			func test():
				print(self) # Prints e.g. &lt;Object#35332818393&gt;
				test_signal.connect(prints.unbind(1), CONNECT_APPEND_SOURCE_OBJECT)
				test_signal.emit("emit_arg_1", "emit_arg_2") # Prints emit_arg_1 &lt;Object#35332818393&gt;
			[/codeblock]
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
