### PR TITLE
Replace `radians` range hint with `radians_as_degrees`

### LINKED ISSUE #73170: @export_range "radians" does not work as documentation suggests
### Godot version

v4.0.rc1, 4.1

### System information

Arch Linux

### Issue description

When using the `@export_range` annotation with the `"radians"` hint, the editor converts the property's value to and from degrees but it uses the range extents (and increment) without any conversion.

To illustrate this, consider the example from the docs: `@export_range(-3.14, 3.14, 0.001, "radians") var angle_radians`. The editor will clamp the value to `[-3.14..3.14] degrees`.

I don't think this behaviour is incorrect, strictly speaking. But it is in conflict with the documentation.

### Steps to reproduce

Add the example properties to a script:
```
extends Node
@export_range(-3.14, 3.14, 0.001, "radians") var angle_radians = PI
@export_range(-180, 180, 0.1, "radians") var angle_radians_but_range_degrees = PI
```
Edit the properties in the inspector and note that the values are clamped to the range extents as written, but the value is converted to degrees.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Deprecates the old syntax

Added compatibility details to the areas I can find that checks for the old tag, haven't attempted any auto-conversion internally or in relation to 3.x, and couldn't find any references to it in mono

If there are any areas that depend on the original syntax I think they can be solved at a later time as it is not pressing

Also renamed the member variable in the editor property classes to make it clear what they do and align with the annotation

As per https://github.com/godotengine/godot/issues/73170#issuecomment-1732317295 and RocketChat

* Fixes: https://github.com/godotengine/godot/issues/73170

### CODE REVIEW

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -2699,7 +2699,11 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 						StringName prop = npath.get_concatenated_subnames();
 						PropertyInfo prop_info;
 						ClassDB::get_property_info(nd->get_class(), prop, &prop_info);
-						bool is_angle = prop_info.type == Variant::FLOAT && prop_info.hint_string.find("radians") != -1;
+						bool is_angle = prop_info.type == Variant::FLOAT && (prop_info.hint_string.find("radians_as_degrees") != -1
+#ifndef DISABLE_DEPRECATED
+																					|| prop_info.hint_string.find("radians") != -1
+#endif
+																			);
```
Comment (AThousandShips) [inline editor/animation_track_editor.cpp:2706]: Unsure how this should best be formatted

Comment (AThousandShips) [inline editor/animation_track_editor.cpp:2706]: Could do this as:
```suggestion
						
#ifdef DISABLE_DEPRECATED
						bool is_angle = prop_info.type == Variant::FLOAT && prop_info.hint_string.find("radians_as_degrees") != -1;
#else
						bool is_angle = prop_info.type == Variant::FLOAT && prop_info.hint_string.find("radians") != -1;
#endif
```
Instead

**Comment by AThousandShips** [comment]
If this gets merged I'll look into uses of the now deprecated hint elsewhere in documentation etc.

**Comment by AThousandShips** [comment]
(Missed a documentation entry in `@GlobalScope` which I'll add after CI has run)

File: modules/gdscript/doc_classes/@GDScript.xml [hunk 2]
```diff
@@ -557,7 +557,7 @@
...
 				If hints [code]"or_greater"[/code] and [code]"or_less"[/code] are provided, the editor widget will not cap the value at range boundaries. The [code]"exp"[/code] hint will make the edited values on range to change exponentially. The [code]"hide_slider"[/code] hint will hide the slider element of the editor widget.
-				Hints also allow to indicate the units for the edited value. Using [code]"radians"[/code] you can specify that the actual value is in radians, but should be displayed in degrees in the Inspector dock. [code]"degrees"[/code] allows to add a degree sign as a unit suffix. Finally, a custom suffix can be provided using [code]"suffix:unit"[/code], where "unit" can be any string.
+				Hints also allow to indicate the units for the edited value. Using [code]"radians_as_degrees"[/code] you can specify that the actual value is in radians, but should be displayed in degrees in the Inspector dock (the range values are also in degrees). [code]"degrees"[/code] allows to add a degree sign as a unit suffix. Finally, a custom suffix can be provided using [code]"suffix:unit"[/code], where "unit" can be any string.
```
Comment (AThousandShips) [inline modules/gdscript/doc_classes/@GDScript.xml:560]:
```suggestion
				Hints also allow to indicate the units for the edited value. Using [code]"radians_as_degrees"[/code] you can specify that the actual value is in radians, but should be displayed in degrees in the Inspector dock (the range values are also in degrees, unchanged). [code]"degrees"[/code] allows to add a degree sign as a unit suffix (the value is unchanged). Finally, a custom suffix can be provided using [code]"suffix:unit"[/code], where "unit" can be any string.
```

File: editor/animation_track_editor.cpp (hunk 1 above)
Comment (YuriSizov) [reply editor/animation_track_editor.cpp:2706]: Yeah, full statement in each block would be better

Comment (AThousandShips) [reply editor/animation_track_editor.cpp:2706]: Good, have done and will push when the CI has finished as it touches `object.h`

**Review by aaronfranke — COMMENTED** [review]
~~I prefer the current name.~~ Marking a property as "radians" means "this property uses radians as its unit", which is an independent thing from how the editor decides to convert the unit. For example, if we ever add an editor setting to display radians as radians, the property hint "radians_as_degrees" makes no sense.

**Comment by AThousandShips** [comment]
But the range is confusing with the naming, and no such system is in place, and are there even any plans to do so? And how would that be useful in the interface?

**Comment by YuriSizov** [comment]
> Marking a property as "radians" means "this property uses radians as its unit"

That doesn't work when the other part of the export hint, the range itself, doesn't use radians as its unit. And we can't change that without breaking compatibility. So we need a new name regardless, even if we want to introduce the behavior that you describe in https://github.com/godotengine/godot/issues/73170#issuecomment-1732381078.

I agree that "radians_as_degrees" caters to one specific behavior, but that's our current and only behavior. And it also aligns the name with how the rest of the hint is set. If we ever add a way to display this value in some other format, it's going to be even a bigger mess, because the actual property would be in radians, the hinted range would be in degrees, and the displayed value would be in ???.

We shouldn't restrict our solutions based on some potential use case in the future, especially given that that use case is unlikely to fit the current implementation.

**Comment by AThousandShips** [comment]
Also, while I don't think there's any really good reason to allow editing radians in the inspector, renaming it now would free up `radians` for this use in the future, without making a breaking change to change its behavior

**Comment by quinnyo** [comment]
Renaming it should at least indicate that it doesn't do a radians-equivalent of the `"degrees"` hint.

Might I suggest using 'to' instead of 'as' so as to match the conversion functions ([`rad_to_deg(float)`](https://docs.godotengine.org/en/latest/classes/class_%40globalscope.html#class-globalscope-method-rad-to-deg)): `"radians_to_degrees"` or even `"rad_to_deg"`.

Also, it's not that important but you can already export radians -- it's just exporting a float normally?

**Comment by AThousandShips** [comment]
> Might I suggest using 'to' instead of 'as'

Already discussed and rejected as it implies the value is modified as opposed to just represented differently

File: doc/classes/@GlobalScope.xml [hunk 3]
```diff
@@ -2719,7 +2719,7 @@
 		<constant name="PROPERTY_HINT_RANGE" value="1" enum="PropertyHint">
 			Hints that an [int] or [float] property should be within a range specified via the hint string [code]"min,max"[/code] or [code]"min,max,step"[/code]. The hint string can optionally include [code]"or_greater"[/code] and/or [code]"or_less"[/code] to allow manual input going respectively above the max or below the min values.
 			[b]Example:[/b] [code]"-360,360,1,or_greater,or_less"[/code].
-			Additionally, other keywords can be included: [code]"exp"[/code] for exponential range editing, [code]"radians"[/code] for editing radian angles in degrees, [code]"degrees"[/code] to hint at an angle and [code]"hide_slider"[/code] to hide the slider.
+			Additionally, other keywords can be included: [code]"exp"[/code] for exponential range editing, [code]"radians_as_degrees"[/code] for editing radian angles in degrees (the range values are also in degrees, unchanged), [code]"degrees"[/code] to hint at an angle and [code]"hide_slider"[/code] to hide the slider.
```
Comment (aaronfranke) [inline doc/classes/@GlobalScope.xml:2722]: I'm not sure the word unchanged actually helps clarify here.

```suggestion
			Additionally, other keywords can be included: [code]"exp"[/code] for exponential range editing, [code]"radians_as_degrees"[/code] for editing radian angles in degrees (the range values are also in degrees), [code]"degrees"[/code] to hint at an angle and [code]"hide_slider"[/code] to hide the slider.
```

**Review by aaronfranke — APPROVED** [review]

File: editor/animation_track_editor.cpp [hunk 4]
```diff
@@ -2699,7 +2699,11 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 						StringName prop = npath.get_concatenated_subnames();
 						PropertyInfo prop_info;
 						ClassDB::get_property_info(nd->get_class(), prop, &prop_info);
+#ifdef DISABLE_DEPRECATED
+						bool is_angle = prop_info.type == Variant::FLOAT && prop_info.hint_string.find("radians_as_degrees") != -1;
+#else
 						bool is_angle = prop_info.type == Variant::FLOAT && prop_info.hint_string.find("radians") != -1;
+#endif // DISABLE_DEPRECATED
```
Comment (akien-mga) [inline editor/animation_track_editor.cpp:2706]: You need to test both in the case where `DISABLE_DEPRECATED` is not defined. Supporting deprecated syntax doesn't mean not supporting the new syntax, it means supporting both (new first, and fallback to deprecated).

Comment (AThousandShips) [reply editor/animation_track_editor.cpp:2706]: Well `prop_info.hint_string.find("radians") != -1` implies `prop_info.hint_string.find("radians_as_degrees") != -1`

Comment (akien-mga) [reply editor/animation_track_editor.cpp:2706]: Ah indeed!

**Review by akien-mga — APPROVED** [review]

File: editor/animation_track_editor.cpp (hunk 4 above)
Comment (AThousandShips) [reply editor/animation_track_editor.cpp:2706]: Granted it will allow anything including `radians` but I'm not sure how to test cleanly here for whole words, and the full phrase would also accept things like `aaaaradians_as_degreesaaaa`

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!
