### PR TITLE
Use processed filter list for native dialogs.

### LINKED ISSUE #99250: Native FileDialog does not add "auto-generated" filter entries
### Tested versions

- Reproduced in v4.4.dev.custom_build [c6c464cf9ae56e8b68620af65125dd980d0e8122]

### System information

Godot v4.4.dev (becbc04e9) - Windows 10.0.19044 - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2080 (NVIDIA; 32.0.15.5585) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 threads)

### Issue description

When setting a FileDialog to native, it passes along the field called `filters` instead of `filter`. (Confusing variable naming here 😄)

The former is the raw array that the user passes, while the latter also translates filter descriptions and also includes entries like "All Recognized" and "All Files" which are auto-generated.

When not using a native window, the auto-generated filter entries are included as expected.

image

image

### Steps to reproduce

- Create FileDialog and enable "Use Native Dialog"
- Add an entry to filters, it can be whatever
- Popup the dialog and notice it does not have any auto-generated entries
- Disable "Use Native Dialog", popup and you see it does have the entries as expected

### Minimal reproduction project (MRP)

I don't have time to create a MRP right now, sorry! I'm mobile for over a week.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/99250

Ensures native dialog filters are translated, have autogenerated filters included and use the same text on all platforms.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/gui/editor_file_dialog.cpp [hunk 1]
```diff
@@ -1161,24 +1163,39 @@ void EditorFileDialog::update_filters() {
 			}
 			all_filters += flt;
 		}
+		for (int i = 0; i < filters.size(); i++) {
+			String flt = filters[i].get_slice(";", 0).strip_edges();
```
Comment (AThousandShips) [inline editor/gui/editor_file_dialog.cpp:1167]:
```suggestion
			String flt = filters[i].get_slicec(';', 0).strip_edges();
```

File: scene/gui/file_dialog.cpp [hunk 2]
```diff
@@ -864,24 +866,39 @@ void FileDialog::update_filters() {
 			}
 			all_filters += flt;
 		}
+		for (int i = 0; i < filters.size(); i++) {
+			String flt = filters[i].get_slice(";", 0).strip_edges();
```
Comment (AThousandShips) [inline scene/gui/file_dialog.cpp:870]:
```suggestion
			String flt = filters[i].get_slicec(';', 0).strip_edges();
```

**Comment by Repiteo** [comment]
Thanks!
