### PR TITLE
Include empty type variations in `Theme::get_type_list`

### LINKED ISSUE #84120: Theme.get_type_list() does not list empty type variations
### Godot version

v4.1.2.stable.arch_linux

### System information

Godot v4.1.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 16:57:15 +0000 - Tty - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 4600 (HSW GT2) () - Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 Threads)

### Issue description

Theme.get_type_list() does not list theme type variations for which no theme item (no constant, no icon, no font, etc) has been set.

Not only is it inconsistent with the behavior description in the docs, and with how Themes are saved as resources (because you can save empty theme variations by calling Theme.set_type_variation("Foo", "Control")), it is inconsistent with Theme.get_type_variation_list(), which does list all type variations regardless of whether theme items have been set for them or not.

This bug means it's impossible to retrieve a full list of type variations (since as far as I can tell, there's no way to list all base_types for which a type variation exists, for example). In essence, the theme resource is partially write-only.

The reason for this bug is quite simple: the code for get_type_list() goes through all the different theme items (fonts, icons, styles) and gathers all theme types, whereas get_type_variation_list() goes through all the variations of the given base_type, regardless of theme items.

The fix is quite simple: inside get_type_list(), for every base_type in variation_base_map, add to the HashSet every type variation associated with that base_type, mimicking get_type_variation_list().

Code links:
get_type_list(): https://github.com/godotengine/godot/blob/3f045951edb9229759644205e155e0a62490ef7a/scene/resources/theme.cpp#L1205
get_type_variation_list(): https://github.com/godotengine/godot/blob/3f045951edb9229759644205e155e0a62490ef7a/scene/resources/theme.cpp#L1153

### Steps to reproduce

```GDScript
var theme := Theme.new()

theme.set_type_variation("Foo", "BoxContainer")
print(theme.get_type_list().has("Foo")) # should print true, but prints false
print(theme.get_type_variation_list("BoxContainer")) # prints true, as is logical

theme.set_theme_item(Theme.DATA_TYPE_CONSTANT, "separation", "Foo", 42)
print(theme.get_type_list().has("Foo")) # now it prints true
print(theme.get_type_variation_list("BoxContainer")) # still prints true
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by quirkylemon**
Fixes #84120 
In get_type_list() loops through variations_map and adds to types hashset.

### CODE REVIEW

File: scene/resources/theme.cpp [hunk 1]
```diff
@@ -1240,6 +1240,11 @@ void Theme::get_type_list(List<StringName> *p_list) const {
 		types.insert(E.key);
 	}
 
+	// Variations
```
Comment (YuriSizov) [inline scene/resources/theme.cpp:1243]:
```suggestion
	// Variations.
```

For consistent style.

**Review by YuriSizov — APPROVED** [review]
Makes sense!

File: scene/resources/theme.cpp (hunk 1 above)
Comment (quirkylemon) [reply scene/resources/theme.cpp]: Sorry about that. it should be fixed now

**Comment by YuriSizov** [comment]
Could you please squash your commits into one? Make sure that the final commit has a short but descriptive message (the title of this PR is a good option). See [this documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase), if you need help with squashing.

**Comment by quirkylemon** [comment]
> Could you please squash your commits into one? Make sure that the final commit has a short but descriptive message (the title of this PR is a good option). See [this documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase), if you need help with squashing.

It should be a single commit now.

also the godot documentations explanation of how to squash commits was amazing.

**Comment by akien-mga** [comment]
Thanks!

**Comment by lamdevhs** [comment]
Thanks so much for this fix!
