### PR TITLE
Fixed bug with text going under scrollbar

### LINKED ISSUE #57881: Tile source names appear over scrollbar
### Godot version

8161e28

### System information

W10

### Issue description

image

### Steps to reproduce

1. Open TileSet editor
2. Add a source with long enough name

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by AlbertFay**
Fixes #57881
I fixed the issue with the text going under the scroll bar in `ItemList`. I changed the default OverrunBehavior to add ellipsis instead of doing nothing.
working preview of itemlist 2

### CODE REVIEW

File: scene/gui/item_list.h [hunk 1]
```diff
@@ -99,7 +99,7 @@ class ItemList : public Control {
 	SelectMode select_mode = SELECT_SINGLE;
 	IconMode icon_mode = ICON_MODE_LEFT;
 	VScrollBar *scroll_bar;
-	TextParagraph::OverrunBehavior text_overrun_behavior = TextParagraph::OVERRUN_NO_TRIMMING;
+	TextParagraph::OverrunBehavior text_overrun_behavior = TextParagraph::OVERRUN_TRIM_ELLIPSIS;
```
Comment (bruvzg) [inline scene/gui/item_list.h:102]: I'm not entirely sure this is desired default mode for all case, but in general should be better the no trim.

**Review by bruvzg — APPROVED** [review]

File: scene/gui/item_list.h (hunk 1 above)
Comment (bruvzg) [reply scene/gui/item_list.h:102]: Run Godot with the `--doctool` command line argument to update the docs, see https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html for more info.

**Comment by AlbertFay** [comment]
I'm not sure how to get rid of the other commits. Help would be appreciated.

**Comment by AlbertFay** [comment]
Thank you so much. It was the `git push --force` that I wasn't doing. Anyways, I updated the class reference.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
