### PR TITLE
Call `EditorNode::set_edited_scene()` manually instead of via the `replacing_by` signal

### LINKED ISSUE #73009: Editor freezes when changing node type Popup to AcceptDialog
### Godot version

4.0rc1

### System information

Windows11

### Issue description

After changing node type Popup to AcceptDialog the editor becomes unresponsive...
This only happens if the Popup node is the root node. If the Popup node is a child to other node the issue does not emerge.

### Steps to reproduce

Create new scene with Popup node as a root.
Change type to AcceptDialog

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
Should not change `scene_root`'s child node in `EditorNode::set_edited_scene()` if replaced later using `replace_by`.  Therefore, it is better to allow the child nodes of `scene_root` not to be modified automatically.

Supersedes #90479.

Fix #73009.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Is this the only case when `replace_by` can be called? Or can it be triggered elsewhere?

**Comment by Rindbee** [comment]
This is for the case of replacing the edited scene root. If you want to replace the original scene root with a new node, you need to manually call `EditorNode::set_edited_scene()` to set the new node. However, for `replace_by`, it is best not to modify the parent node of the new and old nodes first to meet certain conditions.

> Is this the only case when `replace_by` can be called? Or can it be triggered elsewhere?

The main purpose of using `replace_by` is to make the new node inherit some data of the old node. If the new node has already obtained this data, there is no need to use `replace_by`.

**Comment by AThousandShips** [comment]
Just as long as there aren't cases where the editor depends on the signal alone that should be fine, but I'm unsure if it doesn't depend on it for other contexts or I feel signals just wouldn't have been used for this it's quite odd

**Comment by Rindbee** [comment]
What confuses me is that `EditorNode::set_edited_scene` updates 3 `edited_scene_root`, and it seems unclear which one should be the main flag.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -3706,12 +3706,17 @@ void EditorNode::_remove_scene(int index, bool p_change_tab) {
 }
 
 void EditorNode::set_edited_scene(Node *p_scene) {
+	set_edited_scene_root(p_scene, true);
+}
+
+void EditorNode::set_edited_scene_root(Node *p_scene, bool p_auto_add) {
+	ERR_FAIL_COND_MSG(p_scene && p_scene->get_parent(), "Not null nodes that are set as edited scene should not have a parent node.");
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3713]:
```suggestion
	ERR_FAIL_COND_MSG(p_scene && p_scene->get_parent(), "Non-null nodes that are set as edited scene should not have a parent node.");
```

Comment (KoBeWi) [reply editor/editor_node.cpp]: You applied it wrongly 🙃

Comment (Rindbee) [reply editor/editor_node.cpp]: In addition, should re-setting be allowed here? `p_scene == old_edited_scene_root`

**Comment by Rindbee** [comment]
Allow the previous node to be set again as before, as we are not sure which one is used as the flag, we may need to unify the 3 `edited_scene_root`.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -3706,12 +3706,17 @@ void EditorNode::_remove_scene(int index, bool p_change_tab) {
...
+	set_edited_scene_root(p_scene, true);
+}
+
+void EditorNode::set_edited_scene_root(Node *p_scene, bool p_auto_add) {
 	Node *old_edited_scene_root = get_editor_data().get_edited_scene_root();
-	if (old_edited_scene_root) {
+	ERR_FAIL_COND_MSG(p_scene && p_scene != old_edited_scene_root && p_scene->get_parent(), "Non-null nodes that are set as edited scene should not have a parent node.");
+
+	if (p_auto_add && old_edited_scene_root) {
 		if (old_edited_scene_root->get_parent() == scene_root) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3717]:
```suggestion
	if (p_auto_add && old_edited_scene_root && old_edited_scene_root->get_parent() == scene_root) {
```

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -3706,12 +3706,17 @@ void EditorNode::_remove_scene(int index, bool p_change_tab) {
 }
 
 void EditorNode::set_edited_scene(Node *p_scene) {
+	set_edited_scene_root(p_scene, true);
+}
+
+void EditorNode::set_edited_scene_root(Node *p_scene, bool p_auto_add) {
 	Node *old_edited_scene_root = get_editor_data().get_edited_scene_root();
-	if (old_edited_scene_root) {
+	ERR_FAIL_COND_MSG(p_scene && p_scene != old_edited_scene_root && p_scene->get_parent(), "Non-null nodes that are set as edited scene should not have a parent node.");
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3714]: I'm not sure what this condition is trying to do 🤔
If `p_auto_add` is false, it doesn't matter if `p_scene` has a parent.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
