### PR TITLE
Avoid passing zoom scale for ParallaxLayer mirror

### LINKED ISSUE #89563: Regression in ParallaxBackground
### Tested versions

Reproducible in 4.3 dev5, not observed in 4.2 stable

### System information

Windows 10, Godot 4.3 dev5, Nvidia 3060 12 GB

### Issue description

I want to have an infinite scrolling parallax background with 2 layers that move at different speed when the camera is moved and that also respect the zoom level of the camera. I achieved this with ```ParallaxBackground``` and sprites set to repeat to be several times larger than the viewport.
On 4.3 dev5 zooming in causes the top or both layers to dissapear.

### Steps to reproduce

In the attached project you can click and drag around with the mouse to move the camera and the parallax background respectively.
Use the mouse wheel to zoom in and out and notice how one or both layers will not display.

### Minimal reproduction project (MRP)

[BgBug.zip](https://github.com/godotengine/godot/files/14623191/BgBug.zip)

### PR DESCRIPTION
**Pull request by markdibarry**
`ParallaxBackground` doesn't support zoom, so instead it scales all the `ParallaxLayer`s up(!). The old rendering method required that calculation done up front when deciding repeat size, but the new one doesn't. This just uses the `ParallaxLayer`'s original scale to mirror instead.

Before:
68747470733a2f2f692e6779617a6f2e636f6d2f30326364616462626464653565383332643933613765366232356337346561392e676966

After:

https://github.com/godotengine/godot/assets/21325943/499ba4fe-4c20-4f3a-92e0-90bdebab965b

Fixes #89563

I'd like to have some further testing to avoid more regressions. My original PR didn't have any changes to `ParallaxBackground` or `ParallaxLayer` so I want to be cautious with this fix. I'll comment when I have tried a few more scenarios.

### CODE REVIEW

File: scene/2d/parallax_layer.cpp [hunk 1]
```diff
@@ -71,7 +71,7 @@ void ParallaxLayer::_update_mirroring() {
 	if (pb) {
 		RID c = pb->get_canvas();
 		RID ci = get_canvas_item();
-		Point2 mirrorScale = mirroring * get_scale();
+		Point2 mirrorScale = mirroring * orig_scale;
```
Comment (AThousandShips) [inline scene/2d/parallax_layer.cpp:74]:
```suggestion
		Point2 mirror_scale = mirroring * orig_scale;
```
Let's fix the incorrect name while we're at it

Comment (markdibarry) [reply scene/2d/parallax_layer.cpp:74]: Lol. Better late than never!

**Comment by AThousandShips** [comment]
> The old rendering method required that calculation done up front when deciding repeat size, but the new one doesn't

This is somewhat concerning and needs some deeper investigation of potential other side effects from the changes, and sounds like a compatibility breakage

I'm not sure this is the right way to solve this, unsure that breakage is considered valid

**Comment by akien-mga** [comment]
It would be good to figure out what commit caused the regression, since it's apparently not the addition of Parallax2D.

**Comment by AThousandShips** [comment]
Oh that's very interesting, sounded like it was that, will do some digging

**Comment by markdibarry** [comment]
@akien-mga Sorry, I caused a misunderstanding: It *is* my original PR that caused it. I was just clarifying that I didn't change any `ParallaxBackground` or `ParallaxLayer` code in my PR. The renderer method handles both the old nodes and the new one. It used to require the `ParallaxLayer` to account for the scaling before where now it doesn't, but now that I'm actually modifying something in `ParallaxLayer` I want to be sure it's the right call.

**Comment by AThousandShips** [comment]
Now this feature isn't used by the engine anywhere else, but it *is* exposed, so needs some evaluation of what to do to possibly preserve previous behavior

**Comment by markdibarry** [comment]
I've been trying a couple more scenarios between 4.2 and this PR and so far it looks like I haven't found any other regressions in the old nodes. This does, however, uncover an interesting choice we have. 

The behavior for `ParallaxBackground` is that when you zoom in/out, it scrolls the textures as well. I'm not sure if this is desired or not. If not, no changes need be made. If so, for `Parallax2D`, you would have to pass the camera's zoom value separately for every update. The reason is that using the camera's transform would take rotation into account, which we definitely don't want to do with `Parallax2D`. This was not an issue with `ParallaxBackground` only because it doesn't support rotation at all. I could also provide both as a selectable option, but I'd like to know what other's think.

Zoom doesn't scroll textures:

https://github.com/godotengine/godot/assets/21325943/ff777b29-6b79-4925-a7e3-4c462276d460

Zoom scrolls textures:

https://github.com/godotengine/godot/assets/21325943/3c1db403-dfe1-4774-a98e-d4ecdf1cdc0c

**Comment by Mickeon** [comment]
> The behavior for ParallaxBackground is that when you zoom in/out, it scrolls the textures as well. I'm not sure if this is desired or not.

_Absolutely not_ in my humble opinion. Feels like yet another reason to favour Parallax2D

**Comment by markdibarry** [comment]
I did some further testing comparing between versions and it seems this does fix the regression. Unfortunately, the original behavior is not the most ideal since every time you update the scale, you need to reset the mirroring property or it's off. It also seems that `ParallaxLayer` never fully supported scaling besides the zoom feature and scrolling will break if you alter it manually. It's not hard to fix, but that should be in a separate PR. I encountered this issue as well in `Parallax2D`, so I'll make a quick PR to fix that too.

**Comment by Pshy0** [comment]
When zoom scrolls textures, it does not look like a zoom, but rather like moving the camera forward.
Perhaps there could be another property for that if this is needed.

**Review by clayjohn — APPROVED** [review]
Seems fine to me, but I am not very familiar with the ParallaxLayer code

**Comment by akien-mga** [comment]
Thanks!
