### PR TITLE
Expose shape property for shape query parameters classes

### LINKED ISSUE #39699: Bullet engine PhysicsDirectSpaceState.intersect_shape() crash with no errors
**Godot version:**
Godot 3.2.1 Stable 64 Bit

**OS/device including version:**
Windows 10

**Issue description:**
When performing a intersect_shape query using on the space state using the Bullet physics engine, if the PhysicsShapeQueryParameters object's shape is not set, there is a crash with no errors. Using the GodotPhysics physics engine, the error "get: Condition "!p_rid.is_valid()" is true." is outputted to the debugger. Also, this may or may not be a bug, setting the shape of the physics parameters object does not add to the reference counter of the shape, so if the shape was created locally and set to the physics parameter object inside that same scope, when the shape is freed it causes the same crash when using the BulletPhysics engine. PhysicsShapeQueryParameters.set_shape() isn't referencing the shape directly. Maybe that isn't a bug, it just seems that way because of the Bullet engine crash.

**Steps to reproduce:**
I created a project with three nodes. NoShapeSet has a script that performs an intersect_shape with no shape set. ShapeReferenceLost sets the shape in the local scope of a setup function so that the shape reference is lost before the intersect_shape is performed. ShapeReferenceHeld holds a reference to the shape in a script variable and set it to the physics parameters object to act as the control. No crash happens when running the test with only this node's test enabled.

I added two export variables to enable/disable the test on each node and to set whether the intersect_shape is run just once or every frame.

A simple workaround would be to just make sure all query parameters have shapes set and that all shapes used aren't accidently freed, but without error outputs, it took me a bit to track down what caused it in my personal project I am working on. So, a proper fix would be better.

**Minimal reproduction project:**

[PhysicsBug.zip](https://github.com/godotengine/godot/files/4807332/PhysicsBug.zip)

### PR DESCRIPTION
**Pull request by Xrayez**
Exposed properties for both 2D and 3D physics (missing getter).

Related to #15611 (CC @bojidar-bg):

> OS.window_title, **Physics{,2D}ShapeQueryParameters.shape** and Viewport.attach_to_screen_rect lack getters, so I didn't bind them.

Thoughts:
1. ~~Should `shape_rid` be unexposed in favor high-level `shape` member? (4.0)~~ no, see a use case at https://github.com/godotengine/godot/pull/39846#issuecomment-650121026.
2. The doc gen doesn't seem to respect `Shape[2D]` resource type hints for these properties.

Fixes #39699 (see #39846).

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Perhaps do the same for `Physics2DTestMotionResult::collider_rid` (found by searching for `member.+type="RID` in the docs)?

To make the type match, you should change the type from `RES` to `Shape{,2D}`.

They cannot be removed prior to 4.0, so this part of the change should be tracked in #16863.

Note that the code does not build currently.

**Comment by Xrayez** [comment]
> To make the type match, you should change the type from `RES` to `Shape{,2D}`.

Wouldn't this introduce coupling with scene resources? Also I'm not sure whether it's possible to override default shape implementation. Note that currently it still reports as `Resource` in the docs without this PR. I wonder if it can be made possible for the docs to retrieve custom scene export hint even if the object is represented as a `Ref<Resource>` in that case.

> Note that the code does not build currently.

Works perfectly fine on MSVC... Should be solved with the above suggestion though.

**Comment by bojidar-bg** [comment]
Well, it is possible to force a custom return type by adding `:Type` after the method's name, something like:
```c++
ClassDB::bind_method(D_METHOD("get_shape:Shape2D"), &Physics2DShapeQueryParameters::get_shape);
```

**Comment by Xrayez** [comment]
So I was wrong with my assumption that one can convert `RID` to an instance like that, The MSVC compiler was just more permissive and let the `RID` to be converted to a `null` instance in getter...

Updated PR to store the actual reference to the shape resource. I left it as `RES` as it seems like it's possible to implement your own `Shape[2D]` implementation and it shouldn't depend on specific one provided by Godot core I think.

**Comment by Xrayez** [comment]
Rebased following the 2D/3D renames. I do still think it's worth to expose the `shape` property so that we only have structure-like physics parameter class with properties.

**Comment by Xrayez** [comment]
Stumbled upon #39846 which does similar thing except it actually breaks compat in 4.0 as suggested. This PR targeted 3.2 initially so perhaps this can be redone for 3.2 specifically, as it does not break compat.

File: servers/physics_server_2d.cpp [hunk 1]
```diff
@@ -132,9 +132,14 @@ PhysicsDirectBodyState2D::PhysicsDirectBodyState2D() {}
...
+	ERR_FAIL_COND(p_shape_ref.is_null());
+	shape_ref = p_shape_ref;
+	shape = p_shape_ref->get_rid();
+}
+
+RES PhysicsShapeQueryParameters2D::get_shape() const {
+	return shape_ref;
 }
 
 void PhysicsShapeQueryParameters2D::set_shape_rid(const RID &p_shape) {
```
Comment (pouleyKetchoupp) [inline servers/physics_server_2d.cpp:145]: `shape_ref` should be reset here to keep things consistent.

File: servers/physics_server_3d.cpp [hunk 2]
```diff
@@ -136,9 +136,14 @@ PhysicsDirectBodyState3D::PhysicsDirectBodyState3D() {}
...
+	ERR_FAIL_COND(p_shape_ref.is_null());
+	shape_ref = p_shape_ref;
+	shape = p_shape_ref->get_rid();
+}
+
+RES PhysicsShapeQueryParameters3D::get_shape() const {
+	return shape_ref;
 }
 
 void PhysicsShapeQueryParameters3D::set_shape_rid(const RID &p_shape) {
```
Comment (pouleyKetchoupp) [inline servers/physics_server_3d.cpp:149]: Same thing here, `shape_ref` should be reset to keep things consistent.

**Review by pouleyKetchoupp — COMMENTED** [review]
Just commented on some little things that could be improved, otherwise it looks great :)

File: servers/physics_server_2d.cpp (hunk 1 above)
Comment (Xrayez) [reply servers/physics_server_2d.cpp:145]: By resetting you mean this?

```suggestion
void PhysicsShapeQueryParameters2D::set_shape_rid(const RID &p_shape) {
	shape = p_shape;
	shape_ref = RES();
```

In that case we don't want to lose the actual reference if the `p_shape == shape`, will add an additional check if possible.

Comment (pouleyKetchoupp) [reply servers/physics_server_2d.cpp:145]: Yes that's what I meant! And I agree, it's safer to first check if there's a stored shape and if the rid is different.

**Comment by akien-mga** [comment]
Does this fix #39699 too like #39699 would?

File: doc/classes/PhysicsShapeQueryParameters2D.xml [hunk 3]
```diff
@@ -38,8 +29,11 @@
 		<member name="motion" type="Vector2" setter="set_motion" getter="get_motion" default="Vector2( 0, 0 )">
 			The motion of the shape being queried for.
 		</member>
+		<member name="shape" type="Resource" setter="set_shape" getter="get_shape">
+			The [Shape2D] that will be used for collision/intersection queries. See also [member shape_rid].
+		</member>
 		<member name="shape_rid" type="RID" setter="set_shape_rid" getter="get_shape_rid">
-			The queried shape's [RID]. See also [method set_shape].
+			The queried shape's [RID]. See also [member shape].
```
Comment (pouleyKetchoupp) [inline doc/classes/PhysicsShapeQueryParameters2D.xml:36]: I'm thinking that it would be nice if the documentation explicitly mentioned that `set_shape` will store a reference, and in the `shape_id` property it could say that it's safer to use `shape` if you're creating a `Shape2D` for the query.

**Comment by pouleyKetchoupp** [comment]
@akien-mga Yes it fixes #39699 too

**Comment by Xrayez** [comment]
Applied suggestions by @pouleyKetchoupp (added as co-author as well).

Also added some code snippets as in https://github.com/godotengine/godot/pull/39846#issuecomment-650121026.

Tested with 3D as well (interestingly, 2D and 3D have inconsistent API):

```gdscript
extends Node3D

func _ready():
	var rid = PhysicsServer3D.shape_create(PhysicsServer3D.SHAPE_SPHERE)
	var radius = 2.0
	PhysicsServer3D.shape_set_data(rid, radius)
	
	var shape = SphereShape3D.new()
	var params = PhysicsShapeQueryParameters3D.new()
	
	params.shape = shape
	assert(params.shape == shape)
	
	params.shape_rid = rid
	assert(params.shape == null) # Different resources, should be reset.
	
	params.shape = shape
	params.shape_rid = shape.get_rid()
	assert(params.shape == shape) # Not changed, same resource.

```

File: doc/classes/PhysicsShapeQueryParameters3D.xml [hunk 4]
```diff
@@ -35,8 +26,19 @@
 		<member name="margin" type="float" setter="set_margin" getter="get_margin" default="0.0">
 			The collision margin for the shape.
 		</member>
+		<member name="shape" type="Resource" setter="set_shape" getter="get_shape">
+			The [Shape3D] that will be used for collision/intersection queries. This stores the actual reference which avoids the shape to be released while being used for queries, so always prefer using this over [member shape_rid].
+		</member>
 		<member name="shape_rid" type="RID" setter="set_shape_rid" getter="get_shape_rid">
-			The queried shape's [RID]. See also [method set_shape].
+			The queried shape's [RID] that will be used for collision/intersection queries. Use this over [member shape] if you want to optimize for performance using the Servers API:
```
Comment (pouleyKetchoupp) [inline doc/classes/PhysicsShapeQueryParameters3D.xml:33]: Looks great! Just one last suggestion (I'm nitpicking now): this code sample doesn't show how to release resources in this case and might mislead users in causing leaks.

Maybe just adding something like this at the end would makes things perfectly clear:
```
# Execute physics queries here...

# Release the shape when done with physics queries.
PhysicsServer3D.free_rid(rid)
```

Comment (Xrayez) [reply doc/classes/PhysicsShapeQueryParameters3D.xml:33]: Done, I wonder whether those RIDs are automatically freed by the server when exiting application though, I hope so!

Comment (pouleyKetchoupp) [reply doc/classes/PhysicsShapeQueryParameters3D.xml:33]: Leaks in rid owners are detected on exit and an error is printed:
https://github.com/godotengine/godot/blob/b92477d77e9a6f46e4276a20a451dfac9d485f47/core/rid_owner.h#L289-L299

Which is good I think. In case users forget to free them they are at least notified when the game quits.

**Review by madmiraal — APPROVED** [review]
Looks good. :+1:

**Comment by akien-mga** [comment]
Thanks!
