### PR TITLE
Fix `total_visible_line_count` calculation when removing and clearing `TextEdit`'s text.

### LINKED ISSUE #97595: Cutting folded region restricts scrolling after cut and after undo
### Tested versions

v4.4.dev2.official [97ef3c837]

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6109) - 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 Threads)

### Issue description

Cutting a folded region restricts the scrolling, making the bottom of the code unreachable. Undoing the cut still restricts the scroll.

### Steps to reproduce

Have code in a region, and code below it.
Collapse the region and cut, then check scroll
Undo cut and check scroll

### Minimal reproduction project (MRP)

MRP:
[mrp_restricted_region_scroll.zip](https://github.com/user-attachments/files/17175902/mrp_restricted_region_scroll.zip)

Video:
https://github.com/user-attachments/assets/bfc4394d-0714-49c4-88b7-0cf6f8d2508a

### PR DESCRIPTION
**Pull request by Daylily-Zeleen**
This pr fix a bug that when a TextEdit has some folded lines and set its text, the scroll bar can not be updated correctly.

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/97595

### CODE REVIEW

**Comment by kitbdev** [comment]
- fixes https://github.com/godotengine/godot/issues/97595
- partial duplicate of https://github.com/godotengine/godot/pull/97898

Only partial since I didn't fix the issue with the clear.

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -427,14 +428,18 @@ void TextEdit::Text::remove_range(int p_from_line, int p_to_line) {
 		if (text_line.width == max_line_width) {
 			max_line_width_dirty = true;
 		}
-		total_visible_line_count -= text_line.line_count;
+		if (!text_line.hidden) {
+			total_visible_line_count -= text_line.line_count;
+		}
```
Comment (bruvzg) [inline scene/gui/text_edit.cpp:433]: Doing it like it's done in https://github.com/godotengine/godot/pull/97898 seems better, since there's no need to update max w/h if a hidden line is removed.

Comment (Daylily-Zeleen) [reply scene/gui/text_edit.cpp]: You are right. I changed it now.

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
