### PR TITLE
[3.x] Faster queue free

### LINKED ISSUE #61929: Deleting large numbers of child nodes can be excessively slow
### Godot version

3.5 current (3.5 RC 3), earlier versions presumably

### System information

N/A

### Issue description

While benchmarking something else, I noticed that the time taken to `queue_delete()` a large number of `MeshInstance` children seemed to grow exponentially with the number of siblings of the parent. This is unlikely to come up that often outside of benchmarks / extreme cases, but is still a concern.

On discussion with @akien-mga there were two suspect areas, the ordered remove and possibly notifications sent as a result of the moving of the children. Testing revealed that the slowdown didn't occur when removing children in back to front order, which confirmed the suspicions.

I've also profiled the slow situation:
queue_delete_profile

### Steps to reproduce

* Add a large number of children to a node (5000+)
* Call `queue_delete()` in the order of `get_child()`

### Minimal reproduction project
[QueueDeleteSlow.zip](https://github.com/godotengine/godot/files/8883695/QueueDeleteSlow.zip)
* Run the MRP, takes ~5 seconds to add 10,000 boxes and queue delete.
* Comment out the `queue_free()` line 14, takes 250ms.

If you queue free in reverse order:
```
	var num_children = $Boxes.get_child_count()
	for n in range (num_children):
		$Boxes.get_child(num_children - 1 - n).queue_free()
```
It takes 730ms - still curiously slower than adding, but a lot faster than before.

**Update**
Make the box invisible to eliminate the BVH from the bottlenecks, this shows the real difference from the PR linked.

### Discussion
It is possible we can modify the deletion code to prevent this situation occurring, perhaps by guaranteeing reverse ordering:
* sorting the deletion list
* searching in reverse order through children for `queued_for_deletion` flags when deleting nodes

Additionally, if there is a notification on re-ordering, perhaps it can be sent once (after all deletes) instead of after each deletion.

### PR DESCRIPTION
**Pull request by lawnjelly**
Calling `queue_free()` for large numbers of siblings could previously be very slow, with the time taken rising exponentially with number of children. This looked partly due to ordered_remove from the child list and notifications.

This PR identifies objects that are nodes, and sorts the deletion queue so that children are deleted in reverse child order. This minimizes the costs of reordering.

Fixes #61929
Supercedes #61932

## Performance testing, number of child nodes deleted
**50000 nodes** before 137017 ms, after 422 ms seconds (**325x** faster)
**20000 nodes** before 19425 ms, after 250 ms seconds (**78x** faster)
**5000 nodes** before 1228 ms, after 169 ms seconds (**7.3x** faster)
**1000 nodes** before 194 ms, after 150 ms seconds (**1.3x** faster)

(at lower node numbers the measurement from the MRP in #61929 becomes less useful as there are some fixed delays, however the pattern is that the benefit really starts to show with a decent number of children)

## Notes
* On further research, it turned out the child id _is_ already stored in nodes, in `data->pos`, and sorting by child id is a superior approach. It achieves the same upside of deleting in reverse order, but eliminates the possible downside of deleting small numbers of children from a parent that has a large number of children.
* Compared to the previous PR, the technique can now be employed in all cases (rather than having an arbitrary cutoff), and will always yield some benefit (though exponentially more benefit as the number of children rises), and effectively should have negligible cost.
* Uses an additional bit twiddling technique to combine the child id with a "group", to ensure that in most cases, the children of the same parent will be sorted together in the list. This could make things more cache friendly, and is super cheap to do, so why not.
* I also evaluated using a dirty flag for `NOTIFICATION_MOVED_IN_PARENT`. While this increased performance over baseline, it wasn't nearly as effective as the reverse ordering in this PR.
* Same principle can be applied in 4.x as the code is similar.

### CODE REVIEW

File: scene/main/scene_tree.cpp [hunk 1]
```diff
@@ -1217,20 +1217,75 @@ void SceneTree::get_nodes_in_group(const StringName &p_group, List<Node *> *p_li
...
+	// due to notifications being sent to children that are moved, further in the child list.
+	struct ObjectIDComparator {
+		_FORCE_INLINE_ bool operator()(const DeleteQueueElement &p, const DeleteQueueElement &q) const {
+			return (p.child_list_id > q.child_list_id);
+		}
+	};
+
+	delete_queue.sort_custom<ObjectIDComparator>();
+
+	for (unsigned int e = 0; e < delete_queue.size(); e++) {
```
Comment (AaronRecord) [inline scene/main/scene_tree.cpp:1232]:
```suggestion
	for (uint32_t e = 0; e < delete_queue.size(); e++) {
```
Is there a reason to use `unsigned int` over `uint32_t`? I think `uint32_t` is more common in the codebase, and `size()` returns a `uint32_t`:
image

File: scene/main/scene_tree.cpp [hunk 2]
```diff
@@ -1217,20 +1217,75 @@ void SceneTree::get_nodes_in_group(const StringName &p_group, List<Node *> *p_li
...
 
 void SceneTree::queue_delete(Object *p_object) {
 	_THREAD_SAFE_METHOD_
 	ERR_FAIL_NULL(p_object);
-	p_object->_is_queued_for_deletion = true;
-	delete_queue.push_back(p_object->get_instance_id());
+
+	// Guard against the user queueing multiple times,
+	// which is unnecessary.
+	if (!p_object->is_queued_for_deletion()) {
```
Comment (AaronRecord) [inline scene/main/scene_tree.cpp:1249]:
```suggestion
	if (p_object->is_queued_for_deletion()) {
		return;
	}
```

You could return early here and save some horizontal space

File: scene/main/scene_tree.cpp [hunk 3]
```diff
@@ -1217,20 +1217,77 @@ void SceneTree::get_nodes_in_group(const StringName &p_group, List<Node *> *p_li
...
+	DeleteQueueElement e;
+	e.id = p_object->get_instance_id();
+
+	// Storing the list id within the parent allows us
+	// to sort the delete queue in reverse for more efficient
+	// deletion.
+	// Note that data.pos could alternatively be read during flush_delete_queue(),
+	// however reading it here avoids an extra lookup, and should be correct in most cases.
+	// And worst case if the child_list_id changes in the meantime, it will still work, it may just
+	// be slightly slower.
```
Comment (timothyqiu) [inline scene/main/scene_tree.cpp:1264]: Why does it need __extra__ lookup when in `flush_delete_queue()`? I think `data.pos` is still available at that time.

File: scene/main/scene_tree.cpp [hunk 4]
```diff
@@ -1217,20 +1217,77 @@ void SceneTree::get_nodes_in_group(const StringName &p_group, List<Node *> *p_li
...
+
+			// Use a prime number to combine the group with the child id.
+			// Provided there are less than the prime number children in a node,
+			// there will be no collisions. Even if there are collisions, it is no problem.
+			uint32_t group = parent_id * 937;
+
+			// Rollover the group, we never want the group + the child id
+			// to overflow 31 bits
+			group &= (1 << 29);
+			e.child_list_id += (int32_t)group;
```
Comment (timothyqiu) [inline scene/main/scene_tree.cpp:1283]: Is it intended that this makes `group` either `2^29` or `0`?

To avoid overflowing the 32-bit integer, probably better to clear the top 2 bits, e.g. `&= ~(0b11 << 29)`.

Also, does it make sense to make `child_list_id` unsigned? Non-nodes and nodes without a parent can then take `UINT32_MAX`. And it'll be easier to avoid overflowing the id since we are sure that regular `pos` is only half the domain.

File: scene/main/scene_tree.cpp (hunk 3 above)
Comment (lawnjelly) [reply scene/main/scene_tree.cpp:1264]: I think (from memory as I wrote this a while ago) it was that it would have to load all the objects into cache again with a bunch of potential cache misses (if a large amount of objects) unnecessarily. Better to keep the operations using the same bit of memory local, as the object should already be in cache at this point.

This is theoretical, I didn't benchmark both.

File: scene/main/scene_tree.cpp (hunk 4 above)
Comment (lawnjelly) [reply scene/main/scene_tree.cpp:1283]: Well spotted this is a bug, it should be ANDing with 29 bits set. :+1:

Comment (lawnjelly) [reply scene/main/scene_tree.cpp]: Good thing I double checked this with calculator, it has to be `~(0b111 << 29)` or `~(0b11 << 30)`. I went for the prior just for a little safety even though probably not required. :grinning: 

It turns out `~(0b11 << 29)` is:
`1001 1111 11111111 11111111 11111111` which wouldn't have had the desired effect.

**Review by timothyqiu — APPROVED** [review]
Looks good to me.

I believe the overflow when calculating `child_list_id` is destined to happen as long as the numbers are large enough. The bit operation removed quite a lot possibilities and it requires a huge number of sibling nodes to overflow now. It's relatively safe even when overflows (not undefined behavior), so I think this is okay :)

**Comment by lawnjelly** [comment]
Made me wonder what the maximum number of children might be! Not sure this is correct but :grinning:

The group can be a maximum of 536,870,911 .. (29 bits)
We have 31 bits to play with before overflow to negative value (maximum value 2147483647 which is `INT32_MAX`) ..

so I think we'd need 2147483647 - 536870911 to overflow:
1,610,612,736 children?

So I think that's enough for 1 and a half billion children of a node. (It could happen!)

**Comment by RandomShaper** [comment]
I'm wondering if we should consider this a compat breaking change since it can affect observable behavior (e.g., user scripts handling `NOTIFICATION_PREDELETE` that for some reason realy on the current order of deletion). In that case it may be good that in 3.x there's a project setting to opt-in sorting (I think if the "queue" is not sorted, the behavior is as formerly, right?). Such a setting could be disabled by default but enabled for new projects, as we've done with other compat breaking but expected to be universally wanted changes.

**Comment by RandomShaper** [comment]
Also, I'm wondering if it may be better that, instead of sorting just when about to mass-delete, the delete queue is backed by an already sorted container, such as hash set.

**Comment by lawnjelly** [comment]
> I'm wondering if we should consider this a compat breaking change since it can affect observable behavior (e.g., user scripts handling `NOTIFICATION_PREDELETE` that for some reason realy on the current order of deletion). In that case it may be good that in 3.x there's a project setting to opt-in sorting (I think if the "queue" is not sorted, the behavior is as formerly, right?). Such a setting could be disabled by default but enabled for new projects, as we've done with other compat breaking but expected to be universally wanted changes.

Sure I can put this in. I would strongly suggest that any sort of guarantee of order should be discouraged - I'll add this in the classref for `queue_free()`. Without a written guarantee I wouldn't expect wise users to rely on this, but you are correct it is at least possible. Although if there are no reports we could consider removing the option after a couple of betas.

> Also, I'm wondering if it may be better that, instead of sorting just when about to mass-delete, the delete queue is backed by an already sorted container, such as hash set.

I'm not super familiar with hash set - what advantage are you thinking in terms of hash set over sorting? I'm assuming the standard Godot sort is something like qsort (i.e. in place and not using dynamic allocation) .. I haven't looked in detail.

**Comment by akien-mga** [comment]
> > I'm wondering if we should consider this a compat breaking change since it can affect observable behavior (e.g., user scripts handling `NOTIFICATION_PREDELETE` that for some reason realy on the current order of deletion). In that case it may be good that in 3.x there's a project setting to opt-in sorting (I think if the "queue" is not sorted, the behavior is as formerly, right?). Such a setting could be disabled by default but enabled for new projects, as we've done with other compat breaking but expected to be universally wanted changes.
> 
> Sure I can put this in. I would strongly suggest that any sort of guarantee of order should be discouraged - I'll add this in the classref for `queue_free()`. Without a written guarantee I wouldn't expect wise users to rely on this, but you are correct it is at least possible. Although if there are no reports we could consider removing the option after a couple of betas.

Since we're speculating here, I prefer going with the "ask for forgiveness" approach. Change the behavior, see if anyone complains, and consider adding an option for those users if they exist.

**Comment by lawnjelly** [comment]
> Since we're speculating here, I prefer going with the "ask for forgiveness" approach. Change the behavior without opt-out, see if anyone complains, and consider adding an option for those users if they exist. Otherwise we're just adding configuration options for things which may not be needed.
> 
> Betas don't have to be production ready, so if this behavior change is a showstopper for some users, they should report it after testing the beta and stick to using 3.5.x until their feedback is addressed in later 3.6 betas.

I actually agree here... and I'd just added the project setting lol. I'll change it back, but keep a comment in the `queue_free` classref to mention that the order is not guaranteed. :+1:

**Comment by RandomShaper** [comment]
Fair enough.

**Comment by RandomShaper** [comment]
> I'm not super familiar with hash set - what advantage are you thinking in terms of hash set over sorting? I'm assuming the standard Godot sort is something like qsort (i.e. in place and not using dynamic allocation) .. I haven't looked in detail.

To be honest, it's hard to tell for sure without benchmarking, but my idea with a sorted container (it'd be `RBSet` actually) there may be some code complexity or maybe performance advantages. Just an idea if you wish to try and compare.

**Review by RandomShaper — APPROVED** [review]

**Comment by eimfach** [comment]
+1 for this. I am developing a hex turn-based strategy game with lots of tiles and need a fast `queue_free` and/or `free` for releasing tiles out of view. Would be very happy to see this fix soon ! :)

**Comment by akien-mga** [comment]
We discussed this yesterday with @reduz and @lawnjelly.
@reduz wants to explore an alternative solution for 4.x, so we'll hold off merging the `master` PR for now, but for `3.x` we agreed to merge this approach.

**Comment by akien-mga** [comment]
Thanks!

**Comment by shafnaz** [comment]
Nice!
