### PR TITLE
Fixed issues with blend modes in OpenGL 3 renderer

### LINKED ISSUE #76334: OpenGL: Blend modes other than Mix don't work unless Depth Draw Mode is set to Never
### Godot version

v4.1.dev1.official [db1302637]

### System information

Windows 10, Compatibility, NVIDIA GeForce GTX 1050 Ti (528.24)

### Issue description

Setting the blend mode to something besides mix behaves the same as mix. This is the same whether is a ShaderMaterial or a StandarMaterial3D.

Blend-Add

I think this should have been fixed by #75968 unless I misunderstood the PR, and it does seem to be included in this version (4.1 dev1). It does work if you set the **Depth Draw Mode** to **Never** though.

### Steps to reproduce

- Add a MeshInstance3D with a mesh of any type
- Add a StandarMaterial3D
- Set the blend mode to add (or any other than mix)
- It won't work unless you set the depth draw mode to Never

### Minimal reproduction project

[BlendAdd.zip](https://github.com/godotengine/godot/files/11300080/BlendAdd.zip)

### PR DESCRIPTION
**Pull request by allenwp**
Added uses_blend_alpha = true for ADD, SUBTRACT, and MULTIPLY blend modes to match the other renderers.

Fixes #76334

### CODE REVIEW

File: drivers/gles3/storage/material_storage.cpp [hunk 1]
```diff
@@ -3452,6 +3452,10 @@ void SceneShaderData::set_code(const String &p_code) {
 		blend_mode = BLEND_MODE_ALPHA_TO_COVERAGE;
 	}
 
+	if (blend_mode == BLEND_MODE_ADD || blend_mode == BLEND_MODE_SUB || blend_mode == BLEND_MODE_MUL) {
+		uses_blend_alpha = true; //force alpha used because of blend
```
Comment (clayjohn) [inline drivers/gles3/storage/material_storage.cpp:3456]:
```suggestion
		uses_blend_alpha = true; // Force alpha used because of blend.
```
Our style guide requires comments to start with a capital and end with a period. I know this comment was a copy paste from a line already in the engine, but we do try to enforce the style guide on all new comments

File: drivers/gles3/rasterizer_canvas_gles3.cpp [hunk 2]
```diff
@@ -735,7 +735,7 @@ void RasterizerCanvasGLES3::_render_items(RID p_to_render_target, int p_item_cou
 
 				} break;
 				case GLES3::CanvasShaderData::BLEND_MODE_SUB: {
-					glBlendEquation(GL_FUNC_REVERSE_SUBTRACT);
+					glBlendEquation(GL_FUNC_SUBTRACT);
```
Comment (clayjohn) [inline drivers/gles3/rasterizer_canvas_gles3.cpp:738]: I'm not sure about this. In Godot ``BLEND_MODE_SUB`` means that the color from the pixel shader is subtracted from the color behind it. That corresponds to ``GL_FUNC_REVERSE_SUBTRACT``. ``GL_FUNC_SUBTRACT`` subtracts the background color from the pixel shader color and returns that value.

I.e. if you want to write a white pixel to a grey background with ``GL_FUNC_REVERSE_SUBTRACT`` you get ``(0.5, 0.5, 0.5) - (1, 1, 1,) = (0, 0, 0)`` while with ``GL_FUNC_SUBTRACT`` you get ``(1, 1, 1) - (0.5, 0.5, 0.5) = (0.5, 0.5, 0.5)``

**Comment by clayjohn** [comment]
Thanks for taking a look at this. It is super helpful to have others working on the opengl backend

File: drivers/gles3/storage/material_storage.cpp (hunk 1 above)
Comment (allenwp) [reply drivers/gles3/storage/material_storage.cpp]: Thanks for pointing this out! Makes perfect sense :)

File: drivers/gles3/rasterizer_canvas_gles3.cpp (hunk 2 above)
Comment (allenwp) [reply drivers/gles3/rasterizer_canvas_gles3.cpp:738]: Ah, I see that the OpenGL renderer has always used `GL_FUNC_REVERSE_SUBTRACT` for `BLEND_MODE_SUB`. Thanks for pointing this out! I will remove this from the PR.

The reason that I initially made this change was to match the behaviour of the other two renderers in Godot 4 which use `BLEND_OP_SUBTRACT` instead of `BLEND_OP_REVERSE_SUBTRACT`:

https://github.com/godotengine/godot/blob/b7032b5ecf8ac247e01acd5e54c9028c0dfe52df/servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp#L221-L222

https://github.com/godotengine/godot/blob/b7032b5ecf8ac247e01acd5e54c9028c0dfe52df/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L210-L211

https://github.com/godotengine/godot/blob/b7032b5ecf8ac247e01acd5e54c9028c0dfe52df/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L2124-L2125

I will open a different issue sometime later regarding the inconsistency of `BLEND_MODE_SUB` when using different renderers in Godot 4.

**Comment by allenwp** [comment]
> Thanks for taking a look at this. It is super helpful to have others working on the opengl backend

I appreciate this! There's always some challenge with approaching a new open source project, so this feels good to hear. I also believe that one of the top 2 or maybe the top value of a game engine is portability across all devices, including old ones, so the OpenGL backend remains very important.

File: drivers/gles3/rasterizer_canvas_gles3.cpp (hunk 2 above)
Comment (clayjohn) [reply drivers/gles3/rasterizer_canvas_gles3.cpp]: Ah, good catch. So it seems the RD backends are reversed. That actually explains some things

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
