### PR TITLE
Fix tile resizing towards atlas boundary

### LINKED ISSUE #75213: Can't drag a tile on the second row to expand over the first row
### Godot version

4.0.1.stable

### System information

Arch Linux

### Issue description

In the tileset atlas source editor, you can drag to expand the tile after selecting it with the pink handles.

However, you can't drag the top handle up if the tile is on the second row, even if the first row is empty.

ksnip_20230322-161103

### Steps to reproduce

1. Create a tile on the second row.
2. Make sure the first row is empty.
3. Try to drag the top handle up.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #75213

The resizing logic was fine. It was built around the assumption that it can get out-of-bound tile coordinates. But the function to get tile coordinate was probably changed later, clamping the returned coordinate inside the atlas boundary.

This PR changes the `clamp` argument of `TileAtlasView::get_atlas_tile_coords_at_pos()` from `bool` to `ClampMode`, adding a way to clamp to the `(-1, -1, width, height)` region.

https://github.com/godotengine/godot/blob/4e4ba295226030ebf3e9c26a920f0f7511fc21f7/editor/plugins/tiles/tile_atlas_view.h#L125-L129

The previous `clamp = false` can't be reused because it should error by returning the `INVALID_ATLAS_COORDS` constant when the input position is out-of-bound.

### CODE REVIEW

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 1]
```diff
@@ -1100,7 +1101,7 @@ void TileSetAtlasSourceEditor::_tile_atlas_control_gui_input(const Ref<InputEven
 				}
 			} else if (drag_type >= DRAG_TYPE_RESIZE_TOP_LEFT && drag_type <= DRAG_TYPE_RESIZE_LEFT) {
 				// Resizing a tile.
-				new_base_tiles_coords = new_base_tiles_coords.max(Vector2i(-1, -1)).min(grid_size);
+				new_base_tiles_coords = tile_atlas_view->get_atlas_tile_coords_at_pos(tile_atlas_control->get_local_mouse_position(), TileAtlasView::CLAMP_MARGIN);
```
Comment (groud) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:1104]: If this is the only place where this is needed, I believe modifying so much code is not really needed.
Instead,  I think you should use the unclamped version and clamp it manually like how it was done before. Basically you would just replace this line by:
```
new_base_tiles_coords = tile_atlas_view->get_atlas_tile_coords_at_pos(tile_atlas_control->get_local_mouse_position()).max(Vector2i(-1, -1)).min(grid_size);
```

**Review by groud — CHANGES_REQUESTED** [review]

**Review by groud — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!
