### PR TITLE
Set the shortcut context for the edit/search/goto menus to the ScriptEditor so that shortcuts continue to work when FindReplaceBar is focused.

### LINKED ISSUE #67743: ScriptEditor shortcuts only work when focused on code editor
### Godot version

Godot 4.0 beta 3

### System information

Windows 10

### Issue description

In Godot 4 beta 3 it's become impossible to use ScriptEditor shortcuts without having to focus on the code editor first.

In Godot 3 we're able to use the `find` shortcut while focused on the code editor, and even when focused on the `find` input we're still able to use the `find and replace` shortcut; as well as when focused on the filter methods input we're able to use ScriptEditor shortcuts, as seen below:
https://user-images.githubusercontent.com/17155529/197325485-0fc23954-a10d-46b2-b7fb-b9424fe6381b.mp4

However, now in Godot 4 beta 3, we can still use the `find` shortcut while focused on the code editor, however once focused on the find input I'm not able to use anymore ScriptEditor shortcuts, nor when focused on any other thing other than the code editor. This means if I want to switch between `find` and `find and replace` with shortcuts I'd have to focus on the code editor again to be able to use them, as seen below:
https://user-images.githubusercontent.com/17155529/197325476-cb8b4034-0221-4aa2-b318-c10d6183a4c6.mp4

### Steps to reproduce

- Open Godot Engine
- Open any editable file with the ScriptEditor
- Focus on text editor
- Use any ScriptEditor shortcut
- Shortcut works
- Focus on anything else than the text editor
- Use any ScriptEditor shortcut
- Shortcut won't work

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by EricEzaM**
Fixes #67743
See https://github.com/godotengine/godot/issues/67743#issuecomment-1288048173 for some additional notes

This could potentially be done without the added method to `ScriptEditorBase`, but it would involve assuming what the children of `get_edit_menu()` are. This PR's solution is more verbose but also allows for more control by implementers of `ScriptEditorBase`. It might be too much though. The `for` loop in the method implementation could just "inlined" where `se->set_edit_menu_shortcut_context(this);` is called and the result would be the same. However it would break, for example, if `se->get_edit_menu()` had it's menu items nested in additional Controls.

### CODE REVIEW

**Comment by Paulb23** [comment]
Could we reuse / pass it in via `enable_editor` setting the context when they are created, a bit more selectively?

**Comment by EricEzaM** [comment]
@Paulb23 Ok, what do you think?

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -161,6 +161,15 @@ void ScriptTextEditor::enable_editor() {
 	_enable_code_editor();
```
Comment (Paulb23) [inline editor/plugins/script_text_editor.cpp:161]: Would it be worth passing it through here too so we only setting it on specific shortcuts? As in should `convert_case` also be tied to the wider script editor? 

Otherwise looks good.

Comment (EricEzaM) [reply editor/plugins/script_text_editor.cpp:161]: The way it currently is is how it works in 3.X. All shortcuts available in the edit menus are usable when find in files is open. Also, I don't think you can set individual items on a popup menu to have a different shortcut context. The shortcuts get routed through the button, so the ctx of the button is applied to the popup menu items.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
