### PR TITLE
Fix `NOTIFICATION_SORT_CHILDREN` is called twice on startup

### LINKED ISSUE #92644: NOTIFICATION_SORT_CHILDREN is being called twice on start for all Containers.
### Tested versions

4.2 - 4.3.

### System information

win 10

### Issue description

Removing this line will fix the issue.
https://github.com/godotengine/godot/blob/705b7a0b0bd535c95e4e8fb439f3d84b3fb4f427/scene/gui/container.cpp#L181
all editor containers still looks and behaves as expected after removing this line.

Edit: it happens because NOTIFICATION_RESIZED is called before NOTIFICATION_ENTER_TREE.

### Steps to reproduce

Create a new container node, and attach a script to it.

```gdscript
extends Container


func _notification(what: int):
	if what == NOTIFICATION_SORT_CHILDREN:
		print("SORT CHILDREN")
	elif what == NOTIFICATION_RESIZED:
		print("RESIZED")
	elif what == NOTIFICATION_ENTER_TREE:
		print("ENTER TREE")

```

and run the scene, it will print SORT CHILDREN twice.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by WhalesState**
Fixes: https://github.com/godotengine/godot/issues/92644

### CODE REVIEW

File: scene/gui/container.cpp [hunk 1]
```diff
@@ -178,7 +178,6 @@ Vector<int> Container::get_allowed_size_flags_vertical() const {
 void Container::_notification(int p_what) {
 	switch (p_what) {
 		case NOTIFICATION_ENTER_TREE: {
-			pending_sort = false;
```
Comment (AThousandShips) [inline scene/gui/container.cpp:181]: This shouldn't change anything except in cases when a pending sort was fired before exiting the tree, it will be false already at any other time, I don't think this is the right fix

**Comment by WhalesState** [comment]
Is it better to rearrange them based on their call order?
image

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
