### PR TITLE
Fix PopupPanel and PopupMenu menu styles

### LINKED ISSUE #67657: ColorPicker popup has no border or shadow
### Godot version

Godot 4.0 beta 3

### System information

Windows 10

### Issue description

Recent changes have removed border and shadow from ColorPicker popup seen in-engine with the default theme. Without these it's hard to tell where the ColorPicker popup starts and ends, nor is it in line with the overall default theme as other popups do have border and shadow.

For example, if ColorPicker popup is opened on top of a Panel control, it become almost impossible to know where the ColorPicker popup ends and the Panel starts; as seen below:
cp old

Ideally ColorPicker popup should look as follows:
colorpicker new

### Steps to reproduce

1. Open Godot engine with default theme
2. Press on any ColorPickerButton in-engine

### Minimal reproduction project

N/A

### LINKED ISSUE #96517: Popup menus using PopupPanel has no default border like PopupMenu's have.
### Tested versions

Godot v4.4.dev1

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) 

### Issue description

Popup menus using PopupPanel has no default border like PopupMenu's have. 

This makes it hard to differentiate from the background:
ps_ss_before
ot_b4

Compared to Godot 3:

ps_3_1

ps_dock_before

### Steps to reproduce

Open popup menus like dock position, screen selector or color picker

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/96517
Edit: Fixes: https://github.com/godotengine/godot/issues/67657 (border part)

This makes popup menus using PopupPanel and PopupMenus have same base look, as it is in Godot 3. 

## Panel border

Adding a default border to the PopupPanel to make it easier to differentiate from the background. 
I believe this was removed in PR https://github.com/godotengine/godot/pull/45607 and then added back for PopupMenus in PR https://github.com/godotengine/godot/pull/48655 (also removed support for Border Size on PopupMenus)

Before:
ps_ss_before

After:
Screenshot_20240902_224247

### Border color

In Godot 3 both styles of popup menus uses the same border color, light on dark theme and dark border on light themes. 

Godot 3 example:
| 1        |2         
| ------------- |:-------------:| 
| ps_3_2     |ps_3_1 |

Currently Godot 4 uses dark border for PopupMenus and with Border Size in Editor Settings set to 1 or 2 PopupPanel uses a light border in dark themes.

Before: _with border size set_
| 1        |2         
| ------------- |:-------------:| 
|    Screenshot_20240902_133942 |ps_border_size_color_before |

After: _border size is set to deafult_
| 1        |2         
| ------------- |:-------------:| 
| Screenshot_20240903_000646 |Screenshot_20240902_224259 |

Because the PopupMenu border is visible by default I went with that color for both in this PR. 

Maybe there could be a editor setting for changing outline color, but that would need to be a proposal in that case. 

## Border Size

In Godot 3 both PopupPanel and PopupMenus uses the Border Size.

PopupPanel uses this already.

This PR also changes PopupMenus to use the editor setting Border Size for the outer border.

### Separator width

Due to the change of using Border Size the separator line in PopupMenus was much more obvious that it overlaps the outer border. So this was also changed

Before:
ps_sep_zoom_before

After:
Screenshot_20240902_224601

## Compact

Before:
ps_ap_compact_before

After:
Screenshot_20240903_003120

### CODE REVIEW

File: editor/window_wrapper.cpp [hunk 1]
```diff
@@ -454,14 +453,10 @@ ScreenSelect::ScreenSelect() {
 	// Create the popup.
 	const Size2 borders = Size2(4, 4) * EDSCALE;
 
-	popup = memnew(Popup);
+	popup = memnew(PopupPanel);
 	popup->connect("popup_hide", callable_mp(static_cast<BaseButton *>(this), &ScreenSelect::set_pressed).bind(false));
 	add_child(popup);
 
-	popup_background = memnew(Panel);
```
Comment (KoBeWi) [inline editor/window_wrapper.cpp:461]: You need to remove the declaration from `.h` file.

File: editor/themes/editor_theme_manager.cpp [hunk 2]
```diff
@@ -1331,17 +1334,17 @@ void EditorThemeManager::_populate_standard_styles(const Ref<EditorTheme> &p_the
 
 			Ref<StyleBoxLine> style_popup_separator(memnew(StyleBoxLine));
 			style_popup_separator->set_color(p_config.separator_color);
-			style_popup_separator->set_grow_begin(p_config.popup_margin - MAX(Math::round(EDSCALE), p_config.border_width));
-			style_popup_separator->set_grow_end(p_config.popup_margin - MAX(Math::round(EDSCALE), p_config.border_width));
+			style_popup_separator->set_grow_begin(Math::round(EDSCALE) - MAX(Math::round(EDSCALE), p_config.border_width));
```
Comment (KoBeWi) [inline editor/themes/editor_theme_manager.cpp:1337]: This looks sus. There is EDSCALE on both sides, so this has high chance of being 0. Though not sure what's the expected value here.

**Review by KoBeWi — APPROVED** [review]
Tested some popups and they visually look fine with default settings. The border is an improvement.

File: editor/window_wrapper.cpp (hunk 1 above)
Comment (clayjohn) [reply editor/window_wrapper.cpp:461]: @Giganzo This comment is the only thing keeping this PR from being merged. Will you have a chance to make the requested change sometime soon?

Comment (KoBeWi) [reply editor/window_wrapper.cpp:461]: Fixed.

**Comment by Repiteo** [comment]
Thanks!
