### PR TITLE
Optimize NodePath update when renaming or deleting nodes in the editor

### LINKED ISSUE #50267: Editor freeze when removing or renaming a node has very large scene tree
### Godot version

3.4.beta e5b32eda8d

### System information

Kubuntu 21.04 / AMD Ryzen 7 3700X 8-Core / Memory: 16 GiB / Radeon RX 570

### Issue description

Editor freeze when removing or renaming a node that has a very large hierarchy scene tree.

here's call stack after a few minutes wait.
```
SceneTreeDock::_update_node_path(const NodePath & p_root_path, NodePath & r_node_path, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames) (./editor/scene_tree_dock.cpp:1428)
SceneTreeDock::_check_node_path_recursive(const NodePath & p_root_path, Variant & r_variant, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames) (./editor/scene_tree_dock.cpp:1443)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1520)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::perform_node_renames(SceneTreeDock * const this, Node * p_base, List<Pair<NodePath, NodePath>, DefaultAllocator> * p_renames, Map<Ref<Animation>, Set<int, Comparator<int>, DefaultAllocator>, Comparator<Ref<Animation> >, DefaultAllocator> * r_rem_anims) (./editor/scene_tree_dock.cpp:1622)
SceneTreeDock::_node_prerenamed(SceneTreeDock * const this, Node * p_node, const String & p_new_name) (./editor/scene_tree_dock.cpp:1651)
MethodBind2<Node*, String const&>::call(MethodBind2<Node*, String const&> * const this, Object * p_object, const Variant ** p_args, int p_arg_count, Variant::CallError & r_error) (./core/method_bind.gen.inc:1523)
Object::call(Object * const this, const StringName & p_method, const Variant ** p_args, int p_argcount, Variant::CallError & r_error) (./core/object.cpp:918)
Object::emit_signal(Object * const this, const StringName & p_name, const Variant ** p_args, int p_argcount) (./core/object.cpp:1226)
Object::emit_signal(Object * const this, const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) (./core/object.cpp:1281)
SceneTreeEditor::_renamed(SceneTreeEditor * const this) (./editor/scene_tree_editor.cpp:812)
MethodBind0::call(MethodBind0 * const this, Object * p_object, const Variant ** p_args, int p_arg_count, Variant::CallError & r_error) (./core/method_bind.gen.inc:59)
Object::call(Object * const this, const StringName & p_method, const Variant ** p_args, int p_argcount, Variant::CallError & r_error) (./core/object.cpp:918)
MessageQueue::_call_function(MessageQueue * const this, Object * p_target, const StringName & p_func, const Variant * p_args, int p_argcount, bool p_show_error) (./core/message_queue.cpp:241)
MessageQueue::flush(MessageQueue * const this) (./core/message_queue.cpp:284)
SceneTree::iteration(SceneTree * const this, float p_time) (./scene/main/scene_tree.cpp:484)
Main::iteration() (./main/main.cpp:2075)
OS_X11::run(OS_X11 * const this) (./platform/x11/os_x11.cpp:3638)
main(int argc, char ** argv) (./platform/x11/godot_x11.cpp:55)
```

### Steps to reproduce

image

1. Download and open attached MRP
2. Delete or rename selected node as screenshot above

### Minimal reproduction project

[Delete node test.zip](https://github.com/godotengine/godot/files/6780335/Delete.node.test.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Fixes #50267 (regression from #49812).

Now the process uses a Map to lookup node pointers instead of iterating over all modified node paths in a list and comparing them one by one for each property to check.

The process also avoids checking properties with empty node paths and does an early exit on deleted nodes to avoid checking the node and its descendants.

Also made a minor change in NodePath::rel_path_to() to avoid resizing a Vector many times for long paths (with copy-on-write each time). Now it's down to 2 resize calls in any case.

I haven't made precise measurements of the performance difference, but with several thousands of nodes with node paths to update, it takes only a couple seconds (about the same it takes without the node path check) as opposed to freezing the editor completely (at least for several minutes).

Project used for tests on 3.x (modified MRP from #50267):
[Delete.node.test.zip](https://github.com/godotengine/godot/files/6793331/Delete.node.test.zip)

### CODE REVIEW

File: core/string/node_path.cpp [hunk 1]
```diff
@@ -240,19 +240,26 @@ NodePath NodePath::rel_path_to(const NodePath &p_np) const {
 	common_parent--;
 
 	Vector<StringName> relpath;
+	relpath.resize(src_dirs.size() + dst_dirs.size() + 1);
```
Comment (akien-mga) [inline core/string/node_path.cpp:243]: If you want to optimize further, you can probably avoid the two resizes by computing the exact size using `common_parent`.

Comment (pouleyKetchoupp) [reply core/string/node_path.cpp:243]: Yeah, given how `common_parent` is calculated I'm a bit afraid of edge cases, like `common_parent` greater than the size of `src_dir` or `dst_dirs` (and maybe other ones). So for now it seems like a good compromise to make sure it's no more than two allocations, without changing the logic too much.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
