### PR TITLE
C#: Resolve the hostfxr path using dotnet CLI

### LINKED ISSUE #75668: "Unable to load .NET runtime, specifically hostfxr" due to Godot not seeing manually installed .NET SDK
### Godot version

4.0.2

### System information

macOS Ventura 13.3 - M1 CPU

### Issue description

I just installed .Net SDK (tried with 7.0 and 6.0 and same result)
After download Godot .NET I opened it and then an error dialog appear the title

"Failed to Load .Net runtime" and the body
"Unable to load .NET runtime, specifically hostfxr"

I do not know what else I can do, I can access `dotnet` command from my terminal, so I guess it was installed right

### Steps to reproduce

- just download godot .net for mac
- try to open it

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by raulsntos**
Instead of trying to get the location of the dotnet CLI from PATH (which is unavailable in some platforms that don't allow reading environment variables), we execute the dotnet CLI to list the available SDKs and find the hostfxr location that way.

- Supersedes https://github.com/godotengine/godot/pull/74221
- Fixes https://github.com/godotengine/godot/issues/75668

### CODE REVIEW

**Comment by bruvzg** [comment]
> Supersedes https://github.com/godotengine/godot/pull/74221

This will do nothing on macOS (unless running for terminal, or with https://github.com/godotengine/godot/pull/81266), bundled macOS app will never have `dotnet` in PATH.

**Comment by raulsntos** [comment]
I would prefer this PR with https://github.com/godotengine/godot/pull/81266 to avoid hardcoding non-standard hostfxr locations.

**Comment by akien-mga** [comment]
#81266 was merged, so this could now be rebased / retested and should be mergeable.

**Review by akien-mga — APPROVED** [review]

File: modules/mono/mono_gd/gd_mono.cpp [hunk 1]
```diff
@@ -105,6 +106,60 @@ const char_t *get_data(const HostFxrCharString &p_char_str) {
...
+	godotsharp::SemVerParser sem_ver_parser;
+
+	godotsharp::SemVer latest_sdk_version;
+	String latest_sdk_path;
+
+	for (const String &sdk : sdks) {
+		// The format of the SDK lines is:
+		// 8.0.401 [/usr/share/dotnet/sdk]
+		String version_string = sdk.get_slice(" ", 0);
+		String path = sdk.get_slice(" ", 1);
```
Comment (AThousandShips) [inline modules/mono/mono_gd/gd_mono.cpp:132]:
```suggestion
		String version_string = sdk.get_slicec(' ', 0);
		String path = sdk.get_slicec(' ', 1);
```

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

File: modules/mono/mono_gd/gd_mono.cpp (hunk 1 above)
Comment (raulsntos) [reply modules/mono/mono_gd/gd_mono.cpp:132]: Sorry, I didn't get a chance to make the change before the PR got merged.
