### PR TITLE
Fix friction being in the correct if/else branch

### LINKED ISSUE #84009: ParticleProcessMaterial ignores the value set for `particle_flag_damping_as_friction`
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 Threads)

### Issue description

ParticleProcessMaterial will always generate a shader that uses the realistic friction formula for damping, wheter 'particle_flag_damping_as_friction' has been enabled or not.
It's pretty safe to assume that the bug got introduced with #79527.
Additionally, the check for that very flag seems to be inverted: https://github.com/godotengine/godot/blob/09946f79bd8215b2c6332de8821737580909a91c/scene/resources/particle_process_material.cpp#L961

### Steps to reproduce

- Create a GPUParticles3D node.
- Assign a new ParticleProcessMaterial to 'process_material'.
- Convert the ParticleProcessMaterial to a ShaderMaterial
- Open the shader and go to line 300 to see the "realistic friction" code, which shouldn't have been generated, as 'particle_flag_damping_as_friction' is disabled by default.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by QbieShay**
Closes https://github.com/godotengine/godot/issues/84009

Sorry for the regression

### CODE REVIEW

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -959,6 +959,15 @@ void ParticleProcessMaterial::_update_shader() {
 	code += "		// copied from previous version\n";
 	code += "		if (physics_params.damping > 0.0) {\n";
 	if (!particle_flags[PARTICLE_FLAG_DAMPING_AS_FRICTION]) {
+		code += "				float v = length(VELOCITY);\n";
+		code += "				v -= physics_params.damping * DELTA;\n";
+		code += "				if (v < 0.0) {\n";
+		code += "					VELOCITY = vec3(0.0);\n";
+		code += "				} else {\n";
+		code += "					VELOCITY = normalize(VELOCITY) * v;\n";
+		code += "				}\n";
```
Comment (akien-mga) [inline scene/resources/particle_process_material.cpp:968]:
```suggestion
		code += "			float v = length(VELOCITY);\n";
		code += "			v -= physics_params.damping * DELTA;\n";
		code += "			if (v < 0.0) {\n";
		code += "				VELOCITY = vec3(0.0);\n";
		code += "			} else {\n";
		code += "				VELOCITY = normalize(VELOCITY) * v;\n";
		code += "			}\n";
```

File: scene/resources/particle_process_material.cpp [hunk 2]
```diff
@@ -959,6 +959,15 @@ void ParticleProcessMaterial::_update_shader() {
...
+	} else {
+		code += "				if (length(VELOCITY) > 0.001){\n";
```
Comment (akien-mga) [inline scene/resources/particle_process_material.cpp:970]:
```suggestion
		code += "			if (length(VELOCITY) > 0.001) {\n";
```

File: scene/resources/particle_process_material.cpp [hunk 3]
```diff
@@ -968,9 +977,6 @@ void ParticleProcessMaterial::_update_shader() {
 		code += "				} else {\n";
 		code += "					VELOCITY = normalize(VELOCITY) * v;\n";
 		code += "				}\n";
-	} else {
-		code += "				if (length(VELOCITY) > 0.01){\n";
-		code += "					VELOCITY -= normalize(VELOCITY) * length(VELOCITY) * (physics_params.damping) * DELTA;\n";
 		code += "				}\n";
```
Comment (akien-mga) [inline scene/resources/particle_process_material.cpp:980]:
```suggestion
		code += "			}\n";
```

File: scene/resources/particle_process_material.cpp [hunk 4]
```diff
@@ -959,6 +959,15 @@ void ParticleProcessMaterial::_update_shader() {
 	code += "		// copied from previous version\n";
 	code += "		if (physics_params.damping > 0.0) {\n";
 	if (!particle_flags[PARTICLE_FLAG_DAMPING_AS_FRICTION]) {
+		code += "			float v = length(VELOCITY);\n";
+		code += "			v -= physics_params.damping * DELTA;\n";
+		code += "			if (v < 0.0) {\n";
+		code += "				VELOCITY = vec3(0.0);\n";
+		code += "			} else {\n";
+		code += "				VELOCITY = normalize(VELOCITY) * v;\n";
+		code += "			}\n";
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:968]: We should pull this out of the if/else conditional as it is shared by both approaches

**Comment by QbieShay** [comment]
Done!

File: scene/resources/particle_process_material.cpp [hunk 5]
```diff
@@ -958,21 +958,22 @@ void ParticleProcessMaterial::_update_shader() {
 	code += "	{\n";
 	code += "		// copied from previous version\n";
 	code += "		if (physics_params.damping > 0.0) {\n";
+	code += "			float v = length(VELOCITY);\n";
 	if (!particle_flags[PARTICLE_FLAG_DAMPING_AS_FRICTION]) {
-		code += "				float v = length(VELOCITY);\n";
+		code += "			v -= physics_params.damping * DELTA;\n";
+	} else {
+		code += "			if (length(VELOCITY) > 0.001) {\n";
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:965]:
```suggestion
		code += "			if (v > 0.001) {\n";
```

**Review by clayjohn — APPROVED** [review]
Looks good to me, i double checked the math and it seems to line up with the old damping. 

Tested locally and it seems fine to me. I'm not really knowledgeable enough to say if it is correct or not. 

I left one little nitpick to clean the code up a bit and reuse the ``v`` variable since we have it calculated anyway

**Comment by QbieShay** [comment]
Updated

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
