### PR TITLE
Hint fallback property as node when it is a node

### LINKED ISSUE #85492: C# Variable Exports get lost when the ".godot" folder is deleted
### Godot version

4.2.rc2

### System information

Godot v4.2.rc2.mono - macOS 14.2.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

In a minimal project with a single C# export, despite the reference being stored in the .tscn file, it gets lost when the `.godot` folder is deleted.  
Specifically: When both `.godot/exported` and `.godot/mono` are deleted, the issue appears.

It means that this issue will appear when simply storing a Godot project on a Git repo, and cloning that repo to another machine. That machine will be producing broken builds.

When starting the Godot editor in such a state, the variable export will not even appear at first. Hitting the "Run Project" button will make it appear (and the reference *looks* intact), but the internal state of the editor will still be broken in a variety of ways :
- Clicking on Project > Reload Current Project will make the variable export be unassigned.
- Saving the scene will make every reference be `NodePath("")`.
- Any exported build will still be broken.

This issue has succesfully been succesfully reproduced on three separate machines (Windows + macOS, x86 + ARM):
- `Godot v4.2.rc2.mono - macOS 14.2.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)`
- `Godot v4.2.rc2.mono - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 30.0.101.1404) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)`
- `Godot v4.2.rc2.mono - macOS 13.4.1 - Vulkan (Forward+) - integrated Intel(R) Iris(TM) Plus Graphics - Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 Threads)`

This issue also happens in Godot `v4.2.rc1`, and broken builds stay broken no matter which platform it is exported to.

This issue is a problem since every reference from every scene needs to be restored for every machine running the project, unless `.godot/exported` is actually kept as an exclusion in the `.gitignore` file.

### Steps to reproduce

The attached minimal reproduction project only contains a single 2D scene with a Label and a script attached to the root node. That script changes the label's contents from "default text" to "C# actually works"

(As per this repo's rules, the `.godot` folder has not been included, which means that the project will be broken out of the box.)

With the project downloaded as-is, the C# variable export will not be visible in the inspector tab, while focusing the root node.
image

Hitting "Run Project" will make the exported variable show up, and *visually* pointing to the Label in the scene; but the running project will still show "default text", as if the C# script did not work. No errors are shown in the Output nor Debugger.
image

After that, exporting the project will produce a broken build, with the variable export not being actually filled.
image

Clicking on Project > Reload Current Project will now show that the reference has *really* been lost.
image

From that point, re-assigning the label again and saving will fix the project, and exported builds will be functional as expected.

However, closing the editor, and deleting the entire `.godot` folder (OR only deleting `.godot/exported` and `.godot/mono`), and re-opening the project, will restore it into a broken state. Exported builds will not work, and saving a scene will erase every export references to `NodePath("")`, as explained above in the issue description above.

### Minimal reproduction project

[TestExport.zip](https://github.com/godotengine/godot/files/13495048/TestExport.zip)

### PR DESCRIPTION
**Pull request by paulloz**
Fixes #85492

### A comprehensive (I hope) step by step of what is happening.

* Let's make a new scene with a `Node` at the top.
* Attach the following script to the root of the scene.
   ```cs
   using Godot;
   public partial class MyNode : Node
   {
	   [Export]
	   public Sprite2D MySprite { get; private set; }
	
	   public override void _Ready()
	   {
		   GD.Print($"{nameof(MySprite)}: {MySprite?.GetPath()}");
	   }
   }
   ```
* Add a `Sprite2D` in the scene, build, and assign that `Sprite2D` to our `MySprite` property.
* Run the scene, and witness the following output.
   ```
   MySprite: /root/MyNode/MySprite2D
   ```
* At that point, if we look at the `.tscn`, it should look like this.
   ```ini
   [gd_scene load_steps=2 format=3 uid="uid://c7ybg78eykspy"]

   [ext_resource type="Script" path="res://MyNode.cs" id="1_u8846"]

   [node name="MyNode" type="Node" node_paths=PackedStringArray("MySprite")]
   script = ExtResource("1_u8846")
   MySprite = NodePath("MySprite2D")

   [node name="MySprite2D" type="Sprite2D" parent="."]
   ```
* Close all the open scenes, scripts, etc.
* Clean the C# solution.
* Close and reopen Godot, reopen the scene.
* Do not rebuild the C# solution, run the game, and witness the output.
   ```
   MySprite: 
   ```
   ```
   E 0:00:03:0953   NativeCalls.cs:1026 @ Godot.NodePath Godot.NativeCalls.godot_icall_0_112(nint, nint): Cannot get path of node as it is not in a scene tree.
   ```
* At that point, if we look at the `.tscn`, it will look like this.
   ```ini
   [gd_scene load_steps=2 format=3 uid="uid://c7ybg78eykspy"]

   [ext_resource type="Script" path="res://MyNode.cs" id="1_u8846"]

   [node name="MyNode" type="Node"]
   script = ExtResource("1_u8846")
   MySprite = Object(Sprite2D,"_import_path":NodePath(""),"unique_name_in_owner":false,"process_mode":0,"process_priority":0,"process_physics_priority":0,"process_thread_group":0,"auto_translate_mode":0,"editor_description":"","visible":true,"modulate":Color(1, 1, 1, 1),"self_modulate":Color(1, 1, 1, 1),"show_behind_parent":false,"top_level":false,"clip_children":0,"light_mask":1,"visibility_layer":1,"z_index":0,"z_as_relative":true,"y_sort_enabled":false,"texture_filter":0,"texture_repeat":0,"material":null,"use_parent_material":false,"position":Vector2(0, 0),"rotation":0.0,"scale":Vector2(1, 1),"skew":0.0,"texture":null,"centered":true,"offset":Vector2(0, 0),"flip_h":false,"flip_v":false,"hframes":1,"vframes":1,"frame":0,"region_enabled":false,"region_rect":Rect2(0, 0, 0, 0),"region_filter_clip_enabled":false,"script":null)


   [node name="MySprite2D" type="Sprite2D" parent="."]
   ```
* We can see the `Sprite2D` has been serialized inline, instead of via its path. You can fiddle around by, e.g., setting metadata on the `Sprite2D` and see it is indeed the right node being serialized there, only not in the right way.

### My understanding of what is happening

When running a project, the process goes vaguely like this:
1. Save (and so, serialize) all the open scenes.
2. Call all the `_build` callbacks for all plugins (and so, the one from the .NET module).
3. Run the project.

In C#, we rely on the built assembly to retrieve information about exported properties. If the assembly is not built (e.g. the user manually cleaned it, the user just cloned their repo on another computer, etc.). We do not have information about exported properties available. When this is the case, Godot relies on fallbacks that are set [here](https://github.com/godotengine/godot/blob/a07dd0d6a520723c4838fb4b65461a16b7a50f90/core/object/script_language.cpp#L693-L718). This explains how we actually serialize the right node still. But this process always sets the exported property's hint to `PROPERTY_HINT_NONE`, which explains why it is serialized inline (`PROPERTY_HINT_NODE_TYPE` is what triggers the serialization as path).

The fix assumes that setting a fallback to a value of type `OBJECT` that is a `Node` means we want to hint it as `PROPERTY_HINT_NODE_TYPE`.

### CODE REVIEW

File: core/object/script_language.cpp [hunk 1]
```diff
@@ -708,7 +708,12 @@ void PlaceHolderScriptInstance::property_set_fallback(const StringName &p_name,
 			}
 		}
 		if (!found) {
-			properties.push_back(PropertyInfo(p_value.get_type(), p_name, PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NO_EDITOR | PROPERTY_USAGE_SCRIPT_VARIABLE));
+			const Variant::Type type = p_value.get_type();
+			PropertyHint hint = PROPERTY_HINT_NONE;
+			if (type == Variant::OBJECT && ((Object *)p_value)->is_class("Node")) {
```
Comment (AThousandShips) [inline core/object/script_language.cpp:713]: This isn't guaranteed to be safe I'd say, it could be `nullptr` or freed, so I'd use:
```suggestion
			Object *obj = p_value.get_validated_object();
			if (obj && obj->is_class("Node")) {
```

Comment (paulloz) [reply core/object/script_language.cpp]: Thanks for always noticing my mistakes 🙈

**Review by akien-mga — APPROVED** [review]
Thanks for the detailed description. It makes a lot of sense to me.

I think this solution is good, we do want to keep hinting this as a Node if we can get that info.

As discussed on chat, it might be worth evaluating whether compiling assemblies before saving scenes would also be good to do. I think a risk there is that some unsaved scene changes may impact which assemblies should be compiled?

**Comment by paulloz** [comment]
Yes, although I don't think issues about not being sync between the assembly and the scenes are that common, since if you purposefully change something that'd affect the scene (add an export for instance), you'd need to rebuild to be able to assign a value. 

The bigger issue we fix here is the current process being destructive for the content of the scene. Once you click run, the only option too retrieve data would be your VCS.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
