### PR TITLE
Android: Fix save issue when using native file dialog

### LINKED ISSUE #107206: File save issue using the native file dialog on Android
### Tested versions

Issue is present since Native file diaog support is added for android in https://github.com/godotengine/godot/pull/98350

- Reproducible in 4.4.stable
- Reproducible in master

### System information

null

### Issue description

Android allows saving files in `Downloads` and `Documents` without any permission. It's works as expected if saving file directly with filepath but throws error `ERR_FILE_NOT_FOUND` if using the native file dialog to open save file UI and then try to save using the following code:
```gdscript
func _on_file_dialog_file_selected(path: String) -> void:
	print("file path: ", path)
	var file = FileAccess.open(path, FileAccess.WRITE)
	if file:
		file.store_string("This is a test.")
	else:
		print("ERROR opening file: ", FileAccess.get_open_error())
```

### Steps to reproduce

null

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/20625914/test1.zip)

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes the issue where saving a file without `MANAGE_EXTERNAL_STORAGE` permission using the `native file dialog` to get the file path causes the `ERR_FILE_NOT_FOUND` error.

---
A blank file gets created by default when using the save dialog, which isn't available to the Godot app without required permission (MANAGE_EXTERNAL_STORAGE) and when trying to access that file using `FileAccess`(mediastore api) with the path returned by `FileDialog`, results in `ERR_FILE_NOT_FOUND` error (as shown in the linked issue description).
There's no way to stop this blank file creation, so this PR immediately deletes the blank file instead.

This change also brings Android's behavior in line with desktop platforms, where no blank file is created when saving using the native file dialog.

Fixes https://github.com/godotengine/godot/issues/107206

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/io/FilePicker.kt [hunk 1]
```diff
@@ -101,6 +102,10 @@ internal class FilePicker {
 							} else {
 								Log.d(TAG, "null filepath URI: $it")
 							}
+
+							if (requestCode == FILE_SAVE_REQUEST) {
+								DocumentsContract.deleteDocument(context.contentResolver, it)
+							}
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/io/FilePicker.kt:108]: Shouldn't this logic also be replicated in the block above when `clipData != null`?

Comment (syntaxerror247) [reply platform/android/java/lib/src/org/godotengine/godot/io/FilePicker.kt:108]: No, because when saving a file, only a single URI is returned, there’s no support for saving multiple files at once. That only handle multiple file opening where multiple URI is included in clipData.

**Review by m4gr3d — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
