### PR TITLE
[mbedTLS] Integrate TLS handshake defragmentation PR

### LINKED ISSUE #101910: [4.4 beta 1] TLS Handshake Error with Godot HTTPRequest
### Tested versions

4.4 beta 1 

### System information

Windows 11 - Godot 4.4 beta 1 - Vulkan (Mobile)

### Issue description

I’m encountering a TLS handshake error when trying to make a request to https://graph.oculus.com/ using Godot's HTTPRequest.

* Requests to https://www.google.com/ work without any issues.
* Python's requests library can access the URL without any problems.
* The same https://graph.oculus.com/ URL works correctly in Postman.
* I attempted to create a certificate bundle as well, but it was unsuccessful.
* This issue appears to be specific to Godot.

CPP ERROR:

E 0:00:01:0639   StreamPeerMbedTLS::_do_handshake: TLS handshake error: -28800
  <C++ Source>   modules\mbedtls\stream_peer_mbedtls.cpp:88 @ StreamPeerMbedTLS::_do_handshake()

### Steps to reproduce

* Create simple project
* Add a HTTPRequest node
* Add script:
```
extends Node3D

@onready var http: HTTPRequest = $HTTPRequest

func _ready() -> void:
	http.request("https://graph.oculus.com/")
	print(await http.request_completed)
```
* Run

### Minimal reproduction project (MRP)

[teste-vr.zip](https://github.com/user-attachments/files/18505403/teste-vr.zip)

### PR DESCRIPTION
**Pull request by Faless**
Upstream PR https://github.com/Mbed-TLS/mbedtls/pull/9981 has been merged.

Fixes https://github.com/godotengine/godot/issues/101910 while leaving TLS 1.3 support by default.

Added an extra commit to enable TLSv1.3 support by default for editor and project by default.

### CODE REVIEW

File: modules/mbedtls/tls_context_mbedtls.cpp [hunk 1]
```diff
@@ -32,6 +32,10 @@
 
 #include "core/config/project_settings.h"
 
+#ifdef TOOLS_ENABLED
+#include "editor/editor_settings.h"
+#endif // TOOLS_ENABLED
```
Comment (akien-mga) [inline modules/mbedtls/tls_context_mbedtls.cpp:37]: Technically not editor code shouldn't include editor headers (see #53295), but we have quite a few exceptions.
In this case I don't see any easy way to avoid this, it would need to be passed as a argument from where mbedtls is used in the editor, and that seems worse than allowing this exception.

File: modules/mbedtls/tls_context_mbedtls.cpp [hunk 2]
```diff
@@ -197,8 +210,17 @@ Error TLSContextMbedTLS::init_client(int p_transport, const String &p_hostname,
...
+	if (Engine::get_singleton()->is_editor_hint()) {
+		if (!EditorSettings::get_singleton()->get_setting("network/tls/enable_tls_v1.3").operator bool()) {
+			mbedtls_ssl_conf_max_tls_version(&conf, MBEDTLS_SSL_VERSION_TLS1_2);
+		}
+	} else
+#endif
+	{
+		if (!GLOBAL_GET("network/tls/enable_tls_v1.3").operator bool()) {
+			mbedtls_ssl_conf_max_tls_version(&conf, MBEDTLS_SSL_VERSION_TLS1_2);
+		}
```
Comment (akien-mga) [inline modules/mbedtls/tls_context_mbedtls.cpp:223]: In the past we had issues where project settings would affect the editor. Might be worth checking here whether the project setting isn't overriding the first branch for editor code.

I.e. if the editor setting is `true`, but the project setting is `false`, does it wrongly restrict editor TLS to v1.2?

**Review by akien-mga — APPROVED** [review]

File: modules/mbedtls/tls_context_mbedtls.cpp (hunk 2 above)
Comment (akien-mga) [reply modules/mbedtls/tls_context_mbedtls.cpp:223]: Tested with:
```diff
diff --git a/modules/mbedtls/tls_context_mbedtls.cpp b/modules/mbedtls/tls_context_mbedtls.cpp
index 01e52efc44..339cb75bdd 100644
--- a/modules/mbedtls/tls_context_mbedtls.cpp
+++ b/modules/mbedtls/tls_context_mbedtls.cpp
@@ -155,12 +155,14 @@ Error TLSContextMbedTLS::init_server(int p_transport, Ref<TLSOptions> p_options,
 #ifdef TOOLS_ENABLED
 	if (Engine::get_singleton()->is_editor_hint()) {
 		if (!EditorSettings::get_singleton()->get_setting("network/tls/enable_tls_v1.3").operator bool()) {
+			print_line("Editor: Restrict TLS to v1.2");
 			mbedtls_ssl_conf_max_tls_version(&conf, MBEDTLS_SSL_VERSION_TLS1_2);
 		}
 	} else
 #endif
 	{
 		if (!GLOBAL_GET("network/tls/enable_tls_v1.3").operator bool()) {
+			print_line("Project: Restrict TLS to v1.2");
 			mbedtls_ssl_conf_max_tls_version(&conf, MBEDTLS_SSL_VERSION_TLS1_2);
 		}
 	}
@@ -213,12 +215,14 @@ Error TLSContextMbedTLS::init_client(int p_transport, const String &p_hostname,
 #ifdef TOOLS_ENABLED
 	if (Engine::get_singleton()->is_editor_hint()) {
 		if (!EditorSettings::get_singleton()->get_setting("network/tls/enable_tls_v1.3").operator bool()) {
+			print_line("Editor: Restrict TLS to v1.2");
 			mbedtls_ssl_conf_max_tls_version(&conf, MBEDTLS_SSL_VERSION_TLS1_2);
 		}
 	} else
 #endif
 	{
 		if (!GLOBAL_GET("network/tls/enable_tls_v1.3").operator bool()) {
+			print_line("Project: Restrict TLS to v1.2");
 			mbedtls_ssl_conf_max_tls_version(&conf, MBEDTLS_SSL_VERSION_TLS1_2);
 		}
 	}
```

When opening the assetlib in a project where both the editor and project settings are disabled, only the "Editor" message gets printed, so it's working as intended.

**Comment by akien-mga** [comment]
Thanks!
