### PR TITLE
Fix blurry items on `PopupMenu` when `v_separation` has an odd value

### LINKED ISSUE #112557: Blurry icons and highlight rectangle in menus using modern theme
### Tested versions

- Reproducible in 4.6-dev3
- Not reproducible in 4.4

### System information

Ubuntu 24.04.2 LTS

### Issue description

Using the new modern theme on a classic full HD, non-hidpi monitor, the icons in the menus are blurry, as well as the highlight rectangle edges. This happens on the Default and Compact spacing presets; the Spacious one seems to display the icons correctly.

The classic theme displays the icons correctly in all cases.

The blur seems on the vertical axis, as if everything was off a half-pixel vertically. Horizontally, the pixel alignment seems correct.

My guess is that the theme was developed on a Retina / Hidpi screen and not tested on non-hidpi displays.

Here is the rendering of the modern theme with the three spacing settings. You can see that the round radio button icons are kinda squished vertically and the top/bottom edges of the highlight rectangle are blurry, unless in the Spacious case.

Image

Image

Image

Detailed view

Buggy situation

Image

Good example of non-blurry situation

Image

Image

Here is how it looks on the standard setting with the classic theme

Image

The blur effect is also visible on the icons and checkboxes of the top menu

Image

Image

Additionally, the vertical alignment of the highlight rectangle and separators seems off in this example. I would expect to have an equivalent spacing between the separator and the highlight edges

Image

Image

### Steps to reproduce

Use a non-hidpi monitor or laptop, with 1920x1080 resolution and OS scaling set at 100%.

Start on a fresh project.

Go to the Editor Settings and play with the spacing presets menu to see the difference.

Switch to the classic theme to see too, the issue only happens in the modern theme.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #112557.

### CODE REVIEW

**Comment by davthedev** [comment]
Good point. It offsets the icon to the nearest pixel.

The modern theme definition itself should also be reviewed, as there is a good number of non-integer multiplications of EDSCALE that are not rounded/floored afterwards. Otherwise there will remain a slight decentering of the contents of some items. Perhaps for another fix!

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -1200,7 +1200,7 @@ void PopupMenu::_notification(int p_what) {
 			for (int i = 0; i < items.size(); i++) {
 				const Item &item = items.write[i];
 
-				ofs.y += i > 0 ? theme_cache.v_separation : (float)theme_cache.v_separation / 2;
+				ofs.y += i > 0 ? theme_cache.v_separation : theme_cache.v_separation / 2;
```
Comment (bruvzg) [inline scene/gui/popup_menu.cpp]: Min. size calculations use `theme_cache.v_separation` in one step, so this might lead to some discrepancy between drawn items and min.size, since offset will lose or gain one pixel per item depending on rounding direction.

```suggestion
				ofs.y += i > 0 ? theme_cache.v_separation : theme_cache.v_separation - (theme_cache.v_separation / 2);
```

Comment (YeldhamDev) [reply scene/gui/popup_menu.cpp]: Done.

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
