### PR TITLE
Fix crash for classes without an icon

### LINKED ISSUE #112304: Crash when opening help page probably caused by it failing to find the icon
### Tested versions

I tracked it down to being introduced in commit 72a1b5a2e5632ad352f7f7dffd748a38931d9143
which merges PR #108607 from @beicause 

### System information

Godot v4.6.dev (72a1b5a2e) - Windows 11 (build 22631) - Single-window, 4 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2080 SUPER (NVIDIA; 32.0.15.8157) - 12th Gen Intel(R) Core(TM) i9-12900K (24 threads) - 63.78 GiB memory

### Issue description

The editor crashes when opening certain pages that don't have icons in the integrated documentation/help viewer.

### Steps to reproduce

Help -> Search Help -> double click  `@GDScript` or `@GlobalScope` -> crash

### Minimal reproduction project (MRP)

This is not needed. see steps above.

### PR DESCRIPTION
**Pull request by AdvanceControl**
Fixes #112304 
The editor would crash due to a null pointer dereference in EditorHelp::_add_type_icon when trying to display the help page for a class that does not have a registered icon (e.g., internal types like `@GlobalScope`).

This PR adds null check to ``EditorHelp::_add_type_icon``

### CODE REVIEW

**Comment by takethebait** [comment]
Ran into this just now. This does fix the issue for me. Happend when Ctrl + clicking on `preload` in a script.

File: editor/doc/editor_help.cpp [hunk 1]
```diff
@@ -471,6 +471,9 @@ void EditorHelp::_add_type(const String &p_type, const String &p_enum, bool p_is
 
 void EditorHelp::_add_type_icon(const String &p_type, int p_size, const String &p_fallback) {
 	Ref<Texture2D> icon = EditorNode::get_singleton()->get_class_icon(p_type, p_fallback);
+	if (icon.is_null()) {
+		return;
```
Comment (bruvzg) [inline editor/doc/editor_help.cpp]:
```suggestion
		icon = EditorNode::get_singleton()->get_class_icon("Object");
		ERR_FAIL_NULL(icon);
```
To match behavior to be the as before the change that introduced the crash (fallback to default Object "cube" icon).

Comment (AThousandShips) [reply editor/doc/editor_help.cpp]: It should be `ERR_FAIL_COND(icon.is_null());` in this case, you can't use `ERR_FAIL_NULL` here

Comment (bruvzg) [reply editor/doc/editor_help.cpp]: Not having an icon will leave an empty space (two spaces around the missing icon), so having it will make help page look more consistent.

Comment (AdvanceControl) [reply editor/doc/editor_help.cpp]: The crash is caused by `@GDScript` and `@GlobalScope` lacking an icon. Therefore, if we want to handle this error at this stage, we have two options: either implement special handling for these internal names, or assign them a fallback icon.

**Review by bruvzg — APPROVED** [review]
Since there's no consensus about the icon, it's fine to keep it as is, since it is fixing the crash. We can decide which icon to use/not use later.

File: editor/doc/editor_help.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/doc/editor_help.cpp]: I agree that we should fallback to `Object` again, like before. I'll amend this so we can merge for 4.6-dev3.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
