### PR TITLE
Input - fix just pressed and released with short presses

### LINKED ISSUE #73339: `Input.is_action_just_pressed` dropping inputs at low framerates
### Godot version

v4.0.rc2.official [d2699dc7a]

### Issue description

I chased something down a rabbit hole again.

So my understanding of `Input.is_action_just_pressed` was that it returned true if there was an input event that came in at the beginning of a given frame. This, generally, is true. I was concerned about doubling up in heavy load cases with multiple physics frames, but that turned out to be unwarranted: It returns true for the first `_physics_process` of the frame, but false for all others, and it returns true in that frame's `_process`. All good, no problems here, grats to whoever wrote that code. Things got weird when I decided to clamp the FPS and physics ticks to low values.

So here's the best way I can describe the behaviour: `Input._is_action_just_pressed` seems to return true only when the action is actually being held down. Inversely, `Input._is_action_just_released` only returns true when an action is _not_ being held.

I realize that may sound blistering obvious, but essentially, here's a sequence of events that can happen:

Input processing begins
An event is found stating an action is pressed
An event is found stating that same action is released
the frame starts
`Input.is_action_just_pressed` is called
The action was pressed prior to the current frame
However, the action is not currently being pressed
Thus, `Input.is_action_just_pressed` returns false

Essentially, actions being released clears the criteria for `is_just_pressed`. Curiously, the inverse is also true: If you release-and-press-again between frames, it you won't get a call to `Input.is_action_just_released`.

So here's what I think is happening without actually trying to dredge through the source:

The impression I'm getting is that `Input.is_action_just_pressed` and `Input.is_action_just_released` is checking for "current" values, and them comparing those values to what they were the last time `_process` or `_physics_process` was called. This works in _most_ cases, but it can break down if the internal state of an action toggles an even number of times between frames. Admittedly, this is probably not _that_ critical an issue, but it's possible that in certain situations it could lead to dropped inputs if people are doing `just` checks on action presses that are faster than the current framerate.

**Edit: Upon further investigation, I don't think pressed and released are based solely on the state of the button last frame, but there still does seem to be a constraint where just-pressed and just-released aren't triggering unless the action is also up/down.** 

Again, I don't know what the source looks like, but I feel like ideally you'd have `pressed` and `released` be independent boolean sets that are cleared at the end of each frame and then set based on whatever input events were just received. You'd occasionally get delayed presses, and sometimes you'd have `pressed` and `released` both returning true on the same frame, but you'd never have dropped inputs. It might also provide a path to dealing with the infamous mouse wheel events.. but I get ahead of myself.

If I've learned only one thing from this, it's that I really should be putting my input checks in `_unhandled_input` instead of `_physics_process`.

### Steps to reproduce

The clearest way I've found to observe this in action is with aggressive use of print statements and the FPS limiter and physics ticks set to 1. That way you can easily press and release an action in the same frame, within the frame.

### MRP ###

[input_pressed.zip](https://github.com/godotengine/godot/files/10751497/input_pressed.zip)

So this is a crude tool that monitors the input of `ui_accept` (bound to space/enter by default I believe) and prints the output at a framerate of 1. If you don't want to bother downloading, the relevant script is here:

```GDScript
extends Node

func _init():
	Engine.max_fps = 1

func _input(event):
	var frame := Engine.get_frames_drawn()
	if event.is_action_pressed("ui_accept"):
		print("EVENT: \"ui_accept\" pressed")
	if event.is_action_released("ui_accept"):
		print("EVENT: \"ui_accept\" released")

var input_cache : bool = false

func _process(delta):
	var frame := Engine.get_frames_drawn()
	var pressed := Input.is_action_pressed("ui_accept")
	var just_pressed := Input.is_action_just_pressed("ui_accept")
	var just_released := Input.is_action_just_released("ui_accept")
	print("--- Frame %s ---" % frame)
	print("Last frame pressed: %s" % input_cache)
	print("Input.is_action_pressed(\"ui_accept\") == %s" % pressed)
	print("Input.is_action_just_pressed(\"ui_accept\") == %s" % just_pressed)
	print("Input.is_action_just_released(\"ui_accept\") == %s" % just_released)
	print("\n")
	input_cache = pressed
```

### PR DESCRIPTION
**Pull request by lawnjelly**
Previously if an action was both pressed and released on the same tick or frame, `is_action_just_pressed()` would return false, resulting in missed input.

This PR separately the timestamp for pressing and releasing so each can be tested independently.

Fixes #73339
Master version of #77040

## Notes
* There are multiple ways of addressing this bug, so expecting some bikeshedding.
* It is possible to emulate the old (buggy) behaviour with a combination of `is_action_just_pressed()` and `is_action_pressed()`.
* Alternative approaches include adding new functions specifically to cope with this (but that would mean changing game code). An alternative function could e.g. report the number of pressed / releases in the current tick / frame, but that probably would not be required.
* This bug causes lost input particular on Android (because of the separate input thread), and also particularly at low tick and frame rates.
* Now includes a project setting to revert to the old behaviour (I'm not totally sure this is needed, but am happy either way).

## Example Project
See #77040 for demo project.

_Before:_
```
frame 1
frame 9
released tick 9
frame 17
frame 25
frame 23
```
_After:_
```
frame 1
frame 9
pressed tick 9
released tick 9
frame 17
```

### CODE REVIEW

File: core/input/input.cpp [hunk 1]
```diff
@@ -286,7 +286,7 @@ bool Input::is_action_pressed(const StringName &p_action, bool p_exact) const {
 	return action_state.has(p_action) && action_state[p_action].pressed && (p_exact ? action_state[p_action].exact : true);
 }
 
-bool Input::is_action_just_pressed(const StringName &p_action, bool p_exact) const {
+bool Input::is_action_just_pressed(const StringName &p_action, bool p_exact, bool p_current) const {
```
Comment (RandomShaper) [inline core/input/input.cpp:289]: I can't see the difference between calling this with `p_current = true` and calling `is_action_pressed()`.

File: core/input/input.cpp [hunk 2]
```diff
@@ -298,13 +298,13 @@ bool Input::is_action_just_pressed(const StringName &p_action, bool p_exact) con
 	}
 
 	if (Engine::get_singleton()->is_in_physics_frame()) {
-		return E->value.pressed && E->value.physics_frame == Engine::get_singleton()->get_physics_frames();
+		return p_current ? E->value.pressed : true && E->value.pressed_physics_frame == Engine::get_singleton()->get_physics_frames();
```
Comment (RandomShaper) [inline core/input/input.cpp:301]: Those `true &&` look like left-behinds of code iteration.

Comment (lawnjelly) [reply core/input/input.cpp:301]: Ah yes this must have been a mistake when refactoring (blame my old eyesight! :smile: )

I'll change this, but on relooking after a month gap, I'm now tending towards breaking compat for this bug and removing the `p_current` argument. I'm struggling to think of when users might want to have `is_action_just_pressed()` not trigger when they have just pressed the action, and it is possible to mimic the old case anyway. Will change.

**Comment by lawnjelly** [comment]
@RandomShaper : On reflection I went for the approach of fixing the bug without introducing the extra parameter to give the old behaviour. The old behaviour can be emulated by calling:
```
If Input.is_action_just_pressed() && Input.is_action_pressed():
```
But I'm struggling to think of many situations where this would be wanted. Users will likely want to simply know whether the action has been pressed recently.

File: core/input/input.cpp [hunk 3]
```diff
@@ -813,29 +818,27 @@ Point2i Input::warp_mouse_motion(const Ref<InputEventMouseMotion> &p_motion, con
 }
 
 void Input::action_press(const StringName &p_action, float p_strength) {
-	Action action;
+	// Create or retrieve existing action.
+	Action &action = action_state[p_action];
```
Comment (lawnjelly) [inline core/input/input.cpp:822]: Note this is assuming that the usage here is single threaded, and the previous deferring the setting of the action wasn't some attempt at thread protection. If the `action_state` was meant to be thread safe it should probably be done properly with e.g. mutex.

Comment (RandomShaper) [reply core/input/input.cpp:822]: I think it's fine that `Input` is thread-unsafe (i.e., only OK from the main thread) in general (besides `parse_input_event()`. At some point the thread guards should be uncoupled from `Node` so most singletons methods' can be decorated as only-safe-from-main and users get to know if they are doing something risky.

**Comment by RandomShaper** [comment]
> But I'm struggling to think of many situations where this would be wanted. Users will likely want to simply know whether the action has been pressed recently.

My only concern is how this change can break the assumption that just-pressed means currently pressed and the same goes for unpressed. If I'm not mistaken, with this PR it can be both true than an action has been just both pressed and unpressed and you then have to check the current state to know which happened later.

**Comment by lawnjelly** [comment]
> My only concern is how this change can break the assumption that just-pressed means currently pressed and the same goes for unpressed. If I'm not mistaken, with this PR it can be both true than an action has been just both pressed and unpressed and you then have to check the current state to know which happened later.

This is why I originally had the extra parameter to try and emphasize this, but I suspect it would cause more confusion than it solves. I'm not sure there is an easy way to solve this - I would welcome ideas. It is more of a historical oversight I imagine, with the original implementer not considering this problem.

Should `is_action_just_pressed()` imply that it is currently pressed? Perhaps `was_action_just_pressed()` might have been better wording, because it hints that it might no longer be pressed. We could e.g. add an extra function `was_action_just_pressed()` and deprecate the old one, but that might be confusing to users, versus just fixing what effectively is a bug. But that is why bikeshedding is useful here to get a consensus.

One thing is certain - the current system of only returning true if currently pressed just plain fails to report keypresses in some situations. If you are using this to e.g. jump, or drop a bomb, this can be a massive problem, so we have a duty to fix this in some way, and many (perhaps all?) of these will involve some degree of compromise.

**Comment by adamscott** [comment]
Usually, users that check `is_action_just_pressed()` just care if the button was pressed, like to apply or not jump velocity. So the fact that the button is still pressed doesn't impact anything, I think.



> @RandomShaper : On reflection I went for the approach of fixing the bug without introducing the extra parameter to give the old behaviour. The old behaviour can be emulated by calling:
> 
> ```
> If Input.is_action_just_pressed() && Input.is_action_pressed():
> ```
> 
> But I'm struggling to think of many situations where this would be wanted. Users will likely want to simply know whether the action has been pressed recently.

The fact that the old behavior can be emulated quite easily makes me think that it's the correct thing to do.

**Comment by RandomShaper** [comment]
```
var state = STATE_IDLE

func _process();
    match state:
        STATE_IDLE:
            if is_action_just_pressed("jump"):
                state = STATE_JUMP
        STATE_JUMP:
            y -= 5
            if is_action_just_released("jump"):
                state = STATE_IDLE
```

A script in a game could look like that. (Not correct GDScript syntax, but enough for the purposes.)

After the change, the `is_action_just_released("jump")` should be changed to `is_action_released("jump")`, right? I can acknowledge that should have been the function used in the first place, but I can image some scripts out there are written that way. So, either the change should be made very explicit in the release notes or a project setting should be added, defaulting to the old behavior, but explicitly enabled in `project.godot` files created from now on (as we did other times).

**Comment by lawnjelly** [comment]
> A script in a game could look like that. (Not correct GDScript syntax, but enough for the purposes.)

Just to point out this is a buggy script - it neglects the possibility that a key can be both pressed and released on the same frame. It would probably produce bugs with the current version, given that input can currently be missed. But yes, it is possible there could be scripts that depend on the current behaviour.

We could have a backup to the old behaviour with a project setting and normally I go straight for this with a project setting. However in this case I'm not _totally_ convinced it would be necessary. :thinking:

The old behaviour was flat out wrong, and likely to be capable of causing errors for anyone depending on it (even though it may appear to work in most circumstances, it would fail at e.g. low frame rates). So we could argue this should be the "the straw that broke the camel's back" for them to fix their script. But I am happy to have a backup path if this is generally preferred, I do appreciate that people sometimes don't want to deal with fixing things properly (if they aren't aware that it is broken).

> After the change, the is_action_just_released("jump") should be changed to is_action_released("jump"), right?

Well, I'm not convinced that would be a good idea, both in terms of backward compatibility, and also because users may incorrectly think `is_action_released()` is the opposite of `is_action_pressed()`, which is most definitely not what it does. It literally returns true if the action is just released, but not if the action is released but not *just* released. `is_action_released()` would be ambiguous.

**Comment by RandomShaper** [comment]
My question about the change was about the sample script, to understand what changes are required for users relying on the old behavior.

Regarding the project setting, I don't see much the point if it defaults to the new behavior. What I suggested (default is legacy, but new projects override it to the fixed one) allows new projects to benefit from the new behavior while giving existing projects the choice to upgrade or stay, with the latter being automatic if they don't get to know about the change. Otherwise, their games will break and they won't understand.

**Comment by lawnjelly** [comment]
> What I suggested (default is legacy, but new projects override it to the fixed one) allows new projects to benefit from the new behavior while giving existing projects the choice to upgrade or stay, with the latter being automatic if they don't get to know about the change. Otherwise, their games will break and they won't understand.

I do understand but am not sure this is a good idea, if we consider that this is a bug fix, rather than a feature. Existing games are broken, this fixes them. They will be missing input currently on some systems, _even if it does not show on the development system_.

I have a couple of games which I wrote a couple of years ago that were missing input, and I had no idea why. Now it is clear - the input logic is flawed in the engine. User code is usually not at fault. If we _don't_ fix this by default, most existing games will continue to be broken. Remember the default action of users is no action.

Fixing bugs is one area where imo we have to be prepared to risk changes in behaviour (especially if we suspect it will adversely only impact very small percentage, and is easily solvable in those cases). Most users will not want to understand _why_ there was a bug in the engine, they will just want it fixed.

> Otherwise, their games will break and they won't understand.

This isn't an "either / or" though. The situation is very different if the change fixes 99% of games, and exposes a script error in 1% or games, versus exposing a script error in 99% of games and fixing 1%.

This kind of thing is exactly why we have beta testing. If we fix a bug by default, we can quickly identify regressions, and if at that point we discover a lot of regressions we should _then_ consider defaulting to old behaviour. If we do it before, we will never know the correct course of action.

### Project Setting
While I'm not 100% sure the legacy project setting is required, it could potentially be a failsafe, and we could for example, remove it after a beta if there were no reports of regressions.

The alternative script changes in order to get the old behaviour are:
`if Input.is_action_just_pressed():`
_becomes_
`if Input.is_action_just_pressed() && Input.is_action_pressed():`

and

`if Input.is_action_just_released():`
_becomes_
`if Input.is_action_just_released() && !Input.is_action_pressed():`

**Comment by RandomShaper** [comment]
> This kind of thing is exactly why we have beta testing. If we fix a bug by default, we can quickly identify regressions, and if at that point we discover a lot of regressions we should _then_ consider defaulting to old behaviour. If we do it before, we will never know the correct course of action.

That's a good point. Let users catch any problems during betas/RCs. With that perspective, I wouldn't even add a project setting. Just a prominent point in the release notes would do.

**Review by RandomShaper — APPROVED** [review]
But, well, now the project setting is already there, I don't think it's an issue to keep it there as a deprecated item, for extra safety. And we eventually remove it.

File: core/input/input.cpp [hunk 4]
```diff
@@ -297,10 +297,13 @@ bool Input::is_action_just_pressed(const StringName &p_action, bool p_exact) con
 		return false;
 	}
 
+	// Backward compatibility for legacy behaviour, only return true if currently pressed.
+	bool pressed_requirement = legacy_just_pressed_behaviour ? E->value.pressed : true;
```
Comment (akien-mga) [inline core/input/input.cpp:301]:
```suggestion
	// Backward compatibility for legacy behavior, only return true if currently pressed.
	bool pressed_requirement = legacy_just_pressed_behavior ? E->value.pressed : true;
```

File: core/input/input.cpp [hunk 5]
```diff
@@ -1531,6 +1540,12 @@ Input::Input() {
 			parse_mapping(entries[i]);
 		}
 	}
+
+	legacy_just_pressed_behaviour = GLOBAL_DEF("input_devices/misc/behaviour/legacy_just_pressed", false);
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply core/input/input.cpp:1544]: That being said that's a lot of new subsections for a single setting (we don't have `misc` nor `misc/behavior` currently). How about `input_devices/compatibility/legacy_just_pressed_behavior`?

File: core/input/input.h [hunk 6]
```diff
@@ -96,14 +96,17 @@ class Input : public Object {
...
-		float strength;
-		float raw_strength;
+		uint64_t pressed_physics_frame = UINT64_MAX;
+		uint64_t pressed_process_frame = UINT64_MAX;
+		uint64_t released_physics_frame = UINT64_MAX;
+		uint64_t released_process_frame = UINT64_MAX;
+		bool pressed = false;
+		bool exact = true;
+		float strength = 0;
+		float raw_strength = 0;
```
Comment (akien-mga) [inline core/input/input.h:109]: We try to be explicit with float inits:
```suggestion
		float strength = 0.0f;
		float raw_strength = 0.0f;
```

File: core/input/input.cpp [hunk 7]
```diff
@@ -686,19 +692,24 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
...
+					action.pressed = true;
+					action.pressed_physics_frame = Engine::get_singleton()->get_physics_frames();
+					action.pressed_process_frame = Engine::get_singleton()->get_process_frames();
+				} else {
+					action.pressed = false;
+					action.released_physics_frame = Engine::get_singleton()->get_physics_frames();
+					action.released_process_frame = Engine::get_singleton()->get_process_frames();
+				}
 				action.strength = 0.0f;
 				action.raw_strength = 0.0f;
```
Comment (lawnjelly) [inline core/input/input.cpp:708]: These two do get overridden below, but we could leave this in for historical / safety. It will be compiled out. But am equally happy to remove.

**Comment by lawnjelly** [comment]
I think I've caught all the `0.0f`s. :grin: , and have changed the project setting.

I wasn't quite sure what the policy is on deprecated project settings in master, let me know if there's anything that needs to be added in that regard.

**Review by akien-mga — APPROVED** [review]

**Comment by vpellen** [comment]
Hey, very nice, thanks!
