### PR TITLE
Do overflow check in when generating NoiseTexture3D

### LINKED ISSUE #88800: Altering the size of a NoiseTexture3D crashes the editor on startup
### Tested versions

- First found in v4.2.1.stable, reproducible as early as v4.1.dev2, the version NoiseTexture3D was introduced.

### System information

Godot v4.2.1.stable unknown - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3070 Ti (nvidia; 545.29.06) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Increasing the depth of a NoiseTexture3D causes the editor to freeze and crash shortly after altering it. If the resource was attached to a scene and saved, the project then becomes impossible to open as it will freeze and crash during loading in, forcing one to manually edit the NoiseTexture3D file to change the depth back to 64, or to simply revert to a previous version of the project.

Here's a backtrace:
```
================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.1.stable.arch_linux
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3c770) [0x7bdbf9c5a770] (??:0)
[2] godot(+0xca60b5) [0x5afa8de7c0b5] (??:?)
[3] godot(+0xca93cd) [0x5afa8de7f3cd] (??:?)
[4] godot(+0xca9aa5) [0x5afa8de7faa5] (??:?)
[5] godot(+0x6a3b4d) [0x5afa8d879b4d] (??:?)
[6] godot(+0x3d48d5b) [0x5afa90f1ed5b] (??:?)
[7] godot(+0x3b7bf0c) [0x5afa90d51f0c] (??:?)
[8] godot(+0x4098722) [0x5afa9126e722] (??:?)
[9] godot(+0x3da5acd) [0x5afa90f7bacd] (??:?)
[10] godot(+0x21ce186) [0x5afa8f3a4186] (??:?)
[11] godot(+0x66f6a1) [0x5afa8d8456a1] (??:?)
[12] godot(+0x5830de) [0x5afa8d7590de] (??:?)
[13] /usr/lib/libc.so.6(+0x25cd0) [0x7bdbf9c43cd0] (??:0)
[14] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7bdbf9c43d8a] (??:0)
[15] godot(+0x58fda5) [0x5afa8d765da5] (??:?)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Create a NoiseTexture3D
2. Add a FastNoiseLite instance
3. Increase the depth
4. Try to save and exit
5. Attempt to reopen the project; if the NoiseTexture3D resource is attached to a scene, the editor will crash on launch, otherwise opening the NoiseTexture3D resource in the editor will cause the editor to crash

### Minimal reproduction project (MRP)

[NoiseTexture3DCrashMRP.zip](https://github.com/godotengine/godot/files/14395231/NoiseTexture3DCrashMRP.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/88800

The origin problem is that the MRP's NoiseTexture3D's width is 4096, height is 4096 and depth is 4096. And In `Noise::_get_image` it will call `values.resize(p_width * p_height * p_depth)`, the values vector's capacity is uint32_t which can not handle 4096^3 and overflows, thus the `resize` failed, or more preciously speaking, it overflowed to 0, and the later vector indexing caused this crash.

My solution here, technically speaking is not overflow check but more like an sanity check that should be placed somewhere in `NoiseTexture3D`. Feel free to correct me.

Also the `NoiseTexture2D` may need the same check too, although it's less likely to have the same problem as `NoiseTexture3D`.

### CODE REVIEW

**Comment by emre0altan** [comment]
Limits it to the same memory size that maximum 2d texture has, looks good 👍

File: modules/noise/noise_texture_3d.cpp [hunk 1]
```diff
@@ -142,6 +142,8 @@ TypedArray<Image> NoiseTexture3D::_generate_texture() {
 		return TypedArray<Image>();
 	}
 
+	ERR_FAIL_COND_V_MSG((int64_t)width * height * depth > std::numeric_limits<int>::max() / 8, TypedArray<Image>(), "The NoiseTexture3D is too big, consider lowering its width, height or depth.");
```
Comment (Mickeon) [inline modules/noise/noise_texture_3d.cpp:145]: I believe @emre0altan is referring to this (also parenthesis to be a bit clearer):
```suggestion
	ERR_FAIL_COND_V_MSG((int64_t)(width * height * depth) > Image::MAX_WIDTH, TypedArray<Image>(), "The NoiseTexture3D is too big, consider lowering its width, height or depth.");
```

Comment (emre0altan) [reply modules/noise/noise_texture_3d.cpp:145]: I think it should be `Image::MAX_PIXELS` instead, it would be the total allocation of the image.

Comment (jsjtxietian) [reply modules/noise/noise_texture_3d.cpp:145]: > And I think @jsjtxietian wanted to cast first so that it won't overflow.

Yes that's the reason why I wrote it this way. I will update my code now.

**Review by akien-mga — APPROVED** [review]

File: modules/noise/noise_texture_3d.cpp [hunk 2]
```diff
@@ -142,6 +142,8 @@ TypedArray<Image> NoiseTexture3D::_generate_texture() {
 		return TypedArray<Image>();
 	}
 
+	ERR_FAIL_COND_V_MSG((int64_t)width * height * depth > Image::MAX_PIXELS, TypedArray<Image>(), "The NoiseTexture3D is too big, consider lowering its width, height or depth.");
```
Comment (AThousandShips) [inline modules/noise/noise_texture_3d.cpp:145]:
```suggestion
	ERR_FAIL_COND_V_MSG((int64_t)width * height * depth > Image::MAX_PIXELS, TypedArray<Image>(), "The NoiseTexture3D is too big, consider lowering its width, height, or depth.");
```

**Review by AThousandShips — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

File: modules/noise/noise_texture_3d.cpp (hunk 2 above)
Comment (jsjtxietian) [reply modules/noise/noise_texture_3d.cpp:145]: Thanks!

**Comment by akien-mga** [comment]
Thanks!
