### PR TITLE
Clamp menus at the bottom of the screen.

### LINKED ISSUE #109575: Editor Context menu items block underlying menu if bottom portion overflows screen height
### Tested versions

Reproducible in: Godot v4.5.beta5, Godot v4.4.1.stable

### System information

Godot v4.5.beta5.mono - Windows 11 (build 26200) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.7602) - 12th Gen Intel(R) Core(TM) i7-12700H (20 threads) - 15.62 GiB memory

### Issue description

In the editor, a menu item can block the menu behind it when the bottom of the context menu extends past its height (see images):
Image

I think the Godot context menu could work like Blender’s in the images bellow, hovering would scroll it up or down. Another option is opening it upward, but that might block the editor view
Image

### Steps to reproduce

Click menu items "Edit" on the shader editor on the bottom panel after that it will block the menu items

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/109575

| Before | After |
|---|---|
| Screenshot 2025-08-26 at 11 22 02 | Screenshot 2025-08-26 at 11 22 45 |

### CODE REVIEW

**Comment by KoBeWi** [comment]
For some reason this does not work with the menus at the top of the editor.

image

Though it's unrelated to the issue.

File: scene/gui/menu_button.cpp [hunk 1]
```diff
@@ -85,6 +85,16 @@ void MenuButton::show_popup() {
 		Transform2D xform = get_viewport()->get_popup_base_transform_native();
 		rect = xform.xform(rect);
 	}
+	Rect2i scr_usable = DisplayServer::get_singleton()->screen_get_usable_rect(get_window()->get_current_screen());
+	Size2i max_size = Size2i();
```
Comment (KoBeWi) [inline scene/gui/menu_button.cpp]:
```suggestion
	Size2i max_size;
```

File: scene/gui/menu_button.cpp [hunk 2]
```diff
@@ -85,6 +85,16 @@ void MenuButton::show_popup() {
...
+	if (scr_usable != Rect2i()) {
```
Comment (KoBeWi) [inline scene/gui/menu_button.cpp]:
```suggestion
	if (scr_usable.has_area()) {
```
(though it's a bit different check, so might be not applicable)

File: scene/gui/menu_button.cpp [hunk 3]
```diff
@@ -85,6 +85,16 @@ void MenuButton::show_popup() {
...
+		real_t max_h = scr_usable.position.y + scr_usable.size.y - rect.position.y;
+		real_t max_w = scr_usable.position.x + scr_usable.size.x - rect.position.x;
```
Comment (KoBeWi) [inline scene/gui/menu_button.cpp]:
```suggestion
		real_t max_h = scr_usable.get_end().y - rect.position.y;
		real_t max_w = scr_usable.get_end().x - rect.position.x;
```

**Comment by bruvzg** [comment]
> For some reason this does not work with the menus at the top of the editor

Might be because I have set limit to `4 * menu button height` to avoid to tiny menus (and top menu likely has bigger height than menu item).

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
