### PR TITLE
Fix layered HDR texture import with lossless compression

### LINKED ISSUE #97827: RGBH .exr imported as Texture3D with Lossless compression gets converted to RGB8
### Tested versions

4.3

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

My 16-bit floating point 3d textures were getting their values normalized into [0,1].  I don't know if it's supposed to be like this, but it was very confusing.

### Steps to reproduce

An image generated by this script:
```gdscript
var image: Image = Image.create_empty(1, 1, false, Image.FORMAT_RGBH)
image.set_pixel(0, 0, Color(-1.0, 0.5, 43.75))
image.save_exr("res://test_texture.exr")
```
when imported as a Texture3D with Lossless compression, contains the pixel `(0, 0.498, 1, 1)`
but if imported as a Texture2D with Lossless compression it has the original pixel
```
res://2d_lossless.exr            Format 14
res://2d_lossless.exr            Pixel (-1, 0.5, 43.75, 1)
res://2d_vram_uncompressed.exr   Format 14
res://2d_vram_uncompressed.exr   Pixel (-1, 0.5, 43.75, 1)
res://3d_lossless.exr            Format 4
res://3d_lossless.exr            Pixel (0, 0.498, 1, 1)
res://3d_vram_uncompressed.exr   Format 14
res://3d_vram_uncompressed.exr   Pixel (-1, 0.5, 43.75, 1)
```

### Minimal reproduction project (MRP)

[exr-image-float.zip](https://github.com/user-attachments/files/17263606/exr-image-float.zip)

### PR DESCRIPTION
**Pull request by BlueCube3310**
Fixes #97827

The layered texture importer was missing some code from the 2D importer.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/import/resource_importer_texture.cpp [hunk 1]
```diff
@@ -380,7 +380,7 @@ void ResourceImporterTexture::_save_ctex(const Ref<Image> &p_image, const String
 	f->store_32(0);
 	f->store_32(0);
 
-	if ((p_compress_mode == COMPRESS_LOSSLESS || p_compress_mode == COMPRESS_LOSSY) && p_image->get_format() > Image::FORMAT_RGBA8) {
+	if ((p_compress_mode == COMPRESS_LOSSLESS || p_compress_mode == COMPRESS_LOSSY) && p_image->get_format() >= Image::FORMAT_RF) {
```
Comment (clayjohn) [inline editor/import/resource_importer_texture.cpp:383]: Note for the future, this changes the behaviour for `FORMAT_RGBA4444` and `FORMAT_RGB565`. 

I think the change makes sense as people who intentionally use such compressed formats would be surprised that Godot converts them to an RGBA8 internally. Making note of it here though as it is a change in behaviour.

**Review by clayjohn — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
