### PR TITLE
Fix rotated/flipped tiles destination rect calculations

### LINKED ISSUE #86655: Collision Layer not Rotating Upon Rotation of Tile in 2d
### Tested versions

Reproducible in 4.2.1-stable

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3770) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

Whenever I rotate a tile before placing it, the rotation is not applied to the collision layer, leading to CharacterBody2ds being able to go through portions of the tile that are meant to have collision, while not being able to go through areas where the collision layer should not be applied. In the video, the left side had a normal tile, and the right side had a rotated tile.

Video of Issue
https://github.com/godotengine/godot/assets/142550397/0422618e-79c6-4191-95d8-26e440edc1ce

Photo of Editor showing collision layer placement
https://github.com/godotengine/godot/assets/142550397/125f096a-5c9e-44a4-a119-c905c1433410

### Steps to reproduce

In a 2d node, create a tileset with a tile that is larger than 1 grid unit. Add collision to that tile using a collision layer. Rotate and place that tile on the game area, and add a player with the ability to move around the game area. Attempt to move the player through the tile on all sides.

### Minimal reproduction project (MRP)

[Godot rotation bug.zip](https://github.com/godotengine/godot/files/13799321/Godot.rotation.bug.zip)

### LINKED ISSUE #106842: Changing texture origin of alternative tiles moves the tile in the atlas
### Tested versions

Reproducible in v4.5.dev4.mono.official [209a446e3]

### System information

Godot v4.5.dev4.mono - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 32.0.13031.3015) - AMD Ryzen 9 3900X 12-Core Processor (24 threads)

### Issue description

When creating an alternative tile for a big tile (larger than the tilemaplayer's tilesize) and then changing the texture origin it moves the alternative tile itself on the atlas. The texture origin seems to set correctly as the blue square indicator is positioned correctly.

Image

### Steps to reproduce

1. Create a tileset atlas and tile larger than TileMapLayer TileSize (eg. 64x32 for a 32x32 TileSize)
2. Create Alternative Tile for that tile
3. Set the texture origin y value to 16 (or any value other than 0) 
4. The tile moves at an angle (not only on the y axis)

### Minimal reproduction project (MRP)

[alternative-tile-test.zip](https://github.com/user-attachments/files/20445530/alternative-tile-test.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #86655 (AFAICT the collision shapes were being rotated correctly before (tested in v4.4.1.stable.official [49a5bc7b6]) but the rendering could have mismatched the collisions).

Fixes #106842 (regression from #105861).

~~Marking this PR with `cherrypick:4.4` as #105861 is marked as such.~~

---

I've tested all possible per-TileSet-tile and per-TileMapLayer-cell flags combinations (8 * 8 = 64 cases) with a non-symmetrical texture origin and collision shape, all seems to work correctly. But further testing welcomed.

Images below are from modified MRP from #86655: [Godot.rotation.bug_v2.zip](https://github.com/user-attachments/files/20572773/Godot.rotation.bug_v2.zip).
(I've tested #106842 as well, all good.)

Alternative tiles with different flip_h/flip_v/transpose flags:
Texture origins<br>godot windows editor dev x86_64_OcMqIfEyij|Collision shapes<br>godot windows editor dev x86_64_C9WsOjfJwj
-|-

For each alternative tile 4 per-cell rotations (right half-plane) and 4 flipped-rotations (left half-plane):
v4.4.1.stable.official [49a5bc7b6]|v4.5.dev.custom_build [e45cc6809]<br>(current `master`)|v4.5.dev.custom_build [4366e5f5d]<br>(this PR)
-|-|-
Godot_v4 4 1-stable_win64_RnLEfyGSs2|godot windows editor dev x86_64_6etuKixlAq|godot windows editor dev x86_64_i0VLJAnNXJ

### CODE REVIEW

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 1]
```diff
@@ -1531,9 +1507,7 @@ void TileMapLayerEditorTilesPlugin::_apply_transform(int p_type) {
 
 			Vector2i dst_coords;
 
-			if (keep_shape) {
-				dst_coords = src_coords;
-			} else if (p_type == TRANSFORM_ROTATE_LEFT) {
+			if (p_type == TRANSFORM_ROTATE_LEFT) {
```
Comment (kleonc) [inline editor/plugins/tiles/tile_map_layer_editor.cpp:1501]: This is unrelated change, but `size == (1, 1)` case is handled just fine by every other case, no special handling needed here.

**Comment by akien-mga** [comment]
Let's play it safe and not cherry-pick either fix, so we first get sufficient testing in the 4.5 beta phase.

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 2]
```diff
@@ -1558,40 +1532,22 @@ int TileMapLayerEditorTilesPlugin::_get_transformed_alternative(int p_alternativ
...
+			bool negated_flip_h = !transform_flip_h;
+			transform_flip_h = transform_flip_v;
+			transform_flip_v = negated_flip_h;
+			transform_transpose = !transform_transpose;
+		} break;
+		case TRANSFORM_ROTATE_RIGHT: { // (h, v, t) -> (!v, h, !t)
+			bool negated_flip_v = !transform_flip_v;
+			transform_flip_v = transform_flip_h;
+			transform_flip_h = negated_flip_v;
+			transform_transpose = !transform_transpose;
```
Comment (kleonc) [inline editor/plugins/tiles/tile_map_layer_editor.cpp:1536]: That just a simplification, should behave the same.

File: scene/2d/tile_map_layer.h [hunk 3]
```diff
@@ -527,6 +532,7 @@ class TileMapLayer : public Node2D {
 	// Not exposed to users.
 	TileMapCell get_cell(const Vector2i &p_coords) const;
 
+	static TileDrawRectParams compute_transformed_tile_dest_rect(const Vector2 &p_position, const Vector2 &p_dest_rect_size, const TileData *p_tile_data, int p_alternative_tile);
```
Comment (groud) [inline scene/2d/tile_map_layer.h]: I think would rather avoid declaring a new structure here. It makes it a bit more difficult to keep track of what should be used or not. You can use references instead, that's pretty common in the codebase:
```
static void compute_transformed_tile_dest_rect(rect2 r_dest_rect, bool r_transpose, const Vector2 &p_position, const Vector2 &p_dest_rect_size, const TileData *p_tile_data, int p_alternative_tile);
```

**Review by groud — CHANGES_REQUESTED** [review]

File: scene/2d/tile_map_layer.h (hunk 3 above)
Comment (kleonc) [reply scene/2d/tile_map_layer.h]: Changed. I think `r_` params are usually last within the codebase, but not sure if that's required by some style guidelines. I've made them first like you've suggested.

Comment (groud) [reply scene/2d/tile_map_layer.h]: Yeah I am not 100% sure, though I think defining a struct for 2 return values is pretty rare. My rule of thumb is likely to use a reference when you have, like, 2 of 3 values to return. For more, a struct better sense.

Comment (kleonc) [reply scene/2d/tile_map_layer.h]: Yeah, totally makes sense, felt iffy when adding that struct. Also one less "how to name this thing". 🙃

File: editor/plugins/tiles/tile_map_layer_editor.cpp (hunk 1 above)
Comment (groud) [reply editor/plugins/tiles/tile_map_layer_editor.cpp:1501]: I don't mind the change but I feel in such case it would require a check for the `int` value maybe?
Ideally, we should name the enum and use this enum type as argument instead (if that's possible). 

Anyway, that's a nitpick.

Comment (kleonc) [reply editor/plugins/tiles/tile_map_layer_editor.cpp:1501]: This method is only used internally with specific flags binded, so it's probably fine as is.
https://github.com/godotengine/godot/blob/978b38797ba8e8757592f21101e32e364d60662d/editor/plugins/tiles/tile_map_layer_editor.cpp#L2314

But shouldn't hurt to name it, so I did it. Note it required adding `VARIANT_ENUM_CAST(TileMapLayerEditorTilesPlugin::TileTransformType)` for it to compile / work with signals.

File: editor/plugins/tiles/tile_map_layer_editor.cpp (hunk 2 above)
Comment (groud) [reply editor/plugins/tiles/tile_map_layer_editor.cpp:1536]: Tested it. Seems to work fine indeed.

**Review by groud — APPROVED** [review]

**Comment by kleonc** [comment]
I've previously changed param type (`int` -> `TileTransformType` enum) only in `_apply_transform`, missed `_get_transformed_alternative`.

https://github.com/godotengine/godot/blob/445a51834e7172053352ca8f9eeef48efab2de17/editor/plugins/tiles/tile_map_layer_editor.h#L149-L150

So I've done the same in `_get_transformed_alternative` for consistency (+rebased).
(all works as before)

**Comment by akien-mga** [comment]
Thanks!

**Comment by Advay17** [comment]
I'll be honest I'd completely forgotten about this issue, so thanks for taking the time to fix it!
