### PR TITLE
GDScript: Fix wrong marking of some lines related to Variant as unsafe

### LINKED ISSUE #69068: Assigning Variant to Variant is not considered as type safe
### Godot version

Last master build of 5923df92346d65c52ceaf651ea1aaa5ce20e875f

### System information

MacOS 10.15.7

### Issue description

Assigning Variant to Variant is not marked as type safe in the example bellow.

If `b` is typed as `String` instead, then all lines are safe.

Can godot distinguish explicitly typed Variants from implicit ones? If yes then I think that any assignment to explicitly typed variable/property/argument as Variant should be type safe, no?

### Steps to reproduce

```gd
func _ready() -> void:
  var a: Variant = 1
  var b: Variant = 'one'
  a = b # this line is not highlighted as type safe
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by vonagam**
I think most of the things were implemented in other PRs. Here is what remains in this one:

```gdscript
func variant() -> Variant: return null

func as_return() -> Variant:
  return variant() # safe now

func as_argument(arg: Variant): pass
  
func _ready():
  var mystery := variant()
  
  as_argument(mystery) # safe now
  
  if mystery == null: pass # safe now
  if mystery != null: pass # safe now
  if mystery is Node: pass # safe now
  
```

Those will be safe for variant - returning or passing as an argument with explicitly specified Variant type, comparing to null, type checking.

### CODE REVIEW

**Comment by vonagam** [comment]
Marked `is`, `==` and `!=` operators as safe for usage with variants and typed them as booleans. Currently:
```gd
if var_e == null: pass # not safe, bad
if var_e != null: pass # not safe, bad
if var_e is Node: pass # not safe, bad
```

**Comment by vonagam** [comment]
Hm... so comparing two Variants is unsafe, have not expected that. 
Limited blank safety only to comparing to null.

Since arrays and now dictionaries are compared by contents, usual comparison may include a conversion and also does not work between two arbitrary types, starting to think that something like `===` from js might make sense here - operator that checks that types are equal and compares inputs only by reference if possible, so no conversions, no contents checks and safe for all type combinations. Or at least a global helper method `is_equal_strict` for that.

**Comment by vonagam** [comment]
Updated PR to allow inference of hard Variants for variables:
```gdscript
var var_i := variant() # error -> safe
```
Removed some inconsistencies between resolving member variables and local ones.

Added a test.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -783,7 +783,16 @@ void GDScriptAnalyzer::resolve_class_member(GDScriptParser::ClassNode *p_class,
...
-					if (datatype.type_source != GDScriptParser::DataType::UNDETECTED) {
+					if (member.variable->infer_datatype) {
+						if (!datatype.is_set() || datatype.has_no_type()) {
+							push_error(vformat(R"(Cannot infer the type of "%s" variable because the initial value doesn't have a set type.)", member.variable->identifier->name), member.variable->initializer);
+						} else if (datatype.is_variant() && !datatype.is_hard_type()) {
+							push_error(vformat(R"(Cannot infer the type of "%s" variable because the initial value is Variant. Use explicit "Variant" type if this is intended.)", member.variable->identifier->name), member.variable->initializer);
+						} else if (datatype.kind == GDScriptParser::DataType::BUILTIN && datatype.builtin_type == Variant::NIL) {
+							push_error(vformat(R"(Cannot infer the type of "%s" variable because the initial value is "null".)", member.variable->identifier->name), member.variable->initializer);
+						}
+						datatype.type_source = GDScriptParser::DataType::ANNOTATED_INFERRED;
```
Comment (anvilfolk) [inline modules/gdscript/gdscript_analyzer.cpp:794]: I wonder whether this should be set here, given that errors may occur. I don't know what the behavior of the analyzer is elsewhere if it the type source is `ANNOTATED_INFERRED` but the datatype isn't set.

Should it be set like this only for when there are no errors?

**Comment by anvilfolk** [comment]
Just went through the PR. Didn't really do a deep dive, but all the code changes make sense to me, as well as the conceptual changes to what is safe and isn't safe :)

Just had a question above for something that I noticed afterward was already this way, so I guess no harm in leaving it this way either :)

**Review by anvilfolk — APPROVED** [review]

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:794]: Good notice. Yes, it is always set to `ANNOTATED_INFERRED` (in variables, constants and params) ignoring errors. Fix for it should not be hard - new variable `bool is_inferred = false`, additional last `else` branch after errors that set `is_inferred = true` and then `type_source` is set in ternary to either  `ANNOTATED_INFERRED` or `UNDETECTED` based on the bool.

This should be done in other PR for all those places.

Comment (anvilfolk) [reply modules/gdscript/gdscript_analyzer.cpp:794]: I was thinking about this a little more and wondering whether this should change or not. Do you think this is actually an issue?

I've noticed that the analyzer is very permissive - it seems to prefer annotating the first error, and ignoring any errors stemming from the first error. This way it's more obvious which is the _main_ or _original_ error. Do you think that's why this currently works this way?

Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp:794]: Yeah, actually came to the same conclusion after some time. In the end it is a preference and I think that less noise is better, since you seem to agree I'll resolve the conversion.

**Comment by anvilfolk** [comment]
Needs rebase!

**Review by adamscott — APPROVED** [review]
Looks good to me.

**Comment by vnen** [comment]
> Updated PR to allow inference of hard Variants for variables:
> 
> ```gdscript
> var var_i := variant() # error -> safe
> ```

I'm not sure if this is a good idea. Generally one uses type inference expecting to become of that specific type. Since Variant is not really an specific type, it should not be valid for inference, even if the original value is hard typed to be Variant. I fear it's quite easy to do this mistakenly by accident.

In this case it would be better to either not use static type at all or explicitly type it as Variant.

**Comment by vonagam** [comment]
`var var_i := variant()` was part of unification, currently in master, not part of this PR.

I consider the line itself as safe. Unsafe lines would be those where `var_i` is used as anything other than variant. So if `var_i` is used just as a dictionary key, that's pretty type safe. (After type parameters for dictionaries are introduced one will be able to communicate if they really expect variants as key/value or not and those lines might become type unsafe.)

> not use static type

In my view there is a difference between hard variant type and weak variant (untyped) type. With hard variant it should be safe to both read and write variant while with weak one you are told that the value is of some unspecified type, you can expect anything but it does not mean that you can safely set it to anything, so:
```gdscript
var a := variant()
a = another_variant() # type safe

var b = variant()
b = another_variant() # type unsafe
```

**Comment by vonagam** [comment]
Updated description to show what is left in this PR.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
