### PR TITLE
Fix crash with user-defined `ResourceFormatLoader.load`

### LINKED ISSUE #48463: Returning errors from `ResourceFormatLoader.load` crashes engine
**Godot version:**
v3.3 (and v3.2.3)

**OS/device including version:**
Windows 10

**Issue description:**
The documentation for `ResourceFormatLoader.load(...)` says "Returns a Resource object on success, or an Error constant in case of failure." ([documentation](https://docs.godotengine.org/en/stable/classes/class_resourceformatloader.html#class-resourceformatloader-method-load)) Overloading this function and returning an error results in either a crash of the editor or an infinite error printing loop.

**Steps to reproduce:**
1. Create a script that inherits from `ResourceFormatLoader` and fill out all as normal. In the `load` function return an error.
2. Create a file with the extension of the format loader.
3. Double-click the file in the file system dock. The editor will usually crash.

Sometimes I can get an infinite-error loop by restarting the engine. That _may_ be a different issue. If fixing the crash doesn't fix the loop, then I will create a separate issue for that.

**Minimal reproduction project:**
https://github.com/cgbeutler/godot_bug_ResourceFormatLoader_return_error
Open the project. If you don't get the infinite loop version of the bug, double-click `custom_res.txt` in the file explorer and the engine _should_ crash.

### PR DESCRIPTION
**Pull request by akien-mga**
There's still some fishy recursive relationship between `load_interactive` and
`load` which needs to be investigated here, but this patch solves the crash
when returning an error code in user-defined `load`, and improves the error
message.

Fixes #48463.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @Zylann as this code was added in #19501.

But the weird relationship between `load` and `load_interactive` seems to predate that PR and dates back to the original open source commit. I have no clue what's the intended correct behavior here, each method starts by calling the other one.

```
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 106) Ref<ResourceInteractiveLoader> ResourceFormatLoader::load_interactive(const String &p_path) {
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 107) 
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 108)      //either this
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 109)      Ref<Resource> res = load(p_path);
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 110)      if (res.is_null())
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 111)              return Ref<ResourceInteractiveLoader>();
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 112) 
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 113)      Ref<ResourceInteractiveLoaderDefault> ril = Ref<ResourceInteractiveLoaderDefault>( memnew( ResourceInteractiveLoaderDefault ));
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 114)      ril->resource=res;
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 115)      return ril;
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 116) }
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 117) 
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 118) RES ResourceFormatLoader::load(const String &p_path,const String& p_original_path) {
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 119) 
a76709d2403 (Juan Linietsky 2015-05-04 10:17:24 -0300 120)      String path=p_path;
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 121) 
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 122)      //or this must be implemented
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 123)      Ref<ResourceInteractiveLoader> ril = load_interactive(p_path);
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 124)      if (!ril.is_valid())
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 125)              return RES();
0b806ee0fc9 (Juan Linietsky 2014-02-09 22:10:30 -0300 126)      ril->set_local_path(p_original_path);
```

File: core/io/resource_loader.cpp [hunk 1]
```diff
@@ -160,24 +148,46 @@ void ResourceFormatLoader::get_recognized_extensions(List<String> *p_extensions)
...
+	// Check user-defined loader if there's any. Hard fail if it returns an error.
 	if (get_script_instance() && get_script_instance()->has_method("load")) {
 		Variant res = get_script_instance()->call("load", p_path, p_original_path);
 
-		if (res.get_type() == Variant::INT) {
+		if (res.get_type() == Variant::INT) { // Error code, abort.
 			if (r_error) {
 				*r_error = (Error)res.operator int64_t();
 			}
+			const Ref<Script> &script = get_script_instance()->get_script();
```
Comment (reduz) [inline core/io/resource_loader.cpp:176]: this is the same as just get_script()

**Comment by akien-mga** [comment]
> But the weird relationship between `load` and `load_interactive` seems to predate that PR and dates back to the original open source commit. I have no clue what's the intended correct behavior here, each method starts by calling the other one.

This seems to be done on purpose as derived classes must override either `load` or `load_interactive`, and the non-overridden one will call the override. I added some comments to clarify that, and grouped the two methods together.

File: core/io/resource_loader.cpp [hunk 2]
```diff
@@ -160,24 +148,45 @@ void ResourceFormatLoader::get_recognized_extensions(List<String> *p_extensions)
...
 		Variant res = get_script_instance()->call("load", p_path, p_original_path);
 
-		if (res.get_type() == Variant::INT) {
+		if (res.get_type() == Variant::INT) { // Error code, abort.
 			if (r_error) {
 				*r_error = (Error)res.operator int64_t();
 			}
+			const String script_path = get_script().is_valid() ? vformat("'%s'", get_script()->get_path()) : "a user script";
+			ERR_FAIL_V_MSG(RES(),
+					vformat("Failed to load resource '%s' using overridden `load` method in %s. Error code: %d.",
```
Comment (reduz) [inline core/io/resource_loader.cpp:178]: Functions that return error codes do not print error to console. Its either one or the other.

**Review by reduz — DISMISSED** [review]

File: core/io/resource_loader.cpp (hunk 2 above)
Comment (akien-mga) [reply core/io/resource_loader.cpp]: Alright, that's sad because we don't properly use `r_error`, but it's better than a crash in any case. Discussion from Godot chat for reference:
Screenshot_20210505_154702

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.
