### PR TITLE
Do not require editor restart when changing `Path3D` Tilt Disk Size setting

### LINKED ISSUE #84908: Path3D tilt handle size in settings does not work and value is not kept between launches
### Godot version

4.2b5

### System information

macos 12.7

### Issue description

the tilt handles were very small as i had very large path3ds in that project, i found the setting to change their size but it did not seem to do anything, and after restarting the editor, the value was reset.

### Steps to reproduce

change tilt handle size value
restart
check tilt handle size

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ryevdokimov**
Previously you had this prompt:

image

Now:

https://github.com/user-attachments/assets/a6d0fea7-d538-4765-8b96-082082aa81f1

<i>Bugsquad edit:</i>
- Fixes https://github.com/godotengine/godot/issues/84908

### CODE REVIEW

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -902,9 +930,7 @@ Path3DEditorPlugin::Path3DEditorPlugin() {
 	mirror_handle_angle = true;
 	mirror_handle_length = true;
 
-	disk_size = EDITOR_GET("editors/3d_gizmos/gizmo_settings/path3d_tilt_disk_size");
-
-	Ref<Path3DGizmoPlugin> gizmo_plugin = memnew(Path3DGizmoPlugin(disk_size));
+	Ref<Path3DGizmoPlugin> gizmo_plugin = memnew(Path3DGizmoPlugin());
```
Comment (AThousandShips) [inline editor/scene/3d/path_3d_editor_plugin.cpp]:
```suggestion
	Ref<Path3DGizmoPlugin> gizmo_plugin;
	gizmo_plugin.instantiate();
```
Preferred syntax

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -447,6 +447,8 @@ void Path3DGizmo::redraw() {
 
 			// Collect tilt-handles.
 			if (Path3DEditorPlugin::singleton->curve_edit_tilt->is_pressed()) {
+				const float disk_size = EDITOR_GET("editors/3d_gizmos/gizmo_settings/path3d_tilt_disk_size");
```
Comment (Calinou) [inline editor/scene/3d/path_3d_editor_plugin.cpp]: This should be moved outside the loop so it's called only once. Or, better, it should be moved to a member variable that is set in the constructor and `_editor_settings_changed()`.

Comment (ryevdokimov) [reply editor/scene/3d/path_3d_editor_plugin.cpp]: Good catch updated and tested.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

Code looks good to me.

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 3]
```diff
@@ -891,6 +893,30 @@ void Path3DEditorPlugin::_update_toolbar() {
...
+		return;
+	}
+
+	path->update_gizmos();
+}
+
+void Path3DEditorPlugin::_notification(int p_what) {
+	switch (p_what) {
+		case NOTIFICATION_ENTER_TREE: {
+			EditorSettings::get_singleton()->connect("settings_changed", callable_mp(this, &Path3DEditorPlugin::_editor_settings_changed));
```
Comment (KoBeWi) [inline editor/scene/3d/path_3d_editor_plugin.cpp]: Use NOTIFICATION_EDITOR_SETTINGS_CHANGED instead of the signal.

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 4]
```diff
@@ -891,6 +893,30 @@ void Path3DEditorPlugin::_update_toolbar() {
 	create_curve_button->set_visible(!has_curve);
 }
 
+void Path3DEditorPlugin::_editor_settings_changed() {
+	if (!EditorSettings::get_singleton()->get_changed_settings().has("editors/3d_gizmos/gizmo_settings/path3d_tilt_disk_size")) {
+		return;
+	}
+
+	if (!path) {
```
Comment (KoBeWi) [inline editor/scene/3d/path_3d_editor_plugin.cpp]: This should be checked before checking the setting.

File: editor/scene/3d/path_3d_editor_plugin.cpp [hunk 5]
```diff
@@ -869,6 +871,22 @@ void Path3DEditorPlugin::_update_toolbar() {
...
 }
 
+void Path3DEditorPlugin::_notification(int p_what) {
+	switch (p_what) {
+		case EditorSettings::NOTIFICATION_EDITOR_SETTINGS_CHANGED: {
+			if (!path) {
+				return;
+			}
+
+			if (!EditorSettings::get_singleton()->get_changed_settings().has("editors/3d_gizmos/gizmo_settings/path3d_tilt_disk_size")) {
```
Comment (KoBeWi) [inline editor/scene/3d/path_3d_editor_plugin.cpp]:
```suggestion
			if (!EditorSettings::get_singleton()->check_changed_settings_in_group("editors/3d_gizmos/gizmo_settings")) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
