### PR TITLE
Mono/C#: Several android fixes

### LINKED ISSUE #33851: Mono/Android - DateTime.Now crashes the game on Android
**Godot version:**
3.2 Beta 2 (Mono)

**OS/device including version:**
Android 10, Build QP1A.191105.003
Google Pixel 3a

**Issue description:**
Using `System.DateTime.Now` will instantly crash the game

Log from `adb logcat`
```
11-23 18:46:23.164 29219 29271 E mono    : 
11-23 18:46:23.164 29219 29271 E mono    : Unhandled Exception:
11-23 18:46:23.164 29219 29271 E mono    : System.DllNotFoundException: __Internal assembly:<unknown assembly> type:<unknown type> member:(null)
11-23 18:46:23.164 29219 29271 E mono    :   at (wrapper managed-to-native) System.TimeZoneInfo+AndroidTimeZones.monodroid_get_system_property(string,intptr&)
11-23 18:46:23.164 29219 29271 E mono    :   at System.TimeZoneInfo+AndroidTimeZones.GetDefaultTimeZoneName () [0x00029] in <3b08f2249ec641d8b691b85bde6bce48>:0 
11-23 18:46:23.164 29219 29271 E mono    :   at System.TimeZoneInfo+AndroidTimeZones.get_Local () [0x00000] in <3b08f2249ec641d8b691b85bde6bce48>:0 
11-23 18:46:23.164 29219 29271 E mono    :   at System.TimeZoneInfo.CreateLocal () [0x00000] in <3b08f2249ec641d8b691b85bde6bce48>:0 
11-23 18:46:23.164 29219 29271 E mono    :   at System.TimeZoneInfo.get_Local () [0x00009] in <3b08f2249ec641d8b691b85bde6bce48>:0 
11-23 18:46:23.164 29219 29271 E mono    :   at System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc (System.DateTime time, System.Boolean& isAmbiguousLocalDst) [0x00000] in <3b08f2249ec641d8b691b85bde6bce48>:0 
11-23 18:46:23.164 29219 29271 E mono    :   at System.DateTime.get_Now () [0x00008] in <3b08f2249ec641d8b691b85bde6bce48>:0 
11-23 18:46:23.164 29219 29271 E mono    :   at Nodey._Ready () [0x00001] in <47566f4059054cfabb0b52642f33fb86>:0 
```

**Steps to reproduce:**
1. Create a C# Script, and Print out `System.DateTime.Now.ToString()` (for example)
2. Build to an Android device

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/3883102/Test.zip)

### PR DESCRIPTION
**Pull request by neikeq**
- Added correct config file for android dllmaps.
- Fix __Internal DllImports with a dlopen fallback.
- Add missing P/Invoke functions and internal calls expected by the monodroid BCL and our custom version of the 'Android.Runtime.AndroidEnvironment' class (this last one can be found in the godot-mono-builds repo).
- Make sure to set 'btls' instead of 'legacy' as the default TLS provider on Android.

This changes depend on the godot-mono-builds commit: https://github.com/godotengine/godot-mono-builds/commit/ee5482260099212b6164fdf9ecc1fd0522a92654

Also additionally added the `Duplicate` method to the Array and Dictionary bindings. I had to make it part of this PR as my changes depend on it.

Fixes #33851
#33934 likely had something to do with this, so it may be fixed by this as well.

### CODE REVIEW

File: thirdparty/misc/ifaddrs-android.h [hunk 1]
```diff
@@ -32,15 +32,22 @@
...
   struct sockaddr* ifa_netmask;
-  // Real ifaddrs has broadcast, point to point and data members.
-  // We don't need them (yet?).
+  // We never initialize the following members. We only define them to match the ifaddrs struct.
+  union
+  {
+    struct sockaddr *ifu_broadaddr;
+    struct sockaddr *ifu_dstaddr;
+  } ifa_ifu;
+  void *ifa_data;
```
Comment (neikeq) [inline thirdparty/misc/ifaddrs-android.h]: I needed to add the `ifaddrs` missing members as the Mono BCL will do a copy of the struct so it must match. Nothing else changes, these members are still never initialized (the Mono BCL doesn't use them either so that's fine).
This is a third-party header, should this change's diff be documented somewhere?

Comment (akien-mga) [reply thirdparty/misc/ifaddrs-android.h]: It would be good if you can include a patch in `thirdparty/misc/patches/` that does those changes, and mention it where relevant in `thirdparty/README.md`.

Comment (akien-mga) [reply thirdparty/misc/ifaddrs-android.h]: Alternatively, you can enclose all Godot-made changes with
```
// -- GODOT start --
...
// -- GODOT end --
```
so that we can easily identify what we added ourselves.

Comment (neikeq) [reply thirdparty/misc/ifaddrs-android.h]: Which one is the preferred way?

Comment (neikeq) [reply thirdparty/misc/ifaddrs-android.h]: I did it the start/end comments way.

**Comment by akien-mga** [comment]
Thanks!
