### PR TITLE
Fix no unsaved indicator Save As resource

### LINKED ISSUE #44053: Saving a resource to file doesn't mark the scene as modified
**Godot version:**

3.2.4 beta3

**Steps to reproduce:**
1. Create a node (e.g. Node2D)
2. Add any resource to it (e.g. built-in script or material)
3. Save the scene
4. Right-click the resource and choose Save
5. Save it to file
6. The resource is saved to file and reference gets modified
7. But the scene is not marked modified. If you close it, you will lose the reference to the file

### LINKED ISSUE #96087: Save warning doesn't show when you save a built-in resource as an external resource
### Tested versions

- Reproducible in: 4.3.stable

### System information

Godot v4.3.stable - macOS 14.2.1 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When you close a scene after saving a built-in resource as an external resource, you don't get a warning to save your scene and you lose your modifications.

https://github.com/user-attachments/assets/7ad74d07-d5ef-4657-82e8-8547f7f37ca7

I expected a confirmation dialog like this after saving external resource and closing scene:

Screenshot 2024-08-25 at 6 43 42 PM

### Steps to reproduce

- Open a scene containing a built-in resource
- Save the resource as an external resource
- Close the scene
- You don't get a warning to save your scene
- Your scene keeps using a built-in resource instead the external resource

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #96087
- Fixes #44053

There was no unsaved indicator on the scene after using "Save As..." on an internal resource. That caused the issue where the user did not get a warning if he closed the scene after doing the "Save As..." option.

I added a connect to the `resource_saved` signal on the EditorNode to know when the resource was saved. The signal is only disconnected when the `EditorResourcePicker` exit the tree. I don't think it's possible that the `resource_saved` signal could be emitted for the `edited_resource` on `EditorResourcePicker` on which the "Save As..." was used without it to be removed from the tree.

### CODE REVIEW

File: editor/editor_resource_picker.cpp [hunk 1]
```diff
@@ -175,6 +175,13 @@ void EditorResourcePicker::_file_quick_selected() {
 	_file_selected(quick_open->get_selected());
 }
 
+void EditorResourcePicker::_resource_saved(Object *p_resource) {
+	if (edited_resource != nullptr && p_resource == edited_resource.ptr()) {
```
Comment (KoBeWi) [inline editor/editor_resource_picker.cpp:179]:
```suggestion
	if (edited_resource.is_valid() && p_resource == edited_resource.ptr()) {
```

File: editor/editor_resource_picker.cpp [hunk 2]
```diff
@@ -408,6 +415,9 @@ void EditorResourcePicker::_edit_menu_cbk(int p_which) {
 			if (edited_resource.is_null()) {
 				return;
 			}
+			if (!EditorNode::get_singleton()->is_connected("resource_saved", callable_mp(this, &EditorResourcePicker::_resource_saved))) {
```
Comment (KoBeWi) [inline editor/editor_resource_picker.cpp:418]: You can store the callable in a variable to avoid repeating it.

**Review by KoBeWi — APPROVED** [review]

File: editor/editor_resource_picker.cpp (hunk 1 above)
Comment (Hilderin) [reply editor/editor_resource_picker.cpp]: Done!
