### PR TITLE
ResourceLoader: Fix deadlocks caused by the resource changed feature

### LINKED ISSUE #96790: GradientTexture2D causing editor to hang when quitting
### Tested versions

Reproducible in commit 21249950da50e094b141f73646fd477d7832c8db
v4.4.dev.custom_build [21249950d]

### System information

Godot v4.4.dev (21249950d) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

Godot was hanging on Ctrl+Q and it took me some time to narrow it down to a single resource (tres) file.

If you have a GradientTexture2D resource, the editor hangs.

### Steps to reproduce

Here is the tres file `res://GradientTexture2D_0b38e39cdb.tres`
```
[gd_resource type="GradientTexture2D" load_steps=2 format=3 uid="uid://dnsglu4oyarhq"]

[ext_resource type="Gradient" uid="uid://btib1unck3eqp" path="res://Gradient_70322a07ed.tres" id="1_tvpoa"]

[resource]
gradient = ExtResource("1_tvpoa")
```

And the Gradient `res://Gradient_70322a07ed.tres`
```
[gd_resource type="Gradient" format=3 uid="uid://btib1unck3eqp"]

[resource]
```

### Minimal reproduction project (MRP)

All you need is those two resources in an empty project.

### PR DESCRIPTION
**Pull request by RandomShaper**
- One commit is another fixup to #96593. (Despite the `DEFVAL(1)`, the callable would fail due to not enough arguments unless I explicitly bind an argument!)
- The other commit applies to the resource previewer. The main thread shouldn't be blocked when there are loads in progress, or otherwise the resource changed connections can't be flushed to it. You shouldn't block the main thread regardless this, even if we support busy polling the status of threaded resource loads, but that's a bonus. And the resource previewer was busy looping upon waiting for its thread to exit. It was letting the rendering server sync, but that's only part of the whole picture. In situations like that you'd rather run a full iteration, guaranteeing the engine "breathes" and can make progress in anything async.

Fixes #96790.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Cherry-pick for 4.3 included in #96606.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -3423,12 +3423,13 @@ int EditorNode::_next_unsaved_scene(bool p_valid_filename, int p_start) {
 
 void EditorNode::_exit_editor(int p_exit_code) {
 	exiting = true;
-	resource_preview->stop(); // Stop early to avoid crashes.
```
Comment (akien-mga) [inline editor/editor_node.cpp:3426]: This needs _really_ thorough testing. The resource previewer is one of the most crash, deadlock and regression prone code in the editor - as this comment points out. Running `Main::iteration()` explicitly is also almost always a recipe for disaster. Please quadruple check that this is working well in complex scenarios (with and without resource previews pre-existing in the user cache folder).

**Comment by basicer** [comment]
Can confirm this patch fixes the patch I was seeing with deadlocks in `EditorResourcePreviewGenerator::generate_from_path`.

File: editor/editor_node.cpp (hunk 1 above)
Comment (RandomShaper) [reply editor/editor_node.cpp:3426]: - Regarding how early the previewer has to be stopped, that code and comment were added in #24206. Formerly, the previewer was stopped on destruction, much later. And that of course would summon many demons. My assessment is that it's safe to do the controlled stop anywhere in this function. However, I just intended the editor dim to happen earlier, so I'll play it supersafe and just keep this function intact.
- About `Main::iteration()`, the only calls needed from it are `RenderingServer::sync()` and `MessageQueue::flush()`. Those are the currently known heartbeats that keep rendering and resource loading reactive. I chose to run an iteration so this code doesn't get outdated whenever there's a new requirement in that regard. However, now we're aware, I'm changing this to is supersafe: the code will do both calls explicitly instead of invoking a full iteration.

I'm pushing both changes. Verified the issue is still fixed after removing `.godot/`.

Thanks for the warning, because we definitely will enjoy a regression-freer period. 😀

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
