### PR TITLE
Fix `AudioStreamPlayback`'s `_stop()` not being called when `AudioStreamPlayer`'s `stop()` is called

### LINKED ISSUE #97466: AudioStreamPlayback method `_stop()` is not called when `AudioStreamPlayer.stop()` is called
### Tested versions

4.2.2.stable, 4.3.stable, 4.4.dev2

### System information

Godot v4.3.stable - Windows 10.0.19045

### Issue description

When calling `AudioStreamPlayer.stop()`, the corresponding `AudioStreamPlayback`'s `_stop()` method is not called. The [documentation for AudioStreamPlayback._stop()](https://docs.godotengine.org/en/stable/classes/class_audiostreamplayback.html#class-audiostreamplayback-private-method-stop)  says it should get called in this case.

### Steps to reproduce

1. Create a script that extends `AudioStreamPlayback`, and override the `_start()` and `_stop()` methods.
2. Create script that extends `AudioStream` and a corresponding `AudioStream` resource that uses this script. Override the `AudioStream._instantiate_playback()` method, and return a reference to an `AudioStreamPlayback` child object from the previous step.
3. Create a new scene with an `AudioStreamPlayer` node. Set its `stream` property to the `AudioStream` resource from the previous step. Add a script to the node and call the `play()` method, followed by a call to the `stop()` method. Run the project and note that `AudioStreamPlayback._stop()` is not called.  

### Minimal reproduction project (MRP)

[playback-stop-mrp.zip](https://github.com/user-attachments/files/17137534/playback-stop-mrp.zip)

When you run the project, observe that the print statement in `AudioStreamPlaybackChild._stop()` is not executed.

### PR DESCRIPTION
**Pull request by SourceOfHTML**
Small fix that resolves #97466 , although I am not very familiar with that part of the code, and where and how the line would be best implemented, because I have very little idea what the rest of the code in the relevant method is about. (Note: Done with assistance from anvilfolk in the Contributor's Chat)

### CODE REVIEW

File: servers/audio_server.cpp [hunk 1]
```diff
@@ -1246,6 +1246,8 @@ void AudioServer::stop_playback_stream(Ref<AudioStreamPlayback> p_playback) {
 			_delete_stream_playback(p_playback);
 		}
 		return;
+	} else {
+		p_playback->stop(); // Hack solution to get _stop() to be called
 	}
```
Comment (adamscott) [inline servers/audio_server.cpp:1251]: The fix is fine! It's not at all a hack solution. So, I suggest that you remove that comment and you don't have to put the code inside an else statement as there's a unilateral return inside the if.

```suggestion
	}

	p_playback->stop();
```

**Review by adamscott — CHANGES_REQUESTED** [review]
Hi there! Thanks for your first contribution! We're close, thanks to you!

File: servers/audio_server.cpp (hunk 1 above)
Comment (SourceOfHTML) [reply servers/audio_server.cpp:1251]: Alright then, I'll make the change, amend the commit, and notify you

Comment (SourceOfHTML) [reply servers/audio_server.cpp]: Done and done!

**Comment by SourceOfHTML** [comment]
what issue does it specifically have with the code style, and how do I get to fixing it?

**Review by adamscott — APPROVED** [review]
Should be good to merge after the style checks. I tested it and it works well!

**Comment by SourceOfHTML** [comment]
Alright, I reckon the correct version of clang-tools is also necessary? One from https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.1 ? I was putting off downloading clang-tools because I don't know which of the files in that list I should download

**Comment by adamscott** [comment]
> what issue does it specifically have with the code style, and how do I get to fixing it?

I think it's because the in-between blank line has whitespace, just make sure that it's an empty line without tabs.

**Comment by adamscott** [comment]
> Alright, I reckon the correct version of clang-tools is also necessary? One from https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.1 ? I was putting off downloading clang-tools because I don't know which of the files in that list I should download

On which OS are you? You don't have to download the files manually.

**Comment by SourceOfHTML** [comment]
Windows

**Comment by adamscott** [comment]
> Windows, specifically Windows10

I think that by installing LLVM with [scoop](https://scoop.sh/#/), you'll be able to have clang-format.

**Comment by SourceOfHTML** [comment]
I don't know if Github automatically notifies you, but it finished the checks

**Comment by SourceOfHTML** [comment]
I got LLVM and clang-format, woo! Thank you!

**Comment by SourceOfHTML** [comment]
SORRY sorry that should not have happened, I'll revert it, apologies to all involved parties

**Comment by Zireael07** [comment]
At this point you've got to close this PR and remake it from scratch, you messed up rebasing

**Comment by SourceOfHTML** [comment]
RIght yes that makes sense, I'll do that at some point

**Comment by mhilbrunner** [comment]
Don't worry too much about it, everyone has to learn sometime and Git is a complicated beast. Thanks for contributing.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
