### PR TITLE
Make GDScript allow some keywords as identifiers

### LINKED ISSUE #8085: Can't call methods or access properties with names identical to GDScript keywords
*bugsquad edit: * Original title was: "**Can't call VisualServer.sync()**"

**Operating system or device - Godot version:**
Godot 2.2 / 3.0

**Issue description:**

`VisualServer.flush()` is renamed to `sync()` at b524b40fdc5325c840192ce92dbed8108ccef2d9
And `sync` became a keyward for high level network function.
So, now, `VS.sync()` makes error `Expected identifier as member`

**Steps to reproduce:**
```gdscript
func _ready():
    VS.sync()
    VS.call("sync") # workaround
```

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #8085

Here is a test script:
```gdscript
extends SceneTree

func log(a): # Call with self.log()
	print(a)

func _initialize():
	var dict = {
		"true": 1,
		"false": 1,
		"null": 1,
		"sync": 1,
		"remote": 1,
		"slave": 1,
		"if": 1,
		"match": 1,
	}

	print(dict.true)
	print(dict.false)
	print(dict.null)
	print(dict.sync)
	print(dict.remote)
	print(dict.slave)
	print(dict.if)
	print(dict.match)
	print(log(1))
	print(self.log(1))
	quit()
```

Here are some things that won't work with this changes:
```gdscript
var var = 1
var const = 1
var func = 1

func and(a, b): # Technical issues for this one, since it is equivalent to func &&(a, b):..
```
And here are some strange ones that would work
```gdscript
func var(): pass # Call with self.var()
func func(): pass # self.func() or just func() if lambda isn't merged
class class:
  static func static(): return true
func _ready():
  self.var()
  self.func()
  print(class.static()) # true
```

### CODE REVIEW

File: modules/gdscript/gd_parser.cpp [hunk 1]
```diff
@@ -3094,9 +3089,9 @@ void GDParser::_parse_class(ClassNode *p_class) {
 							tokenizer->advance(); //var before the identifier is allowed
 						}
 
-						if (tokenizer->get_token() != GDTokenizer::TK_IDENTIFIER) {
+						if (!tokenizer->is_token_literal(0, true)) {
 
-							_set_error("Expected identifier for argument.");
+							_set_error("Expected literal for argument.");
```
Comment (karroffel) [inline modules/gdscript/gd_parser.cpp]: literal? It's still an identifier. It's just that the identifier might have the same name as a keyword, it's an identifier nonetheless.

Usually "constant values" (like a string or a number) are called literals. I'd keep the old error message.

File: modules/gdscript/gd_parser.cpp [hunk 2]
```diff
@@ -3965,11 +3960,11 @@ void GDParser::_parse_class(ClassNode *p_class) {
 
 					if (tokenizer->get_token() != GDTokenizer::TK_COMMA) {
 						//just comma means using only getter
-						if (tokenizer->get_token() != GDTokenizer::TK_IDENTIFIER) {
-							_set_error("Expected identifier for setter function after 'notify'.");
+						if (!tokenizer->is_token_literal()) {
+							_set_error("Expected literal for setter function after 'setget'.");
```
Comment (karroffel) [inline modules/gdscript/gd_parser.cpp]: Old relict? 😄 This is more descriptive, cool. But I'd still change it to back to identifier.

**Review by karroffel — CHANGES_REQUESTED** [review]
Looks good so far, I'd keep the old error messages though.

File: modules/gdscript/gd_parser.cpp (hunk 1 above)
Comment (bojidar-bg) [inline modules/gdscript/gd_parser.cpp]: Ookay, would revert that part.

**Comment by bojidar-bg** [comment]
@karroffel Fixed

**Review by karroffel — APPROVED** [review]
👍 Looks good!

**Comment by akien-mga** [comment]
Since we now prevent naming variables like properties of the base class (e.g. if you name a member variable `position` or `rotation` in a Node2D, the debugger will raise an error), I think it's unnecessary to allow some half-shadowing of keywords and global scope methods. Because to be consistent we'd have to allow the same for member variables, and it would just become very confusing.

I think Godot users will learn to live with this limitation, it might be frustrating a couple times, but then you make do and benefit from the consistency.

**Comment by bojidar-bg** [comment]
@akien-mga Still, I think we should allow calling methods like `sync` or `log`, even if we disallow creating variables or methods with such names.

**Comment by akien-mga** [comment]
Well if we disallow creating them, it makes no sense to allow calling them, since the situation would never arise.

**Comment by bojidar-bg** [comment]
@akien-mga That's wrong, since we can just have a GDNative or C# script which would be free to register them...

**Comment by akien-mga** [comment]
So what should we do here (apart from a needed rebase)?

**Comment by vnen** [comment]
I'm OK with this change as it fixes some current problems, like String.match() that can't be called. Creating functions with keywords as names should be documented to explain the need of the `self.` prefixing.

**Comment by akien-mga** [comment]
@bojidar-bg You've got the go from @reduz, albeit you need to add some more documentation (and rebase):
```
<reduz> it's ok, but i would add a bit more doc on the source code to make sure what everything is doing and why, since it's clearly an usability hack
<reduz> as in, anyone who looks at the source eould expect to find TK_IDENTIFIER in the switch, for example
<reduz> so explaining those hacks would be a good idea
```

**Comment by bojidar-bg** [comment]
Ok, rebased, now I would have to think how to include the doc. 😃

**Comment by bojidar-bg** [comment]
(Bump, done, updating for email notifications)

**Comment by reduz** [comment]
we really should update all docs..

**Comment by Geequlim** [comment]
After this commit the GDScript is totally broken!

image

image

**Comment by akien-mga** [comment]
Let's give @bojidar-bg some time to try a fix :)

**Comment by akien-mga** [comment]
@Geequlim Fixed by #9846.
