### PR TITLE
Fix wrong mouse wheel position for MOUSE_MODE_CAPTURED on Windows

### LINKED ISSUE #29559: Using mouse wheel with MOUSE_MODE_CAPTURED is changing mouse position
Godot 3.1.1
Windows 10 64 bits

I use `get_viewport().get_mouse_position()` in order to get a ray to the 3D world from within `_physics_update`. However, I found that if I use `MOUSE_MODE_CAPTURED`, scrolling the mouse wheel will make the function return bad coordinates, until you move the mouse again. I expect this should not happen, mouse wheel is not supposed to move the mouse in any way.

Project:
[MousePositionWheel.zip](https://github.com/godotengine/godot/files/3263507/MousePositionWheel.zip)
Run the main scene, notice the mouse position is correctly reported (most often near the center). Then use mouse wheel, you'll see it changes by a lot, until you move the mouse again.

### PR DESCRIPTION
**Pull request by yamgent**
WM_MOUSEWHEEL and WM_MOUSEHWHEEL report mouse coordinates relative to
the screen (see lParam in [1]), rather than to the window like the rest
of the mouse events.

The current code already makes adjustments to take that into account.

However, it only makes the adjustments if the mouse is not captured, and
the coordinates are always relative to the screen regardless of whether
the mouse is captured or not, so let's fix the code to always
consistently apply the adjustments.

This fixes #29559.

[1] - https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousewheel

### CODE REVIEW

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -719,7 +719,7 @@ LRESULT OS_Windows::WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
 						pressrc = 0;
 					}
 				}
-			} else if (mouse_mode != MOUSE_MODE_CAPTURED) {
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp]: For the reference, I checked and this code has been this way since Godot was open sourced in 2014, so noone to blame for it :)

**Comment by akien-mga** [comment]
Thanks!
