### PR TITLE
Fix Clear Inheritance issues

### LINKED ISSUE #91776: Clear Inheritance on Inherited Scene from base Scene with children with signals does not unlock signals until editor restart
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 860M (nvidia; 535.161.07) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

When editing an inherited scene, you can right-click > Clear Inheritance to break the link with the inherited scene and make it its own scene. This is similar to Make Local on an instantiated scene, but the special wording only appears when the scene root itself is the instance.

image

When the base scene has children with connected signals, and you Clear Inheritance, the signals remain displayed in yellow, indication a locked, read-only state. Right-clicking on them will show that Edit... and Disconnect are indeed grayed out.

image

Restarting the editor will clear the read-only state, showing that this was just a bug indeed.

### Steps to reproduce

1. In MWE, open prefab_child_to_test.tscn
2. Right-click on its root > Clear Inheritance and confirm undoable action
3. Select the child Node2D
4. Go to Node tab > Signals > draw > observe how `.. :: _on_node_2d_draw()` is still yellow
5. Since Clear Inheritance is undoable, to repeat, delete prefab_child_to_test.tscn, duplicate prefab_child.tscn into prefab_child_to_test.tscn and repeat steps from 1.
6. Bonus: restart the editor and see how signal is now in white, and editable

### Minimal reproduction project (MRP)

[v4.2.1 - Clear inheritance of instantiated scene keeps signals locked.zip](https://github.com/godotengine/godot/files/15266966/v4.2.1.-.Clear.inheritance.of.instantiated.scene.keeps.signals.locked.zip)

### PR DESCRIPTION
**Pull request by xuhuisheng**
* *fixes: https://github.com/godotengine/godot/issues/91776#issuecomment-3344222025*

There are so many problems when invoking `Clear Inheritance`

- After confirm 'Clear Inheritance? (No Undo)', the scene didn't do save really.
- There is no `unsaved (*)` mark on the title of editor.
- The children node of scene root cannot be renamed.
- The signal in the right side `NodeDock` is readonly.

There latest comment gives me a clue, that we can save scene and reload scene directly, then all of these issues resolved.

---

Edit:

Follows KobeWi suggestion, don't save and reload scene, but update node in memory and mark unsaved.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Is it possible to achieve the same without saving and reloading scene? If the scene is not saved, you can "undo" the change by reloading the scene, which is useful option.

You can clear scene's undo history and it will mark the scene as unsaved with no way of undo. Not sure about other problems, but it should be possible to fix them too.

**Comment by xuhuisheng** [comment]
> Is it possible to achieve the same without saving and reloading scene? If the scene is not saved, you can "undo" the change by reloading the scene, which is useful option.

I can give it a try, but recreating the entire hierarchy, as reloading it from a file, would need lots of works.

**Comment by KoBeWi** [comment]
I think the problem is that `update_tree()` does not take effect for some reason (or it's updated wrong). The fix might be simply forcing a refresh. It should be possible without reload, and without lots of changes.

For a hacky solution, calling `scene_tree->set_valid_types({})` will force full tree update, but I think a dedicated method would be better.

**Comment by xuhuisheng** [comment]
> I think the problem is that `update_tree()` does not take effect for some reason (or it's updated wrong). The fix might be simply forcing a refresh. It should be possible without reload, and without lots of changes.

In my investigation, the "Clear Inheritance" operation is not complete. It only clean `inheritated_state` and emit an event, without clear all of it's children state. So after `update_tree`, we still get the old children's state.

https://github.com/godotengine/godot/blob/e825169957e4ec67bc0baa6168af02b337399f6f/scene/main/node.cpp#L2809-L2813

And before "Clear Inheritance", there is only one node with a reference for an "ext_resource".

```
[ext_resource type="PackedScene" uid="uid://bowuloxmdkrly" path="res://prefab.tscn" id="1_by10c"]
[node name="PrefabChildToTest" instance=ExtResource("1_by10c")]
```

After "Clear Inheritance", we need create the real tree structure for the new scene.

```
[ext_resource type="Script" uid="uid://cdao4baykx3v" path="res://prefab.gd" id="1_3o2mv"]
[node name="PrefabChildToTest" type="Node2D"]
script = ExtResource("1_3o2mv")
[node name="Node2D" type="Node2D" parent="."]
[connection signal="draw" from="Node2D" to="." method="_on_node_2d_draw"]
```

I agree the current PR is not so good. I can do more digging to find a better solution.

---

**Edit:**

`scene_tree->set_valid_types({})` can resolve the left menu tree warning, but signal warning on Inspector is still.
I will keep digging.

**Comment by xuhuisheng** [comment]
@KoBeWi 

I found `check_and_update_scene()` supports reload scene from memory. Please take a look when you have time.

BTW: There is a compilation error on windows platform. Looks like ret_nodes maybe unintiliazed on some situations. I don't know how to fix it, yet.

```
scene\resources\packed_scene.cpp:702:27: error: '*ret_nodes' may be used uninitialized [-Werror=maybe-uninitialized]
  702 |         return ret_nodes[0];
```

Maybe related this: https://github.com/godotengine/godot/pull/111771

File: editor/scene/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1728,6 +1728,10 @@ void SceneTreeEditor::set_display_foreign_nodes(bool p_display) {
 	_update_tree();
 }
 
+void SceneTreeEditor::clear_cache() {
+	set_valid_types({});
```
Comment (KoBeWi) [inline editor/scene/scene_tree_editor.cpp]: That's wrong. It should be
```C++
node_cache.force_update = true;
callable_mp(this, &SceneTreeEditor::_update_tree).call_deferred(false);
tree_dirty = true;
```
And then you can call it in `set_valid_types()`.

File: editor/editor_data.h [hunk 2]
```diff
@@ -219,6 +219,7 @@ class EditorData {
 	void set_edited_scene_live_edit_root(const NodePath &p_root);
 	NodePath get_edited_scene_live_edit_root();
 	bool check_and_update_scene(int p_idx);
+	bool reload_scene_from_memory(int p_idx, bool need_mark_unsaved);
```
Comment (KoBeWi) [inline editor/editor_data.h]:
```suggestion
	bool reload_scene_from_memory(int p_idx, bool p_mark_unsaved);
```

File: editor/editor_data.cpp [hunk 3]
```diff
@@ -706,40 +706,55 @@ bool EditorData::check_and_update_scene(int p_idx) {
...
+
+	new_scene->set_scene_file_path(edited_scene[p_idx].root->get_scene_file_path());
+	Node *old_root = edited_scene[p_idx].root;
+	EditorNode::get_singleton()->set_edited_scene(new_scene);
+	memdelete(old_root);
+	edited_scene.write[p_idx].selection = new_selection;
+
+	if (need_mark_unsaved) {
+		EditorUndoRedoManager::get_singleton()->clear_history();
+		EditorUndoRedoManager::get_singleton()->set_history_as_unsaved(get_current_edited_scene_history_id());
```
Comment (KoBeWi) [inline editor/editor_data.cpp]: You don't need to clear the whole history.
```suggestion
		EditorUndoRedoManager::get_singleton()->clear_history(get_scene_history_id(p_idx));
```

**Review by KoBeWi — COMMENTED** [review]
Some minor details left, but the implementation looks ok now.

File: editor/editor_data.cpp (hunk 3 above)
Comment (xuhuisheng) [reply editor/editor_data.cpp]: @KoBeWi 
Do you mean not clear history? Because I need `set_history_as_unsaved()` to mark current scene as `unsaved`.

Comment (KoBeWi) [reply editor/editor_data.cpp]: `clear_history()` with `p_increase_version` set to `true` (default) automatically marks the scene as unsaved.
`clear_history()` with no arguments (like you did) will clear the history for all scenes, which is unnecessary here.

Comment (xuhuisheng) [reply editor/editor_data.cpp]: Thank you for explaination.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
