### PR TITLE
Fix to occlusion culling where all math is based on Euclidean distance.

### LINKED ISSUE #94210: Occlusion Culling falsely culls large objects visible through small openings when touching the edge of the viewport
### Tested versions

Reproducible in 4.3-beta2 and 4.2.2-stable.

### System information

Arch Linux w/ X11 and  Windows 10 using Radeon RX6800XT

### Issue description

Occlusioin culling falsely culls a large object that is mostly obsured, but still visible through an opening in a wall in certain spatial configurations.

Here the red block is visible (expected):
Clipboard - July 10, 2024 11_13 PM-1

And here it is culled (unexpected):
Clipboard - July 10, 2024 11_13 PM

Video demonstrations in Liblast project:
https://youtu.be/xQW2PNNUggw (Godot 4.2.2-stable)
https://youtu.be/kfxirWBtZQ4 (Godot 4.3-beta2)

### Steps to reproduce

0. Open Blender
1. Model a big block (like 20x20x8 meters)
2. Model a wall with an opening in the middle (like 30x10, with the opening like 1x2)
3. Import both models into Godot
4. Enable occlusion culling and bake occluders
5. Look at the big block through the opening in the wall, so that the wall edges aren't visible in the viewport, but the opening touches the left or right edge of the screen (or even a corner).
6. At a certain combination of camera position and rotation the big block will be culled while still very much visible through the opening in the wall.

### Minimal reproduction project (MRP)

Run the game to see an animated demo.

[MRP.zip](https://github.com/user-attachments/files/16175699/MRP.zip)

### PR DESCRIPTION
**Pull request by Rudolph-B**
Alternative solution to #94210. Main discussion can be found here #97712

The occlusion culler uses a point to compare with the depth mipmap to determine if an object is occluded or not. The occlusion culler currently chooses the point with the shortest Euclidean distance to the camera. While not entirely inaccurate, it can drift when compared to the actual closest point to the camera in terms of depth.

This inaccuracy increases when an object's AABB is skewed (relative to the camera perspective) and partially occluded by other objects, as seen in the MRP in #94210 and the 2D example below.

Screenshot from 2024-10-01 21-37-13

There were two possible solutions to this problem, and this PR implements the first solution.

Possible solutions:
1. Convert the entire occlusion culling algorithm to use Euclidean distance.
2. Select the closest point based on depth. (#97712)

This PR converts the depthmap used for occlusion culling to euclidean distance. Additionally logic is then added for an orthogonal camera. 

_bugsquad edit: Fixes https://github.com/godotengine/godot/issues/94210_

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. The overocclusion issue from https://github.com/godotengine/godot/issues/94210 no longer occurs, yet the level of occlusion remains similar as seen in the Overdraw debug draw mode.

However, in the MRP from https://github.com/godotengine/godot/issues/94210, no occlusion culling seems to occur with an orthogonal camera in the editor (using the Overdraw debug draw mode for a preview). This occurs in both `master` and this PR, so the issue is likely somewhere else:

image

Either way, this resolves the original issue, so it could be merged now already.

**Comment by lawnjelly** [comment]
Although I was initially thinking #97712 would be simpler, having had a look at that PR last night, there are a number of gotchas with that method that are unresolved. This PR on the other hand ends up being simpler than expected, and sidesteps these gotchas, so on balance I now would be thinking of trying this method first.

Of course we will only know snags after some trial in the wild.

File: servers/rendering/renderer_scene_occlusion_cull.h [hunk 1]
```diff
@@ -83,6 +83,10 @@ class RendererSceneOcclusionCull {
 				Vector3 corner = Vector3(p_bounds[0] * c.x + p_bounds[3] * nc.x, p_bounds[1] * c.y + p_bounds[4] * nc.y, p_bounds[2] * c.z + p_bounds[5] * nc.z);
 				Vector3 view = p_cam_inv_transform.xform(corner);
 
+				if (p_cam_projection.is_orthogonal()) {
+					min_depth = MIN(min_depth, view.z);
+				}
```
Comment (lawnjelly) [inline servers/rendering/renderer_scene_occlusion_cull.h:88]: Will this orthogonal case be susceptible to the same problem as the other PR? Namely that a large AABB may come close to the camera z near far off from the view frustum?

I'm not absolutely sure this will be the best way to handle this in the orthogonal case, as is.

Comment (Rudolph-B) [reply servers/rendering/renderer_scene_occlusion_cull.h:88]: This ends up being the exact same math as in the other PR for the the orthogonal case. So the same issue will exist yes, but I don't think think the we have any other option at the moment.

**Review by lawnjelly — APPROVED** [review]

File: servers/rendering/renderer_scene_occlusion_cull.h (hunk 1 above)
Comment (lawnjelly) [reply servers/rendering/renderer_scene_occlusion_cull.h:88]: You can probably do something like identify the closest vert on the AABB, then intersect the 3 line segments with the frustum edges to find the real closest point, if the AABB straddles the view frustum. This might be simpler as the view is orthogonal.

Whether this will lead to that many more being rejected in practice I don't know, as there are the other snags with the algorithm with slanted AABBs.

But something that could be left to follow up.

Comment (Rudolph-B) [reply servers/rendering/renderer_scene_occlusion_cull.h:88]: That makes sense. Will look into it.

**Comment by clayjohn** [comment]
Looks good to me. I also tested locally and can confirm that the overocclusion issues in the MRP are fixed and there is no noticeable increase in false negatives (from eyeballing).

Let's go ahead with this PR and see if things improve in the wild.

**Comment by clayjohn** [comment]
Thank you! And great work everyone!
