### PR TITLE
Fix segment intersection in Geometry2D

### LINKED ISSUE #54695: RayCast2D returning incorrect hit locations in TileMap collisions
### Godot version

v4.0.dev.calinou [78931aa04]

### System information

Windows 10

### Issue description

RayCast2D's return too soon collision points when testing against TileMap physics layers. This behaviour does not exist when casting against RectangleShapes of the same size (tested at 16x16) or longer RectangleShapes.

The TileSet collision is a single encompassing rectangle. The behaviour persists even if the rectangle is extended beyond 16x16.

This does not occur in Godot 3.4 Stable.
This does occur in v4.0.dev.20211004.official [2e8cba0bd] and in v4.0.dev.calinou [78931aa04].

https://user-images.githubusercontent.com/3820082/140634283-9286e553-2d69-46e2-adcf-bbf452f53414.mp4

### Steps to reproduce

Open the attached MRP in Godot 4.0 and play the main scene. The RayCast2D will return unexpected results in the TileMap collision.

### Minimal reproduction project

[raycast-test-4.zip](https://github.com/godotengine/godot/files/7491804/raycast-test-4.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Doing a multiplication to reduce the amount of tests was causing precision which lead to 2D raycast detecting false positive contacts in some cases with convex polygons.

Fixes #54695 (regression caused by #52110)

### CODE REVIEW

File: core/math/geometry_2d.h [hunk 1]
```diff
@@ -181,8 +181,7 @@ class Geometry2D {
 		D = Vector2(D.x * Bn.x + D.y * Bn.y, D.y * Bn.x - D.x * Bn.y);
 
 		// Fail if C x B and D x B have the same sign (segments don't intersect).
-		// (equivalent to condition (C.y < 0 && D.y < CMP_EPSILON) || (C.y > 0 && D.y > CMP_EPSILON))
-		if (C.y * D.y > CMP_EPSILON) {
```
Comment (akien-mga) [inline core/math/geometry_2d.h:185]: There might also be the possibility to use `CMP_EPSILON2`, i.e. the square of `CMP_EPSILON`, which is closer to 0. But the explicit check is also fine.

**Review by akien-mga — APPROVED** [review]

File: core/math/geometry_2d.h (hunk 1 above)
Comment (pouleyKetchoupp) [reply core/math/geometry_2d.h:185]: I've tried to use `CMP_EPSILON2` and it didn't go well (some unit tests with points exactly on polygon edges were failing).

I thought multiplying the values and using just one threshold was equivalent to the full check, but it looks like it's not the case. It could be because of losing float precision while multiplying, I'm not sure.

**Comment by akien-mga** [comment]
Thanks!
