### PR TITLE
Make retarget keep global rest of unmapped bones if there are no mapped bones on the child

### LINKED ISSUE #91558: Retargeting resets orientation of unmapped bones when `Overwrite Axis` is enabled
### Tested versions

v4.3.dev.custom_build [7ebc866418b075df58cbe4e31fcf8b0c3acd70a1]

### System information

Windows 11

### Issue description

Unmmaped bone orientations are lost (the `Basis` reset to identity) after import when retargeting if `Overwrite Axis` is enabled. It works as expected for mapped bones.

Left: correct orientation. Right: `Overwrite Axis` enabled

image image

Disabling this option keeps their orientation but then retargeting is meaningless because differences in mapped bone and animation rotations between characters aren't normalized.

### Steps to reproduce

* In the MRP, open `main.tscn`.
* In the advanced import setting for `bot.glb`, `Skeleton3D > Retarget > Rest Fixer > Overwrite Axis` is enabled. Rotation reset for the unmapped bones with attachments.
* Disable `Overwrite Axis` and reimport. It keeps rotation.

### Minimal reproduction project (MRP)

[overwrite-rotation.zip](https://github.com/godotengine/godot/files/15209810/overwrite-rotation.zip)

### PR DESCRIPTION
**Pull request by ydeltastar**
Fixes: https://github.com/godotengine/godot/issues/91558

I don't know why this was commented out, as it worked in every case I tested. Unmapped bones are unusable without it since we don't want retargeting to change their rests.

### CODE REVIEW

**Review by fire — COMMENTED** [review]
This makes sense, but I am not sure of any sideeffects.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
> I don't know why this was commented out, as it worked in every case I tested.

No. I remember I commented out them because the bones between the mapped bones have rest rotation on sharing animation in Godot 4 caused corrupting the animation sharing even if the those unmapped bones are not animating.

For example such case:
[LeftUpperArm] - [elbow_l(unmapped)] - [LeftLowerArm] - [wrist_l(unmapped)] - [LeftHand]

I think it's fine to keep their original rest if "there are no mapped bones in their children", so at least that check needs to be made.

**Comment by ydeltastar** [comment]
> For example such case:
> [LeftUpperArm] - [elbow_l(unmapped)] - [LeftLowerArm] - [wrist_l(unmapped)] - [LeftHand

I did tests for cases like this and didn't find issues with keeping the axis. In fact, resetting it breaks the animation when there are unmapped bones between mapped too.

I couldn't find any but isn't having issues due to irregular bone hierarchy when sharing animations the expected behavior? The user should fix the source or maybe they designed the rig like this on purpose. Handling it on the engine side seems to break everything else.

**Comment by TokageItLab** [comment]
In Godot 4, the child mapped rests must match the relative rotation from the parent mapped rest. You should test this in the case where the intermediate bone rotation is different from the parent's rotation.

So if you only apply keep rest when there is a child mapped bone, this change is acceptable, but otherwise we need a workaround with another module such as real time retarget.

**Comment by ydeltastar** [comment]
Okay, now I understand what issue and I could reproduce it. I implemented your request and now this fix is working for both cases.

**Review by TokageItLab — APPROVED** [review]
LGTM

**Review by lyuma — CHANGES_REQUESTED** [review]
In terms of code, it's ok. This is haphazardly changing the rest rotation for some non-human bones, and I think the logic seems a little non-obvious. For example, it checks if a child is mapped, but what about grandchildren.

Will a user understand why a "elbow twist" bone has rotation changed while a "elbow sleeve" bone keeps the original rotation?

Furthermore, there may be users who have created BoneAttachments using the identity Basis and adjusted for it either in code or by manually positioning attached objects. Therefore, this risks compatibility break with any existing scenes / bone attachments. which were made assuming the previous design (which has stayed the same since Godot 4.0 was released)

With Godot 4.3 about to hit beta, this is quite late in the release cycle to be changing a fundamental part of the retargeting design.

At the very least, if we decide to go forward with this change, we need to include a compatibility setting on the retarget settings (Skeleton3D) which defaults to the old behavior for existing files and a different setting for new files.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
Ah yes, sorry I missed that it only looks at the children and not the grandchildren.

As long as we don't reimport them, there should be no compatibility issues, but I don't know how to handle compatibility as I don't have a strong opinion for that.

At least if you change it to check its grandchildren, I still can approve this, IMO. For performance, it would better to scan from parentress_bone to pre-create a whitelist with no mapped descendants and check if the rest rewriting bones are included in it.

**Comment by ydeltastar** [comment]
> At the very least, if we decide to go forward with this change, we need to include a compatibility setting on the retarget settings (Skeleton3D) which defaults to the old behavior for existing files and a different setting for new files.

It was my first intention when I went on this but I thought this was a bug. Since this is the wanted behavior for the importer, I added a `Keep Unmapped Axis` default to false and the check for mapped descendants.

**Comment by TokageItLab** [comment]
For intermediate bones, `Keep Unmapped Axis` is strange because it is discarded even if it is axis ummapped, so it would be a very special property like `compatibility mode`. But I personally do not think this option is necessary. I think it's a pretty rare case where this would cause a problem.

**Comment by lyuma** [comment]
Wouldn't this affect every bone attachment on retargeted skeletons in every existing godot project? I'm not convinced that this is rare.

Also, about reimport, we can't assume that they don't happen. In fact, the whole .godot directory is excluded from git and users are told to delete that directory when there is a problem or if reporting a bug, so it is almost guaranteed that any issues which occur on reimport will eventually occur for a user.

**Comment by TokageItLab** [comment]
The values of the bone attachments may be changed, but I expect that in cases where the original rest is discarded due to override rest, the user will notice that something is strange, like the author of this PR, and therefore it is unusual to create a project that relies on that rest for rotation.

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 1]
```diff
@@ -42,6 +42,7 @@ void PostImportPluginSkeletonRestFixer::get_internal_import_options(InternalImpo
 		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/apply_node_transforms"), true));
 		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/normalize_position_tracks"), true));
 		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/overwrite_axis"), true));
+		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/keep_unmapped_axis"), false));
```
Comment (TokageItLab) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:45]: If such an option is added, it should only display when override rest is enabled.

Also, the naming must be changed since the bones between the mapped bones will be changed even though they are not mapped. Such as `Keep Global Rest Outside of Map` since global rest is kept but local rest is changed.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp (hunk 1 above)
Comment (ydeltastar) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:45]: Maybe `Skip Unmapped Ends`? Also, make it a subcategory with the title "Overwrite Axis" and options `Enabled` and `Skip Unmapped Ends`.

I'm not strong on compatibility either. I have been using `Overwrite Axis` disabled since 4.2 because I looks like a bug, but once we introduce characters with different body types, this option is unavoidable. I can't think of a common situation where a user wants these bones to reset rotation on import because their only purpose is to transform attachments.

Comment (lyuma) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp]: Does "Preserve leaf axes" sound better?

I think I am feeling a bit better about this after some thought.

The other thing is I would like this to default to true (don't overwrite leaf bone axis) on new imports if possible, but I am not sure how.

As long as the behavior does not change for existing .import files, I think I would be ok getting this in for 4.3

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 2]
```diff
@@ -41,8 +41,9 @@ void PostImportPluginSkeletonRestFixer::get_internal_import_options(InternalImpo
 	if (p_category == INTERNAL_IMPORT_CATEGORY_SKELETON_3D_NODE) {
 		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/apply_node_transforms"), true));
 		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/normalize_position_tracks"), true));
-		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/overwrite_axis"), true));
 		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/reset_all_bone_poses_after_import"), true));
+		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/overwrite_axis"), true));
+		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/skip_unmapped_ends"), false));
```
Comment (TokageItLab) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:46]:
```suggestion
		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/overwrite_axis", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED), true));
		r_options->push_back(ResourceImporter::ImportOption(PropertyInfo(Variant::BOOL, "retarget/rest_fixer/preserve_leaf_axis_visually"), false));
```

As @lyuma's sugesstion `Preserve Leaf Axes`, so I suggest `Preserve Leaf Axis Visually` for consistency and for the sake of correctness of explanation of behavior.

Also needs `get_internal_option_visibility` implementation to hide it when `!bool(p_options["retarget/rest_fixer/overwrite_axis"])`, I have sent a PR #91641 that will be helpful as the reference for this, please check it out.

**Review by TokageItLab — CHANGES_REQUESTED** [review]

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp (hunk 2 above)
Comment (lyuma) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:46]: The word "Visually" is confusing. It has no visual effect on imported models. just like "overwrite bone axis": it only affects the axis convention.

Just like Overwrite Axis, it affects which bones have overwritten axis.

The reason it appeared to have a visual effect in the original issue is because they had created content assuming a different convention, and the convention change led to different orientations.

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:46]: @lyuma So `Keep Global Rest on Leaf`? By “visually” I mean the global rest. The problem is that the value of local rest is changed even though it is set to hold.

Comment (ydeltastar) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:46]: Aren't leaf bones dummies for determining the orientation or length of the last bone in a chain, like another bone after the fingertip bone? I don't think it fits the context here.

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:46]: Well, indeed. We originally should wanted to mean outside of Mapped End, but I don't think there is a good word for that.

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:46]: How about `Keep Global Rest for Leftovers`

Comment (ydeltastar) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:46]: It'll be hard being descriptive with short names. There is an option as long as `Reset All Bone Poses After Import` so `Keep Global Rest on Leftovers` sounds good. It describes what the implementation is doing and in plain terms.

**Review by lyuma — APPROVED** [review]
With an import option here it's ok.

Note: queue vector .erase(), whitelist vector .has() and nested for loop are all order N^2 time complexity. This is an endemic problem with the Godot import code and not isolated to this codepath so I'll approve anyway.

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 3]
```diff
@@ -447,6 +448,48 @@ void PostImportPluginSkeletonRestFixer::internal_process(InternalImportCategory
...
+			// Scan hierarchy and populate a whitelist of unmapped bones without mapped descendants.
+			Vector<int> keep_bone_rest;
+			if (skip_unmapped_ends) {
+				Vector<int> bones_to_process = src_skeleton->get_parentless_bones();
+				while (bones_to_process.size() > 0) {
+					int src_idx = bones_to_process[0];
+					bones_to_process.erase(src_idx);
+					Vector<int> src_children = src_skeleton->get_bone_children(src_idx);
+					for (int i = 0; i < src_children.size(); i++) {
+						bones_to_process.push_back(src_children[i]);
```
Comment (AThousandShips) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:462]:
```suggestion
					for (const int &src_child : src_children) {
						bones_to_process.push_back(src_child);
```
You can use for-each syntax here

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 4]
```diff
@@ -447,6 +448,48 @@ void PostImportPluginSkeletonRestFixer::internal_process(InternalImportCategory
...
+						// Scan descendants for mapped bones.
+						bool found_mapped = false;
+
+						Vector<int> decendants_to_process = src_skeleton->get_bone_children(src_idx);
+						while (decendants_to_process.size() > 0) {
+							int desc_idx = decendants_to_process[0];
+							decendants_to_process.erase(desc_idx);
+							Vector<int> desc_children = src_skeleton->get_bone_children(desc_idx);
+							for (int i = 0; i < desc_children.size(); i++) {
+								decendants_to_process.push_back(desc_children[i]);
```
Comment (AThousandShips) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:476]:
```suggestion
							for (const int &desc_child : desc_children) {
								decendants_to_process.push_back(desc_child);
```

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 5]
```diff
@@ -53,6 +54,15 @@ void PostImportPluginSkeletonRestFixer::get_internal_import_options(InternalImpo
...
 
+Variant PostImportPluginSkeletonRestFixer::get_internal_option_visibility(InternalImportCategory p_category, bool p_for_animation, const String &p_option, const HashMap<StringName, Variant> &p_options) const {
+	if (p_category == INTERNAL_IMPORT_CATEGORY_SKELETON_3D_NODE) {
+		if (p_option == "retarget/rest_fixer/keep_global_rest_on_leftovers") {
+			return bool(p_options["retarget/rest_fixer/overwrite_axis"]);
+		}
+	}
+	return true;
+}
+
```
Comment (TokageItLab) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:65]: It looks a bit inconsistent with other similar parts, but since the result is not different, it should not be a problem.

**Review by TokageItLab — APPROVED** [review]

**Comment by ydeltastar** [comment]
Rebased with master.

**Comment by akien-mga** [comment]
Thanks!
