### PR TITLE
Use correct AABB for SpotLight3Ds when `spot_angle > 90`

### LINKED ISSUE #110367: SpotLight3D culling happens too early for with angles above 90 degrees
### Tested versions

- Reproducible in: 4.3.stable, 4.4.1.stable, 4.5.rc1

### System information

Godot v4.5.beta (6c9aa4c7d) - Fedora Linux 42 (KDE Plasma Desktop Edition) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 5090 (nvidia; 575.64.05) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 62.33 GiB memory

### Issue description

SpotLight3D culling happens too early for with ultrawide angles (above 90 degrees). The higher the angle, the more likely the issue will appear when the camera moves or rotates. The issue also depends on the viewport's aspect ratio, with narrower aspect ratios more likely to encounter the issue.

This issue affects all rendering methods.

https://github.com/user-attachments/assets/b3d18a1d-7a1a-4e0b-a1fa-84dede746efd

Note that on Forward+, this is **not** a clustering issue anymore, since it was fixed by https://github.com/godotengine/godot/pull/100236. The issue is likely to be on the CPU culling side instead.

PS: I've also noticed that in Compatibility, the Camera3D preview in the inspector will have incorrect lighting (it looks like it uses the editor viewport lights' positions, but the actual camera for mesh rendering). Not sure if this is related, but I couldn't reproduce this in a blank project.

### Steps to reproduce

- Add a SpotLight3D node. Set its angle to a value like 175 degrees.
- Move and rotate the camera in the 3D editor. The light will eventually disappear, even though it should logically still be on screen.

### Minimal reproduction project (MRP)

[test_spotlight_culling.zip](https://github.com/user-attachments/files/22244377/test_spotlight_culling.zip)

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
I guess in 4bd01a93dc82b4ac5734ac2a4af70d49b4559496 the AABB shown in the editor was updated for SpotLight3Ds to support large angles but the AABB actually used for culling was not.

Fixes https://github.com/godotengine/godot/issues/110367

### CODE REVIEW

File: drivers/gles3/storage/light_storage.cpp [hunk 1]
```diff
@@ -350,7 +350,14 @@ AABB LightStorage::light_get_aabb(RID p_light) const {
 	switch (light->type) {
 		case RS::LIGHT_SPOT: {
 			float len = light->param[RS::LIGHT_PARAM_RANGE];
-			float size = Math::tan(Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE])) * len;
+			float angle = Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE]);
+
+			if (angle > Math::PI / 2.0) {
+				// Light casts backwards as well.
+				return AABB(Vector3(-1, -1, -1) * len, Vector3(2, 2, 2) * len);
+			}
```
Comment (Calinou) [inline drivers/gles3/storage/light_storage.cpp]: Small optimization (the compiler doesn't do it for us as we don't use `-ffast-math`):

```suggestion
			if (angle > Math::PI * 0.5) {
				// Light casts backwards as well.
				return AABB(Vector3(-1, -1, -1) * len, Vector3(2, 2, 2) * len);
			}
```

File: servers/rendering/renderer_rd/storage_rd/light_storage.cpp [hunk 2]
```diff
@@ -432,7 +432,14 @@ AABB LightStorage::light_get_aabb(RID p_light) const {
 	switch (light->type) {
 		case RS::LIGHT_SPOT: {
 			float len = light->param[RS::LIGHT_PARAM_RANGE];
-			float size = Math::tan(Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE])) * len;
+			float angle = Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE]);
+
+			if (angle > Math::PI / 2.0) {
+				// Light casts backwards as well.
+				return AABB(Vector3(-1, -1, -1) * len, Vector3(2, 2, 2) * len);
+			}
```
Comment (Calinou) [inline servers/rendering/renderer_rd/storage_rd/light_storage.cpp]:
```suggestion
			if (angle > Math::PI * 0.5) {
				// Light casts backwards as well.
				return AABB(Vector3(-1, -1, -1) * len, Vector3(2, 2, 2) * len);
			}
```

**Review by Calinou — COMMENTED** [review]
Tested locally on all rendering methods, it works as expected. Code looks good to me.

**Comment by Kaleb-Reid** [comment]
@Calinou I made the suggested changes.

**Review by Calinou — APPROVED** [review]
Looks great now 🙂

File: drivers/gles3/storage/light_storage.cpp [hunk 3]
```diff
@@ -350,7 +350,14 @@ AABB LightStorage::light_get_aabb(RID p_light) const {
...
 			float len = light->param[RS::LIGHT_PARAM_RANGE];
-			float size = Math::tan(Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE])) * len;
+			float angle = Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE]);
+
+			if (angle > Math::PI * 0.5) {
+				// Light casts backwards as well.
+				return AABB(Vector3(-1, -1, -1) * len, Vector3(2, 2, 2) * len);
+			}
+
+			float size = Math::tan(angle) * len;
```
Comment (clayjohn) [inline drivers/gles3/storage/light_storage.cpp]: https://github.com/godotengine/godot/pull/71832 also switched to using `sin` instead of `tan` since `tan` will explode towards infinity as `angle` approaches `Math::PI * 0.5`
```suggestion
			float size = Math::sin(angle) * len;
```

File: servers/rendering/renderer_rd/storage_rd/light_storage.cpp [hunk 4]
```diff
@@ -432,7 +432,14 @@ AABB LightStorage::light_get_aabb(RID p_light) const {
...
 			float len = light->param[RS::LIGHT_PARAM_RANGE];
-			float size = Math::tan(Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE])) * len;
+			float angle = Math::deg_to_rad(light->param[RS::LIGHT_PARAM_SPOT_ANGLE]);
+
+			if (angle > Math::PI * 0.5) {
+				// Light casts backwards as well.
+				return AABB(Vector3(-1, -1, -1) * len, Vector3(2, 2, 2) * len);
+			}
+
+			float size = Math::tan(angle) * len;
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/storage_rd/light_storage.cpp]:
```suggestion
			float size = Math::sin(angle) * len;
```
Same here

**Review by clayjohn — CHANGES_REQUESTED** [review]

File: drivers/gles3/storage/light_storage.cpp (hunk 3 above)
Comment (Kaleb-Reid) [reply drivers/gles3/storage/light_storage.cpp]: Good point, changes made.

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by Repiteo** [comment]
Thanks!
