### PR TITLE
Invalidate `Control` global transform before notifying about resize / rect change

### LINKED ISSUE #92449: Calling get_global_rect() inside an item_rect_changed callback behaves inconsistently
### Tested versions

- Reproducible in: v4.2.1.stable.fedora [b09f793f5]

### System information

Godot v4.2.1.stable (b09f793f5) - Fedora Linux 39 (Workstation Edition) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (nvidia; 550.54.14) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Calling `get_global_rect()` inside a `item_rect_changed` callback behaves inconsistently. Sometimes it gives the rectangle as it was **before** the change that triggered the callback, and sometimes it gives the rectangle as it was **after** the change that triggered the callback.

### Steps to reproduce

1. Create a new project.
2. Create a user interface scene (with a Control node as root).
3. Add a ColorRect as a child of the Control.
4. Attach the following script to the ColorRect.
5. Connect the `item_rect_changed` signal to the appropriate function in the script.
6. Run the project.
7. **While the project is running, move your mouse in and out of the ColorRect.**
8. Observe the output until this bug occurs.

(Also, consider using the script in my next post which throws an error when this bug occurs.)

```gdscript
extends ColorRect


func _ready() -> void:
	var timer := Timer.new()
	timer.wait_time = 1
	timer.autostart = true
	timer.connect(
		'timeout',
		func move():
			var t := Time.get_ticks_msec() / 1000.0
			prints('setting position to: ', Vector2(t, t))
			position = Vector2(t, t)
	)
	add_child(timer)


func _on_item_rect_changed() -> void:
	print('in item_rect_changed callback, get_global_rect() returns: ', get_global_rect())
```

On my computer, the script output the following:

```
Godot Engine v4.2.1.stable.fedora.b09f793f5 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 550.54.14 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 3060
 
setting position to:  (1.481, 1.481)
in item_rect_changed callback, get_global_rect() returns: [P: (1.481, 1.481), S: (192, 192)]
setting position to:  (2.481, 2.481)
in item_rect_changed callback, get_global_rect() returns: [P: (2.481, 2.481), S: (192, 192)]
setting position to:  (3.482, 3.482)
in item_rect_changed callback, get_global_rect() returns: [P: (3.482, 3.482), S: (192, 192)]
setting position to:  (4.483, 4.483)
in item_rect_changed callback, get_global_rect() returns: [P: (4.483, 4.483), S: (192, 192)]
setting position to:  (5.485, 5.485)
in item_rect_changed callback, get_global_rect() returns: [P: (5.485, 5.485), S: (192, 192)]
setting position to:  (6.468, 6.468)
in item_rect_changed callback, get_global_rect() returns: [P: (6.468, 6.468), S: (192, 192)]
setting position to:  (7.469, 7.469)
in item_rect_changed callback, get_global_rect() returns: [P: (7.469, 7.469), S: (192, 192)]
setting position to:  (8.469, 8.469)
in item_rect_changed callback, get_global_rect() returns: [P: (8.469, 8.469), S: (192, 192)]
setting position to:  (9.47, 9.47)
in item_rect_changed callback, get_global_rect() returns: [P: (8.469, 8.469), S: (192, 192)]
setting position to:  (10.47, 10.47)
in item_rect_changed callback, get_global_rect() returns: [P: (9.47, 9.47), S: (192, 192)]
setting position to:  (11.471, 11.471)
in item_rect_changed callback, get_global_rect() returns: [P: (10.47, 10.47), S: (192, 192)]
setting position to:  (12.471, 12.471)
in item_rect_changed callback, get_global_rect() returns: [P: (11.471, 11.471), S: (192, 192)]
setting position to:  (13.471, 13.471)
in item_rect_changed callback, get_global_rect() returns: [P: (12.471, 12.471), S: (192, 192)]
setting position to:  (14.472, 14.472)
in item_rect_changed callback, get_global_rect() returns: [P: (13.471, 13.471), S: (192, 192)]
setting position to:  (15.472, 15.472)
in item_rect_changed callback, get_global_rect() returns: [P: (14.472, 14.472), S: (192, 192)]
setting position to:  (16.473, 16.473)
in item_rect_changed callback, get_global_rect() returns: [P: (15.472, 15.472), S: (192, 192)]
setting position to:  (17.473, 17.473)
in item_rect_changed callback, get_global_rect() returns: [P: (16.473, 16.473), S: (192, 192)]
setting position to:  (18.474, 18.474)
in item_rect_changed callback, get_global_rect() returns: [P: (17.473, 17.473), S: (192, 192)]
setting position to:  (19.474, 19.474)
in item_rect_changed callback, get_global_rect() returns: [P: (18.474, 18.474), S: (192, 192)]
setting position to:  (20.475, 20.475)
in item_rect_changed callback, get_global_rect() returns: [P: (19.474, 19.474), S: (192, 192)]
setting position to:  (21.475, 21.475)
in item_rect_changed callback, get_global_rect() returns: [P: (20.475, 20.475), S: (192, 192)]
setting position to:  (22.459, 22.459)
in item_rect_changed callback, get_global_rect() returns: [P: (21.475, 21.475), S: (192, 192)]
setting position to:  (23.459, 23.459)
in item_rect_changed callback, get_global_rect() returns: [P: (22.459, 22.459), S: (192, 192)]
setting position to:  (24.46, 24.46)
in item_rect_changed callback, get_global_rect() returns: [P: (23.459, 23.459), S: (192, 192)]
setting position to:  (25.46, 25.46)
in item_rect_changed callback, get_global_rect() returns: [P: (24.46, 24.46), S: (192, 192)]
setting position to:  (26.461, 26.461)
in item_rect_changed callback, get_global_rect() returns: [P: (25.46, 25.46), S: (192, 192)]
setting position to:  (27.461, 27.461)
in item_rect_changed callback, get_global_rect() returns: [P: (26.461, 26.461), S: (192, 192)]
setting position to:  (28.461, 28.461)
in item_rect_changed callback, get_global_rect() returns: [P: (27.461, 27.461), S: (192, 192)]
setting position to:  (29.462, 29.462)
in item_rect_changed callback, get_global_rect() returns: [P: (28.461, 28.461), S: (192, 192)]
setting position to:  (30.462, 30.462)
in item_rect_changed callback, get_global_rect() returns: [P: (29.462, 29.462), S: (192, 192)]
setting position to:  (31.463, 31.463)
in item_rect_changed callback, get_global_rect() returns: [P: (30.462, 30.462), S: (192, 192)]
setting position to:  (32.463, 32.463)
in item_rect_changed callback, get_global_rect() returns: [P: (31.463, 31.463), S: (192, 192)]
setting position to:  (33.464, 33.464)
in item_rect_changed callback, get_global_rect() returns: [P: (32.463, 32.463), S: (192, 192)]
setting position to:  (34.464, 34.464)
in item_rect_changed callback, get_global_rect() returns: [P: (34.464, 34.464), S: (192, 192)]
setting position to:  (35.465, 35.465)
in item_rect_changed callback, get_global_rect() returns: [P: (35.465, 35.465), S: (192, 192)]
setting position to:  (36.465, 36.465)
in item_rect_changed callback, get_global_rect() returns: [P: (36.465, 36.465), S: (192, 192)]
setting position to:  (37.466, 37.466)
in item_rect_changed callback, get_global_rect() returns: [P: (36.465, 36.465), S: (192, 192)]
setting position to:  (38.467, 38.467)
in item_rect_changed callback, get_global_rect() returns: [P: (38.467, 38.467), S: (192, 192)]
setting position to:  (39.483, 39.483)
in item_rect_changed callback, get_global_rect() returns: [P: (38.467, 38.467), S: (192, 192)]
setting position to:  (40.484, 40.484)
in item_rect_changed callback, get_global_rect() returns: [P: (39.483, 39.483), S: (192, 192)]
setting position to:  (41.484, 41.484)
in item_rect_changed callback, get_global_rect() returns: [P: (41.484, 41.484), S: (192, 192)]
setting position to:  (42.484, 42.484)
in item_rect_changed callback, get_global_rect() returns: [P: (42.484, 42.484), S: (192, 192)]
setting position to:  (43.485, 43.485)
in item_rect_changed callback, get_global_rect() returns: [P: (42.484, 42.484), S: (192, 192)]
--- Debugging process stopped ---
```

Notice that sometimes multiple calls to get_global_rect() return the same value. This should not happen because the node is continuously being moved to a new location. For example:

```
...
setting position to:  (8.469, 8.469)
in item_rect_changed callback, get_global_rect() returns: [P: (8.469, 8.469), S: (192, 192)]
setting position to:  (9.47, 9.47)
in item_rect_changed callback, get_global_rect() returns: [P: (8.469, 8.469), S: (192, 192)]
...
```
and
```
...
setting position to:  (36.465, 36.465)
in item_rect_changed callback, get_global_rect() returns: [P: (36.465, 36.465), S: (192, 192)]
setting position to:  (37.466, 37.466)
in item_rect_changed callback, get_global_rect() returns: [P: (36.465, 36.465), S: (192, 192)]
...
```

I believe this script and these logs make the issue self-evident.

### Minimal reproduction project (MRP)

N/A - Just attach that script to a node, connect one signal, run the project, and observe the output.

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #92449 (as far as I've tested).

Moved only `_notify_transform()` so the order of `NOTIFICATION_RESIZED` / `item_rect_changed` signal remains unchanged.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1739,12 +1739,17 @@ void Control::_size_changed() {
...
+		// Ensure global transform is marked as dirty before `NOTIFICATION_RESIZED` / `item_rect_changed` signal
+		// so an up to date global transform could be obtained when handling these.
+		if (pos_changed || size_changed) {
+			_notify_transform();
+		}
+
 		if (size_changed) {
 			notification(NOTIFICATION_RESIZED);
 		}
 		if (pos_changed || size_changed) {
```
Comment (Sauermann) [inline scene/gui/control.cpp:1751]: Suggestion for reducing a bit of code:
```suggestion

			if (size_changed) {
				notification(NOTIFICATION_RESIZED);
			}
```

**Review by Sauermann — APPROVED** [review]
Changes make sense to me

File: scene/gui/control.cpp (hunk 1 above)
Comment (kleonc) [reply scene/gui/control.cpp]: Done.

**Comment by akien-mga** [comment]
Thanks!
