### PR TITLE
Fix Editor Description tooltip not changing until scene is reopened

### LINKED ISSUE #61521: Node's editor description property tooltip is only updated when the scene is opened
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

5.17.9-1-MANJARO Linux

### Issue description

When you add editor description to a node, you would expect that it would work immediately and show up in a node tooltip. As it stands, you have to reopen the scene for the nodes editor description to take effect.

### Steps to reproduce

1. Create a new project
2. Add a node (any node inherited from `Node`, I used `Node3D`) to the scene tree
3. Add a description to the node using node inspector
4. Save the scene (you can also do it after the next step, no difference)
5. Hover over the node in the scene tree and notice that the description you just added does not show up
6. Close and open the scene again
7. Hover over the node again to see description properly showing up

### Minimal reproduction project

[sample_project.zip](https://github.com/godotengine/godot/files/8792863/sample_project.zip)
A simple project with one scene with one node that has description applied to it. Any change to that description will only take effect after saving, closing and reopening the scene, as described above.

https://user-images.githubusercontent.com/22421580/170857896-cab6063c-3173-40c8-a8c4-65e59a49f1df.mp4

### PR DESCRIPTION
**Pull request by Calinou**
You still need to select another node to see the tooltip updated first, but you no longer need to save and reopen the scene to view the updated tooltip.

The solution is based on https://github.com/godotengine/godot/pull/61531 (thanks @Dentyr), but is only applied in the editor as it's not needed outside the editor.

This closes https://github.com/godotengine/godot/issues/61521.

### CODE REVIEW

**Comment by akien-mga** [comment]
Might be worth guarding against the case where the string doesn't change, to prevent needlessly updating the tree.

This sounds like it would update the tree for every node in a given scene when opening the scene. If you only handle nodes with a non-empty description it's a bit better, though still seems a bit overkill when many nodes have descriptions.

**Review by reduz — APPROVED** [review]

File: scene/main/node.cpp [hunk 1]
```diff
@@ -1926,6 +1926,11 @@ String Node::get_scene_file_path() const {
 
 void Node::set_editor_description(const String &p_editor_description) {
 	data.editor_description = p_editor_description;
```
Comment (akien-mga) [inline scene/main/node.cpp:1928]:
```suggestion
void Node::set_editor_description(const String &p_editor_description) {
	if (data.editor_description == p_editor_description) {
		return;
	}

	data.editor_description = p_editor_description;
```

**Comment by akien-mga** [comment]
Thanks!
