### PR TITLE
Fix virtual keyboard for decimal values on Android

### LINKED ISSUE #84091: Android release does not allow for decimal values on number or decimal type virt keyboard when using line edit with RegEx
### Godot version

4.1.2 stable

### System information

Fedora 38 - 4.1.2 stable - compatibility - Android 13 Color OS 

### Issue description

Android release does not allow for decimal values on number or decimal type virt keyboard when using line edit with RegEx. when the keyboard type is set to default this functions correctly.

Not raised a bug request before so please explain if any additional information is required thanks.

### Steps to reproduce

using the attached minimal reproduction project as per below. Deploy to android platform and test the two boxes. Either should accept number but not  character values a-z however the decimal on the number virtual keyboard will not produce a decimal when the default will. (My export is based on target 33 and my phone is using Android 13 Color OS)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/13194101/test.zip)

Project will need to be compiled into an android file to test I cannot include due to size restrictions  (26mb file) and security concerns for the sake of QA.

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes: #84091

In Europe, `comma (,)` is usually used for decimal numbers and not `period (.)`

**Note:** without `accept_characters / KeyListener` the input is validated correctly, i.e. `'-'` is only possible at the beginning and `'.'` only once. The `KeyListener` is there to accept `','`. On a Samsung Android `','` is deactivated (I could not find a solution)

---------------

Bildschirmfoto 2023-12-29 um 23 18 41

**Tests** (numbertest.zip from https://github.com/godotengine/godot/issues/84091#issuecomment-1814303735)

Pixel 4a (Android 13)

https://github.com/godotengine/godot/assets/41921395/ccf466eb-3357-4740-b078-671fe515f981

Samsung Tab S7 (Android 13)

https://github.com/godotengine/godot/assets/41921395/514d8f0a-b006-4bfb-a2b2-4f5933b513c3

### CODE REVIEW

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 1]
```diff
@@ -137,6 +138,7 @@ private void handleMessage(final Message msg) {
 					}
 
 					int inputType = InputType.TYPE_CLASS_TEXT;
+					String accept_characters = "";
```
Comment (AThousandShips) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:141]:
```suggestion
					String acceptCharacters = "";
```
We use `camelCase` in java

**Comment by Alex2782** [comment]
I could not find any information on how to activate `','` on the Samsung keyboard. The keyboard app is supposed to be open source, but I can't find anything on the Samsung homepage https://opensource.samsung.com/main


However, it is possible to set up the Google keyboard. [Gboard App - PlayStore](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin)

Bildschirmfoto 2023-12-30 um 16 03 18

**Comment by Alex2782** [comment]
virtual keyboard für `decimal values` on Samsung Android 8.1 😢 

Bildschirmfoto 2024-01-01 um 19 08 50

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 2]
```diff
@@ -165,6 +168,10 @@ private void handleMessage(final Message msg) {
 					}
 					edit.setInputType(inputType);
 
+					if (acceptCharacters != null) {
+						edit.setKeyListener(DigitsKeyListener.getInstance(acceptCharacters));
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:172]: Can you use [`DigitsKeyListener.getInstance(Locale)`](https://developer.android.com/reference/android/text/method/DigitsKeyListener#getInstance(java.util.Locale)) instead.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java (hunk 2 above)
Comment (Alex2782) [reply platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:172]: - API level 26 (Android 8.0)
- does not work on Samsung OS (video below) and Locale = `de_DE` (Germany)
- but I think it would be possible with [Gboard App](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin), should I still use Locale?

```java
	if (acceptCharacters != null) {
		Log.d("Locale", "getDefault: " + Locale.getDefault());
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
			edit.setKeyListener(DigitsKeyListener.getInstance(Locale.getDefault()));
		}
		else {
			edit.setKeyListener(DigitsKeyListener.getInstance(acceptCharacters));
		}
	}

```

Android 13, Samsung Tab S7


https://github.com/godotengine/godot/assets/41921395/c80cb1d3-4823-4132-9346-57dba65d9376

Comment (m4gr3d) [reply platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:172]: Yeah, this is an issue with the Samsung keyboard not with the api itself.

The issue with specifying the list ourselves is that we may end be omitting a character that's used by a locale not familiar to us.
For example, the empty space is accepted in some locales

https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html#:~:text=Great%20Britain%20and%20the%20United,also%20called%20the%20radix%20character.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 3]
```diff
@@ -148,7 +152,8 @@ private void handleMessage(final Message msg) {
 							inputType = InputType.TYPE_CLASS_NUMBER;
 							break;
 						case KEYBOARD_TYPE_NUMBER_DECIMAL:
-							inputType = InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_SIGNED;
+							inputType = InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_SIGNED | InputType.TYPE_NUMBER_FLAG_DECIMAL;
+							acceptCharacters = "0123456789,.-";
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:156]: Can you include the empty space as an accepted character.

File: platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java [hunk 4]
```diff
@@ -165,6 +170,14 @@ private void handleMessage(final Message msg) {
 					}
 					edit.setInputType(inputType);
 
+					if (acceptCharacters != null) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/input/GodotEditText.java:173]: Use `TextUtils.isEmpty(acceptCharacters)` instead; the method checks for both nullity and empty strings.

**Review by m4gr3d — CHANGES_REQUESTED** [review]

**Review by m4gr3d — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
Cherry-picked for 4.1.4.

**Comment by ndbn** [comment]
@Alex2782 it's not working on Android 13 and Godot 4.4.1. I guess it must be 
```
if (!TextUtils.isEmpty(acceptCharacters)) {
  if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {	
	  edit.setKeyListener(DigitsKeyListener.getInstance(acceptCharacters));
  }
}
```
(because there was no call `edit.setKeyListener` before and bug foxed in Android.O)
Anyway `Locale.getDefault()` is problematic ([reference link](https://medium.com/@hectorricardomendez/how-to-get-the-current-locale-in-android-fc12d8be6242))

**Comment by Alex2782** [comment]
@m4gr3d  Should we remove it again? -->  https://github.com/godotengine/godot/pull/86619#discussion_r1487036006

[`DigitsKeyListener.getInstance(Locale)`](https://developer.android.com/reference/android/text/method/DigitsKeyListener#getInstance(java.util.Locale))
