### PR TITLE
Fix Android multi touch

### LINKED ISSUE #11798: Android touch errors
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 build 6dc1025

**Issue description:**
On android sometimes one touch is stuck in case of multi tap swipe or pinch and produce the following error:
```
10-03 13:36:35.322: E/godot(32648): **ERROR**: Condition ' touch.size() != p_points.size() ' is true.
10-03 13:36:35.322: E/godot(32648):    At: platform\android\os_android.cpp:406:process_touch() - Condition ' touch.size() != p_points.size() ' is true.
```

**Steps to reproduce:**
Try pinch in game

### PR DESCRIPTION
**Pull request by volzhs**
Fix #11798

tested by repeating to touch and drag on screen with 10 fingers fastly.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @endragor @RandomShaper

File: platform/android/os_android.cpp [hunk 1]
```diff
@@ -444,25 +444,27 @@ void OS_Android::process_touch(int p_what, int p_pointer, const Vector<TouchPos>
 				}
 				touch.clear();
 			}
-
 		} break;
-		case 3: { // add tuchi
-
-			ERR_FAIL_INDEX(p_pointer, p_points.size());
```
Comment (volzhs) [inline platform/android/os_android.cpp]: `p_pointer` can be any integer regardless `p_points.size()`
`p_points` array can be like this.
```
[ id:0, x:10, y:10 ],
[ id:2, x:20, y:20 ],
[ id:3, x:30, y:30 ]
```
and `p_pointer` indicates last id which can be `3`

**Comment by volzhs** [comment]
@endragor sorry for false alarm about your previous PR.
