### PR TITLE
Fix ZipIO crash when reused (and possible leaks).

### LINKED ISSUE #60404: Issue regarding exporting android projects
### Godot version

v4.0.alpha.custom_build [f4b0c7a1e]

### System information

Ubuntu 20.04

### Issue description

Godot 4 crashes when attempting to create android export via android symbol in top right (as apposed to me manually exporting via export menu [have not tested doing this]). below is log of process

0 param: --xr_mode_regular
1 param: --use_immersive
ADDING: classes.dex
ADDING: lib/arm64-v8a/libc++_shared.so
ADDING: kotlin/annotation/annotation.kotlin_builtins
ADDING: kotlin/collections/collections.kotlin_builtins
ADDING: kotlin/coroutines/coroutines.kotlin_builtins
ADDING: kotlin/internal/internal.kotlin_builtins
ADDING: kotlin/kotlin.kotlin_builtins
ADDING: kotlin/ranges/ranges.kotlin_builtins
ADDING: kotlin/reflect/reflect.kotlin_builtins
ADDING: AndroidManifest.xml
ADDING: res/anim-v21/fragment_fast_out_extra_slow_in.xml
ADDING: res/anim/fragment_fast_out_extra_slow_in.xml
ADDING: res/animator/fragment_close_enter.xml
ADDING: res/animator/fragment_close_exit.xml
ADDING: res/animator/fragment_fade_enter.xml
ADDING: res/animator/fragment_fade_exit.xml
ADDING: res/animator/fragment_open_enter.xml
ADDING: res/animator/fragment_open_exit.xml
ADDING: res/drawable-hdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-hdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-mdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-nodpi-v4/splash.png
ADDING: res/drawable-nodpi-v4/splash_bg_color.png
ADDING: res/drawable-v21/notification_action_background.xml
ADDING: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable/notification_bg.xml
ADDING: res/drawable/notification_bg_low.xml
ADDING: res/drawable/notification_icon_background.xml
ADDING: res/drawable/notification_tile_bg.xml
ADDING: res/drawable/splash_drawable.xml
ADDING: res/layout-v16/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_action.xml
ADDING: res/layout-v21/notification_action_tombstone.xml
ADDING: res/layout-v21/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_template_icon_group.xml
ADDING: res/layout/custom_dialog.xml
ADDING: res/layout/downloading_expansion.xml
ADDING: res/layout/godot_app_layout.xml
ADDING: res/layout/notification_action.xml
ADDING: res/layout/notification_action_tombstone.xml
ADDING: res/layout/notification_template_icon_group.xml
ADDING: res/layout/notification_template_part_chronometer.xml
ADDING: res/layout/notification_template_part_time.xml
ADDING: res/layout/status_bar_ongoing_event_progress_bar.xml
ADDING: res/mipmap-anydpi-v26/icon.xml
ADDING: res/mipmap-hdpi-v4/icon.png
ADDING: res/mipmap-hdpi-v4/icon_background.png
ADDING: res/mipmap-hdpi-v4/icon_foreground.png
ADDING: res/mipmap-mdpi-v4/icon.png
ADDING: res/mipmap-mdpi-v4/icon_background.png
ADDING: res/mipmap-mdpi-v4/icon_foreground.png
ADDING: res/mipmap-xhdpi-v4/icon.png
ADDING: res/mipmap-xhdpi-v4/icon_background.png
ADDING: res/mipmap-xhdpi-v4/icon_foreground.png
ADDING: res/mipmap-xxhdpi-v4/icon.png
ADDING: res/mipmap-xxhdpi-v4/icon_background.png
ADDING: res/mipmap-xxhdpi-v4/icon_foreground.png
ADDING: res/mipmap-xxxhdpi-v4/icon.png
ADDING: res/mipmap-xxxhdpi-v4/icon_background.png
ADDING: res/mipmap-xxxhdpi-v4/icon_foreground.png
ADDING: res/mipmap/icon.png
ADDING: res/mipmap/icon_background.png
ADDING: res/mipmap/icon_foreground.png
ADDING: resources.arsc
ADDING: lib/arm64-v8a/libgodot_android.so

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (f4b0c7a1ea8d86c1dfd96478ca12ad1360903d9d)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x430c0) [0x7fc4f80de0c0] (??:0)
[2] RefCounted::unreference() (??:0)
[3] Ref<FileAccess>::unref() (??:0)
[4] Ref<FileAccess>::ref(Ref<FileAccess> const&) (??:0)
[5] Ref<FileAccess>::operator=(Ref<FileAccess> const&) (??:0)
[6] zipio_open(void*, char const*, int) (??:0)
[7] /home/anatole/Documents/OutThere/builds/godot_dev/bin/godot.linuxbsd.tools.64(call_zopen64+0x64) [0x55f5e2cff8a6] (??:0)
[8] /home/anatole/Documents/OutThere/builds/godot_dev/bin/godot.linuxbsd.tools.64(+0x60323d0) [0x55f5e25783d0] (??:0)
[9] /home/anatole/Documents/OutThere/builds/godot_dev/bin/godot.linuxbsd.tools.64(unzOpen2+0x55) [0x55f5e2578a25] (??:0)
[10] EditorExportPlatformAndroid::export_project_helper(Ref<EditorExportPreset> const&, bool, String const&, int, bool, int) (??:0)
[11] EditorExportPlatformAndroid::run(Ref<EditorExportPreset> const&, int, int) (??:0)
[12] EditorRunNative::run_native(int, int) (??:0)
[13] void call_with_variant_args_ret_helper<EditorRunNative, Error, int, int, 0ul, 1ul>(EditorRunNative*, Error (EditorRunNative::*)(int, int), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul>) (??:0)
[14] void call_with_variant_args_ret<EditorRunNative, Error, int, int>(EditorRunNative*, Error (EditorRunNative::*)(int, int), Variant const**, int, Variant&, Callable::CallError&) (??:0)
[15] CallableCustomMethodPointerRet<EditorRunNative, Error, int, int>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[16] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[17] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[18] Error Object::emit_signal<>(StringName const&) (??:0)
[19] BaseButton::_pressed() (??:0)
[20] BaseButton::on_action_event(Ref<InputEvent>) (??:0)
[21] BaseButton::gui_input(Ref<InputEvent> const&) (??:0)
[22] MenuButton::gui_input(Ref<InputEvent> const&) (??:0)
[23] Control::_call_gui_input(Ref<InputEvent> const&) (??:0)
[24] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (??:0)
[25] Viewport::_gui_input_event(Ref<InputEvent>) (??:0)
[26] Viewport::push_input(Ref<InputEvent> const&, bool) (??:0)
[27] Window::_window_input(Ref<InputEvent> const&) (??:0)
[28] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[29] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (??:0)
[30] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[31] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[32] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (??:0)
[33] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (??:0)
[34] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:0)
[35] Input::flush_buffered_events() (??:0)
[36] DisplayServerX11::process_events() (??:0)
[37] OS_LinuxBSD::run() (??:0)
[38] /home/anatole/Documents/OutThere/builds/godot_dev/bin/godot.linuxbsd.tools.64(main+0x16c) [0x55f5de84b935] (??:0)
[39] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fc4f80bf0b3] (??:0)
[40] /home/anatole/Documents/OutThere/builds/godot_dev/bin/godot.linuxbsd.tools.64(_start+0x2e) [0x55f5de84b70e] (??:0)
-- END OF BACKTRACE --
================================================================

expected behavior is for it to build the apk, push it to the device, and then run it in debug mode (release_debug apk used)

### Steps to reproduce

download current version of godot from github
build for linux: scons platform=linuxbsd -j12
build for android: scons platform=android target=release_debug android_arch=arm64v8 -j12
setup godot to use android debug apk
make an empty scene with just node as root
click android symbol to build,export,and run
experience crash

### Minimal reproduction project

no production project as it was literally just an empty scene with a "node" node as the root

### PR DESCRIPTION
**Pull request by bruvzg**
Regression from #59440

Fixes #60404

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/osx/export/export_plugin.cpp [hunk 1]
```diff
@@ -1327,7 +1328,8 @@ Error EditorExportPlatformOSX::export_project(const Ref<EditorExportPreset> &p_p
 					OS::get_singleton()->move_to_trash(p_path);
 				}
 
-				zlib_filefunc_def io_dst = zipio_create_io();
+				Ref<FileAccess> io_fa;
```
Comment (akien-mga) [inline platform/osx/export/export_plugin.cpp:1331]: Shadows previous `io_fa`.

**Comment by akien-mga** [comment]
Thanks!
