### PR TITLE
Fixed Path2D Plugin Editor so segments can be split.

### LINKED ISSUE #18958: Split segment in curve (in Path2D) does not split curve
**Godot version:**
v3.0.2

**OS/device including version:**
Linux

**Issue description:**
When manually adding points to a Path2D, clicking on one of the created curves of a Path2D does not split the curve with a new point when such action is implied when hovering the mouse over the add point tool. 

The pop-up statement is this:
"Add Point (in empty space) 
 **Split Segment (in curve)**""

**Steps to reproduce:**
1) Create a Path2D.
2) Manually add points to the Path2D.
3) Attempt to split a one of the curves with the "Add Point (in empty space) Split Segment (in curve)" tool.

### PR DESCRIPTION
**Pull request by remorse107**
This should fix #18958

Fixed an issue with the plugin editor for the Path2D node where the segment could not be split as originally advertised by existing toolbar buttons.

### CODE REVIEW

File: editor/plugins/path_2d_editor_plugin.h [hunk 1]
```diff
@@ -73,6 +73,7 @@ class Path2DEditor : public HBoxContainer {
 
 	bool mirror_handle_angle;
 	bool mirror_handle_length;
+	bool onEdge;
```
Comment (akien-mga) [inline editor/plugins/path_2d_editor_plugin.h]: Identifiers in Godot's codebase use `snake_case` (look around ;)).

File: editor/plugins/path_2d_editor_plugin.cpp [hunk 2]
```diff
@@ -455,21 +538,21 @@ Path2DEditor::Path2DEditor(EditorNode *p_editor) {
...
-	curve_edit->set_tooltip(TTR("Select Points") + "\n" + TTR("Shift+Drag: Select Control Points") + "\n" + keycode_get_string(KEY_MASK_CMD) + TTR("Click: Add Point") + "\n" + TTR("Right Click: Delete Point"));
+	curve_edit->set_tooltip(TTR("Select Points") + "\n" + TTR("Shift+Drag: Select Control Points") + "\n" + keycode_get_string(KEY_MASK_CMD) + TTR("Click: Add Point") + "\n" + TTR("Left Click: Split Segment (in curve)") + "\n" + TTR("Right Click: Delete Point"));
 	curve_edit->connect("pressed", this, "_mode_selected", varray(MODE_EDIT));
 	base_hb->add_child(curve_edit);
 	curve_edit_curve = memnew(ToolButton);
 	curve_edit_curve->set_icon(EditorNode::get_singleton()->get_gui_base()->get_icon("CurveCurve", "EditorIcons"));
 	curve_edit_curve->set_toggle_mode(true);
 	curve_edit_curve->set_focus_mode(Control::FOCUS_NONE);
-	curve_edit_curve->set_tooltip(TTR("Select Control Points (Shift+Drag)"));
+	curve_edit_curve->set_tooltip(TTR("Select Control Points (Shift+Drag)") + "\n");
```
Comment (akien-mga) [inline editor/plugins/path_2d_editor_plugin.cpp]: Why is the newline needed?

File: editor/plugins/path_2d_editor_plugin.cpp [hunk 3]
```diff
@@ -72,15 +72,15 @@ bool Path2DEditor::forward_gui_input(const Ref<InputEvent> &p_event) {
 
 	Ref<InputEventMouseButton> mb = p_event;
 
+	real_t grab_threshold = EDITOR_DEF("editors/poly_editor/point_grab_radius", 8);
```
Comment (akien-mga) [inline editor/plugins/path_2d_editor_plugin.cpp]: Would make more sense to have it before the definition of `mb` than between it and its validity check.
Also this should use `EDITOR_GET`, no need to attempt redefining it all the time (I know it's not your code, but while at it it would be good to fix it).

Other instances that could be fixed:
```
$ rg "editor/point_grab"
editor/editor_settings.cpp
496:    _initial_set("editors/poly_editor/point_grab_radius", 8);

editor/plugins/collision_polygon_editor_plugin.cpp
147:            real_t grab_threshold = EDITOR_DEF("editors/poly_editor/point_grab_radius", 8);

editor/plugins/canvas_item_editor_plugin.cpp
459:    const real_t grab_distance = EDITOR_DEF("editors/poly_editor/point_grab_radius", 8);

editor/plugins/path_2d_editor_plugin.cpp
82:             real_t grab_threshold = EDITOR_DEF("editors/poly_editor/point_grab_radius", 8);

editor/plugins/abstract_polygon_2d_editor.cpp
425:                                    const real_t grab_threshold = EDITOR_DEF("editors/poly_editor/point_grab_radius", 8);
692:    const real_t grab_threshold = EDITOR_DEF("editors/poly_editor/point_grab_radius", 8);
723:    const real_t grab_threshold = EDITOR_DEF("editors/poly_editor/point_grab_radius", 8);
```

(the `_initial_set` should stay as is of course, it's what defines it originally for use by all abstracted polygon editors)

File: editor/plugins/path_2d_editor_plugin.cpp [hunk 4]
```diff
@@ -179,6 +178,41 @@ bool Path2DEditor::forward_gui_input(const Ref<InputEvent> &p_event) {
 			return true;
 		}
 
+		// Check for segment split.
+		if (mb->is_pressed() && mb->get_button_index() == BUTTON_LEFT && mode == MODE_EDIT && on_edge == true) {
+			Vector2 gpoint = mb->get_position();
+			Ref<Curve2D> curve = node->get_curve();
+
+			int insertionPoint = -1;
```
Comment (akien-mga) [inline editor/plugins/path_2d_editor_plugin.cpp]: Still some `camelCase` identifiers in this code block and the next one, otherwise looks good.

Comment (remorse107) [reply editor/plugins/path_2d_editor_plugin.cpp]: Good grief.  Habit is hard to overcome.

**Comment by akien-mga** [comment]
CC @YeldhamDev @groud for review.

**Comment by YeldhamDev** [comment]
This seems like another editor that would heavily benefit from being inherited of `AbstractPolygon2DEditor`.

**Comment by akien-mga** [comment]
Thanks!
