### PR TITLE
Fix crash when creating new project

### LINKED ISSUE #7555: Project manager segfaults when creating a new project
**Operating system or device - Godot version:**
Arch Linux 64 Bit, current master

**Issue description** (what happened, and what was expected):
I can't create a new project in the project manager. `touch`ing a new `engine.cfg` and importing that works fine.
```
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:145.
Segmentation fault (core dumped)
```

**Steps to reproduce:**
Try to create a new project in the project manager.

**Link to minimal example project** (optional but very welcome):
what project? :^)

### PR DESCRIPTION
**Pull request by volzhs**
it's caused by #7525 and fix #7555

and these results are same as described at #7527
```gdscript
print("".plus_file("file"))  # prints "file"
print("/".plus_file("file"))  # prints "/file"
print("whatever".plus_file("/usr").plus_file("bin"))  # prints "whatever/user/bin"
```

### CODE REVIEW

File: core/ustring.cpp [hunk 1]
```diff
@@ -3898,10 +3898,9 @@ String String::get_extension() const {
 String String::plus_file(const String& p_file) const {
 	if (empty())
 		return p_file;
-	if (operator [](length()-1)=='/' || p_file.operator [](0)=='/')
+	else if (operator [](length()-1)=='/' || (p_file.size()>0 && p_file.operator [](0)=='/'))
```
Comment (karroffel) [inline core/ustring.cpp]: unneccesary `else`, but it doesn't do harm. Looks good to me.

**Review by karroffel — APPROVED** [review]

File: core/ustring.cpp (hunk 1 above)
Comment (volzhs) [inline core/ustring.cpp]: you're right. I think it's better to remove it.

**Review by karroffel — APPROVED** [review]
still looks good to me ^^
