### PR TITLE
Fix memory alignment on 32-bit Windows.

### LINKED ISSUE #113113: Windows 32-bit 4.6 editor does not launch.
### Tested versions

- Reproducible in Godot 4.6-dev2/3/4. Present in both mono & non-mono.
- Not reproducible in Godot 4.5.1, 4.6dev-1, any 4.6 64-bit snapshot.

### System information

Godot v4.5.1.stable.mono - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Mobile) - integrated Intel(R) Arc(TM) Graphics - Intel(R) Core(TM) Ultra 7 256V (8 threads) - 15.54 GiB memory

### Issue description

Launching the 32-bit version of 4.6 (Excluding dev-1) causes the editor to crash on launch.
I do not think this is related to https://github.com/godotengine/godot/issues/113111

I've included the entire log since the property not found warnings are not present in the 64-bit versions, or in the 32-bit dev-1 version.
```
WARNING: Property not found: 'physics/jolt_physics_3d/simulation/allow_sleep'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/simulation/sleep_time_threshold'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/simulation/continuous_cd_max_penetration'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/simulation/body_pair_contact_cache_enabled'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/simulation/body_pair_contact_cache_distance_threshold'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/simulation/body_pair_contact_cache_angle_threshold'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/queries/use_enhanced_internal_edge_removal'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/queries/enable_ray_cast_face_index'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/motion_queries/use_enhanced_internal_edge_removal'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/motion_queries/recovery_iterations'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/motion_queries/recovery_amount'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/collisions/collision_margin_fraction'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/collisions/active_edge_threshold'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/joints/world_node'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/limits/temporary_memory_buffer_size'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/limits/world_boundary_shape_size'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/limits/max_linear_velocity'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/limits/max_angular_velocity'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/limits/max_bodies'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/limits/max_body_pairs'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
WARNING: Property not found: 'physics/jolt_physics_3d/limits/max_contact_constraints'.
     at: get_setting_with_override (core/config/project_settings.cpp:417)
ERROR: FATAL: Index p_index = 1 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 1).
   at: operator[] (./core/templates/vector.h:54)

================================================================
CrashHandlerException: Program crashed with signal 4
Engine version: Godot Engine v4.6.dev4.official (bd2ca13c6f3a5198eac035c855dcd1759e077313)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
-- END OF C++ BACKTRACE --
================================================================
```

### Steps to reproduce

Open 4.6 snapshot other than dev-1.
The crash will appear before the editor finishes loading.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/113113

### CODE REVIEW

File: core/templates/cowdata.h [hunk 1]
```diff
@@ -60,7 +60,10 @@ class CowData {
 	static constexpr USize MAX_INT = INT64_MAX;
 
 private:
-	// Alignment:  ↓ max_align_t           ↓ USize          ↓ USize            ↓ max_align_t
+	static constexpr size_t MAX_ALIGN = 16; // Note: Using hardcoded value, since on some platforms `alignof(max_align_t)` can be different in different compile units.
```
Comment (Ivorforce) [inline core/templates/cowdata.h]: We can use `Memory::MaxAlign` here.

File: core/os/memory.h [hunk 2]
```diff
@@ -41,7 +41,11 @@ constexpr size_t get_aligned_address(size_t p_address, size_t p_alignment) {
 	return (n_bytes_unaligned == 0) ? p_address : (p_address + p_alignment - n_bytes_unaligned);
 }
 
-// Alignment:  ↓ max_align_t        ↓ uint64_t          ↓ max_align_t
+static constexpr size_t MAX_ALIGN = 16; // Note: Using hardcoded value, since on some platforms `alignof(max_align_t)` can be different in different compile units.
+
+static_assert(MAX_ALIGN % alignof(max_align_t) == 0);
```
Comment (Ivorforce) [inline core/os/memory.h]: As far as i understand, `max_align_t` being include dependent is a compiler / stdlib bug, right?

If so, I would prefer to limit the fix to the affected system:

```suggestion
#if defined(_WIN32)
// Note: Using hardcoded value, since the value can end up different in different compile units on 32-bit windows
// due to a compiler bug (see GH-113145)
static constexpr size_t MAX_ALIGN = 16;
static_assert(MAX_ALIGN % alignof(max_align_t) == 0);
#else
static constexpr size_t MAX_ALIGN = max_align_t;
#endif
```

**Comment by AThousandShips** [comment]
Similar changes are probably needed in godot-cpp

File: core/os/memory.h (hunk 2 above)
Comment (bruvzg) [reply core/os/memory.h]: Yes, seems to be specific to 32-bit GCC (or CRT it's using).

**Comment by Ivorforce** [comment]
> Similar changes are probably needed in godot-cpp

Godot-cpp doesn't use the https://github.com/godotengine/godot/pull/105928 `CowData` implementation yet, so it should be good as long as it's synchronized only after the fix.

File: core/os/memory.h [hunk 3]
```diff
@@ -41,7 +41,18 @@ constexpr size_t get_aligned_address(size_t p_address, size_t p_alignment) {
...
+#if defined(_WIN32)
+// Note: Using hardcoded value, since the value can end up different in different compile units on 32-bit windows
+// due to a compiler bug (see GH-113145)
+static constexpr size_t MAX_ALIGN = 16;
+static_assert(MAX_ALIGN % alignof(max_align_t) == 0);
+#else
+static constexpr size_t MAX_ALIGN = alignof(max_align_t);
+#endif
+
+static_assert(MAX_ALIGN % alignof(max_align_t) == 0);
```
Comment (Ivorforce) [inline core/os/memory.h]: You've got this one twice now

```suggestion
```

**Review by Ivorforce — APPROVED** [review]
LGTM

**Comment by bruvzg** [comment]
`godot-cpp` is using the same code:

https://github.com/godotengine/godot-cpp/blob/44a7d6befeff5649ce9161d2e50ad91df3bfc642/include/godot_cpp/templates/cowdata.hpp#L107-L109

But since it doesn't use the https://github.com/godotengine/godot/pull/105928, it's coincidently align to 16 in any case.

File: core/os/memory.h [hunk 4]
```diff
@@ -41,7 +41,16 @@ constexpr size_t get_aligned_address(size_t p_address, size_t p_alignment) {
 	return (n_bytes_unaligned == 0) ? p_address : (p_address + p_alignment - n_bytes_unaligned);
 }
 
-// Alignment:  ↓ max_align_t        ↓ uint64_t          ↓ max_align_t
+#if defined(_WIN32)
```
Comment (akien-mga) [inline core/os/memory.h]: I think we can make this more specific as it's a MinGW bug (https://sourceforge.net/p/mingw-w64/bugs/778/ and https://sourceforge.net/p/mingw-w64/bugs/779/).

Also `_WIN32` is also defined for x86_64.

```suggestion
#if defined(__MINGW32__) && !defined(__MINGW64__)
```

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
