### PR TITLE
Fix empty type removal in theme editor causing all empty types to be deleted

### LINKED ISSUE #71313: When click Delete Type in the Theme Editor Management Theme Items menu, you not only delete the selected type, but delete all unused types
### Godot version

3.5.1mono

### System information

windows10

### Issue description

See this video
[2023-01-13 13-43-42.zip](https://github.com/godotengine/godot/files/10408528/2023-01-13.13-43-42.zip)

### Steps to reproduce

1.Create a project
2.Create a theme
3.Open theme editor
4.Open management theme items menu
5.Create more than 2 type
6.Delete one of them
7.Found all the types that don't be used are deleted

### Minimal reproduction project

An empty project

### PR DESCRIPTION
**Pull request by jaydensipe**
Fixes https://github.com/godotengine/godot/issues/100730, fixes https://github.com/godotengine/godot/issues/71313

| Before | After |
| ------------- | ------------- |
|  <video src=https://github.com/user-attachments/assets/b32d4a52-4b38-4049-9604-26fbe09f0ab9></video> |  <video src=https://github.com/user-attachments/assets/60b66f81-3733-4f3e-97d6-1081207a4d27></video> |

### CODE REVIEW

File: editor/plugins/theme_editor_plugin.cpp [hunk 1]
```diff
@@ -1588,15 +1588,12 @@ void ThemeItemEditorDialog::_add_theme_item(Theme::DataType p_data_type, String
...
-	Ref<Theme> new_snapshot = edited_theme->duplicate();
 
 	EditorUndoRedoManager *ur = EditorUndoRedoManager::get_singleton();
 	ur->create_action(TTR("Remove Theme Type"));
 
-	new_snapshot->remove_type(p_theme_type);
-
-	ur->add_do_method(*edited_theme, "clear");
-	ur->add_do_method(*edited_theme, "merge_with", new_snapshot);
+	// Avoid merging with new_snapshot, if type was empty new_snapshot will merge as empty data and cause all empty types to be deleted, instead of clicked type.
```
Comment (KoBeWi) [inline editor/plugins/theme_editor_plugin.cpp:1595]: The comment does not make sense with the new code. `new_snapshot` no longer exists.

**Review by KoBeWi — APPROVED** [review]
Works fine.

I wonder why the original code did the snapshot.

**Comment by jaydensipe** [comment]
> Works fine.
> 
> I wonder why the original code did the snapshot.

Not sure, it's used all within that class, so maybe just for consistency, and this was a weird edge case?
