### PR TITLE
OS: Better validation of invalid input for get_unix_time_from_datetime

### LINKED ISSUE #49022: Infinite loop on incomplete Datetime dictionary (OS.get_unix_time_from_datetime)
The godot (v3.3.stable.official windows) engine seems to crash if you only provide a part of the dictionary:

Example:
```
func _ready() -> void:
	print(OS.get_unix_time_from_datetime({
		"second": 1,
	}))
```

Edit* No Crash log, the game just freezes

### PR DESCRIPTION
**Pull request by akien-mga**
Default missing keys to Unix time 0 (1970-01-01 at 00:00:00 UTC).
Abort if year <= 0, this is not supported by the current algorithm.

Prevents an infinite loop further down.

Fixes #49022.

### CODE REVIEW

File: core/core_bind.cpp [hunk 1]
```diff
@@ -390,7 +390,7 @@ int64_t _OS::get_unix_time_from_datetime(Dictionary datetime) const {
 	unsigned int hour = ((datetime.has(HOUR_KEY)) ? static_cast<unsigned int>(datetime[HOUR_KEY]) : 0);
 	unsigned int day = ((datetime.has(DAY_KEY)) ? static_cast<unsigned int>(datetime[DAY_KEY]) : 1);
 	unsigned int month = ((datetime.has(MONTH_KEY)) ? static_cast<unsigned int>(datetime[MONTH_KEY]) : 1);
-	unsigned int year = ((datetime.has(YEAR_KEY)) ? static_cast<unsigned int>(datetime[YEAR_KEY]) : 0);
+	unsigned int year = ((datetime.has(YEAR_KEY)) ? static_cast<unsigned int>(datetime[YEAR_KEY]) : 1970);
```
Comment (qarmin) [inline core/core_bind.cpp:393]: There will be still freeze, when user will set `datetime[YEAR_KEY]` to 0.
Probably better is to validate user data(don't know if current algorithm allow to return negative unix time)

Comment (akien-mga) [reply core/core_bind.cpp:393]: Negative times (years before `1970`) seem to work fine down to `1`, but indeed `0` and negative years also freeze. I'll had an err cond, someone should clean up the algorithm and make it actually robust if we want to handle BC years.

Comment (aaronfranke) [reply core/core_bind.cpp:393]: I don't think we can even say it works that far. I don't see a special case for October 1582, so I assume it doesn't work properly for times before then.

Comment (akien-mga) [reply core/core_bind.cpp:393]: Yeah this needs a complete overhaul, or using a third-party library or possibly modern OS APIs.

For now I'm just handling the most obvious crash. BTW negative years would overflow as it's being cast to `unsigned int`, so those might not trigger an infinite loop, just a veeeeeeeeeeeery long one when iterating all the way to `UINT64_MAX` :P

Comment (aaronfranke) [reply core/core_bind.cpp:393]: After further investigation, for the sake of sanity of programmers, most tools use the Proleptic Gregorian calendar which extends the Gregorian calendar back before 1582 as if it had always been adopted. With the Proleptic Gregorian calendar, we don't need a special case for October 1582. https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar

However, if Godot wishes to support historical dates, a parallel API that handles the Julian calendar would be nice.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
