### PR TITLE
Fix Tree buttons jiggle on horizontal scrolling

### LINKED ISSUE #100645: Buttons in tree jiggles when scrolling horizontally
### Tested versions

Godot v4.4.dev7

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window

### Issue description

Buttons in tree jiggles when scrolling horizontally 

https://github.com/user-attachments/assets/7f4627bc-dc0d-4d1b-8a48-023a32606e7e

### Steps to reproduce

Scroll horizontally in scene tree

### Minimal reproduction project (MRP)

[jiggle.zip](https://github.com/user-attachments/files/18209281/jiggle.zip)

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/100645

After:

[Screencast_20250214_234930.webm](https://github.com/user-attachments/assets/3f1bd00b-2735-43fe-8a96-a14bc28312c7)

test file to test in: 
[treejiggle.zip](https://github.com/user-attachments/files/18805320/treejiggle.zip)

Before:

[Screencast_20250214_235242.webm](https://github.com/user-attachments/assets/e04a63da-fd33-4d41-889a-a74f5791260f)

After:

[Screencast_20250214_235141.webm](https://github.com/user-attachments/assets/3511cda1-e39a-4d85-826d-a772c2e8d591)

The editor SceneTree makes the buttons/row jump slightly to the left at end of the scroll when the vertical scroll is visible (was there before too) not sure what makes that happen. Feels like another issue that can be fixed in a separate PR. 

[Screencast_20250214_235844.webm](https://github.com/user-attachments/assets/a82fa1e8-ea02-491c-8902-6c823356d8b9)

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -2184,7 +2184,7 @@ int Tree::draw_item(const Point2i &p_pos, const Point2 &p_draw_ofs, const Size2
 					buttons_width += button_texture->get_size().width + theme_cache.button_pressed->get_minimum_size().width + theme_cache.button_margin;
 				}
 
-				int total_ofs = ofs - theme_cache.offset.x;
+				double total_ofs = ofs - theme_cache.offset.x;
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:2187]:
```suggestion
				real_t total_ofs = ofs - theme_cache.offset.x;
```

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/tree.cpp (hunk 1 above)
Comment (Giganzo) [reply scene/gui/tree.cpp:2187]: When used with real_t I can trigger jiggle issue again:

[Screencast_20250215_232433.webm](https://github.com/user-attachments/assets/facbb1fe-dc9e-45c6-8588-4fd1c9e98628)


Can only reliable trigger this on a narrow tree.

Comment (KoBeWi) [reply scene/gui/tree.cpp:2187]: Alright then.

**Comment by akien-mga** [comment]
I'm keeping this for 4.5 as it's not critical, and such small changes in Controls can lead to unexpected regressions. Notably here the rest of the code seems to compare `total_ofs` with integers so I'm worried there might be other cases where positions will jump unexpectedly.

**Comment by Repiteo** [comment]
Thanks!
