### PR TITLE
Fix CPU/GPUParticles2D bugs on Compatibility Rendering (GLES3) on Adreno 3XX devices.

### LINKED ISSUE #88815: GPUParticles2D on Compatibility Rendering (GLES3) freeze on Adreno 3XX devices
### Tested versions

- Reproducible in: **master branch**

### System information

Android

### Issue description

Using `GPUParticles2D` on Android with the Compatibility Rendering (GLES3), freeze the game at the start **(only on Adreno 3XX devices)**

**Tested Devices:**

- Sony Xperia M2 `(Adreno 305)` - **BUGGED**
- Huawei MediaPad T3 10 `(Adreno 308)` - **BUGGED**
- Samsung Galaxy S4 `(Adreno 320)` - **BUGGED**
- LG Nexus 5 `(Adreno 330)` - **BUGGED**
- Samsung Note 4 `(Adreno 420)` - WORKS
- Huawei Honor 7A `(Adreno 505)` - WORKS
- LG G5  `(Adreno 530) ` - WORKS
- Xiomi Redmi 12 `(Adreno 610)` - WORKS
- Huawei Honor 9 Lite `(Mali T830)` - WORKS

This is the empty screenshot (after the Godot logo)...

image

<details><summary>This is the `logcat`...</summary>

```
02-25 14:23:28.093 29625 29625 V GodotActivity: Creating new Godot fragment instance.
02-25 14:23:28.116 29625 29625 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.godotengine.godot.Godot$onInitRenderView$2>
02-25 14:23:28.116 29625 29625 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.godotengine.godot.Godot$onInitRenderView$2>
02-25 14:23:28.396 29625 29625 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
02-25 14:23:28.396 29625 29625 I art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
02-25 14:23:28.687 29625 29680 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-25 14:23:28.757 29625 29680 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
02-25 14:23:28.762 29625 29680 I OpenGLRenderer: Initialized EGL, version 1.4
02-25 14:23:28.788 29625 29674 W RegularContextFactory: creating OpenGL ES 3.0 context :
02-25 14:23:28.828 29625 29674 I godot   : Godot Engine v4.2.1.stable.custom_build.b09f793f5 - https://godotengine.org
02-25 14:23:29.127 29625 29674 I godot   : OpenGL API OpenGL ES 3.0 V@127.0 AU@  (GIT@I96aee987eb) - Compatibility - Using Device: Qualcomm - Adreno (TM) 330
02-25 14:23:29.129 29625 29674 I godot   :  
02-25 14:23:29.136 29625 29674 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 44100 Hz, output 48000 Hz
02-25 14:23:30.595 29625 29674 D Godot   : OnGodotSetupCompleted
02-25 14:23:30.648 29625 29674 D Godot   : OnGodotMainLoopStarted
***FREEZE HERE!!!***
```

</details>

### Steps to reproduce

- Create an empty project with the _Compatibility Rendering_ 
- add a simple `GPUParticles2D` node
- export it to Android on an **Adreno 3XX device**

PS: you find attached a simple **MRP**.

### Minimal reproduction project (MRP)

[GPUParticles2D-Test.zip](https://github.com/godotengine/godot/files/14396503/GPUParticles2D-Test.zip)

### PR DESCRIPTION
**Pull request by ayremon**
Fixes https://github.com/godotengine/godot/issues/88815
This **PR** is the natural completion of https://github.com/godotengine/godot/pull/87352 

**Tested Devices:**

- Sony Xperia M2 `(Adreno 305)` - **FIXED**
- Huawei MediaPad T3 10 `(Adreno 308)` - **FIXED**
- Samsung Galaxy S4 `(Adreno 320)` - **FIXED**
- LG Nexus 5 `(Adreno 330)` - **FIXED**
- Samsung Note 4 `(Adreno 420)` - NOT AFFECTED
- Huawei Honor 7A `(Adreno 505)` - NOT AFFECTED
- LG G5  `(Adreno 530) ` - NOT AFFECTED
- Xiomi Redmi 12 `(Adreno 610)` - NOT AFFECTED
- Huawei Honor 9 Lite `(Mali T830)` - NOT AFFECTED

This **PR** allows a game that uses `GPUParticles2D` on older **Adreno 3XX devices** to start and run fine (without any freeze) but not allow to use `GPUParticles2D` (however, it allows you to fully use the `CPUParticles2D`, which otherwise would not work at all)...

**Let me Explain...**

After fixed all the incompatibilities of the Particle Shaders that caused the game to freeze at startup (only on **Adreno 3XX devices**), I saw that the particles were still **NOT** displayed even though the **FPS drop** showed that they were still processed.
The drop in **FPS** was truly notable, even just inserting an "empty" `GPUParticles2D` Node, there was a drop of **11/13 FPS.**

At this point I completely disabled the `GPUParticles2D` functionality (only on **Adreno 3XX** devices) because trying to go further no longer made sense since these devices are too old and slow to be able to handle particles smoothly.

So the scope of this **PR** is **ONLY** let a game with `GPUParticles2D` start and run fine (without Freeze) on old **Adreno 3XX** devices (but without any particles).

Screenshot of a demo game on a **LG Nexus 5 (Adreno 330)** before the fixes...
image

**After the fixes...** (you cannot see the Particles because was disabled, but at least the game is playable)
image

### CODE REVIEW

**Comment by joined72** [comment]
@clayjohn can you review it, please?

**Comment by joined72** [comment]
@Calinou do you think this PR can be cherry-picked for the 4.2.2 release?

**Comment by clayjohn** [comment]
@joined72 I expect that the particles process material would be more problematic than actually drawing the particles as drawing particles works the same way as drawing CPU particles or drawing MultiMeshes. 

Have you tested using CPUParticles2D instead of GPUParticles2D? It would be helpful to know if CPUParticles2D causes the same crash

**Comment by joined72** [comment]
> @joined72 I expect that the particles process material would be more problematic than actually drawing the particles as drawing particles works the same way as drawing CPU particles or drawing MultiMeshes.
> 
> Have you tested using CPUParticles2D instead of GPUParticles2D? It would be helpful to know if CPUParticles2D causes the same crash

@clayjohn CPUParticles2D don't cause any crash, but still not showed and don't decrease FPS.

**Comment by joined72** [comment]
@clayjohn 

Let me Explain in details...

The freeze was caused by an incompatibility in the `drivers/gles3/shaders/particles.glsl` Shader.

Fixed that, I found that the `drivers/gles3/shaders/particles_copy.glsl` Shader not compiled for a syntax error.

Fixed that I thought to see the `GPUParticles2D` on the **Adreno 3XX** device, but **NO, it didn't work!** 

While I was working on showing the particles, I understand that the device is too old and slow to handle particles smoothly, so I decided to disable `GPUParticles2D` on **Adreno 3XX** devices.

At the start, I done this working on the `scene/2d/gpu_particles_2d.cpp` source file (at the `GPUParticles2D::set_emitting` and `GPUParticles2D::is_emitting` methods) after I decided to move the _"disabling" logic_ at the _"rendering level"_ (working on the `drivers/gles3/storage/particles_storage.cpp` source file).

PS: from my test `CPUParticles2D` doesn't crash **Adreno 3XX** devices, but particles are still not showed, and **FPS not decrease.**

File: drivers/gles3/storage/particles_storage.cpp [hunk 1]
```diff
@@ -31,6 +31,7 @@
 #ifdef GLES3_ENABLED
 
 #include "particles_storage.h"
+#include "config.h"
```
Comment (AThousandShips) [inline drivers/gles3/storage/particles_storage.cpp:34]:
```suggestion

#include "config.h"
```

**Comment by clayjohn** [comment]
> @clayjohn
> 
> Let me Explain in details...
> 
> The freeze was caused by an incompatibility in the `drivers/gles3/shaders/particles.glsl` Shader.
> 
> Fixed that, I found that the `drivers/gles3/shaders/particles_copy.glsl` Shader not compiled for a syntax error.
> 
> Fixed that I thought to see the `GPUParticles2D` on the **Adreno 3XX** device, but **NO, it didn't work!**
> 
> While I was working on showing the particles, I understand that the device is too old and slow to handle particles smoothly, so I decided to disable `GPUParticles2D` on **Adreno 3XX** devices.
> 
> At the start, I done this working on the `scene/2d/gpu_particles_2d.cpp` source file (at the `GPUParticles2D::set_emitting` and `GPUParticles2D::is_emitting` methods) after I decided to move the _"disabling" logic_ at the _"rendering level"_ (working on the `drivers/gles3/storage/particles_storage.cpp` source file).
> 
> PS: from my test `CPUParticles2D` doesn't crash **Adreno 3XX** devices, but particles are still not showed, and **FPS not decrease.**

Thank you for clarifying! That makes sense to me now. 

So it seems the problem is that MultiMeshes are not drawing correctly in the 2D renderer. I don't think that is a limitation of Adreno 3XX though. It is more likely a problem with our code since regular rect drawing uses a similar pathway to MultiMeshes. I'm assuming you are testing on master in which case, you could actually be seeing a recently introduced issue that was fixed yesterday by https://github.com/godotengine/godot/pull/88938. Could you test with CPUParticles again on the most recent master branch and see if they are visible now?

To be clear, I think we should investigate why particles are not appearing instead of disabling them on Adreno devices.

**Comment by joined72** [comment]
> Could you test with CPUParticles again on the most recent master branch and see if they are visible now?
> 
Ok, I'll update ASAP.
> To be clear, I think we should investigate why particles are not appearing instead of disabling them on Adreno devices.

Great 😃

**Comment by joined72** [comment]
@clayjohn I'm sorry but the most recent master branch has the same issue, `CPUParticles2D` **aren't showed** and the **FPS aren't dropped**.

Based on my experience, the problem _"should"_ be using some form of Shader that uses GLSL code incompatible with **Adreno 3XX** but compatible with all other devices. 

I tried checking in the `scene/2d/cpu_particles_2d.cpp` sources, but I didn't find anything like that. 

Could you give me some directions?

**Comment by clayjohn** [comment]
> @clayjohn I'm sorry but _the most recent master branch_ has the same issue, `CPUParticles2D` **aren't showed** and the **FPS aren't dropped**.
> 
> Based on my experience, the problem _"should"_ be using some form of _Shader_ that uses _GLSL_ code incompatible with **Adreno 3XX** but compatible with all other devices.
> 
> I tried checking in the `scene/2d/cpu_particles_2d.cpp` sources, but I didn't find anything like that.
> 
> Could you give me some directions?
> 
> **EDIT:** is possible the **Adreno 3XX** _Shader "incompatibility"_ is in the Shader generated by the `scene/resources/particle_process_material.cpp` sources?
> 
> https://github.com/godotengine/godot/blob/df78c0636d79c9545a283e0e2a926d623998cc27/scene/resources/particle_process_material.cpp#L149

Based on your description, the only shader that could be causing this issue is https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/canvas.glsl Particularly with the `USE_ATTRIBUTES` and `USE_INSTANCING` defines. To further confirm, can you also test a scene with a MeshInstance2D and a scene with a MultiMeshInstance2D?

If the MeshInstance2D does not appear, then the issue is with `USE_ATTRIBUTES` If the MeshInstance2D appears, but the MultiMeshInstance2D does not appear, then the issue is with `USE_INSTANCING`. 

If the MultiMeshInstance2D _does_ appear correctly. Then the issue is most likely with using both custom color and custom data. So try enabling those on the MultiMeshInstance2D. CPUParticles internally are just a MultiMeshInstance2D with both custom color and custom data enabled.

**Comment by clayjohn** [comment]
On a side note, in the rendering meeting we discussed if there would be a performance impact to using an if/else if branch instead of a switch statement. 

I took a look and confirmed that on AMD the generated bytecode is the same between the two approaches:

Switch: https://shader-playground.timjones.io/6145551406931ced2e87820428c9e21f
If/else: https://shader-playground.timjones.io/e7533bf63f1c292c13f2fffa8c0e76e2

**Comment by joined72** [comment]
> On a side note, in the rendering meeting we discussed if there would be a performance impact to using an if/else if branch instead of a switch statement.
> 
> I took a look and confirmed that on AMD the generated bytecode is the same between the two approaches:
> 
> Switch: https://shader-playground.timjones.io/6145551406931ced2e87820428c9e21f If/else: https://shader-playground.timjones.io/e7533bf63f1c292c13f2fffa8c0e76e2

Really Great, thanks for the update! ;)

**PS:** I'm working on the `MeshInstance2D` and `MultiMeshInstance2D` testing, and found the while `MeshInstance2D` works well, using a `MultiMeshInstance2D` node on an **Adreno 3XX** device crashes the app at the start. 
I'm doing more investigations...

**Comment by joined72** [comment]
> The problem is **"Unable to initialize engine render view"** at [GodotFragment.java](https://github.com/godotengine/godot/blob/master/platform/android/java/lib/src/org/godotengine/godot/GodotFragment.java):196

_Problem solved, was caused from my wrong configuration!_

About the `MeshInstance2D` and `MultiMeshInstance2D` issue, I found that the `MultiMeshInstance2D` works fine **ONLY** if is **NOT** used the `custom color` (`custom data` is OK). I'm working on it...

**Comment by joined72** [comment]
I found other useful info... the problem is in this part of the [drivers/gles3/shaders/canvas.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/canvas.glsl)  sources:

The following line: 

https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/drivers/gles3/shaders/canvas.glsl#L181 

returns **ALWAYS** `instance_color.z` and `instance_color.z` **equal to zero!** 

I'm continuing my investigations...

**Comment by joined72** [comment]
Other info...
If I change the following [drivers/gles3/shaders/canvas.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/canvas.glsl) source code:

**FROM:**

```.cpp
vec4 instance_color = vec4(unpackHalf2x16(instance_color_custom_data.x), unpackHalf2x16(instance_color_custom_data.y));
color *= instance_color;
```
**TO:**

```.cpp
vec4 instance_color = vec4(unpackHalf2x16(instance_color_custom_data.x), unpackHalf2x16(instance_color_custom_data.y));
instance_color.w = 1.0;
instance_color.z = 1.0;
color *= instance_color;
```
I force **BLUE** and **ALPHA** channels **ALWAYS to 100%** but I **CAN SEE CPUParticles2D**, but **ONLY** if I use a **NOT empty** `Texture`!

**Comment by joined72** [comment]
GREAT NEWS! ;)

I found a solution. Changing the following [drivers/gles3/shaders/canvas.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/canvas.glsl) source code:

**FROM:**

```.cpp
if (bool(read_draw_data_flags & FLAGS_INSTANCING_HAS_COLORS)) {
	vec4 instance_color = vec4(unpackHalf2x16(instance_color_custom_data.x), unpackHalf2x16(instance_color_custom_data.y));
	color *= instance_color;
}
if (bool(read_draw_data_flags & FLAGS_INSTANCING_HAS_CUSTOM_DATA)) {
	instance_custom = vec4(unpackHalf2x16(instance_color_custom_data.z), unpackHalf2x16(instance_color_custom_data.w));
}
```

**TO:**

```.cpp
if (bool(read_draw_data_flags & FLAGS_INSTANCING_HAS_COLORS)) {
	vec4 instance_color;
	instance_color.xy = unpackHalf2x16(instance_color_custom_data.x);
	instance_color.zw = unpackHalf2x16(instance_color_custom_data.y);
	color *= instance_color;
}
if (bool(read_draw_data_flags & FLAGS_INSTANCING_HAS_CUSTOM_DATA)) {
	instance_custom.xy = unpackHalf2x16(instance_color_custom_data.z);
	instance_custom.zw = unpackHalf2x16(instance_color_custom_data.w);
}
```
**FIX ANY** `CPUParticles2D` bugs (works fine **with and without** `Texture`)!

@clayjohn what do you think about?

If you think these are acceptable changes then the following piece of code would also need to be modified, although I don't know exactly what it does.

```.cpp
if (gl_VertexID % 3 == 0) {
	vertex = read_draw_data_point_a;
	uv = read_draw_data_uv_a;
	color = vec4(unpackHalf2x16(read_draw_data_color_a_rg), unpackHalf2x16(read_draw_data_color_a_ba));
} else if (gl_VertexID % 3 == 1) {
	vertex = read_draw_data_point_b;
	uv = read_draw_data_uv_b;
	color = vec4(unpackHalf2x16(read_draw_data_color_b_rg), unpackHalf2x16(read_draw_data_color_b_ba));
} else {
	vertex = read_draw_data_point_c;
	uv = read_draw_data_uv_c;
	color = vec4(unpackHalf2x16(read_draw_data_color_c_rg), unpackHalf2x16(read_draw_data_color_c_ba));
}

```

**NOTE:** all these changes **did not fix** the `GPUParticles2D` issue (particles aren't showed at all).

**Comment by clayjohn** [comment]
I think that is an acceptable change. 

> If you think these are acceptable changes then the following piece of code would also need to be modified, although I don't know exactly what it does.

Let's change that code too. It is used for some debug drawing and for drawing certain lines. Mostly it is only used in the editor. If you want to test in a project, you need to use the `draw_line()` method of CanvasItem.

 > NOTE: all these changes did not fix the GPUParticles2D issue (particles aren't showed at all).

Maybe you need to make the same change where the values are packed:

https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/drivers/gles3/shaders/particles_copy.glsl#L111

**Comment by clayjohn** [comment]
> There are some other similar piece of code also in `scene.glsl`. Can I change them too?

Yes please. Those are used by 3D particles, so I assume the same change is needed there

**Comment by joined72** [comment]
> > If you think these are acceptable changes then the following piece of code would also need to be modified, although I don't know exactly what it does.
> 
> Let's change that code too. It is used for some debug drawing and for drawing certain lines. Mostly it is only used in the editor. If you want to test in a project, you need to use the `draw_line()` method of CanvasItem.

Done and tested, all works fine.

> > There are some other similar piece of code also in `scene.glsl`. Can I change them too?
> 
> Yes please. Those are used by 3D particles, so I assume the same change is needed there

Done and tested, works fine (tested on **NOT Adreno 3XX** devices).

> > NOTE: all these changes did not fix the GPUParticles2D issue (particles aren't showed at all).
> 
> Maybe you need to make the same change where the values are packed:
> 
> https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/drivers/gles3/shaders/particles_copy.glsl#L111

Done but **WITHOUT** success. Could be the problem is related to the `ParticleProcessMaterial` Object?

**Comment by clayjohn** [comment]
> Done but **WITHOUT** success. Could be the problem is related to the `ParticleProcessMaterial` Object

It could be. I don't think we do any data packing like this in the ParticleProcessMaterial code though

**Comment by joined72** [comment]
> > Done but **WITHOUT** success. Could be the problem is related to the `ParticleProcessMaterial` Object
> 
> It could be. I don't think we do any data packing like this in the ParticleProcessMaterial code though

To test if was a `ParticleProcessMaterial` related issue, I used as `Process Material` a very simple custom `ShaderMaterial` with the following code:

```.cpp
shader_type particles;

void start() {
    VELOCITY = vec3(0.0, 1.0, 0.0); // Initial velocity
}

void process() {
    VELOCITY.y += 1.0; // Apply gravity
}
```

...same problem, **no particles are showed**, so I think we have to search for this issue in another direction.

**Comment by joined72** [comment]
From my research, it seems that the problem is the [drivers/gles3/shaders/particles_copy.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/particles_copy.glsl) shader, receives incorrect parameters (specifically `velocity_flags`), in fact by commenting on the following line, the particles appear even if they do not move.

```.cpp
	// if (bool(floatBitsToUint(velocity_flags.w) & PARTICLE_FLAG_ACTIVE))

```

I tried to figure out who passed the parameters to [particles_copy.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/particles_copy.glsl) shader, but I couldn't.

I thought it was passed to it by the [particles.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/particles.glsl), but by changing its `out_` parameters, [particles_copy.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/particles_copy.glsl) still gets the wrong ones.

**Comment by joined72** [comment]
From the Chat...
> I don't think we can set flags = PARTICLE_FLAG_ACTIVE every cycle without breaking something. There are many cases where the flag should be inactive, even though emitting is true. Like if you use particle lifetime randomness or explosiveness

@clayjohn 
My problem is that I still can't figure out who initializes `velocity_flags.w` in the **particles.glsl** shader.

I understand that `out_velocity_flags` of **particles.glsl** is passed as **input** parameter to **particles_copy.glsl**, but I still don't understand who is initializing the `velocity_flags` **input** parameter of **particles.glsl**. 

If I could understand this well, I think I could understand why, in **Adreno 3XX** devices, this parameter is always **ZERO**.

**Comment by joined72** [comment]
A few days ago I received a **Sony Xperia M2 (Adreno 305)**, which happens to be one of the oldest devices in the **Adreno 3XX** family.

I bought it to check if my fixes were sufficient even for such an old device and I discovered that they **were NOT**. 

I therefore had to do more research to get `MultiMeshInstance2D` and `CPUParticles2D` working on **Adreno 305** as well. 

What I discovered is that such old **Adreno** drivers have the following extra bugs

-  expose some GLES 310 functions on GLES 300
-  these incorrectly exposed functions **ARE BUGGED**
-  if you call functions present in an `included file`, but inside an `#ifdefs/#endif` block, they give a compilation error: `"'assign' : cannot convert from 'const float' to '2-component vector of float'"`

To fix all these bugs I had to rename all the functions of `stdlib_inc.glsl`, adding the `godot_` prefix, (and those that use them), and eliminate the `#ifdef USE_GLES_OVER_GL`.

@clayjohn can you take a look and tell me what do you think, please?

**Comment by joined72** [comment]
I'm running some benchmarks to test the new `godot_` functions speed. 

From my tests, results that calling the `godot_` functions about **100.000 times/sec** there isn't any performance impact.

Test results (100.000 calls/secs):

* Samsung Galaxy Note 4 - performance lost **0.25%**
* Huawei Honor 7A - performance lost **0.9%**
* Xiaomi Redmi 8 - performance lost **0%**
* Xiaomi Redmi 10 - performance lost **0%**
* Xiaomi Redmi 12 - performance lost **0%**
* Huawei Honor 9 Lite -  performance lost **0%**
* LG G4 -  performance lost **0%**

There is a really minimal performance loss only on very old devices but we have to consider that we are calling these functions **100.000 times/sec**.

**Comment by joined72** [comment]
After further investigation I found that to fix the **Adreno 305** extra bugs, is enough to simply remove any `#ifdef/#endif` code from the [stdlib_inc.glsl](https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/stdlib_inc.glsl) shader! :)

**Comment by joined72** [comment]
@clayjohn 

Currently this **PR** brings the following fixes:

1. fixes the freeze caused by the presence of `GPUParticles2D`
2. fix `CPUParticles2D` and `MultiMeshes` (now they work perfectly)

Considering that the number of bugs to fix `GPUParticles2D` on **Adreno 3XX** devices increases (I just identified a new **bug/freeze** in the [scene/resources/particle_process_material.cpp](https://github.com/godotengine/godot/blob/master/scene/resources/particle_process_material.cpp) code), and considering how slow the **Adreno 3XX** family devices are in processing `GPUParticles2D` (I can say this because even if the particles are not displayed, they are still processed and a notable **decrease in FPS of at least 10/12 FPS** for simple particles can be measured), and considering how many fixes this **PR** brings on all **Adreno 3XX** devices (even on very old devices, like **Adreno 305**) and how much time was required to debug only the part relating to `GPUParticles2D`, without finding any fixes, I decided, at least for the moment, to disable `GPUParticles2D` at all on each **Adreno 3XX** device.

_Can I ask for the review required for the merge, please? ;)_

File: drivers/gles3/shaders/stdlib_inc.glsl [hunk 2]
```diff
@@ -1,5 +1,9 @@
 
-#ifdef USE_GLES_OVER_GL
+// Compatibility renames. These are exposed with the "godot_" prefix
```
Comment (clayjohn) [inline drivers/gles3/shaders/stdlib_inc.glsl:2]: I think we can do this a little cleaner. I don't like making users write "godot_" before these function calls. Its a recipe to introduce regressions. 

Let's look at the reasons why functions in this file exist:
1. lines 4-47 are introduced on desktop only because these functions are part of the GLSL es 300 spec but not the GLSL 330 spec. So they keep their original names, but are only added for destop devices
2. lines 54-76 are introduced because on newer Adreno devices the `pack_***_4x8` functions are wrongfully exposed resulting in a redefinition error. Since we shouldn't have access to those functions anyway, we force the compiler to use the ones defined by us.
3. With this PR, it seems that older Adreno devices have bugs with the packing functions, so we want to use our manually implemented ones instead. In order to use our manually implemented ones, we need t change the function names to avoid function name conflicts. 

I am okay with always falling back to the functions we defined (they shouldn't be any slower than the driver implemented versions and your testing confirmed that). However, since you have used #define to replace the functions with our internal functions, we should not be using the "godot_" prefix in shaders. Shaders should continue to use the normal name (i.e. `packHalf2x16` instead of `godot_packHalf2x16`)

File: drivers/gles3/shaders/stdlib_inc.glsl [hunk 3]
```diff
@@ -1,5 +1,9 @@
...
+// to work around an Adreno bug which was exposing these ES310 functions
+// in ES300 shaders. Internally, we must use the "godot_" prefix, but user shaders
+// will be mapped automatically.
```
Comment (clayjohn) [inline drivers/gles3/shaders/stdlib_inc.glsl:5]:
```suggestion
// Compatibility renames. These are exposed with the "godot_" prefix
// to work around two distinct Adreno bugs:
// 1. Some Adreno devices expose ES310 functions in ES300 shaders.
//    Internally, we must use the "godot_" prefix, but user shaders
//    will be mapped automatically.
// 2. Adreno 3XX devices have poor implementations of the other packing
//    functions, so we just use our own everywhere to keep it simple.
```

File: drivers/gles3/shaders/stdlib_inc.glsl (hunk 2 above)
Comment (joined72) [reply drivers/gles3/shaders/stdlib_inc.glsl:2]: Yes I understand. Changes just committed! ;)

**Review by clayjohn — APPROVED** [review]
Looks good to me now! Great investigative work

**Comment by akien-mga** [comment]
Thanks!
