### PR TITLE
Tweak macOS notarization export message in the editor

### LINKED ISSUE #110674: Mac notarization feedback is hard to read and use, incomplete, and has typo
### Tested versions

v4.5.stable.mono.official [876b29033]

### System information

Godot v4.5.stable.mono - macOS Sequoia (15.6.0) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (8 threads) - 32.00 GiB memory

### Issue description

I experimented with notarization and had trouble with the report. Arguably there are multiple issues but they are all in the attached output.

1. The text was very hard to read, grey on dark grey. Suggest lightening all text (or making the background white).
2. I couldn’t copy the UUID to run the Terminal commands. Suggest allowing copying.
3. The commands were not correct, I had to also specify `--team-id` along with `--apple-id`.
4. There is a typo, `>>` should be `>`.

Image

### Steps to reproduce

Notarize a Mac build

### Minimal reproduction project (MRP)

This is probably not project specific.

### PR DESCRIPTION
**Pull request by Calinou**
One message had a typo and was missing `--team-id` for one of the `xcrun notarytool` commands.

- This closes https://github.com/godotengine/godot/issues/110674.
  - Note that I didn't change the text contrast in this PR, as per https://github.com/godotengine/godot/issues/110674#issuecomment-3321411517.

### CODE REVIEW

File: platform/macos/export/export_plugin.cpp [hunk 1]
```diff
@@ -1165,9 +1165,9 @@ Error EditorExportPlatformMacOS::_notarize(const Ref<EditorExportPreset> &p_pres
...
 				add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), TTR("The notarization process generally takes less than an hour."));
-				add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t" + TTR("You can check progress manually by opening a Terminal and running the following command:"));
-				add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t\t\"xcrun notarytool log <request uuid> --issuer <api uuid> --key-id <api key id> --key <api key path>\" or");
-				add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t\t\"xcrun notarytool log <request uuid> --apple-id <your email> --password <app-specific pwd>>\"");
+				add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t" + TTR("You can check the progress manually by opening a Terminal and running the following command:"));
+				add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t\t\"xcrun notarytool log <request UUID> --issuer <API UUID> --key-id <API key ID> --key <API key path>\" or");
+				add_message(EXPORT_MESSAGE_INFO, TTR("Notarization"), "\t\t\"xcrun notarytool log <request UUID> --team-id <team ID from Xcode> --apple-id <your email> --password <app-specific password>\"");
```
Comment (Calinou) [inline platform/macos/export/export_plugin.cpp]: Getting the team ID seems nontrivial: https://stackoverflow.com/questions/18727894/how-can-i-find-my-apple-developer-team-id-and-team-agent-apple-id

I'm not sure how well we can explain the procedure here.

Comment (alakoring) [reply platform/macos/export/export_plugin.cpp]: In fact I looked up my team ID on developer.apple.com so I don’t know if there’s any better text. But I’m happy that it is now mentioned as a required parameter.

Comment (bruvzg) [reply platform/macos/export/export_plugin.cpp]: Team ID should be visible on the developer portal (membership details), see https://developer.apple.com/help/glossary/team-id

It should be the same as user id (in the certificate name) in most cases.

**Review by bruvzg — APPROVED** [review]

File: platform/macos/export/export_plugin.cpp (hunk 1 above)
Comment (Calinou) [reply platform/macos/export/export_plugin.cpp]: I've added a link to that page in the message.

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.5.1.
