### PR TITLE
Fix dragged nodes icon size

### LINKED ISSUE #79255: Dragged nodes have no icon size limit in script editor
### Godot version

4.1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/3c8ee782-9d5f-42e3-a70f-d2aa59a233dd

We correctly clamp the size to 16x16 everywhere except here (probably).

### Steps to reproduce

1. Add a class with custom icon, e.g.
```GDScript
@icon("res://icon.svg")
extends Node
class_name Icon
```
2. Add it to scene
3. Open Script Editor and drag the node to script editor

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by sepTN**
Fix #79255 

https://github.com/godotengine/godot/assets/13846022/fc068447-710c-4edb-867e-47a9636c9661

### CODE REVIEW

File: editor/gui/scene_tree_editor.cpp [hunk 1]
```diff
@@ -1208,7 +1208,10 @@ Variant SceneTreeEditor::get_drag_data_fw(const Point2 &p_point, Control *p_from
 		if (i < list_max) {
 			HBoxContainer *hb = memnew(HBoxContainer);
 			TextureRect *tf = memnew(TextureRect);
-			tf->set_texture(icons[i]);
+			int icon_size = get_theme_constant(SNAME("class_icon_size"), SNAME("Editor"));
+			Ref<Image> img = icons[i]->get_image();
+			img->resize(icon_size, icon_size);
+			tf->set_texture(ImageTexture::create_from_image(img));
```
Comment (YuriSizov) [inline editor/gui/scene_tree_editor.cpp:1214]: That's wrong. Resizing images is expensive and shouldn't be done. You need to enforce its maximum size. See https://github.com/godotengine/godot/pull/75472/commits/1522762dc986c130ad63cbf854514d730788a4cf.

You need to give the image a minimum size and then configure flags.

```suggestion
			tf->set_custom_minimum_size(Size2(icon_size, icon_size));
			tf->set_stretch_mode(TextureRect::STRETCH_KEEP_ASPECT_CENTERED);
			tf->set_expand_mode(TextureRect::EXPAND_IGNORE_SIZE);
			tf->set_texture(icons[i]);
```

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.
