### PR TITLE
Fixed empty item slipping into Search Classes dialog

### LINKED ISSUE #21640: Empty item inside "Search Classes" dialog
**Godot version:**
29f2571662da0ee93ea2a632ec3b60aa26246563

**Issue description:**
screenshot at 2018-08-31 21-26-52

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed empty item slipping into Search Classes dialog.

Phew tracking this down was weird.

Fixes #21640

### CODE REVIEW

File: editor/editor_help.cpp [hunk 1]
```diff
@@ -761,7 +761,9 @@ void EditorHelp::_update_doc() {
 
 	_init_colors();
 
-	DocData::ClassDoc cd = doc->class_list[edited_class]; //make a copy, so we can sort without worrying
+	DocData::ClassDoc cd;
+	if (doc->class_list.has(edited_class)) //check to prevent empty string slipping into class_list
```
Comment (akien-mga) [inline editor/editor_help.cpp]: AFAIK the whole function is moot if this condition is false, so it would be better to just have
```cpp
if (doc->class_list.has(edited_class)) {
    return;
```
at the very top of the method.

**Comment by akien-mga** [comment]
While this fix is correct and good to merge, I wonder why `_update_doc` gets called with an invalid class name in the first place? That might be worth tracking down further to fix the issue at its root.

I also wonder why we're building the whole classref with all the fancy formatting just to populate the Search Classes dialog, sounds like an expensive way to access classref contents.

File: editor/editor_help.cpp (hunk 1 above)
Comment (DualMatrix) [reply editor/editor_help.cpp]: You mean 

`if (!doc->class_list.has(edited_class)) {
    return;`

With ! right?

Comment (akien-mga) [reply editor/editor_help.cpp]: Ah sure :D

Comment (DualMatrix) [reply editor/editor_help.cpp]: Added that line.

**Comment by akien-mga** [comment]
As discussed with @reduz, the original issue might be that `edited_class` is initially an empty String, so if `_update_doc` gets called with its value (e.g. in `NOTIFICATION_READY`) this can happen.

But the proposed fix is fine enough to "hide" this issue.
