### PR TITLE
Show Anchor even when Control-Node is hidden

### LINKED ISSUE #9542: Unable to set anchor if control node is hidden
**Operating system or device - Godot version:**
Windows 8.1 Godot 3.0 alpha

**Steps to reproduce:**
Make control node
Hide it
Cannot change anchor in top tool panel

### PR DESCRIPTION
**Pull request by H4kor**
Fixes #9542

### CODE REVIEW

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -2080,7 +2080,7 @@ void CanvasItemEditor::_notification(int p_what) {
 		}
 
 		bool show_anchor = all_control && has_control;
-		if (show_anchor != anchor_menu->is_visible()) {
+		if (show_anchor) {
 			if (show_anchor)
```
Comment (Noshyaar) [inline editor/plugins/canvas_item_editor_plugin.cpp]: Duplicated `if` condition

**Comment by Noshyaar** [comment]
`show_anchor` is used only once. Not sure if declaring it is necessary.

**Comment by akien-mga** [comment]
It would be nice to use more explicit logs for your commits, that it fixes a given issue ID is relevant information, but when reading `git log` it doesn't tell much :)
