### PR TITLE
Prevent opening Windows console files

### LINKED ISSUE #20110: Engine hangs when trying to preload a resource from script starting with OS reserved names
**Godot version:**
3.0+, 4.0+

**OS/device including version:**
Windows 10 1803 build 17134.165

**Issue description:**
I have tried to preload a script `condition.gd` using relative path:

gif

```gdscript
const Condition = preload("con 
# engine hangs after `con` is typed
```

After that the engine hangs (no crash), with the following output (master, in official just hangs the engine)
```
WARNING: _open: Case mismatch opening requested file 'con.remap', stored as 'con' in the filesystem. This file will not open when exported to other case-sensitive platforms.
     At: drivers/windows/file_access_windows.cpp:102
```
The issue is most likely related to the fact that parser tries to manipulate OS [reserved names](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file) as pointed by [KellyThomas](https://github.com/godotengine/godot/issues/20110#issuecomment-404477478)

**Workaround:**
gif2

😄

**Minimal reproduction project:**
[con-preload-hang.zip](https://github.com/godotengine/godot/files/2188067/con-preload-hang.zip)

### PR DESCRIPTION
**Pull request by reduz**
These reserved console files are a legacy from the MS/DOS days, but opening them can still crash Godot.

Fixes #20110.

### CODE REVIEW

File: drivers/windows/file_access_windows.cpp [hunk 1]
```diff
@@ -59,6 +58,19 @@ void FileAccessWindows::check_errors() const {
 }
 
 Error FileAccessWindows::open_internal(const String &p_path, int p_mode_flags) {
+	{
+		// Check for invalid operating system file.
+		String f = p_path;
```
Comment (akien-mga) [inline drivers/windows/file_access_windows.cpp:63]: Shadows class member, which is a warning treated as error for MSVC.

**Comment by akien-mga** [comment]
Does it raise a user-friendly error? What happens if you author a scene on Linux named `con.tscn` and try to load it on Windows?

File: drivers/windows/file_access_windows.cpp [hunk 2]
```diff
@@ -352,4 +364,20 @@ FileAccessWindows::~FileAccessWindows() {
 	_close();
 }
 
+HashSet<String> FileAccessWindows::invalid_files;
+
+void FileAccessWindows::initialize() {
+	static const char *reserved_files[]{
+		"con", "prn", "aux", "nul", "com1", "com2", "com3", "com4", "com5", "com6", "com7", "com8", "com9", "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9", nullptr
```
Comment (bruvzg) [inline drivers/windows/file_access_windows.cpp:371]:
```suggestion
		"con", "prn", "aux", "nul", "com0", "com1", "com2", "com3", "com4", "com5", "com6", "com7", "com8", "com9", "lpt0", "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9", nullptr
```

https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by reduz** [comment]
@akien-mga I have no idea if we should raise an error, this function is not supposed to give you error text if it fails (the editor would be spammed). Maybe I could check whether the editor is running and throw an error, or throw an error if writing?

**Comment by reduz** [comment]
Okay, now it will throw a warning if you attempt to write to it, reading probably not need it. This will avoid spamming the editor when trying to reproduce the issue linked.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
