### PR TITLE
Fix initialization order in `AudioStreamInteractive` to allow `initial_clip` to be properly played

### LINKED ISSUE #100514: Clip index problem when changing “Initial Clip” value other than 0
### Tested versions

- Reproducible in : v4.3.stable.official [77dcf97d8], v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.3.stable - Windows 10.0.26100 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6614) - 11th Gen Intel(R) Core(TM) i9-11900 @ 2.50GHz (16 Threads)

### Issue description

When trying to change the value of parameter "Initial clip" in an AudioStreamInteractive ressource and launching a scene, an error appear and the clip played is the first clip in the list of clip:
```
"E 0:00:00:0793   set_initial_clip: Index p_clip = 2 is out of bounds (clip_count = 0).
  <C++ Source>   modules/interactive_music/audio_stream_interactive.cpp:89 @ set_initial_clip()
```

### Steps to reproduce

- Open a project
- Create a scene with a root node and an AudioStreamPlayer
- Add an AudioStreamInteractive ressource
- Add clips and stream
- Change the value of “Initial Clip” on any clip except the first in the list
- Launch the scene
- Error appear

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by mdelorme**
Fixes #100514 

Problem comes from the initialization order of `initial_clip` coming before the actual clips. When the `AudioStreamInteractive` is loaded in the scene, no clips are loaded yet. `initial_clip` is reset to 0 triggering the error. Then the clips are loaded, and the `initial_clip` will inevitably become the first of the list.

I propose a fix by simply changing the order of the two properties in the class. Having the `initial_clip` being declared after the actual clips, fixes everything.

### CODE REVIEW

File: modules/interactive_music/audio_stream_interactive.cpp [hunk 1]
```diff
@@ -484,15 +484,15 @@ void AudioStreamInteractive::_bind_methods() {
...
 	for (int i = 0; i < MAX_CLIPS; i++) {
 		ADD_PROPERTYI(PropertyInfo(Variant::STRING_NAME, "clip_" + itos(i) + "/name", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_INTERNAL), "set_clip_name", "get_clip_name", i);
 		ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "clip_" + itos(i) + "/stream", PROPERTY_HINT_RESOURCE_TYPE, "AudioStream", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_INTERNAL), "set_clip_stream", "get_clip_stream", i);
 		ADD_PROPERTYI(PropertyInfo(Variant::INT, "clip_" + itos(i) + "/auto_advance", PROPERTY_HINT_ENUM, "Disabled,Enabled,ReturnToHold", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_INTERNAL), "set_clip_auto_advance", "get_clip_auto_advance", i);
 		ADD_PROPERTYI(PropertyInfo(Variant::INT, "clip_" + itos(i) + "/next_clip", PROPERTY_HINT_ENUM, "", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_INTERNAL), "set_clip_auto_advance_next_clip", "get_clip_auto_advance_next_clip", i);
 	}
+	
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "initial_clip", PROPERTY_HINT_ENUM, "", PROPERTY_USAGE_DEFAULT), "set_initial_clip", "get_initial_clip");
```
Comment (akien-mga) [inline modules/interactive_music/audio_stream_interactive.cpp:495]:
```suggestion
	// Needs to be registered after `clip_*` properties, as it depends on them.
	ADD_PROPERTY(PropertyInfo(Variant::INT, "initial_clip", PROPERTY_HINT_ENUM, "", PROPERTY_USAGE_DEFAULT), "set_initial_clip", "get_initial_clip");
```

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by mdelorme** [comment]
I think I messed up and included another commit in the PR. Lemme fix that. Sorry

**Comment by mdelorme** [comment]
All good now

**Review by akien-mga — APPROVED** [review]

**Comment by mdelorme** [comment]
Sorry for that, am I the one supposed to fix this or can the formatting changes be approved by a maintainer ?

**Comment by akien-mga** [comment]
You need to do the formatting fixes yourself ideally. You'd do it by removing the trailing tab on the line flagged in the diff: https://github.com/godotengine/godot/actions/runs/12394304279/job/34597974426?pr=100552

And then amend the commit and force push to udpate the PR, keeping a single commit.

**Comment by mdelorme** [comment]
Ok ! Thank you very much for the guidance :)
Fix applied !

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
