### PR TITLE
Customize the file manager label for each platform

### LINKED ISSUE #89533: 'Show in File System' should be 'Show in Finder' on macOS
### Tested versions

4.2.1

### System information

Godot v4.2.1.stable - macOS 14.3.1 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

On macOS, the file explorer is called 'Finder'. It's a term macOS users are used to, so if a context menu in the 'File System' tab of Godot refers to it using a different name ('File Manager'), it is not clear whether that refers to another feature of Godot or the OS. For clarity, it should simply state 'Show in Finder', and every macOS user will know exactly what the option does.

Screenshot 2024-03-15 at 20 34 16

### Steps to reproduce

- Right mouse click on any file in the FileSystem tab of Godot.
- The second to last item is 'Show in File Manager' while 'Show in Finder' would be a lot more clear and intuitive for macOS users.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by adamscott**
This PR changes the lines "Open in File Manager" and "Show in File Manager" to the following: 

| Platform | Line |
| :---: | :--- |
| Windows | ~~Reveal~~ Show in File Explorer |
| macOS | ~~Reveal~~ Show in Finder |
| _others_ | ~~Reveal~~ Show in File Manager |

Capture d’écran, le 2024-06-10 à 11 28 52

As said @kitbdev on https://github.com/godotengine/godot/issues/89533#issuecomment-2002007135 :
> For reference, in [VSCode](https://github.com/microsoft/vscode/blob/b3b3473543f98f70acd9587ea46c17c0e521706c/src/vs/workbench/contrib/files/electron-sandbox/fileActions.contribution.ts#L27):
> 
>     * On Windows "Reveal in File Explorer"
> 
>     * On Mac "Reveal in Finder"
> 
>     * Otherwise "Open Containing Folder"
> 
> 
> And they are translated separately.

I chose to use "Reveal in File Manager" for the other platforms as it is close to what we already had.

The fact that it uses reveal for each platform will help the documentation team to say "click on the reveal button" instead of enumerating the choices each time.

Fixes #89533

### CODE REVIEW

**Comment by adamscott** [comment]
Makes me think @bruvzg, does Finder exist on iOS?

**Comment by bruvzg** [comment]
On iOS its called `Files`, but we do not have iOS editor support anyway.

**Comment by AThousandShips** [comment]
I'd say this doesn't necessarily improve usability, it might be hard to ensure valid translations and it makes writing documentation harder. It also might be confusing in cases where someone has replaced the file manager on macOS, as well as on Windows 7 where it's not called "File Explorer"

I don't expect many users to be confused by the term "File Manager"

**Comment by KoBeWi** [comment]
The funny thing about Windows is that the old name "Windows Explorer" still shows in the Task Manager, which is probably where you see its name the most. I didn't even know it was renamed.

**Comment by adamscott** [comment]
> I'd say this doesn't necessarily improve usability, it might be hard to ensure valid translations and it makes writing documentation harder (I'd say directing to the "reveal button" will be confusing, people would expect it to say just "reveal"). It also might be confusing in cases where someone has replaced the file manager on macOS, as well as on Windows 7 where it's not called "File Explorer"
>
> I don't expect many users to be confused by the term "File Manager"

I don't agree. I think localizing the app for the OS is more important than trivial translation and documentation issues. It's small issues like that makes an application feel like a "dumb" port or feel like a native experience.

We already "adapt" to OSes specificity, like this example:

Capture d’écran, le 2024-06-10 à 12 34 24

Here, the editor settings on macOS are in the application tab, instead of being in the Editor tab. It threw me off a little bit at the beginning, but I wouldn't change this at all. It isn't "macOS" otherwise.

> (The issue also has no real support)

That's not what I read from the comments. And since I recently began to daily drive Godot on macOS, I begin to feel and understand more which issues are impacting macOS users, such as this one.

**Comment by adamscott** [comment]
> The issue has no upvotes (issue OP doesn't count) and 6 confused faces

I did like the issue because I just found about it. And I think it's really important for us to support OSes small details like this.

> most of the comments that aren't OP also don't actively agree, where are you seeing support for this?

Here's what @akien-mga said:
> It's not a hill I'd die on though, if macOS users overwhelmingly want this change for the editor to feel more native to their environment, we can likely do it. But they'll have to live with the potential inconsistency in the docs or if they don't use Finder.

Here's what @passivestar said:
> Personally I wouldn't change it, but if a lot of macOS users feel strongly about it I wouldn't have a problem with this either. It's very rare for documentation to talk about that particular button (I think currently neither godot or unity docs have any mention of it, at least I couldn't easily find it). In any case I think it's a tiny nuance

I think @kitbdev's [comment](https://github.com/godotengine/godot/issues/89533#issuecomment-2002007135) is neutral, but does underline that VSCode uses different terms for each platform.

> But I think we'd need some data on that users find "File Manager" confusing, because I don't believe most users would, on the other hand making translation harder and invalidating old translation and creating a difference between versions will cause confusion. Further this makes translation depend on people knowing this is specifically macOS, or they'll risk translating it incorrectly

For me, I don't think it's about confusion, but more about the "nativeness" of the platform. And I think that we should at least make sure that we must absolutely do what's in the "possible" to accommodate to different platforms idioms.

**Comment by AThousandShips** [comment]
My point was that there isn't much support and I think your quotes reinforces that, and I think changing this with all the costs involved without it actually being something that's in demand is backwards

**Comment by KoBeWi** [comment]
Also, as said in https://github.com/godotengine/godot/issues/89533#issuecomment-2001890099, you can change the system's file manager, so a non-generic name will become incorrect.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -7305,7 +7305,18 @@ EditorNode::EditorNode() {
...
 
 	remove_android_build_template = memnew(ConfirmationDialog);
-	remove_android_build_template->set_ok_button_text(TTR("Show in File Manager"));
+
+#if defined(WINDOWS_ENABLED)
+	const String ok_button_text = TTR("Reveal in File Explorer");
+#elif defined(MACOS_ENABLED)
+	const String ok_button_text = TTR("Reveal in Finder");
+#elif defined(IOS_ENABLED)
+	const String ok_button_text = TTR("Reveal in Files");
```
Comment (AThousandShips) [inline editor/editor_node.cpp:7314]: Why this? This won't be used without iOS editor support and AFAIK that's blocked by limitations with the platform itself, with the needed capabilities and ability to distribute the editor

Comment (adamscott) [reply editor/editor_node.cpp:7314]: You can technically build the iOS editor if you want. So, it should be supported, especially if there's no drawbacks.

Comment (AThousandShips) [reply editor/editor_node.cpp:7314]: Sure but I don't see the value in adding it to something that doesn't have official support

Comment (bruvzg) [reply editor/editor_node.cpp:7314]: Yes, you can build editor for iOS (with some code changes and a lot of limitations), but `shell_show_in_file_manager` is not implemented for iOS, so this editor feature will not work.

Comment (adamscott) [reply editor/editor_node.cpp:7314]: I'll revert then the latest commit.

**Comment by adamscott** [comment]
### Some examples of multi platform apps
<details>
<summary>macOS</summary>

Capture d’écran, le 2024-06-10 à 14 31 24

</details>

<details>
<summary>Firefox</summary>

Capture d’écran, le 2024-06-10 à 14 36 35

</details>

<details>
<summary>Chrome</summary>

Capture d’écran, le 2024-06-10 à 14 37 42

</details>

<details>
<summary>Obsidian</summary>

Capture d’écran, le 2024-06-10 à 14 11 59

</details>

<details>
<summary>IntelliJ Idea CE</summary>

Capture d’écran, le 2024-06-10 à 14 22 31

</details>

<details>
<summary>Adobe Premiere Pro</summary>

image

image

</details>

<details>
<summary>Transmission</summary>

Capture d’écran, le 2024-06-10 à 14 34 38

</details>

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -3321,7 +3321,17 @@ void FileSystemDock::_file_and_folders_fill_popup(PopupMenu *p_popup, const Vect
...
-		p_popup->set_item_text(p_popup->get_item_index(FILE_SHOW_IN_EXPLORER), is_directory ? TTR("Open in File Manager") : TTR("Show in File Manager"));
+
+		// Show in file manager string.
+#if defined(WINDOWS_ENABLED)
+		const String item_text = TTR("Reveal in File Explorer");
+#elif defined(MACOS_ENABLED)
+		const String item_text = TTR("Reveal in Finder");
+#else
+		const String item_text = TTR("Reveal in File Manager");
+#endif
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:3332]: The repeated code needs to be extracted into a method.

Comment (adamscott) [reply editor/filesystem_dock.cpp:3332]: I fully agree. Do we have already a central file for easy access to translations?

**Comment by passivestar** [comment]
> you can change the system's file manager

for what it's worth in over a decade of using macOS I've never heard of anyone changing system's file manager and it never came up in any app reviews/recommendations that I saw. Seems to be a very uncommon thing to do on macOS

File: editor/filesystem_dock.cpp (hunk 2 above)
Comment (KoBeWi) [reply editor/filesystem_dock.cpp:3332]: You could just add a static method like `FileSystemDock::get_file_manager_option()` or something. `TTR()` is available globally.

**Comment by bruvzg** [comment]
> It also might be confusing in cases where someone has replaced the file manager on macOS

On macOS, we can get current file manager name if it was customized, something like:
```obj-c++
String _get_default_file_manager() {
	NSString *fileviewer_id = [[NSUserDefaults standardUserDefaults] stringForKey:@"NSFileViewer"];
	if (fileviewer_id) {
		NSString *fileviewer_path = [[NSWorkspace sharedWorkspace] absolutePathForAppBundleWithIdentifier:fileviewer_id];
		if (fileviewer_path) {
			NSBundle *fileviewer_bundle = [NSBundle bundleWithPath:fileviewer_path];
			if (fileviewer_bundle) {
				NSString *fileviewer_name = [[fileviewer_bundle infoDictionary] objectForKey:@"CFBundleName"];
				if (fileviewer_name) {
					return String::utf8([fileviewer_name UTF8String]);
				}
			}
		}
	}
	return U"Finder";
}
```

**Comment by JoNax97** [comment]
I don't have a strong opinion either way, I just wanted to say that the "reveal" verb feels alien as a windows user. 

I think 'show' or 'open' are more common and expected

**Comment by adamscott** [comment]
> > you can change the system's file manager
> 
> for what it's worth in over a decade of using macOS I've never heard of anyone changing system's file manager and it never came up in any app reviews/recommendations that I saw. Seems to be a very uncommon thing to do on macOS

@passivestar It was more about that my PR changes the sentence for Windows too, for "Reveal in File Explorer"

File: editor/filesystem_dock.cpp (hunk 2 above)
Comment (adamscott) [reply editor/filesystem_dock.cpp]: This should be technically inside the `platforms/` directory. So I'll let this as that, but with a todo to port it to platforms.

**Comment by adamscott** [comment]
I updated the text to "Show in" instead of "Reveal in".

**Review by Calinou — COMMENTED** [review]
Tested locally on Linux, it works as expected. The rationale makes sense to me.

One thing I find strange though is that if I right-click empty space in the FileSystem dock (e.g. below `res://` when it's collapsed), I still see "Open in File Manager" even though this PR doesn't add it anywhere:

image

**Comment by AThousandShips** [comment]
> One thing I find strange though is that if I right-click empty space in the FileSystem dock (e.g. below res:// when it's collapsed), I still see "Open in File Manager" even though this PR doesn't add it anywhere:

There's two places which creates this menu, it seems only one of them is covered by this PR

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -7305,7 +7305,16 @@ EditorNode::EditorNode() {
 	}
 
 	remove_android_build_template = memnew(ConfirmationDialog);
-	remove_android_build_template->set_ok_button_text(TTR("Show in File Manager"));
+
+#if defined(WINDOWS_ENABLED)
```
Comment (skarnl) [inline editor/editor_node.cpp:7309]: imho, this repeating logic + strings should be extracted into a separate centralized function.

Now it's repeated over 4 files, with exactly the same logic and strings
Could be just a simple helper-function.

Comment (adamscott) [reply editor/editor_node.cpp:7309]: Not worth it, I think. Especially that the string should be coming ideally from the OS instead of being fed directly in the code.

**Review by AdriaandeJongh — APPROVED** [review]
I haven't looked at the code, but barring fixing the merge conflicts I think this is a big UX improvement on both macOS and Windows as it removes a bit of confusion between the FileSystem, File Manager, and the name of the native file system.

File: editor/project_manager/project_list.cpp [hunk 4]
```diff
@@ -326,13 +326,13 @@ void ProjectListItemControl::set_is_missing(bool p_missing) {
...
-#if !defined(ANDROID_ENABLED) && !defined(WEB_ENABLED)
-		explore_button->set_button_icon(get_editor_theme_icon(SNAME("Load")));
-		explore_button->set_tooltip_text(TTRC("Show in File Manager"));
-#else
+#if defined(ANDROID_ENABLED) || defined(WEB_ENABLED)
 		// Opening the system file manager is not supported on the Android and web editors.
 		explore_button->hide();
-#endif
+#else // !defined(ANDROID_ENABLED) && !defined(WEB_ENABLED)
+		explore_button->set_tooltip_text(OS::get_singleton()->get_tr_file_manager_open());
```
Comment (AdriaandeJongh) [inline editor/project_manager/project_list.cpp]:
```suggestion
		explore_button->set_tooltip_text(OS::get_singleton()->get_tr_file_manager_show());
```

File: editor/editor_node.cpp [hunk 5]
```diff
@@ -9162,7 +9162,7 @@ EditorNode::EditorNode() {
 	}
 
 	remove_android_build_template = memnew(ConfirmationDialog);
-	remove_android_build_template->set_ok_button_text(TTR("Show in File Manager"));
+	remove_android_build_template->set_ok_button_text(OS::get_singleton()->get_tr_file_manager_open());
```
Comment (AdriaandeJongh) [inline editor/editor_node.cpp]:
```suggestion
	remove_android_build_template->set_ok_button_text(OS::get_singleton()->get_tr_file_manager_show());
```

File: modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp [hunk 6]
```diff
@@ -270,7 +270,7 @@ void ObjectDBProfilerPanel::_snapshot_rmb(const Vector2 &p_pos, MouseButton p_bu
 	rmb_menu->clear(false);
 
 	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Rename")), TTRC("Rename"), OdbProfilerMenuOptions::ODB_MENU_RENAME);
-	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Folder")), TTRC("Show in File Manager"), OdbProfilerMenuOptions::ODB_MENU_SHOW_IN_FOLDER);
+	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Folder")), OS::get_singleton()->get_tr_file_manager_open(), OdbProfilerMenuOptions::ODB_MENU_SHOW_IN_FOLDER);
```
Comment (AdriaandeJongh) [inline modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp]:
```suggestion
	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Folder")), OS::get_singleton()->get_tr_file_manager_show(), OdbProfilerMenuOptions::ODB_MENU_SHOW_IN_FOLDER);
```

File: editor/project_manager/project_list.cpp [hunk 7]
```diff
@@ -326,13 +326,13 @@ void ProjectListItemControl::set_is_missing(bool p_missing) {
...
-		explore_button->set_button_icon(get_editor_theme_icon(SNAME("Load")));
-		explore_button->set_tooltip_text(TTRC("Show in File Manager"));
-#else
+#if defined(ANDROID_ENABLED) || defined(WEB_ENABLED)
 		// Opening the system file manager is not supported on the Android and web editors.
 		explore_button->hide();
-#endif
+#else // !defined(ANDROID_ENABLED) && !defined(WEB_ENABLED)
+		explore_button->set_button_icon(get_editor_theme_icon(SNAME("Load")));
+		explore_button->set_tooltip_text(OS::get_singleton()->get_tr_file_manager_open());
```
Comment (adamscott) [inline editor/project_manager/project_list.cpp]: Used "open" here as it seems to open a directory.

**Review by AdriaandeJongh — CHANGES_REQUESTED** [review]

File: editor/project_manager/project_list.cpp [hunk 8]
```diff
@@ -1197,8 +1197,8 @@ void ProjectList::_open_menu(const Vector2 &p_at, Control *p_hb) {
 		project_context_menu->add_item(TTRC("Run Project"), MENU_RUN);
 		project_context_menu->add_separator();
 #if !defined(ANDROID_ENABLED) && !defined(WEB_ENABLED)
-		project_context_menu->add_item(TTRC("Show in File Manager"), MENU_SHOW_IN_FILE_MANAGER);
-#endif
+		project_context_menu->add_item(OS::get_singleton()->get_tr_file_manager_open(), MENU_SHOW_IN_FILE_MANAGER);
```
Comment (adamscott) [inline editor/project_manager/project_list.cpp]: Used "open" here as it seems to open a directory.

File: editor/editor_node.cpp (hunk 5 above)
Comment (adamscott) [inline editor/editor_node.cpp]: Used "open" here as it seems to open a directory.

File: modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp (hunk 6 above)
Comment (adamscott) [inline modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp]: Used "open" here as it seems to open a directory.

File: editor/project_manager/project_list.cpp (hunk 4 above)
Comment (AdriaandeJongh) [reply editor/project_manager/project_list.cpp]: ah yeah open is better suited

File: editor/editor_node.cpp (hunk 5 above)
Comment (AdriaandeJongh) [reply editor/editor_node.cpp]: ah lol, open is better suited here too. nvm.

**Review by AdriaandeJongh — APPROVED** [review]
Didn't look at the code, but looks good to me.

File: modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp (hunk 6 above)
Comment (adamscott) [reply modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp]: See https://github.com/godotengine/godot/pull/92984#discussion_r2841488874

File: editor/editor_node.cpp (hunk 5 above)
Comment (adamscott) [reply editor/editor_node.cpp]: See https://github.com/godotengine/godot/pull/92984#discussion_r2841487469

File: core/os/os.h [hunk 9]
```diff
@@ -392,6 +398,20 @@ class OS {
...
+		switch (p_platform_string) {
+			case PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN: {
+				return ETR("Open in File Manager");
+			} break;
+			case PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW: {
+				return ETR("Show in File Manager");
+			} break;
+			default: {
+				ERR_FAIL_V_MSG("", "Couldn't find a string for platform string.");
+			} break;
```
Comment (Calinou) [inline core/os/os.h]: You can remove the braces for single-line `case` statements (and remove the `break` for statements that `return`). We generally do this elsewhere in the codebase.

File: drivers/apple_embedded/os_apple_embedded.h [hunk 10]
```diff
@@ -144,6 +144,20 @@ class OS_AppleEmbedded : public OS_Unix {
...
+		switch (p_platform_string) {
+			case OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN: {
+				return ETR("Open in Files");
+			} break;
+			case OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW: {
+				return ETR("Show in Files");
+			} break;
+			default: {
+				return OS::get_platform_string(p_platform_string);
+			} break;
```
Comment (Calinou) [inline drivers/apple_embedded/os_apple_embedded.h]: Same as above.

File: platform/macos/os_macos.h [hunk 11]
```diff
@@ -167,6 +167,20 @@ class OS_MacOS : public OS_Unix {
...
+		switch (p_platform_string) {
+			case OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN: {
+				return ETR("Open in Finder");
+			} break;
+			case OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW: {
+				return ETR("Show in Finder");
+			} break;
+			default: {
+				return OS::get_platform_string(p_platform_string);
+			} break;
```
Comment (Calinou) [inline platform/macos/os_macos.h]: Same as above.

File: platform/windows/os_windows.h [hunk 12]
```diff
@@ -264,6 +264,20 @@ class OS_Windows : public OS {
...
+		switch (p_platform_string) {
+			case OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN: {
+				return ETR("Open in File Explorer");
+			} break;
+			case OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW: {
+				return ETR("Show in File Explorer");
+			} break;
+			default: {
+				return OS::get_platform_string(p_platform_string);
+			} break;
```
Comment (Calinou) [inline platform/windows/os_windows.h]: Same as above.

**Review by Calinou — COMMENTED** [review]
I get a compilation error locally:

```
[ 56%] Compiling editor/settings/.scu/scu_editor_settings.gen.cpp ...
In file included from editor/debugger/.scu/scu_editor_debugger_1.gen.cpp:6:
./editor/debugger/script_editor_debugger.cpp: In constructor 'ScriptEditorDebugger::ScriptEditorDebugger()':
./editor/debugger/script_editor_debugger.cpp:2440:91: error: 'OS::PlatformTranslation' has not been declared
 2440 |                 vmem_item_menu->add_item(atr(OS::get_singleton()->get_platform_string(OS::PlatformTranslation::PLATFORM_TRANSLATION_FILE_MANAGER_SHOW)), VMEM_MENU_SHOW_IN_EXPLORER);
      |                                                                                           ^~~~~~~~~~~~~~~~~~~
scons: *** [bin/obj/editor/debugger/.scu/scu_editor_debugger_1.gen.linuxbsd.editor.x86_64.o] Error 1
In file included from editor/.scu/scu_editor.gen.cpp:5:
./editor/editor_node.cpp: In constructor 'EditorNode::EditorNode()':
./editor/editor_node.cpp:9165:108: error: 'OS::PlatformTranslation' has not been declared
 9165 |         remove_android_build_template->set_ok_button_text(atr(OS::get_singleton()->get_platform_string(OS::PlatformTranslation::PLATFORM_TRANSLATION_FILE_MANAGER_OPEN)));
      |                                                                                                            ^~~~~~~~~~~~~~~~~~~
scons: *** [bin/obj/editor/.scu/scu_editor.gen.linuxbsd.editor.x86_64.o] Error 1
scons: building terminated because of errors.
```

File: core/os/os.h [hunk 13]
```diff
@@ -31,6 +31,7 @@
 #pragma once
 
 #include "core/config/engine.h"
+#include "core/error/error_macros.h"
```
Comment (adamscott) [inline core/os/os.h]: Got to remove this before @AThousandShips sees this.

**Review by Calinou — APPROVED** [review]
Tested locally on Linux, it works as expected. Code looks good to me.

I agree it's better to use OS-native terminology for this. This is especially the case since this functionality is used not just in the editor, but in export templates too (in the FileDialog class).

File: editor/debugger/script_editor_debugger.cpp [hunk 14]
```diff
@@ -2437,7 +2437,7 @@ Instead, use the monitors tab to obtain more precise VRAM usage.
 		vmem_item_menu = memnew(PopupMenu);
 		vmem_item_menu->connect(SceneStringName(id_pressed), callable_mp(this, &ScriptEditorDebugger::_vmem_item_menu_id_pressed));
 		vmem_item_menu->add_item(TTRC("Show in FileSystem"), VMEM_MENU_SHOW_IN_FILESYSTEM);
-		vmem_item_menu->add_item(TTRC("Show in File Manager"), VMEM_MENU_SHOW_IN_EXPLORER);
+		vmem_item_menu->add_item(atr(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW)), VMEM_MENU_SHOW_IN_EXPLORER);
```
Comment (bruvzg) [inline editor/debugger/script_editor_debugger.cpp]:
```suggestion
		vmem_item_menu->add_item(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW), VMEM_MENU_SHOW_IN_EXPLORER);
```

Controls already do translation internally, so using `atr` is not needed wand will break if translation is changed in runtime. `TTRC` is used only to collect string for POT update, and there's already `ETR` for this in OS.

File: editor/docks/filesystem_dock.cpp [hunk 15]
```diff
@@ -3650,7 +3650,7 @@ void FileSystemDock::_file_and_folders_fill_popup(PopupMenu *p_popup, const Vect
 		}
 
 		p_popup->add_icon_shortcut(get_editor_theme_icon(SNAME("Filesystem")), ED_GET_SHORTCUT("filesystem_dock/show_in_explorer"), FILE_MENU_SHOW_IN_EXPLORER);
-		p_popup->set_item_text(p_popup->get_item_index(FILE_MENU_SHOW_IN_EXPLORER), is_directory ? TTRC("Open in File Manager") : TTRC("Show in File Manager"));
+		p_popup->set_item_text(p_popup->get_item_index(FILE_MENU_SHOW_IN_EXPLORER), atr(is_directory ? OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN) : OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW)));
```
Comment (bruvzg) [inline editor/docks/filesystem_dock.cpp]:
```suggestion
		p_popup->set_item_text(p_popup->get_item_index(FILE_MENU_SHOW_IN_EXPLORER), is_directory ? OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN) : OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW));
```

File: editor/gui/editor_quick_open_dialog.cpp [hunk 16]
```diff
@@ -360,7 +360,7 @@ QuickOpenResultContainer::QuickOpenResultContainer() {
 
 			file_context_menu = memnew(PopupMenu);
 			file_context_menu->add_item(TTR("Show in FileSystem"), FILE_SHOW_IN_FILESYSTEM);
-			file_context_menu->add_item(TTR("Show in File Manager"), FILE_SHOW_IN_FILE_MANAGER);
+			file_context_menu->add_item(atr(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW)), FILE_SHOW_IN_FILE_MANAGER);
```
Comment (bruvzg) [inline editor/gui/editor_quick_open_dialog.cpp]:
```suggestion
			file_context_menu->add_item(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW), FILE_SHOW_IN_FILE_MANAGER);
```

File: editor/project_manager/project_list.cpp [hunk 17]
```diff
@@ -326,13 +326,13 @@ void ProjectListItemControl::set_is_missing(bool p_missing) {
...
-		explore_button->set_button_icon(get_editor_theme_icon(SNAME("Load")));
-		explore_button->set_tooltip_text(TTRC("Show in File Manager"));
-#else
+#if defined(ANDROID_ENABLED) || defined(WEB_ENABLED)
 		// Opening the system file manager is not supported on the Android and web editors.
 		explore_button->hide();
-#endif
+#else // !defined(ANDROID_ENABLED) && !defined(WEB_ENABLED)
+		explore_button->set_button_icon(get_editor_theme_icon(SNAME("Load")));
+		explore_button->set_tooltip_text(atr(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN)));
```
Comment (bruvzg) [inline editor/project_manager/project_list.cpp]:
```suggestion
		explore_button->set_tooltip_text(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN));
```

File: editor/project_manager/project_list.cpp [hunk 18]
```diff
@@ -1197,8 +1197,8 @@ void ProjectList::_open_menu(const Vector2 &p_at, Control *p_hb) {
 		project_context_menu->add_item(TTRC("Run Project"), MENU_RUN);
 		project_context_menu->add_separator();
 #if !defined(ANDROID_ENABLED) && !defined(WEB_ENABLED)
-		project_context_menu->add_item(TTRC("Show in File Manager"), MENU_SHOW_IN_FILE_MANAGER);
-#endif
+		project_context_menu->add_item(atr(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN)), MENU_SHOW_IN_FILE_MANAGER);
```
Comment (bruvzg) [inline editor/project_manager/project_list.cpp]:
```suggestion
		project_context_menu->add_item(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN), MENU_SHOW_IN_FILE_MANAGER);
```

File: editor/editor_node.cpp [hunk 19]
```diff
@@ -9162,7 +9162,7 @@ EditorNode::EditorNode() {
 	}
 
 	remove_android_build_template = memnew(ConfirmationDialog);
-	remove_android_build_template->set_ok_button_text(TTR("Show in File Manager"));
+	remove_android_build_template->set_ok_button_text(atr(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN)));
```
Comment (bruvzg) [inline editor/editor_node.cpp]:
```suggestion
	remove_android_build_template->set_ok_button_text(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN));
```

File: modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp [hunk 20]
```diff
@@ -270,7 +270,7 @@ void ObjectDBProfilerPanel::_snapshot_rmb(const Vector2 &p_pos, MouseButton p_bu
 	rmb_menu->clear(false);
 
 	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Rename")), TTRC("Rename"), OdbProfilerMenuOptions::ODB_MENU_RENAME);
-	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Folder")), TTRC("Show in File Manager"), OdbProfilerMenuOptions::ODB_MENU_SHOW_IN_FOLDER);
+	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Folder")), atr(OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN)), OdbProfilerMenuOptions::ODB_MENU_SHOW_IN_FOLDER);
```
Comment (bruvzg) [inline modules/objectdb_profiler/editor/objectdb_profiler_panel.cpp]:
```suggestion
	rmb_menu->add_icon_item(get_editor_theme_icon(SNAME("Folder")), OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN), OdbProfilerMenuOptions::ODB_MENU_SHOW_IN_FOLDER);
```

File: scene/gui/file_dialog.cpp [hunk 21]
```diff
@@ -799,7 +799,7 @@ void FileDialog::_popup_menu(const Vector2 &p_pos, int p_for_item) {
 		meta = file_list->get_item_metadata(p_for_item);
 	}
 
-	item_menu->add_item((p_for_item == -1 || meta["dir"]) ? ETR("Open in File Manager") : ETR("Show in File Manager"), ITEM_MENU_SHOW_IN_EXPLORER);
+	item_menu->add_item(atr((p_for_item == -1 || meta["dir"]) ? OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN) : OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW)), ITEM_MENU_SHOW_IN_EXPLORER);
```
Comment (bruvzg) [inline scene/gui/file_dialog.cpp]:
```suggestion
	item_menu->add_item((p_for_item == -1 || meta["dir"]) ? OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN) : OS::get_singleton()->get_platform_string(OS::PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW), ITEM_MENU_SHOW_IN_EXPLORER);
```

**Review by bruvzg — APPROVED** [review]
Code looks good, and OS specific names is what most people expect.

File: core/os/os.h [hunk 22]
```diff
@@ -392,6 +397,17 @@ class OS {
...
 	virtual void load_platform_gdextensions() const {}
 
+	virtual String get_platform_string(PlatformString p_platform_string) const {
+		switch (p_platform_string) {
+			case PlatformString::PLATFORM_STRING_FILE_MANAGER_OPEN:
+				return ETR("Open in File Manager");
+			case PlatformString::PLATFORM_STRING_FILE_MANAGER_SHOW:
+				return ETR("Show in File Manager");
+			default:
+				ERR_FAIL_V_MSG("", "Couldn't find a string for platform string.");
```
Comment (KoBeWi) [inline core/os/os.h]:
```suggestion
				ERR_FAIL_V_MSG("", vformat("Couldn't find a string for platform string: %d.", p_platform_string));
```

File: editor/docks/filesystem_dock.cpp (hunk 15 above)
Comment (KoBeWi) [reply editor/docks/filesystem_dock.cpp]: Also

```suggestion
		p_popup->set_item_text(p_popup->get_item_index(FILE_MENU_SHOW_IN_EXPLORER), is_directory ? OS::get_singleton()->get_platform_string(OS::PLATFORM_STRING_FILE_MANAGER_OPEN) : OS::get_singleton()->get_platform_string(OS::PLATFORM_STRING_FILE_MANAGER_SHOW));
```

Comment (adamscott) [reply editor/docks/filesystem_dock.cpp]: Replaced all the `OS::PlatformString::` for `OS::`.
