### PR TITLE
[Export] Use project settings overrides with the target preset features instead of current platform features.

### LINKED ISSUE #71506: Localized `application/config/name_<lang>` project setting doesn't respect platform-specific feature overrides for the _target_ platform
### Godot version

3.5.1

### System information

macOS 

### Issue description

override the name in project settings for different platforms doesn't work.

### Steps to reproduce

set the project name 
application/config/name to game

set
application/config/name_zh to game_zh 

set 
application/config/name_zh.Android to game_zh_android

the app name run on Android device is game_zh not game_zh_android

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/71506

### CODE REVIEW

File: editor/export/editor_export_platform.cpp [hunk 1]
```diff
@@ -2466,6 +2468,35 @@ Array EditorExportPlatform::get_current_presets() const {
 	return ret;
 }
 
+Variant EditorExportPlatform::get_project_setting(const Ref<EditorExportPreset> &p_preset, const StringName &p_name) {
```
Comment (dsnopek) [inline editor/export/editor_export_platform.cpp:2471]: This method would really useful to have available to GDExtension, for use in `EditorExportPlugin`s. More specifically, in the [godot_openxr_vendor](https://github.com/GodotVR/godot_openxr_vendors) extension, it would allow us to eliminate some export settings for things we can know from project settings, but it's only safe to check with the feature tags for that specific export preset.

So, I think this should be exposed, either right on this class, or as a part of `EditorExportPreset`, or even a convenience method on `EditorExportPlugin` - whatever would make the nicest API

File: core/config/project_settings.cpp [hunk 2]
```diff
@@ -359,6 +359,29 @@ bool ProjectSettings::_get(const StringName &p_name, Variant &r_ret) const {
 	return true;
 }
 
+Variant ProjectSettings::get_setting_with_override_with_custom_features(const StringName &p_name, const Vector<String> &p_features) const {
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply core/config/project_settings.cpp]: Renamed to `get_setting_with_override_and_custom_features`.

File: editor/export/editor_export_platform.cpp (hunk 1 above)
Comment (bruvzg) [reply editor/export/editor_export_platform.cpp:2471]: Exposed it as `EditorExportPreset::get_project_setting`.

**Review by dsnopek — APPROVED** [review]
Thanks! This is really great :-)

I just tested it with a modified version of the 'godot_openxr_vendors' plugin, and it worked as expected! I was able to have a Project Setting disabled (without any feature tag), but enable the setting with a feature tag used by an export preset, and see an `EditorExportPlugin` respond correctly when exporting that preset

Skimming the code, it looks good to me!

(But now this needs a rebase for some conflicts)

**Review by akien-mga — APPROVED** [review]
Looks good to me from a cursory review (never found time to make the in-depth review I wanted to, but @dsnopek did a good API review already).

**Comment by Repiteo** [comment]
Thanks!
