### PR TITLE
Viewport cancels existing tooltip when window looses focus

### LINKED ISSUE #68197: Editor tooltips stay on game screen when launching maximized/large game window (DisplayServer regression)
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10, 970 GTX

### Issue description

It's not the end of the world but it is very annoying. I like to be maximized when testing but now I have to be conscious of where the mouse pointer is whenever I press F5.

Untitled

When this happens, the window needs to be switched or closed in order to clear it.

It seems if you press F5 when the tooltip is already showing, then it is cleared properly. But if you press F5 right before the tooltip shows, then it stays on screen.

### Steps to reproduce

1. Set `Project Settings -> Display -> Window -> Mode -> Maximized`, or Viewport Width/Height to cover most of the screen
2. Move mouse over something in the inspector that will display an editor tooltip
3. Before the tooltip appears, press F5
4. Tooltip now stays on game screen permanently until you change windows or close it

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Grimmr**
this is to fix #68197 

This should be less likely to cause regressions then the last one.

when NOTIFICATION_WM_WINDOW_FOCUS_OUT is received by a viewport it will now call _gui_cancel_tooltip() to avoid it hanging around after the mouse events stop coming in.

### CODE REVIEW

**Comment by Sauermann** [comment]
I have tested this change and it closes the tool-tips as it should and I found no obvious regressions.

Since this PR solves the mentioned issue, you should link it to this PR, by including the string "fix #68197" (or a similar one) in your issue-description, like in the [Github-Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) mentioned.

However I found, that the problem is larger than in the issue-description.
Not only tool-tips stay open when changing to a different window, but also other popups.

In the following video (Linux X11 Xfce) I
1) open in the editor the color-picker,
2) use Alt-Tab to switch to a different Window.

After _2._ the color-picker is visible above the Window, that I switched to, even though it should probably not be.

https://user-images.githubusercontent.com/6299227/200845883-b00c778a-273e-4e97-b6dc-7b0143eb7faf.mp4

This also happens for other Popups like the Editor-menu.

A solution, that solves this general problem for popups, should consider the change of this PR and investigate, if there is a redundancy with this specialized solution for tool-tips.

**Comment by Grimmr** [comment]
@Sauermann Is there an open issue for the behaviour you mentioned I could look into it as I'm already in this part of the codebase

**Comment by Sauermann** [comment]
I did a quick search but didn't find any open issue about that.

**Comment by Grimmr** [comment]
I've had a look at the colour picker on colour rect specifically and I might have to admit that this is beyond my understanding of the codebase. It doesn't seem to be modeled as a PopupMenu (or a Popup) or if it is it doesn't get closed by _close_pressed() under normal usage. which seems to be how those classes handle closing in most cases. 

I'm going to keep looking for a day or two more, and try finding it in the node tree at runtime, but short of a lucky break I'll probably mark this PR as ready and a decision can be made about bringing it back before we find a way to solve the larger issue of generic popups hanging around after focus is lost.

**Comment by Grimmr** [comment]
I've spent slightly more then the two days I planned looking into it but I'm not making much process. I'm going to mark this as ready for review

**Comment by Sauermann** [comment]
While this PR solves the linked issue, it could be, that in order to solver the underlying problem #68856, adjustments to `DisplayServer` become necessary.

**Comment by Sauermann** [comment]
The PR solves the mentioned problem and I can't see any obvious regressions.

**Review by Sauermann — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -491,6 +491,8 @@ void Viewport::_notification(int p_what) {
 		} break;
 
 		case NOTIFICATION_WM_WINDOW_FOCUS_OUT: {
+			_gui_cancel_tooltip();
+
```
Comment (akien-mga) [inline scene/main/viewport.cpp:495]: There seems to be trailing whitespace on this line as our formatting checks failed.

Please amend the commit with `git commit --amend` to remove whitespace from this line, and update the PR with `git push --force`.

Comment (Grimmr) [reply scene/main/viewport.cpp:495]: Applied (I hope)

Comment (Grimmr) [reply scene/main/viewport.cpp:495]: I did not do, I made a small error. please wait

Comment (Grimmr) [reply scene/main/viewport.cpp]: error resolved it should be okay now, sorry about that

File: scene/main/viewport.cpp [hunk 2]
```diff
@@ -491,6 +491,7 @@ void Viewport::_notification(int p_what) {
 		} break;
 
 		case NOTIFICATION_WM_WINDOW_FOCUS_OUT: {
+			_gui_cancel_tooltip();
```
Comment (akien-mga) [inline scene/main/viewport.cpp:494]: You now have trailing whitespace on this line (two tabs at the end of the line):

image

You can set up clang-format locally in your IDE, or via our pre-commit hooks https://github.com/godotengine/godot/tree/master/misc/hooks, to make sure that files comply with style requirements.

Or configure your IDE to strip trailing whitespace, which would cover at least this type of error.

Comment (Grimmr) [reply scene/main/viewport.cpp]: Sorry for that. I've installed the hooks you suggested and the most recent update has made it through clang format on my end. 

on a slight side note the clang format script doesn't seem to complain about the NL you originally mentioned but it does automatically strip the WS.

Hope everything is good this time.

Comment (akien-mga) [reply scene/main/viewport.cpp]: The newline wasn't a problem, the problem is that there was whitespace on the newline :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
