### PR TITLE
Fix editor crash when converting sprite to 2D mesh

### LINKED ISSUE #26527: Convert Sprite to 2dMesh -> Crash to desk
**Godot version:**
- 3.1 Beta 10 
- _haven't tried other Beta builds nore 3.0.x -> was the first time for me to use the convert function_

**OS/device including version:**
- Windows 10
- RTX 2080
- I7 8700

**Issue description:**
- If "region" function for a Sprite (2D) is active and you click convert to 2D Mesh -> crash to desk.

**Steps to reproduce:**
- create new project
- add Sprite with Godot icon
- enable region and select a part of the icon 
- click "convert to 2D Mesh"

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #26527 - note, Its simple hotfix to avoid sudden editor crash, its not a solution for converting sprite with region to mesh..

### CODE REVIEW

File: editor/plugins/sprite_editor_plugin.cpp [hunk 1]
```diff
@@ -91,6 +91,8 @@ Vector<Vector2> expand(const Vector<Vector2> &points, const Rect2i &rect, float
 
 	Vector<Vector2> outPoints;
 	ClipperLib::PolyNode *p2 = out.GetFirst();
+	if (p2 == NULL) // avoid editor crash
```
Comment (akien-mga) [inline editor/plugins/sprite_editor_plugin.cpp]: Above for `p2` there is:
```
ERR_FAIL_COND_V(!p, points);
```
So I guess it might be better to return `points` when aborting? Don't know if it should be made an `ERR_FAIL` on the other hand. If yes, that means there's still a bug to fix (what makes it fail).

Comment (akien-mga) [reply editor/plugins/sprite_editor_plugin.cpp]: Well given your OP comment, I guess it should be an `ERR_FAIL_COND_V` indeed, since it only prevents the crash, doesn't fix the actual bug.

Comment (Chaosus) [reply editor/plugins/sprite_editor_plugin.cpp]: Hmm. however its possible to actually use Sprite with Region but not through this sub-editor

Comment (Chaosus) [reply editor/plugins/sprite_editor_plugin.cpp]: Yeah, fixed it as you said

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Xrayez** [comment]
Linking #23559 if similar change is needed in case new Clipper is integrated.
