### PR TITLE
Particle internal refactor and additions for more artistic control

### LINKED ISSUE #82837: Deterministic chain of random values in particle shader can be broken when turbulence is used
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 SUPER (NVIDIA; 31.0.15.3130) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

The error is basically known: A random value is generated within an IF-THEN-block. As soon as the condition for IF changes, all subsequent random values change once.
This concerns the following location (turbulence):

```
if (!COLLIDED) {
	float vel_mag = length(VELOCITY);
	float vel_infl = clamp(mix(turbulence_influence_min, turbulence_influence_max, rand_from_seed(alt_seed)) * turbulence_influence, 0.0, 1.0);
	VELOCITY = mix(VELOCITY, normalize(noise_direction) * vel_mag * (1.0 + (1.0 - vel_infl) * 0.2), vel_infl);
}
```
I think the right thing to do would be to pull the random value before IF:
```
float turbulence_influence_rand = rand_from_seed(alt_seed);
if (!COLLIDED) {
	float vel_mag = length(VELOCITY);
	float vel_infl = clamp(mix(turbulence_influence_min, turbulence_influence_max, turbulence_influence_rand) * turbulence_influence, 0.0, 1.0);
	VELOCITY = mix(VELOCITY, normalize(noise_direction) * vel_mag * (1.0 + (1.0 - vel_infl) * 0.2), vel_infl);
}

```

### Steps to reproduce

I found the error directly in the source code.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by QbieShay**
# DO NOT TEST ON IMPORTANT PROJECTS! MAKE A COPY!

## How to test:
1. Login into github
2. Click the "checks" tab of this PR
3. On the right there's an "artifacts" button.
4. Download the appropriate build for your plaform

image

## What to test
1. Compatibility with existing projects! This should not break compatibility and if it does, if the particles look different, it's a bug.
2. Features: are the new features functioning properly?

**NOTE: this is GPUParticles only**

-------------

Description:

This is a gigaenormous rework to particles because adding code to them had become impossibly difficult.
Now parameters are stored in lovely neat structs and subdivided in display, dynamics, accelerations.
This closes probably 90% of the proposals and issues about particles i opened.

IDEALLY: this is 100% compatible with the existing one. Practically there may be some bugs and regressions introduced during the rewrite.

This is an attempt at implementing https://godotshaders.com/shader/particle-process-v2/ and keeping compat.

## How to conduct a test
Ideally, people will try to make something a little more complex than a single particle system.
I'm hoping something of the complexity of a crit hit effect (so I'm imagining 4-5 particle systems..?)
Sword slash, fireball, go for it!

Feel free to use my render material for testing it out (MPL license, means if you change a file you have to open source the changes to that specific file, but it doesn't spread like GPL)
[vfx_kit.zip](https://github.com/godotengine/godot/files/12063036/vfx_kit.zip)

### GPUParticles:
- add an `interp_to_end` parameter to force particles to run to the end of their lifetime fast. This can be animated in the animation player, or tweened to make a complex VFX scene disappeared in a desired time interval. cool isn't it?
- fixed billboard mode not taking into account angle stored in CUSTOM.x

### ParticleProcess:
- Shader entirely rearranged and reorganized. Data is split in different structs and there's function to generate the initial state that can be called from process(), so that there's no discrepancies (hopefully ....?)
- Parameters entirely rearranged in submenus.  I know this will be contentious but i arranged them based on my daily usage of said particles. The editor can remember unfolded submenus, since tweaking is like 80% of particle work, this shouldnt really be too much of an issue, i hope. It will be more prominent, of course, if the testing usage is "i make a lot of different particle systems"
**New features **
Under spawn section, inherit emitter velocity. Currently nonfucntional, will figure out how to make it functional later.

A completely new category of velocity: animated velocity. This is velocity entirely driven by curves. **it will not be subject to damping**
image

Available velocities:
- angular (rotates the particle if billboard, same as before)
- radial: velocity towards, or away, from a point
- orbit:  orbit velocity around XYZ axes. To use in compatibility mode, use flag enable z. To use in new mode, use CurveXYZ. Curve should be in degrees.
- Velocity limit: a curve that defines the maximum velocity magnitude (combined with accelerations) that a particle can have along its lifetime. functions only when assigned.

Accelerations are the same as before. gravity is under accelerations, together with attractor interaction.

Display parameters:
This is where color, scale and animation properties live.
image

Color got two new optional curves, alpha curve and emission curve (emission as in brightness. perhaps brightness would be a better term). emission just multiplies the color so it needs to be read in the render shader as such. Feel free to use the material provided above. a single color ramp will work as before.

image

Scale over velocity!! This is really cool to add some sensation of smear for motion by scaling on the Y axis for example with a XYZ curve. The two min/max parameters indicate the range in which velocity is remapped onto the curve (so when do i make my scale biggest? when max velocity is 10, or 200? that's what the parameters are for)

## Addresses
https://github.com/godotengine/godot-proposals/issues/7082 - interp to end will make trails much easier: it offers a lifetime control.
https://github.com/godotengine/godot-proposals/issues/6779 - improves portability of particle systems and makes technology for VFX color palettes actually possible
https://github.com/godotengine/godot-proposals/issues/6657 - slightly different, but achievest almost all of the same results
https://github.com/godotengine/godot-proposals/issues/6573 - offers it as a property instead of a function, functions can be implemented on top later.
https://github.com/godotengine/godot-proposals/issues/5044 - emission transform built-ins
https://github.com/godotengine/godot/issues/79063 - uses custom.x rotation correctly

_Bugsquad edit: Fixes: https://github.com/godotengine/godot/issues/82837_

## Who whants this

Edit: look at the reaction. Aww. Thanks y'all <3

I know that discussions on proposals didn't really get a huge amount of traction on Github, but i brought up this work in multiple VFX spaces, incorporated feedback from various professionals, and researched how alternatives (Unity, Unreal) are built.
This has been months of research that ultimately condensed into this work.
I believe that what testers will be able to achieve with this PR will speak for itself.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
I wonder if this is a good opportunity to ask for `trail_size/color_modifier` to make a comeback, those two were quite useful for making simple 2D particles that gave the illusion of depth.

**Comment by QbieShay** [comment]
Huh, I don't know exactly how that worked, but I can tentatively take a look, no promises tho.

**Comment by YeldhamDev** [comment]
@QbieShay Thanks! They were removed in this PR: #41810

I've yet to successfully replicate the old behavior with the new particle sub-emitters.

**Comment by QbieShay** [comment]
What's missing exactly?

**Comment by YeldhamDev** [comment]
As I said before, a simple way to give the illusion of depth in 2D. Here's a section of my game for example:

| 3.* | 4.* |
|-|-|
|Screenshot_20230716_144059 | Screenshot_20230716_143826 |

There may be a way to do this currently that I missed, but for the life of me I couldn't find it.

**Comment by QbieShay** [comment]
The 4.x screenshot is done with a subemitter or with trails?

File: scene/resources/particle_process_material.cpp [hunk 1]
```diff
@@ -1712,60 +1941,82 @@ void ParticleProcessMaterial::_bind_methods() {
...
 	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "spread", PROPERTY_HINT_RANGE, "0,180,0.01"), "set_spread", "get_spread");
 	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "flatness", PROPERTY_HINT_RANGE, "0,1,0.01"), "set_flatness", "get_flatness");
-	ADD_GROUP("Gravity", "");
-	ADD_PROPERTY(PropertyInfo(Variant::VECTOR3, "gravity"), "set_gravity", "get_gravity");
-	ADD_GROUP("Initial Velocity", "initial_");
 	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "initial_velocity_min", PROPERTY_HINT_RANGE, "0,1000,0.01,or_less,or_greater"), "set_param_min", "get_param_min", PARAM_INITIAL_LINEAR_VELOCITY);
 	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "initial_velocity_max", PROPERTY_HINT_RANGE, "0,1000,0.01,or_less,or_greater"), "set_param_max", "get_param_max", PARAM_INITIAL_LINEAR_VELOCITY);
-	ADD_GROUP("Angular Velocity", "angular_");
+	ADD_GROUP("Animated Velocity", "");
+	ADD_SUBGROUP("Velocity limit", "");
```
Comment (Calinou) [inline scene/resources/particle_process_material.cpp:1956]: Use Title Case for group names:

```suggestion
	ADD_SUBGROUP("Velocity Limit", "");
```

File: scene/resources/particle_process_material.cpp [hunk 2]
```diff
@@ -1712,60 +1941,82 @@ void ParticleProcessMaterial::_bind_methods() {
...
-	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "orbit_velocity_curve", PROPERTY_HINT_RESOURCE_TYPE, "CurveTexture"), "set_param_texture", "get_param_texture", PARAM_ORBIT_VELOCITY);
-	ADD_GROUP("Linear Accel", "linear_");
+	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "orbit_velocity_curve", PROPERTY_HINT_RESOURCE_TYPE, "CurveTexture, CurveXYZTexture"), "set_param_texture", "get_param_texture", PARAM_ORBIT_VELOCITY);
+	ADD_SUBGROUP("Radial Velocity", "radial_");
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "radial_velocity_min", PROPERTY_HINT_RANGE, "-1000,1000,0.01,or_less,or_greater"), "set_param_min", "get_param_min", PARAM_RADIAL_VELOCITY);
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "radial_velocity_max", PROPERTY_HINT_RANGE, "-1000,1000,0.01,or_less,or_greater"), "set_param_max", "get_param_max", PARAM_RADIAL_VELOCITY);
+	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "radial_velocity_curve", PROPERTY_HINT_RESOURCE_TYPE, "CurveTexture"), "set_param_texture", "get_param_texture", PARAM_RADIAL_VELOCITY);
+	ADD_SUBGROUP("Velocity limit", "");
```
Comment (Calinou) [inline scene/resources/particle_process_material.cpp:1969]:
```suggestion
	ADD_SUBGROUP("Velocity Limit", "");
```

File: scene/resources/particle_process_material.cpp [hunk 3]
```diff
@@ -1712,60 +1941,82 @@ void ParticleProcessMaterial::_bind_methods() {
...
+	ADD_SUBGROUP("Attractor Interaction", "attractor_interaction_");
+	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "attractor_interaction_enabled"), "set_attractor_interaction_enabled", "is_attractor_interaction_enabled");
+
+	ADD_GROUP("Display", "");
+	ADD_SUBGROUP("Scale", "");
 	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "scale_min", PROPERTY_HINT_RANGE, "0,1000,0.01,or_greater"), "set_param_min", "get_param_min", PARAM_SCALE);
 	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "scale_max", PROPERTY_HINT_RANGE, "0,1000,0.01,or_greater"), "set_param_max", "get_param_max", PARAM_SCALE);
 	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "scale_curve", PROPERTY_HINT_RESOURCE_TYPE, "CurveTexture,CurveXYZTexture"), "set_param_texture", "get_param_texture", PARAM_SCALE);
-	ADD_GROUP("Color", "");
+	ADD_SUBGROUP("Scale over velocity", "");
```
Comment (Calinou) [inline scene/resources/particle_process_material.cpp:1998]:
```suggestion
	ADD_SUBGROUP("Scale Over Velocity", "");
```

File: scene/resources/particle_process_material.cpp [hunk 4]
```diff
@@ -1712,60 +1941,82 @@ void ParticleProcessMaterial::_bind_methods() {
...
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "scale_over_velocity_min", PROPERTY_HINT_RANGE, "0,1000,0.01,or_greater"), "set_param_min", "get_param_min", PARAM_SCALE_OVER_VELOCITY);
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "scale_over_velocity_max", PROPERTY_HINT_RANGE, "0,1000,0.01,or_greater"), "set_param_max", "get_param_max", PARAM_SCALE_OVER_VELOCITY);
+	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "scale_over_velocity_curve", PROPERTY_HINT_RESOURCE_TYPE, "CurveTexture,CurveXYZTexture"), "set_param_texture", "get_param_texture", PARAM_SCALE_OVER_VELOCITY);
+
+	ADD_SUBGROUP("Color curves", "");
```
Comment (Calinou) [inline scene/resources/particle_process_material.cpp:2003]:
```suggestion
	ADD_SUBGROUP("Color Curves", "");
```

**Comment by Calinou** [comment]
I've tried to use a scale curve with this PR, but I get Vulkan pipeline error spam after creating a CurveXYZTexture (this also occurs with CurveTexture), even after saving and reloading the scene.

**Testing project:** [test_pr_79527.zip](https://github.com/godotengine/godot/files/12065313/test_pr_79527.zip)

**Comment by QbieShay** [comment]
Thank you @Calinou ! I should have addressed the issues you mentioned.

**Comment by RPicster** [comment]
Maybe I couldn't find it, but one thing that I would 110% would love to see and is extremely helpful is an **amount** parameter that is **dynamic**.

I know that there is amount, but changing that value restarts the particle.

One can easily work around this limitation by using a custom particle shader, but it would be very, very useful to have this as a default parameter. In the workaround, the `amount` acts as a "maximum amount of particles" and when spawning.

**Comment by Calinou** [comment]
> Maybe I couldn't find it, but one thing that I would 110% would love to see and is extremely helpful is an amount parameter that is dynamic.

I guess this can be done by adding a **Amount Ratio** property just below Amount that controls how many particles will be emitted as a ratio of the **Amount**. 1.0 means all particles are emitted at the usual rate, 0.5 means half of the particles are emitted, etc.

**Comment by QbieShay** [comment]
If someone has a code implementation, I can throw it in the PR, but if I have to come up with the implementation then it may be a separate PR, sorryyyy

**Comment by QbieShay** [comment]
Started heavy testing on my end, fixed already a bunch of errors.

This is the result of today's test:

https://github.com/godotengine/godot/assets/7917475/b042e1cf-040f-4605-a27b-02bb57cc0dc0

Tested:
- radial velocity outwards
- radial velocity curve
- velocity limiter
- scale over velocity
- emission curve
- color curve

Known issues:
- material key doesn't seem to update at all. I don't know why. I think i broke it when i tried to put it at 64 bits, every time a curve is added the scene needs to be closed and reopen. Help is welcome with this
- emission velocity inheritance isn't working as of yet.

**Comment by Calinou** [comment]
I've tested the latest version of this PR locally. Some comments

- Alpha Curve doesn't appear to have any effect, despite my material being transparent (Alpha) and having vertex color enabled. The color curve works in comparison.

image

- Emission Curve is actually a brightness multiplier. It works on unshaded materials (which don't display emission), and it does not brighten fully black materials. As a result, I suggest renaming it to **Energy Curve**, **Brightness Curve** or **Intensity Curve** (in order of preference).

- **Directional Velocity** and **Orbit Velocity** appear to do nothing, even with the various 2D-focused particle flags enabled. (I did try setting the **Velocity Pivot** to `(0, 1, 0)`` and ensuring the particle has some initial velocity that goes horizontally.)

- **Scale Over Velocity** appears to do nothing, even though the standard scale and scale curve properties work on my particles.

- **Turbulence** currently doesn't appear to have any effect.

- The **Bounce** particle collision property doesn't appear to work correctly, even if set to its maximum value of `1.0` and even if the particle falls from a high distance at high speed.

**Comment by QbieShay** [comment]
As for the emission curve suggestions, I think I'll go with Brightness just because intensity makes me think of saturation more than brightness, i think intensity is better. Thank you for your suggestion!!

**Comment by Calinou** [comment]
> If you close and reopen the scene, do any of those have any effect? may be the material key bugged and not the shader

I've tried that, but it didn't resolve the issue.

**Comment by QbieShay** [comment]
> I didn't – do these have a hard requirement on a curve? If so, the min/max properties should be hidden in those categories if there is no curve assigned.

Will do, thank you!

File: scene/resources/particle_process_material.cpp [hunk 5]
```diff
@@ -421,396 +502,491 @@ void ParticleProcessMaterial::_update_shader() {
...
+			if (tex_parameters[PARAM_ORBIT_VELOCITY].is_valid()) {
+				code += "   orbit_amount *= texture(orbit_velocity_curve, vec2(lifetime)).rgb;\n";
+			}
+			code += "	if (orbit_amount != 0.0) {\n";
+			code += "       vec3 org = EMISSION_TRANSFORM[3].xyz;\n";
+			code += "       vec3 diff = pos - org;\n";
+			code += "	     float ang = orbit_amount * delta * pi * 2.0;\n";
+			code += "	     mat2 rot = mat2(vec2(cos(ang), -sin(ang)), vec2(sin(ang), cos(ang)));\n";
+			code += "	     displacement.xy -= diff.xy;\n";
+			code += "        displacemen.xy += rot * diff.xy;\n";
```
Comment (Iniquitatis) [inline scene/resources/particle_process_material.cpp:677]:
```suggestion
			code += "        displacement.xy += rot * diff.xy;\n";
```

Comment (QbieShay) [reply scene/resources/particle_process_material.cpp:677]: Hey, is this a typo that prevents the shader from functioning? Otherwise I think it needs to change also in the variable definition and all other usages.

Comment (Iniquitatis) [reply scene/resources/particle_process_material.cpp:677]: Probably, but I'm not sure, as I've simply quickly skimmed through the changes on my phone. Yet, this variable is declared at line 662 and used at line 676 as `displacement`, so it'd be quite peculiar if this code would work properly while referring an undefined variable (`displacemen`).

Comment (QbieShay) [reply scene/resources/particle_process_material.cpp:677]: Oooh thank you! I'll double check

**Comment by webredraptors** [comment]
Out of curiosity does the PR address #61014?

**Comment by QbieShay** [comment]
I don't have explicitely tried to fix that, so no. But maybe it's a side effect of some of the code? though i doubt it.

File: scene/resources/particle_process_material.cpp (hunk 5 above)
Comment (QbieShay) [reply scene/resources/particle_process_material.cpp]: Thanks it was indeed a typo!

**Comment by NathanLovato** [comment]
@QbieShay  Our teammate @gtibo took some time to test the build you sent us, especially using submitters. Note that he isn't specialized in visual effects: he is a multimedia artist and designer with programming skills.

He made these fireworks with your build:

https://github.com/godotengine/godot/assets/12694995/0cee33e7-5e20-4b0b-98f3-c831ca59c213

You can find the Godot project files here: [godot_new_particles_system_test.zip](https://github.com/godotengine/godot/files/12239559/godot_new_particles_system_test.zip)

Here is his feedback:

- The changes to inspector categories are great.
- Parameters to make the behavior and visuals communicate (through the custom and color options) are nice, especially thanks to separated alpha curves.
- He wasn't sure how to use a number of newly added parameters, as he didn't have a precise application in mind. He usually works from an effect he can visualize mentally. He would let other artists who have the need for or experience with these test them.
- He faced one bug when the turbulence has a high influence, and you turn on interpolation: particles shake.

Here's a video of the problem:

https://github.com/godotengine/godot/assets/12694995/b46b9f16-4de2-440a-af05-73a017b9e148

If you need anything else, please let us know!

**Comment by QbieShay** [comment]
Thank you so much @NathanLovato and @gtibo !!! I love the look of those fireworks!

Regarding the jittering I'm not entirely sure what it is, btu it's been reported a couple of times already. It's something I'll try and take a look into, although it seems to already happen on master, so perhaps it will be in a separate PR.

**Comment by Calinou** [comment]
> amount

I went and did it: https://github.com/Calinou/godot/tree/qbe/particles-rework

I've tested it in both 2D and 3D:

https://github.com/godotengine/godot/assets/180032/4ee1b227-3c1c-4ae2-ac7c-525d4dbea06f

https://github.com/godotengine/godot/assets/180032/bf9e9c15-74b2-4ade-b8d2-d1cfb1b78092

**Comment by QbieShay** [comment]
No it does not address that proposal. I think it has to do with buffer allocation for particles and I didn't touch that part

**Comment by QbieShay** [comment]
I haven't implemented the amount ratio yet. Initially i thought to just pull your shader code, but I think there's a more intuitive way to do it directly in the emitter properties (since you'll want to diminish the ratio on one emitter but not another) so I'm trying to approach it in a similar way to how i did that interp to end property

**Comment by QbieShay** [comment]
Amount ratio is added, but instead of process material, it's on the node ^^ Thanks a lot @Calinou !

**Comment by Calinou** [comment]
> Amount ratio is added, but instead of process material, it's on the node ^^ Thanks a lot @Calinou !

I've tested the new implementation and it works great :slightly_smiling_face: 

I agree it makes sense to configure this in the node instead of the material, so that you can adjust it on a per-node basis without having to make the material unique. For instance, this allows you to you reuse a material for a car tire smoke particle for several cars.

**Review by AThousandShips — COMMENTED** [review]
There's also indentation issues across the shader code which harms readability

**Comment by QbieShay** [comment]
@AThousandShips thanks for your review!

When is the const in a function parameter allowed? There's a couple already in the header you pointed at, are those necessary for some other reason (for example vec3 need it explicitely), or just an oversight?

```

	virtual void particles_set_emission_transform(RID p_particles, const Transform3D &p_transform) = 0;
	virtual void particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) = 0;
    virtual void particles_set_interp_to_end(RID p_particles, float p_interp_to_end) = 0;

	virtual int particles_get_draw_passes(RID p_particles) const = 0;
	virtual RID particles_get_draw_pass_mesh(RID p_particles, int p_pass) const = 0;

	virtual void particles_set_view_axis(RID p_particles, const Vector3 &p_axis, const Vector3 &p_up_axis) = 0;
```

**Comment by AThousandShips** [comment]
Oversight I believe, those are all constant *references* where the constant is required to prevent modifying the data sent

**Comment by QbieShay** [comment]
Okay thank you!

File: servers/rendering_server.h [hunk 6]
```diff
@@ -703,6 +704,8 @@ class RenderingServer : public Object {
 	virtual AABB particles_get_current_aabb(RID p_particles) = 0;
 
 	virtual void particles_set_emission_transform(RID p_particles, const Transform3D &p_transform) = 0; // This is only used for 2D, in 3D it's automatic.
+	virtual void particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) = 0;
+	virtual void particles_set_interp_to_end(RID p_particles, const float p_interp) = 0;
```
[the remark this answers is not in the document]
Comment (QbieShay) [reply servers/rendering_server.h:708]: I think this method is the base one, so it should keep the const

[the remark this answers is not in the document]
Comment (AThousandShips) [reply servers/rendering_server.h:708]: I don't see how that matters? The point about const for simple types stand

[the remark this answers is not in the document]
Comment (QbieShay) [reply servers/rendering_server.h:708]: Ah it doesn't, I misunderstood a comment as in "only overridden methods don't need const" but following up with the discussion later I see indeed it should be removed here too. My bad :D

File: misc/extension_api_validation/4.0-stable.expected [hunk 7]
```diff
@@ -443,7 +443,6 @@ Validate extension JSON: Error: Field 'classes/PopupMenu/methods/add_shortcut/ar
 
 Added optional argument. Compatibility methods registered.
 
-
```
Comment (akien-mga) [inline misc/extension_api_validation/4.0-stable.expected:446]: Nitpick, but we actually keep two lines between blocks, it's just the one adding GH-80852 which missed it.

**Comment by akien-mga** [comment]
Will need a rebase after #80354 which split the `4.0.stable.expected` file into one for `4.0 -> 4.1` and one for `4.1 -> master`.

**Comment by QbieShay** [comment]
Done!

**Comment by paddy-exe** [comment]
So I had a look through this PR
First off, thank you very much QbieShay for doing this in the first place! This is highly appreciated.
I tried to recreate more or less the following effect: https://www.youtube.com/watch?v=R4XsJ645l6E
image

My findings:
* I searched like almost 30 min for a way to rotate this damn arrow around its axis (Tbh I have not much experience with the Particles Node yet just FYI). This is not a critique specifically to this PR but just in general a UX issue imho as something like rotation should be relatively easy to do without turning every knob and going through the docs.
* It seems to me like Particle Color Ramp and Initial Ramp through the Vertex Color doesn't seem to work correctly for me ("Use as Alebdo" in Vertex Color segment activated)
* `Speed Scale` set to `0` doesn't pause the Particles as described in the tool hint, it just stops emitting

Other than that I find the restructure really well thought out

**Comment by Calinou** [comment]
> - It seems to me like Particle Color Ramp and Initial Ramp through the Vertex Color doesn't seem to work correctly for me ("Use as Alebdo" in Vertex Color segment activated)
>   - Edit: This seems to either a connected issue or a seperated one from master as it only works when I save the Gradient as a resource file, not right inside the inspector

This may be fixed by https://github.com/godotengine/godot/pull/81198.

**Comment by KoBeWi** [comment]
I'm testing this PR in my project and I found one broken effect. I had an outwards swirl effect like this

https://github.com/godotengine/godot/assets/2223172/c28b2d63-f02d-40ac-a664-c81c79cafd79

But with this PR it becomes inwards and the swirling is removed

https://github.com/godotengine/godot/assets/2223172/eb158956-bb29-4045-8e8b-c465764c5e3c

I saved the scene and no particle properties had changed, so I assume something behaves differently. Here are the parameters I used:
```
particle_flag_disable_z = true
emission_shape = 1
emission_sphere_radius = 50.0
initial_velocity_min = 1.0
initial_velocity_max = 1.0
gravity = Vector3(0, 0, 0)
radial_accel_min = -50.0
tangential_accel_min = 200.0
tangential_accel_max = 200.0
scale_min = 2.0
scale_max = 4.0
```

**Comment by QbieShay** [comment]
Thanks again for testing @KoBeWi , I have fixed the issue, i believe. Can you confirm on your end that also the other particle systems look correct?

**Comment by KoBeWi** [comment]
Yes, it's fixed.

File: doc/classes/ParticleProcessMaterial.xml [hunk 8]
```diff
@@ -151,13 +154,29 @@
 		<member name="direction" type="Vector3" setter="set_direction" getter="get_direction" default="Vector3(1, 0, 0)">
 			Unit vector specifying the particles' emission direction.
 		</member>
+		<member name="directional_velocity_curve" type="Texture2D" setter="set_param_texture" getter="get_param_texture">
+			A curve that specify the velocity along each of the axes of the particle system along its lifetime. 
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:159]:
```suggestion
			A curve that specifies the velocity along each of the axes of the particle system along its lifetime.
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 9]
```diff
@@ -151,13 +154,29 @@
...
+		</member>
+		<member name="directional_velocity_max" type="float" setter="set_param_max" getter="get_param_max">
+			Maximum directional velocity value, which is multiplied by [member directional_velocity_curve]
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:163]:
```suggestion
			Maximum directional velocity value, which is multiplied by [member directional_velocity_curve].
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 10]
```diff
@@ -151,13 +154,29 @@
...
+		</member>
+		<member name="directional_velocity_min" type="float" setter="set_param_min" getter="get_param_min">
+			Minimum directional velocity value, which is multiplied by [member directional_velocity_curve]
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:167]:
```suggestion
			Minimum directional velocity value, which is multiplied by [member directional_velocity_curve].
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 11]
```diff
@@ -151,13 +154,29 @@
...
 			The box's extents if [code]emission_shape[/code] is set to [constant EMISSION_SHAPE_BOX].
 		</member>
 		<member name="emission_color_texture" type="Texture2D" setter="set_emission_color_texture" getter="get_emission_color_texture">
 			Particle color will be modulated by color determined by sampling this texture at the same point as the [member emission_point_texture].
 			[b]Note:[/b] [member emission_color_texture] multiplies the particle mesh's vertex colors. To have a visible effect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserted in the shader's [code]fragment()[/code] function. Otherwise, [member emission_color_texture] will have no visible effect.
 		</member>
+		<member name="emission_curve" type="Texture2D" setter="set_emission_curve" getter="get_emission_curve">
+			Each particle's color will be multiplied by this [CurveTexture] over its lifetime.
+			[b]Note:[/b] This value's effect won't be visible unless the render material is marked as unshaded.
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:178]:
```suggestion
			[b]Note:[/b] This property won't have a visible effect unless the render material is marked as unshaded.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 12]
```diff
@@ -71,6 +71,9 @@
 		</method>
 	</methods>
 	<members>
+		<member name="alpha_curve" type="Texture2D" setter="set_alpha_curve" getter="get_alpha_curve">
+			Optionally multiplies the alpha value of the color from [member color_ramp].
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:75]:
```suggestion
			The alpha value of each particle's color will be multiplied by this [CurveTexture] over its lifetime.
```

Am I getting this right?

File: doc/classes/ParticleProcessMaterial.xml [hunk 13]
```diff
@@ -220,17 +248,23 @@
 		</member>
 		<member name="orbit_velocity_curve" type="Texture2D" setter="set_param_texture" getter="get_param_texture">
 			Each particle's orbital velocity will vary along this [CurveTexture].
+			[b]Note:[/b] For 3D orbital velocity, use a [CurveXYZTexture].
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:252]:
```suggestion
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 14]
```diff
@@ -220,17 +248,23 @@
...
 		</member>
-		<member name="orbit_velocity_max" type="float" setter="set_param_max" getter="get_param_max">
+		<member name="orbit_velocity_max" type="float" setter="set_param_max" getter="get_param_max" default="0.0">
 			Maximum orbital velocity applied to each particle. Makes the particles circle around origin. Specified in number of full rotations around origin per second.
-			Only available when [member particle_flag_disable_z] is [code]true[/code].
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:256]:
```suggestion
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

Comment (MewPurPur) [reply doc/classes/ParticleProcessMaterial.xml:256]: Actually I should stop making these remarks, you know, use capitals everywhere

File: doc/classes/ParticleProcessMaterial.xml [hunk 15]
```diff
@@ -246,6 +280,18 @@
 		<member name="radial_accel_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
 			Minimum equivalent of [member radial_accel_max].
 		</member>
+		<member name="radial_velocity_curve" type="Texture2D" setter="set_param_texture" getter="get_param_texture">
+			A [CurveTexture] that defines the velocity over the particle's lifetime away (or towards) the [member velocity_pivot].
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
+		</member>
+		<member name="radial_velocity_max" type="float" setter="set_param_max" getter="get_param_max" default="0.0">
+			Maximum radial velocity applied to each particle. Makes particle move away (or towards if negative) the [member velocity_pivot]
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:288]:
```suggestion
			Maximum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or towards it if negative.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 16]
```diff
@@ -246,6 +280,18 @@
...
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
+		</member>
+		<member name="radial_velocity_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
+			Minimum radial velocity applied to each particle. Makes particle move away (or towards if negative) the [member velocity_pivot]
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:292]:
```suggestion
			Minimum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or towards it if negative.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 17]
```diff
@@ -255,6 +301,17 @@
 		<member name="scale_min" type="float" setter="set_param_min" getter="get_param_min" default="1.0">
 			Minimum equivalent of [member scale_max].
 		</member>
+		<member name="scale_over_velocity_curve" type="Texture2D" setter="set_param_texture" getter="get_param_texture">
+			Either a [CurveTexture] or a [CurveXYZTexture] that scales each particle based on its velocity.
+		</member>
+		<member name="scale_over_velocity_max" type="float" setter="set_param_max" getter="get_param_max" default="0.0">
+			Maximum velocity value reference for [member scale_over_velocity_curve].
+			[member scale_over_velocity_curve] will be interpolated between [member scale_over_velocity_min] and [member scale_over_velocity_max]
```
Comment (MewPurPur) [inline doc/classes/ParticleProcessMaterial.xml:309]: Add a period here, same for the min one.

**Review by MewPurPur — COMMENTED** [review]
Documentation pass

**Comment by BastiaanOlij** [comment]
Just a quick nitpick on the changes on the rendering side. You forgot to add bindings to the methods in `rendering_server.cpp`.`_bind_methods`. Otherwise looks fine to me.

Haven't had a chance to actually play with it and form an opinion on the feature improvement itself, but not sure I've got much perspective to add there :)

**Comment by QbieShay** [comment]
Thank you @BastiaanOlij ! Should all be exposed now.

**Comment by QbieShay** [comment]
I re-requested reviews after addressing everything that's been discussed in the PR.
I think now i need approvals before merging ^^

Please specify the review type
1. Documentation: @AThousandShips , @MewPurPur 
2. Rendering architecture : @BastiaanOlij , @clayjohn
3. Functionality: @Calinou , @paddy-exe , @RPicster 
4. Compatibility: @KoBeWi 
5. Code style: @AThousandShips

File: drivers/gles3/storage/particles_storage.cpp [hunk 18]
```diff
@@ -190,6 +190,13 @@ void ParticlesStorage::particles_set_amount(RID p_particles, int p_amount) {
 	particles->dependency.changed_notify(Dependency::DEPENDENCY_CHANGED_PARTICLES);
 }
 
+void ParticlesStorage::particles_set_amount_ratio(RID p_particles, float p_amount_ratio) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
```
Comment (AThousandShips) [inline drivers/gles3/storage/particles_storage.cpp:195]:
```suggestion
	ERR_FAIL_NULL(particles);
```

File: drivers/gles3/storage/particles_storage.cpp [hunk 19]
```diff
@@ -431,6 +438,19 @@ void ParticlesStorage::particles_set_emission_transform(RID p_particles, const T
...
 
+void ParticlesStorage::particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
+
+	particles->emitter_velocity = p_velocity;
+}
+void ParticlesStorage::particles_set_interp_to_end(RID p_particles, const float p_interp) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
```
Comment (AThousandShips) [inline drivers/gles3/storage/particles_storage.cpp:449]:
```suggestion
	ERR_FAIL_NULL(particles);
```

File: servers/rendering/renderer_rd/storage_rd/particles_storage.cpp [hunk 20]
```diff
@@ -329,6 +332,13 @@ void ParticlesStorage::particles_set_amount(RID p_particles, int p_amount) {
 	particles->dependency.changed_notify(Dependency::DEPENDENCY_CHANGED_PARTICLES);
 }
 
+void ParticlesStorage::particles_set_amount_ratio(RID p_particles, float p_amount_ratio) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:337]:
```suggestion
	ERR_FAIL_NULL(particles);
```

File: servers/rendering/renderer_rd/storage_rd/particles_storage.cpp [hunk 21]
```diff
@@ -651,6 +661,19 @@ void ParticlesStorage::particles_set_emission_transform(RID p_particles, const T
 	particles->emission_transform = p_transform;
 }
 
+void ParticlesStorage::particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:666]:
```suggestion
	ERR_FAIL_NULL(particles);
```

File: servers/rendering/renderer_rd/storage_rd/particles_storage.cpp [hunk 22]
```diff
@@ -651,6 +661,19 @@ void ParticlesStorage::particles_set_emission_transform(RID p_particles, const T
...
+
+	particles->emitter_velocity = p_velocity;
+}
+void ParticlesStorage::particles_set_interp_to_end(RID p_particles, const float p_interp) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:672]:
```suggestion
	ERR_FAIL_NULL(particles);
```

File: servers/rendering/renderer_rd/storage_rd/particles_storage.h [hunk 23]
```diff
@@ -460,6 +467,8 @@ class ParticlesStorage : public RendererParticlesStorage {
 	virtual AABB particles_get_aabb(RID p_particles) const override;
 
 	virtual void particles_set_emission_transform(RID p_particles, const Transform3D &p_transform) override;
+	virtual void particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) override;
+	virtual void particles_set_interp_to_end(RID p_particles, const float p_interp_to_end) override;
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/particles_storage.h:471]:
```suggestion
	virtual void particles_set_interp_to_end(RID p_particles, float p_interp_to_end) override;
```

File: servers/rendering/renderer_rd/storage_rd/particles_storage.cpp [hunk 24]
```diff
@@ -651,6 +661,19 @@ void ParticlesStorage::particles_set_emission_transform(RID p_particles, const T
 	particles->emission_transform = p_transform;
 }
 
+void ParticlesStorage::particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
+
+	particles->emitter_velocity = p_velocity;
+}
+void ParticlesStorage::particles_set_interp_to_end(RID p_particles, const float p_interp) {
```
Comment (AThousandShips) [inline servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:670]:
```suggestion

void ParticlesStorage::particles_set_interp_to_end(RID p_particles, float p_interp) {
```

File: servers/rendering/dummy/storage/particles_storage.h [hunk 25]
```diff
@@ -81,6 +82,8 @@ class ParticlesStorage : public RendererParticlesStorage {
 	virtual AABB particles_get_aabb(RID p_particles) const override { return AABB(); }
 
 	virtual void particles_set_emission_transform(RID p_particles, const Transform3D &p_transform) override {}
+	virtual void particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) override {}
+	virtual void particles_set_interp_to_end(RID p_particles, const float p_interp) override {}
```
Comment (AThousandShips) [inline servers/rendering/dummy/storage/particles_storage.h:86]:
```suggestion
	virtual void particles_set_interp_to_end(RID p_particles, float p_interp) override {}
```

File: scene/resources/particle_process_material.cpp [hunk 26]
```diff
@@ -1233,6 +1479,40 @@ void ParticleProcessMaterial::set_particle_flag(ParticleFlags p_particle_flag, b
...
+}
+
+void ParticleProcessMaterial::set_velocity_limit_curve(const Ref<Texture2D> &p_texture) {
+	velocity_limit_curve = p_texture;
+	RID tex_rid = p_texture.is_valid() ? p_texture->get_rid() : RID();
+	RenderingServer::get_singleton()->material_set_param(_get_material(), shader_names->velocity_limit_curve, tex_rid);
+	_queue_shader_change();
+	notify_property_list_changed();
+}
+Ref<Texture2D> ParticleProcessMaterial::get_velocity_limit_curve() const {
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:1512]:
```suggestion

Ref<Texture2D> ParticleProcessMaterial::get_velocity_limit_curve() const {
```

File: scene/resources/particle_process_material.cpp [hunk 27]
```diff
@@ -1233,6 +1479,40 @@ void ParticleProcessMaterial::set_particle_flag(ParticleFlags p_particle_flag, b
...
 }
 
+void ParticleProcessMaterial::set_alpha_curve(const Ref<Texture2D> &p_texture) {
+	alpha_curve = p_texture;
+	RID tex_rid = p_texture.is_valid() ? p_texture->get_rid() : RID();
+	RenderingServer::get_singleton()->material_set_param(_get_material(), shader_names->alpha_ramp, tex_rid);
+	_queue_shader_change();
+	notify_property_list_changed();
+}
+Ref<Texture2D> ParticleProcessMaterial::get_alpha_curve() const {
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:1489]:
```suggestion

Ref<Texture2D> ParticleProcessMaterial::get_alpha_curve() const {
```

File: drivers/gles3/storage/particles_storage.h [hunk 28]
```diff
@@ -352,6 +358,8 @@ class ParticlesStorage : public RendererParticlesStorage {
 	virtual AABB particles_get_aabb(RID p_particles) const override;
 
 	virtual void particles_set_emission_transform(RID p_particles, const Transform3D &p_transform) override;
+	virtual void particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) override;
+	virtual void particles_set_interp_to_end(RID p_particles, const float p_interp) override;
```
Comment (AThousandShips) [inline drivers/gles3/storage/particles_storage.h:362]:
```suggestion
	virtual void particles_set_interp_to_end(RID p_particles, float p_interp) override;
```

File: drivers/gles3/storage/particles_storage.cpp [hunk 29]
```diff
@@ -431,6 +438,19 @@ void ParticlesStorage::particles_set_emission_transform(RID p_particles, const T
 	particles->emission_transform = p_transform;
 }
 
+void ParticlesStorage::particles_set_emitter_velocity(RID p_particles, const Vector3 &p_velocity) {
+	Particles *particles = particles_owner.get_or_null(p_particles);
+	ERR_FAIL_COND(!particles);
+
+	particles->emitter_velocity = p_velocity;
+}
+void ParticlesStorage::particles_set_interp_to_end(RID p_particles, const float p_interp) {
```
Comment (AThousandShips) [inline drivers/gles3/storage/particles_storage.cpp:447]:
```suggestion

void ParticlesStorage::particles_set_interp_to_end(RID p_particles, float p_interp) {
```

File: doc/classes/GPUParticles2D.xml [hunk 30]
```diff
@@ -50,6 +50,10 @@
 		<member name="amount" type="int" setter="set_amount" getter="get_amount" default="8">
 			Number of particles emitted in one emission cycle.
 		</member>
+		<member name="amount_ratio" type="float" setter="set_amount_ratio" getter="get_amount_ratio" default="1.0">
+			The ratio of particles that should actually be emitted. If set to a value lower than [code]1.0[/code], this will set the amount of emitted particles throughout the lifetime to [code]amount * amount_ratio[/code]. Unlike changing [member GPUParticles2D.amount], changing [member amount_ratio] while emitting does not affect already-emitted particles and doesn't cause the particle system to restart. [member amount_ratio] can be used to create effects that make the number of emitted particles vary over time.
+			[b]Note:[/b] If you don't need to change the number of particles emitted while particles are emitting, keep [member amount_ratio] at [code]1.0[/code] and change [member GPUParticles2D.amount] instead. This will result in better performance, as inactive particles still need to be partially evaluated in the shader otherwise.
```
Comment (MewPurPur) [inline doc/classes/GPUParticles2D.xml:55]: This seems overexplained, imo make it more user-facing like

```suggestion
			[b]Note:[/b] Consider changing the [member amount] instead if the particle system restarting is not a problem, as changing the [member amount_ratio] is more performance-intensive.
```

Also change [member GPUParticles2D.amount] to just [member amount] in the description right above, and also for 3D.

**Comment by QbieShay** [comment]
@AThousandShips sorry for the const stuff, I thought i addressed it. Been sick the past couple of days so my brain has been fuzzy. Thank you for patiently adding suggestions one by one.

File: doc/classes/GPUParticles2D.xml (hunk 30 above)
Comment (QbieShay) [reply doc/classes/GPUParticles2D.xml:55]: I am not sure for either formulation. I am considering actually removing the note since I am hoping to move the code that calculates that out of the shader, so there shouldn't be any performance impact.

Maybe could change the note to:

Note: reducing the amount ratio doesn't cause any increase in performance, since the number of allocated rendering resoures depends on amount.

What do you think?

**Comment by AThousandShips** [comment]
Will make a pass of the shader code when I have the time for style, and the docs

**Comment by QbieShay** [comment]
I am aware that the shader code indentation has issues, but I'd rather address that in a follow up-PR. My priority right now is functionality and distributing it to people, so we can make sure that there's no compat-breaking and if there is address it before 4.2 stable

File: doc/classes/GPUParticles2D.xml (hunk 30 above)
Comment (MewPurPur) [reply doc/classes/GPUParticles2D.xml:55]: If there's no performance concern people should be aware of, I wouldn't leave a note.

File: doc/classes/ParticleProcessMaterial.xml [hunk 31]
```diff
@@ -220,17 +248,23 @@
...
-		<member name="orbit_velocity_max" type="float" setter="set_param_max" getter="get_param_max">
+		<member name="orbit_velocity_max" type="float" setter="set_param_max" getter="get_param_max" default="0.0">
 			Maximum orbital velocity applied to each particle. Makes the particles circle around origin. Specified in number of full rotations around origin per second.
-			Only available when [member particle_flag_disable_z] is [code]true[/code].
+			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
 		</member>
-		<member name="orbit_velocity_min" type="float" setter="set_param_min" getter="get_param_min">
+		<member name="orbit_velocity_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
 			Minimum equivalent of [member orbit_velocity_max].
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:260]:
```suggestion
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 32]
```diff
@@ -246,6 +280,18 @@
 		<member name="radial_accel_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
 			Minimum equivalent of [member radial_accel_max].
 		</member>
+		<member name="radial_velocity_curve" type="Texture2D" setter="set_param_texture" getter="get_param_texture">
+			A [CurveTexture] that defines the velocity over the particle's lifetime away (or towards) the [member velocity_pivot].
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:285]:
```suggestion
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 33]
```diff
@@ -246,6 +280,18 @@
...
+		</member>
+		<member name="radial_velocity_max" type="float" setter="set_param_max" getter="get_param_max" default="0.0">
+			Maximum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or towards it if negative.
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:289]:
```suggestion
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 34]
```diff
@@ -246,6 +280,18 @@
...
+		</member>
+		<member name="radial_velocity_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
+			Minimum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or towards it if negative.
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:293]:
```suggestion
			[b]Note:[/b] Animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 35]
```diff
@@ -246,6 +280,18 @@
 		<member name="radial_accel_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
 			Minimum equivalent of [member radial_accel_max].
 		</member>
+		<member name="radial_velocity_curve" type="Texture2D" setter="set_param_texture" getter="get_param_texture">
+			A [CurveTexture] that defines the velocity over the particle's lifetime away (or towards) the [member velocity_pivot].
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:284]:
```suggestion
			A [CurveTexture] that defines the velocity over the particle's lifetime away (or toward) the [member velocity_pivot].
```
"towards" is generally considered to be UK English.

File: doc/classes/ParticleProcessMaterial.xml [hunk 36]
```diff
@@ -220,17 +248,23 @@
...
-		<member name="orbit_velocity_min" type="float" setter="set_param_min" getter="get_param_min">
+		<member name="orbit_velocity_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
 			Minimum equivalent of [member orbit_velocity_max].
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
 		</member>
 		<member name="particle_flag_align_y" type="bool" setter="set_particle_flag" getter="get_particle_flag" default="false">
 			Align Y axis of particle with the direction of its velocity.
 		</member>
+		<member name="particle_flag_damping_as_friction" type="bool" setter="set_particle_flag" getter="get_particle_flag" default="false">
+			Changes the behaviour of the damping properties from a linear deceleration to a deceleration based on speed percentage.
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:266]:
```suggestion
			Changes the behavior of the damping properties from a linear deceleration to a deceleration based on speed percentage.
```
US English

File: doc/classes/ParticleProcessMaterial.xml [hunk 37]
```diff
@@ -246,6 +280,18 @@
 		<member name="radial_accel_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
 			Minimum equivalent of [member radial_accel_max].
 		</member>
+		<member name="radial_velocity_curve" type="Texture2D" setter="set_param_texture" getter="get_param_texture">
+			A [CurveTexture] that defines the velocity over the particle's lifetime away (or towards) the [member velocity_pivot].
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
+		</member>
+		<member name="radial_velocity_max" type="float" setter="set_param_max" getter="get_param_max" default="0.0">
+			Maximum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or towards it if negative.
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:288]:
```suggestion
			Maximum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or toward it if negative.
```

File: doc/classes/ParticleProcessMaterial.xml [hunk 38]
```diff
@@ -246,6 +280,18 @@
...
+			[b]Note:[/b] animated velocities will not be affected by damping, use [member velocity_limit_curve] instead.
+		</member>
+		<member name="radial_velocity_min" type="float" setter="set_param_min" getter="get_param_min" default="0.0">
+			Minimum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or towards it if negative.
```
Comment (AThousandShips) [inline doc/classes/ParticleProcessMaterial.xml:292]:
```suggestion
			Minimum radial velocity applied to each particle. Makes particles move away from the [member velocity_pivot], or toward it if negative.
```

File: doc/classes/GPUParticles2D.xml (hunk 30 above)
Comment (MewPurPur) [reply doc/classes/GPUParticles2D.xml:55]: Oh, makes sense. I think your description is fine then, just add bold and member references.

Comment (QbieShay) [reply doc/classes/GPUParticles2D.xml:55]: Bold? Where?

Comment (MewPurPur) [reply doc/classes/GPUParticles2D.xml:55]: Haha you know, [b]Note[/b]. Sorry for confusing ya.

File: doc/classes/GPUParticles2D.xml [hunk 39]
```diff
@@ -50,6 +50,10 @@
 		<member name="amount" type="int" setter="set_amount" getter="get_amount" default="8">
 			Number of particles emitted in one emission cycle.
 		</member>
+		<member name="amount_ratio" type="float" setter="set_amount_ratio" getter="get_amount_ratio" default="1.0">
+			The ratio of particles that should actually be emitted. If set to a value lower than [code]1.0[/code], this will set the amount of emitted particles throughout the lifetime to [code]amount * amount_ratio[/code]. Unlike changing [member GPUParticles2D.amount], changing [member amount_ratio] while emitting does not affect already-emitted particles and doesn't cause the particle system to restart. [member amount_ratio] can be used to create effects that make the number of emitted particles vary over time.
```
Comment (MewPurPur) [inline doc/classes/GPUParticles2D.xml:54]:
```suggestion
			The ratio of particles that will actually be emitted. If set to a value lower than [code]1.0[/code], the amount of emitted particles throughout the lifetime will be [code]amount * amount_ratio[/code]. Unlike the [member amount], this property can be changed without affecting already-emitted particles or causing the particle system to restart. [member amount_ratio] can be used for effects that vary the number of emitted particles over time.
```

It was really long, let's try this instead? Same for 3D.

The line below still uses `[member GPUParticles2D.amount]` instead of just `[member amount]`.

File: servers/rendering/renderer_rd/shaders/particles_copy.glsl [hunk 40]
```diff
@@ -159,7 +159,10 @@ void main() {
 			} break; //nothing
 			case TRANSFORM_ALIGN_Z_BILLBOARD: {
 				mat3 local = mat3(normalize(cross(params.align_up, params.sort_direction)), params.align_up, params.sort_direction);
-				local = local * mat3(txform);
+				mat3 angle = mat3(vec3(cos(particles.data[particle].custom.x), -sin(particles.data[particle].custom.x), 0.0),
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/shaders/particles_copy.glsl:162]: Won't this break user shaders that use `z-billboard` but also use ``CUSTOM`` for their own custom data?

Also, this needs to match the Compatibility renderer if we are keeping this change https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/particles_copy.glsl

File: servers/rendering/renderer_rd/shaders/particles.glsl [hunk 41]
```diff
@@ -67,7 +67,7 @@ struct FrameParams {
 	float delta;
 
 	uint frame;
-	uint pad0;
+	float amount_ratio;
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/shaders/particles.glsl:70]: The same changes are needed in the Compatibility renderer. https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/particles.glsl

**Review by clayjohn — COMMENTED** [review]
Great work! I only did a quick review and it mostly looks okay. I left a couple comments.

I do have a concern about how the properties ``amount_ratio`` and ``interp_to_end`` are exposed. When I review the code, it looks like both properties are only used by the process material and could just have easily been uniforms in the process material instead of built in variables (contrast these to ``emitter_velocity`` which is tied into the node and needs to account for node properties). 

Is there a reason why they are exposed this way instead of being limited to the material? 

My preference would be to keep them local to the material to avoid making our particle pipeline more complex.

File: servers/rendering/renderer_rd/shaders/particles_copy.glsl (hunk 40 above)
Comment (QbieShay) [reply servers/rendering/renderer_rd/shaders/particles_copy.glsl:162]: Yes, it will, but that case they shouldn't use the billboard.

**Comment by QbieShay** [comment]
Hey clay thank you for your review!

Yes, I'm aware that amount ratio and interp to end are taking space in the frame data, but

1. they're substituting padding
2. that's the only way there is currently to change it per-node. Duplicated particle materials are expensive because they still need to allocate a new material, which means you cannot have multiple of them and use these two properties.

The usecase for those two is when you have multiple copies of the same VFX in the scene, but you don't want to control them together. You'd have to make unique, but it's not really a good idea, IMO.

I understand that adding things that are only read by our base particle material is somewhat meh, but I told myself that, worst case, it will give people two extra inputs that they can take from the node and don't need to expose to the material itself.

File: doc/classes/GPUParticles2D.xml (hunk 30 above)
Comment (QbieShay) [reply doc/classes/GPUParticles2D.xml:55]: But it's already there? Or not? Sorry I'm very very confused

**Comment by QbieShay** [comment]
Status Update: Clay and I discussed in rocket chat and wanted to try approaching `interp_to_end` and `amount_ratio` as instance properties instead of built-in. 

Clay's PR: https://github.com/godotengine/godot/pull/81459

We are still evaluating which approach is better.

**Comment by AThousandShips** [comment]
Your commit message has misspelling in `Co-authored-by`

**Comment by QbieShay** [comment]
I wonder how that got in there, since i picked it by rebasing haha. I am fixing it right now.

**Comment by QbieShay** [comment]
@AThousandShips I made an issue to track the indentation issues https://github.com/godotengine/godot/issues/81483 so that even after merge we can continue keeping track of them.

File: misc/extension_api_validation/4.1-stable.expected [hunk 42]
```diff
@@ -176,3 +177,9 @@ Validate extension JSON: API was removed: classes/TileMap/methods/set_quadrant_s
 Validate extension JSON: API was removed: classes/TileMap/properties/cell_quadrant_size
 
 cell_quadrant_size/quadrant_size of the TileMap API was renamed to rendering_quadrant_size.
+
+GH-79527
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.1-stable.expected:181]:
```suggestion

GH-79527
```
Keep two lines between entries

File: misc/extension_api_validation/4.1-stable.expected [hunk 43]
```diff
@@ -176,3 +177,9 @@ Validate extension JSON: API was removed: classes/TileMap/methods/set_quadrant_s
...
+--------
+Validate extension JSON: Error: Field 'classes/ParticleProcessMaterial/properties/orbit_velocity_curve': type changed value in new API, from "CurveTexture" to "CurveTexture,CurveXYZTexture".
+
+Added accepted curve type from only CurveTexture to CurveXYZTexture
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.1-stable.expected:185]:
```suggestion
Added accepted curve type from only CurveTexture to CurveXYZTexture.
```

File: misc/extension_api_validation/4.1-stable.expected [hunk 44]
```diff
@@ -117,6 +117,7 @@ Validate extension JSON: API was removed: classes/GLTFDocumentExtensionTextureWe
 
 Excluded unexposed classes from extension_api.json.
 
+<<<<<<< HEAD
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.1-stable.expected:120]:
```suggestion

```
Keep the line, missed conflict marker

File: scene/resources/particle_process_material.cpp [hunk 45]
```diff
@@ -975,6 +1178,14 @@ float ParticleProcessMaterial::get_flatness() const {
 	return flatness;
 }
 
+void ParticleProcessMaterial::set_velocity_pivot(Vector3 p_pivot) {
+	velocity_pivot = p_pivot;
+	RenderingServer::get_singleton()->material_set_param(_get_material(), shader_names->velocity_pivot, p_pivot);
+}
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:1184]:
```suggestion
}

```

File: scene/resources/particle_process_material.h [hunk 46]
```diff
@@ -328,6 +366,9 @@ class ParticleProcessMaterial : public Material {
 	void set_flatness(float p_flatness);
 	float get_flatness() const;
 
+	void set_velocity_pivot(Vector3 p_pivot);
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.h:369]:
```suggestion
	void set_velocity_pivot(const Vector3 &p_pivot);
```

File: scene/resources/particle_process_material.cpp [hunk 47]
```diff
@@ -975,6 +1178,14 @@ float ParticleProcessMaterial::get_flatness() const {
 	return flatness;
 }
 
+void ParticleProcessMaterial::set_velocity_pivot(Vector3 p_pivot) {
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:1181]:
```suggestion
void ParticleProcessMaterial::set_velocity_pivot(const Vector3 &p_pivot) {
```

File: scene/resources/particle_process_material.cpp [hunk 48]
```diff
@@ -1714,60 +2054,87 @@ void ParticleProcessMaterial::_bind_methods() {
...
-	ADD_PROPERTYI(PropertyInfo(Variant::BOOL, "particle_flag_rotate_y"), "set_particle_flag", "get_particle_flag", PARTICLE_FLAG_ROTATE_Y);
-	ADD_PROPERTYI(PropertyInfo(Variant::BOOL, "particle_flag_disable_z"), "set_particle_flag", "get_particle_flag", PARTICLE_FLAG_DISABLE_Z);
-	ADD_GROUP("Direction", "");
+	ADD_SUBGROUP("Angle", "");
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "angle_min", PROPERTY_HINT_RANGE, "-720,720,0.1,or_less,or_greater,degrees"), "set_param_min", "get_param_min", PARAM_ANGLE);
+	ADD_PROPERTYI(PropertyInfo(Variant::FLOAT, "angle_max", PROPERTY_HINT_RANGE, "-720,720,0.1,or_less,or_greater,degrees"), "set_param_max", "get_param_max", PARAM_ANGLE);
+	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "angle_curve", PROPERTY_HINT_RESOURCE_TYPE, "CurveTexture"), "set_param_texture", "get_param_texture", PARAM_ANGLE);
+	ADD_SUBGROUP("Velocity", "");
+	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "inherit_velocity_ratio", PROPERTY_HINT_RANGE, "0.0,1.0,0.001, or_lesser, or_greater"), "set_inherit_velocity_ratio", "get_inherit_velocity_ratio");
```
Comment (AThousandShips) [inline scene/resources/particle_process_material.cpp:2062]:
```suggestion
	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "inherit_velocity_ratio", PROPERTY_HINT_RANGE, "0.0,1.0,0.001,or_less,or_greater"), "set_inherit_velocity_ratio", "get_inherit_velocity_ratio");
```

**Review by AThousandShips — APPROVED** [review]
Style looks good!

**Comment by Calinou** [comment]
I've tested the latest revision of this PR rebased on `master` on:

- https://github.com/godotengine/godot-demo-projects/tree/master/3d/particles
- https://github.com/godotengine/godot-demo-projects/tree/master/3d/antialiasing
- https://github.com/godotengine/godot-demo-projects/pull/849

It works correctly on all 3 projects, but particle collision now makes particles that no longer move "sink" into the ground if they have gravity. This is most noticeable on https://github.com/godotengine/godot-demo-projects/tree/master/3d/particles:

### `master`

*Look at green particles on the right in fullscreen.*

https://github.com/godotengine/godot/assets/180032/183f565e-c03d-4475-98f8-ac9a4347c563

### This PR

https://github.com/godotengine/godot/assets/180032/74fc2cda-1120-498c-acff-b347342964c8

**Comment by Maaot** [comment]
Hi, is there a way so the particle system flips randomly the sprite texture at start?
- So if the particle emits 50 particles, 25 would be normal, and another 25 flipped, or so.

**Comment by Calinou** [comment]
> Hi, is there a way so the particle system flips randomly the sprite texture at start?

If you want to stick to the default ParticleProcessMaterial, you can use flipbook animation with a flipbook that contains both standard and flipped variations of the texture.

Otherwise, you'll have to create a custom ShaderMaterial to achieve this.

**Comment by QbieShay** [comment]
@Maaot I have a custom shader that uses the instance index to do that

**Comment by QbieShay** [comment]
@Calinou RE: negative values: maybe? i didn't see a use for them because they would just shoot out very fast away from the emitter, and I didn't find a specific usecase for it

**Comment by QbieShay** [comment]
Fixed collisions, they were executing too late!

**Comment by MewPurPur** [comment]
Is this in 4.3 territory now?

File: drivers/gles3/storage/particles_storage.h [hunk 49]
```diff
@@ -154,6 +156,7 @@ class ParticlesStorage : public RendererParticlesStorage {
 		double inactive_time = 0.0;
 		bool emitting = false;
 		bool one_shot = false;
+		real_t amount_ratio = 1.0;
```
Comment (clayjohn) [inline drivers/gles3/storage/particles_storage.h:159]:
```suggestion
		float amount_ratio = 1.0;
```
This can be a float since the setter and the shader both use floats

File: servers/rendering/renderer_rd/shaders/particles_copy.glsl (hunk 40 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/shaders/particles_copy.glsl:162]: Ping on this. This is going to break unexpectedly for users that rely on custom.x. Can we get away without relying on custom.x here? Maybe with a different shader variant?

File: scene/resources/particle_process_material.cpp [hunk 50]
```diff
@@ -421,398 +504,531 @@ void ParticleProcessMaterial::_update_shader() {
...
+	code += "void process() {\n";
+	code += "	uint base_number = NUMBER;\n";
+	code += "//	if (repeatable){\n";
+	code += "//		base_number = INDEX;\n";
+	code += "//	}\n";
+	code += "	uint alt_seed = hash(base_number + uint(1) + RANDOM_SEED);\n";
+	code += "	DisplayParameters params;\n";
+	code += "	calculate_initial_display_params(params, alt_seed);\n";
+	code += "	// reset alt seed?\n";
+	code += "	// alt_seed = hash(base_number + uint(1) + RANDOM_SEED);\n";
```
Comment (clayjohn) [inline scene/resources/particle_process_material.cpp:876]: Is this still needed? Its a bit confusing to me. Maybe just remove if we can

File: scene/2d/gpu_particles_2d.cpp [hunk 51]
```diff
@@ -318,6 +323,10 @@ bool GPUParticles2D::get_interpolate() const {
 	return interpolate;
 }
 
+double GPUParticles2D::get_interp_to_end() const {
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.cpp:326]:
```suggestion
float GPUParticles2D::get_interp_to_end() const {
```

File: scene/2d/gpu_particles_2d.cpp [hunk 52]
```diff
@@ -423,6 +432,15 @@ NodePath GPUParticles2D::get_sub_emitter() const {
 	return sub_emitter;
 }
 
+void GPUParticles2D::set_amount_ratio(double p_ratio) {
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.cpp:435]:
```suggestion
void GPUParticles2D::set_amount_ratio(float p_ratio) {
```

File: scene/2d/gpu_particles_2d.cpp [hunk 53]
```diff
@@ -423,6 +432,15 @@ NodePath GPUParticles2D::get_sub_emitter() const {
...
+	amount_ratio = p_ratio;
+	RenderingServer::get_singleton()->particles_set_amount_ratio(particles, p_ratio);
+}
+
+double GPUParticles2D::get_amount_ratio() const {
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.cpp:440]:
```suggestion
float GPUParticles2D::get_amount_ratio() const {
```

File: scene/2d/gpu_particles_2d.h [hunk 54]
```diff
@@ -52,6 +52,7 @@ class GPUParticles2D : public Node2D {
 	bool signal_canceled = false;
 	bool one_shot = false;
 	int amount = 0;
+	real_t amount_ratio = 1.0;
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.h:55]:
```suggestion
	float amount_ratio = 1.0;
```

File: scene/2d/gpu_particles_2d.h [hunk 55]
```diff
@@ -62,6 +63,8 @@ class GPUParticles2D : public Node2D {
 	int fixed_fps = 0;
 	bool fractional_delta = false;
 	bool interpolate = true;
+	double interp_to_end_factor = 0;
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.h:66]:
```suggestion
	float interp_to_end_factor = 0;
```

File: scene/2d/gpu_particles_2d.h [hunk 56]
```diff
@@ -114,6 +117,7 @@ class GPUParticles2D : public Node2D {
 	void set_trail_lifetime(double p_seconds);
 	void set_trail_sections(int p_sections);
 	void set_trail_section_subdivisions(int p_subdivisions);
+	void set_interp_to_end(double p_interp);
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.h:120]:
```suggestion
	void set_interp_to_end(float p_interp);
```

File: scene/2d/gpu_particles_2d.h [hunk 57]
```diff
@@ -136,6 +140,7 @@ class GPUParticles2D : public Node2D {
 	double get_trail_lifetime() const;
 	int get_trail_sections() const;
 	int get_trail_section_subdivisions() const;
+	double get_interp_to_end() const;
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.h:143]:
```suggestion
	float get_interp_to_end() const;
```

File: scene/2d/gpu_particles_2d.h [hunk 58]
```diff
@@ -152,6 +157,9 @@ class GPUParticles2D : public Node2D {
 	void set_texture(const Ref<Texture2D> &p_texture);
 	Ref<Texture2D> get_texture() const;
 
+	void set_amount_ratio(double p_ratio);
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.h:160]:
```suggestion
	void set_amount_ratio(float p_ratio);
```

File: scene/2d/gpu_particles_2d.h [hunk 59]
```diff
@@ -152,6 +157,9 @@ class GPUParticles2D : public Node2D {
...
+	double get_amount_ratio() const;
```
Comment (clayjohn) [inline scene/2d/gpu_particles_2d.h:161]:
```suggestion
	float get_amount_ratio() const;
```

File: scene/3d/gpu_particles_3d.cpp [hunk 60]
```diff
@@ -79,20 +81,20 @@ void GPUParticles3D::set_lifetime(double p_lifetime) {
 	RS::get_singleton()->particles_set_lifetime(particles, lifetime);
 }
 
+void GPUParticles3D::set_interp_to_end(double p_interp) {
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.cpp:84]:
```suggestion
void GPUParticles3D::set_interp_to_end(float p_interp) {
```

File: scene/3d/gpu_particles_3d.cpp [hunk 61]
```diff
@@ -154,6 +156,10 @@ double GPUParticles3D::get_lifetime() const {
 	return lifetime;
 }
 
+double GPUParticles3D::get_interp_to_end() const {
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.cpp:159]:
```suggestion
float GPUParticles3D::get_interp_to_end() const {
```

File: scene/3d/gpu_particles_3d.cpp [hunk 62]
```diff
@@ -641,6 +651,15 @@ void GPUParticles3D::convert_from_particles(Node *p_particles) {
 #undef CONVERT_PARAM
 }
 
+void GPUParticles3D::set_amount_ratio(double p_ratio) {
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.cpp:654]:
```suggestion
void GPUParticles3D::set_amount_ratio(float p_ratio) {
```

File: scene/3d/gpu_particles_3d.cpp [hunk 63]
```diff
@@ -641,6 +651,15 @@ void GPUParticles3D::convert_from_particles(Node *p_particles) {
...
+	amount_ratio = p_ratio;
+	RS::get_singleton()->particles_set_amount_ratio(particles, p_ratio);
+}
+
+double GPUParticles3D::get_amount_ratio() const {
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.cpp:659]:
```suggestion
float GPUParticles3D::get_amount_ratio() const {
```

File: scene/3d/gpu_particles_3d.h [hunk 64]
```diff
@@ -65,6 +65,7 @@ class GPUParticles3D : public GeometryInstance3D {
 	bool signal_canceled = false;
 	bool one_shot = false;
 	int amount = 0;
+	real_t amount_ratio = 1.0;
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.h:68]:
```suggestion
	float amount_ratio = 1.0;
```

File: scene/3d/gpu_particles_3d.h [hunk 65]
```diff
@@ -93,6 +94,8 @@ class GPUParticles3D : public GeometryInstance3D {
 	double time = 0.0;
 	double emission_time = 0.0;
 	double active_time = 0.0;
+	double interp_to_end_factor = 0;
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.h:97]:
```suggestion
	float interp_to_end_factor = 0;
```

File: scene/3d/gpu_particles_3d.h [hunk 66]
```diff
@@ -120,9 +123,11 @@ class GPUParticles3D : public GeometryInstance3D {
 	void set_collision_base_size(real_t p_ratio);
 	void set_trail_enabled(bool p_enabled);
 	void set_trail_lifetime(double p_seconds);
+	void set_interp_to_end(double p_interp);
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.h:126]:
```suggestion
	void set_interp_to_end(float p_interp);
```

File: scene/3d/gpu_particles_3d.h [hunk 67]
```diff
@@ -135,6 +140,10 @@ class GPUParticles3D : public GeometryInstance3D {
 	real_t get_collision_base_size() const;
 	bool is_trail_enabled() const;
 	double get_trail_lifetime() const;
+	double get_interp_to_end() const;
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.h:143]:
```suggestion
	float get_interp_to_end() const;
```

File: scene/3d/gpu_particles_3d.h [hunk 68]
```diff
@@ -135,6 +140,10 @@ class GPUParticles3D : public GeometryInstance3D {
...
+
+	void set_amount_ratio(double p_ratio);
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.h:145]:
```suggestion
	void set_amount_ratio(float p_ratio);
```

File: scene/3d/gpu_particles_3d.h [hunk 69]
```diff
@@ -135,6 +140,10 @@ class GPUParticles3D : public GeometryInstance3D {
...
+	double get_amount_ratio() const;
```
Comment (clayjohn) [inline scene/3d/gpu_particles_3d.h:146]:
```suggestion
	float get_amount_ratio() const;
```

**Review by clayjohn — COMMENTED** [review]
Looks really good! There are a lot of nice changes in this PR

I've taken a much deeper look now and have left suggestions to fix a few things (mostly little things):
1. Consistency with types (a lot of places in the API were mixing floats/doubles/real_t, I made suggestions to clean that up)
2. OpenGL, some stuff is missing in OpenGL to make it functional
3. Use of custom.x in the GPU Copy shader. We can't assume that custom.x always contains  rotation. It will break particles when users write custom shaders. I suggest adding a new property for this. For this PR, I would remove the changes in gpu_copy and then make a follow up PR add a new ``ROTATION`` property, then in the process shader assign the rotation value to ROTATION and to custom.x (so user shaders continue to work).

File: scene/resources/particle_process_material.cpp [hunk 70]
```diff
@@ -232,6 +278,8 @@ void ParticleProcessMaterial::_update_shader() {
 
 	if (sub_emitter_mode != SUB_EMITTER_DISABLED && !RenderingServer::get_singleton()->is_low_end()) {
 		if (sub_emitter_mode == SUB_EMITTER_CONSTANT) {
+			// TODO
+			// Add sub emitter emission curve.
```
[the remark this answers is not in the document]
Comment (QbieShay) [reply scene/resources/particle_process_material.cpp:282]: I am not sure it is me who added it, but maybe it is, in that case i'll remove it

File: scene/resources/particle_process_material.cpp [hunk 71]
```diff
@@ -421,398 +504,531 @@ void ParticleProcessMaterial::_update_shader() {
...
+	code += "	if (CUSTOM.y > CUSTOM.w) {\n";
+	code += "		ACTIVE = false;\n";
+	code += "	}\n";
+	code += "	\n";
+	code += "	\n";
+	code += "	\n";
+	code += "	// will use this later to calculate final displacement and orient the particle.\n";
+	code += "	vec3 starting_position = TRANSFORM[3].xyz;\n";
+	code += "	vec3 controlled_displacement = vec3(0.0);\n";
+	code += "	// FIXME use instance uniform!!!!!\n";
```
[the remark this answers is not in the document]
Comment (QbieShay) [reply scene/resources/particle_process_material.cpp:896]: It has, I'll remove it, thank you!

File: servers/rendering/renderer_rd/shaders/particles_copy.glsl (hunk 40 above)
Comment (QbieShay) [reply servers/rendering/renderer_rd/shaders/particles_copy.glsl:162]: I don't think there's people using the built-in billboarding and using custom.x as something else, but i can remove it

File: misc/extension_api_validation/4.1-stable.expected [hunk 72]
```diff
@@ -184,3 +184,11 @@ Validate extension JSON: Error: Field 'classes/PhysicsServer3DRenderingServerHan
...
 
 Intentional compatibility breakage to be consistent with the new non-virtual set_vertex/set_normal.
+
+
+GH-79527
+--------
+Validate extension JSON: Error: Field 'classes/ParticleProcessMaterial/properties/orbit_velocity_curve': type changed value in new API, from "CurveTexture" to "CurveTexture,CurveXYZTexture".
+
+Added accepted curve type from only CurveTexture to CurveXYZTexture.
+
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.1-stable.expected:194]:
```suggestion
```

File: misc/extension_api_validation/4.1-stable.expected [hunk 73]
```diff
@@ -185,6 +185,7 @@ Validate extension JSON: Error: Field 'classes/PhysicsServer3DRenderingServerHan
 Intentional compatibility breakage to be consistent with the new non-virtual set_vertex/set_normal.
 
 
+<<<<<<< HEAD
```
Comment (clayjohn) [inline misc/extension_api_validation/4.1-stable.expected:188]:
```suggestion
```

File: drivers/gles3/shaders/particles.glsl [hunk 74]
```diff
@@ -78,7 +78,10 @@ layout(std140) uniform FrameData { //ubo:0
 	float delta;
 
 	float particle_size;
-	float pad0;
+	vec3 emitter_velocity;
+
+	float amount_ratio;
+	float interp_to_end;
```
Comment (clayjohn) [inline drivers/gles3/shaders/particles.glsl:84]: These are just out of place. They need to match the struct in particles_storage.h. 

```
diff --git a/drivers/gles3/shaders/particles.glsl b/drivers/gles3/shaders/particles.glsl
index 105f8316d3..64ef26b075 100644
--- a/drivers/gles3/shaders/particles.glsl
+++ b/drivers/gles3/shaders/particles.glsl
@@ -78,10 +78,7 @@ layout(std140) uniform FrameData { //ubo:0
        float delta;
 
        float particle_size;
-       vec3 emitter_velocity;
-
        float amount_ratio;
-       float interp_to_end;
        float pad1;
        float pad2;
 
@@ -92,6 +89,9 @@ layout(std140) uniform FrameData { //ubo:0
 
        mat4 emission_transform;
 
+       vec3 emitter_velocity;
+       float interp_to_end;
+
        Attractor attractors[MAX_ATTRACTORS];
        Collider colliders[MAX_COLLIDERS];
 };
```

**Review by clayjohn — APPROVED** [review]
Everything looks good to me now. I have tested locally on a few projects and it appears to work fine. 

I have not tested extensively as I don't have complex particle projects available, but I trust the other reviews that were done and confirm that this works and doesn't break compatibility. 

For future reference we discussed the additions extensively on Rocketchat. Ultimately I am a bit hesitant about adding properties to the Particles node (amount_ratio and interp_to_end) which basically are used to ferry data to the shader on a per-node basis. To me it feels messy and over-complicated. However, we discussed alternatives and there are no good alternatives to implement these features. So ultimately, I am fine with the implementation.

Everything else looks fantastic. I am certain that VFX users will be very happy with these changes. 

Great work!

**Comment by QbieShay** [comment]
Thank you!!!!!

**Comment by akien-mga** [comment]
Thanks! Amazing work and dedication :purple_heart: 

Let's get this tested widely in 4.2 beta 1 :)

I'm not sure which of the proposals and issues linked as "Addressed" in the OP can be closed, so I'll let you assess it.

**Comment by arkology** [comment]
Looked through some of closed proposal and not sure that they could be closed as implemented only for GPUParticles. Please correct me if I'm wrong.
Also what about conversion between GPU and CPU particles, how does it work with new features added to GPUParticles?

**Comment by clayjohn** [comment]
> Looked through some of closed proposal and not sure that they could be closed as implemented only for GPUParticles. Please correct me if I'm wrong. Also what about conversion between GPU and CPU particles, how does it work with new features added to GPUParticles?

We aren't porting all GPUParticles features over the CPUParticles anymore. GPUParticles are supported by all backends now, so instead of being the fallback, CPUParticles are now the ultra-light alternative to GPUParticles. As such, we don't want to bloat CPUParticles or add to the development overhead for improving particles in general.

**Comment by arkology** [comment]
@clayjohn thanks for clarifying. If so, I think this should be properly documented to prevent confusion.

**Comment by QbieShay** [comment]
Yup sorry about that. I have a blogpost to publish with info about the changes and how particles will be maintained moving forward. I just haven't published it yet

**Comment by QbieShay** [comment]
@NathanLovato @Calinou mind if i use the videos you posted in the blogpost?

**Comment by NathanLovato** [comment]
@QbieShay you don't even have to ask when it comes to us! And if you want to credit someone, you can credit Thibaud, the artist. Whichever link you prefer:

- His website: https://gotibo.fr/
- His itch.io with jam games: https://gtibo.itch.io/
