### PR TITLE
Fix lack of ProjectManager nullptr initializations

### LINKED ISSUE #59655: Editor hard crash on start
### Godot version

v4.0.dev.custom_build

### System information

Windows 10, Vulkan, GTX 780Ti

### Issue description

Not 100% sure what the issue is but it's a build from 2 hours ago and im hard crashing on startup.

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.dev.custom_build (ACDCABBACD)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] HashMap<StringName,Ref<StyleBox>,HashMapHasherDefault,HashMapComparatorDefault<StringName>,3,8>::getptr (X:\GameDev\Godot\King\king-godot\core\templates\hash_map.h:317)
[1] HashMap<StringName,Ref<StyleBox>,HashMapHasherDefault,HashMapComparatorDefault<StringName>,3,8>::has (X:\GameDev\Godot\King\king-godot\core\templates\hash_map.h:276)
[2] Control::add_theme_style_override (X:\GameDev\Godot\King\king-godot\scene\gui\control.cpp:2245)
[3] ProjectManager::_notification (X:\GameDev\Godot\King\king-godot\editor\project_manager.cpp:1901)
[4] ProjectManager::_notificationv (X:\GameDev\Godot\King\king-godot\editor\project_manager.h:51)
[5] Object::notification (X:\GameDev\Godot\King\king-godot\core\object\object.cpp:850)
[6] Node::_propagate_ready (X:\GameDev\Godot\King\king-godot\scene\main\node.cpp:181)
[7] Node::_propagate_ready (X:\GameDev\Godot\King\king-godot\scene\main\node.cpp:173)
[8] Node::_set_tree (X:\GameDev\Godot\King\king-godot\scene\main\node.cpp:2458)
[9] SceneTree::initialize (X:\GameDev\Godot\King\king-godot\scene\main\scene_tree.cpp:403)
[10] OS_Windows::run (X:\GameDev\Godot\King\king-godot\platform\windows\os_windows.cpp:675)
[11] widechar_main (X:\GameDev\Godot\King\king-godot\platform\windows\godot_windows.cpp:169)
[12] _main (X:\GameDev\Godot\King\king-godot\platform\windows\godot_windows.cpp:191)
[13] main (X:\GameDev\Godot\King\king-godot\platform\windows\godot_windows.cpp:205)
[14] invoke_main (d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79)
[15] __scrt_common_main_seh (d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[16] __scrt_common_main (d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
[17] mainCRTStartup (d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17)
[18] BaseThreadInitThunk
-- END OF BACKTRACE --
```

### Steps to reproduce

Pulled master, compiled, run.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by marstaik**
Initialize all pointers to nullptr, fixes a crash with asset_library caused by uninitialized memory.

Fixes: https://github.com/godotengine/godot/issues/59655

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/project_manager.h [hunk 1]
```diff
@@ -55,46 +55,46 @@ class ProjectManager : public Control {
 
 	static ProjectManager *singleton;
```
Comment (dmitryuck) [inline editor/project_manager.h:56]: here we don't need `static ProjectManager *singleton = nullptr;` ?

Comment (marstaik) [reply editor/project_manager.h:56]: it is already in the c++ file as it is a static

**Comment by akien-mga** [comment]
Thanks!
