### PR TITLE
Fix duplicating visual shader nodes

### LINKED ISSUE #20212: Visual Shader Editor Duplicate bug
**Godot version:**
Godot 3.1

**Issue description:**
Create a Visual shader , Create more then 1 node in the Shader .. Select a node and press CTRL + D to duplicate that node , it duplicate all the nodes not only the selected one

### PR DESCRIPTION
**Pull request by Xrayez**
There's another issue when duplicated nodes do not get reselected that I haven't yet figured out how to fix, for which I opened an issue #24237.

Closes #20212.

### CODE REVIEW

File: editor/plugins/visual_shader_editor_plugin.cpp [hunk 1]
```diff
@@ -636,13 +636,15 @@ void VisualShaderEditor::_duplicate_nodes() {
 
 	for (int i = 0; i < graph->get_child_count(); i++) {
 
-		if (Object::cast_to<GraphNode>(graph->get_child(i))) {
+		GraphNode *gn = Object::cast_to<GraphNode>(graph->get_child(i));
+		if (gn) {
 			int id = String(graph->get_child(i)->get_name()).to_int();
```
Comment (akien-mga) [inline editor/plugins/visual_shader_editor_plugin.cpp]: Maybe replace `graph->get_child(i)` by `gn` here?

Comment (Xrayez) [reply editor/plugins/visual_shader_editor_plugin.cpp]: This is necessary because `GraphEdit` has some other control nodes like `HScrollBar` as direct children, this will lead to crash.

Comment (Xrayez) [reply editor/plugins/visual_shader_editor_plugin.cpp]: Ah, yes, makes sense, I looked at the wrong line.

Comment (Xrayez) [reply editor/plugins/visual_shader_editor_plugin.cpp]: There are other places when the pointer is not reused here, but that can be fixed as part of other PR pertaining to the issue I linked...

**Comment by akien-mga** [comment]
Thanks!
