### PR TITLE
GDScript call stack as reverse linked list with fixed coroutines

### LINKED ISSUE #106489: Incorrect line numbers for coroutines in GDScript stack traces
### Tested versions

- Reproducible in `4.0-stable`, `4.3-stable` and the recent `4.4.1-stable` (must be an old issue)
- Reproducible in `4.5-dev4`
- Not reproducible with `dev_build=yes`

Tested on Linux and macOS.

### System information

Godot v4.5.dev4 - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 02 May 2025 06:44:33 +0000 on Wayland - Wayland display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 threads)

### Issue description

GDScript stack traces involving coroutines do not report proper line numbers:

Screenshot 2025-04-23 at 21 51 43

 f1, f2, f3 are coroutines.

_Originally posted by @limbonaut in https://github.com/godotengine/godot/pull/91006#pullrequestreview-2788548486_
 
This is unrelated to the script backtrace PR, as I can reproduce it on stable versions as well:

Image

### Steps to reproduce

MRP provided. Run a project with the following script to trigger an error and check the `Debugger -> Stack Trace`:

```gdscript
extends Node2D


func _ready() -> void:
	await f1()
	var a
	a.hello() # trigger nullref access error


func f1():
	print("starting f1")
	await f2()
	print("finishing f1")


func f2():
	print("starting f2")
	await f3()
	print("finishing f2")


func f3():
	print("starting f3")
	await get_tree().process_frame
	print("finishing f3")

```

You should see something similar in the editor:

Image

Note the line numbers in the stack trace.

UPDATE:
Make sure you are building with `dev_build=no`. Apparently it's not reproducible with `dev_build=yes`.

### Minimal reproduction project (MRP)

[mrp-coroutine-stack-trace-issue.zip](https://github.com/user-attachments/files/20243852/mrp-coroutine-stack-trace-issue.zip)

### PR DESCRIPTION
**Pull request by limbonaut**
* GDScript call stack as reverse linked list with issues fixed (originally proposed by @reduz in GH-91006).
* Fix coroutine issues with call stack by resuming async call chain inside `GDScriptFunction::call()`.
* Fix GH-106489.
* Supersedes #106758.

Note: The issue with the original implementation was that it was crashing in coroutine tests -- it's resolved here.

Merging this will help [Sentry SDK](https://github.com/getsentry/sentry-godot) to display accurate stack traces to users.

### Why it happens

1. Function is entered, awaited, and therefore exited (we're not interested in details at this point).
2. Later, the function is resumed with a function-state object (now we're interested in details).
3. Inside `call()`: `line` variable is local, and `enter_function()` is passed a reference to this variable.
4. `enter_function()` initializes `CallLevel` with a pointer to the `line` variable (which is scoped to `call()`).
5. The `line` variable is continuously updated during GDScript function execution using OPCODE_LINE operation. 
6. The GDScript function execution ends, `call()` is exited, and `line` is popped off the stack, but the `CallLevel` instance still lives on due to specifics of the resumed function execution (`exit_function()` isn't called yet).
7. The next function-state object is resumed via signal, and steps 2–6 repeat until no function-state objects remain in the resume chain.
8. Resumed functions finally exit, but the `CallLevel` frames overstayed the lifetime of their `line` variables.

**Conclusion:** Because `CallLevel` in GDScript call stack outlives `call()`'s scope for resumed coroutines, `CallLevel*` and `int *line` pointers can sometimes point to heaven-knows-what. 

**Note:** This PR ensures that function-state execution remains within the `call()` scope, and doesn't cause issues with `CallLevel` being freed before it's removed from the GDScript call stack.

### Explaining on example

Consider this code:
```gdscript
func _ready() -> void:
	await f1()
	for b in Engine.capture_script_backtraces(): print(b)

func f1():
	print("starting f1")
	await f2()
	print("finishing f1")

func f2():
	print("starting f2")
	await f3()
	print("finishing f2")

func f3():
	print("starting f3")
	await get_tree().process_frame
	print("finishing f3")

```

Output:
> Note: Lines starting with "debug: " are print_line() statements I placed in the native code.
```
debug: call( @implicit_new ): entering
debug: enter_function( @implicit_new )    [ call_level.line: 0 ]
debug: exit_function( @implicit_new )    [ call_level.line: 0 ]
debug: call( @implicit_new ): exiting
debug: call( _ready ): entering
debug: enter_function( _ready )    [ call_level.line: 4 ]
debug: call( f1 ): entering
debug: enter_function( f1 )    [ call_level.line: 9 ]
starting f1
debug: call( f2 ): entering
debug: enter_function( f2 )    [ call_level.line: 15 ]
starting f2
debug: call( f3 ): entering
debug: enter_function( f3 )    [ call_level.line: 21 ]
starting f3
debug: exit_function( f3 )    [ call_level.line: 23 ]
debug: call( f3 ): exiting
debug: exit_function( f2 )    [ call_level.line: 17 ]
debug: call( f2 ): exiting
debug: exit_function( f1 )    [ call_level.line: 11 ]
debug: call( f1 ): exiting
debug: exit_function( _ready )    [ call_level.line: 5 ]
debug: call( _ready ): exiting
debug: call( f3 ): entering
debug: enter_function( f3 )    [ call_level.line: 23 ]
finishing f3
debug: call( f3 ): exiting
debug: call( f2 ): entering
debug: enter_function( f2 )    [ call_level.line: 17 ]
finishing f2
debug: call( f2 ): exiting
debug: call( f1 ): entering
debug: enter_function( f1 )    [ call_level.line: 11 ]
finishing f1
debug: call( f1 ): exiting
debug: call( _ready ): entering
debug: enter_function( _ready )    [ call_level.line: 5 ]
GDScript backtrace (most recent call first):
    [0] _ready (res://main.gd:6)
    [1] f1 (res://main.gd:32765)
    [2] f2 (res://main.gd:32765)
    [3] f3 (res://main.gd:32765)
debug: call( _ready ): exiting
debug: exit_function( _ready )    [ call_level.line: 6 ]
debug: exit_function( f1 )    [ call_level.line: 32765 ]
debug: exit_function( f2 )    [ call_level.line: 32765 ]
debug: exit_function( f3 )    [ call_level.line: 32765 ]
```
Notice that the backtrace reports crazy line numbers, and how `call(f1)` already exited, but the associated CallLevel frame lingers slightly longer in the end (`exit_function(f1)`). This only happens for resumed functions.

### CODE REVIEW

**Comment by limbonaut** [comment]
Oh, I probably removed that check by accident, as I was thinking of removing the option altogether, but it might be too controversial of a change. I'm not sure how open the team is to enabling script traces for all builds by default.

File: modules/gdscript/gdscript.h [hunk 1]
```diff
@@ -492,23 +483,20 @@ class GDScriptLanguage : public ScriptLanguage {
...
 #ifdef DEBUG_ENABLED
 		ScriptDebugger *script_debugger = EngineDebugger::get_script_debugger();
 		if (script_debugger != nullptr && script_debugger->get_lines_left() > 0 && script_debugger->get_depth() >= 0) {
 			script_debugger->set_depth(script_debugger->get_depth() + 1);
 		}
 #endif
 
-		if (unlikely(_call_stack.stack_pos >= _debug_max_call_stack)) {
+		if (unlikely(_call_stack_size >= _debug_max_call_stack)) {
+			// stack overflow
```
Comment (vnen) [inline modules/gdscript/gdscript.h]: I prefer to avoid comments like this. The error message is already saying "Stack overflow", so this is very redundant.

**Review by vnen — APPROVED** [review]
I'm not really familiar with the call stack code and the coroutine code is quite complex so it's always hard to review. But the code does look okay to me.

We probably need to add proper test for coroutines to guarantee they work as expected, but this is a topic for another day.

File: modules/gdscript/gdscript.h (hunk 1 above)
Comment (limbonaut) [reply modules/gdscript/gdscript.h]: Makes sense – I removed the comment.

**Comment by Repiteo** [comment]
Thanks!
