### PR TITLE
Release focus of Control Node when exiting tree

### LINKED ISSUE #56247: When a focused Control exits the tree it is unfocused yet it does not emit_signal("focus_exited")
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

Controls don't emit the `focus_exited` signal when they are removed from the tree. If they are focused they should emit `focus_exited` along with the standard tree signals.

### Steps to reproduce

```gdscript
extends GridContainer

func _ready() -> void:
	var button := Button.new()
	button.text = "press me"
	add_child(button)

	button.connect("focus_entered", self, "_print", ["focused"])
	button.connect("focus_exited", self, "_print", ["unfocused"])
	button.connect("tree_exiting", self, "_print", ["exiting tree"])
	button.connect("pressed", button, "queue_free")

func _print(value) -> void:
	print(value)
```

Observe when clicking:
```
focused
exiting tree
```
It is expected to have emitted `focus_exited` and printed `unfocused`.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by PucklaJ**
Fixes #56247

`Control::release_focus` is called when `NOTIFICATION_EXIT_TREE` is recieved in `Control::_notification`.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1373,6 +1377,10 @@ void Control::_size_changed() {
 	}
 }
 
+void Control::_tree_exiting() {
+	release_focus();
+}
```
Comment (YeldhamDev) [inline scene/gui/control.cpp:1382]: Wouldn't be better to add this to the `NOTIFICATION_EXIT_TREE` branch of the `_notification()` function instead of creating another one?

Comment (PucklaMotzer09) [reply scene/gui/control.cpp]: Yes this is the better option. I am rather new to contributing to godot, so I used a signal.

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.
