### PR TITLE
Fix gdscript pattern matching expressions

### LINKED ISSUE #52032: [GDScript 2.0] [regression] Godot hangs while parsing complex `match` expression
### Godot version

master #fb176d5f6e6dc2b43c630a041a8ab7d737173ec4

### System information

manjaro linux

### Issue description

following script:
```
var y
func foo(x):
	match x:
		1 + 1:
			pass
		[1,2,[1,{1:2,2:var z,..,}]]:
			pass
		1 if true else 2:
			pass
		1 or 2 and 1:
			pass
		1 < 2:
			pass
		1 | 1:
			pass
		1 >> 1:
			pass
		1, 2 or 3, 4:
			pass
		_:
			pass
```

causes Godot hanging, while it was working fine in Godot `3.x`

### Steps to reproduce

compile

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ThreeRhinosInAnElephantCostume**
Fixes #52032

The parser handled expressions  that began with a literal like `1+1:` as just a single literal (`1`) and then went into an infinite loop. Could be an attempt at an optimization gone wrong, not sure, but it's fixed now. There was another potential issue with dictionaries nested inside arrays, I fixed that too. I also made it less likely that a failure like this will result in an infinite loop in the future. 

The second commit contains tests for expression matching.

### CODE REVIEW

**Comment by lyuma** [comment]
We should also test this against the reproduction projects in related issues #49740, #50865 and #50750

**Comment by ThreeRhinosInAnElephantCostume** [comment]
> We should also test this against the reproduction projects in related issues ~#49740 (edit: probably not this actually)~, #50865 and #50750 and #49293 (adding '0' into line 11 of Chat.gd)

#50865 doesn't even load for me, so I can't test it. 
#50750 and #49293 do seem to be fixed though.

**Comment by lyuma** [comment]
Forgive my lack of familiarity with the code, but I'm interested in the reasoning for removing the literal case from the code:
```cpp
		case GDScriptTokenizer::Token::LITERAL:
			advance();
			pattern->pattern_type = PatternNode::PT_LITERAL;
			pattern->literal = parse_literal();
			if (pattern->literal == nullptr) {
				// Error happened.
				return nullptr;
			}
			break;
```

I would expect the literal case to both be common, and have some important optimization potential over expressions and other cases.

Shouldn't the `advance()` in that literal case prevent any sort of infinite loop by guaranteeing forward progress? In that case, why would removing it be necessary to resolve this bug?

Anyway that's my only question reading the code. The other changes appear good at first glance, though it would be good for someone more familiar with the parser to review.

**Comment by ThreeRhinosInAnElephantCostume** [comment]
Alright, so take the specific test case that I used while debugging the issue:
```
func foo(x):
    match x:
        1+1:
           print("1+1")
 ```
 
The parser gets to the first "1" as a literal, saves it as the pattern, advances past it, and then checks for either:

- A comma indicating another pattern.
- A colon indicating the end of the list of patterns.

You might notice that neither of those are going to happen, because with that advance, were now at a "+" sign.  Note that I also added some error handling, so that an issue like this would likely result in a series of errors instead of a complete freeze.

I think the idea was that the resulting code would be faster if simple patterns like `1:` would be handled as a single literal.

I am working on adding more tests to GDScript to avoid issues like this in the future, but I am going to need this and #52068 to be merged first.

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -1895,6 +1888,7 @@ GDScriptParser::PatternNode *GDScriptParser::parse_match_pattern(PatternNode *p_
 			ExpressionNode *expression = parse_expression(false);
 			if (expression == nullptr) {
 				push_error(R"(Expected expression for match pattern.)");
+				return nullptr;
 			} else {
 				pattern->pattern_type = PatternNode::PT_EXPRESSION;
 				pattern->expression = expression;
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:1894]: Since you removed the `PT_LITERAL` case, there should be a check if this expression is a literal to use that pattern type instead.

**Comment by vnen** [comment]
Seems okay to me. It would be nice if you add a test case for this in `modules/gdscript/test/scripts` (see [the documentation](https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html#integration-tests-for-gdscript) for details) so we can make sure this isn't reintroduced in the future.

**Comment by ThreeRhinosInAnElephantCostume** [comment]
> Seems okay to me. It would be nice if you add a test case for this in `modules/gdscript/test/scripts` (see [the documentation](https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html#integration-tests-for-gdscript) for details) so we can make sure this isn't reintroduced in the future.

I have a couple of tests ready on another branch. I was hoping to include this as a part of #48029, but I can add it to this commit though, if you'd prefer.

**Comment by vnen** [comment]
> I have a couple of tests ready on another branch. I was hoping to include them as a part of #48029, but I can add them to this PR, if you'd prefer.

Yeah, I think it would be better to add them here already instead of waiting for that PR to be merged.

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (ThreeRhinosInAnElephantCostume) [reply modules/gdscript/gdscript_parser.cpp]: Done

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -1745,7 +1746,8 @@ GDScriptParser::MatchBranchNode *GDScriptParser::parse_match_branch() {
 		push_error(R"(No pattern found for "match" branch.)");
 	}
 
-	consume(GDScriptTokenizer::Token::COLON, R"(Expected ":" after "match" patterns.)");
+	if (!consume(GDScriptTokenizer::Token::COLON, R"(Expected ":" after "match" patterns.)"))
+		return nullptr;
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:1750]: Need to use braces on `if` statements to follow the style guidelines.

**Review by vnen — CHANGES_REQUESTED** [review]
Just one little thing, otherwise the fix looks good to me.

File: modules/gdscript/gdscript_parser.cpp (hunk 2 above)
Comment (ThreeRhinosInAnElephantCostume) [reply modules/gdscript/gdscript_parser.cpp]: Should be good now. Out of curiosity, why doesn't aren't there any checks for that?

**Review by vnen — APPROVED** [review]

File: modules/gdscript/gdscript_parser.cpp (hunk 2 above)
Comment (vnen) [reply modules/gdscript/gdscript_parser.cpp]: > Should be good now. Out of curiosity, why aren't there any checks for that?

Not sure, I think clang-format doesn't have a check for that and adding another tool just for this check is not ideal.

File: modules/gdscript/gdscript_parser.cpp [hunk 3]
```diff
@@ -1849,44 +1843,45 @@ GDScriptParser::PatternNode *GDScriptParser::parse_match_pattern(PatternNode *p_
...
+						// Value pattern.
+						PatternNode *sub_pattern = parse_match_pattern(p_root_pattern != nullptr ? p_root_pattern : pattern);
+						if (sub_pattern == nullptr) {
+							continue;
+						}
 						if (pattern->rest_used) {
 							push_error(R"(The ".." pattern must be the last element in the pattern dictionary.)");
+						} else if (sub_pattern->pattern_type == PatternNode::PT_REST) {
+							push_error(R"(The ".." patter
+							n cannot be used as a value.)");
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:1875]: Wait, what happened here? There's a stray newline.

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_parser.cpp (hunk 3 above)
Comment (ThreeRhinosInAnElephantCostume) [reply modules/gdscript/gdscript_parser.cpp]: Oh for crying out loud!

**Review by vnen — APPROVED** [review]

**Comment by vnen** [comment]
Thanks!
