### PR TITLE
Register enum type names in release build

### LINKED ISSUE #64084: GDScript 2.0: An enum type annotation is parsed differently in release and debug/editor mode
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 10, 64-bit editor and builds

### Issue description

The GDScript parser exhibits different behavior in a release export compared to the debug export or running in editor. Here's the offending line:
```gdscript
func _on_json_request_completed(result: HTTPRequest.Result, response_code: int, headers: PackedStringArray, body: PackedByteArray):
    if result != HTTPRequest.RESULT_SUCCESS or response_code != 200:
```

This line causes no issue in the editor or in a debug build. However, a release build throws the following error:
```
SCRIPT ERROR: Parse Error: Invalid operands "HTTPRequest" and "int" for "!=" operator.
          at: GDScript::reload (res://gui/releases/release_list.gd:136)
```

Changing the type annotation of `result` to `int` fixes the error, which likely means the Result enum was mistaken for the HTTPRequest class.

### Steps to reproduce

1. Declare a variable with a `HTTPRequest.Result` type annotation
2. Use the inequality operator to compare it with one of the `HTTPRequest.Result` constants
3. Export the project in release mode
4. Start the build with a console attached

### Minimal reproduction project

[EnumAnnotation.zip](https://github.com/godotengine/godot/files/9292958/EnumAnnotation.zip)

### PR DESCRIPTION
**Pull request by heppocogne**
This commit fixes #64084
- Add script error for non-existing C++ enum types.
- Modify macro definitions for release build.

### CODE REVIEW

**Comment by anvilfolk** [comment]
Can you fix the conflicts? I think this is the only way to fix #69532 :)

**Comment by heppocogne** [comment]
@anvilfolk 
Fixed confliction.

**Comment by anvilfolk** [comment]
Thank you! You also need to squash your commits into a single commit! :)

**Comment by heppocogne** [comment]
ok, I squashed 2 commits into a commit.

**Comment by akien-mga** [comment]
You still have two commits, because you merged the master branch back on top of your squashed commit instead of rebasing:
image

Moreover, the commit message should not be "Squash commit" - that's what *you* did, but we need to know what *the commit does*. It should describe how it improves/changes/fixes engine functionality. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

**Comment by anvilfolk** [comment]
Sorry, my bad for not spotting that. That's what you get with insomnia at 5am ;)

This guide helped me: https://www.sitepoint.com/git-interactive-rebase-guide/

**Comment by heppocogne** [comment]
@akien-mga @anvilfolk 
Thanks for your help. I could squash all commits into one commit.

**Comment by vnen** [comment]
I've actually been meaning to do this, since the alternative is remove the ability to address enums by their names. The only thing I want to see is a comparison in size of release builds with and without this. Though I doubt it would be much since I don't think that are that many enums around.

File: core/object/class_db.h [hunk 1]
```diff
@@ -372,17 +372,17 @@ class ClassDB {
...
 	::ClassDB::bind_integer_constant(get_class_static(), __constant_get_enum_name(m_constant, #m_constant), #m_constant, m_constant);
 
 #define BIND_BITFIELD_FLAG(m_constant) \
 	::ClassDB::bind_integer_constant(get_class_static(), __constant_get_bitfield_name(m_constant, #m_constant), #m_constant, m_constant, true);
 
+#ifdef DEBUG_METHODS_ENABLED
+
+#define BIND_CONSTANT(m_constant) \
+	::ClassDB::bind_integer_constant(get_class_static(), StringName(), #m_constant, m_constant);
+
```
Comment (vnen) [inline core/object/class_db.h:385]: Given this is the same with or without `DEBUG_METHODS_ENABLED` it could stay outside the `#ifdef` too.

Comment (heppocogne) [reply core/object/class_db.h:385]: Sorry, that's probably because I made mistake when I tried to fix conflicts. 
And unfortunately, my branch seems to be broken now (cannot checkout). I will close this PR and make new one later if necessary.

**Comment by anvilfolk** [comment]
@vnen before I knew someone had already proposed this fix, I made a PR and @Calinou did a comparison of the binaries here #69607, and they're the same size. I think we need to look at memory footprint instead!

**Comment by neikeq** [comment]
This could have a negative on startup time, because the enum name needs to be calculated with a few string operations. Perhaps we could find a way to only calculate it once, instead of doing it for every constant.

https://github.com/godotengine/godot/blob/a75493091823020d858fabadbfa5994da0d658cb/core/variant/type_info.h#L278-L283

https://github.com/godotengine/godot/blob/a75493091823020d858fabadbfa5994da0d658cb/core/variant/type_info.h#L265-L268

https://github.com/godotengine/godot/blob/a75493091823020d858fabadbfa5994da0d658cb/core/variant/type_info.h#L249-L256

**Comment by YuriSizov** [comment]
Hey, @heppocogne, you need to rebase and squash again. You seem to have dragged unrelated changes into your PR, probably by merging master into it. Remember that in feature branches you shouldn't merge master, you should rebase those branches against the master instead.

**Comment by heppocogne** [comment]
@YuriSizov Thank you! I could manage to restore my repository.

**Comment by vnen** [comment]
@neikeq yeah, it would be interesting to profile that, maybe we can optimize it. That could potentially help with editor startup as well.

**Review by vnen — APPROVED** [review]
Would be interesting to profile startup to see the actual impact, but I believe this change is needed in any case to keep consistency between debug and release behavior.

**Comment by neikeq** [comment]
If this has a negative on startup time, perhaps we could cache the result from `enum_qualified_name_to_class_info_name` into a static field. The downside of being static is that it's kept alive until the program finishes, but honestly, adding it to ClassDB is almost the same in practice.
