### PR TITLE
Curve2d baking and sampling refactor

### LINKED ISSUE #69220: Curve3D get_closest_point broken
### Godot version

4.0.dev commit f9fa182abc5209671cb4fbadc2dc173157d6f939

### System information

windows 7 and windows 11

### Issue description

The Curve3D.get_closest_point function now returns weirdly discrete answers, instead of the closest points.

### Steps to reproduce

Make a node with a script and put this in the ready function.
```
func _ready():
	var frog : Curve3D = Curve3D.new()
	frog.add_point(Vector3(0.0, 0.0, 0.0), Vector3(0.0, -10.0, 0.0), Vector3(0.0, 10.0, 0.0))
	frog.add_point(Vector3(0.0, 100.0, 0.0), Vector3(0.0, -10.0, 0.0), Vector3(0.0, 10.0, 0.0))
	
	var pos = Vector3(0.2, 0.0, 0.0)
	
	for y in range(0.0, 100.0):
		pos.y = y
		var found = frog.get_closest_point(pos)
		print("at ", y, " => ", found)
```

The curve is just a straight line so it should return points with a Y value matching the Y value of the query.
Instead what you get is: 
```
at 0 => (0, 0, 0)
at 1 => (0, 50, 0)
at 2 => (0, 50, 0)
at 3 => (0, 50, 0)
at 4 => (0, 50, 0)
at 5 => (0, 50, 0)
.
.
.
at 74 => (0, 50, 0)
at 75 => (0, 50, 0)
at 76 => (0, 100, 0)
at 77 => (0, 100, 0)
.
.
.
```
I'm 99% sure the commit f9fa182abc5209671cb4fbadc2dc173157d6f939 introduced this one.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by xiongyaohua**
A follow up PR for https://github.com/godotengine/godot/pull/69043, applying the same change to `Curve2D`.

> The main change is to caculate tangent directly from bezier curve, without going
through discretized polyline, avoiding pitfalls of discretization.

~_Bug Squad Edited:_~
~Fixes #69220~
This PR dosen't fix #69220 per se,  but fix problems on `Curve2D`, which are similar with #69220

### CODE REVIEW

**Comment by xiongyaohua** [comment]
Fix a problem uncovered by https://github.com/godotengine/godot/issues/69220

**Comment by xiongyaohua** [comment]
The tests on Macos and Linux fail, but the log is confusing.

```
===============================================================================
./tests/scene/test_curve.h:220:
TEST CASE:  [Curve2D] Linear sampling should return exact value

./tests/scene/test_curve.h:232: ERROR: CHECK( pos.x == i ) is NOT correct!
  values: CHECK( 1 == 1 )
  logged: sample_baked should return exact value

./tests/scene/test_curve.h:232: ERROR: CHECK( pos.x == i ) is NOT correct!
  values: CHECK( 2 == 2 )
  logged: sample_baked should return exact value

./tests/scene/test_curve.h:232: ERROR: CHECK( pos.x == i ) is NOT correct!
  values: CHECK( 4 == 4 )
  logged: sample_baked should return exact value

===============================================================================
```

Shouldn't `CHECK(1 == 1)` pass?

File: scene/resources/curve.h [hunk 1]
```diff
@@ -181,7 +182,16 @@ class Curve2D : public Resource {
 
 	real_t bake_interval = 5.0;
 
+	struct Interval {
+		int idx;
+		real_t frac;
+	};
```
Comment (TokageItLab) [inline scene/resources/curve.h:188]: It probably should have been pointed out at the time of Curve3D, but it could have been written:
```cpp
typedef Pair<int, real_t> Interval;
```
Well, it is not a blocker.

File: scene/resources/curve.cpp [hunk 2]
```diff
@@ -1224,12 +1284,13 @@ void Curve2D::_bind_methods() {
...
 	ClassDB::bind_method(D_METHOD("get_baked_length"), &Curve2D::get_baked_length);
-	ClassDB::bind_method(D_METHOD("sample_baked", "offset", "cubic"), &Curve2D::sample_baked, DEFVAL(false));
-	ClassDB::bind_method(D_METHOD("sample_baked_with_rotation", "offset", "cubic", "loop", "lookahead"), &Curve2D::sample_baked_with_rotation, DEFVAL(false), DEFVAL(true), DEFVAL(4.0));
+	ClassDB::bind_method(D_METHOD("sample_baked", "offset", "cubic"), &Curve2D::sample_baked, DEFVAL(0.0), DEFVAL(false));
+	ClassDB::bind_method(D_METHOD("sample_baked_with_rotation", "offset", "cubic"), &Curve2D::sample_baked_with_rotation, DEFVAL(0.0), DEFVAL(false));
 	ClassDB::bind_method(D_METHOD("get_baked_points"), &Curve2D::get_baked_points);
 	ClassDB::bind_method(D_METHOD("get_closest_point", "to_point"), &Curve2D::get_closest_point);
 	ClassDB::bind_method(D_METHOD("get_closest_offset", "to_point"), &Curve2D::get_closest_offset);
 	ClassDB::bind_method(D_METHOD("tessellate", "max_stages", "tolerance_degrees"), &Curve2D::tessellate, DEFVAL(5), DEFVAL(4));
+	ClassDB::bind_method(D_METHOD("tessellate_even_length", "max_stages", "tolerance_length"), &Curve2D::tessellate_even_length, DEFVAL(5), DEFVAL(2.0));
```
Comment (TokageItLab) [inline scene/resources/curve.cpp:1293]: In Curve3D the default was 0.2 meter, does this mean that in Curve2D the default is 2.0 px? If this unit is px, it seems a bit small.

**Review by TokageItLab — APPROVED** [review]
It looks like more consistency between 2D and 3D. I commented some points of concern, but they are not blockers.

File: scene/resources/curve.cpp (hunk 2 above)
Comment (xiongyaohua) [reply scene/resources/curve.cpp:1293]: I will investigate the unit.
