### PR TITLE
OS::is_process_running function.

### LINKED ISSUE #1679: Improve `OS.kill()`'s error handling and add a method `is_process_running ` to check for running processes
**Describe the project you are working on:**
I'm working on a unit test plugin. It startes a test client in the background (hidden application)
The client comunicates over network connection with der server running by the plugin.
To run the test client i use the provided functionallity OS.excetute() with this arguments
[--no-window, -d, -s, res://addons/gdUnit/src/core/GdUnitClient.gd]
The client is closing/terminate by it self when all tests are done.
To manually stop a running test client i use the pid from OS.excetute() and send a kill OS.kill(<pid>) to terminate the client.
So good so far ;)

**Describe the problem or limitation you are having in your project:**
When i stop a running test client with OS.kill() results into OK for a success terminated process.
But when the client is already terminatet i have no chance to check if the client still running or not.
e.g. when i try now OS.kill() on a already terminated process i got only an generic error Error.FAILED 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
To improve the OS.kill() it should return a better error  
* add to the Error enum PID_NOT_EXIST
* replace the Error enum with and Error object where contains the error number and a human readable message

Add a new function to check if a process running by given PID
* `OS.is_process_running(<pid>) -> bool`
returns true when a process is running by given PID or false 

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
With this better error handling on OS.kill() we can check if the process already terminated for better control flow.
With OS.is_process(<pid>) we can verify if the process running or not.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
i found no way to check if an process is running by given PID

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is a missing function on the OS class to manage spawned processes

### PR DESCRIPTION
**Pull request by mdavisprog**
This PR adds the OS::is_process_running function that is exposed to script. The function has been implemented for Windows and Unix platforms and provides stubs for other platforms that are unsupported.

This is relevant to the godot-proposal [#1679](https://github.com/godotengine/godot-proposals/issues/1679).

A test project is provided that creates a process to run the 'ping' command and asserts that the is_process_running function properly returns the correct value.

[os-is-process-running-project.zip](https://github.com/godotengine/godot/files/6987421/os-is-process-running-project.zip)

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/1679.*

### CODE REVIEW

**Comment by Ev1lbl0w** [comment]
Came looking for this, this is very much needed for a project I'm working on, any chance of this being merged?

File: platform/javascript/os_javascript.cpp [hunk 1]
```diff
@@ -132,6 +132,10 @@ int OS_JavaScript::get_process_id() const {
 	ERR_FAIL_V_MSG(0, "OS::get_process_id() is not available on the HTML5 platform.");
 }
 
+bool OS_JavaScript::is_process_running(const ProcessID &p_pid) const {
+	ERR_FAIL_V_MSG(ERR_UNAVAILABLE, "OS::is_process_running() is not available on the HTML5 platform.");
```
Comment (akien-mga) [inline platform/javascript/os_javascript.cpp:136]: This should return `false`, not `ERR_UNAVAILABLE`.

File: platform/windows/os_windows.cpp [hunk 2]
```diff
@@ -507,6 +507,22 @@ int OS_Windows::get_process_id() const {
 	return _getpid();
 }
 
+bool OS_Windows::is_process_running(const ProcessID &p_pid) const {
+	if (!process_map->has(p_pid))
+		return false;
```
Comment (akien-mga) [inline platform/windows/os_windows.cpp:512]: Please use braces even for single line `if` statements (same below).

**Review by akien-mga — APPROVED** [review]

**Comment by mdavisprog** [comment]
Hello,

I have implemented the feedback and the branch is now rebased with the latest from master. If there is anything else that needs attention, let me know.

**Comment by akien-mga** [comment]
Thanks!

**Comment by MikeSchulze** [comment]
thanks

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
