### PR TITLE
Don't tint editor bottom panel icons when hovered or pressed

### LINKED ISSUE #98540: Colored icons are tinted with editor accent color
### Tested versions

v4.4.dev.custom_build [61accf060]

### System information

Godot v4.4.dev (61accf060) - macOS 14.5.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

The yellow circle of the output button indicates a warning:

However, when the button is pressed it turns pale green:

If the icon saturation is set to 2 it gets bright green:

This changes the meaning of the icon to the opposite and can be confusing to users because green means success. Which is why I'm reporting this as an issue

Same happens in log filter buttons:

Buttons with colored icons should have special treatment and never be tinted. Tint only makes sense for monochrome icons

### Steps to reproduce

Set icon saturation to 2. You can also experiment with different accent colors, personally I use a more saturated shade of blue which makes the problem more noticeable

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Calinou**
This prevents the error/warning icons from turning gray or green, making them hard to recognize. A similar mechanism is already used for EditorLog filter button icons.

This also fixes typos in FileDialog theme color assignment (`icon_color_pressed` instead of `icon_pressed_color`). The exposed theme item names remain the same. `icon_hover_pressed_color` is now set for EditorLogFilterButton as well, so you get a subtle visual feedback when hovering the buttons when they're already pressed.

This was mentioned in a proposal issue or discussion recently, but I can't find it right now.

- This closes #98540.

### Before

https://github.com/user-attachments/assets/a28ed40f-5ecc-4a22-8448-64b39725acd9

### After

https://github.com/user-attachments/assets/736198fc-12fd-40f2-822f-f9cf1d3e1b80

### CODE REVIEW

**Review by ryevdokimov — APPROVED** [review]
As a moderately colorblind person, I appreciate this 😂

File: editor/themes/editor_theme_manager.cpp [hunk 1]
```diff
@@ -1901,6 +1901,12 @@ void EditorThemeManager::_populate_editor_styles(const Ref<EditorTheme> &p_theme
 		p_theme->set_stylebox(SceneStringName(pressed), "BottomPanelButton", menu_transparent_style);
 		p_theme->set_stylebox("hover_pressed", "BottomPanelButton", main_screen_button_hover);
 		p_theme->set_stylebox("hover", "BottomPanelButton", main_screen_button_hover);
+		// Don't tint the icon even when in "pressed" state.
+		p_theme->set_color("icon_pressed_color", "BottomPanelButton", Color(1, 1, 1, 1));
+		Color icon_hover_color = p_config.icon_normal_color * (p_config.dark_theme ? 1.15 : 1.0);
+		icon_hover_color.a = 1.0;
```
Comment (MewPurPur) [inline editor/themes/editor_theme_manager.cpp:1907]: Is this meant to be the same thing as the lightened() function?

Comment (Calinou) [reply editor/themes/editor_theme_manager.cpp:1907]: Yes, more or less. It's slightly different but probably doesn't matter here.

That said, this may be better to harmonize in a different PR since we use color multiplication all over the place in EditorThemeManager right now.

**Review by passivestar — APPROVED** [review]
Tested, works as expected

Closes https://github.com/godotengine/godot/issues/98540

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
