### PR TITLE
RTL: Improve performance by using list iterators for item/paragraph removal

### LINKED ISSUE #76144: Extreme editor slowdown when using "Collapse Lines" with many different lines.
### Godot version

4.0.2

### System information

Ubuntu 22.04.1 LTS

### Issue description

When "Collapse Lines" in the output dock is enabled, having a lot of different lines in the output makes the editor extremely slow / unusable when trying to add new lines.

This has frozen Godot many times for me when I'm using tool scripts, as every time I get spammed with warnings and errors, the editor quickly becomes unusable, even if my output dock is closed.

### Steps to reproduce

Enable the Collapse Lines functionality. Then add this script to a node:
```gdscript
@tool
extends Node

func _ready() -> void:
	for i in 600:  # 600 different lines. You might have to raise this higher to notice the slowdown.
		print(i)

func _process(_delta: float) -> void:
	print(Time.get_ticks_msec() / 1000)  # Should add as many messages per line as the FPS.
```

You can close the scene, clear the output, and reopen it to restart the test or after adjusting the number of unique lines to be added initially. For me, the editor becomes unusable at around 2000 different lines and pretty much frozen at around 8000 different lines. This problem is completely absent without the Collapse Lines functionality.

### Minimal reproduction project

I provided a script

### PR DESCRIPTION
**Pull request by bruvzg**
Use proper `List` iterators instead of indices for `subitems` and iterate only over relevant sub-set of the items, should improve performance with large number of lines (but we probably should not use `List` at all, so it's a temporary fix).

Fixes https://github.com/godotengine/godot/issues/76144

### CODE REVIEW

**Comment by bruvzg** [comment]
Before (editor is not usable in about 50 sec and 7K messages, `remove_item` is the heaviest function):
Screenshot 2023-08-21 at 20 10 53

After (no visible slowdown after 20 min and 7.8M messages, nothing RTL related in the heaviest function list):
Screenshot 2023-08-21 at 20 02 05

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -3196,19 +3198,21 @@ bool RichTextLabel::remove_paragraph(const int p_paragraph) {
...
-		if (current->subitems[i]->line == p_paragraph) {
-			subitem_indices_to_remove.push_back(i);
+	Vector<List<Item *>::Element *> subitem_to_remove;
+	for (List<Item *>::Element *E = current->subitems.front(); current_frame->lines[p_paragraph].from->E; E = E->next()) {
+		if (E->get()->line == p_paragraph) {
+			subitem_to_remove.push_back(E);
+		} else {
+			break;
 		}
 	}
```
Comment (YuriSizov) [inline scene/gui/rich_text_label.cpp:3208]: I guess this could be simplified like so?

```suggestion
	for (const Item *E : current->subitems) {
		if (!current_frame->lines[p_paragraph].from->E || E->line != p_paragraph) {
			break;
		}

		subitem_to_remove.push_back(E);
	}
```

And below we would have `Item *` instead of `List<Item *>::Element`, removing all the `->get()`s.

The same cannot be done to the first for-loop, as it doesn't start at the front, and instead starts at `current_frame->lines[p_line].from->E`, unfortunately.

Comment (bruvzg) [reply scene/gui/rich_text_label.cpp:3208]: Actually, it should start from `current_frame->lines[p_line].from->E` as well.

Comment (bruvzg) [reply scene/gui/rich_text_label.cpp]: Updated.

**Review by YuriSizov — APPROVED** [review]
I think I can follow the logic here and it LGTM.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
