### PR TITLE
C#: Create script instance of reloaded scripts even if they're not tools

### LINKED ISSUE #64381: [3.5] C# EditorInspectorPlugin.CanHandle(Godot.Object) was not called properly
### Godot version

3.5.stable

### System information

Windows 11

### Issue description

When I followed the [inspector plugin tutorial](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/inspector_plugins.html?highlight=inspector), I found that after **changing** the edited property name and **rebuilding**, `EditorPlugin.Handles` will be called normally and `EditInspectorPlugin.CanHandle` will no longer be called. In gdscript they will all be called normally.

### Steps to reproduce

1. [inspector plugin tutorial](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/inspector_plugins.html?highlight=inspector)
2. Create a Node2D node named main
3. Attach main.cs to node main
```c#
public class main : Node2D
{
    [Export] public int a = 0;
}
```
4. Inspector is displayed normally
5. Change the property name(a -> b) and build
```c#
public class main : Node2D
{
    [Export] public int b = 0;
}
```
6. The Inspector panel will not appear with a random number button

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by raulsntos**
Fixes https://github.com/godotengine/godot/issues/64381 and the exception part of https://github.com/godotengine/godot/issues/65032

As discussed in Rocket Chat with @neikeq this is a proof of concept that instantiates the reloaded scripts even if they don't have the `[Tool]` attribute for cases where a non-Tool class was instantiated by the user from a Tool class.

Without this PR these classes are replaced by a `PlaceHolderScriptInstance` when rebuilding the assemblies and they never turn back into a `CSharpInstance` which means their methods are no longer called by the editor for example in the case of `EditorInspectorPlugin::_CanHandle` (see https://github.com/godotengine/godot/issues/64381).

Now, if a class is ever instantiated in the editor we avoid creating a `PlaceHolderScriptInstance` but if it ever becomes one, we will always try to replace it with a `CSharpInstance` unless the class had the `[Tool]` attribute before the reload but was removed so after the reload the class is no longer a Tool, in this case because the user explicitly removed the attribute so the intention is clear that the class must no longer be instantiated and therefore we replace the instance with a placeholder and no longer consider it when replacing placeholders with instances.

### CODE REVIEW

File: modules/mono/csharp_script.cpp [hunk 1]
```diff
@@ -952,7 +952,12 @@ void CSharpLanguage::reload_assemblies(bool p_soft_reload) {
 				CRASH_COND(si != nullptr);
 #endif
 				// Re-create script instance
-				obj->set_script(script); // will create the script instance as well
+				obj->set_script(script);
+				// Create the script instance as well, by-passing the tool requirement in set_script
+				ScriptInstance *script_instance = script->instance_create(obj);
```
Comment (neikeq) [inline modules/mono/csharp_script.cpp:957]: The script could be marked `[Tool]`, which means the `set_script` above could succeed at creating a new instance. As such, we would be creating a second one unnecessarily. This should be inside a `if (obj->get_script_instance() != nullptr)`

Comment (neikeq) [reply modules/mono/csharp_script.cpp:957]: All right, so the correct solution would be to move the `obj->set_script(script);` line to an `else {` block if the `script_instance` you created is `nullptr`. `set_script_instance` already takes care of setting the script resource as well.

**Comment by neikeq** [comment]
One thing to keep in mind is that with this change, if a script was instantiated because it was marked `[Tool]` and that attribute is removed, after rebuilding it would be instantiated again. That may not be what the user intended.
If we want to avoid that, we would need to keep a flag like `was_tool` before unloading to handle this scenario. However, if we're fine with that behavior, then this is fine.

File: modules/mono/csharp_script.cpp (hunk 1 above)
Comment (neikeq) [reply modules/mono/csharp_script.cpp]: Sorry, it seems I edited my comment and wrote the update too late. Your new change works, but it's still creating an unnecessary placeholder instance. The way I describe above should work.

**Comment by raulsntos** [comment]
Also, I don't really understand what case is this but we are only re-creating the script when the marked with `[Tool]` so should it be changed too?

https://github.com/godotengine/godot/blob/daec089c30ba5f7128eafa6b766abc1d8d3e8a72/modules/mono/csharp_script.cpp#L928-L950

**Comment by neikeq** [comment]
No, those are placeholder instances. If you were to re-create a C# script instance for them, that would be like turning every single script into a tool script after reloading.
The scripts we want to reload shouldn't have placeholder instances any way, as they are either tool scripts or scripts instantiated manually.

File: modules/mono/csharp_script.cpp [hunk 2]
```diff
@@ -951,8 +951,14 @@ void CSharpLanguage::reload_assemblies(bool p_soft_reload) {
 #else
 				CRASH_COND(si != nullptr);
 #endif
-				// Re-create script instance
-				obj->set_script(script); // will create the script instance as well
+
+				// Re-create the script instance, bypassing the tool requirement
```
Comment (neikeq) [inline modules/mono/csharp_script.cpp:955]: Can you explain in the comment explaining why this was done? I can already see myself in two years confused about this code. A "see" link to this PR would be enough.

Comment (neikeq) [inline modules/mono/csharp_script.cpp:955]: Can you explain in the comment why this was done? I can already see myself in two years confused about this code. A "see" link to this PR would be enough.

**Review by neikeq — APPROVED** [review]

**Comment by raulsntos** [comment]
> If we want to avoid that, we would need to keep a flag like `was_tool` before unloading to handle this scenario. However, if we're fine with that behavior, then this is fine.

I don't consider this behavior acceptable, since an user could have a node script with the `[Tool]` attribute running in the scene and then when removing the attribute the node's script will still be running in the scene with no way to stop it other than re-opening the editor. This will surely result in more confused users than the ones confused by the issue this PR is intending to solve.

So I have implemented the `was_tool` flag you describe to try and avoid the regression described, let me know if you think it's too hacky.

**Review by neikeq — APPROVED** [review]

File: modules/mono/csharp_script.h [hunk 3]
```diff
@@ -72,6 +72,7 @@ class CSharpScript : public Script {
 	friend class CSharpLanguage;
 
 	bool tool = false;
+	bool was_tool = false;
```
Comment (neikeq) [inline modules/mono/csharp_script.h:75]: The field could be in `#ifdef GD_MONO_HOT_RELOAD`.

**Comment by raulsntos** [comment]
I think it should be good now, it no longer crashes and always reloads scripts if they were ever instantiated unless the user explicitly removes the `[Tool]` attribute.

**Comment by akien-mga** [comment]
Thanks!
