### PR TITLE
[PopupMenu] Fix submenu item not popping on mouse enter

### LINKED ISSUE #70361: PopupMenu does not highlight items on mouse over if a submenu is opened
### Godot version

v4.0.beta.custom_build [2a04b18d3] (also present in the v4.0 official beta build)

### System information

Windows 10

### Issue description

PopupMenu does not highlight items on mouse over if a submenu is opened:
godot_popup_menu

For comparison, here is an example of a popup menu in vscode to show how it should behave (items are highlighted even if the submenu is opened):
vscode_popup_menu

### Steps to reproduce

Open a PopupMenu and a submenu in the editor, and mouse over items in the popup_menu while the submenu is opened.

### Minimal reproduction project

Any project.

### LINKED ISSUE #77246: PopupMenu ignores mouse hover to adjacent item after sub menu opened until jiggled
### Godot version

4.1dev (6d7413b)

### System information

MacOS M1

### Issue description

Moving the mouse from a `PopupMenu` open sub menu item to another sub menu item is ignored until the mouse is jiggled. This is probably related to [#70361](https://github.com/godotengine/godot/issues/70361)

Inhibiting the `minimum_lifetime_timer` in popup_menu.cpp (effectively setting the timeout to zero) seems to mostly eliminate the issue. Keyboard navigation still works as expected, so I would propose getting rid of the lifetime timer completely.

I am wondering why there is a sub menu lifetime timer at all, because the sub menu should close instantly as soon as the mouse moves to another item. For example, this is how at least MacOS behaves. Is there a rational for the lifetime timer I'm not considering?

https://github.com/godotengine/godot/assets/33969780/4d1aa4d5-50d8-40e8-98fe-49e55f0cf170

### Steps to reproduce

See MRP below.

### Minimal reproduction project

[popup_issues.zip](https://github.com/godotengine/godot/files/11518515/popup_issues.zip)

### LINKED ISSUE #102081: Menu options are not detected correctly.
### Tested versions

v4.4.beta1.official [d33da79d3]

### System information

w10 64

### Issue description

When moving the cursor over menu options that have additional sub-options appearing automatically in a small menu to the right, the main menu options are not properly detected as the cursor moves over them.

As shown in the video, the cursor is positioned over an option, but an additional movement is required for the menu to detect the cursor's position and highlight the intended option.

https://github.com/user-attachments/assets/b92fe306-5aec-4280-bf7a-f61a56f12f64

### Steps to reproduce

See the video

### Minimal reproduction project (MRP)

...

### PR DESCRIPTION
**Pull request by Koyper**
Fixes #77246, Fixes #102081 and Fixes #70361.

This PR fixes the issue where a submenu would not open on hover until the mouse was jiggled. It also adds an additional delay to close a submenu when the mouse is moving to the right and goes across another submenu item. This provides time to reach a long submenu without it being closed by touching another submenu item.

[Edit: The issue below went away after the push eliminating `minimum_lifetime_timer`. See comments below regarding probable source of the issue.]

<s>There were several things confounding the issue, one of which is mysterious. In `_activate_submenu()` calling `submenu_pum->popup()` would intermittently fail, leaving the submenu invisible, even when `submenu_pum->is_visible()` shows as true. This is fixed by a `process_frame`, so I added a hack to do this, but I'm sure there is a better way. There should be a fix maybe in `Window` that would detect the incomplete rendering?

Here's the line that can be improved:
```
submenu_pum->popup();
// Unpredictably, some submenus won't show even after popup without a process_frame.
get_tree()->connect("process_frame", callable_mp(this, &PopupMenu::_activate_submenu).bind(p_over, p_by_keyboard), CONNECT_ONE_SHOT);
```</s>

### CODE REVIEW

**Comment by Koyper** [comment]
This `const` doesn't seem to be used anywhere - can it be removed from `popup_menu.h`? It also shows up in `option_button.h`.
```
	// ATTENTION: This is used by the POT generator's scene parser. If the number of properties returned by `_get_items()` ever changes,
	// this value should be updated to reflect the new size.
	static const int ITEM_PROPERTY_SIZE = 10;
```

File: scene/gui/popup_menu.cpp [hunk 1]
```diff
@@ -402,8 +405,9 @@ void PopupMenu::_activate_submenu(int p_over, bool p_by_keyboard) {
 			}
 		}
 	}
-
 	submenu_pum->popup();
+	// Unpredictably, some submenus won't show even after popup without a process_frame.
+	get_tree()->connect("process_frame", callable_mp(this, &PopupMenu::_activate_submenu).bind(p_over, p_by_keyboard), CONNECT_ONE_SHOT);
```
Comment (WhalesState) [inline scene/gui/popup_menu.cpp]:
```suggestion
	callable_mp(this, &PopupMenu::_activate_submenu).bind(p_over, p_by_keyboard).call_deferred()
```

I wonder if deferring `submenu->popup()` would fix this
```c++
callable_mp(submenu_pum, &PopupMenu::popup).call_deferred();
```

Comment (Koyper) [reply scene/gui/popup_menu.cpp]: I tried the call deferred per below and it doesn't prevent the "ghost" submenu issue like the `process_frame` statement:
```
callable_mp(submenu_pum, &PopupMenu::popup).bind(Rect2i(submenu_pos, submenu_size)).call_deferred();
```
What is the trick to yield for a `process_frame` or `RenderingServer.frame_post_draw`? I couldn't find a code example for this. I still suspect this is an issue with `Window` because `is_visible()` should never be true when it isn't.

Here's something I don't understand I'm curious about. In `_activate_submenu()` there is this statement:
```
	PopupMenu *submenu_pum = Object::cast_to<PopupMenu>(submenu_popup);
```
That recasts `PopupMenu` to another `Popupmenu`, which seems unneccessary. I tried skipping this step and using `submenu_popup` instead of `submenu_pum` and it works but the submenu won't resize correctly and has an extra margin at the bottom. Why is this step necessary and why does it fix that issue? Getting rid of it also doesn't make the ghosting issue go away, so that's not the source of the problem.

Comment (WhalesState) [reply scene/gui/popup_menu.cpp]: > I tried the call deferred per below and it doesn't prevent the "ghost" submenu issue like the `process_frame` statement:
> 
> ```
> callable_mp(submenu_pum, &PopupMenu::popup).bind(Rect2i(submenu_pos, submenu_size)).call_deferred();
> ```

Have you tried this ? 
```c++
callable_mp(this, &PopupMenu::_activate_submenu).bind(p_over, p_by_keyboard).call_deferred()
```

> What is the trick to yield for a `process_frame` or `RenderingServer.frame_post_draw`? I couldn't find a code example for this. I still suspect this is an issue with `Window` because `is_visible()` should never be true when it isn't.

Reminds me of using `await get_tree().process_frame` twice in GDScript to grab the window focus after calling `popup()` because `window.grab_focus.call_deferred()` didn't work even after awaiting once.

> Here's something I don't understand I'm curious about. In `_activate_submenu()` there is this statement:
> 
> ```
> 	PopupMenu *submenu_pum = Object::cast_to<PopupMenu>(submenu_popup);
> ```

This code is old and wasn't cleaned up, it shouldn't return a new pointer, the Item::submenu was a `String` referring to child name, and it was used like that.

```c++
Node *n = get_node_or_null(items[p_over].submenu);
Popup *submenu_popup = Object::cast_to<Popup>(n);
```

Comment (KoBeWi) [reply scene/gui/popup_menu.cpp]: Deferred calls happen at the end of the frame, while `process_frame` is sent at the beginning. This might be causing the difference.

Comment (Koyper) [reply scene/gui/popup_menu.cpp]: Okay, I removed the cobweb code where it was doing the duplicate cast to the same pointer, and did a few more tests looking at the calls to `_activate_submenu()`. Turns out that for those submenus that otherwise would not show, it took two additional calls to `_activate_submenu()` before they became visible. I think it's actually a reasonable solution at this point to use the one shot signal, until someone figures out what's happening in `Window` that prevents the popups from showing on the first call.

**Comment by KoBeWi** [comment]
Doesn't seem to fix the issue

https://github.com/user-attachments/assets/d029d0d3-7a9a-4842-a834-9287389a2398

**Comment by WhalesState** [comment]
It can be fixed by storing the next submenu that should show and once the timer timeouts we show it here after we hide the previous submenu.

```c++
void PopupMenu::_minimum_lifetime_timeout() {
	close_allowed = true;
	// If the mouse still isn't in this popup after timer expires, close.
	if (!activated_by_keyboard && !get_visible_rect().has_point(get_mouse_position())) {
		_close_pressed();
	}
}
```

Or by having smaller wait time for both timers, I have tried `0.01` and it's more user friendly than `0.3`.

```c++
	submenu_timer = memnew(Timer);
	submenu_timer->set_wait_time(0.3);
	submenu_timer->set_one_shot(true);
	submenu_timer->connect("timeout", callable_mp(this, &PopupMenu::_submenu_timeout));
	add_child(submenu_timer, false, INTERNAL_MODE_FRONT);

	minimum_lifetime_timer = memnew(Timer);
	minimum_lifetime_timer->set_wait_time(0.3);
	minimum_lifetime_timer->set_one_shot(true);
	minimum_lifetime_timer->connect("timeout", callable_mp(this, &PopupMenu::_minimum_lifetime_timeout));
	add_child(minimum_lifetime_timer, false, INTERNAL_MODE_FRONT);

```

Edit: `minimum_lifetime_timer` is the issue, but `submenu_timer` can be changed to `0.1` instead of `0.01` to avoid showing it while moving the mouse over the items fast.

**Comment by WhalesState** [comment]
Also this may be related to why the popup menu didn't receive the motion event when the mouse entered.

* https://github.com/godotengine/godot/issues/110093

**Comment by Koyper** [comment]
> Doesn't seem to fix the issue

The whack-a-mole continues - thanks for finding that. If you set the submenu timer to 0.1 does it still act the same per @WhalesState?

Is there a movement sequence you can replicate this on an Editor menu? I will set this up for myself and go back on the hunt.

> Edit: minimum_lifetime_timer is the issue, but submenu_timer can be changed to 0.1 instead of 0.01 to avoid showing it while moving the mouse over the items fast.

I agree that 0.1 feels better - any reason we can't set the default to 0.1 instead of 0.3?

**Comment by KoBeWi** [comment]
> thanks for finding that

I just tested with the MRP from the issue you linked 🙃

> If you set the submenu timer to 0.1 does it still act the same

Yes.

**Comment by Koyper** [comment]
> I just tested with the MRP from the issue you linked 🙃

That's pretty funny! My notoriety must be in reinventing the wheel. I've been testing with a much fancier menu that doesn't exhibit the issues as obviously for an as yet unknown reason.

**Comment by Koyper** [comment]
> I just tested with the MRP from the issue you linked 🙃

Okay, go to project settings and disable `embed_subwindows` and everything works perfectly. I should have tested this properly with embedded subwindows. This might indeed be related to something like #110093.

>Also this may be related to why the popup menu didn't receive the motion event when the mouse entered.

There seems to be an issue regarding incorrect determination of the mouse leaving the safe area.

**Comment by WhalesState** [comment]
> There seems to be an issue regarding incorrect determination of the mouse leaving the safe area.

Yes, The issue is that the parent window only process one event while another window has focus, but when you disable embedding sub-windows they become just fake windows extending `Control` node so the mouse events works fine.

**Comment by WhalesState** [comment]
> Okay, go to project settings and disable `embed_subwindows` and everything works perfectly. I should have tested this properly with embedded subwindows. This might indeed be related to something like #110093.

Also this issue is in both embedded and non-embedded windows so maybe you forgot to revert back the timer changes while testing or you test with the changes from this PR, i have tested with editor submenus in master and the issue also exists there by default and the editor is not embedding subwindows.


https://github.com/user-attachments/assets/8ad194e4-2576-43cd-b494-3deca71e537d

**Comment by WhalesState** [comment]
Also check what happens here, the root window receives one mouse event when another window is focused but when you focus it no other window receives any input, the settings window is exclusive so the parent window shouldn't receive any input at all.

https://github.com/user-attachments/assets/0c81e106-3dae-4615-b78d-c4fc8e8dbc79

**Comment by Koyper** [comment]
> i have tested with editor submenus in master and the issue also exists there by default and the editor is not embedding subwindows.

The PR fixed the issue with non-embedded windows and the Editor, though I found a couple of bugs there that I'm taking care of. What I've got working now for embedded widows is to emit the `popup_hide` signal when a submenu closes, which then creates an `InputEventMouseMotion` event that forces the parent menu to process a mouse movement over the currently hovered item. This seems to offer a solution for the time being. I will set the default submenu wait time to `0.1` and we can test it out to see if it's satisfactory. I think the ergonomics are better with the faster response.

What you demonstrated regarded no window receiving input, might certainly be related to the closed submenu blocking input to the parent menu, which is the source of the blocked submenu issue. This is a deeper problem with `Window` - fixing that might also take care of the "hung" activation of submenus that requires that callable loop to fix.

**Comment by Koyper** [comment]
After a lot of frustration, I finally had to get rid of the `minimum_lifetime_timer` as it was the source of many of the issues. I replaced it with `close_suspended_timer`, which is only set in the parent menu, whereas `minimum_lifetime_timer` was being set in each submenu. The code now enforces submenus only being activated after any open submenus are closed. This eliminated the need for the hack double-calling `_activate_submenu()`, which I believe was being caused by a race condition where a prior submenu was in a closing state while the next was being activated.

The other major problem was the fixes for issues with embedded vs. non-embedded subwindows were completely different. The only way to get embedded subwindows to work was connecting `popup_hide` to spoof a mouse input on the hovered menu item that's triggered by the submenu closing.

When the mouse moves out of a submenu item, it's last relative motion state inside its menu item is preserved, and if it's moving into the lower right quadrant (or lower left if right-to-left layout), it will start the `close_suspended_timer` which runs for `0.5` seconds to allow the mouse to sweep into the open submenu across other menu items without triggering them to open or close the open submenu. This timing is modeled after the behavior of MacOS system menus, which seems reasonable.

Finally, I reduced the default submenu delay time from `0.3` to `0.1` seconds, as that feels more natural and responsive, and the fixes above make it unnecessary to prolong the opening of the submenu.

File: scene/gui/popup_menu.cpp [hunk 2]
```diff
@@ -759,24 +763,45 @@ void PopupMenu::_input_from_window_internal(const Ref<InputEvent> &p_event) {
 	}
 }
 
-void PopupMenu::_mouse_over_update(const Point2 &p_over) {
-	int over = _get_mouse_over(p_over);
-	int id = (over < 0 || items[over].separator || items[over].disabled) ? -1 : (items[over].id >= 0 ? items[over].id : over);
+bool PopupMenu::_is_mouse_moving_right(const Vector2 &p_relative) const {
```
Comment (KoBeWi) [inline scene/gui/popup_menu.cpp]: This needs to account for RTL layout.

**Comment by Koyper** [comment]
This push adds support for right-to-left layouts for the direction testing of mouse movements toward an open submenu.

File: scene/gui/popup_menu.cpp [hunk 3]
```diff
@@ -346,8 +346,12 @@ int PopupMenu::_get_mouse_over(const Point2 &p_over) const {
 void PopupMenu::_activate_submenu(int p_over, bool p_by_keyboard) {
 	PopupMenu *submenu_popup = items[p_over].submenu;
 	if (submenu_popup->is_visible()) {
```
Comment (WhalesState) [inline scene/gui/popup_menu.cpp]:
```suggestion
	ERR_FAIL_COND_MSG(submenu_popup->is_visible(), "Activate submenu should not be called on an open submenu.");
```

File: scene/gui/popup_menu.cpp [hunk 4]
```diff
@@ -753,24 +761,49 @@ void PopupMenu::_input_from_window_internal(const Ref<InputEvent> &p_event) {
...
+	const Vector2 horiz_quadrant = Vector2(-4, 1).normalized();
+	// If the mouse moves right into the LR quadrant rotated 14 degrees (atan of 1/4) counter-clockwise.
+	// The vectors are mirrored in the vertical axis for right-to-left layouts.
+	// NOTE: Upward y values are negative, so the test vectors are the mirror image of the target mouse quadrant.
+	if (is_layout_rtl() && vert_quadrant_rtl.dot(p_relative.normalized()) > 0 && horiz_quadrant_rtl.dot(p_relative.normalized()) < 0) {
+		return true;
+	} else if (vert_quadrant.dot(p_relative.normalized()) > 0 && horiz_quadrant.dot(p_relative.normalized()) < 0) {
+		return true;
+	}
+	return false;
```
Comment (kitbdev) [inline scene/gui/popup_menu.cpp]: Surely there is a better way to do this than checking dot products of multiple vectors. You could use `Math::atan2(p_relative.y, p_relative.x)` to get the angle and check if it is within a certain range.

There is a bigger problem though, the submenu is not always to the right for left-to-right and vice-versa, it depends on if there is enough space for it to the right, if there isn't it will go to the left side instead. We probably need to check the actual submenu rect, and check if the mouse is moving toward it using each of its corners.

Comment (Koyper) [reply scene/gui/popup_menu.cpp]: That's a good call regarding the need for locating the submenu before testing movement direction, so I'll take care of that. EDIT: I actually think using atan would not be any simpler than using dot product, because you still have to deal with quadrants. I would prefer to leave this approach in place if that's okay.

**Comment by Koyper** [comment]
This push handles submenu positions where the right-to-left layout setting is overwritten because of inadequate screen space for the submenu, so the submenu position is left vs. right or the converse.

**Comment by kitbdev** [comment]
I tried visualizing the dot products and different menus. Submenus can be above the cursor when tall near the bottom, and the calculated range doesn't match:

image

Moving toward the top of this submenu closes it.

I found references of how this is done elsewhere https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown , https://codepen.io/popov654/pen/XyGXzb
It shows using a triangle between the mouse and the relevant corners of the submenu, and is much more accurate.

File: scene/gui/popup_menu.cpp (hunk 4 above)
Comment (kitbdev) [reply scene/gui/popup_menu.cpp]: I don't see how quadrants are needed. The math just becomes a range check vs some constants, `if (angle >= Math::atan2(-1,4) && angle =< Math::atan2(4,1))`. So it is much simpler than getting 2 dot products and checking above and below them.

**Comment by Koyper** [comment]
> It shows using a triangle between the mouse and the relevant corners of the submenu, and is much more accurate.

I like this idea! I had not considered that case of the menu originating near the bottom of the screen. I had assumed the submenu would always project below the menu item. Shouldn't be too much work to calculate those vectors aiming at the corners. Nice also to see the quadrant orientation - thanks.

This also future-proofs having submenus that pop with the selected submenu choice aligned with the parent menu item. It's something we don't do now, but would be nice to implement someday.

**Comment by Koyper** [comment]
This push improves the mouse movement direction detection so the detection angles are based on the position and height of the submenu.

I included debug draw lines to visualize the detection angles from the mouse position, which you can see in the screen recordings below. The detection now works correctly for both left and right side submenus, and submenus shifted by any amount vertically.



https://github.com/user-attachments/assets/7257e98e-7a0e-4791-90d2-d26457b2e55a




https://github.com/user-attachments/assets/e5b970f2-4a0e-4d88-aee4-9bb98d9bf582

**Comment by YeldhamDev** [comment]
The PR makes submenus close instantly if the cursor leaves the item.

**Comment by Koyper** [comment]
> The PR makes submenus close instantly if the cursor leaves the item.

The intended behavior is that the submenu stays open for 0.5 seconds if you are moving the mouse toward the submenu upon exiting the parent menu item. Otherwise, the submenu should close instantly when exiting the parent item, because you are moving downward or otherwise away from the submenu. Are you observing something else like a bug?

Do you see some other behavior other than what's shown in the last screen recordings above?

**Comment by YeldhamDev** [comment]
> The intended behavior is that the submenu stays open for 0.5 seconds if you are moving the mouse toward the submenu upon exiting the parent menu item. Otherwise, the submenu should close instantly when exiting the parent item, because you are moving downward or otherwise away from the submenu. Are you observing something else like a bug?

The actual feeling is that the submenu closes faster than the current `master`. It also feels that the submenu _opens_ faster as well.

**Comment by YeldhamDev** [comment]
- Moving the cursor to the submenu makes the hover in the parent item blink, because now when the cursor is in the border it removes the hover.
- Moving the cursor around the border while a submenu is open causes a crash.

**Comment by Koyper** [comment]
> * Moving the cursor to the submenu makes the hover in the parent item blink, because now when the cursor is in the border it removes the hover.
> 
Thanks for comments. I'm working on a fix for this - the parent item also can blink when the mouse moves across another item on the way to the submenu.

>* Moving the cursor around the border while a submenu is open causes a crash.
>
I can't reproduce this - what platform is it happening on? Is this on an Editor menu?

**Comment by YeldhamDev** [comment]
> I can't reproduce this - what platform is it happening on? Is this on an Editor menu?

Just go up-and-down with the cursor in the border while the submenu is open, should crash eventually.

image

**Comment by Koyper** [comment]
Will do.

By-the-way, the new default popup total delay is `0.23` seconds, which is the delay setting of `0.2` seconds, plus the `30` msec delay added before determining the mouse movement vector away from the parent item. This made the vector much more reliable. I more carefully measured the delays on MacOS and now the popup behaves just like it.

**Comment by Koyper** [comment]
> Just go up-and-down with the cursor in the border while the submenu is open, should crash eventually.

Do you get any log output on crash? This might be OS-dependent. I'll see if I can reproduce it on Windows.

**Comment by YeldhamDev** [comment]
```
ERROR: FATAL: Index p_index = -1 is out of bounds (size() = 14).
   at: get (./core/templates/cowdata.h:193)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.6.dev.custom_build (e0cb03a3710e97d4f8b9201ceb1a36c7adac8eeb)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x1a070) [0x7f90e1cb6070] (??:0)
[2] CowData<PopupMenu::Item>::get(long) const (/var/home/michael/Development/Projects/godot/core/templates/cowdata.h:193 (discriminator 13))
[3] Vector<PopupMenu::Item>::operator[](long) const (/var/home/michael/Development/Projects/godot/core/templates/vector.h:134)
[4] PopupMenu::_activate_submenu(int, bool) (/var/home/michael/Development/Projects/godot/scene/gui/popup_menu.cpp:348 (discriminator 1))
[5] PopupMenu::_submenu_timeout() (/var/home/michael/Development/Projects/godot/scene/gui/popup_menu.cpp:467)
[6] void call_with_variant_args_helper<PopupMenu>(PopupMenu*, void (PopupMenu::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/var/home/michael/Development/Projects/godot/core/variant/binder_common.h:228)
[7] void call_with_variant_args<PopupMenu>(PopupMenu*, void (PopupMenu::*)(), Variant const**, int, Callable::CallError&) (/var/home/michael/Development/Projects/godot/core/variant/binder_common.h:338)
[8] CallableCustomMethodPointer<PopupMenu, void>::call(Variant const**, int, Variant&, Callable::CallError&) const (/var/home/michael/Development/Projects/godot/core/object/callable_method_pointer.h:107)
[9] Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/var/home/michael/Development/Projects/godot/core/variant/callable.cpp:57)
[10] Object::emit_signalp(StringName const&, Variant const**, int) (/var/home/michael/Development/Projects/godot/core/object/object.cpp:1342)
[11] Node::emit_signalp(StringName const&, Variant const**, int) (/var/home/michael/Development/Projects/godot/scene/main/node.cpp:4166)
[12] Error Object::emit_signal<>(StringName const&) (/var/home/michael/Development/Projects/godot/core/object/object.h:967)
[13] Timer::_notification(int) (/var/home/michael/Development/Projects/godot/scene/main/timer.cpp:68)
[14] Timer::_notification_forwardv(int) (/var/home/michael/Development/Projects/godot/scene/main/timer.h:36)
[15] Object::_notification_forward(int) (/var/home/michael/Development/Projects/godot/core/object/object.cpp:995)
[16] Object::notification(int, bool) (/var/home/michael/Development/Projects/godot/core/object/object.h:921)
[17] SceneTree::_process_group(SceneTree::ProcessGroup*, bool) (/var/home/michael/Development/Projects/godot/scene/main/scene_tree.cpp:1201)
[18] SceneTree::_process(bool) (/var/home/michael/Development/Projects/godot/scene/main/scene_tree.cpp:1274 (discriminator 2))
[19] SceneTree::process(double) (/var/home/michael/Development/Projects/godot/scene/main/scene_tree.cpp:708)
[20] Main::iteration() (/var/home/michael/Development/Projects/godot/main/main.cpp:4768 (discriminator 3))
[21] OS_LinuxBSD::run() (/var/home/michael/Development/Projects/godot/platform/linuxbsd/os_linuxbsd.cpp:991 (discriminator 1))
[22] ./bin/godot.linuxbsd.editor.dev.x86_64(main+0x1bd) [0x4232f5] (/var/home/michael/Development/Projects/godot/platform/linuxbsd/godot_linuxbsd.cpp:118)
[23] /lib64/libc.so.6(+0x3575) [0x7f90e1c9f575] (??:0)
[24] /lib64/libc.so.6(__libc_start_main+0x88) [0x7f90e1c9f628] (??:0)
[25] ./bin/godot.linuxbsd.editor.dev.x86_64(_start+0x25) [0x406ab5] (??:?)
-- END OF C++ BACKTRACE --
================================================================
```

**Comment by Koyper** [comment]
Excellent - this means it's not a platform issue, and I know where to look...

File: scene/gui/popup_menu.cpp [hunk 5]
```diff
@@ -763,27 +776,47 @@ void PopupMenu::_input_from_window_internal(const Ref<InputEvent> &p_event) {
 	}
 }
 
-void PopupMenu::_mouse_over_update(const Point2 &p_over) {
-	int over = _get_mouse_over(p_over);
-	int id = (over < 0 || items[over].separator || items[over].disabled) ? -1 : (items[over].id >= 0 ? items[over].id : over);
+bool PopupMenu::_is_mouse_moving_toward_submenu(const Vector2 &p_relative, bool is_submenu_left, const Vector2 &p_mouse_position, const Vector<Point2> &p_active_submenu_target_line) const {
```
Comment (AThousandShips) [inline scene/gui/popup_menu.cpp]:
```suggestion
bool PopupMenu::_is_mouse_moving_toward_submenu(const Vector2 &p_relative, bool p_is_submenu_left, const Vector2 &p_mouse_position, const Vector<Point2> &p_active_submenu_target_line) const {
```

**Comment by Koyper** [comment]
I've fixed the crashing and other issues, and added several error checks to prevent any similar crashes. The crash culprit was the submenu timer was running as another submenu was closed. I'm trying to wrap things up regarding the parent item highlight flickering, and ran into this bug - #112358. I can work around it, but it would be nice to sort out.

**Comment by Koyper** [comment]
This push requires that PR [[macOS] Fix mouse enter events sent to wrong popup window. #112383](https://github.com/godotengine/godot/pull/112383) is merged, because `NOTIFICATION_WM_MOUSE_EXIT` unconditionally redraws the popup on every exit notification.

I put the logic to keep the parent submenu item highlighted for the duration of the submenu in `_draw_items`, which simplified some things and eliminated a lot of redraws while hovering over the submenu.

Pending review, I believe everything is working well.

**Comment by YeldhamDev** [comment]
Is the font color changing to non-hovered when exiting the parent popup intentional?

image

**Comment by Koyper** [comment]
I didn't deliberately intend that, but I thought it looked natural since it reflects the cursor moving off the item. I can make it stay on the hovered state if you think that's the way to go. Also, what are your thoughts about the font color as the cursor moves across the parent item below the submenu item on the way to the submenu? Right now, it flickers onto the hovered font color momentarily. This does reflect what the cursor is doing, so there's an argument for leaving it this way; the argument against is it could be perceived as unintentional.

**Comment by YeldhamDev** [comment]
I think it's better to just leave the hovered font color with the highlighted item.

Also, found another issue: The submenus are slightly offset.
|Before|After|
|-|-|
|Screenshot_20251104_180721|Screenshot_20251104_180840|

**Comment by Koyper** [comment]
I’ll go ahead and keep the font color state synced with the hovered style box. That’s odd about the offset - I’ll fix that. I also need to tweak some things to properly handle cascading submenus.

**Comment by Koyper** [comment]
This push fixes the font color hover state mismatch with the item hover state, fixes the submenu vertical pixel offset error, and properly closes secondary submenus when their parent submenu closes. Secondary submenus now also close when the parent item of the first submenu is hovered.

**Comment by YeldhamDev** [comment]
Alright, one last problem that I found with submenus item at the bottom: when the mouse leaves and re-enters, the submenu can randomly re-open or not.

[Screencast_20251105_161941.webm](https://github.com/user-attachments/assets/e0ed1b12-c5e2-4a8c-b1c0-1f68ca94a75e)

**Comment by Koyper** [comment]
> Already, one last problem that I found with submenus item at the bottom: when the mouse leaves and re-enters, the submenu can randomly re-open or not.

This one really had me chasing my tail, fighting the intended behavior of the autohide areas. The solution was actually simply removing the thin autohide area when the item is either at the very top or very bottom. Hopefully this will get us over the line!

**Review by YeldhamDev — APPROVED** [review]
Seems like everything is in order. Fantastic work!

One final recommendation, however: I think this behavior of the cursor's arc deciding if the submenu stays open or not should be documented somewhere.

File: scene/gui/popup_menu.cpp [hunk 6]
```diff
@@ -987,28 +1039,45 @@ void PopupMenu::_draw_items() {
...
+}
+
+void PopupMenu::_close_or_suspend() {
+	if (this_submenu_index != -1) { // Is a submenu.
+		PopupMenu *pp = Object::cast_to<PopupMenu>(get_parent()); // Parent popup.
+		if (pp->submenu_mouse_exited_ticks_msec == -1) {
+			pp->submenu_mouse_exited_ticks_msec = OS::get_singleton()->get_ticks_msec();
+		}
+		//	RenderingServer::get_singleton()->canvas_item_add_line(pp->control->get_canvas_item(), pp->get_mouse_position(), pp->active_submenu_target_line[0] - pp->get_position(), Color(1, 0, 0), 1); // DEBUG DRAW.
+		//	RenderingServer::get_singleton()->canvas_item_add_line(pp->control->get_canvas_item(), pp->get_mouse_position(), pp->active_submenu_target_line[1] - pp->get_position(), Color(1, 0, 0), 1); // DEBUG DRAW.
```
Comment (bruvzg) [inline scene/gui/popup_menu.cpp]: Few debug lines not removed.

**Review by bruvzg — APPROVED** [review]
Seems to be working fine, I have not found any issues with it. Code looks good.

File: scene/gui/popup_menu.cpp [hunk 7]
```diff
@@ -753,24 +773,47 @@ void PopupMenu::_input_from_window_internal(const Ref<InputEvent> &p_event) {
...
-	int id = (over < 0 || items[over].separator || items[over].disabled) ? -1 : (items[over].id >= 0 ? items[over].id : over);
+bool PopupMenu::_is_mouse_moving_toward_submenu(const Vector2 &p_relative, bool is_submenu_left, const Vector2 &p_mouse_position, const Vector<Point2> &p_active_submenu_target_line) const {
+	Vector2 top_target = Vector2(p_active_submenu_target_line[0] - p_mouse_position).rotated(Math::deg_to_rad(is_submenu_left ? -90.0 : 90.0)).normalized();
+	Vector2 bottom_target = Vector2(p_active_submenu_target_line[1] - p_mouse_position).rotated(Math::deg_to_rad(is_submenu_left ? 90.0 : -90.0)).normalized();
+	// The top_target vector is normal to the vector between the mouse position and the top point of the submenu target line.
+	// The dot product is > 0 if the relative vector is +/- 90 degrees of the top_vector.
+	// The bottom_target vector is normal to the vector between the mouse position and the bottom point of the submenu target line,
+	// but pointing in the opposite direction of the top_target vector. Thus, the intersection of top and bottom test semicircles is the area
+	// in which the relative vector is deemed to be moving toward the submenu.
```
Comment (AThousandShips) [inline scene/gui/popup_menu.cpp:797]: I don't think these need to be normalized, the sign of the scalar product should be constant under normalization, as `(a' * a_len).dot(b' * b_len) == (a'.x * b'.x + a'.y * b'.y) * (a_len * b_len)`, where `a' * a_len == a` and `b' * b_len == b` and since the lengths must be positive the sign of the result should be the same as the sign of `(a'.x * b'.x + a'.y * b'.y)`

Also from the fact that `a.dot(b) == cos(T) * a.length() * b.length()` where `T` is the angle between the vectors, where the angle doesn't change under normalization and the lengths once again are positive

File: scene/gui/popup_menu.h [hunk 8]
```diff
@@ -144,6 +150,9 @@ class PopupMenu : public Popup {
 
 	void _activate_submenu(int p_over, bool p_by_keyboard = false);
 	void _submenu_timeout();
+	bool _is_mouse_moving_toward_submenu(const Vector2 &p_relative, bool is_submenu_left, const Vector2 &p_mouse_position, const Vector<Point2> &p_active_submenu_target_line) const;
```
Comment (AThousandShips) [inline scene/gui/popup_menu.h]:
```suggestion
	bool _is_mouse_moving_toward_submenu(const Vector2 &p_relative, bool p_is_submenu_left, const Vector2 &p_mouse_position, const Vector<Point2> &p_active_submenu_target_line) const;
```

File: scene/gui/popup_menu.cpp (hunk 5 above)
Comment (AThousandShips) [inline scene/gui/popup_menu.cpp]:
```suggestion
bool PopupMenu::_is_mouse_moving_toward_submenu(const Vector2 &p_relative, bool p_is_submenu_left, const Vector2 &p_mouse_position, const Vector<Point2> &p_active_submenu_target_line) const {
```

File: scene/gui/popup_menu.cpp [hunk 9]
```diff
@@ -345,10 +345,14 @@ int PopupMenu::_get_mouse_over(const Point2 &p_over) const {
 }
 
 void PopupMenu::_activate_submenu(int p_over, bool p_by_keyboard) {
+	ERR_FAIL_INDEX_MSG(p_over, items.size(), vformat("Invalid submenu index %d in _activate_submenu).", p_over));
 	PopupMenu *submenu_popup = items[p_over].submenu;
-	if (submenu_popup->is_visible()) {
-		return; // Already visible.
-	}
+	ERR_FAIL_COND_MSG(submenu_popup->is_visible(), vformat("_activate_submenu should not be called on an open submenu - index: %d).", p_over));
```
Comment (AThousandShips) [inline scene/gui/popup_menu.cpp]:
```suggestion
	ERR_FAIL_COND_MSG(submenu_popup->is_visible(), vformat("_activate_submenu should not be called on an open submenu - index: %d.", p_over));
```

File: scene/gui/popup_menu.cpp (hunk 7 above)
Comment (Koyper) [reply scene/gui/popup_menu.cpp:797]: Thanks for showing the proofs of this, and the code works the same without the normalization. The docs could be clarified here [Godot docs Vector Math](https://docs.godotengine.org/en/stable/tutorials/math/vector_math.html), because you've proven that these statements regarding the need for unit vectors are confusing.

"The dot product is most useful when used with unit vectors, making the first formula reduce to just cos(θ). This means we can use the dot product to tell us something about the angle between two vectors:"

"When using unit vectors, the result will always be between -1 (180°) and 1 (0°)."

Comment (AThousandShips) [reply scene/gui/popup_menu.cpp:797]: Note that this doesn't apply generally, so the documentation is correct, it *is* relevant where the sign alone is relevant, the actual magnitude is affected, but not the sign, forgot that in my proof that `sign(A*B) == sign(A)` when `B > 0`

**Comment by Koyper** [comment]
> One final recommendation, however: I think this behavior of the cursor's arc deciding if the submenu stays open or not should be documented somewhere.

@YeldhamDev Are you thinking in the class doc? I suppose it could go with `submenu_timer_popup_delay`?

**Comment by YeldhamDev** [comment]
Yeah, that sounds like a good place.

File: scene/gui/popup_menu.cpp (hunk 7 above)
Comment (Koyper) [reply scene/gui/popup_menu.cpp:797]: So the sign is the same regardless of normalization, but without normalization, the results will not be between -1 and 1?

Comment (AThousandShips) [reply scene/gui/popup_menu.cpp:797]: Indeed, the magnitude is affected by normalization but not direction, so the sign of the angle is the same, as it boils down to `cos(theta) * len(a) * len(b)` where both lengths are naturally positive assuming the vectors can be normaized

Comment (Koyper) [reply scene/gui/popup_menu.cpp:797]: I put a comment in the code regarding the special case here that works without normalization.

**Comment by Koyper** [comment]
This push includes all suggested changes.

File: scene/gui/popup_menu.cpp [hunk 10]
```diff
@@ -763,27 +790,52 @@ void PopupMenu::_input_from_window_internal(const Ref<InputEvent> &p_event) {
...
+	Vector2 bottom_target = Vector2(p_active_submenu_target_line[1] - p_mouse_position).rotated(Math::deg_to_rad(p_is_submenu_left ? 90.0 : -90.0));
+	// The top_target vector is perpendicular to the vector between the mouse position and the top point of the submenu target line.
+	// The dot product is > 0 if the relative vector is +/- 90 degrees of the top_vector.
+	// The bottom_target vector is perpendicular to the vector between the mouse position and the bottom point of the submenu target line,
+	// but pointing in the opposite direction of the top_target vector. Thus, the intersection of top and bottom test semicircles is the area
+	// in which the relative vector is deemed to be moving toward the submenu.
+	if (bottom_target.dot(p_relative) > 0 && top_target.dot(p_relative) > 0) { // Without normalization, the comparison is correct by testing only the sign, but would not work against a range of +/- 1.
+		return true;
+	}
+	return false;
```
Comment (kitbdev) [inline scene/gui/popup_menu.cpp]:
```suggestion
	Vector2 top_target = (p_active_submenu_target_line[0] - p_mouse_position).rotated(_is_submenu_left ? -Math::PI / 2 : Math::PI / 2);
	Vector2 bottom_target = (p_active_submenu_target_line[1] - p_mouse_position).rotated(p_is_submenu_left ? Math::PI / 2 : -Math::PI / 2);
	// The top_target vector is perpendicular to the vector between the mouse position and the top point of the submenu target line.
	// The dot product is > 0 if the relative vector is +/- 90 degrees of the top_vector.
	// The bottom_target vector is perpendicular to the vector between the mouse position and the bottom point of the submenu target line,
	// but pointing in the opposite direction of the top_target vector. Thus, the intersection of top and bottom test semicircles is the area
	// in which the relative vector is deemed to be moving toward the submenu.
	// Without normalization, the comparison is correct by testing only the sign, but would not work against a range of +/- 1.
	return bottom_target.dot(p_relative) > 0 && top_target.dot(p_relative) > 0;
```

The `top/bottom_target` should already be Vector2s, radians can be used directly, and the condition can be returned directly.

Though I still think it would be easier to understand if we just got the angles and compared them:

```suggestion
	float top_angle = Math::atan2(p_active_submenu_target_line[0].y - p_mouse_position.y, p_active_submenu_target_line[0].x - p_mouse_position.x);
	float bottom_angle = Math::atan2(p_active_submenu_target_line[1].y - p_mouse_position.y, p_active_submenu_target_line[1].x - p_mouse_position.x);
	float mouse_angle = Math::atan2(p_relative.y, p_relative.x);
	return p_is_submenu_left != (mouse_angle <= bottom_angle && mouse_angle >= top_angle);
```

File: scene/gui/popup_menu.cpp [hunk 11]
```diff
@@ -345,10 +345,14 @@ int PopupMenu::_get_mouse_over(const Point2 &p_over) const {
...
 void PopupMenu::_activate_submenu(int p_over, bool p_by_keyboard) {
+	ERR_FAIL_INDEX_MSG(p_over, items.size(), vformat("Invalid submenu index %d in _activate_submenu.", p_over));
 	PopupMenu *submenu_popup = items[p_over].submenu;
-	if (submenu_popup->is_visible()) {
-		return; // Already visible.
-	}
+	ERR_FAIL_COND_MSG(submenu_popup->is_visible(), vformat("_activate_submenu should not be called on an open submenu - index: %d.", p_over));
+
+	submenu_popup->this_submenu_index = p_over; // `this_submenu_index` is always -1 for the parent popup, and always a positive int for every open submenu.
+	active_submenu_index = p_over; // A positive int for the parent popup if any submenu is open.
```
Comment (kitbdev) [inline scene/gui/popup_menu.cpp]: These comments are already at the definition of these vars in the header, are they really needed?
Same with the other time `active_submenu_index` is set.

File: scene/gui/popup_menu.cpp [hunk 12]
```diff
@@ -987,28 +1039,43 @@ void PopupMenu::_draw_items() {
...
+	if (this_submenu_index != -1 && active_submenu_index != -1) { // Close secondary submenus on first submenu close.
+		ERR_FAIL_INDEX_MSG(active_submenu_index, items.size(), vformat("Invalid active_submenu_index index %d in _close_pressed.", active_submenu_index));
+		items[active_submenu_index].submenu->_close_pressed();
+	}
+	Popup::_close_pressed();
+}
+
+void PopupMenu::_close_or_suspend() {
+	if (this_submenu_index != -1) { // Is a submenu.
+		PopupMenu *pp = Object::cast_to<PopupMenu>(get_parent()); // Parent popup.
```
Comment (kitbdev) [inline scene/gui/popup_menu.cpp]: This comment isn't really needed it's clear.
You could change the name to `parent_popup` to make it more clear and consistent instead.

**Review by kitbdev — COMMENTED** [review]
When the mouse is in between two items with submenus, it can flicker:
System Info: Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 32.0.15.8108) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 threads) - 15.82 GiB memory

> [!WARNING]
> Flickering

https://github.com/user-attachments/assets/b31ae47a-bc1b-4074-876f-3572c7d006cd

I could not get it to happen in single-window mode, its probably only multi-window mode. On master, trying this results in the submenu hiding.

**Comment by Koyper** [comment]
I worked out a fix for this very pesky flickering issue, but ran into another `DisplayServer` bug that's thwarting wrapping this up. See #112620.

**Comment by Koyper** [comment]
This push fixes the flickering issue and ensures proper function with `per_pixel_transparency` and `content_scale_factor` settings. Lots of work.

I also fixed a tricky bug that intermittently caused a submenu to close unexpectedly while moving the mouse toward it. This was caused by an unpredictable delay between when a timer is started and when `is_stopped` will return a valid result. This can unexpectedly be longer than `30` msecs. The result makes the mouse direction detection really reliable and the menu performance feels solid.

Everything seems to be functioning properly for both embedded and non-embedded windows, so give it a whirl.

File: scene/gui/popup_menu.cpp [hunk 13]
```diff
@@ -987,28 +1033,52 @@ void PopupMenu::_draw_items() {
...
+	}
+	Popup::_close_pressed();
+}
+
+void PopupMenu::_close_or_suspend() {
+	if (this_submenu_index != -1) { // Is a submenu.
+		PopupMenu *parent_popup = Object::cast_to<PopupMenu>(get_parent());
+		Point2 mouse_pos = is_embedded() ? parent_popup->get_mouse_position() : Point2(DisplayServer::get_singleton()->mouse_get_position() - parent_popup->get_position());
+		if (parent_popup->_get_mouse_over(mouse_pos) == this_submenu_index) {
+			print_error(vformat("_close_or_suspend was called for submenu index %d with the mouse still inside the parent menu item.", this_submenu_index));
```
Comment (kitbdev) [inline scene/gui/popup_menu.cpp]: This should use an error macro like `ERR_PRINT` (or be removed if it was just for debugging).

**Review by kitbdev — APPROVED** [review]
Flickering issue is fixed. 
Looks good on both single-window mode and multi-window mode.

File: scene/gui/popup_menu.cpp (hunk 13 above)
Comment (Koyper) [reply scene/gui/popup_menu.cpp]: All done. Thanks!

**Comment by Koyper** [comment]
Final push. Also nabbed the last source of the occasional error message.

**Comment by Repiteo** [comment]
Thanks!

**Comment by Koyper** [comment]
Yahoo!

**Comment by CycloneRing** [comment]
This PR broke popup menus on Windows in editor, Was this PR tested on Windows at all before merging?? 
Recently, each update seems to introduce new regressions. 
On Windows simply hovering a pop up menu such as Project > Tools triggers this error :
```cpp
ERR_FAIL_COND_MSG(submenu_popup->is_visible(), vformat("_activate_submenu should not be called on an open submenu - index: %d.", p_over));
```

**Comment by Koyper** [comment]
The error message does not necessarily indicate any instability, but I'll see about tracking down what's happening. How are the popups working otherwise? Is there any sequence of movement that repeatably triggers the error message?

**Comment by CycloneRing** [comment]
> The error message does not necessarily indicate any instability, but I'll see about tracking down what's happening. How are the popups working otherwise? Is there any sequence of movement that repeatably triggers the error message?

Simply hovering on the popup menus in editor triggers the error, I cloned current upstream and built it without any changes. I'm on Windows 10 x64...

Replacing back the error block with 
```CPP
	if (submenu_popup->is_visible()) {
		return; // Already visible.
	}
```
Will fix it but I'm not sure if that's good.

**Comment by Koyper** [comment]
Are you using single-window mode or default?

I can't replicate this on Win 10 at the moment, but since I believe it is being handled cleaning by the `return` I can look at reducing the error spam here and in a few other places. Is anyone else observing this error?

I also have a fix ready for error messages releated to global and native system menus.

**Comment by KoBeWi** [comment]
I managed to replicate it once (in multi window mode). Seems like rather random error.

**Comment by Koyper** [comment]
My best guess at the moment is there is a random and short delay between the submenu hiding and when `submenu_popup->is_visible` returns false. I think it's safe not to show the error.

**Comment by Koyper** [comment]
Should be fixed by  #112967
