### PR TITLE
[SpriteFramesEditor] Decompress texture before auto slicing sprite sheet.

### LINKED ISSUE #108635: Infinite Loop in SpriteFrames Editor when auto slicing compressed png sprite sheet
### Tested versions

- Reproducible in : Godot v4.4.1.rc2 and later versions to Godot v4.5 beta3

### System information

 Windows 11

### Issue description

When adding an AnimatedSprite2D or AnimatedSprite3D, if you open the SpriteFrames editor and use Add frames from sprite sheet with a .png that’s VRAM Compressed, clicking Auto Slice causes an infinite loop.

Expected: Should slice normally or warn, not hang.
```cmd
...
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3235)
...
```

### Steps to reproduce

- create scene
- add AnimatedSprite3D or AnimatedSprite2D
- set  new SpriteFrames in properties
- click to open SpriteFrames Editor
- click 'add frame from sprite sheet' button
- select png that is imported with compressed mode set as "VRAM Compressed"
- click 'auto slice'...leading to a infinite loop

### Minimal reproduction project (MRP)

[spriteframebug.zip](https://github.com/user-attachments/files/21232424/spriteframebug.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/108635

_bugsquad edit: supersedes https://github.com/godotengine/godot/pull/108689_

### CODE REVIEW

**Comment by clayjohn** [comment]
Just to confirm, this fixes the infinite loop because the size was incorrect before? 

With this change you still get the "cannot call get_pixel()" error though right?

**Comment by bruvzg** [comment]
> Just to confirm, this fixes the infinite loop because the size was incorrect before?

It's not, size is the same, and it's not an infinite loop.

`get_pixel` is not supported by compressed textures, so it's spamming errors for every pixel in the texture (x2, since it's two nested loops), and logging errors is not particularly fast (and getting slower as the number of messages increase). It will probably finish in a few minutes (if the texture is small enough and the editor won't run out of memory or message queue space before, which is likely what will happen).

*Edit:*
> *if the texture is small enough and the editor won't run out of memory or message queue space before, which is likely what will happen*

*tested it with MRP from the issue, as predicted, crashes with `Failed method: EditorToaster::_error_handler_impl. Message queue out of memory. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_mb' in project settings.` after 6 min (about half way).*

With decompressed texture, `get_pixel` should always work.

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Makes sense.

File: editor/scene/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -544,7 +544,11 @@ bool SpriteFramesEditor::_matches_background_color(const Color &p_background_col
 
 Size2i SpriteFramesEditor::_estimate_sprite_sheet_size(const Ref<Texture2D> p_texture) {
 	Ref<Image> image = p_texture->get_image();
-	Size2i size = p_texture->get_size();
+	if (image->is_compressed()) {
+		image = image->duplicate();
```
Comment (Ivorforce) [inline editor/scene/sprite_frames_editor_plugin.cpp:548]: Does this have some potential for a performance regression? Is the function called often? Might be worth commenting, or opening a follow-up issue for if so.

Comment (bruvzg) [reply editor/scene/sprite_frames_editor_plugin.cpp:548]: It's only called when you press “Auto Slice” button in the edit dialog, and `is_compressed` is simply `p_format > FORMAT_RGBE9995`, so it should not have any performance impact.

**Comment by Repiteo** [comment]
Thanks!
