### PR TITLE
Set default file name for exported projects

### LINKED ISSUE #17976: Export Game failed on OSX
image

macOS 10.31.3

Failed to export game on OSX

- Download the GODOT from `brew cask`
- Open GODOT
- Download the template Isometric Game
- Download the export templates
- Export to OSX and it fails

image

image

The errors said something about a file exists but the export failed everytime

### PR DESCRIPTION
**Pull request by flashyincceo**
Fixes #17976. 

It looks like the editor doesn't check for a valid file name before exporting a project. This pull request sets the project name as the default value for an exported file if a default name hasn't already been set. 

I imagine it would be better to test for an empty filename and alert the user. Do you think I should implement the alert in addition to this fix?

apr-17-2018 16-28-08

### CODE REVIEW

File: editor/project_export.cpp [hunk 1]
```diff
@@ -724,6 +724,11 @@ void ProjectExportDialog::_export_project() {
 
 	export_project->set_access(FileDialog::ACCESS_FILESYSTEM);
 	export_project->clear_filters();
+
+	if (default_filename == "") {
+		default_filename = ProjectSettings::get_singleton()->get("application/config/name");
```
Comment (akien-mga) [inline editor/project_export.cpp]: This should be done in the constructor instead where `default_filename` is initialized (as a `String()` if not configured otherwise): https://github.com/flashyincceo/godot/blob/e219fcb06d3eb7c99ed308425ef5c68d61a55c03/editor/project_export.cpp#L993

**Comment by flashyincceo** [comment]
@akien-mga Is this the change you were suggesting?

**Comment by akien-mga** [comment]
Yes, seems good :)

**Comment by hpvb** [comment]
Cherry picked into 3.0.3
