### PR TITLE
Fix action state when multiple events are assigned

### LINKED ISSUE #45628: Movement doesn't work while using a controller (d-pad buttons)
**Godot version:**
3.2.4.rc1.official

**OS/device including version:**
Windows 10 (19042.746)

**Issue description:**
When I plug in a PS4 controller, KinematicBody2D doesn't move properly while using the d-pad buttons or the keyboard. Same occurs if I use DS4Windows to emulate a Xbox 360 controller (XInput).

**(!) Note** The same code works fine in Godot v3.2.3.stable, both for the PS4 controller (with and without DS4Windows) and the keyboard.

```
func _physics_process(delta):
	velocity = get_direction() * speed
	velocity = move_and_slide(velocity)


func get_direction():
	var dir: = Vector2.ZERO
	dir.x = Input.get_action_strength("move_right") - Input.get_action_strength("move_left")
	dir.y = Input.get_action_strength("move_down") - Input.get_action_strength("move_up")
	dir = dir.normalized()
	return dir
```

**Steps to reproduce:**
1. Open and run the attached project with a PS4 controller connected.
2. Move the rectangle on the screen using WASD or the arrow keys, then try to move it using the d-pad buttons.
3. The node's movement shouldn't work properly, neither with the keyboard or the controller.
4. Disconnect the controller and the rectangle will move without problems using the keyboard.

Repeat steps 1 and 2 in Godot v3.2.3.stable.official and the rectangle will move without problems.

> [Here](https://streamable.com/45xsjm) you can see how the gamepad registers the buttons pressing without moving the rectangle, same for WASD and arrow keys.

**Minimal reproduction project:**

[GamepadInputError.zip](https://github.com/godotengine/godot/files/5903578/GamepadInputError.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #45628

This PR simply changes `Action.pressed` (internal struct) from bool to int and increments it when action is pressed and decrements when it's released. `Input.is_action_pressed()` and related actions return true when at least one even is pressed.

There is some weirdness when releasing actions with modifier keys. They can be released without being pressed. I added a small workaround, but the changes need some testing in general.

### CODE REVIEW

**Comment by Sauermann** [comment]
The concept looks good from a quick glance at the changes.
Do you think that this PR supersedes #47599?
This PR should probably revert #30890.

**Comment by KoBeWi** [comment]
> Do you think that this PR supersedes https://github.com/godotengine/godot/pull/47599?

Yes. That PR has so many changes that I'm not even sure what it's trying to do.

> This PR should probably revert https://github.com/godotengine/godot/pull/30890.

Done.

**Review by Sauermann — APPROVED** [review]
This PR reverts #30890, which originally solved issue #30888.
I have tested this PR and can confirm, that this PR fixes the implementation and resolves #30888. Implementation looks good.

I can't test if this PR solves issue #45628, because I don't have a PS4 controller.

**Comment by KoBeWi** [comment]
> I can't test if this PR solves issue https://github.com/godotengine/godot/issues/45628, because I don't have a PS4 controller.

You can test with a keyboard, with 2 keys assigned to the same action (e.g. the default `ui_accept`).

File: core/input/input.cpp [hunk 1]
```diff
@@ -697,16 +697,19 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
...
+					}
 				} else {
-					action.pressed = false;
-					action.released_physics_frame = Engine::get_singleton()->get_physics_frames();
-					action.released_process_frame = Engine::get_singleton()->get_process_frames();
+					if (action.pressed == 1) {
+						action.released_physics_frame = Engine::get_singleton()->get_physics_frames();
+						action.released_process_frame = Engine::get_singleton()->get_process_frames();
+					}
+					action.pressed = MAX(action.pressed - 1, 0);
```
[the remark this answers is not in the document]
Comment (KoBeWi) [reply core/input/input.cpp:712]: It solves a problem with modifier actions, like `ui_text_completion_query`. For some reason pressing them requires both keys (`Ctrl + Space` in case of the mentioned action), but releasing doesn't require the modifier to be pressed, which means they can be released without previously being pressed.

**Comment by Sauermann** [comment]
I have tested this PR with 2 keys assigned to the same action.
So #45628 is a duplicate of #30888!?

**Comment by KoBeWi** [comment]
Seems so, although it's weird that it says that it worked in Godot 3 🤔
I'll test with a controller.

**Comment by KoBeWi** [comment]
Ok I pushed some changes to also fix action strength.

I can't exactly reproduce the original issue, so it needs to be tested by affected users.

File: core/input/input.cpp [hunk 2]
```diff
@@ -697,23 +699,32 @@ void Input::_parse_input_event_impl(const Ref<InputEvent> &p_event, bool p_is_em
...
-				action.strength = 0.0f;
-				action.raw_strength = 0.0f;
 				action.exact = InputMap::get_singleton()->event_is_action(p_event, E.key, true);
 			}
-			action.strength = p_event->get_action_strength(E.key);
-			action.raw_strength = p_event->get_action_raw_strength(E.key);
+
+			if (is_pressed || action.pressed == 0) {
+				action.strength = p_event->get_action_strength(E.key);
+				action.raw_strength = p_event->get_action_raw_strength(E.key);
```
Comment (Sauermann) [inline core/input/input.cpp:726]: This implementation changes the action.strength on every event, which might lead to alternating values, if two axis inputs are mapped to the same action and both axis are moved.

The comment https://github.com/godotengine/godot/issues/45628#issuecomment-782840254 suggests to use as strength the maximum strength of all related actions. Perhaps that would be a better solution?

**Review by Sauermann — COMMENTED** [review]
I can't replicate #45628, so it is difficult for me to verify, if the new changes fix that issue.

File: core/input/input.cpp (hunk 2 above)
Comment (KoBeWi) [reply core/input/input.cpp:726]: But then what happens on release? It should assign max strength of still pressed actions, but they are not tracked. This means that if you use analog and then press a key, your analog strength will be ignored until it's released.
Maybe it's fine, idk.

Comment (Sauermann) [reply core/input/input.cpp:724]: > It should assign max strength of still pressed actions, but they are not tracked

Perhaps we could track it with the following, but I haven thought it through yet.

``` diff
diff --git a/core/input/input_map.h b/core/input/input_map.h
index b4d5beacb3..b59e898730 100644
--- a/core/input/input_map.h
+++ b/core/input/input_map.h
@@ -48,10 +48,17 @@ public:
         */
        static int ALL_DEVICES;
 
+       struct EventWithStrength {
+               Ref<InputEvent> event;
+               int pressed = 0;
+               float strength = 0.0f;
+               float raw_strength = 0.0f;
+       };
+
        struct Action {
                int id;
                float deadzone;
-               List<Ref<InputEvent>> inputs;
+               List<EventWithStrength> inputs;
        };
 
 private:
```

**Comment by romlok** [comment]
Stumbled upon this PR while investigating some related behaviour, so I tested this under Linux:

When idle, the (my) DS4's analogue sticks often send out a stream of events with very low values (|n| < 0.1), alternating between two ±0.01 values (eg. 0.06, 0.07 in quick succession).

So if a stick axis is mapped to an action, and that action is triggered through a different input than the stick, the action will tend to be "released" after a short amount of time.

---

I also noticed that, with this PR, if the action _is_ triggered via the stick, it will not always release immediately when the stick is released. The associated input events will be fired, but `Input.is_action_pressed` will continue to be `true` for a while afterward.  Seemingly until some amount of low-value axis events are fired?

---

Also, unrelated to stick axes (I disconnected the DS4 just to be sure!), it appears that the "inputs held" counter doesn't reset to zero when the window loses focus.  If I hold down two keys to trigger an action, and move focus to another window, `Input.is_action_pressed` continues to return `true`.  For a single held key the action is considered released when the window loses focus.

FWIW, this was my test project: [is-action-pressed.zip](https://github.com/godotengine/godot/files/12441899/is-action-pressed.zip)

**Comment by Sauermann** [comment]
> alternating between two ±0.01 values (eg. 0.06, 0.07 in quick succession).

Have you tried to set the deadzone to `0.1`? That might help.

> `Input.is_action_pressed` continues to return `true`

That issue is tracked in #36223.

**Review by reduz — APPROVED** [review]
Looks good

**Comment by reduz** [comment]
To me this was always the right approach to solve the original issue btw.

**Comment by romlok** [comment]
> > alternating between two ±0.01 values (eg. 0.06, 0.07 in quick succession).
> 
> Have you tried to set the deadzone to `0.1`? That might help.

The deadzone specified in the input map is the default `0.5`.  AFAICT deadzone is used to determine pressed/not pressed, but doesn't actually filter out any events.  Or is there another deadzone setting? :thinking: 

> > `Input.is_action_pressed` continues to return `true`
> 
> That issue is tracked in #36223.

I'm using Linux, but that issue appears to be specific to MacOS? :confused: 
The current behaviour for me in 4.1 is that actions are considered released when the window loses focus, no matter how many of that action's inputs are being pressed.  This patch changes that behaviour for multiple simultaneous inputs.

It seems to be that with this patch the "held keys" is reduced by one on each focus loss, so if an action does get "stuck" in this way, one can release it by repeatedly focus-defocusing the window.

**Comment by KoBeWi** [comment]
> It seems to be that with this patch the "held keys" is reduced by one on each focus loss, so if an action does get "stuck" in this way, one can release it by repeatedly focus-defocusing the window.

Fixed.

**Comment by akien-mga** [comment]
Thanks!

---

I actually merged this by mistake xD
I had the tab open because I wanted to do some testing and make sure I can both reproduce the original bug, and confirm the fix. I guess I can still do that post merge.

File: core/input/input.cpp [hunk 3]
```diff
@@ -285,7 +285,9 @@ bool Input::is_joy_button_pressed(int p_device, JoyButton p_button) const {
 
 bool Input::is_action_pressed(const StringName &p_action, bool p_exact) const {
 	ERR_FAIL_COND_V_MSG(!InputMap::get_singleton()->has_action(p_action), false, InputMap::get_singleton()->suggest_actions(p_action));
-	return action_state.has(p_action) && action_state[p_action].pressed && (p_exact ? action_state[p_action].exact : true);
+	if (p_action == "move_right")
+		print_line(action_state.has(p_action), action_state[p_action].pressed, action_state[p_action].pressed > 0, (p_exact ? action_state[p_action].exact : true));
```
Comment (akien-mga) [inline core/input/input.cpp:289]: Debug print?

Comment (KoBeWi) [reply core/input/input.cpp:289]: Yes ;_;

File: core/input/input.cpp (hunk 2 above)
Comment (KoBeWi) [reply core/input/input.cpp:724]: This can be addressed later if someone opens an issue. Let's see if the current behavior is ok for now.

Comment (Sauermann) [reply core/input/input.cpp:724]: Sounds good to me.

**Comment by jordanlis** [comment]
> The deadzone specified in the input map is the default `0.5`. AFAICT deadzone is used to determine pressed/not pressed, but doesn't actually filter out any events. Or is there another deadzone setting? 🤔

Haa ok, I understand now. So the deadzone doesn't apply if the button is not pressed by the user ? (like these random events) ? I don't really see why we just apply this deadzone to any events, it should fix the original issue of really small and random events, no ?

**Comment by KoBeWi** [comment]
The deadzone is always used.
