### PR TITLE
[3.x] [Android 14] Fix GodotEditText white box showing during game load

### LINKED ISSUE #87059: Android 14: white stripe is displayed on top of the screen during game load
### Tested versions

Reproducible in 3.5.3 stable

### System information

Android 14, Samsung Galaxy A32

### Issue description

Immediately after the splash screen and before the game loads, there is a short period where a black screen with a white stripe on top of the screen is displayed. On older versions of Android (e.g., Android 13), there was only a normal black screen shown while the game is loading. The white stripe on the top of the screen should not be there during game load.

Screenshot_20240110_202343_In Sync

### Steps to reproduce

1. Create a new project in Godot
2. Run it on an Android device

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by BZ1234567890**
Prevent GodotEditText white box from showing at the top of the splash screen during game load on Android 14 devices.

This fix is for an issue (#87059) that does not apply to the master branch, hence pull request for the 3.x branch.

Fixes #87059

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
The code changes look good to me.

I'll let @m4gr3d assess more in depth with knowledge of the Android updates.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.java [hunk 1]
```diff
@@ -385,6 +386,12 @@ private void onVideoInit() {
 		GodotEditText edittext = new GodotEditText(activity);
 		edittext.setLayoutParams(new ViewGroup.LayoutParams(LayoutParams.MATCH_PARENT,
 				(int)getResources().getDimension(R.dimen.text_edit_height)));
+		// Prevent GodotEditText from showing on splash screen on devices with Android 14 or newer.
+		// It is already not visible on Android 13 and older versions by default, so there is no
+		// need to do anything when running on these versions.
+		if (Build.VERSION.SDK_INT > Build.VERSION_CODES.TIRAMISU) {
```
Comment (m4gr3d) [inline platform/android/java/lib/src/org/godotengine/godot/Godot.java:392]: Let's remove the version check since regardless of the Android version, the intent for the edittext is to never be visible. 
Do keep the first line of the comments though as it explains why we're updating the background color.

**Review by m4gr3d — APPROVED** [review]
Looks good, just a minor feedback to address and it should be good to merge.

While testing, I've noticed the same issue on the Android editor for Godot 4. Can you apply the same fix to the `master` branch as well.

File: platform/android/java/lib/src/org/godotengine/godot/Godot.java (hunk 1 above)
Comment (BZ1234567890) [reply platform/android/java/lib/src/org/godotengine/godot/Godot.java]: @m4gr3d, thanks for the review. I've updated this commit & prepared a separate pull request for the master branch (see https://github.com/godotengine/godot/pull/88351).

**Review by m4gr3d — APPROVED** [review]
Thanks for the fix!

**Comment by PrimaryCat** [comment]
Sorry if this is the wrong place but will this be added to the 3.6 release? It's already merged on the main branch and added to the 4.3 milestone however I can't see any information regarding the 3.6 milestone.

**Comment by lawnjelly** [comment]
Thanks!
