### PR TITLE
Fixes inherited scenes not working in TileSet scenes collection sources

### LINKED ISSUE #58349: It is not possible to add inherited scenes into Godot 4 TileSet Scene Collection
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

When using node inheritance, and attempting to add an inherited scene to TileSet's Scene Collection, an error is raised :

`Invalid PackedScene for TileSetScenesCollectionSource: res://child.tscn. Root node should extend Control or Node2D.`

Even if the root scene is Node2D in the base scene.

Are inherited scenes unsupported, or is this a bug?

### Steps to reproduce

1. Create a scene with Node2D as root.
2. Create another scene, that inherits from the first scene.
3. Drag the second scene into a TileSet's Scene Collection
4. An error is printed into the output, and the TileSet now contains an invalid entry: "Tile with Invalid Scene"

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by groud**
Fixes https://github.com/godotengine/godot/issues/58349

### CODE REVIEW

File: scene/resources/tile_set.cpp [hunk 1]
```diff
@@ -4716,14 +4716,19 @@ void TileSetScenesCollectionSource::set_scene_tile_id(int p_id, int p_new_id) {
...
 	ERR_FAIL_COND(!scenes.has(p_id));
 	if (p_packed_scene.is_valid()) {
-		// Make sure we have a root node. Supposed to be at 0 index because find_node_by_path() does not seem to work.
-		ERR_FAIL_COND(!p_packed_scene->get_state().is_valid());
-		ERR_FAIL_COND(p_packed_scene->get_state()->get_node_count() < 1);
-
 		// Check if it extends CanvasItem.
-		String type = p_packed_scene->get_state()->get_node_type(0);
+		Ref<SceneState> scene_state = p_packed_scene->get_state();
+		String type = "";
```
Comment (akien-mga) [inline scene/resources/tile_set.cpp:4721]: `String` is default allocated so the `= ""` is not needed.

**Review by akien-mga — APPROVED** [review]

File: scene/resources/tile_set.cpp (hunk 1 above)
Comment (groud) [reply scene/resources/tile_set.cpp]: Fixed, thanks!

**Comment by akien-mga** [comment]
Thanks!
