### PR TITLE
Revamp audio bus UI

### LINKED ISSUE #116073: Confusing UI in audio mixer dB 'levels'
### Tested versions

4.6 stable (mono)

### System information

N/A, but Windows 11

### Issue description

I asked in a Godot discord server whether this was a bug, they explained it to me that it was not, but they recommended me that I might report it anyways as it might look confusing to others as well.

My initial thought was that the top -6 dB was supposed to be +6 dB, as when I slide it up, the value in the tooltip shows +6 dB

They then explained that it's just a reference range, and then it clicked.
The 'second' negative 6 dB is actually the positive value, but happens to be on the reference line making it look like another -6 dB, as the reference dash/line is almost identical as the actual -6.0dB label

I hope I didn't make it more confusing, basically it looks like there's two -6.0dB's on there

Image

### Steps to reproduce

Just look in audio level in any new project

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Akosmo**
Closes: https://github.com/godotengine/godot/issues/116073

Initially this started as a fix for the issue above. However as I looked more into the audio bus, the more problems I found.

This PR fixes many related things, and finishes up with a new (but important) look to the VU meter.

Here's what I have fixed:

- Moved slider level preview so it no longer blocks the view of the VU meter
- Removed extra padding on the notches so it matches the height of the VU meter
- Added positive and negative signs to the dB levels to avoid confusion
- Separated "dB" from dB number and removed unnecessary decimals so there's less clutter
- Fixed a bug where VU meter wouldn't work in some cases
- Changed how VU meter scales so it matches actual dB value
- Added a peak indicator so users can see better at which level their audio peaks at
- Changed VU meter texture
- Minor changes: using UID and fixing typo in a comment

There are plenty of reasons why I changed the VU meter texture:
- Improve clarity
In the original texture, it was very hard to tell where the peak was

- Emphasize clipping
In the original texture, the gradient changed to red only at the very top and way to smoothly. It doesn't give enough feedback that the audio is clipping, and the importance of it

- Remove unnecessary gap
There is a gap in the original texture, which I assume was meant to show where 0 dB sits. Not only is it in the wrong place, but also the gap size doesn't match the notches in the texture (which also don't mean anything AFAIK)

- Improve customizability
The colors of the old meter come with the texture. So the only way to change the colors AFAIK, was by either using modulate, or changing the texture. This PR brings editor settings to change the colors of the meter

- Match the rest of the editor
Godot now has a more cleaner and modern look. In my opinion, this change on the meter makes it fit the editor better

What I didn't do:
- Delete the old texture
That could be used to change to the previous look if a user decides to. And I'm wasn't sure if removing it would break anything

I hope these are good changes. I'm happy with them, but I understand changing the appearance of the VU meter is a big one. I could change back to the previous one if really needed, and try to fix the gap too.

For comparison, here's the old VU meter:

https://github.com/user-attachments/assets/f7c98e1e-cc5e-46b8-bae9-1abcf3aa8cdf

And here's the new one (changes since this video was recorded: peak indicators now disappear at the bottom):

https://github.com/user-attachments/assets/9bb0eeeb-cde1-49fc-ac8c-6df2e0136616

### CODE REVIEW

**Comment by Akosmo** [comment]
> I noticed that when you first open the editor, the peak indicators start at the middle, and then go down.
> 
> Also, I discovered a bug not related to this PR when testing this: if your editor starts with the audio tab open, and you switch to another, and then play something and switch back to it, the volume indicators will not be visible.

I'll try to see if I can fix the indicators position at the start, but thankfully it's no big deal
As for the bars not appearing, good catch! Thankfully not introduced in this PR, but since I'm working on the bus, I'll check if I can fix it.

As mentioned, the indicators not working sometimes is also something that has been bothering me. Still haven't been able to reproduce it, so if anyone finds out how, I'd love to know!

File: editor/audio/editor_audio_buses.cpp [hunk 1]
```diff
@@ -168,40 +165,108 @@ void EditorAudioBus::_notification(int p_what) {
...
+				double lower_bound = normalized_peak_indicator - 0.01;
+				double upper_bound = normalized_peak_indicator + 0.01;
+
+				if (!(channel[i].vu_l->get_value() > lower_bound) && channel[i].vu_l->get_value() < upper_bound) {
+					if (channel[i].peak_timer_l->is_paused()) {
+						channel[i].peak_timer_l->set_paused(false);
+						channel[i].peak_timer_l->start();
+					}
+				} else {
+					if (!channel[i].peak_timer_l->is_paused() || channel[i].indicator_fall_l == true) {
```
Comment (YeldhamDev) [inline editor/audio/editor_audio_buses.cpp]:
```suggestion
				} else if (!channel[i].peak_timer_l->is_paused() || channel[i].indicator_fall_l == true) {
```

File: editor/audio/editor_audio_buses.cpp [hunk 2]
```diff
@@ -168,40 +165,108 @@ void EditorAudioBus::_notification(int p_what) {
...
+				lower_bound = normalized_peak_indicator - 0.01;
+				upper_bound = normalized_peak_indicator + 0.01;
+
+				if (!(channel[i].vu_r->get_value() > lower_bound) && channel[i].vu_r->get_value() < upper_bound) {
+					if (channel[i].peak_timer_r->is_paused()) {
+						channel[i].peak_timer_r->set_paused(false);
+						channel[i].peak_timer_r->start();
+					}
+				} else {
+					if (!channel[i].peak_timer_r->is_paused() || channel[i].indicator_fall_r == true) {
```
Comment (YeldhamDev) [inline editor/audio/editor_audio_buses.cpp]:
```suggestion
				} else if (!channel[i].peak_timer_r->is_paused() || channel[i].indicator_fall_r == true) {
```

File: editor/audio/editor_audio_buses.cpp [hunk 3]
```diff
@@ -168,40 +165,108 @@ void EditorAudioBus::_notification(int p_what) {
...
+				} else {
+					channel[i].peak_indicator_l->set_position(Point2(0.0, MIN(peak_indicator_range, channel[i].peak_indicator_l->get_position().height + get_process_delta_time() * 60.0)));
+				}
+				if (!channel[i].indicator_fall_r) {
+					channel[i].peak_indicator_r->set_position(Point2(0.0, MIN(channel[i].peak_indicator_r->get_position().height, peak_indicator_range - channel[i].vu_r->get_value() * peak_indicator_range)));
+				} else {
+					channel[i].peak_indicator_r->set_position(Point2(0.0, MIN(peak_indicator_range, channel[i].peak_indicator_r->get_position().height + get_process_delta_time() * 60.0)));
+				}
+
+				// Weird hack, `normalized_peak_indicator` almost never equals `channel[i].vu_l->get_value()`.
```
Comment (YeldhamDev) [inline editor/audio/editor_audio_buses.cpp]: Doesn't `is_equal_approx()` work here?

File: editor/settings/editor_settings.cpp [hunk 4]
```diff
@@ -1049,6 +1047,16 @@ void EditorSettings::_load_defaults(Ref<ConfigFile> p_extra_config) {
...
 
+	// Audio buses
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/active_max_db", Color(1.0, 0.0, 0.0), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/active_min_db", Color(0.0, 1.0, 0.1), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/active_normalized_db", Color(1.0, 1.0, 0.1), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/inactive_max_db", Color(0.0, 0.5, 1.0), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/inactive_min_db", Color(0.0, 1.0, 1.0), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/inactive_normalized_db", Color(1.0, 1.0, 1.0), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/tint_over", Color(0.15, 0.15, 0.15), "")
+	EDITOR_SETTING(Variant::COLOR, PROPERTY_HINT_NONE, "editors/audio_buses/tint_under", Color(0.15, 0.15, 0.15), "")
```
Comment (YeldhamDev) [inline editor/settings/editor_settings.cpp]: Is this much fine-tuning necessary?

**Review by YeldhamDev — CHANGES_REQUESTED** [review]

File: editor/audio/editor_audio_buses.cpp (hunk 3 above)
Comment (Akosmo) [reply editor/audio/editor_audio_buses.cpp]: Not sure, but I have considered it. I've tried many different approaches and they didn't work. Things like changing type, `snappedf()`, setting `normalized_peak_indicator` to `channel[i].vu_l->get_value()`... I never get the expected result.
If one of the conditionals only needed to check if they're equal, I'd have tried it before... I'll see how I can implement that function in this case and try it

File: editor/settings/editor_settings.cpp (hunk 4 above)
Comment (Akosmo) [reply editor/settings/editor_settings.cpp]: The colors of the meters stand out a lot in the default theme, and if you're going for a specific palette, or find the colors too saturated, or even deal with colorblindness, being able to change those colors are important. They mean something.
Also, the editor has many settings for colors already. I don't think this is a big addition in my opinion.

File: editor/audio/editor_audio_buses.cpp (hunk 3 above)
Comment (Akosmo) [reply editor/audio/editor_audio_buses.cpp]: Got it working with `is_equal_approx()`.

File: editor/settings/editor_settings.cpp (hunk 4 above)
Comment (YeldhamDev) [reply editor/settings/editor_settings.cpp]: Very well, not a hill I plan to die on.

**Review by YeldhamDev — CHANGES_REQUESTED** [review]
I think it's almost good to go, but I believe the old texture should be removed. Nothing else makes use of it as far as I'm aware.

**Comment by romgerman** [comment]
You could also paint the peak volume indicators red when the bus is peaking

https://github.com/user-attachments/assets/a7785aaf-af3e-43b7-87fc-977095cbafdd

**Comment by Ivorforce** [comment]
It seems in bitwig they're generally colored with whatever the bar would be at the same position, which sounds like a good idea.

**Comment by Akosmo** [comment]
About changing the color of the peak indicator, yea I've thought about that and considered it, but had decided to keep it white for simplicity. I thought the bar colors were good enough. But that's >1 person here considering it as well, so I might give it a try! I'm not sure I have a good reason not to.

**Comment by Akosmo** [comment]
> You could also paint the peak volume indicators red when the bus is peaking

I like a lot how the peak value is shown in numbers there. I wonder if I can make that fit anywhere.

**Comment by romgerman** [comment]
The bar shows the current volume which can change rapidly. Peak indicators show the max volume fading slowly for you to notice if there was any peaking at all. But if that's too much work for this PR it can be changed separately.

**Comment by Akosmo** [comment]
I made a small change which was suggested to me here: change the color of the peak indicator based on where it is on the meter. It should be even easier to tell if audio is clipping or not. It's open for review again. Should be all good.

https://github.com/user-attachments/assets/c84a2d8a-48a0-4f4b-83c5-69cc5a98c7e9

**Review by YeldhamDev — APPROVED** [review]
LGTM.

**Review by Ivorforce — APPROVED** [review]
Haven't looked at the code (which is all editor code), but audio and UX wise I agree with the changes, and that they're necessary.

File: editor/audio/editor_audio_buses.h [hunk 5]
```diff
@@ -43,6 +43,8 @@
 #include "scene/gui/slider.h"
 #include "scene/gui/texture_progress_bar.h"
 #include "scene/gui/tree.h"
+#include "scene/resources/gradient_texture.h"
+#include "scene/resources/style_box_flat.h"
```
Comment (AThousandShips) [inline editor/audio/editor_audio_buses.h]: These two should be forward declared

File: editor/audio/editor_audio_buses.cpp [hunk 6]
```diff
@@ -933,26 +1021,88 @@ EditorAudioBus::EditorAudioBus(EditorAudioBuses *p_buses, bool p_is_master) {
...
-		channel[i].vu_l->set_max(24);
-		channel[i].vu_l->set_step(0.1);
+		channel[i].vu_l->set_min(0);
+		channel[i].vu_l->set_max(1);
+		channel[i].vu_l->set_step(0.0001);
 		channel[i].vu_l->set_accessibility_name(vformat(TTR("Channel %d, Left VU"), i));
 
+		channel[i].peak_indicator_l = memnew(Panel);
+		channel[i].peak_indicator_l->set_custom_minimum_size(Size2(16.0, 2.0));
+		channel[i].peak_indicator_l->add_theme_style_override("panel", peak_indicator_stylebox_l);
```
Comment (AThousandShips) [inline editor/audio/editor_audio_buses.cpp]:
```suggestion
		channel[i].peak_indicator_l->add_theme_style_override(SceneStringName(panel), peak_indicator_stylebox_l);
```

File: editor/audio/editor_audio_buses.cpp [hunk 7]
```diff
@@ -933,26 +1021,88 @@ EditorAudioBus::EditorAudioBus(EditorAudioBuses *p_buses, bool p_is_master) {
...
+		channel[i].vu_r->set_min(0);
+		channel[i].vu_r->set_max(1);
+		channel[i].vu_r->set_step(0.0001);
 		channel[i].vu_r->set_accessibility_name(vformat(TTR("Channel %d, Right VU"), i));
 
-		channel[i].peak_l = 0.0f;
-		channel[i].peak_r = 0.0f;
+		channel[i].peak_indicator_r = memnew(Panel);
+		channel[i].peak_indicator_r->set_custom_minimum_size(Size2(16.0, 2.0));
+		channel[i].peak_indicator_r->add_theme_style_override("panel", peak_indicator_stylebox_r);
```
Comment (AThousandShips) [inline editor/audio/editor_audio_buses.cpp]:
```suggestion
		channel[i].peak_indicator_r->add_theme_style_override(SceneStringName(panel), peak_indicator_stylebox_r);
```

**Comment by romgerman** [comment]
Tested. Works fine. Looks good. Haven't tested the settings.

File: editor/audio/editor_audio_buses.h (hunk 5 above)
Comment (Akosmo) [reply editor/audio/editor_audio_buses.h]: I'm sorry, this is the first time I hear of "forward declaration". I'm reading about it, and just to be sure, you want me to remove those includes, and instead have on the header:

```cpp
class EditorAudioBuses;
class EditorFileDialog;
class GradientTexture2D;
class HBoxContainer;
class StyleBoxFlat;
class Timer;
```

Then on the C++ file, include:

```cpp
#include "scene/resources/gradient_texture.h"
#include "scene/resources/style_box_flat.h"
```

Is that right? Does that change anything else in the code?

Comment (AThousandShips) [reply editor/audio/editor_audio_buses.h]: Yes that would be all!

Comment (Akosmo) [reply editor/audio/editor_audio_buses.h]: Compiled to test, only working with both `Gradient` and `GradientTexture2D` declared. Good to commit? Other suggestions have been addressed.

Comment (AThousandShips) [reply editor/audio/editor_audio_buses.h]: Whatever works should be right

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by Repiteo** [comment]
Thanks!
