### PR TITLE
Make the alternative tile control correctly handle right-click dragging.

### LINKED ISSUE #62626: Right clicking on an alternative tile makes the tileset pans while opening the popup menu
### Godot version

4.0a11

### System information

Linux (Pop_OS!)

### Issue description

In the tileset dock, in the area where the tiles are, right-clicking and dragging on empty space pans the tiles. Right-clicking on a tile opens the pop-up menu but doesn't pan. But, right-clicking on an alternative tile (a simple click or click then drag) doesn't behave correctly. After the right mouse button is released, the menu opens (if it wasn't a drag) but panning continues. If during that state the mouse enters then leaves the popup menu, the tileset is moved far away.

https://user-images.githubusercontent.com/2700596/176996286-a6e7da07-3ebe-40ce-8527-c29a43ca37fa.mp4

*Note: the bottom-right overlay shows when I right click.*

### Steps to reproduce

1. Setup a tileset.
2. Add an alternative tile.
3. Right click on an alternative tile.

### Minimal reproduction project

[Godot 4 Bughunt.zip](https://github.com/godotengine/godot/files/9032809/Godot.4.Bughunt.zip)

### PR DESCRIPTION
**Pull request by linkpy**
Fixes #62626 

I am not sure if it is all correct (like, regarding `drag_start_mouse_pos`) but this fixes the bug.

### CODE REVIEW

**Comment by groud** [comment]
I am not sure how mouse events are handled while dragging, but IIRC, if you start dragging on a given control, this control will keep receiving MouseMotion events even if you drag outside of it. If that's the case as I think it is, I think your fix only needs a few changes to be good.

To do so you should replicate and adapt those lines from `_tile_atlas_control_gui_input` into `_tile_alternatives_control_gui_input`: 
```
else if (drag_type == DRAG_TYPE_MAY_POPUP_MENU) {
				if (Vector2(drag_start_mouse_pos).distance_to(tile_atlas_control->get_local_mouse_position()) > 5.0 * EDSCALE) {
					drag_type = DRAG_TYPE_NONE;
				}
			} 
```

File: editor/plugins/tiles/tile_set_atlas_source_editor.cpp [hunk 1]
```diff
@@ -1911,6 +1911,9 @@ void TileSetAtlasSourceEditor::_tile_alternatives_control_gui_input(const Ref<In
 			}
 		} else if (mb->get_button_index() == MouseButton::RIGHT) {
 			if (mb->is_pressed()) {
+				drag_type = DRAG_TYPE_MAY_POPUP_MENU;
+				drag_start_mouse_pos = alternative_tiles_control->get_local_mouse_position();
+			} else {
 				// Right click pressed
 				Vector3 tile = tile_atlas_view->get_alternative_tile_at_pos(mouse_local_pos);
```
Comment (groud) [inline editor/plugins/tiles/tile_set_atlas_source_editor.cpp:1918]: The popup of the menu should be conditioned by `if (drag_type == DRAG_TYPE_MAY_POPUP_MENU)`. The point is to only to popup the menu if you did not drag too far.

**Review by groud — CHANGES_REQUESTED** [review]

**Comment by linkpy** [comment]
I've implemented the requested changes and rebased on master.

**Comment by linkpy** [comment]
> > To do so you should replicate and adapt those lines from _tile_atlas_control_gui_input into _tile_alternatives_control_gui_input:
> 
> You still need to address that. The popup should not be displayed if you moved your mouse, which requires the lines mentionned in my previous comment to be added in the handling of mouse motion events on the alternative tiles' control node.

Sorry, I forgot about this part.
It should be okay now.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
