### PR TITLE
Return a correctly typed variant in case of function error

### LINKED ISSUE #57585: GDScript 2.0: Passing a typed array from an error function call crashes Godot
### Godot version

4.0 e6caaf4c800912517af783e90519cc2a70001e85, 4.0 alpha 1

### System information

Ubuntu 20.04 based distro (KDE neon)

### Issue description

If I call a function foo that returns a typed array and I pass the result to another function that accept an untyped array and for some reason foo raises an error, the returned array is garbage.
It doesn't happen when executing the scene because the debugger stops the execution when the error occurs.

Here's an example:

```gdscript
@tool
extends Node

func _get_property_list() -> Array:
    # If I put Array[Dictionary] as type, it doesn't crash
    var l1: Array = []
    l1.append_array(get_array([RefCounted.new()])) # Crash Here
    return l1
    
func get_array(input: Array) -> Array[Dictionary]:
    input[0].call_non_existing()
    return []
```

<details>
<summary>Stack trace</summary>

```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7eff47590210] (??:0)
[2] CowData<Variant>::_ref(CowData<Variant> const&) (/path/to/godot/build/core/templates/cowdata.h:368)
[3] Vector<Variant>::Vector(Vector<Variant> const&) (/path/to/godot/build/core/templates/vector.h:276)
[4] Array::append_array(Array const&) (/path/to/godot/build/core/variant/array.cpp:237)
[5] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/path/to/godot/build/modules/gdscript/gdscript_vm.cpp:1910)
[6] GDScriptInstance::get_property_list(List<PropertyInfo, DefaultAllocator>*) const (/path/to/godot/build/modules/gdscript/gdscript.cpp:1434)
[7] Object::get_property_list(List<PropertyInfo, DefaultAllocator>*, bool) const (/path/to/godot/build/core/object/object.cpp:659)
[8] EditorFolding::_fill_folds(Node const*, Node const*, Array&, Array&, Array&, Set<Ref<Resource>, Comparator<Ref<Resource> >, DefaultAllocator>&) (/path/to/godot/build/editor/editor_folding.cpp:?)
[9] EditorFolding::save_scene_folding(Node const*, String const&) (/path/to/godot/build/editor/editor_folding.cpp:?)
[10] EditorNode::_save_scene(String, int) (/path/to/godot/build/editor/editor_node.cpp:1747)
[11] EditorNode::_save_scene_with_preview(String, int) (/path/to/godot/build/editor/editor_node.cpp:?)
[12] EditorNode::_menu_option_confirm(int, bool) (/path/to/godot/build/editor/editor_node.cpp:?)
[13] Object::emit_signal(StringName const&, Variant const**, int) (/path/to/godot/build/core/object/object.cpp:?)
[14] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/path/to/godot/build/core/object/object.cpp:1159)
[15] PopupMenu::activate_item(int) (/path/to/godot/build/scene/gui/popup_menu.cpp:1410)
[16] PopupMenu::activate_item_by_event(Ref<InputEvent> const&, bool) (/path/to/godot/build/scene/gui/popup_menu.cpp:?)
[17] MenuButton::unhandled_key_input(Ref<InputEvent> const&) (/path/to/godot/build/scene/gui/menu_button.cpp:52)
[18] Node::_call_unhandled_key_input(Ref<InputEvent> const&) (/path/to/godot/build/scene/main/node.cpp:2668)
[19] SceneTree::_call_input_pause(StringName const&, SceneTree::CallInputType, Ref<InputEvent> const&, Viewport*) (/path/to/godot/build/scene/main/scene_tree.cpp:?)
[20] Viewport::push_unhandled_input(Ref<InputEvent> const&, bool) (/path/to/godot/build/scene/main/viewport.cpp:2732)
[21] Window::_window_input(Ref<InputEvent> const&) (/path/to/godot/build/scene/main/window.cpp:972)
[22] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/path/to/godot/build/core/variant/binder_common.h:?)
[23] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/path/to/godot/build/platform/linuxbsd/display_server_x11.cpp:?)
[24] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/path/to/godot/build/core/input/input.cpp:?)
[25] Input::flush_buffered_events() (/path/to/godot/build/core/input/input.cpp:872)
[26] DisplayServerX11::process_events() (/path/to/godot/build/platform/linuxbsd/display_server_x11.cpp:?)
[27] OS_LinuxBSD::run() (/path/to/godot/build/platform/linuxbsd/os_linuxbsd.cpp:340)
[28] /path/to/godot/build/bin/godot.linuxbsd.tools.64.llvm(main+0xb0) [0x43fb8e0] (/path/to/godot/build/platform/linuxbsd/godot_linuxbsd.cpp:60)
[29] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7eff475710b3] (??:0)
[30] /path/to/godot/build/bin/godot.linuxbsd.tools.64.llvm(_start+0x2e) [0x43fb76e] (??:?)
```
</details>

### Steps to reproduce

1. Extract the MRP in a project
2. Open the scene in the editor
3. Editor Crash

### Minimal reproduction project
[scene.zip](https://github.com/godotengine/godot/files/7994167/scene.zip) (not a project)

### PR DESCRIPTION
**Pull request by SaracenOne**
Adds a function to the GDScript VM to return a valid default Variant type based on the function definitions return_type in case of an error. This should prevent rare instances where the result of an explicitly typed array is passed into another function unchecked via something like OPCODE_CALL_BUILTIN_TYPE_VALIDATED and can subsequently causes a crash.
Closes #57585

### CODE REVIEW

File: modules/gdscript/gdscript_vm.cpp [hunk 1]
```diff
@@ -123,6 +123,31 @@ static String _get_var_type(const Variant *p_var) {
 }
 #endif // DEBUG_ENABLED
 
+Variant GDScriptFunction::_get_default_variant_for_data_type(const GDScriptDataType &p_data_type) {
+	if (p_data_type.kind == GDScriptDataType::BUILTIN) {
+		if (p_data_type.builtin_type == Variant::ARRAY) {
+			Array array;
+			// Typed array.
+			if (p_data_type.has_container_element_type()) {
+				const GDScriptDataType &element_type = p_data_type.get_container_element_type();
```
Comment (akien-mga) [inline modules/gdscript/gdscript_vm.cpp:132]:
```
modules/gdscript/gdscript_vm.cpp:132:29: error: unused variable 'element_type' [-Werror,-Wunused-variable]
                                const GDScriptDataType &element_type = p_data_type.get_container_element_type();
                                                        ^
```

Comment (SaracenOne) [reply modules/gdscript/gdscript_vm.cpp:132]: Yeah, mistake on my part. Fixing it properly now

**Review by vnen — APPROVED** [review]
Looks good, thanks!

**Comment by akien-mga** [comment]
Thanks!
