### PR TITLE
Fix incorrect default transform values on foreign 3D nodes

### LINKED ISSUE #56434: Node3D Position/Rotation/Scale does not show proper defaults in inspector on foreign nodes
### Godot version

d58dfd4a7c02504c1fb5a436e0410420d6b30023

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

If you instance or inherit a scene, then examine the inspector properties of either its root node or children, the default value on Node3Ds will not be accurate to those in the scenes you derive from. This is due to the fact that the inspector now represents local transform as seperate position, rotation, and scale properties, but still internally stores everything as a single Transform3D. The default behaviour when searching for properties default value is to simply compare it against the properties in the inherited SceneState objects, but since this only stores a "transform" property, the defaults for properties like "position", "rotation", "quaternion", "basis", or "scale" cannot be found, thus will always ignore the defaults from the scenes they inherit from.

There may be other similar issues with other editor properties, but 3D transforms are the most notable.

### Steps to reproduce

In the example project, check the transform of the instanced child cube in RootScene.tscn and note how its default value is a default Transform3D, despite the fact that if you check the file Instance.tscn, the cube's actual default should be what it's set to in that file.

### Minimal reproduction project

[default_values_incorrect.zip](https://github.com/godotengine/godot/files/7799357/default_values_incorrect.zip)

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes #56434
Introduces property_can_revert and property_get_revert methods to Node3D to work around the problem described in the issue. Does this by getting the default value for "transform" then converting it to the desired editor property.

### CODE REVIEW

File: scene/3d/node_3d.cpp [hunk 1]
```diff
@@ -845,6 +846,84 @@ void Node3D::_validate_property(PropertyInfo &property) const {
...
+}
+
+Variant Node3D::property_get_revert(const String &p_name) {
+	Variant r_ret;
+	bool valid = false;
+
+	if (p_name == "basis") {
+		Variant variant = PropertyUtils::get_property_default_value(this, "transform", &valid);
+		if (valid) {
+			if (variant.get_type() == Variant::Type::TRANSFORM3D) {
```
Comment (RandomShaper) [inline scene/3d/node_3d.cpp:871]: Suggestion: make these checks more compact by writing them as `if (valid && variant.get_type() == Variant::Type::...)` so that only one `else` branch is needed.

**Review by RandomShaper — APPROVED** [review]
Looks fine.

**Review by JFonS — APPROVED** [review]
Looks good to me.

File: scene/3d/node_3d.cpp [hunk 2]
```diff
@@ -916,6 +995,9 @@ void Node3D::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("to_local", "global_point"), &Node3D::to_local);
 	ClassDB::bind_method(D_METHOD("to_global", "local_point"), &Node3D::to_global);
 
+	ClassDB::bind_method(D_METHOD("property_can_revert"), &Node3D::property_can_revert);
+	ClassDB::bind_method(D_METHOD("property_get_revert"), &Node3D::property_get_revert);
```
Comment (akien-mga) [inline scene/3d/node_3d.cpp:999]: You need to define the argument name:
```suggestion
	ClassDB::bind_method(D_METHOD("property_can_revert", "name"), &Node3D::property_can_revert);
	ClassDB::bind_method(D_METHOD("property_get_revert", "name"), &Node3D::property_get_revert);
```

**Comment by SaracenOne** [comment]
Updated with suggestion from @RandomShaper to make the if/else chain more compact, and added parameter name as @akien-mga mentioned which should make this PR pass the test suite now

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
