### PR TITLE
Scroll `EditorInspector` while drag & drop hovering near the edges

### LINKED ISSUE #103925: ScrollContainer doesn't scroll during drag & drop like Tree does
### Tested versions

4.5 master

### System information

Windows 10

### Issue description

While working on #103738, I noticed the SceneTree and FileSystem will scroll while drag & drop is held near the edge, but not the inspector, which is a ScrollContainer

### Steps to reproduce

Inspect some node and expand sections until it is scrollable.
Try dragging something like a file near the edges, it will not scroll.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dugramen**
Closes #103925. 

The scroll code is mostly just copied from Tree for the same behavior, but scroll_border and scroll_speed is hardcoded. I can make them theme properties for ScrollContainer, like it is for Tree, if desired

https://github.com/user-attachments/assets/8885d79b-5009-4a3c-a851-668e3dfccf97

### CODE REVIEW

**Comment by KoBeWi** [comment]
The scrolling speed is way too low.
Also properties can unfold while hovered. It should not happen when the inspector scrolls (scrolling could just reset the unfold timer).

File: scene/gui/scroll_container.h [hunk 1]
```diff
@@ -123,6 +124,9 @@ class ScrollContainer : public Container {
 	bool is_following_focus() const;
 	void set_follow_focus(bool p_follow);
 
+	bool is_scroll_on_drag_hover() const;
```
Comment (KoBeWi) [inline scene/gui/scroll_container.h:127]: The getter is never used, so you don't need to add it.

**Comment by dugramen** [comment]
> The scrolling speed is way too low.
> Also properties can unfold while hovered. It should not happen when the inspector scrolls (scrolling could just reset the unfold timer).

Would it be ok to reuse the scroll speed from Tree, with `get_theme_constant("scroll_speed", "Tree")`

**Comment by KoBeWi** [comment]
If the scrolling on drag option is not exposed then it's probably acceptable. Be sure to cache the value though.

**Comment by dugramen** [comment]
> Also properties can unfold while hovered. It should not happen when the inspector scrolls (scrolling could just reset the unfold timer).

Was gonna implement a fix today but I couldn't find a way to reliably detect a scroll in `EditorInspectorSection`. All the scroll notifications say they only fire for touch events. And `NOTIFICATION_RESIZED` and `NOTIFICATION_TRANSFORM_CHANGED` don't seem to respond to scroll either.

I also noticed the scene tree has the same problem, where nodes will sometimes be inspected while hover scrolling. It should be easier to fix there, since it all happens in the same node. But I'm not sure how to handle it for folded sections?

**Comment by KoBeWi** [comment]
The scrolling is still super slow for some reason:

https://github.com/user-attachments/assets/e1364468-2547-4a5a-9bf2-7ccfa1318a38

Compare with Tree:

https://github.com/user-attachments/assets/9708ed72-2080-459c-b30d-516abf4b1481

File: scene/gui/scroll_container.cpp [hunk 2]
```diff
@@ -453,6 +467,31 @@ void ScrollContainer::_notification(int p_what) {
...
 				}
 			}
+
+			if (scroll_on_drag_hover && get_viewport()->gui_is_dragging()) {
+				Point2 mouse_position = get_viewport()->get_mouse_position() - get_global_position();
+				Transform2D xform = get_transform();
+				if (Rect2(Point2(), xform.get_scale() * get_size()).grow(scroll_border).has_point(mouse_position)) {
+					Point2 point;
+
+					if ((ABS(mouse_position.x) < ABS(mouse_position.x - get_size().width)) && (ABS(mouse_position.x) < scroll_border)) {
```
Comment (KoBeWi) [inline scene/gui/scroll_container.cpp:477]: Needs to be changed to `Math::abs`.

**Comment by dugramen** [comment]
> The scrolling is still super slow for some reason:

I'm not experiencing this so idk how to test / fix it. The only difference between this and Tree I noticed is that this was using internal physics process, while tree uses internal process. I just changed it to also use internal process, so maybe that fixes it?

**Comment by KoBeWi** [comment]
That fixed it.

**Review by KoBeWi — APPROVED** [review]
The title is a bit misleading. The scrolling is enabled only in the inspector, the ScrollContainer property is not exposed.

**Review by AThousandShips — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected at various editor scales. The scrolling is smooth on a 120 Hz display (i.e. it's not bound to the physics tick rate).

Code looks good to me.

**Comment by akien-mga** [comment]
Thanks!
