### PR TITLE
[4.3] Fix animation snapping in seconds mode

### LINKED ISSUE #98609: Animation editor key snapping is rounded to some predetermined value instead of using exact snap value
### Tested versions

- Reproducible in : 4.4.dev3, 4.4.dev2
- Not reproducible in : 4.2.2.stable

### System information

Windows 11 - Godot v4.4.dev3

### Issue description

When you set time snap value in animation editor and you try to create or move key, the result key time value is rounded to some predetermined value instead of using exact number to snap.
Some examples:
- If snap value is 0.15, key is actually snapped to value 0.1429
- If snap value is 0.225 or 0.275, key is actually snapped to value 0.25
- If snap value is 0.3 or 0.4, key is actually snapped to value 0.3333333...
- If snap value is from 0.45 to 0.75, key is actually snapped to value 0.5
- If snap value is bigger than 0.75, key is actually snapped to value 1
The same rules apply for any integer value like 2.225 is snapped to 2.25, or 4.3 is snapped to 4.33333...

Note that timeline cursor doesn't have this issue and it snaps correctly to exact snap value, no matter how much decimal part is.

### Steps to reproduce

1.) Create AnimationPlayer, some Sprite or ColorRect, and create some simple moving animation for it
2.) Try to set snapping value to 0.25, 0.3, 0.425, 0.45 and 0.75 and try to create new key or move existing one and see that it snaps to incorrect value, while timeline cursor is moving correctly (when timeline cursor snap is enabled)

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/17541034/MRP.zip)

### PR DESCRIPTION
**Pull request by UnfavorableEnhancer**
Closes #98609 for 4.3 branch as TokageItLab suggested to do

Fixes animation snapping rounding to weird values in seconds mode + fixes holding shift not lowering snap value as intended.

### CODE REVIEW

**Review by TokageItLab — APPROVED** [review]

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -7052,25 +7052,24 @@ void AnimationTrackEditor::_update_snap_unit() {
...
-		fraction = 1.0 / Math::round(1.0 / fraction);
-		snap_unit = integer + fraction;
+		snap_unit = step->get_value();
 	}
 }
 
 float AnimationTrackEditor::snap_time(float p_value, bool p_relative) {
 	if (is_snap_enabled()) {
+		double current_snap = snap_unit;
+
```
Comment (TokageItLab) [inline editor/animation_track_editor.cpp:7062]:
```suggestion
```

**Review by TokageItLab — CHANGES_REQUESTED** [review]

**Review by TokageItLab — APPROVED** [review]
Please fixup this PR into one commit to follow [PR workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

**Comment by UnfavorableEnhancer** [comment]
Fixed-up into single commit

**Comment by AThousandShips** [comment]
Is there any specific reason this is done in 4.3 only? Is a separate fix planned for 4.4?

**Comment by akien-mga** [comment]
Thanks!
