### PR TITLE
Don't allow duplicate events in input actions editor

### LINKED ISSUE #87707: Input map action with two exact events in the project settings will have one event missing
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

 Windows 10

### Issue description

I have a key rebinding menu where player is allowed to have two sets of keybindings for actions (one of them being and alternative input for keyboard)
image
If I were to edit the second event to be the same as the first one (W press), and then in the code go over the events, there will be only two events mapped to the action (W and joystick)

The issue is about making sure that what is visible in the Project's Settings Input map matches the thing we get in code.
If I see 3 events mapped to the action, I expect  ```InputMap.action_get_events("action").size()``` return 3.

Possible solutions:
* Making sure InputMap in code has all events defined in Project Settings
* If making it work with exact events mapped to the action is problematic then we should see a warning that this event is already added and not be allowed to add it. There also needs to be same check when editing existing event

### Steps to reproduce

1. Create an action (called "action" for example) in the Project's Settings Input map with 3 or more events, two or more should be the same
2. Create a script and put the following line in the _ready
3. ```print(InputMap.action_get_events("action").size());```
4. The number printed will be less than the number of events mapped to the action

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/14087015/MRP.zip)

### LINKED ISSUE #95283: Mapping the same button infinite times is possible.
### Tested versions

v4.3.rc2.official [3978628c6]

### System information

w10 64

### Issue description

As can be seen in the screenshot, Godot always detects the same press as a new button.
Shouldn't godot not add the button if it's already added to the action?

In the image you can see that the same button has been added to the same action 4 times.

Captura6

### Steps to reproduce

...

### Minimal reproduction project (MRP)

...

### PR DESCRIPTION
**Pull request by Nintorch**
Fixes https://github.com/godotengine/godot/issues/87707
Fixes https://github.com/godotengine/godot/issues/95283

This PR checks if the `InputEvent` the user is trying to add to an action already exists in that action, and if it does, the user is not allowed to add it again. Previously, it was allowed.

https://github.com/user-attachments/assets/4200d551-3953-45af-bfa9-3dacb9133b34

* *Bugsquad edit, supersedes: https://github.com/godotengine/godot/pull/97673*

### CODE REVIEW

File: editor/settings/input_event_configuration_dialog.cpp [hunk 1]
```diff
@@ -596,8 +611,19 @@ void InputEventConfigurationDialog::_notification(int p_what) {
...
 }
 
-void InputEventConfigurationDialog::popup_and_configure(const Ref<InputEvent> &p_event, const String &p_current_action_name) {
+void InputEventConfigurationDialog::popup_and_configure(const Ref<InputEvent> &p_event, const String &p_current_action_name, const Dictionary &p_current_action) {
+	action_events = p_current_action["events"];
+
 	if (p_event.is_valid()) {
+		for (int i = 0; i < action_events.size(); i++) {
+			Ref<InputEvent> ie = action_events[i];
+			if (!ie.is_valid()) {
```
Comment (AThousandShips) [inline editor/settings/input_event_configuration_dialog.cpp]:
```suggestion
			if (ie.is_null()) {
```

File: editor/settings/input_event_configuration_dialog.cpp [hunk 2]
```diff
@@ -56,6 +56,19 @@ void InputEventConfigurationDialog::_set_event(const Ref<InputEvent> &p_event, c
 		// Update Label
 		event_as_text->set_text(EventListenerLineEdit::get_event_text(event, true));
 
+		bool exists = false;
+		for (int i = 0; i < action_events.size(); i++) {
+			Ref<InputEvent> ie = action_events[i];
+			if (!ie.is_valid()) {
```
Comment (AThousandShips) [inline editor/settings/input_event_configuration_dialog.cpp]:
```suggestion
			if (ie.is_null()) {
```

File: editor/settings/input_event_configuration_dialog.cpp [hunk 3]
```diff
@@ -778,4 +805,9 @@ InputEventConfigurationDialog::InputEventConfigurationDialog() {
 	additional_options_container->add_child(location_container);
 
 	main_vbox->add_child(additional_options_container);
+
+	event_exists = memnew(Label(TTRC("Error: this action already contains this input event.")));
```
Comment (AThousandShips) [inline editor/settings/input_event_configuration_dialog.cpp]:
```suggestion
	event_exists = memnew(Label(TTRC("Error: This action already contains this input event.")));
```

**Comment by Nintorch** [comment]
I added a video to show how this PR works and what the result looks like!

**Review by AdriaandeJongh — APPROVED** [review]
Didn't look at the code but the usability looks good to me.

**Comment by AdriaandeJongh** [comment]
that will help this PR, agreed!

File: editor/settings/input_event_configuration_dialog.cpp [hunk 4]
```diff
@@ -56,6 +56,19 @@ void InputEventConfigurationDialog::_set_event(const Ref<InputEvent> &p_event, c
 		// Update Label
 		event_as_text->set_text(EventListenerLineEdit::get_event_text(event, true));
 
+		bool exists = false;
+		for (int i = 0; i < action_events.size(); i++) {
+			Ref<InputEvent> ie = action_events[i];
```
Comment (KoBeWi) [inline editor/settings/input_event_configuration_dialog.cpp]:
```suggestion
		for (const Variant &v : action_events) {
			Ref<InputEvent> ie = v;
```
(not 100% it works like that though)

**Review by KoBeWi — APPROVED** [review]
