### PR TITLE
Fix missing hover style for Ignore Error breaks button

### LINKED ISSUE #109663: The Ignore Error Breaks toggle button is missing a highlight coloring
### Tested versions

Reproducible in: Godot v4.5.beta5

### System information

Godot v4.5.beta5.mono - Windows 11 (build 26200) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.7602) - 12th Gen Intel(R) Core(TM) i7-12700H (20 threads) - 15.62 GiB memory

### Issue description

The Ignore Error Breaks toggle button is missing a highlight color, unlike the Skip Breakpoints toggle next to it, which makes it hard to distinguish whether it’s interactable or not

Ignore Error Breaks Toggle:
Image

Skip Breakpoints toggle:
Image

### Steps to reproduce

Go to debugger tab stack trace and hover at the bell icon (Ignore Error Breaks Toggle)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/109663

After:

Screenshot_20250816_152616

### CODE REVIEW

File: editor/debugger/script_editor_debugger.cpp [hunk 1]
```diff
@@ -2011,7 +2011,7 @@ ScriptEditorDebugger::ScriptEditorDebugger() {
 		skip_breakpoints->connect(SceneStringName(pressed), callable_mp(this, &ScriptEditorDebugger::debug_skip_breakpoints));
 
 		ignore_error_breaks = memnew(Button);
-		ignore_error_breaks->set_flat(true);
+		ignore_error_breaks->set_theme_type_variation(SceneStringName(FlatButton));
 		ignore_error_breaks->set_tooltip_text(TTR("Ignore Error Breaks"));
 		hbc->add_child(ignore_error_breaks);
 		ignore_error_breaks->connect("pressed", callable_mp(this, &ScriptEditorDebugger::debug_ignore_error_breaks));
```
Comment (arkology) [inline editor/debugger/script_editor_debugger.cpp]: This is not related to current PR, but I suppose it will be good to change `"pressed"` to `SceneStringName(pressed)`

**Review by KoBeWi — APPROVED** [review]

File: editor/debugger/script_editor_debugger.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/debugger/script_editor_debugger.cpp]: It can be done here.

Comment (Giganzo) [reply editor/debugger/script_editor_debugger.cpp]: Added the SceneStringName(pressed)

**Comment by Repiteo** [comment]
Thanks!
