### PR TITLE
Remove warning when project setting requests a larger global shader uniform buffer than the hardware supports

### LINKED ISSUE #85374: global_shader_variables/buffer_size set too high in new Compatibility project
### Godot version

4.2.rc2

### System information

macOS 14.1

### Issue description

Creating a new Compatibility project the default setting for rendering/limits/global_shader_variables/buffer_size is set to 65536, but apparently this is too high for Compatibility renderer limits, because you get a warning when running:

```
W 0:00:00:0093   MaterialStorage: Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 16384
  <C++ Source>   drivers/gles3/storage/material_storage.cpp:1114 @ MaterialStorage()
```

### Steps to reproduce

Create a new blank Compatibility project, with an empty scene and run it and see the warning

### Minimal reproduction project

Just create a new project from the project manager as I think the issue is the default value for new  Compatibility projects.

### PR DESCRIPTION
**Pull request by clayjohn**
Instead provide a better error message when the limit is exceeded and avoid crash with a small limit.

Fixes: https://github.com/godotengine/godot/issues/85374

Tagging for 4.3 since the warning is now shown on every project now that we properly calculate the maximum buffer size.

In the future we may want to explore a way to provide more global uniforms (i.e. provide multiple UBOs or store data in a texture). But we should only do that if there is significant demand. This should be fine for now.

### CODE REVIEW

File: drivers/gles3/storage/material_storage.cpp [hunk 1]
```diff
@@ -1999,7 +1999,7 @@ int32_t MaterialStorage::global_shader_parameters_instance_allocate(RID p_instan
 	ERR_FAIL_COND_V(global_shader_uniforms.instance_buffer_pos.has(p_instance), -1);
 	int32_t pos = _global_shader_uniform_allocate(ShaderLanguage::MAX_INSTANCE_UNIFORM_INDICES);
 	global_shader_uniforms.instance_buffer_pos[p_instance] = pos; //save anyway
-	ERR_FAIL_COND_V_MSG(pos < 0, -1, "Too many instances using shader instance variables. Increase buffer size in Project Settings.");
+	ERR_FAIL_COND_V_MSG(pos < 0, -1, vformat("Too many instances using shader instance variables. Consider increasing rendering/limits/global_shader_variables/buffer_size in the Project Settings. Maximum items supported by this hardware is: " + itos(uint32_t(Config::get_singleton()->max_uniform_buffer_size) / sizeof(GlobalShaderUniforms::Value)) + "."));
```
Comment (akien-mga) [inline drivers/gles3/storage/material_storage.cpp:2002]: Seems like you added `vformat` but then forgot to use it.

With `vformat` this should be:
```suggestion
	ERR_FAIL_COND_V_MSG(pos < 0, -1, vformat("Too many instances using shader instance variables. Consider increasing rendering/limits/global_shader_variables/buffer_size in the Project Settings. Maximum items supported by this hardware is: %d.", uint32_t(Config::get_singleton()->max_uniform_buffer_size) / sizeof(GlobalShaderUniforms::Value)));
```
Same for the other one if you decide to use `vformat` here.

**Review by akien-mga — APPROVED** [review]

File: drivers/gles3/storage/material_storage.cpp (hunk 1 above)
Comment (akien-mga) [reply drivers/gles3/storage/material_storage.cpp]: Amended it myself.

**Review by 888OPENHASH888 — APPROVED** [review]
