### PR TITLE
Fix navigation support for multilayered TileMaps

### LINKED ISSUE #69743: The problem about tilemap navigation
### Godot version

v4.0.beta7.mono.official.0bb1e89fb

### System information

Windows11 Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Hi. My tilemap has two layer:
1. Layer 1 (Low)
2.  Layer 2 (High)

In Layer 1 I place a grassland tile at (0,0), it is navigable. In Layer 2 I place a wall tile at (0,0), it un support navigation.
So, in fact (0,0) in tilemap should be non navigable, but it is still navigable.

I solved this problem by add a Nav Layer (more high) and place transparent navigable tile on where navigation needs to be supported

Is there a better solution?

### Steps to reproduce

N/A

### Minimal reproduction project

[Godot4Tilemap.zip](https://github.com/godotengine/godot/files/10183583/Godot4Tilemap.zip)

### PR DESCRIPTION
**Pull request by smix8**
Fixes navigation support for multilayered TileMaps by automatically creating dedicated navigation maps for each layer. Each navigation map holds the TileSet designed navigation polygons for navigation regions on that specific TileMap layer.

Fixes https://github.com/godotengine/godot/issues/69743 and properly other TileMap navigation issues that expected the TileMap layer layers system to work with navigation.

Mesh based navigation compared to pure point graphs like e.g. AStar2D has the core limitation that edges can not overlap or intersect, at least not when they should be merged and the navigation should make any sense. The TileMap was throwing every navigation polygon from all TileMap layers on the same navigation map creating conflicts between all the polygons.

Now with dedicated navigation maps for each layer this conflict problem does no longer exist and users can quickly receive the map for a layer from the TileMap and assign it for usage to a NavigationAgent2D whenever they switch their 2D actors logically  between the "vertical" TileMap layers.

``` gdscript
var navigation_agent : NavigationAgent2D
var tile_map : TileMap

var tile_map_layer_lower_level : int = 0
var tile_map_layer_upper_level : int = 1

...

func use_stair_to_upper_level_function(): 
    navigation_agent.set_navigation_map(tile_map.get_navigation_map(tile_map_layer_upper_level))

...

func jump_down_to_lower_level_function():
    navigation_agent.set_navigation_map(tile_map.get_navigation_map(tile_map_layer_lower_level))

```

This solution has the added bonus that it not only works for navigation pathfinding and server region sync but also for avoidance. Agents on different navigation maps will not avoid each other through "floors" even if they are close or on top of each other on the "vertical TileMap layers. Since the NavigationServer does not process update unchanged maps it can also help with navigation map sync performance when regions are changed at runtime.

### CODE REVIEW

File: scene/2d/tile_map.h [hunk 1]
```diff
@@ -215,6 +215,14 @@ class TileMap : public Node2D {
 	LocalVector<TileMapLayer> layers;
 	int selected_layer = -1;
 
+	// Navigation
+	struct TileMapNavigationLayer {
+		String name;
+		RID navigation_map;
+		bool uses_default_map = false;
```
Comment (DarkKilauea) [inline scene/2d/tile_map.h:222]: You might want to avoid using a flag to determine if the map is the world's default map, since a user could use `set_navigation_map` to assign the world's map to multiple layers, which may then be freed in `_navigation_cleanup_layer`.  Instead, I'd actually compare the RID of the navigation map to the one in the world to determine if you need to free it.

Comment (smix8) [reply scene/2d/tile_map.h:222]: I was not sure if the TileMap cleanup layer functions would only ever be call while in the SceneTree. The issue is that  get_world_2d().get_navigation_map() crashes when called while not in the SceneTree so I went with this compromise to track the default map.

**Review by DarkKilauea — APPROVED** [review]
From a navigation standpoint, it looks fine to me.

**Review by groud — APPROVED** [review]
Looks good enough. I am not super convinced by the idea of using the default map for the first layer, as the background is often on the last layer instead. But well, I have not a better idea, so I guess that's fine to avoid user issues for now.

Eventually, I think I would prefer the TileMap node to automatically compute a "merged polygon" that would avoid those issues, but that's an accepable solution for now.

**Comment by akien-mga** [comment]
Thanks!
