### PR TITLE
Fixing misleading error message when trying to export

### LINKED ISSUE #26539: Misleading error message when trying to Export all to non-existent directory
**Godot version:**
3.1 beta10

**Issue description:**
Since few versions, there's this "Export All" button that exports everything with a single press of a button. It uses the directory path you provide in export window. The problem is, if the path points to non-existent directory, instead of telling this Godot says that "Export templates for this platform are missing/corrupted".

**Steps to reproduce:**
1. Create a project
2. Export it into some directory
3. Delete that directory
4. Try to export again with "Export All" button
5. ~~Forget that you are reproducing issue and try to figure out what you did wrong~~

### PR DESCRIPTION
**Pull request by rluders**
This patch fixes the misleading error message when users try to "Export all" into an invalid destination path.

It's not perfect, but I think that it will do the job. It's being a while since I wrote something in C++, but I would like to get back my skills, in this case, I'm all in for constructive reviews.

Also, I notice that we have too many places throwing errors, is that expected? Sometimes we have two messages, one for warning immediately followed by an error message.

Closes #26539

### CODE REVIEW

File: platform/osx/export/export.cpp [hunk 1]
```diff
@@ -425,6 +425,10 @@ Error EditorExportPlatformOSX::export_project(const Ref<EditorExportPreset> &p_p
 		}
 	}
 
+	if (!FileAccess::exists(p_path.get_base_dir())) {
+		return ERR_FILE_BAD_PATH;
```
Comment (akien-mga) [inline platform/osx/export/export.cpp]: What about other platforms?

Comment (rluders) [reply platform/osx/export/export.cpp]: I did only found this for JavaScript and OSX. Do you have any ideas where I can found it for the other platforms?

Comment (akien-mga) [reply platform/osx/export/export.cpp]: It's in `platform/*/export/export.cpp` for each platform.

Comment (rluders) [reply platform/osx/export/export.cpp]: Let me double check it.

**Comment by bojidar-bg** [comment]
Something went real wrong with the rebase, probably it was done in the wrong direction?

**Comment by akien-mga** [comment]
Thanks!
