### PR TITLE
Reset TileMap editor `drag_type` when the toolbar mode is not selected

### LINKED ISSUE #85077: TileMap Painting by accident when switching between editor Select Mode (Q) and Move Mode (W)
### Godot version

4.2 RC1

### System information

Windows 11 

### Issue description

While working with the TileMap following a tutorial I've ran into several issues that turned out to be related to persistence of modes between tools (Select, Scale, Erase, and Move). I tried to write a report only to stumble on the reproduction steps, but solved most the issue myself when figuring out persistence of these modes. 

The remaining bug I've identified is when in paint mode in the tilemap, select mode in the editor, where you paint a large line between move positions when using hotkeys to switch between move and select mode.

### Steps to reproduce

1) Pain a tile line of tiles (any direction or length)
2) Press W to switch to move mode while having not released the left mouse button
3) Let got of left mouse, use move mode drag the screen to a new position (method doesn't matter middles click or left mouse)
4) Press Q to switch editor to select mode.
5) A line will be created for the entire path you have move the mouse through, further you'll be stuck active painting where ever the mouse moves until you left click again.

I've also observed some others behaviors that are odd such as snap moving to the mouse position when transitioning to move mode. I suspect its related.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Wiltof**
this fixes : https://github.com/godotengine/godot/issues/85077

The problem made it so that the drag_type was kept until the toolbar mode SELECT was once again pressed. This made it so tilemap was drawing automatically without having to press down the left mouse button. By changing drag type to none when select is not used, this is fixed.

### CODE REVIEW

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by Wiltof** [comment]
> For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

Godammit. Thank you for telling me. Will I need to fix this for the pull request to be approved?

**Comment by akien-mga** [comment]
It's not absolutely mandatory, but your GitHub account will not be recognized as the author of this change. It's easy to fix by either changing your local Git identify and amending the commit (`git commit --amend --reset-author`), or adding your student email used to author this commit as secondary email on your GitHub account.

**Comment by Wiltof** [comment]
> It's not absolutely mandatory, but your GitHub account will not be recognized as the author of this change. It's easy to fix by either changing your local Git identify and amending the commit (`git commit --amend --reset-author`), or adding your student email used to author this commit as secondary email on your GitHub account.

Okay it should be fixed now, I simply added the email address

**Comment by akien-mga** [comment]
It didn't seem effective yet, make sure it's the address shown in the header of https://github.com/godotengine/godot/pull/86066.patch, and you might have received an email from GH there to confirm adding it.

**Comment by akien-mga** [comment]
The last attempt at changing the author info worked, but there are now 3 commits:

image

When amending a commit, you should update with `git push --force` instead of merging the remote branch back, which keeps both the old and the new commits.

Now you can fix it with:
```
git fetch origin
git rebase -i origin/master
```

This should show:
```
pick 5c4b3d490a reset author
pick cc9183562d Sets drag_type of the tile_map_editor to none when the toolbar mode is not select
```

Change the second `pick` to `squash`, exit the text editor, and then you should have the opportunity of improving the commit message (as `reset author` isn't a good one). I'd suggest `Reset TileMap editor `drag_type` when the toolbar mode is not selected`.

The `git log` should then look like this:
```
commit 33aa9afd88251277d334b9b20c2ca543e96ac6bb (HEAD -> tilemapPaint)
Author: wilto938 <wilto938@student.liu.se>
Date:   Tue Dec 12 12:27:26 2023 +0100

    Reset TileMap editor `drag_type` when the toolbar mode is not selected

commit 84692c6252438393999c427bf7f5d35b9c43926c (origin/master, master)
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Tue Dec 12 11:00:06 2023 +0100

    Navigation: Fix GCC 12.3 `-Wtype-limits` warnings
```

And so you can force push to update your fork with `git push --force`.

**Comment by Wiltof** [comment]
Thank you so much for all your help, haha. I don't really understand how all those other commits showed up, but all's well that ends well

File: editor/plugins/tiles/tile_map_editor.cpp [hunk 1]
```diff
@@ -524,6 +524,7 @@ bool TileMapEditorTilesPlugin::forward_canvas_gui_input(const Ref<InputEvent> &p
 	}
 
 	if (CanvasItemEditor::get_singleton()->get_current_tool() != CanvasItemEditor::TOOL_SELECT) {
+		drag_type = DRAG_TYPE_NONE;
```
Comment (groud) [inline editor/plugins/tiles/tile_map_editor.cpp:527]: You should use `_stop_dragging();` instead. This functions makes sure nothing is in an inconsistent state once dragging is done.

**Review by groud — CHANGES_REQUESTED** [review]

File: editor/plugins/tiles/tile_map_editor.cpp (hunk 1 above)
Comment (Wiltof) [reply editor/plugins/tiles/tile_map_editor.cpp]: this should be fixed now

**Comment by groud** [comment]
Looks good. Could you please [squash the commit together](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) ?

**Comment by Wiltof** [comment]
> Looks good. Could you please [squash the commit together](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) ?

Done!

**Review by groud — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged Godot contribution!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.
