### PR TITLE
Stop `FileAccess::fix_path` from emitting errors for invalid UIDs

### LINKED ISSUE #101962: Unrecognized UID: "uid://a"
### Tested versions

4.4 beta1

### System information

W10

### Issue description

When opening project
```
Unrecognized UID: "uid://a"
```
is printed to the console.

I tracked the source to GDScript parser, but no idea what causes it.

### Steps to reproduce

Open MRP.

### Minimal reproduction project (MRP)

[Godot-Instance-Dock.zip](https://github.com/user-attachments/files/18521292/Godot-Instance-Dock.zip)

Includes .godot folder, because the error is rather finicky. There is a chance you still won't be able to reproduce it.

### PR DESCRIPTION
**Pull request by mihe**
Fixes #101962.

This is mostly a quick hack to prompt a discussion about a more proper fix, and maybe serve as a hold-over, but...

This adds a `ResourceUID::has_id` check to `FileAccess::fix_path`, before it tries to call `ResourceUID::text_to_id`, and instead just clears the output string if it's not a known UID, same as what this error check is already doing inadvertently by returning an empty `String` when it can't find the UID:

https://github.com/godotengine/godot/blob/51b0379e5502402d44818a4b6f301f544a5754f3/core/io/resource_uid.cpp#L199

Without this, you could otherwise pass perfectly reasonable (or not) but non-existent `uid://` paths to `FileAccess::fix_path` and it would emit the above mentioned error about `Unrecognized UID`, which is exactly what happens in places like the LSP server, where it runs every string literal in the GDScript file through `FileAccess::file_exists`, which in turn calls `FileAccess::fix_path`, as seen here:

https://github.com/godotengine/godot/blob/51b0379e5502402d44818a4b6f301f544a5754f3/modules/gdscript/language_server/gdscript_extend_parser.cpp#L207-L214

I feel like the proper fix is to change `FileAccess::fix_path` to instead return a `bool`, to indicate a failure to fix/resolve the path, like when trying to fix/resolve a non-existent UID, but since that would/should require changing quite a lot of call sites I settled for this for now.

The fact that the LSP server is running every GDScript string literal through `FileAccess::file_exists` is maybe a bit questionable as well, but that seems like more of a performance concern than anything else. `FileAccess::file_exists` should not throw errors on non-existent UIDs.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @HolonProduction as this seems LSP related.

File: core/io/file_access.cpp [hunk 1]
```diff
@@ -258,7 +258,11 @@ String FileAccess::fix_path(const String &p_path) const {
 		case ACCESS_RESOURCES: {
 			if (ProjectSettings::get_singleton()) {
 				if (r_path.begins_with("uid://")) {
-					r_path = ResourceUID::uid_to_path(r_path);
+					if (ResourceUID::has_uid(r_path)) {
+						r_path = ResourceUID::uid_to_path(r_path);
```
Comment (KoBeWi) [inline core/io/file_access.cpp]:
```suggestion
					const ResourceUID::ID id = ResourceUID::get_singleton()->text_to_id(r_path);
					if (ResourceUID::has_id(id)) {
						r_path = ResourceUID::get_id_path(id);
```
The new method results in multiple conversions, which can be easily avoided.

**Comment by HolonProduction** [comment]
> CC @HolonProduction as this seems LSP related.

The fact that the LSP runs every string through this, could probably be improved given that we have more fine grained knowledge about were a path is expected in the completion context, but it would require an architecture change to have this info available outside of completion.

Even if we'd do that, we'd still need a way to resolve the path, which fails silently, since even if a path is expected there could be a user error. So having this fail silently (or providing a silent alternative) seems necessary to me. Can't say anything about this specific implementation though.

Also a learning from the current situation of `Variant::get` and typed dictionaries: if we make this fail silently, please add a documentation comment to make this contract explicit! Otherwise we'll just get regressions in the future because this behavior changes.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
