### PR TITLE
Fix `TileMapEditorPlugin` crash by storing tilemap ID instead of pointer

### LINKED ISSUE #80609: `TileMapEditorPlugin` crash when closing tab
### Godot version

4.x latest 0308422f461dce11339896249e23ff02d978bfa0

### System information

All

### Issue description

Editor tab with `TileMap` can crash on closing the tab.

```
1   TileMapEditorPlugin::edit                                                                                                                                       tiles_editor_plugin.cpp   351  0x55555d13b2e4 
2   EditorNode::_plugin_over_edit                                                                                                                                   editor_node.cpp           890  0x55555bf70ce7 
3   EditorNode::hide_unused_editors                                                                                                                                 editor_node.cpp           2242 0x55555bf88b6c 
4   SceneTreeDock::_push_item                                                                                                                                       scene_tree_dock.cpp       1488 0x55555c3386e2 
5   SceneTreeDock::_selection_changed                                                                                                                               scene_tree_dock.cpp       2276 0x55555c3582a1 
6   call_with_variant_args_helper<SceneTreeDock>(SceneTreeDock *, void (SceneTreeDock:: *)(), Variant const * *, Callable::CallError&, IndexSequence<>)             binder_common.h           303  0x55555c42af09 
7   call_with_variant_args<SceneTreeDock>                                                                                                                           binder_common.h           417  0x55555c42ae79 
8   CallableCustomMethodPointer<SceneTreeDock>::call                                                                                                                callable_method_pointer.h 104  0x55555c42ad64 
9   Callable::callp                                                                                                                                                 callable.cpp              50   0x55555f921a7a 
10  Object::emit_signalp                                                                                                                                            object.cpp                1072 0x55555fcff623 
11  Object::emit_signal<>(StringName const&)                                                                                                                        object.h                  891  0x55555b28b203 
12  EditorSelection::_emit_change                                                                                                                                   editor_data.cpp           1292 0x55555bd07649 
13  call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass *, void (__UnexistingClass:: *)(), Variant const * *, Callable::CallError&, IndexSequence<>) binder_common.h           303  0x55555a859f19 
14  call_with_variant_args_dv<__UnexistingClass>                                                                                                                    binder_common.h           450  0x55555a859e7c 
15  MethodBindT<>::call(Object *, Variant const * *, int, Callable::CallError&) const                                                                               method_bind.h             331  0x55555a859c46 
16  Object::callp                                                                                                                                                   object.cpp                741  0x55555fcfcdcf 
17  Callable::callp                                                                                                                                                 callable.cpp              62   0x55555f921e77 
18  CallQueue::_call_function                                                                                                                                       message_queue.cpp         219  0x55555fcf7640 
19  CallQueue::flush                                                                                                                                                message_queue.cpp         324  0x55555fcf7eca 
20  SceneTree::physics_process                                                                                                                                      scene_tree.cpp            471  0x55555d2b1935 
... <More>                                                                                                                                                                                                        
```
It's crashing here:
```
void TileMapEditorPlugin::edit(Object *p_object) {
	if (tile_map) {
		tile_map->disconnect("changed", callable_mp(this, &TileMapEditorPlugin::_tile_map_changed));
	}
```
Where `p_object` is NULL, so it looks like it's trying to wipe the old tilemap from the plugin, but it is still accessing the old deleted tilemap.

There's no need to call this on a deleted tilemap as the destructor already does this:

```
TileMap::~TileMap() {
	if (tile_set.is_valid()) {
		tile_set->disconnect_changed(callable_mp(this, &TileMap::_tile_set_changed));
	}
```


### Steps to reproduce

Use MRP from #80088.

1) Open scene
2) Open `TileSet` dropdown in the `TileMap` inspector
3) Close tab
4) CRASH

### Minimal reproduction project

See above.

## Discussion
A number of ways of fixing, e.g.:
* Check validity by storing `ObjectID` and checking valid before use
* Signal to let tilemap editor know has been destroyed
* Use reference instead of raw pointer, so the object is preserved until `edit()` is called and it is assigned to something else.

### PR DESCRIPTION
**Pull request by lawnjelly**
Store the tilemap ObjectID instead of raw pointer, and check it is valid before access.

Fixes #80609 
Alternative to #80537

## Notes
* Stores `ObjectID` for all accesses rather than raw pointer
* Ref counting would have also maybe worked for this, but I don't think `Nodes` are ref counted.

### CODE REVIEW

**Comment by lawnjelly** [comment]
Amusingly, it looks like 4.1 already has a similar fix already applied. Maybe it got broken doing 4.2, or someone else noticed the same problem there in 4.1. :grinning:

**Comment by lawnjelly** [comment]
Failed the `GodotTest` CI, not sure why, am rerunning in case spurious, it's kind of hard to pin down where it is failing.

If it is genuine maybe there's an access of `ObjectDB` outside the lifetime or something. :man_shrugging: Will look if it fails again.

**Comment by KoBeWi** [comment]
I can't reproduce the crash, but I'm getting an error that should be crashing 🤔
image

File: editor/plugins/tiles/tiles_editor_plugin.cpp [hunk 1]
```diff
@@ -347,11 +348,18 @@ void TileMapEditorPlugin::_notification(int p_notification) {
 }
 
 void TileMapEditorPlugin::edit(Object *p_object) {
+	TileMap *tile_map = Object::cast_to<TileMap>(ObjectDB::get_instance(tile_map_id));
+
```
Comment (KoBeWi) [inline editor/plugins/tiles/tiles_editor_plugin.cpp:352]: This blank line is inconsistent with the above. Should be removed.

**Review by KoBeWi — APPROVED** [review]

**Comment by lawnjelly** [comment]
> I can't reproduce the crash, but I'm getting an error that should be crashing thinking

Both of these are consistent with `TileMap` being in the process of being destroyed (possibly at the same time on another thread?) before `TileMapEditorPlugin::edit()` is called with NULL to remove the reference.

The interesting bit is why the CI is failing (assuming not a false flag, I've run it twice), possibly memory corruption / double free going on. I'm not familiar enough with `ObjectDB` to know offhand if there's an order of destruction problem that could cause this, and I'm not really familiar with running the `GodotTest` locally.

I'm happy for you @KoBeWi to investigate, or use #80537 which is simpler and doesn't seem to cause this.

**Comment by KoBeWi** [comment]
Ah I missed that this is a separate PR from #80537. I though you just applied my requested changes 🙃
This one is more complex, but IMO more correct.

**Comment by lawnjelly** [comment]
> I can't reproduce the crash, but I'm getting an error that should be crashing thinking

Actually, thinking about it, this could come down to differences in our debuggers. Maybe mine is catching the access to deleted object early, and yours is running the function on the remnants of the deleted object.

To check the lifetime was the problem when I wrote this, I put a `bool` in the `TileMap` for whether it was active, and set it to false in the destructor. The data still existed in the object remnants, but the destructor had been called.

**Comment by akien-mga** [comment]
Thanks!
