### PR TITLE
Fix audio stream generators getting freed accidentally

### LINKED ISSUE #65155: Audio Stream Playback Generator Broken
### Godot version

Godot 4.X

### System information

Windows 11, Default WASAPI drivers, 

### Issue description

When running the audio generator demo. using `get_stream_playback()` returns `null` which causes `playback.get_frames_available()` to error out with `Attempt to call function 'get_frames_available' in base 'null instance' on a null instance.. `
I've tried writing a condition in the `_process()` function to check if it is `null` and retry getting the playback node. After a few cycles, it will return positive but will only fill the buffer once and will not process the frames any further, leaving `playback.get_frames_available()` to return `0` for the remainder of the runtime.
 
Code:
```
extends Node

var sample_hz = 44100/4.0 # Keep the number of samples to mix low, GDScript is not super fast.
var pulse_hz = 440.0
var phase = 0.0

var playback: AudioStreamPlayback = null # Actual playback stream, assigned in _ready().

func _fill_buffer():
	var increment = pulse_hz / sample_hz

	var to_fill = playback.get_frames_available()
	print(to_fill)
	var buffer : PackedVector2Array
	while to_fill > 0:
		playback.push_frame(Vector2.ONE * sin(phase * TAU)) # Audio frames are stereo.
		phase = fmod(phase + increment, 1.0)
		to_fill -= 1


func _process(_delta):
	if playback != null: _fill_buffer()
	else: 
		print(playback)
		_ready()

func _ready():
	$Player.stream.mix_rate = sample_hz # Setting mix rate is only possible before play().
	playback = $Player.get_stream_playback()
	if playback != null: _fill_buffer() # Prefill, do before play() to avoid delay.
	$Player.play()
```

Log:
```
--- Debugging process started ---
Godot Engine v4.0.alpha14.official.106b68050 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2070 SUPER

[Object:null]
[Object:null]
8191
0
128
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

```

### Steps to reproduce

Open Audio Generator Demo in any Godot 4,X version
https://github.com/godotengine/godot-demo-projects/tree/3.4-b0d4a7c/audio/generator

### Minimal reproduction project

[generator - issue.zip](https://github.com/godotengine/godot/files/9463616/generator.-.issue.zip)

### PR DESCRIPTION
**Pull request by bluenote10**
Closes #65155

This is an alternative to #73162 following @reduz suggestion there https://github.com/godotengine/godot/pull/73162#issuecomment-1427134553

**To recap**: In Godot 4.x audio stream generators have a fundamental bug that they get killed by the audio server in case of a buffer underrun. This leads to a very ugly race condition already when trying to set them up: If the very first "buffer fill" comes too late, the audio server will kill the playback generator even before it got its first chance to fill the buffer! Taking my [minimal debug project](https://github.com/godotengine/godot/issues/65155#issuecomment-1421337379) as an example, I just had to launch this small app 53 times (!) to get one working instance of an audio stream generator. This means that in Godot 4.x, generators are almost completely unusable right now. (I have a music project that I'd love to migrate to Godot 4.x, but this bug is a complete showstopper.)

**Possible minimal bugfixes**: There are a few ways to fix this issue without the need for a big refactoring. #73162 had proposed to fix it on the level of the audio server, by changing the logic when to kill a playback to incorporate the `.is_playing()` information. This PR here basically solves it on the other end -- in `AudioStreamGeneratorPlayback` itself. In my opinion both fixes are a big improvement over the more or less completely broken state in 4.x / master. There are a few minor aspects why the approach taken in this PR may be preferable:

1. It is a more local change, not having to touch audio server logic itself, thus affecting only the anyway broken `AudioStreamGeneratorPlayback`.

2. The change makes the behavior consistent with the other playback's `_mix_internal` implementations ([`AudioStreamPlaybackMP3::_mix_internal`](https://github.com/godotengine/godot/blob/fc99492d3066098e938449b10e02f8e01d07e2d1/modules/minimp3/audio_stream_mp3.cpp#L40-L43), [`AudioStreamPlaybackOggVorbis::_mix_internal`](https://github.com/godotengine/godot/blob/fc99492d3066098e938449b10e02f8e01d07e2d1/modules/vorbis/audio_stream_ogg_vorbis.cpp#L39-L44)), which all have the semantics: Return 0 if inactive/stopped, otherwise return either the number of requested frames, or the number of available frames due to their _finite_ nature. A generator conceptually falls into the _infinite_ category though. Therefore, it should always simply return the number of requested frames. In particular, a buffer underrun should not become a signal to the audio server to kill the playback -- a buffer underrun is always an accident!

3. There is currently an inconsistency between how `mixed` gets updated vs the return value:

    https://github.com/godotengine/godot/blob/fc99492d3066098e938449b10e02f8e01d07e2d1/servers/audio/effects/audio_stream_generator.cpp#L162-L163

    `mixed` already gets incremented by an amount corresponding to `p_frames` (the number of requested frames), but the return value can indicate something else. This PR would make the update to `mixed` and the return value consistent.

-----------------------

In the long term I fully agree with @reduz that it is probably best to partially revert #51296 and do things like ramp up/down rather on the playback/stream level, because they have better capabilities of doing lookaheads e.g. in case of file based playback. I've collected a few relevant parts of the discussion:

- https://github.com/godotengine/godot/pull/73162#discussion_r1103875581
- https://github.com/godotengine/godot/pull/73162#issuecomment-1427146963
- https://github.com/godotengine/godot/pull/71780#issuecomment-1427131768

However, this would obviously require a bigger refactoring.

For the time being, I'd really appreciate if we could either merge (and release) the bugfix in #73162 or this PR here. Over the course over the last half year I've tried numerous hacks on user side trying to work around this bug, but I don't think there is anything that's really practical. Either of the two PRs would change the situation from "more or less unusable" to "basically fully working", so I hope we can go for a temporary fix now, and look into this bigger refactoring as a second step.

### CODE REVIEW

File: servers/audio/effects/audio_stream_generator.cpp [hunk 1]
```diff
@@ -181,7 +184,7 @@ void AudioStreamGeneratorPlayback::stop() {
 }
 
 bool AudioStreamGeneratorPlayback::is_playing() const {
-	return active; //always playing, can't be stopped
```
Comment (bluenote10) [inline servers/audio/effects/audio_stream_generator.cpp:184]: This comment seemed to be outdated. Or, in fact slightly ironic, because in Godot 4.x the generator playbacks get stopped all the time :wink:

**Comment by ellenhp** [comment]
> In the long term I fully agree with @reduz that it is probably best to partially revert #51296 and do things like ramp up/down rather on the playback/stream level, because they have better capabilities of doing lookaheads e.g. in case of file based playback.

As long as we don't fully revert to mixing in the nodes, because that was an absolute nightmare and at some point i just stopped being interested in solving any audio bugs in 3.x because of it. Mixing in the playbacks doesn't make any sense to me either though because it closes the door to having one player send to multiple audio buses, and without that feature it's not possible to change the bus a player is on at runtime without a loud pop. Given that we point to the bus system whenever anyone wants to do something complex with audio in godot I think we should strive to support changing sends at runtime eventually. I know that reduz disagrees with me here so I'm going to get overruled but I think there's a very strong argument for keeping mixing in the audioserver.

**Review by ellenhp — APPROVED** [review]

**Comment by ellenhp** [comment]
@akien-mga I'm a bit out of the loop with regard to release timing because I haven't logged into rocketchat recently, but this would be good to merge when convenient.

**Comment by akien-mga** [comment]
Thanks! I asked reduz to have a look, hopefully he should in coming days. If he can't, then I'm confident merging anyway with just your approval.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
