### PR TITLE
ResourceLoader: Print load message only when actually loading

### LINKED ISSUE #99535: Godot4.4-dev4: Spaming loading messages if --verbose enabled.
### Tested versions

- v4.4.dev4.mono.official [36e6207bb]
- v4.4.dev5.mono.official [9e6098432]

### System information

all

### Issue description

If verbose enabled, resource loading is now spamming loading messages.
Image

Image

I use `ResourceLoader.load(<script_name>, "GDScript", ResourceLoader.CACHE_MODE_REUSE)` to preload and force reuse scripts to mimimize loading times in my test framework. So I use explicit `CACHE_MODE_REUSE`.
But from the new log messages looks like the script is load again and again.

This spamming messages is filling my console when running my CI workflows now.
Godot4.4-dev5
Image
Godot4.3-stable
Image

### Steps to reproduce

Use the script and attach it to a scene to reproduce.
```gd
extends Node2D


func _ready() -> void:
	load_test()
	get_tree().quit()


func load_test() -> void:

	for i in 10:
		ResourceLoader.load("res://test/example_script.gd", "GDScript", ResourceLoader.CACHE_MODE_REUSE)

```
* run the scene on Godot4.4.dev4 and Godot4.4.dev5:
output:
```
Loading resource: res://test/test.tscn
Loading resource: res://test/test.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
--- Debugging process stopped ---

```
* run on Godot4.3-dev3
```
Loading resource: res://test/test.tscn
Loading resource: res://test/test.gd
Loading resource: res://test/example_script.gd
--- Debugging process stopped ---
```

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by RandomShaper**
Not tested.

Note others may prefer the old behavior where the message corresponds to the resource being _requested to be loaded_ rather than _actually being loaded_. However, that's only theoretical. We know at least some prefer the way this PR introduces.

Fixes #99535.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Nitpick suggestion (not required), LGTM.

File: core/io/resource_loader.cpp [hunk 1]
```diff
@@ -312,7 +314,9 @@ Ref<Resource> ResourceLoader::_load(const String &p_path, const String &p_origin
 	res_ref_overrides.erase(load_nesting);
 	load_nesting--;
 
-	if (!res.is_null()) {
+	if (res.is_null()) {
+		print_verbose(vformat("Failed loading resource: %s", p_path));
+	} else {
 		return res;
 	}
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply core/io/resource_loader.cpp:322]: Alternative, `if (res.is_valid())` to be more positive about the success case.

[the remark this answers is not in the document]
Comment (RandomShaper) [reply core/io/resource_loader.cpp]: I've applied your suggestion, but using `res.is_valid()` instead, to avoid the double negation. I've also changed a check a few lines above to use `res.is_valid()` as well. There's a benefit in both checks reading the same, as they are, let's say tightly related.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: core/io/resource_loader.cpp [hunk 2]
```diff
@@ -294,6 +294,8 @@ Ref<Resource> ResourceLoader::_load(const String &p_path, const String &p_origin
...
 	load_paths_stack.push_back(original_path);
 
+	print_verbose(vformat("Loading resource: %s", p_path));
```
Comment (MikeSchulze) [inline core/io/resource_loader.cpp:297]: Will this spam again to the logs?
Why the p_cache_mode is not respected? An already loaded and cached file should not print the loading message again

Comment (RandomShaper) [reply core/io/resource_loader.cpp:297]: It may still be somewhat spammy, but not more than it was in the beginning, before I inadvertedly made the change to have the message printed regardless the resource was already cached.

And in that regard we're safe now. If this line is executed, the resource wasn't in cache so it's loaded from disk for sure. The cache mode at this point serves for telling the loader if it has to replace the current cache entry and how to deal with dependencies.

Comment (MikeSchulze) [reply core/io/resource_loader.cpp:297]: Thanks for clarification 👍

**Comment by MikeSchulze** [comment]
It is not fixed, is still spamming hundreds of loading messages. using v4.4.dev7.mono.official [46c8f8c5c]

image

https://github.com/MikeSchulze/gdUnit4/actions/runs/12529348567/job/34944856605?pr=618
