### PR TITLE
Try to guess method return type even if subscript base has no value

### LINKED ISSUE #78003: Magical type deduction deduces type of function result stored in variable not declared with static type, and enables autocompletion on direct members, but not indirect members (members of members)
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

I found a super edge case for autocompletion breaking, where autocompletion will work on a variable not declared with static type, but only for 1st-degree members. I don't know if the bug if that the parser goes too far (it shouldn't even try to guess non-static variable type), or not far enough (if it does, it might as well autocomplete the 2nd member).

I suppose that the "magical" unsollicited type deduction on non-static-type variables has been added because it's convenient in every day use like doing math computation or trivial calls without needing a `:=` instead of `=` every single time, but it causes inconsistent behavior when dealing with 2nd-degree members; and may confuse the user as autocompletion works on the 1st level so they don't immediately realize that they forgot to static type with `:=`.

So it'd be better if either autocompletion was working all along, or not at all (then user could immediately spot  they forgot to static type).

Take a custom class:

```gdscript
# my_class.gd
class_name MyClass
extends Node2D

var custom_instance: MyClass2
var native_instance: Node
```

and

```gdscript
# my_class2.gd
class_name MyClass2
extends Node2D

var custom_field: int
```

and a script that uses the class, defining some methods, typed or not:

```gdscript
# class_user.gd
extends Node

@export var my_instance: MyClass

func _get_instance_untyped():
	return my_instance

func _get_instance() -> MyClass:
	return my_instance

func _get_array_of_instances_untyped():
	return [my_instance]

func _get_array_of_instances() -> Array[MyClass]:
	return [my_instance]
```

Now we add a final method to this script to test autocompletion.

Note that behavior slightly differs between single vars and arrays: it is the same with single vars whether you use a typed function result or not (and I don't understand how; maybe untyped function is simpler to magic-parse so they can deduce the return type anyway). Whereas a function returning an array but without explicit type will not autocomplete at all when using the result (unless you locally

```gdscript
# class_user.gd
func _ready():
	var local_instance_ref = _get_instance()
	# Even though local_instance_ref is not static typed, parser exploits info from _get_instance
	# ("magical type deduction"). However, autocompletion breaks on indirect member custom_field, UNEXPECTED
	print(local_instance_ref.custom_instance.custom_field)

	var local_instance_ref_untyped = _get_instance_untyped()
	# Even though local_instance_ref is not static typed AND _get_instance_untyped is not typed,
	# parser exploits info from _get_instance_untyped ("magical type deduction"), and I have no idea how
	# Anyway, however, autocompletion breaks only on indirect member custom_field, UNEXPECTED
	print(local_instance_ref_untyped.custom_instance.custom_field) # autocompletion FAILS for custom_field

	# Storing array in local var without explicit type makes the first autocompletion work,
	# but not 2nd degree -> UNEXPECTED (In real project, I forgot a colon here)
	var array_of_instances6 = _get_array_of_instances()
	for instance in array_of_instances6:
		print(instance.get_parent().get_parent()) # autocompletion WORKS for native types, but...
		print(instance.custom_instance.custom_field) # autocompletion FAILS on dot after custom_instance
		print(instance.native_instance.get_parent()) # autocompletion FAILS on dot after native_instance
```

In addition, adding code using the members above in _ready, such as

```gdscript
	print(my_instance.custom_instance)
	print(my_instance.native_instance)
```

will _hint_ the parser and enable autocompletion on indirect members. So when reproducing the bug, you must avoid adding extra code that use the custom members to avoid hiding the bug.

The MRP has even more cases, I just put the unexpected ones (the one where the magical type deduction stops working after 2 members) here.

**Workaround**

The bug occurs where user forgot to statically type, so fortunately a simple `:=` generally does the trick. If the function does not return a static type, you can even explicitly declare type with `: MyType =`.

However, fixing the bug by either not completing at all, or completing all the way down, would help the user avoid being lost.

### Steps to reproduce

0. You can copy the code above to create the 3 scripts, or download the MRP
1. Place the caret inside class_user.gd > _ready in each line/block marked UNEXPECTED, after the first dot, and press Ctrl+Space to try to autocomplete: it works.
2. Repeat after the second (and last) dot: this time, it fails (you cannot see `custom_field`, `get_parent`, etc.)

### Minimal reproduction project

[v4.0.2 - Autocompletion doesnt work for 2nd degree member (member of custom class).zip](https://github.com/godotengine/godot/files/11688743/v4.0.2.-.Autocompletion.doesnt.work.for.2nd.degree.member.member.of.custom.class.zip)

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #78003.

We want to guess the method return type not only if the base has a reduced value but also if the base has a resolved type.

The following example shows the problem:
```gdscript
class B:
	func to_str(b: int):
		return str(b)

var a: B

func _ready():
	a.to_str(10) # Godot does not suggest string methods in autocompletion
```
Since a has no value in the example, the autocompletion does not try to guess the type of `to_str(10)`.

Note that we need to use internal classes to observe that this PR solves the problem. There are other problems preventing it to work in the context of #78003.

### CODE REVIEW

File: modules/gdscript/gdscript_editor.cpp [hunk 1]
```diff
@@ -1813,7 +1813,7 @@ static bool _guess_expression_type(GDScriptParser::CompletionContext &p_context,
 						}
 					}
 
-					if (!found && base.value.get_type() != Variant::NIL) {
+					if (!found && (base.value.get_type() != Variant::NIL || base.type.is_set())) {
```
Comment (Mickeon) [inline modules/gdscript/gdscript_editor.cpp:1816]: Forgive me for being thorough and asking potentially silly questions.

Wouldn't `base.type.is_set()` be enough of a check here? And why would it not be?

Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp:1816]: Good point. I'd also guess `base.type.is_set` would be enough. Will test it.

Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp:1816]: Ok it seems to work well without `base.value.get_type() != Variant::NIL`. However I'm unsure whether we should delete the original condition.

Hypothetical situation which might make problems (unsure whether it can be constructed):
- base type is `UNRESOLVED`
- but there is a value associated with the base

I don't now whether this is a possible scenario. Some insight from the GDScript team might help.

Comment (HolonProduction) [reply modules/gdscript/gdscript_editor.cpp]: I just removed the check completely. `_guess_method_return_type_from_base` does not use base.value and if `base.type.is_set() == false` `_guess_method_return_type_from_base` returns false without much performance overhead anyways.

This seems like the solution that is least likely to cause regressions if the implementation of `_guess_method_return_type_from_base` changes.

**Comment by HolonProduction** [comment]
Rebased and added a test case

**Review by Mickeon — APPROVED** [review]
I'm approving on principle. Doing this speeds up... a general workflow where writing code faster is a priority and polishing it with static typing is an afterthought. In other words, it's just nice.

**Review by akien-mga — APPROVED** [review]
Let's give this a try!

**Comment by akien-mga** [comment]
Might use a rebase though, there's been changes to the test suite in recent months so we should make sure it still works properly.

**Comment by HolonProduction** [comment]
Rebased and adjusted the test to account for #99102

**Review by dalexeev — APPROVED** [review]
I haven't tested, but it makes sense to me.

**Comment by akien-mga** [comment]
Thanks!
