### PR TITLE
Various fixes to Tween code

### LINKED ISSUE #51231: Tween memory leak
### Godot version

4.0

### System information

Mac mini 2018, Mac OS catalina 10.15.7, i5, 8gb ram

### Issue description

https://user-images.githubusercontent.com/30470869/128121306-a0316aca-9a2d-45ea-948a-f78c3758de7a.mov

The number of objects always increases every time tween is used in Godot 4 (see number objects in debug -> monitor)

I don't have this case in Godot 3.2.3 so I think it is memory leak.

### Steps to reproduce

Project contains 1 Node2D and 1 Sprite2D

```
extends Node2D

@onready var sprite := $Sprite2D

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("click"):
		move_node_to_click(get_global_mouse_position())

func move_node_to_click(target_position: Vector2) -> void:
	print(target_position)
	var tween: Tween = get_tree().create_tween()
	tween.tween_property(sprite, "position", target_position, 0.5)
	tween.tween_interval(0.5)
```

Run and click on screen.
Check Debugger -> Monitors - > Object -> Objects: increase by 3 per click

### Minimal reproduction project

[TestGD4.zip](https://github.com/godotengine/godot/files/6928606/TestGD4.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Attempt to fix #51231

The bug is caused by cyclic reference, but even though I clear everything, some of the Tweeners still don't get destroyed. Here's updated code from the issue's MRP, for testing:
```
extends Node2D

@onready var sprite := $Sprite2D

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("click"):
		move_node_to_click(get_global_mouse_position())
		get_tree().create_timer(2).timeout.connect(end)

func move_node_to_click(target_position: Vector2) -> void:
	print(target_position)
	var tween: Tween = get_tree().create_tween()
	tween.tween_interval(0.5)
	tween.tween_property(sprite, "position", target_position, 0.5)
#	tween.tween_callback(end)
	tween.tween_callback(test.bind("end?"))
	tween.tween_method(test, 0, 2, 0.01)

func test(v):
	print(v)

func end():
	print(get_tree().get_processed_tweens())
```
For whatever reason, only MethodTweener and PropertyTweener get properly destroyed. Tween, CallbackTweener and IntervalTweener still linger somewhere. What's more weird, when you change the callback in the code above to the commented out `end`, the callback tweener gets removed too (which makes me think that the issue is not related to Tweens).

Putting it as draft now. Also there are some debug prints for easier testing.

---

Aside from the above issue, I fixed broken `is_valid()` method. Also removed return value from `Tween.append()`, which was a leftover from a brief moment when it was exposed. There is also one error message I improved, but I'm not 100% if it's worded correctly.

### CODE REVIEW

**Comment by KoBeWi** [comment]
When you change `var tween: Tween = get_tree().create_tween()` in the above code to `var tween = get_tree().create_tween()` (just the type removed), suddenly all the Tweeners get removed. This makes me believe that it's a GDScript bug, I'm cleaning everything properly on my side now. I still don't know why Tween is still not destroyed, but this might also be something unrelated to Tweens.

File: scene/animation/tween.cpp [hunk 1]
```diff
@@ -132,11 +132,22 @@ bool Tween::is_running() {
...
 bool Tween::is_valid() {
-	return invalid;
+	return valid;
+}
+
+void Tween::clear() {
+	valid = false;
+
+	for (List<Ref<Tweener>> &step : tweeners) {
+		for (Ref<Tweener> tweener : step) {
```
Comment (akien-mga) [inline scene/animation/tween.cpp:146]:
```suggestion
		for (Ref<Tweener> &tweener : step) {
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
