### PR TITLE
[GraphNode] Fix slot focus rect draw, make slot focus mode configurable.

### LINKED ISSUE #105999: GraphNode focus navigation “down” jumps to slots (creating white rectangles) before moving to the node below
### Tested versions

- Reproducible in Godot 4.5dev3, Godot v4.5.dev4 and also on newest Godot v4.5.dev5
- not reproducible in in Godot 4.5dev2 or Godot 4.4.1

### System information

Godot v4.5.dev3 - macOS Sequoia (15.3.2) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Apple M1 Max - Apple M1 Max (10 threads)

### Issue description

When using the Down cursor key to navigate focus in the GraphNode inspector (with focus_neighbor_bottom assigned), focus always lands on the node’s input/output “slots” (the little white rectangles or “ears”)—even when slot visibility is turned off—before it can move to the next GraphNode below. This both produces unwanted “ears” highlights and prevents a direct jump to the neighboring node.
Image

Image

### Steps to reproduce

	1.	Open Godot 4.5dev3 on macOS.
	2.	Create or open a scene containing two GraphNode instances, one positioned directly below the other.
	3.	In Project → Editor Settings → Interface → Focus:
	•	Assign Neighbor Bottom to the Down key.
	4.	(Optional) In the GraphNode’s Slots section, disable Show Slots.
	5.	Select the upper GraphNode in the 2D editor viewport.
	6.	Press the Down arrow key.

### Minimal reproduction project (MRP)
[250501_test_graphnode_focus_bug_01_2025-05-02_00-40-51.zip](https://github.com/user-attachments/files/20006366/250501_test_graphnode_focus_bug_01_2025-05-02_00-40-51.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/105999

### CODE REVIEW

File: scene/gui/graph_node.cpp [hunk 1]
```diff
@@ -1180,6 +1193,23 @@ Vector<int> GraphNode::get_allowed_size_flags_vertical() const {
...
 }
 
+void GraphNode::set_slots_focus_mode(Control::FocusMode p_focus_mode) {
+	if (slots_focus_mode == p_focus_mode) {
+		return;
+	}
+	ERR_FAIL_COND((int)p_focus_mode < 1 || (int)p_focus_mode > 3);
+
+	slots_focus_mode = p_focus_mode;
+	if (slots_focus_mode == Control::FOCUS_CLICK) {
```
Comment (KoBeWi) [inline scene/gui/graph_node.cpp]:
```suggestion
	if (slots_focus_mode == Control::FOCUS_CLICK && selected_slot > -1) {
```
Unless `queue_redraw()` is needed for something else.

Comment (bruvzg) [reply scene/gui/graph_node.cpp]: No, should not be needed if it's already `-1`.

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/graph_node.cpp [hunk 2]
```diff
@@ -407,21 +407,25 @@ void GraphNode::gui_input(const Ref<InputEvent> &p_event) {
...
-				accept_event();
-			}
-		} else if (p_event->is_action("ui_down", true)) {
-			selected_slot++;
-			if (selected_slot >= slot_count) {
-				selected_slot = -1;
-			} else {
-				accept_event();
+		bool ac_enabled = get_tree() && get_tree()->is_accessibility_enabled();
+		if (((ac_enabled && slots_focus_mode == Control::FOCUS_ACCESSIBILITY) || slots_focus_mode == Control::FOCUS_ALL)) {
```
Comment (AThousandShips) [inline scene/gui/graph_node.cpp]:
```suggestion
		if ((ac_enabled && slots_focus_mode == Control::FOCUS_ACCESSIBILITY) || slots_focus_mode == Control::FOCUS_ALL) {
```

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
