### PR TITLE
Consistently display script icons for nodes in connect dialog's scene tree editor

### LINKED ISSUE #92513: Connection dialog does not show script icon in advanced mode
### Tested versions

4.3 dev6 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/c0b3c703-f787-4c9b-a3a1-121983be2c99

This is caused by `connect_to_script_mode`, which either shows scripts, but blocks other nodes, or allows all nodes, but hides scripts. I don't see a reason why the scripts should be hidden, they provide more context when looking at the scene tree.

### Steps to reproduce

1. Have a scene with scripts
2. Go to Node -> Signals and double-click a signal
3. Toggle Advanced and compare the scene view

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by stephen-berry**
#92513 requested to be able to view script icons with/without the ConnectDialog's advanced tab enabled for better context when selecting signals.

The change made was simple, with the biggest change involving the use of 'connecting_signal' boolean to ensure all script icons are displayed (custom or otherwise) when the connect dialog scene tree is open. 
Before this change, all icon additions were made under the connect_to_script_mode. When Advanced is enabled, the connect_to_script_mode is set to false, which results in never adding the script buttons to the scene tree editor.

The fix should be low-risk because the icons are only added during connect dialog scene tree's. I would have added tests, but I noticed there are currently no test files under editor/ (and this being my first ticket, I wasn't sure how to proceed with the tests).

The 'before change' video (linked in the original ticket) displays the issue, and below I have the 'after change' result of both advanced off/on.

Advanced off:
GODOT-92513_Advanced_Disabled

Advanced on:
GODOT-92513_Advanced_Enabled
 
*Bugsquad edit:*
- Fixes #92513.

### CODE REVIEW

File: editor/gui/scene_tree_editor.cpp [hunk 1]
```diff
@@ -232,23 +232,27 @@ void SceneTreeEditor::_add_nodes(Node *p_node, TreeItem *p_parent) {
 	item->set_icon(0, icon);
 	item->set_metadata(0, p_node->get_path());
 
+	if (connecting_signal) {
+		//add script icons for all scripted nodes
```
Comment (KoBeWi) [inline editor/gui/scene_tree_editor.cpp:236]:
```suggestion
		// Add script icons for all scripted nodes.
```

File: editor/gui/scene_tree_editor.cpp [hunk 2]
```diff
@@ -232,23 +232,27 @@ void SceneTreeEditor::_add_nodes(Node *p_node, TreeItem *p_parent) {
...
+		Ref<Script> scr = p_node->get_script();
+		if (!scr.is_null()) {
```
Comment (KoBeWi) [inline editor/gui/scene_tree_editor.cpp:238]:
```suggestion
		if (scr.is_valid()) {
```

File: editor/gui/scene_tree_editor.cpp [hunk 3]
```diff
@@ -232,23 +232,27 @@ void SceneTreeEditor::_add_nodes(Node *p_node, TreeItem *p_parent) {
...
+			item->add_button(0, get_editor_theme_icon(SNAME("Script")), BUTTON_SCRIPT);
+			if (EditorNode::get_singleton()->get_object_custom_type_base(p_node) == scr) {
+				//disable button on custom scripts (pure visual cue)
```
Comment (KoBeWi) [inline editor/gui/scene_tree_editor.cpp:241]:
```suggestion
				// Disable button on custom scripts (pure visual cue).
```

File: editor/gui/scene_tree_editor.cpp [hunk 4]
```diff
@@ -232,23 +232,27 @@ void SceneTreeEditor::_add_nodes(Node *p_node, TreeItem *p_parent) {
...
 	if (connect_to_script_mode) {
 		Color accent = get_theme_color(SNAME("accent_color"), EditorStringName(Editor));
 
 		Ref<Script> scr = p_node->get_script();
-		if (!scr.is_null() && EditorNode::get_singleton()->get_object_custom_type_base(p_node) != scr) {
-			//has script
-			item->add_button(0, get_editor_theme_icon(SNAME("Script")), BUTTON_SCRIPT);
-		} else {
-			//has no script (or script is a custom type)
+		bool has_custom_script = !scr.is_null() && EditorNode::get_singleton()->get_object_custom_type_base(p_node) == scr;
```
Comment (KoBeWi) [inline editor/gui/scene_tree_editor.cpp:251]:
```suggestion
		bool has_custom_script = scr.is_valid() && EditorNode::get_singleton()->get_object_custom_type_base(p_node) == scr;
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by stephen-berry** [comment]
I will squash them as soon as possible (away from PC til sunday :0) thank you! :)

**Comment by stephen-berry** [comment]
After interactive rebasing, I noticed I didn't see my 2 review commits from here. I added them and amended them as a commit to previous. I hope this is okay, and feel free to let me know if there's something else I should have done :) sorry for any inconvenience (and thank you for reviewing!)

**Comment by akien-mga** [comment]
> After interactive rebasing, I noticed I didn't see my 2 review commits from here. I added them and amended them as a commit to previous.

Yes what you did looks correct. We like that simple PRs have a single commit, so fixups following PR review should be amended into the original commit to keep it as a single commit.

I pushed another rebase of your branch as there was a temporary CI failure due to GitHub Actions changes, unrelated to this PR.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
