### PR TITLE
Port recent move_and_slide fixes to 3D

### LINKED ISSUE #34117: stop_on_slope doesn't seem to work in version 3.2 beta 3
**Godot version:**
Godot 3.2 Beta 3
**OS/device including version:**
Windows 10
**Issue description:**
The function move_and_slde() in Kinematic Body 3D, the stop_on_slope parameter seems to have stopped working after I upgraded from Godot 3.2b2 to 3.2b3. (It only happens in 3.2b3)
**Steps to reproduce:**
Open the project I gave, press play, go to a slope, if you go up and stop everything should be ok, but if you go down even slightly you will be dragged to the bottom. It happens only in 3.2b3
**Minimal reproduction project:**
[FirstPersonStarter 1.03](https://github.com/Whimfoome/godot-FirstPersonStarter/archive/9f98e35f5a1d309d5304183f5753e9b34da2ec1a.zip)
**Additional:**
I don't know if this is a bug but even before, even at a slight velocity, sort of 0.001 you get pulled down instead of stopping on a slope with stop_on_slope parameter true.

### LINKED ISSUE #51874: Result of `CharacterBody`'s gravity calculation on steep slope in air is undesirable
### Godot version

4.0.dev

### System information

MacOS 11.4, Windows 10

### Issue description

At first I thought it was a problem on the GDScript side. However, probably the current implementation does not allow to coexist the behavior of "preventing `CharacterBody` slide-up wall in air" and "resetting gravity".

When `is_on_floor() == true`, `linear_velocity.y` is set to `0` after `move_and_silde()`, even if it is added gravity infinitely. The same is true for `is_on_floor() == true && is_on_wall() == true` and `linear_velocity.xz`. 

In the sample project, I intentionally keep the previous frame's `velocity.y` on steep slopes in air, because if we don't keep it, `CharacterBody` will slide-up the steep slope in air. In addition, GDScript has no way to determine if `CharacterBody` is stuck in the air between walls, so as a result, `CharacterBody` will continue to be added gravity. If the `CharacterBody` is stuck between walls and the `linear_velocity.y` is `0`, there is a possibility to get out of the stack by horizontal moving.

On a steep slope in air, someone may need a slower sliding-down behavior but I think anyone doesn't want the behavior of sliding-up, so may need to fix the calculation of gravity on steep slope in air.

### Steps to reproduce

https://user-images.githubusercontent.com/61938263/130021803-66ef777d-9d1b-487a-b620-7a4f1e7f07ed.mov

If comment out lines 178~180 of `Player.gd` in the sample project

https://user-images.githubusercontent.com/61938263/130032204-836874db-828d-46c1-bfea-857326c6df77.mov

### Minimal reproduction project

Same #50732.

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Improves stop on slopes, sliding on walls and gravity handling by porting existing changes from `CharacterBody2D` to `CharacterBody3D` (made by @fabriceci in #51027 and subsequent PRs).

Although this PR doesn't add the new CharacterBody features and API changes, just the behavior fixes.

These changes are also part of #51896, but if possible it's better to have them in a separate PR to keep track of general `move_and_slide` improvements independently from ray shape fixes.

Fixes #34117 (although it was already closed with a script workaround)
Partly addresses #51874 (the character can't climb a wall anymore)

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
There's a crash in the CI that seems unrelated to this PR. Here's the log in case it can be useful for @godotengine/gdscript:

```
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:3455)
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:3455)
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:3455)
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:3455)
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:3455)
ERROR: Parser bug (please report): Trying to check compatibility of unset value type
   at: is_type_compatible (modules/gdscript/gdscript_analyzer.cpp:3455)
modules/gdscript/gdscript_cache.cpp:143:29: runtime error: member call on null pointer of type 'struct GDScriptParserRef'
modules/gdscript/gdscript_cache.cpp:143:29: runtime error: member access within null pointer of type 'struct GDScriptParserRef'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] bin/godot.linuxbsd.tools.64s() [0x21938f6] (/home/runner/work/godot/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f13f8a3d210] (??:0)
[3] GDScriptCache::get_parser(String const&, GDScriptParserRef::Status, Error&, String const&) (/home/runner/work/godot/godot/modules/gdscript/gdscript_cache.cpp:143)
[4] GDScriptAnalyzer::get_parser_for(String const&) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:3622 (discriminator 1))
[5] GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode*, bool) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:2584)
[6] GDScriptAnalyzer::reduce_expression(GDScriptParser::ExpressionNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:1464 (discriminator 4))
[7] GDScriptAnalyzer::reduce_call(GDScriptParser::CallNode*, bool) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:2104)
[8] GDScriptAnalyzer::reduce_expression(GDScriptParser::ExpressionNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:1452 (discriminator 4))
[9] GDScriptAnalyzer::resolve_variable(GDScriptParser::VariableNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:1106)
[10] GDScriptAnalyzer::resolve_node(GDScriptParser::Node*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:822 (discriminator 4))
[11] GDScriptAnalyzer::resolve_suite(GDScriptParser::SuiteNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:981 (discriminator 2))
[12] GDScriptAnalyzer::resolve_for(GDScriptParser::ForNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:1079)
[13] GDScriptAnalyzer::resolve_node(GDScriptParser::Node*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:809 (discriminator 4))
[14] GDScriptAnalyzer::resolve_suite(GDScriptParser::SuiteNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:981 (discriminator 2))
[15] GDScriptAnalyzer::resolve_function_body(GDScriptParser::FunctionNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:935)
[16] GDScriptAnalyzer::resolve_class_body(GDScriptParser::ClassNode*) (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:763)
[17] GDScriptAnalyzer::resolve_program() (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:3647)
[18] GDScriptAnalyzer::analyze() (/home/runner/work/godot/godot/modules/gdscript/gdscript_analyzer.cpp:3664)
[19] GDScript::reload(bool) (/home/runner/work/godot/godot/modules/gdscript/gdscript.cpp:828)
[20] GDScriptCache::get_full_script(String const&, Error&, String const&) (/home/runner/work/godot/godot/modules/gdscript/gdscript_cache.cpp:213)
[21] ResourceFormatLoaderGDScript::load(String const&, String const&, Error*, bool, float*, ResourceFormatLoader::CacheMode) (/home/runner/work/godot/godot/modules/gdscript/gdscript.cpp:2242)
[22] ResourceLoader::_load(String const&, String const&, String const&, ResourceFormatLoader::CacheMode, Error*, bool, float*) (/home/runner/work/godot/godot/core/io/resource_loader.cpp:201 (discriminator 6))
[23] ResourceLoader::_thread_load_function(void*) (/home/runner/work/godot/godot/core/io/resource_loader.cpp:228 (discriminator 4))
[24] ResourceLoader::load(String const&, String const&, ResourceFormatLoader::CacheMode, Error*) (/home/runner/work/godot/godot/core/io/resource_loader.cpp:575)
[25] EditorResourcePreviewGenerator::generate_from_path(String const&, Vector2 const&) const (/home/runner/work/godot/godot/editor/editor_resource_preview.cpp:61 (discriminator 1))
[26] EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) (/home/runner/work/godot/godot/editor/editor_resource_preview.cpp:160 (discriminator 3))
[27] EditorResourcePreview::_thread() (/home/runner/work/godot/godot/editor/editor_resource_preview.cpp:254)
[28] EditorResourcePreview::_thread_func(void*) (/home/runner/work/godot/godot/editor/editor_resource_preview.cpp:100)
[29] Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) (/home/runner/work/godot/godot/core/os/thread.cpp:73)
[30] void std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(std::__invoke_other, void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (/usr/include/c++/9/bits/invoke.h:60)
[31] std::__invoke_result<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>::type std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*>(void (*&&)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*&&, Thread::Settings&&, void (*&&)(void*), void*&&) (/usr/include/c++/9/bits/invoke.h:96)
[32] void std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (/usr/include/c++/9/thread:244)
[33] std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator()() (/usr/include/c++/9/thread:252)
[34] std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_run() (/usr/include/c++/9/thread:195)
[35] bin/godot.linuxbsd.tools.64s() [0x18ee2ba4] (thread.o:?)
[36] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f13f96b6609] (??:0)
[37] /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f13f8b19293] (??:0)
-- END OF BACKTRACE --
Aborted (core dumped)
FATAL ERROR: Godot has been crashed.
```

**Comment by TokageItLab** [comment]
@pouleyKetchoupp This change will cause a problem where CharacterBody will not be able to go up and down the hill at constant speed. There was an option to solve this problem in 2D, but 3D needs a same option. In the previous of this change, this was done in lines 151-152 of the sample project (#50732).

**Comment by pouleyKetchoupp** [comment]
@TokageItLab Noted! I think we can still merge this change for now, since it's fixing some issues and the plan is to add the same option as in 2D for constant speed in a subsequent PR.

**Comment by TokageItLab** [comment]
I got it, there is no problem!
So, I confirm this change make to certainly no longer going up the wall. Also I confirm that there is still stack problem after this as https://github.com/godotengine/godot/issues/51874#issuecomment-902357899, but it should also be resolved separately from this PR. Thank you for your working!

File: scene/3d/physics_body_3d.cpp [hunk 1]
```diff
@@ -1171,7 +1167,7 @@ bool CharacterBody3D::move_and_slide() {
 
 		sliding_enabled = true;
 
-		if (!found_collision || motion == Vector3()) {
+		if (!collided || motion == Vector3()) {
```
Comment (fabriceci) [inline scene/3d/physics_body_3d.cpp:1170]: Looks perfect only here where you should replace the test by `motion.is_equal_approx(Vector3())`.

(you can also make the same change at the line `1112` and `1175`)

**Review by fire — APPROVED** [review]
Animation Team Review. Will wait for the Physics team to merge.

\<Tokage>

8:03 AM

If it be applied fabriceci's suggestion, I think it will be fine. However, you can't go up and down a slope at a constant speed after this change, until there is a PR to implement an option to make the speed of the slope constant. (And I think it's mainly for the Physics topic...)

**Comment by TokageItLab** [comment]
The note about the "Physics topic" is due to fire making a comment on Rocket Chat's Animation channel, so you don't worry about it.

File: scene/3d/physics_body_3d.cpp (hunk 1 above)
Comment (pouleyKetchoupp) [reply scene/3d/physics_body_3d.cpp]: Thanks! I've changed the check to `is_equal_approx` in the 3 different places.

File: scene/3d/physics_body_3d.cpp [hunk 2]
```diff
@@ -1130,39 +1128,37 @@ bool CharacterBody3D::move_and_slide() {
 
 	for (int iteration = 0; iteration < max_slides; ++iteration) {
 		PhysicsServer3D::MotionResult result;
-		bool found_collision = false;
-
 		bool collided = move_and_collide(motion, result, margin, false, !sliding_enabled);
 		if (!collided) {
```
Comment (fabriceci) [inline scene/3d/physics_body_3d.cpp:1132]: You can remove that condition, only need to do `if(collided)` because at the end the condition check if `collided`

File: scene/3d/physics_body_3d.cpp [hunk 3]
```diff
@@ -1171,12 +1167,12 @@ bool CharacterBody3D::move_and_slide() {
...
 		sliding_enabled = true;
 
-		if (!found_collision || motion == Vector3()) {
+		if (!collided || motion.is_equal_approx(Vector3())) {
 			break;
 		}
 	}
 
-	if (was_on_floor && snap != Vector3()) {
+	if (was_on_floor && !snap.is_equal_approx(Vector3())) {
```
Comment (fabriceci) [inline scene/3d/physics_body_3d.cpp:1175]: We added `&& !on_floor` in a previous PR, you can add it, or I will do it later as I need to work on this file

**Review by fabriceci — APPROVED** [review]
