### PR TITLE
Fix collision shape debug color breaking GDExtension

### LINKED ISSUE #100313: CollisionShape3d Debug Color breaks gdextension compatibility
### Tested versions

- Introduced in this commit: https://github.com/godotengine/godot/commit/0fc082e1ee3af5bb6a4b52f85756d24dc02b230f#diff-0e07df9f216af3d10743ca02b77e1da07d78cbfd736da3d75aaf90bfefa76bee

### System information

N/A

### Issue description

Discovered when using Rust gdext here: https://github.com/godot-rust/gdext

```
ERROR: [panic]
  Failed to load class method CollisionShape3D::set_debug_color (hash 2920490490).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
```

I've found exactly what is causing the issue.  Its because Godot only binds these methods in debug and editor builds:

https://github.com/godotengine/godot/blob/38775731e8494a28deddc3febda895679f49fd6e/scene/3d/physics/collision_shape_3d.cpp#L183C1-L195C24

```cpp
#ifdef DEBUG_ENABLED
	ClassDB::bind_method(D_METHOD("set_debug_color", "color"), &CollisionShape3D::set_debug_color);
	ClassDB::bind_method(D_METHOD("get_debug_color"), &CollisionShape3D::get_debug_color);

	ClassDB::bind_method(D_METHOD("set_enable_debug_fill", "enable"), &CollisionShape3D::set_debug_fill_enabled);
	ClassDB::bind_method(D_METHOD("get_enable_debug_fill"), &CollisionShape3D::get_debug_fill_enabled);

	ADD_PROPERTY(PropertyInfo(Variant::COLOR, "debug_color"), "set_debug_color", "get_debug_color");
	// Default value depends on a project setting, override for doc generation purposes.
	ADD_PROPERTY_DEFAULT("debug_color", get_placeholder_default_color());

	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "debug_fill"), "set_enable_debug_fill", "get_enable_debug_fill");
#endif // DEBUG_ENABLED
```

And don't let the ``DEBUG_ENABLED`` fool you like it did me.  That is not only indicating a debug build.  That is indicating it is an **editor or debug** build as can be seen in the ``SConstruct`` here: https://github.com/godotengine/godot/blob/38775731e8494a28deddc3febda895679f49fd6e/SConstruct#L475.  So even release editor builds have this.

```py
env.debug_features = env["target"] in ["editor", "template_debug"]
```

I'm thinking the proper solution is to support these debug colors even in release builds.  Especially since we do for collision_shape_2d: https://github.com/godotengine/godot/blob/38775731e8494a28deddc3febda895679f49fd6e/scene/2d/physics/collision_shape_2d.cpp#L269C1-L288C2

```cpp
void CollisionShape2D::_bind_methods() {
	ClassDB::bind_method(D_METHOD("set_shape", "shape"), &CollisionShape2D::set_shape);
	ClassDB::bind_method(D_METHOD("get_shape"), &CollisionShape2D::get_shape);
	ClassDB::bind_method(D_METHOD("set_disabled", "disabled"), &CollisionShape2D::set_disabled);
	ClassDB::bind_method(D_METHOD("is_disabled"), &CollisionShape2D::is_disabled);
	ClassDB::bind_method(D_METHOD("set_one_way_collision", "enabled"), &CollisionShape2D::set_one_way_collision);
	ClassDB::bind_method(D_METHOD("is_one_way_collision_enabled"), &CollisionShape2D::is_one_way_collision_enabled);
	ClassDB::bind_method(D_METHOD("set_one_way_collision_margin", "margin"), &CollisionShape2D::set_one_way_collision_margin);
	ClassDB::bind_method(D_METHOD("get_one_way_collision_margin"), &CollisionShape2D::get_one_way_collision_margin);
	ClassDB::bind_method(D_METHOD("set_debug_color", "color"), &CollisionShape2D::set_debug_color);
	ClassDB::bind_method(D_METHOD("get_debug_color"), &CollisionShape2D::get_debug_color);


	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "shape", PROPERTY_HINT_RESOURCE_TYPE, "Shape2D"), "set_shape", "get_shape");
	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "disabled"), "set_disabled", "is_disabled");
	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "one_way_collision"), "set_one_way_collision", "is_one_way_collision_enabled");
	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "one_way_collision_margin", PROPERTY_HINT_RANGE, "0,128,0.1,suffix:px"), "set_one_way_collision_margin", "get_one_way_collision_margin");
	ADD_PROPERTY(PropertyInfo(Variant::COLOR, "debug_color"), "set_debug_color", "get_debug_color");
	// Default value depends on a project setting, override for doc generation purposes.
	ADD_PROPERTY_DEFAULT("debug_color", Color());
}
```

### Steps to reproduce

Invoke the godot editor with the ``--dump-extension-api`` arg.  Then inspect the ``extension_api.json`` and see that ``set_debug_color``, ``get_debug_color``, and other related methods that are only available in debug and editor builds are dumped for CollisionShape3D.

# Proposed Solution:

Allow these methods in all builds the same way we do for ColisionShape2D.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by TCROC**
This fixes https://github.com/godotengine/godot/issues/100313.

Issue description copied in below:

### Tested versions

- Introduced in this commit: https://github.com/godotengine/godot/commit/0fc082e1ee3af5bb6a4b52f85756d24dc02b230f#diff-0e07df9f216af3d10743ca02b77e1da07d78cbfd736da3d75aaf90bfefa76bee

### System information

N/A

### Issue description

Discovered when using Rust gdext here: https://github.com/godot-rust/gdext

```
ERROR: [panic]
  Failed to load class method CollisionShape3D::set_debug_color (hash 2920490490).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
```

I've found exactly what is causing the issue.  Its because Godot only binds these methods in debug and editor builds:

https://github.com/godotengine/godot/blob/38775731e8494a28deddc3febda895679f49fd6e/scene/3d/physics/collision_shape_3d.cpp#L183C1-L195C24

```cpp
#ifdef DEBUG_ENABLED
	ClassDB::bind_method(D_METHOD("set_debug_color", "color"), &CollisionShape3D::set_debug_color);
	ClassDB::bind_method(D_METHOD("get_debug_color"), &CollisionShape3D::get_debug_color);

	ClassDB::bind_method(D_METHOD("set_enable_debug_fill", "enable"), &CollisionShape3D::set_debug_fill_enabled);
	ClassDB::bind_method(D_METHOD("get_enable_debug_fill"), &CollisionShape3D::get_debug_fill_enabled);

	ADD_PROPERTY(PropertyInfo(Variant::COLOR, "debug_color"), "set_debug_color", "get_debug_color");
	// Default value depends on a project setting, override for doc generation purposes.
	ADD_PROPERTY_DEFAULT("debug_color", get_placeholder_default_color());

	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "debug_fill"), "set_enable_debug_fill", "get_enable_debug_fill");
#endif // DEBUG_ENABLED
```

And don't let the ``DEBUG_ENABLED`` fool you like it did me.  That is not only indicating a debug build.  That is indicating it is an **editor or debug** build as can be seen in the ``SConstruct`` here: https://github.com/godotengine/godot/blob/38775731e8494a28deddc3febda895679f49fd6e/SConstruct#L475.  So even release editor builds have this.

```py
env.debug_features = env["target"] in ["editor", "template_debug"]
```

I'm thinking the proper solution is to support these debug colors even in release builds.  Especially since we do for collision_shape_2d: https://github.com/godotengine/godot/blob/38775731e8494a28deddc3febda895679f49fd6e/scene/2d/physics/collision_shape_2d.cpp#L269C1-L288C2

```cpp
void CollisionShape2D::_bind_methods() {
	ClassDB::bind_method(D_METHOD("set_shape", "shape"), &CollisionShape2D::set_shape);
	ClassDB::bind_method(D_METHOD("get_shape"), &CollisionShape2D::get_shape);
	ClassDB::bind_method(D_METHOD("set_disabled", "disabled"), &CollisionShape2D::set_disabled);
	ClassDB::bind_method(D_METHOD("is_disabled"), &CollisionShape2D::is_disabled);
	ClassDB::bind_method(D_METHOD("set_one_way_collision", "enabled"), &CollisionShape2D::set_one_way_collision);
	ClassDB::bind_method(D_METHOD("is_one_way_collision_enabled"), &CollisionShape2D::is_one_way_collision_enabled);
	ClassDB::bind_method(D_METHOD("set_one_way_collision_margin", "margin"), &CollisionShape2D::set_one_way_collision_margin);
	ClassDB::bind_method(D_METHOD("get_one_way_collision_margin"), &CollisionShape2D::get_one_way_collision_margin);
	ClassDB::bind_method(D_METHOD("set_debug_color", "color"), &CollisionShape2D::set_debug_color);
	ClassDB::bind_method(D_METHOD("get_debug_color"), &CollisionShape2D::get_debug_color);


	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "shape", PROPERTY_HINT_RESOURCE_TYPE, "Shape2D"), "set_shape", "get_shape");
	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "disabled"), "set_disabled", "is_disabled");
	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "one_way_collision"), "set_one_way_collision", "is_one_way_collision_enabled");
	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "one_way_collision_margin", PROPERTY_HINT_RANGE, "0,128,0.1,suffix:px"), "set_one_way_collision_margin", "get_one_way_collision_margin");
	ADD_PROPERTY(PropertyInfo(Variant::COLOR, "debug_color"), "set_debug_color", "get_debug_color");
	// Default value depends on a project setting, override for doc generation purposes.
	ADD_PROPERTY_DEFAULT("debug_color", Color());
}
```

### Steps to reproduce

Invoke the godot editor with the ``--dump-extension-api`` arg.  Then inspect the ``extension_api.json`` and see that ``set_debug_color``, ``get_debug_color``, and other related methods that are only available in debug and editor builds are dumped for CollisionShape3D.

# Proposed Solution:

Allow these methods in all builds the same way we do for ColisionShape2D.

### Minimal reproduction project (MRP)

N/A

### CODE REVIEW

**Comment by dsnopek** [comment]
Thanks!

I agree that we shouldn't be conditionally binding these methods - the methods should always exist.

However, do we always want them to actually do something? Is it possible to show debug shapes in release builds? If so, then, yes, then this PR is probably the way to go. But if debug shapes can only be shown in editor or debug builds, then we probably want to remove the functionality in release builds, and just keep the method registration.

**Comment by TCROC** [comment]
I'm honestly not sure.  I've personally never used debug colors.  But I did reference how it is done on the 2d side, and it does look like these ones are functional in release builds and do not differentiate with DEBUG_ENABLED define symbols:

https://github.com/godotengine/godot/blob/19e003bc08ac2fb14fc2434bde9530387afd994c/scene/2d/physics/collision_shape_2d.h

https://github.com/godotengine/godot/blob/19e003bc08ac2fb14fc2434bde9530387afd994c/scene/2d/physics/collision_shape_2d.cpp

I'll let someone with additional expertise on this area of code comment though.  @dsnopek any idea who we should cc?

**Comment by dalexeev** [comment]
* Note that after #100093 you should remove the `#ifdef`s for `CollisionShape2D` too. I was not aware of the negative effect on GDExtension.

**Comment by TCROC** [comment]
@dalexeev sounds good! I'll update the pr! :)

**Comment by TCROC** [comment]
@dalexeev The PR has been updated.  Let me know if you have any other suggestions :)

File: scene/3d/physics/collision_shape_3d.h [hunk 1]
```diff
@@ -43,11 +43,11 @@ class CollisionShape3D : public Node3D {
 	uint32_t owner_id = 0;
 	CollisionObject3D *collision_object = nullptr;
 
-#ifdef DEBUG_ENABLED
 	Color debug_color;
 	bool debug_fill = true;
 
 	Color _get_default_debug_color() const;
+#ifdef DEBUG_ENABLED
```
Comment (dalexeev) [inline scene/3d/physics/collision_shape_3d.h:50]:
```suggestion
	Color _get_default_debug_color() const;

#ifdef DEBUG_ENABLED
```

**Review by dalexeev — APPROVED** [review]
Looks good to me.

File: scene/3d/physics/collision_shape_3d.h (hunk 1 above)
Comment (TCROC) [reply scene/3d/physics/collision_shape_3d.h:50]: @dalexeev You want me to make the _get_default_debug_color a DEBUG_ENABLED only method?  And I presume all of the callers of that method also DEBUG_ENABLED only?

Comment (TCROC) [reply scene/3d/physics/collision_shape_3d.h:50]: Oh wait.  It says you approved this changes.  Should I make a change or are we all good?

Comment (TCROC) [reply scene/3d/physics/collision_shape_3d.h:50]: I'll just go change it quick

Comment (dalexeev) [reply scene/3d/physics/collision_shape_3d.h:50]: I just suggested adding a blank line for better readability.

Comment (TCROC) [reply scene/3d/physics/collision_shape_3d.h:50]: Oh I see.  I thought you were suggesting I move _get_default_debug_color into ``DEBUG_ENABLED``.  I'm actually a fan of doing this as the constructor for CollisionShape2D and CollisionShape3D would no longer need to execute:

```
debug_color = _get_default_debug_color();
```

I expect the runtime overhead is negligeable for the most part.  But if users are spawning "mobs" / millions of colliders, constantly calling ``_get_default_debug_color`` may start to add some unessary overhead on release builds.

So it does make sense to limit this to debug builds.

Comment (TCROC) [reply scene/3d/physics/collision_shape_3d.h:50]: ehhhh or not.  I may be overthinking it.  I'll just go add the extra readability space you suggested

Comment (TCROC) [reply scene/3d/physics/collision_shape_3d.h]: @dalexeev There we go!  I fixed the space! :)  Let me know if there is anything else :)

**Comment by Repiteo** [comment]
Thanks!
