### PR TITLE
[Export] Improve app / file version validation.

### LINKED ISSUE #83379: RCEdit fails on export if no version (FileVersion) is specified
### Godot version

4.2 beta 1

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz (16 Threads)

### Issue description

If you try to export a project as a Windows Runnable and you have RCEdit configured (because for example you want to change the icon of the generated exe) it will fail to run unless you explicitly provide a version for your project. You used to be able to do this without filling out anything for version (in 4.x). This is a regression.

### Steps to reproduce

1. Create a new project. It can remain empty.
2. In editor settings, make sure under Export/Windows that you have rcedit configured correctly.
3. Under Project/Export create a Windows Desktop (Runnable) preset.
4. Click "Export Project..." and put the exe anywhere.
5. Under 4.1.2 that will work fine, under 4.2 beta 1 you will get a dialog with a warning caused by a fatal error (unable to parse version string for FileVersion).
6. The workaround is to to to Project/Project Settings... and under Application/Config fill out something for version, for example 0.0.0.0
7. If you try exporting it again, it now works.
8. If you make that version field empty again, it will fail again.
9. This is a regression from 4.x to 4.2 beta 1.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/83379

### CODE REVIEW

File: editor/export/editor_export_preset.cpp [hunk 1]
```diff
@@ -334,31 +334,55 @@ Variant EditorExportPreset::get_or_env(const StringName &p_name, const String &p
...
+					result = result + ".0";
+				} else {
+					result = vformat("%s.%s.%s.%s", result_split[0], result_split[1], result_split[2], result_split[3]);
+				}
+			} else {
+				result = String(".").join(result_split);
+			}
+		} else {
+			if (!result.is_empty()) {
+				WARN_PRINT(vformat("Invalid version number '%s', version number can only contain numeric characters (0-9) and periods (.).", result));
```
Comment (Calinou) [inline editor/export/editor_export_preset.cpp:379]:
```suggestion
				WARN_PRINT(vformat("Invalid version number \"%s\#. The version number can only contain numeric characters (0-9) and non-consecutive periods (.).", result));
```

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by akien-mga** [comment]
Thanks!
