### PR TITLE
Fix missing icons for custom resources in EditorResourcePicker

### LINKED ISSUE #86072: Custom resource (ArrayMesh) icons are not displayed in resource selector menu and breaks the mesh preview.
### Tested versions

Reproducible in v4.2.stable.arch_linux

### System information

Arch Linux - Godot v4.2.stable.arch_linux

### Issue description

I am working on my custom ArrayMesh class (IcosphereMesh).
After adding `@icon("res://icon.svg")` and restarting the project I figured out that icon is displayed only when resource already set:
image

But in selector menu it has standart resource icon:
image

Also as you can see on the first picture - custom ArrayMesh icon BLOCKS small preview of the mesh 
(preview window is empty) The same picture but with no icon `# @icon("res://icon.svg")` :
image

It is not very important bug but it make me feel quite uncomfortable...

Problem related to Resource icons also was mentioned in this issue: https://github.com/godotengine/godot/issues/82624

### Steps to reproduce

1. Create new project
2. Create 3d scene
3. Add MeshInstance3d to main scene node
4. Create custom class that `extends ArrayMesh`
6. Create a simple surface to be shown in mesh preview display windows
7. Set `MeshInstance3d.mesh` parameter to your custom mesh class
8. Put `@icon("res://icon.svg")`  at the start of class script
9. Reload project
10. Open main scene
11. Open Inspector of MeshInstance3d
12. Unwrap `MeshInstance3d.mesh` property in MeshInstance3d inspector
13. Right click `MeshInstance3d.mesh` to open mesh selector menu.

Results: 
1. Small preview window will be empty,it will show only setted icon and no more. (Bug not affects big preview window in `MeshInstance3d.mesh` inspector)
2. In menu selector your custom array mesh class will have default resource icon that is not equal to "res://icon.svg"

### Minimal reproduction project (MRP)

[project.zip](https://github.com/godotengine/godot/files/13648057/project.zip)

Thank you for your attention and sorry for my bad English. Good luck in engine development.

### PR DESCRIPTION
**Pull request by alessandrofama**
The icons of custom resources created with `class_name` and annotated with `@icon` or GDExtension classes that have an icon specified in the .gdextension file are not appearing in the `EditorResourcePicker`.  The problem is that the `EditorResourcePicker` retrieves the editor theme icon for the resource type and defaults to the `Object` icon if the type wasn't found. This will apply both to `class_name` and GDExtension resources.

This solution addresses the issue by replacing the usage of `Control::get_editor_theme_icon` with `EditorNode::get_class_icon` to ensure the correct icon is retrieved for the resource. Additionally, this fix removes the `custom_resources` lookup above that call, as these resources, added through `EditorPlugin::add_custom_type`, were not being included in the allowed types within `_add_allowed_type` in the `EditorResoucePicker`. Currently, these particular custom resources are never displayed in the picker. The related issue is logged here: #75245.

Fixes #86072.

Example with class_name & GDExtension resources extending ArrayMesh, both with default Godot icon.svg icon, exported ArrayMesh variable:

Before:
Screenshot 2024-01-08 234150

After:
Screenshot 2024-01-08 234332

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
Looks good and works as expected, thanks!

There is a slight concern that the new lookup path can be slower when you have many custom resources. But that's already a problem across the editor and the solution is to improve caching.

I can also confirm that old style custom types are not working in the resource picker at the moment. The removal of related code is justified IMO, and if we ever fix those custom types, icon lookup should be re-implemented as a part of the `get_class_icon` method.

File: editor/editor_resource_picker.cpp [hunk 1]
```diff
@@ -943,6 +926,7 @@ void EditorResourcePicker::_ensure_resource_menu() {
 	add_child(edit_menu);
 	edit_menu->connect("id_pressed", callable_mp(this, &EditorResourcePicker::_edit_menu_cbk));
 	edit_menu->connect("popup_hide", callable_mp((BaseButton *)edit_button, &BaseButton::set_pressed).bind(false));
+	edit_menu->add_theme_constant_override("icon_max_width", get_theme_constant(SNAME("class_icon_size"), EditorStringName(Editor)));
```
Comment (YuriSizov) [inline editor/editor_resource_picker.cpp:929]: We would generally put all configuration lines before `add_child` (except signal connects, which we usually put after `add_child`, like it's done here). But this isn't critical.

Comment (alessandrofama) [reply editor/editor_resource_picker.cpp]: Ah that is good to know! Fixed & I will keep this in mind for next time. Thank you!
