### PR TITLE
Fix incorrect default `transfer_mode` in `@rpc` documentation

### LINKED ISSUE #8874: GDScript.@rpc documentation is inconsistent with C# RpcAttribute
**Your Godot version:**

4.2.1

**Issue description:**

Apologies if this is actually a code bug, I'm not sure where the GDScript code comes from to check on that. I've observed that the `GDScript.@rpc` documentation says `@rpc ( ... transfer_mode="unreliable", ...)` but the C# [RpcAttribute.cs](https://github.com/godotengine/godot/blob/9adb7c7d130c6d4eb0e80b92d6eebd71fac3384d/modules/mono/glue/GodotSharp/GodotSharp/Core/Attributes/RpcAttribute.cs#L27) is defaulting it to `MultiplayerPeer.TransferModeEnum.Reliable`. Again, I'm not sure if this is an issue with the documentation or an issue with the code.

**URL to the documentation page:**

https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-rpc

### PR DESCRIPTION
**Pull request by nanodeath**
The documentation incorrectly stated that the default transfer_mode for `@rpc` is "unreliable", but the actual in code is "reliable".

GDScript ref: https://github.com/godotengine/godot/blob/3b48b0110e04e84db54788ccda4f8f5f7fa1fcf4/modules/multiplayer/scene_rpc_interface.cpp#L90
C# ref: https://github.com/godotengine/godot/blob/3b48b0110e04e84db54788ccda4f8f5f7fa1fcf4/modules/mono/glue/GodotSharp/GodotSharp/Core/Attributes/RpcAttribute.cs#L27

Fixes godotengine/godot-docs#8874
Related docs fix: godotengine/godot-docs#11554

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -186,7 +186,8 @@ GDScriptParser::GDScriptParser() {
 		register_annotation(MethodInfo("@warning_ignore_start", PropertyInfo(Variant::STRING, "warning")), AnnotationInfo::STANDALONE, &GDScriptParser::warning_ignore_region_annotations, varray(), true);
 		register_annotation(MethodInfo("@warning_ignore_restore", PropertyInfo(Variant::STRING, "warning")), AnnotationInfo::STANDALONE, &GDScriptParser::warning_ignore_region_annotations, varray(), true);
 		// Networking.
-		register_annotation(MethodInfo("@rpc", PropertyInfo(Variant::STRING, "mode"), PropertyInfo(Variant::STRING, "sync"), PropertyInfo(Variant::STRING, "transfer_mode"), PropertyInfo(Variant::INT, "transfer_channel")), AnnotationInfo::FUNCTION, &GDScriptParser::rpc_annotation, varray("authority", "call_remote", "unreliable", 0));
+		// Default transfer_mode is "reliable". Keep in sync with `rpc_annotation()` and `SceneRPCInterface::_parse_rpc_config()`.
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp]:
```suggestion
		// Keep in sync with `rpc_annotation()` and `SceneRPCInterface::_parse_rpc_config()`.
```

**Review by dalexeev — APPROVED** [review]
Looks good to me! Please use backticks (`` `@rpc` ``) for annotation names in commit messages, posts/comments, and in titles (just in case) to prevent mentioning random GitHub users.

**Comment by akien-mga** [comment]
Thanks!
