### PR TITLE
Fix the credits not being centered

### LINKED ISSUE #118696: Incorrect position of credits roll
### Tested versions

- Reproducible in: v4.7.dev [a8643700c]

### System information

N/A

### Issue description

Godot's easter egg, a credits roll, is incorrectly positioned to the right.

|Correct|Incorrect|
|-|-|
|Image|Image|

Regression from #118536. CC @StarryWorm.
The credits roll file is located here: https://github.com/godotengine/godot/blob/master/editor/gui/credits_roll.cpp

### Steps to reproduce

- Open the about dialog.
- Click multiple times in Akien's name.

### Minimal reproduction project (MRP)

Unnecessary.

### PR DESCRIPTION
**Pull request by StarryWorm**
* Fixes #118696 

#118536 introduced a deferred `_update_minimum_size()` call, which, for some reason, messed up the credits roll. 
Turns out, due to the way the credits are constructed, this deferred update caused the content VBox to realize "oh, hey, I'm supposed to expand since I have content", a realization it was not having before somehow. So the bug had actually been dormant until now, and it's only now that it's triggered by this deferred call. 
I'm still not exactly sure how that's possible, but that knowledge is not needed to fix it.

The solution: simply make it grow correctly. 

AI disclaimer: Opus 4.6 helped me understand what changed with the commit from that PR. Once it told me, the fix was trivial, and I did it myself.

### CODE REVIEW

File: editor/gui/credits_roll.cpp [hunk 1]
```diff
@@ -232,6 +232,7 @@ void CreditsRoll::roll_credits() {
 	}
 	// Needs to be set here, so it stays centered even if the window is resized.
 	content->set_anchors_and_offsets_preset(Control::PRESET_VCENTER_WIDE);
+	content->set_grow_direction_preset(Control::PRESET_VCENTER_WIDE);
```
Comment (YeldhamDev) [inline editor/gui/credits_roll.cpp]: This can be placed in the constructor.

File: editor/gui/credits_roll.cpp [hunk 2]
```diff
@@ -232,6 +232,7 @@ void CreditsRoll::roll_credits() {
 	}
 	// Needs to be set here, so it stays centered even if the window is resized.
```
Comment (YeldhamDev) [inline editor/gui/credits_roll.cpp]:
```suggestion
	// Needs to be set here, otherwise the starting position will be incorrect.
```

**Review by YeldhamDev — CHANGES_REQUESTED** [review]

File: editor/gui/credits_roll.cpp (hunk 2 above)
Comment (StarryWorm) [reply editor/gui/credits_roll.cpp]: Not a big fan of touching something that is not the objective of my PR. But sure, I trust your judgment that this fits within the scope of the PR.

Comment (YeldhamDev) [reply editor/gui/credits_roll.cpp]: It's because the original text is not true anymore, and it's better change it here instead of creating another PR just to change a comment.

**Review by YeldhamDev — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
