### PR TITLE
Fix animation keying not working with toggleable inspector sections

### LINKED ISSUE #107826: Toggleable Group Checkbox Doesn't Update in Inspector After External Change
### Tested versions

- Reproducible in: v4.5.beta1.official [46c495ca2]

### System information

Godot v4.5.beta1 - Windows 11 (build 26100) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21923.1000) - Genuine Intel(R) CPU 0000 @ 2.60GHz (16 threads) - 15.84 GiB memory

### Issue description

When using `@export_custom` with `PROPERTY_HINT_GROUP_ENABLE` for a toggleable group, the associated checkbox in the Inspector does not update visually when its value is changed externally via a `@tool` script.

Here is a video of the issue:

https://github.com/user-attachments/assets/bec928e1-ada8-426c-af72-0333c97e3ef0

### Steps to reproduce

1. Create a new Node in a scene (e.g., a `Node2D`).

2. Attach a new script to this node.

3. Inside the script, define two `@export_group`.

4. For each group, add an `@export_custom` variable using `PROPERTY_HINT_GROUP_ENABLE`.

5. Implement a setter on one of these variables. In the setter, set its own value and also set the other group's variable to the inverse of the current value.

Here's an example script:
```GDScript
@tool
extends Node

@export_group("Test A")
@export_custom(PROPERTY_HINT_GROUP_ENABLE, "") var enable_a: bool = false

@export_group("Test B")
@export_custom(PROPERTY_HINT_GROUP_ENABLE, "") var enable_b: bool = false:
	set(value):
		enable_b = value
		enable_a = !value
		print("Actual Test A status: %s" % !value)
```

6. Save your scene.

7. Reload the scene.

8. With the node selected in the Scene tree, toggle the **Test B** checkbox (the one with the setter) multiple times, the **Test A** will not update unless you deselect the node and select again.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/20850280/mrp.zip)

### LINKED ISSUE #107891: Editor sections enable checkboxes loss keyframe buttons
### Tested versions

- Reproducible in: 4.5beta1

### System information

Godot v4.5.beta1 - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.7628) - 12th Gen Intel(R) Core(TM) i5-12490F (12 threads) - 31.81 GiB memory

### Issue description

Maybe related to #105272, #105623.
When using a AnimationPlayer to animate properties, u will find that those properties with editor sections enable checkboxes loss keyframe buttons.

For example(Camera2D):

Image

### Steps to reproduce

1. Create a Camera2D node
2. Create a AnimationPlayer node and create a new animation
3. Select the Camera2D node, check the inspector proprieties

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by lodetrick**
Closes #107891 Closes #107826
Supersedes #107857

This PR adds the animation keying button to toggleable sections. This also allows the buttons to update over time in order to  accommodate how the animation editor edits the values.

### CODE REVIEW

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -1928,6 +1928,30 @@ void EditorInspectorSection::_notification(int p_what) {
 				Ref<Font> light_font = theme_cache.light_font;
 				int light_font_size = theme_cache.light_font_size;
 
+				// - Keying
+				Ref<Texture2D> key = theme_cache.icon_gui_animation_key;
+				if (keying && key.is_valid()) {
+					Point2 key_position;
+					key_position.x = rtl ? margin_end + 2 * EDSCALE : get_size().width - key->get_width() - margin_end - 2 * EDSCALE;
```
Comment (AThousandShips) [inline editor/editor_inspector.cpp]:
```suggestion
					key_position.x = rtl ? (margin_end + 2 * EDSCALE) : (get_size().width - key->get_width() - margin_end - 2 * EDSCALE);
```
For readability

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Code looks good to me.

**Comment by lodetrick** [comment]
I just pushed a fix that allows the "favorited" sections to update properly, I just added the relevant ones to the `sections` list (which is used to fold and unfold everything and update the properties now).

It was two lines of code, 4492 and 4532

File: editor/editor_inspector.cpp [hunk 2]
```diff
@@ -5404,6 +5494,12 @@ void EditorInspector::_notification(int p_what) {
 					}
 					pending.remove(pending.begin());
 				}
+
+				for (EditorInspectorSection *S : sections) {
+					if (S && S->is_checkable()) {
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp]: Can `S` be null?

File: editor/editor_inspector.cpp [hunk 3]
```diff
@@ -2251,6 +2292,17 @@ void EditorInspectorSection::set_bg_color(const Color &p_bg_color) {
 	queue_redraw();
 }
 
+void EditorInspectorSection::set_keying(bool p_keying) {
+	if (keying == checkable && p_keying) {
```
Comment (KoBeWi) [inline editor/editor_inspector.cpp]: Matches the assign below. Unless it was intended like this?
```suggestion
	if (keying == (checkable && p_keying)) {
```

**Comment by lodetrick** [comment]
I resolved the comments and adapted the folding code to handle the fact that toggleable sections can now be not foldable (since the sections in favorites were added to sections which meant that fold and unfold were called on them)

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
