### PR TITLE
Fix displacement for centered tilemaps

### LINKED ISSUE #3209: Invalid Tile origin when set as Center
You can recreate this bug with the Kinematic Collision demo:
- Set the TileMap's _Cell_->_Tile Origin_ property to _Center_.
- Select the tile and compare its preview origin to the added tiles origin.

You should see something like this:
vs4itdo

The origin for the added tile is different than the preview's. I am not sure if the preview is the right one or if it should be like this:

igg

### PR DESCRIPTION
**Pull request by hoelzl**
This PR fixes the issue mentioned in #3209, if I understand the problem correctly. I'd be glad to get feedback from people who have more experience with 2D editors whether the behavior with this PR is as intended.

Square cells seem to work the same for all three origin settings, including collision and navigation, no matter how they are transformed or flipped. The test project below contains a number of examples.

Non-square cells don't really work for anything but top-left origin when they are transformed or flipped, but neither do they in the current master. It's not even clear to me what the desired behavior for transformations of non-square cells should be. One way would be to emulate the current "top-left behavior" for all origins, although this does not seem desirable to me: Right now, if you flip a non-square cell horizontally, it does not stay within its bounds but is displaced to the left. I suppose this is done so that the "rotation" buttons (which just select a combination of transposition and h/v flipping) rotate tiles around the center point of the leftmost square (when the origin is top-left, obviously).

Centered isometric tiles also work if they are not transformed. How transforms affect them depends on their size relative to the cell size, and whether they use a region. Since isometric tiles generally don't look right when transformed I don't think this is a problem.

Like I said in IRC, this PR is just trying to fix the most prominent inconsistencies in the current tile map implementation with a minimal amount of changes. To address more of the issues with the tilemap editor, e.g., those mentioned in the discussion of #13062, it would make sense to clarify what the actual use cases are and how the individual features *should* interact. (And to refactor the code to implement them in a cleaner way).

Test project is at <https://gitlab.com/mhoelzl/TilemapTest>.

Fixes #3209

### CODE REVIEW

File: editor/plugins/tile_map_editor_plugin.cpp [hunk 1]
```diff
@@ -565,20 +565,31 @@ void TileMapEditor::_draw_cell(int p_cell, const Point2i &p_point, bool p_flip_h
...
+		Size2 cell_size = node->get_cell_size();
 
-		Vector2 center = (s / 2) - tile_ofs;
+		rect.position += tile_ofs;
 
-		if (p_flip_h)
-			rect.position.x -= s.x - center.x;
-		else
-			rect.position.x -= center.x;
+		if (p_transpose) {
```
Comment (akien-mga) [inline editor/plugins/tile_map_editor_plugin.cpp]: Aren't the two branches doing the exact same thing?

File: scene/2d/tile_map.cpp [hunk 2]
```diff
@@ -429,20 +433,30 @@ void TileMap::_update_dirty_quadrants() {
...
 
-				Vector2 center = (s / 2) - tile_ofs;
-				center_ofs = tcenter - (s / 2);
+				rect.position += tile_ofs;
 
-				if (c.flip_h)
-					rect.position.x -= s.x - center.x;
-				else
-					rect.position.x -= center.x;
+				if (c.transpose) {
```
Comment (akien-mga) [inline scene/2d/tile_map.cpp]: Same here.

**Comment by akien-mga** [comment]
CC @MarianoGnu for review since you got familiar with TileMap recently :)

File: editor/plugins/tile_map_editor_plugin.cpp (hunk 1 above)
Comment (Zylann) [reply editor/plugins/tile_map_editor_plugin.cpp]: One is subtracting, the other is adding

Comment (hoelzl) [reply editor/plugins/tile_map_editor_plugin.cpp]: How embarassing...
I'll push an updated PR once I've run the tests, just to make sure I didn't mess anything up with the change.
