### PR TITLE
Fix some `SpotLight3D` issues (clustering artifacts, leaking light, AABB)

### LINKED ISSUE #48054: Vulkan: SpotLight3D angles above 90 degrees cause clustering artifacts (even with shadows disabled)
**Godot version:**
4.0.dev f817e7fb

**OS/device including version:**
Windows 10.0.19041.928
Nvidia RTX 2080 Ti
Driver version 466.22 

**Issue description:**
SpotLight angles seem doubled from what makes intuitive sense to me. For example, an angle of 120 degrees covers roughly 240 degrees of the sphere. 179 degrees covers effectively the whole sphere, same as an omni light.

However, when the Spotlight angle exceeds a Hemisphere (90 degrees in Godot), the spotlight continues to expand, but the clusters collapse to (180-angle) degrees, causing the square clustering artifacts.

image

My opinion is spotlights which are greater than a hemisphere are kind of a strange concept, but if they are intended to be supported, perhaps this could be worked around by having the clustering algorithm treat them like omni lights.

**Steps to reproduce:**
1. Open the attached project
2. Zoom the camera as in the above screenshot, so that the camera is facing the spotlight and the capsule is off to the side.
3. Play with the spot angle and note how as the angle increases, the cluster squares diminish.
4. For spot angles < 90, everything renders perfectly fine.

**Minimal reproduction project:**
[SpotLightClusterTest.zip](https://github.com/godotengine/godot/files/6346350/SpotLightClusterTest.zip)

### LINKED ISSUE #59262: Vulkan: SpotLight3D + WorldEnvironment fog causes jaggedness due to clustering issues
### Godot version

4.0 Alpha 3

### System information

Windows 10, 3060

### Issue description

My Spotlight is at 500 Energy. 
Screenshot 18-03-2022 12_03_58 PM

### Steps to reproduce

WorldEnvironment Fog
Spotlight
Crank on the energy

### Minimal reproduction project

_No response_

### LINKED ISSUE #68969: Vulkan: SpotLight3D exhibits clustering artifacts at small angle relative to the surface
### Godot version

4.0.beta5.mono (89a33d28f)

### System information

Windows 11, Vulkan (forward_plus), NVIDIA RTX 2070 SUPER (522.25)

### Issue description

When using custom values for attenduation:
image

With default settings it is still visible, but barely:
image

Please find the attached reproduction project.

### Steps to reproduce

Please find the attached reproduction project.

### Minimal reproduction project

[SpotlightBugProject.zip](https://github.com/godotengine/godot/files/10059764/SpotlightBugProject.zip)

### LINKED ISSUE #69936: Vulkan: SpotLight3D affects lighting outside of the cone
### Godot version

4.0.beta8

### System information

Windows 10, Vulkan, Nvidia RTX 3060 ti, driver version 527.56

### Issue description

Spot lights have a strange ring around them, which seems to vary depending on distance and angle. It can be light or dark as well, seemingly at random.
image

This is in the Mobile renderer. The Forward+ renderer has a similar issue, but it's localized only to the clusters that contain the spot light cone.
When trying to reproduce in the OpenGL renderer, I just got errors.

### Steps to reproduce

Add a spot light to a dark scene (set ambient light to low, but not black.)
Set size to somewhere around 35 degrees for best results.
Full ring is more visible in mobile renderer.

### Minimal reproduction project

[SpotLightError.zip](https://github.com/godotengine/godot/files/10203733/SpotLightError.zip)

### LINKED ISSUE #70698: Vulkan Clustered: SpotLight3D clustering artifacts with no fog or other effects
### Godot version

4.0.beta10.official [d0398f62f]

### System information

Windows 10, Vulkan, NVIDIA GeForce RTX 2060m (31.0.15.2698)

### Issue description

I'm getting some kind of clustering/blocky artifact when using spotlights, with no fog or any fancy rendering stuff whatsoever.
I've looked through a bunch of similar issues, but the only ones I could find were related to volumetric fog or other environment effects that I am not using.
Not sure if I'm just missing something, but I think I've played with every option in the spotlight and every option in a WorldEnvironment and nothing makes it go away.

The only lead I have is that the intensity of the artifact seems to be affected by the spot angle. It cycles in a sawtooth pattern every ~0.07 degrees.

image

Lmk if you need more info or need me to try anything.

### Steps to reproduce

1. New Project (Forward+)
2. Put down some MeshInstance3Ds as a backdrop
3. Put a SpotLight3D
4. Raise spotlight intensity, lower spot angle, and increase range to see it better
5. Slowly increase spot angle to see cycling effect

### Minimal reproduction project

[testspotlight.zip](https://github.com/godotengine/godot/files/10318069/testspotlight.zip)

### PR DESCRIPTION
**Pull request by Geometror**
- Fixes light leak to the outside of the cone, visible at certain cone angles (the leaked light changed periodically from being negative to positive, see green spot lights with slightly different spot angle in picture below)
	Fixes #70698
	Fixes #69936
	Fixes #68969
	Fixes #59262 (likely, could not test since no MRP was provided)
	(These basically boil down to the same bug: no clustering issue, but since the light leaks in directions where the cluster builder doesn't expect it to be it looks blocky; its also visible in the mobile renderer)
	Cause: Bisected to #51843. Seems to be a precision issue, changing the precision of `cone_angle` from `mediump` to `highp` in the `LightData` struct (`light_data_inc.glsl`) also fixes the issue, but I went with converting `cone_angle` to a `highp float` inside the shader so the struct size doesn't have to be increased.

- Fixes AABB generation
	The wrong trigonometric function was used, so the AABB would grow towards infinity for angles close to 90 degrees. For angles above 90 degrees a box enclosing the whole sphere (radius = range) is generated.

- Fixes clustering for angles close to and above 90 degrees
	Fixes #48054
	Introduces a threshold constant: the angle above which the cluster builder uses a sphere instead of a cone (see comment in code).

**Before**
Godot_v4 0-beta14_win64_nSIGPu2u3W

**With this PR**
0nhWuPqzLZ

### CODE REVIEW

File: servers/rendering/renderer_rd/cluster_builder_rd.h [hunk 1]
```diff
@@ -49,7 +49,7 @@ class ClusterBuilderSharedDataRD {
 	RID cone_vertex_array;
 	RID cone_index_buffer;
 	RID cone_index_array;
-	float cone_overfit = 0.0; //because an cone mesh is not a perfect sphere, we need to enlarge it to cover the actual cone area
+	float cone_overfit = 0.0; //because an cone mesh is not a perfect cone, we need to enlarge it to cover the actual cone area
```
Comment (clayjohn) [inline servers/rendering/renderer_rd/cluster_builder_rd.h:52]: Style nitpick. This should use our standard formatting of starting with a space and a capital and ending with a period

**Review by clayjohn — APPROVED** [review]
Just a little style nitpick. Otherwise the PR looks good!

Tested locally using an Nvidia GPU which could reproduce the listed issues. This PR fixes the issues

File: servers/rendering/renderer_rd/cluster_builder_rd.h (hunk 1 above)
Comment (Geometror) [reply servers/rendering/renderer_rd/cluster_builder_rd.h]: I took the liberty to fix the formatting (+ sometimes grammar/clarity) of all comments in `cluster_builder_rd.h/cpp`. That might be a bit out of scope, but I thought better now than never :)

**Review by clayjohn — APPROVED** [review]

File: servers/rendering/renderer_rd/cluster_builder_rd.h (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/cluster_builder_rd.h]: Wonderful!

**Comment by akien-mga** [comment]
Thanks!
