### PR TITLE
Move skin registration process into deferred on ready

### LINKED ISSUE #97459: `MeshInstance3D` disappears at runtime if its skeleton is not a direct parent
### Tested versions

Reproducible in 4.3.stable and 4.4.dev2
**NOT** reproducible in 4.2.stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6109) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

When a `MeshInstance3D`'s skeleton is not a direct parent, it works fine in editor, but at runtime, the mesh disappears. This worked previously in `4.2`. In the attached video, the red fish has the skeleton under the mesh, the green fish has the mesh under the skeleton, and the blue fish has skeleton and mesh as siblings. When you run the game, the red fish and the blue fish disappear.

https://github.com/user-attachments/assets/d515c724-bc86-4996-bcf8-04696d870107

### Steps to reproduce

- Open `test.tscn` in the attached project
- Run the game
- Observe that only the green fish remains

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/17134814/bug-report.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes https://github.com/godotengine/godot/issues/97459

Since the initial update of the skin is done in the skeleton's deferred process, it seems that the process that searches for the skeleton when the skin is first loaded into the tree should also be moved to the deferred process.

However, I am not so familiar with the Skin deformation process in MeshInstance3D, so I am not sure if this is really the correct fix. Although, I think it is safe since this just move the process timing on loading, but please review/test carefully. cc @fire @MajorMcDoom

### CODE REVIEW

File: scene/3d/mesh_instance_3d.cpp [hunk 1]
```diff
@@ -332,8 +332,8 @@ void MeshInstance3D::create_multiple_convex_collisions(const Ref<MeshConvexDecom
 
 void MeshInstance3D::_notification(int p_what) {
 	switch (p_what) {
-		case NOTIFICATION_ENTER_TREE: {
-			_resolve_skeleton_path();
+		case NOTIFICATION_READY: {
+			call_deferred("_resolve_skeleton_path");
```
Comment (AThousandShips) [inline scene/3d/mesh_instance_3d.cpp:336]: Any reason this can't be a normal deferred call?

Comment (TokageItLab) [reply scene/3d/mesh_instance_3d.cpp:336]: I have confirmed that normal ready did not solve the MRP issue, I expect it is because Skeleton always uses the deferred process for Skin updates, but as I mentioned in the overview, I don't know if this is the right direction for a fix.

Comment (AThousandShips) [reply scene/3d/mesh_instance_3d.cpp:336]: No I meant:
```suggestion
	callable_mp(this, &MeshInstance3D::_resolve_skeleton_path).call_deferred();
```

Comment (akien-mga) [reply scene/3d/mesh_instance_3d.cpp:336]: I think she meant you could use `callable_mp`, and then you don't have to bind the method.
```
callable_mp(this, &MeshInstance3D::_resolve_skeleton_path).call_deferred();
```

(it may need to be `public` in C++ though, not sure)

Comment (TokageItLab) [reply scene/3d/mesh_instance_3d.cpp:336]: Ah do you means it should be used `callable_mp().call_deferred()` ? Yes, that's true. I'll rewrite it.

**Review by akien-mga — APPROVED** [review]
If it works, that looks good to me. Let's wait for confirmation.

**Comment by MajorMcDoom** [comment]
Seems to work on my end with the repro project!

**Comment by akien-mga** [comment]
Thanks!
