### PR TITLE
[FontData] Fixes saving copy of the font source data, if it was created from built-in font.

### LINKED ISSUE #53253: Wrong glyphs rendered in Label with custom theme derived from editor theme
### Godot version

v4.0.dev.custom_build [5489f4384]

confirmed in v4.0.dev.custom_build [ac7505e27]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

After opening a project with a addon, the text was all messed:
Peek 2021-09-30 07-55

### Steps to reproduce

* Open Project
* Open Addon Scene

### Minimal reproduction project

this is an addon, so in order to install:
* Create a new project
* Create an addon folder
* inside use the command bellow
`git clone git@github.com:nonunknown/gdextension-integration.git`

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #53253 (theme in the extension should be reimported to work).

### CODE REVIEW

File: scene/resources/font.cpp [hunk 1]
```diff
@@ -502,6 +502,11 @@ void FontData::set_data(const PackedByteArray &p_data) {
 }
 
 PackedByteArray FontData::get_data() const {
+	if (unlikely((size_t)data.size() != data_size)) {
```
Comment (akien-mga) [inline scene/resources/font.cpp:505]: If feels weird that this could happen and be handled in the getter specifically. Shouldn't it be properly matching if `set_data()` was called?

Comment (bruvzg) [reply scene/resources/font.cpp:505]: It could be handled in the `set_data_ptr`, but then it will create extra copy of all editor fonts every time (more than 10 MB of wasted memory), this way `PackedByteArray` copy is created on demand.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
