### PR TITLE
LSP: Fixing URI and path formating problems on unix systems regression from #63388

### LINKED ISSUE #64064: PR #63388 broke LSP on Linux
### Godot version

v4.0.alpha.custom_build [f2ddd8172]

### System information

Linux

### Issue description

#63388 replaces `///` with `//` in LSP file paths, which apparently fixes #63205 on Windows. But `file:///` is entirely correct on Linux and much LSP functionality is now broken on Linux as a result. For example, externally modified script files are not reloaded and features like _go to definition_ does not work in the LSP client.

The console is spammed with these two errors:

```
ERROR: Attempt to open script 'file:/home/<snip>' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1062)
ERROR: Attempt to open script 'file://home/<snip>' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1062)
```
I reverted commit 3fa943fe23 locally and that fixed the problem.

Ping @A-Lamia and sorry for reporting a bug on your first commit.

### Steps to reproduce

1. Open Godot editor on Linux.
2. Connect an editor via LSP.
3. Notice the errors in the Godot console.
4. Notice that modified script files are not reloaded in Godot.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by A-Lamia**
Reported Issue: #64064

Needs testing on linux and some other problems i might look in to before this should be merged to master.

*Bugsquad edit:*
- Fixes #64064

### CODE REVIEW

File: modules/gdscript/language_server/gdscript_language_protocol.cpp [hunk 1]
```diff
@@ -184,7 +184,9 @@ Dictionary GDScriptLanguageProtocol::initialize(const Dictionary &p_params) {
 	if (root_uri.length() && is_same_workspace) {
 		workspace->root_uri = root_uri;
 	} else {
-		workspace->root_uri = "file://" + workspace->root;
+		String r_root = workspace->root;
+		r_root = r_root.replacen(":", "%3A");
+		workspace->root_uri = "file:///" + r_root;
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: Isn't that going to be one `/` too much on Unix?

Comment (A-Lamia) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: it shouldn't be the root_uri should be `file:///c%3A` as that is what the LSP server communicates with this then gets converted to `res://` in `get_file_path()` also made sure that `get_file_uri()` would correctly convert it back to `file:///c%3A`.

Comment (akien-mga) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: Well `c%3A` is just `c:` which is the default root partition on Windows. I don't think that applies to Linux and macOS?

**Comment by permelin** [comment]
So, as I understand it, the problem is that:
1. Paths sent by the LSP client are URL encoded: space is replaced by either `+` or `%20` and some other symbols are replaced by `%xx`
2. The workspace `root_uri` however is not URL encoded.
3. Therefore matching `root_uri` with the beginning of URIs from the client to replace it with `res://` fails when one is encoded and the other one is not.

Can't that be fixed by simply swapping the order of two lines and running `uri_decode()` on the URI from the client **before** matching against `root_uri` (currently it is done afterwards)? Like this:
```
path = path.uri_decode();
path = path.replace(root_uri + "/", "res://");
```

File: modules/gdscript/language_server/gdscript_language_protocol.cpp (hunk 1 above)
Comment (permelin) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: `workspace->root` already starts with `/` on Linux and macOS, so you'll end up with `file:////` which won't work.

**Comment by A-Lamia** [comment]
@permelin sadly that will not work, it will still fail on windows `root_uri` will still be incorrect. the `root_uri` must be the same `uri` being sent through the lsp buffer, that's what's being replaced and turned in to `res://`.

File: modules/gdscript/language_server/gdscript_language_protocol.cpp (hunk 1 above)
Comment (A-Lamia) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: ok so i see what is going on here windows will return `c%3A\\path\\to\\root` and linux will return `\path\to\root` ?

**Comment by A-Lamia** [comment]
Ok so this fixes the decode issues and the missing forward slash issue.

File: modules/gdscript/language_server/gdscript_language_protocol.cpp [hunk 2]
```diff
@@ -184,7 +184,9 @@ Dictionary GDScriptLanguageProtocol::initialize(const Dictionary &p_params) {
 	if (root_uri.length() && is_same_workspace) {
 		workspace->root_uri = root_uri;
 	} else {
-		workspace->root_uri = "file://" + workspace->root;
+		String r_root = workspace->root;
+		r_root = r_root.lstrip("/");
+		workspace->root_uri = "file:///" + r_root;
```
Comment (akien-mga) [inline modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: Is this change still needed at all? This looks wrong and might break on Windows (and is unnecessary on Linux).

The be clear, the `file://` protocol is `file://` - two slashes. After that should come a valid URI.

On Linux a valid URI for an absolute path will start with `/` so it will indeed be `file:///home/akien/...` etc.
On Windows AFAIU a valid URI will start with `c:\\path\\to\\root` so it would become `file://c:\\path\\to\\root` which should be fine.

Comment (permelin) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: @akien-mga If I understand @A-Lamia correctly, the problem is that this `root_uri` is later matched against other paths coming from the LSP client, and apparently they are sent like this on Windows clients: `file:///c:/path/to/root`.

Comment (permelin) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: If that is the case, I wonder if this wouldn't be the less error prone way to do this?
```C
#ifndef WINDOWS_ENABLED
		workspace->root_uri = "file://" + workspace->root;
#else
		workspace->root_uri = "file:///" + workspace->root;
#endif
```
It assumes that `workspace_root` is always absolute, which seems like a reasonably safe assumption? It also assumes that the LSP client and server are on the same OS.

There is also the risk that this path format is actually different on different LSP client implementation on Windows.

Comment (akien-mga) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: Alright, reading https://en.wikipedia.org/wiki/File_URI_scheme it does seem indeed that the prefix will often be `file:///` because it should be `file://` + `host` + `/` + `path` and `host` can be empty to default to localhost.

So `file:///c:/path/to/root` is indeed valid. And reading that page I would actually expect a Linux absolute path to be `file:////path/to/file` or `file://localhost//path/to/file`, but I guess they made the root slash optional.

So this fix looks good indeed.

**Review by akien-mga — APPROVED** [review]
Looks correct to me after discussion.

File: modules/gdscript/language_server/gdscript_language_protocol.cpp (hunk 2 above)
Comment (permelin) [reply modules/gdscript/language_server/gdscript_language_protocol.cpp:189]: File URI format is defined in [RFC 8089](https://datatracker.ietf.org/doc/html/rfc8089) and according to [Wikipedia](https://en.wikipedia.org/wiki/File_URI_scheme) this is the correct way:
```
file:///c:/WINDOWS/clock.avi
```

Interestingly, the article also says:
> A valid file URI must therefore begin with either file:/path (no hostname), file:///path (empty hostname), or file://hostname/path.
> file://path (i.e. two slashes, without a hostname) is never correct, but is often used.

**Comment by A-Lamia** [comment]
seems like neovim isn't working but VScode is, so i need to see what the issue is.

**Comment by permelin** [comment]
It works on my Linux with neovim.

**Comment by A-Lamia** [comment]
Neovim:
"rootPath":"X:\\path\\to\\root"
"rootUri":"file:\/\/\/X:\/path\/to\/root",

VSCode:
"rootPath":"x:\\path\\to\\root",
"rootUri":"file:///x%3A/path/to/root",

Oh god, seems like we may have an issue.

**Comment by A-Lamia** [comment]
> It works on my Linux with neovim.

I get an initial connection then nothing.

**Comment by permelin** [comment]
OK, so it doesn't _always_ work for me.

There are two different branches the code can take: one if the Godot editor is opened with the same project as the LSP client, and another branch if the projects are different.

When the projects are different, LSP does **not** work for me with this patch. However, neither does it in 4.0alpha12 or 3.5.

@A-Lamia in your tests, are you opening the same project in both Godot and VSCode/Vim? Because half of the changes you've made here are only for when they are different.

**Comment by A-Lamia** [comment]
@permelin for the most part all the tests i have done with the first path return the correct path because it is using the URI directly for the LSP buffer rather then from `workspace->root`.

So the issue you are having is in the main project directory project sub directories, what i fixed for windows was the sub directories.

**Comment by permelin** [comment]
> So the issue you are having is in the main project directory or sub directories ? what i fixed for windows was the sub directories.

Doesn't matter. I get exactly the same values in the debugger for `is_same_workspace`, `root` and `root_uri` regardless of whether it's a subdirectory or not.

It seems wrong to me if  `is_same_workspace` is `false` for you in subdirectories. That's can't be how it's suppose to be.

**Comment by A-Lamia** [comment]
@permelin i have just fixed both ways for windows, now we need to figure out what is happening on your end. could you tell me what your path looks like for `root_uri`, `root` and `workplace->root` ?

**Comment by permelin** [comment]
Same project
```
(bool) is_same_workspace = true
(String) root_uri = {
  _cowdata = (_ptr = U"file:///home/p/Godot/Lab4")
}
(String) root = {
  _cowdata = (_ptr = U"/home/p/Godot/Lab4")
}
(String) workspace->root = {
  _cowdata = (_ptr = U"/home/p/Godot/Lab4")
}
```

Different projects
`Lab4` in Godot and `Test` in Vim
```
(bool) is_same_workspace = false
(String) root_uri = {
  _cowdata = (_ptr = U"file:///home/p/Godot/Test")
}
(String) root = {
  _cowdata = (_ptr = U"/home/p/Godot/Test")
}
(String) workspace->root = {
  _cowdata = (_ptr = U"/home/p/Godot/Lab4")
}
```

**Comment by A-Lamia** [comment]
> Same project
> 
> ```
> (bool) is_same_workspace = true
> (String) root_uri = {
>   _cowdata = (_ptr = U"file:///home/p/Godot/Lab4")
> }
> (String) root = {
>   _cowdata = (_ptr = U"/home/p/Godot/Lab4")
> }
> (String) workspace->root = {
>   _cowdata = (_ptr = U"/home/p/Godot/Lab4")
> }
> ```
> 
> Different projects `Lab4` in Godot and `Test` in Vim
> 
> ```
> (bool) is_same_workspace = false
> (String) root_uri = {
>   _cowdata = (_ptr = U"file:///home/p/Godot/Test")
> }
> (String) root = {
>   _cowdata = (_ptr = U"/home/p/Godot/Test")
> }
> (String) workspace->root = {
>   _cowdata = (_ptr = U"/home/p/Godot/Lab4")
> }
> ```
Should that bottom one bet lab4 i think i might understand what is going on here.

**Comment by permelin** [comment]
> and yes it being false when you initialize the LSP connection in a none root folder changes where it gets the root uri from so it's working as it's intended

This makes no sense to me. Your LSP client must know where the project's main directory is.

If I try to open a project subdir directly in VSCode, or `cd` to a project subdir and open Neovim, neither of them even try to connect to the server, which is correct.

**Comment by A-Lamia** [comment]
@permelin Sure, I'm just saying that is how it designed currently, so what you are saying we should do is always initialize in the root directory ?

**Comment by permelin** [comment]
1. Only open your client in the project directory.
2. If your client is sending a `rootPath` or `rootUri` which is not the main project directory simply because you edit a file in a subdir then the client is configured wrong.

`root_uri` is replaced by `res://`, which means the directory where `project.godot` is. If `root_uri` is some other directory and that is replaced by `res://`, Godot won't be able to find anything.

**Comment by A-Lamia** [comment]
Thats strange if i open a subdirectory in my project the rootPath and rootUri is a path to that sub directory but everything still works.

**Comment by permelin** [comment]
> also are you saying your root_uri not workspace->root_uri is being replaced by res:// ?? if so what function is that overwrite happening ?

No, sorry, I wrote that wrong. I'm too tired and should go to bed. The only thing that matters for initialization is what was in `workspace->root_uri` to begin with. The only time any path from the client is used is when it's the same as what was already in `workspace->root_uri` anyway.

Which is why it doesn't work if the client opens a different project. The workspace is still initialized with the project that Godot was opened with, so `workspace->root_uri` doesn't match any script paths from the client and isn't replaced with `res://` and nothing works.

**Comment by A-Lamia** [comment]
@permelin all good im tired as well haha, I'll look in to it more and see what some of these other functions do.

**Comment by permelin** [comment]
I'm an idiot. It was never supported to connect a client with a different project. I made assumptions instead of reading the code.

So this PR looks good and it works as intended for me.

I'm really sorry for all the noise.

**Comment by akien-mga** [comment]
Thanks!

**Comment by A-Lamia** [comment]
@permelin all good :D
