### PR TITLE
[MP] Allow multiple synchronizers per node.

### LINKED ISSUE #64599: Channging authority of MultiplayerSynchronizers that control spawned nodes does not work.
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10, Vulkan

### Issue description

The character controlled on the server syncs to the clients just fine, but synchronizers with multiplayer_authority properties set to anything other than 1 seem to stop working.

### Steps to reproduce

multiplayer_peer.peer_connected.connect(
		func(id):
			await get_tree().create_timer(2).timeout
			add_player_character(id)
	)

func add_player_character(id=1):
	var character = preload("res://player_character/player_character.tscn").instantiate()
	character.name = str(id)
	add_child(character)

##In player character script:

@onready var multiplayer_synchronizer = $MultiplayerSynchronizer
func _ready():
	multiplayer_synchronizer.set_multiplayer_authority(str(name).to_int())

image

image

### Minimal reproduction project

[Mulitplayer Nodes.zip](https://github.com/godotengine/godot/files/9378818/Mulitplayer.Nodes.zip)

### PR DESCRIPTION
**Pull request by Faless**
The same node can now be controlled by multiple synchronizers at once. Spawn visibility is composed in OR across multiple synchronizers (i.e. if any synchronizer is visible to the peer, the object will be spawned).

Synchronizers controlling spawned nodes can now have a different authority then the one spawning the node, in that case, the spawn variables for that specific synchronizer are simply ignored (other synchronizers with the same authority of the spawner will correctly synchronize variables on spawn).

The SceneReplicationState class has been completly removed, since it was bloating the implementation, the state is now simply stored in the SceneReplicationInterface.

Closes https://github.com/godotengine/godot/pull/66036 (superseded)
Fixes https://github.com/godotengine/godot/issues/64599.

### CODE REVIEW

File: modules/multiplayer/scene_replication_interface.h [hunk 1]
```diff
@@ -33,33 +33,77 @@
 
 #include "scene/main/multiplayer_api.h"
 
-#include "scene_replication_state.h"
+#include "modules/multiplayer/multiplayer_spawner.h"
+#include "modules/multiplayer/multiplayer_synchronizer.h"
```
Comment (akien-mga) [inline modules/multiplayer/scene_replication_interface.h:37]: Use relative includes for module headers so it doesn't break if the module is renamed / used from out of source via `custom.py`/`custom_modules` SCons option.

**Review by akien-mga — APPROVED** [review]
