### PR TITLE
Fix missing script time for some functions in profiler

### LINKED ISSUE #23715: Time spent waiting for servers not included in functions profiler (e.g. physics)
**Godot version:**
3.1 alpha c025f526c

**OS/device including version:**
Windows 10

**Issue description:**
When script call spends bulk of the time waiting for a game server, it is not included in the profiler. This makes finding function/nodes that abuse servers difficult to pinpoint and fix.

Specific use case: One of components of the game was doing excessive raycasts queries that could bump up the "Idle time" up to >0.1s, dropping FPS down to 10. This was in no way visible it the profiler. Had to resort to bisecting the nodes with inspector to find the problem.

**Steps to reproduce:**
Write a gdscript that interacts a lot with one of game servers (ie. raycasts with `direct_space_state`). Run and observe that time spent on raycasts is not included in the profiler output for scripts.

**Misc:**
I would suggest renaming *Idle time* to *Waiting time* in debugger. This is how profilers usually show time spent on waiting for other subsystems.

### LINKED ISSUE #29049: Profiler sometimes properly count time but sometimes not
**Godot version:**
3.2.dev.custom_build. af731f8

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I check profiler, I got sometimes not properly time(Look at the Script Functions)
Zrzut ekranu z 2019-05-20 22-53-30
or this
Zrzut ekranu z 2019-05-20 22-52-56

this happens not all the time, here are correct time
Zrzut ekranu z 2019-05-20 22-52-48

### LINKED ISSUE #40251: Profiler missing most of my functions.
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10
Version 1903
Build 18362.900

**Issue description:**
The profiler fails to detect a large portion of my functions and shows a suspiciously low Script Function time.
Using `Measure: Frame Time (sec)` and `Time: Inclusive`.

Here's a screenshot of the profiler on one of the spikes I'm investigating:
borked_profile2

It states that the frame takes 34ms in Idle time, but the Script Function total is only 0.19ms!

Further more, the time for Script Function seemingly drops when the load spike occurs. (Pink: Idle, Yellow: Script)
borked_profile3

The spike occurs at the start of a turn in my game. It's spread out since each enemy character's turn takes at least one frame, ends its turn and then moves on to next until its the players turn. All of this is triggered by signals and some use of `yield(get_tree(), "idle_frame")`

I've checked and doubled checked, by using `OS.get_ticks_usec()` and `Engine.get_idle_frames()`, that one of the missing functions actually runs during these frames and is a time hog, but it won't show up in the profiler (and I double checked the neighboring frames too)!

In fact most of the functions that I'd expect to show in the profiler for that frame are missing.

I managed to optimize the function, so I'm convinced its my own code and not any server or file loading that occurs during these frames.

I've tried twiddling the Max Functions setting, but no change. Made a grep for func definitions and only got ~750, so it seems hardly an issue with the default setting of 16k, but I've tried 32k and 64k to make sure.

The drop in Script Function time as the load increases suggests to me that there's some silent overflow besides the Max Function setting.

**Steps to reproduce:**
Unfortunately I've failed to pinpoint what causes it. Hope this report is informative enough anyway! I'll make another attempt at reproducing it at a small scale.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by reach-satori**
This PR adds the (toggleable in settings) ability to profile non-gdscript functions , and makes it so the time spent in them no longer disappears

Since it's a pretty big pr and touches a lot of code, I'll briefly explain what the problem was and how I solved it:

Essentially, the script profile information is saved only in GDScriptFunction. But when something that's not a GDScriptFunction is called from there, the code assumed it would profile normally anyway and subtracted the time spent in it to get a self-time, and this wrong information caused the bug. 

I've added an additional hashmap attribute  to GDScriptFunction::Profile that instead saves the information on any function directly under it in the stack that has no capability to profile itself. In profiling_get_frame_data these sub-profiles then get converted to normal profile frames and sent off as usual.

The changes in ScriptLanguage and GDScriptLanguage are just to get the information on whether profiling is enabled or not from the settings to the VM, following the same mold of the profiler enabling/disabling. I thought this was necessary because collecting more information naturally slows down the execution during profiling.

pr_img

Fixes #23715, fixes #40251, fixes #29049

### CODE REVIEW

**Comment by vnen** [comment]
Overall looks okay but I do have some nitpicks.

The major one is calling this "builtins" which I think isn't clear. In general they are called "native". I would prefer to use `profiler_include_native_calls` than `profiler_include_builtins` as the editor setting name for instance.

File: modules/gdscript/gdscript_vm.cpp [hunk 1]
```diff
@@ -1666,7 +1680,13 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
 					base->callp(*methodname, (const Variant **)argptrs, argc, ret, err);
 				}
 #ifdef DEBUG_ENABLED
-				if (GDScriptLanguage::get_singleton()->profiling) {
+				// In some cases, non-verified builtin functions end up in OPCODE_CALL.
+				// When that happens, base_class is empty, so we can use this to stop
+				// the time from being subtracted in that case
+				//
```
Comment (vnen) [inline modules/gdscript/gdscript_vm.cpp:1686]: I don't see why this would be the case. They should still have a base Object which will always have a class name (unless they are freed or it's `null`). The only exception are calls on built-in types (Vector2, String, etc.) which don't have a base Object.

Comment (reach-satori) [reply modules/gdscript/gdscript_vm.cpp:1686]: You're right, I just completely missed it. Then, what's a good way to distinguish the two at that point? Would the base Object's get_script work? Native calls shouldn't have scripts attached to them, right?

Other than that I can only think of changing the compiler and opcodes, which seems inadvisable.

Comment (reach-satori) [reply modules/gdscript/gdscript_vm.cpp]: You're right, that was my mistake. I can't figure out a nice way to distinguish native from user GDScript  code at this point in the VM without bigger changes. After thinking about it for a while and testing some things, the best I could find was:
```cpp
if (!base_obj || !base_obj->get_script_instance() || !base_obj->get_script_instance()->has_method(*methodname))
```
 But I don't know, there seem to be a ton of potential corner cases. Can you think of a scenario where this would fail? Or a decent alternative?  I'll spend some more time testing this more thoroughly regardless.

**Comment by reach-satori** [comment]
As per @vnen's comment, there seems to be no clean way to do this properly without bigger changes that would probably require a proposal first (and/or would be over my head by quite a bit atm), but I think I managed to get some of the way there using ClassDB. As it is, according to my testing, this works as intended with straightforward native calls from GDScript, but fails in a few important cases.

Those cases are: call_deferred(), call(), and new(), because I couldn't find a way to find out if what they're calling ends up in native code or GDScript code. So I've left them unchanged and they'll miss time, same as the current profiler does for all native functions.
There might be others of the same kind I'm missing, or other cases where this approach fails that I couldn't find or think of.

In case someone eventually wants to look into it, here's also the small testing project I was using. It's essentially just a loop that calls one from a selection of function configurations, with a menu, so you can look at the profiler behaviour.
[prof_proj.zip](https://github.com/godotengine/godot/files/11296945/prof_proj.zip)

Although, if it seems like nothing useful can come of this, feel free to close this PR.

File: editor/debugger/editor_profiler.cpp [hunk 2]
```diff
@@ -351,6 +352,10 @@ void EditorProfiler::_update_frame() {
 		for (int j = m.categories[i].items.size() - 1; j >= 0; j--) {
 			const Metric::Category::Item &it = m.categories[i].items[j];
 
+			bool internal_func = (it.internal == it.total);
+			if (internal_func && m.categories[i].name == "Script Functions" && !display_internal_profiles->is_pressed()) {
```
Comment (AThousandShips) [inline editor/debugger/editor_profiler.cpp:356]:
```suggestion
			if (internal_func && !display_internal_profiles->is_pressed() && m.categories[i].name == "Script Functions") {
```
I'd move the more expensive check later

File: modules/gdscript/gdscript.cpp [hunk 3]
```diff
@@ -2190,24 +2215,69 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
 		}
 		elem = elem->next();
 	}
 #endif
 
 	return current;
 }
+void GDScriptLanguage::profiling_collate_native_call_data(bool accumulated) {
+#ifdef DEBUG_ENABLED
+	// The same native call can be called from multiple functions, so join them together here
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2255]:
```suggestion
	// The same native call can be called from multiple functions, so join them together here.
```
[Comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide) nitpick

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -2190,24 +2215,69 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
+	// Only use the name of the function (ie signature.split[2])
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2256]:
```suggestion
	// Only use the name of the function (ie signature.split[2]).
```

File: modules/mono/csharp_script.h [hunk 5]
```diff
@@ -465,6 +465,7 @@ class CSharpLanguage : public ScriptLanguage {
 	/* PROFILING FUNCTIONS */
 	/* TODO */ void profiling_start() override {}
 	/* TODO */ void profiling_stop() override {}
+	/* TODO */ void profiling_set_save_native_calls(bool opt) override{};
```
Comment (AThousandShips) [inline modules/mono/csharp_script.h:468]:
```suggestion
	/* TODO */ void profiling_set_save_native_calls(bool opt) override {}
```

File: editor/debugger/editor_profiler.cpp [hunk 6]
```diff
@@ -351,6 +352,10 @@ void EditorProfiler::_update_frame() {
 		for (int j = m.categories[i].items.size() - 1; j >= 0; j--) {
 			const Metric::Category::Item &it = m.categories[i].items[j];
 
+			bool internal_func = (it.internal == it.total);
```
Comment (AThousandShips) [inline editor/debugger/editor_profiler.cpp:355]: Short enough that it isn't worth separating it IMO, as it's used only once

File: modules/gdscript/gdscript.cpp [hunk 7]
```diff
@@ -2146,13 +2146,22 @@ void GDScriptLanguage::profiling_start() {
...
 		elem = elem->next();
 	}
 
 	profiling = true;
 #endif
 }
 
+void GDScriptLanguage::profiling_set_save_native_calls(bool opt) {
+#ifdef DEBUG_ENABLED
+	MutexLock lock(this->mutex);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2160]:
```suggestion
	MutexLock lock(mutex);
```
Unless this name is somehow ambiguous

**Comment by AThousandShips** [comment]
You will also need to rebase for CI

File: core/object/script_language.h [hunk 8]
```diff
@@ -431,10 +431,12 @@ class ScriptLanguage : public Object {
 		uint64_t call_count;
 		uint64_t total_time;
 		uint64_t self_time;
+		uint64_t internal_time;
 	};
 
 	virtual void profiling_start() = 0;
 	virtual void profiling_stop() = 0;
+	virtual void profiling_set_save_native_calls(bool opt) = 0;
```
Comment (AThousandShips) [inline core/object/script_language.h:439]:
```suggestion
	virtual void profiling_set_save_native_calls(bool p_opt) = 0;
```
Arguments are prefixed with `p_`

File: modules/gdscript/gdscript.cpp [hunk 9]
```diff
@@ -2146,13 +2146,22 @@ void GDScriptLanguage::profiling_start() {
...
 	}
 
 	profiling = true;
 #endif
 }
 
+void GDScriptLanguage::profiling_set_save_native_calls(bool opt) {
+#ifdef DEBUG_ENABLED
+	MutexLock lock(mutex);
+	profile_native_calls = opt;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2161]:
```suggestion
	profile_native_calls = p_opt;
```

File: modules/gdscript/gdscript.cpp [hunk 10]
```diff
@@ -2190,24 +2215,69 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
+			}
+			p_info_arr[last_non_internal].internal_time = nat_time;
 		}
 		elem = elem->next();
 	}
 #endif
 
 	return current;
 }
+void GDScriptLanguage::profiling_collate_native_call_data(bool accumulated) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2253]:
```suggestion

void GDScriptLanguage::profiling_collate_native_call_data(bool p_accumulated) {
```

File: modules/gdscript/gdscript.cpp [hunk 11]
```diff
@@ -2190,24 +2215,69 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
+#ifdef DEBUG_ENABLED
+	// The same native call can be called from multiple functions, so join them together here.
+	// Only use the name of the function (ie signature.split[2]).
+	HashMap<String, GDScriptFunction::Profile::NativeProfile *> seen_nat_calls;
+	SelfList<GDScriptFunction> *elem = function_list.first();
+	while (elem) {
+		HashMap<String, GDScriptFunction::Profile::NativeProfile> *nat_calls;
+		HashMap<String, GDScriptFunction::Profile::NativeProfile>::Iterator it;
+		nat_calls = accumulated ? &elem->self()->profile.native_calls : &elem->self()->profile.last_native_calls;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2262]:
```suggestion
		nat_calls = p_accumulated ? &elem->self()->profile.native_calls : &elem->self()->profile.last_native_calls;
```

File: modules/gdscript/gdscript.h [hunk 12]
```diff
@@ -540,6 +541,8 @@ class GDScriptLanguage : public ScriptLanguage {
 
 	virtual void profiling_start() override;
 	virtual void profiling_stop() override;
+	virtual void profiling_set_save_native_calls(bool opt) override;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.h:544]:
```suggestion
	virtual void profiling_set_save_native_calls(bool p_opt) override;
```

File: modules/gdscript/gdscript.h [hunk 13]
```diff
@@ -540,6 +541,8 @@ class GDScriptLanguage : public ScriptLanguage {
...
+	void profiling_collate_native_call_data(bool accumulated);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.h:545]:
```suggestion
	void profiling_collate_native_call_data(bool p_accumulated);
```

File: modules/gdscript/gdscript_function.h [hunk 14]
```diff
@@ -612,6 +619,7 @@ class GDScriptFunction {
 	Variant call(GDScriptInstance *p_instance, const Variant **p_args, int p_argcount, Callable::CallError &r_err, CallState *p_state = nullptr);
 
 #ifdef DEBUG_ENABLED
+	void _profile_native_call(uint64_t t_taken, String function_name, String instance_class_name);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_function.h:622]:
```suggestion
	void _profile_native_call(uint64_t p_t_taken, String p_function_name, String p_instance_class_name = String());
```
Default argument is defined here

File: modules/gdscript/gdscript_vm.cpp [hunk 15]
```diff
@@ -36,6 +36,28 @@
...
+	if (gdscript.is_valid()) {
+		return gdscript->get_script_class_name();
+	} else if (p_script->get_name().is_empty()) {
+		return p_script->get_path().get_file();
+	} else {
+		return p_script->get_name();
+	}
+}
+
+static bool _profile_count_as_native(const Object *base_obj, const StringName methodname) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:50]:
```suggestion
static bool _profile_count_as_native(const Object *p_base_obj, const StringName &p_methodname) {
```

File: modules/gdscript/gdscript_vm.cpp [hunk 16]
```diff
@@ -36,6 +36,28 @@
...
+	if (!base_obj) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:51]:
```suggestion
	if (!p_base_obj) {
```

File: modules/gdscript/gdscript_vm.cpp [hunk 17]
```diff
@@ -36,6 +36,28 @@
...
+		return false;
+	}
+	StringName cname = base_obj->get_class_name();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:54]:
```suggestion
	StringName cname = p_base_obj->get_class_name();
```

File: modules/gdscript/gdscript_vm.cpp [hunk 18]
```diff
@@ -36,6 +36,28 @@
...
+	if ((methodname == "new" && cname == "GDScript") || methodname == "call") {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:55]:
```suggestion
	if ((p_methodname == "new" && cname == "GDScript") || p_methodname == "call") {
```

File: modules/gdscript/gdscript_vm.cpp [hunk 19]
```diff
@@ -36,6 +36,28 @@
...
+		return false;
+	}
+	return ClassDB::class_exists(cname) && ClassDB::has_method(cname, methodname, false);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:58]:
```suggestion
	return ClassDB::class_exists(cname) && ClassDB::has_method(cname, p_methodname, false);
```

File: modules/gdscript/gdscript_vm.cpp [hunk 20]
```diff
@@ -84,6 +106,21 @@ static String _get_var_type(const Variant *p_var) {
 
 	return basestr;
 }
+
+void GDScriptFunction::_profile_native_call(uint64_t t_taken, String func_name, String instance_class_name = "") {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:110]:
```suggestion
void GDScriptFunction::_profile_native_call(uint64_t p_t_taken, String p_func_name, String p_instance_class_name) {
```
Default arguments are not defined in the source but the header

File: modules/gdscript/gdscript_vm.cpp [hunk 21]
```diff
@@ -84,6 +106,21 @@ static String _get_var_type(const Variant *p_var) {
...
+	HashMap<String, Profile::NativeProfile>::Iterator inner_prof = profile.native_calls.find(func_name);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:111]:
```suggestion
	HashMap<String, Profile::NativeProfile>::Iterator inner_prof = profile.native_calls.find(p_func_name);
```

File: modules/gdscript/gdscript_vm.cpp [hunk 22]
```diff
@@ -84,6 +106,21 @@ static String _get_var_type(const Variant *p_var) {
...
+	if (inner_prof) {
+		inner_prof->value.call_count += 1;
+	} else {
+		if (!instance_class_name.is_empty()) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:115]:
```suggestion
		if (!p_instance_class_name.is_empty()) {
```

File: modules/gdscript/gdscript_vm.cpp [hunk 23]
```diff
@@ -84,6 +106,21 @@ static String _get_var_type(const Variant *p_var) {
...
+			instance_class_name += ".";
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:116]:
```suggestion
			p_instance_class_name += ".";
```

File: modules/gdscript/gdscript_vm.cpp [hunk 24]
```diff
@@ -84,6 +106,21 @@ static String _get_var_type(const Variant *p_var) {
...
+		}
+		String sig = vformat("%s::0::%s%s", get_script()->get_script_path(), instance_class_name, func_name);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:118]:
```suggestion
		String sig = vformat("%s::0::%s%s", get_script()->get_script_path(), p_instance_class_name, p_func_name);
```

File: modules/gdscript/gdscript_vm.cpp [hunk 25]
```diff
@@ -84,6 +106,21 @@ static String _get_var_type(const Variant *p_var) {
...
+		inner_prof = profile.native_calls.insert(func_name, Profile::NativeProfile{ 1, 0, sig });
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:119]:
```suggestion
		inner_prof = profile.native_calls.insert(p_func_name, Profile::NativeProfile{ 1, 0, sig });
```

File: modules/gdscript/gdscript_vm.cpp [hunk 26]
```diff
@@ -84,6 +106,21 @@ static String _get_var_type(const Variant *p_var) {
...
+	}
+	inner_prof->value.total_time += t_taken;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:121]:
```suggestion
	inner_prof->value.total_time += p_t_taken;
```

File: modules/mono/csharp_script.h [hunk 27]
```diff
@@ -465,6 +465,7 @@ class CSharpLanguage : public ScriptLanguage {
 	/* PROFILING FUNCTIONS */
 	/* TODO */ void profiling_start() override {}
 	/* TODO */ void profiling_stop() override {}
+	/* TODO */ void profiling_set_save_native_calls(bool opt) override {}
```
Comment (AThousandShips) [inline modules/mono/csharp_script.h:468]:
```suggestion
	/* TODO */ void profiling_set_save_native_calls(bool p_opt) override {}
```

File: modules/gdscript/gdscript_vm.cpp [hunk 28]
```diff
@@ -36,6 +36,28 @@
 #include "core/os/os.h"
 
 #ifdef DEBUG_ENABLED
+static String _get_script_name(const Ref<Script> p_script) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:39]: Unused, should be removed

File: editor/debugger/editor_profiler.cpp [hunk 29]
```diff
@@ -362,6 +366,9 @@ void EditorProfiler::_update_frame() {
 			item->set_tooltip_text(0, it.name + "\n" + it.script + ":" + itos(it.line));
 
 			float time = dtime == DISPLAY_SELF_TIME ? it.self : it.total;
+			if (!display_internal_profiles->is_pressed() && dtime == DISPLAY_SELF_TIME) {
```
Comment (AThousandShips) [inline editor/debugger/editor_profiler.cpp:369]:
```suggestion
			if (dtime == DISPLAY_SELF_TIME && !display_internal_profiles->is_pressed()) {
```
Put cheaper condition first

File: editor/debugger/editor_profiler.cpp [hunk 30]
```diff
@@ -685,6 +701,9 @@ EditorProfiler::EditorProfiler() {
 	int metric_size = CLAMP(int(EDITOR_GET("debugger/profiler_frame_history_size")), 60, 10000);
 	frame_metrics.resize(metric_size);
 
+	EDITOR_DEF("debugger/profiler_frame_max_functions", 64);
+	EDITOR_DEF("debugger/profile_native_calls", false);
```
Comment (AThousandShips) [inline editor/debugger/editor_profiler.cpp:705]: These should be defined in one place, in `editor_settings.cpp`

File: modules/gdscript/gdscript.cpp [hunk 31]
```diff
@@ -2167,17 +2176,33 @@ int GDScriptLanguage::profiling_get_accumulated_data(ProfilingInfo *p_info_arr,
...
 		p_info_arr[current].self_time = elem->self()->profile.self_time.get();
 		p_info_arr[current].total_time = elem->self()->profile.total_time.get();
 		p_info_arr[current].signature = elem->self()->profile.signature;
-		elem = elem->next();
 		current++;
+
+		int nat_time = 0;
+		HashMap<String, GDScriptFunction::Profile::NativeProfile>::ConstIterator nat_calls;
+		nat_calls = elem->self()->profile.native_calls.begin();
+		while (nat_calls != elem->self()->profile.native_calls.end()) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2195]:
```suggestion
		while (nat_calls) {
```
It has a boolean check, so this is simpler, the end iterator is just `Iterator(nullptr)`

File: modules/gdscript/gdscript.cpp [hunk 32]
```diff
@@ -2190,24 +2215,69 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
 			p_info_arr[current].call_count = elem->self()->profile.last_frame_call_count;
 			p_info_arr[current].self_time = elem->self()->profile.last_frame_self_time;
 			p_info_arr[current].total_time = elem->self()->profile.last_frame_total_time;
 			p_info_arr[current].signature = elem->self()->profile.signature;
 			current++;
+
+			int nat_time = 0;
+			HashMap<String, GDScriptFunction::Profile::NativeProfile>::ConstIterator nat_calls;
+			nat_calls = elem->self()->profile.last_native_calls.begin();
+			while (nat_calls != elem->self()->profile.last_native_calls.end()) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2235]:
```suggestion
			while (nat_calls) {
```

File: modules/gdscript/gdscript.cpp [hunk 33]
```diff
@@ -2190,24 +2215,69 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
+	while (elem) {
+		HashMap<String, GDScriptFunction::Profile::NativeProfile> *nat_calls;
+		HashMap<String, GDScriptFunction::Profile::NativeProfile>::Iterator it;
+		nat_calls = accumulated ? &elem->self()->profile.native_calls : &elem->self()->profile.last_native_calls;
+
+		it = nat_calls->begin();
+		while (it != nat_calls->end()) {
+			Vector<String> sig = it->value.signature.split("::");
+			HashMap<String, GDScriptFunction::Profile::NativeProfile *>::ConstIterator already_found = seen_nat_calls.find(sig[2]);
+			if (already_found != seen_nat_calls.end()) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2268]:
```suggestion
			if (already_found) {
```

File: editor/debugger/editor_profiler.cpp [hunk 34]
```diff
@@ -351,6 +352,9 @@ void EditorProfiler::_update_frame() {
 		for (int j = m.categories[i].items.size() - 1; j >= 0; j--) {
 			const Metric::Category::Item &it = m.categories[i].items[j];
 
+			if ((it.internal == it.total) && !display_internal_profiles->is_pressed() && m.categories[i].name == "Script Functions") {
```
Comment (AThousandShips) [inline editor/debugger/editor_profiler.cpp:355]:
```suggestion
			if (it.internal == it.total && !display_internal_profiles->is_pressed() && m.categories[i].name == "Script Functions") {
```
Or put parentheses around all, uniformity

**Comment by YuriSizov** [comment]
Please don't merge `master into your feature branch. Prefer rebasing, so your PR only contains changes relevant to your work and nothing else.

See [this documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase), if you need help with rebasing.

**Comment by adamscott** [comment]
Hi @reach-satori! Thanks for your first PR.
It seems that you still have problems with your merge, as it shows still 3,313 files changed.

Don't hesitate to join our [developer chat](https://chat.godotengine.org/)! We could help you with git and your PR.

**Comment by adamscott** [comment]
Happy to see that you resolved your issue! 
And the invitation to join our [developer chat](https://chat.godotengine.org/) still stands!

**Review by adamscott — APPROVED** [review]
Reviewed in today's GDScript meeting. This PR seems fine, we don't see how else the job could be done. It would be better to improve the code based on this PR than not.

Thank you for your PR!

File: modules/gdscript/gdscript_vm.cpp [hunk 35]
```diff
@@ -84,6 +96,21 @@ static String _get_var_type(const Variant *p_var) {
 
 	return basestr;
 }
+
+void GDScriptFunction::_profile_native_call(uint64_t p_t_taken, String p_func_name, String p_instance_class_name) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_vm.cpp:100]:
```suggestion
void GDScriptFunction::_profile_native_call(uint64_t p_t_taken, const String &p_func_name, const String &p_instance_class_name) {
```
Missed here when applying suggestions

File: modules/gdscript/gdscript.cpp [hunk 36]
```diff
@@ -2283,6 +2325,35 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
 }
 
+void GDScriptLanguage::profiling_collate_native_call_data(bool p_accumulated) {
+#ifdef DEBUG_ENABLED
+	// The same native call can be called from multiple functions, so join them together here.
+	// Only use the name of the function (ie signature.split[2]).
+	HashMap<String, GDScriptFunction::Profile::NativeProfile *> seen_nat_calls;
+	SelfList<GDScriptFunction> *elem = function_list.first();
+	while (elem) {
+		HashMap<String, GDScriptFunction::Profile::NativeProfile> *nat_calls;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2335]:
```suggestion
		HashMap<String, GDScriptFunction::Profile::NativeProfile> *nat_calls = nullptr;
```
Always initialize variables

**Review by AThousandShips — APPROVED** [review]
Looks good otherwise!

File: modules/gdscript/gdscript_function.h [hunk 37]
```diff
@@ -474,6 +474,13 @@ class GDScriptFunction {
 		uint64_t last_frame_call_count = 0;
 		uint64_t last_frame_self_time = 0;
 		uint64_t last_frame_total_time = 0;
+		typedef struct NativeProfile {
+			uint64_t call_count;
+			uint64_t total_time;
+			String signature;
+		} NativeProfile;
+		HashMap<String, NativeProfile> native_calls{};
+		HashMap<String, NativeProfile> last_native_calls{};
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_function.h:483]:
```suggestion
		HashMap<String, NativeProfile> native_calls;
		HashMap<String, NativeProfile> last_native_calls;
```
Unnecessary initialization

File: modules/gdscript/gdscript.cpp [hunk 38]
```diff
@@ -2283,6 +2325,35 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
+		HashMap<String, GDScriptFunction::Profile::NativeProfile>::Iterator it;
+		nat_calls = p_accumulated ? &elem->self()->profile.native_calls : &elem->self()->profile.last_native_calls;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2337]:
```suggestion
		HashMap<String, GDScriptFunction::Profile::NativeProfile>::Iterator it;
		HashMap<String, GDScriptFunction::Profile::NativeProfile> *nat_calls = p_accumulated ? &elem->self()->profile.native_calls : &elem->self()->profile.last_native_calls;
```
Alternatively for the same

File: modules/gdscript/gdscript.cpp [hunk 39]
```diff
@@ -2241,17 +2250,33 @@ int GDScriptLanguage::profiling_get_accumulated_data(ProfilingInfo *p_info_arr,
...
 		p_info_arr[current].call_count = elem->self()->profile.call_count.get();
 		p_info_arr[current].self_time = elem->self()->profile.self_time.get();
 		p_info_arr[current].total_time = elem->self()->profile.total_time.get();
 		p_info_arr[current].signature = elem->self()->profile.signature;
-		elem = elem->next();
 		current++;
+
+		int nat_time = 0;
+		HashMap<String, GDScriptFunction::Profile::NativeProfile>::ConstIterator nat_calls;
+		nat_calls = elem->self()->profile.native_calls.begin();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2268]:
```suggestion
		HashMap<String, GDScriptFunction::Profile::NativeProfile>::ConstIterator nat_calls = elem->self()->profile.native_calls.begin();
```
I'd suggest initializing at once, even if it means long lines

File: modules/gdscript/gdscript.cpp [hunk 40]
```diff
@@ -2264,17 +2289,34 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
+			int last_non_internal = current;
 			p_info_arr[current].call_count = elem->self()->profile.last_frame_call_count;
 			p_info_arr[current].self_time = elem->self()->profile.last_frame_self_time;
 			p_info_arr[current].total_time = elem->self()->profile.last_frame_total_time;
 			p_info_arr[current].signature = elem->self()->profile.signature;
 			current++;
+
+			int nat_time = 0;
+			HashMap<String, GDScriptFunction::Profile::NativeProfile>::ConstIterator nat_calls;
+			nat_calls = elem->self()->profile.last_native_calls.begin();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2308]:
```suggestion
			HashMap<String, GDScriptFunction::Profile::NativeProfile>::ConstIterator nat_calls = elem->self()->profile.last_native_calls.begin();
```

File: modules/gdscript/gdscript.cpp [hunk 41]
```diff
@@ -2283,6 +2325,35 @@ int GDScriptLanguage::profiling_get_frame_data(ProfilingInfo *p_info_arr, int p_
...
+	// The same native call can be called from multiple functions, so join them together here.
+	// Only use the name of the function (ie signature.split[2]).
+	HashMap<String, GDScriptFunction::Profile::NativeProfile *> seen_nat_calls;
+	SelfList<GDScriptFunction> *elem = function_list.first();
+	while (elem) {
+		HashMap<String, GDScriptFunction::Profile::NativeProfile> *nat_calls;
+		HashMap<String, GDScriptFunction::Profile::NativeProfile>::Iterator it;
+		nat_calls = p_accumulated ? &elem->self()->profile.native_calls : &elem->self()->profile.last_native_calls;
+
+		it = nat_calls->begin();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:2339]:
```suggestion
		HashMap<String, GDScriptFunction::Profile::NativeProfile> *nat_calls = p_accumulated ? &elem->self()->profile.native_calls : &elem->self()->profile.last_native_calls;
		HashMap<String, GDScriptFunction::Profile::NativeProfile>::Iterator it = nat_calls->begin();

```
Clearer IMO

File: core/object/script_language.h [hunk 42]
```diff
@@ -384,10 +384,12 @@ class ScriptLanguage : public Object {
 		uint64_t call_count;
 		uint64_t total_time;
 		uint64_t self_time;
+		uint64_t internal_time;
 	};
 
 	virtual void profiling_start() = 0;
 	virtual void profiling_stop() = 0;
+	virtual void profiling_set_save_native_calls(bool p_opt) = 0;
```
Comment (Faless) [inline core/object/script_language.h:392]:
```suggestion
	virtual void profiling_set_save_native_calls(bool p_enable) = 0;
```

File: core/object/script_language_extension.cpp [hunk 43]
```diff
@@ -145,6 +145,7 @@ void ScriptLanguageExtension::_bind_methods() {
 
 	GDVIRTUAL_BIND(_profiling_start);
 	GDVIRTUAL_BIND(_profiling_stop);
+	GDVIRTUAL_BIND(_profiling_set_save_native_calls, "opt");
```
Comment (Faless) [inline core/object/script_language_extension.cpp:148]:
```suggestion
	GDVIRTUAL_BIND(_profiling_set_save_native_calls, "enable");
```

File: doc/classes/ScriptLanguageExtension.xml [hunk 44]
```diff
@@ -276,6 +276,12 @@
 			<description>
 			</description>
 		</method>
+		<method name="_profiling_set_save_native_calls" qualifiers="virtual">
+			<return type="void" />
+			<param index="0" name="opt" type="bool" />
```
Comment (Faless) [inline doc/classes/ScriptLanguageExtension.xml:281]:
```suggestion
			<param index="0" name="enable" type="bool" />
```

File: modules/gdscript/gdscript.cpp [hunk 45]
```diff
@@ -2220,13 +2220,22 @@ void GDScriptLanguage::profiling_start() {
...
+		elem->self()->profile.native_calls.clear();
+		elem->self()->profile.last_native_calls.clear();
 		elem = elem->next();
 	}
 
 	profiling = true;
 #endif
 }
 
+void GDScriptLanguage::profiling_set_save_native_calls(bool p_opt) {
```
Comment (Faless) [inline modules/gdscript/gdscript.cpp:2232]:
```suggestion
void GDScriptLanguage::profiling_set_save_native_calls(bool p_enable) {
```

File: modules/gdscript/gdscript.cpp [hunk 46]
```diff
@@ -2220,13 +2220,22 @@ void GDScriptLanguage::profiling_start() {
...
+#ifdef DEBUG_ENABLED
+	MutexLock lock(mutex);
+	profile_native_calls = p_opt;
```
Comment (Faless) [inline modules/gdscript/gdscript.cpp:2235]:
```suggestion
	profile_native_calls = p_enable;
```

File: modules/gdscript/gdscript.h [hunk 47]
```diff
@@ -590,6 +591,8 @@ class GDScriptLanguage : public ScriptLanguage {
 
 	virtual void profiling_start() override;
 	virtual void profiling_stop() override;
+	virtual void profiling_set_save_native_calls(bool p_opt) override;
```
Comment (Faless) [inline modules/gdscript/gdscript.h:594]:
```suggestion
	virtual void profiling_set_save_native_calls(bool p_enable) override;
```

File: modules/mono/csharp_script.h [hunk 48]
```diff
@@ -463,6 +463,7 @@ class CSharpLanguage : public ScriptLanguage {
 	/* PROFILING FUNCTIONS */
 	/* TODO */ void profiling_start() override {}
 	/* TODO */ void profiling_stop() override {}
+	/* TODO */ void profiling_set_save_native_calls(bool p_opt) override {}
```
Comment (Faless) [inline modules/mono/csharp_script.h:466]:
```suggestion
	/* TODO */ void profiling_set_save_native_calls(bool p_enable) override {}
```

**Review by Faless — APPROVED** [review]
Amazing work :trophy: !
I just have some nitpicks on the parameter name for `profiling_set_save_native_calls`, but it's looking great otherwise!

Thanks a lot for working on this! :blue_heart:

**Comment by YuriSizov** [comment]
Applied suggestions and rebased on your behalf.

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged Godot contribution!
