### PR TITLE
Use compatible text resource format when possible

### LINKED ISSUE #90846: Editor settings wiped out when going from latest 4.3.dev to older releases
### Tested versions

4.3[3b1806182a3564736ad64793b203c2c13c251f56]

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

I updated my 4.3 master branch yesterday (previous update was from couple days ago) and after opening the editor all my settings in Editor settings were wiped out.
Shortcuts, anything I had set up (external editor, blender path, everything), editor theme, nothing left the same.
Just to be clear, this project was created in 4.3 (I don't remember when) so it's not a conversion from 4.2 -> 4.3 and it was working just fine just in a couple days old master build.

### Steps to reproduce

1. Create a project in 4.3 master let's say from a week ago.
2. Change editor settings, add shortcuts, change the editor theme, ...
3. Open your project in the 4.3 master updated to 3b1806182a3564736ad64793b203c2c13c251f56.
4. See if the editor settings are still intact.

### Minimal reproduction project (MRP)

N/A - it doesn't seem to be specific to a project in particular, it's related to editor settings.

### PR DESCRIPTION
**Pull request by timothyqiu**
Use the new format only when saving a resource / scene containing a PackedByteArray with at least 64 elements.

This way, editor settings can be kept, and users can still open most scenes with previous versions of Godot.

This PR is a proof of concept of my suggestion on RocketChat.

*Bugsquad edit:* Fixes https://github.com/godotengine/godot/issues/90846

### CODE REVIEW

**Comment by timothyqiu** [comment]
> This makes TileMapLayer save in the old PackedByteArray format, which is wrong.

If you mean the change in `TileMapLayer.xml`, it's because only resource files are possible to use the new format. In this case, serializing XML still uses the old format indeed.

**Comment by KoBeWi** [comment]
No I mean I tested with a TileMapLayer in a scene. The whole format change was because of TileMapLayer.

**Comment by timothyqiu** [comment]
Ah, sorry I missed the recursion part when in VariantWriter. I'll get rid of the setup for TileSet and push again.

**Comment by timothyqiu** [comment]
It should work correctly now.

`prefer_compat_format()` is now `PackedScene` only.

File: scene/resources/resource_format_text.h [hunk 1]
```diff
@@ -54,6 +54,7 @@ class ResourceLoaderText {
 	};
 
 	bool is_scene = false;
+	int format_version;
```
Comment (KoBeWi) [inline scene/resources/resource_format_text.h:57]: Needs to be initialized to some value (especially when `format` field is optional).

File: scene/resources/packed_scene.cpp [hunk 2]
```diff
@@ -2112,6 +2112,24 @@ Ref<SceneState> PackedScene::get_state() const {
 	return state;
 }
 
+bool PackedScene::prefer_compat_format() const {
+	if (state.is_null()) {
+		return true;
+	}
+
+	StringName tile_map_name = "TileMap";
+	StringName tile_map_layer_name = "TileMapLayer";
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp:2121]:
```suggestion
	const StringName tile_map_name = "TileMap";
	const StringName tile_map_layer_name = "TileMapLayer";
```
Note that TileMap still saves as PackedIntArray (although it's unintended?), so it's not necessary here as of now.

File: scene/resources/packed_scene.cpp [hunk 3]
```diff
@@ -2112,6 +2112,24 @@ Ref<SceneState> PackedScene::get_state() const {
...
+
+	int count = state->get_node_count();
+	for (int i = 0; i < count; i++) {
+		const StringName &type = state->get_node_type(i);
+		if (type == tile_map_name || type == tile_map_layer_name) {
+			return false;
+		}
+	}
```
Comment (KoBeWi) [inline scene/resources/packed_scene.cpp:2129]: That's basically a hard-coded hack. Makes me think that this should be wrapped in `DISABLE_DEPRECATED` at least.

**Comment by KoBeWi** [comment]
This works correctly and even resolves Resources issue, making my PR irrelevant.

But it's hacky. And also it makes Base64 hard-coded only for TileMapLayer, which means nothing else can benefit from it. I think perfectly scenes/resources should always save under new format if they contain PackedByteArray.

File: scene/resources/packed_scene.cpp (hunk 3 above)
Comment (timothyqiu) [reply scene/resources/packed_scene.cpp:2129]: Hardcoding can be avoided by adding something like `prefer_compat_format()` to `Node`s. But currently only TileMapLayer needs to carry a large PackedByteArray regularly, so I think hardcoding is better than an invasive solution affecting the node API.

**Comment by timothyqiu** [comment]
It turns out `ResourceFormatSaverTextInstance::_find_resources()` goes through every value to be stored. It's a good place to check whether PackedByteArray is used.

Now the resource saver will use the new format if there's a PackedByteArray with at least 64 elements. The hard-coded TileMapLayer check is removed.

The downside is that the format version may change depending on what's inside the resource / scene. Maybe the array size limit is an overthinking, a non-empty check is enough.

**Comment by timothyqiu** [comment]
The main reason I added the size check is for potential custom nodes / resources that export PackedByteArray variables.

If the array only contains a few elements, using Base64 won't save much space and is not human readable. Seems not worth breaking compat for.

File: doc/classes/TileMapLayer.xml [hunk 4]
```diff
@@ -268,7 +268,7 @@
 			The quadrant size does not apply on a Y-sorted [TileMapLayer], as tiles are be grouped by Y position instead in that case.
 			[b]Note:[/b] As quadrants are created according to the map's coordinate system, the quadrant's "square shape" might not look like square in the [TileMapLayer]'s local coordinate system.
 		</member>
-		<member name="tile_map_data" type="PackedByteArray" setter="set_tile_map_data_from_array" getter="get_tile_map_data_as_array" default="PackedByteArray(&quot;AAA=&quot;)">
+		<member name="tile_map_data" type="PackedByteArray" setter="set_tile_map_data_from_array" getter="get_tile_map_data_as_array" default="PackedByteArray(0, 0)">
```
Comment (KoBeWi) [inline doc/classes/TileMapLayer.xml:271]: I wonder why does it write something at all if it's empty 🤔

File: scene/resources/resource_format_text.h (hunk 1 above)
Comment (KoBeWi) [reply scene/resources/resource_format_text.h:57]: I meant initialized here :P
Same with `use_compat`.

**Review by KoBeWi — APPROVED** [review]
It's still somewhat hacky, but at least it's no longer hard-coded to one class. It's a nice solution.

File: doc/classes/TileMapLayer.xml (hunk 4 above)
Comment (KoBeWi) [reply doc/classes/TileMapLayer.xml:271]: It could skip it when there are no tiles 🤔

**Review by akien-mga — APPROVED** [review]
That approach looks fine to me overall.

I discussed it with @reduz, and we agreed to merge this for now to address the immediate issue, and then:
- Backport support for parsing the new base64 PackedByteArray to 4.1.5 and 4.2.3 (but not saving - so keeping version format 3 there, but being able to parse version 4).
- Eventually consider reverting this compat handling once the currently supported stable versions no longer need it.

**Comment by akien-mga** [comment]
Thanks!
