### PR TITLE
Use `AHashMap` for `RBMap nodes` and `HashMap` `input_activity` (reverted)

### LINKED ISSUE #101494: Animation Performance Problems
### Tested versions

Tested 4.4 Dev 7

### System information

Windows 11, i3 10105f

### Issue description

I've noticed that Animation Tree and Animation Player seem to have a Ludicrously high cost

For Reference, in my game to have 60 FPS, I can have ~100 AI characters with active animation players and trees, but 3-4 times as many with them disabled.
Each of the AI's is dynamically typed GDScript, that isn't even all that optimized, gathering data of their environment and communicating with each other, moving around with Godot's physics and navigation calculations running in the background of all of that.

The GPU is not the limitation, given it's taking only a couple of milliseconds per frame to render and changing GPU taxing settings does nothing

### Steps to reproduce

Open MRP, Observe poor performance, go to the instance, and set process mode of the animation tree and player to disabled, Observe Massive Improvement

Note: The MRP went a bit extreme (some 2.4k instances) to tank the performance even harder for those more powerful systems out there (It's a slide show on mine in the editor with animations activated in the instances)

### Minimal reproduction project (MRP)

[Animation.zip](https://github.com/user-attachments/files/18397920/Animation.zip)

### PR DESCRIPTION
**Pull request by Nazarwadim**
Forgot to change in #92554

Gives 15% more FPS on MPR from #101494.

Helps with #101494

### CODE REVIEW

**Comment by Nazarwadim** [comment]
@akien-mga See this comment https://github.com/godotengine/godot/issues/101494#issuecomment-2590642323

In 4.3, for some reason, two animations are played due to the combination of `AnimationPlayer` and `AnimationMixer`. The first is empty from `AnimationPlayer`, which does nothing, but only takes resources, and the second is real from `AnimationTree`.

**Review by TokageItLab — APPROVED** [review]

File: scene/animation/animation_blend_tree.h [hunk 1]
```diff
@@ -410,7 +410,7 @@ class AnimationNodeBlendTree : public AnimationRootNode {
 		Vector<StringName> connections;
 	};
 
-	RBMap<StringName, Node, StringName::AlphCompare> nodes;
+	AHashMap<StringName, Node> nodes;
```
Comment (TokageItLab) [inline scene/animation/animation_blend_tree.h:413]:
```suggestion
	AHashMap<StringName, Node, StringName::AlphCompare> nodes;
```

**Review by TokageItLab — COMMENTED** [review]
~I am not familiar with AHashMap, but doesn't it change the sorting order as the hash seed is changed with each startup? If so, this argument is needed to avoid to change .tres.~ Resolved as AHashMap doesn't change index order.

File: scene/animation/animation_blend_tree.h (hunk 1 above)
Comment (akien-mga) [reply scene/animation/animation_blend_tree.h:413]: Could you check if this is indeed needed @Nazarwadim?

Comment (Nazarwadim) [reply scene/animation/animation_blend_tree.h:413]: @TokageItLab This should not affect the storage of .tres because AHashMap preserves the insertion order.

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Reverting with #102432 to fix #102374, but this is worth looking into again for 4.5 as the gains seemed to be substantial.

**Comment by eddieataberk** [comment]
> Reverting with #102432 to fix #102374, but this is worth looking into again for 4.5 as the gains seemed to be substantial.

https://github.com/godotengine/godot/pull/102376
This is pr closed but i highly recommend merging it. I've been using it in a very complex anim tree since yesterday with no issues.

**Comment by clayjohn** [comment]
@Nazarwadim Can you open a new PR with these changes combined with https://github.com/godotengine/godot/pull/102376 ?
