### PR TITLE
Fix infinite loop state check in `AnimationStateMachine`

### LINKED ISSUE #79012: Crash when setting AnimationTree active with circular dependency (infinite loop)
### Godot version

v4.1.rc2.official [46424488e]

### System information

Godot v4.1.rc2 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

When setting the AnimationTree to active, Godot crashes.

### Steps to reproduce

https://github.com/godotengine/godot/assets/46705245/dbe5eb81-1357-43e8-ac80-a4eb97eea9fc

### Minimal reproduction project

[Crash.zip](https://github.com/godotengine/godot/files/11945826/Crash.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #79012.

If only the first pass is stored and compared, the loop detection will fail if an infinite loop starts in the middle of the path. So, all transition paths must be stored and compared. Also, remove `is_state_changed = false` as it was actually wrong (state change occurs just before the try infinite loop).

### CODE REVIEW

**Comment by akien-mga** [comment]
How is the issue communicated to the user when such a potential infinite loop is detected? I see it breaks but doesn't raise an error (here at least, it maybe does further up the stack). Will users understand that their setup is non functional due to recursion?

**Comment by TokageItLab** [comment]
Perhaps the state continues to change every frame, but that is a normal transition and not an error.

Since a StateMachine cannot have a path to itself, if this check works, there is no longer an infinite loop in the true sense of the word.

**Comment by TokageItLab** [comment]
@akien-mga I've added a warning in case you're concerned.

image

File: scene/animation/animation_node_state_machine.cpp [hunk 1]
```diff
@@ -901,18 +901,20 @@ bool AnimationNodeStateMachinePlayback::_transition_to_next_recursive(AnimationT
 	bool is_state_changed = false;
 
 	NextInfo next;
-	StringName transition_start = current;
+	Vector<StringName> transition_path;
```
Comment (bruvzg) [inline scene/animation/animation_node_state_machine.cpp:904]: What's the usual number of elements in this vector? It looks like a use case for the hash map, but I guess it's quite small and won't benefit from `HashSet<StringName>` usage?

Comment (TokageItLab) [reply scene/animation/animation_node_state_machine.cpp:904]: Depending on the complexity of the StateMachine, but I guess the number of "transition path in one frame" should not exceed 10 at the most.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.
