### PR TITLE
UndoRedo: Fix `MERGE_ALL` commit from repeating actions

### LINKED ISSUE #26118: Possible bug with UndoRedo's MERGE_ALL mode
**Godot version:**
ced77db

**Issue description:**
It seems that there's a bug with `UndoRedo`'s `MERGE_ALL` mode, in that it repeats instructions if actions are committed fast enough. In the example bellow, if pressing "ui_accept" (enter or space) with long intervals, it works fine. Short ones will make "pressed" be printed twice.

```
var undo := UndoRedo.new()

func _input(event: InputEvent) -> void:
	if not event.is_action_pressed("ui_accept"):
		return
	
	undo.create_action("action", UndoRedo.MERGE_ALL)
	undo.add_do_method(self, "test")
	undo.commit_action()

func test() -> void:
	print("pressed")
```

### PR DESCRIPTION
**Pull request by TheSofox**
Fixes #26118

Committing an UNDO action will run the action. This is fine if it's set to not merge or only merge the ends, but with MERGE_ALL it meant that the action could be merged into previous actions, then the operations from ALL the merged actions would be run, instead of from the most recent action.

This pull request fixes this by keeping a record (merge_total) of the amount of operations that are in the current action that the new action is being merged into. Then, when the action is committed. This variable is used to skip over operations until we get to the ones that only the newest action added.

### CODE REVIEW

File: core/object/undo_redo.cpp [hunk 1]
```diff
@@ -71,7 +71,13 @@ bool UndoRedo::_redo(bool p_execute) {
 	}
 
 	current_action++;
-	_process_operation_list(actions.write[current_action].do_ops.front(), p_execute);
+	
+	List<Operation>::Element *start_doops_element = actions.write[current_action].do_ops.front();
+	while (merge_total-- > 0 && start_doops_element) {
```
Comment (AThousandShips) [inline core/object/undo_redo.cpp:76]: We prefer not having decrement or increment in a statement like this, it hurts readability, please separate it

Comment (TheSofox) [reply core/object/undo_redo.cpp]: Done

**Comment by TheSofox** [comment]
I've added Unit Tests that prove the bug has been fixed and test one or two other parts of `UndoRedo` for good measure.

File: tests/core/object/test_undo_redo.h [hunk 2]
```diff
@@ -0,0 +1,211 @@
...
+
+void increment_property_action(UndoRedo *undo_redo, const String &name, _TestUndoRedoObject *test_object, int value, UndoRedo::MergeMode merge_mode = UndoRedo::MERGE_DISABLE) {
+	undo_redo->create_action(name, merge_mode);
+
+	Variant val = Variant(value);
+	const Variant *argptrs[1];
+	argptrs[0] = &val;
+
+	undo_redo->add_do_method(Callable(test_object, "add_to_property").bindp(argptrs, 1));
+	undo_redo->add_undo_method(Callable(test_object, "subtract_from_property").bindp(argptrs, 1));
```
Comment (KoBeWi) [inline tests/core/object/test_undo_redo.h:78]: You can use `callable_mp()` here. There is no reason to bind these methods.

File: tests/core/object/test_undo_redo.h [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+	undo_redo->commit_action();
+}
+
+TEST_CASE("[UndoRedo] Simple Property UndoRedo") {
+	GDREGISTER_CLASS(_TestUndoRedoObject);
+	UndoRedo *undo_redo = memnew(UndoRedo());
+
+	_TestUndoRedoObject *test_object = memnew(_TestUndoRedoObject());
+
+	CHECK(test_object->get_property() == 0);
```
Comment (KoBeWi) [inline tests/core/object/test_undo_redo.h:89]: This check looks redundant. It's a test object which was just created, so obviously the value will be correct.

**Review by KoBeWi — APPROVED** [review]

File: tests/core/object/test_undo_redo.h (hunk 2 above)
Comment (TheSofox) [reply tests/core/object/test_undo_redo.h]: Done. Both good suggestions.

**Comment by akien-mga** [comment]
Thanks!
