### PR TITLE
Fix crash when clicking on "Interpolation Mode" with nonexistent node path

### LINKED ISSUE #81769: AnimationPlayer: Editor crashes when clicking on "Interpolation Mode" with nonexistent node path
### Godot version

4.1.1.stable

### System information

Ubuntu 22.04

### Issue description

The editor crashes when clicking on "Interpolation Mode" when a path points to a none-existing `NodePath`. I noticed this issue when I duplicated an `AnimationPlayer` from one scene to another.

I expect some sort of error message but not a crash.

### Steps to reproduce

Create a new project with a simple scene and add an `AnimationPlayer` as a child node. Change a path (tracks/0/path) to something that doesn't exist. Click on the button for "Interpolation Mode".

### Minimal reproduction project

[AnimationPlayerCrash.zip](https://github.com/godotengine/godot/files/12641629/AnimationPlayerCrash.zip)

### PR DESCRIPTION
**Pull request by RealMadvicius**
#81769 AnimationPlayer: Editor crashes when clicking on "Interpolation Mode" with nonexistent node path

- adding a nullptr check on a Node pointer obtained from get_node(NodePath) in case it is null now we wont execute the next instruction

> ClassDB::get_property_info(nd->get_class(), prop, &prop_info);

Which then prevents the crash and leave the PropertyInfo prop_info blank default, so when we reach next instruction

> bool is_angle = prop_info.type == Variant::FLOAT && prop_info.hint_string.find("radians") != -1;

we will have prop_info.type = NIL and
prop_info.hint_string.find("radians") will return -1 since it is empty

So is_angle will be set to false and the code can continue to execute normaly without any crash

* *Bugsquad edit, fixes: #81769*

### CODE REVIEW

**Comment by RealMadvicius** [comment]
Normaly the typo is fixed to respect the clang format, lets cross fingers

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -2698,7 +2698,11 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 						Node *nd = ap->get_node(ap->get_root())->get_node(NodePath(npath.get_concatenated_names()));
 						StringName prop = npath.get_concatenated_subnames();
 						PropertyInfo prop_info;
-						ClassDB::get_property_info(nd->get_class(), prop, &prop_info);
+
```
Comment (AThousandShips) [inline editor/animation_track_editor.cpp:2701]: This should be inside an if statement instead, like so:
```cpp
						if (nd) {
							StringName prop = npath.get_concatenated_subnames();
							PropertyInfo prop_info;
							ClassDB::get_property_info(nd->get_class(), prop, &prop_info);

							bool is_angle = prop_info.type == Variant::FLOAT && prop_info.hint_string.find("radians") != -1;
							if (is_angle) {
								menu->add_icon_item(get_editor_theme_icon(SNAME("InterpLinearAngle")), TTR("Linear Angle"), MENU_INTERPOLATION_LINEAR_ANGLE);
								menu->add_icon_item(get_editor_theme_icon(SNAME("InterpCubicAngle")), TTR("Cubic Angle"), MENU_INTERPOLATION_CUBIC_ANGLE);
							}
						}
```
Starting from the line below `Node *nd = ap->get_node(ap->get_root())->get_node(NodePath(npath.get_concatenated_names()));`

Comment (RealMadvicius) [reply editor/animation_track_editor.cpp:2699]: I have ammended my commit with the recommendations you provided

Comment (AThousandShips) [reply editor/animation_track_editor.cpp:2699]: Looks good! But remove this line

Comment (RealMadvicius) [reply editor/animation_track_editor.cpp]: Done

File: editor/animation_track_editor.cpp [hunk 2]
```diff
@@ -2696,13 +2696,15 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 					if (ap) {
 						NodePath npath = animation->track_get_path(track);
 						Node *nd = ap->get_node(ap->get_root())->get_node(NodePath(npath.get_concatenated_names()));
```
Comment (lyuma) [inline editor/animation_track_editor.cpp:2698]: We should store the result of `ap->get_node(ap->get_root())` in a tempoary `Node*` and also perform a null check on this part.

I checked and this is the only place in the file that performs either of these `get_node` calls so it's probably best to be safe. Not all AnimationPlayer nodes have their root set to `..`

**Review by lyuma — APPROVED** [review]
I think it makes a lot of sense to do this check. This code generally doesn't touch nodes within the scene

This is the only place in the code that does either call to `get_node()` which is a big warning flag, so we need to be extra safe in this part of the code.

Your change is good, and I propose one additional check to be extra safe on top of what you already did.

File: editor/animation_track_editor.cpp (hunk 2 above)
Comment (RealMadvicius) [reply editor/animation_track_editor.cpp]: I have added the extra check and a little comment in the code to explain why we need it

File: editor/animation_track_editor.cpp [hunk 3]
```diff
@@ -2695,18 +2695,25 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 					AnimationPlayer *ap = ape->get_player();
 					if (ap) {
 						NodePath npath = animation->track_get_path(track);
-						Node *nd = ap->get_node(ap->get_root_node())->get_node(NodePath(npath.get_concatenated_names()));
-						StringName prop = npath.get_concatenated_subnames();
-						PropertyInfo prop_info;
-						ClassDB::get_property_info(nd->get_class(), prop, &prop_info);
+						Node *aApRootNode = ap->get_node(ap->get_root_node());
```
Comment (AThousandShips) [inline editor/animation_track_editor.cpp:2698]:
```suggestion
						Node *a_ap_root_node = ap->get_node(ap->get_root_node());
```
Use `snake_case`

File: editor/animation_track_editor.cpp [hunk 4]
```diff
@@ -2695,18 +2695,25 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
...
+						Node *nd = nullptr;
+						//we must test that we have a valid ApRootNode before trying to access its content to init the nd Node
+						if(aApRootNode) {
```
Comment (AThousandShips) [inline editor/animation_track_editor.cpp:2701]:
```suggestion
						if (a_ap_root_node) {
```

File: editor/animation_track_editor.cpp [hunk 5]
```diff
@@ -2695,18 +2695,25 @@ void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) {
 					AnimationPlayer *ap = ape->get_player();
 					if (ap) {
 						NodePath npath = animation->track_get_path(track);
-						Node *nd = ap->get_node(ap->get_root_node())->get_node(NodePath(npath.get_concatenated_names()));
-						StringName prop = npath.get_concatenated_subnames();
-						PropertyInfo prop_info;
-						ClassDB::get_property_info(nd->get_class(), prop, &prop_info);
+						Node *aApRootNode = ap->get_node(ap->get_root_node());
+						Node *nd = nullptr;
+						//we must test that we have a valid ApRootNode before trying to access its content to init the nd Node
```
Comment (AThousandShips) [inline editor/animation_track_editor.cpp:2700]:
```suggestion
						// We must test that we have a valid ApRootNode before trying to access its content to init the nd Node.
```

File: editor/animation_track_editor.cpp (hunk 3 above)
Comment (RealMadvicius) [reply editor/animation_track_editor.cpp:2698]: my bad I'm too used to camel case from my workplace, I'm gonna fix this

**Comment by AThousandShips** [comment]
Please update your commit title to be more descriptive, the title of the PR is good

**Review by lyuma — APPROVED** [review]

**Comment by RealMadvicius** [comment]
I have edited the commit title to correspond to the PR title as asked

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by harrisyu** [comment]
With this commit, we found a bug, after you moved a node, animationplayer lost it's path. does it execute when node in / out of tree?

**Comment by YuriSizov** [comment]
@harrisyu Please report your bug as a new issue with a reproduction project attached.
