### PR TITLE
Fix passive mouse hovering for physics

### LINKED ISSUE #69708: mouse_entered/mouse_exited not emitting when camera moves
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Linux T430 Thinkpad, Mobile renderer, Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz

### Issue description

the mouse_entered and mouse_exited signals only update when the mouse has moved, which means if the players camera moves looking away from an object. godot does not detect that the mouse has exited the object.

### Steps to reproduce

1. create a area3d with a collider
2. connect the mouse_entered and mouse_exited to a script to print the results
4. without moving your mouse move your in-game camera around
5. the mouse_entered and mouse_exited signal do not emit even though your mouse is exiting and or entering the area3d

### Minimal reproduction project

hover your mouse over the square
and see that "mouse_entered" is printed into the console

move your camera away from the square with 'a' or 'd' without moving your mouse
and see that "mouse_exited" is not printed until you move your mouse again
[mouseenterbugfix.zip](https://github.com/godotengine/godot/files/10173908/mouseenterbugfix.zip)

example video to better show what I mean

https://user-images.githubusercontent.com/94768729/206123583-ac7b89f7-4001-4944-bdbb-4cdb2cd6b717.mp4

### LINKED ISSUE #75711: Area2D mouse_entered/mouse_exited doesn't update properly with Camera2D movement
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Linux

### Issue description

When the `mouse_entered` and `mouse_exited` signals are used with an `Area2D` node, the signals are not emitted if the `Camera2D` moves the viewport such that the mouse enters or leaves the area.

area

### Steps to reproduce

Open the attached minimal project...

1) Put the mouse cursor inside the circular area
2) Move the camera with WASD or arrow keys such that the mouse cursor enters and leaves the area (don't move the mouse in this step)
3) Watch as the label doesn't update properly

### Minimal reproduction project

[Area2D bug.zip](https://github.com/godotengine/godot/files/11162322/Area2D.bug.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Currently mouse hovering doesn't update the state, when collision objects or the camera move.
This PR fixes this problem by taking the mouse position from the viewport and not from a nonexistent previous event.

Since previous events could potentially be a long time ago, their modifier-key state might be outdated. This PR fetches the current status of modifier-keys from `Input`.

These changes allow the removal of some class-variables and making additional simplifications.

resolve #69708
resolve #75711

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -682,32 +682,31 @@ void Viewport::_process_picking() {
...
-			mm->set_button_mask(physics_last_mouse_state.mouse_mask);
-			physics_picking_events.push_back(mm);
-		}
+		mm->set_device(InputEvent::DEVICE_ID_INTERNAL);
+		mm->set_position(get_mouse_position());
+		mm->set_global_position(mm->get_position());
+		mm->set_alt_pressed(Input::get_singleton()->is_physical_key_pressed(Key::ALT));
+		mm->set_shift_pressed(Input::get_singleton()->is_physical_key_pressed(Key::SHIFT));
+		mm->set_ctrl_pressed(Input::get_singleton()->is_physical_key_pressed(Key::CMD_OR_CTRL));
+		mm->set_meta_pressed(Input::get_singleton()->is_physical_key_pressed(Key::META));
```
Comment (RandomShaper) [inline scene/main/viewport.cpp:707]:
```suggestion
		mm->set_alt_pressed(Input::get_singleton()->is_key_pressed(Key::ALT));
		mm->set_shift_pressed(Input::get_singleton()->is_key_pressed(Key::SHIFT));
		mm->set_ctrl_pressed(Input::get_singleton()->is_key_pressed(Key::CTRL));
		mm->set_meta_pressed(Input::get_singleton()->is_key_pressed(Key::META));
```

I'm not super sure. What do you think?

Comment (Sauermann) [reply scene/main/viewport.cpp]: I'm not versed in these difference between `is_physical_key_pressed` and `is_key_pressed` and their implications, so I will accept your changes.
Have tested these changes with the MPRs of both linked issues.

**Review by RandomShaper — APPROVED** [review]
TIWAGOS, but LGTM.

**Comment by akien-mga** [comment]
Thanks!
