### PR TITLE
Fix unstable AnimationTrackEditor snapping value

### LINKED ISSUE #91729: Mismatch of snap results between key movement and cursor movement in AnimationTrackEditor
### Tested versions

4.3.dev6 (no error on cursor, key has error)
4.1.3, 4.2.2 (match the result but both have float error)

### System information

Any

### Issue description

The default snap setting for animation is now 0.0333 second, but there is a problem with the snap result not matching the key and current time cursor at this time.

https://github.com/godotengine/godot/assets/61938263/77529b48-b169-4a6d-88e4-f88dab187fab

There seems to have been a fix for the cursor at some point (Maybe #87250? I will test later), so the key movement needs to follow suit.

### Steps to reproduce

Use snap with float second value and move key and timeline current position cursor.

### Minimal reproduction project (MRP)

[snapanim.zip](https://github.com/godotengine/godot/files/15252801/snapanim.zip)

### LINKED ISSUE #92273: Godot Changing AnimationPlayer Snap Settings in FPS Mode
### Tested versions

Godot 4.2.2 Stable
tested in Godot 3.5.3 Stable and it works correctly

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 SUPER (NVIDIA; 31.0.15.5222) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When i set my animations to snap to 60fps in the animationplayer, and i close the program, reopen it, it changes the 60fps to 59.9999. for all my animations

### Steps to reproduce

1. create new project
2. create a node
3. add animationplayer to it and create an animation.
4. change snap to 60fps
5. save node as scene
6. close program
7. reopen program to find it changed

### Minimal reproduction project (MRP)

[TestProject.zip](https://github.com/godotengine/godot/files/15410281/TestProject.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #91729, Fixes #92273. Fundamentally, both are due to lack of precision.

- **Explanation about #91729:**

`0.0333 second` cannot be snapped to `1.0 second` because the lack of precision; the result of `0.0333 * 30` is `0.9999`.

At some point, for timeline current time, even in second mode, it seems snap was to be done by dividing after the FPS conversion by an int value. However, the snap method for moving keyframes was implemented differently, resulting in inconsistent results. Considering the use case, an internal/temporary int conversion seems to make sense.

- **Explanation about #92273:**

The `60 fps` value is actually converted to `0.01666666666667 second` and stored in animation as `0.0166667 second`. I don't know if this is a change in 4.0 or not, but I suspect it is the reason why it is not a problem in 3.x (it stored `60 fps` without converting?). The problem in 4.0 is that after storing the value in `.tscn`, the inverse is computed.

The problem in 4.0 is that after storing the value in `.tscn`, the resuld of `1.0 / 0.0166667` is `59.9999 fps`, although `1.0 / 0.01666666666667` is `60 fps` before storing. This can be solved by reducing the user-specifiable precision when in fps mode. ~As I mentioned in my comment, considering the format for broadcasting (such as 29.97 fps), I think 2 decimal places are sufficient.~

---

By the way, make sure you don't confuse #91729 with #92273. They are different calculations and need to be corrected in different places:

- #91729 
  - This is a problem caused by errors due to the accumulation of decimals and requires a workaround to correct the calculation at the snap.
- #92273 
  - This is a problem caused by an error when calculating the inverse of a decimal, and requires a workaround to reduce the overall user-specifiable precision of the fps mode.

### CODE REVIEW

**Comment by TokageItLab** [comment]
KeyTime in fps mode seems to be limited to int by KeyEditor to begin with.

**AnimationTrackKeyEditEditor**
```cpp
    if (use_fps) {
        spinner->set_step(1);
        spinner->set_hide_slider(true);
        real_t fps = animation->get_step();
        if (fps > 0) {
            fps = 1.0 / fps;
        }
        spinner->set_value(key_ofs * fps);
    }
```

Considering this, limiting with int may be fine. Although for broadcast, it may need to be encoded externally, since the second decimal place is defined as a format, but it needs technically more precise (multiplication comes in to add frames for the signal), so it would not be very useful to support decimals here.

File: editor/animation_track_editor.cpp [hunk 1]
```diff
@@ -7007,25 +7016,26 @@ void AnimationTrackEditor::_selection_changed() {
 	}
 }
 
+void AnimationTrackEditor::_update_snap_unit() {
+	if (timeline->is_using_fps() && step->get_value() > 0) {
+		snap_unit = 1.0 / step->get_value();
+	} else {
+		snap_unit = 1.0 / Math::round(1.0 / step->get_value()); // Follow the snap behavior of the timeline editor.
```
Comment (stephen-berry) [inline editor/animation_track_editor.cpp:7023]: Is there a chance that step->get_value() > 0 is false? I always like to make sure there is no scenario where we are dividing by 0.

Comment (TokageItLab) [reply editor/animation_track_editor.cpp:7028]: Oh sure. This was not enough to avoid zero div, thanks. Now fixed.

File: editor/animation_track_editor.cpp [hunk 2]
```diff
@@ -7007,25 +7016,31 @@ void AnimationTrackEditor::_selection_changed() {
 	}
 }
 
+void AnimationTrackEditor::_update_snap_unit() {
+	if (step->get_value() < 0) {
```
Comment (AThousandShips) [inline editor/animation_track_editor.cpp:7020]:
```suggestion
	if (step->get_value() <= 0) {
```
Surely? Otherwise it'll still divide by zero below

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
