### PR TITLE
Fix `reparent()` losing owner

### LINKED ISSUE #81480: Can't access node by %UniqueName after .reparent()
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

After reparenting a node, you can't access it anymore by it's unique name %.
I would expect the unique name to still point to the node.

### Steps to reproduce

- Make node accessable by unique name
- Reparent node at runtime `reparent()`
- Try to access by unique name

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by twobitadder**
Fixes #81480, but I am open to suggestions on any changes that need to be made - I just took the most obvious path suggested in the issue for a fix.

Thanks!

### CODE REVIEW

**Comment by RandomShaper** [comment]
I think this makes sense, but let me bring a couple of points up:

- Setting the owner requires additional steps, like checking the new owner is valid (an ancestor). Let me suggest moving the code of `Node::set_owner()` to a private function `_set_owner()` that also takes a `bool p_show_warning`. The `Node::set_owner()` would just call through it with `true`. `reparent()` would instead call it with `false` to try to set the original owner, but not printing an error in case that one is no longer valid. Additionally, in cases like this we likely don't want `owner_changed_notify()` to be called (see `_set_owner_nocheck()`) when the original owner is successfully restores. Maybe this warrants a more comprehensive rewrite so all this is taken into account at a more elemental level instead of being that "patchy."
- Documentation would need to be updated (haven't checked, but it likely says that `reparent()` is _exactly_ like removing plus re-adding somewhere else; the owner-preserving behavior should be mentioned).

**Comment by twobitadder** [comment]
this doesn't feel much less patchy, but maybe we can include a `bool p_pending_reparent` in the `Node` class that will skip clearing owner on `Node::_propagate_after_exit_tree()` if true? that way there doesn't have to be a private `Node::_set_owner()` implementation. just set it to true before reparenting and then false immediately after

**Comment by YuriSizov** [comment]
> this doesn't feel much less patchy, but maybe we can include a `bool p_pending_reparent` in the `Node` class that will skip clearing owner on `Node::_propagate_after_exit_tree()` if true? that way there doesn't have to be a private `Node::_set_owner()` implementation. just set it to true before reparenting and then false immediately after

That would be very hacky and prone to issues, like leaving pointers to the old owner when the nodes are no longer in a relationship. What Pedro suggests is much more robust and in line with how we often do stuff. And also much simpler.

**Comment by twobitadder** [comment]
i guess the issue i'm seeing (and realizing my original solution is definitely inadequate for) is that children of the reparented node will lose their `owner`, which would mean that if the unique node is a child of the reparented node, the reference is lost. i can use the private `_set_owner()` call to set the owner of the reparented node, but any children will find their owner lost.

i also may have misunderstood the original intention here! i was under the impression that you would want to keep the owner during reparent, even if the new parent doesn't share a branch with the original parent.

**Comment by YuriSizov** [comment]
>  i was under the impression that you would want to keep the owner during reparent, even if the new parent doesn't share a branch with the original parent.

Owner must be an ancestor of the node. If after reparenting this is no longer the case, then losing the owner is the correct behavior.

**Comment by twobitadder** [comment]
my mistake! so i think the assessment of this is the nodes being reparented need to be checked for who their `owner` is and if they're being reparented to a descendant of that owner. then the owner can be reset on those nodes (and not any nodes that did not originally have that owner).

i apologize, i'm sure it's obvious that i'm also familiarizing myself with the idiomatic way of doing things as i go and want to make sure this is done correctly, but it definitely ended up being a bit more involved than i anticipated :sweat_smile:

**Comment by RandomShaper** [comment]
No need to apologize! You're trying, learning and addressing feedback. You can't be asked for more.

**Comment by KoBeWi** [comment]
btw turns out the label "good first issue" was wrongly assigned on this one. It's more complex than I anticipated, sorry 🙃

**Comment by twobitadder** [comment]
all good! i appreciate the patience everybody. once i'm back in town middle of next week i'll sit down and get this worked out.

**Comment by twobitadder** [comment]
here's a first pass at a way to resolve all of the needs of this fix. it's, admittedly, an extremely naive take - my c++ experience is about ten years out of use at this point and was already rusty as i was using it, haha. i'm welcome to any recommendations as a result, and if this needs to be a more fundamental change, then so be it! as it stands i'm a little uncertain how this might be taken as it involves three iterations in order to solve the original issue, which is a bit undesired, i feel like.

**Comment by twobitadder** [comment]
... once i fix all of the style issues, of course.

**Comment by RandomShaper** [comment]
I will likely add new comments in the future (as soon as I can reason carefully about this). That said, your C++ is fine. (And if it's "rusty," well, it's trendy. 😃)

**Comment by twobitadder** [comment]
hi! i just wanted to see if there was any chance to check this out a little more. if not, no problem, but i would love to be able to contribute a fix if possible.

**Comment by RandomShaper** [comment]
This is still under my radar, but I have been too busy. I will come back very soon!

**Comment by twobitadder** [comment]
no problem at all! i appreciate the update, i also know it's probably gotten quite a bit busier with all of the new people recently :)

File: scene/main/node.cpp [hunk 1]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
 		return;
 	}
 
+	bool preserve_owner = false;
+	Node *search = p_parent;
+	Node *owner_temp = data.owner;
+	List<Node *> common_parents;
+
+	//First determine if the original owner is an ancestor of the node we're reparenting to
+	while (search) {
```
Comment (KoBeWi) [inline scene/main/node.cpp:1724]: You can use `is_ancestor_of()` instead.

File: scene/main/node.cpp [hunk 2]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+		if (search == data.owner) {
+			preserve_owner = true;
+			break;
+		}
+		search = search->data.parent;
+	}
+
+	//If so, find all children of the reparented node who have the same owner so that we can reassign them
```
Comment (KoBeWi) [inline scene/main/node.cpp:1732]:
```suggestion
	// If so, find all children of the reparented node who have the same owner so that we can reassign them.
```
Same with other comments.

File: doc/classes/Node.xml [hunk 3]
```diff
@@ -679,7 +679,7 @@
 			<param index="0" name="new_parent" type="Node" />
 			<param index="1" name="keep_global_transform" type="bool" default="true" />
 			<description>
-				Changes the parent of this [Node] to the [param new_parent]. The node needs to already have a parent.
+				Changes the parent of this [Node] to the [param new_parent]. The node needs to already have a parent. The node's [code]owner[/code] is preserved, if the owner is or is an ancestor of the new parent.
```
Comment (KoBeWi) [inline doc/classes/Node.xml:682]: "if the owner is or"
?

File: scene/main/node.cpp [hunk 4]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+				}
+			}
+			to_visit.pop_back();
+		}
+	}
+
 	data.parent->remove_child(this);
 	p_parent->add_child(this);
+
+	//Reassign the old owner to those found nodes
```
Comment (AThousandShips) [inline scene/main/node.cpp:1756]:
```suggestion
	// Reassign the old owner to those found nodes.
```

File: scene/main/node.cpp [hunk 5]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
 		return;
 	}
 
+	bool preserve_owner = false;
+	Node *search = p_parent;
+	Node *owner_temp = data.owner;
+	List<Node *> common_parents;
+
+	//First determine if the original owner is an ancestor of the node we're reparenting to
```
Comment (AThousandShips) [inline scene/main/node.cpp:1723]:
```suggestion
	// First determine if the original owner is an ancestor of the node we're reparenting to.
```

File: scene/main/node.cpp [hunk 6]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+		List<Node *> to_visit;
+
+		to_visit.push_back(this);
+		common_parents.push_back(this);
+
+		while (to_visit.size() > 0) {
+			Node *check = to_visit[to_visit.size() - 1];
+
+			for (int i = 0; i < check->get_child_count(); i++) {
+				Node *child = check->get_child(i, false);
```
Comment (KoBeWi) [inline scene/main/node.cpp:1743]:
```suggestion
				const Node *child = check->get_child(i, false);
```

File: scene/main/node.cpp [hunk 7]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+				if (child->data.owner == owner_temp) {
+					to_visit.push_back(child);
+					common_parents.push_back(child);
+				}
+			}
+			to_visit.pop_back();
```
Comment (KoBeWi) [inline scene/main/node.cpp:1749]: This should be before the loop, otherwise you are removing the node you just added.

File: scene/main/node.cpp [hunk 8]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+		}
+	}
+
 	data.parent->remove_child(this);
 	p_parent->add_child(this);
+
+	//Reassign the old owner to those found nodes
+	if (preserve_owner) {
+		for (int i = 0; i < common_parents.size(); i++) {
```
Comment (KoBeWi) [inline scene/main/node.cpp:1758]:
```suggestion
		for (Node *E : common_parents) {
```

File: scene/main/node.cpp [hunk 9]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+			common_parents[i]->_set_owner(owner_temp, false);
```
Comment (KoBeWi) [inline scene/main/node.cpp:1759]:
```suggestion
		for (Node *E : common_parents) {
			E->_set_owner(owner_temp, false);
```

File: scene/main/node.cpp [hunk 10]
```diff
@@ -1892,7 +1938,7 @@ bool Node::is_unique_name_in_owner() const {
 	return data.unique_name_in_owner;
 }
 
-void Node::set_owner(Node *p_owner) {
+void Node::_set_owner(Node *p_owner, bool p_show_warning) {
```
Comment (KoBeWi) [inline scene/main/node.cpp:1941]: What is this change for? Don't you already ensure this when checking the owner beforehand?

File: scene/main/node.cpp [hunk 11]
```diff
@@ -1715,8 +1715,50 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+		to_visit.push_back(this);
+		common_parents.push_back(this);
+
+		while (to_visit.size() > 0) {
+			Node *check = to_visit[to_visit.size() - 1];
+
+			for (int i = 0; i < check->get_child_count(); i++) {
+				Node *child = check->get_child(i, false);
+				if (child->data.owner == owner_temp) {
+					to_visit.push_back(child);
```
Comment (KoBeWi) [inline scene/main/node.cpp:1745]: You should push `to_visit` even if owner doesn't match, to handle local ancestors of editable children.

**Comment by KoBeWi** [comment]
I think the general implementation is ok, there are a few details to iron out.

File: doc/classes/Node.xml (hunk 3 above)
Comment (twobitadder) [reply doc/classes/Node.xml:682]: boy i don't know what happened there lol. i think i was just tired. i was trying to go for "if the owner is - or is an ancestor of - the new parent..." but that is extremely poorly worded

File: scene/main/node.cpp (hunk 10 above)
Comment (twobitadder) [reply scene/main/node.cpp:1941]: you are totally correct - i think i just kept the old implementation and didn't think about it. i'll go ahead and get this cleaned up too

File: scene/main/node.cpp (hunk 7 above)
Comment (twobitadder) [reply scene/main/node.cpp:1749]: yeah, not sure what i was thinking there

File: scene/main/node.cpp [hunk 12]
```diff
@@ -1715,8 +1715,41 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
 		return;
 	}
 
+	bool preserve_owner = p_parent->is_ancestor_of(this);
```
Comment (KoBeWi) [inline scene/main/node.cpp:1718]: This is not the same as the previous code. You should check if `data.owner` is ancestor of `p_parent`.

File: scene/main/node.h [hunk 13]
```diff
@@ -440,6 +440,7 @@ class Node : public Object {
 	void _move_child(Node *p_child, int p_index, bool p_ignore_end = false);
 
 	void set_owner(Node *p_owner);
+	void _set_owner(Node *p_owner, bool p_show_warning);
```
Comment (KoBeWi) [inline scene/main/node.h:443]:
```suggestion
```
Unused.

File: scene/main/node.cpp [hunk 14]
```diff
@@ -1918,6 +1951,7 @@ void Node::set_owner(Node *p_owner) {
 
 	ERR_FAIL_COND_MSG(!owner_valid, "Invalid owner. Owner must be an ancestor in the tree.");
 
+
```
Comment (KoBeWi) [inline scene/main/node.cpp:1954]:
```suggestion
```

File: scene/main/node.cpp (hunk 12 above)
Comment (twobitadder) [reply scene/main/node.cpp:1718]: sheesh you're fast. you're also totally correct on that. i'll get that fixed.

File: scene/main/node.cpp [hunk 15]
```diff
@@ -1715,8 +1715,41 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
 		return;
 	}
 
+	bool preserve_owner = data.owner->is_ancestor_of(p_parent);
```
Comment (KoBeWi) [inline scene/main/node.cpp:1718]:
```suggestion
	bool preserve_owner = data.owner && data.owner->is_ancestor_of(p_parent);
```
Otherwise it will crash with no owner.

Comment (twobitadder) [reply scene/main/node.cpp:1718]: ah, yes, my old friend the segfault. in retrospect it's obvious to check for, but i would be blind if it weren't for hindsight! i appreciate your eyes on this.

Comment (KoBeWi) [reply scene/main/node.cpp:1718]: tbh this one was caught by CI.

**Review by KoBeWi — APPROVED** [review]

**Comment by twobitadder** [comment]
squashed to one commit. thanks again for the assistance and patience!

**Comment by akien-mga** [comment]
Last git nitpick, could you tidy the commit's description too?

image

See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind for general advice on commit messages for Godot.

**Comment by twobitadder** [comment]
not a nitpick at all! i, uh, didn't realize i had been taking everybody else on the same journey i had been going on while updating this PR

File: scene/main/node.cpp [hunk 16]
```diff
@@ -1715,8 +1715,41 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+
 	data.parent->remove_child(this);
 	p_parent->add_child(this);
+
+	// Reassign the old owner to those found nodes.
+	if (preserve_owner) {
+		for (const Node *E : common_parents) {
+			Node *N = const_cast<Node *>(E);
+			N->set_owner(owner_temp);
+		}
```
Comment (RandomShaper) [inline scene/main/node.cpp:1751]:
```suggestion
		for (Node *E : common_parents) {
			E->set_owner(owner_temp);
		}
```

File: scene/main/node.cpp [hunk 17]
```diff
@@ -1715,8 +1715,41 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
 		return;
 	}
 
+	bool preserve_owner = data.owner && (data.owner == p_parent || data.owner->is_ancestor_of(p_parent));
+	Node *owner_temp = data.owner;
+	List<const Node *> common_parents;
```
Comment (RandomShaper) [inline scene/main/node.cpp:1720]: Maybe a `LocalVector` would be better here.

File: scene/main/node.cpp [hunk 18]
```diff
@@ -1715,8 +1715,41 @@ void Node::reparent(Node *p_parent, bool p_keep_global_transform) {
...
+
+	// If the new parent is related to the owner, find all children of the reparented node who have the same owner so that we can reassign them.
+	if (preserve_owner) {
+		List<const Node *> to_visit;
```
Comment (RandomShaper) [inline scene/main/node.cpp:1724]: ...and maybe here, too (`LocalVector`).

**Review by RandomShaper — CHANGES_REQUESTED** [review]

**Comment by RandomShaper** [comment]
Sorry for stepping in when everything looked settled. Just a few minor things I think can be improved.

File: doc/classes/Node.xml (hunk 3 above)
[the remark this answers is not in the document]
Comment (twobitadder) [reply doc/classes/Node.xml]: huh! this seems to be outdated from what i'd changed the docs to. regardless, this is definitely clearer so i'll get that changed.

File: scene/main/node.cpp (hunk 18 above)
Comment (AThousandShips) [reply scene/main/node.cpp:1724]: `LocalVector` is perfectly suited for a stack

Comment (twobitadder) [reply scene/main/node.cpp:1724]: ok! removed the `const`ness and changed the `List`s to `LocalVector`s

**Comment by twobitadder** [comment]
no problem! i'm definitely also learning as i go with this experience so it's useful for me as well

**Comment by akien-mga** [comment]
For the record, we discussed this together with other PR with Yuri and Clay from the production team and decided that this wasn't critical for 4.2 (which is nearing release candidate), and might need some testing to ensure everyone agrees with the behavior change, hence the milestone bump to 4.3.

**Comment by twobitadder** [comment]
sounds good - i think that's completely reasonable given this is a fairly common action

**Comment by twobitadder** [comment]
hi! just wanted to check in and see if this is still a good candidate for 4.3, and if there's anything else required of me to assess/change

**Comment by AThousandShips** [comment]
The review comments you marked as resolved but didn't apply maybe?

**Comment by twobitadder** [comment]
hmm, i'm not really sure... i applied all of the requested changes as far as i know, so i'm not certain why it's saying that there are more changes. maybe i missed one? reviewing the four requested changes i do see, i did enact them all before listing them as resolved (at the very least, the current version of the code reflects those changes)

File: scene/main/node.cpp (hunk 16 above)
Comment (twobitadder) [reply scene/main/node.cpp]: also done! just commenting on this for clarity's sake after the fact.

**Comment by AThousandShips** [comment]
Unresolved the ones you didn't apply 🙂

**Comment by twobitadder** [comment]
ahh okay - the ones from KoBeWi were _previously_ applied, but i had changed them out based on later requested changes by RandomShaper. they were resolved at the time though they do conflict now, is there a consensus on which direction i should go with those particular lines?

**Comment by AThousandShips** [comment]
Then resolved, my bad, the change is correct 🙂

**Comment by twobitadder** [comment]
not a problem at all, and i appreciate the check! i just wanted to be sure i wasn't missing anything, haha

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
CC @RandomShaper

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by pc9098** [comment]
This doesn't seem to be included in [changelog](https://godotengine.github.io/godot-interactive-changelog/#4.3)

**Comment by twobitadder** [comment]
correct me if i'm wrong, but i think this would only be in there if it is a part of a release. this missed the dev 2 window so it won't be in engine until dev 3 at earliest

**Comment by akien-mga** [comment]
The interactive changelog isn't updated automatically, it was last synced when I released 4.2-dev2. So yeah changes merged after dev2 aren't reflected yet.
