### PR TITLE
Ensure MSBuildPanel buttons are instantiated

### LINKED ISSUE #51344: Unhandled Exception on opening of any project and build for 3.4 Beta 3 Mono
### Godot version

3.4-beta3-mono

### System information

Windows 10

### Issue description

Opening any project with Godot 3.4 beta 3 produces following on console/terminal:

> Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.Build.MSBuildPanel._Notification (System.Int32 what) [0x00022] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
  at (wrapper managed-to-native) Godot.EditorNativeCalls.godot_icall_2_387(intptr,intptr,intptr,string)
  at Godot.EditorPlugin.AddControlToBottomPanel (Godot.Control control, System.String title) [0x00012] in <d86e52e4ad7b488bbaa0527a6715c72d>:0
  at GodotTools.GodotSharpEditor.EnablePlugin () [0x00066] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
ERROR: System.NullReferenceException: Object reference not set to an instance of an object
   at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)

> Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.Build.MSBuildPanel._Notification (System.Int32 what) [0x00022] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
ERROR: System.NullReferenceException: Object reference not set to an instance of an object
   at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)

Building solution generates another one:
> Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.Build.MSBuildPanel.BuildSolution () [0x0003a] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
  at GodotTools.Build.MSBuildPanel.BuildMenuOptionPressed (GodotTools.Build.MSBuildPanel+BuildMenuOptions id) [0x00014] in <b9053caf64864612ac6ebb8ebfb7cdbb>:0
ERROR: System.NullReferenceException: Object reference not set to an instance of an object
   at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)

Happens for me on two different Windows machines.
Doesn't seems to have any negative effect, at least not on second machine. On first Godot crashed/closed once during build but I haven't tested if that was a persistent issue or a one off.

Not sure if this is related, but Editor Settings -> Mono -> Builds -> Build tool is showing a number for me.

Annotation 2021-08-06 223440

Similar to https://github.com/godotengine/godot/issues/50486#issuecomment-880774291

Neither of those (exception or number in build tools instead of name/drop down) happens for me in 3.4 beta 2.

### Steps to reproduce

Open any project in Godot v3.4 beta 3, on windows 10

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by raulsntos**
After #51220, `MSBuildPanel` was throwing a `NullReferenceException` on the `_Notification` method since the method can get called before the `_Ready` method where the buttons are instantiated so it was trying to set the icon of a null button. This PR initializes the panel in the constructor instead of using the `_Ready` method to make sure the buttons are never null.

An alternative implementation would be to leave the initialization in the `_Ready` method and check if the buttons are null in the `_Notification` method, but it doesn't seem like we need to wait for `_Ready` to do any of the initialization that `MSBuildPanel` does so it can be done in the constructor.

*Bugsquad edit:* Fixes #51344.

### CODE REVIEW

**Comment by pycbouh** [comment]
> An alternative implementation would be to leave the initialization in the `_Ready` method and check if the buttons are null in the `_Notification` method, but it doesn't seem like we need to wait for `_Ready` to do any of the initialization that `MSBuildPanel` does so it can be done in the constructor.

Indeed your current solution is correct (at least as far as we usually do it in Godot's codebase). Weird that I didn't experience the issue, or at least didn't notice it, but this change makes sense.

**Review by neikeq — CHANGES_REQUESTED** [review]
As far as I remember, we do initialization on `_Ready` because the constructor is always called after hot-reload. If we were to do initialization in the constructor we would be adding extra child buttons every time assemblies were hot-reloaded.

**Comment by pycbouh** [comment]
Is it a C# specific thing? Neither C++ side nor GDScript would do that (unless it was terminated improperly).

**Comment by neikeq** [comment]
> Is it a C# specific thing? Neither C++ side nor GDScript would do that (unless it was terminated improperly).

I don't know if GDScript calls `_init` every time a script is reloaded. But GDScript doesn't need to reload all script, only the ones that change.

> Also, why would it hot reload at all? :upside_down_face: 

Because we need to destroy the domain, start a new one and reload assemblies back. So we need to reload everything if something changes.

**Comment by pycbouh** [comment]
But shouldn't all the UI nodes be removed from the tree and destroyed when you do a complete reload? `_Ready` is way too late to add child nodes generally. `_Ready` should indicate that child nodes are also ready, and this way it's not possible.

**Comment by neikeq** [comment]
No, they are not removed on reload regardless of the language.
Regarding the constructor and `_Ready`, I want to improve this as I don't like it either. But right now this is how it works, so there's no point in discussing it in the scope of this PR.

**Comment by raulsntos** [comment]
> As far as I remember, we do initialization on `_Ready` because the constructor is always called after hot-reload. If we were to do initialization in the constructor we would be adding extra child buttons every time assemblies were hot-reloaded.

That makes sense. I was under the impression the game assembly was the only one that needed to be reloaded.

> Regarding the constructor and `_Ready`, I want to improve this as I don't like it either. But right now this is how it works, so there's no point in discussing it in the scope of this PR.

That would be nice.

I have updated the PR to use `_Ready` and check if the buttons are `null` instead.

File: modules/mono/editor/GodotTools/GodotTools/Build/MSBuildPanel.cs [hunk 1]
```diff
@@ -183,10 +183,14 @@ public override void _Notification(int what)
...
-                errorsBtn.Icon = GetThemeIcon("StatusError", "EditorIcons");
-                warningsBtn.Icon = GetThemeIcon("NodeWarning", "EditorIcons");
+            if (what == NotificationThemeChanged)
+            {
+                if (buildMenuBtn != null)
+                    buildMenuBtn.Icon = GetThemeIcon("Play", "EditorIcons");
+                if (errorsBtn != null)
+                    errorsBtn.Icon = GetThemeIcon("StatusError", "EditorIcons");
+                if (warningsBtn != null)
+                    warningsBtn.Icon = GetThemeIcon("NodeWarning", "EditorIcons");
```
Comment (neikeq) [inline modules/mono/editor/GodotTools/GodotTools/Build/MSBuildPanel.cs:193]: Null conditional operator `?.` would be shorter and more readable. But it's nothing important.

**Review by neikeq — APPROVED** [review]

File: modules/mono/editor/GodotTools/GodotTools/Build/MSBuildPanel.cs (hunk 1 above)
Comment (raulsntos) [reply modules/mono/editor/GodotTools/GodotTools/Build/MSBuildPanel.cs:193]: I can't use it on an assignment: `The left-hand side of an assignment must be a variable, property or indexer`.

**Comment by akien-mga** [comment]
Thanks!
