### PR TITLE
Fix shader editor crash

### LINKED ISSUE #77701: Editor Crash when pressing "Control + S" with .gdshaderinc open in shader editor
### Godot version

Godot Engine v4.1.dev3 [a67d37f7c]

### System information

Windows 10, i711800H, Forward+ Vulkan

### Issue description

If I have a .gdshaderinc open in the bottompanel shader editor and then press CTRL + S to save the current scene the editor crashes and closes. However, it seems to work if I press save via File > Save File.
This is even an issue with an empty .gdshaderinc file

### Steps to reproduce

1. Open Main Scene
2. Open .gdshaderinc
3.  Press CTRL + S

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/11616811/MRP.zip)

### PR DESCRIPTION
**Pull request by bitsawer**
Fixes an unreported (?) crash when editing shaders and shader includes using the shader editor.

Seems like this small error was introduced by https://github.com/godotengine/godot/pull/72277. This PR adds a check to make sure the right type of resource is used, previously it would sometimes crash when handling a ShaderInclude.

*Bugsquad edit:*
- Fixed #77701

### CODE REVIEW

File: editor/plugins/shader_editor_plugin.cpp [hunk 1]
```diff
@@ -265,13 +265,19 @@ void ShaderEditorPlugin::get_window_layout(Ref<ConfigFile> p_layout) {
 	for (int i = 0; i < shader_tabs->get_tab_count(); i++) {
 		EditedShader edited_shader = edited_shaders[i];
 		if (edited_shader.shader_editor || edited_shader.visual_shader_editor) {
-			shaders.push_back(edited_shader.shader->get_path());
+			String shader_path;
+			if (!edited_shader.shader.is_null()) {
+				shader_path = edited_shader.shader->get_path();
+			} else {
+				shader_path = edited_shader.shader_inc->get_path();
```
Comment (QbieShay) [inline editor/plugins/shader_editor_plugin.cpp:272]: Does it need to check also for shader_inc to not be null?

Comment (bitsawer) [reply editor/plugins/shader_editor_plugin.cpp:272]: In general, the behavior in these shader editors seems to be that the shader is checked first. If that is null, assume that shader include is valid. If both are null for some reason the code will crash because something else is very wrong and should be fixed. Probably not the most robust way to handle things, but seems to work okay in practice.

For example here:

https://github.com/godotengine/godot/blob/2eec9a67d564b11326f44c5ef8b6b6f9aec251b9/editor/plugins/shader_editor_plugin.cpp#L49-L54

Or in here (and several other places):

https://github.com/godotengine/godot/blob/2eec9a67d564b11326f44c5ef8b6b6f9aec251b9/editor/plugins/text_shader_editor.cpp#L429-L434

Comment (clayjohn) [reply editor/plugins/shader_editor_plugin.cpp:272]: In that case you can add a DEV_ASSERT inside the ``else`` condition just before reading from ``shader_inc``. DEV_ASSERTs are compiled out in release builds so they are very handy for this type of rare error checking

Comment (bitsawer) [reply editor/plugins/shader_editor_plugin.cpp:273]: Done.

**Review by clayjohn — APPROVED** [review]
Looks great! Thank you!

**Comment by akien-mga** [comment]
Thanks!
