### PR TITLE
Fix wrong focus neighbor for grid-aligned 0 separation controls

### LINKED ISSUE #42965: Unexpected focus neighbor behavior with buttons in a GridContainer when the vseparation and hseparation are set to 0
**Godot version:**
Godot 3.2.3.stable

**OS/device including version:**
Windows 10

**Issue description:**
When I attempt to navigate the buttons in a GridContainer with the vseparation and hseparation set to 0, I get unexpected behavior. For example, pressing the left arrow key when focused on a button in the right column won't focus on the button to the left, it will focus on the button up and to the left.

When I set the vseparation and hseparation of the GridContainer to at least 1, I get the expected behavior.

**Steps to reproduce:**
Run the project and try to navigate the buttons in the grid container using the arrow keys.

**Minimal reproduction project:**
[ButtonGrid.zip](https://github.com/godotengine/godot/files/5417341/ButtonGrid.zip)

### PR DESCRIPTION
**Pull request by tetrapod00**
Fixes https://github.com/godotengine/godot/issues/42965.

In these videos, I am inputting "ui_right" by pressing the right arrow key.
Current behavior:

https://github.com/user-attachments/assets/f31b2d18-9117-4f4f-83ed-e220c4f4ca7a

This fix:

https://github.com/user-attachments/assets/127162be-c7f5-40b9-a243-9aefba2bed7a

The current algorithm for finding focus neighbors seems to check each side of a control against each side of a potential closest neighbor, and choose the control which is closest. In cases where there is non-zero separation between controls, this works just fine. But in cases where there is zero separation between controls, and the controls are arranged in a grid, multiple potential controls are equally close (e.g, up-left, up. and left will all have a distance of 0). This introduces a bias towards the first found neighbor control (empirically, controls that are to the left and/or up from the current control).

This fix adds a tie-breaking step in the case where multiple controls are equally close. It sorts by the minimum distance between the *centers* of the current control and prospective closest neighbors, which works nicely for grid-aligned controls. 

Since it only runs in the tied case, this shouldn't affect existing behavior in cases where there is any separation between controls. The default theme adds separation, and anyone using zero-separation grid containers is very unlikely to be dependent on incorrect existing behavior.

My C++ will need extensive changes for style and efficiency - it's been a while since I wrote any!

Edit: Okay, that's my best attempt at C++ style. I'm aware that my code is different in style than the surrounding function, but I wanted to leave in verbose names and comments in case the algorithm itself needs to be changed. I also don't know what I don't know in terms of helper functions to use.

### CODE REVIEW

**Comment by tetrapod00** [comment]
Ah, there's another case, where checking by distance is incorrect. Video of my PR:

https://github.com/user-attachments/assets/322c94b3-b058-4fc9-8c0c-da0a84c150e3

**Comment by tetrapod00** [comment]
This video shows tie-breaking the prospective neighbors by the which one is most aligned with the desired input direction. This works in the basic grid-aligned case, and it works well enough for the center button in the edge case presented. However, it does not work intuitively when moving from the large buttons to the small ones.

https://github.com/user-attachments/assets/3f3cf3e7-f513-4a6a-a6db-d47020c0d7e6

Satisfying *all* the intuitive behaviors of neighbor focus would require rethinking the entire selection algorithm, rather than just patching a tie-breaking step at the end. 

I propose solving the narrow problem of 0 separation grid-aligned controls in this PR, using tie-breaking by the closest aligned control. This solves the obvious pain-point of a 0 separation GridContainer, as well as some other grid-aligned cases. In other cases, users can add manual neighbor overrides (as they are probably already doing). Existing behavior in non-zero separation cases will remain unchanged.

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -2358,6 +2358,19 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
 		points[2] = xform.xform(c->get_size());
 		points[3] = xform.xform(Point2(0, c->get_size().y));
 
+		// Tiebreaking variables
```
Comment (Calinou) [inline scene/gui/control.cpp:2361]: Add a more descriptive comment:

```suggestion
		// Tie-breaking refers to situations where a potential focus neighbor's bounding rect
		// is right next to the currently focused control (e.g. in BoxContainer with
		// separation overridden to 0). This needs specific handling so that the correct
		// focus neighbor is selected.
```

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -2358,6 +2358,19 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
...
+		Point2 center = xform.xform(0.5 * c->get_size());
+		Point2 p_center = 0.25 * (p_points[0] + p_points[1] + p_points[2] + p_points[3]); // We only have the points, not an actual reference
+		Point2 closest_center = Point2();
+		bool should_tiebreak = false;
```
Comment (Calinou) [inline scene/gui/control.cpp:2365]:
```suggestion
		Point2 center = xform.xform(0.5 * c->get_size());
		Point2 p_center = 0.25 * (p_points[0] + p_points[1] + p_points[2] + p_points[3]); // We only have the points, not an actual reference.
		Point2 closest_center = Point2();
		bool should_tiebreak = false;
```

File: scene/gui/control.cpp [hunk 3]
```diff
@@ -2383,6 +2396,13 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
 						r_closest_dist = d;
 						*r_closest = c;
 					}
+					// Tie-break by the control most aligned with p_dir
```
Comment (Calinou) [inline scene/gui/control.cpp:2399]:
```suggestion
					// Tie-break by the control most aligned with p_dir.
```

File: scene/gui/control.cpp [hunk 4]
```diff
@@ -2358,6 +2358,19 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
 		points[2] = xform.xform(c->get_size());
 		points[3] = xform.xform(Point2(0, c->get_size().y));
 
+		// Tiebreaking variables
+		Point2 center = xform.xform(0.5 * c->get_size());
+		Point2 p_center = 0.25 * (p_points[0] + p_points[1] + p_points[2] + p_points[3]); // We only have the points, not an actual reference
+		Point2 closest_center = Point2();
+		bool should_tiebreak = false;
+		// Calculate centers of this c, closest, and original controls
```
Comment (Calinou) [inline scene/gui/control.cpp:2366]:
```suggestion
		// Calculate centers of this c, closest, and original controls.
```

File: scene/gui/control.cpp [hunk 5]
```diff
@@ -2383,6 +2396,13 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
 						r_closest_dist = d;
 						*r_closest = c;
 					}
+					// Tie-break by the control most aligned with p_dir
+					else if (should_tiebreak && d == r_closest_dist) {
```
Comment (Calinou) [inline scene/gui/control.cpp:2400]:
```suggestion
					} else if (should_tiebreak && d == r_closest_dist) {
						// Tie-break by the control most aligned with p_dir.
```

File: scene/gui/control.cpp [hunk 6]
```diff
@@ -2358,6 +2358,19 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
...
 		points[3] = xform.xform(Point2(0, c->get_size().y));
 
+		// Tiebreaking variables
+		Point2 center = xform.xform(0.5 * c->get_size());
+		Point2 p_center = 0.25 * (p_points[0] + p_points[1] + p_points[2] + p_points[3]); // We only have the points, not an actual reference
+		Point2 closest_center = Point2();
+		bool should_tiebreak = false;
+		// Calculate centers of this c, closest, and original controls
+		if (*r_closest != nullptr) {
+			should_tiebreak = true; // Could be removed in favor of checking r_closest directly further down
```
Comment (Calinou) [inline scene/gui/control.cpp:2368]:
```suggestion
			// FIXME: This could be removed in favor of checking r_closest directly further down.
			should_tiebreak = true;
```

**Comment by KoBeWi** [comment]
In your new test project it's not possible to select corner buttons:

https://github.com/user-attachments/assets/686ae67a-57e7-4b64-b6ba-0d31f4de410d

You can select them using Tab, but the order is odd.

With old behavior it was at least partially possible:

https://github.com/user-attachments/assets/78e4a092-cfb4-445a-ab94-d3a663d67ff9

That's a corner case though, so probably fine.

File: scene/gui/control.cpp [hunk 7]
```diff
@@ -2358,6 +2358,25 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
...
+		// Tie-breaking aims to address situations where a potential focus neighbor's bounding rect
+		// is right next to the currently focused control (e.g. in BoxContainer with
+		// separation overridden to 0). This needs specific handling so that the correct
+		// focus neighbor is selected.
+
+		// Calculate centers of the potential neighbor, currently focused, and closest controls.
+		Point2 center = xform.xform(0.5 * c->get_size());
+		// We only have the points, not an actual reference.
+		Point2 p_center = 0.25 * (p_points[0] + p_points[1] + p_points[2] + p_points[3]);
+		Point2 closest_center = Point2();
```
Comment (AThousandShips) [inline scene/gui/control.cpp:2370]:
```suggestion
		Point2 closest_center;
```
Unnecessary default

**Review by KoBeWi — APPROVED** [review]
Overall it's better functionality-wise. Can't say much about the code, as it's rather complex .-.

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by tetrapod00** [comment]
> In your new test project it's not possible to select corner buttons:

My goal with this PR was to make the common case behave correctly, and make it the user's responsibility to use manual neighbors to fix literal corner cases like this. As it is, the common case is already wrong and the user's responsibility to fix with manual neighbors, so this is an improvement

If it's a hard requirement that every control on the screen must be accessible through some permutation of left, right, up, down inputs - that might be possible, but I'm not even sure if the existing system can guarantee that.

I do think that the existing algorithm + this patch is not exactly what would be designed from first principles for an intuitive default neighbor selection algorithm - that would use some weighted combination of closeness and alignment with direction. But I wanted to make a change that does not affect the existing behavior except when tie-breaking.

File: scene/gui/control.cpp [hunk 8]
```diff
@@ -2358,6 +2358,25 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
...
+		// focus neighbor is selected.
+
+		// Calculate centers of the potential neighbor, currently focused, and closest controls.
+		Point2 center = xform.xform(0.5 * c->get_size());
+		// We only have the points, not an actual reference.
+		Point2 p_center = 0.25 * (p_points[0] + p_points[1] + p_points[2] + p_points[3]);
+		Point2 closest_center;
+		bool should_tiebreak = false;
+		if (*r_closest != nullptr) {
+			// FIXME: This could be removed in favor of checking r_closest directly further down.
```
Comment (akien-mga) [inline scene/gui/control.cpp:2373]: What would it take to solve this FIXME?
FIXMEs and TODOs tend to never be fixed or done once the PR is merged.

Comment (tetrapod00) [reply scene/gui/control.cpp:2373]: We would remove the `should_tiebreak` bool and inline the check directly further down, on line 2403:
```diff
-   } else if (should_tiebreak && d == r_closest_dist) {
+   } else if ((*r_closest != nullptr) && d == r_closest_dist) {
```
I was not sure what was preferred between setting a named boolean flag or doing the check directly, so I went with a boolean because it makes the code more readable in the context of a review.

Comment (KoBeWi) [reply scene/gui/control.cpp:2373]: If you are unsure about some part, it's preferable to leave a comment in the PR itself, not in code.

Comment (tetrapod00) [reply scene/gui/control.cpp]: I just removed the FIXME. In my opinion the current explicit boolean flag is more readable than the alternative of checking `*r_closest != nullptr` directly.

**Comment by akien-mga** [comment]
Thanks!

File: scene/gui/control.cpp [hunk 9]
```diff
@@ -2378,10 +2396,15 @@ void Control::_window_find_focus_neighbor(const Vector2 &p_dir, Node *p_at, cons
 
 					Vector2 pa, pb;
 					real_t d = Geometry2D::get_closest_points_between_segments(la, lb, fa, fb, pa, pb);
-					//real_t d = Geometry2D::get_closest_distance_between_segments(Vector3(la.x,la.y,0),Vector3(lb.x,lb.y,0),Vector3(fa.x,fa.y,0),Vector3(fb.x,fb.y,0));
 					if (d < r_closest_dist) {
 						r_closest_dist = d;
 						*r_closest = c;
+					} else if (should_tiebreak && d == r_closest_dist) {
+						// Tie-break in favor of the control most aligned with p_dir.
+						if (p_dir.dot((center - p_center).normalized()) > p_dir.dot((closest_center - p_center).normalized())) {
```
Comment (Rindbee) [inline scene/gui/control.cpp:2404]: Now we are using the offset angle, this is why the corner buttons cannot be selected.

Wouldn't it be better to compare the absolute value of the cross product here?

This makes it possible to select the corner buttons.

Comment (tetrapod00) [reply scene/gui/control.cpp:2404]: That might be better, indeed. When I wrote this PR I only considered distance and dot product as options for tiebreaking.

It would probably be good to write some unit tests for focus neighbor behavior, so we can make changes like this safely.
