### PR TITLE
Fix new region select with selection when over geometry

### LINKED ISSUE #85736: Click and drag on any node in 3D incorrectly moves selected node
### Godot version

3.5 stable, all 4.x stable versions

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

So this seems to be an old one, but got worse in 3.5 and 4.0, I couldn't find any other issues about this.

Basically when in Select Mode in the 3D editor, with a node selected, clicking and dragging moves the currently selected node as if you had clicked on it, regardless of which node is under the mouse cursor. Prior to 3.5 this only happened with locked nodes under the mouse specifically.

I believe the correct behavior would be to move the node under the cursor, unless it is locked in which case a box selection would be started. This would be consistent with the 2D editor and would avoid the situation in the 3D editor where you cannot perform box selection because the background is obscured by locked nodes.

Current behavior:
* No node selected, click anything and drag -> box selection
* Node selected, click on any node and drag -> selected node moves
* Node selected, click on background and drag -> box selection

GIF demonstration, the sphere is locked:
3_5_behavior

Prior to 3.5 the behavior worked like this:
* No node selected, click background and drag -> box selection
* No node selected, click unlocked or locked node and drag -> node moves if unlocked, no box selection
* Node selected, click on any **unlocked** node and drag -> node under mouse is selected and moves
* Node selected, click on any **locked** node and drag -> selected node moves
* Node selected, click on background and drag -> box selection
<details> <summary>GIF of 3.2 - 3.4 behavior (the sphere is locked)</summary>

3_2_behavior
</details>

It seems prior to 3.2 you could click and select locked nodes in the 3D editor and that seems to have prevented the bug from appearing at all.
<details><summary>GIF of original behavior</summary>

behavior_up_to_3_1_2
</details>

### Steps to reproduce

* Open the included Godot 4 project or create a blank project and add multiple objects into a 3d scene.
* Select one node
* While staying in Select mode, click the mouse in the 3D view over a non-selected node and drag
* (prior to 3.5) click the mouse over a locked node and drag

### Minimal reproduction project

[TestClickDrag.zip](https://github.com/godotengine/godot/files/13541268/TestClickDrag.zip)

### LINKED ISSUE #87949: Select tool translates node when dragging w/o the gizmo over geometry
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]
v4.3.dev.custom_build [b4e2a24c1]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

When attempting to region-select over geometry while a node is selected, and the select tool is enabled, the selected node ends up being translated, which seems wrong.

https://github.com/godotengine/godot/assets/105675984/6d39ec75-21bc-40e9-8e93-8a13e56d3496

### Steps to reproduce

See video.

Select node using select tool.

Attempt to region select over some kind other geometry like another mesh. 

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ryevdokimov**
Fixes: #87949 Fixes #85736

You should be able to region select with the select tool even if you already have a node selected. All other tools already have the default behavior of remotely manipulating their respective gizmo when a node is selected. 

Before:

https://github.com/godotengine/godot/assets/105675984/a605187a-6167-4626-9aaf-f955ccfa41ed

After:

https://github.com/godotengine/godot/assets/105675984/8d56ad74-fc17-4e54-ae99-96ca4ac59bb8

### CODE REVIEW

**Comment by KoBeWi** [comment]
This breaks selected node dragging:

https://github.com/godotengine/godot/assets/2223172/c93f2277-c002-45e3-b265-09ae00aca745

Dragging should still move a node when the clicked node is part of the current selection.

**Comment by ryevdokimov** [comment]
Good catch. Working on it...

**Comment by ryevdokimov** [comment]
Should be fixed now. Had to add code to check whether or not the node(s) trying to be dragged are the ones that are selected.

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 1]
```diff
@@ -1985,9 +1985,19 @@ void Node3DEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
...
+					const HashMap<Node *, Object *> &selection = editor_selection->get_selection();
+
+					bool node_in_selection_clicked = false;
+
+					for (const KeyValue<Node *, Object *> &E : selection) {
+						if (E.key->get_instance_id() == clicked) {
+							node_in_selection_clicked = true;
+							break;
+						}
+					}
```
Comment (AThousandShips) [inline editor/plugins/node_3d_editor_plugin.cpp:1998]: I think this can be done more efficiently, instead of iterating over it, I think this should be enough: `editor_selection->is_selected(Object::cast_to<Node>(ObjectDB::get_instance(clicked)));`

Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp:1998]: Test it. It sure is.

**Review by KoBeWi — APPROVED** [review]

File: editor/plugins/node_3d_editor_plugin.cpp [hunk 2]
```diff
@@ -1985,9 +1985,10 @@ void Node3DEditorViewport::_sinput(const Ref<InputEvent> &p_event) {
 			} else {
 				const bool movement_threshold_passed = _edit.original_mouse_pos.distance_to(_edit.mouse_pos) > 8 * EDSCALE;
 
-				// enable region-select if nothing has been selected yet or multi-select (shift key) is active
-				if (selection_in_progress && movement_threshold_passed) {
-					if (get_selected_count() == 0 || clicked_wants_append) {
+				if (selection_in_progress && movement_threshold_passed && clicked.is_valid()) {
+					bool node_in_selection_clicked = editor_selection->is_selected(Object::cast_to<Node>(ObjectDB::get_instance(clicked)));
+
+					if (!node_in_selection_clicked) {
```
Comment (AThousandShips) [inline editor/plugins/node_3d_editor_plugin.cpp:1991]:
```suggestion
					if (!node_in_selection_clicked || clicked_wants_append) {
```
Maybe keep the shift behaviour, haven't tested but was in the original

Comment (ryevdokimov) [reply editor/plugins/node_3d_editor_plugin.cpp:1991]: This is a really good point and would have been a regression, good catch.

**Comment by ryevdokimov** [comment]
Suggestions applied and tested. Thanks for help.

**Review by AThousandShips — APPROVED** [review]

**Comment by Cammymoop** [comment]
It seems that both this approach and the one in #85740 could be desirable, probably due to the select mode tool wearing too many hats. I would prefer having the old functionality from before 3.5 restored (selecting and moving a node with a single click) but I could see myself using this style too.

Either way it looks like there's conflicting expectations on how the select tool should work in this instance, aside from the agreement that the current behavior is a bug.

**Comment by akien-mga** [comment]
Thanks!

@Cammymoop This might warrant opening a proposal to discuss what should be the desired behavior, or whether it needs to be made configurable. If the behavior changed in 3.5 / 4.0 and most users are now familiar with the current behavior as being the intended one, changing it back would likely be a problem for more users than the 3.5 / 4.0 change was.
