### PR TITLE
C#: Make internal properties and property accessors public (but hidden)

### LINKED ISSUE #71062: [C# API] Possible type mismatch of property Node.AnchorsPreset
### Godot version

4.0 beta 10

### System information

Irrevalent

### Issue description

The property Node.AnchorsPreset should be of type LayoutPreset just like what Node.SetAnchorsPreset takes, but it is now of type int. This is difficult for users to figure out which preset each int value stands for, which makes the property unusable. Its type should be changed to LayoutPreset instead. 

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by raulsntos**
Instead of making the accessors `internal` which can break binary compat, make them `public` but hide them with EB never so they don't show up in IntelliSense.

Also, do the same for properties with the `PROPERTY_USAGE_INTERNAL` flag. These properties were not meant to be exposed to scripting, but since they've been public before all we can do now is hide them.

- I _think_ this closes https://github.com/godotengine/godot/issues/71062 since the property that was confusing should now be hidden.

### CODE REVIEW

**Comment by AThousandShips** [comment]
I like this generally, but one potential compatibility issue:
Does it count as shadowing/blocking `internal` methods of parent classes in C#?

I.e. if I extend `Animation` and I decided to add a `GetLength` method to it, will this break now that `Animation.GetLength` goes from `internal` to `public`? Regardless of that being appropriate or not it's not a method anyone would know existed

File: modules/mono/editor/bindings_generator.h [hunk 1]
```diff
@@ -179,6 +187,14 @@ class BindingsGenerator {
 		 */
 		bool is_internal = false;
```
Comment (AThousandShips) [inline modules/mono/editor/bindings_generator.h:188]: We might want to update the comment on this, it speaks of setters and getters but are not internal any longer

File: modules/mono/editor/bindings_generator.cpp [hunk 2]
```diff
@@ -3863,7 +3872,7 @@ bool BindingsGenerator::_populate_object_type_interfaces() {
 				// We only make internal an accessor method if it's in the same class as the property.
```
Comment (AThousandShips) [inline modules/mono/editor/bindings_generator.cpp:3872]: This comment as well

File: modules/mono/editor/bindings_generator.h (hunk 1 above)
Comment (raulsntos) [reply modules/mono/editor/bindings_generator.h:188]: I think this still applies, it refers to property getters and setters when the method starts with an underscore and are not virtual. For example: `AnimationLibrary::_set_data`.

**Comment by raulsntos** [comment]
> I.e. if I extend `Animation` and I decided to add a `GetLength` method to it, will this break now that `Animation.GetLength` goes from `internal` to `public`?

It doesn't break binary compatibility if that's what you are asking. Your `GetLength` method shadows the inherited method and that will now give you a [warning](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108) that you can suppress with the [`new` modifier](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier) if shadowing was intended.

**Comment by AThousandShips** [comment]
That answers my question that the warning isn't an issue as such, as opposed to virtual methods in C++ etc., good!

**Review by paulloz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
