### PR TITLE
Fix commenting collapsed function issue

### LINKED ISSUE #74802: Commenting collapsed function not working properly
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

If select and comment collapsed function, only the first line will be commented.

comments bug

### Steps to reproduce

Collapse function.
Select line with mouse,
Press Ctrl + K
Expand collapsed function

You will see that all lines are not commented.

### Minimal reproduction project

```
func dummy() -> void:
	print (1)
	print (2)
	print (3)
```

### PR DESCRIPTION
**Pull request by jmb462**
Fix #74802

### Issue fixed

Commenting a folded function didn't comment the content of the function if at last line of the selection.

bug

### Fix proposal

If last commented line  via CTRL+K is a folded, also comment inner folded content.

comment_folded_function

Note : If selection was not ending on a folded line but contains a folded part, comment inside was correctly commented.

### CODE REVIEW

**Review by Paulb23 — CHANGES_REQUESTED** [review]
This breaks when using multi carets as it no longer keeps track of the last changed line. So if there are 2 carets on the same line, no comment will be toggled.

**Comment by jmb462** [comment]
> This breaks when using multi carets as it no longer keeps track of the last changed line. So if there are 2 carets on the same line, no comment will be toggled.

Oh sorry. I had misunderstood the purpose of the last_line variable. It should be better now.

multicarret

File: editor/code_editor.cpp [hunk 1]
```diff
@@ -1584,11 +1584,17 @@ void CodeTextEditor::toggle_inline_comment(const String &delimiter) {
...
 	for (const int &c1 : caret_edit_order) {
 		int from = _get_affected_lines_from(c1);
-		from += from == last_line ? 1 : 0;
+		from += from == last_line ? 1 + folded_to : 0;
 		int to = _get_affected_lines_to(c1);
 		last_line = to;
+		// If last line is folded, extends to the end of the folded section
+		if (text_editor->is_line_folded(to)) {
+			folded_to = text_editor->get_next_visible_line_offset_from(to + 1, 1) - 1;
+			to += folded_to;
```
Comment (Paulb23) [inline editor/code_editor.cpp:1596]: `last_line = to` above, does it need to be set after this instead?

Comment (jmb462) [reply editor/code_editor.cpp:1596]: I don't think so.

In the loop, ``last_line`` need to be the set at the real cursor line to prevent issue when pair number of carets are on the same line and would lead to comment and uncomment (and so no visible action will occur because the second (or any other pair) caret will undo what the first (or unpair) would have done)

**Review by Paulb23 — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.
