### PR TITLE
multiplayer - remove child on despawn instead of just queue_delete

### LINKED ISSUE #4432: `MultiplayerSpawner` - add/remove order should be preserved
### Describe the project you are working on

Real Time Strategy

### Describe the problem or limitation you are having in your project

To change maps, I am removing and re-adding a map node. However, the order that the MultiplayerSpawner actions are sent to the client does not seem to be deterministic, randomly leading to an error (if the nodes have the same name).

```py
# Remove the previous node named Map if it exists.
var old_map := get_node_or_null(^"Map")
if old_map != null:
	print("Removing old map")
	remove_child(old_map)
	old_map.queue_free()

# Workaround: Make a noticeable delay. Even awaiting process_frame twice is not always sufficient.
await get_tree().create_timer(0.1).timeout

# Create a new node named Map.
print("Adding new map")
var map := map_scene.instantiate()
add_child(map)
```

**Without the await timer**, an error is printed on the client when the spawner tries to add the new node:

```
ERROR: Condition "parent->has_node(name)" is true. Returning: ERR_INVALID_DATA
   at: on_spawn_receive (scene/multiplayer/scene_replication_interface.cpp:268)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Spawner jobs should happen in the order that they are added.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The above code should work without the workaround `await`.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I don't think it can be fully worked around as it seems to be a race condition. When the delay is replaced with `await`-ing two `process_frame`s, the code only works sometimes.

### Is there a reason why this should be core and not an add-on in the asset library?

`MultiplayerSpawner` is already part of core.

Unsure if this should be an issue or a proposal. I chose proposal to facilitate discussion. \
CC @Faless

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes https://github.com/godotengine/godot-proposals/issues/4432

CC @Faless

### CODE REVIEW

File: scene/multiplayer/scene_replication_interface.cpp [hunk 1]
```diff
@@ -309,6 +309,7 @@ Error SceneReplicationInterface::on_despawn_receive(int p_from, const uint8_t *p
 	Error err = rep_state->peer_del_remote(p_from, net_id, &node);
 	ERR_FAIL_COND_V(err != OK, err);
 	ERR_FAIL_COND_V(!node, ERR_BUG);
+	node->get_parent()->remove_child(node);
```
Comment (Faless) [inline scene/multiplayer/scene_replication_interface.cpp:312]: Better to also check `node->get_parent() != nullptr`, very unlikely but at least we'll be able to better catch bugs if they happen.

**Review by Faless — CHANGES_REQUESTED** [review]
I'm a bit worried by this, I fear it could have unexpected side effects.
We don't use this pattern anywhere in the engine, but I guess it's worth a try.
See my note on adding an extra check.

**Review by Faless — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
