### PR TITLE
Always create global class list, even if empty

### LINKED ISSUE #72451: Exporting project with no scripts raises error about `res://.godot/global_script_class_cache.cfg`
### Godot version

4.0 beta (e1648b3327431a09cc9498663fac483275eb711d)

### System information

Mageia 9, Linux

### Issue description

When exporting a project with no attached script (or with only a builtin GDScript), the following error is printed:
```
ERROR: Can't open file from path 'res://.godot/global_script_class_cache.cfg'.
   at: get_file_as_bytes (core/io/file_access.cpp:699)
```

And while the export succeeds, when running the project, it prints:
```
ERROR: Couldn't find the given section "" and key "list", and no default was given.
   at: get_value (core/io/config_file.cpp:86)
```

We should ensure that this file is always created, regardless of whether there are scripts to parse for class names or not. It should always contain at least `list=[]`.

### Steps to reproduce

- Create new project
- Create main scene with no script
- Export

### Minimal reproduction project

[NewProj.zip](https://github.com/godotengine/godot/files/10547125/NewProj.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #72451.

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -1138,7 +1138,7 @@ Array ProjectSettings::get_global_class_list() {
 	Ref<ConfigFile> cf;
 	cf.instantiate();
 	if (cf->load(get_global_class_list_path()) == OK) {
-		script_classes = cf->get_value("", "list");
+		script_classes = cf->get_value("", "list", Array());
```
Comment (akien-mga) [inline core/config/project_settings.cpp:1141]: This shouldn't be needed anymore since the other change makes sure to generate the file, but for good measure... :)

File: editor/editor_file_system.cpp [hunk 2]
```diff
@@ -1593,7 +1593,7 @@ void EditorFileSystem::_update_pending_script_classes() {
 		_update_script_classes();
 	} else {
 		// In case the class cache file was removed somehow, regenerate it.
-		if (ScriptServer::has_global_classes() && !FileAccess::exists(ScriptServer::get_global_class_cache_file_path())) {
```
Comment (KoBeWi) [inline editor/editor_file_system.cpp:1596]: `has_global_classes()` becomes unused after this PR.
