### PR TITLE
Warn when setting Control size inside ready()

### LINKED ISSUE #24859: Wrong position and size setters for Control nodes
**Godot version:**

3.1 alpha 5

**OS/device including version:**

Win 10

**Issue description:**

The item is not displayed correctly (see below)

**Steps to reproduce:**
1) Create root scene. (and make it main scene)
2) Create child Control
3) Make this child a external branch
4) Get into it.
5) Create a panel and repaint it
6) Create another control as the child of our control.
7) Add to new control panel
8) Create script and add his to Control Scene
9) Write in
```
extends Control

func _ready():
	$Control.rect_size = Vector2(
		1024,
		600
	)
	$Control.rect_global_position.x = -1024
```

(In the project settings the resolution is 1024*600)
8) Run Control Scene and see
9) And Run Main (root) Scene and see

You can see that when you start different scenes, the color changes. This is the Panel, whose size in the script has been changed to some ugly and increased by a couple of times.

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/2739968/Test.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Attempt to resolve #24859
Some project for testing:
[Test.zip](https://github.com/godotengine/godot/files/5304651/Test.zip)

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1662,6 +1668,11 @@ void Control::set_position(const Size2 &p_point, bool p_keep_margins) {
 }
 
 void Control::_set_size(const Size2 &p_size) {
+#ifdef DEBUG_ENABLED
+	if (data.size_warning) {
+		WARN_PRINT("Setting the size of Control inside _ready() is unreliable. Consider deferring it with set_deferred().");
```
Comment (akien-mga) [inline scene/gui/control.cpp:1673]: Note that this will also be printed for stuff that are before ready (`_init`, `_enter_tree`), so the message might be misleading.

Comment (KoBeWi) [reply scene/gui/control.cpp:1673]: How should it be changed then? `Setting the size of Control before it's fully initialized`?

Comment (capnm) [reply scene/gui/control.cpp:1673]: Adjusting the size of Controll node at startup time is unreliable ... ?

Comment (KoBeWi) [reply scene/gui/control.cpp:1673]: Is "startup" a precise term though? Someone might understand it as app startup.

Comment (capnm) [reply scene/gui/control.cpp:1673]: Adjusting the size of not initialized Control node is unreliable. ... ?

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -475,7 +479,9 @@ void Control::_notification(int p_notification) {
 		} break;
 		case NOTIFICATION_EXIT_TREE: {
 			get_viewport()->_gui_remove_control(this);
-
+		} break;
+		case NOTIFICATION_READY: {
+			connect("ready", callable_mp(this, &Control::_clear_size_warning), varray(), CONNECT_DEFERRED | CONNECT_ONESHOT);
```
Comment (capnm) [inline scene/gui/control.cpp:484]: How can this be ported to 3.2? The old version of signals prints errors.
`connect("ready", this, "_clear_size_warning", varray(), CONNECT_DEFERRED | CONNECT_ONESHOT);`

Comment (KoBeWi) [reply scene/gui/control.cpp:484]: `_clear_size_warning` needs to be bound to work in 3.2. It's one additional line in `bind_methods`.

**Comment by capnm** [comment]
Tested on the 3.2 branch, works as intended.
Thanks!
```
WARNING: Adjusting the size of not initialized Control node is unreliable. Consider deferring it with set_deferred().
     at: _set_size (scene/gui/control.cpp:1838)
(2048, 1200)
```

File: scene/gui/control.cpp [hunk 3]
```diff
@@ -1662,6 +1668,11 @@ void Control::set_position(const Size2 &p_point, bool p_keep_margins) {
 }
 
 void Control::_set_size(const Size2 &p_size) {
+#ifdef DEBUG_ENABLED
+	if (data.size_warning) {
+		WARN_PRINT("Adjusting the size of not initialized Control node is unreliable. Consider deferring it with set_deferred().");
```
Comment (akien-mga) [inline scene/gui/control.cpp:1673]:
```suggestion
		WARN_PRINT("Adjusting the size of Control node before they are fully initialized is unreliable. Consider deferring it with set_deferred().");
```

**Review by groud — APPROVED** [review]
Sorry for the late review. It needs a rebase but I'm ok with the idea.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by akien-mga** [comment]
I've reverted the `3.2` cherry-pick for now to solve #46376.

Keeping it in `master` where we can improve, and eventually cherry-pick again for 3.2.5. Here are some suggestions:

- Warning should be only in the specific cases which are problematic (to be determined)
- Should likely use `WARN_PRINT_ONCE` to avoid spam
- Signal connections for the warning's logic should likely also be made `DEBUG_ENABLED` only
