### PR TITLE
Fix Windows `OS.get_unique_id()` null termination issue

### LINKED ISSUE #106012: Windows OS.get_unique_id() bug
### Tested versions

Git commit hash: 931820d33cbc38328e4014d65dd62c359b5116fc
Git commit hash short: 931820d33c

### System information

Windows 10 - Godot Engine v4.5.dev.custom_build.931820d33 Vulkan 1.4.303 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 4080 SUPER

### Issue description

Hello. I got the issue with `OS.get_unique_id()`. The issue persists only on Windows machine (on Mac machine it is fine). After I print() the value of `OS.get_unique_id()`, Godot stops displaying any further output in the console (see image 1). However, if I don't print `OS.get_unique_id()` then all other print() statements will be displayed in the console as expected, like `print("HELLO")` (see image 2). I also send the value of `OS.get_unique_id()` to the server and print it there (see Image 3). What I noticed, that the string has some strange character at the end. I suspect that this character might be causing the Godot console to behave incorrectly and suppress further output. Additionally, I checked the log file (see image 4) and it does contain the output of `print("HELLO")`, even after printing `OS.get_unique_id()`. However, it also includes that mysterious trailing character. Could this be a bug? Also, why is the unique Windows ID enclosed in curly brackets {}?

Image
Image
Image
Image

### Steps to reproduce

Simply write the code as shown in Image 1 (uploaded in the "Issue Description") or use the provided demo project, then check the console log - print("HELLO") will not be visible. Also, check logs and you will see that Windows unique ID contains a special character at the end. Also, a unique Windows ID is enclosed in curly brackets

### Minimal reproduction project (MRP)

As you can see in this demo project, "HELLO" is not being printed. Also, the length is shown as 39, but it's actually 38 (due to a hidden character at the end). Additionally, the unique Windows ID is enclosed in curly brackets.
Demo project: [test-device-unique-id.zip](https://github.com/user-attachments/files/20010458/test-device-unique-id.zip)

Image

### PR DESCRIPTION
**Pull request by uno1982**
Fixes: #106012 

It appears the function return from the windows API included a null termination? 
I've commented this specific segment of code with a safety to handle this. 
There was quite a bit of changes between 4.4 and 4.5-Dev around print() and print_rich() that created some difficulty in hunting the exact cause of the editor output hang while the console exe continued to function

This fix addresses the length, output and concat, issues. 

Before:
image

After:
image

### CODE REVIEW

File: platform/windows/os_windows.cpp [hunk 1]
```diff
@@ -2260,6 +2260,26 @@ String OS_Windows::get_processor_name() const {
...
 }
 
+String OS_Windows::get_unique_id() const {
+	HW_PROFILE_INFOA HwProfInfo;
+	ERR_FAIL_COND_V(!GetCurrentHwProfileA(&HwProfInfo), "");
+	
+	// Create a string from the raw GUID data first
+	String guid_str = String(HwProfInfo.szHwProfileGuid);
+	
+	// Remove any potential null characters within the string
```
Comment (AThousandShips) [inline platform/windows/os_windows.cpp:2270]: The string constructor skips any null characters, so this shouldn't be needed, I think just removing the length part of the original is the proper solution

File: platform/windows/os_windows.cpp [hunk 2]
```diff
@@ -2260,6 +2260,17 @@ String OS_Windows::get_processor_name() const {
 	}
 }
 
+String OS_Windows::get_unique_id() const {
+	HW_PROFILE_INFOA HwProfInfo;
+	ERR_FAIL_COND_V(!GetCurrentHwProfileA(&HwProfInfo), "");
+
+	// Windows API returns a null-terminated GUID string
+	String guid_str = String(HwProfInfo.szHwProfileGuid);
```
Comment (AThousandShips) [inline platform/windows/os_windows.cpp:2268]: This assumes the string is latin1, the original used `String::ascii`, is this guaranteed to be the case? From the documentation for this type:
> The winbase.h header defines HW_PROFILE_INFO as an alias that automatically selects the ANSI or Unicode version of this function based on the definition of the UNICODE preprocessor constant. Mixing usage of the encoding-neutral alias with code that is not encoding-neutral can lead to mismatches that result in compilation or runtime errors.

From the format it should just be valid latin1 but good to make sure

Comment (AThousandShips) [reply platform/windows/os_windows.cpp]: Did you discover something about this? You made the change and then reverted it

Comment (uno1982) [reply platform/windows/os_windows.cpp]: I removed span but when using String:ascii it fails to compile properly for all test

Comment (uno1982) [reply platform/windows/os_windows.cpp]: It was getting late and some checks failed so I reverted back to the passing checks.

Comment (uno1982) [reply platform/windows/os_windows.cpp]: https://github.com/godotengine/godot/compare/21f05d2d975cc3f08ca521c2938507030eb7889a..eab57c5e2b7d26fc4e79065a1694c9e4470a476b

This failed checks for some platforms

Comment (uno1982) [reply platform/windows/os_windows.cpp]: platform\windows\os_windows.cpp(2268): error C2352: 'String::ascii': a call of a non-static member function requires an object. 
Changing to return String().ascii(HwProfInfo.szHwProfileGuid);
resulted in
platform\windows\os_windows.cpp(2268): error C2440: 'return': cannot convert from 'CharString' to 'String'

digging deeper

Comment (AThousandShips) [reply platform/windows/os_windows.cpp]: That is because you need to call `String::ascii(Span(HwProfInfo.szHwProfileGuid, strlen(HwProfInfo.szHwProfileGuid))` I'd say, but I think the core issue here needs to be assessed as the string should be of valid length when using the constant

Comment (uno1982) [reply platform/windows/os_windows.cpp]: I should have the expected syntax in a second 👍

**Comment by uno1982** [comment]
Just following up @AThousandShips I think we are good here right? OP of the initial report suggested the issue was resolved with this PR as well. :) Let me know if I can assist further. 👍

**Comment by AThousandShips** [comment]
I think it looks alright, but I'm not experienced on the Windows side so this needs a review by that team

**Review by bruvzg — APPROVED** [review]
Windows docs use:
```_tprintf(TEXT("Profile Guid = %s\n"), HwProfInfo.szHwProfileGuid);```
as a usage example, so a null terminated string seems to be expected.

But to be 100% safe, we can check both null termination and buffer size:

```c++
return String::ascii(Span<char>(HwProfInfo.szHwProfileGuid, strnlen(HwProfInfo.szHwProfileGuid, HW_PROFILE_GUIDLEN)));
```

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by uno1982** [comment]
> Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

Should see this squashed

**Review by akien-mga — COMMENTED** [review]
Apologies for the delay - I had a couple review comments queued which I forgot to submit.

**Review by akien-mga — APPROVED** [review]
