### PR TITLE
Fix specialization constant patching on D3D12.

### LINKED ISSUE #100138: Bicubic Lightmap Filtering Fails to Engage Under DX12
### Tested versions

Tested in v4.4.dev (47bc374ed), built locally.

### System information

Godot v4.4.dev (47bc374ed) - Windows 10.0.19045 - Direct3D 12 (Forward+) - dedicated Radeon RX 5500 XT (Advanced Micro Devices, Inc.; 32.0.11027.1003) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

### Issue description

When using the DX12 backend, lightmaps never receive bicubic filtering even with the `Use Bicubic Filter` setting enabled. This is not an issue when using Vulkan, where the filtering switches to bicubic as expected.

| Vulkan | DirectX 12 |
|--------|--------|
| Image | Image |

Additionally, I was able to force bicubic filtering by changing line `1653` in `scene_forward_clustered.glsl` from
`if (sc_use_lightmap_bicubic_filter()) {`
to
`if (sc_use_lightmap_bicubic_filter() || true) {`
so I believe this is an issue of the relevant flag somehow not being set.

When starting up the test project, the console also prints `drivers/d3d12/rendering_device_driver_d3d12.cpp:2873 - Condition "int_value & (1 << 31)" is true. Returning: 0` eight times, then does so again whenever `Use Bicubic Filter` is toggled on or off.
I also noticed in `scene_forward_clustered_inc.glsl` that this flag, along with several others, is pulled conditionally from either a push constant or a specialization constant based on whether ubershaders are being used, which may be relevant, but I didn't see anything else suspicious following the trail back to where `Use Bicubic Filter` is read from the project settings.

### Steps to reproduce

Create a 3D scene, add some `MeshInstances` to receive lightmaps and a light source to be baked, add a `LightmapGI` node and bake it.
In **Project Settings**, under **Rendering/Rendering Device** set `Driver` to `d3d12`, and under **Rendering/Lightmapping** ensure `Use Bicubic Filter` is toggled on.

### Minimal reproduction project (MRP)

[bicubic-lightmap-bug-mrp.zip](https://github.com/user-attachments/files/18047736/bicubic-lightmap-bug-mrp.zip)

### PR DESCRIPTION
**Pull request by blueskythlikesclouds**
Fixes #100138.

The specialization constant patching code was rejecting signed values, assuming it needed to set the MSB to respect LLVM IR's VBR encoding. However, as explained [here](https://llvm.org/docs/BitCodeFormat.html#variable-width-integer), the contents of the integer actually do not matter at all, because we can just keep emitting continue bits even if the bits are all zero.

Godot already uses an appropriate sentinel value to enforce 32 bits in the output bytecode, so this approach works fine.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
seems fine to me

File: drivers/d3d12/rendering_shader_container_d3d12.cpp [hunk 1]
```diff
@@ -94,28 +94,26 @@ uint32_t RenderingDXIL::patch_specialization_constant(
 		const uint64_t (&p_stages_bit_offsets)[D3D12_BITCODE_OFFSETS_NUM_STAGES],
 		HashMap<RenderingDeviceCommons::ShaderStage, Vector<uint8_t>> &r_stages_bytecodes,
 		bool p_is_first_patch) {
-	uint32_t patch_val = 0;
+	int64_t patch_val = 0;
```
Comment (Repiteo) [inline drivers/d3d12/rendering_shader_container_d3d12.cpp:97]:
```suggestion
	uint64_t patch_val = 0;
```

**Review by Repiteo — CHANGES_REQUESTED** [review]
Local dev builds fail from the sign change. Given the lambda already expects a `uint64_t`, we should be doing the same with the base variable

File: drivers/d3d12/rendering_shader_container_d3d12.cpp
Comment (Repiteo) [inline drivers/d3d12/rendering_shader_container_d3d12.cpp]: Alternatively:
```suggestion
		DEV_ASSERT(readback_patch_val == (uint64_t)patch_val);
```

File: drivers/d3d12/rendering_shader_container_d3d12.cpp (hunk 1 above)
Comment (blueskythlikesclouds) [reply drivers/d3d12/rendering_shader_container_d3d12.cpp:97]: I'm relying on sign extension behavior, the if statement also expects a signed value. I'll apply your other suggestion.

**Review by Repiteo — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
