### PR TITLE
Fixed the remove_line function in richtextlabel. It was totally broken

### LINKED ISSUE #21037: Rich Text Label : remove_line don't remove all the line
Godot version: 3.0.6
OS: Windows 7

Steps to reproduce:
Create new scene, add Node, add RichTextLabel child, expend it a little to see text write in, add gdScript on RTL.

RichTextLabel.gd:
```gdscript
extends RichTextLabel

func _ready():
	push_color(ColorN("red", 1))
	add_text("Gobelin")
	pop()

	add_text(" appear.")

	remove_line(0)

	pass
```

Issue description:
When you start scene you expect to see nothing but " appear." is write on screen.

*Bugsquad edit: code formatting*

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed the remove_line function in richtextlabel. It was totally broken

This fixes #21037

### CODE REVIEW

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -1423,18 +1423,28 @@ bool RichTextLabel::remove_line(const int p_line) {
...
 
-	if (current->subitems[lines]->type != ITEM_NEWLINE)
-		_remove_item(current->subitems[lines], current->subitems[lines]->line, lines);
+	bool was_newline = false;
+	while (i < current->subitems.size()) {
+		was_newline = current->subitems[i]->type == ITEM_NEWLINE;
+		_remove_item(current->subitems[i], current->subitems[i]->line, p_line);
+		if (was_newline)
+			break;
+	}
```
Comment (malbach) [inline scene/gui/rich_text_label.cpp]: I think you forgot i++ / i-- or something similar in this loop, no ?

**Comment by akien-mga** [comment]
Thanks!
