### PR TITLE
Fixes for documentation search

### LINKED ISSUE #32687: Search previous unexpected behaviour in built-in docs
**Godot version:**
3.1

**Issue description:**
When you search something in the documentation of Godot's built-in docs, you can use "Enter" key to search for next occurrence and "Shift + Enter" to search for the previous occourence(you can also use the GUI arrow buttons). When searching for previous a unexpected behaviour occours, rather than shoing the previous result of the search, it shows the first result in previous "segment" of the text(see GIF below).

**Steps to reproduce:**

1. Open some doc in the editor
2. Search something which occours multiple times within each segment of the opened doc
3. Click the search next arrow until you pass a segment where your search term occoured more than once
4. Click the search previous arrow and step back through the segment where your search term occoured more than once

### LINKED ISSUE #44991: Help pages search jumping doesn't work
**Godot version:**

c7b4514

**Steps to reproduce:**
1. Open any search page in the editor
2. Search something so the result count appears at the bottom
3. Try using the navigation arrows to jump to result

Searching nor pressing arrows doesn't scroll.

### PR DESCRIPTION
**Pull request by megalobyte**
Fixes #44991
*Bugsquad edit:* Fixes #32687

Fixes a couple of issues when using `FindBar`:
1. Find next result
2. Find previous result
3. Wrap around
4. Update the scroll bar so that the next result is displayed (not centered, could be improved)  
5. `FindBar` does not use sensitive matches, so use case insensitive search when counting results

I used `Transform2D` as the sample documentation for testing.

### CODE REVIEW

**Comment by megalobyte** [comment]
Added clang format. The search can now find multiple results in the same line. It's still unable to find multiple results in a table. 

I'm tempted to revert the changes that were introduced with the RichTextLabel refactor. It makes more sense to me to iterate through the different items, rather than by each line. Any ideas as to what this search method supports that the previous method didn't?

**Comment by megalobyte** [comment]
This branch isn't currently ready for review. I found another bug with the previous search, but I have a fix for it on my local branch. Also, I may have a fix for the table search. I'm going to try to implement it when I get home

**Comment by pycbouh** [comment]
You can mark your PR as draft in case you want to work a bit more on it.

**Comment by megalobyte** [comment]
I think I got everything working. At the very least, none of the edge cases I came across had any issues :sweat:

**Comment by megalobyte** [comment]
By the way, is there a story for `Shift+Enter` not invoking previous search? I know the source of the problem. I just don't know if I should add `Shift+Enter` to `ui_text_newline`, make a new input event, or add it to a different input event that I overlooked.

**Comment by akien-mga** [comment]
> By the way, is there a story for `Shift+Enter` not invoking previous search? I know the source of the problem. I just don't know if I should add `Shift+Enter` to `ui_text_newline`, make a new input event, or add it to a different input event that I overlooked.

There should probably be `ui_text_search_next` and `ui_text_search_previous` shortcuts. Using `ui_text_newline` for "Search Next" is probably wrong in the first place.

File: scene/gui/rich_text_label.cpp [hunk 1]
```diff
@@ -3511,23 +3533,81 @@ bool RichTextLabel::_search_line(ItemFrame *p_frame, int p_line, const String &p
...
-				update();
-				return true;
+		// First check to see if other results exist in current line
+		char_idx = p_search_previous ? selection.from_char - 1 : selection.to_char;
+		if (!(p_search_previous && char_idx < 0) &&
+				_search_line(selection.from_frame, selection.from_line, p_string, char_idx, p_search_previous)) {
+			scroll_to_line(selection.from_frame->line + selection.from_line);
+			update();
+			return true;
+		};
```
Comment (akien-mga) [inline scene/gui/rich_text_label.cpp:3552]: Unnecessary semicolon.

**Comment by megalobyte** [comment]
> > By the way, is there a story for `Shift+Enter` not invoking previous search? I know the source of the problem. I just don't know if I should add `Shift+Enter` to `ui_text_newline`, make a new input event, or add it to a different input event that I overlooked.
> 
> There should probably be `ui_text_search_next` and `ui_text_search_previous` shortcuts. Using `ui_text_newline` for "Search Next" is probably wrong in the first place.

Sounds good. The changes were pretty minimal, so I took the liberty of adding them to this PR since adding them seemed relevant enough

File: scene/gui/line_edit.cpp [hunk 2]
```diff
@@ -357,8 +357,8 @@ void LineEdit::_gui_input(Ref<InputEvent> p_event) {
 			}
 		}
 
-		// Default is ENTER, KP_ENTER. Cannot use ui_accept as default includes SPACE
-		if (k->is_action("ui_text_newline", true)) {
+		// Default is ENTER. Cannot use ui_accept as default includes SPACE
+		if (k->is_action("ui_text_search_next", true) || k->is_action("ui_text_search_previous", true)) {
```
Comment (Paulb23) [inline scene/gui/line_edit.cpp:361]: This is tricky, as search is misleading.

I'm thinking about `ui_text_submit` and renaming the signal to `text_submitted` so they align.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Overall LGTM.

Minor nitpick, as I'm not sure on the new shortcut naming as `LineEdit` is a generic node.

File: scene/gui/rich_text_label.h [hunk 3]
```diff
@@ -392,7 +392,8 @@ class RichTextLabel : public Control {
 	void _find_click(ItemFrame *p_frame, const Point2i &p_click, ItemFrame **r_click_frame = nullptr, int *r_click_line = nullptr, Item **r_click_item = nullptr, int *r_click_char = nullptr, bool *r_outside = nullptr);
 
 	String _get_line_text(ItemFrame *p_frame, int p_line, Selection p_sel) const;
-	bool _search_line(ItemFrame *p_frame, int p_line, const String &p_string, Item *p_from, Item *p_to);
+	bool _search_line(ItemFrame *p_frame, int p_line, const String &p_string, int char_idx, bool reverse_search);
```
Comment (Paulb23) [inline scene/gui/rich_text_label.h:395]: `char_idx` and `reverse_search` need to be preficed with `p_` ditto for `_search_table`

File: scene/gui/rich_text_label.cpp [hunk 4]
```diff
@@ -3511,23 +3533,81 @@ bool RichTextLabel::_search_line(ItemFrame *p_frame, int p_line, const String &p
...
-		for (int i = 0; i < main->lines.size(); i++) {
-			if (_search_line(main, i, p_string, nullptr, nullptr)) {
-				update();
-				return true;
+		char_idx = p_search_previous ? -1 : 0;
+
+		// Next, check to see if the current search result is in a table
+		if (selection.from_frame->parent != nullptr && selection.from_frame->parent->type == ITEM_TABLE) {
+			// Find last search result in table
+			ItemTable *p_table = static_cast<ItemTable *>(selection.from_frame->parent);
```
Comment (Paulb23) [inline scene/gui/rich_text_label.cpp:3558]: `p_` is for params so needs renaming to `parent_table`? same for `p_element`

File: scene/gui/rich_text_label.h (hunk 3 above)
Comment (megalobyte) [reply scene/gui/rich_text_label.h:395]: I thought the `p_` prefix is used to denote a pointer. Does `p_` mean something else in godot?

File: scene/gui/line_edit.cpp (hunk 2 above)
Comment (megalobyte) [reply scene/gui/line_edit.cpp]: What are your thoughts about naming it to `ui_text_entered`? I'm a bit hesitant to rename the signal to `text_submitted`, since a lot of other functions are connecting to `text_entered`

Comment (Paulb23) [reply scene/gui/line_edit.cpp]: Yeah the problem with `ui_text_entered` is that it somewhat implies that text has been entered, rather then the `enter` key has been pressed. Given that we're making it a configurable shortcut, it may not event be the `enter` key, so would be even more confusing.

Comment (megalobyte) [reply scene/gui/line_edit.cpp]: Agreed, it's definitely not ideal. So you think I should rename the signal from `text_entered` to `text_submitted` and update all the files that use `LineEdit`? Or would it be better to just add a new signal called `text_submitted`?

Comment (Paulb23) [reply scene/gui/line_edit.cpp]: Go for the rename, this is for 4.0 only so it's okay to break compat. 

Though probably worth doing the rename as a separate commit.

File: doc/classes/ProjectSettings.xml [hunk 5]
```diff
@@ -733,6 +733,10 @@
 		</member>
 		<member name="input/ui_text_scroll_up.OSX" type="Dictionary" setter="" getter="">
 		</member>
+		<member name="input/ui_text_search_next" type="Dictionary" setter="" getter="">
+		</member>
+		<member name="input/ui_text_search_previous" type="Dictionary" setter="" getter="">
+		</member>
```
Comment (EricEzaM) [inline doc/classes/ProjectSettings.xml:739]: How come these are added to the doco? I can't find references to them anywhere else.

File: core/input/input_map.cpp [hunk 6]
```diff
@@ -667,6 +668,11 @@ const OrderedHashMap<String, List<Ref<InputEvent>>> &InputMap::get_builtins() {
 	inputs.push_back(InputEventKey::create_reference(KEY_MENU));
 	default_builtin_cache.insert("ui_menu", inputs);
 
+	inputs = List<Ref<InputEvent>>();
+	inputs.push_back(InputEventKey::create_reference(KEY_ENTER));
+	inputs.push_back(InputEventKey::create_reference(KEY_ENTER | KEY_MASK_SHIFT));
+	default_builtin_cache.insert("ui_text_enter", inputs);
+
```
Comment (EricEzaM) [inline core/input/input_map.cpp:675]: It seems wrong to have Shift+Enter for the "Text Entered" shortcut...

I think a better solution could be to only have `KEY_ENTER` and `KEY_KP_ENTER` assigned to this, and in the `is_action` check in LineEdit do a non-exact check (i.e. second param is `false`). This would allow for Shift-Enter to trigger the signal, and then the current logic downstream (checking if Shift is pressed) would still work as it currently does.

File: scene/gui/line_edit.cpp [hunk 7]
```diff
@@ -357,8 +357,8 @@ void LineEdit::_gui_input(Ref<InputEvent> p_event) {
 			}
 		}
 
-		// Default is ENTER, KP_ENTER. Cannot use ui_accept as default includes SPACE
-		if (k->is_action("ui_text_newline", true)) {
+		// Default is ENTER. Cannot use ui_accept as default includes SPACE
+		if (k->is_action("ui_text_enter", true)) {
```
Comment (EricEzaM) [inline scene/gui/line_edit.cpp:361]:
```suggestion
		// Default is ENTER and KP_ENTER. Cannot use ui_accept as default includes SPACE
		if (k->is_action("ui_text_enter", false)) {
```

This is the change I am talking about it my comment above.

**Review by EricEzaM — CHANGES_REQUESTED** [review]

File: scene/gui/line_edit.cpp (hunk 2 above)
Comment (megalobyte) [reply scene/gui/line_edit.cpp]: Okay. I will keep the signal name `text_entered` for this PR. I will mark this comment resolved once I submit a follow on PR that renames `text_entered` to `text_submitted`

File: scene/gui/rich_text_label.cpp (hunk 4 above)
Comment (megalobyte) [reply scene/gui/rich_text_label.cpp]: This should be fixed with the latest push

File: doc/classes/ProjectSettings.xml (hunk 5 above)
Comment (megalobyte) [reply doc/classes/ProjectSettings.xml:739]: These shortcuts were added in a previous commit. I renamed them to address feedback, but forgot to run the doctool.

File: core/input/input_map.cpp (hunk 6 above)
Comment (megalobyte) [reply core/input/input_map.cpp]: That is good to know! I'm still learning how godot works, but I should have looked more closely at how `is_action` works. Will be updated in latest push

File: scene/gui/line_edit.cpp (hunk 7 above)
Comment (megalobyte) [reply scene/gui/line_edit.cpp]: Added in latest commit

File: scene/gui/line_edit.cpp (hunk 2 above)
Comment (megalobyte) [reply scene/gui/line_edit.cpp]: Forget the extra PR. I forgot we can squash the commit after the review if everything gets approved

File: editor/animation_track_editor.cpp [hunk 8]
```diff
@@ -2725,7 +2725,7 @@ void AnimationTrackEdit::_gui_input(const Ref<InputEvent> &p_event) {
 			path = memnew(LineEdit);
 			path_popup->add_child(path);
 			path->set_anchors_and_offsets_preset(PRESET_WIDE);
-			path->connect("text_entered", callable_mp(this, &AnimationTrackEdit::_path_entered));
+			path->connect("text_submitted", callable_mp(this, &AnimationTrackEdit::_path_entered));
```
Comment (Paulb23) [inline editor/animation_track_editor.cpp:2728]: Missed `_path_entered` to `_path_submitted`

**Review by Paulb23 — COMMENTED** [review]
Couple small misses of `text_entered` in docs `expression.xml`, and one inline.

After that LGTM.

File: editor/animation_track_editor.cpp (hunk 8 above)
Comment (megalobyte) [reply editor/animation_track_editor.cpp]: Good catch! I should have paid more attention to my exclusion search filter :facepalm: 

Updated `expression.xml` and `animation_track_editor.cpp`. I've also squashed the commits into one, but I saved a branch locally that preserves the separate commits in case some one wants to review the commits separately

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
FYI, the email used to author your commit doesn't seem to be linked to your GitHub account (see header of https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/49258.patch). It's not a problem for Git or GitHub, but if you want to claim ownership of the commit for street creds, you can add it as secondary email in your profile.

**Comment by megalobyte** [comment]
@akien-mga Thanks. I thought I updated my email address, but I guess not. I'll update it when I get home. Please postpone merging until then

**Review by EricEzaM — APPROVED** [review]
Changes I suggested were incorporated, they look good.

**Comment by akien-mga** [comment]
Thanks!

> I'll update it when I get home. Please postpone merging until then

Oops, sorry about that. Merged while on phone and I just recalled this after hitting the button.

**Comment by megalobyte** [comment]
No worries. I just added the email address to my github account like you suggested. Thanks
