### PR TITLE
Fix unexpected editor dependency

### LINKED ISSUE #69663: Can't compile debug template on latest master
### Godot version

v4.0.beta.custom_build [43e9ca40f]

### System information

Manjaro Linux

### Issue description

Fails to compile with:

`scene/debugger/scene_debugger.cpp: In static member function 'static void SceneDebugger::_save_node(ObjectID, const String&)':
scene/debugger/scene_debugger.cpp:224:28: error: 'class Node' has no member named 'duplicate_from_editor'
  224 |         Node *copy = node->duplicate_from_editor(duplimap);
      |                            ^~~~~~~~~~~~~~~~~~~~~
`

### Steps to reproduce

just compile with  `scons target=template_debug arch=x86_64 -j "$(nproc)"`

### Minimal reproduction project

Not needed

### PR DESCRIPTION
**Pull request by KoBeWi**
See https://github.com/godotengine/godot/pull/65228#issuecomment-1338859262

`duplicate()` and `duplicate_from_editor()` are a bit different, but *hopefully* it doesn't matter that much when saving a scene. I think the only way to call `_save_node()` outside editor builds is to send a custom message to the debugger.

- Fixes #69663

### CODE REVIEW

File: scene/debugger/scene_debugger.cpp [hunk 1]
```diff
@@ -221,7 +221,11 @@ void SceneDebugger::_save_node(ObjectID id, const String &p_path) {
 	ERR_FAIL_COND(!node);
 
 	HashMap<const Node *, Node *> duplimap;
+#ifdef TOOLS_ENABLED
```
Comment (akien-mga) [inline scene/debugger/scene_debugger.cpp:224]: You don't need `duplimap` in template build, so it can go inside the `TOOLS_ENABLED`.

Though it's not used *at all*, so you could check if the method supports just passing a nullptr instead of allocating and filling a hashmap for nothing.

Comment (KoBeWi) [reply scene/debugger/scene_debugger.cpp:223]: It can't be null, because it's passed as reference.

Comment (akien-mga) [reply scene/debugger/scene_debugger.cpp:223]: Looks like it still needs to be defined in the scope first to be passed as reference.

Comment (KoBeWi) [reply scene/debugger/scene_debugger.cpp:223]: But the same code is used in `duplicate_from_editor()` :/ (it's an overload for method that takes 2 hashmaps)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by nikitalita** [comment]
Thanks for fixing this; The CI doesn't do `template_debug` builds currently, and this would have been caught if it were so. Consider adding it to the matrix?
