### PR TITLE
Fix `FOCUS_ACCESSIBILITY` grabbing focus when it is not supposed to, forward `GraphNode` key input to `GraphEdit`.

### LINKED ISSUE #105591: [Bisected] GraphEdit shortcut input (delete, copy, etc) doesn't work
### Tested versions

4.5, Bisected to b106dfd4f9acbc910e327a10ffdb86fabefcaa61 #76829
Not reproducible in 4.4

### System information

Godot v4.5.dev.mono - EndeavourOS  SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:59 +0000 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Mobile) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 4800U with Radeon Graphics (16 threads)

### Issue description

Can't use shortcut to delete, copy&paste or duplicate GraphNode In GraphEdit.

### Steps to reproduce

Create a VisualShader and open the GraphEdit, add a node and select it, try to press `Delete`, `Ctrl + D` or `Ctrl + C` `Ctrl + V`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
- Fixes `FOCUS_ACCESSIBILITY` grabbing focus on click even if screen reader is not active.
- Forwards key input from focused `GraphNode` (can have keyboard focus when screen reader is active) to the `GraphEdit` (which is handling copy-paste-delete shortcuts).

Fixes https://github.com/godotengine/godot/issues/105591

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -2270,7 +2270,8 @@ Control *Control::find_next_valid_focus() const {
 		ERR_FAIL_NULL_V_MSG(n, nullptr, "Next focus node path is invalid: '" + data.focus_next + "'.");
 		Control *c = Object::cast_to<Control>(n);
 		ERR_FAIL_NULL_V_MSG(c, nullptr, "Next focus node is not a control: '" + n->get_name() + "'.");
-		if (c->is_visible_in_tree() && c->get_focus_mode_with_override() != FOCUS_NONE) {
+		bool ac_enabled = c->get_tree() && c->get_tree()->is_accessibility_enabled();
+		if (c->is_visible_in_tree() && ((c->get_focus_mode_with_override() == FOCUS_ALL) || (c->get_focus_mode_with_override() == FOCUS_CLICK) || (ac_enabled && c->get_focus_mode_with_override() == FOCUS_ACCESSIBILITY))) {
```
Comment (KoBeWi) [inline scene/gui/control.cpp:2274]: This repeats multiple times. It should be a method.

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -2270,7 +2270,8 @@ Control *Control::find_next_valid_focus() const {
 		ERR_FAIL_NULL_V_MSG(n, nullptr, "Next focus node path is invalid: '" + data.focus_next + "'.");
 		Control *c = Object::cast_to<Control>(n);
 		ERR_FAIL_NULL_V_MSG(c, nullptr, "Next focus node is not a control: '" + n->get_name() + "'.");
-		if (c->is_visible_in_tree() && c->get_focus_mode_with_override() != FOCUS_NONE) {
+		bool ac_enabled = c->get_tree() && c->get_tree()->is_accessibility_enabled();
```
Comment (KoBeWi) [inline scene/gui/control.cpp:2273]:
```suggestion
		bool ac_enabled = c->is_inside_tree() && c->get_tree()->is_accessibility_enabled();
```

File: scene/gui/control.cpp (hunk 1 above)
Comment (bruvzg) [reply scene/gui/control.cpp]: Move it to `Control::_is_focusable()`.

File: scene/gui/control.cpp [hunk 3]
```diff
@@ -2158,6 +2158,11 @@ Control::FocusBehaviorRecursive Control::get_focus_behavior_recursive() const {
 	return data.focus_behavior_recursive;
 }
 
+bool Control::_is_focusable() const {
+	bool ac_enabled = is_inside_tree() && get_tree()->is_accessibility_enabled();
+	return (is_visible_in_tree() && ((get_focus_mode_with_override() == FOCUS_ALL) || (get_focus_mode_with_override() == FOCUS_CLICK) || (ac_enabled && get_focus_mode_with_override() == FOCUS_ACCESSIBILITY)));
```
Comment (KoBeWi) [inline scene/gui/control.cpp:2163]: I didn't notice earlier, but allowing FOCUS_CLICK here is wrong and it wasn't there before. E.g. `find_next_valid_focus()` is used for joypad focus, while this mode should only allow mouse button focus.

Comment (bruvzg) [reply scene/gui/control.cpp:2163]: `find_next_valid_focus()` is documented as `Finds the next [Control] that can receive the focus.`, and was using `!= FOCUS_NONE` before, so it should handle `FOCUS_CLICK` exactly the same as it was.

Comment (KoBeWi) [reply scene/gui/control.cpp:2163]: Ah right .-.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
