### PR TITLE
Use MOUSE_FILTER_PASS for all containers

### LINKED ISSUE #34933: CenterContainer blocks parent from receiving drag and drop
**Godot version:**
Godot (Mono*) 3.2 Beta 5
*The reproduction project uses GDScript to demonstrate the issue

**OS/device including version:**
Manjaro Linux x86_64

**Issue description:**
When the mouse drag is released over a CenterContainer it prevents its parent from receiving the drag data.

**Steps to reproduce:**
See reproduction project + explanation

**Minimal reproduction project:**
[DragAndDrop.zip](https://github.com/godotengine/godot/files/4037238/DragAndDrop.zip)
When dragging on the grey Panel the number `42` is given to Godot as the drag data. When it is released on the left side of the screen the HBoxContainer receives this and prints it. However when released on the right side of the screen the CenterContainer instead blocks it. The VBoxContainers on both sides of the screen do not exhibit this behavior.

### PR DESCRIPTION
**Pull request by akien-mga**
Containers are meant to forward mouse input to their the Controls
they contain.

Fixes #34933.

---

Putting this up for discussion, I haven't thoroughly tested yet.

Apart from `GridContainer` and `BoxContainer`-derived classes which already defaulted to `PASS`, this changes the behavior for `CenterContainer`, `MarginContainer`, `PanelContainer`, `ScrollContainer`, `SplitContainer`, `TabContainer`, `ViewportContainer` and the base `Container`. Might have unforeseen consequences if nobody noticed this discrepancy in 6 years.

### CODE REVIEW

**Comment by akien-mga** [comment]
Related: #24083 (but that one would be for 4.0).

**Comment by YeldhamDev** [comment]
Parts of the editor code that sets the filtering to pass in containers should be removed too, these are the ones that I found at first glance:
https://github.com/godotengine/godot/blob/33be750634cffe577df4c97963124f27e65e6549/editor/editor_audio_buses.cpp#L859
https://github.com/godotengine/godot/blob/33be750634cffe577df4c97963124f27e65e6549/editor/plugins/asset_library_editor_plugin.cpp#L1455

**Comment by akien-mga** [comment]
Thanks, removed all occurrences I found in `editor/` and `scene/` (notably `GraphNode` which is a container too).

File: scene/gui/graph_edit.cpp [hunk 1]
```diff
@@ -1335,7 +1334,6 @@ GraphEdit::GraphEdit() {
 	top_layer->set_mouse_filter(MOUSE_FILTER_PASS);
 	top_layer->set_anchors_and_margins_preset(Control::PRESET_WIDE);
 	top_layer->connect("draw", this, "_top_layer_draw");
-	top_layer->set_mouse_filter(MOUSE_FILTER_PASS);
```
Comment (akien-mga) [inline scene/gui/graph_edit.cpp]: This one is not a Container, but the mouse filter was already set to `Pass` on line 1335.
