### PR TITLE
Fix wrong children range when duplicating node

### LINKED ISSUE #105596: AcceptDialog/ConfirmationDialog children do not duplicate.
### Tested versions

- 2d3bdcac35ac22ee6c4d5d5edc88ba947d0659d5 - reproducible
- 4.4.1 - Not reproducible

### System information

Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 10 Apr 2025 18:43:59 +0000 on X11 - X11 display driver, Single-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 19.1.7, DRM 3.61, 6.14.2-arch1-1) - AMD Ryzen 9 5950X 16-Core Processor (32 threads)

### Issue description

Duplicating AcceptDialog/ConfirmationDialog nodes with children will yield the following message:

```
ERROR: Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
   at: get_child (scene/main/node.cpp:1946)
ERROR: Child node disappeared while duplicating.
   at: _duplicate_properties (scene/main/node.cpp:3194)
```

### Steps to reproduce

- Open MRP's main scene.
- Click on the node named "DuplicateBugsOutHere" and press Ctrl-D to generate the error message shown previously.
- Changing the type of this node to AcceptDialog and attempting to duplicate will yield the same error.
- Curiously, after changing the type of this node to Window, duplicate works normally but only under that type.

### Minimal reproduction project (MRP)

[DuplicateNodeBug.zip](https://github.com/user-attachments/files/19826373/DuplicateNodeBug.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #105596

### CODE REVIEW

File: scene/main/node.cpp [hunk 1]
```diff
@@ -3032,7 +3032,7 @@ Node *Node::_duplicate(int p_flags, HashMap<const Node *, Node *> *r_duplimap) c
 		parent->add_child(dup);
 		int pos = E->get_index();
```
Comment (kleonc) [inline scene/main/node.cpp:3033]:
```suggestion
		int pos = E->get_index(false);
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Welp:
```
./tests/scene/test_node.h:502: FATAL ERROR: test case CRASHED: SIGSEGV - Segmentation violation signal
```

**Comment by KoBeWi** [comment]
```
ERROR: Class 'AcceptDialog' isn't exposed.
   at: _instantiate_internal (core/object/class_db.cpp:549)
```
What.

**Comment by akien-mga** [comment]
Thanks!
