### PR TITLE
Fix shader type detection

### LINKED ISSUE #78482: Disabling shader pre-processor displays editor-only error about unknown built-ins
### Godot version

4.0.3.stable

### System information

Linux - Godot v4.0.3.stable - Vulkan (Forward+)

### Issue description

Disabling the shader pre-processor with `#pragma disable_preprocessor` causes errors to be displayed about built-ins being unknown. However, the shader will correctly compile and function as normal - the error is only in the shader editor.

Example screenshot:
Screenshot from 2023-06-20 17-55-20

### Steps to reproduce

1. Open project
2. Open `error-example.gdshader` in shader editor
3. Observe error

### Minimal reproduction project

[godot-4-shader-preprocessor-editor-error-minimal-reproduction-project-main.zip](https://github.com/godotengine/godot/files/11804403/godot-4-shader-preprocessor-editor-error-minimal-reproduction-project-main.zip)

Can also be found at: https://github.com/MenacingMecha/godot-4-shader-preprocessor-editor-error-minimal-reproduction-project

### PR DESCRIPTION
**Pull request by bitsawer**
* Fixes https://github.com/godotengine/godot/issues/78482

The problem was that `get_shader_type()` was called too early, before the preprocessing step. This PR moves the check after the preprocessing and uses the preprocessed shader code to figure out the shader_type. This makes sure the shader compiler only sees valid shader code that has all preprocessor statements removed, so that `get_shader_type()` can correctly parse the code and figure out the type. Previously, any preprocessor statements before the `shader_type xyz;` would cause a silent parsing failure and the shader type would default to `spatial`.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Makes sense to me!

File: scene/resources/shader.cpp [hunk 1]
```diff
@@ -100,6 +86,20 @@ void Shader::set_code(const String &p_code) {
 		}
 	}
 
+	String type = ShaderLanguage::get_shader_type(pp_code);
```
Comment (akien-mga) [inline scene/resources/shader.cpp:89]: This might warrant a comment to make it clear why the order matters. Because otherwise it looks weird to have this between the code that gathers the `include_dependencies`, and the code that uses them. It looks like it's asking to be moved around ;)

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
