### PR TITLE
Fixed a bug within sprite.cpp that caused a nan value to appear

### LINKED ISSUE #33716: Using nan values in sprite.cpp
**Godot version:**
Godot 3.2 Beta 1
**OS/device including version:**
Ubuntu 19.10
**Issue description:**

```
scene/2d/sprite.cpp:355:51: runtime error: -nan is outside the range of representable values of type 'int'
scene/2d/sprite.cpp:355:41: runtime error: -nan is outside the range of representable values of type 'int'
```

**Steps to reproduce:**
1. Set breakpoint like in image
Zrzut ekranu z 2019-11-18 19-38-22

2. Run project

**Minimal reproduction project:**
[asf.zip](https://github.com/godotengine/godot/files/3860047/asf.zip)

### PR DESCRIPTION
**Pull request by tygree**
A nan value would be present and cause a project to crash if is_pixel_opaque was called on a sprite with a texture of area zero and still had the repeating flag set.

Since a texture is still valid even with zero area, the fix involves checking the length and width of the texture. If either are zero, is_pixel_opaque now immediately returns false instead of allowing nan to reach the return values.

Fixes #33716

[godot-test-project.zip](https://github.com/godotengine/godot/files/3947531/godot-test-project.zip)
Modified minimal reproduction project from #33716 (from user: qarmin) that now tests the behavior

### CODE REVIEW

File: scene/2d/sprite.cpp [hunk 1]
```diff
@@ -339,6 +339,8 @@ bool Sprite::is_pixel_opaque(const Point2 &p_point) const {
 			mirror_x = (int)(q.x / texture->get_size().width);
 			mirror_y = (int)(q.y / texture->get_size().height);
 		}
+		if (texture->get_size().width == 0 || texture->get_size().height == 0)
```
Comment (groud) [inline scene/2d/sprite.cpp]: You should likely move the code before the previous block, otherwise you already did a division by zero.

Comment (tygree) [reply scene/2d/sprite.cpp]: Good catch, thank you! I forgot to account for if the texture is also mirror repeating. I am changing it now.

**Comment by YeldhamDev** [comment]
Please squash your commits: https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

File: scene/2d/sprite.cpp [hunk 2]
```diff
@@ -335,10 +335,15 @@ bool Sprite::is_pixel_opaque(const Point2 &p_point) const {
 	if (is_repeat) {
 		int mirror_x = 0;
 		int mirror_y = 0;
+
+		if (texture->get_size().width == 0 || texture->get_size().height == 0)
```
Comment (akien-mga) [inline scene/2d/sprite.cpp]: I'd move this up after the first `if (texture.is_null())` check. Looking at the code, I don't think it's necessary to let it run through all those calculations to finally return if the input was invalid.

**Comment by akien-mga** [comment]
Force pushed an amended commit addressing the above comment.

**Review by akien-mga — APPROVED** [review]

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
