### PR TITLE
Replace CameraMatrix::get_viewport_size with get_viewport_half_extents, shadow culling with ortho camera and other affected issues

### LINKED ISSUE #19900: VIEWPORT_SIZE doesn’t seem to give the viewport size in pixels
**Godot version:** 3.0.2

**OS/device including version:** Ubuntu 17.10

**Issue description:** The [documentation](http://docs.godotengine.org/en/3.0/tutorials/shading/shading_language.html#vertex-built-ins) says the `VIEWPORT_SIZE` uniform contains the size of the viewport in pixels, but its actual value seems to be an aspect ratio. For example, resizing the window in the vertical direction should not affect `VIEWPORT_SIZE.x`, but it does.

**Steps to reproduce:** Create any shader material that uses `VIEWPORT_SIZE`

**Minimal reproduction project:** [viewport.zip](https://github.com/godotengine/godot/files/2153433/viewport.zip)

### LINKED ISSUE #26637: Shadows get clipped at runtime in orthogonal mode
Godot version:
Tested on all versions of 3.1 betas using GLES2 mode (May exist for GLES3 as well)

OS/device including version:
Various computers running Windows 7 and 10, shitty Intel based GPUs

Issue description:
Shadows clip out on the left and right sides of a scene when moving a 3D object around using a direction light with shadows enabled (Orthogonal, PSSM, Stable, Optimized options used, doesn't stop this bug), and an angled camera in orthogonal mode. This does not affect the 3D editor, or when using the camera view within the editor. Seems to only happen at runtime.

It looks like it clips more depending on the width of the game window. If the window is maximized, the shadows no longer clip on the left and right sides. Bare bones project provided (3.1 beta 7).

Steps to reproduce:
Load the provided project, click and drag the cube around the scene, notice how the shadow of the cube disappears when dragging it to the left or right edge. Now maximize the game window. It appears the shadow does not get clipped.

Minimal reproduction project:
base project provided
[shadow_test.zip](https://github.com/godotengine/godot/files/2931193/shadow_test.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
Fixes #26637.
Fixes #19900.

The viewport_size returned by `get_viewport_size` was previously incorrect, being half the correct value. The function is renamed to `get_viewport_half_extents`, and now returns a Vector2.

Code which called this function has also been modified accordingly.

This PR also fixes shadow culling when using ortho cameras, because the correct input for `CameraMatrix::set_orthogonal` should be the full HEIGHT from `get_viewport_half_extents`, and not half the width.

It also fixes `state.ubo_data.viewport_size` in rasterizer_scene_gles3.cpp to be the width and the height of the viewport in pixels as stated in the documentation, rather than the current value which is half the viewport extents in worldspace, presumed to be a bug.

### CODE REVIEW

File: servers/visual/visual_server_scene.cpp [hunk 1]
```diff
@@ -1400,7 +1400,16 @@ bool VisualServerScene::_light_instance_update_shadow(Instance *p_instance, cons
 
 					float w, h;
 					p_cam_projection.get_viewport_size(w, h);
-					camera_matrix.set_orthogonal(w, aspect, distances[(i == 0 || !overlap) ? i : i - 1], distances[i + 1], false);
+
+					real_t size;
+					if (w > 0.0) {
+						size = w * ((real_t)h / w) * 2.0;
```
Comment (akien-mga) [inline servers/visual/visual_server_scene.cpp]: Is the cast to `real_t` necessary when they're both already `float`?

Comment (akien-mga) [reply servers/visual/visual_server_scene.cpp]: Barring any precision errors this is just `2.0 * h`, no?

**Comment by lawnjelly** [comment]
Having spoken to @clayjohn he reports that I may be able to fix other bugs (#19900) at the same time by fixing CameraMatrix::get_viewport_size internally (same idea). So I've marked this WIP and will have a look at putting the fix in that function tomorrow.

File: servers/visual/visual_server_scene.cpp (hunk 1 above)
Comment (lawnjelly) [reply servers/visual/visual_server_scene.cpp]: It probably doesn't matter one iota, I'm just trying to get into the whole 'everything should be a real_t to future proof for double precision' idea. set_orthogonal takes a real_t as argument, and h / w should be minutely more accurate as a double lol. I'll consider using floats when I edit tomorrow. :smile:

Comment (lawnjelly) [reply servers/visual/visual_server_scene.cpp]: > Barring any precision errors this is just `2.0 * h`, no?

Good point, I didn't even notice that. Will address tomorrow. :)

File: servers/visual/visual_server_scene.cpp [hunk 2]
```diff
@@ -2088,8 +2088,10 @@ void VisualServerScene::_prepare_scene(const Transform p_cam_transform, const Ca
 				float zn = p_cam_projection.get_z_near();
 				Plane p(cam_xf.origin + cam_xf.basis.get_axis(2) * -zn, -cam_xf.basis.get_axis(2)); //camera near plane
 
+				Vector2 vp_he = p_cam_projection.get_viewport_half_extents();
 				float vp_w, vp_h; //near plane size in screen coordinates
-				p_cam_projection.get_viewport_size(vp_w, vp_h);
+				vp_w = vp_he.x;
```
Comment (lawnjelly) [inline servers/visual/visual_server_scene.cpp]: @clayjohn , @reduz 
This is a possible bug in [setup shadow maps .. compute coverage] caused by the previous confusing function name. Should vp_w and vp_h be in fact set to double the half extents?

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 3]
```diff
@@ -4181,7 +4181,9 @@ void RasterizerSceneGLES3::render_scene(const Transform &p_cam_transform, const
 	state.ubo_data.shadow_dual_paraboloid_render_zfar = 0;
 	state.ubo_data.opaque_prepass_threshold = 0.99;
 
-	p_cam_projection.get_viewport_size(state.ubo_data.viewport_size[0], state.ubo_data.viewport_size[1]);
+	Vector2 vp_half_exts = p_cam_projection.get_viewport_half_extents();
+	state.ubo_data.viewport_size[0] = vp_half_exts.x;
```
Comment (lawnjelly) [inline drivers/gles3/rasterizer_scene_gles3.cpp]: @clayjohn , @reduz 
Should this be double the half extents? (I have duplicated the old behaviour, but I assume the old could be a bug)

Comment (lawnjelly) [reply drivers/gles3/rasterizer_scene_gles3.cpp]: Looking at #19900 I now believe this could be a 'double bug'. i.e. it is now incorrectly set to half the viewport extents, rather than the full extents, _however_ the docs say this should be the width and height of the viewport in pixels.

If so then the original may have been a mistake thinking that the old CameraMatrix::get_viewport_size returned pixels.

I can't find anything in the standard shaders glsl referring to viewport_size (aside from screen space reflections which seems to replace it with something different) so there might be an argument for changing this to the actual viewport width and height in pixels. I'll try it out and see if anything looks amiss.

File: servers/visual/visual_server_scene.cpp [hunk 4]
```diff
@@ -1398,9 +1398,9 @@ bool VisualServerScene::_light_instance_update_shadow(Instance *p_instance, cons
 
 				if (p_cam_orthogonal) {
 
-					float w, h;
-					p_cam_projection.get_viewport_size(w, h);
-					camera_matrix.set_orthogonal(w, aspect, distances[(i == 0 || !overlap) ? i : i - 1], distances[i + 1], false);
+					Vector2 vp_he = p_cam_projection.get_viewport_half_extents();
+
+					camera_matrix.set_orthogonal(vp_he.y * 2.0, aspect, distances[(i == 0 || !overlap) ? i : i - 1], distances[i + 1], false);
```
Comment (clayjohn) [inline servers/visual/visual_server_scene.cpp]: Any reason why it went from using width in the original to using height in the updated code? I feel like they may not result in the same behaviour.

Comment (lawnjelly) [reply servers/visual/visual_server_scene.cpp]: Yes .. they don't result in the same behaviour! The old code was broken badly. #26637 

This was the original reason for the PR, the use of height (and the 2x multiplier) fixes the bug.

It turns out that when you pass size into CameraMatrix::set_orthogonal, size only persists in terms of the height dimension (unless the aspect ratio is 1.0). To get back to the original size in order to create a new CameraMatrix, you have to use the HEIGHT rather than the width. I.e. height is preserved rather than width. This makes sense for typical use cases of aspect ratio.

File: servers/visual/visual_server_scene.cpp (hunk 2 above)
Comment (clayjohn) [reply servers/visual/visual_server_scene.cpp]: I just tested it out manually as I wasnt sure either. But the current implementation is definitely correct. It seems these should be half extents. When I tried doubling, or doubling and subtracting 1.0, everything broke.

**Review by clayjohn — APPROVED** [review]

File: servers/visual/visual_server_scene.cpp (hunk 2 above)
Comment (lawnjelly) [reply servers/visual/visual_server_scene.cpp]: > I just tested it out manually as I wasnt sure either. But the current implementation is definitely correct. It seems these should be half extents. When I tried doubling, or doubling and subtracting 1.0, everything broke.

Ok that's good to know. In that case I could possibly simplify it by removing the vp_w and vp_h variables, renaming the vp_he and using that later in the code. Which do you think would be clearer? Also I'm not sure about the comment, I'm not sure it is correct, see above.

Comment (clayjohn) [reply servers/visual/visual_server_scene.cpp]: The comment definitely seems wrong. 

Renaming the variables to increase clarity is definitely helpful. :)

**Review by akien-mga — APPROVED** [review]
Looks good, and AFAICT apart from the two bug fixes, there shouldn't be any logic change, so it seems safe enough to merge for 3.2.

**Comment by akien-mga** [comment]
Thanks!

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Hey this is only for GLES3 right?  Because from my tests I noticed GLES2 function is also not working properly

**Comment by clayjohn** [comment]
@CarlGustavAlbertDwarfsteinYung what function are you referring to? This particular function is in the Camera matrix class which is not specific to GLES2 or GLES3.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@clayjohn  Sorry disregard that message. I misread.
