### PR TITLE
Simplify Subresource Saving

### LINKED ISSUE #55885: .tres file with a Dictionary/Array with a Resource is only saved the first time (or when the Dictionary/Array is expanded again)
### Godot version

3.x, 4.0

### System information

Windows 10

### Issue description

First of all: This only happens when using a `Resource` inside a `Dictionary` or `Array`.
image

Editing and saving a `.tres` file will work only the first time. When editing and saving again, nothing will happen (can be checked by opening the `.tres` file in a text editor).

I debugged a bit and found out that it works due to the `Dictionary`/`Array` expand, which will set the `Dictionary`/`Array` to `edited`.
That's why it works the first time.
As soon as I at least once collapse/expand the `Dictionary`/`Array` again the save will work again for the first time.

### Steps to reproduce

1. Open the attached project
2. Open the save.tres - Verify that there is 'ChangeMe' in the `Dictionary`
3. Open the save.tres in a text editor (e.g. Notepad++) - There should be 'ChangeMe' as well
4. Change the text (in Godot) to something else
5. Save
6. Everything should work and the change is saved Verify in the text editor)
7. Change the text (in Godot) again
8. Save
9. You will see your change in the editor but in the text editor you won't see the change (I used Notepad++)

### Minimal reproduction project

[GodotSaveBug.zip](https://github.com/godotengine/godot/files/7700024/GodotSaveBug.zip)

### PR DESCRIPTION
**Pull request by reduz**
Redo edited subresource (and resource) saving in a much more simplified way. It should be _much_ faster too and help considerably improve save times on large scenes.

I think this should work (unless I am missing something) and be faster than what is there.
Fixes #55885 and supersedes #57077.

I am not 100% entirely convinced that this approach works. Everything points to the fact it should and it seems to work for me, but just in case make sure to test well!

### CODE REVIEW

**Comment by TokageItLab** [comment]
Is it related to #62287?

**Review by Maran23 — COMMENTED** [review]
I just tested it and this indeed fixes the bug and works well.

This implementation is quite smart, I remember while debugging that I also found out that `ResourceCache::get_cached_resources(&cached);` will also contain all sub resources but I didn't know how to proceed from there.

**Comment by KoBeWi** [comment]
Seems like this PR causes changes to unopened scenes. When you have an instanced scene, but it's not opened in the editor, saving the parent scene will still save all instanced scenes.

**Comment by reduz** [comment]
@KoBeWi Strangely I don't see why that would be different than what it was before, but in either case I don't think applying this to PackedScenes makes any sense, so I could manually skip them?

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -1651,29 +1623,43 @@ int EditorNode::_save_external_resources() {
...
-		}
-	}
 
-	// Clear later, because user may have put the same subresource in two different resources,
-	// which will be shared until the next reload.
+		String path = res->get_path();
+		if (path.begins_with("res://")) {
+			int subres_pos = path.find("::");
+			if (subres_pos == -1) {
+				// Actual resource
```
Comment (KoBeWi) [inline editor/editor_node.cpp:1640]:
```suggestion
				// Actual resource.
```

**Comment by reduz** [comment]
@KoBeWi Please test again to see if you encounter the same behavior

**Review by KoBeWi — APPROVED** [review]
Doesn't cause (obvious) problems anymore and fixes the issue.
Can't say much about the code though, other than it probably makes sense.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.
