### PR TITLE
Readd mipmaps 'bug' in Image::expand_x2_hq2x, fixing it caused a regression

### LINKED ISSUE #22747: Image re-import sometimes doesn't work and keeps old textures.
**Windows 10 64-bit Alpha 3.1 8068d02**

When replacing PNG files, sometimes Godot now doesn't update and reimport the new image.  Even when forcing it, it still has some display issues that aren't corrected, and **the old texture may still appear even when restarting the editor**?

Hard to say exactly how to reproduce this, but it happened at least twice when:

1. I created a new scene, dragged a PNG from the file manager onto the canvas as a Sprite.
2. Replaced the source image in the folder from Windows Explorer

Below I had originally dragged a PNG of an X11 icon, then replace it with a Win10 icon.

## Overwrote the image in Windows Explorer
(Changed the os.png from the X11 one to a Win10 version.  No change on the canvas or in the file manager.)
godot_master_2018-10-05_05-58-03

## Manually re-import sort of works, but is cut off.
(At one point it was saying it was 54x60 or something, the canvas texture shows that at least.)

godot_master_2018-10-05_05-59-17

## Still shows the old icon in the file manager.
godot_master_2018-10-05_05-59-38

## Overwrote the Win icon back to the X11 and restarted the editor.
(The textures for the windows icon were overwritten with the X11 one, but they still remain in the scenes?)

godot_master_2018-10-05_06-08-09

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #22747, was a regression from dec20a9.

### CODE REVIEW

File: core/image.cpp [hunk 1]
```diff
@@ -1198,7 +1198,9 @@ void Image::expand_x2_hq2x() {
 	if (current != FORMAT_RGBA8)
 		convert(current);
 
-	if (used_mipmaps) {
+	// FIXME: This is likely meant to use "used_mipmaps" as defined above, but if we do,
+	// we end up with a regression: GH-22747
+	if (mipmaps) {
```
Comment (akien-mga) [inline core/image.cpp]: @reduz I did not dig much to understand why it misbehaves, but it looks like fixing this apparent bug caused #22747.
All other methods set `used_mipmaps = has_mipmaps()` at the beginning and regenerate mipmaps if it was set, while here we check `mipmaps` which is always false (due to `clear_mipmaps()` above).

So the question is why generating mipmaps in `expand_x2_hq2x` causes #22747, and how to fix it.

Comment (akien-mga) [reply core/image.cpp]: To be clear, this commit undoes a previous "fix" in https://github.com/godotengine/godot/commit/dec20a987b40e7625b38e520cc223723da9bae2a#diff-1cf7b15b355bb206717d5061d1768debR1201 which causes the bug.
