### PR TITLE
Unify typing of variables, constants and parameters in GDScript

### LINKED ISSUE #53115: [Godot4] maybe should treat null as any variant type
### Godot version

4.0.dev.20210924.official

### System information

window10

### Issue description

I try implement my MyVector class,

### Steps to reproduce

If I code like this, all work well.

But if I want set default parameter and set data=null,
I don't know how to code it because syntax error:

Maybe I can not asign the function 'set_data' parameter 'value' type,
but I think it's not a good idea and also have a syntax

### Minimal reproduction project
[NullParamTest.zip](https://github.com/godotengine/godot/files/7234250/NullParamTest.zip)

_No response_

### LINKED ISSUE #56217: Using `null` as default parameter causes parse error when trying to access members of that parameter
### Godot version

v4.0.dev.custom_build [9d02cfa6b]

### System information

Linux Mint - Vulkan API 1.2.131 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

When having a function that is using a default parameter which is `null` the parser seemingly always asumes that this variable is `null` if no further assignment in the function itself happens.
This leads to problems if this variable is a dictionary because members can't be accessed.

The provided code snippets should make it clearer.

Maybe this issue is related? #54643

#### Not working
```gdscript
func test(data=null):
	if data:
		print(data['test'])  # Accessing this member will cause the ParseError
	else:
		print("no data")
```

#### Working
```gdscript
func test(data=null):
	data = data  # This unnecessary line can be used to prevent the ParseError
	if data:
		print(data['test'])  # Now this line is working
	else:
		print("no data")
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #66141: GDScript 2.0: Statically typed variables can have different types assigned to them
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10

### Issue description

Statically typed GDScript variables sometimes don't work statically as promised, even when debugging the game from the editor.

### Steps to reproduce

Normally, attempting to assign a float to an int variable in GDScript will result in an automatic conversion:
```gdscript
var a: int = 1.5
print(a) # 1
```
However, if the float comes from a non-statically typed variable, there's no conversion:
```gdscript
var b = 1.5
var a: int = b
print(a) # 1.5
assert(a is int) # Runtime error
assert(a is float) # (Editor error, even though a is a float at this point, but this is the expected behaviour)
```

A similar thing happens with incompatible types where you'd expect an error instead. It works fine without variables:
```gdscript
var a: int = "" # Editor error
var c: int = 0
c = "" # Editor error
```
Then with variables, (at least in the case of strings, the error sometimes will trigger on variable declaration, but it can still slip by later):
```gdscript
var b = ":("
var a: int = b # Editor error
var c: int = 0
c = b # No error
print(c) # ":("
assert(c is int) # Runtime error
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #67048: GDScript 2.0: Strange type errors on dynamic default params
### Godot version

godot 4 beta 2

### System information

Linux (Pop! OS)

### Issue description

When working with a dynamic param which defaults to `null`, the following function throws a type-checking error (in editor, not at runtime) complaining that `rpc_id` expects an int but is receiving null

(I tested with a default param `recipient = ""` and received the same errors, so the type-checking error is specific to default params but not specific to null)

```python
func send_ping(recipient = null):
  if recipient is null:
    return
  elif typeof(recipient) == TYPE_INT:
    rpc_id(recipient, "ping")
```

Trying to cast recipient as int throws the error "cannot cast null as int":

```python
func send_ping(recipient = null):
  if recipient is null:
    return
  elif typeof(recipient) == TYPE_INT:
    rpc_id(recipient as int, "ping")
```

However the following all successfully make the error go away:

```python
# reassign recipient as int
func send_ping(recipient = null):
  if recipient is null:
    return
  elif typeof(recipient) == TYPE_INT:
    var: int id = recipient
    rpc_id(id, "ping")
```

```python
# reassign recipient to itself
func send_ping(recipient = null):
  recipient = recipient
  if recipient is null:
    return
  elif typeof(recipient) == TYPE_INT:
    rpc_id(recipient, "ping")
```

```python
# ironically, setting recipient to null makes the error go away
func send_ping(recipient = null):
  if recipient is null:
    return
  elif typeof(recipient) == TYPE_INT:
    recipient = null
    rpc_id(recipient, "ping")
```

### Steps to reproduce

throw the following code into a standard Node2D

```python
func send_ping(recipient = null):
  if recipient is null:
    return
  elif typeof(recipient) == TYPE_INT:
    rpc_id(recipient, "ping")
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #70523: "Cannot Use Subscript Operator on a Base Type of 'null'" Error Not Allowing for Other Types when 'null' is Only Default Value
### Godot version

4.0beta10

### System information

Windows 10

### Issue description

GDScript error occurs in Godot 4.0 beta 10 (worked as expected in beta 9) when unreachable code is given a variable of the wrong type. In the function in the below example, some variables are set by according to a dictionary in an array, provided in the argument `val`. If no argument is provided (defaulting to `null`), those variables are reset to their defaults, and the function returns.

error

The error occurs at the four lines where the variables are set according to the given array/dictionary, as `null` would indeed not be compatible. But, this code is unreachable if `val` is `null`.

This error can be worked around by using `[null]` instead, of course, and the error makes sense in theory, but it doesn't make sense for it to be raised before runtime.

### Steps to reproduce

Create any function with a default argument with a base type that includes no subscript operators, then attempt to use a subscript operator from that argument in code within the function which should be unreachable by that type

### Minimal reproduction project

[Variable Type Error.zip](https://github.com/godotengine/godot/files/10298445/Variable.Type.Error.zip)

### LINKED ISSUE #70912: Type Hinting Changes Subsequent Arithmetic Results
### Godot version

v4.0.beta.custom_build [0160fea1c]

### System information

- OS: Arch Linux
- KERNEL: 6.1.2-arch1-1
- CPU: AMD Ryzen 7 3700X 8-Core
- GPU: AMD Radeon RX 6900 XT (navi21, LLVM 14.0.6, DRM 3.49, 6.1.2-arch1-1)
- GPU DRIVER: 4.6 Mesa 22.3.2
- RAM: 16 GB

### Issue description

(The example is destilled from a real world project of mine and therefore may seem a bit convoluted)

```gdscript
extends Control

var d1:Dictionary = {
	"min": Vector2(49.75, -88.25),
	"max": Vector2(0, 36.25)
}

var d2:Dictionary = {
	"min": Vector2(60, -88.25),
	"max": Vector2(0, 36.25)
}

var d3:Dictionary = {
	"min": Vector2(46.5, -88.25),
	"max": Vector2(0, 36.25)
}

var d4:Dictionary = {
	"min": Vector2(63, -88.25),
	"max": Vector2(0, 36.25)
}

var matrix_cell_dimensions:Array

# Called when the node enters the scene tree for the first time.
func _ready():
	var row_heights:Array[float] = [15.4, 12.3]
	var col_widths:Array[float] = [49.75, 63.0]
	matrix_cell_dimensions =  [
		[d1, d2],
		[d3, d4]
	]
	var a = 10
	var b = 20
	for row in range(0, row_heights.size()):
		for col in range(0, col_widths.size()):
			var x_pos:float = a * col
			var m:Dictionary = matrix_cell_dimensions[row][col] 
			var _t1 = (absf(m.min.x) + absf(m.max.x)) # <------------------- NO type hint
			print("_t1: ", _t1)
			x_pos += (((_t1) - col_widths[col]) / 2.0)
			print("x_pos: ", x_pos)
			print()
```

Will result in output:
```
_t1: 49.75
x_pos: 0

_t1: 60
x_pos: 8.5

_t1: 46.5
x_pos: -1.625

_t1: 63
x_pos: 10
```

**With type hinting**
```gdscript
# . . .
	for row in range(0, row_heights.size()):
		for col in range(0, col_widths.size()):
			var x_pos:float = a * col
			var m:Dictionary = matrix_cell_dimensions[row][col] 
			var _t1:float = (absf(m.min.x) + absf(m.max.x)) # <------------------- WITH type hint
			print("_t1: ", _t1)
			x_pos += (((_t1) - col_widths[col]) / 2.0)
			print("x_pos: ", x_pos)
			print()
```

Will result in output:
```
_t1: 49.75
x_pos: 0

_t1: 60
x_pos: -1.5

_t1: 46.5
x_pos: -1.625

_t1: 63
x_pos: 0
```

My question is now:
Why does `x_pos` does not have the same value in both cases, even though `_t1`s value stays the same?  

### Steps to reproduce

See above

### Minimal reproduction project

[absf_bug.zip](https://github.com/godotengine/godot/files/10343759/absf_bug.zip)

### PR DESCRIPTION
**Pull request by vonagam**
Member variables, local variables, member constants, local constants and parameters - all of those have almost the same code for determining a type. This PR tries to unify that logic under one function, fix inconsistencies and to show explicitly what are the differences between those types.

Introduced `GDScriptParser::AssignableNode` as a parent for `VariableNode`, `ConstantNode` and `ParameterNode`. They all have the same properties that used by the resolving logic:
```cpp
IdentifierNode *identifier;
ExpressionNode *initializer;
TypeNode *datatype_specifier;
bool infer_datatype;
int usages;
```

The only difference is that in `ParameterNode` `initializer` was called `default_value`. If this rename is a deal breaker - can remove `AssignableNode` and pass those properties one by one instead.

Otherwise pretty-straightforward.

Notes:

- A variable has `use_conversion_assign`, strange that same functionality is not exposed to a parameter.

- I used construction like `static constexpr const char* kind = "variable";` inside a function to pass a string used in errors. Did so to avoid allocations/conversions. If this does not matter and I should use `String` instead - just let me know.

Next issue(s) about typing of null as default value is fixed (example in [next comment](https://github.com/godotengine/godot/pull/70464#issuecomment-1367688699)):  
Fixes #53115.
Fixes #56217.
Fixes #67048.
Fixes #70523.

Next issue(s) connected to assignment of weak default value to typed variable is fixed:
Fixes #66141.
Fixes #70912.

### CODE REVIEW

**Comment by vonagam** [comment]
Added simple test to show that implicit conversion now works for arguments:
```gdscript
func check(arg: float = 3): # would have failed before
	return typeof(arg) == typeof(3.0)
```

Updated to include fix for null as default type of arguments/variables with corresponding test:
```gdscript
func check(input: int) -> bool:
  return input == 1

var recur = null
var prop = null

func check_arg(arg = null) -> void:
  if arg != null:
    print(check(arg)) # would have failed before

func check_recur() -> void:
  if recur != null:
    print(check(recur)) # would have failed before
  else:
    recur = 1
    check_recur()

func test() -> void:
  check_arg(1)

  check_recur()

  if prop == null:
    set('prop', 1)
    print(check(prop)) # would have failed before
    set('prop', null)

  var loop = null
  while loop != 2:
    if loop != null:
      print(check(loop)) # would have failed before
    loop = 1 if loop == null else 2
```

I know from [this comment](https://github.com/godotengine/godot/pull/56759#issuecomment-1169986964) that there is a discussion to stop inferring type of arguments from default values. 

I see two ways:

1) Either current system is kept as is, but null as default for variables/arguments means Variant.

2) Or all not explicitly typed or explicitly inferring variables/arguments should be treated as Variants. I assume that the discussion was only about arguments but I don't see much difference between them and member variables - both can be changed from outside with arbitrary values. With local variables you can actually do try to narrow it down, but as shown in loop example it does not work flawlessly right now. 

Can remove that change from PR. It is a one-line difference.

**Comment by dalexeev** [comment]
@vonagam Could you add conversion for constant initializers to `resolve_assignable` if the specified type is different? See #70873 for an example (albeit a memory leak). There was also the question of whether we should allow non-exact type matching for constants and parameters.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1601,6 +1481,132 @@ void GDScriptAnalyzer::resolve_suite(GDScriptParser::SuiteNode *p_suite) {
...
+
+#ifdef DEBUG_ENABLED
+	if (p_is_local) {
+		if (p_variable->usages == 0 && !String(p_variable->identifier->name).begins_with("_")) {
+			parser->push_warning(p_variable, GDScriptWarning::UNUSED_VARIABLE, p_variable->identifier->name);
+		} else if (p_variable->assignments == 0) {
+			parser->push_warning(p_variable, GDScriptWarning::UNASSIGNED_VARIABLE, p_variable->identifier->name);
+		}
+
+		is_shadowing(p_variable->identifier, "variable");
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1585]: You could use `kind` here instead of repeating the string `"variable"`. Same for `"constant"` below.

On an unrelated note, we should maybe rename the `is_shadowing()` function given it has side effects and we never use its result.

**Review by vnen — APPROVED** [review]
This seems a good approach to me.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (vonagam) [reply modules/gdscript/gdscript_analyzer.cpp]: Done. (Renaming note sounds reasonable.)

**Comment by Malcolmnixon** [comment]
Whups - just found this PR after filing the bug - https://github.com/godotengine/godot/issues/70978.

The following code now crashes:
```gdscript
func _ready():
	# This works
	test([1, 1, 1])
        
	# This crashes
	test()
	
func test(array := [1, 2, 3]):
	print("array is ", array)
```
