### PR TITLE
Process skeleton modifiers when the skeleton is marked as dirty

### LINKED ISSUE #109110: Using a LookAtModifier3D node and a BoneAttachment3D node (with OverridePose and External Skeleton enabled) inside another BoneAttachment3D , disables the LookAtModifier when pausing.
### Tested versions

Tested versions
Godot v4.5 beta 4

### System information

Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 32.0.15.6614) - AMD Ryzen 9 5900XT 16-Core Processor (32 threads)

### Issue description

Using a LookAtModifier3D Node in conjunction with a BoneAttachment3D Node (with override pose enabled and external skeleton) inside another BoneAttachment3D , disables LookAtModifier3D when pausing, even if the BoneAttachment3D is affecting a completly different bone to the LookAtModifier3D.

I tested in 4.4.1 and you can use this set up just fine without any issues.

I also don't think its just "disabling it on pause", Its making any collider attached to the lookat bone behave in a strange way, as if it was in 2 positions at once. the neutral position and the position after the lookat is applied, but this the best way I can decribe whats happening

this is what it looks like now in 4.5 beta 4

https://github.com/user-attachments/assets/83100d6e-3fcc-4e90-a4fa-efbf225318f6

https://github.com/user-attachments/assets/0f45ec28-e306-4d1d-8908-ab19664d0bd6

### Steps to reproduce

import a rigged character and use LookAtModifier3D on one bone and BoneAttachment3D on another, then insert another BoneAttachment3D in the first BoneAttachment3D, enable "Override Pose" and Use "External Skeleton" on this second one, and set up a target for the LookAtModifier3D, run the game and pause, the LookAtModifier3D bone should get disabled on pause and re-enabled when resuming.

### Minimal reproduction project (MRP)

[Bug.zip](https://github.com/user-attachments/files/21501808/Bug.zip)

### PR DESCRIPTION
**Pull request by precup**
Fixes #109110.

The only place that the default argument of the function is used is in `Skeleton3D::_make_dirty`, so this is just a roundabout way of changing that call. I think it makes more sense to have the full update be the default, though, so I changed it here.

The other change is because the `_make_modifiers_dirty` shortly before does try to add `UPDATE_FLAG_MODIFIER` to `update_flags`, but it ends up getting clobbered afterwards by the direct assignment.

I can't really think of a case where you'd want to skip `_process_modifiers` and display the skeleton without them, to be honest, so perhaps I've misunderstood something about the intent.

### CODE REVIEW

File: scene/3d/skeleton_3d.h [hunk 1]
```diff
@@ -91,7 +91,7 @@ class Skeleton3D : public Node3D {
 		UPDATE_FLAG_POSE = 4,
 	};
 
-	void _update_deferred(UpdateFlag p_update_flag = UPDATE_FLAG_POSE);
+	void _update_deferred(UpdateFlag p_update_flag = (UpdateFlag)(UPDATE_FLAG_POSE | UPDATE_FLAG_MODIFIER));
```
Comment (TokageItLab) [inline scene/3d/skeleton_3d.h]:
```cpp
void Skeleton3D::_make_dirty() {
	if (dirty) {
		return;
	}
	dirty = true;
	_update_deferred(modifiers.is_empty() ? UPDATE_FLAG_POSE : (UpdateFlag)(UPDATE_FLAG_POSE | UPDATE_FLAG_MODIFIER);
}
```

It seems necessary to check for the existence of modifiers to prevent unnecessary processing.

The default value of` _update_deferred()` is currently only used within `_make_dirty()`, so I think it would be better to explicitly pass the flags there.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
Fixing `_notification()` seems reasonable in order to prevent overwriting UPDATE_FLAG_MODIFIER in the line above.

However, for `_update_deferred()`, I think we should modify `_make_dirty()` instead.

**Review by TokageItLab — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by fire** [comment]
Causes failure in https://github.com/godotengine/godot/issues/110095
