### PR TITLE
Web: Remove deprecated worker.js file

### LINKED ISSUE #98973: Web release export template fails to build when using `optimize=none`
### Tested versions

- Reproducible in: 4.4.dev e65a23762b36b564eb94672031f37fdadba72333

### System information

Godot v4.4.dev (e65a23762) - Fedora Linux 41 (KDE Plasma) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 565.57.01) - 13th Gen Intel(R) Core(TM) i9-13900K (32 threads)

### Issue description

I get a build error when compiling a web export template with `optimize=none`. In this case, wasm-opt is not called, but I get this error:

```
em++: warning: -pthread + ALLOW_MEMORY_GROWTH may run non-wasm code slowly, see https://github.com/WebAssembly/design/issues/1271 [-Wpthreads-mem-growth]
Install file: "bin/godot.web.template_release.wasm32.wasm" as "bin/.web_zip/godot.wasm"
Creating 'bin/godot.web.template_release.wasm32.wrapped.js'
Install file: "bin/godot.web.template_release.wasm32.worker.js" as "bin/.web_zip/godot.worker.js"
scons: *** [bin/.web_zip/godot.worker.js] bin/godot.web.template_release.wasm32.worker.js: No such file or directory
scons: building terminated because of errors.
```

Using emsdk 3.1.71. For context, I use `optimize=none` to make builds as fast to compile as possible (even if that comes at the expense of runtime performance).

### Steps to reproduce

```bash
scons -j32 platform=web target=template_release optimize=none debug_symbols=no progress=no scu_build=all
```

If you remove the `optimize=none`, the above command will build successfully.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Sticksman**
Remove godot.<PROGSUFFIX>.worker.js. As far as I can tell this file is deprecated. The ci pulls this file from build cache, and when the build artifact is examined, the worker.js file has a dummy description inside (see linked issue). 

This all points to the web .worker.js file as having been removed.

Fixes #98973

### CODE REVIEW

File: platform/web/js/engine/config.js [hunk 1]
```diff
@@ -295,8 +295,8 @@ const InternalConfig = function (initConfig) { // eslint-disable-line no-unused-
 			'locateFile': function (path) {
 				if (!path.startsWith('godot.')) {
 					return path;
-				} else if (path.endsWith('.worker.js')) {
-					return `${loadPath}.worker.js`;
+				} else if (path.endsWith('.service.worker.js')) {
+					return `${loadPath}.service.worker.js`;
```
Comment (Faless) [inline platform/web/js/engine/config.js:299]:
```suggestion
```

Service worker doesn't need to be located via locateFile

File: platform/web/emscripten_helpers.py [hunk 2]
```diff
@@ -45,9 +45,6 @@ def create_template_zip(env, js, wasm, worker, side):
         zip_dir.File(binary_name + ".audio.worklet.js"),
         zip_dir.File(binary_name + ".audio.position.worklet.js"),
     ]
-    if env["threads"]:
-        in_files.append(worker)
-        out_files.append(zip_dir.File(binary_name + ".worker.js"))
```
Comment (Faless) [inline platform/web/emscripten_helpers.py:50]: There's another:

```

        if env["threads"]:
            cache.append("godot.editor.worker.js")
```

below that needs to be removed

**Review by Faless — DISMISSED** [review]
This seems correct overall, since we bumped the minimum emscripten version to 3.1.62 it should be safe to remove the deprecated worker for threads.

See review comments.

**Comment by Sticksman** [comment]
Ah yeah sorry, I committed from a different computer (was using mac to test the build)

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. I can now compile a web export template successfully with emsdk 3.1.71 on Linux.

**Comment by Sticksman** [comment]
@Faless Could you take another look?

**Review by adamscott — APPROVED** [review]
Everything seems fine! Thank you @Sticksman !

**Comment by luxun0517** [comment]
good!!!!

**Comment by Repiteo** [comment]
Thanks!

**Comment by gitsomebit** [comment]
this pull request broke PWA offline functionality as mentioned in #100089

**Comment by adamscott** [comment]
@gitsomebit Can you create a new issue about this?

**Comment by gitsomebit** [comment]
> @gitsomebit Can you create a new issue about this?

@adamscott is #100089 or #100518 not sufficient?
