### PR TITLE
Fixed rotated RootMotionView grid glitch

### LINKED ISSUE #60342: Rotated RootMotionView grid cause glitch
### Godot version

3.5, 4.0.dev(292e34c6a8d04987a7b36f89a9a95b897ba13e87)

### System information

MacOS 11.6

### Issue description

RootMotionView grid is skewed after rotation causing glitch.

I think there may be a problem with the method of get the coordinates used to calculate the drawing of the grid after rotation.

### Steps to reproduce

https://user-images.githubusercontent.com/61938263/163802543-1d098c79-25fe-4b0e-b54f-9fa127f6d17a.mov

### Minimal reproduction project

[turn_rotation_root.zip](https://github.com/godotengine/godot/files/8505364/turn_rotation_root.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixed #60342. It should be `fposmod()` in normal space, not in inverted space.

Before:

https://user-images.githubusercontent.com/61938263/165081164-2d79d39c-c341-4937-9de0-d6e379ea4b89.mov

After:

https://user-images.githubusercontent.com/61938263/165081251-e05b22a2-9177-4e7f-8dab-01aa7b4ce7c7.mov

[turn_rotation_root.zip](https://github.com/godotengine/godot/files/8554105/turn_rotation_root.zip)

### CODE REVIEW

**Comment by TokageItLab** [comment]
Oh something is still wrong, maybe something needs to be fixed comprehensively for RootMotion.

**Comment by TokageItLab** [comment]
Bugs about drawing can be fixed in this PR, but additional fixes may be needed later in AnimationTree for rotation.

File: scene/animation/root_motion_view.cpp [hunk 1]
```diff
@@ -134,9 +133,9 @@ void RootMotionView::_notification(int p_what) {
 					Vector3 from(i * cell_size, 0, j * cell_size);
 					Vector3 from_i((i + 1) * cell_size, 0, j * cell_size);
 					Vector3 from_j(i * cell_size, 0, (j + 1) * cell_size);
-					from = accumulated.xform(from);
-					from_i = accumulated.xform(from_i);
-					from_j = accumulated.xform(from_j);
+					from = accumulated.xform_inv(from);
```
Comment (reduz) [inline scene/animation/root_motion_view.cpp:136]: Is this ok? remember that if scale is present, xform_inv will not work.

Comment (TokageItLab) [reply scene/animation/root_motion_view.cpp:136]: @reduz transform's scale has been orthonormalized in line 116, so always accumulated's scale is should be 1.

Comment (reduz) [reply scene/animation/root_motion_view.cpp:136]: alright looks good then

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.
