### PR TITLE
Fix Texture3D import not working

### LINKED ISSUE #92315: Texture3D import not working when texture has fully opaque and partly transparent slices
### Tested versions

Reproducible in: 4.2.2 (stable), 4.3 dev6, 4.0, (maybe?) 3.5.3 (stable)

### System information

Windows 10 - Godot Engine v4.3.dev6.official.89850d553 - https://godotengine.org OpenGL API 3.3.0 NVIDIA 551.76 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 3070 Laptop GPU (tested with Forward+, Compatibility and Mobile) - Also tested on a Surface Pro 10

### Issue description

Under certain conditions one cannot import Texture3Ds. One suspicion i have is, that on import Godot removes the alpha channel of textures that are fully opaque (which is quite annoying to begin with). Maybe it removes the alpha channel of the slices that are fully opaque and keeps them on the slices that have some transparency, leading to a mismatch in the format of the slices (RGB8 vs RGBA8). I made a few test textures attached to this with several different (but not all thinkable) cases. They are 512 * 512px with 8 * 8 slices. To be sure the files are not corrupted by the graphic software i made the same textures with different programs and the results were the same.

1.png: import as Texture3D working
2.png: import as Texture3D working
3.png: import as Texture3D NOT working
4.png: import as Texture3D working
5.png: import as Texture3D NOT working
6.png: import as Texture3D NOT working
7.png: import as Texture3D working

error message:
Image format mismatch
Attempting to use an uninitialized RID
servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:1416 - Parameter "tex" is null.
Attempting to use an uninitialized RID
servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:1416 - Parameter "tex" is null.
Attempting to use an uninitialized RID
servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:767 - Parameter "t" is null.

Godot 3.5.3 error message before forced restart:
ERROR: Condition "header[0] != 'G' || header[1] != 'D' || header[2] != 'S' || header[3] != 'T'" is true. Returned: ERR_FILE_CORRUPT
   at: _load_data (scene/resources/texture.cpp:476)
No error message after forced restart (but not sure if Texture3D was imported correctly.

### Steps to reproduce

Start a new project, drag and drop texture into it. Go to import tab, choose Texture3D with 8 by 8 tiles, hit import button.

### Minimal reproduction project (MRP)

No minimal reproduction project needed (can be done in new project). Here are the textures:

### PR DESCRIPTION
**Pull request by fire**
Fix Texture3D import not working when texture has fully opaque and (partly or fully) transparent slices.

Fixes: https://github.com/godotengine/godot/issues/92315

The idea behind this pr is all Texture3D and Texture2DLayered must match the format in the header which may not be the format of the first image.

~~The idea behind this pr is all Texture3D and Texture2DLayered must match the first image in format. We enforce this, since the RD and the gpu does.~~

~~This feels vaguely wrong though.. because we're being strict on the load and forcing it to match the first image rather than rejecting the CompressedTexture2D but the advantage is this is both valid and allows failing files to load.~~

~~Somehow when saving LayeredTexture (TextureArray or Texture3D) the image goes from rgba -> rgb randomly in some of the layers. There probably should be a future pr for that but this also solves it in a less clean way.~~

https://github.com/godotengine/godot/files/15439250/Archive.zip has a series of failure cases that are fixed. Remember to convert them to Texture3D at 8x8 slices.

See also `Ref<Image> _validate_texture_format(const Ref<Image> &p_image, TextureToRDFormat &r_format);`

### CODE REVIEW

**Comment by fire** [comment]
Fails on 

333582176-363733e8-b988-48c9-8ee1-0bdd0d2a85c0

The Texture2D has a transparent hole in the second slice.

image

The Texture3D loses the hole.

image

**Comment by fire** [comment]
Tested on:

1. on lossless compression
2. on lossy compression 
3. on vram compress
5. on the first slice being transparent
6. on the first slice being opaque
7. on the first slice opaque and the second slice transparent
8. on the first slice opaque and the second slice transparent

**Comment by lyuma** [comment]
> https://github.com/godotengine/godot/pull/92344#issuecomment-2130482863

I am not clear how the PR solves that case (opaque, transparent, opaque slices)
The change to Image::detect_alpha() != ALPHA_NONE is nice for readability but does not functionally change the behavior since that constant is 0

**Comment by fire** [comment]
1. We solve it for vram here: `if (image->get_format() == Image::FORMAT_RGBA8 && !image->detect_alpha())`
2. We solve it lossless / lossy here 

```c++
// If the image is compressed and its format doesn't match the desired format, return an empty reference.
	if (first) {
	// This is done to avoid recompressing the image on load.
		//format will actually be the format of the first image,
	ERR_FAIL_COND_V(img->is_compressed() && format != img->get_format(), Ref<Image>());
		//as it may have changed on compression

		format = img->get_format();
	// The format will actually be the format of the header,
		first = false;
	// as it may have changed on compression.
	} else if (img->get_format() != format) {
	if (!img->is_compressed() && format != img->get_format()) {
		img->convert(format); //all needs to be the same format
		// Convert the image to the desired format.
		// Note: We are not decompressing the image here, just changing its format.
		// It's important that all images in the texture array share the same format for correct rendering.
		img->convert(format);
	}
}
```

**Comment by Kukuschi** [comment]
Would be nice if somebody could review that, was hoping for it to work in stable 4.3.

File: modules/webp/webp_common.cpp [hunk 1]
```diff
@@ -63,7 +63,7 @@ Vector<uint8_t> _webp_packer(const Ref<Image> &p_image, float p_quality, bool p_
 		Error error = img->decompress();
 		ERR_FAIL_COND_V_MSG(error != OK, Vector<uint8_t>(), "Couldn't decompress image.");
 	}
-	if (img->detect_alpha()) {
+	if (img->detect_alpha() != Image::ALPHA_NONE) {
```
Comment (fire) [inline modules/webp/webp_common.cpp:66]: Can be a separate pr.

**Comment by fire** [comment]
I'll split the ALPHA_NONE to a separate pr.

**Comment by fire** [comment]
@BlueCube3310 If you have time, could you look into this bug?

**Review by lyuma — COMMENTED** [review]
Rebased, so now it's just the format check.

Part of my apprehension is that I'm worried this change can affect 2D textures, especially uncompressed png or webp images like might be used in a 2D or pixel art game.

I'm having trouble understanding if this will adversely affect those cases or cause unnecessary calls to convert(). The code seemed very intentionally written to use the format of the first mipmap, not the file header, and this is reversing that. I would believe that this solves 3D textures, but it would be nice to guarantee that this won't break other cases.

File: scene/resources/compressed_texture.cpp [hunk 2]
```diff
@@ -339,18 +337,20 @@ Ref<Image> CompressedTexture2D::load_image_from_file(Ref<FileAccess> f, int p_si
...
-			if (first) {
-				//format will actually be the format of the first image,
-				//as it may have changed on compression
-				format = img->get_format();
-				first = false;
-			} else if (img->get_format() != format) {
-				img->convert(format); //all needs to be the same format
+			// If the image is compressed and its format doesn't match the desired format, return an empty reference.
+			// This is done to avoid recompressing the image on load.
+			ERR_FAIL_COND_V(img->is_compressed() && format != img->get_format(), Ref<Image>());
```
Comment (BlueCube3310) [inline scene/resources/compressed_texture.cpp:343]: Technically lossy/lossless images cannot be VRAM-compressed, though it may better to leave this check just in case.

**Review by BlueCube3310 — COMMENTED** [review]
Sorry for not taking a look at this earlier, this should indeed fix most of the issues. #106627 should be fixed by this too, since the cause is the same.

File: scene/resources/compressed_texture.cpp (hunk 2 above)
Comment (fire) [reply scene/resources/compressed_texture.cpp:343]: Send more review comments or an approval when it's ready. Thanks for reviewing.

**Review by Calinou — APPROVED** [review]
Tested locally with the MRP from OP, it works as expected. In `master`, several of the files failed to import, but they all import correctly now. I've imported Material Testers, the TPS demo and Dogwalk; they still import correctly too.

Code looks good to me.

**Testing project:** [test_pr_92344.zip](https://github.com/user-attachments/files/21373433/test_pr_92344.zip)
*Just the MRP packaged as an actual project for convenience, as opposed to loose files.*

File: scene/resources/compressed_texture.cpp [hunk 3]
```diff
@@ -339,18 +337,20 @@ Ref<Image> CompressedTexture2D::load_image_from_file(Ref<FileAccess> f, int p_si
 			} else if (data_format == DATA_FORMAT_WEBP && Image::webp_unpacker) {
 				img = Image::webp_unpacker(pv);
 			}
-
```
Comment (BlueCube3310) [inline scene/resources/compressed_texture.cpp]: I think the space here should be kept

File: scene/resources/compressed_texture.cpp [hunk 4]
```diff
@@ -339,18 +337,20 @@ Ref<Image> CompressedTexture2D::load_image_from_file(Ref<FileAccess> f, int p_si
...
-				first = false;
-			} else if (img->get_format() != format) {
-				img->convert(format); //all needs to be the same format
+			// If the image is compressed and its format doesn't match the desired format, return an empty reference.
+			// This is done to avoid recompressing the image on load.
+			ERR_FAIL_COND_V(img->is_compressed() && format != img->get_format(), Ref<Image>());
+
+			// The format will actually be the format of the header,
+			// as it may have changed on compression.
+			if (!img->is_compressed() && format != img->get_format()) {
```
Comment (BlueCube3310) [inline scene/resources/compressed_texture.cpp]: There's already a check for compressed images above.

```suggestion
			if (format != img->get_format()) {
```

**Review by BlueCube3310 — APPROVED** [review]
Looks good to me. I did some tests and it works as expected

File: scene/resources/compressed_texture.cpp (hunk 4 above)
Comment (fire) [reply scene/resources/compressed_texture.cpp]: The check above is on two conditions `img->is_compressed() && format != img->get_format()`. Haven't thought too hard about them.

File: scene/resources/compressed_texture.cpp (hunk 3 above)
Comment (fire) [reply scene/resources/compressed_texture.cpp]: Will update.

**Comment by fire** [comment]
I have updated the Fix Texture3D import not working pull request onto master.

> `if (!img->is_compressed() && format != img->get_format()) {`

Not sure about the conditions for this so advice solicited.

File: scene/resources/compressed_texture.cpp (hunk 4 above)
Comment (BlueCube3310) [reply scene/resources/compressed_texture.cpp]: When the above check is passed, the image is either uncompressed with mismatched formats (as expected), or compressed with the same formats. For the latter, simply `format != img->get_format()` is enough to ensure that conversion of a compressed image will not happen.

**Comment by Repiteo** [comment]
Thanks!
