### PR TITLE
Expand the imported texture channel count for remapping if necessary

### LINKED ISSUE #106422: Channel Remap: Information not preserved when remapping to a non-existent destination channel
### Tested versions

- Reproducible in: v4.5.dev.mono.gh [428a762e9]

### System information

Godot v4.5.dev.mono (428a762e9) - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (nvidia; 550.144.03) - AMD FX(tm)-6300 Six-Core Processor (6 threads)

### Issue description

Recently, the feature [Channel Remap](https://github.com/godotengine/godot/pull/99676) was added, but it has a behavior that can be considered problematic when trying to remap a channel to a non-existent channel in the texture.

Unity
As you can see, Unity allowed me to move the red channel to the alpha channel.

Godot
In the case of Godot, it does create the alpha channel but leaves it blank.

### Steps to reproduce

1. Select an RGB texture.
2. Go to the import dock.
3. Remap the Red channel to Zero.
4. Remap the Blue channel to Zero.
5. Remap the Alpha channel to Red.
6. Reimport the texture.

### Minimal reproduction project (MRP)

Here the [textures](https://ambientcg.com/view?id=Planks036B).

### PR DESCRIPTION
**Pull request by BlueCube3310**
Fixes #106422

Manages the remapped channel count in a sophisticated way that expands their amount only when said channel is necessary. This ensures that the memory usage, as well as extended import times due to format conversion, are kept to the minimum.

This needs a lot of testing. From my own, it looks like it works as intended, though since it's a complicated change it would be best to ensure it works for as many remap/format combinations as possible.

### CODE REVIEW

File: editor/import/resource_importer_texture.cpp [hunk 1]
```diff
@@ -480,11 +482,127 @@ void ResourceImporterTexture::_remap_channels(Ref<Image> &r_image, ChannelRemap
...
+	const bool remap_b = p_options[2] != REMAP_B ? !(!has_channel_b && p_options[2] == REMAP_0) : false;
+	const bool remap_a = p_options[3] != REMAP_A ? !(!has_channel_a && p_options[3] == REMAP_1) : false;
+
+	if (!(remap_r || remap_g || remap_b || remap_a)) {
 		// Default color map, do nothing.
 		return;
 	}
 
+	// Whether a certain channel set is needed, either from the source or the remap.
+	const bool needs_r = remap_r || has_channel_r;
```
Comment (akien-mga) [inline editor/import/resource_importer_texture.cpp:514]: CI fails because this variable is unused.

File: editor/import/resource_importer_texture.cpp [hunk 2]
```diff
@@ -480,11 +482,126 @@ void ResourceImporterTexture::_remap_channels(Ref<Image> &r_image, ChannelRemap
...
+				could_not_expand = true;
+			}
+		} break;
+
+		default: {
+		} break;
+	}
+
+	if (could_not_expand) {
+		WARN_PRINT(vformat("Unable to expand image format %s's channels, converting to %s.", Image::get_format_name(original_format), Image::get_format_name(r_image->get_format())));
```
Comment (Calinou) [inline editor/import/resource_importer_texture.cpp:601]: Make the warning more precise:

```suggestion
		WARN_PRINT(vformat("Unable to expand image format %s's channels (the target format does not exist), converting to %s as a fallback.", Image::get_format_name(original_format), Image::get_format_name(r_image->get_format())));
```

**Review by Calinou — APPROVED** [review]
Tested locally with the MRP from https://github.com/godotengine/godot/issues/106422, it works as expected. Code looks good to me.

`master` | This PR
-|-
image | image

**Comment by LiveTrower** [comment]
I've tried various textures and combinations, and I found a detail that I don't quite understand.

I'm going to give two examples:

First, an RGB texture where we set the Green and Blue channels to Zero, leaving only the Red channel, gives us this result.
Channel_R

But if we change the Red channel to Zero and the Green channel to its default value, the Alpha channel appears, which didn't happen in the previous example.
Channel_G


Is this a bug?

**Comment by BlueCube3310** [comment]
> Is this a bug?

It is, I noticed it too but it looks like it's related to the `Image` function that detects the used channels. I'll look into it as well

**Comment by fire** [comment]
> It is, I noticed it too but it looks like it's related to the Image function that detects the used channels. I'll look into it as well 

does this need to be resolved before merge?

**Comment by BlueCube3310** [comment]
> > It is, I noticed it too but it looks like it's related to the Image function that detects the used channels. I'll look into it as well
> 
> does this need to be resolved before merge?

I figured out what causes this, it's a fairly simple fix but I would like to make a separate PR for that.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
