### PR TITLE
Fix editor colors reseting while the color chooser is still open

### LINKED ISSUE #113440: Unable to change theme color
### Tested versions

Godot 4.6 dev5

### System information

Godot v4.6.dev5 - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.21912.14) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 threads) - 15.93 GiB memory

### Issue description

It's impossible to change the theme color in the editor settings; after changing it, the color reverts to its previous state.
This happens with the base color and accent color.

### Steps to reproduce

1. Open the editor settings and go to the Theme section.
2. Try changing the color; it will return to its previous value.

Do not close the color selection window until the color has changed.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
If one would try to change a color setting in the editor (e.g. the base color), and lingered in the color picker before closing it, the color would reset to its default value.

This happens when the color preset is not set to "Custom", which is done automatically when when the color picker is _closed_, as it makes the inspector fire the `property_edited` signal, and then the modified property is checked.

To workaround this, the check is now done when `settings_changed` is fired instead.

Fixes #113440.

### CODE REVIEW

File: editor/settings/editor_settings_dialog.cpp [hunk 1]
```diff
@@ -65,8 +64,13 @@ void EditorSettingsDialog::_settings_changed() {
...
 
-void EditorSettingsDialog::_settings_property_edited(const String &p_name) {
-	String full_name = inspector->get_full_item_path(p_name);
+void EditorSettingsDialog::_settings_property_edited() {
+	Vector<String> changed = EditorSettings::get_singleton()->get_changed_settings();
+	if (changed.is_empty()) {
+		return;
+	}
+
+	String full_name = changed.get(changed.size() - 1);
```
Comment (KoBeWi) [inline editor/settings/editor_settings_dialog.cpp]:
```suggestion
	String full_name = changed[changed.size() - 1];
```
Although it would be more efficient to add some `get_last_changed_setting()` method, because the `changed` Vector is converted from HashSet.

**Review by KoBeWi — APPROVED** [review]
Fixes the bug.

File: editor/settings/editor_settings_dialog.cpp (hunk 1 above)
Comment (YeldhamDev) [reply editor/settings/editor_settings_dialog.cpp]: Good idea, but maybe as a separated PR? I don't know if a new method addition would get cherry-picked.

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.3.
