### PR TITLE
PathFollow3D update transform immediately by default

### LINKED ISSUE #95612: PathFollow3D progress and progress_ratio properties not working after upgrading from 4.2.2 to 4.3
### Tested versions

- Reproducible 4.3.stable
- Works in 4.2.2.stable

### System information

Godot v4.2.2.stable - Debian GNU/Linux 12 (bookworm) 12 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 960 (nvidia) - AMD FX(tm)-6300 Six-Core Processor (6 Threads)

### Issue description

PathFollow3D progress and progress_ratio properties are not working after upgrading from 4.2.2 to 4.3.  Running my game on 4.2.2 again afterwards works as expected.  In the inspector, I can manually adjust the properties and see the position move in the 3D view.
The full project is shared on GitHub : https://github.com/Pixel-Gladiator/LaserBall3D
Load it in 4.2.2 and the world resources populate as expected.
Load it in 4.3 and the world resources populate in a single location.
In both cases, world resources spawning off of a timer are added as expected.
I've shared videos of what it used to look like and what it looks like now on YouTube
https://www.youtube.com/channel/UCIIdIVhHBYRUmjfhPLQyY5Q

### Steps to reproduce

Load it in 4.2.2 and the world resources populate as expected.
Load it in 4.3 and the world resources populate in a single location.
In both cases, world resources spawning off of a timer are created as expected.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by xiongyaohua**
Fix https://github.com/godotengine/godot/issues/95612

### CODE REVIEW

File: scene/3d/path_3d.h [hunk 1]
```diff
@@ -124,7 +124,7 @@ class PathFollow3D : public Node3D {
 
 	PackedStringArray get_configuration_warnings() const override;
 
-	void update_transform(bool p_immediate = false);
+	void update_transform(bool p_immediate = true);
```
Comment (akien-mga) [inline scene/3d/path_3d.h:127]: Seems like the `p_immediate` argument should be removed together with the deferred branch. I don't see any code explicitly calling `update_transform(false)`, and the only `update_transform(true)` is in `tests/scene/test_path_follow_3d.h` and can now be simplified.

This would also restore consistency with PathFollow2D.

**Comment by kleonc** [comment]
> Fix #95612

Tested and confirmed.

File: scene/3d/path_3d.h (hunk 1 above)
Comment (akien-mga) [reply scene/3d/path_3d.h:127]: Bump. I could update the PR to remove it myself but it questions a lot of the changes added in #80233 that need to be reviewed.

The "deferred" mode referenced in multiple comments no longer exists as it's never used, and the need for `update_transform` that would just set the dirty flag before calling `_update_transform` is now put into question too.

Could you take a closer look and see what code should be changed as a consequence of this fix?

**Comment by kleonc** [comment]
Rebased, made the transforms update immediately, removed deferred path (as suggested in https://github.com/godotengine/godot/pull/96140#discussion_r1732887390), added some property guards to prevent unnecessary updates.

**Review by akien-mga — APPROVED** [review]

**Review by adamscott — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Comment by xiongyaohua** [comment]
@kleonc Thank you for completing this. Been quite busy lately, and really appreciate your help!

**Comment by Steinbeuge** [comment]
I've also been bitten by the 4.3 path issue

There is still an issue in 4.4 dev3, after instantiating the object, initialising the path with a zero value skips immediate update, using a value close to zero however does update.

.progress_ratio = 0.0
.progress = 0.0
.force_transform_update()
Does not force an update, using a value like 0.000001 does cause an update.

Because of this, objects that have the path3d and pathfollow3d as children, with the path3d set as TopLevel, and are copying transforms manually in script, do not start on their placed or spawned location. (I do it this way, and I imagine a lot of other people do to, because its really awkward and unintuitive to have a path3d as your top level object in the instance)

I'd suggest some kind of .update() function or .set_progress_ratio(value, true) that immediately updates the transforms?
Should I open a new ticket about this on 4.4 dev3?
