### PR TITLE
Fix broken Navigation Obstacle regression

### LINKED ISSUE #99271: NavigationObstacle2D's `affect_navigation_mesh` property no longer works
### Tested versions

Reproducible in builds after commit [07b7f76]

### System information

Godot v4.4.dev (07b7f7689) - Arch Linux # 1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 on Wayland - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (nvidia; 560.35.03) - AMD Ryzen 5 2600X Six-Core Processor (12 threads)

### Issue description

NavigationObstacle2D no longer affects NavigationRegion2D's navigation polygon during baking when its  `affect_navigation_mesh` property is set to to true. Checking ` carve_navigation_mesh` also makes no difference.

I have bisected the bug to commit 07b7f76 which was introduced in #98957.

### Steps to reproduce

- Create a `NavigationRegion2D` and set up a `NavigationPolygon` for it.
- Create a `NavigationObstacle2D` and either set its vertices or its radius, and position it so that the obstacle overlaps the navigation polygon.
- Add the obstacle to the `navigation_polygon_source_geometry_group` group and set up the `NavigationPolygon` such that it takes this node into account during baking (e.g. set `source_geometry_mode` to "Group with children")
- Check `affect_navigation_mesh`
- Bake the navigation polygon and observe that the obstacle has no effect.

Alternatively, download the MRP below, open the main scene, go to the `NavigationRegion2D` node and hit "Bake NavigationPolygon".

### Minimal reproduction project (MRP)

[obstacle_2d_baking_mrp.zip](https://github.com/user-attachments/files/17773419/obstacle_2d_baking_mrp.zip)

### PR DESCRIPTION
**Pull request by kiroxas**
Fix broken navigation regression.

The carved obstacles were not reapplied correctly.

Fixes [99271](https://github.com/godotengine/godot/issues/99271 )

### CODE REVIEW

**Comment by tracefree** [comment]
Just tested it out and confirm this resolves the issue, thank you for the quick fix!

**Review by smix8 — APPROVED** [review]

File: modules/navigation/2d/nav_mesh_generator_2d.cpp [hunk 1]
```diff
@@ -931,27 +930,48 @@ void NavMeshGenerator2D::generator_bake_from_source_geometry_data(Ref<Navigation
...
 
 	real_t agent_radius_offset = p_navigation_mesh->get_agent_radius();
 	if (agent_radius_offset > 0.0) {
 		path_solution = InflatePaths(path_solution, -agent_radius_offset, JoinType::Miter, EndType::Polygon);
 	}
 
-	if (obstruction_polygon_path_size > 0) {
-		obstruction_polygon_paths.resize(obstruction_polygon_path_size);
-		path_solution = Difference(path_solution, obstruction_polygon_paths, FillRule::NonZero);
+	// Apply obstructions that are not affected by agent radius, the ones with carve enabled
```
Comment (AThousandShips) [inline modules/navigation/2d/nav_mesh_generator_2d.cpp:949]:
```suggestion
	// Apply obstructions that are not affected by agent radius, the ones with carve enabled.
```
Per the [comment style](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#comment-style-guide).

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
