### PR TITLE
Shader Baker: Fix Linux export warning

### LINKED ISSUE #112462: Bake Shaders at Export for Linux: Property not found: 'rendering/rendering_device/driver.linux'.
### Tested versions

- Reproducible in Godot versions: 4.5.stable.official.876b29033 and 4.5.1.stable.official

### System information

Godot v4.5.stable - Ubuntu 24.04.3 LTS 24.04 on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (RPL-P) - 13th Gen Intel(R) Core(TM) i5-1340P (16 threads) - 15.28 GiB memory and Godot v4.5.1.stable - macOS Sequoia (15.6.1) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M2 (Apple8) - Apple M2 (8 threads) - 8.00 GiB memory

### Issue description

Warning appears if you are trying to export project for Linux with `Shaders Bake` enabled.
The warning is:  `WARNING: core/config/project_settings.cpp:404 - Property not found: 'rendering/rendering_device/driver.linux'.`
As i see there is no option `driver.linux` in the settings, only `driver.linuxbsd`.

Image

### Steps to reproduce

Export project for Linux with `Shaders Bake` enabled.

### Minimal reproduction project (MRP)

Eny project. Here, the empty one, for example.

[new-game-project.zip](https://github.com/user-attachments/files/23381570/new-game-project.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
We now have APIs exactly for this use case of querying project settings for a target platform instead of the host OS.

- Fixes #112462.

### CODE REVIEW

File: editor/export/shader_baker_export_plugin.cpp [hunk 1]
```diff
@@ -56,20 +56,15 @@ bool ShaderBakerExportPlugin::_is_active(const Vector<String> &p_features) const
...
-bool ShaderBakerExportPlugin::_initialize_container_format(const Ref<EditorExportPlatform> &p_platform, const Vector<String> &p_features, const Ref<EditorExportPreset> &p_preset) {
-	Variant driver_variant = GLOBAL_GET("rendering/rendering_device/driver." + p_platform->get_os_name().to_lower());
-	if (!driver_variant.is_string()) {
-		driver_variant = GLOBAL_GET("rendering/rendering_device/driver");
-		if (!driver_variant.is_string()) {
-			return false;
-		}
-	}
+bool ShaderBakerExportPlugin::_initialize_container_format(const Ref<EditorExportPlatform> &p_platform, const Ref<EditorExportPreset> &p_preset) {
+	String driver_variant = p_preset->get_project_setting("rendering/rendering_device/driver");
```
Comment (DarioSamo) [inline editor/export/shader_baker_export_plugin.cpp]: `get_project_setting` seems to return a Variant but the new code assumes it can be safely used as String (and stores it directly in one on a variable that specifies it's a variant). The original code didn't make this assumption and it checked for the type as well.

**Review by DarioSamo — APPROVED** [review]
Other than a minor code nitpick, the changes look good to me as long as `get_project_setting` works as described.

File: editor/export/shader_baker_export_plugin.cpp (hunk 1 above)
Comment (akien-mga) [reply editor/export/shader_baker_export_plugin.cpp]: Assigning a Variant to a String will convert it to String, which is something all Variant types support. It's highly unlikely for this value to be something else than a String, unless users manually edited the file to write invalid values. In such a case the resulting String (e.g. stringification of `42` as `"42"`) will just not match any driver and shader baking will be skipped.

We don't normally do extra validation of the result of `GLOBAL_GET` or related functions, e.g.:
```
editor/editor_data.cpp
1085:           Dictionary d = GLOBAL_GET("_global_script_class_icons");

editor/export/editor_export_platform_pc.cpp
72:             String export_renderer = GLOBAL_GET("rendering/renderer/rendering_method");

modules/godot_physics_2d/register_types.cpp
40:     bool using_threads = GLOBAL_GET("physics/2d/run_on_separate_thread");
```

Comment (DarioSamo) [reply editor/export/shader_baker_export_plugin.cpp]: That seems good to me, I wasn't clear if it was intentional or not as the name of the variable didn't change.

Comment (akien-mga) [reply editor/export/shader_baker_export_plugin.cpp]: Oh I thought `driver_variant` meant "the variant/flavor of driver", not referred to the Variant type. I can rename it to just `driver` then.

Comment (akien-mga) [reply editor/export/shader_baker_export_plugin.cpp]: I assigned the setting directly to `shader_container_driver` in the end, the intermediary variable didn't seem necessary.

**Comment by Repiteo** [comment]
Thanks!
