### PR TITLE
Fix onready vars / vars accessing class members if _ready / _init not present

### LINKED ISSUE #19548: Scripts don't recognize onready variables when there isn't a _ready() function
**Godot version:**
3.0.2 stable

**OS/device including version:**
MacBook Air (13-inch, Early 2014) (1,4 GHz Intel Core i5)
MacOS High Sierra 10.13.3

**Issue description:**
Consider these two scripts:
```python
extends Node2D

onready var testVariable = position

func _ready():
	pass
```
and:
```python
extends Node2D

# Comment the line below and it will work
onready var testVariable = position
```

They might appear to be equivalent, but only the first one works. The second shows an error saying that it can not find the position variable.

**Minimal reproduction project:**
[Onready Bug Test Project.zip](https://github.com/godotengine/godot/files/2099898/Onready.Bug.Test.Project.zip)

### PR DESCRIPTION
**Pull request by dragmz**
Fixes #19548

**Please review**
I'm assuming that the condition was supposed to check for a static function only as per http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html:
"When a function is static it has no access to the instance member variables"

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you amend the commit log to be more explicit (`git commit --amend`)? A commit log should explain what the commit does in a human-readable way, independently of the issue tracker (in `git log` you don't have the data from GitHub), see https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind for details.

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -34,7 +34,7 @@
 
 bool GDScriptCompiler::_is_class_member_property(CodeGen &codegen, const StringName &p_name) {
 
-	if (!codegen.function_node || codegen.function_node->_static)
+	if (codegen.function_node && codegen.function_node->_static)
```
Comment (karroffel) [inline modules/gdscript/gdscript_compiler.cpp]: Not exactly sure what the context of this method is, but this doesn't return `false` when `codegen.function_node` is `NULL` anymore while previously it did.

Not sure how important that is, if at all.

**Comment by vnen** [comment]
I don't think this is the right fix. I was investigating this right now and the problem is that the `_static` field is never set if it does not have an actual function in the code (i.e. it's generated by the compiler).

**Review by vnen — CHANGES_REQUESTED** [review]
The right fix would be to set the `_static` value even if the `_parse_function` is called with `NULL` (in this case it should be set to `false`).

Should be around here: https://github.com/godotengine/godot/blob/08c6cc668ac98773827d5007783f0b1ac29fd179/modules/gdscript/gdscript_compiler.cpp#L1490-L1493

**Comment by dragmz** [comment]
I'm not sure how setting _static = false helps here as the function_node is still NULL if _ready func is missing.

**Comment by vnen** [comment]
@dragmz true. Now I realize that **both** changes are needed. Because currently it's filling the `_static` field with garbage because it's never set (and the `rpc_mode` too).

But this PR is okay. The null check is not important because it's not accessed later.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.
