### PR TITLE
Android: Delete `.idsig` on One Click Deploy

### LINKED ISSUE #100101: *.idsig not removed after One Click Deploy
### Tested versions

- Reproducible in 4.4.dev4

### System information

Godot v4.4.dev4 - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 on Wayland - X11 display driver, Single-window, 1 monitor - OpenGL 3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 threads)

### Issue description

After clicking One Click Deploy and exporting to Android, temporary export apk is removed, but .idsig (which is artifact of signing) is not. This pollutes editor cache directory.

### Steps to reproduce

1. Use One Click Deploy to Android.
2. Open editor cache folder.
3. Notice tmpexport.*.apk removed, but tmpexport.*.apk.idsig is still there.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Summersay415**
Fixes #100101

### CODE REVIEW

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -2087,11 +2087,12 @@ Error EditorExportPlatformAndroid::run(const Ref<EditorExportPreset> &p_preset,
...
 
-#define CLEANUP_AND_RETURN(m_err)                         \
-	{                                                     \
-		DirAccess::remove_file_or_error(tmp_export_path); \
-		return m_err;                                     \
-	}                                                     \
+#define CLEANUP_AND_RETURN(m_err)                                    \
+	{                                                                \
+		DirAccess::remove_file_or_error(tmp_export_path);            \
+		DirAccess::remove_file_or_error(tmp_export_path + ".idsig"); \
```
Comment (adamscott) [inline platform/android/export/export_plugin.cpp:2093]: It could throw an error if the file wasn't signed yet.

```suggestion
		if (FileAccess::exists(tmp_export_path + ".idsig") { \
			DirAccess::remove_file_or_error(tmp_export_path + ".idsig"); \
		} \
```

Comment (Summersay415) [reply platform/android/export/export_plugin.cpp:2093]: But if export failed with no cresting APK at all? When removing file DirAccess will also throw an error. Should we do this check for both deletions then?

**Comment by Summersay415** [comment]
Okay I added check because we have `Signed` option.
So, can this be merged? It's not good to pollute /tmp directory...

**Review by syntaxerror247 — APPROVED** [review]
Looks good!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
