### PR TITLE
JSON parser fix

### LINKED ISSUE #40794: Validate_Json() and parse_json does not catch missing start "{" squirly bracket
**Godot version:**

3.2.2.stable.official

**OS/device including version:**

Windows 10

**Issue description:**

When testing Validate_Json() and parse_json, i found that it does not catch the missing start '{' ,but gladly continues and thinks its a valid JSON string, althoug prints out some thing, but not a JSON formated string.

**Steps to reproduce:**
1 remove the first squirly bracket
2 run example, no exception is thrown

**Minimal reproduction project:**

```
# correct string '{ "apa":12345,"epa":12345 }'

onready var parseTest ={}
onready var jsonString = ' "apa":12345,"epa":12345 }
func _ready() -> void:
	
	var a = validate_json(jsonString)
	
	if not a:
		parseTest = parse_json(jsonString)
		print("---------------------")
		print(parseTest)
	else:
		print(a)
```

### PR DESCRIPTION
**Pull request by naithar**
Related issue: https://github.com/godotengine/godot/issues/40794

Tested with:
```
func _ready():
	_check('"text"')
	_check('   "text"   ')
	_check('"10"')
	_check('10')
	_check('{}')
	_check('["a", 0]')
	_check('["a", 0, null]')
	_check(' { "a": "b" }')
	_check(' { "a": null }')
	_check(' { "a": 0 }')
	_check(' { "a": ["b"] }')
	_check(' { "a": {} }')
	print("should fail")
	_check('"a": 0 }')
	_check('{ "a": 0 ')
	_check('"a')
	_check('"a"0')
	_check('{}{}')
	_check('["a", 0')
	_check('["a", 0}')
	_check('{ ["a", 0] }')
	_check('true, false, [1,2,3]')


func _check(jsonString):
	var a = validate_json(jsonString)
	print('validation error: "{error}", result: "{json}"'.format({'error' : a, 'json' : parse_json(jsonString)}))
```
Some test cases could probably be added to the test added in https://github.com/godotengine/godot/pull/40795

Result:
```
2020-07-28 22:16:20.077650+0300 godot_4_test[14675:6335126] validation error: "", result: "text"
2020-07-28 22:16:20.077687+0300 godot_4_test[14675:6335126] validation error: "", result: "text"
2020-07-28 22:16:20.077716+0300 godot_4_test[14675:6335126] validation error: "", result: "10"
2020-07-28 22:16:20.077745+0300 godot_4_test[14675:6335126] validation error: "", result: "10"
2020-07-28 22:16:20.077775+0300 godot_4_test[14675:6335126] validation error: "", result: "{}"
2020-07-28 22:16:20.077811+0300 godot_4_test[14675:6335126] validation error: "", result: "[a, 0]"
2020-07-28 22:16:20.077855+0300 godot_4_test[14675:6335126] validation error: "", result: "[a, 0, Null]"
2020-07-28 22:16:20.077895+0300 godot_4_test[14675:6335126] validation error: "", result: "{a:b}"
2020-07-28 22:16:20.077939+0300 godot_4_test[14675:6335126] validation error: "", result: "{a:Null}"
2020-07-28 22:16:20.077978+0300 godot_4_test[14675:6335126] validation error: "", result: "{a:0}"
2020-07-28 22:16:20.078020+0300 godot_4_test[14675:6335126] validation error: "", result: "{a:[b]}"
2020-07-28 22:16:20.078063+0300 godot_4_test[14675:6335126] validation error: "", result: "{a:{}}"
2020-07-28 22:16:20.078077+0300 godot_4_test[14675:6335126] should fail
2020-07-28 22:16:20.078155+0300 godot_4_test[14675:6335126] validation error: "0:Expected 'EOF'", result: "Null"
2020-07-28 22:16:20.078232+0300 godot_4_test[14675:6335126] validation error: "0:Expected '}' or ','", result: "Null"
2020-07-28 22:16:20.078304+0300 godot_4_test[14675:6335126] validation error: "0:Unterminated String", result: "Null"
2020-07-28 22:16:20.078379+0300 godot_4_test[14675:6335126] validation error: "0:Expected 'EOF'", result: "Null"
2020-07-28 22:16:20.078450+0300 godot_4_test[14675:6335126] validation error: "0:Expected 'EOF'", result: "Null"
2020-07-28 22:16:20.078525+0300 godot_4_test[14675:6335126] validation error: "0:Expected ']'", result: "Null"
2020-07-28 22:16:20.078598+0300 godot_4_test[14675:6335126] validation error: "0:Expected ','", result: "Null"
2020-07-28 22:16:20.078667+0300 godot_4_test[14675:6335126] validation error: "0:Expected key", result: "Null"
2020-07-28 22:16:20.078748+0300 godot_4_test[14675:6335126] validation error: "0:Expected 'EOF'", result: "Null"
```

Testing same test cases with macOS's `JSONSerializer` produces same success/failure results.

*Bugsquad edit:* Fixes #40794.

### CODE REVIEW

**Comment by Xrayez** [comment]
Nice, ideally this is where #40795 could've been merged to `master` at this point, so you could rebase and see if my tests pass. If not, perhaps there might be something wrong with the test itself, so you'll may make changes in your PR to the test if necessary. 🙂

**Comment by Xrayez** [comment]
This fixes the first assert in #40795 (detected as parse error now)!

But this assert fails:
```
D:\src\godot\tests\test_json.h(52): ERROR: CHECK( parsed.get_type() != Variant::STRING ) is NOT correct!
  values: CHECK( 4 != 4 )
  logged: Should not prematurely parse as a string.
```

Do you think it should return the string or return empty `Variant` instead?

**Comment by naithar** [comment]
@Xrayez I've added results reset for malformed json, test case should not be failing now

File: core/io/json.cpp [hunk 1]
```diff
@@ -453,5 +448,18 @@ Error JSON::parse(const String &p_json, Variant &r_ret, String &r_err_str, int &
...
+	// Check if EOF is reached
+	// or it's a type of the next token.
+	if (err == OK && idx < len) {
+		err = _get_token(str, idx, len, token, r_err_line, r_err_str);
+
+		if (err || token.type != TK_EOF) {
+			r_err_str = "Expected 'EOF'";
+			// Reset return value to empty `Variant`
+			r_ret = Variant();
+			return ERR_PARSE_ERROR;
```
Comment (Xrayez) [inline core/io/json.cpp:460]: Yeah just tested now, I confirm it resets the value to `Variant()` (aka `null` in GDScript), all assertions in #40795 pass!

This is the case where I'm not really sure whether returning a "half-way" token even on parse error is intended, but I'm not sure if this "bug" was used as a "feature" before. 🙂

**Review by Calinou — APPROVED** [review]
I think we should merge this only in `master` for now, and then cherry-pick this to the `3.x` branch after 3.3 is released to avoid introducing regressions in 3.3.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
