### PR TITLE
Windows: Fall back to D3D12 if Vulkan is not supported and vice versa

### LINKED ISSUE #94760: Windows PC without Vulkan or OpenGL should default to Direct3D12
### Tested versions

- Reproducible in Godot 4.3-rc1 for Windows x64 and arm64

### System information

Windows 11 (ARM64) - Godot 4.3-rc1

### Issue description

I have a Windows 11 ARM64 laptop (Samsung Galaxy Book Go) that Qualcomm decided to only give it DirectX support.

It might be a good idea to have this workflow for deciding automatically which rendering driver should Godot use when starting the editor or a game:
- Method: If one is not available, check the next one. If it's not the recommended one (project is forward+, only opengl3 is available), just give a warning instead of exiting.
- Driver priorities (native, most performant, compatibility): Vulkan, Direct3D12, OpenGL3, ANGLE.

Although I'm just posting this strange case anyone would like to check it, but I believe it should have the lowest priority, as these devices currently are just residual.

PS: Congrats to the team on the recent progresses on Direct3D and Windows on ARM! 👏🥳

### Steps to reproduce

- When I start the editor (4.3-rc1 x64), Godot detects that the laptop doesn't support OpenGL and uses the ANGLE backend for the project selector dialog.
Captura de pantalla 2024-07-25 234422

- When I select a project that uses the Forward+ renderer, it says that Vulkan is unavailable and that I should force the compatible opengl3 driver:
Captura de pantalla 2024-07-25 234623

- If I enforce the d3d12 rendering driver, it seems to initialize correctly for the project manager and I can get into the editor after that:
Captura de pantalla 2024-07-25 235217

- I got to export a game with the ARM64 template, but when trying to run the standalone game, this message appeared once more:
Captura de pantalla 2024-07-25 235756

- But after enforcing the d3d12 driver for the standalone executable, it worked and performed as expected. It was nice to see Arm64 as the executable architecture in the process list:
Captura de pantalla 2024-07-26 000039

### Minimal reproduction project (MRP)

"Game Base 2D" from the Assets library is good enough.

### PR DESCRIPTION
**Pull request by kus04e4ek**
* Fixes: #94760.

Similar approach to `rendering/gl_compatibility/fallback_to_angle`, `rendering/gl_compatibility/fallback_to_gles` and `rendering/gl_compatibility/fallback_to_native`.
Can be tested with this (with this Godot will always try to fall back to another driver):
```diff
diff --git a/platform/windows/display_server_windows.cpp b/platform/windows/display_server_windows.cpp
index b8fcab64177..36cf4e10bd3 100644
--- a/platform/windows/display_server_windows.cpp
+++ b/platform/windows/display_server_windows.cpp
@@ -5928,7 +5928,7 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
 #endif
 
 	if (rendering_context) {
-		if (rendering_context->initialize() != OK) {
+		if (true) {
 			bool failed = true;
 #if defined(VULKAN_ENABLED)
 			bool fallback_to_vulkan = GLOBAL_GET("rendering/rendering_device/vulkan/fallback_to_vulkan");

```

### CODE REVIEW

**Comment by Calinou** [comment]
Note that the original issue also refers to PCs without OpenGL support (i.e. ARM laptops without the compatibility pack installed). Falling back to Direct3D 12 on those would imply using a different rendering method – and therefore different visuals – unless ANGLE is used. I expect ANGLE to be quite a bit slower than a native D3D12 implementation.

Either way, this might be worth its own proposal so you can choose which rendering methods can fall back to other ones (e.g. falling back to Compatibility if Forward+/Mobile is not supported, or vice versa).

**Comment by kus04e4ek** [comment]
Not quite sure I understood your comment correctly.

> Note that the original issue also refers to PCs without OpenGL support (i.e. ARM laptops without the compatibility pack installed). Falling back to Direct3D 12 on those would imply using a different rendering method.

This PR doesn't do it, it will only fall back to Direct3D 12 from Vulkan. If native OpenGL is not supported Godot already falls back to ANGLE on Windows.

> Either way, this might be worth its own proposal so you can choose which rendering methods can fall back to other ones (e.g. falling back to Compatibility if Forward+/Mobile is not supported, or vice versa).

Agree, I think this PR is ok as is for 4.3 cause Godot already falls back to different rendering drivers within the same rendering method, this can be improved in future versions.

**Comment by bruvzg** [comment]
> Note that the original issue also refers to PCs without OpenGL support (i.e. ARM laptops without the compatibility pack installed). Falling back to Direct3D 12 on those would imply using a different rendering method – and therefore different visuals – unless ANGLE is used. I expect ANGLE to be quite a bit slower than a native D3D12 implementation.

Currently, we aren't even trying to load native GL on ARM64 if engine was compiled with ANGLE, it's switching to ANGLE (over D3D11) automatically.

File: main/main.cpp [hunk 1]
```diff
@@ -1956,6 +1956,9 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
 		GLOBAL_DEF_RST_NOVAL(PropertyInfo(Variant::STRING, "rendering/rendering_device/driver.android", PROPERTY_HINT_ENUM, driver_hints), default_driver);
 		GLOBAL_DEF_RST_NOVAL(PropertyInfo(Variant::STRING, "rendering/rendering_device/driver.ios", PROPERTY_HINT_ENUM, driver_hints), default_driver);
 		GLOBAL_DEF_RST_NOVAL(PropertyInfo(Variant::STRING, "rendering/rendering_device/driver.macos", PROPERTY_HINT_ENUM, driver_hints), default_driver);
+
+		GLOBAL_DEF_RST("rendering/rendering_device/vulkan/fallback_to_vulkan", true);
+		GLOBAL_DEF_RST("rendering/rendering_device/d3d12/fallback_to_d3d12", true);
```
Comment (bruvzg) [inline main/main.cpp:1961]: Wouldn't it be clearer to have it named `rendering/rendering_device/d3d12/fallback_to_vulkan` and `rendering/rendering_device/vulkan/fallback_to_d3d12`, since it's Direct3D falling back to Vulkan and vice versa? Or have it directly under the `rendering/rendering_device/`

**Review by bruvzg — APPROVED** [review]

File: main/main.cpp (hunk 1 above)
Comment (kus04e4ek) [reply main/main.cpp]: Moved to `rendering/rendering_device/`

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
