### PR TITLE
Fix dotnet class lookup returning modified names instead of engine names

### LINKED ISSUE #111990: [C#][4.5.1]: GlobalClass that extends HttpRequest does not show up in the global class hierarchy
### Tested versions

* Reproducible in v4.5.1.stable.mono
* Older versions not tested

### System information

Windows 11 - Godot v4.5.1.stable.mono - Compatibility

### Issue description

I tried to create an async extension of HttpRequest but it simply does not show up in the global class hierarchy:
```csharp
[GlobalClass]
public partial class AsyncHttpRequest : HttpRequest
{
    [Export] public string BaseAddressLink { get; set; } = "";

    [Signal] public delegate void RequestFinishedEventHandler();

    private bool _isRequesting;
    
    public async Task<HttpResult> RequestAsync(string endpoint,
        string[] customHeaders = null,
        HttpClient.Method method = HttpClient.Method.Get,
        string requestData = "")
    {
        if (_isRequesting)
            return HttpResult.FromError(Error.Busy);

        _isRequesting = true;
        try
        {
            var error = Request($"{BaseAddressLink}/{endpoint}", customHeaders, method, requestData);
            if (error != Error.Ok) return HttpResult.FromError(error);

            var args = await ToSignal(this, HttpRequest.SignalName.RequestCompleted);
            EmitSignalRequestFinished();
            return HttpResult.FromSynchronousRequest(args);
        }
        finally
        {
            _isRequesting = false;
        }
    }
}
```

### Steps to reproduce

- Create a new script
- Extend HttpRequest
- Annotate as GlobalClass
- Build
- Check "add new node" menu

### Minimal reproduction project (MRP)

I do not think it is necessary for this. It is a small bug that is probably well known (and maybe even an intenional feature).

### PR DESCRIPTION
**Pull request by kevinlam508**
Fixes #111247
Fixes #111990

Side effect of #87890 combined with #69547 which lines up with the versions that had the issues.

Issue was that the script bridge was returning the C# names instead of the engine names, so inheritance checks fail from using the wrong name. This affected anything renamed in #69547, which thankfully already set up the needed data to fix the bug.

image

Also confirmed classes that don't have `GodotClassNameAttribute` are unaffected by this change. (See `TestControl`)
image

### CODE REVIEW

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs [hunk 1]
```diff
@@ -250,7 +250,9 @@ internal static unsafe void GetGlobalClassName(godot_string* scriptPath, godot_s
                 }
                 if (!foundGlobalBaseScript)
                 {
-                    *outBaseType = Marshaling.ConvertStringToNative(native.Name);
+                    // Type name may have been changed to follow .Net conventions.
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs]: Not sure the comment is entirely necessary, but it should at least use the proper casing for the .NET brand name.

```suggestion
                    // Type name may have been changed to follow .NET conventions.
```

**Review by raulsntos — APPROVED** [review]
Nice catch, thanks! Tested and works as expected.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs (hunk 1 above)
Comment (kevinlam508) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs]: Removed the comment instead since it's pretty self explanatory. Habit from personal work.

**Comment by Repiteo** [comment]
Thanks!
