### PR TITLE
Fixes for windows in X11 tiling WMs

### LINKED ISSUE #37930: Godot 4.0.dev editor behaves weird while using i3wm (and maybe other tilling wm's)
**Godot version:** 4.0.dev

**OS/device including version:** Manjaro + i3

**Issue description:** The new editor behaves weird while using i3wm (and maybe other tilling wm's). I know version 4 is still in development, i just wanted to report that!
image
The image below is when clicking the "Editor"
image
The image below is when click the 3 vertical dots
image

**Steps to reproduce:** Use i3

**Minimal reproduction project:** I don't need to provide a project because its not a project specific

### PR DESCRIPTION
**Pull request by deralmas**
Fixes #37930

This PR aims to fix various window issues on the platform "linuxbsd" regarding titling WMs.
All popups seem to work intermittently, behaviour which i believe is caused by the current implementation of [`_create_window()`](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/display_server_x11.cpp#L3174)

The current way of creating windows works by mapping them before changing their properties.
This approach works on floating window based WMs but not on tiling ones, which as soon as they are mapped get resized to full screen and get cleared of most of their properties, as shown in this part of an i3 debug log:
>09/05/2020 03:01:22 - WM_CLASS changed to Godot_Engine (instance), [PROJECT_NAME] (class)
09/05/2020 03:01:22 - WM_NAME changed to "Godot"
09/05/2020 03:01:22 - Using legacy window title. Note that in order to get Unicode window titles in i3, the application has to set _NET_WM_NAME (UTF-8)
09/05/2020 03:01:22 - window.c:window_update_name:64 - _NET_WM_NAME not specified, not changing
09/05/2020 03:01:22 - window.c:window_update_leader:139 - CLIENT_LEADER not set on window 0x05a00053.
09/05/2020 03:01:22 - window.c:window_update_transient_for:164 - TRANSIENT_FOR not set on window 0x05a00053.
09/05/2020 03:01:22 - window.c:window_update_strut_partial:189 - _NET_WM_STRUT_PARTIAL not set.
09/05/2020 03:01:22 - window.c:window_update_role:214 - WM_WINDOW_ROLE not set.
09/05/2020 03:01:22 - window.c:window_update_hints:377 - WM_HINTS not set.
09/05/2020 03:01:22 - window.c:window_update_normal_hints:291 - Clearing maximum size 
09/05/2020 03:01:22 - window.c:window_update_normal_hints:312 - Clearing size increments
09/05/2020 03:01:22 - window.c:window_update_normal_hints:326 - Clearing base size
09/05/2020 03:01:22 - window.c:window_update_normal_hints:335 - Setting geometry x=1616 y=87 w=294 h=218
09/05/2020 03:01:22 - window.c:window_update_normal_hints:359 - Clearing aspect ratios

This whole issue is all pretty messy as it seems to happen in two different processes at the same time, so the results vary a little sometimes, letting the window work by sheer luck.
By mapping the window later, we avoid all of this.

Almost everything works, but there is some stuff left to do, so i'm making this a draft PR. There are also some other issues, but they seem related to X11 in general, such as focus(#37531) and offset(#38591) related ones.

Edit: made the issue clearer

### CODE REVIEW

**Comment by akien-mga** [comment]
Note that one of your commit includes `modules/stXI98cE` which is a temporary binary from the compiler, it should be removed by amending the commit.

**Comment by Riteo** [comment]
Oh, sorry, gonna fix it immediately!

**Comment by Riteo** [comment]
I tried removing it, only changed the latest commit, i'm going to see how to remove it later.

**Comment by groud** [comment]
Oh, nice !
I am eager to see the result, as my awesomeWM doesn't like Godot that much for now. :D

**Comment by Riteo** [comment]
I'm trying to keep this PR as minimal as possible, but there is a little change in the generic DisplayServer implementation by adding `show_window(WindowID p_id)` to it, and requiring first to create a window, then setting its properties, and only then showing it. This also changes other classes creating a window, but for now only 2 were changed.

All platforms seem to have a "show window" function, but if one doesn't have it and directly shows one on creation, probably setting a window's properties after showing will work. In that case an empty implementation of `show_window(WindowID p_id)`should work. For now, its default implementation throws an error regarding missing window support.

**Comment by EIREXE** [comment]
Is this also related to godot not getting the proper window ID for the game until it's started?

**Comment by Riteo** [comment]
I don't think so, but i may be not fully get what you're referring to. This PR fixes some issues with screen sized popups on tiling window managers

**Comment by Riteo** [comment]
After some time, as I got the opportunity to work on this again, a lot of issues seem to have been fixed in one form or the other, leaving this PR usable, I tried it a bit and seems to work quite well. Still, without this PR, there are some tiling WM specific issues, so I just got to implement the other platforms and I think that this PR will be ready for review!

**Comment by Riteo** [comment]
Ok, so now i should have implemented `show_window` on Windows, but there's a big issue: MacOS.
Currently I have no way of compiling nor testing for this platform. Should I add a dummy implementation of `show_window`(that should still work) and set this PR as ready for review?

**Comment by Riteo** [comment]
Oh well, after some testing i found some other issues, i'm aware of them and i'm working on it.

**Comment by bruvzg** [comment]
> but there's a big issue: MacOS.

Relevant core for macOS: 

Split this part to the `show_window` function:
https://github.com/godotengine/godot/blob/a5fb4451210625702474a8fac1dd880e78a409e9/platform/osx/display_server_osx.mm#L2320-L2324

and replace this line with `show_window(MAIN_WINDOW_ID, 0);`:

https://github.com/godotengine/godot/blob/a5fb4451210625702474a8fac1dd880e78a409e9/platform/osx/display_server_osx.mm#L3758

**Comment by Riteo** [comment]
Thanks! I'll implement 'show_window' for MacOS with your changes ASAP!
Btw, the previously mentioned issues were caused by some mistake I made during my testing(I should really stop doing this stuff at 5 AM). Still, I'll keep an eye open for any issue.

File: platform/osx/display_server_osx.mm [hunk 1]
```diff
@@ -2317,12 +2317,16 @@ static void displays_arrangement_changed(CGDirectDisplayID display_id, CGDisplay
 			window_set_flag(WindowFlags(i), true, id);
 		}
 	}
+
+	return id;
+}
+
+void DisplayServerOSX::show_window(const WindowData &wd, uint32_t p_flags) {
```
Comment (bruvzg) [inline platform/osx/display_server_osx.mm:2324]: It's `... show_window(WindowID p_id ...` on other platforms, probably should be the same here. And definition is missing from `display_server_osx.h`.

```obj-c++
void DisplayServerOSX::show_window(WindowID p_id, uint32_t p_flags) {
	WindowData &wd = windows[p_id];
	....
```

Comment (Riteo) [reply platform/osx/display_server_osx.mm:2324]: oh yeah sorry, i messed up, i was distracted and wrote without thinking too much. I should be more careful while writing code i can't compile eheh. I'll fix it immediately!

**Comment by Riteo** [comment]
It doesn't want to compile? This is confusing.
The latest check is giving an error on a line that i removed. What's going on?

**Comment by bruvzg** [comment]
> What's going on?

It's probably still running previous build, not sure how GitHub Actions handle it, but Travis only cancels old build if it's not started.

**Comment by Riteo** [comment]
Well, my new commit(that i'm testing before pushing) will surely freshen it up.

**Comment by Riteo** [comment]
What? Github actions still believes that there's that line! Does it really not compile on MacOS or is actions messed up?

File: platform/osx/display_server_osx.h [hunk 2]
```diff
@@ -230,6 +230,7 @@ class DisplayServerOSX : public DisplayServer {
 	virtual Vector<int> get_window_list() const override;
 
 	virtual WindowID create_sub_window(WindowMode p_mode, uint32_t p_flags, const Rect2i &p_rect = Rect2i()) override;
+	virtual void show_window(WindowID p_id, uint32_t p_flags) override;
```
Comment (bruvzg) [inline platform/osx/display_server_osx.h:233]: You have not removed `p_flags` from macOS version.

Comment (Riteo) [reply platform/osx/display_server_osx.h:233]: oooh, that's why! Very very sorry, i was convinced that the issue was still that line!

**Comment by bruvzg** [comment]
> What? Github actions still believes that there's that line! Does it really not compile on MacOS or is actions messed up?

Try squashing commits (it's necessary to do it before merging anyway), see: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#modifying-a-pull-request.

File: platform/osx/display_server_osx.h (hunk 2 above)
Comment (Riteo) [reply platform/osx/display_server_osx.h:233]: Fixing it right now!

**Comment by Riteo** [comment]
Ok, I hope to have squashed the pr correctly. I tried it on linux and a bit on wine(yeah, it isn't the most accurate way of testing it, but it works), but I have no way of testing it on MacOS. Still, the PR should be done. Setting it as ready for review!

**Comment by akien-mga** [comment]
CC @vnen @groud - since you had issues with tiling WMs, could either of you test this PR and confirm the fix?

**Comment by groud** [comment]
Ok I've just tested the PR. Generally, this works a lot better than before, the popups and subwindows work great.

The only problem I found is that, when I disable the tiling (awesomewm allows me to do so), the popup do not pop at the correct position anymore. I figured out that this position was the one chosen by my windows manager to open a new window. 
So basically it's like the popup was considered as a normal window and not moved at the correct position anymore. See the screenshot:

2020-07-23-185354_3840x1600_scrot

When tiling is activated it works correctly though.

**Comment by Riteo** [comment]
Do you have multiple screens? It looks a lot like the stuff that https://github.com/godotengine/godot/pull/37506 is trying to fix.
The fact that it works in tiling mode confuses me though. I'll investigate further.

**Comment by groud** [comment]
> Do you have multiple screens? It looks a lot like the stuff that #37506 is trying to fix.

No I have only one screen (at least active).

We have to make sure this PR does not break the situation for any non-tiling WM though. If someone could test that :)

**Comment by Riteo** [comment]
> Ok I've just tested the PR. Generally, this works a lot better than before, the popups and subwindows work great.
> 
> The only problem I found is that, when I disable the tiling (awesomewm allows me to do so), the popup do not pop at the correct position anymore. I figured out that this position was the one chosen by my windows manager to open a new window.
> So basically it's like the popup was considered as a normal window and not moved at the correct position anymore. See the screenshot:
> 
> 2020-07-23-185354_3840x1600_scrot
> 
> Edit: Note that all other subwindows are popped there too, not only popups.
> 
> When tiling is activated it works correctly though.

I did a quick test before going to bed, and I can't reproduce this issue on i3.

**Comment by groud** [comment]
> I did a quick test before going to bed, and I can't reproduce this issue on i3.

Ok. In any case this drastically improves the situation anywayu. It would be good if someone could test the PR on a non-tiling WM though, but on my side it looks good to merge.

**Comment by akien-mga** [comment]
Tested on KDE Plasma / KWin with e7a56a245461e49c2950ee1cc3442f33e792430a + this PR, it seems to work fine.

I get an error when I select a node in the Create New Node dialog, but it seems unrelated to this PR (happens without it too):
```
ERROR: Condition "!windows.has(p_window)" is true. Returning: -1
   at: window_get_current_screen (platform/linuxbsd/display_server_x11.cpp:807)
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by opl-** [comment]
Can confirm that this PR greatly improved usability on KDE, making both context menus and dialogs render much quicker and without visual artifacts that were visible before (the windows were displaying pixels that were below them when they were created until the first render).

It did however reveal some issues in the X11 display server implementation that makes all the context menus and popups (probably others too) appear in the top left corner of the screen or around the main window, regardless of the requested position. I believe I have found the cause of this tonight. Will try to implement that fix and PR tomorrow.

**Comment by reduz** [comment]
This breaks popups on Stock Ubuntu (Gnome), I suggest reverting until we figure out whats going on, then try the PR again.

**Comment by reduz** [comment]
image

**Comment by reduz** [comment]
Please test in stock Ubuntu, when it works attempt the PR again.

**Comment by reduz** [comment]
Another problem with this PR is that simple popups (For value editors) do not get focus instantly like they normally did. Please check this too.

**Comment by pouleyKetchoupp** [comment]
I found out that with these changes, `XMapWindow` is not called anymore when creating sub windows, which might be part of the problem with popups on Ubuntu.

But just adding `show_window` after `_create_window` for sub windows doesn't fix the issue, so there's something else going wrong with the order of calls.

**Comment by pouleyKetchoupp** [comment]
@Riteo After some more research, it seems `XMapWindow` is actually not needed for sub windows, but it requires some extra fixes to work correctly on Ubuntu with Gnome. So I think this PR goes in the right direction, and I'm going to include it along with a new PR for some general fixes for popups I'm working on (I'll co-author you). When it's ready we'll make sure tiling VMs are still working with my extra changes :)
