### PR TITLE
Fix Android disabling splash screen Show Image

### LINKED ISSUE #69316: Disabling splash screen Show Image project setting has no effect on Android
### Godot version

3.5.1 stable

### System information

Android 11 (GLES2)

### Issue description

image

Hey guys, I caught a bug in Godot 3.5.1

When you unselect "Show Image", it won't show image on PC versions but on Android, it completely ignores that and keep showing the image normally

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by scgm0**
* *Bugsquad edit, fixes: #69316*

### CODE REVIEW

**Comment by AThousandShips** [comment]
Is there an open issue for this? If not please open one

**Comment by scgm0** [comment]
> Is there an open issue for this? If not please open one这有一个开放的问题吗？如果没有请打开一个

https://github.com/godotengine/godot/issues/69316
Sorry, I'm not familiar with github

**Review by m4gr3d — APPROVED** [review]
Looks good! Thanks for the fix!

File: platform/android/export/export_plugin.cpp [hunk 1]
```diff
@@ -1542,18 +1542,32 @@ void EditorExportPlatformAndroid::_process_launcher_icons(const String &p_file_n
...
 
-	if (!project_splash_path.is_empty()) {
-		splash_image.instantiate();
-		print_verbose("Loading splash image: " + project_splash_path);
-		const Error err = ImageLoader::load_image(project_splash_path, splash_image);
-		if (err) {
-			if (OS::get_singleton()->is_stdout_verbose()) {
-				print_error("- unable to load splash image from " + project_splash_path + " (" + itos(err) + ")");
+	// Setup the splash bg color
+	bool bg_color_valid;
```
Comment (YuriSizov) [inline platform/android/export/export_plugin.cpp:1549]: Needs to be initialized.

Comment (YuriSizov) [reply platform/android/export/export_plugin.cpp:1549]: Though maybe it can even be done without a boolean, using `get_setting("application/boot_splash/bg_color", boot_splash_bg_color)`.

Comment (scgm0) [reply platform/android/export/export_plugin.cpp:1549]: > Though maybe it can even be done without a boolean, using `get_setting("application/boot_splash/bg_color", boot_splash_bg_color)`.

It was already there, I wasn't sure what it did, I just changed its position

**Comment by AThousandShips** [comment]
Your rebase went wrong and you have included commits from others you need to restore this

**Comment by AThousandShips** [comment]
Please do:
```
git reset --hard e325567
```
And then add your fix to the default value with
```
git commit --amend
```
And finally
```
git push --force
```

**Comment by scgm0** [comment]
> Please do:
> 
> ```
> git reset --hard e325567
> ```
> 
> And then add your fix to the default value with
> 
> ```
> git commit --amend
> ```
> 
> And finally
> 
> ```
> git push --force
> ```

Thanks! I'm so stupid.（

File: platform/android/export/export_plugin.cpp [hunk 2]
```diff
@@ -1542,18 +1542,32 @@ void EditorExportPlatformAndroid::_process_launcher_icons(const String &p_file_n
...
 	String project_splash_path = GLOBAL_GET("application/boot_splash/image");
 
-	if (!project_splash_path.is_empty()) {
-		splash_image.instantiate();
-		print_verbose("Loading splash image: " + project_splash_path);
-		const Error err = ImageLoader::load_image(project_splash_path, splash_image);
-		if (err) {
-			if (OS::get_singleton()->is_stdout_verbose()) {
-				print_error("- unable to load splash image from " + project_splash_path + " (" + itos(err) + ")");
+	// Setup the splash bg color
```
Comment (AThousandShips) [inline platform/android/export/export_plugin.cpp:1548]:
```suggestion
	// Setup the splash bg color.
```

**Review by AThousandShips — APPROVED** [review]
Looks good otherwise, just the comment and squashing :)

**Comment by AThousandShips** [comment]
Not at all! Git can be a mess to figure out and there are plenty of pitfalls

**Comment by scgm0** [comment]
> Not at all! Git can be a mess to figure out and there are plenty of pitfalls

Should be fine, thanks!

File: platform/android/export/export_plugin.cpp (hunk 1 above)
Comment (YuriSizov) [reply platform/android/export/export_plugin.cpp]: That's okay for now 👍  But we should probably fix it at some point.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
