### PR TITLE
Fix completion for built-in load() function

### LINKED ISSUE #43349: Completion for built-in load() function doesn't work
Same as closed: https://github.com/godotengine/godot/issues/27078
Related to: https://github.com/godotengine/godot/issues/40933

**Godot version:**

v4.0.dev.custom_build.8e13b93bf

**OS/device including version:**

Windows

**Issue description:**
No resource paths are suggested when you write `load(|)` where "|" is the cursor position.

**Steps to reproduce:**
Write `load(` in a script.

### PR DESCRIPTION
**Pull request by gvekan**
image
Screenshoot from https://github.com/godotengine/godot/pull/37232 because it solves the same issue in an older version of `master`.
Fixes https://github.com/godotengine/godot/issues/43349
_Edit: Fixes "no argument hint immediately after open a bracket" for built-in functions mentioned in https://github.com/godotengine/godot/issues/40933_

### CODE REVIEW

**Comment by gvekan** [comment]
@vnen I asked in my first comment for a better load function detection and now I've fixed it myself because I realized that I had a stupid solution. It's ready for review.

**Comment by vnen** [comment]
It looks mostly okay. What concerns me is that if someone adds extra arguments to the function it breaks parsing. I know the function only accepts 1 argument, so it wouldn't work anyway, but I prefer that to be checked in the second pass (the analyzer), which does the type checking as well. And error recovery in the parser isn't really good yet.

What I would do is create a `CompletionType` variable and set it to `COMPLETION_CALL_ARGUMENTS` by default. Then if the function is `load` (as you are checking here) you just set the type to be `COMPLETION_RESOURCE_PATH` instead. Then we don't need to repeat the parsing logic. I know this would (wrongly) show path completion to extra arguments in `load` which are not valid but it's still better in the code. Alternatively you could add a check in the loop to only use this completion type in the first iteration so the second argument doesn't show completion.

**Comment by gvekan** [comment]
@vnen I've implemented it your way. My first solution did the parsing in the same way as for `preload` in `parse_preload`, maybe it is a difference because it is prefix and not infix or because it is not a call or do `parse_preload` also break the parsing?

Anyhow, the new solution also fixes the issue with no hint showing for calls when you have empty brackets.

**Comment by vnen** [comment]
> @vnen I've implemented it your way. My first solution did the parsing in the same way as for `preload` in `parse_preload`, maybe it is a difference because it is prefix and not infix or because it is not a call or do `parse_preload` also break the parsing?

I think `preload` will also break parsing if you try to use multiple arguments. But it's a special case because it's not really a function: it's a GDScript keyword, so it requires a special treatment. Eventually we could allow multiple arguments in the parser for the sake of better error reporting, but this is out of scope for this PR.

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -2486,13 +2486,16 @@ GDScriptParser::ExpressionNode *GDScriptParser::parse_call(ExpressionNode *p_pre
 		}
 	}
 
-	if (!check(GDScriptTokenizer::Token::PARENTHESIS_CLOSE)) {
+	if (previous.type == GDScriptTokenizer::Token::PARENTHESIS_OPEN) {
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.cpp:2489]: I guess this still works since the check is done in the loop. But in this case I believe this will always be true since it's the token that makes this function be called. In this case I think we can remove the `if`.

**Review by vnen — CHANGES_REQUESTED** [review]

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (gvekan) [reply modules/gdscript/gdscript_parser.cpp:2489]: I thought about that, but the `GDScriptTokenizer::Token::SUPER` token also triggers this function so if we have `super.call|` for example, the condition is `false`. Because `consume(...PARENTHESIS_OPEN...` doesn't exit if `false`.
https://github.com/godotengine/godot/blob/9185b34890141b4b96a9fbb1500de35e9ca0d356/modules/gdscript/gdscript_parser.cpp#L2456-L2463

Comment (vnen) [reply modules/gdscript/gdscript_parser.cpp:2489]: Yeah, but at this point the `super` is already handled. It doesn't exit on this `consume` to keep parsing and detect other potential errors, so you can assume the parenthesis is there.

Comment (gvekan) [reply modules/gdscript/gdscript_parser.cpp]: Okay, I fixed it.

**Review by vnen — APPROVED** [review]
LGTM. Thanks a ton!

**Comment by akien-mga** [comment]
Thanks!
