### PR TITLE
Do not bother with line colors if `line_number_gutter` is not yet calculated

### LINKED ISSUE #81135: `Index p_gutter = -1 is out of bounds` error when saving file in external editor
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Godot v4.2.dev3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

You get these errors when saving file in external editor:

kuva

```gdscript
Godot Engine v4.2.dev3.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
[LSP] Connection Taken
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
```

### Steps to reproduce

`Text Editor | Appearance | Highlight Type Safe Lines` setting must be on.

My external editor is vscode version 1.18.1 with godot-tools version 1.3.1.

1. Open attached minimal reproduction project (Project is created from a large project by chopping off stuff that didn't seem to affect the error.)
2. Open `stages.gd` in vscode
3. Press Ctrl-S to save `stages.gd` in vscode
4. Change focus back to Godot 

Sometimes the errors are displayed immediately after step 3, sometimes step 4 is needed.

### Minimal reproduction project

I left some files in the `.godot` folder as I suspect that the editor layout might have something to do with the bug.

[g42_p_gutter.zip](https://github.com/godotengine/godot/files/12467771/g42_p_gutter.zip)

### PR DESCRIPTION
**Pull request by miv391**
Fixes https://github.com/godotengine/godot/issues/81135

When code files are changed with an external editor, all files in script list are reloaded. Files are validated and then `_update_errors()` is called for each file and type safe lines are colored by `_update_errors()` calling `TextEdit`'s `set_line_gutter_item_color()` with `line_number_gutter` as a parameter. `line_number_gutter` is however calculated only when a file is opened to the edit view. When a project is opened, only one file is opened to edit view and only that file's `line_number_gutter` is calculated. If any file is now saved in external editor, all other files have `line_number_gutter == -1` and the error message "Index p_gutter = -1 is out of bounds" is spawned for every line of those files. If the user opens all files in script list to the edit view _before_ saving in the external editor, every file will have it's `line_number_gutter` calculated and there will be no errors.

~~This is now fixed simply by skipping the setting of line colors altogether if the `line_number_gutter` is not yet calculated. The script is not shown, so it doesn't matter. When the user opens the script file to the edit view, `line_number_gutter` is calculated and also `_update_errors()` is called again.~~

This is now fixed by not calling `_validate_script()` from `reload_text()` if `editor_enabled == false`.

### CODE REVIEW

**Review by Paulb23 — DISMISSED** [review]
Thanks for the detailed description!

Looks like the root cause is the editor lazy loading, as you pointed out. Once the tab is loaded `_validate_script` is connected / called. So we should probably not call it in the first place if the editor is not enabled, as there might be other things in an unexpected state. Would guess it's called from `reload_text`.

**Comment by akien-mga** [comment]
@miv391 Would you be able to look into @Paulb23's suggestion for fixing the issue earlier on?

I tried to reproduce #81135 myself to see if I could do it but didn't manage to trigger the problem in 4.3.dev so far.

**Comment by miv391** [comment]
I cannot reproduce the bug with v4.3.dev2.official either.

File: editor/plugins/script_text_editor.cpp [hunk 1]
```diff
@@ -662,6 +662,10 @@ void ScriptTextEditor::_update_errors() {
 		errors_panel->pop(); // Indent.
 	}
 
+	if (line_number_gutter == -1) {
```
Comment (Calinou) [inline editor/plugins/script_text_editor.cpp:665]: It might be worth adding a comment to describe why this early return is here.

**Review by Calinou — APPROVED** [review]
I can reproduce the original issue with the MRP from https://github.com/godotengine/godot/issues/81135 in 4.3.dev 7d2ca2d8a, and this PR fixes it (Linux + VS Code).

**Comment by miv391** [comment]
I tried the solution suggested by Paulb23 and it seems to work, so I changed what this fix does. Now `_validate_script` is not called at all if `editor_enabled == false`. So even less is done if the file is not yet opened in the edit view.

File: editor/plugins/script_text_editor.cpp (hunk 1 above)
Comment (miv391) [reply editor/plugins/script_text_editor.cpp]: The fix changed completely. The current fix is a bit more self explanatory.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
