### PR TITLE
Hack as a hot fix for Bullet's collision margin issue

### LINKED ISSUE #62153: [Bullet] KinematicBody (3D) move_and_collide fails to return KinematicCollision with small velocity
### Godot version

3.5.rc4.official [e047c5006]

### System information

Win10, GLES3, Bullet Physics

### Issue description

When using `move_and_collide`, it will fail to return a KinematicCollision if the collision resulted from a small velocity. This is a regression from the version of Godot I currently use, 3.4.4 stable.

I have a KinematicBody with a Cylinder CollisionShape which I will move into a StaticBody with a Cube CollisionShape.

With the following code:

```
func _physics_process(delta):
    var col = move_and_collide(Vector3.DOWN * 0.1 * delta);
    if (col):
        print("Collision");
```

you will never see "Collision" printed to the output. However, if I change that `0.1` to a `5.0`, you will see "Collision" printed.

I've created a minimal repro project to demonstrate.

### Steps to reproduce

Load the provided repro projct.
Press play
Note the cylinder touches the cube and does not produce any output. If you want, you can even breakpoint line 18 in `KinematicBody.gd` and see that the execution never pauses.
Now hop into `KinematicBody.gd` and modify the `0.1` to be `5.0`.
Play the project again and note that we now get the expected collision.

### Minimal reproduction project

[move_and_collide_problem.zip](https://github.com/godotengine/godot/files/8929474/move_and_collide_problem.zip)

### PR DESCRIPTION
**Pull request by fabriceci**
fix #62153.

We currently have an infamous issue with bullet, see the issue. We have not been able to determine the correct fix, however this causes major problems for games using Bullet.

It's ugly, I don't like it, but I don't see what else to do at the moment.

### CODE REVIEW

File: scene/3d/physics_body.cpp [hunk 1]
```diff
@@ -962,8 +962,12 @@ Ref<KinematicCollision> KinematicBody::_move(const Vector3 &p_motion, bool p_inf
 
 	bool collided = move_and_collide(p_motion, p_infinite_inertia, col, p_exclude_raycast_shapes, p_test_only);
 
+	// Ugly hack as a hot fix, 65b3200 fix an issue but cause a problem with Bullet that broke games using Bullet.
+	// The bug is something internal to Bullet, seems to be related to the Bullet’s margin. As not proper fix was found yet,
+	// this temporary solution solves the issue for games using Bullet.
+	bool is_bullet = ProjectSettings::get_singleton()->get(PhysicsServerManager::setting_property_name) != "GodotPhysics";
 	// Don't report collision when the whole motion is done.
```
Comment (lawnjelly) [inline scene/3d/physics_body.cpp:969]: ProjectSettings should not be `got` frequently, they should be cached (perhaps as a static within the physics?).

See `project_settings.h` for details on how to keep this updated in the case of changes, if this can change after startup.

Comment (akien-mga) [reply scene/3d/physics_body.cpp:969]: I don't think the physics engine can change at runtime, so caching this in a constructor should be enough.

Comment (fabriceci) [reply scene/3d/physics_body.cpp:970]: I found a cleaner solution without using the `ProjectSettings`, by caching the server ID in PhysicsServerManager (as you suggested).

**Review by akien-mga — APPROVED** [review]
It's not a pretty hack, but I guess it's needed until someone is motivated enough to do a deep dive in Bullet and see if a better solution is possible.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Comment by elvisish** [comment]
Unfortunately doesn't fix this bug: [58260](https://github.com/godotengine/godot/issues/58260)
