### PR TITLE
BaseButton: Make shortcuts call virtual methods

### LINKED ISSUE #29604: ShortCut doesn't call Button _pressed virtual function
**Godot version:** Godot 3.1.1

**OS/device including version:** Windows 10

**Issue description:**

When the ShortCut key combination is pressed, the `_pressed` function is not call but the signal `pressed` is emitted.

```
extends TextureButton

func _ready():
#	connect('pressed', self, 'toggle') # works if uncommented
	pass

func _pressed():
	toggle()

func toggle():
	OS.window_fullscreen = not OS.window_fullscreen
```

**Steps to reproduce:**
1. Extract zip and put scene in any project
2. Run the scene with F6
3. Press `Alt + Enter`

**Minimal reproduction project:**

[FullscreenButton.zip](https://github.com/godotengine/godot/files/3268607/FullscreenButton.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
When buttons are not in Toggle Mode, shortcuts used to only trigger the
`pressed` signal, without calling the `_pressed` virtual method,
contrarily to what happens when you click the button.

For Toggle Mode buttons, it did call the `_toggled` virtual method
together with emitting the `toggled` signal *twice*.

This commit harmonizes it all and makes shortcuts behave the same as
mouse clicks or `ui_accept`, for both toggle and non-toggle modes.

Fixes #29604.

----

I briefly tested the editor and the attached MRP, and it seems to work fine, but I'd be glad if others could give it a try too and confirm that the editor and their button-intensive UIs still behave as expected.

MRP: [FullscreenButton.zip](https://github.com/godotengine/godot/files/3281796/FullscreenButton.zip)
Shortcuts on <kbd>F</kbd>, <kbd>G</kbd> and <kbd>H</kbd>.

### CODE REVIEW

File: scene/gui/base_button.cpp [hunk 1]
```diff
@@ -216,9 +216,7 @@ void BaseButton::set_pressed(bool p_pressed) {
 	if (p_pressed) {
 		_unpress_group();
 	}
-	if (toggle_mode) {
-		_toggled(status.pressed);
-	}
+	_toggled(status.pressed);
```
Comment (akien-mga) [inline scene/gui/base_button.cpp]: We already have an early return for `!toggle_mode` above, so this appeared redundant.

File: scene/gui/base_button.cpp [hunk 2]
```diff
@@ -216,9 +216,7 @@ void BaseButton::set_pressed(bool p_pressed) {
 	if (p_pressed) {
 		_unpress_group();
 	}
-	if (toggle_mode) {
```
Comment (akien-mga) [inline scene/gui/base_button.cpp]: We already have an early return for `!toggle_mode` above, so this appeared redundant.

File: scene/gui/base_button.cpp [hunk 3]
```diff
@@ -337,9 +335,6 @@ bool BaseButton::is_keep_pressed_outside() const {
 
 void BaseButton::set_shortcut(const Ref<ShortCut> &p_shortcut) {
 
-	if (shortcut.is_null() == p_shortcut.is_null())
```
Comment (akien-mga) [inline scene/gui/base_button.cpp]: This test was completely bogus, as I understand it means that you could not set a new shortcut if both the existing one and the new one are valid (as `false == false` is `true`).

File: scene/gui/base_button.cpp [hunk 4]
```diff
@@ -356,11 +351,10 @@ void BaseButton::_unhandled_input(Ref<InputEvent> p_event) {
 			return; //ignore because of modal window
 
 		if (is_toggle_mode()) {
-			set_pressed(!is_pressed());
-			emit_signal("toggled", is_pressed());
```
Comment (akien-mga) [inline scene/gui/base_button.cpp]: This is already emitted by `_toggled()` which is called by `set_pressed()`.

**Review by volzhs — APPROVED** [review]
looks good for me
