### PR TITLE
Fix: Skip setting current dock when tab cannot switch [ Make EditorDocks respect panel lock ]

### LINKED ISSUE #14143: Alt-clicking a node should keep the currently active bottom dock open
### Describe the project you are working on

Various projects, in which I wish to Animate nodes such as AnimatedSprite2D.

### Describe the problem or limitation you are having in your project

When I click on a node such as AnimatedSprite2D, the Animation dock will be replaced by the dock for that node. The primary suspects are:

1. Animating AnimatedSprite2D nodes (opens sprite frames dock)
2. Animating material properties (opens shader editor dock)

The current Animation panel contains *two seperate pin buttons*, but neither of them works. 

- Pin Animation Player (top one) is meant to keep the current AnimationPlayer selected, even when selecting other AnimationPlayer nodes. 
- Pin Bottom Panel Switching (bottom one) seems to be related to not closing the panel in some cases. I can hardly tell what it's supposed to do.

Image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Alongside the existing "Pin" system, I suggest implementing the ability to ALT-click a node in the Node Tree, in order to select it in the Scene and Inspector, without changing the active dock. 

Expanding a Shader Material in the Inspector with ALT-click should also allow expanding current material (to access shader params) without changing the dock. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The signal which the dock is listening to would need to be augmented, with a flag on whether to switch the bottom panel. Or a new signal could be introduced just for switching the bottom panel, and then that could be selectivly triggered when selecting nodes without ALT-click.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can probably technically be implemented as a hacky editor plugin which listens to events and tries to prevent the dock from switchig.

### Is there a reason why this should be core and not an add-on in the asset library?

It's core UX of the engine.

### PR DESCRIPTION
**Pull request by brendevr**
When opening a dock into a DockTabContainer that returns can_switch_dock() == false, avoid marking the dock as current. Previously p_set_current was passed through to _move_dock unconditionally; now we cast the slot to DockTabContainer and force set_current to false if switching is disallowed, preventing an unwanted focus/tab switch.

Revisits #115696  with a proper solution after I rethought my approach.

*Bugsquad edit:* Closes https://github.com/godotengine/godot-proposals/issues/14143

### CODE REVIEW

File: editor/docks/editor_dock_manager.cpp [hunk 1]
```diff
@@ -608,7 +608,14 @@ void EditorDockManager::open_dock(EditorDock *p_dock, bool p_set_current) {
 		if (tab_index < 0) {
 			tab_index = slot->get_tab_count();
 		}
-		_move_dock(p_dock, slot, tab_index, p_set_current);
+		
+		bool set_current = p_set_current;
+        DockTabContainer *dock_tab_container = Object::cast_to<DockTabContainer>(slot);
```
Comment (lodetrick) [inline editor/docks/editor_dock_manager.cpp]:
```suggestion
```
`dock_slots` is an array of `DockTabContainer` so you can just change the type of slot

File: editor/docks/editor_dock_manager.cpp [hunk 2]
```diff
@@ -608,7 +608,14 @@ void EditorDockManager::open_dock(EditorDock *p_dock, bool p_set_current) {
...
+        if (dock_tab_container && !dock_tab_container->can_switch_dock()) {
+            set_current = false;
+        }
+
+        _move_dock(p_dock, slot, tab_index, set_current);
```
Comment (lodetrick) [inline editor/docks/editor_dock_manager.cpp]:
```suggestion
        _move_dock(p_dock, slot, tab_index, p_set_current && slot->can_switch_dock());
```
Optional but it is more concise

File: editor/docks/editor_dock_manager.cpp (hunk 1 above)
Comment (brendevr) [reply editor/docks/editor_dock_manager.cpp]: Thanks for pointing that out!

File: editor/docks/editor_dock_manager.cpp (hunk 2 above)
Comment (brendevr) [reply editor/docks/editor_dock_manager.cpp]: That works, didn't even think of that. Thanks.

**Review by KoBeWi — APPROVED** [review]

**Comment by SpikeTrapBoomStudios** [comment]
Squashed :+1:
