### PR TITLE
Check that ColorPickerButton popup is currently open in `_modal_closed()`

### LINKED ISSUE #111245: ColorPickerButton color is reverted when pressing escape while the popup is already closed
### Tested versions

- Reproducible in: 4.6.dev1, 4.5.stable, 4.5.beta7 and later snapshots
- Not reproducible in 4.5.beta6 and earlier snapshots

### System information

Godot v4.6.dev1 - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.8129) - AMD Ryzen 7 5700X3D 8-Core Processor (16 threads) - 15.92 GiB memory

### Issue description

When editing a color in the inspector through a ```ColorPickerButton``` and pressing escape **_after_** the color picker popup has already been closed, the color will still be reverted back to the previous color. I understand that this is intended behavior while the popup is **open**, but started happening even when it's closed after 4.5.beta7. Reopening the popup and closing it again fixes the issue until the color is changed again.

I have already identified what causes the issue and will be making a PR to address it.

### Steps to reproduce

Create a scene with a node that has a ```ColorPickerButton``` in it's inspector (e.g. a ```ColorRect```).
Open the color picker popup and change the color to something else.
Close the popup by pressing Enter or by clicking out of it while making sure the inspector stays on the current node.
Press Escape while the cursor is outside of the inspector to deselect the current node.

### Minimal reproduction project (MRP)

[color-picker-reverting-mrp.zip](https://github.com/user-attachments/files/22695777/color-picker-reverting-mrp.zip)

### PR DESCRIPTION
**Pull request by J4RH**
Fixes #111245 

This is my first time contributing here so please let me know if I've done something wrong.

Currently the `_modal_closed()` method checks if `ui_cancel` was just pressed so it can revert the color to the old one before closing. This wasn't an issue before as previously this method was only called when the popup was closed, but after #109824 it is also possible for this method to be called when the ```ColorPickerButton``` exits the scene tree, regardless of if the popup was already open; and since `ui_cancel` can deselect the current node from the inspector it is possible for `_modal_closed()` to be called on the same frame as `ui_cancel` without the popup previously being open.

I've fixed this by just adding a check to see if the popup is currently visible in the scene tree, which seems to work from my testing but there might be some edge cases where the popup is hidden before `_modal_closed()` is called, so let me know if there is a more robust solution this. This also fixes another potential issue where the `popup_closed` signal would be called on scene tree exit too, even while it was already closed. 

I have also tested the MRP from the issue that #109824 was fixing and confirmed that it still works.

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -2442,12 +2442,14 @@ void ColorPickerButton::_color_changed(const Color &p_color) {
 }
 
 void ColorPickerButton::_modal_closed() {
-	if (Input::get_singleton()->is_action_just_pressed(SNAME("ui_cancel"))) {
-		set_pick_color(picker->get_old_color());
-		emit_signal(SNAME("color_changed"), color);
+	if (picker->is_visible_in_tree()) {
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:2445]: This can be early return:

```suggestion
	if (!picker->is_visible_in_tree()) {
		return;
	}
```

Comment (J4RH) [reply scene/gui/color_picker.cpp:2445]: I considered this but didn't want to interfere with the previous fix, I'll test it now though and see. In theory it shouldn't make a difference.

Comment (J4RH) [reply scene/gui/color_picker.cpp:2445]: Unfortunately an early return **does** break the previous fix.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
