### PR TITLE
SceneTreeDock: Remove animation tracks with correct indices

### LINKED ISSUE #81602: AnimationPlayer unexpectedly deletes or adds tracks when Undo after nodes are deleted.
### Godot version

Godot v4.1.1.stable (bd6af8e0e) 

### System information

Manjaro Linux - Vulkan (Compatibility) - NVIDIA GeForce RTX 3060 (nvidia; 535.104.05) - 12th Gen Intel(R) Core(TM) i7-12700 (20 Threads)

### Issue description

AnimationPlayer unexpectedly deletes or adds tracks when nodes with animations also present in the animation clip are deleted, followed by an Undo.

https://github.com/godotengine/godot/assets/6387498/f28f363b-08dc-40c1-ae03-4a97162a7512

### Steps to reproduce

1. Add Node3d nodes.
2. Add AnimationPlayer node
3. Create move / rotate / scale keys in the animation clip.
4. Delete one of those nodes.
5. Undo the delete step.
6. You will find some tracks are duplicated and some tracks are missing in the animation clip.

### Minimal reproduction project

[AnimationPlayerBug.zip](https://github.com/godotengine/godot/files/12593861/AnimationPlayerBug.zip)

### PR DESCRIPTION
**Pull request by garychia**
Fixes #81602

The index of an animation track to be removed was not determined correctly. `HashSet` was used to find out the updated index but it does not always keep its keys in the same order after erasing a key.

### CODE REVIEW

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1774,14 +1776,7 @@ void SceneTreeDock::perform_node_renames(Node *p_base, HashMap<Node *, NodePath>
...
 
-								int idx = 0;
-								HashSet<int>::Iterator EI = ran.begin();
-								ERR_FAIL_COND(!EI); //bug
-								while (*EI != i) {
-									idx++;
-									++EI;
-									ERR_FAIL_COND(!EI); //another bug
-								}
+								const int idx = i - tracks_removed++;
```
Comment (YuriSizov) [inline editor/scene_tree_dock.cpp:1779]: Just as style suggestion: this doesn't need to be `const`, the block is pretty short, and also we prefer to make things explicit, so the increment should be moved to a separate line.

**Comment by YuriSizov** [comment]
While the trick makes sense, wouldn't it be more convenient to start from the end? That way indices are not changing under your feet.

**Review by YuriSizov — APPROVED** [review]

**Review by fire — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.
