### PR TITLE
WebsocketPeer outbound buffer fixes and buffer size query

### LINKED ISSUE #50988: WSLPeer::put_packet has an unbound outgoing buffer.  Websocket outgoing buffers unused.
### Godot version

3.X, 4.X

### System information

All

### Issue description

`WebsocketPeer`, when running through the `WSLPeer` implementation (anything non HTML5), has an unbound output message buffer.

This manifests itself under conditions where outbound traffic on the put_packet() interface under WebSocketPeer exceeds what the far-end can pull out.  

The output buffer configuration in `WSLPeer::make_context()` is unused  (and actually the `p_out_pkt_size` parameter is incorrectly being used to configure the receiving `_packet_buffer` size) .  This causes the underlying wslay `wslay_event_queue_msg()` to indefinitely queue up messages into the internal wslay message queue.  This queue is unbound.  

### Steps to reproduce

Send traffic through `WSLPeer::put_packet()` and observe the internal wslay queue length in `wslay_queue_push()`.  

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by jordo**
Fixes #50988 on master.

This PR addresses a few issue with outbound buffers in the WebsocketPeer class, and exposes an outbound buffer query for anyone working with a websocket server in godot.

Currently the wslay implementation of WebsocketPeer (anything non HTML5), will buffer an unlimited amount of outgoing messages in `wslay_event_queue_msg()`.  This is effectively an unbound outgoing queue.  

When implementing a websocket server, if an outbound websocket's tcp connection is saturated, `put_packet` will continue to buffer an unlimited amount of outgoing data within the wslay websocket library.  This PR will fail `put_packet` similar to what happens in `get_packet` if the amount of data being requested to send exceeds the current configured outbound buffer size.

Likewise this PR exposes querying the current amount of buffered outbound data in the websocketpeer buffer.  This is useful and needed when implementing a websocket server to implement throttling and congestion control per peer.  Normally congestion control would just happen via socket.send() and a stream will self-throttle, however WebsocketPeer is exposed as a `PacketPeer` interface with messages queuing up in a wslay in-memory queue.  With a working outbound buffer and the ability to introspect the amount of current buffered outgoing data, an application can make good decisions about how and when to throttle packets.  

The outbound buffer amount is implemented in HTML5 platform using the Websocket.bufferedAmount property https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/bufferedAmount and implemented using  `wslay_event_get_queued_msg_length` in the wslay implementation on other platforms.

### CODE REVIEW

File: modules/websocket/wsl_peer.cpp [hunk 1]
```diff
@@ -280,6 +284,13 @@ int WSLPeer::get_available_packet_count() const {
 	return _in_buffer.packets_left();
 }
 
+int WSLPeer::get_current_outbound_buffered_amount() const {
+	if (!_data)
+		return 0;
```
Comment (Faless) [inline modules/websocket/wsl_peer.cpp:289]:
```suggestion
	ERR_FAIL_COND_V(!_data, 0);
```

**Review by Faless — CHANGES_REQUESTED** [review]
See comments, looks good otherwise :+1: . Great job!

**Review by Faless — APPROVED** [review]
Looks great, can you please squash the 2 commits together?
See here for instructions: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by jordo** [comment]
Squashed.  Also please see https://github.com/godotengine/godot/pull/51037 for 3.X version as well

**Comment by akien-mga** [comment]
Would be nice if the commit message could be as clear as the PR title is ("WebsocketPeer outbound buffer fixes and buffer size query") for a nice Git log.

**Comment by jordo** [comment]
modified commit msg.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
