### PR TITLE
Fix for 2D viewport not updating in the editor when the camera moves

### LINKED ISSUE #40441: Viewports do not register 2D Cameras while in the editor
**Godot version:**
v3.2.1

**OS:**
Windows 10

**Issue description:**
When rendering the contents of a Viewport while in the editor, it ignores Camera2Ds. The bug does not occur when rendering 3D objects using a viewport.

**Steps to reproduce:**
1. Open reproduction project 
4. Observe editor preview of a Viewport with a 2D scene with 2D.tscn

image

5. Run 2D.tscn (the view now correctly uses the Camera2D)
image

**Minimal reproduction project:**
[ViewportTextureEditorBug.zip](https://github.com/godotengine/godot/files/4929957/ViewportTextureEditorBug.zip)

### PR DESCRIPTION
**Pull request by radenling**
This fixes a problem with 2D viewports not taking the camera position into consideration when previewed in the editor.

This is based on the fix done in PR #40677 (which was never merged) with the addition of solving the problems mentioned in that review.

This will not not work for `3.x` since `queue_redraw()` has changed name. I'll open a separate PR for the backported fix.

Fixes #40441

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -39,8 +39,10 @@ void Camera2D::_update_scroll() {
 	}
 
 	if (Engine::get_singleton()->is_editor_hint()) {
-		queue_redraw(); //will just be drawn
-		return;
+		queue_redraw();
+		// Only set viewport transform when not bound to the main viewport
+		if (get_viewport() == get_tree()->get_edited_scene_root()->get_viewport())
+			return;
```
Comment (akien-mga) [inline scene/2d/camera_2d.cpp:45]: Two style issues:
- End comment sentences with a period (it's not done consistently in existing code but should be for new code).
- Use brackets even for single line `if` blocks.

Comment (radenling) [reply scene/2d/camera_2d.cpp]: Fixed!

File: scene/2d/camera_2d.cpp [hunk 2]
```diff
@@ -39,8 +39,11 @@ void Camera2D::_update_scroll() {
 	}
 
 	if (Engine::get_singleton()->is_editor_hint()) {
-		queue_redraw(); //will just be drawn
-		return;
+		queue_redraw();
+		// Only set viewport transform when not bound to the main viewport.
+		if (get_viewport() == get_tree()->get_edited_scene_root()->get_viewport()) {
+			return;
+        }
```
Comment (akien-mga) [inline scene/2d/camera_2d.cpp:46]: Indentation issue.

Comment (radenling) [reply scene/2d/camera_2d.cpp]: Yeah, sorry. I thought I'd fixed everything and went to lunch. I've pushed a fixed version.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
