### PR TITLE
Fix `display/window/size/window_{width,height}_override` to permit `0`

### LINKED ISSUE #87906: Unable to revert `display/window/size/window_{width,height}_override` to `0`
### Tested versions

- Reproducible in 4.3.dev[1c8ae43efe]
- Not reproducible in 4.2.stable

Found the culprit: #84800

### System information

Godot v4.3.dev (1c8ae43ef) - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX Vega (RADV VEGA10) () - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

You cannot revert `display/window/size/window_{width,height}_override` to `0`.

Capture d’écran du 2024-02-03 12-15-32

The documentation explicitly says that you can set it to `0` in order to revert to default values.

image

### Steps to reproduce

1. Create a new project
2. Open the project settings
3. Enable the advanced settings
4. Change the window width override setting
5. See that you cannot put it back to `0`, as the minimum number is `1`

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #87906

# Before
image

# After
image

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -1410,8 +1410,8 @@ ProjectSettings::ProjectSettings() {
 	GLOBAL_DEF("display/window/size/extend_to_title", false);
 	GLOBAL_DEF("display/window/size/no_focus", false);
 
-	GLOBAL_DEF(PropertyInfo(Variant::INT, "display/window/size/window_width_override", PROPERTY_HINT_RANGE, "1,7680,1,or_greater"), 0); // 8K resolution
-	GLOBAL_DEF(PropertyInfo(Variant::INT, "display/window/size/window_height_override", PROPERTY_HINT_RANGE, "1,4320,1,or_greater"), 0); // 8K resolution
+	GLOBAL_DEF(PropertyInfo(Variant::INT, "display/window/size/window_width_override", PROPERTY_HINT_RANGE, "0,7680,0,or_greater"), 0); // 8K resolution
+	GLOBAL_DEF(PropertyInfo(Variant::INT, "display/window/size/window_height_override", PROPERTY_HINT_RANGE, "0,4320,0,or_greater"), 0); // 8K resolution
```
Comment (AThousandShips) [inline core/config/project_settings.cpp:1414]:
```suggestion
	GLOBAL_DEF(PropertyInfo(Variant::INT, "display/window/size/window_width_override", PROPERTY_HINT_RANGE, "0,7680,1,or_greater"), 0); // 8K resolution
	GLOBAL_DEF(PropertyInfo(Variant::INT, "display/window/size/window_height_override", PROPERTY_HINT_RANGE, "0,4320,1,or_greater"), 0); // 8K resolution
```
Step should be kept

Comment (adamscott) [reply core/config/project_settings.cpp:1414]: Or, yeah, sure! Forgot that it was the step.

**Review by AThousandShips — APPROVED** [review]
Confirmed that the code using these values all check that they are greater than zero:
https://github.com/godotengine/godot/blob/1c8ae43efefa679ed01ddefb38ccf2c1e52abb22/main/main.cpp#L2025-L2035
https://github.com/godotengine/godot/blob/1c8ae43efefa679ed01ddefb38ccf2c1e52abb22/editor/editor_run.cpp#L171-L176

**Comment by akien-mga** [comment]
Thanks!
