### PR TITLE
Incorporate min and max zoom limits into the EditorZoomWidget

### LINKED ISSUE #75886: TileSet editor's zoom values are clamped poorly
### Godot version

4.0.2

### System information

All systems

### Issue description

TileSet clamps the zoom level between 1% and 10000%. This isn't ideal because hitting the min/max zoom level means you're no longer on a multiple of 2. For instance, the canvas editor's max zoom level is 12800% and the minimum is 0.78125%

Meanwhile, the Tile Polygon editor doesn't clamp its values at all, allowing you to break it if you so desire.
image

### Steps to reproduce

Make a tileset, add icon.png as an atlas for example. Play around with the zoom level there.
Add a physics layer from the inspector, then go back to the tileset editor, select a tile, select Physics, go to the tile polygon editor, and play around with the zoom level there.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by MewPurPur**
Fixes #75886. I think it's safe to say EditorZoomWidget should have built-in zoom limits that can be set up in the different places it's used.

### CODE REVIEW

File: editor/gui/editor_zoom_widget.cpp [hunk 1]
```diff
@@ -70,12 +70,38 @@ float EditorZoomWidget::get_zoom() {
 }
 
 void EditorZoomWidget::set_zoom(float p_zoom) {
-	if (p_zoom > 0 && p_zoom != zoom) {
-		zoom = p_zoom;
+	float new_zoom = CLAMP(p_zoom, min_zoom, max_zoom)
```
Comment (AThousandShips) [inline editor/gui/editor_zoom_widget.cpp:73]:
```suggestion
	float new_zoom = CLAMP(p_zoom, min_zoom, max_zoom);
```

File: editor/gui/editor_zoom_widget.cpp [hunk 2]
```diff
@@ -70,12 +70,38 @@ float EditorZoomWidget::get_zoom() {
...
+float EditorZoomWidget::get_min_zoom() {
+	return min_zoom;
+}
+
+float EditorZoomWidget::get_max_zoom() {
+	return max_zoom;
+}
+
+void EditorZoomWidget::setup_zoom_limits(float p_min, float p_max) {
+	if (p_min < 0 || p_min > p_max) {
```
Comment (KoBeWi) [inline editor/gui/editor_zoom_widget.cpp:89]: Shouldn't this result in an error?

**Review by KoBeWi — APPROVED** [review]

File: editor/gui/editor_zoom_widget.cpp (hunk 2 above)
Comment (MewPurPur) [reply editor/gui/editor_zoom_widget.cpp]: Sure.

**Comment by akien-mga** [comment]
Thanks!
