### PR TITLE
Use a src rect for copying from screen with CanvasGroup in the mobile backend

### LINKED ISSUE #75956: Vulkan Mobile: Clip Children shows a copy of all nodes in the scene
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.2.stable

### System information

Windows 11, AMD RX 6700 XT (23.4.1), Mobile renderer

### Issue description

sprites with clip_children - 'Clip Only' enabled, have a shrunk-down mirror of the scene behind them. 

This only happens in the Mobile renderer

Godot_4_cYreMgGK0z
Godot_4_rOcYBV4uRd

### Steps to reproduce

1. Create a background, e.g. a sprite
2. Add a sprite with clip_children enabled
3. Add another sprite as a child of the one with clip_children enabled, and scale it down or turn down its transparency
4. The background sprite will appear behind it (may require moving it)

### Minimal reproduction project

[Clip Children Bug.zip](https://github.com/godotengine/godot/files/11206016/Clip.Children.Bug.zip)

### LINKED ISSUE #76104: Vulkan Mobile: CLIP_ONLY doesn't work with tilemap, shows background clear color
### Godot version

4.0.2 stable

### System information

Windows 10, Vulkan, RTX 3060 (466.81)

### Issue description

When using CLIP_ONLY setting on Clip Children and the Forward Mobile renderer, it doesn't hide the clipping object, it renders the background color instead.

### Steps to reproduce

- Add a sprite object to clip with.
- Add a child sprite to be clipped.
- Set the renderer to Mobile.
- Watch the clip object be rendered as the background/the tileset hall-of-mirrorsing.

### Minimal reproduction project

[cliptest.zip](https://github.com/godotengine/godot/files/11240698/cliptest.zip)

### LINKED ISSUE #85063: 2D clip function behaves wrong effect on the mobile rendering backends.
### Godot version

4.2 rc1

### System information

Windows 11

### Issue description

Only the TextureRect node sets to Clip Only state. The sprite2d node will appear into the TextureRect box.
It will be ok when using the Forward+ and  GL Compatibility backends.

### Steps to reproduce

See the mini demo.

### Minimal reproduction project

[TestDemo.zip](https://github.com/godotengine/godot/files/13400783/TestDemo.zip)

### LINKED ISSUE #89689: ColorRect with clipping enabled and panel as child renders the screen texture onto it
### Tested versions

- Reproducible v4.3.dev5.official [89f70e98d]

### System information

Windows 11

### Issue description

When setting a color rect to clip mode, and adding a panel to it as a child, it will render the whole game screen texture onto it.

image

### Steps to reproduce

Create a 2D scene, add some sprites and stuff to it. Add a ColorRect and set the clip to clip only. Add a panel to it as a child. It will render the screen with sprites added to the scene.

### Minimal reproduction project (MRP)

[weird_viewport.zip](https://github.com/godotengine/godot/files/14657231/weird_viewport.zip)

### LINKED ISSUE #90793: Polygon2D clipping generates spurious elements inside masked area
### Tested versions

Reproducible in: 4.3-dev5, 4.2.1-stable, 4.1.3-stable

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5152) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5152) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

I am trying to use Polygon2D clipping to mask out an area of the screen. See picture.

When I make a test scene, the clipping polygon (selected) correctly masks the Godot icon. But there are undesired scaled copies of other elements in the scene inside the clip area (green and grey polygons). As you pan the background of the editor around these copies shift around like there is some transform effect.

PolygonClippingMaskBugAnnotated_17Apr2024

### Steps to reproduce

1. In a 2D scene, create a white Polygon2D with points in a rough circle, called PolygonA.

2. Drag the Godot sprite Icon.svg into the viewport so that it overlaps an edge of PolygonA.

3. Make the icon sprite a child of PolygonA and set PolygonA's Clip Children to Clip Only.

4. This correctly masks the sprite so that it is only visible inside the mask area.

5. Now add a new Polygon2D, called PolygonB, to the scene, move it above PolygonA in the hierarchy. Set it to green and add some points in a rectangle that will encompass PolygonA.

6. You will now see the bug. There is an undesired scaled copy of PolygonB inside the clip area of PolygonA. It also shows any other scene elements inside this clip area, if they are above PolygonA in hierarchy.

7. If you use MMB to pan the editor background, the scene copies move around.

### Minimal reproduction project (MRP)

[PolygonClippingMaskBug.zip](https://github.com/godotengine/godot/files/15010766/PolygonClippingMaskBug.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/75956, fixes https://github.com/godotengine/godot/issues/76104, fixes https://github.com/godotengine/godot/issues/85063, fixes https://github.com/godotengine/godot/issues/89689, fixes https://github.com/godotengine/godot/issues/90793

To fix this I had to extend `copy_to_fb_rect` to allow for reading from a section of a texture instead of always copying the entire texture. 

_before_
Screenshot from 2024-04-17 15-21-20
_after_
Screenshot from 2024-04-17 15-20-15

### CODE REVIEW

**Comment by kleonc** [comment]
> Fixes: #75956

What about #76104, #85063, #89689, #90793 (are they duplicates of #75956)?

File: servers/rendering/renderer_rd/storage_rd/texture_storage.cpp [hunk 1]
```diff
@@ -3820,7 +3820,10 @@ void TextureStorage::render_target_copy_to_back_buffer(RID p_render_target, cons
 	if (RendererSceneRenderRD::get_singleton()->_render_buffers_can_be_storage()) {
 		copy_effects->copy_to_rect(rt->color, rt->backbuffer_mipmap0, region, false, false, false, !rt->use_hdr, true);
 	} else {
-		copy_effects->copy_to_fb_rect(rt->color, rt->backbuffer_fb, region, false, false, false, false, RID(), false, true);
+		Rect2 src_rect = Rect2(region);
+		src_rect.position /= Size2(rt->size);
+		src_rect.size /= Size2(rt->size);
```
Comment (lawnjelly) [inline servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:3825]: Can render target ever be zero size? Or is that prevented elsewhere?

**Comment by clayjohn** [comment]
> > Fixes: #75956
> 
> What about #76104, #85063, #89689, #90793 (are they duplicates of #75956)?

Woah, great work finding all those. Indeed they all have the same root cause as #75956 and are all fixed by this PR :)

File: servers/rendering/renderer_rd/storage_rd/texture_storage.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:3825]: Render target can have a zero size, but this code can't be reached by a zero size viewport as zero size viewports are culled before rendering

**Review by lawnjelly — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by NafunaAfrica** [comment]
I dont get the fix? I am experiencing the same issue but not sure what copy_to_fb_rect  is

**Comment by clayjohn** [comment]
> I dont get the fix? I am experiencing the same issue but not sure what copy_to_fb_rect is

What version of Godot are you using?

**Comment by Nicholas3413** [comment]
Please fix this for Godot 4.1.5 next. I had to manually change the code and rebuild custom editor&export template to be able to fix the masking. Cherry pick may cause issue. the Godot 4.1.4 doesnt have the p_normal parameter
here's my change to fix it on 4.1.4:
image
image
image
image

**Comment by akien-mga** [comment]
@Nicholas3413 Any reason you need to stay on 4.1 instead of upgrading to 4.3?

We can't maintain all branches forever, and now with both 4.2 and 4.3 to support, the 4.1 branch will soon be EOL. The only changes suitable to include for 4.1.5 if we ever release it are critical bug fixes for platform compatibility.

**Comment by Nicholas3413** [comment]
@akien-mga, Sorry for late reply,  it was because there was a shader visual bug that's not fixed on 4.2 and 4.3 on certain PC driver that's not yet updated, but Godot 4.1.4 doesn't have that issue, only when upgraded to 4.2 and 4.3 we had that issue. so we are forced to stay at 4.1.4. Now i can't test it if the bug still exists on 4.3, because the driver for the device that has bugged shader visual was updated/changed. The Shader Visual Bug is a big deal, because it's part of the game UI and we used it on several area including main area. 

I see, but isn't this kind of critical bug? Mobile Renderer build can't have a proper masking.
for now yes, we are using the custom build both export templates (MacOS, Android, iOS) and editor (windows 64).
