### PR TITLE
Fix memory leak in GDScript during infinnity loops with yields

### LINKED ISSUE #19823: Memory leak when yielding (regression from #17291)
**Godot version:**

Godot 3.0.4

**OS/device including version:**

macOS Mojave 10.14 Beta (18A314h)

**Issue description:**

simple yielding produces huge memory leaks

This code 
```gd
extends Node

func _ready():
	while true:
		yield(get_tree(), "idle_frame")
		yield(get_tree(), "idle_frame")
		yield(get_tree(), "idle_frame")
		print("yield 3 idle frames ", Performance.get_monitor(Performance.OBJECT_COUNT))
```
produces dat output:
```
** Debug Process Started **
Remote Debugger: Connection failed with status: '2', retrying in 1 msec.
OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Plus Graphics 640
yield 3 idle frames 702
yield 3 idle frames 705
yield 3 idle frames 708
yield 3 idle frames 711
yield 3 idle frames 714
yield 3 idle frames 717
...
```
Memory/Static && Object/Objects are constantly increasing in Debug/Monitors view.
Godot 3.0.2 didn't leak with same code.

### PR DESCRIPTION
**Pull request by jkb0o**
Fixes #19823 introduced in #17291

The code below passes assertions
```gd
extends Node

var iterations = 5;

func _ready():
	print("start single_yield()")
	assert(yield(single_yield(), "completed") == 1)
	print("done single_yield()")
	print("start three_yields()")
	assert(yield(three_yields(), "completed") == 3)
	print("done three_yields()")
	var num_objects = Performance.get_monitor(Performance.OBJECT_COUNT) - 2
	while iterations:
		yield(get_tree(), "idle_frame")
		yield(get_tree(), "idle_frame")
		yield(get_tree(), "idle_frame")
		var current_objects = Performance.get_monitor(Performance.OBJECT_COUNT)
		print("yield 3 idle frames, current objects == ", current_objects, ", awaits ", num_objects, " objects")
		assert(num_objects == current_objects)
		iterations -= 1
	
func single_yield():
	var i = 0
	print("  single_yield: -> yield1")
	yield(get_tree(), "idle_frame")
	print("  single_yield: -> yield1 ->")
	i += 1
	return i
	
func three_yields():
	var i = 0
	print(" three_yields: -> yield1")
	yield(get_tree(), "idle_frame")
	
	print(" three_yields: -> yield1 -> yield2")
	i += 1

	yield(get_tree(), "idle_frame")
	
	print(" three_yields: -> yield1 -> yield2 -> yield3")	
	i += 1

	yield(get_tree(), "idle_frame")
	
	i += 1
	print(" three_yields: -> yield1 -> yield2 -> yield3 ->")	
	return i
```
and produce output
```
start single_yield()
  single_yield: -> yield1
  single_yield: -> yield1 ->
done single_yield()
start three_yields()
 three_yields: -> yield1
 three_yields: -> yield1 -> yield2
 three_yields: -> yield1 -> yield2 -> yield3
 three_yields: -> yield1 -> yield2 -> yield3 ->
done three_yields()
yield 3 idle frames, current objects == 837, awaits 837 objects
yield 3 idle frames, current objects == 837, awaits 837 objects
yield 3 idle frames, current objects == 837, awaits 837 objects
yield 3 idle frames, current objects == 837, awaits 837 objects
yield 3 idle frames, current objects == 837, awaits 837 objects
```

Also I'm attaching example project witch fails with 3.0.3+ and passes with current pr.
[godot_yield_leak.zip](https://github.com/godotengine/godot/files/2145986/godot_yield_leak.zip)

CC @Warlaan

### CODE REVIEW

File: modules/gdscript/gdscript_function.cpp [hunk 1]
```diff
@@ -1552,19 +1552,16 @@ Variant GDScriptFunctionState::_signal_callback(const Variant **p_args, int p_ar
...
 	function = NULL; //cleaned up;
 	state.result = Variant();
 
 	if (completed) {
-		GDScriptFunctionState *state = this;
-		while (state != NULL) {
-			state->emit_signal("completed", ret);
-			state = *(state->previous_state);
-		}
+		if (first_state.is_valid()) first_state->emit_signal("completed", ret);
```
Comment (akien-mga) [inline modules/gdscript/gdscript_function.cpp]: Please don't put condition and code block inline for `if`s, it makes it hard to read what is the condition and what is the statement that will be executed. We tolerate it for simple `if (cond) return false;`, but even then I'd advise not to use it.

Comment (jjay) [reply modules/gdscript/gdscript_function.cpp]: fixed

**Comment by puppetmaster-** [comment]
this script should be included in the Godot test project 😄

**Comment by jjay** [comment]
It actually is. But it is also here for those lazy and trustful persons like me (=

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
