### PR TITLE
Always treat exponent as float

### LINKED ISSUE #23939: Godot seems to no longer like 1eN notation.
**Godot version:**
Godot 3.1 todays  master

**OS/device including version:**
Any

**Issue description:**
Looking at this report:
https://github.com/BastiaanOlij/godot-sky-asset/issues/4

I tracked this down to a line of code in the shader:
```
if (d < 0.0) return vec2(1e5,-1e5);
```
It gave an invalid numeric value error on the 1e5 notation. I'm guessing because this is an integer value while the input is a float but this worked fine in earlier versions. 

Ended up changing it to:
```
if (d < 0.0) return vec2(100000.0,-100000.0);
```
To work around the limitation

**Steps to reproduce:**
Use an e number notation in your shader :)

**Minimal reproduction project:**
Try using:
https://github.com/BastiaanOlij/godot-sky-asset/commit/fe5238610d8c403acb6ebb48c467f5068f66a77a

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This fixes #23939 

Don't know when this changed or why but the parser was treating 1e5 (10000.0) as an integer while 1e-5 (0.00001) as a float. While on face value that should be fine two things cause a problem with this:
1) it leads to a call to is_valid_integer which will return false because it doesn't see 1e5 as an integer
2) GLSL treats exponential notation as floating point anyway as far as I understand.

This fix simply ensures the parser treats any exponential notation as floating point and it works perfectly.

### CODE REVIEW

File: servers/visual/shader_language.cpp [hunk 1]
```diff
@@ -614,7 +614,7 @@ ShaderLanguage::Token ShaderLanguage::_get_token() {
 
 					char_idx += str.length();
 					Token tk;
-					if (period_found || minus_exponent_found || float_suffix_found)
+					if (period_found || exponent_found || float_suffix_found)
```
Comment (akien-mga) [inline servers/visual/shader_language.cpp]:
```
servers/visual/shader_language.cpp: In member function 'ShaderLanguage::Token ShaderLanguage::_get_token()':
servers/visual/shader_language.cpp:528:11: error: variable 'minus_exponent_found' set but not used [-Werror=unused-but-set-variable]
      bool minus_exponent_found = false;
           ^
```
:)

File: servers/visual/shader_language.cpp [hunk 2]
```diff
@@ -571,7 +571,7 @@ ShaderLanguage::Token ShaderLanguage::_get_token() {
 					if (hexa_found) {
 						//hex integers eg."0xFF" or "0x12AB", etc - NOT supported yet
 						return _make_token(TK_ERROR, "Invalid (hexadecimal) numeric constant - Not supported");
-					} else if (period_found || float_suffix_found) {
+					} else if (exponent_found || period_found || float_suffix_found) {
```
Comment (akien-mga) [inline servers/visual/shader_language.cpp]: Just a matter of style, but maybe move it to the second place to match line 617?

File: servers/visual/shader_language.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply servers/visual/shader_language.cpp]: @akien-mga I think we need to find out who introduced the minus_exponent_found logic, obviously someone on purpose made positive exponents be treated as integers but didn't test it through. My best guess is that this is a change in one of the other parsers where it makes sense and simply duplicated for the GLSL shader parser.

I'm happy to remove the minus_exponent_found logic but I left it there more or less in case someone came back with a reason why it was added in the first place.

File: servers/visual/shader_language.cpp (hunk 2 above)
Comment (BastiaanOlij) [reply servers/visual/shader_language.cpp]: yeah makes sense, I'll change that once we make a decision on the other issue.

File: servers/visual/shader_language.cpp (hunk 1 above)
Comment (akien-mga) [reply servers/visual/shader_language.cpp]: It was added by @reduz in 22d83bc9f6.

Comment (BastiaanOlij) [reply servers/visual/shader_language.cpp]: Well hopefully @reduz will shed some light on it then before this gets fixed the wrong way around.

Comment (BastiaanOlij) [reply servers/visual/shader_language.cpp]: From https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)

> Literals
> 
> A literal is a value written into the shader. Literals are always basic types, and they can be used to initialize the value of a basic type. They can also be used wherever a constant basic value is needed.
> 
> Literals are typed. There are two literals of bool type: true and false.
> 
> Any integer value is by default of type int (a signed integer). To create an integer literal of unsigned type, use the suffix u or U.
> 
> Integer literals can be defined in base 8 or base 16 using the standard C/C++ conventions (prefix with 0 for base 8 or 0x for base 16).
> 
> A numeric literal that uses a decimal is by default of type float. To create a float literal from an integer value, use the suffix f or F as in C/C++.
> 
> **Floats can also be defined using exponential notation, using the e or E to separate the base from the exponent. The exponent is always base-10.**
> 
> In GLSL 4.00 and above, double-precision floats are available. By default, all floating-point literals are of type float. To create a double-precision float, use the lf or LF suffixes. This will force it to the double type.

Especially that 2nd to last paragraph specifically mentioning floats can use exponential notation. So my guess is that checking for the negative value isn't needed. If we've detected its exponential than it's float.

**Comment by akien-mga** [comment]
@reduz says the change looks ok, just needs a rebase to remove the unused var.

**Comment by akien-mga** [comment]
I force-pushed an amend doing the required changes.

**Comment by akien-mga** [comment]
Thanks!
