### PR TITLE
Fix some GDScript bugs

### LINKED ISSUE #45003: Crash when opening project in GDScriptAnalyzer::resolve_datatype, following: "Parser bug (please report): Trying to check compatibility of unset value type"
**Godot version:**

8ba67b7

**Issue description:**

So I was messing with my project and 4.0 and trying to make things work until eventually after some script changes I can no longer open the project. I get this crash on startup:
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] CowData<GDScriptParser::IdentifierNode *>::size (C:\godot_source\core\templates\cowdata.h:131)
[1] CowData<GDScriptParser::IdentifierNode *>::get (C:\godot_source\core\templates\cowdata.h:153)
[2] Vector<GDScriptParser::IdentifierNode *>::operator[] (C:\godot_source\core\templates\vector.h:89)
[3] GDScriptAnalyzer::resolve_datatype (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:387)
[4] GDScriptAnalyzer::resolve_parameter (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:1339)
[5] GDScriptAnalyzer::resolve_function_signature (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:893)
[6] GDScriptAnalyzer::resolve_class_interface (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:699)
[7] GDScriptAnalyzer::resolve_interface (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:3405)
[8] GDScriptParserRef::raise_status (C:\godot_source\modules\gdscript\gdscript_cache.cpp:71)
[9] GDScriptAnalyzer::resolve_datatype (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:425)
[10] GDScriptAnalyzer::resolve_class_interface (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:548)
[11] GDScriptAnalyzer::resolve_program (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:3415)
[12] GDScriptAnalyzer::analyze (C:\godot_source\modules\gdscript\gdscript_analyzer.cpp:3435)
[13] GDScript::reload (C:\godot_source\modules\gdscript\gdscript.cpp:820)
[14] GDScriptCache::get_full_script (C:\godot_source\modules\gdscript\gdscript_cache.cpp:211)
[15] ResourceFormatLoaderGDScript::load (C:\godot_source\modules\gdscript\gdscript.cpp:2336)
[16] ResourceLoader::_load (C:\godot_source\core\io\resource_loader.cpp:190)
[17] ResourceLoader::_thread_load_function (C:\godot_source\core\io\resource_loader.cpp:217)
[18] ResourceLoader::load (C:\godot_source\core\io\resource_loader.cpp:581)
[19] EditorAutoloadSettings::_create_autoload (C:\godot_source\editor\editor_autoload_settings.cpp:347)
[20] EditorAutoloadSettings::EditorAutoloadSettings (C:\godot_source\editor\editor_autoload_settings.cpp:805)
[21] ProjectSettingsEditor::ProjectSettingsEditor (C:\godot_source\editor\project_settings_editor.cpp:457)
[22] EditorNode::EditorNode (C:\godot_source\editor\editor_node.cpp:6077)
[23] Main::start (C:\godot_source\main\main.cpp:2139)
[24] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:161)
[25] _main (C:\godot_source\platform\windows\godot_windows.cpp:185)
[26] main (C:\godot_source\platform\windows\godot_windows.cpp:199)
[27] __scrt_common_main_seh (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[28] BaseThreadInitThunk
-- END OF BACKTRACE --
```
I can't really share the project, hope the backtrace is enough >_>

### PR DESCRIPTION
**Pull request by RandomShaper**
Probaly only the last commit is needed to fix the crash in #45003. By the way, that last commit partially reverts a change done in 3abb3c0d6e9e81d3ed171162cc5ce2bbe58296e0, maybe unrelated to its main purpose, but it's good to bear it in mind in case the issue solved there resurrects.

However, I found other errors triggered by the test project and fixed them as well.

Fixes #45003.

There's the possibility that this PR fixes other errors. I haven't tested against other bug reports.

**UPDATE:** Removed one commit which already exists in #51653.

### CODE REVIEW

**Comment by qarmin** [comment]
This broke project in CI(even if CI not failing) - 
```

SCRIPT ERROR: Parse Error: Invalid operands "String" and "Array" for "+" operator.
          at: GDScript::reload (res://AutomaticBugs/FunctionExecutor.gd:41)
SCRIPT ERROR: Parse Error: Invalid argument for "get_instance_from_name()" function: argument 1 should be String but is Array.
          at: GDScript::reload (res://AutomaticBugs/FunctionExecutor.gd:43)
SCRIPT ERROR: Parse Error: Invalid argument for "class_get_method_list()" function: argument 1 should be StringName but is Array.
          at: GDScript::reload (res://AutomaticBugs/FunctionExecutor.gd:48)
SCRIPT ERROR: Parse Error: Invalid argument for "check_if_is_allowed()" function: argument 1 should be Dictionary but is Array.
          at: GDScript::reload (res://AutomaticBugs/FunctionExecutor.gd:55)
SCRIPT ERROR: Parse Error: Invalid argument for "parse_and_return_objects()" function: argument 1 should be Dictionary but is Array.
          at: GDScript::reload (res://AutomaticBugs/FunctionExecutor.gd:58)
SCRIPT ERROR: Parse Error: Invalid argument for "parse_and_return_objects()" function: argument 2 should be String but is Array.
          at: GDScript::reload (res://AutomaticBugs/FunctionExecutor.gd:58)
```

**Comment by RandomShaper** [comment]
Fixed. I was not handling the case of builtin typed arrays and also I was overhandling the case of any builtin type.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1089,12 +1089,28 @@ void GDScriptAnalyzer::resolve_for(GDScriptParser::ForNode *p_for) {
 		}
 	}
 
-	if (!list_resolved) {
+	GDScriptParser::DataType variable_type;
+	if (list_resolved) {
+		variable_type.type_source = GDScriptParser::DataType::ANNOTATED_INFERRED;
+		variable_type.kind = GDScriptParser::DataType::BUILTIN;
+		variable_type.builtin_type = Variant::INT; // Can this ever be a float or something else?
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1096]: I guess it only reaches this is `range()` is used which in practice can only be an array of ´int´s. Maybe we can can change `range()` to return a PackedInt64Array instead and then just get the type from there to avoid mismatches. This can be done in a later change though.

File: modules/gdscript/gdscript_parser.h [hunk 2]
```diff
@@ -50,6 +50,31 @@
...
 #endif // DEBUG_ENABLED
 
+static Variant::Type _variant_type_to_typed_array_element_type(Variant::Type p_type) {
+	switch (p_type) {
+		case Variant::PACKED_BYTE_ARRAY:
+			[[fallthrough]];
+		case Variant::PACKED_INT32_ARRAY:
+			[[fallthrough]];
+		case Variant::PACKED_INT64_ARRAY:
+			return Variant::INT;
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.h:60]: You don't really need `[[fallthrough]]` here since there are no other statements. It's easier to read if the cases are packed together.`

```suggestion
	switch (p_type) {
		case Variant::PACKED_BYTE_ARRAY:
		case Variant::PACKED_INT32_ARRAY:
		case Variant::PACKED_INT64_ARRAY:
			return Variant::INT;
```

File: modules/gdscript/gdscript_parser.h [hunk 3]
```diff
@@ -50,6 +50,31 @@
 #include "gdscript_warning.h"
 #endif // DEBUG_ENABLED
 
+static Variant::Type _variant_type_to_typed_array_element_type(Variant::Type p_type) {
```
Comment (vnen) [inline modules/gdscript/gdscript_parser.h:53]: I'm not really fond of adding this function to the header. This should be added to the `.cpp` instead and the methods that depend on it can be defined in the `.cpp` too since they're not being inlined anyway.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 4]
```diff
@@ -1398,8 +1398,7 @@ void GDScriptAnalyzer::resolve_parameter(GDScriptParser::ParameterNode *p_parame
 	}
 
 	if (p_parameter->datatype_specifier != nullptr) {
-		resolve_datatype(p_parameter->datatype_specifier);
-		result = p_parameter->datatype_specifier->get_datatype();
+		result = resolve_datatype(p_parameter->datatype_specifier);
```
Comment (vnen) [inline modules/gdscript/gdscript_analyzer.cpp:1401]: Technically this should be the same thing, but there seems to be some branches that don't set the datatype in the specifier (which is sort of a bug). I guess this format is clearer anyway.

**Review by vnen — CHANGES_REQUESTED** [review]
I have a few nitpicks but otherwise looks good.

File: modules/gdscript/gdscript_parser.h (hunk 2 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript_parser.h:60]: I agree with yout point, but some of the CI build checks would fail otherwise.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript_analyzer.cpp:1096]: I'll take your offer to leave it as it is now if you think it's already any good and let you (or me in a future) enhance it.

File: modules/gdscript/gdscript_parser.h (hunk 3 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript_parser.h]: Fixed.

File: modules/gdscript/gdscript_parser.h (hunk 2 above)
Comment (vnen) [reply modules/gdscript/gdscript_parser.h]: I don't see why the CI would fail, we have already many instances of this in the code.

**Comment by vnen** [comment]
Looks good, apart from the `[[fallthrough]]` excess (which shouldn't fail the build given we have other instances like I commented).

And there's a style issue in the CI.

File: modules/gdscript/gdscript_parser.h (hunk 2 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript_parser.h]: I don't remember how I managed to come to believe that those were needed... In any case, I've removed them and all seems fine!

**Review by vnen — APPROVED** [review]

**Comment by vnen** [comment]
Thanks!
