### PR TITLE
Fix filtering editor nodes in Create Dialog

### LINKED ISSUE #72033: Editor nodes not filtered on the 'Create CanvasItem' window
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows10, Forward+, AMD Ryzen 5 5600H with Radeon Graphics

### Issue description

Users can only add Control and Node2D nodes on the Create CanvasItem window, but there are Editor nodes not filtered out. 

### Steps to reproduce

Right-clicking on the 2D viewport. Select the add node feature. A Create CanvasItem window shows. Users can only add Control and Node2D nodes, but there are Editor nodes not filtered out.
图片

### Minimal reproduction project

No project is needed.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #72033

The create dialog opened from 2D editor uses CanvasItem as base type, which wasn't caught by the old condition.

### CODE REVIEW

File: editor/create_dialog.cpp [hunk 1]
```diff
@@ -508,6 +508,11 @@ String CreateDialog::get_selected_type() {
 	return selected->get_text(0);
 }
 
+void CreateDialog::set_base_type(const String &p_base) {
+	base_type = p_base;
+	is_base_type_node = ClassDB::is_parent_class(p_base, "Node");
```
Comment (KoBeWi) [inline editor/create_dialog.cpp:513]: Cached for performance. No reason to check it each time.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
