### PR TITLE
Fix mesh instance not updated when changing blend shape values

### LINKED ISSUE #91871: Shadows don't update when changing blend shape values
### Tested versions

Reproducible in 2ba22d1554ded08094e3869a83bd87487266ad38 (custom build from 2 days ago)

### System information

Windows 10.0.19044 - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

If you change a MeshInstance's blend shapes using code `set_blend_shape_value` in e.g. `_process`, then shadows of an OmniLight3D will not update until you also move the mesh (e.g. by nudging the `position` value slightly).

This happens in Compatibility, Mobile and Forward+ renderers.

### Steps to reproduce

See above.

### Minimal reproduction project (MRP)

[blend-shapes-dont-update-shadows.zip](https://github.com/godotengine/godot/files/15285844/blend-shapes-dont-update-shadows.zip)

The cube is animated via blend shapes only. Uncommenting the last line in the cube's script will fix shadows not updating. Change renderer to any other and observe the same problem.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/91871

### CODE REVIEW

File: servers/rendering/renderer_scene_cull.cpp [hunk 1]
```diff
@@ -958,6 +958,8 @@ void RendererSceneCull::instance_set_blend_shape_weight(RID p_instance, int p_sh
 	if (instance->mesh_instance.is_valid()) {
 		RSG::mesh_storage->mesh_instance_set_blend_shape_weight(instance->mesh_instance, p_shape, p_weight);
 	}
+
+	_instance_queue_update(instance, true, true);
```
Comment (clayjohn) [inline servers/rendering/renderer_scene_cull.cpp:962]: I don't think we need to update the AABB or dependencies, do we? Setting these to true is kind of expensive. So they should be false unless needed

Comment (jsjtxietian) [reply servers/rendering/renderer_scene_cull.cpp:962]: Tested locally, we don't need to update the  AABB or dependencies, but I wonder if we should update the AABB anyway, since it can results to better culling? The shape can change a lot depends on weight.

Comment (clayjohn) [reply servers/rendering/renderer_scene_cull.cpp:962]: I don't think the AABB calculation takes the blend shape weights into account. It uses the bone AABBs and the skeleton position though.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
