### PR TITLE
Fix script editor wrongly replaces and quotes non-ASCII letters

### LINKED ISSUE #92899: Script editor wrongly replaces and quotes non-ASCII letters
### Tested versions

4.3 beta1 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/735a81e3-5bf7-419e-991e-32af57003fbd

The non-ASCII letters are replaced with `_`, while they make a valid identifier. Also the path is quoted, but it works without the quote.

### Steps to reproduce

1. Have a node with some accented letters in name, like `bułka`
2. Drag and drop it to script editor while holding Ctrl
3. The line ends up as `@onready var bu_ka = $"bułka"`
4. Change it to `@onready var bułka = $bułka`
5. It still works, so the identifier processing was unnecessary

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #92899

- Variable names generated when Ctrl-drop files into the script editor
- Variable names and `$`/`%` paths generated when Ctrl-drop nodes into the script editor
- Class names generated when using a script template

After this PR, `String::validate_ascii_identifier()` is not used anymore in the codebase except for some related tests. We could remove this method completed after some time if it is still not used.

### CODE REVIEW

File: core/string/ustring.cpp [hunk 1]
```diff
@@ -4647,6 +4647,29 @@ String String::validate_ascii_identifier() const {
 	return result;
 }
 
+String String::validate_unicode_identifier() const {
+	if (is_empty()) {
+		return "_"; // Empty string is not a valid identifier;
```
Comment (AThousandShips) [inline core/string/ustring.cpp:4652]:
```suggestion
		return "_"; // Empty string is not a valid identifier.
```

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by wayrboy** [comment]
Good Job!
