### PR TITLE
Fix Heap buffer overflow in Animation::_find()

### LINKED ISSUE #106647: Heap buffer overflow in Animation::_find()
### Tested versions

- Reproducible in 4.4.1-stable

### System information

Godot v4.4.1.stable (49a5bc7b6) - Windows 11 (build 22631) - Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 31.0.101.2115) - Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 threads)

### Issue description

While debugging process lockups during threaded loading I ran into this asan behavior

Image

>	godot.windows.template_release.x86_64.san.exe!Animation::_find<Animation::MethodKey>(const Vector<Animation::MethodKey> & p_keys, double p_time, bool p_backward, bool p_limit) Line 2443	C++
 	godot.windows.template_release.x86_64.san.exe!Animation::track_find_key(int p_track, double p_time, Animation::FindMode p_find_mode, bool p_limit, bool p_backward) Line 1671	C++
 	godot.windows.template_release.x86_64.san.exe!AnimationMixer::_blend_process(double p_delta, bool p_update_only) Line 1655	C++
 	godot.windows.template_release.x86_64.san.exe!AnimationMixer::_process_animation(double p_delta, bool p_update_only) Line 990	C++
 	godot.windows.template_release.x86_64.san.exe!AnimationMixer::_notificationv(int p_notification, bool p_reversed) Line 44	C++
 	godot.windows.template_release.x86_64.san.exe!AnimationTree::_notificationv(int p_notification, bool p_reversed) Line 269	C++
 	godot.windows.template_release.x86_64.san.exe!Object::notification(int p_notification, bool p_reversed) Line 914	C++
 	godot.windows.template_release.x86_64.san.exe!SceneTree::_process_group(SceneTree::ProcessGroup * p_group, bool p_physics) Line 1064	C++
 	godot.windows.template_release.x86_64.san.exe!SceneTree::_process(bool p_physics) Line 1137	C++
 	godot.windows.template_release.x86_64.san.exe!SceneTree::process(double p_time) Line 585	C++
 	godot.windows.template_release.x86_64.san.exe!Main::iteration() Line 4529	C++
 	godot.windows.template_release.x86_64.san.exe!OS_Windows::run() Line 2075	C++
 	godot.windows.template_release.x86_64.san.exe!widechar_main(int argc, wchar_t * * argv) Line 97	C++
 	[Inline Frame] godot.windows.template_release.x86_64.san.exe!_main() Line 122	C++
 	godot.windows.template_release.x86_64.san.exe!main(int argc, char * * argv) Line 141	C++

### Steps to reproduce
Set up the vsproject with `scons vsproj=yes dev_build=yes use_asan=yes target=template_release` and set the debugger Working Directory to the MRP

or build with `scons dev_build=yes use_asan=yes target=template_release` and run the MRP

### Minimal reproduction project (MRP)

[animation-heap-overflow-repro.zip](https://github.com/user-attachments/files/20357580/animation-heap-overflow-repro.zip)

### PR DESCRIPTION
**Pull request by jamie-pate**
Fixes #106647

`middle` can be set to -1 and then used as an index in `keys`, which causes a heap buffer underflow.

### CODE REVIEW

File: scene/resources/animation.cpp [hunk 1]
```diff
@@ -2441,7 +2441,7 @@ int Animation::_find(const Vector<K> &p_keys, double p_time, bool p_backward, bo
 		}
 	}
 
-	if (p_limit) {
+	if (p_limit && middle > -1) {
```
Comment (clayjohn) [inline scene/resources/animation.cpp:2444]: Do we still want the error if middle is -1?

Comment (jamie-pate) [reply scene/resources/animation.cpp:2444]: The error says 'found the key' but if middle is -1 then we didn't find the key (binary search has gone off the left side of the array)

Comment (a-johnston) [reply scene/resources/animation.cpp:2444]: The error is specifically for if a valid key is found but it's outside the animation's range; from the usage of this method both `-1` and `len` are valid return values. With that in mind this check should cover both bounds - `p_limit && middle > -1 && middle < len`.

Comment (clayjohn) [reply scene/resources/animation.cpp:2444]: Thanks for the answers!

That makes sense. And also makes sense why we would want to also check that `middle < len`

Comment (jamie-pate) [reply scene/resources/animation.cpp]: updated

**Review by TokageItLab — APPROVED** [review]
LGTM, this was my fault. Thanks for the follow up!

**Comment by Repiteo** [comment]
Thanks!
