### PR TITLE
Fix `switch_on_hover` for `MenuButton`

### LINKED ISSUE #99842: MenuButton's switch_on_hover property ignores its own popup menu.
### Tested versions

- Reproducible in 4.4, 4.3 and 4.2 .

### System information

Windows 10 64bits, Godot 4.4 mainly

### Issue description

When enabling the "Switch on hover" property for a Menu Button, a button requested to change will ignore if its own popup menu is in between the cursor and the other Menu Button. This results in undesirable behavior on a vertical layout.

Image

### Steps to reproduce

1. Open the default scene.
2. Click on menu A.
3. With its popup menu deployed, move the cursor where menu B would be.

Please note that switch on hover is enabled on both.

### Minimal reproduction project (MRP)

[bug_menu.zip](https://github.com/user-attachments/files/17962480/bug_menu.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
Previously, embedded Windows (the opened menu) were not accounted for when checking for `switch_on_hover`.

 `gui_get_hovered_control()` is more appropriate to check for the hover status of other `MenuButton` nodes at the mouse position.

Explain the usage of the incorrectly used function in a comment.

- resolve #99842

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -1632,7 +1632,9 @@ void Viewport::_gui_call_notification(Control *p_control, int p_what) {
 
 Control *Viewport::gui_find_control(const Point2 &p_global) {
 	ERR_MAIN_THREAD_GUARD_V(nullptr);
-	// Handle subwindows.
+	// `gui_find_control` doesn't take embedded windows into account. So the caller of this function
```
Comment (Geometror) [inline scene/main/viewport.cpp:1635]: I would put this comment above the function so that certain editors/IDEs show it in the info popup, e.g. like in VSCode:

image

**Review by Geometror — APPROVED** [review]
Looks good! Tested locally and I can confirm that this fixes the linked issue.

Edit: Maybe `gui_find_control` should be fixed to handle (embedded) subwindows since the former comment implies that this is a bug, but that can be done separately from this PR.

**Comment by akien-mga** [comment]
Thanks!
