### PR TITLE
Save "Show Built-In Actions" state to project metadata

### LINKED ISSUE #80828: Project -> Project Settings -> Input Map -> Show Built-In Actions - does not keep its state after editor restart.
### Godot version

4.2.dev3.official

### System information

Godot v4.2.dev3 - Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

The toggle button "Show Built-In Actions" in the "Input Map" tab of the Project Settings window does not keep its ON state after restarting the editor - it always resets to being OFF.

This is different than the behaviour of the "Advanced Settings" toggle button in the "General" tab of the Project Settings - this one does keep its state between editor restarts.

I'm not sure if what I am reporting is an issue or the intended behaviour.

### Steps to reproduce

1. Create a new project.
2. Go to Project -> Project Settings -> Input Map and toggle "Show Built-In Actions" button to ON.
3. Restart the Godot editor.
4. Check if the setting was kept or changed.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
"Show Built-In Actions" button keep its state after editor restart now, fixes #80828

### CODE REVIEW

**Review by dalexeev — APPROVED** [review]
Looks good to me.

File: editor/action_map_editor.cpp [hunk 1]
```diff
@@ -573,6 +575,11 @@ ActionMapEditor::ActionMapEditor() {
 	show_builtin_actions_checkbutton->connect("toggled", callable_mp(this, &ActionMapEditor::set_show_builtin_actions));
 	add_hbox->add_child(show_builtin_actions_checkbutton);
 
+	show_builtin_actions = EditorSettings::get_singleton()->get_project_metadata("project_settings", "show_builtin_actions", false);
+	if (show_builtin_actions) {
+		show_builtin_actions_checkbutton->set_pressed(true);
```
Comment (AThousandShips) [inline editor/action_map_editor.cpp:580]: I'd remove the above assignment of false (line 573) and make it a single `set_pressed` with the loaded value

Comment (jsjtxietian) [reply editor/action_map_editor.cpp:580]: Sounds great !

**Review by AThousandShips — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks! Please in future make sure that your commit message is formatted just like the PR title would, with proper capitalization and all the necessary punctuation marks.
