### PR TITLE
Make platform feature tag names lowercase

### LINKED ISSUE #2492: Make all feature tag names lowercase
*See also https://github.com/godotengine/godot/pull/47255.*

### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

[Feature tags](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html) are case-sensitive. Most feature tags like `mobile` have lowercase names, but platform feature tags are an exception: `Windows`, `OSX`, `HTML5`, …

This can lead to surprises when attempting to override project settings based on feature tags, especially from C++ code where you don't have access to a graphical Project Settings editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use the lowercase platform name for platform feature tags.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Change the following feature tag names:

- `Windows` -> `windows`
- `OSX` -> `osx`
- `Linux` -> `linux` (also applies to FreeBSD, NetBSD, and BSD)
- `Android` -> `android`
- `iOS` -> `ios`
- `HTML5` -> `html5`
- `JavaScript` -> `javascript`
- `UWP` -> `uwp`
- `Server` -> `server`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as default feature tags are hardcoded.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

### PR DESCRIPTION
**Pull request by Calinou**
Feature tag names are still case-sensitive, but this makes built-in feature tags more consistent.

- `Windows` -> `windows`
- `OSX` -> `osx`
- `Linux` -> `linux` (also applies to FreeBSD, NetBSD, and BSD)
- `Android` -> `android`
- `iOS` -> `ios`
- `HTML5` -> `html5`
- `JavaScript` -> `javascript`
- `UWP` -> `uwp`
- `Server` -> `server`

This also hides the "X11" feature tag in the project settings editor's override list and adds Linux and BSD manually. Ideally, this should be fixed properly but I don't know how to do it right now. I think we should have a single `linuxbsd` feature tag as there's not much reason to have separate feature tags for Linux and *BSD.

This closes https://github.com/godotengine/godot-proposals/issues/2492.

## Preview

Using `print(ProjectSettings.get_setting("application/config/hello"))` will display `hello from Linux` on Linux, and `hello world` on all other platforms.

*The correct name to use is `linux`, the others are present just for testing.*

image

### CODE REVIEW

File: editor/project_settings_editor.cpp [hunk 1]
```diff
@@ -220,15 +220,24 @@ void ProjectSettingsEditor::_add_feature_overrides() {
 	presets.insert("standalone");
 	presets.insert("32");
 	presets.insert("64");
-	presets.insert("Server"); // Not available as an export platform yet, so it needs to be added manually
+	presets.insert("server"); // Not available as an export platform yet, so it needs to be added manually.
```
Comment (akien-mga) [inline editor/project_settings_editor.cpp:223]: Server has been removed.

File: editor/project_settings_editor.cpp [hunk 2]
```diff
@@ -220,15 +220,24 @@ void ProjectSettingsEditor::_add_feature_overrides() {
...
+	presets.insert("linux"); // Not reported in the list of export platforms yet, so it needs to be added manually.
+	presets.insert("bsd"); // Not reported in the list of export platforms yet, so it needs to be added manually.
```
Comment (akien-mga) [inline editor/project_settings_editor.cpp:225]: I'm not fond of hardcoding those here. They should be registered by the `linuxbsd` platform code if relevant. They're not directly related to this PR though so I'd probably leave them out here and make another PR to assess whether they're wanted and how to include them.

File: editor/project_settings_editor.cpp [hunk 3]
```diff
@@ -220,15 +220,24 @@ void ProjectSettingsEditor::_add_feature_overrides() {
...
 		List<String> p;
 		ee->get_export_platform(i)->get_platform_features(&p);
 		for (List<String>::Element *E = p.front(); E; E = E->next()) {
-			presets.insert(E->get());
+			// Feature tags for platform names are lowercase.
+			if (E->get().to_lower() == "x11") {
+				// `x11` is no longer a valid feature tag name in Godot 4.0 and later.
+				// Use `linux` or `bsd` instead.
+				continue;
+			}
```
Comment (akien-mga) [inline editor/project_settings_editor.cpp:238]: This comes from the platform preset, no? So would `x11` even be present in the first place? I don't think this kind of compatibility code is needed here.

**Review by akien-mga — APPROVED** [review]
Change approved in PR review meeting.

**Comment by akien-mga** [comment]
There's still some review comments to address (and a rebase to do) before this can be merged.

**Comment by reduz** [comment]
@Calinou please don' t forget about this.

**Comment by Calinou** [comment]
Rebased and tested again on Linux, it works successfully.

File: editor/project_settings_editor.cpp (hunk 3 above)
Comment (Calinou) [reply editor/project_settings_editor.cpp]: I removed this part as it's no longer useful with the new approach.

File: editor/project_settings_editor.cpp (hunk 2 above)
Comment (Calinou) [reply editor/project_settings_editor.cpp]: I found a different way to address this by modifying `OS::has_feature()` instead. This hack is no longer needed.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks for this :)
