### PR TITLE
Fix crash on calling play() in a uninitialized AnimatedSprite2D (Fix #46013)

### LINKED ISSUE #46013: Executing `AnimatedSprite.new().play(".", true)` crashes Godot
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
AnimatedSprite.new().play(".", true)
```

crashes with backtrace
```
ERROR: set_animation: There is no animation with name '.'.
   At: scene/2d/animated_sprite.cpp:651.
scene/2d/animated_sprite.cpp:614:37: runtime error: member call on null pointer of type 'struct SpriteFrames'
scene/2d/animated_sprite.cpp:614:37: runtime error: member access within null pointer of type 'struct SpriteFrames'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x16f757a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fa82c98e210] (??:0)
[3] AnimatedSprite::play(StringName const&, bool) (/mnt/Miecz/godot3.2/scene/2d/animated_sprite.cpp:614)
[4] MethodBind2<StringName const&, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:1523 (discriminator 19))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[8] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1269)
[9] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1278)
[10] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:152)
[11] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[15] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:197)
[16] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:186 (discriminator 2))
[17] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[18] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:464)
[19] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[20] godots(main+0x331) [0x16ee467] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fa82c96f0b3] (??:0)
[22] godots(_start+0x2e) [0x16ee07e] (??:?)
```

### PR DESCRIPTION
**Pull request by jmb462**
Fix #46013

### Issue Fixed

When AnimatedSprite2D::play() was called before SpriteFrames has been initialized, a crash occurred.

### Cause of crash

In AnimatedSprite2D::play(), frames->get_frame() can be called even if frames is null.
Occurs when play() is called before frames are initialized.

### Fix proposal

An informative error message on null check test has been added to prevent crash.
`ERR_FAIL_NULL_MSG(frames, "SpriteFrames reference is invalid (NULL) in AnimatedSprite2D::play()");`

### CODE REVIEW

**Comment by gongpha** [comment]
IMO, It should be placed on top of the function to early check. Otherwise, `set_animation` also had a check and the message may print out twice.

**Comment by jmb462** [comment]
> IMO, It should be placed on top of the function to early check. Otherwise, `set_animation` also had a check and the message may print out twice.

I agree with you. Change done.

File: scene/2d/animated_sprite_2d.cpp [hunk 1]
```diff
@@ -382,6 +382,7 @@ bool AnimatedSprite2D::_is_playing() const {
 }
 
 void AnimatedSprite2D::play(const StringName &p_animation, const bool p_backwards) {
+	ERR_FAIL_NULL_MSG(frames, "SpriteFrames reference is invalid (NULL) in AnimatedSprite2D::play()");
```
Comment (akien-mga) [inline scene/2d/animated_sprite_2d.cpp:385]: The actual error will already include a mention of `AnimatedSprite2D::play()` and `frames` being `NULL`, so it doesn't need to be repeated. I'd suggest instead:
```suggestion
	ERR_FAIL_NULL_MSG(frames, "Can't play AnimatedSprite2D without a valid SpriteFrames resource.");
```

Comment (jmb462) [reply scene/2d/animated_sprite_2d.cpp]: Can't see null pointer is included in the default error message but seems to be easier to understand anyway. 

Capture d’écran 2021-03-17 150211

Done.

Comment (akien-mga) [reply scene/2d/animated_sprite_2d.cpp]: It should be included in Godot's debugger when you click the error ("C++ error").

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.
