### PR TITLE
Automatically reparent editor message dialogs to avoid error spam.

### LINKED ISSUE #73356: "Transient parent has another exclusive child." when exporting Android Gradle build
### Godot version

4.0.rc2.official

### System information

Mageia 9, Linux

### Issue description

Users have been accustomed to our "Transient parent has another exclusive child." errors, some occurrence of which got fixed following #67122. But it still happens in some circumstances, so we should keep track of those and ideally fix them.

This even became meme material :) https://www.reddit.com/r/godot/comments/10zhq56/i_love_when_the_editor_speaks_in_tongues/

If anything, I think we could make this error verbose only, as it doesn't seem to affect the use of the editor and end users can't do anything about it.

---

So I noticed one occurrence when exporting to Android with "Use Gradle Build" enabled, which shows another exclusive popup with the gradle build output.

Here's a stacktrace:
```
(gdb) bt
#0  Window::set_visible (this=0x1be64380, p_visible=true) at scene/main/window.cpp:748
#1  0x00000000083c6e98 in Window::popup (this=0x1be64380, p_screen_rect=...) at scene/main/window.cpp:1546
#2  0x00000000083c6b69 in Window::popup_centered_ratio (this=0x1be64380, p_ratio=0.800000012) at scene/main/window.cpp:1508
#3  0x00000000074ec562 in EditorNode::execute_and_show_output (this=0xe40c430, p_title=..., p_path=..., p_arguments=..., p_close_on_ok=true, p_close_on_errors=false) at editor/editor_node.cpp:6524
#4  0x00000000070d2dab in EditorExportPlatformAndroid::export_project_helper (this=0xf30e8f0, p_preset=..., p_debug=true, p_path=..., export_format=0, should_sign=true, p_flags=0)
    at platform/android/export/export_plugin.cpp:2903
#5  0x00000000070cf9bb in EditorExportPlatformAndroid::export_project (this=0xf30e8f0, p_preset=..., p_debug=true, p_path=..., p_flags=0) at platform/android/export/export_plugin.cpp:2671
#6  0x00000000079c18dd in ProjectExportDialog::_export_project_to_path (this=0x1020c630, p_path=...) at editor/export/project_export.cpp:1021
#7  0x00000000079d0e4e in call_with_variant_args_helper<ProjectExportDialog, String const&, 0ul> (p_instance=0x1020c630, 
    p_method=(void (ProjectExportDialog::*)(ProjectExportDialog * const, const String &)) 0x79c16ae <ProjectExportDialog::_export_project_to_path(String const&)>, p_args=0x7fffffff8c80, r_error=...)
    at ./core/variant/binder_common.h:293
#8  0x00000000079d06b0 in call_with_variant_args<ProjectExportDialog, String const&> (p_instance=0x1020c630, 
    p_method=(void (ProjectExportDialog::*)(ProjectExportDialog * const, const String &)) 0x79c16ae <ProjectExportDialog::_export_project_to_path(String const&)>, p_args=0x7fffffff8c80, p_argcount=1, r_error=...)
    at ./core/variant/binder_common.h:407
#9  0x00000000079ce306 in CallableCustomMethodPointer<ProjectExportDialog, String const&>::call (this=0x10665dc0, p_arguments=0x7fffffff8c80, p_argcount=1, r_return_value=..., r_call_error=...)
    at ./core/object/callable_method_pointer.h:104
#10 0x000000000a08033d in Callable::callp (this=0x7fffb8003de8, p_arguments=0x7fffffff8c80, p_argcount=1, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#11 0x000000000a3b6214 in Object::emit_signalp (this=0x104fa740, p_name=..., p_args=0x7fffffff8c80, p_argcount=1) at core/object/object.cpp:1046
#12 0x0000000006376a0c in Object::emit_signal<String> (this=0x104fa740, p_name=...) at ./core/object/object.h:869
#13 0x00000000073a359c in EditorFileDialog::_action_pressed (this=0x104fa740) at editor/editor_file_dialog.cpp:489
#14 0x00000000073c2122 in call_with_variant_args_helper<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0x104fa740, 
    p_method=(void (EditorFileDialog::*)(EditorFileDialog * const)) 0x73a2570 <EditorFileDialog::_action_pressed()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:293
#15 0x00000000073c0a01 in call_with_variant_args<EditorFileDialog> (p_instance=0x104fa740, p_method=(void (EditorFileDialog::*)(EditorFileDialog * const)) 0x73a2570 <EditorFileDialog::_action_pressed()>, 
    p_args=0x0, p_argcount=0, r_error=...) at ./core/variant/binder_common.h:407
#16 0x00000000073bf464 in CallableCustomMethodPointer<EditorFileDialog>::call (this=0x105ace50, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...)
    at ./core/object/callable_method_pointer.h:104
#17 0x000000000a08033d in Callable::callp (this=0x22e1ee38, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#18 0x000000000a3b6214 in Object::emit_signalp (this=0x104fa740, p_name=..., p_args=0x0, p_argcount=0) at core/object/object.cpp:1046
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x0000000005852765 in Object::emit_signal<>(StringName const&) (this=0x104fa740, p_name=...) at ./core/object/object.h:869
#20 0x00000000084bd405 in AcceptDialog::_ok_pressed (this=0x104fa740) at scene/gui/dialogs.cpp:127
#21 0x00000000084c5b19 in call_with_variant_args_helper<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0x104fa740, 
    p_method=(void (AcceptDialog::*)(AcceptDialog * const)) 0x84bd3a4 <AcceptDialog::_ok_pressed()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:293
#22 0x00000000084c5204 in call_with_variant_args<AcceptDialog> (p_instance=0x104fa740, p_method=(void (AcceptDialog::*)(AcceptDialog * const)) 0x84bd3a4 <AcceptDialog::_ok_pressed()>, p_args=0x0, p_argcount=0, 
    r_error=...) at ./core/variant/binder_common.h:407
#23 0x00000000084c48b0 in CallableCustomMethodPointer<AcceptDialog>::call (this=0x10508a70, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:104
#24 0x000000000a08033d in Callable::callp (this=0x22f3add8, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#25 0x000000000a3b6214 in Object::emit_signalp (this=0x10503e80, p_name=..., p_args=0x0, p_argcount=0) at core/object/object.cpp:1046
#26 0x0000000005852765 in Object::emit_signal<>(StringName const&) (this=0x10503e80, p_name=...) at ./core/object/object.h:869
#27 0x00000000083f9e39 in BaseButton::_pressed (this=0x10503e80) at scene/gui/base_button.cpp:138
#28 0x00000000083fa353 in BaseButton::on_action_event (this=0x10503e80, p_event=...) at scene/gui/base_button.cpp:172
#29 0x00000000083f9aae in BaseButton::gui_input (this=0x10503e80, p_event=...) at scene/gui/base_button.cpp:69
#30 0x000000000848d14f in Control::_call_gui_input (this=0x10503e80, p_event=...) at scene/gui/control.cpp:1746
#31 0x000000000837a12b in Viewport::_gui_call_input (this=0x104fa740, p_control=0x10503e80, p_input=...) at scene/main/viewport.cpp:1389
#32 0x000000000837b3b6 in Viewport::_gui_input_event (this=0x104fa740, p_event=...) at scene/main/viewport.cpp:1659
#33 0x0000000008382b0c in Viewport::push_input (this=0x104fa740, p_event=..., p_local_coords=false) at scene/main/viewport.cpp:2834
#34 0x00000000083c5ce1 in Window::_window_input (this=0x104fa740, p_ev=...) at scene/main/window.cpp:1370
#35 0x00000000083f3baa in call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul> (p_instance=0x104fa740, 
    p_method=(void (Window::*)(Window * const, const Ref<InputEvent> &)) 0x83c58ea <Window::_window_input(Ref<InputEvent> const&)>, p_args=0x7fffffffc8c8, r_error=...) at ./core/variant/binder_common.h:293
#36 0x00000000083f06a1 in call_with_variant_args<Window, Ref<InputEvent> const&> (p_instance=0x104fa740, 
    p_method=(void (Window::*)(Window * const, const Ref<InputEvent> &)) 0x83c58ea <Window::_window_input(Ref<InputEvent> const&)>, p_args=0x7fffffffc8c8, p_argcount=1, r_error=...) at ./core/variant/binder_common.h:407
#37 0x00000000083ec71a in CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call (this=0x104fba40, p_arguments=0x7fffffffc8c8, p_argcount=1, r_return_value=..., r_call_error=...)
    at ./core/object/callable_method_pointer.h:104
#38 0x000000000a08033d in Callable::callp (this=0x7fffffffc870, p_arguments=0x7fffffffc8c8, p_argcount=1, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#39 0x000000000523e70f in DisplayServerX11::_dispatch_input_event (this=0xc1e6c40, p_event=...) at platform/linuxbsd/x11/display_server_x11.cpp:3546
#40 0x000000000523e487 in DisplayServerX11::_dispatch_input_events (p_event=...) at platform/linuxbsd/x11/display_server_x11.cpp:3517
#41 0x000000000a01f8a3 in Input::_parse_input_event_impl (this=0xbb86930, p_event=..., p_is_emulated=false) at core/input/input.cpp:690
--Type <RET> for more, q to quit, c to continue without paging--
#42 0x000000000a020cac in Input::flush_buffered_events (this=0xbb86930) at core/input/input.cpp:940
#43 0x000000000524343b in DisplayServerX11::process_events (this=0xc1e6c40) at platform/linuxbsd/x11/display_server_x11.cpp:4614
#44 0x000000000522302e in OS_LinuxBSD::run (this=0x7fffffffd1a0) at platform/linuxbsd/os_linuxbsd.cpp:876
#45 0x000000000521a500 in main (argc=2, argv=0x7fffffffd708) at platform/linuxbsd/godot_linuxbsd.cpp:73
```

For the record, here's the stack of windows when this happens (actually some time after, I had to `continue` so the windows are visible):
image

The same error happens a second time at the end of the export, with the exact same stacktrace aside from frame 4 being `platform/android/export/export_plugin.cpp:2933` instead of `platform/android/export/export_plugin.cpp:2903`.

### Steps to reproduce

- Create new project
- Install Android build template
- Add Android export preset
- Select "Use Gradle Build"
- Export - when you press "Save", the gradle log output show up in a window and the error is raised

### Minimal reproduction project

Empty project.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/73356 (at least part of it).

### CODE REVIEW

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -47,7 +47,6 @@
 #include "core/version.h"
 #include "main/main.h"
 #include "scene/gui/color_picker.h"
-#include "scene/gui/dialogs.h"
```
Comment (YuriSizov) [inline editor/editor_node.cpp:50]: Did you remove it because it's redundant due to indirect inclusion from FileDialog? I think we prefer explicitness with includes, as otherwise some weird dependency issues crop up.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -151,6 +150,49 @@ EditorNode *EditorNode::singleton = nullptr;
 // The metadata key used to store and retrieve the version text to copy to the clipboard.
 static const String META_TEXT_TO_COPY = "text_to_copy";
 
+class AcceptDialogAutoReparent : public AcceptDialog {
```
Comment (YuriSizov) [inline editor/editor_node.cpp:153]: Will this work correctly with all virtual and ML calls without the GDCLASS macro?

Comment (bruvzg) [reply editor/editor_node.cpp:154]: Nothing here requires it, but it should be there in case something will need it in the future. Fixed.

File: editor/editor_node.cpp (hunk 1 above)
Comment (bruvzg) [reply editor/editor_node.cpp]: It was moved it the header, and I forgot to put it back. Fixed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
I noticed an issue while testing this locally, probably related to this PR.
When testing the MRP from https://github.com/godotengine/godot/issues/72989
- Open city.tscn, select Garage, for Vehicle A select Quick Load and the one available resource
- There's a error dialog shown as described in #72989 (that's expected), but then in the terminal (and toaster for a dev build):
```
ERROR: Condition "!is_inside_tree()" is true.
   at: push_unhandled_input (scene/main/viewport.cpp:2845)
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
