### PR TITLE
Validate image size for `Noise` get image methods

### LINKED ISSUE #60637: Executing `FastNoiseLite.get_seamless_image` crashes Godot
### Godot version

4.0.alpha.custom_build. cbdc33bcf

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

When executing
```
	var temp_variable5178 = FastNoiseLite.new()
	temp_variable5178.get_seamless_image(4, -1, true, true, 1.55910432338715)
```

Godot crashes with this backtrace
```
ERROR: Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
   at: resize (./core/templates/cowdata.h:259)
ERROR: Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
   at: resize (./core/templates/cowdata.h:259)
ERROR: Image height must be greater than 0.
   at: create (core/io/image.cpp:1971)
ERROR: Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
   at: resize (./core/templates/cowdata.h:259)
modules/noise/noise.h:63:62: runtime error: division by zero

================================================================
handle_crash: Program crashed with signal 8
Engine version: Godot Engine v4.0.alpha.custom_build (cbdc33bcf73090962e60c1cf5ee50a21b29e4bad)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x23dd45c] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:55)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fbdf5b7a520] (??:0)
[3] Noise::img_buff<unsigned char>::operator()(int, int, Noise::img_buff<unsigned char>::ALT_MODULO) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/noise/noise.h:63 (discriminator 6))
[4] Ref<Image> Noise::_generate_seamless_image<unsigned char>(Ref<Image>, int, int, bool, float) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/noise/noise.h:170)
[5] Noise::get_seamless_image(int, int, bool, bool, float) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/noise/noise.cpp:42)
[6] void call_with_variant_args_retc_helper<__UnexistingClass, Ref<Image>, int, int, bool, bool, float, 0ul, 1ul, 2ul, 3ul, 4ul>(__UnexistingClass*, Ref<Image> (__UnexistingClass::*)(int, int, bool, bool, float) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul, 3ul, 4ul>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:705 (discriminator 4))
[7] void call_with_variant_args_retc_dv<__UnexistingClass, Ref<Image>, int, int, bool, bool, float>(__UnexistingClass*, Ref<Image> (__UnexistingClass::*)(int, int, bool, bool, float) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:471)
[8] MethodBindTRC<Ref<Image>, int, int, bool, bool, float>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:582)
[9] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:839 (discriminator 1))
[10] Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/variant_call.cpp:1021)
[11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1544)
[12] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1543)
[13] bool Node::_gdvirtual__process_call<false>(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:235 (discriminator 5))
[14] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:57)
[15] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:45 (discriminator 14))
[16] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:850)
[17] SceneTree::_notify_group_pause(StringName const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:855)
[18] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:454 (discriminator 4))
[19] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2722)
[20] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:441)
[21] godot4s(main+0x48a) [0x23dad70] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:70)
[22] /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7fbdf5b61fd0] (??:0)
[23] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7fbdf5b6207d] (??:0)
[24] godot4s(_start+0x2e) [0x23da82e] (??:?)
-- END OF BACKTRACE --

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #60637

Zero is not allowed because it'll later be passed to `Image::create_image()` which won't allow zero.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

File: modules/noise/noise.cpp [hunk 1]
```diff
@@ -31,6 +31,9 @@
 #include "noise.h"
 
 Ref<Image> Noise::get_seamless_image(int p_width, int p_height, bool p_invert, bool p_in_3d_space, real_t p_blend_skirt) const {
+	ERR_FAIL_COND_V(p_width <= 0, Ref<Image>());
+	ERR_FAIL_COND_V(p_height <= 0, Ref<Image>());
```
Comment (akien-mga) [inline modules/noise/noise.cpp:35]: I'd do both in one check with `||`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
