### PR TITLE
Clean up .blend importer to fix unreachable code paths

### LINKED ISSUE #66836: Mend fix visibility filtering options for .blend imports
### Godot version

1371a97acfb9263aaca7fa8642e95ba68534fa19

### System information

Windows 11, Nvidia 3000

### Issue description

\<Akien> I'm not sure this fix is complete, the logic that parses the option seems bogus as it treats the integer as a boolean. It will now "work" because All is 0 and so it will use the else branch which does the same as All, but that code is broken.

@jtnicholl

https://github.com/godotengine/godot/issues/66753

### Steps to reproduce

Need to recreate the sample.

### Minimal reproduction project

None

### PR DESCRIPTION
**Pull request by jtnicholl**
There were some checks to see if the options included certain enums, and also check if they weren't zero. If they were present and not zero, they were checked against zero _again_, creating unreachable code paths. The unreachable path for skinning options wasn't even setting the correct arguments, now that it's reachable I fixed that too.
Closes #66836.

### CODE REVIEW

**Comment by fire** [comment]
I'm not able to technical review promptly now, but I support this idea. If the test plan of checking that every single option in blender works and gives the correct result. This can be merged.

File: modules/gltf/editor/editor_scene_importer_blend.cpp [hunk 1]
```diff
@@ -77,20 +77,19 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
...
-			parameters_arg += "export_all_influences=False,";
+			parameters_arg += "export_skins=False,";
 		} else if (skins == BLEND_BONE_INFLUENCES_COMPATIBLE) {
-			parameters_arg += "export_all_influences=False,";
+			parameters_arg += "export_all_influences=False,export_skins=True,";
 		} else if (skins == BLEND_BONE_INFLUENCES_ALL) {
-			parameters_arg += "export_all_influences=True,";
+			parameters_arg += "export_all_influences=True,export_skins=True,";
 		}
-		parameters_arg += "export_skins=True,";
```
Comment (akien-mga) [inline modules/gltf/editor/editor_scene_importer_blend.cpp:89]: I'm not familiar with mesh skinning in Blender but it's not 100% clear to me how the enum values match the used options. I assume that if `export_skins` is `False` then `export_all_influences` isn't used at all?

Comment (fire) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:89]: @julienduroure I think that's correct, but maybe you have something to add.

Comment (jtnicholl) [reply modules/gltf/editor/editor_scene_importer_blend.cpp:89]: That is correct, it's an option related to skinning, so if skinning is disabled it has no effect.
In the exporter it's grayed out if skinning is off:
Screenshot_20221004_123232
Also this is the same arguments as the `else` statement that it was going to before. I made sure to test all the options, they work as expected.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by julienduroure** [comment]
Well, a little late on that, but seems to be ok :)
