### PR TITLE
Fix unchecked array access in build_*_planes

### LINKED ISSUE #46225: Executing `_Geometry::build_capsule_planes` crashes Godot
**Godot version:**
Godot 3.2.4 rc 2

**OS**
Ubuntu 20.04 - Ubuntu 3.36 X11

**Issue description:**
Executing
```
_Geometry.build_capsule_planes(-121.41335, 126.161397, -89, -343, -6)
```
address sanitizer shows this info
```
core/math/vector3.h:64:22: runtime error: index -48 out of bounds for type 'float [3]'
build_capsule_planes
Parameters [-121.41335, 126.161397, -89, -343, -6]
=================================================================
==66281==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fff1a1554f8 at pc 0x000011b66818 bp 0x7fff1a155480 sp 0x7fff1a155470
WRITE of size 4 at 0x7fff1a1554f8 thread T0
    #0 0x11b66817 in Geometry::build_capsule_planes(float, float, int, int, Vector3::Axis) core/math/geometry.cpp:939
    #1 0x120256a2 in _Geometry::build_capsule_planes(float, float, int, int, Vector3::Axis) core/bind/core_bind.cpp:1570
    #2 0x121b1341 in MethodBind5R<PoolVector<Plane>, float, float, int, int, Vector3::Axis>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:4177
    #3 0x114e3461 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #4 0x114e10e0 in Object::callv(StringName const&, Array const&) core/object.cpp:825
    #5 0x11548a7f in MethodBind2R<Variant, StringName const&, Array const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1717
    #6 0x114e3461 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #7 0x117688f9 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1129
    #8 0x1d920e7 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #9 0x1bc27e7 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1208
    #10 0x114e2fd1 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:898
    #11 0x117688f9 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1129
    #12 0x1d920e7 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #13 0x1bc3531 in GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1239
    #14 0x1bc37e4 in GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1246
    #15 0xc0090da in Node::_notification(int) scene/main/node.cpp:149
    #16 0x1a71307 in Node::_notificationv(int, bool) scene/main/node.h:46
    #17 0x1a7377c in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #18 0xdaf05b6 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #19 0x114e38fb in Object::notification(int, bool) core/object.cpp:929
    #20 0xc00b057 in Node::_propagate_ready() scene/main/node.cpp:196
    #21 0xc00a8bd in Node::_propagate_ready() scene/main/node.cpp:188
    #22 0xc059da6 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2613
    #23 0xc11d132 in SceneTree::init() scene/main/scene_tree.cpp:463
    #24 0x17ba51b in OS_X11::run() platform/x11/os_x11.cpp:3615
    #25 0x1726f06 in main platform/x11/godot_x11.cpp:56
    #26 0x7fd7324480b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #27 0x1726b1d in _start (/usr/bin/godots+0x1726b1d)

Address 0x7fff1a1554f8 is located in stack of thread T0 at offset 8 in frame
    #0 0x11b6663b in Geometry::build_capsule_planes(float, float, int, int, Vector3::Axis) core/math/geometry.cpp:934

  This frame has 14 object(s):
    [32, 44) 'axis' (line 938)
    [64, 76) 'axis_neg' (line 941)
    [96, 108) 'normal' (line 948)
    [128, 140) 'angle' (line 956)
    [160, 172) '<unknown>'
    [192, 204) 'pos' (line 957)
    [224, 236) '<unknown>'
    [256, 268) '<unknown>'
    [288, 300) '<unknown>'
    [320, 332) '<unknown>'
    [352, 364) '<unknown>'
    [384, 400) '<unknown>'
    [416, 432) '<unknown>'
    [448, 464) '<unknown>'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow core/math/geometry.cpp:939 in Geometry::build_capsule_planes(float, float, int, int, Vector3::Axis)
```

### PR DESCRIPTION
**Pull request by nmrkr**
Fixes #46225.

Also fixes the same problem in `build_sphere_planes` and `build_cylinder_planes`.

### CODE REVIEW

File: core/math/geometry_3d.cpp [hunk 1]
```diff
@@ -775,6 +775,8 @@ Vector<Plane> Geometry3D::build_box_planes(const Vector3 &p_extents) {
 }
 
 Vector<Plane> Geometry3D::build_cylinder_planes(real_t p_radius, real_t p_height, int p_sides, Vector3::Axis p_axis) {
+	ERR_FAIL_COND_V(!(p_axis == Vector3::AXIS_X || p_axis == Vector3::AXIS_Y || p_axis == Vector3::AXIS_Z), Vector<Plane>());
```
Comment (akien-mga) [inline core/math/geometry_3d.cpp:778]: That's a bit verbose, I'd simplify to:
```cpp
ERR_FAIL_INDEX_V(p_axis, 3, Vector<Plane>());
```

There's plenty occurrence of 3 dimensions being hardcoded/expected in this file so the magic number is not too bad.

**Comment by akien-mga** [comment]
Looks good, could you squash commits together? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by nmrkr** [comment]
Done, and thank you for linking the relevant doc. I kept wondering what the local policy concerning this might be, but somehow I missed that section...

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
