### PR TITLE
Fix `SplitContainerDragger` dragging with enabled screen reader, allow resizing with keyboard shortcuts.

### LINKED ISSUE #116535: Dock panel resizing stops when mouse enters 3D viewport during drag
### Tested versions

v4.6.1.stable.official
Godot Engine v4.6.1.stable.official.14d19694e - https://godotengine.org/
OpenGL API 3.3.0 NVIDIA 591.74 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1650
Same Issue on v4.6 stable

### System information

Window 10 x64 Latest - Godot v4.6.1 stable - GTX 1650 - Ryzen 3 3100

### Issue description

When resizing any dock panel (Scene Tree, Inspector, FileSystem, History, Bottom Panel, etc.), the resize operation stops immediately if the mouse cursor enters the 3D viewport while still dragging.

This issue affects all dock panels and only occurs when interacting near the 3D viewport. Resizing works correctly when dragging in directions that do not cross into the 3D viewport.

The issue does NOT occur in:
2D viewport
Script editor
Scene editor UI areas

The issue ONLY occurs when the cursor enters the 3D viewport.
This suggests the 3D viewport is capturing or interrupting mouse drag events during active UI resize operations.

### Steps to reproduce

1. Open any 3D project
2. Ensure 3D viewport is visible
3. Hover mouse over resize grab bar of any dock panel. Examples: [ Scene Tree, Inspector, FileSystem, Bottom Panel ]
4. Click and hold mouse button to resize
5. While still holding mouse button, move cursor into the 3D viewport
6. Observe resizing stops immediately

Expected result
- Resize operation continues normally regardless of cursor entering viewport
- Dock resizing remains active until mouse button is released

Actual result
- Resize operation stops immediately when cursor enters 3D viewport
- User must release mouse and start drag again

### Minimal reproduction project (MRP)

Simple New Project will do.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/116535

### CODE REVIEW

File: scene/gui/split_container.cpp [hunk 1]
```diff
@@ -39,11 +39,24 @@ void SplitContainerDragger::gui_input(const Ref<InputEvent> &p_event) {
...
 	if (sc->collapsed || sc->valid_children.size() < 2u || !sc->dragging_enabled) {
 		return;
 	}
 
+	if ((sc->vertical && p_event->is_action_pressed("ui_up", true)) || (!sc->vertical && p_event->is_action_pressed("ui_left", true))) {
+		sc->set_split_offset(sc->get_split_offset(dragger_index) - (sc->vertical ? sc->get_size().height : sc->get_size().width) * 0.1, dragger_index);
+		sc->clamp_split_offset(dragger_index);
+		accept_event();
+		return;
+	} else if ((sc->vertical && p_event->is_action_pressed("ui_down", true)) || (!sc->vertical && p_event->is_action_pressed("ui_right", true))) {
```
Comment (kitbdev) [inline scene/gui/split_container.cpp]: Left and right need to be flipped if rtl.

**Review by kitbdev — COMMENTED** [review]
Arrow keys work, but it doesn't fix dragging with the mouse for me.
Technically it doesn't account for children minimum size for arrow keys, but its fine.

https://github.com/user-attachments/assets/acc48969-b1b9-4e21-b7a3-a1b60f5bcabc

**Comment by bruvzg** [comment]
For the reference, `accept_event();` is what fining it on macOS, since `SplitContainerDragger` was grabbing focus on click.

**Review by kitbdev — APPROVED** [review]

**Comment by Repiteo** [comment]
Cherry-picked for 4.6.2.
