### PR TITLE
PopupMenu rework and enhancements.

### LINKED ISSUE #29111: Make possible to navigate overflowed 'PopupMenu's without a scroll wheel
**Godot version:**

15cda53

**OS/device including version:**

Linux

**Issue description:**
And therefore I cannot select a bone.

**Steps to reproduce:**
Use a BoneAttachment node in a skeleton with hundreds of bones

**Minimal reproduction project:**

[TooManyBones.zip](https://github.com/godotengine/godot/files/3209067/TooManyBones.zip)
https://user-images.githubusercontent.com/48971470/58204044-508c0800-7c90-11e9-8d11-c4642424b9ee.png

### LINKED ISSUE #41564: PopupMenu size doesn't respect usable screen size
**Godot version:**
master b0ca859501186b6fa088a3d3542f7dd4d72ae305

**OS/device including version:**
Linux (Ubuntu 20.04)
Also reproduced on Windows 10

**Issue description:**
PopupMenu items sometimes expand outside of the usable desktop space, either on top or behind decorations like task bars depending on the desktop system.

Example with Ubuntu/Gnome, the menu can show behind the top bar and the dock (when set at the bottom):

**Steps to reproduce:**
Simple repro case in the editor:
- Make an export variable of type Resource
- Click the resource load button in the inspector
- Scroll up and down through resource types

**Minimal reproduction project:**
[popup-menu-size-bug.zip](https://github.com/godotengine/godot/files/5137521/popup-menu-size-bug.zip)

### PR DESCRIPTION
**Pull request by EricEzaM**
Initially inspired by [this](https://www.reddit.com/r/godot/comments/id93w6/resizing_the_optionbutton_popupmenu/) reddit post, which never got it's own issue submitted. This PR resolves a few existing issues with PopupMenu's which did have issue tickets, but also a few others which I found when making this PR.

* Popup menu size can now be limited, and content will scroll. Previously, if the popup menu had a lot of items, it would take up the entire window height and then scroll from there. Now, the size of popup menus can be limited by using `get_popup()->set_max_size()` (in C++) or `get_popup().max_size` (in GDScript). Of course, this works both in editor and in projects.
* This can be selectively used around the editor to help resolve ui issues such as #22404. Examples in-editor shown below.
pum_in_game
* Added margin container which improves consistency of look, as well as makes item positioning code simpler and easier to understand.
* Now uses a scroll container so users know it can be scrolled. This also allows the user to scroll without a scroll wheel by clicking and dragging the scrollbar. Previously users needed a scroll wheel to be able to scroll. (Closes #29111)
pum_scrolling
* Changing item selection with arrow keys now scrolls to follow selected item, whereas previously it did not. (resolves this comment by @KoBeWi, which did not have a separate issue: https://github.com/godotengine/godot/issues/29111#issuecomment-495631414)
* Scrolling with arrow keys stops at first or last item when scrolling up and down, respectively. Previously it looped around and kept on going. 
pum_arrow_scrolling
* Fixed submenu autohide areas to match exactly the hover area. Previously they were slightly off. Also fixed selection of which item was hovered, as that was also slightly off. Previously the darker area which represented which item was hovered did not accurately represent the size of the actual item. As you can see, submenu's are correctly placed when scrolling is used. Note: I am not recommending that the project menu is made to scroll, this was only for submenu testing purposes.
pum_submenus
* When search is enabled, selected item from search query will be scrolled to and highlighted. In the below case I type "obj" and then "res".
pum_scroll_to_search
* Reduced code duplication by moving query of item icon size to a member function in the `Item` struct.
* General code clean up - comments where needed, and rewording variables to be more clear about what they are.

*Bugsquad edit:* Also fixes #41564.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Would be cool if you added [hysteresis](https://github.com/godotengine/godot/issues/11219) too 🙃
I have an unfinished PR that attempted to implement it: #35487

**Comment by EricEzaM** [comment]
@KoBeWi That's a good feature, I'll see if I can add it in this PR.

**Comment by groud** [comment]
It looks great ! :) I'll have a look to the code.

**Comment by EricEzaM** [comment]
@KoBeWi I have made some progress on adding that, but I think I would put it in a separate PR so it can be reviewed separately from this PR, and not too many features/changes get muddled up in one PR.

**Review by groud — APPROVED** [review]
The code looks good to me, but i haven't tested locally.

**Review by KoBeWi — CHANGES_REQUESTED** [review]
I did some testing and I noticed that some popups have maximum size that don't really make sense
VXpMW3yhhJ
Looks like it's calculated wrongly or something.

~~Also the new `max_size` property needs documentation.~~ (I now noticed it comes from Window)

Other than that, all seems to work fine.

**Comment by EricEzaM** [comment]
Hmm yeah it looks like the height of the contents  is calculated with an extra very small value, so the contents has to scroll a tiny bit. Will investigate in the morning

**Comment by EricEzaM** [comment]
Looks like there are a number of issues to resolve...

- [x] 1. (This existed before this PR) Popups have height set to 100px even if they do not need it. See `File -> Convert To...`. The weird thing is that this doesn't seem to apply to all menus... See `File -> Open Recent` (when the list is empty), which does not have the same issue. Edit: Resolved

image
image

- [x] 2. The issue Kobewi pointed out above, plus: the scroll bars do not focus automatically on what seems to be only these popup menus. When you hover the bar it does not highlight. Additionally, when you do click on the scrollbar *then* is highlights and you can click and scroll. Also, if you close it in it's highlighted state, it will stay that way when it comes up again. So it seems like the scrollbar is frozen to input or something? very weird. Edit: Resolved

popup_bug


- [x] 3. When a max size is not set, and the popup menu minimum size returns something higher than the screen height, no scrollbar is visible and you cannot scroll. Edit: Resolved now.

image

**Comment by EricEzaM** [comment]
@KoBeWi ok, all done. I found some more stuff as in my previous comment which is now resolves.

The issue you found was really weird... It seems like the setting of the margin was not occurring properly on the margin container. So, the margins were 10px, but the content thought it was only 8px (which is what it should be). Therefore there was a 4px scroll (10px*2 - 8px*2). Anyway, moving the setting of the margins away from notification enter tree is what worked.

@groud if you care to re-review, the changes of the most recent commit (which were squashed into one) were:

`popup.cpp`

- Added check which ensures popup is not larger than parent, and also does an early exit is max size is not set (Lines 129 to 141). This is part of what solved `#3` above

`popup_menu.cpp`

- Limited PopupMenu height to usable parent rect height. (lines 104 to 108) - this fixed `#3` above
- Used `set_as_minsize()` to 'shrink' the borders of the submenu (line 200) - this is what fixed `#1` above. Also did this in the `PopupMenu::Popup()` method, in case it is not a submenu.
- Moved setting of margin overrides for the margin container from ENTER_TREE to VISIBILITY_CHANGED (and after `is_visible()` check) - fixed Kobewi's issue and `#2` above

**Comment by EricEzaM** [comment]
As a bonus, this PR also fixes the issue where popup menus were going off screen:
image

After:
popup_in_screen

**Review by KoBeWi — APPROVED** [review]
Looks fine now after brief testing.

File: scene/gui/popup.cpp [hunk 1]
```diff
@@ -126,6 +126,27 @@ Rect2i Popup::_popup_adjust_rect() const {
...
+	if (current.size.y > parent.size.y) {
+		current.size.y = parent.size.y;
+	}
+
+	if (current.size.x > parent.size.x) {
+		current.size.x = parent.size.x;
+	}
+
+	// Early out if max size not set.
+	if (get_max_size() <= Size2()) {
```
Comment (pouleyKetchoupp) [inline scene/gui/popup.cpp:138]: You could call get_max_size() only once and keep the value locally here. Since it's doing a platform specific call, that would ensure it never does anything expensive several times.

File: scene/gui/popup_menu.h [hunk 2]
```diff
@@ -57,11 +59,17 @@ class PopupMenu : public Popup {
...
 		uint32_t accel;
 		int _ofs_cache;
+		int _height_cache;
 		int h_ofs;
 		Ref<ShortCut> shortcut;
 		bool shortcut_is_global;
 		bool shortcut_is_disabled;
 
+		// Returns (0,0) if icon is null.
+		const Size2 get_icon_size() const {
```
Comment (pouleyKetchoupp) [inline scene/gui/popup_menu.h:69]: The first const is not needed for a return value by copy.

**Review by pouleyKetchoupp — COMMENTED** [review]
Great work! I've just commented on some details.

I can also confirm the latest changes fix #41564.

File: scene/gui/popup.cpp (hunk 1 above)
Comment (EricEzaM) [reply scene/gui/popup.cpp]: Yeah good point, calling so many `get` methods in the same scope is quite the code smell.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! Amazing work :)

**Comment by groud** [comment]
Awesome, thanks a lot !

**Comment by chiguireitor** [comment]
will this be backported to the v3 branch?

**Comment by SJcoded** [comment]
Is this obselete?

**Comment by Calinou** [comment]
> Is this obselete?

This pull request was merged in the `master` branch (for 4.0.alpha), but it won't be cherry-picked to `3.x` as it introduces compatibility-breaking changes.

**Comment by Ev1lbl0w** [comment]
I'm interested in backporting these changes, but what are the mentioned "breaking changes"? And what features should I avoid backporting?

**Comment by EricEzaM** [comment]
I'm not too sure. @Calinou is it breaking change because of the fact that it changes the way the popup looks?

I don't think there was any breaking api changes by looking at the code, only the addition of the Max_size property. If you like, you can try backporting it and see how you go. Working through it will probably make any breaking changes more obvious.
