### PR TITLE
GDScript: Fix `@warning_ignore` annotation issues

### LINKED ISSUE #56592: `@warning_ignore()` annotation don't work with all warnings
### Godot version

4.0.dev.custom_build.096a13b3b

### System information

Linux, 5.16.0-1-MANJARO

### Issue description

The annotation "@warning_ignore" don't ignore all warnings properly, some are still raised even with the annotation

Properly ignored warnings:
- UNASSIGNED_VARIABLE
- UNUSED_VARIABLE
- UNUSED_LOCAL_CONSTANT
- SHADOWED_VARIABLE
- VOID_ASSIGNMENT
- NARROWING_CONVERSION
- INCOMPATIBLE_TERNARY
- INTEGER_DIVISION
- ASSERT_ALWAYS_TRUE
- ASSERT_ALWAYS_FALSE
- REDUNDANT_AWAIT

Not ignored warnings:
- UNUSED_PARAMETER
- UNASSIGNED_VARIABLE_OP_ASSIGN
- STANDALONE_EXPRESSION
- UNREACHABLE_CODE

Untested warnings:
- SHADOWED_VARIABLE_BASE_CLASS (not sure what it is exactly)
- UNUSED_PRIVATE_CLASS_VARIABLE (don't know how to make private class variable)
- UNREACHABLE_PATTERN (don't know what it is)
- STANDALONE_TERNARY (was raised as STANDALONE_EXPRESSION)
- UNUSED_SIGNAL (was not raised)
- RETURN_VALUE_DISCARDED (was not raised)

### Steps to reproduce

Use this code as a new script and look at the warning section.

```gdscript
extends Node

@warning_ignore(unused_signal)
signal unused_signal # UNUSED_SIGNAL not shown
signal awaited_signal

class test_entity:
	var shadowed_variable
	var shadowed_variable_base_class
	var property_used_as_function
	var active
	
	func void_assign() -> void:
		return
	
	func get_two() -> int:
		return 2
	@warning_ignore(unused_parameter)
	func test_function(unused_parameter: int) -> void: # UNUSED_PARAMETER
		@warning_ignore(unassigned_variable)
		var unassigned_var # UNASSIGNED_VARIABLE
		var a = unassigned_var
		print(a)
		
		var unassigned_var_op_assign 
		@warning_ignore(unassigned_variable_op_assign)
		unassigned_var_op_assign += 1 # UNASSIGNED_VARIABLE_OP_ASSIGN
		print(unassigned_var_op_assign)
		
		@warning_ignore(unused_variable)
		var unused_variable = 1 # UNUSED_VARIABLE
		
		@warning_ignore(unused_local_constant)
		const unused_constant = 1 # UNUSED_LOCAL_CONSTANT
		@warning_ignore(shadowed_variable)
		var shadowed_variable = 2 # SHADOWED_VARIABLE
		print(shadowed_variable)
		
		@warning_ignore(standalone_expression)
		2 + 2 # STANDALONE_EXPRESSION
		
		@warning_ignore(void_assignment)
		var void_assignment = void_assign() # VOID_ASSIGNMENT
		print(void_assignment)
		
		var test_float : float = 3.3
		@warning_ignore(narrowing_conversion)
		var test_int : int = test_float # NARROWING_CONVERSION
		print("%f %d" % [test_float, test_int])
		
		@warning_ignore(incompatible_ternary)
		test_float = 1 if 1 > 2 else null #INCOMPATIBLE_TERNARY
		
		@warning_ignore(return_value_discarded)
		get_two() #RETURN_VALUE_DISCARDED not shown
		
		@warning_ignore(integer_division)
		test_int = test_int / test_int # INTEGER_DIVISION
		
		@warning_ignore(standalone_ternary)
		42 if active else 0 # raise STANDALONE_EXPRESSION instead of STANDALONE_TERNARY
		
		@warning_ignore(assert_always_true)
		assert(true) # ASSERT_ALWAYS_TRUE
		@warning_ignore(assert_always_false)
		assert(false) # ASSERT_ALWAYS_FALSE
		
		@warning_ignore(redundant_await)
		await null # REDUNDANT_AWAIT
		
		return
		@warning_ignore(unreachable_code)
		print("unreachable code") # UNREACHABLE_CODE
	
	
class entity_child extends test_entity:
	func bidule() -> void:
		@warning_ignore(shadowed_variable_base_class)
		var shadowed_variable_base_class = 2# SHADOWED_VARIABLE, should have been SHADOWED_VARIABLE_BASE_CLASS ?
		print(shadowed_variable_base_class)

```

### Minimal reproduction project

[test_warning_ignore.zip](https://github.com/godotengine/godot/files/7829075/test_warning_ignore.zip)

### LINKED ISSUE #73222: @warning-ignore doesn't work for conditions statements
### Godot version

4.0-rc1

### System information

MacOS

### Issue description

The `@warning_ignore` decorator doesn't work for condition lines. Is it expected to work only on statements?

```gdscript
@warning_ignore("some_warning")
var x: String = line_with_warning() # works

@warning_ignore("some_warning")
if line_with_warning(): # warning persist
  pass
```

### Steps to reproduce

Given as example the usage of a static function on an instance:

```gdscript
class_name MyClass
extends Node

static func get_component_name() -> String:
  return "MyComponent"
```

And `_c` being an instance of `MyClass`

image

### Minimal reproduction project

N/A

### LINKED ISSUE #84719: warning_ignore attribute ignored in for loop range expression
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA RTX A2000 Laptop GPU (NVIDIA; 31.0.15.2737) - 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 Threads)

### Issue description

The `@warning_ignore` attribute is ignored or at least not applied as expected to a for loop range expression.

As such it is not possible to ignore a warning in a specific for loop expression. My current workaround is to ignore the warning across the entire function.

### Steps to reproduce

```gdscript
func _ready():
	var items: Array = [0, 1, 2, 3, 4]
	@warning_ignore("integer_division")
	for i in items.size() / 2:
		print(i)
```
The warning about integer division is still shown both in the ide and debugger.

### Minimal reproduction project

Trivial to reproduce without a specific project.

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #56592.
* Closes #73222.
* Closes #84719.

---

* Fix warnings produced in the parser are not ignored since `@warning_ignore`s are resolved and applied in the analyzer.
* Fix annotations before blocks (`if`, `for`, `while`, etc.) applied to the first most nested statement due to a bug with recursion.
* Fix parsing of standalone annotations in the script header.
* Deprecate outdated and unused warnings `PROPERTY_USED_AS_FUNCTION`, `CONSTANT_USED_AS_FUNCTION` and `FUNCTION_USED_AS_PROPERTY`. In 4.x properties, methods and signals share the same name scope, accessing methods without parentheses returns a `Callable`.
  * These warnings have also been moved to the end of the list. This does not break compatibility since the enum is not exposed to the public API.
  * ~~We could probably remove these warnings, since they are project settings (not real properties) and it is unlikely that anyone would use them.~~
* Add missed `STANDALONE_TERNARY` (a special case that replaces `STANDALONE_EXPRESSION`, since the ternary operator can have side effects) and `UNUSED_SIGNAL` warnings.
* Add support for `@warning_ignore` in `match` (to ignore the `UNREACHABLE_PATTERN` warning).
* Add support for `pass` in `match`.

_Production edit: closes godotengine/godot-roadmap#64_

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -4224,17 +4308,72 @@ bool GDScriptParser::export_group_annotations(const AnnotationNode *p_annotation
...
+					FunctionNode *function = static_cast<FunctionNode *>(p_target);
+					end_line = function->start_line;
+					for (int i = 0; i < function->parameters.size(); i++) {
+						end_line = function->parameters[i]->end_line;
+						if (function->parameters[i]->initializer != nullptr) {
+							end_line = function->parameters[i]->initializer->end_line;
+						}
+					}
+				} break;*/
+					/* clang-format on */
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp:4365]: We have a controversial feature: `@warning_ignore` applied to a function affects its entire body, not just the header (unused parameters, warnings on their initializers). Like here:

https://github.com/godotengine/godot/blob/b4e2a24c1f62088b3f7ce0197afc90832fc25009/modules/gdscript/tests/scripts/analyzer/warnings/shadowning.gd#L9-L17

Comment (Mickeon) [reply modules/gdscript/gdscript_parser.cpp:4365]: Controversial? I think it makes sense to me and reduces repetition. If `@warning_ignore` could be applied to the class itself it would make even more sense.

Comment (dalexeev) [reply modules/gdscript/gdscript_parser.cpp:4365]: For me, this is a controversial feature, since you can accidentally disable a warning for an entire function, although you intended to do it only for the parameter initializer.

Also, what about the other cases? In my opinion, ignoring a warning on a variable should not ignore warnings in its getter/setter, ignoring a warning on `if` should not ignore all warnings of that type in the entire block.

* Regarding mass-ignoring, see #76020.

File: doc/classes/ProjectSettings.xml [hunk 2]
```diff
@@ -461,11 +461,13 @@
 		<member name="debug/gdscript/warnings/confusable_local_usage" type="int" setter="" getter="" default="1">
 			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when an identifier that will be shadowed below in the block is used.
 		</member>
-		<member name="debug/gdscript/warnings/constant_used_as_function" type="int" setter="" getter="" default="1">
+		<member name="debug/gdscript/warnings/constant_used_as_function" type="int" setter="" getter="" default="1" is_deprecated="true">
 			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when a constant is used as a function.
+			[i]Deprecated.[/i] This warning is never produced. Instead, an error is generated if the expression type is known at compile time.
```
Comment (Mickeon) [inline doc/classes/ProjectSettings.xml:466]: I don't know how to feel about this. If they literally do not work it is better to remove them outright, otherwise it can get very confusing. There's a lot of "unordered" settings in the warning section and these contribute to clutter.

There's no compatibility broken here by removing them. Users that overrode the default setting for whatever reason will still keep this setting in the `.project` file, albeit they would no longer be built-in.
If the reason to deprecate them is to tell the user that these settings are not built-in, there should probably be a better way of going about it that is outside the scope of this PR...

Comment (dalexeev) [reply doc/classes/ProjectSettings.xml:466]: > There's no compatibility broken here by removing them.

Hypothetically, someone could use `@warning_ignore()`, although that wouldn't make sense. Removing the warnings will result in script error:

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (Mickeon) [reply modules/gdscript/gdscript_parser.cpp:4365]: Sorry, we do not see it the same way. I think warnings being ignored in the whole scope makes more sense in GDScript, as it's more accessible and easier to read. This is so long as it's documented and the behavior is consistent.

> > since you can accidentally disable a warning for an entire function, although you intended to do it only for the parameter initializer.

There's a clear distinction between the `unused_parameter` and `unused_property` warning and their purpose does not intertwine. I find this difficult to happen in practice.

> ignoring a warning on a variable should not ignore warnings in its getter/setter, ignoring a warning on if should not ignore all warnings of that type in the entire block.

Wen assigning a value a setter/getter function is called and the scope is shifted to the called function. So of course warnings would be issued only within that nested context.
```GDscript
var property: int:
    set(new_value):
         # Only warn about standalone expression here.
         @warning_ignore("standalone_expression")
         "Standalone expression"
         property = new_value

func _ready():
    # Only warn about narrowing conversion here.
    @warning_ignore("narrowing_conversion")
    property = 1.5
```
When an `if` condition passes or similar, a nested scope is created, I imagine. The behavior sounds consistent, to me.
```GDScript
# I know what I am doing here, but I may REALLY need that warning anywhere else.
@warning_ignore("narrowing_conversion")
@warning_ignore("integer_division")
func _ready():
    int_height = height_input.value / 2
    int_width = width_input.value / 2
    int_depth = depth_input.value / 2
```

I would be in favour of it over the [two new annotations](https://github.com/godotengine/godot/pull/76020) (does not mean they do not have merit).

File: doc/classes/ProjectSettings.xml (hunk 2 above)
Comment (Mickeon) [reply doc/classes/ProjectSettings.xml:466]: I see now. So it is hardcoded this way. A shame it has to be this way but it's better to document these as _deprecated_ than a compilation error I suppose, even though the ignore never did anything in practice.

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_parser.cpp:4365]: > There's a clear distinction between the `unused_parameter` and `unused_property` warning and their purpose does not intertwine. I find this difficult to happen in practice.

This is not true for other warning types:

https://github.com/godotengine/godot/assets/47700418/83aa875f-d6f2-49f5-86be-c781a0202e45

File: modules/gdscript/gdscript_parser.cpp [hunk 3]
```diff
@@ -4224,17 +4308,80 @@ bool GDScriptParser::export_group_annotations(const AnnotationNode *p_annotation
...
+
+			switch (p_target->type) {
+#define SIMPLE_CASE(m_type, m_class, m_property)          \
+	case Node::m_type: {                                  \
+		m_class *node = static_cast<m_class *>(p_target); \
+		if (node->m_property != nullptr) {                \
+			end_line = node->m_property->end_line;        \
+		} else {                                          \
+			end_line = node->start_line;                  \
+		}                                                 \
```
Comment (adamscott) [inline modules/gdscript/gdscript_parser.cpp:4333]:
```suggestion
		if (node->m_property == nullptr) {                \
			end_line = node->start_line;                  \
		} else {                                          \
					end_line = node->m_property->end_line;        \
		}                                                 \
```
I would flip this condition just to make sure that we don't begin with a not.

File: modules/gdscript/gdscript_parser.cpp [hunk 4]
```diff
@@ -4224,17 +4308,80 @@ bool GDScriptParser::export_group_annotations(const AnnotationNode *p_annotation
...
+
+				// Can contain properties (set/get).
+				SIMPLE_CASE(VARIABLE, VariableNode, initializer)
+
+				// Contain bodies.
+				SIMPLE_CASE(FOR, ForNode, list)
+				SIMPLE_CASE(IF, IfNode, condition)
+				SIMPLE_CASE(MATCH, MatchNode, test)
+				SIMPLE_CASE(WHILE, WhileNode, condition)
+#undef SIMPLE_CASE
```
Comment (adamscott) [inline modules/gdscript/gdscript_parser.cpp:4344]: I'm not sure about that definition, readability-wise. Especially since `m_type` is only used in the first line.
I would do something more akin this, but I may be wrong:

```suggestion
#define SIMPLE_CASE(m_class, m_property)          \
	m_class *node = static_cast<m_class *>(p_target); \
	if (node->m_property != nullptr) {                \
		end_line = node->m_property->end_line;        \
	} else {                                          \
		end_line = node->start_line;                  \
	}

				// Can contain properties (set/get).
				case Node::VARIABLE: { SIMPLE_CASE(VariableNode, initializer) } break;

				// Contain bodies.
				case Node::FOR: { SIMPLE_CASE(ForNode, list) } break;
				case Node::IF: { SIMPLE_CASE(IfNode, condition) } break;
				case Node::MATCH { SIMPLE_CASE(MatchNode, test) } break;
				case Node::WHILE { SIMPLE_CASE(WhileNode, condition) } break;
#undef SIMPLE_CASE
```

File: modules/gdscript/gdscript_parser.cpp [hunk 5]
```diff
@@ -4224,17 +4308,80 @@ bool GDScriptParser::export_group_annotations(const AnnotationNode *p_annotation
...
+					FunctionNode *function = static_cast<FunctionNode *>(p_target);
+					end_line = function->start_line;
+					for (int i = 0; i < function->parameters.size(); i++) {
+						end_line = MAX(end_line, function->parameters[i]->end_line);
+						if (function->parameters[i]->initializer != nullptr) {
+							end_line = MAX(end_line, function->parameters[i]->initializer->end_line);
+						}
+					}
+				} break;*/
+					/* clang-format on */
```
Comment (adamscott) [inline modules/gdscript/gdscript_parser.cpp:4365]: Maybe remove that part of code and mention in a comment why it doesn't apply to functions?

File: modules/gdscript/gdscript_warning.cpp [hunk 6]
```diff
@@ -58,7 +58,7 @@ String GDScriptWarning::get_message() const {
 			return vformat(R"*(The parameter "%s" is never used in the function "%s()". If this is intended, prefix it with an underscore: "_%s".)*", symbols[1], symbols[0], symbols[1]);
 		case UNUSED_SIGNAL:
 			CHECK_SYMBOLS(1);
-			return vformat(R"(The signal "%s" is declared but never emitted.)", symbols[0]);
+			return vformat(R"(The signal "%s" is declared but never used in the script.)", symbols[0]);
```
Comment (adamscott) [inline modules/gdscript/gdscript_warning.cpp:61]: Nice correction.

**Review by adamscott — APPROVED** [review]
Nice PR. Seems to fix a lot of issues. Maybe we could merge this PR before dev4, as it changes a lot of lines? cc. @akien-mga

File: modules/gdscript/gdscript_parser.cpp [hunk 7]
```diff
@@ -4224,17 +4308,80 @@ bool GDScriptParser::export_group_annotations(const AnnotationNode *p_annotation
 
 bool GDScriptParser::warning_annotations(const AnnotationNode *p_annotation, Node *p_target, ClassNode *p_class) {
 #ifdef DEBUG_ENABLED
```
Comment (adamscott) [inline modules/gdscript/gdscript_parser.cpp:4310]: What I meant [here](https://github.com/godotengine/godot/pull/76020#discussion_r1190040033) is to refactor the `#ifdef` into a `#ifndef`.

```suggestion
bool GDScriptParser::warning_annotations(const AnnotationNode *p_annotation, Node *p_target, ClassNode *p_class) {
#ifndef DEBUG_ENABLED
	// Only available in debug builds.
	return true;
#endif
```

Comment (dalexeev) [reply modules/gdscript/gdscript_parser.cpp:4310]: It probably makes sense to handle the simple case first, but isn't it "don't begin with a not" like above? Also, the return values of annotation application methods are not used, we could remove them in a separate PR.

File: modules/gdscript/gdscript_parser.cpp (hunk 4 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_parser.cpp:4344]: I would leave it as it is, maybe only remove `Node::` from the macro for readability. While there is no need to use the check inside a complex case, in my opinion it is better to leave `case` inside the macro. If this changes, then we can refactor it easily.

File: modules/gdscript/gdscript_warning.cpp (hunk 6 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_warning.cpp:61]:
```suggestion
			return vformat(R"(The signal "%s" is declared but never used in the class.)", symbols[0]);
```

File: modules/gdscript/gdscript_parser.cpp (hunk 7 above)
Comment (adamscott) [reply modules/gdscript/gdscript_parser.cpp:4310]: It's more akin the [Return early pattern](https://medium.com/swlh/return-early-pattern-3d18a41bba8) than anything else.

File: modules/gdscript/gdscript_warning.cpp [hunk 8]
```diff
@@ -162,10 +153,16 @@ String GDScriptWarning::get_message() const {
 			return vformat(R"*(The default value is using "%s" which won't return nodes in the scene tree before "_ready()" is called. Use the "@onready" annotation to solve this.)*", symbols[0]);
 		case ONREADY_WITH_EXPORT:
 			return R"("@onready" will set the default value after "@export" takes effect and will override it.)";
+#ifndef DISABLE_DEPRECATED
+		case PROPERTY_USED_AS_FUNCTION:
+		case CONSTANT_USED_AS_FUNCTION:
+		case FUNCTION_USED_AS_PROPERTY:
+			break; // Never produced.
+#endif
```
Comment (vnen) [inline modules/gdscript/gdscript_warning.cpp:161]: I don't think it's a good idea deprecating these just because they're unused. They should be produced instead, when relevant.

`FUNCTION_USED_AS_PROPERTY` is okay, since we have Callable now, but the others could be helpful.

File: modules/gdscript/gdscript_parser.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_parser.cpp]: I have marked this as resolved because I am not changing it in this PR. For further discussion, see #76020.

File: modules/gdscript/gdscript_warning.cpp [hunk 9]
```diff
@@ -76,18 +76,9 @@ String GDScriptWarning::get_message() const {
 		case STANDALONE_EXPRESSION:
 			return "Standalone expression (the line has no effect).";
 		case STANDALONE_TERNARY:
-			return "Standalone ternary conditional operator: the return value is being discarded.";
+			return "Standalone ternary operator: the return value is being discarded.";
```
Comment (dalexeev) [inline modules/gdscript/gdscript_warning.cpp:79]: I'm guessing that `STANDALONE_TERNARY` was probably added because of the "(the line has no effect)" in `STANDALONE_EXPRESSION` message. But in fact, these warnings are not much different. The static analyzer is currently not very good at detecting side effects, so `STANDALONE_EXPRESSION` may be produced for expressions with side effects. Could we reformulate the message so that it is not misleading?

Anyway, we already have `STANDALONE_TERNARY`, so it probably makes sense to make the warning work rather than deprecating it and producing `STANDALONE_EXPRESSION` instead?

Comment (adamscott) [reply modules/gdscript/gdscript_warning.cpp:79]: > The static analyzer is currently not very good at detecting side effects, so STANDALONE_EXPRESSION may be produced for expressions with side effects.

Yes, we're thinking about getters that introduce side-effects.

image

We could modify the `STANDALONE_EXPRESSION` to remove the parenthesis `(the line has no effect)`.

If we had error numbers, we could add a description to the error. Food for thought.

> Anyway, we already have STANDALONE_TERNARY, so it probably makes sense to make the warning work rather than deprecating it and producing STANDALONE_EXPRESSION instead?

So, as @dalexeev said in the meeting:
> Danil Alexeev says:STANDALONE_TERNARY is not currently implemented. This was just migrated from 3.x with no implementation. 

Yes, we could make `STANDALONE_TERNARY` work, if it's not too difficult to implement.

Comment (adamscott) [reply modules/gdscript/gdscript_warning.cpp:79]: @dalexeev in the meeting:
> We have a choice: either implement this (already done in the PR) or deprecate it and produce STANDALONE_EXPRESSION instead. 

We think it's ok then! Great!

**Comment by akien-mga** [comment]
Needs resyncing the docs for the `is_deprecated` -> `deprecated` change.

File: doc/classes/ProjectSettings.xml [hunk 10]
```diff
@@ -470,11 +470,13 @@
...
```
Comment (AThousandShips) [inline doc/classes/ProjectSettings.xml:475]:
```suggestion
		<member name="debug/gdscript/warnings/constant_used_as_function" type="int" setter="" getter="" default="1" deprecated="This warning is never produced. Instead, an error is generated if the expression type is known at compile time.">
			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when a constant is used as a function.
```

File: doc/classes/ProjectSettings.xml [hunk 11]
```diff
@@ -485,8 +487,9 @@
 		<member name="debug/gdscript/warnings/exclude_addons" type="bool" setter="" getter="" default="true">
 			If [code]true[/code], scripts in the [code]res://addons[/code] folder will not generate warnings.
 		</member>
-		<member name="debug/gdscript/warnings/function_used_as_property" type="int" setter="" getter="" default="1">
+		<member name="debug/gdscript/warnings/function_used_as_property" type="int" setter="" getter="" default="1" is_deprecated="true">
 			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when using a function as if it is a property.
+			[i]Deprecated.[/i] This warning is never produced. When a function is used as a property, a [Callable] is returned.
```
Comment (AThousandShips) [inline doc/classes/ProjectSettings.xml:492]:
```suggestion
		<member name="debug/gdscript/warnings/function_used_as_property" type="int" setter="" getter="" default="1" deprecated="This warning is never produced. When a function is used as a property, a [Callable] is returned.">
			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when using a function as if it is a property.
```

File: doc/classes/ProjectSettings.xml [hunk 12]
```diff
@@ -519,8 +522,9 @@
 		<member name="debug/gdscript/warnings/onready_with_export" type="int" setter="" getter="" default="2">
 			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when the [code]@onready[/code] annotation is used together with the [code]@export[/code] annotation, since it may not behave as expected.
 		</member>
-		<member name="debug/gdscript/warnings/property_used_as_function" type="int" setter="" getter="" default="1">
+		<member name="debug/gdscript/warnings/property_used_as_function" type="int" setter="" getter="" default="1" is_deprecated="true">
 			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when using a property as if it is a function.
+			[i]Deprecated.[/i] This warning is never produced. Instead, an error is generated if the expression type is known at compile time.
```
Comment (AThousandShips) [inline doc/classes/ProjectSettings.xml:527]:
```suggestion
		<member name="debug/gdscript/warnings/property_used_as_function" type="int" setter="" getter="" default="1" deprecated="This warning is never produced. Instead, an error is generated if the expression type is known at compile time.">
			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when using a property as if it is a function.
```

File: modules/gdscript/gdscript_warning.cpp (hunk 8 above)
Comment (adamscott) [reply modules/gdscript/gdscript_warning.cpp:161]:
```suggestion
#ifndef DISABLE_DEPRECATED
		case PROPERTY_USED_AS_FUNCTION:
		case CONSTANT_USED_AS_FUNCTION:
		case FUNCTION_USED_AS_PROPERTY:
			break; // Warnings never produced as they already produce errors.
#endif
```

File: doc/classes/ProjectSettings.xml [hunk 13]
```diff
@@ -593,7 +594,7 @@
 			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when a private member variable is never used.
 		</member>
 		<member name="debug/gdscript/warnings/unused_signal" type="int" setter="" getter="" default="1">
-			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when a signal is declared but never emitted.
+			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when a signal is declared but never used.
```
Comment (adamscott) [inline doc/classes/ProjectSettings.xml:597]:
```suggestion
			When set to [code]warn[/code] or [code]error[/code], produces a warning or an error respectively when a signal is declared but never explicitly used.
```

File: modules/gdscript/gdscript_warning.h [hunk 14]
```diff
@@ -50,9 +50,9 @@ class GDScriptWarning {
 		UNASSIGNED_VARIABLE_OP_ASSIGN, // Variable never assigned but used in an assignment operation (+=, *=, etc).
 		UNUSED_VARIABLE, // Local variable is declared but never used.
 		UNUSED_LOCAL_CONSTANT, // Local constant is declared but never used.
-		UNUSED_PRIVATE_CLASS_VARIABLE, // Class variable is declared private ("_" prefix) but never used in the file.
+		UNUSED_PRIVATE_CLASS_VARIABLE, // Class variable is declared private ("_" prefix) but never used in the class.
 		UNUSED_PARAMETER, // Function parameter is never used.
-		UNUSED_SIGNAL, // Signal is defined but never emitted.
+		UNUSED_SIGNAL, // Signal is defined but never used.
```
Comment (adamscott) [inline modules/gdscript/gdscript_warning.h:55]:
```suggestion
		UNUSED_SIGNAL, // Signal is defined but never explicitly used.
```

**Review by adamscott — APPROVED** [review]
Reviewed during the GDScript meeting. Other than small nitpicks, the PR seems absolutely fine! Thanks for your hard work, @dalexeev.

**Comment by MikeSchulze** [comment]
Thank you very much!
