### PR TITLE
Make silhouette fixer to use arc `Quaternion` constructor instead of `looking_at()`

### LINKED ISSUE #105703: Skeleton retarget regression in Fix Silhouette on Godot 4.4
### Tested versions

- Reproducible in 4.4-beta1, 4.4-stable, 4.4.1-stable
- Not reproducible in 4.3-stable, 4.4-dev5, 4.4-dev6, 4.4-dev7

### System information

Godot v4.4.beta1 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 threads)

### Issue description

Good behavior: 4.3-stable and all 4.4-dev builds print the following errors during import and work fine. During import, the following two errors are printed:
```
  ERROR: The target vector can't be zero.
  ERROR: The target vector and up vector can't be parallel to each other.
```
Here is a screenshot of expected behavior from Godot 4.4-dev7
Screenshot of Godot 4.4-dev7

Bad behavior: However, starting from 4.4-beta1 and newer, I instead get one error and several *warnings* which correspond with the error:
```
  ERROR: The target vector can't be zero.
  WARNING: core/math/basis.cpp:1053 - Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.
  WARNING: core/math/basis.cpp:1053 - Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.
  WARNING: core/math/basis.cpp:1053 - Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.
  WARNING: core/math/basis.cpp:1053 - Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.
  WARNING: core/math/basis.cpp:1053 - Target and up vectors are colinear. This is not advised as it may cause unwanted rotation around local Z axis.
```
Here is a picture of the import as of 4.4-beta1 and newer (taken from 4.4.1-stable):
Screenshot of Godot 4.4.1-stable showing the issue

### Steps to reproduce

1. Open the attached project.
2. Open addons/renik/sample_models in the filesystem and make a New Inherited Scene from godette.glb
3. Optionally open the advanced importer to confirm the import settings for Skeleton3D include a BoneMap with Fix Silhouette enabled.

### Minimal reproduction project (MRP)

[silhouette_fixer.zip](https://github.com/user-attachments/files/19886864/silhouette_fixer.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/105703
- Prerequisite https://github.com/godotengine/godot/pull/106337

Probably a problem dependent on the change in `looking_at()`, since the quaternion is now handled more accurately when rotating 180 degrees, so we should replace it with an implementation that.

To the reviewer, please properly test the comparison with past versions using several models. If you still have problems, perhaps you need to either change to an approach that uses look_at() or revise the epsilon values as I commented in https://github.com/godotengine/godot/issues/102679.

### CODE REVIEW

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 1]
```diff
@@ -367,31 +367,15 @@ void PostImportPluginSkeletonRestFixer::internal_process(InternalImportCategory
 
 				Vector3 prof_dir = prof_tail - prof_head;
 				Vector3 src_dir = src_tail - src_head;
+				if (prof_dir.is_zero_approx() || src_dir.is_zero_approx()) {
```
Comment (fire) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:370]: there'a an alternative way of coding this where we check length squared

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 2]
```diff
@@ -367,31 +367,15 @@ void PostImportPluginSkeletonRestFixer::internal_process(InternalImportCategory
...
-					Basis src_b;
-					src_b = src_b.looking_at(src_dir, up_vec);
-					Basis prof_b;
-					prof_b = src_b.looking_at(prof_dir, up_vec);
-					if (prof_b.is_equal_approx(Basis())) {
-						continue; // May not need to rotate.
-					}
-					Basis diff_b = prof_b * src_b.inverse();
-
+				if (Math::rad_to_deg((1.0 - src_dir.dot(prof_dir)) * Math::PI) > float(p_options["retarget/rest_fixer/fix_silhouette/threshold"])) {
```
Comment (precup) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:377]: Isn't this a behavior change from the old condition? The old threshold was relative to the angle, this one is relative to the cosine of the angle scaled up to fit in an angle range. It would change the effective value of threshold slightly. Perhaps too small of a difference to practically matter, but noting it anyways.

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp]: Oh, I had the wrong range to begin with (it should be `* 0.5 * Math::PI`). However, there should still be a slight difference between "atan with cross" and "simple dot" results, so if this is a problem, perhaps the original formula should be used.

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp]: At any rate, I reverted it back considering that this is a place where accuracy should be prioritized over performance so much. Thanks.

File: editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp [hunk 3]
```diff
@@ -367,31 +367,15 @@ void PostImportPluginSkeletonRestFixer::internal_process(InternalImportCategory
...
-					Basis src_b;
-					src_b = src_b.looking_at(src_dir, up_vec);
-					Basis prof_b;
-					prof_b = src_b.looking_at(prof_dir, up_vec);
-					if (prof_b.is_equal_approx(Basis())) {
-						continue; // May not need to rotate.
-					}
-					Basis diff_b = prof_b * src_b.inverse();
-
+					Basis diff_b = Basis(Quaternion(src_dir, prof_dir));
```
Comment (fire) [inline editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:378]: Do we need to normalize here?

Comment (TokageItLab) [reply editor/import/3d/post_import_plugin_skeleton_rest_fixer.cpp:378]: No, since src_dir and prof_dir are normalized.

**Review by lyuma — APPROVED** [review]
This seems reasonable. We just need to test it
