### PR TITLE
Core: Add typed array support for binary serialization

### LINKED ISSUE #69215: Unable to do an `rpc` with a function that uses arguments annotated with an typed Array
### Godot version

Godot_v4.0-beta6_win64

### System information

Windows 11

### Issue description

Godot gives me an error when I try to execute an rpc function that has an argument annotated as `Array[int]`, but it works fine when I remove the type annotation or change it to just `Array`. The data I'm sending is an `Array[int]`.

This is the code of the function (it doesn't work when it has the argument type annotation):
```gdscript
@rpc
func client_print_array(host_array: Array[int]):
    print("Host array: ", host_array)
    print("My array: ", self.array)
```

When I try to trigger the rpc from the host it gives me this error:
```
E 0:00:04:0771   _process_rpc: RPC - 'Node(Main.gd)::client_print_array': Cannot convert argument 1 from Array to Array
  <C++ Source>   modules/multiplayer/scene_rpc_interface.cpp:294 @ _process_rpc()
```
Removing the annotation fixes the problem.

### Steps to reproduce

1. Open the Minimal reproduction project
2. Run the projects as 2 instances
3. In the first instance press "Host"
4. In the second instance press "Join"
5. In the first (host) instance press "Send message"
6. Observe errors in the debugger.
  ```
  E 0:00:04:0771   _process_rpc: RPC - 'Node(Main.gd)::client_print_array': Cannot convert argument 1 from Array to Array
  <C++ Source>   modules/multiplayer/scene_rpc_interface.cpp:294 @ _process_rpc()
  ```
7. Modify the `Main.gd` script by removing type annotation on line 28
8. Repeat steps 1-5
9. Observe expected messages in the log output 
```
Host array: [1, 2, 3, 4]
My array: [4, 3, 2, 1]
```

### Minimal reproduction project

[RpcIntArrayIssueExample.zip](https://github.com/godotengine/godot/files/10096459/RpcIntArrayIssueExample.zip)

### LINKED ISSUE #74391: Typed Arrays don't seem to work correctly with MultiplayerSynchronizer
### Godot version

4.0 stable

### System information

Windows 10, NVidia RTX 3080, Vulkan

### Issue description

While working on a project where I wanted to sync an Array of Vector2i for setting up a tilemap, I discovered typed arrays don't seem to play nice with MultiplayerSynchronizer, neither Spawn or Sync mode. In particular, I am testing when a scene with a child synchronizer (syncing the exported array) is replicated by a MultiplayerSpawner. The workaround I found there was to use an Array instead of Array[Vector2i].

Another issue in this same reproduction project is that the automatically generated names for instanced scenes can cause path errors and prevent the scene from replicating to clients. I think this is related to https://github.com/godotengine/godot/issues/68508, maybe a configuration issue but I am running into this in my other project as well. If its not a config issue & different enough I can create a separate issue to capture it.

### Steps to reproduce

1. Run 2 instances of the project
2. Click Host on one
3. Click Connect on the other
4. Click "Spawn Test Label" on host, which will instantiate a simple label scene 

Note that it fails to correctly create the scene on clients when the 'array' property of spawn_label.gd is a typed array, but works fine when typed as a standard Array

Bonus issue:
5. Comment control.gd:43
6. Try steps 1-4 above and see error generated in console related to get_node

### Minimal reproduction project

[SyncTypedArray.zip](https://github.com/godotengine/godot/files/10889685/SyncTypedArray.zip)

### LINKED ISSUE #76841: `var_to_bytes` omits type of typed array
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11

### Issue description

```swift
@export var _e_export: Array[String]
func _ready():
    var bytes_export = var_to_bytes(_e_export)
    var var_export = bytes_to_var(bytes_export)
    _e_export = var_export # Error
```
This snippet of code will crash with the error `Trying to assign an array of type "Array" to a variable of type "Array[String]".` because `var_to_bytes` doesn't seem to store the type of the typed array `_e_export`.

### Steps to reproduce

1) Create a new project
2) Create a new empty scene and place the code snippet above inside a node

### Minimal reproduction project

[Typed_Array_Var_To_Bytes.zip](https://github.com/godotengine/godot/files/11421178/Typed_Array_Var_To_Bytes.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #76841.
* Closes #69215.
* Closes #74391.

```gdscript
@tool
extends EditorScript

func print_buffer(buffer: PackedByteArray) -> void:
    var hex := buffer.hex_encode()
    var res: String
    for i in range(0, mini(hex.length(), 64), 8):
        if i > 0:
            res += " "
        res += hex.substr(i, 8)
    print(res)

func _run() -> void:
    var a: Array = []
    var b: Array = [256]
    var c: Array[int] = [128]
    var d: Array[RefCounted] = [RefCounted.new()]
    var e: Array[MyClass] = [MyClass.new(111)]
    
    print_buffer(var_to_bytes(a))
    print_buffer(var_to_bytes(b))
    print_buffer(var_to_bytes(c))
    print_buffer(var_to_bytes_with_objects(d))
    print_buffer(var_to_bytes_with_objects(e))
    
    print(var_to_bytes_with_objects(e).hex_encode())
    
    print(bytes_to_var(var_to_bytes(a)))
    print(bytes_to_var(var_to_bytes(b)))
    print(bytes_to_var(var_to_bytes(c)))
    print(bytes_to_var_with_objects(var_to_bytes_with_objects(d)))
    print(bytes_to_var_with_objects(var_to_bytes_with_objects(e))[0].x)
    
    print(bytes_to_var_with_objects(var_to_bytes_with_objects(MyClass.new(222))).x)
```

For builtins, it is possible to optimize the size by removing the 4 bytes of type that are repeated before each element. And the element type can be encoded in the array type instead of separate 4 bytes.

I'm not sure if `OBJECT_AS_ID` can be used for arrays.

For scripts see:

https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/core/variant/variant_parser.cpp#L1936-L1951

_Production edit: closes godotengine/godot-roadmap#68_

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs rebase to fix CI.

**Comment by akien-mga** [comment]
Moving to 4.2 as this seems a bit risky to merge just before RC1, even if it was approved today. Could be considered for a cherry-pick if it's safe enough and not breaking.

**Comment by dalexeev** [comment]
I think this shouldn't be cherry-picked, since the array flags are not checked in master, and the type data will be recognized as the size (and elements) of the array.

**Comment by akien-mga** [comment]
Thanks for the input. How should we handle the data compatibility between 4.1 and 4.2 with this PR merged?

**Comment by dalexeev** [comment]
I don't know. 4.2 will be able to read 4.1 data (which stores typed arrays as untyped), but 4.1 will not be able to read 4.2 data correctly. Backward compatibility is respected, but forward compatibility is broken. This is OK in the case of save files, but can be a problem in the case of multiplayer games if the users' clients are using different versions of Godot. On the other hand, due to bug #69215 this should not be very common.

I think it's acceptable for a minor release if we add a warning to the 4.2 release notes? We could mitigate the impact by adding checks for array flags now or in later 4.1.x patch releases (without implementing support for typed arrays). But the problem will remain for all previous releases (e.g. 4.0.3) and non-upgraded clients.

Preserving forward compatibility (avoiding array type being recognized as size or elements) looks like an unrealistic or very hacky solution to me.

File: core/io/marshalls.cpp [hunk 1]
```diff
@@ -59,6 +62,13 @@ ObjectID EncodedObjectAsID::get_object_id() const {
 #define ENCODE_FLAG_64 1 << 16
 #define ENCODE_FLAG_OBJECT_AS_ID 1 << 16
 
+// Actually, these are not flags.
+#define ENCODE_FLAG_TYPED_ARRAY_BUILTIN 1 << 16
+#define ENCODE_FLAG_TYPED_ARRAY_CLASS_NAME 2 << 16
+#define ENCODE_FLAG_TYPED_ARRAY_SCRIPT 3 << 16
+// Occupies bits 16 and 17. If we need more flags, we can place them after.
+#define ENCODE_FLAG_TYPED_ARRAY_MASK 0b11 << 16
```
Comment (RandomShaper) [inline core/io/marshalls.cpp:70]: - Let me suggest putting the definitions inside parentheses.
- Isn't there an overlap between the first two and the third one? Shouldn't `ENCODE_FLAG_TYPED_ARRAY_SCRIPT` get its own bit? I think it'd be less error-prone to define them as `(1 << 16)`, `(1 << 17)` and so on.

Comment (dalexeev) [reply core/io/marshalls.cpp:70]:
```suggestion
// Occupies bits 16 and 17. If we need more flags, we can place them after.
#define ENCODE_FLAG_UNTYPED_ARRAY (0b00 << 16)
#define ENCODE_FLAG_TYPED_ARRAY_BUILTIN (0b01 << 16)
#define ENCODE_FLAG_TYPED_ARRAY_CLASS_NAME (0b10 << 16)
#define ENCODE_FLAG_TYPED_ARRAY_SCRIPT (0b11 << 16)
#define ENCODE_FLAG_TYPED_ARRAY_MASK (0b11 << 16)
```

I'm not sure how to name it better.

Comment (RandomShaper) [inline core/io/marshalls.cpp:70]: After some thinking, I suggest `ENCODE_FIELD_TYPED_ARRAY_*`.

Regarding parentheses, I realize the existing defined weren't using them. So, for consistency, either ignore my suggestion or add them to the existing ones (me liking the latter better).

File: core/io/marshalls.cpp [hunk 2]
```diff
@@ -1152,6 +1237,22 @@ Error encode_variant(const Variant &p_variant, uint8_t *r_buffer, int &r_len, bo
 				flags |= ENCODE_FLAG_OBJECT_AS_ID;
 			}
 		} break;
+		case Variant::ARRAY: {
+			Array array = p_variant;
+			if (array.is_typed()) {
+				Ref<Script> script = array.get_typed_script();
+				if (script.is_valid()) {
+					ERR_FAIL_COND_V(!p_full_objects, ERR_UNAVAILABLE);
+					flags |= ENCODE_FIELD_TYPED_ARRAY_SCRIPT;
```
Comment (dalexeev) [inline core/io/marshalls.cpp:1246]: It looks a little weird (flags vs field).

Comment (RandomShaper) [reply core/io/marshalls.cpp:1246]: Indeed. Maybe `flags` warrants a rename to `encode_data` or the like.

Comment (dalexeev) [reply core/io/marshalls.cpp]: I used `header` as in [documentation](https://docs.godotengine.org/en/stable/tutorials/io/binary_serialization_api.html#packet-specification):

> The lowest value two bytes are used to determine the type, while the highest value two bytes contain flags

File: core/io/marshalls.cpp [hunk 3]
```diff
@@ -657,6 +672,21 @@ Error decode_variant(Variant &r_variant, const uint8_t *p_buffer, int p_len, int
 							return err;
 						}
 
+						if (str == "script") {
+							String path;
+							err = _decode_string(buf, len, r_len, path);
```
Comment (dalexeev) [inline core/io/marshalls.cpp:677]: I think that even if it didn't work properly before (creating a new script instead of loading an existing one, causing the type checks to fail), we should still use a new flag (`HEADER_DATA_OBJECT_SCRIPT_AS_PATH`), for compatibility reasons?

File: core/io/marshalls.cpp (hunk 2 above)
Comment (RandomShaper) [reply core/io/marshalls.cpp]: Sorry for going on with the bikeshedding, but my point is to keep flags named `*_FLAG_*` (so it's very easy to understand they are independent bits) and the new values `*_FIELD_*` (so it's easy to understand it's a bunch of bits representing some other type). Then, both _flags_ and _fields_ would be considered part of the "header," "encoding data", or any other suiting name.

Comment (dalexeev) [reply core/io/marshalls.cpp]: Done.

```mermaid
flowchart LR
    header-->type
    header-->data
    data-->flag
    data-->field
```

File: core/io/marshalls.cpp (hunk 3 above)
Comment (dalexeev) [reply core/io/marshalls.cpp]: I used `decode_variant()` instead of `_decode_string()` and added a type check, now it doesn't break backwards compatibility.

**Comment by dalexeev** [comment]
Should we add `OBJECT_AS_ID` support for typed arrays? I'm not sure how it works and what it's for. I tried to do this 2 months ago, but I didn't succeed.

File: core/io/marshalls.cpp [hunk 4]
```diff
@@ -30,7 +30,10 @@
 
 #include "marshalls.h"
 
+#include "core/core_string_names.h"
+#include "core/io/resource_loader.h"
 #include "core/object/ref_counted.h"
+#include "core/object/script_language.h"
```
Comment (akien-mga) [inline core/io/marshalls.cpp:36]: Are you using ScriptLanguage here, or just Script?

Comment (dalexeev) [reply core/io/marshalls.cpp:36]: Just `Script`.

Comment (akien-mga) [reply core/io/marshalls.cpp:36]: Ah I thought Script was in its own file, but it's ScriptInstance that we recently split.

**Comment by dalexeev** [comment]
I think this shouldn't be cherry-picked, since the array flags are not checked in master, and the type data will be recognized as the size (and elements) of the array.

**Comment by raulsntos** [comment]
Can the changes to Object script serialization be cherry-picked? They fix `bytes_to_var_with_objects` and `var_to_bytes_with_objects` for Objects with C# scripts (and we need it for https://github.com/godotengine/godot/pull/83217).

The changes I mean are: https://github.com/godotengine/godot/pull/78219/files#diff-d6943ae2d070769f732c9b2ef76248b1ee57d45f1cae64d799611d9d34e17868R688-R696 and https://github.com/godotengine/godot/pull/78219/files#diff-d6943ae2d070769f732c9b2ef76248b1ee57d45f1cae64d799611d9d34e17868R1616-R1627.

**Comment by dalexeev** [comment]
> Can the changes to Object script serialization be cherry-picked? They fix `bytes_to_var_with_objects` and `var_to_bytes_with_objects` for Objects with C# scripts (and we need it for #83217).

Feel free to extract this into a separate PR for the 4.2 branch when it's created.

**Review by RandomShaper — APPROVED** [review]
LGTM, AFAIC. I think it's good to have this merged now we are early in the release cycle so potential issues are not disruptive.

**Comment by reduz** [comment]
I am not completely sure why this is needed. To me it sounds like assigning an array to a typedarray should just work via property or rpc as long as the content is compatible, and this is the real bug.

IMO this is a workaround that adds more complexity to a very sensitive area.

**Comment by reduz** [comment]
As you can see here, there should be automatic conversion taking place:
https://github.com/godotengine/godot/blob/9e65c5c0f4f8944d17fc7f5b05682206e9348d81/core/variant/array.cpp#L236

**Comment by reduz** [comment]
Nevermind my comment on this, it no longer works as I describe (it seems it was changed, @dalexeev mentioned [this](https://github.com/godotengine/godot-proposals/discussions/7364). I just forgot, but then we never fixed these functions.

To add more context for everyone on this thread since this can be a bit confusing. Originally typed arrays could be assigned from regular arrays and the typed array would do compatibility check (if the non typed array had the some format in the content as the typed array) and either convert or fail.

It looks like this caused issues on the GDScript side (as described on the proposal above) and was changed. The problem is that the binary serialization (this PR) still assumes the original behavior (hence why it does not serialize types, i just expects the receiver will convert on assignment) and this is why it needs to be fixed on this side.

That said, as this is an extremely security sensitive area (you can exploit a networking peer or crash it), I would place as a requirement that we ask a few more reviewers before merging (and we could make it a rule when this code is being modified).

I will be giving it a check, but at least definitely @Faless needs to give ok too before merging, and I would be happy if @AThousandShips can also review to find any potential bugs.

**Comment by dalexeev** [comment]
> I am not completely sure why this is needed. To me it sounds like assigning an array to a typedarray should just work via property or rpc as long as the content is compatible, and this is the real bug.

It was originally implemented differently, but now you cannot assign an array of a different type:

```gdscript
var a: Array = [1, 2, 3]
#var b: Array[int] = a # Error.
var b: Array[int]
b.assign(a) # OK.
prints(a == b, is_same(a, b)) # true false
```

Arrays are passed by reference, which would cause issues when multiple variables of different types reference the same array. And implicitly duplicating an array during assignment would be inconsistent and confusing.

* See also godotengine/godot-proposals#7364.

> As you can see here, there should be automatic conversion taking place

The `=` operator copies a reference, while the `assign()` method copies the contents.

File: core/io/marshalls.cpp [hunk 5]
```diff
@@ -745,7 +768,60 @@ Error decode_variant(Variant &r_variant, const uint8_t *p_buffer, int p_len, int
...
+				case HEADER_DATA_FIELD_TYPED_ARRAY_SCRIPT: {
+					ERR_FAIL_COND_V(!p_allow_objects, ERR_UNAUTHORIZED);
+
+					String path;
+					Error err = _decode_string(buf, len, r_len, path);
+					if (err) {
+						return err;
+					}
+					ERR_FAIL_COND_V_MSG(path.is_empty() || !path.is_resource_file(), ERR_INVALID_DATA, "Invalid script path: '" + path + "'.");
+					script = ResourceLoader::load(path);
```
Comment (AThousandShips) [inline core/io/marshalls.cpp:813]:
```suggestion
					script = ResourceLoader::load(path, "Script");
```
As above, I believe

File: core/io/marshalls.cpp [hunk 6]
```diff
@@ -670,7 +685,15 @@ Error decode_variant(Variant &r_variant, const uint8_t *p_buffer, int p_len, int
 							(*r_len) += used;
 						}
 
-						obj->set(str, value);
+						if (str == "script" && value.get_type() == Variant::STRING) {
+							String path = value;
+							ERR_FAIL_COND_V_MSG(path.is_empty() || !path.is_resource_file(), ERR_INVALID_DATA, "Invalid script path: '" + path + "'.");
```
Comment (AThousandShips) [inline core/io/marshalls.cpp:690]: Is the resource file a safety restriction here, i.e. arbitrary code execution? Otherwise, unless I'm mistaken, scripts can be loaded from anywhere

**Review by AThousandShips — APPROVED** [review]
This looks good to me, nothing sticks out as an issue

Some notes however, but nothing critical to my eyes

File: core/io/marshalls.cpp (hunk 6 above)
Comment (dalexeev) [reply core/io/marshalls.cpp:690]: There is a similar restriction in text serialization.

https://github.com/godotengine/godot/blob/107f2961ccfac179af7682eb5f6e7ea91e80040c/core/variant/variant_parser.cpp#L1989-L1991

I think `res://` can be considered a trusted source, unliker `user://`, `http://`, etc.

https://github.com/godotengine/godot/blob/107f2961ccfac179af7682eb5f6e7ea91e80040c/core/string/ustring.cpp#L4623-L4625

Comment (AThousandShips) [reply core/io/marshalls.cpp:690]: Then it's fine I think, parity is good here, could look into future optional permission for it with a new argument, but I think matching the behaviour of the text version makes sense 🙂

File: core/io/marshalls.cpp [hunk 7]
```diff
@@ -1523,8 +1618,21 @@ Error encode_variant(const Variant &p_variant, uint8_t *r_buffer, int &r_len, bo
 
 						_encode_string(E.name, buf, r_len);
 
+						Variant value;
+
+						if (E.name == CoreStringNames::get_singleton()->_script) {
+							Ref<Script> script = obj->get_script();
+							if (script.is_valid()) {
+								String path = script->get_path();
+								ERR_FAIL_COND_V_MSG(path.is_empty() || !path.is_resource_file(), ERR_UNAVAILABLE, "Failed to encode a path to a custom script.");
```
Comment (Faless) [inline core/io/marshalls.cpp:1627]: Well, this actually breaks encoding/decoding of builtin scripts, which which used to work.

**Review by Faless — CHANGES_REQUESTED** [review]
It seems mostly okay, but the PR breaks encoding and decoding of built-in scripts (see my comment below).

**Comment by Faless** [comment]
See this MRP for the issue:

[broken_builtin.zip](https://github.com/godotengine/godot/files/14431739/broken_builtin.zip)

File: core/io/marshalls.cpp (hunk 7 above)
Comment (dalexeev) [reply core/io/marshalls.cpp]: Fixed. This is because `is_resource_file()` does not allow sub-resources. But `ResourceLoader.load()` correctly loads built-in scripts.

https://github.com/godotengine/godot/blob/df78c0636d79c9545a283e0e2a926d623998cc27/core/string/ustring.cpp#L4623-L4625

**Comment by dalexeev** [comment]
@Faless I did this on purpose. When you deserialize a script, you get another instance of the script, a different class (albeit with the same source code). This didn't work properly before (typed variable assignments, type compatibility checking). Now it works where possible and explicitly fails where it doesn't.

**Comment by Faless** [comment]
> I did this on purpose. When you deserialize a script, you get another instance of the script, a different class

Well, that's the same for any other object. If I serialize a `Node`, then deserialize it, doing `node == deserialized_node` will return false. They are 2 different instances.

If we want to prevent this completely we should also change the deserialization part to always require a valid script path (right now, it can deserialize such scripts, but not serialize them).

We should also add the `breaks compat` label since if anyone is relying on that behavior, their project will break upon update (they'll have to manually handle serialization of those scripts).

**Comment by Cammymoop** [comment]
This is a pretty major change to script serialization behavior. 

GDScript is currently serialized as a resource, keeping the source code as it was whenever an object with a script was serialized (`var_to_bytes_with_objects` etc)
With this, that is no longer the case and the resource path is saved, so that, when it's deserialized, the script is instead loaded from the bundled resources or loader cache. Which can be good for a number of reasons, including not ending up with some stale code in a serialized object that you aren't aware of and being able to compare the type of the script/the objects script class properly.

This is backwards compatible though, so deserializing is no less dangerous than before.

Shouldn't this part of the change have it's own proposal or issue though?

**Comment by Cammymoop** [comment]
Also if this implementation is going in it looks like it could fix stuff like #65393 and #68666

**Comment by raulsntos** [comment]
The changes to script serialization are needed to fix `var_to_bytes_with_objects`/`bytes_to_var_with_objects` for Objects with C# scripts. Without these changes, deserializing Objects with C# scripts end up with an invalid C# script attached.

C# doesn't support embedded scripts, so they must be loaded from a path. IMO, serializing a script that was loaded from a path shouldn't lose its path. So I consider this a bug fix.

@Faless diff in https://github.com/godotengine/godot/pull/78219#issuecomment-1973095390 still fixes the bug for C# scripts, so I consider that also an acceptable solution.

**Comment by Delsin-Yu** [comment]
Any chance we can have this for 4.3, or what's the blocker on it?

**Comment by dalexeev** [comment]
> This is a pretty major change to script serialization behavior.

Without the change, binary deserialization of scripted objects and typed arrays is mostly broken at the moment. Especially in the case of typed arrays, where the same script is encoded several times, and we can end up with a situation where each element has a different type, incompatible with the type of the array itself.

I discovered this as a result of testing and did not even consider it as a compatibility break, just as a bug fix. As far as I remember, this was noted in the first comment and further in the discussion.

Also, the approach is used in text serialization, this change eliminates the inconsistency between them. See also #69248 for context.

> If we want to prevent this completely we should also change the deserialization part to always require a valid script path (right now, it can deserialize such scripts, but not serialize them).

I would prefer this option so as not to create inconsistency between scripts with and without paths.

> We should also add the `breaks compat` label since if anyone is relying on that behavior, their project will break upon update (they'll have to manually handle serialization of those scripts).

Done.

**Comment by dalexeev** [comment]
> > If we want to prevent this completely we should also change the deserialization part to always require a valid script path (right now, it can deserialize such scripts, but not serialize them).
> 
> I would prefer this option so as not to create inconsistency between scripts with and without paths.

Done.

```diff
@@ -687,7 +687,8 @@ Error decode_variant(Variant &r_variant, const uint8_t *p_buffer, int p_len, int
 							(*r_len) += used;
 						}
 
-						if (str == "script" && value.get_type() == Variant::STRING) {
+						if (str == "script") {
+							ERR_FAIL_COND_V_MSG(value.get_type() != Variant::STRING, ERR_INVALID_DATA, "Invalid value for \"script\" property, expected script path as String.");
 							String path = value;
 							ERR_FAIL_COND_V_MSG(path.is_empty() || !path.begins_with("res://") || !ResourceLoader::exists(path, "Script"), ERR_INVALID_DATA, "Invalid script path: '" + path + "'.");
 							Ref<Script> script = ResourceLoader::load(path, "Script");
```

**Review by Faless — APPROVED** [review]
Awesome work :trophy: !

**Comment by akien-mga** [comment]
Thanks!

**Comment by Saadies** [comment]
> Also if this implementation is going in it looks like it could fix stuff like #65393 and #68666

I've tried with the recent Master https://github.com/godotengine/godot/commit/d00734053f9cda8ade5e6c3afd86266e6df571c6

And unfortunately neither saving and loading resources with a class name, nor saving and loading nested Resources using ResourceSaver.FLAG_BUNDLE_RESOURCES is working. (#74918 and #65393)

[minimumProjektKalado.zip](https://github.com/godotengine/godot/files/14971444/minimumProjektKalado.zip)
