### PR TITLE
Fix duplicating node references of custom node type properties

### LINKED ISSUE #102793: Using `Node.duplicate` copies exported custom-class-typed node property pointing to a descendant Node as null
### Tested versions

- Reproducible in: 4.3-stable [77dcf97d8], 4.4-beta3
- Not reproducible in: 4.2.2-stable [15073afe3]

### System information

Windows 11

### Issue description

When you have a node that exports a property of a custom type, and you set that property to point to *any* descendant node, using `Node.duplicate` won't duplicate that property at all, and it will remain `null`.

If you move the descendant node to anywhere else outside the subtree of the tested node, the issue doesn't happen.

If you use the editor to duplicate, the issue doesn't happen.

I guess this is related to work that was made regarding node duplication in recent versions (4.3, 4.4), but the issues they fix don't describe this error, so I figured writing a new issue would be better.

### Steps to reproduce

In the MRP, there's a simple scene setup with 4 nodes (Test > CustomNode > Node > Node2).

CustomNode's `prop` points to Node2. The `Test` node tries to duplicate CustomNode, but `prop` remains null. The error "failed to duplicate" is output to the console.

Reparenting Node2 to Test in the editor makes the error go away.

### Minimal reproduction project (MRP)

[duplicate-issue-mrp.zip](https://github.com/user-attachments/files/18804518/duplicate-issue-mrp.zip)

### LINKED ISSUE #110665: Invalid Cast Exception when Duplicating a node with C# script that has [Export] for another node with C# script
### Tested versions

- Reproducible in 4.4.1.stable

### System information

Godot v4.4.1.stable.mono - Windows 11 (build 26100) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.8088) - AMD Ryzen 7 9800X3D 8-Core Processor (16 threads)

### Issue description

When duplicating a node with C# script that has an `[Export]` of another node with C# script, there is an issue with casting and `Invalid Cast Exception` is thrown.
It's very easy to reproduce and I can even show the whole code here.

First we have the root of the project that will duplicate a node.
```cs
public partial class Root : Node
{
    [Export] private NodeToDuplicate _nodeToDuplicate;

    public override void _Ready()
    {
        var e = _nodeToDuplicate.Duplicate();
    }
}
```

Then we have a node with a C# script (I only tested on Control, not sure about other nodes) that has an `[Export]` with another C# script Control.
```cs
public partial class NodeToDuplicate : Control
{
    [Export] private NotCastableChild _notCastableChild;
}
```

And the final node that has an issue being casted.
```cs
public partial class NotCastableChild : Control;
```

It's important that it's only an issue when accessing the node through `[Export]`. It's possible to find it with `GetNode` and cast it later without issues.

The exact error is this:
```
E 0:00:01:475   VariantUtils.generic.cs:388 @ T Godot.NativeInterop.VariantUtils.ConvertTo<T>(Godot.NativeInterop.godot_variant&): System.InvalidCastException: Unable to cast object of type 'Godot.Control' to type 'NotCastableChild'.
  <C# Error>    System.InvalidCastException
  <C# Source>   /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.generic.cs:388 @ T Godot.NativeInterop.VariantUtils.ConvertTo<T>(Godot.NativeInterop.godot_variant&)
  <Stack Trace> VariantUtils.generic.cs:388 @ T Godot.NativeInterop.VariantUtils.ConvertTo<T>(Godot.NativeInterop.godot_variant&)
                NodeToDuplicate_ScriptProperties.generated.cs:21 @ bool NodeToDuplicate.SetGodotClassPropertyValue(Godot.NativeInterop.godot_string_name&, Godot.NativeInterop.godot_variant&)
                CSharpInstanceBridge.cs:57 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Set(nint, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant*)
```

### Steps to reproduce

1. Run the scene `main.tscn`
2. See that there is an error in the Debugger

### Minimal reproduction project (MRP)

[invalid-cast-exception.zip](https://github.com/user-attachments/files/22412407/invalid-cast-exception.zip)

### PR DESCRIPTION
**Pull request by kevinlam508**
Fixes #102793
Fixes #110665

Issue was that script property of child nodes weren't assigned by the time a parent node's node properties were being processed. So `_duplicate_properties()` would grab the correct node, but `set()` would fail from type checking since the node didn't have a script on it.

#91329 caused the issue since it removed the property copy pass that would successfully do assignment since the first pass copied the scripts.

This fix ensures at least the script property is copied before trying to assign node properties. Couldn't only change the traversal order of `_duplicate_properties()` since that would cause nodes with references to ancestors to fail assignment instead.

### CODE REVIEW

File: scene/main/node.cpp [hunk 1]
```diff
@@ -3043,20 +3051,28 @@ void Node::_emit_editor_state_changed() {
 }
 #endif
 
+void Node::_duplicate_scripts(const Node *p_original, Node *p_copy) const {
+	const StringName &script_property_name = CoreStringName(script);
+	bool is_valid = false;
+	Variant scr = p_original->get(script_property_name, &is_valid);
+	if (is_valid) {
+		p_copy->set(script_property_name, scr);
```
Comment (AThousandShips) [inline scene/main/node.cpp]:
```suggestion
	bool is_valid = false;
	Variant scr = p_original->get(CoreStringName(script), &is_valid);
	if (is_valid) {
		p_copy->set(CoreStringName(script), scr);
```
Not necessary for just two uses

**Review by RandomShaper — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
