### PR TITLE
Fix json dump and print of circular structure

### LINKED ISSUE #48289: Silent crash with to_json(dictionary) if dictionary has point to itself
**Godot version:**

3.4.beta e554ecd691

**OS/device including version:**

Kubuntu 20.10

**Issue description:**

Silent crash with to_json(dictionary) if dictionary has point to itself without any error on console.

**Steps to reproduce:**
```gdscript
func _ready() -> void:
	var dic:Dictionary = {}
	dic.test = dic
	printt(to_json(dic))
```

**Minimal reproduction project:**

[Dictionary crash.zip](https://github.com/godotengine/godot/files/6397255/Dictionary.crash.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
This fixes #48289, also applies to 3.x (`core/variant/variant.cpp` → `core/variant.cpp`).

When the parameter of `JSON.print` contains circular structure, an error will now be printed and the dictionary / array will be stringified into `"{...}"` / `"[...]"` to help debugging while keeping the output valid JSON.

```gdscript
var d = {1: 1, 2: 2, 3: 3}
d[1] = d
# {1:{...}, 2:2, 3:3}
print(d)
# ERROR: _print_var: Converting circular structure to JSON.
#    At: core/io/json.cpp:103.
# {"1":"{...}","2":2,"3":3}
print(JSON.print(d))  # 3.2 to_json(d)
```

The `print` function treated any repeated element as circular structure even if they are not nested. This is also fixed:

```gdscript
var x = ['a', 'b', 'c']
var y = [1, 2, 3]
var z = [x, y, x, y]

# before: [[a, b, c], [1, 2, 3], [...], [...]]
# after:  [[a, b, c], [1, 2, 3], [a, b, c], [1, 2, 3]]
print(z)
```

### CODE REVIEW

File: core/io/json.cpp [hunk 1]
```diff
@@ -55,7 +55,7 @@ static String _make_indent(const String &p_indent, int p_size) {
 	return indent_text;
 }
 
-String JSON::_print_var(const Variant &p_var, const String &p_indent, int p_cur_indent, bool p_sort_keys) {
+String JSON::_print_var(const Variant &p_var, const String &p_indent, int p_cur_indent, bool p_sort_keys, Set<const void *> &p_markers) {
```
Comment (LightningAA) [inline core/io/json.cpp:58]: What's the point of having to pass in `p_markers`? Couldn't it be created by the class/function?

Comment (timothyqiu) [reply core/io/json.cpp:58]: `p_markers` can't be created by `_print_var()` because the function is recursive. It is created by the actual `print()` function which is the only caller of the recursive `_print_var()`.

`p_markers` is only useful during `print()`, so it does not make sense to make it a member of `JSON`. Making it a member variable would also introduce potential race condition if `JSON::print()` is called by multithreaded code.

`Variant::stringify()` requires passing a similar structure to track circular structure:
https://github.com/godotengine/godot/blob/364ea7f280a3f074795e542b16b1d0ec76cf6ce2/core/variant/variant.cpp#L1626

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
