### PR TITLE
[3.x] Fix Viewport interpolation mode

### LINKED ISSUE #91918: Performance between 3.5.3 and 3.6.b5 framerate/shader/material worse
### Tested versions

3.6.b5

### System information

Windows 10

### Issue description

I've been testing a project I've been working on in 3.5 for 2 years in 3.6 and there was a noticeably worse framerate/performance in 3.6:

3.5 always has a solid framerate on 165 on my laptop:
image

But trying in 3.6 it looks stuttery in comparison:
image

I am using a few shader materials, one of which has its transform matrix update on each frame, which is fine in 3.5 but there's definitely more draw calls in 3.6:

3.5:
image

3.6:
image

I'm not sure if this would affect the framerate to this degree, but it is a significant increase from 3.5. I tried making a barebones test movement project for example purposes, but the performance returned to its usual speed once most of the game was removed so I'm not sure how I can share an example of this without uploading my entire game.

### Steps to reproduce

Load a game that uses a few shader-materials from 3.5 into 3.6 and compare the draw calls.

### Minimal reproduction project (MRP)

N/A (I attempted to make one but it wasn't possible for this example).

### LINKED ISSUE #92150: [3.x] `ViewportContainer` unexpectedly turns off physics interpolation
### Tested versions

3.6 from beta 3 (2D physics interpolation)
Doesn't occur in 3.5 and prior to 2D physics interpolation

### System information

All

### Issue description

In a physics interpolated game, when using `ViewportContainer`, objects below the `ViewportContainer` are unexpectedly not physics interpolated.

This issue was isolated from #91918 (and found by @elvisish )

### Steps to reproduce

* Create `ViewportContainer`
* Create physics interpolated gameplay below the above node
* Switch on physics interpolation in project settings
* See no physics interpolation

### Minimal reproduction project (MRP)

Press return to toggle on / off the physics interpolation mode of the `ViewportContainer`.
[viewport_interpolation_bug.zip](https://github.com/godotengine/godot/files/15374150/viewport_interpolation_bug.zip)

## Discussion
Unsure whether to class this as a bug or documentation as yet, but probably something I can fix engine side to make more sensible.

The problem stems from 2D physics interpolation, because `Control` now defaults to `PHYSICS_INTERPOLATION_MODE_OFF`. This is because user interface elements typically are not desired to interpolate (they can still be interpolated but they must be explicitly set to e.g. `PHYSICS_INTERPOLATION_MODE_ON` or `PHYSICS_INTERPOLATION_MODE_INHERIT`).

In the particular case of `ViewportContainer` (and possibly other controls containing a viewport with an interpolated scene), this has the side effect of propagating the physics_interpolation flag to be `OFF` for the scene tree branch below the viewport.

There may be a simple fix to this (rather than documentation), such as defaulting `Viewport` itself to `PHYSICS_INTERPOLATION_MODE_ON` rather than `PHYSICS_INTERPOLATION_MODE_INHERIT`, thereby resetting physics interpolation to the default state below any viewport.

### PR DESCRIPTION
**Pull request by lawnjelly**
Viewport interpolation mode is a special case, which should be set to ON instead of INHERIT.

Fixes #92150
Fixes #91918

## Notes
* Controls defaulting to OFF is a trade off - it makes adding controls easy to a physics interpolated game, but users need to be aware that nodes below the control will usually inherit this OFF setting.
* Viewports are typically children of Controls, and previously would inherit OFF, which could be unexpected for physics interpolated games.
* The simplest and most sensible solution seems to be to reset the physics interpolation mode and consider the `Viewport` as a new root of each subscene.
* This is something that can eventually be added to the physics interpolation docs, along with other special cases. But it should now work in a more expected manner for most users.

### CODE REVIEW

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -3681,6 +3681,13 @@ Viewport::Viewport() {
 	local_input_handled = false;
 	handle_input_locally = true;
 	physics_last_id = 0; //ensures first time there will be a check
+
+	// Physics interpolation mode for viewports is a special case.
+	// Typically viewports will be housed within Controls,
+	// and Controls default to PHYSICS_INTERPOLATION_MODE_ON.
```
Comment (akien-mga) [inline scene/main/viewport.cpp:3687]:
```suggestion
	// and Controls default to PHYSICS_INTERPOLATION_MODE_OFF.
```

**Comment by akien-mga** [comment]
CC @rburing - I guess this might be relevant for 4.x too?

File: scene/main/viewport.cpp (hunk 1 above)
Comment (lawnjelly) [reply scene/main/viewport.cpp]: Oo good spot! :blush:

**Comment by lawnjelly** [comment]
> I guess this might be relevant for 4.x too?

Yes, this should be forward ported as it will affect 3D and 2D games using `Viewport`s.

**Review by akien-mga — APPROVED** [review]

**Comment by lawnjelly** [comment]
Thanks!

**Comment by oeleo1** [comment]
Wow! That's pretty major - si it turns out I was tricked to believe we were using FTI for 2D while most things are running in a ViewportContainer without it? Hmm... We did have to fix visual artefacts with `reset_physics_interpolation()` so we were definitely running FTI but I can't recall right now whether this was inside or outside that ViewportContainer. Something to test with a new 3.6 beta in a not so distant future hopefully :-)

Thanks!

**Comment by lawnjelly** [comment]
> Something to test with a new 3.6 beta in a not so distant future hopefully :-)

Yes we should have an RC soon as this is just bug fixing phase.

As I say in the docs, for anything physics interpolation related, you should be regularly switching your physics tick rate down to e.g. 10 tps so that things are super obvious, e.g. need for resets. You can't rely on noticing whether things are operating correctly by eye at 60tps.

**Comment by oeleo1** [comment]
> As I say in the docs, for anything physics interpolation related, you should be regularly switching your physics tick rate down to e.g. 10 tps so that things are super obvious, e.g. need for resets. You can't rely on noticing whether things are operating correctly by eye at 60tps.

I wish that was true. It is not. We can't operate the game at anything below 60tps. It is a real-time action game. This is due to an unimaginable set of factors for the Godot developers. They include plenty of physics interactions, barrier hits, penetration thresholds, increased gravities to prevent sporadic jumps on curved rigid bodies, etc., etc., etc. If we lower physics below 60 fps, say 20fps, nothing moves as expected. At 30 fps - barely acceptable byt clearly unplayable, 40 and 50 - almost playable, but really regularily irritating. Whatever cool things the docs say, belive it or not, people apply to them a x16 Anisotropic filter right away, according to their own project. :-) Long live the next Beta!

**Comment by lawnjelly** [comment]
Yup sure, you will tune a game to a particular physics tick rate, and you will definitely start getting crazy behaviour below 20 tps with physics engine :grinning: , but it only needs to run enough temporarily to help identify interpolation problems.

But sure I do take your point that in some games the logic gets mucked up too much to test easily at very low tick rates. It is _usually_ a good technique that will help troubleshoot.

Thinking about it, It's actually likely very possible to just jerry rig the OS timer to test this kind of thing without disrupting gameplay (although certain things like audio would be difficult to timeshift).

**Comment by oeleo1** [comment]
> Thinking about it, It's actually likely very possible to just jerry rig the OS timer to test this kind of thing without disrupting gameplay (although certain things like audio would be difficult to timeshift).

Yes. `Engine.set_time_scale()` is the way to go. Audio put aside, values like 0.1 allow for testing the sequences of interest and FTI is doing its smoothing job very well without disturbing physics. Actually this is much better than lowering artificially the physics FPS setting.

**Comment by lawnjelly** [comment]
> Yes. Engine.set_time_scale() is the way to go. Audio put aside, values like 0.1 allow for testing the sequences of interest and FTI is doing its smoothing job very well without disturbing physics. Actually this is much better than lowering artificially the physics FPS setting.

I'll try and test this out and add to the docs, it could be a better suggestion than lowering the tick rate (in some situations at least).
