### PR TITLE
Set the unlit / unshaded extension when importing / exporting GLTF

### LINKED ISSUE #74268: Unlit (unshaded) material property is ignored in glTF files
### Godot version

4.0

### System information

windows 10

### Issue description

Gltf files that have KHR_materials_unlit (unshaded mode), won't be set to Unshaded in Godot.

### Steps to reproduce

The example project contains a gltf model that is suppose to be unlit/unshaded. However, Godot imports it incorrectly with its Shading mode set to per-pixel instead.

### Minimal reproduction project

[gltfUnshadedBug.zip](https://github.com/godotengine/godot/files/10877513/gltfUnshadedBug.zip)

### PR DESCRIPTION
**Pull request by hakro**
Fixes #74268

### CODE REVIEW

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -3748,6 +3748,13 @@ Error GLTFDocument::_serialize_materials(Ref<GLTFState> p_state) {
 			d["alphaMode"] = "BLEND";
 		}
 
+		Dictionary extensions;
+		if (base_material->get_shading_mode() == BaseMaterial3D::SHADING_MODE_UNSHADED) {
+			Dictionary mat_unlit;
```
Comment (clayjohn) [inline modules/gltf/gltf_document.cpp:3753]: I wonder if this could just be an empty variant instead as it is never checked. Dictionary initializes a few things that I don't think you would get with another variant

Comment (hakro) [reply modules/gltf/gltf_document.cpp:3753]: Some thing like this you mean ?
`extensions["KHR_materials_unlit"] = Variant();`

It didn't work. It yields a json file that looks like this : 


But the [spec](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_unlit/README.md) defines it as an empty {object}, not a null : 



And when importing the gltf file with the variant into blender, it fails, which is expected.

Comment (clayjohn) [reply modules/gltf/gltf_document.cpp:3753]: Thanks for checking and for referring me to the spec. Indeed it looks like the spec requires an empty dictionary. In hindsight that makes sense as they may make additions to the extension in the future (unlikely for this particular extension, but still).

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Comment by lyuma** [comment]
`KHR_materials_unlit` must also be added into the document's top-level `extensionsUsed` dictionary?

I'm asking some gltf nerds just to double-check if this is true, but I'm pretty sure.

**Comment by hakro** [comment]
> `KHR_materials_unlit` must also be added into the document's top-level `extensionsUsed` dictionary?
> 
> I'm asking some gltf nerds just to double-check if this is true, but I'm pretty sure.

Good catch, thank you.
I missed it, since the import in blender worked fine.
But you're right, it's better to have it as it's documented here: 
https://github.com/KhronosGroup/glTF/blob/main/extensions/README.md#about-gltf-extensions

I checked how Blender also does the export, and the dictionnary is there as well.

Now the export from Godot looks like this : 



Cheers !

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
