### PR TITLE
GDScript: Fix lambda hot reloading

### LINKED ISSUE #62769: Lambda references are corrupted when script is modified while debugging
### Godot version

v4.0.alpha.custom_build [83ad1231a]

### System information

Arch on 5.18.9-arch1-1

### Issue description

Code:
```gdscript
extends Node

func this_is_never_referenced1() -> void:
	print("This is never referenced1")

func this_is_never_referenced2() -> void:
	print("This is never referenced2")

func this_is_never_referenced3() -> void:
	print("This is never referenced3")

func this_is_never_referenced4() -> void:
	print("This is never referenced4")

var hello := func() -> void:
	print("Hi")

# This works fine:
#var hello := hellofunc
#func hellofunc():
#	print("Hi")

func _process(_delta: float) -> void:
	hello.call()

```

Output:
```
Hi
Hi
Hi
…
--- Script modified now ---
This is never referenced2
This is never referenced2
This is never referenced2
…
```

Note for testers: This is not an issue with GDScript member variables, since I discovered (and can reproduce) this issue with `Performance.add_custom_monitor`.

### Steps to reproduce

1) Open MRP in editor
2) Run project
3) Modify script (e.g. add a single `#` to an empty line)

### Minimal reproduction project

[test4.zip](https://github.com/godotengine/godot/files/9052581/test4.zip)

### PR DESCRIPTION
**Pull request by rune-scape**
fixes https://github.com/godotengine/godot/issues/62769

swaps out the function pointers used in LambdaCallables when a script is reloaded
if it cant find a good replacement it invalidates the callable, so no more 'Bad Address Index' and crashes, it tells you its called an invalid lambda
the logic it uses to swap lambdas is very simple right now, swapping only if the argument count vaguely matches, and no lambdas were added or removed, evaluated for each function the lambda was in
also should be safe across threads, because lambdas can be created on any thread. i took care to make sure it wouldnt slow lambda creation down

it may be a good idea to add some more logic to how old lamdas are matched to new ones, the data is there but i dont know what would be intuitive, what would break logic, im all ears for heuristics

**MRP:**
[81628.zip](https://github.com/godotengine/godot/files/12830903/81628.zip)

_Production edit: added the MRP_

### CODE REVIEW

**Comment by rune-scape** [comment]
umm, the failed check seems like an unrelated crash..

**Comment by ryanabx** [comment]
> umm, the failed check seems like an unrelated crash..

You're absolutely right

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -2984,6 +2984,120 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+	}
+	if (p_script->static_initializer) {
+		info.static_initializer_info = _get_function_lambda_replacement_info(p_script->static_initializer);
+	}
+
+	for (const KeyValue<StringName, GDScriptFunction *> &E : p_script->member_functions) {
+		info.member_function_infos.insert(E.key, _get_function_lambda_replacement_info(E.value));
+	}
+
+	for (auto &KV : p_script->get_subclasses()) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3033]:
```suggestion
	for (KeyValue<StringName, Ref<GDScript>> &KV : p_script->get_subclasses()) {
```
`auto` is forbidden

File: modules/gdscript/gdscript_compiler.cpp [hunk 2]
```diff
@@ -2984,6 +2984,120 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+		_get_function_ptr_replacements(r_replacements, old_info, new_info);
+	}
+}
+
+void GDScriptCompiler::_get_function_ptr_replacements(HashMap<GDScriptFunction *, GDScriptFunction *> &r_replacements, const ScriptLambdaInfo &p_old_info, const ScriptLambdaInfo *p_new_info) {
+	_get_function_ptr_replacements(r_replacements, p_old_info.implicit_initializer_info, p_new_info != nullptr ? &p_new_info->implicit_initializer_info : nullptr);
+	_get_function_ptr_replacements(r_replacements, p_old_info.implicit_ready_info, p_new_info != nullptr ? &p_new_info->implicit_ready_info : nullptr);
+	_get_function_ptr_replacements(r_replacements, p_old_info.static_initializer_info, p_new_info != nullptr ? &p_new_info->static_initializer_info : nullptr);
+
+	for (auto &old_KV : p_old_info.member_function_infos) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3081]:
```suggestion
	for (KeyValue<StringName, Vector<FunctionLambdaInfo>> &old_KV : p_old_info.member_function_infos) {
```

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (akien-mga) [reply modules/gdscript/gdscript_compiler.cpp:3033]: Can probably be `const KeyValue<...> &`?

File: modules/gdscript/gdscript.h [hunk 3]
```diff
@@ -88,6 +88,8 @@ class GDScript : public Script {
 	friend class GDScriptDocGen;
 	friend class GDScriptLanguage;
 	friend struct GDScriptUtilityFunctionsDefinitions;
+	friend class GDScriptLambdaCallable;
+	friend class GDScriptLambdaSelfCallable;
```
Comment (dalexeev) [inline modules/gdscript/gdscript.h:92]:
```suggestion
	friend class GDScriptLanguage;
	friend class GDScriptLambdaCallable;
	friend class GDScriptLambdaSelfCallable;
	friend struct GDScriptUtilityFunctionsDefinitions;
```

File: modules/gdscript/gdscript_lambda_callable.cpp [hunk 4]
```diff
@@ -44,11 +44,18 @@ bool GDScriptLambdaCallable::compare_less(const CallableCustom *p_a, const Calla
...
+	return CallableCustom::is_valid() && function != nullptr;
+}
+
 uint32_t GDScriptLambdaCallable::hash() const {
 	return h;
 }
 
 String GDScriptLambdaCallable::get_as_text() const {
+	if (function == nullptr) {
+		return "(invalid lambda)";
```
Comment (dalexeev) [inline modules/gdscript/gdscript_lambda_callable.cpp:57]:
```suggestion
		return "<invalid lambda>";
```

File: modules/gdscript/gdscript_lambda_callable.cpp [hunk 5]
```diff
@@ -109,11 +130,18 @@ bool GDScriptLambdaSelfCallable::compare_less(const CallableCustom *p_a, const C
...
+	return CallableCustom::is_valid() && function != nullptr;
+}
+
 uint32_t GDScriptLambdaSelfCallable::hash() const {
 	return h;
 }
 
 String GDScriptLambdaSelfCallable::get_as_text() const {
+	if (function == nullptr) {
+		return "(invalid lambda)";
```
Comment (dalexeev) [inline modules/gdscript/gdscript_lambda_callable.cpp:143]:
```suggestion
		return "<invalid lambda>";
```

**Review by dalexeev — COMMENTED** [review]
I'm not qualified enough to review this, I just noticed a couple of minor flaws.

If hot reloading is only available in the editor, does it make sense to wrap some code in `TOOLS_ENABLED` or `DEBUG_ENABLED`?

**Comment by rune-scape** [comment]
> If hot reloading is only available in the editor, does it make sense to wrap some code in `TOOLS_ENABLED` or `DEBUG_ENABLED`?

@dalexeev `script.reload(true)` is hot reloading, i believe. and thats available at runtime with tools disabled
placeholders, docs, and tests are whats disabled in gdscript when the editor is
except for old_static_variables and member_default_values? it seems inconsistent, but hot-reloading in concept is allowed without tools,, and this is a memory safety issue,, so i think a big chunk of it would need to stay, and it should probably be enabled wherever member function hot-reloading is enabled, which is all the time with or without tools right now 

tbh i dont know why you would pass `false` to reload for that matter,,, it seems like that would just cause weird runtime behavior. is it even used anywhere?

**Comment by rune-scape** [comment]
should i click the resolve conversation button now that ive pushed the corrections?? i do not remember

**Comment by YuriSizov** [comment]
> should i click the resolve conversation button now that ive pushed the corrections?? i do not remember

If you've addressed the comment and there is no open matters to discuss, then feel free to click resolve :)

**Comment by rune-scape** [comment]
@AThousandShips id appreciate another review on the thread safety, i changed some things in gdscript.cpp, and i remember your affinity on the subject

File: modules/gdscript/gdscript.cpp [hunk 6]
```diff
@@ -1372,6 +1372,35 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
+	UpdatableFuncPtrElement result{ func_ptrs_to_update_thread_local.ptrs.push_back(p_func_ptr_ptr), &func_ptrs_to_update_thread_local.mutex };
+
+	if (unlikely(!func_ptrs_to_update_thread_local.initialized)) {
+		func_ptrs_to_update_thread_local.initialized = true;
+		// Unlock thread local mutex before main one to prevent a deadlock
+		func_ptrs_to_update_thread_local.mutex.unlock();
+
+		func_ptrs_to_update_mutex.lock();
+		func_ptrs_to_update.push_back(&func_ptrs_to_update_thread_local);
+		func_ptrs_to_update_mutex.unlock();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:1388]:
```suggestion
		MutexLock lock(func_ptrs_to_update_mutex);
		func_ptrs_to_update.push_back(&func_ptrs_to_update_thread_local);
```
I'd suggest using `MutexLock` here and in places where the locking is scope based, it ensures some degrees of safety and avoids forgetting to unlock it.

File: modules/gdscript/gdscript.cpp [hunk 7]
```diff
@@ -1372,6 +1372,35 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
+
+	return result;
+}
+
+void GDScript::_remove_func_ptr_to_update(UpdatableFuncPtrElement p_func_ptr_element) {
+	ERR_FAIL_NULL(p_func_ptr_element.element);
+	ERR_FAIL_NULL(p_func_ptr_element.mutex);
+	p_func_ptr_element.mutex->lock();
+	p_func_ptr_element.element->erase();
+	p_func_ptr_element.mutex->unlock();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:1401]:
```suggestion
	MutexLock lock(*p_func_ptr_element.mutex);
	p_func_ptr_element.element->erase();
```

File: modules/gdscript/gdscript.cpp [hunk 8]
```diff
@@ -1389,6 +1418,16 @@ void GDScript::clear(ClearData *p_clear_data) {
...
 
+	func_ptrs_to_update_mutex.lock();
+	for (UpdatableFuncPtr *updatable : func_ptrs_to_update) {
+		updatable->mutex.lock();
+		for (GDScriptFunction **func_ptr_ptr : updatable->ptrs) {
+			*func_ptr_ptr = nullptr;
+		}
+		updatable->mutex.unlock();
+	}
+	func_ptrs_to_update_mutex.unlock();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:1429]:
```suggestion
	MutexLock outer_lock(func_ptrs_to_update_mutex);
	for (UpdatableFuncPtr *updatable : func_ptrs_to_update) {
		MutexLock inner_lock(updatable->mutex);
		for (GDScriptFunction **func_ptr_ptr : updatable->ptrs) {
			*func_ptr_ptr = nullptr;
		}
	}
```

File: modules/gdscript/gdscript_compiler.cpp [hunk 9]
```diff
@@ -3009,6 +3139,27 @@ Error GDScriptCompiler::compile(const GDScriptParser *p_parser, GDScript *p_scri
...
+			if (replacement != nullptr) {
+				*func_ptr_ptr = *replacement;
+			} else {
+				// Probably a lambda from another reload, ignore.
+				*func_ptr_ptr = nullptr;
+			}
+		}
+		updatable->mutex.unlock();
+	}
+	main_script->func_ptrs_to_update_mutex.unlock();
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3161]:
```suggestion
	MutexLock outer_lock(main_script->func_ptrs_to_update_mutex);
	for (GDScript::UpdatableFuncPtr *updatable : main_script->func_ptrs_to_update) {
		MutexLock inner_lock(updatable->mutex);
		for (GDScriptFunction **func_ptr_ptr : updatable->ptrs) {
			GDScriptFunction **replacement = func_ptr_replacements.getptr(*func_ptr_ptr);
			if (replacement != nullptr) {
				*func_ptr_ptr = *replacement;
			} else {
				// Probably a lambda from another reload, ignore.
				*func_ptr_ptr = nullptr;
			}
		}
	}
```

**Review by AThousandShips — COMMENTED** [review]
Otherwise I don't see any issues with the threading, but I'm a bit rusty with the specifics so might be missing something, so someone else should take a look at that as well

**Comment by adamscott** [comment]
Thanks @AThousandShips, I integrated your suggestions into the PR as @rune-scape is unavailable for the moment.

**Comment by adamscott** [comment]
I created a MRP to make sure that it works. And it works flawlessly. 
[81628.zip](https://github.com/godotengine/godot/files/12830903/81628.zip)

Just run the project, then change the inner value of the lambdas. It just works!

**Review by adamscott — APPROVED** [review]
It's fine for me. It works and the code is clean. I'm no hot-reloading-whiz, but I'm OK with merging this for 4.2.

**Review by AThousandShips — APPROVED** [review]

**Comment by rune-scape** [comment]
while using it yesterday i just found a small bug related to thread safety checks. pushing that now before it gets merged

File: modules/gdscript/gdscript_compiler.cpp [hunk 10]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+	info.index = p_index;
+	info.depth = p_depth;
+	//info.code_hash = hash_murmur3_buffer(reinterpret_cast<const int *>(p_func->code.ptr()), p_func->code.size() * sizeof(int));
+	//info.code_size = p_func->code.size();
+	info.capture_count = 0;
+	info.use_self = false;
+	info.arg_count = p_func->_argument_count;
+	info.default_arg_count = p_func->_default_arg_count;
+	//info.argument_types = p_func->argument_types;
+	//info.return_type = p_func->return_type;
```
Comment (vnen) [inline modules/gdscript/gdscript_compiler.cpp:3061]: Any reason to keep these commented lines? If they're not needed they can just be omitted.

File: modules/gdscript/gdscript_compiler.cpp [hunk 11]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+	}
+
+	if (p_new_info->capture_count != p_old_info.capture_count || p_new_info->use_self != p_old_info.use_self) {
+		return false;
+	}
+
+	int old_requred_arg_count = p_old_info.arg_count - p_old_info.default_arg_count;
+	int new_requred_arg_count = p_new_info->arg_count - p_new_info->default_arg_count;
+	if (new_requred_arg_count > old_requred_arg_count || p_new_info->arg_count < old_requred_arg_count) {
+		return false;
```
Comment (vnen) [inline modules/gdscript/gdscript_compiler.cpp:3118]: Typo here: `requred` -> `required`

**Review by vnen — COMMENTED** [review]
For a glance it looks good. It'll take some time if I dive deep on the logic, so I'll trust rune on this. It's already a big improvement over the current status even if some bug crops up.

File: modules/gdscript/gdscript_compiler.cpp [hunk 12]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+		info.capture_count = extra_info->capture_count;
+		info.use_self = extra_info->use_self;
+	}
+
+	return info;
+}
+
+Vector<GDScriptCompiler::FunctionLambdaInfo> GDScriptCompiler::_get_function_lambda_replacement_info(GDScriptFunction *p_func, int p_depth, GDScriptFunction *p_parent_func) {
+	Vector<FunctionLambdaInfo> result;
+	// Only scrape the lambdas inside p_func
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3075]:
```suggestion
	// Only scrape the lambdas inside p_func.
```

File: modules/gdscript/gdscript_compiler.cpp [hunk 13]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+	r_replacements.insert(p_old_info.function, p_new_info != nullptr ? p_new_info->function : nullptr);
+	_get_function_ptr_replacements(r_replacements, p_old_info.sublambdas, p_new_info != nullptr ? &p_new_info->sublambdas : nullptr);
+}
+
+void GDScriptCompiler::_get_function_ptr_replacements(HashMap<GDScriptFunction *, GDScriptFunction *> &r_replacements, const Vector<FunctionLambdaInfo> &p_old_infos, const Vector<FunctionLambdaInfo> *p_new_infos) {
+	for (int i = 0; i < p_old_infos.size(); ++i) {
+		const FunctionLambdaInfo &old_info = p_old_infos[i];
+		const FunctionLambdaInfo *new_info = nullptr;
+		if (p_new_infos != nullptr && p_new_infos->size() == p_old_infos.size()) {
+			// for now only attempt if the size is the same
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3139]:
```suggestion
			// For now only attempt if the size is the same.
```

File: modules/gdscript/gdscript_compiler.cpp [hunk 14]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+	_get_function_ptr_replacements(r_replacements, p_old_info.static_initializer_info, p_new_info != nullptr ? &p_new_info->static_initializer_info : nullptr);
+
+	for (const KeyValue<StringName, Vector<FunctionLambdaInfo>> &old_KV : p_old_info.member_function_infos) {
+		_get_function_ptr_replacements(r_replacements, old_KV.value, p_new_info != nullptr ? p_new_info->member_function_infos.getptr(old_KV.key) : nullptr);
+	}
+	for (int i = 0; i < p_old_info.other_function_infos.size(); ++i) {
+		const FunctionLambdaInfo &old_other_info = p_old_info.other_function_infos[i];
+		const FunctionLambdaInfo *new_other_info = nullptr;
+		if (p_new_info != nullptr && p_new_info->other_function_infos.size() == p_old_info.other_function_infos.size()) {
+			// for now only attempt if the size is the same
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3158]:
```suggestion
			// For now only attempt if the size is the same.
```

File: modules/gdscript/gdscript_compiler.cpp [hunk 15]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+			new_other_info = &p_new_info->other_function_infos[i];
+		}
+		// needs to be called on all old lambdas, even if there's no replacement
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3161]:
```suggestion
		// Needs to be called on all old lambdas, even if there's no replacement.
```

File: modules/gdscript/gdscript_compiler.cpp [hunk 16]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+		_get_function_ptr_replacements(r_replacements, old_other_info, new_other_info);
+	}
+	for (const KeyValue<StringName, ScriptLambdaInfo> &old_KV : p_old_info.subclass_info) {
+		const ScriptLambdaInfo &old_subinfo = old_KV.value;
+		const ScriptLambdaInfo *new_subinfo = p_new_info != nullptr ? p_new_info->subclass_info.getptr(old_KV.key) : nullptr;
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3166]:
```suggestion
	for (const KeyValue<StringName, ScriptLambdaInfo> &old_kv : p_old_info.subclass_info) {
		const ScriptLambdaInfo &old_subinfo = old_kv.value;
		const ScriptLambdaInfo *new_subinfo = p_new_info != nullptr ? p_new_info->subclass_info.getptr(old_kv.key) : nullptr;
```
Avoid mixing `snake_case`, if it's just a single element like `KV` it's okay but here I'd say this is neater

File: modules/gdscript/gdscript_compiler.cpp [hunk 17]
```diff
@@ -3040,6 +3042,132 @@ void GDScriptCompiler::make_scripts(GDScript *p_script, const GDScriptParser::Cl
...
+	}
+}
+
+void GDScriptCompiler::_get_function_ptr_replacements(HashMap<GDScriptFunction *, GDScriptFunction *> &r_replacements, const ScriptLambdaInfo &p_old_info, const ScriptLambdaInfo *p_new_info) {
+	_get_function_ptr_replacements(r_replacements, p_old_info.implicit_initializer_info, p_new_info != nullptr ? &p_new_info->implicit_initializer_info : nullptr);
+	_get_function_ptr_replacements(r_replacements, p_old_info.implicit_ready_info, p_new_info != nullptr ? &p_new_info->implicit_ready_info : nullptr);
+	_get_function_ptr_replacements(r_replacements, p_old_info.static_initializer_info, p_new_info != nullptr ? &p_new_info->static_initializer_info : nullptr);
+
+	for (const KeyValue<StringName, Vector<FunctionLambdaInfo>> &old_KV : p_old_info.member_function_infos) {
+		_get_function_ptr_replacements(r_replacements, old_KV.value, p_new_info != nullptr ? p_new_info->member_function_infos.getptr(old_KV.key) : nullptr);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript_compiler.cpp:3152]:
```suggestion
	for (const KeyValue<StringName, Vector<FunctionLambdaInfo>> &old_kv : p_old_info.member_function_infos) {
		_get_function_ptr_replacements(r_replacements, old_kv.value, p_new_info != nullptr ? p_new_info->member_function_infos.getptr(old_kv.key) : nullptr);
```

File: modules/gdscript/gdscript.h [hunk 18]
```diff
@@ -108,6 +110,30 @@ class GDScript : public Script {
...
+	struct UpdatableFuncPtrElement {
+		List<GDScriptFunction **>::Element *element = nullptr;
+		Mutex *mutex = nullptr;
+	};
+	static thread_local UpdatableFuncPtr func_ptrs_to_update_thread_local;
+	List<UpdatableFuncPtr *> func_ptrs_to_update;
+	Mutex func_ptrs_to_update_mutex;
+
+	UpdatableFuncPtrElement _add_func_ptr_to_update(GDScriptFunction **p_func_ptr_ptr);
+	static void _remove_func_ptr_to_update(UpdatableFuncPtrElement p_func_ptr_element);
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.h:135]:
```suggestion
	static void _remove_func_ptr_to_update(const UpdatableFuncPtrElement &p_func_ptr_element);
```
Avoid copy here

File: modules/gdscript/gdscript.cpp [hunk 19]
```diff
@@ -1379,6 +1379,36 @@ String GDScript::debug_get_script_name(const Ref<Script> &p_script) {
...
+		func_ptrs_to_update_thread_local.initialized = true;
+	}
+
+	MutexLock lock(func_ptrs_to_update_mutex);
+	func_ptrs_to_update.push_back(&func_ptrs_to_update_thread_local);
+
+	return result;
+}
+
+void GDScript::_remove_func_ptr_to_update(UpdatableFuncPtrElement p_func_ptr_element) {
```
Comment (AThousandShips) [inline modules/gdscript/gdscript.cpp:1405]:
```suggestion
void GDScript::_remove_func_ptr_to_update(const UpdatableFuncPtrElement &p_func_ptr_element) {
```

**Review by vnen — APPROVED** [review]
Looks good. It's a huge improvement over the current status.

**Comment by akien-mga** [comment]
Thanks! Amazing work :tada:
