### PR TITLE
Fix potential crash when checking unsaved history

### LINKED ISSUE #106459: Clicking "New inherited" on an imported GLTF mesh crashes the editor
### Tested versions

- Reproducible in Godot v4.5.dev (5e27318b6)

### System information

Godot v4.5.dev (5e27318b6) - macOS Sequoia (15.4.1) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M3 Pro (Apple9) - Apple M3 Pro (12 threads)

### Issue description

Attempting to click "New inherited scene" on an imported GLTF mesh after clicking "Open in Editor" in the scene hierarchy crashes the editor with the following stack trace:
```
Engine version: Godot Engine v4.5.dev.custom_build (5e27318b6c81c7eeef462737e6259d78841757e6)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x000000018371b624 _sigtramp + 56
[2] EditorUndoRedoManager::is_history_unsaved(int) (in godot.macos.editor.arm64) + 28
[3] EditorSceneTabs::_update_tab_titles() (in godot.macos.editor.arm64) + 1216
[4] EditorSceneTabs::update_scene_tabs() (in godot.macos.editor.arm64) + 1248
[5] EditorNode::load_scene(String const&, bool, bool, bool, bool) (in godot.macos.editor.arm64) + 5392
[6] SceneExporterGLTFPlugin::SceneExporterGLTFPlugin()
[7] Object::emit_signalp(StringName const&, Variant const**, int) (in godot.macos.editor.arm64) + 928
[8] AcceptDialog::_custom_action(String const&) (in godot.macos.editor.arm64) + 180
[9] SceneExporterGLTFPlugin::SceneExporterGLTFPlugin()
[10] CallableCustomBind::call(Variant const**, int, Variant&, Callable::CallError&) const (in godot.macos.editor.arm64) + 404
[11] Object::emit_signalp(StringName const&, Variant const**, int) (in godot.macos.editor.arm64) + 928
[12] BaseButton::_pressed() (in godot.macos.editor.arm64) + 272
[13] BaseButton::on_action_event(Ref<InputEvent>) (in godot.macos.editor.arm64) + 272
[14] BaseButton::gui_input(Ref<InputEvent> const&) (in godot.macos.editor.arm64) + 256
[15] Control::_call_gui_input(Ref<InputEvent> const&) (in godot.macos.editor.arm64) + 732
[16] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (in godot.macos.editor.arm64) + 512
[17] Viewport::_gui_input_event(Ref<InputEvent>) (in godot.macos.editor.arm64) + 2024
[18] Viewport::push_input(Ref<InputEvent> const&, bool) (in godot.macos.editor.arm64) + 796
[19] Window::_window_input(Ref<InputEvent> const&) (in godot.macos.editor.arm64) + 340
[20] GridMapEditorPlugin::make_visible(bool)
[21] DisplayServerMacOS::_dispatch_input_event(Ref<InputEvent> const&)
[22] DisplayServerMacOS::_dispatch_input_event(Ref<InputEvent> const&) (in godot.macos.editor.arm64) + 464
[23] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (in godot.macos.editor.arm64) + 4352
[24] Input::flush_buffered_events() (in godot.macos.editor.arm64) + 132
[25] DisplayServerMacOS::_process_events(bool) (in godot.macos.editor.arm64) + 740
[26] OS_MacOS_NSApp::start_main()
[27] 27  CoreFoundation                      0x00000001837cc1a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
[28] 28  CoreFoundation                      0x00000001837cc090 __CFRunLoopDoObservers + 536
[29] 29  CoreFoundation                      0x00000001837cb7a0 __CFRunLoopRun + 944
[30] 30  CoreFoundation                      0x00000001837cad68 CFRunLoopRunSpecific + 572
[31] 31  HIToolbox                           0x000000018ef7e27c RunCurrentEventLoopInMode + 324
[32] 32  HIToolbox                           0x000000018ef814e8 ReceiveNextEventCommon + 676
[33] 33  HIToolbox                           0x000000018f10c484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
[34] 34  AppKit                              0x000000018741dab4 _DPSNextEvent + 684
[35] 35  AppKit                              0x0000000187dbc314 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
[36] 36  AppKit                              0x0000000187410c64 -[NSApplication run] + 480
[37] main (in godot.macos.editor.arm64) + 696
[38] 38  dyld                                0x0000000183342b4c start + 6000
-- END OF C++ BACKTRACE --
================================================================
```

This may or may not be caused by #106121 

### Steps to reproduce

- Open the attached MRP
- In the scene tree pane on the "weird_tower" node, press "Open in Editor"
- In the popup select "New inherited" 

### Minimal reproduction project (MRP)

[inherited_mrp_2025-05-15_21-29-49.zip](https://github.com/user-attachments/files/20233543/inherited_mrp_2025-05-15_21-29-49.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
#106121 added a code that iterates a list based on external index. It's looks super unsafe, but nothing should go wrong if the undo stack is consistent with version, no?

Well :D
```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.5.dev.custom_build (428a762e9866afc41e9ba7fa334751142a81b432)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] EditorUndoRedoManager::is_history_unsaved (C:\godot_source\editor\editor_undo_redo_manager.cpp:398)
[1] EditorUndoRedoManager::is_history_unsaved (C:\godot_source\editor\editor_undo_redo_manager.cpp:398)
[2] EditorNode::_update_unsaved_cache (C:\godot_source\editor\editor_node.cpp:358)
[3] call_with_variant_args_helper<EditorNode> (C:\godot_source\core\variant\binder_common.h:228)
[4] call_with_variant_args<EditorNode> (C:\godot_source\core\variant\binder_common.h:338)
[5] CallableCustomMethodPointer<EditorNode,void>::call (C:\godot_source\core\object\callable_method_pointer.h:107)
[6] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[7] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1288)
[8] Object::emit_signal<> (C:\godot_source\core\object\object.h:930)
[9] EditorUndoRedoManager::commit_action (C:\godot_source\editor\editor_undo_redo_manager.cpp:287)
[10] ThemeTypeEditor::_theme_type_rename_dialog_confirmed (C:\godot_source\editor\plugins\theme_editor_plugin.cpp:2909)
[11] call_with_variant_args_helper<ThemeTypeEditor> (C:\godot_source\core\variant\binder_common.h:228)
[12] call_with_variant_args<ThemeTypeEditor> (C:\godot_source\core\variant\binder_common.h:338)
[13] CallableCustomMethodPointer<ThemeTypeEditor,void>::call (C:\godot_source\core\object\callable_method_pointer.h:107)
[14] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[15] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1288)
[16] Node::emit_signalp (C:\godot_source\scene\main\node.cpp:4292)
[17] Object::emit_signal<> (C:\godot_source\core\object\object.h:930)
[18] AcceptDialog::_ok_pressed (C:\godot_source\scene\gui\dialogs.cpp:141)
[19] AcceptDialog::_text_submitted (C:\godot_source\scene\gui\dialogs.cpp:127)
[20] call_with_variant_args_helper<AcceptDialog,String const &,0> (C:\godot_source\core\variant\binder_common.h:223)
[21] call_with_variant_args<AcceptDialog,String const &> (C:\godot_source\core\variant\binder_common.h:338)
[22] CallableCustomMethodPointer<AcceptDialog,void,String const &>::call (C:\godot_source\core\object\callable_method_pointer.h:107)
[23] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[24] Object::emit_signalp (C:\godot_source\core\object\object.cpp:1288)
[25] Node::emit_signalp (C:\godot_source\scene\main\node.cpp:4292)
[26] Object::emit_signal<String> (C:\godot_source\core\object\object.h:930)
[27] LineEdit::gui_input (C:\godot_source\scene\gui\line_edit.cpp:876)
[28] Control::_call_gui_input (C:\godot_source\scene\gui\control.cpp:1871)
[29] Viewport::_gui_input_event (C:\godot_source\scene\main\viewport.cpp:2274)
[30] Viewport::push_input (C:\godot_source\scene\main\viewport.cpp:3427)
[31] Window::_window_input (C:\godot_source\scene\main\window.cpp:1839)
[32] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\godot_source\core\variant\binder_common.h:223)
[33] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\godot_source\core\variant\binder_common.h:338)
[34] CallableCustomMethodPointer<Window,void,Ref<InputEvent> const &>::call (C:\godot_source\core\object\callable_method_pointer.h:107)
[35] Callable::callp (C:\godot_source\core\variant\callable.cpp:58)
[36] Callable::call<Ref<InputEvent> > (C:\godot_source\core\variant\variant.h:951)
[37] DisplayServerWindows::_dispatch_input_event (C:\godot_source\platform\windows\display_server_windows.cpp:4414)
[38] DisplayServerWindows::_dispatch_input_events (C:\godot_source\platform\windows\display_server_windows.cpp:4385)
[39] Input::_parse_input_event_impl (C:\godot_source\core\input\input.cpp:903)
[40] Input::flush_buffered_events (C:\godot_source\core\input\input.cpp:1184)
[41] DisplayServerWindows::process_events (C:\godot_source\platform\windows\display_server_windows.cpp:3798)
[42] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:2272)
[43] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:97)
[44] _main (C:\godot_source\platform\windows\godot_windows.cpp:122)
[45] main (C:\godot_source\platform\windows\godot_windows.cpp:136)
[46] WinMain (C:\godot_source\platform\windows\godot_windows.cpp:150)
[47] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[48] <couldn't map PC to fn name>
-- END OF C++ BACKTRACE --
```
I don't know how to reproduce it yet (I tried repeating the same thing I did with no result), so I though for now there should be a safeguard at least.

Fixes #106459

### CODE REVIEW

**Comment by KoBeWi** [comment]
Ok I think I fixed it. There was a special case where `saved_version` can be `-1` to force history as unsaved.

File: editor/editor_undo_redo_manager.cpp [hunk 1]
```diff
@@ -382,11 +382,15 @@ void EditorUndoRedoManager::set_history_as_unsaved(int p_id) {
 
 bool EditorUndoRedoManager::is_history_unsaved(int p_id) {
 	History &history = get_or_create_history(p_id);
+	if (history.saved_version == -1) {
```
Comment (akien-mga) [inline editor/editor_undo_redo_manager.cpp:385]: It's `uint64_t` so that triggers warnings.

Comment (KoBeWi) [reply editor/editor_undo_redo_manager.cpp:385]: Why this doesn't trigger warning? 🙃
https://github.com/godotengine/godot/blob/b7b3a1a78ad07591fa64e471ef5d42c1166e33e7/editor/editor_undo_redo_manager.cpp#L380

Comment (akien-mga) [reply editor/editor_undo_redo_manager.cpp]: No idea :(
Seems like they have warnings for `==` but not `=`.

**Review by akien-mga — APPROVED** [review]
Looks good. I confirm this fixes #106459.

**Comment by akien-mga** [comment]
Thanks!
