### PR TITLE
Fix navmesh baking

### LINKED ISSUE #57148: Baking navmesh on thread takes 100x more time
### Godot version

3.x (f2ec36fbcd486badcdca363d95be1f28b5f25e07)

### System information

manjaro linux

### Issue description

When baking navigation mesh with lots of obstacles (static bodies with box shape) the baking process on my PC takes the following time:

- ~1s in the editor
- ~100s when a scene is run
- ~1s when a scene is run and thread is disabled (`_bake_navigation_mesh` of `NavigationMeshInstance` called directly from the main thread)

From what I've narrowed down, the bottleneck is `NavigationMeshGenerator::_parse_geometry()`.

### Steps to reproduce

Run `ComplexNavmesBaking` demo scene from the project below.

### Minimal reproduction project

[godot-navigation-demos.zip](https://github.com/godotengine/godot/files/7928338/godot-navigation-demos.zip)

### PR DESCRIPTION
**Pull request by Scony**
fixes #57148

- improved mesh data calculation from static colliders so that no
  VisualServer calls are performed - and thus no VS mutexes need to
  be locked in case of on-thread baking
- improved the same for GridMap's static colliders

### CODE REVIEW

**Comment by Scony** [comment]
I've drafted a part of the solution for #57148

Basically, the idea is to export the static `create_mesh_array` function of each primitive mesh and leverage that when converting static colliders to raw mesh data. This way we don't need temporary mesh-es which are uploaded to the `VisualServer` and then accessed from it (which is very slow due to mutexes involved as `VisualServer` holds each mutex for a long interval).

Tested it on my reproduction project (1 big mesh and hundreds of static box colliders) and I got 100x speedup so basically, there is no problem with baking on thread anymore.

@AndreaCatania @akien-mga or @BastiaanOlij do you think this approach is ok?

**Comment by tavurth** [comment]
@Calinou @akien-mga can we check in on this PR?

**Comment by Scony** [comment]
If someone agrees on the approach presented at the moment, I'll implement the missing stuff.

**Comment by tavurth** [comment]
I was taking the same approach with my custom AStar, but using the outline generator which was generating a new mesh each time.

This seems to be something that needs to be done by 3.5, and seems like an optimal solution if it doesn't cause problems elsewhere

File: modules/navigation/navigation_mesh_generator.cpp [hunk 1]
```diff
@@ -194,10 +216,11 @@ void NavigationMeshGenerator::_parse_geometry(Transform p_accumulated_transform,
 
 					BoxShape *box = Object::cast_to<BoxShape>(*s);
 					if (box) {
-						Ref<CubeMesh> cube_mesh;
-						cube_mesh.instance();
-						cube_mesh->set_size(box->get_extents() * 2.0);
-						mesh = cube_mesh;
+						Array arr;
```
Comment (tavurth) [inline modules/navigation/navigation_mesh_generator.cpp:219]: Shouldn't this be the length of the vertices?

Comment (Scony) [reply modules/navigation/navigation_mesh_generator.cpp:219]: we don't know the number of vertices at this point so we're resizing to `VS::ARRAY_MAX`

**Review by AndreaCatania — APPROVED** [review]
Looks good, Great work!!

**Comment by AndreaCatania** [comment]
I think we use this technique on other places too (physics), probably we should consider doing the same we are doing in this PR.

**Comment by tavurth** [comment]
@Scony is this ready?

**Comment by akien-mga** [comment]
@Scony If you're happy with the PR in the current state, we could likely merge it for the next 3.5 beta this week. Just needs deciding if it's ready to go out of draft status.

**Comment by Scony** [comment]
It's far from ready, but I'll finish it before Sunday :)

**Comment by Scony** [comment]
Missing stuff added. @AndreaCatania would you mind re-review?

**Review by AndreaCatania — APPROVED** [review]
I like this change, this is a really good idea. I just wonder if we should remove `_add_mesh`, so far it doesn't seems used anymore. If it's dead code now you can consider remove it now.

In any case, LGTM :)

**Comment by Scony** [comment]
@AndreaCatania actually `_add_mesh` is still used in a few cases.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Could you PR the same for `master`, assuming it has the same issue?

**Comment by Scony** [comment]
Will do, no worries.
