### PR TITLE
Clear overrides on passing null

### LINKED ISSUE #29004: add_font_override("font", null) does nothing
**Godot version:**
master branch (3.1+?)

**OS/device including version:**
Windows 10, compiled with MSVS2019

**Issue description:**
add_font_override("font", null) does nothing, and should clear the previously set override

**Steps to reproduce:**
use the function mentioned with a valid override, then try to clear it using the same function with an empty font (as the documentation says)

### PR DESCRIPTION
**Pull request by swarnimarun**
Fixes #29004.

I could move the `erase()` function inside the `if has()` block but I think it's more readable this way.

### CODE REVIEW

File: scene/gui/control.cpp [hunk 1]
```diff
@@ -1840,53 +1840,76 @@ Rect2 Control::get_anchorable_rect() const {
...
 	if (data.icon_override.has(p_name)) {
 		data.icon_override[p_name]->disconnect("changed", this, "_override_changed");
 	}
-	data.icon_override[p_name] = p_icon;
-	if (data.icon_override[p_name].is_valid()) {
-		data.icon_override[p_name]->connect("changed", this, "_override_changed", Vector<Variant>(), CONNECT_REFERENCE_COUNTED);
+
+	// clear if "null" is passed instead of a icon
+	if (p_icon.is_null()) {
+		data.font_override.erase(p_name);
```
Comment (akien-mga) [inline scene/gui/control.cpp]: Should be `icon_override` I guess.

File: scene/gui/control.cpp [hunk 2]
```diff
@@ -1840,53 +1840,76 @@ Rect2 Control::get_anchorable_rect() const {
...
 		data.style_override[p_name]->disconnect("changed", this, "_override_changed");
 	}
-	data.style_override[p_name] = p_style;
-	if (data.style_override[p_name].is_valid()) {
-		data.style_override[p_name]->connect("changed", this, "_override_changed", Vector<Variant>(), CONNECT_REFERENCE_COUNTED);
-	}
 
+	// clear if "null" is passed instead of a style
+	if (p_style.is_null()) {
+		data.font_override.erase(p_name);
```
Comment (akien-mga) [inline scene/gui/control.cpp]: Should be `style_override`.

File: scene/gui/control.cpp [hunk 3]
```diff
@@ -1840,53 +1840,76 @@ Rect2 Control::get_anchorable_rect() const {
...
 	if (data.shader_override.has(p_name)) {
 		data.shader_override[p_name]->disconnect("changed", this, "_override_changed");
 	}
-	data.shader_override[p_name] = p_shader;
-	if (data.shader_override[p_name].is_valid()) {
-		data.shader_override[p_name]->connect("changed", this, "_override_changed", Vector<Variant>(), CONNECT_REFERENCE_COUNTED);
+
+	// clear if "null" is passed instead of a shader
+	if (p_shader.is_null()) {
+		data.font_override.erase(p_name);
```
Comment (akien-mga) [inline scene/gui/control.cpp]: Should be `shader_override`.

File: scene/gui/control.cpp [hunk 4]
```diff
@@ -1840,53 +1840,76 @@ Rect2 Control::get_anchorable_rect() const {
 
 void Control::add_icon_override(const StringName &p_name, const Ref<Texture> &p_icon) {
 
-	ERR_FAIL_COND(p_icon.is_null());
+	// ERR_FAIL_COND(p_icon.is_null());
```
Comment (akien-mga) [inline scene/gui/control.cpp]: You can remove those instead of commenting them out.

File: scene/gui/control.cpp (hunk 1 above)
Comment (swarnimarun) [reply scene/gui/control.cpp]: Seems like I can't even copy-paste stuff properly sometimes... :P

File: scene/gui/control.cpp (hunk 4 above)
Comment (swarnimarun) [reply scene/gui/control.cpp]: Oh. Just thought commenting those was some kind of a style :man_facepalming:

**Comment by akien-mga** [comment]
Thanks!
