### PR TITLE
Fix 'linux' and specific BSD feature tags

### LINKED ISSUE #76990: `OS.has_feature("linux")` returns false on linux
### Godot version

c80a2b4fe

### System information

ArchLinux x11

### Issue description

```gdscript
OS.has_feature("linux")
```
returns false.
This is a problem because:
- its a regression
- [documentation](https://docs.godotengine.org/en/stable/tutorials/export/feature_tags.html#default-features) tells you it works
- it works on other platforms
- it breaks gdextension, where you specify libs with feature tags: `linux.release.x86_64 = "res://lib.so"`

Regression introduced somewhere between bd1bc68..6980b2b
<sup>Causes [gdext#270](https://github.com/godot-rust/gdext/issues/270)</sup>

### PR DESCRIPTION
**Pull request by dsnopek**
After #76540, GDExtension's that have libraries like this are broken:

```
linux.debug.x86_64 = "res://bin/libexample.so"
```

... you now have to change that to:

```
linuxbsd.debug.x86_64 = "res://bin/libexample.so"
```

This also affects project settings that used the ".linux" suffix - those would also need to update to ".linuxbsd".

This PR makes the 'linux' feature tag work on Linux again, and it should also allow specific BSD tags (ex. freebsd, netbsd, etc) which were previously supported as well, but I don't personally have a way to test those.

- *Bugsquad edit: This closes https://github.com/godotengine/godot/issues/76990.*

### CODE REVIEW

File: platform/linuxbsd/os_linuxbsd.cpp [hunk 1]
```diff
@@ -494,6 +494,11 @@ bool OS_LinuxBSD::_check_internal_feature_support(const String &p_feature) {
 		return true;
 	}
 
+	// Match against the specific OS (linux, freebsd, etc).
+	if (p_feature == get_name().to_lower()) {
+		return true;
+	}
```
Comment (aaronfranke) [inline platform/linuxbsd/os_linuxbsd.cpp:500]: Shouldn't this be `get_identifier` to match `OS::has_feature`? The contents of the method are `return get_name().to_lower();`. But then... how is this code any different from this code already in `OS::has_feature`?

	if (p_feature == get_identifier()) {
		return true;
	}

Comment (dsnopek) [reply platform/linuxbsd/os_linuxbsd.cpp:500]: This is the code for `get_name()`:

```
String OS_LinuxBSD::get_name() const {
#ifdef __linux__
	return "Linux";
#elif defined(__FreeBSD__)
	return "FreeBSD";
#elif defined(__NetBSD__)
	return "NetBSD";
#elif defined(__OpenBSD__)
	return "OpenBSD";
#else
	return "BSD";
#endif
}
```

It's different depending on the OS, and gets 'linux' working on Linux again. `get_identifier()` is just this:

```
String OS_LinuxBSD::get_identifier() const {
	return "linuxbsd";
}
```

Comment (aaronfranke) [reply platform/linuxbsd/os_linuxbsd.cpp:500]: Ah, I see. Why do we have `OS_LinuxBSD::get_identifier()` separately overwritten if it also has a default implementation in the OS class?

It looks like the only other place that calls this method is `RemoteFilesystemClient::_synchronize_with_server`, which I am suspicious of, do we really want to have that class use the tag `linuxbsd` instead of `linux` and *`bsd` separately?

Comment (dsnopek) [reply platform/linuxbsd/os_linuxbsd.cpp:500]: > It looks like the only other place that calls this method is RemoteFilesystemClient::_synchronize_with_server, which I am suspicious of, do we really want to have that class use the tag linuxbsd instead of linux and *bsd separately?

I believe this was the intentional change: the PR that caused the regression (https://github.com/godotengine/godot/pull/76540) is about reworking how the remote file system works. I think causing the 'linux' and BSD feature tags to stop working was an unintended consequence of that.

**Review by akien-mga — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
