### PR TITLE
Fix PagedArray.merge_unordered() sometimes dropping pages

### LINKED ISSUE #73166: 3D Meshes disappearing (glitching?) in worlds with lots of objects.
### Godot version

4.0 RC1 dotnet

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

I was, just out of curiosity, testing what performance godot can give with larger worlds with just default settings dropping lots of objects in so I made a pretty big map (in the example below it was about 50000 objects, I went up to 400000 after that), I understand that there are optimization steps such as MultiMesh or the particle system or GeometryShaders, I did NOT use any of these.

As you can see sometimes something glitches, I thought maybe it was an issues with not having properly set up shadow map or something but in the video editor I noticed that some meshes jsut completely disappear. I'm not sure if this is an actual bug or maybe just my computer not being strong enough to handle this? (the scene was running at smooth 60 fps).

I also tried this on a smaller scene with couple hundreds objects but I had no issues there, I have them only when I add large number of objects.
It also doesn't seem to be an issues of distance since it happens to both distant objects as well as nearby ones. In the video you can see I even jump to increase the distance with objects below but they get back to normal when I move.

It also happens only at certain camera angles I guess (or at least it seems to be related to a camera angle or some world positions?).

I'm sorry if this is not an issues I wasn't sure if this is worth a report or if this is just my HW?

Please check the entire video below, I've also took couple screenshots to showcase what exactly happens because some of these happen in just a frame or so (in a video editing program I've took screenshots of exact moments of the issues).

Video: https://youtu.be/63NRSsudxu0 (check timestamps)

Images:
Issues apparent in the distance (long grea area from left to right) and meshes disappear in the bottom right corner.
glitch0
Well lots of meshes disappeared, compared to the video if needed it's the last couple seconds)
glitch1
Well lots of meshes disappeared, compared to the video if needed it's the last couple seconds)
glitch2

### Steps to reproduce

Using Minimal Reproduction Project:
1. Play the project.
2. If it doesn't load in a reasonable time (my old computer takes couple seconds) then play stop and then press the play button again (yeah for some reason if your project adds a lot of stuff in Godot at the beginning it doesn't start away and you need to stop and play it again - NOT pause!)
3. Take your hands off mouse so you don't move the character wrong.
4. Press CTRL + E (your character will be moved to position and rotated properly where I get the issues every time)
5. Observer (check screen/video below to see what it looks like)
6. If you don't see any issues then you might need to walk around for quiet a while and find perfect spot + rotation, it only happens under certain conditions, I have no idea what these are), if your HW is better than mine then you might need to increase the number of objects in the screen by clicking on Main node and changing Size (but be careful how much you change this value, it roughly equals to `(rows * columns) * 3 * 1.5`, the current 325 is about 400k objects!)

(In your own custom project: Add lots of objects to the scene and move around, observe what was in the video.)

### Minimal reproduction project

[LotsObjectsGlitchRepro.zip](https://github.com/godotengine/godot/files/10721849/LotsObjectsGlitchRepro.zip)
Video from minimal repro project: https://youtu.be/Hi9m2Q-kAcY
(At the beginning there's just couple frames showcasing it happening in other parts of the world but you have to pause the video and really just move frame by frame to see these, the second part of the video shows the saved location you can get to with CTRL + E)

### PR DESCRIPTION
**Pull request by myaaaaaaaaa**
`PagedArray.merge_unordered()` drops the last page if the array being merged in has a size that's a multiple of the page size.

Fixes #73166

### CODE REVIEW

File: core/templates/paged_array.h [hunk 1]
```diff
@@ -278,27 +278,25 @@ class PagedArray {
...
 			uint32_t page_count = _get_pages_in_use();
 			uint32_t new_page_count = page_count + 1;
 
 			if (unlikely(new_page_count > max_pages_used)) {
 				_grow_page_array(); //keep out of inline
 			}
 
-			page_data[page_count] = p_array.page_data[i];
-			page_ids[page_count] = p_array.page_ids[i];
-			if (i == src_pages - 1) {
```
Comment (RandomShaper) [inline core/templates/paged_array.h:294]: For the records, the issue was here. The last page was assumed to be partially filled. If it happened to contain as many items as the page size (page full), `count` would be incremented by zero instead of by the page size.

This line inside this branch would prove so: `DEV_ASSERT((p_array.count & page_size_mask) != 0);`.

**Review by RandomShaper — APPROVED** [review]
Good catch.

I've added an informative comment explaining what the issue was.

**Comment by akien-mga** [comment]
Thanks!
