### PR TITLE
Don't save unnecessarily with `save_before_running`

### LINKED ISSUE #78753: 'Save before running' option in editor can greatly affect the speed of starting a run
### Godot version

4.1 beta3 

### System information

Windows 11

### Issue description

I've recently found the startup of running projects to be unbearably slow. Sometimes the editor would hang for like ~40s from the time I pressed the run button until I saw the actual game window.
After doing some research, I found that if I didn't have any of the scenes open in the editor, then I would get instantaneous startup speeds. The more scenes that are open in the editor, the slower it is to start the game.
I further found that disabling the 'save before running' option would give me almost the same startup speed as not having any scenes open while having a large number of scenes open.
I find it strange that even if none of the scenes have changed, enabling the 'save before running' option will save them all over again. I guess this affects the speed of the startup. I think it might be better to skip saving scenes that haven't changed.

no scene opened:
Godot_v4 1-beta3_win64_hzXmzFfllc

9 scenes opened and 'Save before running' on (~30s):
Godot_v4 1-beta3_win64_8ijcaF5Z0r

9 scenes opened and 'Save before running' off:
Godot_v4 1-beta3_win64_smMKD2tYpm

There are some gif compression issues, but I think they are enough to illustrate what I mean.

### Steps to reproduce

1. Open a large number of more complex scenes in the editor
2. Make sure the 'Save before running' option is enabled in the editor settings
3. Run the game
4. Watch the editor hangs

### Minimal reproduction project

N/A
In a small project, it may not make a significant difference, so it is difficult to produce an MRP.

### LINKED ISSUE #94563: Game window loses focus due to scene group update
### Tested versions

4.3 beta3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Regression from #89739, though I didn't notice it until recently. Might be a combination of various factors.

When you launch the project, all scenes are saved, which triggers update of scene groups, which causes editor progress to appear due to groups. The editor progress makes the window focused, stealing focus from the launched project.

### Steps to reproduce

0. Make sure `run/auto_save/save_before_running` is enabled
1. Open multiple scenes
2. Run the project
3. See that the running window is not focused

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
When `save_before_running` is enabled, it will save all scenes, which can lead to longer running times if you have many opened scenes. That's rather absurd.

This PR changes that mechanism to only save when there are unsaved changes in the scene (which we can detect pretty reliably).

Fixes #78753
Fixes #94563

### CODE REVIEW

**Comment by Calinou** [comment]
> This PR changes that mechanism to only save when there are unsaved changes in the scene (which we can detect pretty reliably).

With editor plugins, this may not be the case: https://github.com/godotengine/godot-proposals/issues/2153

**Comment by ogapo** [comment]
Excited to see this change come in! I am wondering if rather than changing the behavior only for `save_before_running` it might make more sense to change the implementation of "Save All Scenes" instead (with the same caveats @Calinou pointed out)?

The current behavior of "Save All Scenes" is really "Re-Save All Open Scenes" and that's not super useful. I'd expect it to either 1) save all dirty scenes (strict subset of open ones so I think that's why the current implementation is what it is) or 2) Re-Save All Scenes regardless of open status. Doing a full re-save but only of open scenes feels like a weird in-between that isn't correct for either reasonable interpretation. 

Personally I'd prefer to have it just do option #1 (hence this suggestion) but I could see a use case for full re-save too. Most applications that support multiple documents simply have a "Save All" option which essentially just takes care of dirty docs so I think it's reasonable to expect users would interpret it as this. 

Also I noticed it technically resaves everything that's open (including shaders and scripts) so "Save All" might be a more correct name as well.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -3356,6 +3384,14 @@ void EditorNode::_discard_changes(const String &p_str) {
...
 
 void EditorNode::_update_file_menu_opened() {
+	bool has_unsaved = false;
+	for (int i = 0; i < editor_data.get_edited_scene_count(); i++) {
+		if (_is_scene_unsaved(i)) {
+			has_unsaved = true;
+			break;
+		}
+	}
+	file_menu->set_item_disabled(file_menu->get_item_index(FILE_SAVE_ALL_SCENES), !has_unsaved);
```
Comment (akien-mga) [inline editor/editor_node.cpp:3394]: Will it seem clear enough to the user why this is disabled?

Comment (KoBeWi) [reply editor/editor_node.cpp:3394]: I can add a tooltip.

**Comment by ogapo** [comment]
This change works like a charm for scenes and scripts. In testing, however, I noticed that any open shaders always re-save any time any scene is saved (whether or not they are modified). I tracked it down to needing an `is_unsaved` check in `ShaderEditorPlugin::save_external_data()` i.e.

```c++
void ShaderEditorPlugin::save_external_data() {
	for (EditedShader &edited_shader : edited_shaders) {
		if (edited_shader.shader_editor) {
			if (edited_shader.shader_editor->is_unsaved()) {
				edited_shader.shader_editor->save_external_data();
			}
		}
	}
	_update_shader_list();
}
```

It might be worth including that in this PR also for completeness sake.

**Comment by akien-mga** [comment]
How does this work with changes to resources, instead of scenes? Currently I think a lot of the Godot workflow hinges on scene saving actually saving all dependent resources, even if there's no change to the scene itself. Saving changes to resources specifically is pretty cumbersome currently with just the save button in the inspector IIRC.

**Comment by KoBeWi** [comment]
Apparently if you make a change in external resource, the editor will save the current scene which will also save that resource 🤔
And if you have no open scenes, the external changes are not saved when running. But this is the same behavior as before this PR, so it can be fixed separately.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -2000,6 +2006,28 @@ void EditorNode::_mark_unsaved_scenes() {
...
+
+	if (EditorUndoRedoManager::get_singleton()->is_history_unsaved(editor_data.get_scene_history_id(p_idx))) {
+		return true;
+	}
+
+	const String &scene_path = scene->get_scene_file_path();
+	if (!scene_path.is_empty()) {
+		// Check if scene has unsaved changes in built-in resources.
+		for (int j = 0; j < editor_data.get_editor_plugin_count(); j++) {
+			if (!editor_data.get_editor_plugin(j)->get_unsaved_status(scene_path).is_empty()) {
```
Comment (Mickeon) [inline editor/editor_node.cpp:2023]:
```suggestion
		for (int i = 0; i < editor_data.get_editor_plugin_count(); i++) {
			if (!editor_data.get_editor_plugin(i)->get_unsaved_status(scene_path).is_empty()) {
```
Unless `j` was chosen because of `p_idx`

Comment (KoBeWi) [reply editor/editor_node.cpp:2023]: j was choosen because of outer loop.

File: editor/editor_node.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/editor_node.cpp]: Added a tooltip, although we don't really do that anywhere else.

**Review by akien-mga — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/f2cc3f12750adae431384d7bac2f75d1c7e506be), it works as expected. The disabled state of **Save All Scenes** updates correctly, including with undo/redo.

Note that when you modify a scene, switch to another scene tab then run the project with <kbd>F5</kbd>, the progress dialog won't appear. However, the change is correctly reflected in the running project.

The progress dialog only appears when you press <kbd>F5</kbd> while your current scene tab is a modified scene.

**Comment by Repiteo** [comment]
Thanks!
