### PR TITLE
WebGL2: Fix 2D array textures with RGTC compression not rendering

### LINKED ISSUE #101711: Shadowmasks broken on Web exports when using RGTC texture compression
### Tested versions

Godot v4.4.beta1

### System information

Godot v4.4.beta1 - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu, 02 Jan 2025 10:28:29 +0000 on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 (nvidia) - AMD Ryzen 9 9900X 12-Core Processor (24 threads)

### Issue description

Image
Currently in the beta build the shadow-masks are rendered incorrectly. Here I have the shadowmask mode set to **Replace** and you can clearly see the distance at which it switches to the shadow mask and there's a shadowed line.

Image
Here it is with the shadowmask mode set to **None**

Image
And with the shadowmask mode set to **Overlay** (notice how much brighter the people are, as they're lit dynamically and not with the lightmap)

and finally what it *should* look like (and what it looks like in the editor or when exported as an android build):
Image
shadowmask mode set to **Overlay** in android build

Hopefully this is possible to fix, shadowmasks are *incredibly* useful for web builds where performance is paramount.
### Steps to reproduce

Create a scene with lightmap GI and the shadowmask mode set to replace or overlay and notice the broken shadows. 

### Minimal reproduction project (MRP)

Here's a simple MRP with the same behavior shown (shadowmasks broken only on web builds):

Image

[shadowmask-test.zip](https://github.com/user-attachments/files/18458584/shadowmask-test.zip)

### PR DESCRIPTION
**Pull request by BlueCube3310**
Fixes #101711

WebGL2 seemingly doesn't support 2D array RGTC-compressed textures (though it's not documented anywhere). This PR makes it so that under WebGL2 layered textures with RGTC compression are decompressed before being used. 

The memory usage increase shouldn't be too significant, since the decompressed images only use either 1 or 2 color channels, so they will be twice as big (8 bytes vs 16 for RGTC_R and 16 bytes vs 32 for RGTC_RG)

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Makes sense to me.

**Comment by clayjohn** [comment]
WebGL uses the [`EXT_texture_compression_rgtc`](https://registry.khronos.org/webgl/extensions/EXT_texture_compression_rgtc/) extension to support RGTC, which only supports 2D images (not 3D images which include array textures). 

Compare that to the [`WEBGL_compressed_texture`](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_etc/) extension (for ETC) which specifically mentions array textures. 

Implementations are required to support either ETC or S3TC/RGTC, but the wording of _both_ the RGTC and S3TC extensions don't cover array textures. Therefore they are not required to be supported for RGTC or S3TC. 

Have you checked whether S3TC array textures are supported on your device? I wonder if there is another optional extension that adds support that we could check for.

**Comment by clayjohn** [comment]
On an unrelated note, it would be interesting to look into properly supporting ASTC in the web. I think all we need to do is check for [`WEBGL_compressed_texture_astc`] and then it should work just like BPTC.

File: drivers/gles3/storage/texture_storage.cpp [hunk 1]
```diff
@@ -1509,8 +1509,19 @@ void TextureStorage::_texture_set_data(RID p_texture, const Ref<Image> &p_image,
 	GLenum internal_format;
 	bool compressed = false;
 
+	bool needs_decompress = texture->resize_to_po2;
+
+#ifdef WEB_ENABLED
```
Comment (clayjohn) [inline drivers/gles3/storage/texture_storage.cpp:1514]: After looking into it, this seems to be true for all GLES3 contexts since they rely on [`EXT_texture_compression_rgtc `](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_texture_compression_rgtc.txt) which explicitly does not support 3D textures. 

Therefore, I think this needs to use `is_gles_over_gl()` instead to capture any time we use a GLES3 context (i.e. web, mobile, and ANGLE on desktop). 

I am not 100% sure about ANGLE on desktop though, it might work anyway despite not being guaranteed by the spec

**Comment by BlueCube3310** [comment]
> On an unrelated note, it would be interesting to look into properly supporting ASTC in the web. I think all we need to do is check for [`WEBGL_compressed_texture_astc`](https://registry.khronos.org/webgl/extensions/WEBGL_compressed_texture_astc/) and then it should work just like BPTC. Also it seems very [widely support](https://caniuse.com/mdn-api_webgl_compressed_texture_astc) so for web exports we may want to always use ASTC when available

Added in #101932

**Review by clayjohn — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
