### PR TITLE
Avoid bubbling up changed notification when on new item/key of dictionaries to avoid inspector wipeout.

### LINKED ISSUE #95647: AnimationPlayer dictionary for AnimationLibraries does not accept values after the first
### Tested versions

Reproducible: 4.3 stable mono
Working: 4.1.1 stable mono

### System information

Godot 4.3 mono - Windows 7

### Issue description

When the dictionary that holds AnimationLibraries on the AnimationPlayer has 1 entry, trying to to add a key or value with the type of String or Object (possibly others, but float works) will make the focus shift as soon as you start typing the sting, and the Key-Value form resets.

### Steps to reproduce

Open AnimationPlayer.
In Libraries dictionary select New Key's type "String".
Start typing the sting.
(alternatively, select Object and drag AnimationLibrary onto the input space)

### Minimal reproduction project (MRP)

[dictionary does not accept string.zip](https://github.com/user-attachments/files/16639228/dictionary.does.not.accept.string.zip)

### PR DESCRIPTION
**Pull request by ajreckof**
fix #95647
This fix the issue at hand but first of all I'm not sure this is the right fix second I'm not even sure this property should be exposed in the inspector as it doesn't seem to be the right way to edit it (dedicated interface in the animation bottom panel). In any case this fix is safe so it can be included anyway.

### CODE REVIEW

**Comment by fire** [comment]
I don't know if this is correct. Needs someone to investigate.

**Comment by ajreckof** [comment]
I just remembered why I didn't do it while it was so simple to do. Doing it the easy way like I did makes the copy paste bug to reappear. I'll make a version that fixes both this and not make the copy paste bug reappear during this week-end. Shouldn't too hard but requires a bit more thought then this first attempt.

**Comment by ajreckof** [comment]
In the end I had some time rn so made the PR and here are some small hindsight on the subject. 
**So why the bug this fixes happens.** 
What happens is that modifying the libraries modifies the available animation available. The available animation are needed in the property `current_animation` as it is a drop down menu of all animation available. Hence whenever the list of animations are changed you need to update the list of properties. Unfortunately rn this means a full whipe out  of the inspector. 
**You might have realised there is two possibilities other then what I propose here.**
First we could finally enable the possibility to only update/remove/add properties in the list so that small modifications like that do not whipe-out the full inspector. This is something that is also needed to fix other bugs and as been discarded for now as it would be something that needs a lot of work. But since bugs that would highly benefit from it tends to stack, it might indicate that the work might be worth it. 
The second possible fix is to only update the list of properties only if the list of animations is actually modified. In fact here when we type a string this does not affect the list of animation in any way hence there is no reason to whipe-out the 

 **How the bug can happen outside of this scope**
 In fact everything that is done here could be replicated in GDScript (I could give a MRP if needed). The question that I'm wondering is wether this practice would be considered an user error as it is the user that is whiping out the inspector at every change even if there isn't the need to (in this situation we should modify our code as proposed in previous paragraphs) or it the fault of the engine that is reporting modification where there isn't (then what is needed is the change in this PR). Maybe both are valid and both fixes are needed.

File: editor/editor_properties_array_dict.cpp [hunk 1]
```diff
@@ -869,7 +869,11 @@ void EditorPropertyDictionary::_property_changed(const String &p_property, Varia
 	}
 
 	object->set(p_property, p_value);
-	emit_changed(get_edited_property(), object->get_dict(), p_name, p_changing);
+	bool new_item_or_key = !p_property.begins_with("indices");
+	emit_changed(get_edited_property(), object->get_dict(), p_name, p_changing || new_item_or_key);
+	if (new_item_or_key) {
+		update_property();
```
Comment (KoBeWi) [inline editor/editor_properties_array_dict.cpp:875]: What's this line for?

Comment (ajreckof) [reply editor/editor_properties_array_dict.cpp:875]: the `p_changing || new_item_or_key` prevent the inspector from being wiped out but at the same times it means it won't be updated at all so when needed we update it manually.

**Review by KoBeWi — APPROVED** [review]
