### PR TITLE
Fix one-way-collision polygons being merged despite being on different Y-origins in TileMapLayer

### LINKED ISSUE #109492: One-way property of shapes is not respected in TileMapLayer chunks
### Tested versions

- Reproducible in: all snapshots between 4.5.dev1 and 4.5.beta5
- Not reproducible in: 4.4.1.stable

### System information

Godot v4.5.beta5 - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1070 Ti (nvidia; 550.163.01) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 threads) - 15.57 GiB memory

### Issue description

I'm creating 2D platformer and I want to add semisolid tiles that can stack on top of each other.

Since [GH-102662](https://github.com/godotengine/godot/pull/102662) adjacent tiles merge into bigger collision shapes. This process doesn't respect one-way property of shapes and always merge them.
In my case this leads to only topmost tile having one-way collision.
This can be fixed by setting 'physics_quadrant_size' to 1.

physics_quadrant_size = 16

https://github.com/user-attachments/assets/15f3fa49-877c-4251-ae32-f5cdea2b7db0

physics_quadrant_size = 1

https://github.com/user-attachments/assets/f494e423-0756-483b-aaed-ce220d50f01c

### Steps to reproduce

MRP:
1. Open project;
2. Run it (Controls: left and right arrows, space for jump);
3. Notice that only topmost tiles have one-way collision.

Manual:
1. Add TileMapLayer to scene;
2. Add tile and assign shape with one-way collision to it;
3. Draw tiles and stack them on top of each other;
4. Add CharacterBody2D with rectangle shape and attach short script for platformer controls:
```GDScript
extends CharacterBody2D

func _physics_process(delta: float) -> void:
	velocity.x = 500.0 * Input.get_axis(&"ui_left", &"ui_right")
	velocity.y += 1000.0 * delta
	
	if is_on_floor() and Input.is_action_just_pressed(&"ui_accept"):
		velocity.y -= 600.0            
	
	move_and_slide()
```
5. Run project and notice that only topmost tiles have one-way collision.

### Minimal reproduction project (MRP)

[OneWayTilesBug.zip](https://github.com/user-attachments/files/21705858/OneWayTilesBug.zip)

### PR DESCRIPTION
**Pull request by groud**
Fixes [#109492](https://github.com/godotengine/godot/issues/109492)

### CODE REVIEW

File: scene/2d/tile_map_layer.h [hunk 1]
```diff
@@ -243,14 +243,23 @@ class PhysicsQuadrant : public RefCounted {
...
+
 		bool operator<(const PhysicsBodyKey &p_other) const {
 			if (physics_layer == p_other.physics_layer) {
 				if (linear_velocity == p_other.linear_velocity) {
 					if (angular_velocity == p_other.angular_velocity) {
 						if (one_way_collision == p_other.one_way_collision) {
+							if (one_way_collision) {
+								if (y_origin == p_other.y_origin) {
+									return one_way_collision_margin < p_other.one_way_collision_margin;
+								}
```
Comment (KoBeWi) [inline scene/2d/tile_map_layer.h]:
```suggestion
							if (one_way_collision && y_origin != p_other.y_origin) {
```
Simpler, avoids checking margin twice.

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
