### PR TITLE
Fix randfn to prevent generating of nan values

### LINKED ISSUE #72394: `randfn` can extremely rarely return nan in some cases
### Godot version

3.5, 4.0 beta and probably most other versions that have `randfn`

### System information

N/A

### Issue description

I believe there is a possibility that `randfn` (implemented in https://github.com/godotengine/godot/blob/master/core/math/random_pcg.h), can extremely rarely produce nan when `deviation` is 0 or in even rarer cases with any `deviation` value.

This is because the value is computed as `p_mean + p_deviation * (cos(Math_TAU * randd()) * sqrt(-2.0 * log(randd())))`.  
When `randd()` returns 0 then `log(randd())` would be -infinity and by extension `sqrt(-2.0 * log(randd())))` would be infinity. If `p_deviation` or `(cos(Math_TAU * randd())` is 0 then this would lead to a value of 0 * infinity which under IEEE floating point standard is nan.

While this is an extremely rare occurrance (in fact I have yet to successfully produce it in godot), it would be nice if this was fixed or documented, so that if someone does happen to come across it they will at least know what happened.

### Steps to reproduce

In theory it should be reproducible by running `randfn` calls with a `deviation` value of 0 for a long time and checking for nan, but this is rare enough that it would probably take more than several days of continuous running to observe a single occurrance.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/72394

### CODE REVIEW

File: core/math/random_pcg.h [hunk 1]
```diff
@@ -126,10 +126,18 @@ class RandomPCG {
 	}
 
 	_FORCE_INLINE_ double randfn(double p_mean, double p_deviation) {
-		return p_mean + p_deviation * (cos(Math_TAU * randd()) * sqrt(-2.0 * log(randd()))); // Box-Muller transform
+		double temp = randd();
+		if (fabs(temp) < CMP_EPSILON) {
```
Comment (akien-mga) [inline core/math/random_pcg.h:130]: If it's e.g. `- CMP_EPSILON/2`, adding `CMP_EPSILON` won't be enough to make it far enough from 0.

Comment (Chaosus) [reply core/math/random_pcg.h]: Ah, I forgot the fact that CMP_EPSILON2 is precision used by double. I've changed it a bit - does this looks correct now?

Comment (Chaosus) [reply core/math/random_pcg.h]: But what the point if `randd` generates the value in range of 0.0 - 1.0 and SIGN will always return positive sign?

Comment (Chaosus) [reply core/math/random_pcg.h]: Ah, and SIGN suddenly receive 0.0 from `randd`, then the `temp` become 0, because 0 *  (temp_abs + CMP_EPSILON); will be 0.

Comment (akien-mga) [reply core/math/random_pcg.h]: Well, why do you use `fabs()` if `randd()` is always positive? That's what caused my confusion.

Comment (Chaosus) [reply core/math/random_pcg.h]: Hmm.. how true..

File: core/math/random_pcg.h [hunk 2]
```diff
@@ -126,10 +126,18 @@ class RandomPCG {
 	}
 
 	_FORCE_INLINE_ double randfn(double p_mean, double p_deviation) {
-		return p_mean + p_deviation * (cos(Math_TAU * randd()) * sqrt(-2.0 * log(randd()))); // Box-Muller transform
+		double temp = randd();
+		if (temp < CMP_EPSILON2) {
+			temp += CMP_EPSILON2; // To prevent generating of INF value in log function, resulting to return NaN value from this function.
```
Comment (akien-mga) [inline core/math/random_pcg.h:131]: `CMP_EPSILON2` is for squared values, not relevant here:
```
#define CMP_EPSILON 0.00001
#define CMP_EPSILON2 (CMP_EPSILON * CMP_EPSILON)
```

Comment (Chaosus) [reply core/math/random_pcg.h:131]: I thought it for double type cuz 0.00001 * 0.00001 = 0.000000001

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.
