### PR TITLE
Fix shader editor filename not updating after file rename

### LINKED ISSUE #113451: Filename not updated in Shader Editor after renaming a shader file
### Tested versions

Reproducible: 
- v4.6.dev.custom_build [5f12ada7a]
- 4.5.1.stable
- 4.2.stable

### System information

Godot v4.6.dev (5f12ada7a) - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 24 Nov 2025 15:21:09 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 580.105.08) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads) - 15.37 GiB memory

### Issue description

After renaming a shader file, its filename is not updated accordingly in Shader Editor.

Image

### Steps to reproduce

1. Create a new shader in Shader Editor
2. Rename the shader file in FileSystem
3. Check the file list in Shader Editor
    - Expected: The filename is changed
    - Actual: The filename stays the same

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ayanchavand**
Fixes  #113451 
Connected the editor’s global `filesystem_changed` signal to the shader editor UI refresh, so shader tab names update immediately after a rename.

### CODE REVIEW

File: editor/shader/shader_editor_plugin.cpp [hunk 1]
```diff
@@ -828,6 +828,7 @@ void ShaderEditorPlugin::_notification(int p_what) {
 			EditorNode::get_singleton()->connect("scene_closed", callable_mp(this, &ShaderEditorPlugin::_close_builtin_shaders_from_scene));
 			FileSystemDock::get_singleton()->connect("file_removed", callable_mp(this, &ShaderEditorPlugin::_file_removed));
 			EditorNode::get_singleton()->connect("resource_saved", callable_mp(this, &ShaderEditorPlugin::_res_saved_callback));
+			EditorFileSystem::get_singleton()->connect("filesystem_changed", callable_mp(this, &ShaderEditorPlugin::_update_shader_list), CONNECT_DEFERRED);
```
Comment (kitbdev) [inline editor/shader/shader_editor_plugin.cpp]: Is there a reason why this is deferred? It should work without it.

**Review by kitbdev — APPROVED** [review]
Makes sense, ScriptEditor does this too.
Fixes the issue.

File: editor/shader/shader_editor_plugin.cpp (hunk 1 above)
Comment (ayanchavand) [reply editor/shader/shader_editor_plugin.cpp]: I added it to avoid updating the shader list during filesystem change processing. If that’s not a concern here, I’m happy to drop it.

Comment (kitbdev) [reply editor/shader/shader_editor_plugin.cpp]: The signal is generally emitted after the filesystem scan is done, and ScriptEditor doesn't seem to need it deferred. 
So we should remove the deferred here if it isn't needed.

**Review by kitbdev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
