### PR TITLE
Correct occlusion culling viewport location calculation when projection uses asymmetric FOV

### LINKED ISSUE #104193: Occlusion Culling on OpenXR is unstable (meshes flickering) in Godot4.4-stable
### Tested versions

- Reproducible in Godot v4.4-stable, Godot v4.4.1-rc1
   - Meta Quest 3
   - X11+SteamVR/OpenXR Vulkan (mobile and forward+)
       - OpenXR: Running on OpenXR runtime:  SteamVR/OpenXR   2.9.6
       - OpenXR: XrGraphicsRequirementsVulkan2KHR:
         - minApiVersionSupported:  1.0.0
         - maxApiVersionSupported:  1.2.0

- Not Reproducible in Godot v4.3-stable

### System information

Godot v4.4.stable - Ubuntu 22.04.5 LTS 22.04 on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU - 12th Gen Intel(R) Core(TM) i7-12700H (14 threads)

### Issue description

https://github.com/user-attachments/assets/b1f55edf-e9d9-4691-80e5-fc0363f7f0fc

When Occlusion Culling is enabled in Godot 4.4-stable some meshes are mysteriously culled. Only Reproducible when using OpenXR and `root.use_xr == true`

### Steps to reproduce

* Extract minimal reproduction in OpenXR
* install [Godot Openxr vendors addon](https://github.com/GodotVR/godot_openxr_vendors/releases/) in 4_4/addons and 4_3/addons
* Run 4_4/project.godot or 4_3/project.godot

### Minimal reproduction project (MRP)

[xr-ocull-broken.zip](https://github.com/user-attachments/files/19265466/xr-ocull-broken.zip)

### PR DESCRIPTION
**Pull request by jamie-pate**
Fixes #104193

In OpenXR the viewport location is not centered on the transform origin

### CODE REVIEW

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 1]
```diff
@@ -596,8 +596,10 @@ void RaycastOcclusionCull::buffer_update(RID p_buffer, const Transform3D &p_cam_
 	scenario.update();
 
 	Vector2 viewport_half = p_cam_projection.get_viewport_half_extents();
-	Vector2 jitter_viewport_half = _jitter_half_extents(viewport_half, buffer.get_occlusion_buffer_size());
-	Vector3 near_bottom_left = Vector3(-jitter_viewport_half.x, -jitter_viewport_half.y, -p_cam_projection.get_z_near());
+	Vector2 jitter = _get_jitter(viewport_half, buffer.get_occlusion_buffer_size());
+	Vector3 endpoints[8];
+	p_cam_projection.get_endpoints(Transform3D(), endpoints);
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.cpp:601]: You don't need the 8 endpoints - just the near-bottom-left corner.

This currently adds a performance penalty to all users including non-XR (`get_endpoints()` is not that cheap)

**Review by Flarkk — CHANGES_REQUESTED** [review]
In its current state this PR will introduce inconsistent jittering on the Y-axis for OpenXR users, in addition to some performance penalty to everyone.

I believe there's a cleaner way to solve it - see my detailed comments.

As a side effect, this will also fix occlusion culling with `FRUSTUM` camera mode as it likely suffers from the same issue.

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 2]
```diff
@@ -596,8 +596,10 @@ void RaycastOcclusionCull::buffer_update(RID p_buffer, const Transform3D &p_cam_
 	scenario.update();
 
 	Vector2 viewport_half = p_cam_projection.get_viewport_half_extents();
-	Vector2 jitter_viewport_half = _jitter_half_extents(viewport_half, buffer.get_occlusion_buffer_size());
-	Vector3 near_bottom_left = Vector3(-jitter_viewport_half.x, -jitter_viewport_half.y, -p_cam_projection.get_z_near());
+	Vector2 jitter = _get_jitter(viewport_half, buffer.get_occlusion_buffer_size());
```
[the remark this answers is not in the document]
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp:599]: `get_viewport_rect()` would be similar to `get_endpoints()` but only get the 4 near plane endpoints right?

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 1 above)
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp:601]: I meant to measure the penalty but decided to let this cook for a bit first :D

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp:599]: well, 2 endpoints, but 5 planes (instead of 6) and 6 intersections instead of 46

[the remark this answers is not in the document]
Comment (Flarkk) [reply modules/raycast/raycast_occlusion_cull.cpp:599]: It would compute the near-bottom-left and the near-top-right corners, then assume the viewport is a rectangle laying in the XY plane and return the bottom corner and the extents.

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 1 above)
Comment (Flarkk) [reply modules/raycast/raycast_occlusion_cull.cpp:601]: With my suggestion to add and use `get_viewport_rect()` in the other comment you wouldn't need `get_endpoints()` at all.
`get_viewport_rect()` would call 2 `Plane::intersect3()` and you're all set.

**Comment by dsnopek** [comment]
I can confirm that this PR fixes the issue as shown in the MRP on https://github.com/godotengine/godot/issues/104193

I'd be happy to re-test again after it's been updated

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp:599]: do we still have to rethink the jitter calculation to account for a skewed viewport?

[the remark this answers is not in the document]
Comment (Flarkk) [reply modules/raycast/raycast_occlusion_cull.cpp:599]: What I call a skewed viewport still has rectangular far and near planes in the XY plane. You can take a look at the `Camera3D`'s `FRUSTUM` mode : it's exactly that.

No additional transformation is needed : just take a corner and translate it by a certain amount across X and Y, as it's done in the current implementation.

Hope that helps !

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 3]
```diff
@@ -594,10 +594,14 @@ void RaycastOcclusionCull::buffer_update(RID p_buffer, const Transform3D &p_cam_
 
 	Scenario &scenario = scenarios[buffer.scenario_rid];
 	scenario.update();
-
-	Vector2 viewport_half = p_cam_projection.get_viewport_half_extents();
-	Vector2 jitter_viewport_half = _jitter_half_extents(viewport_half, buffer.get_occlusion_buffer_size());
-	Vector3 near_bottom_left = Vector3(-jitter_viewport_half.x, -jitter_viewport_half.y, -p_cam_projection.get_z_near());
+	Vector3 near_top_right;
+	Vector3 near_bottom_left;
+	p_cam_projection.get_viewport_endpoints(near_bottom_left, near_top_right);
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.cpp:599]: Could you try using `Projection::get_viewport_rect()` from PR #104311 I just pulled together instead ?
I think it's going to be more consistent.

Comment (dsnopek) [reply modules/raycast/raycast_occlusion_cull.cpp:599]: For the purposes of this PR, I personally think we should avoid changing `Projection` at all. If we can keep the change local to `RaycastOcclusionCull`, then we can perhaps get this merged for Godot 4.4.1 (which is likely to happen in a matter of days). But if we change `Projection` then it'll need to be discussed and approved by the core team, which could take longer.

Comment (Flarkk) [reply modules/raycast/raycast_occlusion_cull.cpp:599]: I thought @jamie-pate could locally duplicate the logic I implemented in `Projection` as a short-term fix.

You're right changing `Projection` will take longer, but it has it own interest : I see many places `get_viewport_half_extents()` is used without care for non-symmetrical viewports, which create issues soon or later. `get_viewport_rect()` offers a safe alternative.

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 1 above)
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp]: more timings :D
vp_endpoints is the new fn which takes 0.5us roughly
endpoints is `get_endpoints()` which takes roughly 1.25us
all of it's dominated by the actual work of course at 355..1000us

vp_endpoints 100x: 91us endpoints 100x: 158us rest: 1035us
vp_endpoints 100x: 79us endpoints 100x: 136us rest: 558us
vp_endpoints 100x: 79us endpoints 100x: 144us rest: 543us
vp_endpoints 100x: 59us endpoints 100x: 100us rest: 385us
vp_endpoints 100x: 61us endpoints 100x: 113us rest: 591us
vp_endpoints 100x: 59us endpoints 100x: 102us rest: 615us
vp_endpoints 100x: 57us endpoints 100x: 100us rest: 355us

**Comment by jamie-pate** [comment]
> Something I'm a little confused about with this PR, is that it appears to only be changing the jitter calculation, but isn't changing the code from PR #98758 that apparently caused the regression. That code still uses `get_viewport_half_extents()` - is that OK? Also, is this PR in some way better than reverting that PR, and trying to come up with a different way to fix the bug it intended to fix?

I had to put the fix in the calling function at the current HEAD because the change in https://github.com/godotengine/godot/pull/98758 has actually been refactored here: c7895ca22686bb0c6873f265273503bea93cd69d

**Comment by Flarkk** [comment]
Ah okay, I understand better now.
https://github.com/godotengine/godot/commit/c7895ca22686bb0c6873f265273503bea93cd69d refactored https://github.com/godotengine/godot/pull/98758 in a way it supports asymmetrical frustums.

So this PR is the only remaining `get_viewport_half_extents()` that cause problems, and should completely fix the issue.

File: modules/raycast/raycast_occlusion_cull.h [hunk 4]
```diff
@@ -161,7 +161,8 @@ class RaycastOcclusionCull : public RendererSceneOcclusionCull {
 	bool _jitter_enabled = false;
 
 	void _init_embree();
-	Vector2 _jitter_half_extents(const Vector2 &p_half_extents, const Size2i &p_viewport_size);
+	Vector2 _get_jitter(const Vector2 &p_half_extents, const Size2i &p_viewport_size);
+	Rect2 _get_viewport_rect(const Projection &p_cam_projection) const;
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.h:165]:
```suggestion
```
Not needed as a member function. I would remove this completely.

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 5]
```diff
@@ -578,7 +578,17 @@ Vector2 RaycastOcclusionCull::_jitter_half_extents(const Vector2 &p_half_extents
 	// False shown can lower percentage that are occluded, and therefore performance.
 	jitter *= 0.66f;
 
-	return p_half_extents + jitter;
+	return jitter;
+}
+
+Rect2 RaycastOcclusionCull::_get_viewport_rect(const Projection &p_cam_projection) const {
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.cpp:584]:
```suggestion
Rect2 _get_viewport_rect(const Projection &p_cam_projection) {
```
I believe you can make it a free function in the .cpp. It's not that common across godot's codebase but given it has only one local use + it might be made obsolete by the other PR, it's probably a valid exception.

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 6]
```diff
@@ -525,14 +525,14 @@ void RaycastOcclusionCull::buffer_set_size(RID p_buffer, const Vector2i &p_size)
 	buffers[p_buffer].resize(p_size);
 }
 
-Vector2 RaycastOcclusionCull::_jitter_half_extents(const Vector2 &p_half_extents, const Size2i &p_viewport_size) {
+Vector2 RaycastOcclusionCull::_get_jitter(const Vector2 &p_half_extents, const Size2i &p_viewport_size) {
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.cpp:528]: Minor point, but you could keep the former function almost unchanged : 
- take the viewport's `Rect2` in place of the half extents
- return the jittered `Rect2`
- rename it `_jitter_viewport_rect` for clarity

It would reduce the diff by a lot.

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 7]
```diff
@@ -595,9 +605,11 @@ void RaycastOcclusionCull::buffer_update(RID p_buffer, const Transform3D &p_cam_
...
-	Vector2 viewport_half = p_cam_projection.get_viewport_half_extents();
-	Vector2 jitter_viewport_half = _jitter_half_extents(viewport_half, buffer.get_occlusion_buffer_size());
-	Vector3 near_bottom_left = Vector3(-jitter_viewport_half.x, -jitter_viewport_half.y, -p_cam_projection.get_z_near());
+	Rect2 vp_rect = _get_viewport_rect(p_cam_projection);
+	Vector2 viewport_half = vp_rect.get_size() * 0.5;
+	Vector2 bottom_left = vp_rect.position;
+	bottom_left += _get_jitter(viewport_half, buffer.get_occlusion_buffer_size());
+	Vector3 near_bottom_left = Vector3(bottom_left.x, bottom_left.y, -p_cam_projection.get_z_near());
 
 	buffer.update_camera_rays(p_cam_transform, near_bottom_left, 2 * viewport_half, p_cam_projection.get_z_far(), p_cam_orthogonal);
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.cpp:614]: Also minor comment : 
For code clarity it makes sense now to change `update_camera_rays()` definition so that it takes the viewport's `Rect2` directly instead of separated `Vector2`s

**Review by Flarkk — COMMENTED** [review]
I find it now in a pretty good shape speaking of the code. I left a few comments.

I didn't check it against the MRP yet.

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 7 above)
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp:614]: it's taking a Vector3 and a Vector2 :shrug:

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 6 above)
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp:528]: I think it's clearer when reading  if you just calculate the jitter in the function, then do the addition outside.
`bottom_left += _get_jitter(...)` is self-explaining. `rect = _jitter_viewport_rect(rect)` is less obvious.

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 8]
```diff
@@ -595,11 +605,12 @@ void RaycastOcclusionCull::buffer_update(RID p_buffer, const Transform3D &p_cam_
...
-	Vector2 viewport_half = p_cam_projection.get_viewport_half_extents();
-	Vector2 jitter_viewport_half = _jitter_half_extents(viewport_half, buffer.get_occlusion_buffer_size());
-	Vector3 near_bottom_left = Vector3(-jitter_viewport_half.x, -jitter_viewport_half.y, -p_cam_projection.get_z_near());
+	Rect2 vp_rect = _get_viewport_rect(p_cam_projection);
+	Vector2 bottom_left = vp_rect.position;
+	bottom_left += _get_jitter(vp_rect, buffer.get_occlusion_buffer_size());
+	Vector3 near_bottom_left = Vector3(bottom_left.x, bottom_left.y, -p_cam_projection.get_z_near());
 
-	buffer.update_camera_rays(p_cam_transform, near_bottom_left, 2 * viewport_half, p_cam_projection.get_z_far(), p_cam_orthogonal);
+	buffer.update_camera_rays(p_cam_transform, near_bottom_left, vp_rect.get_size(), p_cam_projection.get_z_far(), p_cam_orthogonal);
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.cpp:613]:
```suggestion
	buffer.update_camera_rays(p_cam_transform, near_bottom_left, vp_rect_jittered.get_size(), p_cam_projection.get_z_far(), p_cam_orthogonal);
```

File: modules/raycast/raycast_occlusion_cull.h [hunk 9]
```diff
@@ -161,7 +161,7 @@ class RaycastOcclusionCull : public RendererSceneOcclusionCull {
 	bool _jitter_enabled = false;
 
 	void _init_embree();
-	Vector2 _jitter_half_extents(const Vector2 &p_half_extents, const Size2i &p_viewport_size);
+	Vector2 _get_jitter(const Rect2 &p_viewport_rect, const Size2i &p_buffer_size);
```
Comment (Flarkk) [inline modules/raycast/raycast_occlusion_cull.h:164]:
```suggestion
	Rect2 _jitter_viewport(const Rect2 &p_viewport_rect, const Size2i &p_buffer_size) const;
```

**Review by Flarkk — COMMENTED** [review]
Last last round - please don't hate me, it's done with good intentions for the sake of code clarity.

Also I did it on my smartphone, so forgive any typo.

Thank you for your patience !

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 10]
```diff
@@ -525,14 +525,14 @@ void RaycastOcclusionCull::buffer_set_size(RID p_buffer, const Vector2i &p_size)
 	buffers[p_buffer].resize(p_size);
 }
 
-Vector2 RaycastOcclusionCull::_jitter_half_extents(const Vector2 &p_half_extents, const Size2i &p_viewport_size) {
+Vector2 RaycastOcclusionCull::_get_jitter(const Rect2 &p_viewport_rect, const Size2i &p_buffer_size) {
```
[the remark this answers is not in the document]
Comment (jamie-pate) [reply modules/raycast/raycast_occlusion_cull.cpp:528]: I disagree

**Comment by jamie-pate** [comment]
> Last last round - please don't hate me, it's done with good intentions for the sake of code clarity.
> 
> Also I did it on my smartphone, so forgive any typo.
> 
> Thank you for your patience !

I don't think this improves anything. (I previously commented but it probably got lost in the churn)

I believe `bottom_left += _get_jitter(...)` is more readable than the changes you are requesting.

**Comment by Flarkk** [comment]
Look, it's pretty much the same either way so it's fine by me if you don't make the change.

It's just that changing how the jitter is added doesn't contribute to the fix anymore.

**Review by Flarkk — APPROVED** [review]

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 11]
```diff
@@ -578,7 +578,17 @@ Vector2 RaycastOcclusionCull::_jitter_half_extents(const Vector2 &p_half_extents
 	// False shown can lower percentage that are occluded, and therefore performance.
 	jitter *= 0.66f;
 
-	return p_half_extents + jitter;
+	return jitter;
+}
+
+Rect2 _get_viewport_rect(const Projection &p_cam_projection) {
+	// TODO: this is proposed as a feature of Projection at https://github.com/godotengine/godot/pull/104311
```
Comment (akien-mga) [inline modules/raycast/raycast_occlusion_cull.cpp:585]: I would put that "TODO" in PR 104311 itself, not here. If that PR isn't merged then this TODO is just added noise.

File: modules/raycast/raycast_occlusion_cull.cpp [hunk 12]
```diff
@@ -578,7 +578,17 @@ Vector2 RaycastOcclusionCull::_jitter_half_extents(const Vector2 &p_half_extents
...
+	// NOTE: This assumes a rectangular projection plane, i.e. that :
```
Comment (akien-mga) [inline modules/raycast/raycast_occlusion_cull.cpp:586]:
```suggestion
	// NOTE: This assumes a rectangular projection plane, i.e. that:
```

File: modules/raycast/raycast_occlusion_cull.cpp (hunk 11 above)
Comment (Flarkk) [reply modules/raycast/raycast_occlusion_cull.cpp:585]: Just added the TODO in PR #104311

**Review by dsnopek — APPROVED** [review]
Thanks, this is working in my testing on Quest 3!

I think the code is fine as it is, even without Flarkk's suggested refactor to return `Rect2`. The priority at this point is fixing the regression - a re-organization can be discussed in a follow-up.

But I think the changes to the comments that Akien suggests should be made, so that if we don't change this, we don't end up with out-of-date comments

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by dsnopek** [comment]
While squashing, it would be nice if you could also rewrite the commit message to match the PR title - the message on the current 1st commit is out-of-date. Thanks!

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.4.1.
