### PR TITLE
Fix parameterised macros in core. Addresses #25488

### LINKED ISSUE #25488: Possible unintended behaviour with macro expansions in core/typedefs.h
https://github.com/godotengine/godot/blob/35bb52011a4cbcd8ca3779ab1761244f06a33127/core/typedefs.h#L138
This line doesn't have the safety braces for programmers who might like to write:
```cpp
SWAP(x++, y--);
```

This requires a simple fix by just surrounding the arguments with braces.

### PR DESCRIPTION
**Pull request by twaritwaikar**
This saves the programmer of doing something like SWAP(x++, y--)
and getting the wrong result unless the parameters are evaluated
before use.

Fixes #25488

### CODE REVIEW

File: core/math/geometry.cpp [hunk 1]
```diff
@@ -514,7 +514,7 @@ static inline void _build_faces(uint8_t ***p_cell_status, int x, int y, int z, i
 		Vector3(1,1,1),
 	};
 */
-#define vert(m_idx) Vector3((m_idx & 4) >> 2, (m_idx & 2) >> 1, m_idx & 1)
+#define vert(m_idx) Vector3(((m_idx) & 4) >> 2, ((m_idx) & 2) >> 1, (m_idx) & 1)
```
Comment (akien-mga) [inline core/math/geometry.cpp]: Apparently after this change, `clang-format` wants things formatted differently:
```diff
--- a/core/math/geometry.cpp	2019-01-30 19:51:42.607631131 +0000
+++ b/core/math/geometry.cpp	2019-01-30 19:51:52.104321095 +0000
@@ -514,7 +514,7 @@
 		Vector3(1,1,1),
 	};
 */
-#define vert(m_idx) Vector3(((m_idx) & 4) >> 2, ((m_idx) & 2) >> 1, (m_idx) & 1)
+#define vert(m_idx) Vector3(((m_idx)&4) >> 2, ((m_idx)&2) >> 1, (m_idx)&1)
 
 	static const uint8_t indices[6][4] = {
 		{ 7, 6, 4, 5 },

```

Seems bogus to me, but if it's the only occurrence, it's probably not worth fighting `clang-format` over it.

**Comment by IronicallySerious** [comment]
@akien-mga I have updated this to account for the `clang-format`

**Comment by akien-mga** [comment]
Thanks!
