### PR TITLE
GDScript: Fix brief/long description documentation comments

### LINKED ISSUE #63032: Brief/long description documentation comments aren't working properly
### Godot version

v4.0.alpha.custom_build [5fec0d232]

### System information

Arch on 5.18.10-arch1-1

### Issue description

```gdscript
extends Node

## Says Hello1.
##
## Method description here.
func hello1() -> void:
	print("Hello1")

## Says Hello2.
##
## Method description here.
func hello2() -> void:
	print("Hello2")

```

### Steps to reproduce

image

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by zerc**
[Issue](https://github.com/godotengine/godot/issues/63032)

It doesn't look nice but fixes the issue. Not sure if there are any side-effects I missed 🤔 

_Bugsquad edit: Fix #63032_

### CODE REVIEW

File: modules/gdscript/gdscript_parser.cpp [hunk 1]
```diff
@@ -3422,7 +3422,16 @@ void GDScriptParser::get_class_doc_comment(int p_line, String &p_brief, String &
...
 				break;
 			case DONE:
-				return;
+				break;
+		}
+	}
+	if (current_class->members.size() > 0) {
+		const ClassNode::Member &m = current_class->members[0];
+		int first_member_line = m.get_line();
+		if (first_member_line == line) {
```
Comment (zerc) [inline modules/gdscript/gdscript_parser.cpp:3431]: After `p_brief` and `p_desc` and `p_tutorials` are populated, `line` points to the next line. I compare it with the line of the first member of the class and if it's the same line - then discard the values populated because they belong to the member.

**Review by vnen — APPROVED** [review]
TBH I'm not super familiar with this code but the fix makes sense to me.

**Comment by akien-mga** [comment]
Please amend the commit message so that it actually says what it does (e.g. make it match the PR title).

**Comment by akien-mga** [comment]
Thanks!
