### PR TITLE
C#: Get singleton instances using the Core name

### LINKED ISSUE #74270: Using ResourceUid in C# gives error
### Godot version

4.0.stable.mono

### System information

Windows 10

### Issue description

When calling `ResourceUid.TextToId(text)` or `ResourceUid.IdToText(id)` in C# it causes this error:
```
Failed to retrieve non-existent singleton 'ResourceUid'.
  modules/mono/glue/runtime_interop.cpp:1303 - System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
     at Godot.NativeCalls.godot_icall_1_922(IntPtr method, IntPtr ptr, String arg1) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/NativeCalls.cs:line 8450
     at Godot.ResourceUid.TextToId(String textId) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/ResourceUid.cs:line 58
     at uidtest.set_Text(String value) in D:\Documents\Repos\Godot\CitrusOrchestra\uidtest.cs:line 14
     at uidtest.SetGodotClassPropertyValue(godot_string_name& name, godot_variant& value) in D:\Documents\Repos\Godot\CitrusOrchestra\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\uidtest_ScriptProperties.generated.cs:line 16
     at Godot.Bridge.CSharpInstanceBridge.Set(IntPtr godotObjectGCHandle, godot_string_name* name, godot_variant* value) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 57
```

### Steps to reproduce

Add script below to a node, build, and write some number in the Id property in inspector. See error in output.

### Minimal reproduction project

```CSharp
using Godot;
using System;

[Tool]
public partial class uidtest : Node
{
	[Export]
	public string Text
	{
		get => text;
		set
		{
			text = value;
			GD.Print(ResourceUid.TextToId(text));
		}
	}
	
	[Export]
	public long Id
	{
		get => id;
		set
		{
			id = value;
			GD.Print(ResourceUid.IdToText(id));
		}
	}

	private string text;
	private long id;
}
```

### PR DESCRIPTION
**Pull request by RedworkDE**
- Followup to https://github.com/godotengine/godot/pull/73882
- Fixes https://github.com/godotengine/godot/issues/74270

### CODE REVIEW

File: modules/mono/editor/bindings_generator.cpp [hunk 1]
```diff
@@ -1483,9 +1483,9 @@ Error BindingsGenerator::_generate_cs_type(const TypeInterface &itype, const Str
 
 		output << MEMBER_BEGIN "public static GodotObject " CS_PROPERTY_SINGLETON "\n" INDENT1 "{\n"
 			   << INDENT2 "get\n" INDENT2 "{\n" INDENT3 "if (singleton == null)\n"
-			   << INDENT4 "singleton = " C_METHOD_ENGINE_GET_SINGLETON "(typeof("
-			   << itype.proxy_name
-			   << ").Name);\n" INDENT3 "return singleton;\n" INDENT2 "}\n" INDENT1 "}\n";
+			   << INDENT4 "singleton = " C_METHOD_ENGINE_GET_SINGLETON "(\""
+			   << itype.cname
```
Comment (raulsntos) [inline modules/mono/editor/bindings_generator.cpp:1487]: Shouldn't it be `itype.name` like we use in the static `NativeName` field?

```suggestion
			   << itype.name
```

Comment (RedworkDE) [reply modules/mono/editor/bindings_generator.cpp:1487]: I am actually not sure whats the difference between those two, beyond that one is a `String` and the other a `StringName` I picked `cname` because you used `type_cname` in your PR and that was the closest thing available here and it gave the correct result.

Comment (raulsntos) [reply modules/mono/editor/bindings_generator.cpp:1487]: I think they are the same, probably to avoid converting between `String` and `StringName` multiple times.

In my PR, the `Engine::has_singleton` method takes a `StringName` so I used `cname`. In this case, since the `<<` operator takes a `String` it may be better to use `name` and avoid the conversion.

Comment (RedworkDE) [reply modules/mono/editor/bindings_generator.cpp]: Well, I tried both and they generate the exact same code, so I switched to avoid the unnecessary conversion and keep it in sync with the `NativeName`.

**Review by raulsntos — APPROVED** [review]
LGTM, but @neikeq may want to chime in about the difference between `itype.name` and `itype.cname` because I'm also a bit confused by it. We should probably add comments documenting them.

**Comment by neikeq** [comment]
Now that this is using the native name, it would be more appropriate to use the `NativeName` field and update `godotsharp_engine_get_singleton` to use StringName. But we can't do the latter without breaking compat (we could add a new native call, but it's not worth for this), so it will have to be in Godot 5.

`itype.name` and `itype.cname` are the same, but the former is a String and the latter StringName.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.
