### PR TITLE
C#: Fix errors when creating `Variant` from null array

### LINKED ISSUE #82362: Exporting NodePath as a C# array don't work
### Godot version

4.1.1 & 4.2-dev5

### System information

win10

### Issue description

The docs says it is possible to export NodePath in a native c# array, but in reality is not.
https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_exports.html#exporting-c-arrays

### Steps to reproduce

```cs
[Export] public NodePath[] NodePaths { get; set; }
```

And try to build you will receive a similar error message:
```
  modules/mono/glue/runtime_interop.cpp:1324 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.ArgumentNullException: Value cannot be null. (Parameter 'array')
     at Godot.Collections.Array..ctor(Span`1 array) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs:line 90
     at Godot.NativeInterop.VariantUtils.CreateFromSystemArrayOfNodePath(Span`1 from) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs:line 238
     at Project.Test.GetGodotPropertyDefaultValues() in ProjectPath\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\Project.Test_ScriptPropertyDefVal.generated.cs:line 11
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
     --- End of inner exception stack trace ---
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(Type type, IntPtr scriptPtr, IntPtr addDefValFunc) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 992
```

### Minimal reproduction project

easily reproducible

### LINKED ISSUE #89586: C# Array of StringNames Exported property with null default value causes null value exceptions in editor and in game.
### Tested versions

Reproducible in v4.2.1.stable.mono b09f793

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

When exporting a C# array of StringName objects with a null default value, null argument exceptions are thrown both in the editor and at runtime, unlike C# arrays of other reference or value types such as Resources or Vector2s. The exception is also not thrown when exporting a single StringName set to null or exporting a `Godot.Collections.Array<StringName>`.
```cs
[Export] public StringName[] ExportedArray;
```

The editor error in question:
```
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.ArgumentNullException: Value cannot be null. (Parameter 'array')
     at Godot.Collections.Array..ctor(Span`1 array) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs:line 87
     at Godot.NativeInterop.VariantUtils.CreateFromSystemArrayOfStringName(Span`1 from) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs:line 235
     at ExportArray.ExportArrayTest.GetGodotPropertyDefaultValues() in [[personal computer directory name omitted]]\ArrayTesting\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\ExportArray.ExportArrayTest_ScriptPropertyDefVal.generated.cs:line 18
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
     --- End of inner exception stack trace ---
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(Type type, IntPtr scriptPtr,  addDefValFunc) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 1052
```

### Steps to reproduce

Make a class extending from Node or Resource with the GlobalClass attribute and an exported property of type `StringName[]`. Upon building or running the project, the null argument exceptions are thrown.

```cs
using Godot;
namespace ExportArray;

[GlobalClass]
public partial class ExportArrayTest : Resource {
    [Export]
    public StringName[] ExportedArray;
}
```

### Minimal reproduction project (MRP)

[StringName Array Bug MRP.zip](https://github.com/godotengine/godot/files/14625219/StringName.Array.Bug.MRP.zip)

### PR DESCRIPTION
**Pull request by zaevi**
Returns default `Variant` (nil) if the `Span<*>` is null. 

This also adds the disposal of temporary array.

- Fix #89586
- Fix #82362

- Supersedes #82388

### CODE REVIEW

**Review by paulloz — COMMENTED** [review]
Good catch! I think this is fine, yep.

**Review by paulloz — APPROVED** [review]

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs [hunk 1]
```diff
@@ -235,13 +235,28 @@ public static godot_variant CreateFromPackedColorArray(Span<Color> from)
         }
 
         public static godot_variant CreateFromSystemArrayOfStringName(Span<StringName> from)
-            => CreateFromArray(new Collections.Array(from));
+        {
+            if (from == null)
```
Comment (raulsntos) [inline modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs:239]: This looks weird to me, Spans are value types so they can't be null. The only reason why they can be compared to null is because there is an implicit conversion from arrays to spans and the `null` literal can be converted to array so basically this is doing this:

```csharp
if (from == (Span<StringName>)((StringName[])null))
    return default;
```

Which means this also returns a default `Variant` for empty arrays and I'm not sure we want that.

**Review by raulsntos — CHANGES_REQUESTED** [review]
Thanks for the contribution, I'd like to understand the PR a bit better before approving.

> Returns default `Variant` (nil) if the `Span<*>` is null.

I'm not sure what you mean by this, Spans can't be null because they are value types. Can you explain why this change is needed? Do empty arrays work before/after this PR?

The current issue is probably because of checks like:

https://github.com/godotengine/godot/blob/fe01776f05b1787b28b4a270d53037a3c25f4ca2/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs#L88-L91

I imagine this was a copy-paste mistake. But then `Array.Empty<StringName>()` should throw as well.

File: modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs (hunk 1 above)
Comment (zaevi) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs:239]: It's ok because for **empty** arrays, the span won't be null (as its `_pointer` points to that array). So, it returns default `Variant` only when the array is **null**.

Comment (raulsntos) [reply modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs:239]: That's true, I was thinking whether we should allow creating `Godot.Array` from null but on second thought I think the changes in this PR are more _correct_.

**Review by raulsntos — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
