### PR TITLE
Fix "reparent to new node" not remembering index

### LINKED ISSUE #1652: "Reparent to New Node" moves node unexpectedly in single-branch case.
**Describe the project you are working on:**
Docs for a Node Flexibility demonstration.

**Describe the problem or limitation you are having in your project:**
I was demonstrating the features available for manipulating node trees. "Reparent" I was used to, and it worked exactly as I suspected (similar to clicking and dragging a node). However, then I tried the "Reparent to New Node" option. I thought, "Okay, this is going to just replace my selected node with the node I'm adding, and then make the selected node its child." So I did it, and all of a sudden, my node jumped to the bottom of the list. *surprised pikachu face*

What I started with:

flexibility_lighted_area

What I selected (choosing Camera2D):

flexibility_reparent_new_node

What I thought I would get:

flexibility_reparent_new_node_result

What I actually got:

flexibility_reparent_new_node_result_actual

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The behavior as it currently is makes perfect sense when you've selected multiple nodes in different subtrees and are reparenting all of the selected subtrees to a new node in a new subtree. This is the "multi-top-node" case that the source code accounts for. However, it leads to rather bizarre behavior when there is only one branch involved.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

In the case where there is only one top node in the selection, keep track of its indexed position relative to its siblings. After creating the new node, move it to that position. I have a PR solution ready-to-go.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

I'm honestly not sure how often people use this utility, as I don't really use Godot all that much (yet), but it definitely threw me for a loop the first time I tried it, and I'll bet I'm not the only one. You *can* just move the node after-the-fact, but it still *feels* like a bug. In fact, I almost opened this as a bug report, but I think it's still *technically* an enhancement since everything is functioning as it should in a literal sense.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Requires internal changes to SceneTreeDock class in editor source code.

### LINKED ISSUE #5427: Prevent changing node order when reparenting nodes
### Describe the project you are working on

Just another 2D game.
(This issue post isn't specific to any of my current Godot projects.)

### Describe the problem or limitation you are having in your project

(similar issue post: https://github.com/godotengine/godot-proposals/issues/1652)

This issue post pertains to fundamental scene tree ui behavior in the editor - basically a ux complaint I have.

When reparenting one or more nodes, the newly reparented node(s) are sent to the bottom of their siblings in the hierarchy.
This can be inconvenient because then manually re-ordering the newly parented nodes is almost always necessary.

Can efforts be made to try to leave the newly reparented nodes as close as possible to their pre-reparented place in the hierarchy?

In cases where a random selection of nodes from all over the scene tree are reparented, I can understand the newly reparented nodes needing to be moved to an arbitrary place in the hierarchy, but this happens even when only one node is being reparented.

_Screen recording of two adjacent sibling nodes being reparented:_
https://www.youtube.com/watch?v=7ZhjoytNk2c

^ Here I'm selecting two adjacent siblings and reparenting them. They're sent to the bottom of their siblings level instead of staying place.
After reparenting, I use Undo and Redo to show that reparenting is actually doing two operations - it creates the new parent node at the bottom of the current hierarchy level then the selected nodes are nested as children.
Notice how the water caustics animations need to be moved back to their intended place so the draw order is correct.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Normally, I avoid the Reparent feature because of this. Instead, I'll add the new parent node manually, move it into place, then nest whichever nodes under it I need to.

If Reparent could be a little more intuitive and not arbitrarily add the new parent node at the bottom of the current node level it could save on time and frustration.

Can the editor recognize the lowest selected node when reparenting and spawn the new parent at that lowest node's place in the scene tree? Instead of all the way to the bottom of the current tree level.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

No. I'm trying to suggest a basic quality-of-life improvement for a specific scene tree behavior in the editor.

### PR DESCRIPTION
**Pull request by RedMser**
Supersedes #42730
Fixes https://github.com/godotengine/godot-proposals/issues/1652, fixes https://github.com/godotengine/godot-proposals/issues/5427

https://github.com/godotengine/godot/assets/5117197/e2526753-5571-4d63-9056-9b5f620f0fb5

Also merges the operation into a single undo step.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I did not debug too deeply, but the first error likely comes from here:
https://github.com/godotengine/godot/blob/c495eb5102278a110c14bbffbf833ed436d1594d/editor/scene_tree_dock.cpp#L2318
Since the action is nested, the commit will take no effect and the node is still outside the scene tree. Maybe adding an `is_inside_tree()` condition would be sufficient.

The other error comes from
https://github.com/godotengine/godot/blob/c495eb5102278a110c14bbffbf833ed436d1594d/editor/scene_tree_dock.cpp#L2415
Also caused by the node not being inside scene tree.

**Comment by YuriSizov** [comment]
@RedMser Will you be able to look into what's discussed above?

**Comment by RedMser** [comment]
Rebased and included the suggested fixes in a second commit, so it's easier to review.

Reparenting a MeshInstance3D causes a lot of these errors: `Node not found: "../../root/@EditorNode@17140/@Panel@13/@VBoxContainer@14/@HSplitContainer@17/@HSplitContainer@25/@HSplitContainer@33/@VBoxContainer@34/@VSplitContainer@36/@VSplitContainer@62/@VBoxContainer@63/@PanelContainer@110/MainScreen/@CanvasItemEditor@9462/@VSplitContainer@9281/@HSplitContainer@9283/@HSplitContainer@9285/@Control@9286/@SubViewportContainer@9287/@SubViewport@9288/Node/MeshInstance3D" (relative to ...`

which comes from a `_notification` call of type `NOTIFICATION_ENTER_TREE`. So something seems pretty wrong here still, and these is_inside_tree checks I added are likely not a proper fix.

Sorry I don't have much time to work on this lately, but I hope it can be resolved and fixed for 4.3

**Comment by KoBeWi** [comment]
The errors are caused due to updating NodePath properties. It seems to happen with other nodes too, e.g. I tried reparenting AnimationPlayer and ended with this:
image
Not sure why is that.

**Comment by RedMser** [comment]
Well, I got the PR into a better state than it previously was.

I moved any logic that relied on the node already being added to the scene tree, and put it into `add_do_method "_post_do_create"`

No errors anymore from my testing, and NodePath in AnimationPlayer is properly updated, however this did break "Reparent to New Node" no longer working in live reloading context. I wrote a TODO comment, best solution I can think of is custom do/undo methods so that the paths are evaluated only once child was added, but this all feels really hacky and not worth it...

**Review by KoBeWi — APPROVED** [review]
It works correctly now.
But as you noted, it breaks live edit for Reparent to New Node, while it was functional before. I think it's less important than the linked issues though.

File: editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -2354,8 +2353,12 @@ void SceneTreeDock::_do_reparent(Node *p_new_parent, int p_position_in_parent, V
 			}
 		}
 
-		undo_redo->add_do_method(ed, "live_debug_reparent_node", edited_scene->get_path_to(node), edited_scene->get_path_to(new_parent), new_name, new_position_in_parent);
-		undo_redo->add_undo_method(ed, "live_debug_reparent_node", NodePath(String(edited_scene->get_path_to(new_parent)).path_join(new_name)), edited_scene->get_path_to(node->get_parent()), node->get_name(), node->get_index(false));
+		// TODO: Live reloading of "Reparent to New Node" is broken.
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:2356]:
```suggestion
		// TODO: Live editing for "Reparent to New Node" option is broken.
```

**Comment by akien-mga** [comment]
Thanks!

File: editor/scene_tree_dock.cpp [hunk 2]
```diff
@@ -2922,22 +2929,24 @@ void SceneTreeDock::_create() {
 		}
 
 		Node *parent = nullptr;
+		int original_position = -1;
 		if (only_one_top_node) {
 			parent = top_node->get_parent();
+			original_position = top_node->get_index();
```
Comment (kleonc) [inline editor/scene_tree_dock.cpp:2935]: @RedMser This should be `original_position = top_node->get_index(false);`, as `move_child` takes in an index not accounting for internal nodes.

Here's an example of it failing for TabContainer (which has front-internal TabBar child):
godot windows editor x86_64_IqOzGwV6GD
After `First` -> `Reparent to New Node...`:
godot windows editor x86_64_NDmkEd7XBO
Correct result (currently only if parent has no internal children):
godot windows editor x86_64_z8THw1XRG6

Comment (RedMser) [reply editor/scene_tree_dock.cpp:2935]: Ah I see. Would you like to create a followup PR to fix this, or should I do so?

Comment (kleonc) [reply editor/scene_tree_dock.cpp:2935]: Go ahead! :slightly_smiling_face:

Comment (RedMser) [reply editor/scene_tree_dock.cpp:2935]: Done, thanks for the info!
https://github.com/godotengine/godot/pull/96646

**Comment by kleonc** [comment]
Note: should be cherry-picked together with #96646.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
