### PR TITLE
Don't stop closing on unsaved script

### LINKED ISSUE #46649: Can't close all scripts if some are unsaved
**Godot version:**

3.2.4 rc3 / dd1881a

**Issue description:**

When there is an unsaved script on your script list, using Close All or Close Others will stop on that script. The unsaved dialog will interrupt closing scripts, so you have to use it again.

This is especially problematic with built-in scripts, which tend to ask you to save changes even if they are unmodified.

**Steps to reproduce:**
1. Open few scripts
2. Modify 1 of them (or 2 for best effect)
3. Right click script list and Close All
4. Not all scripts are closed, because of the dialog

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #46649

### CODE REVIEW

File: editor/plugins/script_editor_plugin.h [hunk 1]
```diff
@@ -308,6 +308,7 @@ class ScriptEditor : public PanelContainer {
 	int history_pos;
 
 	List<String> previous_scripts;
+	List<int> script_close_queue;
```
Comment (Paulb23) [inline editor/plugins/script_editor_plugin.h:311]: Any reason why this can't be an argument to `_queue_close_tabs`?

Comment (KoBeWi) [reply editor/plugins/script_editor_plugin.h:311]: `_queue_close_tabs()` is interrupted by the dialog, which is asynchronous.

Comment (Paulb23) [reply editor/plugins/script_editor_plugin.h:311]: Can we pass it through the connection arg list?

Comment (KoBeWi) [reply editor/plugins/script_editor_plugin.h:311]: Hmm, actually it should be possible.

Comment (KoBeWi) [reply editor/plugins/script_editor_plugin.h:311]: Ok so I tried the connection arg approach and it has a few problems. It can't take List, so I had to change the close queue to Vector, which is very wasteful for this case (especially the `pop_front()`). The worst part is that it doesn't actually work xd It compiles and closes the scripts, but in some cases some scripts are not being closed.

IMO having a helper variable in class is fine, if it simplifies the code and avoids problems. Changing it isn't really worth it.

Comment (Paulb23) [reply editor/plugins/script_editor_plugin.h:311]: Ah that's shame, looks all good in that case.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
