### PR TITLE
GDScript default argument override bug fix

### LINKED ISSUE #41766: Default values given in GDScript function declarations overriding anything else.
**Godot version:** Godot Engine v4.0.dev.custom_build. 5c4dffe7c

**Issue description:** I have a function `add_sound_to_library` in `sound_player` with two arguments, `sound_file` and `sound_name`. By default, `sound_name` reverts to `""` if nothing is supplied for it. `func add_sound_to_library (sound_file, sound_name = "") -> void`

However: `sound_player.add_sound_to_library ("res://Assets/Audio/Sound/ring_get.ogg", "ring_get")` does not work as expected. The name given here is ignored, and instead the function uses the default given. This can also be seen in the `play_sound` function.

**Minimal reproduction project:**

[41766_Demonstrator.zip](https://github.com/godotengine/godot/files/5175071/41766_Demonstrator.zip)

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #41766

### CODE REVIEW

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -1742,6 +1742,7 @@ Error GDScriptCompiler::_parse_function(GDScript *p_script, const GDScriptParser
 				}
 				GDScriptCodeGenerator::Address dst_addr = codegen.parameters[parameter->identifier->name];
 				codegen.generator->write_assign(dst_addr, src_addr);
+				codegen.generator->set_default_parameter();
```
Comment (vnen) [inline modules/gdscript/gdscript_compiler.cpp:1745]: I don't like this interface. A `set_*()` method without arguments is odd, hard to tell what it does.

In this case, I would prefer to create a function called `write_assign_default_parameter(Address dst, Address src)` and then replace the `write_assign()` call. This function could do what `set_default_parameter()` does then just call `write_assign` internally.

This will make more sense for other generators added in the future.

P.S. sorry for the delay reviewing this.

**Review by vnen — CHANGES_REQUESTED** [review]
The changes make sense but I feel like the change in the CodeGen API is a bit confusing.

File: modules/gdscript/gdscript_compiler.cpp (hunk 1 above)
Comment (ThakeeNathees) [reply modules/gdscript/gdscript_compiler.cpp]: @vnen done!

**Review by vnen — APPROVED** [review]

**Comment by vnen** [comment]
Thanks!
