### PR TITLE
Fix path with multiple slashes not being corrected on templates

### LINKED ISSUE #52507: Paths with "//" instead of "/" works in editor but not in export
### Godot version

3.3.3.stable

### System information

Manjaro 21.1.1 Pahvo, GLES2, Radeon RX 5500 XT (NAVI14, DRM 3.40.0, 5.10.60-1-MANJARO, LLVM 12.0.1)

### Issue description

If you use "//" in file name instead of "/" while in editor and run - all works fine.
If you export project - it would won't work anymore.

Accidentally hit this issue because I was constructing file path with string operations.

### Steps to reproduce

1) Use "//" instead of "/" in address on file, like "res://folder//folder//folder//icon.png"
2) use this address to load() something
3) It would work while running from editor
4) It won't work after export

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/7132792/New.Game.Project.zip)

### PR DESCRIPTION
**Pull request by rsubtil**
Fixes #52507

Paths with multiple slashes like `res://folder//folder//folder//icon.png` were not being simplified on export templates because these load from PCK files, and thus `resource_path` is never set.

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -55,11 +55,7 @@ String ProjectSettings::get_resource_path() const {
 const String ProjectSettings::IMPORTED_FILES_PATH("res://.godot/imported");
 
 String ProjectSettings::localize_path(const String &p_path) const {
-	if (resource_path == "") {
-		return p_path; //not initialized yet
-	}
-
-	if (p_path.begins_with("res://") || p_path.begins_with("user://") ||
+	if (resource_path == "" || p_path.begins_with("res://") || p_path.begins_with("user://") ||
```
Comment (kdiduk) [inline core/config/project_settings.cpp:58]: [Cosmetic] Wouldn't it be better to change the first condition `resource_path == ""` into `resource_path.is_empty`? 
```
if (resource_path.is_empty() || p_path.begins_with("res://") || p_path.begins_with("user://") ||
```

Comment (Ev1lbl0w) [reply core/config/project_settings.cpp:58]: Yes, it's also more efficient, thanks for the tip :+1:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.
