### PR TITLE
Prevent infinite recursion during printing

### LINKED ISSUE #108838: `StringName` errors can cause stack overflow through infinite recursion
### Tested versions

- Reproducible in: 4.5.beta [71a9948157dc2d5cc71fcb456c9d96656678757d]
- Not reproducible in: 4.4.1.stable

### System information

Godot v4.5.beta (71a994815) - Fedora Linux 42 (Adams) on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 9070 XT (RADV GFX1201) - AMD Ryzen 9 9950X3D 16-Core Processor (32 threads) - 60.39 GiB memory

### Issue description

In short, because we now (as of #91006) have a way for things like `ERR_FAIL_COND` and other error macros to create a `StringName` as part of its error printing, the errors found in the `StringName` class itself can (and do) cause a stack overflow through infinite recursion when actually emitted.

The call stack (for 2 recursions) looks something like this:

```
StringName::unref() (core/string/string_name.cpp:113)
StringName::operator=(StringName const&) (core/string/string_name.cpp:190)
Array::set_typed(unsigned int, StringName const&, Variant const&) (core/variant/array.cpp:885)
TypedArray<ScriptBacktrace>::TypedArray() (core/variant/typed_array.h:61)
TypedArray<ScriptBacktrace>::TypedArray() (core/variant/typed_array.h:60)
CoreBind::OS::LoggerBind::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType, Vector<Ref<ScriptBacktrace>> const&) (core/core_bind.cpp:272)
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType, Vector<Ref<ScriptBacktrace>> const&) (core/io/logger.cpp:259)
_err_print_error(char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) (core/error/error_macros.cpp:95)
_err_print_error(char const*, char const*, int, char const*, bool, ErrorHandlerType) (core/error/error_macros.cpp:85)
StringName::unref() (core/string/string_name.cpp:114)
StringName::operator=(StringName const&) (core/string/string_name.cpp:190)
Array::set_typed(unsigned int, StringName const&, Variant const&) (core/variant/array.cpp:885)
TypedArray<ScriptBacktrace>::TypedArray() (core/variant/typed_array.h:61)
TypedArray<ScriptBacktrace>::TypedArray() (core/variant/typed_array.h:60)
CoreBind::OS::LoggerBind::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType, Vector<Ref<ScriptBacktrace>> const&) (core/core_bind.cpp:272)
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType, Vector<Ref<ScriptBacktrace>> const&) (core/io/logger.cpp:259)
_err_print_error(char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) (core/error/error_macros.cpp:95)
_err_print_error(char const*, char const*, int, char const*, bool, ErrorHandlerType) (core/error/error_macros.cpp:85)
StringName::unref() (core/string/string_name.cpp:114)
StringName::operator=(StringName const&) (core/string/string_name.cpp:190)
Array::set_typed(unsigned int, StringName const&, Variant const&) (core/variant/array.cpp:885)
TypedArray<ScriptBacktrace>::TypedArray() (core/variant/typed_array.h:61)
TypedArray<ScriptBacktrace>::TypedArray() (core/variant/typed_array.h:60)
CoreBind::OS::LoggerBind::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType, Vector<Ref<ScriptBacktrace>> const&) (core/core_bind.cpp:272)
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, bool, Logger::ErrorType, Vector<Ref<ScriptBacktrace>> const&) (core/io/logger.cpp:259)
_err_print_error(char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType) (core/error/error_macros.cpp:95)
_err_print_error(char const*, char const*, int, String const&, bool, ErrorHandlerType) (core/error/error_macros.cpp:89)
PagedAllocator<Variant::Pools::BucketMedium, true, 4096u>::~PagedAllocator() (core/templates/paged_allocator.h:169)
```

It's possible that this could have happened even before #91006 as well, but I'll label this a regression for now.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

Unfortunately I have not been successful in making an MRP for this, but I hope the call stack speaks for itself.

### PR DESCRIPTION
**Pull request by mihe**
Fixes #108838.
Supersedes #108839.

This introduces a reentrancy guard to `_err_print_error`, and another reentrancy guard to cover `__print_line`, `__print_line_rich` and `print_error`, which is meant to prevent cases where we (deliberately or not) emit an error from within a logger, or print from within a logger, thus causing infinite recursion.

In such cases we would now fall back on using `fprintf` instead.

I also removed an already existing reentrancy guard in `CoreBind::OS::LoggerBind`, which I added as part of #91006 to achieve the same effect, albeit more localized.

### CODE REVIEW

File: core/error/error_macros.cpp [hunk 1]
```diff
@@ -91,12 +100,21 @@ void _err_print_error(const char *p_function, const char *p_file, int p_line, co
 
 // Main error printing function.
 void _err_print_error(const char *p_function, const char *p_file, int p_line, const char *p_error, const char *p_message, bool p_editor_notify, ErrorHandlerType p_type) {
+	if (is_printing_error) {
+		// Fallback if we're already printing an error, to prevent infinite recursion.
+		const char *err_details = (p_message && *p_message) ? p_message : p_error;
+		_err_print_fallback(p_function, p_file, p_line, err_details, p_type);
+		return;
```
Comment (Ivorforce) [inline core/error/error_macros.cpp]: Maybe we should additionally print that it's a fallback? 
I think python does something like "During handling this exception, another exception occurred". 

```suggestion
		// Fallback if we're already printing an error, to prevent infinite recursion.
		const char *err_details = (p_message && *p_message) ? p_message : p_error;
		_err_print_fallback(p_function, p_file, p_line, err_details, p_type);
		_err_print_fallback(p_function, p_file, p_line, "(error occurred during printing, recovering by falling back to default pipe)", ERR_HANDLER_ERROR);
		return;
```

Edit: Since we have a bunch of these calls, maybe add it to the fallback?

**Review by Ivorforce — APPROVED** [review]
I didn't test, but this makes a lot of sense to me.

As discussed in the earlier PR, we can expect for infinite recursions to occur again and again, especially during development. We should really have a robust fallback.

`thread_local` notably incurs some cost, but given that printing is not performance critical (and costly anyway), it should be acceptable.

File: core/error/error_macros.cpp (hunk 1 above)
Comment (mihe) [reply core/error/error_macros.cpp]: Yeah, that's a good idea. I'll just add it to the format strings in the fallback functions.

Comment (mihe) [reply core/error/error_macros.cpp]: There. I toyed around with making it fancier using indentation and stuff, but it got too messy. This should be clear enough. It's not supposed to happen in the first place anyway.

**Comment by mihe** [comment]
If anyone wants to try it for themselves, this MRP should (only with this PR) force the recursion to happen and thus show these new fallback messages in the terminal output: [logger_recursion_2025-07-22_13-58-04.zip](https://github.com/user-attachments/files/21366382/logger_recursion_2025-07-22_13-58-04.zip)

**Comment by Ivorforce** [comment]
I tested with the reproducer. I didn't get an infinite recursion on master (71a9948157dc2d5cc71fcb456c9d96656678757d) (but I did get a single recursion, perhaps this is what you wanted to test?).

Instead, the `master` implementation printed two errors:

```
 ❯ bin/godot.macos.editor.arm64.master --path /Users/lukas/Downloads/logger-recursion/
Godot Engine v4.5.beta.custom_build.71a994815 (2025-07-18 16:05:19 UTC) - https://godotengine.org
Metal 3.2 - Forward+ - Using Device #0: Apple - Apple M1 Max (Apple7)

Just printing normally from _enter_tree
Trying to print normally from _log_message
Trying to print rich from _log_message
Just printing rich from _enter_tree
Trying to print normally from _log_message
Trying to print rich from _log_message
ERROR: Printing an error from _enter_tree
   at: push_error (core/variant/variant_utility.cpp:1024)
   GDScript backtrace (most recent call first):
       [0] _enter_tree (res://main.gd:18)
ERROR: Trying to log an error from _log_error
   at: push_error (core/variant/variant_utility.cpp:1024)
   GDScript backtrace (most recent call first):
       [0] _log_error (res://main.gd:12)
       [1] _enter_tree (res://main.gd:18)
2025-07-22 15:23:56.558 godot.macos.editor.arm64.master[35078:41616486] +[IMKClient subclass]: chose IMKClient_Modern
2025-07-22 15:23:56.630 godot.macos.editor.arm64.master[35078:41616486] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

The new implementation printed a bunch of fallback errors, and falls back for the second error message:

```
 ❯ bin/godot.macos.editor.arm64 --path /Users/lukas/Downloads/logger-recursion/
Godot Engine v4.5.beta.custom_build.7a4509556 (2025-07-22 11:58:33 UTC) - https://godotengine.org
Metal 3.2 - Forward+ - Using Device #0: Apple - Apple M1 Max (Apple7)

Just printing normally from _enter_tree
Unable to print the following message, due to printing another message:
Trying to print normally from _log_message
Unable to print the following message, due to printing another message:
Trying to print rich from _log_message
Just printing rich from _enter_tree
Unable to print the following message, due to printing another message:
Trying to print normally from _log_message
Unable to print the following message, due to printing another message:
Trying to print rich from _log_message
ERROR: Printing an error from _enter_tree
   at: push_error (core/variant/variant_utility.cpp:1024)
   GDScript backtrace (most recent call first):
       [0] _enter_tree (res://main.gd:18)
Unable to print the following error, due to printing another error:
ERROR: Trying to log an error from _log_error
   at: push_error (core/variant/variant_utility.cpp:1024)
2025-07-22 15:24:08.465 godot.macos.editor.arm64[35225:41617391] +[IMKClient subclass]: chose IMKClient_Modern
2025-07-22 15:24:08.560 godot.macos.editor.arm64[35225:41617391] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

One thing I'm noting is that there is no "following error" in the last example. It's particularly unclear to me which is the "following error" and which is the "another error".

I have a third proposition for the message, what do you think? "While attempting to print an error, another error was printed:"

**Comment by mihe** [comment]
> I didn't get an infinite recursion on master ([71a9948](https://github.com/godotengine/godot/commit/71a9948157dc2d5cc71fcb456c9d96656678757d))

On `master` you'd be covered by the reentrancy guard that this PR removes from `CoreBind::OS::LoggerBind`, which just does an early-out for the script-based loggers, so you won't get any infinite recursion there when dealing with script-based loggers specifically.

The MRP was mostly just an easy way to test these new fallbacks, now that the reentrancy guard in `CoreBind::OS::LoggerBind` is gone.

> One thing I'm noting is that there is no "following error" in the last example. It's particularly unclear to me which is the "following error" and which is the "another error".

Fair enough. That does indeed read a bit weird.

> I have a third proposition for the message, what do you think? "While attempting to print an error, another error was printed:"

Done! That does indeed read better.

**Review by Ivorforce — APPROVED** [review]
Re-approving after changes. Should be good to merge now!

**Review by Calinou — APPROVED** [review]
Tested locally with the MRP from https://github.com/godotengine/godot/pull/108860#issuecomment-3102421600, it works as expected. Code looks good to me.

```
Just printing normally from _enter_tree
While attempting to print a message, another message was printed:
Trying to print normally from _log_message
While attempting to print a message, another message was printed:
Trying to print rich from _log_message
Just printing rich from _enter_tree
While attempting to print a message, another message was printed:
Trying to print normally from _log_message
While attempting to print a message, another message was printed:
Trying to print rich from _log_message
ERROR: Printing an error from _enter_tree
   at: push_error (./core/variant/variant_utility.cpp:1024)
   GDScript backtrace (most recent call first):
       [0] _enter_tree (res://main.gd:18)
While attempting to print an error, another error was printed:
ERROR: Trying to log an error from _log_error
   at: push_error (./core/variant/variant_utility.cpp:1024)
```

Note that the recursion messages are not colored according to their type (i.e. errors appear as plain text, not red). This could probably be added later on unless there's a good reason not to do it.

Recursion messages also won't appear in the editor Output panel, but I don't think anything can be done about that.

**Comment by Ivorforce** [comment]
> Recursion messages also won't appear in the editor Output panel, but I don't think anything can be done about that.

I think we don't _want_ these messages to appear in the editor. Getting them there risks more recursion, and you really don't want more risks in your fallback.

**Comment by Repiteo** [comment]
Thanks!

**Comment by mihe** [comment]
I don't know if it makes any real difference, but with this being merged we might want to re-evaluate the `fprintf` that were added in #85397 and #89490 (CC @AThousandShips), since this should presumably be able to cover all of those as well.
