### PR TITLE
Fix Popup submenu in single-window mode

### LINKED ISSUE #50734: Popup submenu won't close and allows for a sibling submenu if the pointer has entered it at least once (DisplayServer regression)
### Godot version

v4.0.dev.custom_build [6b1886f99] (checked that not on 3.3)

### System information

Arch Linux (kernel 5.12.15-arch1-1, X11), WM: at least on GNOME (default session, wayland with xwayland) and dwm

### Issue description

If one hovers onto submenu, then hovers back to parent, then CLICKS (important) to open second submenu, the second submenu opens without closing the first one. Clicking is needed because even though the first submenu opens on hover, the second submenu cannot open on hover.

This DOES happen is SingleWindowMode, but because of #50529 you need to hover onto a submenu quickly before it closes by itself. (It is not too hard ^_^).

On gifs, i first demonstrate the delay between me hovering off the submenu button and the parent regaining focus. It will not regain focus until the submenu is hidden (which happens with a delay). One can see the focus because it highlights buttons that are hovered over.
Secondly, i demonstrate the bug itself. Notice how the focus is NOT transferred back to parent when i hover back from the submenu to the parent, and how the submenu is NOT autoclosing anymore. 

double_submenu

Log (dwm, multiwindow mode). Notice that focus is not transferred to parent on hover back. 

```
[665] ButtonPress window=20971522 (0), button_index=1 (click to open parent menu) 
window_set_transient: 20971623 (1), prev_parent=4294967295, parent=0
show_window: 20971623 (1) 
[666] MapNotify window=20971623 (1) 
[666] VisibilityNotify window=20971623 (1), state=0 
[666] VisibilityNotify window=20971522 (0), state=1 
[666] Expose window=20971623 (1), count='0' 
[671] FocusOut window=20971522 (0), mode='0' 
[671] FocusIn window=20971623 (1), mode='0' 
[680] ButtonRelease window=20971522 (0), button_index=1 
[832] LeaveNotify window=20971522 (0), mode='0' 
[832] EnterNotify window=20971623 (1), mode='0' 
(hover on 1st submenu)
window_set_transient: 20971633 (2), prev_parent=4294967295, parent=1
show_window: 20971633 (2) 
[928] MapNotify window=20971633 (2) 
[928] VisibilityNotify window=20971633 (2), state=0 
[928] Expose window=20971633 (2), count='0' 
[929] FocusOut window=20971623 (1), mode='0' 
[929] FocusIn window=20971633 (2), mode='0' 

(moving pointer to 1st submenu)
[1042] LeaveNotify window=20971623 (1), mode='0' 
[1042] EnterNotify window=20971633 (2), mode='0' 

(and back)
[1129] LeaveNotify window=20971633 (2), mode='0' 
[1129] EnterNotify window=20971623 (1), mode='0' 
(no focus transferred back to 1 on enter)

(pressing submenu button to open 2nd submenu. It won't open onjust hover)
[1356] ButtonPress window=20971623 (1), button_index=1 
window_set_transient: 20971643 (3), prev_parent=4294967295, parent=1
show_window: 20971643 (3) 
[1357] FocusOut window=20971633 (2), mode='0' 
[1357] FocusIn window=20971623 (1), mode='0' 
[1357] MapNotify window=20971643 (3) 
[1357] VisibilityNotify window=20971643 (3), state=0 
[1357] Expose window=20971643 (3), count='0' 
[1358] FocusOut window=20971623 (1), mode='0' 
[1358] FocusIn window=20971643 (3), mode='0' 
[1378] ButtonRelease window=20971623 (1), button_index=1 
```

### Steps to reproduce

* Make a new empty project (or open any other project you have)
* Open a menu with 2 or more submenus from the topbar
* Hover onto submenu
* Hover back to the parent menu
* CLICK (important) to open a second submenu.

### Minimal reproduction project

New empty project is good enough.

### PR DESCRIPTION
**Pull request by JFonS**
The internal processing code only works for OS windows, since it takes the mouse position relative to the window and not the viewport. 

Now we make sure it's not called in single-window mode.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by KoBeWi** [comment]
Your changes to tooltips is basically what I did in #43693 :/

**Comment by JFonS** [comment]
@KoBeWi I didn't know about that PR, I got to similar changes for different reasons.

As long as `Viewport` doesn't use internal processing the issue I was looking into should be solved. Once #43693 is merged I can rebase this PR to keep only the changes in Popup.

**Comment by akien-mga** [comment]
Can now be rebased.

File: scene/main/viewport.cpp [hunk 1]
```diff
@@ -3781,13 +3769,23 @@ Viewport::Viewport() {
...
+	gui.tooltip_timer->set_one_shot(true);
+	gui.tooltip_timer->connect("timeout", callable_mp(this, &Viewport::_gui_show_tooltip));
+	add_child(gui.tooltip_timer);
+
 	set_sdf_oversize(sdf_oversize); //set to server
 }
 
 Viewport::~Viewport() {
+	if (gui.tooltip_timer) {
+		gui.tooltip_timer->queue_delete();
```
Comment (qarmin) [inline scene/main/viewport.cpp:3786]: This node is already child of viewport and doesn't need to be deleted(this line cause invalid read in CI - https://github.com/godotengine/godot/runs/3144902320?check_suite_focus=true)

Comment (KoBeWi) [reply scene/main/viewport.cpp:3786]: This code is no longer relevant, see #43693

Comment (JFonS) [reply scene/main/viewport.cpp]: Yup, rebase without the changes, but still good to know for other cases :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
