### PR TITLE
[macOS] Fix wrong object type in joypad queue.

### LINKED ISSUE #95365: NSException: Joypad playerIndex
### Tested versions

Godot 4.3rc3.

### System information

Mac M1, macOS 14.5, Logitech Gamepad F310

### Issue description

I can get a ton of errors in 4.3rc3. Sometimes at startup it will freeze with gamepad plugged in. Other times it will start project fine then sometimes when I go to play the game it'll freeze up and display these errors run: NSException: -[Joypad playerIndex]: unrecognized selector sent to instance 0x6000037fc990

Did not see this is issue in rc2. 

Screenshot 2024-08-10 at 12 28 37

### Steps to reproduce

Not sure if just happens when the Logitech F310 is plugged in.

### Minimal reproduction project (MRP)

NA

### PR DESCRIPTION
**Pull request by bruvzg**
`joypadsQueue` expected to have `GCController *` when it's read, but `Joypad *` was pushed to it.

Should fix https://github.com/godotengine/godot/issues/95365

I can't reproduce the issue in normal conditions, but can reproduce it by delaying `start_processing`.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/macos/joypad_macos.mm [hunk 1]
```diff
@@ -228,7 +228,7 @@ @interface JoypadMacOSObserver ()
 @property(assign, nonatomic) BOOL isObserving;
 @property(assign, nonatomic) BOOL isProcessing;
 @property(strong, nonatomic) NSMutableDictionary<NSNumber *, Joypad *> *connectedJoypads;
```
Comment (akien-mga) [inline platform/macos/joypad_macos.mm:230]: How about this one? I'm not familiar with that code but I see it used as GCController too:
```
217:                    GCController *controller = [self.connectedJoypads objectForKey:key];
```

File: platform/macos/joypad_macos.mm [hunk 2]
```diff
@@ -228,7 +228,7 @@ @interface JoypadMacOSObserver ()
...
-@property(strong, nonatomic) NSMutableArray<Joypad *> *joypadsQueue;
+@property(strong, nonatomic) NSMutableArray<GCController *> *joypadsQueue;
```
Comment (akien-mga) [inline platform/macos/joypad_macos.mm:231]: For the record, the `joypad_ios.mm` implementation seems similar but doesn't specify the types for the `NSMutableArray` and `NSMutableDictionary` used here. Should that be harmonized?

File: platform/macos/joypad_macos.mm (hunk 1 above)
Comment (bruvzg) [reply platform/macos/joypad_macos.mm:230]: It's in iOS code, it's a bit different and always using `GCController *`.

File: platform/macos/joypad_macos.mm (hunk 2 above)
Comment (bruvzg) [reply platform/macos/joypad_macos.mm:231]: In case of iOS it should be:
```obj-c
@property(strong, nonatomic) NSMutableDictionary<NSNumber *, GCController *> *connectedJoypads;
@property(strong, nonatomic) NSMutableArray<GCController *> *joypadsQueue;
```

Probably worth merging both int a single file, it's using the same API and code should be almost same.

Comment (akien-mga) [reply platform/macos/joypad_macos.mm:231]: Makes sense. I'd guess that should be for a follow-up 4.4 PR, as I'm evaluating whether this one should be merged for 4.3.

**Comment by akien-mga** [comment]
Thanks!
