### PR TITLE
Fix wrong sampling in ColorPicker

### LINKED ISSUE #46334: ColorPicker eyedrop doesn't work
**Godot version:**

c5a88e6

**OS/device including version:**

Windows 10

**Issue description:**

Nothing happens when you click it
image

### PR DESCRIPTION
**Pull request by Rindbee**
Quick fix #46334.

Previously, the position was calculated incorrectly, resulting in incorrect sampling. This may not be the best solution, the `ColorPickerButton` still has problems in play mode and `interface/editor/single_window_mode`.

| Editor | Play |
| :------: | :-----: |
|  |  |

#25358 appears to have been fixed.

**Edit:**

~~Make `deferred_mode` available again. If enabled, only display and record the different colors when the `LMB` is pressed/released in the shape, or the color obtained when the sampling is ended.~~

### CODE REVIEW

**Comment by fire** [comment]
To be clear, the point that is being sampled on the screen coordinate system is wrong?

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -295,7 +295,12 @@ void ColorPicker::_update_controls() {
 }
 
 void ColorPicker::_set_pick_color(const Color &p_color, bool p_update_sliders) {
+	if (color == p_color) {
+		return;
+	}
 	color = p_color;
+	emit_signal(SNAME("color_changed"), color);
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:302]: The signal shouldn't be emitted here, because when it makes it emitted when changing color via code.

**Comment by KoBeWi** [comment]
I wouldn't change the code more than necessary. This started as a pretty simple PR but then you added code changes everywhere. Why ;_;

It changes signal behavior to undesired (changing color from script shouldn't emit signal) and breaks the hue wheel when color has no saturation.
Y6YeIOIcEN
There might be more regressions.

Refactoring is nice, but bugfixing PRs shouldn't do it (unless it's something minor). Also ColorPicker is being refactored right now by @Vitika9 as a GSoC project, so this code will soon be changed anyway.

I'd suggest going back to the initial PR that fixed the issue and if you want you can open a separate PR with the other changes.

**Comment by Rindbee** [comment]
> This started as a pretty simple PR but then you added code changes everywhere. 

When I tested the original modified code, I found that `deferred_mode` doesn't work, so...

I should fix them one by one in different PRs.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
