### PR TITLE
Fix some editor crashes

### LINKED ISSUE #29622: Editor crash when using Node::set_process_priority(int)
**Godot version:**
3.2.dev.custom_build. 197b65f32

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fcb806f7f60] (??:0)
[2] Map<StringName, SceneTree::Group, Comparator<StringName>, DefaultAllocator>::find(StringName const&) (/home/rafal/Pulpit/godot/./core/map.h:533)
[3] SceneTree::make_group_changed(StringName const&) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:141)
[4] Node::set_process_priority(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:844 (discriminator 2))
[5] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] Spatial::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/spatial.h:58 (discriminator 3))
[13] VisualInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:43 (discriminator 3))
[14] GeometryInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:87 (discriminator 3))
[15] CPUParticles::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/3d/cpu_particles.h:43 (discriminator 3))
[16] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[17] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[18] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[19] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1919)
[20] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3034)
[21] /usr/bin/godot(main+0xdc) [0x138598e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fcb806dab6b] (??:0)
[23] /usr/bin/godot(_start+0x2a) [0x13857fa] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project
commit 7b11e4c6146b366af6f0918afe879e0925bab162
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/7b11e4c6146b366af6f0918afe879e0925bab162.zip

### LINKED ISSUE #29623: Editor crash when using GDScriptFunction::call
**Godot version:**
3.2.dev.custom_build. 197b65f32

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f18ea19af60] (??:0)
[2] CowData<wchar_t>::_ref(CowData<wchar_t> const&) (/home/rafal/Pulpit/godot/./core/cowdata.h:346)
[3] String::operator=(String const&) (/home/rafal/Pulpit/godot/./core/ustring.h:355)
[4] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1552 (discriminator 1))
[5] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[6] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[7] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[8] Spatial::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/spatial.h:58 (discriminator 3))
[9] VisualInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:43 (discriminator 3))
[10] GeometryInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:87 (discriminator 3))
[11] CPUParticles::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/3d/cpu_particles.h:43 (discriminator 3))
[12] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[13] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[14] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[15] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1919)
[16] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3034)
[17] /usr/bin/godot(main+0xdc) [0x138598e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f18ea17db6b] (??:0)
[19] /usr/bin/godot(_start+0x2a) [0x13857fa] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project
commit ea87828f3cc1f609b100907e4591b8d34dfeefb4
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/ea87828f3cc1f609b100907e4591b8d34dfeefb4.zip

### LINKED ISSUE #29657: Editor crash when using CanvasItem::make_input_local
**Godot version:**
3.2.dev.custom_build. 197b65f32

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f1aab696f60] (??:0)
[2] CanvasItem::make_input_local(Ref<InputEvent> const&) const (/home/rafal/Pulpit/godot/scene/2d/canvas_item.cpp:1079 (discriminator 2))
[3] MethodBind1RC<Ref<InputEvent>, Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1333 (discriminator 9))
[4] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[5] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[6] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[7] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[8] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[9] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[10] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[11] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[12] AnimatedSprite::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/2d/animated_sprite.h:127 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1919)
[17] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3034)
[18] /usr/bin/godot(main+0xdc) [0x138598e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f1aab679b6b] (??:0)
[20] /usr/bin/godot(_start+0x2a) [0x13857fa] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit a32e30a447bb4819c54cf3042eb2b57da8e0f2e3
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/a32e30a447bb4819c54cf3042eb2b57da8e0f2e3.zip

### LINKED ISSUE #29673: Editor crash on virtual void RigidBodyBullet::on_exit_area(AreaBullet*): Assertion `0 <= countGravityPointSpaces' failed
**Godot version:**
3.2.dev.custom_build.7f3c2e7b0

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
Godot crash with only this one line of explanation
```
godot: modules/bullet/rigid_body_bullet.cpp:891: virtual void RigidBodyBullet::on_exit_area(AreaBullet*): Assertion `0 <= countGravityPointSpaces' failed.
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 2e07ae3230853f214ab98abd3861e1cc426930c2
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/2e07ae3230853f214ab98abd3861e1cc426930c2.zip

### LINKED ISSUE #29745: Editor crash when using _gui_input_event
**Godot version:**
3.2.dev.custom_build. 15425b450
**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f7c8d6ddf60] (??:0)
[2] Viewport::_gui_input_event(Ref<InputEvent>) (/home/rafal/Pulpit/godot/scene/main/viewport.cpp:2242 (discriminator 3))
[3] Viewport::input(Ref<InputEvent> const&) (/home/rafal/Pulpit/godot/scene/main/viewport.cpp:2672 (discriminator 2))
[4] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] Viewport::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/main/viewport.h:94 (discriminator 3))
[12] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[13] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[14] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[15] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1919)
[16] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3051)
[17] /usr/bin/godot(main+0xdc) [0x138798e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f7c8d6c0b6b] (??:0)
[19] /usr/bin/godot(_start+0x2a) [0x13877fa] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit a1e2f171d9a15689c3815b98d1c49106320b107d
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/a1e2f171d9a15689c3815b98d1c49106320b107d.zip

### LINKED ISSUE #29746: Editor crash when using HTTPRequest::cancel_request()
**Godot version:**
3.2.dev.custom_build. 15425b450
**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7ff7c6eebf60] (??:0)
[2] void memdelete<Thread>(Thread*) (/home/rafal/Pulpit/godot/./core/os/memory.h:120)
[3] HTTPRequest::cancel_request() (/home/rafal/Pulpit/godot/scene/main/http_request.cpp:165)
[4] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:61 (discriminator 4))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] HTTPRequest::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/main/http_request.h:41 (discriminator 3))
[12] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[13] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[14] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[15] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1919)
[16] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3051)
[17] /usr/bin/godot(main+0xdc) [0x138798e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7ff7c6eceb6b] (??:0)
[19] /usr/bin/godot(_start+0x2a) [0x13877fa] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit c2735fc0ef311832e612710bb0f304fa25029a94
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/c2735fc0ef311832e612710bb0f304fa25029a94.zip

### LINKED ISSUE #29767: Editor crash in Ref<World>::is_valid()
**Godot version:**
3.2.dev.custom_build. bd937ea39

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f235ac6ef60] (??:0)
[2] Ref<World>::is_valid() const (/home/rafal/Pulpit/godot/./core/reference.h:272)
[3] Viewport::find_world() const (/home/rafal/Pulpit/godot/scene/main/viewport.cpp:1095)
[4] Spatial::get_world() const (/home/rafal/Pulpit/godot/scene/3d/spatial.cpp:510)
[5] VisualInstance::_notification(int) (/home/rafal/Pulpit/godot/scene/3d/visual_instance.cpp:64)
[6] VisualInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:43 (discriminator 14))
[7] GeometryInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:87 (discriminator 3))
[8] CPUParticles::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/3d/cpu_particles.h:43 (discriminator 3))
[9] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[10] Spatial::_notification(int) (/home/rafal/Pulpit/godot/scene/3d/spatial.cpp:152)
[11] Spatial::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/spatial.h:58 (discriminator 14))
[12] VisualInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:43)
[13] GeometryInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:87)
[14] CPUParticles::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/3d/cpu_particles.h:43)
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] MethodBind2<int, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[17] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[18] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[19] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[20] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[21] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[22] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[23] Spatial::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/spatial.h:58 (discriminator 3))
[24] VisualInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:43 (discriminator 3))
[25] GeometryInstance::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/3d/visual_instance.h:87 (discriminator 3))
[26] CPUParticles::_notificationv(int, bool) (/home/rafal/Pulpit/godot/scene/3d/cpu_particles.h:43 (discriminator 3))
[27] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[28] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[29] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[30] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1918)
[31] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3051)
[32] /usr/bin/godot(main+0xdc) [0x138999e] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[33] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f235ac51b6b] (??:0)
[34] /usr/bin/godot(_start+0x2a) [0x138980a] (??:?)
```
**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit dd694c609c034e52ae54bdafe746e086ab2c5eb7
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/dd694c609c034e52ae54bdafe746e086ab2c5eb7.zip

### LINKED ISSUE #29920: Editor crash in CubeMap::set_side
**Godot version:**
3.2.dev.custom_build. 974b07fc7

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f1d5ba3df60] (??:0)
[2] PoolVector<unsigned char>::size() const (/home/rafal/Pulpit/godot/./core/pool_vector.h:475)
[3] Image::empty() const (/home/rafal/Pulpit/godot/core/image.cpp:1583)
[4] CubeMap::set_side(CubeMap::Side, Ref<Image> const&) (/home/rafal/Pulpit/godot/scene/resources/texture.cpp:1490)
[5] MethodBind2<CubeMap::Side, Ref<Image> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x138d871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f1d5ba20b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x138d6da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit a11def603d41df03de926175058dd86b64409379
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/a11def603d41df03de926175058dd86b64409379.zip

### LINKED ISSUE #29950: Editor crash when using Image::shrink_x2
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f54e9b2ff60] (??:0)
[2] Image::average_4_uint8(unsigned char&, unsigned char const&, unsigned char const&, unsigned char const&, unsigned char const&) (/home/rafal/Pulpit/godot/core/image.cpp:3119)
[3] godot() [0x368cc68] (/home/rafal/Pulpit/godot/core/image.cpp:1309 (discriminator 2))
[4] Image::shrink_x2() (/home/rafal/Pulpit/godot/core/image.cpp:1403)
[5] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:61 (discriminator 4))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f54e9b12b6b] (??:0)
[21] godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit bcf8c184467c90f360275ccdf876eb6126c14de8
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/bcf8c184467c90f360275ccdf876eb6126c14de8.zip

### LINKED ISSUE #29954: Editor crash when using  AudioEffectRecord::get_recording()
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fbd5afeff60] (??:0)
[2] CowData<float>::_get_size() const (/home/rafal/Pulpit/godot/./core/cowdata.h:70)
[3] CowData<float>::size() const (/home/rafal/Pulpit/godot/./core/cowdata.h:125)
[4] Vector<float>::size() const (/home/rafal/Pulpit/godot/./core/vector.h:83)
[5] AudioEffectRecord::get_recording() const (/home/rafal/Pulpit/godot/servers/audio/effects/audio_effect_record.cpp:220)
[6] MethodBind0RC<Ref<AudioStreamSample> >::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:593 (discriminator 4))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1080)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fbd5afd2b6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)

```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit c91a92d68ac5da842765c9c0559ea112d8b0a787
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/c91a92d68ac5da842765c9c0559ea112d8b0a787.zip

### LINKED ISSUE #29960: Editor crash when using VisualShaderNodeGroupBase::set_inputs
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fab513f4f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::set_inputs(String const&) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1767 (discriminator 2))
[5] MethodBind1<String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fab513d7b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 5d147e55c127b5bf7af79bf1f9166de5cf293f1f
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/5d147e55c127b5bf7af79bf1f9166de5cf293f1f.zip

### LINKED ISSUE #29963: Editor crash when using VisualShaderNodeGroupBase::set_outputs(String const&)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f0ede552f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::set_outputs(String const&) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1799 (discriminator 2))
[5] MethodBind1<String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f0ede535b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 11509a07e3a8ce47db70c254c102e93049e01eb0
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/11509a07e3a8ce47db70c254c102e93049e01eb0.zip

### PR DESCRIPTION
**Pull request by Dentrax**
Fixes #29960
Fixes #29954
Fixes #29963
Fixes #29950
Fixes #29920
Fixes #29767
Fixes #29746
Fixes #29745
Fixes #29673
Fixes #29657
Fixes #29623
Fixes #29622

**IDK:** For #29778 , I waited _~5_ mins and it did not crash.
**IDK:** For #29766 , I waited _~5_ mins and it did not crash.
**IDK:** For #29369 , I waited _~5_ mins and it did not crash.

In addition, Thanks to @qarmin for the well explained test cases.

My second _PR_ on _Godot_. Yay!

### CODE REVIEW

File: scene/main/node.cpp [hunk 1]
```diff
@@ -841,15 +845,19 @@ void Node::set_process_priority(int p_priority) {
 	data.process_priority = p_priority;
 
 	if (is_processing())
+		ERR_FAIL_COND(!data.tree);
```
Comment (Selene29) [inline scene/main/node.cpp]: You need braces here and below, otherwise only the first line after the "if" is part of the if-clause.

Comment (Dentrax) [reply scene/main/node.cpp]: Oh, I missed that point. Fixed.

**Comment by LinuxUserGD** [comment]
Seems like @qarmin is the crash king :D

File: scene/resources/visual_shader.cpp [hunk 2]
```diff
@@ -1762,6 +1762,9 @@ void VisualShaderNodeGroupBase::set_inputs(const String &p_inputs) {
 	for (int i = 0; i < input_port_count; i++) {
 
 		Vector<String> arr = input_strings[i].split(",");
+		ERR_FAIL_INDEX(0, arr.size());
```
Comment (Chaosus) [inline scene/resources/visual_shader.cpp]: I think, there should be check for exactly 3 arguments instead (ERR_FAIL_COND(arr.size() != 3))

File: scene/resources/visual_shader.cpp [hunk 3]
```diff
@@ -1792,8 +1795,10 @@ void VisualShaderNodeGroupBase::set_outputs(const String &p_outputs) {
 	int output_port_count = output_strings.size();
 
 	for (int i = 0; i < output_port_count; i++) {
-
 		Vector<String> arr = output_strings[i].split(",");
+		ERR_FAIL_INDEX(0, arr.size());
```
Comment (Chaosus) [inline scene/resources/visual_shader.cpp]: Same as above

File: scene/resources/visual_shader.cpp (hunk 2 above)
Comment (Dentrax) [reply scene/resources/visual_shader.cpp]: Actually, I did that on purpose. If I checked in _!= 3_ way, we cannot understand exactly which index of the error is in the editor. But only because I check the index, I can see that the error is exactly in _nth_ index.

Comment (Chaosus) [reply scene/resources/visual_shader.cpp]: Ah, nvm then

File: drivers/gles3/rasterizer_storage_gles3.cpp [hunk 4]
```diff
@@ -4635,7 +4635,6 @@ Transform2D RasterizerStorageGLES3::multimesh_instance_get_transform_2d(RID p_mu
 }
 
 Color RasterizerStorageGLES3::multimesh_instance_get_color(RID p_multimesh, int p_index) const {
-
```
Comment (akien-mga) [inline drivers/gles3/rasterizer_storage_gles3.cpp]: It would be better not to remove this line, as it marks this file as modified by this commit even though there is no functional changes.

File: modules/bullet/rigid_body_bullet.cpp [hunk 5]
```diff
@@ -866,7 +866,7 @@ void RigidBodyBullet::on_enter_area(AreaBullet *p_area) {
 
 	if (p_area->is_spOv_gravityPoint()) {
 		++countGravityPointSpaces;
-		assert(0 < countGravityPointSpaces);
+		ERR_FAIL_COND(countGravityPointSpaces < 0);
```
Comment (akien-mga) [inline modules/bullet/rigid_body_bullet.cpp]: If we want to match the previous code it should be `<= 0`. Or is allowing the `0` cases part of the fix?

File: modules/gdscript/gdscript_function.cpp [hunk 6]
```diff
@@ -1549,7 +1549,9 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
 		// function, file, line, error, explanation
 		String err_file;
 		if (p_instance)
-			err_file = p_instance->script->path;
+			if(p_instance->script->path != "") {
```
Comment (akien-mga) [inline modules/gdscript/gdscript_function.cpp]: Style issue, there should be a space after `if`.

File: scene/3d/visual_instance.cpp [hunk 7]
```diff
@@ -60,7 +60,7 @@ void VisualInstance::_notification(int p_what) {
 			if (skeleton)
 				VisualServer::get_singleton()->instance_attach_skeleton( instance, skeleton->get_skeleton() );
 			*/
-
+			ERR_FAIL_COND(get_world().is_null());
```
Comment (akien-mga) [inline scene/3d/visual_instance.cpp]: The fix seems fine, but in what case do we receive `NOTIFICATION_ENTER_WORLD` without a valid `get_world()`?

File: scene/main/http_request.cpp [hunk 8]
```diff
@@ -159,16 +159,20 @@ void HTTPRequest::cancel_request() {
 	if (!use_threads) {
 		set_process_internal(false);
 	} else {
-		thread_request_quit = true;
-		Thread::wait_to_finish(thread);
-		memdelete(thread);
-		thread = NULL;
+
+		if(thread) {
```
Comment (akien-mga) [inline scene/main/http_request.cpp]: Style issue.

File: scene/main/node.cpp [hunk 9]
```diff
@@ -71,6 +71,8 @@ void Node::_notification(int p_notification) {
 
 		} break;
 		case NOTIFICATION_ENTER_TREE: {
+			ERR_FAIL_COND(!get_viewport());
+			ERR_FAIL_COND(!get_tree());
```
Comment (akien-mga) [inline scene/main/node.cpp]: It also seems weird that any of those two can happen, `NOTIFICATION_ENTER_TREE` is emitted when the node enters the tree, which means that there should be a tree (and thus a root, so a viewport).

File: scene/main/node.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/main/node.cpp]: Checking once before the first `if` should be enough.

File: scene/resources/visual_shader.cpp (hunk 2 above)
Comment (akien-mga) [reply scene/resources/visual_shader.cpp]: `ERR_FAIL_INDEX` is meant to compare a user-passed index with an array size, not the other way around.
This should simply be `ERR_FAIL_COND(arr.size() != 3);` as suggested.

Users won't get a lot more information from `Index 2=2 out of size (arr.size()=3)` than a plain `Condition ' arr.size() != 3 ' is true.` IMO. The latter is more explicit about the fact that something should have a size of 3.

File: servers/audio/effects/audio_effect_record.cpp [hunk 10]
```diff
@@ -216,6 +216,9 @@ Ref<AudioStreamSample> AudioEffectRecord::get_recording() const {
 
 	PoolVector<uint8_t> dst_data;
 
+	ERR_FAIL_COND_V(current_instance.is_null(), NULL)
+	ERR_FAIL_COND_V(current_instance->recording_data.size(), NULL)
```
Comment (akien-mga) [inline servers/audio/effects/audio_effect_record.cpp]: Missing semicolons.

**Comment by akien-mga** [comment]
For the VisualShader bugs, I prefer the approach in #29987 as it does most of the input validation before running into issues in the for loops. So once that one is merged, you'll have to amend/rebase your commit to remove the conflicting changes.

**Comment by akien-mga** [comment]
It would be nice to amend the commit log too to be slightly more explicit, even though I agree that it's hard to give a good description of such a commit. Something like "Add checks to prevent out of bounds indexing".

File: modules/bullet/rigid_body_bullet.cpp (hunk 5 above)
Comment (Dentrax) [reply modules/bullet/rigid_body_bullet.cpp]: I think `< 0` is fine. Because of, that initialized with value of `0` at line `274`. Also it checked with `< 0` at line `379` as well. Why do you think that should be `<= 0`?

File: drivers/gles3/rasterizer_storage_gles3.cpp (hunk 4 above)
Comment (Dentrax) [reply drivers/gles3/rasterizer_storage_gles3.cpp]: Oh, I did not change that file, it happened accidentally somehow. :)

File: modules/gdscript/gdscript_function.cpp (hunk 6 above)
Comment (Dentrax) [reply modules/gdscript/gdscript_function.cpp]: Fixed, and I am curious about something. Why we not use a static reference to check a string is empty or null instead of creating new string everytime like `""`?

File: modules/bullet/rigid_body_bullet.cpp (hunk 5 above)
Comment (akien-mga) [reply modules/bullet/rigid_body_bullet.cpp]: Well I ask because the previous code was asserting on `countGravityPointSpaces > 0`, i.e failing on `countGravityPointSpaces <= 0`. I'm not saying the previous code was correct, just that this changes the logic so I wanted to make sure it's done on purpose.

File: modules/gdscript/gdscript_function.cpp (hunk 6 above)
Comment (akien-mga) [reply modules/gdscript/gdscript_function.cpp]: You can use `!path.empty()` if you want. It would be interesting to benchmark what difference it makes, if any.

File: scene/3d/visual_instance.cpp (hunk 7 above)
Comment (Dentrax) [reply scene/3d/visual_instance.cpp]: I don't know exactly but somehow the function of `Ref<World> Viewport::find_world() const` returns _else_ situation. Maybe it returns `Ref<World>()` if `is_inside_world()` is _false_ or `data.viewport` is `null`. How can we test that `get_world()` why returns _null_ or _empty_ with a better way? What is your opinion?

File: modules/bullet/rigid_body_bullet.cpp (hunk 5 above)
Comment (Dentrax) [reply modules/bullet/rigid_body_bullet.cpp]: Oh, you are right. I missed that point. :)

File: scene/main/node.cpp (hunk 9 above)
Comment (Dentrax) [reply scene/main/node.cpp]: I am suprised too. But if I don't check this way, the editor crashes. I think thats very rare condition.

**Comment by Dentrax** [comment]
@akien-mga 

Thanks for the suggestion. I will take heed of to commit messages for my next work. :)

To merge to @Chaosus 's PR, I did this way: 

`git checkout upstream/master -- .\scene\resources\visual_shader.cpp` and then `git add -u` then `git commit --amend` Is that correct? There are some things about git that I don't know yet. Sorry for that. I don't want that code to be like I changed it. But now, `visual_shader.cpp` seems that I have changed. How can i fix that?

File: scene/main/http_request.cpp [hunk 11]
```diff
@@ -159,16 +159,21 @@ void HTTPRequest::cancel_request() {
 	if (!use_threads) {
 		set_process_internal(false);
 	} else {
-		thread_request_quit = true;
-		Thread::wait_to_finish(thread);
-		memdelete(thread);
-		thread = NULL;
+
+		if (thread) {
```
Comment (Faless) [inline scene/main/http_request.cpp]: I think a better solution would be to fix the condition in `set_use_threads` that can cause the value to change before the request has finished, thus causing `use_threads` to be `true` but `thread` to be null. (`_request_done`/`cancel_request` is called deferred when status become disconnected during poll, thus causing a frame to be in the situation where `status == STATUS_DISCONNECTED` but `requesting == true`)

```diff
diff --git a/scene/main/http_request.cpp b/scene/main/http_request.cpp
index e65314644..d6392d62d 100644
--- a/scene/main/http_request.cpp
+++ b/scene/main/http_request.cpp
@@ -425,7 +425,7 @@ void HTTPRequest::_notification(int p_what) {
 
 void HTTPRequest::set_use_threads(bool p_use) {
 
-       ERR_FAIL_COND(status != HTTPClient::STATUS_DISCONNECTED);
+       ERR_FAIL_COND(requesting);
        use_threads = p_use;
 }
```

File: modules/bullet/rigid_body_bullet.cpp [hunk 12]
```diff
@@ -888,7 +888,7 @@ void RigidBodyBullet::on_exit_area(AreaBullet *p_area) {
 	if (wasTheAreaFound) {
 		if (p_area->is_spOv_gravityPoint()) {
 			--countGravityPointSpaces;
-			assert(0 <= countGravityPointSpaces);
+			ERR_FAIL_COND(countGravityPointSpaces <= 0);
```
Comment (akien-mga) [inline modules/bullet/rigid_body_bullet.cpp]: This changes logic too. The asserts here and at line 869 were different, and assuming they were correct, the new `ERR_FAIL_COND` should respect that logic. `countGravityPointSapces` is initialized to 0, so I guess 0 should be a valid value.

File: modules/gdscript/gdscript_function.cpp [hunk 13]
```diff
@@ -1549,7 +1549,9 @@ Variant GDScriptFunction::call(GDScriptInstance *p_instance, const Variant **p_a
 		// function, file, line, error, explanation
 		String err_file;
 		if (p_instance)
-			err_file = p_instance->script->path;
+			if (p_instance->script->path != "") {
```
Comment (akien-mga) [inline modules/gdscript/gdscript_function.cpp]: What's the point of this check actually? If `p_instance->script->path == ""`, then `err_file` will get an empty String assigned, which is fine as it's its current value anyway.

Didn't you mean to check `p_instance->script->is_valid()` to prevent a null pointer dereference?

File: scene/2d/canvas_item.cpp [hunk 14]
```diff
@@ -1075,6 +1075,7 @@ Vector2 CanvasItem::make_canvas_position_local(const Vector2 &screen_point) cons
 Ref<InputEvent> CanvasItem::make_input_local(const Ref<InputEvent> &p_event) const {
 
 	ERR_FAIL_COND_V(!is_inside_tree(), p_event);
+	ERR_FAIL_COND_V(p_event.is_null(), NULL);
```
Comment (akien-mga) [inline scene/2d/canvas_item.cpp]: It's mostly cosmetic, but I'd say you could return `p_event` here to be consistent with the previous line and overall logic: return the input on failure. Even though here `p_event` *is* NULL so it's the same in the end.

**Comment by akien-mga** [comment]
> There are some things about git that I don't know yet. Sorry for that. I don't want that code to be like I changed it. But now, visual_shader.cpp seems that I have changed. How can i fix that?

You can probably remove those changes with `git rebase upstream/master`.

File: modules/bullet/rigid_body_bullet.cpp (hunk 12 above)
Comment (Dentrax) [reply modules/bullet/rigid_body_bullet.cpp]: Oh, you are right. I missed it.

File: modules/gdscript/gdscript_function.cpp (hunk 13 above)
Comment (Dentrax) [reply modules/gdscript/gdscript_function.cpp]: Interesting part is, the bug was fixed that way. Now I am adding the `is_valid()` checks.

File: scene/main/http_request.cpp (hunk 11 above)
Comment (Dentrax) [reply scene/main/http_request.cpp]: I think, thats a bad idea to remove that `STATUS_DISCONNECTED` because someone can be easily confused at that line. Intead, should we check the `requesting` status that way? @akien-mga 

```
if (!requesting) {
	use_threads = p_use;
}
```

**Comment by Dentrax** [comment]
@akien-mga Could you review again, please? :)

File: scene/main/http_request.cpp (hunk 11 above)
Comment (Faless) [reply scene/main/http_request.cpp]: > Isn't this exactly the change I proposed above in the diff?

Oh, I see the difference, keeping both COND, sorry. Yeah, we might keep both conditions. I think it needs to print an error though if you try to change it while requesting.

Comment (Faless) [reply scene/main/http_request.cpp]: I think I found the underlying issue. See #30218

File: drivers/gles3/rasterizer_storage_gles3.cpp (hunk 4 above)
Comment (akien-mga) [reply drivers/gles3/rasterizer_storage_gles3.cpp]: If you can undo the change next time you amend the commit, that would be great :)
But it's not a big deal either if it stays this way.

File: modules/bullet/rigid_body_bullet.cpp (hunk 5 above)
Comment (akien-mga) [reply modules/bullet/rigid_body_bullet.cpp]: So, this is still changing the logic.
`assert` checks that a condition is true, and `ERR_FAIL_COND` checks that a condition is false, so if you want to change `assert` to `ERR_FAIL_COND`, you should negate the condition. The negation of `0 < countGravityPointSpaces` (i.e. `countGravityPointSpaces > 0` without the Java-ism) is `countGravityPointSpaces <= 0`.

File: modules/bullet/rigid_body_bullet.cpp (hunk 12 above)
Comment (akien-mga) [reply modules/bullet/rigid_body_bullet.cpp]: Same as above, but this time it's the other way around.

The original condition was `countGravityPointSpaces >= 0`, so when negated, it should be `countGravityPointSpaces < 0`.

File: scene/main/http_request.cpp (hunk 11 above)
Comment (akien-mga) [reply scene/main/http_request.cpp]: The changes in this file can now be removed since #30218 is merged.

File: modules/bullet/rigid_body_bullet.cpp (hunk 5 above)
Comment (Dentrax) [reply modules/bullet/rigid_body_bullet.cpp]: I'm always confused when I'm transforming between `assert` and `cond`. Thank you! Fixed.

File: modules/bullet/rigid_body_bullet.cpp (hunk 12 above)
Comment (Dentrax) [reply modules/bullet/rigid_body_bullet.cpp]: Fixed

File: scene/main/http_request.cpp (hunk 11 above)
Comment (Dentrax) [reply scene/main/http_request.cpp]: Looks like @Faless 's way is more effective solution. I removed that changes.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

File: scene/main/node.cpp [hunk 15]
```diff
@@ -840,6 +844,8 @@ bool Node::is_processing_internal() const {
 void Node::set_process_priority(int p_priority) {
 	data.process_priority = p_priority;
 
+	ERR_FAIL_COND(!data.tree);
```
Comment (akien-mga) [inline scene/main/node.cpp]: This now causes an error when loading a project in the editor:
```
ERROR: set_process_priority: Condition ' !data.tree ' is true.
   At: scene/main/node.cpp:847.
```

Comment (Dentrax) [reply scene/main/node.cpp]: Hmm, what condition are you testing to get this error? If you hadn't taken this error, editor would crash in one of the 4 if structures. According to your [comment](https://github.com/godotengine/godot/pull/29980#discussion_r296474512), is there a condition that must not enter the any of structures?

Comment (akien-mga) [reply scene/main/node.cpp]: Just open the editor on any project:
```
$ mkdir ~/tmp/new_project
$ cd ~/tmp/new_project
$ touch project.godot
$ godot -e
Godot Engine v3.2.dev.custom_build.266dc732b - https://godotengine.org
Found discrete GPU, setting DRI_PRIME=1 to use it.
Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
OpenGL ES 3.0 Renderer: AMD VEGAM (DRM 3.30.0, 5.1.14-desktop-1.mga7, LLVM 8.0.0)
 
ERROR: set_process_priority: Condition ' !data.tree ' is true.
   At: scene/main/node.cpp:847.
```

Comment (Dentrax) [reply scene/main/node.cpp]: I tried your way and also i created new project from editor. And I didn't get that error on version `v3.2.dev.custom_build. 7d8d337b2`.

Comment (akien-mga) [reply scene/main/node.cpp]: @bojidar-bg fixed it in #30254, so no worry :)
