### PR TITLE
Prevent shallow scripts from leaking into the `ResourceCache`

### LINKED ISSUE #87397: Resource loaded without being associated with script class name
### Tested versions

v4.3.dev2.official [352434668]

### System information

Windows 10 Mobile

### Issue description

I'm running into a strange error where attempting to load a custom resource with a `class_name` results in an object with none of the resources properties and which cannot be passed to any method which requires the `class_name`.  

It seems to be related to having a resource that contains an array that preloads other resources.  In my original project, I was using custom resources as UIDs to reference game levels and items.  I wanted to create a class that I could use as an index of all rooms and items in my game which my game's save file loader could reference to turn string ids back into these resource UIDs.  However, this seems to be breaking things.

### Steps to reproduce

Run the attached project.  Press the Test button.

### Minimal reproduction project (MRP)

[resource_load_test.zip](https://github.com/godotengine/godot/files/13997200/resource_load_test.zip)

### LINKED ISSUE #93433: Type Casting .may cause property access rrror with custom resource
### Tested versions

godot 4.3.beta1

### System information

win11

### Issue description

Direct instantiation using a preloaded scene reference works as expected. Proper access is ok. 
But, casting the instantiated scene to Charactor using a function (StaticClass.get_pack().instantiate() as Charactor) results in an "invalid access property" error.

### Steps to reproduce

```
extends Node2D
func _ready() -> void:
	#var ti: Charactor # this works
	#ti = StaticClass.get_pack().instantiate()

	#var ti:= StaticClass.CHARACTOR_SCENE.instantiate() as Charactor # this works

	var ti:= StaticClass.get_pack().instantiate() as Charactor # unexpected type cast behavior

	print(ti.bm.add_num) # error invalid access property

#class_name StaticClass
#
#const CHARACTOR_SCENE = preload("res://CharactorScene.tscn")
#static func get_pack() -> PackedScene:
	#return CHARACTOR_SCENE

```

CHARACTOR_SCENE  properties
image

### Minimal reproduction project (MRP)

[4.3test.zip](https://github.com/user-attachments/files/15929045/4.3test.zip)

### LINKED ISSUE #95909: Validation error using Resource sub-classes and sub-resources with specific combination of preload/@onready/instantiation
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]
- Reproducible behavior, with different error messages, in: v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

With a _very_ specific set of Resource subclasses and sub-resources, use of preload, use of `@onready`, and instantiation in script, the following error occurs:

```
E 0:00:00:0708   validate_object: Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
  <C++ Error>    Condition "!other_script->inherits_script(script)" is true. Returning: false
  <C++ Source>   core/variant/container_type_validate.h:140 @ validate_object()
```
```
E 0:00:00:0708   assign: Unable to convert array index 0 from "Object" to "Object".
  <C++ Error>    Method/function failed.
  <C++ Source>   core/variant/array.cpp:238 @ assign()
```

This occurs when attempting to run the project. The data in the sub-resource will not be loaded, and will be removed from disk when saved. Additionally, validation performed by the editor when loading the project will similarly remove the 'offending' data and give a similar error.

However, it seems that if you _don't_ have a call to instantiate the sub-resource in code (or preload, or `@onready` in this specific way), then this configuration of resources/subresources is fine to load, use, and save. This may suggest that the class structure is supported but there is some issue arising in the validation process.

### Error and automatic deletion of sub-resource at startup
When you open the included minimal reproduction project, you will see the following error in the output window:

```  
Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
Unable to convert array index 0 from "Object" to "Object". 
```

At this point, the included resource `.tres` file will be automatically modified to remove the problematic data. You should see its contents go from something like this:

```
[gd_resource type="Resource" script_class="MyResourceContainer" load_steps=5 format=3 uid="uid://6qhpq8xclwhy"]

[ext_resource type="Script" path="res://my_resource_a.gd" id="1_huj0e"]
[ext_resource type="Script" path="res://my_resource_container.gd" id="2_88hls"]
[ext_resource type="Script" path="res://my_resource_b.gd" id="2_tfgcd"]

[sub_resource type="Resource" id="Resource_aiw63"]
script = ExtResource("2_tfgcd")

[resource]
script = ExtResource("2_88hls")
data = Array[ExtResource("1_huj0e")]([SubResource("Resource_aiw63")])
```

to this (where the sub_resource has been removed)

```
[gd_resource type="Resource" script_class="MyResourceContainer" load_steps=3 format=3 uid="uid://6qhpq8xclwhy"]

[ext_resource type="Script" path="res://my_resource_a.gd" id="1_huj0e"]
[ext_resource type="Script" path="res://my_resource_container.gd" id="2_88hls"]

[resource]
script = ExtResource("2_88hls")
data = Array[ExtResource("1_huj0e")]([])
```

### Automatic deletion at runtime if you attempt to add it back
At this point, you _could_ run the project without errors, but that's because the sub-resource has been automatically removed. If you add it back in:
1. Select `test_resource.tres`
2. In the inspector, click `Add Element` for MyResourceContainer -> Data
3. Set the new element to `New MyResourceB`

Now when you run the project, you will see the two errors:
```
validate_object: Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
assign: Unable to convert array index 0 from "Object" to "Object".
```

Additionally, the data will not be available if you load the resource. It will also be removed from disk if you save the project.

### Interactions with preload, `@onready`, and more
This is a _very_ specific set of scripts! If you remove the `@onready` references, the type hints, the function call to instantiate `MyResourceB.new()`, or the preload call, the issue appears to go away.

I have tried to simplify the project further but this eliminates the issue. For example, simply having "a resource class that contains a sub-resource of a type that itself is a subclass of Resource" is not enough to trigger this error.

### Godot 4.2.2:
In v4.2.2.stable.mono.official [15073afe3], the startup error is a little different:
```
 Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
  unsupported format character
  core/variant/array.cpp:222 - Method/function failed.
```

The result is the same however, as the sub-resource data is removed from the `.tres` file.

And at runtime (if you replace the automatically removed sub-resource as described above):
```
E 0:00:00:0691   validate_object: Attempted to assign an object into a TypedArray, that does not inherit from 'GDScript'.
  <C++ Error>    Condition "!other_script->inherits_script(script)" is true. Returning: false
  <C++ Source>   core/variant/container_type_validate.h:140 @ validate_object()
```
```
E 0:00:00:0691   vformat: unsupported format character
  <C++ Error>    Condition "error" is true. Returning: String()
  <C++ Source>   ./core/variant/variant.h:835 @ vformat()
```
```
E 0:00:00:0691   assign: Method/function failed.
  <C++ Source>   core/variant/array.cpp:222 @ assign()
```

### Minimal reproduction project (MRP)

[resource-bug.zip](https://github.com/user-attachments/files/16695302/resource-bug.zip)

### PR DESCRIPTION
**Pull request by HolonProduction**
This is a new attempt at https://github.com/godotengine/godot/pull/96499 that also includes https://github.com/godotengine/godot/pull/102063

Fixes https://github.com/godotengine/godot/issues/95909
Fixes (maybe) https://github.com/godotengine/godot/issues/95789 (the described crash, does not occur with this PR when run from editor. I did not test exporting as mentioned in the issue though. Also the MRP trows a lot of errors when opening, nut sure if that is related).
Fixes https://github.com/godotengine/godot/issues/93433
Fixes https://github.com/godotengine/godot/issues/110332

Bugsquad edit:
Fixes [#110394](https://github.com/godotengine/godot/issues/110394)
Fixes https://github.com/godotengine/godot/issues/87397 according to @Maran23

Does not reintroduce https://github.com/godotengine/godot/issues/99006 or https://github.com/godotengine/godot/issues/101615

The main difference from https://github.com/godotengine/godot/pull/96499 is that in this PR `set_path_cache` does not interact with `GDScriptCache`. This prevents shallow loaded scripts from having any side effects on other fully loaded scripts (which would lead to https://github.com/godotengine/godot/issues/99006 and https://github.com/godotengine/godot/issues/101615). It also does not break shallow loaded script behavior since `set_path_cache` is only used when there is no shallow script for that path present.

Regardless of the specifics in here, I believe that the approach taken in this PR and #96499 is the correct one. Shallow scripts are an implementation detail of GDScript compilation. They must not end up in the `ResourceCache`. https://github.com/godotengine/godot/pull/97302 tries to fix the scripts after they leaked into the cache. Those partially loaded scripts fixing themselves when creating instances solves some issues but there is more that one could do with scripts than creating instances. Also users simply expect resource loading to do the actual loading work.

### CODE REVIEW

**Comment by HolonProduction** [comment]
After looking into it a bit more, this version does indeed reintroduce https://github.com/godotengine/godot/issues/101615, the issue just does not seem to trigger after opening the script in the inspector.

Reason seems to be, that using `set_path` after `set_path_cache` does not add the resource to the `ResourceCache` (which leads to a mismatch between resource and GDScript cache with this change).

Converting this to a draft for now.

**Comment by HolonProduction** [comment]
Should work correctly now.

**Comment by Maran23** [comment]
This also fixes: https://github.com/godotengine/godot/issues/87397 for me.

**Review by Maran23 — APPROVED** [review]
Since I had the same problem in the past, I tested this with my project(s) and can confirm that it fixes the issues!

I did not spot any other issues or problems. 
Code makes sense to me, could not spot any problems (Although this is an area to which I have not yet contributed.).

I wonder if we want to add more tests later (if possible), maybe even taking a mrp from one of the issues?

**Comment by HolonProduction** [comment]
I was thinking about tests, especially for known regressions that occurred in previous attempts to fix this.

However the biggest risk here is definitely the editor, which interacts with the scripts and resource cache in ways that I don't fully understand.

I have no real idea on how to write tests that look for such editor regressions. However adding more tests based on some MRPs sounds like a nice idea. I just don't really want to put in the effort in the context of this PR, since this PR is high risk and I'm not fully convinced of it myself at this point (there probably are additional editor bugs that will only be visible in complex projects).

**Comment by HolonProduction** [comment]
I'll remove the cherrypick labels from this PR. It does not introduce the known regressions of the previous attempt to fix this, it's still high risk though (fixed another regression the other day after opening a complex project with this PR).

**Comment by Maran23** [comment]
> However the biggest risk here is definitely the editor, which interacts with the scripts and resource cache in ways that I don't fully understand.

Ahh, I see. I think focusing on tests for `GDScript` only after is still a big win (without the editor).

> I'll remove the cherrypick labels from this PR.

Makes sense, I agree to the rationale as well.

**Comment by bsil78** [comment]
@HolonProduction can this me merged for testing in next dev ?

**Comment by HolonProduction** [comment]
In general PR's need to be reviewed before they can be considered for merging. This PR lacks reviews, so no. Also it's not up to me to decide when stuff gets merged.

File: modules/gdscript/gdscript_cache.cpp [hunk 1]
```diff
@@ -338,9 +339,20 @@ Ref<GDScript> GDScriptCache::get_shallow_script(const String &p_path, Error &r_e
 }
 
 Ref<GDScript> GDScriptCache::get_full_script(const String &p_path, Error &r_error, const String &p_owner, bool p_update_from_disk) {
+	Ref<GDScript> uncached_script = get_full_script_no_resource_cache(p_path, r_error, p_owner, p_update_from_disk);
+
+	// Resources don't know whether they are cached, so using set_path after set_path_cache does not add the resource to the cache if the path is the same.
+	// We reset the cached path from get_shallow_script so that when ResourceLoaders uses set_path everything can get cached correctly.
```
Comment (adamscott) [inline modules/gdscript/gdscript_cache.cpp]:
```suggestion
	// Resources don't know whether they are cached, so using `set_path()` after `set_path_cache()` does not add the resource to the cache if the path is the same.
	// We reset the cached path from `get_shallow_script()` so that when `ResourceLoaders` uses `set_path()` everything can get cached correctly.
```

File: modules/gdscript/gdscript_cache.h [hunk 2]
```diff
@@ -91,6 +95,7 @@ class GDScriptCache {
 	friend class GDScript;
 	friend class GDScriptParserRef;
 	friend class GDScriptInstance;
+	friend class GDScriptTests::TestGDScriptCacheAccessor;
```
Comment (adamscott) [inline modules/gdscript/gdscript_cache.h:101]:
```suggestion
#ifdef TESTS_ENABLED
	friend class GDScriptTests::TestGDScriptCacheAccessor;
#endif // TESTS_ENABLED
```

File: modules/gdscript/gdscript_cache.h [hunk 3]
```diff
@@ -78,6 +78,10 @@ class GDScriptParserRef : public RefCounted {
 	~GDScriptParserRef();
 };
 
+namespace GDScriptTests {
+class TestGDScriptCacheAccessor;
+}
+
```
Comment (adamscott) [inline modules/gdscript/gdscript_cache.h:86]:
```suggestion
#ifdef TESTS_ENABLED
namespace GDScriptTests {
class TestGDScriptCacheAccessor;
}
#endif // TESTS_ENABLED

```

File: modules/gdscript/gdscript.cpp [hunk 4]
```diff
@@ -1079,6 +1079,16 @@ void GDScript::_bind_methods() {
...
 
+void GDScript::set_path_cache(const String &p_path) {
+	if (is_root_script()) {
+		Script::set_path_cache(p_path);
+	}
+
+	for (KeyValue<StringName, Ref<GDScript>> &kv : subclasses) {
+		kv.value->set_path_cache(p_path);
+	}
+}
```
Comment (adamscott) [inline modules/gdscript/gdscript.cpp:1081]: From what I understand, the loop is pretty much dead code. Each subclass by design will have an owner, so `is_root_script() == false`. If `is_root_script() == true`, the only thing `set_path_cache()` does is to loop its children (which themselves will only loop their children).

```suggestion
void GDScript::set_path_cache(const String &p_path) {
	if (is_root_script()) {
		Script::set_path_cache(p_path);
	}
}
```

**Review by adamscott — APPROVED** [review]
Great PR. I think it will solve the cache issues, at least most of them.

I had difficulties running the test you added independantly from the rest of the tests (`--test --test-suite="[Modules][GDScript]" --test-case="[Modules][GDScript] Loading keeps ResourceCache and GDScriptCache in sync"`), but I figured that I could fix that (I'm pretty sure) with #112484.

Other than the small comments I made, I think it's pretty much alright.

File: modules/gdscript/gdscript_cache.h (hunk 2 above)
Comment (HolonProduction) [reply modules/gdscript/gdscript_cache.h:101]: Tried this but it does not seem to compile :thinking: No clue why not to be honest.

Comment (HolonProduction) [reply modules/gdscript/gdscript_cache.h:101]: Ok got it! When the new approach with generated test headers for all modules was introduced the `TESTS_ENABLED` define was missing from this one specific scons file where the generated header is added. Adding it there fixes the build issues.

**Review by Repiteo — APPROVED** [review]
Yeah, let's give this a shot

**Comment by Repiteo** [comment]
Thanks!

**Comment by HolonProduction** [comment]
List of potential regression fixes related to this PR. In case this gets reverted:

- https://github.com/godotengine/godot/pull/113580
- https://github.com/godotengine/godot/pull/113600

File: modules/gdscript/gdscript_cache.cpp [hunk 5]
```diff
@@ -312,7 +312,8 @@ Ref<GDScript> GDScriptCache::get_shallow_script(const String &p_path, Error &r_e
 
 	Ref<GDScript> script;
 	script.instantiate();
-	script->set_path(p_path, true);
+
+	script->set_path_cache(p_path);
```
Comment (TheDying0fLight) [inline modules/gdscript/gdscript_cache.cpp:316]: From my testing this breaks caching of scripts in `ResourceLoader`, as it prevents adding the script to the cache in `Resource::set_path` because `path_cache == p_path` is true.

I found this when jumping to a GDScript with a syntax error through a `Find in Files` search result and the file parsing errors showing up every time you jump to it. Reverting this line fixed the behavior.

(I don't know if this is already tracked somewhere)

Comment (HolonProduction) [reply modules/gdscript/gdscript_cache.cpp:316]: If you are having issues that are reproducible in the latest beta (there have been 2 regression fixes for this PR already) please open an issue with concrete steps and an MRP (feel free to tag me, I'll look into it).

I'm aware of the behaviour you are describing and I tried to compensate for it in this PR and the regression fixes. E.g. here 

https://github.com/HolonProduction/godot/blob/b4203f7f643640dd0a0212f454e8894aac018021/modules/gdscript/gdscript_cache.cpp#L344-L347

If it's still occurring there might be some control flow that I did miss.
