### PR TITLE
Remove FileSystem dock errors on unimported files

### LINKED ISSUE #47296: Errors when selecting file using "Keep" importer in FileSystem dock
**Godot version:**
cd05653e3, after #47268.

**OS/device including version:**
Linux, but should happen on any OS.

**Issue description:**
When using the new "Keep" import mode for a given file (here CSV), the following errors can be reproduced:

1. When you select the file in the FileSystem dock with a single mouse click, this error is printed:

```
ERROR: Couldn't find the given section "remap" and key "type", and no default was given.
   at: get_value (core/io/config_file.cpp:85)
```

2. When you double-click the file, or "open" it with `ui_accept`, the following errors are raised:

```
ERROR: Resource file not found: .
   at: _load (core/io/resource_loader.cpp:207)
ERROR: Failed loading resource: res://test.csv. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:202)
ERROR: Condition "!res.is_valid()" is true. Returning: ERR_CANT_OPEN
   at: load_resource (editor/editor_node.cpp:1016)
```

3. The CSV is shown with a "broken import" icon. It should likely use a "plain file" icon instead.

Screenshot_20210323_145923

**Steps to reproduce:**
See above.

**Minimal reproduction project:**
[CSVImporterKeep.zip](https://github.com/godotengine/godot/files/6190133/CSVImporterKeep.zip)

### PR DESCRIPTION
**Pull request by reduz**
* Removes error shown when file is in 'keep' mode
* Display a warning when attempting to open the file
* Closes #47296
image

Should be easy to cherrypick to 3.x.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -944,6 +944,21 @@ void FileSystemDock::_select_file(const String &p_path, bool p_select_in_favorit
...
 	} else if (fpath != "Favorites") {
+		if (FileAccess::exists(fpath + ".import")) {
+			Ref<ConfigFile> config;
+			config.instance();
+			Error err = config->load(fpath + ".import");
+			if (err == OK) {
+				if (config->has_section_key("remap", "importer")) {
+					String importer = config->get_value("remap", "importer");
+					if (importer == "keep") {
+						EditorNode::get_singleton()->show_warning(TTR("Importing has been disabled for this file, so it can't be opened."));
```
Comment (Calinou) [inline editor/filesystem_dock.cpp:955]: It's still possible to open the file via scripting, so I think this makes it more clear:

```suggestion
						EditorNode::get_singleton()->show_warning(TTR("Importing has been disabled for this file, so it can't be opened in the editor."));
```

Comment (reduz) [reply editor/filesystem_dock.cpp:955]: maybe it should be renamed from opened to edited instead?

Comment (reduz) [reply editor/filesystem_dock.cpp]: changed

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3. (Via #47300.)
