### PR TITLE
Fix VisualShader conversion failing with subresources

### LINKED ISSUE #101375: Converting visual shader to normal shader breaks the shader
### Tested versions

- Reproduceable in: v4.4.dev.mono.custom_build [61d0ff4b9] / our fork that closely tracks master

### System information

Godot v4.4.dev.mono (61d0ff4b9) - Pop!_OS 22.04 LTS on Wayland - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (nvidia; 565.77) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

### Issue description

When converting the visual shader to a normal shader, the shader breaks for specific visual shaders.  In our case, our water shader.  We are making use of the shaderV plugin as well which I include in the mrp: https://github.com/arkology/ShaderV

Visual Shader ✅:

Image

Converted Normal Shader ❌

Image

Now the extremely strange thing is the shader code in the visual shader and the normal shader once converted are identical:

Image

This leads me to believe it must be an error on either the implementation of VisualShader.cpp or Shader.cpp when it comes to generating the actual shader code the gpu uses but this is just speculation.  In reality, I am very new to the internals of Godot's shader generation.

I discovered this because I found a bug in the visual shader that causes a crash on exported projects.  Changing to a normal shader at export time fixes it.  I'll be opening a separate issue and a PR enabling (at least via custom plugins) support to change to normal shaders at export time as I have found this to have significant benefits in regards to game size.

### Steps to reproduce

1. Open the attached MRP
2. See that there are 2 scenes in the root: normal_shader.tscn and visual_shader.tscn
3. See that the water renders correct in visual_shader.tscn
4. See that the water does not render correctly in normal_shader.tscn
5. For fun, convert the visual_shader to a normal_shader via right clicking on the asset and see that it breaks

Image

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/18368949/mrp.zip)

### PR DESCRIPTION
**Pull request by ColinSORourke**
(Attempts to) Resolve: https://github.com/godotengine/godot/issues/101375

Visual Shaders can have Subresources such as Textures embedded directly in the Visual Shader, and some users find this desirable to better preview the Visual Shader's behavior. However, this breaks the conversion from Visual Shader to Text GDShader because a Text GDshader cannot have SubResources (the appropriate place for these resources would be as a Shader Parameter on a ShaderMaterial).

This PR aligns with @QbieShay's suggestion that 
> I think that converting to shader a visual shader with embedded textures should just fail and print a warning/error.

And resolves the issue by adding a has_node_embeds function to the VisualShader class. Has_node_embeds iterates over the child nodes, and searches through the object properties for embedded resources. The conversion plugin calls this function to catch and throw appropriate errors/warnings.

Note: ConversionPlugin fail states can cause a crash in FileSystem_Dock.cpp - I've mirrored a catch for that from https://github.com/godotengine/godot/pull/109369 to here.

Screenshot 2025-08-06 at 1 57 49 PM

This PR could unblock https://github.com/godotengine/godot/pull/102918, which could decrease file sizes and improve load times. Would require a little more work to have that PRs code handle a failed conversion.

More ideal solutions could be developed in the future such as:
* Disallowing subresource embeds in VisualShaders, and forcing resource references to go through the appropriate ShaderParameters on a Material Resource
* Automatically making embeds 'unique' or creating a Material with the appropriate parameters upon conversion

But I believe this code is still a necessary step to resolve the core error (Conversion deleting subresources) and to track VisualShader subresources for compatibility with future changes.

### CODE REVIEW

File: scene/resources/visual_shader_nodes.cpp [hunk 1]
```diff
@@ -1082,7 +1092,17 @@ String VisualShaderNodeCurveTexture::get_output_port_name(int p_port) const {
 }
 
 void VisualShaderNodeCurveTexture::set_texture(Ref<CurveTexture> p_texture) {
+	if (!texture.is_null()) {
+		if (texture->is_built_in()) {
```
Comment (KoBeWi) [inline scene/resources/visual_shader_nodes.cpp]: Why this checks? External resources embeds are also broken.

File: editor/shader/visual_shader_editor_plugin.cpp [hunk 2]
```diff
@@ -8437,6 +8437,7 @@ bool VisualShaderConversionPlugin::handles(const Ref<Resource> &p_resource) cons
 Ref<Resource> VisualShaderConversionPlugin::convert(const Ref<Resource> &p_resource) const {
 	Ref<VisualShader> vshader = p_resource;
 	ERR_FAIL_COND_V(vshader.is_null(), Ref<Resource>());
+	ERR_FAIL_COND_V(vshader->has_node_embeds(), Ref<Resource>());
```
Comment (KoBeWi) [inline editor/shader/visual_shader_editor_plugin.cpp]: It would be nice to have a clear message.

**Comment by KoBeWi** [comment]
The problem with this solution is that VisualShader nodes have to count the embeds manually. If someone adds a new node with a resource, but does not mark embed, it will miss the error.

File: editor/shader/visual_shader_editor_plugin.cpp (hunk 2 above)
Comment (ColinSORourke) [reply editor/shader/visual_shader_editor_plugin.cpp]: Adding "Cannot convert VisualShader to GDShader because VisualShader has embedded resources. Make resources unique before conversion." 

That's clear enough?

Comment (KoBeWi) [reply editor/shader/visual_shader_editor_plugin.cpp]: How does making the resource unique help?

File: scene/resources/visual_shader_nodes.cpp (hunk 1 above)
Comment (ColinSORourke) [reply scene/resources/visual_shader_nodes.cpp]: The focus of this fix is preventing a 'destructive' conversion. 

The problems are twofold:
A. VisualShader -> GDShader conversion doesn't work with any embeds because a GDShader is a text file without embeds. Any embed would need to be rebound as ShaderParameters on a ShaderMaterial. This is a fundamental consequence of providing this specific conversion. 
B. VisualShader -> GDShader conversion destroys sub resources embedded in the VisualShader because they have no where to go, a user could lose important data.

Fixing A requires a more drastic change, such as removing the VisualShader -> GDShader Conversion, and possibly replacing it with a VisualShader -> ShaderMaterial with embedded GDShader conversion.

In the meantime, fixing B just requires catching embedded sub-resources, and throwing error so the resources can't be deleted. I think 'Embed_count' was an imprecise name, I mean to keep SubResource count. This check in particular catches the case where an embedded sub resource is replaced with an embedded external resource.

I don't think a true embed count is useful - that value is simpler to keep track of, just whether or not each Ref is null. Tracking builtin resources is necessary currently to prevent the destructive conversion, and I think will be useful in future code working with this topic, as it would also need to differentiate BuiltIn resources from Externals.

File: editor/shader/visual_shader_editor_plugin.cpp (hunk 2 above)
Comment (ColinSORourke) [reply editor/shader/visual_shader_editor_plugin.cpp]: Somewhere I got the wrong idea that the "make unique" button in Inspector converted subresources to external resources. Disregard, that's on me

**Comment by QbieShay** [comment]
Came back to this. I wonder how we feel about adding a `hint_default("res://blabla.png")` ?

**Comment by ColinSORourke** [comment]
@KoBeWi 
> If someone adds a new node with a resource, but does not mark embed,

Assuming you are talking about VisualShaderNodeCustom - VisualShaderNodeCustom cannot have Resource Embeds, nothing in the [current API](https://docs.godotengine.org/en/4.4/classes/class_visualshadernodecustom.html#class-visualshadernodecustom-private-method-get-property-name) provides that functionality unless I am misunderstanding. 

@QbieShay 
> Came back to this. I wonder how we feel about adding a hint_default("res://blabla.png") ?

We talked about this in the Rendering Meeting today (Aug.20) (You were there :) ) and determined hint_default is not a workable feature.

Conclusion we reached in the Rendering Meeting for the issue is to throw a warning popup when the conversion plugin is called via Editor, and fall back to throwing an Error (like the current solution) when the conversion is initiated via code. I will adjust my fix to throw the popup when I have some spare time

**Comment by KoBeWi** [comment]
> Assuming you are talking about VisualShaderNodeCustom

No, adding a new visual shader node type in the engine. This PR modifies many classes, and in the future there may be more classes that will need similar checks.

**Comment by ColinSORourke** [comment]
> The problem with this solution is that VisualShader nodes have to count the embeds manually. If someone adds a new node with a resource, but does not mark embed, it will miss the error.
> No, adding a new visual shader node type in the engine. This PR modifies many classes, and in the future there may be more classes that will need similar checks.

Tracking embeds is necessary to catch and communicate this bad conversion behavior. I think the responsibility of tracking embeds is best assigned to individual node classes. Currently only 6 VisualShaderNode classes can have embedded resources, and I would say safe handling of resources on future node classes is important, and low cost.

I have a hard time envisioning an alternative architecture that defers the responsibility of tracking embeds somewhere else? Managing this information from the Visual Shader Editor Plugin seems like it would require more work than having each node track itself, and I don't know if the Visual Shader resource Class has enough info to do any of this tracking.

**Comment by ColinSORourke** [comment]
@KoBeWi Talked about it in the rendering meeting today, and have updated the PR with a different architecture for the fix. 

```
// Returns 0 if no embeds, 1 if external embeds, 2 if builtin embeds
int VisualShader::has_node_embeds() const {
	bool external_embeds = false;
	for (int i = 0; i < TYPE_MAX; i++) {
		for (const KeyValue<int, Node> &E : graph[i].nodes) {
			List<PropertyInfo> props;
			E.value.node->get_property_list(&props);
			// For classes that inherit from VisualShaderNode, the class properties start at the 12th, and the last value is always 'script'
			for (int i = 12; i < props.size() - 1; i++) {
				// VisualShaderNodeCustom cannot have embeds
				if (props.get(i).name == "VisualShaderNodeCustom") {
					break;
				}
				// Ref<Resource> properties get classed as type Variant::Object
				if (props.get(i).type == Variant::OBJECT) {
					Ref<Resource> res = E.value.node->get(props.get(i).name);
					if (res.is_valid()) {
						if (res->is_built_in()) {
							return 2;
						} else {
							external_embeds = true;
						}
					}
				}
			}
		}
	}

	return external_embeds;
}
```

This single function in the VisualShader class should be able to catch which child nodes have embedded resource properties without requiring any overhead on the VisualShaderNode classes

**Comment by KoBeWi** [comment]
I tested the MRP from #101375 with the newest version of this PR and it doesn't seem to do anything. Conversion is still broken and there is no error/warning. Maybe I'm doing something wrong, idk.

**Comment by ColinSORourke** [comment]
@KoBeWi My bad! Silly mistake, I've pushed a fix.

I changed an inner loop variable name 'i'->'j' to satisfy the code check that inner loop should not use same name as outer loop, but forget to replace in a few relevant locations. Fixed, tested, works.

File: editor/shader/visual_shader_editor_plugin.cpp [hunk 3]
```diff
@@ -8446,6 +8446,11 @@ bool VisualShaderConversionPlugin::handles(const Ref<Resource> &p_resource) cons
 Ref<Resource> VisualShaderConversionPlugin::convert(const Ref<Resource> &p_resource) const {
 	Ref<VisualShader> vshader = p_resource;
 	ERR_FAIL_COND_V(vshader.is_null(), Ref<Resource>());
+	int embed = vshader->has_node_embeds();
+	ERR_FAIL_COND_V_MSG(embed == 2, Ref<Resource>(), "Cannot convert VisualShader to GDShader because VisualShader has embedded subresources.");
+	if (embed == 1) {
+		WARN_PRINT("Visual Shader conversion cannot convert embedded resources. Resource references from Nodes will have to be rebound as ShaderParameters on a Material");
```
Comment (KoBeWi) [inline editor/shader/visual_shader_editor_plugin.cpp]: "embedded" is not correct here. They are not embedded, they are external dependencies of the shader.

btw are the shader parameters automatically created?

File: scene/resources/visual_shader.cpp [hunk 4]
```diff
@@ -967,6 +967,37 @@ void VisualShader::set_node_position(Type p_type, int p_id, const Vector2 &p_pos
 	g->nodes[p_id].position = p_position;
 }
 
+// Returns 0 if no embeds, 1 if external embeds, 2 if builtin embeds
```
Comment (KoBeWi) [inline scene/resources/visual_shader.cpp:970]: This sounds like it should be an enum, but since it's an editor one-time helper, hard-coding is fine too.

**Comment by KoBeWi** [comment]
Looks fine now, but I'd change the warning to a toaster message, as it's easy to miss.

Also converting the shader from the inspector results in clearing the property if there are sub-resources.


https://github.com/user-attachments/assets/3723eabb-452f-4396-9bfb-08a07a03c768

This could be avoided by returning the same shader instead of null.

**Comment by ColinSORourke** [comment]
@KoBeWi Updated warning language, and changed to throw a Toaster Message (when it can - I think there are cases where a conversion plugin can be invoked outside of editor)

> Also converting the shader from the inspector results in clearing the property if there are sub-resources.
> This could be avoided by returning the same shader instead of null.

Made this update too, although I think it'd be preferable if the Inspector Dock handled a null return and recognized the value as unchanged.  Looking for the file that manages that ;)

File: editor/shader/visual_shader_editor_plugin.cpp (hunk 3 above)
Comment (ColinSORourke) [reply editor/shader/visual_shader_editor_plugin.cpp]: Updated the language on the error.

As far as I can tell, yes the Shader Parameters are automatically created. A Texture2D Node (which could have an embedded texture) is converted to a Uniform in the GD Shader Code, which will be recognized as a Shader Parameter.

The VisualShader in the MRP has 2 Texture2D Nodes, they convert to code 
```
uniform sampler2D tex_frg_44;
uniform sampler2D tex_frg_43;
```
And when the converted GDShader is attached to a ShaderMaterial, the uniforms show up as a parameter again

File: editor/shader/visual_shader_editor_plugin.cpp [hunk 5]
```diff
@@ -8446,6 +8446,20 @@ bool VisualShaderConversionPlugin::handles(const Ref<Resource> &p_resource) cons
 Ref<Resource> VisualShaderConversionPlugin::convert(const Ref<Resource> &p_resource) const {
 	Ref<VisualShader> vshader = p_resource;
 	ERR_FAIL_COND_V(vshader.is_null(), Ref<Resource>());
+	int embed = vshader->has_node_embeds();
+
+	EditorToaster *toast = EditorToaster::get_singleton();
+	if (toast == nullptr) {
+		ERR_FAIL_COND_V_MSG(embed == 2, vshader, "Cannot convert VisualShader to GDShader because VisualShader has embedded subresources.");
+		if (embed == 1) {
+			WARN_PRINT("Visual Shader conversion cannot convert external dependencies. Resource references from Nodes will have to be rebound as ShaderParameters on a Material");
```
Comment (AThousandShips) [inline editor/shader/visual_shader_editor_plugin.cpp]:
```suggestion
			WARN_PRINT("Visual Shader conversion cannot convert external dependencies. Resource references from Nodes will have to be rebound as ShaderParameters on a Material.");
```

File: editor/shader/visual_shader_editor_plugin.cpp [hunk 6]
```diff
@@ -8446,6 +8446,20 @@ bool VisualShaderConversionPlugin::handles(const Ref<Resource> &p_resource) cons
...
+		}
+	} else if (embed == 2) {
+		toast->popup_str("Cannot convert VisualShader to GDShader because VisualShader has embedded subresources.", EditorToaster::SEVERITY_ERROR);
+		return vshader;
+	} else if (embed == 1) {
+		toast->popup_str("Visual Shader conversion cannot convert external dependencies. Resource references from Nodes will have to be rebound as ShaderParameters on a Material", EditorToaster::SEVERITY_WARNING);
```
Comment (AThousandShips) [inline editor/shader/visual_shader_editor_plugin.cpp]:
```suggestion
		toast->popup_str(TTR("Visual Shader conversion cannot convert external dependencies. Resource references from Nodes will have to be rebound as ShaderParameters on a Material."), EditorToaster::SEVERITY_WARNING);
```

**Comment by KoBeWi** [comment]
Looks like easy fix:
https://github.com/godotengine/godot/blob/adb2ec043ed61ea8451f2593171d7163303b7ba5/editor/inspector/editor_resource_picker.cpp#L487

**Comment by ColinSORourke** [comment]
Added a catch in Editor_Resource_Picker conversion to handle being given null by a failed conversion. Returned the Conversion plugin to always return null in a failed conversion.

Also added `emit_signal(SNAME("file_removed")` to the FileSystemDock conversion action - without this, if a VisualShader was converted to Shader, the ShaderEditor would keep the VisualShader version open as a hanging [unsaved]

File: editor/shader/visual_shader_editor_plugin.h [hunk 7]
```diff
@@ -30,6 +30,7 @@
 
 #pragma once
 
+#include "editor/gui/editor_toaster.h"
```
Comment (KoBeWi) [inline editor/shader/visual_shader_editor_plugin.h]: This should be in cpp file.

File: editor/shader/visual_shader_editor_plugin.cpp [hunk 8]
```diff
@@ -8446,6 +8446,20 @@ bool VisualShaderConversionPlugin::handles(const Ref<Resource> &p_resource) cons
...
+	int embed = vshader->has_node_embeds();
+
+	EditorToaster *toast = EditorToaster::get_singleton();
+	if (toast == nullptr) {
+		ERR_FAIL_COND_V_MSG(embed == 2, Ref<Resource>(), "Cannot convert VisualShader to GDShader because VisualShader has embedded subresources.");
+		if (embed == 1) {
+			WARN_PRINT("Visual Shader conversion cannot convert external dependencies. Resource references from Nodes will have to be rebound as ShaderParameters on a Material");
+		}
+	} else if (embed == 2) {
+		toast->popup_str("Cannot convert VisualShader to GDShader because VisualShader has embedded subresources.", EditorToaster::SEVERITY_ERROR);
```
Comment (KoBeWi) [inline editor/shader/visual_shader_editor_plugin.cpp]: Toaster messages should be translated.
```suggestion
		toast->popup_str(TTR("Cannot convert VisualShader to GDShader because VisualShader has embedded subresources."), EditorToaster::SEVERITY_ERROR);
```
Same below.

File: editor/inspector/editor_resource_picker.cpp [hunk 9]
```diff
@@ -484,8 +484,11 @@ void EditorResourcePicker::_edit_menu_cbk(int p_which) {
 				Vector<Ref<EditorResourceConversionPlugin>> conversions = EditorNode::get_singleton()->find_resource_conversion_plugin_for_resource(edited_resource);
 				ERR_FAIL_INDEX(to_type, conversions.size());
 
-				edited_resource = conversions[to_type]->convert(edited_resource);
-				_resource_changed();
+				Ref<Resource> converted_resource = conversions[to_type]->convert(edited_resource);
+				if (!converted_resource.is_null()) {
```
Comment (KoBeWi) [inline editor/inspector/editor_resource_picker.cpp]:
```suggestion
				if (converted_resource.is_valid()) {
```

File: editor/docks/filesystem_dock.cpp [hunk 10]
```diff
@@ -1926,6 +1926,7 @@ void FileSystemDock::_convert_dialog_action() {
 		Ref<Resource> new_resource = converted_resources.get(i);
 
 		// Overwrite the path.
+		emit_signal(SNAME("file_removed"), original_resource->get_path());
```
Comment (KoBeWi) [inline editor/docks/filesystem_dock.cpp]:
```suggestion
		// Notify plugins that the original resource is removed.
		emit_signal(SNAME("file_removed"), original_resource->get_path());
		// Overwrite the path.
```

**Review by KoBeWi — APPROVED** [review]

**Comment by ColinSORourke** [comment]
Pushed a build addressing @KoBeWi  and @AThousandShips  comments.

**Review by AThousandShips — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
