### PR TITLE
Remap script path when registering class.

### LINKED ISSUE #40991: Custom class not working with 3.2.3 RC3, but it works in RC2
**Godot version:**
3.2.3 RC3

**OS/device including version:**
Windows 10

**Issue description:**
I found some weird difference between RC2 and RC3 that I can't figure out.

My HTML5 build crashes when a custom class is included, and complains "identifier "SafeNum" isn't a valid type (not a script or class), or couldn't be found on base "self"."

The class DOES work in RC2 (and everything before that), so this must be a new bug.

**Steps to reproduce:**
Just include my class file (that I pasted below), and use it like this:
var diamonds:SafeNum = SafeNum.new(1)

**Minimal reproduction project:**

```class_name SafeNum
extends Reference

var _num = null
var _permutator = null
var _permutation = null

class DynNum:
    var _num:float
    func _init(n):
        _num = n
        pass
    func getValue():
        return _num

func _init(n):
    _setUnchecked(n)
    pass

func _setUnchecked(n):
    _num = DynNum.new(n)
    _permutator = DynNum.new(randf()+1.0)
    _permutation = DynNum.new(_num.getValue() * _permutator.getValue())
    return self

func _setChecked(n):
    if _permutation.getValue() != (_num.getValue() * _permutator.getValue()):
        printerr("MEMORY CHEAT DETECTED")
    return _setUnchecked(n)

func getValue():
    _setChecked(_num.getValue())
    return _num.getValue()
    
func setValue(n):
    return _setChecked(n)
    
func plus(n):
    return _setChecked(_num.getValue() + n)

func minus(n):
    return _setChecked(_num.getValue() - n)

func multiply(n):
    return _setChecked(_num.getValue() * n)
    
func divide(n):
    return _setChecked(_num.getValue() / n)```

### PR DESCRIPTION
**Pull request by Faless**
Was causing `class_name`-defined scripts to not being loaded in exported games due to the remap from `*.gd` to `*.gdc`/`*.gde`.

**Note**: I could have used `ResourceLoader::exists` directly, but it seems to come with a more complex logic (thus slower).
But I'd like an opinion on this from someone more knowledgable on the topic (since e.g. ResourceLoader would allow us to specify the exptected type).  @vnen @Xrayez ?

Fixes #40991

### CODE REVIEW

**Comment by Xrayez** [comment]
> Was causing `class_name`-defined scripts to not being loaded in exported games due to the remap from `*.gd` to `*.gdc`/`*.gde`.

I think this is due to #40781 (CC @Rubonnek). I'm surprised about myself why I didn't think about this before because I've done similar path remapping workarounds/hacks: #33266. 😃

> **Note**: I could have used `ResourceLoader::exists` directly, but it seems to come with a more complex logic (thus slower).

According to #39797, yeah it indeed may be slow, and may impact #39841, but it may be different for `exists` specifically.

If your solution works, I think it's ok then, especially since the task is to fix the regression first, then we should re-evaluate the way scripts are remapped, because it's very easy to break something with the current mechanism.

File: core/script_language.cpp [hunk 1]
```diff
@@ -163,7 +164,7 @@ void ScriptServer::init_languages() {
 
 			for (int i = 0; i < script_classes.size(); i++) {
 				Dictionary c = script_classes[i];
-				if (!c.has("class") || !c.has("language") || !c.has("path") || !FileAccess::exists(c["path"]) || !c.has("base")) {
+				if (!c.has("class") || !c.has("language") || !c.has("path") || !FileAccess::exists(ResourceLoader::path_remap(c["path"])) || !c.has("base")) {
```
Comment (Xrayez) [inline core/script_language.cpp:167]: Would `FileAccess::exists` work in exported project anyways? May be it's better to omit the check in release builds?

**Comment by vnen** [comment]
TBH I'm not familiar with this code and the release target is broken on master so I have not tested the export. But yes, if you need to check if the file exists you need to use the remapped path.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Comment by akien-mga** [comment]
Reverted with #41501 as per https://github.com/godotengine/godot/issues/40584#issuecomment-679470085.
The revert will also be cherry-picked for `3.2`.
