### PR TITLE
Massively optimize canvas 2D rendering by using vertex buffers

### LINKED ISSUE #104194: Performance regression in 4.4 on Android after introducing batching (GPU bottleneck)
### Tested versions

Playable on 4.4 for android
This performance issue is in 4.4

### System information

Android 13 Go Edition GPU Vendor: (Imagination Technologies) GPU Render: (PowerVR Rogue GE8300 OpenGL ES 3.2) API Level 33 Build ID:(ML_SO0S_SO4S_M7_WIFI.V3_20240626) CPU (ARM Cortex-A53 Model:A133 Revision: r0p4)

### Issue description

Dear developers,

Since I updated Godot 4.3 stable to 4.4 stable, I have had performance problems on my tablet "Multilazer M7_wifi" in the previous version the editor runs smoothly. And today when I went to do a test project just to do things with animationPlayer the android ended up closing and this never happened. with 4.3.
I know that the hardware of my device is weak but it is the first time that this happens and also continuous crashes

I used a translator for this, and this is my first report that I will do on github so I do not know yet how to mark the labels Ok

### Steps to reproduce

Just Create any project in Godot with an Old Hardware
"more specifically on a 2014 Hardware", and this will happen

### Minimal reproduction project (MRP)

Any Project In Godot 4.4 On Old Hardware

### PR DESCRIPTION
**Pull request by stuartcarnie**
# Summary

Closes #104194

This PR is a performance optimisation for the Canvas RD renderer after introducing batching. @clayjohn has observed a regression in performance under certain combinations and older hardware that this PR is intended to address. It should not regress existing performance gains. The core change is to switch instance data from a uniform buffer (shader storage buffer object) to a vertex buffer object (VBO).

> [!CAUTION]
>
> D3D12 needs a validate `vertex_format_create` to use the new `VertexAttribute::binding` member and to update `command_render_bind_vertex_buffers` to handle UMA buffers.

# TODOs

- [x] Remove all the USE_VAO stuff, as that was just me trying to work with both
- [x] Fix the PushConstant data so that it's size is reduced from 144 bytes to 84 (+ padding)
- [x] Add the `dynamic_offset` index to the vertex buffer binding. Update the drivers to use the offset (already similar for uniforms):
  - [x] Metal
  - [x] Vulkan
  - [x] D3D12
- [x] Clean up the new dynamic vertex binding API and streamline it (switch to Span in the RenderDeviceGraph, so we don't have to allocate)
- [x] Extend `VertexAttribute` change, so a set of attributes can bind to the same buffer
  - [x] This will make the API more efficient as drivers will only need to create a single buffer binding and consume a single slot.

# Testing

We must verify all rendered command types:

- [x] TYPE_RECT
- [x] TYPE_NINEPATCH,
- [x] TYPE_POLYGON,
- [x] TYPE_PRIMITIVE,
- [x] TYPE_MESH,
- [x] TYPE_MULTIMESH,
- [x] TYPE_PARTICLES,

Verify:

- [x] `INSTANCE_FLAGS_USE_MSDF`
- [x] `INSTANCE_FLAGS_USE_LCD`

# Benchmarks

See below for more detail

|             | Adreno 530 | Adreno 640 | Mali G715 | Intel Xe | RX 6900XT | Mali G68 MP5 |
|-------------|------------|------------|-----------|----------|-----------|--------------|
| improvement | 4-5x       | 1.5-2x     | 1-1.25x   | 2-3x     | 1x        | 1.1x         |

### CODE REVIEW

File: drivers/d3d12/rendering_device_driver_d3d12.cpp
Comment (stuartcarnie) [inline drivers/d3d12/rendering_device_driver_d3d12.cpp:1]: D3D12 will still need to implement the changes to `command_render_bind_vertex_buffers` and verify that `vertex_format_create` is correct.

File: core/templates/hash_map.h [hunk 1]
```diff
@@ -609,6 +626,36 @@ class HashMap : private Allocator {
 		}
 	}
 
+	HashMap &operator=(HashMap &&p_other) noexcept {
```
Comment (stuartcarnie) [inline core/templates/hash_map.h]: We can `std::move` so we can transfer to another type. I'm using it in `vertex_format_create` for the `bindings` member:

```cpp
	VertexDescriptionCache &ce = vertex_formats.insert(id, VertexDescriptionCache())->value;
	ce.vertex_formats = vertex_descriptions;
	ce.bindings = std::move(bindings);
	ce.driver_id = driver_id;
```

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 2]
```diff
@@ -772,7 +772,7 @@ void RenderForwardClustered::SceneState::grow_instance_buffer(RenderListType p_r
 		if (instance_buffer[p_render_list].get_size(0u) < p_req_element_count * sizeof(SceneState::InstanceData)) {
 			instance_buffer[p_render_list].uninit();
 			uint32_t new_size = nearest_power_of_2_templated(MAX(uint64_t(INSTANCE_DATA_BUFFER_MIN_SIZE), p_req_element_count));
-			instance_buffer[p_render_list].set_size(0u, new_size * sizeof(SceneState::InstanceData), true);
+			instance_buffer[p_render_list].set_storage_size(0u, new_size * sizeof(SceneState::InstanceData));
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:775]: We can now create vertex buffers, so `true` was no longer valid. Introduced specifically named APIs to create a UMA for SSBO, VBO, etc

File: servers/rendering/renderer_rd/shaders/canvas.glsl
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/shaders/canvas.glsl:1]: A lot of the naming was taken from the compatibility version of `canvas.glsl`

File: servers/rendering/renderer_rd/shaders/canvas.glsl [hunk 3]
```diff
@@ -487,29 +600,30 @@ void main() {
...
 
-#ifndef USE_PRIMITIVE
-	if (bool(draw_data.flags & INSTANCE_FLAGS_USE_MSDF)) {
-		float px_range = draw_data.ninepatch_margins.x;
-		float outline_thickness = draw_data.ninepatch_margins.y;
-		//float reserved1 = draw_data.ninepatch_margins.z;
-		//float reserved2 = draw_data.ninepatch_margins.w;
+#if !defined(USE_ATTRIBUTES) && !defined(USE_PRIMITIVE)
+	// only used by TYPE_RECT
+	if (bool(read_draw_data_flags & INSTANCE_FLAGS_USE_MSDF)) {
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/shaders/canvas.glsl]: As noted, this is only ever used by TYPE_RECT, so no sense including it when `USE_ATTRIBUTES` is defined. Should be a minor optimisation for PARTICLE, MESH and MULTI_MESH types.

File: servers/rendering/renderer_rd/shaders/canvas_uniforms_inc.glsl [hunk 4]
```diff
@@ -36,7 +35,8 @@ struct InstanceData {
 	vec2 pad;
 
 #endif
-	vec2 color_texture_pixel_size;
+	uint flags;
+	uint instance_uniforms_ofs;
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/shaders/canvas_uniforms_inc.glsl:37]: Moved these to match the compatibility version

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 5]
```diff
@@ -1954,6 +1952,64 @@ RendererCanvasRenderRD::RendererCanvasRenderRD() {
...
 
+	{
+		Vector<RD::VertexAttribute> vf;
+		uint32_t offset = 0;
+		RD::VertexAttribute vd;
+		vd.format = RD::DATA_FORMAT_R32G32B32A32_SFLOAT;
+		vd.stride = sizeof(InstanceData);
+		vd.frequency = RD::VERTEX_FREQUENCY_INSTANCE;
+		vd.location = 8;
+		vd.binding = 0; // Explicitly assign binding 0 for instance data.
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:1968]: 🏎️ We're taking advantage of the new `binding` field, which means we are using the same buffer binding slot for all vertex attributes. Rather than binding 8 buffers (with potentially different frequency and stride values) every draw call, we now only bind one buffer. 

A binding specifies how the buffer is read by the GPU, controlled by `frequency` and `stride`. Assuming the driver doesn't coalesce all 8 bindings, that reduces bookkeeping from 8 to 1 buffer.

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 6]
```diff
@@ -2584,7 +2640,7 @@ void RendererCanvasRenderRD::_record_item_commands(const Item *p_item, RenderTar
 				instance_data->modulation[2] = color.b;
 				instance_data->modulation[3] = color.a;
 
-				_add_to_batch(r_batch_broken, r_current_batch);
+				r_current_batch->instance_count = 0x80000000;
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp]: We're not adding an instance to the VBO buffer, but instance_count > 0 for the batch to be committed. This is just a flag that is masked out later.

File: servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp [hunk 7]
```diff
@@ -3182,13 +3252,18 @@ RendererCanvasRenderRD::Batch *RendererCanvasRenderRD::_new_batch(bool &r_batch_
...
+	new_batch.push_data = InstanceData();
 	state.current_batch_index++;
 	state.canvas_instance_batches.push_back(new_batch);
 	return &state.canvas_instance_batches[state.current_batch_index];
 }
 
 void RendererCanvasRenderRD::_add_to_batch(bool &r_batch_broken, Batch *&r_current_batch) {
+	DEV_ASSERT(r_current_batch->command_type == Item::Command::TYPE_RECT ||
+			r_current_batch->command_type == Item::Command::TYPE_NINEPATCH ||
+			r_current_batch->command_type == Item::Command::TYPE_PRIMITIVE);
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:3281]: Make sure we don't accidentally try to add the other types to the batch

File: servers/rendering/rendering_device.cpp [hunk 8]
```diff
@@ -3087,14 +3088,20 @@ RID RenderingDevice::vertex_buffer_create(uint32_t p_size_bytes, Span<uint8_t> p
 	if (p_creation_bits.has_flag(BUFFER_CREATION_AS_STORAGE_BIT)) {
 		buffer.usage.set_flag(RDD::BUFFER_USAGE_STORAGE_BIT);
 	}
+	if (p_creation_bits.has_flag(BUFFER_CREATION_DYNAMIC_PERSISTENT_BIT)) {
+		buffer.usage.set_flag(RDD::BUFFER_USAGE_DYNAMIC_PERSISTENT_BIT);
+
+		// Persistent buffers expect frequent CPU -> GPU writes, so GPU writes should avoid the same path.
+		buffer.usage.clear_flag(RDD::BUFFER_USAGE_TRANSFER_TO_BIT);
+	}
```
Comment (stuartcarnie) [inline servers/rendering/rendering_device.cpp:3097]: We can now use UMA for vertex buffers

File: servers/rendering/rendering_device.cpp [hunk 9]
```diff
@@ -3126,24 +3133,49 @@ RenderingDevice::VertexFormatID RenderingDevice::vertex_format_create(const Vect
...
+	RDD::VertexFormatID driver_id = driver->vertex_format_create(vertex_descriptions, bindings);
 	ERR_FAIL_COND_V(!driver_id, 0);
 
 	VertexFormatID id = (vertex_format_cache.size() | ((int64_t)ID_TYPE_VERTEX_FORMAT << ID_BASE_SHIFT));
 	vertex_format_cache[key] = id;
-	vertex_formats[id].vertex_formats = p_vertex_descriptions;
-	vertex_formats[id].driver_id = driver_id;
+	VertexDescriptionCache &ce = vertex_formats.insert(id, VertexDescriptionCache())->value;
+	ce.vertex_formats = vertex_descriptions;
+	ce.bindings = std::move(bindings);
```
Comment (stuartcarnie) [inline servers/rendering/rendering_device.cpp]: Take advantage of the move-assignment operator to avoid reallocating.

File: servers/rendering/rendering_device.cpp [hunk 10]
```diff
@@ -3171,39 +3197,53 @@ RID RenderingDevice::vertex_array_create(uint32_t p_vertex_count, VertexFormatID
...
+			continue;
+		}
+
+		unique_buffers.insert(buf);
 
 		if (buffer->draw_tracker != nullptr) {
 			vertex_array.draw_trackers.push_back(buffer->draw_tracker);
 		} else {
-			vertex_array.untracked_buffers.insert(p_src_buffers[i]);
+			vertex_array.untracked_buffers.insert(buf);
```
Comment (stuartcarnie) [inline servers/rendering/rendering_device.cpp:3247]: There are many cases where the engine binds the same buffer multiple times. By tracking unique buffers, we only perform this logic once, which reduces unnecessary allocations, as `draw_trackers` is a vector, so the same buffer would be added multiple times.

File: servers/rendering/rendering_device.cpp [hunk 11]
```diff
@@ -4666,6 +4706,101 @@ void RenderingDevice::draw_list_bind_vertex_array(DrawListID p_list, RID p_verte
 	}
 }
 
+void RenderingDevice::draw_list_bind_vertex_buffers_format(DrawListID p_list, VertexFormatID p_vertex_format, uint32_t p_vertex_count, const Span<RID> &p_vertex_buffers, const Span<uint64_t> &p_offsets) {
```
Comment (stuartcarnie) [inline servers/rendering/rendering_device.cpp:4710]: I still have to tidy up this function and remove some of the unnecessary logic. It _behaves_ the same, so for performance testing it should be fine.

File: servers/rendering/rendering_device_driver.h [hunk 12]
```diff
@@ -301,7 +302,7 @@ class RenderingDeviceDriver : public RenderingDeviceCommons {
 	/**** VERTEX ARRAY ****/
 	/**********************/
 
-	virtual VertexFormatID vertex_format_create(VectorView<VertexAttribute> p_vertex_attribs) = 0;
+	virtual VertexFormatID vertex_format_create(Span<VertexAttribute> p_vertex_attribs, const VertexAttributeBindingsMap &p_vertex_bindings) = 0;
```
Comment (stuartcarnie) [inline servers/rendering/rendering_device_driver.h:305]: Switching to Span means we can avoid allocations at call sites. We should evaluate all calls and use FixedVector, as the sizes in the renderer_rd are all known at compile time.

**Review by stuartcarnie — COMMENTED** [review]
@clayjohn, et al some notes for your information

File: core/templates/hash_map.h [hunk 13]
```diff
@@ -71,6 +71,7 @@ class HashMap : private Allocator {
 	static constexpr uint32_t MIN_CAPACITY_INDEX = 2; // Use a prime.
 	static constexpr float MAX_OCCUPANCY = 0.75;
 	static constexpr uint32_t EMPTY_HASH = 0;
+	using KV = KeyValue<TKey, TValue>; // Type alias for easier access to KeyValue.
```
Comment (stuartcarnie) [inline core/templates/hash_map.h]: Particularly useful when you have a typedef such as:

```cpp
typedef HashMap<uint32_t, VertexAttributeBinding> VertexAttributeBindingsMap;
```

as you can then use:

```
for (const VertexAttributeBindingsMap::KV &ky : p_vertex_bindings) {
  // ...
}
```

vs

```cpp
for (const KeyValue<uint32_t, VertexAttributeBinding> &kv : p_vertex_bindings) {
  // ...
}
```

Also, if you change the Key or Value type, these call sites don't need to be updated.

File: servers/rendering/multi_uma_buffer.h [hunk 14]
```diff
@@ -320,7 +353,7 @@ class MultiUmaBuffer : public MultiUmaBufferBase {
 
 	/**
 	 * @param p_append	True if you wish to append more data to existing buffer.
-	 * @return			True if it's possible to append. False if the internal buffer changed.
+	 * @return			False if it's possible to append. True if the internal buffer changed.
```
Comment (stuartcarnie) [inline servers/rendering/multi_uma_buffer.h:356]: This was incorrect.

File: core/templates/hash_map.h (hunk 1 above)
Comment (Ivorforce) [reply core/templates/hash_map.h]: This is worth a separate core PR. Move semantics are desirable for all our containers, and that would make this PR completely non-core.

**Comment by clayjohn** [comment]
Some preliminary testing using a modified MRP from https://github.com/godotengine/godot/issues/104194

[android-4.4-perf-clay.zip](https://github.com/user-attachments/files/23515624/android-4.4-perf-clay.zip)

The original MRP has a loop that adds SubViewports that have a single Sprite rendered to them, then are rendered to the screen. 

That means that in a loop of N, we rendering N * 2 draw calls using N + 1 render passes (i.e. N render passes with 1 draw call and 1 render pass with N draw calls). None of the draw calls are batched, so this MRP exposes the worst case performance. It can be CPU bottlenecked on some hardware and GPU bottlenecked on others. 

The second test case renders N sprites with the same texture in the same location. This is the best case for batching. The number of draw calls depends on the hardware's capabilities, but it is often only 1 or a handful. Drawing that many Sprites in one location is a weird edge case for TBDR GPUs, so Mali GPUs and Apple silicon GPUs may not reflect typical performance scenarios. 

```
# 2000 Sprites Adreno 530
4.3: 55 FPS
4.5.1: 10 FPS
PR:  43 FPS

# 100 viewports Adreno 530
4.3 36 FPS
4.5.1: 6 FPS
PR: 30 FPS

# 10000 Sprites Adreno 640
4.3 25 FPS
4.5.1: 19 FPS
PR: 37 FPS

# 500 viewports Adreno 640
4.3 18 FPS
4.5.1: 12 FPS
PR: 18 FPS

# 10000 Sprites Mali G715
4.3 52 FPS
4.5.1: 45 FPS
PR: 57 FPS

# 500 viewports Mali G715
4.3 32 FPS
4.5.1: 24 FPS
PR: 25 FPS (This is likely caused by an unrelated bug and should be investigated)

# 10000 Sprites Intel XE
4.3: 80 FPS
4.5.1: 23 FPS
PR: 102 FPS

# 500 viewports Intel XE
4.3: 28 FPS
4.5.1: 16 FPS
PR: 39 FPS

# 10000 Sprites Windows - Ryzen 5 9600X - Radeon RX 6900 XT
4.3: 675 FPS
4.5.1:  752 FPS
PR: 856 FPS
Master: 839 FPS

# 500 viewports Windows - Ryzen 5 9600X - Radeon RX 6900 XT
4.3: 1475 FPS
4.5.1:  1924 FPS
PR: 2307 FPS
Master: 2206 FPS

# 50000 Sprites Windows - Ryzen 5 9600X - Radeon RX 6900 XT
4.3: 102 FPS
4.5.1:  170 FPS
PR: 145 FPS
Master: 145 FPS

# 10000 viewports Windows - Ryzen 5 9600X - Radeon RX 6900 XT
4.3:  97 FPS (GPU Bound)
4.5.1:  13 FPS
PR: 98 FP
Master: CRASH
```

**Comment by blueskythlikesclouds** [comment]
I can implement the D3D12 changes. Should I make a PR to your fork?

File: core/templates/hash_map.h [hunk 15]
```diff
@@ -590,6 +591,22 @@ class HashMap : private Allocator {
 		}
 	}
 
+	HashMap(HashMap &&p_other) noexcept {
```
Comment (AThousandShips) [inline core/templates/hash_map.h]: Do these `noexcept` have any effect? We don't use exceptions and as far as I know we don't use this directive elsewhere

File: doc/classes/RDVertexAttribute.xml [hunk 16]
```diff
@@ -9,6 +9,10 @@
 	<tutorials>
 	</tutorials>
 	<members>
+		<member name="binding" type="int" setter="set_binding" getter="get_binding" default="4294967295">
+			The index of the buffer in the vertex buffer array to bind this vertex attribute. When set to -1, it defaults to the index of the attribute.
+			[b]Note:[/b] You cannot mix binding explicitly assigned attributes with implicitly assigned ones (i.e. -1). Either all attributes must have their binding set to -1, or all must have explicit bindings.
```
Comment (AThousandShips) [inline doc/classes/RDVertexAttribute.xml]:
```suggestion
			[b]Note:[/b] You cannot mix binding explicitly assigned attributes with implicitly assigned ones (i.e. [code]-1[/code]). Either all attributes must have their binding set to [code]-1[/code], or all must have explicit bindings.
```

File: core/templates/hash_map.h (hunk 15 above)
Comment (stuartcarnie) [reply core/templates/hash_map.h]: True – I'll remove them

File: core/templates/hash_map.h (hunk 1 above)
Comment (clayjohn) [reply core/templates/hash_map.h]: @Ivorforce Are you okay with merging this change in this PR? I don't really want to block this PR while we wait for this optimization to be applied to other containers. 

My preference in general is for core optimizations to be in the same PR where they are used as well so the git history shows why certain changes were needed

**Review by clayjohn — APPROVED** [review]
Amazing work! I have tested extensively on Linux, Windows, and Android in addition to your testing on MacOS. So I think we have covered our bases. 

From testing it appears we have resolved the performance regression introduced from batching in almost all cases and even improved performance in many cases. At this point I think this PR is ready to go and get wider testing!

While discussing this with Stuart, we identified some further optimizations we could make. But the current state is really good and gives us the majority of possible gains with the least intrusive changes

File: doc/classes/RDVertexAttribute.xml (hunk 16 above)
Comment (AThousandShips) [inline doc/classes/RDVertexAttribute.xml]:
```suggestion
			[b]Note:[/b] You cannot mix binding explicitly assigned attributes with implicitly assigned ones (i.e. [code]-1[/code]). Either all attributes must have their binding set to [code]-1[/code], or all must have explicit bindings.
```

File: doc/classes/RDVertexAttribute.xml [hunk 17]
```diff
@@ -9,6 +9,10 @@
 	<tutorials>
 	</tutorials>
 	<members>
+		<member name="binding" type="int" setter="set_binding" getter="get_binding" default="4294967295">
+			The index of the buffer in the vertex buffer array to bind this vertex attribute. When set to -1, it defaults to the index of the attribute.
```
Comment (AThousandShips) [inline doc/classes/RDVertexAttribute.xml]:
```suggestion
			The index of the buffer in the vertex buffer array to bind this vertex attribute. When set to [code]-1[/code], it defaults to the index of the attribute.
```

File: core/templates/hash_map.h (hunk 1 above)
Comment (Ivorforce) [reply core/templates/hash_map.h]: Generally agree that optimizations should be introduced only when needed, but move semantics are needed for all our containers (and most of them do have it already). Looks like I just forgot to add them for hash maps.
Core changes particularly have a habit of being 'snuck in' in bigger PRs, which can make it very hard to spot and estimate the repercussions of. Generally I would expect core changes to be beneficial to not only the use-case of a PR, but the codebase in general. For example, I would normally expect benchmarks for common cases, if it's optimization related. That's why I prefer them in separate PRs when possible.

Anyway, they look fine to me (granted `noexcept` is removed), so I'm OK with merging them in here.

**Comment by software-2** [comment]
I ran some tests on my Samsung Galaxy Tab S9 FE+, which seems to be a worst-case device, using my original test program ([here](https://github.com/godotengine/godot/issues/104194#issuecomment-2755104452)). @clayjohn should I run your modified version? (I didn't see it until after I finished)

I couldn't get this PR branch to run (the android app would hang at the splash screen). Master at bd2ca13c6f3a5198eac035c855dcd1759e077313 ran just fine, so I pulled in this PR's commits on top of that.


4.5-dev3: 68-72fps lows, sometimes hitting 80
master: 72-80 lows, but frequently hitting the device max of 90
master + PR: 86-90 consistently, but I'm seeing dips sometimes to 74 briefly about every 10 seconds. (Those spikes seem to disappear when I have the Visual Profiler running, keeping a consistent 86+ when the profiler is on.)

For comparison, 4.3-stable (prior to the batching changes) gives lower overall frames (~82 on average), but does not have the occasional framerate dip.

This is absolutely a major improvement!

**Comment by clayjohn** [comment]
> I ran some tests on my Samsung Galaxy Tab S9 FE+, which seems to be a worst-case device, using my original test program ([here](https://github.com/godotengine/godot/issues/104194#issuecomment-2755104452)). @clayjohn should I run your modified version? (I didn't see it until after I finished)

No need. My modified version just added a couple lines of code to also test rendering a high number of sprites in a single batch

> I couldn't get this PR branch to run (the android app would hang at the splash screen). Master at [bd2ca13](https://github.com/godotengine/godot/commit/bd2ca13c6f3a5198eac035c855dcd1759e077313) ran just fine, so I pulled in this PR's commits on top of that.

Sorry about that, there was an android regression two days ago that was fixed yesterday https://github.com/godotengine/godot/pull/112716. Pulling in this change on top of master was the right thing to do!

> For comparison, 4.3-stable (prior to the batching changes) gives lower overall frames (~82 on average), but does not have the occasional framerate dip.

Depending on your build settings, the dip may go away with official builds. We enable swappy by default on official builds which helps reduce frame dips. By default, swappy is disabled for custom build

**Comment by stuartcarnie** [comment]
@AThousandShips I've removed the `except` and fixed the documentation and added you as a co-author.

@clayjohn shall I'll wait for @Ivorforce's response before removing the move semantics from `HashMap`?

**Comment by Ivorforce** [comment]
I've [already replied](https://github.com/godotengine/godot/pull/112481#discussion_r2526800492); in short: The `HashMap` changes look good to me.

File: core/templates/hash_map.h (hunk 1 above)
Comment (stuartcarnie) [reply core/templates/hash_map.h]: `noexcept` has been removed - thanks for the feedback!

**Comment by Repiteo** [comment]
Thanks!

**Comment by YeldhamDev** [comment]
This PR is still has regressions, see #112938.
