### PR TITLE
[3.5] Avoid GL undefined behavior in ubershaders

### LINKED ISSUE #62590: [3.5 RC 5] GLES3 projects with Asynchronous shaders causing `_gl_debug_print` errors.
### Godot version

3.5 RC5

### System information

Linux, Nvidia 1650GTi, GLES3

### Issue description

Running a GLES3 project with Godot 3.5 RC5 appears to cause the following (non-fatal) error:
`E 0:00:00.347   _gl_debug_print: GL ERROR: Source: OpenGL	Type: Undefined behavior	ID: 131222	Severity: Medium	Message: Program undefined behavior warning: The current GL state uses a sampler (0) that has depth comparisons disabled, with a texture object (0) with a non-depth format, by a shader that samples it with a shadow sampler. Using this state to sample would result in undefined behavior.
  <C++ Source>  drivers/gles3/rasterizer_gles3.cpp:124 @ _gl_debug_print()`

GLES2 does not cause this error. Things appear to run as expected despite said error(s).

### Steps to reproduce

Run any GLES3 project.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by RandomShaper**
Quoting here the big comment in the code:
> If an ubershader has shadow samplers, they are generally not used if the current material has shadowing disabled, but that also implies the rasterizer won't do any preparation to the relevant shadow samplers (which won't really exist, so that's the correct way in a conditioned shader).
> However, in the case of the ubershader those shadow samplers are unconditionally declared, although potentially unused and thus "uninitialized". Sampling in that situation (compare disabled, no depth texture bound) is undefined behavior for GL.
> And that's a problem for us because, even if dynamic branching will serve to avoid using the unprepared sampler when shadowing is not enabled, the GPU may still run the other branch. And it's not just that the results from the sampling are undefined (that wouldn't be a problem and we could just ignore the warning); the problem is that sampling in that state is fully UB.

Fixes #62590.

### CODE REVIEW

File: drivers/gles3/shader_gles3.cpp [hunk 1]
```diff
@@ -195,6 +195,27 @@ bool ShaderGLES3::_bind_ubershader() {
 	CRASH_COND(new_conditional_version.version >= 0x80000000);
 #endif
 	glUniform1i(conditionals_uniform, new_conditional_version.version);
+
+	// This is done to avoid running into the GL UB message id 131222. Long explanation:
+	// If an ubershader has shadow samplers, they are generally not used if the current material has shadowing disabled,
+	// but that also implies the rasterizer won't do any preparation to the relevant shadow samplers (which won't really exist,
+	// so that's the correct way in a conditioned shader).
+	// However, in the case of the ubershader those shadow samplers are unconditionally declared, although potentially unused and
+	// thus "uninitialized". Sampling in that situation (compare disabled, no depth teture bound) is undefined behavior for GL.
```
Comment (akien-mga) [inline drivers/gles3/shader_gles3.cpp:204]:
```suggestion
	// thus "uninitialized". Sampling in that situation (compare disabled, no depth texture bound) is undefined behavior for GL.
```

**Comment by akien-mga** [comment]
```
./drivers/gles3/shaders/tonemap.glsl.gen.h:228:182: error: no matching function for call to 'TonemapShaderGLES3::setup(const char* [25], int, const char* [8], int, ShaderGLES3::AttributePair*&, int, ShaderGLES3::TexUnitPair [4], int, ShaderGLES3::UBOPair*&, int, const ShaderGLES3::Feedback*&, int, const char [280], const char [16998], const int&, const int&)'
```
Might be an issue with caching / SCons not properly seeing that it needs to regenerate the files.maybe we need to add a `Depends()` on the .py file so it recreates headers when the python script is modified.

**Comment by RandomShaper** [comment]
I can't understand the build errors on Linux-editor. Is maybe the CI taking something from cache that it shouldn't?

**Comment by akien-mga** [comment]
Maybe adding something here:
https://github.com/godotengine/godot/blob/2b31c88982e4fdcbc8f0d7ba5d02cfd451a1df88/SConstruct#L774

Like:
```
env.Depends(GLSL_BUILDERS["GLES3_GLSL"], "#gles3_builders.py")
```
And same for the RD ones. On phone so can't easily test to confirm.

**Comment by RandomShaper** [comment]
Thanks, but I don't see how I can apply that to 3.x. It seems something similar is already being done.

**Comment by akien-mga** [comment]
This should do the trick: https://github.com/godotengine/godot/pull/62634

**Comment by RandomShaper** [comment]
@akien-mga, you're my build system hero.

**Review by lawnjelly — APPROVED** [review]
Looks fine to me from looking through. :+1:

**Comment by akien-mga** [comment]
Thanks!
