### PR TITLE
[Windows] Use `GetFileTime` for `FileAccess`

### LINKED ISSUE #74816: "Files are newer on disk" warnings after shift to Daylight Savings Time
### Godot version

4.0

### System information

Windows 10

### Issue description

Last night we shifted to Daylight Savings Time in the US.  I left Godot running overnight.  When I awoke, there was a dialog on screen listing many of the files in the project and saying that the files were newer on disk.  This hasn't happened before so I assume it is the result of clocks moving forward overnight.

### Steps to reproduce

N/A - see above.

### Minimal reproduction project

N/A

### LINKED ISSUE #92911: Same file returns different modified time in different Godot builds
### Tested versions

v4.3.beta1.official [a4f2ea91a]
v4.3.beta.custom_build [a4f2ea91a]

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I noticed that whenever I open my project in a custom build, the scene groups are being re-scanned for no reason. Then it happens again when I use official build. Turns out that's because the 2 builds for some reason return different modified time for a file, which causes filesystem timestamp mismatch.

I made a simple editor script to illustrate the issue. I run it in 2 Godot instances build from the same commit, but one is official and one isn't:

https://github.com/godotengine/godot/assets/2223172/b2c4c3ba-588c-4e58-8736-0b294cf86058

I tested it with 2 files. One was a scene that belongs to a project, the other one was a random file I had in my downloads folder. The issue did not occur in case of the other file.

### Steps to reproduce

1. Print a modified time of a scene file that belongs to a different project
2. Compare results from official and custom builds

### Minimal reproduction project (MRP)

```GDScript
@tool
extends EditorScript

func _run() -> void:
	print(FileAccess.get_modified_time("path/goes/here.tscn"))
```

### LINKED ISSUE #96810: [4.4.dev2, Windows] Changes to exports are only shown after relaunching the editor
### Tested versions

- Tested as broken in 4.4.dev2 and 4.4.dev2.mono on Windows 10
- Tested as working in 4.4.dev1.mono on Windows 10 and working in 4.4.dev2 on Linux

### System information

Godot v4.4.dev2.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.6070) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

For both gdscript and c# objects, changes to exports only are updated in the editor after relaunching entirely. Testing in 4.4.dev1, gdscript changes are updated immediately and c# changes are updated after building as expected.

### Steps to reproduce

1) Add a new export to some custom class (I was testing nodes in the scene tree)
2) If on c#, build
3) See that exports are unchanged
4) Relaunch editor and see that exports are changed

### Minimal reproduction project (MRP)

N/A, bug dependent on changes done to a project rather than a fixed state

### LINKED ISSUE #96812: [4.4.dev2, Windows] Project manager list uses unix time 0 for all projects
### Tested versions

- Tested as broken in 4.4.dev2 and 4.4.dev2.mono on Windows
- Tested as working in 4.4.dev1.mono on Windows and 4.4.dev2 on Linux

### System information

Godot v4.4.dev2.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.6070) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

All projects in the 4.4.dev2 project manager show up with a last edited time of 1970-01-01 00:00:00 causing the default sorting of the list to be effectively random:
image

Notably, projects saved in 4.4.dev2 and then reopened with 4.4.dev1 show the correct last edited time for the project so it's likely the project manager is just using the wrong value, or reading the value incorrectly:
image

### Steps to reproduce

Open the project manager and look at timestamps / try to sort projects by Last Edited

### Minimal reproduction project (MRP)

N/A, issue is with the project manager

### LINKED ISSUE #96828: [4.4.dev2, Windows] New assets not recognized, requires project reload to import
### Tested versions

v4.4.dev2.mono.official [97ef3c837]

### System information

Godot v4.4.dev2.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 32.0.15.6081) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description

New assets require to reload the project to get recognized.

### Steps to reproduce

Place new file (.fbx, .wav etc.) in filesystem -> nothing happens. 
Reload project -> import happens.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Prevents DST from rearranging file times.

`_wstat` does weird things with DST, which from I can find does not apply to Unix

Internally the same function is used but `_wstat` converts it to local time, without indicating DST, the approach here is based on that in Windows CRT, using creation time as fallback, and here ensuring the epoch is valid.

For all except DST overlap times this gives the same result, in UTC

Edit: Also resolves an inconsistency between MinGW and MSVC builds, see #92911

Fixes #74816
Fixes #92911
Fixes #96810
Fixes #96828
Fixes #96812

### CODE REVIEW

**Comment by AThousandShips** [comment]
For easy testing, use PowerShell and `(Get-Item C:\Users\ninni\Documents\Godot\Test1\icon.svg).LastWriteTimeUtc` and see that time during the hour of overlap with DST now works

**Comment by AThousandShips** [comment]
For easy testing, use PowerShell and `(Get-Item file).LastWriteTimeUtc` and see that time during the hour of overlap with DST now works

File: drivers/windows/file_access_windows.cpp [hunk 1]
```diff
@@ -356,15 +356,40 @@ uint64_t FileAccessWindows::_get_modified_time(const String &p_file) {
...
 
-	if (rv == 0) {
-		return st.st_mtime;
-	} else {
-		print_verbose("Failed to get modified time for: " + p_file + "");
-		return 0;
+	if (handle != INVALID_HANDLE_VALUE) {
+		FILETIME ft_create, ft_write;
+
+		bool status = GetFileTime(handle, &ft_create, nullptr, &ft_write);
```
Comment (bruvzg) [inline drivers/windows/file_access_windows.cpp:364]: [According to the docs](https://learn.microsoft.com/en-us/windows/win32/sysinfo/file-times), `GetFileTime` can have issues with DST as well (at least with FAT):

> The FAT file system records times on disk in local time. [GetFileTime](https://learn.microsoft.com/en-us/windows/desktop/api/FileAPI/nf-fileapi-getfiletime) retrieves cached UTC times from the FAT file system. When it becomes daylight saving time, the time retrieved by `GetFileTime` is off an hour, because the cache is not updated. When you restart the computer, the cached time that `GetFileTime` retrieves is correct.

But for `_wstat` it [seems to always invalid on FAT](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/14h5k7ff(v=vs.120)), so I guess it's better

> st_atime
> Time of last access of file. Valid on NTFS but not on FAT formatted disk drives.

> st_ctime
> Time of creation of file. Valid on NTFS but not on FAT formatted disk drives.

Comment (AThousandShips) [reply drivers/windows/file_access_windows.cpp:364]: I'm not sure what you are suggesting?

**Comment by AThousandShips** [comment]
Need to investigate an issue that has arisen with this, unsure what exactly but it no longer works on my setup, will try fix it when I find the time to dig through the Windows stuff

File: drivers/windows/file_access_windows.cpp [hunk 2]
```diff
@@ -553,15 +553,40 @@ uint64_t FileAccessWindows::_get_modified_time(const String &p_file) {
 		file = file.substr(0, file.length() - 1);
 	}
 
-	struct _stat st;
-	int rv = _wstat((LPCWSTR)(file.utf16().get_data()), &st);
+	HANDLE handle = CreateFileW((LPCWSTR)(file.utf16().get_data()), GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, NULL);
```
Comment (AThousandShips) [inline drivers/windows/file_access_windows.cpp:556]:
```suggestion
	HANDLE handle = CreateFileW((LPCWSTR)(file.utf16().get_data()), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS, nullptr);
```
Will update when ci is done

**Comment by KoBeWi** [comment]
I marked this as fix for #92911, but after testing again now, the results are wrong. Did something change?

**Comment by AThousandShips** [comment]
I will take a look, nothing should have changed though

**Comment by KoBeWi** [comment]
Expected results is that I get the same modified time in a dev build and an official build. This is no longer true.

**Comment by AThousandShips** [comment]
This code hasn't changed so I suspect something with the official builds have changed, or windows libraries

**Comment by akien-mga** [comment]
CC @bruvzg

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Comment by The-Cyber-Captain** [comment]
LOL. You won't believe how insane this manifested itself when targeting VR; ie, iterating Win-based exports / remote debugs of Android APKs for standalone headsets. I thought I was going full-on LAWNMOWER MAN mad inside the VR there. (With changed resources apparently 'randomly' being updated or included in the next run... all based on what the Godot Editor under Windows thought had changed on file, obviously, in hindsight)

Thanks for the quick fix! Looks like you managed to get it rectified and merged in less time than it took me to even pinpoint and reproduce for a Bug Report. Bravo!!! [applause]

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
