### PR TITLE
Suppress expected errors in resource unit tests

### LINKED ISSUE #80616: Error spam when running the test suite
### Godot version

4.2.dev (

### System information

Mageia 9 - Vulkan (Forward+) - dedicated AMD Radeon RX Vega M GL Graphics (RADV VEGAM) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

When compiling Godot with `dev_build=yes tests=yes`, running the test suite succeeds, but prints a lot of errors:
```
$ ./bin/godot.linuxbsd.editor.dev.x86_64 --test
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
ERROR: Condition "singleton != nullptr" is true.
   at: NavigationServer3D (./servers/navigation_server_3d.cpp:189)
ERROR: Resource was not pre cached for the resource section, bug?
   at: _write_resource (./scene/resources/resource_format_text.cpp:1848)
WARNING: Couldn't load resource (no cache): local://Resource_q0hwh
     at: parse_variant (./core/io/resource_format_binary.cpp:411)
ERROR: The object does not have any 'meta' values with the key 'next'.
   at: get_meta (./core/object/object.cpp:926)
ERROR: The object does not have any 'meta' values with the key 'next'.
   at: get_meta (./core/object/object.cpp:926)
ERROR: Condition "map == nullptr" is true. Returning: Vector3()
   at: map_get_closest_point (./modules/navigation/godot_navigation_server.cpp:241)
ERROR: Condition "map == nullptr" is true. Returning: Vector3()
   at: map_get_closest_point_normal (./modules/navigation/godot_navigation_server.cpp:248)
ERROR: Condition "map == nullptr" is true. Returning: RID()
   at: map_get_closest_point_owner (./modules/navigation/godot_navigation_server.cpp:255)
ERROR: Condition "map == nullptr" is true. Returning: Vector3()
   at: map_get_closest_point_to_segment (./modules/navigation/godot_navigation_server.cpp:234)
ERROR: Condition "map == nullptr" is true. Returning: Vector3()
   at: map_get_closest_point_to_segment (./modules/navigation/godot_navigation_server.cpp:234)
ERROR: Condition "map == nullptr" is true. Returning: Vector<Vector3>()
   at: map_get_path (./modules/navigation/godot_navigation_server.cpp:227)
ERROR: Condition "map == nullptr" is true. Returning: Vector<Vector3>()
   at: map_get_path (./modules/navigation/godot_navigation_server.cpp:227)
ERROR: Condition "map == nullptr" is true. Returning: r_query_result
   at: _query_path (./modules/navigation/godot_navigation_server.cpp:1161)
ERROR: Condition "!map" is true. Returning: Vector3()
   at: get_connection_pathway_end (./modules/navigation/nav_region.cpp:98)
ERROR: Condition "!map" is true. Returning: Vector3()
   at: get_connection_pathway_start (./modules/navigation/nav_region.cpp:92)
WARNING: NavigationServer3D::region_bake_navigation_mesh() is deprecated due to core threading changes. To upgrade existing code, first create a NavigationMeshSourceGeometryData3D resource. Use this resource with method parse_source_geometry_data() to parse the SceneTree for nodes that should contribute to the navigation mesh baking. The SceneTree parsing needs to happen on the main thread. After the parsing is finished use the resource with method bake_from_source_geometry_data() to bake a navigation mesh..
     at: region_bake_navigation_mesh (./modules/navigation/godot_navigation_server.cpp:468)
===============================================================================
[doctest] test cases:     816 |     816 passed | 0 failed | 1 skipped
[doctest] assertions: 2331757 | 2331757 passed | 0 failed |
[doctest] Status: SUCCESS!
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (./core/object/object.cpp:2049)
```

Some of those errors are intentionally caused by the tests, but they need to be silenced with `ERR_PRINT_OFF` and `ERR_PRINT_ON` macros in the test.

CC @smix8 as most are navigation related.

### Steps to reproduce

- `scons dev_build=yes tests=yes`
- `godot --test`

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by killzebug**
The test "[Resource] Breaking circular references on save" produces errors 
```
ERROR: Resource was not pre cached for the resource section, bug?
   at: _write_resource (scene/resources/resource_format_text.cpp:1882)
WARNING: Couldn't load resource (no cache): local://Resource_agy4p
     at: parse_variant (core/io/resource_format_binary.cpp:412)
```
The errors are intentional because the test uses uncached internal resources and as a result of the test the circular reference is broken. I tested out the branchpath in ResourceFormatSaverBinaryInstance::_find_resources that mentions circular references and found that it skips over internal resources. 
I have only suppressed the parts that produce errors: saving to text and loading from binary. 
Fixes: #80616

### CODE REVIEW

File: tests/core/io/test_resource.h [hunk 1]
```diff
@@ -124,9 +126,11 @@ TEST_CASE("[Resource] Breaking circular references on save") {
 	const String save_path_binary = OS::get_singleton()->get_cache_path().path_join("resource.res");
 	const String save_path_text = OS::get_singleton()->get_cache_path().path_join("resource.tres");
 	ResourceSaver::save(resource_a, save_path_binary);
+	ERR_PRINT_OFF;
```
Comment (akien-mga) [inline tests/core/io/test_resource.h:129]: Could you add a short comment explaining why the errors are expected, like you did in the PR?

File: tests/core/io/test_resource.h [hunk 2]
```diff
@@ -124,9 +126,12 @@ TEST_CASE("[Resource] Breaking circular references on save") {
 	const String save_path_binary = OS::get_singleton()->get_cache_path().path_join("resource.res");
 	const String save_path_text = OS::get_singleton()->get_cache_path().path_join("resource.tres");
 	ResourceSaver::save(resource_a, save_path_binary);
+	//Suppresses expected errors caused by the resources above being uncached
```
Comment (akien-mga) [inline tests/core/io/test_resource.h:129]:
```suggestion
	// Suppress expected errors caused by the resources above being uncached.
```

**Comment by killzebug** [comment]
Changed the comment, should be good to go.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
