### PR TITLE
Forbid calling of derivative functions in incorrect functions

### LINKED ISSUE #76155: dFdx and dFdy Bricking Spatial Shaders from Vertex Function
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

When the functions `dFdx` and `dFdy` are used in the vertex function of a spatial shader, the shader stops working (as though there were a syntax error), even though no errors are thrown in the shader editor.

The standard editor output does show the following error:
`servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:171 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.`

And many errors are thrown when the project is run.

### Steps to reproduce

From my experimentation, having either of the functions anywhere in the vertex function have the described effect.

### Minimal reproduction project

[dFdx + dFdy Demonstration.zip](https://github.com/godotengine/godot/files/11246120/dFdx.%2B.dFdy.Demonstration.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/76155

Compared to https://github.com/godotengine/godot/pull/83897 this code will recursively check the functions, and if it contains any derivative function and being called by `vertex` processor - it will correctly emit error.

shader_derivative_fix

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

image

image

File: servers/rendering/shader_language.cpp [hunk 1]
```diff
@@ -4610,6 +4624,57 @@ bool ShaderLanguage::_check_node_constness(const Node *p_node) const {
...
+		idx++;
+	}
+
+	return false;
+}
+
+bool ShaderLanguage::_validate_restricted_func(const StringName &p_name, const CallInfo *p_func_info, bool p_is_builtin_hint) {
+	const bool is_in_restricted_function = p_func_info->name == "vertex";
+
+	if (!p_is_builtin_hint) { // No need to check up the hierarchy if its a built-in.
```
Comment (Calinou) [inline servers/rendering/shader_language.cpp:4650]:
```suggestion
	// No need to check up the hierarchy if its a built-in.
	if (!p_is_builtin_hint) {
```

File: servers/rendering/shader_language.cpp [hunk 2]
```diff
@@ -4610,6 +4624,57 @@ bool ShaderLanguage::_check_node_constness(const Node *p_node) const {
...
+	}
+
+	if (!p_func_info->uses_restricted_functions.is_empty()) {
+		const Pair<StringName, TkPos> &first_element = p_func_info->uses_restricted_functions.get(0);
+		_set_tkpos(first_element.second);
+
+		if (is_in_restricted_function) {
+			_set_error(vformat(RTR("'%s' is restricted for usage within '%s' processor function."), first_element.first, "vertex"));
+		} else {
+			_set_error(vformat(RTR("'%s' cannot be used here, because '%s' is called by the '%s' processor function."), first_element.first, p_func_info->name, "vertex"));
```
Comment (Calinou) [inline servers/rendering/shader_language.cpp:4670]:
```suggestion
			_set_error(vformat(RTR("'%s' cannot be used within the '%s' processor function."), first_element.first, "vertex"));
		} else {
			_set_error(vformat(RTR("'%s' cannot be used here, because '%s' is called by the '%s' processor function (which is not allowed)."), first_element.first, p_func_info->name, "vertex"));
```

File: servers/rendering/shader_language.cpp [hunk 3]
```diff
@@ -5266,6 +5331,36 @@ ShaderLanguage::Node *ShaderLanguage::_parse_expression(BlockNode *p_block, cons
...
+						}
+
+						int idx = 0;
+						bool is_builtin = false;
+
+						while (frag_only_func_defs[idx].name) {
+							if (frag_only_func_defs[idx].name == name) {
+								// If a built-in function not found for the current shader type, then it shouldn't be parsed further.
+								if (!is_supported_frag_only_funcs) {
+									_set_error(vformat(RTR("Built-in function '%s' does not supported for '%s' shader type."), name, shader_type_identifier));
```
Comment (Calinou) [inline servers/rendering/shader_language.cpp:5347]:
```suggestion
									_set_error(vformat(RTR("Built-in function '%s' is not supported for the '%s' shader type."), name, shader_type_identifier));
```

**Comment by akien-mga** [comment]
Thanks!
