### PR TITLE
Fix build errors when building with `disable_3d=yes`

### LINKED ISSUE #104139: Errors when building godot with `disable_3d=yes`
### Tested versions

- Reproducible in current master https://github.com/godotengine/godot/commit/b377562b52fa8a68a99d5e818d8e08ac8d3fd7da
- Not reproducible in 4.4.stable

### System information

Windows 11

### Issue description

I’m getting some errors when building with the following command: scons platform=android target=template_debug arch=arm64 disable_3d=yes

```command
ERROR: scene\debugger\scene_debugger.cpp:1644:43: error: use of undeclared identifier 'selected_3d_nodes'; did you mean 'selected_ci_nodes'?
                                if (!selected_ci_nodes.is_empty() || !selected_3d_nodes.is_empty()) {
                                                                      ^~~~~~~~~~~~~~~~~
                                                                      selected_ci_nodes
scene\debugger/scene_debugger.h:242:24: note: 'selected_ci_nodes' declared here
        LocalVector<ObjectID> selected_ci_nodes;
                              ^
scene\debugger\scene_debugger.cpp:1713:64: error: use of undeclared identifier 'selected_3d_nodes'; did you mean 'selected_ci_nodes'?
        const int limit = max_selection - (selected_ci_nodes.size() + selected_3d_nodes.size());
                                                                      ^~~~~~~~~~~~~~~~~
                                                                      selected_ci_nodes
scene\debugger/scene_debugger.h:242:24: note: 'selected_ci_nodes' declared here
        LocalVector<ObjectID> selected_ci_nodes;
                              ^
scene\debugger\scene_debugger.cpp:1851:65: error: use of undeclared identifier 'nodes_3d'; did you mean 'nodes_ci'?
        if (!changed && nodes_ci.size() == selected_ci_nodes.size() && nodes_3d.size() == selected_3d_nodes.size()) {
                                                                       ^~~~~~~~
                                                                       nodes_ci
scene\debugger\scene_debugger.cpp:1790:24: note: 'nodes_ci' declared here
        LocalVector<ObjectID> nodes_ci;
                              ^
scene\debugger\scene_debugger.cpp:1851:84: error: use of undeclared identifier 'selected_3d_nodes'; did you mean 'selected_ci_nodes'?
        if (!changed && nodes_ci.size() == selected_ci_nodes.size() && nodes_3d.size() == selected_3d_nodes.size()) {
                                                                                          ^~~~~~~~~~~~~~~~~
                                                                                          selected_ci_nodes
scene\debugger/scene_debugger.h:242:24: note: 'selected_ci_nodes' declared here
        LocalVector<ObjectID> selected_ci_nodes;
                              ^
4 errors generated.
```

### Steps to reproduce

1. Clone master https://github.com/godotengine/godot/commit/b377562b52fa8a68a99d5e818d8e08ac8d3fd7da
2. Build with `scons platform=android target=template_debug arch=arm64 disable_3d=yes`
3. Wait for it.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes https://github.com/godotengine/godot/issues/104139

### CODE REVIEW

File: scene/debugger/scene_debugger.cpp [hunk 1]
```diff
@@ -1641,7 +1641,11 @@ void RuntimeNodeSelect::_physics_frame() {
 				// Allow forcing box selection when an item was clicked.
 				selection_drag_state = SELECTION_DRAG_MOVE;
 			} else if (items.is_empty()) {
+#ifndef _3D_DISABLED
 				if (!selected_ci_nodes.is_empty() || !selected_3d_nodes.is_empty()) {
+#else
+				if (!selected_ci_nodes.is_empty()) {
+#endif // _3D_DISABLED
```
Comment (AThousandShips) [inline scene/debugger/scene_debugger.cpp:1648]:
```suggestion
#ifdef _3D_DISABLED
				if (!selected_ci_nodes.is_empty()) {
#else
				if (!selected_ci_nodes.is_empty() || !selected_3d_nodes.is_empty()) {
#endif // _3D_DISABLED
```
For all these, general preference not not have the first option be negated

File: scene/debugger/scene_debugger.cpp [hunk 2]
```diff
@@ -1710,7 +1714,11 @@ void RuntimeNodeSelect::_send_ids(const Vector<Node *> &p_picked_nodes, bool p_i
 		return;
 	}
 
+#ifdef _3D_DISABLED
+	const int limit = max_selection - selected_ci_nodes.size();
+#else
 	const int limit = max_selection - (selected_ci_nodes.size() + selected_3d_nodes.size());
+#endif // _3D_DISABLED
```
Comment (YeldhamDev) [inline scene/debugger/scene_debugger.cpp:1721]:
```suggestion
	int limit = max_selection - selected_ci_nodes.size();
#ifndef _3D_DISABLED
	limit -= selected_3d_nodes.size();
#endif // _3D_DISABLED
```
Is fine for this to not be a constant.

**Review by YeldhamDev — CHANGES_REQUESTED** [review]

**Review by YeldhamDev — APPROVED** [review]

**Review by m4gr3d — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
