### PR TITLE
[macOS] Add exclusive fullscreen mode with Dock and Menu disabled.

### LINKED ISSUE #68254: OSX export fullscreen mode inconsistent due to missing info.plist entries
### Godot version

3.5.1-stable

### System information

OSX

### Issue description

Games exported with Godot Engine, when running in the full-screen mode on OSX, will show the title bar and menu docks as soon as the user puts the mouse pointer near the edge of the screen. While this is an expected behaviour for a full-screen application, it is not the case for the games, which require exclusive input without OS interruptions.

This behaviour can be controlled by `info.plist` file entry:
```
	<key>LSUIPresentationMode</key>
	<integer>3</integer>
```

I classified this report as a bug based on the fact that it makes Godot Engine unsuitable to create games to run fullscreen on OSX. Once the "trick" is known it can be easily worked around by the game developer, either manually or in the build script, but I'd argue that the default behaviour for the game engine should be to treat its projects as games, not a "generic full-screen apps".

### Steps to reproduce

- Export any fullscreen project on OSX.
- Move the mouse cursor to the lower edge of the screen.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/68254

### CODE REVIEW

File: platform/macos/display_server_macos.mm [hunk 1]
```diff
@@ -2573,7 +2573,13 @@
 				[wd.window_object setContentMaxSize:NSMakeSize(size.x, size.y)];
 			}
 			[wd.window_object toggleFullScreen:nil];
+
+			if (p_mode == WINDOW_MODE_EXCLUSIVE_FULLSCREEN) {
```
Comment (akien-mga) [inline platform/macos/display_server_macos.mm:2577]: Isn't this later override in the `switch (p_mode)`? Or it's needed to force going back to default presentation for some updates before going exclude fullscreen?

**Review by akien-mga — APPROVED** [review]

File: platform/macos/display_server_macos.mm (hunk 1 above)
Comment (bruvzg) [reply platform/macos/display_server_macos.mm:2577]: Should be `old_mode`.

**Comment by akien-mga** [comment]
Would be interesting to also have this implemented for 3.x somehow (not sure how since we don't have exclusive fullscreen there).

File: platform/macos/display_server_macos.mm (hunk 1 above)
Comment (akien-mga) [reply platform/macos/display_server_macos.mm]: Right, I thought about that too but then wondered why it would only be handling this for `WINDOW_MODE_FULLSCREEN` and not for the other non-fullscreen modes. But those are handled by `windowDidExitFullScreen` I suppose.

**Comment by bruvzg** [comment]
> Would be interesting to also have this implemented for 3.x somehow (not sure how since we don't have exclusive fullscreen there).

I guess 3.x always use exclusive fs on Windows, so it probably should always do it on macOS as well (but I would keep window title button to work without setting presentation mode, since it's more expected behavior).

**Comment by bruvzg** [comment]
Actually not full sure about setting `NSApplicationPresentationDisableProcessSwitching`, it's disabling Exposé hot corners (which is probably as desired as disabling Dock and Menu), but also disabling switching app with `Cmd+Tab` (which night be too much).

**Comment by bruvzg** [comment]
> How do other non-Godot games behave typically on macOS for this?

Seems like most of the games I have tested do not block Expose, so I have removed it as well.

**Comment by akien-mga** [comment]
Thanks!
