### PR TITLE
Make the retrieval of audio tracks consistent and implement trimming to AnimationTrackEditor shortcut and clean-up

### LINKED ISSUE #85088: AudioStreamPlayer keyframe is silent if the AudioClip starts at an negative time position
### Godot version

v4.2.rc1.mono.official [ad72de508]

### System information

Godot v4.2.rc1.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GTX 1070 () - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

4.1 Behaviour: If an AudioClip is positioned at an negative number inside the animation player. The Audio plays Exact at the 0 position.

Screenshot 2023-11-19 150448

4.2 Behaviour: The clip is silence if played. Also if played by the play button of the animation player

This bug is not critical because it can be worarround by cutting the animation clip inside the player so it does not need to be positioned at an negative number. But on large projects it requirest many refactors.

### Steps to reproduce

Create an Scene with an AnimationPlayer Node and an AudioStreamPlayer Node.
Create a new Animation.
Drag and Drop an Audio File inside the animation player and place its start below zero.
In my Case the Audio file was mp3

### Minimal reproduction project

NA, Because i did not know how to upload it. But it is easy to reproduce

### PR DESCRIPTION
**Pull request by TokageItLab**
- Supersedes/Contains #85582
- Fixes #85088
- Prerequisite #86227

#85088 occurred in 4.2.0 and should be temporarily fixed in 4.2.1. However, it is causing a more serious regression as #86147. Therefore, #86227 must be merged and cause problem #85088 again.

Solution:

Allow the audio track to get the key from the middle of the track by forcing `NEAREST` to get the key. This may cause double playback, but unlike a method track, the same stream is never played twice at the same time, so this should not be a problem.

However, keys placed in negative time can only be retrieved during seek. This means that the key will not be retrieved at loop time.

The reason for that is the difference in the search range between `track_find_key()` and `track_get_key_indices_in_range()`. To begin with, it is not expected to access keys outside the animation range in the playback process, so I add an argument `p_limit` to `track_find_key()` to limit the range.

As a result, audio keys placed at negative time will not be played, although playback of audio keys from the middle will be permitted. Finally, add an option to Clean-up to trim them, then close #85088.

image

### CODE REVIEW

File: scene/resources/animation.h [hunk 1]
```diff
@@ -401,7 +401,10 @@ class Animation : public Resource {
 	void track_set_key_transition(int p_track, int p_key_idx, real_t p_transition);
 	void track_set_key_value(int p_track, int p_key_idx, const Variant &p_value);
 	void track_set_key_time(int p_track, int p_key_idx, double p_time);
-	int track_find_key(int p_track, double p_time, FindMode p_find_mode = FIND_MODE_NEAREST) const;
+	int track_find_key(int p_track, double p_time, FindMode p_find_mode = FIND_MODE_NEAREST, bool p_limit = false) const;
+#ifndef DISABLE_DEPRECATED
+	int _track_find_key_bind_compat_86661(int p_track, double p_time, FindMode p_find_mode = FIND_MODE_NEAREST) const;
```
Comment (AThousandShips) [inline scene/resources/animation.h:406]: Should be moved above `_bind_compatibility_methods`, they should be grouped in one place (also the bind should not be public)

**Comment by AThousandShips** [comment]
If #86227 depends on this then either both or neither have to be cheery picked

File: misc/extension_api_validation/4.2-stable.expected [hunk 2]
```diff
@@ -14,3 +14,10 @@ Validate extension JSON: Error: Field 'classes/TileData/methods/get_navigation_p
 Validate extension JSON: Error: Field 'classes/TileData/methods/get_occluder/arguments': size changed value in new API, from 1 to 4.
 
 Added optional argument to get_navigation_polygon and get_occluder to specify a polygon transform.
+
+
+GH-86661
+--------
+Validate extension JSON: Error: Field 'classes/Animation/methods/track_find_key/arguments': size changed value in new API, from 3 to 4.
+
+Added optional argument to track_find_key to avoid finding keys out of the animation range.
```
Comment (AThousandShips) [inline misc/extension_api_validation/4.2-stable.expected:23]:
```suggestion
Added optional argument to track_find_key to avoid finding keys out of the animation range. Compatibility method registered.
```
I'd add this note (also trailing space)

File: editor/animation_track_editor.cpp [hunk 3]
```diff
@@ -5982,6 +5982,56 @@ void AnimationTrackEditor::_edit_menu_pressed(int p_option) {
...
 
+		case EDIT_SET_START_OFFSET: {
+			EditorUndoRedoManager *undo_redo = EditorUndoRedoManager::get_singleton();
+			undo_redo->create_action(TTR("Animation Set Start Offset"), UndoRedo::MERGE_ENDS);
+			for (const KeyValue<SelectedKey, KeyInfo> &E : selection) {
+				if (animation->track_get_type(E.key.track) != Animation::TYPE_AUDIO) {
+					continue;
+				}
+				Ref<AudioStream> stream = animation->audio_track_get_key_stream(E.key.track, E.key.key);
+				real_t len = stream->get_length() - animation->audio_track_get_key_end_offset(E.key.track, E.key.key);
```
Comment (akien-mga) [inline editor/animation_track_editor.cpp:5993]: I see you're using `real_t` throughout this code, is there a specific reason for that?

AFAIK these APIs like `AudioStream::get_length()` return `double`. It doesn't seem useful to cast those to `float` in `precision=single` builds (which is the default).

As a reminder, `real_t` is only for things like vector types whose precision can be configured for performance purposes in heavy computational stuff like transforms/physics/rendering.

For audio/animation I don't think `real_t` is a good choice, anything that's `Variant::FLOAT` in the API should use `double` in C++.

Comment (TokageItLab) [reply editor/animation_track_editor.cpp]: I remember that it was preferable for keys not to be double at least when inserting keys, as there is a possibility of duplicate keys due to errors between float and dloble, which are not visible in the editor.

But for now, I changed them to respect the retrieved type.

**Comment by fire** [comment]
@TokageItLab This needs a rebase so we can review and merge into Godot Engine master.

**Comment by TokageItLab** [comment]
Due to concerns from @lyuma , options that are only valid for Audio now clearly indicate it and it will gray out when Audio Key is not selected.

image

**Review by lyuma — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase after #86629.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
This crashes for me:
```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.dev.custom_build (9283d0d65c42663326f3f6f3d621207b550225ae)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] AnimationTrackEditor::_edit_menu_pressed (editor\animation_track_editor.cpp:6250)
[1] call_with_variant_args_helper<AnimationTrackEditor,int,0> (core\variant\binder_common.h:309)
[2] call_with_variant_args<AnimationTrackEditor,int> (core\variant\binder_common.h:419)
[3] CallableCustomMethodPointer<AnimationTrackEditor,int>::call (core\object\callable_method_pointer.h:99)
[4] Callable::callp (core\variant\callable.cpp:57)
[5] Object::emit_signalp (core\object\object.cpp:1128)
[6] Node::emit_signalp (scene\main\node.cpp:3846)
[7] Object::emit_signal<int> (core\object\object.h:922)
[8] PopupMenu::activate_item (scene\gui\popup_menu.cpp:2414)
[9] PopupMenu::_input_from_window_internal (scene\gui\popup_menu.cpp:642)
[10] PopupMenu::_input_from_window (scene\gui\popup_menu.cpp:452)
[11] Window::_window_input (scene\main\window.cpp:1606)
[12] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (core\variant\binder_common.h:304)
[13] call_with_variant_args<Window,Ref<InputEvent> const &> (core\variant\binder_common.h:419)
[14] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (core\object\callable_method_pointer.h:99)
[15] Callable::callp (core\variant\callable.cpp:57)
[16] Callable::call<Ref<InputEvent> > (core\variant\variant.h:864)
[17] DisplayServerWindows::_dispatch_input_event (platform\windows\display_server_windows.cpp:3171)
[18] DisplayServerWindows::_dispatch_input_events (platform\windows\display_server_windows.cpp:3141)
[19] Input::_parse_input_event_impl (core\input\input.cpp:771)
[20] Input::flush_buffered_events (core\input\input.cpp:1042)
[21] DisplayServerWindows::process_events (platform\windows\display_server_windows.cpp:2690)
[22] OS_Windows::run (platform\windows\os_windows.cpp:1476)
[23] widechar_main (platform\windows\godot_windows.cpp:182)
[24] _main (platform\windows\godot_windows.cpp:204)
[25] main (platform\windows\godot_windows.cpp:218)
[26] WinMain (platform\windows\godot_windows.cpp:232)
[27] __scrt_common_main_seh
[28] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

**Comment by AThousandShips** [comment]
Is indeed when the key does not have an associated stream, will write a fix
