### PR TITLE
Fix incorrect word block colors in the inspector tooltip

### LINKED ISSUE #51561: Hyperlinks in editor documentation tooltips (EditorHelpBit) are too dark to read
### Godot version

v4.0.dev.20210811.official [7188cb601]

### System information

Windows 10, AMD R9 280X, Vulkan

### Issue description

When hovering over something over the editor, most of the time there is a hint.
Some hints have links on them, that can be clicked.
Well, in Godot 4, these links are too dark to read, I don't know if it is a graphical issue or theme issue and/or if I can change the color manually.

Here's how they look in Godot 3.4 vs Godot 4:
godot3.4
godot4.0

While I'm at it, also when hovering over a link the mouse cursor doesn't change until you click somewhere in the hint box.

### Steps to reproduce

1. Open the a project with Godot 4 editor
2. Hover over an item, that has a hint with link (like project settings or resources such as `Sky`)
3. Done, it's too dark to read, at least for me

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
By setting up a theme to this tooltip at its creation.

Before:
image

After:

image

*Bugsquad edit:* Fixes #51561.

### CODE REVIEW

**Comment by akien-mga** [comment]
Should fix #51561. I remember we looked into this a while ago with @bruvzg maybe? I don't remember what was the conclusion about this theme propagation issue.

**Comment by KoBeWi** [comment]
I wonder why help bit in connections dock doesn't have this problem 🤔 It doesn't set the theme.

**Comment by Chaosus** [comment]
> I wonder why help bit in connections dock doesn't have this problem 🤔 It doesn't set the theme.

My guess `make_custom_tooltip` called in the Viewport which is not a subject to the theme apply.

**Comment by KoBeWi** [comment]
But it's the same as in EditorProperty
https://github.com/godotengine/godot/blob/1e0c6db62139f0b79fa9b90e1e8f5015996f94af/editor/connections_dialog.cpp#L509-L520
There's even a comment saying to keep them in sync. But one is broken and the other is not.

**Comment by KoBeWi** [comment]
Yep, just change `help_bit->set_text()` to deferred, as in ConnectionsDockTree.

**Comment by Chaosus** [comment]
I'm not sure why this hack is needed - maybe changing a `help_bit->call_deferred(SNAME("set_text"), text);` to `set_theme` is better?

**Comment by Chaosus** [comment]
@KoBeWi Ok, changed it as you said - it has less code and bring the same result after all...

**Comment by KoBeWi** [comment]
The theme was fine too, you just didn't need to check if it's valid. But both are correct, so let's leave it for now.

File: editor/editor_inspector.cpp [hunk 1]
```diff
@@ -1102,7 +1102,7 @@ Control *EditorInspectorCategory::make_custom_tooltip(const String &p_text) cons
 				text += "\n" + property_doc;
 			}
 		}
-		help_bit->set_text(text); //hack so it uses proper theme once inside scene
+		help_bit->call_deferred(SNAME("set_text"), text); //hack so it uses proper theme once inside scene
```
Comment (akien-mga) [inline editor/editor_inspector.cpp:1105]: For the reference, the comment was wrong because @reduz removed the hack in 047e0b7de5c - but as we see here the hack is still needed.

**Review by akien-mga — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
