### PR TITLE
Fix `Quaternion` arc constructor to check dot & Add test for same `Vector3`s

### LINKED ISSUE #101789: [4.4beta1] Quaternion arc constructor gives wrong rotation when vectors are the same
### Tested versions

Reproducible in 4.4beta1
Not reproducible in 4.4dev7

### System information

Godot v4.4.beta1 - Windows 10 (build 19045) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6094) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

Bug appeared in my project right after updating from 4.4dev7 to 4.4beta1. 

An easy workaround is checking if the angle between the vectors are below some small value, and if they are then replace the quaternion with the quaternion identity.

### Steps to reproduce

Rotate an object with a quaternion created from the Quaternion(arc_from: Vector3, arc_to Vector3) constructor where the vectors are parallel or nearly parallel and in the same direction, and the resulting rotation will be a 180 degree arc.

### Minimal reproduction project (MRP)

[quaternion-issue.zip](https://github.com/user-attachments/files/18467897/quaternion-issue.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/101789
- Follow up https://github.com/godotengine/godot/pull/100991

We removed the dot check in the review for the performance, but did not consider the case of the same vector. So fix to add the dot check. Also, add a test for the same vectors.

### CODE REVIEW

File: core/math/quaternion.h [hunk 1]
```diff
@@ -141,16 +141,19 @@ struct [[nodiscard]] Quaternion {
 	}
 
 	Quaternion(const Vector3 &p_v0, const Vector3 &p_v1) { // Shortest arc.
-		Vector3 c = p_v0.cross(p_v1);
+		real_t d = p_v0.dot(p_v1);
+		if (Math::is_equal_approx(d, 1.0)) {
```
Comment (lawnjelly) [inline core/math/quaternion.h:145]: `is_equal_approx()` seems to do some extra unneeded stuff, the old version:
```
if (d < -1.0f + (real_t)CMP_EPSILON)
```
seems better, although I'm not sure it has to be converted to `real_t`, unless we need 64 bit later for the dot (this PR has been refreshed since I initially posted).

File: core/math/quaternion.h [hunk 2]
```diff
@@ -141,16 +141,26 @@ struct [[nodiscard]] Quaternion {
...
-		Vector3 c = p_v0.cross(p_v1);
+#ifdef MATH_CHECKS
+		ERR_FAIL_COND_MSG(p_v0.is_zero_approx() || p_v1.is_zero_approx(), "The vectors must not be zero.");
+#endif
+		Vector3 n0 = p_v0.normalized();
+		Vector3 n1 = p_v1.normalized();
+
+		real_t d = n0.dot(n1);
+		real_t n = 1.0f - (real_t)CMP_EPSILON;
+		if (d > n) {
```
Comment (lawnjelly) [inline core/math/quaternion.h:152]: Should this be `<`?

Comment (TokageItLab) [reply core/math/quaternion.h:152]: `n0.dot(n1) > 1.0f - (real_t)CMP_EPSILON` is correct because it returns no rotation if the dot product is 1.

File: core/math/quaternion.h [hunk 3]
```diff
@@ -141,16 +141,26 @@ struct [[nodiscard]] Quaternion {
...
+			return;
+		}
 
-		if (c.is_zero_approx()) {
-			Vector3 axis = p_v0.get_any_perpendicular();
+		if (d < -n) {
```
Comment (TokageItLab) [inline core/math/quaternion.h:156]: I am not sure of the strictness of `-(1.0f - (real_t)CMP_EPSILON)` vs `-1.0f + (real_t)CMP_EPSILON`. Is it fine to reuse the `n`?

Comment (lawnjelly) [reply core/math/quaternion.h:156]: Yeah it's fine afaik. You could make it a `constexp` too if you wanted to make more clear, but the compiler should realize it's a `const`.

Compiler should add two separate consts (one for positive and one for negative). Or rather I don't see why it wouldn't.

Comment (TokageItLab) [reply core/math/quaternion.h:156]: ah const sounds good.

**Review by lawnjelly — APPROVED** [review]
Looks fine for fixing the bug, although would be good to have someone else check with another set of eyes.

There's a few things that could be checked out if going to town for performance, but probably not necessary.

For instance you could evaluate whether checking both conditions with:
```
if (ABS(d) > ALMOST_ONE)
```
Made a difference. You could then do a second check for polarity.
The idea being ABS cheaper than a comparison. But that would require looking at assembly / profiles and I don't think it's necessary unless someone is super keen.

By the way, can confirm compiler uses two separate constants for the positive and negative, I checked the assembly.

**Review by fire — APPROVED** [review]

**Comment by fire** [comment]
I liked the unit test added for the error case.

**Comment by TokageItLab** [comment]
Adopted abs with comments on the second comparison.

**Review by lawnjelly — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
