### PR TITLE
Fix: Tilemap tools not overriding main editor tools

### LINKED ISSUE #12646: Make Tilemap tools override the tools on the top toolbar
### Describe the problem or limitation you are having in your project

Hard to see which tools are active, due to several toolbars

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

When drawing tilemaps using Paint Tool, you need to have Select Mode enabled on the top toolbar. This is confusing for a beginner like me. Maybe make the selected tool at the bottom override the tool on the top, so it automatically becomes "Select Mode" on the top? 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

not relevant

### If this enhancement will not be used often, can it be worked around with a few lines of script?

not relevant

### Is there a reason why this should be core and not an add-on in the asset library?

not relevant

### PR DESCRIPTION
**Pull request by DexterFstone**
Closes https://github.com/godotengine/godot-proposals/issues/12646

### CODE REVIEW

**Comment by groud** [comment]
Removed the "bug" label as this is the intended behavior.

I am not sure about this change, I'd like the proposal to be backed a bit more, as the other tools can be useful even if the TileMap editor is visible. Those other tools are more specific than the "select" one, which make me think when you change to them, then you know what you are doing and expect them to work right away.

**Comment by DexterFstone** [comment]
> I am not sure about this change, I'd like the proposal to be backed a bit more, as the other tools can be useful even if the TileMap editor is visible. Those other tools are more specific than the "select" one, which make me think when you change to them, then you know what you are doing and expect them to work right away.

The scenario I was considering was this:
The user has selected a tool other than the `select tool`
Now the user selects the `TileMapLayer` node and wants to start painting with the default tool, but since the selection tool is not a `select`, it is having trouble
I think the best place to edit the tool selection was when the `TileMapEditor` is displayed
After that, if needed, the user can select their own tool, such as `rotate` or `scale`

**Comment by groud** [comment]
hmm. I guess it makes sense then. If it still allows you to use the tools afterward I guess it could work. 

I wonder if it's still good though, there might be some users who you like, for example, the "move" tool to stay active when selecting nodes one after the other in the scene tree. And the fact we would introduce this new behavior (about selecting a node possibly auto-switching the tool) might be a bit confusing and annoying for some.

That being said, switching to select mode when clicking a tool in the tilemap bottom toolbar makes perfect sense. I think it might deserve either a dedicated function though, or simply `_update_toolbar` to be renamed to something like `_tool_button_pressed` (so that's it's a bit clearer it does now more than update the toolbar).

**Comment by DexterFstone** [comment]
I updated the code, now it should be cleaner and work better. Additionally, it keeps track of the previously selected tool, so whenever `TileMapLayerEditor` is unavailable, the tool will revert to its original state.
- When selecting `TileMapLayer`, it forces the `CanvasItemEditor` to select the `Select` tool.
- When the mouse enters the `TileMapLayerEditor`, it forces the `CanvasItemEditor` to select the `Select` tool.
- When selecting the `TileMapLayerEditor` tools, it forces the `CanvasItemEditor` to select the `Select` tool.
- When deselecting the `TileMapLayer`, it forces the `CanvasItemEditor` to revert to the previous tool.

> [!NOTE]
> In my tests, the mouse entered does not always work

**Comment by KoBeWi** [comment]
The tool switches as soon as you hover the TileMapLayer editor, it seems weird:

https://github.com/user-attachments/assets/bafad716-e761-49c4-b0d5-6ef5e48a7d6d

Also not sure if switching the tool back after deselecting tilemap is intuitive.

**Comment by DexterFstone** [comment]
> The tool switches as soon as you hover the TileMapLayer editor, it seems weird:
> 
>  godot.windows.editor.dev.x86_64_vTMZxtVfxQ.mp4 
> Also not sure if switching the tool back after deselecting tilemap is intuitive.

So you're saying is to completely remove the auto-switching tool?

**Comment by KoBeWi** [comment]
Switching to Select when selecting the node is fine, not sure if it's necessary to switch afterwards (e.g. when user decides to use Move tool while the tilemap is selected).

Going back to the previous tool when tilemap is deselected should be removed IMO. The tilemap editor can be hidden e.g. when starting project, so "randomly" changing tools can be confusing.

File: editor/plugins/canvas_item_editor_plugin.cpp [hunk 1]
```diff
@@ -4104,6 +4104,10 @@ void CanvasItemEditor::set_current_tool(Tool p_tool) {
 	_button_tool_select(p_tool);
 }
 
+void CanvasItemEditor::update_tool() {
```
Comment (KoBeWi) [inline editor/plugins/canvas_item_editor_plugin.cpp]: What's this method for and why does it have such generic name?
You can just call `set_current_tool()` directly.

**Review by KoBeWi — APPROVED** [review]
Looks fine now.

File: editor/plugins/canvas_item_editor_plugin.cpp (hunk 1 above)
Comment (groud) [reply editor/plugins/canvas_item_editor_plugin.cpp]: Yep, maybe it should be "reset_to_select_tool" or something ? `update_tool` isn't a great name TBH.

Edit: but yeah, calling `set_current_tool` directly make even more sense.

File: editor/plugins/tiles/tile_map_layer_editor.cpp [hunk 2]
```diff
@@ -3654,6 +3655,12 @@ void TileMapLayerEditor::_node_change(Node *p_node) {
 
 void TileMapLayerEditor::_notification(int p_what) {
 	switch (p_what) {
+		case NOTIFICATION_VISIBILITY_CHANGED: {
+			if (is_visible()) {
+				CanvasItemEditor::update_tool();
```
Comment (groud) [inline editor/plugins/tiles/tile_map_layer_editor.cpp]: I'm still unsure about this change, as selecting a node changing the tool might be a bit annoying to users.
But I guess we can give it a try and see if anyone complains.

**Comment by Repiteo** [comment]
Needs rebase

**Comment by DexterFstone** [comment]
> Needs rebase

Done

**Comment by Repiteo** [comment]
Thanks!
