### PR TITLE
Fixed error in ParallaxLayer when set_mirroring is called before entering the tree

### LINKED ISSUE #31300: Canvas item not found error instancing a scene containing parallax layer and overriding mirroring property
**Godot version:**
3.2-dev 3418f76a9eab9f496e5b26310bd3bc1125b8119b
Likely 3.1 too.

**OS/device including version:**
Windows 10

**Issue description:**
When overriding `mirroring` property of a `ParallaxLayer` node inside instanced editable scene, the following error shows up:
```
ERROR: VisualServerCanvas::canvas_set_item_mirroring: Condition ' idx == -1 ' is true.
   At: servers\visual\visual_server_canvas.cpp:318
```
https://github.com/godotengine/godot/blob/5ca74604217758d91e344b052fe87c9eda8940a9/servers/visual/visual_server_canvas.cpp#L318

This doesn't happen if not instancing.

**Steps to reproduce:**
1. Create a hierarchy of `ParallaxBackground` → `ParallaxLayer` → `Sprite` and save this as scene.
2. Instance this scene in the main scene, enable `Editable Children` on it and override mirroring property of `ParallaxLayer`.
3. Save the scene or run the project.

**Minimal reproduction project:**
[canvas_item_set_mirroring_idx_not_found.zip](https://github.com/godotengine/godot/files/3490297/canvas_item_set_mirroring_idx_not_found.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Fixes #31300

Mirroring override with `Editable Children` was causing mirroring to be updated before entering the tree and it wasn't supported.

This change avoids this case the same way it's done for `set_base_offset_and_scale`.

Callstack when instanciating the scene:

```
 	godot.windows.opt.tools.64.exe!ParallaxLayer::set_mirroring(const Vector2 & p_mirroring) Line 90	C++
 	godot.windows.opt.tools.64.exe!MethodBind1<ParallaxLayer,Vector2 const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 867	C++
 	godot.windows.opt.tools.64.exe!ClassDB::set_property(Object * p_object, const StringName & p_property, const Variant & p_value, bool * r_valid) Line 1049	C++
 	godot.windows.opt.tools.64.exe!Object::set(const StringName & p_name, const Variant & p_value, bool * r_valid) Line 422	C++
 	godot.windows.opt.tools.64.exe!SceneState::instance(SceneState::GenEditState p_edit_state) Line 253	C++
 	godot.windows.opt.tools.64.exe!PackedScene::instance(PackedScene::GenEditState p_edit_state) Line 1692	C++
 	godot.windows.opt.tools.64.exe!Main::start() Line 1752	C++
```

Mirroring is properly updated on `NOTIFICATION_ENTER_TREE`

### CODE REVIEW

File: scene/2d/parallax_layer.cpp [hunk 1]
```diff
@@ -87,6 +87,9 @@ void ParallaxLayer::set_mirroring(const Size2 &p_mirroring) {
 	if (mirroring.y < 0)
 		mirroring.y = 0;
 
+	if (!is_inside_tree())
```
Comment (Xrayez) [inline scene/2d/parallax_layer.cpp]: Perhaps it would be better to check this directly in `_update_mirroring` method as to avoid the same bug happening in the future, even if this is called in `NOTIFICATION_ENTER_TREE` already.

Comment (pouleyKetchoupp) [reply scene/2d/parallax_layer.cpp]: Ok, I'm moving the test inside `_update_mirroring()`.

**Review by Xrayez — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.
