### PR TITLE
Fix never ending loop with overlapping probes

### LINKED ISSUE #88940: Crash when adding multiple reflection probes
### Tested versions

- Reproducible in 4.3 23191b834e4609baacf19855c3acb6a9f607b30f

### System information

Window 10 - 4.3 master

### Issue description

System crash when adding a 3rd reflection probe:

```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.dev.custom_build (c76bf7e2cf8b0f0eb95ee6a11e5849da9156230c)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] RenderingDeviceGraph::_add_command_to_graph (C:\Projects\godot4-git\servers\rendering\rendering_device_graph.cpp:509)
[1] RenderingDeviceGraph::add_draw_list_end (C:\Projects\godot4-git\servers\rendering\rendering_device_graph.cpp:1678)
[2] RenderingDevice::draw_list_end (C:\Projects\godot4-git\servers\rendering\rendering_device.cpp:3947)
[3] RendererRD::CopyEffects::cubemap_downsample_raster (C:\Projects\godot4-git\servers\rendering\renderer_rd\effects\copy_effects.cpp:1091)
[4] RendererRD::SkyRD::ReflectionData::create_reflection_fast_filter (C:\Projects\godot4-git\servers\rendering\renderer_rd\environment\sky.cpp:395)
[5] RendererRD::LightStorage::reflection_probe_instance_postprocess_step (C:\Projects\godot4-git\servers\rendering\renderer_rd\storage_rd\light_storage.cpp:1550)
[6] RendererSceneCull::_render_reflection_probe_step (C:\Projects\godot4-git\servers\rendering\renderer_scene_cull.cpp:3551)
[7] RendererSceneCull::render_probes (C:\Projects\godot4-git\servers\rendering\renderer_scene_cull.cpp:3587)
[8] RenderingServerDefault::_draw (C:\Projects\godot4-git\servers\rendering\rendering_server_default.cpp:91)
[9] RenderingServerDefault::draw (C:\Projects\godot4-git\servers\rendering\rendering_server_default.cpp:388)
[10] Main::iteration (C:\Projects\godot4-git\main\main.cpp:4021)
[11] OS_Windows::run (C:\Projects\godot4-git\platform\windows\os_windows.cpp:1476)
[12] widechar_main (C:\Projects\godot4-git\platform\windows\godot_windows.cpp:182)
[13] _main (C:\Projects\godot4-git\platform\windows\godot_windows.cpp:204)
[14] main (C:\Projects\godot4-git\platform\windows\godot_windows.cpp:218)
[15] WinMain (C:\Projects\godot4-git\platform\windows\godot_windows.cpp:232)
[16] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[17] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

I ran into this by accident while working on reflection probes for GLES. Found out there was a never ending loop condition in `RendererSceneCull::render_probes`, decided to test this on Vulkan and found out the same is happening eventually leading to a crash as the same probe keeps being added to the render list.

This may be related to the probes having update always turned on.

### Steps to reproduce

Use the MRP, in the editor duplicate one of the two reflection probes by selecting it and pressing CTRL-D. Watch it crash...

### Minimal reproduction project (MRP)

[testreflectionprobe.zip](https://github.com/godotengine/godot/files/14427042/testreflectionprobe.zip)

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR changes two issues.

1. If we have overlapping probes set to update always, we render the first probe, remove it from our probe render list, then render our second probe, where our culling sees our first probe is within our AABB, which adds the first probe back into the render list, after which we remove the second probe, and return to process the first probe, which then finds the second probe and adds it to the render list, and we keep going and going and going...
   I've changed it so the probes remain in our render lists and are only removed once we're done. That seems to fix it.
2. After fixing that bug I ran into another bug because I had two render probes set to update always, and a 3rd render probe set to once. Godot handles the probes in reverse order so it renders the "update once" probe first. Then it renders the the "update always" probe, however as I didn't have my probe size set to 256, it tosses away the atlas and starts over. Our "update once" probe now panics as it tries to complete it's rendering process. 

- This closes https://github.com/godotengine/godot/issues/88940.

### CODE REVIEW

File: servers/rendering/renderer_rd/storage_rd/light_storage.cpp [hunk 1]
```diff
@@ -1535,13 +1554,12 @@ bool LightStorage::reflection_probe_instance_postprocess_step(RID p_instance) {
...
 	ERR_FAIL_COND_V(!rpi->rendering, false);
-	ERR_FAIL_COND_V(rpi->atlas.is_null(), false);
 
 	ReflectionAtlas *atlas = reflection_atlas_owner.get_or_null(rpi->atlas);
 	if (!atlas || rpi->atlas_index == -1) {
-		//does not belong to an atlas anymore, cancel (was removed from atlas or atlas changed while rendering)
+		// Does not belong to an atlas anymore, cancel (was removed from atlas or atlas changed while rendering).
 		rpi->rendering = false;
-		return false;
+		return false; // Q: this will just keep looping, consider returning true?
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/storage_rd/light_storage.cpp:1562]: With the other fixes we don't get here anymore, but I still think we should change this to `return true;` to indicate there is nothing more to render. Now if there is no atlas and we somehow get this far, we would just keep calling this endlessly for this probe with nothing really happening.

File: servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp [hunk 2]
```diff
@@ -1615,15 +1615,16 @@ void RenderForwardClustered::_render_scene(RenderDataRD *p_render_data, const Co
...
 		current_cluster_builder = nullptr;
+		return; // No point in continuing, we'll just crash.
 	}
 
-	if (current_cluster_builder != nullptr) {
-		p_render_data->cluster_buffer = current_cluster_builder->get_cluster_buffer();
-		p_render_data->cluster_size = current_cluster_builder->get_cluster_size();
-		p_render_data->cluster_max_elements = current_cluster_builder->get_max_cluster_elements();
-	}
+	ERR_FAIL_NULL(current_cluster_builder);
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:1623]: There really is no point in continuing here without a cluster builder, loads of things just error out and we get loads of error spam including a divide by zero crash. Returning early here at the point of failure will prevent a lot of confusion.

File: servers/rendering/renderer_rd/storage_rd/light_storage.cpp (hunk 1 above)
Comment (clayjohn) [reply servers/rendering/renderer_rd/storage_rd/light_storage.cpp:1562]: I'm not sure this will always continue rendering. I think that this will, in most cases, ensure that the probe gets updated the following frame (which it should). I have a feeling that setting to true will result in situations where the probe doesn't get updated at all if set to update once

**Review by clayjohn — APPROVED** [review]
Overall, this looks great. I replied to your comment, but I am not sure it is a good idea. I suspect that code is there for a reason and flipping the false to true will break something. 

Feel free to look deeper into it if you really feel like the false should become true, but otherwise I think we can merge this once you remove the comment with the question

File: servers/rendering/renderer_rd/storage_rd/light_storage.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/storage_rd/light_storage.cpp:1562]: Indeed, if we return true here, it marks the probe as done, so if there wasn't another change that causes it to be re-queued for updating (like I've done in the situation where the atlas is rebuild) then it gets lost.

**However** if we return false, that just means it gets stuck at its current processing step and it will forever try and redo this processing step. As the failure isn't being resolved, it will never get past this point. 

The only failure scenario that I can think of that would cause this situation, is when the atlas is full. If I follow the code correctly there is a condition where a probe that was rendered some frames ago will give up its spot when a new probe comes in. But it is unclear to me whether this can happen to a probe that is still being updated over multiple frames.

So if we manage to remove a probe where we completed the first processing step (e.g. rendered the faces) but where now updating on level of the mips each frame, than that probe will forever be stuck attempting to update that mip which it can never complete because it will never attempt to redo the first step.

It really seems to me that we're dealing with logic that was written once upon a time when certain things worked differently and it would retry rendering a probe in this condition, but it is definitely broken at this point in time.

Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/storage_rd/light_storage.cpp]: I have removed the comment, without an MRP this is all theory and I may have done enough to prevent ever getting into this situation.
Suggest we keep this in the back of our heads in case someone runs into a broken probe :P

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
