### PR TITLE
Bind `_reset`/`_restore` in AnimationMixer

### LINKED ISSUE #85203: AnimatedSprite2D's animation does not play properly if the previous set animation wasn't set to looping
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - macOS 14.1.1 - Vulkan (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

Animated sprite's animation stops playing

### Steps to reproduce

To reproduce it, launch the attached project. The animation will stop playing after the first AnimationPlayer's loop.

Here is how the AnimationPlayer is set:
image
The first keyframe is pointing to a looping animation of a AnimatedSprite2D, the other keyframe is pointing to a non looping animation of the same AnimatedSprite2D. This sequence of both animations is meant to repeat. If you launch the project, it will play only once and then stop even when the first (looping) animation is meant to play.

If both animations in the AnimatedSprite2D are set to loop, the animation playing does not break.

### Minimal reproduction project

[engage bug 02.zip](https://github.com/godotengine/godot/files/13433221/engage.bug.02.zip)

### LINKED ISSUE #85232: Animation window Edit -> Apply Reset fails because `AnimationMixer::_reset` is not exposed
### Godot version

4.2.rc 7022271

### System information

Godot v4.2.rc (702227129) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Attempting to run Edit -> Apply Reset on an animation player with a RESET track fails because the `AnimationMixer::apply_reset` method is called with `p_user_initiated` true.

In this case, it attempts to use UndoRedo to apply `"_reset"` which does not exist / is not exposed on AnimationPlayer.
```
Animation Apply Reset
  core\object\undo_redo.cpp:345 - Error calling UndoRedo method operation '_reset': 'AnimationPlayer::_reset': Instance is null
```
Other uses of `apply_reset` pass false which directly calls `AnimationMixer::reset()` and works fine.

Is there any reason that `reset` or `apply_reset` aren't exposed to scripting normally?

### Steps to reproduce

1. Import a model with a reset track
2. New Inherited Scene
3. Select the scene button in the hierarchy to open the base model directly.
4. Click "Open Anyway"
5. Select the AnimationPlayer
6. Choose the `_T-Pose_` animation or any animation other than `RESET`
7. Click the Edit menu -> `Apply Reset`. Nothing happens.
8. An error is printed in the log

### Minimal reproduction project

[ApplyReset.zip](https://github.com/godotengine/godot/files/13442920/ApplyReset.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Sorry that I have missed to bind it.

Fixes #85232.

But #85233 still seems happen so it may be related by https://github.com/godotengine/godot/pull/84942#discussion_r1398422454 or others... (Will this fix that?  https://github.com/godotengine/godot/issues/85233#issuecomment-1823258389)

### CODE REVIEW

File: scene/animation/animation_mixer.cpp [hunk 1]
```diff
@@ -2128,6 +2128,11 @@ void AnimationMixer::_bind_methods() {
 	ADD_SIGNAL(MethodInfo(SNAME("animation_finished"), PropertyInfo(Variant::STRING_NAME, "anim_name")));
 	ADD_SIGNAL(MethodInfo(SNAME("animation_started"), PropertyInfo(Variant::STRING_NAME, "anim_name")));
 	ADD_SIGNAL(MethodInfo(SNAME("caches_cleared")));
+
+#ifdef TOOLS_ENABLED
```
Comment (akien-mga) [inline scene/animation/animation_mixer.cpp:2132]: The API should be the same for editor and runtime, so this shouldn't be in `TOOLS_ENABLED` but always exposed.

Comment (TokageItLab) [reply scene/animation/animation_mixer.cpp:2132]: Before AnimationMixer was implemented, this was an API that was only valid for TOOLS_ENABLED. I assume that as long as the prefix _ is there it won't actually be exposed, but is there a case for using it at runtime?

Comment (akien-mga) [reply scene/animation/animation_mixer.cpp:2132]: I don't expect users to use these methods at runtime, especially since they're prefixed with `_` so they're hidden. But for classes which are part of the public API, we try to make sure we don't create a discrepancy between the API exposed in `TOOLS_ENABLED` and non-tools.

Here again the `_` prefix will hide it, but if that were to change in the future, we shouldn't have methods that count in the API hash / GDExtension API that actually won't exist at runtime, but aren't documented as editor-only.

I see in 4.1 the `restore` method was only for `TOOLS_ENABLED`, but it was also exposed in `AnimatedValuesBackup` which isn't part of the public (scripting) API.

So I don't have a concrete use case in mind, it's more a code consistency guideline that the API we expose in `TOOLS_ENABLED` and non `TOOLS_ENABLED` should be the same for core classes.

Comment (TokageItLab) [reply scene/animation/animation_mixer.cpp]: Exposed functions except `apply_reset()` since `apply_reset()` depends on the editor feature such as UndoRedo and dummy player.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
