### PR TITLE
Fix crash on importing FBX file

### LINKED ISSUE #51373: Godot crashes on importing FBX file
### Godot version

3.3.3-stable, 4.0.dev (4cb406e02)

### System information

Linux, GLES3

### Issue description

When import one of the FBX files I attached in the comments down below, Godot crashes. I assume this is a problem related to the FBX importer.

From Godot 3.3.2 I get the following backtrace dump:
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7fecf9af7d60] (??:0)
[2] /home/me/Godot_v3.3.2-stable_x11.64() [0xec3d67] (??:0)
[3] /home/me/Godot_v3.3.2-stable_x11.64() [0xa1eda3] (??:0)
[4] /home/me/Godot_v3.3.2-stable_x11.64() [0x2b1023a] (??:?)
[5] /home/me/Godot_v3.3.2-stable_x11.64() [0xa252bf] (??:0)
[6] /home/me/Godot_v3.3.2-stable_x11.64() [0x2d019fb] (??:?)
[7] /home/me/Godot_v3.3.2-stable_x11.64() [0x2241205] (??:0)
[8] /home/me/Godot_v3.3.2-stable_x11.64() [0x25d72a5] (??:0)
[9] /home/me/Godot_v3.3.2-stable_x11.64() [0x25da050] (??:0)
[10] /home/me/Godot_v3.3.2-stable_x11.64() [0x25debaa] (??:0)
[11] /home/me/Godot_v3.3.2-stable_x11.64() [0x25dfdb0] (??:0)
[12] /home/me/Godot_v3.3.2-stable_x11.64() [0xdfee64] (??:0)
[13] /home/me/Godot_v3.3.2-stable_x11.64() [0x1cc334e] (??:0)
[14] /home/me/Godot_v3.3.2-stable_x11.64() [0x1cd4b8f] (??:0)
[15] /home/me/Godot_v3.3.2-stable_x11.64() [0x310d4ed] (??:?)
[16] /home/me/Godot_v3.3.2-stable_x11.64() [0x98e9dd] (??:0)
[17] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7fecf9ae2d0a] (??:0)
[18] /home/me/Godot_v3.3.2-stable_x11.64() [0x99d1be] (??:0)
```

Since this error message isn't quite useful, here is the message from 4.0.dev:
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7ff970885d60] (??:0)
[2] Set<TPPLPartition::ScanLineEdge, Comparator<TPPLPartition::ScanLineEdge>, DefaultAllocator>::_lower_bound(TPPLPartition::ScanLineEdge const&) const (/builds/Calinou/godot-builds-ci/godot/./core/templates/set.h:301)
[3] Set<TPPLPartition::ScanLineEdge, Comparator<TPPLPartition::ScanLineEdge>, DefaultAllocator>::lower_bound(TPPLPartition::ScanLineEdge const&) const (/builds/Calinou/godot-builds-ci/godot/./core/templates/set.h:586)
[4] TPPLPartition::MonotonePartition(List<TPPLPoly, DefaultAllocator>*, List<TPPLPoly, DefaultAllocator>*) (/builds/Calinou/godot-builds-ci/godot/thirdparty/misc/polypartition.cpp:1410)
[5] TPPLPartition::Triangulate_MONO(List<TPPLPoly, DefaultAllocator>*, List<TPPLPoly, DefaultAllocator>*) (/builds/Calinou/godot-builds-ci/godot/thirdparty/misc/polypartition.cpp:1833)
[6] TPPLPartition::Triangulate_MONO(TPPLPoly*, List<TPPLPoly, DefaultAllocator>*) (/builds/Calinou/godot-builds-ci/godot/thirdparty/misc/polypartition.cpp:1848)
[7] FBXMeshData::triangulate_polygon(SurfaceData*, Vector<int> const&, std::vector<Vector3, std::allocator<Vector3> > const&) const (/builds/Calinou/godot-builds-ci/godot/modules/fbx/data/fbx_mesh_data.cpp:938)
[8] FBXMeshData::create_fbx_mesh(ImportState const&, FBXDocParser::MeshGeometry const*, FBXDocParser::Model const*, bool) (/builds/Calinou/godot-builds-ci/godot/modules/fbx/data/fbx_mesh_data.cpp:294)
[9] EditorSceneImporterFBX::_generate_scene(String const&, FBXDocParser::Document const*, unsigned int, int, int, bool) (/builds/Calinou/godot-builds-ci/godot/modules/fbx/editor_scene_importer_fbx.cpp:660)
[10] EditorSceneImporterFBX::import_scene(String const&, unsigned int, int, List<String, DefaultAllocator>*, Error*) (/builds/Calinou/godot-builds-ci/godot/modules/fbx/editor_scene_importer_fbx.cpp:210)
[11] ResourceImporterScene::import(String const&, String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*, Variant*) (/builds/Calinou/godot-builds-ci/godot/editor/import/resource_importer_scene.cpp:1373)
[12] EditorFileSystem::_reimport_file(String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const*, String const&) (/builds/Calinou/godot-builds-ci/godot/editor/editor_file_system.cpp:1849)
[13] EditorFileSystem::reimport_files(Vector<String> const&) (/builds/Calinou/godot-builds-ci/godot/editor/editor_file_system.cpp:2098 (discriminator 5))
[14] EditorFileSystem::_update_scan_actions() (/builds/Calinou/godot-builds-ci/godot/editor/editor_file_system.cpp:609)
[15] EditorFileSystem::_notification(int) (/builds/Calinou/godot-builds-ci/godot/editor/editor_file_system.cpp:1192)
[16] EditorFileSystem::_notificationv(int, bool) (/builds/Calinou/godot-builds-ci/godot/editor/editor_file_system.h:113 (discriminator 14))
[17] Object::notification(int, bool) (/builds/Calinou/godot-builds-ci/godot/core/object/object.cpp:843)
[18] SceneTree::_notify_group_pause(StringName const&, int) (/builds/Calinou/godot-builds-ci/godot/scene/main/scene_tree.cpp:851)
[19] SceneTree::process(double) (/builds/Calinou/godot-builds-ci/godot/scene/main/scene_tree.cpp:455 (discriminator 2))
[20] Main::iteration() (/builds/Calinou/godot-builds-ci/godot/main/main.cpp:2530)
[21] OS_LinuxBSD::run() (/builds/Calinou/godot-builds-ci/godot/platform/linuxbsd/os_linuxbsd.cpp:342)
[22] /home/me/godot(main+0x162) [0x20e2d34] (/builds/Calinou/godot-builds-ci/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[23] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7ff970870d0a] (??:0)
[24] /home/me/godot(_start+0x29) [0x20e2b29] (??:?)
```

### Steps to reproduce

See in the comments.

### Minimal reproduction project

See in the comments.

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #51373

* Null pointer access when calling `Set::lower_bound` on empty sets.
* Some branches did not handle negative polygon index.

### CODE REVIEW

File: modules/fbx/data/fbx_mesh_data.cpp [hunk 1]
```diff
@@ -1092,7 +1092,10 @@ HashMap<int, R> FBXMeshData::extract_per_vertex_data(
 					const int vertex_index = get_vertex_from_polygon_vertex(p_mesh_indices, polygon_vertex_index);
 					ERR_FAIL_COND_V_MSG(vertex_index < 0, (HashMap<int, R>()), "FBX file corrupted: #ERR05");
 					ERR_FAIL_COND_V_MSG(vertex_index >= p_vertex_count, (HashMap<int, R>()), "FBX file corrupted: #ERR06");
-					const int index_to_direct = p_mapping_data.index[polygon_vertex_index];
+					int index_to_direct = p_mapping_data.index[polygon_vertex_index];
+					if (index_to_direct < 0) {
+						index_to_direct = ~index_to_direct; // Relative to the end.
```
Comment (akien-mga) [inline modules/fbx/data/fbx_mesh_data.cpp:1097]: CC @RevoluPowered 

Are you sure that this always give a valid index and the one expected?
Other places in this file seem to have ERR conditions for negative `p_mapping_data.index[vertex_index]`.

Comment (timothyqiu) [reply modules/fbx/data/fbx_mesh_data.cpp:1097]: Negative indices are only allowed when handling polygons according to [this tutorial](https://banexdevblog.wordpress.com/2014/06/23/a-quick-tutorial-about-the-fbx-ascii-format/) and the [blender fbx importer](https://github.com/blender/blender-addons/blob/40e34a8bbb30c6a4ddc73aa11e92c6bd2095eb80/io_scene_fbx/import_fbx.py#L1269-L1280).

These touched codes are for `MapType::polygon_vertex` and `MapType::polygon`.

This one is for `MapType::vertex`:

https://github.com/godotengine/godot/blob/d7464757084099765dee5755b21a8847f4226360/modules/fbx/data/fbx_mesh_data.cpp#L1078

Comment (timothyqiu) [reply modules/fbx/data/fbx_mesh_data.cpp:1097]: Ah, I think `FBXMeshData::get_vertex_from_polygon_vertex()` is an existing wrapper code for this logic. I should change the code to use that directly.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.
