### PR TITLE
Fix how scripts reload outside of ScriptEditor

### LINKED ISSUE #89029: Save in VS code in 4.3-dev5
### Tested versions

Only tested in 4.3-dev3 to 4.3-dev5

### System information

Godot v4.3.dev4.mono - openSUSE Tumbleweed 20240226 - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

And, if you are using VS Code (I did not tried with other IDES), modifies something in your code, then run the game. Godot "makes" a Ctrl + z to the code. To see your last change, in your code, do a Ctrl + z. Yes, its super weird.

### Steps to reproduce

* Modify something in your code.
* Run the game.

### Minimal reproduction project (MRP)

With a minimal project.
This issue, affects after sometime, like 5 mins working with Godot, not at start. It happens to me, with the last 2 4.3 dev releases all the time.

### LINKED ISSUE #89239: 4.3 csharp files are changed on editor save causing issues in IDEs - regression?
### Tested versions

Reproducible in: 4.3 dev4 and 4.3[bfdac951e3efe87c14a18ca33b16bb901687a43f]
Not reproducible: 4.2.1

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

Video showcasing the issue in 4.3 and comparison with 4.2.1: https://youtu.be/LFMKV9npR8U

In 4.3 for some reason saving editor when any scene is open also modifies c# files which were last modified for some reason, this causes discontinuity in how IDEs see the file since the IDEs now see that the file was modified, one such issue is in Rider when a popup dialog appears asking you if you want to reload from disk when you try to undo every time. This is increadibly annoying.

From the file itself codewise nothing changes, so maybe godot started changing some meta data or some kind of format?

I've been checking modified status in windows file explorer (also the issue with undo happening in my IDE constantly which doesn't seem to happen in 4.2.1).

### Steps to reproduce

(Follow the video above for clarity or steps below)

1. Create a C# godot project
2. Build the project.
3. Add any node and attach a C# script (or open the attached script through the editor in MRP).
4. Make any changes to the file, for example add couple empty lines. (this step is necessary the IDE first needs totake the current state of the file into account).
5. Open a file explorer and check the script file's modified status, write down/remember the date + time.
6. Wait for a minute or more (depends on what is the minimum change your system can display, in this test I recommend a minute to make it simpler to notice the change clearly).
7. Switch to Godot editor and pres CTRL + S (save scene/all scenes) while the scene is opened (if no scene is opened then nothing happens, if you change script A but have a scene B with a script B open then the issue still happens in the script A even though you are saving scene B).
8. Go to the file explorer, refresh the window if you haven't (typically F5 shortcut), and observe the changed modified status.
9. Open the script file in your IDE and observe that all the code is still the same.
(10. This can cause issues in IDE syncing with files/undo history and I don't know what else, in my case it's undo issues in Jetbrains Rider)

### Minimal reproduction project (MRP)

[Test43master.zip](https://github.com/godotengine/godot/files/14517179/Test43master.zip)

### PR DESCRIPTION
**Pull request by paulloz**
- Relates to #82113
- Fixes #89239
- Fixes #89029

#82113 made script being reloaded from outside `ScriptEditor`. The current `Resource::reload_from_file()` implementation indirectly calls `Object::set_edited(true)` on the script resource, so any script reloaded that way ends up being overwritten by the engine when a scene they are in is saved.  

This is simply making sure we apply the same logic in `Script::reload_from_file()` as in `ScriptEditor::reload_scripts()`. Although, it feels quite weird that we purposefully call that method when `Script::editor_can_reload_from_file()` returns `false`.

### CODE REVIEW

**Review by Chubercik — APPROVED** [review]

**Comment by akien-mga** [comment]
CC @nongvantinh

**Comment by nongvantinh** [comment]
Hi @paulloz,

When `Script::editor_can_reload_from_file()` returns `false`, it means the Editor won't update to reflect new changes in that script.

If the file is edited outside the editor and we don't use the internal editor, there's no way to get the latest changes. Consequently, whenever we use data of that file from `ResourceCache`, we always get outdated data, which can lead to issues requiring the most current and valid data. For instance, when we press Ctrl + S and the resource's state is marked as `edited`, then we save the current state of that script using `ResourceCache`, causing it to override the changes we made previously.

This problem stems from the `Script::reload_from_file()` method, which hasn't been used before. If it were, this issue would have occurred long ago. However, thanks to #82113, we now know that it doesn't function correctly.

File: core/object/script_language.cpp [hunk 1]
```diff
@@ -154,6 +155,24 @@ void Script::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::STRING, "source_code", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_NONE), "set_source_code", "get_source_code");
 }
 
+void Script::reload_from_file() {
+#ifdef TOOLS_ENABLED
+	// Replicates how the ScriptEditor reloads script resources, which generally handles it.
+	// However, when scripts are to be reloaded but aren't open in the internal editor, we go through here instead.
+	const Ref<Script> rel = ResourceLoader::load(ResourceLoader::path_remap(get_path()), get_class(), ResourceFormatLoader::CACHE_MODE_IGNORE);
+	if (!rel.is_valid()) {
```
Comment (KoBeWi) [inline core/object/script_language.cpp:163]:
```suggestion
	if (rel.is_null()) {
```

**Review by KoBeWi — APPROVED** [review]
I can't reproduce the issue with GDScript, but the code looks fine.

**Comment by akien-mga** [comment]
Thanks!
