### PR TITLE
Restore metadata to script create dialog

### LINKED ISSUE #67988: Disabling script template is not remembered after editor restart
### Godot version

4.0 11e1bac

### System information

Windows 10 x64

### Issue description

When you disable script template to have an empty script, it will only be remembered until you exit the editor. Next time you will have to disable it again. Pretty sure it wasn't like that when the feature was implemented for the first time.

### Steps to reproduce

1. Add script to node
2. Uncheck this
image
3. Restart the editor
4. It's enabled again

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
#53957 used a small trick to store editor-wide settings in a way that isn't exposed to the settings dialog. It used metadata and was later broken after #59452, because it made slashes no longer allowed in metadata names. The errors were fixed in #59603, but it was not a correct fix, because it made the choices no longer remembered between sessions.

This PR reverts #59603 and fixes the original problem, i.e. invalid metadata names.
Fixes #67988
Supersedes #68045

### CODE REVIEW

File: editor/script_create_dialog.cpp [hunk 1]
```diff
@@ -330,8 +332,13 @@ void ScriptCreateDialog::_template_changed(int p_template) {
 			dic_templates_project[parent_name->get_text()] = sinfo.get_hash();
 			EditorSettings::get_singleton()->set_project_metadata("script_setup", "templates_dictionary", dic_templates_project);
 		} else {
-			// Save template info to editor dictionary (not a project template).
-			templates_dictionary[parent_name->get_text()] = sinfo.get_hash();
+			// Save template into to editor dictionary (not a project template).
```
Comment (akien-mga) [inline editor/script_create_dialog.cpp:335]: The "info" wasn't a typo here I think. At least the new sentence doesn't make sense ("into to").

**Comment by akien-mga** [comment]
To see the fix properly, it could be meaning to have this as two commits: One `git revert bb5198a5ac92a6fe699751df9bb9c09109a2955a`, and then a commit with the fix for the original bug.
If that's too bothersome to make though, don't worry.

File: editor/script_create_dialog.cpp (hunk 1 above)
Comment (KoBeWi) [reply editor/script_create_dialog.cpp:335]: That's the original comment, I'll fix it.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
