### PR TITLE
Fix some code found by Coverity Scan and PVS Studio

### LINKED ISSUE #27638: Potential bugs raised by static analyser (part 1)
Godot 3.1 f64336f

Recently I checked Godot code with PVS-Studio which is a static analyser and I maybe found some bugs/mist.

- [x] 1. godot/platform/x11/joypad_linux.cpp:448: ostrzeżenie: V519 The 'jx.value' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 446, 448.

jx.value always will have value "(float)p_value / max", even if p_value is lesser than 0
I think that should have else
```		
if (p_value < 0) {
	jx.value = (float)-p_value / min;
}
else {
	jx.value = (float)p_value / max;
}
```

- [ ] 2. godot/platform/x11/joypad_linux.cpp:515(also 516, 517): ostrzeżenie: V557 Array overrun is possible. The value of 'ev.code' index could reach 766.

In declaration abs_map has size 63 if ev.code is bigger than 63 and smaller than 767 then can overrun an array. If ev.code always have smaller value, then it is not necessary to check it with MAX_KEY but with MAX_ABS
```
enum {
	JOYPADS_MAX = 16,
	MAX_ABS = 63,
	MAX_KEY = 767, // Hack because <linux/input.h> can't be included here
};
int abs_map[MAX_ABS]; 
...
if (ev.code >= MAX_KEY)
	return;
...
if (joy->abs_map[ev.code] != -1 && joy->abs_info[ev.code]) {
	InputDefault::JoyAxis value = axis_correct(joy->abs_info[ev.code], ev.value);
	joy->curr_axis[joy->abs_map[ev.code]] = value;
}
```
To fix this I think that abs_map could have bigger size
```
int abs_map[MAX_KEY];
```
or check about ev.code should be more restrict
```
if (ev.code >= MAX_ABS)
	return;
```

- [x] 3. /godot/platform/x11/crash_handler_x11.cpp:99: ostrzeżenie: V547 Expression 'OS::get_singleton()' is always true.
check if OS::get_singleton() is NULL happens in line 49

- [x] 4. /godot/platform/x11/power_x11.cpp:118: błąd: V590 Consider inspecting the '(* ptr == ' ') && (* ptr != '\0')' expression. The expression is excessive or contains a misprint.

A pointer can't point at two objects, if show at the ' ', the second part about != '\0' is always true.
4 png

- [x] 5. /home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:46: ostrzeżenie: V575 The potential null pointer is passed into 'getcwd' function. Inspect the first argument. Check lines: 46, 45.

- [x] 6. godot/modules/gdscript/gdscript.h:411: ostrzeżenie: V1004 The '_call_stack[i].function' pointer was used unsafely after it was verified against nullptr. Check lines: 409, 411.

This code should look like this:
```
if (_call_stack[i].function){
	csi.write[_debug_call_stack_pos - i - 1].func = _call_stack[i].function->get_name();
	csi.write[_debug_call_stack_pos - i - 1].file = _call_stack[i].function->get_script()->get_path();
}
```
not that, because we don't check properly if _call_stack[i].function exists
```
if (_call_stack[i].function)
	csi.write[_debug_call_stack_pos - i - 1].func = _call_stack[i].function->get_name();
csi.write[_debug_call_stack_pos - i - 1].file = _call_stack[i].function->get_script()->get_path();
```

- [x] 7. godot/core/vmap.h:200: błąd: V614 Instantiation of VMap < uint32_t, uint32_t >: Uninitialized variable 'val' used. Consider checking the second actual argument of the 'insert' function.

Uninitialised variable put into function without checking, Hmmm...

- [x] 8. godot/main/tests/test_gdscript.cpp:896: błąd: V547 Expression 'incr == 0' is always true.

This condition is always true so better would be write this
```
if (incr == 0) {

	ERR_EXPLAIN("unhandled opcode: " + itos(code[ip]));
	ERR_BREAK(true);
}
```

- [x] 9. 
godot/core/list.h:506: ostrzeżenie: V547 Expression 'p_I->next_ptr' is always true.
and
godot/core/list.h:541: ostrzeżenie: V547 Expression 'p_I->prev_ptr' is always true.

Pointer always will point at some value because at the top is checked if point at null 

- [x] 10. godot/core/math/rect2.h:70: ostrzeżenie: V547 Expression 'inside' is always true.

I think that was caused by copy/paste and this isn't bug, but this code shouldn't trigger the analyser:
```
bool inside = true;

if (p_point.x < position.x) {
	real_t d = position.x - p_point.x;
	dist = d;
	inside = false;
}
if (p_point.y < position.y) {
	real_t d = position.y - p_point.y;
	dist = inside ? d : MIN(dist, d);
	inside = false;
}
```

I used this tool first time and I don't have big C++ acknowledge so issues from above can be a false flags.

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #27638, in others parts(2 - 4) just remain 1/2 open issues so I create another one, which will contain them and also new possible issues found by Coverity Scan

Changes in power_x11.cpp was done because in SDL code(https://github.com/spurious/SDL-mirror/blob/17af4584cb28cdb3c2feba17e7d989a806007d9f/src/power/SDL_power.c), directory was just closed
```
    closedir(dirp);
}
dirp = opendir(proc_acpi_ac_adapter_path);
```
but in Godot, memory was deleted, which can cause crash 
```
    memdelete(dirp);
}
dirp->change_dir(proc_acpi_ac_adapter_path);
```

### CODE REVIEW

File: core/class_db.cpp [hunk 1]
```diff
@@ -480,6 +480,8 @@ uint64_t ClassDB::get_api_hash(APIType p_api) {
 			for (List<StringName>::Element *F = snames.front(); F; F = F->next()) {
 
 				PropertySetGet *psg = t->property_setget.getptr(F->get());
+				if (!psg)
+					continue;
```
Comment (akien-mga) [inline core/class_db.cpp]: If that's a hypothetical case that doesn't actually happen, this should probably be `ERR_CONTINUE()`, so that we know that we're getting a broken hash. CC @neikeq

File: platform/uwp/export/export.cpp [hunk 2]
```diff
@@ -519,7 +519,9 @@ Error AppxPackager::add_file(String p_file_name, const uint8_t *p_buffer, size_t
 
 			int total_out_before = strm.total_out;
 
-			deflate(&strm, Z_FULL_FLUSH);
+			int err = deflate(&strm, Z_FULL_FLUSH);
+			ERR_FAIL_COND_V(Error(err) != OK, ERR_BUG);
```
Comment (akien-mga) [inline platform/uwp/export/export.cpp]: We shouldn't cast thirdparty error codes to our own, there's no guarantee that we use the same conventions. Here the equivalent woudl be `err != Z_OK` (see `zlib.h`), though I think `Z_STREAM_END` (1) is also a success return value:
```
deflate() returns Z_OK if some progress has been made (more input
  processed or more output produced), Z_STREAM_END if all input has been
  consumed and all output has been produced (only when flush is set to
  Z_FINISH), Z_STREAM_ERROR if the stream state was inconsistent (for example
  if next_in or next_out was Z_NULL or the state was inadvertently written over
  by the application), or Z_BUF_ERROR if no progress is possible (for example
  avail_in or avail_out was zero).  Note that Z_BUF_ERROR is not fatal, and
  deflate() can be called again with more input and more output space to
  continue compressing.
```

Maybe `err >= 0` would be safer as per:
```
#define Z_OK            0
#define Z_STREAM_END    1
#define Z_NEED_DICT     2
#define Z_ERRNO        (-1)
#define Z_STREAM_ERROR (-2)
#define Z_DATA_ERROR   (-3)
#define Z_MEM_ERROR    (-4)
#define Z_BUF_ERROR    (-5)
#define Z_VERSION_ERROR (-6)
/* Return codes for the compression/decompression functions. Negative values
 * are errors, positive values are used for special but normal events.
 */
```

File: scene/main/scene_tree.cpp [hunk 3]
```diff
@@ -1507,8 +1507,11 @@ void SceneTree::_live_edit_instance_node_func(const NodePath &p_parent, const St
 		Node *n2 = n->get_node(p_parent);
 
 		Node *no = ps->instance();
-		no->set_name(p_name);
+		if (!no) {
+			continue;
```
Comment (akien-mga) [inline scene/main/scene_tree.cpp]: Should maybe be `ERR_CONTINUE` too, I don't think we want to silently ignore a failure to instantiate a packed scene.

Comment (qarmin) [reply scene/main/scene_tree.cpp]: I just copy behaviour from above https://github.com/godotengine/godot/blob/437939589234559febabb9a4c392145521a9c3a5/scene/main/scene_tree.cpp#L1474-L1480

Comment (akien-mga) [reply scene/main/scene_tree.cpp]: Alright, makes sense then I guess :)

File: core/class_db.cpp (hunk 1 above)
Comment (neikeq) [reply core/class_db.cpp]: I would use `CRASH_COND` here, but [the code above](https://github.com/godotengine/godot/blob/017b224a87064a3d333ba63809a0f12cfe2c4412/core/class_db.cpp#L378) uses `ERR_FAIL_COND_V` so that may be better for consistency.

Comment (akien-mga) [reply core/class_db.cpp]: Should be `ERR_FAIL_COND_V(!psg, 0)` then @qarmin.

**Comment by akien-mga** [comment]
Thanks!
