### PR TITLE
Fixed navigation schemes Modo/Maya when used with grid map tile place…

### LINKED ISSUE #17906: MODO Navigation Scheme Does Not Work with GridMaps
Godot v3.0.2

Windows 10, Nvidia GeForce 1070

MODO Navigation Scheme does not work with GridMap tile placement.

If you go to Editor>Editor Settings>Navigation>Navigation Scheme and change the Scheme to MODO, then you can no longer navigate the viewport when placing GridMap tiles.

- Go through the steps to create a GridMap
- Go to Editor>Editor Settings>Navigation>Navigation Scheme and change the scheme to MODO
- Click on a GridMap item to start placing instances in the viewport
- Attempt to rotate or pan the viewport using MODO shortcuts (SHIFT+LMB, etc.)

### PR DESCRIPTION
**Pull request by zqyoung1**
Completely fixes #17906
When using grid maps, tile placement and Maya/Modo navigation schemes were previously incompatible.

### CODE REVIEW

File: modules/gridmap/grid_map_editor_plugin.h [hunk 1]
```diff
@@ -176,6 +176,12 @@ class GridMapEditor : public VBoxContainer {
 
 	};
 
+	enum NavigationScheme {
```
Comment (akien-mga) [inline modules/gridmap/grid_map_editor_plugin.h]: Can't we reuse `SpatialEditorPlugin::NavigationScheme` instead of duplicating it?

Comment (zqyoung1) [reply modules/gridmap/grid_map_editor_plugin.h]: Yeah we definitely can and should. My bad

**Comment by akien-mga** [comment]
Could you squash commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by akien-mga** [comment]
Squashed it myself, can be merged.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Youngey339** [comment]
Sorry! I Didn't see that this PR was looked at again since I cleaned up the code. Would have squashed it myself otherwise.

**Comment by zqyoung1** [comment]
Sorry!! I didn't realize this PR was looked at since I cleaned up the prior issues. I should have squashed it myself -- sorry.  Glad I could help regardless!

**Comment by akien-mga** [comment]
No worry :)
