### PR TITLE
Only allow valid types in Decal, Light3D projector, PointLight2D texture and CSGMesh3D mesh

### LINKED ISSUE #77564: Decal with MeshTexture appears broken (not visible, and also affects other decals)
### Godot version

4.0.3 (.NET)

### System information

- Windows 11
- Forward+
- Nvidia GTX 3060

### Issue description

I am trying to use a Decal with a MeshTexture, because in my game it would be very useful to dynamically draw decal shapes at runtime, which I could do by creating a MeshTexture with SurfaceTool etc, as far as I understand.

However, Decals with MeshTextures as their texture appears to not work. There are two problems I encounter:

1. The Decal with the MeshTexture itself is not visible.
2. Other, nearby Decals with regular Texture2D textures, can also seemingly break when the MeshTexture Decal is present. It varies when moving them around relative to each other, but in many positions, when the MeshTexture Decal is present, the regular Decal can also turn invisible or be clipped.

Take a look at the reproduction project. There should be three decals visible, but only one is.  To verify that the MeshTexture used in the decal in the sample project is a valid one, you can enable the TestingTexture instance. I generated the MeshTexture by converting a Sprite2D to this MeshInstance2D.

The documentation for MeshTexture is also generally very barebone. It is hard to understand exactly what this class does and how it's used, maybe this whole issue stems from me using it incorrectly.

### Steps to reproduce

1. Open the reproduction project and run it.
2. Note that only one decal (blue circle) is visible, despite there being three decals in the tree. MeshTextureDecal and RegularTextureDecal2 should be visible too, but are not.
3. Disable MeshTextureDecal.
4. Note that RegularTextureDecal2 somehow became visible after step 3.

### Minimal reproduction project

[meshtexture_decal_test.zip](https://github.com/godotengine/godot/files/11583745/meshtexture_decal_test.zip)

### PR DESCRIPTION
**Pull request by Calinou**
If an invalid type is supplied (which can still be done from a script), a warning is printed (along with a workaround for ViewportTexture).

This also adds support for "negative" resource hints such as `"Texture2D,-ViewportTexture"` to exclude one or more subclasses from a class hint.

**Testing project:** [test_decal_warning.zip](https://github.com/godotengine/godot/files/14289574/test_decal_warning.zip)

- This closes https://github.com/godotengine/godot/issues/77564.
See also https://github.com/godotengine/godot/issues/54506,
https://github.com/godotengine/godot/issues/73400,
and https://github.com/godotengine/godot/issues/75868.

## Preview

Before | After
-|-
Screenshot_20240215_001706 | image

```
WARNING: ViewportTexture is not supported as a PointLight2D texture (/root/Node3D/PointLight2D). As a workaround, use `get_image()` on the ViewportTexture to assign the returned value to the PointLight2D texture property, but keep in mind this is a slow operation.
     at: set_texture (./scene/2d/light_2d.cpp:405)
WARNING: AtlasTexture is not supported as a Light3D projector texture (/root/Node3D/OmniLight3D).
     at: set_projector (./scene/3d/light_3d.cpp:207)
WARNING: MeshTexture is not supported as a Decal texture (/root/Node3D/Decal2).
     at: set_texture (./scene/3d/decal.cpp:66)
```

### CODE REVIEW

File: scene/2d/light_2d.cpp [hunk 1]
```diff
@@ -449,7 +476,7 @@ void PointLight2D::_bind_methods() {
 	ClassDB::bind_method(D_METHOD("set_texture_scale", "texture_scale"), &PointLight2D::set_texture_scale);
 	ClassDB::bind_method(D_METHOD("get_texture_scale"), &PointLight2D::get_texture_scale);
 
-	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "texture", PROPERTY_HINT_RESOURCE_TYPE, "Texture2D"), "set_texture", "get_texture");
+	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "texture", PROPERTY_HINT_RESOURCE_TYPE, "CompressedTexture2D,PortableCompressedTexture2D,ImageTexture,CurveTexture,CurveXYZTexture,GradientTexture1D,GradientTexture2D,PlaceholderTexture2D,NoiseTexture2D"), "set_texture", "get_texture");
```
Comment (Calinou) [inline scene/2d/light_2d.cpp:479]: This list of types is something we should probably reuse across in the editor a lot more, as there are a *lot* of situations where a type like CameraTexture or AtlasTexture is not allowed (only one or two of those at at time).

Maybe we should have a special syntax using `-` to denote exceptions, like `Texture2D,-ViewportTexture,-AtlasTexture` to allow anything that extends Texture2D *except* ViewportTexture and AtlasTexture.

Comment (Mickeon) [reply scene/2d/light_2d.cpp:480]: I did not even know this was a feature. Concerning to me. It has been here for a while, yet PROPERTY_HINT_RESOURCE_TYPE is not documented well enough to showcase this.

File: scene/3d/light_3d.cpp [hunk 2]
```diff
@@ -191,6 +199,25 @@ Light3D::BakeMode Light3D::get_bake_mode() const {
...
+	} else if (Object::cast_to<CameraTexture>(*p_texture)) {
+		WARN_PRINT(vformat("CameraTexture is not supported as a Light3D projector texture (%s).", get_path()));
+	} else if (Object::cast_to<CanvasTexture>(*p_texture)) {
+		WARN_PRINT(vformat("CanvasTexture is not supported as a Light3D projector texture (%s).", get_path()));
+	} else if (Object::cast_to<MeshTexture>(*p_texture)) {
+		WARN_PRINT(vformat("MeshTexture is not supported as a Light3D projector texture (%s).", get_path()));
+	} else if (Object::cast_to<Texture2DRD>(*p_texture)) {
+		WARN_PRINT(vformat("Texture2DRD is not supported as a Light3D projector texture (%s).", get_path()));
+	} else if (Object::cast_to<ViewportTexture>(*p_texture)) {
+		WARN_PRINT(vformat("ViewportTexture is not supported as a Light3D projector texture (%s). As a workaround, use `get_image()` on the ViewportTexture to assign the returned value to the Light3D projector property, but keep in mind this is a slow operation.", get_path()));
```
Comment (Mickeon) [inline scene/3d/light_3d.cpp:217]: This is the kind of thing I would expect to see on a Note in the class reference.
I don't think it's out of place here, just a bit of a mouthful. And that's not mentioning how long it gets when the node's path is included.
```suggestion
		WARN_PRINT(vformat("ViewportTexture cannot be used as a Light3D projector texture (%s). As a workaround, create an ImageTexture from the ViewportTexture's `get_image()`.", get_path()));
```
The "slow operation" part is important too, of course, it's just... a lot of information to cram into a warning.

File: scene/2d/light_2d.cpp (hunk 1 above)
Comment (KoBeWi) [reply scene/2d/light_2d.cpp:480]: > Maybe we should have a special syntax using - to denote exceptions, like Texture2D,-ViewportTexture,-AtlasTexture to allow anything that extends Texture2D except ViewportTexture and AtlasTexture.

That sounds more scalable in case new texture types are added. I think the hint is only used in EditorResourcePicker, so it should be trivial to implement (the picker already unfolds the base type into inheriting classes).

File: scene/2d/light_2d.cpp [hunk 3]
```diff
@@ -28,6 +28,15 @@
 /* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
 /**************************************************************************/
 
+#include "scene/main/canvas_item.h"
```
Comment (AThousandShips) [inline scene/2d/light_2d.cpp:31]:
```suggestion
#include "light_2d.h"

#include "scene/main/canvas_item.h"
```
And remove below

File: scene/3d/decal.cpp [hunk 4]
```diff
@@ -28,6 +28,14 @@
 /* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
 /**************************************************************************/
 
+#include "scene/main/canvas_item.h"
```
Comment (AThousandShips) [inline scene/3d/decal.cpp:31]:
```suggestion
#include "decal.h"

#include "scene/main/canvas_item.h"
#include "scene/main/viewport.h"
```

File: scene/3d/light_3d.cpp [hunk 5]
```diff
@@ -29,6 +29,14 @@
 /**************************************************************************/
 
 #include "core/config/project_settings.h"
```
Comment (AThousandShips) [inline scene/3d/light_3d.cpp:31]:
```suggestion
#include "light_3d.h"

#include "core/config/project_settings.h"
```
Though it's odd that this is included before the header in the first place

File: doc/classes/ViewportTexture.xml [hunk 6]
```diff
@@ -7,6 +7,7 @@
 		Provides the content of a [Viewport] as a dynamic [Texture2D]. This can be used to mix controls, 2D game objects, and 3D game objects in the same scene.
 		To create a [ViewportTexture] in code, use the [method Viewport.get_texture] method on the target viewport.
 		[b]Note:[/b] A [ViewportTexture] is always local to its scene (see [member Resource.resource_local_to_scene]). If the scene root is not ready, it may return incorrect data (see [signal Node.ready]).
+		[b]Note:[/b] Some nodes such as [Decal], [Light3D] projector texture and [PointLight2D] texture don't support using [ViewportTexture] directly. To use texture data from a [ViewportTexture] in these nodes, you need to create an [ImageTexture] by calling [method Texture2D.get_image] on the [ViewportTexture]. This conversion is a slow operation, so it should not be performed every frame.
```
Comment (Mickeon) [inline doc/classes/ViewportTexture.xml:10]: I don't see why mentioning the properties like these for a few reason:
- "Some nodes such as", but then the sentence refers to the properties specifically;
- All of these nodes only have one property that accepts **Texture2D** (and if there were more they likely wouldn't support **ViewportTexture** either);
- They cannot be translated consistently like this, compared to e.g. `[member Light3D.projector_texture]`.
```suggestion
		[b]Note:[/b] Some nodes such as [Decal], [Light3D] and [PointLight2D] do not support using [ViewportTexture] directly. To use texture data from a [ViewportTexture] in these nodes, you need to create an [ImageTexture] by calling [method Texture2D.get_image] on the [ViewportTexture]. This conversion is a slow operation, so it should not be performed every frame.
```

File: doc/classes/Texture2D.xml [hunk 7]
```diff
@@ -124,7 +124,7 @@
 			<description>
 				Returns an [Image] that is a copy of data from this [Texture2D] (a new [Image] is created each time). [Image]s can be accessed and manipulated directly.
 				[b]Note:[/b] This will return [code]null[/code] if this [Texture2D] is invalid.
-				[b]Note:[/b] This will fetch the texture data from the GPU, which might cause performance problems when overused.
+				[b]Note:[/b] This will fetch the texture data from the GPU, which might cause performance problems when overused. Avoid calling [method get_image] every frame, especially on large images.
```
Comment (Mickeon) [inline doc/classes/Texture2D.xml:127]:
```suggestion
				[b]Note:[/b] This will fetch the texture data from the GPU, which might cause performance problems when overused. Avoid calling [method get_image] every frame, especially on large textures.
```

**Review by Mickeon — APPROVED** [review]
Not sure about "every frame", I'd say "frequently" but it's nitpicky.

Yippie

File: scene/3d/decal.cpp [hunk 8]
```diff
@@ -30,6 +30,15 @@
...
 #include "decal.h"
 
+#include "scene/main/canvas_item.h"
+#include "scene/main/viewport.h"
+#include "scene/resources/animated_texture.h"
+#include "scene/resources/atlas_texture.h"
+#include "scene/resources/camera_texture.h"
+#include "scene/resources/mesh_texture.h"
+#include "scene/resources/texture.h"
+#include "scene/resources/texture_rd.h"
```
Comment (akien-mga) [inline scene/3d/decal.cpp:40]: It seems a bit unfortunate to add all these dependencies just for a warning, which will cause recompilation any time one of these texture types or their dependencies is edited.

Comment (KoBeWi) [reply scene/3d/decal.cpp:40]: These includes could be debug-only at least.

File: scene/2d/light_2d.cpp [hunk 9]
```diff
@@ -379,6 +388,24 @@ Rect2 PointLight2D::get_anchorable_rect() const {
...
+			WARN_PRINT(vformat("CameraTexture cannot be used as a PointLight2D texture (%s).", get_path()));
+		} else if (Object::cast_to<CanvasTexture>(*p_texture)) {
+			WARN_PRINT(vformat("CanvasTexture cannot be used as a PointLight2D texture (%s).", get_path()));
+		} else if (Object::cast_to<MeshTexture>(*p_texture)) {
+			WARN_PRINT(vformat("MeshTexture cannot be used as a PointLight2D texture (%s).", get_path()));
+		} else if (Object::cast_to<Texture2DRD>(*p_texture)) {
+			WARN_PRINT(vformat("Texture2DRD cannot be used as a PointLight2D texture (%s).", get_path()));
+		} else if (Object::cast_to<ViewportTexture>(*p_texture)) {
+			WARN_PRINT(vformat("ViewportTexture cannot be used as a PointLight2D texture (%s). As a workaround, assign the value returned by ViewportTexture's `get_image()` instead.", get_path()));
+		}
```
Comment (KoBeWi) [inline scene/2d/light_2d.cpp:406]: I think this should be replaced by a method that takes texture type and automatically includes it in the warning message. You can use `is_class()` to check class by String.
Not sure where to put the method though, perfectly it should be one for all 3 classes.

Comment (Calinou) [reply scene/2d/light_2d.cpp]: I've simplified the code somewhat for each class. I'm not sure where a generic method could be put so it can be reused across all 3 classes though.

File: doc/classes/ViewportTexture.xml [hunk 10]
```diff
@@ -7,6 +7,7 @@
 		Provides the content of a [Viewport] as a dynamic [Texture2D]. This can be used to mix controls, 2D game objects, and 3D game objects in the same scene.
 		To create a [ViewportTexture] in code, use the [method Viewport.get_texture] method on the target viewport.
 		[b]Note:[/b] A [ViewportTexture] is always local to its scene (see [member Resource.resource_local_to_scene]). If the scene root is not ready, it may return incorrect data (see [signal Node.ready]).
+		[b]Note:[/b] Some nodes such as [Decal], [Light3D] and [PointLight2D] do not support using [ViewportTexture] directly. To use texture data from a [ViewportTexture] in these nodes, you need to create an [ImageTexture] by calling [method Texture2D.get_image] on the [ViewportTexture]. This conversion is a slow operation, so it should not be performed every frame.
```
Comment (AThousandShips) [inline doc/classes/ViewportTexture.xml:10]:
```suggestion
		[b]Note:[/b] Some nodes such as [Decal], [Light3D], and [PointLight2D] do not support using [ViewportTexture] directly. To use texture data from a [ViewportTexture] in these nodes, you need to create an [ImageTexture] by calling [method Texture2D.get_image] on the [ViewportTexture]. This conversion is a slow operation, so it should not be performed every frame.
```

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
There are these errors to handle for the GDExtension compatibility checker:
```
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_albedo': type changed value in new API, from "Texture" to "CompressedTexture2D,PortableCompressedTexture2D,ImageTexture,CurveTexture,CurveXYZTexture,GradientTexture1D,GradientTexture2D,PlaceholderTexture2D,NoiseTexture2D".
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_emission': type changed value in new API, from "Texture" to "CompressedTexture2D,PortableCompressedTexture2D,ImageTexture,CurveTexture,CurveXYZTexture,GradientTexture1D,GradientTexture2D,PlaceholderTexture2D,NoiseTexture2D".
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_normal': type changed value in new API, from "Texture" to "CompressedTexture2D,PortableCompressedTexture2D,ImageTexture,CurveTexture,CurveXYZTexture,GradientTexture1D,GradientTexture2D,PlaceholderTexture2D,NoiseTexture2D".
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_orm': type changed value in new API, from "Texture" to "CompressedTexture2D,PortableCompressedTexture2D,ImageTexture,CurveTexture,CurveXYZTexture,GradientTexture1D,GradientTexture2D,PlaceholderTexture2D,NoiseTexture2D".
Validate extension JSON: Error: Field 'classes/Light3D/properties/light_projector': type changed value in new API, from "Texture2D" to "CompressedTexture2D,PortableCompressedTexture2D,ImageTexture,CurveTexture,CurveXYZTexture,GradientTexture1D,GradientTexture2D,PlaceholderTexture2D,NoiseTexture2D".
Validate extension JSON: Error: Field 'classes/PointLight2D/properties/texture': type changed value in new API, from "Texture2D" to "CompressedTexture2D,PortableCompressedTexture2D,ImageTexture,CurveTexture,CurveXYZTexture,GradientTexture1D,GradientTexture2D,PlaceholderTexture2D,NoiseTexture2D".
```

I'm not sure how those hints are used in godot-cpp when there's multiple classes, cc @dsnopek

**Comment by raulsntos** [comment]
> I'm not sure how those hints are used in godot-cpp when there's multiple classes

AFAIK godot-cpp doesn't use the properties from the JSON. Since C++ doesn't have properties I guess there's nothing to generate, so they only generate the getter/setter methods.

In C#, we use the getter/setter method signature to determine the property type not the hint, so it doesn't affect us either.

**Comment by Mickeon** [comment]
I have not a clue as to why the check is still failing but I wanted to mention it as a reminder.

**Comment by KoBeWi** [comment]
If this is going to "break compatibility", it's better to do it properly. I was going to open a PR for that, but feel free to add this commit and use it to simplify the hints:
https://github.com/godotengine/godot/commit/ff8f797b54f64da2cc166971aa6e63d0dfa205c6
You can do e.g. `"Texture2D,-ViewportTexture"` to allow everything except ViewportTexture.

**Comment by Calinou** [comment]
> If this is going to "break compatibility", it's better to do it properly. I was going to open a PR for that, but feel free to add this commit and use it to simplify the hints: [ff8f797](https://github.com/godotengine/godot/commit/ff8f797b54f64da2cc166971aa6e63d0dfa205c6) You can do e.g. `"Texture2D,-ViewportTexture"` to allow everything except ViewportTexture.

This code works, but it causes the items to be reordered with this hint (it's always the same order in every editor session):

```
"Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture"
```

image

I'd like the original order to be preserved.

**Comment by KoBeWi** [comment]
Seems like HashSet does not preserve order when elements are erased 🤔
I updated the branch to fix it. It's a bit more complex and slower, but it should be fine.

**Comment by Calinou** [comment]
> Seems like HashSet does not preserve order when elements are erased 🤔 I updated the branch to fix it. It's a bit more complex and slower, but it should be fine.

Can you link to the branch in question? I can't find it on your fork.

**Comment by Calinou** [comment]
> Right, the force push invalidated previous commit. Here's the branch: [KoBeWi/godot@`%F0%9F%9B%91No_Resource_allowed`](https://github.com/KoBeWi/godot/tree/%F0%9F%9B%91No_Resource_allowed?rgh-link-date=2024-03-15T17%3A07%3A33Z)

It works, thanks a lot! I've added you as a co-author :slightly_smiling_face:

File: doc/classes/ViewportTexture.xml [hunk 11]
```diff
@@ -7,6 +7,7 @@
 		Provides the content of a [Viewport] as a dynamic [Texture2D]. This can be used to mix controls, 2D game objects, and 3D game objects in the same scene.
 		To create a [ViewportTexture] in code, use the [method Viewport.get_texture] method on the target viewport.
 		[b]Note:[/b] A [ViewportTexture] is always local to its scene (see [member Resource.resource_local_to_scene]). If the scene root is not ready, it may return incorrect data (see [signal Node.ready]).
+		[b]Note:[/b] Some nodes such as [Decal], [Light3D], and [PointLight2D] do not support using [ViewportTexture] directly. To use texture data from a [ViewportTexture] in these nodes, you need to create an [ImageTexture] by calling [method Texture2D.get_image] on the [ViewportTexture]. This conversion is a slow operation, so it should not be performed every frame.
```
Comment (KoBeWi) [inline doc/classes/ViewportTexture.xml:10]: `get_image()` returns Image not ImageTexture, so this is a bit misleading.

File: scene/2d/light_2d.cpp [hunk 12]
```diff
@@ -30,6 +30,18 @@
...
+#include "scene/main/viewport.h"
+
+#ifdef DEBUG_ENABLED
+#include "scene/resources/animated_texture.h"
+#include "scene/resources/atlas_texture.h"
+#include "scene/resources/camera_texture.h"
+#include "scene/resources/mesh_texture.h"
+#include "scene/resources/texture.h"
+#include "scene/resources/texture_rd.h"
+#endif
```
Comment (KoBeWi) [inline scene/2d/light_2d.cpp:43]: You could avoid these includes by using `is_class()`.

File: scene/3d/decal.cpp [hunk 13]
```diff
@@ -225,10 +251,11 @@ void Decal::_bind_methods() {
 	ADD_PROPERTY(PropertyInfo(Variant::VECTOR3, "size", PROPERTY_HINT_RANGE, "0,1024,0.001,or_greater,suffix:m"), "set_size", "get_size");
 
 	ADD_GROUP("Textures", "texture_");
-	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "texture_albedo", PROPERTY_HINT_RESOURCE_TYPE, "Texture2D"), "set_texture", "get_texture", TEXTURE_ALBEDO);
-	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "texture_normal", PROPERTY_HINT_RESOURCE_TYPE, "Texture2D"), "set_texture", "get_texture", TEXTURE_NORMAL);
-	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "texture_orm", PROPERTY_HINT_RESOURCE_TYPE, "Texture2D"), "set_texture", "get_texture", TEXTURE_ORM);
-	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "texture_emission", PROPERTY_HINT_RESOURCE_TYPE, "Texture2D"), "set_texture", "get_texture", TEXTURE_EMISSION);
+	// Only allow texture types that display correctly.
+	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "texture_albedo", PROPERTY_HINT_RESOURCE_TYPE, "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture"), "set_texture", "get_texture", TEXTURE_ALBEDO);
```
Comment (KoBeWi) [inline scene/3d/decal.cpp:255]: You could make a String variable and reuse it for all properties.
```suggestion
	const String texture_hint = "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture";
	ADD_PROPERTYI(PropertyInfo(Variant::OBJECT, "texture_albedo", PROPERTY_HINT_RESOURCE_TYPE, texture_hint), "set_texture", "get_texture", TEXTURE_ALBEDO);
```

File: scene/2d/light_2d.cpp [hunk 14]
```diff
@@ -30,6 +30,9 @@
 
 #include "light_2d.h"
 
+#include "scene/main/canvas_item.h"
+#include "scene/main/viewport.h"
```
Comment (KoBeWi) [inline scene/2d/light_2d.cpp:34]: Leftover?
Same in other files.

**Comment by clayjohn** [comment]
CC @dsnopek Can you confirm that godot-cpp ignores these property hints? (see https://github.com/godotengine/godot/pull/88349#issuecomment-1967456455)

**Comment by Calinou** [comment]
Rebased and tested again following **https://github.com/godotengine/godot/pull/84443,** it works as expected.

**Comment by akien-mga** [comment]
We still have the GDExtension compat issue to figure out, which is blocking this.

**Comment by dsnopek** [comment]
Sorry for missing all the pings on this one!

I can definitely say this won't have any effect on godot-cpp: we don't use properties, because there isn't really an equivalent in C++ - we just use the getters and setters.

However, this may have an effect on bindings for languages that do have properties. That said, I would expect that in most cases, they'd use the return value type of the getter, rather than the type hint in order to determine which type should be used for the property. There's plenty of properties which list multiple types, which would potentially make using that tricky.

If any bindings actually _do_ use the property type, then the addition of the `-` types would probably break things. But I personally feel like this sort of change is acceptable in a new minor release - we've made other small breaking changes to the format of `extension_api.json` in previous minor releases. But I don't think this is something that should be cherry-picked to Godot 4.2 or earlier.

**Review by clayjohn — APPROVED** [review]
Approved from the perspective of allowable types. I can't comment on the compatibility stuff or the changes to object etc.

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected.

This now integrates https://github.com/godotengine/godot/pull/99959 by hiding non-manifold meshes in the CSGMesh3D `mesh` property.

File: misc/extension_api_validation/4.3-stable.expected [hunk 15]
```diff
@@ -205,3 +205,16 @@ GH-99481
...
+
+
+GH-88349
+--------
+Validate extension JSON: Error: Field 'classes/CSGMesh3D/properties/mesh': type changed value in new API, from "Mesh" to "Mesh,-PlaneMesh,-QuadMesh,-RibbonTrailMesh".
+Validate extension JSON: Error: Field 'classes/Decal/properties/texture_albedo': type changed value in new API, from "Texture2D" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
+Validate extension JSON: Error: Field 'classes/Decal/properties/texture_emission': type changed value in new API, from "Texture2D" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
+Validate extension JSON: Error: Field 'classes/Decal/properties/texture_normal': type changed value in new API, from "Texture2D" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
+Validate extension JSON: Error: Field 'classes/Decal/properties/texture_orm': type changed value in new API, from "Texture2D" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
```
Comment (akien-mga) [inline misc/extension_api_validation/4.3-stable.expected:216]:
```suggestion
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_albedo': type changed value in new API, from "Texture" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_emission': type changed value in new API, from "Texture" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_normal': type changed value in new API, from "Texture" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
Validate extension JSON: Error: Field 'classes/Decal/properties/texture_orm': type changed value in new API, from "Texture" to "Texture2D,-AnimatedTexture,-AtlasTexture,-CameraTexture,-CanvasTexture,-MeshTexture,-Texture2DRD,-ViewportTexture".
```

File: scene/2d/light_2d.cpp (hunk 1 above)
Comment (akien-mga) [reply scene/2d/light_2d.cpp]: Honestly I'm not sure I like this syntax to exclude unsupported types. We're excluding as many times as we'd have to explicitly include using the usual syntax.

And I think future proofing the addition of new types is not a good idea, as we don't know whether those new types would be supported. So it's better to state explicitly what we know we support. This would also make it easier possibly in the future to actually parse this hint and provide this information automatically in the class reference for example.

**Comment by akien-mga** [comment]
Reposting [my comment](https://github.com/godotengine/godot/pull/88349#discussion_r1881790411) from the old thread above for visibility, as IMO that's still a blocker for doing these otherwise relatively straightforward changes:

Honestly I'm not sure I like this syntax to exclude unsupported types. We're excluding as many times as we'd have to explicitly include using the usual syntax.

And I think future proofing the addition of new types is not a good idea, as we don't know whether those new types would be supported. So it's better to state explicitly what we know we support. This would also make it easier possibly in the future to actually parse this hint and provide this information automatically in the class reference for example.

**Comment by akien-mga** [comment]
I amended the PR to finally fix the extension validation issue (same issue as in #90993, previous changes done in another stable version of Godot conflict with new changes to the same API, and the workaround is to list both in the current `4.3.stable.expected` file).

I still have concerns about the new syntax in cases like Texture2D where we're excluding 7 types explicitly to keep 10, where we might want to just list the 10 types we know we support.

But let's not block it further, for other cases like CSGMesh it makes some sense (excluding 3 to keep 12).

**Comment by akien-mga** [comment]
Also added PointMesh to the list of primitives not supported by CSGMesh3D, as points are (I suppose?) non manifold.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
