### PR TITLE
GDScript: Prevent constructing and inheriting engine singletons

### LINKED ISSUE #80728: Misleading error message when attempting to create an instance of a singleton
### Godot version

0511f9d9a7d56c742d87fafdcea8785d40ad14b3 4.2.dev (current master as of writing)

### System information

macOS 13.4.1 (this issue affects all systems)

### Issue description

When trying to construct a built-in singleton (ex: `DisplayServer.new()`), this error message is misleading:

Screenshot 2023-08-17 at 11 30 46 AM

The error message says it's abstract, which seems like it should indicate that you need to use a derived class. However, this is a singleton, and you are meant to use its methods directly. Instead of the current error text, it should say something about how it's a singleton and you should use its methods directly.

### Steps to reproduce

Write `DisplayServer.new()` in the script editor.

### Minimal reproduction project

Since it's one line I am not going to bother making a MRP.

### LINKED ISSUE #82081: Empty parser error when defining a custom class extending Time
### Godot version

v4.1.1.stable.flathub [bd6af8e0e]

### System information

Godot v4.1.1.stable (bd6af8e0e) - Freedesktop SDK 23.08 (Flatpak runtime) - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

### Issue description

Creating a custom class extending `Time`, and assigning it or instantiating it with `new()` at runtime crashes Godot with an empty parser error, and the source error:
```
E 0:00:00:0165   _populate_class_members: Condition "p_script->native.is_null()" is true. Returning: ERR_BUG
  <C++ Source>   modules/gdscript/gdscript_compiler.cpp:2562 @ _populate_class_members()
```
I tried to extend other classes, such as `Object`, `Resource`, `Timer`, `Node`, but none of which cause this issue. Since no other classes inherit `Time`, I cannot try with those.
## Images
image
image

### Steps to reproduce

Script a (only saved in file system):
```gdscript
extends Time
class_name c
```
Script b (attached to scene or autoload):
````gdscript
extends Node2D
var v = c
````

### Minimal reproduction project

[godot.zip](https://github.com/godotengine/godot/files/12694015/godot.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #80728.
* Fixes #82081.

You cannot create a new instance of an engine singleton.

https://github.com/godotengine/godot/blob/fe5b1c8d49313d63fbe91cb7cdf463e10fb86afa/core/os/time.cpp#L446-L449

### CODE REVIEW

**Review by ryanabx — APPROVED** [review]
LGTM! Thanks Dalexeev as always!

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -459,6 +459,10 @@ Error GDScriptAnalyzer::resolve_class_inheritance(GDScriptParser::ClassNode *p_c
 				}
 				base = info_parser->get_parser()->head->get_datatype();
 			} else if (class_exists(name)) {
+				if (Engine::get_singleton()->has_singleton(name)) {
+					push_error(vformat(R"(Cannot inherit native class "%s" because it is engine singleton.)", name), id);
```
Comment (akien-mga) [inline modules/gdscript/gdscript_analyzer.cpp:463]:
```suggestion
					push_error(vformat(R"(Cannot inherit native class "%s" because it is an engine singleton.)", name), id);
```

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -3203,6 +3207,12 @@ void GDScriptAnalyzer::reduce_call(GDScriptParser::CallNode *p_call, bool p_is_a
 
 	bool is_constructor = (base_type.is_meta_type || (p_call->callee && p_call->callee->type == GDScriptParser::Node::IDENTIFIER)) && p_call->function_name == SNAME("new");
 
+	if (is_constructor && Engine::get_singleton()->has_singleton(base_type.native_type)) {
+		push_error(vformat(R"(Cannot construct native class "%s" because it is engine singleton.)", base_type.native_type), p_call);
```
Comment (akien-mga) [inline modules/gdscript/gdscript_analyzer.cpp:3211]:
```suggestion
		push_error(vformat(R"(Cannot construct native class "%s" because it is an engine singleton.)", base_type.native_type), p_call);
```

**Review by akien-mga — APPROVED** [review]

**Review by adamscott — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
