### PR TITLE
Fix grid snapping for box shape gizmos

### LINKED ISSUE #81916: New 3D scaling gizmos not snapping to grid correctly
### Godot version

v4.2.dev5.official

### System information

Godot v4.2.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 30.0.15.1179) - AMD Ryzen 3 1200 Quad-Core Processor (4 Threads)

### Issue description

When using the new 3D scaling gizmos and grid snapping, they seem to sometimes snap correctly, but occasionally, it will start moving in smaller increments until the size is completely off the grid. I also think that there are some problems due to the fact that the transform gizmo is in the centre of these types of nodes, so even if the edges of the node are snapped, the position will almost never be snapped. Maybe adding an option to switch between a centered transform gizmo, and a corner transform gizmo could solve some problems.

Screenshot 2023-09-19 130445

### Steps to reproduce

Create a node that uses these gizmos, and with grid snapping on, keep moving the handles until it goes off the grid. You have to keep letting go of it, and click/dragging it again. When you initially grab the handle, and it snaps, it will continue to snap, it's when you click it again that it sometimes goes off.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by dervus**
Fixes #81916 

I've rewritten Gizmo3DHelper logic for its box "extrusion" mode. In this version it applies snapping directly to box size and then adjusts box position by ensuring that opposite end of the box doesn't move as result of the operation. This way box size doesn't deviate from the snap grid.

Position (origin) adjustment logic is thus:
1. Calculate initial offsets of box sides on selected axis.
2. Adjust offset of the side we're extruding to accommodate new box size.
3. Adjust box position to be in the middle between unmoved side and extruded side.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Shouldn't the gizmos get snapped to the grid?

https://github.com/godotengine/godot/assets/2223172/db460437-f5aa-407d-8517-fc333e5c1a98

They move in correct increments, but not sure if this is intended.

**Comment by dervus** [comment]
I'm quite new to Godot, so I'm not sure myself what if it's intended or not, but AFAIK all translation ops with grid snapping just force target property to change in integer increments (0.1 increments if shifted). I think that makes sense for box sizing, though because when I'm working with several CSG shapes I find it handy if they all snap like this, so they can fit even then their origin is not on grid.

**Comment by dervus** [comment]
On the other hand, I think it would be quite simple to make it always snap to visual grid. This would cause size property to deviate from being integer, but it always could be corrected by pulling the other side of the box. However, this would be inconsistent with translation gizmo behavior, and also would be a change from original behavior of this specific gizmo, so I assume even if it is desired, it shouldn't be a part of this PR?

File: editor/plugins/gizmos/gizmo_3d_helper.cpp [hunk 1]
```diff
@@ -77,36 +77,46 @@ String Gizmo3DHelper::box_get_handle_name(int p_id) const {
...
-		Geometry3D::get_closest_points_between_segments(Vector3(), axis * 4096 * -sign, p_segment[0], p_segment[1], ra, rb);
-	}
+	Vector3 axis_segment[2] = { Vector3(), Vector3() };
+	axis_segment[0][axis] = 4096.0;
+	axis_segment[1][axis] = -4096.0;
+	Vector3 ra, rb;
+	Geometry3D::get_closest_points_between_segments(axis_segment[0], axis_segment[1], p_segment[0], p_segment[1], ra, rb);
 
-	float d = ra[p_id / 2] * sign;
+	// Calculate new size
```
Comment (KoBeWi) [inline editor/plugins/gizmos/gizmo_3d_helper.cpp:93]:
```suggestion
	// Calculate new size.
```

File: editor/plugins/gizmos/gizmo_3d_helper.cpp [hunk 2]
```diff
@@ -77,36 +77,46 @@ String Gizmo3DHelper::box_get_handle_name(int p_id) const {
...
+	r_box_size = initial_size;
+	if (Input::get_singleton()->is_key_pressed(Key::ALT)) {
+		r_box_size[axis] = ra[axis] * sign * 2;
+	} else {
+		r_box_size[axis] = sign > 0 ? ra[axis] - neg_end : -(ra[axis] - pos_end);
+	}
 
-	Vector3 he = r_box_size;
-	he[p_id / 2] = d * 2;
+	// Snap to grid
```
Comment (KoBeWi) [inline editor/plugins/gizmos/gizmo_3d_helper.cpp:101]:
```suggestion
	// Snap to grid.
```

File: editor/plugins/gizmos/gizmo_3d_helper.cpp [hunk 3]
```diff
@@ -77,36 +77,46 @@ String Gizmo3DHelper::box_get_handle_name(int p_id) const {
...
+	Vector3 ra, rb;
+	Geometry3D::get_closest_points_between_segments(axis_segment[0], axis_segment[1], p_segment[0], p_segment[1], ra, rb);
 
-	float d = ra[p_id / 2] * sign;
+	// Calculate new size
+	r_box_size = initial_size;
+	if (Input::get_singleton()->is_key_pressed(Key::ALT)) {
+		r_box_size[axis] = ra[axis] * sign * 2;
+	} else {
+		r_box_size[axis] = sign > 0 ? ra[axis] - neg_end : -(ra[axis] - pos_end);
```
Comment (KoBeWi) [inline editor/plugins/gizmos/gizmo_3d_helper.cpp:98]: This can be reduced to
```suggestion
		r_box_size[axis] = sign > 0 ? ra[axis] - neg_end : pos_end - ra[axis];
```

File: editor/plugins/gizmos/gizmo_3d_helper.cpp [hunk 4]
```diff
@@ -77,36 +77,46 @@ String Gizmo3DHelper::box_get_handle_name(int p_id) const {
...
-	Vector3 he = r_box_size;
-	he[p_id / 2] = d * 2;
+	// Snap to grid
 	if (Node3DEditor::get_singleton()->is_snap_enabled()) {
-		he[p_id / 2] = Math::snapped(he[p_id / 2], Node3DEditor::get_singleton()->get_translate_snap());
+		r_box_size[axis] = Math::snapped(r_box_size[axis], Node3DEditor::get_singleton()->get_translate_snap());
 	}
+	r_box_size[axis] = MAX(r_box_size[axis], 0.001);
 
+	// Adjust position
```
Comment (KoBeWi) [inline editor/plugins/gizmos/gizmo_3d_helper.cpp:107]:
```suggestion
	// Adjust position.
```

**Review by KoBeWi — APPROVED** [review]
Seems fine.
CC @Calinou You might want to test the fixed behavior.

File: editor/plugins/gizmos/gizmo_3d_helper.cpp [hunk 5]
```diff
@@ -77,36 +77,46 @@ String Gizmo3DHelper::box_get_handle_name(int p_id) const {
...
-		Vector3 pos = initial_transform.affine_inverse().xform(initial_transform.get_origin());
-		pos += (r_box_size - initial_size) * 0.5 * sign;
-		r_box_position = initial_transform.xform(pos);
+		if (sign > 0) {
+			pos_end = neg_end + r_box_size[axis];
+		} else {
+			neg_end = pos_end - r_box_size[axis];
+		}
+
+		Vector3 offset = Vector3();
```
Comment (akien-mga) [inline editor/plugins/gizmos/gizmo_3d_helper.cpp:117]: Vectors are default initialized to zero already.
```suggestion
		Vector3 offset;
```

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by dervus** [comment]
Thanks for merging!

**Comment by JamesC01** [comment]
Thanks so much, just tested it and it seems to work well. This will make grey-boxing levels so much easier!
