### PR TITLE
Inherit parent method return types for untyped overrides

### LINKED ISSUE #90694: GDScript overloaded functions can override return type
### Tested versions

Reproducible in 4.2.1 to 4.2.2-rc3.

### System information

Godot v4.2.1.stable - Debian GNU/Linux 12 (bookworm) 12 - Wayland - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 Threads)

### Issue description

Overloaded functions can return a different type than the original function's declaration. Additionally, this can force non-nullable typed variables to be null, causing interpreter bugs (see the MRP).

### Steps to reproduce

Create a class `a.gd`:

```gdscript
extends RefCounted
class_name A

func f() -> bool:
	return true
```

Create another class `b.gd`:
```gdscript
extends A
class_name B

func f():
	pass
```

Now note the type inconsistency when treating a `B` as an `A`:

```gdscript
var b: A
b = B.new()
var r := b.f() # This variable is strongly-typed as a bool
print(b.f()) # Outputs <null>, which should be impossible!
```

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/godotengine/godot/files/14977810/mrp.zip)

### PR DESCRIPTION
**Pull request by Hrothdel**
- Fixes #111536
- *Bugsquad edit:* Fixes #90694

When overriding a typed method with an untyped one, the type of the parent method propagates implicitly. This allows the analyzer to check the compatibility of the return type to maintain covariance. Some unit tests needed small changes for this to not break them.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -2576,7 +2578,11 @@ void GDScriptAnalyzer::resolve_return(GDScriptParser::ReturnNode *p_return) {
 		} else if (!is_type_compatible(expected_type, result, true, p_return)) {
 			mark_node_unsafe(p_return);
 			if (!is_type_compatible(result, expected_type)) {
-				push_error(vformat(R"(Cannot return value of type "%s" because the function return type is "%s".)", result.to_string(), expected_type.to_string()), p_return);
+				if (parser->current_function->return_type != nullptr) {
+					push_error(vformat(R"(Cannot return value of type "%s" because the function return type is "%s".)", result.to_string(), expected_type.to_string()), p_return);
+				} else {
+					push_error(vformat(R"(Cannot return value of type "%s" because the function return type is "%s" (inherited).)", result.to_string(), expected_type.to_string()), p_return);
+				}
```
Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp]: I'd suggest inverting the condition and swapping the branches to get rid of the negative check. The same above, lines 1878-1895.

Comment (dalexeev) [inline modules/gdscript/gdscript_analyzer.cpp]: I don't mind this clarification, but please note that the checks above in this method and other helper methods like `update_const_expression_builtin_type()` can prevent or obscure your error. This is what happens with void functions and literals as return values:



This increases the already high inconsistency of error messages. I'm just saying that making error messages clear and useful is a bit more difficult than it seems. The primary focus is fixing the bug and engine crash, improving the error messages can be postponed to subsequent PRs.

**Review by dalexeev — COMMENTED** [review]
Looks good to me. :+1: Just need to add some tests and improve the code style.

<details>
<summary><code>analyzer/features</code> test</summary>

```gdscript
class A:
    func return_float() -> float: return 1.0
    func return_int_as_float(_x: int) -> float: return 1.0
    func return_variant_as_float(_x: Variant) -> float: return 1.0
    func return_float_array() -> Array[float]: return [1.0]
    func return_float_dict() -> Dictionary[float, float]: return {1.0: 1.0}

class B extends A:
    func return_float(): return 2
    func return_int_as_float(x: int): return x
    func return_variant_as_float(x: Variant): return x
    func return_float_array(): return [2]
    func return_float_dict(): return {2: 2}

func output(value: Variant) -> void:
    print(var_to_str(value).replace("\n", ""))

func test():
    var b := B.new()
    output(b.return_float())
    output(b.return_int_as_float(2))
    output(b.return_variant_as_float(2))
    output(b.return_float_array())
    output(b.return_float_dict())
```

</details>

<details>
<summary><code>analyzer/errors</code> test</summary>

```gdscript
class A:
    func return_void() -> void: pass
    func return_int() -> int: return 123
    func return_node(_resource: Resource) -> Node: return null

class B extends A:
    func return_void(): return 1
    func return_int(): return "abc"
    func return_node(resource: Resource): return resource

func test():
    pass
```

</details>

<details>
<summary><code>runtime/errors</code> test</summary>

```gdscript
class A:
    func return_int(_variant: Variant) -> int: return 123
    func return_int_array(_variant: Variant) -> Array[int]: return [1]
    func return_int_dict(_variant: Variant) -> Dictionary[int, int]: return {1: 1}
    func return_node(_variant: Variant) -> Node: return null

class B extends A:
    func return_int(variant: Variant): return variant
    func return_int_array(variant: Variant): return variant
    func return_int_dict(variant: Variant): return variant
    func return_node(variant: Variant): return variant

func output(value: Variant) -> void:
    print(var_to_str(value).replace("\n", ""))

func test():
    var b := B.new()

    output(b.return_int("abc"))
    output(b.return_int_array("abc"))
    output(b.return_int_dict("abc"))
    output(b.return_node("abc"))
```

</details>

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (Hrothdel) [reply modules/gdscript/gdscript_analyzer.cpp]: I didn't think of that, fair point. Should I just get rid of the clarification?

Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp]: Yes, I think it's better to remove the clarification for now. Because bringing error messages into a consistent format is more complex and doesn't directly relate to the scope of this PR (fixing the crash). But subsequent PR would be very welcome.

File: modules/gdscript/tests/scripts/analyzer/errors/untyped_override_incompatible_type.gd [hunk 2]
```diff
@@ -0,0 +1,12 @@
+class A:
+	func return_void() -> void: pass
+	func return_int() -> int: return 123
+	func return_node(_resource: Resource) -> Node: return null
+
+class B extends A:
+	func return_void(): return 1
+	func return_int(): return "abc"
+	func return_node(resource: Resource): return resource
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/errors/untyped_override_incompatible_type.gd:10]: Please, add this case:

```gdscript
class A:
	func return_variant() -> Variant: return null
	# ...

class B extends A:
	func return_variant(): pass
	# ...
```

File: modules/gdscript/tests/scripts/analyzer/errors/untyped_override_return_incompatible_type.gd
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/errors/untyped_override_return_incompatible_type.gd:1]: It would be nice to rename this file to `untyped_override_return_incompatible_type.gd` so that all 3 tests start with `untyped_override_return_`.

File: modules/gdscript/tests/scripts/analyzer/features/untyped_override_return_compatible_type.gd
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/features/untyped_override_return_compatible_type.gd:1]: It would be nice to rename this file to `untyped_override_return_compatible_type.gd` so that all 3 tests start with `untyped_override_return_`.

File: modules/gdscript/tests/scripts/analyzer/features/untyped_overrides_return_compatible_types.gd [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+	func return_variant_as_float(x: Variant): return x
+	func return_float_array(): return [2]
+	func return_float_dict(): return {2: 2}
+
+func output(value: Variant) -> void:
+	print(var_to_str(value).replace("\n", ""))
+
+func test():
+	var b := B.new()
+	output(b.return_float())
```
Comment (dalexeev) [inline modules/gdscript/tests/scripts/analyzer/features/untyped_overrides_return_compatible_types.gd:21]:
```suggestion
	var b := B.new()

	output(b.return_float())
```

**Review by dalexeev — APPROVED** [review]
Great job, thanks! :+1: A small but very important fix.

I noticed a bug in the compiler/codegen, but it's easily separable from this fix, so I'll make a PR later.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉
