### PR TITLE
Fix forwarding of CLI arguments taking an option

### LINKED ISSUE #64845: Passing --audio-driver from project manager to project fails
### Godot version

3.x current after #64375
May also be present in master

### System information

Linux Mint 20

### Issue description

Just been testing out #64375 and unfortunately there seems to be a bug. @RandomShaper 

Call godot with `godot.exe --audio-driver Dummy` to launch the project manager, then open a project and you get:
```
Unknown audio driver '--path', aborting.
Valid options are 'PulseAudio', 'ALSA' and 'Dummy'.
```
Is is possibly only passing the first string (i.e. `--audio-driver`) and not `Dummy`? :thinking: 

### Steps to reproduce

As above.

### Minimal reproduction project

N/A.

### PR DESCRIPTION
**Pull request by RandomShaper**
@lawnjelly, some testing would be awesome.

Fixes #64845.

### CODE REVIEW

File: main/main.cpp [hunk 1]
```diff
@@ -725,11 +725,16 @@ Error Main::setup(const char *execpath, int argc, char *argv[], bool p_second_ph
...
+		if (I->get() == "--single-window") {
+			forwardable_cli_arguments[CLI_SCOPE_TOOL].push_back(I->get());
+		}
+		if (I->get() == "--audio-driver" ||
 				I->get() == "--display-driver" ||
 				I->get() == "--rendering-driver") {
-			forwardable_cli_arguments[CLI_SCOPE_TOOL].push_back(I->get());
+			if (I->next()) {
+				forwardable_cli_arguments[CLI_SCOPE_TOOL].push_back(I->get());
+				forwardable_cli_arguments[CLI_SCOPE_TOOL].push_back(I->next()->get());
```
Comment (akien-mga) [inline main/main.cpp:736]: Does the `TOOL` scope include running the project from the editor too? As if forcing a rendering driver that overrides the one from project settings for the editor, it should likely also be used when running.

**Comment by lawnjelly** [comment]
Looks good although I haven't currently got a moment for testing. :+1: 
(Am assuming you tried it with `--audio-driver Dummy` as an example).

File: main/main.cpp (hunk 1 above)
Comment (RandomShaper) [reply main/main.cpp:736]: It's only for the project manager and editor restarts. I added the concept of scopes precisely to avoid such arguments from crossing the editor-project boundary. My only concern is the potential of confusion when a user switches drivers in project settings, but they don't get applied because of the original CLI argunments being "stuck". That said, I don't really have a strong opinion on it. Just did what I considered sensible.

In any case, the PR where this was introduced already had a decision on this and this one is only meant to fix it. If we finally decide it's better that all the arguments make it to the running game, that'd be matter for a subsequent PR.

**Comment by RandomShaper** [comment]
> Looks good although I haven't currently got a moment for testing. 👍 (Am assuming you tried it with `--audio-driver Dummy` as an example).

You're correct.

I've tested it a bit more myself now and I'm quite confident this works as intended now.

File: main/main.cpp (hunk 1 above)
Comment (lawnjelly) [reply main/main.cpp:736]: Am tending to be in agreement with @RandomShaper , although there are some cases for passing arguments to the running project in the editor, it is a bit of a bag of worms and might be better in a separate PR (if we decided to do it).

For running projects from the editor, maybe we could have a command line section in the project settings, or some checkboxes / toggles for the editor runs? :thinking:

**Review by lawnjelly — APPROVED** [review]
Thumbs up from me. (pending what @akien-mga thinks about the passing to running projects).

**Review by akien-mga — APPROVED** [review]
Looks correct.

**Comment by akien-mga** [comment]
Thanks!

**Comment by lawnjelly** [comment]
Reminder this needs a version or cherry picking for 3.x. :+1:

**Comment by akien-mga** [comment]
It has the label, so I'll get to it when I have time :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.
