### PR TITLE
Defer updating the animations Tree in SpriteFramesEditor to avoid crashes

### LINKED ISSUE #79149: Switch animation while renaming other animation in SpriteFrames crash
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

6.1.31-2-MANJARO

### Issue description

In the SpriteFrames in the bottom panel, while editing animation name, Godot crashes (freezes for a short moment then quits) if you switch to another animation (to rename) without entering enter to the currently being-edited (while it has text focus) animation name. 

### Steps to reproduce

1. Create SpriteFrames for AnimatedSprite2D node and create atleast two animations.
2. Try to rename one. While editing that one, don't press enter and switch to rename the other. (while the previous still has focus). Make sure to add or delete atleast one new letter while editing
3. It crashes from here

### Minimal reproduction project

[SpriteFrameNameCrash.tar.gz](https://github.com/godotengine/godot/files/11981249/SpriteFrameNameCrash.tar.gz)

### PR DESCRIPTION
**Pull request by Rindbee**
Previously, clicking the LMB while renaming an animation could cause `SpriteFramesEditor::_update_library(false)` to be called during `Tree::propagate_mouse_event()`. This may cause a crash.

https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/scene/gui/tree.cpp#L3783-L3784

https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/scene/gui/tree.cpp#L4290-L4291

https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/editor/plugins/sprite_frames_editor_plugin.cpp#L1222-L1223

We can defer updates to the editor interface to avoid calling `Tree::create_item()` at the wrong time.

Fix #79149.

### CODE REVIEW

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 1]
```diff
@@ -1187,6 +1188,13 @@ void SpriteFramesEditor::_zoom_reset() {
 }
 
 void SpriteFramesEditor::_update_library(bool p_skip_selector) {
+	if (!p_skip_selector) {
+		animations_dirty = true;
+	}
+	callable_mp(this, &SpriteFramesEditor::_update_library_impl).call_deferred();
```
Comment (KoBeWi) [inline editor/plugins/sprite_frames_editor_plugin.cpp:1194]: Why did you make every update_library call deferred if the problem happens only in one case?

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 2]
```diff
@@ -957,6 +957,7 @@ void SpriteFramesEditor::_animation_name_edited() {
 		counter++;
 		name = new_name + "_" + itos(counter);
 	}
+	edited->set_text(0, name);
```
Comment (KoBeWi) [inline editor/plugins/sprite_frames_editor_plugin.cpp:960]: If you do it unconditionally anyway, it can be moved before `while` loop and the other `set_text()` can be removed.

Comment (Rindbee) [reply editor/plugins/sprite_frames_editor_plugin.cpp:960]: Here, `name` is the new name. The case where the name has not changed has been returned early.

File: editor/plugins/sprite_frames_editor_plugin.cpp (hunk 1 above)
Comment (Rindbee) [reply editor/plugins/sprite_frames_editor_plugin.cpp:1194]: The code here is indeed problematic.

`_update_library()` seems to just read data from `frames` to update the GUI, calling it multiple times in a single frame can be reduced to just calling it once.

**Comment by Rindbee** [comment]
A mechanism similar to `update_tree()` in `EditorInspector` is used.

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 3]
```diff
@@ -589,11 +589,23 @@ void SpriteFramesEditor::_notification(int p_what) {
...
 
 		case NOTIFICATION_EXIT_TREE: {
 			get_tree()->disconnect("node_removed", callable_mp(this, &SpriteFramesEditor::_node_removed));
 		} break;
+
+		case NOTIFICATION_VISIBILITY_CHANGED: {
+			set_process(is_visible_in_tree());
+		} break;
+
+		case NOTIFICATION_PROCESS: {
```
Comment (KoBeWi) [inline editor/plugins/sprite_frames_editor_plugin.cpp:603]: You don't need `NOTIFICATION_PROCESS` for queued updates.
Pseudocode:
```
bool update_queued = false

void queue_library_update()
	if update_queued
		return
	
	update_queued = true
	call_deferred(_update_library)

void _update_library()
	update_queued =false
```

**Comment by Rindbee** [comment]
Fix the edited animation not updating when undoing.

**Before:**

https://github.com/godotengine/godot/assets/30386067/27f784b5-e60c-4d7e-96b6-607bec30660d

**After:**

https://github.com/godotengine/godot/assets/30386067/08967417-2e0c-4ead-a604-258ca51b1ea5

File: editor/plugins/sprite_frames_editor_plugin.cpp [hunk 4]
```diff
@@ -1228,6 +1243,7 @@ void SpriteFramesEditor::_update_library(bool p_skip_selector) {
 		if (selected) {
 			animations->scroll_to_item(selected);
 		}
+		animations_dirty = false;
```
Comment (KoBeWi) [inline editor/plugins/sprite_frames_editor_plugin.cpp:1246]: This is checked only once, so it can be moved to the top right after `animations->clear();`, to avoid the other assign.

**Review by KoBeWi — APPROVED** [review]
I can't really reproduce the crash to test the fix, but the changes look fine.

**Comment by akien-mga** [comment]
Thanks!
