### PR TITLE
[TextEdit] Improve wrapped line indent handling.

### LINKED ISSUE #93794: TextEdit: Text not shown with too many tabs and `indent_wrapped_lines`
### Tested versions

Godot v4.3.beta (4ab8fb809)

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

- related https://github.com/godotengine/godot/pull/88546
- I found this while looking into https://github.com/godotengine/godot/issues/93762

If you have `indent_wrapped_lines` enabled and a line after many tabs, it doesn't get wrapped anymore. It tries to put the text after the indentation to match the first line, but there is too much and the text can't be shown. 
It should reset the indent count if there is too many.

image

### Steps to reproduce

1. Make sure word wrap and `indent_wrapped_lines` is on.
2. Have a script with text after many tabs or spaces so it goes out of view, like `																														 	#test`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/93794

### Before

All text is cut:

Screenshot 2025-02-07 at 09 35 21

### After

If possible, wrapped lines are aligned to the first wrapped line that is not all indent:
Screenshot 2025-02-07 at 08 12 35

Otherwise, it still should fill at least 40% of the width all the time (should it be a user adjustable value?):
Screenshot 2025-02-07 at 09 33 46

### CODE REVIEW

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -3529,6 +3541,32 @@ int TextEdit::get_line_height() const {
...
 }
 
+int TextEdit::_get_wrapped_indent_level(int p_line, int &r_first_wrap) const {
+	ERR_FAIL_INDEX_V(p_line, text.size(), 0);
+
+	const Vector<Vector2i> wr = text.get_line_wrap_ranges(p_line);
+	r_first_wrap = 0;
+
+	int tab_count = 0;
+	int whitespace_count = 0;
```
Comment (KoBeWi) [inline scene/gui/text_edit.cpp:3551]:
```suggestion
	int space_count = 0;
```
More accurate.

**Review by KoBeWi — APPROVED** [review]
Fixes the issue.

**Comment by Repiteo** [comment]
Thanks!
