### PR TITLE
Fix code editor scrolling experience on track pads

### LINKED ISSUE #28149: Script editor doesn't track scrolling via Touchpad smoothly (or at all when scrolling is slow)
**Godot version:**
3.1

**OS/device including version:**
macOS 10.13.6 (High Sierra)
MacBook Pro Retina (mid 2012)

**Issue description:**
Touchpad/trackpad two-finger scroll takes effort to scroll the text editor areas (script editor and the textual shader editor). All other views in Godot (including those that contain text, such as the FileSystem, Inspector, Node, and Scene tabs) all move very smoothly, instantly tracking the two-finger scroll on the touchpad. However, the script editor and the textual shader editor seem to wait for a certain amount of fast scroll before starting to scroll, which causes not only effort to get the scrolling going, but also causes these views to not scroll at all if the fingers are moved slowly. I can move my fingers from the top of the trackpad all the way to the bottom slowly without Godot scrolling the script a single line. Other views such as the Inspector track the finger movements immediately, even if the fingers are moved very slowly.

**Steps to reproduce:**
Try to scroll using multitouch on a MacBook touchpad/trackpad, using a slow motion of the fingers. Note that the script editor does not move at all unless you move your fingers fast, but then the scrolling is fast too.

P.S. This doesn't seem to be related to issue #11030, but issues #8953, #7884, and #7864 may be relevant, but they all treat smooth-scrolling as fixed, while there's clearly an issue with it in Godot 3.1.

### PR DESCRIPTION
**Pull request by Kurble**
Fixes #28149 

This PR fixes two closely related problems:
- Scrolling slowly in the code editor with a track pad would not do anything;
- Smooth scrolling would animate track pad scrolls, but they are already animated as the pixel deltas are provided on a frame-by-frame basis.

The first problem is caused by the step size that's set on the `VScrollBar`, any scroll event going through `TextEdit::_scroll_up` and `TextEdit::_scroll_down` got rounded down to an integer number of lines. Since scrolling on a track pad happens every frame, the individual deltas are relatively small, and they would be rounded down to zero unless you're scrolling quite fast. This is addressed differently for the smooth scrolling enabled and disabled case:
- When disabled the scrolling deltas are accumulated the same way they were already being accumulated for the smooth scrolling case, so when slow scrolling for long enough the step size threshold is reached;
- When smooth scrolling is enabled the step size is set to 0, allowing all fractional increments. 

The second problem becomes quickly apparent when the first problem is fixed: scroll delta's less than 1 line are applied immediately, while scroll delta's larger than 1 line are animated. This feels really snappy as long as the target scroll value is less than 1 line away from the current scroll value, only to suddenly change to a fixed speed when the delta becomes too big. This has been addressed by directly applying any scroll delta coming from `InputEventPanGesture` events, instead of allowing it to animate.

### CODE REVIEW

**Comment by Calinou** [comment]
Rounding scrollng to lines is probably not desired behavior nowadays, even with a mouse wheel. For example, VS Code doesn't round to lines when scrolling with the wheel, so I'd get rid of the behavior entirely 🙂

**Comment by Kurble** [comment]
Updated to get rid of line snapping.

**Comment by Kurble** [comment]
Some tests were failing after getting rid of line snapping, because scrolling to a caret position can then result in fractional scroll values. That actually feels really weird, so I fixed it by rounding the scroll values in `set_line_as_last_visible`.

**Comment by KeatsPeeks** [comment]
Any update on this one ? Without it the editor really feels clunky with a touchpad.

**Comment by Kurble** [comment]
@KeatsPeeks Currently just waiting for review I guess, PR should be good to go.

**Comment by akien-mga** [comment]
Looks fine from the input team's perspective, but we'd like some assessment from those more familiar with TextEdit or the expected behavior of trackpads.

**Comment by BoydWiglaf** [comment]
@Kurble I created an new pull request #82260  with you changes in it with the updates from the godot master branch.  It seems your this PR has conflicts.  If you have the time to resolve the conflicts I think this PR could get pulled in soon.  However, If not I have the new PR with your changes in it.   I hope Im not stepping on any toes.  I am new to doing these things and really would love to see this update pulled into Godot.

**Comment by AThousandShips** [comment]
Can you rebase your PR and fix the merge conflicts

File: scene/gui/text_edit.cpp [hunk 1]
```diff
@@ -5431,7 +5431,7 @@ void TextEdit::set_line_as_last_visible(int p_line, int p_wrap_index) {
 		set_v_scroll(0);
 		return;
 	}
-	set_v_scroll(get_scroll_pos_for_line(first_line, next_line.y) + _get_visible_lines_offset());
+	set_v_scroll(round(get_scroll_pos_for_line(first_line, next_line.y) + _get_visible_lines_offset()));
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp:5434]:
```suggestion
	set_v_scroll(Math::round(get_scroll_pos_for_line(first_line, next_line.y) + _get_visible_lines_offset()));
```

Comment (Kurble) [reply scene/gui/text_edit.cpp]: Alright, fair enough

**Comment by Kurble** [comment]
Rebased on master and now the tests even pass without any changes!

**Comment by BoydWiglaf** [comment]
@Calinou @Paulb23 @bruvzg @godotengine/input @godotengine/gui-nodes @godotengine/tests
What else is needed on this PR?

**Comment by Calinou** [comment]
I suggest [testing](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) the pull request locally and make sure it works on your end. (I don't have a macOS device with a trackpad to test this PR.)

File: scene/gui/text_edit.cpp [hunk 2]
```diff
@@ -7499,7 +7494,7 @@ void TextEdit::_scroll_down(real_t p_delta) {
 		if (target_v_scroll > max_v_scroll) {
 			target_v_scroll = max_v_scroll;
 		}
-		if (Math::abs(target_v_scroll - v_scroll->get_value()) < 1.0) {
+		if (Math::abs(target_v_scroll - v_scroll->get_value()) < 1.0 || !p_animate) {
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp:7497]:
```suggestion
		if (!p_animate || Math::abs(target_v_scroll - v_scroll->get_value()) < 1.0) {
```
Put cheaper condition first

File: scene/gui/text_edit.cpp [hunk 3]
```diff
@@ -7471,7 +7466,7 @@ void TextEdit::_scroll_up(real_t p_delta) {
 		if (target_v_scroll <= 0) {
 			target_v_scroll = 0;
 		}
-		if (Math::abs(target_v_scroll - v_scroll->get_value()) < 1.0) {
+		if (Math::abs(target_v_scroll - v_scroll->get_value()) < 1.0 || !p_animate) {
```
Comment (AThousandShips) [inline scene/gui/text_edit.cpp:7469]:
```suggestion
		if (!p_animate || Math::abs(target_v_scroll - v_scroll->get_value()) < 1.0) {
```

**Comment by ikkerens** [comment]
Built this from source on my 14" Macbook Pro with M1 Max 24c, 64gb, 1tb ssd and found no issues.
Overall this change makes the whole experience a lot more refined and far less sluggish than the currently available official release.

I hope this gets merged soon!

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` a574c0296b38d5f786f249b12e6251e562c528cc) on mouse wheel. It works as expected in the sense that I can't notice any regressions.

Note that this PR doesn't resolve https://github.com/godotengine/godot/issues/28385.

**Review by deralmas — APPROVED** [review]
Tested again on top of the Wayland branch (#57025), which implements `InputEventPanGesture`, and it still works great as last time!

Other than that I'll reiterate that the patch looks really nice and concise, great job!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
