### PR TITLE
GDScript: Improve evaluation of constant expressions with arrays/dictionaries

### LINKED ISSUE #81256: Can't format `const` string with `const` values
### Godot version

4.1.1.stable

### System information

Arch Linux

### Issue description

In my project, I used to define my version like so:
```gdscript
const version_major := 0
const version_minor := 2
const version_patch := 1
const version_extra := "beta"

const version_str := "%d.%d.%d-%s" % [version_major, version_minor, version_patch, version_extra]
```

This worked for Godot 3, but in Godot 4 it no longer lets me do this, although it should still be a const expression:
image

A few other experiments around this:
```gdscript
# Not allowed
const version_extra := "%d.%d" % [version_major, version_minor]
const version_extra := str(version_major)

# Allowed
const version_extra := "%d" % version_major
```

### Steps to reproduce

- Define constants
- Define a constant string, and use string formatting with multiple const values on it

### Minimal reproduction project

N/A

### LINKED ISSUE #95568: Unable to load Array of custom classes directly from load/preload to statically typed variable
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]
- Not present in v4.2.stable.official [46dc27791]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

In 4.2 and earlier, one could load arrays of custom object types directly from a loaded resource file in one line. E.g. ```var myvar: Array[SomeResource] = preload("somefile.tres").someVariable```. Now, it gives the following error message: "Cannot assign a value of type Array[res://SomeResource.gd] to variable "myvar" with specified type Array[SomeResource]." 

No error is brought up and code runs as usual if ```myvar``` is not statically typed. The error is also avoided if split up into two lines, e.g. 
```var myvar = preload("somefile.tres")
var yourvar: Array[SomeResource] = myvar.someVariable

### Steps to reproduce

In the minimum reproduction project, the ```node.gd``` file will display the error. It can be reproduced by 

1. Creating a custom class
2. Creating a resource with an array of that class as a variable
3. Trying to load that data into a statically typed variable.

### Minimal reproduction project (MRP)

[Bug-Reporting.zip](https://github.com/user-attachments/files/16627056/Bug-Reporting.zip)

### LINKED ISSUE #95851: Resources with typed arrays of resources show up as the path to the resource instead of the class name in editor causing an error that the type does not match.
### Tested versions

- Reproducible in 4.3 but was not present in 4.2

### System information

Mac OS Sonoma M1

### Issue description

Resources with typed arrays of resources show up as the path to the resource instead of the class name in editor causing an error that the type does not match. Removing the typing in script logic accessing the array fixes the error and the script runs correctly.

Resource contains:
```gdscript
@export var resources: Array[test_res]
```
Accessing it like so:
```gdscript
const CONTAINER: container_res = preload("res://container.tres")
...
for resource: test_res in CONTAINER.resources:
```
Produces:
`Parse Error: Unable to iterate on value of type "Array[res://test_res.gd]" with variable of type "test_res".`

I believe this is related to the following changes: #78219 #90751 #85024

### Steps to reproduce

Create resource that contains an array of custom resources. Attempt to iterate or access values from the array as the custom resource class type.

### Minimal reproduction project (MRP)

Minimum example files
[testgd.zip](https://github.com/user-attachments/files/16671595/testgd.zip)

### LINKED ISSUE #103200: Editor cannot cast constant subresource when accessed by through variable index
### Tested versions

Reproducible in 4.4-beta1, 4.4-rc1

### System information

Godot v4.4.rc1 - Windows 11 (build 22631) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

### Issue description

Attempting to assign a variable typed to resource class creates error message if it was accessed from an array or dictionary of another constant resource with a variable used as an index. Loading it, instead of preloading, does not have this issue.

### Steps to reproduce

Create a custom resourcesuch as:

```gdscript
class_name MyResource
extends Resource

@export var sub_resource_arr: Array[MySubResource]
@export var sub_resource_dict: Dictionary[int, MySubResource]
```

And another with:

```gdscript
class_name MySubResource
extends Resource
```

Create a new resource of that type, then attempt to assign a variable like so:

```gdscript
class_name MyClass
extends Node

const resource: MyResource = preload("res://my_resource.tres")

func _ready():
	var index: int = 0
	var sub_resource: MySubResource
	var loaded_resource: MyResource = load("res://my_resource.tres")
	sub_resource = loaded_resource.sub_resource_arr[index]
	sub_resource = resource.sub_resource_arr[index]
	sub_resource = resource.sub_resource_dict[index]
```

The editor throws an error for the last two lines in _ready().

```
Line 11:Value of type "res://my_sub_resource.gd" cannot be assigned to a variable of type "MySubResource".
Line 12:Value of type "res://my_sub_resource.gd" cannot be assigned to a variable of type "MySubResource".
```

### Minimal reproduction project (MRP)

N/A

### LINKED ISSUE #113278: Exporting Variant initialized as Array(or certain types) results in Nil
### Tested versions

Reproducible in 4.5 and above.
Variants can't be exported until v4.5.

### System information

Godot v4.6.dev (7ed0b6167) - Windows 11 (build 26100) - OpenGL 3 (Compatibility) -  i7-14700K (28 threads) - 31.76 GiB memory

### Issue description

A variable can be exported as a Variant as follows:
```
@export var test1 = 1 as Variant
@export var test2 = "test" as Variant
@export var test3 = [1, 2] as Variant
```
the first two variables are exported correctly as Variants.

Image

But the third variable is exported as a Nil type.

Image

whereas it was supposed to be exported like this:

Image

It happens to basically any nullable type like Array, PackedByteArray, Dictionary, etc..

Another thing to note is that whenever you change the type in editor from a non-nullable type to a nullable type, the nullable type always gets assigned to Nil.

Image

Image

But when i change that variable to Nil type and change it to Array or any nullable type, the default value gets assigned correctly.

Image

Image

Image

Image

Basically, exporting or editing nullable types (Array, Dictionary, etc.) as Variant in Godot causes them to incorrectly default to Nil, unlike basic types which export correctly.

### Steps to reproduce

Attach a script to any node in the scene.

Issue while creating:

Try exporting Array or Dictionary variable like:
```
@export var test3 = [1, 2] as Variant
@export var test4 = {} as Variant
```
See the output in editor -> it will be null, instead it should be represented as valid objects of respective types.

Issue while modifying:
```
@export var test1 = 1 as Variant
@export var test2 = "test" as Variant
```

Change the type of the variables in editor (using the pen icon) to Array or Dictionary.
You will see null, instead it should be represented as default values of respective types.

### Minimal reproduction project (MRP)

[reproc_project_4.6.zip](https://github.com/user-attachments/files/23824098/reproc_project_4.6.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
> [!IMPORTANT]
> This PR also fixes a bug (eliminates an inconsistency between `Array` and packed arrays) that some users may consider a breaking change, see the [comment](#issuecomment-3737468559) below.

* Fixes #81256.
* Fixes #95568.
* Fixes #95851.
* Fixes #96152.
* Fixes #103200.
* Fixes #113278.
* Fixes #115428.

I've noticed that users are complaining that the following code doesn't work:

```gdscript
@export_custom(
    PROPERTY_HINT_TYPE_STRING,
    "%d/%d:Zero,One,Two" % [TYPE_INT, PROPERTY_HINT_ENUM],
)
var my_array: Array
```

due to the error `Argument 2 of annotation "@export_custom" isn't a constant expression.`.

As a workaround, you can use:

```gdscript
const FORMAT_PARAMS = [TYPE_INT, PROPERTY_HINT_ENUM]
@export_custom(
    PROPERTY_HINT_TYPE_STRING,
    "%d/%d:Zero,One,Two" % FORMAT_PARAMS,
)
var my_array: Array
```

But this is not the most intuitive solution, and it also requires you to have a redundant constant.

The main problem is that our main expression reduction mechanism doesn't take context into account (typed context, constant context), and array/dictionary "literals" (`[]` and `{}` constructs) create untyped, non-constant arrays/dictionaries by default. While changing this system requires relatively significant effort, fixing constant reduction within the existing `make_*_reduced_value()` helper functions is fairly straightforward.

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -6150,6 +6314,21 @@ bool GDScriptAnalyzer::is_type_compatible(const GDScriptParser::DataType &p_targ
 	return check_type_compatibility(p_target, p_source, p_allow_implicit_conversion, p_source_node);
 }
 
+// NOTE:`is_type_compatible()` considers typed arrays/dictionaries compatible with untyped ones (but the operation is unsafe).
+// However, in the case of constant expressions, this leads to incorrect results.
```
Comment (Shadows-of-Fire) [inline modules/gdscript/gdscript_analyzer.cpp:6294]: What do you mean here by the operation is unsafe? The consideration of it being compatible is unsafe?

Why does that consideration cause correctness issues in constant eval?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -229,6 +231,28 @@ static GDScriptParser::DataType make_builtin_meta_type(Variant::Type p_type) {
...
+		case Variant::PACKED_VECTOR2_ARRAY:
+		case Variant::PACKED_VECTOR3_ARRAY:
+		case Variant::PACKED_COLOR_ARRAY:
+		case Variant::PACKED_VECTOR4_ARRAY:
+			return true;
+		default:
+			return false;
+	}
+}
+
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_analyzer.cpp]: What exactly is the concern with adding packed arrays to the mentioned method directly?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 3]
```diff
@@ -3113,7 +3137,10 @@ void GDScriptAnalyzer::reduce_binary_op(GDScriptParser::BinaryOpNode *p_binary_o
 	}
 #endif // DEBUG_ENABLED
 
-	if (p_binary_op->left_operand->is_constant && p_binary_op->right_operand->is_constant) {
+	if (p_binary_op->left_operand->is_constant &&
+			p_binary_op->right_operand->is_constant &&
+			!is_reference_type(p_binary_op->left_operand->reduced_value.get_type()) &&
+			!is_reference_type(p_binary_op->right_operand->reduced_value.get_type())) {
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_analyzer.cpp]: Why are those checks necessary? As far as I understood the approach nothing changes about the node data. Only the results from the helper methods reflect the new logic.

In particular those checks mean that e.g. `A + B` is no longer considered constant for this:
```
const A = []
const B = []
```

It does not seem to cause issues because we fallback to the helper methods to get a constant value anyway. Still I wonder if the behaviour change is intended?

File: modules/gdscript/gdscript_analyzer.cpp [hunk 4]
```diff
@@ -5426,6 +5439,140 @@ Variant GDScriptAnalyzer::make_call_reduced_value(GDScriptParser::CallNode *p_ca
...
+		} else if (result.get_type() == Variant::DICTIONARY) {
+			Dictionary dictionary = result;
+			dictionary.make_read_only();
+		}
+
+		is_reduced = true;
+		return result;
+	}
+
+	return Variant();
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_analyzer.cpp]:
```suggestion
	if (!valid) {
		return Variant();
	}
	if (result.get_type() == Variant::ARRAY) {
		Array array = result;
		array.make_read_only();
	} else if (result.get_type() == Variant::DICTIONARY) {
		Dictionary dictionary = result;
		dictionary.make_read_only();
	}

	is_reduced = true;
	return result;
```
IMO reducing nesting helps with readability. Might be subjective though.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 5]
```diff
@@ -5426,6 +5439,140 @@ Variant GDScriptAnalyzer::make_call_reduced_value(GDScriptParser::CallNode *p_ca
 	return Variant();
 }
 
+Variant GDScriptAnalyzer::make_binary_op_reduced_value(GDScriptParser::BinaryOpNode *p_binary_op, bool &is_reduced) {
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_analyzer.cpp]:
```suggestion
Variant GDScriptAnalyzer::make_binary_op_reduced_value(GDScriptParser::BinaryOpNode *p_binary_op, bool &r_is_reduced) {
```

Usually this should be `r` prefixed I guess. Not sure if we should leave it away for consistency though since the old methods also omit it.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 6]
```diff
@@ -5426,6 +5439,140 @@ Variant GDScriptAnalyzer::make_call_reduced_value(GDScriptParser::CallNode *p_ca
...
+			dictionary.assign(result);
+			dictionary.make_read_only();
+			result = dictionary;
+		}
+
+		is_reduced = true;
+		return result;
+	}
+
+	return Variant();
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_analyzer.cpp:5523]:
```suggestion
	if (cast_type.kind != GDScriptParser::DataType::BUILTIN & cast_type.kind != GDScriptParser::DataType::ENUM) {
		return Variant();
	}
	Variant result;
	const Variant *argptr = &operand_value;
	Callable::CallError ce;
	Variant::construct(cast_type.builtin_type, result, &argptr, 1, ce);
	if (ce.error) {
		return Variant();
	}

	if (result.get_type() == Variant::ARRAY) {
		Array array = cast_type.has_container_element_type(0) ? make_array_from_element_datatype(cast_type.get_container_element_type(0)) : Array();
		array.assign(result);
		array.make_read_only();
		result = array;
	} else if (result.get_type() == Variant::DICTIONARY) {
		Dictionary dictionary = cast_type.has_container_element_types()
				? make_dictionary_from_element_datatype(cast_type.get_container_element_type_or_variant(0), cast_type.get_container_element_type_or_variant(1))
				: Dictionary();
		dictionary.assign(result);
		dictionary.make_read_only();
		result = dictionary;
	}

	is_reduced = true;
	return result;
```

File: modules/gdscript/gdscript_analyzer.cpp [hunk 7]
```diff
@@ -5426,6 +5439,140 @@ Variant GDScriptAnalyzer::make_call_reduced_value(GDScriptParser::CallNode *p_ca
...
+}
+
+Variant GDScriptAnalyzer::make_type_test_reduced_value(GDScriptParser::TypeTestNode *p_type_test, bool &is_reduced) {
+	bool is_operand_value_reduced = false;
+	Variant operand_value = make_expression_reduced_value(p_type_test->operand, is_operand_value_reduced);
+	if (!is_operand_value_reduced) {
+		return Variant();
+	}
+
+	GDScriptParser::DataType test_type = type_from_metatype(p_type_test->test_type->get_datatype());
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_analyzer.cpp:5533]: This should work and relies on the fact that a node gets reduced before `make_reduced_value` is called for it. This is currently the case, but I'm a fan of writing such assumptions down somewhere so maybe we could add a comment to the root method to mention this assumption as part of the methods contract.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 8]
```diff
@@ -5426,6 +5439,140 @@ Variant GDScriptAnalyzer::make_call_reduced_value(GDScriptParser::CallNode *p_ca
...
+	}
+
+	GDScriptParser::DataType operand_type = type_from_variant(operand_value, p_type_test->operand);
+	if (!operand_type.is_set()) {
+		return Variant();
+	}
+
+	bool result = false;
+	if (is_type_compatible_strict_collections(test_type, operand_type)) {
+		result = test_type.builtin_type != Variant::OBJECT || !operand_value.is_null();
```
Comment (HolonProduction) [inline modules/gdscript/gdscript_analyzer.cpp:5545]: This condition is unnecessarily confusing IMO. Why the `test_type.builtin_type != Variant::OBJECT` part? `null is ...` should always eval to `false`. Am I missing something?

If the idea is to only correct exactly those results of `is_type_compatible` that are not viable for type tests (null being assignable to Object) then couldn't we just add this case to `is_type_compatible_strict_collections` and rename it to `is_type_compatible_type_test`?

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:6294]: We have an exception in the type system that allows untyped arrays to reference typed ones. Accordingly, typed arrays can also accept untyped arrays, but source lines involving such operations are marked as unsafe (at runtime, the untyped array may or may not be of the correct type). For constants, the situation is different in that we know the values ​​statically, and this part of the type-checking logic fails in a constant context.

```gdscript
# Godot 4.5.1

const UNTYPED_ARRAY: Array = ["a"]
const A: Array[int] = UNTYPED_ARRAY # Marked as safe.
print(A) # Bug: Prints `["a"]`.

var untyped_array: Array = ["a"]
# Runtime error: Trying to assign an array of type "Array" to a variable of type "Array[int]".
var a: Array[int] = untyped_array # Marked as unsafe.
print(a)
```

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp]: This affects the core. I'll look at other uses of this method, and if nothing else depends on it, I'll update the PR.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 3 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp]: The difference is that regular constant folding always works, in both dynamic and constant contexts. Meanwhile, `make_*_reduced_value()` methods are called exclusively in constant context (constant initializers, annotation arguments). Thus, we prohibit treating `<constant array> + <constant array>` as a constant expression in dynamic context (via regular constant folding) and allow it in constant context (via the fallback constant folding mechanism).

File: modules/gdscript/gdscript_analyzer.cpp (hunk 4 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp]: Makes sense in this case, thanks! But I'd like to point out that, in general, I don't think it's always a good idea to reduce the level of block nesting. In some cases, I find it much clearer to have non-inverted conditions and a clearer control flow than to skimp on nesting levels.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 5 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp]: We should probably rename the parameter for all `make_*_reduced_value()` functions. I'll do that since I've already touched on this.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 6 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:5523]: In this case, I'd prefer not to invert the condition and not perform an early exit from the function. This code reflects a case in which we **can** perform constant folds on the cast construct (if the type is built-in or enumerable), but not one in which we **can't**.

Suppose we want to extend this code in the future and find another case where we can perform constant folds. In that case, we'll have to not just add the condition below, but either exclude it as well from the early exit condition above, or first invert the condition back and refactor the code to its current form.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 7 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:5533]: Added a comment.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 8 above)
Comment (dalexeev) [reply modules/gdscript/gdscript_analyzer.cpp:5545]: This logic is copied from `reduce_type_test()`. Initially, I wanted to do something like what you described, but I didn't like the excessive specificity of that method. In my opinion, `is_type_compatible_strict_collections()` is more abstract, general, and potentially reusable. Yes, it's still far from the solution I'd like to have, but such a change to type compatibility checking would be much more significant.

File: modules/gdscript/tests/scripts/utils.notest.gd
Comment (dalexeev) [inline modules/gdscript/tests/scripts/utils.notest.gd:1]: `Engine.capture_script_backtraces()` does not work in GDScript tests, unlike `get_stack()`. CC @mihe

File: modules/gdscript/gdscript_analyzer.cpp (hunk 8 above)
Comment (HolonProduction) [reply modules/gdscript/gdscript_analyzer.cpp:5545]: Ok so no part of the function. Still I think we should just do `result = !operand_value.is_null();`. It will result in the same behaviour and is easier to understand.

**Review by HolonProduction — APPROVED** [review]
LGTM. If the change to regular constant folding has any unwanted effects we will find out I guess.

I don't think the "compat break" with packed arrays is of much concern. Since there was never a writeback for methods like `append` it was no way to monitor array changes reliable anyway. So I don't see any usecase for the old behavior.

**Review by Ivorforce — APPROVED** [review]
Core changes look good. Packed arrays are indeed shared inside `Variant`.

However, I think the history of the function should be considered before merge:

- The function started in GODOT IS OPEN SOURCE without considering packed arrays as shared.
- Later, @vnen changed this via https://github.com/godotengine/godot/pull/62462/, to fix setter related bugs.
- Later still, @vnen reverted this change via https://github.com/godotengine/godot/pull/72398 because packed arrays "are copied on C++/script boundaries".

Indeed, packed arrays behave differently inside and outside `Variant`. For example, `Variant` based calls copy the arrays across the boundary, while the `ptrcall` does not cause a copy to be made.
I still think `is_type_shared` makes sense to be `true` for packed arrays in the context of `Variant`, but we should tread carefully to not overinterpret this information.
I checked `is_type_shared` and `is_shared`, and they seem to only be used inside GDScript / the GDScript vm. 

So please confirm you're confident the GDScript changes are fine, especially with regards to https://github.com/godotengine/godot/pull/72398 / https://github.com/godotengine/godot/issues/62857. If so, I agree we should merge this.

File: modules/gdscript/tests/scripts/utils.notest.gd
Comment (mihe) [reply modules/gdscript/tests/scripts/utils.notest.gd:1]: Noted. I'll look into it when I can find some time.
