### PR TITLE
Check for a Vulkan extension before checking its features

### LINKED ISSUE #65409: Godot 4: gpu/os crash on startup with Vulkan (Linux, Radeon, regression in alpha 13)
### Godot version

4.0 alpha 15 (same problem on older alphas)

### System information

Nobara linux 36 KDE (Fedora 36)

### Issue description

Hello,

In short, my issue is that my display freezes and input stops (keyboard, mouse, etc) but sound is still working, whenever I startup Godot 4 alpha 15 | x86_64 (and 32) (same problem on older alphas) and my only option is hard reboot. Crash happens before Godot's window is drawn. I'm currently on Nobara 36 KDE (Fedora 36, Wayland) and I've also tried with EndeavourOS Atlantis (arch, xOrg) on the same system, the problem persists.

I've tried launching godot with `--single-window`, the problem is still there, but I found that launching Godot with `opengl3` instead of Vulkan, works. Well not totally, the UI is broken, unless I launch it with `--single-window` on top of using `opengl3`.

I think that Vulkan is the problem here, I can't log what's happening since my pc is freezing, but the freeze happens the instant Vulkan is executed by Godot. 

And of course, Vulkan is installed and working well in my pc, no errors, I can play games with Vulkan exclusively already, everything is up-to-date in my system and I also recently did a clean os install, just to make sure my system wasn't the problem. Godot 3.5 and older versions perfectly work, in windows or linux.

For the experiment, I tried launching Godot 4 alpha 15 win 64 with wine, the exact same problem happens. Seems like the AMD Vulkan driver is having issues with Godot's behavior?

Here's more info about my system, just in case:

- Operating System: Nobara Linux 36
- KDE Plasma Version: 5.25.4
- KDE Frameworks Version: 5.97.0
- Qt Version: 5.15.5
- Kernel Version: 5.19.4-201.fsync.fc36.x86_64 (64-bit)
- Graphics Platform: Wayland
- Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
- Memory: 7.7 GiB of RAM
- Graphics Processor: AMD Radeon HD 8800 Series
- GPU driver: Mesa 22.3.0-devel (LLVM 14.0.5)
- Vulkan driver: RADV 1.3.224
- Manufacturer: Gigabyte Technology Co., Ltd.

### Steps to reproduce

Launch Godot 4 with the default launch options (Vulkan) in Linux, GPU AMD Radeon HD 8800 series.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by deralmas**
For some reason AFAICT mesa reports a feature as enabled even when its extension isn't supported. The Vulkan specification says nothing aboutd this so this is technically more of a workaround, but it works.

I think that this oddity has always been present in mesa but we just got lucky by targeting features supported by all GPUs, up until variable rate shading.

Fixes #65409.

Note that this approach technically still uses `vkGetPhysicalDeviceFeatures2` in an invalid way (passing disabled extension feature structs in `pNext`), but a proper solution would require a more convoluted approach and this works fine.

### CODE REVIEW

File: drivers/vulkan/vulkan_context.cpp [hunk 1]
```diff
@@ -687,21 +687,42 @@ Error VulkanContext::_check_capabilities() {
 
 		vkGetPhysicalDeviceFeatures2_func(gpu, &device_features);
 
-		vrs_capabilities.pipeline_vrs_supported = vrs_features.pipelineFragmentShadingRate;
-		vrs_capabilities.primitive_vrs_supported = vrs_features.primitiveFragmentShadingRate;
-		vrs_capabilities.attachment_vrs_supported = vrs_features.attachmentFragmentShadingRate;
+		// We must check that the relative extension is present before assume a
+		// feature as enabled. While this isn't in the spec, this has caused some
```
Comment (RandomShaper) [inline drivers/vulkan/vulkan_context.cpp:691]: Now we know it's in the spec, this comment warrants a change.

File: drivers/vulkan/vulkan_context.cpp [hunk 2]
```diff
@@ -687,21 +687,42 @@ Error VulkanContext::_check_capabilities() {
...
+		// issues. See also: https://github.com/godotengine/godot/issues/65409
+		for (uint32_t i = 0; i < enabled_extension_count; ++i) {
+			if (!strcmp(VK_KHR_FRAGMENT_SHADING_RATE_EXTENSION_NAME, extension_names[i])) {
```
Comment (RandomShaper) [inline drivers/vulkan/vulkan_context.cpp:694]: It's up to you, but let me suggest using `== 0` syntax, which is more readable as equality

**Review by RandomShaper — CHANGES_REQUESTED** [review]
I've left a couple of little comments. Looks good otherwise.

**Review by RandomShaper — APPROVED** [review]
Makes sense!

**Review by akien-mga — APPROVED** [review]
Great work, thanks a lot for fixing this!
