### PR TITLE
Fix cursor selection box color

### LINKED ISSUE #115023: Modern Theme: selection marquee is hard to see against a dark background in light mode (and vice versa)
### Tested versions

v4.6.rc1.official [481f36ed2]

### System information

Godot v4.6.rc1 - Manjaro Linux `#1` SMP PREEMPT_DYNAMIC Thu, 08 Jan 2026 10:03:06 +0000 on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7600 (RADV NAVI33) - AMD Ryzen 5 5600 6-Core Processor (12 threads) - 15.54 GiB memory

### Issue description

When using light mode with the Modern theme, the selection marquee (both 2D and 3D) is very hard to see against dark backgrounds:

Image

Image

The inverse is also true:

Image

Image

In the Classic theme, the selection marquee used the accent color which mitigated this problem, but it seems like the Modern theme is using the base color instead.

### Steps to reproduce

Set theme color preset to light/dark and drag a selection in 2D or 3D against a dark/light background

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MaxiSanc37**
Fixed cursor selection box color in ./themes/theme_modern.cpp 

Fixes #115023 

https://github.com/user-attachments/assets/82856ec3-7f09-49eb-9a9f-807309a15a42

### CODE REVIEW

File: editor/themes/theme_modern.cpp [hunk 1]
```diff
@@ -220,8 +220,8 @@ void ThemeModern::populate_shared_styles(const Ref<EditorTheme> &p_theme, Editor
 
 		// Additional editor colors.
 
-		p_theme->set_color("box_selection_fill_color", EditorStringName(Editor), p_config.mono_color * Color(1, 1, 1, 0.12));
-		p_theme->set_color("box_selection_stroke_color", EditorStringName(Editor), p_config.mono_color * Color(1, 1, 1, 0.4));
+		p_theme->set_color("box_selection_fill_color", EditorStringName(Editor), Color(0.65, 0.65, 0.65, 0.28)); // changed the values for better contrast in the selection box
```
Comment (AThousandShips) [inline editor/themes/theme_modern.cpp]:
```suggestion
		p_theme->set_color("box_selection_fill_color", EditorStringName(Editor), Color(0.65, 0.65, 0.65, 0.28));
```
Unnecessary comment

File: editor/themes/theme_modern.cpp [hunk 2]
```diff
@@ -220,8 +220,8 @@ void ThemeModern::populate_shared_styles(const Ref<EditorTheme> &p_theme, Editor
 
 		// Additional editor colors.
 
-		p_theme->set_color("box_selection_fill_color", EditorStringName(Editor), p_config.mono_color * Color(1, 1, 1, 0.12));
-		p_theme->set_color("box_selection_stroke_color", EditorStringName(Editor), p_config.mono_color * Color(1, 1, 1, 0.4));
+		p_theme->set_color("box_selection_fill_color", EditorStringName(Editor), Color(0.65, 0.65, 0.65, 0.28));
+		p_theme->set_color("box_selection_stroke_color", EditorStringName(Editor), Color(0.55, 0.55, 0.55, 0.4));
```
Comment (passivestar) [inline editor/themes/theme_modern.cpp]:
```suggestion
		p_theme->set_color("box_selection_fill_color", EditorStringName(Editor), Color(0.65, 0.65, 0.65, 0.15));
		p_theme->set_color("box_selection_stroke_color", EditorStringName(Editor), Color(0.55, 0.55, 0.55, 0.55));
```

I'd push the opacity of stroke and fill apart from each other to make the border easier to see:

| Before | After |
|--------|--------|
|  |  |

Comment (MaxiSanc37) [reply editor/themes/theme_modern.cpp]: Totally, I'll commit that suggestion!

**Review by passivestar — APPROVED** [review]
