### PR TITLE
Fix NavBase properties not requesting sync

### LINKED ISSUE #102745: NavigationAgent3D doesn't use NavigationLink3D after switching navigation layer of NavigationLink3D via script
### Tested versions

4.4 beta2, beta3
This works in 4.3

### System information

 4.4-beta3 .NET for windows

### Issue description

I use NavigationLink3D for doors. I used tutorial below, but instead of navigation mesh i used NavigationLink3D 
 because it works better with Terrain3D https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_different_actor_area_access.html 
My scene is initialized with NavigationLink3D at layer 2 and when I open door it moves to Layer 1, however NPC still can't calculate path until I modify "End" or "Start" via "Remote" Tab of Scene Tree.

### Steps to reproduce

1. connect 2 navigation meshes with NavigationLink3D
2. Set NavigationLink3D layer to 2
3. Set NavigationAgent3D layer to 1 and NavigationRegion3D layer to 1
4. Attach script that changes NavigationLink3D layer to 1
5. At runtime active script to switch NavigationLink3D  layer to 1
Expected:
NavigationAgent3D can use NavigationLink3D to reach unreachable navigation mesh

Actual:
NavigationAgent3D doesn't use NavigationLink3D  and can't reach desired mesh

### Minimal reproduction project (MRP)

[pathfindingbug.zip](https://github.com/user-attachments/files/18761829/pathfindingbug.zip)

### PR DESCRIPTION
**Pull request by smix8**
Fixes that setters of NavBase properties never made the link or region dirty and requested a sync.

Fixes https://github.com/godotengine/godot/issues/102745

Frankly that the NavBase setters never made the link or region dirty was already questionable, it was just not creating an immediate problem. It was not a problem before because everything, for better or worse, was reading directly from the link or region pointer. Now it is reading from an iteration and without a sync request this iteration never gets updated and that caused the bug.

### CODE REVIEW

File: modules/navigation/nav_link.cpp [hunk 1]
```diff
@@ -94,6 +94,46 @@ void NavLink::set_end_position(const Vector3 p_position) {
...
+	link_dirty = true;
+
+	request_sync();
+}
+
+void NavLink::set_enter_cost(real_t p_enter_cost) {
+	if (enter_cost == p_enter_cost) {
+		return;
+	}
+	enter_cost = MAX(p_enter_cost, 0.0);
```
Comment (kiroxas) [inline modules/navigation/nav_link.cpp:111]: You should probably clamp the incoming cost before the if. As if your enter_cost is 0 and p_enter_cost is negative, you will sync for no reason

**Review by akien-mga — APPROVED** [review]

**Review by kiroxas — APPROVED** [review]
