### PR TITLE
Avoid color conversion roundtrip in colorpicker

### LINKED ISSUE #109065: Colorpicker slider/spinbox yields incorrect values in rgb mode
### Tested versions

Master(https://github.com/godotengine/godot/commit/0dd9178269e447aca805bc4b4a9a840119c10275) (Couple days old)

### System information

-

### Issue description

Was thinking a bit more about https://github.com/godotengine/godot/pull/109012. How come `11.0/255.0` gets saved as `0.04313725` when there are two closer decimal representations? Well it seems the fault lies with the color picker sliders (doesn't invalidate the pr - rounding is still the correct approach as `10.9999983943998813629150390625` should still definitely result in choosing 11 not 10).

When setting a slider to an integer value in RGB mode, the picked color float value is not the closest presentable float value. E.g. Color #0b0000, red channel:
```
0.04313725490196078371507582005506 - double, 11 / 255
0.0431372560560703277587890625 - Color.html(#0b0000)
0.0431372560560703277587890625 - Color8(11, 11, 11)
0.0431372560560703277587890625 - Color picker, html #0b0000
0.0431372486054897308349609375 - Color picker, slider 11 (2 bits off from closest possible)
```
Why important? Multiplying and flooring yields different values:
```
0.0431372560560703277587890625 * 255.0 = 11.0000002942979335784912109375
0.0431372486054897308349609375 * 255.0 = 10.9999983943998813629150390625
```

### Steps to reproduce

1. Choose a value in color picker using sliders in RGB mode
2. Compare the value to setting it using html.
3. Observe that the values don't match.

### Minimal reproduction project (MRP)

[picker-underreperesented.zip](https://github.com/user-attachments/files/21477412/picker-underreperesented.zip)

### PR DESCRIPTION
**Pull request by Lielay9**
Fixes #109065

### CODE REVIEW

File: scene/gui/color_picker.cpp [hunk 1]
```diff
@@ -680,6 +680,9 @@ void ColorPicker::_copy_hsv_okhsl_to_normalized() {
 }
 
 Color ColorPicker::_color_apply_intensity(const Color &col) const {
+	if (intensity == 0.0f) {
```
Comment (KoBeWi) [inline scene/gui/color_picker.cpp:683]:
```suggestion
	if (Math::is_zero_approx(intensity)) {
```
Though not sure if it matters here.

**Review by KoBeWi — APPROVED** [review]

File: scene/gui/color_picker.cpp (hunk 1 above)
Comment (Lielay9) [reply scene/gui/color_picker.cpp:683]: > Though not sure if it matters here.

Technically speaking zero approx would forbid using values below `0.0000099999988378840498626232147216796875` (1,850,706,774 values wasted 😱!), in practice there is no difference as it's an user facing ui value that you cant even set below `0.001`. Since it is trivial to set to 0, I'd say setting it to any other value is intentional.

**Comment by Repiteo** [comment]
Thanks!
