### PR TITLE
Metal: Fix crash when uniform set is empty for slot binding mode

### LINKED ISSUE #100764: Metal: Error compiling compute shader on iPhone A12
When compiling the `particles.glsl` shader for an A12 or earlier device, it fails with the following error:

```
validateComputeFunctionArguments:1083: failed assertion `Compute Function(main0): argument src_particles[0] from buffer(4) with offset(0) and length(16) has space for 16 bytes, but argument has a length(128).'
```

> [!NOTE]
>
> Disabling API validation allows the app to run.

The issue is that when using classic binding (i.e. not argument buffers), the ABI for the shader passes the structures as arguments to the entry point:

```metal
struct ParticleEmission
{
    float4x4 xform;
    packed_float3 velocity;
    uint flags;
    float4 color;
    float4 custom;
};

struct SourceEmission
{
    int particle_count;
    uint pad0;
    uint pad1;
    uint pad2;
    ParticleEmission data[1];
};

kernel void main0(device SourceEmission& src_particles [[buffer(5)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
// ...
```

Note that the `src_particles` argument is a `struct SourceEmission`. Note again that this struct has an embedded type `struct ParticleEmission[1]`. Metal doesn't support unsized arrays, but SPRIV-Cross works around it by passing an embedded struct of size `1`. Interestingly, Metal is a variant of C++, and even Godot's definition has to use a sized array for the structure definition:

https://github.com/godotengine/godot/blob/2450dee1bc1495daa2b7bdf06c7b3ddfbf8007e1/servers/rendering/renderer_rd/storage_rd/particles_storage.h#L157

The issue is that when Godot binds an empty emission buffer, it does not need to account for this, so it allocates a size 16:

https://github.com/godotengine/godot/blob/d9ef826c545e7d623279c312ca837b947a4989b3/servers/rendering/renderer_rd/storage_rd/particles_storage.cpp#L544

_Originally posted by @TCROC in https://github.com/godotengine/godot/issues/99820#issuecomment-2558697999_

### PR DESCRIPTION
**Pull request by stuartcarnie**
Closes #100764

Resolves a `CRASH_BAD_INDEX` error when binding uniform sets that are empty, specifically for A12 devices and earlier, which use slot-based binding vs argument buffers.

Resolves a Metal CPU API validation error when binding "empty" particle buffers, that were incorrectly sized. Metal doesn't support defining a struct with an empty array.

# Overview

An example of this in GLSL is:

```glsl
struct ParticleEmission {
  vec3 velocity;
  uint flags;
};

layout(set = 1, binding = 2, std430) restrict buffer SourceEmission {
  int particle_count;
  uint pad0;
  uint pad1;
  uint pad2;
  ParticleEmission data[];
}
src_particles;
```

The minimum size of `SourceEmission` is 16 bytes when binding a buffer for backends that support empty arrays.

However, when this is converted to Metal, note the data member is an array of size `1`:

```metal
struct ParticleEmission {
  float3 velocity;
  uint flags;
};

struct SourceEmission {
  int particle_count;
  uint pad0;
  uint pad1;
  uint pad2;
  ParticleEmission data[1];
};
```

This means that the minimum size of the struct when binding an "empty" array is 32 bytes. This doesn't cause an issue when Metal API validation is disabled, but this feature is often enabled when running code from Xcode, which iPhone developers are likely to do.

### CODE REVIEW

File: drivers/metal/metal_objects.mm [hunk 1]
```diff
@@ -1082,7 +1083,7 @@
 
 	UniformSet const &set = p_shader->sets[index];
 
-	for (uint32_t i = 0; i < uniforms.size(); i++) {
+	for (uint32_t i = 0; i < std::min(uniforms.size(), set.uniforms.size()); i++) {
```
Comment (clayjohn) [inline drivers/metal/metal_objects.mm:1086]:
```suggestion
	for (uint32_t i = 0; i < MIN(uniforms.size(), set.uniforms.size()); i++) {
```
This should use our math library instead of std

Comment (akien-mga) [reply drivers/metal/metal_objects.mm]: That's weird, as `core/typedefs.h` which defines our `MIN` and `MAX` also `undef`'s the pre-existing ones.

Maybe you need an explicit `core/typedefs.h` include here? It's kind of taken for granted usually as most Godot headers include it one way or another, but maybe this specific file of the Metal driver doesn't as it's relatively self-contained?

Comment (stuartcarnie) [reply drivers/metal/metal_objects.mm]: Unfortunately, I'd have to include `typedefs.h` before the system libraries, and then `NSObjCRuntime.h` re-defines it again. Quite a nuisance!

Comment (stuartcarnie) [reply drivers/metal/metal_objects.mm]: This is what it looks like:

```c
#if !defined(MIN)
    #define __NSMIN_IMPL__(A,B,L) ({ __typeof__(A) __NSX_PASTE__(__a,L) = (A); __typeof__(B) __NSX_PASTE__(__b,L) = (B); (__NSX_PASTE__(__a,L) < __NSX_PASTE__(__b,L)) ? __NSX_PASTE__(__a,L) : __NSX_PASTE__(__b,L); })
    #define MIN(A,B) __NSMIN_IMPL__(A,B,__COUNTER__)
#endif
```

**Review by Calinou — APPROVED** [review]
Code looks good to me.

File: drivers/metal/metal_objects.mm [hunk 2]
```diff
@@ -56,6 +56,10 @@
 
 #import <os/signpost.h>
 
+// we have to undefine these macros because they are defined in NSObjCRuntime.h
```
Comment (Calinou) [inline drivers/metal/metal_objects.mm:59]:
```suggestion
// We have to undefine these macros because they are defined in NSObjCRuntime.h.
```

Comment (stuartcarnie) [reply drivers/metal/metal_objects.mm]: Done

File: servers/rendering/renderer_rd/storage_rd/particles_storage.cpp [hunk 3]
```diff
@@ -541,13 +541,15 @@ void ParticlesStorage::_particles_allocate_emission_buffer(Particles *particles)
 
 void ParticlesStorage::_particles_ensure_unused_emission_buffer(Particles *particles) {
 	if (particles->unused_emission_storage_buffer.is_null()) {
-		particles->unused_emission_storage_buffer = RD::get_singleton()->storage_buffer_create(sizeof(uint32_t) * 4);
+		// For rendering devices that do not support empty arrays (like C++),
+		// we need to size the buffer with at least 1 element.
+		particles->unused_emission_storage_buffer = RD::get_singleton()->storage_buffer_create(sizeof(ParticleEmissionBuffer));
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:546]: I'm creating an empty buffer with enough data for one element, which is required for backends, like Metal, that don't support empty arrays in `struct` definitions, similar to C++.

File: servers/rendering/renderer_rd/storage_rd/particles_storage.cpp [hunk 4]
```diff
@@ -541,13 +541,15 @@ void ParticlesStorage::_particles_allocate_emission_buffer(Particles *particles)
...
 	}
 }
 
 void ParticlesStorage::_particles_ensure_unused_trail_buffer(Particles *particles) {
 	if (particles->unused_trail_storage_buffer.is_null()) {
-		particles->unused_trail_storage_buffer = RD::get_singleton()->storage_buffer_create(sizeof(uint32_t) * 4);
+		particles->unused_trail_storage_buffer = RD::get_singleton()->storage_buffer_create(16 * sizeof(float)); // Size of mat4.
```
Comment (stuartcarnie) [inline servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:552]: This was incorrectly sized, so was causing validation errors when using Metal's slot-based binding API (A12 devices)

**Comment by stuartcarnie** [comment]
@TCROC can you try this, as it should resolve your issues

**Comment by TCROC** [comment]
> @TCROC can you try this, as it should resolve your issues

@stuartcarnie Yep.  I'll merge it into my fork now and let you know how it goes :).

**Comment by TCROC** [comment]
@stuartcarnie I can confirm, this PR appears to fix the issue!  Thank you for the quick response and patch! :)

**Comment by stuartcarnie** [comment]
That's great, thanks for confirming @TCROC

**Review by clayjohn — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
