### PR TITLE
Fix phantom tab right button

### LINKED ISSUE #83232: Phantom tab button steals input despite texture = `null`
### Godot version

v4.0.2.stable.official [7a0977ce2] v4.2.dev6.official [57a6813bb]

### System information

Windows 10

### Issue description

When assigning an already valid tab button icon texture to `null`, it keeps a phantom tab button around that intercepts input from the tabs, even off the tab bar.

- Issue occurs in both TabContainer and TabBar.
- Assigning tab button icon from a texture to `null` will cause the issue.
- Will emit its `tab_button_pressed` signal, prevents tab beneath from getting the input.

[Godot_v4.2-dev6_win64_AWBHLNAo4x.webm](https://github.com/godotengine/godot/assets/104049283/ca88585b-41fd-4523-840b-9cfe5a0bd1e2)

### Steps to reproduce

Download repro, run main and click around like the video above.

### Minimal reproduction project

[bug_reproduction.zip](https://github.com/godotengine/godot/files/12888789/bug_reproduction.zip)

### PR DESCRIPTION
**Pull request by Wierdox**
Fixes #83232

Was caused by only updating the right button `rb_rect` of a tab if the texture was valid. Therefore, it would never be updated when texture is `null` and so keep its size forever.

Solved by adding a branch to its update logic in `TabBar::_draw_tab()` to set `rb_rect` to an empty `Rect2`.

### CODE REVIEW

File: scene/gui/tab_bar.cpp [hunk 1]
```diff
@@ -567,6 +567,9 @@ void TabBar::_draw_tab(Ref<StyleBox> &p_tab_style, Color &p_font_color, int p_in
 		rb->draw(ci, Point2i(rb_rect.position.x + style->get_margin(SIDE_LEFT), rb_rect.position.y + style->get_margin(SIDE_TOP)));
 
 		p_x = rtl ? rb_rect.position.x : rb_rect.position.x + rb_rect.size.width;
+	} else {
+		Rect2 rb_rect;
+		tabs.write[p_index].rb_rect = rb_rect;
```
Comment (YeldhamDev) [inline scene/gui/tab_bar.cpp:572]:
```suggestion
	} else {
		tabs.write[p_index].rb_rect = Rect2();
```

**Review by YeldhamDev — CHANGES_REQUESTED** [review]

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
