### PR TITLE
`ThemeEditor` fix to show filename for new/renamed files

### LINKED ISSUE #109546: `ThemeEditor` does not show theme filename for newly created files
### Tested versions

Godot v4.4.1.stable

### System information

Godot v4.4.1.stable - Windows 11 (build 26100) - Single-window, 2 monitors - OpenGL 3 (Compatibility) - Intel(R) HD Graphics 620 (Intel Corporation; 31.0.101.2115) - Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz (4 threads)

### Issue description

`ThemeEditor` does not show theme filename for newly created files

### Steps to reproduce

Create new Theme resource in FileSystem and see "Theme: " without theme name in `ThemeEditor`.

https://github.com/user-attachments/assets/19c703ea-bdc1-4d5b-8fd7-436e3bd32da9

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aaronp64**
Updated `ThemeEditor` to set the theme name label when theme file is initially created or renamed.

Fixes #109546

### CODE REVIEW

File: editor/scene/gui/theme_editor_plugin.cpp [hunk 1]
```diff
@@ -3749,6 +3750,23 @@ void ThemeEditor::_scene_closed(const String &p_path) {
...
+}
+
+void ThemeEditor::_files_moved(const String &p_old_path, const String &p_new_path) {
+	// Theme's path may not have been updated to new path yet - need to check both old and new.
+	if (theme.is_valid() && (theme->get_path() == p_old_path || theme->get_path() == p_new_path)) {
+		_update_theme_name(p_new_path.get_file());
+	}
+}
+
+void ThemeEditor::_update_theme_name(const String &p_name) {
```
Comment (KoBeWi) [inline editor/scene/gui/theme_editor_plugin.cpp:3766]: The name parameter is redundant tbh.
You can use `theme->get_path().get_file()`.

**Review by KoBeWi — APPROVED** [review]

File: editor/scene/gui/theme_editor_plugin.cpp (hunk 1 above)
Comment (aaronp64) [reply editor/scene/gui/theme_editor_plugin.cpp:3766]: The `p_name` parameter is needed for the `_files_moved` case, when the `theme` path might not have been updated yet.  This happens when the `ThemeEditor` has a theme open, but the inspector dock is pointing to a different object.  If the inspector dock is pointing to the edited theme, `InspectorDock::_files_moved` will set the theme's path, so it can be used directly.  Otherwise, the theme's path is still the old value in `ThemeEditor::_files_moved`, so `p_new_path` needs to be used.  Something else seems to update the theme's path later on - if the inspector dock doesn't get it, saving the theme still uses the correct new path.

**Comment by Repiteo** [comment]
Thanks!
