### PR TITLE
Fix inconsistent scene file name casing

### LINKED ISSUE #57768: Inconsistent capitalization of default scene file names
### Godot version

Godot_v4.0-alpha1_linux.64

### System information

recently updated arch linux

### Issue description

When saving a new scene for the first time the default name (without extension) is the name of the root node of that scene but starting with a lowercase letter (even when the root node starts with an uppercase letter).

When saving a branch as a scene and the root of that branch starts with an uppercase letter, the default filename is the name of that branch root as it is, so with an uppercase letter.

I would expect the proposed default filename to be more consistent

### Steps to reproduce

- Create a new project
- Create a root node called `Main`
- Save this scene. It will show `main.tscn` as default filename
- Create a child node called `Player`
- Save the Player branch as a scene. It will show `Player.tscn` as default filename.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ryburnj**
Fixes https://github.com/godotengine/godot/issues/57768.

Moved SceneNameCasing enum and function from `editor_node `to `project_settings`, to make it accessible to both `editor_node `AND `scene_tree_dock`

Also #included `ustring `header in `project_settings.h`

### CODE REVIEW

**Comment by YuriSizov** [comment]
> Moved SceneNameCasing enum and function from editor_node to project_settings, to make it accessible to both editor_node AND scene_tree_dock

Scene dock has access to the editor node, so this is not necessary. You can just factor out the relevant code into a new public method of EditorNode and use it in the scene dock.

**Comment by ryburnj** [comment]
oh sweet, that'll make it easier.
Ill run the changes, thanks man

**Comment by YuriSizov** [comment]
No problem. Please squash your commits into one with a short but specific message that answers the question what does the commit do (same as the PR title, for example).

You can refer to our documentation about rebasing in git to learn about squashing: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by ryburnj** [comment]
sweet, should be all sorted now 👍

File: core/config/project_settings.h [hunk 1]
```diff
@@ -45,9 +45,10 @@ class ProjectSettings : public Object {
 	static const String PROJECT_DATA_DIR_NAME_SUFFIX;
 
 	enum {
-		//properties that are not for built in values begin from this value, so builtin ones are displayed first
+		// Properties that are not for built in values begin from this value, so builtin ones are displayed first
```
Comment (KoBeWi) [inline core/config/project_settings.h:48]:
```suggestion
		// Properties that are not for built in values begin from this value, so builtin ones are displayed first.
```
Should be like this, if you are fixing it.

File: editor/editor_node.cpp [hunk 2]
```diff
@@ -2763,18 +2763,9 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
...
-					case SCENE_NAME_CASING_PASCAL_CASE: {
-						root_name = root_name.to_pascal_case();
-					} break;
-					case SCENE_NAME_CASING_SNAKE_CASE:
-						root_name = root_name.replace("-", "_").to_snake_case();
-						break;
-				}
+				// Send root_name to function in editor_node
+				// to correctly case name based on Global Def, also located in editor_node.
+				root_name = (EditorNode::node_scene_name_casing(root_name));
```
Comment (KoBeWi) [inline editor/editor_node.cpp:2768]:
```suggestion
				root_name = EditorNode::node_scene_name_casing(root_name);
```
Not needed.

File: editor/editor_node.cpp [hunk 3]
```diff
@@ -3090,6 +3081,21 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
 	}
 }
 
+String EditorNode::node_scene_name_casing(String &root_name) {
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3084]:
```suggestion
String EditorNode::adjust_scene_name_casing(String &root_name) {
```
To be consistent with [another similar function](https://github.com/godotengine/godot/blob/4ba934bf3d1e697d8f332b5e8cfd694cdf49a7ba/scene/main/node.cpp#L945).

File: editor/scene_tree_dock.cpp [hunk 4]
```diff
@@ -916,6 +916,9 @@ void SceneTreeDock::_tool_selected(int p_tool, bool p_confirm_override) {
 			String existing;
 			if (extensions.size()) {
 				String root_name(tocopy->get_name());
+				// Send root_name to function in editor_node
+				// to correctly case name based on Global Def, also located in editor_node.
```
Comment (KoBeWi) [inline editor/scene_tree_dock.cpp:920]: Same. Comment not needed.

File: editor/editor_node.cpp (hunk 3 above)
Comment (akien-mga) [reply editor/editor_node.cpp:3084]: Can also be `const String &`.

File: editor/scene_tree_dock.cpp (hunk 4 above)
Comment (ryburnj) [reply editor/scene_tree_dock.cpp:920]: sweet, ill run the changes now
cheers

File: editor/editor_node.cpp (hunk 3 above)
Comment (ryburnj) [reply editor/editor_node.cpp:3084]: Would `const ` be required when I'm altering `p_root_name` by passing it to either `to_pascal_case `or `to_snake_case`?

Comment (ryburnj) [reply editor/editor_node.cpp:3084]: both of the functions I'm passing to expect and un-const string

Comment (KoBeWi) [reply editor/editor_node.cpp:3084]: You don't really need to alter the param, just do `return p_root_name.to_pascal_case()` etc.

Comment (ryburnj) [reply editor/editor_node.cpp:3084]: easy as, cheers mate

**Comment by ryburnj** [comment]
alright, now everything should be squared away

File: editor/editor_node.cpp [hunk 5]
```diff
@@ -3090,6 +3079,21 @@ void EditorNode::_menu_option_confirm(int p_option, bool p_confirmed) {
...
+	switch (ProjectSettings::get_singleton()->get("editor/scene/scene_naming").operator int()) {
+		case SCENE_NAME_CASING_AUTO:
+			// Use casing of the root node.
+			break;
+		case SCENE_NAME_CASING_PASCAL_CASE: {
+			return root_name.to_pascal_case();
+		} break;
+		case SCENE_NAME_CASING_SNAKE_CASE:
+			return root_name.replace("-", "_").to_snake_case();
+			break;
```
Comment (KoBeWi) [inline editor/editor_node.cpp:3092]: No need to break after return. Same above.

File: editor/editor_node.h [hunk 6]
```diff
@@ -125,6 +126,13 @@ class EditorNode : public Node {
 		EDITOR_ASSETLIB
 	};
 
+	// A copy of the name casing used for scripts, modified *barely* to be used with scenes
```
Comment (KoBeWi) [inline editor/editor_node.h:129]:
```suggestion
	// A copy of the name casing used for scripts, modified *barely* to be used with scenes.
```
That comment is not necessary tbh.

**Comment by ryburnj** [comment]
Implemented the suggested changes

File: editor/editor_node.h [hunk 7]
```diff
@@ -89,6 +89,7 @@ class PanelContainer;
 class PluginConfigDialog;
 class ProgressDialog;
 class ProjectExportDialog;
+class ProjectSettings;
```
Comment (KoBeWi) [inline editor/editor_node.h:92]: This is not used.

**Comment by ryburnj** [comment]
done

**Review by KoBeWi — APPROVED** [review]

**Comment by ryburnj** [comment]
for the failed static check, would the fix require the use of `--doctool` ? or is there another way to fix it?

**Comment by KoBeWi** [comment]
You have trailing spaces after `SCENE_NAME_CASING_PASCAL_CASE: `

**Comment by ryburnj** [comment]
hahaha, dam
making the change now

**Comment by ryburnj** [comment]
done

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by ryburnj** [comment]
thanks man, I hope this is a long and happy journey!
