### PR TITLE
GDScript: Fix message when calling non-tool function in tool mode

### LINKED ISSUE #36592: Improve error message for calling non-tool scripts from tool scripts
**Godot version:** 3.2+

**OS/device including version:** Applies to all versions.

**Issue description:**

```
if current_node.has_method("set_view_mode"):
        current_node.set_view_mode(view_mode_index)
```

This gave me the error message: `Invalid call. Nonexistent function 'set_view_mode'`

This was extremely confusing until I asked for help online and we realized that `current_node`'s script was missing the `tool` keyword. It would be very helpful if there was a better error message when this situation occurs. Perhaps something like:

> Cannot run `set_view_mode` on base [whatever] in the editor because the script is not a tool script.

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #36592.
* Alternative to #84045.
* See also #94499.

Instead of the "Nonexistent function..." error, a more useful message is displayed:

> res://addons/BugIsHere/addon_main.gd:15 - Invalid call function 'initialize' in base 'Control (AddonControl)': Attempt to call a method on a placeholder instance. Check if the script has the tool annotation.

### CODE REVIEW

**Comment by AdriaandeJongh** [comment]
Why not something along the lines of "Methods without the @tool annotation can't by called by scripts in tool mode."? "Check if" implies less of a fix.

File: core/object/script_language.cpp [hunk 1]
```diff
@@ -708,6 +708,16 @@ bool PlaceHolderScriptInstance::has_method(const StringName &p_method) const {
 	return false;
 }
 
+Variant PlaceHolderScriptInstance::callp(const StringName &p_method, const Variant **p_args, int p_argcount, Callable::CallError &r_error) {
+	r_error.error = Callable::CallError::CALL_ERROR_INVALID_METHOD;
+#if TOOLS_ENABLED
+	if (Engine::get_singleton()->is_editor_hint()) {
+		return String("Attempt to call a method on a placeholder instance. Check if the script has the tool annotation.");
```
Comment (vnen) [inline core/object/script_language.cpp:715]: "tool annotation" is very specific to GDScript, but this could happen in other scripting languages too. It might be better to refer it as "tool mode" which is more general.

Comment (dalexeev) [reply core/object/script_language.cpp:715]: That's why I didn't use `@tool` so as not to refer to a specific syntax. In my opinion, the term "annotation" can be taken more broadly to include C# attributes and Python decorators. But perhaps other languages ​​have completely different ways of registering global classes, so you're probably right.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Comment by akien-mga** [comment]
No cherry-picking for 4.3.x for now as this caused regressions (fixed with #96173 and #96344, but this calls for some caution/more testing in 4.4).
