### PR TITLE
Fixes to ESCN mesh import

### LINKED ISSUE #63862: Renaming a TSCN to ESCN doesn't regenerate lods
### Godot version

80ddee06e67e93a5453b37f8e5b3297f17a016ac

### System information

Windows 11, Nvidia 3000 series, Vulkan

### Issue description

Rename a tscn to escn and see the lods are gone.  // A hypothetical blender importer that was upgraded.

The MeshInstance3D -> ImporterInstance3d -> MeshInstance3D workflow is broken.

You have a lot of existing work, but the lods are gone because they're user-dev generated meshes

### Steps to reproduce

1. take this fox https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb
2. extract as tscn
3. rename tscn to escn
4. check if lods exist

### Minimal reproduction project

Not at this time. Maybe if requested.

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/63862

Convert mesh instance 3d to a mesh importer instance 3d. Multi mesh is not converted.

Restore ESCN to a working state even if the Blender importer is slower to be updated.

Restores the tscn to escn usecase.

https://github.com/godotengine/godot-docs/pull/6603

## Test Plan

1. take the fox from https://github.com/godotengine/godot/issues/63862 or anywhere else
2. clear inheritance
3. save as different tscn
4. rename that tscn to escn
5. check that the lod works by setting it to lod property to 0 and compare.

### CODE REVIEW

**Comment by fire** [comment]
## Blend Shape Test Plan

1. take the fox from https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/glTF-Binary/AnimatedMorphCube.glb or anywhere else
2. clear inheritance
3. save as different tscn
4. rename that tscn to escn
5. check that the lod works by setting it to lod property to 0 and compare.

File: editor/import/resource_importer_scene.cpp [hunk 1]
```diff
@@ -2614,8 +2614,53 @@ Node *EditorSceneFormatImporterESCN::import_scene(const String &p_path, uint32_t
...
+	TypedArray<Node> nodes = scene->find_children("*", "MeshInstance3D");
+	for (int32_t node_i = 0; node_i < nodes.size(); node_i++) {
+		MeshInstance3D *mesh_3d = cast_to<MeshInstance3D>(nodes[node_i]);
+		Ref<ImporterMesh> mesh;
+		mesh.instantiate();
+		Ref<ArrayMesh> array_mesh_3d_mesh = mesh_3d->get_mesh();
+		Ref<Mesh> mesh_3d_mesh = mesh_3d->get_mesh();
+		if (array_mesh_3d_mesh.is_valid()) {
+			// For the MeshInstance3D nodes, we need to convert the ArrayMesh to an ImporterMesh specially.
+			array_mesh_3d_mesh->set_name(mesh_3d_mesh->get_name());
```
Comment (fire) [inline editor/import/resource_importer_scene.cpp:2627]: Blend Shape are bugged currently.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
