### PR TITLE
Fix for deselecting item when select_mode == SELECT_ROW

### LINKED ISSUE #71306: TreeItem.deselect() doesn't work if select_mode is Tree.SELECT_ROW
### Godot version

v4.0.beta.custom_build [3cc926bf7]

### System information

Windows 10, NVIDIA GeForce GTX 760

### Issue description

If Tree Control select_mode is set to SELECT_ROW, TreeItem.deselect() will not deselect selected item.

### Steps to reproduce

Add Tree Control to scene and set select_mode to SELECT_ROW. Create TreeItem and Button to deselect. Run scene and select item in Tree. Use Tree.get_selected() and on that deselect().

### Minimal reproduction project

[Tree_bug_example.zip](https://github.com/godotengine/godot/files/10407339/Tree_bug_example.zip)

### PR DESCRIPTION
**Pull request by eskandrej**
Fixes [71306](https://github.com/godotengine/godot/issues/71306)

### CODE REVIEW

File: scene/gui/tree.cpp [hunk 1]
```diff
@@ -4202,6 +4202,10 @@ void Tree::item_deselected(int p_column, TreeItem *p_item) {
 
 	if (select_mode == SELECT_MULTI || select_mode == SELECT_SINGLE) {
 		p_item->cells.write[p_column].selected = false;
+	} else {
+		for (int i = 0; i < p_item->cells.size(); i++) {
+			p_item->cells.write[i].selected = false;
+		}
```
Comment (marzecdawid) [inline scene/gui/tree.cpp:4208]: Maybe add `if (select_mode == SELECT_ROW)` after the `else` for better readability?

**Comment by marzecdawid** [comment]
As stated [here](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#modifying-a-pull-request) you should combine every commit into one.

**Review by marzecdawid — APPROVED** [review]
The code looks good and fixes the problem.

However you should probably create a new PR based on separate branch. Quoting @KoBeWi on that matter after asking if PR based on Master does matter:

> yes. PRs on master don't allow you to open a new PR, because every new branch will include master (unless you use some git-fu). Also there is a bug on GitHub, not sure if fixed, but closes master PRs will appear as merged even if they weren't merged. That said, you can't change PRs branch without opening a new one

Follow instructions on this page:
https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

**Comment by KoBeWi** [comment]
Well, PR on master is ok, but you have to wait until it's merged before you make a new one.
Just for future contributions make a new branch per PR.

**Comment by eskandrej** [comment]
🤦‍♂️ Oh, I understand.

**Review by akien-mga — APPROVED** [review]
Seems good to me, but let's wait after the 4.0 release to be safe.

File: scene/gui/tree.cpp [hunk 2]
```diff
@@ -4202,6 +4202,12 @@ void Tree::item_deselected(int p_column, TreeItem *p_item) {
 
 	if (select_mode == SELECT_MULTI || select_mode == SELECT_SINGLE) {
 		p_item->cells.write[p_column].selected = false;
+	} else {
+		if (select_mode == SELECT_ROW) {
```
Comment (KoBeWi) [inline scene/gui/tree.cpp:4206]: This can be combined into one block
```suggestion
	} else if (select_mode == SELECT_ROW) {
```

**Review by KoBeWi — APPROVED** [review]

**Comment by YuriSizov** [comment]
Hey, @eskandrej, can you please rebase your PR against the current master and force-push again? Seems like there were some issues with Godot CPP the last time our checks were run, which blocks this PR from being merged.

**Comment by YuriSizov** [comment]
Thanks! And congrats on your first merged pull request!
