### PR TITLE
Fix audio input gets muted after a while on android

### LINKED ISSUE #86428: Audio input gets muted after a while on android
### Tested versions

4.1.1,4.2 (all devs and betas), 4.2, 4.2.1
mono and regular, tried them all

### System information

MacOS, Sonoma 14, M1 pro -> Problem on Android (tested on 10 - 13)

### Issue description

When recording audio with this minimal project, the audio input gets muted for no apparent reason.
This was a problem on many of my projects and i finally made a minimal project to troubleshoot and same issue.
This only happens on Android, but not on my mac.

https://github.com/godotengine/godot/assets/144027730/ee85caa2-61bf-4dc5-ba8e-e2eca3931ef7

In the video above i was talking and making noise, the bar at the top displays the volume.
You will see it drop to 0 permanently after a while, this was not from me stopping but from the app not detecting any audio input anymore.

The audio file is muted from that part on as you'd expect.

I have tried messing around with mix rate, stereo, other random settings, audio focus an threads but with no luck.

I believe there is some issue in the godot backend

### Steps to reproduce

Install android build template on the minimal project.
Install on android.
Start recording.
Watch how it just mutes permanently after a while.
The muted thing resets after restarting the audio recorder.

### Minimal reproduction project (MRP)

[AudioRecord test.zip](https://github.com/godotengine/godot/files/13751660/AudioRecord.test.zip)

### PR DESCRIPTION
**Pull request by AndreiPetrov890**
Fix the buffer underrun situation, which leads to unexpected mute of mic input in android application.

Original bug report: (https://github.com/godotengine/godot/issues/86428)

I personally encountered the same problem on my own project.

My solution is to delete mixed_frames correction in AudioStreamMicrophone. In other places of code this correction is used as sign of end of sound source (melody or recordings). But it's mic, folks. Mic stream must work until I stop it by myself, recording ambient sound. So no need to check the end of sound source. Mic source have no end.

Big thanks to @leoyanis, who ponts to problem, and great thanks to @kus04e4ek, who points to roots of the problem.

* *Bugsquad edit, fixed: https://github.com/godotengine/godot/issues/86428*

### CODE REVIEW

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/pull/92969
* https://github.com/godotengine/godot/pull/93154

**Comment by kus04e4ek** [comment]
I don't really like this approach, if this code get triggered, that means that `AudioStremPlaybackMicrophone` tries to read data that's not yet written (at least that's what this code tries to do), this should never happen and if it does that means that safety measures against it should be rethinked (input buffer size and `playback_delay`) or `AudioDriver` implementation does something wrong. This was however trigerred not by `AudioDriver` implementation being wrong or safety measures not working, it was trigerred by this: #93125. I think this check should stay, as otherwise reading from the input buffer would randomly fail and you would here silence for a second, which is not ideal. In the PRs AThousandShips linked I added an error message if something like this happens, IMO users should report the error message and not silence, if something goes wrong

**Comment by AndreiPetrov890** [comment]
> if this code gets triggered, that means that `AudioStremPlaybackMicrophone` tries to read data that's not yet written (at least that's when this code is supposed to be executing), this should never happen

100%, dude!

I guess this happens occasionly due to noise suppressor working in android, which stops recording instead of recording silence. I'm not sure, but that might be the case.

However, this patch works in my project and anyone can use it until a new version of the engine comes out, which I hope will include your patch for this issue.

Best regards!

**Comment by goatchurchprime** [comment]
Looking at the code, this PR [reverts a change](https://github.com/godotengine/godot/commit/53843ba872e3e76c05e8bf9a86d1876914e1ba89) made 3 years ago to make `_mix_internal()` correctly return the number of frames successfully mixed. 

I can't find my way round the code perfectly, but it seems that if the the number of frames mixed is less than the number of frames requested then the AudioServer assumes it has hit the end of the input stream, copies the tail into the stream buffer and probably turns itself off.  https://github.com/godotengine/godot/blob/master/servers/audio_server.cpp#L405

This PR suppresses this case of the mixing buffer catching up to `AudioDriver.input_position` of the `AudioDriver.input_buffer` and believing that the stream has ended, and instead packs missing samples with zeros.  

Even if this fix worked, it would leave gaps and crackles in the input audio since the mixing buffer is not held back and will keep grabbing those few extra frames every cycle. We can get away with it if the mismatch between the mixing and the input_buffer is marginal and the timing of both are almost the same but for an insignificant number of frames.

This fix also doesn't handle the [the android stutter bug](https://github.com/godotengine/godot/issues/95120) where the input stops adding new samples so that when you turn the Microphone stream back on (or force it to remain on with this fix) the stream loops around the buffer endlessly like a broken CD player.  

It also doesn't handle the case where the mixing is slightly slower and falls behind the rate the buffer is filled until it is lapped by the input_position.

I believe the core problem is the expectation that the samples are being posted into the input buffer by the external microphone device at exactly the same rate that the Godot audio server consumes them.  This exact match only holds when Godot controls both ends of the pipe and can logically push the same number of samples into each bus that it pops at the other end.  

Otherwise the input and output rates are not locked and will inevitably drift over time.  These bugs are extremely hard to get because they happen over minutes on different systems, and everything is fine when you reset it.

Taking account of the primary purpose of listening to the microphone (ie for recording and sending over a network to another player), I have [a proposal](https://github.com/godotengine/godot-proposals/issues/11325) to access to this `AudioDriver.input_buffer` directly without invoking any part of the audio system.   Any slight mis-timing of the rates at which the input_buffer is filled will be handled with the jittering of the network traffic and the fact that this application does not assume that the clock rates of entirely different computers on either side of the world are going to match exactly.

File: servers/audio/audio_stream.cpp [hunk 1]
```diff
@@ -353,9 +353,6 @@ int AudioStreamPlaybackMicrophone::_mix_internal(AudioFrame *p_buffer, int p_fra
 
 				p_buffer[i] = AudioFrame(l, r);
 			} else {
-				if (mixed_frames == p_frames) {
-					mixed_frames = i;
-				}
 				p_buffer[i] = AudioFrame(0.0f, 0.0f);
```
Comment (lyuma) [inline servers/audio/audio_stream.cpp:356]: Depending on the amount of samples being underrun, it may be interesting to perform smearing rather than produce 0.0f samples. This won't fix longer underruns though unless you remember the DC offset, so it really depends on the nature of the buffer underrun. (and keeping a DC offset for a long time isn't really a good idea anyway).

You don't have to apply this change. It really depends on the cause / nature of the underrun. Just an idea.

```suggestion
				if (i == 0) {
					p_buffer[i] = AudioFrame(0.0f, 0.0f);
				} else {
					p_buffer[i] = p_buffer[i - 1];
				}
```

**Review by lyuma — APPROVED** [review]
Thanks @goatchurchprime for linking this. Looks good to me.

This mitigates one of the issues discussed in #105244 related to microphone quality. I think it's okay to merge as is, but I do have some ideas if you want to try them perhaps in a future PR:

It may be reasonable to add a warning log that we hit a buffer underrun on the microphone. A broken microphone might cause lots of log spam so how about a safe WARN_PRINT_ONCE for now:
```
WARN_PRINT_ONCE("Buffer underrun in AudioStreamPlaybackMicrophone.");
```

It might also be good to offer statistics on number of buffer underruns and overruns (should be 0 in an ideal world, but the world is not always ideal, and having data can help diagnose problems)

**Comment by lyuma** [comment]
I also just want to highlight that there was some discussion on PR #105244, and where some of the confusion comes from about correctness.

Essentially, what I learned recently is that, contrary to the first comments, this issue is *not* necessarily caused by threading: From what goatchurch explained to me, on Android, in some cases such as bluetooth, there is a possibility that the hardware device may use a different audio clock than the Godot audio server, causing some desync over time. That desync is what can eventually lead to buffer underrun (mitigated this PR) or overrun (ever-increasing delay).

The fact that the underrun can happen due to hardware or driver differences tells me that we should try our best to mitigate the worst case.

A pop is never a good thing, but in the case that something has gone wrong somewhere, it is better to have a pop than a completely broken application caused by ending the stream. This is why I now offer a different opinion from the original comments and think it is worth approving this as a bugfix.

This PR is not the end of the road in solving this issue: it is merely one bastion of addressing a larger problem.

**Comment by syntaxerror247** [comment]
I tested it on a Poco device running Android 15, and it does fix the issue as described. However, I encountered a few remaining problems: after stopping the recording once, I’m unable to turn the mic back on. The recording only captures some stuttering sounds and doesn’t record any input unless I restart the app and start recording again.

**Comment by syntaxerror247** [comment]
Microphone is not recording second time even without this PR, so I think it's fine to proceed with it for now - at least it resolves one of the issues.

Also, I haven’t been following this issue closely, and since @lyuma, who’s been tracking it, has already approved the PR, I’m good with moving forward.

**Review by syntaxerror247 — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by sjoerdev** [comment]
This fixed the issue of the microphone shutting of after a while. But it still doesnt fix the stuttering sound.

**Comment by Calinou** [comment]
> This fixed the issue of the microphone shutting of after a while. But it still doesnt fix the stuttering sound.

Please open a new issue with a minimal reproduction project attached.
