### PR TITLE
Make certain editor callbacks thread-safe

### LINKED ISSUE #77235: Crash on loading complex scene
### Godot version

master (92b7da9832f21314ca3c656bae9d1ffa31f6c614)

### System information

Windows - RTX 4070

### Issue description

Loading up a more complex project results in a crash in the threaded resource loader.

This issue happens during conversion of images and other resources on a freshly cloned project. It looks like the code is trying to open up one of the error messages but it is doing this from a thread while the code expects to be run on the main thread.

Note that this issue may be a result of another problem as it seems the conversion of various resources is failing. Once we fix the crash in relating the error we'll find the causing error.

image

### Steps to reproduce

Freshly clone a larger project such as XR Tools and import it into Godot.

### Minimal reproduction project

https://github.com/godotvr/godot-xr-tools

### PR DESCRIPTION
**Pull request by RandomShaper**
The current design goal for the editor API is that it's not meant to be thread-safe. However, certain callbacks can be called from contexts that shouldn't contain explicit thread awareness. Therefore, the way to go is make those callbacks thread-safe, which is what this PR does.

A bit of story:
- In #71670 we could affect a specific component since it is its own class.
- In #71280 we could keep the editor API thread-unsafe because the affected functions were always called through a "bridge" that allowed to keep both ends unaware of threading.

Fixes #77235,

### CODE REVIEW

**Review by stavolt — APPROVED** [review]
Looks good.

**Review by BastiaanOlij — APPROVED** [review]
This prevents the crash issues I was experiencing importing a larger project. Still having some runtime issues that may be thread based but not sure of the cause yet.

File: editor/editor_node.cpp [hunk 1]
```diff
@@ -6502,13 +6506,16 @@ static Node *_resource_get_edited_scene() {
 }
 
 void EditorNode::_print_handler(void *p_this, const String &p_string, bool p_error, bool p_rich) {
```
Comment (akien-mga) [inline editor/editor_node.cpp:6508]: It's no longer using `p_this`. What was it for in the first place since we have singleton access?

Comment (RandomShaper) [reply editor/editor_node.cpp:6508]: I think the prototype of print handler function was designed similarly to thread functions, in that they get an arbitrary user data pointer that the caller code can use for anything. There are some resource loader error callbacks I stripped their counterpart parameter from because no known use case needed it. However, in this case, I've decided to keep it since I thought in this case the "users" could be of very varied natures. That said, I didn't check if others actually need the parameter and we could consider a similar surgery if none do.

**Comment by akien-mga** [comment]
Thanks!
