### PR TITLE
[HTML5] Fix multi-touch input handling.

### LINKED ISSUE #54135: Mobile HTML5 multitouch isn't working properly
### Godot version

3.4

### System information

Windows 10, GLES2, GTX 1060

### Issue description

Multitouch seems to work on HTML5, as it detects the touch indexes (touch 0, 1, etc).
However, if there are multiple touches, and they both start dragging, it can only follow one, and temporarily sets the first touch to (0,0)?

Kinda weird, try the test project I have on itch.io to see what I mean.

It does keep track of the individual touches (if they're released and they're relative drag), but only one at a time.

Load up HTML project (on itch.io) and try to drag both left and right at the same time.

https://justyouraveragejosh.itch.io/multitouch

### Steps to reproduce

Here is a simplified version of my code:

	
```
var left_touched=[-1,Vector2()]
var right_touched=[-1,Vector2()]


func _input(event):
	
	if event is InputEventScreenDrag and event.relative.length_squared()<15000:
		if left_touched[0]==event.index:
			$Left.rect_position+=event.relative
			
		elif right_touched[0]==event.index:
			$Right.rect_position+=event.index
			
			
	if event is InputEventScreenTouch:
		if event.is_pressed() and event.index<2:
			if event.position.x>get_viewport().get_visible_rect().size.x*.5 :
				right_touched=[event.index,event.position]; 
			else:left_touched=[event.index,event.position]

		if !event.is_pressed():
			if event.index==right_touched[0]:
				right_touched[0]=-1
			elif event.index==left_touched[0]:
				left_touched[0]=-1
```

### Minimal reproduction project

[HTML_DUMMY_ZIP.zip](https://github.com/godotengine/godot/files/7400680/HTML_DUMMY_ZIP.zip)

### PR DESCRIPTION
**Pull request by Faless**
The code to populate the input data for WebAssembly was incorrectly overriding values when multiple touches were present due to wrong indexing.

Fixes #54135 .

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

File: platform/javascript/js/libs/library_godot_input.js [hunk 1]
```diff
@@ -424,9 +424,9 @@ const GodotInput = {
 			for (let i = 0; i < touches.length; i++) {
 				const touch = touches[i];
 				const pos = GodotInput.computePosition(touch, rect);
-				GodotRuntime.setHeapValue(coords + (i * 2), pos[0], 'double');
-				GodotRuntime.setHeapValue(coords + (i * 2 + 8), pos[1], 'double');
-				GodotRuntime.setHeapValue(ids + i, touch.identifier, 'i32');
+				GodotRuntime.setHeapValue(coords + (i * 2 * 8), pos[0], 'double');
+				GodotRuntime.setHeapValue(coords + (i * 2 * 8) + 8, pos[1], 'double');
```
Comment (akien-mga) [inline platform/javascript/js/libs/library_godot_input.js:428]: For the record, this could also have been:
```suggestion
				GodotRuntime.setHeapValue(coords + (i * 2) * 8, pos[0], 'double');
				GodotRuntime.setHeapValue(coords + (i * 2 + 1) * 8, pos[1], 'double');
```
to clarify that it's "index" * "size of double".
But it's also fine as is, it's mostly a matter of taste.

Comment (Faless) [reply platform/javascript/js/libs/library_godot_input.js]: I like your style :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.
