### PR TITLE
Fix LSP not returning expected localization for API docs.

### LINKED ISSUE #409: Add support for documentation in other languages
### Godot version

3.5.stable

### VS Code version

1.70.1

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Problem statement

There is only English documentation now, I hope to add support for documentation in other languages

### Proposed solution

Add support for documentation in other languages

### PR DESCRIPTION
**Pull request by the-loki**
The current engine's LSP does not handle translations according to the engine's settings when returning document-related content, and now translates symbol-related information during the LSP's initialization process. (In PR #104062 , the translation is done when the document is loaded by modifying DocTools class, but this solution may have other effects, so we do translate in the LSP now.)

before:
before

after:
after

_Bugsquad edit: Fixes godotengine/godot-vscode-plugin#409_

### CODE REVIEW

**Review by HolonProduction — APPROVED** [review]
Tested locally and works. Code looks good to me.

Only thing worth noting: the last dev release added support for changing the editor language on the fly. This PR does not yet support that, it might be worth recalculating the cache when the `NOTIFICATION_TRANSLATION_CHANGED` is fired. (The entry point would be `GDScriptLanguageServer` which is a `Node` and receives notifications.) 

Not a dealbreaker for me, I'll let the production team decide whether this can be merged without support for dynamic language changing.

**Comment by the-loki** [comment]
> Tested locally and works. Code looks good to me.
> 
> Only thing worth noting: the last dev release added support for changing the editor language on the fly. This PR does not yet support that, it might be worth recalculating the cache when the `NOTIFICATION_TRANSLATION_CHANGED` is fired. (The entry point would be `GDScriptLanguageServer` which is a `Node` and receives notifications.)
> 
> Not a dealbreaker for me, I'll let the production team decide whether this can be merged without support for dynamic language changing.

Thanks. i'll try to impl it.

**Comment by HolonProduction** [comment]
If the vscode plugin treats this as stable and we have no way to signal an update, I guess there is no need to support it for the time being.

**Comment by the-loki** [comment]
> If the vscode plugin treats this as stable and we have no way to signal an update, I guess there is no need to support it for the time being.如果 vscode 插件将其视为稳定，而我们无法发出更新信号，我想暂时没有必要支持它。

Ok, thanks for the reply, let me know if there is anything else to maintain with this PR.

**Comment by the-loki** [comment]
> If the vscode plugin treats this as stable and we have no way to signal an update, I guess there is no need to support it for the time being.

Ok, thanks for the reply.

**Comment by AstroWYH** [comment]
@the-loki Does it support other language now?

**Comment by the-loki** [comment]
> @the-loki Does it support other language now?

If there is a translation of the corresponding text in the engine, then this PR can make the document in vscode appear in the correct language.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Comment by the-loki** [comment]
> Thanks! Congratulations on your first merged contribution! 🎉谢谢！祝贺您第一次合并贡献！🎉

thank.

**Comment by the-loki** [comment]
> Thanks! Congratulations on your first merged contribution! 🎉

Thanks.

File: modules/gdscript/language_server/gdscript_workspace.cpp [hunk 1]
```diff
@@ -279,6 +279,8 @@ ExtendGDScriptParser *GDScriptWorkspace::get_parse_result(const String &p_path)
 	return nullptr;
 }
 
+#define HANDLE_DOC(m_string) ((is_native ? DTR(m_string) : (m_string)).strip_edges())
```
Comment (dalexeev) [inline modules/gdscript/language_server/gdscript_workspace.cpp:282]: I'm late, but you forgot to add `#undef HANDLE_DOC` at the end. This is not required, but is recommended for good style and to prevent potential conflicts in SCU builds.
