### PR TITLE
GDScript: Add warning if non-`@tool` class extends `@tool` class

### LINKED ISSUE #754: Warn if script inheriting tool script isn't tool
**Describe the project you are working on:**
A complex metroidvania game.

**Describe the problem or limitation you are having in your project:**
I use tool scripts a lot in my project, because they are handy to update a scene based on exported properties. For a particular example, I have a class (with `class_name`) called NPC, which has basic interaction code and uses `tool` for updating sprite based on a variable. However the base NPC is little useful, so each NPC inherits it and provides own interaction code.

My problem is that the inheriting script must be a tool too. I've ran into this multiple times already - when you inherit tool script, the inheriting script must be explicitly tool too or it won't work as such. 

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I forgot to enable it few times and it caused some confusion, so I thought that a warning when inheriting script doesn't have `tool` keyword would be useful. This way instead of wasting few minutes trying to figure out why the script behaves weird, you could just see that you forgot to make it `tool`.

Alternatively we could make the inheriting script automatically be a tool.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
If a script inherits tool script, warn if it doesn't have `tool` keyword too. It would be a standard warning, so someone could disable it if their action was intended.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Inheriting tool scripts might not be a very common operation, but there's no way to work around my problem.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Impossible to make plugin for this.

### LINKED ISSUE #78174: @tool script extended without @tool does not show all exported vars in inspector
### Godot version

4.0.3

### System information

linux

### Issue description

Users of my plugin currently have to use the @tool annotation for any script otherwise they can't really use it. It feels pretty un-intuitive for them.

It seems that if one extends a @tool script, @exported variables display correctly in the inspector but variables exported using _get_property_list do not display at all in the inspector.

### Steps to reproduce

Try the minimal project below, you can see an exported var displayed and an other one not displayed.

### Minimal reproduction project

[test_tool_vars.zip](https://github.com/godotengine/godot/files/11733045/test_tool_vars.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #78174.
* Closes godotengine/godot-proposals#754.

### CODE REVIEW

**Comment by akien-mga** [comment]
I support the idea in principle.

One question we might want to ponder is whether there might be a valid use case for extending `@tool` scripts with a non-`@tool` script, to disable the tool-specific behavior in that script. E.g. for a script that has both in-game and in-editor logic, where the in-editor logic is only meant for debugging in a specific scene, but inherited scenes with their own extending scripts should not run it.

I guess this use case, if it exists, could be achieved the other way around by making the base script non `@tool` and extending it via a `@tool` script only where wanted.

**Comment by ajreckof** [comment]
Effectively I can see cases where the base script is a tool script and the extended should not. For example the base script can have some exported value that has a setter that needs to run but the current script has a lot of things happening on process which you don't want to run in the editor because of performance reasons. 
The workaround proposed by akien does not work because as of now if a script is marked as `@tool` even if the base class is not marked as tool it will be considered as such. 
This is still a fix for the issue but it feels more like a bandaid then a proper fix. I think a proper fix should aim to make it possible to have abas script that run in the editor while the script extending it is not i `@tool` mode

**Comment by Flavelius** [comment]
@notool or @disable_tool definitely makes more sense, because the base class explicitly expresses the intent to be a tool, and this explicit requirement shouln't be violatable by inheritors. It's the same reason that not all base class methods are virtual by default.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -409,6 +409,11 @@ Error GDScriptAnalyzer::resolve_class_inheritance(GDScriptParser::ClassNode *p_c
 				return err;
 			}
 
+			if (!parser->_is_tool && ext_parser->get_parser()->_is_tool) {
+				push_error(R"(The base class script has the "@tool" annotation, but this script does not have it.)", p_class);
+				return ERR_PARSE_ERROR;
+			}
+
```
Comment (adamscott) [inline modules/gdscript/gdscript_analyzer.cpp:416]:
```suggestion
			if (!parser->_is_tool && ext_parser->get_parser()->_is_tool) {
				push_warning(R"(The base class script has the "@tool" annotation, but this script does not have it.)", p_class);
				return ERR_PARSE_ERROR;
			}

```

As discussed in the GDScript team meeting, this should return a warning instead of an error.

**Comment by adamscott** [comment]
As discussed in the GDScript team meeting, instead of adding `@disable_tool` or `@notool`, we decided to go ahead with `@tool(false)` as annotations can take arguments. Technically, the first argument of tool would default to `true` if none is supplied.

**Comment by dalexeev** [comment]
> we decided to go ahead with `@tool(false)` as annotations can take arguments. Technically, the first argument of tool would default to `true` if none is supplied.

Autocompletion inserts empty parentheses when there are optional arguments. We could have added an exception, but I remembered that we already have an annotation for ignoring warnings, which is most likely the first thing the user will use by clicking the "Ignore" button in the warning bar. I don't think we need any other way than `@warning_ignore`.

File: modules/gdscript/gdscript_parser.cpp [hunk 2]
```diff
@@ -501,25 +501,58 @@ void GDScriptParser::end_statement(const String &p_context) {
...
 
+	/* clang-format off */
+#define PUSH_PENDING_ANNOTATIONS_TO_HEAD                 \
+	if (!annotation_stack.is_empty()) {                  \
+		for (AnnotationNode *annot : annotation_stack) { \
+			head->annotations.push_back(annot);          \
+		}                                                \
+		annotation_stack.clear();                        \
+	}
+	/* clang-format on */
```
Comment (dalexeev) [inline modules/gdscript/gdscript_parser.cpp:518]:
```suggestion
#define PUSH_PENDING_ANNOTATIONS_TO_HEAD                 \
	if (!annotation_stack.is_empty()) {                  \
		for (AnnotationNode * annot : annotation_stack) { \
			head->annotations.push_back(annot);          \
		}                                                \
		annotation_stack.clear();                        \
	}
```

**Review by Mickeon — COMMENTED** [review]
Documentation for the warning looks fine but I have a feel this PR is abandoned a bit?

**Review by Mickeon — APPROVED** [review]
I personally relate to the issues the warning would address (it used to be extremely painful figuring them out on my own), but it's worth questioning if this should be in 4.3 right now, in feature freeze.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!
