### PR TITLE
Fixed RigidBody stuttering when changing collision layer/mask

### LINKED ISSUE #32577: Area that repeatedly sets collision layer bit messes with gravity
**Godot version:** 3.1.1.devel.custom_build.cab4921

**OS/device including version:** Arch Linux (5.3.1-arch1-1-ARCH)

**Issue description:** Creating an Area that repeatedly sets the collision layer bit of the physics bodies inside it causes the affected bodies to ignore the effects of gravity. This happens even when invoking `b.set_collision_layer_bit(2, b.get_collision_layer_bit(2))`, which should do nothing.

**Steps to reproduce:**

- Create a 3D scene with an Area and a smaller RigidBody inside it.
- Attach the following script to the Area:
```
extends Area

func _physics_process(delta):
	for b in get_overlapping_bodies():
		# this should do nothing...
		b.set_collision_layer_bit(2, b.get_collision_layer_bit(2))
```
- Run the project.

**Minimal reproduction project:** Attached as a zip file.

[areaglitch.zip](https://github.com/godotengine/godot/files/3693839/areaglitch.zip)

Additional observations:

- Attaching this script to the RigidBody, although it similarly repeatedly sets the collision layer bit, appears to do nothing.
```
extends RigidBody

# Called when the node enters the scene tree for the first time.
func _integrate_forces(state):
	self.set_collision_layer_bit(2, self.get_collision_layer_bit(2))
```
- To get around using an Area, I instead tried using a Spatial that casts a collision shape into the physics server:
```
extends Spatial

onready var shape = BoxShape.new()
onready var query = PhysicsShapeQueryParameters.new()

func _ready():
	shape.extents = Vector3(5,5,5)
	query.set_shape(shape)
	query.collision_mask = 1
	
func _physics_process(delta):
	var space_rid = get_world().space
	var ss = PhysicsServer.space_get_direct_state(space_rid)
	var results = ss.intersect_shape(query)
	
	for r in results:
		r.collider.set_collision_layer_bit(2, true)
```
Again, this causes the RigidBody to ignore gravity.

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
- Changing collision layer/mask now only updates the broadphase proxy to avoid the velocity to be reset each time (also avoids unnecessary computations)
- No rigid body update at all when the collision layer/mask stays the same
- Same changes for Area for optimization purpose

Fixes #32577

### CODE REVIEW

File: modules/bullet/bullet_physics_server.cpp [hunk 1]
```diff
@@ -408,13 +408,19 @@ Transform BulletPhysicsServer::area_get_transform(RID p_area) const {
 void BulletPhysicsServer::area_set_collision_mask(RID p_area, uint32_t p_mask) {
 	AreaBullet *area = area_owner.get(p_area);
 	ERR_FAIL_COND(!area);
-	area->set_collision_mask(p_mask);
+
+	if (area->get_collision_mask() != p_mask) {
```
Comment (AndreaCatania) [inline modules/bullet/bullet_physics_server.cpp]: Can you please perform this operation inside the `set_collision_mask` function?

In this way if any other function change collision mask by calling the `area->set_collision_mask(p_mask);` directly, the same logic is applied.

File: modules/bullet/bullet_physics_server.cpp [hunk 2]
```diff
@@ -601,7 +607,10 @@ void BulletPhysicsServer::body_set_collision_layer(RID p_body, uint32_t p_layer)
 	RigidBodyBullet *body = rigid_body_owner.get(p_body);
 	ERR_FAIL_COND(!body);
 
-	body->set_collision_layer(p_layer);
+	if (body->get_collision_layer() != p_layer) {
+		body->set_collision_layer(p_layer);
+		body->set_activation_state(true);
```
Comment (AndreaCatania) [inline modules/bullet/bullet_physics_server.cpp]: Following the above advice, can you please put the `set_activation_state` inside the `set_collision_layer` ?

**Review by AndreaCatania — CHANGES_REQUESTED** [review]

**Comment by AndreaCatania** [comment]
Can you please submit a sample project to check this PR?

**Comment by pouleyKetchoupp** [comment]
@AndreaCatania Thanks for the review! I've pushed the changes you asked for.

Here's a sample project to test the changes, which is mostly based on the repro project from #32577.
[areatest.zip](https://github.com/godotengine/godot/files/3702384/areatest.zip)

You can set `test` property in the area script to 3 different modes:
- DynamicBody: press space to toggle the collision layer for the falling cube, on layer 2 it will fall through the static body under it.
- StaticBody: same but it changes the static body's collision layer.
- Area: toggles the collision layer of the area itself, and when detecting rigid bodies it forces them to have a velocity of 0.

**Comment by AndreaCatania** [comment]
It works! thanks for the improvement!

@akien-mga you can merge this

**Review by AndreaCatania — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
