### PR TITLE
Fix custom inertia in physics2d

### LINKED ISSUE #30838: set_inertia on RigidBody2D to greater than zero prevents set_mode from working correctly
**Godot version:**
3.1.1 stable official

**OS/device including version:**
Windows 10 Home

**Issue description:**
When using set_inertia on a RigidBody2D setting anything greater than zero prevents set_mode from working correctly.
Specifically: if in MODE_CHARACTER and set_mode(RigidBody2D.MODE_RIGID) is used the MODE flag changes to MODE_RIGID but the body continues to act as MODE_CHARACTER.
Note that by removing the first set_inertia instruction from the script (the one that sets inertia to a very small value >0) all then works fine.

**Steps to reproduce:**
Run the NODE2D scene in the attached project, press "down arrow" which should switch the RigidBody2D from Character to Rigid. The mode flag changes but the body`s behaviour does not. The body should start to rotate as torque is being applied.
You can check the current mode and inertia by pressing "Enter". Press 'Up Arrow" to switch back to rigid mode.

**Minimal reproduction project:**
[rigidbodybug.zip](https://github.com/godotengine/godot/files/3435819/rigidbodybug.zip)

### PR DESCRIPTION
**Pull request by Raphael2048**
1, set_inertia shouldn't check for >0, since a value <=0 means erasing custom inertia
2, Add a variable to save custom inertia
3, only update inertia when it's needed when change mode
4, reset angular velocity to 0 when switching to character mode
closes #30838

### CODE REVIEW

File: scene/2d/physics_body_2d.cpp [hunk 1]
```diff
@@ -594,7 +594,6 @@ real_t RigidBody2D::get_mass() const {
 
 void RigidBody2D::set_inertia(real_t p_inertia) {
 
-	ERR_FAIL_COND(p_inertia <= 0);
```
Comment (akien-mga) [inline scene/2d/physics_body_2d.cpp]: Does it make sense to set a negative inertia?

Comment (raphael10241024) [reply scene/2d/physics_body_2d.cpp]: According to this https://docs.godotengine.org/en/3.1/classes/class_rigidbody2d.html#class-rigidbody2d-property-inertia , a negative inertia means erasing user custom inertia and recalculate it.
Maybe we should use another param like `custom_inertia` to control it? If so, we can keep in same with setting custom gravity center in the future, since you can't set a "negative gravity center".

Comment (akien-mga) [reply scene/2d/physics_body_2d.cpp]: I think the "(or negative)" part of the documentation should simply be removed, setting it to 0 is sufficient for a way to erase the custom inertia.

Comment (raphael10241024) [reply scene/2d/physics_body_2d.cpp]: So how about adding a bool param `custom_inertia` to control it ?
If we add it, this will be same mechanism with `custom_gravity_center`(future feature) , 
you can't use a zero value meaning erase custom gravity center(zero means a custom gravity center at origin position).

Comment (akien-mga) [reply scene/2d/physics_body_2d.cpp]: Well I prefer not future proofing the API, we can do these changes if we do add a way to override the gravity center. Until this, it's better to keep the API unchanged in this PR and just fix the issue.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
