### PR TITLE
Fix unlimited project option ranges that could cause crashes.

### LINKED ISSUE #84727: Some setting values without limit could cause crash
### Godot version

v4.2.beta5.official [4c96e9676]

### System information

Godot v4.2.beta5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 5500 XT (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD FX(tm)-6300 Six-Core Processor (6 Threads)

### Issue description

There's a number of project settings, that has no limit for possible values range. In some cases, setting invalid value (mostly zero or negative) could cause editor crash on project open or game crash on start.
I suppose such limitation should be added (also it was in 3.x at least for some of them).

I created a commit that fixes this issue by adding PROPERTY_HINT_RANGE to forbid negative or zero values. But using PROPERTY_HINT_RANGE also has highest value limit, which is unknown to me without knowledge of engine internals. Because of that, I created this issue report instead of PR, to discuss values correctness. Please take a look:
https://github.com/godotengine/godot/compare/master...gshadows:godot:fix_options_range

Example of possible values is on image below. I found this bug when actually set some of such options to -1 accidentally.
Example of invalid values

### Steps to reproduce

1. Create empty project or open existing (assuming you have backup).
2. Open project settings and enable Advanced Settings (not all affected settings are advanced, this is just a good example).
3. Select "Reflections" and set any values as on image above, for example roughness layers = -1.
4. After project save and attempt to re-open, editor will crash.
5. The only way to recover is manual edit of project.godot (or restore from backup/vcs).

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by gshadows**
This PR fixes #84727 - missed limits for some project options could cause editor or game crash.

### CODE REVIEW

File: servers/rendering_server.cpp [hunk 1]
```diff
@@ -3513,7 +3513,7 @@ void RenderingServer::init() {
 	GLOBAL_DEF(PropertyInfo(Variant::INT, "rendering/textures/decals/filter", PROPERTY_HINT_ENUM, "Nearest (Fast),Linear (Fast),Nearest Mipmap (Fast),Linear Mipmap (Fast),Nearest Mipmap Anisotropic (Average),Linear Mipmap Anisotropic (Average)"), DECAL_FILTER_LINEAR_MIPMAPS);
 	GLOBAL_DEF(PropertyInfo(Variant::INT, "rendering/textures/light_projectors/filter", PROPERTY_HINT_ENUM, "Nearest (Fast),Linear (Fast),Nearest Mipmap (Fast),Linear Mipmap (Fast),Nearest Mipmap Anisotropic (Average),Linear Mipmap Anisotropic (Average)"), LIGHT_PROJECTOR_FILTER_LINEAR_MIPMAPS);
 
-	GLOBAL_DEF_RST("rendering/occlusion_culling/occlusion_rays_per_thread", 512);
+	GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "rendering/occlusion_culling/occlusion_rays_per_thread", PROPERTY_HINT_RANGE, "1,2048,1,or_greater"), 512);
```
Comment (AThousandShips) [inline servers/rendering_server.cpp:3516]: Unsure if this should be `or_greater`

File: servers/audio_server.cpp [hunk 2]
```diff
@@ -199,8 +199,8 @@ int AudioDriverManager::get_driver_count() {
 
 void AudioDriverManager::initialize(int p_driver) {
 	GLOBAL_DEF_RST("audio/driver/enable_input", false);
-	GLOBAL_DEF_RST("audio/driver/mix_rate", DEFAULT_MIX_RATE);
-	GLOBAL_DEF_RST("audio/driver/mix_rate.web", 0); // Safer default output_latency for web (use browser default).
+	GLOBAL_DEF_RST(PropertyInfo(Variant::INT, "audio/driver/mix_rate", PROPERTY_HINT_RANGE, "0,192000,1,or_greater,suffix:Hz"), DEFAULT_MIX_RATE);
```
Comment (AThousandShips) [inline servers/audio_server.cpp:202]: Is zero safe here? We do division by it in some places

Comment (gshadows) [reply servers/audio_server.cpp:202]: I've searched sources for this variable access and found that mix_rate = 0 means "use default". This is used for "mix_rate.web" for example. I didn't found other access to this option, at least with full path "audio/driver/mix_rate"

Here it is in "audio_server.cpp":
```cpp
int AudioDriver::_get_configured_mix_rate() {
	StringName audio_driver_setting = "audio/driver/mix_rate";
	int mix_rate = GLOBAL_GET(audio_driver_setting);

	// In the case of invalid mix rate, let's default to a sensible value..
	if (mix_rate <= 0) {
		WARN_PRINT(vformat("Invalid mix rate of %d, consider reassigning setting \'%s\'. \nDefaulting mix rate to value %d.",
				mix_rate, audio_driver_setting, AudioDriverManager::DEFAULT_MIX_RATE));
		mix_rate = AudioDriverManager::DEFAULT_MIX_RATE;
	}

	return mix_rate;
}
```

Comment (AThousandShips) [reply servers/audio_server.cpp:202]: As I linked too 🙂, however it's treated as an error and will show a warning, so unsure how correct it is

File: servers/rendering_server.cpp (hunk 1 above)
Comment (gshadows) [reply servers/rendering_server.cpp:3516]: I'm not experienced in engine internals. That's why I was unsure about what exact values should be an upper limits. Initially I added `or_greater` almost everywhere because assumed it safer then creating limit and then find that someone actually used larger value.
If you know exact upper limit values or could confirm here 2048 is good top value I will remove `or_greater`. Thanks!

Comment (AThousandShips) [reply servers/rendering_server.cpp:3516]: I have no clue, was just pointing out since it seems like a pretty performance critical thing given occlusion and threads

File: servers/audio_server.cpp (hunk 2 above)
Comment (gshadows) [reply servers/audio_server.cpp:202]: It seems you're right, this function was introduced as a bug fix for a crash when mix_rate is not valid: [commit](https://github.com/godotengine/godot/commit/5a08091168782a924cd3a23baf31c5cd4cd63906).

For web build it seems that it supposed to rely on zero default value (from [this](https://github.com/godotengine/godot/commit/d187bb4e11182ee3edbc0008dba5762148bc530d) commit) to fallback to browser defaults (in [library_godot_audio.js](https://github.com/godotengine/godot/blob/d443f127ef1db9fb2fe623ba1c17ded5402aff10/platform/web/js/libs/library_godot_audio.js#L41)), but if I understood correctly it still uses same `_get_configured_mix_rate()` method to obtain this value. If this true, then it should never get zero and also should always complain "Invalid mix rate" in console. But I never used Godot for web so can't check.

Comment (Calinou) [reply servers/audio_server.cpp:202]: The warning should be silenced on the Web platform, as a mix rate project setting of `0` is valid there.

Comment (gshadows) [reply servers/audio_server.cpp]: Done. For non-web limit now starts from 1.

Comment (Calinou) [reply servers/audio_server.cpp]: > Done. For non-web limit now starts from 1.

The lowest mix rate could probably be set to 11025 Hz, as I don't think lower mix rates will work correctly at all.

Comment (gshadows) [reply servers/audio_server.cpp]: > The lowest mix rate hint could probably be set to 11025 Hz, as I don't think lower mix rates will work correctly at all.

Well, talking about this, will non standard rates work at all? I just tried few experiments and it seems that rates below 11025 has no difference with 11025. I've tried 8000, 4000, 1000 and 1. May be it is my audio card specific, or just it always rounded to nearest 11024 * N and 8000 * N values (I used 8000 because Audacity lists it as an one of standard rates and also 48k, 96k are multiplies of it).

**Comment by gshadows** [comment]
Yes, sorry, I somehow messed rebase but hope now I restored as it should be.
So, could you please suggest if I can do something useful for this PR or I should wait? Except keeping it up to date with upstream of course. Just to be sure we don't wait each other in deadlock :)

**Comment by AThousandShips** [comment]
Needs some feedback, and we're in feature freeze so will be getting more focus once 4.2 is released, if people are busy

File: servers/audio_server.cpp (hunk 2 above)
Comment (Calinou) [reply servers/audio_server.cpp]: > Well, talking about this, will non standard rates work at all?

It depends on the audio driver, but I'd assume rates lower than 11025 Hz won't work on all platforms Godot supports.

**Review by Calinou — APPROVED** [review]

File: servers/rendering_server.cpp (hunk 1 above)
Comment (akien-mga) [reply servers/rendering_server.cpp:3529]: Poke @clayjohn

Comment (clayjohn) [reply servers/rendering_server.cpp:3529]: This value gets clamped internally between `viewport_size.x * viewport_size.y / (32 * 32)` and `viewport_size.x * viewport_size.y / (2 * 2)` after being multiplied by the number of threads. For a 1080x1920 screen with a CPU that supports 8 threads, the theoretical min is 254 and the theoretical max is 64,800.

For a 32 thread machine, it becomes 64 and 16,200. 

With a 4K monitor, the theoretical limits are much higher (with 8 threads, min is 1013, max is 259,200)

Accordingly, it makes sense to use `or_greater`

**Comment by akien-mga** [comment]
Thanks!
