### PR TITLE
Small fixes, mostly duplicated code

### LINKED ISSUE #27672: Code duplication bugs raised by static analyser
3.1 c2c11fc063e723c41

Errors and warnings was found by PVS-Studio

1. platform/x11/os_x11.cpp:1168: błąd: V501 There are identical sub-expressions to the left and to the right of the '||' operator: xdpi || xdpi

2. modules/gdnative/videodecoder/video_stream_gdnative.cpp:64: błąd: V595 The 'file' pointer was utilized before it was verified against nullptr. Check lines: 64, 65.
		
3. modules/gdscript/gdscript_editor.cpp:3001: ostrzeżenie: V1004 The 'base_type.class_type' pointer was used unsafely after it was verified against nullptr. Check lines: 2969, 3001.

4. modules/gdscript/gdscript_tokenizer.cpp:897: ostrzeżenie: V560 A part of conditional expression is always false: hexa_found.

5. modules/recast/navigation_mesh_editor_plugin.cpp:68: błąd: V595 The 'node' pointer was utilized before it was verified against nullptr. Check lines: 68, 70.

6. drivers/gles3/rasterizer_scene_gles3.cpp:1064: ostrzeżenie: V547 Expression 'gipd' is always true.

7. thirdparty/b2d_convexdecomp/b2Polygon.cpp:180: ostrzeżenie: V560 A part of conditional expression is always false: newNVertices == 0.

Checking if newNVertices == 0 happens a little before
(I forgot that this is thirdparty, but I won't destroy my task numbers)

8. drivers/gles2/rasterizer_scene_gles2.cpp:483: ostrzeżenie: V519 The 'rpi->last_pass' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 479, 483.

9. platform/android/export/export.cpp:1926: ostrzeżenie: V547 Expression 'err' is always false.

10. editor/inspector_dock.cpp:133: ostrzeżenie: V547 Expression 'current' is always true.

11. editor/collada/collada.cpp:2258: błąd: V547 Expression 'node->type != Node::TYPE_JOINT' is always false.

12. editor/scene_tree_dock.cpp:815: ostrzeżenie: V571 Recurring check. The 'node' condition was already verified in line 814.

13. editor/spatial_editor_gizmos.cpp:327: ostrzeżenie: V547 Expression '!spatial_node' is always false.

14. editor/import/editor_import_collada.cpp:1617: ostrzeżenie: V547 Expression 'xform_idx == - 1' is always false.

15. editor/plugins/animation_tree_player_editor_plugin.cpp:838: ostrzeżenie: V592 The expression was enclosed by parentheses twice: ((expression)). One pair of parentheses is unnecessary or misprint is present.

16. editor/plugins/canvas_item_editor_plugin.cpp:1850: ostrzeżenie: V560 A part of conditional expression is always true: (drag_type == DRAG_MOVE).

17. scene/main/http_request.cpp:289: ostrzeżenie: V560 A part of conditional expression is always true: got_response.

18. scene/gui/base_button.cpp:62: ostrzeżenie: V560 A part of conditional expression is always false: status.disabled.

19. scene/gui/popup_menu.cpp:242: ostrzeżenie: V560 A part of conditional expression is always false: i < 0.

20. scene/gui/rich_text_label.cpp:1999: ostrzeżenie: V560 A part of conditional expression is always true: selection.enabled.

21. scene/gui/tabs.cpp:582: ostrzeżenie: V560 A part of conditional expression is always false: i == current.

22. scene/gui/tree.cpp:3933: ostrzeżenie: V519 The 'cache.hover_index' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 3927, 3933.

23. scene/3d/physics_body.cpp:1208: ostrzeżenie: V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 1204, 1208.
and
scene/2d/physics_body_2d.cpp:1280: ostrzeżenie: V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 1276, 1280.

24. scene/resources/curve.cpp:271: ostrzeżenie: V571 Recurring check. The 'i + 1 < _points.size()' condition was already verified in line 270.

25.  servers/physics/space_sw.cpp:354: ostrzeżenie: V547 Expression 'p_result_max > 0' is always true.
servers/physics_2d/space_2d_sw.cpp:336: ostrzeżenie: V547 Expression 'p_result_max > 0' is always true.
and
servers/physics_2d/space_2d_sw.cpp:356: ostrzeżenie: V560 A part of conditional expression is always false: p_result_max == 0.

26. servers/physics_2d/shape_2d_sw.cpp:589: ostrzeżenie: V728 An excessive check can be simplified. The '(A && !B) || (!A && B)' expression is equivalent to the 'bool(A) != bool(B)' expression.

27. servers/audio/audio_rb_resampler.cpp:204: ostrzeżenie: V547 Expression 'rb' is always true.

28.  servers/visual/visual_server_scene.cpp:1867: ostrzeżenie: V560 A part of conditional expression is always true: ins->visible.
and
servers/visual/visual_server_scene.cpp:1884: ostrzeżenie: V560 A part of conditional expression is always true: ins->visible.
and
servers/visual/visual_server_scene.cpp:1884: ostrzeżenie: V571 Recurring check. The 'ins->visible' condition was already verified in line 1882.
and
servers/visual/visual_server_scene.cpp:1867: ostrzeżenie: V571 Recurring check. The 'ins->visible' condition was already verified in line 1865.

29. servers/audio/effects/audio_effect_record.cpp:69: ostrzeżenie: V560 A part of conditional expression is always true: is_recording.

### PR DESCRIPTION
**Pull request by qarmin**
This PR just remove duplicated code or checking.
Should not broke anything

Fix #27672

### CODE REVIEW

File: scene/gui/tabs.cpp [hunk 1]
```diff
@@ -579,7 +579,7 @@ void Tabs::_update_cache() {
 					slen -= tabs[i].icon->get_width();
 					slen -= get_constant("hseparation");
 				}
-				if (cb_displaypolicy == CLOSE_BUTTON_SHOW_ALWAYS || (cb_displaypolicy == CLOSE_BUTTON_SHOW_ACTIVE_ONLY && i == current)) {
+				if (cb_displaypolicy == CLOSE_BUTTON_SHOW_ALWAYS || (cb_displaypolicy == CLOSE_BUTTON_SHOW_ACTIVE_ONLY)) {
```
Comment (akien-mga) [inline scene/gui/tabs.cpp]: That might introduce a bug, the previous condition was always false, but now it's going to add a close button on all tabs if the policy is `CLOSE_BUTTON_SHOW_ACTIVE_ONLY`. CC @StraToN

**Review by akien-mga — APPROVED** [review]
All good apart from one change.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.
