### PR TITLE
Fix cannot input Chinese after restarting the input method on X11

### LINKED ISSUE #103748: Restarting the input method while the engine is running will result in an inability to input Chinese
### Tested versions

- Reproducible in: master [134da3749], v4.4.stable.official [4c311cbee]

### System information

Godot v4.4.stable - Linux Mint 22.1 (Xia) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.183.01) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 threads)

### Issue description

The input method I use occasionally encounters problems when typing and switching between Chinese and English input. I usually restart the input method to make it work normally.

But after restarting, Godot cannot detect that the input method is available again. This results in being unable to input Chinese until Godot is restarted. No problem with English input.

After restarting the input method, you will receive the following warning:

```
WARNING: Input method stopped
     at: _xim_destroy_callback (platform/linuxbsd/x11/display_server_x11.cpp:4138)
```

Whenever you open a window or popup, you will receive the following warning:

```
WARNING: XCreateIC couldn't create wd.xic
     at: _create_window (platform/linuxbsd/x11/display_server_x11.cpp:6308)
```

https://github.com/user-attachments/assets/2a0dba77-9900-414b-a195-bf1be4cf8b04

### Steps to reproduce

1. Run the editor;
2. Restart the input method, you will get a warning;
3. Hover on a control and wait for a pop-up window, you will get another warning;
4. Switch to Chinese input, can't switch.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
Register a callback via `XRegisterIMInstantiateCallback()` to detect whether the input method is available again.

Fix #103748.

https://github.com/user-attachments/assets/6f43fe8a-4283-427f-b812-566ef01013cf

### CODE REVIEW

**Review by timothyqiu — APPROVED** [review]
I haven't checked the code, but after applying this patch, I can indeed continue to input as normal after restarting the IME (fcitx5).

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 1]
```diff
@@ -6711,42 +6763,9 @@ DisplayServerX11::DisplayServerX11(const String &p_rendering_driver, WindowMode
...
-				}
-
-				xim_style = _get_best_xim_style(xim_style, style);
-			}
-
-			XFree(xim_styles);
-		}
-		XFree(imvalret);
+	if (!XRegisterIMInstantiateCallback(x11_display, nullptr, nullptr, nullptr, (::XIDProc)(_xim_instantiate_callback), (::XPointer)this)) {
+		WARN_PRINT("Error register XIM instantiate callback");
```
Comment (akien-mga) [inline platform/linuxbsd/x11/display_server_x11.cpp:6767]: Normally we'd end warnings with a period but none of the other warnings in this code seem to follow that convention, so I think it's fine to keep it consistent by not having a period (or we could add one to all warnings here).
```suggestion
		WARN_PRINT("Error registering XIM instantiate callback");
```

Comment (Rindbee) [reply platform/linuxbsd/x11/display_server_x11.cpp]: Thanks for the suggestion, added a period to all warnings.

**Review by bruvzg — APPROVED** [review]
Seems to be working fine.

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 2]
```diff
@@ -4143,7 +4143,7 @@ void DisplayServerX11::_xim_preedit_caret_callback(::XIM xim, ::XPointer client_
 
 void DisplayServerX11::_xim_destroy_callback(::XIM im, ::XPointer client_data,
 		::XPointer call_data) {
-	WARN_PRINT("Input method stopped");
+	WARN_PRINT("Input method stopped.");
```
[the remark this answers is not in the document]
Comment (Rindbee) [reply platform/linuxbsd/x11/display_server_x11.cpp]: Thanks for your suggestion, it has been removed.

**Comment by Repiteo** [comment]
Thanks!
