### PR TITLE
Fix GodotFetch glue code for null response bodies

### LINKED ISSUE #76825: HTTPRequest fails HEAD mode requests in Chrome 113
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

Chrome Version 113.0.5672.64 (Official Build) (64-bit), Microsoft Edge Version 113.0.1774.35 (Official build) (64-bit)

### Issue description

After Chromium 113, http requests with the HEAD method returns a response with an null body. This results in a TypeError in html5 exports, which causes HTTPRequest nodes to return a RESULT_CONNECTION_ERROR  with a response code of 0. So far this affects all Chromium browsers, Firefox and Safari have not been affected (based on my limited testing). I suspect the problem to affect the HTTPClient node as well, but I have not tested that yet.

**TypeError and Variables returned from 'request_completed' signal**
image

**Response object with body being `null` in Chrome 113**
image
**Response object in Firefox and older Chromium Browsers**
image

I believe the js error is caused by this bit of code in the .js export:
image

But re-writing that bit so that obj.reader is `null`, `undefined` or `new ReadableStream().getReader()` only suppresses the error and does not solve the problem.

### Steps to reproduce

1. Create a HTTPRequest node
2. Make a (valid) request with the HEAD method.
3. Export the project to HTML5
4. Run the project in any Chromium browser based on Chromium 113

### Minimal reproduction project

[HTTPRequestMRP.zip](https://github.com/godotengine/godot/files/11418745/HTTPRequestMRP.zip)

### PR DESCRIPTION
**Pull request by pandinocoder**
Fixes #76825 

The [spec says that `body` can be `null`](https://fetch.spec.whatwg.org/#body-mixin) [for fetch responses](https://fetch.spec.whatwg.org/#responses) (in the event of requests that should have no body, like HEAD requests) and Firefox adheres to it which results in request failure for HEAD requests on Firefox for web exports.

This fix addresses that by treating a `null` body as an "empty" body (without using a polyfill) and avoids changing the request lifecycle as much as possible.

Minimal reproduction project: [mrp-gh76825.zip](https://github.com/user-attachments/files/17481158/mrp-gh76825.zip)

### CODE REVIEW

File: platform/web/js/libs/library_godot_fetch.js [hunk 1]
```diff
@@ -159,7 +167,10 @@ const GodotFetch = {
 		if (!obj.response) {
 			return 0;
 		}
-		if (obj.reader) {
+		// If the reader is nullish, but there is no body, and the request is not marked as done,
+		// the same status should be returned as though the request is currently being read
+		// so that the proper lifecycle closure can be handled in read()
+		if (obj.reader || (obj.response.body === null && !obj.done)) {
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_fetch.js:173]: Added a period, and changed the check from `===` to `==`.

```suggestion
		// If the reader is nullish, but there is no body, and the request is not marked as done,
		// the same status should be returned as though the request is currently being read
		// so that the proper lifecycle closure can be handled in `read()`.
		if (obj.reader || (obj.response.body == null && !obj.done)) {
```

File: platform/web/js/libs/library_godot_fetch.js [hunk 2]
```diff
@@ -121,6 +125,10 @@ const GodotFetch = {
 				}
 				obj.reading = true;
 				obj.reader.read().then(GodotFetch.onread.bind(null, id)).catch(GodotFetch.onerror.bind(null, id));
+			} else if (obj.reader === null && obj.response.body === null) {
+				// Emulate a stream closure to maintain the request lifecycle
+				obj.reading = true;
+				GodotFetch.onread(id, { value: undefined, done: true });
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_fetch.js:131]: Added a period and set the comparison to use `==` instead of the strict one (`===`).

```suggestion
			} else if (obj.reader == null && obj.response.body == null) {
				// Emulate a stream closure to maintain the request lifecycle.
				obj.reading = true;
				GodotFetch.onread(id, { value: undefined, done: true });
```

File: platform/web/js/libs/library_godot_fetch.js [hunk 3]
```diff
@@ -59,7 +59,11 @@ const GodotFetch = {
 			});
 			obj.status = response.status;
 			obj.response = response;
-			obj.reader = response.body.getReader();
+			// `body` can be null per spec (for example, in cases where the request method is HEAD)
+			// As of the time of writing, Chromium (127.0.6533.72) does not follow the spec but Firefox (131.0.3) does
+			// See GH-76825 (godot) for more information
+			// See Chromium revert (of the change to follow the spec): https://chromium.googlesource.com/chromium/src/+/135354b7bdb554cd03c913af7c90aceead03c4d4
+			obj.reader = response.body?.getReader() ?? null;
```
Comment (adamscott) [inline platform/web/js/libs/library_godot_fetch.js:66]: Added periods and removed the unnecessary `null` return.

```suggestion
			// `body` can be null per spec (for example, in cases where the request method is HEAD).
			// As of the time of writing, Chromium (127.0.6533.72) does not follow the spec but Firefox (131.0.3) does.
			// See godotengine/godot#76825 for more information.
			// See Chromium revert (of the change to follow the spec): 
			// https://chromium.googlesource.com/chromium/src/+/135354b7bdb554cd03c913af7c90aceead03c4d4
			obj.reader = response.body?.getReader();
```

**Review by adamscott — CHANGES_REQUESTED** [review]
Small changes (more nitpicks than real changes), but very good overall. Thanks!

**Comment by adamscott** [comment]
You can remove me from the commit! Keep ownership of it, really.

**Comment by lodicolo** [comment]
I updated the commit and also fixed the eslint error, and rebuilt the export locally and re-verified it on both my project as well as the MRP I provided.

Thanks for the review!

**Review by adamscott — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks, and congratulations on your first contribution! 🎉
