### PR TITLE
Send a focus-out notification when opening a Window Manager Popup

### LINKED ISSUE #59406: The focus is not released as expected
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Linux Mint 20.3, Vulkan (both), NVIDIA GeForce GTX 1050 Ti

### Issue description

The editor cannot switch panels and tabs after a period of use. Now I feel like I have found the reason, the popup context menu.

### Steps to reproduce

New/Open a project, and enter the editor. 

Right-click on a dock A (for example, the file system dock) to open the context menu A-popup. Then left-click in anywhere, A-popup will be hidden. 

After doing this several times, the mouse it may not interact with any other editor/dock anymore, the dock A locks the focus.

This lock will be unlocked when the entire editor loses the focus.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Sauermann**
fix #59406

Currently, when a Window Manager Popup Window is opened, the previously focused Window loses focus, but never receives a `NOTIFICATION_WM_WINDOW_FOCUS_OUT` notification.

This patch resolves this problem.

### CODE REVIEW

**Comment by novaplusplus** [comment]
I just compiled with this change myself (linux) and it does in fact fix the issue.

File: scene/main/window.cpp [hunk 1]
```diff
@@ -1101,6 +1101,14 @@ void Window::popup_centered_ratio(float p_ratio) {
 void Window::popup(const Rect2i &p_screen_rect) {
 	emit_signal(SNAME("about_to_popup"));
 
+	if (!_get_embedder()) {
```
Comment (bruvzg) [inline scene/main/window.cpp:1104]:
```suggestion
	if (!_get_embedder() && get_flag(FLAG_POPUP)) {
```

It should be necessary only when opening an unfocusable Popup window, the `popup` method can be used to open other windows as well, and in this case it will send two `NOTIFICATION_WM_WINDOW_FOCUS_OUT`.

Fix seems fine, but I have not fully tested it (seems to work on Linux and macOS, but I was not able to reproduce original issue).

Comment (Sauermann) [reply scene/main/window.cpp]: Thank you for pointing me to this flag. I updated the PR.

**Comment by lewiji** [comment]
Yes, this fixes the UI focus issues for me on Linux also! Thanks!

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
