### PR TITLE
Fix invalid DAP responses when content has non-ASCII content

### LINKED ISSUE #104902: Print Chinese character cause debug instance unexpectedly closed
### Tested versions

4.4.1-stable

### System information

Windows 11 24H2

### Issue description

Currently using vscode with dap to debug godot projects. (launch setting from godot docs: https://docs.godotengine.org/en/stable/tutorials/editor/external_editor.html#lsp-dap-support)
When trying to print debug infos in Chinese and debug find that the game instance closes unexpectedly.
I did a custom build to get more info from dap, found out that vscode send disconnect command and godot closes the instance.

Image.

After I disabled all prints, it worked fine.
I did a further test trying to make a mrp, but only found it's related to Chinese characters.

### Steps to reproduce

1. open the mrp, set a break point after print
2. press F5 to debug with dap

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/19561154/mrp.zip)

### PR DESCRIPTION
**Pull request by rsubtil**
Fixes #104902

When sending DAP responses, the code simultaneously used buffer size and string size for calculating how much data to send. For UTF-8 encoded data, these values can be different due to special characters. This resulted in the response being truncated, generating invalid JSON responses to clients.

### CODE REVIEW

File: editor/debugger/debug_adapter/debug_adapter_protocol.cpp [hunk 1]
```diff
@@ -116,12 +116,12 @@ Error DAPeer::send_data() {
...
 		}
-		String formatted_data = format_output(data);
+		const Vector<uint8_t> &formatted_data = format_output(data);
 
 		int data_sent = 0;
-		while (data_sent < formatted_data.length()) {
+		while (data_sent < formatted_data.size()) {
 			int curr_sent = 0;
-			Error err = connection->put_partial_data((const uint8_t *)formatted_data.utf8().get_data(), formatted_data.size() - data_sent - 1, curr_sent);
+			Error err = connection->put_partial_data(formatted_data.ptr(), formatted_data.size() - data_sent, curr_sent);
```
Comment (bruvzg) [inline editor/debugger/debug_adapter/debug_adapter_protocol.cpp:124]: I assume null termination is not necessary, since it had `-1` before.

Comment (bruvzg) [reply editor/debugger/debug_adapter/debug_adapter_protocol.cpp:124]: For the reference, the same code for GDScript do add it:

https://github.com/godotengine/godot/blob/1f56d96cf2c768c3844c68ccb504dfeee841ae15/modules/gdscript/language_server/gdscript_language_protocol.cpp#L107-L114

Comment (rsubtil) [reply editor/debugger/debug_adapter/debug_adapter_protocol.cpp]: Fixed; I did a "hack" to test this scenario, and it behaves as expected.
image
image
image

**Review by bruvzg — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
