### PR TITLE
[X11] Fallback to root window size, when Xinerama extension is available, but return zero screens.

### LINKED ISSUE #85886: Popup menus and tooltips are not working when no displays connected
### Tested versions

4.2.stable

### System information

Linux, X11

### Issue description

I'm connecting to my PC remotely via VNC, and since the physical display is off, the system thinks there are no displays connected. Godot complains about it:

```
platform/linuxbsd/x11/display_server_x11.cpp:1062 - Invalid screen index: 0(count: 0).
platform/linuxbsd/x11/display_server_x11.cpp:1133 - Index p_screen = 0 is out of bounds (screen_count = 0).
```

Most functions work fine, however I have noticed that pop-up menus and tooltips don't work. I suspect that the menus are 0x0 pixels in size and therefore not visible.

However, the X11 screen still exists even without display, and I think Godot should work with it correctly.

### Steps to reproduce

Unplug the display cable, I guess?

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/85886

### CODE REVIEW

File: platform/linuxbsd/x11/display_server_x11.cpp [hunk 1]
```diff
@@ -1068,25 +1069,29 @@ Rect2i DisplayServerX11::_screen_get_rect(int p_screen) const {
...
+			if (count > 0) {
+				// Check if screen is valid.
+				if (p_screen < count) {
+					rect.position.x = xsi[p_screen].x_org;
+					rect.position.y = xsi[p_screen].y_org;
+					rect.size.width = xsi[p_screen].width;
+					rect.size.height = xsi[p_screen].height;
+					found = true;
+				} else {
+					ERR_PRINT("Invalid screen index: " + itos(p_screen) + "(count: " + itos(count) + ").");
```
Comment (akien-mga) [inline platform/linuxbsd/x11/display_server_x11.cpp:1087]: While at it, let's fix the missing space.
```suggestion
					ERR_PRINT(vformat("Invalid screen index: %d (count: %d).", p_screen, count));
```
Same for the other occurrences below.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
