### PR TITLE
Enhance checks and user experience around tangent arrays in meshes.

### LINKED ISSUE #83236: Manually generated Normals now missing data (4.2 Beta1 regression)
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.22000 - Vulkan (Forward+) 

### Issue description

I wrote a bootleg subdivided plane mesh generation script in 4.2 dev 6 that pushes a generated ArrayMesh into ImporterMesh to return the decimated version. As the LODed version had some seriously stretched flat normals, notably on flat areas (my landscape is tiered), I manually calculated averaged normals and handled a special case for upwards facing normals.

This worked fine in 4.2 Dev 6:
image

Identical code run on 4.2 Beta 1 causes this:
image

Edit: Further note, normal maps 'appear' fine until they are enabled in a shader (see below)

### Steps to reproduce
Run Main.tscn
Hit "Gen" = On in the inspector (might want to reduce Thread count depending on your machine)
Witness:
image

Deselect "Normal Map" on Mat in the inspector and Witness again:
image

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/12902382/MRP.zip)

### LINKED ISSUE #83850: GPU Particles look different from 4.1.1 to 4.2
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.5.0 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

We use particles extensively throughout our project and after upgrading to 4.2 and running the project I noticed the particles all look different. It seems it may be something to do with the normal map and/or the opacity of the particles. The screenshots below illustrate the visual differences.
Screenshot 2023-10-23 at 12 16 22 PM
Screenshot 2023-10-23 at 12 15 53 PM

### Steps to reproduce

Run both repro projects in their respective versions of Godot to see the difference between the appearance of the particles.

### Minimal reproduction project

[particle-bug-4.1.1.zip](https://github.com/godotengine/godot/files/13073293/particle-bug-4.1.1.zip)
[particle-bug-4.2-beta2.zip](https://github.com/godotengine/godot/files/13073295/particle-bug-4.2-beta2.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/83236
Fixes: https://github.com/godotengine/godot/issues/83850

In both linked MRPs the user was attempting to read tangents in a shader from a mesh with no tangents. The behaviour in 4.1 was for Godot to supply a dummy tangent (1, 0, 0). That is no longer possible without a performance penalty (but it is possible see [here](https://github.com/clayjohn/godot/commit/0e44f0f6a85a43447b92fc105e802c326a2ba4e7)). 

Since it was never supported behaviour to read from non-existent tangents (see the strong warning in the docs for [normal_texture](https://docs.godotengine.org/en/latest/classes/class_basematerial3d.html#class-basematerial3d-property-normal-texture)) and the result of relying would typically look horrible. We decided not to bring back the previous behaviour and instead try to make the usage of tangents more intuitive and user-friendly. 

We do that with three things:
1. Ensure `ensure_tangents` option actually creates tangent array. Even if it is just a dummy array.

Previous, we gave up on generating a tangent array if there were no UVs in the mesh.

This ensures that most imported meshes have tangent arrays. It is how the "ensure tangents" option was intended to work and it aligns with the name. Users who don't want tangents can uncheck the option with no harm to their mesh. This is much preferable to the old behaviour as the tangent used will now actually be tangential to the normal.

3. Allow mesh to generate its own tangents when using compression. This allows users to compress meshes without tangents.

Even if no tangent array is used, we need tangents to compress the mesh and we have good performance savings when using mesh compression. So this is a fallback to ensure that meshes can be compressed, even if just using normals

5. Warn users if they are trying to read from tangents without providing tangents.

This is the needed for cases like https://github.com/godotengine/godot/issues/83236 where the user is generating their own mesh and is relying on normal mapping, but has forgotten to create tangents. This warning warns the user while pairing the material to a mesh (which only happens once). 

--------------

Taken together, these 3 things should ensure that most users can carry on without any changes. Some users will run into the warning and have to generate tangents. But the end result should be much better for everyone.

### CODE REVIEW

File: modules/gltf/gltf_document.cpp [hunk 1]
```diff
@@ -2797,9 +2797,26 @@ Error GLTFDocument::_parse_meshes(Ref<GLTFState> p_state) {
...
+			bool generate_tangents = p_state->force_generate_tangents && (primitive == Mesh::PRIMITIVE_TRIANGLES && !a.has("TANGENT") && a.has("NORMAL"));
+
+			if (generate_tangents && !a.has("TEXCOORD_0")) {
+				// If we don't have UVs we provide a dummy tangent array.
+				Vector<float> tangents;
+				tangents.resize(vertex_num * 4);
+				float *tangentsw = tangents.ptrw();
+
+				Vector<Vector3> normals = array[Mesh::ARRAY_NORMAL];
+				for (int i = 0; i < vertex_num; i++) {
```
Comment (akien-mga) [inline modules/gltf/gltf_document.cpp:2809]: Seems like we're already in a `for (i ...) { for (j ...) {` nested loop, so this overrides `i`.

File: servers/rendering_server.cpp [hunk 2]
```diff
@@ -524,7 +523,7 @@ Error RenderingServer::_surface_set_data(Array p_arrays, uint64_t p_format, uint
 									memcpy(&vw[p_offsets[ai] + i * p_vertex_stride], vector, sizeof(uint16_t) * 4);
 								}
 							}
-						} else { // PACKED_FLOAT64_ARRAY
+						} else if (tangent_type == Variant::PACKED_FLOAT32_ARRAY) {
```
Comment (akien-mga) [inline servers/rendering_server.cpp:526]: Duplicated condition, this is the same as the previous branch.

File: drivers/gles3/rasterizer_scene_gles3.cpp [hunk 3]
```diff
@@ -259,6 +259,11 @@ void RasterizerSceneGLES3::_geometry_instance_add_surface_with_material(Geometry
 	sdcache->sort.shader_id = p_shader_id;
 	sdcache->sort.geometry_id = p_mesh.get_local_index();
 	sdcache->sort.priority = p_material->priority;
+
+	GLES3::Mesh::Surface *s = reinterpret_cast<GLES3::Mesh::Surface *>(sdcache->surface);
+	if (p_material->shader_data->uses_tangent && !(s->format & RS::ARRAY_FORMAT_TANGENT)) {
+		WARN_PRINT_ED("Attempting to use a shader that requires tangents with a mesh that doesn't contain tangents. Ensure that meshes are imported with 'ensure_tangents' option. If creating your own meshes, ensure you used `ARRAY_TANGENT` (when using ArrayMesh) or `generate_tangents()` (when using SurfaceTool).");
```
[the remark this answers is not in the document]
Comment (clayjohn) [reply drivers/gles3/rasterizer_scene_gles3.cpp:265]: Updated and rephrased to remove an instance of "ensure"

**Review by akien-mga — APPROVED** [review]
Looks good to me from a cursory review.

File: editor/import/resource_importer_obj.cpp [hunk 4]
```diff
@@ -327,6 +327,17 @@ static Error _parse_obj(const String &p_path, List<Ref<Mesh>> &r_meshes, bool p_
 						}
 						ERR_FAIL_INDEX_V(norm, normals.size(), ERR_FILE_CORRUPT);
 						surf_tool->set_normal(normals[norm]);
+						if (generate_tangents && !uvs.size()) {
```
Comment (AThousandShips) [inline editor/import/resource_importer_obj.cpp:330]:
```suggestion
						if (generate_tangents && uvs.is_empty()) {
```

File: editor/import/resource_importer_obj.cpp [hunk 5]
```diff
@@ -327,6 +327,17 @@ static Error _parse_obj(const String &p_path, List<Ref<Mesh>> &r_meshes, bool p_
...
+							// We can't generate tangents without UVs, so create dummy tangents.
+							Vector3 tan = Vector3(0.0, 1.0, 0.0).cross(normals[norm]);
+							surf_tool->set_tangent(Plane(tan.x, tan.y, tan.z, 1.0));
+						}
+					} else {
+						// No normals, use a dummy normal since normals will be generated.
+						if (generate_tangents && !uvs.size()) {
```
Comment (AThousandShips) [inline editor/import/resource_importer_obj.cpp:337]:
```suggestion
						if (generate_tangents && uvs.is_empty()) {
```

File: editor/import/resource_importer_obj.cpp (hunk 4 above)
Comment (clayjohn) [reply editor/import/resource_importer_obj.cpp]: added locally!

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
