### PR TITLE
PathFollow3D parallel transport frame reliability improvements

### LINKED ISSUE #3713: PathFollow 3D erratic rotations / wobbling / twitching
The object following pathfollow offset gets weird and erratic rotations but only on the first loop/lap. Tested on beta and RC 2.0 on linux systems.

Simple test inluded to confirm the issue.
[followcurvetest.zip](https://github.com/godotengine/godot/files/130461/followcurvetest.zip)

### LINKED ISSUE #27137: Path (3D) seems to make a wrong rotation
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64

**Issue description:**
I did a Path / Pathfollow (by GdScript)  with a form more or less equal to this (a capsule):
image

The coordinates in the code are:
```
	var p = $Path.curve
	# right curve
	p.add_point(Vector3(0, 0.35, 0), Vector3(0, 0, 0), Vector3(0, 0, 0))
	p.add_point(Vector3(0.35, 0, 0), Vector3(0, 0.35, 0), Vector3(0, -0.35, 0))
	p.add_point(Vector3(0, -0.35, 0), Vector3(0, 0, 0), Vector3(0, 0, 0))
	
	# left curve
	p.add_point(Vector3(-dist_eixos, -0.35, 0), Vector3(0, 0, 0), Vector3(0, 0, 0))
	p.add_point(Vector3(-dist_eixos - 0.35, 0, 0), Vector3(0, -0.35, 0), Vector3(0, 0.35, 0))
	p.add_point(Vector3(-dist_eixos, 0.35, 0), Vector3(0, 0, 0), Vector3(0, 0, 0))
	
	#close path
	p.add_point(Vector3(0, 0.35, 0), Vector3(0, 0, 0), Vector3(0, 0, 0))
```

I did a mesh like a tile to follow the Path. 0 rotation.
However, the mesh is following the Path with a sligth rotation.

**Steps to reproduce:**

Run the Scene on the attached project 

**Minimal reproduction project:**
[path.zip](https://github.com/godotengine/godot/files/2974399/path.zip)

### LINKED ISSUE #48864: PathFollow rotation inconsistent when Path contains control points in XYZ rotation mode
similar (not exactly the same) as #13434 and #3713

**Godot version:**

Godot Engine v3.3.stable.official - https://godotengine.org

**OS/device including version:**

OpenGL ES 3.0 Renderer: GeForce RTX 2060 with Max-Q Design/PCIe/SSE2

**Issue description:**

When changing offset (or unit_offset) in PathFollow when the Path.curve has control points it (randomly?) changes the rotation of the PathFollow node. 

sometimes the change is marginal. other times it can be as much as +-30 degrees. It also goes in both positive and negative directions. 

This issue is completely alleviated when the rotation mode is set to oriented as opposed to XYZ

**Steps to reproduce:**
create a Spatial. 
add a Path child
create 2+ points
add a PathFollow child 
grab the offset slider and wiggle it around as wildly as you can.

you should see the translation change, but the rotation stay constant.

go back to the path and shift drag one of the points (add control points)

go back to the PathFollow and jiggle the offset slider. 

Transform.rotation_degrees of PathFollow will not return to Vector3()

**Minimal reproduction project:**

[PathFollowBug.zip](https://github.com/godotengine/godot/files/6511755/PathFollowBug.zip)

### PR DESCRIPTION
**Pull request by Klowner**
While looking through old bugs I noticed #3713 and it described behavior that I've encountered (and have been confused by) so I decided to look into it a bit. I left a pretty lengthy comment on that ticket describing my findings regarding potential shortcomings of the current implementation of the parallel transport frame algorithm.

I've tested these changes against the following bug tickets and it seems to be a solution (at least visually):
- #48864
- #27137

Memory requirements are identical as before, but this includes 2 additional calls to the associated curve's `interpolate_baked()`

Hopefully this is a beneficial change, any input is much appreciated!

Fixes #3713
Fixes #48864
Fixes #27137

### CODE REVIEW

File: scene/3d/path_3d.cpp [hunk 1]
```diff
@@ -303,24 +307,18 @@ void PathFollow3D::_bind_methods() {
...
+			p_offset = Math::fposmod(p_offset, path_length);
+		} else {
+			p_offset = CLAMP(p_offset, 0, path_length);
 		}
-
+		prev_offset = offset;
+		offset = p_offset;
 		_update_transform();
+	} else {
+		prev_offset = offset = p_offset;
```
Comment (akien-mga) [inline scene/3d/path_3d.cpp:321]: These should be each on their own line.

File: scene/3d/path_3d.h [hunk 2]
```diff
@@ -65,7 +65,7 @@ class PathFollow3D : public Node3D {
 
 private:
 	Path3D *path = nullptr;
-	real_t delta_offset = 0.0; // Change in offset since last _update_transform.
+	real_t prev_offset = 0.0; // Offset during the last _update_transform
```
Comment (akien-mga) [inline scene/3d/path_3d.h:68]: The dot at the end is preferred in our comment style.

**Comment by akien-mga** [comment]
To clarify, does this PR fix the three mentioned issues? If so you can use `Fixes #1234` in the PR description so that it's tracked automatically by GitHub to close the issues when the PR is merged.

CC @rburing @raulsntos who have been working on Path3D/PathFollow3D recently.

File: scene/3d/path_3d.cpp [hunk 3]
```diff
@@ -303,24 +307,19 @@ void PathFollow3D::_bind_methods() {
...
-
-	if (path) {
-		if (path->get_curve().is_valid()) {
-			real_t path_length = path->get_curve()->get_baked_length();
-
-			if (loop) {
-				offset = Math::fposmod(offset, path_length);
-				if (!Math::is_zero_approx(p_offset) && Math::is_zero_approx(offset)) {
-					offset = path_length;
-				}
```
Comment (rburing) [inline scene/3d/path_3d.cpp:317]: Why is this branch removed?

File: scene/3d/path_3d.cpp [hunk 4]
```diff
@@ -303,24 +307,19 @@ void PathFollow3D::_bind_methods() {
...
+		} else {
+			p_offset = CLAMP(p_offset, 0, path_length);
 		}
-
+		prev_offset = offset;
+		offset = p_offset;
 		_update_transform();
+	} else {
+		prev_offset = p_offset;
+		offset = p_offset;
```
Comment (rburing) [inline scene/3d/path_3d.cpp:322]: Why is this branch added?

**Comment by rburing** [comment]
Please [rebase](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#updating-your-branch).

**Comment by raulsntos** [comment]
I've tested this PR with the MRP from https://github.com/godotengine/godot/issues/3713#issuecomment-640725685 and it does seem to fix the orientation issue but the movement seems still a bit glitchy.

<details>
<summary>
<strong><tt>master</tt> at commit 5c79782c7</strong>
</summary>

https://user-images.githubusercontent.com/3903059/168943863-25236848-4edd-4dbd-93d5-2bc7c5a9c954.mp4

</details>

<details>
<summary>
<strong>This PR at commit 281cf5fb8</strong>
</summary>

https://user-images.githubusercontent.com/3903059/168943883-aa02754e-4864-4e28-ae7a-df66289bb532.mp4

</details>

Conceptually the change from `delta_offset` to `prev_offset` makes sense to me, but I'm by no means an expert in this area.

**Comment by raulsntos** [comment]
I see now. In your example I'm not getting jerky movements in either branch, but in master the orientation drifts and this PR fixes that. I agree that this PR improves the movement so I'd merge it, I'm only a bit worried that since this PR doesn't fix the issue completely we should probably not close them.

**Comment by Zireael07** [comment]
@Calinou: I'm thinking separate PR for that, though, this one has been held up for waay too long considering it fixes a serious path following problem.

**Comment by Calinou** [comment]
> @Calinou: I'm thinking separate PR for that, though, this one has been held up for waay too long considering it fixes a serious path following problem.

Indeed, this should be added in a separate PR.

File: scene/3d/path_3d.cpp (hunk 4 above)
Comment (Klowner) [reply scene/3d/path_3d.cpp]: I reorganized some of the conditional branching while narrowing down what was going on, but it looks like those changes were unnecessary so I've reverted much of the changes in that function. Thank you for pointing that out :+1:

**Review by Calinou — APPROVED** [review]

**Comment by Calinou** [comment]
It might be worth checking whether these changes are required in PathFollow2D as well.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
