### PR TITLE
Fix error list not being cleared

### LINKED ISSUE #52730: Errors in debugger aren't cleared on run
### Godot version

a1a8afa

### System information

W10

### Issue description

Seems like the Errors tab in the debugger isn't auto-cleared anymore. What's more interesting, the error count for Debugger tab does reset, so there is a mismatch between the number and the actual accumulated amount of errors:
image

### Steps to reproduce

1. Make some code with errors/warnings (very easy on master, you don't even need code lol)
2. Run
3. Run
4. Notice how the errors accumulated in the Debugger

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by rsubtil**
Fixes #52730

### CODE REVIEW

File: editor/debugger/script_editor_debugger.cpp [hunk 1]
```diff
@@ -884,6 +884,7 @@ void ScriptEditorDebugger::_clear_breakpoints() {
 }
 
 void ScriptEditorDebugger::start(Ref<RemoteDebuggerPeer> p_peer) {
+	error_tree->clear();
 	error_count = 0;
 	warning_count = 0;
```
Comment (akien-mga) [inline editor/debugger/script_editor_debugger.cpp:889]: Maybe call `_clear_errors_list()` instead?

Any idea when the regression started?

Comment (akien-mga) [reply editor/debugger/script_editor_debugger.cpp:889]: > Any idea when the regression started?

Seems the previous `error_tree->clear();` present in `3.x` was removed in cbc450c0e53dbfc31a30f5ebf37c51cee77cde5c, CC @Faless.

The fix in this PR seems fine, makes sense to me to clear on start.

Comment (Ev1lbl0w) [reply editor/debugger/script_editor_debugger.cpp:889]: Yeah, but since `_clear_errors_list()` runs a process loop at the end, I didn't use it to prevent any side-effects. I've tested with it now and seems to run fine, but I'll wait on Faless's input before pushing.

Comment (akien-mga) [reply editor/debugger/script_editor_debugger.cpp:889]: `_clear_errors_list()` is just this, so it's the same code no?
https://github.com/Ev1lbl0w/godot/blob/fix_debug_errors_not_clearing/editor/debugger/script_editor_debugger.cpp#L1401-L1405

Comment (Ev1lbl0w) [reply editor/debugger/script_editor_debugger.cpp:889]: Oh yeah, you're right; it changed after the refactoring and I didn't even bother to check it again :sweat_smile:

Yup it's safe then, so I'll change it

**Review by Faless — APPROVED** [review]
Looks great! Thanks!

**Comment by Faless** [comment]
Thanks!
