### PR TITLE
Always register the Smooth Trimesh Collision project setting

### LINKED ISSUE #58667: smooth_trimesh_collision missing in project settings
### Godot version

3.4.3

### System information

Linux, Debian 11 64 bit

### Issue description

I can't find the Smooth Trimesh Collision option in my project settings.

### Steps to reproduce

According to the documentation, it should be here
Screenshot from 2022-03-01 17-48-26

### Minimal reproduction project

[gammaball.zip](https://github.com/godotengine/godot/files/8165272/gammaball.zip)

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/58674.

This ensures the project setting never disappears from the editor, even if the current physics engine is GodotPhysics.

This also adds documentation for the Smooth Trimesh Collision project setting.

This closes https://github.com/godotengine/godot/issues/58667 and closes https://github.com/godotengine/godot/pull/42193 by superseding it.

### CODE REVIEW

File: core/config/project_settings.cpp [hunk 1]
```diff
@@ -1256,6 +1256,12 @@ ProjectSettings::ProjectSettings() {
 
 	GLOBAL_DEF("compression/formats/gzip/compression_level", Compression::gzip_level);
 	custom_prop_info["compression/formats/gzip/compression_level"] = PropertyInfo(Variant::INT, "compression/formats/gzip/compression_level", PROPERTY_HINT_RANGE, "-1,9,1");
+
+	// Required to make the project setting appear even if the physics engine is GodotPhysics,
+	// while also making it appear in the ProjectSettings class documentation.
+	// The setting is only relevant when using Bullet physics, but it should still
+	// appear in the project settings as documented.
+	GLOBAL_DEF("physics/3d/smooth_trimesh_collision", false);
```
Comment (akien-mga) [inline core/config/project_settings.cpp:1264]: There are a couple other `physics/` settings above, would be nice to keep them grouped. Maybe the comment can also be shortened a bit to reduce LOC / information overload, two lines would be enough to convey why this is here IMO.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
