### PR TITLE
Fix "Download Project Source" for Web Editor

### LINKED ISSUE #74818: "Download Project Source" broken in web editor
### Godot version

4.0.stable

### System information

Ubuntu 22.04.2 LTS, tested on Firefox and Chromium

### Issue description

The web editor no longer allows downloading your project's source from Project > Tools > Download Project Source. This is a critical issue for the web since there is no other way to backup or move your projects, seeing as neither version control nor cloud backup is yet supported (something I am hoping to investigate in future). Every web editor project is essentially stuck in a virtual filesystem limbo.

Reintroduces #71702

### Steps to reproduce

- Open the web editor at https://editor.godotengine.org/releases/4.0.1.stable/
- Create and open a new project, or open an existing one
- Go to Project > Tools > Download Project Source
- Check whether anything is downloaded, and look at the output - it should read:
  - `not enough arguments for format string`
  - `Unable to create ZIP file.`

### Minimal reproduction project

Uploading a project to the web editor would be more effort that it's worth.

### PR DESCRIPTION
**Pull request by ator-dev**
Fix #74818 

- Correctly pass safe project name and safe datetime to `vformat()`

**Important:** @akien-mga added the issue to the **4.1** milestone, but this is entirely a regression fix. If it is delayed until 4.1, my Godot club will not be able to operate (I know we could downgrade to 3, but it made coding concepts a lot harder to teach). I was hoping this could be added to 4.0.2 instead?

### CODE REVIEW

**Comment by YuriSizov** [comment]
Don't mind the milestone. It was assigned to the next available milestone, but it can still be cherry-picked for a 4.0.x release.

File: platform/web/api/web_tools_editor_plugin.cpp [hunk 1]
```diff
@@ -75,7 +75,7 @@ void WebToolsEditorPlugin::_download_zip() {
 	const String project_name_safe = project_name.to_lower().replace(" ", "_");
```
Comment (YuriSizov) [inline platform/web/api/web_tools_editor_plugin.cpp:75]: I think this is still incomplete. The comment above suggests that the name is sanitized somehow, but all we do is change it to be in lower case, and replace spaces with underscores. The given example will not be achieved with that. We probably want to call `validate_filename()` in here somewhere.

```suggestion
	const String project_name_safe = project_name.validate_filename().to_lower().replace(" ", "_");
```

But do note that it doesn't seem to replace all the symbols like the example suggests (e.g. it considers single `'` to be safe).

Comment (YuriSizov) [reply platform/web/api/web_tools_editor_plugin.cpp:75]: cc @Calinou since this was your PR originally https://github.com/godotengine/godot/pull/49598

Comment (ator-dev) [reply platform/web/api/web_tools_editor_plugin.cpp:75]: Thank you, I will look into this further. Note: I haven't had a chance to test this because I still need to get a server up to do it, but I wanted to get at least the cause of the error fixed.

Comment (ator-dev) [reply platform/web/api/web_tools_editor_plugin.cpp:75]: Slight concern, isn't it the job of `get_safe_dir_name` to do the validating? I would have expected that we'd need to do no further sanitisation than that.

Comment (YuriSizov) [reply platform/web/api/web_tools_editor_plugin.cpp:75]: You are correct. Despite the name we also use it to sanitize other strings, and it does a bit more than `validate_filename` (though I believe `'` is still allowed). This is good as is then.

**Review by YuriSizov — APPROVED** [review]
