### PR TITLE
Fix sampling bug when SSAO is using half size

### LINKED ISSUE #62881: Vulkan: Strange black line artifact in SSAO when Half Size is enabled
### Godot version

d26442e709f6361af9ac755ec9291bb43f2cd69b

### System information

Windows 10, GTX 1060 6GB

### Issue description

When SSAO quality is set to above "Low (Fast)" a weird line appears directly in the middle of the screen - it seems like some visual artifact - It always appears, but when `ssao_detail` is lowered the artifact is less visible, albeit still there.

SSAO OFF
image

SSAO on Medium
image

SSAO on Low
image

I think it doesn't show on low because Low doesn't use the detail pass in SSAO though I'm not sure.

### Steps to reproduce

Open any scene in godot. Enable SSAO in the WorldEnvironment, and if you can't see the strange line then increase Detail and Intensity of the SSAO.

### Minimal reproduction project

_No response_

### LINKED ISSUE #66643: Vulkan: strange SSAO artifacts on flat surfaces
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Arch Linux, Vulkan Clustered, Nvidia 1660(Nvidia open driver 515.76-2)

### Issue description

I initially thought this has something to do with the SSAO half size issues(https://github.com/godotengine/godot/issues/59471, https://github.com/godotengine/godot/issues/51564#issuecomment-897700747), but I found out that disabling half size only made the issue more subtle.

Personally, I think these issues have the same cause issue and the disabling of half size fixing them is due to how subtle the artifacts become after disabling half size.

https://user-images.githubusercontent.com/25323231/193185181-7dd5dd28-9de4-445e-a975-31106f1552e6.mp4

### Steps to reproduce

1. Set up a scene with a flat surface(cube, plane, etc.)
2. Enable SSAO

### Minimal reproduction project

[SSAO Issue.zip](https://github.com/godotengine/godot/files/9680537/SSAO.Issue.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/62881
Fixes: https://github.com/godotengine/godot/issues/66643

There are two pieces to this PR:
1. When downsampling 5 mip levels at once, the 5th mip level was showing some artifacts which lead to invalid samples in the SSAO shader. To fix it, I have removed the invalid averaging code from the 5th mipmap computation. This code path was only hit when using both SSAO and SSIL and only one of them is using half size
2. Change the ``half_screen_pixel_size`` to be based off the full screen size / 2. This was a difficult bug to track down, but essentially when using a screen size that could not be subdivided cleanly 4 times the half res samples would drift away from their intended positions. To fix that, we base our scaling off of the full viewport size. 

This also cleans up two unreported bugs:
1. The SSAO shader was using the wrong sampler (default instead of mirror)
2. The depth linearization process was doubling the depth value. This could have led to SSAO improperly rejecting valid occlusion (i.e. appearing slightly lighter than it should).

Finally, on investigation it appears that SSIL was suffering from the same issues, it was just less obvious. So I made the changes to SSIL as well

_Before_
Screenshot from 2023-02-16 00-13-09
_After_
Screenshot from 2023-02-16 00-13-47

_Before_

Screenshot from 2023-02-16 00-11-46

_After_
Screenshot from 2023-02-16 00-12-09

### CODE REVIEW

File: servers/rendering/renderer_rd/effects/ss_effects.cpp [hunk 1]
```diff
@@ -668,8 +668,14 @@ void SSEffects::screen_space_indirect_lighting(Ref<RenderSceneBuffersRD> p_rende
 		ssil.gather_push_constant.screen_size[0] = p_settings.full_screen_size.x;
 		ssil.gather_push_constant.screen_size[1] = p_settings.full_screen_size.y;
 
-		ssil.gather_push_constant.half_screen_pixel_size[0] = 1.0 / p_ssil_buffers.buffer_width;
-		ssil.gather_push_constant.half_screen_pixel_size[1] = 1.0 / p_ssil_buffers.buffer_height;
+		ssil.gather_push_constant.half_screen_pixel_size[0] = 2.0 / p_settings.full_screen_size.x;
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/effects/ss_effects.cpp:671]: I think `buffer_width` and `buffer_height` are already half `full_screen_size.xy`, Seems to be we should use `1.0/buffer_width` for normal and '1.0/half_width` for `ssil_half_size`?

File: servers/rendering/renderer_rd/effects/ss_effects.cpp [hunk 2]
```diff
@@ -733,7 +736,7 @@ void SSEffects::screen_space_indirect_lighting(Ref<RenderSceneBuffersRD> p_rende
 			RD::Uniform u_depth_texture_view;
 			u_depth_texture_view.uniform_type = RD::UNIFORM_TYPE_SAMPLER_WITH_TEXTURE;
 			u_depth_texture_view.binding = 0;
-			u_depth_texture_view.append_id(default_sampler);
+			u_depth_texture_view.append_id(ss_effects.mirror_sampler);
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/effects/ss_effects.cpp:739]: This might have been my bad :)

File: servers/rendering/renderer_rd/effects/ss_effects.cpp [hunk 3]
```diff
@@ -1056,8 +1059,14 @@ void SSEffects::generate_ssao(Ref<RenderSceneBuffersRD> p_render_buffers, SSAORe
 		ssao.gather_push_constant.screen_size[0] = p_settings.full_screen_size.x;
 		ssao.gather_push_constant.screen_size[1] = p_settings.full_screen_size.y;
 
-		ssao.gather_push_constant.half_screen_pixel_size[0] = 1.0 / p_ssao_buffers.buffer_width;
-		ssao.gather_push_constant.half_screen_pixel_size[1] = 1.0 / p_ssao_buffers.buffer_height;
+		ssao.gather_push_constant.half_screen_pixel_size[0] = 2.0 / p_settings.full_screen_size.x;
```
Comment (BastiaanOlij) [inline servers/rendering/renderer_rd/effects/ss_effects.cpp:1062]: so same here with `buffer_width` and `half_width`?

File: servers/rendering/renderer_rd/effects/ss_effects.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/effects/ss_effects.cpp:671]: I might be wrong though because `buffer_width` I think is also halved if `ssil_half_size`

Comment (clayjohn) [reply servers/rendering/renderer_rd/effects/ss_effects.cpp:671]: The problem is 1.0 / buffer_width does not equal 2.0 / screen_width

For example. If the screen is 1001 pixels wide, 2.0/ screen_width is ``0.001998001998`` while 1.0 / buffer width is ``0.001996007984`` that small difference is enough to cause an artifact when sampling the entire screen which is exactly what we see in the attached issues

**Review by BastiaanOlij — APPROVED** [review]
After discussing further with Clay, agreed this seems like a sound fix

File: servers/rendering/renderer_rd/effects/ss_effects.cpp (hunk 1 above)
Comment (BastiaanOlij) [reply servers/rendering/renderer_rd/effects/ss_effects.cpp:671]: Hmm, interesting, so its the source size that is more important than the size with which we create the destination texture width.

**Comment by akien-mga** [comment]
Thanks!
