### PR TITLE
fixes #6695 - MultiNodeEdit edit path in exported NodePath

### LINKED ISSUE #6695: Nodepath Assign use absolute path when many nodes are selected and assigned
Tested on Godot 2.1 stable

**Issue description:**
When the user has multiple nodes with an export var of NodePath type and try to assign **two or more** at the same time, the assigned value is an absolute one of type:
"/root/EditorNode/@@4/@@5/@@9/@@11/@@15/@@19/@@20/@@21/@@37/@@38/@@40/@@41/@@8585/@@8475/@@8476/@@8477/@@8478/@@8479/stage/paths/pattern_5/pattern_5_trigger"
The value should be a relative one, if the user select and assign only one NodePath, the value is assigned as relative ("../../paths/pattern_5/pattern_5_trigger").
This issue break the has_node/get_node which return false/error with the "/root/EditorNode/..." path 

**Steps to reproduce:**
Create a script with this export line:
`export(NodePath) var path`
add this script to two or more nodes
Try to assign the path value from the script with two or more nodes selected

Here is a video of the steps:
https://gfycat.com/FarflungHonorableArabianwildcat

**Link to minimal example project** (optional but very welcome):
The project from the video:
https://dl.dropboxusercontent.com/s/3e346ng6n88zji2/nodepath_issue.zip

### PR DESCRIPTION
**Pull request by razcore-rad**
Someone should verify this as I am not sure it is 100% correct :D

### CODE REVIEW

File: tools/editor/multi_node_edit.cpp [hunk 1]
```diff
@@ -52,8 +52,16 @@ bool MultiNodeEdit::_set(const StringName& p_name, const Variant& p_value){
 		Node*n=es->get_node(E->get());
 		if (!n)
 			continue;
+		else if (p_value.get_type() == Variant::NODE_PATH) {
```
Comment (bojidar-bg) [inline tools/editor/multi_node_edit.cpp]: I think you should remove the `else` from here though. (and maybe add an additional newline..)

File: tools/editor/multi_node_edit.cpp [hunk 2]
```diff
@@ -52,8 +52,16 @@ bool MultiNodeEdit::_set(const StringName& p_name, const Variant& p_value){
...
+			Node *tonode = n->get_node(p_value);
+			if (tonode) {
+				NodePath p_path = n->get_path_to(tonode);
+				ur->add_do_property(n,name,p_path);
+			}
```
Comment (bojidar-bg) [inline tools/editor/multi_node_edit.cpp]: And what if `tonode == NULL`? We don't set anything?

Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: Good question, I guess when tonode is null we should throw an error, but I don't know how :c

File: tools/editor/multi_node_edit.cpp (hunk 1 above)
Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: The else is necessary because `n` has to exist

Comment (bojidar-bg) [inline tools/editor/multi_node_edit.cpp]: The continue would catch it already...

Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: Oh right, didn't think about that D:, makes sense yes

File: tools/editor/multi_node_edit.cpp (hunk 2 above)
Comment (bojidar-bg) [inline tools/editor/multi_node_edit.cpp]: Well, I guess we should just fallback to setting the property normally, just in case...

File: tools/editor/multi_node_edit.cpp (hunk 1 above)
Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: Updated this one

File: tools/editor/multi_node_edit.cpp (hunk 2 above)
Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: M, no, I don't think so, because this would end up with that `/root/EditNode/@@4/@@6/etc` thing. If `tonode == NULL` for some reason then it should be an error, I mean, it's something that shouldn't happen.

Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: M, no, I don't think so, because this would end up with that `/root/EditNode/@@4/@@6/etc` thing. If `tonode == NULL` for some reason then it should be an error, I mean, it's something that shouldn't happen.

Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: I checked `Node::get_path_to` and it has fail conditions inside, `ERR_FAIL_NULL_V(p_node,NodePath())` etc. so if `tonode` isn't reachable for some reason it will fail so there's no need to add an extra error here, at least I think so... this patch should work as expected

Comment (razvanc-r) [inline tools/editor/multi_node_edit.cpp]: yes, that makes sense, just did that. The reason why I had the if was that I copied the code from `tools/editor/property_editor.cpp` which uses an if. But who wrote that probably forgot about the error checking inside `get_node`, `get_path_to`, etc
