### PR TITLE
Fix several issues with renaming in FileSystem dock

### LINKED ISSUE #82074: Editor crashes when renaming a file/folder by clicking outside of it
### Godot version

v4.2.dev5

### System information

Windows 11

### Issue description

The editor crashes when confirming a file/folder rename by clicking outside the selection.
This works fine in the Scene Tree dock.
I don't know why, but it's easier to reproduce in single window mode.

### Steps to reproduce

1. Enable single window mode in the editor settings.
2. Select a file/folder in the FileSystem dock.
3. Press F2 or select the Rename option from the context menu.
4. Click an empty area in FileSystem dock to confirm the rename.
Clicking outside the FileSystem dock shows a false warning instead.

### Minimal reproduction project

N/A

### LINKED ISSUE #82543: "A file or folder with this name already exists" errors when renaming folder to a different name
### Godot version

Godot v4.2.dev (44e399ed5)

### System information

Mageia 9 - X11 - GLES3 (Compatibility) - AMD Radeon RX Vega M GL Graphics (vegam, LLVM 15.0.6, DRM 3.52, 6.4.9-desktop-4.mga9) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

I have this simple setup, using **Split Mode**:
image

If I try to rename a folder (e.g. `player`) in the thumbnails view, a number of bugs occur:

Start renaming with F2 or Right click > Rename

- Keep the same name, and click in the FileSystem dock: no change, no error, as expected
- Keep the same name, and click outside the FileSystem dock:
  * If clicking in the Scene tree (positioned in the same column for me), no change, no error
  * If clicking in the Inspector, or 3D viewport, an error is shown that it can't be renamed as the name is taken

image

And a transient window elusive child error from that popup.

- Change the name to something unique (e.g. `player2`), then confirm the change with the mouse:
  * If clicking in the FileSystem dock, the rename works sometimes, and the folder is entered automatically, which seems weird to me. The selection is also out of sync between the tree view and the thumbnails view:

image

  * But in other times with the same steps, it fails with the error about a file name conflict. Not sure how to reproduce reliably, it seems to happen maybe 10% of the time for me.
  * If clicking in the Scene tree, same behavior as above.
  * If clicking in the Inspector, or 3D viewport, same file conflict error as above.

- Change the name to something unique (e.g. `player2`), then confirm the change with the <kbd>Enter</kbd>:
  * Same behavior as with mouse click.

Some of these bugs seem specific to the Split Mode, but others seem to also happen in Tree view. It feels very buggy overall, it needs a thorough fixup pass.

Seems to be a regression which happened between 4.2-dev1 and 4.2-dev3. 4.2-dev2 is outright crashing on start so I can't test further. In dev1, I don't get the dialog about file name conflicts. I do get the weird behavior that editing a folder name enters the folder, and makes the selection out of sync in Split Mode, so that's a pre-existing and different bug.

### Steps to reproduce

See above.

### Minimal reproduction project

Reproducible in a brand new project.

### PR DESCRIPTION
**Pull request by VedatGunel**
Fixes #82074
Fixes #82543
I tested all the cases I could think of, with Single Window Mode on/off & Split Mode on/off, and didn't spot any regressions.

### CODE REVIEW

**Comment by VedatGunel** [comment]
Rebased to replace the focus check that was merged with #81007, similar to the others.
Checking if the tree has focus doesn't work when clicking outside the FileSystem dock, but checking the edited item always works.

**Comment by Sauermann** [comment]
It is good to see, that we came to the same conclusion of how to fix #82543.

**Comment by VedatGunel** [comment]
Included an experimental fix for #19592.
I couldn't reproduce the issue on Windows 10 or Windows 11, so I included the macOS preprocessor check.
Can any macOS users test it?

**Comment by akien-mga** [comment]
> Included an experimental fix for #19592. I couldn't reproduce the issue on Windows 10 or Windows 11, so I included the macOS preprocessor check. Can any macOS users test it?

CC @bruvzg

**Review by bruvzg — COMMENTED** [review]
> Included an experimental fix for https://github.com/godotengine/godot/issues/19592.
I couldn't reproduce the issue on Windows 10 or Windows 11, so I included the macOS preprocessor check.
Can any macOS users test it?

It is fixing it on macOS, on a case-insensitive file system. But it will overwrite file without any warnings on case-sensitive FS!

**Comment by bruvzg** [comment]
> It is fixing it on macOS, on a case-insensitive file system. But it will overwrite file without any warnings on case-sensitive FS!

Probably require something more complex (work on both case-insensitive and case-sensitive fs on macOS, have not tested it on Windows).

https://github.com/godotengine/godot/pull/82957

**Comment by VedatGunel** [comment]
Thanks for the review and quick PR!
I reverted the macOS change.

**Comment by VedatGunel** [comment]
Included a fix for https://github.com/godotengine/godot/issues/82543#issuecomment-1751042987, which is a recent regression from https://github.com/godotengine/godot/pull/82045.
I'm not sure if it's the best solution though, I'm open to suggestions.

**Review by akien-mga — APPROVED** [review]
Awesome work! I can confirm this fixes both issues for me.

I didn't review the code changes in depth (not very familiar with this code), review welcome from @KoBeWi @groud (and @Sauermann since you looked into this too).

**Comment by akien-mga** [comment]
BTW now that you're familiar with that code @VedatGunel, you might be interested to look into #82774 (but if you do it's probably best left for a follow-up PR, as this one is fixing a regression while #82774 seems to be a pre-existing issue).

File: editor/filesystem_dock.cpp [hunk 1]
```diff
@@ -1729,12 +1729,12 @@ void FileSystemDock::_folder_removed(String p_folder) {
 
 void FileSystemDock::_rename_operation_confirm() {
 	String new_name;
-	TreeItem *s = tree->get_selected();
-	int col_index = tree->get_selected_column();
+	TreeItem *s = tree->get_edited();
+	int col_index = tree->get_edited_column();
 
-	if (tree->has_focus()) {
+	if (s != nullptr) {
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:1735]:
```suggestion
	if (s) {
```
`s` is a pointer (integer), so it can be used as boolean (with null being 0/false) and that's what we do more often. Although either way is fine.

File: editor/filesystem_dock.cpp [hunk 2]
```diff
@@ -2048,7 +2048,7 @@ Vector<String> FileSystemDock::_remove_self_included_paths(Vector<String> select
 }
 
 void FileSystemDock::_tree_rmb_option(int p_option) {
-	Vector<String> selected_strings = _tree_get_selected(false);
+	Vector<String> selected_strings = _tree_get_selected(false, true);
```
Comment (KoBeWi) [inline editor/filesystem_dock.cpp:2051]: What does this change fix?

Comment (VedatGunel) [reply editor/filesystem_dock.cpp:2051]: The issue described here: https://github.com/godotengine/godot/issues/82543#issuecomment-1751042987
#82045 made it so that currently focused but unselected item in the tree wouldn't be included in the selected item list, but this broke the renaming behavior because visually renamed item (tree->get_selected()) and the path being renamed (to_rename.path) became different. https://github.com/godotengine/godot/blob/42425baa59956dc9d1e22341fe5e5d7f8fad5067/editor/filesystem_dock.cpp#L2232-L2235

So, I added an optional parameter to also include the unselected focused item to the list, to restore the old behavior. But I noticed that making this change at the top of _tree_rmb_option() wouldn't be the correct fix, because we want this behavior only for renaming. So, maybe I should add another call to  _tree_get_selected() with second argument as true inside the FILE_RENAME case, and revert the one in _tree_rmb_option(). What do you think?

Comment (KoBeWi) [reply editor/filesystem_dock.cpp:2051]: Right, this function confused me a bit.

I think it's good here (right-clicking an item has the same problem actually), but I agree that it should only affect FILE_RENAME. You can add another `case` that overwrites selected strings (although it kind of sucks to call `_tree_get_selected()` twice; maybe it can be done better):
```C++
case FILE_RENAME: {
	selected_strings = _tree_get_selected(false, true);
	[[fallthrough]];
}
default: {
	_file_option(p_option, selected_strings);
} break;
```

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
