### PR TITLE
Fix crash when dropping scene as a sibling of the root node

### LINKED ISSUE #5782: Crash on dropping scene as sibling of the root node
If you drag a scene from the FileSystem dock and try to drop it on top of the root node as a sibling, the editor will crash. It should just not allow it as it does when you drag nodes already in the tree.

[Sample project](https://github.com/godotengine/godot/files/369558/instance-crash.tar.gz). To reproduce drag the `instance.tscn` scene from the FileSystem dock and drop it as a top sibling of the root node, as in the following image:

godot windows opt tools 64_2016-07-18_13-24-58

### PR DESCRIPTION
**Pull request by ghost**
Closes #5782.

### CODE REVIEW

File: tools/editor/scene_tree_dock.cpp [hunk 1]
```diff
@@ -1617,8 +1615,9 @@ void SceneTreeDock::_normalize_drop(Node*& to_node, int &to_pos, int p_type) {
 	} else if (p_type==1) {
 			//drop at below selected node
 			if (to_node==EditorNode::get_singleton()->get_edited_scene()) {
-				to_node=NULL;
-				ERR_FAIL_COND(to_node==EditorNode::get_singleton()->get_edited_scene());
+				//if at lower sibling of root node
+				to_pos=0; //just insert at begining of root node
+				return;
```
Comment (TheHX) [inline tools/editor/scene_tree_dock.cpp]: I've moved the code of the first  `if` on this CF block to here, so i could remove the unreachable code, even if it's not related with the issue.
