### PR TITLE
Remove the obsolete "2D Pixel" import preset

### LINKED ISSUE #37057: (Vulkan) 2D Pixel Import Not Working
**Godot version:**
4.0 custom build f65781fe7

**OS/device including version:**
Windows 10

**Issue description:**

Importing PNG and attempting to re-import using 2d Pixel does not result in a pixel perfect texture. This problem has actually been for while now and I was waiting to report it.

**Steps to reproduce:**

Start a new 4.0 project. Add a new pixel like texture. Drag the Texture onto a new scene and notice how the image is blurry. Select the Import Tab. Select 2D Pixel from the drop down. Click Re import button. Notice that nothing happened to the Texture. 

See video below for example.

[2020-03-14_18-20-28.zip](https://github.com/godotengine/godot/files/4333527/2020-03-14_18-20-28.zip)

**Minimal reproduction project:**

Sample project is attached.

[2dpixel-vulkan.zip](https://github.com/godotengine/godot/files/4333530/2dpixel-vulkan.zip)

### PR DESCRIPTION
**Pull request by Calinou**
**Note:** Not cherry-pickable to the `3.2` branch, as this is specific to the Vulkan renderer.

Texture filtering is now defined on a per-node basis, thanks to bindless textures provided by Vulkan.

This closes #37057.

### CODE REVIEW

File: editor/import/resource_importer_texture.cpp [hunk 1]
```diff
@@ -181,15 +181,14 @@ bool ResourceImporterTexture::get_option_visibility(const String &p_option, cons
...
 }
 
 String ResourceImporterTexture::get_preset_name(int p_idx) const {
 	static const char *preset_names[] = {
-		"2D, Detect 3D",
+		"2D/3D (Auto-Detect)",
 		"2D",
-		"2D Pixel",
-		"3D"
+		"3D",
```
Comment (Anutrix) [inline editor/import/resource_importer_texture.cpp:191]: Maybe remove the comma after "3D".

Comment (Calinou) [reply editor/import/resource_importer_texture.cpp:191]: I intentionally added it so we can get more VCS-friendly diffs in the future. clang-format currently doesn't enforce trailing commas in multiline arrays.

**Comment by akien-mga** [comment]
Thanks!
