### PR TITLE
Fix viewport not updating with make_current() for Camera2D

### LINKED ISSUE #23966: Camera2D.make_current() doesn't work
**Godot version:** 3.1

**OS/device including version:** Ubuntu 18.04

**Issue description:**
Trying to set a camera with Camera2D.make_current() outside of _ready() doesn't work.

**Steps to reproduce:**
Add a Camera2D to a 2D scene. Add a script that calls Camera2D.make_current() outside of _ready().
The game won't show the perspective of the new camera but will keep showing the default camera's or the viewport's one.

**Minimal reproduction project:** [camera2d_demo.zip](https://github.com/godotengine/godot/files/2613309/camera2d_demo.zip)
In the scene there is a sprite to the right of a camera and to the left of another one. Pressing space should switch the current camera and change the sprite's position on screen but nothing happens.

### PR DESCRIPTION
**Pull request by BrodyEller**
Fixes issue #23966 where viewport would not update with new **Camera2D** when `make_current()` was called.  

*Bugsquad edit:* Fixes #23966.

### CODE REVIEW

File: scene/2d/camera_2d.cpp [hunk 1]
```diff
@@ -410,6 +410,7 @@ void Camera2D::make_current() {
 	} else {
 		get_tree()->call_group_flags(SceneTree::GROUP_CALL_REALTIME, group_name, "_make_current", this);
 	}
+  _update_scroll();
```
Comment (SoIAS) [inline scene/2d/camera_2d.cpp]: Hello there, you should correct indentation of the _update_scroll() to match the previous closing bracket, preferably using a tabulator.

Comment (BrodyEller) [reply scene/2d/camera_2d.cpp]: As it turns out, I still had two space tabs turned on in Xcode.  It all looks fine in there, switching it to normal tabs fixed the indentation.

File: scene/2d/camera_2d.cpp [hunk 2]
```diff
@@ -410,6 +410,7 @@ void Camera2D::make_current() {
 	} else {
 		get_tree()->call_group_flags(SceneTree::GROUP_CALL_REALTIME, group_name, "_make_current", this);
 	}
+	_update_scroll()
```
Comment (akien-mga) [inline scene/2d/camera_2d.cpp]: Missing `;`.

Comment (BrodyEller) [reply scene/2d/camera_2d.cpp]: Realized this in the build but now CI is failing for some reason.

**Comment by akien-mga** [comment]
Thanks!
