### PR TITLE
Make dark mode Title Bar work on Windows 10 1909 (build:18363) and above

### LINKED ISSUE #65492: Windows 10: Title bar not changing color while in dark mode
### Godot version

4.0.alpha16

### System information

Windows 10

### Issue description

When launching the Godot editor with dark mode enabled, the title bar stays white, but the other UI elements switch to dark mode (also white) so they cannot be seen properly. 

This also happens to any child window when it is created even when the main window has the black title bar.

dark_mode

This effect disappears as soon as the window is unfocused or resized. Dragging it around does nothing as well as switching from project manager to the editor.

### Steps to reproduce

Launch the editor either directly or trough console

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by emanvidmaker**
## Summary:
 Properly fixes #65492 thereby adding dark mode support for win 10 without the Title Bar glitching out

## The Issue:
Currently Godot enables dark mode features exclusively for windows 11 users ( PR #65262 ), even tho windows 10 Supports it.
This was done to patch a bug where the Title Bar doesn't update its color to dark theme on Win 10 #65492 . 
## My solution:
I fixed this bug, by looking at how other Open Source projects support dark mode on win 10 and discovered a way that Godot can implement it too. Thereby adding dark mode support back to Godot Win 10 users, with minimal changes to the window server.
## How? 
The windows display server was missing a window message handler, WM_CREATE that is needed to set darkmode in win10. In there i added a `SendMessageW(windows[window_id].hWnd, WM_PAINT, 0, 0);` call to repaint and update the title bar. This call a key part that makes it work. 

## Videos

Video of Me replicating" Windows 10: Title bar not changing color while in dark mode #65492 " bug:

BrokenGodot_dark

Video of my bugfix: 
FixedGodot_dark

## Extra details
Currently the minimum version that godot(master) supports dark mode is `Windows 11 Version 21H2 (OS build 22000)`

With this change it gets lowered to `Windows 10 Version 1909 (OS build 18363)` 
Since that the lowest version i could find in other code bases where the `DwmSetWindowAttribute` implementation works.

I tested the fix on my PC that runs `Windows 10 22H2 (OS build: 19045)` and it works like a charm.

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
If setting it in the `WM_CREATE` fix it on Windows 10, it should be fine to add.

File: platform/windows/display_server_windows.cpp [hunk 1]
```diff
@@ -4614,7 +4621,7 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
 		GetImmersiveUserColorSetPreference = (GetImmersiveUserColorSetPreferencePtr)GetProcAddress(ux_theme_lib, MAKEINTRESOURCEA(98));
 
 		ux_theme_available = ShouldAppsUseDarkMode && GetImmersiveColorFromColorSetEx && GetImmersiveColorTypeFromName && GetImmersiveUserColorSetPreference;
-		if (os_ver.dwBuildNumber >= 22000) {
+		if (os_ver.dwBuildNumber >= 18363) {
```
[the remark this answers is not in the document]
Comment (emanvidmaker) [reply platform/windows/display_server_windows.cpp:4624]: On it, il  do checks from a static bool thats true on that version range

**Comment by emanvidmaker** [comment]
@bruvzg  is this fine?

File: platform/windows/display_server_windows.cpp [hunk 2]
```diff
@@ -4355,7 +4371,8 @@ DisplayServer::WindowID DisplayServerWindows::_create_window(WindowMode p_mode,
 
 		if (is_dark_mode_supported() && dark_title_available) {
 			BOOL value = is_dark_mode();
-			::DwmSetWindowAttribute(wd.hWnd, DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value));
+			::DwmSetWindowAttribute(wd.hWnd, use_legacy_dark_mode_before_20H1 ? DWMWA_USE_IMMERSIVE_DARK_MODE_BEFORE_20H1 : DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value));
+			::DwmSetWindowAttribute(wd.hWnd, use_legacy_dark_mode_before_20H1 ? DWMWA_USE_IMMERSIVE_DARK_MODE_BEFORE_20H1 : DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value));
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:4375]: All calls seem to be duplicated.

File: platform/windows/display_server_windows.cpp [hunk 3]
```diff
@@ -4493,6 +4510,8 @@ WTEnablePtr DisplayServerWindows::wintab_WTEnable = nullptr;
 
 // UXTheme API.
 bool DisplayServerWindows::dark_title_available = false;
+bool DisplayServerWindows::use_legacy_dark_mode_before_20H1 = false;
+bool DisplayServerWindows::use_legacy_dark_mode_before_20H1 = false;
```
Comment (bruvzg) [inline platform/windows/display_server_windows.cpp:4514]: Same here.

**Comment by AThousandShips** [comment]
When updating your branch please use `git rebase`, otherwise squashing your commits becomes much harder, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Review by bruvzg — APPROVED** [review]
Please squash your commits into one, see [pull request workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) page for details.

File: platform/windows/display_server_windows.cpp [hunk 4]
```diff
@@ -4610,7 +4618,6 @@ DisplayServerWindows::DisplayServerWindows(const String &p_rendering_driver, Win
 		GetImmersiveUserColorSetPreference = (GetImmersiveUserColorSetPreferencePtr)GetProcAddress(ux_theme_lib, MAKEINTRESOURCEA(98));
 
 		ux_theme_available = ShouldAppsUseDarkMode && GetImmersiveColorFromColorSetEx && GetImmersiveColorTypeFromName && GetImmersiveUserColorSetPreference;
-		if (os_ver.dwBuildNumber >= 22000) {
```
Comment (AThousandShips) [inline platform/windows/display_server_windows.cpp:4613]: You didn't squash this correctly, you just removed this line and all the changes you made here instead

File: platform/windows/display_server_windows.cpp [hunk 5]
```diff
@@ -4489,6 +4496,7 @@ WTEnablePtr DisplayServerWindows::wintab_WTEnable = nullptr;
 
 // UXTheme API.
 bool DisplayServerWindows::dark_title_available = false;
+bool DisplayServerWindows::use_legacy_dark_mode_before_20H1 = false;
```
Comment (AThousandShips) [inline platform/windows/display_server_windows.cpp:4499]: You also removed the changes to the header so this variable doesn't exist

**Comment by emanvidmaker** [comment]
Im having some merge isuess, I know how to fix it and its almost done

**Comment by AThousandShips** [comment]
Please reset your branch to `5e8094b` with `git reset --hard 5e8094b` and try again, you need to use `git rebase -i master`

**Comment by emanvidmaker** [comment]
I think i fixed it by making a serial patch of my older version before the force push, forcing my branch to match origin/master and applying a patch to it, and force pushing that

**Comment by AThousandShips** [comment]
(I'd suggest fixing your system clock, it really messes with the threads when your computer is in the future 😆)

**Comment by emanvidmaker** [comment]
(i fixed, didnt realize it)

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
