### PR TITLE
String[size()] should return a default constructed CharType

### LINKED ISSUE #21242: store_pascal_string() crashes when saving an empty string
**Godot version:**
v3.0.5-stable_x11.64, Xubuntu

**Issue description:**
_store_pascal_string()_ crashes the game when trying to save an empty string.

**Steps to reproduce:**
Download the example project.
Run the scene.
The game quits.
Edit the script, write anything in the currently empty string.
Run the game.
The game runs fine.

**Example project:**
[pascal_string_bug.zip](https://github.com/godotengine/godot/files/2303609/pascal_string_bug.zip)

### LINKED ISSUE #22221: Crash during Concave shape import from DAE file
**Godot version:**
e522baf0b78ae475685e890059afd7f402b21541

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
It seems that editor is crashing in my project during the reimport of collision bodies that were defined in Blender. I will attach the reproduction project together with a sample dae file. Also it's worth to mention this works fine in 3.0.6.

Backtrace:
````
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f513acd2f20] (??:0)
[2] String::parse_utf8(char const*, int) (??:0)
[3] String::utf8(char const*, int) (??:0)
[4] String::percent_decode() const (??:0)
[5] Collada::_parse_image(XMLParser&) (??:0)
[6] Collada::_parse_library(XMLParser&) (??:0)
[7] Collada::load(String const&, int) (??:0)
[8] ColladaImport::load(String const&, int, bool, bool) (??:0)
[9] EditorSceneImporterCollada::import_scene(String const&, unsigned int, int, List<String, DefaultAllocator>*, Error*) (??:0)
[10] ResourceImporterScene::import(String const&, String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*) (??:0)
[11] EditorFileSystem::_reimport_file(String const&) (??:0)
[12] EditorFileSystem::reimport_files(Vector<String> const&) (??:0)
[13] EditorFileSystem::_update_scan_actions() (??:0)
[14] EditorFileSystem::_notification(int) (??:0)
[15] EditorFileSystem::_notificationv(int, bool) (??:0)
[16] Object::notification(int, bool) (??:0)
[17] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[18] SceneTree::idle(float) (??:0)
[19] Main::iteration() (??:0)
[20] OS_X11::run() (??:0)
[21] /home/kubeczek/Projects/GIT/godot/bin/godot.x11.tools.64(main+0xd5) [0x55670449061f] (??:0)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f513acb5b97] (??:0)
[23] /home/kubeczek/Projects/GIT/godot/bin/godot.x11.tools.64(_start+0x2a) [0x55670449046a] (??:0)
-- END OF BACKTRACE --
````

**Steps to reproduce:**
1. Download sample project and open it
2. Observe the editor crash during the import of `tut_level-col.dae` file

**Minimal reproduction project:**
[ConclaveCollisionShape.zip](https://github.com/godotengine/godot/files/2393474/ConclaveCollisionShape.zip)

### PR DESCRIPTION
**Pull request by hpvb**
As per the C++ standard 21.3.4.1 for std::string:
Returns: If pos < size(), returns data()[pos]. Otherwise, if pos ==
size(), the const version returns charT(). Otherwise, the behavior is
undefined.

Since the behavior is undefined Godot now does the same thing for const
and non-const versions of operator[].

This fixes #21242 and fixes #22221.

### CODE REVIEW

**Comment by hpvb** [comment]
PS: for people who watched the stream where this PR was developed, bunnymark performance is in margin of error when not streaming the benchmark :)

File: core/cowdata.h [hunk 1]
```diff
@@ -52,29 +52,31 @@ class CowData {
 
 private:
 	mutable T *_ptr;
+	T *_defval;
```
Comment (reduz) [inline core/cowdata.h]: I dont think this is a good idea, we should refrain to keep adding stuff here. Also this should be for string, not for cowdata

**Review by reduz — DISMISSED** [review]

**Comment by akien-mga** [comment]
Added #22221 as fixed by this PR since it seems to be another symptom of the same bug.

**Comment by akien-mga** [comment]
Needs a rework to use the new #24385.

**Comment by akien-mga** [comment]
Bump. Another occurrence of a `String[size()]` crash: #24585.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Doesn't cherry-pick cleanly on the 3.0 branch, and I'm not sure we should bother at this stage, but I'll let you decide @hpvb.

**Comment by akien-mga** [comment]
Opting out from cherry-picking this for 3.0 for now.
