### PR TITLE
prevent selecting hidden editable children in spatial editor

### LINKED ISSUE #46032: Can select children of instanced scene while it doesn't have editable children
**Godot version:**
3.2.4.rc.custom_build / 3.2.4.rc1 (both exhibit the same behaviour)

**System**
Linux (PopOS - most recent, up to date including drivers), GLES3, Nvidia 1060 - laptop

**Issue description:**
This is a really weird bug. It only affects projects created with previous versions of Godot.
As of rc1 i believe, the 3d editor unreliably alters between selecting the instanced scene or its children.
No errors whatsoever. In the screenshot below you can see:
- instanced scene which doesnt have editable children
- first click on the scene selected one of its children
- understandably the node is not highlighted in the scene tree as it's not there at all.

image

**Steps to reproduce:**
Open a project created in 3.2.3 or lower

**Minimal reproduction project:**
Sadly I am not in possession of a minimal reproduction project, I've only got bigger ones, which I don't mind sharing if it'd help and you don't mind downloading a bigger project.

### PR DESCRIPTION
**Pull request by hilfazer**
Fixes #46032.

There are 3 actions that need to be tested: single selection, region selection and list selection (Alt + RMB). I'm completely green at 3D stuff so i did test it only on some simple scenes.

PR for 3.2 since i was not able to reproduce this issue on master and don't know if the changes are needed there as well.

### CODE REVIEW

File: editor/plugins/spatial_editor_plugin.cpp [hunk 1]
```diff
@@ -75,6 +75,26 @@
 #define MIN_FOV 0.01
 #define MAX_FOV 179
 
+namespace {
```
Comment (akien-mga) [inline editor/plugins/spatial_editor_plugin.cpp:78]: We don't normally use namespaces in Godot code. This should likely just be a normal static method or a private class method.

Comment (hilfazer) [reply editor/plugins/spatial_editor_plugin.cpp]: Ok. Replaced namespace with a static function.

**Review by akien-mga — APPROVED** [review]
Code seems OK, and the fix was confirmed by @lentsius-bark in https://github.com/godotengine/godot/issues/46032#issuecomment-781327012.

**Comment by akien-mga** [comment]
Thanks!
