### PR TITLE
CryptoCore: Use `size_t` for buffer sizes to fix encoding/sums of 2.0+ GiB files

### LINKED ISSUE #104949: Editor crashes with signal 11 when exporting a project and trying to include a 2 GiB file in the `.pck` file
### Tested versions

- Reproducible in: 4.3.stable, 4.4.1.stable.
- Not reproducible in: 4.2.2.stable

### System information

Godot v4.4.1.stable (49a5bc7b6) - cpe:/o:nixos:nixos:24.11 #1-NixOS SMP PREEMPT_DYNAMIC Sat Mar 22 19:56:59 UTC 2025 on Wayland - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.61, 6.13.8) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

### Issue description

If I tell the Godot editor to include a large file (2 GiB) in a project’s `.pck` file, then when I try to export that project, the Godot editor crashes with this error:

<pre><samp>Godot Engine v4.4.1.stable.nixpkgs.49a5bc7b6 - https://godotengine.org
Inconsistent value (1) for DRI_PRIME. Should be &lt; 1 (GPU devices count). Using: 0
OpenGL API 4.6 (Core Profile) Mesa 24.2.8 - Compatibility - Using Device: AMD - AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.61, 6.13.8)

first_scan_filesystem: begin: Project initialization steps: 5
        first_scan_filesystem: step 0: Scanning file structure...
        first_scan_filesystem: step 1: Loading global class names...
        first_scan_filesystem: step 2: Verifying GDExtensions...
        first_scan_filesystem: step 3: Creating autoload scripts...
        first_scan_filesystem: step 4: Initializing plugins...
        first_scan_filesystem: step 5: Starting file scan...
first_scan_filesystem: end
savepack: begin: Packing steps: 102
        savepack: step 2: Storing File: res://.godot/imported/icon.webp-e94f9a68b0f625a567a797079e4d325f.ctex
        savepack: step 2: Storing File: res://icon.webp.import
        savepack: step 35: Storing File: res://.godot/exported/133200997/export-3070c538c03ee49b7677ff960a3f5195-main.scn

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.4.1.stable.nixpkgs (49a5bc7b616bd04689a2c89e89bda41f50241464)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /nix/store/rmy663w9p7xb202rcln4jjzmvivznmz8-glibc-2.40-66/lib/libc.so.6(+0x40f30) [0x7ffff7c40f30] (??:0)
[2] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x50bf7d3] (??:?)
[3] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x11cc37f] (??:?)
[4] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x11cc55c] (??:?)
[5] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x1c9b4b8] (??:?)
[6] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x1ca31de] (??:?)
[7] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x1ca5a78] (??:?)
[8] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x1ca92b4] (??:?)
[9] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x195c68b] (??:?)
[10] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x4967fd3] (??:?)
[11] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x82a8d3] (??:?)
[12] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x185e0b2] (??:?)
[13] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x48def98] (??:?)
[14] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x2a21de7] (??:?)
[15] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x2a515c2] (??:?)
[16] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x2a9c429] (??:?)
[17] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x51c606] (??:?)
[18] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x4242e2] (??:?)
[19] /nix/store/rmy663w9p7xb202rcln4jjzmvivznmz8-glibc-2.40-66/lib/libc.so.6(+0x2a1fe) [0x7ffff7c2a1fe] (??:0)
[20] /nix/store/rmy663w9p7xb202rcln4jjzmvivznmz8-glibc-2.40-66/lib/libc.so.6(__libc_start_main+0x89) [0x7ffff7c2a2b9] (??:0)
[21] /nix/store/mb8wrl1pf82z8lkg72qqpnjqiy5bbzgn-godot4-4.4.1-stable/bin/godot4() [0x4485b5] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
</samp></pre>

### Steps to reproduce

Follow the instructions in [the repo that I created for this bug’s minimum reproduction project](https://codeberg.org/JasonYundt/godot-export-crash-reproduction-project).

### Minimal reproduction project (MRP)

<https://codeberg.org/JasonYundt/godot-export-crash-reproduction-project>

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #104949.

Could also use `uint64_t` as we do elsewhere for file access. I went with `size_t` as that's what mbedtls expects.

There's a few more mbedtls calls in `mbedtls/crypto_mbedtls.cpp` which pass `int` where mbedtls takes `size_t`, but those mostly deal with small buffers (certificates, keys). Might still be worth a cleanup pass.

### CODE REVIEW

File: core/crypto/crypto_core.cpp [hunk 1]
```diff
@@ -225,27 +225,27 @@ String CryptoCore::b64_encode_str(const uint8_t *p_src, int p_src_len) {
...
 }
 
-Error CryptoCore::b64_decode(uint8_t *r_dst, int p_dst_len, size_t *r_len, const uint8_t *p_src, int p_src_len) {
+Error CryptoCore::b64_decode(uint8_t *r_dst, size_t p_dst_len, size_t *r_len, const uint8_t *p_src, size_t p_src_len) {
 	int ret = mbedtls_base64_decode(r_dst, p_dst_len, r_len, p_src, p_src_len);
 	return ret ? FAILED : OK;
 }
 
-Error CryptoCore::md5(const uint8_t *p_src, int p_src_len, unsigned char r_hash[16]) {
+Error CryptoCore::md5(const uint8_t *p_src, size_t p_src_len, unsigned char r_hash[16]) {
```
Comment (akien-mga) [inline core/crypto/crypto_core.cpp:238]: Technically, the case that crashed in #104949 was from `editor/export/editor_export_platform.cpp:221`:
```cpp
bool EditorExportPlatform::_check_hash(const uint8_t *p_hash, const Vector<uint8_t> &p_data) {
        if (p_hash == nullptr) {
                return false;
        }

        unsigned char hash[16];
        Error err = CryptoCore::md5(p_data.ptr(), p_data.size(), hash);
```
`Vector<T>::size` is based on `CowData` and uses `Size`, which is a typedef for `int64_t`.

**Comment by lawnjelly** [comment]
I don't know whether Godot 4 is compiled under 32 bit, but there `size_t` could be 32 bit.

Maybe this is a limitation of mbedtls (if it takes `size_t`).

We could also consider having the Godot functions take a `uint64_t`, then `ERR_FAIL` if the size is above `size_t` range (`SIZE_MAX`) before calling mbedtls, rather than crash.

That's if there are any 32 bit builds planned.

And there's the question of whether the calling code can cope with a failure gracefully...

**Review by lawnjelly — APPROVED** [review]
Approved but leave it to you whether you want to handle the 64 bit case as above, depending on whether 32 bit builds are planned.

**Comment by bruvzg** [comment]
> I don't know whether Godot 4 is compiled under 32 bit, but there size_t could be 32 bit.

It's used for memory buffers, so `size_t` is a natural limit. For files there are equivalent functions in the `FileAccess`, which read file in 32K chunks.

**Comment by bruvzg** [comment]
> So I tested this PR on Linux x86_32 and interestingly it doesn't crash, as it seems to fail before computing the md5sum

PCK exporter read each file to the memory as a single `PackedByteArray`, so I guess it's expected to fail before it get to the hash checks. But it's not the case for reading PCK, so exported 32-bit project should be able to access it.

**Comment by akien-mga** [comment]
I tested some more with this script, and I'm surprised that `FileAccess.get_md5` actually works for that file on x86_32:
```gdscript
func _ready():
	var size = FileAccess.get_size("generated")
	print(size)
	var file = FileAccess.open("generated", FileAccess.READ)
	print(file.is_open())
	var buf = file.get_buffer(size)
	print(buf.size())
	var md5 = FileAccess.get_md5("generated")
	print(md5)
```

On x86_32 Linux:
```
2147483648
true
ERROR: Parameter "mem" is null.
   at: alloc_static (./core/os/memory.cpp:108)
ERROR: Parameter "mem_new" is null.
   at: resize (./core/templates/cowdata.h:367)
ERROR: Can't resize data to 2147483648 elements.
   at: get_buffer (./core/io/file_access.cpp:545)
0
a981130cf2b7e09f4686dc273cf7187e
```

On x86_64 Linux:
```
2147483648
true
2147483648
a981130cf2b7e09f4686dc273cf7187e
```

**Comment by bruvzg** [comment]
> and I'm surprised that FileAccess.get_md5 actually works for that file on x86_32

Why wouldn't it, it's reading 32 KiB at a time and file offset is always 64-bit.

**Review by Jayman2000 — APPROVED** [review]
I tested a 64-bit build of this PR on this system…

Godot v4.5.dev (35beb07ee) - Fedora Linux 41 (Workstation Edition) on Wayland - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - llvmpipe (LLVM 19.1.7, 256 bits) - AMD Ryzen 5 3600 6-Core Processor (11 threads)

…and I wasn’t able to reproduce the bug anymore!

**Comment by Repiteo** [comment]
Thanks!
