### PR TITLE
Fix toggling after scrolling resulted in blank space

### LINKED ISSUE #57356: Wrong ScrollContainer behavior with always visible scrolls when children don't need scrolling
### Godot version

38c6611

### System information

W10

### Issue description

With scroll auto, child container can be expanded to full size:
godot windows tools 64_DE0LdwRscH

Buf if scroll is always visible, the child will be shrunk to minimum size and doesn't fit to the whole container anymore:
godot windows tools 64_Fy9N7il6kn
(notice how bottom of the panel is cut)

### Steps to reproduce

1. Add ScrollContainer with some scroll set to always visible
2. Add some child container that doesn't need to be scrolled
3. Observe

### Minimal reproduction project

[control.tscn.txt](https://github.com/godotengine/godot/files/7959248/control.tscn.txt)
Press any key to see the bug.

### LINKED ISSUE #63334: Inspector, Project Settings, Editor Settings retain scroll position across nodes/tabs, sometimes resulting in a blank space
### Godot version

v4.0 master [fe929d478]

### System information

popOS, Vulkan

### Issue description

When switching between nodes in the the scene tree, the scroll position of the last selected node seems to be used to set the scroll position of the newly selected node. When the new node's inspector doesn't have a scrollbar, this can mean the inspector appears empty:

https://user-images.githubusercontent.com/61291296/180580152-4f626106-660e-4e0b-828d-6f3f6dfbe89f.mp4

(note that dropdowns etc did appear - I had the recording software set to record the window)

Showing or collapsing a section in the inspector causes it to be redrawn correctly.

The bug doesn't happen in the "Node" tab - both signals and groups display properly.

Doesn't happen in alpha 12.

### Steps to reproduce

Scroll far down in the inspector on one node, then switch to another.

### Minimal reproduction project

-

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #63334.

Previously, the data used by `update_scrollbars()` and `_update_dimensions()` in their calculations depended on each other, which caused some problems.

Now, the calculation of `child_max_size` is put into `get_minimum_size()`, as the containers call `update_minimum_size()` before calling `queue_sort()`.

Edit:
Can fix #57356.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @jasonwinterpixel @AaronRecord

File: scene/gui/scroll_container.cpp [hunk 1]
```diff
@@ -426,36 +423,32 @@ void ScrollContainer::update_scrollbars() {
...
 	// Avoid scrollbar overlapping.
-	h_scroll->set_anchor_and_offset(SIDE_RIGHT, ANCHOR_END, hide_scroll_v ? 0 : -vmin.width);
-	v_scroll->set_anchor_and_offset(SIDE_BOTTOM, ANCHOR_END, hide_scroll_h ? 0 : -hmin.height);
+	h_scroll->set_anchor_and_offset(SIDE_RIGHT, ANCHOR_END, -vmin.width);
+	v_scroll->set_anchor_and_offset(SIDE_BOTTOM, ANCHOR_END, -hmin.height);
 }
 
 void ScrollContainer::_scroll_moved(float) {
 	queue_sort();
-	update();
```
Comment (Rindbee) [inline scene/gui/scroll_container.cpp:458]: For `ScrollContainer`, `queue_sort()` will eventually cause `update()` to be called, and all information can be confirmed at once, so there is no need to call `update()`.

**Comment by AaronRecord** [comment]
Guess I should've tested https://github.com/godotengine/godot/pull/63295 more thoroughly 🙃

Thanks for the fix, will try and review when I get a chance

File: scene/gui/scroll_container.cpp [hunk 2]
```diff
@@ -50,25 +50,27 @@ Size2 ScrollContainer::get_minimum_size() const {
...
-	bool v_scroll_show = vertical_scroll_mode == SCROLL_MODE_SHOW_ALWAYS || (vertical_scroll_mode == SCROLL_MODE_AUTO && content_min_size.y > min_size.y);
-	if (h_scroll_show) {
+	bool h_scroll_show = horizontal_scroll_mode == SCROLL_MODE_SHOW_ALWAYS || (horizontal_scroll_mode == SCROLL_MODE_AUTO && child_max_size.x > min_size.x);
+	bool v_scroll_show = vertical_scroll_mode == SCROLL_MODE_SHOW_ALWAYS || (vertical_scroll_mode == SCROLL_MODE_AUTO && child_max_size.y > min_size.y);
+
+	if (h_scroll_show && h_scroll->get_parent() == this) {
 		min_size.y += h_scroll->get_minimum_size().y;
 	}
-	if (v_scroll_show) {
+	if (v_scroll_show && v_scroll->get_parent() == this) {
```
[the remark this answers is not in the document]
Comment (Rindbee) [reply scene/gui/scroll_container.cpp:73]: Mainly consistent with the one here:
https://github.com/godotengine/godot/blob/3f39625399d8a5ef118341e47500f31f21b11581/scene/gui/scroll_container.cpp#L274-L280

I'm not sure if this actually exists.

[the remark this answers is not in the document]
Comment (KoBeWi) [reply scene/gui/scroll_container.cpp:73]: We actually have one instance in the editor where this happens:
https://github.com/godotengine/godot/blob/cc09dc92c8ee06255a158d81533d35c6d2e8d31e/editor/animation_track_editor.cpp#L6268

[the remark this answers is not in the document]
Comment (AaronRecord) [reply scene/gui/scroll_container.cpp:73]: https://github.com/godotengine/godot/pull/63475

**Comment by AaronRecord** [comment]
I really don't like the naming of a lot of the variables in this code 🙃
Like here, with `min_size` and `minsize`:
https://github.com/godotengine/godot/blob/aa135e448ed133ee39c298f5996f39beba75e128/scene/gui/scroll_container.cpp#L39-L62

And here, where the terms `min` and `max` seem to be used interchangeably:
https://github.com/godotengine/godot/blob/aa135e448ed133ee39c298f5996f39beba75e128/scene/gui/scroll_container.cpp#L426-L428

if I understand the code correctly it'd be better to rename `child_max_size` to `largest_child_min_size`

File: scene/gui/scroll_container.cpp [hunk 3]
```diff
@@ -426,36 +423,32 @@ void ScrollContainer::update_scrollbars() {
 	Ref<StyleBox> sb = get_theme_stylebox(SNAME("bg"));
 	size -= sb->get_minimum_size();
 
+	Size2 min = child_max_size;
+	h_scroll->set_visible(min.width > size.width);
+	v_scroll->set_visible(min.height > size.height);
```
Comment (AaronRecord) [inline scene/gui/scroll_container.cpp:428]:
```suggestion
	h_scroll->set_visible(child_max_size.width > size.width);
	v_scroll->set_visible(child_max_size.height > size.height);
```

File: scene/gui/scroll_container.h [hunk 4]
```diff
@@ -50,7 +50,7 @@ class ScrollContainer : public Container {
 	HScrollBar *h_scroll = nullptr;
 	VScrollBar *v_scroll = nullptr;
 
-	Size2 child_max_size;
+	mutable Size2 child_max_size;
```
Comment (AaronRecord) [inline scene/gui/scroll_container.h:53]: What if this was calculated in `_update_dimensions` instead? I think that'd make more sense, and then we wouldn't need a `mutable` here (`mutable` = 😓)

**Comment by AaronRecord** [comment]
I left a few small suggestions but otherwise the changes look good 🙂

File: scene/gui/scroll_container.h (hunk 4 above)
Comment (Rindbee) [reply scene/gui/scroll_container.h:53]: It needs to traverse all the child controls to calculate it.

The main purpose of `ScrollContainer::update_scrollbars()` is to confirm the status (`max`/`page`/`visible`) of scrollbars, it needs to have determined the largest one of the minimum size of child controls (`child_max_size`).

`ScrollContainer::_update_dimensions()` mainly determines the `rect` of the child controls. The `rect` needs to be calculated according to the `value` of the `ScrollBar`s.

So in terms of dependencies, it is unlikely to calculate all the data in one loop. Two loops are required. 

For convenience, it is better to calculate in `get_minimum_size()`. As the containers call `update_minimum_size()` before calling `queue_sort()`. See `*_child_notify(Node *p_child)` in `Container`.

**Comment by Rindbee** [comment]
> if I understand the code correctly it'd be better to rename `child_max_size` to something like `largest_child_min_size` Also `_update_dimensions` should probably be renamed to something like `_resposition_children`

I think it's better to add a note. It can be confusing to have big and small at the same time.

**Review by AaronRecord — APPROVED** [review]
Looks good! The only things I might add would be a comment explaining why `largest_child_min_size` is calculated in `get_minimum_size`, and maybe one explaining why `update_scrollbars` should be called first before calculating child positions if you think it'd be helpful

**Comment by Rindbee** [comment]
The case where `*_scroll_mode` is `SCROLL_MODE_SHOW_NEVER` was previously missed. 

Now, the result of `update_scrollbars` is the same as before. The `max`/`page`/`value` of the `ScrollBar` will all be set to the appropriate value. 

Please review it again.

File: scene/gui/scroll_container.cpp [hunk 5]
```diff
@@ -291,25 +296,13 @@ void ScrollContainer::_update_dimensions() {
 			continue;
 		}
 		Size2 minsize = c->get_combined_minimum_size();
-		child_max_size.x = MAX(child_max_size.x, minsize.x);
-		child_max_size.y = MAX(child_max_size.y, minsize.y);
 
 		Rect2 r = Rect2(-Size2(get_h_scroll(), get_v_scroll()), minsize);
-		if (horizontal_scroll_mode == SCROLL_MODE_DISABLED || (!h_scroll->is_visible_in_tree() && c->get_h_size_flags() & SIZE_EXPAND)) {
-			r.position.x = 0;
```
Comment (Rindbee) [inline scene/gui/scroll_container.cpp:299]: Since `update_scrollbars() is called` first, the appropriate `max`/`page`/`value` will be set. So there is no need to reset to `0` here.

File: scene/gui/scroll_container.cpp [hunk 6]
```diff
@@ -291,25 +296,13 @@ void ScrollContainer::_update_dimensions() {
 			continue;
 		}
 		Size2 minsize = c->get_combined_minimum_size();
-		child_max_size.x = MAX(child_max_size.x, minsize.x);
-		child_max_size.y = MAX(child_max_size.y, minsize.y);
 
 		Rect2 r = Rect2(-Size2(get_h_scroll(), get_v_scroll()), minsize);
-		if (horizontal_scroll_mode == SCROLL_MODE_DISABLED || (!h_scroll->is_visible_in_tree() && c->get_h_size_flags() & SIZE_EXPAND)) {
```
Comment (Rindbee) [inline scene/gui/scroll_container.cpp:298]: When `*_scroll_mode` is `SCROLL_MODE_SHOW_NEVER`, it is always invisible. As a result, in this case, the resizing cannot be performed. 

Didn't notice before due to display issues with `clip_contents` (#63707).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
