### PR TITLE
[3.x] Make binary resource loader utilize loaded external resources

### LINKED ISSUE #80783: Binary scenes don't save instanced scenes in them
### Godot version

3.6.beta3

### System information

Ubuntu Studio 23.04

### Issue description

When saving binary scenes, references to instanced scenes are not saved. So, reopening saved scene causes loss of references to instanced scenes (only topmost node is saved, without reference). This bug is 3.x only, 3.5.2 don't have it.
Caused by: https://github.com/godotengine/godot/pull/62408

### Steps to reproduce

1. Create scene.
2. Instance another scene inside.
3. Save first scene with .scn (binary) extension.
4. Reopen it. Reference to instanced scene is lost.

https://github.com/godotengine/godot/assets/71974498/666ad675-c1da-45fe-836b-8800d9383a0a

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Razoric480**
The Binary Resource Loader would load external resources, like TSCN files, twice, and basically discard the first one. It always had a `resource_cache` property that got populated, but never actually utilized.

When the no-cache flag wasn't being passed along, that issue wasn't noticeable besides longer loading times. Once it started being taken into account, it became noticeable (though it went under the radar until now.)

Fixes #80783

### CODE REVIEW

**Review by Summersay415 — APPROVED** [review]
Can confirm what this PR fixes my bug!

**Comment by EzraT** [comment]
Thanks!

File: core/io/resource_format_binary.cpp [hunk 1]
```diff
@@ -339,7 +339,18 @@ Error ResourceInteractiveLoaderBinary::parse_variant(Variant &r_v) {
...
+						for (List<RES>::Element *E = resource_cache.front(); E; E = E->next()) {
+							if (E->get()->get_path() == path) {
+								res = E->get();
+								break;
+							}
+						}
+
+						if (res == nullptr) {
+							res = ResourceLoader::load(path, exttype, no_subresource_cache);
+						}
```
Comment (akien-mga) [inline core/io/resource_format_binary.cpp:353]: AFAIK `res` can't be `nullptr` technically, it's `Ref<Resource>` so if it's empty/invalid, it will still be a `Ref<Resource>` that passes `res.is_null()`. It just happens to work with `nullptr` as it gets casted implicitly, but it would be cleaner to just do:
``
RES res;

...

if (res.is_null()) {
```
which is consistent with the later check.

Comment (Razoric480) [reply core/io/resource_format_binary.cpp]: > AFAIK `res` can't be `nullptr` technically, it's `Ref<Resource>` so if it's empty/invalid, it will still be a `Ref<Resource>` that passes `res.is_null()`. It just happens to work with `nullptr` as it gets casted implicitly, but it would be cleaner to just do:

Fixed. Thanks

**Comment by KoBeWi** [comment]
> When the no-cache flag wasn't being passed along, that issue wasn't noticeable besides longer loading times. Once it started being taken into account, it became noticeable (though it went under the radar until now.)

Doesn't that mean the code you added should be executed only if `no_subresource_cache` is false?

**Comment by Razoric480** [comment]
> Doesn't that mean the code you added should be executed only if `no_subresource_cache` is false?

No. This variable is meant to hold external resources in a local cache between `poll()` calls.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
