### PR TITLE
Fix undo crash when animation editor is not active

### LINKED ISSUE #118945: Editor crashes if you undo an action while outside of BlendSpace1D/BlendSpace2D editors
### Tested versions

Reproducible in:
v4.7.beta1.official [1c8cc9e7e]
v4.6.stable.official [89cea1439]
v4.5.stable.official [876b29033]

### System information

Godot v4.6.stable - Windows 10 (build 19045) - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1060 3GB (NVIDIA; 32.0.15.8180) - Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 threads) - 15.95 GiB memory

### Issue description

Apparently been an issue for many versions.
If you undo the creation/deletion of a node inside BlendSpace1D/BlendSpace2D while you're NOT inside their editors, godot editor will crash. Otherwise its fine

### Steps to reproduce

https://github.com/user-attachments/assets/90e1c347-2e03-4478-855b-abd9ad195b80

1. Make any BlendTree + BlendSpace1D/BlendSpace2D setup
2. Add/delete something inside the BlendSpace1D/BlendSpace2D
3. Go up the level
4. Press Ctrl+Z. Engine will crash

### Minimal reproduction project (MRP)

[blendspaceerror_2026-04-25_09-09-58.zip](https://github.com/user-attachments/files/27079212/blendspaceerror_2026-04-25_09-09-58.zip)

### PR DESCRIPTION
**Pull request by Ryan-000**
Split from https://github.com/godotengine/godot/pull/119029
Resolves https://github.com/godotengine/godot/issues/118945

### CODE REVIEW

File: editor/animation/animation_blend_space_1d_editor.cpp [hunk 1]
```diff
@@ -408,7 +408,8 @@ void AnimationNodeBlendSpace1DEditor::_blend_space_draw() {
 }
 
 void AnimationNodeBlendSpace1DEditor::_update_space() {
-	if (updating) {
+	// edge case when undoing action after editor has changed
+	if (updating || blend_space.is_null()) {
```
Comment (TokageItLab) [inline editor/animation/animation_blend_space_1d_editor.cpp:412]:
```suggestion
	if (blend_space.is_null() || updating) {
```
I assume that performing a null check first is likely slightly more efficient.

**Review by TokageItLab — APPROVED** [review]

**Comment by TokageItLab** [comment]
Also fixes https://github.com/godotengine/godot/issues/118982 ?

File: editor/animation/animation_blend_space_1d_editor.cpp (hunk 1 above)
Comment (Ryan-000) [reply editor/animation/animation_blend_space_1d_editor.cpp:412]: I checked the generated assembly, and the difference seems negligible here.

For what it’s worth, `updating || blend_space.is_null()` looks _slightly_ better in the normal update path.

Either order is fine to me, so we can go with whichever you find more readable.

**Comment by matheusmdx** [comment]
> Also fixes #118982 ?

Unfortunatelly this PR do not fix #118982 (but fixes the target issue, #118945). They look similar but each one generate different backtraces, started in different versions and #118982 happens specifically with the first added point.


https://github.com/user-attachments/assets/73e8e34b-ec2f-487c-91d7-e11496d9c3a0

**Comment by Repiteo** [comment]
Thanks!

**Comment by Ryan-000** [comment]
> Also fixes #118982 ?

https://github.com/godotengine/godot/pull/119070 will directly resolve the crashing (I have updated that PR description to include the issue link).
